[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_000_000_00]
[s]Dummy[n][w][e]

[msg MSG_STAFF_JR_TALK_000_00 [Empleado de la estaci吋n]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]斡Lamentamos las molestias durante[n]este tiempo! La L胤nea JL est茨[n]sufriendo muchos retrasos hoy.[n][w][e]
[s][vp 8 2 1 0 851 0]夷La L胤nea Ginza? Est茨 en[n]el [clr 2]edificio Teikyu[clr 27], justo al lado.[n][w][e]

[msg MSG_STAFF_JR_GREET_000_0]
[s][vp 8 2 1 0 851 0][clr 2]Los trenes no circulan seg雨n[n]lo previsto[clr 27].[n]斡Lamentamos las molestias![n][f 1 2 65535][e]

[msg MSG_STAFF_JR_GREET_000_0_2]
[s][vp 8 2 1 0 851 0][clr 28]Los trenes no circulan seg雨n[clr 27][n][clr 28]lo previsto[clr 27].[n]斡Lamentamos las molestias![n][f 1 2 65535][e]

[msg MSG_STAFF_PARK_TALK_000_ [Empleado de la estaci吋n ocupado]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Los trenes est茨n sufriendo[n]retrasos por culpa del accidente[n]de metro de ayer.[n][w][e]
[s][vp 8 2 1 0 850 0]Para llegar a la L胤nea JL,[n]atraviesa los torniquetes que est茨n[n]a mano izquierda.[n][w][e]
[s][vp 8 2 1 0 850 0]Para ir al metro, dir胤gete[n]al distrito subterr茨neo usando[n]las escaleras centrales.[n][w][e]
[s][vp 8 2 1 0 850 0]Para llegar a la L胤nea Ginza, sube[n]por las escaleras del [clr 2]edificio Teikyu[clr 27][n]que est茨n ah胤 al lado.[n][w][e]

[msg MSG_STAFF_PARK_GREET_000]
[s][vp 8 2 1 0 850 0]斡Esta zona est茨 demasiado[n][clr 2]concurrida[clr 27] ahora mismo![n][f 1 2 65535][e]

[msg MSG_STAFF_PARK_GREET_000_2]
[s][vp 8 2 1 0 850 0]斡Esta zona est茨 demasiado[n][clr 2]concurrida[clr 27] ahora mismo![n][f 1 2 65535][e]

[msg MSG_STAFF_STBLDG_TALK_00 [Asistente somnoliento]]
[s][f 4 23 1 852 3 10 0 0][vp 8 2 1 0 852 0]斡Las escaleras que llevan abajo[n]est茨n muy concurridas![n][w][e]
[s][vp 8 2 1 0 852 0]Recomiendo que uses[n]las centrales si tienes[n]que coger el metro.[n][w][e]
[s][vp 8 2 1 0 852 0]Ayer tambi姻n me toc吋[n]quedarme hasta tarde.[n]Necesito un descanso... *bostezo*[n][w][e]
[s][vp 8 2 1 0 852 0]La L胤nea JL est茨 a la derecha de[n]la plaza. La L胤nea Ginza est茨[n][clr 2]subiendo estas escaleras[clr 27].[n][w][e]

[msg MSG_STAFF_STBLDG_GREET_0]
[s][vp 8 2 1 0 852 0]Las escaleras que llevan abajo[n]est茨n muy[clr 2]concurridas[clr 27] ahora mismo.[n][f 1 2 65535][e]

[msg MSG_STAFF_STBLDG_GREET_0_2]
[s][vp 8 2 1 0 852 0]Las escaleras que llevan abajo[n]est茨n muy[clr 2]concurridas[clr 27] ahora mismo.[n][f 1 2 65535][e]

