[sel YESNO_SEL top]
[s]S胤.[e]
[s]No.[e]

[msg MSG_794_101_00]
[s]Dummy[n][w][e]

[msg MSG_NPC_RYUJI_000_00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Eh, ah胤 est茨s![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]C吋mo mola esta tienda, 夷no?[n]Vamos a entrar, anda.[n][w][e]

[msg SYS_ALPHA1_000_00]
[s]Despu姻s, tiene lugar un evento.[n]El tiempo corre cuando termina. [n][w][e]
[s]Todav胤a no hay eventos,[n]as胤 que el tiempo correr茨 despu姻s.[n][w][e]

