[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_000_000_00]
[s]Dummy[n][w][e]

[msg MSG_E24320100_001_00 [Estudiante empoll吋n]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]No me importa lo de la mafia.[n]Yo solo s姻 que la polic胤a[n]deber胤a arrestarlos a todos.[n][w][e]
[s][vp 8 2 1 0 850 0]No es normal que nos pidan[n]que no vayamos a Shibuya.[n]Yo tengo clase all胤.[n][w][e]

[msg MSG_E24320100_002_00 [Estudiante mezquino]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]Es que menuda tonter胤a.[n]Los de la mafia no son m茨s que una[n]panda de in雨tiles sin oficio, 夷no?[n][w][e]
[s][vp 8 2 1 0 851 0]Si quieren ser delincuentes, pues[n]bien por ellos, pero a m胤 que[n]me dejen en paz.[n][w][e]

