[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_000_000_00]
[s]Dummy[n][w][e]

[msg MSG_E24330100_MAN_001_00 [Hombre alto]]
[s][vp 8 2 1 0 850 0]斡Te dije que era una pasada![n]斡D茨melo, r茨pido![n][w][e]
[s][vp 8 2 1 0 850 0]He o胤do que es muy eficaz.[n]Cualquier desierto se convierte[n]en un frondoso bosque de pelo.[n][w][e]

[msg MSG_E24330100_MAN_002_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Esa era la persona de la que[n]hablaba Ryuji. Un bosque frondoso...[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]No quiero saber nada m茨s.[n]Entiendo por qu姻 lo has confundido[n]con la gente a la que buscamos.[n][w][e]

[msg MSG_E24330100_MAN_102_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Deber胤amos pasar de 姻l.[n]Busquemos en otro sitio.[n][w][e]

[msg MSG_E24330100_RYUJI_001_ [Anciana amable]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]Hola, joven.[n]夷Podr胤as indicarme por d吋nde[n]se va a la l胤nea Inogami?[n][w][e]

[msg MSG_E24330100_RYUJI_002_ [Ryuji]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Ehh, baje las escaleras y luego[n]gire a la izquierda.Tenga cuidado, abuela.[n][w][e]

[msg MSG_E24330100_RYUJI_003_ [Anciana amable]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]Jo, Shibuya tiene tela.[n]Estos huesos ya no se mueven[n]como antes. Qu姻 desgracia.[n][w][e]

[msg MSG_E24330100_RYUJI_004_ [Ryuji]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Uf, venga...[n][w][e]

[msg MSG_E24330100_RYUJI_005_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7088 65535 0]Eh, [f 4 2].[n][w][e]

[msg MSG_E24330100_RYUJI_006_ [Ryuji]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lo siento, al final lo que dije[n]no sirvi吋 para nada.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ese tipo de las escaleras...[n]Como para no liarse.[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oye, 夷y Ann y Yusuke?[n]Vamos a ver c吋mo van.[n][w][e]

[msg MSG_E24330100_RYUJI_007_ [Ryuji]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Abuela, 夷todo en orden?[n]La veo un poco nerviosa.[n]Si quiere, le echo una mano.[n][w][e]

[msg MSG_E24330100_RYUJI_101_ [Anciana amable]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]Qu姻 pelo tan bonito tienes,[n]jovencito. Y tambi姻n buen coraz吋n.[n][w][e]

[msg MSG_E24330100_RYUJI_102_ [Ryuji]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 7022 65535 0]Vaya, gracias. Ando un poco[n]perdido, la verdad...[n][w][e]

[msg MSG_E24330100_RYUJI_103_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 1172 0 0]Dice que la pista que ten胤a[n]al final no era nada.[n]Dej姻mosle esta zona, 夷vale?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Venga, vamos a ver[n]a la se隠orita Ann y a Yusuke.[n][w][e]

