[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_TOBIORI_GAYA_grt_A_0]
[s]斡Ser茨 una broma![n]斡夷Fue un accidente?! 斡No me[n]digas que fue un suicidio![n][f 1 2 65535][e]

[msg MSG_TOBIORI_NPC_01 [Estudiante decepcionado]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]No lo vi... 夷De veras[n]salt吋 del tejado?[n][w][e]

[msg MSG_TOBIORI_NPC_02 [Estudiante fren姻tico]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]斡Cay吋 como un juguete![n]Estar茨 muerta a estas alturas.[n][w][e]

