[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_401_102_00]
[s]Dummy[n][w][e]

[msg MSG_NPC_800_00 [Anciano sorprendido]]
[s][f 4 23 1 800 3 10 0 0][vp 8 2 1 0 800 0]夷Shido? 斡夷Shido?![n][w][e]

[msg MSG_NPC_801_00 [Ama de casa emocionada]]
[s][f 4 23 1 801 3 10 0 0][vp 8 2 1 0 801 0]斡夷Est茨 aqu胤?! 斡夷D吋nde?![n][w][e]

[msg MSG_NPC_802_00 [Joven emocionado]]
[s][f 4 23 1 802 3 10 0 0][vp 8 2 1 0 802 0]斡Hala, es incre胤ble![n]斡Vamos a ver![n][w][e]

[msg MSG_NPC_Family_00 [Ni隠o curioso]]
[s][f 4 23 1 803 3 10 0 0][vp 8 2 1 0 803 0]夷Ese es Shido?[n][w][e]

[msg MSG_NPC_Family_01 [Madre joven]]
[s][f 4 23 1 804 3 10 0 0][vp 8 2 1 0 804 0]S胤. 斡Es un hombre[n]fuerte y admirable![n][w][e]

[msg MSG_NPC_Family_02 [Ni隠o curioso]]
[s][f 4 23 1 803 3 10 0 0][vp 8 2 1 0 803 0]夷M茨s que pap茨?[n][w][e]

[msg MSG_NPC_Family_03 [Padre callado]]
[s][f 4 23 1 805 3 10 0 0][vp 8 2 1 0 805 0]Mmm, bueno, dir胤a que s胤.[n]Shido es una persona maravillosa.[n][w][e]

[msg MSG_NPC_YUSUKE_00 [Yusuke]]
[s][f 4 23 1 856 3 10 0 10][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 4198 856 0]Si vamos todos juntos, llamaremos[n]demasiado la atenci吋n. Investiga[n]por tu cuenta, [f 4 2].[n][w][e]

[msg MSG_NPC_FUTABA_00 [Futaba]]
[s][f 4 23 1 854 3 10 0 10][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9176 854 0]Me quedar姻 por aqu胤[n]haciendo tiempo.[n][w][e]

[msg MSG_NPC_MAKOTO_00 [Makoto]]
[s][f 4 23 1 852 3 10 0 10][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2047 852 0]Conque puede que el responsable[n]de la muerte del padre de Haru est姻[n]libre. Mira a ver, [f 4 2].[n][w][e]

[msg MSG_NPC_ANN_00 [Ann]]
[s][f 4 23 1 855 3 10 0 10][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 6022 855 0]Espero que Ryuji[n]no haga de las suyas.[n][w][e]

