[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_000_000_00]
[s]Dummy[n][w][e]

[msg MSG_E22810101_000_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Ese tal Akechi parece[n]bastante influyente, pero un d胤a[n]le haremos tragarse sus palabras...[n][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]En fin, mejor olvidarse de 姻l y[n]centrarse en divertirse por ahora.[n]Venga, hay que prepararse.[n][w][e]

[msg MSG_E22810101_001_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ah, por cierto...[n]夷qui姻n va a sazonar el estofado?[n][w][e]

