[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_001_0_0 [Estudiante educado]]
[s][bup 0 111 504 65535 0][f 4 10 65535 0 0][vp 8 2 1 19102 853 0]斡夷Qu姻?![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 853 0]夷Q-qu姻 quieres de m胤?[n][w][e]

[sel MSG_002_SEL top]
[s]夷D吋nde est茨 la azotea?[e]
[s]No importa.[e]

[msg MSG_003_0_0 [Estudiante educado]]
[s][f 4 23 1 853 3 10 0 0][bup 0 111 500 65535 0][f 4 10 65535 0 0][vp 8 2 1 19044 853 0]Si subir no est茨 permitido.[n][w][e]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 853 0]En fin...[n]Tan solo sube esas escaleras.[n][w][e]

[msg MSG_003_0_1 [Estudiante educado]]
[s][f 4 23 1 853 3 10 0 0][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 853 0]Uy, me has asustado.[n][w][e]

[msg MSG_004_0_0 [Estudiante educado]]
[s][f 4 23 1 853 3 10 0 0][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 19064 853 0]A-ah, no es nada.[n][w][e]

[msg MSG_005_0_0 [Estudiante educado]]
[s][bup 0 111 505 65535 0][f 4 10 65535 0 0][vp 8 2 1 19027 853 0]夷N-necesitas algo m茨s?[n][w][e]

[msg MSG_006_0_0 [Estudiante educado]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 853 0]V-vale...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 853 0]Yo... Lo siento, pero llego tarde[n]a mi club.[n][w][e]

[msg MSG_E12310100_MISHIMA_gr]
[s][clr 2]Clubs del instituto[clr 27]...[n][f 1 2 65535][e]

[msg MSG_E12310100_MISHIMA_gr_2]
[s][clr 28]Clubs del instituto[clr 27]...[n][f 1 2 65535][e]

[msg MSG_007_0_0 [Miembro del club del peri吋dico]]
[s][vp 8 2 1 0 854 0]Mmm... 夷Qu姻 deber胤a tratar[n]en el pr吋ximo n雨mero?[n]Ojal茨 tuviera algo interesante.[n][w][e]

[sel SEL_008_0_0 top]
[s]夷Sobre el castillo?[e]
[s]夷Sobre el alumno nuevo?[e]
[s]Deber胤as rendirte.[e]

[msg MSG_009_0_0 [Miembro del club del peri吋dico]]
[s][vp 8 2 1 0 854 0]斡Ah! 斡夷Qu姻?![n][w][e]
[s][vp 8 2 1 0 854 0]夷Un castillo?[n]夷Como uno de esos antiguos[n]de la era Sengoku?[n][w][e]
[s][vp 8 2 1 0 854 0]Lo siento, no s姻[n]de qu姻 me est茨s hablando.[n][w][e]

[msg MSG_010_0_0 [Miembro del club del peri吋dico]]
[s][vp 8 2 1 0 854 0]斡Ah! 斡夷Qu姻?![n][w][e]
[s][vp 8 2 1 0 854 0]夷Te refieres a ese del que hablan[n]sin parar en internet?[n][w][e]
[s][vp 8 2 1 0 854 0]Alcohol, tabaco, robos, violencia...[n]Ning雨n profesor le dar胤a el visto[n]bueno a un art胤culo como ese.[n][w][e]

[msg MSG_011_0_0 [Miembro del club del peri吋dico]]
[s][vp 8 2 1 0 854 0]斡Ay, me has asustado![n]夷Y t雨 qui姻n eres? Creo que[n]nunca te hab胤a visto antes.[n][w][e]
[s][vp 8 2 1 0 854 0]Y, en teor胤a, pronto llega[n]ese terrible estudiante de fuera...[n]No, no puede ser.[n][w][e]
[s][vp 8 2 1 0 854 0]Se supone que es violento, bebe,[n]fuma, roba y lastima a los dem茨s...[n]Todo lo contrario a ti.[n][w][e]

[msg MSG_009_1_0 [Miembro del club del peri吋dico]]
[s][vp 8 2 1 0 854 0]斡Ah! 斡夷Qu姻?![n][w][e]

[msg MSG_009_1_1 [Miembro del club del peri吋dico]]
[s][vp 8 2 1 0 854 0]夷Un castillo?[n]夷Como uno de esos antiguos[n]de la era Sengoku?[n][w][e]
[s][vp 8 2 1 0 854 0]Lo siento, no s姻[n]de qu姻 me est茨s hablando.[n][w][e]

[msg MSG_010_1_0 [Miembro del club del peri吋dico]]
[s][vp 8 2 1 0 854 0]斡Ah! 斡夷Qu姻?![n][w][e]

[msg MSG_010_1_1 [Miembro del club del peri吋dico]]
[s][vp 8 2 1 0 854 0]夷Te refieres a ese del que hablan[n]sin parar en internet?[n][w][e]
[s][vp 8 2 1 0 854 0]Alcohol, tabaco, robos, violencia...[n]Ning雨n profesor le dar胤a el visto[n]bueno a un art胤culo como ese.[n][w][e]

[msg MSG_011_1_0 [Miembro del club del peri吋dico]]
[s][vp 8 2 1 0 854 0]斡Ah! 斡Me has asustado![n]夷Qui姻n eres? [n][w][e]

[msg MSG_011_1_1 [Miembro del club del peri吋dico]]
[s][vp 8 2 1 0 854 0]Nunca te hab胤a visto por aqu胤.[n][w][e]
[s][vp 8 2 1 0 854 0]Y, en teor胤a, pronto llega[n]ese terrible estudiante de fuera...[n]No, no puede ser.[n][w][e]
[s][vp 8 2 1 0 854 0]Se supone que es violento, bebe,[n]fuma, roba y lastima a los dem茨s...[n]Todo lo contrario a ti.[n][w][e]

[msg MSG_E12310100_SINBUN_grt]
[s]夷No hay [clr 2]temas[clr 27] interesantes[n]sobre los que escribir?[n][f 1 2 65535][e]

[msg MSG_E12310100_SINBUN_grt_2]
[s]Me pregunto si hay alg雨n [clr 28]tema[n]interesante[clr 27] sobre el que escribir.[n][f 1 2 65535][e]

[msg MSG_021_0_0 [Alumna herida]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]夷Qu姻? 夷Eres el nuevo estudiante[n]de la clase D?[n][w][e]

[sel SEL_022_0_0 top]
[s]Me has reconocido, qu姻 sorpresa.[e]
[s]Te equivocas de persona.[e]

[msg MSG_023_0_0 [Alumna herida]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Bueno, todo el mundo ha estado[n]hablando de ti.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Pero no te preocupes[n]por los rumores, tan solo nos[n]ha pillado a todos por sorpresa.[n][w][e]

[msg MSG_023_1_0 [Alumna herida]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]夷Eh? No tienes que mentir.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Por cierto, olv胤date[n]de los rumores. Si no hay pruebas,[n]no me los creo.[n][w][e]

[msg MSG_024_0_0 [Alumna herida]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Tambi姻n hay muchos[n]que se meten con mi mejor amiga[n]por su aspecto.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 855 0]No puedes juzgar a alguien[n]solo por eso, 夷no crees?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Bueno, si alguna vez necesitas[n]ayuda, solo tienes que pedirla.[n][w][e]

[sel SEL_025_0_0 top]
[s]夷D吋nde est茨 la azotea?[e]
[s]夷Por qu姻 est茨s herida?[e]

[msg MSG_026_0_0 [Alumna herida]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Est茨 subiendo estas escaleras.[n][w][e]

[msg MSG_026_1_0 [Alumna herida]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]夷Qu姻...? Ah, s胤.[n]Es del entrenamiento de voleibol.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Estoy bien. No te preocupes por m胤.[n][w][e]

[msg MSG_027_0_0 [Alumna herida]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Perd吋n por interrumpirte,[n]pero tengo que ir al entrenamiento.[n]Nos vemos.[n][w][e]

[msg MSG_028_0_0 [Alumna herida]]
[s][f 4 23 1 855 3 10 0 0][bup 0 212 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Debo darme prisa e ir a entrenar,[n]me meter姻 en problemas[n]si llego tarde...[n][w][e]
[s][vp 1 0 0 0 0 0]...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 855 0]Si huyo,[n]夷se acabar茨n mis problemas?[n][w][e]

[msg MSG_E12310100_ANNE_FRIEN]
[s][clr 2]Ann[clr 27]...[n][f 1 2 65535][e]

[msg MSG_E12310100_ANNE_FRIEN_2]
[s][clr 28]Ann[clr 27]...[n][f 1 2 65535][e]

[msg MSG_040_0_0 [Alumna despreocupada]]
[s][f 4 23 1 856 3 10 0 0][vp 8 2 1 0 856 0]夷Tener antecedentes no es algo[n]muy grave? 夷Por qu姻 lo han dejado[n]venir a nuestro instituto?[n][w][e]

[msg MSG_041_0_0 [Estudiante t胤mida]]
[s][f 4 23 1 857 3 10 0 0][vp 8 2 1 0 857 0]Todo el mundo le tiene miedo...[n]Espero que lo expulsen pronto.[n][w][e]

[msg MSG_042_0_0 [Alumna despreocupada]]
[s][f 4 23 1 856 3 10 0 0][vp 8 2 1 0 856 0]Nuestro instituto est茨 plagado[n]de gente problem茨tica. 夷No pas吋[n]algo similar el a隠o pasado?[n][w][e]

[msg MSG_043_0_0 [Estudiante t胤mida]]
[s][f 4 23 1 857 3 10 0 0][vp 8 2 1 0 857 0]*suspiro* En teor胤a,[n]este es un instituto de 姻lite.[n]Ojal茨 lo solucionen pronto.[n][w][e]

