[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_193_104_REPORTER_00 [Periodista intr姻pida]]
[s][f 4 23 1 801 3 10 0 0][vp 8 2 1 0 801 0]Disculpe, ha ido a la exposici吋n[n]del se隠or Madarame, 夷verdad? 夷Puedo[n]preguntarle qu姻 le ha parecido?[n][w][e]

[msg MSG_193_104_REPORTER_01 [Hombre que parece satisfecho]]
[s][f 4 23 1 800 3 10 0 0][vp 8 2 1 0 800 0]Ah, 斡magn胤fica![n]Todas y cada una de las obras[n]eran admirables.[n][w][e]
[s][vp 8 2 1 0 800 0]El se隠or Madarame es el orgullo[n]del arte japon姻s. Tiene un talento[n]enorme, y adem茨s es muy humilde.[n][w][e]

[msg MSG_193_104_REPORTER_02 [Periodista intr姻pida]]
[s][f 4 23 1 801 3 10 0 0][vp 8 2 1 0 801 0]Ayer se inaugur吋 la exposici吋n[n]personal del se隠or Madarame,[n]y ya es todo un 姻xito.[n][w][e]
[s][vp 8 2 1 0 801 0]Como era de esperar, es[n]casi imposible conseguir entrada.[n]Devolvemos la conexi吋n, Ken.[n][w][e]

[msg MSG_193_104_WOMEN_00 [Mujer muy perfumada]]
[s][f 4 23 1 803 3 10 0 0][vp 8 2 1 0 803 0]斡La exposici吋n de Madarame era[n]maravillosa! Es el mejor, sin duda.[n][w][e]
[s][vp 8 2 1 0 803 0]Lo 雨nico malo es que[n]hab胤a mucha gente y me gustar胤a[n]haber estado all胤 m茨s tiempo.[n][w][e]

[msg MSG_193_104_WOMEN_01 [Mujer con pinta de rica]]
[s][f 4 23 1 804 3 10 0 0][vp 8 2 1 0 804 0]S胤, empez吋 a llenarse de gente[n]que ni siquiera es muy fan del arte[n]desde que se anunci吋 por la tele.[n][w][e]

[msg MSG_193_104_WOMEN_02 [Mujer muy perfumada]]
[s][f 4 23 1 803 3 10 0 0][vp 8 2 1 0 803 0]Ojal茨 tuviera uno en casa para[n]poder disfrutarlo siempre. Igual[n]le pido a mi marido que lo compre.[n][w][e]

[msg MSG_193_104_LADIES_00 [Mujer dubitativa]]
[s][f 4 23 1 805 3 10 0 0][vp 8 2 1 0 805 0]夷Crees que me gustar茨 la exposici吋n[n]de Madarame? No s姻 mucho de arte.[n][w][e]

[msg MSG_193_104_LADIES_01 [Mujer intelectual]]
[s][f 4 23 1 806 3 10 0 0][vp 1 0 0 0 0 0][f 4 25 1 806 0 0]Tranquila,[n]no hace falta pensar mucho.[n]Su obra se 或siente位 nada m茨s verla.[n][w][e]
[s][vp 1 0 0 0 0 0][f 4 25 1 806 0 0]La pasi吋n que imprime el se隠or[n]Madarame en su obra es innegable.[n]Seguro que t雨 tambi姻n la percibes.[n][w][e]

[msg MSG_193_104_LADIES_02 [Mujer dubitativa]]
[s][f 4 23 1 805 3 10 0 0][vp 8 2 1 0 805 0]Ah, vale. En la tele tambi姻n hablan[n]maravillas de esta exposici吋n.[n]斡Qu姻 emoci吋n![n][w][e]

[msg MSG_193_104_COUPLE_00 [Hombre ap茨tico]]
[s][f 4 23 1 807 3 10 0 0][vp 8 2 1 0 807 0]夷De repente quieres ver[n]la exposici吋n de Madarame?[n]Venga ya, si no te gusta el arte.[n][w][e]

[msg MSG_193_104_COUPLE_01 [Mujer a la moda]]
[s][f 4 23 1 808 3 10 0 0][vp 8 2 1 0 808 0]Pero 斡todo el mundo habla de ella![n]斡Compra las entradas en alguna[n]subasta por internet o algo![n][w][e]

[msg MSG_193_104_COUPLE_02 [Hombre ap茨tico]]
[s][f 4 23 1 807 3 10 0 0][vp 8 2 1 0 807 0]Pero 夷qu姻 dices?[n]夷T雨 sabes lo que cuestan?[n]Adem茨s, va a estar a reventar.[n][w][e]
[s][vp 8 2 1 0 807 0]斡Y t雨 te quejabas de las colas[n]de Destinyland! Pues la exposici吋n[n]de Madarame va a ser mucho peor.[n][w][e]

[msg MSG_support_mes01 [Hombre ap茨tico]]
[s]斡夷Vamos andando?![n]斡夷Hay que andar a雨n m茨s[n]despu姻s de coger el tren?![n][f 1 2 57][e]

[msg MSG_support_mes02 [Hombre ap茨tico]]
[s]斡Deja de quejarte y en marcha![n][f 1 2 47][e]

[msg MSG_support_mes03 [Hombre ap茨tico]]
[s]夷Vive justo en el centro?[n]Vaya, no esperaba menos[n]de todo un maestro como 姻l.[n][f 1 2 57][e]

