[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_000_000_00]
[s]Dummy[n][w][e]

[msg MSG_E24320100_NISHIYAMA_ [Nishiyama]]
[s][vp 8 0 1 1 850 0]夷Nishiyama? Soy yo.[n][w][e]
[s][vp 8 0 1 2 850 0]T雨 eres el nuevo ese, 夷no?[n]夷Quieres algo?[n][w][e]

[sel SEL_E24320100_NISHIYAMA_ top]
[s]夷Qu姻 le ha pasado a Iida?[e]
[s]夷Qu姻 es eso de un trabajo?[e]

[msg MSG_E24320100_NISHIYAMA__2 [Nishiyama]]
[s][vp 8 0 1 3 850 0]夷Iida? 夷Y t雨 c吋mo sabes eso?[n][w][e]

[msg MSG_E24320100_NISHIYAMA__3 [Nishiyama]]
[s][vp 8 0 1 4 850 0]夷Un trabajo?[n][w][e]
[s][vp 8 0 1 5 850 0]夷Te refieres a lo de esa vez?[n]N-no s姻, yo dije[n]que no quer胤a hacerlo...[n][w][e]
[s][vp 8 0 1 6 850 0]F-fue cosa de Iida... 斡Oye![n][w][e]

[msg MSG_E24320100_NISHIYAMA__4 [Nishiyama]]
[s][f 4 23 1 850 0 20 0 0][vp 8 0 1 7 850 0]夷Le has hecho algo?[n]郁ltimamente est茨 muy raro.[n][w][e]

[sel SEL_E24320100_NISHIYAMA__2 top]
[s]Ya me lo puedes ir contando todo.[e]
[s]Quiero ayudarlo.[e]

[msg MSG_E24320100_NISHIYAMA__5 [Nishiyama]]
[s][f 4 23 1 850 3 10 0 0][vp 8 0 1 8 850 0]V-vale, har姻 lo que quieras,[n]pero no me hagas da隠o, por favor.[n][w][e]

[msg MSG_E24320100_NISHIYAMA__6 [Nishiyama]]
[s][f 4 23 1 850 3 10 0 0][vp 8 0 1 9 850 0]夷A-a qu姻 te refieres?[n]夷Est茨 metido en algo turbio?[n][w][e]

[sel SEL_E24320100_NISHIYAMA__3 top]
[s]Cu姻ntame m茨s.[e]
[s]Dime todo lo que sabes.[e]

[msg MSG_E24320100_NISHIYAMA__7 [Nishiyama]]
[s][f 4 23 1 850 3 10 0 0][vp 8 0 1 10 850 0]Un d胤a fui con 姻l a Shibuya[n]y se nos acerc吋 un hombre[n]cerca de la calle principal.[n][w][e]
[s][vp 8 0 1 11 850 0]Nos pregunt吋 si nos interesaba[n]un trabajillo a cambio de dinero f茨cil.[n][w][e]
[s][vp 8 0 1 12 850 0]Yo dije que no, pero Iida[n]parec胤a interesado. Le pregunt吋[n]un mont吋n de cosas.[n][w][e]

[sel SEL_E24320100_NISHIYAMA__4 top]
[s]夷En qu姻 consist胤a el trabajo?[e]
[s]夷Cu茨nto dinero os ofreci吋?[e]

[msg MSG_E24320100_NISHIYAMA__8 [Nishiyama]]
[s][f 4 23 1 850 3 10 0 0][vp 8 0 1 13 850 0]P-pues no s姻. Ten胤a tanto[n]miedo que me fui a casa solo.[n][w][e]
[s][vp 8 0 1 14 850 0]Seg雨n Iida, se tarda diez minutos[n]y es perfecto para gente que[n]no llama la atenci吋n.[n][w][e]

[msg MSG_E24320100_NISHIYAMA__9 [Nishiyama]]
[s][f 4 23 1 850 3 10 0 0][vp 8 0 1 15 850 0]P-pues no s姻. Ten胤a tanto[n]miedo que me fui a casa solo.[n][w][e]
[s][vp 8 0 1 16 850 0]Solo s姻 que 或se tarda diez minutos位[n]y 或es perfecto para gente que[n]no llama la atenci吋n位.[n][w][e]

[sel SEL_E24320100_NISHIYAMA__5 top]
[s]夷Qu姻 pas吋 despu姻s?[e]
[s]夷Algo m茨s?[e]

[msg MSG_E24320100_NISHIYAMA__10 [Nishiyama]]
[s][f 4 23 1 850 3 10 0 0][vp 8 0 1 17 850 0]Iida empez吋 a gastar[n]un mont吋n y a comportarse[n]de forma extra隠a.[n][w][e]
[s][vp 8 0 1 18 850 0]Pero no s姻 nada m茨s.[n]夷Te basta con eso?[n][w][e]

[msg MSG_E24320100_NISHIYAMA__11 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 1 19 65535 0]Un hombre en la calle principal, 夷eh?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 20 65535 0]Qu姻 sospechoso... Igual lo estaba[n]obligando a cometer delitos.[n][w][e]

[msg MSG_E24320100_NISHIYAMA__12 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 1 21 65535 0]Eso quiere decir que el trabajo tiene[n]que ver con actividades delictivas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 22 65535 0]Se tarda diez minutos, es perfecto[n]para gente que no llama la atenci吋n[n]y se usa un sobre...[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 1 23 65535 0]夷Te suena de algo? Parece[n]un asunto de la mafia, desde luego.[n][w][e]

[msg MSG_E24320100_NISHIYAMA__13 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]Mmm, 夷alguna otra idea?[n]Algo que encaje con la mafia.[n][w][e]

[sel SEL_E24320100_NISHIYAMA__6 top]
[s]Asesinato.[e]
[s]Fraude.[e]
[s]Prostituci吋n.[e]
[s]Drogas.[e]

[msg MSG_E24320100_NISHIYAMA__14 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 1 25 65535 0]夷Eso qu姻 tiene que ver con sobres?[n]Y llama bastante la atenci吋n.[n][w][e]

[msg MSG_E24320100_NISHIYAMA__15 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 1 26 65535 0]Al parecer, la mafia est茨 detr茨s[n]de todas esas estafas.[n]夷Igual los sobres son para mover dinero?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 27 65535 0]Pero son muy peque隠os. No creo[n]que quepan grandes fajos de billetes.[n][w][e]

[msg MSG_E24320100_NISHIYAMA__16 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 1 28 65535 0]夷Eso qu姻 tiene que ver con sobres?[n]Y llama bastante la atenci吋n.[n][w][e]

[msg MSG_E24320100_NISHIYAMA__17 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]夷Drogas ilegales? Igual ten胤an[n]a Iida traficando para ellos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 30 65535 0]En ese caso, el sobre encaja,[n]y pueden arrestarte[n]solo por posesi吋n.[n][w][e]

[msg MSG_E24320100_NISHIYAMA__18 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 1 31 65535 0]As胤 que anda traficando...[n]La cosa se va a poner fea.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]Venga, vamos a volver con la se隠orita Ann[n]y le preguntamos directamente a Iida.[n][w][e]

[msg MSG_E24320100_NISHIYAMA__19 [Nishiyama]]
[s][f 4 23 1 850 3 10 20 10][vp 8 2 1 0 850 0]D姻jame en paz. Si quieres saber[n]m茨s, ve a hablar con Iida.[n][w][e]
[s][vp 8 2 1 0 850 0]No s姻 qu姻 es lo que pretendes,[n]pero ni se te ocurra decirle[n]que te lo cont姻 yo.[n][w][e]

[msg MSG_E24320100_NISHIYAMA__20 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Venga, vamos a volver con la se隠orita Ann[n]y le preguntamos directamente a Iida.[n][w][e]

