[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_000_000_00]
[s]Dummy[n][w][e]

[msg MSG_STUDENT_F_851_000_00 [Estudiante atormentada]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]Ha habido otro extra隠o accidente.[n][w][e]
[s][vp 8 2 1 0 851 0]Esta vez ha sido en el metro.[n]Menos mal que fue un domingo[n]o me habr胤a pillado a m胤 tambi姻n.[n][w][e]

[msg MSG_STUDENT_F_850_001_00 [Estudiante con nervios]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Qu姻 miedo... 夷Cu茨nto tiempo tendremos[n]que sufrir los accidentes?[n][w][e]

[msg MSG_STUDENT_F_850_100_00 [Estudiante con nervios]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Vamos, hay que darse prisa.[n]Est茨 empezando a llover.[n][w][e]

[msg MSG_STUDENT_F_851_101_00 [Estudiante atormentada]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]Justo hoy he salido sin paraguas.[n]Me habr姻 levantado[n]con el pie izquierdo.[n][w][e]

