[msg MSG_TEACHER_001_00 [Profesor con gafas]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Ya no puedo recomendarte a esa[n]universidad. Al final hemos optado[n]por otro alumno.[n][w][e]

[msg MSG_TEACHER_002_00 [Estudiante asustado]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]斡夷Qu姻?! Pero me hab胤ais prometido[n]que me recomendar胤ais a m胤.[n][w][e]

[msg MSG_TEACHER_003_00 [Profesor con gafas]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Lo siento, pero tienes que entender[n]que esta decisi吋n ha sido tomada[n]por el instituto.[n][w][e]
[s][vp 8 2 1 0 850 0]Quieren darle prioridad a nuestro[n]famoso equipo de voleibol.[n][w][e]

[msg MSG_ZENKAZENREKI_001_00 [Estudiante inquieto]]
[s][f 4 23 1 852 3 10 0 0][vp 8 2 1 0 852 0]夷De verdad aceptan a criminales[n]en el instituto? Yo no quiero[n]ir a clase con alguien como 姻l.[n][w][e]

[msg MSG_ZENKAZENREKI_002_00 [Alumno muy nervioso]]
[s][f 4 23 1 853 3 10 0 0][vp 8 2 1 0 853 0]夷Es un criminal a pesar de ser[n]menor de edad? Bueno, lo que cuenta[n]es que es peligroso.[n][w][e]
[s][vp 8 2 1 0 853 0]Le hab胤an acusado de agresi吋n, 夷no?[n]Seguro que tiene unas pintas[n]de a雨pa.[n][w][e]

[msg MSG_ZENKAZENREKI_003_00 [Estudiante inquieto]]
[s][f 4 23 1 852 3 10 0 0][vp 8 2 1 0 852 0]El instituto deber胤a expulsarlo ya.[n]Es una bomba de relojer胤a[n]a punto de estallar.[n][w][e]

