[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_NPC_850 [Hombre del barrio]]
[s][vp 8 2 1 0 850 0]夷Futaba?[n][w][e]
[s][vp 8 2 1 0 850 0]No. No, no me suena de nada.[n][w][e]

[msg MSG_NPC_851 [Anciano sensato]]
[s][vp 8 2 1 0 851 0]夷Futaba? 夷Qui姻n es? No[n]conozco a nadie que se llame as胤.[n][w][e]
[s][vp 8 2 1 0 851 0]Mm, 夷no le molestar胤a a Futaba[n]enterarse de que andas cotilleando[n]para saber qui姻n es?[n][w][e]

[msg MSG_NPC_852 [Anciano aturdido]]
[s][vp 8 2 1 0 852 0]夷Futaba? Futaba...[n]S胤, ese nombre me suena.[n]Lo he o胤do en alguna parte.[n][w][e]
[s][vp 1 0 0 0 0 0]...[n][w][e]
[s][vp 8 2 1 0 852 0]斡Ah, s胤! As胤 se llamaba[n]la profesora por la que estaba[n]colado en primaria.[n][w][e]

[msg MSG_NPC_852_MOR [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 1178 0 0]関係ねえな。[n][w][e]

[msg MSG_NPC_853 [Ama de casa del barrio]]
[s][vp 8 2 1 0 853 0]El se隠or Sakura est茨 soltero, 夷no?[n]Cre胤a que no ten胤a hijos.[n][w][e]

[msg MSG_NPC_854_00 [Comprador]]
[s][vp 8 2 1 0 854 0]夷Futaba? A saber.[n][w][e]
[s][vp 8 2 1 0 854 0]Por cierto, 夷comes mucho?[n][w][e]

[sel SEL_NPC_854_0 top]
[s]夷De qu姻 hablas?[e]
[s]Oye, que estoy creciendo.[e]
[s]La verdad es que no.[e]

[msg MSG_NPC_854_01a [Comprador]]
[s][vp 8 2 1 0 854 0]Es que cuando el Jefe[n]compra comida,[n]es m茨s que suficiente para tres.[n][w][e]

[msg MSG_NPC_854_01b [Comprador]]
[s][vp 8 2 1 0 854 0]Si est茨is solo los dos, veo que[n]comes m茨s que de sobra.[n]Eres de buen comer, 夷verdad?[n][w][e]

[msg MSG_NPC_854_02 [Comprador]]
[s][vp 8 2 1 0 854 0]夷Qu姻? 夷Que no comes tanto, dices?[n]Ser茨 el Jefe, entonces.[n][w][e]

[msg MSG_NPC_855 [Repartidor]]
[s][vp 8 2 1 0 855 0]夷Futaba?[n]No, no conozco a nadie[n]que se llame as胤.[n][w][e]
[s][vp 8 2 1 0 855 0]Vengo a casa del se隠or Sakura[n]a traer paquetes con frecuencia,[n]pero no s姻 de qui姻n me hablas.[n][w][e]

[msg MSG_NPC_END_MOR_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]Hasta ahora, solo tenemos[n]una pista...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]El Jefe compra mucha comida,[n]demasiada para un hombre[n]que vive solo.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Vamos a investigar[n]todas las tiendas de comida.[n][w][e]

[msg MSG_NPC_END_MOR_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Deber胤amos preguntar a m茨s gente.[n][w][e]

