[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_000_000_00]
[s]Dummy[n][w][e]

[msg fev0409_11_mes01]
[s][vp 1 0 0 0 0 0]Es tarde. Creo que llevo limpiando[n]un buen rato.[n][w][e]

[msg fev0409_11_mes02 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5001 65535 0]夷Qu姻 narices? Estabas armando[n]un buen jaleo, pero nunca hubiera[n]dicho que estar胤as limpiando.[n][w][e]

[msg fev0409_11_mes03 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5086 65535 0]Cabe decir que has hecho un buen trabajo.[n][w][e]

[msg fev0409_11_mes04 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Aunque es normal que quieras[n]tener tu habitaci吋n recogida.[n][w][e]

[msg fev0409_11_mes05 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5074 65535 0]夷Por qu姻 no te acuestas ya?[n]No tienes nada mejor que hacer.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Yo voy a cerrar e irme a casa.[n][w][e]

[msg fev0409_11_mes06 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ten, aqu胤 tienes unas s茨banas.[n]Tranquilo, est茨n limpias.[n][w][e]

[msg fev0409_11_mes07]
[s][vp 1 0 0 0 0 0]Estas s茨banas son muy finas,[n]salta a la vista que son baratas.[n][w][e]

[msg fev0409_11_mes08 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si te pones enfermo[n]por no descansar lo suficiente,[n]no pienso cuidar de ti, 夷entendido?[n][w][e]

[msg fev0409_11_mes09]
[s][vp 1 0 0 0 0 0]Dormir en tu cama har茨[n]que avance un d胤a.[n][w][e]

