[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_TOBIORI_GAYA_grt_A_0]
[s]斡夷Se ha ca胤do del tejado?![n]Joder, pues estar茨 muerta.[n][f 1 2 65535][e]

[msg MSG_TOBIORI_GAYA_grt_B_0]
[s]Pero 斡夷por qu姻?![n]斡夷Ha sido un suicidio?[n][f 1 2 65535][e]

[msg MSG_TOBIORI_NPC_01 [Alumno boquiabierto]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]Hay demasiada gente.[n]No veo nada desde aqu胤.[n][w][e]

[msg MSG_TOBIORI_NPC_02 [Alumno que finge rectitud]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]夷Alguien ha tenido un accidente[n]y t雨 quer胤as verlo por morbo?[n]Mal, muy mal.[n][w][e]

[msg MSG_TOBIORI_NPC_03 [Alumno boquiabierto]]
[s][f 4 23 1 850 3 10 0 0][vp 8 2 1 0 850 0]夷Ah, s胤? 夷Y t雨 qu姻 haces aqu胤?[n]Pues cotillear tambi姻n.[n][w][e]

[msg MSG_TOBIORI_NPC_04 [Alumno que finge rectitud]]
[s][f 4 23 1 851 3 10 0 0][vp 8 2 1 0 851 0]夷Qu姻? N-No...[n]Solo estoy preocupado.[n][w][e]

