[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_000_000_00]
[s]Dummy[n][w][e]

[msg MSG_064_0_0 [Estudiante de primer a隠o motivada]]
[s][vp 1 0 0 0 0 0]斡He visto a un bellez吋n tremendo![n]斡Parec胤a una modelo![n][w][e]

[msg MSG_065_0_0 [Estudiante de primer a隠o con energ胤a]]
[s][vp 1 0 0 0 0 0]夷Te refieres a Takamaki?[n]Es famosa. Dicen que viv胤a en el[n]extranjero y que sale en anuncios.[n][w][e]

[msg MSG_066_0_0 [Estudiante de primer a隠o motivada]]
[s][vp 1 0 0 0 0 0]Me gustar胤a conocerla,[n]pero est茨 fuera de mi liga.[n][w][e]

[msg MSG_067_0_0 [Estudiante de primer a隠o con energ胤a]]
[s][vp 1 0 0 0 0 0]Es verdad, resalta entre los dem茨s.[n]Parece que algunos de tercer[n]a隠o le tienen echado el ojo.[n][w][e]

[msg MSG_068_0_0 [Estudiante de primer a隠o motivada]]
[s][vp 1 0 0 0 0 0]斡夷Qu姻?! Pero qu姻 miedo...[n]Supongo que es lo que pasa[n]cuando se llama tanto la atenci吋n.[n][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Por fin te encuentro.[n]Tengo que pedirte un favor.[n][w][e]

[msg MSG_027_0_0 [Jugador de voleibol inquieto]]
[s][vp 1 0 0 0 0 0]S-Sakamoto, sab胤a[n]que vendr胤as por m胤...[n][w][e]
[s][vp 1 0 0 0 0 0]Tengo que animar al profesor[n]Kamoshida, as胤 que es mejor[n]que lo dejemos para despu姻s.[n][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]畏l te hizo las heridas, 夷no?[n]Necesitamos v胤ctimas[n]para denunciarlo.[n][w][e]
[s][vp 1 0 0 0 0 0]夷En serio quieres que ese capullo[n]quede impune?[n]斡Por favor, ay雨danos![n][w][e]

[sel SEL_029_0_0 top]
[s]Ay雨danos.[e]
[s]No lo pases por alto.[e]

[msg MSG_030_0_0 [Jugador de voleibol inquieto]]
[s][vp 1 0 0 0 0 0]Lo siento, pero vais a tener[n]que buscar a otra persona.[n][w][e]
[s][vp 1 0 0 0 0 0]Quiero terminar el instituto[n]sin problemas... No me gustar胤a[n]acabar como t雨.[n][w][e]
[s][vp 1 0 0 0 0 0]Si me pongo en contra del profesor[n]Kamoshida, no lo conseguir姻.[n]Sabes lo influyente que es, 夷no?[n][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Joder, no va a soltar prenda.[n]Y todo por las triqui隠uelas[n]del desgraciado ese...[n][w][e]

[msg MSG_031_5_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Tendremos que hablar[n]con otra persona.No pienso rendirme.[n][w][e]

[msg MSG_078_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]No sirve de nada. Todos cierran[n]el pico en cuanto nombramos[n]al puto Kamoshida.[n][w][e]
[s][vp 1 0 0 0 0 0]Joder... 斡夷Qu姻 cojones hacemos?![n][w][e]

[sel SEL_079_0_0 top]
[s]Vamos a descansar un rato.[e]
[s]Esto es culpa tuya.[e]

[msg MSG_080_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Supongo que nos vendr茨 bien[n]tomarnos un respiro y pensar[n]de nuevo nuestra estrategia.[n][w][e]
[s][vp 1 0 0 0 0 0]Venga, vamos a pillar algo[n]de beber y a bajar al patio.[n][w][e]

[msg MSG_081_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]No digas eso, t雨 eres[n]el que tiene antecedentes...[n][w][e]
[s][vp 1 0 0 0 0 0]O sea, que te han arrestado,[n]nada m茨s, pero...[n][w][e]
[s][vp 1 0 0 0 0 0]Lo siento...[n][w][e]
[s][vp 1 0 0 0 0 0]Venga, te invito a un zumo como[n]ofrenda de paz. Vamos al patio.[n][w][e]

[msg MSG_032_0_0 [Jugador de voleibol inquieto]]
[s][vp 1 0 0 0 0 0]夷Por qu姻 quieres montar un pollo?[n]Todo el mundo ve bien[n]dejar las cosas como est茨n.[n][w][e]
[s][vp 1 0 0 0 0 0]Deber胤as saberlo mejor[n]que nadie. El 或statu quo位[n]es la mejor opci吋n.[n][w][e]

