[sel YESNO_SEL top]
[s]S胤.[e]
[s]No.[e]

[msg MSG_650_102_00]
[s]Dummy[n][w][e]

[msg MSG_E65010200_Men_000_00 [Empleado de estaci吋n de mediana edad]]
[s][vp 8 2 1 0 802 0]夷Eh?[n][w][e]
[s][vp 8 2 1 0 802 0]夷Buscas el acceso a la l胤nea[n]Inogami? Venga, ind胤cale.[n][w][e]

[msg MSG_E65010200_Men_001_00 [Empleado de estaci吋n asustadizo]]
[s][f 4 23 1 803 3 10 0 0][vp 8 2 1 0 803 0]斡Vale![n][w][e]
[s][vp 8 2 1 0 803 0]Cruza el acceso a la l胤nea[n]Denentoshi y ver茨s la Inogami.[n]No tiene p姻rdida.[n][w][e]

