[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_DET_INFO_GOT_ENOUGH [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Creo que ya podemos[n]ir a ver a Taihei.[n][w][e]

[msg MSG_DET_INFO_GOT_ALL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Creo que ya hemos aprendido[n]todo lo que pod胤amos.[n]Vamos a ver a Taihei.[n][w][e]

[msg MSG_DET_INFO_NEXT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Vamos a ver si conseguimos[n]m茨s informaci吋n.[n][w][e]

[msg MSG_DET_MISHIMA_00 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][f 4 23 1 802 3 10 0 10]斡Oye, espera! No me digas que...[n][w][e]
[s]Seg雨n mis investigaciones,[n]est茨s recopilando informaci吋n[n]sobre la profesora Kawakami.[n][w][e]
[s]斡夷Y quieres que lo haga por ti?![n][w][e]

[sel SEL_DET_MISHIMA_01 top]
[s]夷Podr胤as?[e]
[s]夷De qu姻 est茨s hablando?[e]

[msg MSG_DET_MISHIMA_02 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][f 4 23 1 802 3 10 0 10]S胤, d姻jamelo a m胤.[n][w][e]
[s]斡Ya ver茨s! 斡Conseguir姻 todo[n]lo que necesitas en diez minutos![n][w][e]

[msg MSG_DET_MISHIMA_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya han pasado diez minutos.[n]Me pregunto qu姻 ser茨 de Mishima.[n][w][e]

[msg MSG_DET_MISHIMA_04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Vaya, ha resultado ser muy 雨til.[n][w][e]

[msg MSG_DET_MISHIMA_10 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][f 4 23 1 802 3 10 0 10]Si en alg雨n momento necesitas[n]ayuda, av胤same.[n][w][e]
[s]斡Te demostrar姻 lo 雨til[n]que puedo llegar a ser![n][w][e]

[msg MSG_DET_MISHIMA_50 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Creo que ya tenemos todo[n]lo que necesitamos sin Mishima.[n][w][e]
[s]斡Venga, vamos a por Taihei![n][w][e]

[msg MSG_DET_MISHIMA_51 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][f 4 23 1 802 3 10 0 10]夷Qu姻? 夷Estaba equivocado?[n][w][e]
[s]Qu姻 raro. Puede que mi informaci吋n[n]no fuera muy precisa.[n][w][e]

