[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_180_105_00]
[s]Dummy[n][w][e]

[msg MSG_POLICE_180105_00 [Hombre duro]]
[s][vp 8 2 1 0 801 0]Conque es aqu胤...[n][w][e]

[msg MSG_POLICE_180105_01 [Hombre sospechoso]]
[s][vp 8 2 1 0 800 0]Eso parece.[n]Hay que ocuparse del tema.[n][w][e]

[msg MSG_POLICE_180105_02 [Hombre duro]]
[s][vp 8 2 1 0 801 0]斡Espera! A雨n no tenemos[n]orden de registro.[n][w][e]
[s][vp 8 2 1 0 801 0]Calma, seguro que[n]nos la dan pronto.[n][w][e]
[s][vp 8 2 1 0 801 0]Y ni se les ocurrir胤a echar[n]a correr por este callej吋n[n]tan estrecho.[n][w][e]

[msg MSG_CATCH_001_00 [Hombre amenazante]]
[s][f 4 23 1 850 3 10 0 10][vp 8 2 1 0 850 0]Oye, 夷eres estudiante?[n][w][e]
[s]夷Quieres un trabajo en el que[n]te forres sin matarte a trabajar?[n][w][e]

[sel SEL_CATCH_001 top]
[s]夷Qu姻 tendr胤a que hacer?[e]
[s]No tengo tiempo.[e]
[s]Suena bastante turbio...[e]

[msg MSG_CATCH_001_01a [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]Eh, 斡ni caso! Adem茨s, creo que ya[n]lo hemos visto por ah胤 alguna vez.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]En fin, empe隠ar la medalla de oro[n]es nuestra prioridad ahora mismo.[n]斡Pasa del t胤o ese![n][w][e]

[msg MSG_CATCH_001_01b [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1034 65535 0]S胤, empe隠ar la medalla de oro[n]es nuestra prioridad ahora mismo.[n]斡Pasa del t胤o ese![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Adem茨s, tiene bastante mala pinta.[n]Es mejor evitar[n]a este tipo de gente.[n][w][e]

[msg MSG_CATCH_001_01c [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Suena demasiado bonito para ser[n]verdad. Adem茨s, creo que ya[n]lo hemos visto por ah胤 alguna vez.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]En fin, empe隠ar la medalla de oro[n]es nuestra prioridad ahora mismo.[n]Venga, andando.[n][w][e]

[msg MSG_CATCH_GREETING_00 [Vendedor]]
[s][f 4 23 1 850 3 10 0 10][vp 8 2 1 0 850 0]斡Eh, t雨! 夷Quieres jugar a un juego?[n][w][e]

