[msg MSG_000_0_0 [(SE)モルガナ]]
[s][vp 8 0 0 1 65535 0](苦しそうに悪夢にうなされる)[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]夷Esa cosa negra era yo...?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]No es posible.[n]Se supone que soy humano...[n][f 1 3 65535][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Deber胤a ser...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Si nos libramos de la distorsi吋n[n]en las profundidades de Mementos,[n]seguro que... todo ir茨 bien...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Perdona, 夷te he despertado?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]夷Has tenido pesadillas?[e]
[s]夷Qu姻 ocurre?[e]
[s]Estabas gru隠endo.[e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Pues...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]El sol estaba abras茨ndome[n]y por eso me he despertado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Estaba absorbiendo todos los rayos.[n]Como soy negro... 夷Lo pillas?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]夷Est茨s bien?[e]
[s]夷Los gatos se queman con el sol?[e]
[s]Est茨s chamuscado.[e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Eh, mmm, la verdad es que[n]no s姻 qu姻 hacer cuando me respondes[n]con tanta preocupaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Est茨s pensando que tengo[n]el cuerpo cubierto de pelo, 夷no?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]斡Pues en las almohadillas[n]de las patas no![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]斡Es natural![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Por cierto, y no pienses que esto[n]me preocupa o algo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Pero, hipot姻ticamente hablando...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]夷Qu姻 har胤as si fuera[n]una especie de cosa rara?[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]No me molestar胤a.[e]
[s]Ya eres raro.[e]
[s]夷Te est茨s confesando?[e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]斡A m胤 me molestar胤a![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Es que, bueno...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 13 300 1][vp 8 0 0 20 65535 0]斡Para nada! 斡Es solo hipot姻tico![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Si lo que vi antes es cierto,[n]夷puedo quedarme[n]con los Ladrones Fantasma?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Aunque est姻 con el grupo,[n]ahora mismo no sirvo para nada.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]No es nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]La verdad es que ya[n]me he acostumbrado a ser un gato[n]y este trastero no est茨 nada mal.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Pero tambi姻n es verdad[n]que no puedo esperar a volver[n]a ser humano para mudarme.[n][f 1 3 65535][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Igual llevo una vida llena de lujos[n]en una suite en el piso m茨s alto.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 27 0 0]...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Pero si tengo que elegir entre[n]convertirme en una cosa rara[n]o ser un gato, prefiero lo segundo.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]T雨 y yo hicimos un trato, 夷verdad?[n]Eso significa que puedo[n]quedarme aqu胤, 夷no?[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s]S胤.[e]
[s]Haz lo que quieras.[e]

[msg MSG_023_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Eso cre胤a...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]No te olvides de lo que acabas[n]de decir, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 10 300 1][vp 8 0 0 32 65535 0]Venga, a dormir.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Buenas noches.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Todo saldr茨 bien, 夷no?[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 1 0 0 0 0 0]Siento que mi v胤nculo[n]con Morgana se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

