[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Oye, prep茨rate.[n]Nos vamos a comer fuera.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷Quieres que vaya?[e]
[s]Si invitas, voy.[e]
[s]Esto no me lo esperaba.[e]

[msg MSG_002_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]No tienes planes, 夷verdad?[n]Pues venga, yo invito.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Por supuesto.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]No te quejes, que pago yo.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Futaba ya sale de casa[n]y las vacaciones de verano casi[n]han terminado. Hay que hacer algo.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]He reservado[n]en un restaurante de sushi.[n]M茨s vale que est姻s agradecido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Tengo entendido que la comida[n]est茨 buen胤sima.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]斡夷Sushi?! 斡Yo quiero ir![n]No com胤 cuando pedisteis[n]a domicilio, 夷te acuerdas?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Ese bicho no deja de maullar, 夷eh?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Quiere apuntarse.[e]
[s]Quiere sushi.[e]
[s]夷Puede venir?[e]

[msg MSG_013_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]No nos dejar茨n entrar si[n]nos plantamos ah胤 con un gato.[n]Lo siento, pero no.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][f 4 16 3 3 301 1 65535][vp 8 0 0 10 65535 0]斡Dile que yo tambi姻n voy![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]No querr茨 venir[n]con nosotros, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]夷Al restaurante?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sojiro]]
[s][f 4 16 3 1 301 65535 65535][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Pero me da una penita...[n]Bueno, le traer姻 un poco de sushi.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][f 4 16 3 1 301 1 65535][vp 8 0 0 15 65535 0]斡Qu姻 bien me conoce![n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]A ver, quiero at雨n semigrasiento,[n]at雨n grasiento, huevas de salm吋n,[n]anguila y, y...[n][f 1 3 65535][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]夷Te vas a acordar de todo?[n]Mejor ap雨ntalo.[n][f 1 3 65535][w][e]

