[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Jam茨s habr胤a pensado que lo de la[n]madre de Futaba estar胤a conectado[n]con los incidentes de la ciudad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]斡No podemos quedarnos[n]de brazos cruzados![n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Tienes raz吋n.[e]
[s]夷Qu姻 te est茨 pasando?[e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Bueno, 斡ahora nos toca[n]lucirnos a nosotros![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Aunque estos canallas tienen[n]nuestro mismo poder, causan[n]desconexiones mentales a la gente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Si de verdad existen, 夷qui姻n puede[n]detenerlos? Solo nosotros.[n][f 1 3 65535][w][e]

[msg MSG_003_5_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 1 301 1][vp 8 0 0 6 65535 0]斡Esto se pone interesante![n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Pareces animado.[e]
[s]夷Podemos ganar?[e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Hay un nuevo miembro en el equipo,[n]斡as胤 que es hora de que muestre[n]mis habilidades de veterano![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]No podemos tenerte dando tumbos.[n]No te preocupes, 斡yo te ayudar姻[n]con mi experiencia![n][f 1 3 65535][w][e]

[msg MND_007_0_0]
[s][vp 8 0 0 0 65535 0]Morgana parece estar emocionado.[n][f 1 3 65535][w][e]

