[msg MSG_000_0_0 [Director]]
[s][bup 0 204 4 0 0][f 4 10 65535 0 0][vp 8 0 0 1 4 0]夷Qu姻? 夷Que he salido[n]en una revista sensacionalista?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 4 0]Pero si he dado la orden de guardar[n]silencio con respecto al caso[n]del profesor Kamoshida.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Director]]
[s][bup 0 204 4 0 0][f 4 10 65535 0 0][vp 8 0 0 3 4 0]斡No tan r茨pido![n]斡Necesito algo de tiempo![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 4 0]斡Prometo que encontrar姻 pruebas[n]sobre los Ladrones Fantasma![n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Director]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 5 4 0]Se隠or, no habr胤a llegando tan lejos[n]de no ser por su ayuda,[n]as胤 que...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 4 0]Se lo ruego, perm胤tame...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Director]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 7 4 0]A-ah... No... 斡Noooooo![n][f 1 3 65535][w][e]

