[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Vaya, no sab胤a que tambi姻n[n]hab胤a un Big Bang Burger en Haw茨i.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]S胤, 雨ltimamente se ha puesto[n]de moda en Jap吋n.[n]Supongo que querr茨n expandirse.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Ahora que lo dices,[n]hace poco le胤 un art胤culo[n]sobre el 姻xito de Okumura Foods.[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Ah, ya, la empresa propietaria[n]de Big Bang Burger.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 3 1 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]夷Okumura...?[n][f 1 3 65535][w][e]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]夷Ese no es el que est茨[n]de los primeros en la Fansite?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 4 1 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Es eso cierto?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Te lo aseguro. Nunca me equivoco[n]con esas cosas.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Eres incre胤ble.[e]
[s]Claro que no.[e]
[s]夷Okumura Foods?[e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]夷Verdad?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][bup 0 2 3 1 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]夷Eso es sarcasmo?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]S胤. Antes no at姻 cabos,[n]pero supongo que los conocemos[n]bastante bien.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]夷Eh? 夷Sucede algo?[n][f 1 3 65535][w][e]

[msg MSG_016_3_0 [Makoto]]
[s][bup 0 6 4 1 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Ah, probablemente nada.[n][f 1 3 65535][w][e]
[s][f 4 16 4 1 300 65535 65535][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Solo es un rumor que o胤[n]sobre Okumura Foods...[n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Supuestamente... todos sus[n]competidores extranjeros[n]se han retirado misteriosamente.[n][f 1 3 65535][w][e]

[msg MSG_016_7_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Da igual. Seguro que le estoy[n]dando demasiadas vueltas.[n]Se me habr茨 pegado de mi hermana.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Oye, 夷y si nos sacamos una foto?[n]斡Como recuerdo del viaje y eso![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ann]]
[s][bup 0 4 1 1 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]斡Anda, buena idea![n][f 1 3 65535][w][e]

[sel SEL_018_5_0 top]
[s]Yo saco la foto.[e]
[s]Colocaos por ah胤.[e]

[msg MSG_019_0_0 [Makoto]]
[s][bup 0 6 4 1 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]夷Seguro que no quieres salir?[n]Gracias.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Yusuke]]
[s][bup 0 5 1 1 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Solo pido que la composici吋n[n]quede equilibrada.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ann]]
[s][bup 0 4 3 1 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]夷Puedes dejar de preocuparte[n]por eso por un momento?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Venga, [f 4 2].[n][f 1 3 65535][w][e]

[sel SEL_023_0_0 top]
[s]斡Sonre胤d![e]
[s]Esperemos que salga bien...[e]
[s]...[e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 1 1 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Todav胤a tenemos algo[n]de tiempo libre, 夷no? 夷D吋nde vamos?[n][f 1 3 65535][w][e]

[msg MSG_024_5_0 [Ryuji]]
[s][bup 0 2 1 1 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Hay una tienda[n]cerca de la playa. 夷Vamos?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Suena fant茨stico.[n]Me gustar胤a descansar un poco.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Vale, pues vamos para all茨.[n][f 1 3 65535][w][e]

