[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Qu姻 horror...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Es el tipo ese con el que[n]te han prometido, 夷no?[n]Ya sabes lo que pasar茨...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Seg雨n lo que nos ha contado Haru,[n]la llevar茨n a su casa[n]el 11 de octubre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Nuestra fecha l胤mite es el d胤a 10.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Pero, si despertamos el coraz吋n[n]de tu padre, lo arrestar茨n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Y ser茨s la hija de un delincuente[n]para siempre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Puede que tu vida[n]tambi姻n cambie.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Si acepto ser feliz a costa de la[n]desgracia de los dem茨s, no soy[n]mejor persona que mi padre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Y siendo sincera...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Hace tiempo dej姻[n]una solicitud en la Web[n]del Aficionado de los Fantasmas.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Lo hizo cuando est茨bamos[n]decidiendo qui姻n ser胤a[n]nuestro pr吋ximo objetivo.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Pero los Ladrones Fantasma[n]no hicieron nada.[n][f 1 3 65535][w][e]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Y entonces conoc胤 a Mona.[n]Pens姻 que era cosa del destino.[n][f 1 3 65535][w][e]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]En aquel momento tom姻 una decisi吋n:[n]si los Ladrones Fantasma no[n]actuaban, lo har胤a yo.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Desconexiones mentales, tesoros[n]y despertares...[n]Nuestros intereses se han alineado.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Entonces, 夷vas a ayudarnos?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Por supuesto.[n]Deber胤a ser yo quien pidiera[n]que me admitieseis en el equipo.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]A partir de ahora, puede que nos[n]enfrentemos al culpable[n]de las desconexiones mentales.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Esto no tiene nada que ver con el[n]entrenamiento de Mementos.[n]Ser茨 mejor que est姻is preparados.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Menudo serm吋n...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Pero 斡a ti qu姻 te pasa![n]Haru es poco m茨s[n]que una novata.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Ha despertado sus poderes, pero[n]es d姻bil. Su Persona ni siquiera[n]tiene una forma definida todav胤a.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]夷D姻bil?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]夷En serio?[n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Puede transformarse, pero,[n]si os soy sincero, quiz茨 nos[n]retrase bastante.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Siento mucho causaros[n]tantos problemas.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Nada, no te preocupes.[n]De hecho, nos viene muy bien[n]centrarnos en el CEO.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Echadle un vistazo a[n]este blog de noticias.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Hay muchos comentarios negativos[n]sobre los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]或Han salido a la luz los nombres de[n]varios delincuentes. 夷Por qu姻 no[n]hacen nada los Ladrones Fantasma?位.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]La forma en la que est茨n[n]reaccionando no tiene precedente.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]No olvid姻is la informaci吋n sobre[n]los casos de desconexi吋n[n]mental, 夷de acuerdo?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]斡Claro! 斡Iremos a por todo![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]El 10 de... octubre, 夷no?[n]Para entonces tendremos que haber[n]despertado el coraz吋n de Okumura.[n][f 1 3 65535][w][e]

