[msg MSG_000_0_0 [Futaba]]
[s][vp 8 0 0 0 65535 0][f 5 14]斡Noticia de 雨ltima hora![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Est茨n hablando del fallo[n]de seguridad en la sede[n]de Okumura Foods por la tele.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][vp 8 0 0 0 65535 0][f 5 14]夷Y el presidente Okumura?[n]夷Ha confirmado la situaci吋n?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][vp 8 0 0 0 65535 0][f 5 14]Ahora lo est茨n entrevistando.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Le preguntan si est茨 relacionado[n]con las cr胤ticas que ha recibido[n]por explotar a sus trabajadores.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Eso quiere decir que ha visto[n]lo que hizo Futaba, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]斡Genial, ha funcionado![n]La puerta ya deber胤a estar abierta.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Bueno, podemos ir cuando queramos.[n]Av胤sanos cuando quieras[n]volver al Palacio.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Perfecto, la cognici吋n del CEO[n]deber胤a haber cambiado. Creo que[n]ya podemos pasar por la puerta.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Entraremos a la vez cuando est姻s[n]listo. 斡No hay tiempo que perder![n][f 1 3 65535][w][e]

