[msg MSG_006_5_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]斡Lo hemos encontrado! 斡Es esto![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Pero no hemos encontrado[n]informaci吋n sobre los colapsos[n]mentales. Qu姻 fastidio...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Cierto, tienes raz吋n.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Cre姻is que lo est茨 escondiendo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Hemos llegado hasta aqu胤. 夷Y si le[n]sacamos la verdad a la fuerza?[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Despu姻s de despertar su coraz吋n.[e]
[s]Una vez alcancemos nuestra meta.[e]

[msg MSG_016_0_0 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Me parece bien.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Bueno, pues enviemos el aviso[n]y rob姻mosle el tesoro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]T雨 decides cu茨ndo.[n][f 1 3 65535][w][e]

