[msg MSG_000_5_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Mirad... 斡Es el tesoro![n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]斡夷Qu姻?![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Voz rob吋tica]]
[s][vp 8 0 0 2 65535 0]La secuencia de lanzamiento[n]de emergencia se activar茨[n]en breves instantes.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 65535 0]Es posible que algunas zonas queden[n]inaccesibles y sean destruidas.[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Voz rob吋tica]]
[s][vp 8 0 0 4 65535 0]Repito, la secuencia de lanzamiento[n]de emergencia se activar茨[n]en breves instantes.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 5 65535 0]Se aconseja a todo el personal[n]que evacue inmediatamente a una[n]zona segura de las instalaciones.[n][f 1 3 65535][w][e]

[msg MSG_001_8_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Pero 斡夷qu姻 narices?![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Voz de Sombra de Okumura]]
[s][vp 8 0 0 7 65535 0]No tengo tiempo para ocuparme[n]de vosotros, ladrones.[n]Tengo que marcharme.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 8 65535 0]斡Pod姻is quedaros ah胤 y observar[n]con desesperaci吋n c吋mo ca姻is[n]junto con la base![n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 65535 0]斡Vuestra destrucci吋n es inminente![n][f 1 3 65535][w][e]
[s][vp 8 0 0 10 65535 0]斡Ja, ja, ja, ja![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]斡No tenemos tiempo![n]斡Hay que apresurarse![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]斡Por aqu胤![n][f 1 3 65535][w][e]

