[msg MSG_000_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]斡Parece que hemos[n]calculado mal, recluso![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Pens茨bamos que no, pero al final[n]eres bastante prometedor.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Tus poderes siguen creciendo,[n]as胤 como las relaciones con los[n]que has forjado un contrato.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Veo que tu rehabilitaci吋n[n]va por buen camino.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Hemos acabado con un delincuente.[e]
[s]夷Va todo bien?[e]
[s]...[e]

[msg MSG_004_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]*risita*[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Eres bastante cauteloso.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Pero una cosa te digo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Estar en lo m茨s alto[n]significa que en cualquier momento[n]se puede caer en picado.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Las situaciones inesperadas son[n]necesarias en cualquier juego.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [(SE)イゴール]]
[s][vp 8 0 0 11 65535 0](『フフフ』という笑い)[n][f 1 3 65535][w][e]

