[msg MSG_000_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]En pie, recluso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]El maestro tiene que hablar contigo[n]de un asunto muy importante.[n]Escucha con atenci吋n.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Antes de nada, quiero felicitarte[n]por deshacerte de aquel[n]orgulloso de su avaricia...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]O eso me gustar胤a decir,[n]ya que ha sucedido algo[n]harto extra隠o.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]No ha sido culpa nuestra.[e]
[s]夷Qu姻 ha pasado?[e]

[msg MSG_003_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Estoy al tanto, por supuesto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Pero 夷qu姻 hay[n]de la opini吋n p雨blica?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Qui姻n sabe?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Pero 夷acaso no sientes la maliciosa[n]voluntad de otra persona?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Parece que ha surgido[n]un contratiempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]A este paso, no podr茨s completar[n]tu rehabilitaci吋n... Aunque dudo[n]que acabe siendo el caso.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Tengo muchas ganas[n]de ver c吋mo superas[n]este obst茨culo.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Volveremos a vernos.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]斡Eso es todo, recluso![n]斡Date prisa y vuelve a tu mundo![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 1 0 0 0 0 0]Siento que mi v胤nculo[n]con Igor se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

