[msg MSG_000_0_0 [Haru]]
[s][vp 8 0 0 0 65535 0][f 5 14]Oh, 夷[f 4 2]?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Disculpa que te escriba[n]tan temprano.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]La situaci吋n se ha calmado[n]un poco en casa... As胤 que[n]hay una cosa que debo contaros.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]夷Qu姻 ocurre?[e]
[s]夷Est茨s bien?[e]

[msg MSG_002_0_0 [Haru]]
[s][vp 8 0 0 0 65535 0][f 5 14]Mmm...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Gracias.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][vp 8 0 0 0 65535 0][f 5 14]Mmm, hay algo que me ha llamado[n]la atenci吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Creo que tengo que hablarlo[n]con el resto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Deber胤amos quedar en el escondite[n]despu姻s de clase.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Parece que Haru se las est茨[n]apa隠ando...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Muy bien, reun茨monos todos[n]despu姻s de clase.[n][f 1 3 65535][w][e]

