[msg MSG_000_0_0 [Estudiante asustado]]
[s][vp 8 0 0 1 28 0]夷Otra vez la polic胤a por aqu胤?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Estudiante irritado]]
[s][vp 8 0 0 2 15 0]S胤. Parece que ahora van en serio.[n]Se ve que alguien que estudia aqu胤[n]es un Ladr吋n Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Estudiante asustado]]
[s][vp 8 0 0 3 28 0]斡夷En serio?![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Estudiante irritado]]
[s][vp 8 0 0 4 15 0]Lo he visto en internet. Parece que[n]Seguridad ciudadana ya est茨 en marcha...[n][f 1 3 65535][w][e]

