[msg MSG_000_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]No se puede permitir que unos[n]delincuentes se salgan con la suya[n]solo porque dicen hacer justicia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]El gobierno est茨 hablando[n]de tomar medidas, pero 斡no son[n]suficientes y llegan tarde![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]El gobierno se ha quedado atr茨s.[n]斡Est茨 obsoleto![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]斡No tenemos que hundirnos con el barco![n]斡Nosotros podemos cambiarlo todo![n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Shido]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 206 12 300 1][vp 8 0 0 5 65535 0]斡Acabemos con este caos[n]entre todos![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Trabajador joven]]
[s][vp 8 0 0 6 65535 0]Es un pol胤tico del partido[n]gobernante, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Trabajador mayor]]
[s][vp 8 0 0 7 65535 0]Van a dividirse para formar[n]un nuevo partido, as胤 que podr胤an[n]celebrarse elecciones pronto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Trabajador joven]]
[s][vp 8 0 0 8 65535 0]斡Esta vez s胤 que votar姻![n]Este hombre tiene todo mi apoyo.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Trabajador mayor]]
[s][vp 8 0 0 9 65535 0]夷A雨n no has votado?[n]Formas parte de la sociedad,[n]as胤 que deber胤as.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Trabajador joven]]
[s][vp 8 0 0 10 65535 0]La pol胤tica nunca me hab胤a llamado[n]la atenci吋n, pero este hombre[n]me parece incre胤ble.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 11 65535 0]Tiene pasi吋n y piensa en el futuro.[n]Yo creo que alguien como 姻l[n]deber胤a ser primer ministro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 12 65535 0]Lo votar姻.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Trabajador mayor]]
[s][vp 8 0 0 13 65535 0]Bueno, tiene sentido, teniendo[n]en cuenta que los otros pol胤ticos[n]no son nada fiables.[n][f 1 3 65535][w][e]

