[msg MSG_000_0_0 [Voz mec茨nica]]
[s][vp 8 0 0 1 65535 0]Autentificaci吋n necesaria.[n]Introduzca su tarjeta de miembro.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]夷Qu姻 tarjeta de miembro?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]A lo mejor es como[n]un club de jugadores o algo as胤.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]斡No entiendo esas palabras tan[n]t姻cnicas! 斡Habla claro![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Los casinos suelen tener[n]un sistema de miembros,[n]un club de jugadores.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Algunas zonas incluso est茨n[n]limitadas para determinados[n]niveles de jugador.[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Akechi]]
[s][bup 0 9 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Por c吋mo pintan las cosas,[n]creo que este sitio[n]cuenta con un sistema similar.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]As胤 ser茨 m茨s f茨cil.[n]Venga, vamos a meternos[n]en ese embolado.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Me gustar胤a decir lo mismo, pero...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]斡夷Una sombra?![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Como imaginaba, apuntarnos[n]no va a ser tan f茨cil.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Seguro que nos est茨 haciendo[n]enfrentarnos a la seguridad[n]antes de que lleguemos a ella.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]斡Ah胤 viene![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]No hay de qu姻 preocuparse.[n]Yo me ocupo. Tengo que[n]demostraros que valgo.[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]Espero mucho de ti.[e]
[s]夷Estar茨s bien?[e]

[msg MSG_014_0_0 [Akechi]]
[s][bup 0 9 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Prometo superar incluso[n]unas expectativas tan altas.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]A saber, pero creo que nadie[n]va a tener que intervenir.[n][f 1 3 65535][w][e]

