[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As胤 que nuestra reputaci吋n mejorar茨[n]si conseguimos monedas, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Juegos de dados y tragaperras...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Como son juegos de azar,[n]no me extra隠ar胤a[n]que estuviesen trucados.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡夷Crees que est茨 haciendo trampa?![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Entonces, 夷vamos a perder[n]hasta que descubramos el pastel?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sin duda. Y m茨s sabiendo[n]que este mundo pertenece a Sae,[n]una abogada del Estado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aunque parezca un casino,[n]en realidad es un juzgado,[n]夷me equivoco?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤, 夷y qu姻?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La probabilidad de salir declarado[n]culpable en el primer juicio aqu胤[n]es del 99,9 %, la mayor del mundo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Si una persona es arrestada[n]y se abre un juicio contra ella,[n]es casi imposible que salga airosa.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espera un momento.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷C吋mo es posible que el porcentaje[n]sea tan alto? 夷Tan precisas son[n]las investigaciones?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No... Al fin y al cabo,[n]los investigadores son humanos.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Entonces?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No eres la primera que se percata[n]de la injusticia del sistema.[n]El fiscal es casi invencible.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Con raz吋n las acusaciones falsas[n]causan tanta conmoci吋n...[n]Si es que no se dan con frecuencia.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero 夷qu姻 gilipollez es esta[n]de que te arresten[n]sin ser culpable?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si no nos damos prisa,[n]los Ladrones Fantasma[n]sufrir茨n esa misma suerte.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hay que ganar como sea.[n][f 1 3 65535][w][e]

