[msg MSG_000_0_0 [Sombra de Sae]]
[s][bup 0 105 100 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Perdedores.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sombra de Sae]]
[s][bup 0 105 102 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Juzgar a delincuentes no es[n]m茨s que un juego, y los fiscales[n]somos quienes preparamos la mesa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Por tanto, 斡perder es inadmisible![n]Debemos ganar, 斡aunque sea[n]mediante acusaciones falsas![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]斡夷Lo dices en serio, Sae?![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]斡夷Por qu姻 no me contestas?![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Mako...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sombra de Sae]]
[s][bup 0 105 100 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]No voy a caer[n]en un truco tan mezquino.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]No tendr姻 m茨s remedio que admitir[n]que sois h茨biles... si lleg茨is[n]a la planta de direcci吋n, claro.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 103 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]夷De verdad piensa que los juicios,[n]que condicionan la vida de la[n]gente, no son m茨s que un juego?[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Akechi]]
[s][bup 0 9 105 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Ojal茨 no tuviera que o胤r[n]eso de boca de la propia Sae...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]斡Mi hermana est茨[n]totalmente corrompida![n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]斡Tenemos que detenerla como sea![n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Tenemos que salvarla juntos.[e]
[s]Calma.[e]
[s]Nos las arreglaremos.[e]

[msg MSG_009_0_0 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Todos pensamos lo mismo.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Es verdad.[n]A雨n nos queda un largo camino.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Tiene raz吋n.[n]斡Seguro que lo conseguimos![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]No hay tiempo que perder.[n]Ha dicho algo de una planta[n]de direcci吋n, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_012_5_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Hay que intentar llegar ah胤.[n]Vamos a despertar a Niijima,[n]dadlo por hecho.[n][f 1 3 65535][w][e]

