[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Ma隠ana es el d胤a por fin.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Lo 雨nico que queda es[n]llevar a cabo la operaci吋n[n]que ha planeado Makoto.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 53105 65535 0]Ya solo hay que entregarlo.[n]Tenemos que conseguir[n]que le llegue a Niijima...[n][f 1 3 65535][w][e]

