[msg MSG_000_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Enhorabuena por llegar tan lejos,[n]recluso.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Ahora que has pasado por[n]tus largos y peligrosos recuerdos,[n]por fin est茨s en el presente...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Los efectos del f茨rmaco[n]se te pasar茨n pronto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Esta es tu gran oportunidad.[n]Debes comprender la verdad que[n]te salvar茨 de la perdici吋n.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]La influencia malvada que ans胤a[n]tu muerte se acerca con celeridad.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Si quieres ganar este juego[n]tan poco razonable...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Justine]]
[s][bup 0 101 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Si deseas recuperar[n]el futuro que te robaron...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Caroline y Justine]]
[s][vp 8 0 0 12 4 0]Recuerda los v胤nculos[n]que has forjado con tus aliados...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 13 4 0]Y comprende la verdad que[n]te salvar茨 de la perdici吋n.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [(SE)イゴール]]
[s][vp 8 0 0 0 65535 0](『フフフ』という笑い)[n][f 1 3 65535][w][e]

