[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Estoy agotado...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Siento que estoy a punto[n]de perder el conocimiento...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Eh, 夷est茨s bien?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]No te duermas hasta que lleguemos[n]a nuestro destino.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]夷Me est茨s escuchando?[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]夷Puede ser que se est姻 pasando[n]el efecto de los f茨rmacos?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Los recuerdos que parec胤an[n]olvidados est茨n volviendo...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]夷Me est茨s escuchando?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]S胤.[e]
[s]夷De qu姻 habl茨bamos?[e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]夷No me estabas escuchando?[n]Bueno, supongo que comprendo[n]que te quedes ensimismado.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]En fin, tenemos que hablar[n]de c吋mo salir de esta situaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]El seguimiento del m吋vil[n]que hizo Futaba lo ha confirmado...[n]Ten胤a otros motivos.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Est茨 a otro nivel[n]totalmente diferente.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]No solo intentaba inculparnos,[n]sino que era el culpable de las[n]desconexiones mentales...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Se ofreci吋 a ayudarnos para[n]incriminar a los Ladrones Fantasma...[n]y matar a [f 4 2].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Si vamos al Palacio[n]de mi hermana, nos encontraremos[n]una emboscada de la polic胤a.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Qui姻n iba a pensar que llegar胤a[n]tan lejos... Ahora s姻 lo que es[n]tener escalofr胤os.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Adem茨s, quiere llevar a la polic胤a[n]de verdad al Palacio...[n][f 1 3 65535][w][e]

[msg MSG_010_5_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Si nosotros ocho no podemos acceder[n]a la vez, mucho menos[n]un grupo m茨s grande.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Incluso podr胤a meter veh胤culos o[n]partes de equipamiento especiales.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]O sea, que esto estaba preparado[n]para echarnos el muerto a nosotros...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Nos hizo ir tras Okumura, y cuando[n]despertamos su coraz吋n, lo mat吋...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Haru]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 3 300 1][vp 8 0 0 18 65535 0]Y nos dijo que hab胤a visto al[n]verdadero culpable... pero 斡era 姻l![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 3 301 1][vp 8 0 0 19 65535 0]斡Todo el tiempo que trabaj吋[n]con la hermana de Makoto... y era[n]un puto pirado homicida![n][f 1 3 65535][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]斡Venga, hay que acabar con[n]el cabr吋n de Akechi! 斡夷La grabaci吋n[n]no es prueba suficiente o qu姻?![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]No, Akechi es solo un pe吋n. Recibe[n]吋rdenes de alguien m茨s...[n]Del culpable de todo esto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Un desalmado capaz de organizar[n]el asesinato de un sospechoso[n]dentro de una comisar胤a...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Si no averiguamos qui姻n es,[n]nos seguir茨 persiguiendo aunque[n]acabemos con Akechi...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Pero... 夷c吋mo podemos[n]descubrir su identidad?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Se lo sacaremos a Akechi...,[n]pero cuando lo logremos,[n]esa persona querr茨 vernos muertos.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Eso pasar茨 averig鵜emos[n]su identidad o no.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]El 雨nico motivo por el que[n]no ha ocurrido todav胤a es porque[n]nos puede culpar de sus delitos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Si se da cuenta de que eso ya no es[n]posible y abandona el plan, podr胤a[n]intentar matarnos de inmediato.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Maldita sea... O sea que no hay[n]otra opci吋n que hacer lo que[n]sugiri吋 ese capullo...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Pero si entramos en el Palacio,[n]a [f 4 2] lo arrestar茨n[n]y Akechi lo asesinar茨...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Palacio...[n][f 1 3 65535][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]El Palacio...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]En realidad, me gustar胤a[n]decir algo sobre...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Futaba]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 14 301 1][vp 8 0 0 34 65535 0]斡Aj茨! 斡Podemos usar el Palacio[n]a nuestro favor![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]斡夷A qu姻 viene esto de repente?![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Hay un modo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Un modo de escapar de Akechi y de[n]que quien est茨 detr茨s de esto nos[n]deje, averiguando de paso qui姻n es.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]斡夷En serio?![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]斡Ser茨 una broma![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Si quiere matar a [f 4 2],[n]夷por qu姻 no dejarlo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Dentro del Palacio, claro...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]S胤. Podemos hacer que mate[n]al [f 4 2] cognitivo y[n]que crea que ha matado al real.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]斡S胤, eso es![n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]Parece ser nuestra 雨nica opci吋n.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Escuchad bien, tengo un plan[n]sobre c吋mo podemos llevar[n]a cabo esta operaci吋n...[n][f 1 3 65535][w][e]

