[msg MSG_000_0_0 [Guardia de la sala de interrogatorios]]
[s][vp 1 0 0 16 0 0]斡...![n][f 1 3 65535][w][e]

[msg MSG_000_3_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]夷Qu姻 pasa?[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Guardia de la sala de interrogatorios]]
[s][vp 8 0 0 18 4 0]E-eh, nada...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 19 4 0]Bueno, 夷qu姻 la trae por aqu胤?[n]Pensaba que hab胤a[n]terminado con sus asuntos...[n][f 1 3 65535][w][e]

[msg MSG_000_7_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]夷Ha venido alguien m茨s?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sae]]
[s][bup 0 105 2 65535 0][vp 1 0 0 21 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]夷Nadie?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Guardia de la sala de interrogatorios]]
[s][vp 8 0 0 4 4 0]斡N-no hay ninguna raz吋n[n]para que venga nadie m茨s![n][f 1 3 65535][w][e]

[msg MSG_003_5_0 [Voz de Akechi]]
[s][vp 8 0 0 22 65535 0]S胤, el guardia ser茨 uno de los[n]nuestros, pero habr茨 que[n]carg茨rselo para eliminar pruebas...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]As胤 que es todo verdad...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Guardia de la sala de interrogatorios]]
[s][vp 8 0 0 6 4 0]斡P-por supuesto! 夷Ocurre algo?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Es Akechi. Ha tenido una urgencia[n]y no podr茨 venir hoy.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Guardia de la sala de interrogatorios]]
[s][vp 8 0 0 8 4 0]夷Eh?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Me han pedido que me ocupe[n]de ciertas cosas.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Guardia de la sala de interrogatorios]]
[s][vp 8 0 0 10 4 0]夷Usted? Pero...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Ya sabes que... si te quedas,[n]probablemente te maten[n]para eliminar las pruebas.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [(SE)見張りの警官]]
[s][vp 8 0 0 12 65535 0](息を呑む)[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Te recomiendo que te escondas[n]de inmediato si valoras tu vida.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Guardia de la sala de interrogatorios]]
[s][vp 8 0 0 14 4 0]S-s胤, se隠ora.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Y no digas ni una palabra de[n]lo que ha ocurrido. No conf胤es[n]en nadie. Olvida todo esto.[n][f 1 3 65535][w][e]

