[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 113 65535 0]Que la polic胤a capturase[n]a [f 4 2] fue[n]justo lo que planeamos.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 114 65535 0]Y yo estuve interrog茨ndolo[n]sin saber nada de esto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 115 65535 0]Pero 夷c吋mo atrajisteis a Akechi[n]a esa... sala de interrogatorios[n]del mundo cognitivo?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 120 65535 0]Solo necesitaba las coordenadas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 116 65535 0]Je, je, je...[n][f 1 3 65535][w][e]

[msg MND_003_5_0]
[s][vp 8 0 0 0 65535 0]Parece que us吋 este port茨til[n]para acceder[n]remotamente al Metaverso...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Preguntarle por 姻l ahora alargar胤a[n]demasiado la conversaci吋n...[n]Ya se lo comentar姻 luego.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Akechi mat吋 a la versi吋n falsa[n]en el Palacio y se fue creyendo[n]que hab胤a salido victorioso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Tuvo que ser divertid胤simo para[n]nuestro l胤der, que pasaba el rato[n]en la sala de interrogatorios real.[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Seguro que se puso en plan[n]sobrado al verse solo en[n]aquella c茨mara tan tranquila.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Por eso me diste tu m吋vil...[n]Solo lo cog胤 por lo que[n]me dijiste.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Qu姻 pena no haber podido[n]verlo con mis propios ojos.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Yo tampoco lo pude ver.[e]
[s]No hab胤a tiempo.[e]
[s]Me alegra no haber muerto.[e]

[msg MSG_008_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 106 65535 0]Yo solo pod胤a atender[n]a todos los mensajes que[n]empezaron a llegarme a su m吋vil.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 75 65535 0]Ah...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]As胤 que, en otras palabras,[n]he ido al Metaverso,[n]aunque solo fuera un instante.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 78 65535 0]Por nuestra experiencia, hay poco[n]peligro en que alguien entre en su[n]propio Palacio tan poco tiempo.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 79 65535 0]Ese es el otro motivo por el que[n]hicimos que te lo diese.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 80 65535 0]Necesit茨bamos que escucharas a[n]Al胤 Bab茨, que enga隠aras al guardia[n]y que lo ayudaras a escapar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 81 65535 0]Al hacerte volver a la sala[n]de interrogatorios, pudimos[n]devolverte tambi姻n al mundo real.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 85 65535 0]Bueno, tuve que pensar alg雨n[n]modo de evitar que te encontrases[n]con Akechi en pleno asesinato.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 86 65535 0]Asombroso.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]No ten胤a ni la menor idea de que[n]una operaci吋n de este calibre[n]estaba teniendo lugar dentro de m胤.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Me alegro de que [f 4 2] pudiera convencerte[n]durante el interrogatorio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Aunque conoc胤amos el plan[n]de Akechi, nos preocupaba[n]mucho esa parte.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Pues s胤.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]夷Por qu姻?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Si mi hermana no hubiera estado[n]de nuestro lado, el plan de Futaba[n]y la fuga no habr胤an sido posibles.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Convencerla era nuestra[n]gran apuesta.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]No pudimos consult茨rselo a Sae[n]de antemano, as胤 que fue el momento[n]m茨s decisivo de todo el plan.[n][f 1 3 65535][w][e]

[msg MSG_018_1_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Aun as胤, me sorprende que[n]me convencieras en tan poco tiempo.[n]夷Sab胤as que lo conseguir胤as?[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]Sin ninguna duda.[e]
[s]En absoluto.[e]
[s]Con tanto f茨rmaco, no lo recuerdo.[e]

[msg MSG_020_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 109 65535 0]Ya veo...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Sae]]
[s][bup 0 105 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 110 65535 0]Entonces, s胤 que era una situaci吋n[n]de vida o muerte, 夷no?[n]斡Qu姻 locura![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 111 65535 0]Es comprensible...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 112 65535 0]De todos modos, no puedo creer que[n]apostaseis por algo tan arriesgado...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Sab胤a que, si te explic茨bamos[n]los planes del verdadero culpable,[n]lo entender胤as todo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Te dar胤as cuenta de que [f 4 2][n]dec胤a la verdad y de que hab胤a[n]alguien peor a quien perseguir.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Por eso salimos victoriosos.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]As胤 que me ocultaste todo esto[n]para capturar al verdadero[n]culpable, 夷correcto?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]S胤. Adem茨s, por aquel[n]entonces, hab胤as perdido[n]el control sobre ti misma...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Esto es impresionante...[n]Lo 雨nico que puedo hacer es re胤rme.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]He deducido que Akechi[n]no mat吋 a nadie de verdad...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Pero 夷qu姻 hicisteis con el cuerpo?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]La polic胤a ni se molest吋[n]en mirarlo.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]夷Eh?[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Contrataron a un forense[n]para que confirmara que la muerte[n]de [f 4 2] fue un suicidio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Y ni siquiera investig吋 el lugar[n]de los hechos; tan solo falsific吋[n]el certificado de defunci吋n.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]夷Los malos tienen tanta influencia?[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Matar a alguien en una comisar胤a[n]es una temeridad. Adem茨s,[n]sab胤amos de un posible conspirador.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Gracias a los mensajes de Futaba[n]y a la conducta del guardia,[n]al final lo entend胤...[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Como los altos cargos de la polic胤a[n]no estaban al tanto del asunto,[n]se hizo el caos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Todo fue seg雨n el plan de Akechi,[n]y la prensa inform吋 del suicidio[n]de [f 4 2] en la c茨rcel.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Y aprovechando la confusi吋n,[n]pudo escapar gracias a la ayuda[n]de Niijima.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Evit姻 que la gente fuera[n]a la morgue a ver el cad茨ver.[n]Y as胤, nadie supo que sobrevivi吋.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Cuando pienso en el interrogatorio...[n]No puedo creer lo que[n]le hicieron a [f 4 2].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 40 65535 0][f 4 10 65535 0 0]El uso de la violencia[n]y los f茨rmacos no es algo normal...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Si hubiera perdido el conocimiento[n]y no le hubiera dicho a mi hermana[n]lo del tel姻fono, estar胤a muerto...[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Me alegra mucho que volvieras[n]sano y salvo, [f 4 2].[n][f 1 3 65535][w][e]

[sel SEL_040_0_0 top]
[s]Falt吋 muy poco.[e]
[s]No recuerdo mucho.[e]
[s]Fue pan comido.[e]

[msg MSG_041_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Yo casi me convierto[n]en uno de tus torturadores...[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]No. No tendr胤as que recordar[n]algo as胤...[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Eres muy duro de pelar, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Cuando vi la noticia del suicidio,[n]me qued姻 helada.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Hac胤amos vida normal[n]mientras lo interrogaban[n]para no levantar sospechas.[n][f 1 3 65535][w][e]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Pero, en mi interior,[n]no pod胤a evitar preocuparme por 姻l...[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Pues yo supe de inmediato[n]que nuestro plan hab胤a funcionado.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Quer胤a tener fe...[n]pero teniendo en cuenta[n]a lo que nos enfrent茨bamos...[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]La actitud de Ryuji[n]es m茨s bobalicona y desenfadada.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 3 301 1][vp 8 0 0 52 65535 0]斡Cierra el pico, gato![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]Tuve que ser paciente y evitar[n]este sitio hasta que pasara todo.[n]Al fin puedo respirar un poco...[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Sab胤amos que estaba vivo, pero[n]fue dif胤cil mantener la compostura[n]hasta confirmarlo en persona.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 62 65535 0]Pens茨ndolo bien, mi interrogatorio[n]fue una mera formalidad[n]para el comandante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 63 65535 0]Dejar que interrogara a alguien[n]que iba a morir era una idiotez.[n]Quer胤an evitar las represalias...[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 64 65535 0]Muy bien. De ahora en adelante,[n]har姻 lo que sea por ayudaros.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 97 65535 0]Despu姻s de todo, me hab姻is salvado.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 65 65535 0]Escuchar eso es un alivio.[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]Yo tambi姻n har姻 todo lo que pueda[n]para ayudar. Avisadme y punto.[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 70 65535 0]Y ahora, d姻monos un respiro.[n]Mi viejo cerebro est茨 hecho polvo.[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 98 65535 0]Ah, y pod姻is usar la primera planta[n]cuando os d姻 la gana[n]para reuniros y charlar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 99 65535 0]Necesitar姻is un escondite seguro.[n]Y dadme un toque cuando haga falta[n]para que cierre antes.[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 100 65535 0]夷Est茨s seguro?[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 101 65535 0]Este no puede salir. Adem茨s,[n]no avanzareis mucho si la gente[n]os escucha desde abajo.[n][f 1 3 65535][w][e]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 102 65535 0]Este local no es el m茨s ajetreado[n]de la ciudad, por lo que[n]no me supondr茨 una gran p姻rdida.[n][f 1 3 65535][w][e]

[msg MSG_060_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 103 65535 0]Perm胤tenos aceptar la oferta.[n]Qu姻 hombre tan amable...[n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 105 65535 0]Je, je.[n][f 1 3 65535][w][e]

