[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Hicimos que Akechi viniera al[n]Palacio de mi hermana, y logramos[n]que creyera matar a nuestro l胤der.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]夷Puedes explicar eso con m茨s[n]detalle? 夷Qu姻 pas吋 exactamente[n]en mi mundo cognitivo?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Sentimos haberte usado sin[n]tu permiso. Tu Palacio ten胤a todas[n]las condiciones que necesit茨bamos...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sae]]
[s][bup 0 105 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]夷Qu姻 condiciones?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Primero, necesit茨bamos un lugar[n]del mundo cognitivo que fuera[n]igual que en la realidad.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Ese sitio se basa en el mundo real,[n]despu姻s de todo. Los sitios que no[n]est茨n deformados parecen normales.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Por eso nadie salvo quien usa[n]el Navegador se da cuenta[n]de que est茨 en el Metaverso.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Cuando lo de Kamoshida,[n]entramos por la estaci吋n[n]sin darnos ni cuenta...[n][f 1 3 65535][w][e]

[sel SEL_007_5_0 top]
[s]Qu姻 recuerdos.[e]
[s]No ten胤amos ni idea.[e]
[s]Hasta que fuimos al instituto.[e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]No hay forma de notar[n]ninguna diferencia si no hay[n]algo distorsionado a la vista.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Ya hab胤amos investigado[n]el Palacio de Niijima cuando[n]Makoto nos plante吋 esta sugerencia.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Me impresion吋 mucho su propuesta.[n][f 1 3 65535][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Sinceramente,[n]no la acababa de entender,[n]pero decid胤 cooperar.[n][f 1 3 65535][w][e]

[sel SEL_011_2_0 top]
[s]Fue una gran idea.[e]
[s]Fue imprudente.[e]
[s]Decidimos fiarnos.[e]

[msg MSG_011_4_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]S胤, es estupendo que la tengamos[n]dirigiendo nuestras operaciones.[n][f 1 3 65535][w][e]

[msg MSG_011_6_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Aun as胤, conseguimos[n]que funcionase.[n][f 1 3 65535][w][e]

[msg MSG_011_8_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Y fue la mejor decisi吋n[n]que podr胤amos haber tomado.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Makoto normalmente es muy[n]tranquila... pero cuando decide algo,[n]se vuelve extra隠amente impulsiva.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Admito que ten胤a cierta[n]rivalidad con Akechi...[n][f 1 3 65535][w][e]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Pero ya no pude contenerme[n]m茨s cuando te volviste[n]un objetivo, Sae.[n][f 1 3 65535][w][e]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Si me un胤 a los Ladrones Fantasma[n]fue para curar tu coraz吋n,[n]despu姻s de todo.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Mis propios logros eran todo[n]lo que me importaba... Estaba[n]desesperada. No era yo misma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]Siento no haber podido verlo.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Eso nos pas吋 a las dos.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Supimos gracias a Mako que t雨[n]te ibas a encargar[n]del interrogatorio, Niijima.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Y con respecto a su ubicaci吋n...[n]asumo que usasteis[n]los datos de mi port茨til, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Lo siento.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Contadme el resto.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Hubo dos cosas que pudimos[n]confirmar en el Metaverso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Primero, que nuestra ropa[n]no cambi吋 cuando fuimos[n]a la sala de interrogatorios.[n][f 1 3 65535][w][e]

[msg MSG_020_5_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Segundo, que el entorno y los[n]detalles del exterior del Palacio[n]eran iguales que en el mundo real.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]En cuanto Makoto nos cont吋 esto,[n]fuimos a verlo en secreto[n]sin que lo supiera Akechi.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Tambi姻n hab胤a otra cosa[n]que necesit茨bamos[n]para que esto funcionara...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Una r姻plica cognitiva perfecta[n]de 姻l en la sala de interrogatorios[n]del Metaverso.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Pero como a雨n no lo hab胤an[n]pillado, obviamente no habr胤a[n]nadie en esa sala.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]En cuanto vimos a los clientes del[n]casino y a los polic胤as, nos qued吋[n]claro que pod胤a funcionar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]No parec胤an distintos[n]de la gente viva de verdad.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Despu姻s, solo tuvimos que abrirnos[n]paso hasta el Palacio como siempre[n]sin decirle nada a Akechi.[n][f 1 3 65535][w][e]

