[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Todo fue como estaba planeado[n]hasta que derrotamos[n]a la sombra de mi hermana.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Sin embargo, entonces nos[n]encontramos una aterradora[n]emboscada policial inesperada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Como resultado, aunque[n]logramos hacernos con el tesoro,[n]no pudimos sacarlo del Metaverso...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Solo que todo fue teatro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Ten胤amos preparado un malet胤n vac胤o[n]y solo fingimos llevarnos el tesoro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Sab胤amos que la polic胤a[n]vendr胤a a por nosotros.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Antes de actuar, nos aseguramos[n]de que la polic胤a nos tender胤a[n]una emboscada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Y tal como esper茨bamos,[n]mordi吋 el anzuelo.[n][f 1 3 65535][w][e]

