[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Parece que no ir茨s al instituto[n]durante un tiempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Tranqui, en comparaci吋n con lo que[n]nos hemos tenido que enfrentar[n]hasta ahora, esto estar茨 chupado.[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 10 301 1][vp 8 0 0 3 65535 0]斡Y tendremos mucho tiempo para[n]preparar juntos los planes![n][f 1 3 65535][w][e]

[msg MSG_083_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Para ser sincero, no me importa[n]lo que le ocurra a Shido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Es tu enemigo, as胤 que,[n]naturalmente, tambi姻n es el m胤o.[n][f 1 3 65535][w][e]

[msg MSG_089_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Estar姻 a tu lado hasta el final.[n][f 1 3 65535][w][e]

