[msg MSG_BTLSTART_001 [Ars因ne]]
[s][vp 8 0 2 1001 0 0]斡A este paso vas a acabar[n]a trocitos![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Ars因ne]]
[s][vp 8 0 2 1002 0 0]斡Odia a tus enemigos![n]Transforma ese rencor[n]en poder... 斡y lib姻ralo![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Ars因ne]]
[s][vp 8 0 2 1003 0 0]斡Mueve esa hoja![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Ars因ne]]
[s][vp 8 0 2 1004 0 0]斡Destr吋zalos hasta[n]que tu coraz吋n quede satisfecho![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Ars因ne]]
[s]斡Y ahora, acaba con ellos! 斡Termina[n]con los deseos de ese cerdo![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Ars因ne]]
[s][vp 8 0 2 1006 0 0]斡Mi poder te pertenece![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Ars因ne]]
[s][vp 8 0 2 1006 0 0]斡Mi poder te pertenece![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Ars因ne]]
[s][vp 8 0 2 1007 0 0]M茨talos de la forma que prefieras.[n]斡Dale rienda suelta[n]a los deseos de tu coraz吋n![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_009]
[s]斡En esta forma, soy la mism胤sima[n]reencarnaci吋n de la destrucci吋n,[n]jo! 斡No saldr茨s con vida, jii, jo![n][f 1 3 65535][w][e]

