[msg MSG_BTLSTART_001 [Morgana]]
[s][bup 0 3 0 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Llevas el arma a distancia, 夷verdad?[n]斡Apunta a una sombra y dispara![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Morgana]]
[s][bup 0 3 0 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]斡Apunta a una sombra y dispara![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003]
[s]Pulsa el bot吋n hacia arriba para[n]sacar tu arma y el [clr 2]bot吋n ○[clr 27][n]para disparar.[n][f 1 3 65535][w][e]
[s]Ahora puedes pulsar el bot吋n hacia la izquierda[n]o el bot吋n hacia la derecha para cambiar de[n]objetivo hasta que te quedes sin munici吋n.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Morgana]]
[s][bup 0 3 1 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]斡夷Qu姻 te ha parecido?![n]Menuda sorpresa, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Morgana]]
[s][bup 0 3 0 0 0][vp 8 0 2 1003 0 3][f 4 10 65535 0 0]En muchas ocasiones,[n]es m茨s 雨til disparar con rapidez[n]que atacar con un cuchillo.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Morgana]]
[s][bup 0 3 0 0 0][vp 8 0 2 1004 1 3][f 4 10 65535 0 0]Sobra decir que te puedes quedar[n]sin balas, pero 斡gastarlas es mejor[n]que dejar que se oxiden![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007]
[s]Las armas a distancia son[n]poderosas, pero la munici吋n que se[n]puede llevar es militada.[n][f 1 3 65535][w][e]
[s]La munici吋n no se rellenar茨[n]autom茨ticamente dentro de Palacios,[n]pero s胤 al salir de ellos.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Morgana]]
[s][bup 0 3 1 0 0][vp 8 0 2 1005 0 3][f 4 10 65535 0 0]斡Muy bien, te ense隠ar姻 mi arma[n]a ti tambi姻n![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_009 [Morgana]]
[s]行くぞ必殺、パチンコストラーイクッ![n][f 1 3 65535][w][e]

