[msg MSG_BTLSTART_001 [Prometido de Haru]]
[s][vp 8 0 2 1001 1 246]Hay que tener mano dura[n]con quienes roban a los dem茨s.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Prometido de Haru]]
[s][vp 8 0 2 1002 1 246]斡Haru! 斡P吋rtate bien![n]斡S姻 mi juguete![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Haru]]
[s][bup 0 7 122 0 0][vp 8 0 2 1003 0 7][f 4 10 65535 0 0]斡No tengo ninguna intenci吋n[n]de hablar contigo...![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Haru]]
[s][bup 0 7 122 0 0][vp 8 0 2 1004 0 7][f 4 10 65535 0 0]斡Si quiero despertar el coraz吋n[n]de mi padre, no puedo perder![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Makoto]]
[s][bup 0 6 104 0 0][vp 8 0 2 1005 0 6][f 4 10 65535 0 0]斡As胤 que este es[n]el aut姻ntico poder de Haru...![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Morgana]]
[s][bup 0 3 3 0 0][vp 8 0 2 1006 0 3][f 4 10 65535 0 0]Haru...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Morgana]]
[s][bup 0 3 2 0 0][vp 8 0 2 1007 0 3][f 4 10 65535 0 0]斡Vale, vamos all茨![n]斡Hora de machacar a ese capullo![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Prometido de Haru]]
[s][vp 8 0 2 1008 1 246]斡夷Por qu姻?! 斡夷C吋mo han podido[n]derrotarme unos mocosos?![n][f 1 3 65535][w][e]

