[msg MSG_BTLSTART_001 [Sombra de Nejima]]
[s][vp 8 0 2 1001 1 0]夷Otra vez vosotros? 斡Da igual[n]cu茨ntas veces veng茨is![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Morgana]]
[s][bup 0 3 0 0 0][vp 8 0 2 1002 0 3][f 4 10 65535 0 0]Te han ense隠ado una t姻cnica[n]para derrotarlo, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Morgana]]
[s][bup 0 3 0 0 0][vp 8 0 2 1003 0 3][f 4 10 65535 0 0]斡Pues 雨sala[n]y dale una paliza a ese tramposo![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Futaba]]
[s][bup 0 8 600 0 0][vp 8 0 2 1004 0 8][f 4 10 65535 0 0]Un jugador te ha ense隠ado[n]c吋mo derrotarlo, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Futaba]]
[s][bup 0 8 600 0 0][vp 8 0 2 1005 0 8][f 4 10 65535 0 0]斡Dale una lecci吋n[n]a ese maldito tramposo![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006]
[s][vp 1 0 0 0 0 0]En el turno de [f 4 2], selecciona[n]Arma a distancia y pulsa el [f 1 10 28][n]para efectuar un disparo de derribo.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Solo se puede utilizar una vez en[n]cada infiltraci吋n en el Metaverso,[n]pero derribar茨 al enemigo.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Sombra de Nejima]]
[s][vp 8 0 2 1008 1 0]斡No puede ser![n]斡Es imposible que pase algo as胤![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_009 [Sombra de Nejima]]
[s][vp 8 0 2 1009 1 0]斡夷Un disparo que ignora[n]mis trampas?! 斡Imposible![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010 [Sombra de Nejima]]
[s][vp 8 0 2 1010 1 0]斡Mierda! 斡Soy el m茨s fuerte![n]斡Se supone que soy el rey! Yo...[n][f 1 3 65535][w][e]

