[msg MSG_BTL_START_000 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡Voy a ser multimillonaria![n]斡Y si te metes en mi camino,[n]entonces acabar姻 contigo![n][f 1 3 65535][w][e]

[msg MSG_BTL_START_001 [Makoto]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]斡Joker, habla con ella![n]斡Seguro que as胤 se tranquiliza![n][f 1 3 65535][w][e]

[msg MSG_BTL_SYS_MSG]
[s][vp 8 0 2 0 0 0]Si retienes a los enemigos,[n]podr茨s hablar con ellos.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0]Podr茨s despertar[n]el coraz吋n del objetivo[n]si respondes correctamente.[n][f 1 3 65535][w][e]

[msg MSG_BTL_DIA_BF__000_000 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡Poder multimillonario![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0 [Makoto]]
[s][bup 0 6 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]斡Cuidado, se ha curado![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0_2 [Makoto]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]斡Joker, intenta hablar con ella![n]斡Seguro que se tranquiliza[n]cuando hable del tema![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_000 [Makoto]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]La gente que te ha comprado monedas[n]afirma ser v胤ctima de tu estafa.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_001 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]夷Estafa? 斡No s姻 de qu姻 me hablas![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_002 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡Solo les he dicho que tendr胤an m茨s[n]dinero en el futuro! 斡Est茨n[n]desesperados, no tienen un duro![n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP01_000 top]
[s]夷Cu茨ndo?[e]
[s]Solo son puntos digitales.[e]
[s]夷Cu茨nto valdr茨?[e]

[msg MSG_BTL_HOLDUP01_001_000 [Makoto]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Lo llamas 或moneda virtual位, pero[n]parece que no tiene valor[n]monetario real.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_001 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡夷Q-qu姻?! 斡Como si unos mocosos[n]como vosotros lo entendierais![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_002 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡Es superpopular en las redes![n]斡Hasta los multimillonarios[n]lo recomiendan![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_000 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡夷Para qu姻 preguntas?![n]斡Si no puedes permit胤rtelo![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_001 [Makoto]]
[s][bup 0 6 105 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Parece que no la has convencido.[n]Prueba otra cosa.[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP02_000 top]
[s]Esas cuentas son tuyas.[e]
[s]Todos trabajan contigo.[e]
[s]Entrega las monedas.[e]

[msg MSG_BTL_HOLDUP02_001_000 [Makoto]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Es una trampa para que parezca[n]m茨s leg胤timo, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_001 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡N-no tienes ninguna prueba![n]斡Deja de acusarme![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_000 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡Madre m胤a, eres tonto![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_001 [Makoto]]
[s][bup 0 6 105 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Parece que no la has convencido.[n]Prueba otra cosa.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_000_000 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡Haz lo que quieras[n]con las monedas! Si tanto[n]se han cabreado, que las vendan.[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP03_000 top]
[s]No hay manera de venderlas.[e]
[s]Las monedas son virtuales.[e]
[s]Deber胤as compr茨rselas.[e]

[msg MSG_BTL_HOLDUP03_001_000 [Makoto]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]夷C吋mo van a venderlas si la 雨nica[n]p茨gina de venta que existe[n]est茨 siempre en mantenimiento?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_001 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]Eso es...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_002 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]S-si no las necesitan,[n]斡que las gasten![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_000 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡Deja de quejarte y c吋mprate[n]un cerebro, imb姻cil![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_001 [Makoto]]
[s][bup 0 6 105 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Parece que no la has convencido.[n]Prueba otra cosa.[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP04_000 top]
[s]No valen nada.[e]
[s]Los precios son alt胤simos.[e]
[s]No sirven para nada.[e]

[msg MSG_BTL_HOLDUP04_001_000 [Makoto]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]夷D吋nde podemos comprar[n]con los puntos que creaste?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_001 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]T-todav胤a no est茨 acabado.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_002 [Makoto]]
[s][bup 0 6 102 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]斡Ya es suficiente![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_003 [Makoto]]
[s][bup 0 6 102 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Te creer茨s muy listo y que te est茨s[n]saliendo con la tuya, pero 斡lo que[n]haces es inhumano![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_004 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]Inhumano...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_000 [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]斡Yo no he dicho eso![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_001 [Makoto]]
[s][bup 0 6 105 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Parece que no la has convencido.[n]Prueba otra cosa.[n][f 1 3 65535][w][e]

[msg MSG_BTL_END [Sombra de Amai]]
[s][vp 8 0 2 50930 1 73]Lo siento...[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_OFF [Sombra de Amai]]
[s][vp 8 2 2 0 0 0]斡No puedes hablar con ella![n][f 1 3 65535][w][e]

