[msg MSG_BTL_START_000 [Sombra de Fuwa]]
[s][vp 8 2 2 50233 1 16]斡La 雨nica persona que puede[n]quejarse de mis aficiones es mi[n]esposa, y con ella me basta! 斡Vete![n][f 1 3 65535][w][e]

[msg MSG_BTL_HEAL_000 [Sombra de Fuwa]]
[s][vp 8 2 2 50246 1 16]斡Lily Miau, dame fuerzas![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FIRST_000 [Sombra de Fuwa]]
[s][vp 8 2 2 50249 1 16]U-un momento.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 50221 1 16]斡Si me voy, habr茨 un otaku[n]menos animando a Lily Miau![n][f 1 3 65535][w][e]
[s][vp 8 2 2 50206 1 16]Por favor, deja que me vaya.[n]斡Por Lily Miau![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FIRST_001 [Ryuji]]
[s][bup 0 2 107 0 0][vp 8 2 2 7026 0 2][f 4 10 65535 0 0]Entiendo que las famosas[n]sean importantes, pero no lo son[n]todo en la vida, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FIRST_002 [Ryuji]]
[s][bup 0 2 111 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Hay que decirle que hay cosas[n]m茨s importantes.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FIRST_003 [Ryuji]]
[s][bup 0 2 100 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Esto es lo que sabemos sobre 姻l.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0][f 4 10 65535 0 0]或No tiene sitio en casa位 y 或Quiere[n]involucrarse en la vida de su hijo,[n]pero no puede位.[n][f 1 3 65535][w][e]

[msg MSG_BTL_SYS_MSG]
[s][vp 8 2 2 0 0 0]Podr茨s despertar[n]el coraz吋n del objetivo[n]si respondes correctamente.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 0 0 0]斡Usa la informaci吋n[n]que has obtenido para responder![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_000_000 [Sombra de Fuwa]]
[s][vp 8 2 2 50235 1 16]斡La 雨nica persona a la que quiero[n]proteger es a Lily Miau![n]La amo, 夷lo entiendes?[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP01_000 top]
[s]A Lily Miau seguro que le preocupa.[e]
[s]Creo que s胤.[e]
[s]夷Y tu familia?[e]

[msg MSG_BTL_TALK_001_002 [Sombra de Fuwa]]
[s][vp 8 2 2 50233 1 16]No tienes derecho a hablar[n]de Lily Miau.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FAIL_002_00 [Futaba]]
[s][bup 0 8 604 0 0][vp 8 2 2 9040 0 8][f 4 10 65535 0 0]Mierda, 斡est茨 hecho una furia![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FAIL_002_00_2 [Futaba]]
[s][vp 8 2 2 0 0 0][bup 0 8 602 0 0][f 4 10 65535 0 0]Piensa lo que quieres decir[n]y vuelve a intentarlo, Joker.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_001_003_000 [Sombra de Fuwa]]
[s][vp 8 2 2 50274 1 16]斡夷Verdad?![n][f 1 3 65535][w][e]
[s][vp 8 2 2 50295 1 16]夷Ves? 斡No hac胤a nada malo![n]斡Siempre y cuando quiera[n]a Lily Miau, todo ir茨 bien![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_FAIL_003_00 [Futaba]]
[s][bup 0 8 604 0 0][vp 8 2 2 9040 0 8][f 4 10 65535 0 0]斡Hala! 斡Se ha animado de repente![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_001_001_000 [Sombra de Fuwa]]
[s][vp 8 2 2 50251 1 16]...[n][f 1 3 65535][w][e]
[s][vp 8 2 2 50220 1 16]夷Por qu姻 sacas el tema[n]de mi familia?[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_001_001_001 [Sombra de Fuwa]]
[s][vp 8 2 2 50239 1 16]Familia, eh... Pues yo con mi esposa[n]no hago m茨s que discutir.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 50275 1 16]Le he comentado que se pasa,[n]que presiona much胤simo al ni隠o...[n][f 1 3 65535][w][e]
[s][vp 8 2 2 50260 1 16]Pero no lo entiende. Mis palabras[n]no le llegan al coraz吋n.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_001_001_002 [Sombra de Fuwa]]
[s][vp 8 2 2 50284 1 16]Pero 斡no Lily Miau![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_001_001_003 [Sombra de Fuwa]]
[s][vp 8 2 2 50235 1 16]斡Lily Miau siempre me escucha![n]斡Es la 雨nica que lo hace![n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP02_000 top]
[s]Mientras tengas dinero.[e]
[s]夷No hablas con tu hijo?[e]
[s]Quiz茨 tengas raz吋n.[e]

[msg MSG_BTL_TALK_002_002_000 [Sombra de Fuwa]]
[s][vp 8 2 2 50269 1 16]斡Que te calles! 斡Me da igual![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_002_003_000 [Sombra de Fuwa]]
[s][vp 8 2 2 50262 1 16]斡夷Verdad?![n][f 1 3 65535][w][e]
[s][vp 8 2 2 50245 1 16]夷Ves? 斡No hac胤a nada malo![n]斡Siempre y cuando quiera[n]a Lily Miau, todo ir茨 bien![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_002_001_000 [Sombra de Fuwa]]
[s][vp 8 2 2 50249 1 16]夷Mi hijo?[n][f 1 3 65535][w][e]
[s][vp 8 2 2 50255 1 16]Ya no puedo hacer nada.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_002_001_001 [Sombra de Fuwa]]
[s][vp 8 2 2 50248 1 16]Me gasto el sueldo en sus discos[n]y a veces voy a los conciertos.[n]Apenas pienso en mi familia.[n][f 1 3 65535][w][e]
[s][vp 8 2 2 50224 1 16]Mi esposa fue la que dej吋[n]de preocuparse por m胤,[n]as胤 que yo hice lo mismo con ella.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_002_001_002 [Futaba]]
[s][bup 0 8 600 0 0][vp 8 2 2 9135 0 8][f 4 10 65535 0 0]Y por eso te gustan tanto[n]las famosas...[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_002_001_003 [Futaba]]
[s][bup 0 8 600 0 0][vp 8 2 2 0 0 0][f 4 10 65535 0 0]Puede que se crea que su familia[n]le da igual, pero todos[n]sabemos que no es cierto.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_002_001_004 [Futaba]]
[s][vp 8 2 2 9158 0 3][bup 0 8 602 0 0][f 4 10 65535 0 0]D胤selo, Joker.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_002_001_005 [Sombra de Fuwa]]
[s][vp 8 2 2 50234 1 16]Mi familia no me necesita...[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP03_000 top]
[s]Quiz茨 tu hijo lo piense.[e]
[s]Est茨s a tiempo de volver.[e]

[msg MSG_BTL_TALK_END [Sombra de Fuwa]]
[s][vp 8 2 2 50255 1 16]夷Hasta yo?[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_OFF [Sombra de Fuwa]]
[s][vp 8 2 2 50245 1 16]No puedes hablar con 姻l.[n][f 1 3 65535][w][e]

