[msg MSG_BTLSTART_000 [Sombra del se隠or Magario]]
[s][vp 8 2 2 50124 1 39]斡Mocoso impertinente! 斡Voy[n]a matarte de un golpe![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_001 [Sombra de la se隠ora Magario]]
[s][vp 8 2 2 50933 1 69]斡No te metas en los asuntos[n]de otras personas![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Sombra del se隠or Magario]]
[s][vp 8 2 2 51055 1 39]Nooo... Me han derrotado...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Sombra de la se隠ora Magario]]
[s][vp 8 2 2 50957 1 69]Maldita... sea...[n][f 1 3 65535][w][e]

