[msg MSG_BTL_START_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡Te dar姻 con un saque en toda[n]la cara! 斡Venga! 斡Que comience[n]el combate a muerte![n][f 1 3 65535][w][e]

[msg MSG_BTL_START_001 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Intentemos que razone.[n]Quiz茨 as胤 se lo piense mejor.[n][f 1 3 65535][w][e]

[msg MSG_BTL_SYS_MSG]
[s][vp 8 0 2 0 0 0]Si retienes a los enemigos,[n]podr茨s hablar con ellos.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0]Podr茨s despertar[n]el coraz吋n del objetivo[n]si respondes correctamente.[n][f 1 3 65535][w][e]

[msg MSG_BTL_DIA_BF__000_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡No me pienso rendir! 斡Demostrar姻[n]el coraje que he obtenido[n]de jugar al pimp吋n![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]斡夷Qu姻...?! 斡Se ha curado[n]con su esp胤ritu![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0_2 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Intentemos que razone.[n]Quiz茨 as胤 se lo piense mejor.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_000 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]A ver si me queda claro.[n]La partida estaba ama隠ada, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_001 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]Pero 夷t雨 de qu姻 hablas?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_002 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]夷Ama隠ada? Son imaginaciones[n]de la gente retorcida[n]que tiene envidia de mi fama.[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP01_000 top]
[s]夷Cu茨nto ganaste?[e]
[s]Di la verdad.[e]
[s]Los medios lo acabar茨n averiguando.[e]

[msg MSG_BTL_HOLDUP01_001_000 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Solo es cuesti吋n de tiempo[n]hasta que todos sepan la verdad.[n]Confiesa de una vez.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_001 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡Jol胤n! 斡Los medios escriben[n]lo que quieren, sea verdad o no![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_002 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]Tuve un problema en el pasado:[n]difundieron el rumor de que ten胤a[n]novio, pero no era cierto.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡Falta! 斡Te voy a demandar[n]por difamaci吋n![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_001 [Sumire]]
[s][bup 0 10 104 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Parece que no ha funcionado.[n]Quiz茨 haya que decir otra cosa.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_000_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]No pod姻is confiar en los medios.[n]夷Acaso ten姻is pruebas[n]de que fuera una conspiraci吋n?[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP02_000 top]
[s]Los medios lo contar茨n.[e]
[s]Los fans se han dado cuenta.[e]
[s]No nos fiamos de ti.[e]

[msg MSG_BTL_HOLDUP02_001_000 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Parece que has cometido el error[n]a posta. Todo el mundo lo sabe.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_001 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Adem茨s, el cliente es un fan[n]de hace mucho tiempo.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_002 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]Ja, ja, ja. 夷No crees que un fan[n]se creer胤a lo que digo?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡Red! 斡Quiero pruebas[n]que me convenzan![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_001 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]No la hemos podido convencer.[n]Deber胤amos probar de nuevo.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_000_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]Puede que no lo parezca, pero soy[n]una jugadora de pimp吋n[n]profesional a nivel mundial.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_000_001 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]夷Por qu姻 iba a necesitar[n]yo un juego ama隠ado?[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP03_000 top]
[s]El premio en met茨lico es muy bajo...[e]
[s]Porque eres d姻bil.[e]
[s]夷Lo has apostado todo?[e]

[msg MSG_BTL_HOLDUP03_001_000 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]He o胤do que hasta los profesionales[n]lo tienen dif胤cil si no ganan.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_001 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]夷Ya no aspiras a m茨s y te has[n]convertido en esclava del dinero?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_002 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]B-bueno, s胤... La cantidad[n]del premio era bastante baja.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_003 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]Pero 斡yo soy una profesional![n]斡Tengo todo el talento del mundo![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡夷Quieres dejarlo ya?! 斡Te dar姻[n]con un rev姻s donde m茨s duele![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_001 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]No la hemos podido convencer.[n]Deber胤amos probar de nuevo.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_000_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]Representaba a Jap吋n en el[n]instituto. En el extranjero[n]me llamaban 或La ni隠a drag吋n位.[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP04_000 top]
[s]Me da igual.[e]
[s]Te has topado con un muro, 夷o no?[e]
[s]Deja de hablar del pasado.[e]

[msg MSG_BTL_HOLDUP04_001_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡E-eso no es...![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_001 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Te hiciste profesional, pero te[n]costaba mucho llegar a fin de mes.[n]夷Por eso has accedido?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_002 [Sumire]]
[s][bup 0 10 102 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Entonces, 斡夷entrenaste tanto[n]y te hiciste profesional[n]para perder a prop吋sito?![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_003 [Sumire]]
[s][bup 0 10 102 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]斡Hay gente que renunci吋 a sus[n]sue隠os porque perdi吋 contra ti![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_004 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡夷Te quieres callar de una vez?![n]斡Los ni隠atos como vosotros no[n]entender胤an c吋mo me siento![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_005 [Sumire]]
[s][bup 0 10 103 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]No, te entiendo perfectamente.[n]Vivimos en un mundo en el que el[n]trabajo duro no te garantiza nada.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_006 [Sumire]]
[s][bup 0 10 103 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Por eso entiendo lo que pensar胤as[n]cuando te propusieron[n]una oferta tan tentadora...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_007 [Sumire]]
[s][bup 0 10 102 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Pero 斡hay cosas que no se pueden[n]hacer! 斡Vas a dejar en evidencia[n]el deporte que tanto amas![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_008 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]Argh...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡Argh! 斡Descalificados por hacer[n]trampas! 斡Largaos de una vez![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_001 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]No la hemos podido convencer.[n]Deber胤amos probar de nuevo.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_000_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡Dejadme en paz, puedo hacer[n]lo que me d姻 la gana![n]Adem茨s, yo no quer胤a perder.[n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP05_000 top]
[s]Los perdedores son unos quejicas.[e]
[s]Haz lo que quieras.[e]
[s]Te estaban amenazando.[e]

[msg MSG_BTL_HOLDUP05_001_000 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]夷Te dijeron algo como:[n]或Si no pierdes, est茨s muerta位?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_001 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡Aaaaaaah![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_002 [Sumire]]
[s][bup 0 10 102 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]斡Basta de disparates![n]斡Solo est茨n soltando faroles![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_003 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Si contin雨as con las partidas[n]ama隠adas, 斡lo perder茨s todo[n]y te expulsar茨n![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_004 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]Yo...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_005 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]Tienes que parar. De lo contrario,[n]alg雨n d胤a se dar茨n cuenta.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_006 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]斡Por favor, deja de traicionar a la[n]gente y de humillarte a ti misma![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_007 [Sumire]]
[s][bup 0 10 100 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]斡Recuerda c吋mo te sent胤as[n]cuando entrenabas con pasi吋n[n]e integridad![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_001_008 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]Argh...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_002_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]斡Voy a acabar con todos vosotros[n]y tambi姻n con este juego![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP05_002_001 [Sumire]]
[s][bup 0 10 104 0 0][vp 8 0 2 1001 0 10][f 4 10 65535 0 0]No la hemos podido convencer.[n]Deber胤amos probar de nuevo.[n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_OFF [Sombra de Mariko]]
[s][vp 8 2 2 0 0 0]斡No puedes hablar con ella![n][f 1 3 65535][w][e]

[msg MSG_BTL_BTLEND_000 [Sombra de Mariko]]
[s][vp 8 0 2 51130 1 42]Lista...[n][f 1 3 65535][w][e]

