[msg MSG_BTL_START_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50987 1 89]斡Dejad de hablar de plagio![n]斡No s姻 nada de eso![n][f 1 3 65535][w][e]

[msg MSG_BTL_START_001 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]斡Joker, vamos a intentar[n]convencerla de que lo deje! Estoy[n]seguro de que podemos despertarla.[n][f 1 3 65535][w][e]

[msg MSG_BTL_SYS_MSG]
[s][vp 8 0 2 0 0 0]Si retienes a los enemigos,[n]podr茨s hablar con ellos.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0]Podr茨s despertar[n]el coraz吋n del objetivo[n]si respondes correctamente.[n][f 1 3 65535][w][e]

[msg MSG_BTL_DIA_BF__000_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50969 1 89]Mmm, 斡un retoque[n]r茨pido y estar姻 bien![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]斡夷Se cur吋 con solo retocarse?![n][f 1 3 65535][w][e]

[msg MSG_BTL_ATTACK_NG__000_0_2 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]斡Joker, hablemos con ella![n]斡Quiz茨 sea m茨s f茨cil que luchar![n][f 1 3 65535][w][e]

[msg MSG_BTL_START_003]
[s][vp 8 0 2 0 0 0]Si retienes a los enemigos,[n]podr茨s hablar con ellos.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 0 0 0]Podr茨s despertar[n]el coraz吋n del objetivo[n]si respondes correctamente.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_000 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]斡Deja de hacerte la longuis[n]y cu姻ntanos la verdad![n]夷Por qu姻 acabaste plagiando?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_001 [Sombra de Chiyo]]
[s][vp 8 0 2 50965 1 89]斡No me estoy haciendo[n]la longuis! 斡C茨llate![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_000_002 [Sombra de Chiyo]]
[s][vp 8 0 2 50972 1 89]Est茨n intentando dar con el origen[n]del arte en l胤nea y no s姻[n]qu姻 m茨s, pero 斡calcar no es ilegal![n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP01_000 top]
[s]No ten胤as permiso.[e]
[s]Si es legal, 夷no pasa nada?[e]
[s]夷Son iguales por casualidad?[e]

[msg MSG_BTL_HOLDUP01_001_000 [Makoto]]
[s][bup 0 6 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Si calcaste sin permiso algo[n]que est茨 registrado,[n]se considera plagio.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_001 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Efectivamente, es ilegal.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_001_002 [Sombra de Chiyo]]
[s][vp 8 0 2 50970 1 89]夷Qu姻? Pero eso...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50933 1 89]斡Que os call姻is de una vez![n]斡No ten姻is derecho a cuestionarme![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP01_002_001 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]No la hemos convencido[n]con eso, Joker. 斡Hay que probar[n]con otro enfoque![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_000_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50969 1 89]斡Solo dicen que lo plagi姻 porque[n]tienen celos de mi popularidad![n]斡Son lo peor![n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP02_000 top]
[s]Deja de plagiar.[e]
[s]夷Cu茨nto dinero conseguiste?[e]
[s]Tu fama te a隠adi吋 presi吋n.[e]

[msg MSG_BTL_HOLDUP02_001_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50970 1 89]夷D-de qu姻 est茨s hablando?[n]Por supuesto que no estaba[n]bajo ninguna pres-[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_001 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]La popularidad te ha hecho feliz,[n]pero tambi姻n tendr茨s que hacer[n]frente a cr胤ticas mucho m茨s duras.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_001_002 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Los fans esperan mucho m茨s de ti.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50987 1 89]斡Estoy hasta los ovarios[n]de o胤r comentarios de mierda![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP02_002_001 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]No la hemos convencido[n]con eso, Joker. 斡Hay que probar[n]con otro enfoque![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_000_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50901 1 89]斡Si hasta saqu姻 cre姻 algo nuevo[n]para mis fans! [n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP03_000 top]
[s]夷Alguna novedad?[e]
[s]Qu姻 duro.[e]
[s]Se ha hecho viral.[e]

[msg MSG_BTL_HOLDUP03_001_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50970 1 89]夷Qu姻...? 夷Por qu姻 me iba a dar[n]problemas crear una historia nueva?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_001_001 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Al principio pod胤as dibujar[n]como quisieses, pero ahora te toca[n]hacer lo que te pidan.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50959 1 73]斡Como no os call姻is, os mato![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP03_002_001 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]No la hemos convencido[n]con eso, Joker. 斡Hay que probar[n]con otro enfoque![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_000_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50933 1 73]斡夷Que si ser popular es dif胤cil?![n]斡Por supuesto que no![n][f 1 3 65535][w][e]

[sel SEL_BTL_HOLDUP04_000 top]
[s]夷Porque eres pobre?[e]
[s]夷Falta de habilidad?[e]
[s]S胤 que eres popular.[e]

[msg MSG_BTL_HOLDUP04_001_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50901 1 73]斡N-no! 斡S-soy un genio,[n]que lo sepas![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_001 [Yusuke]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Empiezas a tener insomnio. Pasas[n]las noches enteras pregunt茨ndote[n]si tienes lo que hay que tener...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_002 [Yusuke]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Muchos autores lo sufrieron[n]en el pasado y seguro[n]que habr茨 m茨s casos en el futuro...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_003 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Pero 夷acaso no es ese el motivo[n]por el que la gente se esfuerza?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_004 [Sombra de Chiyo]]
[s][vp 8 0 2 50957 1 73]斡Ah...![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_005 [Yusuke]]
[s][bup 0 5 100 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Entiendo que quieras huir. Hace[n]falta mucha habilidad para crear[n]algo que los dem茨s quieran ver.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_006 [Yusuke]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Pero has tirado por tierra[n]todo lo que has conseguido.[n]夷Qu姻 intentabas proteger?[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_007 [Yusuke]]
[s][bup 0 5 103 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]Recuerda qu姻 era lo m茨s importante[n]para ti como artista.[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_001_008 [Sombra de Chiyo]]
[s][vp 8 0 2 50957 1 73]Lo que era m茨s importante para m胤...[n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50959 1 73]斡夷E-eres idiota?![n]斡Todos vosotros, haters,[n]iros de una vez a la mierda![n][f 1 3 65535][w][e]

[msg MSG_BTL_HOLDUP04_002_001 [Yusuke]]
[s][bup 0 5 104 0 0][vp 8 0 2 1001 0 3][f 4 10 65535 0 0]No la hemos convencido[n]con eso, Joker. 斡Hay que probar[n]con otro enfoque![n][f 1 3 65535][w][e]

[msg MSG_BTL_TALK_OFF [Sombra de Chiyo]]
[s][vp 8 2 2 0 0 0]斡No puedes hablar con ella![n][f 1 3 65535][w][e]

[msg MSG_BTL_BTLEND_000 [Sombra de Chiyo]]
[s][vp 8 0 2 50930 1 73]Lo m茨s importante[n]para m胤 son los c吋mics.[n][f 1 3 65535][w][e]

