[msg MSG_BTLTALKTEST_010_001]
[s][vp 1 0 0 1000 0 0][f 1 3 65535][w][e]

[msg MSG_BTLTALKTEST_010_003]
[s][vp 3 0 3 1324 0 0][f 1 3 65535][w][e]

[msg MSG_BTLARTISTENTRY_000_0 [Sombra de Madarame]]
[s][vp 8 0 2 1001 1 210]Venga, 斡al l胤o, alima隠as![n][f 1 3 65535][w][e]

[msg MSG_BTLARTISTENTRY_010_0 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 5]Utiliz吋 a los dem茨s para satisfacer[n]sus despreciables deseos, Madarame.[n][f 1 3 65535][w][e]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1003 0 5]斡Ni siquiera es usted digno[n]del arte que ha 或creado位![n][f 1 3 65535][w][e]

[msg MSG_BTLARTISTENTRY_020_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1004 0 3]斡No bajes la guardia, Joker![n]斡No sabemos de lo que es capaz![n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_100_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 3]斡Madarame est茨 KO![n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_010_000 [Sombra de Madarame]]
[s][vp 8 0 2 1006 1 210]Mierda... Soy el gran Madarame...[n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_011_000 [Sombra de Madarame]]
[s][vp 8 0 2 1007 1 210]斡El Madarame que llena[n]salas cada vez que inaugura[n]una exposici吋n![n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_012_000 [Sombra de Madarame]]
[s][vp 8 0 2 1008 1 210]斡No soy alguien a quien unos ni隠atos[n]como vosotros puedan desafiar![n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_020_004 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1009 0 5]斡Ya basta de tanto egocentrismo![n][f 1 3 65535][w][e]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1010 0 5]斡Saborea la ira de quienes sufrieron tus abusos![n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_021_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1015 0 3]夷Todav胤a sigues con eso?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1016 0 3]斡No tendremos piedad![n]斡A por 姻l, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTISTSPECIAL_00 [Sombra de Madarame]]
[s][vp 8 0 2 1017 1 210]Grrr... 斡Sois unos impertinentes![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1018 1 210]斡La 雨nica manera de que aprend茨is[n]es con unos buenos azotes![n][f 1 3 65535][w][e]

[msg MSG_BTLSEAL_000_002 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3]斡夷Qu姻 es ese ataque?![n][f 1 3 65535][w][e]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1020 0 3]斡No puede ser que solo[n]cambiemos de color![n]斡Habr茨 que tener cuidado![n][f 1 3 65535][w][e]

[msg MSG_BTLSEAL_100_002 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1021 0 3]斡Tengo una idea! 斡夷Tienes[n]el 或limpiador位 que compramos?![n][f 1 3 65535][w][e]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3]斡Es para ocasiones como esta![n]斡郁salo para borrar los colores![n][f 1 3 65535][w][e]

[msg MSG_REPORT_000_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1023 0 3]Ha vuelto a cambiar.[n][f 1 3 65535][w][e]

[msg MSG_REPORT_990_03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 3]斡夷Qu姻 hacemos?![n][f 1 3 65535][w][e]

[sel SEL_REPORT_999_000 top]
[s]Usa eso.[e]
[s]D姻mosle la vuelta a la tortilla.[e]

[msg MSG_REPORT_991_03 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0]夷No es lo que ha estado[n]usando Madarame?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 3]斡Llen姻moslo de pintura![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1032 0 3]斡Llen姻moslo de pintura![n][f 1 3 65535][w][e]

[msg MSG_REPORT_010_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1024 0 3]Oye, Joker, se me ha ocurrido[n]una buena para hacerle sufrir.[n][f 1 3 65535][w][e]

[sel SEL_REPORT_020_000 top]
[s]Soy todo o胤dos.[e]
[s]斡Qu姻 repentino![e]
[s]Cu姻ntamelo luego.[e]

[msg MSG_REPORT_030_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1025 0 3]Vale.[n]斡Mira all胤![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1026 0 3]夷Ves ese cubo tan sospechoso?[n][f 1 3 65535][w][e]

[msg MSG_REPORT_031_002 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1027 0 3]斡Primero esc雨chame![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1028 0 3]斡Mira! 夷Ves ese cubo[n]tan sospechoso?[n][f 1 3 65535][w][e]

[msg MSG_REPORT_032_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 3]斡Venga! 斡Es importante![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 3]斡Mira! 夷Ves ese cubo[n]tan sospechoso?[n][f 1 3 65535][w][e]

[msg MSG_REPORT_040_03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1031 0 3]夷No es lo que ha estado[n]usando Madarame?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1032 0 3]斡Llen姻moslo de pintura![n][f 1 3 65535][w][e]

[msg charaorder_Reiji_00]
[s][vp 8 0 2 1033 0 2]斡Vamos a llenarlo de pintura![n]夷Qu姻 os parece?[n][w][e]

[msg charaorder_Reiji_01]
[s][vp 8 0 2 1034 0 2]斡Puedo ir cuando quieras, t胤o![n][w][e]

[msg charaorder_Morgana_00]
[s][vp 8 0 2 1035 0 3]斡Vamos, llen姻moslo de pintura![n][w][e]

[msg charaorder_Morgana_01]
[s][vp 8 0 2 1036 0 3]斡Yo me encargo![n][w][e]

[msg charaorder_Ann_00]
[s][vp 8 0 2 1037 0 4]斡Deber胤amos llenarlo de pintura![n][w][e]

[msg charaorder_Ann_01]
[s][vp 8 0 2 1038 0 4]斡Estoy preparada![n][w][e]

[msg charaorder_Yugo_00]
[s][vp 8 0 2 1039 0 5]斡Es hora de humillarlo[n]llen茨ndolo de pintura![n][w][e]

[msg charaorder_Yugo_01]
[s][vp 8 0 2 1040 0 5]Yo me encargo. Dej茨dmelo a m胤.[n][w][e]

[msg MSG_PAINT_USE_EVE_000_00 [Sombra de Madarame]]
[s][vp 8 0 2 1041 1 210]斡Argh![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1042 1 210]斡夷Qu姻 narices...?! Mis poderes...[n]Se est茨n debilitando...[n][f 1 3 65535][w][e]

[msg MSG_BTLUSE_RECARM_000_00 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]斡夷Se han regenerado?![n][f 1 3 65535][w][e]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 3]Mierda... Parece que esas cosas[n]vuelven si no acabamos con ellas[n]de un solo golpe...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST80_000_000 [Sombra de Madarame]]
[s][vp 8 0 2 1045 1 210]Argh...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST80_001_000 [Sombra de Madarame]]
[s][vp 8 0 2 1046 1 210]斡Basta! 斡夷As胤 le demuestras[n]tu gratitud al hombre que te crio?![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST80_010_004 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1047 0 5]斡Silencio! 斡No malgastes[n]energ胤a![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST40_000_000 [Sombra de Madarame]]
[s][vp 8 0 2 1048 1 210]Mierda... Mierda...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST40_001_000 [Sombra de Madarame]]
[s][vp 8 0 2 1049 1 210]斡Ya basta, mocosos![n]斡Os voy a dar una...![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST40_010_004 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1050 0 5]斡夷Cree que nos asustan[n]sus amenazas?![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTISTEND_000_00 [Sombra de Madarame]]
[s][vp 8 0 2 1051 1 210]Argh... Malditos cr胤os...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1052 1 210]Si necesit茨is ayuda alg雨n d胤a,[n]os arrepentir姻is de esto...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1053 1 210]Ning雨n adulto os ayudar茨...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST25_010_004 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1054 0 5]斡Espero que est姻s listo[n]para morder el polvo, Madarame![n][f 1 3 65535][w][e]

[msg MSG_BTLARTISTENTRY_000_0_2 [Sombra de Madarame]]
[s][vp 8 0 2 1001 1 210]Venga, 斡al l胤o, alima隠as![n][f 1 3 65535][w][e]

[msg MSG_BTLARTISTENTRY_010_0_2 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 5]Utiliz吋 a los dem茨s para satisfacer[n]sus despreciables deseos, Madarame.[n][f 1 3 65535][w][e]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1003 0 5]斡Ni siquiera es usted digno[n]del arte que ha 或creado位![n][f 1 3 65535][w][e]

[msg MSG_BTLARTISTENTRY_020_0_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1004 0 3]斡No bajes la guardia, Joker![n]斡No sabemos de lo que es capaz![n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_100_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1004 0 3]斡Madarame est茨 KO![n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_010_000EX [Sombra de Madarame]]
[s][vp 8 0 2 1005 1 210]Mierda... Soy el gran Madarame...[n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_011_000EX [Sombra de Madarame]]
[s][vp 8 0 2 1006 1 210]斡El Madarame que llena salas cada vez[n]que inaugura una exposici吋n![n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_012_000EX [Sombra de Madarame]]
[s][vp 8 0 2 1007 1 210]斡No soy alguien a quien unos ni隠atos[n]como vosotros puedan desafiar![n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_020_004EX [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 5]斡Ya basta de tanto egocentrismo![n][f 1 3 65535][w][e]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1009 0 5]斡Saborea la ira de quienes[n]han sufrido tus abusos![n][f 1 3 65535][w][e]

[msg MSG_BTLHOLDUP_021_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1010 0 3]夷Todav胤a sigues con eso?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1011 0 3]斡No tendremos piedad![n]斡A por 姻l, Joker![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTISTSPECIAL_00_2 [Sombra de Madarame]]
[s][vp 8 0 2 1012 1 210]Grrr... 斡Sois unos impertinentes![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1013 1 210]斡La 雨nica manera de que aprend茨is[n]es con unos buenos azotes![n][f 1 3 65535][w][e]

[msg MSG_BTLSEAL_000_002EX [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1014 0 3]斡夷Qu姻 es ese ataque?![n][f 1 3 65535][w][e]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1015 0 3]斡No puede ser que solo[n]cambiemos de color![n]斡Habr茨 que tener cuidado![n][f 1 3 65535][w][e]

[msg MSG_BTLSEAL_100_002EX [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1021 0 3](未使用)そうだ、持ってきた『洗剤』はあるか!?[n][f 1 3 65535][w][e]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3](未使用)こういう時の為に持ってきたんだ![n]アレで洗い流しちまえ![n][f 1 3 65535][w][e]

[msg MSG_REPORT_000_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1018 0 3]Ese ataque que te cubre[n]de pintura es una lata...[n][f 1 3 65535][w][e]

[msg MSG_REPORT_990_03EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1071 0 3]夷Cu茨l es el plan?[n][f 1 3 65535][w][e]

[sel SEL_REPORT_999_000EX top]
[s]Usa eso.[e]
[s]D姻mosle la vuelta a la tortilla.[e]

[msg MSG_REPORT_991_03EX [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1019 0 3]斡...![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1020 0 3]夷No es lo que ha estado[n]usando Madarame?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1021 0 3]斡Llen姻moslo de pintura![n][f 1 3 65535][w][e]

[msg MSG_REPORT_010_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1022 0 3]Oye, Joker, se me ha ocurrido[n]una buena para hacerle sufrir.[n][f 1 3 65535][w][e]

[sel SEL_REPORT_020_000EX top]
[s]Soy todo o胤dos.[e]
[s]斡Qu姻 repentino![e]
[s]Cu姻ntamelo luego.[e]

[msg MSG_REPORT_030_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1023 0 3]斡Muy bien, mira ah胤![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1024 0 3]夷Ves ese cubo[n]tan sospechoso?[n][f 1 3 65535][w][e]

[msg MSG_REPORT_031_002EX [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1025 0 3]斡Primero esc雨chame![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1026 0 3]斡Mira! 夷Ves ese cubo[n]tan sospechoso?[n][f 1 3 65535][w][e]

[msg MSG_REPORT_032_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1027 0 3]斡Venga! 斡Es importante![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1028 0 3]斡Mira! 夷Ves ese cubo[n]tan sospechoso?[n][f 1 3 65535][w][e]

[msg MSG_REPORT_040_03EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 3]夷No es lo que ha estado[n]usando Madarame?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1030 0 3]斡Llen姻moslo de pintura![n][f 1 3 65535][w][e]

[msg charaorder_Reiji_00EX]
[s][vp 8 0 2 1031 0 2]斡Vamos a llenarlo de pintura![n][w][e]

[msg charaorder_Reiji_01EX]
[s][vp 8 0 2 1032 0 2]斡Puedo ir cuando quieras, t胤o![n][w][e]

[msg charaorder_Morgana_00EX]
[s][vp 8 0 2 1033 0 3]斡Vamos, llen姻moslo de pintura![n][w][e]

[msg charaorder_Morgana_01EX]
[s][vp 8 0 2 1034 0 3]斡Yo me encargo![n][w][e]

[msg charaorder_Ann_00EX]
[s][vp 8 0 2 1035 0 4]斡Deber胤amos llenarlo de pintura![n][w][e]

[msg charaorder_Ann_01EX]
[s][vp 8 0 2 1036 0 4]斡Estoy preparada![n][w][e]

[msg charaorder_Yugo_00EX]
[s][vp 8 0 2 1037 0 5]斡Es hora de humillarlo[n]llen茨ndolo de pintura![n][w][e]

[msg charaorder_Yugo_01EX]
[s][vp 8 0 2 1038 0 5]Yo me encargo. Dej茨dmelo a m胤.[n][w][e]

[msg MSG_PAINT_USE_EVE_000_00_2 [Sombra de Madarame]]
[s][vp 8 0 2 1039 1 210]斡Argh![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1040 1 210]斡夷Qu姻 narices...?! Mis poderes...[n]Se est茨n debilitando...[n][f 1 3 65535][w][e]

[msg MSG_BTLUSE_RECARM_000_00_2 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]斡夷Se han regenerado?![n][f 1 3 65535][w][e]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 3]Mierda... Parece que esas cosas vuelven[n]si no acabamos con ellas de un golpe...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST80_000_000_2 [Sombra de Madarame]]
[s][vp 8 0 2 1043 1 210]Argh...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST80_001_000_2 [Sombra de Madarame]]
[s][vp 8 0 2 1044 1 210]斡Basta! 斡夷As胤 le demuestras[n]tu gratitud al hombre que te crio?![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST80_010_004_2 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1045 0 5]斡Silencio! 斡No gaste saliva![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST40_000_000_2 [Sombra de Madarame]]
[s][vp 8 0 2 1047 1 210]Mierda... Mierda...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST40_001_000_2 [Sombra de Madarame]]
[s][vp 8 0 2 1048 1 210]斡Ya basta, mocosos! 斡Os voy a dar una...![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST40_010_004_2 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1049 0 5]斡夷Cree que nos asustan[n]sus amenazas?![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTISTEND_000_00_2 [Sombra de Madarame]]
[s][vp 8 0 2 1051 1 210]Argh... Malditos cr胤os...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1052 1 210]Si necesit茨is ayuda alg雨n d胤a,[n]os arrepentir姻is de esto... [n][f 1 3 65535][w][e]
[s][vp 8 0 2 1053 1 210]Ning雨n adulto os ayudar茨...[n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST25_010_004_2 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1054 0 5]斡Espero que est姻s listo[n]para morder el polvo, Madarame![n][f 1 3 65535][w][e]

[msg MSG_RESPONSE_COPY_STARTE [Sombra de Madarame]]
[s][vp 8 0 2 1057 1 210]斡Soy Madarame, el gran artista![n]A ver si os enter茨is porque si no...[n][f 1 3 65535][w][e]

[msg MSG_RESPONSE_COPY_STARTE_2 [Sombra de Madarame]]
[s][vp 8 0 2 1058 1 210]斡Lo ver姻is con vuestros propios ojos![n]斡Contemplad mi obra maestra![n][f 1 3 65535][w][e]

[msg MSG_RESPONSE_COPY_EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1059 0 3]斡夷Est茨 haciendo copias de s胤 mismo?![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1060 0 3]Ja, muy bien... 斡Crear duplicados[n]es su especialidad![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST40_010_005 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1046 0 3]斡夷Gratitud, dices?! 斡Les robaste[n]el futuro a tus estudiantes![n]夷Por qu姻 iban a estar agradecidos?[n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST25_010_003 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 3]斡Sigue siendo mejor que dejar[n]que alguien como t雨 nos utilice![n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1056 0 3]Venga, Joker, acabemos con esto.[n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST80_010_003 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1050 0 3]Amen茨zanos todo lo que quieras...[n]斡No nos vas a detener ahora![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST_FAKE_000_ [Imitaci吋n de pena]]
[s][vp 8 0 2 1061 1 210]夷Os atrev姻is a desafiar a un erudito?[n]斡Pues temblad de miedo![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST_FAKE_000__2 [Imitaci吋n de furia]]
[s][vp 8 0 2 1062 1 210]Mocosos de pacotilla...[n]斡Os reducir姻 a cenizas![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST_FAKE_000__3 [Imitaci吋n de j雨bilo]]
[s][vp 8 0 2 1063 1 210]斡Desapareced de mi vista[n]como si fuerais polvo![n][f 1 3 65535][w][e]

[msg MSG_BTL_ARTIST_FAKE_000__4 [Imitaci吋n de alegr胤a]]
[s][vp 8 0 2 1064 1 210]Mi superioridad golpea[n]como un rel茨mpago...[n]斡y ahora lo comprobar姻is![n][f 1 3 65535][w][e]

[msg MSG_RESPONSE_COPY_EX_FAI [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1065 0 3]斡Algo no va bien![n]夷Ser茨 que...?[n][f 1 3 65535][w][e]

[msg MSG_RESPONSE_COPY_EX_FAI_2 [Sombra de Madarame]]
[s][vp 8 0 2 1066 1 210]斡夷Qu姻?! Yo, el gran Madarame...[n]斡夷he cometido un error?![n][f 1 3 65535][w][e]

[msg MSG_RESPONSE_COPY_EX_FAI_3 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1067 0 5]As胤 que este es el l胤mite de sus[n]habilidades... Qu姻 infantil.[n][f 1 3 65535][w][e]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 2 1068 0 5]Y pensar que ni siquiera es capaz[n]de producir bien una de sus copias...[n]Por favor, 斡deje de decepcionarme![n][f 1 3 65535][w][e]

[msg MSG_RESPONSE_COPY_EX_FAI_4 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1069 0 5]Parece que te has superado.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1070 0 5]夷No has podido completar[n]ni una falsificaci吋n? 斡Eres lo peor![n][f 1 3 65535][w][e]

