[msg MSG_BTLSTART02_000_000 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1001 1 218]Imperdonable... 斡Imperdonable![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_010_006 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 8]Pero 夷qu姻...? 斡Est茨 volando![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_020_002 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 0 2 1003 0 3]S胤, por eso nos est茨 dando[n]lo nuestro. Solo podemos alcanzarla[n]con habilidades o disparos...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_030_006 [Futaba]]
[s][bup 0 8 600 65535 0][f 4 10 65535 0 0][vp 8 0 2 1004 0 8]Los ataques normales no sirven.[n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 8]斡Va a tocar derribarla a tiros![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_031_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1014 0 8]Nos toca... 斡All茨 va![n]Invocar姻 a nuestra arma definitiva[n]al campo de batalla.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_040_002 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1015 0 3]斡夷U-una ballesta?![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_050_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 8]斡Hay que derribarla con esto[n]y luego molerla a palos![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_060_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1009 0 3]斡Aaah, ya lo pillo! 斡Vamos![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_010_000 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1026 1 218]斡Argh! 斡夷C吋mo os atrev姻is...?![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_020_000 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1027 1 218]Los hijos que desaf胤an[n]a sus madres deber胤an... 斡morir![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_030_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1028 0 8]斡C茨llate! 斡T雨 no eres mi madre![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_040_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1029 0 8]Solo eres un monstruo[n]fruto de mi propia debilidad...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1030 0 8][f 4 10 65535 0 0]斡Seguid atacando! 斡No flaque姻is![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_050_006 [Futaba]]
[s][f 4 10 65535 0 0][vp 8 0 2 1030 0 8]斡Seguid atacando![n]斡No flaque姻is![n][f 1 3 65535][w][e]

[msg MSG_UNDER25_000_000 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1036 1 218]斡Una cr胤a que me desaf胤a[n]es un estorbo![n][f 1 3 65535][w][e]

[msg MSG_UNDER25_010_000 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1037 1 218]Y los cr胤os que me estorban...[n]斡deben morir![n][f 1 3 65535][w][e]

[msg MSG_UNDER25_020_006 [Futaba]]
[s][bup 0 8 605 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 8]Ma-mam茨...[n][f 1 3 65535][w][e]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1039 0 8]No, no es ella.[n][f 1 3 65535][w][e]

[msg MSG_UNDER25_030_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 8]斡No eres m茨s que un monstruo![n][f 1 3 65535][w][e]

[msg MSG_UNDER75_000_000 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218]Ser茨s...[n][f 1 3 65535][w][e]

[msg MSG_UNDER75_010_000 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1050 1 218]斡Malditos mocosoooos![n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_000_000 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]斡Mierda! 斡Ah胤 vuelve![n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_010_006 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 8]夷Qu姻 pasa?[n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_020_002 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]斡Nos va a atacar desde al aire![n]斡Y no sabemos cu茨ndo![n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_030_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 8]Puedo adivinarlo... con mi Persona.[n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_040_000 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1045 0 3]斡夷C吋mo?![n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_050_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1046 0 8]斡Avisar姻 cuando el enemigo[n]se acerque![n][f 1 3 65535][w][e]

[msg MSG_WAIT_000_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1047 0 8]斡Va bien por ahora! 斡Est茨 muy lejos![n][f 1 3 65535][w][e]

[msg MSG_WAIT_010_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1048 0 8]斡Se acerca sin control![n][f 1 3 65535][w][e]

[msg MSG_BTLEND02_000_002 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1131 1 218]Argh... Futaba... 斡Futaba![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1132 1 218]斡Ojal茨 nunca hubieras nacido![n][f 1 3 65535][w][e]

[msg MSG_BTLEND02_010_006 [Futaba]]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1133 0 8]Me da igual lo que me digas...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1134 0 8]斡Voy a seguir viva![n][f 1 3 65535][w][e]

[msg MSG_BTLEND02_011_006 [Futaba]]
[s][vp 8 0 2 1053 0 8]Me da igual lo que me digas...[n][f 1 3 65535][w][e]

[msg MSG_BTLEND02_012_006 [Futaba]]
[s][vp 8 0 2 1054 0 8]斡Voy a seguir viva![n][f 1 3 65535][w][e]

[msg MSG_BTLEND02_020_006 [Futaba]]
[s][vp 8 0 2 1055 0 8]斡Fuego![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_000_000EX [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1001 1 218]許さない...許さない...!(未使用)[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_010_006EX [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1002 0 8]なんだ、あいつ...飛んでるぞ。(未使用)[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_020_002EX [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 0 2 1003 0 3]ああ、そのせいでやられっぱだ。(未使用)[n]こっちの攻撃はスキルか銃しか届かねぇ...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_030_006EX [Futaba]]
[s][bup 0 8 600 65535 0][f 4 10 65535 0 0][vp 8 0 2 1004 0 8]攻撃が、届かない...(未使用)[n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 8]...なら、撃ち落とせばいい!(未使用)[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_031_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1014 0 8]Nos toca... 斡All茨 va![n]Invocar姻 a nuestra arma definitiva[n]al campo de batalla.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_040_002EX [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1015 0 3]斡夷U-una ballesta?![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_050_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1016 0 8]斡Hay que derribarla con esto[n]y luego molerla a palos![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART02_060_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1017 0 3]斡Aaah, ya lo pillo! 斡Vamos![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_010_000EX [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1034 1 218]斡Argh! 斡夷C吋mo os atrev姻is...?![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_020_000EX [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1035 1 218]Los hijos que desaf胤an[n]a sus madres deber胤an... 斡morir![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_030_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1036 0 8]斡C茨llate! 斡T雨 no eres mi madre![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_040_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1037 0 8]Solo eres un monstruo[n]fruto de mi propia debilidad...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1038 0 8][f 4 10 65535 0 0]斡Seguid atacando! 斡No flaque姻is![n][f 1 3 65535][w][e]

[msg MSG_BTLTALK_050_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 8]斡Seguid atacando! 斡No flaque姻is![n][f 1 3 65535][w][e]

[msg MSG_UNDER25_000_000EX [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1036 1 218]逆らう子供は...要らない!!(未使用)[n][f 1 3 65535][w][e]

[msg MSG_UNDER25_010_000EX [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1037 1 218]要らない子供はァァ...殺ォォォす!!(未使用)[n][f 1 3 65535][w][e]

[msg MSG_UNDER25_020_006EX [Futaba]]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1038 0 8]お、お母さん...(未使用)[n][f 1 3 65535][w][e]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1039 0 8]......。(未使用)[n]...いや、違う。[n][f 1 3 65535][w][e]

[msg MSG_UNDER25_030_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1040 0 8]おまえはただの怪物だッ!!(未使用)[n][f 1 3 65535][w][e]

[msg MSG_UNDER75_000_000EX [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218]こ、このッ...(未使用)[n][f 1 3 65535][w][e]

[msg MSG_UNDER75_010_000EX [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1050 1 218]クソガキどもぉぉーっ!(未使用)[n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_000_000EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1041 0 3]くそっ! またか!(未使用)[n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_010_006EX [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 8]どうした?(未使用)[n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_020_002EX [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1043 0 3]アイツ、空から落下攻撃する気なんだ!(未使用)[n]でも、いつ仕掛けて来るかわかんねぇ...[n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_030_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1044 0 8]わかるぞ...わたしのペルソナなら。(未使用)[n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_040_000EX [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 2 1045 0 3]何!?(未使用)[n][f 1 3 65535][w][e]

[msg MSG_SPECIALUSE_050_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1046 0 8]敵が近付いたら言う!(未使用)[n][f 1 3 65535][w][e]

[msg MSG_WAIT_000_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1047 0 8]今は大丈夫!(未使用)[n]...アイツの気配、遠い![n][f 1 3 65535][w][e]

[msg MSG_WAIT_010_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1048 0 8]あいつが急接近中!(未使用)[n][f 1 3 65535][w][e]

[msg MSG_BTLEND02_000_002EX [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1131 1 218]斡Argh...! Futaba...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1132 1 218]斡Ojal茨 nunca hubieras nacido![n][f 1 3 65535][w][e]

[msg MSG_BTLEND02_010_006EX [Futaba]]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1133 0 8]Me da igual lo que me digas...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1054 0 8]斡Voy a seguir viva![n][f 1 3 65535][w][e]

[msg MSG_BTLEND02_011_006EX [Futaba]]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1133 0 8]Me da igual lo que me digas...[n][f 1 11 65535][w][e]

[msg MSG_BTLEND02_012_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1134 0 8]斡Voy a seguir viva![n][f 1 11 65535][w][e]

[msg MSG_BTLEND02_020_006EX [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1135 0 8]斡Fuego![n][f 1 11 65535][w][e]

[msg MSG_BTL_EXQ01_001_001 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1001 1 218]斡Futabaaa! 斡Yo no te eduqu姻 as胤![n]斡夷Y c吋mo te atreves[n]a juntarte con esa gentuza?![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1002 1 218]斡Lo que tendr胤as que hacer[n]es obedecerme![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_001_002 [Futaba]]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1003 0 8]Ma-mam茨...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_001_002ADD [Futaba]]
[s][bup 0 8 600 65535 0][f 4 10 65535 0 0][vp 8 0 2 1004 1 218]No, no es ella.[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_001_002B [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1005 0 8]斡No eres m茨s que un monstruo![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_001_003 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1051 1 218](未使用)EX冒頭質問[n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ01_001_001 top]
[s](未使用)答え1(大正解)[e]
[s](未使用)答え2(正解)[e]
[s](未使用)答え3(不正解)[e]

[msg MSG_BTL_EXQ01_002_001 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1051 1 218](未使用)EX冒頭質問[n]答え1のリアクション(大正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_002_002 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1051 1 218](未使用)EX冒頭質問[n]答え2のリアクション(正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_002_003 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218](未使用)EX冒頭質問[n]答え3のリアクション(不正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_001_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1026 1 218]EX冒頭質問_2の前振り[n](未使用)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_001_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1006 1 218]斡夷Le contestas a tu propia madre?![n]斡Has pasado demasiado tiempo[n]con esos mocosos insolentes![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1007 1 218]斡Los aplastar姻![n][f 1 3 65535][w][e]

[msg MSG_BTL_PRE_BLOCK [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1008 0 3]斡Mierda! Se va a abalanzar sobre nosotros[n]otra vez, 夷no? 夷Qu姻 hacemos?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_001_005 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1009 0 8]No os preocup姻is. 斡Yo me encargo![n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ01_001_002 top]
[s]Contamos contigo.[e]
[s]夷Lo tienes?[e]

[msg MSG_BTL_1ST_ATTACK [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1011 1 218]斡Moriiiiiiiiiid![n][f 1 11 65535][w][e]

[msg MSG_BTL_1ST_BLOCK [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1018 0 8]Este es el mundo de mi coraz吋n,[n]夷no? 斡Deber胤a poder piratear[n]mi distorsi吋n sin problema![n][f 1 11 65535][w][e]

[msg MSG_BTL_1ST_BLOCKED [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1012 0 8]斡Va a ser que no![n][f 1 11 65535][w][e]

[msg MSG_BTL_1ST_BLOCKED2 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1013 1 218]Grrr... 斡Mocosos de mierda![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ05_001_001 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1104 1 218]斡Futaba! 斡Futaba, Futaba, Futabaaaaaa![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ05_001_002 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8](未使用)EX最終質問のヒント[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ05_001_003 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1105 1 218]斡Da igual lo que digas![n]Futaba me pertenece.[n]Desafiar a una madre es una verg鵜enza.[n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ05_001_001 top]
[s]Nos llevamos a Futaba.[e]
[s]Est茨s acabada.[e]

[msg MSG_BTL_EXQ05_002_001 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1106 1 218]C茨llate... 斡C茨llate![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ05_002_002 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1051 1 218]EX最終質問答え2のリアクション(正解)[n](未使用)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ05_002_003 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218]EX最終質問答え3のリアクション(不正解)[n](未使用)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_WRONG_ [Futaba]]
[s][bup 0 8 605 65535 0][f 4 10 65535 0 0][vp 8 0 2 1046 0 8]斡N-no![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_WRONG__2 [Futaba]]
[s][bup 0 8 605 65535 0][f 4 10 65535 0 0][vp 8 0 2 1053 0 8]E-eso no...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_WRONG__3 [Futaba]]
[s][bup 0 8 605 65535 0][f 4 10 65535 0 0][vp 8 0 2 1060 0 8]斡No, para![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_WRONG__4 [Futaba]]
[s][bup 0 8 605 65535 0][f 4 10 65535 0 0][vp 8 0 2 1069 0 8]P-para... 斡No quiero o胤rlo![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_WRONG__5 [Futaba]]
[s][bup 0 8 605 65535 0][f 4 10 65535 0 0][vp 8 0 2 1096 0 8]Y-yo...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_WRONG__6 [Futaba]]
[s][bup 0 8 605 65535 0][f 4 10 65535 0 0][vp 8 0 2 1102 0 8]斡Mentira![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1107 0 8]斡S胤, eso es![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_2 [Futaba]]
[s][bup 0 8 605 65535 0][f 4 10 65535 0 0][vp 8 0 2 1111 0 8]斡...![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_3 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1112 0 8]斡Recuerda la verdad![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_4 [Futaba]]
[s][bup 0 8 601 65535 0][f 4 10 65535 0 0][vp 8 0 2 1108 0 8]斡Tiene raz吋n![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_CORREC [Futaba]]
[s][bup 0 8 601 65535 0][f 4 10 65535 0 0][vp 8 0 2 1109 0 8]斡De eso nada![n][f 1 11 65535][w][e]

[msg MSG_BTL_EX_FUTABA_WRONG [Futaba]]
[s][bup 0 8 603 65535 0][f 4 10 65535 0 0][vp 8 0 2 1114 0 8]夷Eh? M-mam茨...[n][f 1 11 65535][w][e]

[msg MSG_BTL_EX_FUTABA_CORREC_2 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1117 0 8]夷Y qu姻 tal esto?[n][f 1 11 65535][w][e]

[msg MSG_BTL_EX_FUTABA_PRE_WR [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1061 1 218]斡S胤胤胤, Futaba![n]Qu姻date con mam茨 para siempre.[n][f 1 11 65535][w][e]

[msg MSG_BTL_EX_FUTABA_PRE_WR_2 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1083 1 218]斡Es in雨til! De los pecados no se puede huir.[n][f 1 11 65535][w][e]

[msg MSG_BTL_EX_FUTABA_PRE_WR_3 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1103 1 218]斡夷Ves?! 斡Lo que yo dec胤a![n]Futaba, tu felicidad consiste en morir conmigo.[n][f 1 11 65535][w][e]

[msg MSG_BTL_EX_FUTABA_PRE_WR_4 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1119 1 218]斡A los ni隠os que se enfrentan[n]a sus padres hay que castigarlos![n][f 1 11 65535][w][e]

[msg MSG_BTL_EX_FUTABA_PRE_FL [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1120 1 218]斡Pu隠eteros mocosos![n][f 1 11 65535][w][e]

[msg MSG_BTL_EX_FUTABA_CORREC_3 [Futaba]]
[s][bup 0 8 601 65535 0][f 4 10 65535 0 0][vp 8 0 2 1110 0 8]斡Es la hora de mi poder![n][f 1 11 65535][w][e]

[msg MSG_BTL_EX_FUTABA_OBSTRU [Futaba]]
[s][bup 0 8 605 65535 0][f 4 10 65535 0 0][vp 8 0 2 1118 0 8]斡No, no...![n][f 1 11 65535][w][e]

[msg MSG_BTL_EX_FUTABA_PRE_WR_5 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1121 1 218]斡Vais a ver lo que les pasa[n]a quienes se interponen en mi camino![n][f 1 11 65535][w][e]

[msg MSG_BTL_EXQ02_001_001 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1039 1 218]斡Aj! Con lo que me he esforzado[n]para educarte... 斡夷C吋mo te atreves[n]a darle la espalda a tu madre?![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_001_002 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8](未使用)EX質問1_1[n]パレスでのパズル1を見てきたら答えられるはずだ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_001_003 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1040 1 218]斡Soy tu madre! 斡La 雨nica que tienes[n]en este horrible mundo![n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ02_001_001 top]
[s]Cierto...[e]
[s]No es verdad.[e]

[msg MSG_BTL_EXQ02_002_001 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1041 1 218]斡夷C吋mo?! 斡夷Por qu姻 no lo admites?![n]夷Por qu姻, por qu姻, por qu姻...?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_002_002 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1045 1 218]Es verdad. 斡Soy la madre de Futaba![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_002_003 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218]EX質問1_1(未使用)[n]答え3のリアクション(不正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_001_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1026 1 218](未使用)EX質問1_2正解ルート[n]なら、この質問には答えられるかしら?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_001_005 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8](未使用)EX質問1_2正解ルート[n]壁画1を見てきたら答えられるはずだ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_001_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1054 1 218]Para sobrevivir en un mundo tan[n]cruel, la gente necesita[n]madres que se preocupen... 斡como yo![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1055 1 218]斡夷Entendido?![n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ02_001_002 top]
[s]Quiz茨 tengas raz吋n.[e]
[s]Eres una impostora.[e]

[msg MSG_BTL_EXQ02_002_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1056 1 218]斡夷Soy... una impostora?![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_002_005 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1059 1 218]斡Claro! 斡Futaba no puede vivir sin m胤![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_002_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218]EX質問1_2(未使用)[n]答え3のリアクション(不正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_011_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1026 1 218](未使用)EX質問1_2不正解ルート[n]なら、この質問には答えられるかしら?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_011_005 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8](未使用)EX質問1_2不正解ルート[n]壁画1を見てきたら答えられるはずだ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ02_011_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1047 1 218]斡Futaba ser茨 feliz aqu胤![n]En la realidad solo hay dolor.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1048 1 218]斡No dejar姻 que nadie se la lleve![n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ02_011_002 top]
[s]Futaba estar茨 bien.[e]
[s]Puede que tengas raz吋n...[e]

[msg MSG_BTL_EXQ01_012_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218]斡夷Qu姻?! 夷Qu姻 pruebas tienes[n]para afirmar semejante tonter胤a?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_012_005 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1052 1 218]斡S胤! 斡Futaba me pertenece![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ01_012_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218]EX質問1_2(未使用)[n]答え3のリアクション(不正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_001_001 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1062 1 218]斡Futabaaa! Si no te hubiera tenido...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1063 1 218]Es culpa tuya... 斡Me has jodido la vida![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_001_002 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8](未使用)EX質問2_1[n]壁画2を見てきたら答えられるはずだ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_001_003 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1064 1 218]斡Has fastidiado mi investigaci吋n![n]斡No deber胤a haberte tenido![n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ03_001_001 top]
[s]Conque as胤 se sent胤a...[e]
[s]No tienes raz吋n.[e]

[msg MSG_BTL_EXQ03_002_001 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1065 1 218]No, eso es lo que siempre[n]he pensado. Sin Futaba, yo...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_002_002 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1068 1 218]斡S胤! No paraba de darme la tabarra.[n]Si no hubiera tenido[n]a Futaba, habr胤a sido libre.[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_002_003 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218]EX質問2_1(未使用)[n]答え3のリアクション(不正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_001_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1026 1 218](未使用)EX質問2_2正解ルート[n]なら、この質問には答えられるかしら?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_001_005 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8](未使用)EX質問2_2正解ルート[n]壁画2を見てきたら答えられるはずだ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_001_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1097 1 218]Da igual cu茨nto te resistas,[n]斡jam茨s podr茨s huir de m胤![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1098 1 218]斡La culpa te perseguir茨[n]para siempre![n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ03_001_002 top]
[s]La hemos recuperado.[e]
[s]Bueno, si usamos la investigaci吋n...[e]

[msg MSG_BTL_EXQ03_002_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1099 1 218]P-pero eso es imposible...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_002_005 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1101 1 218]Aunque lo intentarais, no servir胤a de nada.[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_002_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218]EX質問2_2(未使用)[n]答え3のリアクション(不正解))[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_011_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1026 1 218](未使用)EX質問2_2不正解ルート[n]なら、この質問には答えられるかしら?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_011_005 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8](未使用)EX質問2_2不正解ルート[n]壁画2を見てきたら答えられるはずだ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_011_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1090 1 218]Da igual lo que digas, Futaba.[n]斡No eres m茨s que una fracasada[n]incapaz de vivir una vida normal![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1091 1 218]Con lo rara que eres, es evidente[n]que ser胤as m茨s feliz aqu胤.[n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ03_011_002 top]
[s]夷Es eso cierto?[e]
[s]El futuro se puede cambiar.[e]

[msg MSG_BTL_EXQ03_003_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1092 1 218]斡夷El... futuro...?![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_003_005 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1075 1 218]斡Exacto! Futaba no me importaba[n]lo m茨s m胤nimo.[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ03_003_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1049 1 218](未使用)EX質問2_2(未使用)[n]答え3のリアクション(不正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_001_001 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1084 1 218]斡Futaba, no mereces vivir![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_001_002 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8](未使用)EX質問3_1[n]壁画3を見てきたら答えられるはずだ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_001_003 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1084 1 218]斡Futaba, no mereces vivir![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1085 1 218]Es lo que escrib胤 en mi nota de[n]suicidio. 斡Es un hecho irrefutable![n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ04_001_001 top]
[s]Eso se hab胤a fraguado.[e]
[s]La verdad no se puede cambiar.[e]

[msg MSG_BTL_EXQ04_002_001 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1086 1 218]夷Era falsa? 斡No puede ser![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_002_002 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1088 1 218]斡S胤! 斡La nota de suicidio lo es todo![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_002_003 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1051 1 218](未使用)EX質問3_1(未使用)[n]答え3のリアクション(不正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_001_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1051 1 218](未使用)EX質問3_2正解ルート[n]なら、この質問には答えられるかしら?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_001_005 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8](未使用)EX質問3_2正解ルート[n]壁画3を見てきたら答えられるはずだ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_001_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1097 1 218]Da igual cu茨nto te resistas,[n]斡jam茨s podr茨s huir de m胤![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1098 1 218]斡La culpa te perseguir茨[n]para siempre![n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ04_001_002 top]
[s]La hemos recuperado.[e]
[s]Bueno, si usamos la investigaci吋n...[e]

[msg MSG_BTL_EXQ04_002_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1099 1 218]P-pero eso es imposible...[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_002_005 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1101 1 218]Aunque lo intentarais, no servir胤a de nada.[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_002_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1051 1 218]EX質問3_2(未使用)[n]答え3のリアクション(不正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_011_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1051 1 218](未使用)EX質問3_2不正解ルート[n]なら、この質問には答えられるかしら?[n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_011_005 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1055 0 8](未使用)EX質問3_2不正解ルート[n]壁画3を見てきたら答えられるはずだ![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_011_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1090 1 218]Da igual lo que digas, Futaba.[n]斡No eres m茨s que una fracasada[n]incapaz de vivir una vida normal![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1091 1 218]Con lo rara que eres, es evidente[n]que ser胤as m茨s feliz aqu胤.[n][f 1 3 65535][w][e]

[sel SEL_BTL_EXQ04_011_002 top]
[s]夷Es eso cierto?[e]
[s]El futuro se puede cambiar.[e]

[msg MSG_BTL_EXQ04_012_004 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1092 1 218]斡夷El... futuro...?![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_012_005 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1095 1 218]斡Pues claro que s胤![n]斡No escapar茨s, Futaba![n][f 1 3 65535][w][e]

[msg MSG_BTL_EXQ04_012_006 [Wakaba Isshiki cognitiva]]
[s][vp 8 0 2 1051 1 218]EX質問3_2(未使用)[n]答え3のリアクション(不正解)[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_5 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1042 0 8]Mi madre ya no est茨. Por mucho[n]que desee estar con ella,[n]nunca se har茨 realidad.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1043 0 8][f 4 10 65535 0 0]Por eso vivir姻 en el mundo real,[n]aunque ella ya no est姻 conmigo.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1044 0 8][f 4 10 65535 0 0]斡Y ser姻 tan libre[n]y feliz como pueda![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_6 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1050 0 8]斡Pues tiene raz吋n![n]Y se debe a que ya no estoy sola.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1051 0 8][f 4 10 65535 0 0]斡Acabar姻 siendo feliz![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_7 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1057 0 8]Mira, adoro a mi madre y la quiero[n]much胤simo, pero 斡no eres ella![n][f 1 3 65535][w][e]
[s][vp 8 0 2 1058 0 8][f 4 10 65535 0 0]Y nunca vivir姻 una vida[n]en la que los dem茨s decidan por m胤.[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_8 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1066 0 8]Mentira. 斡Mi madre me lo dijo![n]Me dijo que, pasara lo que pasara,[n]se esforzar胤a por m胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1067 0 8][f 4 10 65535 0 0]斡Quien supuso que mi existencia[n]era una carga para ella fui yo![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_9 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1093 0 8]No pasa nada por equivocarme.[n]Si caigo, solo tengo que [n]volver a levantarme.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1094 0 8][f 4 10 65535 0 0]Y lo mismo se aplica[n]a este momento.[n]斡Esta gente me lo ha ense隠ado![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_10 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1100 0 8]斡No! Con ellos,[n]hasta lo imposible es posible.[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_11 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1087 0 8]Es cierto. 斡La nota era una vil[n]mentira! 斡Mi madre no se suicid吋![n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_12 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1100 0 8]斡No! Con ellos,[n]hasta lo imposible es posible.[n][f 1 3 65535][w][e]

[msg MSG_BTL_EX_FUTABA_REACTI_13 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1093 0 8]No pasa nada por equivocarme.[n]Si caigo, solo tengo que [n]volver a levantarme.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1094 0 8][f 4 10 65535 0 0]Y lo mismo se aplica[n]a este momento.[n]斡Esta gente me lo ha ense隠ado![n][f 1 3 65535][w][e]

