[msg MSG_BTLSTART_000_000 [Akechi]]
[s][vp 8 0 2 1001 1 232]斡Os matar姻! 斡Os destruir姻![n]斡Os aplastar姻![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_010_000 [Akechi]]
[s][vp 8 0 2 1002 1 232]斡Los compa隠eros no son[n]m茨s que basura![n][f 1 3 65535][w][e]

[msg MSG_BTLHPU75_000_000 [Akechi]]
[s][vp 8 0 2 1003 1 232]斡No sois m茨s que unos mierdas[n]que se lamen las heridas[n]los unos a otros![n][f 1 3 65535][w][e]

[msg MSG_BTLHPU75_010_000 [Akechi]]
[s][vp 8 0 2 1004 1 232]斡Cualquier cosa vale...[n]si dec胤s que sois compa隠eros![n][f 1 3 65535][w][e]

[msg MSG_BTLHPU25_000_000 [Akechi]]
[s][vp 8 0 2 1005 1 232]斡夷Por qu姻... me mir茨is as胤?![n]Yo... he triunfado hasta ahora...[n]斡sin la ayuda de nadie![n][f 1 3 65535][w][e]

[msg MSG_BTLHPU25_010_000 [Akechi]]
[s][vp 8 0 2 1006 1 232]Yo no necesito... compa隠eros... No...[n][f 1 3 65535][w][e]

