[msg MSG_BTLBOSSECT01_999_001 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 2 1015 0 3]斡Destruyamos esta cosa[n]cuanto antes! 斡Vamos, equipo...[n]a darlo todo![n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSECT01_000_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1014 0 8]Muy bien, 斡a por todas![n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_000_000 [(SE)囚人シャドウの男声A]]
[s]やめろぉ...やめてくれ...![n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_010_000 [(SE)囚人シャドウの女声A]]
[s]『聖杯』に触らないで![n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_020_001 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1004 0 8]夷El Santo Grial...?[n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_030_006 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 8]斡夷Qu姻 ha sido eso?![n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1007 0 8]Maldici吋n... se ha curado...[n]Estamos en las mismas[n]que cuando empezamos a atacar...[n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1012 0 8]夷Eh? Espera, el color...[n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_930_006 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 8]斡夷Qu姻 ha sido eso?![n][f 1 3 65535][w][e]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1012 0 8]夷Eh? Espera, el color...[n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_931_006 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1006 0 8]斡夷Qu姻 ha sido eso?![n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_932_006 [Futaba]]
[s][bup 0 8 602 65535 0][f 4 10 65535 0 0][vp 8 0 2 1012 0 8]夷Eh? Espera, el color...[n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_040_000 [(SE)囚人シャドウの男声B]]
[s]そうだ! 聖杯は不滅なんだ![n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_050_000 [(SE)囚人シャドウの女声B]]
[s]ああ、その輝き...永遠にぃ![n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_060_001 [Morgana]]
[s]No fastidies... 斡夷Los reclusos[n]le est茨n dando su fuerza...?![n][f 1 3 65535][w][e]

[msg MSG_BTLBOSSHPALL_060_006 [Futaba]]
[s][bup 0 8 604 65535 0][f 4 10 65535 0 0][vp 8 0 2 1011 0 8]No fastidies... 斡夷Los reclusos[n]le est茨n dando su fuerza...?![n][f 1 3 65535][w][e]

