[msg MSG_BTLSTART_001 [Abismo retorcido]]
[s][vp 8 0 2 1001 1 521]Qu姻 imb姻ciles. Mira que rechazar[n]a nuestro se隠or...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_000 [Akechi]]
[s][bup 0 9 802 65535 0][vp 8 0 2 1002 0 9][f 4 10 65535 0 0]Qu姻 asco.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1003 0 9][f 4 10 65535 0 0]斡No hemos venido para escuchar[n]tus gilipolleces![n][f 1 3 65535][w][e]

[msg MSG_ACTSTART_001 [Abismo retorcido]]
[s][vp 8 0 2 1004 1 521]No...[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1005 1 521]斡No bastar茨 con esos intentos tan pat姻ticos![n][f 1 3 65535][w][e]

[msg MSG_ACTSTART_002 [Akechi]]
[s][bup 0 9 802 65535 0][vp 8 0 2 1006 0 9][f 4 10 65535 0 0]Tss... Este payaso no se rinde.[n][f 1 3 65535][w][e]

[msg MSG_BTLGATTAI_002 [Abismo retorcido]]
[s][vp 8 0 2 1007 1 521]Aceptad su clemencia... 斡Rend胤os[n]ante 姻l![n][f 1 3 65535][w][e]

[msg MSG_BTLGATTAI_001 [Akechi]]
[s][bup 0 9 802 65535 0][vp 8 0 2 1008 0 9][f 4 10 65535 0 0]Deja ya de soltar memeces.[n][f 1 3 65535][w][e]
[s][vp 8 0 2 1009 0 9][f 4 10 65535 0 0]斡Joker! Voy a cerrarle la boca a esa cosa.[n]斡畏chame una mano![n][f 1 3 65535][w][e]

[msg MSG_BTLEND_000]
[s]Ya puedes ejecutar una habilidad combinada[n]entre [f 4 2] y Akechi. Solo se puede[n]activar durante el turno de Akechi.[n][f 1 3 65535][w][e]

[msg MSG_BTLEND_001 [Akechi]]
[s][bup 0 9 805 65535 0][vp 8 0 2 1010 0 9][f 4 10 65535 0 0]Je, no est茨 mal para ser una t姻cnica[n]improvisada.[n][f 1 3 65535][w][e]

