[msg MSG_DUMMY]
[s]...[n][w][e]

[msg MSG_DUMMY_UPDATE]
[s]dummy messageSel[n][w][e]

[msg MSG_SHORTCUT_AJITO_NG_TI]
[s]Lo mejor ser茨 que los avise de d胤a[n]o despu姻s de clase[n]para que vayan al escondite.[n][w][e]

[msg MSG_SHORTCUT_AJITO_NG_KF]
[s]Ahora no.[n]Ya les dir姻 que vayan[n]al escondite en otra ocasi吋n.[n][w][e]

[msg MSG_IN_KF_EVENT]
[s]No es momento de ir a otro sitio.[n][w][e]

[msg MSG_IN_KF_EVENT_MORU [Morgana]]
[s]Eh, no es el momento[n]de irse por ah胤.[n][w][e]

[msg MSG_SHORTCUT_AJITO]
[s]夷Llamo a los dem茨s[n]para que vayan al escondite?[n][w][e]

[sel SEL_SHORTCUT_AJITO top]
[s]Avisar para que vayan al escondite[e]
[s]Decidir luego[e]

[msg MSG_NG_ROJIURA_OUT [Morgana]]
[s]斡La ciudad es peligrosa de noche![n]Hace falta ser muy valiente.[n][w][e]
[s]Para recorrer las calles de noche,[n]recomiendo mucho [f 4 11 3][clr 26][f 4 12 3][clr 27][n]para conseguir [clr 1]nervios de acero[clr 27].[n][w][e]

[msg MSG_NG_GO_OUT [Morgana]]
[s]Estar茨s cansado.[n]Deber胤amos irnos a dormir.[n][w][e]

[msg MSG_GO_OUT_FRIEND [Morgana]]
[s]夷En serio quieres salir teniendo[n]un amigo en casa?[n][w][e]

[sel SEL_GO_OUT_FRIEND top]
[s]Salir[e]
[s]Cancelar[e]

[msg MSG_SPOT_AFTERNOON_ERROR]
[s]Deber胤a ir a los torniquetes.[n][w][e]

[msg MSG_SPOT_NIGHT_ERROR]
[s]Estoy cansado,[n]as胤 que deber胤a irme a la cama.[n][w][e]

[msg MND_MAIL_NG]
[s]Estoy cansado.[n]Ya saldr姻 en otra ocasi吋n.[n][w][e]

[msg MND_RETURNHOME_NORMAL]
[s]夷Deber胤a volver a casa[n]y pasar la noche all胤?[n][w][e]

[sel SEL_RETURNHOME top]
[s]Ir a casa[e]
[s]A雨n no[e]

[msg MND_RETURNHOME_SLEEP]
[s]夷Lo dejo ya y me voy a dormir?[n][w][e]

[sel SEL_RETURNHOME_SLEEP top]
[s]Ir a dormir[e]
[s]A雨n no[e]

[msg MSG_LOOK_EVT_713_010_TOD [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Por lo que se ve,[n]no vamos a ninguna parte.[n]Volvamos en otra ocasi吋n.[n][w][e]

[msg MSG_LOOK_EVT_713_010_TOD_2]
[s]Parece que con esto no voy[n]a ninguna parte. Quiz茨 deber胤a[n]volver en otra ocasi吋n.[n][w][e]

[msg MSG_DUMMY_TEST_END]
[s]dummy messageSel[n][w][e]

[msg MSG_GOTO_AJITO_HOLIDAY_R [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7018 65535 0]Ah, 夷quedamos en el escondite?[n]Aunque los dem茨s van a[n]tardar en llegar.[n][w][e]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 7029 65535 0]斡Mierda! Se me ha olvidado algo.[n]斡Vuelvo enseguida![n][w][e]

[msg MSG_GOTO_2F_HOLIDAY_RYUJ [Ryuji]]
[s][bup 0 2 0 3 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, 夷todav胤a tienes algo que hacer?[n][w][e]

[sel SEL_GOTO_2F_HOLIDAY top]
[s]S胤.[e]
[s]No.[e]

[msg MSG_GOTO_2F_HOLIDAY_RYUJ_2 [Ryuji]]
[s][bup 0 2 0 3 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, 夷s胤? Entonces puede que[n]yo tambi姻n salga.[n][w][e]

[msg MSG_GOTO_2F_HOLIDAY_RYUJ_3 [Ryuji]]
[s][bup 0 2 1 3 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entonces, 夷quieres quedar?[n][w][e]

[msg MSG_GOTO_AJITO_HOLIDAY_Y [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4130 65535 0]夷Quedamos en el escondite?[n]Eso significa que yo llegar姻[n]primero... 夷Eh?[n][w][e]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 4065 65535 0]Ay, se me han olvidado mis dichosos[n]materiales. Voy r茨pido a casa[n]y volver姻 tan pronto como pueda.[n][w][e]

[msg MSG_GOTO_2F_HOLIDAY_YUSU [Yusuke]]
[s][bup 0 5 0 3 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 2],[n]夷tienes algo m茨s que hacer?[n][w][e]

[msg MSG_GOTO_2F_HOLIDAY_YUSU_2 [Yusuke]]
[s][bup 0 5 0 3 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vale. Entonces, puede que[n]yo tambi姻n salga.[n][w][e]

[msg MSG_GOTO_2F_HOLIDAY_YUSU_3 [Yusuke]]
[s][bup 0 5 1 3 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Comprendo. Si no est茨s ocupado,[n]夷podr胤a acompa隠arte?[n][w][e]

[msg MSG_GOTO_AJITO_MORGANA [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Vamos a juntarnos todos[n]en el escondite.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No podemos perder contra Maruki.[n]夷Todo listo?[n][w][e]

[sel SEL_GOTO_AJITO top]
[s]Vamos a quedar.[e]
[s]Necesito m茨s tiempo.[e]

[msg MSG_LAST_DAY_CAUTION [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1189 0 0]夷No quieres ir a despedirte[n]del Jefe y los dem茨s?[n][w][e]

[sel SEL_GO_LAST top]
[s]Vamos con ellos.[e]
[s]No, da igual.[e]

[msg MSG_MONEY_SHORTAGE_FARE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Mm, no tienes suficiente dinero.[n][w][e]
[s][f 4 10 65535 0 0]Hacer planes es importante[n]para ser un buen ladr吋n.[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0]Pero, bueno, te echar姻 una mano[n]con mis ahorros.[n][w][e]

[msg MND_MONEY_SHORTAGE_FARE]
[s]No tengo suficiente dinero[n]para el tren.[n][w][e]
[s]Ay, espera.[n][w][e]
[s]Morgana me dio parte[n]de sus ahorros. Deber胤a[n]tener cuidado con lo que gasto.[n][e]

[msg MND_127101_NG_SHORTCUT]
[s]Debo ir al instituto.[n][w][e]

[msg MND_141301_NG_SHORTCUT_0]
[s]Deber胤a ir a ver a Ryuji.[n][w][e]

[msg MND_141301_NG_SHORTCUT_0_2]
[s]No me queda nada por hacer en[n]el instituto. Deber胤a irme a casa.[n][w][e]

