[msg dummy_mes]
[s]...[n][w][e]

[msg D08_01_e437_005_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]E-eh, esto de aqu胤 es la puerta esa[n]a las profundidades, 夷no?[n][w][e]

[msg D08_01_e437_005_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Se supone. 夷Por? 夷Qu姻 ocurre?[n][w][e]

[msg D08_01_e437_005_mes03 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]No s姻, es que parece igual[n]que todas las dem茨s...[n]Me ha dado un poco de baj吋n...[n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]A ver si vamos a haber currado[n]que no veas para nada.[n][w][e]

[msg D08_01_e437_005_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]La falta de circunstancias imprevistas[n]no es motivo para quejarse.[n]Continuemos.[n][w][e]

[msg SCN_LOCK_07_mes01]
[s]No parece que[n]vaya a abrirse...[n][w][e]

[msg SCN_LOCK_07_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]Supongo que la gente no nos acepta[n]tanto como para que esto se abra.[n][w][e]

[msg SCN_LOCK_07_mes03 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]N-no podemos hacer[n]nada ahora mismo.[n]Hasta aqu胤 podemos llegar.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Damos media vuelta, Joker?[n][w][e]

