[msg MSG_LAST_GREETING_PAPER_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Los folletos los har茨 Iwai.[n]Su letra es m茨s bonita[n]de lo que pensaba.[n][w][e]

[msg MSG_LAST_GREETING_CUPSUL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]No creo que en tu ciudad haya[n]muchos boletines militares, 夷no?[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Aqu胤 no se te ha perdido nada, 夷no?[n]Venga, 斡vayamos a otro lado![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]夷Qu姻 ocurre? Venga, 斡tenemos[n]que despedirnos de los dem茨s![n][w][e]

[msg MSG_GOTO_OUT_NG]
[s][vp 8 2 1 0 65535 0]A雨n no tengo arma.[n]Deber胤a hablar con el dependiente.[n][w][e]

[msg CHK_PAPER_RACK_PC_0404_0]
[s][vp 8 2 1 0 65535 0]Parece un anuncio de una r姻plica.[n][w][e]
[s][vp 8 2 1 0 65535 0]Hay un mont吋n de t姻rminos[n]que desconozco.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Te interesa ese rev吋lver?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lleva equipado un guardamanos[n]en todo el ca隠吋n y el efecto[n]del estabilizador es brutal.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]El muelle es de acero inoxidable.[n]Si es para colecci吋n,[n]puedo ponerle cartuchos falsos.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_2 [Encargado arisco]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Te interesa ese rev吋lver?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lleva equipado un guardamanos[n]en todo el ca隠吋n y el efecto[n]del estabilizador es brutal.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]El muelle es de acero inoxidable.[n]Si es para colecci吋n,[n]puedo ponerle cartuchos falsos.[n][w][e]

[sel CHK_PAPER_RACK_0404_SEL top]
[s]S胤, claro.[e]
[s]Mejor no.[e]

[msg CHK_PAPER_RACK_IWAI_0404_3 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷En serio? Qu姻 t胤o m茨s precavido.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_4 [Encargado arisco]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷En serio? Qu姻 t胤o m茨s precavido.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_5 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Je... No te culpo, la verdad.[n]Si quisieras presumir,[n]yo har胤a lo mismo.[n][w][e]

[msg CHK_PAPER_RACK_IWAI_0404_6 [Encargado arisco]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Je... No te culpo, la verdad.[n]Si quisieras presumir,[n]yo har胤a lo mismo.[n][w][e]

[msg CHK_PAPER_RACK_PC_0418]
[s][vp 8 2 1 0 65535 0]Es una invitaci吋n[n]para un juego de supervivencia.[n][w][e]
[s][vp 8 2 1 0 65535 0]Al parecer, tambi姻n hay un club[n]de juegos de supervivencia[n]en el Instituto Shujin.[n][w][e]

[msg CHK_PAPER_RACK_0425]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s]或斡Te traemos nuevas r姻plicas[n]y mercanc胤a militar[n]todos los meses!位.[n][w][e]

[msg CHK_PAPER_RACK_0503]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或El producto del mes es una[n]pasada: 斡la [clr 4]Bianchi SBAS[clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_0519]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡La estrella del cat茨logo[n]de enero es [clr 4][var 1][clr 27]!位.[n][w][e]
[s][vp 8 2 1 0 65535 0]或Una masa de nubes furiosas:[n]斡la [clr 4]Sand Hawk[clr 27]![n]Muy popular: 斡[clr 4][var 3][clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_0607]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡Por fin ha llegado el especial[n]del mes! 斡Se trata[n]de la [clr 4]Cometa 3[clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_0620]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或Julio nos trae una vieja leyenda:[n]斡[clr 4][var 1][clr 27]!位.[n][w][e]
[s][vp 8 2 1 0 65535 0]或Con motivo del 50 aniversario,[n]斡te traemos la [clr 4]Hellfire[clr 27]![n]斡Y [clr 4][var 3][clr 27] llega por todo lo alto!位.[n][w][e]

[msg CHK_PAPER_RACK_0710]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或El producto de este mes es[n]lo mejor que ha dado este siglo,[n]斡[clr 4][var 1][clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_0725]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡Septiembre se va por todo lo[n]alto! 斡Te presentamos [clr 4][var 1][clr 27]!位.[n][w][e]
[s][vp 8 2 1 0 65535 0]或Un poder sobrecogedor:[n]斡el [clr 4]Aniquilador[clr 27]! Con mucho detalle:[n]斡[clr 4][var 3][clr 27]!位.   [n][w][e]

[msg CHK_PAPER_RACK_0815]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡La joya del mes que viene![n]斡Codiciada por los m茨s grandes![n]斡Se trata de [clr 4][var 1][clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_0831]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或La estrella del cat茨logo de[n]octubre: 斡el pu隠o americano[n]supers吋nico: [clr 4][var 1][clr 27]!位.[n][w][e]
[s][vp 8 2 1 0 65535 0]或Pura destrucci吋n:[n]斡el [clr 4]subfusil del oeste[clr 27]![n]De estabilidad sobresaliente: 斡[clr 4][var 3][clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_0914]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡El producto de octubre est茨[n]tan bien hecho que parece real![n]斡Se trata de [clr 4][var 1][clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_0921]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡La nueva estrella del cat茨logo[n]de noviembre es [clr 4][var 1][clr 27]!位.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡El [clr 4]Arma calamidad[clr 27] ha vuelto![n]斡Para los novatos, es [clr 4][var 3][clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_1012]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡El producto del mes es exclusivo![n]斡Se trata del [clr 4]Borrador[clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_1026]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或El cat茨logo de diciembre nos trae[n]un arma muy esperada: 斡[clr 4][var 1][clr 27]!位.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡Para los fans![n]斡La [clr 4]pistola R. I.[clr 27]! 斡Protecci吋n[n]con tranquilidad! 斡[clr 4][var 3][clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_1109]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或El producto especial de fin de a隠o[n]es una maravilla: 斡[clr 4][var 1][clr 27]!位.[n][w][e]

[msg CHK_PAPER_RACK_1123]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]

[msg CHK_PAPER_RACK_1207]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]

[msg CHK_PAPER_RACK_1219]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡Enero nos trae lo m茨s nuevo de la[n]mano de un maestro artesano:[n]斡[clr 4][var 1][clr 27]!位.[n][w][e]
[s][vp 8 2 1 0 65535 0]或La 雨ltima de su clase: 斡la [clr 4]SIG 227[clr 27]![n]斡Una [clr 4][var 2][clr 27] para cada hogar!位.[n][w][e]

[msg CHK_PAPER_RACK_0101]
[s][vp 8 2 1 0 65535 0]Parece un anuncio[n]de esta tienda.[n][w][e]
[s][vp 8 2 1 0 65535 0]或斡Aqu胤 est茨 la estrella[n]del cat茨logo de enero![n]斡Siente el nuevo viento: [clr 4][var 1][clr 27]!位.[n][w][e]

[msg MSG_CUPSULE_MACHINE_NOSA]
[s][vp 8 2 1 0 65535 0]Es una m茨quina expendedora[n]de raciones de combate.[n][w][e]
[s][vp 8 2 1 0 65535 0]Pone: 或斡Se calcula que llegar茨[n]dentro de unos d胤as!位.[n][w][e]

[msg MSG_CUPSULE_MACHINE_0401 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Pone: 或斡Hora de la cata![n]Raciones del mundo, vol. 37位.[n][w][e]

[msg MSG_CUPSULE_MACHINE_0607 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pone: 或斡Hora de la cata![n]Raciones del mundo, vol. 38位.[n][w][e]

[msg MSG_CUPSULE_MACHINE_0815 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Pone: 或斡Hora de la cata![n]Raciones del mundo, vol. 39位.[n][w][e]

[msg MSG_CUPSULE_MACHINE_1012 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Pone: 或斡Hora de la cata![n]Raciones del mundo, vol. 40位.[n][w][e]

[msg MSG_CUPSULE_MACHINE_1207 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pone: 或斡Hora de la cata![n]Raciones del mundo, vol. 41位.[n][w][e]

[msg MSG_CUPSULE_MACHINE_0101 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pone: 或斡Hora de la cata![n]Raciones del mundo, vol. 42位.[n][w][e]

[msg MSG_CUPSULE_MACHINE_0109]
[s][vp 8 2 1 0 65535 0]Pone: 或斡Hora de la cata![n]Raciones del mundo, vol. 42位.[n][w][e]

[msg MSG_CUPSULE_MACHINE_0404 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Son 800 yenes por intento.[n]夷Quieres probar de todos modos?[n][w][e]

[msg MSG_CUPSULE_MACHINE_0404_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Son 800 yenes por intento.[n]夷Quieres probar de todos modos?[n][w][e]

[msg MSG_CUPSULE_MACHINE_0109_2]
[s][vp 8 2 1 0 65535 0]Son 800 yenes por intento.[n]夷Pruebo a ver?[n][w][e]

[sel MIRIMESI_SEL top]
[s]Habr茨 que probar.[e]
[s]Paso.[e]

[msg SEL_MIRIMESI_A_02]
[s][vp 8 2 1 0 65535 0]La c茨psula est茨 un poco pegajosa.[n][w][e]

[msg SEL_MIRIMESI_A_03]
[s][vp 8 2 1 0 65535 0]Igual es cosa m胤a,[n]pero por un momento[n]me ha parecido que ol胤a fatal...[n][w][e]

[msg SEL_MIRIMESI_A_04]
[s][vp 8 2 1 0 65535 0]A simple vista parece normal, pero...[n][w][e]

[msg SEL_MIRIMESI_BIG_HAZURE [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13074 65535 0]Vaya, qu姻 asco.[n][w][e]

[msg SEL_MIRIMESI_HAZURE [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13043 65535 0]No est茨 mal...[n][w][e]

[msg SEL_MIRIMESI_ATARI [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 1 13045 65535 0]Jo, menuda potra.[n][w][e]

[msg SEL_MIRIMESI_BIG_HAZURE_ [Encargado arisco]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13074 65535 0]Vaya, qu姻 asco.[n][w][e]

[msg SEL_MIRIMESI_HAZURE_name [Encargado arisco]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13043 65535 0]No est茨 mal...[n][w][e]

[msg SEL_MIRIMESI_ATARI_namel [Encargado arisco]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 1 13045 65535 0]Jo, menuda potra.[n][w][e]

[msg MSG_CUPSULE_NO_MONEY [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1025 65535 0]Vaya, no tienes suficiente dinero.[n][w][e]

[msg MSG_CUPSULE_NO_MONEY_HER]
[s][vp 8 2 1 0 65535 0]No tengo suficiente dinero.[n][w][e]

[msg MND_NOOPEN_SHOP]
[s]A雨n no he comprado nada.[n][w][e]

[msg MSG_180105_GOTO_NG_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]A雨n no has vendido la medalla[n]de oro, 夷no? 斡No nos vamos hasta[n]que preguntes si te la compra![n][w][e]

[msg MSG_OPEN_SHOP [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]夷Ya te vas a casa?[n][w][e]
[s][vp 8 2 1 0 65535 0]Bueno, a partir de ahora eliges t雨.[n]Pero 斡p胤llame la que tenga pinta[n]de ser m茨s potente![n][w][e]

[msg MSG_C12_BEGIN_TIME_08 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13001 212 0]Vaya cara m茨s larga llevas.[n]No quiero meterme en l胤os,[n]as胤 que no voy a preguntar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 212 0]Si quieres algo,[n]m胤ralo sin problemas.[n][w][e]

[msg MSG_C12_BEGIN_TIME_08_01 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 212 0]No te fuerces.[n][w][e]

[msg MSG_C12_BEGIN_TIME_0109_ [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 13082 212 0]Perd吋n por el retraso, y feliz a隠o.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 212 0]Viene mucha gente problem茨tica[n]a principios de a隠o, pero, bueno,[n]el sitio tampoco ayuda.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 13090 212 0]Parece que a todo el mundo[n]se le est茨 yendo la olla.[n][w][e]

[msg MSG_C12_BEGIN_TIME_0109__2 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 212 0]Si quieres algo,[n]m胤ralo sin problemas.[n][w][e]

[msg MSG_C12_BEGIN_TIME_0109__3 [Iwai]]
[s][f 4 23 1 212 49 10 40 10][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 212 0]Nos vemos.[n][w][e]

