[msg Dummy]
[s]...[n][w][e]

[msg mini_ev_mes_02_02_03_mes [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Para, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Todas las tragaperras[n]se controlan igual.[n]Es f茨cil trucarlas.[n][w][e]

[msg mini_ev_mes_02_02_03_mes_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entonces, seg雨n t雨, as胤[n]no ganaremos nunca.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A no ser que hagamos algo[n]para remediarlo, claro.[n][w][e]

[msg mini_ev_mes_02_01_mes08 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]S姻 c吋mo te sientes,[n]pero la prioridad es desactivar[n]las trampas, Joker.[n][w][e]

[msg mini_ev_mes_02_01_mes09 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puede que haya una terminal[n]de informaci吋n detr茨s.[n]Busca por ah胤, Joker.[n][w][e]

[msg D157_010_miniEV_01_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que el enemigo[n]no quiere abandonar la zona.[n]夷Estar茨 protegiendo algo?[n][w][e]

[msg D157_010_miniEV_01_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No estoy segura...[n]夷Crees que deber胤amos derrotarlo?[n][w][e]

[msg D157_010_miniEV_01_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, deber胤amos hacerlo[n]lo antes posible.[n][w][e]

[msg D157_010_miniEV_01_mes04 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Vale! 斡Ya nos tomaremos[n]nuestro tiempo para ver lo que hay[n]all胤 cuando le partamos la cara![n][w][e]

[msg SLOT_SAKUSEN_01]
[s]作戦イベント部屋。[n][w][e]
[s]1:敵を全て倒す。2:散開探索[n]3:アケチによる作戦提案。作戦発生。[n][w][e]
[s]作戦イベント後、追加4万枚入手。[n]所持コイン5万枚になり、EVの新フロア解放。[n][w][e]

[msg SLOT_SAIKU_01]
[s][clr 4]細工でスロットが絶対当たる様になるイベント[n](フタバが回線に繋ぐ? )[clr 27][n][w][e]

[msg SLOT_SAIKU_02 [Futaba]]
[s]Esta m茨quina grande controlaba[n]todas las tragaperras.[n][w][e]
[s]He reprogramado unas cuantas cosas,[n]as胤 que deber胤a ser m茨s f茨cil[n]ganar en las tragaperras peque隠as.[n][w][e]
[s]T雨 decides qu姻 hacer ahora, Joker.[n][w][e]

[msg e380_220_mes9 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos a tener que probar con[n]otro panel de control. Desde aqu胤[n]no podemos desactivar las trampas.[n][w][e]

[msg mini_ev_mes_02_02_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Primero, vamos a acabar[n]con el negocio de las trampas.[n]Buscad cosas sospechosas.[n][w][e]

[msg mini_ev_mes_02_02_mes02 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos a jugar a la tragaperras[n]grande primero. No queremos[n]que juegue nadie en nuestro lugar.[n][w][e]

[msg mini_ev_mes_02_02_mes03 [Voz mec茨nica]]
[s]El bote es de 20 monedas por las cerezas,[n]120 monedas por BAR y 200 monedas[n]por un 777.[n][w][e]
[s]La entrada a este juego[n]es de veinte monedas.[n]夷Desea jugar?[n][w][e]

[sel mini_ev_mes_02_02_selA top]
[s]Jugar una ronda[e]
[s]Ignorarlo de momento[e]

[msg mini_ev_mes_02_02_selA_0 [Morgana]]
[s][bup 0 3 0 65535 0]...[n][w][e]

[msg mini_ev_mes_02_02_selA_1 [Morgana]]
[s][bup 0 3 0 65535 0]...[n][w][e]

[msg D07_10_BIG_SLOT_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Primero, vamos a acabar[n]con el negocio de las trampas.[n]Buscad cosas sospechosas.[n][w][e]

[msg D07_10_BIG_SLOT_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡S胤胤胤! 斡Vamos a ganar dinerito![n][w][e]

[msg D07_10_BIG_SLOT_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Haz lo que t雨 sabes, Joker![n][w][e]

[msg D07_10_BIG_SLOT_mes04 [Voz mec茨nica]]
[s]El bote es de 20 000 monedas por[n]las cerezas, 30 000 monedas por BAR[n]y 50 000 monedas por un 777.[n][w][e]
[s]La entrada a este juego son[n]5000 monedas. 夷Deseas jugar?[n][w][e]

[sel D07_10_BIG_SLOT_selA top]
[s]Jugar a la tragaperras grande[e]
[s]Ignorarla de momento[e]

[msg D07_10_BIG_SLOT_selA_0_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hala! 斡Esto es incre胤ble![n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_2 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡H-hemos ganado! 斡Mirad![n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_3 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En el mundo de las apuestas,[n]es un buen momento para decir: 或A[n]ganar, a ganar, pollo para cenar位.[n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_4 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh?[n][w][e]

[msg D07_10_BIG_SLOT_selA_0_m_5 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Da igual.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, ya tenemos las monedas que[n]quer胤amos. Vamos a intercambiarlas[n]por una tarjeta de la planta alta.[n][w][e]

[msg D07_10_BIG_SLOT_selA_1_m [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Por qu姻?![n][w][e]

[msg D07_10_BIG_SLOT_selA_1_m_2 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No tenemos monedas suficientes?[n][w][e]

[msg D07_10_BIG_SLOT_selA_2_m [Morgana]]
[s][bup 0 3 0 65535 0]...[n][w][e]

[msg mini_ev_mes_02_mes05 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si seguimos con esta tragaperras,[n]vamos a levantar sospechas.[n]Dejemos de usarla por ahora.[n][w][e]

[msg D06_SLOT_CONSOLE_NOT_mes [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Joker, sugiero que examinemos[n]antes esa tragaperras gigante.[n][w][e]

[msg seigyoban_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]No vamos a poder detener[n]sus trampas desde aqu胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que hay varios paneles[n]de control de distintos colores[n]en esta zona.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Solo necesitar姻 el [clr 2]rojo[clr 27][n]y el [clr 2]verde[clr 27]. Despu姻s, deber胤a[n]poder controlarlo todo.[n][w][e]

[msg seigyoban_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7192 65535 0]Pero 夷d吋nde van a estar?[n][w][e]

[msg seigyoban_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El primero deber胤a de estar[n][clr 2]cerca de la entrada[clr 27] a la zona.[n]Hasta ah胤 llegaba la se隠al.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y el otro, en alg雨n lugar del[n][clr 2]茨rea de personal[clr 27].[n]O eso creo...[n][w][e]

[msg seigyoban_mes04 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8021 65535 0]Conque la entrada a la zona[n]de tragaperras y alg雨n lugar[n]del 茨rea de personal...[n][w][e]

[msg seigyoban_mes05 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]No vamos a poder detener[n]sus trampas desde aqu胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Encuentra los paneles de control[n]de color [clr 2]rojo[clr 27] y [clr 2]verde[clr 27].[n]Despu姻s, podr姻 arreglarlo todo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, pero el rojo ya est茨.[n]Solo falta por encontrar el [clr 2]verde[clr 27][n]y listo.[n][w][e]

[msg seigyoban_mes06 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]El panel de control verde...[n]夷D吋nde dijiste que estaba?[n][w][e]

[msg seigyoban_mes07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El rojo estaba cerca[n]de la entrada, as胤 que este debe[n]estar en el [clr 2]茨rea de personal[clr 27].[n][w][e]

[msg seigyoban_mes08 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entonces supongo[n]que estar茨 en alg雨n sitio[n]desprovisto de clientes.[n][w][e]

[msg seigyoban_mes09 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]Guay, 斡pues a buscar![n][w][e]

[msg seigyoban_mes10 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]No vamos a poder detener[n]sus trampas desde aqu胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Encuentra los paneles de control[n]de color [clr 2]rojo[clr 27] y [clr 2]verde[clr 27].[n]Despu姻s, podr姻 arreglarlo todo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, pero el verde ya est茨.[n]Solo falta por encontrar el [clr 2]rojo[clr 27][n]y listo.[n][w][e]

[msg seigyoban_mes11 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]夷Sabes d吋nde est茨?[n][w][e]

[msg seigyoban_mes12 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El verde estaba en el pasillo[n]de personal, as胤 que el rojo estar茨[n][clr 2]cerca de la entrada[clr 27].[n][w][e]

[msg seigyoban_mes13 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]La entrada a la zona[n]de tragaperras... All胤 fue donde[n]nos estaba esperando esa sombra.[n][w][e]

