[msg DUMMY_MSG]
[s]...[n][w][e]

[msg MND_GoOut]
[s][vp 1 0 0 0 0 0]夷Ad吋nde voy?[n][w][e]

[sel SEL_DEBUG_PLACE_000_00 top]
[s]A la cl胤nica.[e]
[s]A la tienda de airsoft.[e]
[s]De hecho, olv胤dalo.[e]

[msg MND_RankUp_OK_Chishiki]
[s]Siento que mi [f 4 11 1][clr 26][f 4 12 0][clr 27][n]va a aumentar pronto.[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]No creo que mi [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vaya a mejorar pronto.[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Parece que todav胤a tengo mucho[n]margen de mejora...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Noto que algo me sobreviene...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Creo que estoy cerca de avanzar[n]con mi [f 4 11 0][clr 26][f 4 12 0][clr 27].[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Siento que mi [f 4 11 1][clr 26][f 4 12 0][clr 27][n]va a aumentar pronto.[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]No creo que mi [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vaya a mejorar pronto.[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Parece que todav胤a tengo mucho[n]margen de mejora...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Noto que algo me sobreviene...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Creo que estoy cerca de avanzar[n]con mi [f 4 11 1][clr 26][f 4 12 1][clr 27].[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Siento que mi [f 4 11 2][clr 26][f 4 12 2][clr 27][n]va a aumentar pronto.[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]No creo que mi [f 4 11 2][clr 26][f 4 12 2][clr 27][n]vaya a mejorar pronto.[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Si todo va bien, creo que mis[n][f 4 11 1][clr 26][f 4 12 1][clr 27] podr胤an mejorar.[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Parece que todav胤a tengo mucho[n]margen de mejora...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Noto que algo me sobreviene...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Creo que estoy cerca de avanzar[n]con mi [f 4 11 2][clr 26][f 4 12 2][clr 27].[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Siento que mis [f 4 11 3][clr 26][f 4 12 3][clr 27][n]van a mejorar pronto.[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]No creo que mis [f 4 11 3][clr 26][f 4 12 3][clr 27][n]vayan a mejorar pronto.[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Parece que todav胤a tengo mucho[n]margen de mejora...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Noto que algo me sobreviene...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Creo que estoy cerca de avanzar[n]con mi [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Siento que mi [f 4 11 4][clr 26][f 4 12 4][clr 27][n]va a aumentar pronto.[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]No creo que mi [f 4 11 4][clr 26][f 4 12 4][clr 27][n]vaya a mejorar pronto.[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Si todo va bien, creo que mis[n][f 4 11 4][clr 26][f 4 12 4][clr 27] podr胤an mejorar.[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Parece que todav胤a tengo mucho[n]margen de mejora...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Noto que algo me sobreviene...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Creo que estoy cerca de avanzar[n]con mi [f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

