[msg D08_01_e446_053_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7176 65535 0]夷Eso es el fondo?[n][w][e]

[msg D08_01_e446_053_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tiene que serlo. Vamos.[n][w][e]

[msg D08_01_NPC_TALK_26_mes01 [Hombre de aspecto somnoliento]]
[s]Todo se acaba. Mis deseos...[n]ser茨n concedidos.[n][w][e]

[msg D08_01_NPC_TALK_27_mes01 [Mujer feliz]]
[s]Ya casi... Mis sue隠os est茨n[n]a punto de cumplirse.[n][w][e]

[msg D08_01_NPC_TALK_28_mes01 [Joven hostil]]
[s]夷Sois... los Ladrones Fantasma?[n][w][e]
[s]斡夷Qu姻 hac姻is aqu胤?![n]斡No os atrev茨is a tocarlo![n][w][e]

[msg D08_01_NPC_TALK_29_mes01 [Hombre satisfecho]]
[s]Ahhh... Mientras lo tenga...[n]no necesito nada m茨s.[n][w][e]

[msg D08_01_NPC_TALK_30_mes01 [Joven feliz]]
[s]Por favor... salvadnos.[n]Haced realidad nuestros sue隠os.[n][w][e]

[msg D08_01_NPC_TALK_31_mes01 [Joven indiferente]]
[s]Cumplir茨 todos nuestros deseos.[n]Nos liberar茨 de todo.[n][w][e]

[msg D08_01_NPC_TALK_32_mes01 [Hombre embelesado]]
[s]Por favor... dame lo que quiero.[n]Termina con todo.[n][w][e]

[msg D08_01_NPC_TALK_33_mes01 [Joven agotado]]
[s]Ah... Por fin mi deseo[n]se cumplir茨. Al fin podr姻...[n]ser feliz.[n][w][e]

[msg TEST]
[s]Dummy[n][w][e]

