[msg DUMMY_MSG]
[s]...[n][w][e]

[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_DAIFUGOU_TEST]
[s]Punto de acceso Magnate[n][w][e]

[msg MSG_VIDEO_TEST]
[s]Punto de acceso TV[n][w][e]

[msg MSG_SOUND_TEST]
[s]Punto de acceso Reproductor de m雨sica[n][w][e]

[msg MSG_IMAGE_TEST]
[s]Punto de acceso Galer胤a[n][w][e]

[msg MSG_AWARD_TEST]
[s]Punto de acceso Recompensas[n][w][e]

[msg MSG_PALACE_MAKER_TEST]
[s]Punto de acceso Creador de Palacio[n][w][e]

[msg MSG_001]
[s]夷Irse de la[n]Guardia de los Ladrones?[n][w][e]

[sel SEL_002 top]
[s]S胤[e]
[s]No[e]

[msg Futaba_MSG [Wakaba Isshiki cognitiva]]
[s]Monstruo de la cognici吋n de Futaba.[n]Proteg胤a a Futaba como las esfinges[n]a los dioses.[n][w][e]

[msg Yaruda_MSG [Yaldabaoth]]
[s]Dios del control, nacido del[n]subconsciente humano, y dios[n]malvado creador del mundo f胤sico.[n][w][e]

[msg Maruki_MSG [Adam Kadmon]]
[s]Persona evolucionada de Maruki.[n]Seg雨n la c茨bala, es un humano[n]deificado que sirve como referente.[n][w][e]

[msg Arsene_MSG [Ars因ne]]
[s]Forma del coraz吋n rebelde de Joker.[n]Maestro del disfraz gracias a un riguroso[n]sentido de la imitaci吋n y la observaci吋n.[n][w][e]

[msg Kid_MSG [Capit茨n Kidd]]
[s]Forma del coraz吋n rebelde de Ryuji.[n]Basado en William Kidd, un pirata[n]de cuya vida se sabe poco.[n][w][e]

[msg Goemon_MSG [Goemon]]
[s]Forma del coraz吋n rebelde de Yusuke.[n]Aparece en historias del periodo[n]Edo, pero vivi吋 en otra era.[n][w][e]

[msg Necro_MSG [Necronomic吋n]]
[s]Forma del coraz吋n rebelde de Futaba.[n]Sale en obras de Lovecraft y se[n]le llama 或libro de los muertos位.[n][w][e]

[msg Robin_MSG [Robin Hood]]
[s]Forma del coraz吋n rebelde de Akechi.[n]Suele ser un justiciero,[n]pero tiene otras representaciones.[n][w][e]

[msg Roki_MSG [Loki]]
[s]Forma del coraz吋n rebelde de Akechi.[n]Seg雨n la mitolog胤a, es el dios del [n]enga隠o. A veces aparece como mujer.[n][w][e]

[msg Cend_MSG [Cendrillon]]
[s]Forma del coraz吋n rebelde de Sumire.[n]Esta variante de 或Cenicienta位 viene[n]de la palabra 或cendre位 (或ceniza位).[n][w][e]

[msg Rakugaki_MSG]
[s]Parece un dibujo de un ni隠o.[n][w][e]
[s]Hay cinco estrellas dibujadas.[n][w][e]

