[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Aqu胤 no se te ha perdido nada, 夷no?[n]Venga, 斡vayamos a otro lado![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]夷Qu姻 ocurre? Venga, 斡tenemos[n]que despedirnos de los dem茨s![n][w][e]

[msg MSG_LAST_GREETING_Teache [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]夷No vas a darle las gracias[n]a tus profesores? Es broma.[n]V茨monos a otro sitio.[n][w][e]

[msg MSG_TEACHERS_DOOR_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]A雨n quedan algunos[n]profesores. Parecen relajados.[n][w][e]

[msg MSG_TEACHERS_DOOR]
[s][vp 1 0 0 0 0 0]Los profesores[n]est茨n en una reuni吋n.[n][w][e]

[msg MSG_PRINCIPAL_MORU [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Guau, c吋mo mola esa sala.[n]Huele a autoridad.[n][w][e]

[msg MSG_PRINCIPAL]
[s][vp 1 0 0 0 0 0]No se me ha perdido nada[n]en el despacho del director.[n][w][e]

[msg MSG_CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]Huele un poco a moho.[n][w][e]

[msg MSG_CHK_QUEST10_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Acaba con esto lo antes[n]posible, 夷vale?[n][w][e]

[msg MSG_CHK_QUEST10_01]
[s][vp 1 0 0 0 0 0]Alguien ha escrito en las paredes[n]del ba隠o.[n][w][e]
[s][vp 1 0 0 0 0 0]或斡Menuda cara tiene! Se cree[n]que es una reina y que su novio[n]es su esclavo位.[n][w][e]
[s][vp 1 0 0 0 0 0]或Para quien lea esto, si te dan[n]un pu隠etazo sin venir a cuento,[n]es culpa de Kuroko Hara位.[n][w][e]

[msg MSG_CHK_QUEST10_02]
[s][vp 1 0 0 0 0 0]Tendr姻 cuidado de no llevarme[n]un pu隠etazo.[n][w][e]

[msg MSG_CHK_QUEST10_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Has tardado un buen rato.[n][w][e]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Ah, he visto a una chica muy rara[n]en el pasillo. 斡Su voz me daba[n]escalofr胤os![n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]斡Oye, que ese es el ba隠o[n]de las chicas! Ah胤 no pintas nada.[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]No tengo ning雨n motivo[n]para ir al ba隠o de las chicas.[n][w][e]

[msg MSG_STUDENT_COUNCIL_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]夷El departamento de orientaci吋n?[n]Qu姻 nombre tan prepotente.[n][w][e]

[msg MSG_STUDENT_COUNCIL]
[s][vp 1 0 0 0 0 0]No necesito ayuda.[n][w][e]

[msg MSG_BOARD_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Parece que es una lista de todas[n]las actividades del instituto.[n][w][e]

[msg MSG_BOARD]
[s][vp 1 0 0 0 0 0]Son las fechas de las pr吋ximas[n]actividades del instituto.[n][w][e]

[msg MSG_GRADE2_CLASS_MORU [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Esos chicos de ah胤 no paran[n]de mirarnos. Me dan mala espina.[n][w][e]

[msg MSG_GRADE2_CLASS]
[s][vp 1 0 0 0 0 0]Los estudiantes que hay dentro[n]no dejan de mirar hacia aqu胤.[n][w][e]

[msg MSG_Emergency_Door_m [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Espera, deber胤amos usar la entrada[n]principal si quieres salir.[n][w][e]

[msg MSG_Emergency_Door]
[s][vp 1 0 0 0 0 0]No tengo ning雨n motivo[n]para usar la salida de emergencia.[n][w][e]

[msg MND_BLDG_B_KEEPOUT_000_0]
[s][vp 1 0 0 0 0 0]No tengo nada que hacer[n]m茨s adelante.[n][w][e]

[msg MND_E12010100_NG_BLDGA2F]
[s][vp 1 0 0 0 0 0]Este camino parece llevar[n]a otro edificio.[n][w][e]
[s][vp 1 0 0 0 0 0]La sala de profesores deber胤a[n]estar en [clr 2]este edificio[clr 27].[n][w][e]

[msg MSG_E13710100_NG_BLDGA2F [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]Por ah胤 se llega al edificio[n]de pr茨cticas. Tenemos que ir[n]al aula de la clase D.[n][w][e]

[msg MND_E13710100_NG_BLDGA2F]
[s][vp 1 0 0 0 0 0]Deber胤a dejar que Ryuji se encargue[n]del edificio de pr茨cticas.[n][w][e]

[msg MND_E14710100_NG_BLDGA2F]
[s][vp 1 0 0 0 0 0]Hay tanta gente en el camino que[n]conduce al edificio de pr茨cticas[n]que no puedo pasar.[n][w][e]
[s][vp 1 0 0 0 0 0]Deber胤a intentar ir por otra ruta.[n][w][e]

[msg MSG_E65410201_NG_BldgA2F [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]斡Oye! 斡夷A d吋nde vas?![n]夷No tienes que perseguir[n]a la mariposa?[n][w][e]

[msg MND_E12010100_NG_BldgA2F]
[s][vp 1 0 0 0 0 0]La sala de profesores deber胤a[n]estar en [clr 2]esta planta[clr 27].[n][w][e]

[msg MSG_E14710101_NG_BldgA2F [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 7167 65535 0]Eh, 斡夷ad吋nde te crees que vas?![n]斡Tenemos que darnos prisa[n]y bajar al patio![n][w][e]

[msg MSG_E65410201_NG_BldgA2F_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]斡Oye! 斡夷A d吋nde vas?![n]夷No tienes que perseguir[n]a la mariposa?[n][w][e]

[msg MSG_E65410201_NG_BldgA2F_3 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]斡La mariposa no fue hacia arriba,[n]sino hacia abajo![n][w][e]

[msg MND_E12010100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Parece que est茨n ocupados con algo.[n]No creo que pueda pasar por ah胤.[n][w][e]

[msg MND_E12010100_GOTO_TEACH]
[s][vp 1 0 0 0 0 0]Esto parece la sala de profesores.[n]Ya es hora de entrar.[n][w][e]

[msg MND_E12310100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Los profesores[n]est茨n en una reuni吋n.[n][w][e]

[msg MND_E12720100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Los profesores[n]est茨n en una reuni吋n.[n][w][e]

[msg MSG_E13710100_CHK_TEACHE [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7046 65535 0]No necesitas nada de la sala[n]de profesores, 夷verdad?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ninguno va a soltar prenda[n]sobre Kamoshida, de todos modos.[n][w][e]

[msg MND_E13710100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Los profesores[n]est茨n en una reuni吋n.[n][w][e]

[msg MSG_E13910100_CHK_TEACHE [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, 斡he dicho la entrada principal![n]Si no nos damos prisa, se ir茨.[n][w][e]

[msg MND_E14130100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Los profesores[n]est茨n en una reuni吋n.[n][w][e]

[msg MND_E14710100_CHK_TEACHE]
[s][vp 1 0 0 0 0 0]Parece que los profesores est茨n[n]un poco estresados.[n][w][e]
[s][vp 1 0 0 0 0 0]Ser茨 mejor que me d姻 prisa[n]en llegar al patio...[n][w][e]

[msg MSG_E23810100_CHK_TEACHE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Esta es la sala de profesores.[n]夷No ibas al aula del consejo[n]estudiantil de la [clr 2]tercera planta[clr 27]?[n][w][e]

[msg MSG_E65410201_CHK_TEACHE [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Oye, esa es la sala de profesores.[n]Sigamos a esa mariposa hacia[n]la primera planta.[n][w][e]

[msg MND_COMMON_CHK_TEACHERRO]
[s][vp 1 0 0 0 0 0]Aqu胤 no se me ha perdido nada...[n][w][e]

[msg MND_E12010100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]No se me ha perdido nada[n]en el despacho del director.[n][w][e]

[msg MND_E12310100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]No se me ha perdido nada[n]en el despacho del director.[n][w][e]

[msg MND_E12720100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]No se me ha perdido nada[n]en el despacho del director.[n][w][e]

[msg MSG_E13710100_CHK_Koucho [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7179 65535 0]Ni siquiera el director puede tocar[n]a Kamoshida, 夷sabes?[n][w][e]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7175 65535 0]Joder... Hay algo muy turbio[n]en este instituto.[n][w][e]

[msg MND_E13710100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]No se me ha perdido nada[n]en el despacho del director.[n][w][e]

[msg MSG_E13910100_CHK_Koucho [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, 斡he dicho la entrada principal![n]Si no nos damos prisa, se ir茨.[n][w][e]

[msg MND_E14130100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]No se me ha perdido nada[n]en el despacho del director.[n][w][e]

[msg MND_E14710100_CHK_Koucho]
[s][vp 1 0 0 0 0 0]No tengo que ver al director.[n][w][e]
[s][vp 1 0 0 0 0 0]Ser茨 mejor que me d姻 prisa[n]en llegar al patio...[n][w][e]

[msg MSG_E23810100_CHK_Koucho [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]夷Quieres algo del despacho[n]del director? 夷El aula del consejo[n]no est茨 en la [clr 2]tercera planta[clr 27]?[n][w][e]

[msg MSG_E65410201_CHK_Koucho [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]夷Acaso necesitas algo del despacho[n]del director? Sigamos a esa[n]mariposa hacia la primera planta.[n][w][e]

[msg MND_COMMON_CHK_KouchoRoo]
[s][vp 1 0 0 0 0 0]Aqu胤 no se me ha perdido nada...[n][w][e]

[msg MND_E12010100_CHK_Myclas]
[s][vp 1 0 0 0 0 0]Parece que todas las aulas[n]de los alumnos de segundo[n]est茨n en la segunda planta.[n][w][e]
[s][vp 1 0 0 0 0 0]De momento, ser茨 mejor que vaya[n]a la [clr 2]sala de profesores[clr 27].[n][w][e]

[msg MND_E14710100_CHK_Myclas]
[s][vp 1 0 0 0 0 0]No tengo tiempo de volver[n]a la clase.[n][w][e]
[s][vp 1 0 0 0 0 0]Ser茨 mejor que me d姻 prisa[n]en llegar al patio...[n][w][e]

[msg MSG_E65410201_CHK_Myclas [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]斡Oye! 斡夷A d吋nde vas?![n]夷No tienes que perseguir[n]a la mariposa?[n][w][e]

[msg MND_COMMON_CHK_Myclass_0]
[s][vp 1 0 0 0 0 0]Ahora mismo no tengo nada[n]que hacer en mi clase.[n][w][e]

[msg MND_E12010100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Huele un poco a moho.[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Huele un poco a moho.[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Huele un poco a moho.[n][w][e]

[msg MSG_E13710100_CHK_TOILET [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7200 65535 0]Hace rato que me estoy[n]aguantando las ganas.[n]斡Ser茨 mejor que aprovechemos![n][w][e]

[msg MSG_E13710100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Uf...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_3 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 7045 65535 0]Vale, 斡v茨monos![n]Empezaremos por tu clase.[n][w][e]

[msg MSG_E13710100_CHK_TOILET_4 [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]夷Otra vez?[n]Pero si acabamos de ir.[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]No necesito ir al ba隠o.[n][w][e]

[msg MSG_E13910100_CHK_TOILET [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, 斡夷qu姻 haces?![n]斡Tenemos que darnos prisa[n]y alcanzar a Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Vayamos al patio por ahora.[n][w][e]

[msg MND_E14710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Ser茨 mejor que me d姻 prisa[n]en llegar al patio...[n][w][e]

[msg MSG_E23810100_CHK_TOILET [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1018 0 0]D姻jalo para luego. Ahora ve al aula[n]del consejo estudiantil que hay[n]en la [clr 2]tercera planta[clr 27].[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]No necesito ir al ba隠o.[n][w][e]

[msg MND_E12010100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]No tengo ning雨n motivo[n]para ir al ba隠o de las chicas.[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]No tengo ning雨n motivo[n]para ir al ba隠o de las chicas.[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]No tengo ning雨n motivo[n]para ir al ba隠o de las chicas.[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Joder, t胤o. 斡No podemos entrar ah胤![n]斡Date prisa y vamos a tu clase![n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]No tengo ning雨n motivo[n]para ir al ba隠o de las chicas.[n][w][e]

[msg MSG_E13910100_CHK_TOILET_2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, 斡夷qu姻 haces?![n]斡Tenemos que darnos prisa[n]y alcanzar a Mishima![n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]No tengo ning雨n motivo[n]para ir al ba隠o de las chicas.[n][w][e]

[msg MND_E14710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Ser茨 mejor que me d姻 prisa[n]en llegar al patio...[n][w][e]

[msg MSG_E23810100_CHK_TOILET_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1057 0 0]No necesitas nada de por aqu胤, 夷no?[n]夷No ibas al aula del consejo[n]estudiantil de la [clr 2]tercera planta[clr 27]?[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]No tengo ning雨n motivo[n]para ir al ba隠o de las chicas.[n][w][e]

[msg MND_E12010100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]No necesito ayuda.[n][w][e]

[msg MND_E12310100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]Esto parece el departamento[n]de orientaci吋n.[n][w][e]
[s][vp 1 0 0 0 0 0]Hay un estudiante hablando[n]con un profesor.[n][w][e]

[msg MND_E12720100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]No necesito ayuda.[n][w][e]

[msg MSG_E13710100_CHK_SIDOSI [Ryuji]]
[s][bup 0 2 205 65535 0][f 4 10 65535 0 0][vp 8 2 1 7182 65535 0]夷Eh? 夷Te ha llamado alguien?[n][w][e]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bah, olv胤dalo. 斡Vamos a ver[n]lo que nos cuenta[n]el equipo de voleibol![n][w][e]

[msg MND_E13710100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]No parece que haya nadie dentro.[n][w][e]

[msg MSG_E13910100_CHK_SIDOSI [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, 斡he dicho la entrada principal![n]Si no nos damos prisa, se ir茨.[n][w][e]

[msg MND_E14130100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]Hay varias chicas a las que est茨n[n]obligando a escribir algo.[n][w][e]

[msg MND_E14710100_CHK_SIDOSI]
[s][vp 1 0 0 0 0 0]Ser茨 mejor que me d姻 prisa[n]en llegar al patio...[n][w][e]

[msg MSG_E23810100_CHK_SIDOSI [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1173 0 0]Este es el departamento[n]de orientaci吋n. El aula del consejo[n]est茨 en la [clr 2]tercera planta[clr 27], 夷no?[n][w][e]

[msg MND_COMMON_CHK_SIDOSITU_]
[s][vp 1 0 0 0 0 0]Aqu胤 no se me ha perdido nada...[n][w][e]

[msg MND_E12010100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]El programa de actividades[n]del instituto est茨 publicado[n]en el tabl吋n de anuncios.[n][w][e]
[s][vp 1 0 0 0 0 0]Parece que pasado ma隠ana hay[n]un torneo de voleibol.[n][w][e]

[msg MND_E12310100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]El programa de actividades[n]del instituto est茨 publicado[n]en el tabl吋n de anuncios.[n][w][e]
[s][vp 1 0 0 0 0 0]Parece que pasado ma隠ana hay[n]un torneo de voleibol.[n][w][e]

[msg MND_E12720100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]El programa de actividades[n]del instituto est茨 publicado[n]en el tabl吋n de anuncios.[n][w][e]
[s][vp 1 0 0 0 0 0]Oh, ma隠ana hay un partido[n]de voleibol...[n][w][e]

[msg MSG_E13710100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7183 65535 0]夷Qu姻 haces? 斡D姻monos prisa[n]y vayamos a tu clase![n][w][e]

[msg MND_E13710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]El programa de actividades[n]del instituto est茨 publicado[n]en el tabl吋n de anuncios.[n][w][e]

[msg MSG_E13910100_CHK_BOARD_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, 斡夷qu姻 haces?![n]斡Tenemos que darnos prisa[n]y alcanzar a Mishima![n][w][e]

[msg MND_E14130100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]El programa de actividades[n]del instituto est茨 publicado[n]en el tabl吋n de anuncios.[n][w][e]

[msg MND_E14710100_CHK_BOARD_]
[s][vp 1 0 0 0 0 0]Ser茨 mejor que me d姻 prisa[n]en llegar al patio...[n][w][e]

[msg MSG_E23810100_CHK_BOARD_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]夷Pasa algo? Vas al aula[n]del consejo estudiantil que hay[n]en la [clr 2]tercera planta[clr 27], 夷no?[n][w][e]

[msg MND_COMMON_CHK_BOARD_000]
[s][vp 1 0 0 0 0 0]El programa de actividades[n]del instituto est茨 publicado[n]en el tabl吋n de anuncios.[n][w][e]

[msg MND_E12010100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Parece que todas las aulas[n]de los alumnos de segundo[n]est茨n en la segunda planta.[n][w][e]
[s][vp 1 0 0 0 0 0]De momento, ser茨 mejor que vaya[n]a la [clr 2]sala de profesores[clr 27].[n][w][e]

[msg MND_E12310100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Los estudiantes que hay dentro[n]no dejan de mirar hacia aqu胤.[n][w][e]

[msg MND_E12720100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Los estudiantes que hay dentro[n]no dejan de mirar hacia aqu胤.[n][w][e]

[msg MSG_E13710100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]No veo a nadie del equipo[n]de voleibol.[n][w][e]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Era la clase D? 斡Echemos[n]un vistazo a tu clase tambi姻n![n][w][e]

[msg MND_E13710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]No veo ning雨n alumno[n]con heridas notorias.[n][w][e]

[msg MSG_E13910100_CHK_CLASS_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, 斡he dicho la entrada principal![n]Si no nos damos prisa, se ir茨.[n][w][e]

[msg MND_E14130100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Los estudiantes que hay dentro[n]no dejan de mirar hacia aqu胤.[n][w][e]

[msg MND_E14710100_CHK_CLASS_]
[s][vp 1 0 0 0 0 0]Ser茨 mejor que me d姻 prisa[n]en llegar al patio...[n][w][e]

[msg MSG_E23810100_CHK_CLASS_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1190 0 0]No necesitas nada de otra clase.[n]Vamos al aula del consejo[n]estudiantil de la [clr 2]tercera planta[clr 27].[n][w][e]

[msg MSG_E65410201_CHK_CLASS_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]No necesitas nada de otra clase.[n]Vamos tras la mariposa.[n][w][e]

[msg MND_COMMON_CHK_CLASS_2_0]
[s][vp 1 0 0 0 0 0]Los estudiantes que hay dentro[n]no dejan de mirar hacia aqu胤.[n][w][e]

