[msg DUMMY_MSG]
[s]...[n][w][e]

[msg MSG_LAST_GREETING_GUNSHO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Estuviste aqu胤 con Makoto una vez,[n]夷verdad? Ella ha cambiado bastante[n]desde entonces.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]En cualquier caso, al tipo ese...[n]Era Takekuma, 夷no?[n]Seguro que le encanta este juego.[n][w][e]

[msg MSG_LAST_GREETING_GUNSHO_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Estuviste aqu胤 con Makoto una vez,[n]夷verdad? Ella ha cambiado bastante[n]desde entonces.[n][w][e]

[msg MSG_LAST_GREETING_GUNSHO_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Al tipo ese... Era Takekuma, 夷no?[n]Seguro que le encanta este juego.[n][w][e]

[msg MSG_LAST_GREETING_GUNSHO_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]No tenemos tiempo para jueguecitos.[n]Vamos a ver a los dem茨s.[n][w][e]

[msg MSG_LAST_GREETING_JUICE_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Parece que hay un zumo[n]extra隠o... Pero nuestra prioridad es[n]despedirnos de todo el mundo.[n][w][e]

[msg MSG_LAST_GREETING_BATTLE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Kunoichi y Machimusume[n]est茨n peleando. Est茨n[n]llenos de sangre...[n][w][e]

[msg MSG_LAST_GREETING_MONEY_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1111 65535 0]Eh, 夷para qu姻 est茨s cambiando[n]dinero? No estar茨s pensando en[n]jugar, 夷verdad?[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Aqu胤 no se te ha perdido nada, 夷no?[n]Venga, 斡vayamos a otro lado![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]夷Qu姻 ocurre? Venga, 斡tenemos[n]que despedirnos de los dem茨s![n][w][e]

[msg MSG_GUN_DEAFULT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Una pistola de videojuegos, 夷eh?[n]Tiene un dise隠o excelente, pero[n]no deja de ser un juguete.[n][w][e]

[msg quest27_hint_talk_00 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]夷C吋mo? 夷Que quieres jugar a esto?[n][w][e]
[s]Yo estoy ahora con Gun About,[n]as胤 que no me molestes.[n][w][e]

[msg quest27_hint_talk_01 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]斡Oye! 斡夷Ya has cambiado o qu姻?![n][w][e]

[msg quest27_hint_talk_02 [Jugador aturdido]]
[s][f 4 23 1 613 3 10 0 10]斡No me coge el billete[n]de 1000 yenes![n][w][e]

[msg quest27_hint_talk_03 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]斡Ah, esta es la m胤a! 斡El tramposo[n]se ha puesto a jugar![n][w][e]
[s]斡Oye, corre, tr茨eme cambio![n][w][e]

[sel SELquest27_hint_talk_04 top]
[s]D姻jame jugar.[e]
[s]夷El tramposo?[e]

[msg quest27_hint_talk_05 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]Lo siento, pero voy a estar[n]jugando a esto un buen rato.[n][w][e]
[s]Espera. 夷Te gusta Gun About pero[n]no sabes nada del tramposo?[n][w][e]

[msg quest27_hint_talk_06 [Jugador aturdido]]
[s][f 4 23 1 613 3 10 0 10]H-hay un tramposo de mierda[n]del que todos se quejan[n]en internet.[n][w][e]
[s]Por muchos ataques que reciba,[n]no sufre da隠o. Nadie lo ha vencido[n]jam茨s.[n][w][e]
[s]Los desarrolladores le cerraron[n]la cuenta, pero 姻l se crea otras[n]y sigue erre que erre.[n][w][e]

[msg quest27_hint_talk_07 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]Encontraron su verdadero[n]nombre en una red social,[n]y la gente est茨 que trina.[n][w][e]
[s]Creo que se llama[n][clr 2]Yoshikuni Nejima[clr 27]. Ese mam吋n tiene[n]40 tacos y ni trabaja ni nada.[n][w][e]
[s]Bueno, voy a aplastar a Nejima y[n]me voy a convertir en un h姻roe.[n][w][e]

[msg quest27_hint_talk_08 [Jugador aturdido]]
[s][f 4 23 1 613 3 10 0 10]Pues no veo que est姻s ganando[n]precisamente...[n][w][e]

[msg quest27_hint_talk_09 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]斡Cierra el pico! 斡Tr茨eme[n]cambio y ya est茨![n][w][e]

[msg MSG_quest27_morgana_10 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Este ser茨 el jugador marrullero[n]del que habl吋 Makoto, el tramposo[n]ese al que nadie traga.[n][w][e]
[s][f 4 10 65535 0 0]Hacer trampas jugando a solas tiene[n]un pase, pero fastidiar as胤[n]a los dem茨s es mucha tela.[n][w][e]
[s][f 4 10 65535 0 0]Tambi姻n sabemos c吋mo se llama.[n]Parece que [clr 2]Yoshikuni Nejima[clr 27][n]va a ser nuestro pr吋ximo objetivo.[n][w][e]

[msg MSG_quest27_Target_Find]
[s]Ahora que tienes un objetivo, aseg雨rate[n]de que todos se unen a la misi吋n.[n]Quedad en el escondite para decidir.[n][w][e]

[msg quest27_hint_talk_11 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]斡Corre a por m茨s monedas![n]斡No quiero que el tramposo ese[n]se vaya de rositas![n][w][e]

[msg quest27_hint_talk_12 [Jugador aturdido]]
[s][f 4 23 1 613 3 10 0 10]P-pero... N-no pilla el dinero.[n][w][e]

[msg quest27_hint_talk_20 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]Oye... yo te conozco, 夷no?[n][w][e]
[s]Entonces somos amigos, 夷verdad?[n]Mira a ver si tienes por ah胤 alguna[n]monedilla que prestarme.[n][w][e]

[msg quest27_hint_talk_21 [Jugador aturdido]]
[s][f 4 23 1 613 3 10 0 10]T胤o, 夷c吋mo se te ocurre ir pidiendo[n]pasta a cualquiera?[n][w][e]
[s]D姻jalo ya. Te has gastado[n]todo tu dinero intentando[n]vencer a Nejima.[n][w][e]

[msg quest27_hint_talk_22 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]Jo, vale. Bueno, 夷qu姻 quieres?[n][w][e]

[sel SELquest27_hint_talk_23 top]
[s]夷Conoces al Rey?[e]
[s]夷Eres el Rey?[e]

[msg quest27_hint_talk_24 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]夷El Rey? Claro que s姻 qui姻n es.[n][w][e]

[msg quest27_hint_talk_25 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]夷Que yo soy el Rey? Anda ya.[n][w][e]

[msg quest27_hint_talk_26 [Jugador aturdido]]
[s][f 4 23 1 613 3 10 0 10]Te refieres al Rey[n]de Akihabara, 夷no?[n][w][e]
[s]Todav胤a est茨 en primaria, pero es[n]un m茨quina jugando a Gun About.[n][w][e]

[msg quest27_hint_talk_27 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]Maldito ni隠o de primaria...[n]Seguro que tambi姻n hace trampas.[n][w][e]

[msg quest27_hint_talk_28 [Jugador aturdido]]
[s][f 4 23 1 613 3 10 0 10]Creo que frecuenta los recreativos[n]Gigolo de Akiba.[n][w][e]
[s]Cuesta creerlo, pero[n]ese t胤o no tiene rival.[n][w][e]
[s]P茨sate de d胤a para verlo en acci吋n.[n]Los ni隠os de primaria no pueden[n]entrar de noche en los recreativos.[n][w][e]

[msg quest27_hint_talk_29 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]As胤 que lo mismo damos con el Rey[n]en los Gigolo de Akihabara.[n]Vayamos a echar un ojo.[n][w][e]

[msg quest27_hint_talk_30 [Jugador aturdido]]
[s][f 4 23 1 613 3 10 0 10]Supongo que el Rey estar茨[n]en los Gigolo de Akihabara.[n][w][e]

[msg quest27_hint_talk_31 [Jugador descontento]]
[s][f 4 23 1 614 3 10 0 10]Un cr胤o de primaria que se hace[n]llamar el Rey... Seguro que[n]hace trampas.[n][w][e]

[msg MND_Juice_NotOpen]
[s]Ahora mismo no tengo sed.[n][w][e]

[msg MSG_Juice_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]夷Est茨s pensando[n]en comprar alguna bebida?[n][w][e]

[msg MSG_Juice_SoldOut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]No quedan existencias. Esperemos[n]a que repongan la semana que viene.[n][w][e]

[msg MSG_Juice_AllBuy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Vaya, no quedan existencias.[n]Esperemos a que repongan[n]la semana que viene.[n][w][e]

[msg MSG_Juice_HeatIsland [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]No quedan existencias.[n]Con este calor, es normal...[n][w][e]

[msg MSG_BATTLE_CABINET_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Un samur茨i y un ninja luchan a[n]muerte. Las salpicaduras de sangre[n]son una locura.[n][w][e]

[msg MSG_BATTLE_CABINET]
[s]Parece una pelea entre un samur茨i y[n]un ninja. Debe de ser una m茨quina[n]arcade de lucha.[n][w][e]

[msg MSG_MONEY_CHANGER_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]斡Hala! 夷Puedes elegir c吋mo quieres[n]el cambio? Est茨 muy bien, porque[n]los precios var胤an seg雨n el juego.[n][w][e]

[msg MSG_MONEY_CHANGER]
[s]Aqu胤 hay una m茨quina de cambio.[n][w][e]

[msg MSG_GUNSHOOT_CABINET_NG_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1019 0 0]No tienes tiempo[n]para jugar ahora, 夷verdad?[n][w][e]

[msg MSG_GAME_NOTE_NG_000_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Mm, no hay ninguna publicaci吋n[n]que me interese especialmente...[n][w][e]

