[msg DUMMY_MSG]
[s]......[n][w][e]

[msg MSG_Door_WhatDo_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7062 65535 0]夷Tienes algo m茨s que hacer?[n]Pues yo tambi姻n me piro.[n][w][e]

[msg MSG_Door_WhatDo_Yusuke [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 4054 65535 0]夷Tienes alg雨n sitio al que ir?[n]Yo me ir姻 pronto tambi姻n.[n][w][e]

[msg MSG_DAY_END_MONA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷No est茨s cansado?[n]V茨monos a dormir ya.[n][w][e]

[msg MSG_DAY_END]
[s]Deber胤a irme a la cama.[n][w][e]

[sel SEL_DAY_END top]
[s]Dormir[e]
[s]No dormir a雨n[e]

[msg MSG_LAST_GREETING_Freeze [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]No es momento para buscar[n]ingredientes. Vamos a despedirnos.[n][w][e]

[msg MSG_LAST_GREETING_Kitche [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Ah, el aroma del caf姻...[n]Lo echar姻 de menos.[n][w][e]

[msg MSG_LAST_GREETING_Phone_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]夷Estar茨 Kawakami en el instituto?[n]夷Quieres ir a verla?[n][w][e]

[msg MSG_LAST_GREETING_Phone__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]夷Estar茨 Kawakami en el instituto?[n]Aunque hoy es domingo.[n][w][e]

[msg MSG_LAST_GREETING_Phone [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Tenemos que ver a todo el mundo.[n]No basta con llamarlos.[n][w][e]

[msg MSG_LAST_GREETING_Counte [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Esta barra era ideal para leer.[n][w][e]

[msg MSG_LAST_GREETING_Counte_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]Basta de libros. Salgamos[n]y veamos a los dem茨s.[n][w][e]

[msg MSG_LAST_GREETING_Table [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Echo de menos los d胤as en los que[n]estudi茨bamos todos juntos.[n][w][e]

[msg MSG_LAST_GREETING_Tv01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]夷Quieres ir a ver los cerezos[n]en flor? Nos pillan de camino.[n][w][e]

[msg MSG_LAST_GREETING_Curry [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Supongo que no comeremos[n]el curry del Jefe en un tiempo.[n]Venga, volvamos.[n][w][e]

[msg MSG_LAST_GREETING_SHELF_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Has convivido con este aroma[n]durante un a隠o. 夷Recordar茨s todo[n]lo que te ha ense隠ado el Jefe?[n][w][e]

[msg MSG_LAST_GREETING_COFFEE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Que no se te olvide lo que[n]te ense隠吋 el Jefe sobre[n]los granos de caf姻.[n][w][e]

[msg MSG_LAST_GREETING_SHELF [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]Deja de mirar los granos de caf姻[n]y vamos a ver a todo el mundo.[n][w][e]

[msg MSG_LAST_GREETING_Sayuri [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]El 或Sayuri位 es un cuadro incre胤ble,[n]da igual cu茨ntas veces lo mire.[n]Desp胤dete de Yusuke, 夷vale?[n][w][e]

[msg MSG_LAST_GREETING_Sayuri_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]El 或Sayuri位 es un cuadro incre胤ble,[n]da igual cu茨ntas veces lo mire.[n]No lo ver茨s en un tiempo.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Aqu胤 no se te ha perdido nada, 夷no?[n]Venga, 斡vayamos a otro lado![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]夷Qu姻 ocurre? Venga, 斡tenemos[n]que despedirnos de los dem茨s![n][w][e]

[msg MSG_LAST_GREETING_TV [Presentador de telediario]]
[s]Con este sol y las primeras se隠ales[n]de la flor del cerezo, ma隠ana[n]ser茨 un d胤a ideal para salir.[n][w][e]

[msg MSG_LAST_GREETING_DOOR_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]No te has despedido de esos dos.[n]夷Seguro que as胤 es como[n]quieres que acabe todo?[n][w][e]

[msg MSG_LAST_GREETING_DOOR_0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]A雨n no te has despedido de Futaba.[n]夷Seguro que as胤 es como[n]quieres que acabe todo?[n][w][e]

[msg MSG_LAST_GREETING_DOOR_0_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]A雨n no te has despedido del Jefe.[n]夷Seguro que as胤 es como[n]quieres que acabe todo?[n][w][e]

[sel SEL_LAST_GREETING_DOOR_0 top]
[s]Salir[e]
[s]Replante茨rselo[e]

[msg MSG_TABLE_CENTER_LOCK_MO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]夷Eh? 夷Hay alg雨n problema[n]con esa mesa?[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quiz茨s ser胤a 雨til echar algo encima[n]y tomar medidas.[n][w][e]

[msg MSG_TABLE_CENTER_LOCK]
[s]Creo que ser胤a 雨til echar algo[n]encima y tomar medidas.[n][w][e]

[msg MSG_StudyTutorial_Sojiro [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5147 65535 0]Puedes usar eso[n]cuando quieras estudiar.[n][w][e]

[msg MSG_StudyTutorial [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Tiene un buen tama隠o y hay[n]un mont吋n de sitio para estudiar.[n][w][e]
[s]No subestimes el poder de la[n]inteligencia. Nadie quiere que[n]lo lidere un idiota.[n][w][e]

[msg MND_StudyTutorial]
[s]Esta mesa tiene el tama隠o[n]perfecto para estudiar.[n][w][e]

[msg MSG_Study_NotNight [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷No sigue abierto el Leblanc?[n]Deber胤as estudiar aqu胤 de noche.[n][w][e]

[msg MND_Study_NotNight]
[s]El Leblanc sigue abierto.[n]Es mejor que estudie aqu胤 de noche.[n][w][e]

[msg MSG_Study_NotNight_nonTu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Tiene sitio de sobra[n]si quieres estudiar.[n]Pero el Leblanc sigue abierto...[n][w][e]

[msg MND_Study_NotNight_nonTu]
[s]Esta mesa parece bastante 雨til[n]para estudiar. Pero el Leblanc[n]sigue abierto...[n][w][e]

[msg MSG_Study_StandBy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Deja los estudios para m茨s tarde.[n]Ma隠ana es el asalto, 夷lo sabes?[n][w][e]

[msg MSG_Study_StandBy_nonTut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Este parece un buen sitio[n]para estudiar, pero deber胤as[n]centrarte en los preparativos.[n][w][e]

[msg MSG_Study_PalaceAfter [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Deber胤as estudiar en otro momento.[n]Si est茨s cansado, no te servir茨[n]de nada.[n][w][e]

[msg MND_Study_PalaceAfter]
[s]Estoy bastante cansado.[n]Ya estudiar姻 otro d胤a.[n][w][e]

[msg MSG_Study_PalaceAfter_no [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Este parece un buen sitio[n]para estudiar, pero...[n]夷no deber胤as descansar por hoy?[n][w][e]

[msg MND_Study_PalaceAfter_no]
[s]Esta mesa parece bastante 雨til[n]para estudiar. Pero hoy[n]estoy muy cansado.[n][w][e]

[msg MSG_Study_SleepDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Descansa lo que queda de d胤a,[n]as胤 estaremos listos para ma隠ana.[n]Ya leer茨s en otro momento.[n][w][e]

[msg MND_Study_SleepDay]
[s]Ma隠ana va a ser un d胤a duro.[n]Estudiar姻 en otro momento.[n][w][e]

[msg MSG_Study_SleepDay_nonTu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Este parece un buen sitio[n]para estudiar, pero deber胤as[n]descansar por ahora.[n][w][e]

[msg MND_Study_SleepDay_nonTu]
[s]Esta mesa parece bastante 雨til[n]para estudiar, pero ser茨 mejor que[n]descanse para ma隠ana.[n][w][e]

[msg MSG_Study_NotOpen_KyakuD [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]El Leblanc sigue abierto, 夷sabes...?[n]Molestar茨s si te quedas ah胤[n]haraganeando sin hacer nada.[n][w][e]

[msg MND_Study_NotOpen_KyakuD]
[s]El Leblanc sigue abierto.[n][w][e]

[msg MSG_StudyNG_Sojiro_Kyaku [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0]Hoy hemos tenido clientes, as胤 que...[n]Bueno, me entiendes, 夷no?[n][w][e]

[msg MSG_StudyNG_KyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Todav胤a quedan clientes.[n]Deber胤as estudiar en otro momento.[n][w][e]

[msg MND_StudyNG_KyakuDay]
[s]Todav胤a quedan clientes.[n]Deber胤a estudiar en otro momento.[n][w][e]

[msg MSG_Study_Open_AkechiDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Oye, Akechi sigue siendo[n]cliente aqu胤. Deber胤as dejar[n]lo de estudiar para luego.[n][w][e]

[msg MSG_TABLE_CENTER_SojiroG [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Me voy a casa. L胤mpialo todo[n]cuando termines, 夷vale?[n][w][e]

[msg MSG_TABLE_CENTER_SojiroG_2 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Muy bien, me voy a casa.[n][w][e]

[msg MSG_Study_Q_Sojiro [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5081 65535 0]No tendr茨s tiempo para estudiar[n]cuando salgas al mundo real,[n]as胤 que hazlo ahora que puedes.[n][w][e]

[msg MSG_Study_Q_R [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]夷Qu姻 vas a hacer hoy, estudiar?[n][w][e]

[msg MSG_Study_Q_Rain [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Hoy hace un tiempo de perros,[n]pero es m茨s f茨cil concentrarse en[n]estudiar cuando no puedes salir.[n][w][e]

[msg MND_Study_Q]
[s]Quiz茨 deber胤a[n]pasar el d胤a estudiando.[n][w][e]

[sel SEL_TABLE_USE top]
[s]Estudiar[e]
[s]Cancelar[e]

[msg MSG_Study_ParamInfo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Oye, hay un sof茨 libre.[n]夷Quieres estudiar y mejorar[n]tu [f 4 11 0][clr 26][f 4 12 0][clr 27]?[n][w][e]

[msg MND_Study_ParamInfo]
[s]Creo que mi [f 4 11 0][clr 26][f 4 12 0][clr 27][n]mejorar茨 si estudio aqu胤.[n][w][e]

[msg MND_Study_ParamEndInfo]
[s]Creo que ya tengo suficiente[n][f 4 11 0][clr 26][f 4 12 0][clr 27].[n][w][e]

[msg MND_Study_ParamUpInfo]
[s]Siento que mi [f 4 11 0][clr 26][f 4 12 0][clr 27][n]va a aumentar pronto.[n][w][e]

[msg MSG_FreezerRuburanOpen [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]El Leblanc sigue abierto...[n]Deber胤as cerrar el frigor胤fico[n]antes de que te metas en un l胤o.[n][w][e]

[msg MND_FreezerRuburanOpen]
[s]El Leblanc sigue abierto.[n]Deber胤a cerrar el frigor胤fico[n]antes de meterme en un l胤o.[n][w][e]

[msg MSG_FreezerKyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]A雨n quedan algunos clientes.[n]Deber胤as cerrar el frigor胤fico[n]antes de que te metas en un l胤o.[n][w][e]

[msg MND_FreezerKyakuDay]
[s]Todav胤a quedan algunos clientes.[n]Deber胤a cerrar el frigor胤fico[n]antes de meterme en un l胤o.[n][w][e]

[msg MSG_Curry_NotOpen_Akechi [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Akechi sigue siendo cliente de este[n]sitio. Mejor cierra el frigor胤fico[n]antes de que el Jefe se enfade.[n][w][e]

[msg MSG_Curry_NotOpen_Goro [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Akechi sigue siendo cliente de este[n]sitio. Mejor cierra el frigor胤fico[n]antes de que el Jefe se enfade.[n][w][e]

[msg MSG_FreezerItem_NotEnd [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]夷Eh? 夷Qu姻 pone en la esquina[n]del frigor胤fico? 或Puedes[n]usar las sobras位.[n][w][e]

[msg MND_FreezerItem_NotEnd]
[s]Hay una nota en la esquina[n]del frigor胤fico. 或Puedes usar[n]las sobras位.[n][w][e]

[msg MSG_FreezerItem_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Mmm, parece que no queda nada.[n][w][e]

[msg MND_FreezerItem_End]
[s]Parece que no queda nada.[n][w][e]

[msg MSG_FreezerFull_CurryON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Aqu胤 hay un pu隠ado de ingredientes.[n]Podr胤as usarlos para hacer curry.[n][w][e]

[msg MND_FreezerFull_CurryON]
[s]Hay diferentes ingredientes[n]dentro. Parece que son[n]para preparar curry.[n][w][e]

[msg MSG_FreezerNone_CurryON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Parece que no quedan ingredientes[n]para hacer curry...[n]Ya lo haremos otro d胤a.[n][w][e]

[msg MND_FreezerNone_CurryON]
[s]Parece que no nos quedan[n]ingredientes para hacer curry.[n][w][e]

[msg MSG_FREEZER_NOTHING_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Aqu胤 dentro hay comida, pero[n]nada que se pueda comer[n]inmediatamente. Es desalentador.[n][w][e]

[msg MSG_FREEZER_NOTHING]
[s]No hay nada listo para comer[n]en el frigor胤fico.[n][w][e]

[msg MSG_TABLE_Freezer_Sojiro [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0]Mmm... 夷Vas a comer algo[n]del frigor胤fico?[n][w][e]
[s][f 4 10 65535 0 0]Bueno, me voy a casa.[n]D姻jalo todo limpio, 夷vale?[n][w][e]

[msg MSG_CurryNG_KawaCoffeeON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Kawakami est茨 usando la cocina[n]ahora mismo. Tendr茨s que[n]hacer curry en otro momento.[n][w][e]

[msg MSG_CurryNG_KawaCoffeeON_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]El Jefe te ha ense隠ado a hacer[n]curry, pero parece que Kawakami[n]est茨 usando la cocina.[n][w][e]

[msg MSG_Curry_TodayGoPalace [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷No est茨s cansado?[n]Dej姻moslo por hoy[n]y vayamos a dormir.[n][w][e]

[msg MND_Curry_TodayGoPalace [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Estoy bastante cansado.[n]Ser茨 mejor que me vaya a dormir.[n][w][e]

[msg MSG_Curry_OnlySleepDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Deber胤amos descansar para ma隠ana.[n][w][e]

[msg MND_Curry_OnlySleepDay]
[s]Ser茨 mejor que descanse hoy para[n]que estemos preparados ma隠ana.[n][w][e]

[msg MSG_Curry_NoticeDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Ma隠ana llevaremos a cabo el plan.[n]No querr茨s resfriarte, 夷no?[n][w][e]

[msg MND_Curry_NoticeDay]
[s]Ma隠ana llevaremos a cabo el plan.[n][w][e]

[msg MSG_Curry_Tutorial [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Toma ya, el Jefe te ha ense隠ado[n]a preparar curry, 夷no?[n][w][e]

[msg MND_Curry_Tutorial]
[s]Ah, es verdad...[n]Sojiro me ense隠吋 a preparar curry.[n][w][e]

[msg MSG_CurryInfo_Common [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]斡Oye, han sobrado ingredientes[n]para hacer curry![n][w][e]

[msg MND_CurryInfo_Common]
[s]斡Han sobrado ingredientes[n]para hacer curry![n][w][e]

[msg MSG_CURRY_NG_0410]
[s]Hay una olla de curry enorme aqu胤.[n]Me pregunto si se est茨 preparando[n]para servirse ma隠ana...[n][w][e]

[msg MSG_CurryPot_KyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]El Leblanc sigue abierto.[n]Salgamos de la cocina antes[n]de que te metas en un l胤o.[n][w][e]

[msg MSG_CURRY_NOTOPEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Ojal茨 supieras hacer el curry[n]especialidad de la casa. As胤 lo[n]podr胤amos comer cuando quisi姻ramos.[n][w][e]

[msg MSG_CURRY_NOTOPEN]
[s]Esto parece el sitio donde[n]se hace el curry del Leblanc.[n][w][e]

[msg MSG_CURRY_OPEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Si quedan ingredientes[n]en el frigor胤fico, deber胤amos[n]probar a hacer curry.[n][w][e]

[msg MND_CURRY_OPEN]
[s]Si quedan ingredientes[n]en el frigor胤fico, deber胤a[n]intentar hacer curry.[n][w][e]

[msg MSG_CURRY_OPEN_Gogo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷No sigue abierto el Leblanc?[n]Si te quedas plantado[n]en la cocina, vas a estorbar.[n][w][e]

[msg MND_CURRY_OPEN_Gogo]
[s]El Leblanc sigue abierto.[n]No deber胤a estar[n]en medio de la cocina.[n][w][e]

[msg MSG_CURRY_OPEN_Dng [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷No est茨s cansado?[n]Dej姻moslo por hoy[n]y vayamos a dormir.[n][w][e]

[msg MND_CURRY_OPEN_Dng]
[s]Estoy bastante cansado.[n]Ser茨 mejor que me vaya a dormir.[n][w][e]

[msg MSG_CurryPot_NotMakeDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Parece que el Jefe ha preparado[n]curry, pero dudo que hayan[n]sobrado ingredientes...[n][w][e]

[msg MND_CurryPot_NotMakeDay]
[s]Parece que Sojiro ha hecho curry.[n]No creo que hayan sobrado[n]ingredientes para poder cocinar.[n][w][e]

[msg MSG_Curry_Sojiro [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]No dejes abierto el frigor胤fico.[n][w][e]

[msg MSG_Curry_SojiroGoHome [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5020 65535 0]夷Est茨s preparando la cena?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Estoy a punto de irme a casa.[n]Ten cuidado con el fuego.[n][w][e]

[msg MSG_Curry_SojiroGoHome_c [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]夷Est茨s preparando la cena?[n]Estoy a punto de irme a casa.[n]Cuidado con el fuego.[n][w][e]

[msg MND_NotOpen_Croosword]
[s]Esta mesa tiene pinta[n]de haber sido pulida con mimo.[n][w][e]

[msg MSG_DUMMY_01]
[s]Deber胤a pensar en qu姻 hacer ahora.[n][w][e]
[s]...[n][w][e]

[msg MSG_DUMMY_0410_mes01]
[s]夷Deber胤a coger el tel姻fono?[n][w][e]

[msg MSG_DUMMY_0410_mes02]
[s]Me ha pedido que gire el cartel.[n]夷Se referir茨 al de la puerta?[n][w][e]

[msg MSG_DUMMY_0410_mes03]
[s]Me muero de hambre...[n][w][e]

[msg MSG_DUMMY_0410_mes04]
[s]Ma隠ana tengo clase.[n]Deber胤a irme a la cama.[n][w][e]

[msg MSG_DUMMY_0411_mes01]
[s]Espero no liarme con[n]los transbordos de tren.[n][w][e]

[msg MSG_CW_NotSetDay_NotOpen [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Mmm, qu姻 mesa tan usada...[n]Tiene algo a隠ejo muy pintoresco.[n][w][e]

[msg MND_CW_NotSetDay_NotOpen]
[s]Hay unos ara隠azos en la mesa.[n][w][e]

[msg MSG_CW_NotOpen_KyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]El Leblanc sigue abierto.[n][w][e]

[msg MND_CW_NotOpen_KyakuDay]
[s]El Leblanc sigue abierto.[n][w][e]

[msg MSG_CW_NotOpen_KyakuDay_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]El Leblanc sigue abierto.[n][w][e]

[msg MND_CW_NotOpen_KyakuDay_]
[s]El Leblanc sigue abierto.[n][w][e]

[msg MSG_CW_NotSetDay_Open [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Hoy no veo la revista[n]con los crucigramas.[n][w][e]

[msg MND_CW_NotSetDay_Open]
[s]Hoy no hay ninguna revista[n]de crucigramas.[n][w][e]

[msg MSG_NotOpen_Crossword_tu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Crucigramas, 夷eh?[n]Supongo que son un buen modo[n]de poner a prueba tu mente.[n][w][e]

[msg MND_NotOpen_Crossword_tu]
[s]Es una revista de crucigramas.[n][w][e]

[msg MSG_CROSSWORD_PLAY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]夷Vas a hacer crucigramas?[n]Tienes m茨s cosas que hacer,[n]as胤 que no te entretengas mucho.[n][w][e]

[msg MND_CROSSWORD_PLAY]
[s]Puede que intente resolver[n]uno de estos crucigramas.[n][w][e]

[sel SEL_MGK_CROSSWORD_PLAY top]
[s]Hacer alguno[e]
[s]Ahora no[e]

[sel SEL_MGK_CROSSWORD_PLAY2 top]
[s]Hacer alguno[e]
[s]Echarle un vistazo al crucigrama[e]
[s]Ahora no[e]

[sel SEL_MGK_CROSSWORD_PLAY3 top]
[s]Echarle un vistazo al crucigrama[e]
[s]Ahora no[e]

[msg MSG_CROSSWORD_SojiroGoHo [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5020 65535 0]Ah, 夷estabas mirando eso? Ya veo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Pronto me voy a casa.[n]No te pases demasiado tiempo[n]con esos crucigramas, 夷vale?[n][w][e]

[msg MSG_CROSSWORD_SojiroGoHo_2 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Muy bien, me voy a casa.[n][w][e]

[msg MND_CrossWord_Stage_Coff]
[s]Esta p茨gina es la secci吋n[n]或Caf姻 y cafeter胤as位.[n][w][e]

[msg MND_CrossWord_Stage_Scho]
[s]Esta p茨gina es la secci吋n[n]或Vida en el campus位.[n][w][e]

[msg MND_CrossWord_Stage_Phan]
[s]Esta p茨gina es la secci吋n[n]或Ladrones Fantasma位.[n][w][e]

[msg MND_CrossWord_Stage_Myth]
[s]Esta p茨gina es la secci吋n[n]或Religi吋n y mitolog胤a位.[n][w][e]

[msg MSG_CrossWord_ParamUp [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]Vaya... Ni siquiera yo[n]pod胤a resolver eso.[n][w][e]

[msg MSG_CrossWord_ParamUp02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0]Puede que te hayas vuelto[n]m茨s listo despu姻s de resolver[n]estos crucigramas.[n][w][e]

[msg MND_CrossWord_ParamUp]
[s]Vale, vale. Ah... ya lo entiendo.[n][w][e]

[msg MND_CrossWord_ParamUp02]
[s]Creo que he conseguido[n]un poco m茨s de [f 4 11 0][clr 26][f 4 12 0][clr 27][n]despu姻s de resolver un crucigrama.[n][w][e]

[msg MSG_CrossWord_AllClear [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]No quedan m茨s crucigramas.[n]Creo que los has hecho todos.[n][w][e]

[msg MND_CrossWord_AllClear]
[s]No quedan m茨s crucigramas.[n]Creo que los he hecho todos.[n][w][e]

[msg MSG_CrossWord_End [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]*bostezo* 夷Tanto rato llevamos[n]resolviendo crucigramas? Es tarde.[n]Deber胤amos irnos a dormir.[n][w][e]

[msg MND_CrossWord_End]
[s]Se est茨 haciendo tarde.[n]Ser茨 mejor que lo deje por hoy[n]y me vaya a dormir.[n][w][e]

[msg MSG_CrossWord_Bad [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]夷Todav胤a no los has resuelto todos?[n]Bueno, pues tendr茨s que volver[n]a intentarlo m茨s adelante.[n][w][e]

[msg MND_CrossWord_Bad]
[s]No he podido resolver[n]todas las preguntas.[n][w][e]

[msg MSG_MGK_CROSSWORD_ALLCLE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Parece que has completado[n]todas las preguntas de esta p茨gina.[n][w][e]

[msg MND_MGK_CROSSWORD_ALLCLE]
[s]No quedan m茨s preguntas[n]en esta p茨gina.[n][w][e]

[msg MSG_CrossWord_kuria [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Venga, s姻 que est茨s aburrido,[n]pero 夷no crees que[n]ya has jugado bastante?[n][w][e]

[msg MND_CrossWord_kuria]
[s]Ya casi he terminado el crucigrama.[n]No puedo jugar m茨s por hoy.[n][w][e]

[msg MSG_CrossWord_sippai [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]No puedes rendirte con el problema[n]de antes, 夷eh? 斡Esa es la actitud![n][w][e]

[msg MND_CrossWord_sippai]
[s]Volvamos a intentar[n]resolver el crucigrama.[n][w][e]

[sel CrossWord_SEL top]
[s]SEMESTRES[e]
[s]FLORECER[e]
[s]GOLDEN[e]
[s]ESTR畏S[e]
[s]GALER緯A[e]
[s]POLINOSIS[e]
[s]JAPON畏S[e]
[s]MAESTRO[e]
[s]RUEDA[e]
[s]ARMARIO[e]
[s]DIVISA[e]
[s]FRENTE[e]
[s]NARC遺TICOS[e]
[s]VACACIONES[e]
[s]FINALES[e]
[s]PIROTECNIA[e]
[s]ISLA[e]
[s]CORAJE[e]
[s]QUEMADURA[e]
[s]SOFOCO[e]
[s]HACKEAR[e]
[s]TIF遺N[e]
[s]FESTIVAL[e]
[s]RANKING[e]
[s]NEGRO[e]
[s]HALLOWEEN[e]
[s]CASETAS[e]
[s]RECOMPENSA[e]
[s]VAPULEAR[e]
[s]CARISMA[e]
[s]INFLUENZA[e]
[s]ILUMINAR[e]
[s]APROBACI遺N[e]
[s]NAVIDAD[e]
[s]PROP遺SITO[e]
[s]DIONISO[e]
[s]L威QUESIS[e]
[s]OROCHI[e]

[msg CrossWord_MENU]
[s]Crucigrama[n][e]

[msg MSG_CrossWord_Toribia_OS [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Nunca sabes cu茨ndo pueden[n]serte 雨tiles estos conocimientos.[n][w][e]

[msg MSG_CrossWord_NG_Kyaku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]夷Todav胤a hay clientes[n]a estas horas?[n][w][e]

[msg MND_CrossWord_NG_Kyaku]
[s]Todav胤a hay clientes aqu胤.[n][w][e]

[msg MSG_CrossWord_NG_Akechi_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]夷Akechi sigue por aqu胤? Bueno,[n]ya no es tan popular, as胤 que[n]no puedo culparle.[n][w][e]

[msg MSG_CrossWord_NG_Akechi__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Akechi debe tener mucho tiempo[n]libre si se queda aqu胤[n]hasta tan tarde.[n][w][e]

[msg MSG_CrossWord_NG_Akechi__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Akechi sigue aqu胤.[n]No estar茨 tramando algo, 夷no?[n][w][e]

[msg MSG_CrossWord_NG_Akechi__4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Akechi sigue aqu胤. Este sitio[n]le resultar茨 muy relajante.[n][w][e]

[msg MSG_CrossWord_NG_StandBy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]No tienes tiempo para tonter胤as.[n]Te acuerdas de lo que[n]vamos a hacer ma隠ana, 夷no?[n][w][e]

[msg MSG_CW_NG_StandBy_NotSet [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷Qu姻 ocurre? Tenemos que[n]prepararnos para ma隠ana.[n][w][e]

[msg MSG_CrossWord_NG_StandBy_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷Te ha llamado la atenci吋n[n]esa revista? Ser茨 mejor que[n]nos preparemos para ma隠ana.[n][w][e]

[msg MSG_CW_NG_StandBy_nonTut [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷Qu姻 ocurre? Tenemos que[n]prepararnos para ma隠ana.[n][w][e]

[msg MSG_CrossWord_NG_DNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]No te fuerces si est茨s[n]cansado. Siempre puedes[n]hacerlo m茨s adelante.[n][w][e]

[msg MND_CrossWord_NG_DNG]
[s]Estoy reventado despu姻s[n]de lo de hoy. Deber胤a dejar[n]esto para otro momento.[n][w][e]

[msg MSG_CW_NG_DNG_notSet [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]夷Qu姻 ocurre? Deber胤as darte[n]prisa y descansar un poco.[n][w][e]

[msg MND_CW_NG_DNG_notSet]
[s]Por hoy, creo que[n]deber胤a descansar.[n][w][e]

[msg MSG_CrossWord_NG_DNG_non [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Una revista de crucigramas,[n]夷eh? 夷No est茨s cansado?[n]Vamos a dejarlo para otro momento.[n][w][e]

[msg MND_CrossWord_NG_DNG_non]
[s]Anda, una revista con crucigramas.[n]Pero deber胤a descansar por hoy.[n][w][e]

[msg MSG_CW_NG_DNG_nonTuto_no [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Qu姻 mesa tan grande.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Por qu姻 no le preguntas al Jefe[n]si puedes usarla?[n][w][e]

[msg MND_CW_NG_DNG_nonTuto_no]
[s]Por hoy, creo que[n]deber胤a descansar.[n][w][e]

[msg MSG_CrossWord_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]El Leblanc sigue abierto.[n][w][e]

[msg MND_CrossWord_NG]
[s]El Leblanc sigue abierto.[n][w][e]

[msg MSG_CrossWord_Trivia01 [SEMESTRES]]
[s]Muchos institutos dividen el a隠o en dos o tres[n]semestres. En Jap吋n, el nuevo semestre empieza[n]en abril.[n][w][e]
[s]El gobierno japon姻s divide el a隠o de otra forma.[n]De julio a junio es el 或a隠o del trigo位 y de octubre a[n]septiembre, el 或a隠o del az雨car位 o el 或a隠o del pesticida位.[n][w][e]

[msg MSG_CrossWord_Trivia02 [FLORECER]]
[s]El hanami, literalmente 或ver flores位, es una[n]antigua tradici吋n japonesa para observar los cerezos[n]en flor y disfrutar de la llegada de la primavera.[n][w][e]
[s]La 或flor位 que se menciona en la poes胤a japonesa[n]tradicional se refiere a la flor de ciruelo, que fue[n]sustituida por la del cerezo durante el periodo Heian.[n][w][e]

[msg MSG_CrossWord_Trivia03 [GOLDEN]]
[s]Esta semana de vacaciones suele durar desde[n]finales de abril hasta principios de mayo.[n][w][e]
[s]La parte 或de oro位 proviene del t姻rmino de[n]audiencias 或minuto de oro位, que se refiere[n]a la franja horaria m茨s deseada del d胤a.[n][w][e]

[msg MSG_CrossWord_Trivia04 [ESTR畏S]]
[s]En Jap吋n, la 或enfermedad de mayo位 se llama as胤[n]debido a los s胤ntomas que provoca el cambio de[n]estaci吋n tras las vacaciones que ponen fin al mes.[n][w][e]
[s]En Estados Unidos, tienen la 或enfermedad de[n]septiembre位 tras las vacaciones de verano,[n]y en Reino Unido, la 或enfermedad de enero位.[n][w][e]

[msg MSG_CrossWord_Trivia05 [GALER緯A]]
[s]Una sala o pasillo donde se exhiben obras de arte.[n]Tambi姻n es la zona donde los espectadores[n]se re雨nen para todo tipo de eventos.[n][w][e]
[s]Tambi姻n puede referirse a la sociedad (sobre[n]todo en lo que respecta a la opini吋n mayoritaria)[n]o incluso a una red de t雨neles subterr茨neos.[n][w][e]

[msg MSG_CrossWord_Trivia06 [POLINOSIS]]
[s]Es una reacci吋n al姻rgica provocada por el contacto[n]del polen con las membranas de la nariz o los ojos.[n]Provoca estornudos, secreciones nasales y picor.[n][w][e]
[s]Los s胤ntomas aparecieron cuando los granjeros[n]ingleses cosechaban sus tierras, lo que deriv吋[n]en el apodo de 或fiebre del heno位.[n][w][e]

[msg MSG_CrossWord_Trivia07 [JAPON畏S]]
[s]A diferencia de los estilos art胤sticos occidentales,[n]los cuadros de t姻cnica japonesa posteriores[n]a 1900 reciben el nombre de 或Nihonga位.[n][w][e]
[s]Los extranjeros que visitaron Jap吋n durante el[n]periodo Meiji lo llamaron as胤 por su traducci吋n[n]literal de 或Nihon位 (Jap吋n) y 或ga位 (arte).[n][w][e]

[msg MSG_CrossWord_Trivia08 [MAESTRO]]
[s]Usado en frases como 或maestro artesano位, que[n]describen a artistas con habilidades y t姻cnicas[n]de gran influencia en sus medios espec胤ficos.[n][w][e]
[s]Uno de los maestros m茨s prol胤ficos de la pintura,[n]Pablo Picasso, tiene uno de los nombres m茨s largos[n]de la historia del arte: 斡103 letras en total![n][w][e]

[msg MSG_CrossWord_Trivia09 [RUEDA]]
[s]Es una reuni吋n para escuchar y comunicar alg雨n[n]tipo de informaci吋n que se hace p雨blica. Puede[n]planificarse o prepararse en el 雨ltimo momento.[n][w][e]
[s]Cuando se llevan a cabo, se establecen[n]varias entradas y salidas para que la prensa[n]no acribille a los oradores cuando se marchen.[n][w][e]

[msg MSG_CrossWord_Trivia10 [ARMARIO]]
[s]En los institutos de Jap吋n, los estudiantes cambian de[n]armario dos veces al a隠o para una mayor comodidad.[n]Cada uniforme tiene versi吋n de verano y de invierno.[n][w][e]
[s]Se dice que el cambio de armario surgi吋 en[n]China durante el periodo Edo, donde la gente[n]cambiaba de armario cuatro veces al a隠o.[n][w][e]

[msg MSG_CrossWord_Trivia11 [DIVISA]]
[s]El t姻rmino se usa en frases como 或cambio de divisas位,[n]refiri姻ndose a las monedas de distintos pa胤ses.[n]Proviene del lat胤n 或divisus位, que significa 或dividido位.[n][w][e]
[s]Desde la implementaci吋n de la moneda, monarcas[n]y ciudades empezaron a acu隠arlas con sus sellos[n]identificativos para certificar su valor met茨lico.[n][w][e]

[msg MSG_CrossWord_Trivia12 [FRENTE]]
[s]Se le llama 或frente estacionario位 al choque entre aire[n]caliente y fr胤o de igual fuerza. El frente de lluvias[n]en Jap吋n suele ocurrir entre primavera y verano.[n][w][e]
[s]或Tsuyu位, la 姻poca lluviosa en Jap吋n, se escribe con los[n]caracteres chinos de ciruela y lluvia. Esto puede[n]deberse a que la lluvia cae cuando las ciruelas maduran.[n][w][e]

[msg MSG_CrossWord_Trivia13 [NARC遺TICOS]]
[s]Este t姻rmino se aplica a cualquier f茨rmaco que[n]aten雨e los sentidos. Comprende una gran[n]variedad de drogas con efectos psicoactivos.[n][w][e]
[s]La morfina, un narc吋tico com雨n que se usa como[n]analg姻sico en muchos centros m姻dicos, se llama[n]as胤 por Morfeo, el dios griego del sue隠o.[n][w][e]

[msg MSG_CrossWord_Trivia14 [VACACIONES]]
[s]Las vacaciones m茨s populares en el instituto[n]y los negocios tienen lugar en verano.[n]La duraci吋n depende del lugar.[n][w][e]
[s]Jap吋n tambi姻n tiene otro periodo vacacional en oto隠o.[n]Dura de tres a siete d胤as. Es bastante m茨s corto[n]que el verano, pero tiene muy buena acogida.[n][w][e]

[msg MSG_CrossWord_Trivia15 [FINALES]]
[s]Son ex茨menes que se hacen al final[n]del semestre para saber cu茨nto dominan[n]los alumnos cada materia.[n][w][e]
[s]En Jap吋n, los s胤mbolos 或O位 y 或X位 se usan para[n]puntuar los finales. 斡Aunque 或O位 no siempre[n]significa que la respuesta sea correcta![n][w][e]

[msg MSG_CrossWord_Trivia16 [PIROTECNIA]]
[s]La pirotecnia es popular desde hace siglos.[n]Se llenan recipientes con varios compuestos qu胤micos[n]que generan colores y humo y suenan al detonarlos.[n][w][e]
[s]夷Sab胤as que los fuegos artificiales no silban?[n]El silbido que acompa隠a al ascenso es el resultado[n]de una pieza integrada dise隠ada con ese fin.[n][w][e]

[msg MSG_CrossWord_Trivia17 [ISLA]]
[s]Las islas de calor son zonas m茨s calurosas que sus[n]alrededores, provocadas por un nivel de agua bajo[n]y por la absorci吋n de calor de ciertas superficies.[n][w][e]
[s]Los d胤as de m茨s de 25, 30 y 35 grados pertenecen[n]al 或natsubi位 (verano), 或manatsubi位 (mitad de verano),[n]y 或moushobi位 (calor extremo), respectivamente.[n][w][e]

[msg MSG_CrossWord_Trivia18 [CORAJE]]
[s]Una prueba de valent胤a com雨n es entrar en lugares[n]escalofriantes o intimidantes. En Jap吋n, estos sitios[n]suelen ser cementerios y templos.[n][w][e]
[s]El cl茨sico juego de mesa 或100 cuentos[n]sobrenaturales位 se hizo popular entre[n]los samur茨is para aguzar su valent胤a.[n][w][e]

[msg MSG_CrossWord_Trivia19 [QUEMADURA]]
[s]Es una inflamaci吋n de la piel causada por los[n]rayos ultravioleta del sol, que provocan un[n]cambio temporal de la pigmentaci吋n de la piel.[n][w][e]
[s]Los rayos ultravioleta se reflejan en superficies como[n]el agua, la arena y la nieve. Esto puede producir[n]quemaduras hasta practicando snowboard o esqu胤.[n][w][e]

[msg MSG_CrossWord_Trivia20 [SOFOCO]]
[s]Suele venir acompa隠ado de enrojecimiento[n]de la piel y sudor. Las noches abrasadoras[n]son consecuencias de la isla de calor.[n][w][e]
[s]Hasta que el concepto de 或golpe de calor位 se dio a[n]conocer p雨blicamente, a los que mor胤an de eso se[n]les clasificaba como 或muertos por causas no naturales位.[n][w][e]

[msg MSG_CrossWord_Trivia21 [HACKEAR]]
[s]Aunque normalmente se atribuye a una conducta[n]criminal, el 或hackeo位 abarca cualquier acceso a[n]tecnolog胤a protegida, sin importar las intenciones.[n][w][e]
[s]Cuando los hackers hacen el bien, a veces se les[n]llama 或sombreros blancos位. A los que tienen malas[n]intenciones, se les llama 或sombreros negros位.[n][w][e]

[msg MSG_CrossWord_Trivia22 [TIF遺N]]
[s]Se refiere a un cicl吋n tropical con fuertes vientos[n]de al menos 118 kil吋metros por hora en la zona[n]del noroeste del Oc姻ano Pac胤fico.[n][w][e]
[s]La escala de intensidad de ciclones tropicales[n]oficial de Jap吋n los engloba en tres categor胤as:[n]tifones, supertifones y tifones violentos.[n][w][e]

[msg MSG_CrossWord_Trivia23 [FESTIVAL]]
[s]El Tsukimi es un festival tradicional para ver la luna[n]en oto隠o. Hay t姻rminos especiales para ver la luna[n]cuando llueve o cuando cambia de fase.[n][w][e]
[s]Al preparar Tsukimi dango, hay que tener en cuenta[n]la fecha. Si vas al Tsukimi el d胤a 15, hay que preparar[n]quince. Si vas el 12, hay que preparar una docena.[n][w][e]

[msg MSG_CrossWord_Trivia24 [RANKING]]
[s]Establecer el orden de una lista, sin importar lo larga[n]que sea, es f茨cil con una clasificaci吋n. Al cuantificar[n]un factor relevante, ordenar es mucho m茨s f茨cil.[n][w][e]
[s]Votar puede ser muy complicado. El 或recuento Borda位[n]es un m姻todo en el que los votantes clasifican sus[n]elecciones, las cuales se escrutan.[n][w][e]

[msg MSG_CrossWord_Trivia25 [NEGRO]]
[s]Este color aparece en muchas expresiones y[n]met茨foras con connotaciones negativas como[n]或lista negra位, 或mercado negro位 u 或oveja negra位.[n][w][e]
[s]Muchas banderas de pa胤ses llevan el color negro,[n]pero tiene muchos significados, desde las batallas[n]y la derrota de un enemigo hasta el pasado en general.[n][w][e]

[msg MSG_CrossWord_Trivia26 [HALLOWEEN]]
[s]Fiesta que se celebra el 31 de octubre. Algunos dicen[n]que era un festival de cosecha de los celtas y otros[n]que es una fiesta cristiana para honrar a los santos.[n][w][e]
[s]La linterna de calabaza tambi姻n tiene varios or胤genes,[n]pero en general todos coinciden en que el tallado[n]de calabazas surgi吋 en Irlanda.[n][w][e]

[msg MSG_CrossWord_Trivia27 [CASETAS]]
[s]Tiendas sencillas que los estudiantes crean[n]para eventos escolares. En ellas venden[n]todo tipo de comida y otros productos.[n][w][e]
[s]Se deben reunir ciertos requisitos para poder montar[n]una tienda, como enviar informes al departamento[n]de salud y cumplir las normas de seguridad.[n][w][e]

[msg MSG_CrossWord_Trivia28 [RECOMPENSA]]
[s]Dinero que se otorga a quien cumple los requisitos[n]del recopilador de informaci吋n. Se entrega a quien[n]ofrece una soluci吋n o informaci吋n 雨til sobre un caso.[n][w][e]
[s]En caso de haber varios informantes, la distribuci吋n[n]del Sistema Especial de Incentivos de Investigaci吋n[n]de Jap吋n se basa en el grado de ayuda de cada uno.[n][w][e]

[msg MSG_CrossWord_Trivia29 [VAPULEAR]]
[s]Originalmente, significa 或golpear位 o 或dar una paliza位.[n]Actualmente, tambi姻n significa criticar[n]duramente a una persona o a un grupo.[n][w][e]
[s]En la industria de restauraci吋n[n]japonesa, tambi姻n significa[n]limpiar los platos de una mesa.[n][w][e]

[msg MSG_CrossWord_Trivia30 [CARISMA]]
[s]La habilidad para atraer a otra gente.[n]Deriva de la palabra griega 或charis位,[n]que significa 或gracia位 o 或buena voluntad位.[n][w][e]
[s]El carisma no tiene nada que ver con ser bueno o malo.[n]Alguien caritativo y alguien que comete atrocidades son[n]carism茨ticos si tienen el poder de atraer a los dem茨s.[n][w][e]

[msg MSG_CrossWord_Trivia31 [INFLUENZA]]
[s]Enfermedad infecciosa que da fiebre[n]y dolor de articulaciones. Puede sobrevivir[n]varios d胤as fuera del cuerpo humano.[n][w][e]
[s]Aunque la gripe es dif胤cil de combatir por su mutaci吋n[n]gen姻tica, ya se ha puesto fin a varias enfermedades[n]parecidas, como la peste bovina, erradicada en 2001.[n][w][e]

[msg MSG_CrossWord_Trivia32 [ILUMINAR]]
[s]Se les llama 或denshoku位, literalmente 或iluminaci吋n[n]decorativa位, a las fuentes de luz como tiras LED[n]o bombillas que iluminan letreros y dem茨s.[n][w][e]
[s]Las primeras luces LED de color eran rojas. Tras[n]el desarrollo de las verdes, azules y blancas, los[n]publicistas dispusieron de toda la gama de colores.[n][w][e]

[msg MSG_CrossWord_Trivia33 [APROBACI遺N]]
[s]Un valor num姻rico que indica qu姻 opina la sociedad[n]sobre algo, ya sea el l胤der de un pa胤s o un partido[n]pol胤tico. La aprobaci吋n es independiente del 姻xito.[n][w][e]
[s]La aprobaci吋n se calcula encuestando a un conjunto[n]aleatorio de personas, no a toda la poblaci吋n, as胤 que[n]puede que los resultados no sean del todo exactos.[n][w][e]

[msg MSG_CrossWord_Trivia34 [NAVIDAD]]
[s]El 25 de diciembre en el calendario gregoriano,[n]el d胤a designado para el nacimiento de Jesucristo[n]y el d胤a despu姻s de la jornada laboral de Pap茨 Noel.[n][w][e]
[s]El gobierno estadounidense tiene un programa que[n]rastrea a Pap茨 Noel cada Navidad. Seg雨n sus informes,[n]viaja 100 veces m茨s r茨pido que un tren bala.[n][w][e]

[msg MSG_CrossWord_Trivia35 [PROP遺SITO]]
[s]Meta o plan para el pr吋ximo a隠o. Se hace antes[n]del nuevo a隠o o al principio del mismo. Mucha[n]gente pretende conseguirlo en el plazo de un a隠o.[n][w][e]
[s]Un kanji japon姻s de 或prop吋sito位 significa 或carga位,[n]aunque no se usa con connotaciones negativas,[n]sino que se trata de una responsabilidad.[n][w][e]

[msg MSG_CrossWord_Trivia36 [DIONISO]]
[s]Un dios de la mitolog胤a griega cuyo nombre[n]significa 或joven Zeus位. Viaj吋 por varios pa胤ses,[n]haci姻ndose con muchos devotos fan茨ticos.[n][w][e]
[s]El fil吋sofo Nietzsche design吋 los dos principios[n]centrales de la cultura griega antigua, 或lo apol胤neo位[n]y 或lo dionis胤aco位, en 或El nacimiento de la tragedia位.[n][w][e]

[msg MSG_CrossWord_Trivia37 [L威QUESIS]]
[s]Junto con su hermana peque隠a 威tropos y su hermana[n]mayor Cloto, es una de las diosas griegas del destino.[n]Ella elige el hilo del destino que hay que cortar.[n][w][e]
[s]L茨quesis es tambi姻n el nombre de un g姻nero de[n]crotalinos llamado cascabel muda, las serpientes[n]venenosas m茨s grandes del hemisferio oeste.[n][w][e]

[msg MSG_CrossWord_Trivia38 [OROCHI]]
[s]Yamata-no-Orochi es un drag吋n gigante de ocho[n]cabezas y ocho colas de la mitolog胤a japonesa. Fue[n]asesinado por Susanoo mientras dorm胤a la mona.[n][w][e]
[s]Orochi devor吋 a siete hijas de una pobre pareja[n]de ancianos, as胤 que Susanoo se ofreci吋 a acabar[n]con 姻l a cambio de la mano de la 雨ltima hija.[n][w][e]

[msg MSG_TABLE_FRONT_DEFAULT_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]El sof茨 del local es muy[n]viejo, pero ha quedado limpio[n]como los chorros del oro.[n][w][e]

[msg MSG_TABLE_FRONT_DEFAULT]
[s]El sof茨 ha quedado[n]como los chorros del oro.[n][w][e]

[msg MSG_RuburanTable_Akechi0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]夷Akechi sigue por aqu胤? Bueno,[n]ya no es tan popular, as胤 que[n]no puedo culparle.[n][w][e]

[msg MSG_RuburanTable_Akechi0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]Akechi debe tener mucho tiempo[n]libre si se queda aqu胤[n]hasta tan tarde.[n][w][e]

[msg MSG_RuburanTable_Akechi0_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Akechi sigue aqu胤.[n]No estar茨 tramando algo, 夷no?[n][w][e]

[msg MSG_RuburanTable_Akechi0_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Akechi sigue aqu胤. Este sitio[n]le resultar茨 muy relajante.[n][w][e]

[msg MSG_COUNTER_NOTOPEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Ese libro parece viejo. Ni siquiera[n]se puede leer. 夷Por qu姻 no[n]compras alguno por ah胤?[n][w][e]

[msg MSG_COUNTER_NOTOPEN]
[s]Hay libros viejos[n]de tapa blanda por aqu胤.[n][w][e]

[msg MSG_BookNG_NotNight [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]El Leblanc sigue abierto, 夷no?[n]Si vas a leer, mejor por la noche.[n][w][e]

[msg MND_BookNG_NotNight]
[s]El Leblanc sigue abierto.[n]Si voy a leer, mejor de noche.[n][w][e]

[msg MSG_BookNG_NotNight_nonT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Este parece un buen sitio para[n]leer, pero el Leblanc[n]sigue abierto.[n][w][e]

[msg MND_BookNG_NotNight_nonT]
[s]Este parece un sitio c吋modo[n]para leer un libro,[n]pero el Leblanc sigue abierto.[n][w][e]

[msg MSG_BookNG_StandBy [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1002 65535 0]No hace falta que leas hoy.[n]Es m茨s, deber胤as[n]prepararte para ma隠ana.[n][w][e]

[msg MSG_BookNG_StandBy_nonTu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1002 65535 0]Este parece un buen sitio para[n]leer, pero hoy deber胤as[n]centrarte en prepararte.[n][w][e]

[msg MSG_BookNG_PalaceAfter [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1002 65535 0]Debes estar agotado.[n]Dudo que nada de lo que leas se te[n]quede en la cabeza ahora mismo.[n][w][e]

[msg MND_BookNG_PalaceAfter]
[s]Estoy bastante cansado hoy.[n]Deber胤a leer en otro momento.[n][w][e]

[msg MSG_BookNG_PalaceAfter_n [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1002 65535 0]Ah, 夷te apetece leer algo?[n]Tienes que estar cansado.[n]D姻jalo para otro momento.[n][w][e]

[msg MND_BookNG_PalaceAfter_n]
[s]Parece que aqu胤 puedo[n]leer un libro, pero deber胤a[n]descansar por hoy.[n][w][e]

[msg MSG_BookNG_SleepDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Descansa lo que queda de d胤a,[n]as胤 estaremos listos para ma隠ana.[n]Ya leer茨s en otro momento.[n][w][e]

[msg MND_BookNG_SleepDay]
[s]Ma隠ana va a ser un d胤a duro.[n]Leer姻 en otro momento.[n][w][e]

[msg MSG_BookNG_SleepDay_nonT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Ah, 夷te apetece leer algo?[n]Tienes que estar cansado.[n]D姻jalo para otro momento.[n][w][e]

[msg MND_BookNG_SleepDay_nonT]
[s]Parece que aqu胤 puedo[n]leer un libro, pero deber胤a[n]descansar por hoy.[n][w][e]

[msg MSG_BookNG_NotHave [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Pero si no tienes ning雨n libro...[n][w][e]

[msg MND_BookNG_NotHave]
[s]No tengo libros.[n][w][e]

[msg MSG_BookNG_NotHave_nonTu [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Este parece un buen sitio para[n]leer. 夷Por qu姻 no[n]vas a comprarte un libro?[n][w][e]

[msg MND_BookNG_NotHave_nonTu]
[s]Parece que aqu胤 puedo perderme[n]en las p茨ginas de un libro.[n]Deber胤a comprarme uno.[n][w][e]

[msg MSG_BookNG_KyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Todav胤a quedan clientes.[n]Ya leer茨s en otro momento.[n][w][e]

[msg MND_BookNG_KyakuDay]
[s]Todav胤a quedan clientes.[n]Deber胤a leer en otro momento.[n][w][e]

[msg MSG_BookNG_KyakuDay_nonT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Este parece un buen sitio para[n]leer, pero no puedes hacerlo[n]mientras haya clientes.[n][w][e]

[msg MND_BookNG_KyakuDay_nonT]
[s]Este parece un buen sitio para[n]leer, pero todav胤a hay clientes.[n][w][e]

[msg MSG_RubuBook_Tuto [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Parece un buen sitio[n]para leer un poco.[n][w][e]

[msg MND_RubuBook_Tuto]
[s]Este parece el t胤pico sitio donde[n]podr胤a concentrarme y leer mucho.[n][w][e]

[msg MSG_TABLE_Book_SojiroGoH [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5020 65535 0]夷Eh...? 夷Quieres usar el local[n]para algo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Bueno... No rompas nada.[n]Me voy a casa.[n][w][e]

[msg MSG_TABLE_Book_SojiroGoH_2 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Muy bien, me voy a casa.[n][w][e]

[msg MSG_PHONE_DEFAULT_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]夷Eh? 夷Por qu姻 ibas a usar[n]esa cosa hoy en d胤a?[n][w][e]

[msg MSG_PHONE_DEFAULT]
[s]Me pregunto si habr茨 clientes[n]que usen este tel姻fono p雨blico...[n][w][e]

[msg MSG_PHONE_0410_mes01]
[s]Me pregunto si habr茨 clientes[n]que usen este tel姻fono p雨blico...[n][w][e]

[msg MSG_PHONE_STANDBY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ma隠ana es el asalto, 夷sabes?[n]Deja eso para otra ocasi吋n.[n][w][e]

[msg MSG_PHONE_KyakuDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Si usas el tel姻fono mientras[n]la tienda sigue abierta,[n]el Jefe se enfadar茨.[n][w][e]

[msg MSG_COFFEE_NG_mes01]
[s]Queda alguna cafetera por aqu胤.[n][w][e]

[msg MSG_Coffee_NotOpen_Kyaku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Entonces, esto sirve para[n]hacer caf姻, 夷no? Parece que[n]se ha usado bastante.[n][w][e]

[msg MSG_Coffee_Open_Kyaku [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]El Leblanc sigue abierto.[n]No deber胤as hacer eso ahora.[n][w][e]

[msg MSG_Coffee_Open_Akechi [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Oye, Akechi tambi姻n es[n]un cliente. No deber胤amos[n]preparar caf姻 ahora.[n][w][e]

[msg MSG_Coffee_Open_Goro [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Oye, Akechi es tambi姻n[n]un cliente. No deber胤amos[n]preparar caf姻 ahora.[n][w][e]

[msg MSG_COFFEE_NG_0410_mes01]
[s]Deber胤a coger el tel姻fono.[n][w][e]

[msg MSG_COFFEE_NG_0410_mes02]
[s]Ahora mismo, prefiero comer algo[n]antes que tomar caf姻.[n]Vamos a mirar en el [clr 2]frigor胤fico[clr 27].[n][w][e]

[msg MSG_COFFEE_NOTOPEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Entonces, esto sirve para[n]hacer caf姻, 夷no? Parece que[n]se ha usado bastante.[n][w][e]

[msg MSG_COFFEE_NOTOPEN]
[s]Aqu胤 hay toda una selecci吋n[n]de aparatos que pueden usarse[n]para hacer caf姻.[n][w][e]

[msg MSG_Coffee_Sojiro_FIRST [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5001 65535 0]夷Sabes preparar caf姻?[n][w][e]
[s][f 4 10 65535 0 0]Usa los granos de las estanter胤as.[n]Luego te ense隠ar姻 las diferencias[n]entre los distintos tipos.[n][w][e]
[s][f 4 10 65535 0 0]Vale, voy a salir[n]a comprar tabaco.[n][w][e]

[msg MSG_Coffee_Sojiro_01 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5122 65535 0]Parece que te est茨 empezando[n]a interesar esto. No estar茨s[n]intentando impresionarme, 夷no?[n][w][e]
[s][f 4 10 65535 0 0]Bueno, da igual. Vale,[n]voy a salir a comprar tabaco.[n][w][e]

[msg MSG_Coffee_Sojiro_02 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5019 65535 0]Es bastante divertido cuando[n]empiezas, 夷eh? Se disfruta y[n]se aprende mucho con el caf姻.[n][w][e]
[s][f 4 10 65535 0 0]Bueno, da igual. Vale,[n]voy a salir a comprar tabaco.[n][w][e]

[msg MSG_Coffee_Sojiro_03 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5092 65535 0]Vaya, s胤 que tienes ganas.[n]Te ha picado bien la curiosidad[n]por el caf姻, 夷eh?[n][w][e]
[s][f 4 10 65535 0 0]Bueno, da igual. Vale,[n]voy a salir a comprar tabaco.[n][w][e]

[msg MSG_Coffee_Sojiro_04 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5024 65535 0]Parece que te lo est茨s[n]tomando en serio. 夷Quieres[n]apoderarte de la cafeter胤a?[n][w][e]
[s][f 4 10 65535 0 0]Bueno, da igual. Vale,[n]voy a salir a comprar tabaco.[n][w][e]

[msg MSG_Coffee_Sojiro_GoHome [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5053 65535 0]Me voy a casa ya.[n]Me gusta que te est姻s[n]interesando por esto.[n][w][e]

[msg MSG_CoffeeNG_KawaCurryON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Kawakami est茨 usando la cocina[n]ahora mismo. Tendr茨s que[n]preparar caf姻 en otro momento.[n][w][e]

[msg MSG_CoffeeNG_KawaCurryON_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]El Jefe te ha ense隠ado a preparar[n]caf姻, pero parece que Kawakami[n]est茨 usando la cocina.[n][w][e]

[msg MSG_COFFEE_NOT_NIGHT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]El Jefe te ha ense隠ado a preparar[n]caf姻, pero deber胤as esperar[n]a que cierre la cafeter胤a.[n][w][e]

[msg MND_COFFEE_NOT_NIGHT]
[s]El Leblanc sigue abierto.[n]Tendr姻 que preparar[n]caf姻 por la noche.[n][w][e]

[msg MSG_COFFEE_TodayGoPalace [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷Por qu姻 vas a hacer esto,[n]si est茨s hecho polvo? Vamos[n]a dejarlo para otro momento.[n][w][e]

[msg MND_COFFEE_TodayGoPalace]
[s]Hoy estoy muy cansado.[n]Dejar姻 esto para ma隠ana.[n][w][e]

[msg MSG_COFFEE_OrderAfter [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷No le has pedido a alguien[n]que te haga caf姻?[n][w][e]

[msg MND_COFFEE_OrderAfter]
[s]Ya le he pedido a Kawakami[n]que haga caf姻.[n][w][e]

[msg MSG_COFFEE_NoticeDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷Est茨s pensando en usar[n]la m茨quina de hacer caf姻? Primero[n]deber胤as descansar para ma隠ana.[n][w][e]

[msg MND_COFFEE_NoticeDay]
[s]Deber胤a descansar para ma隠ana.[n][w][e]

[msg MSG_COFFEE_SHELF_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Blue Mountain, Kilimanjaro,[n]Guatemala, Costa Rica...[n][w][e]
[s][f 4 10 65535 0 0]夷Todos son diferentes tipos[n]de granos de caf姻? Hay m茨s[n]de los que pensaba.[n][w][e]

[msg MSG_COFFEE_SHELF]
[s]Una selecci吋n de granos de caf姻[n]ordenados. El suave aroma del caf姻[n]llega hasta aqu胤.[n][w][e]
[s]Blue Mountain, Kilimanjaro,[n]Guatemala, Costa Rica...[n][w][e]
[s]Tambi姻n hay otros cuyo nombre[n]no conozco.[n][w][e]

[msg MSG_COFFEE_SETUMEI_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Blue Mountain, Kilimanjaro,[n]Guatemala, Costa Rica...[n][w][e]
[s][f 4 10 65535 0 0]夷Todos son diferentes tipos[n]de granos de caf姻? Hay m茨s[n]de los que pensaba.[n][w][e]
[s][f 4 10 65535 0 0]夷Recuerdas cuando el Jefe[n]te ense隠吋 cosas sobre el caf姻?[n]夷Te acuerdas de algunos tipos?[n][w][e]

[msg MND_COFFEE_SETUMEI_01]
[s]Una selecci吋n de granos de caf姻[n]ordenados. El suave aroma del caf姻[n]llega hasta aqu胤.[n][w][e]
[s]Blue Mountain, Kilimanjaro,[n]Guatemala, Costa Rica...[n][w][e]
[s]Tambi姻n hay otros cuyo nombre[n]no conozco.[n][w][e]
[s]Recuerdo cuando Sojiro[n]me ense隠吋 cosas sobre el caf姻.[n][w][e]

[msg MSG_COFFEE_OSIMAI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1163 65535 0]Cu茨ntos granos de caf姻...[n][w][e]

[msg MND_COFFEE_OSIMAI]
[s]Creo que he descubierto[n]algunos secretos[n]sobre el rico sabor del caf姻.[n][w][e]

[msg COFFEE_MENU]
[s]Conocimiento en grano de caf姻[n][e]

[sel COFFEE_SEL top]
[s]Blue Mountain de Jamaica[e]
[s]Caf姻 SHB guatemalteco[e]
[s]Colombiano de Nari隠o[e]
[s]Crystal Mountain de Cuba[e]
[s]Caf姻 Kona hawaiano[e]
[s]Caf姻 Moca Harrar de Etiop胤a[e]
[s]Caf姻 moca Matari[e]
[s]Caf姻 mexicano Altura[e]
[s]Brasile隠o n.伊 2/18[e]
[s]Colombiano de Bucaramanga supremo[e]
[s]Caf姻 SHB de Costa Rica[e]
[s]Caf姻 Kenia AA[e]
[s]Bourbon brasile隠o[e]
[s]Colombiano 100 % Typica[e]
[s]Caf姻 SHG de Honduras[e]
[s]Guatemala Antigua[e]
[s]El Salvador Pacamara[e]
[s]Panama Esmeralda Geisha[e]
[s]Kopi Luwak de Indonesia[e]

[msg SYS_050_1_0 [Blue Mountain de Jamaica]]
[s][vp 8 2 65535 0 0 0]Las Monta隠as Azules de Jamaica[n]tienen un clima 雨nico y un suelo[n]volc茨nico bueno para cultivar caf姻.[n][w][e]
[s][vp 8 2 65535 0 0 0]El caf姻 se controla y se[n]cosecha en peque隠as cantidades. As胤[n]se obtiene un caf姻 con mucho aroma.[n][w][e]

[msg SYS_051_1_0 [Caf姻 SHB guatemalteco]]
[s][vp 8 2 65535 0 0 0]El suelo volc茨nico de Guatemala es ideal[n]para plantar caf姻. Sus granos se clasifican[n]seg雨n la altitud a la que se cultivan.[n][w][e]
[s][vp 8 2 65535 0 0 0]El caf姻 estrictamente duro (SHB),[n]cultivado a m茨s de 1400 metros,[n]es consistente y de acidez c胤trica.[n][w][e]

[msg SYS_052_1_0 [Colombiano de Nari隠o]]
[s][vp 8 2 65535 0 0 0]La altitud, clima lluvioso y suelo[n]de las monta隠as colombianas son la[n]fuerte base de su caf姻 de calidad.[n][w][e]
[s][vp 8 2 65535 0 0 0]El caf姻 de Nari隠o es cremoso y[n]sabe a frutas y nueces.[n][w][e]

[msg SYS_053_1_0 [Crystal Mountain de Cuba]]
[s][vp 8 2 65535 0 0 0]Cuba es la isla m茨s grande[n]del Caribe. Su caf姻 es conocido[n]por su aroma y sabor.[n][w][e]
[s][vp 8 2 65535 0 0 0]El caf姻 Crystal Mountain se hace[n]con los granos m茨s grandes. Es[n]dulce, poco 茨cido y sabe a nueces.[n][w][e]

[msg SYS_054_1_0 [Caf姻 Kona hawaiano]]
[s][vp 8 2 65535 0 0 0]Una delicia hawaiana. Por su rareza[n]y el precio de los granos, la mezcla[n]solo necesita un 10 % de granos Kona.[n][w][e]
[s][vp 8 2 65535 0 0 0]Preparar un caf姻 Kona 100 % es muy[n]caro. Es famoso por tener sabor,[n]una ligera acidez y un aroma complejo.[n][w][e]

[msg SYS_055_1_0 [Caf姻 Moca Harrar de Etiop胤a]]
[s][vp 8 2 65535 0 0 0]Moca es una ciudad de Yemen,[n]desde donde se exportan el caf姻[n]yemen胤 y el Moca Harrar de Etiop胤a.[n][w][e]
[s][vp 8 2 65535 0 0 0]El caf姻 de esta zona se llama moca.[n]Tiene un sabor especiado y[n]un fuerte aroma con notas de mora.[n][w][e]

[msg SYS_056_1_0 [Caf姻 moca Matari]]
[s][vp 8 2 65535 0 0 0]Moca es una ciudad de Yemen,[n]desde donde se exportan el caf姻[n]yemen胤 y el Moca Harrar de Etiop胤a.[n][w][e]
[s][vp 8 2 65535 0 0 0]Moca Matari tiene sabor a especias[n]y chocolate con un cuerpo pesado[n]parecido al del vino.[n][w][e]

[msg SYS_057_1_0 [Caf姻 mexicano Altura]]
[s][vp 8 2 65535 0 0 0]Los espa隠oles trajeron el caf姻 a[n]M姻xico en el siglo XVIII. Ahora, es[n]uno de los mayores productores.[n][w][e]
[s][vp 8 2 65535 0 0 0]El nombre 或Altura位 se debe a la[n]altitud a la que se cultiva el caf姻,[n]que huele a tomillo y sabe a nueces.[n][w][e]

[msg SYS_058_1_0 [Brasile隠o n.伊 2/18]]
[s][vp 8 2 65535 0 0 0]Brasil es el mayor productor[n]de caf姻. Este es de gran calidad,[n]acidez justa y acabado amargo.[n][w][e]
[s][vp 8 2 65535 0 0 0]El caf姻 n.伊 2/18, conocido como[n]Santos, es un caf姻 muy famoso. El 2[n]es la calidad, y el 18, el tama隠o.[n][w][e]

[msg SYS_059_1_0 [Colombiano de Bucaramanga supremo]]
[s][vp 8 2 65535 0 0 0]La altitud, clima lluvioso y suelo[n]de las monta隠as colombianas son la[n]fuerte base de su caf姻 de calidad.[n][w][e]
[s][vp 8 2 65535 0 0 0]Supremo se refiere al tama隠o,[n]y Bucaramanga es donde se cultiva.[n]Tiene sabor dulce y acidez suave.[n][w][e]

[msg SYS_060_1_0 [Caf姻 SHB de Costa Rica]]
[s][vp 8 2 65535 0 0 0]En Costa Rica abundan la flora[n]y la fauna, y el pa胤s ha exportado[n]caf姻 durante siglos.[n][w][e]
[s][vp 8 2 65535 0 0 0]El caf姻 estrictamente duro (SHB) es el[n]que se cultiva a m茨s de 1400 metros.[n]Es elegante y tiene un sabor dulce.[n][w][e]

[msg SYS_061_1_0 [Caf姻 Kenia AA]]
[s][vp 8 2 65535 0 0 0]Las granjas de caf姻 de Kenia est茨n[n]muy controladas y producen granos[n]de caf姻 de gran calidad.[n][w][e]
[s][vp 8 2 65535 0 0 0]El caf姻 AA se cultiva a gran[n]altitud. AA se refiere a la calidad.[n]Tiene mucho aroma y acidez media.[n][w][e]

[msg SYS_062_1_0 [Bourbon brasile隠o]]
[s][vp 8 2 65535 0 0 0]Brasil es el mayor productor[n]de caf姻. Este es de gran calidad,[n]acidez justa y acabado amargo.[n][w][e]
[s][vp 8 2 65535 0 0 0]El Bourbon brasile隠o se produce[n]en peque隠as cantidades y es raro.[n]Es dulce y tiene un acabado limpio.[n][w][e]

[msg SYS_063_1_0 [Colombiano 100 % Typica]]
[s][vp 8 2 65535 0 0 0]La altitud, clima lluvioso y suelo[n]de las monta隠as colombianas son la[n]fuerte base de su caf姻 de calidad.[n][w][e]
[s][vp 8 2 65535 0 0 0]Este caf姻 se hace con granos[n]Typica y es dif胤cil de cosechar.[n]Es c胤trico y muy arom茨tico.[n][w][e]

[msg SYS_064_1_0 [Caf姻 SHG de Honduras]]
[s][vp 8 2 65535 0 0 0]El paisaje de Honduras es monta隠oso[n]o de terreno alto. La calidad[n]del caf姻 depende de la altitud.[n][w][e]
[s][vp 8 2 65535 0 0 0]El caf姻 SHG se cultiva a gran altitud.[n]Tiene un aroma afrutado, suave[n]acidez y un sabor s吋lido.[n][w][e]

[msg SYS_065_1_0 [Guatemala Antigua]]
[s][vp 8 2 65535 0 0 0]El suelo volc茨nico de Guatemala es ideal[n]para plantar caf姻. Sus granos se clasifican[n]seg雨n la altitud a la que se cultivan.[n][w][e]
[s][vp 8 2 65535 0 0 0]Los minerales y nutrientes del suelo[n]dotan al caf姻 Antigua de[n]una acidez suave y un regusto fresco.[n][w][e]

[msg SYS_066_1_0 [El Salvador Pacamara]]
[s][vp 8 2 65535 0 0 0]El 50 % de las exportaciones de El[n]Salvador son de caf姻. El Pacamara[n]es un h胤brido que viene de all胤.[n][w][e]
[s][vp 8 2 65535 0 0 0]Surge de una planta h胤brida que[n]produce muchos granos grandes.[n]Es denso y sabe a chocolate.[n][w][e]

[msg SYS_067_1_0 [Panama Esmeralda Geisha]]
[s][vp 8 2 65535 0 0 0]Esta variedad tan codiciada tiene[n]el r姻cord de pujas m茨s altas[n]en las subastas de caf姻 de Panam茨.[n][w][e]
[s][vp 8 2 65535 0 0 0]Se cultiva muy poco y por eso[n]es tan rara. Tiene aroma a flores,[n]una fresca acidez y acabado dulce.[n][w][e]

[msg SYS_068_1_0 [Kopi Luwak de Indonesia]]
[s][vp 8 2 65535 0 0 0]Este raro caf姻 se hace con granos[n]que han sido digeridos[n]por la civeta de palmera asi茨tica.[n][w][e]
[s][vp 8 2 65535 0 0 0]Aunque es caro, el Kopi Luwak tiene[n]gran aroma y sabor por las[n]encimas digestivas de la civeta.[n][w][e]

[msg MND_SayuriPicture]
[s]Es el 或Sayuri位,[n]ese cuadro tan famoso.[n][w][e]
[s]Siento que desprende[n]un profundo amor de madre.[n][w][e]

[msg MSG_SayuriPicture [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]或Sayuri位, 夷eh?[n][w][e]
[s][f 4 10 65535 0 0]El cuadro me transmite bondad[n]y ternura. Las madres[n]son realmente fuertes.[n][w][e]

[msg STOP_OUTDOOR_DEFAULT_MOR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Deber胤amos acostarnos ya.[n][w][e]

[msg STOP_OUTDOOR_DEFAULT]
[s]Deber胤a irme a dormir...[n][w][e]

[msg STOP_OUTDOOR_0410]
[s]Ya es tarde... No deber胤a salir[n]en lo que queda de d胤a.[n][w][e]

[msg MSG_CHK_DOOR_playroom [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Tus amigos han venido a verte.[n]夷Vas a salir?[n][w][e]
[s][f 4 10 65535 0 0]Si lo haces, se ir茨n.[n]夷Qu姻 quieres hacer?[n][w][e]

[sel SEL_CHK_DOOR_pc_playroom top]
[s]Voy a salir.[e]
[s]Me quedar姻 en casa.[e]

[msg MSG_CHK_DOOR_ryuji_react [Ryuji]]
[s]Culpa m胤a. Bueno,[n]nos vemos ma隠ana.[n][w][e]

[msg MSG_CHK_DOOR_anne_reacti [Ann]]
[s]Siento haberme presentado[n]as胤 de repente. Hasta luego.[n][w][e]

[msg MSG_CHK_DOOR_makoto_reac [Makoto]]
[s]Ah, lo siento. Nos vemos ma隠ana.[n][w][e]

[msg MSG_CHK_DOOR_yusuke_reac [Yusuke]]
[s]Entiendo... siento molestar.[n]Disc雨lpame.[n][w][e]

[msg MSG_CHK_DOOR_akechi_reac [Akechi]]
[s]Siento si molesto.[n]Vendr姻 en otro momento.[n][w][e]

[msg MSG_CHK_DOOR_futaba_reac [Futaba]]
[s]*suspiro* Vaaaale. T胤胤胤胤胤o...[n]Me ir姻 a casa.[n][w][e]

[msg MSG_CHK_DOOR_haru_reacti [Haru]]
[s]Vale, lo entiendo.[n]Hasta luego, entonces.[n][w][e]

[msg MSG_STANDBY_MORU_DOOR_No [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]斡Ma隠ana es el asalto! Ser茨 mejor[n]tom茨rselo con calma y no salir.[n][w][e]

[msg MSG_GO_DUNGEON_TODAY_MOR [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷No est茨s cansado?[n]Ser茨 mejor que no salgamos.[n][w][e]

[msg MND_GO_DUNGEON_TODAY]
[s]Estoy bastante cansado hoy.[n]Deber胤a relajarme y[n]quedarme en mi habitaci吋n.[n][w][e]

[msg MSG_GO_DUNGEON_TODAY_MOR_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Tenemos que pensar en ma隠ana.[n]Podemos salir en otro momento.[n][w][e]

[msg MND_GO_DUNGEON_TODAY_V2]
[s]Tengo que pensar en ma隠ana.[n][w][e]
[s]Deber胤a salir en otra ocasi吋n.[n][w][e]

[msg MSG_STOP_GO_OUT_0501 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sabes lo que tienes que hacer[n]ma隠ana, 夷no? Tampoco nos excedamos.[n]Vamos a dormir ya.[n][w][e]

[msg MSG_STOP_GO_OUT_0503 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Seguro que ma隠ana venderemos[n]aquello, as胤 vamos a relajarnos[n]en casa esta noche.[n][w][e]

[msg MSG_STOP_GO_OUT_0504 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Ma隠ana es la fiesta, 夷no?[n]Descansemos en casa hoy.[n][w][e]

[msg MSG_STOP_GO_OUT_0505 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0]Je, je, je. 斡Estaba buen胤simo![n]Voy a reventar.[n][w][e]
[s][vp 1 0 0 0 0 0]Deber胤amos descansar esta noche.[n]A partir de ma隠ana trabajaremos[n]como [f 4 28].[n][w][e]

[msg MSG_STOP_GO_OUT_0507 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Supongo que estar茨s cansado[n]despu姻s del d胤a de hoy.[n]Salgamos en otra ocasi吋n.[n][w][e]

[msg MSG_STOP_GO_OUT_0604 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sabes lo que tienes que hacer[n]ma隠ana, 夷no? Tampoco nos excedamos.[n]Vamos a dormir ya.[n][w][e]

[msg MSG_STOP_GO_OUT_0619 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1188 65535 0]Debes estar cansado despu姻s[n]del Metaverso. Admiro tu tenacidad,[n]pero ya est茨 bien por hoy.[n][w][e]

[msg MSG_STOP_GO_OUT_0620 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Estoy destrozado despu姻s[n]del Palacio. Descansemos por hoy.[n][w][e]

[msg MSG_STOP_GO_OUT_0708 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sabes lo que tienes que hacer[n]ma隠ana, 夷no? Tampoco nos excedamos.[n]Vamos a dormir ya.[n][w][e]

[msg MSG_STOP_GO_OUT_0710 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 53114 65535 0]Miau... Hoy has hecho[n]un buen trabajo. Es tarde, as胤 que[n]ser茨 mejor no salir esta noche.[n][w][e]

[msg MSG_STOP_GO_OUT_0820 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sabes lo que tienes que hacer[n]ma隠ana, 夷no? Tampoco nos excedamos.[n]Vamos a dormir ya.[n][w][e]

[msg MSG_STOP_GO_OUT_1007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sabes lo que tienes que hacer[n]ma隠ana, 夷no? Tampoco nos excedamos.[n]Vamos a dormir ya.[n][w][e]

[msg MSG_STOP_GO_OUT_1011 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Eh, qued姻monos en casa.[n]夷De verdad te apetece salir?[n][w][e]

[msg MSG_STOP_GO_OUT_1012_101 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]夷No quedamos en que[n]ten胤amos que pasar[n]desapercibidos? Mejor no salgamos.[n][w][e]

[msg MSG_STOP_GO_OUT_1020_102 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Si el equipo de investigaci吋n te[n]ve, estamos acabados. Lo mejor ser茨[n]no andar por ah胤 de noche.[n][w][e]

[msg MSG_STOP_GO_OUT_1120 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sabes lo que tienes que hacer[n]ma隠ana, 夷no? Tampoco nos excedamos.[n]Vamos a dormir ya.[n][w][e]

[msg MSG_STOP_GO_OUT_1217 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Sabes lo que tienes que hacer[n]ma隠ana, 夷no? Tampoco nos excedamos.[n]Vamos a dormir ya.[n][w][e]

[msg MSG_STOP_GO_OUT_01 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Anda con cuidado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por otro lado, seguro que nadie[n]va a estar buscando a quien[n]se supone que ha muerto.[n][w][e]

[msg MSG_STOP_GO_OUT_02 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]No vuelvas tarde, 夷eh?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por otro lado, seguro que nadie[n]va a estar buscando a quien[n]se supone que ha muerto.[n][w][e]

[msg MSG_STOP_GO_OUT_03 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Intenta no meterte en[n]ning雨n l胤o, 夷de acuerdo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por otro lado, seguro que nadie[n]va a estar buscando a quien[n]se supone que ha muerto.[n][w][e]

[msg MSG_NIGHTWALK_NG [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Espera, 夷qui姻n te ha dado[n]permiso para salir?[n][w][e]

[msg MSG_NIGHT_RESTRICTION [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Yo soy quien tiene que cerrar[n]la puerta con llave. Procura no[n]estar fuera hasta muy tarde, 夷vale?[n][w][e]

[msg MSG_0506_0604_0 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5018 65535 0]Oye, no te vayas a meter[n]en ning雨n l胤o raro, 夷vale?[n][w][e]

[msg MSG_0506_0604_1 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5081 65535 0]No te vayas a acercar a sitios[n]que puedan ser peligrosos, 夷vale?[n][w][e]

[msg MSG_0506_0604_2 [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 5106 65535 0]Todav胤a est茨s en libertad[n]condicional. Que no se te olvide.[n][w][e]

[msg MSG_DUNGEON_SENTOU_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷No est茨s cansado? Si vas a salir,[n]que sea a los ba隠os p雨blicos.[n][w][e]

[msg MND_DUNGEON_SENTOU]
[s]Hoy estoy cansado.[n]No deber胤a salir.[n][w][e]
[s]A lo mejor voy a los ba隠os p雨blicos[n]para acabar bien el d胤a.[n][w][e]

[msg MSG_EVENT_SENTOU_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Piensa en el d胤a que te espera[n]ma隠ana. Si vas a salir, procura ir[n]solo a los ba隠os p雨blicos.[n][w][e]

[msg MND_EVENT_SENTOU]
[s]Tengo que pensar en el d胤a que me[n]espera ma隠ana. No deber胤a ir lejos.[n][w][e]
[s]A lo mejor voy a los ba隠os p雨blicos[n]para acabar bien el d胤a.[n][w][e]

[sel SEL_LEBLANC_SENTOU top]
[s]Ir a los ba隠os p雨blicos[e]
[s]Pensarlo[e]

[msg MND_Sentou_ParamUpInfo]
[s]Creo que podr姻 mejorar[n]mi [f 4 11 1][clr 26][f 4 12 1][clr 27] un poco m茨s.[n][w][e]

[msg MND_Sentou_ParamEndInfo]
[s]Creo que ya tengo suficiente[n][f 4 11 1][clr 26][f 4 12 1][clr 27].[n][w][e]

[msg MSG_LEBLANC_SENTOU_NoMon [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Un momento.[n]No puedes ir a los ba隠os p雨blicos[n]con tan poco dinero.[n][w][e]

[msg MND_LEBLANC_SENTOU_NoMon]
[s]Parece que no tengo[n]suficiente dinero.[n][w][e]

[msg MSG_SYSTEM_SHORTCUT_SENT]
[s]Ya puedes usar Viaje r茨pido para ir[n]a los [clr 6]ba隠os p雨blicos[clr 0] en Yongen-Jaya.[n][w][e]

[msg MSG_LEBLANC_SENTOU_LAST [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Creo que la entrada eran 500 yenes.[n][w][e]

[msg fev0410_05_EXIT_NG_mes01]
[s][vp 1 0 0 0 0 0]Parece que todav胤a[n]hay jaleo en la calle.[n][w][e]
[s][vp 1 0 0 0 0 0]Deber胤a coger el tel姻fono.[n][w][e]

[msg fev0410_05_EXIT_NG_mes02]
[s][vp 1 0 0 0 0 0]Parece que todav胤a[n]hay jaleo en la calle.[n][w][e]
[s][vp 1 0 0 0 0 0]Tengo mucho que hacer[n]ma隠ana temprano, as胤 que es mejor[n]que me quede el resto del d胤a.[n][w][e]

[msg MSG_GO_OUTSIDE_000 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]Ah, 夷y puedes girar el cartel[n]de la puerta para que[n]ponga 或abierto位?[n][w][e]

[sel SEL_GO_OUTSIDE_001 top]
[s]Vale, entendido.[e]
[s]夷Por qu姻 deber胤a?[e]
[s]夷Ya hemos abierto?[e]

[msg MSG_GO_OUTSIDE_010 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]No te olvides, 夷de acuerdo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Ya te puedes dar prisa.[n]Vas a llegar tarde[n]como te pierdas, pueblerino.[n][w][e]

[msg MSG_GO_OUTSIDE_011 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]夷No lo pillas? Forma parte[n]de tus tareas[n]mientras vivas bajo mi techo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 15 65535 0]Ya te puedes dar prisa.[n]Vas a llegar tarde[n]como te pierdas, pueblerino.[n][w][e]

[msg MSG_GO_OUTSIDE_012 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 1 16 65535 0]夷Ya? En fin, que vamos tarde.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]Ya te puedes dar prisa.[n]Vas a llegar tarde[n]como te pierdas, pueblerino.[n][w][e]

[msg MSG_GO_OUTSIDE_127101_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]G胤rame el cartel de la puerta.[n]Forma parte de tu trabajo.[n][w][e]

[sel SEL_GO_OUTSIDE_127101_00 top]
[s]Vale, entiendo.[e]
[s]夷Mi trabajo...?[e]

[msg MSG_GO_OUTSIDE_127101_00_2 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estupendo.[n][w][e]

[msg MSG_GO_OUTSIDE_127101_00_3 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]S胤, eso es. Aunque, bueno...,[n]ni que fuese a pagarte.[n][w][e]

[msg MSG_E22810100_NG_GOOUT [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5001 65535 0]夷Eh? 夷Ad吋nde vas? Tus amigos[n]han salido a comprar algo.[n][w][e]

[msg MSG_0415_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]夷Ya estamos?[n][w][e]

[msg MSG_0415_01 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5001 65535 0]夷Acabo de o胤r a un gato?[n][w][e]

[sel SEL_0415 top]
[s]Yo no he o胤do nada.[e]
[s]Son imaginaciones tuyas.[e]
[s]Era de fuera.[e]

[msg MSG_0415_02 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, da igual.[n]Supongo que no importa, pero...[n][w][e]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 2 1 5099 65535 0]夷Sabes? Hay gatos que se meten[n]en el local y ni siquiera[n]nos damos cuenta, as胤 que...[n][w][e]

[msg MSG_0415_03 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Oye, no des de comer a ning雨n gato[n]callejero, 夷entendido? Solo[n]conseguir茨s molestar a los vecinos.[n][w][e]

[msg MSG_E40110100_TALK [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, 夷ad吋nde vas?[n]Ven aqu胤 y dime qu姻 opinas de esto.[n][w][e]

[msg EX_FREEZER_0410_mes00]
[s][vp 1 0 0 0 0 0]Los ingredientes de la tienda[n]est茨n guardados aqu胤. No deber胤a[n]usar ninguno sin preguntar.[n][w][e]

[msg MSG_E10920200_CHK_Freeze [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Ejem.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Date prisa y ci姻rralo.[n]No quiero que se estropee nada[n]de lo que hay dentro.[n][w][e]

[msg MSG_E12710100_CHK_Freeze [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Ejem.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Date prisa y ci姻rralo.[n]No quiero que se estropee nada[n]de lo que hay dentro.[n][w][e]

[msg MSG_E22810100_CHK_Freeze [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Eh, si vas a coger algo de comida[n]del local, m茨s te vale pagarla.[n][w][e]

[msg MSG_E22810100_CHK_Freeze_2 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]夷No vas a necesitar[n]una olla para eso?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Y si vas a coger algo de comida[n]del local, m茨s te vale pagarla.[n][w][e]

[msg MND_COMMON_CHK_Freezer_0]
[s][vp 1 0 0 0 0 0]Parece que los ingredientes[n]de la tienda est茨n guardados aqu胤.[n][w][e]

[msg MSG_E10920200_CHK_Kitche [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]夷Qu姻 est茨s haciendo?[n]Anda, vete al instituto.[n][w][e]

[msg MSG_E12710100_CHK_Kitche [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]夷Qu姻 est茨s haciendo?[n]Anda, vete al instituto.[n][w][e]

[msg MND_E22810100_CHK_Kitche]
[s][vp 1 0 0 0 0 0]Solo hay cafeteras por aqu胤.[n][w][e]

[msg MND_COMMON_CHK_Kitchen_0]
[s][vp 1 0 0 0 0 0]Queda alguna cafetera por aqu胤.[n][w][e]

[msg MSG_E10530200_CHK_Phone_]
[s][vp 1 0 0 0 0 0]Me pregunto si habr茨 clientes[n]que usen este tel姻fono p雨blico...[n][w][e]

[msg MSG_E10920200_CHK_Phone_ [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]夷Qu姻 est茨s haciendo?[n]Anda, vete al instituto.[n][w][e]

[msg MSG_E12710100_CHK_Phone_ [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]夷Qu姻 est茨s haciendo?[n]Anda, vete al instituto.[n][w][e]

[msg MND_E22810100_CHK_Phone_]
[s][vp 1 0 0 0 0 0]Deber胤a centrarme[n]en encontrar una olla.[n][w][e]

[msg MND_COMMON_CHK_Phone_000]
[s][vp 1 0 0 0 0 0]No tengo tiempo para esto ahora.[n][w][e]

[msg MSG_E10530200_CHK_Counte]
[s][vp 1 0 0 0 0 0]Hay libros viejos[n]de tapa blanda por aqu胤.[n][w][e]

[msg MSG_E10920200_CHK_Counte [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]夷Qu姻 est茨s haciendo?[n]Anda, vete al instituto.[n][w][e]

[msg MSG_E12710100_CHK_Counte [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]夷Qu姻 est茨s haciendo?[n]Anda, vete al instituto.[n][w][e]

[msg MND_E22810100_CHK_Counte]
[s][vp 1 0 0 0 0 0]Deber胤a ir a preparar la olla.[n][w][e]

[msg MND_COMMON_CHK_Counter_0]
[s][vp 1 0 0 0 0 0]Hay un libro que parece antiguo[n]colocado en el mostrador.[n][w][e]

[msg MSG_E10530200_CHK_Table_]
[s][vp 1 0 0 0 0 0]Esta mesa tiene pinta[n]de haber sido pulida con mimo.[n][w][e]

[msg MSG_E10920200_CHK_Table_ [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]夷Qu姻 est茨s haciendo?[n]Anda, vete al instituto.[n][w][e]

[msg MSG_E12710100_CHK_Table_ [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]夷Qu姻 est茨s haciendo?[n]Anda, vete al instituto.[n][w][e]

[msg MND_E22810100_CHK_Table_]
[s][vp 1 0 0 0 0 0]Deber胤a ir a preparar la olla.[n][w][e]

[msg MND_COMMON_CHK_Table_000]
[s][vp 1 0 0 0 0 0]No tengo tiempo para relajarme.[n][w][e]

[msg MSG_E10530200_Table_Fron]
[s][vp 1 0 0 0 0 0]El sof茨 ha quedado[n]como los chorros del oro.[n][w][e]

[msg MSG_E12710100_Table_Fron [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5003 65535 0]夷Qu姻 est茨s haciendo?[n]Anda, vete al instituto.[n][w][e]

[msg MND_E22810100_Table_Fron]
[s][vp 1 0 0 0 0 0]Deber胤a ir a preparar la olla.[n][w][e]

[msg MND_E14620000_Table_Fron]
[s][vp 1 0 0 0 0 0]Hay un cliente en el Leblanc.[n][w][e]

[msg MND_COMMON_Table_Front_0]
[s][vp 1 0 0 0 0 0]No tengo tiempo para relajarme.[n][w][e]

[msg MND_E10920200_CHK_Kitche]
[s][vp 1 0 0 0 0 0]Hay una olla de curry enorme aqu胤.[n]Parece ser la especialidad[n]de la casa.[n][w][e]

[msg MSG_E10920200_CHK_Kitche_2 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5150 65535 0]夷Qu姻 est茨s haciendo?[n]No estropees nada que sea[n]para la clientela, 夷entendido?[n][w][e]

[msg MND_E12710100_CHK_Kitche]
[s][vp 1 0 0 0 0 0]Hay una olla de curry enorme aqu胤.[n]Parece ser la especialidad[n]de la casa.[n][w][e]

[msg MSG_E12710100_CHK_Kitche_2 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5150 65535 0]夷Qu姻 est茨s haciendo?[n]No estropees nada que sea[n]para la clientela, 夷entendido?[n][w][e]

[msg MND_E22810100_CHK_Kitche_2]
[s][vp 1 0 0 0 0 0]Hay una olla de curry enorme aqu胤.[n]Parece ser la especialidad[n]de la casa.[n][w][e]

[msg MND_COMMON_CHK_KitchenCu]
[s][vp 1 0 0 0 0 0]Hay una olla de curry enorme aqu胤.[n]Me pregunto si se est茨 preparando[n]para servirse ma隠ana...[n][w][e]

[msg MND_E22810100_CrossWord_]
[s][vp 1 0 0 0 0 0]Deber胤a ir a preparar la olla.[n][w][e]

[msg MND_COMMON_CrossWord_000]
[s][vp 1 0 0 0 0 0]Esta mesa tiene pinta[n]de haber sido pulida con mimo.[n][w][e]

[msg MSG_GOTO_OUT_NG_PLAY_OK [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Anda, no salgas ahora.[n]Date prisa y vete arriba[n]a dormir de una santa vez.[n][w][e]

[msg MSG_GOTO_OUT_NG_0416 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Eh, 夷ad吋nde te crees que vas?[n]夷No te he dicho ya[n]que vayas arriba?[n][w][e]

[msg fev0410_05_STEP_mes01]
[s][vp 1 0 0 0 0 0]Deber胤a coger el tel姻fono.[n][w][e]

[msg fev0410_05_STEP_mes02]
[s][vp 1 0 0 0 0 0]Puede que sea buena idea hacer[n]lo que me ha pedido.[n][w][e]

[msg fev0410_05_STEP_mes03]
[s][vp 1 0 0 0 0 0]Deber胤a darle la vuelta[n]al cartel de la entrada.[n][w][e]

[msg fev0410_06_mes01 [Voz de hombre]]
[s][vp 8 0 1 1 65535 0]Eh, soy yo.[n][w][e]

[sel fev0410_06_Q01_SEL top]
[s]夷Qui姻n eres?[e]
[s]夷Es una broma telef吋nica?[e]

[msg fev0410_06_A_mes01 [Sojiro]]
[s][bup 0 103 602 0 1][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]No me digas que ya te has olvidado[n]de mi voz. Soy Sakura.[n][w][e]

[msg fev0410_06_B_mes01 [Sojiro]]
[s][bup 0 103 603 0 1][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]夷En serio te has olvidado ya[n]de mi voz? Soy Sakura.[n][w][e]

[msg fev0410_06_mes02 [Sojiro]]
[s][bup 0 103 600 0 1][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Ver茨s... He cerrado el Leblanc,[n]pero me he olvidado de girar[n]el cartel antes de irme.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Ser胤a una lata tener que volver[n]solo por eso. 夷Podr胤as hacerlo[n]por m胤?[n][w][e]

[sel fev0410_06_Q02_SEL top]
[s]Vale, entendido.[e]
[s]No me apetece.[e]
[s]夷Has llamado al tel姻fono p雨blico?[e]

[msg fev0410_06_A_mes02 [Sojiro]]
[s][bup 0 103 601 0 1][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Dudo que vayan clientes[n]a estas horas, aunque est姻[n]el cartel de abierto.[n][w][e]
[s][bup 0 103 600 0 1][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]Tengo que admitir que es un alivio.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]Por norma general, no suelo guardar[n]el n雨mero de un t胤o en mi tel姻fono.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]Me alegra que lo hayas cogido.[n][w][e]

[msg fev0410_06_B_mes02 [Sojiro]]
[s][bup 0 103 602 0 1][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Oye, tienes que entender[n]la situaci吋n en la que est茨s.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]S姻 que tienes mucho en qu姻 pensar,[n]pero deber胤as escucharme[n]mientras vivas bajo mi techo.[n][w][e]

[msg fev0410_06_C_mes02 [Sojiro]]
[s][bup 0 103 600 0 1][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Por norma general, no suelo guardar[n]el n雨mero de un t胤o en mi tel姻fono.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Pero bueno, me alegra que lo hayas cogido.[n][w][e]

[msg fev0410_06_mes03 [Sojiro]]
[s][bup 0 103 600 0 1][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]Bueno, dejo lo del [clr 2]cartel[clr 27] en tus manos.[n][w][e]

[msg fev0410_06_mes04]
[s][vp 1 0 0 0 0 0]Parece que quiere que le d姻[n]la vuelta al cartel de la puerta.[n][w][e]

[msg MSG_NIGHT_LEAVE_MASTER [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voy a salir.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si no vienes pronto a casa,[n]cerrar姻 el local.[n][w][e]

[msg MSG_E126101_009_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Un segundo, quieto.[n][w][e]

[msg MSG_E126101_010_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me iba a ir ahora.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Acu姻rdate de cerrar con llave[n]y apagar todas las luces, 夷eh?[n][w][e]

[msg MSG_E126101_011_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5019 65535 0]S胤, salgo ya.[n][w][e]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 2 1 5037 65535 0]Ya te lo he dicho,[n]trabaja a tiempo parcial...[n][w][e]

[msg MSG_E136101_001_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Oye, espera un momento.[n][w][e]

[msg MSG_E136101_002_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oye, yo ya me voy a casa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Voy a cerrar, as胤 que nada[n]de salir a husmear.[n][w][e]

[msg MSG_E14110100_200_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oye, 夷tienes un momento?[n][w][e]

[msg MSG_E14110100_201_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Sabes qu姻 les gusta[n]a las chicas j吋venes?[n][w][e]

[sel SEL_E14110100_202_00 top]
[s]夷C吋mo iba a saberlo?[e]
[s]夷Tienes una cita?[e]
[s]Viejo verde...[e]

[msg MSG_E14110100_203_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eso pensaba. No parece[n]que se te tiren encima las chicas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]A las mujeres les gustan[n]los hombres diligentes, recu姻rdalo.[n][w][e]

[msg MSG_E14110100_203_01 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oye, a las chicas no les gustan[n]los fisgones.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero t雨 qu姻 sabr茨s.[n]No tienes pinta de tener[n]mucho 姻xito con las f姻minas.[n][w][e]

[msg MSG_E14110100_203_02 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oye, no hay nada de malo en ello.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero t雨 qu姻 sabr茨s.[n]No tienes pinta de tener[n]mucho 姻xito con las f姻minas.[n][w][e]

[msg MSG_E14110100_204_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno... me voy a casa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Acu姻rdate de cerrar[n]todas las ventanas, 夷vale?[n][w][e]

[msg MSG_E146101_001_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5018 65535 0]Vale, yo me voy ya.[n][w][e]

[msg MSG_E146101_002_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Te recuerdo que no deber胤as[n]quedarte despierto hasta[n]muy tarde, 夷de acuerdo?[n][w][e]

[msg MSG_E146201_001_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5074 65535 0]Bueno, yo me voy ya.[n][w][e]

[msg MSG_E146201_002_00 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Enc茨rgate del resto[n]por aqu胤, 夷vale?[n][w][e]

[msg MSG_E152101_017_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Yo me voy ya.[n][w][e]

[msg MSG_E152101_017_01 [Sojiro]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No la l胤es, 夷de acuerdo? Si vas[n]a salir, qu姻date por el barrio.[n][w][e]

[msg MSG_E152101_GOOUT_00 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 2 1 5125 65535 0]No salgas cuando ni siquiera[n]tienes llave.[n][w][e]

[msg MSG_E152101_GOOUT_01 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me voy ya. Si vas a salir,[n]qu姻date por el barrio.[n][w][e]

[msg MSG_E401201_00 [Yusuke]]
[s][f 4 23 1 855 3 10 0 10][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡夷[f 4 2]?![n][w][e]

[msg MSG_E401201_01 [Ann]]
[s][f 4 23 1 853 14 10 13 10][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mmm... 夷Se acaba de ir pitando?[n][w][e]

[msg MSG_E401201_02 [Futaba]]
[s][f 4 23 1 850 110 10 0 10][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Argh, 斡se supone que est茨s muerto![n]斡No mola que vengas[n]a ense隠ar tu jeto![n][w][e]

[msg MSG_E401201_03 [Ryuji]]
[s][f 4 23 1 852 14 10 13 10][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Vamos a seguirlo![n][w][e]

[msg MSG_E401201_04 [Makoto]]
[s][f 4 23 1 851 14 10 13 10][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No es muy inteligente[n]que vayamos todos. Algunos[n]deber胤amos quedarnos esperando.[n][w][e]

[msg MSG_E401201_05 [Haru]]
[s][f 4 23 1 854 14 10 13 10][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Yo tambi姻n voy![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No te preocupes.[n]Te prometo que no har姻[n]ninguna idiotez.[n][w][e]

[msg MSG_E401201_06 [Morgana]]
[s][f 4 23 1 857 3 10 0 10][bup 0 3 0 0 0][f 4 10 0 0 0][vp 8 2 1 0 65535 0]Qu姻 se le va a hacer...[n]Voy con vosotros.  [n][w][e]
[s][f 4 10 0 0 0][vp 8 2 1 0 65535 0]Vale, 夷est茨is listos?[n][w][e]

[msg MND_C14_INIT_01_00]
[s]Ah胤 est茨 el tel姻fono p雨blico.[n][w][e]
[s]夷Llamo al servicio de sirvientas?[n][w][e]

[msg MND_C14_INIT_01_01]
[s]...[n][w][e]
[s]Sin embargo, no tengo suficiente[n][f 4 11 3][clr 26][f 4 12 3][clr 27]...[n][w][e]
[s]No creo que pueda llamar[n]desde el Leblanc a no ser[n]que tenga suficiente [f 4 11 3][clr 26][f 4 12 3][clr 27] para ser [clr 26][f 4 13 3 3][clr 27].[n][w][e]

[msg MND_C14_INIT_01_02]
[s]Creo que puedo llamar[n]cuando quiera mientras[n]tenga suficiente [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][w][e]

[msg MSG_C14_INIT_01_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]夷Pensando en llamar a una sirvienta?[n]Mira, si utilizas esto, 斡no saldr茨[n]en tu registro de llamadas![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lo hacemos por el bien de[n]los Ladrones Fantasma, 夷no...?[n][w][e]

[sel SEL_C14_INIT_01_00 top]
[s]Claro que s胤.[e]
[s]Quiz茨 en otro momento.[e]

[msg MND_C14_INIT_00_00]
[s]Ah胤 est茨 el tel姻fono p雨blico.[n][w][e]
[s]Probar姻 a llamar al n雨mero[n]del trabajo de Kawakami.[n][w][e]

[msg MSG_C14_INIT_00_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]夷Vas a llamar a Kawakami?[n][w][e]

[sel SEL_C14_INIT_00_02 top]
[s]Llamemos al servicio.[e]
[s]No, da igual.[e]

[msg MND_C14_INIT_NG_00]
[s]Ah胤 est茨 el tel姻fono p雨blico.[n][w][e]
[s]Hoy no puedo con mi alma,[n]as胤 que ya lo usar姻 otro d胤a.[n][w][e]

[msg MSG_C14_INIT_NG_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Pareces cansado.[n]Bueno, al fin y al cabo[n]hemos estado en el Metaverso.[n][w][e]
[s][f 4 10 65535 0 0]Puedes pedirle a Kawakami que haga[n]las tareas del hogar. 斡Decide qu姻[n]quieres que haga antes de llamarla![n][w][e]

[msg MSG_C14_INIT_NG_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Oye, ya le has pedido a Kawakami[n]que venga hoy.[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Si tienes alguna otra solicitud,[n]gu茨rdatela para otro momento.[n][w][e]

[msg MND_C14_INIT_NG_03]
[s]Ahora mismo, tengo cosas[n]m茨s importantes que hacer.[n]Ya llamar姻 otro d胤a.[n][w][e]

[msg MSG_C14_INIT_NG_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]夷No tienes nada mejor que hacer?[n]Ya llamar茨s en otro momento.[n][w][e]

[msg MSG_C14_INIT_NG_04 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Pareces cansado.[n]Bueno, al fin y al cabo[n]hemos estado en el Metaverso.[n][w][e]

[msg MSG_C14_PRECOOP_00_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Hola, al habla Becky...[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Ah, espera, si eres t雨.[n][w][e]
[s][f 4 10 65535 0 0]Vale, ser茨n 5000 yenes, tasas[n]incluidas. 夷Te parece bien?[n][w][e]

[sel SEL_C14_PRECOOP_00_01 top]
[s]Claro.[e]
[s]Otra vez ser茨.[e]

[msg MSG_C14_PRECOOP_00_02 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15153 65535 0]De acuerdo.[n][w][e]
[s][f 4 10 65535 0 0]Salgo ahora mismo.[n][w][e]

[msg MSG_C14_PRECOOP_00_03 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Mmm...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 15032 65535 0]Lo siento, me pillas en el trabajo...[n]Ll茨mame luego.[n][w][e]

[msg MSG_C14_PRECOOP_NG_00 [Voz de Kawakami]]
[s][vp 8 2 1 15091 65535 0]Lo siento, amo.[n]Estoy en mitad del descanso.[n][w][e]
[s]Solo puedo atenderte[n]como sirvienta por la noche.[n][w][e]
[s]斡Muy bien, estar姻 esperando[n]tu llamada![n][w][e]

[msg MSG_KAWAKAMI_SASOI_THROU [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15058 65535 0]Me ha sorprendido que me llamaras.[n][w][e]
[s][f 4 10 65535 0 0]Puede que no lo entiendas, pero[n]ayudarte a saltarte las clases[n]no es nada f茨cil.[n][w][e]
[s][f 4 10 65535 0 0]Puede que otro d胤a.[n][w][e]

[msg MSG_KAWAKAMI_SASOI_THROU_2 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15058 65535 0]Me ha sorprendido que me llamaras.[n][w][e]
[s][f 4 10 65535 0 0]Puede que no lo entiendas, pero[n]ayudarte a saltarte las clases[n]no es nada f茨cil.[n][w][e]
[s][f 4 10 65535 0 0]Puede que otro d胤a.[n][w][e]

[msg MSG_KAWAKAMI_SASOI_THROU_3 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15058 65535 0]Anda, pero si eres t雨.[n]夷En serio me est茨s llamando?[n][w][e]
[s][f 4 10 65535 0 0]Pensaba que estabas tan ocupado[n]que no pod胤as ni responderme[n]los mensajes.[n][w][e]

[msg MSG_KAWAKAMI_SASOI_THROU_4 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15058 65535 0]Anda, pero si eres t雨.[n]夷En serio me est茨s llamando?[n][w][e]
[s][f 4 10 65535 0 0]Pensaba que estabas tan ocupado[n]que no pod胤as ni responderme[n]los mensajes.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]斡Hola! Ahora mismo estoy calada[n]hasta los huesos y... Ah, eres t雨.[n][w][e]
[s][f 4 10 65535 0 0]Uf, odio la lluvia. Tarda much胤simo[n]en secarse la colada...[n][w][e]
[s][f 4 10 65535 0 0]Y tengo que secar la ropa[n]diez minutos m茨s que de costumbre. [n][w][e]

[msg MSG_C14_BEGIN_WEATHER_00_2 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Hola. Oh, [f 4 1].[n][w][e]
[s][f 4 10 65535 0 0]Uf, odio la lluvia. Tarda much胤simo[n]en secarse la colada...[n][w][e]
[s][f 4 10 65535 0 0]Y tengo que secar la ropa[n]diez minutos m茨s que de costumbre. [n][w][e]

[msg MSG_C14_BEGIN_WEATHER_01 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Hola, al habla Becky. Estoy[n]cubierta de... Ah, pero si eres t雨.[n][w][e]
[s][f 4 10 65535 0 0]夷No es raro que nieve en la ciudad?[n][w][e]
[s][f 4 10 65535 0 0]Por cierto, no ofrezco servicios[n]de quitanieves. Levantar peso[n]y esas cosas no es lo m胤o.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_01_2 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Hola. Oh, [f 4 1].[n][w][e]
[s][f 4 10 65535 0 0]夷No es raro que nieve en la ciudad?[n][w][e]
[s][f 4 10 65535 0 0]Por cierto, no ofrezco servicios[n]de quitanieves. Levantar peso[n]y esas cosas no es lo m胤o.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_02 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Hola, al habla Becky. Gracias[n]por llamar en este d胤a de llu...[n]Ah, espera, pero si eres t雨.[n][w][e]
[s][f 4 10 65535 0 0]Casi nadie llama cuando llueve...[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_02_2 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Hola. Oh, [f 4 1].[n][w][e]
[s][f 4 10 65535 0 0]Espero que deje de llover pronto.[n]La colada tarda mucho en secarse[n]y ya estoy bastante ocupada.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_03 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]斡Hola, aqu胤 Becky! Qu姻 miedo[n]da el tif... 斡夷Ah, eres t雨?![n][w][e]
[s][f 4 10 65535 0 0]A ver, que si me llamas, voy[n]aunque caigan chuzos de punta.[n]Es lo que tiene el trabajo.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_03_2 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Hola. Oh, [f 4 1].[n][w][e]
[s][f 4 10 65535 0 0]Menudo tif吋n, 夷eh?[n]A ver si acaba pronto...[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_04 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Hola, aqu胤 Bec...[n][w][e]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0]*estornudo* Oh, vaya, perd吋n.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Espera, 夷eres t雨? Uf, qu姻 alivio.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_04_2 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Holaaa! Ah, eres t雨[n], [f 4 1]...[n][w][e]
[s][bup 0 109 3 65535 1][f 4 10 65535 0 0]*estornudo* Oh, vaya, perd吋n.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_05 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Hola, soy Becky, la sirvienta[n]guerrillera. El tipo de trabajos[n]que acepto depend... Ah, eres t雨.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_05_2 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]夷Hola? Oh, [f 4 1].[n]Est茨 lloviendo a c茨ntaros.[n]夷T雨 qu姻 tal? No te resfr胤es, 夷eh?[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_06 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]斡Al habla Becky! Hace un[n]calor asfixiante, pero deja[n]que me ocupe de... Ah, eres t雨.[n][w][e]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0]Pero qu姻 calooooooor.[n]En tu casa no hay aire[n]acondicionado, 夷verdad?[n][w][e]
[s][f 4 10 65535 0 0]Ya me las apa隠ar姻 si[n]solicitas mis servicios.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_06_2 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]
[s][bup 0 109 3 65535 1][f 4 10 65535 0 0]Pero qu姻 calooooooor.[n]En tu casa no hay aire[n]acondicionado, 夷verdad?[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_07 [Kawakami]]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Hola, aqu胤 Bec...*tos* *tos*[n][w][e]
[s][f 4 10 65535 0 0]Perd吋name, amo... Ah, eres t雨.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Ay, estaba picoteando[n]y me he atragantado. No te asustes,[n]que no tengo la gripe ni nada.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_07_2 [Kawakami]]
[s][bup 0 109 3 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Oh, vaya, pero si eres[n]t雨, [f 4 1].[n]*tos* *tos*[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Ay, estaba picoteando[n]y me he atragantado. No te asustes,[n]que no tengo la gripe ni nada.[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_08 [Kawakami]]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]斡Holaaa! Becky te puede hacer[n]entrar en calor en esta g姻lida[n]noche... Ah, si eres t雨.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Tu casa no est茨 muy bien aislada.[n]No te resfr胤es, 夷vale?[n][w][e]

[msg MSG_C14_BEGIN_WEATHER_08_2 [Kawakami]]
[s][bup 0 109 3 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]Hola... 斡Ah, [f 4 1]![n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Espero que est姻s bien abrigado,[n]que hoy hace mucho fr胤o.[n]斡No te resfr胤es![n][w][e]

[msg MSG_C14_BEGIN_TIME_01 [Kawakami]]
[s][bup 0 109 600 65535 1]斡Hola! Ah, vaya, eres t雨.[n][w][e]

[msg MSG_C14_BEGIN_TIME_01_01 [Kawakami]]
[s][bup 0 109 0 65535 1]斡Hola! Ah, vaya, eres t雨.[n][w][e]

[msg MSG_C14_BEGIN_TIME_02 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]斡Hola! Ah, vaya, eres t雨.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]夷Has estudiado algo? No vayas[n]a holgazanear solo por haber[n]terminado los ex茨menes, 夷eh?[n][w][e]

[msg MSG_C14_BEGIN_TIME_02_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]夷Has estudiado algo? No vayas[n]a holgazanear solo por haber[n]terminado los ex茨menes, 夷eh?[n][w][e]

[msg MSG_C14_BEGIN_TIME_03 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]斡Gracias por llamar![n]Estoy a tu... Anda, si eres t雨.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Me han dicho que Shibuya se ha[n]vuelto m茨s peligroso 雨ltimamente.[n][w][e]
[s][f 4 10 65535 0 0]S姻 que pasas[n]por la zona para ir a clase,[n]as胤 que no te distraigas, 夷vale?[n][w][e]

[msg MSG_C14_BEGIN_TIME_03_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Me han dicho que Shibuya se ha[n]vuelto m茨s peligroso 雨ltimamente.[n][w][e]
[s][f 4 10 65535 0 0]S姻 que pasas[n]por la zona para ir a clase,[n]as胤 que no te distraigas, 夷vale?[n][w][e]

[msg MSG_C14_BEGIN_TIME_04 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]斡Hola! Ah, vaya, eres t雨.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Es verano, pero no te descentres.[n]A雨n vas al instituto, as胤 que[n]nada de salir a jugar por la noche.[n][w][e]
[s][f 4 10 65535 0 0]夷Esto se considera jugar por la[n]noche? 夷O es peor? Bueno,[n]como superviso yo, no pasa nada.[n][w][e]

[msg MSG_C14_BEGIN_TIME_04_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Es verano, pero no te descentres.[n]A雨n vas al instituto, as胤 que[n]nada de salir a jugar por la noche.[n][w][e]
[s][f 4 10 65535 0 0]夷Esto se considera jugar por la[n]noche? 夷O es peor? Bueno,[n]como superviso yo, no pasa nada.[n][w][e]

[msg MSG_C14_BEGIN_TIME_05 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15089 65535 0]Hola, amo.[n]斡Soy Becky![n]Anda, eres t雨.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Por cierto, 夷vas a poner[n]aire acondicionado en tu casa?[n][w][e]
[s][f 4 10 65535 0 0]Los atuendos de sirvienta dan[n]mucho calor en verano y mucho fr胤o[n]en invierno. No son nada pr茨cticos.[n][w][e]

[msg MSG_C14_BEGIN_TIME_05_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Aunque de d胤a hace calor,[n]por la noche va a refrescar.[n]No te vayas a poner malo, 夷eh?[n][w][e]

[msg MSG_C14_BEGIN_TIME_06 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]斡Hola! Ah, vaya, eres t雨.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]夷Ya te has hecho a la vida[n]en la ciudad?[n][w][e]
[s][f 4 10 65535 0 0]Has estado aqu胤 m茨s de seis[n]meses, 夷no? El tiempo pasa[n]cada vez m茨s r茨pido...[n][w][e]

[msg MSG_C14_BEGIN_TIME_06_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]夷Ya te has hecho a la vida[n]en la ciudad?[n][w][e]
[s][f 4 10 65535 0 0]Has estado aqu胤 m茨s de seis[n]meses, 夷no? El tiempo pasa[n]cada vez m茨s r茨pido...[n][w][e]

[msg MSG_C14_BEGIN_TIME_07 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]斡Hola! Estoy a tu disposici吋n, amo...[n]Ah, eres t雨.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Todos se piensan que has[n]vuelto ya a tu ciudad, as胤 que[n]ve con cuidado, 夷quieres?[n][w][e]
[s][f 4 10 65535 0 0]Vendr姻 cada vez que me lo pidas.[n][w][e]

[msg MSG_C14_BEGIN_TIME_07_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Todos se piensan que has[n]vuelto ya a tu ciudad, as胤 que[n]ve con cuidado, 夷quieres?[n][w][e]
[s][f 4 10 65535 0 0]Vendr姻 cada vez que me lo pidas.[n][w][e]

[msg MSG_C14_BEGIN_TIME_08 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15089 65535 0]斡Hola, al habla Becky![n]Si me lo pides, ir姻 all胤 ense...[n]Ah, eres t雨.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Vendr姻 cuando quieras, no importa[n]si es Navidad o A隠o Nuevo.[n][w][e]

[msg MSG_C14_BEGIN_TIME_08_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Vendr姻 cuando quieras, no importa[n]si es Navidad o A隠o Nuevo.[n][w][e]

[msg MSG_C14_BEGIN_TIME_09 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15089 65535 0]斡Holaaaa! 斡Soy Becky y estoy[n]a tu disposici吋n, amo! Ah, eres t雨.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Tengo m茨s clientes[n]desde que empez吋 el a隠o.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]El encargado est茨 contento,[n]pero a m胤 se me hace raro.[n][w][e]

[msg MSG_C14_BEGIN_TIME_09_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]夷Hola? 夷[f 4 1]?[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]夷No te parece que todo el mundo[n]est茨 m茨s feliz de repente? Incluso[n]en el instituto. Es muy extra隠o...[n][w][e]
[s]Pero cuando pregunto,[n]me dicen que est茨n como siempre.[n]Ser茨n imaginaciones m胤as.[n][w][e]

[msg MSG_C14_BEGIN_SECOMD_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]斡Hola! Ah, vaya, eres t雨.[n][w][e]

[msg MSG_C14_BEGIN_SECOMD_00_ [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]

[msg MSG_C14_BIGEN_NG_00_02 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15091 65535 0]Oh, 夷eres t雨?[n][w][e]
[s][f 4 10 65535 0 0]Trabajo [clr 2]viernes y s茨bados por[n]la tarde[clr 27], av胤same entonces.[n][w][e]
[s][vp 8 2 1 15053 65535 0][f 4 10 65535 0 0]Te avisar姻 si trabajo[n]otros d胤as quitando[n]viernes o s茨bados. 斡Nos vemos![n][w][e]

[msg MSG_C14_BIGEN_NG_00 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15091 65535 0]Oh, 夷eres t雨?[n][w][e]
[s][f 4 10 65535 0 0]Trabajo [clr 2]viernes y s茨bados por[n]la tarde[clr 27], av胤same entonces.[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Bueno, si solo son tareas del[n]hogar, podr胤a ir y acabarlas[n]en un momento.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 15053 65535 0][f 4 10 65535 0 0]Pero te avisar姻 si trabajo[n]otros d胤as aparte de[n]viernes o s茨bados. 斡Nos vemos![n][w][e]

[msg MSG_C14_BIGEN_NG_00_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]
[s][f 4 10 65535 0 0]Estoy con unos informes. 夷Podr胤as[n]solicitar mis servicios [clr 2]los[n]viernes o s茨bados por la tarde[clr 27]?[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Vale, si solo son tareas del[n]hogar, puedo ir y acabarlas[n]en un momento.[n][w][e]
[s][vp 8 2 1 15053 65535 0][f 4 10 65535 0 0]En cualquier caso, te avisar姻[n]si tengo tiempo libre aparte[n]de los fines de semana. Nos vemos.[n][w][e]

[msg MSG_C14_BIGEN_NG_02_02 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15091 65535 0]Lo siento mucho, amo.[n]Hoy no tengo ni un hueco libre.[n][w][e]
[s]Vuelve a solicitar mis servicios[n]en otra ocasi吋n, 夷vale?[n]Hasta la pr吋xima.[n][w][e]

[msg MSG_C14_BIGEN_NG_02 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15091 65535 0]Lo siento mucho, amo.[n]Hoy no tengo ni un hueco libre.[n][w][e]
[s][f 4 10 65535 0 0]Pero si solo son tareas del hogar,[n]puedo ir y acabarlas en un momento...[n][w][e]
[s][f 4 10 65535 0 0]Si necesitas alguna otra cosa,[n]av胤same en otra ocasi吋n.[n]斡Que pases un buen d胤a![n][w][e]

[msg MSG_C14_BIGEN_NG_02_01 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]斡Hola! Ah, espera, eres[n]t雨, [f 4 1].[n][w][e]
[s][f 4 10 65535 0 0]Pero si solo son tareas del hogar,[n]puedo ir y acabarlas en un momento...[n][w][e]
[s][f 4 10 65535 0 0]Si necesitas alguna otra cosa,[n]av胤same en otra ocasi吋n.[n]斡Que pases un buen d胤a![n][w][e]

[msg MSG_C14_BIGEN_NG_01 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15091 65535 0]夷T雨 otra vez? Perdona, estoy[n]bastante ocupada ahora mismo.[n][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0]Si tantas tareas tienes para m胤,[n]reserva los [clr 2]viernes y los s茨bados[n]por la tarde[clr 27]. 斡Nos vemos![n][w][e]

[msg MSG_C14_BIGEN_NG_01_01 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15004 65535 0]夷T雨 otra vez? Perdona, estoy[n]bastante ocupada ahora mismo.[n][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0]Si tantas tareas tienes para m胤,[n]reserva los [clr 2]viernes y los s茨bados[n]por la tarde[clr 27]. 斡Nos vemos![n][w][e]

[msg MSG_C14_CORP_00_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Puedo hacerte las tareas del hogar[n]siempre que est姻s dispuesto[n]a pagar 5000 yenes.[n][w][e]

[msg MSG_C14_CORP_10_00 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Gracias por llamar.[n][w][e]
[s][f 4 10 65535 0 0]夷Hay algo que pueda hacer por ti?[n][w][e]

[msg MSG_C14_CORP_10_01 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Gracias por llamar.[n][w][e]
[s][f 4 10 65535 0 0]夷Te importa si me paso[n]hoy por tu casa?[n][w][e]

[msg MSG_C14_SPOT_01_00 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15019 65535 0][f 4 10 65535 0 0]夷Y si vamos a alguna parte[n]como actividad extraescolar?[n][w][e]
[s][f 4 10 65535 0 0]Dejar姻 que decidas d吋nde ir.[n]T吋matelo como tu primera tarea.[n][w][e]
[s][f 4 10 65535 0 0]Si hay alguna cosa con la que[n]te pueda ayudar hoy, ir姻 a tu casa[n]encantada. 夷Qu姻 te parece?[n][w][e]

[msg MSG_C14_SPOT_02_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15090 65535 0]Quiero salir y comprar[n]algo de comer para celebrar[n]que me han dado el alta.[n][w][e]
[s][f 4 10 65535 0 0]斡Alg雨n sitio con alcohol y comida[n]rica que no cueste un ri隠吋n![n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]夷A qui姻n quiero enga隠ar?[n]No se lo puedo pedir a un cr胤o.[n][w][e]
[s][f 4 10 65535 0 0]El precio es el de siempre,[n]unos 5000 yenes.[n][w][e]

[msg MSG_C14_SPOT_03_00 [Kawakami]]
[s][bup 0 109 6 65535 1][f 4 10 65535 0 0]Ahora que estamos saliendo, me[n]gustar胤a ir a alg雨n sitio especial...[n][w][e]
[s][f 4 10 65535 0 0]Ya sabes: bonitas vistas nocturnas,[n]t雨 y yo solos...[n][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15085 65535 0]Ja, ja, ja, 夷me he pasado?[n]En fin, ir姻 para all茨[n]si necesitas ayuda con algo.[n][w][e]

[msg MSG_C14_SPOT_04_00 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15090 65535 0]En el hospital me han dicho que[n]procure ingerir comida con[n]muchos nutrientes.[n][w][e]
[s][f 4 10 65535 0 0]No tengo mucho dinero,[n]pero quiz茨 pueda ir a uno[n]de esos bufet especiales.[n][w][e]
[s][f 4 10 65535 0 0]Bueno, ya me ocupar姻 de eso luego.[n]Puedo pasarme por tu casa[n]si necesitas ayuda con algo.[n][w][e]

[msg MSG_C14_SPOT_05_00 [Kawakami]]
[s][bup 0 109 6 65535 1][f 4 10 65535 0 0][vp 8 2 1 15165 65535 0]Quiero ir a tu casa, pero no como[n]tu sirvienta, sino como tu novia...[n]Bah, no es nada.[n]夷Puedo ayudarte en otra cosa?[n][w][e]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Bah, no es nada.[n]夷Puedo ayudarte en otra cosa?[n][w][e]

[msg MSG_C14_SPOT_06_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15002 65535 0]Estoy intentando aprender[n]sobre subculturas, pero[n]me he quedado atascada.[n][w][e]
[s][f 4 10 65535 0 0]夷Alguna idea de d吋nde puedo[n]investigar sobre ese tema?[n][w][e]
[s][f 4 10 65535 0 0]Ya he estado en Akihabara,[n]as胤 que cualquier otro sitio[n]me va bien.[n][w][e]

[msg MSG_C14_CORP_01_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]斡Te va a costar 5000 yenes,[n]pero me esforzar姻 al m茨ximo[n]en hacer un buen trabajo![n][w][e]

[msg MSG_C14_CORP_02_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Esto, amo... 夷Tienes hambre?[n][w][e]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]斡Ofrecemos servicios especiales[n]como 或Sirvienta cocinera位[n]y 或Cocina con una sirvienta位! [clr 2][f 1 9 0][clr 27][n][w][e]
[s][f 4 10 65535 0 0]La tasa de servicio va incluida...[n]斡Son solo 5000 yenes! 斡Una ganga![n][w][e]

[msg MSG_C14_CORP_03_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]斡Te ofrezco mis servicios por[n]5000 yenes, tasas incluidas![n][w][e]
[s][f 4 10 65535 0 0]Hoy vas a solicitar mis servicios,[n]夷verdad...? 夷Verdad?[n][w][e]

[msg MSG_C14_CORP_04_00 [Kawakami]]
[s][bup 0 109 602 65535 1][f 4 10 65535 0 0]Entiendes lo que te dije[n]la 雨ltima vez, 夷no...? 夷Aun as胤[n]quieres solicitar mis servicios?[n][w][e]

[msg MSG_C14_CORP_05_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]Tengo algo especial en el men雨[n]solo para mi amo. [clr 2][f 1 9 0][clr 27][n][w][e]
[s][f 4 10 65535 0 0]斡Y solo cuesta 5000 yenes![n][w][e]

[msg MSG_C14_CORP_06_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Kawakami no contesta.[n]Prueba a llamarla directamente.[n][w][e]

[msg MSG_C14_CORP_06_00 [Voz de mujer desconocida]]
[s]Hola... Oh, 夷no ser茨s t雨[n][f 4 1]?[n][w][e]

[msg MSG_C14_CORP_07_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]夷Sin ganas de limpiar tu cuarto?[n]夷Necesitas alguien que te cocine?[n]斡Ofrezco toda clase de servicios![n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Aunque, esto... hay algo de[n]lo que tengo que hablarte.[n]夷Vas a solicitar mis servicios?[n][w][e]

[msg MSG_C14_CORP_08_00 [Voz de Kawakami]]
[s][vp 8 2 1 15002 65535 0]斡Hola, soy Becky![n]Estoy tom茨ndome un descanso.[n][w][e]
[s]斡Espero que vuelvas[n]a llamar pronto![n][w][e]

[msg MSG_C14_CORP_08_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Parece que Kawakami hoy no[n]est茨 disponible. 夷Ser茨[n]verdad que lo va a dejar?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Seguramente te seguir茨[n]haciendo las tareas del hogar.[n]Un trato es un trato, 夷no?[n][w][e]

[msg MND_C14_CORP_08_02]
[s]Kawakami no est茨 en la tienda,[n]pero puedo pedirle que cumpla[n]su parte del trato.[n][w][e]
[s]Ya tengo los nombres del matrimonio[n]Takase. Deber胤a ir a Mementos[n]y despertar sus corazones.[n][w][e]

[msg MSG_C14_CORP_08_03 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15019 65535 0]斡Escucha![n]Ha ocurrido algo incre胤ble...[n][w][e]
[s][f 4 10 65535 0 0]Todav胤a no me lo creo.[n]No s姻 por d吋nde empezar...[n][w][e]
[s][f 4 10 65535 0 0]Y hay otras cosas que me gustar胤a[n]comentarte. 夷Vas a solicitar hoy[n]mis servicios?[n][w][e]

[msg MSG_C14_CORP_09_00 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15006 65535 0]斡Qu姻 sincronizaci吋n! Yo tambi姻n[n]quiero hablarte de algo.[n][w][e]
[s][f 4 10 65535 0 0]Pero no como sirvienta, sino[n]como profesora. 夷Te importa[n]si me paso luego por el Leblanc?[n][w][e]

[msg MSG_C14_CORP_09_01 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]Te agradezco que hayas llamado.[n][w][e]
[s][vp 8 2 1 15193 65535 0][f 4 10 65535 0 0]Yo tambi姻n quiero hablarte de algo...[n][w][e]
[s][f 4 10 65535 0 0]Como sirvienta o como[n]profesora, lo mismo da.[n]夷Puedo pasarme ahora?[n][w][e]

[msg MND_COOP_DOUZOKUSEI]
[s]Gracias a la Persona del arcano[n][var 2], [clr 1][var 5][clr 27],[n]puedo estrechar lazos con Kawakami.[n][w][e]

[msg MND_COOP_RANKUP_OK]
[s]Siento que mi v胤nculo con Kawakami[n]se fortalecer茨 pronto.[n][w][e]

[msg MND_COOP_RANKUP_NG]
[s]No creo que mi v胤nculo con Kawakami[n]se vaya a fortalecer a雨n.[n][w][e]

[msg MND_COOP_RANK_MAX_00]
[s]Tengo un v胤nculo s吋lido[n]con Kawakami.[n][w][e]

[msg MND_COOP_RANK_MAX_01]
[s]Tengo un v胤nculo especial[n]con Kawakami.[n][w][e]

[msg MSG_COOP_CHECK_NIGHT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Te va a costar 5000 yenes.[n]夷Vas a llamar a Kawakami?[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Te va a costar 5000 yenes.[n]夷Vas a llamar a Kawakami?[n][w][e]

[msg MSG_COOP_CHECK_RANK_6 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]La voz del tel姻fono[n]no era la de Kawakami.[n]夷Y si pides m茨s detalles?[n][w][e]

[msg MSG_COOP_CHECK_RANK_10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]夷Vas a decirle[n]a Kawakami que venga?[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU_10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]夷Vas a decirle[n]a Kawakami que venga?[n][w][e]

[sel SEL_COOP_CHECK top]
[s]Pedirle que venga[e]
[s]Comprobar v胤nculo con Kawakami[e]
[s]Rechazar[e]

[sel SEL_COOP_CHECK_06 top]
[s]夷Qui姻n llama?[e]
[s]Comprobar v胤nculo con Kawakami[e]
[s]Se equivoca de n雨mero[e]

[msg MSG_MONEY_NG_MORGANA [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Oye, que solo tienes [var 1] yenes.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Con eso no te llega[n]para pagar a Kawakami.[n][w][e]

[msg MSG_MONEY_NG [Kawakami]]
[s][bup 0 109 604 65535 1][f 4 10 65535 0 0][vp 8 2 1 15039 65535 0]斡夷Es que andas corto de dinero?![n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]Bueno, ll茨mame cuando ahorres[n]un poco m茨s. Hasta luego.[n][w][e]

[msg MSG_C14_YES_01_00 [Kawakami]]
[s][bup 0 109 604 65535 1][f 4 10 65535 0 0][vp 8 2 1 15040 65535 0]斡夷Qu姻?! 斡夷De verdad vas a[n]solicitar mis servicios?![n][w][e]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]Bueno, pues voy ahora mismo...[n][w][e]
[s][f 4 10 65535 0 0]Estar胤a bien que limpiaras[n]un poco antes de que vaya.[n]斡Me facilitar茨s mucho la faena! [clr 2][f 1 9 0][clr 27][n][w][e]

[msg MSG_C14_YES_02_00 [Kawakami]]
[s][bup 0 109 604 65535 1][f 4 10 65535 0 0][vp 8 2 1 15040 65535 0]斡夷Qu姻?! 夷En serio?[n][w][e]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0]O-o sea, que muchas gracias por[n]solicitar mis servicios.[n][w][e]
[s][f 4 10 65535 0 0]斡Ya voy, amo! 斡Espero[n]que hoy tengas mucha hambre![n][w][e]

[msg MSG_C14_YES_03_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15030 65535 0]斡Bieeeen! 斡Te quiero, amo![clr 2][f 1 9 0][clr 27][n][w][e]
[s][f 4 10 65535 0 0]斡Ir姻 ahora mismo![n][w][e]

[msg MSG_C14_YES_04_00 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0][vp 8 2 1 15066 65535 0]Est茨 bien... Supongo que tendremos[n]que hablar de ello en condiciones.[n][w][e]
[s][f 4 10 65535 0 0]T雨 esp姻rame.[n][w][e]

[msg MSG_C14_YES_05_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15030 65535 0]斡Gracias por solicitar siempre[n]mis servicios![n][w][e]
[s][f 4 10 65535 0 0]斡Esp姻rame, que llegar姻 en nada![n][w][e]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0]*tos* *tos*[n][w][e]

[msg MSG_C14_YES_06_00 [Enfermera]]
[s]Al habla la enfermera jefa del[n]hospital Aoyama. Hablo[n]en nombre de la se隠ora Kawakami.[n][w][e]
[s]Kawakami se ha desmayado[n]y la han ingresado.[n][w][e]
[s]夷Conoce la direcci吋n del hospital?[n]El n雨mero de habitaci吋n es...[n][w][e]

[msg MSG_C14_YES_06_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Esto no pinta bien.[n]斡Vamos inmediatamente![n][w][e]

[msg MSG_C14_YES_07_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15060 65535 0]斡Salgo ahora mismo![n]斡Esp姻rame, amo![n][w][e]

[msg MSG_C14_YES_08_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15031 65535 0]Ya, supongo que tienes raz吋n...[n][w][e]
[s][f 4 10 65535 0 0]Voy para all茨.[n][w][e]

[msg MSG_C14_YES_09_00 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15087 65535 0]Voy ahora mismo,[n]t雨 esp姻rame.[n][w][e]

[msg MSG_C14_YES_09_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15164 65535 0]Vale, voy para all茨 ahora mismo.[n][w][e]

[msg MSG_C14_YES_00_00 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15059 65535 0]Acabo de comprar en la tienda y voy[n]para all茨. Mientras tanto,[n]ve recogiendo tu habitaci吋n.[clr 2][f 1 9 0][clr 27][n][w][e]

[msg MSG_C14_YES_10_00 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15087 65535 0]Vale, voy para all茨 ahora mismo.[n][w][e]

[msg MSG_C14_YES_10_01 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15164 65535 0]Vale. Esp姻rame, que ya voy.[n][w][e]

[msg MND_C14_SPOT_01_01]
[s]Igual deber胤a invitarla[n]al museo de arte.[n][w][e]

[sel SEL_C14_SPOT_01_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C14_SPOT_01_03 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0]夷El museo de arte de Ueno?[n]Podr胤a ser educativo.[n][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 2 1 15051 65535 0]Espero que no haya cerrado ya.[n]Vamos a mirar.[n][w][e]

[msg MND_C14_SPOT_02_01]
[s]Quiz茨 deber胤a proponerle ir[n]a comer monjayaki conmigo.[n][w][e]

[sel SEL_C14_SPOT_02_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C14_SPOT_02_03 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15045 65535 0]斡Buena idea![n]En Tsukushima hacen[n]el mejor monjayaki.[n][w][e]
[s][f 4 10 65535 0 0]斡Quedamos en la estaci吋n![n][w][e]
[s][f 4 10 65535 0 0]Pero t雨 no puedes beber alcohol.[n]夷Vale, amo?[n][w][e]

[msg MND_C14_SPOT_03_01]
[s]Quiz茨 deber胤a proponerle ir a[n]montarnos en la noria de Odaiba.[n][w][e]

[sel SEL_C14_SPOT_03_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C14_SPOT_03_03 [Kawakami]]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0]Vale, am... Espera.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 15173 65535 0]Gracias, [f 4 1].[n]Montar en la noria con el chico al[n]que amo es un sue隠o hecho realidad.[n][w][e]

[msg MND_C14_SPOT_04_01]
[s]Quiz茨 deber胤a proponerle ir[n]al bufet Wilton conmigo.[n][w][e]

[sel SEL_C14_SPOT_04_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C14_SPOT_04_03 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15178 65535 0]Oh, qu姻 paladar tan exigente.[n]Pero es un poco caro...[n][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0]De acuerdo, d姻jaselo a tu profe.[n]Nos vemos luego en Shibuya.[n][w][e]

[msg MND_C14_SPOT_05_01]
[s]Como es mi novia, quiz茨 deber胤a proponerle[n]venir a mi habitaci吋n.[n][w][e]

[sel SEL_C14_SPOT_05_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C14_SPOT_05_03 [Kawakami]]
[s][bup 0 109 6 65535 1][f 4 10 65535 0 0]Esto, claro...[n]S-s胤...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 15088 65535 0]He subido muchas veces[n]a tu habitaci吋n. 夷Por qu姻[n]me pongo tan nerviosa...?[n][w][e]

[msg MND_C14_SPOT_06_01]
[s]Quiz茨 deber胤a proponerle ir[n]a Nakano Broadway conmigo.[n][w][e]

[sel SEL_C14_SPOT_06_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C14_SPOT_06_03 [Kawakami]]
[s][bup 0 109 601 65535 1][f 4 10 65535 0 0][vp 8 2 1 15045 65535 0]斡Ah, Nakano![n]斡Solo lo conozco de o胤das![n][w][e]
[s][f 4 10 65535 0 0]斡Vamos a echar un vistazo[n]ahora mismo! Yo te sigo, amo.[n][w][e]

[msg MSG_C14_COOP_CANCEL_00 [Kawakami]]
[s][bup 0 109 603 65535 1][f 4 10 65535 0 0][vp 8 2 1 15028 65535 0]*suspiro* Vale. Supongo que solo[n]tengo que llamar a la gente[n]y ver si a alguien le interesa.[n][w][e]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]M茨s vale que sigas[n]estudiando mucho.[n][w][e]

[msg MSG_C14_COOP_CANCEL_04 [Kawakami]]
[s][bup 0 109 600 65535 1][f 4 10 65535 0 0]S胤, eso ser胤a lo m茨s inteligente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 15127 65535 0]Espero que te tomes las clases[n]en serio a partir de ahora.[n][w][e]

[msg MSG_C14_COOP_CANCEL_06 [Enfermera]]
[s]夷Qu姻? Pensaba que erais familia.[n]Perd吋n por el malentendido.[n][w][e]

[msg MSG_C14_COOP_CANCEL_09 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15054 65535 0]M茨s te vale hincar los codos en casa.[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Ya puedes ir a [clr 1]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Ya puedes ir a [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Ya puedes ir a [clr 2]Akihabara[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste Akihabara[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Parque Inokashira[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el Parque[n]Inokashira para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el ramen[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Parque Seaside de Odaiba[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste este tipo[n]de parques para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Museo Ueno[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le gusten los museos[n]de arte para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el monjayaki[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]calle Takenoko de Harajuku[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente a[n]la que le guste la calle Takenoko[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Chinatown de Motomachi[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste Chinatown[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Destinyland de Maihama[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste Destinyland[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]Puedes invitar a gente a la que le[n]guste la Skytree o la calle[n]Nakamise para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Planetario de Ikebukuro[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el planetario[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Santuario Meiji[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el Santuario[n]Meiji para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir por tu cuenta[n]para venerarlo.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Dome Town de Suidobashi[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste Dome Town[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Hotel Wilton de Shibuya[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el Hotel Wilton[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]restaurante de sushi de Ginza[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el sushi caro[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Tienes informaci吋n sobre un nuevo[n]punto de encuentro: [clr 2]La ciudad[n]de los libros de Jinbocho[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le gusten las librer胤as de[n]segunda mano para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir por tu cuenta[n]a comprar.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Estanque Ichigaya[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste pescar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir[n]por tu cuenta para ver[n]qu姻 tal se te da pescar.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Acuario de Shinagawa[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el acuario[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]zona comercial de Nakano[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste la zona comercial[n]para que vaya contigo.[n][w][e]

[msg MND_C14_MASSAGE_00_00]
[s]Ah胤 est茨 el tel姻fono p雨blico.[n][w][e]
[s]Estoy que no puedo m茨s.[n]Deber胤a pedirle a Kawakami[n]que me d姻 un masaje.[n][w][e]

[msg MSG_C14_MASSAGE_00_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Si tan cansado est茨s, 夷por qu姻[n]no le pides un masaje a Kawakami?[n][w][e]

[sel SEL_C14_MASSAGE_00_02 top]
[s]Quiero un masaje.[e]
[s]No, da igual.[e]

[msg MSG_C14_MASSAGE_00_03_00 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15100 65535 0]Oh, 夷pasa algo si llevo[n]mi atuendo de sirvienta?[n][w][e]
[s][f 4 10 65535 0 0]Es verdad que he dejado el[n]trabajo, pero es raro que una[n]profesora visite a un alumno.[n][w][e]
[s][f 4 10 65535 0 0]Sabes que no me pueden pillar.[n]Espero que no te importe que vista[n]as胤 cuando venga a ayudarte.[n][w][e]

[msg MSG_C14_MASSAGE_00_03 [Kawakami]]
[s][bup 0 109 0 65535 1][f 4 10 65535 0 0][vp 8 2 1 15040 65535 0]夷En serio quieres un masaje?[n][w][e]
[s][f 4 10 65535 0 0]Vaaaaale... pero que sepas que[n]entren姻 cuando trabajaba[n]con Victoria. Soy muy habilidosa.[n][w][e]
[s][f 4 10 65535 0 0]Vale, voy para all茨. Esp姻rame.[n][w][e]

[msg MND_C14_MASSAGE_00_04]
[s]De momento, paso.[n][w][e]

[msg MSG_C14_MASSAGE_00_05 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1059 65535 0]夷No vas a llamarla?[n]Si se te pasa el cansancio,[n]puedes salir, 夷no?[n][w][e]

[msg MSG_C14_NG_MASSAGE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Ya lo pensaremos ma隠ana. Llamemos[n]a Kawakami en otro momento.[n][w][e]

