[msg D05_02_e341_084_ng_mes01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 no miramos[n]al otro lado de la puerta?[n][w][e]
[s]Quiero confirmar ad吋nde[n]lleva la cinta transportadora.[n][w][e]

[msg timer_block_mes03 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1029 65535 0]斡夷Ad吋nde vas?![n]斡Se nos acaba el tiempo![n][w][e]

[msg Dummy]
[s]...[n][w][e]

