[msg Dummy]
[s]...[n][w][e]

[msg D01_02_moru_navi_mes01 [Morgana]]
[s][bup 0 3 0 65535 0]斡Usemos la ruta de escape[n]de la 雨ltima vez![n][w][e]

[msg D01_02_moru_navi_mes02 [Morgana]]
[s][bup 0 3 0 65535 0]夷No te acuerdas? Salimos por[n]la sala que hay nada m茨s subir.[n][w][e]

[msg D01_02_moru_navi_mes03 [Morgana]]
[s][bup 0 3 0 65535 0]Muy bien, 斡aqu胤 es![n][w][e]
[s]斡Hala![n][w][e]

[msg D01_02_moru_navi_mes04 [Morgana]]
[s][bup 0 3 0 65535 0]斡夷Otra vez la patrulla?! Venga,[n]v茨monos antes de que nos vean.[n][w][e]

[msg D01_02_moru_navi_mes05 [Morgana]]
[s][bup 0 3 0 65535 0]El camino subterr茨neo[n]est茨 justo debajo.[n][w][e]

[msg D01_02_moru_navi_mes06 [Morgana]]
[s][bup 0 3 0 65535 0]斡Ya casi estamos![n][w][e]

[msg Dummy_09 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es una olla. No parece que haya[n]nada por aqu胤.[n][w][e]

[msg Dummy_10 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hostias, c吋mo quema! Me ha saltado[n]cera a la cara.[n][w][e]

[msg Dummy_11 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En este estante no hay m茨s que[n]utensilios de cocina.[n][w][e]

[msg Dummy_12 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bah, aqu胤 no hay nada.[n][w][e]

[msg Dummy_13 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uf... Este castillo[n]es feo de narices.[n][w][e]

[msg D01_02__ng_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, que no hay tiempo para hacer[n]el capullo. Vayamos tras 姻l.[n][w][e]

[msg D01_02__ng_mes02 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Que nos pillan, payaso![n]斡Venga, todos adentro! 斡R茨pido![n][w][e]

[msg D01_02_escape_ng_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mierda, hay un soldado[n]ah胤 plantado.[n][w][e]

[msg D01_02_escape_ng_mes02 [Morgana]]
[s][bup 0 3 0 65535 0]No hay m茨s formas de pasar.[n]Habr茨 que huir por esa puerta[n]antes de que nos descubran.[n][w][e]

