[msg D157_013_miniEV_01_mes01 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8020 65535 0]Hemos podido evitar[n]la puerta de cartas.[n][w][e]

[msg D157_013_miniEV_01_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡T胤o, lo del camino m茨s largo[n]es mentira! 斡夷D吋nde se ha metido[n]el cabr吋n de antes, a ver?![n][w][e]

[msg e382_235_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6194 65535 0]Eh, 夷no es esta la cosa con la que[n]jugaba la sombra?[n][w][e]

[msg e382_235_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Anda, ya tenemos una ruta[n]de escape! Podemos avanzar[n]sin volver a preocuparnos.[n][w][e]

[msg D06_mini_ev03_mes01 [Crupier]]
[s]Hola.[n][w][e]
[s]Le voy a explicar las reglas[n]de la batalla. No se preocupe,[n]son muy sencillitas.[n][w][e]

[msg D06_mini_ev03_mes02 [Crupier]]
[s][clr 2]Si su carta muestra un n雨mero mayor[n]que la de su oponente, gana[clr 27].[n][w][e]
[s][clr 2]Tres victorias[clr 27] otorgan [clr 2]un set[clr 27].[n][w][e]
[s]El primero en hacerse[n]con [clr 2]dos sets[clr 27], gana.[n][w][e]
[s]Si se alza con la victoria,[n]le [clr 2]duplicaremos[clr 27][n]las monedas que posea.[n][w][e]
[s]Eso es todo.[n]夷Ha entendido las reglas?[n][w][e]

[sel D06_mini_ev03_selA top]
[s]S胤.[e]
[s]Una vez m茨s.[e]

[msg D06_mini_ev03_selA_0_mes [Crupier]]
[s]Que comience el combate.[n][w][e]

[msg D06_mini_ev03_selA_1_mes [Crupier]]
[s]Muy bien, lo volver姻 a explicar.[n][w][e]

[msg D06_mini_ev03_mes03 [Crupier]]
[s]Ha ganado este set.[n][w][e]
[s]Es su primer set.[n]Uno m茨s y duplicaremos[n]las monedas que tenga.[n][w][e]

[msg D06_mini_ev03_mes4 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 夷qu姻...? Es pan comido.[n]斡Nosotros podemos![n][w][e]

[msg D06_mini_ev03_mes5 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ojal茨 siga siendo as胤 de sencillo.[n][w][e]

[msg D06_mini_ev03_mes6 [Crupier]]
[s]Es un cliente de los dif胤ciles.[n]Estoy en un buen l胤o.[n][w][e]
[s]Tengo que ponerme las pilas.[n][w][e]

[msg D06_mini_ev03_mes7 [Crupier]]
[s]Mmm, 夷eso es... un uno?[n][w][e]
[s]Entonces voy con esto.[n][w][e]

[msg D06_mini_ev03_mes8 [Crupier]]
[s]Mmm... 夷Qu姻 carta es esa?[n]No tengo ni idea.[n][w][e]
[s]Bueno, utilizar姻 esta.[n][w][e]

[msg D06_mini_ev03_mes9 [Crupier]]
[s]Oh, conque un tres, 夷eh?[n]Bueno, ah胤 va un cuatro.[n][w][e]

[msg D06_mini_ev03_mes10 [Crupier]]
[s]Tengo la sensaci吋n de que va[n]a sacar un n雨mero alto.[n]Usar姻 esta.[n][w][e]

[msg D06_mini_ev03_mes11 [Crupier]]
[s]No s姻 si podr姻 ganar esta vez.[n]Tendr姻 que probar.[n][w][e]

[msg D06_mini_ev03_mes12 [Crupier]]
[s]Vaya, ten胤a raz吋n, qu姻 suerte.[n][w][e]

[msg D06_mini_ev03_mes13 [Crupier]]
[s]He ganado, pero por poco.[n]Ha sido cuesti吋n de suerte.[n][w][e]

[msg D06_mini_ev03_mes14 [Crupier]]
[s]Oh, he elegido bien.[n]Parece que he ganado.[n][w][e]

[msg D06_mini_ev03_mes15 [Crupier]]
[s]Ay, tengo la mente despejada.[n]Qu姻 suerte.[n][w][e]

[msg D06_mini_ev03_mes16 [Crupier]]
[s]Parece que no pod胤a ganar esta vez.[n][w][e]

[msg D06_mini_ev03_mes17 [Crupier]]
[s]He ganado el set.[n][w][e]
[s]Estamos empatados a uno. Quien[n]se haga con el siguiente, gana.[n][w][e]

[msg D06_mini_ev03_mes18 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ser茨s cabr吋n! 斡Esto est茨 ama隠ado![n][w][e]

[msg D06_mini_ev03_mes19 [Crupier]]
[s]夷Ama隠ado? 夷C吋mo que ama隠ado?[n][w][e]

[msg D06_mini_ev03_mes20 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Sab胤as perfectamente qu姻[n]n雨meros 胤bamos a utilizar![n][w][e]

[msg D06_mini_ev03_mes21 [Crupier]]
[s]No s姻 de qu姻 est茨 hablando. Ha[n]sido casualidad que haya acertado.[n][w][e]

[msg D06_mini_ev03_mes22 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Conque casualidad, 夷eh?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Muy bien, pero tus trucos no te[n]servir茨n m茨s con nosotros.[n][w][e]

[msg D06_mini_ev03_mes23 [Crupier]]
[s]P-pero 斡夷c吋mo es posible?![n][w][e]

[msg D06_mini_ev03_mes24 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 ocurre? Hemos ganado, 夷no?[n][w][e]

[msg D06_mini_ev03_mes25 [Crupier]]
[s]Eso no es posible...[n][w][e]

[msg D06_mini_ev03_mes26 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Venga, sigamos.[n][w][e]

[msg D06_mini_ev03_mes27 [Crupier]]
[s]A-algo va mal...[n]斡Esto no puede ser cierto![n][w][e]
[s]斡Tienen que estar haciendo trampas![n][w][e]

[msg D06_mini_ev03_mes28 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira qui姻n fue a hablar.[n][w][e]

[msg D06_mini_ev03_mes29 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No estamos haciendo trampas. Y no[n]est茨 bien acusar en falso, 夷sabes?[n][w][e]

[msg D06_mini_ev03_mes30 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eso es! 斡Vamos,[n]sigamos con lo que est茨bamos![n][w][e]

[msg D06_mini_ev03_mes31 [Crupier]]
[s]Argh...[n][w][e]

[msg D06_13_TRUMP_END_mes01 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, hemos ganado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Cu茨l era el premio? Dijiste que[n]nos duplicar胤as las monedas[n]que tuvi姻ramos, 夷no?[n][w][e]

[msg D06_13_TRUMP_END_mes02 [Crupier]]
[s]S胤...[n][w][e]
[s]En recepci吋n se encargar茨n de eso.[n][w][e]

[msg D06_13_TRUMP_END_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Qu姻 est茨s maquinando?[n][w][e]

[msg D06_13_TRUMP_END_mes04 [Crupier]]
[s]夷No se lo dije?[n][w][e]
[s]Tendr茨n que sobrevivir a una pelea[n]contra uno de nuestros talentosos[n]empleados si quieren ganar.[n][w][e]

[msg D06_13_TRUMP_END_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esto es rid胤culo.[n][w][e]

[msg D06_13_TRUMP_END_mes06 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deber胤a ser f茨cil.[n][w][e]

[msg D06_13_TRUMP_END_mes7 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Vamos al l胤o![n][w][e]

[msg Battle_Number01 [Crupier]]
[s]Hola.[n][w][e]
[s]Le voy a explicar las reglas[n]de la batalla. No se preocupe,[n]son muy sencillitas.[n][w][e]
[s][clr 2]Si tu carta es m茨s alta[n]que la del oponente, ganas[clr 27].[n][w][e]
[s]Llegue [clr 2]primero a los tres sets[clr 27][n]y le [clr 2]duplicaremos[clr 27][n]las monedas que posea.[n][w][e]
[s]Muy bien, empecemos.[n][w][e]

[msg Battle_Number02 [Crupier]]
[s]A por la siguiente batalla.[n][w][e]

[msg Card_Battle_WIN [Crupier]]
[s]Muy bien, estoy impresionado.[n][w][e]

[msg Card_Battle_LOSE [Crupier]]
[s]Anda, he ganado yo.[n][w][e]

[msg Card_Battle_DRAW [Crupier]]
[s]Es un empate.[n][w][e]

[msg Card_Battle_WIN_SET [Crupier]]
[s]Maravilloso, ha ganado este set.[n][w][e]

[msg Card_Battle_LOSE_SET [Crupier]]
[s]Anda, a la primera. Qu姻 suerte.[n][w][e]

[msg Card_Battle_WIN_END [Crupier]]
[s]E-enhorabuena, ha ganado.[n][w][e]
[s]Le dar姻 sus monedas. Ah, y no[n]olvide su tarjeta de socio.[n][w][e]

[msg Card_Battle_LOSE_END [Crupier]]
[s]Por desgracia,[n]parece que he ganado.[n][w][e]
[s]Bueno, pues ser茨 penalizado, se隠or.[n][w][e]

[msg Card_Battle_Trick [Crupier]]
[s]Mm... Si tuviera que apostar, dir胤a[n]que ha colocado un [clr 2][var 0][clr 27].[n][w][e]
[s]En tal caso, quiz茨 deber胤a[n]ir con esta carta.[n][w][e]

[msg Card_Battle_LAST_01 [Crupier]]
[s]Mmm, estoy algo confundido.[n][w][e]
[s]Quiz茨s deber胤a usar... esta.[n][w][e]

[msg Card_Battle_LAST_02 [Ryuji]]
[s]Deja de joder ya...[n]斡Esto tiene que estar ama隠ado![n][w][e]

[msg Card_Battle_LAST02_01 [Crupier]]
[s]斡Ah, ya vuelvo a tener la mente[n]despejada! Usar姻 esta.[n][w][e]

[msg Card_Battle_LAST03_01 [Akechi]]
[s]Un momento, 夷seguro que no[n]est茨s haciendo trampas?[n][w][e]

[msg Card_Battle_LAST03_02 [Crupier]]
[s]斡Pues claro que no! 夷C吋mo podr胤a[n]hacerlas en algo as胤?[n][w][e]

[msg Card_Battle_LAST03_03 [Akechi]]
[s]Mmm, creo que eso significa[n]que has ama隠ado el juego[n]de una forma dif胤cil de probar.[n][w][e]

[msg Card_Battle_LAST03_04 [Crupier]]
[s]Puede interpretarlo[n]como quiera, se隠or.[n][w][e]

[msg Card_Battle_LAST03_05 [Akechi]]
[s]Muy bien, sigamos jugando.[n][w][e]

[msg Card_Battle_LAST03_06 [Crupier]]
[s]Me alegro de que lo entienda.[n]Giremos las cartas.[n][w][e]

[msg WIN_COUNT_MES [Crupier]]
[s]Su registro actual es[n]de [clr 2][var 0][clr 27] victorias y [clr 2][var 1][clr 27] derrotas.[n][w][e]

[msg __test_message_01]
[s]dummy fhit_157_013_00[n][w][e]

