[msg Dummy]
[s]...[n][w][e]

[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[sel GIMMIC_SEL top]
[s]Pulsarlo[e]
[s]No pulsarlo[e]

[msg D04_155_003_EV01_mes01 [Makoto]]
[s]Uf... A diferencia de la gran[n]escalera delantera, las otras[n]zonas son muy complicadas.[n][w][e]
[s]斡...![n][w][e]

[msg D04_155_003_GIM01_mes01 [Makoto]]
[s]Parece que caer茨n rocas[n]cada vez que intentemos[n]subir por aqu胤.[n][w][e]
[s]As胤 no hay forma de avanzar.[n]Busquemos por los alrededores[n]a ver si encontramos algo.[n][w][e]

[msg D04_155_003_GIM01_CLEAR_ [Makoto]]
[s]Mm, parece un interruptor...[n]夷Le damos a ver qu姻 pasa?[n][w][e]

[msg D04_155_003_GIM01_CLEAR__2 [Makoto]]
[s]夷Qu姻 ha sido eso?[n]Acaban de caer unas rocas...[n][w][e]
[s]Deber胤amos ir a ver[n]si ha cambiado algo.[n][w][e]

[msg D04_155_003_GIM01_CLEAR__3 [Makoto]]
[s]S胤, a lo mejor es una trampa.[n]Vamos a mirar[n]por otra parte de momento.[n][w][e]

[msg D04_155_003_GIM01_CLEAR__4 [Morgana]]
[s]Ya hemos activado esto.[n][w][e]

