[msg D05_02_e341_071_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que solo hay una puerta m茨s.[n]Deber胤amos ir para all茨.[n][w][e]

[msg D05_02_e341_071_mes02 [Yusuke]]
[s][bup 0 5 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? Esperad un momento...[n][w][e]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No lograremos alcanzarla[n]si no cruzamos eso que parece[n]una prensa hidr茨ulica.[n][w][e]

[msg D05_02_e341_071_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤... Tendremos que buscar[n]alg雨n modo de pararla. Centr姻monos[n]en eso de momento.[n][w][e]

