[msg D08_01_NPC_TALK_13_mes01 [Mujer sonriente]]
[s]No hay forma de cambiar el mundo.[n]Todos pensamos igual.[n][w][e]
[s]夷Por qu姻 no os un胤s a nosotros?[n]El mundo llegar茨 pronto a su fin,[n]as胤 que ser胤a lo mejor.[n][w][e]

[msg D08_01_NPC_TALK_13_mes02 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3111 65535 0]夷Cu茨ndo comenz吋 esta gente[n]a pensar que una prisi吋n es[n]un buen lugar para vivir?[n][w][e]

[msg D08_01_NPC_TALK_14_mes01 [Estudiante sin esperanzas]]
[s]Solo un idiota se esforzar胤a[n]para tratar de cumplir[n]sus sue隠os.[n][w][e]
[s]Aqu胤 cualquier deseo puede hacerse[n]realidad. 夷No es eso[n]lo que quiere todo el mundo?[n][w][e]

[msg D08_01_NPC_TALK_14_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]夷Esta gente de verdad cree que[n]sus deseos se har茨n realidad?[n][w][e]

[msg D08_01_NPC_TALK_15_mes01 [Hombre de mediana edad resignado]]
[s]Eh, chicos, ser茨 mejor que teng茨is[n]cuidado. Nosotros no somos[n]los 雨nicos que hay por aqu胤.[n][w][e]
[s]Parece que hay otro lugar reservado[n]para la gente m茨s malvada[n]que puede haber.[n][w][e]

[msg D08_01_NPC_TALK_15_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9021 65535 0]夷Ser茨 la celda de cuarentena[n]de la que hemos o胤do hablar?[n][w][e]

[msg D161_06_DUMMY_mes01]
[s](調整中)戦闘は飛ばします。[n][w][e]

