[msg GENERIC_HELP_00]
[s]夷Y si quedo a solas con Ohya?[n][e]

[msg GENERIC_HELP_01]
[s]夷Y si quedo a solas con Takemi?[n][e]

[msg GENERIC_HELP_02]
[s]夷Y si quedo a solas con Kawakami?[n][e]

[msg GENERIC_HELP_03]
[s]夷Y si quedo a solas con Hifumi?[n][e]

[msg GENERIC_HELP_04]
[s]夷Y si quedo a solas con Chihaya?[n][e]

[msg GENERIC_HELP_05]
[s]夷Y si quedo a solas con Futaba?[n][e]

[msg GENERIC_HELP_06]
[s]夷Y si quedo a solas con Ann?[n][e]

[msg GENERIC_HELP_07]
[s]夷Y si quedo a solas con Makoto?[n][e]

[msg GENERIC_HELP_08]
[s]夷Y si quedo a solas con Haru?[n][e]

[msg GENERIC_HELP_09]
[s]夷Y si quedo a solas con Sumire?[n][e]

[msg GENERIC_HELP_10]
[s]Puede que no invite a nadie.[n][e]

[msg MSG_LAST_GREETING_CDSHOP [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1001 65535 0]Esta tienda siempre tiene ofertas.[n][w][e]

[msg MSG_LAST_GREETING_SUPERM [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]No tenemos tiempo para comprar.[n]Vamos a ver a los dem茨s.[n][w][e]

[msg MSG_LAST_GREETING_MIYAGE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]No necesitas regalos,[n]sino palabras.[n][w][e]

[msg MSG_LAST_GREETING_JEWELR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]Ahora mismo no puedes comprar[n]joyas. Vamos a despedirnos.[n][w][e]

[msg MSG_LAST_GREETING_ACCESS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Esta tienda estaba muy de moda.[n]夷Habr茨 alguna en tu ciudad?[n][w][e]

[msg MSG_LAST_GREETING_SPORTS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]En tu ciudad hay tiendas de[n]zapatos. Vamos a despedirnos.[n][w][e]

[msg MSG_LAST_GREETING_UMBREL [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0]夷Te acuerdas de aquella vez en la que[n]vine preparado con un paraguas?[n]Al final nos vino bien.[n][w][e]

[msg MSG_LAST_GREETING_ORIENT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Esta tienda est茨 muy de moda,[n]aunque no es de mi estilo.[n][w][e]

[msg MSG_LAST_GREETING_SHOES_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Tus zapatos est茨 muy bien[n]para tener ya un a隠o.[n][w][e]

[msg MSG_LAST_GREETING_BAGSHO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Me gusta la mochila que llevas.[n][w][e]

[msg MSG_LAST_GREETING_DRESSS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Viniste a esta tienda con Sumire,[n]夷no? Estar胤a bien repetir.[n][w][e]

[msg MSG_LAST_GREETING_DRESSS_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Esta tienda le gusta a Ann.[n]No creo que tengan nada para m胤.[n][w][e]

[msg MSG_LAST_GREETING_BRANDS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Esta tienda siempre estaba llena.[n][w][e]

[msg MSG_LAST_GREETING_FLOWER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]En todo caso, las flores tendr胤an[n]que ser para ti, 夷no?[n]斡Vamos a despedirnos![n][w][e]

[msg MSG_LAST_GREETING_WATCHS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]斡No hay tiempo que perder![n]斡Vamos a despedirnos![n][w][e]

[msg MSG_LAST_GREETING_LEATHE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Todav胤a huele a animales. V茨monos[n]antes de que se nos pegue el olor.[n][w][e]

[msg MSG_LAST_GREETING_COSME_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1052 65535 0]No tienes tiempo para ir de[n]compras. Vamos a despedirnos.[n][w][e]

[msg MSG_LAST_GREETING_SHOESS [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]No necesitas nada de eso.[n]Vamos a ver a los dem茨s.[n][w][e]

[msg MSG_LAST_GREETING_PHOTO_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1099 65535 0]Tienes recuerdos que no pueden[n]plasmarse en im茨genes. Vamos[n]a verlos a todos por 雨ltima vez.[n][w][e]

[msg MSG_LAST_GREETING_DEADEN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1018 65535 0]No conoces a nadie por aqu胤, 夷no?[n]Pues vamos a otro sitio.[n][w][e]

[msg MSG_LAST_GREETING_place [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Aqu胤 no se te ha perdido nada, 夷no?[n]Venga, 斡vayamos a otro lado![n][w][e]

[msg MSG_LAST_GREETING_etc [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]夷Qu姻 ocurre? Venga, 斡tenemos[n]que despedirnos de los dem茨s![n][w][e]

[msg MSG_LastKeyfree [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]No podemos esperar m茨s.[n]斡Hay que prepararse ya![n][w][e]

[msg MND_0103]
[s]No tengo nada que hacer aqu胤.[n][w][e]
[s]Deber胤a ir a ver[n]c吋mo van los dem茨s.[n][w][e]

[msg MND_0103to0108_Error_Not]
[s]No hay tiempo para ir de compras.[n][w][e]
[s]Deber胤a ir a ver[n]c吋mo van los dem茨s.[n][w][e]

[msg MND_0103to0108_Error_Not_2]
[s]No hay tiempo que perder.[n][w][e]
[s]Deber胤a ir a ver[n]c吋mo van los dem茨s.[n][w][e]

[msg MSG_SPORTS_NOTOPEN]
[s]Parece que aqu胤 venden[n]todo tipo de productos deportivos,[n]tanto novedades como cl茨sicos.[n][w][e]
[s]Ya me pasar姻 a comprar[n]algo cuando tenga tiempo.[n][w][e]

[msg MSG_SPORTS_SELECT [Ayudante de tienda de deportes]]
[s]Hola, tenemos las mejores ofertas.[n][w][e]

[msg MSG_SPORTS_THANKS [Ayudante de tienda de deportes]]
[s]斡Gracias! Esperamos[n]volver a verte pronto.[n][w][e]

[msg MSG_SPORTS_NOT_BUY [Ayudante de tienda de deportes]]
[s]斡Vuelva otro d胤a![n][w][e]

[msg MSG_CDSHOP_P5R [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Hay un aut吋grafo en un p吋ster[n]de la tienda. Vamos a ver.[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0]No veo nada.[n][w][e]

[msg MSG_SportShop_MayCueInfo [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Son tacos de billar...[n]T雨 no sabes usarlos, 夷no?[n][w][e]
[s][f 4 10 65535 0 0]Vend胤an un libro por aqu胤 cerca.[n]Puede que ense隠e c吋mo usarlos.[n][w][e]

[msg SUPERMARKET_NOTOPEN]
[s]Este sitio parece tener[n]productos caros hechos[n]con distintos materiales.[n][w][e]
[s]Deber胤a venir a comprar[n]cuando necesite algo.[n][w][e]

[msg SUPERMARKET_SELECT [Ayudante de supermercado]]
[s]T吋mese su tiempo para mirar[n]lo que le interese.[n][w][e]

[msg SUPERMARKET_THANKS [Ayudante de supermercado]]
[s]Muchas gracias. Esperamos volver[n]a verlo pronto.[n][w][e]

[msg SUPERMARKET_NOT_BUY [Ayudante de supermercado]]
[s]Vuelva cuando quiera.[n][w][e]

[msg MSG_MIYAGE [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Venden much胤simas cosas aqu胤, pero[n]夷qu姻 tipo de tienda es?[n][w][e]

[msg MND_MIYAGE]
[s]En esta tienda de souvenirs venden[n]todo tipo de art胤culos.[n][w][e]

[msg MSG_JEWELRY_NOTOPEN]
[s]Aqu胤 venden joyas y accesorios.[n][w][e]
[s]Cuando me hagan falta,[n]deber胤a venir aqu胤.[n][w][e]

[msg JEWELRY_START [Ayudante de joyer胤a]]
[s][f 4 23 1 8 3 5 65534 0][vp 8 2 1 0 8 0]Muy buenas. Por favor,[n]no toque los art胤culos.[n][w][e]

[msg JEWELRY_THANKS [Ayudante de joyer胤a]]
[s][vp 8 2 1 0 8 0]Muchas gracias. Esperamos volver[n]a verlo pronto.[n][w][e]

[msg JEWELRY_NOT_BUY [Ayudante de joyer胤a]]
[s][vp 8 2 1 0 8 0]Esperamos volver a verlo pronto.[n][w][e]

[msg MSG_ACCESSORIES_NOTOPEN]
[s]Aqu胤 venden muchos accesorios.[n][w][e]
[s]Ya me pasar姻 cuando me haga[n]falta algo.[n][w][e]

[msg ACCESSORIES_SELECT [Ayudante de tienda de accesorios]]
[s][f 4 23 1 16 3 5 65534 0][vp 8 2 1 0 16 0]斡Hola! Tenemos accesorios[n]para todos los bolsillos.[n][w][e]

[msg ACCESSORIES_THANKS [Ayudante de tienda de accesorios]]
[s][vp 8 2 1 0 16 0]斡Muchas gracias! Vuelva pronto.[n][w][e]

[msg ACCESSORIES_NOT_BUY [Ayudante de tienda de accesorios]]
[s][vp 8 2 1 0 16 0]De acuerdo. Vuelva cuando quiera.[n][w][e]

[msg MSG_ShoesShop_Moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]No est茨s en ning雨n equipo[n]deportivo. 夷Para qu姻[n]vas a comprar zapatillas?[n][w][e]

[msg MSG_ShoesShop]
[s]Hay un mont吋n de zapatillas[n]de deporte apiladas.[n][w][e]

[msg MSG_UMBRELLA_SHOP_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1191 65535 0]Ten un paraguas a mano por si[n]llueve de pronto. No puedo mojarme[n]bajo ning雨n concepto.[n][w][e]

[msg MSG_UMBRELLA_SHOP]
[s]Aqu胤 tienen todo tipo de paraguas.[n]Algunos caros,[n]otros m茨s baratos de vinilo...[n][w][e]

[msg MSG_ORIENTAL_SHOP]
[s]Es una tienda que vende[n]productos japoneses diversos.[n][w][e]
[s]Si compro algo aqu胤[n]y se lo doy a alguien,[n]podr胤a hacerle muy feliz.[n][w][e]

[msg MSG_ORIENTAL_SHOP_START [Ayudante de bazar]]
[s][f 4 23 1 5 3 5 65534 0][vp 8 2 1 0 5 0]Bienvenido. 夷Qu姻 le parece cambiar[n]un poco y comprar[n]peque隠os productos japoneses?[n][w][e]

[msg MSG_ORIENTAL_SHOP_THANKS [Ayudante de bazar]]
[s][vp 8 2 1 0 5 0]Muchas gracias. 斡Vuelva pronto![n][w][e]

[msg MSG_ORIENTAL_SHOP_NOT_BU [Ayudante de bazar]]
[s][vp 8 2 1 0 5 0]Vuelva cuando quiera.[n][w][e]

[msg MSG_SHOES_REPAIR_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Tus zapatos siguen[n]en perfecto estado. No parece[n]que les haga falta ning雨n arreglo.[n][w][e]

[msg MSG_SHOES_REPAIR]
[s]A mis zapatos[n]no les hacen falta arreglos.[n][w][e]

[msg MSG_BAGSHOP_MORU [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Parecen demasiado peque隠os y[n]estrechos para m胤.[n][w][e]

[msg MSG_BAGSHOP]
[s]Hay un mont吋n de zapatos de mujer.[n][w][e]

[msg MSG_DRESSSHOP_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Todas las prendas parecen iguales[n]si se ponen unas al lado de otras.[n][w][e]

[msg MSG_DRESSSHOP]
[s]Venden ropa de mujer.[n][w][e]

[msg MSG_BRANDSHOP_MORU [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Todo el mundo mira las prendas[n]con mucho inter姻s. 夷Son marcas[n]conocidas o qu姻?[n][w][e]

[msg MSG_BRANDSHOP]
[s]Es una tienda de marca para[n]mujeres. Est茨 llena de gente.[n][w][e]

[msg MSG_Flower_ByebyeEnd [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]夷Has terminado?[n]Muy bien, vamos a otro sitio.[n][w][e]

[msg MSG_FlowerLAstDay [Hanasaki]]
[s][vp 8 2 0 58508 6 0]Ah, [f 4 2]. 夷C吋mo te va?[n]夷Vas a...?[n][w][e]
[s][vp 8 2 0 0 6 0]Ah, que vuelves a tu ciudad natal.[n][w][e]
[s][vp 8 2 0 0 6 0]En todas partes hay flores,[n]as胤 que acu姻rdate de la tienda[n]cuando veas alguna. Je, je.[n][w][e]
[s][vp 8 2 0 0 6 0]Mucha suerte.[n]Tienes todo mi apoyo.[n][w][e]

[msg MSG_FLOWERSHOP_NOTOPEN]
[s]Hay varios tipos de flores[n]a la vista. Cuando necesite[n]algunas, deber胤a venir a comprar.[n][w][e]

[msg MSG_FLOWER_BAITO_COMMIT_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Solicitaste un trabajo a tiempo[n]parcial en esta florister胤a, 夷no?[n][w][e]

[msg MSG_FlowerShop_ActQ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]Las flores huelen bien.[n]夷Qu姻 vas a hacer?[n][w][e]

[sel FLOWER_SEL top]
[s]Trabajar姻 aqu胤.[e]
[s]Comprar姻 algo.[e]
[s]Nada.[e]

[msg MSG_FLOWER_NotBaitoDay [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Si no recuerdo mal,[n]solicitaste un trabajo[n]a tiempo parcial aqu胤, 夷verdad?[n][w][e]
[s][f 4 10 65535 0 0]Creo que solo necesitaban gente[n]por el [clr 2]d胤a[clr 27].[n]Ya trabajar茨s en otro momento.[n][w][e]

[msg MSG_FLOWER_NotBaitoDay_c [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Creo que solo necesitaban gente[n]por las [clr 2]tardes[clr 27].[n][w][e]

[msg MSG_FLOWERSHOP_START_01 [Florista]]
[s][f 4 23 1 18 3 5 65534 0][vp 8 2 1 0 18 0]Recibir flores le alegra el d胤a[n]a cualquiera. 夷Quiere hacerle[n]un regalo a alguien especial?[n][w][e]

[msg MSG_FLOWERSHOP_START_02 [Florista]]
[s][f 4 23 1 18 3 5 65534 0][vp 8 2 1 0 18 0]Tambi姻n vendemos aceite y corteza.[n]Eche un vistazo a todo[n]lo que tenemos.[n][w][e]

[msg MSG_FLOWERSHOP_START_03 [Florista]]
[s][f 4 23 1 18 3 5 65534 0][vp 8 2 1 0 18 0]Tener flores cerca le pondr茨[n]de buen humor. Le recomiendo darles[n]nutrientes para plantas.[n][w][e]

[msg MSG_FLOWERSHOP_START_04 [Hanasaki]]
[s][f 4 23 1 18 3 5 65534 0][vp 8 2 1 0 18 0]Hola. 夷Qu姻 desea?[n][w][e]

[msg MSG_FLOWERSHOP_BUY_END [Florista]]
[s][f 4 23 1 18 6 5 65534 0][vp 8 2 1 0 18 0]Gracias por su compra.[n][w][e]

[msg MSG_FLOWERSHOP_BUY_END_n [Hanasaki]]
[s][f 4 23 1 18 6 5 65534 0][vp 8 2 1 0 18 0]Gracias por su compra.[n][w][e]

[msg MSG_FLOWERSHOP_NOTBUY_EN [Florista]]
[s][f 4 23 1 18 6 5 65534 0][vp 8 2 1 0 18 0]Muchas gracias.[n]Esperamos verlo de nuevo.[n][w][e]

[msg MSG_FLOWERSHOP_NOTBUY_EN_2 [Hanasaki]]
[s][f 4 23 1 18 6 5 65534 0][vp 8 2 1 0 18 0]Muchas gracias.[n]Esperamos verlo de nuevo.[n][w][e]

[msg MSG_FlowerBaito_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Quiz茨 mejore tu[n][f 4 11 4][clr 26][f 4 12 4][clr 27] si trabajas[n]en una florister胤a.[n][w][e]

[msg MSG_FlowerBaito_StartSPd [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]Dicen que hay mucha gente[n][clr 2]los mi姻rcoles y los s茨bados[clr 27].[n][w][e]

[msg MND_Flower_ParamUpInfo]
[s]Siento que mi [f 4 11 1][clr 26][f 4 12 0][clr 27][n]va a aumentar pronto.[n][w][e]

[msg MND_Flower_ParamEndInfo]
[s]Creo que ya tengo suficiente[n][f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

[msg MSG_FlowerBaito_Ask [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷Quieres trabajar?[n][w][e]

[sel SEL_FlowerBaitoFix top]
[s]Trabajar姻.[e]
[s]Deja que me lo piense.[e]

[msg MSG_SYSTEM_SHORTCUT_FLOW]
[s]Ya puedes usar Viaje r茨pido para ir[n]a la [clr 6]florister胤a[clr 0] de Shibuya.[n][w][e]

[msg MSG_WATCHSHOP_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]夷Acaso no puedes mirar la hora[n]en el m吋vil sin gastarte[n]el dinero en un reloj caro?[n][w][e]

[msg MSG_WATCHSHOP]
[s]Hay una gran variedad de relojes[n]aqu胤, con estilos tanto juveniles[n]como m茨s maduros.[n][w][e]

[msg MSG_LEATHERSHOP_MORU [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]夷Eh? Esta tienda huele a animal.[n]夷Podemos ir a otro lado?[n][w][e]

[msg MSG_LEATHERSHOP]
[s]El ambiente est茨 impregnado[n]de olor a cuero.[n][w][e]

[msg MSG_COSME_NOTOPEN]
[s]Aqu胤 venden perfume y maquillaje.[n]Cuando me hagan falta,[n]deber胤a venir aqu胤.[n][w][e]

[msg MSG_COSME_INFO [Empleada de tienda de cosm姻tica]]
[s][f 4 23 1 13 3 5 65534 0][vp 8 2 1 0 13 0]Hola. 夷Desea comprar[n]alg雨n regalo? 夷O algo para usted?[n][w][e]

[msg MSG_COSME_THANKS [Empleada de tienda de cosm姻tica]]
[s][vp 8 2 1 0 13 0]斡Muchas gracias![n][w][e]

[msg MSG_COSME_NOTBUY [Empleada de tienda de cosm姻tica]]
[s][vp 8 2 1 0 13 0]Esperamos que vuelva pronto.[n][w][e]

[msg MSG_SHOESSHOP_MORU [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Esos tacones son alt胤simos.[n]Casi parecen armas.[n][w][e]

[msg MSG_SHOESSHOP]
[s]Aqu胤 venden zapatos[n]de tac吋n.[n][w][e]

[msg MSG_PHOTO_MACHINE_MORU [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Tiene muchas funciones para mejorar[n]el aspecto, pero...[n][w][e]
[s][f 4 10 65535 0 0]Es un fotomat吋n, 夷no? No deber胤an[n]salir fotos manipuladas.[n][w][e]

[msg MSG_PHOTO_MACHINE]
[s]Es un fotomat吋n.[n][w][e]
[s]Parece que tiene opciones[n]para estilizar el rostro[n]y retocar la imagen.[n][w][e]

[msg MSG_DEADEND01_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0]Creo que por all胤 no hay nada[n]de inter姻s. Volvamos.[n][w][e]

[msg MSG_DEADEND01]
[s]Por all胤 no hay nada de inter姻s.[n][w][e]

[msg MND_CO_NG_COMMON_000]
[s][vp 1 0 0 0 0 0]No puedo permitirme[n]perder el tiempo.[n][w][e]

[msg MND_E10920100_NG_UNDER_0]
[s][vp 1 0 0 0 0 0]Parece que el acceso[n]a la [clr 2]l胤nea Ginza[clr 27] est茨[n]en esta planta.[n][w][e]

[msg MND_E10920100_NG_Hideout]
[s][vp 1 0 0 0 0 0]Hay una salida que lleva arriba.[n][w][e]
[s][vp 1 0 0 0 0 0]Pero el camino que debo[n]tomar no es este.[n][w][e]

[msg MND_E10920100_CHK_AUTO_M]
[s][vp 1 0 0 0 0 0]Es una m茨quina expendedora.[n][w][e]
[s][vp 1 0 0 0 0 0]No tengo sed.[n][w][e]

[msg MND_E10920100_CHK_BAKERY]
[s][vp 1 0 0 0 0 0]Hay varias filas de panes[n]reci姻n horneados en la panader胤a.[n][w][e]
[s][vp 1 0 0 0 0 0]Su apetecible aroma est茨[n]por toda la zona.[n][w][e]

[msg MSG_E243301_CHK_SHOP_NG_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Aqu胤 no se te ha perdido nada, 夷no?[n]Venga, 斡vayamos a otro lado![n][w][e]

[msg MSG_E243301_CHK_SHOP_NG__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷Qu姻 pasa? 斡V茨monos ya a otro lado![n][w][e]

[msg MSG_E243301_CHK_SHOP_NG__3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Aqu胤 no se te ha perdido nada, 夷no?[n]斡Ya vendremos[n]cuando tengamos tiempo![n][w][e]

[msg MSG_E19310100_NG_GINZASE [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6023 65535 0]Tenemos que cambiar a la l胤nea JL[n]en Shibuya. 夷Podemos darnos prisa?[n][w][e]

[msg MSG_E19310100_NG_HIDEOUT [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7190 65535 0]Tenemos que coger la JL.[n]夷No deber胤amos estar yendo[n]hacia la plaza?[n][w][e]

[msg MSG_E24420300_NG_GINZASE [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]Espera. Tenemos que coger la JL[n]para ir a Shinjuku. La entrada[n]est茨 yendo hacia la plaza.[n][w][e]

[msg MSG_E24420300_NG_HIDEOUT [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7172 65535 0]夷Ad吋nde vas?[n]斡V茨monos ya a Shinjuku![n][w][e]

[msg MSG_E655104_CHK_SHOP_NG_ [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1140 0 0]Vamos a darle flores[n]al Jefe, 夷verdad?[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__2 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1139 0 0]No necesitas nada de aqu胤, 夷verdad?[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__3 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1111 0 0]Esto no es una florister胤a.[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__4 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1112 0 0]Mmm, no tienen mala pinta,[n]pero mejor compramos las flores.[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__5 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1178 0 0]Lo est茨s haciendo aposta, 夷no?[n]Este no es el lugar que buscamos.[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__6 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 2 65535 1036 0 0]Hay que ir a la florister胤a.[n]斡Vamos! 斡A la florister胤a![n]斡斡A la florister胤a!![n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__7 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0]T雨 trabajaste en una[n]florister胤a, 夷no? Pues vamos.[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__8 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0]Se supone que hay una florister胤a[n]en el centro comercial subterr茨neo.[n]Vamos a echar un vistazo.[n][w][e]

[msg MSG_E655104_CHK_SHOP_NG__9 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0]斡Oye! 夷No 胤bamos a comprar flores?[n][w][e]

[msg MSG_E65510400_FLOWER_000 [Hanasaki]]
[s][f 4 23 1 18 3 10 0 10][vp 8 0 1 1 18 0]Hola, [f 4 1]. 夷Necesitas ayuda?[n][f 1 3 65535][w][e]

[sel SEL_E65510400_FLOWER_000 top]
[s]Ven胤a a por algo para regalar.[e]
[s]Quer胤a un regalo sorpresa.[e]

[msg MSG_E65510400_FLOWER_001 [Hanasaki]]
[s][vp 8 0 1 2 18 0]斡Estupendo! 斡Yo me encargo![n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_002 [Hanasaki]]
[s][f 4 23 1 18 3 10 0 10][vp 8 0 1 3 18 0]Esto servir茨. He intentado que sea[n]lo m茨s sencillo posible.[n][f 1 3 65535][w][e]
[s][vp 8 0 1 4 18 0]De acuerdo, el total se queda en...[n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_002_2 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]斡Estate quieto! Ya pago yo.[n]Has estado cuidando mucho de m胤,[n]as胤 que...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Tengo que agradec姻rtelo.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_003 [Hanasaki]]
[s][f 4 23 1 18 3 10 0 10][vp 8 0 1 7 18 0]斡Buena suerte! 斡T雨 puedes![n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_100 [Trabajadora]]
[s][f 4 23 1 18 6 10 0 10][vp 8 0 1 8 18 0]斡Buenas! 夷Qu姻 tipo de flores[n]est茨s buscando?[n][f 1 3 65535][w][e]

[sel SEL_E65510400_FLOWER_100 top]
[s]Ven胤a a por algo para regalar.[e]
[s]Quer胤a un regalo sorpresa.[e]

[msg MSG_E65510400_FLOWER_101 [Trabajadora]]
[s][vp 8 0 1 9 18 0]Genial, ahora mismo.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_103 [Trabajadora]]
[s][f 4 23 1 18 3 10 0 10][vp 8 0 1 10 18 0]斡Aqu胤 tienes! He intentado que sea[n]lo m茨s sencillo posible.[n][f 1 3 65535][w][e]
[s][vp 8 0 1 11 18 0]El total se queda en...[n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_103_2 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]斡Estate quieto! Ya pago yo.[n]Has estado cuidando mucho de m胤,[n]as胤 que...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Tengo que agradec姻rtelo.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_104 [Trabajadora]]
[s][f 4 23 1 18 6 10 0 10][vp 8 0 1 14 18 0]Muchas gracias. 斡Buena suerte![n][f 1 3 65535][w][e]

[msg MSG_E65510400_FLOWER_005 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 1 15 65535 0]斡Listo, ya tienes el regalo![n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_000_00 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 1 52 65535 0]Pues ya est茨s preparado[n]para la cita.[n]Sabes a qui姻n vas a invitar, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 53 65535 0]Tranquilo, soy un caballero[n]con buenos modales, no me acoplar姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 54 65535 0]斡Muy bien, que tengas suerte![n][f 1 3 65535][w][e]

[msg MND_E65510400_TEL_001_00]
[s][vp 1 0 0 0 0 0]Voy a invitar a...[n][f 1 3 65535][w][e]

[sel SEL_E65510400_TEL_001_00 top]
[s]Pasar un rato con Ohya[ref 0 0][e]
[s]Pasar un rato con Takemi[ref 1 1][e]
[s]Pasar un rato con Kawakami[ref 2 2][e]
[s]Pasar un rato con Hifumi[ref 3 3][e]
[s]Pasar un rato con Chihaya[ref 4 4][e]
[s]Pasar un rato con Futaba[ref 5 5][e]
[s]Pasar un rato con Ann[ref 6 6][e]
[s]Pasar un rato con Makoto[ref 7 7][e]
[s]Pasar un rato con Haru[ref 8 8][e]
[s]Pasar un rato con Sumire[ref 9 9][e]

[msg MSG_E65510400_TEL_002_00 [Ohya]]
[s][bup 0 107 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 41 65535 0]Eh, 夷qu姻 tal?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_01 [Takemi]]
[s][bup 0 108 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 35 65535 0]夷Qu姻? 夷Ha ocurrido algo?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_02 [Kawakami]]
[s][bup 0 109 3 65535 1][f 4 10 65535 0 0][vp 8 0 1 38 65535 0]Perdona, estoy en el instituto.[n]夷Necesitas algo?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_03 [Hifumi]]
[s][bup 0 106 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 44 65535 0]D胤game...[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_04 [Chihaya]]
[s][bup 0 113 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]Hola, [f 4 1]. 夷Ocurre algo?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_05 [Futaba]]
[s][bup 0 8 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 28 65535 0]Buenas. 夷C吋mo te va?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_06 [Ann]]
[s][bup 0 4 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]Hola, 夷c吋mo est茨s?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_07 [Makoto]]
[s][bup 0 6 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 16 65535 0]夷[f 4 2]? 夷Ocurre algo?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_08 [Haru]]
[s][bup 0 7 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 20 65535 0]夷[f 4 2]? 夷Ocurre algo?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_002_09 [Sumire]]
[s][bup 0 10 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 48 65535 0]夷S胤? Aqu胤 Yoshizawa.[n][f 1 3 65535][w][e]

[sel SEL_E65510400_TEL_002_00 top]
[s]Ven a Shinagawa.[e]
[s]夷Te apetece ir a Shinagawa?[e]

[msg MSG_E65510400_TEL_003_00 [Ohya]]
[s][bup 0 107 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 42 65535 0]夷Ahora? 夷As胤 por las buenas?[n][f 1 3 65535][w][e]
[s][bup 0 107 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 43 65535 0]Si es lo que quiere mi novio,[n]斡que as胤 sea![n]Acabo una cosilla y voy.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_01 [Takemi]]
[s][bup 0 108 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 36 65535 0]夷A Shinagawa? 夷Por qu姻?[n]Espera, menuda pregunta...[n][f 1 3 65535][w][e]
[s][bup 0 108 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 37 65535 0]Estoy trabajando, pero puedo[n]salir pronto. Te veo all胤.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_02 [Kawakami]]
[s][bup 0 109 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 39 65535 0]夷Ahora? Me pillas de improviso.[n][f 1 3 65535][w][e]
[s][bup 0 109 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 40 65535 0]Pero s胤. Ya casi he acabado[n]de trabajar, as胤 que puedo ir.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_03 [Hifumi]]
[s][bup 0 106 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 45 65535 0]夷A Shinagawa?[n][f 1 3 65535][w][e]
[s][bup 0 106 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 46 65535 0]Vale... Me preparo[n]y voy para all茨.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 47 65535 0]Nos vemos luego.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_04 [Chihaya]]
[s][bup 0 113 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 33 65535 0]夷A Shinagawa? Vale.[n][f 1 3 65535][w][e]
[s][bup 0 113 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]Cerrar姻 pronto para poder ir.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_05 [Futaba]]
[s][bup 0 8 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]夷A Shinagawa? V-vale, s胤.[n][f 1 3 65535][w][e]
[s][bup 0 8 2 65535 1][f 4 10 65535 0 0][vp 8 0 1 30 65535 0]夷Est茨s en la calle?[n]夷Podr胤as venir a...?[n]Mira, da igual. Nos vemos all胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 31 65535 0]斡Chachi! 斡Nos vemos![n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_06 [Ann]]
[s][bup 0 4 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 25 65535 0]夷A Shinagawa? S胤, claro.[n][f 1 3 65535][w][e]
[s][bup 0 4 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 26 65535 0]Y resulta que cae[n]en el D胤a Blanco, 夷eh?[n]Lo cierto es que ten胤a ganas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 27 65535 0]De acuerdo. Me preparo[n]y voy para all茨.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_07 [Makoto]]
[s][bup 0 6 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]Mm, vale.[n][f 1 3 65535][w][e]
[s][bup 0 6 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 18 65535 0]Menos mal que has dicho algo.[n]Estaba empezando a preocuparme.[n]Hoy es..., bueno, ya lo sabes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 19 65535 0]Genial, me cambio[n]y nos vemos all胤.[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_08 [Haru]]
[s][bup 0 7 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 21 65535 0]夷A Shinagawa? Bueno, vale.[n][f 1 3 65535][w][e]
[s][bup 0 7 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 22 65535 0]夷Una cita? 斡Me encantar胤a![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 23 65535 0]Vale, deja que me prepare.[n]夷Quedamos all胤?[n][f 1 3 65535][w][e]

[msg MSG_E65510400_TEL_003_09 [Sumire]]
[s][bup 0 10 4 65535 1][f 4 10 65535 0 0][vp 8 0 1 49 65535 0]夷Ahora? Claro, sin problema.[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 1][f 4 10 65535 0 0][vp 8 0 1 50 65535 0]No tengo entrenamiento,[n]as胤 que voy enseguida.[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 1][f 4 10 65535 0 0][vp 8 0 1 51 65535 0]斡Nos vemos all胤![n][f 1 3 65535][w][e]

[msg MND_E65510400_TEL_004_00]
[s][vp 1 0 0 0 0 0]Deber胤a prepararme[n]para ir a Shinagawa.[n][f 1 3 65535][w][e]

[msg MND_E65510400_TEL_005_00]
[s][vp 1 0 0 0 0 0]Deber胤a volver al Leblanc.[n][f 1 3 65535][w][e]

[msg EX_0103_0108_LOCK_mes01 [Invitada]]
[s][vp 1 0 0 0 0 0]Estas mochilas de la suerte[n]son incre胤bles. 斡Se dice que valen[n]10 veces m茨s de lo que cuestan![n][w][e]

[msg EX_0103_0108_LOCK_mes02 [Invitado]]
[s][vp 1 0 0 0 0 0]Parece que se ha corrido la voz.[n]Esto est茨 a reventar.[n][w][e]
[s][vp 1 0 0 0 0 0]Pero me da a m胤 que hay gente[n]que planea vender lo que consiga.[n][w][e]

[msg EX_0103_0108_LOCK_mes03 [Invitada]]
[s][vp 1 0 0 0 0 0]Es una locura la cantidad de gente[n]que hay, pero 斡yo quiero una![n][w][e]

[msg EX_0103_0108_LOCK_mes04]
[s][vp 1 0 0 0 0 0]Parece que esta cola es para[n]comprar las mochilas de la suerte.[n][w][e]
[s][vp 1 0 0 0 0 0]No creo que pueda continuar...[n][w][e]

[msg EX_0103_0108_LOCK_mes00]
[s][vp 1 0 0 0 0 0]Hay demasiada gente.[n]No puedo seguir...[n][w][e]

[msg MND_RankUp_OK_Chishiki]
[s]Siento que mi [f 4 11 1][clr 26][f 4 12 0][clr 27][n]va a aumentar pronto.[n][w][e]

[msg MND_RankUp_NG_Chishiki]
[s]No creo que mi [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vaya a mejorar pronto.[n][w][e]

[msg MND_INC_PARAMCHK_L_TISIK]
[s]Parece que todav胤a tengo mucho[n]margen de mejora...[n][w][e]

[msg MND_INC_PARAMCHK_M_TISIK]
[s]Noto que algo me sobreviene...[n][w][e]

[msg MND_INC_PARAMCHK_S_TISIK]
[s]Creo que estoy cerca de avanzar[n]con mi [f 4 11 0][clr 26][f 4 12 0][clr 27].[n][w][e]

[msg MND_RankUp_OK_Miryoku]
[s]Siento que mi [f 4 11 1][clr 26][f 4 12 0][clr 27][n]va a aumentar pronto.[n][w][e]

[msg MND_RankUp_NG_Miryoku]
[s]No creo que mi [f 4 11 1][clr 26][f 4 12 0][clr 27][n]vaya a mejorar pronto.[n][w][e]

[msg MND_INC_PARAMCHK_L_MIRYO]
[s]Parece que todav胤a tengo mucho[n]margen de mejora...[n][w][e]

[msg MND_INC_PARAMCHK_M_MIRYO]
[s]Noto que algo me sobreviene...[n][w][e]

[msg MND_INC_PARAMCHK_S_MIRYO]
[s]Creo que estoy cerca de avanzar[n]con mi [f 4 11 1][clr 26][f 4 12 1][clr 27].[n][w][e]

[msg MND_RankUp_OK_Kiyou]
[s]Siento que mi [f 4 11 2][clr 26][f 4 12 2][clr 27][n]va a aumentar pronto.[n][w][e]

[msg MND_RankUp_NG_Kiyou]
[s]No creo que mi [f 4 11 2][clr 26][f 4 12 2][clr 27][n]vaya a mejorar pronto.[n][w][e]

[msg MND_RankUp_OK_Kiyou_Beef]
[s]Si todo va bien, creo que mis[n][f 4 11 1][clr 26][f 4 12 1][clr 27] podr胤an mejorar.[n][w][e]

[msg MND_INC_PARAMCHK_L_KIYOU]
[s]Parece que todav胤a tengo mucho[n]margen de mejora...[n][w][e]

[msg MND_INC_PARAMCHK_M_KIYOU]
[s]Noto que algo me sobreviene...[n][w][e]

[msg MND_INC_PARAMCHK_S_KIYOU]
[s]Creo que estoy cerca de avanzar[n]con mi [f 4 11 2][clr 26][f 4 12 2][clr 27].[n][w][e]

[msg MND_RankUp_OK_Dokyo]
[s]Siento que mis [f 4 11 3][clr 26][f 4 12 3][clr 27][n]van a mejorar pronto.[n][w][e]

[msg MND_RankUp_NG_Dokyo]
[s]No creo que mis [f 4 11 3][clr 26][f 4 12 3][clr 27][n]vayan a mejorar pronto.[n][w][e]

[msg MND_INC_PARAMCHK_L_DOKYO]
[s]Parece que todav胤a tengo mucho[n]margen de mejora...[n][w][e]

[msg MND_INC_PARAMCHK_M_DOKYO]
[s]Noto que algo me sobreviene...[n][w][e]

[msg MND_INC_PARAMCHK_S_DOKYO]
[s]Creo que estoy cerca de avanzar[n]con mi [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][w][e]

[msg MND_RankUp_OK_Yasasisa]
[s]Siento que mi [f 4 11 4][clr 26][f 4 12 4][clr 27][n]va a aumentar pronto.[n][w][e]

[msg MND_RankUp_NG_Yasasisa]
[s]No creo que mi [f 4 11 4][clr 26][f 4 12 4][clr 27][n]vaya a mejorar pronto.[n][w][e]

[msg MND_RankUp_OK_Yasasisa_F]
[s]Si todo va bien, creo que mis[n][f 4 11 4][clr 26][f 4 12 4][clr 27] podr胤an mejorar.[n][w][e]

[msg MND_INC_PARAMCHK_L_YASAS]
[s]Parece que todav胤a tengo mucho[n]margen de mejora...[n][w][e]

[msg MND_INC_PARAMCHK_M_YASAS]
[s]Noto que algo me sobreviene...[n][w][e]

[msg MND_INC_PARAMCHK_S_YASAS]
[s]Creo que estoy cerca de avanzar[n]con mi [f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]

