[msg D157_004_miniEV_01_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que esta puerta no se abre.[n][w][e]

[msg D157_004_miniEV_01_mes02 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tendremos que buscar otro camino.[n][w][e]

[msg D157_004_miniEV_02_mes01 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No pretendo perjudicar[n]a tu grupo. Lo demostrar姻[n]aqu胤 y ahora.[n][w][e]

[sel D157_004_miniEV_02_selA top]
[s]Me muero de ganas.[e]
[s]Vamos a prepararnos primero.[e]

[msg D157_004_miniEV_02_selA_ [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entonces, 斡superar姻[n]tus expectativas![n][w][e]

[msg D157_004_miniEV_02_selA__2 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale, comenzaremos[n]cuando est姻s preparado.[n][w][e]

[msg e380_255_mes01 [Voz mec茨nica]]
[s]Estamos posponiendo[n]la operaci吋n. Espere, por favor.[n][w][e]

[msg EV_MOVE_57_04_MENU]
[s]>何処に移動しますか?[n][w][e]

[sel EV_MOVE_57_04_SEL top]
[s]5F:ボス部屋へ行く[e]
[s]4F:ボス前カジノに行く[e]
[s]3F:ハイローラー用カジノに行く[e]
[s]2F:VIP用カジノに行く[e]
[s]行かない[e]

[msg EV_MOVE_57_04_VIP]
[s]>VIP用カジノへ移動[n][w][e]

[msg EV_MOVE_57_04_HIGH]
[s]>ハイローラー用カジノへ移動[n][w][e]

[msg EV_MOVE_57_04_BOSS]
[s]>ボス前カジノへ移動[n][w][e]

[msg EV_MOVE_57_04_BOSS_BATTL]
[s]>ボス戦へ移動[n][w][e]

[msg EV_MOVE_57_04_CAN]
[s]>乗るのを止めた[n][w][e]

[msg EV_MOVE_57_04_NOT]
[s]>スイッチが反応しない...[n] カードキーが必要なようだ。[n][w][e]

[msg TEST_KENJI_EVENT]
[s]>女検事がエレベーターで上がっていく[n] 所が見える。[n][w][e]

[msg D157_004_miniEV_04_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]No parece que esta puerta[n]se vaya a abrir.[n][w][e]

[msg D157_004_LOCK_KENJI_mes0 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8158 65535 0]Por ahora, deber胤amos centrarnos[n]en ir tras Sae.[n][w][e]

[msg D157_004_LOCK_KENJI_mes0_2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1164 65535 0]No tiene sentido luchar.[n]Vamos a bajar[n]a ver qu姻 tiene que decir.[n][w][e]

