[msg D08_01_e440_010_mes01 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 es esto?[n]Joker, prueba a activarlo.[n][w][e]

[msg D08_01_NPC_TALK_01_mes01 [Hombre de negocios exhausto]]
[s]Trabajo duro, esfuerzo, la ilusi吋n[n]de ser feliz aunque sea un segundo...[n]夷De veras es necesario algo de eso?[n][w][e]
[s]El mundo ya est茨 completo.[n]No queda nada por hacer.[n][w][e]

[msg D08_01_NPC_TALK_01_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]Pero 夷qu姻...?[n]夷Es alguna clase de celda?[n][w][e]

[msg D08_01_NPC_TALK_01_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y adem茨s, hay una especie[n]de vasos sangu胤neos que bajan...[n][w][e]

[msg D08_01_NPC_TALK_02_mes01 [Estudiante somnoliento]]
[s]No podemos hacer nada.[n]Padres, profesores...[n]Los adultos solo nos manipulan.[n][w][e]
[s]Nadie nos escucha si intentamos[n]oponernos a ellos.[n]Y eso nos quiebra el alma.[n][w][e]
[s]Quiz茨 ser胤a mejor aceptar[n]que la vida es esto y ceder[n]a su voluntad.[n][w][e]

[msg D08_01_NPC_TALK_02_mes02 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3184 65535 0]Yo sol胤a ser as胤...[n][w][e]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y de haber seguido igual, ahora[n]dir胤a las mismas cosas que ella.[n][w][e]

[msg D08_01_NPC_TALK_03_mes01 [Hombre sin expresi吋n]]
[s]No importa si llevan raz吋n o no.[n]Las normas est茨n para cumplirlas.[n][w][e]
[s]Los que siguen las reglas son[n]los buenos, mientras que quienes[n]se las saltan son los malos.[n][w][e]

[msg D08_01_NPC_TALK_03_mes02 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9027 65535 0]Hablas de justicia, pero sabes que[n]te est茨n sorbiendo el cerebro, 夷no?[n][w][e]

[msg D08_01_NPC_TALK_04_mes01 [Hombre confuso]]
[s]Qu姻 panda de idiotas. Vuestras[n]acciones no van a cambiar nada.[n][w][e]
[s]Da igual, todo esto acabar茨[n]pronto. Har胤ais bien[n]en aguardar vuestro final.[n][w][e]

[msg D08_01_NPC_TALK_04_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]夷Acaso... todo va a acabar?[n]夷Qu姻 est茨 diciendo?[n][w][e]

