[msg GOTO_D03_EXIT_NG_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7018 65535 0]Oye, antes deber胤amos[n]examinar a fondo.[n][w][e]

[sel START_CHECK_SEL top]
[s]Ir a la 雨ltima Habitaci吋n segura[e]
[s]Infiltrarse tal cual[e]
[s]No entrar a雨n[e]

[msg START_CHECK_MES [Morgana]]
[s][bup 0 3 0 65535 0]Bueno, 夷por d吋nde quieres[n]empezar a explorar?[n][w][e]

[msg START_CHECK_MES_NEXT [Morgana]]
[s][bup 0 3 0 65535 0]Elige sabiamente la ubicaci吋n.[n][w][e]

[sel DUNGEON_EXIT_SEL top]
[s]*Especial[e]
[s]Volver al mundo real[e]
[s]Quedarse un poco m茨s[e]

[sel DUNGEON_EXIT_154_SEL top]
[s]Ir a la ciudad[e]
[s]Volver al mundo real[e]
[s]Quedarse un poco m茨s[e]

[sel DUNGEON_EXIT_155_SEL top]
[s]Ir a la ciudad[e]
[s]Volver al mundo real[e]
[s]Quedarse un poco m茨s[e]

[msg D01_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Kamoshida.[n]Buen trabajo.[n][w][e]

[msg D02_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Madarame.[n]Buen trabajo.[n][w][e]

[msg D03_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Kaneshiro.[n]Buen trabajo.[n][w][e]

[msg D04_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Futaba.[n]Buen trabajo.[n][w][e]

[msg D05_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Okumura.[n]Buen trabajo.[n][w][e]

[msg D06_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Niijima.[n]Buen trabajo.[n][w][e]

[msg D07_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Shido.[n]Buen trabajo.[n][w][e]

[msg D08_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde Mementos. Buen trabajo.[n][w][e]

[msg D10_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Maruki.[n]Buen trabajo.[n][w][e]

[msg DUNGEON_ROUTE_COMP_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Hemos asegurado un camino[n]hacia el tesoro. 夷Es que[n]quieres irte ahora?[n][w][e]

[msg DUNGEON_ROUTE_COMP_PC04_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]Solo podemos prepararnos[n]para el gran d胤a. 夷Y ahora qu姻?[n]夷Volvemos?[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ya volvemos?[n]Pero si no hemos hecho nada...[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 ocurre, Joker? Todav胤a[n]no hemos hecho nada.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Ya te quieres ir a casa?[n]Si no hemos hecho nada.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 sucede?[n]Todav胤a queda mucho por explorar.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 ocurre? 夷Quieres volver?[n]Apenas hemos hecho nada.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Nos volvemos ya?[n]Hoy no hemos hecho nada.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 ocurre, Joker?[n]No hemos llegado a hacer nada hoy.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC09 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Quieres regresar? Pero si a雨n[n]no hemos conseguido nada[n]importante en lo que llevamos aqu胤.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Volvemos ya?[n]Hoy no hemos hecho nada.[n][w][e]

[msg DUNGEON_EXIT_01_PC02_mes [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7072 65535 0]夷Qu姻 ocurre?[n]夷Quieres volver y reagruparte?[n][w][e]

[msg DUNGEON_EXIT_01_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1059 65535 0]夷Eh? 夷Quieres retirarte, Joker?[n][w][e]

[msg DUNGEON_EXIT_01_PC04_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6072 65535 0]夷Qu姻 pasa?[n]夷Quieres que lo dejemos aqu胤?[n][w][e]

[msg DUNGEON_EXIT_01_PC05_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4072 65535 0]夷Quieres que nos reunamos, Joker?[n][w][e]

[msg DUNGEON_EXIT_01_PC06_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2120 65535 0]Mmm, 夷quieres volver?[n][w][e]

[msg DUNGEON_EXIT_01_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9136 65535 0]Puede que sea buena idea[n]que nos reagrupemos.[n][w][e]

[msg DUNGEON_EXIT_01_PC08_mes [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3001 65535 0]夷Es hora de retirarse?[n][w][e]

[msg DUNGEON_EXIT_01_PC09_mes [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]夷C吋mo? 夷Nos retiramos?[n][w][e]

[msg DUNGEON_EXIT_01_PC10_mes [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57089 65535 0]夷Quieres que nos reagrupemos?[n][w][e]

[msg DUNGEON_EXIT_01_PC11_mes [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]夷C吋mo? 夷Nos retiramos?[n][w][e]

[msg ATD_EXIT_REMIND_FLOWER_V [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53101 65535 0]Jose dijo que las flores[n]desaparecen cuando sales[n]de Mementos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......[n][w][e]

[msg ATD_EXIT_REMIND_FLOWER_V_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53101 65535 0]Jose dijo que las flores[n]desaparecen cuando sales[n]de Mementos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Has recogido [clr 2][var 0][clr 27] flores[n]de momento. 夷Seguro[n]que quieres irte?[n][w][e]

[msg ATD_EXIT_REMIND_FLOWER_V_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]夷Eh? 夷Nos retiramos?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora mismo tienes [clr 2][var 0][clr 27] flores.[n]Si te vas, desaparecer茨n.[n][w][e]

[msg ATD_EXIT_CABLE_VANISHED_ [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Ya hemos hecho todo lo que[n]ten胤amos que hacer.[n]Dej姻moslo por hoy.[n][w][e]

[msg ATD_EXIT_CANCEL_CABLE_VA [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]Muy bien. Exploremos un rato m茨s.[n][w][e]

[msg D_EXIT_OK_01_PC02_mes [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7050 65535 0]Chachi, prosigamos.[n][w][e]

[msg D_EXIT_OK_01_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1049 65535 0]Mmm, dej姻moslo por hoy.[n][w][e]

[msg D_EXIT_OK_01_PC04_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6049 65535 0]V茨monos.[n][w][e]

[msg D_EXIT_OK_01_PC05_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4049 65535 0]Mmm, muy bien. Nos vamos.[n][w][e]

[msg D_EXIT_OK_01_PC06_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2049 65535 0]Vale, dej姻moslo por hoy.[n][w][e]

[msg D_EXIT_OK_01_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9050 65535 0]斡S胤胤胤, v茨monos a casa![n][w][e]

[msg D_EXIT_OK_01_PC08_mes [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3049 65535 0]Muy bien, march姻monos a casa.[n][w][e]

[msg D_EXIT_OK_01_PC09_mes [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8035 65535 0]Qu姻 buena idea. En ese caso,[n]march姻monos.[n][w][e]

[msg D_EXIT_OK_01_PC10_mes [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57066 65535 0]Entendido, 夷damos media vuelta?[n][w][e]

[msg D_EXIT_OK_01_PC11_mes [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8138 65535 0]Qu姻 buena idea. En ese caso,[n]march姻monos.[n][w][e]

[sel DUNGEON_EXIT_151_EX_SEL top]
[s]*Especial[e]
[s]Activar el [clr 6]Navegador del Metaverso[clr 27][e]
[s]No activar el navegador[e]

[msg DUNGEON_EXIT_D01_EX_mes [Ryuji]]
[s][bup 0 2 0 65535 0]Si usamos el Navegador aqu胤,[n]volveremos al mundo real.[n][w][e]

[msg D_EXIT_OK_D01_EX_mes [Ryuji]]
[s][bup 0 2 0 65535 0]斡Estupendo, ha funcionado![n][w][e]

[msg D_EXIT_NG_D01_EX_mes [Ryuji]]
[s][bup 0 2 0 65535 0]夷Qu姻 haces? 斡Hay que salir de aqu胤![n][w][e]

[msg D_EXIT_CANCEL_PC02_mes [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]Chachi, puedo seguir[n]si es eso lo que quieres.[n][w][e]

[msg D_EXIT_CANCEL_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1096 65535 0]Bueno, sigamos explorando.[n][w][e]

[msg D_EXIT_CANCEL_PC04_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6096 65535 0]Vale, vamos a echar otro vistazo[n]por esta zona.[n][w][e]

[msg D_EXIT_CANCEL_PC05_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4052 65535 0]Coincido. Seguro que quedan lugares[n]por visitar.[n][w][e]

[msg D_EXIT_CANCEL_PC06_mes [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2081 65535 0]Tienes raz吋n, sigamos.[n][w][e]

[msg D_EXIT_CANCEL_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9130 65535 0]Vale, vamos a quedarnos[n]un poquito m茨s.[n][w][e]

[msg D_EXIT_CANCEL_PC08_mes [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3051 65535 0]Mmm, bueno, pong茨monos a explorar.[n][w][e]

[msg D_EXIT_CANCEL_PC09_mes [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8070 65535 0]Vale, sigamos un poco m茨s.[n][w][e]

[msg D_EXIT_CANCEL_PC10_mes [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57163 65535 0]Vale. Solo un poquito m茨s.[n][w][e]

[msg D_EXIT_CANCEL_PC11_mes [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8137 65535 0]斡No bajes la guardia![n][w][e]

[msg ALERT_MAX_EXIT_mes00 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1039 65535 0]斡Uf, esto no mola nada! El nivel[n]de seguridad de esta zona[n]es demasiado alto![n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Nuestras vidas corren[n]peligro si nos quedamos.[n][w][e]
[s]斡Tenemos que retirarnos, Joker![n][w][e]

[msg ALERT_MAX_EXIT_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]U-un momentito.[n]Estar胤a bien que...[n][w][e]

[msg ALERT_MAX_EXIT_mes02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1082 65535 0]斡Las sombras no dejan[n]de multiplicarse! 斡Tenemos[n]que marcharnos, y r茨pido![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]斡夷Qu姻 dices, t胤o?! 斡Si ya hemos[n]mandado el aviso![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Todo nuestro trabajo[n]se va a ir a tomar por culo[n]si no robamos el tesoro hoy![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC03 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1040 65535 0]夷Qu姻? 斡夷Es que no has escuchado[n]nada de lo que te he dicho?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Si no nos llevamos el tesoro hoy,[n]todo lo que hemos logrado[n]se ir茨 por la borda![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6039 65535 0]斡Eso no va a pasar! 斡Ni de broma![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Todo nuestro plan se ir茨[n]al garete si no nos llevamos[n]el tesoro hoy mismo![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4104 65535 0]夷Quieres volver? Ja, ja, anda que[n]mira que ponerte a gastar bromas[n]en medio de una misi吋n...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En fin, sigamos con lo que[n]est茨bamos haciendo.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2043 65535 0]Venga, basta de quejas.[n]夷Es que no eres el l胤der?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Tenemos que hacernos con el tesoro[n]hoy, cueste lo que cueste![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale, volvamos a casa...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9100 65535 0]Esto, eh... que era broma.[n]Nadie se va a largar ahora.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cre胤a que no pod胤amos retirarnos[n]hasta haber enviado el aviso.[n][w][e]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3136 65535 0]斡No te preocupes, Joker![n]斡Nosotros te apoyamos![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC09 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8112 65535 0]夷Quieres abandonar ahora[n]que hemos llegado hasta aqu胤?[n]No es muy propio de ti.[n][w][e]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenemos que intentar solucionar[n]esto hoy. Tienes mi apoyo.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57118 65535 0]Pensaba que no pod胤amos volver[n]hasta que envi茨semos el aviso.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos, Joker, yo tambi姻n[n]me esforzar姻 al m茨ximo.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC11 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8018 65535 0]Hemos llegado muy lejos,[n]no podemos marcharnos ahora.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Acabemos con esto![n][w][e]

[msg SAFEROOM_EXIT_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De veras quieres irte, Joker?[n][w][e]

[msg SAFEROOM_EXIT_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷En serio nos vamos a casa, Joker?[n][w][e]

[msg D01_04_e166_015_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]Chachi, ahora solo tenemos[n]que robar el tesoro que aparezca.[n]Por fin lleg吋 el momento.[n][w][e]

[msg D01_04_e166_015_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero primero tenemos que enviar[n]el aviso. 夷Cu茨ndo lo hacemos?[n][w][e]

[msg D01_04_e166_015_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale, dej姻moslo. Retir姻monos[n]por ahora, ya trataremos m茨s[n]ese tema en el escondite.[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1030 65535 0]斡Ah, y buen trabajo![n][w][e]

[msg D02_MISSION_POINT_PC03_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1172 65535 0]Deber胤amos irnos e intentar[n]desactivar la seguridad del patio.[n][w][e]

[msg D02_04_e210_240_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7153 65535 0]Bueno, sigo preocupado...[n]pero no nos queda otra.[n][w][e]

[msg D02_04_e210_240_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4076 65535 0]No puedo ni imaginarme[n]qu姻 es el tesoro de Madarame...[n][w][e]

[msg D02_04_e210_240_mes03 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es igual, lo robaremos de todos[n]modos. 斡Ah, y hoy lo hab姻is[n]hecho de maravilla![n][w][e]

[msg D03_FIRST_END_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1172 65535 0]La puerta cognitiva est茨 cerrada.[n]夷Deber胤amos volver ya?[n][w][e]

[msg D06_FIRST_END_PC06_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2118 65535 0]Tenemos que reagruparnos[n]en el mundo real.[n][w][e]

[msg D07_FIRST_END_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]Entendido, Joker. 斡Retirada![n][w][e]

[msg D01_EXIT_NG_EV01_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ad吋nde vas, Joker?[n][w][e]
[s]Ya hemos revisado esas celdas.[n]Vamos a echarle un vistazo[n]al castillo por dentro.[n][w][e]

[msg D01_EXIT_NG_EV01_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenemos que pasar por la entrada[n]para llegar hasta all胤.[n]Pero 夷no estaba cerrada la puerta?[n][w][e]
[s]Ser茨 imposible de conseguir[n]a menos que encontremos[n]otro camino a la primera planta.[n][w][e]

[msg D07_DUNGEON_EXIT_SC_mes0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Venga, hemos llegado hasta aqu胤.[n]Al menos vamos a comprobar[n]la zona primero.[n][w][e]

[sel D_VELVET_IN_SEL top]
[s]D姻jame entrar en la celda.[e]
[s]No quiero entrar.[e]

[msg D_VELVET_IN_QUIET_01 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 0 12002 65535 0]Parece que echas de menos[n]tu prisi吋n. La soluci吋n es f茨cil...[n][w][e]

[msg D_VELVET_IN_QUIET_OK [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Muy bien, conceder姻 tu deseo[n]con much胤simo gusto...[n][w][e]

[msg D_VELVET_IN_QUIET_NO [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Contin雨a con tu sufrimiento...[n][w][e]

[msg D_VELVET_IN_LOUD_01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 ocurre, recluso?[n]夷Echas de menos la prisi吋n?[n][w][e]

[msg D_VELVET_IN_LOUD_OK [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Te voy a devolver al sitio[n]al que perteneces! 斡Je, je, je![n][w][e]

[msg D_VELVET_IN_LOUD_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sigue sufriendo, recluso.[n][w][e]

[msg D_VELVET_IN_LAST_01 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te llevar姻 hasta mi maestro...[n][w][e]

[sel D_VELVET_IN_LAST_SEL top]
[s]Quiero prepararme.[e]
[s]No quiero entrar.[e]

[msg D_VELVET_IN_LAST_OK [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entra, por favor.[n][w][e]

[msg D_VELVET_IN_LAST_NO [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Muy bien, mi maestro y yo[n]te estaremos vigilando.[n][w][e]

