[msg MSG_000_0_0 [Estudiante desenfadado]]
[s][vp 8 2 0 38702 15 0]夷En qu姻 estar胤a pensando el conductor[n]al entrar a esa velocidad[n]en la estaci吋n?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Estudiante gentil]]
[s][vp 8 0 0 0 65535 0]夷No te has enterado?[n]El t胤o perdi吋 la cabeza.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pasa mucho 雨ltimamente.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Estudiante desenfadado]]
[s][vp 8 0 0 0 65535 0]Todos estos accidentes se deben[n]a que la gente enloquece[n]de repente, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Estudiante gentil]]
[s][vp 8 2 0 38405 12 0]Bueno, con la econom胤a como est茨[n]y lo deprimentes que son siempre[n]las noticias, no me sorprende.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Universitario sin blanca]]
[s][vp 8 0 0 0 65535 0]Ojal茨 tuviera dinero. Matar胤a[n]por un desayuno de verdad...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Universitario con energ胤a]]
[s][vp 8 2 0 39104 12 0]夷Vamos al [clr 2]Big Bang Burger[clr 27]?[n]En el de la [clr 2]calle principal[clr 27][n]hay un concurso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]El desaf胤o Big Bang o algo as胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Si vas de noche, puedes cenar[n]por solo 500 yenes.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Universitario sin blanca]]
[s][vp 8 0 0 0 65535 0]Pero tienes que zamparte una[n]de esas hamburguesas gigantes[n]enterita, 夷no? 斡Es imposible![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aunque por 500 yenes... es un chollo.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1168 65535 0]夷Una hamburguesa gigante? Muy bien.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seguro que si te animas[n]mejorar茨 tu [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Universitario despreocupado]]
[s][vp 8 0 0 0 65535 0]Anoche me puse a ver[n]una serie que echaron en la tele[n]y me he enganchado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Quiero empezarla[n]desde el principio. 夷Tendr茨n en[n]alg雨n sitio la primera temporada?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Universitario superficial]]
[s][vp 8 0 0 0 65535 0]夷Y en el videoclub de la calle[n]principal? Los socios pueden[n]alquilar todos los DVD que quieran.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Universitario despreocupado]]
[s][vp 8 0 0 0 65535 0]夷S胤? La tienda es conocida,[n]as胤 que seguramente la tengan.[n]Gracias, me pasar姻 luego.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1162 65535 0]El videoclub de la calle principal...[n]Ah, ser茨 el edificio gigante[n]que hay enfrente de la librer胤a.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Poder pillar todo lo que se quiera[n]es tentador. Cuando tengamos[n]tiempo, le echamos un ojo.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Mujer perezosa]]
[s][vp 8 0 0 0 65535 0]Estos d胤as libres[n]me he rascado la barriga cosa mala...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Maquillarse es un co隠azo[n]y odio ir de compras, as胤 que suelo[n]acabar haciendo el vago en casa.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Amante de las compras]]
[s][vp 8 2 0 40000 12 0]Yo igual. Suerte que se puede[n]comprar desde casa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Siempre venden lo mejor[n]los domingos.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Mujer perezosa]]
[s][vp 8 0 0 0 65535 0]斡S胤, tienes toda la raz吋n[n]del mundo![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Hasta venden mascarillas[n]para cuando est茨s enferma.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Amante de las compras]]
[s][vp 8 0 0 0 65535 0]Ma隠ana no se me escapa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Es tan popular que siempre[n]vuela si no llamas el mismo d胤a.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Oficinista a la moda]]
[s][vp 8 2 0 37651 15 0]Hala, 夷y esas gafas?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Vas a hacer snowboard o qu姻?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Oficinista con gafas]]
[s][vp 8 0 0 0 65535 0]He o胤do que los cedros florecer茨n[n]m茨s tarde de lo habitual...[n]El cambio clim茨tico y tal y cual.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Uf, la alergia al polen es lo peor...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No podr胤a ir a la monta隠a[n]ni aunque quisiera. Los ojos[n]y la nariz me chorrear胤an a mares.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Oficinista a la moda]]
[s][vp 8 0 0 0 65535 0]Menudo panorama.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1014 65535 0]Es verdad. Dijeron en las noticias[n]que la temporada de polen[n]se retrasar胤a este a隠o.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Los problemas derivados del polen[n]acaban de empezar. Pronto, la gente[n]notar茨 el picor en los ojos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Puede que esto afecte a Mementos,[n]igual que el tiempo.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Joven p茨lido]]
[s][vp 8 2 0 39052 15 0]*suspiro* Mi trabajo es un tost吋n[n]de mucho cuidado.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Amiga joven atenta]]
[s][vp 8 0 0 0 65535 0]夷El del [clr 2]restaurante de gyuudon[n]de la calle principal[clr 27]?[n]夷No dec胤as que pagaban bien?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Tengo entendido que el pol胤tico[n]que da discursos frente[n]a la estaci吋n va por all胤 a menudo.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Si te lo montas bien,[n]es un buen contacto.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Joven p茨lido]]
[s][vp 8 0 0 0 65535 0]Quita, quita. Yo paso de pol胤tica.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]*suspiro* No quiero ir. Aunque[n]paguen bien, no me apetece[n]encargarme de todo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]En la oferta dec胤an que era[n]un lugar divertido y amigable.[n]Ojal茨 viniese alguien m茨s a currar...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]La cosa est茨 complicada...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Pero los Ladrones Fantasma tambi姻n[n]necesitan dinero. Ojea las[n][clr 2]revistas con anuncios de trabajo[clr 27].[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Oficinista joven]]
[s][vp 8 2 0 46150 15 0]Ayer vi a un famoso en Shibuya.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]El parlamentario ese de cuando[n]era un cr胤o... Toranosuke no s姻 qu姻.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Trabajador con gafas]]
[s][vp 8 0 0 0 65535 0]Ah, s胤, [clr 2]Toranosuke Yoshida[clr 27].[n]O como muchos lo llamamos,[n]或el in雨til Tora位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Va de estaci吋n en estaci吋n[n]dando discursos,[n]pero nadie le presta atenci吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Promet胤a mucho en pol胤tica, pero[n]acab吋 involucrado en un sinf胤n[n]de esc茨ndalos.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Oficinista joven]]
[s][vp 8 0 0 0 65535 0]S胤, lo vi en la cola[n]para pillar comida.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Fue raro ver a un pol胤tico[n]comiendo en el mismo lugar[n]que nosotros.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Trabajador con gafas]]
[s][vp 8 2 0 37902 12 0]Ser茨 su nueva estratagema, 夷no?[n]Caerle en gracia a la clase media.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Joven con emoci吋n]]
[s][vp 8 0 0 0 65535 0]夷Crees que los Ladrones Fantasma[n]existen de verdad?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Joven c胤nico]]
[s][vp 8 0 0 0 65535 0]夷Te refieres a la gente esa[n]que va dejando avisos?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 38155 12 0]夷De verdad te tragas la chorrada[n]esa de 或despertar corazones位[n]o como se diga?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Joven con emoci吋n]]
[s][vp 8 0 0 0 65535 0]Mira, algo hizo que aquel artista[n]confesara sus delitos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Y he o胤do que Kamoshida[n]tambi姻n recibi吋 el aviso[n]antes de entregarse.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No s姻 qu姻 se traen entre manos,[n]pero me alegro de que est姻n[n]haciendo de este un lugar mejor.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Joven c胤nico]]
[s][vp 8 0 0 0 65535 0]Bueno, si sucede de nuevo,[n]puede que me lo crea.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Mujer muy maquillada]]
[s][vp 8 0 0 0 65535 0]夷Viste ayer al estudiante detective[n]en televisi吋n?[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Se隠ora ruidosa]]
[s][vp 8 2 0 41157 12 0]夷El de aquel programa?[n]Fue espantoso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷A qui姻n se le ocurre soltar que[n]unos seres sobrenaturales est茨n[n]despertando corazones?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ese chico es un farsante.[n]Que los Ladrones Fantasma[n]existan es imposible.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Mujer muy maquillada]]
[s][vp 8 0 0 0 65535 0]Pues mis hijos se lo creen a pies[n]juntillas. Y peor a雨n, piensan[n]que el detective ese es un genio.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Los ni隠os son muy cr姻dulos como[n]para ver semejantes programas[n]en televisi吋n.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]La gente todav胤a no cree[n]que seamos reales.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Aficionado a la adivinaci吋n]]
[s][vp 8 0 0 0 65535 0]Oye, 夷te has enterado? Hay[n]una famosa [clr 2]adivina[clr 27][n]en [clr 2]Shinjuku[clr 27].[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Oficinista conocedor]]
[s][vp 8 2 0 39304 12 0]S胤, algo he le胤do sobre el tema[n]en internet. 或La preciosa[n]adivina位 o algo as胤...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Dicen que es muy buena,[n]y muchos comentan que sus[n]predicciones se hicieron realidad.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Aficionado a la adivinaci吋n]]
[s][vp 8 0 0 0 65535 0]Tambi姻n afirman que puede adivinar[n]el destino. Quiz茨s pueda decirme[n]qui姻n ser茨 mi alma gemela...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Creo que le har姻 una visita.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Conque una [clr 2]adivina en Shinjuku[clr 27].[n]夷No la vimos cuando quedamos[n]con aquella periodista?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 1168 65535 0][f 4 10 65535 0 0]Parece muy popular.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Ella misma dijo que [clr 2]iba all胤[n]por la noche[clr 27]. 夷Y si vamos a verla?[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Mujer habladora]]
[s][vp 8 2 0 37956 15 0]夷No te parecen impresionantes[n]los Ladrones Fantasma? Esta vez[n]han acabado con unos mafiosos.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Mujer esc姻ptica]]
[s][vp 8 0 0 0 65535 0]夷C吋mo? 夷Que ha sido cosa[n]de los Ladrones Fantasma?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Quiz茨 la gente est茨 de cachondeo[n]y les atribuye el m姻rito de algo[n]que solo es una coincidencia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]O sea, nadie puede despertar[n]el coraz吋n de otro.[n]Ser茨 una leyenda urbana.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Mujer habladora]]
[s][vp 8 0 0 0 65535 0]夷No es lo mismo que dijeron[n]sobre el grupo de hackers?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Solo es una forma amable de decir[n]que est茨n chantajeando a maleantes[n]para que confiesen sus delitos![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Qui姻n te crees que eres para dudar[n]de los Ladrones Fantasma?[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Mujer esc姻ptica]]
[s][vp 8 0 0 0 65535 0]夷Disculpa?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Chico impresionable]]
[s][vp 8 0 0 0 65535 0]夷Gun About: The Super Real?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Ese es el juego que tiene un mando[n]con forma de pistola?[n]Todo el mundo habla de 姻l.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Amante de los juegos]]
[s][vp 8 2 0 38104 12 0]El multijugador es la leche.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Est茨 en los recreativos de la calle[n]principal. Me paso por all胤 cuando[n]vuelvo a casa despu姻s de clase.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]El otro d胤a jugu姻[n]con alguien superbueno...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No le di ni una sola vez.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Chico impresionable]]
[s][vp 8 0 0 0 65535 0]Jo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Me gustar胤a probarlo, pero no[n]quiero que alguien tan bueno[n]me d姻 una paliza nada m茨s empezar...[n][f 1 3 65535][w][e]

[msg MND_047_0_0]
[s][vp 8 0 0 0 65535 0]Parece que hay[n]un juego nuevo en los [n][clr 2]recreativos de la calle principal[clr 27].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Quiz茨 deber胤a ir a echarle[n]un vistazo despu姻s de clase...[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Mujer despreocupada]]
[s][vp 8 2 0 43804 15 0]La gente no para de hablar[n]de 或Medjed位. 夷Qu姻 narices es eso?[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Hombre serio]]
[s][vp 8 0 0 0 65535 0]T雨 no ves mucho las noticias, 夷no?[n]Es una red internacional[n]de hacktivistas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Van a por empresas que est茨n[n]metidas en asuntos ilegales[n]y las sumen en el caos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Lo del servidor de la compa隠胤a[n]de metro? Fue Medjed intentando[n]descubrir al autor del accidente.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Mujer despreocupada]]
[s][vp 8 0 0 0 65535 0]Entonces, 夷son buena gente?[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Hombre serio]]
[s][vp 8 2 0 38155 12 0]Algunos los consideran[n]los Robin Hood digitales.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero esp胤an correos[n]y destruyen datos. No son mejores[n]que los delincuentes.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Mujer observadora]]
[s][vp 8 2 0 39351 15 0]夷Esos no son[n]estudiantes del Shujin?[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Cotilla]]
[s][vp 8 0 0 0 65535 0]He le胤do un art胤culo sobre[n]el Shujin en una revista.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]或Terror en el instituto:[n]encubrimiento en las aulas位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Al parecer, la administraci吋n hizo[n]la vista gorda ante los abusos de[n]un profesor. Es dif胤cil de creer...[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Mujer observadora]]
[s][vp 8 0 0 0 65535 0]En un principio, el director afirm吋[n]que no sab胤a nada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Estamos hablando de la vida[n]de unos ni隠os. La gente[n]como 姻l deber胤a pagar por esto.[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]La mirada que nos est茨n echando[n]no me gusta un pelo.[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Hombre joven]]
[s][vp 8 2 0 37856 15 0]Los Ladrones Fantasma[n]molan un mont吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Hasta los comentaristas[n]de televisi吋n[n]m茨s duros los alaban.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Muchos famosos hablan[n]abiertamente de ellos.[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Mujer joven]]
[s][vp 8 0 0 0 65535 0]斡Los Ladrones Fantasma luchan[n]por la gente! Sus detractores[n]viven en el pasado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]F胤jate en ese Akechi. Le est茨[n]cayendo la del pulpo[n]por lo sucedido con Medjed.[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Hombre joven]]
[s][vp 8 0 0 0 65535 0]或La justicia no puede coexistir[n]con los Ladrones Fantasma位... Mucho[n]hablar, pero no puede pillarlos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Incluso los pol胤ticos dicen[n]que son peligrosos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Bah, mienten m茨s que hablan.[n]Los Ladrones Fantasma[n]son dignos de confianza.[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]La gente se est茨 poniendo[n]de nuestro lado...[n][f 1 3 65535][w][e]

[msg MSG_060_0_0 [Oficinista encorvado]]
[s][vp 8 0 0 0 65535 0]T胤o, este lugar es un asco...[n]Mi jefe es lo peor.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 46152 15 0]Se dedica a hincharme[n]a horas extra cuando 姻l[n]sale a las cinco en punto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ojal茨 los Ladrones Fantasma[n]obrasen su magia en 姻l.[n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [Oficinista agotado]]
[s][vp 8 0 0 0 65535 0]夷Y c吋mo lo har胤an?[n]夷Despertar胤an su coraz吋n?[n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Oficinista encorvado]]
[s][vp 8 0 0 0 65535 0]Parece que te conviertes[n]en lo opuesto[n]a lo que eres normalmente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]As胤 que ser胤a m茨s abierto de mente,[n]mejor comunicador y empezar胤a[n]a tomar la iniciativa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Tan incre胤ble como el presidente[n]de Okumura Foods, b茨sicamente.[n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Oficinista encorvado]]
[s][vp 8 0 0 0 65535 0]斡Os lo suplico, Ladrones Fantasma![n]斡Por favor, cumplid mi deseo![n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [Oficinista cotilla]]
[s][vp 8 2 0 40000 15 0]夷Le has echado un vistazo[n]a la Fansite? Okumura est茨[n]en lo alto de la lista.[n][f 1 3 65535][w][e]

[msg MSG_065_0_0 [Oficinista sorprendida]]
[s][vp 8 0 0 0 65535 0]Buah, 夷el CEO de Big Bang Burger?[n]夷Y eso por qu姻?[n][f 1 3 65535][w][e]

[msg MSG_066_0_0 [Oficinista habladora]]
[s][vp 8 0 0 0 65535 0]Se dice que tratan a sus empleados[n]como la mierda.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No pagan las horas extra,[n]y el trabajo es tan duro[n]que un empleado muri吋.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Tambi姻n he o胤do que el que destroz吋[n]la entrada de la empresa[n]fue un exempleado cabreado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Corren rumores terribles[n]sobre ellos. Parece que intimidan[n]a la competencia...[n][f 1 3 65535][w][e]

[msg MSG_067_0_0 [Oficinista sorprendida]]
[s][vp 8 2 0 0 12 0]Uf, pues justo ayer com胤 all胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Nunca me plante姻 c吋mo pod胤an[n]producir tanta comida tan barata.[n]Espero que no le metan cosas raras...[n][f 1 3 65535][w][e]

[msg MSG_068_0_0 [Oficinista de mediana edad]]
[s][vp 8 2 0 43559 15 0]Los Ladrones Fantasma deben darse[n]prisa y encargarse de Okumura.[n][f 1 3 65535][w][e]

[msg MSG_069_0_0 [Auxiliar de oficina]]
[s][vp 8 0 0 0 65535 0]De 姻l y de todas las empresas[n]que explotan a sus empleados.[n][f 1 3 65535][w][e]

[msg MSG_070_0_0 [Oficinista de mediana edad]]
[s][vp 8 0 0 0 65535 0]Pues s胤, que nosotros tambi姻n[n]estamos con el agua al cuello.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Si te encargas de una,[n]te encargas de todas. Es lo justo.[n][f 1 3 65535][w][e]

[msg MSG_071_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1025 65535 0]夷Se puede saber por qu姻[n]nos meten tanta ca隠a?[n][f 1 3 65535][w][e]

[msg MSG_072_0_0 [Oficinista cansado]]
[s][vp 8 0 0 0 65535 0]夷Qu姻 crees que pasar茨[n]con Okumura Foods?[n][f 1 3 65535][w][e]

[msg MSG_073_0_0 [Trabajador con gafas]]
[s][vp 8 2 0 41352 12 0]A pesar de que han despertado[n]el coraz吋n del CEO, la imagen de[n]la compa隠胤a est茨 por los suelos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Las acciones valdr茨n nada y menos.[n][f 1 3 65535][w][e]

[msg MSG_074_0_0 [Oficinista cansado]]
[s][vp 8 0 0 0 65535 0]夷De verdad crees que Okumura[n]explotaba a sus empleados?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Hoy en d胤a, cualquier rumor[n]se extiende como la p吋lvora.[n]夷Y si era todo mentira?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]En ese caso, las verdaderas[n]v胤ctimas son los empleados.[n][f 1 3 65535][w][e]

[msg MSG_075_0_0 [Trabajador con gafas]]
[s][vp 8 0 0 0 65535 0]Nah, lo que pasaba en Okumura Foods[n]era bien sabido en la industria.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Le est茨s dando demasiadas vueltas.[n][f 1 3 65535][w][e]

[msg MSG_076_0_0 [Mujer joven]]
[s][vp 8 0 0 0 65535 0]夷Viste la rueda de prensa[n]de Okumura Foods?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 37952 15 0]Ver c吋mo se desplomaba el CEO...[n]y su expresi吋n...[n]Terrible. Fue terrible.[n][f 1 3 65535][w][e]

[msg MSG_077_0_0 [Hombre joven]]
[s][vp 8 0 0 0 65535 0]Dicen que est茨 enfermo,[n]pero que pase eso justo ahora[n]es muy raro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Casi parece planeado...[n][f 1 3 65535][w][e]

[msg MSG_078_0_0 [Mujer joven]]
[s][vp 8 0 0 0 65535 0]Crees que... 夷Crees que ha sido cosa[n]de los Ladrones Fantasma?[n][f 1 3 65535][w][e]

[msg MSG_079_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1046 65535 0]Mierda, el resultado ha sido[n]el contrario al esperado...[n]夷Qu姻 est茨 pasando?[n][f 1 3 65535][w][e]

[msg MSG_080_0_0 [Hombre de negocios enfadado]]
[s][vp 8 0 0 0 65535 0]Apuesto que mataron a Okumura[n]para dar ejemplo.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 46152 15 0]夷Por qu姻 iban a matarlo si no[n]durante una rueda de prensa?[n][f 1 3 65535][w][e]

[msg MSG_081_0_0 [Padre enfadado]]
[s][vp 8 0 0 0 65535 0]Le胤 en alg雨n sitio que Okumura[n]crio a su hija solo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Puede que no fuera el mejor presidente,[n]pero como padre me da pena...[n][f 1 3 65535][w][e]

[msg MSG_082_0_0 [Hombre de negocios enfadado]]
[s][vp 8 0 0 0 65535 0]Asesinar a una persona[n]para demostrar algo[n]es terrorismo de manual.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Como dijeron Shido y Akechi,[n]los Ladrones Fantasma[n]son una amenaza.[n][f 1 3 65535][w][e]

[msg MSG_083_0_0 [Morgana]]
[s][bup 0 3 3 0 0][vp 8 2 65535 1027 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_084_0_0 [Joven distanciado]]
[s][vp 8 2 0 39057 15 0]夷Todav胤a no han encontrado[n]a los Ladrones Fantasma?[n][f 1 3 65535][w][e]

[msg MSG_085_0_0 [Joven arrogante]]
[s][vp 8 0 0 0 65535 0]El gobierno y la polic胤a[n]son in雨tiles.[n]夷Acaso intentan hacer algo?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ojal茨 no usaran el dinero de los[n]impuestos para limpiarse el culo...[n][f 1 3 65535][w][e]

[msg MSG_086_0_0 [Joven distanciado]]
[s][vp 8 0 0 0 65535 0]Un grupo misterioso de asesinos,[n]un gobierno inepto... 夷En qu姻 se est茨[n]convirtiendo el mundo?[n][f 1 3 65535][w][e]

[msg MSG_087_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1027 65535 0]Todo el mundo habla pestes[n]de nosotros...[n][f 1 3 65535][w][e]

[msg MSG_088_0_0 [Mujer joven]]
[s][vp 8 2 0 37952 15 0]Me pregunto qu姻 le habr茨 pasado[n]a Akechi.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Iba por ah胤 jurando que los[n]Ladrones Fantasma eran malvados...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Y ahora dice que no tienen[n]nada que ver[n]con los episodios de descontrol.[n][f 1 3 65535][w][e]

[msg MSG_089_0_0 [Hombre joven]]
[s][vp 8 0 0 0 65535 0]Se habr茨 subido al carro sin m茨s.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Seguro que antes acertaba[n]de pura chiripa.[n][f 1 3 65535][w][e]

[msg MSG_090_0_0 [Mujer joven]]
[s][vp 8 0 0 0 65535 0]Pues s胤, igual no es tan bueno[n]como parec胤a, 夷verdad?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]M茨s le valdr胤a haberse mantenido[n]en sus trece.[n][f 1 3 65535][w][e]

[msg MSG_091_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1040 65535 0]Con todo lo que ha dicho y hecho,[n]vete a saber c吋mo acaba...[n][f 1 3 65535][w][e]

[msg MSG_092_0_0 [Hombre de pelo casta隠o]]
[s][vp 8 0 0 0 65535 0]Al final han puesto precio[n]a los Ladrones Fantasma...[n][f 1 3 65535][w][e]

[msg MSG_093_0_0 [Hombre de pelo negro]]
[s][vp 8 2 0 38157 12 0]A la polic胤a le ha costado[n]tomarse esto en serio.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Como dijo Shido, deber胤an[n]haberlo cortado de ra胤z.[n][f 1 3 65535][w][e]

[msg MSG_094_0_0 [Hombre de pelo casta隠o]]
[s][vp 8 0 0 0 65535 0]Aun as胤, la confianza de la gente[n]en el gobierno se ir茨 al garete[n]si no los atrapan pronto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Normal que se pongan nerviosos.[n][f 1 3 65535][w][e]

[msg MSG_095_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1040 65535 0]La hermana de Makoto[n]nos tiene a raya.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Al parecer, la presionan[n]un mont吋n desde arriba.[n][f 1 3 65535][w][e]

[msg MSG_096_0_0 [Oficinista joven]]
[s][vp 8 0 0 0 65535 0]La C茨mara Baja se ha disuelto.[n]Ha habido una ruptura interna.[n][f 1 3 65535][w][e]

[msg MSG_097_0_0 [Trabajador con gafas]]
[s][vp 8 0 0 0 65535 0]Masayoshi Shido. 畏l es la soluci吋n.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 37900 12 0]Es el 雨nico que lucha[n]por lo que est茨 bien...[n]El 雨nico que cumple su palabra.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ese es el tipo de persona que tiene[n]que liderar esta naci吋n,[n]sobre todo en momentos como estos.[n][f 1 3 65535][w][e]

[msg MSG_098_0_0 [Oficinista joven]]
[s][vp 8 0 0 0 65535 0]Shido lidera el movimiento[n]Futuro Unido, 夷verdad?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ten胤a raz吋n. Si hubi姻ramos ido a[n]por los Ladrones Fantasma desde[n]el principio, estar胤an entre rejas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Qu姻 crees que pasar茨 antes?[n]夷Que cambie el r姻gimen o que[n]arresten a los Ladrones Fantasma?[n][f 1 3 65535][w][e]

[msg MSG_099_0_0 [Morgana]]
[s][bup 0 3 0 0 0][vp 8 2 65535 1027 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_100_0_0 [Joven de pelo casta隠o]]
[s][vp 8 0 0 0 65535 0]夷Has visto la rueda de prensa[n]de Shido? Parece que los Ladrones Fantasma[n]han despertado su coraz吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No me puedo creer[n]que fuera un delincuente...[n][f 1 3 65535][w][e]

[msg MSG_101_0_0 [Joven de pelo negro]]
[s][vp 8 0 0 0 65535 0]夷Pero el l胤der de los Ladrones[n]Fantasma no se hab胤a suicidado?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ese v胤deo del 或regreso位[n]que colgaron antes[n]de las elecciones... 夷es real?[n][f 1 3 65535][w][e]

[msg MSG_102_0_0 [Joven de pelo casta隠o]]
[s][vp 8 2 0 39051 15 0]Ya no s姻 qu姻 est茨 pasando.[n]En Internet hay opiniones[n]de todos los colores.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷C吋mo afecta esto a las elecciones?[n]Este pa胤s tiene problemas.[n]Estamos sin primer ministro.[n][f 1 3 65535][w][e]

[msg MSG_103_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1027 65535 0]Ha pasado todo de repente.[n]Entiendo que la gente est姻 confusa.[n][f 1 3 65535][w][e]

[msg MSG_104_0_0 [Mujer joven]]
[s][vp 8 2 0 37952 15 0]夷Crees que el se隠or Shido[n]ha despertado de verdad?[n][f 1 3 65535][w][e]

[msg MSG_105_0_0 [Hombre joven]]
[s][vp 8 0 0 0 65535 0]Se ha hablado mucho de que si est茨[n]cansado, que si est茨 enfermo...[n]Pero vete a saber.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Adem茨s, ya le habr胤an arrestado[n]si algo de eso fuera verdad.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Estar茨 esperando a que el gobierno[n]comunique oficialmente qui姻n ser茨[n]el pr吋ximo primer ministro?[n][f 1 3 65535][w][e]

[msg MSG_106_0_0 [Mujer joven]]
[s][vp 8 0 0 0 65535 0]No s姻, hay algo raro en todo esto.[n]Aunque...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Si no hay problemas serios[n]con el se隠or Shido,[n]casi que lo prefiero a 姻l...[n][f 1 3 65535][w][e]

[msg MSG_107_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1140 65535 0]Pero vamos a ver,[n]斡si solo hay problemas![n][f 1 3 65535][w][e]

[msg MSG_108_0_0 [Oficinista de mediana edad]]
[s][vp 8 0 0 0 65535 0]夷Qu姻 pasa con Shido? 夷Alguien lo[n]ha visto desde la rueda de prensa?[n][f 1 3 65535][w][e]

[msg MSG_109_0_0 [Trabajador con gafas]]
[s][vp 8 2 0 41352 12 0]Yo esperaba mucho de 姻l...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Es inadmisible que Jap吋n[n]est姻 sin primer ministro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Espero que vuelva[n]y lidere este pa胤s...[n][f 1 3 65535][w][e]

[msg MSG_110_0_0 [Oficinista de mediana edad]]
[s][vp 8 0 0 0 65535 0]Pues s胤. La verdad es que no hay[n]nadie m茨s cualificado que Shido...[n][f 1 3 65535][w][e]

[msg MSG_111_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1190 65535 0]Pero 夷la gente se ha vuelto majara?[n]夷C吋mo pueden seguir[n]confiando en Shido?[n][f 1 3 65535][w][e]

[msg MSG_112_0_0 [Joven hambriento]]
[s][vp 8 0 0 0 65535 0]Me he levantado tarde[n]y no he comido nada...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Igual me muero de hambre, tronco...[n][f 1 3 65535][w][e]

[msg MSG_113_0_0 [Universitario con energ胤a]]
[s][vp 8 0 0 0 65535 0]Pues nos pasamos por Yon-Germain[n]antes del trasbordo en Shibuya.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Empezaron a vender[n]pastel de 茨ngel en primavera.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Est茨 que alucinas.[n]斡Un bocado resucitar胤a a un muerto![n][f 1 3 65535][w][e]

[msg MSG_114_0_0 [Joven hambriento]]
[s][vp 8 0 0 0 65535 0]En esa panader胤a est茨 todo[n]de muerte... Y los d胤as[n]de lluvia tienen ofertas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Se me hace la boca agua[n]solo de pensarlo. No le har胤a ascos[n]a ese pastel de 茨ngel...[n][f 1 3 65535][w][e]

[msg MSG_115_0_0 [Morgana]]
[s][vp 8 2 0 1133 65535 0][bup 0 3 0 0 0][f 4 10 65535 0 0]Un pastel tan bueno que resucita[n]a los muertos... 夷Quieres ir?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]La panader胤a est茨 cerca[n]del acceso a la l胤nea Ginza.[n]Alg雨n d胤a podemos pasarnos.[n][f 1 3 65535][w][e]

[msg MSG_116_0_0 [Estudiante del Shujin cotilla]]
[s][vp 8 0 0 0 65535 0]Oye, no s姻 si has visto el art胤culo[n]este que circula por internet...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Se llama 或Confesiones del chico M:[n]toda la verdad sobre el esc茨ndalo[n]de los abusos de Kamoshida位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Tiene que ser Mishima[n]por narices, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_117_0_0 [Estudiante del Shujin ruidoso]]
[s][vp 8 0 0 0 65535 0]Oh, 夷ese de Ohya? S胤, lo he visto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Es todo tan horrible...[n]No me extra隠a que consideren[n]h姻roes a los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Como para criticarlos[n]despu姻s de leer eso...[n][f 1 3 65535][w][e]

[msg MSG_118_0_0 [Estudiante del Shujin cotilla]]
[s][vp 8 0 0 0 65535 0]Es verdad. De hecho, me atrever胤a[n]a llamarlos superh姻roes.[n][f 1 3 65535][w][e]

[msg MSG_119_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Puede que esos art胤culos sean el[n]tipo de publicidad que necesitamos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Que los Ladrones Fantasma sean[n]m茨s conocidos en el mundo real[n]quiz茨 afecte a Mementos tambi姻n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Podr胤an pasar cosas buenas,[n]斡como cuando se abri吋 ese muro![n]斡Hay que aprovechar la oportunidad![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]斡Hay que ir al [clr 2]bar de Shinjuku[clr 27][n]y convencerla de que escriba[n]m茨s art胤culos sobre nosotros![n][f 1 3 65535][w][e]

[msg MSG_120_0_0 [Joven p茨lido]]
[s][vp 8 2 0 39052 15 0]*suspiro* Hoy no quiero[n]ir a trabajar...[n][f 1 3 65535][w][e]

[msg MSG_121_0_0 [Amiga joven atenta]]
[s][vp 8 0 0 0 65535 0]夷Sigues en el sitio de [clr 2]gyuudon[n]de la calle principal[clr 27]?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Cre胤a que te gustaba[n]porque pagaban bien.[n]夷Qu姻 ha pasado?[n][f 1 3 65535][w][e]

[msg MSG_122_0_0 [Joven p茨lido]]
[s][vp 8 0 0 0 65535 0]S胤, si dan mucha pasta, pero soy[n]el 雨nico en el turno de noche.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]En la oferta dec胤an que era[n]或un lugar divertido y amigable位.[n]*suspiro* Estoy por pirarme...[n][f 1 3 65535][w][e]

[msg MSG_123_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1027 65535 0]Es verdad lo que dice, el trabajo[n]puede ser duro a veces...[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero la experiencia merece la pena.[n]No hay que rendirse.[n][f 1 3 65535][w][e]

[msg MSG_124_0_0 [Alumna t胤mida]]
[s][vp 8 0 0 0 65535 0]夷Has estado alguna vez[n]en los recreativos Gigolo[n]de la calle principal?[n][f 1 3 65535][w][e]

[msg MSG_125_0_0 [Alumno en姻rgico]]
[s][vp 8 0 0 0 65535 0]夷Los recreativos Gigolo?[n]夷Los que est茨n al lado[n]de la tienda de autoservicio?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Cre胤a que el instituto prohib胤a ir[n]a los recreativos, y se comenta que[n]un delincuente merodea por la zona.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Por qu姻 preguntas?[n]夷Te apetece jugar o qu姻?[n][f 1 3 65535][w][e]

[msg MSG_126_0_0 [Alumna t胤mida]]
[s][vp 8 0 0 0 65535 0]N-no. Supuestamente venden una[n]marca extranjera de zumos[n]que ayudan a conciliar el sue隠o.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mis notas han bajado,[n]pero me da miedo el delincuente...[n][f 1 3 65535][w][e]

[msg MSG_127_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1163 65535 0]夷Por qu姻 parece que los productos[n]de fuera siempre funcionan?[n]夷Ser茨 por el sabor?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y hay un delincuente, 夷eh?[n]Seguro que no es nada[n]comparado con las sombras.[n][f 1 3 65535][w][e]

[msg MSG_128_0_0 [Alumno amante de la carne]]
[s][vp 8 0 0 0 65535 0]夷Has o胤do que ma隠ana[n]hay un festival de verano[n]en Odaiba?[n][f 1 3 65535][w][e]

[msg MSG_129_0_0 [Alumno amante de las verduras]]
[s][vp 8 0 0 0 65535 0]Un festival de verano...[n]夷C吋mo come la gente[n]tanta grasa con este calor?[n][f 1 3 65535][w][e]

[msg MSG_130_0_0 [Alumno amante de la carne]]
[s][vp 8 0 0 0 65535 0]T胤o, es que no lo pillas.[n]Comemos tanta carne precisamente[n]porque hace calor.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Vamos a verlo, anda.[n]Te invito a un pincho.[n][f 1 3 65535][w][e]

[msg MSG_131_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1163 65535 0]Un festival de verano...[n]夷Tendr茨n ternera de la buena?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Primero c姻ntrate en los finales.[n]Cuando acaben,[n]斡estaremos de vacaciones![n][f 1 3 65535][w][e]

[msg MSG_132_0_0 [Oficinista ostentoso]]
[s][vp 8 0 0 0 65535 0]Estoy pensando en dejar el trabajo.[n][f 1 3 65535][w][e]

[msg MSG_133_0_0 [Oficinista t胤mido]]
[s][vp 8 0 0 0 65535 0]斡夷Qu姻?! S姻 que nuestra empresa[n]sol胤a ser bastante turbia...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero 斡ahora estamos mucho mejor![n]夷Qu姻 ha pasado?[n][f 1 3 65535][w][e]

[msg MSG_134_0_0 [Oficinista ostentoso]]
[s][vp 8 0 0 0 65535 0]S胤, no te falta raz吋n.[n]Tampoco es que odie trabajar aqu胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero mi otro trabajo va muy bien[n]y mis acciones est茨n subiendo[n]como la espuma.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Gano bastante y apenas trabajo.[n]Viendo lo visto, trabajar[n]a tiempo completo es una tonter胤a.[n][f 1 3 65535][w][e]

[msg MSG_135_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1163 65535 0]Yo creo que puede hacer[n]lo que quiera si eso lo hace feliz,[n]pero es un poco triste.[n][f 1 3 65535][w][e]

[msg MSG_136_0_0 [Universitario emocionado]]
[s][vp 8 0 0 0 65535 0]斡Eh, adivina! 斡Por fin me han[n]concedido mi deseo![n][f 1 3 65535][w][e]

[msg MSG_137_0_0 [Universitario tranquilo]]
[s][vp 8 0 0 0 65535 0]Haz el favor de no gritar,[n]que estamos en el tren.[n]夷Qu姻 dec胤as de un deseo?[n][f 1 3 65535][w][e]

[msg MSG_138_0_0 [Universitario emocionado]]
[s][vp 8 0 0 0 65535 0]斡Han a隠adido una nueva pista[n]en las jaulas de bateo[n]de Yongen-Jaya![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Es alucinante! Nunca me habr胤a[n]imaginado que...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Oye, 夷por qu姻 me miras as胤?[n]Echemos un vistazo[n]de camino a casa.[n][f 1 3 65535][w][e]

[msg MSG_139_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]夷Una nueva pista?[n]Parec胤a bastante ilusionado.[n][f 1 3 65535][w][e]

[msg MSG_140_0_0 [Oficinista con seriedad]]
[s][vp 8 0 0 0 65535 0]斡La semana pasada fui al estanque![n]Al de Ichigaya, digo.[n][f 1 3 65535][w][e]

[msg MSG_141_0_0 [Oficinista pausado]]
[s][vp 8 0 0 0 65535 0]Pues no lo conoc胤a.[n]夷Es que te gusta pescar?[n][f 1 3 65535][w][e]

[msg MSG_142_0_0 [Oficinista con seriedad]]
[s][vp 8 0 0 0 65535 0]夷No lo sab胤as?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Bueno, los estaba sacando[n]con mi t姻cnica habitual.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero de repente, vi la sombra[n]de un pez enorme. Habr胤a sido[n]un gran adversario, pero escap吋.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Hice bien en ir cuando nevaba,[n]斡aunque hiciera fr胤o! Eh, 夷me est茨s[n]haciendo caso? Deja el tel姻fono.[n][f 1 3 65535][w][e]

[msg MSG_143_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]Pescar cuando nieva... Hace falta[n]coraje. Deber胤as intentarlo[n]alguna vez si te apetece.[n][f 1 3 65535][w][e]

[msg MSG_144_0_0 [Universitario despreocupado]]
[s][vp 8 0 0 0 65535 0]Anoche me puse a ver[n]una serie que echaron en la tele[n]y me he enganchado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Quiero empezarla[n]desde el principio. 夷Tendr茨n en[n]alg雨n sitio la primera temporada?[n][f 1 3 65535][w][e]

[msg MSG_145_0_0 [Universitario superficial]]
[s][vp 8 0 0 0 65535 0]夷Y en el videoclub de la calle[n]principal? Los socios pueden[n]alquilar todos los DVD que quieran.[n][f 1 3 65535][w][e]

[msg MSG_146_0_0 [Universitario despreocupado]]
[s][vp 8 0 0 0 65535 0]夷S胤? La tienda es conocida,[n]as胤 que seguramente la tengan.[n]Gracias, me pasar姻 luego.[n][f 1 3 65535][w][e]

[msg MSG_147_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1162 65535 0]El videoclub de la calle principal...[n]Ah, ser茨 el edificio gigante[n]que hay enfrente de la librer胤a.[n][f 1 3 65535][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1067 65535 0]T雨 eres socio, 夷no?[n]Pues habr茨 que aprovechar.[n]斡Ya alquilaremos algo m茨s adelante![n][f 1 3 65535][w][e]

