[msg MSG_000_0_0 [Estudiante de primer a隠o insatisfecho]]
[s][vp 8 0 0 1 4 0]Vaya mierda. Acabamos de empezar[n]el instituto y ya nos hacen[n]jugar un torneo de voleibol.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 4 0]夷Y por qu姻 nos ponen[n]contra un equipo de profesores? [n]Kamoshida nos va a dar una paliza.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Estudiante de primer a隠o gregario]]
[s][vp 8 0 0 3 5 0]Bueno, vamos a ver c吋mo se le da[n]en persona. 斡Es superguay![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Estudiante de primer a隠o insatisfecho]]
[s][vp 8 0 0 4 4 0]S胤, bueno, te van a dar[n]con la pelota en la cara.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 5 4 0]F胤jate en lo destrozados[n]que est茨n los del equipo.[n]夷Qu姻 har茨n cuando entrenan?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Amante de la moda]]
[s][vp 8 2 0 39602 4 0]Puf, me he gastado demasiado[n]en ropa nueva este mes.[n]No tengo un duro.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Chica de aspecto maduro]]
[s][vp 8 0 0 0 5 0]Ponte a trabajar. Las [clr 2]revistas[n]con anuncios de trabajo[clr 27][n]de la estaci吋n son 雨tiles.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Amante de la moda]]
[s][vp 8 0 0 0 4 0]Quiz茨 me pase por el[n][clr 2]metro de Shibuya[clr 27][n]y coja una despu姻s de clase.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Pero el trabajo es para perdedores.[n]A ver si encuentro algo f茨cil.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Tipo de aspecto somnoliento]]
[s][vp 8 2 0 46252 4 0]*bostezo* Los lunes me dan pereza...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Por qu姻 no ponen hoy fiesta[n]tambi姻n? A partir de[n]ma隠ana tenemos la semana libre.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Tipo de aspecto serio]]
[s][vp 8 0 0 0 5 0]S胤, menuda tonter胤a. Oye, 夷qu姻 ha[n]pasado con el aviso?[n]El que le enviaron a Kamoshida.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]夷No pon胤a que iban a robar[n]sus deseos distorsionados[n]o algo por el estilo?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Tipo de aspecto somnoliento]]
[s][vp 8 0 0 0 4 0]S胤, algo as胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Seguro que es una broma.[n]Nadie se lo toma en serio.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Tipo serio]]
[s][vp 8 2 0 37554 4 0]Dicen que el consejo estudiantil[n]va tras el que dej吋 el aviso.[n]Con los ex茨menes aqu胤, vaya locura.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Estudiante de tercer a隠o optimista]]
[s][vp 8 0 0 0 5 0]Ni me acordaba de los ex茨menes.[n]No he estudiado nada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]夷Quieres que estudiemos en grupo?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Tipo serio]]
[s][vp 8 0 0 0 4 0]T雨 solo quieres copiarme[n]los apuntes, 夷eh?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0][f 1 5]Estudiante de tercer a隠o optimista[n]夷C吋mo?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]斡Los amigos de verdad se equilibran[n]las debilidades mutuamente![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Jugadora de voleibol nerviosa]]
[s][vp 8 0 0 0 4 0]Es incre胤ble que Suzui faltara a la[n]reuni吋n, con lo importante que era.[n]夷Qu姻 habr茨 pasado?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Jugadora de voleibol preocupada]]
[s][vp 8 0 0 0 5 0]Kamoshida dijo que quer胤a verla.[n]Se rumorea que se han estado[n]quedando hasta tarde...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Jugadora de voleibol nerviosa]]
[s][vp 8 0 0 0 4 0]Me pregunto qu姻 ocurrir茨...[n]夷Crees que est茨n...?[n][f 1 3 65535][w][e]
[s][f 1 5]Jugadora de voleibol preocupada[n][vp 8 0 0 0 5 0]No, imposible.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]郁ltimamente solo hay malas[n]noticias. Me preocupa el futuro...[n][f 1 3 65535][w][e]
[s][f 1 5]Jugadora de voleibol nerviosa[n][vp 8 0 0 0 4 0]Ah, por cierto, hoy viene[n]un invitado al instituto.[n]Es un chico joven, creo.[n][f 1 3 65535][w][e]
[s][f 1 5]Jugadora de voleibol preocupada[n][vp 8 0 0 0 5 0]夷Ah, s胤? Cu姻ntamelo todo.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Chica emocionada]]
[s][vp 8 0 0 0 4 0]夷Viste a Kamoshida jugar ayer?[n]斡Estuvo incre胤ble![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Creo que le voy a pedir[n]un aut吋grafo despu姻s de clase.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Chica nerviosa]]
[s][vp 8 0 0 0 5 0]No s姻 si es muy buena idea... Dicen[n]que nadie deber胤a acercarse[n]al despacho de Educaci吋n F胤sica.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Me han dicho que se oyen[n]ruidos raros, como gritos,[n]aunque no haya nadie...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Chica emocionada]]
[s][vp 8 0 0 0 4 0]夷Qu姻? Seguramente sea[n]un rumor que se han inventado[n]para asustar a la competencia.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Chica ostentosa]]
[s][vp 8 0 0 0 4 0]Todas las tiendas est茨n[n]sacando la ropa de verano.[n]Tengo que empezar a ahorrar.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Chica de aspecto maduro]]
[s][vp 8 0 0 0 5 0]Seguro que hay alg雨n trabajo[n]a tiempo parcial que te vaya bien.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Si puedes elegir,[n]qu姻date con el mejor pagado.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Chica ostentosa]]
[s][vp 8 0 0 0 4 0]Pero lo que mejor pagan[n]son los turnos de noche, 夷no?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Vamos, los curros[n]que son m茨s dif胤ciles.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Estudiante de tercer a隠o optimista]]
[s][vp 8 0 0 0 4 0]Han metido hasta al consejo[n]estudiantil en el ajo porque no[n]encuentran al que envi吋 el aviso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Pero Kamoshida lo estaba haciendo[n]de pena. Sinceramente, el que lo[n]enviara se merece una recompensa.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Estudiante de tercer a隠o serio]]
[s][vp 8 0 0 0 5 0]Tonter胤as. Esto ha destrozado[n]nuestra reputaci吋n. 夷Y si afecta[n]a los ex茨menes de acceso a la uni?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]A todo esto, 夷has estudiado?[n]Es dif胤cil concentrarse[n]con todo lo que est茨 pasando.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Estudiante de tercer a隠o optimista]]
[s][vp 8 0 0 0 4 0]Calla, calla. No me creo[n]que los parciales empiecen ma隠ana.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Ir姻 a la [clr 2]biblioteca[clr 27][n]despu姻s de clase.[n]All胤 es m茨s f茨cil estudiar.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Chica curiosa]]
[s][vp 8 2 0 42953 4 0]Ayer estabas en la librer胤a, 夷no?[n]Pens姻 en saludarte,[n]pero parec胤as ocupada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Qu姻 estabas leyendo?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Chica tratable]]
[s][vp 8 0 0 0 5 0][clr 2]或Shogi para principiantes位[clr 27].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Suspend胤 los ex茨menes,[n]as胤 que pens姻 que leer algo[n]complicado me ayudar胤a.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Chica curiosa]]
[s][vp 8 0 0 0 4 0]Bueno, en el shogi hay que pensar,[n]pero 夷no crees que[n]te has equivocado de tema? [n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Tipo moderno]]
[s][vp 8 2 0 40152 4 0]夷Un videojuego antiguo?[n]夷Por qu姻 quieres algo as胤?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Con la de juegos gratis que hay...[n]Solo se necesita un m吋vil.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Jugador]]
[s][vp 8 0 0 0 5 0]夷No te gustan los juegos retro?[n]Pues vaya.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Los efectos de sonido baratos[n]y los gr茨ficos pixelados dejan[n]mucho m茨s a la imaginaci吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Cuando uno sucumbe a su encanto,[n]es dif胤cil volver a los modernos. [n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Tipo moderno]]
[s][vp 8 0 0 0 4 0]Bueno, vas a pasarlo mal buscando[n]con tantos entusiastas [n]mirando a la vez.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]A no ser que alguien[n]deje los suyos.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Estudiante iniciado en moda]]
[s][vp 8 2 0 41900 4 0]夷Podemos pasarnos[n]por la librer胤a de camino a casa?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Alumno]]
[s][vp 8 0 0 0 5 0]Claro. A ver si adivino...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Estudiante iniciado en moda]]
[s][vp 8 0 0 0 4 0]Exacto, ya ha salido[n]el nuevo libro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]斡[clr 2]或Lector a la 雨ltima 2位[clr 27]![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]斡Con 姻l, al fin dejar姻 de ser[n]un novato en esto de la moda![n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Tipo de aspecto energ姻tico]]
[s][vp 8 2 0 38700 4 0]斡Est茨s m茨s blanco que la leche,[n]t胤o! 斡D姻jate de mangas cortas![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [T胤o p茨lido]]
[s][vp 8 0 0 0 5 0]斡Que te calles, plasta! Por cierto,[n]夷viste las noticias ayer?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Hay que ver, ese artista famoso[n]estaba llorando como un cr胤o[n]por las obras que rob吋...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Si no recuerdo mal,[n]夷no pas吋 lo mismo con Kamoshida?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Ambos recibieron avisos extra隠os...[n]En mi opini吋n, todo ha sido obra[n]de la misma persona.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Tipo de aspecto energ姻tico]]
[s][vp 8 0 0 0 4 0]En los informativos matinales[n]dijeron que los avisos los envi吋 un[n]grupo llamado [f 4 28].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Me pregunto c吋mo hacen que la gente[n]confiese. Es imposible que vayan[n]por ah胤 或despertando corazones位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Los habr茨n chantajeado?[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Chica amante de los rumores]]
[s][vp 8 2 0 43201 4 0]Kawakami ya ni se esfuerza[n]en ocultar que est茨 reventada.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Chica l茨nguida]]
[s][vp 8 0 0 0 5 0]Intenta taparse la cara con el[n]libro cuando bosteza, pero de poco[n]le sirve. Todo el mundo lo sabe.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Chica amante de los rumores]]
[s][vp 8 0 0 0 4 0]Y tambi姻n se maquilla las ojeras.[n]Adem茨s, se va derechita a casa[n]despu姻s de clase.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Y si sale de juerga cada noche?[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Chica delicada]]
[s][vp 8 2 0 40454 4 0]Oye, 夷crees que el aviso[n]de la exposici吋n de Madarame...?[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Chica amante de los rumores]]
[s][vp 8 2 0 40604 5 0]S胤, es clavado al que[n]le enviaron a Kamoshida.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]En internet dicen que fue cosa[n]de los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 40603 5 0]Hay una Fansite con un mont吋n[n]de solicitudes.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Chica delicada]]
[s][vp 8 2 0 40450 4 0]No puedo creer que haya[n]superh姻roes en la vida real.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Ha ocurrido dos veces, as胤 que tal[n]vez suceda una tercera. Tengo ganas[n]de ver qui姻n es el siguiente.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Tipo sudoroso]]
[s][vp 8 2 0 42202 4 0]Pero qu姻 calooor...[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Tipo tranquilo]]
[s][vp 8 2 0 42655 5 0]夷Has o胤do las noticias[n]esta ma隠ana? Han detenido[n]a un jefe de la mafia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Al parecer, alguien estuvo dejando[n]avisos por Shibuya[n]justo antes del arresto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]夷Recuerdas el caso de Kamoshida?[n]Dicen que ha sido igualito,[n]que alguien envi吋 un aviso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Y lo mismo con Madarame,[n]si no me equivoco.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Tipo sudoroso]]
[s][vp 8 0 0 0 4 0]夷Crees que han sido[n]los Ladrones Fantasma?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Si es as胤, estoy impresionado.[n]斡No puedo creer que despierten[n]corazones de verdad![n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Tipo con energ胤a]]
[s][vp 8 2 0 42206 4 0]Me encanta que los Ladrones[n]Fantasma salgan en las noticias.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Tipo desenfadado]]
[s][vp 8 0 0 0 5 0]S胤, se han vuelto muy populares[n]desde lo de Kamoshida.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]斡Y pensar que su leyenda empez吋[n]en nuestro instituto! 斡Es como si[n]form茨ramos parte del grupo![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Tipo con energ胤a]]
[s][vp 8 0 0 0 4 0]夷Y a qui姻n le puede parecer[n]mal lo que hacen?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]La polic胤a deber胤a aprender c吋mo se[n]castiga a esos adultos corruptos.[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Estudiante con cara de aburrimiento]]
[s][vp 8 2 0 39505 4 0]No ha habido noticias[n]del enfrentamiento entre[n]los Ladrones Fantasma y Medjed.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Qui姻n se alzar茨 victorioso?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Ambos son pandas de criminales[n]jugando a ser h姻roes.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Estudiante de aspecto ap茨tico]]
[s][vp 8 0 0 0 5 0]Pues yo creo que Medjed[n]da muchos m茨s problemas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Atacan a toda empresa[n]que se les ponga por delante.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Estudiante con cara de aburrimiento]]
[s][vp 8 0 0 0 4 0]Ya...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Tan solo espero que haya acci吋n[n]pronto. Pero dime, 夷qui姻n crees[n]que ganar茨?[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Estudiante con cara de aburrimiento]]
[s][vp 8 2 0 38710 4 0]No me puedo creer que deba[n]ir a clases de verano...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Es cierto que va a pasar un tif吋n?[n]Puede que las cancelen por eso.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Estudiante de aspecto ap茨tico]]
[s][vp 8 0 0 0 5 0]Pasar茨 ma隠ana por la regi吋n[n]de Kanto, pero de noche.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Estudiante con cara de aburrimiento]]
[s][vp 8 0 0 0 4 0]C吋mo no... Y por si fuera poco,[n]todav胤a no hay noticias[n]de los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Supongo que lo tecnol吋gico se[n]ha impuesto a lo sobrenatural.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Chica propensa a preocuparse]]
[s][vp 8 2 0 42910 4 0]El tif吋n llega esta noche, 夷no?[n]Espero poder volver a casa,[n]que ya tardo mucho con la l胤nea JL.[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Chica alegre]]
[s][vp 8 0 0 0 5 0]En las noticias dicen que alcanzar茨[n]el punto 茨lgido por la noche.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]夷Y has visto la declaraci吋n[n]de Medjed? Lo de que solo quieren[n]acciones. Menuda decepci吋n.[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Chica propensa a preocuparse]]
[s][vp 8 0 0 0 4 0]No s姻 qui姻n est茨 en lo correcto,[n]pero una cosa tengo clara...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Las verdaderas v胤ctimas[n]no ser茨n los Ladrones Fantasma,[n]sino nosotros, la gente normal.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Menudo engorro...[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Estudiante de aspecto somnoliento]]
[s][vp 8 2 0 38702 4 0]Menuda movida el vendaval de ayer.[n]Lo primero que hice por la ma隠ana[n]fue limpiar la puerta de mi casa.[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Estudiante sin preocupaciones]]
[s][vp 8 0 0 0 5 0]Sal胤 bajo la lluvia y pos姻[n]como Featherman.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]夷Quieres ver la foto?[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Estudiante de aspecto somnoliento]]
[s][vp 8 0 0 0 4 0]Espero que no la colgaras[n]en internet.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]A la gente le llueven[n]las cr胤ticas por hacer el capullo[n]durante la tormenta.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Parece que hoy toca[n]hablar solo del tif吋n.[n][f 1 3 65535][w][e]

[msg MSG_060_0_0 [Chica de tercer a隠o]]
[s][vp 8 2 0 42953 4 0]斡Es el 雨ltimo d胤a de las clases[n]de verano! 斡Al fin puedo disfrutar[n]de las vacaciones![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Pero la academia de verano[n]empieza la semana que viene...[n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [Tipo de tercer a隠o]]
[s][vp 8 0 0 0 5 0]Incre胤ble, ya es verano.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]夷Qu姻 ha pasado entre Medjed[n]y los Ladrones Fantasma?[n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Chica de tercer a隠o]]
[s][vp 8 0 0 0 4 0]A saber. Pero 夷a qui姻n le importa?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Solo dan problemas,[n]y en internet no paran[n]de hablar de ellos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Los que comentan para decir[n]sandeces son gilipollas.[n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Estudiante de aspecto ap茨tico]]
[s][vp 8 2 0 37852 4 0]No puedo creer que ya empiecen[n]las clases de nuevo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Aunque no hice nada durante[n]las vacaciones, salvo estar en casa[n]jugando en el ordenador.[n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [Estudiante vivaracho]]
[s][vp 8 2 0 38406 4 0]Pero 斡nada de lo que hicieras[n]este verano habr胤a llegado al nivel[n]de lo de los Ladrones Fantasma![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Hackear Medjed y todo lo dem茨s...[n]斡Ha sido brutal![n][f 1 3 65535][w][e]

[msg MSG_065_0_0 [Estudiante de aspecto ap茨tico]]
[s][vp 8 0 0 0 4 0]Todos en internet esperaban[n]la llegada de la fecha l胤mite.[n]Les encantan los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Y has visto[n]la Fansite 雨ltimamente?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Han a隠adido un huevo de cosas,[n]incluso la opci吋n de votar a gente[n]a la que despertar el coraz吋n.[n][f 1 3 65535][w][e]

[msg MSG_066_0_0 [Tipo de pelo negro]]
[s][vp 8 2 0 38701 4 0]Ojal茨 despertasen[n]el coraz吋n del director.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Sab胤a todo lo de Kamoshida, pero[n]bien que se lo call吋. Es rid胤culo.[n][f 1 3 65535][w][e]

[msg MSG_067_0_0 [Chico de pelo casta隠o]]
[s][vp 8 0 0 0 5 0]Pues vamos a votarlo en la Fansite.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Dudo que los Ladrones Fantasma no[n]persigan a alguien as胤 de podrido.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Fijo que otros profesores tambi姻n[n]lo sab胤an. Todos ellos se merecen[n]que les despierten el coraz吋n.[n][f 1 3 65535][w][e]

[msg MSG_068_0_0 [Tipo de pelo negro]]
[s][vp 8 0 0 0 4 0]Ya... 斡No, espera![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Y si eso nos chafa[n]el viaje escolar?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Creo que ser茨 mejor[n]esperar hasta despu姻s.[n][f 1 3 65535][w][e]

[msg MSG_069_0_0 [Seguidora de modas]]
[s][vp 8 2 0 42804 4 0]斡Mira este s茨ndwich de chocolate[n]de los Ladrones Fantasma! 斡Lo vi[n]en Shibuya y no pude contenerme![n][f 1 3 65535][w][e]

[msg MSG_070_0_0 [Chica amistosa]]
[s][vp 8 0 0 0 5 0]Viene con una pegatina, 夷no? S胤 que[n]han salido productos de los[n]Ladrones Fantasma de repente.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Pero eso de 或Ladrones Fantasma位[n]no me parece un buen nombre.[n][f 1 3 65535][w][e]

[msg MSG_071_0_0 [Seguidora de modas]]
[s][vp 8 0 0 0 4 0]No s姻, a m胤 me gusta.[n]Es como muy misterioso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Te parece mala idea que ponga[n]mi nombre en la Fansite para[n]que despierten mi coraz吋n?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Tengo unas ganas de conocerlos[n]en persona...[n][f 1 3 65535][w][e]

[msg MSG_072_0_0 [Alumna]]
[s][vp 8 2 0 42352 4 0]夷De verdad ha muerto el director?[n]He o胤do que tuvo un accidente.[n][f 1 3 65535][w][e]

[msg MSG_073_0_0 [Alumno]]
[s][vp 8 0 0 0 5 0]Tengo entendido que se suicid吋[n]tras salir en la revista que cubri吋[n]el esc茨ndalo de Kamoshida.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Sabiendo que estaba al tanto[n]de lo que pasaba,[n]yo creo que se lo merec胤a.[n][f 1 3 65535][w][e]

[msg MSG_074_0_0 [Alumna]]
[s][vp 8 0 0 0 4 0]Ya, pero tanto como para morir...[n][f 1 3 65535][w][e]

[msg MSG_075_0_0 [Simpatizante de los Ladrones Fantasma]]
[s][vp 8 2 0 42506 4 0]No me trago que la muerte del[n]director fuera un accidente. Habr茨[n]sido cosa de los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_076_0_0 [Tipo con cara de preocupaci吋n]]
[s][vp 8 0 0 0 5 0]夷Crees que fueron ellos los que[n]lo mataron? 夷Por qu姻?[n][f 1 3 65535][w][e]

[msg MSG_077_0_0 [Simpatizante de los Ladrones Fantasma]]
[s][vp 8 0 0 0 4 0]Piensa en las v胤ctimas[n]de Kamoshida. El director es igual[n]de culpable por call茨rselo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]La gente que se aprovecha[n]de los dem茨s para sacar[n]beneficio deber胤a desaparecer.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Es m茨s, alguien deber胤a eliminar[n]a todos esos mierdas[n]para purificar el mundo.[n][f 1 3 65535][w][e]

[msg MSG_078_0_0 [Deportista]]
[s][vp 8 2 0 42650 4 0]Vamos a comer despu姻s de clase.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Tengo cupones del Big Bang Burger,[n]pero... supongo que no[n]deber胤amos volver, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_079_0_0 [Tipo muy nervioso]]
[s][vp 8 0 0 0 5 0]Paso. He o胤do que te da un episodio[n]de descontrol si comes ah胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]夷No murieron los rivales de Okumura[n]en circunstancias extra隠as?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Puede que les diera hamburguesas[n]envenenadas. Menudo desgraciado.[n][f 1 3 65535][w][e]

[msg MSG_080_0_0 [Deportista]]
[s][vp 8 0 0 0 4 0]Yo he votado a Okumura[n]en la Fansite...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]El deber de los Ladrones Fantasma[n]es castigar a los malos. Espero[n]que se encarguen pronto de 姻l.[n][f 1 3 65535][w][e]

[msg MSG_081_0_0 [Seguidora de modas]]
[s][vp 8 2 0 40250 4 0]夷Y ese olor? 夷Es un perfume nuevo?[n]Qu姻 agradable.[n][f 1 3 65535][w][e]

[msg MSG_082_0_0 [Aficionada de los Fantasma]]
[s][vp 8 0 0 0 5 0]S胤, es una nueva fragancia oto隠al.[n]Se supone que es misteriosa,[n]como los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Quer胤a mostrarles mi apoyo[n]por ir a por esa empresa[n]tan malvada.[n][f 1 3 65535][w][e]

[msg MSG_083_0_0 [Seguidora de modas]]
[s][vp 8 0 0 0 4 0]夷Mostrarles tu apoyo? Pues yo[n]podr胤a colgar una foto de todos[n]los productos que he comprado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Seguro que ver la pasi吋n[n]de sus fans les motiva.[n][f 1 3 65535][w][e]

[msg MSG_084_0_0 [Fantasmafan]]
[s][vp 8 2 0 42706 4 0]夷Crees que los Ladrones Fantasma[n]le har茨n a ese presidente[n]lo mismo que al director?[n][f 1 3 65535][w][e]

[msg MSG_085_0_0 [Tipo ligeramente horrorizado]]
[s][vp 8 0 0 0 5 0]Venga ya, 夷c吋mo van a matarlo?[n]Adem茨s, estoy convencido[n]de que el director se suicid吋.[n][f 1 3 65535][w][e]

[msg MSG_086_0_0 [Fantasmafan]]
[s][vp 8 0 0 0 4 0]斡Qu姻 va, fueron ellos,[n]a modo de mensaje![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]或Gente, despertad. 斡Es hora[n]de redimirse!位 O algo as胤, vaya.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Matar胤a por tener un poder as胤...[n][f 1 3 65535][w][e]

[msg MSG_087_0_0 [Estudiante emocionado]]
[s][vp 8 2 0 38704 4 0]夷Lo has o胤do? 斡Okumura ha muerto![n]斡Ha salido en todas las noticias![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Se desplom吋 durante la rueda[n]de prensa. Ojal茨 lo hubiese visto.[n][f 1 3 65535][w][e]

[msg MSG_088_0_0 [T胤o descorazonado]]
[s][vp 8 0 0 0 5 0]Si no lo viste, mejor para ti.[n]Fue terrible, la verdad.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Nunca pens姻 que ver un ataque[n]al coraz吋n fuese tan perturbador...[n][f 1 3 65535][w][e]

[msg MSG_089_0_0 [Estudiante emocionado]]
[s][vp 8 0 0 0 4 0]En las noticias dicen que fue[n]por una enfermedad, pero[n]夷t雨 te lo crees? Es muy raro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Mierda, me hubiera[n]gustado estar all胤.[n][f 1 3 65535][w][e]

[msg MSG_090_0_0 [Chica de pelo corto]]
[s][vp 8 2 0 37704 4 0]夷Es cierto que ha venido la poli?[n][f 1 3 65535][w][e]

[msg MSG_091_0_0 [Chica de pelo largo]]
[s][vp 8 0 0 0 5 0]S胤. Est茨n intentando relacionar[n]lo sucedido con el director[n]con los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Y he o胤do que est茨n hablando[n]con estudiantes.[n][f 1 3 65535][w][e]

[msg MSG_092_0_0 [Chica de pelo corto]]
[s][vp 8 0 0 0 4 0]Entonces, 夷es una investigaci吋n[n]en toda regla? 斡Qu姻 locur吋n![n][f 1 3 65535][w][e]

[msg MSG_093_0_0 [Tipo con cara de preocupaci吋n]]
[s][vp 8 2 0 38405 4 0]Me qued姻 helado cuando los agentes[n]vinieron a hablar conmigo.[n]Fijo que ahora sospechan de m胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Cu茨nto tiempo van[n]a estar con esto?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Deber胤amos estar a tope preparando[n]el festival escolar.[n][f 1 3 65535][w][e]

[msg MSG_094_0_0 [Tipo con mirada penetrante]]
[s][vp 8 0 0 0 5 0]夷Por qu姻 ha decidido el instituto[n]celebrar el festival tan tarde?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]No entiendo que se cambie[n]la fecha solo porque salgamos[n]en las noticias.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]斡Pasarlo al pr吋ximo martes[n]solo nos da m茨s trabajo![n][f 1 3 65535][w][e]

[msg MSG_095_0_0 [Tipo con cara de preocupaci吋n]]
[s][vp 8 0 0 0 4 0]No podremos invitar a estudiantes[n]de otros centros ahora que[n]lo hacemos entre semana.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Y ser茨 un problema para los que[n]ya estaban invitados, claro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Y qu姻 hay de la fiesta de despu姻s[n]del festival? 夷Vendr茨[n]gente suficiente a la ceremonia?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]*suspiro* Los 茨nimos estar茨n[n]por los suelos. Va a ser rar胤simo.[n][f 1 3 65535][w][e]

[msg MSG_096_0_0 [Seguidora de modas]]
[s][vp 8 2 0 40602 4 0]夷Qu姻 le pasa a Akechi?[n]夷Por qu姻 ha parado de inculpar[n]a Ladrones Fantasma?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Ten胤a ganas de un enfrentamiento[n]a gran escala entre ellos.[n][f 1 3 65535][w][e]

[msg MSG_097_0_0 [Chica apacible]]
[s][vp 8 0 0 0 5 0]Solo quer胤a llevarles la contraria.[n]A no ser...[n][f 1 3 65535][w][e]

[msg MSG_098_0_0 [Seguidora de modas]]
[s][vp 8 0 0 0 4 0]A no ser...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Y si los Ladrones Fantasma[n]han despertado su coraz吋n?[n][f 1 3 65535][w][e]

[msg MSG_099_0_0 [Tipo muy emocionado]]
[s][vp 8 2 0 37850 4 0]斡Qu姻 pedazo de recompensa![n]斡Deber胤amos buscar a los Ladrones[n]Fantasma nosotros mismos![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Akechi insinu吋 que ven胤an[n]a este instituto, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_100_0_0 [T胤o p茨lido]]
[s][vp 8 0 0 0 5 0]S胤, pero... mejor no. Ya ha habido[n]demasiadas desconexiones mentales.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Es posible que acaben con nosotros[n]si metemos las narices.[n][f 1 3 65535][w][e]

[msg MSG_101_0_0 [Tipo muy emocionado]]
[s][vp 8 0 0 0 4 0]Que son 30 millones de yenes...[n]D姻jame so隠ar despierto, anda.[n][f 1 3 65535][w][e]

[msg MSG_102_0_0 [Alumna]]
[s][vp 8 2 0 39954 4 0]Ah, y Akechi dijo que se imaginaba[n]qui姻nes eran los Ladrones Fantasma.[n]夷Se ha sabido algo m茨s del tema?[n][f 1 3 65535][w][e]

[msg MSG_103_0_0 [Alumno]]
[s][vp 8 0 0 0 5 0]No puedo creer que no haya[n]soltado prenda despu姻s de todo[n]lo que ha pasado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Se habr茨 marcado una trola[n]para encandilar a la gente[n]como orador.[n][f 1 3 65535][w][e]

[msg MSG_104_0_0 [Alumna]]
[s][vp 8 0 0 0 4 0]夷T雨 crees?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]No s姻, puede que solo quiera[n]la recompensa para 姻l solito.[n][f 1 3 65535][w][e]

[msg MSG_105_0_0 [Tipo curioso]]
[s][vp 8 2 0 42655 4 0]Me pregunto qu姻 clase de persona[n]es en realidad ese Ladr吋n Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_106_0_0 [Tipo evasivo]]
[s][vp 8 0 0 0 5 0]Ha estado oculto todo este tiempo,[n]y todo lo que sabemos es que[n]parece un tipo normal.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Incluso puede que sea similar a ti.[n][f 1 3 65535][w][e]

[msg MSG_107_0_0 [Tipo curioso]]
[s][vp 8 0 0 0 4 0]Claro, como t雨 tienes[n]un estilo tan exc姻ntrico...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]No, ahora en serio.[n]Es cuesti吋n de tiempo[n]que la polic胤a atrape a ese t胤o.[n][f 1 3 65535][w][e]

[msg MSG_108_0_0 [Tipo esc姻ptico]]
[s][vp 8 2 0 42553 4 0]夷No es un poco raro[n]que Okumura sea el m茨s votado[n]en la Fansite?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Quiero decir, habr茨 miles[n]de empresas m茨s que har茨n lo mismo.[n][f 1 3 65535][w][e]

[msg MSG_109_0_0 [Tipo evasivo]]
[s][vp 8 0 0 0 5 0]夷Ser茨 que le habr茨n hecho la cruz[n]por todos los elogios que recibe?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Adem茨s, est茨n empezando a surgir[n]un huevo de rumores raros[n]sobre su empresa...[n][f 1 3 65535][w][e]

[msg MSG_110_0_0 [Tipo esc姻ptico]]
[s][vp 8 0 0 0 4 0]Ah, 夷como lo de que les pasen[n]tantas cosas a sus competidores?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]No me digas que te tragas[n]esas gilipolleces.[n]Seguro que es coincidencia.[n][f 1 3 65535][w][e]

[msg MSG_111_0_0 [Tipo de aspecto somnoliento]]
[s][vp 8 2 0 42202 4 0]*bostezo* Ya empieza a hacer calor.[n]No queda nada de tercer semestre.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]S姻 que es lo mismo todos los a隠os,[n]pero es que el tiempo vuela, macho...[n][f 1 3 65535][w][e]

[msg MSG_112_0_0 [Tipo evasivo]]
[s][vp 8 0 0 0 5 0]Me pregunto qu姻 ser茨[n]de los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_113_0_0 [Tipo de aspecto somnoliento]]
[s][vp 8 0 0 0 4 0]Llevo tiempo sin pensar en ellos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Seg雨n dicen, la muerte del director[n]fue accidental. Igual hemos hecho[n]una monta隠a de un grano de arena.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]*bostezo* Ojal茨 vuelva[n]a pasar algo interesante.[n][f 1 3 65535][w][e]

[msg MSG_114_0_0 [Tipo de tercer a隠o]]
[s][vp 8 2 0 42702 4 0]Me pregunto cu茨ndo volver茨[n]Okumura a clase.[n]S姻 que el funeral es pronto...[n][f 1 3 65535][w][e]

[msg MSG_115_0_0 [Chica de tercer a隠o]]
[s][vp 8 0 0 0 5 0]No tiene que ser f茨cil organizar[n]el funeral de un pez tan gordo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Okumura suele ser muy callada.[n]夷Crees que estar茨 bien?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Cuesta creer que el padre de[n]una chica tan maja fuera tan malo...[n][f 1 3 65535][w][e]

[msg MSG_116_0_0 [Tipo de tercer a隠o]]
[s][vp 8 0 0 0 4 0]No me esperaba esto[n]de los Ladrones Fantasma...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Ha sido una ejecuci吋n p雨blica[n]en toda regla...[n][f 1 3 65535][w][e]

[msg MSG_117_0_0 [Chica ruidosa]]
[s][vp 8 2 0 37703 4 0]Yo no me creo que sali姻ramos[n]ayer en la tele... 斡con Akechi![n]Es un sue隠o hecho realidad.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Es incre胤ble que un estudiante[n]trabaje tambi姻n de detective.[n]Es igual que el Pr胤ncipe Detective.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Es tan listo y tan guapo...[n]斡Es casi demasiado perfecto![n][f 1 3 65535][w][e]

[msg MSG_118_0_0 [Chica emocionada]]
[s][vp 8 2 0 38300 5 0]Es que est茨bamos en primera fila.[n]斡Casi pod胤a tocarlo![n]斡Estaba de los nervios![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Le sentaba genial ese uniforme,[n]y sin parecer un esnob.[n]Es un orador nato.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Seg雨n tengo entendido, es hu姻rfano[n]y se cri吋 en una familia humilde.[n]斡Por eso es tan incre胤ble![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Quiere acabar el instituto habiendo[n]atrapado a los Ladrones Fantasma.[n]斡Esto no es ning雨n juego para 姻l![n][f 1 3 65535][w][e]

[msg MSG_119_0_0 [Chica ruidosa]]
[s][vp 8 2 0 37705 4 0]Yo o胤 que su padre es el jefe de[n]un gran conglomerado de empresas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]La verdad, me encanta que odie a[n]los medios. Me hace pensar que todo[n]esto no lo hace por la fama.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]La gente dice que es tan bueno que[n]algunos polic胤as lo odian...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]斡Ah, s胤! Al parecer, la entrevista[n]de ayer tuvo tanto 姻xito que[n]van a volver a emitirla esta noche.[n][f 1 3 65535][w][e]

[msg MSG_120_0_0 [Estudiante emocionado]]
[s][vp 8 2 0 39505 4 0]He visto a Niijima discutir[n]con el director sobre la mafia...[n]o algo as胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷De qu姻 iba todo eso?[n][f 1 3 65535][w][e]

[msg MSG_121_0_0 [T胤o descorazonado]]
[s][vp 8 0 0 0 5 0]Creo que su hermana mayor est茨[n]en la investigaci吋n. Quiz茨 ella[n]tambi姻n juegue a ser detective.[n][f 1 3 65535][w][e]

[msg MSG_122_0_0 [Estudiante emocionado]]
[s][vp 8 0 0 0 4 0]夷Est茨s de co隠a?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Vaya presidenta del consejo que no[n]es capaz de centrarse en lo suyo...[n][f 1 3 65535][w][e]

[msg MSG_123_0_0 [Estudiante amante de los juegos]]
[s][vp 8 2 0 39505 4 0]Todos saben lo del encubrimiento.[n]Ya nadie habla de eso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Sabes de lo que s胤 se habla?[n]De mi nivel de Gun About.[n][f 1 3 65535][w][e]

[msg MSG_124_0_0 [Estudiante impresionable]]
[s][vp 8 0 0 0 5 0]夷Gun About: The Super Real?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]夷Ese es el juego que tiene un mando[n]con forma de pistola?[n]Todo el mundo habla de 姻l.[n][f 1 3 65535][w][e]

[msg MSG_125_0_0 [Estudiante amante de los juegos]]
[s][vp 8 0 0 0 4 0]El multijugador es la bomba.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Est茨 en los recreativos[n]de [clr 2]la calle principal[clr 27] y en los de[n][clr 2]Akihabara[clr 27]. Tienes que probarlo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Yo el otro d胤a jugu姻[n]contra alguien buen胤simo...[n]No le di ni una sola vez.[n][f 1 3 65535][w][e]

[msg MSG_126_0_0 [Chica procrastinadora]]
[s][vp 8 2 0 40652 4 0]Quedarse toda la noche estudiando[n]da asco. Tendr胤a que haber empezado[n]a estudiar antes.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Al menos queda poco[n]para el festival del instituto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Es lo que m茨s me apetece[n]ahora mismo...[n][f 1 3 65535][w][e]

[msg MSG_127_0_0 [Chica apacible]]
[s][vp 8 0 0 0 5 0]S胤, pero... 夷al final se va a hacer?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Dec胤an que igual lo cancelaban...[n][f 1 3 65535][w][e]

[msg MSG_128_0_0 [Chica procrastinadora]]
[s][vp 8 0 0 0 4 0]斡Qu姻 dices! Vaya 茨nimos[n]de cara a los ex茨menes...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Las cosas ya est茨n mal de por s胤.[n]Si cancelan el festival,[n]斡los alumnos montar茨n una revuelta![n][f 1 3 65535][w][e]

[msg MSG_129_0_0 [Chica amante de los rumores]]
[s][vp 8 2 0 43201 4 0]Chouno ha vuelto[n]a arremeter contra Kawakami.[n][f 1 3 65535][w][e]

[msg MSG_130_0_0 [Chica l茨nguida]]
[s][vp 8 0 0 0 5 0]夷Otra vez? Pero 夷qu姻 ha hecho?[n][f 1 3 65535][w][e]

[msg MSG_131_0_0 [Chica amante de los rumores]]
[s][vp 8 0 0 0 4 0]Chouno se quejaba de la falta[n]de valores del instituto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Yo la he visto bostezando todo el[n]rato. Quiz茨 hayan descubierto la[n]vida nocturna secreta de Kawakami.[n][f 1 3 65535][w][e]

[msg MSG_132_0_0 [Chica imaginativa]]
[s][vp 8 2 0 43201 4 0]夷A que est茨 bueno el doctor Maruki?[n]Es supertorpe, 斡qu姻 mono![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]A lo mejor voy a una[n]de sus sesiones de orientaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_133_0_0 [Chica l茨nguida]]
[s][vp 8 0 0 0 5 0]Seguro que est茨 en la[n][clr 2]enfermer胤a[clr 27].[n]Lo vi ayer en la puerta.[n][f 1 3 65535][w][e]

[msg MSG_134_0_0 [Chica imaginativa]]
[s][vp 8 0 0 0 4 0]La [clr 2]enfermer胤a[clr 27] est茨 en la [clr 2]primera[n]planta del edificio de pr茨cticas[clr 27].[n]Yo no he ido nunca.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Deber胤a pedir cita para decirle:[n]或Doctor, me duele en el coraz吋n位.[n][f 1 3 65535][w][e]

[msg MSG_135_0_0 [Alumno de primero hablador]]
[s][vp 8 2 0 42702 4 0]En mi clase hay una chica muy mona,[n]pero no hay quien se le acerque.[n]Se llama Yoshizawa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Ayer quer胤a hablar un poco[n]con ella, pero siempre[n]se va corriendo a casa.[n][f 1 3 65535][w][e]

[msg MSG_136_0_0 [Alumno de primero informado]]
[s][vp 8 0 0 0 5 0]He visto a Yoshizawa en la puerta[n]de una clase de [clr 2]segundo[clr 27].[n]Creo que era la [clr 2]clase D[clr 27].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Parec胤a que estaba[n]esperando a alguien.[n][f 1 3 65535][w][e]

[msg MSG_137_0_0 [Alumno de primero hablador]]
[s][vp 8 0 0 0 4 0]A lo mejor le gusta alguien[n]de otra clase.[n]斡Yo quiero enterarme![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]El [clr 2]aula 2D[clr 27], aj茨...[n]夷Hoy tambi姻n estar茨 en la puerta?[n][f 1 3 65535][w][e]

[msg MSG_138_0_0 [Chica en姻rgica]]
[s][vp 8 0 0 0 4 0]夷Alguna vez estudias en la[n]biblioteca? Yo es que en casa[n]siempre me pongo a gandulear.[n][f 1 3 65535][w][e]

[msg MSG_139_0_0 [Chica inquieta]]
[s][vp 8 0 0 0 5 0]夷No te parece que el ambiente[n]es un problema? 夷Has o胤do[n]los rumores sobre el estudiante nuevo?[n][f 1 3 65535][w][e]

[msg MSG_140_0_0 [Chica en姻rgica]]
[s][vp 8 0 0 0 4 0]Ah, ese, s胤.[n]No paraban de hablar de 姻l.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]夷Recuerdas que el profesor[n]Kamoshida se disculp吋?[n]Lo del nuevo ya es agua pasada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Mis 雨ltimas notas no han sido[n]muy buenas... Como no mejore,[n]me van a quitar la paga.[n][f 1 3 65535][w][e]

[msg MSG_141_0_0 [Chica despreocupada]]
[s][vp 8 0 0 0 4 0]Anda, 夷era hoy?[n]Es un lobo y me come.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Eh... 夷Est茨s bien? S姻 que has ido[n]a verlo todos los d胤as.[n][f 1 3 65535][w][e]

[msg MSG_142_0_0 [Chica deprimida]]
[s][vp 8 0 0 0 5 0]夷C吋mo es que se va? Me siento[n]fatal. Hab胤a muchas cosas de las[n]que quer胤a hablar con 姻l.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Por qu姻 no se quedar茨 para siempre...[n]夷Qu姻 se supone[n]que voy a hacer ahora?[n][f 1 3 65535][w][e]

[msg MSG_143_0_0 [Chica despreocupada]]
[s][vp 8 0 0 0 4 0]Madre m胤a, lo tuyo es grave.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Pero parece que no solo te pasa[n]a ti, el hombre tiene mucho 姻xito[n]con las chicas.[n][f 1 3 65535][w][e]

[msg MSG_144_0_0 [Chico deportista]]
[s][vp 8 0 0 0 4 0]Eh, 夷lo has o胤do?[n]斡El encuentro deportivo fue genial![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]La forma en la que superaron[n]las adversidades y ganaron...[n]斡Parec胤a sacado de una peli![n][f 1 3 65535][w][e]

[msg MSG_145_0_0 [Chico sereno]]
[s][vp 8 0 0 0 5 0]S胤, esta vez han hecho[n]una actuaci吋n estelar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Habr茨n estado mat茨ndose[n]a entrenar. 斡Qu姻 bonito[n]es ver c吋mo sonr胤e la gente![n][f 1 3 65535][w][e]

[msg MSG_146_0_0 [Chico deportista]]
[s][vp 8 0 0 0 4 0]夷Qu姻? 夷De verdad has ido a verlo?[n]夷En serio?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Entiendo lo que quieres decir.[n]Puede que vaya a animarlos tambi姻n.[n][f 1 3 65535][w][e]

[msg MSG_147_0_0 [Estudiante de primer a隠o ap茨tico]]
[s][vp 8 2 0 0 4 0]Ah, el evento de limpieza es pasado[n]ma隠ana. Mi clase ir茨 en direcci吋n[n]contraria al Parque Inokashira.[n][f 1 3 65535][w][e]

[msg MSG_148_0_0 [Estudiante de primer a隠o d吋cil]]
[s][vp 8 0 0 0 5 0]En cierto modo, tengo ganas.[n]斡La estudiante honor胤fica[n]est茨 en mi grupo![n][f 1 3 65535][w][e]

[msg MSG_149_0_0 [Estudiante de primer a隠o ap茨tico]]
[s][vp 8 0 0 0 4 0]夷Eh? 夷Es tu tipo o qu姻?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Qu姻 mal. A los estudiantes de honor[n]no los obligan a ir, 夷verdad?[n]Pues no es justo.[n][f 1 3 65535][w][e]
[s][f 1 5]Estudiante de primer a隠o d吋cil[n][vp 8 0 0 0 5 0]Q-qu姻... Uf, 夷me han metido[n]con los mayores?[n]Vaya mierda, yo me quiero ir.[n][f 1 3 65535][w][e]

