[msg MSG_000_0_0 [オシャレに目覚めた男子]]
[s][vp 8 0 0 0 4 0]今日、帰りに本屋寄ってもいい?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [地味な男子]]
[s][vp 8 0 0 0 5 0]いいけど...[n]お前が本屋? 珍しいな...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]何買うんだ?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [オシャレに目覚めた男子]]
[s][vp 8 0 0 0 4 0]『色気が上がると噂のおしゃれ入門書』[n]って知らない?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]ネットのレビューも高くて、売り切れ続出。[n]ようやく再入荷したんだよ。[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]これで僕も...[n]フフフ...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Chico bruto]]
[s][vp 8 0 0 0 4 0]Siempre sacas buenas notas, t胤o...[n]夷Es que estudias en[n]la biblioteca o algo?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Chico fino]]
[s][vp 8 0 0 0 5 0]Qu姻 va. Para eso voy[n]al restaurante.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Aunque no lo parezca, va bien[n]para concentrarse. Y, si te entra[n]hambre, puedes comer.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Chico bruto]]
[s][vp 8 0 0 0 4 0]夷Est茨s de co隠a? T胤o, los pijitos[n]ricos sois tan diferentes...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]斡Yo tambi姻n quiero estudiar[n]en el restaurante![n]Pero tendr姻 que buscar trabajo.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Estudiante que odia la lluvia]]
[s][vp 8 0 0 0 4 0]Odio los d胤as de lluvia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Se me pone el pelo hecho un[n]desastre, se me moja la ropa...[n]Es que no apetece salir, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Estudiante que adora la lluvia]]
[s][vp 8 0 0 0 5 0]夷En serio? A m胤 me encantan.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Es que el sonido de la lluvia[n]es relajante... Me concentro m茨s[n]a la hora de leer y estudiar.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Estudiante que adora la lluvia]]
[s][vp 8 0 0 0 4 0]夷Eh? No me esperaba esa[n]respuesta... Eres bastante peculiar.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Estudiante con nervios]]
[s][vp 8 2 0 42913 4 0]夷No te parece una locura[n]todo el tema del chantaje?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Pensaba que eso era otro mundo,[n]pero hay v胤ctimas[n]hasta en mi clase.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Estudiante charlatana]]
[s][vp 8 0 0 0 5 0]斡Ah, yo s姻 c吋mo lo hacen![n]Se te acercan unos t胤os preguntando[n]si quieres ganar dinero f茨cil...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Y, si dices que s胤, te meten[n]en unos asuntos muy turbios.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Los profesores o el consejo[n]estudiantil har茨n algo.[n]La gente est茨 preocupada.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Estudiante con nervios]]
[s][vp 8 0 0 0 4 0]Ah, 夷te refieres a esa publicaci吋n?[n]夷Ir胤a en serio?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 4 0]Dicen que sab胤a lo de Kamoshida[n]y el acoso...[n]Seguramente no sea de mucha ayuda.[n][f 1 3 65535][w][e]

