[msg MSG_BATTING_THROUGH_01 [Morgana]]
[s][vp 8 2 1 1025 65535 0]At least take a swing...[n][f 1 2 45][e]

[msg MSG_BATTING_THROUGH_02 [Morgana]]
[s][vp 8 2 1 1025 65535 0]Uh, it went right by you...[n][f 1 2 45][e]

[msg MSG_BATTING_THROUGH_03 [Morgana]]
[s][vp 8 2 1 1025 65535 0]Why aren't you swinging?[n][f 1 2 45][e]

[msg MSG_BATTING_THROUGH_04 [Morgana]]
[s][vp 8 2 1 1025 65535 0]Oh, could you not react in time?[n][f 1 2 45][e]

[msg MSG_BATTING_THROUGH_05 [Morgana]]
[s][vp 8 2 1 1025 65535 0]Less looking more swinging...[n][f 1 2 45][e]

[msg MSG_BATTING_MISS_01 [Morgana]]
[s][vp 8 2 1 1028 65535 0]Gahhh, let me switch with you![n][f 1 2 45][e]

[msg MSG_BATTING_MISS_02 [Morgana]]
[s][vp 8 2 1 1028 65535 0]Not a horrible swing...[n][f 1 2 45][e]

[msg MSG_BATTING_MISS_03 [Morgana]]
[s][vp 8 2 1 1189 65535 0]Focus...![n][f 1 2 45][e]

[msg MSG_BATTING_MISS_04 [Morgana]]
[s][vp 8 2 1 1028 65535 0]Ah, what a bummer...[n][f 1 2 45][e]

[msg MSG_BATTING_MISS_05 [Morgana]]
[s][vp 8 2 1 1189 65535 0]Watch the ball carefully...![n][f 1 2 45][e]

[msg MSG_BATTING_HIT_01 [Morgana]]
[s][vp 8 2 1 1166 65535 0]Good one![n][f 1 2 45][e]

[msg MSG_BATTING_HIT_02 [Morgana]]
[s][vp 8 2 1 1180 65535 0]Nice hit![n][f 1 2 45][e]

[msg MSG_BATTING_HIT_03 [Morgana]]
[s][vp 8 2 1 1181 65535 0]Way to go![n][f 1 2 45][e]

[msg MSG_BATTING_HIT_04 [Morgana]]
[s][vp 8 2 1 1171 65535 0]Perfect timing![n][f 1 2 45][e]

[msg MSG_BATTING_HIT_05 [Morgana]]
[s][vp 8 2 1 1174 65535 0]Awesome, awesome![n][f 1 2 45][e]

[msg MSG_BATTING_HOMERUN_01 [Morgana]]
[s][vp 8 2 1 1045 65535 0]Ooh, home run![n][f 1 2 45][e]

[msg MSG_BATTING_HOMERUN_02 [Morgana]]
[s][vp 8 2 1 1045 65535 0]A-Amazing![n][f 1 2 45][e]

[msg MSG_BATTING_HOMERUN_03 [Morgana]]
[s][vp 8 2 1 1045 65535 0]That one's out of here![n][f 1 2 45][e]

[msg MSG_BATTING_HOMERUN_04 [Morgana]]
[s][vp 8 2 1 1045 65535 0]That was the sweet spot...![n][f 1 2 45][e]

[msg MSG_BATTING_HOMERUN_05 [Morgana]]
[s][vp 8 2 1 1045 65535 0]Such impressive form...![n][f 1 2 45][e]

