[msg ROUNDSTART_00 [Ryuji]]
[s][vp 8 2 1 7197 65535 0]Round 1! I'm counting on you![n][w][e]

[msg ROUNDSTART_01 [Ryuji]]
[s][vp 8 2 1 7110 65535 0]Let's begin![n][w][e]

[msg ROUNDSTART_02 [Ryuji]]
[s][vp 8 2 1 54236 65535 0]The first shot's what's important![n][w][e]

[msg ROUNDSTART_03 [Morgana]]
[s][vp 8 2 1 1175 65535 0]I know you can do it![n][w][e]

[msg ROUNDSTART_04 [Morgana]]
[s][vp 8 2 1 1174 65535 0]Let's start![n][w][e]

[msg ROUNDSTART_05 [Morgana]]
[s][vp 8 2 1 53126 65535 0]Stay calm, all right?[n][w][e]

[msg ROUNDSTART_06 [Ann]]
[s][vp 8 2 1 6153 65535 0]First round! Let's do it together![n][w][e]

[msg ROUNDSTART_07 [Ann]]
[s][vp 8 2 1 54043 65535 0]I'm leaving it to you![n][w][e]

[msg ROUNDSTART_08 [Ann]]
[s][vp 8 2 1 6048 65535 0]Game start![n][w][e]

[msg ROUNDSTART_09 [Yusuke]]
[s][vp 8 2 1 4023 65535 0]So, it has begun.[n][w][e]

[msg ROUNDSTART_10 [Yusuke]]
[s][vp 8 2 1 53730 65535 0]The first move is always important.[n][w][e]

[msg ROUNDSTART_11 [Yusuke]]
[s][vp 8 2 1 4088 65535 0]I shall leave this to you...![n][w][e]

[msg ROUNDSTART_12 [Makoto]]
[s][vp 8 2 1 2053 65535 0]I'm leaving the first one to you![n][w][e]

[msg ROUNDSTART_13 [Makoto]]
[s][vp 8 2 1 53329 65535 0]Just be sure to stay calm...![n][w][e]

[msg ROUNDSTART_14 [Makoto]]
[s][vp 8 2 1 2114 65535 0]You'll be fine, you got this![n][w][e]

[msg ROUNDSTART_15 [Futaba]]
[s][vp 8 2 1 54731 65535 0]Now then, show me what you got![n][w][e]

[msg ROUNDSTART_16 [Futaba]]
[s][vp 8 2 1 54738 65535 0]Relax, all right...!?[n][w][e]

[msg ROUNDSTART_17 [Futaba]]
[s][vp 8 2 1 9052 65535 0]Just clear it![n][w][e]

[msg ROUNDSTART_18 [Haru]]
[s][vp 8 2 1 53540 65535 0]I am sure you got round 1![n][w][e]

[msg ROUNDSTART_19 [Haru]]
[s][vp 8 2 1 3048 65535 0]Just be yourself and do your best![n][w][e]

[msg ROUNDSTART_20 [Haru]]
[s][vp 8 2 1 53533 65535 0]You will do great![n][w][e]

[msg ROUNDSTART_21 [Akechi]]
[s][vp 8 2 1 8127 65535 0]Show me what you can do.[n][w][e]

[msg ROUNDSTART_22 [Akechi]]
[s][vp 8 2 1 8020 65535 0]I'm counting on you.[n][w][e]

[msg ROUNDSTART_23 [Akechi]]
[s][vp 8 2 1 8127 65535 0]Now then, let's see how this'll turn out.[n][w][e]

[msg ROUNDSTART_24 [Sumire]]
[s][vp 8 2 1 57163 65535 0]Good luck, Senpai![n][w][e]

[msg ROUNDSTART_25 [Sumire]]
[s][vp 8 2 1 57022 65535 0]I'm sure you got this![n][w][e]

[msg ROUNDSTART_26 [Sumire]]
[s][vp 8 2 1 57164 65535 0]Your throwing form is really[n]important as well![n][w][e]

[msg YELL_NOTFINISH_00 [Ryuji]]
[s][vp 8 2 1 7038 65535 0]Let's see how it'll turn out...[n][w][e]

[msg YELL_NOTFINISH_01 [Ryuji]]
[s][vp 8 2 1 7028 65535 0]My heart's poundin' dude...[n][w][e]

[msg YELL_NOTFINISH_02 [Ryuji]]
[s][vp 8 2 1 54244 65535 0]I-Is it time?[n][w][e]

[msg YELL_NOTFINISH_03 [Morgana]]
[s][vp 8 2 1 1018 65535 0]Don't throw it with too hard...![n][w][e]

[msg YELL_NOTFINISH_04 [Morgana]]
[s][vp 8 2 1 1021 65535 0]Are you gonna throw it?[n][w][e]

[msg YELL_NOTFINISH_05 [Morgana]]
[s][vp 8 2 1 1028 65535 0]My paws are sweating...![n][w][e]

[msg YELL_NOTFINISH_06 [Ann]]
[s][vp 8 2 1 6021 65535 0]I'm getting nervous...![n][w][e]

[msg YELL_NOTFINISH_07 [Ann]]
[s][vp 8 2 1 6028 65535 0]Stay calm...![n][w][e]

[msg YELL_NOTFINISH_08 [Ann]]
[s][vp 8 2 1 6034 65535 0]You'll be fine![n][w][e]

[msg YELL_NOTFINISH_09 [Yusuke]]
[s][vp 8 2 1 4023 65535 0]Don't rush now...[n][w][e]

[msg YELL_NOTFINISH_10 [Yusuke]]
[s][vp 8 2 1 4023 65535 0]Try imagining your success...[n][w][e]

[msg YELL_NOTFINISH_11 [Yusuke]]
[s][vp 8 2 1 4087 65535 0]Are you going to throw it?[n][w][e]

[msg YELL_NOTFINISH_12 [Makoto]]
[s][vp 8 2 1 2114 65535 0]Just be your usual self.[n][w][e]

[msg YELL_NOTFINISH_13 [Makoto]]
[s][vp 8 2 1 2035 65535 0]You'll be okay...![n][w][e]

[msg YELL_NOTFINISH_14 [Makoto]]
[s][vp 8 2 1 2113 65535 0]Is it almost time?[n][w][e]

[msg YELL_NOTFINISH_15 [Futaba]]
[s][vp 8 2 1 9027 65535 0]S-S-Stay calm![n][w][e]

[msg YELL_NOTFINISH_16 [Futaba]]
[s][vp 8 2 1 9043 65535 0]Is this your chance?[n][w][e]

[msg YELL_NOTFINISH_17 [Futaba]]
[s][vp 8 2 1 9137 65535 0]You'll be okay![n]What'll happen will happen![n][w][e]

[msg YELL_NOTFINISH_18 [Haru]]
[s][vp 8 2 1 3019 65535 0]Good luck![n][w][e]

[msg YELL_NOTFINISH_19 [Haru]]
[s][vp 8 2 1 3028 65535 0]I am getting nervous...[n][w][e]

[msg YELL_NOTFINISH_20 [Haru]]
[s][vp 8 2 1 3127 65535 0]Where are you planning to aim...?[n][w][e]

[msg YELL_NOTFINISH_21 [Akechi]]
[s][vp 8 2 1 8127 65535 0]How will it turn out...[n][w][e]

[msg YELL_NOTFINISH_22 [Akechi]]
[s][vp 8 2 1 8130 65535 0]Are you nervous?[n][w][e]

[msg YELL_NOTFINISH_23 [Akechi]]
[s][vp 8 2 1 8128 65535 0]Your posture is fine.[n][w][e]

[msg YELL_NOTFINISH_24 [Sumire]]
[s][vp 8 2 1 57142 65535 0]This is quite nerve-racking![n][w][e]

[msg YELL_NOTFINISH_25 [Sumire]]
[s][vp 8 2 1 57023 65535 0]You'll be fine, Senpai![n][w][e]

[msg YELL_NOTFINISH_26 [Sumire]]
[s][vp 8 2 1 57056 65535 0]My heart is racing...![n][w][e]

[msg YELL_FINISH_00 [Ryuji]]
[s][vp 8 2 1 7023 65535 0]We've got this![n][w][e]

[msg YELL_FINISH_01 [Ryuji]]
[s][vp 8 2 1 7045 65535 0]Just finish it![n][w][e]

[msg YELL_FINISH_02 [Ryuji]]
[s][vp 8 2 1 7080 65535 0]Just a lil more![n][w][e]

[msg YELL_FINISH_03 [Morgana]]
[s][vp 8 2 1 1069 65535 0]You got this?[n][w][e]

[msg YELL_FINISH_04 [Morgana]]
[s][vp 8 2 1 1159 65535 0]We're finally here...[n][w][e]

[msg YELL_FINISH_05 [Morgana]]
[s][vp 8 2 1 1109 65535 0]You only need a bit more![n][w][e]

[msg YELL_FINISH_06 [Ann]]
[s][vp 8 2 1 6019 65535 0]We're almost there![n][w][e]

[msg YELL_FINISH_07 [Ann]]
[s][vp 8 2 1 6066 65535 0]We're just about done![n][w][e]

[msg YELL_FINISH_08 [Ann]]
[s][vp 8 2 1 6117 65535 0]The moment of truth![n][w][e]

[msg YELL_FINISH_09 [Yusuke]]
[s][vp 8 2 1 4045 65535 0]This is going to be your most[n]important throw.[n][w][e]

[msg YELL_FINISH_10 [Yusuke]]
[s][vp 8 2 1 53737 65535 0]Don't let your guard down...![n][w][e]

[msg YELL_FINISH_11 [Yusuke]]
[s][vp 8 2 1 4105 65535 0]You just need a little more![n][w][e]

[msg YELL_FINISH_12 [Makoto]]
[s][vp 8 2 1 2048 65535 0]You only need a little more![n][w][e]

[msg YELL_FINISH_13 [Makoto]]
[s][vp 8 2 1 2114 65535 0]This is crucial![n][w][e]

[msg YELL_FINISH_14 [Makoto]]
[s][vp 8 2 1 2105 65535 0]I think you got this...![n][w][e]

[msg YELL_FINISH_15 [Futaba]]
[s][vp 8 2 1 9105 65535 0]Your victory is right up ahead...![n][w][e]

[msg YELL_FINISH_16 [Futaba]]
[s][vp 8 2 1 9055 65535 0]Go for it![n][w][e]

[msg YELL_FINISH_17 [Futaba]]
[s][vp 8 2 1 54715 65535 0]Will this finish it!?[n][w][e]

[msg YELL_FINISH_18 [Haru]]
[s][vp 8 2 1 53522 65535 0]You are almost there...![n][w][e]

[msg YELL_FINISH_19 [Haru]]
[s][vp 8 2 1 3105 65535 0]I am sure you can finish this game![n][w][e]

[msg YELL_FINISH_20 [Haru]]
[s][vp 8 2 1 53541 65535 0]Ah, my heart... it's racing...![n][w][e]

[msg YELL_FINISH_21 [Akechi]]
[s][vp 8 2 1 8127 65535 0]We're finally here.[n][w][e]

[msg YELL_FINISH_22 [Akechi]]
[s][vp 8 2 1 8156 65535 0]You think you can finish this?[n][w][e]

[msg YELL_FINISH_23 [Akechi]]
[s][vp 8 2 1 8155 65535 0]Don't get impatient now...[n][w][e]

[msg YELL_FINISH_24 [Sumire]]
[s][vp 8 2 1 57058 65535 0]Just finish it, Senpai![n][w][e]

[msg YELL_FINISH_25 [Sumire]]
[s][vp 8 2 1 57022 65535 0]Go! Go! Senpai![n][w][e]

[msg YELL_FINISH_26 [Sumire]]
[s][vp 8 2 1 57083 65535 0]You're almost done![n][w][e]

[msg SCORE_HIGH_00 [Ryuji]]
[s][vp 8 2 1 7039 65535 0]All right![n][w][e]

[msg SCORE_HIGH_01 [Ryuji]]
[s][vp 8 2 1 7048 65535 0]Nice goin'![n][w][e]

[msg SCORE_HIGH_02 [Ryuji]]
[s][vp 8 2 1 7020 65535 0]Sweet![n][w][e]

[msg SCORE_HIGH_03 [Morgana]]
[s][vp 8 2 1 1181 65535 0]You did it![n][w][e]

[msg SCORE_HIGH_04 [Morgana]]
[s][vp 8 2 1 1184 65535 0]Whoa![n][w][e]

[msg SCORE_HIGH_05 [Morgana]]
[s][vp 8 2 1 1040 65535 0]Good going![n][w][e]

[msg SCORE_HIGH_06 [Ann]]
[s][vp 8 2 1 6039 65535 0]Amazing![n][w][e]

[msg SCORE_HIGH_07 [Ann]]
[s][vp 8 2 1 54037 65535 0]Good job![n][w][e]

[msg SCORE_HIGH_08 [Ann]]
[s][vp 8 2 1 6045 65535 0]Whoo![n][w][e]

[msg SCORE_HIGH_09 [Yusuke]]
[s][vp 8 2 1 4135 65535 0]Fantastic![n][w][e]

[msg SCORE_HIGH_10 [Yusuke]]
[s][vp 8 2 1 4047 65535 0]That was amazing![n][w][e]

[msg SCORE_HIGH_11 [Yusuke]]
[s][vp 8 2 1 4081 65535 0]You did it![n][w][e]

[msg SCORE_HIGH_12 [Makoto]]
[s][vp 8 2 1 2162 65535 0]Nice one![n][w][e]

[msg SCORE_HIGH_13 [Makoto]]
[s][vp 8 2 1 53340 65535 0]That was amazing![n][w][e]

[msg SCORE_HIGH_14 [Makoto]]
[s][vp 8 2 1 2164 65535 0]There it is![n][w][e]

[msg SCORE_HIGH_15 [Futaba]]
[s][vp 8 2 1 9040 65535 0]Ah, good work![n][w][e]

[msg SCORE_HIGH_16 [Futaba]]
[s][vp 8 2 1 9045 65535 0]That was a nice one![n][w][e]

[msg SCORE_HIGH_17 [Futaba]]
[s][vp 8 2 1 9162 65535 0]Whoaa... I'm getting excited![n][w][e]

[msg SCORE_HIGH_18 [Haru]]
[s][vp 8 2 1 3040 65535 0]Wow, you're very good![n][w][e]

[msg SCORE_HIGH_19 [Haru]]
[s][vp 8 2 1 3114 65535 0]Mm-hm! Not bad at all![n][w][e]

[msg SCORE_HIGH_20 [Haru]]
[s][vp 8 2 1 3104 65535 0]Hurray! You did it![n][w][e]

[msg SCORE_HIGH_21 [Akechi]]
[s][vp 8 2 1 8133 65535 0]Huh...[n][w][e]

[msg SCORE_HIGH_22 [Akechi]]
[s][vp 8 2 1 8134 65535 0]Not too bad...![n][w][e]

[msg SCORE_HIGH_23 [Akechi]]
[s][vp 8 2 1 8038 65535 0]You're quite good at this.[n][w][e]

[msg SCORE_HIGH_24 [Sumire]]
[s][vp 8 2 1 57065 65535 0]Th-That was amazing![n][w][e]

[msg SCORE_HIGH_25 [Sumire]]
[s][vp 8 2 1 57120 65535 0]So that's where you were aiming![n][w][e]

[msg SCORE_HIGH_26 [Sumire]]
[s][vp 8 2 1 57051 65535 0]Congratulations, Senpai![n][w][e]

[msg SCORE_NORMAL_00 [Ryuji]]
[s][vp 8 2 1 7088 65535 0]All right...[n][w][e]

[msg SCORE_NORMAL_01 [Ryuji]]
[s][vp 8 2 1 7048 65535 0]That wasn't too bad.[n][w][e]

[msg SCORE_NORMAL_02 [Ryuji]]
[s][vp 8 2 1 7038 65535 0]I see...[n][w][e]

[msg SCORE_NORMAL_03 [Morgana]]
[s][vp 8 2 1 1020 65535 0]So that's where you were aiming.[n][w][e]

[msg SCORE_NORMAL_04 [Morgana]]
[s][vp 8 2 1 1174 65535 0]Not bad...[n][w][e]

[msg SCORE_NORMAL_05 [Morgana]]
[s][vp 8 2 1 1035 65535 0]Hmhm...[n][w][e]

[msg SCORE_NORMAL_06 [Ann]]
[s][vp 8 2 1 6020 65535 0]Huh...[n][w][e]

[msg SCORE_NORMAL_07 [Ann]]
[s][vp 8 2 1 6110 65535 0]There...?[n][w][e]

[msg SCORE_NORMAL_08 [Ann]]
[s][vp 8 2 1 6168 65535 0]I see where you're going...[n][w][e]

[msg SCORE_NORMAL_09 [Yusuke]]
[s][vp 8 2 1 4133 65535 0]Hm... That's where it landed...[n][w][e]

[msg SCORE_NORMAL_10 [Yusuke]]
[s][vp 8 2 1 4088 65535 0]All right...[n][w][e]

[msg SCORE_NORMAL_11 [Yusuke]]
[s][vp 8 2 1 4090 65535 0]Not bad...[n][w][e]

[msg SCORE_NORMAL_12 [Makoto]]
[s][vp 8 2 1 2081 65535 0]That could work.[n][w][e]

[msg SCORE_NORMAL_13 [Makoto]]
[s][vp 8 2 1 2064 65535 0]That's where it landed...[n][w][e]

[msg SCORE_NORMAL_14 [Makoto]]
[s][vp 8 2 1 2113 65535 0]I suppose that'll work.[n][w][e]

[msg SCORE_NORMAL_15 [Futaba]]
[s][vp 8 2 1 9098 65535 0]Oh-ho...[n][w][e]

[msg SCORE_NORMAL_16 [Futaba]]
[s][vp 8 2 1 9021 65535 0]Not a bad choice.[n][w][e]

[msg SCORE_NORMAL_17 [Futaba]]
[s][vp 8 2 1 9081 65535 0]Ah, okay...[n][w][e]

[msg SCORE_NORMAL_18 [Haru]]
[s][vp 8 2 1 3020 65535 0]Oh, hm...[n][w][e]

[msg SCORE_NORMAL_19 [Haru]]
[s][vp 8 2 1 3120 65535 0]That wasn't too bad.[n][w][e]

[msg SCORE_NORMAL_20 [Haru]]
[s][vp 8 2 1 3021 65535 0]Oh, that is where it went...[n][w][e]

[msg SCORE_NORMAL_21 [Akechi]]
[s][vp 8 2 1 8038 65535 0]Hm...[n][w][e]

[msg SCORE_NORMAL_22 [Akechi]]
[s][vp 8 2 1 8038 65535 0]Oh...?[n][w][e]

[msg SCORE_NORMAL_23 [Akechi]]
[s][vp 8 2 1 8020 65535 0]I think I get it...[n][w][e]

[msg SCORE_NORMAL_24 [Sumire]]
[s][vp 8 2 1 57173 65535 0]Hm, so that's what you're planning.[n][w][e]

[msg SCORE_NORMAL_25 [Sumire]]
[s][vp 8 2 1 57119 65535 0]Ah-hah...[n][w][e]

[msg SCORE_NORMAL_26 [Sumire]]
[s][vp 8 2 1 57113 65535 0]It landed there?[n][w][e]

[msg OUT_00 [Ryuji]]
[s][vp 8 2 1 7021 65535 0]Don't worry 'bout it.[n][w][e]

[msg OUT_01 [Ryuji]]
[s][vp 8 2 1 7191 65535 0]Dang...[n][w][e]

[msg OUT_02 [Ryuji]]
[s][vp 8 2 1 7085 65535 0]Things happen, man.[n][w][e]

[msg OUT_03 [Morgana]]
[s][vp 8 2 1 1022 65535 0]Crap...[n][w][e]

[msg OUT_04 [Morgana]]
[s][vp 8 2 1 1025 65535 0]Aw man...[n][w][e]

[msg OUT_05 [Morgana]]
[s][vp 8 2 1 1173 65535 0]Don't be too down.[n][w][e]

[msg OUT_06 [Ann]]
[s][vp 8 2 1 6021 65535 0]Oh no...[n][w][e]

[msg OUT_07 [Ann]]
[s][vp 8 2 1 6119 65535 0]Huh? Was that a miss?[n][w][e]

[msg OUT_08 [Ann]]
[s][vp 8 2 1 54038 65535 0]Don't worry about it![n][w][e]

[msg OUT_09 [Yusuke]]
[s][vp 8 2 1 4065 65535 0]You've lucked out...[n][w][e]

[msg OUT_10 [Yusuke]]
[s][vp 8 2 1 4074 65535 0]It's quite a shame...[n][w][e]

[msg OUT_11 [Yusuke]]
[s][vp 8 2 1 4026 65535 0]Sometimes it's all about luck.[n][w][e]

[msg OUT_12 [Makoto]]
[s][vp 8 2 1 2028 65535 0]Hmm...[n][w][e]

[msg OUT_13 [Makoto]]
[s][vp 8 2 1 2064 65535 0]That was unfortunate...[n][w][e]

[msg OUT_14 [Makoto]]
[s][vp 8 2 1 2029 65535 0]Don't worry about it.[n][w][e]

[msg OUT_15 [Futaba]]
[s][vp 8 2 1 9038 65535 0]Oh nooo!![n][w][e]

[msg OUT_16 [Futaba]]
[s][vp 8 2 1 9029 65535 0]We're done for![n][w][e]

[msg OUT_17 [Futaba]]
[s][vp 8 2 1 54733 65535 0]Dwelling means you've already lost![n][w][e]

[msg OUT_18 [Haru]]
[s][vp 8 2 1 3024 65535 0]Oh dear...[n][w][e]

[msg OUT_19 [Haru]]
[s][vp 8 2 1 3110 65535 0]Try not to be so down about it...[n][w][e]

[msg OUT_20 [Haru]]
[s][vp 8 2 1 3027 65535 0]That one was tough...[n][w][e]

[msg OUT_21 [Akechi]]
[s][vp 8 2 1 8020 65535 0]You missed...[n][w][e]

[msg OUT_22 [Akechi]]
[s][vp 8 2 1 8003 65535 0]You were aiming there?[n][w][e]

[msg OUT_23 [Akechi]]
[s][vp 8 2 1 8028 65535 0]That was hard to believe...[n][w][e]

[msg OUT_24 [Sumire]]
[s][vp 8 2 1 57063 65535 0]D-Don't worry about it![n][w][e]

[msg OUT_25 [Sumire]]
[s][vp 8 2 1 57048 65535 0]I didn't expect it to turn out like this...[n][w][e]

[msg OUT_26 [Sumire]]
[s][vp 8 2 1 57088 65535 0]Please don't feel down![n][w][e]

[msg OVER60_00 [Ryuji]]
[s][vp 8 2 1 54237 65535 0]You're under 60, dude![n][w][e]

[msg OVER60_01 [Ryuji]]
[s][vp 8 2 1 54237 65535 0]Alright! Y'see that? Under 60![n][w][e]

[msg OVER60_02 [Ryuji]]
[s][vp 8 2 1 54237 65535 0]Sweet! You're below 60![n][w][e]

[msg OVER60_03 [Morgana]]
[s][vp 8 2 1 53127 65535 0]It's under 60![n][w][e]

[msg OVER60_04 [Morgana]]
[s][vp 8 2 1 53127 65535 0]We're below 60 now![n][w][e]

[msg OVER60_05 [Morgana]]
[s][vp 8 2 1 53127 65535 0]Good going! It's under 60 now![n][w][e]

[msg OVER60_06 [Ann]]
[s][vp 8 2 1 54036 65535 0]Oh! You're below 60 now![n][w][e]

[msg OVER60_07 [Ann]]
[s][vp 8 2 1 54036 65535 0]Check out that number![n]You're below 60![n][w][e]

[msg OVER60_08 [Ann]]
[s][vp 8 2 1 54036 65535 0]So how much do we need now?[n][w][e]

[msg OVER60_09 [Yusuke]]
[s][vp 8 2 1 53731 65535 0]Ah, you're below 60 now![n][w][e]

[msg OVER60_10 [Yusuke]]
[s][vp 8 2 1 53731 65535 0]Hm, you're almost done.[n][w][e]

[msg OVER60_11 [Yusuke]]
[s][vp 8 2 1 53731 65535 0]It seems you just need a little[n]under 60.[n][w][e]

[msg OVER60_12 [Makoto]]
[s][vp 8 2 1 53330 65535 0]You've gotten below 60![n][w][e]

[msg OVER60_13 [Makoto]]
[s][vp 8 2 1 53330 65535 0]You're only a few shots away![n][w][e]

[msg OVER60_14 [Makoto]]
[s][vp 8 2 1 53330 65535 0]Just a little more...[n][w][e]

[msg OVER60_15 [Futaba]]
[s][vp 8 2 1 54732 65535 0]Good! You're below 60 now.[n][w][e]

[msg OVER60_16 [Futaba]]
[s][vp 8 2 1 54732 65535 0]Oh! You're score's below 60![n][w][e]

[msg OVER60_17 [Futaba]]
[s][vp 8 2 1 54732 65535 0]Sweet you're almost done![n][w][e]

[msg OVER60_18 [Haru]]
[s][vp 8 2 1 53535 65535 0]Ah, you are below 60![n][w][e]

[msg OVER60_19 [Haru]]
[s][vp 8 2 1 53535 65535 0]Look at your score! Just a little more![n][w][e]

[msg OVER60_20 [Haru]]
[s][vp 8 2 1 53535 65535 0]Oh! You're almost done![n][w][e]

[msg OVER60_21 [Akechi]]
[s][vp 8 2 1 8131 65535 0]Below 60, huh...[n][w][e]

[msg OVER60_22 [Akechi]]
[s][vp 8 2 1 8131 65535 0]You're almost done.[n][w][e]

[msg OVER60_23 [Akechi]]
[s][vp 8 2 1 8131 65535 0]You've gotten your score below 60.[n][w][e]

[msg OVER60_24 [Sumire]]
[s][vp 8 2 1 57157 65535 0]Oh, look, Senpai![n]You're below 60 now![n][w][e]

[msg OVER60_25 [Sumire]]
[s][vp 8 2 1 57157 65535 0]You've got this, Senpai![n][w][e]

[msg OVER60_26 [Sumire]]
[s][vp 8 2 1 57157 65535 0]You only have a little less than 60[n]to go, Senpai![n][w][e]

