[msg NOT_OPEN_DOOR]
[s]La puerta est茨 cerrada[n]a cal y canto.[n][w][e]

[msg LOCK_DOOR]
[s]La puerta est茨 cerrada.[n][w][e]

[msg D10_07_locked_door_mes_s [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]夷Qu姻 cojones? Est茨 cerrada.[n][w][e]

[msg D10_07_locked_door_mes02 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que no hay manera.[n][w][e]

[msg D10_07_locked_door_mes04 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Esos andamios ayudan a desplazarse[n]a los trabajadores del auditorio.[n]Quiz茨 tambi姻n nos sirvan.[n][w][e]

[msg D10_07_locked_door_mes_e [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pues no es mala idea.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]Joker, a ver si nos puedes[n]ayudar con el arpeo.[n][w][e]

[msg DOOR_Dummy_MES [Makoto]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

