[msg NOT_OPEN_DOOR]
[s]La puerta est茨 cerrada[n]a cal y canto.[n][w][e]

[msg mini_EV_DOOR_LOCK06_mes0 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Parece que esta puerta[n]tambi姻n est茨 bloqueada.[n][w][e]

[msg mini_EV_DOOR_LOCK06_mes0_2 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]夷Har茨 falta una tarjeta?[n][w][e]

[msg mini_EV_DOOR_LOCK12_mes0 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4045 65535 0]Magn胤fico. El camino est茨 abierto.[n][w][e]

[msg DOOR_Dummy_MES [Yusuke]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

