[msg FLD162_015_notkey_mes_St [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 cojones? Est茨 cerrada.[n][w][e]

[msg FLD162_015_notkey_mes_En [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No podemos hacer nada.[n]Busquemos otra puerta.[n][w][e]

[msg FLD162_015_notkey_Retry_ [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 haces? D姻monos prisa[n]y busquemos otra puerta.[n][w][e]

[msg NOT_OPEN_DOOR]
[s]La puerta est茨 cerrada[n]a cal y canto.[n][w][e]

[msg LOCK_DOOR]
[s]La puerta est茨 cerrada.[n][w][e]

[msg DOOR_Dummy_MES [Akechi]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

