[msg NOT_OPEN_DOOR]
[s]La puerta est茨 cerrada[n]a cal y canto.[n][w][e]

[msg LOCK_DOOR]
[s]La puerta est茨 cerrada.[n][w][e]

[msg FLD162_009_LookEnemy_sta [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que esta es la sala de[n]la respuesta err吋nea... 夷Qu姻 habr胤a[n]pasado si la hubi姻ramos escogido?[n][w][e]

[msg FLD162_009_LookEnemy_02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Supongo que podemos[n]echar un vistazo.[n][w][e]

[msg FLD162_009_LookEnemy_03 [Sombra con bata de laboratorio]]
[s]斡夷...?! Me hab胤a parecido[n]sentir una presencia...[n][w][e]

[msg FLD162_009_LookEnemy_04 [Sombra con bata de laboratorio]]
[s]Creo que necesito descansar. No he[n]parado de ayudar a los pacientes.[n]Esto no es bueno para m胤...[n][w][e]

[msg FLD162_009_LookEnemy_05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Una sombra... Es f茨cil imaginar[n]lo que habr胤a pasado si hubi姻ramos[n]escogido la opci吋n A.[n][w][e]

[msg FLD162_009_LookEnemy_end [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que ten胤amos raz吋n. Escoger[n]la respuesta que dar胤a Maruki es[n]la forma m茨s segura de avanzar.[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]V茨monos... Ser胤a un fastidio[n]tener que enfrentarnos a eso.[n][w][e]

[msg FLD162_009_accept_lock [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No sabemos qu姻 est茨 pasando dentro.[n]Deber胤amos investigar la recepci吋n[n]antes de nada.[n][w][e]

[msg DOOR_Dummy_MES [Yusuke]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

