[msg NOT_OPEN_DOOR]
[s]La puerta est茨 cerrada[n]a cal y canto.[n][w][e]

[msg mini_EV_DOOR_LOCK01_mes0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]La puerta est茨 cerrada. Parece[n]que no podemos forzar la cerradura.[n][w][e]

[msg mini_EV_DOOR_LOCK01_mes0_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]夷Necesitaremos una tarjeta?[n][w][e]

[msg mini_EV_DOOR_LOCK01_mes0_3 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque no tiene lector de tarjetas.[n]夷Estar茨 por el otro lado?[n][w][e]

[msg mini_EV_DOOR_LOCK01_mes0_4 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7088 65535 0]Ohhh. A lo mejor podemos[n]abrirla con una tarjeta.[n][w][e]

[msg mini_EV_DOOR_LOCK02_mes0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2164 65535 0]Hay rejas... As胤 no[n]vamos a poder abrir la puerta.[n][w][e]

[msg mini_EV_DOOR_LOCK02_mes0_2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A lo mejor podr胤amos pasar[n]con un objeto especial...[n][w][e]

[msg mini_EV_DOOR_LOCK02_mes0_3 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7088 65535 0]夷Habr茨 que sacar[n]la tarjeta que cogimos antes?[n][w][e]

[msg mini_EV_DOOR_LOCK02_mes0_4 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]斡Muy bien![n][w][e]

[msg mini_EV_DOOR_LOCK03_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Mierda, a este paso[n]nunca vamos a entrar.[n][w][e]

[msg mini_EV_DOOR_LOCK03_mes0_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mirad. 或Prohibida la entrada[n]al personal no autorizado位.[n][w][e]

[msg mini_EV_DOOR_LOCK03_mes0_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ahora tengo m茨s ganas de entrar![n]夷Hay algo que podamos hacer?[n][w][e]

[msg mini_EV_DOOR_LOCK07_mes0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]夷No se abre?[n][w][e]

[msg mini_EV_DOOR_LOCK07_mes0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, de nada sirve[n]volver a la recepci吋n.[n]Vamos a mirar en otro sitio.[n][w][e]

[msg DOOR_Dummy_MES [Morgana]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

