[msg mini_EV_DOOR_LOCK04_mes0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Mmm. Otra puerta igual...[n][w][e]

[msg mini_EV_DOOR_LOCK04_mes0_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque no veo ning雨n dispositivo[n]identificador de tarjetas.[n]夷Estar茨 por el otro lado?[n][w][e]

[msg mini_EV_DOOR_LOCK04_mes0_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Si usamos el dispositivo,[n]la puerta deber胤a abrirse, 夷no?[n][w][e]

[msg mini_EV_DOOR_LOCK05_mes0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]夷Una puerta cerrada?[n]Tendr胤a que haber un lector[n]de tarjetas por aqu胤...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O no. 夷Estar茨 por el otro lado?[n][w][e]

[msg mini_EV_DOOR_LOCK05_mes0_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Creo que, si usas eso,[n]conseguir茨s que se abra.[n][w][e]

[msg mini_EV_DOOR_LOCK11_mes0 [Ann]]
[s][bup 0 4 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6170 65535 0]Jol胤n, no se abre desde este lado.[n][w][e]

[msg mini_EV_DOOR_LOCK11_mes0_2 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Se abrir茨 por el otro lado?[n][w][e]

[msg mini_EV_DOOR_LOCK11_mes0_3 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4192 65535 0]O con el dispositivo aquel.[n][w][e]

[msg e259_152_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Oye, vamos a echarle un ojo[n]al chisme ese, anda.[n][w][e]

[msg DOOR_Dummy_MES [Morgana]]
[s]ERROR! イベントをセットして下さい。[n][w][e]

