[msg YELL_00 [Ryuji]]
[s][vp 8 2 1 1190 65535 0]斡No pierdas la concentraci吋n![n][w][e]

[msg YELL_01 [Ryuji]]
[s][vp 8 2 1 1190 65535 0]斡Lo har茨s bien,[n]no te pongas nervioso![n][w][e]

[msg YELL_02 [Ryuji]]
[s][vp 8 2 1 1190 65535 0]斡S姻 t雨 mismo![n][w][e]

[msg YELL_03 [Morgana]]
[s][vp 8 2 1 1190 65535 0]斡Hazlo por m胤![n][w][e]

[msg YELL_04 [Morgana]]
[s][vp 8 2 1 1190 65535 0]Bueno, 斡no est茨 mal! [n][w][e]

[msg YELL_05 [Morgana]]
[s][vp 8 2 1 1190 65535 0]斡Tranquilo![n][w][e]

[msg YELL_06 [Ann]]
[s][vp 8 2 1 1190 65535 0]斡El coraz吋n me va a mil! [n][w][e]

[msg YELL_07 [Ann]]
[s][vp 8 2 1 1190 65535 0]斡S姻 que lo har茨s bien![n][w][e]

[msg YELL_08 [Ann]]
[s][vp 8 2 1 1190 65535 0]斡T雨 puedes![n][w][e]

[msg YELL_09 [Yusuke]]
[s][vp 8 2 1 1190 65535 0]斡Conc姻ntrate![n][w][e]

[msg YELL_10 [Yusuke]]
[s][vp 8 2 1 1190 65535 0]斡Prep茨rate![n][w][e]

[msg YELL_11 [Yusuke]]
[s][vp 8 2 1 1190 65535 0]斡Acu姻rdate de respirar![n][w][e]

[msg YELL_12 [Makoto]]
[s][vp 8 2 1 1190 65535 0]斡Buena suerte![n][w][e]

[msg YELL_13 [Makoto]]
[s][vp 8 2 1 1190 65535 0]斡C胤隠ete al plan! [n][w][e]

[msg YELL_14 [Makoto]]
[s][vp 8 2 1 1190 65535 0]斡La postura tambi姻n es importante![n][w][e]

[msg YELL_15 [Futaba]]
[s][vp 8 2 1 1190 65535 0]斡畏chale valor![n][w][e]

[msg YELL_16 [Futaba]]
[s][vp 8 2 1 1190 65535 0]Mierda, ojal茨 pudiera hacerte re胤r.[n][w][e]

[msg YELL_17 [Futaba]]
[s][vp 8 2 1 1190 65535 0]斡Qu姻 nervios![n][w][e]

[msg YELL_18 [Haru]]
[s][vp 8 2 1 1190 65535 0]斡T雨 puedes![n][w][e]

[msg YELL_19 [Haru]]
[s][vp 8 2 1 1190 65535 0]斡Se me va a salir el coraz吋n![n][w][e]

[msg YELL_20 [Haru]]
[s][vp 8 2 1 1190 65535 0]斡S姻 que lo har茨s bien![n][w][e]

[msg YELL_21 [Akechi]]
[s][vp 8 2 1 1190 65535 0]Venga.[n][w][e]

[msg YELL_22 [Akechi]]
[s][vp 8 2 1 1190 65535 0]夷Estar茨s bien?[n][w][e]

[msg YELL_23 [Akechi]]
[s][vp 8 2 1 1190 65535 0]No pinta mal.[n][w][e]

[msg YELL_24 [Sumire]]
[s][vp 8 2 1 1190 65535 0]斡No pierdas la concentraci吋n![n][w][e]

[msg YELL_25 [Sumire]]
[s][vp 8 2 1 1190 65535 0]斡Hazlo lo mejor que puedas![n][w][e]

[msg YELL_26 [Sumire]]
[s][vp 8 2 1 1190 65535 0]斡Estoy muy nerviosa![n][w][e]

