[msg ROUNDSTART_00 [Ryuji]]
[s][vp 8 2 1 7197 65535 0]斡Primera ronda! 斡Cuento contigo![n][w][e]

[msg ROUNDSTART_01 [Ryuji]]
[s][vp 8 2 1 7110 65535 0]斡Comencemos![n][w][e]

[msg ROUNDSTART_02 [Ryuji]]
[s][vp 8 2 1 54236 65535 0]斡El primer tiro es el importante![n][w][e]

[msg ROUNDSTART_03 [Morgana]]
[s][vp 8 2 1 1175 65535 0]斡S姻 que lo conseguir茨s![n][w][e]

[msg ROUNDSTART_04 [Morgana]]
[s][vp 8 2 1 1174 65535 0]斡Empecemos![n][w][e]

[msg ROUNDSTART_05 [Morgana]]
[s][vp 8 2 1 53126 65535 0]Calma, 夷de acuerdo?[n][w][e]

[msg ROUNDSTART_06 [Ann]]
[s][vp 8 2 1 6153 65535 0]斡Vamos, a por la primera ronda![n][w][e]

[msg ROUNDSTART_07 [Ann]]
[s][vp 8 2 1 54043 65535 0]斡Lo dejo en tus manos![n][w][e]

[msg ROUNDSTART_08 [Ann]]
[s][vp 8 2 1 6048 65535 0]斡Que comience el juego![n][w][e]

[msg ROUNDSTART_09 [Yusuke]]
[s][vp 8 2 1 4023 65535 0]Ya ha empezado.[n][w][e]

[msg ROUNDSTART_10 [Yusuke]]
[s][vp 8 2 1 53730 65535 0]El primer movimiento[n]siempre es importante.[n][w][e]

[msg ROUNDSTART_11 [Yusuke]]
[s][vp 8 2 1 4088 65535 0]斡Te lo dejo a ti![n][w][e]

[msg ROUNDSTART_12 [Makoto]]
[s][vp 8 2 1 2053 65535 0]斡Te dejo a ti primero![n][w][e]

[msg ROUNDSTART_13 [Makoto]]
[s][vp 8 2 1 53329 65535 0]斡Mant姻n la calma![n][w][e]

[msg ROUNDSTART_14 [Makoto]]
[s][vp 8 2 1 2114 65535 0]斡Lo har茨s bien! 斡T雨 puedes![n][w][e]

[msg ROUNDSTART_15 [Futaba]]
[s][vp 8 2 1 54731 65535 0]Muy bien, 斡a ver de lo que[n]eres capaz![n][w][e]

[msg ROUNDSTART_16 [Futaba]]
[s][vp 8 2 1 54738 65535 0]Rel茨jate, 夷vale?[n][w][e]

[msg ROUNDSTART_17 [Futaba]]
[s][vp 8 2 1 9052 65535 0]斡Acaba con ello![n][w][e]

[msg ROUNDSTART_18 [Haru]]
[s][vp 8 2 1 53540 65535 0]斡La primera ronda es tuya![n][w][e]

[msg ROUNDSTART_19 [Haru]]
[s][vp 8 2 1 3048 65535 0]斡S姻 t雨 mismo y dalo todo![n][w][e]

[msg ROUNDSTART_20 [Haru]]
[s][vp 8 2 1 53533 65535 0]斡Lo har茨s genial![n][w][e]

[msg ROUNDSTART_21 [Akechi]]
[s][vp 8 2 1 8127 65535 0]A ver de lo que eres capaz.[n][w][e]

[msg ROUNDSTART_22 [Akechi]]
[s][vp 8 2 1 8020 65535 0]Cuento contigo.[n][w][e]

[msg ROUNDSTART_23 [Akechi]]
[s][vp 8 2 1 8127 65535 0]Veamos c吋mo termina esto.[n][w][e]

[msg ROUNDSTART_24 [Sumire]]
[s][vp 8 2 1 57163 65535 0]斡Buena suerte![n][w][e]

[msg ROUNDSTART_25 [Sumire]]
[s][vp 8 2 1 57022 65535 0]斡T雨 puedes, te lo digo yo![n][w][e]

[msg ROUNDSTART_26 [Sumire]]
[s][vp 8 2 1 57164 65535 0]斡Tu forma de tirar es[n]muy importante tambi姻n![n][w][e]

[msg YELL_NOTFINISH_00 [Ryuji]]
[s][vp 8 2 1 7038 65535 0]Ya veremos c吋mo termina esto.[n][w][e]

[msg YELL_NOTFINISH_01 [Ryuji]]
[s][vp 8 2 1 7028 65535 0]El coraz吋n me va a mil, t胤o.[n][w][e]

[msg YELL_NOTFINISH_02 [Ryuji]]
[s][vp 8 2 1 54244 65535 0]夷E-es la hora?[n][w][e]

[msg YELL_NOTFINISH_03 [Morgana]]
[s][vp 8 2 1 1018 65535 0]斡No tires muy fuerte![n][w][e]

[msg YELL_NOTFINISH_04 [Morgana]]
[s][vp 8 2 1 1021 65535 0]夷Lo vas a lanzar?[n][w][e]

[msg YELL_NOTFINISH_05 [Morgana]]
[s][vp 8 2 1 1028 65535 0]斡Me sudan las patas![n][w][e]

[msg YELL_NOTFINISH_06 [Ann]]
[s][vp 8 2 1 6021 65535 0]Pero 斡qu姻 nervios![n][w][e]

[msg YELL_NOTFINISH_07 [Ann]]
[s][vp 8 2 1 6028 65535 0]斡Tranquilo![n][w][e]

[msg YELL_NOTFINISH_08 [Ann]]
[s][vp 8 2 1 6034 65535 0]斡Lo har茨s bien![n][w][e]

[msg YELL_NOTFINISH_09 [Yusuke]]
[s][vp 8 2 1 4023 65535 0]No te precipites ahora.[n][w][e]

[msg YELL_NOTFINISH_10 [Yusuke]]
[s][vp 8 2 1 4023 65535 0]Imag胤nate ganando...[n][w][e]

[msg YELL_NOTFINISH_11 [Yusuke]]
[s][vp 8 2 1 4087 65535 0]夷Lo vas a tirar?[n][w][e]

[msg YELL_NOTFINISH_12 [Makoto]]
[s][vp 8 2 1 2114 65535 0]S姻 t雨 mismo.[n][w][e]

[msg YELL_NOTFINISH_13 [Makoto]]
[s][vp 8 2 1 2035 65535 0]斡Todo ir茨 bien![n][w][e]

[msg YELL_NOTFINISH_14 [Makoto]]
[s][vp 8 2 1 2113 65535 0]Ya es casi la hora. [n][w][e]

[msg YELL_NOTFINISH_15 [Futaba]]
[s][vp 8 2 1 9027 65535 0]斡T-t-tranquilidad ante todo![n][w][e]

[msg YELL_NOTFINISH_16 [Futaba]]
[s][vp 8 2 1 9043 65535 0]夷Esta es tu oportunidad?[n][w][e]

[msg YELL_NOTFINISH_17 [Futaba]]
[s][vp 8 2 1 9137 65535 0]斡Lo har茨s bien![n]斡Lo que tenga que ser, ser茨![n][w][e]

[msg YELL_NOTFINISH_18 [Haru]]
[s][vp 8 2 1 3019 65535 0]斡Buena suerte![n][w][e]

[msg YELL_NOTFINISH_19 [Haru]]
[s][vp 8 2 1 3028 65535 0]Me estoy poniendo nerviosa...[n][w][e]

[msg YELL_NOTFINISH_20 [Haru]]
[s][vp 8 2 1 3127 65535 0]夷D吋nde vas a apuntar?[n][w][e]

[msg YELL_NOTFINISH_21 [Akechi]]
[s][vp 8 2 1 8127 65535 0]夷C吋mo acabar茨 esto?[n][w][e]

[msg YELL_NOTFINISH_22 [Akechi]]
[s][vp 8 2 1 8130 65535 0]夷Est茨s nervioso?[n][w][e]

[msg YELL_NOTFINISH_23 [Akechi]]
[s][vp 8 2 1 8128 65535 0]Tu postura es correcta.[n][w][e]

[msg YELL_NOTFINISH_24 [Sumire]]
[s][vp 8 2 1 57142 65535 0]斡Me va a dar un infarto![n][w][e]

[msg YELL_NOTFINISH_25 [Sumire]]
[s][vp 8 2 1 57023 65535 0]斡Lo har茨s bien![n][w][e]

[msg YELL_NOTFINISH_26 [Sumire]]
[s][vp 8 2 1 57056 65535 0]斡Se me va a salir el coraz吋n![n][w][e]

[msg YELL_FINISH_00 [Ryuji]]
[s][vp 8 2 1 7023 65535 0]斡Lo tenemos controlado![n][w][e]

[msg YELL_FINISH_01 [Ryuji]]
[s][vp 8 2 1 7045 65535 0]斡Acaba ya![n][w][e]

[msg YELL_FINISH_02 [Ryuji]]
[s][vp 8 2 1 7080 65535 0]斡Solo un poco m茨s![n][w][e]

[msg YELL_FINISH_03 [Morgana]]
[s][vp 8 2 1 1069 65535 0]夷Puedes con esto?[n][w][e]

[msg YELL_FINISH_04 [Morgana]]
[s][vp 8 2 1 1159 65535 0]Por fin hemos llegado...[n][w][e]

[msg YELL_FINISH_05 [Morgana]]
[s][vp 8 2 1 1109 65535 0]斡Solo te falta un poquito![n][w][e]

[msg YELL_FINISH_06 [Ann]]
[s][vp 8 2 1 6019 65535 0]斡Ya casi estamos![n][w][e]

[msg YELL_FINISH_07 [Ann]]
[s][vp 8 2 1 6066 65535 0]斡Casi hemos terminado![n][w][e]

[msg YELL_FINISH_08 [Ann]]
[s][vp 8 2 1 6117 65535 0]斡Es la hora de la verdad![n][w][e]

[msg YELL_FINISH_09 [Yusuke]]
[s][vp 8 2 1 4045 65535 0]Este va a ser el tiro[n]m茨s importante.[n][w][e]

[msg YELL_FINISH_10 [Yusuke]]
[s][vp 8 2 1 53737 65535 0]斡No bajes la guardia...![n][w][e]

[msg YELL_FINISH_11 [Yusuke]]
[s][vp 8 2 1 4105 65535 0]斡Solo te falta un poco![n][w][e]

[msg YELL_FINISH_12 [Makoto]]
[s][vp 8 2 1 2048 65535 0]斡No falta nada![n][w][e]

[msg YELL_FINISH_13 [Makoto]]
[s][vp 8 2 1 2114 65535 0]斡Esto es crucial![n][w][e]

[msg YELL_FINISH_14 [Makoto]]
[s][vp 8 2 1 2105 65535 0]斡Yo creo que lo tienes dominado![n][w][e]

[msg YELL_FINISH_15 [Futaba]]
[s][vp 8 2 1 9105 65535 0]斡La victoria te espera![n][w][e]

[msg YELL_FINISH_16 [Futaba]]
[s][vp 8 2 1 9055 65535 0]斡A por ello![n][w][e]

[msg YELL_FINISH_17 [Futaba]]
[s][vp 8 2 1 54715 65535 0]斡夷Ser茨 el 雨ltimo?![n][w][e]

[msg YELL_FINISH_18 [Haru]]
[s][vp 8 2 1 53522 65535 0]斡Ya casi![n][w][e]

[msg YELL_FINISH_19 [Haru]]
[s][vp 8 2 1 3105 65535 0]斡Esta partida la acabas seguro![n][w][e]

[msg YELL_FINISH_20 [Haru]]
[s][vp 8 2 1 53541 65535 0]斡Ay, el coraz吋n me va a mil![n][w][e]

[msg YELL_FINISH_21 [Akechi]]
[s][vp 8 2 1 8127 65535 0]Por fin hemos llegado.[n][w][e]

[msg YELL_FINISH_22 [Akechi]]
[s][vp 8 2 1 8156 65535 0]夷Crees que puedes acabar ya?[n][w][e]

[msg YELL_FINISH_23 [Akechi]]
[s][vp 8 2 1 8155 65535 0]No te impacientes.[n][w][e]

[msg YELL_FINISH_24 [Sumire]]
[s][vp 8 2 1 57058 65535 0]Pero 斡acaba ya![n][w][e]

[msg YELL_FINISH_25 [Sumire]]
[s][vp 8 2 1 57022 65535 0]斡Venga, vamos![n][w][e]

[msg YELL_FINISH_26 [Sumire]]
[s][vp 8 2 1 57083 65535 0]斡Ya casi lo tienes![n][w][e]

[msg SCORE_HIGH_00 [Ryuji]]
[s][vp 8 2 1 7039 65535 0]斡Muy bien![n][w][e]

[msg SCORE_HIGH_01 [Ryuji]]
[s][vp 8 2 1 7048 65535 0]斡Bien hecho![n][w][e]

[msg SCORE_HIGH_02 [Ryuji]]
[s][vp 8 2 1 7020 65535 0]斡Genial![n][w][e]

[msg SCORE_HIGH_03 [Morgana]]
[s][vp 8 2 1 1181 65535 0]斡Lo has conseguido![n][w][e]

[msg SCORE_HIGH_04 [Morgana]]
[s][vp 8 2 1 1184 65535 0]斡Hala![n][w][e]

[msg SCORE_HIGH_05 [Morgana]]
[s][vp 8 2 1 1040 65535 0]斡As胤 se hace![n][w][e]

[msg SCORE_HIGH_06 [Ann]]
[s][vp 8 2 1 6039 65535 0]斡Incre胤ble![n][w][e]

[msg SCORE_HIGH_07 [Ann]]
[s][vp 8 2 1 54037 65535 0]斡Buen trabajo![n][w][e]

[msg SCORE_HIGH_08 [Ann]]
[s][vp 8 2 1 6045 65535 0]斡Vaamos![n][w][e]

[msg SCORE_HIGH_09 [Yusuke]]
[s][vp 8 2 1 4135 65535 0]斡Fant茨stico![n][w][e]

[msg SCORE_HIGH_10 [Yusuke]]
[s][vp 8 2 1 4047 65535 0]斡Ha sido impresionante![n][w][e]

[msg SCORE_HIGH_11 [Yusuke]]
[s][vp 8 2 1 4081 65535 0]斡Lo has conseguido![n][w][e]

[msg SCORE_HIGH_12 [Makoto]]
[s][vp 8 2 1 2162 65535 0]斡Qu姻 buena![n][w][e]

[msg SCORE_HIGH_13 [Makoto]]
[s][vp 8 2 1 53340 65535 0]斡Ha sido impresionante![n][w][e]

[msg SCORE_HIGH_14 [Makoto]]
[s][vp 8 2 1 2164 65535 0]斡Ah胤 est茨![n][w][e]

[msg SCORE_HIGH_15 [Futaba]]
[s][vp 8 2 1 9040 65535 0]斡Hala, buen trabajo![n][w][e]

[msg SCORE_HIGH_16 [Futaba]]
[s][vp 8 2 1 9045 65535 0]斡Qu姻 pasada![n][w][e]

[msg SCORE_HIGH_17 [Futaba]]
[s][vp 8 2 1 9162 65535 0]斡No veas, qu姻 emoci吋n![n][w][e]

[msg SCORE_HIGH_18 [Haru]]
[s][vp 8 2 1 3040 65535 0]斡Vaya, se te da de maravilla![n][w][e]

[msg SCORE_HIGH_19 [Haru]]
[s][vp 8 2 1 3114 65535 0]Mmm, no est茨 nada mal.[n][w][e]

[msg SCORE_HIGH_20 [Haru]]
[s][vp 8 2 1 3104 65535 0]斡Hurra, lo lograste![n][w][e]

[msg SCORE_HIGH_21 [Akechi]]
[s][vp 8 2 1 8133 65535 0]Eh...[n][w][e]

[msg SCORE_HIGH_22 [Akechi]]
[s][vp 8 2 1 8134 65535 0]斡No est茨 nada mal![n][w][e]

[msg SCORE_HIGH_23 [Akechi]]
[s][vp 8 2 1 8038 65535 0]Se te da bastante bien.[n][w][e]

[msg SCORE_HIGH_24 [Sumire]]
[s][vp 8 2 1 57065 65535 0]斡H-ha sido impresionante![n][w][e]

[msg SCORE_HIGH_25 [Sumire]]
[s][vp 8 2 1 57120 65535 0]斡Conque ah胤 estabas apuntando![n][w][e]

[msg SCORE_HIGH_26 [Sumire]]
[s][vp 8 2 1 57051 65535 0]斡Enhorabuena![n][w][e]

[msg SCORE_NORMAL_00 [Ryuji]]
[s][vp 8 2 1 7088 65535 0]Vale...[n][w][e]

[msg SCORE_NORMAL_01 [Ryuji]]
[s][vp 8 2 1 7048 65535 0]No ha estado nada mal.[n][w][e]

[msg SCORE_NORMAL_02 [Ryuji]]
[s][vp 8 2 1 7038 65535 0]Ah...[n][w][e]

[msg SCORE_NORMAL_03 [Morgana]]
[s][vp 8 2 1 1020 65535 0]Conque ah胤 estabas apuntando.[n][w][e]

[msg SCORE_NORMAL_04 [Morgana]]
[s][vp 8 2 1 1174 65535 0]No est茨 mal.[n][w][e]

[msg SCORE_NORMAL_05 [Morgana]]
[s][vp 8 2 1 1035 65535 0]Mmm...[n][w][e]

[msg SCORE_NORMAL_06 [Ann]]
[s][vp 8 2 1 6020 65535 0]Eh...[n][w][e]

[msg SCORE_NORMAL_07 [Ann]]
[s][vp 8 2 1 6110 65535 0]夷Ah胤?[n][w][e]

[msg SCORE_NORMAL_08 [Ann]]
[s][vp 8 2 1 6168 65535 0]Ya veo por d吋nde vas.[n][w][e]

[msg SCORE_NORMAL_09 [Yusuke]]
[s][vp 8 2 1 4133 65535 0]Mmm, conque ah胤 ha dado...[n][w][e]

[msg SCORE_NORMAL_10 [Yusuke]]
[s][vp 8 2 1 4088 65535 0]Vale...[n][w][e]

[msg SCORE_NORMAL_11 [Yusuke]]
[s][vp 8 2 1 4090 65535 0]No est茨 mal.[n][w][e]

[msg SCORE_NORMAL_12 [Makoto]]
[s][vp 8 2 1 2081 65535 0]Con eso deber胤a servir.[n][w][e]

[msg SCORE_NORMAL_13 [Makoto]]
[s][vp 8 2 1 2064 65535 0]Conque ah胤 ha dado...[n][w][e]

[msg SCORE_NORMAL_14 [Makoto]]
[s][vp 8 2 1 2113 65535 0]Creo que con eso deber胤a servir.[n][w][e]

[msg SCORE_NORMAL_15 [Futaba]]
[s][vp 8 2 1 9098 65535 0]Vaya...[n][w][e]

[msg SCORE_NORMAL_16 [Futaba]]
[s][vp 8 2 1 9021 65535 0]No es mala elecci吋n.[n][w][e]

[msg SCORE_NORMAL_17 [Futaba]]
[s][vp 8 2 1 9081 65535 0]Ah, vale...[n][w][e]

[msg SCORE_NORMAL_18 [Haru]]
[s][vp 8 2 1 3020 65535 0]Oh, mmm...[n][w][e]

[msg SCORE_NORMAL_19 [Haru]]
[s][vp 8 2 1 3120 65535 0]No ha estado nada mal.[n][w][e]

[msg SCORE_NORMAL_20 [Haru]]
[s][vp 8 2 1 3021 65535 0]Oh, as胤 que ha ido a parar ah胤...[n][w][e]

[msg SCORE_NORMAL_21 [Akechi]]
[s][vp 8 2 1 8038 65535 0]Mm...[n][w][e]

[msg SCORE_NORMAL_22 [Akechi]]
[s][vp 8 2 1 8038 65535 0]夷Qu姻...?[n][w][e]

[msg SCORE_NORMAL_23 [Akechi]]
[s][vp 8 2 1 8020 65535 0]Creo que lo pillo...[n][w][e]

[msg SCORE_NORMAL_24 [Sumire]]
[s][vp 8 2 1 57173 65535 0]As胤 que ese era tu plan.[n][w][e]

[msg SCORE_NORMAL_25 [Sumire]]
[s][vp 8 2 1 57119 65535 0]Aj茨...[n][w][e]

[msg SCORE_NORMAL_26 [Sumire]]
[s][vp 8 2 1 57113 65535 0]夷Ha ido a parar ah胤?[n][w][e]

[msg OUT_00 [Ryuji]]
[s][vp 8 2 1 7021 65535 0]No te preocupes por eso.[n][w][e]

[msg OUT_01 [Ryuji]]
[s][vp 8 2 1 7191 65535 0]Ostras...[n][w][e]

[msg OUT_02 [Ryuji]]
[s][vp 8 2 1 7085 65535 0]Cosas que pasan.[n][w][e]

[msg OUT_03 [Morgana]]
[s][vp 8 2 1 1022 65535 0]Mierda...[n][w][e]

[msg OUT_04 [Morgana]]
[s][vp 8 2 1 1025 65535 0]Jo, t胤o...[n][w][e]

[msg OUT_05 [Morgana]]
[s][vp 8 2 1 1173 65535 0]No te desanimes.[n][w][e]

[msg OUT_06 [Ann]]
[s][vp 8 2 1 6021 65535 0]Oh, no...[n][w][e]

[msg OUT_07 [Ann]]
[s][vp 8 2 1 6119 65535 0]夷Eh? 夷He fallado?[n][w][e]

[msg OUT_08 [Ann]]
[s][vp 8 2 1 54038 65535 0]斡No te preocupes![n][w][e]

[msg OUT_09 [Yusuke]]
[s][vp 8 2 1 4065 65535 0]Qu姻 suerte has tenido...[n][w][e]

[msg OUT_10 [Yusuke]]
[s][vp 8 2 1 4074 65535 0]Qu姻 verg鵜enza...[n][w][e]

[msg OUT_11 [Yusuke]]
[s][vp 8 2 1 4026 65535 0]A veces solo es cuesti吋n de suerte.[n][w][e]

[msg OUT_12 [Makoto]]
[s][vp 8 2 1 2028 65535 0]Mmm...[n][w][e]

[msg OUT_13 [Makoto]]
[s][vp 8 2 1 2064 65535 0]Qu姻 mala suerte...[n][w][e]

[msg OUT_14 [Makoto]]
[s][vp 8 2 1 2029 65535 0]No te preocupes.[n][w][e]

[msg OUT_15 [Futaba]]
[s][vp 8 2 1 9038 65535 0]斡Nooo![n][w][e]

[msg OUT_16 [Futaba]]
[s][vp 8 2 1 9029 65535 0]斡Estamos acabados![n][w][e]

[msg OUT_17 [Futaba]]
[s][vp 8 2 1 54733 65535 0]斡Si te obsesionas, ya has perdido![n][w][e]

[msg OUT_18 [Haru]]
[s][vp 8 2 1 3024 65535 0]Jop姻...[n][w][e]

[msg OUT_19 [Haru]]
[s][vp 8 2 1 3110 65535 0]Intenta no deprimirte mucho.[n][w][e]

[msg OUT_20 [Haru]]
[s][vp 8 2 1 3027 65535 0]Ha sido duro de pelar.[n][w][e]

[msg OUT_21 [Akechi]]
[s][vp 8 2 1 8020 65535 0]Has fallado...[n][w][e]

[msg OUT_22 [Akechi]]
[s][vp 8 2 1 8003 65535 0]夷Ad吋nde estabas apuntando?[n][w][e]

[msg OUT_23 [Akechi]]
[s][vp 8 2 1 8028 65535 0]Incre胤ble...[n][w][e]

[msg OUT_24 [Sumire]]
[s][vp 8 2 1 57063 65535 0]斡N-no te preocupes![n][w][e]

[msg OUT_25 [Sumire]]
[s][vp 8 2 1 57048 65535 0]No ha salido como me esperaba.[n][w][e]

[msg OUT_26 [Sumire]]
[s][vp 8 2 1 57088 65535 0]斡No decaigas![n][w][e]

[msg OVER60_00 [Ryuji]]
[s][vp 8 2 1 54237 65535 0]斡Menos de 60, tronco![n][w][e]

[msg OVER60_01 [Ryuji]]
[s][vp 8 2 1 54237 65535 0]斡夷Lo hab姻is visto?![n]斡Menos de 60![n][w][e]

[msg OVER60_02 [Ryuji]]
[s][vp 8 2 1 54237 65535 0]斡Guay! 斡Menos de 60![n][w][e]

[msg OVER60_03 [Morgana]]
[s][vp 8 2 1 53127 65535 0]斡Menos de 60! [n][w][e]

[msg OVER60_04 [Morgana]]
[s][vp 8 2 1 53127 65535 0]斡Estamos en menos de 60![n][w][e]

[msg OVER60_05 [Morgana]]
[s][vp 8 2 1 53127 65535 0]斡Vamos! 斡Menos de 60![n][w][e]

[msg OVER60_06 [Ann]]
[s][vp 8 2 1 54036 65535 0]斡Hala, est茨s en menos de 60![n][w][e]

[msg OVER60_07 [Ann]]
[s][vp 8 2 1 54036 65535 0]Pero 斡mira esa puntuaci吋n![n]斡Menos de 60![n][w][e]

[msg OVER60_08 [Ann]]
[s][vp 8 2 1 54036 65535 0]夷Cu茨nto nos hace falta?[n][w][e]

[msg OVER60_09 [Yusuke]]
[s][vp 8 2 1 53731 65535 0]斡Ah, est茨s en menos de 60![n][w][e]

[msg OVER60_10 [Yusuke]]
[s][vp 8 2 1 53731 65535 0]Mmm, ya casi lo tienes.[n][w][e]

[msg OVER60_11 [Yusuke]]
[s][vp 8 2 1 53731 65535 0]Parece que solo necesitas[n]un poco menos de 60.[n][w][e]

[msg OVER60_12 [Makoto]]
[s][vp 8 2 1 53330 65535 0]斡Has bajado de 60![n][w][e]

[msg OVER60_13 [Makoto]]
[s][vp 8 2 1 53330 65535 0]斡Solo te faltan un par de tiros![n][w][e]

[msg OVER60_14 [Makoto]]
[s][vp 8 2 1 53330 65535 0]Solo un poco m茨s...[n][w][e]

[msg OVER60_15 [Futaba]]
[s][vp 8 2 1 54732 65535 0]斡Bien! Est茨s en menos de 60.[n][w][e]

[msg OVER60_16 [Futaba]]
[s][vp 8 2 1 54732 65535 0]斡Anda, est茨s por debajo de 60![n][w][e]

[msg OVER60_17 [Futaba]]
[s][vp 8 2 1 54732 65535 0]斡Genial, ya casi lo tienes![n][w][e]

[msg OVER60_18 [Haru]]
[s][vp 8 2 1 53535 65535 0]斡Ya est茨s por debajo de 60![n][w][e]

[msg OVER60_19 [Haru]]
[s][vp 8 2 1 53535 65535 0]斡Est茨s que lo tiras! 斡Solo un poco m茨s![n][w][e]

[msg OVER60_20 [Haru]]
[s][vp 8 2 1 53535 65535 0]斡Anda, si ya casi has acabado![n][w][e]

[msg OVER60_21 [Akechi]]
[s][vp 8 2 1 8131 65535 0]Conque menos de 60...[n][w][e]

[msg OVER60_22 [Akechi]]
[s][vp 8 2 1 8131 65535 0]Ya casi est茨s.[n][w][e]

[msg OVER60_23 [Akechi]]
[s][vp 8 2 1 8131 65535 0]Tu puntuaci吋n es inferior a 60.[n][w][e]

[msg OVER60_24 [Sumire]]
[s][vp 8 2 1 57157 65535 0]斡Oh, mira! 斡Menos de 60![n][w][e]

[msg OVER60_25 [Sumire]]
[s][vp 8 2 1 57157 65535 0]斡T雨 puedes![n][w][e]

[msg OVER60_26 [Sumire]]
[s][vp 8 2 1 57157 65535 0]斡Solo te queda poco menos de 60![n][w][e]

