[msg MSG_NML06_FIND_01_01]
[s]斡夷Qui姻n anda ah胤?![n][f 1 2 65535][e]

[msg MSG_NML06_FIND_01_02]
[s]斡Eh, t雨![n][f 1 2 65535][e]

[msg MSG_NML06_FIND_01_03]
[s]斡Desgraciados![n][f 1 2 65535][e]

[msg MSG_NML06_FIND_01_04]
[s]夷Eh? 斡夷Qui姻nes sois?![n][f 1 2 65535][e]

[msg MSG_NML06_FIND_01_05]
[s]斡夷Qui姻nes sois, cabrones?![n][f 1 2 65535][e]

[msg MSG_NML06_PURSUE_01_01]
[s]斡Eh! 斡Esperad![n][f 1 2 65535][e]

[msg MSG_NML06_PURSUE_01_02]
[s]斡Alto![n][f 1 2 65535][e]

[msg MSG_NML06_PURSUE_01_03]
[s]斡夷Qui姻nes sois?! 斡Alto![n][f 1 2 65535][e]

[msg MSG_NML06_PURSUE_01_04]
[s]斡Eh! 斡Alto![n][f 1 2 65535][e]

[msg MSG_NML06_PURSUE_01_05]
[s]斡Alto ah胤, escoria inmunda![n][f 1 2 65535][e]

[msg MSG_NML06_LOST_01_01]
[s]斡Mierda! 夷Ad吋nde han ido...?[n][f 1 2 65535][e]

[msg MSG_NML06_LOST_01_02]
[s]斡Grrr![n][f 1 2 65535][e]

[msg MSG_NML06_LOST_01_03]
[s]斡夷D吋nde se han metido?![n][f 1 2 65535][e]

[msg MSG_NML06_LOST_01_04]
[s]斡夷Eh?! 斡夷D吋nde se han metido?![n][f 1 2 65535][e]

[msg MSG_NML06_LOST_01_05]
[s]斡夷Ad吋nde han ido?! 斡Joder![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_01_01]
[s]No veo nada fuera de lo normal.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_01_02]
[s]No hay ning雨n problema.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_01_03]
[s]Todo despejado por aqu胤.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_01_04]
[s]Todo en orden por el momento.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_01_05]
[s]Mmm, ning雨n problema.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_01_06]
[s]De momento, nada fuera de lo[n]normal. Seguir姻 patrullando.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_01_07]
[s]Todo est茨 despejado.[n]Seguir姻 patrullando.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_01_08]
[s]Si alg雨n intruso piensa[n]que se puede colar por aqu胤,[n]se equivoca de cabo a rabo.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_01_09]
[s]Venga quien venga,[n]solo har姻 mi trabajo.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_01_10]
[s]Pronto ver茨n que desafiar[n]a la directora es una tonter胤a.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_01_01]
[s]Intrusos... 夷D吋nde podr茨n estar?[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_01_02]
[s]斡夷D吋nde os escond姻is?![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_01_03]
[s]Os vais a enterar[n]cuando os encuentre...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_01_04]
[s]斡Eh! 斡夷D吋nde est茨is?![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_01_05]
[s]斡Joder! 斡夷D吋nde se han metido?![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_01_06]
[s]No tendr姻 piedad con nadie que[n]intente hacer da隠o a la directora.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_01_07]
[s]Es hora de mostrar[n]lo que un verdadero profesional[n]es capaz de hacer.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_01_08]
[s]斡Me asegurar姻 de que vuestra[n]muerte sea r茨pida! 斡Salid![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_01_09]
[s]Me da igual lo que grit姻is.[n]Ciertos pecados son imperdonables.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_01_10]
[s]Aqu胤 tampoco est茨n...[n]夷Se habr茨n ido a otro sitio?[n][f 1 2 65535][e]

[msg MSG_NML06_REPORT_01_01]
[s]Hay problemas. Debo informar[n]a la directora.[n][f 1 2 65535][e]

[msg MSG_NML06_REPORT_01_02]
[s]斡Informar姻 de esta situaci吋n[n]a la directora de inmediato![n][f 1 2 65535][e]

[msg MSG_NML06_REPORT_01_03]
[s]Hay mucho sospechoso por aqu胤...[n]Debo avisar a la directora.[n][f 1 2 65535][e]

[msg MSG_NML06_REPORT_01_04]
[s]Tengo que avisar a la directora.[n]No consiento que estas alima隠as[n]hagan lo que les plazca.[n][f 1 2 65535][e]

[msg MSG_NML06_REPORT_01_05]
[s]斡Ser姻is...! Os vais a enterar[n]cuando venga la directora.[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01_]
[s]Por mucho que me cueste,[n]no pienso bajar la guardia.[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__2]
[s]Da igual qui姻n venga... 斡No dejar姻[n]de proteger este lugar![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__3]
[s]Hoy tambi姻n debo asegurar[n]la protecci吋n de este lugar.[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__4]
[s]No s姻 si conmigo bastar茨[n]para protegerlo...[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__5]
[s]Cu茨nta responsabilidad...[n]夷Por qu姻 tengo que ser[n]yo quien lo proteja?[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01]
[s]斡Directora, he visto a unos[n]intrusos! 斡Deme instrucciones,[n]por favor![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_2]
[s]斡He visto a los intrusos! 斡Solicito[n]un refuerzo en la seguridad![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_3]
[s]Veo algunos clientes problem茨ticos.[n]夷Qu姻 hago, directora?[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_4]
[s]He descubierto a unos agitadores[n]de masas. Solicito refuerzos.[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_5]
[s]斡He dado con unos invitados[n]sospechosos! 夷Qu姻 hago?[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_0]
[s]Ufff... Mi siguiente tarea es...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_0_2]
[s]斡Les ense隠ar姻 mis asombrosos[n]trucos![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_0_3]
[s]夷Intrusos? Supongo que hay gente[n]que no tiene modales.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_0_4]
[s]斡La directora no tiene por qu姻[n]ensuciarse las manos[n]con unos intrusos! Yo me encargo.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_0_5]
[s]No me puedo creer que se est姻n[n]jugando la vida. Aunque bueno,[n]all茨 ellos...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_0_6]
[s]Me resulta interesante que[n]arriesguen sus vidas de esta forma.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_0_7]
[s]Qu姻 suerte tengo de poder[n]pasar el rato con un juego[n]tan estimulante...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_0_8]
[s]Los humanos siguen creyendo[n]en el poder de la suerte...[n]hasta que mueren.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_0_9]
[s]Este trabajo es un poco distinto[n]de lo normal, pero me sigo jugando[n]la vida...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_1]
[s]Me pareci吋 o胤r algo...[n]Quiz茨 se le ha ca胤do una moneda[n]a alguien.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_1_2]
[s]Les quitar姻 a los intrusos todo[n]lo que tienen... Hasta sus vidas.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_1_3]
[s]Espero librarme pronto de estos[n]intrusos para poder continuar[n]con mi trabajo.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_1_4]
[s]Los intrusos se juegan la vida[n]igual que el resto de pobres[n]desgraciados que hay por aqu胤.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_1_5]
[s]Ups, todo este estr姻s me est茨[n]dejando la cara como una piedra.[n]Tengo que sonre胤r m茨s.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_1_6]
[s]Se arrepentir茨n de haber venido[n]si cre胤an que iba a ser divertido.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_1_7]
[s]Har姻 que se arrepientan de haberse[n]metido con la directora.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_1_8]
[s]La vida de unos ladrones no vale[n]nada. Espero que al menos[n]me entretengan un poco.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_1_9]
[s]夷Realmente vale la pena[n]que arriesgue mi vida[n]por unos intrusos?[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_1_10]
[s]Aprovecharse de todo este caos[n]es una jugada muy rastrera.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_01_2]
[s]Les ense隠ar姻 c吋mo hace las cosas[n]un verdadero profesional.[n][f 1 2 65535][e]

[msg MSG_NML06_FIND_02_01]
[s]夷Qui姻n es?[n][f 1 2 65535][e]

[msg MSG_NML06_FIND_02_02]
[s]斡Intrusos![n][f 1 2 65535][e]

[msg MSG_NML06_FIND_02_03]
[s]斡All胤 hay alguien![n][f 1 2 65535][e]

[msg MSG_NML06_FIND_02_04]
[s]夷Qu姻? 斡夷Qui姻n anda ah胤?![n][f 1 2 65535][e]

[msg MSG_NML06_FIND_02_05]
[s]斡Ahhh! 斡夷Intrusos?![n][f 1 2 65535][e]

[msg MSG_NML06_PURSUE_02_01]
[s]斡Esperad![n][f 1 2 65535][e]

[msg MSG_NML06_PURSUE_02_02]
[s]斡De aqu胤 no se escapa nadie![n][f 1 2 65535][e]

[msg MSG_NML06_PURSUE_02_03]
[s]斡Intrusos! 斡De aqu胤 no vais[n]a escapar![n][f 1 2 65535][e]

[msg MSG_NML06_PURSUE_02_04]
[s]斡Eh, intrusos![n][f 1 2 65535][e]

[msg MSG_NML06_PURSUE_02_05]
[s]斡Alto! 斡Malditos![n][f 1 2 65535][e]

[msg MSG_NML06_LOST_02_01]
[s]斡夷Los he perdido?![n][f 1 2 65535][e]

[msg MSG_NML06_LOST_02_02]
[s]斡夷D吋nde os hab姻is metido?![n][f 1 2 65535][e]

[msg MSG_NML06_LOST_02_03]
[s]斡夷Qu姻?! Han desaparecido...[n][f 1 2 65535][e]

[msg MSG_NML06_LOST_02_04]
[s]斡夷No est茨n aqu胤?![n]斡夷D吋nde estar茨n?![n][f 1 2 65535][e]

[msg MSG_NML06_LOST_02_05]
[s]斡Esos cabrones![n]斡夷D吋nde est茨n?![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_02_01]
[s]No hay nada fuera de lo normal.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_02_02]
[s]Nadie sospechoso por aqu胤.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_02_03]
[s]夷Intrusos? Por aqu胤 no hay ni uno.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_02_04]
[s]夷Eh? 夷No ser茨...? Qu姻 va, deben[n]de ser cosas m胤as.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_02_05]
[s]夷Eh? No, por aqu胤 no hay intrusos.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_02_06]
[s]斡Ayyy, se me han enganchado[n]las medias![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_02_07]
[s]Siento que me miran[n]con ojos lascivos...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_02_08]
[s]夷C吋mo os atrev姻is a darme[n]m茨s trabajo, escoria? 斡Maldita sea![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_02_09]
[s]Someter a la gente me produce[n]un placer inimaginable.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_NML_02_10]
[s]斡Oh, intrusos![n]斡Aqu胤 os espero![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_02_01]
[s]Esos intrusos...[n]夷D吋nde est茨n?[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_02_02]
[s]Encontrar姻 a los intrusos, no[n]importa el tiempo que tenga[n]que estar busc茨ndolos.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_02_03]
[s]夷D吋nde estar茨n?[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_02_04]
[s]Tengo que estar atento[n]por si hay intrusos.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_02_05]
[s]Los encontrar姻...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_02_06]
[s]Ojal茨 tuviese la frialdad y[n]la crueldad de la directora.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_02_07]
[s]Me ocupar姻 tan bien de ellos que[n]el puro 姻xtasis los matar茨.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_02_08]
[s]Se pondr茨n a suplicarme de[n]rodillas... pero nunca los perdonar姻.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_02_09]
[s]斡夷Y ese ruido?![n]Esto es demasiado estresante...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_ALT_02_10]
[s]夷Cu茨l ser胤a un buen castigo?[n]Quiz茨 los obligue a obedecerme[n]en cuerpo y alma...[n][f 1 2 65535][e]

[msg MSG_NML06_REPORT_02_01]
[s]斡Voy a informar de esto[n]a la directora![n][f 1 2 65535][e]

[msg MSG_NML06_REPORT_02_02]
[s]斡Os la vais a cargar![n]斡Pienso informar a la directora![n][f 1 2 65535][e]

[msg MSG_NML06_REPORT_02_03]
[s]斡Voy a informar a la directora[n]para que refuerce la seguridad![n][f 1 2 65535][e]

[msg MSG_NML06_REPORT_02_04]
[s]斡Esto es imperdonable![n]斡Debo informar a la directora![n][f 1 2 65535][e]

[msg MSG_NML06_REPORT_02_05]
[s]斡D-debo informar a la directora[n]de inmediato![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02_]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02__2]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02__3]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02__4]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02__5]
[s]......[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02]
[s]斡Directora! 斡Aqu胤 hay unos[n]invitados problem茨ticos![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02_2]
[s]斡Invitados extra隠os a la vista![n]斡Hay que reforzar la seguridad![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02_3]
[s]斡Tenemos unos objetivos[n]problem茨ticos por aqu胤! 斡Directora,[n]dame una orden, por favor![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02_4]
[s]斡Sospechosos encontrados![n]斡Se debe reforzar la seguridad![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02_5]
[s]斡Aqu胤 hay unos extra隠os[n]que est茨n causando problemas![n]斡Reforcemos la seguridad![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_0]
[s]*suspiro* Qu姻 cansancio.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_0_2]
[s]斡Todo estr姻s desaparecer茨[n]de mi vida cuando atrape[n]a esos intrusos![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_0_3]
[s]Siento que me miran[n]con ojos lascivos...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_0_4]
[s]Esos intrusos tienen que ser[n]unos cr胤os est雨pidos o unos viejos[n]calvos. 斡Qu姻 asco![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_0_5]
[s]斡La directora me dar茨 un aumento[n]cuando atrape a los intrusos![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_0_6]
[s]Uf... Esto es un tost吋n...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_0_7]
[s]夷Solo tengo que atrapar[n]a los intrusos?[n]Puedo matarlos, 夷verdad?[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_0_8]
[s]夷C吋mo os atrev姻is a darme[n]m茨s trabajo, escoria? 斡Maldita sea![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_0_9]
[s]斡Ayyy, se me han enganchado[n]las medias![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_1]
[s]Me ocupar姻 tan bien de ellos que[n]el puro 姻xtasis los matar茨.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_1_2]
[s]斡Aaah! Estos tacones[n]me est茨n matando.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_1_3]
[s]Se pondr茨n a suplicarme de[n]rodillas... pero nunca los perdonar姻.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_1_4]
[s]斡夷Y ese ruido?![n]Esto es demasiado estresante...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_1_5]
[s]夷De verdad hay intrusos[n]aqu胤? Seguro que todo el mundo[n]est茨 paranoico por nada.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_1_6]
[s]Someter a la gente me produce[n]un placer inimaginable.[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_1_7]
[s]斡Oh, intrusos![n]斡Aqu胤 os espero![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_1_8]
[s]夷Eh? Pero 斡si no hay nadie![n]斡Si vais a venir a por m胤, hacedlo[n]de una vez! Madre m胤a...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_1_9]
[s]斡Ay, leches, se me est茨[n]corriendo el maquillaje![n]Ufff, 斡me los voy a cargar![n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_1_10]
[s]夷Cu茨l ser胤a un buen castigo?[n]Quiz茨 los obligue a obedecerme[n]en cuerpo y alma...[n][f 1 2 65535][e]

[msg MSG_NML06_MNLG_FREE_02_2]
[s]Ojal茨 tuviese la frialdad y[n]la crueldad de la directora.[n][f 1 2 65535][e]

