[msg MSG_NML03_FIND_01_01]
[s]斡夷Qui姻n anda ah胤?![n]斡Hay alguien cerca![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_01_02]
[s]斡Ah胤! 斡Acabo de ver algo ah胤![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_01_03]
[s]夷Qu姻?[n]斡夷Qui姻n anda ah胤?![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_01_04]
[s]斡夷Qui姻n anda ah胤?![n]斡Hay alguien cerca![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_01_05]
[s]斡夷Eh?! Hab胤a... alguien ah胤, 夷no?[n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_01_01]
[s]斡Alto! 斡夷C吋mo hab姻is entrado?![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_01_02]
[s]斡No escapar姻is, ladrones![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_01_03]
[s]斡Alto! 斡No os dejar姻 escapar![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_01_04]
[s]斡No cre茨is que podr姻is huir![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_01_05]
[s]斡No ten姻is escapatoria! 斡Alerta,[n]intrusos! 斡Rodeadlos![n][f 1 2 65535][e]

[msg MSG_NML03_LOST_01_01]
[s]Los he perdido... 夷D吋nde os hab姻is[n]escondido? 斡Salid![n][f 1 2 65535][e]

[msg MSG_NML03_LOST_01_02]
[s]斡Mierda![n]Los he perdido...[n][f 1 2 65535][e]

[msg MSG_NML03_LOST_01_03]
[s]Son r茨pidos... 夷D吋nde se han metido?[n][f 1 2 65535][e]

[msg MSG_NML03_LOST_01_04]
[s]斡Deber胤an seguir por la zona![n]Os encontrar姻...[n][f 1 2 65535][e]

[msg MSG_NML03_LOST_01_05]
[s]斡夷Han desaparecido?![n]Ni que fueran magos.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_01]
[s]Mientras yo est姻 aqu胤,[n]no pasar茨 ning雨n intruso.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_02]
[s]或斡Si quer姻is pasar por aqu胤,[n]tendr姻is que derrotarme!位.[n]Eso, tengo que practicar.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_03]
[s]No dejar姻 que nadie[n]pase por aqu胤. Nunca.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_04]
[s]Ning雨n intruso podr胤a haber llegado[n]tan lejos...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_05]
[s]No puedo dejar que nadie pase[n]por aqu胤...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_06]
[s]Quiero darle un buen pu隠etazo[n]a alguien, me da igual a qui姻n.[n]Ladrones, ni隠os, qu姻 m茨s da...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_07]
[s]Ah, me encanta el olor del dinero...[n]Podr胤a pasarme el d胤a entero[n]oliendo estos fajos de billetes.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_08]
[s]斡El se隠or Kaneshiro se preocupa[n]demasiado! Aunque no puedo[n]culparlo, con el dinero que tiene...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_09]
[s]Venga, imb姻ciles. Venid aqu胤...[n]斡Os hundir姻 la maldita cara![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_01_10]
[s]Las ganancias de hoy han sido[n]tan buenas como siempre. 斡El se隠or[n]Kaneshiro se est茨 forrando![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_01]
[s]No escapar姻is. Os encontrar姻,[n]cueste lo que cueste.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_02]
[s]夷D吋nde os hab姻is escondido?[n]No escapar姻is...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_03]
[s]No soy como esos zoquetes.[n]No dejar姻 que nadie escape.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_04]
[s]斡Los encontrar姻 y los capturar姻![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_05]
[s]夷Est茨n por aqu胤? No, 夷verdad?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_06]
[s]夷Hay alguien ah胤?[n]斡Venid a por m胤![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_07]
[s]Aqu胤 no hay nada.[n]Pero deber胤a volver a comprobarlo...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_08]
[s]斡Aqu胤 no hay nadie![n]斡Y por ah胤 tampoco![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_09]
[s]Si los intrusos aparecen...[n]斡los matar姻 con mis amigos![n]斡Ja, ja![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_01_10]
[s]斡Vengaa! 斡Salid![n]No os har姻 da隠o... 斡Ja, ja![n][f 1 2 65535][e]

[msg MSG_NML03_REPORT_01_01]
[s]斡Debo avisar al presidente[n]del banco![n][f 1 2 65535][e]

[msg MSG_NML03_REPORT_01_02]
[s]Debo informar al presidente[n]del banco para que aumente[n]la seguridad.[n][f 1 2 65535][e]

[msg MSG_NML03_REPORT_01_03]
[s]斡Debemos informar al presidente[n]del banco de inmediato![n][f 1 2 65535][e]

[msg MSG_NML03_REPORT_01_04]
[s]斡Tengo que pedirle al presidente[n]del banco que aumente la seguridad![n][f 1 2 65535][e]

[msg MSG_NML03_REPORT_01_05]
[s]斡Ya ver姻is! 斡Voy a aumentar[n]la seguridad![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01_]
[s]No dejar姻 que se lo lleven,[n]de ninguna manera.[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__2]
[s]Si no lo protejo, el se隠or[n]Kaneshiro me matar茨...[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__3]
[s]Este es mi cometido. Lo proteger姻[n]cueste lo que cueste.[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__4]
[s]斡Por favor, que no venga nadie[n]ahora mismo![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_01__5]
[s]Me meter胤a en problemas si alguien[n]lo robara... Tengo que protegerlo[n]con todas mis fuerzas.[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01]
[s]斡Se隠or Kaneshiro![n]斡Hay un intruso![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_2]
[s]斡Informando![n]斡He encontrado intrusos![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_3]
[s]斡Hay intrusos! 斡Tenga cuidado,[n]se隠or Kaneshiro![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_4]
[s]斡I-intrusos! 斡Se隠or Kaneshiro![n]斡He encontrado intrusos![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_01_5]
[s]斡Intrusos detectados![n]斡Intrusos detectados![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0]
[s]Aqu胤 no hay nadie.[n]夷Qu姻 esperaba encontrar?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_2]
[s]夷Acaso es posible colarse aqu胤?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_3]
[s]Lingotes de oro... Nadie se dar茨[n]cuenta si me llevo un par, 夷verdad?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_4]
[s]*suspiro* Ojal茨 contrataran a m茨s[n]personal. Me gustar胤a tener[n]m茨s descansos...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_5]
[s]夷Cu茨nto tiempo m茨s tengo que[n]estar aqu胤, haciendo guardia[n]para nada?[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_6]
[s]Quiero darle un buen pu隠etazo[n]a alguien, me da igual a qui姻n.[n]Ladrones, ni隠os, qu姻 m茨s da...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_7]
[s]Ah, me encanta el olor del dinero...[n]Podr胤a pasarme el d胤a entero[n]oliendo estos fajos de billetes.[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_8]
[s]斡El se隠or Kaneshiro se preocupa[n]demasiado! Aunque no puedo[n]culparlo, con el dinero que tiene...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_0_9]
[s]夷Hay alguien ah胤?[n]斡Venid a por m胤![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1]
[s]Si no mantengo este lugar a salvo,[n]me quedar姻 sin trabajo...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_2]
[s]斡Buah, lo que dar胤a por tomarme[n]una cerveza con el se隠or Kaneshiro![n]斡Ja, ja, ja![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_3]
[s]斡Aqu胤 no hay nadie![n]斡Y por ah胤 tampoco![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_4]
[s]Si los intrusos aparecen...[n]斡los matar姻 con mis amigos![n]斡Ja, ja![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_5]
[s]Los cr胤os son est雨pidos[n]por desafiar a los adultos...[n]斡Hay que ver![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_6]
[s]Venga, imb姻ciles. Venid aqu胤...[n]斡Os hundir姻 la maldita cara![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_7]
[s]Aqu胤 no hay nada.[n]Pero deber胤a volver a comprobarlo...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_8]
[s]Las ganancias de hoy han sido[n]tan buenas como siempre. 斡El se隠or[n]Kaneshiro se est茨 forrando![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_9]
[s]斡Nosotros nos ocupamos[n]de la seguridad! Siempre estamos[n]en guardia...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_1_10]
[s]Jooo, qu姻 tost吋n... Ojal茨 viniera[n]alguien... Qu姻... aburrimiento...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_FREE_01_2]
[s]斡Vengaa! 斡Salid![n]No os har姻 da隠o... 斡Ja, ja![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_02_01]
[s]斡Guau! 斡Guau, guau![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_02_02]
[s]斡Auuuuuu![n][f 1 2 65535][e]

[msg MSG_NML03_FIND_02_03]
[s]斡Guau, guau, guau![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_02_01]
[s]斡Guau! 斡Guau, guau![n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_02_02]
[s]Grrrrrr...[n][f 1 2 65535][e]

[msg MSG_NML03_PURSUE_02_03]
[s]斡Guau! Grrr... 斡Guau![n][f 1 2 65535][e]

[msg MSG_NML03_LOST_02_01]
[s]斡Guau! 斡Guau![n][f 1 2 65535][e]

[msg MSG_NML03_LOST_02_02]
[s]斡Guau![n][f 1 2 65535][e]

[msg MSG_NML03_LOST_02_03]
[s]Grrr...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_02_01]
[s]*olfateo* *olfateo*[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_02_02]
[s]*jadeo* *jadeo* *jadeo*[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_NML_02_03]
[s]Rrr... Grrr...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_02_01]
[s]*olfateo* *olfateo*[n]Guau... Grrr...[n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_02_02]
[s]斡Auuuuuu![n][f 1 2 65535][e]

[msg MSG_NML03_MNLG_ALT_02_03]
[s]斡Guau![n]*olfateo* *olfateo*[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02_]
[s]Grrr...[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02__2]
[s]*olfateo* *olfateo*[n]斡Guau, guau![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_GUARD_02__3]
[s]*jadeo* *jadeo* *jadeo*[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02]
[s]Grrr...[n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02_2]
[s]*olfateo* *olfateo*[n]斡Guau, guau![n][f 1 2 65535][e]

[msg MSG_STG01_MNLG_DEFEND_02_3]
[s]*jadeo* *jadeo* *jadeo*[n][f 1 2 65535][e]

