[msg CMM_EVENT_OPEN]
[s][vp 1 0 0 0 0 0]斡Has desbloqueado al Confidente[n]del Hierofante![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Fusionar Personas[n]de este arcano te dar茨 EXP[n]gracias a la Explosi吋n arcana.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_2]
[s][vp 1 0 0 0 0 0]斡El Confidente del Hierofante[n]ha alcanzado el [clr 2]nivel 2[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Sojiro te ha ense隠ado[n]a preparar [clr 1]Caf姻 b茨sico[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_3]
[s][vp 1 0 0 0 0 0]斡El Confidente del Hierofante[n]ha alcanzado el [clr 2]nivel 3[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_4]
[s][vp 1 0 0 0 0 0]斡El Confidente del Hierofante[n]ha alcanzado el [clr 2]nivel 4[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Sojiro te ha ense隠ado[n]a preparar [clr 1]Curry Leblanc[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_5]
[s][vp 1 0 0 0 0 0]斡El Confidente del Hierofante[n]ha alcanzado el [clr 2]nivel 5[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_6]
[s][vp 1 0 0 0 0 0]斡El Confidente del Hierofante[n]ha alcanzado el [clr 2]nivel 6[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Sojiro te ha ense隠ado[n]a preparar [clr 1]Caf姻 superior[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_7]
[s][vp 1 0 0 0 0 0]斡El Confidente del Hierofante[n]ha alcanzado el [clr 2]nivel 7[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_8]
[s][vp 1 0 0 0 0 0]斡El Confidente del Hierofante[n]ha alcanzado el [clr 2]nivel 8[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_9]
[s][vp 1 0 0 0 0 0]斡El Confidente del Hierofante[n]ha alcanzado el [clr 2]nivel 9[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Sojiro te ha ense隠ado[n]los [clr 1]Secretos del curry[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKMAX]
[s][vp 1 0 0 0 0 0]斡El Confidente del Hierofante[n]ha alcanzado el [clr 2]nivel m茨ximo[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Sojiro te ha ense隠ado[n]a preparar [clr 1]Curry superior[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_UNLOCK]
[s][vp 1 0 0 0 0 0]Ya puedes fusionar a [clr 1]Kouryuu[clr 27],[n]la Persona m茨s poderosa[n]del arcano del Hierofante.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_REVERSE]
[s][vp 1 0 0 0 0 0]Al Confidente del Hierofante[n]le asalta la duda.[n]No recibir茨s beneficio alguno[n]hasta que limpies tu nombre.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_UPRIGHT]
[s][vp 1 0 0 0 0 0]Has disipado la duda[n]del Confidente del Hierofante.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_BROKEN]
[s][vp 1 0 0 0 0 0]La relaci吋n con el Confidente[n]del Hierofante se ha roto.[n]Ya no hay pacto, as胤 que[n]no recibir茨s ning雨n beneficio.[n][f 1 3 65535][w][e]

