[msg CMM_EVENT_OPEN]
[s][vp 1 0 0 0 0 0]斡Has desbloqueado al Confidente[n]del Emperador![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Fusionar Personas[n]de este arcano te dar茨 EXP[n]gracias a la Explosi吋n arcana.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Yusuke ya puede usar[n][clr 1]Duplicaci吋n de cartas[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_2]
[s][vp 1 0 0 0 0 0]斡El Confidente del Emperador[n]ha alcanzado el [clr 2]nivel 2[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_3]
[s][vp 1 0 0 0 0 0]斡El Confidente del Emperador[n]ha alcanzado el [clr 2]nivel 3[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Yusuke ya puede usar[n][clr 1]Golpe de gracia[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_4]
[s][vp 1 0 0 0 0 0]斡El Confidente del Emperador[n]ha alcanzado el [clr 2]nivel 4[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Yusuke ya puede usar [n][clr 1]Mediaci吋n de artista[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_5]
[s][vp 1 0 0 0 0 0]斡El Confidente del Emperador[n]ha alcanzado el [clr 2]nivel 5[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Yusuke ya puede usar[n][clr 1]Creaci吋n de cartas[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_6]
[s][vp 1 0 0 0 0 0]斡El Confidente del Emperador[n]ha alcanzado el [clr 2]nivel 6[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Yusuke ya puede usar[n][clr 1]Golpe de abanico[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_7]
[s][vp 1 0 0 0 0 0]斡El Confidente del Emperador[n]ha alcanzado el [clr 2]nivel 7[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Yusuke ya puede usar[n][clr 1]Pintura en vivo[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_8]
[s][vp 1 0 0 0 0 0]斡El Confidente del Emperador[n]ha alcanzado el [clr 2]nivel 8[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Yusuke ya puede usar[n][clr 1]郁ltimo aliento[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKUP_9]
[s][vp 1 0 0 0 0 0]斡El Confidente del Emperador[n]ha alcanzado el [clr 2]nivel 9[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡Yusuke ya puede usar[n][clr 1]Protecci吋n[clr 27]![n][f 1 3 65535][w][e]

[msg CMM_EVENT_RANKMAX]
[s][vp 1 0 0 0 0 0]斡El Confidente del Emperador[n]ha alcanzado el [clr 2]nivel m茨ximo[clr 27]![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Ganar茨s m茨s EXP[n]con la Explosi吋n arcana cuando[n]fusiones Personas de este arcano.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_UNLOCK]
[s][vp 1 0 0 0 0 0]Ya puedes fusionar a [clr 1]Od胤n[clr 27],[n]la Persona m茨s poderosa[n]del arcano del Emperador.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_REVERSE]
[s][vp 1 0 0 0 0 0]Al Confidente del Emperador[n]le asalta la duda.[n]No recibir茨s beneficio alguno[n]hasta que limpies tu nombre.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_UPRIGHT]
[s][vp 1 0 0 0 0 0]Has disipado la duda[n]del Confidente del Emperador.[n][f 1 3 65535][w][e]

[msg CMM_EVENT_BROKEN]
[s][vp 1 0 0 0 0 0]La relaci吋n con el Confidente[n]del Emperador se ha roto.[n]Ya no hay pacto, as胤 que[n]no recibir茨s ning雨n beneficio.[n][f 1 3 65535][w][e]

