[msg MSG_C22_BEGIN_D01_10_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57021 65535 0]斡Anda, hola![n][w][e]

[msg MSG_C22_BEGIN_D02_10_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57006 65535 0]斡Hola! Qu姻 calor hace 雨ltimamente.[n]Pero tengo un encuentro dentro de[n]poco, 斡as胤 que nada de desanimarse![n][w][e]

[msg MSG_C22_BEGIN_D03_10_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57006 65535 0]斡Hola![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Menudo sol hace hoy.[n]斡Procura hidratarte![n][w][e]

[msg MSG_C22_BEGIN_D04_10_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57021 65535 0]Ah, hola.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Est茨 empezando a hacer mucho fr胤o.[n]Ser茨 que ya ha llegado el oto隠o.[n][w][e]

[msg MSG_C22_BEGIN_D04_10_01 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57023 65535 0]Esto... En cuanto a lo del Palacio[n]de antes...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E-en realidad... bueno, da igual. No es nada.[n][w][e]

[msg MSG_C22_BEGIN_D05_10_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57021 65535 0]Se te ve algo cansado. 夷Est茨s bien?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Es importante esforzarse,[n]pero no te exijas demasiado.[n][w][e]

[msg MSG_C22_BEGIN_D07_10_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57021 65535 0]夷Est茨s bien?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]S姻 que te est茨s esforzando mucho,[n]pero ten cuidado de no excederte.[n][w][e]

[msg MSG_C22_BEGIN_D09_10_00 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57021 65535 0]夷Est茨s bien?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Darlo todo es importante, pero no[n]hasta el punto de la extenuaci吋n.[n][w][e]

[msg MSG_C22_BEGIN_D09_30_00 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57045 65535 0]Todo el mundo parece feliz,[n]pero hay algo que no cuadra...[n][w][e]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Vamos hoy al Palacio? 斡Tenemos[n]que detener al doctor Maruki![n][w][e]

[sel SEL_C22_ACTION_D09_31_00 top]
[s]Vamos a pasar el rato juntos.[e]
[s]Vamos al Metaverso.[e]
[s]A雨n no lo tengo claro.[e]

[msg MSG_C22_ACTION_D09_31_10 [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57065 65535 0]夷P-pasar el rato? Pero 斡hay que[n]hacer algo antes de que sea tarde![n][w][e]

[sel SEL_C22_ACTION_D09_31_10 top]
[s]No le des tantas vueltas.[e]
[s]Vamos a darle otra vuelta.[e]

[msg MSG_C22_ACTION_D09_31_11 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57119 65535 0]Es verdad. Estoy ahog茨ndome[n]en un vaso de agua, y as胤 no puedo[n]sacar lo mejor de m胤.[n][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Gracias por preocuparte.[n]斡Relaj姻monos por hoy![n][w][e]

[msg MSG_C22_ACTION_D09_31_12 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57027 65535 0]Entiendo. Bueno, av胤same cuando[n]hayas decidido qu姻 hacemos hoy.[n][w][e]

[msg MSG_C22_ACTION_D09_31_13 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57026 65535 0]斡Vale! Har姻 lo que pueda[n]para no causar problemas. [n][w][e]

[msg MSG_C22_BEGIN_D09_40_00 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57182 65535 0]Ya no quiero huir m茨s.[n]Hay que acabar con este mundo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No nos queda mucho tiempo.[n]夷Vamos al Palacio hoy?[n][w][e]

[msg MSG_C22_BEGIN_D09_50_00 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 7167 65535 0]メッセージダミー[n][w][e]

[sel SEL_C22_ACTION_D09_99_00 top]
[s]Por supuesto.[e]
[s]Todav胤a no estoy seguro.[e]

[msg MSG_C22_ACTION_D09_99_00 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Entonces tendremos que reunirnos[n]en el Leblanc, 夷no? Vamos.[n][w][e]

[msg MSG_C22_ACTION_D09_31_00 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57055 65535 0]Eso es cierto. Tenemos mucho tiempo[n]hasta la fecha l胤mite.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero ni siquiera hemos encontrado[n]el tesoro todav胤a, as胤 que lo mejor[n]ser茨 infiltrarnos en el Palacio.[n][w][e]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Seguro que tienes planes,[n]pero al menos pi姻nsatelo.[n][w][e]

[msg MSG_C22_ACTION_D09_41_00 [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57035 65535 0]夷Est茨s seguro? No nos queda[n]mucho tiempo hasta la fecha l胤mite.[n][w][e]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Y todav胤a no hemos encontrado[n]el tesoro... Quiz茨 ser胤a buena idea[n]buscarlo cuanto antes.[n][w][e]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Seguro que tienes planes,[n]pero al menos pi姻nsatelo.[n][w][e]

[msg MSG_C02_BEGIN_D09_50_00 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Ahora que hemos asegurado[n]el camino al tesoro, tenemos[n]que enviar el aviso, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No s姻 muy bien c吋mo funciona.[n]夷Quedamos primero en el Leblanc?[n][w][e]

[sel SEL_C02_ACTION_D09_50_00 top]
[s]Suena bien.[e]
[s]Ahora mismo no...[e]

[msg MSG_C02_ACTION_D09_50_00 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57039 65535 0]斡Muchas gracias! 斡Entonces tenemos[n]que reunir a todo el mundo![n][w][e]

[msg MSG_C02_ACTION_D09_51_00 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2037 65535 0][f 4 10 65535 0 0]Entiendo. Seguro que[n]tienes planes hoy.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 57179 65535 0]Pero si decides reunir al grupo,[n]all胤 estar姻. T雨 av胤same.[n][w][e]

[msg MSG_C02_BEGIN_D09_50_01 [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57045 65535 0]Toca esperar al doctor Maruki.[n]斡Qu姻 nervios! Como en los momentos[n]previos a una competici吋n.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Hay que detener al doctor Maruki![n]斡Voy a darlo todo, lo prometo![n][w][e]

[msg MSG_C22_BEGIN_D07_20_00 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57033 65535 0]Oye, 夷se te dan bien los estudios?[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si te digo la verdad, he estado[n]tan centrada en el encuentro que[n]no he podido estudiar mucho.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si te parece bien... me gustar胤a[n]que me ayudaras a estudiar.[n][w][e]

[msg MSG_C22_BEGIN_D00_20_00 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57033 65535 0]Hay muchas partes del examen[n]que a雨n no tengo bien preparadas. [n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No quiero obligarte, pero[n]夷puedes ayudarme a estudiar?[n][w][e]

[sel SEL_C22_ACTION_D07_20_01 top]
[s]Entendido.[e]
[s]Me lo pensar姻.[e]

[msg MSG_C22_ACTION_D07_20_02 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57051 65535 0]斡夷Est茨s seguro?! T雨 tambi姻n tienes[n]que estudiar, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Muchas gracias. 斡Es un alivio saber[n]que me vas a ense隠ar t雨![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, 夷vamos al restaurante?[n]斡Voy a prepararme![n][w][e]

[msg MSG_C22_ACTION_D07_21_02 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57081 65535 0]Supongo que es pedir demasiado...[n]斡Disculpa! 斡Intentar姻 apa隠茨rmelas[n]yo sola![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero si alg雨n d胤a puedes...[n]斡Agradecer胤a mucho tu ayuda![n][w][e]

[msg MSG_C22_BEGIN_D10_20_00_ [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57033 65535 0]Bueno... En cuanto a los ex茨menes...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Uf, no me mires as胤.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Como sabr茨s, no estoy pasando[n]por muy buen momento.[n]No puedo apa隠茨rmelas sola.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Ay雨dame con los ex茨menes,[n]por favor! [n][w][e]

[sel SEL_C22_ACTION_D10_20_01 top]
[s]Vale.[e]
[s]Me lo pensar姻.[e]

[msg MSG_C22_ACTION_D10_20_02 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57023 65535 0]斡Much胤simas gracias![n]Eres muy amable.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Pues vamos al restaurante[n]de Shibuya! Puede que[n]tengamos que trasnochar.[n][w][e]

[msg MSG_C22_ACTION_D10_20_02_2 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57065 65535 0]夷Eres un 茨ngel de la guarda?[n]斡No, m茨s bien eres un dios![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Vamos al restaurante de Shibuya[n]antes de que cambies de idea![n][w][e]

[msg MSG_C22_ACTION_D10_21_02 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57026 65535 0]斡S胤, claro! Siempre y cuando[n]tengas tiempo, claro...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Por favor, pi姻nsatelo![n][w][e]

[msg MSG_C22_ACTION_D10_21_02_2 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57061 65535 0]Argh... Al menos pi姻nsatelo.[n]Por ahora, har姻 lo que pueda.[n][w][e]

[msg MSG_C22_BEGIN_D00_10_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57021 65535 0]Ah, 夷te vas a casa?[n][w][e]

[msg MSG_C22_BEGIN_D00_10_00_ [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57001 65535 0]Hola, 夷tienes un momento?[n][w][e]

[msg MSG_C22_BEGIN_COOPNG_00 [Kasumi]]
[s][bup 0 10 5 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57037 65535 0]La verdad es que tengo[n]entrenamiento pronto.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, 夷quer胤as hablar de algo?[n]夷Puede esperar?[n][w][e]

[msg MSG_C22_BEGIN_COOPNG_00_ [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57037 65535 0]Ahora debo ir a entrenar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lo siento si ten胤as algo que[n]decirme. 斡A lo mejor podemos[n]hablarlo luego![n][w][e]

[msg MSG_C22_OPEN_NPC_000_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 7028 65535 0]Oye, 夷tienes tiempo ahora?[n][w][e]
[s][vp 1 0 0 0 0 0]......[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡夷P-puedes salir conmigo?![n][w][e]

[msg SEL_C22_OPEN_NPC_001_00 [Kasumi]]
[s]夷A d吋nde vamos?[n]Tengo tiempo.[n]Ahora mismo no.[n][e]

[msg MSG_C22_OPEN_NPC_002_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 7028 65535 0]斡夷En serio?![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entonces, 夷vamos a tomar un t姻?[n]夷Al restaurante de Shibuya, quiz茨s?[n][w][e]

[msg MSG_C22_OPEN_NPC_002_01 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 7028 65535 0]Bueno... 斡夷vienes conmigo?![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Pues vamos a tomar t姻![n]夷Qu姻 te parece[n]el restaurante de Shibuya?[n][w][e]

[msg MSG_C22_OPEN_NPC_002_02 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 7028 65535 0]Ah, entiendo.[n][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Que no puedas ahora no implica[n]que no puedas m茨s tarde, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Te estar姻 esperando! 斡Av胤same![n][w][e]

[msg MSG_C22_OPEN_NPC_003_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 7028 65535 0]斡Pues decidido! 斡Venga, vamos![n][w][e]

[msg MSG_YOSIZAWA_COOP_C00_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Si tienes tiempo, 夷quieres hacer[n]estiramientos conmigo?[n][w][e]

[msg MSG_YOSIZAWA_COOP_C10_01 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]夷Quieres que vayamos[n]a dar una vuelta a alg雨n lado?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Viene bien descansar[n]de vez en cuando, as胤 que...[n]si te parece bien...[n][w][e]

[msg MSG_YOSIZAWA_COOP_C00_00_2 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Me gustar胤a hablar contigo hoy.[n]Si tienes un rato, claro.[n][w][e]

[msg MSG_YOSIZAWA_COOP_C10_00 [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Tengo una idea...[n][w][e]
[s][bup 0 10 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 57097 65535 0]夷Te gustar胤a tener una cita?[n]Como novios, digo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me har胤a muy feliz estar contigo.[n][w][e]
[s][bup 0 10 6 65535 0][f 4 10 65535 0 0][vp 8 2 1 57096 65535 0]夷Te parece si pasamos[n]un rato juntos?[n][w][e]

[msg MSG_YOSIZAWA_COOP_C10_01_2 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]夷Quieres ir a alg雨n sitio hoy?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No es bueno excederse. Puede que[n]nos venga bien un descanso.[n][w][e]

[msg MSG_YOSIZAWA_COOP_R01_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]夷Quieres entrenar? Haremos[n]estiramientos para empezar.[n][w][e]

[msg MSG_YOSIZAWA_COOP_R02_00 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]夷Tienes tiempo ahora?[n][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me han dado permiso para usar[n]el gimnasio del instituto, 斡as胤 que[n]podr胤amos entrenar all胤![n][w][e]

[msg MSG_YOSIZAWA_COOP_R03_00 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Quiero que vengas de compras[n]conmigo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No s姻 si podr胤a con esto[n]yo sola, 夷sabes?[n][w][e]

[msg MND_YOSIZAWA_COOP_R03_01]
[s]A Kasumi le preocupa algo.[n]夷Conseguir姻 que me lo cuente?[n][w][e]

[msg MND_YOSIZAWA_COOP_R03_02]
[s]Con mi [f 4 11 4][clr 26][f 4 12 4][clr 27] actual,[n]no s姻 si llegaremos a conectar.[n][w][e]
[s]Kasumi confiar胤a m茨s en m胤[n]si mi [f 4 11 4][clr 26][f 4 12 4][clr 27][n]fuera [clr 26][f 4 13 4 4][clr 27].[n][w][e]

[msg MSG_YOSIZAWA_COOP_R03_03 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Lo siento, pero hoy voy a tener[n]que saltarme el entrenamiento.[n][w][e]
[s]斡Pues a la pr吋xima ser茨![n][w][e]

[msg MND_YOSIZAWA_COOP_R03_03]
[s]Con mi [f 4 11 4][clr 26][f 4 12 4][clr 27] actual,[n]creo que puedo ayudarla a abrirse.[n][w][e]

[msg MSG_YOSIZAWA_COOP_R03_05 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Ay雨dame, por favor! 斡Tengo[n]que cumplir con mi parte del trato![n][w][e]

[msg MSG_YOSIZAWA_COOP_R04_00 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Estoy pensando en cambiar[n]la rutina de entrenamiento.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Qu姻 te parece?[n]夷Tienes un rato ahora?[n][w][e]

[msg MSG_YOSIZAWA_CORP_R05_99 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Perdona, esperaba que hablases[n]conmigo un minut胤n.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Te viene bien ahora?[n][w][e]

[msg MSG_YOSIZAWA_CORP_R05_90 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0][f 4 2]...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quiero comentarte una cosa,[n]as胤 que av胤same[n]cuando tengas un rato.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No hace falta si no quieres, claro.[n][w][e]

[msg MSG_YOSIZAWA_COOP_R06_00 [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Oye... Es que... [n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quiero comentarte una cosa.[n]夷Tienes un rato?[n][w][e]

[msg MSG_YOSIZAWA_COOP_R07_00 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Estoy intentando dar [n]lo mejor de m胤 ahora.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]A lo mejor voy a una clase especial[n]con la entrenadora del equipo.[n][w][e]

[msg MSG_YOSIZAWA_COOP_R07_01 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Es una rutina de ejercicios[n]especial basada en el boxeo.  [n][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Reduce el estr姻s y puede asistir[n]cualquiera. Vente si te apetece.[n][w][e]

[msg MSG_YOSIZAWA_COOP_R07_ch [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57037 65535 0]Perd吋n por no haber avisado[n]con antelaci吋n. S姻 que est茨s liado.[n][w][e]

[msg MSG_YOSIZAWA_COOP_R08_00 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Oye, me he dado cuenta de una cosa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si quiero tener coraje,[n]he de cambiar de mentalidad.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 57088 65535 0]Por eso he pensado que...[n]podr胤as quedarte a verme entrenar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Tienes planes hoy?[n][w][e]

[msg MSG_YOSIZAWA_COOP_R09_00 [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Quer胤a comentarte una cosa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Tienes un segundo?[n][w][e]

[msg MSG_YOSIZAWA_COOP_R10_00 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Voy a hacer mi ejercicio ahora[n]delante de mi entrenadora.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me gustar胤a que vinieras[n]a verme entrenar, [f 4 2].[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me siento con confianza suficiente para[n]mostrarle mi respuesta mediante[n]mi rutina.[n][w][e]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 57095 65535 0]As胤 que, si me puedes dedicar un rato,[n]acomp茨隠ame, por favor.[n][w][e]

[msg MSG_YOSIZAWA_COOP_R10_01 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Voy a hacer mi ejercicio ahora[n]delante de mi entrenadora.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me gustar胤a que vinieras[n]a verme entrenar, [f 4 2].[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me siento con confianza suficiente para[n]mostrarle mi respuesta mediante[n]mi rutina.[n][w][e]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 57095 65535 0]As胤 que, si me puedes dedicar un rato,[n]acomp茨隠ame, por favor.[n][w][e]

[msg MND_COOP_DOUZOKUSEI]
[s]Gracias a la Persona del arcano[n][var 2], [clr 1][var 5][clr 27],[n]puedo estrechar lazos con [f 4 31 10 1].[n][w][e]

[msg MND_COOP_DOUZOKUSEI_SMR]
[s]Gracias a la Persona del arcano[n][var 2], [clr 1][var 5][clr 27],[n]puedo estrechar lazos con [f 4 31 10 1].[n][w][e]

[msg MND_COOP_RANKUP_OK_FIRST]
[s]Esta puede ser una buena[n]oportunidad para fortalecer[n]mi v胤nculo con Kasumi.[n][w][e]

[msg MND_COOP_RANKUP_OK]
[s]Siento que mi v胤nculo con [f 4 31 10 1][n]se fortalecer茨 pronto.[n][w][e]

[msg MND_COOP_RANKUP_OK_SMR]
[s]Siento que mi v胤nculo con [f 4 31 10 1][n]se fortalecer茨 pronto.[n][w][e]

[msg MND_COOP_RANKUP_NG]
[s]No creo que mi v胤nculo[n]con [f 4 31 10 1][n]se vaya a fortalecer a雨n.[n][w][e]

[msg MND_COOP_RANKUP_NG_SMR]
[s]No creo que mi v胤nculo[n]con [f 4 31 10 1][n]se vaya a fortalecer a雨n.[n][w][e]

[msg MND_COOP_RANK_MAX_00]
[s]Tengo un v胤nculo especial[n]con [f 4 31 10 1].[n][w][e]

[msg MND_COOP_RANK_MAX_01]
[s]Tengo un v胤nculo s吋lido[n]con [f 4 31 10 1].[n][w][e]

[msg MSG_COOP_CHECK_DUNGEON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Es bueno desconectar[n]de vez en cuando. 夷Quieres[n]pasar el rato con Yoshizawa?[n][w][e]

[msg MSG_COOP_CHECK_DUNGEON_S [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Es bueno desconectar[n]de vez en cuando.[n]夷Quieres pasar el rato con Sumire?[n][w][e]

[msg MSG_COOP_CHECK_DAY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, 夷vas a pasar el rato[n]con Yoshizawa?[n][w][e]

[msg MSG_COOP_CHECK_DAY_SMR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entonces, 夷qu姻?[n]夷Quieres pasar un rato con Sumire?[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, 夷qu姻? 夷Quieres pasar el rato[n]con [f 4 31 10 1]?[n][w][e]

[sel SEL_COOP_CHECK top]
[s]Pasar el rato con ella[e]
[s]Comprobar v胤nculo con [f 4 31 10 1][e]
[s]Rechazar[e]

[sel SEL_COOP_CHECK_SMR top]
[s]Pasar el rato con ella[e]
[s]Comprobar v胤nculo con [f 4 31 10 1][e]
[s]Rechazar[e]

[sel SEL_COOP_CHECK_SMR2 top]
[s]Pasar el rato con ella[e]
[s]Comprobar v胤nculo con [f 4 31 10 1][e]

[msg MSG_C22_YES_01_00 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Pues decidido! Ya sabes lo que[n]dicen, que hay que aprovechar[n]el momento.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]Suelo entrenar en el Parque[n]Inokashira. 斡Estar胤a[n]bien pasarse por all胤 hoy![n][w][e]

[msg MSG_C22_YES_02_00 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Hurra! 斡Pues en marcha![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 57141 65535 0]Bueno, llegaremos tarde o temprano,[n]pero 夷quieres ir a por algo[n]de comida primero?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No puedo hacer ejercicio[n]con el est吋mago vac胤o.[n]斡Y la prote胤na es muy importante![n][w][e]

[msg MSG_C22_YES_02_01 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]夷D吋nde podemos comer?[n]夷Qu姻 te parece la cafeter胤a[n]del instituto?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 57069 65535 0]斡Venga, v茨monos![n]Pero esta vez de verdad, 夷eh? [n][w][e]

[msg MSG_C22_YES_03_00 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57052 65535 0]斡Gracias! No sab胤a qu姻 hacer[n]con los ovalados.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No s姻 qu姻 les gusta a los hombres.[n]Estaba completamente perdida.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 57058 65535 0]Pero 斡gracias a ti, creo que[n]por fin puedo entenderlo! [n][w][e]

[sel SEL_C22_YES_03_01 bottom]
[s]夷El qu姻?[e]
[s]夷Te echo una mano?[e]

[msg MSG_C22_YES_03_02 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57113 65535 0]Es como si... No s姻,[n]no es una decisi吋n que pueda[n]tomar una novata como yo.[n][w][e]

[msg MSG_C22_YES_03_03 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57026 65535 0]斡S胤, por supuesto![n]No creo que haya nadie mejor.[n][w][e]

[msg MSG_C22_YES_03_04 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Bueno, ser茨 mejor que vayamos ya.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 57069 65535 0]El objeto en cuesti吋n[n]est茨 en Kichijoji. 夷Vamos?[n][w][e]

[msg MSG_C22_YES_04_00 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Vaya, 斡s胤 que est茨s preparado![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 57058 65535 0]Vamos a las jaulas de bateo.[n]斡Espero que te haga ilusi吋n![n][w][e]

[msg MSG_C22_YES_05_00 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡G-gracias![n][w][e]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 57075 65535 0]夷Podemos ir a otro sitio?[n]No es f茨cil hablar aqu胤.[n][w][e]

[msg MSG_C22_YES_06_00 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57077 65535 0]夷En serio? Much胤simas gracias.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Te presentar姻 a la entrenadora[n]Hiraguchi cuando termine.[n][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Es una persona estupenda.[n]Nos ha ayudado a Kasumi y a m胤[n]desde que 姻ramos peque隠as.[n][w][e]

[msg MSG_C22_YES_06_chat [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Te presentar姻 a la entrenadora[n]Hiraguchi cuando termine.[n][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Es una persona estupenda.[n]Nos ha ayudado a Kasumi y a m胤[n]desde que 姻ramos peque隠as.[n][w][e]

[msg MSG_C22_YES_06_01 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57068 65535 0]Venga, vamos para all茨.[n][w][e]

[msg MSG_C22_YES_07_00 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57040 65535 0]Muchas gracias. 夷Podemos vernos[n]en la tienda de Shibuya?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hay algo que me gustar胤a ense隠arte.[n]Me adelantar姻 para irme preparando.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, si me disculpas...[n]斡Nos vemos luego![n][w][e]

[msg MSG_C22_YES_08_00 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57023 65535 0]Much胤simas gracias.[n][w][e]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero 夷a-ad吋nde vamos...?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si es posible, me gustar胤a ir[n]a un sitio donde podamos hablar[n]tranquilos.[n][w][e]

[sel SEL_C22_YES_08_01 bottom]
[s]夷Te apetece venir a mi casa?[e]
[s]Tenemos una cafeter胤a.[e]

[msg MSG_C22_YES_08_02 [Sumire]]
[s][bup 0 10 7 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57097 65535 0]斡夷Q-qu姻?! 斡夷C吋mo que a tu casa?![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷No es un poco pronto?[n]E-es que no s姻 si estoy lista para...[n]Ya sabes...[n][w][e]
[s][vp 8 2 1 0 65535 0]...[n][w][e]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah... Cuando dijiste que fuera,[n]夷te refer胤as al Leblanc?[n][w][e]
[s][vp 8 2 1 0 65535 0]...[n][w][e]
[s][bup 0 10 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 57098 65535 0]斡Lo siento mucho![n]Me he precipitado.[n]斡Mira que soy idiota! [n][w][e]

[msg MSG_C22_YES_08_03 [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57120 65535 0]斡Ah, el Leblanc![n][w][e]

[msg MSG_C22_YES_08_04 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Supongo que all胤 podr胤amos[n]hablar tranquilamente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si de verdad no te importa,[n]voy para all茨.[n][w][e]

[msg MSG_C22_YES_09_00 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57039 65535 0]斡G-gracias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Pues prep茨rate y al gimnasio![n][w][e]

[msg MSG_C22_YES_09_01 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57039 65535 0]斡G-gracias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Pues prep茨rate y al gimnasio![n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, yo voy a dar una vuelta.[n]Av胤same cuando quieras irte.[n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]※ないよう変更に伴い、不使用でいいかと[n][e]

[msg MSG_C22_SPOT_00_00 [[f 4 31 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57049 65535 0]夷Qu姻 hacemos hoy?[n]夷Hay algo que te apetezca?[n][w][e]

[msg MSG_C22_SPOT_00_00_SMR [[f 4 31 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57047 65535 0]夷Qu姻 hacemos hoy?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si hay algo que te apetezca[n]hacer hoy, te acompa隠o.[n][w][e]

[sel SEL_C22_SPOT_00_01 top]
[s]Vamos a dar una vuelta.[e]
[s]Vamos a mi habitaci吋n.[e]
[s]Hablemos un rato.[e]

[msg MSG_C22_SPOT_00_10 [[f 4 31 10 0]]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57025 65535 0]Me parece estupendo. Creo que[n]nos ayudar胤a a relajarnos un poco.[n][w][e]

[msg MSG_C22_SPOT_00_10_SMR [[f 4 31 10 0]]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57123 65535 0]斡Qu姻 buena idea![n]Descansar es importante.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero 夷d吋nde vamos?[n][w][e]

[msg MSG_C22_MYROOM_00_10_SMR [Sumire]]
[s][bup 0 10 7 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57065 65535 0]夷Qu姻? 斡夷En tu habitaci吋n?![n]斡夷L-los dos solos?![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No es que piense hacer[n]nada raro, pero...[n][w][e]
[s][vp 8 2 1 0 65535 0]...[n][w][e]
[s][bup 0 10 6 65535 0][f 4 10 65535 0 0][vp 8 2 1 57093 65535 0]Si te parece bien, me encantar胤a.[n][w][e]

[msg MSG_C22_YES_00_00 [[f 4 31 10 0]]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57067 65535 0]斡Qu姻 emoci吋n! Date prisa y v茨monos.[n][w][e]

[msg MSG_C22_YES_00_00_SMR [[f 4 31 10 0]]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57087 65535 0]Pues en marcha. Yo te sigo.[n][w][e]

[msg MSG_C22_YES_10_00 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57097 65535 0]Estoy empezando a ponerme nerviosa.[n][w][e]

[msg MSG_C22_YES_10_01 [[f 4 31 10 0]]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57069 65535 0]斡Pues vamos! 斡Qu姻 emoci吋n![n][w][e]

[msg MSG_C22_COOP_CANCEL [[f 4 31 10 0]]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57080 65535 0]Ah, 夷s胤? 斡Quiz茨 la pr吋xima vez![n][w][e]

[msg MSG_C22_COOP_CANCEL_SMR [[f 4 31 10 0]]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57055 65535 0]Ah...[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pues ven a hablar conmigo[n]cuando tengas tiempo.[n][w][e]

[msg MSG_C22_BEGIN_D10_REV [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57023 65535 0]Ah, hola, [f 4 2].[n][w][e]

[msg MSG_C22_COOP_10_00_REV [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]No quiero molestarte, pero[n]夷tienes tiempo para hablar?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quiero contarte[n]mis planes de futuro.[n][w][e]

[msg MND_COOP_RANK_MAX__REV]
[s]Parece que Sumire tiene algo[n]importante que decirme.[n][w][e]

[msg MSG_COOP_CHECK_3RD_REV [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Sumire parece muy seria.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Qu姻 vas a hacer? 夷Quieres pasar[n]el rato con Sumire? [n][w][e]

[sel SEL_COOP_CHECK_REV top]
[s]Quedar.[e]
[s]Esta vez no.[e]

[msg MSG_C22_YES_10_00_REV [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57078 65535 0]斡Much胤simas gracias![n]Entonces, 夷puedes venir a mi casa?[n][w][e]
[s][vp 8 2 1 0 65535 0]...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 57097 65535 0]斡Uy, lo siento! S姻 que es raro[n]invitarte a mi casa as胤 de repente...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡L-lo siento![n]斡Te prometo que no es nada raro! [n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]B-bueno, 夷nos vamos?[n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vale, entonces me marcho.[n]Te dejo a la se隠orita Ann.[n][w][e]

[msg MSG_C22_COOP_CANCEL_REV [Sumire]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57081 65535 0]Ya veo... Bueno, av胤same[n]cuando tengas un rato.[n][w][e]

[msg MSG_C22_EVOLUTION_WAIT [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57045 65535 0]Lo siento, hoy tengo otras cosas[n]en mente. Quiero estar sola.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero si es una emergencia,[n]av胤same y all胤 estar姻.[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Ya puedes ir a [clr 1]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Ya puedes ir a [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Ya puedes ir a [clr 2]Akihabara[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Parque Inokashira[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el ramen[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Parque Seaside de Odaiba[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste este tipo[n]de parques para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Museo Ueno[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le gusten los museos[n]de arte para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el monjayaki[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]calle Takenoko de Harajuku[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente a[n]la que le guste la calle Takenoko[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Chinatown de Motomachi[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Destinyland de Maihama[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]Puedes invitar a gente a la que le[n]guste la Skytree o la calle[n]Nakamise para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Planetario de Ikebukuro[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Santuario Meiji[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir por tu cuenta[n]para venerarlo.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Dome Town de Suidobashi[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Hotel Wilton de Shibuya[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]restaurante de sushi de Ginza[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el sushi caro[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Tienes informaci吋n sobre un nuevo[n]punto de encuentro: [clr 2]La ciudad[n]de los libros de Jinbocho[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir por tu cuenta[n]a comprar.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Estanque Ichigaya[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste pescar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir[n]por tu cuenta para ver[n]qu姻 tal se te da pescar.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Acuario de Shinagawa[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el acuario[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]zona comercial de Nakano[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste ese lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_C22_BYEGREET_00_00 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]すみれとの[n]挨拶周り会話  [n][w][e]

[sel SEL_C22_BYEGREET_00_01 top]
[s]選択1[e]
[s]選択2[e]
[s]選択3 [e]

[msg MSG_C22_BYEGREET_00_02 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]選択1の返答 [n][w][e]

[msg MSG_C22_BYEGREET_00_03 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]選択2の返答 [n][w][e]

[msg MSG_C22_BYEGREET_00_04 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]選択3の返答 [n][w][e]

[msg MSG_C22_BYEGREET_00_05 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]将来について自分語り [n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]プレゼント渡す [n][w][e]

[msg MSG_C22_BYEGREET_00_06 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]プレゼントについて [n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]会話締め [n][w][e]

[msg MSG_C22_BYEGREET_00_07 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]2回目アクセス時会話[n]「会話締め」 [n][w][e]

