[msg MSG_C03_BEGIN_D05_10_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3001 65535 0]夷Necesitas algo?[n][w][e]

[msg MSG_C03_BEGIN_D05_30_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3019 65535 0]Primero tenemos que asegurar[n]un camino hacia el tesoro, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Vamos a infiltrarnos hoy?[n]En tal caso, deber胤amos[n]reunirnos en el escondite.[n][w][e]

[msg MSG_C03_BEGIN_D05_40_00 [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3181 65535 0]No quiero casarme con ese hombre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tenemos que asegurar un camino[n]hacia el tesoro pronto.[n]夷Nos reunimos hoy en el escondite?[n][w][e]

[msg MSG_C03_BEGIN_D05_50_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3019 65535 0]Entonces, si enviamos el aviso,[n]夷el tesoro aparecer茨[n]en la ubicaci吋n que vimos antes?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, 夷cu茨ndo lo enviamos?[n]Tendremos que reunirnos antes.[n][w][e]

[sel SEL_C03_ACTION_D05_00_00 top]
[s]Reun茨monos con los dem茨s.[e]
[s]Un momento.[e]

[msg MSG_C03_ACTION_D05_00_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Entiendo. Antes tengo que[n]cambiarme, as胤 que ve yendo t雨.[n][w][e]

[msg MSG_C03_ACTION_D05_31_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]夷Hay alg雨n problema?[n][w][e]

[sel SEL_C03_ACTION_D05_32_00 top]
[s]Ten paciencia.[e]
[s]Quiero saber m茨s de ti.[e]

[msg MSG_C03_ACTION_D05_33_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3194 65535 0]Tienes raz吋n. Perd吋name.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Av胤same cuando est姻s listo.[n][w][e]

[msg MSG_C03_ACTION_D05_35_00 [Haru]]
[s][bup 0 7 204 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3024 65535 0]斡夷Qu姻?![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mm, vale... Me interesa cultivar[n]varios tipos de plantas.[n][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero creo que despertar el coraz吋n[n]de mi padre es m茨s importante.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No puedo casarme con ese hombre.[n][w][e]

[msg MSG_C03_ACTION_D05_80_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]A Haru le interesa la jardiner胤a.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si se te diera mejor, quiz茨[n]podr胤as ayudarla.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero supongo que la prioridad[n]ahora mismo es nuestra operaci吋n.[n][w][e]

[msg MSG_C03_ACTION_D05_41_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3192 65535 0]Mmm. Ya casi es d胤a 10...[n]夷Nos ir茨 bien?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estar姻 esperando tu llamada,[n]as胤 que av胤same cuando est姻s listo.[n][w][e]

[msg MSG_C03_ACTION_D05_51_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3111 65535 0]Solo tenemos que robar[n]el tesoro, 夷no? 夷Por qu姻 no[n]enviamos el aviso ya?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Yo ya estoy lista.[n][w][e]

[msg MSG_C03_BEGIN_D05_60_00 [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3067 65535 0]Mi padre se ha encerrado[n]en el estudio. Nuestra 雨nica opci吋n[n]es esperar hasta que decida hablar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cambiar茨, 夷verdad?[n][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cambiando de tema, 夷tienes algo[n]que hacer aqu胤, [f 4 2]?[n][w][e]

[sel SEL_C03_ACTION_D05_60_01 top]
[s]He venido a verte.[e]
[s]He venido por las verduras.[e]
[s]Nada en particular.[e]

[msg MSG_C03_BEGIN_D99_00_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3002 65535 0]斡Ah, [f 4 2]! Hola.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Qu姻 opinas de este parterre?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lo he tra胤do con la esperanza de[n]ponerme en serio con la jardiner胤a.[n][w][e]

[msg MSG_C03_BEGIN_D99_01_00 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1022 65535 0]Vaya... Qu姻 trabajadora es...[n][w][e]

[msg MSG_C03_BEGIN_D99_02_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Av胤same si quieres[n]que cultive verduras.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, 夷qu姻 hacemos hoy?[n][w][e]

[msg MSG_C03_BEGIN_D00_10_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3002 65535 0][f 4 2], 夷tienes algo[n]que hacer hoy aqu胤?[n][w][e]

[sel SEL_C03_ACTION_D00_10_01 top]
[s]He venido a verte.[e]
[s]He venido por las verduras.[e]
[s]Nada en particular.[e]

[msg MSG_C03_BEGIN_D00_20_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Los ex茨menes est茨n al caer,[n]as胤 que pensaba terminar un poco[n]antes e irme a estudiar.[n][w][e]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si te parece bien,[n]podr胤amos estudiar juntos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Igual puedo ense隠arte algo.[n]Como soy un a隠o mayor que t雨...[n][w][e]

[sel SEL_C03_ACTION_D00_20_01 top]
[s]Me parece genial.[e]
[s]Preferir胤a plantar flores.[e]
[s]Ahora mismo no.[e]

[msg MSG_C03_ACTION_D00_20_02 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]斡D姻jamelo a m胤! Voy a cambiarme,[n]as胤 que esp姻rame en la biblioteca.[n][w][e]

[msg MSG_C03_ACTION_D00_21_02 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3064 65535 0]夷Mmm? No hace falta ser[n]tan reservado. Bueno,[n]av胤same si alg雨n d胤a te apetece.[n][w][e]

[msg MSG_C03_BEGIN_D00_30_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3001 65535 0][f 4 2], 夷has decidido[n]qu姻 vas a hacer hoy?[n][w][e]

[sel SEL_C03_ACTION_D00_31_00 top]
[s]Vamos a pasar el rato juntos.[e]
[s]He venido por las verduras.[e]
[s]Reun茨monos con los dem茨s.[e]
[s]A雨n no.[e]

[msg MSG_C03_ACTION_D00_31_10 [Haru]]
[s][bup 0 7 204 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]夷Eh? 夷En un momento as胤?[n]夷Esto forma parte de tu[n]gran estrategia de infiltraci吋n?[n][w][e]

[sel SEL_C03_ACTION_D00_31_10 top]
[s]Es un secreto.[e]
[s]No lo s姻.[e]

[msg MSG_C03_ACTION_D00_31_11 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3048 65535 0]*risita* Si lo dices as胤,[n]parece muy importante.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Supongo que relajarse[n]es esencial en momentos como este.[n][w][e]

[msg MSG_C03_ACTION_D00_31_12 [Haru]]
[s][bup 0 7 202 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3046 65535 0]Bueno, igual deber胤as pensar[n]un poco m茨s en ello.[n][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]En fin, av胤same[n]cuando te hayas planificado.[n][w][e]

[msg MSG_C03_BEGIN_D00_40_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3019 65535 0]Se acerca la fecha l胤mite. Debemos[n]asegurar una ruta de infiltraci吋n.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Nos reunimos ya?[n][w][e]

[msg MSG_C03_BEGIN_D00_50_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3019 65535 0]Ya sabemos la ubicaci吋n[n]del tesoro. Ya solo falta[n]enviar el aviso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Aunque primero tenemos[n]que reunirnos, 夷no?[n][w][e]

[sel SEL_C03_ACTION_D00_99_00 top]
[s]Reun茨monos con los dem茨s.[e]
[s]Quiero ver las verduras.[e]
[s]Un momento.[e]

[msg MSG_C03_ACTION_D00_99_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Entiendo. Antes tengo que[n]cambiarme, as胤 que ve yendo t雨.[n][w][e]

[msg MSG_C03_ACTION_D00_31_00 [Haru]]
[s][bup 0 7 202 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3046 65535 0]*suspiro* Tenemos que asegurar[n]la ruta de infiltraci吋n.[n][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Te estar姻 esperando, as胤 que[n]av胤same cuando est姻s listo.[n][w][e]

[msg MSG_C03_ACTION_D00_41_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3046 65535 0]Eso no nos ayudar茨 a encontrar[n]el tesoro. Tenemos que asegurar[n]una ruta de infiltraci吋n.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Av胤same cuando est姻s listo.[n][w][e]

[msg MSG_C03_ACTION_D00_51_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Ah, vale. 夷Esto tiene que ver[n]con tu plan o algo?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lo 雨nico que nos queda por hacer[n]es enviar el aviso. Av胤same[n]cuando est姻s listo, [f 4 2].[n][w][e]

[msg MSG_C03_BEGIN_D00_60_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3001 65535 0]Ahora solo queda esperar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, 夷necesitas algo?[n][w][e]

[sel SEL_C03_ACTION_D00_60_01 top]
[s]He venido a verte.[e]
[s]He venido por las verduras.[e]
[s]Nada en particular.[e]

[msg MSG_C03_BEGIN_D06_50_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Tenemos que esperar[n]al d胤a del anuncio. Hasta entonces,[n]estar姻 ocup茨ndome de las plantas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Necesitas algo[n]mientras tanto, [f 4 2]?[n][w][e]

[sel SEL_C03_ACTION_D06_50_01 top]
[s]He venido a verte.[e]
[s]He venido por las verduras.[e]
[s]Nada en particular.[e]

[msg MSG_C03_BEGIN_D07_10_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Es un buen momento[n]para cargar las pilas. Bueno,[n]夷necesitas algo, [f 4 2]?[n][w][e]

[sel SEL_C03_ACTION_D07_10_01 top]
[s]He venido a verte.[e]
[s]He venido por las verduras.[e]
[s]Nada en particular.[e]

[msg MSG_C03_BEGIN_D07_20_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3193 65535 0]Los ex茨menes est茨n al caer,[n]as胤 que pensaba terminar un poco[n]antes e irme a estudiar.[n][w][e]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si te parece bien,[n]podr胤amos estudiar juntos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estoy en tercero, as胤 que[n]igual te puedo ense隠ar algo.[n][w][e]

[sel SEL_C03_ACTION_D07_20_01 top]
[s]Ser胤a fant茨stico.[e]
[s]Quiero ver las verduras.[e]
[s]Deja que me lo piense.[e]

[msg MSG_C03_ACTION_D07_20_02 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Vale. En ese caso,[n]vamos al restaurante.[n][w][e]

[msg MSG_C03_ACTION_D07_21_02 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3064 65535 0]Puedo ense隠arte cosas que igual[n]no entender胤as de otra forma, as胤[n]que av胤same si quieres estudiar.[n][w][e]

[msg MSG_C03_BEGIN_D07_30_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3002 65535 0]夷Qu姻 quieres hacer[n]hoy, [f 4 2]?[n][w][e]

[sel SEL_C03_ACTION_D07_31_00 top]
[s]Vamos a pasar el rato juntos.[e]
[s]Quiero ver las verduras.[e]
[s]Reun茨monos con los dem茨s.[e]
[s]A雨n no lo he decidido.[e]

[msg MSG_C03_ACTION_D07_31_10 [Haru]]
[s][bup 0 7 204 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3024 65535 0]夷Eh? 夷En un momento as胤?[n]夷Esto forma parte de tu[n]gran estrategia de infiltraci吋n?[n][w][e]

[sel SEL_C03_ACTION_D07_31_10 top]
[s]Es un secreto.[e]
[s]No lo s姻.[e]

[msg MSG_C03_ACTION_D07_31_11 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3048 65535 0]*risita* Si lo dices as胤,[n]parece muy importante.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Supongo que relajarse[n]es esencial en momentos como este.[n][w][e]

[msg MSG_C03_ACTION_D07_31_12 [Haru]]
[s][bup 0 7 202 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3028 65535 0]Bueno, igual deber胤as pensar[n]un poco m茨s en ello.[n][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]En fin, av胤same[n]cuando te hayas planificado.[n][w][e]

[msg MSG_C03_BEGIN_D07_40_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3197 65535 0]Me gustar胤a ir al Palacio hoy.[n]Tenemos que ajustar cuentas[n]con Shido por lo de mi padre.[n][w][e]

[msg MSG_C03_BEGIN_D07_50_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3197 65535 0]夷Podemos enviar el aviso?[n]Tenemos que ajustar cuentas[n]con Shido por lo de mi padre.[n][w][e]

[sel SEL_C03_ACTION_D07_99_00 top]
[s]Venga.[e]
[s]Primero veamos las verduras.[e]
[s]A雨n no.[e]

[msg MSG_C03_ACTION_D07_99_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Muy bien. Ir姻 para all茨 cuando[n]hayas hablado con los dem茨s.[n][w][e]

[msg MSG_C03_ACTION_D07_31_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3111 65535 0]Claro, pero antes[n]tenemos que asegurar un camino.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Te estar姻 esperando, as胤 que[n]av胤same cuando est姻s listo.[n][w][e]

[msg MSG_C03_ACTION_D07_41_00 [Haru]]
[s][bup 0 7 202 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3046 65535 0]夷Puedes centrarte?[n][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Te estar姻 esperando, as胤 que[n]av胤same cuando est姻s listo.[n][w][e]

[msg MSG_C03_ACTION_D07_51_00 [Haru]]
[s][bup 0 7 202 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3046 65535 0]夷Puedes centrarte?[n][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lo siguiente es enviar[n]el aviso, as胤 que av胤sanos[n]cuando est姻s listo.[n][w][e]

[msg MSG_C03_BEGIN_D07_60_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3019 65535 0]Ya nadie deber胤a sufrir[n]desconexiones mentales, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cambiando de tema, 夷qu姻 te trae[n]por la azotea, [f 4 2]?[n][w][e]

[sel SEL_C03_ACTION_D07_60_01 top]
[s]He venido a verte.[e]
[s]He venido por las verduras.[e]
[s]Nada en particular.[e]

[msg MSG_C03_BEGIN_D10_50_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Tenemos que esperar[n]al d胤a del anuncio. Hasta entonces,[n]estar姻 ocup茨ndome de las plantas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Necesitas algo[n]mientras tanto, [f 4 2]?[n][w][e]

[sel SEL_C03_ACTION_D10_50_00 top]
[s]He venido a verte.[e]
[s]He venido por las verduras.[e]
[s]Nada en particular.[e]

[msg MSG_C03_BEGIN_D09_10_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Hola, [f 4 2]. 夷Qu姻 te [n]trae por aqu胤 hoy?[n][w][e]

[sel SEL_C03_ACTION_D09_10_01 top]
[s]He venido a verte.[e]
[s]He venido por las verduras.[e]
[s]Nada en particular.[e]

[msg MSG_C03_BEGIN_D09_20_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3002 65535 0]夷Cu茨l es el plan de hoy, [f 4 2]?[n][w][e]
[s]Dadas las circunstancias, 夷nuestra[n]prioridad no deber胤a ser encontrar[n]un camino hacia el tesoro?[n][w][e]

[sel SEL_C03_ACTION_D09_20_01 top]
[s]Vamos a pasar el rato juntos.[e]
[s]Quiero ver las verduras.[e]
[s]Reun茨monos con los dem茨s.[e]
[s]A雨n no lo he decidido.[e]

[msg MSG_C03_BEGIN_D09_20_02 [Haru]]
[s][bup 0 7 204 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3024 65535 0]夷Eh? 夷Quedar? 夷Podemos?[n]Pero tenemos que solucionar[n]el problema de la materializaci吋n...[n][w][e]

[sel SEL_C03_ACTION_D09_20_02 top]
[s]No nos conviene impacientarnos.[e]
[s]Eso es cierto...[e]

[msg MSG_C03_BEGIN_D09_20_03 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3048 65535 0]Je, je... Parece que nada[n]te perturba, [f 4 2].[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero supongo que relajarse[n]es esencial en momentos como este.[n][w][e]

[msg MSG_C03_BEGIN_D09_20_04 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]S胤, creo que es un momento crucial.[n][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Por favor, av胤same[n]cuando te organices.[n][w][e]

[msg MSG_C03_BEGIN_D09_30_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3197 65535 0]Hay que hacer algo[n]con el doctor Maruki.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Y si vamos hoy al Palacio?[n]No podemos ignorar la situaci吋n.[n][w][e]

[msg MSG_C03_BEGIN_D09_40_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3197 65535 0]Ahora solo queda esperar[n]hasta el d胤a que mencion吋 el doctor[n]Maruki. Tenemos que detenerlo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero hasta entonces, me quedar姻[n]aqu胤 cuidando de las plantas. 夷T雨[n]qu姻 planes tienes, [f 4 2]?[n][w][e]

[sel SEL_C03_ACTION_D09_40_01 top]
[s]Nos vemos en el escondite.[e]
[s]Primero veamos las verduras.[e]
[s]No me he decidido.[e]

[msg MSG_C03_BEGIN_D09_40_02 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Muy bien. Ir姻 para all茨 cuando[n]hayas hablado con los dem茨s.[n][w][e]

[msg MSG_C03_BEGIN_D09_40_03 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3111 65535 0]Bueno... Pero tenemos que asegurar[n]un camino. La materializaci吋n[n]se est茨 expandiendo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Te estar姻 esperando, as胤 que[n]av胤same cuando est姻s listo.[n][w][e]

[msg MSG_C03_BEGIN_D09_40_04 [Haru]]
[s][bup 0 7 202 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3046 65535 0]斡[f 4 2], c姻ntrate![n][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Tenemos que enfrentarnos[n]al doctor Maruki si queremos[n]volver a nuestra realidad![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Av胤same cuando est姻s listo.[n]Te estar姻 esperando.[n][w][e]

[msg MSG_C03_CONNECT_OK_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]*risita* Ay, gracias.[n][w][e]

[msg MSG_C03_CONNECT_HARVEST_ [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3048 65535 0]*risita* Qu姻 alegr胤a.[n][w][e]

[msg MSG_C03_CONNECT_CANCEL_0 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Cuido del jard胤n todos los d胤as.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3054 65535 0]P茨sate por aqu胤[n]cuando quieras ver qu姻 tal va.[n][w][e]

[msg MSG_C03_BEGIN_COOPNG_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3032 65535 0]Creo que voy a irme a casa despu姻s[n]de echarle un ojo a las plantas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ponte en contacto conmigo si hay[n]una emergencia. Vendr姻 encantada.[n][w][e]

[msg MSG_C03_EVOLUTION_WAIT [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3032 65535 0]He estado d茨ndole vueltas a algo...[n]夷Te parece bien si hablamos[n]cuando las cosas se calmen un poco?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ponte en contacto conmigo si hay[n]una emergencia. Vendr姻 encantada.[n][w][e]

[msg MSG_C03_PRECOOP_30_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3019 65535 0]En tal caso, me gustar胤a aprovechar[n]esta oportunidad para llevarle[n]mi cosecha m茨s reciente a Sakura.[n][w][e]

[msg MND_C03_PRECOOP_30_01]
[s]Esta puede ser una buena oportunidad[n]para fortalecer mi v胤nculo con Haru.[n][w][e]

[msg MSG_C03_PRECOOP_30_02 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3019 65535 0]Me gustar胤a ir al Leblanc[n]hoy... 夷Te vienes?[n][w][e]

[sel SEL_C03_PRECOOP_30_01 top]
[s]Claro.[e]
[s]Ahora estoy muy ocupado.[e]

[msg MSG_C03_PRECOOP_31_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3045 65535 0]斡Estupendo! Pues vamos.[n][w][e]

[msg MSG_C03_PRECOOP_00_99 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3063 65535 0]Vaya... Bueno, pi姻nsatelo bien[n]si al final tienes tiempo libre.[n][w][e]

[msg MSG_C03_COOP_00_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Ah, si no te importa, 夷podr胤as[n]echarme una mano con las plantas?[n][w][e]

[msg MSG_C03_COOP_01_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]夷Te puedo pedir un consejito?[n]Sobre las verduras[n]y sobre algunas cosas m茨s...[n][w][e]

[msg MSG_C03_COOP_01_01 [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][f 4 23 1 203 0 10 0 10][vp 8 2 1 3028 65535 0]Lo siento. Estoy ocupada[n]cuidando de las plantas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Como soy tan torpe,[n]me lleva mi tiempo...[n][w][e]

[msg MND_C03_COOP_01_01]
[s]Parece que Haru est茨 ocupada[n]cuidando de las plantas.[n][w][e]

[msg MND_C03_COOP_01_02]
[s]Con mi nivel actual de [f 4 11 2][clr 26][f 4 12 2][clr 27],[n]solo me interpondr胤a en su camino.[n][w][e]
[s]Igual podr胤a ayudarla[n]si mi [f 4 11 2][clr 26][f 4 12 2][clr 27] fuera[n][clr 26][f 4 13 2 5][clr 27]...[n][w][e]

[msg MND_C03_COOP_01_03]
[s]Con mi [f 4 11 2][clr 26][f 4 12 2][clr 27] actual,[n]斡podr胤a ayudar a Haru con lo que sea![n][w][e]

[msg MSG_C03_COOP_02_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Las verduras van bien. Si quieres,[n]puedo ense隠茨rtelas.[n][w][e]

[msg MSG_C03_COOP_03_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]斡Ah! He encontrado un sitio en el[n]que sirven un caf姻 muy poco com雨n.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Te gustar胤a ir conmigo?[n][w][e]

[msg MND_C03_COOP_03_01]
[s]Haru me est茨 invitando a salir.[n]Tengo que actuar[n]como un caballero.[n][w][e]

[msg MND_C03_COOP_03_02]
[s]Pero dudo que pueda hacerlo[n]con mi [f 4 11 2][clr 26][f 4 12 2][clr 27] actual.[n][w][e]
[s]Podr胤a hacerlo si mi[n][f 4 11 2][clr 26][f 4 12 2][clr 27] fuera [clr 26][f 4 13 2 5][clr 27].[n][w][e]

[msg MND_C03_COOP_03_03]
[s]Con mi [f 4 11 2][clr 26][f 4 12 2][clr 27] actual, creo[n]que puedo acompa隠ar a Haru.[n][w][e]

[msg MSG_C03_COOP_04_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Mmm. Si tienes tiempo, me[n]encantar胤a pasar el rato contigo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tengo que hablarte sobre Takakura.[n][w][e]

[msg MSG_C03_COOP_05_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Estoy pensando en ir a por libros[n]para aprender m茨s sobre el caf姻.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Te importar胤a venir conmigo?[n][w][e]

[msg MSG_C03_COOP_06_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 23 1 203 3 10 0 10]...[n][w][e]
[s][bup 0 7 204 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Ay, perd吋n![n]Me he quedado empanada.[n][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mmm. 夷Te gustar胤a ver[n]c吋mo van las plantas?[n]Me gustar胤a hablar contigo.[n][w][e]

[msg MSG_C03_COOP_07_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Ah, quer胤a hablarte de una cosa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Se me ha ocurrido un buen trato[n]para Takakura y para la empresa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Tienes tiempo para charlar hoy?[n][w][e]

[msg MSG_C03_COOP_08_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]He concertado un encuentro[n]con Takakura.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si no es mucha molestia,[n]me gustar胤a que vinieras.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Hoy tienes tiempo?[n][w][e]

[msg MSG_C03_COOP_09_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]El otro d胤a me pas姻 por[n]la empresa y... tengo malas noticias.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Tienes tiempo para charlar hoy?[n][w][e]

[msg MSG_C03_COOP_09_01 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]El otro d胤a me pas姻[n]por la empresa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tengo muchas cosas que contarte.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Tienes tiempo para charlar hoy?[n][w][e]

[msg MSG_C03_COOP_10_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Je, je... 夷Te preocupan las plantas?[n][w][e]

[msg MSG_C03_COOP_10_10 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 0 65535 0]Je, je... 夷Te preocupan las plantas?[n][w][e]

[msg MND_COOP_DOUZOKUSEI]
[s]Gracias a la Persona del arcano[n][var 2], [clr 1][var 5][clr 27],[n]puedo estrechar lazos con Haru.[n][w][e]

[msg MND_COOP_RANKUP_OK]
[s]Siento que mi v胤nculo con Haru[n]se fortalecer茨 pronto.[n][w][e]

[msg MND_COOP_RANKUP_NG]
[s]No creo que mi v胤nculo con Haru[n]se vaya a fortalecer a雨n.[n][w][e]

[msg MND_COOP_RANK_MAX_00]
[s]Tengo un v胤nculo s吋lido[n]con Haru.[n][w][e]

[msg MND_COOP_RANK_MAX_01]
[s]Tengo un v胤nculo especial[n]con Haru.[n][w][e]

[msg MSG_COOP_CHECK_DUNGEON [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Es bueno desconectar[n]de vez en cuando.[n]夷Quieres pasar el rato con Haru?[n][w][e]

[msg MSG_COOP_CHECK_DAY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entonces, 夷qu姻?[n]夷Quieres pasar un rato con Haru?[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Entonces, 夷qu姻?[n]夷Quieres pasar un rato con Haru?[n][w][e]

[sel SEL_COOP_CHECK top]
[s]Pasar el rato con ella[e]
[s]Comprobar v胤nculo con Haru[e]
[s]Rechazar[e]

[msg MSG_C03_YES_01_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]夷Me vas a ayudar?[n]Bueno, si insistes...[n][w][e]

[msg MSG_C03_YES_02_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]夷Le vas a echar un vistazo?[n]Gracias por ayudarme.[n][w][e]

[msg MSG_C03_YES_03_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3048 65535 0]Pues decidido.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Es el restaurante de un hotel muy[n]caro. Esperemos que el caf姻 est姻[n]a la altura de su reputaci吋n.[n][w][e]

[msg MSG_C03_YES_04_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]Gracias. Tomemos un caf姻[n]mientras charlamos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Ah, ya s姻! 夷Por qu姻 no vamos[n]al Big Bang Burger por cambiar?[n][w][e]

[msg MSG_C03_YES_05_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]斡Gracias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Qu姻 te parece Jinbocho?[n]Es el sitio ideal para buscar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Venga, vamos.[n][w][e]

[msg MSG_C03_YES_06_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]Me alegra escuchar eso. Gracias.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]La verdad es que...[n][w][e]

[msg MSG_C03_YES_07_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3194 65535 0]Vale. Gracias...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ver茨s...[n][w][e]

[msg MSG_C03_YES_08_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]Gracias.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]S姻 que ser姻 capaz de expresarme[n]si est茨s conmigo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, voy a llamar a Takakura.[n][w][e]

[msg MSG_C03_YES_09_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]Gracias.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mmm... 夷podemos hablar en tu casa?[n][w][e]
[s][bup 0 7 204 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]O-oh, 斡no me refer胤a a eso![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Y-yo solo quer胤a tomar caf姻[n]del Jefe! 夷Te parece bien que[n]vayamos all胤?[n][w][e]

[msg MSG_C03_YES_09_10 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]Gracias.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me gustar胤a tomarme una buena taza[n]de caf姻 del Jefe. 夷Podemos ir[n]al Leblanc?[n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, yo ir姻 a dar un paseo[n]mientras est茨s ocupado con ella.[n]Av胤same cuando quieras irte.[n][w][e]

[msg MSG_C03_SPOT_00_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3019 65535 0]夷Qu姻 hacemos hoy?[n][w][e]

[sel SEL_C03_SPOT_00_01 top]
[s]Vamos a alg雨n sitio divertido.[e]
[s]Vamos a mi habitaci吋n.[e]
[s]Ocup姻monos del jard胤n.[e]

[msg MSG_C03_SPOT_00_10 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Genial. 夷Ad吋nde me vas a llevar?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me gustar胤a ir a alg雨n sitio[n]donde vaya la gente normal...[n][w][e]

[msg MSG_C03_MYROOM_00_00 [Haru]]
[s][bup 0 7 206 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]S胤, suena bien.[n][w][e]

[msg MSG_C03_YES_00_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Pues decidido.[n][w][e]

[msg MSG_C03_YES_00_07 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Pues decidido. Si viene[n]alguien, esc吋ndete, 夷vale?[n][w][e]

[msg MSG_C03_YES_10_00 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Pues decidido.[n][w][e]

[msg MSG_C03_YES_10_07 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Pues decidido. Si viene[n]alguien, te proteger姻.[n][w][e]

[msg MSG_C03_YES_10_10 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Pues decidido.[n][w][e]

[msg MSG_C03_YES_10_17 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3020 65535 0]Pues decidido. Si viene[n]alguien, te proteger姻.[n][w][e]

[msg MSG_C03_COOP_CANCEL_00 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3064 65535 0]Entiendo... Otra vez ser茨.[n][w][e]

[msg MSG_C03_BEGIN_D10_REV [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3192 65535 0]Oh, [f 4 2]...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hace m茨s fr胤o 雨ltimamente, 夷no?[n]夷Necesitas algo?[n][w][e]

[msg MSG_C03_BEGIN_D10_REV_OK [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3192 65535 0][f 4 2]... 夷Qu姻 te [n]trae por aqu胤 hoy?[n][w][e]

[sel SEL_COOP_CHECK_REV top]
[s]He venido a verte.[e]
[s]He venido por las verduras.[e]
[s]Nos vemos en el escondite.[e]
[s]Nada en particular.[e]

[msg MSG_C03_COOP_10_00_REV [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 53516 65535 0]夷Tienes tiempo ahora?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Necesito contarte algo...[n]夷Te parece bien?[n][w][e]

[msg MND_COOP_RANK_MAX__REV]
[s]Parece que Haru tiene[n]algo en mente...[n][w][e]

[msg MSG_COOP_CHECK_3RD_REV [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1189 65535 0]Haru...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Qu姻 vas a hacer?[n]夷Quieres pasar el d胤a con Haru?[n][w][e]

[sel SEL_COOP_CHECK_REV2 top]
[s]Pasar el rato con ella[e]
[s]Comprobar v胤nculo con Haru[e]
[s]Rechazar[e]

[msg MSG_C03_YES_10_00_REV [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]Gracias. Entonces,[n]夷podemos ir a mi casa hoy?[n][w][e]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Te voy a servir un delicioso[n]t姻 negro. Espera un momento[n]mientras me cambio.[n][w][e]

[msg MSG_C03_HARVEST_REV [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3030 65535 0]夷Has venido a ver las plantas?[n]Est茨n bien.[n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE_ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vale, entonces me marcho.[n]Te dejo a la se隠orita Ann.[n][w][e]

[msg MSG_C03_COOP_CANCEL_REV [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 53561 65535 0]Ah, vale. Lo siento...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Av胤same cuando tengas tiempo,[n][f 4 2]. Aqu胤 te espero.[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Ya puedes ir a [clr 1]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Ya puedes ir a [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Ya puedes ir a [clr 2]Akihabara[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Parque Inokashira[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el ramen[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Parque Seaside de Odaiba[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste este tipo[n]de parques para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Museo Ueno[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le gusten los museos[n]de arte para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el monjayaki[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]calle Takenoko de Harajuku[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente a[n]la que le guste la calle Takenoko[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Chinatown de Motomachi[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Destinyland de Maihama[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]Puedes invitar a gente a la que le[n]guste la Skytree o la calle[n]Nakamise para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Planetario de Ikebukuro[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Santuario Meiji[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir por tu cuenta[n]para venerarlo.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Dome Town de Suidobashi[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Hotel Wilton de Shibuya[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]restaurante de sushi de Ginza[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el sushi caro[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Tienes informaci吋n sobre un nuevo[n]punto de encuentro: [clr 2]La ciudad[n]de los libros de Jinbocho[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir por tu cuenta[n]a comprar.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Estanque Ichigaya[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste pescar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir[n]por tu cuenta para ver[n]qu姻 tal se te da pescar.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Acuario de Shinagawa[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el acuario[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]zona comercial de Nakano[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste ese lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_C03_BYEGREET_00_00 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]Lo has conseguido.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Te he pedido ayuda[n]tant胤simas veces...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Pero gracias a ti,[n]la nueva cafeter胤a[n]va a abrir su primer local.[n][w][e]

[sel SEL_C03_BYEGREET_00_01 top]
[s]Qu姻 alivio.[e]
[s]Espero que no decepcione.[e]
[s]夷Qu姻 tal est茨 el caf姻?[e]

[msg MSG_C03_BYEGREET_00_02 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]La verdad es que s胤...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Adem茨s, voy a ser part胤cipe de su crecimiento[n]mientras voy a la universidad.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Me va a costar sacarlo todo adelante,[n]pero es la oportunidad perfecta[n]para aprender el oficio.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]As胤 me asegurar姻 de que todo[n]vaya sobre ruedas cuando por fin[n]abra mi propia cafeter胤a.[n][w][e]

[msg MSG_C03_BYEGREET_00_03 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]Gracias.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]Adem茨s, voy a ser part胤cipe de su crecimiento[n]mientras voy a la universidad.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Me va a costar sacarlo todo adelante,[n]pero es la oportunidad perfecta[n]para aprender el oficio.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]As胤 me asegurar姻 de que todo[n]vaya sobre ruedas cuando por fin[n]abra mi propia cafeter胤a.[n][w][e]

[msg MSG_C03_BYEGREET_00_04 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Todav胤a no lo s姻, pero espero[n]que se parezca al del Leblanc.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Adem茨s, voy a ser part胤cipe de su crecimiento[n]mientras voy a la universidad.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]Me va a costar sacarlo todo adelante,[n]pero es la oportunidad perfecta[n]para aprender el oficio.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 15 65535 0]As胤 me asegurar姻 de que todo[n]vaya sobre ruedas cuando por fin[n]abra mi propia cafeter胤a.[n][w][e]

[msg MSG_C03_BYEGREET_00_05 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 16 65535 0]Y, bueno... quiero que est姻s conmigo[n]cuando eso ocurra.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]Por cierto, he intentado[n]hacerte una cosa.[n][w][e]

[msg MSG_C03_BYEGREET_00_06 [Haru]]
[s][bup 0 7 0 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 18 65535 0]Quiero vender art胤culos artesanales[n]en la cafeter胤a,[n]as胤 que he hecho esto para practicar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 19 65535 0]Perd吋n si se desti隠e[n]cuando lo uses.[n][w][e]
[s][bup 0 7 6 65535 0][f 4 10 65535 0 0][vp 8 0 1 20 65535 0]Anda, 斡igual deber胤a probar[n]a hacer sombreros! 夷Hago unos a juego?[n][w][e]
[s][f 4 10 65535 0 230][vp 8 0 1 21 65535 0]Es... mi promesa hacia ti.[n][w][e]

[msg MSG_C03_BYEGREET_00_07 [Haru]]
[s][bup 0 7 6 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 230][vp 8 0 1 22 65535 0]Es... mi promesa hacia ti.[n][w][e]

[msg MSG_C03_BYEGREET_01_00 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 23 65535 0][f 4 2]...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]Qu姻 raro vernos aqu胤.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 25 65535 0]A todo esto, la nueva cafeter胤a[n]va a abrir su primer local.[n][w][e]

[sel SEL_C03_BYEGREET_01_01 top]
[s]Lo has hecho genial.[e]
[s]Qu姻 buena noticia.[e]
[s]Espero que haya una cerca de m胤.[e]

[msg MSG_C03_BYEGREET_01_02 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 26 65535 0]Aunque lo m茨s importante[n]a雨n est茨 por llegar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 27 65535 0]A decir verdad,[n]voy a gestionar la cafeter胤a[n]mientras voy a la universidad.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 28 65535 0]Aprender姻 todo lo que hay[n]que saber hasta que alg雨n d胤a[n]pueda abrir la m胤a propia.[n][w][e]

[msg MSG_C03_BYEGREET_01_03 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]La verdad es que s胤...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 30 65535 0]A decir verdad,[n]voy a gestionar la cafeter胤a[n]mientras voy a la universidad.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 31 65535 0]Aprender姻 todo lo que hay[n]que saber hasta que alg雨n d胤a[n]pueda abrir la m胤a propia.[n][w][e]

[msg MSG_C03_BYEGREET_01_04 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]斡Claro! Te avisar姻.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 33 65535 0]A decir verdad,[n]voy a gestionar la cafeter胤a[n]mientras voy a la universidad.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]Aprender姻 todo lo que hay[n]que saber hasta que alg雨n d胤a[n]pueda abrir la m胤a propia.[n][w][e]

[msg MSG_C03_BYEGREET_01_05 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 35 65535 0]Por cierto, he intentado[n]hacerte una cosa.[n][w][e]

[msg MSG_C03_BYEGREET_01_06 [Haru]]
[s][bup 0 7 0 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 36 65535 0]Quiero vender art胤culos artesanales[n]en la cafeter胤a,[n]as胤 que he hecho esto para practicar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 37 65535 0]Perd吋n si se desti隠e[n]cuando lo uses.[n][w][e]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 38 65535 0][f 4 2], gracias[n]por estar ah胤 y ayudarme.[n][w][e]
[s][f 4 10 65535 0 530][vp 8 0 1 39 65535 0]Eres... mi h姻roe. Ojal茨 pueda[n]devolverte el favor alg雨n d胤a.[n][w][e]

[msg MSG_C03_BYEGREET_01_07 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 530][vp 8 0 1 40 65535 0]Eres... mi h姻roe. Ojal茨 pueda[n]devolverte el favor alg雨n d胤a.[n][w][e]

[msg MSG_C03_BYEGREET_00_00_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 41 65535 0]Lo has conseguido.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 42 65535 0]Te he pedido ayuda[n]tant胤simas veces...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 43 65535 0]Pero gracias a ti,[n]la nueva cafeter胤a[n]va a abrir su primer local.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 44 65535 0]Lo cierto es que estar姻 involucrada en la[n]inauguraci吋n mientras voy a la universidad.[n][w][e]

[sel SEL_C03_BYEGREET_00_01_5 top]
[s]Parece que la cosa marcha.[e]
[s]Me muero de ganas.[e]
[s]夷C吋mo sabr茨 el caf姻?[e]

[msg MSG_C03_BYEGREET_00_02_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 45 65535 0]As胤 es. No solo estoy reconstruyendo[n]la empresa, tambi姻n persigo mi sue隠o.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 46 65535 0]Compaginar los estudios[n]y el trabajo no ser茨 f茨cil,[n]pero juro que lo conseguir姻.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 47 65535 0]Adem茨s, si lo consigo,[n]podr姻 llevar mi propia cafeter胤a.[n][w][e]

[msg MSG_C03_BYEGREET_00_03_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 48 65535 0]S胤, confieso que tengo ganas de ver[n]qu姻 me depara el futuro.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 49 65535 0]S姻 que ser茨 dif胤cil.[n]Tendr姻 que compaginar los estudios[n]y la gesti吋n de la empresa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 50 65535 0]Pero todo sea por hacer realidad[n]mi sue隠o.[n]Prometo que saldr姻 adelante.[n][w][e]

[msg MSG_C03_BYEGREET_00_04_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 51 65535 0]Los empleados est茨n haciendo[n]pruebas de calidad.[n]No queremos perder el toque artesano.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 52 65535 0]S姻 que ser茨 dif胤cil.[n]Tendr姻 que compaginar los estudios[n]y la gesti吋n de la empresa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 53 65535 0]Pero todo sea por hacer realidad[n]mi sue隠o.[n]Prometo que saldr姻 adelante.[n][w][e]

[msg MSG_C03_BYEGREET_00_05_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 54 65535 0]Dicho esto, es cierto que estoy[n]un poco nerviosa.[n]Tengo que saber si soy capaz.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 55 65535 0]Pero, mientras est姻 contigo, tengo[n]que demostrar que soy digna[n]de tu apoyo y de tu orgullo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 56 65535 0]Por cierto, he intentado[n]hacerte una cosa.[n][w][e]

[msg MSG_C03_BYEGREET_00_06_5 [Haru]]
[s][bup 0 7 0 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 57 65535 0]Quiero vender art胤culos artesanales[n]en la cafeter胤a,[n]as胤 que he hecho esto para practicar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 58 65535 0]No puedo tirar por la borda[n]la reputaci吋n de mi abuelo[n]ni el legado de mi padre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 59 65535 0]Tiene que ser un lugar c吋modo[n]y acogedor, un sitio[n]donde la gente pueda estar a gusto.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 60 65535 0]Ser茨s el primero en saber[n]cu茨ndo abrir茨.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 61 65535 0]He decidido que ser茨s[n]mi primer cliente, [f 4 2].[n][w][e]

[msg MSG_C03_BYEGREET_00_07_5 [Haru]]
[s][bup 0 7 6 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 230][vp 8 0 1 62 65535 0]Ser茨s el primero en saber[n]cu茨ndo abrir茨.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 63 65535 0]He decidido que ser茨s[n]mi primer cliente, [f 4 2].[n][w][e]

[msg MSG_C03_BYEGREET_01_00_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 64 65535 0][f 4 2]...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 65 65535 0]Qu姻 raro vernos aqu胤.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 66 65535 0]A todo esto, la nueva cafeter胤a[n]va a abrir su primer local.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 67 65535 0]Lo cierto es que estar姻 involucrada en la[n]inauguraci吋n mientras voy a la universidad.[n][w][e]

[sel SEL_C03_BYEGREET_01_01_5 top]
[s]As胤 que vas a perseguir tu sue隠o.[e]
[s]夷Y lo de tu propia cafeter胤a?[e]
[s]Me encantar胤a ir y tomarme un caf姻.[e]

[msg MSG_C03_BYEGREET_01_02_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 68 65535 0]Sin duda. No es m茨s que el primer paso,[n]pero sigue siendo crucial.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 69 65535 0]S姻 que ser茨 dif胤cil.[n]Tendr姻 que compaginar los estudios[n]y la gesti吋n de la empresa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 70 65535 0]Pero todo sea por hacer realidad[n]mi sue隠o.[n]Prometo que saldr姻 adelante.[n][w][e]

[msg MSG_C03_BYEGREET_01_03_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 71 65535 0]Todav胤a falta mucho,[n]pero mientras tanto quiero aprender[n]todo lo que pueda.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 72 65535 0]Podr胤a aprender lo m茨s b茨sico[n]sobre gesti吋n. Me ser茨 雨til[n]cuando vaya a abrir mi propia cafeter胤a.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 73 65535 0]Compaginar los estudios[n]y el trabajo no ser茨 f茨cil,[n]pero juro que lo conseguir姻.[n][w][e]

[msg MSG_C03_BYEGREET_01_04_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 74 65535 0]斡Tenemos pensado expandirnos[n]por otras regiones! A lo mejor[n]montamos una en tu ciudad, [f 4 2].[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 75 65535 0]Tendr姻 que compaginar los estudios[n]y la gesti吋n de la empresa.[n]No ser茨 tarea f茨cil.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 76 65535 0]Pero todo sea por hacer realidad[n]mi sue隠o.[n]Prometo que saldr姻 adelante.[n][w][e]

[msg MSG_C03_BYEGREET_01_05_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 77 65535 0]Por cierto, he intentado[n]hacerte una cosa.[n][w][e]

[msg MSG_C03_BYEGREET_01_06_5 [Haru]]
[s][bup 0 7 0 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 0][vp 8 0 1 78 65535 0]Quiero vender art胤culos artesanales[n]en la cafeter胤a,[n]as胤 que he hecho esto para practicar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 79 65535 0]Quiero estar a la altura[n]de la reputaci吋n de mi abuelo...[n]y del legado de mi padre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 80 65535 0]Tiene que ser un lugar c吋modo[n]y acogedor, un sitio[n]donde la gente pueda estar a gusto.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 81 65535 0]Tendr胤amos que quedar todos[n]all胤 cuando abra,[n]como cuando 胤bamos al Leblanc.[n][w][e]

[msg MSG_C03_BYEGREET_01_07_5 [Haru]]
[s][bup 0 7 1 65535 0][f 4 23 1 203 3 10 0 10][f 4 10 65535 0 530][vp 8 0 1 82 65535 0]Tendr胤amos que quedar todos[n]all胤 cuando abra,[n]como cuando 胤bamos al Leblanc.[n][w][e]

