[msg HELP_UIRANAI_KAIUN]
[s]Mejores resultados al aumentar[n]las estad胤sticas sociales.[n][e]

[msg HELP_UIRANAI_KINUN]
[s]El dinero de recompensa[n]de un combate aumentar茨[n]si ganas con un ataque combinado.[n][e]

[msg HELP_UIRANAI_RENAI]
[s]Predice tu compatibilidad con[n]un personaje para fortalecer[n]vuestra conexi吋n.[n][e]

[msg HELP_UIRANAI_UNMEI]
[s]Puedes ver todas[n]las habilidades de Confidente[n]de un personaje.[n][e]

[msg HELP_UIRANAI_ALERT]
[s]Suena una Alarma de fusi吋n[n]en la prisi吋n de [f 4 2].[n][e]

[msg HELP_RENAI_SECRETS_5R]
[s]Entiendes lo que quieren[n]escuchar tus Confidentes[n]cuando pasas tiempo con ellos.[n][e]

[msg HELP_URANAI_COOP_C02]
[s]La Sacerdotisa:[n]Confidente[n]Makoto Niijima[n][e]

[msg HELP_URANAI_COOP_C03]
[s]La Emperatriz:[n]Confidente[n]Haru Okumura[n][e]

[msg HELP_URANAI_COOP_C04]
[s]El Emperador:[n]Confidente[n]Yusuke Kitagawa[n][e]

[msg HELP_URANAI_COOP_C05]
[s]El Hierofante:[n]Confidente[n]Sojiro Sakura[n][e]

[msg HELP_URANAI_COOP_C06]
[s]Los Amantes:[n]Confidente[n]Ann Takamaki[n][e]

[msg HELP_URANAI_COOP_C07]
[s]El Carro:[n]Confidente[n]Ryuji Sakamoto[n][e]

[msg HELP_URANAI_COOP_C08]
[s]La Justicia:[n]Confidente[n]Goro Akechi[n][e]

[msg HELP_URANAI_COOP_C09]
[s]El Ermita隠o:[n]Confidente[n]Futaba Sakura[n][e]

[msg HELP_URANAI_COOP_C10]
[s]La Fortuna:[n]Confidente[n]Adivina[n][e]

[msg HELP_URANAI_COOP_C12]
[s]El Ahorcado:[n]Confidente[n]Vendedor de armas[n][e]

[msg HELP_URANAI_COOP_C13]
[s]La Muerte:[n]Confidente[n]Doctora del callej吋n[n][e]

[msg HELP_URANAI_COOP_C14]
[s]La Templanza:[n]Confidente[n]Sadayo Kawakami[n][e]

[msg HELP_URANAI_COOP_C15]
[s]El Diablo:[n]Confidente[n]Ichiko Ohya[n][e]

[msg HELP_URANAI_COOP_C16]
[s]La Torre:[n]Confidente[n]Jugador h茨bil[n][e]

[msg HELP_URANAI_COOP_C17]
[s]La Estrella:[n]Confidente[n]Hifumi Togo[n][e]

[msg HELP_URANAI_COOP_C18]
[s]La Luna:[n]Confidente[n]Yuuki Mishima[n][e]

[msg HELP_URANAI_COOP_C19]
[s]El Sol:[n]Confidente[n]Hombre del pueblo[n][e]

[msg HELP_URANAI_COOP_C22]
[s]Fe:[n]Confidente[n][f 4 31 10 1] Yoshizawa[n][e]

[msg HELP_URANAI_COOP_C23]
[s]El Consejero:[n]Confidente[n]Takuto Maruki[n][e]

[msg HELP_URANAI_COOP_C00]
[s]El Loco:[n]Confidente[n]Maestro de la prisi吋n[n][e]

[msg HELP_URANAI_COOP_C01]
[s]El Mago:[n]Confidente[n]Morgana[n][e]

[msg HELP_URANAI_COOP_C11]
[s]La Fuerza:[n]Confidente[n]Alcaidesas[n][e]

[msg MSG_C10_PRE_FACILITY_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Eh, es la adivina[n]de la que todo el mundo habla.[n]夷Quieres que te lea el futuro?[n][w][e]

[sel SEL_C10_PRE_FACILITY_01 top]
[s]S胤.[e]
[s]No.[e]

[msg MSG_C10_PRE_FACILITY_02 [Adivina alegre]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10003 210 0]Uy, 斡holaaa! Si姻ntate, por favor.[n][w][e]

[msg MSG_C10_PRE_FACILITY_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1059 65535 0]夷No? 斡Pues yo s胤 quiero![n][w][e]

[msg MSG_C10_PRECOOP_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10001 65535 0]Ah, t雨 eres [f 4 1],[n]el del otro d胤a, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me acuerdo de ti. Recuerdo que tu[n]destino era bastante at胤pico.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si姻ntense, por favor.[n][w][e]

[msg MSG_C10_PRECOOP_00_99 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10001 65535 0]De nuevo por aqu胤, 夷eh?[n]Si姻ntate, por favor.[n][w][e]

[msg MSG_C10_PRECOOP_00_01 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10086 65535 0]Quer胤as comprar una Piedra sagrada,[n]夷no? 斡Podr茨s cambiar tu destino por[n]solo 100 000 yenes![n][w][e]

[msg MSG_C10_PRECOOP_00_01_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Por esa cantidad, no solo deber胤a[n]cambiar tu destino, sino otorgarte[n]la mejor de las suertes.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si al final compras una,[n]debemos ir a casa para probarla.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, 夷qu姻 quieres hacer?[n][w][e]

[sel SEL_C10_PRECOOP_00_02 top]
[s]Me llevar姻 una.[e]
[s]No voy a comprar nada.[e]

[msg MSG_C10_PRECOOP_00_03 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]斡Muchas gracias![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Aqu胤 tiene.[n][w][e]

[msg MSG_C10_PRECOOP_00_04 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10020 65535 0]En vista de que es la mejor forma[n]de evitar la mala suerte,[n]es lo m茨s inteligente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ya est茨 cargada con un aura[n]de felicidad, as胤 que notar茨s[n]los efectos de inmediato.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Acu姻rdate de recargarla con[n]la luz de la luna cada tres d胤as.[n][w][e]

[msg MSG_C10_PRECOOP_00_05 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Vuelve por aqu胤 y cu姻ntame c吋mo[n]te ha cambiado el destino.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 10051 65535 0]Adi吋s...[n][w][e]

[msg MND_C10_PRECOOP_00_06]
[s]Deber胤a irme...[n][w][e]

[msg MSG_C10_PRECOOP_00_10 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10043 65535 0]No tienes dinero suficiente.[n]No me hagas perder el tiempo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Regresa cuando tengas[n]la cantidad necesaria.[n][w][e]

[msg MSG_C10_PRECOOP_00_20 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]El destino es absolutoe inalterable.[n][w][e]

[msg MSG_C10_PREQUEST_00_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Pregunt姻mosle a Chihaya por la[n]Piedra sagrada.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Eh? Est茨 con un cliente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me parece que est茨n hablando[n]sobre la Piedra sagrada.[n]A ver si te enteras de algo...[n][w][e]

[msg MSG_C10_PREQUEST_00_99 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Parece que est茨 hablando con un[n]cliente sobre la Piedra sagrada.[n]A ver si te enteras de algo...[n][w][e]

[sel SEL_C10_PREQUEST_00_01 top]
[s]Poner la oreja[e]
[s]No poner la oreja[e]

[msg MSG_C10_PREQUEST_00_02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0]夷Le vas a presentar alguna queja[n]sobre la Piedra sagrada?[n][w][e]

[msg MSG_C10_QUESTNOW_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10067 65535 0]Veremos si su destino cambia o no.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estoy deseando o胤r el resultado.[n][w][e]

[msg MND_C10_QUESTNOW_00_01]
[s]Si voy a Mementos y despierto el[n]coraz吋n de ese novio abus吋n, ver茨[n]que se puede alterar el destino.[n][w][e]

[msg MSG_C10_PRECOOP_10_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10056 65535 0]夷Y bien? 夷Le cambi吋 el destino?[n][w][e]

[msg MSG_C10_PRECOOP_10_99 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10043 65535 0]夷Algo m茨s? Ya sabes que el destino[n]no se puede cambiar.[n][w][e]

[sel SEL_C10_PRECOOP_10_01 top]
[s]Decirle el resultado[e]
[s]No decirle el resultado[e]

[msg MSG_C10_PRECOOP_10_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10073 65535 0]Vale, cu姻ntame.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Toma asiento, por favor.[n][w][e]

[msg MSG_C10_PRECOOP_10_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]El destino es absoluto. Solo una[n]Piedra sagrada puede cambiarlo.[n][w][e]

[msg MSG_C10_BEGIN_QUEST_00 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10021 65535 0]El Trickster que me ayudar茨...[n]夷Qu姻 significa esto?[n][w][e]

[msg MSG_C10_BEGIN_QUEST_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10001 65535 0]斡Ah, [f 4 1]![n][w][e]

[msg MSG_URANAI_SASOI_THROUGH [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10096 65535 0]Si no te importa...[n][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]A partir de ahora, te escribir姻.[n][w][e]

[msg MSG_URANAI_SASOI_THROUGH_2 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10044 65535 0]斡Mmm...! Malos augurios en[n]torno a tus relaciones.[n][w][e]
[s][vp 8 2 1 0 65535 0][f 4 10 65535 0 0]Podr胤a ser un castigo por[n]desatender a los dem茨s. Los actos[n]de sinceridad ser茨n la clave.[n][w][e]

[msg MSG_C10_BEGIN_WEATHER_00 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10009 65535 0]No me gusta la lluvia...[n]Aqu胤 caen chuzos de punta.[n][w][e]

[msg MSG_C10_BEGIN_WEATHER_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10011 65535 0]Es raro que nieve en la ciudad.[n]Hace mucho fr胤o,[n]as胤 que igual cierro y me voy.[n][w][e]

[msg MSG_C10_BEGIN_WEATHER_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10012 65535 0]El tiempo est茨 loco. Ahora llueve,[n]de repente deja de llover...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Siento tener que cerrar[n]tanto 雨ltimamente.[n][w][e]

[msg MSG_C10_BEGIN_WEATHER_03 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10013 65535 0]Qu姻 viento hace...[n]斡Se me van a volar las cartas![n]Ser茨 mejor que cierre ya.[n][w][e]

[msg MSG_C10_BEGIN_WEATHER_04 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10014 65535 0]Aunque no haya[n]茨rboles en la ciudad,[n]hay mucha gente con alergias.[n][w][e]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Normalmente, me gu胤o por las caras[n]de mis clientes, pero con las[n]m茨scaras es complicado saberlo.[n][w][e]

[msg MSG_C10_BEGIN_WEATHER_05 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10015 65535 0]Esta lluvia es una locura.[n]Con este techo tan peque隠o,[n]se me va a empapar el puesto.[n][w][e]

[msg MSG_C10_BEGIN_WEATHER_06 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10016 65535 0]Qu姻 calor hace hoy.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]He sacado el puesto a la calle[n]para ver a la gente pasar,[n]pero igual me derrito.[n][w][e]

[msg MSG_C10_BEGIN_WEATHER_07 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10017 65535 0]Todo el mundo va con m茨scara.[n]夷Es para no pillar la gripe?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pues que sepas que a veces[n]constiparse es cosa del destino.[n][w][e]

[msg MSG_C10_BEGIN_WEATHER_08 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10017 65535 0]Uf... 斡夷Por qu姻 hace tanto fr胤ooo?![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Me estar茨 diciendo el destino[n]que deje de trabajar por hoy?[n][w][e]

[msg MSG_C10_BEGIN_TIME_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 23 1 210 14 10 13 10]No me gusta que la gente me pida[n]que adivine si les van a subir[n]la paga de verano.[n][w][e]
[s]Siempre pienso que ojal茨[n]me lo hubieran pedido antes...[n][w][e]

[msg MSG_C10_BEGIN_TIME_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 23 1 210 14 10 13 10]No me gusta que la gente me pida[n]que adivine si les van a subir[n]la paga de verano.[n][w][e]
[s]Siempre pienso que ojal茨[n]me lo hubieran pedido antes...[n][w][e]

[msg MSG_C10_BEGIN_TIME_03 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10021 65535 0]Mmm...[n]Parece que se te avecinan[n]diversas cat茨strofes.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Es una de las pistas de la muerte.[n]夷M... E... D... J...?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No puedo descifrar nada m茨s, pero[n]tendr茨s que tener cuidado.[n][w][e]

[msg MSG_C10_BEGIN_TIME_04 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10091 65535 0]Percibo que tienes problemas[n]con las mujeres.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Mm...? La 雨ltima vez[n]tambi姻n hab胤a una mujer.[n]Espera, 夷eso es...?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E-en fin, ten cuidado, anda.[n][w][e]

[msg MSG_C10_BEGIN_TIME_05 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10001 65535 0]Ah, me preguntaba c吋mo te iba,[n]as胤 que te he echado las cartas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]He probado varias veces[n]y siempre aparece[n]la carta de la Emperatriz.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]La 雨ltima vez me pareci吋 que ten胤as[n]problemas con las mujeres,[n]pero ahora percibo algo distinto...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E-en fin, ten cuidado, anda.[n][w][e]

[msg MSG_C10_BEGIN_TIME_06 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10021 65535 0][f 4 1]...[n]夷Seguuuro que todo ir茨 bien?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lo percibo con solo mirarte[n]a la cara. El aura de la muerte[n]emite una luz extra隠a...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Por favor, ten cuidado.[n][w][e]

[msg MSG_C10_BEGIN_TIME_07 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10021 65535 0]Est茨s vivo, pero a la vez[n]est茨s muerto.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No cabe duda de que tienes[n]un destino interesante.[n][w][e]

[msg MSG_C10_BEGIN_TIME_08 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10018 65535 0]Te he echado las cartas[n]por curiosidad.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hasta ahora no he podido[n]ver bien tu destino,[n]pero pronto se aclarar茨 todo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Por favor, prep茨rate.[n][w][e]

[msg MSG_C10_BEGIN_TIME_09 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10018 65535 0]斡[f 4 1]! 郁ltimamente,[n]todo es muy extra隠o.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Da igual a qui姻n le lea el futuro,[n]solo hay felicidad[n]y buenos momentos. Es asombroso...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me alegra que todos sean felices,[n]pero... 夷por qu姻 me preocupa tanto?[n][w][e]

[msg MSG_C10_CONNECT_NG_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Bueno, 夷quieres que te lea[n]el futuro en detalle?[n][w][e]

[msg MSG_C10_CONNECT_OK_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Bueno, 夷qu姻 te gustar胤a hacer hoy?[n][w][e]

[msg MSG_C10_CONNECT_OK_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]夷Has recibido mis mensajes?[n]夷Qu姻 te gustar胤a hacer hoy?[n][w][e]

[msg MSG_C10_CONNECT_NG_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]No puedo ver mi futuro[n]con claridad, pero el tuyo s胤...[n][w][e]

[msg MSG_C10_CONNECT_OK_02 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]斡Te estaba esperando! 夷Podemos hablar?[n][w][e]

[msg MSG_C10_BEGIN_SECOND_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10018 65535 0]夷Necesitas algo m茨s?[n][w][e]

[sel SEL_C10_BUY_OR_COOP top]
[s]Hacer una prueba de comprobaci吋n[e]
[s]Conocer el futuro[e]
[s]No hacer nada[e]

[sel SEL_C10_BUY_OR_COOP_7 top]
[s]Claro.[e]
[s]Quiero conocer mi futuro.[e]
[s]No, nada.[e]

[sel SEL_C10_DOUBT top]
[s]Escucha mi historia.[e]
[s]Quiero conocer mi futuro.[e]
[s]No, nada.[e]

[msg MSG_C10_SHOP_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]De acuerdo. Si姻ntate, por favor.[n][w][e]

[msg MSG_C10_SHOP_01_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10089 65535 0]夷Qu姻 quieres saber del futuro?[n][w][e]

[msg TITLE_URANAI_MENU]
[s]Lecturas de Chihaya[n][e]

[sel SEL_URANAI_CHK_MENU top]
[s]Lectura de fortuna[ref 0 0][e]
[s]Lectura de dinero[ref 1 1][e]
[s]Lectura de afinidad[ref 2 2][e]
[s]Lectura especial del sino[ref 3 3][e]
[s]Lectura celestial[ref 4 4][e]
[s]Lectura especial de v胤nculo[ref 5 5][e]

[msg MSG_C10_SHOP_02_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10056 65535 0]Espero que te haya gustado[n]la predicci吋n.[n]Ojal茨 volvamos a vernos.[n][w][e]

[msg MSG_C10_SHOP_00_01 [Chihaya]]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]No puedo echarte las cartas[n]de momento, pues no conf胤o en ti.[n][w][e]

[msg MSG_C10_SHOP_00_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Creo que ahora no te va a leer el[n]futuro, as胤 que despej姻mosle[n]las dudas.[n][w][e]

[msg MSG_C10_SHOP_03_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10063 65535 0]Espero volver a verte pronto.[n][w][e]

[msg MSG_C10_SHOP_03_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10054 65535 0]斡P茨sate de nuevo[n]cuando tengas tiempo![n][w][e]

[msg MSG_C10_COOP_NG_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10032 65535 0]Lo siento. Tengo otro cliente[n]despu姻s.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero puedo hacer la prueba de[n]comprobaci吋n por la noche.[n]P茨sate luego.[n][w][e]

[msg MSG_C10_COOP_NG_00_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10032 65535 0]Lo lamento. Ya voy a cerrar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vuelve en otro momento.[n][w][e]

[msg MSG_C10__COOP_NG_01_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10028 65535 0]Tengo un mont吋n de clientes[n]despu姻s, as胤 que vuelve[n]en otro momento, por favor.[n][w][e]

[msg MSG_C10_COOP_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10051 65535 0]Si姻ntate, por favor.[n][w][e]

[msg MSG_C10_COOP_10_00 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10035 65535 0]夷Hacemos una prueba de comprobaci吋n[n]de los Ladrones Fantasma?[n][w][e]

[msg MSG_C10_COOP_10_01 [Chihaya]]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10133 65535 0]Quiz茨 lea... nuestro futuro...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]P-por favor, toma asiento.[n][w][e]

[msg MSG_C10_SPOT_01_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Tu destino es muy... interesante.[n]Me gustar胤a probar una t姻cnica[n]de adivinaci吋n diferente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]He consultado todos mis libros...[n]Quiz茨 necesite alguno que est姻[n]agotado. 夷D吋nde podr胤a haber?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, da igual. Comencemos con la[n]prueba de comprobaci吋n.[n][w][e]

[msg MSG_C10_SPOT_02_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]La Torre se ha oscurecido. 夷Has[n]sufrido alg雨n cambio a gran altura?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Av胤same si se te viene algo[n]a la cabeza.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ahora toma asiento, por favor.[n][w][e]

[msg MSG_C10_SPOT_03_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Y... aquella noria en la que[n]nos montamos el otro d胤a...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Espero poder disfrutarla de nuevo.[n]Contigo, por supuesto.[n][w][e]
[s][bup 0 113 7 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, a ver..., comencemos con la[n]prueba de comprobaci吋n de los[n]Ladrones Fantasma.[n][w][e]

[msg MSG_C10_SPOT_04_00 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Aqu胤 huele fatal a gases de escape[n]y comida de los restaurantes.[n][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ojal茨 pudiera dar un paseo para[n]alejarme del ruido y contemplar[n]el cielo o el mar...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Era broma. Empecemos con la prueba[n]de comprobaci吋n. Si姻ntate, por favor.[n][w][e]

[msg MSG_C10_SPOT_05_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Ho-hola.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E-eh...夷C吋mo es tu cuarto?[n]夷Es justo como lo vi?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]E-eh, 夷la prueba de comprobaci吋n?[n]S胤, ya vamos.[n][w][e]

[msg MSG_C10_COOP_01_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]斡Te estaba esperando![n]斡Quiero hacer ya la prueba[n]de comprobaci吋n![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Seguro que descubro tus trucos![n][w][e]

[msg MSG_C10_COOP_02_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]斡Adelante![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡A雨n no hemos acabado[n]con las pruebas![n][w][e]

[msg MSG_C10_COOP_03_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Has venido por la prueba[n]de comprobaci吋n, 夷verdad? Pues...[n]es que iba a cerrar ya.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero 夷te importa que hablemos[n]de otro asunto?[n][w][e]

[msg MSG_C10_COOP_04_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Quiero decirte un mont吋n de cosas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si姻ntate, por favor.[n][w][e]

[msg MSG_C10_COOP_05_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]斡Te estaba esperando! 斡No te vas[n]a creer lo que ha pasado![n][w][e]

[msg MSG_C10_COOP_06_00 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mmm... 夷Te acuerdas de[n]lo que pas吋 la 雨ltima vez?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Aquel hombre, el presidente[n]Fukurai, ha venido a verme.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Podr胤as quedarte[n]a charlar un rato?[n][w][e]

[msg MSG_C10_COOP_07_00 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Quisiera comentarte algo. El caso[n]de la APD es m茨s complejo de[n]lo que pensaba.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]*suspiro* 夷Qu姻 voy a hacer?[n][w][e]

[msg MSG_C10_COOP_07_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10126 65535 0]Quedan pendientes las pruebas[n]de comprobaci吋n. Debo centrarme en[n]los tejemanejes del presidente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ya dir姻 algo si logro avanzar.[n][w][e]

[msg MND_C10_COOP_07_02]
[s]Chihaya tiene problemas... Tengo[n]que ir a Mementos y despertar[n]el coraz吋n del presidente.[n][w][e]

[msg MSG_C10_COOP_07_03 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]斡Uy, si姻ntate! 斡Si姻ntate![n]斡Tengo muchas cosas que contar![n][w][e]

[msg MSG_C10_COOP_08_00 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]斡He avanzado mucho[n]con el caso de la APD![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Si姻ntate, que me muero[n]por cont茨rtelo![n][w][e]

[msg MSG_C10_COOP_09_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Me gustar胤a preguntarte una cosa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Toma asiento, por favor.[n][w][e]

[msg MSG_C10_COOP_09_01 [Chihaya]]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Acabo de leer...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nuestro...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡T-tienes que o胤r esto![n][w][e]

[msg MND_COOP_DOUZOKUSEI]
[s]Gracias a la Persona del arcano[n][var 2], [clr 1][var 5][clr 27],[n]puedo estrechar lazos con Chihaya.[n][w][e]

[msg MND_COOP_RANKUP_OK]
[s]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][w][e]

[msg MND_COOP_RANKUP_NG]
[s]No creo que mi v胤nculo con Chihaya[n]se vaya a fortalecer a雨n.[n][w][e]

[msg MND_COOP_RANK_MAX_00]
[s]Tengo un fuerte v胤nculo[n]con Chihaya.[n][w][e]

[msg MND_COOP_RANK_MAX_01]
[s]Tengo un v胤nculo especial[n]con Chihaya.[n][w][e]

[msg MSG_COOP_CHECK_NIGHT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Qu姻 vas a hacer?[n]夷Vas a pasar el rato con Chihaya?[n][w][e]

[msg MSG_COOP_CHECK_SHIDOU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Qu姻 vas a hacer?[n]夷Vas a pasar el rato con Chihaya?[n][w][e]

[sel SEL_COOP_CHECK top]
[s]Pasar el rato con ella[e]
[s]Comprobar v胤nculo con Chihaya[e]
[s]Rechazar[e]

[msg MSG_C10_YES_01_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10120 65535 0]Ay, estaba a punto de atender[n]a un cliente.[n]Qu姻date a mirar, por favor.[n][w][e]

[msg MSG_C10_YES_02_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10120 65535 0]Ahora estoy atendiendo[n]a un cliente.[n]Qu姻date a mirar, por favor.[n][w][e]

[msg MSG_C10_YES_03_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Muchas gracias...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 10096 65535 0]Ya estoy cerrando, un segund胤n.[n][w][e]

[msg MSG_C10_YES_04_00 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10117 65535 0]斡Genial![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]A ver, para hoy...[n][w][e]

[msg MSG_C10_YES_05_00 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10086 65535 0]Toma asiento, por favor.[n][w][e]

[msg MSG_C10_YES_06_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10096 65535 0]Vale, vayamos a otro sitio.[n][w][e]

[msg MSG_C10_YES_07_00 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10023 65535 0]斡S胤! 斡Toma asiento, por favor![n][w][e]

[msg MSG_C10_YES_08_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10023 65535 0]斡S胤! 斡Adelante, por favor![n][w][e]

[msg MSG_C10_YES_09_00 [Chihaya]]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10133 65535 0]斡D-da igual![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Parece la suerte nos sonreir茨[n]a lo grande si vamos[n]juntos a alg雨n lugar![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡V-vamos![n][w][e]

[msg MSG_C10_YES_09_01 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10023 65535 0]S胤, toma asiento, por favor.[n][w][e]

[msg MSG_MORGANA_COOP_ESCAPE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, yo voy a dar una vuelta.[n]Av胤same cuando quieras irte.[n][w][e]

[msg MSG_C10_YES_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10023 65535 0]Bien, all茨 vamooos.[n][w][e]

[msg MSG_C10_YES_10_00 [Chihaya]]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10086 65535 0]Muy bien, veamosqu姻 nos dicen las cartas...[n][w][e]

[msg MSG_C10_YES_10_01 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10086 65535 0]Como favor especial, te leer姻 el futuro.[n][w][e]

[msg MND_C10_SPOT_01_01]
[s]Quiz茨 deber胤a proponerle ir[n]a La ciudad de los libros.[n][w][e]

[sel SEL_C10_SPOT_01_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C10_SPOT_01_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]夷Jinbocho? All胤 hay muchas[n]librer胤as de segunda mano.[n][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 10052 65535 0]Queda algo lejos, pero 斡vamos all茨![n]No s姻 si seguir茨n abiertas...[n][w][e]

[msg MND_C10_SPOT_02_01]
[s]Quiz茨 deber胤a proponerle ir[n]a la Skytree.[n][w][e]

[sel SEL_C10_SPOT_02_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C10_SPOT_02_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]夷La Skytree? Mmm...[n]Suena bastante bien.[n][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 10052 65535 0]斡Vamos![n][w][e]

[msg MND_C10_SPOT_03_01]
[s]Chihaya quiere montar en la noria[n]de nuevo. Quiz茨 deber胤a invitarla.[n][w][e]

[sel SEL_C10_SPOT_03_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C10_SPOT_03_03 [Chihaya]]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10023 65535 0]斡S-s胤! 斡Vamos![n][w][e]

[msg MND_C10_SPOT_04_01]
[s]Quiz茨 deber胤a proponerle ir[n]al Parque Seaside.[n][w][e]

[sel SEL_C10_SPOT_04_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C10_SPOT_04_03 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10023 65535 0]Me encantar胤a ir.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Gu胤ame.[n][w][e]

[msg MND_C10_SPOT_05_01]
[s]夷Deber胤a proponerlevenir a mi habitaci吋n?[n][w][e]

[sel SEL_C10_SPOT_05_02 top]
[s]Invitarla[e]
[s]No invitarla[e]

[msg MSG_C10_SPOT_05_03 [Chihaya]]
[s][bup 0 113 7 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10040 65535 0]斡夷Eh?! 斡夷Qu姻 vayamos a su casa?![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]D-de acuerdo... Voy a prepararme.[n][w][e]

[msg MSG_C10_COOP_CANCEL_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10025 65535 0]Oh, 夷de veras?[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Ya puedes ir a [clr 2]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Ya puedes ir a [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Ya puedes ir a [clr 2]Akihabara[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Parque Inokashira[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el ramen[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Parque Seaside de Odaiba[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste este tipo[n]de parques para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Museo Ueno[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le gusten los museos[n]de arte para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el monjayaki[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]calle Takenoko de Harajuku[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente a[n]la que le guste la calle Takenoko[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Chinatown de Motomachi[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Destinyland de Maihama[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]Puedes invitar a gente a la que le[n]guste la Skytree o la calle[n]Nakamise para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Planetario de Ikebukuro[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Santuario Meiji[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir por tu cuenta[n]para venerarlo.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Dome Town de Suidobashi[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Hotel Wilton de Shibuya[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]restaurante de sushi de Ginza[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el sushi caro[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Tienes informaci吋n sobre un nuevo[n]punto de encuentro: [clr 2]La ciudad[n]de los libros de Jinbocho[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el lugar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir por tu cuenta[n]a comprar.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Estanque Ichigaya[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste pescar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir[n]por tu cuenta para ver[n]qu姻 tal se te da pescar.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Acuario de Shinagawa[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el acuario[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]zona comercial de Nakano[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste ese lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_C10_UNSEI_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Que te lea la suerte[n]te costar茨 [clr 2][var 0] yenes[clr 27].[n]夷Te parece bien?[n][w][e]

[sel SEL_C10_UNSEI_00_01 top]
[s]Conocer el futuro[e]
[s]No conocer el futuro[e]

[msg MSG_C10_UNSEI_10_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Oye, no tienes tanto dinero.[n]Vas a tener que pasar[n]de esto de momento.[n][w][e]

[msg MSG_C10_UNSEI_10_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10038 65535 0]夷Eh? 夷No quieres[n]que te lea el futuro?[n][w][e]

[msg MSG_C10_UNSEI_20_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10090 65535 0]Vale, 夷est茨s listo?[n][w][e]

[msg MSG_C10_UNSEI_20_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Mm... Mmmm...[n][w][e]

[msg MSG_C10_UNSEI_20_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Ya te he le胤do la suerte. Repetir[n]el proceso no cambiar茨 nada.[n][w][e]
[s][f 4 10 65535 0 0]Las cartas me dicen que...[n][w][e]

[msg MSG_C10_UNSEI_30_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Tu coraz吋n est茨 experimentando un[n]cambio, pero la taza...[n][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0]S胤, es buena 姻poca para que[n]crees algo nuevo. Los resultados[n]ser茨n mejores que de costumbre.[n][w][e]

[msg SYS_C10_UNSEI_30_02]
[s]Hoy obtendr茨s una[n]bonificaci吋n de puntos[n]de explosi吋n al fusionar Personas.[n][w][e]

[msg MSG_C10_UNSEI_30_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Obtendr茨s mejores resultados que de[n]costumbre al crear algo nuevo.[n][w][e]
[s][f 4 10 65535 0 0]Que no se te olvide, 夷vale?[n][w][e]

[msg MSG_C10_UNSEI_31_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Un cambio en tu coraz吋n,[n]pero ya que est茨 el pentagrama...[n][w][e]
[s][f 4 10 65535 0 0]Ah, ya veo. Vale, ahora entiendo.[n][w][e]
[s][f 4 10 65535 0 0]Parece ser que cuando crees algo[n]nuevo, es m茨s probable que ocurra[n]un accidente.[n][w][e]

[msg SYS_C10_UNSEI_31_02]
[s]Hoy es m茨s probable que[n]ocurra un accidente[n]al fusionar Personas.[n][w][e]

[msg MSG_C10_UNSEI_31_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Parece ser que cuando crees algo[n]nuevo, es m茨s probable que ocurra[n]un accidente.[n][w][e]
[s][f 4 10 65535 0 0]Que no se te olvide, 夷vale?[n][w][e]

[msg MSG_C10_UNSEI_32_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]La espada est茨 en el centro y el[n]coraz吋n ha cambiado[n]a un tono m茨s oscuro...[n][w][e]
[s][f 4 10 65535 0 0]S胤, es una 姻poca de evoluci吋n.[n][w][e]
[s][f 4 10 65535 0 0]Cuando crees algo nuevo, una calidad[n]ya existente se ver茨 mejorada.[n][w][e]

[msg SYS_C10_UNSEI_32_02]
[s]Hoy puede evolucionar[n]una habilidad al fusionar Personas.[n][w][e]

[msg MSG_C10_UNSEI_32_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Cuando crees algo nuevo,[n]una calidad ya existente se[n]ver茨 mejorada.[n][w][e]
[s][f 4 10 65535 0 0]夷Te acordar茨s?[n][w][e]

[msg MSG_C10_UNSEI_33_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Parece que tu coraz吋n experimenta[n]un gran cambio, pero los bastos[n]tambi姻n ejercen una gran influencia.[n][w][e]
[s][f 4 10 65535 0 0]Entiendo.[n]Ha llegado el momento del cambio.[n][w][e]
[s][f 4 10 65535 0 0]Cuando crees algo nuevo,[n]se producir茨 un cambio.[n][w][e]

[msg SYS_C10_UNSEI_33_02]
[s]Hoy puede cambiar[n]una habilidad al fusionar Personas.[n][w][e]

[msg MSG_C10_UNSEI_33_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Cuando crees algo nuevo,[n]se producir茨 un cambio.[n][w][e]
[s][f 4 10 65535 0 0]Recu姻rdalo, 夷vale?[n][w][e]

[msg MSG_C10_UNSEI_40_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Eso es todo por hoy.[n][w][e]

[msg MSG_C10_UNSEI_40_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Tu suerte podr胤a cambiar ma隠ana.[n][w][e]
[s][f 4 10 65535 0 0]Esto es lo que hoy te aguarda[n]el destino. Conf胤a en 姻l.[n][w][e]

[msg MSG_C10_KAIUN_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Si quieres que te lea la suerte,[n]te voy a tener que pedir[n][clr 2][var 0] yenes[clr 27].[n][w][e]

[sel MSG_C10_KAIUN_00_01 top]
[s]Conocer el futuro[e]
[s]No conocer el futuro[e]

[msg MSG_C10_KAIUN_10_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Oye, no tienes tanto dinero.[n]Vas a tener que pasar[n]de esto de momento.[n][w][e]

[msg MSG_C10_KAIUN_10_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10038 65535 0]夷No quieres que te lea futuro?[n][w][e]

[msg MSG_C10_KAIUN_20_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10119 65535 0]Muy bien, 夷qu姻 aspecto[n]de tu vida querr胤as mejorar?[n][w][e]

[sel MSG_C10_KAIUN_00_02 top]
[s]Quiero aumentar mi Conocimiento.[e]
[s]Quiero aumentar mi Coraje.[e]
[s]Quiero aumentar mi Destreza.[e]
[s]Quiero aumentar mi Gentileza.[e]
[s]Quiero aumentar mi Encanto.[e]

[msg MSG_C10_KAIUN_20_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mm... Mmmm... Mmmmmmm...[n][w][e]

[msg MSG_C10_KAIUN_20_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]夷No te he le胤do ya la suerte? Nada[n]cambiar茨 por hacerlo otra vez.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Las cartas me dicen que...[n][w][e]

[msg MSG_C10_KAIUN_30_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]La Sacerdotisa...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Veo que te vas a beneficiar mucho[n]de ciertos actos con las que[n]aumentar茨s tu Conocimiento.[n][w][e]

[msg SYS_C10_KAIUN_30_02]
[s]Hoy es m茨s probable[n]que aumente tu Conocimiento.[n][w][e]

[msg MSG_C10_KAIUN_30_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Veo que te vas a beneficiar mucho[n]de ciertos actos con las que[n]aumentar茨s tu Conocimiento.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Que no se te olvide, 夷vale?[n][w][e]

[msg MSG_C10_KAIUN_31_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]El Loco...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Veo que te vas a beneficiar mucho[n]de ciertos actos con los que[n]aumentar茨s tu Coraje.[n][w][e]

[msg SYS_C10_KAIUN_31_02]
[s]Hoy es m茨s probable[n]que aumente tu Coraje.[n][w][e]

[msg MSG_C10_KAIUN_31_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Veo que te vas a beneficiar mucho[n]de ciertos actos con los que[n]aumentar茨s tu Coraje.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Que no se te olvide, 夷vale?[n][w][e]

[msg MSG_C10_KAIUN_32_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]La Templanza...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Veo que te vas a beneficiar mucho[n]de ciertos actos con los que[n]aumentar茨s tu Destreza.[n][w][e]

[msg SYS_C10_KAIUN_32_02]
[s]Hoy es m茨s probable[n]que aumente tu Destreza.[n][w][e]

[msg MSG_C10_KAIUN_32_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Veo que te vas a beneficiar mucho[n]de ciertos actos con los que[n]aumentar茨s tu Destreza.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Que no se te olvide, 夷vale?[n][w][e]

[msg MSG_C10_KAIUN_33_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]El Hierofante...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Veo que te vas a beneficiar mucho[n]de ciertos actos con los que[n]aumentar茨s tu Gentileza.[n][w][e]

[msg SYS_C10_KAIUN_33_02]
[s]Hoy es m茨s probable[n]que aumente tu Gentileza.[n][w][e]

[msg MSG_C10_KAIUN_33_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Veo que te vas a beneficiar mucho[n]de ciertos actos con los que[n]aumentar茨s tu Gentileza.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Que no se te olvide, 夷vale?[n][w][e]

[msg MSG_C10_KAIUN_34_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]El Diablo...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Veo que te vas a beneficiar mucho[n]de ciertos actos con los que[n]aumentar茨s tu Encanto.[n][w][e]

[msg SYS_C10_KAIUN_34_02]
[s]Hoy es m茨s probable[n]que aumente tu Encanto.[n][w][e]

[msg MSG_C10_KAIUN_34_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Veo que te vas a beneficiar mucho[n]de ciertos actos con los que[n]aumentar茨s tu Encanto.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Que no se te olvide, 夷vale?[n][w][e]

[msg MSG_C10_KAIUN_40_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Eso es todo lo que puedo[n]decirte hoy de cara al futuro.[n][w][e]

[msg MSG_C10_KAIUN_40_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Puede que ma隠ana salga otra cosa.[n][w][e]

[msg MSG_C10_UNMEI_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Hay alguien que desea[n]conocer su futuro contigo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ahora..., conc姻ntrate en esa persona.[n][w][e]

[msg MND_C10_UNMEI_00_01]
[s]A ver si se me ocurre alguien...[n][w][e]

[msg MSG_C10_JINSEI_00_02 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Tu aura es muy buena.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Has establecido buenos contactos.[n]斡No tienes nada de que preocuparte![n][w][e]

[msg TITLE_C10_UNMEI_MENU]
[s]Lectura del destino[n][e]

[sel SEL_C10_UNMEI_SEL_00 top]
[s]Ryuji[ref 0 11][e]
[s]Ann[ref 1 10][e]
[s]Yusuke[ref 2 8][e]
[s]Makoto[ref 3 6][e]
[s]Futaba[ref 4 13][e]
[s]Haru[ref 5 7][e]
[s]Akechi[ref 6 12][e]
[s]Sojiro[ref 7 9][e]
[s]Chihaya[ref 8 14][e]
[s]Iwai[ref 9 15][e]
[s]Takemi[ref 10 16][e]
[s]Kawakami[ref 11 17][e]
[s]Ohya[ref 12 18][e]
[s]Shinya[ref 13 19][e]
[s]Hifumi[ref 14 20][e]
[s]Mishima[ref 15 21][e]
[s]Yoshida[ref 16 22][e]
[s] [f 4 31 10 0][ref 17 23] [e]
[s]Maruki[ref 18 24][e]
[s]Igor[ref 19 25][e]
[s]Morgana[ref 20 26][e]
[s]Gemelas de la Habitaci吋n Terciopelo[ref 21 27][e]

[msg MSG_C10_UNMEI_10_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Parece que ya tienes[n]a alguien en mente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, que te lea el futuro te costar茨[n][clr 2][var 0] yenes[clr 27].[n][w][e]

[sel SEL_C10_UNMEI_10_01 top]
[s]Conocer el futuro[e]
[s]No conocer el futuro[e]

[msg MSG_C10_UNMEI_10_02 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Oye, no tienes tanto dinero.[n]Vas a tener que pasar[n]de esto de momento.[n][w][e]

[msg MSG_C10_UNMEI_10_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10038 65535 0]夷No quieres que te lea futuro?[n][w][e]

[msg MSG_C10_UNMEI_20_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10090 65535 0]Vale. Vaaamos a veeer...[n][w][e]

[msg MSG_C10_UNMEI_20_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mm... Mmmm... Mmmmmmm...[n][w][e]

[msg MSG_C10_UNMEI_20_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Gracias por esperar. Creo que[n]ahora puedo leer el coraz吋n[n]de la otra persona.[n][w][e]

[msg SYS_C10_UNMEI_30_02]
[s]Puedes ver una parte[n]de las habilidades de Confidente[n]en el men雨 Campamento.[n][w][e]

[msg MSG_C10_UNMEI_20_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Ya conoces tu destino. No se te[n]pueden echar las cartas sobre el[n]mismo tema una y otra vez.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Muy bien. Nos vemos pronto.[n][w][e]

[msg MSG_C10_UNMEI_20_04 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Est茨s pensando en la misma persona[n]a la que le le胤 el destino, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Solo puedo leer el destino una vez[n]por persona. Piensa en otra.[n][w][e]

[msg MSG_C10_UNMEI_20_05 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Creo que ya conoces muy bien[n]el coraz吋n de esta persona.[n]No vas a descubrir nada nuevo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero puede leerte el futuro[n]con otra persona.[n][w][e]

[msg MSG_C10_AISHO_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10]Que te lea el futuro te costar茨[n][clr 2][var 0] yenes[clr 27]. 夷Te parece bien?[n][w][e]

[sel SEL_C10_AISHO_00_01 top]
[s]Conocer el futuro[e]
[s]No conocer el futuro[e]

[msg MSG_C10_AISHO_10_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Oye, no tienes tanto dinero.[n]Vas a tener que pasar[n]de esto de momento.[n][w][e]

[msg MSG_C10_AISHO_10_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10038 65535 0]夷No quieres que te lea futuro?[n][w][e]

[msg MSG_C10_AISHO_20_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Piensa en alguien con quien[n]quieras fortalecer tu v胤nculo.[n][w][e]

[msg TITLE_C10_AISHO_MENU_00]
[s]Lectura de afinidad[n][e]

[sel SEL_C10_AISHO_SEL_00 top]
[s]Ryuji[ref 0 11][e]
[s]Ann[ref 1 10][e]
[s]Yusuke[ref 2 8][e]
[s]Makoto[ref 3 6][e]
[s]Futaba[ref 4 13][e]
[s]Haru[ref 5 7][e]
[s]Akechi[ref 6 12][e]
[s]Sojiro[ref 7 9][e]
[s]Chihaya[ref 8 14][e]
[s]Iwai[ref 9 15][e]
[s]Takemi[ref 10 16][e]
[s]Kawakami[ref 11 17][e]
[s]Ohya[ref 12 18][e]
[s]Shinya[ref 13 19][e]
[s]Hifumi[ref 14 20][e]
[s]Mishima[ref 15 21][e]
[s]Yoshida[ref 16 22][e]
[s] [f 4 31 10 0][ref 17 23] [e]
[s]Maruki[ref 18 24][e]

[msg MSG_C10_AISHO_20_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10090 65535 0]Vale. Vaaamos a veeer...[n][w][e]

[msg MSG_C10_AISHO_20_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mm... Mmmm... Mmmmmmm...[n][w][e]

[msg MSG_C10_AISHO_20_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]夷La compatibilidad no te la he[n]le胤do ya? Es tab雨 pedirles[n]lo mismo dos veces a las cartas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Por favor, ven a verme[n]en otro momento.[n][w][e]

[msg MSG_C10_AISHO_30_01 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Tus sentimientos deben de haberle[n]llegado a la otra persona.[n][w][e]

[msg MSG_C10_AISHO_40_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mm, seguro que ahora pod姻is[n]fortalecer vuestra amistad a雨n m茨s.[n][w][e]

[msg MSG_C10_AISHO_50_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Bueno, eso es todo por hoy.[n]Espero haberte ayudado.[n][w][e]

[msg MSG_C10_KINUN_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Ver qu姻 te deparan las finanzas[n]te costar茨 [clr 2][var 0] yenes[clr 27].[n]夷Te parece bien?[n][w][e]

[sel MSG_C10_KINUN_00_01 top]
[s]Conocer el futuro[e]
[s]No conocer el futuro[e]

[msg MSG_C10_KINUN_10_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Oye, no tienes tanto dinero.[n]Vas a tener que pasar[n]de esto de momento.[n][w][e]

[msg MSG_C10_KINUN_10_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10038 65535 0]夷No quieres que te eche las cartas?[n][w][e]

[msg MSG_C10_KINUN_20_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10090 65535 0]Muy bien, veamos[n]qu姻 te deparan las finanzas.[n][w][e]

[msg MSG_C10_KINUN_20_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mm... Mmmm... Mmmmmmm...[n][w][e]

[msg MSG_C10_KINUN_20_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Pero si ya te ech姻 las cartas, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Las cartas me dicen que...[n][w][e]

[msg MSG_C10_KINUN_30_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mmm... en el futuro...[n]veo... 夷dinero?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Veo que te embolsar茨s[n]m茨s dinero que de costumbre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Con suerte, pronto recibir茨s[n]un pago.[n][w][e]

[msg SYS_C10_KINUN_30_02]
[s]Hoy obtendr茨s m茨s dinero si ganas[n]un combate con un ataque combinado.[n][w][e]

[msg MSG_C10_KINUN_30_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Si te dedicas a combatir,[n]te embolsar茨s m茨s dinero[n]que de costumbre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Recu姻rdalo, 夷vale?[n][w][e]

[msg MSG_C10_KINUN_40_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Eso es todo por hoy en cuanto al futuro.[n][w][e]

[msg MSG_C10_KINUN_40_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Nada m茨s que a隠adir por hoy[n]en cuanto al futuro.[n][w][e]

[msg MSG_C10_KINUN_40_10 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Lo siento. Solo puedo echarte[n]las cartas a la luz del sol.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Necesito el poder del Sol[n]para canalizar la luz de Apolo.[n]P茨sate durante el d胤a.[n][w][e]

[msg MSG_C10_ALERT_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Si quieres que te lea la suerte,[n]te voy a tener que pedir[n][clr 2][var 0] yenes[clr 27].[n][w][e]

[sel MSG_C10_ALERT_00_01 top]
[s]Conocer el futuro[e]
[s]No conocer el futuro[e]

[msg MSG_C10_ALERT_10_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Oye, no tienes tanto dinero.[n]Vas a tener que pasar[n]de esto de momento.[n][w][e]

[msg MSG_C10_ALERT_10_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10038 65535 0]夷No quieres que te eche las cartas?[n][w][e]

[msg MSG_C10_ALERT_20_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10090 65535 0]Vale, empecemos.[n][w][e]

[msg MSG_C10_ALERT_20_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mm... Mmmm... Mmmmmmm...[n][w][e]

[msg MSG_C10_ALERT_20_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Ya te he le胤do la suerte.[n]夷Acaso lo has olvidado?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]El futuro te depara...[n][w][e]

[msg MSG_C10_ALERT_30_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mmm... 夷Una carta de la Fuerza[n]y una luz roja?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Puede que te sientas[n]algo inquieto hoy.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero podr胤a ser una se隠al[n]para que te atrevas[n]a aceptar un desaf胤o.[n][w][e]

[msg SYS_C10_ALERT_30_02]
[s]Hoy sonar茨 la alarma de fusi吋n[n]una vez en la Habitaci吋n Terciopelo[n]y podr茨n sonar m茨s alarmas.[n][w][e]

[msg MSG_C10_ALERT_30_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Cuando peleas, puedes[n]experimentar un crecimiento[n]a雨n mayor de lo normal.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Recu姻rdalo, 夷vale?[n][w][e]

[msg MSG_C10_ALERT_40_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Esa es la lectura celestial de hoy.[n][w][e]

[msg MSG_C10_ALERT_40_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Ese es el resultado[n]de la lectura celestial de hoy.[n][w][e]

[msg MSG_C10_ALERT_40_10 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Lo siento. Las lecturas celestiales[n]especiales solo pueden hacerse[n]de d胤a.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Necesito el poder del Sol[n]para canalizar la luz de Apolo.[n]P茨sate durante el d胤a.[n][w][e]

[msg MSG_C10_ALERT_40_11 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mmm. En tu estado actual, puede[n]que esa lectura no sirva de nada.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Intenta relajarte por hoy. Siempre[n]podemos intentarlo m茨s tarde.[n][w][e]

[msg MSG_C10_SECRETS_00_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]La lectura especial de v胤nculo[n]te costar茨 [clr 2][var 0] yenes[clr 27].[n]夷Te parece bien?[n][w][e]

[sel MSG_C10_SECRETS_00_01 top]
[s]Conocer el futuro[e]
[s]No conocer el futuro[e]

[msg MSG_C10_SECRETS_10_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]夷No tienes dinero? Dejemos[n]la lectura para otro momento.[n][w][e]

[msg MSG_C10_SECRETS_10_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10038 65535 0]夷No quieres que te eche las cartas?[n][w][e]

[msg MSG_C10_SECRETS_20_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 10090 65535 0]Veamos, deja que te lea[n]la afinidad...[n][w][e]

[msg MSG_C10_SECRETS_20_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Mm... Mmmm... Mmmmmmm...[n][w][e]

[msg MSG_C10_SECRETS_20_02 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Hoy ya te he hecho la lectura[n]especial de v胤nculo, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Las cartas me dicen que...[n][w][e]

[msg MSG_C10_SECRETS_30_01 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]斡Cielos! 斡La carta del Sol![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Hoy es un d胤a especial![n]斡Podr茨s conocer a fondo[n]el coraz吋n de otra persona![n][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Te recomiendo encarecidamente[n]que te tomes el d胤a libre[n]para fortalecer tus relaciones.[n][w][e]

[msg SYS_C10_SECRETS_30_02]
[s]Hoy, las opciones de di茨logo que[n]m茨s fortalezcan la relaci吋n con tus[n]Confidentes aparecer茨n se隠aladas.[n][w][e]

[msg MSG_C10_SECRETS_30_03 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]斡Hoy es un d胤a especial![n]斡Podr茨s conocer a fondo[n]el coraz吋n de otra persona![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Recu姻rdalo, 夷vale?[n][w][e]

[msg MSG_C10_SECRETS_40_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 23 1 210 14 10 13 10][vp 8 2 1 0 65535 0]Aqu胤 concluye la lectura[n]especial de v胤nculo.[n]Disfruta de lo que queda de d胤a.[n][w][e]

[msg MSG_C10_BYEGREET_00_00 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]Has venido.[n][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Como te vas ma隠ana, me voy a quedar[n]bastante sola aqu胤, pero...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Trabajar姻 duro para seguir mejorando[n]mientras espero a que vuelvas.[n][w][e]

[sel SEL_C10_BYEGREET_00_01 top]
[s]Admiro tu positividad.[e]
[s]Me pasar姻 otro d胤a.[e]
[s]Yo tambi姻n seguir姻 creciendo.[e]

[msg MSG_C10_BYEGREET_00_02 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Bueno, eso me lo has ense隠ado t雨.[n][w][e]

[msg MSG_C10_BYEGREET_00_03 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Qu姻 bien, qu姻 alegr胤a.[n]Me muero de ganas.[n][w][e]

[msg MSG_C10_BYEGREET_00_04 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Ah, 夷s胤? En tal caso,[n]me esforzar姻 de lo lindo.[n][w][e]

[msg MSG_C10_BYEGREET_00_05 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]Mis clientes me han estado[n]animando mucho 雨ltimamente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]Cuando pensaba que hab胤a[n]tocado fondo, me di cuenta de que[n]eso era fundamental a la larga.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]As胤 que... quiz茨 la raz吋n por la que[n]dej姻 mi pueblo era conocerte.[n][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Esta carta revela tu futuro. Por favor,[n]gu茨rdala como amuleto de la suerte.[n][w][e]

[msg MSG_C10_BYEGREET_00_06 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 11 0 0]Por la posici吋n de la Fortuna,[n]la felicidad est茨 en camino.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Para ser sincera conmigo misma,[n]quiero estar contigo toda la vida,[n]pero a雨n eres un estudiante.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Sin embargo, cuando te grad雨es...[n][w][e]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 450][vp 8 0 1 14 65535 0]Yo ser姻 quien ocupe tu futuro...[n]Es broma.[n][w][e]

[msg MSG_C10_BYEGREET_00_07 [Chihaya]]
[s][bup 0 113 6 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 450][vp 8 0 1 15 65535 0]Yo ser姻 quien ocupe tu futuro...[n]Es broma.[n][w][e]

[msg MSG_C10_BYEGREET_01_00 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 16 65535 0]斡Hala![n][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]Justo lo que dec胤an las cartas...[n]Has venido a verme.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 18 65535 0]Tal y como est茨s ahora,[n]deber胤a irte bien.[n][w][e]

[sel SEL_C10_BYEGREET_01_01 top]
[s]Me alegra o胤rlo.[e]
[s]夷Me has le胤do el futuro?[e]
[s]A ti tambi姻n te ir茨 bien.[e]

[msg MSG_C10_BYEGREET_01_02 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 19 65535 0]Rel茨jate cuando llegues[n]a casa para descansar de todo[n]lo que has trabajado aqu胤.[n][w][e]

[msg MSG_C10_BYEGREET_01_03 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 20 65535 0]S胤, estaba preocupada por ti...[n][w][e]

[msg MSG_C10_BYEGREET_01_04 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 21 65535 0]Ja, ja, ja. Bueno,[n]si t雨 lo dices, ser茨 verdad.[n][w][e]

[msg MSG_C10_BYEGREET_01_05 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 22 65535 0]Mis clientes me han estado[n]animando mucho 雨ltimamente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 23 65535 0]Es bastante raro, porque se supone[n]que yo deber胤a animarlos a ellos,[n]pero noto que estoy mejorando.[n][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]Esta carta revela tu futuro. Por favor,[n]gu茨rdala como amuleto de la suerte.[n][w][e]

[msg MSG_C10_BYEGREET_01_06 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 25 65535 0]Por la posici吋n de la Fortuna,[n]la felicidad est茨 en camino.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 26 65535 0]As胤 que, por favor,[n]vive la vida como t雨 desees.[n][w][e]
[s][f 4 10 65535 0 600][vp 8 0 1 27 65535 0]Estoy orgullosa de tener un compa隠ero como t雨...[n]Me alegro de haber podido dec胤rtelo.[n][w][e]

[msg MSG_C10_BYEGREET_01_07 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 600][vp 8 0 1 28 65535 0]Estoy orgullosa de tener un compa隠ero como t雨...[n]Me alegro de haber podido dec胤rtelo.[n][w][e]

[msg MSG_C10_BYEGREET_00_00_5 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]Has venido.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 30 65535 0]Como te vas ma隠ana, me voy a quedar[n]bastante sola aqu胤, pero...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 31 65535 0]Trabajar姻 duro para seguir mejorando[n]mientras espero a que vuelvas.[n][w][e]

[sel SEL_C10_BYEGREET_00_01_5 top]
[s]Admiro tu positividad.[e]
[s]Me pasar姻 otro d胤a.[e]
[s]Yo tambi姻n seguir姻 creciendo.[e]

[msg MSG_C10_BYEGREET_00_02_5 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]Bueno, eso me lo has ense隠ado t雨.[n][w][e]

[msg MSG_C10_BYEGREET_00_03_5 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 33 65535 0]Qu姻 bien, qu姻 alegr胤a.[n]Me muero de ganas.[n][w][e]

[msg MSG_C10_BYEGREET_00_04_5 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]Ah, 夷s胤? En tal caso,[n]me esforzar姻 de lo lindo.[n][w][e]

[msg MSG_C10_BYEGREET_00_05_5 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 35 65535 0]Mis clientes me han estado[n]animando mucho 雨ltimamente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 36 65535 0]Lo que de primeras puede parecer[n]un obst茨culo puede llegar a ser[n]un primer paso relevante y significativo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 37 65535 0]Si no me hubiera ido de mi ciudad[n]y acabado aqu胤, no habr胤a usado[n]mis poderes para ayudar a otros.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 38 65535 0]Y lo m茨s importante, no te habr胤a[n]conocido, [f 4 1].[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 39 65535 0]Toma, esta carta representa tu futuro.[n]Gu茨rdala como amuleto de la suerte.[n][w][e]

[msg MSG_C10_BYEGREET_00_06_5 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 40 65535 0]La posici吋n vertical de la Fortuna significa[n]felicidad, pero cuando est茨 invertida[n]es un mal augurio.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 41 65535 0]Pero parece que tienes[n]el poder de llevar la felicidad[n]a cualquiera.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 42 65535 0]Ahora lo entiendo. No hay que aferrarse[n]al destino. Podemos cambiarlo[n]nosotros mismos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 43 65535 0]Mira, no voy a esperar hasta que[n]las ranas cr胤en pelo. Si tardas,[n]yo ir姻 a por ti, 斡rec吋rcholis![n][w][e]

[msg MSG_C10_BYEGREET_00_07_5 [Chihaya]]
[s][bup 0 113 6 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 450][vp 8 0 1 45 65535 0]Mira, no voy a esperar hasta que[n]las ranas cr胤en pelo. Si tardas,[n]yo ir姻 a por ti, 斡rec吋rcholis![n][w][e]

[msg MSG_C10_BYEGREET_01_00_5 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 47 65535 0]斡Hala![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 48 65535 0]Justo lo que dec胤an las cartas...[n]Has venido a verme.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 49 65535 0]Tal y como est茨s ahora,[n]deber胤a irte bien.[n][w][e]

[sel SEL_C10_BYEGREET_01_01_5 top]
[s]Me alegra o胤rlo.[e]
[s]夷Me has le胤do el futuro?[e]
[s]A ti tambi姻n te ir茨 bien.[e]

[msg MSG_C10_BYEGREET_01_02_5 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 50 65535 0]Por favor, rel茨jate cuando llegues[n]a casa para descansar de todo[n]lo que has trabajado aqu胤.[n][w][e]

[msg MSG_C10_BYEGREET_01_03_5 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 51 65535 0]S胤, estaba preocupada por ti...[n][w][e]

[msg MSG_C10_BYEGREET_01_04_5 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 52 65535 0]Ja, ja, ja. Bueno,[n]si t雨 lo dices, ser茨 verdad.[n][w][e]

[msg MSG_C10_BYEGREET_01_05_5 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 53 65535 0]Mis clientes me han estado[n]animando mucho 雨ltimamente.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 54 65535 0]Aunque se supone que yo deber胤a[n]animarlos a ellos. Es extra隠o, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 55 65535 0]Pero quiz茨s esa sea la forma[n]verdadera de la adivinaci吋n.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 56 65535 0]Animarse mutuamente para ser feliz[n]en un mundo lleno de complicados[n]y dolorosos destinos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 57 65535 0]Es el tipo de consuelo que siempre[n]espero ofrecer en mis lecturas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 58 65535 0]Toma, esta carta representa tu futuro.[n]Gu茨rdala como amuleto de la suerte.[n][w][e]

[msg MSG_C10_BYEGREET_01_06_5 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 0][vp 8 0 1 59 65535 0]La posici吋n vertical de la Fortuna significa[n]felicidad, pero cuando est茨 invertida[n]es un mal augurio.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 60 65535 0]Pero s姻 que continuar茨s con la misma[n]convicci吋n de siempre.[n]Nunca le has temido al futuro.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 61 65535 0]As胤 es como llevas[n]la felicidad a cualquier destino.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 62 65535 0]Volveremos a vernos. Aunque[n]no es ning雨n presagio,[n]solo un deseo personal.[n][w][e]

[msg MSG_C10_BYEGREET_01_07_5 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 23 1 210 14 10 13 10][f 4 10 65535 0 600][vp 8 0 1 63 65535 0]Volveremos a vernos. Aunque[n]no es ning雨n presagio,[n]solo un deseo personal.[n][w][e]

