[msg dummy_mes]
[s]...[n][w][e]

[msg SAFE_MES_RYUJI_01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_RYUJI_02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_RYUJI_03 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 2 1 7103 65535 0]斡Chachi, una novata![n]斡Ense隠姻mosle c吋mo nos lo montamos![n][w][e]

[msg SAFE_MES_RYUJI_04 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 2 1 7020 65535 0]斡Hala! 斡Violet es buen胤sima![n]斡Tendr姻 que esforzarme[n]para no quedarme atr茨s![n][w][e]

[msg SAFE_MES_RYUJI_05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 2 1 7115 65535 0]斡Ese almac姻n era enorme![n]夷Qu姻 guardar茨?[n][w][e]

[msg SAFE_MES_RYUJI_06 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 2 1 7192 65535 0]Esta zona no se parece[n]a la entrada, 夷no?[n]夷Crees que seguir茨 cambiando?[n][w][e]

[msg SAFE_MES_RYUJI_07 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][vp 8 2 1 7021 65535 0]No sabemos mucho[n]sobre el pasado de Maruki,[n]aunque tiene l吋gica.  [n][w][e]

[msg SAFE_MES_RYUJI_08 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 2 1 7158 65535 0]Creo que ya s姻 la respuesta[n]para esa puerta... 斡Vamos all茨![n][w][e]

[msg SAFE_MES_RYUJI_09 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 2 1 7038 65535 0]Hac胤a un huevo que no ve胤a un VHS.[n]Menudo mal rollo[n]daba esa sala, 夷eh?[n][w][e]

[msg SAFE_MES_RYUJI_10 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 2 1 7040 65535 0]夷Su Palacio es un laboratorio?[n]Joder, como para adivinarlo.[n][w][e]

[msg SAFE_MES_RYUJI_11 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]Vaya pregunta m茨s rara. Yo...[n]Os dejo lo de pensar[n]a vosotros, los expertos.[n][w][e]

[msg SAFE_MES_RYUJI_12 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][vp 8 2 1 7022 65535 0]夷Qu姻 les dir茨 ese chisme[n]que tienen en la cabeza?[n]Bueno, ni que me interesara.[n][w][e]

[msg SAFE_MES_RYUJI_13 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 2 1 7155 65535 0]斡Vamos a descansar un poco[n]y a encontrar esa cinta! [n][w][e]

[msg SAFE_MES_RYUJI_14 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][vp 8 2 1 7028 65535 0]夷Vamos a tener que ver otro v胤deo?[n][w][e]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0]Vaaale, vamos all茨.[n][w][e]

[msg SAFE_MES_RYUJI_15 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][vp 8 2 1 7191 65535 0]A veces, uno quiere huir[n]de sus problemas. Tengo que admitir[n]que a m胤 me ha pasado.[n][w][e]

[msg SAFE_MES_RYUJI_16 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 2 1 7176 65535 0]夷Los tratan para que puedan ir[n]al cielo?[n][w][e]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0]Solo cambia su cognici吋n, 夷no?[n]夷Y a ninguno le molesta?[n][w][e]

[msg SAFE_MES_RYUJI_17 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 2 1 7045 65535 0]Ya tenemos la ruta. Hagamos otra[n]cosa hasta el d胤a del asalto.[n][w][e]

[msg SAFE_MES_MORGANA_01 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_MORGANA_02 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_MORGANA_03 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]No cre胤a que volver胤amos nunca[n]al Metaverso.[n][w][e]

[msg SAFE_MES_MORGANA_04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0]Violet acaba de despertar su poder...[n]No le exijas mucho, Joker.[n][w][e]

[msg SAFE_MES_MORGANA_05 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Estamos avanzando bastante...[n]Solo un poco m茨s.[n][w][e]

[msg SAFE_MES_MORGANA_06 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]Ahora que nos hemos quitado[n]de en medio esos cables, por fin[n]podemos seguir investigando.[n][w][e]

[msg SAFE_MES_MORGANA_07 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Una puerta que no se abre si no[n]conocemos el pasado de Maruki.[n][w][e]
[s][f 4 10 65535 0 0]Pues s胤, es un co隠azo,[n]pero este es su Palacio.[n]Alguna pista encontraremos.[n][w][e]

[msg SAFE_MES_MORGANA_08 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1161 65535 0]Entonces, lo que perdi吋 Maruki fue...[n][w][e]
[s][f 4 10 65535 0 0]Vayamos a esa puerta[n]cuando est姻s listo.[n][w][e]

[msg SAFE_MES_MORGANA_09 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]Qu姻 pregunta m茨s rara... Bueno,[n]al menos la puerta se ha abierto.[n][w][e]

[msg SAFE_MES_MORGANA_10 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1022 65535 0]Conque el Palacio es[n]un laboratorio, 夷eh? Lo sab胤a...[n][w][e]

[msg SAFE_MES_MORGANA_11 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]Maruki asegura que est茨 ayudando[n]a esta gente, pero lo 雨nico[n]que hace es engatusarla.[n][w][e]

[msg SAFE_MES_MORGANA_12 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0]La gente se marea[n]despu姻s del tratamiento.[n]Conmigo no cont姻is.[n][w][e]

[msg SAFE_MES_MORGANA_13 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]No hay cinta, 夷eh? 斡Parece que[n]tendremos que robarla como[n]aut姻nticos Ladrones Fantasma! [n][w][e]

[msg SAFE_MES_MORGANA_14 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Tenemos la cinta.[n]斡Ve茨mosla cuanto antes![n][w][e]

[msg SAFE_MES_MORGANA_15 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1051 65535 0]Maruki est茨 un poco m茨s adelante.[n]斡Vamos, Joker![n][w][e]

[msg SAFE_MES_MORGANA_16 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0]La gente est茨 volando por todas[n]partes... Aqu胤 todo es posible.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Raz吋n de m茨s para estar alerta.[n][w][e]

[msg SAFE_MES_MORGANA_17 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1181 65535 0]Excelente, tenemos la ruta.[n]Ahora, prepar姻monos para el asalto.[n][w][e]

[msg SAFE_MES_ANN_01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_ANN_02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_ANN_03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 2 1 6021 65535 0]Este Palacio parec胤a muy grande[n]desde fuera... Nos queda[n]un largo camino.[n][w][e]

[msg SAFE_MES_ANN_04 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][vp 8 2 1 6019 65535 0]斡Violet parece lista[n]para la acci吋n! 斡En marcha, Joker![n][w][e]

[msg SAFE_MES_ANN_05 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 2 1 6166 65535 0]Esto parece totalmente distinto[n]al almac姻n. 夷Volver茨[n]a cambiar otra vez?[n][w][e]

[msg SAFE_MES_ANN_06 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 2 1 6025 65535 0]Vincular Mementos con un Palacio...[n]Cuesta creerlo.[n][w][e]

[msg SAFE_MES_ANN_07 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 2 1 6058 65535 0]Ahora que lo pienso,[n]no sabemos nada sobre el pasado[n]del doctor Maruki.[n][w][e]

[msg SAFE_MES_ANN_08 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 2 1 6058 65535 0]As胤 que eso fue lo que le pas吋[n]al doctor Maruki...[n][w][e]
[s][f 4 10 65535 0 0]No s姻 todo lo que pas吋, pero creo[n]que empiezo a entender por qu姻 dice[n]que la realidad es tan dolorosa.[n][w][e]

[msg SAFE_MES_ANN_09 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 2 1 6197 65535 0]Pues si est茨 grabado, ser茨[n]importante para el doctor Maruki.[n][w][e]

[msg SAFE_MES_ANN_10 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 2 1 54001 65535 0]Estaba tan ensimismada que no[n]me par姻 a pensar lo que representa[n]el Palacio del doctor Maruki...[n][w][e]
[s][f 4 10 65535 0 0]Ahora que lo pienso,[n]parece un laboratorio. [n][w][e]

[msg SAFE_MES_ANN_11 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 2 1 6028 65535 0]*bostezo* Estoy bastante cansada...[n][w][e]
[s][f 4 10 65535 0 0]Creo que se me da mejor luchar[n]que pensar.[n][w][e]

[msg SAFE_MES_ANN_12 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 2 1 6028 65535 0]As胤 que eso es lo que ocurre[n]cuando terminas la prueba...[n]Vaya tela.[n][w][e]
[s][f 4 10 65535 0 0]Aunque eso no parec胤a[n]un tratamiento de verdad...[n][w][e]

[msg SAFE_MES_ANN_13 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 2 1 6155 65535 0]Espero que la cinta ande por aqu胤.[n]A ver d吋nde no hemos mirado...[n][w][e]

[msg SAFE_MES_ANN_14 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 2 1 6058 65535 0]夷Qu姻 veremos en esta cinta?[n][w][e]

[msg SAFE_MES_ANN_15 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][vp 8 2 1 6197 65535 0]Perder a alguien cercano[n]es un palo tremendo.[n][w][e]
[s][f 4 10 65535 0 0]Si Shiho no se hubiese recuperado,[n]yo tambi姻n me sentir胤a culpable.[n][w][e]

[msg SAFE_MES_ANN_16 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 2 1 6058 65535 0]Unas escaleras preciosas, pero[n]夷c吋mo las ver茨 el doctor Maruki?[n][w][e]

[msg SAFE_MES_ANN_17 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 2 1 6019 65535 0]斡Tenemos la ruta hacia el tesoro![n]斡Av胤same si me necesitas[n]para cualquier cosa![n][w][e]

[msg SAFE_MES_YUSUKE_01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_YUSUKE_02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_YUSUKE_03 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][vp 8 2 1 4129 65535 0]Nos enfrentamos a un oponente[n]totalmente distinto a lo que[n]hemos visto hasta ahora.[n][w][e]
[s][f 4 10 65535 0 0]Prepar姻monos por 雨ltima vez.[n][w][e]

[msg SAFE_MES_YUSUKE_04 [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][vp 8 2 1 4190 65535 0]La Persona de Violet tiene una[n]forma encantadora. Qu姻 preciosidad.[n][w][e]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0]La dibujar胤a si no estuvi姻semos[n]tan ocupados. Qu姻 l茨stima.[n][w][e]

[msg SAFE_MES_YUSUKE_05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 2 1 4158 65535 0]夷Ahora hay m茨s sombras aqu胤?[n]Aseg雨rate de ir con cautela, Joker.[n][w][e]

[msg SAFE_MES_YUSUKE_06 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][vp 8 2 1 4047 65535 0]Ha fusionado Mementos con[n]su Palacio... Es extraordinario.[n][w][e]

[msg SAFE_MES_YUSUKE_07 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][vp 8 2 1 4028 65535 0]Hay que responder a una pregunta[n]personal sobre el pasado de Maruki.[n][w][e]
[s][f 4 10 65535 0 0]No me gusta cotillear,[n]pero no hay tiempo para m茨s.[n][w][e]

[msg SAFE_MES_YUSUKE_08 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][vp 8 2 1 4169 65535 0]Deber胤amos alegrarnos de haber[n]podido abrir la puerta, pero[n]ver un v胤deo as胤...[n][w][e]

[msg SAFE_MES_YUSUKE_09 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 2 1 4087 65535 0]El reproductor VHS me provoca[n]una agradable nostalgia,[n]pero sin cinta no sirve de nada.[n][w][e]

[msg SAFE_MES_YUSUKE_10 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 2 1 4117 65535 0]Los seres cognitivos de aqu胤[n]buscan la felicidad mediante[n]la investigaci吋n de Maruki...[n][w][e]

[msg SAFE_MES_YUSUKE_11 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 2 1 4129 65535 0]夷Determinar el estado mental[n]de alguien con preguntas es otro[n]de sus m姻todos de orientaci吋n?[n][w][e]

[msg SAFE_MES_YUSUKE_12 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 2 1 4129 65535 0]La gente est茨 como hechizada.[n]Esto parece cualquier cosa,[n]menos felicidad.[n][w][e]

[msg SAFE_MES_YUSUKE_13 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][vp 8 2 1 4028 65535 0]Ay, falta el v胤deo...[n]Habr茨 que esforzarse el doble.[n][w][e]

[msg SAFE_MES_YUSUKE_14 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 2 1 4127 65535 0]Vamos a ver el v胤deo[n]antes de que me entre tanta hambre[n]que no pueda ni prestar atenci吋n.[n][w][e]

[msg SAFE_MES_YUSUKE_15 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 2 1 4187 65535 0]A m胤 tambi姻n me gustar胤a[n]que mi pasado fuese otro, pero...[n][w][e]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0]Si me preguntaran si lo deseo[n]de verdad, dir胤a que no.[n][w][e]

[msg SAFE_MES_YUSUKE_16 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][vp 8 2 1 4128 65535 0]Qu姻 preciosidad de sitio, pero hay[n]una gran sensaci吋n de vac胤o...[n][w][e]
[s][f 4 10 65535 0 0]夷Tambi姻n lo ver茨 as胤[n]el se隠or del Palacio?[n][w][e]

[msg SAFE_MES_YUSUKE_17 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 2 1 4023 65535 0]Ahora debemos esperar.[n]Si necesitas cualquier cosa,[n]perm胤teme que te ayude.[n][w][e]

[msg SAFE_MES_MAKOTO_01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_MAKOTO_02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_MAKOTO_03 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][vp 8 2 1 2128 65535 0]Nunca pens姻 que volver胤amos[n]de nuevo al Metaverso,[n]y menos por algo como esto.[n][w][e]

[msg SAFE_MES_MAKOTO_04 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][vp 8 2 1 2048 65535 0]Violet s胤 que sabe combatir.[n][w][e]

[msg SAFE_MES_MAKOTO_05 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][vp 8 2 1 2160 65535 0]La zona posterior al almac姻n[n]es diferente. No baj姻is la guardia.[n][w][e]

[msg SAFE_MES_MAKOTO_06 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][vp 8 2 1 2128 65535 0]Antes hab胤a que cambiar la[n]cognici吋n del se隠or del Palacio,[n]pero ahora es casi lo contrario.[n][w][e]

[msg SAFE_MES_MAKOTO_07 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][vp 8 2 1 2028 65535 0]夷Qu姻 perdi吋 el doctor Maruki?[n]Es una pregunta tan ambigua que no[n]puedo ni imaginar una respuesta.[n][w][e]

[msg SAFE_MES_MAKOTO_08 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 2 1 2132 65535 0]Entonces lo que vimos en el v胤deo...[n]夷Ah胤 surgi吋 el poder de[n]materializaci吋n del doctor Maruki?[n][w][e]

[msg SAFE_MES_MAKOTO_09 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][vp 8 2 1 53339 65535 0]Dar con la respuesta estuvo bien,[n]pero a saber si nos esperan m茨s[n]tras esa puerta...[n][w][e]

[msg SAFE_MES_MAKOTO_10 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][vp 8 2 1 2188 65535 0]Jam茨s habr胤a imaginado que salvar[n]vidas mediante una investigaci吋n[n]fuese un deseo distorsionado.[n][w][e]

[msg SAFE_MES_MAKOTO_11 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][vp 8 2 1 2028 65535 0]No me esperaba que Maruki[n]nos examinara.[n][w][e]

[msg SAFE_MES_MAKOTO_12 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 2 1 2019 65535 0]夷Qu姻 ser茨n esos grandes cables[n]que vimos antes?[n][w][e]
[s][f 4 10 65535 0 0]Me pregunto ad吋nde conducir茨n...[n]夷Tal vez a Mementos?[n][w][e]

[msg SAFE_MES_MAKOTO_13 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 2 1 2150 65535 0]Vayamos a buscar esa cinta[n]en cuanto estemos listos.[n][w][e]

[msg SAFE_MES_MAKOTO_14 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][vp 8 2 1 2128 65535 0]A saber qu姻 veremos[n]en el siguiente v胤deo.[n][w][e]

[msg SAFE_MES_MAKOTO_15 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][vp 8 2 1 2028 65535 0]Tarde o temprano,[n]todos nos comparamos[n]con el resto de nuestra familia.[n][w][e]

[msg SAFE_MES_MAKOTO_16 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 2 1 2157 65535 0]Casi hemos llegado[n]al doctor Maruki. Sigue as胤, Joker.[n][w][e]

[msg SAFE_MES_MAKOTO_17 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 2 1 2165 65535 0]La ruta est茨 asegurada. Av胤sanos[n]cuando quieras que vayamos.[n][w][e]

[msg SAFE_MES_HARU_01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_HARU_02 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_HARU_03 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 2 1 3193 65535 0]A雨n no puedo perdonar a Crow[n]por lo que hizo.[n][w][e]
[s][f 4 10 65535 0 0]Solo colaboro con 姻l porque[n]considero que necesitamos su ayuda.[n][w][e]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 2 1 53509 65535 0]Despu姻s de todo,[n]este es un trabajo[n]para los Ladrones Fantasma.[n][w][e]

[msg SAFE_MES_HARU_04 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][vp 8 2 1 3048 65535 0]Violet est茨 muy activa.[n]Cuesta seguirle el ritmo.[n][w][e]

[msg SAFE_MES_HARU_05 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 2 1 3019 65535 0]Las cosas han cambiado.[n]夷Estaremos progresando?[n]Sigamos adelante, Joker.[n][w][e]

[msg SAFE_MES_HARU_06 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 2 1 3178 65535 0]夷En qu姻 clase de mundo[n]viviremos si la realidad[n]se fusiona con Mementos?[n][w][e]

[msg SAFE_MES_HARU_07 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 2 1 3111 65535 0]夷Qu姻 perdi吋 el doctor Maruki?[n][w][e]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0]Preferir胤a evitarlo, pero nuestra[n]雨nica opci吋n es dar[n]con la respuesta.[n][w][e]

[msg SAFE_MES_HARU_08 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 2 1 3198 65535 0]No me imagino por lo que[n]habr茨n pasado la novia[n]y la familia del doctor Maruki...[n][w][e]

[msg SAFE_MES_HARU_09 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 2 1 3157 65535 0]La sala de v胤deo[n]no era como el resto del Palacio,[n]夷no crees?  [n][w][e]
[s][f 4 10 65535 0 0]夷Ser茨 especial por alguna raz吋n?[n][w][e]

[msg SAFE_MES_HARU_10 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 2 1 3156 65535 0]Parece que a雨n nos queda mucho[n]camino por recorrer, pero podemos[n]regresar si es peligroso.[n][w][e]

[msg SAFE_MES_HARU_11 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 2 1 3111 65535 0]Entiendo mejor la realidad ideal[n]del doctor Maruki, pero eso no[n]quiere decir que est姻 de acuerdo.[n][w][e]

[msg SAFE_MES_HARU_12 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 2 1 3192 65535 0]夷Qu姻 estar茨 sintiendo[n]la gente que lleva auriculares?[n]Parecen bastante felices...[n][w][e]

[msg SAFE_MES_HARU_13 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 2 1 3052 65535 0]Primero hay que encontrar[n]esa cinta. Cuando est姻is listos,[n]deber胤amos irnos.[n][w][e]

[msg SAFE_MES_HARU_14 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 2 1 3019 65535 0]Menos mal que tenemos la cinta.[n]Vamos a la sala de v胤deo[n]a ver qu姻 nos depara.[n][w][e]

[msg SAFE_MES_HARU_15 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 2 1 3018 65535 0]La gente a la que ha reunido aqu胤[n]Maruki... son sus pacientes, 夷no?[n][w][e]
[s][f 4 10 65535 0 0]Todos estaban sonriendo, pero[n]no s姻 si son realmente felices...[n][w][e]

[msg SAFE_MES_HARU_16 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 2 1 3178 65535 0]La enorme sala de las escaleras era[n]muy hermosa, pero me transmit胤a[n]mucha tristeza. 夷Por qu姻 ser茨?[n][w][e]

[msg SAFE_MES_HARU_17 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 2 1 3048 65535 0]Ahora solo queda esperar al gran[n]d胤a. Procuremos no arrepentirnos[n]de nada.[n][w][e]

[msg SAFE_MES_HUTABA_01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_HUTABA_02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_HUTABA_03 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][vp 8 2 1 9176 65535 0]Una parte de m胤 no acepta[n]a Crow en el equipo.[n][w][e]
[s][f 4 10 65535 0 0]Por mucho que lo intente,[n]no creo que pueda aceptarlo.[n][w][e]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][vp 8 2 1 9089 65535 0]斡Deja que vuelva a encargarme de[n]la navegaci吋n! 斡Tengo tantas ganas[n]que no podr姻 pensar en otra cosa![n][w][e]

[msg SAFE_MES_HUTABA_04 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][vp 8 2 1 9158 65535 0]Parece que a雨n nos queda[n]mucho por delante. Continuemos.[n][w][e]

[msg SAFE_MES_HUTABA_05 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][vp 8 2 1 9028 65535 0]El almac姻n estaba hasta arriba[n]de cajas...[n]Me ha recordado a mi habitaci吋n.[n][w][e]

[msg SAFE_MES_HUTABA_06 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][vp 8 2 1 9026 65535 0]斡Esp胤a el mundo real[n]desde su Palacio![n]斡No tenemos privacidad![n][w][e]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0]斡Grabar nuestras conversaciones no[n]mola! Ignorar姻 cualquier comentario[n]de 或le dijo la sart姻n al cazo位.[n][w][e]

[msg SAFE_MES_HUTABA_07 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][vp 8 2 1 54741 65535 0]Esa puerta es un aut姻ntico pe隠azo.[n]Tampoco podemos hacer nada[n]para evitarla.[n][w][e]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0]Vamos a husmear a ver si[n]encontramos alguna pista.[n][w][e]

[msg SAFE_MES_HUTABA_08 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][vp 8 2 1 9128 65535 0]夷Acabamos de ver c吋mo despierta[n]la Persona de Maruki en el v胤deo?[n][w][e]
[s][f 4 10 65535 0 0]Pero no parec胤a que supiera[n]lo que estaba ocurriendo.[n]Mmm, no lo pillo.[n][w][e]

[msg SAFE_MES_HUTABA_09 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][vp 8 2 1 9029 65535 0]No quiero que nadie conozca[n]las respuestas[n]a mis preguntas secretas.[n][w][e]

[msg SAFE_MES_HUTABA_10 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][vp 8 2 1 9176 65535 0]夷El deseo de Maruki[n]de tener un laboratorio[n]es lo que cre吋 este Palacio?[n][w][e]

[msg SAFE_MES_HUTABA_11 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]Parece que la prueba ha terminado.[n]斡Vuelta a la rutina![n][w][e]

[msg SAFE_MES_HUTABA_12 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][vp 8 2 1 9038 65535 0]No sab胤a que exist胤an unos[n]auriculares as胤. Bueno, no existen,[n]que estamos en el Metaverso.[n][w][e]

[msg SAFE_MES_HUTABA_13 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][vp 8 2 1 9100 65535 0]Detecto un mont吋n de sombras cerca. [n][w][e]
[s][f 4 10 65535 0 0]Cuidado con la b雨squeda[n]de la cinta de v胤deo, Joker.[n][w][e]

[msg SAFE_MES_HUTABA_14 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][vp 8 2 1 9052 65535 0]斡La b雨squeda ha sido un 姻xito![n]斡Vamos a la sala de v胤deo![n][w][e]

[msg SAFE_MES_HUTABA_15 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][vp 8 2 1 9029 65535 0]Puede manipular la cognici吋n de[n]cualquiera en la realidad. Si lo piensas,[n]es un poder bastante chungo.[n][w][e]

[msg SAFE_MES_HUTABA_16 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][vp 8 2 1 9196 65535 0]斡Casi hemos llegado[n]al doctor Maruki![n][w][e]
[s][f 4 10 65535 0 0]斡Vamos, Joker![n]斡Os cubrir姻 el resto del camino![n][w][e]

[msg SAFE_MES_HUTABA_17 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][vp 8 2 1 9158 65535 0]斡Ruta asegurada![n]Hagamos lo que podamos[n]con el tiempo que nos queda.[n][w][e]

[msg SAFE_MES_AKECHI_01 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 2 1 8155 65535 0]S姻 que descansar de vez[n]en cuando es importante,[n]pero 夷acaso tenemos tiempo?[n][w][e]

[msg SAFE_MES_AKECHI_02 [Akechi]]
[s][bup 0 9 812 0 0][f 4 10 65535 0 0][vp 8 2 1 8127 65535 0]Largu姻monos en cuanto hayamos[n]terminado. Vamos al auditorio,[n]夷verdad?[n][w][e]

[msg SAFE_MES_AKECHI_03 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 2 1 8127 65535 0]Otra vez todos juntos...[n][w][e]
[s][f 4 10 65535 0 0]Oracle se encargar茨[n]de las estrategias y yo me centrar姻[n]en el combate.[n][w][e]

[msg SAFE_MES_AKECHI_04 [Akechi]]
[s][bup 0 9 811 0 0][f 4 10 65535 0 0][vp 8 2 1 8133 65535 0]Al final Violet le ha cogido el truco[n]a las peleas.[n][w][e]
[s][f 4 10 65535 0 0]Deber胤amos irnos,[n]que ya hemos terminado, Joker.[n][w][e]

[msg SAFE_MES_AKECHI_05 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][vp 8 2 1 8127 65535 0]Un almac姻n, 夷eh?[n]Seguro que hay un mont吋n de...[n][w][e]
[s][f 4 10 65535 0 0]Bueno, ahora eso no importa[n]en absoluto.[n][w][e]

[msg SAFE_MES_AKECHI_06 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][vp 8 2 1 54499 65535 0]Supervisa el mundo desde dentro de[n]su Palacio... Vaya sistema m茨s[n]absurdo se ha montado.[n][w][e]

[msg SAFE_MES_AKECHI_07 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 2 1 54502 65535 0]La pregunta de seguridad es sobre[n]lo que perdi吋 el doctor Maruki.[n][w][e]
[s][f 4 10 65535 0 0]Pues de algo se arrepentir茨[n]si esa es su contrase隠a.[n][w][e]

[msg SAFE_MES_AKECHI_08 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 2 1 54503 65535 0]Parece que despert吋[n]a su Persona mientras estaba[n]en el mundo real.[n][w][e]
[s][f 4 10 65535 0 0]夷Y si tiene un Palacio[n]desde entonces? Bueno...,[n]la verdad es que da igual.[n][w][e]

[msg SAFE_MES_AKECHI_09 [Akechi]]
[s][bup 0 9 813 0 0][f 4 10 65535 0 0][vp 8 2 1 8028 65535 0]Usar informaci吋n personal[n]como medida de seguridad...[n][w][e]
[s][f 4 10 65535 0 0]Es sencillo y eficaz...[n]a la hora de fastidiar a los dem茨s.[n]Espero que no haya m茨s.[n][w][e]

[msg SAFE_MES_AKECHI_10 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 2 1 8128 65535 0]En el auditorio se presentan los[n]resultados de las investigaciones y[n]las pistas ser茨n para experimentar.[n][w][e]
[s][f 4 10 65535 0 0]No son m茨s que conjeturas,[n]pero creo que tengo raz吋n.[n][w][e]

[msg SAFE_MES_AKECHI_11 [Akechi]]
[s][bup 0 9 812 0 0][f 4 10 65535 0 0][vp 8 2 1 54502 65535 0]Aqu胤 no se te considera normal[n]si no est茨s de acuerdo con[n]la filosof胤a egoc姻ntrica de Maruki.[n][w][e]
[s][f 4 10 65535 0 0]S姻 que fue decisi吋n[n]de los seres cognitivos del Palacio,[n]pero 夷no os parece absurdo?[n][w][e]

[msg SAFE_MES_AKECHI_12 [Akechi]]
[s][bup 0 9 812 0 0][f 4 10 65535 0 0][vp 8 2 1 54489 65535 0]As胤 que los cascos se usan[n]para lavar cerebros...[n][w][e]
[s][f 4 10 65535 0 0]Si esa es la 或salvaci吋n位 de la que[n]habla Maruki, yo lo tacho de loco.[n][w][e]

[msg SAFE_MES_AKECHI_13 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 2 1 8155 65535 0]Seguramente haya m茨s enemigos[n]a partir de ahora. Cuidado,[n]no mur茨is antes de tiempo.[n][w][e]

[msg SAFE_MES_AKECHI_14 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 2 1 8158 65535 0]Ahora que tenemos la cinta,[n]deber胤amos ver qu姻 tipo de pistas[n]contiene.[n][w][e]

[msg SAFE_MES_AKECHI_15 [Akechi]]
[s][bup 0 9 812 0 0][f 4 10 65535 0 0][vp 8 2 1 54489 65535 0]Maruki est茨 convencido[n]de que est茨 salvando a la gente.[n][w][e]
[s][f 4 10 65535 0 0]Lo 雨nico que hace es obligarles[n]a cumplir sus deseos, y lo peor es[n]que se considera bondadoso. Puaj.[n][w][e]

[msg SAFE_MES_AKECHI_16 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][vp 8 2 1 8099 65535 0]Sospecho que nos acercamos[n]al tesoro. Sigamos adelante,[n]pero ve con cuidado, Joker.[n][w][e]

[msg SAFE_MES_AKECHI_17 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 2 1 54503 65535 0]Ahora esperamos a la fecha l胤mite...[n][w][e]
[s][f 4 10 65535 0 0]Si tienes cosas que hacer antes,[n]te acompa隠o.[n][w][e]

[msg SAFE_MES_YOSHIZAWA_01 [[f 4 31 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 2 1 57045 65535 0]Siento un cosquilleo raro en[n]el pecho... Espero que solo sean[n]los nervios por estar aqu胤.[n][w][e]

[msg SAFE_MES_YOSHIZAWA_02 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0]RESERVE[n][w][e]

[msg SAFE_MES_YOSHIZAWA_03 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 2 1 57144 65535 0]斡Cuando quieras, Joker![n][w][e]

[msg SAFE_MES_YOSHIZAWA_04 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]Siento haberte preocupado.[n]Pero 斡ya estoy bien! Sigamos.[n][w][e]

[msg SAFE_MES_YOSHIZAWA_05 [[f 4 31 10 0]]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][vp 8 2 1 57058 65535 0]斡Con Oracle, avanzar por el Palacio[n]parece un juego de ni隠os!  [n][w][e]

[msg SAFE_MES_YOSHIZAWA_06 [[f 4 31 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 2 1 57037 65535 0]Todav胤a no me hago a la idea[n]de que hay un mundo entero que[n]surgi吋 de la cognici吋n de la gente.[n][w][e]

[msg SAFE_MES_YOSHIZAWA_07 [[f 4 31 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 2 1 57181 65535 0]夷Qu姻 puede haber perdido[n]el doctor Maruki?[n][w][e]
[s][f 4 10 65535 0 0]Si usa esa respuesta como[n]c吋digo de seguridad, debe de ser[n]algo muy especial para 姻l.  [n][w][e]

[msg SAFE_MES_YOSHIZAWA_08 [[f 4 31 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 2 1 57060 65535 0]No sab胤a que el doctor Maruki[n]hab胤a pasado por eso...[n][w][e]
[s][f 4 10 65535 0 0]Lo 雨nico que hice fue contarle[n]mis problemas.[n][w][e]

[msg SAFE_MES_YOSHIZAWA_09 [[f 4 31 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 2 1 57045 65535 0]Con cada v胤deo que vemos,[n]es m茨s dif胤cil avanzar.[n][w][e]

[msg SAFE_MES_YOSHIZAWA_10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 2 1 57173 65535 0]夷Entonces el estadio se transform吋[n]en un laboratorio por su cognici吋n?[n]Qu姻 cosa m茨s rara.  [n][w][e]

[msg SAFE_MES_YOSHIZAWA_11 [[f 4 31 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 2 1 57037 65535 0]El 或tratamiento位 del que hablan[n]las sombras...[n]夷Es el mismo que el m胤o?[n][w][e]
[s][f 4 10 65535 0 0]A ver, s胤, me sent胤a mejor, pero...[n][w][e]

[msg SAFE_MES_YOSHIZAWA_12 [[f 4 31 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 2 1 57045 65535 0]Cambiar toda tu cognici吋n[n]para poder vivir feliz...[n][w][e]
[s][f 4 10 65535 0 0]Yo antes era as胤.[n][w][e]

[msg SAFE_MES_YOSHIZAWA_13 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 2 1 57142 65535 0]La primera vez que he visto[n]un v胤deo en VHS[n]ha sido en este Palacio.[n][w][e]
[s][f 4 10 65535 0 0]Aunque recuerdo que en mi casa[n]ve胤a pel胤culas as胤[n]cuando era peque.[n][w][e]

[msg SAFE_MES_YOSHIZAWA_14 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 2 1 57033 65535 0]Encontramos la cinta.[n]夷Qu姻 habr茨 dentro?[n][w][e]

[msg SAFE_MES_YOSHIZAWA_15 [[f 4 31 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][vp 8 2 1 57181 65535 0]Lo 雨ltimo que esperaba era[n]ver una cosa as胤 en v胤deo.[n][w][e]
[s][f 4 10 65535 0 0]夷Eso significa... que de verdad[n]se preocupaba por mi bienestar?[n][w][e]

[msg SAFE_MES_YOSHIZAWA_16 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 2 1 57036 65535 0]Esta zona no es como la anterior.[n]夷Qu姻 habr茨 m茨s adelante?[n][w][e]

[msg SAFE_MES_YOSHIZAWA_17 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 2 1 57051 65535 0]Ahora solo queda esperar hasta[n]la fecha l胤mite, 夷no? 斡Hasta[n]entonces, hagamos lo que podamos![n][w][e]

