[sel YESNO_SEL top]
[s]はい[e]
[s]いいえ[e]

[msg NPC_GREETING_MSG]
[s]挨拶[n][w][e]

[msg NPC_01]
[s]会話[n][w][e]

[msg MSG_NARAIGOTO_001_0_0 [Madre irritada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]斡Vas a llegar tarde a las clases[n]como no te des prisa![n]斡Deja de entretenerte![n][w][e]

[msg MSG_NARAIGOTO_001_1_0 [Hija triste]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]No me entretengo.[n][w][e]
[s][vp 8 2 1 0 11 0]夷Por qu姻 tengo que ir a clases[n]de piano? No quiero ser pianista...[n][w][e]

[msg MSG_NARAIGOTO_001_2_0 [Madre irritada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]斡Bobadas! 斡Tienes que tomarte[n]en serio las clases![n]斡Es por tu futuro![n][w][e]

[msg MSG_NARAIGOTO_001_3_0 [Hija triste]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Vale, hasta luego...[n][w][e]

[msg MSG_NARAIGOTO_002_0_0 [Hija t胤mida]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Mam茨, 夷sab胤as[n]que los Ladrones Fantasma[n]despiertan el coraz吋n de la gente?[n][w][e]
[s][vp 8 2 1 0 11 0]Me pregunto si eso cambia[n]a las personas...[n][w][e]

[msg MSG_NARAIGOTO_002_1_0 [Madre irritada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Ya basta. Si tienes tiempo[n]para esas tonter胤as, tambi姻n lo tienes[n]para una nueva canci吋n.[n][w][e]
[s][vp 8 2 1 0 12 0]斡La competici吋n est茨 al caer![n]斡No hay cena si no tocas bien![n][w][e]

[msg MSG_NARAIGOTO_002_2_0 [Hija triste]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Ya no quiero hacerlo...[n]Desear胤a que mi mam茨[n]se convirtiera en otra persona...[n][w][e]

[msg MSG_NARAIGOTO_003_0_0 [Hija t胤mida]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Mis amigos me han invitado a jugar[n]a voleibol durante el d胤a libre.[n][w][e]

[msg MSG_NARAIGOTO_003_1_0 [Madre irritada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]斡Imposible! 斡夷C吋mo vas a tocar[n]el piano si te lesionas?![n][w][e]

[msg MSG_NARAIGOTO_003_2_0 [Hija t胤mida]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]夷Y si vamos a alg雨n sitio?[n]Todos mis amigos est茨n[n]de viaje con sus familias...[n][w][e]

[msg MSG_NARAIGOTO_003_3_0 [Madre irritada]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Cuando seas una pianista de[n]renombre, podr茨s ir a donde[n]quieras. Ahora, sigue practicando.[n][w][e]
[s][vp 8 2 1 0 12 0]Ya casi es la hora de la[n]competici吋n. Tienes que ganar,[n]夷queda claro?[n][w][e]

[msg MSG_NARAIGOTO_004_0_0 [Madre hist姻rica]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]斡Qu姻 desastre de actuaci吋n![n]斡La oportunidad de tu vida,[n]desperdiciada![n][w][e]
[s][vp 8 2 1 0 12 0]夷Por qu姻? 夷Por qu姻 me haces esto?[n]斡Necesito que triunfes al piano![n][w][e]
[s][vp 8 2 1 0 12 0]斡No has practicado lo suficiente![n]斡No me haces caso![n][w][e]

[msg MSG_NARAIGOTO_004_1_0 [Hija a punto de llorar]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Lo siento, lo siento mucho...[n]Me esforzar姻 m茨s en las clases...[n]*sollozo*[n][w][e]

[msg MSG_NARAIGOTO_004_2_0 [Madre hist姻rica]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]斡La que deber胤a llorar soy yo![n]斡Es todo culpa tuya![n][w][e]

[msg MSG_quest30_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]斡Parece que hemos encontrado[n]al objetivo! 斡Vamos a hablarlo[n]con los dem茨s en el escondite![n][w][e]

[msg MSG_NARAIGOTO_005_0_0 [Madre deca胤da]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Cuando era joven, quer胤a ser[n]pianista. Me esforc姻 al m茨ximo[n]y practiqu姻 un mont吋n, pero...[n][w][e]
[s][vp 8 2 1 0 12 0]Siento haberte obligado a perseguir[n]mi sue隠o. A partir de ahora, eres[n]libre de hacer lo que quieras.[n][w][e]

[msg MSG_NARAIGOTO_005_1_0 [Hija amable]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]No me gusta que te enfades[n]conmigo, pero disfruto tocando el[n]piano, as胤 que no lo voy a dejar.[n][w][e]
[s][vp 8 2 1 0 11 0]Alg雨n d胤a, ser姻 una gran pianista[n]y viajaremos juntas por el mundo.[n][w][e]

[msg MSG_NARAIGOTO_005_2_0 [Madre deca胤da]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Lo siento mucho... Gracias.[n][w][e]

[msg MSG_NARAIGOTO_006_0_0 [Madre amable]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]夷Qu姻 te parece si hacemos planes[n]con tu padre en tu d胤a libre?[n][w][e]

[msg MSG_NARAIGOTO_006_1_0 [Hija feliz]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]Quiero ir de compras contigo[n]y quedarme a jugar con pap茨.[n][w][e]
[s][vp 8 2 1 0 11 0]Ah, tambi姻n me gustar胤a ir a mirar[n]partituras para aprender[n]una canci吋n nueva.[n][w][e]

[msg MSG_NARAIGOTO_006_2_0 [Madre amable]]
[s][f 4 23 1 12 3 10 0 0][vp 8 2 1 0 12 0]Estupendo. Venga, ten cuidado.[n][w][e]

[msg MSG_NARAIGOTO_006_3_0 [Hija feliz]]
[s][f 4 23 1 11 3 10 0 0][vp 8 2 1 0 11 0]斡Gracias, mam茨! Voy a darlo[n]todo en clase.[n][w][e]

[msg MSG_TUMAARASOI_001_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Tanto accidente me pone[n]de los nervios. Mi gordi acaba[n]de ascender, 夷y si le pasa algo?[n][w][e]

[msg MSG_TUMAARASOI_001_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Corren unos tiempos horribles.[n]Solo pido que tambi姻n proteja[n]a mi marido.[n][w][e]

[msg MSG_TUMAARASOI_001_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 20 20 0 10][vp 8 2 1 0 19 0]Jo, jo, jo. Mientras trabaje,[n]le ir茨 bien bajo las 吋rdenes[n]de mi pastelito.[n][w][e]
[s][vp 8 2 1 0 19 0]No soporta a la gente vaga.[n]Jo, jo, jo.[n][w][e]

[msg MSG_TUMAARASOI_002_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]夷Tu hijo no va al Shujin?[n]Dicen que es muy estricto.[n][w][e]
[s][vp 8 2 1 0 19 0]Debe de ser duro ir a clase[n]con tantos delin..., digo,[n]estudiantes 或peculiares位.[n][w][e]

[msg MSG_TUMAARASOI_002_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Es cierto, no le va muy bien.[n]Habr茨 salido a su padre...[n]No ha sido f茨cil.[n][w][e]

[msg MSG_TUMAARASOI_002_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Bueno, tras un gran hombre, siempre[n]hay una gran mujer y, tras[n]cada hijo, hay una gran madre.[n][w][e]

[msg MSG_TUMAARASOI_003_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Han invitado a mi terroncito[n]a la exposici吋n de Madarame.[n]夷Quieres venir con tu familia?[n][w][e]

[msg MSG_TUMAARASOI_003_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Ni pensarlo. No sabemos distinguir[n]el buen arte del malo.[n][w][e]

[msg MSG_TUMAARASOI_003_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Y nunca lo conseguir姻is si no[n]aprend姻is a apreciar la calidad.[n][w][e]

[msg MSG_TUMAARASOI_004_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]La exhibici吋n de Madarame[n]fue sublime.[n][w][e]
[s][vp 8 2 1 0 19 0]Estoy muy orgullosa[n]de ser japonesa. Jo, jo, jo.[n][w][e]

[msg MSG_TUMAARASOI_004_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Entonces eras t雨[n]a la que vi en las noticias.[n][w][e]

[msg MSG_TUMAARASOI_004_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Ay, 夷de veras?[n]No ten胤a ni idea. Jo, jo, jo.[n][w][e]

[msg MSG_TUMAARASOI_005_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]斡Madarame ha resultado ser[n]un aut姻ntico fraude! 斡Lo 雨nico[n]que busca es sacar tajada![n][w][e]

[msg MSG_TUMAARASOI_005_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Ha confesado que plagiaba, 夷no?[n]Y nada menos que a su alumno.[n][w][e]

[msg MSG_TUMAARASOI_005_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]A veces pasa. Gente que intenta colar[n]el trabajo de otros como si fuera suyo.[n][w][e]

[msg MSG_TUMAARASOI_005_3_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Jo, jo, jo. S胤, mi marido[n]est茨 muy consternado.[n][w][e]

[msg MSG_TUMAARASOI_006_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]No hago m茨s que o胤r hablar sobre[n]las extorsiones. Tu queridito[n]deber胤a ir con cuidado.[n][w][e]

[msg MSG_TUMAARASOI_006_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Por suerte, su salario es tan bajo[n]que no tiene de qu姻 preocuparse.[n][w][e]

[msg MSG_TUMAARASOI_006_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Qu姻 valiente por tu parte.[n]A nosotros nos aterra la idea[n]de estar en peligro.[n][w][e]

[msg MSG_TUMAARASOI_006_3_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Hay cosas que los ricachones[n]como vosotros no entend姻is.[n][w][e]

[msg MSG_TUMAARASOI_007_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]斡No permitir姻 que extorsionen[n]a mi hijo! 斡夷Por qu姻[n]no hace nada la polic胤a?![n][w][e]

[msg MSG_TUMAARASOI_007_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Es terrible. 夷Qu姻 ha pasado?[n][w][e]

[msg MSG_TUMAARASOI_007_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]斡Lo es! Pero solo le han quitado[n]una cartera barata que no costaba[n]m茨s de 100 000 yenes.[n][w][e]

[msg MSG_TUMAARASOI_007_3_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Para nosotros, una p姻rdida as胤[n]habr胤a sido la ruina. No esperaba[n]menos de tu familia. Jo, jo, jo.[n][w][e]

[msg MSG_TUMAARASOI_008_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Los Ladrones Fantasma han acabado[n]con la mafia, 夷no? Les est茨 bien[n]empleado por asustar a mi ni隠o.[n][w][e]
[s][vp 8 2 1 0 19 0]Se han ganado todo mi apoyo.[n]斡Ojal茨 hagan lo mismo[n]con toda la gente mala![n][w][e]

[msg MSG_TUMAARASOI_008_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]A saber qu姻 estar茨 haciendo[n]la polic胤a. No parece de fiar.[n][w][e]

[msg MSG_TUMAARASOI_008_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Tienes toda la raz吋n. Se estar茨n[n]replanteando la pol胤tica[n]de prevenci吋n de delitos.[n][w][e]

[msg MSG_TUMAARASOI_009_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]夷Te has enterado de lo de Medjed?[n]斡Es hora de que los Ladrones[n]Fantasma act雨en de nuevo![n][w][e]

[msg MSG_TUMAARASOI_009_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Lo 雨nico que podemos hacer[n]es rezar para que Medjed no le eche[n]el ojo a nuestra empresa.[n][w][e]

[msg MSG_TUMAARASOI_009_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]As胤 es. Los mandamases como[n]mi marido tendr茨n que dar un paso[n]al frente si la cosa se tuerce.[n][w][e]

[msg MSG_TUMAARASOI_009_3_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]A veces pienso que es un alivio[n]que no hayan ascendido a mi marido.[n][w][e]

[msg MSG_TUMAARASOI_010_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]斡Los Ladrones Fantasma[n]lo han vuelto a conseguir![n]Siempre he confiado en ellos.[n][w][e]

[msg MSG_TUMAARASOI_010_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Ahora todo el mundo est茨 con[n]los Ladrones Fantasma. 斡No paran[n]de hablar de ellos en televisi吋n![n][w][e]

[msg MSG_TUMAARASOI_010_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Mi pichoncito dice[n]que quiere vender una hamburguesa[n]de los Ladrones Fantasma.[n][w][e]
[s][vp 8 2 1 0 19 0]夷No crees que ser茨 el no va m茨s?[n]Uno siempre debe estar al tanto[n]de las 雨ltimas tendencias.[n][w][e]

[msg MSG_TUMAARASOI_011_0_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]夷C吋mo est茨 tu marido? Despu姻s[n]de las noticias, habr茨n saltado[n]todas las alarmas en la empresa.[n][w][e]

[msg MSG_TUMAARASOI_011_1_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]斡Es todo mentira! 斡Atacan[n]a Okumura Foods porque[n]tienen envidia de su 姻xito![n][w][e]

[msg MSG_TUMAARASOI_011_2_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]夷Est茨s segura? Mi marido nunca cobra las horas extra.[n][w][e]
[s][vp 8 2 1 0 20 0]夷Le echar茨n la culpa al presidente?[n]M茨s le vale confesar. Jo, jo, jo.[n][w][e]

[msg MSG_TUMAARASOI_012_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Parece que es imposible[n]dar con Okumura. Mi tortolito[n]no para de trabajar con tanto l胤o.[n][w][e]

[msg MSG_TUMAARASOI_012_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Los Ladrones Fantasma han enviado[n]el aviso. Las cosas se ponen feas[n]para los mandamases de la empresa.[n][w][e]

[msg MSG_TUMAARASOI_012_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]斡La polic胤a deber胤a espabilar[n]y arrestar a esa panda[n]de delincuentes![n][w][e]

[msg MSG_TUMAARASOI_012_3_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Pensaba que estabas a favor de[n]los Ladrones Fantasma, jo, jo, jo.[n]La cosa est茨 dif胤cil, pero...[n][w][e]

[msg MSG_TUMAARASOI_013_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]斡Todav胤a no me creo que le haya[n]dado un jamacuco a Okumura![n]夷Qu姻 va a ser de la empresa?[n][w][e]

[msg MSG_TUMAARASOI_013_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Rel茨jate, que todo ir茨 bien.[n][w][e]
[s][vp 8 2 1 0 20 0]Aunque, claro, puede que echen[n]a unos cuantos y degraden a otros.[n][w][e]

[msg MSG_TUMAARASOI_013_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Pero 斡acaban de ascender[n]a mi tortolito! 斡Os odio,[n]Ladrones Fantasma![n][w][e]

[msg MSG_TUMAARASOI_014_0_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Okumura Foods est茨 bajo m胤nimos.[n]He o胤do que le han bajado[n]el sueldo a tu marido.[n][w][e]

[msg MSG_TUMAARASOI_014_1_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Me alegro de que la empresa[n]no se haya ido a pique. Adem茨s,[n]tenemos ahorros suficientes.[n][w][e]
[s][vp 8 2 1 0 19 0]夷C吋mo le va al tuyo? Uy, perdona,[n]tal vez sea mejor no preguntar.[n][w][e]

[msg MSG_TUMAARASOI_014_2_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Pues, mira, como arrim吋 el hombro[n]como el que m茨s durante el foll吋n,[n]lo han ascendido. Jo, jo.[n][w][e]

[msg MSG_TUMAARASOI_015_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Los Ladrones Fantasma siguen[n]sueltos. Qu姻 miedo me da estar sola[n]en casa cuando mi marido trabaja...[n][w][e]

[msg MSG_TUMAARASOI_015_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]夷Sola? 夷Y la sirvienta? No me digas[n]que la hab姻is despedido.[n][w][e]

[msg MSG_TUMAARASOI_015_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]No nos qued吋 m茨s remedio.[n]No podemos derrochar el dinero[n]en estos tiempos tan dif胤ciles.[n][w][e]

[msg MSG_TUMAARASOI_015_3_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Te has convertido en una mujer[n]admirable. Dicen que la soberbia[n]precede al fracaso... Jo, jo, jo.[n][w][e]

[msg MSG_TUMAARASOI_016_0_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Shido, el de Futuro Unido,[n]parece un buen hombre.[n]Deber胤a ser primer ministro.[n][w][e]

[msg MSG_TUMAARASOI_016_1_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Jo, jo, jo. Pues yo lo conoc胤[n]en un evento de los amigos[n]de mi churri.[n][w][e]

[msg MSG_TUMAARASOI_016_2_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]夷Lo dices en serio? Lo vi el otro[n]d胤a cuando me apunt姻[n]a una asociaci吋n de apoyo.[n][w][e]
[s][vp 8 2 1 0 20 0]Me dio muy buena impresi吋n.[n]夷Estabas por all胤?[n][w][e]

[msg MSG_TUMAARASOI_017_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 20 0]夷Te has enterado? 斡El l胤der de[n]los Ladrones Fantasma sigue vivo![n][w][e]

[msg MSG_TUMAARASOI_017_1_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 19 0]斡Se tratar茨 de una artima隠a[n]para desacreditar al se隠or Shido![n][w][e]
[s][vp 8 2 1 0 19 0]O eso se comenta en todos[n]los programas, que no es m茨s que[n]un bulo como hay elecciones.[n][w][e]

[msg MSG_TUMAARASOI_018_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]La salud del se隠or Shido[n]me tiene en vilo.[n][w][e]

[msg MSG_TUMAARASOI_018_1_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]S胤, necesitamos que enderece[n]el rumbo del pa胤s. Mi hijo tiene[n]los ex茨menes de acceso al caer.[n][w][e]
[s][vp 8 2 1 0 20 0]Quiero un Jap吋n pr吋spero para 姻l.[n][w][e]

[msg MSG_TUMAARASOI_019_0_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Ah, feliz a隠o nuevo. El anterior[n]estuvo lleno de sorpresas,[n]夷no crees?[n][w][e]

[msg MSG_TUMAARASOI_019_1_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]S胤, la verdad. Menuda sorpresa...[n][w][e]
[s][vp 8 2 1 0 19 0]El negocio ha ido muy bien[n]y mi familia ahora es mucho m茨s[n]estable econ吋micamente.[n][w][e]
[s][vp 8 2 1 0 19 0]Adem茨s, han ascendido[n]a mi marido, por lo que ha estado[n]bastante ocupado...[n][w][e]

[msg MSG_TUMAARASOI_019_2_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]夷C吋mo? No me digas...[n][w][e]
[s][vp 8 2 1 0 20 0]Bueno, tambi姻n han ascendido[n]al m胤o, as胤 que seguramente[n]seguir茨n trabajando juntos.[n][w][e]

[msg MSG_TUMAARASOI_020_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Dicen que este invierno[n]cada vez va a hacer m茨s fr胤o.[n][w][e]
[s][vp 8 2 1 0 19 0]Por eso hemos decidido pasar[n]el invierno en una playa privada en[n]Haw茨i, a partir del mes que viene.[n][w][e]
[s][vp 8 2 1 0 19 0]El invierno es mucho m茨s[n]c茨lido all胤.[n][w][e]

[msg MSG_TUMAARASOI_020_1_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]夷C-c吋mo? Pues s胤 que vais a pasar[n]tiempo all胤.[n][w][e]
[s][vp 8 2 1 0 20 0]斡Pe-pero nosotros tambi姻n[n]tenemos previsto irnos a una playa[n]privada en Guam el mes que viene![n][w][e]
[s][vp 8 2 1 0 20 0]Le han subido el sueldo[n]a mi marido, as胤 que podemos[n]permit胤rnoslo.[n][w][e]

[msg MSG_TUMAARASOI_020_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]斡Anda, qu姻 pasada! Me alegro[n]de que a tu familia le vaya bien.[n][w][e]
[s][vp 8 2 1 0 19 0]Parece que este a隠o[n]tambi姻n va a ser maravilloso.[n][w][e]

[msg MSG_TUMAARASOI_020_3_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]S-s胤... Yo tambi姻n lo creo.[n][w][e]

[msg MSG_TUMAARASOI_021_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]斡Ja! 斡Me ha dicho mi marido que[n]lo han elegido para ser miembro[n]principal del pr吋ximo proyecto![n][w][e]
[s][vp 8 2 1 0 19 0]郁ltimamente todo son[n]buenas noticias.[n][w][e]

[msg MSG_TUMAARASOI_021_1_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]M-me alegro.[n][w][e]
[s][vp 8 2 1 0 20 0]A mi marido tambi姻n le ha ido[n]muy bien. Acaba de cerrar[n]un contrato muy suculento...[n][w][e]
[s][vp 8 2 1 0 20 0]斡Ha-hasta nos estamos planteando[n]construirnos una casa nueva![n][w][e]
[s][vp 8 2 1 0 20 0]斡Es como si la felicidad[n]estuviera de rebajas![n][w][e]

[msg MSG_TUMAARASOI_021_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Vaya, lo has conseguido.[n][w][e]

[msg MSG_TUMAARASOI_021_3_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]夷C吋mo...?[n][w][e]

[msg MSG_TUMAARASOI_021_4_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]O sea, dices que las cosas[n]te van tan bien que no deseas[n]nada m茨s, 夷no?[n][w][e]
[s][vp 8 2 1 0 19 0]Pero creo que deber胤as[n]relajarte un poco.[n][w][e]
[s][vp 8 2 1 0 19 0]A lo mejor te est茨s dejando llevar[n]por la avaricia.[n]Todo depende de c吋mo se mire.[n][w][e]
[s][vp 8 2 1 0 19 0]Puede que logres comprenderme[n]cuando conozcas[n]la verdadera felicidad. Jo, jo, jo.[n][w][e]

[msg MSG_TUMAARASOI_022_0_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]He o胤do que le han impuesto[n]una jubilaci吋n forzosa a tu marido.[n]Debe de haber sido duro.[n][w][e]

[msg MSG_TUMAARASOI_022_1_0 [Ama de casa poco arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Es cierto. Puede que tengamos que[n]mudarnos con mis padres,[n]pero de forma temporal.[n][w][e]

[msg MSG_TUMAARASOI_022_2_0 [Ama de casa poco modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Si alguna vez necesitas algo[n]de la ciudad, p胤demelo sin reparo.[n][w][e]
[s][vp 8 2 1 0 20 0]Seguro que la echar茨s[n]de menos. Jo, jo, jo.[n][w][e]

[msg MSG_TUMAARASOI_0504_0_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 3 10 0 0][vp 8 2 1 0 19 0]Tu hijo estudia en el Shujin, 夷no?[n]Donde arrestaron a aquel profesor...[n][w][e]
[s][vp 8 2 1 0 19 0]Si hubiera sabido[n]lo de ese profesor, lo habr胤a[n]cambiado de centro de inmediato.[n][w][e]
[s][vp 8 2 1 0 19 0]Yo siempre hago que mi hijo[n]lo escriba todo en un diario.[n][w][e]
[s][vp 8 2 1 0 19 0]As胤 me entero de lo que pasa[n]en su instituto.[n][w][e]

[msg MSG_TUMAARASOI_0504_1_0 [Ama de casa modesta]]
[s][f 4 23 1 20 3 10 0 0][vp 8 2 1 0 20 0]Bueno, mi hijo no est茨 en el equipo[n]de voleibol, as胤 que no hay[n]necesidad de que escriba un diario.[n][w][e]

[msg MSG_TUMAARASOI_0504_2_0 [Ama de casa arrogante]]
[s][f 4 23 1 19 20 10 0 10][vp 8 2 1 0 19 0]Las amas de casa somos responsables[n]de criar a ni隠os con futuro.[n]No podemos holgazanear, jo, jo...[n][w][e]

[msg MSG_TOKAISOMARU_001_0_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]夷Se puede saber qu姻 te pasa?[n][w][e]

[msg MSG_TOKAISOMARU_001_1_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Soy tu novio y no permitir姻[n]que te subas a unos trenes[n]que descarrilan cada dos por tres.[n][w][e]
[s][vp 8 2 1 0 22 0]斡Que me tienes preocupado,[n]que la ciudad es un peligro![n][w][e]

[msg MSG_TOKAISOMARU_001_2_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]斡No montes un numerito,[n]que me da verg鵜enza![n][w][e]

[msg MSG_TOKAISOMARU_002_0_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]La ciudad est茨 petada[n]de pervertidos y rufianes.[n]No es para gente como nosotros.[n][w][e]

[msg MSG_TOKAISOMARU_002_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Pero 斡siempre he so隠ado[n]con vivir aqu胤![n][w][e]

[msg MSG_TOKAISOMARU_002_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]夷Lo vas a tirar todo por la borda?[n]夷Qu姻 hay de tus ra胤ces[n]y de tu hogar?[n][w][e]

[msg MSG_TOKAISOMARU_002_3_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Que no, jol胤n.[n]Ya he dicho que ir胤a de visita[n]una vez al a隠o.[n][w][e]

[msg MSG_TOKAISOMARU_003_0_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Las tiendas de autoservicio[n]tienen de todo y...[n]bueno, te sirves t雨 mismo.[n][w][e]

[msg MSG_TOKAISOMARU_003_1_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Pues en el campo,[n]si necesitas algo,[n]se lo pides al vecino y punto.[n][w][e]
[s][vp 8 2 1 0 22 0]斡Te dar姻 una vuelta en coche![n]斡Podr胤a alquilar una limusina o uno[n]de esos de lujo todo guapos![n][w][e]

[msg MSG_TOKAISOMARU_003_2_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Te refieres a un tractor, 夷verdad?[n]Creo que paso, gracias.[n][w][e]

[msg MSG_TOKAISOMARU_004_0_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Fui a la exhibici吋n porque[n]es superfamoso, pero 斡resulta[n]que lo hab胤a plagiado todo![n][w][e]

[msg MSG_TOKAISOMARU_004_1_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]斡Lo sab胤a! 斡Los de la ciudad[n]son una piara[n]de mentirosos y degenerados![n][w][e]
[s][vp 8 2 1 0 22 0]斡Y encima hay unos ladrones[n]sueltos por ah胤![n]Venga, que te llevo a casa.[n][w][e]

[msg MSG_TOKAISOMARU_004_2_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]斡Tampoco exageres, que encima[n]tenemos a los Ladrones Fantasma[n]de nuestro lado![n][w][e]

[msg MSG_TOKAISOMARU_005_0_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]En la tele dicen que hay unos criminales[n]por ah胤 sueltos.[n]Cierra bien la puerta de noche.[n][w][e]

[msg MSG_TOKAISOMARU_005_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Que s胤胤胤, que ya s姻 lo de la mafia.[n]Tranqui, que la ciudad es segura.[n][w][e]

[msg MSG_TOKAISOMARU_005_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Y el campo tambi姻n. 斡Todo gracias[n]a Taro, el vecino![n][w][e]

[msg MSG_TOKAISOMARU_005_3_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]夷Hablas del chucho que juega[n]con cualquiera que se le acerca?[n]S胤, intimida que no veas.[n][w][e]

[msg MSG_TOKAISOMARU_006_0_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Quiero ir a una discoteca[n]a bailar toda la noche[n]y a beberme unos c吋cteles.[n][w][e]

[msg MSG_TOKAISOMARU_006_1_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Pues hace poco fui a un bar[n]muy guapo en Shinjuku.[n][w][e]
[s][vp 8 2 1 0 22 0]La due隠a era la mar de maja.[n]Era el para胤so, te lo juro.[n][w][e]

[msg MSG_TOKAISOMARU_006_2_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]No ser胤a un club de hostesses, 夷no?[n][w][e]

[msg MSG_TOKAISOMARU_007_0_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Ahora que han pillado a la mafia,[n]dormir姻 a pierna suelta. 斡Voy[n]a disfrutar de la ciudad a tope![n][w][e]

[msg MSG_TOKAISOMARU_007_1_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]斡La ciudad no es segura![n]Los Ladrones Fantasma andan por ah胤[n]campando a sus anchas.[n][w][e]
[s][vp 8 2 1 0 22 0]夷Y si te pillan[n]en mitad de la noche?[n]Venga, volvamos a casa.[n][w][e]

[msg MSG_TOKAISOMARU_007_2_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]斡Que cortes el rollo de una vez![n]斡Estoy hasta el gorro de o胤rte[n]hablar del campo![n][w][e]

[msg MSG_TOKAISOMARU_008_0_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Si te quedas aqu胤,[n]esa panda de haraganes[n]te va a fastidiar el ordenador.[n][w][e]

[msg MSG_TOKAISOMARU_008_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Se llaman Medjed y son hackers.[n]Solo van a por empresas,[n]para tu informaci吋n.[n][w][e]

[msg MSG_TOKAISOMARU_008_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Esa actitud te va a dar quebraderos[n]de cabeza. Si quieres,[n]monto guardia esta noche.[n][w][e]

[msg MSG_TOKAISOMARU_008_3_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Vale, vale...[n][w][e]

[msg MSG_TOKAISOMARU_009_0_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Vuelve a casa durante el Obon.[n]Adem茨s, la ciudad no es segura[n]por culpa de los Medjedes esos.[n][w][e]

[msg MSG_TOKAISOMARU_009_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]En internet no importa d吋nde est姻s.[n]Y seguro que los Ladrones Fantasma[n]les dar茨n un buen repaso.[n][w][e]

[msg MSG_TOKAISOMARU_009_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]斡Los Ladrones Fantasma[n]son solo habladur胤as,[n]por eso no han respondido![n][w][e]
[s][vp 8 2 1 0 22 0]斡Espabila, que en la ciudad[n]son todo mentiras![n][w][e]

[msg MSG_TOKAISOMARU_010_0_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Siento haber dicho que[n]los Ladrones Fantasma no exist胤an.[n][w][e]
[s][vp 8 2 1 0 22 0]Est茨 claro que son la leche.[n]Quiero aprender de ellos.[n][w][e]

[msg MSG_TOKAISOMARU_010_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Por fin te has dado cuenta.[n][w][e]

[msg MSG_TOKAISOMARU_010_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Pues claro. Deja que te traiga[n]un regalito del campo[n]para demostrarte que lo siento.[n][w][e]

[msg MSG_TOKAISOMARU_010_3_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Retiro lo dicho.[n]斡No te has coscado de nada![n][w][e]

[msg MSG_TOKAISOMARU_011_0_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]El presidente ese es malo[n]hasta la m姻dula.[n]斡Solo se preocupa de s胤 mismo![n][w][e]

[msg MSG_TOKAISOMARU_011_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Los Ladrones Fantasma[n]le dar茨n para el pelo.[n]Espero que no tarden mucho.[n][w][e]

[msg MSG_TOKAISOMARU_011_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Los bomberos del pueblo[n]ya le habr胤an dado una buena leche.[n][w][e]

[msg MSG_TOKAISOMARU_011_3_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Dejemos ya el temita, anda.[n][w][e]

[msg MSG_TOKAISOMARU_012_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Han dejado un nuevo aviso.[n][w][e]
[s][vp 8 2 1 0 21 0]夷Las hamburguesas[n]ser茨n m茨s baratas si despiertan[n]el coraz吋n del presidente?[n][w][e]

[msg MSG_TOKAISOMARU_012_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Abrieron una hace poco[n]en el pueblo. Pedazo de colas[n]hab胤a, pensaba que era un festival.[n][w][e]
[s][vp 8 2 1 0 22 0]No sab胤a que las hamburguesas[n]del Pin Pon Burger ese[n]estuvieran tan buenas.[n][w][e]

[msg MSG_TOKAISOMARU_013_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Me apetece una hamburguesa,[n]pero, con todo este l胤o, no s姻 yo...[n][w][e]

[msg MSG_TOKAISOMARU_013_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]夷Del Pin Pon Burger?[n]Seguro que la empresa[n]ha pegado un batacazo.[n][w][e]
[s][vp 8 2 1 0 22 0]La cara del presi acojonaba.[n]Los Ladrones Fantasma son lo peor.[n][w][e]

[msg MSG_TOKAISOMARU_014_0_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Los Ladrones Fantasma est茨n en el[n]meollo, 夷no? 夷Y si est茨n escondidos[n]por aqu胤? Qu姻 miedo.[n][w][e]

[msg MSG_TOKAISOMARU_014_1_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Entonces, 夷quieres volver al campo?[n][w][e]

[msg MSG_TOKAISOMARU_014_2_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]No. Me he matado a trabajar,[n]no voy a salir huyendo ahora.[n]Solo espero que los atrapen pronto.[n][w][e]

[msg MSG_TOKAISOMARU_014_3_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Yo te proteger姻.[n]Estamos preocupad胤simos por ti,[n]que lo sepas.[n][w][e]

[msg MSG_TOKAISOMARU_015_0_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]夷Lo has o胤do? Un antiguo compa隠ero[n]del cole se ha presentado[n]a las elecciones.[n][w][e]

[msg MSG_TOKAISOMARU_015_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]斡夷En serio?![n]A lo mejor fue amigo nuestro...[n][w][e]

[msg MSG_TOKAISOMARU_015_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Siempre dec胤a que quer胤a[n]mejorar el pueblo. Tengo entendido[n]que no lo va a tener f茨cil.[n][w][e]

[msg MSG_TOKAISOMARU_016_0_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Da igual las adversidades[n]que se presenten, el suicidio[n]nunca es la soluci吋n.[n][w][e]
[s][vp 8 2 1 0 22 0]Mira que hacerle eso a tus padres...[n]No fastidies, macho.[n][w][e]

[msg MSG_TOKAISOMARU_016_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]S胤, a m胤 tampoco me parece bien.[n]No ten胤a por qu姻 morir.[n][w][e]

[msg MSG_TOKAISOMARU_016_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]斡Pues tambi姻n es culpa nuestra,[n]que hemos soltado mierda[n]por un tubo![n][w][e]

[msg MSG_TOKAISOMARU_016_3_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Es verdad, lo siento...[n]Jol胤n, nunca me hab胤an hablado as胤.[n][w][e]

[msg MSG_TOKAISOMARU_017_0_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]夷Shido es un mal hombre? 夷Debemos[n]confiar en los Ladrones Fantasma?[n][w][e]

[msg MSG_TOKAISOMARU_017_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]De todas formas, tenemos[n]que observar y esperar.[n]No nos queda otra.[n][w][e]

[msg MSG_TOKAISOMARU_017_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]No s姻 qu姻 hacer. Me siento[n]muy perdido en esta jungla[n]de asfalto.[n][w][e]

[msg MSG_TOKAISOMARU_017_3_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Me sorprende[n]que te sientas perdido.[n][w][e]

[msg MSG_TOKAISOMARU_018_0_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]En fin, me vuelvo al pueblo.[n]夷Te quedas en la ciudad?[n][w][e]

[msg MSG_TOKAISOMARU_018_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]夷Qu姻? Pues s胤...[n]夷A qu姻 viene este cambio?[n][w][e]

[msg MSG_TOKAISOMARU_018_2_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Aqu胤 he comprendido que Tokio no[n]es para m胤. Adem茨s, quiero apoyar[n]a nuestro amigo en las elecciones.[n][w][e]

[msg MSG_TOKAISOMARU_018_3_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Entiendo...[n][w][e]

[msg MSG_TOKAISOMARU_019_0_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]夷Puedes repetir[n]lo que acabas de decir?[n][w][e]

[msg MSG_TOKAISOMARU_019_1_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]He dicho que deber胤amos vivir[n]juntos en Tokio.[n][w][e]
[s][vp 8 2 1 0 22 0]A ti te gusta y a m胤 tambi姻n.[n][w][e]
[s]Adem茨s, tenemos los mismos valores.[n]夷No te parece buena idea?[n][w][e]

[msg MSG_TOKAISOMARU_019_2_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]A ver, 夷qu姻 mosca te ha picado?[n][w][e]
[s][vp 8 2 1 0 21 0]Hablas y te comportas como[n]si no fueras t雨. Menudo l胤o tengo.[n][w][e]

[msg MSG_TOKAISOMARU_020_0_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]夷Puedes repetir lo que has dicho?[n][w][e]

[msg MSG_TOKAISOMARU_020_1_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Digo que deber胤amos vivir[n]en una de esas mansiones de dise隠o.[n][w][e]
[s][vp 8 2 1 0 22 0]Podemos hacerla acogedora y[n]femenina... 夷No es lo que quieres?[n][w][e]

[msg MSG_TOKAISOMARU_020_2_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]B-bueno, es lo que siempre[n]he querido, pero...[n][w][e]
[s][vp 8 2 1 0 21 0]夷C吋mo sabes todo eso?[n][w][e]

[msg MSG_TOKAISOMARU_020_3_0 [Zagal]]
[s][f 4 23 1 22 3 10 0 0][vp 8 2 1 0 22 0]Hoy en d胤a es importante[n]ampliar horizontes y no dejar[n]de aprender cosas nuevas.[n][w][e]
[s][vp 8 2 1 0 22 0]As胤 puedo disfrutar de una vida[n]feliz en la ciudad contigo.[n][w][e]

[msg MSG_TOKAISOMARU_021_0_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0]...[n][w][e]
[s][vp 8 2 1 0 21 0]Siempre he so隠ado con vivir[n]una vida as胤 en Tokio. Y ahora[n]puedo hacerlo con 姻l...[n][w][e]
[s][vp 8 2 1 0 21 0]Todo va a pedir de boca, pero...[n][w][e]
[s][vp 8 2 1 0 21 0]*suspiro* 夷Por qu姻 me siento[n]tan triste de repente?[n][w][e]

[msg MSG_TOKAISOMARU_021_1_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Todo el mundo parece muy feliz[n]desde que empez吋 el a隠o.[n][w][e]
[s][vp 8 2 1 0 21 0]Pero entonces, 夷por qu姻[n]siento esta tristeza?[n][w][e]

[msg MSG_TOKAISOMARU_022_0_0 [Mujer adorable]]
[s][f 4 23 1 21 3 10 0 0][vp 8 2 1 0 21 0]Cu茨nta tranquilidad hay en Tokio...[n][w][e]
[s][vp 8 2 1 0 21 0]O puede que antes hubiese[n]demasiado ruido, a saber.[n][w][e]
[s][vp 8 2 1 0 21 0]Es cierto que hay cosas que solo[n]puedo hacer en la ciudad,[n]pero me falta algo.[n][w][e]
[s][vp 8 2 1 0 21 0]Tal vez deber胤a volver[n]a casa yo tambi姻n.[n][w][e]

[msg Quest05_target_00_00 [Mitsumi Kure]]
[s][vp 8 2 1 0 600 0]Perdone, pero ten胤a una queja[n]importante sobre su curry picante.[n][w][e]
[s][vp 8 2 1 0 600 0]斡Pica demasiado![n]Lo he pasado muy mal.[n][w][e]
[s][vp 8 2 1 0 600 0]Tengo la boca llena de quemaduras y[n]estoy peor de la estomatitis por[n]culpa del curry. No puedo ni comer...[n][w][e]
[s][vp 8 2 1 0 600 0]斡Ay! 斡Ah! Me duele un mont吋n...[n]No creo que deban andar[n]sirviendo esto a sus clientes.[n][w][e]
[s][vp 8 2 1 0 600 0]Quiero una disculpa y que se me[n]devuelva el dinero.[n]Llame al encargado, 斡rapidito![n][w][e]
[s][vp 8 2 1 0 600 0]夷Qu姻? Me llamo Mitsumi.[n]斡Mitsumi Kure![n][w][e]

[msg MSG_quest05_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Creo que ya tenemos al objetivo.[n]斡Hay que pensar un buen plan[n]en el escondite![n][w][e]

[msg HELP_MEMENTOS_MISSION_02 [斡Misi吋n actualizada!]]
[s]或[clr 4]Suceso en Mementos[clr 27]位[n]Objetivo identificado.[n]Habl姻moslo en el [clr 2]escondite[clr 27].[n][w][e]

[msg Quest05_target_01_00 [Mitsumi Kure]]
[s][vp 8 2 1 0 600 0]Por esto tengo tantos problemas con[n]los empleados del sector servicios.[n]Espere, que tengo pruebas.[n][w][e]
[s][vp 8 2 1 0 600 0]Encontr姻 este mensaje de broma[n]en mi bolso que parece un aviso[n]por haber cometido un delito.[n][w][e]
[s][vp 8 2 1 0 600 0]Compr姻 el bolso aqu胤, as胤 que[n]han tenido que ser ustedes.[n]斡Ya pueden disculparse![n][w][e]

[msg Quest05_target_02_00 [Mitsumi Kure]]
[s][vp 8 2 1 0 600 0]Siento lo de la 雨ltima vez y las[n]quejas por mi estomatitis[n]y todo ese asunto.[n][w][e]
[s][vp 8 2 1 0 600 0]Me gustar胤a disculparme[n]sinceramente por todas las quejas[n]que present姻.[n][w][e]
[s][vp 8 2 1 0 600 0]En realidad, el curry picante[n]estaba buen胤simo.[n][w][e]
[s][vp 8 2 1 0 600 0]Ya ten胤a problemas de hinchaz吋n[n]en la boca. Fue culpa m胤a que[n]fueran a peor. Qu姻 verg鵜enza...[n][w][e]
[s][vp 8 2 1 0 600 0]Hoy he venido a expresar[n]mi m茨s sincera gratitud.[n][w][e]
[s][vp 8 2 1 0 600 0]El curry de este restaurante[n]est茨 a otro nivel en comparaci吋n[n]con los dem茨s que he probado.[n][w][e]
[s][vp 8 2 1 0 600 0]Me muero de ganas de que a隠adan[n]platos nuevos al men雨.[n][w][e]

[msg Quest09_target_00_00 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]Ya te lo he dicho, quedamos un[n]ratito de nada. 斡Ya sabes que yo[n]nunca te enga隠ar胤a![n][w][e]

[msg Quest09_target_00_01 [Hombre a punto de llorar y demandar]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]斡No te hagas la tonta! S姻 que me[n]has enga隠ado con un mont吋n[n]de gente, 斡incluidos mis amigos![n][w][e]
[s][vp 8 2 1 0 602 0]斡La agencia de investigadores[n]que contrat姻 me ha dado[n]grabaciones incriminatorias![n][w][e]

[msg Quest09_target_00_02 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 65535 0 0 0]...[n][w][e]
[s][vp 8 2 1 0 601 0]夷Y qu姻 hay de malo en que una mujer[n]busque el amor? Es culpa tuya,[n]que no me mereces.[n][w][e]
[s][vp 8 2 1 0 601 0]Venga, den雨nciame si te atreves.[n]En mi familia hay muchos[n]abogados, as胤 que buena suerte.[n][w][e]

[msg Quest09_target_00_03 [Hombre a punto de llorar y demandar]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]夷Eh? 斡夷Est茨s de co隠a?! 斡No pienso[n]dejar que te salgas con la tuya![n][w][e]

[msg Quest09_target_sinjyo_00]
[s][vp 8 2 65535 0 0 0]Un comportamiento intolerable.[n][w][e]

[msg MSG_quest09_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]斡Parece que hemos encontrado[n]al objetivo! 斡Vamos a hablarlo[n]con los dem茨s en el escondite![n][w][e]

[msg Quest09_target_01_00 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]斡夷Y esto?! Como sabes que perder茨s[n]el juicio, me vienes con trucos[n]sucios, como este aviso.[n][w][e]

[msg Quest09_target_01_01 [Hombre a punto de llorar y demandar]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]夷Q-qu姻? 斡No he sido yo![n][w][e]
[s][vp 8 2 1 0 602 0]斡Seguro que son los Ladrones[n]Fantasma! Al parecer van por ah胤[n]despertando corazones.[n][w][e]

[msg Quest09_target_01_02 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]斡夷C吋mo te atreves a mentirme?![n]Solo van a por gente que ha[n]cometido delitos de verdad.[n][w][e]
[s][vp 8 2 1 0 601 0]Yo no he hecho nada malo.[n]斡Soy buena persona![n][w][e]

[msg Quest09_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece que el aviso[n]ha llegado a su destino.[n][w][e]

[msg Quest09_target_02_00 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]E-eh...[n]Por favor, esc雨chame.[n][w][e]

[msg Quest09_target_02_01 [Hombre de mirada fr胤a]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]Anda, 斡夷qu姻 quieres?! Si te crees[n]que me vas a enga隠ar haciendo[n]como que lloras, vas lista.[n][w][e]

[msg Quest09_target_02_02 [Sachiko Kuwai]]
[s][f 4 23 1 601 3 10 0 0][vp 8 2 1 0 601 0]斡No, de verdad! Siento mucho[n]haberte enga隠ado en el pasado.[n][w][e]
[s][vp 8 2 1 0 601 0]Te pagar姻 lo que haga falta[n]para que te sientas mejor.[n]斡Lo que haga falta![n][w][e]
[s][vp 8 2 1 0 601 0]Por favor, perd吋name.[n][w][e]

[msg Quest09_target_02_03 [Hombre de mirada fr胤a]]
[s][f 4 23 1 602 3 10 0 0][vp 8 2 1 0 602 0]夷Qu姻 narices...?[n]Ya es un poco tarde como para[n]que me vengas con eso.[n][w][e]
[s][vp 8 2 1 0 602 0]Ya veo que los Ladrones Fantasma[n]han despertado tu coraz吋n.[n]Ahora que te han salvado...[n][w][e]
[s][vp 8 2 1 0 602 0]Lo 雨nico que te pido es que te[n]busques un buen novio al que serle[n]fiel, y que se茨is felices.[n][w][e]

[msg Quest09_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]La misi吋n ha sido todo un 姻xito.[n][w][e]

[msg Quest14_target_00_00 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]En la zona de siempre, delante de[n]la entrada. 斡A estas alturas, ya[n]deber胤as saberlo, vieja bruja![n][w][e]
[s][vp 8 2 1 0 605 0]Mira, solo necesito algo m茨s de[n]pasta y acabar姻 forrado.[n]斡Cierra el pico y ve desembolsando![n][w][e]
[s][vp 8 2 1 0 605 0]Anda, que s姻 que acabas de cobrar[n]la pensi吋n.[n][w][e]
[s][vp 8 2 1 0 605 0]斡Venga, date prisa y ve a por[n]el dinero! 斡Y no me mires as胤![n][w][e]
[s][vp 8 2 1 0 605 0]Pf, ni que fuera tanto pedir.[n]Una buena madre ayuda a su hijo[n]cuando hace falta sin poner pegas.[n][w][e]

[msg Quest14_target_sinjyo_00]
[s][vp 8 2 65535 0 0 0]Qu姻 asco de t胤o.[n][w][e]

[msg MSG_quest14_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]斡Parece que hemos encontrado[n]al objetivo! 斡Vamos a hablarlo[n]con los dem茨s en el escondite![n][w][e]

[msg Quest14_target_01_00 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]夷Un aviso?[n]夷Y eso qu姻 co隠o es?[n][w][e]

[msg Quest14_target_01_01 [Hombre a punto de llorar y demandar]]
[s][vp 8 2 1 0 605 0]Pon胤a tu nombre...[n][w][e]

[msg Quest14_target_01_02 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]夷Qu姻 haces tray姻ndome[n]cosas turbias, arp胤a?[n][w][e]
[s][vp 8 2 1 0 605 0]斡Que me des la pasta![n][w][e]

[msg Quest14_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece que el aviso[n]ha llegado a su destino.[n][w][e]

[msg Quest14_target_02_00 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Mam茨, voy a empezar a trabajar[n]de empleado interno.[n][w][e]
[s][vp 8 2 1 0 605 0]Le he explicado la situaci吋n a mi[n]jefe, y ha dicho que se encargar茨[n]de ayudarme.[n][w][e]

[msg Quest14_target_02_01 [Madre de Daichi]]
[s][vp 8 2 1 0 605 0]夷De verdad? 斡Cu茨nto me alegro![n][w][e]
[s][vp 8 2 1 0 605 0]Aunque me da un poco de pena.[n]Me quedar姻 sola en casa...[n][w][e]

[msg Quest14_target_02_02 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Ir姻 a visitarte.[n][w][e]
[s][vp 8 2 1 0 605 0]Y no te preocupes, que te devolver姻[n]hasta el 雨ltimo yen.[n][w][e]

[msg Quest14_target_02_03 [Madre de Daichi]]
[s][vp 8 2 1 0 605 0]No te preocupes por eso.[n][w][e]
[s][vp 8 2 1 0 605 0]Yo solo quiero que seas feliz.[n][w][e]

[msg Quest14_target_02_04 [Daichi Nakamura]]
[s][vp 8 2 1 0 605 0]Mam茨...[n][w][e]

[msg Quest14_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]La misi吋n ha sido todo un 姻xito.[n][w][e]

[msg Quest15_target_00_00 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]Les pido que se aparten[n]y me contestan con descaro.[n]Los j吋venes no tienen verg鵜enza.[n][w][e]

[msg Quest15_target_00_01 [Nieto de Muneo]]
[s][f 4 23 1 604 3 10 0 0][vp 8 2 1 0 604 0]Abuelo, ya te he dicho que no[n]me importa estar de pie.[n][w][e]

[msg Quest15_target_00_02 [Muneo Horiguchi]]
[s][vp 8 2 1 0 603 0]Eso no es lo importante. Deber胤an[n]cederme el sitio si se lo pido.[n][w][e]

[msg Quest15_target_00_03 [Nieto de Muneo]]
[s][vp 8 2 1 0 604 0]Pero ya nos dijo pap茨 que andar[n]gritando a la gente est茨 mal.[n][w][e]

[msg Quest15_target_00_04 [Muneo Horiguchi]]
[s][vp 8 2 1 0 603 0]No, 斡si esto es cuesti吋n de 姻tica[n]y disciplina! Alguien tiene que[n]ense隠arles a comportarse.[n][w][e]

[msg Quest15_target_00_05 [Nieto de Muneo]]
[s][vp 8 2 1 0 604 0]Todo el mundo nos miraba[n]con mala cara.[n][w][e]

[msg Quest15_target_00_06 [Muneo Horiguchi]]
[s][vp 8 2 1 0 603 0]斡Insensatos![n][w][e]
[s][vp 8 2 1 0 603 0]斡Nosotros somos los que hemos[n]forjado el Jap吋n de hoy en d胤a[n]con sudor y sangre![n][w][e]
[s][vp 8 2 1 0 603 0]夷Por qu姻 se creen que viven[n]en paz? Los j吋venes no tienen[n]derecho a quejarse.[n][w][e]
[s][vp 8 2 1 0 603 0]Y tienen el morro de negarse[n]a cederme el asiento. 夷No les han[n]ense隠ado lo que es el respeto?[n][w][e]

[msg MSG_quest15_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]斡Parece que hemos encontrado[n]al objetivo! 斡Vamos a hablarlo[n]con los dem茨s en el escondite![n][w][e]

[msg Quest15_target_01_00 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]夷Mm? 夷Un aviso?[n]No me lo puedo creer.[n][w][e]
[s][vp 8 2 1 0 603 0]夷Qu姻 clase de ni隠ato descarado[n]se atreve a tomarme el pelo[n]de esta manera?[n][w][e]

[msg Quest15_target_sinjyo_01]
[s][vp 8 2 65535 0 0 0]Parece que el aviso[n]ha llegado a su destino.[n][w][e]

[msg Quest15_target_02_00 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]Mi nieto ya no quiere saber nada de[n]m胤. Ni siquiera viene a visitarme.[n][w][e]
[s][vp 8 2 1 0 603 0]Se ha hartado de estar conmigo[n]porque me paso el d胤a quej茨ndome.[n][w][e]
[s][vp 8 2 1 0 603 0]Mi familia me ha dicho que soy muy[n]testarudo, que no supe ense隠arles[n]a tener empat胤a.[n][w][e]

[msg Quest15_target_02_01 [Anciano risue隠o]]
[s][f 4 23 1 604 3 10 0 0][vp 8 2 1 0 604 0]La edad hace a uno m茨s sabio,[n]s胤, pero no perfecto.[n][w][e]
[s][vp 8 2 1 0 604 0]Siempre has sido bastante tosco...[n][w][e]
[s][vp 8 2 1 0 604 0]La verdad es que yo tambi姻n[n]me plante姻 distanciarme de ti[n]en alguna que otra ocasi吋n.[n][w][e]

[msg Quest15_target_02_02 [Muneo Horiguchi]]
[s][f 4 23 1 603 3 10 0 0][vp 8 2 1 0 603 0]Hay tantas cosas que hab胤a[n]entendido mal... No me puedo creer[n]que me est姻 dando cuenta a mi edad.[n][w][e]
[s][vp 8 2 1 0 603 0]No me queda mucho tiempo para[n]empezar de nuevo, pero har姻[n]lo que pueda por mejorar.[n][w][e]
[s][vp 8 2 1 0 603 0]Empezar姻 por apuntarme al Centro[n]Silver de Recursos Humanos.[n][w][e]
[s][vp 8 2 1 0 603 0]Si consigo ser 雨til y encuentro[n]un prop吋sito, podr姻 vivir mi vida[n]de otra manera.[n][w][e]

[msg Quest15_target_sinjyo_02]
[s][vp 8 2 65535 0 0 0]Su introspecci吋n demuestra[n]que ha despertado.[n][w][e]

[msg quest23_hint_talk_00 [ヒント23]]
[s]クエスト23のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest23_hint_sinjyo]
[s]クエスト23のテスト心情メッセージです。[n][w][e]

[msg MSG_quest23_morgana_00 [Morgana]]
[s]クエスト23のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg quest26_hint_talk_00 [ヒント26]]
[s]クエスト26のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest26_hint_sinjyo]
[s]クエスト26のテスト心情メッセージです。[n][w][e]

[msg MSG_quest26_morgana_00 [Morgana]]
[s]クエスト26のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg quest37_hint_talk_00 [ヒント37]]
[s]クエスト37のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest37_hint_sinjyo]
[s]クエスト37のテスト心情メッセージです。[n][w][e]

[msg MSG_quest37_morgana_00 [Morgana]]
[s]クエスト37のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg quest42_hint_talk_00 [ヒント42]]
[s]クエスト42のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest42_hint_sinjyo]
[s]クエスト42のテスト心情メッセージです。[n][w][e]

[msg MSG_quest42_morgana_00 [Morgana]]
[s]クエスト42のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg Quest44_target_00_00 [ターゲット44]]
[s][f 4 23 1 614 3 10 0 0]クエスト44のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest44_target_sinjyo_00]
[s]クエスト44のテスト心情メッセージです。[n][w][e]

[msg MSG_quest44_morgana_01 [Morgana]]
[s]クエスト44のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest44_target_01_00 [ターゲット44]]
[s][f 4 23 1 614 3 10 0 0]クエスト44のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest44_target_sinjyo_01]
[s]クエスト44のテスト心情メッセージです。[n][w][e]

[msg Quest44_target_02_00 [ターゲット44]]
[s][f 4 23 1 614 3 10 0 0]クエスト44のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest44_target_sinjyo_02]
[s]クエスト44のテスト心情メッセージです。[n][w][e]

[msg Quest46_target_00_00 [ターゲット46]]
[s][f 4 23 1 616 3 10 0 0]クエスト46のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest46_target_sinjyo_00]
[s]クエスト46のテスト心情メッセージです。[n][w][e]

[msg MSG_quest46_morgana_01 [Morgana]]
[s]クエスト46のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest46_target_01_00 [ターゲット46]]
[s][f 4 23 1 616 3 10 0 0]クエスト46のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest46_target_sinjyo_01]
[s]クエスト46のテスト心情メッセージです。[n][w][e]

[msg Quest46_target_02_00 [ターゲット46]]
[s][f 4 23 1 616 3 10 0 0]クエスト46のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest46_target_sinjyo_02]
[s]クエスト46のテスト心情メッセージです。[n][w][e]

[msg JUICE_SHOP_NOTOPEN [Ayudante]]
[s][vp 8 2 1 0 2 0]Lo siento, seguimos de reformas.[n][w][e]
[s][vp 8 2 1 0 2 0]○日になったらオープンしますので[n]また来てください![n][w][e]

[msg JUICE_SHOP_SELECT [Ayudante]]
[s][vp 8 2 1 0 2 0]斡Bienvenido! Nuestro zumo de bayas[n]variadas est茨 de oferta hoy[n]a un precio muy, muy reducido.[n][w][e]
[s][vp 8 2 1 0 2 0]夷Le gustar胤a pedir uno?[n][w][e]

[msg JUICE_SHOP_THANKS [Ayudante]]
[s][vp 8 2 1 0 2 0]斡Muchas gracias! 斡Esperamos[n]volver a verle muy, muy pronto![n][w][e]

[msg JUICE_SHOP_NOT_BUY [Ayudante]]
[s][vp 8 2 1 0 2 0]斡Vuelva pronto![n][w][e]

[msg JUICE_SHOP_SOLDOUT [Ayudante]]
[s][vp 8 2 1 0 2 0]Lo siento mucho...[n]Se nos ha agotado...[n]todo.[n][w][e]

[msg MSG_01030108_MAKOTO_01 [Sae]]
[s][bup 0 105 0 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 25 1 65535 0 0]Ah...[n][f 1 3 65535][w][e]

[msg MSG_01030108_MAKOTO_02 [Makoto]]
[s][bup 0 6 0 6 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 25 1 65535 0 0]Anda, [f 4 2], qu姻 casualidad.[n][f 1 3 65535][w][e]

[msg MSG_GRT_main_All_001_01_ [Makoto]]
[s][vp 9 2 65535 38752 0 0]Nunca pasa nada bueno...[n]Alguien deber胤a hacer[n]algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_02_ [Makoto]]
[s][vp 9 2 65535 41352 0 0]Espero que jam茨s vuelva a ocurrir[n]algo tan raro...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_03_ [Makoto]]
[s][vp 9 2 65535 38355 0 0]Han estado sembrando el p茨nico[n]y nadie sabe por qu姻.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_04_ [Makoto]]
[s][vp 9 2 65535 41655 0 0]夷Esta gente est茨 como loca[n]a causa del estr姻s?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_05_ [Makoto]]
[s][vp 9 2 65535 38805 0 0]Pf, qu姻 co隠azo tener que ir[n]a trabajar... A lo mejor digo[n]que me he puesto malo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]Esto es aburrid胤simo...[n]Quiero ir a alg雨n sitio divertido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_07_ [Makoto]]
[s][vp 9 2 65535 46052 0 0]夷Por qu姻 no pasa nunca nada bueno?[n]Que alguien tome cartas[n]en el asunto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_08_ [Makoto]]
[s][vp 9 2 65535 45152 0 0]Todo es tan aburrido...[n]夷Cu茨ndo tendremos buenas noticias?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_09_ [Makoto]]
[s][vp 9 2 65535 37909 0 0]Quiero volverme rico r茨pido.[n]夷C吋mo podr胤a conseguirlo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_10_ [Makoto]]
[s][vp 9 2 65535 38710 0 0]Pf, qu姻 co隠azo tener que ir[n]a trabajar... A lo mejor digo[n]que me he puesto malo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_11_ [Makoto]]
[s][vp 9 2 65535 44755 0 0]No va a cambiar nada,[n]as胤 que paso de tomarme[n]las cosas en serio.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_12_ [Makoto]]
[s][vp 9 2 65535 41555 0 0]Todo es tan aburrido...[n]夷Cu茨ndo tendremos buenas noticias?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_13_ [Makoto]]
[s][vp 9 2 65535 37552 0 0]Pf, qu姻 co隠azo tener que ir[n]a trabajar... A lo mejor digo[n]que me he puesto malo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_14_ [Makoto]]
[s][vp 9 2 65535 43952 0 0]Nunca pasa nada bueno...[n]Alguien deber胤a hacer[n]algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_15_ [Makoto]]
[s][vp 9 2 65535 39305 0 0]Todo es tan aburrido...[n]夷Cu茨ndo tendremos buenas noticias?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_16_ [Makoto]]
[s][vp 9 2 65535 41110 0 0]No va a cambiar nada,[n]as胤 que paso de tomarme[n]las cosas en serio.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_01_ [Makoto]]
[s][vp 9 2 65535 37902 0 0]夷A雨n no se sabe la causa?[n]Venga ya, hombre...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_02_ [Makoto]]
[s][vp 9 2 65535 42709 0 0]Las ventas siguen cayendo[n]en picado... Nadie vale para nada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_03_ [Makoto]]
[s][vp 9 2 65535 40605 0 0]Dicen que montan en c吋lera[n]como si estuvieran pose胤dos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_04_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Da igual qui姻n, pero que alguien[n]haga algo ya mismo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_05_ [Makoto]]
[s][vp 9 2 65535 38201 0 0]Esto es aburrid胤simo...[n]Quiero ir a alg雨n sitio divertido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_06_ [Makoto]]
[s][vp 9 2 65535 41855 0 0]Los pol胤ticos no sirven para nada.[n]Da igual qui姻n ostente el poder[n]porque son todos iguales.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_07_ [Makoto]]
[s][vp 9 2 65535 41005 0 0]No va a cambiar nada,[n]as胤 que paso de tomarme[n]las cosas en serio.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_08_ [Makoto]]
[s][vp 9 2 65535 46052 0 0]Este mundo es horroroso...[n]夷De qui姻n ser茨 la culpa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_09_ [Makoto]]
[s][vp 9 2 65535 39052 0 0]Cuando me entero de que va[n]a ocurrir algo, me estreso mucho.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_10_ [Makoto]]
[s][vp 9 2 65535 43055 0 0]夷Est茨 exagerando la gente?[n]Al final, se solucionar茨 todo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_11_ [Makoto]]
[s][vp 9 2 65535 42955 0 0]Tiene que ser cosa de fantasmas.[n]夷No es espeluznante?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_12_ [Makoto]]
[s][vp 9 2 65535 43454 0 0]夷Nadie sabe qu姻 caus吋[n]ese accidente tan extra隠o?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_13_ [Makoto]]
[s][vp 9 2 65535 42659 0 0]Este mundo es horroroso...[n]夷De qui姻n ser茨 la culpa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_14_ [Makoto]]
[s][vp 9 2 65535 40702 0 0]Todos los d胤as me aburro como[n]una ostra. 夷Es que no hay nada[n]con lo que entretenerse?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_15_ [Makoto]]
[s][vp 9 2 65535 39360 0 0]Es dif胤cil motivarse cuando[n]sabes que no vas a recibir[n]ning雨n aumento.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_16_ [Makoto]]
[s][vp 9 2 65535 43802 0 0]Las ventas est茨n cayendo en picado.[n]Ser茨 porque la econom胤a[n]no va bien, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_01_ [Makoto]]
[s][vp 9 2 65535 39109 0 0]Qu姻 rabia que el medallista de oro[n]fuera un pervertido de tomo y lomo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_02_ [Makoto]]
[s][vp 9 2 65535 43405 0 0]Jol胤n, si ten胤a pensado confesar,[n]夷para qu姻 lo hace?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_03_ [Makoto]]
[s][vp 9 2 65535 38652 0 0]Se aprovechaba[n]de las chicas del equipo.[n]Qu姻 asco de t胤o...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_04_ [Makoto]]
[s][vp 9 2 65535 40051 0 0]No me puedo creer que acosara[n]sexualmente a esas chicas.[n]Mira que abusar as胤 de su poder...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_05_ [Makoto]]
[s][vp 9 2 65535 37904 0 0]夷Han detenido a un profesor[n]por pervertido? 斡夷En serio?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_06_ [Makoto]]
[s][vp 9 2 65535 45301 0 0]Jol胤n, si ten胤a pensado confesar,[n]夷para qu姻 lo hace?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_07_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]Se aprovechaba[n]de las chicas del equipo.[n]Qu姻 asco de t胤o...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_08_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]S胤, ha confesado los delitos, pero[n]sigo sin entender qu姻 ha pasado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_09_ [Makoto]]
[s][vp 9 2 65535 38152 0 0]Jol胤n, si ten胤a pensado confesar,[n]夷para qu姻 lo hace?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_10_ [Makoto]]
[s][vp 9 2 65535 42703 0 0]Qu姻 rabia que el medallista de oro[n]fuera un pervertido de tomo y lomo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_11_ [Makoto]]
[s][vp 9 2 65535 46351 0 0]No me puedo creer que acosara[n]sexualmente a esas chicas.[n]Menuda forma de abusar de su poder.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_12_ [Makoto]]
[s][vp 9 2 65535 44751 0 0]Se aprovechaba[n]de las chicas del equipo.[n]Qu姻 asco de t胤o...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_13_ [Makoto]]
[s][vp 9 2 65535 38152 0 0]Medallista de oro o no,[n]hasta aqu胤 ha llegado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_14_ [Makoto]]
[s][vp 9 2 65535 45304 0 0]Jol胤n, si ten胤a pensado confesar,[n]夷para qu姻 lo hace?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_15_ [Makoto]]
[s][vp 9 2 65535 46405 0 0]夷Por qu姻 lo confiesa todo[n]de repente? No lo entiendo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_16_ [Makoto]]
[s][vp 9 2 65535 41001 0 0]Se aprovechaba[n]de las chicas del equipo.[n]Qu姻 asco de t胤o...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_01_ [Makoto]]
[s][vp 9 2 65535 39105 0 0]No me interesa mucho el arte,[n]pero creo que es famoso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_02_ [Makoto]]
[s][vp 9 2 65535 45650 0 0]Lo he visto por la tele.[n]Su arte es bastante bueno.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_03_ [Makoto]]
[s][vp 9 2 65535 41404 0 0]斡Dicen que es conocido[n]en todo el mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_04_ [Makoto]]
[s][vp 9 2 65535 46053 0 0]He visto sus cuadros en la tele.[n]Eran impresionantes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_05_ [Makoto]]
[s][vp 9 2 65535 38200 0 0]Seguro que los artistas ganan[n]mucho dinero. Puede que[n]me convierta en uno alg雨n d胤a.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_06_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Lo he visto por la tele.[n]Su arte es bastante bueno.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_07_ [Makoto]]
[s][vp 9 2 65535 45753 0 0]Es muy popular. Quiz茨 yo tambi姻n[n]deber胤a hacerme artista.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_08_ [Makoto]]
[s][vp 9 2 65535 41300 0 0]斡Su obra goza de gran[n]reconocimiento en todo el mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_09_ [Makoto]]
[s][vp 9 2 65535 46305 0 0]Yo paso del arte y esos rollos,[n]pero dicen que es muy famoso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_10_ [Makoto]]
[s][vp 9 2 65535 46303 0 0]Lo he visto por la tele.[n]Su arte es bastante bueno.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_11_ [Makoto]]
[s][vp 9 2 65535 38259 0 0]Seguro que sus obras[n]se venden por una pasta...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_12_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]斡Su obra goza de gran[n]reconocimiento en todo el mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_13_ [Makoto]]
[s][vp 9 2 65535 45654 0 0]夷Has o胤do hablar de Madarame?[n]Por lo visto, es un artista famoso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_14_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Lo he visto por la tele.[n]Su arte es bastante bueno.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_15_ [Makoto]]
[s][vp 9 2 65535 40854 0 0]斡Dicen que es conocido[n]en todo el mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_16_ [Makoto]]
[s][vp 9 2 65535 40410 0 0]Fijo que ese artista[n]se est茨 forrando.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_01_ [Makoto]]
[s][vp 9 2 65535 42255 0 0]夷Crees que las victimas tienen[n]culpa de caer en las estafas?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_02_ [Makoto]]
[s][vp 9 2 65535 41352 0 0]S姻 que es peligroso salir,[n]pero tengo que ir a trabajar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_03_ [Makoto]]
[s][vp 9 2 65535 44502 0 0]Dicen que no es seguro. Espero que[n]a alguien se le ocurra una forma[n]de resolver esto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_04_ [Makoto]]
[s][vp 9 2 65535 46105 0 0]夷Ser茨 cierto todo lo que comentan[n]sobre estafas y amenazas?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_05_ [Makoto]]
[s][vp 9 2 65535 45802 0 0]Dicen que, como hagas clic,[n]est茨s condenado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]Comentan que la mafia[n]de Shibuya es enorme.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_07_ [Makoto]]
[s][vp 9 2 65535 41452 0 0]夷Son ciertos los rumores[n]de extorsi吋n y fraude?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_08_ [Makoto]]
[s][vp 9 2 65535 43852 0 0]夷Soy yo, o cada vez hay m茨s gente[n]con mala pinta por aqu胤?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_09_ [Makoto]]
[s][vp 9 2 65535 43704 0 0]La inseguridad de Shibuya[n]es algo reciente, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_10_ [Makoto]]
[s][vp 9 2 65535 38502 0 0]Dicen que la mayor胤a[n]de las v胤ctimas son j吋venes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_11_ [Makoto]]
[s][vp 9 2 65535 44759 0 0]He recibido otro correo extra隠o.[n]Qu姻 pesados son...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_12_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]夷Crees que esas amenazas[n]van en serio?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_13_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]Dicen que los hilos los mueve[n]una gran organizaci吋n.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_14_ [Makoto]]
[s][vp 9 2 65535 39152 0 0]Dicen que, como vayan a por ti,[n]est茨s acabado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_15_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]A veces veo matones[n]merodeando por aqu胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_16_ [Makoto]]
[s][vp 9 2 65535 37952 0 0]Ya no puedo pasear[n]tranquilo por la calle.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_01_ [Makoto]]
[s][vp 9 2 65535 44405 0 0]He o胤do que despu姻s de un episodio[n]de descontrol sufres[n]una muerte cerebral.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_02_ [Makoto]]
[s][vp 9 2 65535 44704 0 0]Esos casos ocurrieron uno tras[n]otro. 夷Ha sido una coincidencia?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_03_ [Makoto]]
[s][vp 9 2 65535 38602 0 0]Espero que no haya[n]m茨s incidentes raros...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_04_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_05_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_06_ [Makoto]]
[s][vp 9 2 65535 39155 0 0]Entonces, 夷que la gente perdiera[n]el conocimiento era mentira?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_07_ [Makoto]]
[s][vp 9 2 65535 41154 0 0]Quiz茨s ya no tengamos[n]que preocuparnos m茨s[n]por esos accidentes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_08_ [Makoto]]
[s][vp 9 2 65535 41155 0 0]Seguro que la gente se inventaba[n]lo que quer胤a sobre[n]las desconexiones mentales.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_09_ [Makoto]]
[s][vp 9 2 65535 41610 0 0]Qu姻 raro que haya dejado[n]de haber accidentes[n]de la noche a la ma隠ana.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_10_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_11_ [Makoto]]
[s][vp 9 2 65535 43200 0 0]Supongo que ya no hay tanta gente[n]que pueda causarlos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_12_ [Makoto]]
[s][vp 9 2 65535 39655 0 0]Hasta hace poco, ocurr胤an muchos[n]de esos incidentes tan raros.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_13_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_14_ [Makoto]]
[s][vp 9 2 65535 40705 0 0]A lo mejor vuelven a ocurrir cuando[n]empecemos a olvidarnos de ellos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_15_ [Makoto]]
[s][vp 9 2 65535 45104 0 0]夷Ese accidente de metro no ocurri吋[n]a principios de abril?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_16_ [Makoto]]
[s][vp 9 2 65535 39709 0 0]斡El que provoque los accidentes[n]debe cargar con la culpa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_01_ [Makoto]]
[s][vp 9 2 65535 42554 0 0]斡Si me acepta como su alumno,[n]quiz茨s me haga famoso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_02_ [Makoto]]
[s][vp 9 2 65535 41505 0 0]夷Arte? La verdad es que no[n]me interesa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_03_ [Makoto]]
[s][vp 9 2 65535 45754 0 0]He o胤do que hay una exposici吋n[n]de ese artista en Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_04_ [Makoto]]
[s][vp 9 2 65535 40050 0 0]斡Ha sido incre胤ble![n]斡Sus obras son alucinantes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_05_ [Makoto]]
[s][vp 9 2 65535 38200 0 0]斡Salir y disfrutar del arte es[n]lo mejor![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_06_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]A lo mejor deber胤a ir[n]a la exposici吋n de Madarame...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_07_ [Makoto]]
[s][vp 9 2 65535 46054 0 0]夷El artista que pint吋 el 或Sayuri位?[n]斡He o胤do hablar de 姻l![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_08_ [Makoto]]
[s][vp 9 2 65535 45154 0 0]Es bastante serio, pero[n]夷no te parece algo sospechoso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_09_ [Makoto]]
[s][vp 9 2 65535 39054 0 0]He intentado ir a ver el sitio,[n]pero hab胤a demasiada gente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_10_ [Makoto]]
[s][vp 9 2 65535 38700 0 0]夷C吋mo ha podido pintar tantos[n]cuadros? 夷Es parte de su talento?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_11_ [Makoto]]
[s][vp 9 2 65535 43354 0 0]Parece que es tan popular que ya[n]no quedan entradas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_12_ [Makoto]]
[s][vp 9 2 65535 40653 0 0]Si de verdad es tan bueno,[n]puede que valga la pena ir.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_13_ [Makoto]]
[s][vp 9 2 65535 37853 0 0]夷Ya se ha inaugurado la exposici吋n?[n]Creo que ir姻. As胤 tendr姻 algo[n]de lo que hablar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_14_ [Makoto]]
[s][vp 9 2 65535 42050 0 0]Es un artista reconocido,[n]斡y el orgullo de Jap吋n![n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_15_ [Makoto]]
[s][vp 9 2 65535 41304 0 0]Si es el cuadro de un artista[n]famoso, seguramente valga[n]mucho dinero.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_16_ [Makoto]]
[s][vp 9 2 65535 45110 0 0]Tengo que reconocer que envidio[n]a la gente con talento.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_01_ [Makoto]]
[s][vp 9 2 65535 43753 0 0]Esa rueda de prensa[n]ha sido divertid胤sima.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_02_ [Makoto]]
[s][vp 9 2 65535 46002 0 0]Abusando de sus alumnos...[n]Qu姻 horror.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_03_ [Makoto]]
[s][vp 9 2 65535 39651 0 0]As胤 que ese artista ha salido rana...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_04_ [Makoto]]
[s][vp 9 2 65535 46102 0 0]斡Quiero que me devuelvan[n]el dinero de la entrada![n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_05_ [Makoto]]
[s][vp 9 2 65535 39804 0 0]Visto lo visto, 夷no te preguntas[n]por qu姻 lo hizo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_06_ [Makoto]]
[s][vp 9 2 65535 45505 0 0]Fue un error dejarlo en paz[n]hasta ahora.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_07_ [Makoto]]
[s][vp 9 2 65535 39705 0 0]No entiendo por qu姻 est茨[n]tan arrepentido de repente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_08_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]Me siento idiota[n]por haberlo apoyado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_09_ [Makoto]]
[s][vp 9 2 65535 46304 0 0]Hay que ser basura para abusar[n]de los alumnos de esa manera.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_10_ [Makoto]]
[s][vp 9 2 65535 40551 0 0]Vaya tomadura de pelo. Ni siquiera[n]era un artista de verdad...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_11_ [Makoto]]
[s][vp 9 2 65535 42604 0 0]Dicen que hay otros que est茨n[n]或confesando sus delitos位[n]sin venir a cuento.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_12_ [Makoto]]
[s][vp 9 2 65535 38055 0 0]Valiente payasada. Todo el mundo[n]est茨 hablando sin parar[n]sobre los 或Ladrones Fantasma位.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_13_ [Makoto]]
[s][vp 9 2 65535 40355 0 0]La gente ha de estar tramando[n]algo turbio a nuestras espaldas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_14_ [Makoto]]
[s][vp 9 2 65535 45500 0 0]Vaya rueda de prensa... El t胤o[n]debe de haber perdido la chaveta.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_15_ [Makoto]]
[s][vp 9 2 65535 39354 0 0]夷Es cierto que alguien dijo[n]que esto se ve胤a venir?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_16_ [Makoto]]
[s][vp 9 2 65535 40055 0 0]Conque ha estado robando[n]dinero todo este tiempo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_01_ [Makoto]]
[s][vp 9 2 65535 38702 0 0]夷Ir茨 todo bien en Shibuya?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_02_ [Makoto]]
[s][vp 9 2 65535 43759 0 0]夷Son ciertos los rumores[n]de extorsi吋n y fraude?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_03_ [Makoto]]
[s][vp 9 2 65535 40952 0 0]夷Son ciertos los rumores[n]de extorsi吋n y fraude?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_04_ [Makoto]]
[s][vp 9 2 65535 43852 0 0]夷Soy yo, o cada vez hay m茨s gente[n]con mala pinta por aqu胤?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_05_ [Makoto]]
[s][vp 9 2 65535 39752 0 0]La gente est茨 muy asustada[n]como para venir a Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]Me da la impresi吋n de que cada vez[n]hay m茨s gente con mala pinta.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_07_ [Makoto]]
[s][vp 9 2 65535 41004 0 0]夷Son ciertos los rumores[n]de extorsi吋n y fraude?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_08_ [Makoto]]
[s][vp 9 2 65535 46059 0 0]夷Soy yo, o cada vez hay m茨s gente[n]con mala pinta por aqu胤?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_09_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]He escuchado un rumor[n]de que te convocan en Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_10_ [Makoto]]
[s][vp 9 2 65535 42204 0 0]He o胤do que la gente[n]est茨 recibiendo correos[n]que son ciberestafas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_11_ [Makoto]]
[s][vp 9 2 65535 43352 0 0]Todo el mundo tiene[n]demasiado miedo de pisar Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_12_ [Makoto]]
[s][vp 9 2 65535 43854 0 0]夷Fraudes por internet? 斡Qu姻 horror![n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_13_ [Makoto]]
[s][vp 9 2 65535 40555 0 0]He escuchado un rumor[n]de que te convocan en Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_14_ [Makoto]]
[s][vp 9 2 65535 39151 0 0]He o胤do que la gente[n]est茨 recibiendo correos[n]que son ciberestafas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_15_ [Makoto]]
[s][vp 9 2 65535 42912 0 0]A veces veo matones merodeando[n]por aqu胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_16_ [Makoto]]
[s][vp 9 2 65535 40802 0 0]夷Fraudes por internet? 斡Qu姻 horror![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_01_ [Makoto]]
[s][vp 9 2 65535 38100 0 0]Madarame tambi姻n[n]lo ha sufrido, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_02_ [Makoto]]
[s][vp 9 2 65535 41505 0 0]Es imposible que los Ladrones[n]Fantasma existan de verdad.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_03_ [Makoto]]
[s][vp 9 2 65535 40604 0 0]Mientras todo est姻[n]en calma por aqu胤, por m胤 bien.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_04_ [Makoto]]
[s][vp 9 2 65535 44255 0 0]As胤 que los Ladrones Fantasma, 夷eh?[n]夷Crees que existen de verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_05_ [Makoto]]
[s][vp 9 2 65535 40304 0 0]Ser胤a interesante[n]que los avisos fueran reales.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_06_ [Makoto]]
[s][vp 9 2 65535 38455 0 0]Es imposible que los Ladrones[n]Fantasma existan de verdad.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_07_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]斡Mi amiga dice que ha visto[n]uno de los avisos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_08_ [Makoto]]
[s][vp 9 2 65535 45755 0 0]As胤 que los Ladrones Fantasma, 夷eh?[n]夷Crees que existen de verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_09_ [Makoto]]
[s][vp 9 2 65535 44904 0 0]Todo este rollo de los Ladrones[n]Fantasma me parece una patochada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_10_ [Makoto]]
[s][vp 9 2 65535 40355 0 0]夷El Kaneshiro ese es mala persona?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_11_ [Makoto]]
[s][vp 9 2 65535 42755 0 0]夷El aviso de los Ladrones Fantasma?[n]斡No es m茨s que otra leyenda urbana![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_12_ [Makoto]]
[s][vp 9 2 65535 39005 0 0]As胤 que los Ladrones Fantasma, 夷eh?[n]夷Crees que existen de verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_13_ [Makoto]]
[s][vp 9 2 65535 42554 0 0]He o胤do que los han colgado[n]por todas partes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_14_ [Makoto]]
[s][vp 9 2 65535 38450 0 0]Es imposible que los Ladrones[n]Fantasma existan de verdad.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_15_ [Makoto]]
[s][vp 9 2 65535 39654 0 0]He o胤do que los han colgado[n]por todas partes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_16_ [Makoto]]
[s][vp 9 2 65535 43455 0 0]As胤 que los Ladrones Fantasma, 夷eh?[n]夷Crees que existen de verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_01_ [Makoto]]
[s][vp 9 2 65535 37508 0 0]斡Vamos a Shibuya,[n]que ha vuelto a la normalidad![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_02_ [Makoto]]
[s][vp 9 2 65535 41204 0 0]Parece que las aguas volver茨n[n]a su cauce a partir de ahora.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_03_ [Makoto]]
[s][vp 9 2 65535 38600 0 0]Es un alivio que Shibuya[n]est姻 tranquila de nuevo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_04_ [Makoto]]
[s][vp 9 2 65535 41303 0 0]斡Qu姻 alivio![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_05_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]斡Menos mal que ya no est茨[n]ese hatajo de delincuentes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_06_ [Makoto]]
[s][vp 9 2 65535 45300 0 0]斡Por fin han arrestado al jefe[n]de la organizaci吋n criminal![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_07_ [Makoto]]
[s][vp 9 2 65535 41454 0 0]斡Parece que todo vuelve[n]a estar tranquilo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_08_ [Makoto]]
[s][vp 9 2 65535 40050 0 0]斡Shibuya vuelve a ser[n]un lugar seguro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_09_ [Makoto]]
[s][vp 9 2 65535 39450 0 0]斡Ya no habr茨 de qu姻 preocuparse[n]cuando vayamos a Shibuya![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_10_ [Makoto]]
[s][vp 9 2 65535 42550 0 0]No sab胤a qu姻 iba a pasar,[n]pero me alegro de su detenci吋n.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_11_ [Makoto]]
[s][vp 9 2 65535 42953 0 0]Ahora que es un lugar seguro,[n]podremos salir por Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_12_ [Makoto]]
[s][vp 9 2 65535 41304 0 0]Es un alivio que Shibuya[n]est姻 tranquila de nuevo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_13_ [Makoto]]
[s][vp 9 2 65535 41700 0 0]斡Shibuya vuelve a ser un lugar[n]seguro para vivir![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_14_ [Makoto]]
[s][vp 9 2 65535 45503 0 0]No sab胤a qu姻 iba a pasar,[n]pero me alegro de su detenci吋n.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_15_ [Makoto]]
[s][vp 9 2 65535 46203 0 0]Ya no hay nada[n]de lo que preocuparse, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_16_ [Makoto]]
[s][vp 9 2 65535 42000 0 0]Que vuelva a reinar la paz[n]en Shibuya me hace muy feliz.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_01_ [Makoto]]
[s][vp 9 2 65535 37856 0 0]夷Has visto las noticias?[n]斡Parece que ha sido cosa[n]de los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_02_ [Makoto]]
[s][vp 9 2 65535 41954 0 0]As胤 que todo ha ido seg雨n[n]el aviso de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_03_ [Makoto]]
[s][vp 9 2 65535 40954 0 0]夷Has visto las noticias?[n]斡Parece que han sido[n]los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_04_ [Makoto]]
[s][vp 9 2 65535 43854 0 0]斡夷Es cierto que los Ladrones[n]Fantasma han resuelto[n]ese incidente?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_05_ [Makoto]]
[s][vp 9 2 65535 38504 0 0]As胤 que los Ladrones Fantasma[n]han acabado con Kaneshiro, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_06_ [Makoto]]
[s][vp 9 2 65535 38456 0 0]斡Esos t胤os son la ca隠a![n]斡Est茨n haci姻ndolo mejor[n]que la polic胤a![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_07_ [Makoto]]
[s][vp 9 2 65535 45156 0 0]斡Al final, el aviso[n]no era ninguna broma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_08_ [Makoto]]
[s][vp 9 2 65535 39704 0 0]En las noticias han dicho que los[n]Ladrones Fantasma podr胤an[n]estar involucrados.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_09_ [Makoto]]
[s][vp 9 2 65535 39800 0 0]Ser胤a la leche si de verdad[n]fueran los Ladrones Fantasma[n]los que lo han hecho.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_10_ [Makoto]]
[s][vp 9 2 65535 44906 0 0]斡Esos t胤os son la ca隠a![n]斡Est茨n haci姻ndolo mejor[n]que la polic胤a![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_11_ [Makoto]]
[s][vp 9 2 65535 44456 0 0]斡Ha sucedido exactamente como se[n]indicaba en el aviso[n]de los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_12_ [Makoto]]
[s][vp 9 2 65535 41804 0 0]En las noticias han dicho que los[n]Ladrones Fantasma podr胤an[n]estar involucrados.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_13_ [Makoto]]
[s][vp 9 2 65535 38756 0 0]夷Has visto lo de las noticias?[n]斡Parece que han sido[n]los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_14_ [Makoto]]
[s][vp 9 2 65535 39153 0 0]As胤 que todo ha ido seg雨n[n]el aviso de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_15_ [Makoto]]
[s][vp 9 2 65535 39356 0 0]夷Has visto lo de las noticias?[n]斡Parece que han sido[n]los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_16_ [Makoto]]
[s][vp 9 2 65535 39004 0 0]斡夷Es cierto que los Ladrones[n]Fantasma han resuelto[n]ese incidente?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_01_ [Makoto]]
[s][vp 9 2 65535 38405 0 0]Parece que Medjed[n]tiene muy presente[n]a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_02_ [Makoto]]
[s][vp 9 2 65535 41504 0 0]Pero 夷qu姻 clase de grupo es Medjed?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_03_ [Makoto]]
[s][vp 9 2 65535 37700 0 0]Pues yo apoyo[n]a los Ladrones Fantasma.[n]Son los Robin Hood actuales.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_04_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]No dicen m茨s que mentiras.[n]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma al respecto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_05_ [Makoto]]
[s][vp 9 2 65535 40304 0 0]夷Qu姻 clase de grupo es Medjed?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_06_ [Makoto]]
[s][vp 9 2 65535 45504 0 0]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma[n]con respecto a esos hackers.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_07_ [Makoto]]
[s][vp 9 2 65535 38354 0 0]夷Por qu姻 Medjed est茨 atacando[n]a los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_08_ [Makoto]]
[s][vp 9 2 65535 46056 0 0]Me pregunto qu姻 har茨n los Ladrones[n]Fantasma ante tal desaf胤o.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_09_ [Makoto]]
[s][vp 9 2 65535 39104 0 0]夷Has visto las noticias sobre[n]el comunicado? 夷Qu姻 har茨n[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_10_ [Makoto]]
[s][vp 9 2 65535 42554 0 0]Los Ladrones Fantasma[n]se encargar茨n de ellos, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_11_ [Makoto]]
[s][vp 9 2 65535 45104 0 0]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma[n]con respecto a Medjed...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_12_ [Makoto]]
[s][vp 9 2 65535 38254 0 0]No dicen m茨s que mentiras.[n]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma al respecto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_13_ [Makoto]]
[s][vp 9 2 65535 39804 0 0]夷Has visto las noticias sobre[n]el comunicado? 夷Qu姻 har茨n[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_14_ [Makoto]]
[s][vp 9 2 65535 38452 0 0]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma[n]con respecto a esos hackers.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_15_ [Makoto]]
[s][vp 9 2 65535 38654 0 0]斡Los Ladrones Fantasma son los[n]雨nicos que pueden acabar[n]con esos hackers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_16_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]No dicen m茨s que mentiras.[n]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma al respecto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_01_ [Makoto]]
[s][vp 9 2 65535 39057 0 0]Vamos, Ladrones Fantasma,[n]pronunciaos ya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_02_ [Makoto]]
[s][vp 9 2 65535 41756 0 0]夷C吋mo piensan combatir[n]los Ladrones Fantasma[n]a esos hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_03_ [Makoto]]
[s][vp 9 2 65535 42462 0 0]Tienen a Jap吋n en el punto de mira.[n]Espero que hagan algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_04_ [Makoto]]
[s][vp 9 2 65535 41455 0 0]Tienen que hacer algo[n]antes de que suceda algo malo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_05_ [Makoto]]
[s][vp 9 2 65535 41504 0 0]夷Qu姻 pueden hacer los Ladrones[n]Fantasma contra esos hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_06_ [Makoto]]
[s][vp 9 2 65535 41856 0 0]夷Qu姻 est茨n haciendo[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_07_ [Makoto]]
[s][vp 9 2 65535 43852 0 0]Tienen a Jap吋n en el punto de mira.[n]Espero que hagan algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_08_ [Makoto]]
[s][vp 9 2 65535 46055 0 0]Si los Ladrones Fantasma[n]revelan su verdadera identidad,[n]no nos har茨n nada, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_09_ [Makoto]]
[s][vp 9 2 65535 46303 0 0]夷Qu姻 pueden hacer los Ladrones[n]Fantasma contra esos hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_10_ [Makoto]]
[s][vp 9 2 65535 40557 0 0]Vamos, Ladrones Fantasma,[n]pronunciaos ya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_11_ [Makoto]]
[s][vp 9 2 65535 43201 0 0]Los Ladrones Fantasma[n]guardan silencio. 夷Qu姻 va a pasar?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_12_ [Makoto]]
[s][vp 9 2 65535 43455 0 0]Si los Ladrones Fantasma[n]revelan su verdadera identidad,[n]no nos har茨n nada, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_13_ [Makoto]]
[s][vp 9 2 65535 38754 0 0]夷Qu姻 pueden hacer los Ladrones[n]Fantasma contra esos hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_14_ [Makoto]]
[s][vp 9 2 65535 42054 0 0]Vamos, Ladrones Fantasma,[n]pronunciaos ya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_15_ [Makoto]]
[s][vp 9 2 65535 40804 0 0]Tienen a Jap吋n en el punto de mira.[n]Espero que hagan algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_16_ [Makoto]]
[s][vp 9 2 65535 41805 0 0]Si los Ladrones Fantasma[n]revelan su verdadera identidad,[n]no nos har茨n nada, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_01_ [Makoto]]
[s][vp 9 2 65535 40754 0 0]斡He o胤do que los Ladrones Fantasma[n]lo han logrado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_02_ [Makoto]]
[s][vp 9 2 65535 41950 0 0]Me alegra que se haya resuelto[n]antes de que provocaran[n]ning雨n da隠o...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_03_ [Makoto]]
[s][vp 9 2 65535 44456 0 0]斡Parece que han cerrado[n]la web de Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_04_ [Makoto]]
[s][vp 9 2 65535 44254 0 0]Me alegra que todo se haya resuelto[n]y que nadie haya salido herido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_05_ [Makoto]]
[s][vp 9 2 65535 43700 0 0]斡Es incre胤ble que hayan derrotado[n]a Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_06_ [Makoto]]
[s][vp 9 2 65535 41850 0 0]Me alegra que se haya resuelto[n]antes de que provocaran[n]ning雨n da隠o...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_07_ [Makoto]]
[s][vp 9 2 65535 41004 0 0]斡Parece que han cerrado[n]la web de Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_08_ [Makoto]]
[s][vp 9 2 65535 46100 0 0]斡Me alegra que se haya resuelto![n]斡Y es todo gracias[n]a los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_09_ [Makoto]]
[s][vp 9 2 65535 37606 0 0]Eso quiere decir que los Ladrones[n]Fantasma nos han salvado, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_10_ [Makoto]]
[s][vp 9 2 65535 38706 0 0]斡Es incre胤ble que hayan derrotado[n]a Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_11_ [Makoto]]
[s][vp 9 2 65535 42800 0 0]斡He o胤do que han cerrado[n]la p茨gina web de Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_12_ [Makoto]]
[s][vp 9 2 65535 46106 0 0]斡No puedo creer que hayan sido[n]capaces de acabar con un grupo[n]internacional de hackers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_13_ [Makoto]]
[s][vp 9 2 65535 40106 0 0]Eso quiere decir que los Ladrones[n]Fantasma nos han salvado, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_14_ [Makoto]]
[s][vp 9 2 65535 42053 0 0]斡Es incre胤ble que hayan derrotado[n]a Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_15_ [Makoto]]
[s][vp 9 2 65535 38004 0 0]Los Ladrones Fantasma[n]lo han conseguido, 斡夷eh?! 斡Es incre胤ble![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_16_ [Makoto]]
[s][vp 9 2 65535 38553 0 0]斡No puedo creer que hayan sido[n]capaces de acabar con un grupo[n]internacional de hackers![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_01_ [Makoto]]
[s][vp 9 2 65535 39756 0 0]斡Los Ladrones Fantasma ten胤an raz吋n[n]desde el principio![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_02_ [Makoto]]
[s][vp 9 2 65535 43400 0 0]斡Esos Ladrones Fantasma[n]son impresionantes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_03_ [Makoto]]
[s][vp 9 2 65535 38900 0 0]斡No me puedo creer[n]que hayan derrotado a esos hackers![n]斡Son lo m茨s![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_04_ [Makoto]]
[s][vp 9 2 65535 41656 0 0]斡Los Ladrones Fantasma[n]son la justicia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_05_ [Makoto]]
[s][vp 9 2 65535 45803 0 0]斡Los Ladrones Fantasma[n]han salvado Jap吋n![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_06_ [Makoto]]
[s][vp 9 2 65535 39156 0 0]Pens姻 que era el fin.[n]斡Vivan los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_07_ [Makoto]]
[s][vp 9 2 65535 40806 0 0]No me extra隠ar胤a[n]que tambi姻n estuviesen sorprendidos[n]en el extranjero.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_08_ [Makoto]]
[s][vp 9 2 65535 41650 0 0]斡Estamos a salvo gracias[n]a los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_09_ [Makoto]]
[s][vp 9 2 65535 41904 0 0]斡C吋mo me alegra[n]no haber dudado de ellos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_10_ [Makoto]]
[s][vp 9 2 65535 44950 0 0]斡Me alegra que podamos contar[n]con los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_11_ [Makoto]]
[s][vp 9 2 65535 40206 0 0]斡Han acabado con Medjed![n]斡Tienen todos mis respetos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_12_ [Makoto]]
[s][vp 9 2 65535 39006 0 0]斡Los Ladrones Fantasma[n]son mis 胤dolos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_13_ [Makoto]]
[s][vp 9 2 65535 39800 0 0]斡Acabar con Medjed[n]no es moco de pavo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_14_ [Makoto]]
[s][vp 9 2 65535 40706 0 0]斡Me alegra que podamos contar[n]con los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_15_ [Makoto]]
[s][vp 9 2 65535 39356 0 0]Parece que Jap吋n est茨 a salvo[n]gracias a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_16_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]斡Los Ladrones Fantasma[n]son geniales![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_01_ [Makoto]]
[s][vp 9 2 65535 40103 0 0]All茨 donde mires, la gente solo[n]habla de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_02_ [Makoto]]
[s][vp 9 2 65535 44706 0 0]斡La sociedad[n]se ha vuelto loca con la fiebre[n]de los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_03_ [Makoto]]
[s][vp 9 2 65535 40606 0 0]斡Yo tambi姻n quiero pedirles que[n]despierten el coraz吋n de alguien![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_04_ [Makoto]]
[s][vp 9 2 65535 41306 0 0]斡No hay nada que temer[n]mientras est姻n aqu胤[n]los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_05_ [Makoto]]
[s][vp 9 2 65535 44353 0 0]斡Acabad con los malvados del mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_06_ [Makoto]]
[s][vp 9 2 65535 38458 0 0]斡Los Ladrones Fantasma[n]han salido de la nada![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_07_ [Makoto]]
[s][vp 9 2 65535 44505 0 0]Mucha gente est茨 apoyando[n]a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_08_ [Makoto]]
[s][vp 9 2 65535 41650 0 0]斡Mientras los Ladrones Fantasma[n]est姻n aqu胤, todo ir茨 bien![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_09_ [Makoto]]
[s][vp 9 2 65535 38206 0 0]斡Los Ladrones Fantasma[n]velan por nuestra seguridad![n]斡Todo saldr茨 bien![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_10_ [Makoto]]
[s][vp 9 2 65535 38405 0 0]Es incre胤ble lo populares[n]que son los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_11_ [Makoto]]
[s][vp 9 2 65535 40606 0 0]斡Si no sabes qui姻nes son[n]los Ladrones Fantasma, va siendo[n]hora de que te pongas al d胤a![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_12_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Me estoy planteando enviarles una[n]solicitud a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_13_ [Makoto]]
[s][vp 9 2 65535 39056 0 0]斡Los Ladrones Fantasma[n]velan por nuestra seguridad![n]斡Todo saldr茨 bien![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_14_ [Makoto]]
[s][vp 9 2 65535 41861 0 0]All茨 donde mires, la gente solo[n]habla de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_15_ [Makoto]]
[s][vp 9 2 65535 41656 0 0]斡Los Ladrones Fantasma[n]son geniales![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_16_ [Makoto]]
[s][vp 9 2 65535 39350 0 0]Mientras los Ladrones[n]Fantasma est姻n aqu胤,[n]Jap吋n estar茨 a salvo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_01_ [Makoto]]
[s][vp 9 2 65535 40505 0 0]Los tratan como esclavos, 夷verdad?[n]Qu姻 empresa tan horrible.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_02_ [Makoto]]
[s][vp 9 2 65535 41500 0 0]Y pensar que Okumura Foods[n]explotaba a sus empleados...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_03_ [Makoto]]
[s][vp 9 2 65535 40255 0 0]Me siento mal por los que[n]trabajan ah胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_04_ [Makoto]]
[s][vp 9 2 65535 40051 0 0]Son lo peor. Tratan a sus empleados[n]como si fuesen basura.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_05_ [Makoto]]
[s][vp 9 2 65535 38204 0 0]Y pensar que Okumura Foods[n]explotaba a sus empleados...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_06_ [Makoto]]
[s][vp 9 2 65535 39151 0 0]Tratan a sus empleados[n]como si fueran esclavos, 夷no?[n]Es horrible.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_07_ [Makoto]]
[s][vp 9 2 65535 41001 0 0]Explotaban a sus empleados...[n]Es terrible.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_08_ [Makoto]]
[s][vp 9 2 65535 38601 0 0]Han hecho cosas bastante inmorales[n]a escondidas, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_09_ [Makoto]]
[s][vp 9 2 65535 40302 0 0]He o胤do que los hac胤an trabajar[n]una cantidad inhumana de horas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_10_ [Makoto]]
[s][vp 9 2 65535 43002 0 0]Me sorprende que este tema no[n]se haya hecho p雨blico hasta ahora.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_11_ [Makoto]]
[s][vp 9 2 65535 40004 0 0]Mis padres tambi姻n se quedaron[n]de piedra cuando se enteraron.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_12_ [Makoto]]
[s][vp 9 2 65535 42401 0 0]No ten胤a ni idea de que este era[n]el motivo por el que Okumura Foods[n]hab胤a crecido tan r茨pido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_13_ [Makoto]]
[s][vp 9 2 65535 44602 0 0]He o胤do que los obligaban[n]a trabajar muy duro[n]durante muchas horas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_14_ [Makoto]]
[s][vp 9 2 65535 43952 0 0]Me sorprende que este tema no[n]se haya hecho p雨blico hasta ahora.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_15_ [Makoto]]
[s][vp 9 2 65535 43454 0 0]La cosa estaba tan mal que[n]hasta ha habido disturbios, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_16_ [Makoto]]
[s][vp 9 2 65535 39304 0 0]No ten胤a ni idea de que este era[n]el motivo por el que Okumura Foods[n]hab胤a crecido tan r茨pido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_01_ [Makoto]]
[s][vp 9 2 65535 40750 0 0]夷No pueden hacer alguna clase[n]de reforma social o algo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_02_ [Makoto]]
[s][vp 9 2 65535 41203 0 0]斡Los Ladrones Fantasma seguir茨n[n]luchando contra los villanos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_03_ [Makoto]]
[s][vp 9 2 65535 41403 0 0]Me pregunto a qui姻n elegir茨n[n]como pr吋ximo objetivo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_04_ [Makoto]]
[s][vp 9 2 65535 41656 0 0]Si vais a arreglar el mundo,[n]斡夷a qu姻 esper茨is para poneros[n]manos a la obra?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_05_ [Makoto]]
[s][vp 9 2 65535 38206 0 0]Supongo que los Ladrones Fantasma[n]se pondr茨n las pilas pronto, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_06_ [Makoto]]
[s][vp 9 2 65535 43956 0 0]斡Todo saldr茨 bien[n]si lo dejamos en manos[n]de los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_07_ [Makoto]]
[s][vp 9 2 65535 40404 0 0]Me pregunto a qui姻n elegir茨n[n]como pr吋ximo objetivo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_08_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]斡Los Ladrones Fantasma reformar茨n[n]este mundo podrido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_09_ [Makoto]]
[s][vp 9 2 65535 44706 0 0]斡No me cabe duda de que[n]los Ladrones Fantasma har茨n[n]algo al respecto![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_10_ [Makoto]]
[s][vp 9 2 65535 37553 0 0]斡Vamos, Ladrones Fantasma![n]斡A ver si hac姻is algo interesante[n]de una vez![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_11_ [Makoto]]
[s][vp 9 2 65535 43103 0 0]No pasa nada...[n]斡Los Ladrones Fantasma[n]se encargar茨n de eso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_12_ [Makoto]]
[s][vp 9 2 65535 46100 0 0]No hay nada que temer[n]mientras los Ladrones Fantasma[n]est姻n aqu胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_13_ [Makoto]]
[s][vp 9 2 65535 41750 0 0]斡No me cabe duda de que[n]los Ladrones Fantasma har茨n[n]algo al respecto![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_14_ [Makoto]]
[s][vp 9 2 65535 45306 0 0]斡Vamos, Ladrones Fantasma![n]斡A ver si hac姻is algo interesante[n]de una vez![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_15_ [Makoto]]
[s][vp 9 2 65535 46203 0 0]Me pregunto a qui姻n elegir茨n[n]como pr吋ximo objetivo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_16_ [Makoto]]
[s][vp 9 2 65535 39306 0 0]斡Los Ladrones Fantasma reformar茨n[n]este mundo podrido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_01_ [Makoto]]
[s][vp 9 2 65535 42706 0 0]斡Han enviado otro aviso![n]斡Sab胤a que ser胤a para Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_02_ [Makoto]]
[s][vp 9 2 65535 41051 0 0]斡Okumura est茨 acabado![n]斡A por 姻l, Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_03_ [Makoto]]
[s][vp 9 2 65535 44203 0 0]斡Qu姻 ganas ten胤a[n]de que enviaran el aviso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_04_ [Makoto]]
[s][vp 9 2 65535 41003 0 0]斡Quiero ver una disculpa mucho[n]m茨s dram茨tica que la de Madarame![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_05_ [Makoto]]
[s][vp 9 2 65535 39806 0 0]斡Adelante, Ladrones Fantasma![n]斡Id a por ellos y no os reprim茨is![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_06_ [Makoto]]
[s][vp 9 2 65535 41856 0 0]斡No dej姻is que se salga[n]con la suya, Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_07_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]斡Quiero ver m茨s[n]de esos incre胤bles castigos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_08_ [Makoto]]
[s][vp 9 2 65535 41161 0 0]斡S胤, Ladrones Fantasma![n]斡Dadles para el pelo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_09_ [Makoto]]
[s][vp 9 2 65535 43156 0 0]斡Mostradnos vuestra justicia![n]斡Acabad con Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_10_ [Makoto]]
[s][vp 9 2 65535 37806 0 0]斡Llevaba tiempo esperando esto,[n]Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_11_ [Makoto]]
[s][vp 9 2 65535 43253 0 0]斡Estaba deseando que los Ladrones[n]Fantasma enviaran otro aviso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_12_ [Makoto]]
[s][vp 9 2 65535 39600 0 0]斡Quiero ver una disculpa mucho[n]m茨s dram茨tica que la de Madarame![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_13_ [Makoto]]
[s][vp 9 2 65535 43406 0 0]斡No me extra隠a que lo castiguen,[n]si solo le importa el dinero![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_14_ [Makoto]]
[s][vp 9 2 65535 40706 0 0]斡Llevaba tiempo esperando esto,[n]Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_15_ [Makoto]]
[s][vp 9 2 65535 37753 0 0]斡Lo m茨s justo es que las personas[n]que hagan cosas terribles reciban[n]un buen castigo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_16_ [Makoto]]
[s][vp 9 2 65535 42400 0 0]斡El presidente Okumura tiene[n]que pagar por lo que ha hecho![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_01_ [Makoto]]
[s][vp 9 2 65535 43007 0 0]Por la forma en que lo han hecho,[n]parece que disfrutan[n]matando a la gente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_02_ [Makoto]]
[s][vp 9 2 65535 41201 0 0]No importa lo malo que fuera.[n]斡Matarlo es una locura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_03_ [Makoto]]
[s][vp 9 2 65535 40407 0 0]斡夷A eso lo llaman[n]或despertar el coraz吋n位?![n]斡Solo son unos asesinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_04_ [Makoto]]
[s][vp 9 2 65535 40055 0 0]夷C吋mo van a despertar el coraz吋n[n]de nadie si lo matan?[n]斡Son unos embusteros![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_05_ [Makoto]]
[s][vp 9 2 65535 39402 0 0]Yo creo que disfrutan[n]matando a la gente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_06_ [Makoto]]
[s][vp 9 2 65535 42057 0 0]斡No me puedo creer que hayan[n]matado a alguien! 斡Est茨n locos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_07_ [Makoto]]
[s][vp 9 2 65535 45157 0 0]斡夷A eso lo llaman[n]或despertar el coraz吋n位?![n]斡Solo son unos asesinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_08_ [Makoto]]
[s][vp 9 2 65535 41657 0 0]Entonces, 夷despiertan el coraz吋n[n]de alguien mat茨ndolo?[n]斡Tiene que ser una broma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_09_ [Makoto]]
[s][vp 9 2 65535 43057 0 0]Por la forma en que lo han hecho,[n]parece que disfrutan[n]matando a la gente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_10_ [Makoto]]
[s][vp 9 2 65535 43751 0 0]斡No hay excusa para matar a nadie,[n]por muy malvado que sea![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_11_ [Makoto]]
[s][vp 9 2 65535 42607 0 0]斡Tampoco hac胤a falta matarlo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_12_ [Makoto]]
[s][vp 9 2 65535 41007 0 0]夷C吋mo van a despertar el coraz吋n[n]de nadie si lo matan?[n]斡Son unos embusteros![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_13_ [Makoto]]
[s][vp 9 2 65535 44171 0 0]Por la forma en que lo han hecho,[n]parece que disfrutan[n]matando a la gente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_14_ [Makoto]]
[s][vp 9 2 65535 42057 0 0]斡No hay excusa para matar a nadie,[n]por muy malvado que sea![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_15_ [Makoto]]
[s][vp 9 2 65535 45157 0 0]斡夷A eso lo llaman[n]或despertar el coraz吋n位?![n]斡Solo son unos asesinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_16_ [Makoto]]
[s][vp 9 2 65535 43251 0 0]夷Despiertan el coraz吋n de una[n]persona mat茨ndola? 斡Est茨n locos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_01_ [Makoto]]
[s][vp 9 2 65535 43507 0 0]Alguien, no importa qui姻n,[n]tiene que detener[n]a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_02_ [Makoto]]
[s][vp 9 2 65535 43401 0 0]Ni el gobierno ni la polic胤a[n]son de fiar...[n]夷Qu姻 le pasa a este pa胤s?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_03_ [Makoto]]
[s][vp 9 2 65535 40957 0 0]斡夷A qu姻 espera la polic胤a?![n]斡Daos prisa y arrestad[n]a los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_04_ [Makoto]]
[s][vp 9 2 65535 44251 0 0]Ya sabemos qui姻nes[n]son los culpables, pero a雨n[n]no los han arrestado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_05_ [Makoto]]
[s][vp 9 2 65535 38202 0 0]Qu姻 horror... Los episodios[n]de descontrol se repiten[n]cada vez con m茨s frecuencia.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_06_ [Makoto]]
[s][vp 9 2 65535 45302 0 0]Ni el gobierno ni la polic胤a[n]son de fiar...[n]夷Qu姻 le pasa a este pa胤s?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_07_ [Makoto]]
[s][vp 9 2 65535 39707 0 0]斡夷A qu姻 espera la polic胤a?![n]斡Daos prisa y arrestad[n]a los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_08_ [Makoto]]
[s][vp 9 2 65535 43851 0 0]Ya sabemos qui姻nes[n]son los culpables, pero a雨n[n]no los han arrestado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_09_ [Makoto]]
[s][vp 9 2 65535 41907 0 0]Alguien, no importa qui姻n,[n]tiene que detener[n]a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_10_ [Makoto]]
[s][vp 9 2 65535 40301 0 0]Ni el gobierno ni la polic胤a[n]son de fiar...[n]夷Qu姻 le pasa a este pa胤s?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_11_ [Makoto]]
[s][vp 9 2 65535 37657 0 0]斡Daos prisa y haced algo[n]con los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_12_ [Makoto]]
[s][vp 9 2 65535 40251 0 0]斡夷Cu茨ndo va a actuar la polic胤a y[n]arrestar a Los Ladrones Fantasma?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_13_ [Makoto]]
[s][vp 9 2 65535 42707 0 0]Alguien, no importa qui姻n,[n]tiene que detener[n]a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_14_ [Makoto]]
[s][vp 9 2 65535 40702 0 0]Ni el gobierno ni la polic胤a[n]son de fiar...[n]夷Qu姻 le pasa a este pa胤s?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_15_ [Makoto]]
[s][vp 9 2 65535 40801 0 0]斡夷A qu姻 espera la polic胤a?![n]斡Daos prisa y arrestad[n]a los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_16_ [Makoto]]
[s][vp 9 2 65535 41657 0 0]Ya sabemos qui姻nes[n]son los culpables, pero a雨n[n]no los han arrestado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_01_ [Makoto]]
[s][vp 9 2 65535 43157 0 0]斡Que alguien capture[n]a los Ladrones Fantasma![n]斡No importa qui姻n![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_02_ [Makoto]]
[s][vp 9 2 65535 46007 0 0]La polic胤a por fin est茨 tomando[n]medidas para arrestarlos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_03_ [Makoto]]
[s][vp 9 2 65535 41251 0 0]夷De verdad se creen[n]que los van a capturar[n]poniendo una recompensa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_04_ [Makoto]]
[s][vp 9 2 65535 41307 0 0]Deber胤an dar caza a los Ladrones[n]Fantasma cuanto antes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_05_ [Makoto]]
[s][vp 9 2 65535 38404 0 0]斡夷Ofrecen treinta millones[n]de yenes como recompensa?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_06_ [Makoto]]
[s][vp 9 2 65535 41859 0 0]Daos prisa y arrestad ya[n]a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_07_ [Makoto]]
[s][vp 9 2 65535 41251 0 0]夷Servir茨 de algo[n]poner una recompensa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_08_ [Makoto]]
[s][vp 9 2 65535 41157 0 0]夷Cu茨nto tiempo tendremos[n]que vivir atemorizados[n]por los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_09_ [Makoto]]
[s][vp 9 2 65535 45651 0 0]夷Por qu姻 calla el gobierno?[n]斡Haced algo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_10_ [Makoto]]
[s][vp 9 2 65535 43901 0 0]斡La polic胤a est茨 tardando demasiado[n]en tomar cartas en el asunto![n]夷Se puede saber qu姻 est茨n haciendo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_11_ [Makoto]]
[s][vp 9 2 65535 41401 0 0]斡夷No se supone que la polic胤a[n]tiene que ocuparse[n]de los criminales?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_12_ [Makoto]]
[s][vp 9 2 65535 42157 0 0]Me da igual c吋mo,[n]pero arrestad a esos asesinos[n]de una vez por todas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_13_ [Makoto]]
[s][vp 9 2 65535 38700 0 0]斡夷Una recompensa[n]de treinta millones de yenes?![n]斡夷Est茨n mal de la azotea?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_14_ [Makoto]]
[s][vp 9 2 65535 45501 0 0]Tienen que darse prisa[n]y trazar un buen plan.[n]Nuestras vidas est茨n en juego.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_15_ [Makoto]]
[s][vp 9 2 65535 39300 0 0]La polic胤a por fin est茨 tomando[n]medidas para arrestarlos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_16_ [Makoto]]
[s][vp 9 2 65535 41302 0 0]Siempre son tan lentos[n]a la hora de tomar medidas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_01_ [Makoto]]
[s][vp 9 2 65535 38405 0 0]As胤 que los que dan discursos[n]en la calle son candidatos[n]para las elecciones.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_02_ [Makoto]]
[s][vp 9 2 65535 41610 0 0]Espero que el gobierno[n]cambie su forma de actuar[n]despu姻s de las elecciones.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_03_ [Makoto]]
[s][vp 9 2 65535 42155 0 0]夷Hay alguien capaz[n]de solucionar los problemas[n]de este mundo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_04_ [Makoto]]
[s][vp 9 2 65535 39009 0 0]Mi hijo se puso a llorar porque[n]gritaba mucho en su discurso...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_05_ [Makoto]]
[s][vp 9 2 65535 43709 0 0]Lo que dar胤a por que apareciera[n]un pol胤tico honrado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_06_ [Makoto]]
[s][vp 9 2 65535 41854 0 0]斡Ahora necesitamos[n]un pol胤tico con convicci吋n[n]y visi吋n de futuro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_07_ [Makoto]]
[s][vp 9 2 65535 43252 0 0]Ojal茨 apareciese un candidato[n]capaz de reformar la sociedad[n]en las elecciones.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_08_ [Makoto]]
[s][vp 9 2 65535 41155 0 0]夷Qui姻nes ser茨n los candidatos[n]con m茨s posibilidades[n]de ganar las elecciones?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_09_ [Makoto]]
[s][vp 9 2 65535 43704 0 0]夷C吋mo se llama el t胤o[n]que ha estado dando[n]tantos discursos 雨ltimamente?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_10_ [Makoto]]
[s][vp 9 2 65535 41705 0 0]夷Cu茨ndo son las elecciones?[n]Se me ha ido la fecha de la cabeza.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_11_ [Makoto]]
[s][vp 9 2 65535 39655 0 0]No s姻 qui姻n, pero uno[n]de los candidatos es un portento.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_12_ [Makoto]]
[s][vp 9 2 65535 46054 0 0]Algunos de los diputados[n]de este a隠o son muy prometedores,[n]夷no crees?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_13_ [Makoto]]
[s][vp 9 2 65535 38705 0 0]Las elecciones son a finales[n]de a隠o, 夷verdad?[n]Es que se me ha olvidado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_14_ [Makoto]]
[s][vp 9 2 65535 40703 0 0]夷Es verdad que hay un cisma[n]en el partido gobernante?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_15_ [Makoto]]
[s][vp 9 2 65535 45755 0 0]夷Se ha disuelto[n]la C茨mara de Representantes?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_16_ [Makoto]]
[s][vp 9 2 65535 39011 0 0]S胤, es 姻l... 斡No es como[n]los dem茨s pol胤ticos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_01_ [Makoto]]
[s][vp 9 2 65535 44302 0 0]斡夷Qu姻 hace la polic胤a?![n]Hay que arrestarlos de inmediato.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_02_ [Makoto]]
[s][vp 9 2 65535 41751 0 0]Ni el gobierno ni la polic胤a[n]son de fiar...[n]夷Qu姻 le pasa a este pa胤s?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_03_ [Makoto]]
[s][vp 9 2 65535 38357 0 0]Cuando la gente empez吋 a hablar[n]de los Ladrones Fantasma[n]fue muy raro...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_04_ [Makoto]]
[s][vp 9 2 65535 39007 0 0]斡Los Ladrones Fantasma[n]son una panda de asesinos[n]sin escr雨pulos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_05_ [Makoto]]
[s][vp 9 2 65535 39755 0 0]En serio, 夷qui姻nes son[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_06_ [Makoto]]
[s][vp 9 2 65535 40709 0 0]斡夷Qu姻 hace la polic胤a?![n]Justo cuando es m茨s necesaria...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_07_ [Makoto]]
[s][vp 9 2 65535 40257 0 0]斡Olvidaos de los perfiles[n]criminales de los Ladrones[n]Fantasma y pilladlos ya![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_08_ [Makoto]]
[s][vp 9 2 65535 46063 0 0]斡夷Cu茨ndo piensan arrestar[n]a los Ladrones Fantasma?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_09_ [Makoto]]
[s][vp 9 2 65535 44907 0 0]Entonces, 夷los episodios[n]de descontrol fueron obra[n]de los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_10_ [Makoto]]
[s][vp 9 2 65535 42709 0 0]Su identidad me la trae al pairo.[n]Que los arresten de una vez.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_11_ [Makoto]]
[s][vp 9 2 65535 42757 0 0]夷C吋mo no van a estar locos?[n]斡Si son una banda de criminales![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_12_ [Makoto]]
[s][vp 9 2 65535 41107 0 0]Me da que todo nos lleva[n]a cuando los Ladrones Fantasma[n]aparecieron por primera vez.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_13_ [Makoto]]
[s][vp 9 2 65535 39107 0 0]No me puedo creer que los Ladrones[n]Fantasma sean unos delincuentes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_14_ [Makoto]]
[s][vp 9 2 65535 38460 0 0]Mira que regodearse[n]con la muerte de alguien...[n]Est茨n mal de la cabeza.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_15_ [Makoto]]
[s][vp 9 2 65535 40857 0 0]Los episodios de descontrol dan[n]mucho miedo. Alguien tiene que[n]hacer algo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_16_ [Makoto]]
[s][vp 9 2 65535 39005 0 0]Los Ladrones Fantasma[n]son una panda de asesinos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_01_ [Makoto]]
[s][vp 9 2 65535 42503 0 0]Shido hace honor a su nombre.[n]Es el liderazgo en persona.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_02_ [Makoto]]
[s][vp 9 2 65535 41504 0 0]Shido ha estado parti姻ndose[n]el lomo 雨ltimamente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_03_ [Makoto]]
[s][vp 9 2 65535 41100 0 0]Shido tiene un no s姻 qu姻[n]que hace que destaque[n]sobre los dem茨s.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_04_ [Makoto]]
[s][vp 9 2 65535 39000 0 0]斡Los dem茨s pol胤ticos[n]no me inspiran la misma confianza![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_05_ [Makoto]]
[s][vp 9 2 65535 39804 0 0]夷No crees que el se隠or Shido[n]est茨 de buen ver?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_06_ [Makoto]]
[s][vp 9 2 65535 38453 0 0]Shido es la clase de pol胤tico[n]que necesitamos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_07_ [Makoto]]
[s][vp 9 2 65535 41300 0 0]El se隠or Shido tiene un aura[n]especial. 斡No hay nadie como 姻l![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_08_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Qu姻 sorpresa. Shido es muy joven,[n]pero tiene una visi吋n[n]muy clara del futuro.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_09_ [Makoto]]
[s][vp 9 2 65535 40354 0 0]斡Ese tal Shido[n]parece muy competente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_10_ [Makoto]]
[s][vp 9 2 65535 43704 0 0]Shido es un diputado incre胤ble,[n]夷a que s胤?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_11_ [Makoto]]
[s][vp 9 2 65535 42754 0 0]斡Se comenta que Shido, el pol胤tico,[n]es nuestra esperanza![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_12_ [Makoto]]
[s][vp 9 2 65535 46050 0 0]斡He asistido a un discurso[n]de ese tal Shido y creo que puede[n]cambiar las cosas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_13_ [Makoto]]
[s][vp 9 2 65535 38403 0 0]斡El se隠or Shido[n]est茨 en plena forma 雨ltimamente![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_14_ [Makoto]]
[s][vp 9 2 65535 43953 0 0]斡He escuchado much胤simo[n]el nombre de Shido estos d胤as![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_15_ [Makoto]]
[s][vp 9 2 65535 44753 0 0]斡A diferencia del resto[n]de pol胤ticos, Shido tiene[n]un carisma especial![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_01_ [Makoto]]
[s][vp 9 2 65535 43910 0 0]Espero que, tras la muerte[n]de ese Ladr吋n Fantasma,[n]el mundo sea un lugar mejor.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_02_ [Makoto]]
[s][vp 9 2 65535 37602 0 0]No sab胤a que ese Ladr吋n Fantasma[n]era solo un cr胤o.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_03_ [Makoto]]
[s][vp 9 2 65535 42154 0 0]斡夷Que el Ladr吋n Fantasma[n]se ha suicidado?! 夷Lo dices en serio?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_04_ [Makoto]]
[s][vp 9 2 65535 39001 0 0]Me da igual que sea menor...[n]斡Tiene que responsabilizarse![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_05_ [Makoto]]
[s][vp 9 2 65535 38401 0 0]Venga, hombre. No te suicides[n]en cuanto te atrapan.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_06_ [Makoto]]
[s][vp 9 2 65535 39157 0 0]夷Se ha suicidado[n]para no confesar sus cr胤menes?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_07_ [Makoto]]
[s][vp 9 2 65535 39705 0 0]Seguro que los episodios[n]de descontrol han llegado a su fin.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_08_ [Makoto]]
[s][vp 9 2 65535 44202 0 0]夷El Ladr吋n Fantasma[n]se ha suicidado?[n]Pero si solo lo hab胤an arrestado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_09_ [Makoto]]
[s][vp 9 2 65535 39504 0 0]斡夷El l胤der de los Ladrones Fantasma[n]al que pillaron se ha suicidado?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_10_ [Makoto]]
[s][vp 9 2 65535 40355 0 0]No tendr胤a que haberse suicidado[n]solo porque lo arrestaran.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_11_ [Makoto]]
[s][vp 9 2 65535 42154 0 0]夷Es cierto que el Ladr吋n Fantasma[n]era un estudiante?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_12_ [Makoto]]
[s][vp 9 2 65535 42352 0 0]Nunca hubiese pensado[n]que el Ladr吋n Fantasma era menor.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_13_ [Makoto]]
[s][vp 9 2 65535 42302 0 0]夷Se ha suicidado en la c茨rcel?[n]Qu姻 final tan repentino.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_14_ [Makoto]]
[s][vp 9 2 65535 45311 0 0]Si el Ladr吋n Fantasma[n]ha muerto, eso quiere decir[n]que estamos a salvo, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_15_ [Makoto]]
[s][vp 9 2 65535 39355 0 0]斡夷Que el Ladr吋n Fantasma[n]se ha suicidado?! 夷Lo dices en serio?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_01_ [Makoto]]
[s][vp 9 2 65535 40750 0 0]斡Podemos confiar en que Shido[n]arreglar茨 el mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_02_ [Makoto]]
[s][vp 9 2 65535 41353 0 0]Solo tenemos que poner a Shido[n]al mando. Har茨 los cambios[n]que la sociedad necesita.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_03_ [Makoto]]
[s][vp 9 2 65535 40400 0 0]斡Shido ser茨 un gran l胤der[n]para el pa胤s![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_04_ [Makoto]]
[s][vp 9 2 65535 39361 0 0]斡El se隠or Shido mejorar茨 nuestra[n]naci吋n! 斡S姻 que puede hacerlo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_05_ [Makoto]]
[s][vp 9 2 65535 38403 0 0]斡Dicen que Shido[n]va a revolucionar el mundo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_06_ [Makoto]]
[s][vp 9 2 65535 41850 0 0]Shido va a mejorar el pa胤s.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_07_ [Makoto]]
[s][vp 9 2 65535 45904 0 0]La gente habla sobre que Shido[n]sea el pr吋ximo primer ministro...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_08_ [Makoto]]
[s][vp 9 2 65535 46100 0 0]斡Shido va a ganar las elecciones![n]斡Recordad mis palabras![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_09_ [Makoto]]
[s][vp 9 2 65535 38804 0 0]斡El se隠or Shido[n]traer茨 la revoluci吋n![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_10_ [Makoto]]
[s][vp 9 2 65535 43003 0 0]斡Shido va a cambiar Jap吋n![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_11_ [Makoto]]
[s][vp 9 2 65535 42454 0 0]斡Shido tiene la victoria[n]en el bolsillo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_12_ [Makoto]]
[s][vp 9 2 65535 45253 0 0]El se隠or Shido[n]va a transformar el pa胤s.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_13_ [Makoto]]
[s][vp 9 2 65535 42850 0 0]斡Espero grandes cosas de usted,[n]se隠or Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_14_ [Makoto]]
[s][vp 9 2 65535 41853 0 0]斡Con Shido en el poder,[n]no hay de qu姻 preocuparse![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_15_ [Makoto]]
[s][vp 9 2 65535 40400 0 0]斡El se隠or Shido es el mejor l胤der[n]para nuestro futuro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_01_ [Makoto]]
[s][vp 9 2 65535 39503 0 0]No entiendo mucho de pol胤tica,[n]pero 斡Shido es una apuesta segura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_02_ [Makoto]]
[s][vp 9 2 65535 41953 0 0]Qu姻 ganas tengo de ver[n]las medidas que Shido[n]tiene preparadas para el pa胤s.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_03_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]斡Shido es de fiar![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_04_ [Makoto]]
[s][vp 9 2 65535 39350 0 0]斡Seguro que Shido conduce a nuestra[n]naci吋n hacia la grandeza![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_05_ [Makoto]]
[s][vp 9 2 65535 41750 0 0]斡Shido es la persona[n]que el mundo necesita![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_06_ [Makoto]]
[s][vp 9 2 65535 42053 0 0]斡Masayoshi Shido ser茨 el l胤der[n]del pr吋ximo gobierno![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_07_ [Makoto]]
[s][vp 9 2 65535 41653 0 0]No s姻 por qu姻, pero me parece[n]natural confiar en Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_08_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]斡Tengo ganas de ver qu姻 tiene[n]pensado Shido para el pa胤s![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_09_ [Makoto]]
[s][vp 9 2 65535 41753 0 0]斡Con Masayoshi Shido al mando,[n]podremos dormir tranquilos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_10_ [Makoto]]
[s][vp 9 2 65535 43403 0 0]Shido ser茨 el nuevo primer ministro[n]tras las elecciones, 夷me equivoco?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_11_ [Makoto]]
[s][vp 9 2 65535 42603 0 0]斡Shido va a cambiar[n]el mundo entero![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_12_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]No corre ning雨n rumor extra隠o[n]sobre Shido, as胤 que puedo votarlo[n]con tranquilidad.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_13_ [Makoto]]
[s][vp 9 2 65535 40161 0 0]斡A partir de ahora, Shido llevar茨[n]a Jap吋n hacia el futuro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_14_ [Makoto]]
[s][vp 9 2 65535 45511 0 0]Shido tiene un aire diferente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_15_ [Makoto]]
[s][vp 9 2 65535 38961 0 0]斡Nadie puede vencer a Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_16_ [Makoto]]
[s][vp 9 2 65535 39353 0 0]斡Nuestro gobierno ya est茨[n]en buenas manos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_01_ [Makoto]]
[s][vp 9 2 65535 42251 0 0]夷No se supone que ese Ladr吋n[n]Fantasma estaba muerto?[n]夷Qu姻 narices pasa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_02_ [Makoto]]
[s][vp 9 2 65535 41954 0 0]夷Qu姻 opinas de lo que dijeron[n]cuando piratearon la emisi吋n?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_03_ [Makoto]]
[s][vp 9 2 65535 41405 0 0]夷Importa siquiera qui姻n[n]tiene raz吋n?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_04_ [Makoto]]
[s][vp 9 2 65535 39355 0 0]夷Qu姻 est茨 pasando?[n]夷Qu姻 se supone que tenemos[n]que hacer ahora?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_05_ [Makoto]]
[s][vp 9 2 65535 38201 0 0]Yo ya no s姻 qu姻 pensar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_06_ [Makoto]]
[s][vp 9 2 65535 45509 0 0]Dudo que Shido haga lo que[n]los Ladrones Fantasma[n]le han pedido...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_07_ [Makoto]]
[s][vp 9 2 65535 41105 0 0]夷Es verdad lo que dicen[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_08_ [Makoto]]
[s][vp 9 2 65535 41457 0 0]夷De qu姻 iba todo lo de[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_09_ [Makoto]]
[s][vp 9 2 65535 40155 0 0]Ya no lo s姻.[n]Seguro que a Shido le ir茨 bien.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_10_ [Makoto]]
[s][vp 9 2 65535 44901 0 0]夷Por qu姻 estamos hablando otra vez[n]de los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_11_ [Makoto]]
[s][vp 9 2 65535 43355 0 0]斡Todo ir茨 bien si lo dejamos[n]en manos de Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_12_ [Makoto]]
[s][vp 9 2 65535 44757 0 0]夷Otra vez los Ladrones Fantasma?[n]夷Qu姻 est茨 pasando?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_13_ [Makoto]]
[s][vp 9 2 65535 41909 0 0]夷Por qu姻 han vuelto a aparecer[n]los Ladrones Fantasma de repente?[n]No lo entiendo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_14_ [Makoto]]
[s][vp 9 2 65535 39155 0 0]Los Ladrones Fantasma[n]est茨n mintiendo, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_15_ [Makoto]]
[s][vp 9 2 65535 43205 0 0]Los Ladrones Fantasma deben estar[n]invent茨ndose todo lo que dicen.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_16_ [Makoto]]
[s][vp 9 2 65535 39352 0 0]Ahora que han vuelto los Ladrones[n]Fantasma, no s姻 qu姻 pensar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_01_ [Makoto]]
[s][vp 9 2 65535 42252 0 0]Se supon胤a que Shido iba[n]a cambiar las cosas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_02_ [Makoto]]
[s][vp 9 2 65535 41202 0 0]No me lo puedo creer.[n]夷Shido? No puede ser cierto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_03_ [Makoto]]
[s][vp 9 2 65535 41252 0 0]Shido no dimitir茨, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_04_ [Makoto]]
[s][vp 9 2 65535 39702 0 0]Pensaba que pod胤a confiar en Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_05_ [Makoto]]
[s][vp 9 2 65535 38102 0 0]No podemos ni fiarnos de Shido.[n]夷Qu姻 nos va a pasar?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_06_ [Makoto]]
[s][vp 9 2 65535 39855 0 0]夷Que Shido no se encuentra bien?[n]Pero acabar茨 volviendo, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_07_ [Makoto]]
[s][vp 9 2 65535 46102 0 0]Yo pensaba que Shido iba[n]a cambiar este pa胤s.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_08_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]夷Qu姻 vamos a hacer sin Shido?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_09_ [Makoto]]
[s][vp 9 2 65535 38702 0 0]Espero que Shido est姻 bien.[n]Habr茨 estado trabajando demasiado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_10_ [Makoto]]
[s][vp 9 2 65535 45652 0 0]Me preocupa su salud.[n]Espero que no est姻 pensando[n]en dimitir.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_11_ [Makoto]]
[s][vp 9 2 65535 42452 0 0]El pa胤s se ir茨 al traste sin Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_12_ [Makoto]]
[s][vp 9 2 65535 39702 0 0]No, se隠or Shido...[n]No puede ser cierto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_13_ [Makoto]]
[s][vp 9 2 65535 40552 0 0]夷Qu姻 vamos a hacer sin Shido?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_14_ [Makoto]]
[s][vp 9 2 65535 45302 0 0]No... 斡Vuelva, se隠or Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_15_ [Makoto]]
[s][vp 9 2 65535 42152 0 0]Shido ya ha ganado.[n]Espero que no dimita.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_16_ [Makoto]]
[s][vp 9 2 65535 39705 0 0]Hablaba con tanto 胤mpetu...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_01_ [Makoto]]
[s][vp 9 2 65535 39105 0 0]Da igual de qui姻n nos fiemos.[n]Nada cambiar茨.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_02_ [Makoto]]
[s][vp 9 2 65535 44702 0 0]Esto es in雨til...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_03_ [Makoto]]
[s][vp 9 2 65535 38302 0 0]Se acab吋...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_04_ [Makoto]]
[s][vp 9 2 65535 40052 0 0]Ya no me creo nada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_05_ [Makoto]]
[s][vp 9 2 65535 41952 0 0]Nada va a cambiar...[n]No hay nada que podamos hacer.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_06_ [Makoto]]
[s][vp 9 2 65535 38455 0 0]Es imposible...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_07_ [Makoto]]
[s][vp 9 2 65535 45452 0 0]Que alguien transforme este pa胤s,[n]por favor...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_08_ [Makoto]]
[s][vp 9 2 65535 44805 0 0]Ya me da igual.[n]Nada va a cambiar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_09_ [Makoto]]
[s][vp 9 2 65535 37802 0 0]Estamos perdidos.[n]Que alguien haga algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_10_ [Makoto]]
[s][vp 9 2 65535 39052 0 0]Me da igual qui姻n,[n]pero que alguien nos salve...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_11_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]夷C吋mo ha pasado esto?[n]Alguien deber胤a hacer algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_12_ [Makoto]]
[s][vp 9 2 65535 41552 0 0]Sin el se隠or Shido, nuestro pa胤s[n]est茨 acabado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_13_ [Makoto]]
[s][vp 9 2 65535 44902 0 0]Que alguien nos salve...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_14_ [Makoto]]
[s][vp 9 2 65535 39152 0 0]Estamos acabados...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_15_ [Makoto]]
[s][vp 9 2 65535 46202 0 0]夷Qu姻 va a pasar?[n]Alguien nos tiene que ayudar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_16_ [Makoto]]
[s][vp 9 2 65535 41152 0 0]夷Y qu姻 hacemos?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_01_ [Makoto]]
[s][vp 9 2 65535 39054 0 0]夷Qu姻 necesitas adem茨s[n]de lo esencial?[n]El minimalismo es incre胤ble.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_02_ [Makoto]]
[s][vp 9 2 65535 41850 0 0]Mi familia ha crecido, as胤 que[n]no puedo estar de brazos cruzados.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_03_ [Makoto]]
[s][vp 9 2 65535 39954 0 0]夷Esto? Es un regalo para mi madre.[n]Le doy uno cada a隠o.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_04_ [Makoto]]
[s][vp 9 2 65535 40053 0 0]Ahora que no hay incidentes[n]en Jap吋n, se vive muy bien.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_05_ [Makoto]]
[s][vp 9 2 65535 40153 0 0]En el lugar de siempre, 夷verdad?[n]Seguro que las chicas vendr茨n[n]de todos modos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_06_ [Makoto]]
[s][vp 9 2 65535 39850 0 0]夷Puedes guardarme la botella?[n]A la pr吋xima vendr姻 con mi mujer.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_07_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]A雨n usa la corbata que[n]le regal姻 la primera vez.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_08_ [Makoto]]
[s][vp 9 2 65535 39702 0 0]Esa chica ha vuelto y...[n]Espera, 夷no la recuerdas?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_09_ [Makoto]]
[s][vp 9 2 65535 59020 0 0]Lo siento, tengo que llevar[n]a mi hija a clase.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_10_ [Makoto]]
[s][vp 9 2 65535 38103 0 0]Hoy tengo pr茨cticas... 斡Puede que[n]est姻 libre por la noche![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_11_ [Makoto]]
[s][vp 9 2 65535 37703 0 0]18 puntos ya son m茨s que[n]la 雨ltima vez. 斡Al姻grate![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_12_ [Makoto]]
[s][vp 9 2 65535 46050 0 0]Que nos juntemos todos as胤[n]me recuerda a los viejos tiempos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_13_ [Makoto]]
[s][vp 9 2 65535 43905 0 0]夷Mi tabla de snowboard?[n]Qu姻datela, que yo ya no la uso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_14_ [Makoto]]
[s][vp 9 2 65535 39501 0 0]Oye, 斡夷qu姻 ha pasado[n]con el traslado?![n]夷No te dieron la orden?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_15_ [Makoto]]
[s][vp 9 2 65535 38954 0 0]夷No vas a buscar trabajo?[n]Ah, que est茨s estudiando.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_16_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]夷Viaje de negocios al extranjero?[n]Yo no... 夷Conoces a alguien[n]que haya hecho uno?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_01_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_02_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_03_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_04_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_05_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_06_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_07_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_08_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_09_ [Makoto]]
[s][vp 9 2 65535 40152 0 0]夷Ha cambiado algo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_10_ [Makoto]]
[s][vp 9 2 65535 39752 0 0]Me parece que ir姻 a mi ritmo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_11_ [Makoto]]
[s][vp 9 2 65535 37700 0 0]夷Sabes? Puede que haga algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_12_ [Makoto]]
[s][vp 9 2 65535 40652 0 0]No s姻 si el mundo mejorar茨...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_13_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_14_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_15_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_01_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_02_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_03_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_04_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_05_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_06_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_07_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_08_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_09_ [Makoto]]
[s][vp 9 2 65535 41610 0 0]Quiero volverme rico r茨pido.[n]夷C吋mo podr胤a conseguirlo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_10_ [Makoto]]
[s][vp 9 2 65535 41509 0 0]No es culpa m胤a...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_11_ [Makoto]]
[s][vp 9 2 65535 42452 0 0]No va a cambiar nada,[n]as胤 que paso de tomarme[n]las cosas en serio.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_12_ [Makoto]]
[s][vp 9 2 65535 45060 0 0]Todos los d胤as son igual[n]de aburridos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_13_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_14_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_15_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_01_ [Makoto]]
[s][vp 9 2 65535 39802 0 0]Esto es serio. Las cosas[n]no pueden seguir as胤...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_02_ [Makoto]]
[s][vp 9 2 65535 45654 0 0]夷Has visto las noticias sobre[n]el accidente? La forma en que[n]descarril吋 fue catastr吋fica...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_03_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]夷El tren a雨n no ha llegado?[n]Uf, menudo pe隠azo.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_04_ [Makoto]]
[s][vp 9 2 65535 41301 0 0]斡Ha sido obra de terroristas![n]斡Es la 雨nica explicaci吋n![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_05_ [Makoto]]
[s][vp 9 2 65535 38101 0 0]El tren se ha parado.[n]夷Qu姻 cojones est茨 pasando?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_06_ [Makoto]]
[s][vp 9 2 65535 38452 0 0]郁ltimamente ha habido[n]muchos accidentes. Podr胤a haber[n]otro en cualquier momento.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_07_ [Makoto]]
[s][vp 9 2 65535 40802 0 0]Aqu胤 la seguridad da pena.[n]Me da mucho miedo coger el tren.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_08_ [Makoto]]
[s][vp 9 2 65535 40952 0 0]郁ltimamente ha habido[n]muchos accidentes. Podr胤a haber[n]otro en cualquier momento.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_01_ [Makoto]]
[s][vp 9 2 65535 38504 0 0]Pues ser茨 un artista[n]muy famoso si ha salido[n]en Good Morning Japan.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_02_ [Makoto]]
[s][vp 9 2 65535 43554 0 0]Dicen que en el mundo[n]del arte japon姻s[n]nadie est茨 a su altura.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_03_ [Makoto]]
[s][vp 9 2 65535 40954 0 0]Pues ser茨 un artista[n]muy famoso si ha salido[n]en Good Morning Japan, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_04_ [Makoto]]
[s][vp 9 2 65535 46050 0 0]斡El artista Madarame[n]ha salido en Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_05_ [Makoto]]
[s][vp 9 2 65535 38800 0 0]As胤 que Madarame, el que sali吋[n]en Good Morning Japan,[n]es impresionante, 夷eh?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_06_ [Makoto]]
[s][vp 9 2 65535 45300 0 0]Dicen que en el mundo[n]del arte japon姻s[n]nadie est茨 a su altura.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_07_ [Makoto]]
[s][vp 9 2 65535 41004 0 0]Pues ser茨 un artista[n]muy famoso si ha salido[n]en Good Morning Japan, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_08_ [Makoto]]
[s][vp 9 2 65535 46058 0 0]斡El artista Madarame[n]ha salido en Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_09_ [Makoto]]
[s][vp 9 2 65535 43403 0 0]Han anunciado que va a haber[n]una exposici吋n de las obras[n]de Madarame.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_10_ [Makoto]]
[s][vp 9 2 65535 40104 0 0]Dicen que en el mundo[n]del arte japon姻s[n]nadie est茨 a su altura.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_11_ [Makoto]]
[s][vp 9 2 65535 41254 0 0]As胤 que Madarame, el que sali吋[n]en Good Morning Japan,[n]es impresionante, 夷eh?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_12_ [Makoto]]
[s][vp 9 2 65535 43450 0 0]斡En el mundo del arte japon姻s[n]no tiene rival![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_13_ [Makoto]]
[s][vp 9 2 65535 45654 0 0]Han anunciado que va a haber[n]una exposici吋n de las obras[n]de Madarame.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_14_ [Makoto]]
[s][vp 9 2 65535 39153 0 0]Dicen que en el mundo[n]del arte japon姻s[n]nadie est茨 a su altura.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_15_ [Makoto]]
[s][vp 9 2 65535 45050 0 0]斡Me han dicho que el artista[n]Madarame ha salido[n]en Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_16_ [Makoto]]
[s][vp 9 2 65535 41300 0 0]斡En el mundo del arte japon姻s[n]no tiene rival![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_01_ [Makoto]]
[s][vp 9 2 65535 41602 0 0]夷Es cierto que ni la polic胤a[n]ha podido ponerles la mano encima?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_02_ [Makoto]]
[s][vp 9 2 65535 37604 0 0]Dicen que usan trucos realmente[n]sucios. Son lo peor.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_03_ [Makoto]]
[s][vp 9 2 65535 40602 0 0]He o胤do que mucha gente ha sido[n]v胤ctima de estos enga隠os...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_04_ [Makoto]]
[s][vp 9 2 65535 44201 0 0]夷Qu姻 est茨 haciendo la polic胤a?[n]A este paso, m茨s gente[n]saldr茨 mal parada...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_05_ [Makoto]]
[s][vp 9 2 65535 40302 0 0]夷Tambi姻n amenazan a tus familiares?[n]Qu姻 miedo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_06_ [Makoto]]
[s][vp 9 2 65535 41852 0 0]Dicen que usan trucos realmente[n]sucios. Son lo peor.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_07_ [Makoto]]
[s][vp 9 2 65535 44502 0 0]He o胤do que mucha gente ha sido[n]v胤ctima de estos enga隠os...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_08_ [Makoto]]
[s][vp 9 2 65535 43201 0 0]夷Qu姻 est茨 haciendo la polic胤a?[n]A este paso, m茨s gente[n]saldr茨 mal parada...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_09_ [Makoto]]
[s][vp 9 2 65535 40555 0 0]夷Es cierto que ni la polic胤a[n]ha podido ponerles la mano encima?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_10_ [Makoto]]
[s][vp 9 2 65535 39802 0 0]Dicen que usan trucos realmente[n]sucios. Son lo peor.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_11_ [Makoto]]
[s][vp 9 2 65535 40654 0 0]Dicen que te obligan[n]a hacer cosas horribles[n]si te atrapan...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_12_ [Makoto]]
[s][vp 9 2 65535 41301 0 0]夷Qu姻 est茨 haciendo la polic胤a?[n]A este paso, m茨s gente[n]saldr茨 mal parada...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_13_ [Makoto]]
[s][vp 9 2 65535 43002 0 0]夷Es cierto que ni la polic胤a[n]ha podido ponerles la mano encima?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_14_ [Makoto]]
[s][vp 9 2 65535 45505 0 0]Dicen que usan trucos realmente[n]sucios. Son lo peor.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_15_ [Makoto]]
[s][vp 9 2 65535 39955 0 0]He o胤do que mucha gente ha sido[n]v胤ctima de estos enga隠os...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_16_ [Makoto]]
[s][vp 9 2 65535 45252 0 0]夷Qu姻 est茨 haciendo la polic胤a?[n]A este paso, m茨s gente[n]saldr茨 mal parada...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_01_ [Makoto]]
[s][vp 9 2 65535 43150 0 0]Me muero de ganas de ver[n]a las chicas con yukata.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_02_ [Makoto]]
[s][vp 9 2 65535 38811 0 0]夷Qui姻n tiene tiempo para ir a ver[n]los fuegos artificiales?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_03_ [Makoto]]
[s][vp 9 2 65535 40203 0 0]Quiz茨s deber胤a ir[n]a ver el espect茨culo[n]de fuegos artificiales...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_04_ [Makoto]]
[s][vp 9 2 65535 41405 0 0]No recuerdo la 雨ltima vez que[n]vi fuegos artificiales.[n]No he parado de trabajar...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_05_ [Makoto]]
[s][vp 9 2 65535 40500 0 0]Hay un espect茨culo de fuegos[n]artificiales, 夷no? 夷Vas a ir?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_06_ [Makoto]]
[s][vp 9 2 65535 38451 0 0]夷Qui姻n tiene tiempo para ir a ver[n]los fuegos artificiales?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_07_ [Makoto]]
[s][vp 9 2 65535 44853 0 0]Quiz茨s deber胤a ir[n]a ver el espect茨culo[n]de fuegos artificiales...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_08_ [Makoto]]
[s][vp 9 2 65535 41005 0 0]No recuerdo la 雨ltima vez que[n]vi fuegos artificiales.[n]No he parado de trabajar...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_09_ [Makoto]]
[s][vp 9 2 65535 39805 0 0]Un festival de fuegos artificiales...[n]Espero que no ensucien mucho[n]la calle de mi tienda.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_10_ [Makoto]]
[s][vp 9 2 65535 38802 0 0]S胤, claro... Haya fuegos artificiales[n]o no, no me dan el d胤a libre.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_11_ [Makoto]]
[s][vp 9 2 65535 38954 0 0]夷Y si vamos a ligar con t胤os?[n]斡Seguro que ser胤a entretenido![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_12_ [Makoto]]
[s][vp 9 2 65535 39003 0 0]No recuerdo la 雨ltima vez[n]que vi unos fuegos artificiales.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_13_ [Makoto]]
[s][vp 9 2 65535 39803 0 0]Yukatas por todos lados...[n]斡Esto me encanta![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_14_ [Makoto]]
[s][vp 9 2 65535 39850 0 0]斡Hay que llevar la yukata[n]con estilo![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_15_ [Makoto]]
[s][vp 9 2 65535 39658 0 0]斡Mira este yukata![n]斡El dise隠o es mon胤simo![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_16_ [Makoto]]
[s][vp 9 2 65535 39703 0 0]夷Cu茨nto van a durar[n]los fuegos artificiales?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_01_ [Makoto]]
[s][vp 9 2 65535 41607 0 0]夷Has visto la rueda de prensa[n]del se隠or Okumura? Menuda locura...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_02_ [Makoto]]
[s][vp 9 2 65535 45001 0 0]Se han pasado mucho...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_03_ [Makoto]]
[s][vp 9 2 65535 40607 0 0]Lo que le ha pasado al se隠or[n]Okumura no ha sido un montaje,[n]夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_04_ [Makoto]]
[s][vp 9 2 65535 42157 0 0]Puso los ojos en blanco...[n]Qu姻 mal rollo.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_05_ [Makoto]]
[s][vp 9 2 65535 41602 0 0]Ha sido una ejecuci吋n p雨blica.[n]Qu姻 horror...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_06_ [Makoto]]
[s][vp 9 2 65535 41857 0 0]Se han pasado mucho...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_07_ [Makoto]]
[s][vp 9 2 65535 44202 0 0]Lo que le ha pasado al se隠or[n]Okumura no ha sido un montaje,[n]夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_08_ [Makoto]]
[s][vp 9 2 65535 46107 0 0]Puso los ojos en blanco...[n]Qu姻 mal rollo.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_09_ [Makoto]]
[s][vp 9 2 65535 42302 0 0]Lo que le ha pasado a Okumura[n]ha sido horripilante.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_10_ [Makoto]]
[s][vp 9 2 65535 37857 0 0]La rueda de prensa[n]ha sido impactante.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_11_ [Makoto]]
[s][vp 9 2 65535 38252 0 0]夷Has visto la rueda de prensa?[n]斡Me ha dejado de piedra![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_12_ [Makoto]]
[s][vp 9 2 65535 43207 0 0]Han sido los Ladrones[n]Fantasma, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_13_ [Makoto]]
[s][vp 9 2 65535 43057 0 0]Lo que le ha pasado a Okumura[n]ha sido horripilante.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_14_ [Makoto]]
[s][vp 9 2 65535 38460 0 0]La rueda de prensa[n]ha sido impactante.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_15_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]No eran efectos especiales, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_16_ [Makoto]]
[s][vp 9 2 65535 45057 0 0]Han sido los Ladrones[n]Fantasma, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_01_ [Makoto]]
[s][vp 9 2 65535 44904 0 0]Akechi, el detective,[n]es muy inteligente.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_02_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_03_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_04_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_05_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_06_ [Makoto]]
[s][vp 9 2 65535 42050 0 0]Todav胤a est茨 en el instituto,[n]pero el detective Akechi[n]ha conseguido un mont吋n de cosas.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_07_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_08_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_09_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_10_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_11_ [Makoto]]
[s][vp 9 2 65535 38904 0 0]Akechi es inteligente y guapo.[n]斡Lo tiene todo![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_12_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_13_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_14_ [Makoto]]
[s][vp 9 2 65535 39154 0 0]夷Has o胤do hablar[n]del detective ese, Akechi?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_15_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_201_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_01_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_02_ [Makoto]]
[s][vp 9 2 65535 41957 0 0]夷C吋mo sabemos si seguir茨n yendo[n]solo a por quienes lo merecen?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_03_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_04_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_05_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_06_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_07_ [Makoto]]
[s][vp 9 2 65535 45157 0 0]Controlan como quieren el coraz吋n[n]de las personas para que hagan[n]lo que les venga en gana.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_08_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_09_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_10_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_11_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_12_ [Makoto]]
[s][vp 9 2 65535 45257 0 0]夷C吋mo podemos estar seguros[n]de que no ir茨n a por nadie[n]que no sea malvado?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_13_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_14_ [Makoto]]
[s][vp 9 2 65535 39157 0 0]Controlar a la gente... Tiene raz吋n,[n]es bastante sospechoso.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_15_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_202_16_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_01_ [Makoto]]
[s][vp 9 2 65535 38700 0 0]斡Ojal茨 tuviera una cita[n]con una chica guapa![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_02_ [Makoto]]
[s][vp 9 2 65535 38800 0 0]Acaba de pasar una chica[n]despampanante...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_03_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]No pasa nada,[n]pero que no se retrase.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_04_ [Makoto]]
[s][vp 9 2 65535 39354 0 0]Ah, 夷tendr姻 menos estr姻s[n]si hago ejercicio?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_05_ [Makoto]]
[s][vp 9 2 65535 38750 0 0]斡Eh, f胤jate en esa![n]Vaya, ya se ha ido.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_06_ [Makoto]]
[s][vp 9 2 65535 37800 0 0]斡Las chicas de hoy en d胤a[n]est茨n tremendas![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_07_ [Makoto]]
[s][vp 9 2 65535 45151 0 0]斡Me voy a cabrear mucho si llego[n]tarde por el retraso del tren![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_08_ [Makoto]]
[s][vp 9 2 65535 38052 0 0]S姻 que hacer ejercicio[n]es lo mejor, pero...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_09_ [Makoto]]
[s][vp 9 2 65535 38101 0 0]Estoy en tensi吋n vaya a donde vaya.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_10_ [Makoto]]
[s][vp 9 2 65535 38802 0 0]Ojal茨 llovieran millones del cielo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_11_ [Makoto]]
[s][vp 9 2 65535 40802 0 0]Ese accidente no fue[n]un ataque terrorista, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_12_ [Makoto]]
[s][vp 9 2 65535 38052 0 0]Mi hijo no estudia nunca.[n]Solo le importa salir de marcha.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_13_ [Makoto]]
[s][vp 9 2 65535 37552 0 0]夷Es deportista y guapa?[n]Qu姻 injusta es la vida...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_14_ [Makoto]]
[s][vp 9 2 65535 38802 0 0]Todos los d胤as acabo hecho polvo.[n]Me merezco una palmadita[n]en la espalda.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_15_ [Makoto]]
[s][vp 9 2 65535 39302 0 0]Parece que ya no hay ning雨n[n]lugar seguro...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_16_ [Makoto]]
[s][vp 9 2 65535 40952 0 0]Uf, al menos podr胤as[n]lavarte el uniforme.[n][f 1 2 180][e]

[msg MSG_HOMELESS_DAY_001_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷Pasa algo? Aunque me gusta[n]que me prestes atenci吋n.[n][w][e]
[s][vp 8 2 1 0 30 0]Como soy mayor que t雨, perm胤teme[n]un consejo. No caigas tan bajo[n]como he ca胤do yo.[n][w][e]
[s][vp 8 2 1 0 30 0]No lo digo por asustarte, pero, si[n]no andas con ojo, la vida se[n]puede ir al traste en un momento.[n][w][e]

[msg MSG_HOMELESS_DAY_002_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷Eh? 夷Necesitas algo?[n][w][e]

[sel SEL_HOMELESS_DAY_002_0_0 top]
[s]Solo estaba mirando.[e]
[s]夷Te resulta dif胤cil vivir as胤?[e]

[msg MSG_HOMELESS_DAY_002_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Mmm, supongo que no te sueles[n]topar con gente como yo.[n]Se te hace raro, 夷verdad?[n][w][e]
[s][vp 8 2 1 0 30 0]Yo eleg胤 esta vida y tengo que[n]apechugar, pero t雨 debes andar[n]con pies de plomo.[n][w][e]
[s][vp 8 2 1 0 30 0]Tengo amigos que han tocado[n]fondo por dejarse engatusar[n]por gente sin escr雨pulos.[n][w][e]

[msg MSG_HOMELESS_DAY_002_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ja, ja, me emociona que te[n]preocupes por m胤. Calma, ya estoy[n]acostumbrado. Saldr姻 adelante.[n][w][e]
[s][vp 8 2 1 0 30 0]Llevo este estilo de vida[n]desde que tengo uso de raz吋n,[n]pero me falla la memoria.[n][w][e]
[s][vp 8 2 1 0 30 0]En realidad, me cuesta recordar[n]cualquier cosa que pase de noche.[n]Supongo que no es para tanto.[n][w][e]

[msg MSG_HOMELESS_NIGHT_002_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]夷Qu姻 quieres...?[n]Vete a casa si quieres salir ileso.[n][w][e]

[sel SEL_HOMELESS_NIGHT_002_0 top]
[s]Nada.[e]
[s]Lo siento.[e]
[s]夷Qu姻 est茨s haciendo?[e]

[msg MSG_HOMELESS_NIGHT_002_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Tss... As胤 que solo me est茨s[n]tomando el pelo. Da igual.[n][w][e]
[s][vp 8 2 1 0 30 0]夷Te has enterado del accidente[n]del otro d胤a? 斡Qu姻 divertido![n][w][e]
[s][vp 8 2 1 0 30 0]La gente est茨 ansiosa.[n]Amo ver el miedo en sus caras.[n][w][e]

[msg MSG_HOMELESS_NIGHT_002_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]S胤, es buena idea que los chavales[n]como t雨 se茨is sinceros.[n][w][e]
[s][vp 8 2 1 0 30 0]Aqu胤, en la ciudad, podr胤as salir[n]herido por meterte en los asuntos[n]de otro, 夷sabes? Ve con cuidado.[n][w][e]

[msg MSG_HOMELESS_NIGHT_002_3 [Vagabundo]]
[s][vp 8 2 1 0 30 0]A ti qu姻 te importa.[n]C吋mo viva no tiene nada[n]que ver contigo, chaval.[n][w][e]
[s][vp 8 2 1 0 30 0]Aqu胤, en la ciudad, podr胤as salir[n]herido por meterte en los asuntos[n]de otro, 夷sabes? Ve con cuidado.[n][w][e]

[msg MSG_HOMELESS_DAY_003_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Oye, quisiera hacerte una pregunta.[n][w][e]
[s][vp 8 2 1 0 30 0]Dicen que este 或Madarame位 goza[n]de mucha reputaci吋n. 夷Tan bueno es?[n][w][e]

[sel SEL_HOMELESS_DAY_003_0_0 top]
[s]Es bastante famoso.[e]
[s]Tan solo es una mala persona.[e]

[msg MSG_HOMELESS_DAY_003_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ya veo. Todav胤a se le da bien[n]hacerle creer a la gente[n]lo que quiere.[n][w][e]

[msg MSG_HOMELESS_DAY_003_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷Eh? 夷Corre alg雨n rumor sobre 姻l?[n][w][e]

[msg MSG_HOMELESS_DAY_003_3_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Tengo un amigo que asegura ser[n]antiguo alumno suyo. Por lo visto,[n]tuvo una experiencia horrible...[n][w][e]
[s][vp 8 2 1 0 30 0]La verdad es que no le he pedido[n]detalles. No me gusta meterme[n]en la vida de nadie.[n][w][e]

[msg MSG_HOMELESS_NIGHT_003_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 3 10 0 10]Tal y como pensaba, a la gente[n]le encanta que ese viejo pellejo[n]se ponga grandilocuente.[n][w][e]
[s][vp 8 2 1 0 30 0]Me pregunto cu茨ntos[n]habr茨n sufrido por su culpa.[n]Aunque tampoco me importa.[n][w][e]

[msg MSG_HOMELESS_DAY_004_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]He vuelto a encontrar dinero en mi[n]bolsillo. Lo malo es que no s姻 c吋mo[n]ha llegado hasta ah胤.[n][w][e]

[sel SEL_HOMELESS_DAY_004_0_0 top]
[s]Tienes suerte.[e]
[s]夷Te has vuelto senil?[e]
[s]夷Qu姻 ha pasado?[e]

[msg MSG_HOMELESS_DAY_004_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Lamento discrepar. Me desagrada[n]descubrir que llevo dinero y no[n]conocer su procedencia.[n][w][e]
[s][vp 8 2 1 0 30 0]Nunca s姻 c吋mo deshacerme de 姻l,[n]por eso siempre lo dejo[n]en una caja de donativos.[n][w][e]
[s][vp 8 2 1 0 30 0]Ser胤a interesante pedirle[n]a ese genial detective[n]que resolviera este misterio...[n][w][e]

[msg MSG_HOMELESS_DAY_004_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Siendo sincero, no puedo negarlo.[n][w][e]
[s][vp 8 2 1 0 30 0]夷Ser姻 son茨mbulo? Siempre acabo[n]en otro lugar en mitad de la noche.[n][w][e]
[s][vp 8 2 1 0 30 0]夷No crees que Shibuya es un sitio[n]peligroso de noche? 夷Y si padezco[n]un episodio de descontrol?[n][w][e]

[msg MSG_HOMELESS_DAY_004_3_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]No es ninguna novedad,[n]pero tengo un problema[n]y hay cosas que no recuerdo.[n][w][e]
[s][vp 8 2 1 0 30 0]Lo que peor recuerdo es lo que[n]pasa por la noche. Me da[n]bastante miedo, la verdad.[n][w][e]
[s][vp 8 2 1 0 30 0]Ser胤a interesante pedirle[n]a ese genial detective[n]que resolviera este misterio...[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Tss, 夷es esto todo[n]lo que queda de ese dinero?[n]Con lo que sufr胤 para conseguirlo.[n][w][e]

[sel SEL_HOMELESS_NIGHT_004_0 top]
[s]Qu姻 envidia.[e]
[s]Encuentra algo que hacer.[e]
[s]夷Qu姻 est茨s haciendo aqu胤?[e]

[msg MSG_HOMELESS_NIGHT_004_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Que te calles.[n]P胤rate de una vez, chaval.[n][w][e]
[s][vp 8 2 1 0 30 0]Shibuya es un lugar genial[n]de noche. Je. Aunque un chaval[n]como t雨 no lo entender胤a.[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]No te preocupes, trabajo haciendo[n]lo que quiero. Es como si Shibuya[n]de noche existiera solo para m胤.[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_3 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Eh, eso digo yo.[n][w][e]
[s][vp 8 2 1 0 30 0]Cuidado, chaval. No puedes ir[n]por ah胤 meti姻ndote en los asuntos[n]ajenos en esta ciudad.[n][w][e]

[msg MSG_HOMELESS_NIGHT_004_4 [Vagabundo]]
[s][vp 8 2 1 0 30 0]De acuerdo. Hora de salir[n]y hacer pasta. Me voy a oxidar[n]como me quede sentado todo el rato.[n][w][e]

[msg MSG_HOMELESS_DAY_005_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]N-no... 斡No tengo nada de valor![n]斡Por favor, estoy sin blanca![n]D姻jame en paz.[n][w][e]
[s][vp 8 2 1 0 30 0]夷Eh? 夷No vienes a robarme?[n]斡Pues no me des estos sustos![n][w][e]

[sel SEL_HOMELESS_DAY_005_0_0 top]
[s]Est茨s exagerando.[e]
[s]Perd吋n.[e]
[s]夷Qu姻 ha sucedido?[e]

[msg MSG_HOMELESS_DAY_005_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Es que 雨ltimamente ha habido una[n]oleada de asaltos y robos por aqu胤.[n]Mis amigos los han sufrido.[n][w][e]
[s][vp 8 2 1 0 30 0]Seg雨n dicen, hay un solo culpable[n]detr茨s de todo esto. M茨s te vale[n]ir con cuidado, jovencito.[n][w][e]

[msg MSG_HOMELESS_DAY_005_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]No, soy yo el que se ha precipitado[n]en sacar conclusiones.[n][w][e]
[s][vp 8 2 1 0 30 0]Como de costumbre, Shibuya es un[n]lugar traicionero de noche.[n][w][e]

[msg MSG_HOMELESS_DAY_005_3_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷Est茨s al tanto del incidente de[n]Madarame? Una organizaci吋n[n]de Shibuya estaba en el ajo.[n][w][e]
[s][vp 8 2 1 0 30 0]La tensi吋n en la ciudad se va a[n]disparar con tanto dinero[n]movi姻ndose de tapadillo.[n][w][e]

[msg MSG_HOMELESS_NIGHT_005_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]夷Qu姻 quieres, chaval? Vas a salir[n]herido si sales a merodear[n]de noche por aqu胤.[n][w][e]

[sel SEL_HOMELESS_NIGHT_005_0 top]
[s]No me importa.[e]
[s]Tendr姻 cuidado.[e]
[s]夷Shibuya es peligrosa?[e]

[msg MSG_HOMELESS_NIGHT_005_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Cada vez hay m茨s ni隠atos[n]que buscan pelea con tipos como yo.[n][w][e]
[s][vp 8 2 1 0 30 0]No s姻 qui姻n fue la 雨ltima vez,[n]pero le di su merecido.[n]Deber胤as andarte con ojo. 斡Ja, ja![n][w][e]

[msg MSG_HOMELESS_NIGHT_005_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]S胤, mucho hablar,[n]pero en realidad no vas[n]a hacerlo, 夷a que no?[n][w][e]
[s][vp 8 2 1 0 30 0]La gente puede decir lo que quiera,[n]pero har茨 lo que le d姻 la gana[n]por turbio que sea, como Madarame.[n][w][e]

[msg MSG_HOMELESS_NIGHT_005_3 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Un chaval胤n escu茨lido como t雨[n]deber胤a andar con ojo. Este lugar[n]har胤a llorar hasta al m茨s pintado.[n][w][e]
[s][vp 8 2 1 0 30 0]Hablando de llorar,[n]夷qu姻 te parece el Madarame ese?[n]Lo ha confesado todo. 斡Me meo![n][w][e]

[msg MSG_HOMELESS_DAY_006_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷Eh? 夷Qu姻 pasa? 夷Est茨s aburrido?[n][w][e]

[sel SEL_HOMELESS_DAY_006_0_0 top]
[s]Exactamente.[e]
[s]Estoy demasiado ocupado.[e]
[s]Solo miraba.[e]

[msg MSG_HOMELESS_DAY_006_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Mira en el pasaje subterr茨neo de la[n]estaci吋n de Shibuya. Hay ofertas de[n]trabajo junto a las escaleras.[n][w][e]
[s][vp 8 2 1 0 30 0]Yo tambi姻n he pensado en buscar[n]empleo, pero 夷qui姻n me va a querer[n]con estas pintas? Ja, ja.[n][w][e]

[msg MSG_HOMELESS_DAY_006_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Eso est茨 bien. Seguro que,[n]a tu edad, prefieres la diversi吋n[n]al trabajo.[n][w][e]

[msg MSG_HOMELESS_DAY_006_3_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Oye, me gustar胤a preguntarte algo.[n]En la ciudad, la gente habla sobre[n]unos Ladrones Fantasma.[n][w][e]
[s][vp 8 2 1 0 30 0]夷Qu姻 trucos usar茨n para despertar[n]los corazones? 斡Ja, ja![n]Supongo que no tienes ni idea.[n][w][e]

[msg MSG_HOMELESS_DAY_006_4_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ah, bien. Si por casualidad te[n]cruzas conmigo de noche, te sugiero[n]guardar cierta distancia, 夷vale?[n][w][e]

[msg MSG_HOMELESS_NIGHT_006_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]夷Qu姻 hay? Estoy de buen humor,[n]as胤 que te har姻 compa隠胤a.[n][w][e]

[sel SEL_HOMELESS_NIGHT_006_0 top]
[s]夷C吋mo est茨 la econom胤a?[e]
[s]No tengo nada que decir.[e]

[msg MSG_HOMELESS_NIGHT_006_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]S姻 de un trabajo que te har茨 rico.[n]Puedo enchufarte, pero tendr茨s[n]que borrarte del mapa legalmente.[n][w][e]
[s][vp 8 2 1 0 30 0]No, hombre, que te estoy[n]tomando el pelo. Je, je.[n][w][e]

[msg MSG_HOMELESS_NIGHT_006_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Pues ve a casa, chaval.[n]No es mi problema si te quedas[n]y te pasa algo.[n][w][e]
[s][vp 8 2 1 0 30 0]De noche, este es nuestro mundo.[n]Je, je.[n][w][e]

[msg MSG_HOMELESS_NIGHT_006_4 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Me encanta la noche,[n]puedo ser totalmente libre.[n][w][e]

[msg MSG_HOMELESS_DAY_007_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷Eh? 夷Necesitas algo?[n][w][e]

[sel SEL_HOMELESS_DAY_007_0_0 top]
[s]Solo quiero hablar un poco.[e]
[s]En realidad, nada.[e]
[s]夷C吋mo est茨 la ciudad 雨ltimamente?[e]

[msg MSG_HOMELESS_DAY_007_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]A ver... Sabes que los Ladrones[n]Fantasma han enviado un aviso,[n]夷verdad?[n][w][e]
[s][vp 8 2 1 0 30 0]Seguro que va a causar[n]un gran revuelo por aqu胤.[n][w][e]

[msg MSG_HOMELESS_DAY_007_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Oh, cierto. 夷Lo has visto?[n][w][e]
[s][vp 8 2 1 0 30 0]夷Has visto el aviso de[n]los Ladrones Fantasma? Lo que hacen[n]es muy interesante[n][w][e]

[msg MSG_HOMELESS_DAY_007_3_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]La gente no para de hablar[n]del aviso que han enviado[n]los Ladrones Fantasma.[n][w][e]
[s][vp 8 2 1 0 30 0]En los bajos fondos reinan[n]los matones. Es un asco. 夷D吋nde[n]ha quedado el c吋digo de honor?[n][w][e]

[msg MSG_HOMELESS_NIGHT_007_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Eh, es el chaval noct茨mbulo[n]de nuevo. 夷Qu姻 quieres?[n][w][e]

[sel SEL_HOMELESS_NIGHT_007_0 top]
[s]Solo quiero hablar un poco.[e]
[s]En realidad, nada.[e]
[s]夷C吋mo est茨 la ciudad 雨ltimamente?[e]

[msg MSG_HOMELESS_NIGHT_007_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]He o胤do que los Ladrones Fantasma[n]est茨n yendo a por la mafia. Bah,[n]solo son un pu隠ado de ni隠os.[n][w][e]
[s][vp 8 2 1 0 30 0]Si los acariciara con un cuchillo,[n]estoy seguro de que saldr胤an[n]corriendo. 斡Ja, ja, ja![n][w][e]

[msg MSG_HOMELESS_NIGHT_007_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Por culpa de esos Ladrones Fantasma,[n]hay mucha m茨s pasma por esta zona.[n][w][e]
[s][vp 8 2 1 0 30 0]Tss. El aviso ese de las narices[n]me lo ha puesto todo m茨s dif胤cil.[n][w][e]

[msg MSG_HOMELESS_NIGHT_007_3 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Los matones de Shibuya est茨n dando[n]guerra porque los Ladrones Fantasma[n]han enviado un aviso.[n][w][e]
[s][vp 8 2 1 0 30 0]A ver, tampoco es todo malo. Me lo[n]paso bien llev茨ndome por delante[n]a algunos de ellos... Je, je.[n][w][e]

[msg MSG_HOMELESS_DAY_008_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Siento que mis amigos me est茨n evitando...[n]夷Tendr茨 或eso位 algo que ver?[n][w][e]

[sel SEL_HOMELESS_DAY_008_0_0 top]
[s]夷A qu姻 te refieres con 或eso位?[e]
[s]夷Te odian?[e]

[msg MSG_HOMELESS_DAY_008_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Todos huyen en cuanto me ven[n]la cara, pero no s姻[n]muy bien por qu姻...[n][w][e]

[msg MSG_HOMELESS_DAY_008_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ja, ja... No creo haber hecho nada[n]para que la gente corra[n]de esa manera.[n][w][e]

[msg MSG_HOMELESS_DAY_008_4_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Oye, 夷puedo hacerte una pregunta?[n][w][e]
[s][vp 8 2 1 0 30 0]夷Crees que una persona[n]puede cambiar radicalmente[n]de la noche a la ma隠ana?[n][w][e]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]No, lo siento. No importa...[n][w][e]

[msg MSG_HOMELESS_NIGHT_008_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Mmm... 夷qu姻 quieres, chaval?[n][w][e]

[sel SEL_HOMELESS_NIGHT_008_0 top]
[s]夷La zona ya est茨 tranquila?[e]
[s]Nada.[e]
[s]夷No te vas a dormir?[e]

[msg MSG_HOMELESS_NIGHT_008_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]S胤, las cosas se calmaron tras el[n]arresto de Kaneshiro. Los Ladrones[n]Fantasma lo han conseguido.[n][w][e]
[s][vp 8 2 1 0 30 0]Despertar un coraz吋n suena[n]disparatado, pero 夷sabes qu姻?[n]Hace la vida algo m茨s interesante.[n][w][e]

[msg MSG_HOMELESS_NIGHT_008_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Desde que los Ladrones Fantasma se[n]encargaron de Kaneshiro, la ciudad[n]est茨 sumida en el silencio.[n][w][e]
[s][vp 8 2 1 0 30 0]Tss, esto no es Shibuya si no hay[n]ning雨n peligro al acecho.[n][w][e]

[msg MSG_HOMELESS_NIGHT_008_3 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Je, je. Oye, trabajo de noche.[n]Si tienes un encargo, deja[n]una carta en ese cubo de basura.[n][w][e]
[s][vp 8 2 1 0 30 0]Si hay alg雨n capullo[n]que quieres que liquide,[n]d姻jamelo a m胤. 斡Ja, ja, ja![n][w][e]

[msg MSG_HOMELESS_DAY_009_0_0 [Vagabundo]]
[s][f 4 23 1 30 5 10 4 10][vp 8 2 1 0 30 0]夷Yo? 夷Pegar a mis propios amigos?[n]Imposible. Pero es cierto[n]que no recuerdo nada...[n][w][e]

[sel SEL_HOMELESS_DAY_009_0_0 top]
[s]夷Est茨s bien?[e]
[s]夷No te acuerdas?[e]

[msg MSG_HOMELESS_DAY_009_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]S-s胤... Estoy bien...[n][w][e]
[s][vp 8 2 1 0 30 0]Todas las ma隠anas me despierto[n]asustado. Me siento como si... Como[n]si no fuera yo mismo.[n][w][e]

[msg MSG_HOMELESS_DAY_009_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Es como si mis recuerdos[n]estuvieran difusos, como[n]si todo fuera un sue隠o.[n][w][e]
[s][vp 8 2 1 0 30 0]Como si mi cerebro... o el propio[n]mundo se reescribiera totalmente...[n][w][e]

[msg MSG_HOMELESS_DAY_009_3_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷Ser茨 cosa de los Ladrones[n]Fantasma? No... No puede ser.[n][w][e]

[msg MSG_HOMELESS_NIGHT_009_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]夷Qu姻 quieres? Estoy muy de mala[n]hostia ahora mismo.[n][w][e]

[sel SEL_HOMELESS_NIGHT_009_0 top]
[s]夷Por qu姻?[e]
[s]C茨lmate.[e]

[msg MSG_HOMELESS_NIGHT_009_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Esto no tiene nada que ver contigo.[n][w][e]
[s][vp 8 2 1 0 30 0]Si juego bien mis cartas, puede que[n]los Ladrones Fantasma carguen[n]con las culpas de mi trabajo...[n][w][e]
[s][vp 8 2 1 0 30 0]Ay, 斡夷qu姻 co隠o?![n]P胤rate de aqu胤. 斡Vete![n][w][e]

[msg MSG_HOMELESS_NIGHT_009_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Mmm... Un viejo cabr吋n ha intentado[n]entrar en mi territorio, as胤 que[n]he hecho que se vaya amablemente.[n][w][e]
[s][vp 8 2 1 0 30 0]Si no quieres que te pase lo mismo,[n]al姻jate de ese cubo de basura.[n][w][e]
[s][vp 8 2 1 0 30 0]Aunque si tienes una solicitud[n]para m胤, la cosa cambia... Je, je.[n][w][e]

[msg MSG_HOMELESS_DAY_010_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]He hecho cosas horribles...[n]Como siga as胤, puede[n]que pronto llegue mi fin.[n][w][e]

[sel SEL_HOMELESS_DAY_010_0_0 top]
[s]夷Qu姻 ha pasado?[e]
[s]Contr吋late.[e]

[msg MSG_HOMELESS_DAY_010_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]No, nada. Parece que sigo[n]siendo... yo.[n][w][e]
[s][vp 8 2 1 0 30 0]Oye, 夷t雨 crees que se puede[n]despertar el coraz吋n de la gente?[n][w][e]

[msg MSG_HOMELESS_DAY_010_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]No, estoy bien. Parece que...[n]sigo siendo yo.[n][w][e]
[s][vp 8 2 1 0 30 0]Los Ladrones Fantasma despiertan[n]corazones, 夷no? Sinceramente, ojal茨[n]despertaran el de... ya sabes.[n][w][e]

[msg MSG_HOMELESS_DAY_010_4_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Voy a intentar convencerlo[n]escribi姻ndole otra carta.[n]Mejor eso que nada.[n][w][e]

[msg MSG_HOMELESS_NIGHT_010_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]夷Ese t胤o nos ha dejado otra carta[n]en el bolsillo? No voy a cambiar[n]de opini吋n. Deber胤a rendirse ya.[n][w][e]

[sel SEL_HOMELESS_NIGHT_010_0 top]
[s]夷Una carta?[e]
[s]夷A qui姻n te refieres con 或ese t胤o位?[e]

[msg MSG_HOMELESS_NIGHT_010_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]As胤 que estabas escuchando.[n]Mira, puede que salgas herido si[n]metes las narices donde no debes.[n][w][e]
[s][vp 8 2 1 0 30 0]Eh, las cartas escritas y las notas[n]son muy 雨tiles. Una vez que[n]las quemas, no quedan pruebas.[n][w][e]
[s][vp 8 2 1 0 30 0]Usar internet deja huella.[n]En mi trabajo, todo se tramita[n]en papel.[n][w][e]
[s][vp 8 2 1 0 30 0]Je, ni siquiera Medjed sabr茨 jam茨s[n]lo que est茨 escrito[n]en esta nota. 斡Ja, ja![n][w][e]

[msg MSG_HOMELESS_NIGHT_010_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]As胤 que estabas escuchando.[n]L茨rgate si no quieres salir herido.[n][w][e]
[s][vp 8 2 1 0 30 0]Cuanto m茨s luches y te resistas,[n]peor lo vas a pasar, 夷sabes?[n][w][e]
[s][vp 8 2 1 0 30 0]Aunque, para m胤, es mucho m茨s[n]divertido de esta forma. Je, je.[n][w][e]

[msg MSG_HOMELESS_DAY_011_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]*suspiro* 夷Necesitas algo,[n]jovencito?[n][w][e]

[sel SEL_HOMELESS_DAY_011_0_0 top]
[s]夷C吋mo te ha ido?[e]
[s]夷Te preocupa algo?[e]

[msg MSG_HOMELESS_DAY_011_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Vaya donde vaya, la gente habla[n]de los Ladrones Fantasma. Se les[n]considera h姻roes modernos.[n][w][e]
[s][vp 8 2 1 0 30 0]Si les pidiera ayuda,[n]tal vez pudieran despejar[n]mi cabeza de una vez... *suspiro*[n][w][e]

[msg MSG_HOMELESS_DAY_011_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Algo as胤. Quiz茨 deber胤a[n]preguntarles a esos Ladrones Fant...[n][w][e]
[s][vp 8 2 1 0 30 0]Bah, olv胤dalo. No me hagas caso.[n][w][e]

[msg MSG_HOMELESS_DAY_011_3_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]He hallado dinero y un cuchillo[n]ensangrentado en mi ropa. Y no es[n]la primera vez que me pasa...[n][w][e]
[s][vp 8 2 1 0 30 0]Cada vez son m茨s largos los lapsos[n]de tiempo que paso en blanco.[n]Nadie entiende lo que me pasa...[n][w][e]

[msg MSG_HOMELESS_NIGHT_011_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Ahora estoy de buen humor,[n]as胤 que si quieres hablar,[n]te har姻 compa隠胤a.[n][w][e]

[sel SEL_HOMELESS_NIGHT_011_0 top]
[s]No tengo nada de lo que hablar.[e]
[s]夷Ha pasado algo?[e]

[msg MSG_HOMELESS_NIGHT_011_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Bastante, gracias al alboroto[n]causado por esos Ladrones Fantasma.[n]Espero que sigan as胤.[n][w][e]
[s][vp 8 2 1 0 30 0]Para m胤, es m茨s f茨cil actuar si[n]la polic胤a est茨 centrada en ellos.[n]Nah, te estoy vacilando. Je, je.[n][w][e]

[msg MSG_HOMELESS_NIGHT_011_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]夷Qu姻? Pues deja de aburrirme[n]y l茨rgate. Fuera.[n][w][e]
[s][vp 8 2 1 0 30 0]夷Por qu姻 no pides a tu mami[n]que te compre juguetes[n]de los Ladrones Fantasma?[n][w][e]

[msg MSG_HOMELESS_NIGHT_011_3 [Vagabundo]]
[s][vp 8 2 1 0 30 0]El trabajo me va bien.[n]夷Acaso quieres contratarme?[n][w][e]
[s][vp 8 2 1 0 30 0]Deja tus datos aqu胤 y el efectivo[n]en el cubo. Desapariciones,[n]accidentes... Lo que t雨 quieras.[n][w][e]
[s][vp 8 2 1 0 30 0]No dejar姻 ni una sola prueba,[n]igual que los Ladrones Fantasma.[n]斡Ja, ja![n][w][e]

[msg MSG_HOMELESS_DAY_012_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Q-quiero conocer a los Ladrones[n]Fantasma. Quiero que despierten[n]el coraz吋n de alguien...[n][w][e]

[sel SEL_HOMELESS_DAY_012_0_0 top]
[s]夷El coraz吋n de qui姻n?[e]
[s]Yo me encargo.[e]

[msg MSG_HOMELESS_DAY_012_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Esa es una pregunta[n]que ni yo sabr胤a responder.[n][w][e]
[s][vp 8 2 1 0 30 0]Puede que acabe dando con esta[n]persona si espero frente[n]a Okumura Foods.[n][w][e]

[msg MSG_HOMELESS_DAY_012_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ja, ja, agradezco que intentes[n]ayudarme. Pareces todo[n]un Ladr吋n Fantasma.[n][w][e]
[s][vp 8 2 1 0 30 0]Sin embargo, ni siquiera s姻 qui姻n[n]ser茨 la pr吋xima v胤ctima... Disculpa,[n]estoy pensando en voz alta.[n][w][e]

[msg MSG_HOMELESS_NIGHT_012_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]夷Qu姻 quieres? Tengo mucho tiempo,[n]as胤 que si necesitas algo,[n]soy todo o胤dos.[n][w][e]

[sel SEL_HOMELESS_NIGHT_012_0 top]
[s]夷Est茨s aburrido?[e]
[s]Yo paso.[e]

[msg MSG_HOMELESS_NIGHT_012_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]S胤, ahora tengo mucho tiempo.[n]Poco a poco, he sido capaz[n]de estar m茨s tiempo fuera.[n][w][e]
[s][vp 8 2 1 0 30 0]Parece que ser姻 libre en breve.[n]Ese t胤o me est茨 buscando, su[n]coraz吋n es cada vez m茨s d姻bil.[n][w][e]
[s][vp 8 2 1 0 30 0]夷Que de qui姻n estoy hablando...?[n]斡De alguien muy cercano! 斡Ja, ja![n][w][e]

[msg MSG_HOMELESS_NIGHT_012_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]No seas as胤. Mira, est茨n pasando[n]un mont吋n de movidas divertidas[n]e interesantes. Por ejemplo...[n][w][e]
[s][vp 8 2 1 0 30 0]夷Sabes que ese capullo finolis[n]recibi吋 un aviso? Por fin capta la[n]atenci吋n de los Ladrones Fantasma.[n][w][e]
[s][vp 8 2 1 0 30 0]Est茨n castigando a gente chunga[n]que la ley no puede pillar.[n]Son igualitos que yo. 斡Ja, ja, ja![n][w][e]

[msg MSG_HOMELESS_DAY_013_0_0 [Vagabundo]]
[s][vp 8 2 65535 0 0 0]...[n][w][e]

[sel SEL_HOMELESS_DAY_013_0_0 top]
[s]夷Est茨s bien?[e]
[s]夷Est茨s enfermo?[e]

[msg MSG_HOMELESS_DAY_013_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷Eh? Oh... 夷Necesitas algo?[n][w][e]
[s][vp 8 2 1 0 30 0]郁ltimamente no he pasado mucho[n]tiempo consciente. Temo que se[n]apodere de m胤 si me duermo.[n][w][e]

[msg MSG_HOMELESS_DAY_013_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷Enfermo? Conque es eso...[n][w][e]
[s][vp 8 2 1 0 30 0]Quiz茨 esto sea de lo que[n]la gente habla, lo de perder[n]la cabeza...[n][w][e]
[s][vp 8 2 1 0 30 0]Aunque no suena mal del todo.[n]Mientras el otro tambi姻n[n]desaparezca...[n][w][e]

[msg MSG_HOMELESS_NIGHT_013_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 0 10 0 10]Je, je. Qu姻 noche tan maja.[n]Tengo que disfrutar por completo[n]de mi tiempo fuera, de mi libertad...[n][w][e]
[s][vp 8 2 1 0 30 0]夷Y t雨, qu姻?[n]夷Tambi姻n disfrutas de la vida?[n][w][e]

[sel SEL_HOMELESS_NIGHT_013_0 top]
[s]Algo as胤, s胤.[e]
[s]S胤, as胤 es.[e]
[s]El mundo da asco.[e]

[msg MSG_HOMELESS_NIGHT_013_1 [Vagabundo]]
[s][vp 8 2 1 0 30 0]夷Algo as胤? Ja, qu姻 mediocre.[n]夷Sabes? El mundo es un juego.[n]O somos jugadores, o somos piezas.[n][w][e]
[s][vp 8 2 1 0 30 0]夷Eres un jugador, o una pieza[n]a la que manipulan?[n]Te vendr胤a bien pensar en eso.[n][w][e]

[msg MSG_HOMELESS_NIGHT_013_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Qu姻 sonrisa tan burlona.[n]Veo que lo captas. La vida es solo[n]un juego, y t雨 sabes c吋mo jugarlo.[n][w][e]
[s][vp 8 2 1 0 30 0]Si llegas a aburrirte de seguir el[n]camino correcto, te podr胤a ense隠ar[n]a pas茨rtelo mejor.[n][w][e]

[msg MSG_HOMELESS_NIGHT_013_3 [Vagabundo]]
[s][vp 8 2 1 0 30 0]夷Sabes qu姻? Tienes raz吋n.[n]Este mundo es lo peor,[n]sin duda alguna.[n][w][e]
[s][vp 8 2 1 0 30 0]Todo lo que tiene son adultos[n]asquerosos tocando las narices,[n]como moscas. Yo soy un matamoscas.[n][w][e]

[msg MSG_HOMELESS_DAY_014_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]斡Podr胤a haberles pedido ayuda a los[n]Ladrones Fantasma mucho antes si[n]hubiera sabido su nombre![n][w][e]
[s][vp 8 2 1 0 30 0]Por mucho que lo intente, no logro[n]recordar. Nadie parece conocer mi[n]pasado. 夷Qu姻 hago?[n][w][e]
[s][vp 8 2 1 0 30 0]夷Sabr茨 algo? Es que me[n]resulta imposible dar con 姻l...[n][w][e]
[s][vp 8 2 1 0 30 0]Por favor, que alguien me ayude...[n][w][e]

[msg MSG_HOMELESS_NIGHT_014_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 3 10 0 10]Mierda, 斡qu姻 cabr吋n...![n]夷A qu姻 ha venido esa paliza?[n][w][e]
[s][vp 8 2 1 0 30 0]夷Ha intentado suicidarse[n]para detenerme o qu姻?[n]Je, pero le falta valor.[n][w][e]
[s][vp 8 2 1 0 30 0]Da igual. Ese t胤o va a desaparecer[n]bien pronto, y entonces solo[n]quedar姻 yo en este cuerpo. Je, je.[n][w][e]

[msg MSG_HOMELESS_DAY_015_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Nombre... Mi nombre...[n][w][e]
[s][vp 8 2 1 0 30 0]Se lo pregunt姻 a la polic胤a y al[n]tipo ese de negro con el que habl姻[n]el otro d胤a, pero nadie sabe nada...[n][w][e]
[s][vp 8 2 1 0 30 0]Por favor... Que alguien me diga[n]algo. 夷C吋mo me llamo?[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 0 10]夷No te dije que no hablaras con mi[n]yo diurno? Si me necesitas,[n]deja una carta en el cubo.[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_1 [Agente trajeado]]
[s][vp 8 2 1 0 31 0][f 4 23 1 31 5 10 4 10]Lo siento, pero deb胤a confirmar[n]que el exmercenario 或Yohei[n]Kiritani位 hab胤a perdido la memoria.[n][w][e]

[msg MSG_HOMELESS_NIGHT_015_2 [Vagabundo]]
[s][vp 8 2 1 0 30 0]斡No vuelvas a decir ese puto[n]nombre! 斡夷Quieras que tambi姻n[n]me deshaga de ti?![n][w][e]

[msg MSG_HOMELESS_NIGHT_015_3 [Agente trajeado]]
[s][vp 8 2 1 0 31 0]P-por supuesto que no.[n]No podr胤a hacer nada...[n][w][e]

[msg MSG_quest29_morgana_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Creo que ya tenemos al objetivo.[n]斡Hay que pensar un buen plan[n]en el escondite![n][w][e]

[msg MSG_YOKOKUJYOU_GET_HIRU [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷Yohei Kiritani?[n]Yohei... Me suena ...[n][w][e]
[s][vp 8 2 1 0 30 0]Es... 斡夷mi nombre?! 夷Quiere decir[n]que los Ladrones Fantasma...?[n][w][e]

[msg MSG_YOKOKUJYOU_GET_YORU [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 0 10]Mierda, 夷c吋mo han descubierto[n]mi maldito nombre?[n][w][e]
[s][vp 8 2 1 0 30 0]夷Van a intentar eliminarme?[n]Bien, que vengan.[n]Me deshar姻 de ellos...[n][w][e]

[msg MSG_HOMELESS_DAY_016_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ahora lo recuerdo todo...[n]Todo lo que he hecho...[n]斡Ay, mi cabeza![n][w][e]

[sel SEL_HOMELESS_DAY_016_0_0 top]
[s]夷Est茨s bien?[e]
[s]Ve al hospital.[e]

[msg MSG_HOMELESS_DAY_016_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]S胤, gracias... Empec姻 a enfermar[n]cuando mis recuerdos volvieron.[n][w][e]

[msg MSG_HOMELESS_DAY_016_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Agradezco el inter姻s, pero no[n]merezco que me atiendan[n]en ning雨n hospital.[n][w][e]

[msg MSG_HOMELESS_DAY_016_3_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0]Por unas cuantas monedas, fui[n]capaz de causar da隠os irreparables[n]a mucha gente...[n][w][e]
[s][vp 8 2 1 0 30 0]夷Me han salvado los Ladrones[n]Fantasma? No puede ser. Ellos...[n][w][e]

[msg MSG_HOMELESS_DAY_017_0_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]夷T雨 no tienes nada que quieras[n]borrar de tu pasado?[n][w][e]

[sel SEL_HOMELESS_DAY_017_0_0 top]
[s]Claro.[e]
[s]No.[e]
[s]夷Y t雨?[e]

[msg MSG_HOMELESS_DAY_017_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]A雨n eres joven.[n]Deber胤as organizar tu vida[n]de una vez por todas.[n][w][e]

[msg MSG_HOMELESS_DAY_017_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Ya veo... Da igual. Sin embargo,[n]quiz茨 un d胤a te arrepientas de[n]los errores que hayas cometido.[n][w][e]

[msg MSG_HOMELESS_DAY_017_3_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]S胤, ojal茨 pudiera olvidar ciertas[n]cosas. Cre胤a que ya las hab胤a[n]enterrado, pero me equivocaba.[n][w][e]

[msg MSG_HOMELESS_DAY_017_4_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0]A partir de ahora, afrontar姻[n]mis delitos. Los Ladrones Fantasma[n]me han salvado.[n][w][e]
[s][vp 8 2 1 0 30 0]Por eso me emocion姻 tanto[n]al saber que estaban vivos.[n]Me hizo muy feliz.[n][w][e]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]A雨n eres joven. Vive plenamente[n]para que, a diferencia de m胤[n]no tengas que arrepentirte de nada.[n][w][e]

[msg MSG_HOMELESS_DAY_018_0_0 [Vagabundo]]
[s][vp 8 2 1 0 65535 0]Oye, 夷no crees que en esta ciudad[n]pasa algo raro?[n][w][e]
[s][vp 8 2 1 0 65535 0]Todo el mundo parece[n]muy feliz de repente.[n][w][e]
[s][vp 8 2 1 0 65535 0]夷Qu姻 narices est茨 pasando?[n]Da hasta miedo.[n][w][e]

[msg MSG_HOMELESS_DAY_019_0_0 [Vagabundo]]
[s][vp 8 2 1 0 65535 0]Puede parecer que vivir en la calle[n]no tiene nada de bueno.[n][w][e]
[s][vp 8 2 1 0 65535 0]Pero la libertad que te da[n]tiene su gracia.[n][w][e]

[sel SEL_HOMELESS_DAY_019_0_0 top]
[s]夷Ya no te acuerdas?[e]
[s]夷Qu姻 ocurre?[e]
[s]夷Seguro?[e]

[msg MSG_HOMELESS_DAY_019_1_0 [Vagabundo]]
[s][vp 8 2 1 0 65535 0]No, no me acuerdo de nada.[n]No tengo recuerdos del pasado.[n][w][e]
[s][vp 8 2 1 0 65535 0]Pero el pasado da igual, 夷verdad?[n]Ja, ja, ja...[n][w][e]

[msg MSG_HOMELESS_DAY_019_2_0 [Vagabundo]]
[s][vp 8 2 1 0 65535 0]Te pregunto lo mismo.[n]夷Me conoces o algo?[n][w][e]
[s][vp 8 2 1 0 65535 0]Es que no recuerdo nada[n]de mi pasado. 斡Ja, ja, ja![n][w][e]

[msg MSG_HOMELESS_DAY_019_3_0 [Vagabundo]]
[s][vp 8 2 1 0 65535 0]S胤, se est茨 muy bien sin tener que[n]preocuparse de nada. 斡No recuerdo[n]mi pasado, pero me siento libre![n][w][e]
[s][vp 8 2 1 0 65535 0]Eso demuestra que el pasado[n]no es necesario para vivir,[n]夷no crees? 斡Ja, ja, ja![n][w][e]

[msg MSG_HOMELESS_DAY_020_0_0 [Vagabundo]]
[s][vp 8 2 1 0 65535 0]No pareces contento.[n][w][e]
[s][vp 8 2 1 0 65535 0]Siempre veo a gente as胤[n]por la ciudad, perdidos[n]entre un mar de gente feliz.[n][w][e]
[s][vp 8 2 1 0 65535 0]Pero 夷qu姻 te preocupa tanto?[n][w][e]
[s][vp 8 2 1 0 65535 0]Ser胤a mejor que olvidaras[n]lo malo y vivieras como yo...[n][w][e]

[msg MSG_HOMELESS_DAY_021_0_0 [Vagabundo]]
[s][vp 8 2 1 0 65535 0]Es la temporada de las despedidas,[n]夷eh? Me pone un poco triste[n]dejar este lugar.[n][w][e]

[sel SEL_HOMELESS_DAY_021_0_0 top]
[s]夷Ad吋nde vas?[e]

[msg MSG_HOMELESS_DAY_021_1_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]No podr姻 expiar mis pecados[n]si estoy indeciso. Encontrar姻[n]un trabajo en un lugar tranquilo.[n][w][e]

[msg MSG_HOMELESS_DAY_021_2_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Es agradable tener a alguien[n]que venga a despedirse de m胤.[n]Gracias, significa mucho.[n][w][e]

[msg MSG_HOMELESS_DAY_021_3_0 [Vagabundo]]
[s][vp 8 2 1 0 30 0][f 4 23 1 30 5 10 4 10]Teniendo en cuenta lo necio[n]que soy, no estoy seguro de si[n]podr姻 expiar mis pecados.[n][w][e]
[s][vp 8 2 1 0 30 0]Pero vivir姻 el resto de mi vida[n]pensando c吋mo puedo hacerlo.[n]Adi吋s, jovencito.[n][w][e]
[s][vp 8 2 1 0 30 0]Espero verte de nuevo alg雨n d胤a...[n]si consigo convertirme[n]en un hombre decente.[n][w][e]

[msg MSG_Q83_HINT_HOMELESS_00 [Vagabundo]]
[s][vp 1 0 0 0 0 0]夷Eh? 夷Necesitas algo?[n][w][e]
[s][vp 1 0 0 0 0 0]夷Un partido ama隠ado conectado[n]con apuestas deportivas? S胤...[n]He o胤do hablar de ello.[n][w][e]
[s][vp 8 2 1 0 65535 0]Parece que lo lleva[n]una organizaci吋n peligrosa que[n]trata con mafias extranjeras.[n][w][e]
[s][vp 1 0 0 0 0 0]Y he o胤do que amenazan[n]de forma muy cruel a los jugadores,[n]sobre todo a las chicas.[n][w][e]

[sel SEL_Q83_HINT_HOMELESS_01 top]
[s]夷Por ejemplo?[e]
[s]夷Amenazas?[e]

[msg MSG_Q83_HINT_HOMELESS_02 [Vagabundo]]
[s][vp 1 0 0 0 0 0]Los amenazan de muerte si pierden,[n]aunque no creo que los maten[n]de verdad.[n][w][e]
[s][vp 1 0 0 0 0 0]Como son partidos ama隠ados,[n]no pueden ir a la polic胤a. Tienen[n]que seguir las normas establecidas.[n][w][e]

[msg MSG_CHK_Q83_HINT_HOMELES]
[s][vp 1 0 0 0 0 0]クエスト83 ヒントNPC[n]全部ヒント手に入れた[n][w][e]

[msg MSG_CHK_Q83_HINT_HOMELES_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]斡Parece que ya tenemos suficiente[n]informaci吋n! 斡Vayamos al escondite[n]a trazar un plan con los dem茨s![n][w][e]

[msg MSG_BACKGROUND_EKIIN_001 [Empleado de la estaci吋n serio]]
[s][vp 8 2 1 0 17 0]Se ruega a los viajeros de la l胤nea[n]Inogami que salgan por la v胤a[n]opuesta y sigan adelante.[n][w][e]
[s][vp 8 2 1 0 17 0]Los de las l胤neas JL y Ginza,[n]salgan por estas puertas y dir胤janse[n]hacia la salida ocho.[n][w][e]

