[msg NPC_GREETING_MSG]
[s]挨拶[n][w][e]

[msg NPC_01]
[s]会話[n][w][e]

[msg KARIOKI_NPC_grt00]
[s]……[n][w][e]

[msg KARIOKI_NPC_talk00]
[s]テスト用仮配置NPCです。[n][w][e]

[msg MSG_IJIMEKKO_001_0_0 [Alumno de pelo casta隠o]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Podr胤as cambiarte el nombre[n]de 或Hideo位 a 或Hipop吋tamo位.[n][w][e]
[s][vp 8 2 1 0 1 0]O quiz茨 Kamoshida podr胤a usarte[n]como pelota.[n][w][e]

[msg MSG_IJIMEKKO_001_1_0 [Alumno regordete]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]夷Por qu姻 dices eso?[n][w][e]

[msg MSG_IJIMEKKO_001_2_0 [Alumno de pelo casta隠o]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]No seas tan estirado. A ver si[n]aprendes a aceptar las bromas.[n][w][e]

[msg MSG_IJIMEKKO_002_0_0 [Alumno de pelo casta隠o]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Oye, mis cuatro colegas y yo[n]necesitamos copias[n]de todos tus apuntes.[n][w][e]

[msg MSG_IJIMEKKO_002_1_0 [Alumno regordete]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Claro, Takanashi... pero necesito[n]dinero para la fotocopiadora.[n][w][e]

[msg MSG_IJIMEKKO_002_2_0 [Alumno de pelo casta隠o]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]夷Tu padre no es m姻dico? Seguro[n]que 姻l te lo puede dar.[n][w][e]
[s][vp 8 2 1 0 1 0]No vengas ma隠ana[n]sin los apuntes, 夷entendido?[n][w][e]

[msg MSG_IJIMEKKO_003_0_0 [Alumno de pelo casta隠o]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Eh, Hipop吋tamo, pr姻stame pasta.[n]Mi colega anda un poco corto hoy.[n][w][e]

[msg MSG_IJIMEKKO_003_1_0 [Alumno regordete]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]夷Me lo devolver茨s?[n][w][e]

[msg MSG_IJIMEKKO_003_2_0 [Alumno de pelo casta隠o]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Cierra el pico y dame la pasta![n]Y ni se te ocurra dec胤rselo[n]a un profe.[n][w][e]
[s][vp 8 2 1 0 1 0]Todos est茨n cagados despu姻s[n]de lo que le pas吋 a Kamoshida.[n][w][e]

[msg MSG_IJIMEKKO_004_0_0 [Alumno de pelo casta隠o]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Sakoda y yo vamos a comer algo.[n]T雨 tambi姻n te vienes,[n]夷no, Hipop吋tamo? 夷Nos invitas?[n][w][e]

[msg MSG_IJIMEKKO_004_1_0 [Sakoda]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]夷Vamos al restaurante de sushi[n]que tanto le gusta a Hipop吋tamo?[n]No quiero que coma cerditos.[n][w][e]

[msg MSG_IJIMEKKO_004_2_0 [Alumno regordete]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Ah... pero...[n][w][e]

[msg MSG_IJIMEKKO_004_3_0 [Alumno de pelo casta隠o]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]A ver si lo pillas, gordo seboso.[n]斡Ser茨 mejor que no me enfades![n][w][e]

[msg MSG_quest03_morgana_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Creo que ya tenemos al objetivo.[n]斡Hay que pensar un buen plan[n]en el escondite![n][w][e]

[msg HELP_MEMENTOS_MISSION_01 [斡Incidente en la misi吋n!]]
[s]或[clr 4]Suceso en Mementos[clr 27]位[n]Objetivo identificado.[n]Habl姻moslo en el [clr 2]escondite[clr 27].[n][w][e]

[msg MSG_IJIMEKKO_004_6_0 [Alumno de pelo casta隠o]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Odio a la gente como t雨.[n]斡Eres un in雨til de mierda![n][w][e]

[msg MSG_IJIMEKKO_004_7_0 [Alumno regordete]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]No s姻 qu姻 quieres de m胤...[n][w][e]

[msg MSG_IJIMEKKO_004_8_0 [Alumno de pelo casta隠o]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Lo 雨nico bueno que tienes es que[n]est茨s forrado. 夷Lo pillas, bola[n]de sebo con patas?[n][w][e]

[msg MSG_IJIMEKKO_004_9_0 [Sakoda]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]斡Buah, Daisuke, que Hipop吋tamo[n]est茨 a punto de llorar![n][w][e]

[msg MSG_IJIMEKKO_005_0_0 [Daisuke Takanashi]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Oye... Siento mucho[n]lo malo que he sido contigo. No[n]volver茨 a ocurrir. Te lo prometo.[n][w][e]

[msg MSG_IJIMEKKO_005_1_0 [Alumno regordete]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]夷Q-qu姻 pretendes?[n]Solo quieres enga隠arme para[n]que te deje m茨s dinero.[n][w][e]

[msg MSG_IJIMEKKO_005_2_0 [Daisuke Takanashi]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Que no, en serio. Es Sakoda.[n]Me est茨 chantajeando.[n][w][e]
[s][vp 8 2 1 0 1 0]Bueno, d姻jalo, no importa.[n]Lo que quiero decir es que[n]lo siento much胤simo.[n][w][e]

[msg MSG_IJIMEKKO_005_5_0 [Daisuke Takanashi]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Lo siento mucho, y pienso[n]devolverte todo lo que te debo.[n]Te lo juro.[n][w][e]

[msg MSG_IJIMEKKO_005_6_0 [Alumno regordete]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]No te preocupes por el dinero.[n]夷T-t雨 est茨s bien?[n][w][e]

[msg MSG_IJIMEKKO_005_7_0 [Daisuke Takanashi]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]No, hablar姻 con Sakoda y recuperar姻[n]todo tu dinero.[n][w][e]
[s][vp 8 2 1 0 1 0]Me gustar胤a hacer algo bueno[n]al menos una vez. Y no pienso[n]meterte en esto.[n][w][e]

[msg MSG_quest12_morgana_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Parece que hay alguien a雨n[n]peor al mando. 斡Hay que estar[n]atentos para pillarlo![n][w][e]

[msg MSG_IJIMEKKO_006_0_0 [Sakoda]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]夷Est茨s seguro? No me creo[n]que te haga mucha gracia que[n]publique ese v胤deo en el que robas.[n][w][e]

[msg MSG_IJIMEKKO_006_1_0 [Daisuke Takanashi]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]斡Me da igual! 斡Yo solo quiero que[n]dejes de hacerme joder[n]a los dem茨s, Sakoda![n][w][e]

[msg MSG_IJIMEKKO_006_2_0 [Sakoda]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Oye, t雨 lo hiciste solito.[n]夷De verdad quieres que se lo[n]muestre a tus profes, Takanashi?[n][w][e]
[s][vp 8 2 1 0 9 0]Abre otra vez la boca y el mundo[n]entero podr茨 disfrutar de tu peli.[n][w][e]
[s]或[clr 2]Cr吋nicas de Yoshimori Sakoda[clr 27]位.[n]斡Se avecina un taquillazo![n][w][e]

[msg MSG_IJIMEKKO_006_3_0 [Daisuke Takanashi]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]斡Venga ya! 斡Si t雨 me obligastea hacerlo todo! Joder...[n][w][e]

[msg HELP_MEMENTOS_MISSION_03 [斡Incidente en la misi吋n!]]
[s]或[clr 4]Suceso en Mementos[clr 27]位[n]Objetivo identificado.[n]Reun茨monos en el [clr 2]escondite[clr 27].[n][w][e]

[msg MSG_quest12_morgana_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]As胤 que hab胤a alguien peor[n]moviendo los hilos. 斡Hay que[n]hacer algo al respecto![n][w][e]

[msg MSG_quest12_Target_Find]
[s]Ahora que tienes un objetivo, aseg雨rate[n]de que todos se unen a la misi吋n.[n]Quedad en el escondite para decidir.[n][w][e]

[msg MSG_IJIMEKKO_006_4_0 [Yoshimori Sakoda]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Eh, Takanashi![n]Vamos a comer algo.[n][w][e]
[s][vp 8 2 1 0 1 0]夷Qu姻 dices? 夷Que quieres pagar?[n]Bueno, si insistes... 斡Gracias![n][w][e]

[msg MSG_IJIMEKKO_006_5_0 [Daisuke Takanashi]]
[s][f 4 23 1 0 3 10 0 10]Mierda...[n][w][e]

[msg MSG_IJIMEKKO_007_0_0 [Yoshimori Sakoda]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]He borrado todas las fotos y[n]el v胤deo. Por favor, perd吋name.[n][w][e]

[msg MSG_IJIMEKKO_007_1_0 [Daisuke Takanashi]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]夷C吋mo voy a creerte?[n][w][e]

[msg MSG_IJIMEKKO_007_2_0 [Yoshimori Sakoda]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Tienes raz吋n. Deber胤a entregarme.[n][w][e]

[msg MSG_IJIMEKKO_007_3_0 [Daisuke Takanashi]]
[s][f 4 23 1 0 3 10 0 10][vp 8 2 1 0 0 0]Espera. Yo soy responsable[n]de mis actos, as胤 que ir姻 contigo[n]y me entregar姻 tambi姻n.[n][w][e]

[msg MSG_OOYA_001_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 8 10 0 10][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 16028 65535 0]Est茨n en guardia. Supongo que[n]les preocupaba que pudiera[n]haber un esc茨ndalo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Creo que volver姻 luego. Ser胤a[n]un engorro que llamaran[n]a la polic胤a para echarme.[n][w][e]

[msg MSG_OOYA_002_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 8 10 0 10][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 16028 65535 0]Uf... Lo 雨nico que oigo es que[n]nadie quiere comentar nada. As胤 es[n]imposible tener un buen art胤culo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No puedo ir de frente, pero ahora[n]tengo claro que est茨n[n]escondiendo algo.[n][w][e]

[msg MSG_OOYA_002_1_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 8 10 0 10][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 16021 65535 0]夷Qu姻 deber胤a hacer? Creo que[n]ha llegado el momento[n]de cambiar de t茨ctica.[n][w][e]

[msg MSG_GRT_main_All_001_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42112 0 0]夷Has visto lo que dec胤a la gente[n]en aquella p茨gina? Es 姻l...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43162 0 0]Creo que ese es el nuevo.[n]En internet lo tachaban[n]de delincuente...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42912 0 0]夷Ese es el nuevo alumno[n]con antecedentes?[n]夷Viene a estudiar aqu胤?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42313 0 0]Ahora est茨 tranquilo,[n]pero cualquiera sabe cu茨ndo la l胤a.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42863 0 0]Ap茨rtate de su camino,[n]que a saber por d吋nde sale...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43212 0 0]Espero que deje en paz a la gente[n]hasta que lo expulsen por algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43112 0 0]Me da miedo tenerlo tan cerca.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43012 0 0]夷Sigue viniendo al instituto? 夷C吋mo[n]puede tener tan poca verg鵜enza?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42562 0 0]Dicen que le ha tocado[n]las narices al profesor Kamoshida[n]y lo van a expulsar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42612 0 0]夷C吋mo? 夷Que lo van a expulsar?[n]Pero 夷qu姻 narices ha hecho?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42912 0 0]He o胤do que los expulsan[n]tanto a 姻l como a Sakamoto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42204 0 0]夷Lo has visto?[n]夷De verdad ha hecho algo Kamoshida?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42653 0 0]Ah, s胤, el aviso del tabl吋n[n]de anuncios, 夷no? 斡Qu姻 risa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42154 0 0]夷Un aviso de un Ladr吋n Fantasma?[n]斡Es la leche![n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43004 0 0]夷Van a despedir a Kamoshida?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42705 0 0]Nadie podr胤a tomarse en serio[n]esa publicaci吋n.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43255 0 0]斡Venga ya, los Ladrones Fantasma[n]no existen![n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42312 0 0]夷Ha hecho algo? Porque se le ha[n]visto mucho con Sakamoto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43013 0 0]Que lo expulsen del instituto[n]antes de que cause alg雨n problema.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43263 0 0]Kamoshida se ha pirado, as胤 que[n]dudo que lo expulsen...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43263 0 0]夷Crees que lo habr茨 amenazado?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40355 0 0]El equipo de voleibol est茨[n]acabado sin Kamoshida.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40500 0 0]Los del equipo de voleibol[n]ya no podr茨n pasearse[n]como si fueran los amos del lugar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42913 0 0]夷El instituto se ha ido al carajo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_01_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42304 0 0]夷Madarame es el artista ese?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_03_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42205 0 0]He recibido otro de esos[n]correos sospechosos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_02_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43105 0 0]He o胤do que Shibuya[n]se est茨 volviendo muy peligrosa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_205_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42655 0 0]夷Los Ladrones Fantasma[n]existen de verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40554 0 0]夷Dices que tambi姻n enviaron[n]un aviso antes de la rueda[n]de prensa de Madarame?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42454 0 0]Parece que la rueda de prensa[n]para pedir disculpas se celebr吋[n]gracias a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40505 0 0]Ahora van a por los estudiantes,[n]夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40302 0 0]Algunas de las v胤ctimas ven胤an[n]al instituto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43110 0 0]Ojal茨 los arreste la polic胤a...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42705 0 0]Dicen que los Ladrones Fantasma[n]han enviado otro aviso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42203 0 0]斡No paro de o胤r sobre[n]los avisos en Shibuya![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43204 0 0]斡Esta vez han enviado un aviso[n]a un tal Kaneshiro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42300 0 0]斡Aquel jefe de la mafia[n]ha confesado todos sus delitos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42254 0 0]Espera, 夷los Ladrones Fantasma[n]est茨n detr茨s del arresto[n]de Kaneshiro?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43306 0 0]斡No me puedo creer[n]que acabaran con ellos![n]斡Ni la polic胤a fue capaz![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42106 0 0]En el foro de los Ladrones Fantasma[n]puedes pedirles que vayan[n]a por gente que se lo merezca.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42503 0 0]斡Internet est茨 que arde[n]con los Ladrones Fantasma![n]斡Los consideran aut姻nticos h姻roes![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42606 0 0]斡Parece que hay[n]mucha gente agradecida[n]con los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 38403 0 0]Todo empez吋 aqu胤, con Kamoshida.[n]夷Crees que los Ladrones[n]Fantasma son...?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40306 0 0]夷Hay que darles las gracias[n]a los Ladrones Fantasma[n]por reformar a los malos?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 41256 0 0]斡Mola un mont吋n[n]que los Ladrones Fantasma[n]despierten corazones![n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42506 0 0]Incre胤ble, 斡los Ladrones Fantasma[n]existen de verdad![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 39403 0 0]夷Los hackers contra[n]los Ladrones Fantasma?[n]斡Qu姻 subid吋n![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 38303 0 0]Se la tienen jurada[n]a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 39804 0 0]夷C吋mo piensan acabar[n]los Ladrones Fantasma[n]con los hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 39505 0 0]夷C吋mo derrotar茨n a los hackers[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 39954 0 0]夷Cu茨l ser茨 la estrategia[n]de los Ladrones Fantasma[n]contra los ciberterroristas?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 38106 0 0]斡Los Ladrones Fantasma han[n]acabado con Medjed! 斡Son la ca隠a![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 41700 0 0]斡Akechi no sabe de lo que habla![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 38256 0 0]斡S胤, se van a convertir en[n]iconos mundiales![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_150_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43002 0 0]As胤 que sab胤an que pegaba[n]palizas a sus estudiantes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_150_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42702 0 0]Ya no puedo confiar[n]en este instituto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42302 0 0]El director se ha suicidado...[n]夷Qu姻 le est茨 pasando al instituto?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42305 0 0]夷Se habr茨 suicidado el director[n]para pagar por lo sucedido?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42451 0 0]夷Va a volver la polic胤a[n]para investigar el suicidio[n]del director?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 41906 0 0]夷Sabes qu姻? Una reportera[n]me ha preguntado[n]por los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 39104 0 0]夷Qu姻 clase de personas[n]son los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40206 0 0]斡Vaya donde vaya, todos hablan[n]de los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 38404 0 0]夷Sabes qui姻n es el presidente de[n]Okumura Foods? Por lo visto, su[n]hija estudia en nuestro instituto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40555 0 0]Me han dicho que el presidente[n]de Okumura Foods tiene una hija[n]que estudia en este instituto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 38054 0 0]夷Sabes qu姻? 斡La hija del presidente[n]de Okumura Foods estudia[n]en nuestro instituto![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42506 0 0]斡No te preocupes! Los Ladrones[n]Fantasma despertar茨n sus corazones.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40503 0 0]斡Todav胤a hay muchos malhechores![n]斡Que sigan d茨ndole duro![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 39656 0 0]斡Quiero que los Ladrones Fantasma[n]sigan deshaci姻ndose de los malos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43156 0 0]斡Eh, Ladrones Fantasma! 斡Hay que[n]acabar con los adultos corruptos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 38206 0 0]斡Adelante, Ladrones Fantasma![n]斡A por ellos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42403 0 0]斡Los Ladrones Fantasma acabar茨n[n]con todos esos adultos podridos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42555 0 0]La rueda de prensa[n]de Okumura fue terror胤fica...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42702 0 0]Lo que le ha pasado a Okumura[n]es culpa de los Ladrones Fantasma,[n]夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 41260 0 0]夷Ten胤an que hacerlo durante[n]la rueda de prensa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42207 0 0]Entonces... 斡夷han estado despertando[n]corazones para enga隠arnos?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40751 0 0]No ten胤an por qu姻 matarlo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43307 0 0]斡Nunca hubiera dicho que eran[n]una panda de asesinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 46307 0 0]夷Qu姻 hace la polic胤a?[n]斡Que los arresten de inmediato![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 44604 0 0]夷Crees que es cierto que[n]los Ladrones Fantasma est茨n[n]relacionados con el Shujin?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43359 0 0]夷Por qu姻 no hace nada la polic胤a?[n]Ni siquiera nos han dado[n]una explicaci吋n.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43703 0 0]斡夷Has visto la recompensa que hay[n]por los Ladrones Fantasma?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42701 0 0]斡La polic胤a est茨 tardando[n]demasiado en actuar![n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42154 0 0]Treinta millones de yenes[n]es una recompensa desorbitada...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42254 0 0]夷Has o胤do que los Ladrones Fantasma[n]podr胤an ser alumnos del Shujin?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40352 0 0]夷Ser茨 verdad que solo[n]estaban calentando?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 38657 0 0]Las personas que act雨an como[n]Ladrones Fantasma no tienen nada[n]que ver con el instituto, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40551 0 0]夷Has visto la rueda de prensa[n]de Shido? Menuda pu隠alada trapera...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 46152 0 0]No me creo ni una palabra[n]de las disculpas de Shido[n]en la conferencia de prensa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 41252 0 0]Mis padres tem胤an[n]que Shido estuviera enfermo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40160 0 0]Que alguien haga algo[n]y arregle esto de una vez.[n]No importa c吋mo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43155 0 0]Por mucho que estudie,[n]es una p姻rdida de tiempo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42760 0 0]Que alguien haga algo...[n]Da igual qui姻n sea.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SCH_main_All_029 [Mujer con c茨mara]]
[s][vp 9 2 65535 42508 0 0]En fin, tendr胤amos[n]que centrarnos en estudiar.[n][f 1 2 180][e]

[msg MSG_GRT_SCH_main_All_029_2 [Mujer con c茨mara]]
[s][vp 9 2 65535 42108 0 0]斡Estoy a tope![n][f 1 2 180][e]

[msg MSG_GRT_SCH_main_All_029_3 [Mujer con c茨mara]]
[s][vp 9 2 65535 42953 0 0]Yo tambi姻n puedo hacer algo.[n]斡Seguro que s胤![n][f 1 2 180][e]

[msg MSG_GRT_SCH_main_All_029_4 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43062 0 0]夷As胤 que ese es?[n]夷Ese es el t胤o con antecedentes?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42213 0 0]Es el t胤pico que parece normal,[n]pero que en realidad[n]est茨 ido de la olla.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42162 0 0]He o胤do que ha hecho todo tipo[n]de cosas chungas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43163 0 0]Me han dicho[n]que lleva armas escondidas...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42312 0 0]Parece que es de esos[n]que atacan a los dem茨s porque s胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42463 0 0]Voy a alejarme de 姻l,[n]que no quiero tener nada[n]que ver con ese pavo.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40505 0 0]La polic胤a ha estado merodeando[n]por el instituto.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43004 0 0]Creo que han estado[n]investigando a Kamoshida.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42913 0 0]No me extra隠a que haya[n]rumores circulando[n]con la polic胤a por aqu胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42505 0 0]Casi nunca estudio, as胤 que siempre[n]entro en p茨nico cuando se acercan[n]los ex茨menes parciales, 夷sabes?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42304 0 0]Ya tenemos encima los ex茨menes[n]parciales. 夷Qu姻 tal el estudio?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42355 0 0]夷Has empezado a estudiar[n]para los ex茨menes parciales?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 40500 0 0]Tengo que estudiar[n]a saco para los finales.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42510 0 0]Tengo que empezar[n]a estudiar para los finales...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42408 0 0]Si sigo estudiando a este ritmo,[n]me ir茨 bien en los finales.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_04_ [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 41701 0 0]斡夷Entre los diez mejores?![n]No me lo creo.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 44601 0 0]Seguro que ha copiado.[n]As胤 no vale...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42361 0 0]夷Alguien como 姻l lo ha hecho mejor[n]que yo? Deber胤a estudiar m茨s...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_301_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 38705 0 0]Da igual lo inteligente que sea,[n]sigue teniendo antecedentes.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42210 0 0]斡夷Es el mejor de la clase?![n]Venga ya...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 46301 0 0]Estar茨 orgulloso. Mira que hacer[n]trampas para ser el mejor...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42412 0 0]He perdido contra 姻l...[n]No me entra en la cabeza.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_302_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 39051 0 0]夷C吋mo ha podido un delincuente[n]sacar la mejor nota?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 39052 0 0]夷Est茨 entre los diez mejores?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 39752 0 0]Qu姻 pena que tenga[n]esos antecedentes...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42754 0 0]Yo avis姻 de que parec胤a[n]un estudiante muy serio,[n]y su nota lo demuestra.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_303_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43204 0 0]No parece que copie...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42704 0 0]He o胤do que el estudiante nuevo[n]est茨 en lo m茨s alto[n]de nuestra clase.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 39050 0 0]Ha sacado unas notas estupendas...[n]Lo aceptar胤an en el instituto[n]que 姻l quisiera.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42354 0 0]No pod胤a cre姻rmelo, pero...[n]Es 姻l de verdad, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_304_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43262 0 0]Aunque sea todo fachada,[n]es sorprendente que haya[n]conseguido la nota m茨s alta.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 38755 0 0]Espera, acabo de acordarme[n]despu姻s de ver su nombre.[n]夷No era el que ten胤a antecedentes?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42112 0 0]夷Otra vez 姻l?[n]Est茨 hasta en la sopa...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43304 0 0]夷Crees que de verdad[n]es para tanto?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_305_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42363 0 0]Sus notas son muy buenas,[n]pero 夷no era un delincuente?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42110 0 0]Es taaan bueno...[n]La verdad es que siento envidia.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42860 0 0]Siempre saca las notas m茨s altas.[n]Es muy raro...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 45054 0 0]Es de lo mejorcito de la clase,[n]夷verdad? A lo mejor deber胤a[n]pedirle que me eche una mano.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_306_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42163 0 0]Eh, mira. He o胤do que ese t胤o[n]es de los mejores de la clase.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All [Mujer con c茨mara]]
[s][vp 9 2 65535 38105 0 0]郁ltimamente hay un mont吋n[n]de incidentes extra隠os, 夷eh?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_2 [Mujer con c茨mara]]
[s][vp 9 2 65535 37552 0 0]Qu姻 aburrimiento... 夷No hay nada[n]interesante que hacer?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_3 [Mujer con c茨mara]]
[s][vp 9 2 65535 37652 0 0]Da miedo, 夷no? Presiento[n]que va a pasar algo de nuevo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_4 [Mujer con c茨mara]]
[s][vp 9 2 65535 39652 0 0]Ya hubo un accidente[n]de tren, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_5 [Mujer con c茨mara]]
[s]Quiero volverme rico r茨pido.[n]夷C吋mo podr胤a conseguirlo?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_6 [Mujer con c茨mara]]
[s]Nunca pasa nada bueno...[n]Alguien deber胤a hacer[n]algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_7 [Mujer con c茨mara]]
[s]Me gustar胤a hacer dinero f茨cil.[n]夷C吋mo podr胤a conseguirlo?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_8 [Mujer con c茨mara]]
[s]No va a cambiar nada,[n]as胤 que paso de tomarme[n]las cosas en serio.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_9 [Mujer con c茨mara]]
[s]Pf, qu姻 co隠azo tener que ir[n]a trabajar... A lo mejor digo[n]que me he puesto malo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_10 [Mujer con c茨mara]]
[s]Nunca pasa nada bueno...[n]Alguien deber胤a hacer[n]algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_11 [Mujer con c茨mara]]
[s]No va a cambiar nada,[n]as胤 que paso de tomarme[n]las cosas en serio.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_12 [Mujer con c茨mara]]
[s]Siempre hay malas noticias.[n]Alguien deber胤a dar un paso[n]al frente y cambiar las cosas.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_13 [Mujer con c茨mara]]
[s]Nunca pasa nada bueno...[n]Alguien deber胤a hacer[n]algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_14 [Mujer con c茨mara]]
[s]Esto es aburrid胤simo...[n]Quiero ir a alg雨n sitio divertido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_15 [Mujer con c茨mara]]
[s]No va a cambiar nada,[n]as胤 que paso de tomarme[n]las cosas en serio.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_16 [Mujer con c茨mara]]
[s]Me gustar胤a hacer dinero f茨cil.[n]夷C吋mo podr胤a conseguirlo?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_17 [Mujer con c茨mara]]
[s][vp 9 2 65535 38402 0 0]He o胤do que el accidente ocurri吋[n]por un episodio de descontrol.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_18 [Mujer con c茨mara]]
[s][vp 9 2 65535 37602 0 0]Pierden el conocimiento de pronto.[n]No hay manera de prevenirlo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_19 [Mujer con c茨mara]]
[s][vp 9 2 65535 39702 0 0]Ha habido muchos incidentes[n]extra隠os 雨ltimamente.[n]Volvamos r茨pido a casa...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_20 [Mujer con c茨mara]]
[s][vp 9 2 65535 40602 0 0]Me pregunto qu姻 suceder茨 ahora.[n]Todo esto me pone de los nervios...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_21 [Mujer con c茨mara]]
[s][vp 9 2 65535 37852 0 0]Las ventas tambi姻n han disminuido.[n]Argh, me duele la cabeza...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_22 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]Los pol胤ticos son in雨tiles.[n]夷Por qu姻 no toman cartas[n]en el asunto?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_23 [Mujer con c茨mara]]
[s][vp 9 2 65535 40402 0 0]Desde que vi el accidente,[n]tengo un miedo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_24 [Mujer con c茨mara]]
[s][vp 9 2 65535 40001 0 0]夷Nadie sabe qu姻 caus吋[n]ese accidente tan extra隠o?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_25 [Mujer con c茨mara]]
[s][vp 9 2 65535 38155 0 0]Estar involucrado en uno de esos[n]accidentes debe de ser horrible.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_26 [Mujer con c茨mara]]
[s][vp 9 2 65535 38205 0 0]La polic胤a es in雨til.[n]夷Est茨n investigando algo?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_27 [Mujer con c茨mara]]
[s][vp 9 2 65535 38252 0 0]Desde que vi el accidente,[n]tengo un miedo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_28 [Mujer con c茨mara]]
[s][vp 9 2 65535 38355 0 0]He o胤do que su personalidad[n]cambi吋 de repente[n]y que no recuerda lo que hizo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_29 [Mujer con c茨mara]]
[s][vp 9 2 65535 37801 0 0]Este mundo es horroroso...[n]夷De qui姻n ser茨 la culpa?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_30 [Mujer con c茨mara]]
[s][vp 9 2 65535 40302 0 0]Nunca pasa nada bueno...[n]Alguien deber胤a hacer[n]algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_31 [Mujer con c茨mara]]
[s][vp 9 2 65535 40952 0 0]Todo es aburrid胤simo.[n]夷Nunca pasa nada bueno?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_32 [Mujer con c茨mara]]
[s][vp 9 2 65535 41452 0 0]Siempre hay malas noticias.[n]Alguien deber胤a dar un paso[n]al frente y cambiar las cosas.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_33 [Mujer con c茨mara]]
[s][vp 9 2 65535 39804 0 0]夷En qu姻 instituto ha pasado?[n]夷En el Shujin?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_34 [Mujer con c茨mara]]
[s][vp 9 2 65535 38152 0 0]Qu姻 rabia que el medallista de oro[n]fuera un pervertido de tomo y lomo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_35 [Mujer con c茨mara]]
[s][vp 9 2 65535 38953 0 0]夷Han detenido a un profesor salido?[n]斡Ja! 斡Menuda risa![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_36 [Mujer con c茨mara]]
[s][vp 9 2 65535 38904 0 0]Se aprovechaba[n]de las chicas del equipo.[n]Qu姻 asco de t胤o...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_37 [Mujer con c茨mara]]
[s][vp 9 2 65535 38452 0 0]夷Lo ha admitido? Si iba[n]a confesar de todos modos,[n]夷por qu姻 lo ha hecho?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_38 [Mujer con c茨mara]]
[s][vp 9 2 65535 39053 0 0]Qu姻 rabia que el medallista de oro[n]fuera un pervertido de tomo y lomo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_39 [Mujer con c茨mara]]
[s][vp 9 2 65535 38903 0 0]夷Han detenido a un profesor salido?[n]斡Ja! 斡Menuda risa![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_40 [Mujer con c茨mara]]
[s][vp 9 2 65535 39651 0 0]No me puedo creer que acosara[n]sexualmente a esas chicas.[n]Menuda forma de abusar de su poder...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_41 [Mujer con c茨mara]]
[s][vp 9 2 65535 38152 0 0]夷Lo ha admitido? Si iba[n]a confesar de todos modos,[n]夷por qu姻 lo ha hecho?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_42 [Mujer con c茨mara]]
[s][vp 9 2 65535 38205 0 0]Medallista de oro o no,[n]hasta aqu胤 ha llegado.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_43 [Mujer con c茨mara]]
[s][vp 9 2 65535 38251 0 0]Menudo cerdo. Manose吋 a las pobres[n]chicas como quiso.[n]Ser茨 asqueroso...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_44 [Mujer con c茨mara]]
[s][vp 9 2 65535 38351 0 0]Qu姻 rabia que el medallista de oro[n]fuera un pervertido de tomo y lomo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_45 [Mujer con c茨mara]]
[s][vp 9 2 65535 38451 0 0]Medallista de oro o no,[n]hasta aqu胤 ha llegado.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_46 [Mujer con c茨mara]]
[s][vp 9 2 65535 38501 0 0]Qu姻 rabia que el medallista de oro[n]fuera un pervertido de tomo y lomo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_47 [Mujer con c茨mara]]
[s][vp 9 2 65535 38553 0 0]夷Han detenido a un profesor salido?[n]斡Ja! 斡Menuda risa![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_48 [Mujer con c茨mara]]
[s][vp 9 2 65535 38651 0 0]No me puedo creer que acosara[n]sexualmente a esas chicas.[n]Mira que abusar as胤 de su poder...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_49 [Mujer con c茨mara]]
[s][vp 9 2 65535 37504 0 0]No me interesa mucho el arte,[n]pero creo que es famoso.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_50 [Mujer con c茨mara]]
[s][vp 9 2 65535 37554 0 0]夷Has o胤do hablar de Madarame?[n]Por lo visto, es un artista famoso.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_51 [Mujer con c茨mara]]
[s][vp 9 2 65535 37652 0 0]Seguro que sus obras[n]se venden por una pasta...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_52 [Mujer con c茨mara]]
[s][vp 9 2 65535 37700 0 0]Es muy popular. Quiz茨 yo tambi姻n[n]deber胤a hacerme artista.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_53 [Mujer con c茨mara]]
[s][vp 9 2 65535 37800 0 0]Es muy popular. Quiz茨 yo tambi姻n[n]deber胤a convertirme en artista.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_54 [Mujer con c茨mara]]
[s][vp 9 2 65535 37904 0 0]S胤, he escuchado en las noticias[n]que un artista famoso[n]ha organizado una exposici吋n...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_55 [Mujer con c茨mara]]
[s][vp 9 2 65535 37954 0 0]斡Dicen que es conocido[n]en todo el mundo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_56 [Mujer con c茨mara]]
[s][vp 9 2 65535 38054 0 0]Fijo que ese artista[n]se est茨 forrando.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_57 [Mujer con c茨mara]]
[s][vp 9 2 65535 38150 0 0]夷Has o胤do hablar de Madarame?[n]Por lo visto, es un artista famoso.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_58 [Mujer con c茨mara]]
[s][vp 9 2 65535 38204 0 0]Seguro que sus cuadros[n]se venden por una pasta...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_59 [Mujer con c茨mara]]
[s][vp 9 2 65535 38254 0 0]S胤, he escuchado en las noticias[n]que un artista famoso[n]ha organizado una exposici吋n...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_60 [Mujer con c茨mara]]
[s][vp 9 2 65535 38350 0 0]Lo he visto por la tele.[n]Su arte es bastante bueno.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_61 [Mujer con c茨mara]]
[s][vp 9 2 65535 38454 0 0]夷Has o胤do hablar de Madarame?[n]Por lo visto, es un artista famoso.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_62 [Mujer con c茨mara]]
[s][vp 9 2 65535 38504 0 0]Seguro que sus cuadros[n]se venden por una pasta...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_63 [Mujer con c茨mara]]
[s][vp 9 2 65535 38554 0 0]S胤, he escuchado en las noticias[n]que un artista famoso[n]ha organizado una exposici吋n...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_64 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]Lo he visto por la tele.[n]Su arte es bastante bueno.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_65 [Mujer con c茨mara]]
[s][vp 9 2 65535 37502 0 0]He recibido un correo extra隠o.[n]夷Qu姻 es esto?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_66 [Mujer con c茨mara]]
[s][vp 9 2 65535 37552 0 0]郁ltimamente he visto gente[n]sospechosa rondando por ah胤...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_67 [Mujer con c茨mara]]
[s][vp 9 2 65535 37655 0 0]Tengo miedo de que la mafia[n]me chantajee...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_68 [Mujer con c茨mara]]
[s][vp 9 2 65535 37702 0 0]He le胤do en internet[n]que Shibuya se ha vuelto peligrosa.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_69 [Mujer con c茨mara]]
[s][vp 9 2 65535 37805 0 0]郁ltimamente no he escuchado[n]nada bueno de Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_70 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]Hab胤a yakuza rondando[n]a plena luz del d胤a...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_71 [Mujer con c茨mara]]
[s][vp 9 2 65535 37952 0 0]夷No es horrible que tengan[n]a estudiantes en el punto de mira?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_72 [Mujer con c茨mara]]
[s][vp 9 2 65535 38055 0 0]He o胤do que hay un grupo[n]de estafadores que se dedicaa timar por Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_73 [Mujer con c茨mara]]
[s][vp 9 2 65535 38152 0 0]As胤 que un fraude por internet.[n]Habr茨 que andarse con ojo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_74 [Mujer con c茨mara]]
[s][vp 9 2 65535 38201 0 0]夷D吋nde est茨 la polic胤a?[n]Tiene que hacer algo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_75 [Mujer con c茨mara]]
[s][vp 9 2 65535 38255 0 0]Tendr姻 que ir con cuidado[n]cuando vaya a Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_76 [Mujer con c茨mara]]
[s][vp 9 2 65535 38352 0 0]He escuchado que la delincuencia[n]ha aumentado por aqu胤.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_77 [Mujer con c茨mara]]
[s][vp 9 2 65535 38455 0 0]Pues me ir姻 echando leches[n]si veo a alguien que d姻 mal rollo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_78 [Mujer con c茨mara]]
[s][vp 9 2 65535 38502 0 0]A lo mejor dejo de ir a Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_79 [Mujer con c茨mara]]
[s][vp 9 2 65535 38555 0 0]Despu姻s de o胤r lo peligroso[n]que se ha vuelto, me da miedo[n]ir por mi cuenta.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_80 [Mujer con c茨mara]]
[s][vp 9 2 65535 38652 0 0]Tengo un amigo[n]al que estafaron...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_81 [Mujer con c茨mara]]
[s][vp 9 2 65535 37502 0 0]Parece que no volver茨 a haber[n]accidentes tan extra隠os.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_82 [Mujer con c茨mara]]
[s][vp 9 2 65535 37552 0 0]夷Cu茨ndo fue la 雨ltima[n]vez que hubo un accidente?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_83 [Mujer con c茨mara]]
[s][vp 9 2 65535 37655 0 0]夷Ser茨 este el fin de esos extra隠os[n]accidentes?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_84 [Mujer con c茨mara]]
[s][vp 9 2 65535 37702 0 0]夷Alguien conoce la causa[n]de todos los accidentes?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_85 [Mujer con c茨mara]]
[s][vp 9 2 65535 37805 0 0]A雨n es peligroso salir.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_86 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]郁ltimamente no se ha dicho[n]gran cosa sobre los accidentes.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_87 [Mujer con c茨mara]]
[s][vp 9 2 65535 37952 0 0]Antes, los accidentes[n]suced胤an continuamente.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_88 [Mujer con c茨mara]]
[s][vp 9 2 65535 38055 0 0]Qu姻 raro que haya[n]dejado de haber accidentes[n]tan de repente.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_89 [Mujer con c茨mara]]
[s][vp 9 2 65535 38152 0 0]Seguro que pronto[n]habr茨 un gran accidente.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_90 [Mujer con c茨mara]]
[s][vp 9 2 65535 38201 0 0]Es triste,[n]pero ya se me hab胤an[n]olvidado los accidentes.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_91 [Mujer con c茨mara]]
[s][vp 9 2 65535 38255 0 0]郁ltimamente no he o胤do nada[n]sobre los episodios de descontrol.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_92 [Mujer con c茨mara]]
[s][vp 9 2 65535 38352 0 0]Las cosas se han calmado,[n]pero eso no significa nada.[n]Pronto habr茨 otro accidente.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_93 [Mujer con c茨mara]]
[s][vp 9 2 65535 38455 0 0]No ha cambiado nada.[n]Siguen ocurriendo[n]cosas raras en el mundo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_94 [Mujer con c茨mara]]
[s][vp 9 2 65535 38502 0 0]Siempre ha habido accidentes.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_95 [Mujer con c茨mara]]
[s][vp 9 2 65535 38555 0 0]No creo que pueda relajarme[n]a雨n. Puede haber otro accidente[n]en cualquier momento.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_96 [Mujer con c茨mara]]
[s][vp 9 2 65535 38652 0 0]Y le estaban dando[n]much胤sima importancia[n]a no conocer la causa.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_97 [Mujer con c茨mara]]
[s][vp 9 2 65535 37502 0 0]He o胤do que no cab胤a un alfiler[n]en la exposici吋n de Madarame.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_98 [Mujer con c茨mara]]
[s][vp 9 2 65535 37552 0 0]夷Cu茨nto va a durar[n]la exposici吋n de Madarame?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_99 [Mujer con c茨mara]]
[s][vp 9 2 65535 37655 0 0]Mi amiga fue a verla.[n]Dice que est茨 bastante bien.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_100 [Mujer con c茨mara]]
[s][vp 9 2 65535 37702 0 0]夷Crees que si voy a la exposici吋n[n]conocer姻 al mism胤simo Madarame?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_101 [Mujer con c茨mara]]
[s][vp 9 2 65535 37805 0 0]Crear arte parece divertido,[n]pero mejor me centro[n]en encauzar mi vida...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_102 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]A lo mejor hago que mi hijo[n]tambi姻n sea artista.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_103 [Mujer con c茨mara]]
[s][vp 9 2 65535 37952 0 0]Lo he visto por la tele.[n]Es bastante bueno, 夷eh?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_104 [Mujer con c茨mara]]
[s][vp 9 2 65535 38055 0 0]Qu姻 guapo es Madarame.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_105 [Mujer con c茨mara]]
[s][vp 9 2 65535 38152 0 0]El 或Sayuri位 no estaba.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_106 [Mujer con c茨mara]]
[s][vp 9 2 65535 38201 0 0]La exposici吋n de Madarame[n]est茨 recibiendo cr胤ticas[n]muy favorables. 夷Quieres ir?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_107 [Mujer con c茨mara]]
[s][vp 9 2 65535 38255 0 0]斡La exposici吋n de Madarame[n]ha sido genial! 斡Incre胤ble![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_108 [Mujer con c茨mara]]
[s][vp 9 2 65535 38352 0 0]Deber胤a ir temprano.[n]Dicen que est茨 abarrotada.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_109 [Mujer con c茨mara]]
[s][vp 9 2 65535 38455 0 0]夷A qui姻n le importa Madarame?[n]斡Yo tambi姻n s姻 pintar![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_110 [Mujer con c茨mara]]
[s][vp 9 2 65535 38502 0 0]No es momento de perder[n]el tiempo creando arte.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_111 [Mujer con c茨mara]]
[s][vp 9 2 65535 38555 0 0]斡Quiero ir a ver el espect茨culo[n]de arte de Madarame![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_112 [Mujer con c茨mara]]
[s][vp 9 2 65535 38652 0 0]Es un buen modelo[n]para una vida tan sencilla.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_113 [Mujer con c茨mara]]
[s][vp 9 2 65535 37501 0 0]Estaba sacando pasta del arte[n]que robaba de artistas de verdad.[n]Menudo desgraciado.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_114 [Mujer con c茨mara]]
[s][vp 9 2 65535 37551 0 0]Explotaba a sus aprendices[n]e incluso les robaba sus obras.[n]夷Te lo puedes creer?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_115 [Mujer con c茨mara]]
[s][vp 9 2 65535 37653 0 0]夷Hab姻is visto la rueda de prensa?[n]斡No pod胤a dejar de re胤rme![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_116 [Mujer con c茨mara]]
[s][vp 9 2 65535 37701 0 0]Parec胤a una buena persona y pensaba[n]que era un caballero de verdad.[n]Me enga隠吋 de lo lindo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_117 [Mujer con c茨mara]]
[s][vp 9 2 65535 37801 0 0]夷Es cierto que hubo un aviso?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_118 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]Es penoso, un hombre hecho[n]y derecho llorando como un cr胤o.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_119 [Mujer con c茨mara]]
[s][vp 9 2 65535 37951 0 0]Hay rumores de que alguien anunci吋[n]de antemano que esto iba a pasar.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_120 [Mujer con c茨mara]]
[s][vp 9 2 65535 38055 0 0]Los medios me enga隠aron[n]por completo. Hablaban de 姻l[n]como si fuera un supergenio.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_121 [Mujer con c茨mara]]
[s][vp 9 2 65535 38151 0 0]La disculpa que dio[n]en la rueda de prensa[n]fue de pel胤cula, 夷eh?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_122 [Mujer con c茨mara]]
[s][vp 9 2 65535 38201 0 0]夷Es cierto que alguien avis吋[n]de lo que iba a pasar?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_123 [Mujer con c茨mara]]
[s][vp 9 2 65535 38252 0 0]Lloraba a moco tendido.[n]Daba un poco de asco.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_124 [Mujer con c茨mara]]
[s][vp 9 2 65535 38351 0 0]夷Por qu姻 lo confes吋 de pronto?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_125 [Mujer con c茨mara]]
[s][vp 9 2 65535 38460 0 0]En la tele dijeron que alguien[n]anunci吋 lo que suceder胤a[n]antes de que pasara.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_126 [Mujer con c茨mara]]
[s][vp 9 2 65535 38502 0 0]夷Ladrones Fantasma?[n]夷De qu姻 est茨s hablando?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_127 [Mujer con c茨mara]]
[s][vp 9 2 65535 38551 0 0]夷De verdad se piensa que la gente[n]lo va a perdonar si se derrumba[n]y se pone a llorar?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_128 [Mujer con c茨mara]]
[s][vp 9 2 65535 38655 0 0]La gente que pag吋 todo ese dinero[n]para comprar su arte debe[n]de sentirse muy est雨pida.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_129 [Mujer con c茨mara]]
[s][vp 9 2 65535 37502 0 0]郁ltimamente no he escuchado[n]nada bueno de Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_130 [Mujer con c茨mara]]
[s][vp 9 2 65535 37552 0 0]Me da la impresi吋n de que cada vez[n]hay m茨s gente con mala pinta.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_131 [Mujer con c茨mara]]
[s][vp 9 2 65535 37652 0 0]He escuchado un rumor[n]de que te convocan en Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_132 [Mujer con c茨mara]]
[s][vp 9 2 65535 37702 0 0]夷Soy yo, o cada vez hay m茨s gente[n]con mala pinta por aqu胤?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_133 [Mujer con c茨mara]]
[s][vp 9 2 65535 37805 0 0]He o胤do que la gente[n]est茨 recibiendo correos[n]que parecen ciberestafas.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_134 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]Me da la impresi吋n de que cada vez[n]hay m茨s gente con mala pinta.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_135 [Mujer con c茨mara]]
[s][vp 9 2 65535 37952 0 0]夷Es verdad que van[n]a por los estudiantes?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_136 [Mujer con c茨mara]]
[s][vp 9 2 65535 38055 0 0]夷Son ciertos los rumores[n]de extorsi吋n y fraude?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_137 [Mujer con c茨mara]]
[s][vp 9 2 65535 38155 0 0]郁ltimamente no he escuchado[n]nada bueno de Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_138 [Mujer con c茨mara]]
[s][vp 9 2 65535 38202 0 0]夷D吋nde est茨 la polic胤a?[n]Tiene que hacer algo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_139 [Mujer con c茨mara]]
[s][vp 9 2 65535 38255 0 0]Todo el mundo tiene[n]demasiado miedo de pisar Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_140 [Mujer con c茨mara]]
[s][vp 9 2 65535 38351 0 0]夷Fraudes por internet? 斡Qu姻 horror![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_141 [Mujer con c茨mara]]
[s][vp 9 2 65535 38452 0 0]郁ltimamente no he escuchado[n]nada bueno de Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_142 [Mujer con c茨mara]]
[s][vp 9 2 65535 38505 0 0]夷Qu姻 est茨 pasando en Shibuya?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_143 [Mujer con c茨mara]]
[s][vp 9 2 65535 38552 0 0]Todo el mundo tiene[n]demasiado miedo de pisar Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_144 [Mujer con c茨mara]]
[s][vp 9 2 65535 38655 0 0]夷Fraudes por internet? 斡Qu姻 horror![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_145 [Mujer con c茨mara]]
[s][vp 9 2 65535 37505 0 0]夷Eso de los avisos es cierto?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_146 [Mujer con c茨mara]]
[s][vp 9 2 65535 37554 0 0]He o胤do que estaban[n]por toda Shibuya...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_147 [Mujer con c茨mara]]
[s][vp 9 2 65535 37655 0 0]Es una broma, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_148 [Mujer con c茨mara]]
[s][vp 9 2 65535 37705 0 0]Ser胤a muy interesante[n]que los avisos fueran reales.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_149 [Mujer con c茨mara]]
[s][vp 9 2 65535 37805 0 0]Lo de los avisos[n]es una patra隠a de internet, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_150 [Mujer con c茨mara]]
[s][vp 9 2 65535 37905 0 0]Ni de co隠a los Ladrones Fantasma[n]existen de verdad.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_151 [Mujer con c茨mara]]
[s][vp 9 2 65535 37955 0 0]He o胤do que los han colgado[n]por todas partes.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_152 [Mujer con c茨mara]]
[s][vp 9 2 65535 38055 0 0]As胤 que los Ladrones Fantasma, 夷eh?[n]夷Crees que existen de verdad?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_153 [Mujer con c茨mara]]
[s][vp 9 2 65535 38154 0 0]He o胤do que hay carteles[n]por toda la ciudad.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_154 [Mujer con c茨mara]]
[s][vp 9 2 65535 38205 0 0]夷Un aviso de los Ladrones Fantasma?[n]夷Qu姻 me est茨s contando?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_155 [Mujer con c茨mara]]
[s][vp 9 2 65535 38254 0 0]Ser胤a muy interesante[n]que los avisos fueran reales.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_156 [Mujer con c茨mara]]
[s][vp 9 2 65535 38355 0 0]Espera, 夷qui姻n es Kaneshiro?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_157 [Mujer con c茨mara]]
[s][vp 9 2 65535 38455 0 0]夷Crees que los Ladrones Fantasma[n]existen de verdad?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_158 [Mujer con c茨mara]]
[s][vp 9 2 65535 38504 0 0]夷Cu茨ndo va a hacer[n]la polic胤a su trabajo?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_159 [Mujer con c茨mara]]
[s][vp 9 2 65535 38554 0 0]Ser胤a genial[n]que fueran de verdad.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_160 [Mujer con c茨mara]]
[s][vp 9 2 65535 38655 0 0]夷Crees que los Ladrones Fantasma[n]existen de verdad?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_161 [Mujer con c茨mara]]
[s][vp 9 2 65535 37503 0 0]斡He o胤do que el principal[n]sospechoso est茨 detenido![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_162 [Mujer con c茨mara]]
[s][vp 9 2 65535 37553 0 0]斡Vamos a Shibuya,[n]que ha vuelto a la normalidad![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_163 [Mujer con c茨mara]]
[s][vp 9 2 65535 37650 0 0]斡Por fin podemos relajarnos[n]cuando salgamos por ah胤![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_164 [Mujer con c茨mara]]
[s][vp 9 2 65535 37700 0 0]Es un alivio que Shibuya[n]est姻 tranquila de nuevo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_165 [Mujer con c茨mara]]
[s][vp 9 2 65535 37800 0 0]斡He o胤do que por fin[n]detuvieron al l胤der[n]de esa organizaci吋n criminal![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_166 [Mujer con c茨mara]]
[s][vp 9 2 65535 38400 0 0]斡S胤, he escuchado en las noticias[n]que lo detuvieron![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_167 [Mujer con c茨mara]]
[s][vp 9 2 65535 37950 0 0]Es un alivio que Shibuya[n]est姻 tranquila de nuevo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_168 [Mujer con c茨mara]]
[s][vp 9 2 65535 38053 0 0]Ahora puedo ir por la calle[n]de nuevo sin sentir miedo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_169 [Mujer con c茨mara]]
[s][vp 9 2 65535 38153 0 0]斡He o胤do que por fin[n]detuvieron al l胤der[n]de esa organizaci吋n criminal![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_170 [Mujer con c茨mara]]
[s][vp 9 2 65535 38203 0 0]Parece que todas las estafas[n]se van a acabar por fin.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_171 [Mujer con c茨mara]]
[s][vp 9 2 65535 38250 0 0]斡Al fin puedo salir[n]por Shibuya otra vez![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_172 [Mujer con c茨mara]]
[s][vp 9 2 65535 38353 0 0]斡He o胤do que han detenido[n]a los estafadores![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_173 [Mujer con c茨mara]]
[s][vp 9 2 65535 38450 0 0]斡Qu姻 bien que los hayan detenido![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_174 [Mujer con c茨mara]]
[s][vp 9 2 65535 38500 0 0]Qu姻 bien que hayan detenido[n]a toda esa gentuza peligrosa.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_175 [Mujer con c茨mara]]
[s][vp 9 2 65535 38553 0 0]斡Al fin puedo salir[n]por Shibuya otra vez![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_176 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]斡He o胤do que han detenido[n]a los estafadores![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_177 [Mujer con c茨mara]]
[s][vp 9 2 65535 37506 0 0]斡El aviso era real![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_178 [Mujer con c茨mara]]
[s][vp 9 2 65535 37556 0 0]Ser胤a la leche si de verdad[n]fueran los Ladrones Fantasma[n]los que lo han hecho.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_179 [Mujer con c茨mara]]
[s][vp 9 2 65535 37656 0 0]Supongo que los rumores sobre los[n]Ladrones Fantasma eran ciertos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_180 [Mujer con c茨mara]]
[s][vp 9 2 65535 37704 0 0]夷Has visto las noticias?[n]斡Parece que han sido[n]los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_181 [Mujer con c茨mara]]
[s][vp 9 2 65535 37850 0 0]斡Supongo que aquel aviso de los[n]Ladrones Fantasma no era una broma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_182 [Mujer con c茨mara]]
[s][vp 9 2 65535 37904 0 0]He o胤do que ha sido cosa[n]de un grupo,[n]unos Ladrones Fantasma o no s姻 qu姻.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_183 [Mujer con c茨mara]]
[s][vp 9 2 65535 37954 0 0]斡Al final el aviso[n]ha resultado ser real![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_184 [Mujer con c茨mara]]
[s][vp 9 2 65535 38050 0 0]En las noticias han dicho que los[n]Ladrones Fantasma podr胤an[n]estar involucrados.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_185 [Mujer con c茨mara]]
[s][vp 9 2 65535 38150 0 0]Ser胤a la leche si de verdad[n]fueran los Ladrones Fantasma[n]los que lo han hecho.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_186 [Mujer con c茨mara]]
[s][vp 9 2 65535 38204 0 0]He o胤do que ha sido cosa[n]de un grupo,[n]unos Ladrones Fantasma o no s姻 qu姻.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_187 [Mujer con c茨mara]]
[s][vp 9 2 65535 38254 0 0]斡Ha sucedido exactamente como se[n]indicaba en el aviso[n]de los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_188 [Mujer con c茨mara]]
[s][vp 9 2 65535 38354 0 0]En las noticias han dicho que los[n]Ladrones Fantasma podr胤an[n]estar involucrados.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_189 [Mujer con c茨mara]]
[s][vp 9 2 65535 38454 0 0]Ser胤a la leche si de verdad[n]fueran los Ladrones Fantasma[n]los que lo han hecho.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_190 [Mujer con c茨mara]]
[s][vp 9 2 65535 38504 0 0]He o胤do que ha sido cosa[n]de un grupo,[n]los Ladrones Fantasma o algo as胤.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_191 [Mujer con c茨mara]]
[s][vp 9 2 65535 38550 0 0]Supongo que los rumores sobre los[n]Ladrones Fantasma eran ciertos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_192 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]斡夷Es cierto que los Ladrones[n]Fantasma han resuelto[n]ese incidente?![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_193 [Mujer con c茨mara]]
[s][vp 9 2 65535 37505 0 0]夷Has visto las noticias?[n]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_194 [Mujer con c茨mara]]
[s][vp 9 2 65535 37552 0 0]夷En qu姻 estar胤an pensando esos[n]hackers para enemistarse con los[n]Ladrones Fantasma as胤 de repente?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_195 [Mujer con c茨mara]]
[s][vp 9 2 65535 37651 0 0]夷A qu姻 se refiere la gente cuando[n]dice que los Ladrones Fantasma[n]imparten una justicia falsa?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_196 [Mujer con c茨mara]]
[s][vp 9 2 65535 37704 0 0]Se han cebado mucho con[n]los Ladrones Fantasma.[n]Me pregunto qu姻 har茨n ahora...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_197 [Mujer con c茨mara]]
[s][vp 9 2 65535 37804 0 0]夷Has visto el comunicado de Medjed?[n]夷C吋mo reaccionar茨n[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_198 [Mujer con c茨mara]]
[s][vp 9 2 65535 37905 0 0]夷A qu姻 se refiere la gente cuando[n]dice que los Ladrones Fantasma[n]imparten una justicia falsa?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_199 [Mujer con c茨mara]]
[s][vp 9 2 65535 37954 0 0]Parece que Medjed ha estado[n]siguiendo de cerca a[n]los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_200 [Mujer con c茨mara]]
[s][vp 9 2 65535 38054 0 0]No dicen m茨s que mentiras.[n]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma al respecto...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_201 [Mujer con c茨mara]]
[s][vp 9 2 65535 38151 0 0]夷Qu姻 quiere Medjed?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_202 [Mujer con c茨mara]]
[s][vp 9 2 65535 38205 0 0]夷A qu姻 narices se refieren cuando[n]dicen que los Ladrones Fantasma[n]imparten una justicia falsa?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_203 [Mujer con c茨mara]]
[s][vp 9 2 65535 38254 0 0]Medjed puede decir todo[n]lo que quiera, pero[n]夷qu姻 est茨n haciendo realmente?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_204 [Mujer con c茨mara]]
[s][vp 9 2 65535 38355 0 0]No dicen m茨s que mentiras.[n]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma al respecto...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_205 [Mujer con c茨mara]]
[s][vp 9 2 65535 38455 0 0]夷Medjed? Uf, 斡qu姻 rollazo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_206 [Mujer con c茨mara]]
[s][vp 9 2 65535 38505 0 0]夷A qu姻 narices se refieren cuando[n]dicen que los Ladrones Fantasma[n]imparten una justicia falsa?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_207 [Mujer con c茨mara]]
[s][vp 9 2 65535 38554 0 0]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma[n]con respecto a Medjed...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_208 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]No dicen m茨s que mentiras.[n]Me pregunto qu姻 har茨n[n]los Ladrones Fantasma al respecto...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_209 [Mujer con c茨mara]]
[s][vp 9 2 65535 37504 0 0]夷Qu姻 pueden hacer los Ladrones[n]Fantasma contra esos hackers?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_210 [Mujer con c茨mara]]
[s][vp 9 2 65535 37551 0 0]Vamos, Ladrones Fantasma,[n]pronunciaos ya.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_211 [Mujer con c茨mara]]
[s][vp 9 2 65535 37652 0 0]Los Ladrones Fantasma[n]guardan silencio.[n]夷Qu姻 va a pasar?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_212 [Mujer con c茨mara]]
[s][vp 9 2 65535 37704 0 0]Tienen a Jap吋n en el punto de mira.[n]Espero que hagan algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_213 [Mujer con c茨mara]]
[s][vp 9 2 65535 37803 0 0]夷Qu姻 pueden hacer los Ladrones[n]Fantasma contra esos hackers?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_214 [Mujer con c茨mara]]
[s][vp 9 2 65535 37903 0 0]斡Nuestra econom胤a no podr胤a[n]soportar 或da隠os devastadores位![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_215 [Mujer con c茨mara]]
[s][vp 9 2 65535 37953 0 0]Tienen a Jap吋n en el punto de mira.[n]Espero que hagan algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_216 [Mujer con c茨mara]]
[s][vp 9 2 65535 38050 0 0]Si los Ladrones Fantasma revelan[n]su identidad, 夷nos dejar茨n en paz?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_217 [Mujer con c茨mara]]
[s][vp 9 2 65535 38155 0 0]Vamos, Ladrones Fantasma,[n]pronunciaos ya.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_218 [Mujer con c茨mara]]
[s][vp 9 2 65535 38205 0 0]夷Qu姻 est茨n haciendo[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_219 [Mujer con c茨mara]]
[s][vp 9 2 65535 38254 0 0]Los Ladrones Fantasma[n]guardan silencio.[n]夷Qu姻 va a pasar?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_220 [Mujer con c茨mara]]
[s][vp 9 2 65535 38354 0 0]Si los Ladrones Fantasma revelan[n]su identidad, 夷nos dejar茨n en paz?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_221 [Mujer con c茨mara]]
[s][vp 9 2 65535 38452 0 0]Vamos, Ladrones Fantasma,[n]pronunciaos ya.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_222 [Mujer con c茨mara]]
[s][vp 9 2 65535 38501 0 0]夷Qu姻 est茨n haciendo[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_223 [Mujer con c茨mara]]
[s][vp 9 2 65535 38554 0 0]Los Ladrones Fantasma[n]guardan silencio.[n]夷Qu姻 va a pasar?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_224 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]Si los Ladrones Fantasma[n]revelan su verdadera identidad,[n]no nos har茨n nada, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_225 [Mujer con c茨mara]]
[s][vp 9 2 65535 37500 0 0]斡He o胤do que han pirateado[n]la p茨gina web de Medjed![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_226 [Mujer con c茨mara]]
[s][vp 9 2 65535 37550 0 0]斡Es incre胤ble que hayan derrotado[n]a Medjed![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_227 [Mujer con c茨mara]]
[s][vp 9 2 65535 37656 0 0]斡He o胤do que los Ladrones Fantasma[n]han acabado con Medjed![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_228 [Mujer con c茨mara]]
[s][vp 9 2 65535 37706 0 0]夷Los Ladrones Fantasma han acabado[n]con ellos? 斡Alucinante![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_229 [Mujer con c茨mara]]
[s][vp 9 2 65535 37800 0 0]斡He o胤do que han pirateado[n]la p茨gina web de Medjed![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_230 [Mujer con c茨mara]]
[s][vp 9 2 65535 37900 0 0]夷Eso quiere decir que los Ladrones[n]Fantasma nos han salvado?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_231 [Mujer con c茨mara]]
[s][vp 9 2 65535 37956 0 0]Los Ladrones Fantasma[n]se han encargado de ellos, 夷verdad?[n]斡Hay que darles las gracias![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_232 [Mujer con c茨mara]]
[s][vp 9 2 65535 38054 0 0]斡No me puedo creer[n]que hayan derrotado a Medjed![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_233 [Mujer con c茨mara]]
[s][vp 9 2 65535 38150 0 0]斡Es incre胤ble que hayan derrotado[n]a Medjed![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_234 [Mujer con c茨mara]]
[s][vp 9 2 65535 38204 0 0]Eso quiere decir que los Ladrones[n]Fantasma nos han salvado, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_235 [Mujer con c茨mara]]
[s][vp 9 2 65535 38253 0 0]斡He o胤do que han puesto el logo[n]de los Ladrones Fantasma[n]en la web de los hackers![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_236 [Mujer con c茨mara]]
[s][vp 9 2 65535 38353 0 0]斡No puedo creer que hayan sido[n]capaces de acabar con un grupo[n]internacional de hackers![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_237 [Mujer con c茨mara]]
[s][vp 9 2 65535 38450 0 0]斡Es incre胤ble que hayan derrotado[n]a Medjed![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_238 [Mujer con c茨mara]]
[s][vp 9 2 65535 38504 0 0]夷Qui姻n necesita a la polic胤a cuando[n]tenemos a los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_239 [Mujer con c茨mara]]
[s][vp 9 2 65535 38550 0 0]斡He o胤do que han cerrado[n]la p茨gina web de Medjed![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_240 [Mujer con c茨mara]]
[s][vp 9 2 65535 38650 0 0]斡No puedo creer que hayan sido[n]capaces de acabar con un grupo[n]internacional de hackers![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_241 [Mujer con c茨mara]]
[s][vp 9 2 65535 37506 0 0]斡He o胤do que han protegido a Jap吋n[n]frente a los hackers![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_242 [Mujer con c茨mara]]
[s][vp 9 2 65535 37556 0 0]斡Los Ladrones Fantasma ten胤an raz吋n[n]desde el principio![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_243 [Mujer con c茨mara]]
[s][vp 9 2 65535 37656 0 0]斡Me alegro de haber confiado[n]en los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_244 [Mujer con c茨mara]]
[s][vp 9 2 65535 37706 0 0]夷Han acabado con Medjed?[n]斡Son geniales![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_245 [Mujer con c茨mara]]
[s][vp 9 2 65535 37806 0 0]斡Son como h姻roes de carne y hueso![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_246 [Mujer con c茨mara]]
[s][vp 9 2 65535 37906 0 0]斡Los Ladrones Fantasma[n]han salvado Jap吋n![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_247 [Mujer con c茨mara]]
[s][vp 9 2 65535 37956 0 0]夷Han derrotado a Medjed?[n]Alucinante, 斡no me lo puedo creer![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_248 [Mujer con c茨mara]]
[s][vp 9 2 65535 38056 0 0]斡Los Ladrones Fantasma[n]son la justicia![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_249 [Mujer con c茨mara]]
[s][vp 9 2 65535 38156 0 0]斡Los Ladrones Fantasma[n]nos han salvado![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_250 [Mujer con c茨mara]]
[s][vp 9 2 65535 38206 0 0]斡Los Ladrones Fantasma ten胤an raz吋n[n]desde el principio![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_251 [Mujer con c茨mara]]
[s][vp 9 2 65535 38256 0 0]斡Los Ladrones Fantasma han[n]acabado con Medjed! 斡Bien hecho![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_252 [Mujer con c茨mara]]
[s][vp 9 2 65535 38356 0 0]斡Los Ladrones Fantasma[n]nos han salvado![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_253 [Mujer con c茨mara]]
[s][vp 9 2 65535 38456 0 0]斡Los Ladrones Fantasma[n]nos han salvado![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_254 [Mujer con c茨mara]]
[s][vp 9 2 65535 38506 0 0]斡Los Ladrones Fantasma ten胤an raz吋n[n]desde el principio![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_255 [Mujer con c茨mara]]
[s][vp 9 2 65535 38556 0 0]斡Son unos fen吋menos![n]斡Han derrotado a los hackers![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_256 [Mujer con c茨mara]]
[s][vp 9 2 65535 38656 0 0]斡Los Ladrones Fantasma[n]nos han salvado![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_257 [Mujer con c茨mara]]
[s][vp 9 2 65535 37506 0 0]斡Los Ladrones Fantasma[n]son como dioses![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_258 [Mujer con c茨mara]]
[s][vp 9 2 65535 37554 0 0]夷Para qu姻 necesitamos a la polic胤a[n]si tenemos a los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_259 [Mujer con c茨mara]]
[s][vp 9 2 65535 37656 0 0]斡Los Ladrones Fantasma[n]est茨n de nuestro lado![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_260 [Mujer con c茨mara]]
[s][vp 9 2 65535 37706 0 0]Ahora venden productos de los[n]Ladrones Fantasma, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_261 [Mujer con c茨mara]]
[s][vp 9 2 65535 37806 0 0]Si dejamos estos asuntos en manos[n]de los Ladrones Fantasma,[n]podemos dormir tranquilos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_262 [Mujer con c茨mara]]
[s][vp 9 2 65535 37906 0 0]斡Vivan los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_263 [Mujer con c茨mara]]
[s][vp 9 2 65535 37956 0 0]斡La popularidad de los Ladrones[n]Fantasma est茨 por las nubes![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_264 [Mujer con c茨mara]]
[s][vp 9 2 65535 38056 0 0]斡No hay nada que temer[n]mientras est姻n aqu胤[n]los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_265 [Mujer con c茨mara]]
[s][vp 9 2 65535 38156 0 0]斡Yo quiero enviar un aviso[n]tan chulo como ese![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_266 [Mujer con c茨mara]]
[s][vp 9 2 65535 38206 0 0]斡Los Ladrones Fantasma son la ca隠a![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_267 [Mujer con c茨mara]]
[s][vp 9 2 65535 38256 0 0]斡Son unos verdaderos h姻roes![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_268 [Mujer con c茨mara]]
[s][vp 9 2 65535 38356 0 0]斡Me encantar胤a conocer[n]a los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_269 [Mujer con c茨mara]]
[s][vp 9 2 65535 38456 0 0]Los Ladrones Fantasma[n]son superguais.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_270 [Mujer con c茨mara]]
[s][vp 9 2 65535 38506 0 0]斡Vivan los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_271 [Mujer con c茨mara]]
[s][vp 9 2 65535 38556 0 0]夷Crees que alguno de los Ladrones[n]Fantasma estar茨 soltero?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_272 [Mujer con c茨mara]]
[s][vp 9 2 65535 38656 0 0]Quiero conseguir algunos productos[n]de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_273 [Mujer con c茨mara]]
[s][vp 9 2 65535 37501 0 0]夷Has o胤do los rumores[n]sobre Okumura Foods?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_274 [Mujer con c茨mara]]
[s][vp 9 2 65535 37551 0 0]Los tratan como esclavos, 夷verdad?[n]Qu姻 empresa tan horrible.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_275 [Mujer con c茨mara]]
[s][vp 9 2 65535 37652 0 0]Me pregunto si los rumores sobre[n]Okumura Foods ser茨n ciertos...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_276 [Mujer con c茨mara]]
[s][vp 9 2 65535 37705 0 0]夷Okumura Foods? 夷La empresa[n]propietaria de Big Bang Burger?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_277 [Mujer con c茨mara]]
[s][vp 9 2 65535 37801 0 0]夷Has o胤do los rumores[n]sobre Okumura Foods?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_278 [Mujer con c茨mara]]
[s][vp 9 2 65535 37901 0 0]La empresa creci吋 muy r茨pido,[n]pero ahora sabemos lo que pasaba[n]entre bambalinas...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_279 [Mujer con c茨mara]]
[s][vp 9 2 65535 37955 0 0]夷Okumura Foods? 夷La empresa[n]propietaria de Big Bang Burger?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_280 [Mujer con c茨mara]]
[s][vp 9 2 65535 38055 0 0]Es horrible que tratasen[n]a sus empleados como esclavos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_281 [Mujer con c茨mara]]
[s][vp 9 2 65535 38155 0 0]He o胤do que no es de fiar...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_282 [Mujer con c茨mara]]
[s][vp 9 2 65535 38205 0 0]夷Es cierto que los empleados[n]se amotinaron?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_283 [Mujer con c茨mara]]
[s][vp 9 2 65535 38251 0 0]Las empresas corruptas[n]me dan mucho miedo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_284 [Mujer con c茨mara]]
[s][vp 9 2 65535 38352 0 0]Es una barbaridad que tratasen[n]a los empleados como a esclavos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_285 [Mujer con c茨mara]]
[s][vp 9 2 65535 38460 0 0]La empresa creci吋 muy r茨pido,[n]pero ahora sabemos lo que pasaba[n]entre bambalinas...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_286 [Mujer con c茨mara]]
[s][vp 9 2 65535 38501 0 0]He visto en la tele[n]que los empleados se sublevaron.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_287 [Mujer con c茨mara]]
[s][vp 9 2 65535 38551 0 0]Me pregunto si los rumores sobre[n]Okumura Foods ser茨n ciertos...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_288 [Mujer con c茨mara]]
[s][vp 9 2 65535 38652 0 0]Es horrible que tratasen[n]a sus empleados como esclavos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_289 [Mujer con c茨mara]]
[s][vp 9 2 65535 37506 0 0]斡Me encantar胤a que solucionaran[n]m茨s problemas a nivel mundial![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_290 [Mujer con c茨mara]]
[s][vp 9 2 65535 37556 0 0]斡No me cabe duda de que[n]los Ladrones Fantasma har茨n[n]algo al respecto![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_291 [Mujer con c茨mara]]
[s][vp 9 2 65535 37656 0 0]No pasa nada...[n]斡Los Ladrones Fantasma[n]se encargar茨n de eso![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_292 [Mujer con c茨mara]]
[s][vp 9 2 65535 37700 0 0]Me pregunto a qui姻n elegir茨n[n]como pr吋ximo objetivo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_293 [Mujer con c茨mara]]
[s][vp 9 2 65535 37806 0 0]斡Todo saldr茨 bien[n]mientras lo dejemos en manos[n]de los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_294 [Mujer con c茨mara]]
[s][vp 9 2 65535 37900 0 0]斡Los Ladrones Fantasma seguir茨n[n]luchando contra los villanos![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_295 [Mujer con c茨mara]]
[s][vp 9 2 65535 37953 0 0]Me pregunto a qui姻n elegir茨n[n]como pr吋ximo objetivo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_296 [Mujer con c茨mara]]
[s][vp 9 2 65535 38050 0 0]斡Quiero que erradiquen todos[n]los males de nuestra sociedad![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_297 [Mujer con c茨mara]]
[s][vp 9 2 65535 38156 0 0]斡Los Ladrones Fantasma[n]se encargar茨n de eso![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_298 [Mujer con c茨mara]]
[s][vp 9 2 65535 38209 0 0]Hay muchas personas malas[n]en el mundo.[n]斡Espero que las reformen a todas![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_299 [Mujer con c茨mara]]
[s][vp 9 2 65535 38256 0 0]No pasa nada...[n]斡Los Ladrones Fantasma[n]se encargar茨n de eso![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_300 [Mujer con c茨mara]]
[s][vp 9 2 65535 38356 0 0]Si vais a arreglar el mundo,[n]斡夷a qu姻 esper茨is para poneros[n]manos a la obra?![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_301 [Mujer con c茨mara]]
[s][vp 9 2 65535 38456 0 0]斡Los Ladrones Fantasma[n]se encargar茨n de eso![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_302 [Mujer con c茨mara]]
[s][vp 9 2 65535 38506 0 0]Hay muchas personas malas[n]en el mundo.[n]斡Espero que las reformen a todas![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_303 [Mujer con c茨mara]]
[s][vp 9 2 65535 38556 0 0]No pasa nada...[n]斡Los Ladrones Fantasma[n]se encargar茨n de eso![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_304 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]Si vais a arreglar el mundo,[n]斡夷a qu姻 esper茨is para poneros[n]manos a la obra?![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_305 [Mujer con c茨mara]]
[s][vp 9 2 65535 37506 0 0]斡Adelante, Ladrones Fantasma![n]斡Id a por ellos y no os reprim茨is![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_306 [Mujer con c茨mara]]
[s][vp 9 2 65535 37553 0 0]斡Han enviado otro aviso![n]斡Sab胤a que ser胤a para Okumura![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_307 [Mujer con c茨mara]]
[s][vp 9 2 65535 37650 0 0]斡Estaba deseando que los Ladrones[n]Fantasma enviaran otro aviso![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_308 [Mujer con c茨mara]]
[s][vp 9 2 65535 37701 0 0]斡Ese malnacido avaricioso se merece[n]un buen castigo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_309 [Mujer con c茨mara]]
[s][vp 9 2 65535 37806 0 0]斡Adelante, Ladrones Fantasma![n]斡Id a por ellos y no os reprim茨is![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_310 [Mujer con c茨mara]]
[s][vp 9 2 65535 37903 0 0]斡No podr茨s escapar[n]de los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_311 [Mujer con c茨mara]]
[s][vp 9 2 65535 37951 0 0]斡Lo m茨s justo es que las personas[n]que hagan cosas terribles reciban[n]un buen castigo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_312 [Mujer con c茨mara]]
[s][vp 9 2 65535 38056 0 0]斡Quiero ver una disculpa mucho[n]m茨s dram茨tica que la de Madarame![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_313 [Mujer con c茨mara]]
[s][vp 9 2 65535 38159 0 0]斡Okumura merece un castigo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_314 [Mujer con c茨mara]]
[s][vp 9 2 65535 38206 0 0]斡Llevaba tiempo esperando esto,[n]Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_315 [Mujer con c茨mara]]
[s][vp 9 2 65535 38256 0 0]斡Acabad ya con ese CEO![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_316 [Mujer con c茨mara]]
[s][vp 9 2 65535 38356 0 0]斡S胤, Ladrones Fantasma![n]斡Dadles para el pelo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_317 [Mujer con c茨mara]]
[s][vp 9 2 65535 38461 0 0]斡No habr茨 piedad para ese CEO![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_318 [Mujer con c茨mara]]
[s][vp 9 2 65535 38503 0 0]斡Estoy impaciente por ver la rueda[n]de prensa de Okumura![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_319 [Mujer con c茨mara]]
[s][vp 9 2 65535 38556 0 0]斡Humillad a ese CEO![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_320 [Mujer con c茨mara]]
[s][vp 9 2 65535 38656 0 0]斡S胤, Ladrones Fantasma![n]斡Dadles para el pelo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_321 [Mujer con c茨mara]]
[s][vp 9 2 65535 37507 0 0]Seguro que lo ten胤an todo planeado[n]para que ocurriera[n]durante la rueda de prensa.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_322 [Mujer con c茨mara]]
[s][vp 9 2 65535 37551 0 0]Se han pasado...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_323 [Mujer con c茨mara]]
[s][vp 9 2 65535 37651 0 0]斡No hac胤a falta que acabarais[n]con su vida![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_324 [Mujer con c茨mara]]
[s][vp 9 2 65535 37707 0 0]斡Los Ladrones Fantasma[n]son unos asesinos![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_325 [Mujer con c茨mara]]
[s][vp 9 2 65535 37807 0 0]Seguro que lo ten胤an todo planeado[n]para que ocurriera[n]durante la rueda de prensa.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_326 [Mujer con c茨mara]]
[s][vp 9 2 65535 37907 0 0]斡Los Ladrones Fantasma[n]nos han mentido! 斡Nunca pens姻 que[n]matar胤an a una persona![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_327 [Mujer con c茨mara]]
[s][vp 9 2 65535 37957 0 0]斡Los Ladrones Fantasma no est茨n[n]del lado de la justicia![n]斡Son unos villanos![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_328 [Mujer con c茨mara]]
[s][vp 9 2 65535 38057 0 0]斡Los Ladrones Fantasma[n]han matado a una persona![n]斡Son lo peor de lo peor![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_329 [Mujer con c茨mara]]
[s][vp 9 2 65535 38157 0 0]Seguro que lo ten胤an todo planeado[n]para que ocurriera[n]durante la rueda de prensa.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_330 [Mujer con c茨mara]]
[s][vp 9 2 65535 38207 0 0]Por la forma en que lo han hecho,[n]parece que disfrutan[n]matando a la gente.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_331 [Mujer con c茨mara]]
[s][vp 9 2 65535 38257 0 0]斡Los Ladrones Fantasma[n]son unos asesinos![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_332 [Mujer con c茨mara]]
[s][vp 9 2 65535 38357 0 0]No me lo puedo creer.[n]斡Qu姻 atajo de asesinos![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_333 [Mujer con c茨mara]]
[s][vp 9 2 65535 38457 0 0]Seguro que lo ten胤an todo planeado[n]para que ocurriera[n]durante la rueda de prensa.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_334 [Mujer con c茨mara]]
[s][vp 9 2 65535 38507 0 0]Por la forma en que lo han hecho,[n]parece que disfrutan[n]matando a la gente.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_335 [Mujer con c茨mara]]
[s][vp 9 2 65535 38557 0 0]斡Los Ladrones Fantasma[n]son unos asesinos![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_336 [Mujer con c茨mara]]
[s][vp 9 2 65535 38657 0 0]No me lo puedo creer.[n]斡Qu姻 atajo de asesinos![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_337 [Mujer con c茨mara]]
[s][vp 9 2 65535 37501 0 0]夷D吋nde est茨 la polic胤a?[n]斡Tiene que hacer algo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_338 [Mujer con c茨mara]]
[s][vp 9 2 65535 37557 0 0]斡Que se den prisa en arrestar[n]a los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_339 [Mujer con c茨mara]]
[s][vp 9 2 65535 37657 0 0]Alguien tiene que hacer algo[n]con los Ladrones Fantasma.[n]斡Da igual qui姻n sea![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_340 [Mujer con c茨mara]]
[s][vp 9 2 65535 37707 0 0]斡Haced algo con los Ladrones[n]Fantasma! 斡Hay que destruir[n]a ese grupo de delincuentes![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_341 [Mujer con c茨mara]]
[s][vp 9 2 65535 37801 0 0]斡夷Qu姻 hace la polic胤a?![n]斡Vaya panda de in雨tiles![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_342 [Mujer con c茨mara]]
[s][vp 9 2 65535 37907 0 0]Entonces, 夷los episodios[n]de descontrol fueron obra[n]de los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_343 [Mujer con c茨mara]]
[s][vp 9 2 65535 37957 0 0]斡He o胤do que los causantes[n]de los incidentes fueron los[n]Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_344 [Mujer con c茨mara]]
[s][vp 9 2 65535 38057 0 0]斡夷Qu姻 hace la polic胤a?![n]斡Que los arresten de inmediato![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_345 [Mujer con c茨mara]]
[s][vp 9 2 65535 38151 0 0]夷D吋nde est茨 la polic胤a?[n]斡Tiene que hacer algo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_346 [Mujer con c茨mara]]
[s][vp 9 2 65535 38207 0 0]Yo no pago impuestos para que[n]la polic胤a ande por ah胤 de brazos[n]cruzados. 斡Haced vuestro trabajo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_347 [Mujer con c茨mara]]
[s][vp 9 2 65535 38257 0 0]Alguien tiene que hacer algo[n]con los Ladrones Fantasma.[n]斡Da igual qui姻n sea![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_348 [Mujer con c茨mara]]
[s][vp 9 2 65535 38357 0 0]斡Que alguien arreste a los Ladrones[n]Fantasma antes de que[n]me hagan da隠o![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_349 [Mujer con c茨mara]]
[s][vp 9 2 65535 38457 0 0]Yo no pago impuestos para que[n]la polic胤a ande por ah胤 de brazos[n]cruzados. 斡Haced vuestro trabajo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_350 [Mujer con c茨mara]]
[s][vp 9 2 65535 38507 0 0]斡夷Es que nadie va a hacer nada?![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_351 [Mujer con c茨mara]]
[s][vp 9 2 65535 38557 0 0]Alguien tiene que hacer algo[n]con los Ladrones Fantasma.[n]斡Da igual qui姻n sea![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_352 [Mujer con c茨mara]]
[s][vp 9 2 65535 38657 0 0]斡Que alguien arreste a los Ladrones[n]Fantasma antes de que[n]me hagan da隠o![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_353 [Mujer con c茨mara]]
[s][vp 9 2 65535 37507 0 0]夷Ofrecer una recompensa ayudar茨[n]a arrestar a los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_354 [Mujer con c茨mara]]
[s][vp 9 2 65535 37557 0 0]Creo que la recompensa por los[n]Ladrones Fantasma es la m茨s alta[n]en la historia de nuestro pa胤s.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_355 [Mujer con c茨mara]]
[s][vp 9 2 65535 37651 0 0]斡La polic胤a est茨 tardando mucho![n]斡Qu姻 lentitud![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_356 [Mujer con c茨mara]]
[s][vp 9 2 65535 37707 0 0]Quiero que arresten a los Ladrones[n]Fantasma antes de que[n]causen m茨s da隠os.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_357 [Mujer con c茨mara]]
[s][vp 9 2 65535 37804 0 0]Dicen que ofrecen dinero[n]a cambio de informaci吋n[n]sobre los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_358 [Mujer con c茨mara]]
[s][vp 9 2 65535 37904 0 0]Dicen que treinta millones de yenes[n]es la mayor recompensa[n]de la historia...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_359 [Mujer con c茨mara]]
[s][vp 9 2 65535 37957 0 0]Una recompensa, mmm...[n]Bueno, lo que sea con tal de que[n]encierren a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_360 [Mujer con c茨mara]]
[s][vp 9 2 65535 38057 0 0]Parece que la polic胤a se est茨[n]tomando en serio lo de capturarlos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_361 [Mujer con c茨mara]]
[s][vp 9 2 65535 38151 0 0]Los episodios de descontrol dan[n]mucho miedo. Alguien tiene que[n]hacer algo para pararlos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_362 [Mujer con c茨mara]]
[s][vp 9 2 65535 38205 0 0]斡夷Te has enterado[n]de lo de la recompensa?![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_363 [Mujer con c茨mara]]
[s][vp 9 2 65535 38253 0 0]斡Menudo dineral![n]斡Con esa cantidad tendr胤a[n]la vida solucionada![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_364 [Mujer con c茨mara]]
[s][vp 9 2 65535 38352 0 0]斡La polic胤a est茨 tardando mucho![n]斡Qu姻 lentitud![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_365 [Mujer con c茨mara]]
[s][vp 9 2 65535 38460 0 0]斡夷Treinta millones de yenes[n]de recompensa?![n]Pues s胤 que son peligrosos...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_366 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_367 [Mujer con c茨mara]]
[s][vp 9 2 65535 38551 0 0]Parece que la polic胤a se est茨[n]tomando en serio lo de capturar[n]a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_368 [Mujer con c茨mara]]
[s][vp 9 2 65535 38652 0 0]Espero que arresten pronto[n]a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_369 [Mujer con c茨mara]]
[s][vp 9 2 65535 37505 0 0]夷Cu茨ndo se celebran las elecciones?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_370 [Mujer con c茨mara]]
[s][vp 9 2 65535 37554 0 0]夷C吋mo se llama el pol胤tico[n]que fund吋 el partido nuevo?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_371 [Mujer con c茨mara]]
[s][vp 9 2 65535 37652 0 0]Los pol胤ticos actuales son todos[n]unos incompetentes. No me extra隠a[n]que disolvieran el parlamento.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_372 [Mujer con c茨mara]]
[s][vp 9 2 65535 37702 0 0]夷Este a隠o hay elecciones?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_373 [Mujer con c茨mara]]
[s][vp 9 2 65535 37804 0 0]夷Sab胤as que el partido gobernante[n]se ha separado?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_374 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]Este a隠o tendr姻 que tener m茨s[n]cuidado a la hora de votar.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_375 [Mujer con c茨mara]]
[s][vp 9 2 65535 37955 0 0]Toma ya...[n]Este a隠o hay elecciones.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_376 [Mujer con c茨mara]]
[s][vp 9 2 65535 38052 0 0]Dec胤an que iban a crear[n]un nuevo partido. Tengo curiosidad[n]por ver qu姻 pasa.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_377 [Mujer con c茨mara]]
[s][vp 9 2 65535 38154 0 0]Las elecciones son a finales[n]de a隠o, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_378 [Mujer con c茨mara]]
[s][vp 9 2 65535 38202 0 0]Supongo que dan tantos[n]discursos por el tema[n]de las elecciones.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_379 [Mujer con c茨mara]]
[s][vp 9 2 65535 38255 0 0]Mis padres hablan mucho[n]sobre las elecciones.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_380 [Mujer con c茨mara]]
[s][vp 9 2 65535 38354 0 0]Espero que el siguiente gobierno[n]no sea corrupto.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_381 [Mujer con c茨mara]]
[s][vp 9 2 65535 38452 0 0]El partido actual se ha visto[n]envuelto en multitud[n]de esc茨ndalos y problemas.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_382 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_383 [Mujer con c茨mara]]
[s][vp 9 2 65535 38554 0 0]夷Las elecciones son[n]a finales de a隠o?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_384 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]El otro d胤a vimos a un pol胤tico[n]dando un discurso, 夷a que s胤?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_385 [Mujer con c茨mara]]
[s][vp 9 2 65535 37507 0 0]夷Cu茨ndo piensan arrestar[n]a los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_386 [Mujer con c茨mara]]
[s][vp 9 2 65535 37557 0 0]斡Que se den prisa en arrestar[n]a los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_387 [Mujer con c茨mara]]
[s][vp 9 2 65535 37651 0 0]夷Cu茨ndo van a arrestarlos?[n]斡La polic胤a es in雨til![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_388 [Mujer con c茨mara]]
[s][vp 9 2 65535 37701 0 0]夷Cu茨nto tiempo piensan dejar que[n]los Ladrones Fantasma pululen[n]por ah胤 libremente?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_389 [Mujer con c茨mara]]
[s][vp 9 2 65535 37804 0 0]夷Todav胤a no han capturado[n]a los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_390 [Mujer con c茨mara]]
[s][vp 9 2 65535 37901 0 0]夷D吋nde est茨 la polic胤a?[n]斡Tiene que hacer algo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_391 [Mujer con c茨mara]]
[s][vp 9 2 65535 37951 0 0]斡夷Qu姻 hace la polic胤a?![n]斡Que atrapen a los culpables ya![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_392 [Mujer con c茨mara]]
[s][vp 9 2 65535 38057 0 0]斡夷Cu茨ndo va a aparecer[n]la polic胤a con un plan?![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_393 [Mujer con c茨mara]]
[s][vp 9 2 65535 38151 0 0]夷Cu茨nto tiempo m茨s van a dejar[n]libres a esos asesinos?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_394 [Mujer con c茨mara]]
[s][vp 9 2 65535 38201 0 0]Yo no pago impuestos para que[n]la polic胤a ande por ah胤 de brazos[n]cruzados. 斡Haced vuestro trabajo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_395 [Mujer con c茨mara]]
[s][vp 9 2 65535 38254 0 0]Los Ladrones Fantasma aparecieron[n]por primera vez en el Shujin, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_396 [Mujer con c茨mara]]
[s][vp 9 2 65535 38351 0 0]Los episodios de descontrol[n]los causaron los Ladrones Fantasma,[n]夷no? Que alguien haga algo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_397 [Mujer con c茨mara]]
[s][vp 9 2 65535 38457 0 0]Alguien tiene que hacer algo[n]con los Ladrones Fantasma.[n]斡La polic胤a es muy incompetente![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_398 [Mujer con c茨mara]]
[s][vp 9 2 65535 38507 0 0]斡夷Es que nadie va a hacer nada?![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_399 [Mujer con c茨mara]]
[s][vp 9 2 65535 38551 0 0]No podemos fiarnos[n]ni de la polic胤a...[n]Por favor, que alguien haga algo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_400 [Mujer con c茨mara]]
[s][vp 9 2 65535 38651 0 0]斡夷Cu茨ndo van a detener[n]a los Ladrones Fantasma?![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_401 [Mujer con c茨mara]]
[s][vp 9 2 65535 37500 0 0]Me he enterado de que Shido[n]es muy ingenioso para ser pol胤tico.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_402 [Mujer con c茨mara]]
[s][vp 9 2 65535 37553 0 0]夷Has o胤do hablar de un pol胤tico[n]que se llama Shido?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_403 [Mujer con c茨mara]]
[s][vp 9 2 65535 37653 0 0]He o胤do hablar del pol胤tico ese,[n]el tal Shido. Se supone[n]que es bastante bueno.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_404 [Mujer con c茨mara]]
[s][vp 9 2 65535 37700 0 0]Parece que Shido[n]promete, 斡no como[n]los dem茨s pol胤ticos![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_405 [Mujer con c茨mara]]
[s][vp 9 2 65535 37800 0 0]Shido promete.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_406 [Mujer con c茨mara]]
[s][vp 9 2 65535 37903 0 0]A lo mejor voto a Shido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_407 [Mujer con c茨mara]]
[s][vp 9 2 65535 37954 0 0]El tal Shido da[n]unos discursos incre胤bles.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_408 [Mujer con c茨mara]]
[s][vp 9 2 65535 38050 0 0]Me han dicho que Shido es[n]el que ha fundado el nuevo partido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_409 [Mujer con c茨mara]]
[s][vp 9 2 65535 38161 0 0]夷Has escuchado el discurso[n]de Shido? La verdad[n]es que lo respeto mucho.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_410 [Mujer con c茨mara]]
[s][vp 9 2 65535 38203 0 0]Shido no dice las mismas[n]cosas que han ido soltando[n]los pol胤ticos incompetentes.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_411 [Mujer con c茨mara]]
[s][vp 9 2 65535 38254 0 0]Mis padres dec胤an[n]muchas cosas buenas sobre Shido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_412 [Mujer con c茨mara]]
[s][vp 9 2 65535 38354 0 0]Ha sido un discurso estupendo.[n]Ese era el se隠or Shido, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_413 [Mujer con c茨mara]]
[s][vp 9 2 65535 38454 0 0]Shido parece diferente[n]a los dem茨s pol胤ticos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_414 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_415 [Mujer con c茨mara]]
[s][vp 9 2 65535 38561 0 0]Masayoshi Shido[n]es bastante guapo, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_416 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]夷A que Shido[n]es un pol胤tico excelente?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_417 [Mujer con c茨mara]]
[s][vp 9 2 65535 37507 0 0]夷Se suicid吋 porque lo arrestaron?[n]Venga ya...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_418 [Mujer con c茨mara]]
[s][vp 9 2 65535 37554 0 0]夷Es cierto que han atrapado[n]al l胤der de los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_419 [Mujer con c茨mara]]
[s][vp 9 2 65535 37651 0 0]Por fin atrapamos al cabecilla[n]de los Ladrones Fantasma[n]y va y se suicida...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_420 [Mujer con c茨mara]]
[s][vp 9 2 65535 37705 0 0]夷Es cierto que el l胤der[n]de los Ladrones Fantasma[n]era menor de edad?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_421 [Mujer con c茨mara]]
[s][vp 9 2 65535 37800 0 0]斡Me han dicho que por fin[n]han atrapado al l胤der[n]de los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_422 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]Supongo que nunca sabremos[n]cu茨l era el verdadero objetivo[n]de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_423 [Mujer con c茨mara]]
[s][vp 9 2 65535 37952 0 0]Me qued姻 de piedra cuando me enter姻[n]de que el l胤der de los Ladrones[n]Fantasma se hab胤a suicidado.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_424 [Mujer con c茨mara]]
[s][vp 9 2 65535 38051 0 0]Ten胤a que estar muy loco[n]para suicidarse[n]el d胤a que lo arrestaron.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_425 [Mujer con c茨mara]]
[s][vp 9 2 65535 38151 0 0]斡夷De verdad ha muerto[n]el l胤der de los Ladrones Fantasma?![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_426 [Mujer con c茨mara]]
[s][vp 9 2 65535 38205 0 0]夷Uno de los Ladrones Fantasma[n]se ha suicidado? No estar胤a[n]bien de la cabeza...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_427 [Mujer con c茨mara]]
[s][vp 9 2 65535 38252 0 0]夷Lo arrestaron y luego se suicid吋?[n]斡夷Qu姻 est茨 pasando?![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_428 [Mujer con c茨mara]]
[s][vp 9 2 65535 38355 0 0]夷Se suicid吋 el mismo[n]d胤a que lo arrestaron? Pues s胤[n]que ha cambiado r茨pido la cosa.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_429 [Mujer con c茨mara]]
[s][vp 9 2 65535 38455 0 0]Pero si acaban de arrestarlo.[n]夷Se ha suicidado?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_430 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_431 [Mujer con c茨mara]]
[s][vp 9 2 65535 38554 0 0]斡Me alegro de que hayan[n]detenido a los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_432 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]Ahora que ya no est茨n los Ladrones[n]Fantasma, puedo relajarme.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_433 [Mujer con c茨mara]]
[s][vp 9 2 65535 37503 0 0]En estos tiempos que corren,[n]necesitamos pol胤ticos como Shido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_434 [Mujer con c茨mara]]
[s][vp 9 2 65535 37553 0 0]Shido es el hombre perfecto[n]para guiarnos en esta era.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_435 [Mujer con c茨mara]]
[s][vp 9 2 65535 37653 0 0]Shido no tiene enemigos.[n]斡Seguro que gana las elecciones![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_436 [Mujer con c茨mara]]
[s][vp 9 2 65535 37700 0 0]斡Seguro que Shido[n]gana las elecciones![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_437 [Mujer con c茨mara]]
[s][vp 9 2 65535 37803 0 0]斡Seguro que Shido[n]gana las elecciones![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_438 [Mujer con c茨mara]]
[s][vp 9 2 65535 37903 0 0]Shido va a mejorar el pa胤s.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_439 [Mujer con c茨mara]]
[s][vp 9 2 65535 37954 0 0]斡Todo ir茨 bien[n]mientras dejemos las cosas[n]en manos del se隠or Shido![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_440 [Mujer con c茨mara]]
[s][vp 9 2 65535 38050 0 0]Solo Shido es capaz.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_441 [Mujer con c茨mara]]
[s][vp 9 2 65535 38159 0 0]夷Elecciones para qu姻?[n]斡Que proclamen a Shido[n]ganador y punto![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_442 [Mujer con c茨mara]]
[s][vp 9 2 65535 38200 0 0]Los Ladrones Fantasma[n]han fracasado, as胤 que supongo[n]que Shido es nuestra 雨nica opci吋n.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_443 [Mujer con c茨mara]]
[s][vp 9 2 65535 38254 0 0]Dicen que todo ir茨 bien[n]mientras tengamos al se隠or Shido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_444 [Mujer con c茨mara]]
[s][vp 9 2 65535 38354 0 0]斡Shido es el 雨nico[n]capaz de dirigir el pa胤s![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_445 [Mujer con c茨mara]]
[s][vp 9 2 65535 38453 0 0]斡El futuro es de Shido![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_446 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_447 [Mujer con c茨mara]]
[s][vp 9 2 65535 38561 0 0]斡Todo saldr茨 bien[n]mientras tengamos a Shido![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_448 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]斡Shido lo cambiar茨 todo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_449 [Mujer con c茨mara]]
[s][vp 9 2 65535 37504 0 0]El se隠or Shido es el 雨nico pol胤tico[n]del que no se rumorea nada malo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_450 [Mujer con c茨mara]]
[s][vp 9 2 65535 37550 0 0]夷Has escuchado el discurso[n]del pol胤tico ese, Shido?[n]Es un hombre incre胤ble.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_451 [Mujer con c茨mara]]
[s][vp 9 2 65535 37653 0 0]Todo ir茨 bien mientras[n]lo dejemos en manos de Shido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_452 [Mujer con c茨mara]]
[s][vp 9 2 65535 37700 0 0]Shido est茨 trabajando[n]mucho en su campa隠a.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_453 [Mujer con c茨mara]]
[s][vp 9 2 65535 37800 0 0]Shido es la 雨nica alternativa real.[n]斡No hacen falta elecciones![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_454 [Mujer con c茨mara]]
[s][vp 9 2 65535 37904 0 0]Dicen que, si gana,[n]Shido ser茨 primer ministro.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_455 [Mujer con c茨mara]]
[s][vp 9 2 65535 37950 0 0]Shido tiene un aura diferente.[n]Se nota que es especial.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_456 [Mujer con c茨mara]]
[s][vp 9 2 65535 38050 0 0]Shido har茨 algo[n]para arreglar el pa胤s.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_457 [Mujer con c茨mara]]
[s][vp 9 2 65535 38153 0 0]夷Por qu姻 Shido[n]no se autoproclama primer ministro?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_458 [Mujer con c茨mara]]
[s][vp 9 2 65535 38200 0 0]Tengo que participar[n]en las elecciones[n]para votar a Shido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_459 [Mujer con c茨mara]]
[s][vp 9 2 65535 38254 0 0]斡El tal Shido es famos胤simo![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_460 [Mujer con c茨mara]]
[s][vp 9 2 65535 38350 0 0]斡Shido es de esas personas[n]con las que se puede contar[n]para cualquier cosa![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_461 [Mujer con c茨mara]]
[s][vp 9 2 65535 38453 0 0]Pocos est茨n a la altura de Shido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_462 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_463 [Mujer con c茨mara]]
[s][vp 9 2 65535 38561 0 0]Las cosas que dice Shido[n]suenan muy convincentes.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_464 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]Shido ha trabajado much胤simo[n]en su campa隠a.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_465 [Mujer con c茨mara]]
[s][vp 9 2 65535 37502 0 0]夷De qui姻n me f胤o? 夷De los[n]Ladrones Fantasma o de Shido?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_466 [Mujer con c茨mara]]
[s][vp 9 2 65535 37552 0 0]夷Qui姻n lleva raz吋n?[n]夷Los Ladrones Fantasma[n]o Shido?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_467 [Mujer con c茨mara]]
[s][vp 9 2 65535 37655 0 0]Shido lo ha negado todo.[n]A lo mejor son rumores inventados[n]por los Ladrones Fantasma...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_468 [Mujer con c茨mara]]
[s][vp 9 2 65535 37702 0 0]Entonces, 夷los Ladrones[n]Fantasma dec胤an la verdad?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_469 [Mujer con c茨mara]]
[s][vp 9 2 65535 37804 0 0]Creo que Shido lleva raz吋n.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_470 [Mujer con c茨mara]]
[s][vp 9 2 65535 37905 0 0]Qu姻 raro[n]que hayan vuelto[n]tan de repente.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_471 [Mujer con c茨mara]]
[s][vp 9 2 65535 37952 0 0]Es de locos que los[n]Ladrones Fantasma hayan[n]pirateado una emisi吋n en directo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_472 [Mujer con c茨mara]]
[s][vp 9 2 65535 38055 0 0]Me da igual si lleva raz吋n o no.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_473 [Mujer con c茨mara]]
[s][vp 9 2 65535 38150 0 0]夷No podemos decir que Shido[n]lleva raz吋n y acabar con esto?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_474 [Mujer con c茨mara]]
[s][vp 9 2 65535 38201 0 0]Ya me da igual qui姻n[n]dice la verdad[n]y qui姻n miente.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_475 [Mujer con c茨mara]]
[s][vp 9 2 65535 38255 0 0]夷Ser茨 verdad lo que dicen[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_476 [Mujer con c茨mara]]
[s][vp 9 2 65535 38352 0 0]Shido lo niega, pero...[n]no s姻 si fiarme de 姻l.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_477 [Mujer con c茨mara]]
[s][vp 9 2 65535 38455 0 0]Ya ni siquiera importa[n]qui姻n lleve raz吋n.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_478 [Mujer con c茨mara]]
[s][vp 9 2 65535 38502 0 0]Cre胤a que los Ladrones[n]Fantasma hab胤an muerto.[n]夷Qu姻 est茨 pasando?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_479 [Mujer con c茨mara]]
[s][vp 9 2 65535 38555 0 0]夷Un esc茨ndalo sobre Shido?[n]夷No ser茨n calumnias?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_480 [Mujer con c茨mara]]
[s][vp 9 2 65535 38655 0 0]夷Ser茨 verdad lo que dicen[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_481 [Mujer con c茨mara]]
[s][vp 9 2 65535 37501 0 0]Entonces, 夷Shido nos ha estado[n]enga隠ando todo el tiempo?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_482 [Mujer con c茨mara]]
[s][vp 9 2 65535 37551 0 0]夷Qu姻 vamos a hacer sin Shido?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_483 [Mujer con c茨mara]]
[s][vp 9 2 65535 37651 0 0]夷No se encuentra bien?[n]Espero que no dimita...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_484 [Mujer con c茨mara]]
[s][vp 9 2 65535 37701 0 0]Cre胤a que todo ir胤a bien[n]mientras tuvi姻ramos a Shido...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_485 [Mujer con c茨mara]]
[s][vp 9 2 65535 37802 0 0]Pero se supon胤a que Shido[n]iba a cambiar el pa胤s...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_486 [Mujer con c茨mara]]
[s][vp 9 2 65535 37901 0 0]Las cosas no se quedar茨n as胤, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_487 [Mujer con c茨mara]]
[s][vp 9 2 65535 37951 0 0]夷Qu姻 ha pasado?[n]Cre胤a que no nos equivocar胤amos[n]con el se隠or Shido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_488 [Mujer con c茨mara]]
[s][vp 9 2 65535 38055 0 0]Shido no va a dimitir, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_489 [Mujer con c茨mara]]
[s][vp 9 2 65535 38151 0 0]斡Tiene que ser una broma![n]No me puedo creer[n]que Shido estuviera mintiendo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_490 [Mujer con c茨mara]]
[s][vp 9 2 65535 38202 0 0]斡Shido![n]斡Por favor, dime que es mentira![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_491 [Mujer con c茨mara]]
[s][vp 9 2 65535 38252 0 0]斡Cre胤a que todo ir胤a bien[n]mientras tuvi姻ramos al se隠or[n]Shido de nuestro lado![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_492 [Mujer con c茨mara]]
[s][vp 9 2 65535 38351 0 0]Cre胤a que todo ir胤a bien[n]mientras tuvi姻ramos al se隠or[n]Shido de nuestro lado...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_493 [Mujer con c茨mara]]
[s][vp 9 2 65535 38451 0 0]夷Por qu姻? 夷C吋mo? Shido...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_494 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_495 [Mujer con c茨mara]]
[s][vp 9 2 65535 38552 0 0]夷Por qu姻, Shido?[n]No puede ser cierto...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_496 [Mujer con c茨mara]]
[s][vp 9 2 65535 38651 0 0]Pero 斡si Shido dijo[n]que todo saldr胤a bien![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_497 [Mujer con c茨mara]]
[s][vp 9 2 65535 37501 0 0]Alguien tiene que[n]reemplazar a Shido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_498 [Mujer con c茨mara]]
[s][vp 9 2 65535 37552 0 0]Me da igual qui姻n,[n]pero que alguien haga algo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_499 [Mujer con c茨mara]]
[s][vp 9 2 65535 37652 0 0]夷Qu姻 est茨 pasando...?[n]Ayuda...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_500 [Mujer con c茨mara]]
[s][vp 9 2 65535 37702 0 0]夷C吋mo piensan arreglar este asunto?[n]Alguien tiene que hacer algo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_501 [Mujer con c茨mara]]
[s][vp 9 2 65535 37802 0 0]夷C吋mo hemos llegado a esto?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_502 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]Me da igual qui姻n sea,[n]pero hay que ponerle soluci吋n.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_503 [Mujer con c茨mara]]
[s][vp 9 2 65535 37952 0 0]Se acab吋... y nada puede cambiarlo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_504 [Mujer con c茨mara]]
[s][vp 9 2 65535 38060 0 0]Nada... No se puede[n]hacer nada para ayudar.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_505 [Mujer con c茨mara]]
[s][vp 9 2 65535 38152 0 0]Sin Shido, el pa胤s se va al traste.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_506 [Mujer con c茨mara]]
[s][vp 9 2 65535 38201 0 0]El pa胤s se va al traste.[n]Se acab吋...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_507 [Mujer con c茨mara]]
[s][vp 9 2 65535 38252 0 0]夷Qui姻n tiene la culpa de todo esto?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_508 [Mujer con c茨mara]]
[s][vp 9 2 65535 38352 0 0]夷C吋mo ha pasado esto?[n]Que alguien haga algo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_509 [Mujer con c茨mara]]
[s][vp 9 2 65535 38452 0 0]夷Qu姻 est茨 pasando?[n]Que alguien haga algo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_510 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_511 [Mujer con c茨mara]]
[s][vp 9 2 65535 38552 0 0]Da igual lo que hagamos.[n]Se acab吋...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_512 [Mujer con c茨mara]]
[s][vp 9 2 65535 38655 0 0]夷Qu姻 est茨 pasando...?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_513 [Mujer con c茨mara]]
[s][vp 9 2 65535 39150 0 0]Puede que haga algo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_514 [Mujer con c茨mara]]
[s][vp 9 2 65535 37603 0 0]El t胤o ha estado currando[n]de lo lindo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_515 [Mujer con c茨mara]]
[s]Qu姻 r茨pido se ha pasado el a隠o...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_516 [Mujer con c茨mara]]
[s]Hace bastante calor.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_517 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_518 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_519 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_520 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_521 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_522 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_523 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_524 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_525 [Mujer con c茨mara]]
[s]夷No hubo un incidente[n]la pasada primavera?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_526 [Mujer con c茨mara]]
[s]Ya es primavera.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_527 [Mujer con c茨mara]]
[s]Qu姻 r茨pido se ha pasado el a隠o...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_528 [Mujer con c茨mara]]
[s]Hace bastante calor.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_529 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_530 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_531 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_532 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_533 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_534 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_535 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_536 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_537 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_538 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_539 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_540 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_541 [Mujer con c茨mara]]
[s]Pf, qu姻 co隠azo tener que ir[n]a trabajar... A lo mejor digo[n]que me he puesto malo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_542 [Mujer con c茨mara]]
[s]Me pregunto si estar茨[n]ocurriendo algo interesante.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_543 [Mujer con c茨mara]]
[s]De todas formas,[n]no puedo hacer nada.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_544 [Mujer con c茨mara]]
[s]夷Alguna vez ocurrir茨 algo bueno?[n]Que alguien haga algo...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_545 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_546 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_547 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_All_548 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim [Mujer con c茨mara]]
[s][vp 9 2 65535 37505 0 0]Ha vuelto a ocurrir[n]eso que hace que la gente[n]se vuelva loca de repente.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_2 [Mujer con c茨mara]]
[s][vp 9 2 65535 37552 0 0]Me da miedo coger[n]el tren despu姻s de ver algo as胤.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_3 [Mujer con c茨mara]]
[s][vp 9 2 65535 37652 0 0]Los trenes se han parado[n]de momento.[n]Menudo cabreo tengo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_4 [Mujer con c茨mara]]
[s][vp 9 2 65535 37705 0 0]夷De verdad fue un accidente?[n]Igual fue una maldici吋n...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_5 [Mujer con c茨mara]]
[s]El tren se ha parado.[n]夷Qu姻 cojones est茨 pasando?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_6 [Mujer con c茨mara]]
[s]郁ltimamente ha habido[n]muchos accidentes. Podr胤a haber[n]otro en cualquier momento.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_7 [Mujer con c茨mara]]
[s]Aqu胤 la seguridad da pena.[n]Me da mucho miedo coger el tren.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_8 [Mujer con c茨mara]]
[s]郁ltimamente ha habido[n]muchos accidentes. Podr胤a haber[n]otro en cualquier momento.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_9 [Mujer con c茨mara]]
[s][vp 9 2 65535 37500 0 0]斡El artista Madarame[n]ha salido en Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_10 [Mujer con c茨mara]]
[s][vp 9 2 65535 37550 0 0]斡Sali吋 en Good Morning Japan![n]Ser茨 un artista famoso.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_11 [Mujer con c茨mara]]
[s][vp 9 2 65535 37654 0 0]Dicen que en el mundo[n]del arte japon姻s[n]nadie est茨 a su altura.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_12 [Mujer con c茨mara]]
[s][vp 9 2 65535 37704 0 0]Pues ser茨 un artista[n]muy famoso si ha salido[n]en Good Morning Japan, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_13 [Mujer con c茨mara]]
[s][vp 9 2 65535 37804 0 0]斡El artista Madarame[n]ha salido en Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_14 [Mujer con c茨mara]]
[s][vp 9 2 65535 37904 0 0]斡Sali吋 en Good Morning Japan![n]Ser茨 un artista famoso.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_15 [Mujer con c茨mara]]
[s][vp 9 2 65535 37953 0 0]Pues ser茨 un artista[n]muy famoso si ha salido[n]en Good Morning Japan, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_16 [Mujer con c茨mara]]
[s][vp 9 2 65535 38050 0 0]斡El artista Madarame[n]ha salido en Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_17 [Mujer con c茨mara]]
[s][vp 9 2 65535 38153 0 0]Dicen que en el mundo[n]del arte japon姻s[n]nadie est茨 a su altura.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_18 [Mujer con c茨mara]]
[s][vp 9 2 65535 38204 0 0]Pues ser茨 un artista[n]muy famoso si ha salido[n]en Good Morning Japan, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_19 [Mujer con c茨mara]]
[s][vp 9 2 65535 38254 0 0]Dicen que en el mundo[n]del arte japon姻s[n]nadie est茨 a su altura.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_20 [Mujer con c茨mara]]
[s][vp 9 2 65535 38350 0 0]斡El artista Madarame[n]ha salido en Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_21 [Mujer con c茨mara]]
[s][vp 9 2 65535 38454 0 0]Dicen que en el mundo[n]del arte japon姻s[n]nadie est茨 a su altura.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_22 [Mujer con c茨mara]]
[s][vp 9 2 65535 38504 0 0]Pues ser茨 un artista[n]muy famoso si ha salido[n]en Good Morning Japan, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_23 [Mujer con c茨mara]]
[s][vp 9 2 65535 38561 0 0]Dicen que en el mundo[n]del arte japon姻s[n]nadie est茨 a su altura.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_24 [Mujer con c茨mara]]
[s][vp 9 2 65535 38654 0 0]斡El artista Madarame[n]ha salido en Good Morning Japan![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_25 [Mujer con c茨mara]]
[s][vp 9 2 65535 37501 0 0]Dicen que chantajean[n]y amenazan a la gente sin parar...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_26 [Mujer con c茨mara]]
[s][vp 9 2 65535 37555 0 0]夷Es cierto que la polic胤a no ha[n]podido ponerles la mano encima?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_27 [Mujer con c茨mara]]
[s][vp 9 2 65535 37652 0 0]Dicen que obligan[n]a la gente a prostituirse...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_28 [Mujer con c茨mara]]
[s][vp 9 2 65535 37701 0 0]Dicen que te obligan a hacer[n]cosas horribles si te atrapan...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_29 [Mujer con c茨mara]]
[s][vp 9 2 65535 37805 0 0]Seg雨n los rumores,[n]hay un mont吋n de informes[n]de la polic胤a sobre ellos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_30 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]Dicen que usan[n]trucos de lo m茨s sucios.[n]Son lo peor.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_31 [Mujer con c茨mara]]
[s][vp 9 2 65535 37952 0 0]Dicen que te obligan a hacer[n]cosas horribles si te atrapan...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_32 [Mujer con c茨mara]]
[s][vp 9 2 65535 38051 0 0]Hasta la polic胤a[n]est茨 teniendo problemas.[n]夷Qu姻 vamos a hacer?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_33 [Mujer con c茨mara]]
[s][vp 9 2 65535 38154 0 0]夷Es cierto que la polic胤a no ha[n]podido ponerles la mano encima?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_34 [Mujer con c茨mara]]
[s][vp 9 2 65535 38205 0 0]Dicen que usan[n]trucos de lo m茨s sucios.[n]Son lo peor.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_35 [Mujer con c茨mara]]
[s][vp 9 2 65535 38251 0 0]Dicen que obligan[n]a la gente a venderse...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_36 [Mujer con c茨mara]]
[s][vp 9 2 65535 38351 0 0]Hasta la polic胤a[n]est茨 teniendo problemas.[n]夷Qu姻 vamos a hacer?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_37 [Mujer con c茨mara]]
[s][vp 9 2 65535 38452 0 0]Dicen que ni la polic胤a puede[n]ponerles la mano encima...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_38 [Mujer con c茨mara]]
[s][vp 9 2 65535 38502 0 0]Dicen que usan[n]trucos de lo m茨s sucios.[n]Son lo peor.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_39 [Mujer con c茨mara]]
[s][vp 9 2 65535 38552 0 0]Dicen que el grupo[n]no solo extorsiona, sino que[n]tambi姻n prostituye a las chicas.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_40 [Mujer con c茨mara]]
[s][vp 9 2 65535 38655 0 0]Hasta la polic胤a[n]est茨 teniendo problemas.[n]夷Qu姻 vamos a hacer?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_41 [Mujer con c茨mara]]
[s][vp 9 2 65535 37508 0 0]夷Quieres ponerte un yukata y ver[n]los fuegos artificiales conmigo?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_42 [Mujer con c茨mara]]
[s][vp 9 2 65535 37550 0 0]Ya es hora de que empiecen[n]los fuegos artificiales.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_43 [Mujer con c茨mara]]
[s][vp 9 2 65535 37654 0 0]夷Quieres ponerte un yukata[n]para ver los fuegos artificiales?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_44 [Mujer con c茨mara]]
[s][vp 9 2 65535 37703 0 0]斡Qu姻 ganas tengo de ir[n]a ver los fuegos artificiales![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_45 [Mujer con c茨mara]]
[s][vp 9 2 65535 37803 0 0]夷Quieres ponerte un yukata y ver[n]los fuegos artificiales conmigo?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_46 [Mujer con c茨mara]]
[s][vp 9 2 65535 37902 0 0]Hace a隠os que no[n]voy a ver fuegos artificiales.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_47 [Mujer con c茨mara]]
[s][vp 9 2 65535 37950 0 0]斡Qu姻 ganas tengo de ir[n]a ver los fuegos artificiales![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_48 [Mujer con c茨mara]]
[s][vp 9 2 65535 38052 0 0]夷Qu姻 tiene de divertido[n]ver los fuegos artificiales?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_49 [Mujer con c茨mara]]
[s][vp 9 2 65535 37502 0 0]Ha sido una ejecuci吋n p雨blica.[n]Qu姻 horror...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_50 [Mujer con c茨mara]]
[s][vp 9 2 65535 37551 0 0]夷Has visto la rueda de prensa[n]del se隠or Okumura? Menuda locura...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_51 [Mujer con c茨mara]]
[s][vp 9 2 65535 37652 0 0]La rueda de prensa del se隠or[n]Okumura ha sido una locura.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_52 [Mujer con c茨mara]]
[s][vp 9 2 65535 37701 0 0]S胤, quer胤a que lo castigaran,[n]pero se han pasado tres pueblos.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_53 [Mujer con c茨mara]]
[s][vp 9 2 65535 37801 0 0]No eran efectos especiales, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_54 [Mujer con c茨mara]]
[s][vp 9 2 65535 37901 0 0]De repente, entorn吋 los ojos[n]y se cay吋. Fue insoportable.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_55 [Mujer con c茨mara]]
[s][vp 9 2 65535 37952 0 0]Solo de pensarlo[n]se me pone la piel de gallina.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_56 [Mujer con c茨mara]]
[s][vp 9 2 65535 38051 0 0]Fue demasiado.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_57 [Mujer con c茨mara]]
[s][vp 9 2 65535 38151 0 0]Se pasaron un poco.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_58 [Mujer con c茨mara]]
[s][vp 9 2 65535 38201 0 0]Ha sido una ejecuci吋n p雨blica.[n]Qu姻 horror...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_59 [Mujer con c茨mara]]
[s][vp 9 2 65535 38252 0 0]No eran efectos especiales[n]ni nada parecido, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_60 [Mujer con c茨mara]]
[s][vp 9 2 65535 38352 0 0]Puso los ojos en blanco...[n]Qu姻 mal rollo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_61 [Mujer con c茨mara]]
[s][vp 9 2 65535 38460 0 0]Se pasaron un poco.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_62 [Mujer con c茨mara]]
[s][vp 9 2 65535 38502 0 0]Ha sido una ejecuci吋n p雨blica.[n]Qu姻 horror...[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_63 [Mujer con c茨mara]]
[s][vp 9 2 65535 38552 0 0]No eran efectos especiales[n]ni nada parecido, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_64 [Mujer con c茨mara]]
[s][vp 9 2 65535 38652 0 0]Puso los ojos en blanco...[n]Qu姻 mal rollo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_65 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_66 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_67 [Mujer con c茨mara]]
[s][vp 9 2 65535 37653 0 0]Akechi, el detective, se ha vuelto[n]muy popular 雨ltimamente.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_68 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_69 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_70 [Mujer con c茨mara]]
[s][vp 9 2 65535 37904 0 0]Es muy inteligente a pesar[n]de ir a雨n al instituto.[n]斡Le espera un futuro brillante![n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_71 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_72 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_73 [Mujer con c茨mara]]
[s][vp 9 2 65535 38150 0 0]夷Has o胤do hablar[n]de ese gran detective?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_74 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_75 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_76 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_77 [Mujer con c茨mara]]
[s][vp 9 2 65535 38454 0 0]夷Conoces a Akechi, el detective?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_78 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_79 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_80 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_81 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_82 [Mujer con c茨mara]]
[s][vp 9 2 65535 37550 0 0]Creo que lo que dijo Akechi[n]tambi姻n tiene sentido.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_83 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_84 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_85 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_86 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_87 [Mujer con c茨mara]]
[s][vp 9 2 65535 37952 0 0]Destruir el coraz吋n de alguien...[n]Si lo piensas, da miedo.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_88 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_89 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_90 [Mujer con c茨mara]]
[s][vp 9 2 65535 38204 0 0]夷Qu姻 te parece lo que dijo[n]Akechi en televisi吋n?[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_91 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_92 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_93 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_94 [Mujer con c茨mara]]
[s][vp 9 2 65535 38504 0 0]Yo no veo problema[n]si solo van a por malhechores.[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_95 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_SHIBUYA_main_Lim_96 [Mujer con c茨mara]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42511 0 0]Las clases particulares[n]son lo mejor. Creo que me gustan[n]m茨s que el instituto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42661 0 0]Creo que mi hermano me va a echar[n]una mano con los estudios,[n]pero 夷te apetece venir?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42353 0 0]S胤, comparto habitaci吋n[n]con mi hermana. A veces[n]grita mucho, pero 斡es graciosa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43351 0 0]Vete a casa ya, que es tarde.[n]Te van a pillar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_05_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43008 0 0]夷Puedo ir a ver qu姻 me perd胤[n]en clase de biolog胤a?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_06_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42251 0 0]斡Cre胤a que te hab胤as mudado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_07_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42601 0 0]Tienes pinta de ser m茨s aburrido.[n]Est茨s como m茨s serio.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_08_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42653 0 0]斡Uy! Pues ir姻 a buscarlo.[n]Cuantos m茨s seamos,[n]mejor nos lo pasaremos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_09_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42853 0 0]As胤 son las cosas.[n]Vamos a descansar un rato.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_10_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42904 0 0]Voy a ser aprendiz[n]cuando me grad雨e.[n]Adem茨s, ya lo tenemos hablado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_11_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43352 0 0]夷No te parece que los bares[n]cierran muy pronto?[n]Ojal茨 abriesen hasta tarde.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_12_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42555 0 0]Me han comentado[n]que vas a cogerte unos d胤as.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_503_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42102 0 0]He o胤do que estaban poniendo[n]a caldo a nuestro instituto despu姻s[n]de lo que pas吋 con Kamoshida.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_503_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42255 0 0]夷Vas a ir a orientaci吋n?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_503_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43105 0 0]夷De verdad que ese tal Maruki[n]va a servir de algo?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_503_05_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42555 0 0]夷Las sesiones las llevan a cabo[n]en la enfermer胤a?[n]Es que tengo curiosidad.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_503_06_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42554 0 0]夷Podremos confiar en 姻l?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_503_07_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42950 0 0]El doctor Maruki es guap胤simo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_504_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42255 0 0]夷Para qu姻 sirve limpiar?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_504_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42655 0 0]Eso de despertar corazones[n]es imposible.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_504_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42602 0 0]La movida de limpiar[n]es el d胤a 30, 夷no? Menudo pe隠azo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_504_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43152 0 0]Van a despedir a Kamoshida.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_504_05_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42451 0 0]夷Por qu姻 narices hay que ir[n]a limpiar? Yo no lo entiendo.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_504_06_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42452 0 0]Qu姻 asco da limpiar...[n]Lo 雨nico que vamos a conseguir[n]es cansarnos.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_504_07_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42451 0 0]夷Por qu姻 nos toca limpiar?[n]Qu姻 pe隠azo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_504_08_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42655 0 0]Qu姻 verg鵜enza me dio ir[n]por el parque con ropa de deporte...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_505_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43105 0 0]Me han contado que Yoshizawa[n]est茨 haciendo buenas migas[n]con el nuevo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_505_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43154 0 0]夷En serio? Y encima es guapa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_505_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42655 0 0]Me parece alucinante que el nuevo[n]sea amigo de Yoshizawa.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_505_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43354 0 0]Seguro que se complementan bien.[n]La verdad es que ambos son[n]una desgracia para el instituto.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_505_05_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43201 0 0]La gente lista siempre consigue[n]lo que quiere. Qu姻 suerte.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43252 0 0]夷Te has enterado[n]de lo de la gimnasta?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42202 0 0]No la menosprecies.[n]Se esfuerza mucho con todo[n]lo del entrenamiento y tal.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42851 0 0]Dale un respiro.[n]Hace todo lo que est茨 en su mano.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43252 0 0]Hace como que conf胤a en s胤 misma[n]a pesar de que no puede hacerlo.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_506_05_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43202 0 0]Ya podr胤a dejar de ser[n]una alumna tan ejemplar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_06_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43002 0 0]Seguro que esta vez[n]no le sali吋 bien, eso es todo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_07_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43152 0 0]Deja de odiar a las chicas[n]solo porque griten.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_506_08_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42602 0 0]Pero 夷se le da bien la gimnasia?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_601_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42104 0 0]Al parecer, la tal Yoshizawa es[n]buen胤sima en gimnasia.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_601_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42754 0 0]La gente espera grandes cosas[n]de Yoshizawa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_601_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42204 0 0]Se comenta que ser茨[n]la siguiente medallista.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_601_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42154 0 0]斡Sac吋 unas notazas en secundaria![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_601_05_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42954 0 0]Hasta el director espera[n]que le vaya bien.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_602_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42100 0 0]He hablado con el doctor Maruki[n]y ahora me siento mucho mejor.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_602_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42753 0 0]El doctor Maruki es supermajo y se[n]le puede hablar de cualquier cosa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_602_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42353 0 0]Yo tambi姻n ir姻 pronto[n]a la enfermer胤a.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_602_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42200 0 0]T胤o, vamos a la enfermer胤a,[n]que nos dan aperitivos gratis.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_501_01_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43252 0 0]Es que no puedo ni hablar con ella.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_501_02_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42350 0 0]Todo el mundo espera[n]que a esa gimnasta le vaya bien.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_501_03_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42200 0 0]He o胤do que hay una gimnasta[n]muy buena en primero.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_501_04_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43100 0 0]Qu姻 piernecitas tiene...[n]Supongo que ser茨[n]cosa de la gimnasia.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_501_05_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42954 0 0]Tiene un cuerpazo. 夷Qu姻 dieta[n]crees que har茨 para estar as胤?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_501_06_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43105 0 0]Ella tambi姻n estaba. Qu姻 mojigata...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_501_07_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42605 0 0]Ser胤a divertido que se pusiera[n]a hacer gimnasia mientras limpia.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_501_08_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43201 0 0]Ojal茨 pudiera cambiar[n]la fecha de mis ex茨menes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_501_09_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43002 0 0]夷No ser胤a obvio si trabajaran[n]duro todos los d胤as?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_501_10_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43100 0 0]Flipo con que vaya a primero.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_501_11_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42950 0 0]Es estudiante honor胤fica[n]por ser deportista, 夷no?[n]Tiene que ser buen胤sima.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_501_12_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43354 0 0]A los profesores les va a encantar[n]esa alumna nueva.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_501_13_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42604 0 0]Me pasar姻 por la clase de primero.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_501_14_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43352 0 0]No se parece en nada al delincuente[n]ese que va a segundo.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_501_15_ [Mujer con c茨mara]]
[s][vp 9 2 65535 42800 0 0]Tiene hasta entrenadora[n]y todo, 夷no? Jol胤n...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_501_16_ [Mujer con c茨mara]]
[s][vp 9 2 65535 43101 0 0]夷Eh? 夷De verdad?[n]夷Qu姻 mosca le ha picado?[n][f 1 2 180][e]

[msg MSG_TAKEISHI_001_0_0 [Takeishi]]
[s][vp 8 2 1 0 780 0]Oh, [f 4 1]...[n][w][e]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]夷No te lo ha dicho Sakamoto?[n]Va a retomar el atletismo.[n][w][e]

[msg MSG_TAKEISHI_002_0_0 [Nakaoka]]
[s][f 4 23 1 781 3 10 0 10][vp 8 2 1 0 781 0]斡Est茨 pirado! Parece que va[n]a tener que hacer rehabilitaci吋n[n]cuando se haya instalado.[n][w][e]
[s][vp 8 2 1 0 781 0]Pero me alegra volver a correr[n]con 姻l.[n][w][e]

[msg MSG_TAKEISHI_003_0_0 [Takeishi]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]Haremos cuanto est姻 en nuestras[n]manos para ayudarlo en su regreso.[n][w][e]
[s][vp 8 2 1 0 780 0]El t胤o es un corredor alucinante.[n]Ojal茨 podamos echarle un cable.[n][w][e]

[msg MSG_TAKEISHI_004_0_0 [Nakaoka]]
[s][f 4 23 1 781 3 10 0 10][vp 8 2 1 0 781 0]Ya, pero no te preocupes por 姻l.[n][w][e]
[s][vp 8 2 1 0 781 0]Incluso si acabas regresando[n]a tu ciudad, seguir茨 teniendo gente[n]que se preocupa por 姻l.[n][w][e]

[msg MSG_TAKEISHI_005_0_0 [Takeishi]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]Costar茨 acostumbrarse,[n]pero que eso no te eche para atr茨s.[n][w][e]

[msg MSG_TAKEISHI_END_0 [Nakaoka]]
[s][f 4 23 1 781 3 10 0 10][vp 8 2 1 0 781 0]Estar姻 por aqu胤 para asegurarme[n]de que todo le va bien.[n]No te comas mucho el tarro.[n][w][e]

[msg MSG_TAKEISHI_END_1 [Takeishi]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]S姻 que las cosas pueden[n]complicarse, pero cuenta conmigo.[n][w][e]

[msg MSG_TAKEISHI_001_0_1 [Takeishi]]
[s][vp 8 2 1 0 780 0][f 4 1]...[n][w][e]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]He hablado con Sakamoto.[n]Te vuelves a casa, 夷no?[n][w][e]

[msg MSG_TAKEISHI_002_0_1 [Nakaoka]]
[s][f 4 23 1 781 3 10 0 10][vp 8 2 1 0 781 0]Oye..., siento haberte metido en la[n]movida del equipo de atletismo.[n][w][e]
[s][vp 8 2 1 0 781 0]Nunca te he dado las gracias[n]por todo, as胤 que me alegro[n]de haberte pillado ahora.[n][w][e]

[msg MSG_TAKEISHI_003_0_1 [Takeishi]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]S姻 que las cosas pueden[n]complicarse, pero cuenta conmigo.[n][w][e]

[msg MSG_TAKEISHI_004_0_1 [Nakaoka]]
[s][f 4 23 1 781 3 10 0 10][vp 8 2 1 0 781 0]Si las cosas no salen bien, siempre[n]podr茨s volver. 斡El equipo[n]de atletismo es tu casa![n][w][e]

[msg MSG_TAKEISHI_005_0_1 [Takeishi]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]Bueno, 斡cu胤date![n][w][e]

[msg MSG_TAKEISHI_END_0_1 [Takeishi]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]Bueno, 斡cu胤date![n][w][e]

[msg MSG_TAKEISHI_END_1_1 [Nakaoka]]
[s][f 4 23 1 781 3 10 0 10][vp 8 2 1 0 781 0]Si las cosas no salen bien, siempre[n]podr茨s volver. 斡El equipo[n]de atletismo es tu casa![n][w][e]

