[msg DUMMY_01]
[s]ダミー[n][w][e]

[msg D159_MOB_VOICE_GUY01_mes [Pasajero]]
[s][vp 8 1 65535 5002 0 0]斡Somos los elegidos![n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY01_mes_2 [Pasajero]]
[s][vp 8 1 65535 5003 0 0]No hay duda alguna.[n]斡Somos unos triunfadores![n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY01_mes_3 [Pasajero]]
[s][vp 8 1 65535 5004 0 0]斡Mua, ja, ja, ja![n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY01_mes_4 [Pasajero]]
[s][vp 8 1 65535 5005 0 0]Esto es genial.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY01_mes_5 [Pasajero]]
[s][vp 8 1 65535 5006 0 0]No hay duda alguna.[n]斡Somos unos triunfadores![n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY01_mes_6 [Pasajero]]
[s][vp 8 1 65535 5007 0 0]夷D吋nde est茨 el alcohol?[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY01_mes_7 [Pasajero]]
[s][vp 8 1 65535 5008 0 0]Un sitio de post胤n como este[n]es digno de gente[n]de nuestro estatus.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY01_mes_8 [Pasajero]]
[s][vp 8 1 65535 5009 0 0]夷Por qu姻 胤bamos nosotros[n]a trabajar como hormigas?[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY02_mes [Pasajero]]
[s][vp 8 1 65535 5102 0 0]斡Somos los elegidos![n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY02_mes_2 [Pasajero]]
[s][vp 8 1 65535 5103 0 0]No hay duda alguna.[n]斡Somos unos triunfadores![n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY02_mes_3 [Pasajero]]
[s][vp 8 1 65535 5104 0 0]斡Mua, ja, ja, ja![n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY02_mes_4 [Pasajero]]
[s][vp 8 1 65535 5105 0 0]Esto es genial.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY02_mes_5 [Pasajero]]
[s][vp 8 1 65535 5106 0 0]No hay duda alguna.[n]斡Somos unos triunfadores![n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY02_mes_6 [Pasajero]]
[s][vp 8 1 65535 5107 0 0]夷D吋nde est茨 el alcohol?[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY02_mes_7 [Pasajero]]
[s][vp 8 1 65535 5108 0 0]Un sitio de post胤n como este[n]es digno de gente[n]de nuestro estatus.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_GUY02_mes_8 [Pasajero]]
[s][vp 8 1 65535 5109 0 0]夷Por qu姻 胤bamos nosotros[n]a trabajar como hormigas?[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY01_me [Pasajera]]
[s][vp 8 1 65535 5202 0 0]Hala, qu姻 u隠as m茨s chulas tienes.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY01_me_2 [Pasajera]]
[s][vp 8 1 65535 5203 0 0]Qu姻 vistas tan magn胤ficas.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY01_me_3 [Pasajera]]
[s][vp 8 1 65535 5204 0 0]斡Ohhh, jo, jo, jo![n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY01_me_4 [Pasajera]]
[s][vp 8 1 65535 5205 0 0]Uf, he vuelto a empezar a beber[n]sin darme cuenta siquiera.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY01_me_5 [Pasajera]]
[s][vp 8 1 65535 5206 0 0]Otra copa de vino, por favor.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY01_me_6 [Pasajera]]
[s][vp 8 1 65535 5207 0 0]No soporto a la plebe.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY01_me_7 [Pasajera]]
[s][vp 8 1 65535 5208 0 0]Esta fiesta es espl姻ndida.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY01_me_8 [Pasajera]]
[s][vp 8 1 65535 5209 0 0]No tenemos nada que ver[n]con esa plebe.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY02_me [Pasajera]]
[s][vp 8 1 65535 5302 0 0]Hala, qu姻 u隠as m茨s chulas tienes.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY02_me_2 [Pasajera]]
[s][vp 8 1 65535 5303 0 0]Qu姻 vistas tan magn胤ficas.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY02_me_3 [Pasajera]]
[s][vp 8 1 65535 5304 0 0]斡Ohhh, jo, jo, jo![n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY02_me_4 [Pasajera]]
[s][vp 8 1 65535 5305 0 0]Uf, he vuelto a empezar a beber[n]sin darme cuenta siquiera.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY02_me_5 [Pasajera]]
[s][vp 8 1 65535 5306 0 0]Otra copa de vino, por favor.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY02_me_6 [Pasajera]]
[s][vp 8 1 65535 5307 0 0]No soporto a la plebe.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY02_me_7 [Pasajera]]
[s][vp 8 1 65535 5308 0 0]Esta fiesta es espl姻ndida.[n][f 1 6 65534][e]

[msg D159_MOB_VOICE_LADY02_me_8 [Pasajera]]
[s][vp 8 1 65535 5309 0 0]No tenemos nada que ver[n]con esa plebe.[n][f 1 6 65534][e]

