[msg COUNTER_ANNOUNCE_GREETIN]
[s]ダミー[n][w][e]

[msg D153_MOB_VOICE_TV_mes01 [Voz]]
[s][vp 8 1 65535 5000 0 0]Gracias por la visita.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes02 [Voz]]
[s][vp 8 1 65535 5001 0 0]Ahora mismo tenemos una exposici吋n[n]de los trabajos del gran Madarame.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes03 [Voz]]
[s][vp 8 1 65535 5002 0 0]Madarame siempre estuvo[n]a la vanguardia del universo[n]art胤stico de Jap吋n.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes04 [Voz]]
[s][vp 8 1 65535 5003 0 0]La exposici吋n trata de expresar[n]y compartir el atractivo[n]de sus obras.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes05 [Voz]]
[s][vp 8 1 65535 5004 0 0]Sus singulares ideas, totalmente[n]libres de preconcepciones...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes06 [Voz]]
[s][vp 8 1 65535 5005 0 0]...abren un mundo de posibilidades[n]en el arte del Nihonga.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes07 [Voz]]
[s][vp 8 1 65535 5006 0 0]No solo ha sido pionero en nuevos[n]enfoques del mundo art胤stico...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes08 [Voz]]
[s][vp 8 1 65535 5007 0 0]...tambi姻n ha sido mentor de la[n]siguiente generaci吋n de artistas.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes09 [Voz]]
[s][vp 8 1 65535 5008 0 0]Es una figura esencial del arte[n]contempor茨neo japon姻s.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_TV_mes10 [Voz]]
[s][vp 8 1 65535 5009 0 0]El mundo tiene los ojos puestos[n]en 姻l. 夷C吋mo va a revolucionar[n]el arte la pr吋xima vez?[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes [Anuncio]]
[s][vp 8 1 65535 5100 0 0]Esta obra, pintada con esmero[n]dando delicadas pinceladas...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_2 [Anuncio]]
[s][vp 8 1 65535 5101 0 0]...presenta una coloraci吋n[n]profunda e intrincada.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_3 [Anuncio]]
[s][vp 8 1 65535 5102 0 0]Las caracter胤sticas del modelo[n]se reflejan con maestr胤a.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_4 [Anuncio]]
[s][vp 8 1 65535 5103 0 0]Es casi como si estuviera delante.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_5 [Anuncio]]
[s][vp 8 1 65535 5104 0 0]No solo tiene un porte que impone...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_6 [Anuncio]]
[s][vp 8 1 65535 5105 0 0]...sino que adem茨s cuenta con un aire[n]misterioso y 雨nico que...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_7 [Anuncio]]
[s][vp 8 1 65535 5106 0 0]...atrae a cualquiera[n]que lo contemple.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_8 [Anuncio]]
[s][vp 8 1 65535 5107 0 0]Tiene una presencia sin igual...[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_9 [Anuncio]]
[s][vp 8 1 65535 5108 0 0]...que te hace sentir que podr胤as[n]pasarte la vida mir茨ndolo.[n][f 1 6 65534][e]

[msg D153_MOB_VOICE_GUIDE_mes_10 [Anuncio]]
[s][vp 8 1 65535 5109 0 0]No ser胤a una exageraci吋n decir que[n]este cuadro es la perfecci吋n.[n][f 1 6 65534][e]

