[msg TEST_MES]
[s]Prueba[n][w][e]

[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg SAFE_MES_RYUJI_01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54215 65535 0]No entiendo por qu姻 la gente[n]querr胤a estar en una celda.[n][w][e]

[msg SAFE_MES_RYUJI_02 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7028 65535 0]S胤, ser胤a mejor si no tuvi姻ramos[n]que preocuparnos de nada, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como... No s姻 c吋mo decirlo,[n]pero huir de los pensamientos[n]no est茨 bien, 夷verdad?[n][w][e]

[msg SAFE_MES_RYUJI_03 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Hay m茨s guardias aqu胤[n]que en la entrada. Preparaos.[n][w][e]

[msg SAFE_MES_RYUJI_04 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7172 65535 0]Mona dice que el tesoro anda cerca.[n]斡A por 姻l![n][w][e]

[msg SAFE_MES_MORGANA_01 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1112 65535 0]夷Estaba intentando llegar[n]a esta prisi吋n? Uf, no lo recuerdo...[n][w][e]

[msg SAFE_MES_MORGANA_02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1044 65535 0]No estoy seguro del todo, pero creo[n]que empiezo a recordar cosas.[n][w][e]

[msg SAFE_MES_MORGANA_03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53112 65535 0]S胤. Yo estaba en cuarentena y...[n]夷qui姻n era? 夷Qui姻n me cre吋?[n][w][e]

[msg SAFE_MES_MORGANA_04 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Oye, Joker,[n]cuando esto haya terminado...[n][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Je, no. Es muy pronto para pensar[n]en eso. 斡Vamos, Joker![n][w][e]

[msg SAFE_MES_ANN_01 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6162 65535 0]Las venas aquellas de Mementos[n]se juntan aqu胤, en la prisi吋n...[n][w][e]

[msg SAFE_MES_ANN_02 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6190 65535 0]La 或libertad de no tomar[n]decisiones位. 夷Se le puede llamar[n]a eso ser libre?[n][w][e]

[msg SAFE_MES_ANN_03 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6058 65535 0]A saber qu姻 es eso de la[n]cuarentena. 夷Y qu姻 clase de persona[n]ser茨 ese 或recluso m茨s peligroso位?[n][w][e]

[msg SAFE_MES_ANN_04 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6166 65535 0]夷No es el tesoro de uno,[n]sino el de todos?[n]Me pregunto c吋mo ser茨.[n][w][e]

[msg SAFE_MES_YUSUKE_01 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]Y pensar que existe una prisi吋n[n]subconsciente de la conciencia[n]de las masas en Mementos...[n][w][e]

[msg SAFE_MES_YUSUKE_02 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4047 65535 0]Para dejar de pensar y preocuparse...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo tambi姻n iba de ese palo,[n]as胤 que lo entiendo, pero...[n][w][e]

[msg SAFE_MES_YUSUKE_03 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4156 65535 0]Las sombras que hacen guardia[n]son m茨s fuertes que antes.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deber胤amos apresurarnos hacia[n]lo m茨s profundo, pero tambi姻n ser胤a[n]buena idea salir y prepararnos.[n][w][e]

[msg SAFE_MES_YUSUKE_04 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4158 65535 0]Gracias a vosotros, he aprendido[n]que huir de los problemas[n]es un error.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos, Joker. El tesoro est茨 cerca.[n][w][e]

[msg SAFE_MES_MAKOTO_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2128 65535 0]Esas baldosas brillantes[n]son un fastidio.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No aparecen enemigos[n]si metemos la pata,[n]as胤 que sin prisa.[n][w][e]

[msg SAFE_MES_MAKOTO_02 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53339 65535 0]Hemos avanzado mucho.[n]夷Desde cu茨ndo existir茨 este sitio?[n][w][e]

[msg SAFE_MES_MAKOTO_03 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2113 65535 0]夷Habr茨n creado a Mona para que[n]nos gu胤e? Hay tantas preguntas[n]sin respuesta...[n][w][e]

[msg SAFE_MES_MAKOTO_04 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2157 65535 0]Si estamos cerca del tesoro, es que[n]casi hemos llegado a la parte[n]m茨s profunda de Mementos.[n][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No s姻 lo que nos espera,[n]pero sabemos lo que hay que hacer.[n][w][e]

[msg SAFE_MES_HARU_01 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3158 65535 0]La zona m茨s profunda de Mementos...[n]A saber por qu姻 Mona[n]quiere llegar hasta all胤.[n][w][e]

[msg SAFE_MES_HARU_02 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3198 65535 0]Si mi padre viviera, 夷ser胤a...?[n][w][e]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perdona. Olv胤dalo, por favor.[n]Hagamos un descanso y continuemos.[n][w][e]

[msg SAFE_MES_HARU_03 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3111 65535 0]夷C吋mo ser茨 vivir en cuarentena?[n]Seg雨n Mona, 姻l naci吋 as胤...[n][w][e]

[msg SAFE_MES_HARU_04 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3019 65535 0]Espero que Mona recuerde qui姻n es[n]en cuanto pisemos[n]las profundidades de Mementos.[n][w][e]

[msg SAFE_MES_HUTABA_01 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9182 65535 0]Entiendo que no quieras salir, pero[n]de ah胤 a encerrarse en una celda...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que habr茨 que seguir[n]avanzando, 夷no, Joker?[n][w][e]

[msg SAFE_MES_HUTABA_02 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9171 65535 0]Abandonar cualquier tipo[n]de vida y vivir encerrado...[n]Me recuerda a m胤.[n][w][e]

[msg SAFE_MES_HUTABA_03 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]夷En cuarentena? 夷Qu姻 le ocurri吋[n]a Mona en el pasado?[n][w][e]

[msg SAFE_MES_HUTABA_04 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9190 65535 0]Da igual lo que le ocurriera a Mona[n]en el pasado. Es nuestro amigo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Verdad, Joker?[n][w][e]

