[sel YESNO_SEL top]
[s]はい[e]
[s]いいえ[e]

[msg NPC_GREETING_MSG]
[s]挨拶[n][w][e]

[msg NPC_01]
[s]会話[n][w][e]

[msg MSG_MIRIOTA_001_01_0 [Fan militar]]
[s][vp 8 2 1 0 10 0]夷T雨 tambi姻n eres un fan[n]de esta tienda?[n][w][e]
[s][vp 8 2 1 0 10 0]Las armas personalizadas de este[n]sitio son geniales. Me quedo[n]prendado solo con verlas.[n][w][e]

[msg MSG_MIRIOTA_001_INFO_0 [Fan militar]]
[s][vp 8 2 1 0 10 0]郁ltimamente viene gente[n]con pinta de ser detective[n]a la tienda.[n][w][e]
[s][vp 8 2 1 0 10 0]Creo que muchos clientes no quieren[n]encargar personalizaciones para[n]que los polis no se den cuenta.[n][w][e]
[s][vp 8 2 1 0 10 0]A m胤 me da igual.[n]No estoy haciendo nada malo.[n][w][e]

[msg MSG_MIRIOTA_001_INFO_MOR [Morgana]]
[s]夷Crees que podr胤as pedirles[n]informaci吋n?[n][w][e]

[msg MSG_MIRIOTA_0425 [Fan militar]]
[s][vp 8 2 1 0 10 0]T胤o, 夷has visto la [clr 4]Makaranov[clr 27][n]que va a salir pronto?[n][w][e]
[s][vp 8 2 1 0 10 0]Entre las autom茨ticas,[n]es una gran elecci吋n.[n][w][e]
[s][vp 8 2 1 0 10 0]斡Qu姻 ganas de probar[n]la [clr 4]Makaranov[clr 27]![n]Tener paciencia es dif胤cil.[n][w][e]

[msg MSG_MIRIOTA_0518 [Fan militar]]
[s][vp 8 2 1 0 10 0]夷Te has fijado en la m茨quina[n]de c茨psulas de la entrada?[n]La que tiene raciones del ej姻rcito.[n][w][e]
[s][vp 8 2 1 0 10 0]Dicen que est茨n asquerosas.[n][w][e]
[s][vp 8 2 1 0 10 0]Y no solo por el sabor,[n]dan asco en muchos sentidos.[n][w][e]
[s][vp 8 2 1 0 10 0]Son muy caras y, posiblemente,[n]peligrosas, pero[n]pru姻balas si tienes curiosidad.[n][w][e]

[msg MSG_MIRIOTA_0620 [Fan militar]]
[s][vp 8 2 1 0 10 0]Qu姻 ganas tengo de que salga[n]el modelo nuevo en julio.[n][w][e]
[s][vp 8 2 1 0 10 0]夷Te has enterado?[n]Se llama [clr 4]Tar茨ntula[clr 27].[n][w][e]
[s][vp 8 2 1 0 10 0]La gente est茨 muy emocionada, pero[n]el mecanismo de fuego r茨pido[n]era complejo para una r姻plica.[n][w][e]
[s][vp 8 2 1 0 10 0]斡Hasta ahora! 斡Por fin han[n]hecho una! 斡Llevo mucho[n]tiempo esper茨ndola![n][w][e]
[s][vp 8 2 1 0 10 0]Tanto, 斡que hasta[n]intent姻 hacerla yo! Pero no,[n]no soy un manitas, precisamente.[n][w][e]
[s][vp 8 2 1 0 10 0]斡Qu姻 ganas de tener[n]mi propia [clr 4]Tar茨ntula[clr 27]![n]Tener paciencia es dif胤cil.[n][w][e]

[msg MSG_MIRIOTA_0725 [Fan militar]]
[s][vp 8 2 1 0 10 0]斡La nueva r姻plica de septiembre[n]va a ser incre胤ble! Es un rev吋lver[n]que se llama [clr 4]Indomable[clr 27].[n][w][e]
[s][vp 8 2 1 0 10 0]Molar胤a que los Ladrones[n]Fantasma usaran armas[n]con tanto estilo como esta.[n][w][e]
[s][vp 8 2 1 0 10 0]Pero 夷usan armas siquiera?[n]No tengo ni idea.[n][w][e]
[s][vp 8 2 1 0 10 0]斡Qu姻 ganas de probar el ca隠吋n[n]del [clr 4]Indomable[clr 27]![n]Odio tener que esperar.[n][w][e]

[msg MSG_MIRIOTA_0831 [Fan militar]]
[s][vp 8 2 1 0 10 0]斡T胤o, qu姻 ganas de que saquen[n]la [clr 4]Furia[clr 27] en octubre![n][w][e]
[s][vp 8 2 1 0 10 0]斡Es una r姻plica reeditada![n]斡No duermo de la emoci吋n![n]Soy adicto a las r姻plicas.[n][w][e]
[s][vp 8 2 1 0 10 0]Ojal茨 esos Ladrones Fantasma[n]de los que todo el mundo habla[n]robaran esta adicci吋n que tengo.[n][w][e]
[s][vp 8 2 1 0 10 0]斡Me apetece mucho practicar[n]para desenfundar r茨pido con ella![n]Odio tener que esperar.[n][w][e]

[msg MSG_MIRIOTA_0921 [Fan militar]]
[s][vp 8 2 1 0 10 0]斡T胤o, estoy loco por la [clr 4]Hizutsu[clr 27][n]que sale en noviembre![n][w][e]
[s][vp 8 2 1 0 10 0]La anunciaron hace ya tiempo,[n]pero se ha retrasado[n]por alguna movida.[n][w][e]
[s][vp 8 2 1 0 10 0]Pens姻 que los Ladrones[n]Fantasma robaron los planos[n]o algo por el estilo.[n][w][e]
[s][vp 8 2 1 0 10 0]Y cuando estaba ray茨ndome...[n][w][e]
[s][vp 8 2 1 0 10 0]斡Van y anuncian la fecha de[n]lanzamiento! Esa gente sabe c吋mo[n]tenernos en vilo.[n][w][e]
[s][vp 8 2 1 0 10 0]斡Qu姻 ganas tengo[n]de dormir con ella![n]Odio tener que esperar.[n][w][e]

[msg MSG_MIRIOTA_1026 [Fan militar]]
[s][vp 8 2 1 0 10 0]Tengo curiosidad por la [clr 4]D.E.Pistola[clr 27][n]que sale a finales de a隠o.[n][w][e]
[s][vp 8 2 1 0 10 0]Parece simple, pero puede que[n]tenga partes m茨s detalladas.[n][w][e]
[s][vp 8 2 1 0 10 0]斡Qu姻 ganas de verme en el espejo[n]con la [clr 4]D.E.Pistola[clr 27]![n]Odio tener que esperar.[n][w][e]

[msg MSG_MIRIOTA_1123 [Fan militar]]
[s][vp 8 2 1 0 10 0]T胤o, estoy superinteresado en[n][clr 4][var 5][clr 27]que sale a final de a隠o.[n][w][e]
[s][vp 8 2 1 0 10 0]夷Qu姻? Es una protecci吋n.[n]En los tiempos que corren,[n]la necesito para sobrevivir.[n][w][e]
[s][vp 8 2 1 0 10 0]斡Qu姻 ganas de mimar a mi[n][clr 4][var 5][clr 27]![n]Odio tener que esperar.[n][w][e]

[msg MSG_MIRIOTA_1219 [Fan militar]]
[s][vp 8 2 1 0 10 0]Tengo curiosidad por la [clr 4]Milkor[clr 27][n]que sale a finales de a隠o.[n][w][e]
[s][vp 8 2 1 0 10 0]Siempre me gasto mucho dinero[n]por esas fechas. 斡Qu姻 ganas[n]de que llegue fin de a隠o![n][w][e]
[s][vp 8 2 1 0 10 0]Odio tener que esperar,[n]pero el autocontrol es muy[n]importante en A隠o Nuevo.[n][w][e]

[msg MSG_MIRIOTA_0101 [Fan militar]]
[s][vp 8 2 1 0 10 0]斡T胤o, no me canso de recomendar[n]la [clr 4]chica amarilla[clr 27][n]que sali吋 a principios de a隠o![n][w][e]
[s][vp 8 2 1 0 10 0]斡Mola mucho c吋mo se recarga![n][w][e]
[s][vp 8 2 1 0 10 0]No me puedo creer que vaya[n]a tener ese modelo.[n]La vida es maravillosa.[n][w][e]

[msg MSG_KAORU_001_0_0 [Kaoru]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]斡[f 4 1]![n]斡Me alegro de verte![n][w][e]
[s][vp 8 2 1 0 780 0]Mi padre me ha dicho que es[n]tu 雨ltimo d胤a aqu胤, as胤 que[n]ten胤a que hablar contigo.[n][w][e]

[sel SEL_KAORU_002_0_0 top]
[s]Gracias.[e]
[s]C茨lmate.[e]
[s]夷Qu姻 pasa?[e]

[msg MSG_KAORU_003_0_0 [Kaoru]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]斡No, yo deber胤a darte las gracias![n]斡Ten胤a que dec胤rtelo en persona![n][w][e]

[msg MSG_KAORU_003_1_0 [Kaoru]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]Ay, lo siento.[n]斡Ten胤a que dec胤rtelo en persona![n][w][e]

[msg MSG_KAORU_004_0_0 [Kaoru]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]斡Voy a ir al Shujin[n]a partir de primavera![n][w][e]
[s][vp 8 2 1 0 780 0]Dije que admiraba a los Ladrones[n]Fantasma, pero creo que t雨 tambi姻n[n]eres alucinante, [f 4 1].[n][w][e]
[s][vp 8 2 1 0 780 0]Quiero ser como t雨. Y pens姻 que[n]pod胤a empezar yendo[n]al mismo instituto.[n][w][e]

[sel SEL_KAORU_005_0_0 top]
[s]Buena suerte.[e]
[s]Anda, eres mi versi吋n j雨nior.[e]

[msg MSG_KAORU_006_0_0 [Kaoru]]
[s][f 4 23 1 780 3 10 0 10][vp 8 2 1 0 780 0]Gracias. 斡Ay, no! 斡Se me olvid吋[n]que hoy me tocaba a m胤[n]preparar la cena![n][w][e]
[s][vp 8 2 1 0 780 0]Lo siento, tengo que irme.[n]Tengo que pillar una oferta[n]antes de que acabe. 斡Adi吋s![n][w][e]

