[msg MSG_MORGANA_C0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]La gente de la ciudad es bastante[n]horrible, pero cuesta encontrar[n]a alguien que tenga un Palacio.[n][w][e]

[msg MSG_REQ_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Entonces quieres fabricar[n]herramientas de infiltraci吋n, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]斡Pues re雨ne los [clr 2]materiales[clr 27][n]en el Metaverso y yo te ayudo[n]a hacerlas![n][w][e]

[msg MSG_KAWAKAMI_00 [Kawakami]]
[s][bup 0 109 600 0 0][f 4 10 65535 0 0][vp 8 2 1 0 10 0]No me hables mientras estoy[n]trabajando. No querr茨s[n]que meta la pata, 夷no?[n][w][e]

[msg MSG_YUUSUKE_0611_001_00 [Yusuke]]
[s][f 4 23 1 65535 14 0 13 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4003 65535 0]夷No vas a irte a dormir a雨n?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Yo estoy bien aqu胤.[n]En ocasiones duermo en mi estudio.[n]Esto es un lujo en comparaci吋n.[n][w][e]

[msg MSG_YUUSUKE_0611_002_00 [Yusuke]]
[s][f 4 23 1 65535 14 0 13 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4129 65535 0]Me gusta ir a un ba隠o[n]p雨blico cada cierto tiempo.[n]El agua caliente es muy relajante.[n][w][e]

[msg MSG_FUTABA_1026_000_00 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9193 65535 0]Es culpa m胤a...[n][w][e]
[s][f 4 23 1 65535 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Todo esto ha pasado[n]por haberme quedado el aviso.[n][w][e]
[s][f 4 10 65535 0 0]...[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9178 65535 0]Es tard胤simo...[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_2 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 9176 65535 0]夷Sojiro sigue despierto?[n][w][e]
[s][f 4 10 65535 0 0]Es un poco raro...[n][w][e]

[sel SEL_BED_MORGANA_NIGHT_10 top]
[s]Ve a casa para que no se preocupe.[e]
[s]Puedes dormir en el sof茨.[e]

[msg MSG_BED_MORGANA_NIGHT_10_3 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1029 65535 0]夷No deber胤as dormir t雨 en el sof茨[n]para que Futaba pueda[n]descansar en la cama?[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_4 [Futaba]]
[s][bup 0 8 3 65535 0]...[n][w][e]

[msg MSG_BED_MORGANA_NIGHT_10_5 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9195 65535 0][f 4 23 1 65535 4 10 0 0]Me voy a casa.[n][w][e]
[s][f 4 10 65535 0 0]Buenas noches.[n][w][e]

[msg MSG_FUTABA_1121_000_00 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]夷Te acuerdas de cuando te pinch姻[n]el m吋vil durante la excursi吋n?[n]斡Al final nos vino bien y todo![n][w][e]

[sel SEL_FUTABA_1121_001_00 top]
[s]夷Y eso?[e]
[s]No me interesa.[e]

[msg MSG_FUTABA_1121_000_01 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Oh, 夷quieres volver a o胤rlo?[n][w][e]

[sel SEL_FUTABA_1121_001_01 top]
[s]Claro.[e]
[s]Ahora no.[e]

[msg MSG_FUTABA_1121_002_00 [Futaba]]
[s][f 4 23 1 65535 4 0 0 0][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]A ver, 夷te acuerdas de cuando[n]le pinch姻 el m吋vil a Akechi?[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]As胤 pude ver la informaci吋n GPS[n]de dos m吋viles, el tuyo y el suyo.[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 0 0 0][vp 8 0 1 5 65535 0]斡Para saber el momento justo en que[n]Sae Niijima, que ten胤a tu m吋vil,[n]se encontr吋 con Akechi![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Entonces vi mi oportunidad y 斡bip!,[n]envi姻 la se隠al para activar[n]el Navegador del Metaverso.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]Pero tambi姻n pod胤a pasar[n]que se cruzaran[n]sin mediar palabra.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]斡Por eso necesitaba que le dijeras a Sae[n]que le ense隠ara el m吋vil a Akechi![n][w][e]

[msg MSG_FUTABA_1121_003_00 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]Este plan me sorprende cada vez[n]que lo oigo, da igual cu茨ntas sean.[n][w][e]

[msg MSG_FUTABA_1121_004_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]Aun as胤, no pod胤a hackear el Navegador sin m茨s.[n]Al fin y al cabo, es una aplicaci吋n misteriosa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]Pero 夷sabes esa funci吋n[n]de marcadores que tiene?[n]Pues solo hay que pulsar el bot吋n.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Hacer que el m吋vil pensara que el bot吋n[n]lo estaba pulsando 姻l era f茨cil.[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Mue, je, je, je... Nada mal, 斡夷eh?![n][w][e]

[msg MSG_FUTABA_1121_002_01 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]夷C吋mooo? Vaya muermazo.[n][w][e]

[msg MSG_FUTABA_1121_003_01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 1 15 65535 0][f 4 2] est茨 cansado. Mejor[n]cu姻ntaselo en otro momento, 夷vale?[n][w][e]

[msg MSG_FUTABA_1121_100_00 [Futaba]]
[s][f 4 23 1 65535 4 0 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 16 65535 0]Puede que no lo parezca,[n]pero todos los dem茨s tambi姻n[n]estaban arriesgando sus vidas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]Aunque no cabe duda de que t雨[n]eras el que m茨s te la jugabas.[n]Te acabaron arrestando, vaya.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 18 65535 0]Pero al parecer, con todos[n]los f茨rmacos y dem茨s, te hab胤as[n]olvidado de los detalles del plan.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 19 65535 0]夷Quieres que te explique c吋mo pas吋 todo?[n]Igual va para largo.[n][w][e]

[sel SEL_FUTABA_1121_101_00 top]
[s]Claro.[e]
[s]Ahora no.[e]

[msg MSG_FUTABA_1121_102_00 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 20 65535 0]Bueno, como al resto no nos pillaron,[n]hab胤a que hacer algo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 21 65535 0]Ten胤amos que fingir que no[n]quer胤amos que te arrestaran...[n]y que lo del suicidio nos sorprendi吋.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 22 65535 0]Vamos, hacer como si no supi姻ramos[n]nada en todo momento.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 23 65535 0]El enemigo sabe qui姻nes somos,[n]as胤 que no pod胤amos bajar la guardia[n]aunque t雨 no estuvieras.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 24 65535 0]Si hubieran descubierto nuestro plan,[n]te habr胤an matado[n]de inmediato.[n][w][e]

[msg MSG_FUTABA_1121_103_00 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 25 65535 0]夷Quieres o胤r m茨s?[n][w][e]

[sel SEL_FUTABA_1121_104_00 top]
[s]S胤, claro.[e]
[s]Ya est茨 bien de momento.[e]

[msg MSG_FUTABA_1121_105_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 26 65535 0]Tambi姻n nos cost吋 dar con la forma[n]de traer a Sae y Akechi[n]de vuelta del Metaverso.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 27 65535 0]Para regresar a la realidad,[n]hay que volver al punto[n]desde donde entraste al Metaverso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 28 65535 0]As胤 que Sae y Akechi ten胤an que pasar[n]por donde se activ吋 el Navegador.[n]Vamos, donde se vieron.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 29 65535 0]Akechi volver胤a por el mismo camino[n]despu姻s del asesinato.[n]El problema era Sae.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 30 65535 0]Ten胤amos que pararla un momento[n]antes de que volviera[n]a la sala de interrogatorios.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 31 65535 0]Pero no se puede enviar nada a un m吋vil[n]dentro de un Palacio. Hab胤a que programar[n]los mensajes de antemano.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 32 65535 0]As胤, parec胤a que los mensajes[n]estaban llegando[n]justo en ese momento.[n][w][e]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 33 65535 0]Esa parte se decidi吋 un poco[n]a 雨ltima hora, as胤 que me qued姻[n]toda la noche prepar茨ndola.[n][w][e]

[msg MSG_FUTABA_1121_106_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 34 65535 0]斡No puedo parar![n]夷Quieres o胤r m茨s?[n][w][e]

[sel SEL_FUTABA_1121_107_00 top]
[s]S胤, por favor.[e]
[s]Creo que ya est茨 bien.[e]

[msg MSG_FUTABA_1121_108_00 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 35 65535 0]A ver, m茨s cosas complicadas...[n][w][e]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 0 1 36 65535 0]斡Ah, s胤! 斡Entretener a Akechi![n]Eso s胤 que fue dif胤cil.[n][w][e]

[msg MSG_FUTABA_1121_109_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 37 65535 0]Ahh, pero no al Akechi de verdad,[n]claro. Aunque pudi姻ramos hacer eso,[n]el plan se habr胤a ido al garete.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 38 65535 0]A quien ten胤amos que entretener[n]era al Akechi cognitivo de Sae.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 39 65535 0]Esta parte era complicad胤sima.[n]S姻 que est茨s cansado.[n]夷Quieres o胤r todo esto ahora?[n][w][e]

[sel SEL_FUTABA_1121_110_00 top]
[s]Claro.[e]
[s]Mejor no.[e]

[msg MSG_FUTABA_1121_111_00 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 40 65535 0]Pues hab胤a que atraer a Akechi al[n]Palacio de Sae y hacer que matara[n]al [f 4 2] cognitivo.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 41 65535 0]Pero Akechi habr胤a entrado[n]en el Palacio justo despu姻s[n]de ver a Sae en el pasillo, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 42 65535 0]Por tanto, hab胤a bastantes posibilidades[n]de que se topara[n]con el Akechi cognitivo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 43 65535 0]Y si hubiera pasado eso, Akechi[n]se habr胤a dado cuenta de que lo[n]hab胤amos atra胤do hasta el Palacio.[n][w][e]

[msg MSG_FUTABA_1121_112_00 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 44 65535 0]A nadie se le ocurri吋[n]esta posibilidad hasta la noche[n]anterior al asesinato.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 45 65535 0]Makoto se dio cuenta en plena[n]noche, y luego estuvimos pensando[n]qu姻 hacer, lo cual fue un caos.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 46 65535 0]Al final, decidimos colarnos[n]en el Metaverso durante el plan[n]para entretener a la cognici吋n.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 47 65535 0]Como le dijiste a Sae que le ense隠ara[n]el m吋vil, esper茨bamos[n]que hablaran un rato al menos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 48 65535 0]Ten胤amos unos minutos desde[n]que apareci吋 el Akechi cognitivo[n]hasta que el Navegador se activ吋.[n][w][e]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 49 65535 0]斡Se pon胤a en marcha[n]la operaci吋n 或Entretenlo位! Aunque[n]al final, de operaci吋n tuvo poco.[n][w][e]

[msg MSG_FUTABA_1121_113_00 [Futaba]]
[s][f 4 23 1 65535 3 0 0 0][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 50 65535 0]Por suerte, Sae no conoc胤a[n]su verdadero aspecto, as胤 que[n]quien apareci吋 era un ni隠o cualquiera.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 51 65535 0]Rodearlo, dejarlo inconsciente[n]y tirarlo a otra planta[n]fue bastante f茨cil.[n][w][e]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 0 1 52 65535 0]Pero tendr胤as que haber[n]visto a Makoto...[n]C吋mo usa los nudillos, colega.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 53 65535 0]Lo que digo es que agradezco[n]lo que hicieron los dem茨s.[n][w][e]

[msg MSG_FUTABA_1121_114_00 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 54 65535 0]Uf, no puedo evitar hablar por los codos[n]sobre temas que me interesan.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 55 65535 0]Lo siento. T雨 descansa.[n]No tienes que preocuparte[n]de nada m茨s.[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 56 65535 0]Y [f 4 2]...[n]Buen trabajo, en serio.[n][w][e]

[msg MSG_FUTABA_1121_102_01 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 57 65535 0]Supongo que es comprensible.[n]Tienes que estar muy cansado.[n][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 58 65535 0]T雨 descansa.[n]No tienes que preocuparte de nada m茨s.[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 59 65535 0]Y... bien hecho,[n][f 4 2], de verdad.[n][w][e]

[msg MSG_MASTER_1121_000_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5111 65535 0]Ah, por cierto...[n][w][e]
[s][f 4 10 65535 0 0]No van a enviar el informe policial[n]de tu muerte al instituto.[n]No te preocupes.[n][w][e]
[s][f 4 10 65535 0 0]Parece que la fiscal Niijima[n]ha hecho una especie de trato[n]con los que mandan o algo as胤.[n][w][e]
[s][f 4 10 65535 0 0]Es que no me han dicho nada ni a m胤.[n]Pero, bueno, t雨 estate callado[n]y todo ir茨 bien.[n][w][e]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 2 1 5135 65535 0]Si dijeran que has muerto,[n]supongo que eso ser胤a como afirmar[n]que eras un Ladr吋n Fantasma.[n][w][e]
[s][f 4 10 65535 0 0]No pueden ir difundiendo[n]qui姻nes son los Ladrones Fantasma,[n]as胤 que imagino que querr茨n evitarlo.[n][w][e]

[msg MSG_MORUGANA_1121_100_00 [Morgana]]
[s][f 4 23 1 65535 6 0 5 0][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1173 65535 0]Bueno, me alegra que hayas vuelto[n]sano y salvo.[n][w][e]
[s][f 4 10 65535 0 0]Pero eso es suavizarlo mucho.[n]Lo pasaste mal, 夷a que s胤?[n][w][e]

[sel SEL_MORUGANA_1121_101_00 top]
[s]No te preocupes.[e]
[s]Solo un poco.[e]

[msg MSG_MORUGANA_1121_102_00 [Morgana]]
[s][f 4 23 1 65535 6 0 5 0][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1032 65535 0]Akechi iba a por ti desde el[n]principio. Aunque fuera arriesgado,[n]ten胤amos que contar con 姻l.[n][w][e]
[s][f 4 10 65535 0 0]Pero gracias a tu perseverancia[n]pudimos enga隠arlo.[n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0]Es la hora de la venganza.[n]斡Que se arrepienta de subestimar[n]a los Ladrones Fantasma![n][w][e]

