[sel YESNO_SEL top]
[s]はい[e]
[s]いいえ[e]

[msg NPC_GREETING_MSG]
[s]挨拶[n][w][e]

[msg NPC_01]
[s]会話[n][w][e]

[msg MSG_EKIINSET_001_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Soy el nuevo trabajador de la[n]estaci吋n de Shibuya! 斡Estoy listo[n]para la formaci吋n, jefe![n][w][e]

[msg MSG_EKIINSET_001_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]No me llames jefe, y rel茨jate un[n]poco. S姻 que eres nuevo, pero no[n]tienes por qu姻 ser tan formal.[n][w][e]
[s][vp 8 2 1 0 2 0]Hay muchos pasajeros preocupados[n]por los accidentes, y debemos hacer[n]que se sientan seguros.[n][w][e]

[msg MSG_EKIINSET_001_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Por supuesto, jefe! 斡No habr茨[n]ning雨n accidente en mi guardia![n]斡A toda mecha![n][w][e]

[msg MSG_EKIINSET_002_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]No hay forma de predecir un accidente,[n]por lo que hay que vigilar[n]todo el and姻n.[n][w][e]
[s][vp 8 2 1 0 1 0]Oye, 夷me est茨s escuchando?[n][w][e]

[msg MSG_EKIINSET_002_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡P-perd吋n, jefe! 斡Es que[n]me ha venido algo a la cabeza![n][w][e]
[s][vp 8 2 1 0 1 0]Cuando se dice que los pasajeros[n]se queden tras la l胤nea amarilla,[n]no es por el lado del tren, 夷no?[n][w][e]

[msg MSG_EKIINSET_003_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Una pregunta r茨pida, jefe.[n]夷El instituto de aquel profe[n]pervertido queda cerca?[n][w][e]

[msg MSG_EKIINSET_003_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]S胤, el Shujin no est茨 lejos. Es[n]importante que conozcas los centros[n]que hay cerca de las estaciones.[n][w][e]

[msg MSG_EKIINSET_003_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Todav胤a no me lo creo...[n]斡Con lo que me gustaba Kamoshida![n][w][e]

[msg MSG_EKIINSET_003_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Pues s胤, hasta yo hab胤a o胤do hablar[n]de 姻l. 夷Qu姻 lleva a un hombre a[n]hacer algo as胤...?[n][w][e]

[msg MSG_EKIINSET_004_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Jefe! 斡Alguien ha vuelto[n]a arrancar los carteles![n][w][e]

[msg MSG_EKIINSET_004_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]夷Los de la exposici吋n de Madarame?[n]Malditos cr胤os...[n][w][e]

[msg MSG_EKIINSET_004_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]夷Qu姻 deber胤amos hacer? En primaria[n]me dieron un premio por mis[n]habilidades art胤sticas. Podr胤a...[n][w][e]

[msg MSG_EKIINSET_004_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]斡夷Insin雨as que volvamos a dibujar[n]los carteles nosotros...?![n][w][e]

[msg MSG_EKIINSET_005_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Parece que en Shibuya cada vez[n]hay m茨s cr胤menes, 夷no crees?[n]O eso es lo que dice la gente.[n][w][e]
[s][vp 8 2 1 0 2 0]Ve con cuidado,[n]que parece que est茨n estafando[n]a todo el mundo.[n][w][e]

[msg MSG_EKIINSET_005_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Ah, s胤... ciberestofados[n]o algo as胤, 夷verdad?[n][w][e]

[msg MSG_EKIINSET_005_2_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Eh... No, es 或ciberestafas位.[n]No te ir胤a mal leer un poco.[n][w][e]

[msg MSG_EKIINSET_006_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Perdona que te lo pregunte,[n]pero 夷por qu姻 quer胤as[n]trabajar aqu胤?[n][w][e]

[msg MSG_EKIINSET_006_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Me perd胤 en una estaci吋n de[n]peque隠o, pero uno de los empleados[n]me encontr吋 y me salv吋![n][w][e]
[s][vp 8 2 1 0 1 0]Desde entonces, siempre he querido[n]trabajar en una y ser como 姻l,[n]un h姻roe en el que confiar.[n][w][e]

[msg MSG_EKIINSET_006_2_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Muy bien. No lo olvides nunca.[n]Te voy a ense隠ar todo lo que s姻.[n][w][e]

[msg MSG_EKIINSET_007_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Parece que los Ladrones Fantasma[n]est茨n en la ciudad. Tenemosque estar atentos.[n][w][e]

[msg MSG_EKIINSET_007_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡A sus 吋rdenes, jefe! Pero 夷eso no[n]es trabajo de la polic胤a?[n][w][e]

[msg MSG_EKIINSET_007_2_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]La seguridad de los pasajeros es[n]nuestro deber. Por eso hay que[n]saber lo que ocurre en la ciudad.[n][w][e]

[msg MSG_EKIINSET_007_3_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡O胤do cocina, jefe![n]斡Tiene todo mi apoyo![n][w][e]

[msg MSG_EKIINSET_008_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Ahora que la mafia ya no est茨,[n]estoy seguro de que vendr茨[n]m茨s gente a Shibuya![n][w][e]

[msg MSG_EKIINSET_008_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]S胤, eso es bueno. Pero me temo[n]que ha sucedido algo terrible.[n][w][e]

[msg MSG_EKIINSET_008_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]夷Que alguien ha saltado a las v胤as?[n][w][e]

[msg MSG_EKIINSET_008_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]S胤. He o胤do lo que dec胤a la polic胤a.[n]Parece que lo echaron de su[n]trabajo y no sab胤a qu姻 hacer...[n][w][e]
[s][vp 8 2 1 0 2 0]Por lo visto se filtr吋 su lista de[n]clientes o algo, as胤 que le largaron.[n]Qu姻 mundo cruel.[n][w][e]

[msg MSG_EKIINSET_009_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Oiga, jefe... Hay algo que no[n]entiendo, as胤 que me gustar胤a[n]pregunt茨rselo.[n][w][e]

[msg MSG_EKIINSET_009_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Me alegra que no te d姻 miedo[n]preguntar. 夷En qu姻 puedo ayudarte?[n][w][e]

[msg MSG_EKIINSET_009_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Llevo toda la noche pens茨ndolo...[n]夷Qui姻n cree que ganar茨, los[n]Ladrones Fantasma o los hackers?[n][w][e]

[msg MSG_EKIINSET_009_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Por el amor de... Mira, ya s姻 que[n]es un debate interesante,[n]pero c姻ntrate en el trabajo.[n][w][e]

[msg MSG_EKIINSET_010_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Es m茨s que probable que Medjed[n]ataque alg雨n tren, por lo que[n]hay que estar alerta.[n][w][e]
[s][vp 8 2 1 0 2 0]Debemos evitar otra cat茨strofe...[n][w][e]
[s][vp 8 2 1 0 2 0]斡Eh! 夷Me est茨s escuchando?[n][w][e]

[msg MSG_EKIINSET_010_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Perd吋n, es que este calor[n]me deja atontado...[n][w][e]

[msg MSG_EKIINSET_011_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Vigila a la gente que est茨[n]m茨s pendiente del m吋vil[n]que de lo que la rodea.[n][w][e]
[s][vp 8 2 1 0 2 0]Y hoy en d胤a no son pocos.[n]夷Qu姻 tiene de interesante estar[n]pegado a una pantalla?[n][w][e]

[msg MSG_EKIINSET_011_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Seguro que est茨n mirando p茨ginas[n]sobre los Ladrones Fantasma.[n]斡A la gente les encanta![n][w][e]

[msg MSG_EKIINSET_011_2_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Tiene l吋gica, y es lo 雨nico[n]que sale en los medios ahora.[n]夷Hasta cu茨ndo estaremos as胤?[n][w][e]

[msg MSG_EKIINSET_012_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Jefe, parece que este mes[n]ha habido menos suicidios![n][w][e]

[msg MSG_EKIINSET_012_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Pues s胤... Puede que, gracias a los[n]Ladrones Fantasma, la gente[n]est姻 m茨s feliz.[n][w][e]

[msg MSG_EKIINSET_012_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Eso es lo que pienso yo, jefe![n]斡Ni una rega隠ina suya podr胤a[n]acabar con mi buen humor![n][w][e]

[msg MSG_EKIINSET_012_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Siempre igual, chico...[n][w][e]

[msg MSG_EKIINSET_013_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 4 3 10 0 10][vp 8 2 1 0 4 0]斡Por favor, mant姻nganse detr茨s[n]de la l胤nea amarilla! 斡La puerta[n]llegar茨 a la v胤a dos![n][w][e]
[s][vp 8 2 1 0 4 0]Eh, quiero decir el tren.[n]斡Y sus puertas![n][w][e]

[sel SEL_EKIINSET_013_0_0 top]
[s]Tranquil胤zate.[e]
[s]Est茨s haciendo mucho ruido.[e]

[msg MSG_EKIINSET_013_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 4 3 10 0 10][vp 8 2 1 0 4 0]斡Gracias, jefe! He estado[n]trabajando en proyectar mis...[n][w][e]
[s][vp 8 2 1 0 4 0]Eh, si no eres el jefe.[n]Perd吋n, me he equivocado.[n][w][e]

[msg MSG_EKIINSET_013_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 4 3 10 0 10][vp 8 2 1 0 4 0]斡Gracias, jefe![n][w][e]
[s][vp 8 2 1 0 4 0]Eh, si no eres el jefe.[n]Perd吋n, me he emocionado.[n][w][e]

[msg MSG_EKIINSET_014_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]No s姻 por qu姻,[n]pero hoy esto est茨 muy triste...[n][w][e]

[msg MSG_EKIINSET_014_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Es un reflejo de lo que siente[n]la sociedad. Seguro que se debe[n]a esa rueda de prensa...[n][w][e]

[msg MSG_EKIINSET_014_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Pues es en momentos como[n]este en el que debemos ser[n]una fuente de inspiraci吋n![n][w][e]

[msg MSG_EKIINSET_014_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Por una vez, tienes toda la raz吋n.[n]Es cierto, los pasajeros[n]deben sentirse seguros.[n][w][e]

[msg MSG_EKIINSET_015_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]La polic胤a busca pistas[n]sobre los Ladrones Fantasma.[n]No bajes la guardia, por si acaso.[n][w][e]

[msg MSG_EKIINSET_015_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡No lo dude, jefe! 斡La seguridad[n]de nuestros pasajeros[n]es mi prioridad![n][w][e]

[msg MSG_EKIINSET_015_2_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Me gusta tu actitud, pero no[n]grites tanto cuando[n]hables por megafon胤a.[n][w][e]
[s][vp 8 2 1 0 2 0]Los pasajeros se quedar胤an[n]de piedra si llegara solo[n]una puerta al and姻n.[n][w][e]

[msg MSG_EKIINSET_015_3_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Eh, 夷me ha o胤do?[n]斡L-lo siento, jefe![n][w][e]

[msg MSG_EKIINSET_016_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]La polic胤a busca pistas[n]sobre los Ladrones Fantasma.[n]No bajes la guardia, por si acaso.[n][w][e]

[msg MSG_EKIINSET_016_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Jefe, 夷cree que el alboroto[n]se debe a la recompensa?[n][w][e]

[msg MSG_EKIINSET_016_2_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Y tambi姻n al cambio de gobierno.[n]O胤 a la mujer del quiosco[n]hablar del tema.[n][w][e]
[s][vp 8 2 1 0 2 0]Seg雨n ella, la prensa amarilla est茨[n]vendiendo como churros. Ser茨 que[n]la gente est茨 interesada.[n][w][e]

[msg MSG_EKIINSET_017_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Has actuado bien ayudando[n]al pasajero que se ha puesto[n]enfermo de repente.[n][w][e]

[msg MSG_EKIINSET_017_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Me asust姻 un poco al principio.[n]Pens姻 que, al caer as胤, ser胤a cosa[n]de los Ladrones Fantasma.[n][w][e]
[s][vp 8 2 1 0 1 0]Pero sab胤a que usted tampoco se[n]quedar胤a de brazos cruzados, jefe.[n]Debemos cuidar de los pasajeros.[n][w][e]

[msg MSG_EKIINSET_017_2_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Has aprendido mucho.[n]Me alegro de que no fuera[n]nada serio.[n][w][e]
[s][vp 8 2 1 0 2 0]En fin, espero que todo esto[n]se acabe m茨s pronto que tarde.[n][w][e]

[msg MSG_EKIINSET_018_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Cuidado con los borrachos,[n]que en esta 姻poca del a隠o[n]salen como setas.[n][w][e]
[s][vp 8 2 1 0 2 0]Y en invierno aumentan[n]los suicidios. Teniendo[n]en cuenta la econom胤a...[n][w][e]

[msg MSG_EKIINSET_018_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Puede que peque de inocente,[n]pero no entiendo por qu姻[n]la gente act雨a as胤...[n][w][e]

[msg MSG_EKIINSET_018_2_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Algunas personas prefieren huir de[n]los problemas... Tal vez sea el caso[n]de aquel Ladr吋n Fantasma.[n][w][e]

[msg MSG_EKIINSET_019_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡T胤o, no me creo[n]que haya aparecido otro aviso![n][w][e]
[s][vp 8 2 1 0 1 0]Ah, perdone, jefe.[n]Estamos de servicio.[n][w][e]

[msg MSG_EKIINSET_019_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]No pasa nada, estoy igual[n]que t雨. Seg雨n la polic胤a,[n]el chico estaba muerto.[n][w][e]
[s][vp 8 2 1 0 2 0]A saber qu姻 nos aguarda el futuro,[n]pero cuento contigo, chico.[n][w][e]

[msg MSG_EKIINSET_020_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Se han acabado las elecciones, 夷no?[n]夷Hay gente nueva gobernando?[n][w][e]

[msg MSG_EKIINSET_020_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]S胤, aunque hay algo que no me[n]acaba de cerrar. Quiz茨 es se隠al[n]de que los tiempos cambian.[n][w][e]
[s][vp 8 2 1 0 2 0]Al igual que nuestro trabajo en[n]esta estaci吋n. A partir de este[n]momento, est茨s al cargo.[n][w][e]

[msg MSG_EKIINSET_020_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡A sus 吋rdenes![n][w][e]
[s][vp 8 2 1 0 1 0]Un momento...[n]夷Qu姻 quiere decir, jefe?[n][w][e]

[msg MSG_EKIINSET_021_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Me alegro de que[n]hayas vuelto, jefe![n][w][e]

[msg MSG_EKIINSET_021_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Se supon胤a que iba a irme de aqu胤[n]a finales del a隠o pasado, pero de[n]repente hubo un cambio de planes.[n][w][e]

[msg MSG_EKIINSET_021_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]A雨n no tengo tanta experiencia.[n]斡Estoy deseando[n]aprender a雨n m茨s de ti![n][w][e]

[msg MSG_EKIINSET_021_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Ser茨 un placer ense隠arte.[n]Me alegra que podamos[n]trabajar juntos un poco m茨s.[n][w][e]

[msg MSG_EKIINSET_022_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]夷No crees que este a隠o los 茨nimos[n]est茨n mejor en la estaci吋n?[n][w][e]

[msg MSG_EKIINSET_022_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Dicen que este a隠o todo el mundo[n]cumplir茨 sus sue隠os.[n][w][e]

[msg MSG_EKIINSET_022_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]T雨 me ense隠aste que la estaci吋n es[n]或un reflejo de los sentimientos[n]de la sociedad位.[n][w][e]

[msg MSG_EKIINSET_022_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]Ah, 夷te acuerdas de eso?[n]Supongo que te he ense隠ado bien.[n][w][e]

[msg MSG_EKIINSET_022_4_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Me he acordado de todo eso[n]porque t雨 me has ense隠ado![n][w][e]
[s][vp 8 2 1 0 1 0]Por eso me sentir胤a mucho mejor[n]si siguieras trabajando[n]aqu胤 conmigo.[n][w][e]

[msg MSG_EKIINSET_023_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]郁ltimamente no oigo nada de los[n]Ladrones Fantasma. El a隠o[n]pasado no se hablaba de otra cosa.[n][w][e]

[msg MSG_EKIINSET_023_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]La gente olvida y sigue[n]con su vida, igual que se olvidar茨n[n]de que yo trabajaba en la estaci吋n.[n][w][e]

[msg MSG_EKIINSET_023_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Yo nunca lo har姻! 斡Eres la persona[n]m茨s admirable que he conocido![n][w][e]
[s][vp 8 2 1 0 1 0]De hecho, tengo una idea.[n]斡Trabajemos aqu胤 siempre![n][w][e]
[s][vp 8 2 1 0 1 0]As胤 siempre te recordar姻, 斡y seremos[n]felices todos los d胤as![n][w][e]

[msg MSG_EKIINSET_023_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]或Siempre位... No suena nada mal.[n][w][e]

[msg MSG_EKIINSET_023_4_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡Hablemos con los jefes! 斡Este a隠o[n]se cumplir茨n nuestros deseos![n][w][e]

[msg MSG_EKIINSET_024_0_0 [Empleado de estaci吋n reci姻n ascendido]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]斡El tren se aproxima al and姻n dos![n]斡Por favor, al姻jense de las v胤as![n][w][e]

[msg MSG_EKIINSET_024_1_0 [Ni隠o inocente]]
[s][f 4 23 1 2 3 10 0 10][vp 8 2 1 0 2 0]斡C吋mo molas![n]夷Por qu姻 sabes tanto de trenes?[n][w][e]

[msg MSG_EKIINSET_024_2_0 [Empleado de estaci吋n reci姻n ascendido]]
[s][f 4 23 1 1 3 10 0 10][vp 8 2 1 0 1 0]Lo he aprendido todo de mi antiguo[n]jefe. Era el mejor.[n][w][e]
[s][vp 8 2 1 0 1 0]Lo ascendieron, pero me dej吋[n]al cargo de la estaci吋n.[n][w][e]
[s][vp 8 2 1 0 1 0]斡M胤reme bien, jefe![n]斡A toda mecha, pero sin accidentes![n][w][e]

[msg MSG_AYASIOTOKO_001_0_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]夷No sabes qu姻 tren tomar?[n][w][e]
[s][vp 8 2 1 0 18 0]Hay much胤sima gente y es muy[n]f茨cil perderse, sobre todo[n]si vienes de una zona rural.[n][w][e]

[sel SEL_AYASIOTOKO_001_0_0 top]
[s]夷C吋mo lo sab胤as?[e]
[s]Soy de la ciudad.[e]
[s]夷Trabajas aqu胤?[e]

[msg MSG_AYASIOTOKO_001_1_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Es mi trabajo, ya estoy[n]acostumbrado. He pasado mucho[n]tiempo observando trenes.[n][w][e]
[s][vp 8 2 1 0 18 0]No estoy haciendo nada sospechoso.[n]No te preocupes por m胤.[n][w][e]

[msg MSG_AYASIOTOKO_001_2_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Qu姻 raro. Parece que mi intuici吋n[n]ya no es lo que era.[n][w][e]
[s][vp 8 2 1 0 18 0]No soy un tipo sospechoso, solo[n]estoy observando los trenes.[n]Haz como si no existiera.[n][w][e]

[msg MSG_AYASIOTOKO_001_3_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Eh... No, solo disfruto observando[n]los trenes desde aqu胤.[n][w][e]
[s][vp 8 2 1 0 18 0]No estoy haciendo nada sospechoso.[n]No te preocupes por m胤.[n][w][e]

[msg MSG_AYASIOTOKO_002_0_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Ese uniforme... 夷Vas al Instituto[n]Shujin? S姻 a qu姻 lugares de inter姻s[n]puedes llegar con esta l胤nea.[n][w][e]
[s][vp 8 2 1 0 18 0]Llevo a隠os aqu胤, observando. Podr胤a[n]compartir much胤simas historias.[n][w][e]
[s][vp 8 2 1 0 18 0]夷Te interesa la historia[n]de esta estaci吋n?[n][w][e]

[sel SEL_AYASIOTOKO_002_0_0 top]
[s]Pues no.[e]
[s]Dime.[e]
[s]夷Me est茨s tirando los tejos?[e]

[msg MSG_AYASIOTOKO_002_1_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Ah, qu姻 decepci吋n... Deber胤as[n]buscarla cuando tengas tiempo.[n][w][e]

[msg MSG_AYASIOTOKO_002_2_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Cuesta imaginarlo ahora, pero[n]la estaci吋n estaba vac胤a el d胤a[n]de su inauguraci吋n. Nadie vino.[n][w][e]
[s][vp 8 2 1 0 18 0]Pero las obras continuaron, se[n]fueron a隠adiendo m茨s l胤neas y ahora[n]es de las que m茨s pasajeros tiene.[n][w][e]

[msg MSG_AYASIOTOKO_002_3_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]斡夷Qu姻?! 斡Claro que no![n]No estoy planeando[n]nada raro, lo prometo...[n][w][e]

[msg MSG_AYASIOTOKO_002_4_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Oh, ya estar茨 al caer... Lo siento,[n]pero tengo que marcharme.[n][w][e]

[msg MSG_AYASIOTOKO_003_0_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]夷Deber胤a armarme de valor[n]y hablar con ella...?[n][w][e]
[s][vp 8 2 1 0 18 0]Pero si hablo con ella, 夷luego qu姻?[n]夷Le digo que la quiero?[n][w][e]
[s][vp 8 2 1 0 18 0]O mejor, 或夷siempre te estoy[n]observando?位. No, ser胤a demasiado.[n]Y muy repentino.[n][w][e]
[s][vp 8 2 1 0 18 0]Est茨n pasando cosas raras[n]雨ltimamente y no quiero que[n]se asuste. 夷Qu姻 deber胤a hacer...?[n][w][e]

[msg MSG_AYASIOTOKO_004_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]Entiendo por lo que est茨s pasando,[n]pero tengo que pedirte que no[n]llames mucho la atenci吋n.[n][w][e]

[msg MSG_AYASIOTOKO_004_1_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Lo entiendo. S姻 lo importante que[n]es este sitio para ti.[n][w][e]

[msg MSG_AYASIOTOKO_004_2_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]La polic胤a se ha metido en nuestro[n]caso por motivos de seguridad.[n]No puedo defenderte siempre.[n][w][e]

[msg MSG_AYASIOTOKO_004_3_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]No dar姻 problemas.[n]Vete, o sospechar茨n de ti.[n][w][e]

[msg MSG_AYASIOTOKO_005_0_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Quiero hablar con ella, aunque sea[n]por un momento...[n][w][e]
[s][vp 8 2 1 0 18 0]夷Tendr茨 novio?[n]Puede que ya est姻 casada...[n][w][e]
[s][vp 8 2 1 0 18 0]No hay manera, no s姻 c吋mo[n]acercarme a ella...[n][w][e]

[msg MSG_AYASIOTOKO_006_0_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Han capturado al l胤der, pero[n]la ciudad sigue siendo peligrosa.[n]Me asegurar姻 de que est茨 a salvo.[n][w][e]

[msg MSG_AYASIOTOKO_006_1_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]夷Qui姻n es la chica de la que[n]habla? Cuidado, que distraerse as胤[n]puede ser peligroso.[n][w][e]

[msg MSG_AYASIOTOKO_006_2_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Eh, solo hablaba conmigo mismo.[n][w][e]
[s][vp 8 2 1 0 18 0]Ah, 夷eres el nuevo?[n]Por favor, vigila bien este lugar.[n][w][e]

[msg MSG_AYASIOTOKO_006_3_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]夷Vigilarlo? 夷La mafia merodea[n]por la zona o qu姻?[n]Pensaba que estaban en la c茨rcel...[n][w][e]

[msg MSG_AYASIOTOKO_007_0_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Hola... S姻 que esto es repentino,[n]pero 夷te acuerdas de m胤?[n][w][e]

[sel SEL_AYASIOTOKO_007_0_0 top]
[s]Te veo mucho por aqu胤.[e]
[s]Te veo alguna vez.[e]
[s]Para nada.[e]

[msg MSG_AYASIOTOKO_007_1_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Estoy aqu胤 casi todos los d胤as.[n]Supongo que no puedo culparte.[n][w][e]
[s][vp 8 2 1 0 18 0]Me pregunto si ella tambi姻n[n]lo sabe. 夷Deber胤a hablarle? Mmm...[n][w][e]

[msg MSG_AYASIOTOKO_007_2_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Hay mucha gente por aqu胤.[n]No pasa nada.[n][w][e]
[s][vp 8 2 1 0 18 0]Observo sin llamar la atenci吋n...[n]No me queda otra... *suspiro*[n][w][e]

[msg MSG_AYASIOTOKO_007_3_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Ya veo... Perdona.[n]Imagino que no te fijar胤as[n]en algo as胤 normalmente.[n][w][e]
[s][vp 8 2 1 0 18 0]Se asustar胤a si supiera que llevo[n]tanto tiempo observ茨ndola...[n]*suspiro*[n][w][e]

[msg MSG_AYASIOTOKO_007_4_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Lamento haberte hecho[n]una pregunta tan rara. Olv胤dalo.[n][w][e]

[msg MSG_AYASIOTOKO_008_0_0 [Mujer asustada]]
[s][vp 8 2 1 0 21 0]Cada vez que vengo por aqu胤, siento[n]como si alguien me mirara.[n]夷Ser茨 mi imaginaci吋n?[n][w][e]
[s][vp 8 2 1 0 21 0]Al parecer, Shibuya ya es segura,[n]pero... por alg雨n motivo,[n]me siento intranquila...[n][w][e]

[msg MSG_AYASIOTOKO_009_0_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]夷Vas a volver a rechazar el puesto[n]en la oficina central?[n][w][e]

[msg MSG_AYASIOTOKO_009_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]Parece que las noticias vuelan,[n]jefe. No puedo abandonar[n]este lugar.[n][w][e]

[msg MSG_AYASIOTOKO_009_2_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Ja, ja, ahora t雨 eres el jefe.[n]Hace tiempo que me retir姻.[n][w][e]
[s][vp 8 2 1 0 18 0]El nuevo se ocupar茨 de este sitio.[n]Que otros hereden tus obligaciones[n]forma parte del trabajo.[n][w][e]

[msg MSG_AYASIOTOKO_009_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]No es tan sencillo...[n]La situaci吋n es muy complicada.[n]No puedo dejarla en sus manos.[n][w][e]

[msg MSG_AYASIOTOKO_009_4_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Ups. Hablaremos de esto luego.[n]Ya casi es hora de que pase[n]por aqu胤.[n][w][e]

[msg MSG_AYASIOTOKO_010_0_0 [Mujer asustada]]
[s][f 4 23 1 20 3 10 0 10][vp 8 2 1 0 20 0]Disculpa. Siempre me est茨s[n]observando, 夷no? 夷Necesitas algo?[n][w][e]

[msg MSG_AYASIOTOKO_010_1_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Em... s胤, pero... tengo mis motivos...[n][w][e]

[msg MSG_AYASIOTOKO_010_2_0 [Mujer asustada]]
[s][f 4 23 1 20 3 10 0 10][vp 8 2 1 0 20 0]斡Deja de acosarme! 斡Si te vuelvo[n]a ver, llamar姻 a la polic胤a![n][w][e]

[msg MSG_AYASIOTOKO_010_3_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Claro, lo siento... Lo siento mucho...[n][w][e]

[msg MSG_AYASIOTOKO_011_0_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Ese reportaje sobre Okumura Foods[n]da mucho que pensar.[n][w][e]

[msg MSG_AYASIOTOKO_011_1_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]Sus empleados estaban obligados[n]a trabajar m茨s, pero nosotros[n]lo hacemos porque queremos.[n][w][e]

[msg MSG_AYASIOTOKO_011_2_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]La cosa no ha ido bien,[n]y me ha llamado acosador...[n]Ya no puedo verla m茨s...[n][w][e]

[msg MSG_AYASIOTOKO_011_3_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]Hablar姻 con ella. Estoy seguro[n]de que lo entender茨.[n][w][e]

[msg MSG_AYASIOTOKO_012_0_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 18 0]Y eso es todo.[n]夷Podr胤a hablar con 姻l?[n][w][e]

[msg MSG_AYASIOTOKO_012_1_0 [Mujer asustada]]
[s][f 4 23 1 20 3 10 0 10][vp 8 2 1 0 20 0]斡No me puede pedir eso![n]斡夷No sabe lo duro que ha sido...?![n][w][e]

[msg MSG_AYASIOTOKO_012_2_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 18 0]S姻 c吋mo se siente, pero d姻jeme[n]decirle una 雨ltima cosa.[n][w][e]
[s][vp 8 2 1 0 18 0]Si siempre usa esta estaci吋n,[n]det姻ngase un momento[n]y observe con atenci吋n.[n][w][e]
[s][vp 8 2 1 0 18 0]Puede que as胤 vea lo que ambos[n]intentamos proteger.[n][w][e]

[msg MSG_AYASIOTOKO_013_0_0 [Mujer asustada]]
[s][vp 8 2 1 0 21 0]Hay mucha gente en la estaci吋n[n]de Shibuya.[n][w][e]
[s][vp 8 2 1 0 21 0]夷Qu姻 estaba intentando proteger[n]que era tan importante como[n]para hacer lo que hizo?[n][w][e]
[s][vp 8 2 1 0 21 0]*suspiro* 夷Por qu姻 deber胤a[n]importarme...? 夷Qu姻 estoy haciendo...?[n][w][e]

[msg MSG_AYASIOTOKO_014_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]Parece estar de capa ca胤da, se隠or.[n]夷Ha perdido algo?[n][w][e]

[msg MSG_AYASIOTOKO_014_1_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Estoy bien, eres muy amable por[n]preguntar. Y se te est茨 empezando[n]a dar bien tu trabajo.[n][w][e]
[s][vp 8 2 1 0 18 0]Me recuerdas a los viejos[n]tiempos, en los que tu jefe[n]y yo trabaj茨bamos aqu胤.[n][w][e]

[msg MSG_AYASIOTOKO_014_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]斡夷Qu姻?! 夷Usted es el jefe de[n]mi jefe? 斡Es un placer![n][w][e]

[msg MSG_AYASIOTOKO_014_3_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Ja, ja, me recuerdas a 姻l cuando[n]era joven. Cuento contigo para[n]cuidar de esta estaci吋n.[n][w][e]

[msg MSG_AYASIOTOKO_015_0_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Tienes mala pinta.[n]夷Ocurre algo?[n][w][e]

[sel SEL_AYASIOTOKO_015_0_0 top]
[s]斡Me est茨n siguiendo![e]
[s]D姻jame en paz.[e]
[s]Me acaban de dejar.[e]

[msg MSG_AYASIOTOKO_015_1_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Ja, ja, 夷qu姻 has hecho? Ser茨 mejor[n]que pidas perd吋n cuanto antes.[n][w][e]
[s][vp 8 2 1 0 18 0]Yo no me merezco la oportunidad[n]de pedir perd吋n ni de verla...[n][w][e]

[msg MSG_AYASIOTOKO_015_2_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Perdona. Es que me fijo en estas[n]cosas porque es mi trabajo.[n]Aunque me retir姻 hace tiempo.[n][w][e]
[s][vp 8 2 1 0 18 0]No quiero insistir, pero[n]deber胤as hablar con alguien[n]si tienes problemas.[n][w][e]

[msg MSG_AYASIOTOKO_015_3_0 [Hombre sospechoso]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Y-ya veo. Ocurren muchas cosas[n]cuando eres joven.[n][w][e]
[s][vp 8 2 1 0 18 0]Aunque, en realidad, a m胤 me pasa[n]lo mismo. No puedo ni ver[n]a la persona que amo...[n][w][e]

[msg MSG_AYASIOTOKO_015_4_0 [Empleado de la estaci吋n veterano]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Si no vas con cuidado, podr胤as[n]acabar perdi姻ndolo todo.[n][w][e]
[s][vp 8 2 1 0 18 0]Es f茨cil convertirse en una persona[n]de mente cerrada cuando eres joven.[n]Que no te pase a ti.[n][w][e]

[msg MSG_AYASIOTOKO_016_0_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]Disculpa, 夷ocurre algo?[n][w][e]
[s][vp 8 2 1 0 19 0]Puede descansar en nuestra[n]enfermer胤a si se encuentra mal.[n][w][e]

[msg MSG_AYASIOTOKO_016_1_0 [Mujer asustada]]
[s][f 4 23 1 20 3 10 0 10][vp 8 2 1 0 20 0]No, pero gracias.[n]Es muy amable.[n][w][e]
[s][vp 8 2 1 0 20 0]Esto puede ser repentino, pero[n]quer胤a preguntarle algo...[n]夷Le gusta trabajar aqu胤?[n][w][e]

[msg MSG_AYASIOTOKO_016_2_0 [Empleado de la estaci吋n novato]]
[s][f 4 23 1 19 3 10 0 10][vp 8 2 1 0 19 0]Es dif胤cil, pero siempre lo hago[n]lo mejor que puedo. Esta estaci吋n[n]es importante para mucha gente.[n][w][e]

[msg MSG_AYASIOTOKO_017_0_0 [Anciano exempleado de la estaci吋n]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Me sorprende que[n]hayas contactado conmigo...[n][w][e]
[s][vp 8 2 1 0 18 0]Lo siento... Quiero pediros perd吋n[n]a tu madre y a ti por lo que hice.[n][w][e]

[msg MSG_AYASIOTOKO_017_1_0 [Mujer de cara seria]]
[s][vp 8 2 65535 0 0 0]...[n][w][e]

[msg MSG_AYASIOTOKO_017_2_0 [Anciano exempleado de la estaci吋n]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Estaba tan ocupado con el trabajo[n]que nunca ten胤a tiempo para estar[n]con mi familia.[n][w][e]
[s][vp 8 2 1 0 18 0]No espero que me perdones.[n]Solo me alegra haber podido hablar[n]contigo una vez m茨s.[n][w][e]

[msg MSG_AYASIOTOKO_017_3_0 [Mujer de cara seria]]
[s][f 4 23 1 20 3 10 0 10][vp 8 2 1 0 20 0]Espera...[n][w][e]
[s][vp 8 2 1 0 20 0]Ahora que paso por aqu胤 todos[n]los d胤as, comprendo lo importante[n]que es trabajar aqu胤.[n][w][e]
[s][vp 8 2 1 0 20 0]Creo que mam茨 te perdonar茨.[n]Quiero que vuelvas a casa, pap茨.[n][w][e]

[msg MSG_AYASIOTOKO_017_4_0 [Anciano exempleado de la estaci吋n]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Te ve胤a por la estaci吋n, pero[n]nunca pude hablar contigo...[n][w][e]
[s][vp 8 2 1 0 18 0]Lamento haberte asustado.[n]夷Me dar茨s la oportunidad[n]de enmendar mis errores?[n][w][e]

[msg MSG_AYASIOTOKO_017_5_0 [Mujer de cara seria]]
[s][f 4 23 1 20 3 10 0 10][vp 8 2 1 0 20 0]No pasa nada, pap茨.[n]Yo tambi姻n te pido perd吋n[n]por haber sido tan dura contigo.[n][w][e]
[s][vp 8 2 1 0 20 0]Espero que ahora podamos pasar[n]el tiempo como una familia.[n]Tambi姻n con mam茨, claro.[n][w][e]

[msg MSG_AYASIOTOKO_018_0_0 [Mujer risue隠a]]
[s][f 4 23 1 20 3 10 0 10][vp 8 2 1 0 20 0]Creo que nunca nos habr胤amos[n]visto si no hubiera sido por[n]el empleado de la estaci吋n.[n][w][e]
[s][vp 8 2 1 0 20 0]Era tu subordinado, 夷no?[n]Tendremos que darle las gracias.[n][w][e]

[msg MSG_AYASIOTOKO_018_1_0 [Anciano exempleado de la estaci吋n]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Al principio, era un tipo distra胤do[n]que se equivocaba constantemente,[n]como al hablar por megafon胤a.[n][w][e]
[s][vp 8 2 1 0 18 0]Preguntaba con una expresi吋n[n]muy seria qu姻 lado de la l胤nea[n]amarilla es el interior.[n][w][e]
[s][vp 8 2 1 0 18 0]Pero se le da muy bien su trabajo y[n]adem茨s ha formado a su subalterno.[n][w][e]

[msg MSG_AYASIOTOKO_018_2_0 [Mujer risue隠a]]
[s][f 4 23 1 20 3 10 0 10][vp 8 2 1 0 20 0]Hay gente tan maravillosa.[n]Quiero que me cuentes m茨s historias[n]de cuando trabajabas aqu胤.[n][w][e]

[msg MSG_AYASIOTOKO_018_3_0 [Anciano exempleado de la estaci吋n]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Claro, en cuanto llegue tu madre.[n]La de cosas que han pasado[n]en esta estaci吋n...[n][w][e]

[msg PAN_SHOP_NOTOPEN [Trabajador vivaz]]
[s]Lo siento, seguimos de reformas.[n][w][e]
[s]○日になったらオープンしますので[n]また来てください![n][w][e]

[msg PAN_SHOP_SELECT [Trabajador vivaz]]
[s]斡Bienvenido! 斡Tenemos una oferta[n]especial por tiempo limitado![n][w][e]
[s]夷No le apetece probar[n]nuestro delicioso pan?[n][w][e]

[sel PAN_SHOP_SELECT_SEL top]
[s]At雨nwich [150 ￥] [e]
[s]Rock n' Rollo [200 ￥][e]
[s]Baguette bateadora [200 ￥][e]
[s]EmPinidilla [250 ￥][e]
[s]Pazlomitas [250 ￥][e]
[s]Cancelar[e]

[msg PAN_SHOP_NO_MONEY]
[s]No tengo suficiente dinero.[n][w][e]

[msg PAN_SHOP_NOITEM [Trabajador vivaz]]
[s]斡Lo siento![n]Ese art胤culo se ha agotado.[n][w][e]

[msg PAN_SHOP_CHECK [Trabajador vivaz]]
[s]Ser茨n [var 0] yenes.[n]夷Te parece bien?[n][w][e]

[msg PAN_SHOP_THANKS [Trabajador vivaz]]
[s]斡Gracias! 斡Vuelva pronto![n][w][e]

[msg quest05_hint_talk_00_01 [Oficinista deprimido]]
[s]夷Qu姻 le pasa a esa se隠ora?[n]No deja de quejarse[n]de los trenes solo para mujeres...[n][w][e]

[msg quest05_hint_talk_00_02 [Oficinista alentador]]
[s]Veo que has conocido a la famosa[n]quejica de los trenes.[n][w][e]
[s]Dice que los trenes para mujeres[n]deber胤an funcionar todo el d胤a.[n]Hasta se queja cuando van vac胤os.[n][w][e]

[msg quest05_hint_talk_00_03 [Oficinista deprimido]]
[s]Ya veo... Eso explica por qu姻[n]a nadie m茨s parec胤a molestarle.[n][w][e]

[msg quest05_hint_talk_00_04 [Oficinista alentador]]
[s]Los empleados de la estaci吋n han[n]tenido que echarla varias veces.[n]Ahora todos intentan ignorarla.[n][w][e]
[s]Supongo que se queja[n]para liberar estr姻s.[n][w][e]
[s]Est茨 en internet, 或Mitsumi Kure位.[n]Hay muchos art胤culos[n]sobre su 或activismo位.[n][w][e]

[msg quest05_hint_talk_00_05 [Oficinista deprimido]]
[s]Es incre胤ble que siga con el tema[n]aunque la gente conozca[n]su informaci吋n personal[n][w][e]

[msg quest05_hint_sinjyo_00]
[s]Bueno, no es muy razonable...[n][w][e]

[msg MSG_quest05_morgana_00 [Morgana]]
[s]斡Bien! 斡Nos hemos enterado[n]de un rumor interesante![n][w][e]

[msg HELP_QUEST05_HINT [斡Incidente en la misi吋n!]]
[s]或[clr 4]Tutorial[clr 27]位 Recibe pistas de los[n]PNJ con [clr 2]globos rojos[clr 27].[n][w][e]

[msg quest05_hint_talk_01_01 [Oficinista alegre]]
[s]斡夷Te has enterado de lo de[n]la quejica de los trenes?![n][w][e]

[msg quest05_hint_talk_01_02 [Oficinista feliz]]
[s]S胤, va por ah胤 pidiendo disculpas,[n]夷no? Me pidi吋 perd吋n el otro d胤a.[n][w][e]
[s]Casi toca el suelo con la frente[n]de lo que se inclin吋. Me jur吋[n]que no se quejar胤a m茨s.[n][w][e]

[msg quest05_hint_talk_01_03 [Oficinista alegre]]
[s]Se dice que por fin alguien[n]la hizo callar. O eso, o fueron[n]los ladrones de corazones esos.[n][w][e]
[s]Si fue cosa suya, son mis h姻roes.[n][w][e]

[msg quest05_hint_talk_01_04 [Oficinista feliz]]
[s]No s姻 yo si los llamar胤a 或h姻roes位,[n]pero me alegro de que alguien[n]haya conseguido calmarla.[n][w][e]

[msg quest05_hint_sinjyo_01]
[s]Parece que el despertarha funcionado.[n][w][e]

[msg Quest13_target_00_00 [Marido reservado]]
[s]Keiko, 夷y si nos vamos de viaje[n]juntos? Solo esta vez.[n][w][e]

[msg Quest13_target_00_01 [Keiko Shiratori]]
[s]夷Con qu姻 dinero?[n][w][e]
[s]Apenas nos llega con lo que[n]tenemos, y no veas lo que[n]me cuesta que as胤 sea.[n][w][e]

[msg Quest13_target_00_02 [Marido reservado]]
[s]S胤, pero... t雨 sales por ah胤[n]de vez en cuando...[n][w][e]

[msg Quest13_target_00_03 [Keiko Shiratori]]
[s]斡Por supuesto![n][w][e]
[s]夷Es que eres de esos que piensan[n]que las mujeres tienen que estar[n]encerradas en casa o qu姻?[n][w][e]

[msg Quest13_target_00_04 [Marido reservado]]
[s]No, solo quer胤a decir que[n]podr胤amos usar ese dinero para...[n][w][e]
[s]*suspiro* Quiz茨s podemos[n]dejarlo para otro momento...[n][w][e]

[msg Quest13_target_00_05 [Keiko Shiratori]]
[s]夷Y cu茨ndo crees que va a ser?[n][w][e]
[s]斡Mi vida ser胤a mucho mejor[n]si ganases m茨s dinero![n][w][e]
[s]Ah, s胤, voy a comer[n]con una de las madres del barrio,[n]as胤 que te quedas solo.[n][w][e]
[s]He de guardar las apariencias[n]con los vecinos. Lo entiendes, 夷no?[n][w][e]

[msg Quest13_target_00_06 [Marido reservado]]
[s]夷Otra vez? Vale...[n][w][e]

[msg Quest13_target_sinjyo_00]
[s]Parece que es ella quien llevalos pantalones en la relaci吋n.[n][w][e]

[msg MSG_quest13_morgana_01 [Morgana]]
[s]Problemas de dinero, 夷eh? 斡Creo[n]que acabamos de encontrar[n]nuestro siguiente objetivo![n][w][e]
[s]斡Reun茨monos en el escondite![n][w][e]

[msg Quest13_target_01_00 [Keiko Shiratori]]
[s]夷Qu姻 es esto, un aviso?[n]夷Ya estamos con bromitas?[n][w][e]
[s]No puedes ser m茨s infantil, 夷no?[n][w][e]

[msg Quest13_target_01_01 [Marido reservado]]
[s]Ser茨 cosa de alg雨n cr胤o.[n]T胤ralo y ya est茨.[n][w][e]

[msg Quest13_target_01_02 [Keiko Shiratori]]
[s]Bueno, vale.[n][w][e]
[s]Ya me he puesto de mal humor,[n]con las ganas que ten胤a[n]de ir al sal吋n de belleza...[n][w][e]

[msg Quest13_target_sinjyo_01]
[s]Parece que el objetivo ha recibido[n]el aviso.[n][w][e]

[msg Quest13_target_02_00 [Hombre p茨lido]]
[s]Estoy bien, no es nada...[n][w][e]

[msg Quest13_target_02_01 [Keiko Shiratori]]
[s]Eso no es un simple resfriado.[n]Tienes que ir al m姻dico.[n][w][e]
[s]Pero a ver c吋mo lo pagamos...[n][w][e]
[s]Todo es culpa m胤a...[n]夷Por qu姻 no he ahorrado m茨s?[n][w][e]

[msg Quest13_target_02_02 [Hombre p茨lido]]
[s]Solo estoy algo cansado[n]de trabajar, nada m茨s.[n]No te preocupes.[n][w][e]

[msg Quest13_target_sinjyo_02]
[s]Parece que el karma[n]les ha pasado factura por vivirpor encima de sus posibilidades.[n][w][e]

[msg quest15_hint_talk_00 [Novio elegante]]
[s]Voy a matar a ese viejo...[n]斡Solo estaba mirando[n]el m吋vil en el tren![n][w][e]
[s]斡Ni siquiera estaba hablando,[n]lo llevaba en silencio![n][w][e]
[s]Fijo que no sabe ni lo que es eso.[n][w][e]

[msg quest15_hint_talk_01 [Novia moderna]]
[s]Ese carcamal se merece[n]una buena tunda, Takkun.[n]斡畏l s胤 que hac胤a ruido![n][w][e]

[msg quest15_hint_talk_02 [Novia elegante]]
[s]Ese cabr吋n no solo[n]me ech吋 la bronca a m胤.[n]Todos saben que es un desgraciado.[n][w][e]
[s]Se llama Muneo Horikuchi.[n]斡Hala, alguien ha publicado[n]su direcci吋n![n][w][e]
[s]斡Espero que ese cabr吋n[n]reciba su merecido![n][w][e]

[msg quest15_hint_sinjyo]
[s]Bueno, no parece que lo quieran[n]mucho.[n][w][e]

[msg MSG_quest15_morgana_00 [Morgana]]
[s]Parece que tiene una reputaci吋n[n]bastante mala en internet. 斡Vamos a buscarlo![n][w][e]

[msg quest24_hint_talk_00 [ヒント24]]
[s]クエスト24のテストメッセージです。[n]表示後、キャンプで追加を確認して下さい。[n][w][e]

[msg quest24_hint_sinjyo]
[s]クエスト24のテスト心情メッセージです。[n][w][e]

[msg MSG_quest24_morgana_00 [Morgana]]
[s]クエスト24のモルガナメッセージです。[n]表示に問題ないか確認して下さい。[n][w][e]

[msg Quest30_target_00_00 [ターゲット30]]
[s]クエスト30のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][f 4 23 1 608 3 10 0 10][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest30_target_sinjyo_00]
[s]クエスト30のテスト心情メッセージです。[n][w][e]

[msg MSG_quest30_morgana_01 [Morgana]]
[s]クエスト30のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest30_target_01_00 [ターゲット30]]
[s]クエスト30のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][f 4 23 1 608 3 10 0 10][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest30_target_sinjyo_01]
[s]クエスト30のテスト心情メッセージです。[n][w][e]

[msg Quest30_target_02_00 [ターゲット30]]
[s]クエスト30のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][f 4 23 1 608 3 10 0 10][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest30_target_sinjyo_02]
[s]クエスト30のテスト心情メッセージです。[n][w][e]

[msg Quest36_target_00_00 [Hombre de negocios infeliz]]
[s]Un momento, nosotros estamos[n]al mando de este proyecto...[n][f 4 23 1 600 3 10 0 10][w][e]

[msg Quest36_target_00_01 [Oficinista curtido]]
[s]Bueno, si estoy yo aqu胤 es[n]porque vosotros solos no pod胤ais.[n][f 4 23 1 601 3 10 0 10][w][e]

[msg Quest36_target_00_02 [Hombre de negocios infeliz]]
[s]Pero me hicieron jefe del proyecto...[n][f 4 23 1 600 3 10 0 10][w][e]

[msg Quest36_target_00_03 [Shinsuke Kishi]]
[s]Pues ya no. Desde ahora mismo,[n]servidor, Shinsuke Kishi,[n]es quien corta el bacalao.[n][f 4 23 1 601 3 10 0 10][w][e]
[s]La empresa me paga un sueldazo[n]para que tome las riendas de este[n]desastre, pedazo de in雨tiles.[n][w][e]
[s]Y ahorradme las quejas, 夷estamos?[n][w][e]
[s]A no ser que quer茨is que os[n]trasladen fuera de Tokio, claro.[n][w][e]

[msg Quest36_target_00_04 [Hombre de negocios infeliz]]
[s]No, se隠or...[n][f 4 23 1 600 3 10 0 10][w][e]

[msg Quest36_target_00_05 [Shinsuke Kishi]]
[s]斡Genial, vamos a informar al CEO![n][f 4 23 1 601 3 10 0 10][w][e]

[msg MSG_quest36_morgana_01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1130 65535 0]No creo que vayamos[n]a encontrar objetivos aqu胤...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Despertemos su coraz吋n[n]en Mementos cuanto antes.[n][w][e]

[msg Quest36_target_01_00 [Shinsuke Kishi]]
[s]夷Qu姻 narices es eso de la Fansite?[n]夷De qu姻 departamento es?[n][f 4 23 1 601 3 10 0 10][w][e]

[msg Quest36_target_01_01 [Hombre de negocios infeliz]]
[s]*grito ahogado* Si es...[n][f 4 23 1 600 3 10 0 10][w][e]

[msg Quest36_target_01_02 [Shinsuke Kishi]]
[s]夷Otra vez t雨?[n][f 4 23 1 601 3 10 0 10][w][e]

[msg Quest36_target_01_03 [Hombre de negocios infeliz]]
[s]斡No, para nada! 斡No fui yo![n][f 4 23 1 600 3 10 0 10][w][e]

[msg Quest36_target_sinjyo_01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0][vp 8 2 1 1106 65535 0]El acoso no acabar茨 hasta que no[n]despertemos su coraz吋n en Mementos.[n][w][e]

[msg Quest36_target_02_00 [Oficinista alegre]]
[s]夷Que qu姻? Pero es tu proyecto...[n][f 4 23 1 600 3 10 0 10][w][e]

[msg Quest36_target_02_01 [Shinsuke Kishi]]
[s]No, no, oc雨pate t雨. Los j吋venes[n]necesit茨is ganar experiencia.[n][f 4 23 1 601 3 10 0 10][w][e]

[msg Quest36_target_02_02 [Oficinista alegre]]
[s]V-vale, 斡gracias![n][f 4 23 1 600 3 10 0 10][w][e]

[msg Quest36_target_02_03 [Shinsuke Kishi]]
[s]斡Haz un gran trabajo, que[n]las copas las pago yo! 斡Prep茨rate[n]para salir toda la noche![n][f 4 23 1 601 3 10 0 10][w][e]

[msg Quest36_target_02_04 [Oficinista alegre]]
[s]斡No, no puedo, mi mujer me matar胤a![n][f 4 23 1 600 3 10 0 10][w][e]

[msg Quest36_target_sinjyo_02 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 1109 65535 0]Parece que ha despertado[n]sin problemas.[n][w][e]

[msg Quest43_target_00_00 [ターゲット43]]
[s]クエスト43のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗は受注可能状態です。[n][w][e]

[msg Quest43_target_sinjyo_00]
[s]クエスト43のテスト心情メッセージです。[n][w][e]

[msg MSG_quest43_morgana_01 [Morgana]]
[s]クエスト43のモルガナメッセージです。[n]ターゲット用です。[n][w][e]

[msg Quest43_target_01_00 [ターゲット43]]
[s]クエスト43のテストメッセージです。[n]表示後、キャンプで表示の変更を確認して下さい。[n][w][e]
[s]クエストの進捗はメメントス突入可能状態です。[n][w][e]

[msg Quest43_target_sinjyo_01]
[s]クエスト43のテスト心情メッセージです。[n][w][e]

[msg Quest43_target_02_00 [ターゲット43]]
[s]クエスト43のテストメッセージです。[n]表示後、キャンプでの状態を確認して下さい。[n][w][e]
[s]クエストの進捗はミッションクリア状態です。[n][w][e]

[msg Quest43_target_sinjyo_02]
[s]クエスト43のテスト心情メッセージです。[n][w][e]

[msg MSG_HAGEOTOKO_001_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]Siempre es mejor salir[n]con chicas m茨s j吋venes, y mi novia[n]es joven y mona. Es perfecta.[n][w][e]
[s][vp 8 2 1 0 6 0]夷Qu姻? 夷Quieres saber[n]si sigue siendo un secreto?[n][w][e]
[s][vp 8 2 1 0 6 0]斡Shhh! 斡No grites! A saber[n]qui姻n puede estar escuchando.[n][w][e]
[s][vp 8 2 1 0 6 0]Ya me pondr姻 en contacto contigo.[n]En cuanto a tu recompensa...[n]夷Qu姻 te parece una jovencita?[n][w][e]

[msg MSG_HAGEOTOKO_002_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]Las cosas con mi novia[n]van bastante bien. Las chicas[n]j吋venes son las mejores.[n][w][e]
[s][vp 8 2 1 0 6 0]夷C吋mo? 夷Matrimonio? Me gustar胤a,[n]pero... entonces ser茨[n]dif胤cil ocultarlo.[n][w][e]
[s][vp 8 2 1 0 6 0]El sistema favorece a los ricos[n]sobre los pobres.[n]No quer胤a recurrir a esto, pero...[n][w][e]
[s][vp 8 2 1 0 6 0]Si quiero ser feliz de verdad,[n]tengo que correr riesgos.[n]Es ir吋nico, pero lo hago por ella.[n][w][e]

[msg MSG_HAGEOTOKO_003_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]夷No te gust吋 la chica[n]que te present姻? Pues tambi姻n[n]era joven y guapa. Qu姻 decepci吋n.[n][w][e]
[s][vp 8 2 1 0 6 0]Pero una promesa es[n]una promesa. Ten胤amos un trato[n]y yo he cumplido mi parte.[n][w][e]
[s][vp 8 2 1 0 6 0]Necesito que me consigas[n]eso de lo que he o胤do[n]hablar. Aunque no ser茨 f茨cil.[n][w][e]
[s][vp 8 2 1 0 6 0]No puedo darte m茨s detalles[n]ahora mismo. Si no me ando con[n]cuidado, se descubrir茨 mi secreto.[n][w][e]

[msg MSG_HAGEOTOKO_004_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]Las mujeres de buen coraz吋n[n]y cari隠osas son lo m茨s,[n]y mi novia es la mejor.[n][w][e]
[s][vp 8 2 1 0 6 0]Es un poco joven, pero[n]se nota lo cari隠osa que es.[n][w][e]
[s][vp 8 2 1 0 6 0]夷Qu姻? 夷Quieres saber[n]si la medicina funcion吋? La verdad...[n]No es lo que esperaba.[n][w][e]
[s][vp 8 2 1 0 6 0]夷Puedes buscarme algo que[n]funcione? Te pagar姻 lo que[n]pueda. Ay雨dame, por favor.[n][w][e]

[msg MSG_HAGEOTOKO_005_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]夷C吋mo? 斡夷Tengo que vencer[n]con un palo de madera?![n][w][e]
[s][vp 8 2 1 0 6 0]No parece muy cient胤fico.[n]Aunque a estas alturas,[n]si funciona me da igual.[n][w][e]
[s][vp 8 2 1 0 6 0]Ya lo celebraremos[n]cuando resuelva mi problemilla.[n]斡Saldremos todos juntos![n][w][e]
[s][vp 8 2 1 0 6 0]夷Que cu茨les son mis planes[n]de boda? Me pondr姻 con ellos[n]cuando me deshaga de las pruebas.[n][w][e]

[msg MSG_HAGEOTOKO_006_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]S胤, es perfecto.[n]Nadie sabr茨 que est茨n[n]en los calcetines.[n][w][e]
[s][vp 8 2 1 0 6 0]Cuando trabajas, te mueves[n]muy r茨pido. Hasta los Ladrones[n]Fantasma se sorprender胤an.[n][w][e]
[s][vp 8 2 1 0 6 0]Ja, ja. S胤, seguro que vienen[n]a por m胤 si sigo enga隠茨ndola[n]de esta manera.[n][w][e]
[s][vp 8 2 1 0 6 0]Como siempre, esto queda[n]entre nosotros... Cuento contigo.[n][w][e]

[msg MSG_HAGEOTOKO_007_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]Los Ladrones Fantasma[n]han acabado con la mafia.[n]Da miedo que puedan hacer eso.[n][w][e]
[s][vp 8 2 1 0 6 0]Dicen que pueden hacerte[n]confesar cualquier cosa. Si me[n]pasara a m胤, estar胤a perdido...[n][w][e]
[s][vp 8 2 1 0 6 0]Claro que estoy desanimado.[n]Mi vida depende de esto.[n][w][e]
[s][vp 8 2 1 0 6 0]Quiero plantearme[n]un futuro con mi novia.[n]Tengo que arreglar esto.[n][w][e]

[msg MSG_HAGEOTOKO_008_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]El verano es la estaci吋n[n]del amor, aunque sea h雨medo.[n]Me he enterado de que tienes novia.[n][w][e]
[s][vp 8 2 1 0 6 0]Ah, 夷es un poco mayor que t雨?[n]A m胤 solo me interesan las j吋venes.[n][w][e]
[s][vp 8 2 1 0 6 0]Por cierto, 夷qu姻 hago[n]con 或lo que t雨 sabes位? Quiero[n]arreglar esto lo antes posible...[n][w][e]
[s][vp 8 2 1 0 6 0]斡夷Que me cuelgue de las mu隠ecas?![n]Suena doloroso,[n]pero no me queda otra.[n][w][e]

[msg MSG_HAGEOTOKO_009_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]Mi novia est茨 muy rara.[n]Creo que me est茨 ocultando algo.[n][w][e]
[s][vp 8 2 1 0 6 0]Joder, y en cuanto a[n]或lo que t雨 sabes位, nada funciona...[n]Como lo descubra...[n][w][e]
[s][vp 8 2 1 0 6 0]Que salgan a la luz mis secretos[n]es mi peor pesadilla. Como[n]los hackers vayan a por m胤...[n][w][e]
[s][vp 8 2 1 0 6 0]夷Que las cosas saldr茨n bien[n]por los Ladrones Fantasma?[n]斡Idiota, no arreglar茨n mi problema![n][w][e]

[msg MSG_HAGEOTOKO_010_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]He tenido much胤simo cuidado,[n]pero puede que pronto[n]acabe mi suerte...[n][w][e]
[s][vp 8 2 1 0 6 0]Ya llevo tres a隠os con mi novia.[n]A lo mejor tengo que casarme[n]con ella y ocult茨rselo.[n][w][e]
[s][vp 8 2 1 0 6 0]No, eso no est茨 bien...[n]Como no se lo cuente,[n]lo acabar茨 averiguando.[n][w][e]
[s][vp 8 2 1 0 6 0]夷Eh? 夷Que deber胤a preguntarle[n]lo que piensa de esos temas? Buena[n]idea. Le preguntar姻 indirectamente.[n][w][e]

[msg MSG_HAGEOTOKO_011_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]Me alegra que me pidieras[n]salir. Me lo he pasado muy bien,[n]y la pel胤cula ha estado genial.[n][w][e]

[msg MSG_HAGEOTOKO_011_1_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]S胤, sobre todo el giro argumental[n]del final. Todo era un espejismo.[n][w][e]

[msg MSG_HAGEOTOKO_011_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]斡夷B-boda?! Bueno, al fin y al cabo,[n]llevamos saliendo tres a隠os.[n]Lo he pensado, pero...[n][w][e]

[msg MSG_HAGEOTOKO_011_3_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]Mmm... 斡夷C吋mo?! 斡夷Boda?![n]斡Yo no he dicho nada de eso![n][w][e]

[msg MSG_HAGEOTOKO_011_4_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]夷No has dicho eso?[n]Ah... Vale...[n][w][e]

[msg MSG_HAGEOTOKO_011_5_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]Espera, 夷qu姻 has dicho?[n]夷Que lo has pensado, 或pero...位?[n]Pero 夷qu姻?[n][w][e]

[msg MSG_HAGEOTOKO_012_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]夷Hola? Oye, el otro d胤a[n]sali吋 el tema del matrimonio.[n][w][e]
[s][vp 8 2 1 0 6 0]No se la ve胤a muy emocionada.[n]A lo mejor es que ya lo sabe...[n][w][e]
[s][vp 8 2 1 0 6 0]斡S胤! 斡Le he ocultado lo de[n]mi calvicie! 斡Y llevo botas[n]de tac吋n para parecer m茨s alto![n][w][e]
[s][vp 8 2 1 0 6 0]Lo siento, no quer胤a[n]pagarlo contigo.[n]夷C吋mo lo habr茨 averiguado?[n][w][e]
[s][vp 8 2 1 0 6 0]Mierda, podr胤a pedirle[n]matrimonio si pudiera[n]encargarme de esto...[n][w][e]

[msg MSG_HAGEOTOKO_013_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]Buf, no soporto esta angustia...[n]Ojal茨 pudiera confesar en una rueda[n]de prensa y pedir disculpas...[n][w][e]
[s][vp 8 2 1 0 6 0]Llevaba botas de tac吋n[n]y 或accesorios位 en la cabeza...[n][w][e]
[s][vp 8 2 1 0 6 0]斡Soy bajito y calvo![n]Mi novia, tan joven y guapa,[n]se merece algo mejor.[n][w][e]
[s][vp 8 2 1 0 6 0]郁ltimamente no hablo mucho[n]con ella. Me da miedo[n]que me pregunte cosas.[n][w][e]
[s][vp 8 2 1 0 6 0]Seguro que lo sabe[n]y por eso no quiere casarse...[n][w][e]

[msg MSG_HAGEOTOKO_014_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]夷Hola? Soy yo. 夷Has visto la rueda[n]de prensa del se隠or Okumura?[n][w][e]
[s][vp 8 2 1 0 6 0]Eso es lo que les pasa[n]a los mentirosos...[n]En alg雨n momento, me ocurrir茨 a m胤.[n][w][e]
[s][vp 8 2 1 0 6 0]夷Crees que estoy exagerando?[n]斡Sin ella no soy nada![n][w][e]
[s][vp 8 2 1 0 6 0]Si de verdad eres mi mejor[n]amigo, tienes que ayudarme. 斡夷C吋mo[n]puedo tener un mont吋n de pelo?![n][w][e]
[s][vp 8 2 1 0 6 0]Tambi姻n tengo que solucionar[n]lo de la altura, con implantes[n]de silicona o lo que haga falta.[n][w][e]

[msg MSG_HAGEOTOKO_015_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]斡Venga, t胤o! 斡Ay雨dame,[n]te pagar姻![n][w][e]
[s][vp 8 2 1 0 6 0]Si son 30 millones de yenes[n]por los Ladrones Fantasma,[n]yo te doy 100! Aunque no los tengo...[n][w][e]
[s][vp 8 2 1 0 6 0]No puedo evitar estresarme...[n]Me quiero casar con mi novia...[n][w][e]
[s][vp 8 2 1 0 6 0]夷Eh? 夷Que por qu姻 me gusta tanto?[n]A ver, es joven y guapa...[n][w][e]
[s][vp 8 2 1 0 6 0]Pero cuando estoy con ella,[n]se me olvida todo lo dem茨s.[n]Es tan buena persona...[n][w][e]

[msg MSG_HAGEOTOKO_016_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]Si le digo la verdad,[n]夷crees que me aceptar茨[n]como soy en realidad?[n][w][e]
[s][vp 8 2 1 0 6 0]Soy muy inseguro... Por eso[n]escondo mis defectos[n]poni姻ndome estas cosas.[n][w][e]
[s][vp 8 2 1 0 6 0]夷Que me voy a quedar a雨n[n]m茨s calvo de tanto pensar?[n]No digas eso en un momento as胤...[n][w][e]
[s][vp 8 2 1 0 6 0]斡En fin, que quiero a mi novia![n]斡Me asusta m茨s perderla a ella[n]que perder el pelo![n][w][e]

[msg MSG_HAGEOTOKO_017_0_0 [Hombre alto]]
[s][vp 8 2 1 0 6 0]夷Calvo y bajito?[n]斡As胤 soy yo![n][w][e]
[s][vp 8 2 1 0 6 0]Seguir ocult茨ndolo ser胤a[n]como traicionar a mi novia, 夷no?[n][w][e]
[s][vp 8 2 1 0 6 0]斡Decidido! 斡Se lo contar姻 todo![n][w][e]
[s][vp 8 2 1 0 6 0]Conocer茨 a mi verdadero yo.[n]Y si no le gusta, pues nada...[n][w][e]
[s][vp 8 2 1 0 6 0]Gracias por escucharme[n]durante todo este tiempo.[n]斡Saldr姻 de esta![n][w][e]

[msg MSG_HAGEOTOKO_018_0_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]Hay algo que te he estado[n]ocultando. Quiero contarte[n]toda la verdad sobre m胤.[n][w][e]
[s][vp 8 2 1 0 6 0]Soy un tap吋n. Llevo zapatos[n]especiales que me hacen[n]al menos diez cent胤metros m茨s alto.[n][w][e]

[msg MSG_HAGEOTOKO_018_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]No me importa...[n]Y adem茨s, yo tambi姻n[n]te he ocultado algo...[n][w][e]
[s][vp 8 2 1 0 9 0]En realidad soy doce a隠os mayor[n]que t雨. Tengo veinte a隠os m茨s[n]de los que te dije... Perd吋name.[n][w][e]

[msg MSG_HAGEOTOKO_018_2_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]Veinte a隠os...[n][w][e]
[s][vp 8 2 1 0 6 0]斡N-no te preocupes, no pasa nada![n]Mi amor por ti sigue intacto. [n][w][e]
[s][vp 8 2 1 0 6 0]El caso es que tengo otro[n]secretillo... 斡Mira qu姻 entradas![n][w][e]
[s][vp 8 2 1 0 6 0]斡Lo he intentado todo, pero cada[n]vez van a m茨s! 斡Lo siento mucho![n][w][e]

[msg MSG_HAGEOTOKO_018_3_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]Hala...[n][w][e]
[s][vp 8 2 1 0 9 0]B-bueno, estoy sorprendida,[n]pero te quiero igual.[n][w][e]

[msg MSG_HAGEOTOKO_018_4_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]Soy un retaco sin pelo...[n]Pero 斡c茨sate conmigo![n][w][e]

[msg MSG_HAGEOTOKO_018_5_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]Y yo te ment胤 sobre mi edad...[n]S胤, quiero.[n][w][e]

[msg MSG_HAGEOTOKO_018_8_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]Me robaste el coraz吋n antes[n]de que me diera cuenta. Por eso[n]te confes姻 mis pecados.[n][w][e]

[msg MSG_HAGEOTOKO_018_9_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]A m胤 me ha pasado igual.[n]Parece que los Ladrones Fantasma[n]han vuelto a la acci吋n.[n][w][e]

[msg MSG_HAGEOTOKO_018_10_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]Te har姻 feliz, te lo prometo.[n][w][e]

[msg MSG_HAGEOTOKO_018_11_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]夷Quieres venir conmigo[n]a las elecciones? Planifiquemos[n]nuestro futuro... juntos.[n][w][e]

[msg MSG_HAGEOTOKO_019_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]Nuestra vida en com雨n acaba de[n]comenzar. Ojal茨 dure para siempre.[n][w][e]

[msg MSG_HAGEOTOKO_019_1_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]Eso espero.[n]Tengo la sensaci吋n de que[n]formaremos una familia feliz.[n][w][e]

[msg MSG_HAGEOTOKO_019_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]Quiero saber m茨s de ti,[n]as胤 que s姻 t雨 mismo.[n][w][e]

[msg MSG_HAGEOTOKO_019_3_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]Y yo. Quiero que puedas cont茨rmelo[n]todo. Te aceptar姻 tal y como eres.[n][w][e]

[msg MSG_HAGEOTOKO_019_4_0 [Mujer de aspecto joven]]
[s][f 4 23 1 9 3 10 0 10][vp 8 2 1 0 9 0]Siempre te he amado por el coraz吋n[n]tan grande que tienes, aunque...[n]斡tu calva tambi姻n es enorme![n][w][e]

[msg MSG_HAGEOTOKO_019_5_0 [Hombre alto]]
[s][f 4 23 1 6 3 10 0 10][vp 8 2 1 0 6 0]斡Y yo me enamor姻 de tu sarcasmo[n]de la vieja escuela, que no es[n]lo 雨nico viejo que hay aqu胤![n][w][e]

[msg MSG_TOSISABA_001_0_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Ay, estoy agotada... He estado[n]haciendo horas extra sin parar...[n]夷Ves estas ojeras?[n][w][e]

[msg MSG_TOSISABA_001_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Ten cuidado. He o胤do que[n]el estr姻s puede tener efectos[n]muy extra隠os hoy en d胤a...[n][w][e]

[msg MSG_TOSISABA_001_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]S胤, como esos accidentes de tren,[n]夷verdad? Toda esa gente se desmay吋[n]de repente y adi吋s...[n][w][e]

[msg MSG_TOSISABA_001_3_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]El estr姻s tampoco es bueno para[n]las arrugas. La calma es estupenda[n]para la piel.[n][w][e]

[msg MSG_TOSISABA_002_0_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Los precios suben, los impuestos se[n]disparan... Y los pol胤ticos no hacen[n]m茨s que hablar. 夷Para qu姻 sirven?[n][w][e]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Y el sueldo de mi marido, congelado[n]tambi姻n. A ti te viene bien, que tu[n]novio se est茨 forrando.[n][w][e]

[msg MSG_TOSISABA_002_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]No es solo cosa de dinero,[n]es que encima es alto y apuesto.[n][w][e]

[msg MSG_TOSISABA_002_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Menudo braguetazo. 夷C吋mo has[n]encontrado a un tiarr吋n as胤?[n][w][e]

[msg MSG_TOSISABA_002_3_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Pues... cosas de la vida.[n]斡El destino nos uni吋![n][w][e]

[msg MSG_TOSISABA_003_0_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Dicen que ese profesor, que estaba[n]muy bien considerado, acosaba a una[n]de sus alumnas. Pobrecilla.[n][w][e]

[msg MSG_TOSISABA_003_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]A las v胤ctimas les cuesta hablar[n]del tema. Te juro que si mi jefe me[n]tocara de forma lasciva...[n][w][e]

[msg MSG_TOSISABA_003_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Le pegar胤as una buena patada[n]con esos taconazos que gastas, 夷no?[n][w][e]

[msg MSG_TOSISABA_003_3_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]斡Pues mira, buena idea! Por suerte,[n]me acabo de comprar unos zapatos[n]de tac吋n de aguja para una cita.[n][w][e]

[msg MSG_TOSISABA_004_0_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]夷Conoces a Madarame?[n]斡夷A que es un bomb吋n?![n]Es totalmente mi tipo.[n][w][e]

[msg MSG_TOSISABA_004_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]He visto 或Imperio de pasi吋n位.[n]夷No es ese c姻lebre artista japon姻s?[n][w][e]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]A m胤 me van m茨s j吋venes. Ja, ja.[n][w][e]

[msg MSG_TOSISABA_004_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Baja esos humos... Eso de tener un jovenzuelo[n]por novio debe de ser la pera.[n][w][e]

[msg MSG_TOSISABA_005_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]夷Has visto la rueda de prensa[n]de Madarame? Ladr吋n, estafador...[n]Qu姻 miserable...[n][w][e]

[msg MSG_TOSISABA_005_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Pero 夷t雨 te has enterado? Se rode吋[n]de un mont吋n de jovencitos a los[n]que trataba como mascotas.[n][w][e]

[msg MSG_TOSISABA_005_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]斡Madre m胤a, me lo estoy imaginando![n]Y de entre todos esos,[n]siempre est茨 el guapo.[n][w][e]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Un guapet吋n delicado de tez clara...[n]斡Estoy segur胤sima![n][w][e]

[msg MSG_TOSISABA_006_0_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]As胤 que Akechi dijo en la tele que[n]los Ladrones Fantasma son[n]peligrosos, 夷no?[n][w][e]

[msg MSG_TOSISABA_006_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]斡S胤, Akechi! Echa unas miraditas[n]de reojo que me vuelven loca...[n][w][e]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Y tambi姻n me encanta la forma[n]que tiene de atusarse el pelo.[n][w][e]

[msg MSG_TOSISABA_006_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]夷Estabas escuch茨ndome?[n]S胤 que te van los yogurines...[n][w][e]

[msg MSG_TOSISABA_007_0_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Mi marido lleva un tiempo[n]fuera de casa.[n][w][e]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Se pasa el d胤a hablando de Egipto,[n]pero 夷de verdad hacer negocios[n]con clientes en el extranjero?[n][w][e]

[msg MSG_TOSISABA_007_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]夷Es por lo de Medjed?[n]No paran de hablar de ello[n]por internet, 夷verdad?[n][w][e]

[msg MSG_TOSISABA_007_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]斡S胤![n][w][e]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Se estaba frustrando por no poder[n]salir del trabajo. Resulta que no[n]puede llevarse el ordenador a casa.[n][w][e]

[msg MSG_TOSISABA_008_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Me asusta que Medjed sea capaz[n]de hackear cualquier cosa.[n][w][e]

[msg MSG_TOSISABA_008_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Me han dicho que son capaces de[n]burlar todo tipo de seguridad[n]en internet. Una pasada, vaya.[n][w][e]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Quiz茨 me una a ellos para que me[n]den el n雨mero de Akechi...[n][w][e]

[msg MSG_TOSISABA_008_3_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Ser茨s...[n][w][e]

[msg MSG_TOSISABA_009_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]No puedo dejar de ver las noticias.[n]Hasta las he grabado en v胤deo.[n][w][e]

[msg MSG_TOSISABA_009_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]No es propio de ti. 夷Es por lo que[n]est茨 pasando entre los[n]Ladrones Fantasma y Medjed?[n][w][e]

[msg MSG_TOSISABA_009_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]斡S胤! 斡Y quiero que ocurra algo![n][w][e]
[s][vp 8 2 1 0 7 0]斡As胤 podr姻 ver a Akechi[n]coment茨ndolo por la tele![n]斡Est茨 tan guapo cuando habla![n][w][e]

[msg MSG_TOSISABA_010_0_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]斡Los Ladrones Fantasma son[n]incre胤bles! 斡He o胤do que[n]han acabado con Medjed![n][w][e]

[msg MSG_TOSISABA_010_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]No s姻 yo. Si los Ladrones Fantasma[n]no lo hubieran conseguido, mi novio[n]y yo no habr胤amos discutido.[n][w][e]

[msg MSG_TOSISABA_010_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Espero que no dijeras algo como[n]或Pobre Akechi位 delante de 姻l.[n][w][e]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Lo has hecho, 夷no?[n][w][e]

[msg MSG_TOSISABA_011_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Por mucho que una intente[n]ocultar las cosas, todo acaba[n]saliendo a la luz...[n][w][e]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Me he dado cuenta al pensar[n]en lo sucedido con Okumura Foods.[n][w][e]

[msg MSG_TOSISABA_011_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]No veo muy acertada la comparaci吋n...[n]En fin, 夷qu姻 edad le dijiste[n]que ten胤as a tu novio?[n][w][e]

[msg MSG_TOSISABA_011_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Le dije que ten胤a quince a隠os menos[n]de los que realmente tengo.[n][w][e]

[msg MSG_TOSISABA_012_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]斡Escucha! 斡Mi novio me ha estado[n]poniendo los cuernos![n][w][e]

[msg MSG_TOSISABA_012_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Bueno, t雨 tambi姻n lo has enga隠ado[n]con lo de tu edad. No creo que[n]tengas derecho a quejarte.[n][w][e]

[msg MSG_TOSISABA_012_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Pero eso es diferente. Les he[n]pedido a los Ladrones Fantasma que[n]despierten su coraz吋n.[n][w][e]

[msg MSG_TOSISABA_012_3_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Uy... Quiz茨 seas t雨 la que necesite[n]que despierten el tuyo.[n][w][e]

[msg MSG_TOSISABA_013_0_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]He visto la rueda de prensa en[n]directo... Voy a tener pesadillas[n]con esos ojos en blanco.[n][w][e]

[msg MSG_TOSISABA_013_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Se lo merece por haber mentido a[n]todo el mundo. Espero que no me[n]pase nunca a m胤...[n][w][e]

[msg MSG_TOSISABA_013_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Mentir sobre tu edad no dice mucho[n]a tu favor. Pide disculpas y todo[n]ir茨 sobre ruedas.[n][w][e]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Pobre hombre. Acabar con su[n]vida ha sido demasiado.[n][w][e]

[msg MSG_TOSISABA_014_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]夷Me investigar茨 Akechi[n]si me vuelvo loca?[n][w][e]

[msg MSG_TOSISABA_014_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]夷Qu姻 dices, mujer? 夷Te ha pasado[n]algo con tu novio?[n][w][e]

[msg MSG_TOSISABA_014_3_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Le he dicho mi verdadera edad[n]y le he pedido disculpas, pero[n]斡no las ha aceptado![n][w][e]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]斡He roto con 姻l! Al final,[n]ser sincera no ha servido de nada.[n][w][e]

[msg MSG_TOSISABA_015_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Pienso olvidarme de los chicos[n]durante una temporada.[n][w][e]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Me meter姻 en pol胤tica. 斡Las mujeres[n]tenemos que ganar peso[n]en esta sociedad![n][w][e]

[msg MSG_TOSISABA_015_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]夷Q-qu姻 te pasa?[n]夷Han despertado tu coraz吋n?[n][w][e]

[msg MSG_TOSISABA_015_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Me voy a presentar voluntaria en la[n]oficina electoral. Seguro que all胤[n]hay un mont吋n de t胤os buenos.[n][w][e]

[msg MSG_TOSISABA_015_3_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Nunca aprender茨s, 夷verdad?[n][w][e]

[msg MSG_TOSISABA_016_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]El suicidio es demasiado...[n]Solo era un ni隠o. Sus padres[n]tienen que estar hechos polvo.[n][w][e]

[msg MSG_TOSISABA_016_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Uy, te ha salido la vena maternal.[n]Tu hija va al instituto, 夷verdad?[n][w][e]

[msg MSG_TOSISABA_016_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Va al Instituto Shujin, y ando[n]preocupada desde que s姻 que[n]los Ladrones Fantasma van all胤.[n][w][e]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Estoy m茨s tranquila[n]desde que atraparon al l胤der,[n]pero sigue siendo chocante...[n][w][e]

[msg MSG_TOSISABA_017_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Ser茨n cosas m胤as, pero...[n][w][e]
[s][vp 8 2 1 0 7 0]夷No te parece que Masayoshi Shido[n]y Akechi se parecen un poco?[n][w][e]

[msg MSG_TOSISABA_017_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]夷C吋mo? Yo no lo veo.[n][w][e]
[s][vp 8 2 1 0 8 0]Eras una gran fan de Akechi.[n]夷Ya te has olvidado de su cara?[n][w][e]

[msg MSG_TOSISABA_017_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]No s姻, me vino de repente cuando[n]miraba un p吋ster de Shido.[n]Habr茨 sido mi imaginaci吋n.[n][w][e]

[msg MSG_TOSISABA_018_0_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Debe de ser horrible ganar las[n]elecciones, caer enfermo y tener[n]que pasar por todo ese mal trago.[n][w][e]

[msg MSG_TOSISABA_018_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Mi coraz吋n tambi姻n sufre...[n][w][e]

[msg MSG_TOSISABA_018_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]斡夷Qu姻?! 斡夷Est茨s enferma?![n][w][e]

[msg MSG_TOSISABA_018_3_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Se acerca la Navidad[n]y no tengo novio...[n][w][e]

[msg MSG_TOSISABA_018_4_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Ser茨s...[n][w][e]

[msg MSG_TOSISABA_019_0_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Oye, se te ve m茨s joven, 夷no?[n]Tienes una piel tan suave...[n][w][e]
[s][vp 8 2 1 0 8 0]夷Te has hecho un tratamiento?[n]夷Usas cremas? 夷Haces ejercicio?[n][w][e]

[msg MSG_TOSISABA_019_1_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]No he hecho nada.[n]Supongo que el 雨nico cambio[n]es que me he echado novio.[n][w][e]
[s][vp 8 2 1 0 7 0]斡Es jovenc胤simo y superguapo![n]斡Estamos en plan tortolitos![n][w][e]

[msg MSG_TOSISABA_019_2_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Uf, seguro que le has dicho[n]que eres m茨s joven.[n]夷Qu姻 edad tiene?[n][w][e]

[msg MSG_TOSISABA_019_3_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]斡La edad de mi hija![n]Quien tuvo, retuvo.[n][w][e]

[msg MSG_TOSISABA_019_4_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]夷E-en serio? 夷No te supone[n]ning雨n problema?[n][w][e]

[msg MSG_TOSISABA_020_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]夷C吋mo le ir茨 a Akechi?[n]Hace mucho que no sale en la tele.[n][w][e]

[msg MSG_TOSISABA_020_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]夷A雨n vas tras 姻l?[n][w][e]

[msg MSG_TOSISABA_020_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Akechi es mi 胤dolo. Paso del grupo[n]ese de Ladrones yo qu姻 s姻 qu姻.[n][w][e]
[s][vp 8 2 1 0 7 0]Quiero decir, todo eso no fue[n]m茨s que un invento, 夷no?[n][w][e]

[msg MSG_TOSISABA_020_3_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]A este paso, te vas a enamorar[n]de alguien bidimensional.[n][w][e]

[msg MSG_TOSISABA_021_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Oye, 夷te acuerdas del novio guapo[n]que me ech姻 hace no mucho?[n]Estoy pensando en cortar con 姻l...[n][w][e]

[msg MSG_TOSISABA_021_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]夷Y por qu姻 no? El atractivo y la[n]juventud no es lo m茨s importante[n]a la hora de elegir pareja.[n][w][e]
[s][vp 8 2 1 0 8 0]Deber胤as despertar y centrarte[n]en alcanzar la felicidad.[n][w][e]

[msg MSG_TOSISABA_021_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]No, no es eso...[n][w][e]
[s][vp 8 2 1 0 7 0]斡Es que he conocido a alguien[n]a雨n mejor! 斡Es igual que Akechi![n][w][e]
[s][vp 8 2 1 0 7 0]斡As胤 que voy a olvidar mi pasado[n]y vivir el futuro![n][w][e]

[msg MSG_TOSISABA_022_0_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]*suspiro* Mi hija se convertir茨 en[n]toda una mujer el a隠o que viene.[n][w][e]

[msg MSG_TOSISABA_022_1_0 [Se隠ora de mediana edad]]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Nadie quiere envejecer, pero no[n]creo que sea algo malo.[n][w][e]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Son los j吋venes quienes deben[n]dar un paso adelante[n]y cambiar el mundo, 夷verdad?[n][w][e]
[s][f 4 23 1 8 3 10 0 10][vp 8 2 1 0 8 0]Al fin puedo relajarme[n]y disfrutar del espect茨culo.[n][w][e]

[msg MSG_TOSISABA_022_2_0 [Mujer de aspecto joven]]
[s][f 4 23 1 7 3 10 0 10][vp 8 2 1 0 7 0]Eso es lo 雨ltimo que yo dir胤a.[n]Yo prefiero ser una mujer[n]inconformista, 夷sabes?[n][w][e]

[msg MSG_AKECHI_000_00 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 8002 65535 0]Ah, si eres t雨. Me alegro de que[n]hayas decidido hablarme.[n][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Como ten胤a algo de tiempo[n]antes de la grabaci吋n,[n]he decidido ir a dar una vuelta.[n][w][e]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]郁ltimamente he o胤do muchos[n]rumores sobre una banda criminal.[n]Espero que no est姻s con ellos.[n][w][e]

[sel SEL_AKECHI_001_00 top]
[s]No te preocupes.[e]
[s]...[e]

[msg MSG_AKECHI_002_00 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 8060 65535 0]Ah, maravilloso.[n][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si necesitas ayuda, no lo dudes.[n]Ya sabes que tengo[n]contactos en la polic胤a.[n][w][e]

[msg MSG_AKECHI_002_01 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 8040 65535 0]夷Va todo bien?[n][w][e]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si necesitas ayuda, no lo dudes.[n]Ya sabes que tengo[n]contactos en la polic胤a.[n][w][e]

[msg MSG_AKECHI_003_00 [Akechi]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 8028 65535 0]Esta ciudad es muy emocionante.[n]Primero, el accidente de metro;[n]ahora, lo de la mafia...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Y no olvidemos a los Ladrones[n]Fantasma. He reflexionado mucho[n]durante el paseo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 8038 65535 0]Ahora que lo pienso, 夷los Ladrones[n]Fantasma fueron a la exposici吋n[n]antes de cometer el delito?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷A qu姻 aspiran? 夷Y qui姻n[n]ser茨 su pr吋ximo objetivo?[n][w][e]

[msg MSG_AKECHI_004_00 [Peatona]]
[s][vp 1 0 0 0 0 0]斡夷No es ese Goro Akechi?![n][w][e]

[msg MSG_AKECHI_005_00 [Mujer emocionada]]
[s][vp 1 0 0 0 0 0]斡S胤胤胤, lo es![n]斡Voy a pedirle una foto![n][w][e]

[msg MSG_AKECHI_006_00 [Akechi]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 8032 65535 0]Parece que 雨ltimamente me[n]reconocen mucho m茨s.[n][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Me gustar胤a quedarme a charlar,[n]pero tengo que irme. Espero[n]que podamos hacerlo pronto.[n][w][e]

[msg MSG_AKECHI_100_00 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ah, por cierto... Hay muchos[n]rumores sobre el aumento[n]de la criminalidad en Shibuya.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hasta a la polic胤a tiene problemas[n]para controlar la situaci吋n.[n]Ser茨 mejor que vayas con cuidado.[n][w][e]

[msg MSG_AKECHI_007_00 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 8002 65535 0]Hola. 夷Vuelves a casa?[n][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]He o胤do rumores sobre un[n]aviso, por lo que he decidido[n]dar una vuelta por Shibuya.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si todo se desarrolla tal y como se[n]dice en 姻l, los Ladrones Fantasma[n]van a volverse muy famosos.[n][w][e]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 8038 65535 0]La inefectividad de la polic胤a[n]solo les dar茨 m茨s seguidores.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No es una buena se隠al. Tendr姻[n]que seguir advirtiendo del peligro[n]que acarrean sus acciones.[n][w][e]

[sel SEL_AKECHI_002_00 top]
[s]No, por favor.[e]
[s]Haz lo que quieras.[e]

[msg MSG_AKECHI_008_00 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 54417 65535 0]Ja, ja. A veces olvido[n]que eres seguidor suyo.[n][w][e]

[msg MSG_AKECHI_008_01 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 8020 65535 0]Desde luego.[n][w][e]

[msg MSG_AKECHI_009_00 [Akechi]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 54406 65535 0]A prop吋sito, creo que pronto[n]suceder茨 algo gordo[n]con los Ladrones Fantasma.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Con la informaci吋n[n]de la que dispongo,[n]solo es una hip吋tesis, pero...[n][w][e]

[msg MSG_AKECHI_010_00 [Peatona]]
[s][vp 1 0 0 0 0 0]斡夷No es ese Goro Akechi?![n][w][e]

[msg MSG_AKECHI_011_00 [Mujer emocionada]]
[s][vp 1 0 0 0 0 0]斡S胤胤胤, lo es![n]斡Voy a pedirle una foto![n][w][e]

[msg MSG_AKECHI_012_00 [Akechi]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh, disc雨lpame. Si me quedo[n]hablando con ellas, llegar姻[n]tarde a la grabaci吋n.[n][w][e]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 8053 65535 0]Que vaya bien.[n]Espero verte pronto.[n][w][e]

[msg MSG_OOYA_001_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 16001 65535 0]Oye, yo te conozco.[n][w][e]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 16057 65535 0]Ah, eres el cr胤o que estaba en[n]casa de Madarame.[n]夷Conseguiste algo interesante?[n][w][e]

[sel SEL_OOYA_002_0_0 top]
[s]Qu姻 va.[e]
[s]No te lo voy a decir.[e]

[msg MSG_OOYA_003_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ya veo. Bueno, av胤same si[n]te enteras de algo interesante.[n][w][e]

[msg MSG_OOYA_004_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]A m胤 no me enga隠as.[n]Yo creo que no tienes nada.[n][w][e]

[msg MSG_OOYA_005_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estoy cubriendo la exposici吋n. No[n]es que me interese, pero eso es[n]lo que pasa cuando tienes jefe.[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ja, 夷por qu姻[n]te lo estoy explicando?[n]Deber胤a volver al tajo.[n][w][e]

[msg MSG_OOYA_006_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1038 0 0]Esta es la mujer que ha aparecido[n]en la casa de Madarame...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Dijo que era periodista. Imagino[n]que estar胤a escribiendo un art胤culo[n]sobre 姻l o algo por el estilo.[n][w][e]

[msg MSG_OOYA_007_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 16006 65535 0]Ah, nos volvemos a encontrar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hay tantos estudiantes por aqu胤...[n]Me siento como un pez[n]fuera del agua.[n][w][e]

[sel SEL_OOYA_008_0_0 top]
[s]夷Trabajas aqu胤?[e]
[s]Pareces ocupada.[e]

[msg MSG_OOYA_009_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estoy cubriendo la exposici吋n. No[n]es que me interese, pero eso es[n]lo que pasa cuando tienes jefe.[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ja, 夷por qu姻[n]te lo estoy explicando?[n]Deber胤a volver al tajo.[n][w][e]

[msg MSG_OOYA_010_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 8 10 0 10][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 16108 65535 0]Apenas puedo dormir con lo de[n]los episodios de descontrol, Medjed[n]y los Ladrones Fantasma...[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Shibuya no es para m胤... Creo lo dejar姻[n]por hoy. Me apetece un trago.[n][w][e]

[msg MSG_OOYA_011_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 16001 65535 0]Oye, yo te conozco.[n][w][e]
[s][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 16057 65535 0]Ah, eres el cr胤o que estaba en[n]casa de Madarame.[n]夷Conseguiste algo interesante?[n][w][e]

[sel SEL_OOYA_012_0_0 top]
[s]Qu姻 va.[e]
[s]No te lo voy a decir.[e]

[msg MSG_OOYA_013_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Ya veo. Bueno, av胤same si[n]te enteras de algo interesante.[n][w][e]

[msg MSG_OOYA_014_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]A m胤 no me enga隠as.[n]Yo creo que no tienes nada.[n][w][e]

[msg MSG_OOYA_015_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estoy aqu胤 por trabajo.[n]He le胤do un rumor muy interesante[n]en internet.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Parece que alguien le ha dejado[n]un 或aviso位 a Madarame y he venido[n]para conseguir la exclusiva.[n][w][e]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]He intentado conseguir una[n]entrevista, pero nadie dice nada.[n]Puede que el rumor sea falso...[n][w][e]

[msg MSG_MORGANA_015_5_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1038 0 0]Esta es la mujer que ha aparecido[n]en la casa de Madarame...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Dijo que era periodista. Imagino[n]que estar胤a escribiendo un art胤culo[n]sobre 姻l o algo por el estilo.[n][w][e]

[msg MSG_OOYA_016_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 16002 65535 0]Eh, eres t雨. Ya que est茨s aqu胤,[n]te pregunto a ti tambi姻n.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Sabes algo sobre ese 或aviso位[n]para Madarame?[n][w][e]

[sel SEL_OOYA_017_0_0 top]
[s]Quiz茨s.[e]
[s]Ni p胤o.[e]

[msg MSG_OOYA_018_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 3 10 0 10][bup 0 107 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Conque s胤 que sabes algo.[n][w][e]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Lo hab胤a visto por internet,[n]as胤 que he venido pitando[n]para conseguir la exclusiva.[n][w][e]

[msg MSG_OOYA_019_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 8 10 0 10][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Vaya, parece que solo era[n]un comentario m茨s entre los muchos[n]que hay en internet.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Algo sobre un 或aviso位 para[n]Madarame. He venido pitando[n]para conseguir la exclusiva.[n][w][e]

[msg MSG_OOYA_020_0_0 [Mujer con c茨mara]]
[s][bup 0 107 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]He hablado con todos los empleados[n]de la exhibici吋n, pero nadie sabe[n]nada. 夷Me la habr茨n colado?[n][w][e]

[msg MSG_OOYA_022_0_0 [Mujer con c茨mara]]
[s][f 4 23 1 65535 8 10 0 10][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 16021 65535 0]Pero con el l胤o que se ha armado[n]alrededor del cuadro 或Sayuri位,[n]dudo que sea una coincidencia.[n][w][e]

[msg MSG_BIKOU01_001_0_0 [Makoto]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 2120 65535 0]Ah... Qu姻 casualidad.[n]夷Tambi姻n vas a casa?[n][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sakamoto y Takamaki no est茨n[n]contigo. Por cierto, parece[n]que sois buenos amigos.[n][w][e]

[msg MSG_BIKOU01_002_0_0 [Makoto]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2129 65535 0]Ve directo a casa si puedes.[n]郁ltimamente hay mucha[n]delincuencia por aqu胤.[n][w][e]

[msg MSG_BIKOU02_001_0_0 [Makoto]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 2129 65535 0]V-vaya, qu姻 coincidencia.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No ir胤as de nuevo...[n]al lugar de los hechos, 夷verdad?[n][w][e]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 2087 65535 0]Mmm, c吋mo me gusta este libro.[n]No puedo dejar de leer. Espero que[n]el pr吋ximo volumen salga pronto.[n][w][e]

[msg MSG_BIKOU02_002_0_0 [Makoto]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 2028 65535 0]S胤 que hay gente en Shibuya.[n]No puedo perder de vista a...[n][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Oh... no me hagas caso.[n]Estaba hablando sola.[n][w][e]

[msg MSG_GRT_main_All_001_01_ [Makoto]]
[s][vp 9 2 65535 41352 0 0]Es imposible salir ileso[n]si te ves envuelto[n]en uno de esos incidentes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_002 [Makoto]]
[s][vp 9 2 65535 42762 0 0]Es terrible. Lo mejor es que[n]lo olvidemos todo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_003 [Makoto]]
[s][vp 9 2 65535 39305 0 0]Ah, eso... Me imaginaba[n]que se encargar胤a otra persona.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_004 [Makoto]]
[s][vp 9 2 65535 40154 0 0]Tengo mucho que hacer,[n]pero mi cerebro est茨 de vacaciones.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_005 [Makoto]]
[s][vp 9 2 65535 40905 0 0]No me acuerdo.[n]No era problema m胤o.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_006 [Makoto]]
[s][vp 9 2 65535 38805 0 0]Por m胤, que hagan lo que quieran.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_007 [Makoto]]
[s][vp 9 2 65535 37752 0 0]Puf, 夷por qu姻 tengo que hacerlo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_02_ [Makoto]]
[s][vp 9 2 65535 37651 0 0]No es normal[n]no acordarse de nada despu姻s.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_03_ [Makoto]]
[s][vp 9 2 65535 43411 0 0]Lo voy a dejar a medias.[n]Las cosas saldr茨n bien[n]de una forma u otra.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_501_12_ [Makoto]]
[s][vp 9 2 65535 41452 0 0]Nunca pasa nada bueno...[n]Alguien deber胤a hacer[n]algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_04_ [Makoto]]
[s][vp 9 2 65535 38002 0 0]夷Por qu姻 es tan horrible el mundo?[n]Seguro que alguien tiene la culpa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_501_14_ [Makoto]]
[s][vp 9 2 65535 37552 0 0]Me aburro como una ostra.[n]夷No hay ning雨n sitio[n]divertido al que ir?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_008 [Makoto]]
[s][vp 9 2 65535 40255 0 0]夷No se podr胤a haber evitado[n]ese accidente?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_001_009 [Makoto]]
[s][vp 9 2 65535 41202 0 0]Me alegro de no ir en ese tren.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_01_ [Makoto]]
[s][vp 9 2 65535 46252 0 0]No tiene sentido pensarlo.[n]Aunque lo deje a medias,[n]no me pasar茨 nada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_04_ [Makoto]]
[s][vp 9 2 65535 40602 0 0]夷Ahora qu姻 va a pasar?[n]Es todo muy desconcertante.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_02_ [Makoto]]
[s][vp 9 2 65535 38352 0 0]夷Por qu姻 es tan horrible el mundo?[n]Seguro que alguien tiene la culpa...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_06_ [Makoto]]
[s][vp 9 2 65535 37902 0 0]夷Por qu姻 los pol胤ticos no mueven[n]ni un dedo? Menuda panda[n]de impresentables.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_03_ [Makoto]]
[s][vp 9 2 65535 41952 0 0]夷Qui姻n tiene la culpa[n]de que el mundo sea as胤?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_12_ [Makoto]]
[s][vp 9 2 65535 38355 0 0]He o胤do que su personalidad[n]cambi吋 de repente[n]y que no recuerda lo que hizo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_04_ [Makoto]]
[s][vp 9 2 65535 39952 0 0]夷Por qu姻 no pasa nunca nada bueno?[n]Que alguien tome cartas[n]en el asunto...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_502_13_ [Makoto]]
[s][vp 9 2 65535 37801 0 0]El mundo es un lugar horrible.[n]夷De qui姻n es la culpa?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_001 [Makoto]]
[s][vp 9 2 65535 40605 0 0]夷Qu姻 ha pasado?[n]夷Han arrestado a alguien?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_002 [Makoto]]
[s][vp 9 2 65535 40155 0 0]Me da igual, no es problema m胤o.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_002_003 [Makoto]]
[s][vp 9 2 65535 39655 0 0]夷Qu姻 le pasa a Jap吋n? Ja, ja, ja...[n]Que alguien nos ayude...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_01_ [Makoto]]
[s][vp 9 2 65535 41505 0 0]No entiendo por qu姻[n]confes吋 de repente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_04_ [Makoto]]
[s][vp 9 2 65535 38904 0 0]Se aprovechaba[n]de las chicas del equipo.[n]Qu姻 asco de t胤o.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_02_ [Makoto]]
[s][vp 9 2 65535 44209 0 0]No me puedo creer que acosara[n]sexualmente a esas chicas.[n]Menuda forma de abusar de su poder.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_06_ [Makoto]]
[s][vp 9 2 65535 39053 0 0]Qu姻 rabia que el medallista de oro[n]fuera un pervertido de tomo y lomo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_03_ [Makoto]]
[s][vp 9 2 65535 44905 0 0]No entiendo por qu姻[n]confes吋 de repente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_12_ [Makoto]]
[s][vp 9 2 65535 38351 0 0]Qu姻 rabia que el medallista de oro[n]fuera un pervertido de tomo y lomo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_04_ [Makoto]]
[s][vp 9 2 65535 46059 0 0]No me puedo creer que acosara[n]sexualmente a esas chicas.[n]Menuda forma de abusar de su poder.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_503_13_ [Makoto]]
[s][vp 9 2 65535 38451 0 0]Medallista de oro o no,[n]hasta aqu胤 ha llegado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_001 [Makoto]]
[s][vp 9 2 65535 39800 0 0]Seguro que disfrutaba[n]abusando de su poder.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_002 [Makoto]]
[s][vp 9 2 65535 40902 0 0]Lo he visto jugar antes.[n]No me lo puedo creer...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_003 [Makoto]]
[s][vp 9 2 65535 40250 0 0]斡夷Te has enterado de lo del[n]medallista de oro?! 斡Qu姻 asco![n][f 1 2 180][e]

[msg MSG_GRT_main_All_003_004 [Makoto]]
[s][vp 9 2 65535 40952 0 0]Uf, es lo 雨nico que les importa[n]a los hombres...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_01_ [Makoto]]
[s][vp 9 2 65535 46003 0 0]Lo he visto por la tele.[n]Su arte es bastante bueno.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_02_ [Makoto]]
[s][vp 9 2 65535 45454 0 0]Han dicho en la tele[n]que el pintor va a hacer[n]una exposici吋n en solitario.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_03_ [Makoto]]
[s][vp 9 2 65535 38803 0 0]Lo he visto por la tele.[n]Su arte es bastante bueno.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_04_ [Makoto]]
[s][vp 9 2 65535 40955 0 0]Han dicho en la tele[n]que el pintor va a hacer[n]una exposici吋n en solitario.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_05_ [Makoto]]
[s][vp 9 2 65535 41504 0 0]He visto el nombre de Madarame[n]en alg雨n sitio hace poco.[n]Puede que en las noticias...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_004_06_ [Makoto]]
[s][vp 9 2 65535 42003 0 0]Es muy popular.[n]Quiero apuntar a mi hijo a clases[n]de pintura de estilo japon姻s.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_01_ [Makoto]]
[s][vp 9 2 65535 41505 0 0]Se rumorea que ahora mismo[n]Shibuya es un sitio peligroso.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_02_ [Makoto]]
[s][vp 9 2 65535 39654 0 0]No dejan de llegarme correos raros...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_03_ [Makoto]]
[s][vp 9 2 65535 46004 0 0]Dicen que te amenazan sin parar[n]despu姻s de chantajearte.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_04_ [Makoto]]
[s][vp 9 2 65535 46105 0 0]Se comenta que muchas[n]de las v胤ctimas son gente joven.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_05_ [Makoto]]
[s][vp 9 2 65535 40952 0 0]No quiero quedarme por aqu胤 mucho.[n]Dicen que no es seguro.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_005_06_ [Makoto]]
[s][vp 9 2 65535 41604 0 0]Ah, s胤, me he enterado.[n]Lo de las estafas, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_01_ [Makoto]]
[s][vp 9 2 65535 37604 0 0]Resulta desconcertante[n]que no sepamos la causa[n]de los episodios de descontrol.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_02_ [Makoto]]
[s][vp 9 2 65535 44504 0 0]夷Es cosa m胤a o el n雨mero[n]de incidentes raros ha disminuido?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_03_ [Makoto]]
[s][vp 9 2 65535 46302 0 0]Las cosas se han calmado un poco,[n]pero seguro que vuelven a ocurrir.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_203_04_ [Makoto]]
[s][vp 9 2 65535 38600 0 0]Ahora que lo pienso,[n]雨ltimamente no he vuelto a o胤r[n]nada sobre los incidentes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_01_ [Makoto]]
[s][vp 9 2 65535 46300 0 0]Cualquier adulto que se precie[n]entiende algo de arte.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_02_ [Makoto]]
[s][vp 9 2 65535 46054 0 0]夷La exposici吋n de Madarame[n]no est茨 por aqu胤?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_03_ [Makoto]]
[s][vp 9 2 65535 37603 0 0]Fue un placer para la vista.[n]Sus obras son mucho m茨s[n]impresionantes de cerca.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_204_04_ [Makoto]]
[s][vp 9 2 65535 38602 0 0]Qu姻 pena que no tengan el 或Sayuri位...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_01_ [Makoto]]
[s][vp 9 2 65535 37605 0 0]Lo de que lo anunciaron[n]antes de que pasara[n]es una patra隠a, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_04_ [Makoto]]
[s][vp 9 2 65535 37701 0 0]Era agradable y todo un caballero.[n]No puedo creer que me enga隠ara.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_02_ [Makoto]]
[s][vp 9 2 65535 39004 0 0]Seguro que Madarame no es el 雨nico[n]mal t胤o que hay por ah胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_06_ [Makoto]]
[s][vp 9 2 65535 37902 0 0]Es penoso que un hombre hecho[n]y derecho llore como un cr胤o.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_03_ [Makoto]]
[s][vp 9 2 65535 45655 0 0]Entonces el famoso artista[n]solo era un estafador.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_12_ [Makoto]]
[s][vp 9 2 65535 38351 0 0]夷Por qu姻 lo confes吋 de pronto?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_04_ [Makoto]]
[s][vp 9 2 65535 38601 0 0]Qu姻 horror. No me puedo[n]creer que se ganara la vida robando[n]el trabajo de los dem茨s.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_506_14_ [Makoto]]
[s][vp 9 2 65535 38502 0 0]夷Ladrones Fantasma?[n]夷De qu姻 est茨s hablando?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_005 [Makoto]]
[s][vp 9 2 65535 38903 0 0]Su vida est茨 totalmente acabada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_006 [Makoto]]
[s][vp 9 2 65535 38752 0 0]Incluso un viejo como ese[n]solo piensa en dinero.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_007 [Makoto]]
[s][vp 9 2 65535 39053 0 0]Tanto Madarame como los Ladrones[n]Fantasma son ladrones.[n]Menuda iron胤a.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_006_008 [Makoto]]
[s][vp 9 2 65535 38055 0 0]Ese es el artista[n]que abri吋 la exposici吋n, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_01_ [Makoto]]
[s][vp 9 2 65535 43404 0 0]Hay gente chunga que intenta[n]extorsionar a estudiantes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_02_ [Makoto]]
[s][vp 9 2 65535 41559 0 0]Hay tanta extorsi吋n y tantos[n]fraudes... 夷Es que la polic胤a[n]no hace nada?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_03_ [Makoto]]
[s][vp 9 2 65535 38504 0 0]Hay gente chunga que intenta[n]extorsionar a estudiantes...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_04_ [Makoto]]
[s][vp 9 2 65535 39359 0 0]Hay tanta extorsi吋n y tantos[n]fraudes... 夷Es que la polic胤a[n]no hace nada?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_05_ [Makoto]]
[s][vp 9 2 65535 38102 0 0]斡No quiero que me chantajeen![n]Shibuya da mucho miedo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_007_06_ [Makoto]]
[s][vp 9 2 65535 40051 0 0]He o胤do que est茨n yendo[n]a por estudiantes.[n]Me preocupa mi hijo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_01_ [Makoto]]
[s][vp 9 2 65535 41605 0 0]夷Un aviso de los Ladrones Fantasma?[n]Es una broma inofensiva.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_508_04_ [Makoto]]
[s][vp 9 2 65535 37705 0 0]Ser胤a muy interesante[n]que los avisos fueran reales.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_02_ [Makoto]]
[s][vp 9 2 65535 38055 0 0]As胤 que los Ladrones Fantasma, 夷eh?[n]夷Crees que existen de verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_508_06_ [Makoto]]
[s][vp 9 2 65535 37905 0 0]Ni de co隠a los Ladrones Fantasma[n]existen de verdad.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_03_ [Makoto]]
[s][vp 9 2 65535 43755 0 0]夷Un aviso de los Ladrones Fantasma?[n]Es una broma inofensiva.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_508_12_ [Makoto]]
[s][vp 9 2 65535 38355 0 0]Espera, 夷qui姻n es Kaneshiro?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_04_ [Makoto]]
[s][vp 9 2 65535 39005 0 0]As胤 que los Ladrones Fantasma, 夷eh?[n]夷Crees que existen de verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_508_14_ [Makoto]]
[s][vp 9 2 65535 38504 0 0]夷Cu茨ndo va a hacer[n]la polic胤a su trabajo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_005 [Makoto]]
[s][vp 9 2 65535 40102 0 0]夷Los Ladrones Fantasma?[n]Qu姻 malotes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_006 [Makoto]]
[s][vp 9 2 65535 40450 0 0]夷Un aviso? 斡Parece que[n]lo han sacado de un manga![n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_007 [Makoto]]
[s][vp 9 2 65535 40054 0 0]斡S胤, un aviso![n]Esto va a ser interesante.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_008_008 [Makoto]]
[s][vp 9 2 65535 38709 0 0]Anda ya, est茨 m茨s claro que el agua[n]que es una broma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_01_ [Makoto]]
[s][vp 9 2 65535 41204 0 0]斡Me he enterado[n]de que han detenido a la mafia![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_02_ [Makoto]]
[s][vp 9 2 65535 40050 0 0]Me alegro de que esos delincuentes[n]ya no est姻n en Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_03_ [Makoto]]
[s][vp 9 2 65535 46304 0 0]斡Hac胤a mucho tiempo que no[n]recib胤a una noticia tan buena![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_05_ [Makoto]]
[s][vp 9 2 65535 41304 0 0]Me alegro de que esos delincuentes[n]ya no est姻n en Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_04_ [Makoto]]
[s][vp 9 2 65535 41304 0 0]Me alegro de que esos delincuentes[n]ya no est姻n en Shibuya.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_06_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]斡Menos mal que todo se ha resuelto![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_07_ [Makoto]]
[s][vp 9 2 65535 41550 0 0]斡Por fin puedo salir por Shibuya[n]otra vez sin preocuparme![n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_08_ [Makoto]]
[s][vp 9 2 65535 38404 0 0]No me puedo creer que la mafia[n]estuviera por aqu胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_09_ [Makoto]]
[s][vp 9 2 65535 40050 0 0]Me alegro de que los pillaran.[n]Las cosas se estaban poniendo feas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_009_10_ [Makoto]]
[s][vp 9 2 65535 41703 0 0]斡Qu姻 bien me siento![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_01_ [Makoto]]
[s][vp 9 2 65535 46006 0 0]Parece que lo de los Ladrones[n]Fantasma no es ninguna patra隠a.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_02_ [Makoto]]
[s][vp 9 2 65535 39700 0 0]Los Ladrones Fantasma esos[n]son los que han resuelto[n]el asunto, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_03_ [Makoto]]
[s][vp 9 2 65535 43403 0 0]Parece que lo de los Ladrones[n]Fantasma no es ninguna patra隠a.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_04_ [Makoto]]
[s][vp 9 2 65535 37756 0 0]Los Ladrones Fantasma esos[n]son los que han resuelto[n]el asunto, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_05_ [Makoto]]
[s][vp 9 2 65535 40250 0 0]As胤 que el aviso era de verdad.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_06_ [Makoto]]
[s][vp 9 2 65535 40105 0 0]El nombre de los Ladrones Fantasma[n]da un poco de repel雨s,[n]pero han hecho un buen trabajo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_07_ [Makoto]]
[s][vp 9 2 65535 37703 0 0]斡He visto las noticias![n]Los Ladrones Fantasma, 夷eh?[n]斡Qu姻 emocionante![n][f 1 2 180][e]

[msg MSG_GRT_main_All_010_08_ [Makoto]]
[s][vp 9 2 65535 38754 0 0]夷Todav胤a no saben qui姻nes son[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_01_ [Makoto]]
[s][vp 9 2 65535 39804 0 0]Se los ve bastante preocupados[n]por los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_511_04_ [Makoto]]
[s][vp 9 2 65535 37704 0 0]Se han cebado mucho con[n]los Ladrones Fantasma.[n]Me pregunto qu姻 har茨n ahora...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_02_ [Makoto]]
[s][vp 9 2 65535 40255 0 0]夷Van a permitir que Medjed campe[n]a sus anchas tras haber dicho eso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_511_06_ [Makoto]]
[s][vp 9 2 65535 37905 0 0]或Los Ladrones Fantasma imparten[n]una justicia falsa位.[n]夷Qu姻 significa eso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_03_ [Makoto]]
[s][vp 9 2 65535 40304 0 0]Se los ve bastante preocupados[n]por los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_511_12_ [Makoto]]
[s][vp 9 2 65535 38355 0 0]Lo 雨nico que hacen es provocarlos.[n]夷Qu姻 har茨n los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_04_ [Makoto]]
[s][vp 9 2 65535 41554 0 0]夷Van a permitir que Medjed campe[n]a sus anchas tras haber dicho eso?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_511_14_ [Makoto]]
[s][vp 9 2 65535 38505 0 0]夷A qu姻 narices se refieren cuando[n]dicen que los Ladrones Fantasma[n]imparten una justicia falsa? [n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_05_ [Makoto]]
[s][vp 9 2 65535 39109 0 0]Los Ladrones Fantasma y Medjed[n]son terribles.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_06_ [Makoto]]
[s][vp 9 2 65535 40453 0 0]斡夷Responder茨n los Ladrones[n]Fantasma?! 斡Molar胤a mucho[n]que se enfrentaran![n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_07_ [Makoto]]
[s][vp 9 2 65535 40550 0 0]夷De parte de qui姻n est茨s?[n]夷De los Ladrones Fantasma[n]o de Medjed?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_011_08_ [Makoto]]
[s][vp 9 2 65535 41305 0 0]Parece que mucha gente[n]habla de los Ladrones Fantasma[n]雨ltimamente.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_01_ [Makoto]]
[s][vp 9 2 65535 39505 0 0]夷Qu姻 pueden hacer los Ladrones[n]Fantasma contra esos hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_512_04_ [Makoto]]
[s][vp 9 2 65535 37704 0 0]Tienen a Jap吋n en el punto de mira.[n]Espero que hagan algo al respecto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_02_ [Makoto]]
[s][vp 9 2 65535 39305 0 0]Si los Ladrones Fantasma[n]revelan su verdadera identidad,[n]no nos har茨n nada, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_512_06_ [Makoto]]
[s][vp 9 2 65535 37903 0 0]斡Nuestra econom胤a no podr胤a[n]soportar 或da隠os devastadores位![n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_03_ [Makoto]]
[s][vp 9 2 65535 41756 0 0]夷Qu姻 pueden hacer los Ladrones[n]Fantasma contra esos hackers?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_512_12_ [Makoto]]
[s][vp 9 2 65535 38354 0 0]Si los Ladrones Fantasma revelan[n]su identidad, 夷nos dejar茨n en paz?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_04_ [Makoto]]
[s][vp 9 2 65535 41305 0 0]Si los Ladrones Fantasma[n]revelan su verdadera identidad,[n]no nos har茨n nada, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_512_14_ [Makoto]]
[s][vp 9 2 65535 38501 0 0]夷Van a actuar[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_05_ [Makoto]]
[s][vp 9 2 65535 41559 0 0]夷Los Ladrones Fantasma existen?[n]Todav胤a no han aparecido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_06_ [Makoto]]
[s][vp 9 2 65535 41951 0 0]Si la econom胤a se ve afectada,[n]ser茨 culpa de los Ladrones[n]Fantasma, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_07_ [Makoto]]
[s][vp 9 2 65535 41002 0 0]No s姻 si Jap吋n deber胤a depender[n]tanto de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_012_08_ [Makoto]]
[s][vp 9 2 65535 41305 0 0]Si derrotaron a la mafia, seguro[n]que pueden con un grupo de hackers.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_01_ [Makoto]]
[s][vp 9 2 65535 38500 0 0]Me alegro de que[n]se hayan encargado del tema[n]antes de que nos pasara nada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_02_ [Makoto]]
[s][vp 9 2 65535 41304 0 0]Parece que los hackers[n]de los que habla todo el mundo[n]han cerrado su web.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_03_ [Makoto]]
[s][vp 9 2 65535 41750 0 0]Me alegro de que[n]se hayan encargado del tema[n]antes de que nos pasara nada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_04_ [Makoto]]
[s][vp 9 2 65535 45454 0 0]Parece que los hackers[n]de los que habla todo el mundo[n]han cerrado su web.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_05_ [Makoto]]
[s][vp 9 2 65535 38600 0 0]No ha pasado nada, 夷verdad?[n]Menos mal.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_06_ [Makoto]]
[s][vp 9 2 65535 38750 0 0]As胤 que se acab吋 Medjed.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_07_ [Makoto]]
[s][vp 9 2 65535 39752 0 0]Aj茨. Supongo que esos hackers[n]no ten胤an ni una posibilidad.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_013_08_ [Makoto]]
[s][vp 9 2 65535 45454 0 0]斡Toma! 斡Medjed ha ca胤do![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_01_ [Makoto]]
[s][vp 9 2 65535 41600 0 0]斡Me alegra que podamos contar[n]con los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_02_ [Makoto]]
[s][vp 9 2 65535 37756 0 0]斡Al final resulta que los Ladrones[n]Fantasma son los buenos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_03_ [Makoto]]
[s][vp 9 2 65535 39106 0 0]斡Me alegra que podamos contar[n]con los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_04_ [Makoto]]
[s][vp 9 2 65535 45453 0 0]斡S胤! 斡Sab胤a que los Ladrones[n]Fantasma ten胤an raz吋n![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_05_ [Makoto]]
[s][vp 9 2 65535 39756 0 0]斡Lo han conseguido![n]斡Los Ladrones Fantasma[n]han salvado Jap吋n![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_06_ [Makoto]]
[s][vp 9 2 65535 39703 0 0]Los Ladrones Fantasma[n]son imparables.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_07_ [Makoto]]
[s][vp 9 2 65535 40206 0 0]斡Me encantan los Ladrones Fantasma![n]斡Han acabado con Medjed![n][f 1 2 180][e]

[msg MSG_GRT_main_All_014_08_ [Makoto]]
[s][vp 9 2 65535 40154 0 0]Han derrotado a los hackers...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_01_ [Makoto]]
[s][vp 9 2 65535 41353 0 0]Hasta los de la oficina[n]hablan sobre los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_515_04_ [Makoto]]
[s][vp 9 2 65535 37706 0 0]Ahora venden productos de los[n]Ladrones Fantasma, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_02_ [Makoto]]
[s][vp 9 2 65535 39006 0 0]Admiro much胤simo a los h姻roes as胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_515_06_ [Makoto]]
[s][vp 9 2 65535 37906 0 0]斡Vivan los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_03_ [Makoto]]
[s][vp 9 2 65535 46303 0 0]Toda mi familia es fan[n]de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_515_12_ [Makoto]]
[s][vp 9 2 65535 38356 0 0]斡Me encantar胤a conocer[n]a los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_04_ [Makoto]]
[s][vp 9 2 65535 45106 0 0]斡Los Ladrones Fantasma[n]son una pasada![n][f 1 2 180][e]

[msg MSG_GRT_main_All_515_14_ [Makoto]]
[s][vp 9 2 65535 38506 0 0]斡Vivan los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_05_ [Makoto]]
[s][vp 9 2 65535 40306 0 0]Todo Jap吋n habla[n]de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_06_ [Makoto]]
[s][vp 9 2 65535 37700 0 0]斡Mira! Es la p茨gina web[n]de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_07_ [Makoto]]
[s][vp 9 2 65535 37904 0 0]Me encanta lo misteriosos que son.[n]斡Molan un mont吋n![n][f 1 2 180][e]

[msg MSG_GRT_main_All_015_08_ [Makoto]]
[s][vp 9 2 65535 38906 0 0]斡No puedo creer que haya[n]superh姻roes en la vida real![n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_01_ [Makoto]]
[s][vp 9 2 65535 37554 0 0]La empresa creci吋 muy r茨pido,[n]pero ahora sabemos lo que pasaba[n]entre bambalinas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_516_04_ [Makoto]]
[s][vp 9 2 65535 37705 0 0]夷Okumura Foods? 夷La empresa[n]propietaria de Big Bang Burger?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_02_ [Makoto]]
[s][vp 9 2 65535 46104 0 0]Nunca me habr胤a imaginado[n]que Okumura Foods[n]fuera tan terrible...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_516_06_ [Makoto]]
[s][vp 9 2 65535 37901 0 0]La empresa creci吋 muy r茨pido,[n]pero ahora sabemos lo que pasaba[n]entre bambalinas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_03_ [Makoto]]
[s][vp 9 2 65535 41051 0 0]La empresa creci吋 muy r茨pido,[n]pero ahora sabemos lo que pasaba[n]entre bambalinas...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_516_12_ [Makoto]]
[s][vp 9 2 65535 38352 0 0]Es horrible que tratasen[n]a sus empleados como esclavos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_04_ [Makoto]]
[s][vp 9 2 65535 46054 0 0]Parece que el presidente[n]Okumura ha hecho cosas horribles.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_516_14_ [Makoto]]
[s][vp 9 2 65535 38501 0 0]He visto en la tele[n]que los empleados se sublevaron.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_05_ [Makoto]]
[s][vp 9 2 65535 38902 0 0]夷Viste la imagen del trabajador[n]de Okumura Foods? Qu姻 horror.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_06_ [Makoto]]
[s][vp 9 2 65535 39102 0 0]夷De verdad est茨 tan mal[n]Big Bang Burger? Madre m胤a...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_07_ [Makoto]]
[s][vp 9 2 65535 38251 0 0]Me gustaba Big Bang Burger,[n]pero ahora no puedo[n]ni pensar en comer ah胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_016_08_ [Makoto]]
[s][vp 9 2 65535 38450 0 0]Nunca pens姻 que las empresas[n]har胤an ese tipo de cosas.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_01_ [Makoto]]
[s][vp 9 2 65535 37553 0 0]Me pregunto qui姻n ser茨[n]su pr吋ximo objetivo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_517_03_ [Makoto]]
[s][vp 9 2 65535 37656 0 0]No pasa nada...[n]斡Los Ladrones Fantasma[n]se encargar茨n de eso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_02_ [Makoto]]
[s][vp 9 2 65535 41006 0 0]夷Crees que ir茨n ahora[n]a por el presidente Okumura?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_517_06_ [Makoto]]
[s][vp 9 2 65535 37900 0 0]斡Los Ladrones Fantasma seguir茨n[n]luchando contra los villanos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_03_ [Makoto]]
[s][vp 9 2 65535 43756 0 0]Me pregunto qui姻n ser茨[n]su pr吋ximo objetivo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_517_12_ [Makoto]]
[s][vp 9 2 65535 38356 0 0]Si vais a arreglar el mundo,[n]斡poneos manos a la obra![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_04_ [Makoto]]
[s][vp 9 2 65535 41153 0 0]Espero que los Ladrones Fantasma[n]logren reformar la sociedad.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_517_14_ [Makoto]]
[s][vp 9 2 65535 38506 0 0]Hay muchas personas malas[n]en el mundo.[n]斡Espero que las reformen a todas![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_05_ [Makoto]]
[s][vp 9 2 65535 39606 0 0]夷No se supone que los Ladrones[n]Fantasma tienen que hacer algo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_06_ [Makoto]]
[s][vp 9 2 65535 38754 0 0]Lo del Big Bang Burger se est茨[n]yendo de madre. 夷D吋nde est茨n[n]los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_07_ [Makoto]]
[s][vp 9 2 65535 38206 0 0]斡Vamos, Ladrones Fantasma![n]斡Haced algo con Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_017_08_ [Makoto]]
[s][vp 9 2 65535 39306 0 0]斡Los Ladrones Fantasma[n]tomar茨n cartas en el asunto![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_01_ [Makoto]]
[s][vp 9 2 65535 40906 0 0]斡Ese CEO avaricioso se merece[n]estar en el punto de mira![n][f 1 2 180][e]

[msg MSG_GRT_main_All_518_03_ [Makoto]]
[s][vp 9 2 65535 37650 0 0]斡Estaba deseando que los Ladrones[n]Fantasma enviaran otro aviso![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_02_ [Makoto]]
[s][vp 9 2 65535 45253 0 0]斡Sab胤a que los Ladrones[n]Fantasma iban a ir[n]a por el presidente Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_518_06_ [Makoto]]
[s][vp 9 2 65535 37903 0 0]斡Nadie puede escapar[n]de los Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_03_ [Makoto]]
[s][vp 9 2 65535 43400 0 0]斡Acabad ya con el CEO ese![n]斡Contamos con vosotros,[n]Ladrones Fantasma![n][f 1 2 180][e]

[msg MSG_GRT_main_All_518_12_ [Makoto]]
[s][vp 9 2 65535 38356 0 0]斡S胤, Ladrones Fantasma![n]斡Dadles para el pelo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_04_ [Makoto]]
[s][vp 9 2 65535 41656 0 0]斡Por fin el presidente Okumura[n]se va a llevar su merecido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_518_14_ [Makoto]]
[s][vp 9 2 65535 38503 0 0]斡Qu姻 ganas tengo de ver la rueda[n]de prensa de Okumura! [n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_05_ [Makoto]]
[s][vp 9 2 65535 38903 0 0]斡S胤胤胤, quiero ver a Okumura[n]llorando como un beb姻 por la tele![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_06_ [Makoto]]
[s][vp 9 2 65535 37856 0 0]斡Estaba esperando esto![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_07_ [Makoto]]
[s][vp 9 2 65535 37556 0 0]斡Lo sab胤a! 斡Sab胤a que los Ladrones[n]Fantasma iban a lograrlo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_018_08_ [Makoto]]
[s][vp 9 2 65535 38351 0 0]El aviso que le enviaron[n]demuestra que Okumura[n]no es trigo limpio...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_01_ [Makoto]]
[s][vp 9 2 65535 40901 0 0]斡夷Est茨n locos?! 斡No me puedo creer[n]que lo hayan matado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_519_04_ [Makoto]]
[s][vp 9 2 65535 37707 0 0]斡Los Ladrones Fantasma[n]son unos asesinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_02_ [Makoto]]
[s][vp 9 2 65535 46107 0 0]斡夷A eso lo llaman[n]或despertar el coraz吋n位?![n]斡Solo son unos asesinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_519_06_ [Makoto]]
[s][vp 9 2 65535 37907 0 0]斡Los Ladrones Fantasma[n]nos han mentido! 斡Nunca pens姻 que[n]matar胤an a una persona![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_03_ [Makoto]]
[s][vp 9 2 65535 41607 0 0]斡夷Est茨n locos?! 斡No me puedo creer[n]que lo hayan matado![n][f 1 2 180][e]

[msg MSG_GRT_main_All_519_12_ [Makoto]]
[s][vp 9 2 65535 38357 0 0]No me lo puedo creer. 斡Al final[n]no eran m茨s que unos asesinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_04_ [Makoto]]
[s][vp 9 2 65535 41801 0 0]斡夷A eso lo llaman[n]或despertar el coraz吋n位?![n]斡Solo son unos asesinos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_519_14_ [Makoto]]
[s][vp 9 2 65535 38507 0 0]Qu姻 barbaridad... Parece que[n]disfrutan matando a la gente. [n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_05_ [Makoto]]
[s][vp 9 2 65535 38402 0 0]No tienen excusa[n]despu姻s de lo que hicieron.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_06_ [Makoto]]
[s][vp 9 2 65535 38301 0 0]Qu姻 barbaridad...[n]夷La gente normal es capaz[n]de hacer algo as胤?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_07_ [Makoto]]
[s][vp 9 2 65535 38552 0 0]Puede que fuera malo,[n]pero ni siquiera 姻l se merec胤a[n]una muerte as胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_019_08_ [Makoto]]
[s][vp 9 2 65535 38757 0 0]夷Ser茨 verdad que los Ladrones[n]Fantasma estaban detr茨s[n]de ese asesinato?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_01_ [Makoto]]
[s][vp 9 2 65535 45657 0 0]Me da igual c吋mo lo hagan,[n]pero que acaben ya[n]con los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_520_04_ [Makoto]]
[s][vp 9 2 65535 37851 0 0]斡Los Ladrones Fantasma[n]son unos criminales![n]斡Hay que acabar con ellos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_02_ [Makoto]]
[s][vp 9 2 65535 41801 0 0]斡夷Cu茨nto tiempo van a dejar[n]libres a los Ladrones Fantasma?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_520_06_ [Makoto]]
[s][vp 9 2 65535 37907 0 0]Entonces, 夷los episodios[n]de descontrol fueron obra[n]de los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_03_ [Makoto]]
[s][vp 9 2 65535 38151 0 0]Me da igual c吋mo lo hagan,[n]pero que acaben ya[n]con los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_520_12_ [Makoto]]
[s][vp 9 2 65535 40151 0 0]斡Que alguien arreste a los Ladrones[n]Fantasma antes de que[n]me hagan da隠o! [n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_04_ [Makoto]]
[s][vp 9 2 65535 41307 0 0]斡夷Por qu姻 la polic胤a[n]y el gobierno no dicen nada?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_520_14_ [Makoto]]
[s][vp 9 2 65535 38507 0 0]斡夷Es que nadie va a hacer nada?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_05_ [Makoto]]
[s][vp 9 2 65535 38759 0 0]夷Qu姻 est茨 haciendo la polic胤a?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_06_ [Makoto]]
[s][vp 9 2 65535 38102 0 0]Si es que ellos mismos[n]se llaman ladrones.[n]Siempre han sido unos delincuentes.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_07_ [Makoto]]
[s][vp 9 2 65535 38307 0 0]Todos estos accidentes... son culpa[n]de los Ladrones Fantasma, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_020_08_ [Makoto]]
[s][vp 9 2 65535 38357 0 0]Qu姻 miedo. Un delincuente[n]al que es imposible atrapar...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_01_ [Makoto]]
[s][vp 9 2 65535 46005 0 0]夷Una recompensa por los Ladrones[n]Fantasma? Bueno, tienen que hacer[n]lo que sea para pillarlos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_521_04_ [Makoto]]
[s][vp 9 2 65535 37707 0 0]Quiero que arresten[n]a los Ladrones Fantasma[n]antes de que causen m茨s da隠os.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_02_ [Makoto]]
[s][vp 9 2 65535 41157 0 0]夷Cu茨ndo piensan arrestar[n]a los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_521_06_ [Makoto]]
[s][vp 9 2 65535 37904 0 0]Dicen que treinta millones de yenes[n]es la mayor recompensa[n]de la historia...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_03_ [Makoto]]
[s][vp 9 2 65535 41502 0 0]夷Cu茨ndo va a arrestar la polic胤a[n]a los Ladrones Fantasma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_521_12_ [Makoto]]
[s][vp 9 2 65535 38352 0 0]斡La polic胤a est茨 tardando mucho![n]斡Que se den prisa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_04_ [Makoto]]
[s][vp 9 2 65535 43457 0 0]Vaya, la polic胤a por fin[n]ha decidido intervenir...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_521_13_ [Makoto]]
[s][vp 9 2 65535 38460 0 0]斡夷Treinta millones de yenes[n]de recompensa?![n]Pues s胤 que son peligrosos...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_05_ [Makoto]]
[s][vp 9 2 65535 37701 0 0]Les han puesto precio[n]a sus cabezas...[n]夷La polic胤a va en serio?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_06_ [Makoto]]
[s][vp 9 2 65535 42157 0 0]Qu姻 horror... 斡Yo no quiero[n]acabar como Okumura![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_07_ [Makoto]]
[s][vp 9 2 65535 42709 0 0]斡Alguien tendr茨 informaci吋n[n]sobre ellos![n][f 1 2 180][e]

[msg MSG_GRT_main_All_021_08_ [Makoto]]
[s][vp 9 2 65535 39807 0 0]Un amigo m胤o ha estado buscando[n]como loco a los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_01_ [Makoto]]
[s][vp 9 2 65535 41354 0 0]Creo que es uno[n]de los candidatos m茨s fuertes[n]de estas elecciones.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_02_ [Makoto]]
[s][vp 9 2 65535 46100 0 0]夷Las elecciones son[n]a finales de a隠o?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_03_ [Makoto]]
[s][vp 9 2 65535 39104 0 0]夷Qui姻n se va a presentar[n]a las pr吋ximas elecciones?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_022_04_ [Makoto]]
[s][vp 9 2 65535 40955 0 0]Me pregunto si este a隠o[n]habr茨 buenos candidatos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_01_ [Makoto]]
[s][vp 9 2 65535 44602 0 0]Yo pago mis impuestos, as胤 que[n]m茨s vale que la polic胤a haga algo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_02_ [Makoto]]
[s][vp 9 2 65535 43805 0 0]夷C吋mo voy a sentirme a salvo[n]si los episodios de descontrol[n]no dejan de multiplicarse?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_03_ [Makoto]]
[s][vp 9 2 65535 39057 0 0]夷Cu茨nto tiempo piensan dejar que[n]los Ladrones Fantasma pululen[n]por ah胤 libremente?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_04_ [Makoto]]
[s][vp 9 2 65535 38057 0 0]斡夷Cu茨ndo van a arrestar[n]a los Ladrones Fantasma?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_05_ [Makoto]]
[s][vp 9 2 65535 40007 0 0]斡夷Por qu姻 tardan tanto[n]en arrestarlos?![n][f 1 2 180][e]

[msg MSG_GRT_main_All_023_06_ [Makoto]]
[s][vp 9 2 65535 38501 0 0]斡Quiero que revelen ya[n]las identidades de esos Ladrones![n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_01_ [Makoto]]
[s][vp 9 2 65535 41950 0 0]夷Conoces a Shido?[n]Parece un buen candidato.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_02_ [Makoto]]
[s][vp 9 2 65535 44204 0 0]La gente habla maravillas[n]de un candidato que se llama Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_03_ [Makoto]]
[s][vp 9 2 65535 43400 0 0]A Shido le apasiona[n]el futuro de Jap吋n.[n]Le tengo mucho respeto.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_04_ [Makoto]]
[s][vp 9 2 65535 46053 0 0]夷Has escuchado el discurso[n]de Shido? Ha sido incre胤ble.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_05_ [Makoto]]
[s][vp 9 2 65535 38150 0 0]Eso s胤 que es tener carisma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_06_ [Makoto]]
[s][vp 9 2 65535 37955 0 0]郁ltimamente no paro de o胤r[n]el nombre de Shido.[n]Tiene que ser buen pol胤tico, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_07_ [Makoto]]
[s][vp 9 2 65535 37603 0 0]Esta vez s胤 que pienso votar.[n]Mi voto es para Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_024_08_ [Makoto]]
[s][vp 9 2 65535 40000 0 0]Ser胤a incre胤ble que Shido[n]dirigiera el pa胤s.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_01_ [Makoto]]
[s][vp 9 2 65535 38205 0 0]Aunque lo arrestes,[n]que se suicide no soluciona nada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_02_ [Makoto]]
[s][vp 9 2 65535 37952 0 0]夷Por qu姻 se suicida justo despu姻s[n]de que lo arresten?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_03_ [Makoto]]
[s][vp 9 2 65535 41507 0 0]Ahora nunca sabremos cu茨les fueron[n]los m姻todos de los Ladrones Fantasma...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_04_ [Makoto]]
[s][vp 9 2 65535 40257 0 0]Me qued姻 de piedra[n]cuando me enter姻 de que[n]ese Ladr吋n Fantasma se suicid吋.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_05_ [Makoto]]
[s][vp 9 2 65535 37707 0 0]El suicidio es solo una forma[n]de escapar de las otras cosas[n]horribles que estaban haciendo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_06_ [Makoto]]
[s][vp 9 2 65535 40155 0 0]Pues nada... Imagino que este es[n]el final de los Ladrones Fantasma.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_025_07_ [Makoto]]
[s][vp 9 2 65535 38252 0 0]Tendr胤an que haberlo ejecutado[n]antes de que se suicidara.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_01_ [Makoto]]
[s][vp 9 2 65535 41353 0 0]斡Seguro que Shido[n]gana las elecciones![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_02_ [Makoto]]
[s][vp 9 2 65535 41000 0 0]Shido es el mejor pol胤tico[n]de este pa胤s.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_03_ [Makoto]]
[s][vp 9 2 65535 40361 0 0]El se隠or Shido[n]tiene una clara visi吋n de futuro.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_04_ [Makoto]]
[s][vp 9 2 65535 41653 0 0]斡El se隠or Shido es el 雨nico[n]ganador posible![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_05_ [Makoto]]
[s][vp 9 2 65535 38104 0 0]斡Ha de ganar Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_06_ [Makoto]]
[s][vp 9 2 65535 38508 0 0]Hac胤a much胤simo tiempo que unas[n]elecciones no me entusiasmaban.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_07_ [Makoto]]
[s][vp 9 2 65535 39300 0 0]Entiendo perfectamente que a todo[n]el mundo le guste Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_026_08_ [Makoto]]
[s][vp 9 2 65535 43104 0 0]夷C吋mo voto a Shido?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_01_ [Makoto]]
[s][vp 9 2 65535 41953 0 0]Los dem茨s pol胤ticos no le llegan[n]ni a la suela del zapato a Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_527_04_ [Makoto]]
[s][vp 9 2 65535 37700 0 0]Shido est茨 trabajando[n]mucho en su campa隠a.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_02_ [Makoto]]
[s][vp 9 2 65535 41800 0 0]Al pa胤s le ir茨 bien siempre[n]que Shido est姻 con nosotros.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_527_06_ [Makoto]]
[s][vp 9 2 65535 37904 0 0]Dicen que, si gana,[n]Shido ser茨 primer ministro. [n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_03_ [Makoto]]
[s][vp 9 2 65535 46153 0 0]El se隠or Shido es[n]el candidato m茨s adecuado.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_527_12_ [Makoto]]
[s][vp 9 2 65535 37750 0 0]Tengo la sensaci吋n[n]de que se puede confiar en Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_04_ [Makoto]]
[s][vp 9 2 65535 37700 0 0]Shido es un ciudadano ejemplar.[n]Jam茨s se meter胤a[n]en negocios ilegales.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_527_13_ [Makoto]]
[s][vp 9 2 65535 38453 0 0]Pocos est茨n a la altura de Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_05_ [Makoto]]
[s][vp 9 2 65535 41300 0 0]斡Un hurra por Shido![n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_06_ [Makoto]]
[s][vp 9 2 65535 41750 0 0]Ojal茨 Shido hubiera estado[n]al frente de este pa胤s[n]desde el principio...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_027_07_ [Makoto]]
[s][vp 9 2 65535 41400 0 0]Conf胤o en que podemos dejar[n]el pa胤s en manos de Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_01_ [Makoto]]
[s][vp 9 2 65535 39455 0 0]Shido est茨 teniendo una mala racha...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_528_04_ [Makoto]]
[s][vp 9 2 65535 37702 0 0]Entonces, 夷los Ladrones[n]Fantasma dec胤an la verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_02_ [Makoto]]
[s][vp 9 2 65535 46405 0 0]Shido lo ha negado. Yo no creo[n]que tenga nada que ocultar.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_528_06_ [Makoto]]
[s][vp 9 2 65535 37905 0 0]Es raro que de repente[n]volvieran de la nada.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_03_ [Makoto]]
[s][vp 9 2 65535 40557 0 0]Un momento, 夷no dijeron que[n]el Ladr吋n Fantasma hab胤a muerto?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_528_12_ [Makoto]]
[s][vp 9 2 65535 38352 0 0]Shido lo ha negado, pero...[n]夷podemos confiar en 姻l?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_04_ [Makoto]]
[s][vp 9 2 65535 45155 0 0]夷Lo que dijeron los Ladrones[n]Fantasma era cierto?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_528_14_ [Makoto]]
[s][vp 9 2 65535 38502 0 0]Cre胤a que los Ladrones[n]Fantasma hab胤an muerto.[n]夷Qu姻 est茨 pasando?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_05_ [Makoto]]
[s][vp 9 2 65535 40352 0 0]Dec胤an que hab胤an muerto.[n]Es mentira, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_06_ [Makoto]]
[s][vp 9 2 65535 40402 0 0]No puede ser verdad. Si no...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_07_ [Makoto]]
[s][vp 9 2 65535 40502 0 0]El se隠or Shido debe estar diciendo[n]la verdad. No queda otra...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_028_08_ [Makoto]]
[s][vp 9 2 65535 41301 0 0]夷No est茨 demasiado currada[n]para ser una broma?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_01_ [Makoto]]
[s][vp 9 2 65535 46152 0 0]夷C吋mo piensan enmendar[n]la situaci吋n del pa胤s?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_529_04_ [Makoto]]
[s][vp 9 2 65535 38952 0 0]Cre胤a que todo ir胤a bien[n]mientras tuvi姻ramos a Shido...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_02_ [Makoto]]
[s][vp 9 2 65535 38552 0 0]No... 夷Por qu姻, Shido?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_529_06_ [Makoto]]
[s][vp 9 2 65535 37901 0 0]Las cosas no se quedar茨n as胤, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_03_ [Makoto]]
[s][vp 9 2 65535 44902 0 0]Se supon胤a que el se隠or Shido[n]iba a devolverle la grandeza[n]a nuestro pa胤s...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_529_12_ [Makoto]]
[s][vp 9 2 65535 38351 0 0]Cre胤a que todo ir胤a bien[n]mientras tuvi姻ramos al se隠or[n]Shido de nuestro lado... [n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_04_ [Makoto]]
[s][vp 9 2 65535 39652 0 0]No puede ser... Qu姻 decepci吋n.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_529_13_ [Makoto]]
[s][vp 9 2 65535 38451 0 0]夷Por qu姻? 夷C吋mo? Shido...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_05_ [Makoto]]
[s][vp 9 2 65535 37952 0 0]A lo mejor los Ladrones Fantasma[n]han amenazado a Shido.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_06_ [Makoto]]
[s][vp 9 2 65535 38302 0 0]夷Qui姻n va a arreglar el pa胤s ahora?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_07_ [Makoto]]
[s][vp 9 2 65535 37852 0 0]夷Qu姻 narices?[n]夷Y qu姻 vamos a hacer ahora?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_029_08_ [Makoto]]
[s][vp 9 2 65535 37602 0 0]No me lo puedo creer.[n]Necesitamos a Shido...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_01_ [Makoto]]
[s][vp 9 2 65535 43410 0 0]夷Por qu姻 est茨 pasando esto?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_530_04_ [Makoto]]
[s][vp 9 2 65535 37702 0 0]夷C吋mo piensan arreglar este asunto?[n]Alguien tiene que hacer algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_02_ [Makoto]]
[s][vp 9 2 65535 45452 0 0]El pa胤s se va al traste...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_530_06_ [Makoto]]
[s][vp 9 2 65535 37902 0 0]Me da igual qui姻n sea,[n]pero hay que ponerle soluci吋n. [n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_03_ [Makoto]]
[s][vp 9 2 65535 41952 0 0]夷Y qu姻 quieres que le haga yo?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_530_12_ [Makoto]]
[s][vp 9 2 65535 38352 0 0]夷C吋mo ha pasado esto?[n]Que alguien haga algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_04_ [Makoto]]
[s][vp 9 2 65535 38060 0 0]Nada de lo que yo hago importa.[n]夷Qu姻 m茨s da?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_530_13_ [Makoto]]
[s][vp 9 2 65535 38452 0 0]夷Qu姻 est茨 pasando?[n]Que alguien haga algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_05_ [Makoto]]
[s][vp 9 2 65535 37552 0 0]Alguien tiene que hacer algo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_06_ [Makoto]]
[s][vp 9 2 65535 37652 0 0]El tiempo se acaba.[n]Que alguien haga algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_07_ [Makoto]]
[s][vp 9 2 65535 38052 0 0]Estamos acabados.[n]夷Por qu姻 no nos rendimos?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_030_08_ [Makoto]]
[s][vp 9 2 65535 39752 0 0]Siempre le tocaba a otra persona[n]hacer algo...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_01_ [Makoto]]
[s][vp 9 2 65535 41750 0 0]斡Es divertid胤simo![n]Adoro mi trabajo.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_02_ [Makoto]]
[s][vp 9 2 65535 39853 0 0]斡Es la persona con quien m茨s[n]me gusta ir a tomar algo![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_03_ [Makoto]]
[s][vp 9 2 65535 38951 0 0]斡Enhorabuena por haber cortado![n]Espera, estabais saliendo, 夷no?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_04_ [Makoto]]
[s][vp 9 2 65535 59138 0 0]夷Quieres ir ahora mismo?[n]Venga, vale, que estoy libre.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_05_ [Makoto]]
[s][vp 9 2 65535 58922 0 0]Ah, 夷quieres que me encargue[n]yo del turno de noche?[n]Vale, t雨 descansa.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_06_ [Makoto]]
[s][vp 9 2 65535 41500 0 0]Mi hija me ha invitado.[n]Tenemos buenos asientos.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_07_ [Makoto]]
[s][vp 9 2 65535 59090 0 0]夷Yo? Si siempre he sido as胤.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_08_ [Makoto]]
[s][vp 9 2 65535 40751 0 0]夷Es cosa m胤a o el jefe[n]est茨 m茨s majo que de costumbre?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_09_ [Makoto]]
[s][vp 9 2 65535 41958 0 0]S胤, tengo dos hijas.[n]La peque隠a por fin[n]ha empezado el colegio.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_10_ [Makoto]]
[s][vp 9 2 65535 40650 0 0]夷Es tu profe?[n]斡Qu姻 moner胤a de beb姻![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_11_ [Makoto]]
[s][vp 9 2 65535 38702 0 0]夷Eh, yo? Pero pensaba[n]que te gustaba otra persona...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_12_ [Makoto]]
[s][vp 9 2 65535 39153 0 0]斡La vida es maravillosa![n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_13_ [Makoto]]
[s][vp 9 2 65535 38505 0 0]夷Un hombre de familia? Gracias.[n]Solo hago lo que har胤a[n]cualquier buen padre.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_14_ [Makoto]]
[s][vp 9 2 65535 39704 0 0]No hemos discutido ni nos hemos[n]peleado... Es raro,[n]pero en cierto modo me gusta.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_15_ [Makoto]]
[s][vp 9 2 65535 37553 0 0]Espero que puedas encontrar[n]un trabajo que te apasione.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_031_16_ [Makoto]]
[s][vp 9 2 65535 38252 0 0]Antes siempre estaba de mal humor.[n]夷Qu姻 le ha pasado?[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_01_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_02_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_03_ [Makoto]]
[s][vp 9 2 65535 43411 0 0]Supongo que no nos queda otra...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_032_04_ [Makoto]]
[s][vp 9 2 65535 37711 0 0]Supongo que al menos es mejor[n]que lo que ocurri吋 el a隠o pasado...[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_01_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_02_ [Makoto]]
[s]0[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_03_ [Makoto]]
[s][vp 9 2 65535 44352 0 0]Da igual cu茨nto esperemos.[n]Nada cambiar茨.[n][f 1 2 180][e]

[msg MSG_GRT_main_All_033_04_ [Makoto]]
[s][vp 9 2 65535 41560 0 0]夷Qui姻n tiene la culpa[n]de que el mundo sea tan horrible?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_01_ [Makoto]]
[s][vp 9 2 65535 43705 0 0]夷Cu茨ntos incidentes raros[n]han ocurrido hasta ahora?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_02_ [Makoto]]
[s][vp 9 2 65535 40654 0 0]郁ltimamente ha habido[n]un mont吋n... 夷Qu姻 est茨 pasando?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_03_ [Makoto]]
[s][vp 9 2 65535 37501 0 0]Todos los trenes se pararon...[n]Se me estaba acabando[n]la paciencia.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_101_04_ [Makoto]]
[s][vp 9 2 65535 43852 0 0]郁ltimamente ha habido[n]muchos accidentes. Podr胤a haber[n]otro en cualquier momento.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_01_ [Makoto]]
[s][vp 9 2 65535 40153 0 0]夷Viste Good Morning Japan?[n]斡Sali吋 Madarame![n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_02_ [Makoto]]
[s][vp 9 2 65535 46200 0 0]Al parecer, no tiene rival[n]en el mundo del arte japon姻s.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_03_ [Makoto]]
[s][vp 9 2 65535 41604 0 0]Debe de ser bastante famoso[n]para salir en Good Morning Japan.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_04_ [Makoto]]
[s][vp 9 2 65535 46054 0 0]Al parecer, no tiene rival[n]en el mundo del arte japon姻s.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_001 [Makoto]]
[s][vp 9 2 65535 40304 0 0]Me han hablado mucho de los cuadros[n]de estilo japon姻s 雨ltimamente.[n]夷Acaso est茨n de moda?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_002 [Makoto]]
[s][vp 9 2 65535 39304 0 0]Ah, 夷Madarame es aquel hombre[n]mayor que sali吋 en la tele?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_003 [Makoto]]
[s][vp 9 2 65535 39253 0 0]Yo no s姻 mucho de arte,[n]pero me parece que esos cuadros[n]son buen胤simos.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_004 [Makoto]]
[s][vp 9 2 65535 39808 0 0]夷No molar胤a aprender[n]sobre arte japon姻s?[n]Igual me pongo a estudiar...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_102_005 [Makoto]]
[s][vp 9 2 65535 40953 0 0]夷Has visto ese cuadro?[n]Por lo visto, el autor es Madarame.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_01_ [Makoto]]
[s][vp 9 2 65535 44354 0 0]Hasta la polic胤a tiene[n]que tener cuidado a la hora[n]de lidiar con ellos...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_02_ [Makoto]]
[s][vp 9 2 65535 39359 0 0]La polic胤a tiene que intervenir[n]antes de que haya[n]a雨n m茨s v胤ctimas.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_03_ [Makoto]]
[s][vp 9 2 65535 41501 0 0]Hasta la polic胤a tiene[n]que tener cuidado a la hora[n]de lidiar con ellos...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_103_04_ [Makoto]]
[s][vp 9 2 65535 39301 0 0]La polic胤a tiene que intervenir[n]antes de que haya[n]a雨n m茨s v胤ctimas.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_01_ [Makoto]]
[s][vp 9 2 65535 46255 0 0]夷Crees que tendr姻 tiempo[n]de ver los fuegos artificiales?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_104_02_ [Makoto]]
[s][vp 9 2 65535 43455 0 0]Quiero ir a ver[n]los fuegos artificiales, pero[n]es que no tengo tiempo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_01_ [Makoto]]
[s][vp 9 2 65535 39109 0 0]Llevar a cabo una ejecuci吋n p雨blica[n]es pasarse de la raya...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_02_ [Makoto]]
[s][vp 9 2 65535 43454 0 0]La rueda de prensa del se隠or[n]Okumura ha sido horrible.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_03_ [Makoto]]
[s][vp 9 2 65535 38155 0 0]Llevar a cabo una ejecuci吋n p雨blica[n]es pasarse de la raya...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_105_04_ [Makoto]]
[s][vp 9 2 65535 39002 0 0]夷Has visto la grabaci吋n[n]de la rueda de prensa?[n]Se han pasado un mont吋n.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_01_ [Makoto]]
[s][vp 9 2 65535 38700 0 0]Qu姻 guapa era la chica[n]del tren, 夷verdad?[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_02_ [Makoto]]
[s][vp 9 2 65535 39300 0 0]Parece que la gente guapa[n]siempre tiene buena actitud.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_03_ [Makoto]]
[s][vp 9 2 65535 37604 0 0]夷La chica del ballet?[n]Puede que se parecieran...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_04_ [Makoto]]
[s][vp 9 2 65535 40654 0 0]Nadie sabe por qu姻.[n]Da un canguelo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_05_ [Makoto]]
[s][vp 9 2 65535 38805 0 0]夷Causas desconocidas? Ya...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_06_ [Makoto]]
[s][vp 9 2 65535 39300 0 0]No hay nada mejor que ser joven.[n]Ojal茨 pudiera volver atr茨s[n]en el tiempo...[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_07_ [Makoto]]
[s][vp 9 2 65535 37803 0 0]Vente a jugar al golf, anda,[n]y haz contactos.[n][f 1 2 180][e]

[msg MSG_GRT_main_Lim_401_08_ [Makoto]]
[s][vp 9 2 65535 38602 0 0]夷Es que no hay nada[n]con lo que entretenerse?[n][f 1 2 180][e]

[msg MSG_BACKGROUND_EKIIN_001 [Empleado de la estaci吋n serio]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]El and姻n de la l胤nea Ginza est茨 por[n]aqu胤, pasando los torniquetes.[n][w][e]

[msg MSG_EKIIN_852_000_00 [Empleado de la estaci吋n serio]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]夷S胤? 夷En qu姻 puedo ayudarle?[n][w][e]
[s][vp 8 2 1 0 11 0]Oh, 夷la l胤nea Ginza?[n]Est茨 por aqu胤,[n]pasando los torniquetes.[n][w][e]

[msg MSG_EKIIN_852_100_00 [Empleado de la estaci吋n serio]]
[s][f 4 23 1 11 3 10 0 10][vp 8 2 1 0 11 0]El and姻n de la l胤nea Ginzaes el ocho.[n][w][e]

[msg MSG_EIKO_001_0_0 [Eiko]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Eh, t雨 eres [f 4 1], 夷verdad?[n]夷Qu姻 haces aqu胤?[n][w][e]

[sel SEL_EIKO_002_0_0 top]
[s]Despidi姻ndome.[e]
[s]Dando una vuelta.[e]
[s]Lo mismo te digo.[e]

[msg MSG_EIKO_003_0_0 [Eiko]]
[s][vp 8 2 1 0 18 0]Ah, s胤, creo que Makoto[n]me lo coment吋.[n]Vuelves a tu ciudad natal, 夷no?[n][w][e]
[s][vp 8 2 1 0 18 0]Para m胤 es justo lo contrario.[n]Estoy con la dichosa preparatoria.[n][w][e]

[msg MSG_EIKO_003_1_0 [Eiko]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]夷En serio? Pues no parece que te[n]estrese tener que estudiar para las[n]pruebas de acceso a la universidad.[n][w][e]
[s][vp 8 2 1 0 18 0]Ufff, qu姻 envidia. Yo estoy[n]con la dichosa preparatoria.[n][w][e]

[msg MSG_EIKO_003_2_0 [Eiko]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Para ya, 夷no?[n]斡Que voy de camino a clase![n][w][e]
[s][vp 8 2 1 0 18 0]Es un curso corto, muy intensivo[n]y solo dura unos meses,[n]pero es una pesadilla.[n][w][e]

[msg MSG_EIKO_004_0_0 [Eiko]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Quer胤a ir a la universidad,[n]pero no consegu胤 ninguna[n]de las que eleg胤.[n][w][e]
[s][vp 8 2 1 0 18 0]Entonces tengo que estudiar[n]otro a隠o entero.[n][w][e]
[s][vp 8 2 1 0 18 0]Me parec胤a absurdo pasarme un a隠o[n]empollando para volver a estudiar...[n][w][e]

[msg MSG_EIKO_005_0_0 [Eiko]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Pero ver que Makoto se esfuerza[n]siempre tanto me hace pensar[n]que quiz茨 merezca la pena.[n][w][e]
[s][vp 8 2 1 0 8 0][f 4 25 1 65535 0 0]Bueno, tengo que irme.[n]斡Ll茨mame! 斡Chao![n][w][e]

[msg MSG_EIKO_End [Eiko]]
[s][f 4 23 1 18 3 10 0 10][vp 8 2 1 0 18 0]Bueno, tengo que irme.[n]斡Ll茨mame! 斡Chao![n][w][e]

