[msg D152_02_RYUJI_mes01 [Chico vulgar]]
[s][bup 0 2 5 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]夷Podr姻 forzar la puerta?[n][w][e]

[msg D152_02_RYUJI_GREE_mes01 [Chico vulgar]]
[s]斡夷Qu姻 co隠o est茨 pasando?![n][w][e]

[msg D152_02_RYUJI_GREE_mes02 [Chico vulgar]]
[s]斡Dejadme saliiiiiiiiir! 斡Holaaaaaa![n][w][e]

[msg D152_02_RYUJI_GREE_mes03 [Chico vulgar]]
[s]Esto no es un sue隠o, es...[n][w][e]

