[msg Dummy_mes]
[s]※イベントを作成して下さい。[n][w][e]

[msg obj_f155_011_100_mes01]
[s]…[n][w][e]

[msg obj_f155_011_100_mes02]
[s]…[n][w][e]

[msg obj_f155_011_102_mes01]
[s]…[n][w][e]

[msg obj_f155_011_102_mes02]
[s]…[n][w][e]

[msg obj_f155_011_103_mes01]
[s]…[n][w][e]

[msg obj_f155_011_103_mes02]
[s]…[n][w][e]

[msg obj_f155_011_104_mes01]
[s]…[n][w][e]

[msg obj_f155_011_104_mes02]
[s]…[n][w][e]

[msg obj_f155_011_105_mes01]
[s]…[n][w][e]

[msg obj_f155_011_105_mes02]
[s]…[n][w][e]

[msg obj_f155_011_106_mes01]
[s]…[n][w][e]

[msg obj_f155_011_106_mes02]
[s]…[n][w][e]

[msg obj_f155_011_108_mes01]
[s]…[n][w][e]

[msg obj_f155_011_108_mes02]
[s]…[n][w][e]

[msg obj_f155_011_109_mes01]
[s]…[n][w][e]

[msg obj_f155_011_109_mes02]
[s]…[n][w][e]

