[msg Dummy_mes]
[s]※イベントを作成して下さい。[n][w][e]

[msg obj_f159_003_101_mes01]
[s]…[n][w][e]

[msg obj_f159_003_101_mes02]
[s]…[n][w][e]

[msg obj_f159_003_102_mes01]
[s]…[n][w][e]

[msg obj_f159_003_102_mes02]
[s]…[n][w][e]

[msg obj_f159_003_103_mes01]
[s]…[n][w][e]

[msg obj_f159_003_103_mes02]
[s]…[n][w][e]

[msg obj_f159_003_104_mes01]
[s]…[n][w][e]

[msg obj_f159_003_104_mes02]
[s]…[n][w][e]

[msg obj_f159_003_105_mes01]
[s]…[n][w][e]

[msg obj_f159_003_105_mes02]
[s]…[n][w][e]

[msg obj_f159_003_106_mes01]
[s]…[n][w][e]

[msg obj_f159_003_106_mes02]
[s]…[n][w][e]

[msg obj_f159_003_109_mes01]
[s]…[n][w][e]

[msg obj_f159_003_109_mes02]
[s]…[n][w][e]

