[msg Dummy_mes]
[s]※イベントを作成して下さい。[n][w][e]

[msg obj_f155_003_100_mes01]
[s]…[n][w][e]

[msg obj_f155_003_100_mes02]
[s]…[n][w][e]

[msg obj_f155_003_101_mes01]
[s]…[n][w][e]

[msg obj_f155_003_101_mes02]
[s]…[n][w][e]

[msg obj_f155_003_102_mes01]
[s]…[n][w][e]

[msg obj_f155_003_102_mes02]
[s]…[n][w][e]

[msg obj_f155_003_103_mes01]
[s]…[n][w][e]

[msg obj_f155_003_103_mes02]
[s]…[n][w][e]

[msg obj_f155_003_104_mes01]
[s]…[n][w][e]

[msg obj_f155_003_104_mes02]
[s]…[n][w][e]

[msg obj_f155_003_105_mes01]
[s]…[n][w][e]

[msg obj_f155_003_105_mes02]
[s]…[n][w][e]

[msg obj_f155_003_107_mes01]
[s]…[n][w][e]

[msg obj_f155_003_107_mes02]
[s]…[n][w][e]

[msg obj_f155_003_108_mes01]
[s]…[n][w][e]

[msg obj_f155_003_108_mes02]
[s]…[n][w][e]

[msg obj_f155_003_110_mes01]
[s]…[n][w][e]

[msg obj_f155_003_110_mes02]
[s]…[n][w][e]

