[msg Dummy_mes]
[s]※イベントを作成して下さい。[n][w][e]

[msg obj_f156_006_100_mes01]
[s]…[n][w][e]

[msg obj_f156_006_100_mes02]
[s]…[n][w][e]

[msg obj_f156_006_101_mes01]
[s]…[n][w][e]

[msg obj_f156_006_101_mes02]
[s]…[n][w][e]

[msg obj_f156_006_103_mes01]
[s]…[n][w][e]

[msg obj_f156_006_103_mes02]
[s]…[n][w][e]

[msg obj_f156_006_104_mes01]
[s]…[n][w][e]

[msg obj_f156_006_104_mes02]
[s]…[n][w][e]

[msg obj_f156_006_106_mes01]
[s]…[n][w][e]

[msg obj_f156_006_106_mes02]
[s]…[n][w][e]

[msg obj_f156_006_107_mes01]
[s]…[n][w][e]

[msg obj_f156_006_107_mes02]
[s]…[n][w][e]

[msg obj_f156_006_108_mes01]
[s]…[n][w][e]

[msg obj_f156_006_108_mes02]
[s]…[n][w][e]

