[msg MSG_000_0_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]斡Escucha, recluso![n][f 1 3 65535][w][e]

[sel SEL_000_3_0 top]
[s]夷Qu姻 pasa?[e]
[s]夷Puedo ayudarte?[e]

[msg MSG_000_5_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Hemos introducido un nuevo r姻gimen[n]en tu rehabilitaci吋n en forma[n]de [clr 2]Desaf胤os de combate[clr 27].[n][f 1 3 65535][w][e]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][f 4 24 0 5 6 36 3 100][vp 8 0 0 2 65535 0]Dejaremos que las cogniciones[n]de tus compa隠eros[n]luchen junto a ti.[n][f 1 3 65535][w][e]

[msg MSG_000_7_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]斡Ya puedes llorar de alegr胤a![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]En funci吋n de los resultados[n]de los combates, tu esfuerzo[n]se ver茨 recompensado de una u otra forma.[n][f 1 3 65535][w][e]
[s][bup 0 101 1 0 0][f 4 10 65535 0 0][f 4 24 0 3 6 36 3 100][vp 8 0 0 4 65535 0]Si te alzas con la victoria, recibir茨s[n]una recompensa y ser茨s m茨s fuerte[n]de cuerpo y alma.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Hasta hemos preparado un escenario[n]especial para que superes[n]esta etapa de la rehabilitaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]T吋matelo como una oportunidad[n]para demostrar[n]cu茨nto has mejorado.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Si quieres enfrentarte a este reto,[n]estaremos encantadas de ayudarte.[n][f 1 3 65535][w][e]

