[msg MSG_000_0_0 [詩]]
[s][vp 8 0 0 0 65535 0]Has ca胤do a la tierra[n]y has desperdiciado tu noble vida.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]El h姻roe cae por el peso[n]de su justicia y la historia de la[n]revoluci吋n no llega al pueblo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Las ascuas del coraje[n]que encendieron la vida han sido[n]apagadas por vientos oscuros...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Lavenza]]
[s][bup 0 100 4 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]斡No puede ser![n]Si t雨 caes, el mundo...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Siento que se acerca[n]una gran calamidad...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Lavenza]]
[s][bup 0 100 3 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]No...[n][f 1 3 65535][w][e]

[msg SYS_004_0_0]
[s][vp 8 0 0 0 65535 0]夷Qu姻 quieres hacer?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Retroceder una semana[e]
[s]Volver a la pantalla de t胤tulo[e]

[sel SEL_006_0_0 top]
[s]Reiniciar el combate[e]
[s]Volver a la Hab. segura anterior[e]
[s]Reiniciar la infiltraci吋n[e]
[s]Volver a la pantalla de t胤tulo[e]

[sel SEL_007_0_0 top]
[s]Reiniciar el combate[e]
[s]Volver a la Hab. segura anterior[e]
[s]Retroceder una semana[e]
[s]Volver a la pantalla de t胤tulo[e]

[sel SEL_008_0_0 top]
[s]Reiniciar el combate[e]
[s]Volver a la Hab. segura anterior[e]
[s]Volver a la pantalla de t胤tulo[e]

[sel SEL_009_0_0 top]
[s]Volver a la Hab. segura anterior[e]
[s]Reiniciar la infiltraci吋n[e]
[s]Volver a la pantalla de t胤tulo[e]

[sel SEL_010_0_0 top]
[s]Volver a la Hab. segura anterior[e]
[s]Retroceder una semana[e]
[s]Volver a la pantalla de t胤tulo[e]

