[msg MSG_000_0_0 [詩(ラヴェンツァ)]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Has ca胤do, y de tu alma solo quedan cenizas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]El fuego desafiante que fue tu gu胤a[n]se ha visto ahogado[n]en una vor茨gine de ilusiones.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]El camino del h姻roe llega a su fin[n]y con 姻l se extingue la llama de su vigilia...[n][f 1 3 65535][w][e]

[msg SYS_002_0_0]
[s][vp 8 0 0 0 65535 0]夷Qu姻 quieres hacer?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Reiniciar el combate[e]
[s]Volver a la Hab. segura anterior[e]
[s]Reiniciar la infiltraci吋n[e]
[s]Volver a la pantalla de t胤tulo[e]

