[msg msg_combine_PERSONA000 [BLANK]]
[s]BLANK[n][w][e]

[msg msg_combine_PERSONA001 [Metatr吋n]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]El poder del canciller del cielo[n]se convertir茨 en tu m茨scara[n]para luchar contra la oscuridad...[n][w][e]

[msg msg_combine_PERSONA002 [Belceb雨]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mi poder demon胤aco se convertir茨[n]en tu nueva m茨scara para que todos[n]sepan lo que es el infierno.[n][w][e]

[msg msg_combine_PERSONA003 [C雨 Chulainn]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mi lanza m茨gica[n]har茨 que llueva sangre.[n]斡Deja que sea tu m茨scara![n][w][e]

[msg msg_combine_PERSONA004 [Jack-o'-Lantern]]
[s]Soy [clr 1][var 1][clr 27], jii, jo.[n][w][e]
[s]斡Como me han echado del infierno,[n]no me queda m茨s remedio[n]que ser tu m茨scara, jo![n][w][e]

[msg msg_combine_PERSONA005 [Jack Frost]]
[s]斡Soy [clr 1][var 1][clr 27], jii, jo![n][w][e]
[s]斡S姻 que solo soy una m茨scara,[n]pero cu胤dame bien, jii, jo![n][w][e]

[msg msg_combine_PERSONA006 [Pixie]]
[s]斡Soy [clr 1][var 1][clr 27]![n][w][e]
[s]斡Ser姻 tu m茨scara[n]y lo pasaremos pipa![n][w][e]

[msg msg_combine_PERSONA007 [Cerbero]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Yo convertir en tu m茨scara.[n]Yo guiar t雨 por otro mundo.[n][w][e]

[msg msg_combine_PERSONA008 [Lilim]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Dejar姻 el reino de los sue隠os[n]por el momento para convertirme[n]en tu m茨scara...[n][w][e]

[msg msg_combine_PERSONA009 [Eligor]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara.[n]斡Que d姻 comienzo la era[n]de la guerra y el amor![n][w][e]

[msg msg_combine_PERSONA010 [Od胤n]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Este poder que me cost吋 un ojo[n]ser茨 la m茨scara de tu alma[n]y te conducir茨 a la batalla.[n][w][e]

[msg msg_combine_PERSONA011 [Hua Po]]
[s]斡Soy... [clr 1][var 1][clr 27]![n][w][e]
[s]Por ti, que a雨n vives,[n]me convertir姻 en una m茨scara...[n][w][e]

[msg msg_combine_PERSONA012 [Decarabia]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]El poder de mi cuerpo estrellado[n]se convertir茨 en una m茨scara[n]para ti.[n][w][e]

[msg msg_combine_PERSONA013 [Mara]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]No hay nada que me puedas ocultar.[n]Tus deseos m茨s profundos no son m茨s[n]que otra de tus fachadas.[n][w][e]

[msg msg_combine_PERSONA014 [Ose]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu m茨scara en este mundo[n]entre la raz吋n y la locura.[n]Yo te guiar姻.[n][w][e]

[msg msg_combine_PERSONA015 [Thor]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]La fuerza de mi martillo[n]estar茨 como en casa en tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA016 [Unicornio]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Yo convertir en m茨scara.[n]Yo proteger de cosa impura.[n][w][e]

[msg msg_combine_PERSONA017 [Uriel]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Yo, el verdugo de la justicia,[n]resido ahora en tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA018 [Sarasvati]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]La melod胤a del coraz吋n...[n]se convertir茨 en tu m茨scara[n]y te acompa隠ar茨...[n][w][e]

[msg msg_combine_PERSONA019 [Valquiria]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡El coraje de enfrentarse[n]a la mism胤sima muerte[n]formar茨 parte de tu m茨scara![n][w][e]

[msg msg_combine_PERSONA020 [Iaksi]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara[n]y consumir姻 a aquellos[n]que osen enfrentarse a ti...[n][w][e]

[msg msg_combine_PERSONA021 [Ganesha]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Ahora que tienes mi m茨scara,[n]la suerte estar茨 de tu parte![n][w][e]

[msg msg_combine_PERSONA022 [Anubis]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en una m茨scara[n]y socorrer姻 a tu magn胤fica alma.[n][w][e]

[msg msg_combine_PERSONA023 [Mot]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Solo deseo arriesgar mi vida[n]en la batalla... Por eso me uno a ti[n]como una m茨scara.[n][w][e]

[msg msg_combine_PERSONA024 [Rafael]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en una m茨scara[n]para cuidar de tu salud,[n]tanto mental como f胤sica.[n][w][e]

[msg msg_combine_PERSONA025 [Sc茨thach]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara[n]y disciplinar姻 tu alma.[n][w][e]

[msg msg_combine_PERSONA026 [Gran Pixie]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Me convertir姻 en tu m茨scara[n]y sabr茨s por qu姻 me llaman[n]或gran hada位![n][w][e]

[msg msg_combine_PERSONA027 [Barong]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Como tu nueva m茨scara, te proteger姻[n]frente a cualquier calamidad.[n][w][e]

[msg msg_combine_PERSONA028 [Girimehkala]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Ahora tu m茨scara contiene[n]mi luz radiante[n]y mi oscuridad tenebrosa.[n][w][e]

[msg msg_combine_PERSONA029 [Rey Frost]]
[s]Soy [clr 1][var 1][clr 27], jii, jo.[n][w][e]
[s]Tus enemigos son mis enemigos.[n]斡Ser姻 tu m茨scara[n]y los congelar姻 a todos, jo![n][w][e]

[msg msg_combine_PERSONA030 [Narciso]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Con mi m茨scara[n]adquieres la aut姻ntica belleza,[n]tanto interior como exterior.[n][w][e]

[msg msg_combine_PERSONA031 [Isis]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mi m茨scara es la prueba de que eres[n]la persona que se sienta[n]en el trono del mundo.[n][w][e]

[msg msg_combine_PERSONA032 [Lamia]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Soy la llama de la venganza...[n]Los que se opongan a nosotros[n]arder茨n con el fuego de tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA033 [Legi吋n]]
[s]Somos [clr 1][var 1][clr 27]...[n][w][e]
[s]El inmenso poder de mi ej姻rcito[n]ahora reside en tu m茨scara...[n][w][e]

[msg msg_combine_PERSONA034 [R茨ksasa]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara.[n]Ahora podemos empezar[n]la fiesta de la destrucci吋n.[n][w][e]

[msg msg_combine_PERSONA035 [Mokoi]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Soy el alma de tu sombra...[n]Por eso me convertir姻[n]en tu m茨scara...[n][w][e]

[msg msg_combine_PERSONA036 [Forneus]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ahora que soy tu m茨scara...[n]las arias ocultas ser茨n tuyas...[n][w][e]

[msg msg_combine_PERSONA037 [Setanta]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Si alguien te da problemas,[n]lo estrangular姻 hasta que muera.[n][w][e]

[msg msg_combine_PERSONA038 [Titania]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara.[n]Ahora podremos disfrutar del sue隠o[n]de una noche de verano.[n][w][e]

[msg msg_combine_PERSONA039 [緯ncubo]]
[s]斡Soy [clr 1][var 1][clr 27]![n][w][e]
[s]斡Ahora que soy tu m茨scara,[n]no volver茨s a pegar ojo![n][w][e]

[msg msg_combine_PERSONA040 [Oni]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Como ahora somos amigos,[n]斡me comer姻 a todo aquel que intente[n]interponerse en nuestro camino![n][w][e]

[msg msg_combine_PERSONA041 [Lilit]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]A partir de ahora, ser姻 tu m茨scara.[n]Vaya nochecita te espera...[n][w][e]

[msg msg_combine_PERSONA042 [Rangda]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Voy a convertirme[n]en tu m茨scara, 夷vale?[n]斡Pero no te mueras![n][w][e]

[msg msg_combine_PERSONA043 [Makami]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]斡Yo ser tu m茨scara[n]y aullar a enemigos![n][w][e]

[msg msg_combine_PERSONA044 [Parvati]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara[n]y te conceder姻 una bendici吋n[n]tan grande como una monta隠a.[n][w][e]

[msg msg_combine_PERSONA045 [Gabriel]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Como tu m茨scara,[n]declaro el nacimiento[n]de tu reci姻n adquirido poder...[n][w][e]

[msg msg_combine_PERSONA046 [Zaou-Gongen]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Te otorgar姻 el poder[n]de tres divinidades. Yo ser姻 otra[n]de tus m茨scaras furiosas...[n][w][e]

[msg msg_combine_PERSONA047 [Alice]]
[s]斡Soy [clr 1][var 1][clr 27]![n][w][e]
[s]斡Ji, ji, ji![n]Creo que ser姻 tu m茨scara...[n]夷Jugar茨s conmigo?[n][w][e]

[msg msg_combine_PERSONA048 [Kali]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Con esta m茨scara,[n]tendr茨s a tu disposici吋n[n]mi furia incontrolable![n][w][e]

[msg msg_combine_PERSONA049 [Kurama Tengu]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Parece que ahora soy tu m茨scara.[n]Supongo que podr姻 entrenarte[n]cuanto quiera.[n][w][e]

[msg msg_combine_PERSONA050 [Ober吋n]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Supongo que no me importa[n]concederte el poder[n]del rey de las hadas...[n][w][e]

[msg msg_combine_PERSONA051 [Shiki-Ouji]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]T雨 tener m茨scara en tu coraz吋n.[n]斡Eso significar t雨 ser colega![n][w][e]

[msg msg_combine_PERSONA052 [Yamata-no-Orochi]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Mi poder desbordarse[n]como inundaci吋n.[n]Con esa m茨scara, tuyo ser...[n][w][e]

[msg msg_combine_PERSONA053 [Orobas]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu m茨scara y te desvelar姻[n]la verdad del futuro que deseas.[n][w][e]

[msg msg_combine_PERSONA054 [H茨numan]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Con esta m茨scara,[n]el poder de mi destreza[n]como espadach胤n es todo tuyo.[n][w][e]

[msg msg_combine_PERSONA055 [Arc茨ngel]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Al poseer esa m茨scara,[n]tambi姻n tienes mi bendici吋n.[n][w][e]

[msg msg_combine_PERSONA056 [Obariyon]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]斡Mientras tengas esa m茨scara,[n]yo te cubro las espaldas, amigo![n][w][e]

[msg msg_combine_PERSONA057 [Reina Mab]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]T雨 que portas mi m茨scara[n]pronto conocer茨s la fuerza[n]de la reina de las hadas.[n][w][e]

[msg msg_combine_PERSONA058 [Sandalf吋n]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Al portar mi m茨scara,[n]tus plegarias me dan fuerza.[n]Venga, luchemos juntos.[n][w][e]

[msg msg_combine_PERSONA059 [Abad吋n]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]La fuerza del abismo[n]est茨 a tu alcance...[n][w][e]

[msg msg_combine_PERSONA060 [Shiisaa]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]T雨 tener m茨scara... T雨 y yo...[n]斡No preocupar, siempre feliz![n][w][e]

[msg msg_combine_PERSONA061 [Sandman]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Poseer esa m茨scara[n]te hace especial. 斡Esta noche[n]te enviar姻 dulces sue隠os![n][w][e]

[msg msg_combine_PERSONA062 [Belial]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Cuando luches y te derroten...[n]yo, tu m茨scara, estar姻 contigo.[n][w][e]

[msg msg_combine_PERSONA063 [Leanan Sidhe]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Nunca te abandonar姻. Esta m茨scara[n]es la prueba de ello... *risita*[n][w][e]

[msg msg_combine_PERSONA064 [Cibeles]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Si osas enga隠arme, te dar姻 caza[n]y te desollar姻. Ahora soy[n]tu m茨scara... Prep茨rate.[n][w][e]

[msg msg_combine_PERSONA065 [Chernobog]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Deja que mi oscuro poder[n]nos corrompa... Ahora que llevas[n]mi m茨scara, todo es posible...[n][w][e]

[msg msg_combine_PERSONA066 [Flauros]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Con esta m茨scara ardiente,[n]mis poderes para vislumbrar[n]el pasado y el futuro ser茨n tuyos...[n][w][e]

[msg msg_combine_PERSONA067 [Ippon-Datara]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Si tienes esta m茨scara,[n]significa que tengo que templarla...[n][w][e]

[msg msg_combine_PERSONA068 [Ortro]]
[s]斡Yo [clr 1][var 1][clr 27]![n][w][e]
[s]M茨scara significa t雨 mi amo.[n]斡Yo ser perro guardi茨n fiel![n][w][e]

[msg msg_combine_PERSONA069 [S雨cubo]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]夷Me deseas tanto que me conviertes[n]en m茨scara? De acuerdo, haz[n]lo que te dicte el coraz吋n.[n][w][e]

[msg msg_combine_PERSONA070 [Hombre polilla]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]夷Qu姻... ser yo...?[n]Ah, s胤, yo tu m茨scara...[n][w][e]

[msg msg_combine_PERSONA071 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA072 [Dominio]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ahora el poder sagrado[n]para desterrar la oscuridad[n]est茨 en tu m茨scara...[n][w][e]

[msg msg_combine_PERSONA073 [Nekomata]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Si cuidas esta m茨scara,[n]cumplir姻 mi parte del trato.[n][w][e]

[msg msg_combine_PERSONA074 [Frost oscuro]]
[s]斡Soy [clr 1][var 1][clr 27], jii, jo![n][w][e]
[s]斡Voy a ser tu m茨scara, jo![n]斡Es un placer conocerte, jo![n][w][e]

[msg msg_combine_PERSONA075 [Arahabaki]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]夷Tambi姻n odias la obediencia ciega?[n]Seremos buenos compa隠eros...[n][w][e]

[msg msg_combine_PERSONA076 [威ngel]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara. Icemos[n]la bandera de la justicia juntos.[n][w][e]

[msg msg_combine_PERSONA077 [Skadi]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Surjo de la oscuridad de tu coraz吋n[n]para otorgarte nuevos poderes...[n]Vamos, acepta mi m茨scara...[n][w][e]

[msg msg_combine_PERSONA078 [Kikuri-Hime]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu m茨scara y te guiar姻[n]por el l胤mite[n]entre la vida y la muerte...[n][w][e]

[msg msg_combine_PERSONA079 [Chi You]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Al llevar esta m茨scara, adquirir茨s[n]el poder de idear una gran cantidad[n]de armas muy poderosas.[n][w][e]

[msg msg_combine_PERSONA080 [Poder]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me fundir姻 con esta m茨scara[n]y te proteger姻 con mi vida[n]como si fuera un escudo de hierro.[n][w][e]

[msg msg_combine_PERSONA081 [Inugami]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Si ans胤as venganza,[n]ser茨 un honor cumplir tal deseo...[n]Vamos, acepta esta m茨scara...[n][w][e]

[msg msg_combine_PERSONA082 [Naberius]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu nueva m茨scara[n]y tomar姻 las riendas de tu destino...[n][w][e]

[msg msg_combine_PERSONA083 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA084 [Limo]]
[s]Yo [clr 1][var 1][clr 27]...[n][w][e]
[s]斡T-t雨... tienes m茨scara![n]P-p-placer conocerte...[n][w][e]

[msg msg_combine_PERSONA085 [Anzu]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Si posees la m茨scara,[n]llegaremos juntos a lo m茨s alto...[n][w][e]

[msg msg_combine_PERSONA086 [Yatagarasu]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]夷Percibes esta noble aura?[n]En ese caso, me convertir姻[n]en m茨scara y te guiar姻... S胤gueme.[n][w][e]

[msg msg_combine_PERSONA087 [Yoshitsune]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Veo que ya conoces mis haza隠as.[n]Celebra mi cortes胤a, pues[n]me convertir姻 en tu m茨scara...[n][w][e]

[msg msg_combine_PERSONA088 [Take-Minakata]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu nueva m茨scara[n]y librar姻 tu coraz吋n del yugo[n]que reprime tu poder...[n][w][e]

[msg msg_combine_PERSONA089 [Ame-no-Uzume]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu nuevo rostro.[n]Venga, disfrutemos de la melod胤a[n]que surge del aut姻ntico poder.[n][w][e]

[msg msg_combine_PERSONA090 [Kushinada]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Es hora de convertirme en m茨scara[n]y liberar el inmaculado poder[n]oculto tras tu carne mortal...[n][w][e]

[msg msg_combine_PERSONA091 [Kumbhanda]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu m茨scara, al parecer.[n]斡Podr姻 desatar la furia que esconde[n]esta alma corrupta![n][w][e]

[msg msg_combine_PERSONA092 [Ongyo-ki]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Je, as胤 que puedes verme...[n]No esperaba menos[n]del poseedor de la m茨scara...[n][w][e]

[msg msg_combine_PERSONA093 [Kin-Ki]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Si posees la m茨scara,[n]te otorgar姻 el poder[n]de un coraz吋n implacable...[n][w][e]

[msg msg_combine_PERSONA094 [Sui-Ki]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Esa nueva m茨scara trae consigo[n]un poder desorbitado...[n][w][e]

[msg msg_combine_PERSONA095 [Fuu-Ki]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Ser姻 una de tus m茨scaras[n]y tu coraz吋n albergar茨[n]la furia de una tormenta![n][w][e]

[msg msg_combine_PERSONA096 [Jatayu]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me complacer茨 sacrificar mi cuerpo[n]para ayudarte. A cambio de gloria,[n]me convertir姻 en una m茨scara.[n][w][e]

[msg msg_combine_PERSONA097 [Kaiwan]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en una m茨scara,[n]y al hacerlo, cambiar姻 tu destino...[n][w][e]

[msg msg_combine_PERSONA098 [Kelpie]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]斡Tu coraz吋n... cre吋 a yo![n]斡Ahora yo ser m茨scara![n][w][e]

[msg msg_combine_PERSONA099 [Tot]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu nueva m茨scara[n]y desatar姻 tu poder interior.[n][w][e]

[msg msg_combine_PERSONA100 [Dioniso]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Luchar姻 junto a ti como m茨scara.[n]Ahora... 斡mu姻strame tu poder[n]para transformarte en combate![n][w][e]

[msg msg_combine_PERSONA101 [Apsar茨]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Perm胤teme desgarrar tu coraz吋n[n]y extraer sus emociones. Lo har姻[n]a trav姻s de tu nueva m茨scara...[n][w][e]

[msg msg_combine_PERSONA102 [Andras]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]夷Quieres que sea tu m茨scara...?[n]Vaya, qu姻 raro. En fin,[n]no me culpes si te matan.[n][w][e]

[msg msg_combine_PERSONA103 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA104 [Koropokguru]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Si soy tu m茨scara,[n]estaremos siempre juntos, 夷no...?[n]Supongo que no me puedo escaquear...[n][w][e]

[msg msg_combine_PERSONA105 [Koppa Tengu]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu m茨scara, pero no me hagas[n]trabajar mucho, 斡夷estamos?![n][w][e]

[msg msg_combine_PERSONA106 [RESERVE]]
[s]X[n][w][e]

[msg msg_combine_PERSONA107 [RESERVE]]
[s]X[n][w][e]

[msg msg_combine_PERSONA108 [RESERVE]]
[s]X[n][w][e]

[msg msg_combine_PERSONA109 [RESERVE]]
[s]X[n][w][e]

[msg msg_combine_PERSONA110 [RESERVE]]
[s]X[n][w][e]

[msg msg_combine_PERSONA111 [RESERVE]]
[s]X[n][w][e]

[msg msg_combine_PERSONA112 [RESERVE]]
[s]X[n][w][e]

[msg msg_combine_PERSONA113 [RESERVE]]
[s]X[n][w][e]

[msg msg_combine_PERSONA114 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA115 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA116 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA117 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA118 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA119 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA120 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA121 [Mandr茨gora]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]夷Sientes una flor letal[n]que crece en tu coraz吋n? 斡Soy yo![n]斡Que esta m茨scara no se marchite![n][w][e]

[msg msg_combine_PERSONA122 [Baal]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Esta m茨scara que te otorgo,[n]oh, maestro de almas, traer茨[n]lluvia y fertilidad a la tierra...[n][w][e]

[msg msg_combine_PERSONA123 [Dakini]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Ah胤 est茨, con su nueva m茨scara![n]斡D姻jame a m胤 y har姻 que el poder[n]de tu coraz吋n explote![n][w][e]

[msg msg_combine_PERSONA124 [Silky]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]T雨, maestro, que has obtenido[n]una nueva m茨scara... Perm胤teme[n]ocuparme de tu coraz吋n.[n][w][e]

[msg msg_combine_PERSONA125 [Bugs]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]夷Eres t雨 el t胤o ese de la m茨scara?[n]Venga, colega, 斡vamos a jugar![n][w][e]

[msg msg_combine_PERSONA126 [Moco negro]]
[s]Yo [clr 1][var 1][clr 27]...[n][w][e]
[s]斡M-m-m-me... convertir姻 en m茨scara![n]斡Quiz茨 entonces adquiera forma...![n][w][e]

[msg msg_combine_PERSONA127 [Bicornio]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]斡Extraigo mi poder[n]de la inmoralidad! 斡Toma,[n]cuida de esta m茨scara por m胤![n][w][e]

[msg msg_combine_PERSONA128 [Mithras]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]T雨, que has obtenido mi m茨scara...[n]Ser姻 un rayo de esperanza[n]que brilla en tu coraz吋n.[n][w][e]

[msg msg_combine_PERSONA129 [Sudama]]
[s]斡S-soy [clr 1][var 1][clr 27]![n][w][e]
[s]斡Voy a ser tu m茨scara, t胤o![n]斡Voy a dejar de merodear por ah胤![n][w][e]

[msg msg_combine_PERSONA130 [Kodama]]
[s]斡Yo [clr 1][var 1][clr 27]![n][w][e]
[s]斡Me convertir姻 en una m茨scara[n]y te acompa隠ar姻! Resonar姻[n]en tu coraz吋n, t胤o... 斡Yuju![n][w][e]

[msg msg_combine_PERSONA131 [Agathion]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]斡Voy a ser tu nueva m茨scara![n]斡郁same, 雨same, 雨same![n][w][e]

[msg msg_combine_PERSONA132 [Onmoraki]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]斡Ser姻 tu m茨scara, amigo! 斡Estar姻[n]contigo hasta en el m茨s all茨![n][w][e]

[msg msg_combine_PERSONA133 [Nue]]
[s]Yo [clr 1][var 1][clr 27]...[n][w][e]
[s]Yo misterio. Ahora yo[n]nueva m茨scara. Placer conocerte.[n][w][e]

[msg msg_combine_PERSONA134 [Pisaca]]
[s]Soy [clr 1][var 1][clr 27]...[n][w][e]
[s]Tienes buena pinta, pero con eso[n]de que soy tu nueva m茨scara y tal,[n]casi que paso de comerte...[n][w][e]

[msg msg_combine_PERSONA135 [Melquisedec]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Dado que soy tu nueva m茨scara,[n]te ayudar姻 a proteger la justicia[n]con todo mi ser.[n][w][e]

[msg msg_combine_PERSONA136 [Baphomet]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Creo que voy a ser tu m茨scara.[n]Si combinamos nuestros poderes...[n][w][e]

[msg msg_combine_PERSONA137 [Raja Naga]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]斡El poder de mi clan[n]ha impregnado tu m茨scara![n][w][e]

[msg msg_combine_PERSONA138 [Naga]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Soy tu m茨scara, puedes confiar[n]en m胤... Bueno, no m茨s de lo que[n]conf胤as en la previsi吋n del tiempo.[n][w][e]

[msg msg_combine_PERSONA139 [Garuda]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara[n]y alzar姻 tu coraz吋n hasta el punto[n]m茨s celestial posible.[n][w][e]

[msg msg_combine_PERSONA140 [Moloch]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mi fuego infernal har茨 que tu alma[n]arda con un brillo carmes胤.[n]Ahora... acepta tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA141 [Norna]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]A ti, que posees la m茨scara...[n]Te deseo fortuna.[n][w][e]

[msg msg_combine_PERSONA142 [Belfegor]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Eres un t胤o, 夷no? Entonces[n]supongo que puedo convertirme[n]en tu m茨scara y unirme a ti...[n][w][e]

[msg msg_combine_PERSONA143 [Berith]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]No hay por qu姻 temer,[n]maestro de almas... Como tu m茨scara,[n]te ofrezco mi m茨s absoluta lealtad.[n][w][e]

[msg msg_combine_PERSONA144 [Choronzon]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Y pensar que volver胤an a invocarme...[n]Te otorgar姻 el poder maligno[n]que contiene esta m茨scara.[n][w][e]

[msg msg_combine_PERSONA145 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA146 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA147 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA148 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA149 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA150 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA151 [Nigi Mitama]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]La gentileza es una bendici吋n[n]que otorga calma. Ser姻 tu m茨scara[n]y sosegar姻 tu alma...[n][w][e]

[msg msg_combine_PERSONA152 [Kushi Mitama]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Le devolver姻 vigor a tu cuerpo.[n]Venga, 斡quiero conocer este mundo[n]y su misteriosa naturaleza![n][w][e]

[msg msg_combine_PERSONA153 [Ara Mitama]]
[s]斡Soy [clr 1][var 1][clr 27]![n][w][e]
[s]斡Hay que desatarse! 斡La fiereza[n]es mi aut姻ntico poder! 斡Tallar姻[n]mi ira salvaje en esa cara tuya![n][w][e]

[msg msg_combine_PERSONA154 [Saki Mitama]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Amor y simpat胤a es todo[n]lo que necesitas. Ser姻 tu m茨scara[n]y conocer茨s la pasi吋n m茨s intensa...[n][w][e]

[msg msg_combine_PERSONA155 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA156 [Shiva]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mostrar姻 mis poderes de destrucci吋n[n]y renacimiento. Bailemos juntos[n]gracias a esta m茨scara...[n][w][e]

[msg msg_combine_PERSONA157 [Miguel]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]En nombre de la luz de tu interior,[n]me convertir姻 en tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA158 [Asura]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Que mi luz destructora[n]pase a formar parte de tu m茨scara[n]y te conceda poder.[n][w][e]

[msg msg_combine_PERSONA159 [Mada]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Que este pozo infinito de poder...[n]que podr胤a tragarse el universo...[n]se convierta en tu m茨scara...[n][w][e]

[msg msg_combine_PERSONA160 [Ramera babil吋nica]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Lo impuro es bello, lo bello[n]es fuerte, y hay fuerza en ti. Soy[n]la reina de lo impuro, tu m茨scara...[n][w][e]

[msg msg_combine_PERSONA161 [Cloto]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]El hilo del destino no deja[n]de girar... Soy la m茨scara[n]que puede ver tu pasado...[n][w][e]

[msg msg_combine_PERSONA162 [L茨quesis]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mi mano controla el hilo[n]del destino... Soy la m茨scara[n]que determina tu futuro...[n][w][e]

[msg msg_combine_PERSONA163 [威tropos]]
[s]Soy [clr 1][var 1][clr 27]. [n][w][e]
[s]El hilo del destino no deja[n]de cortarse... Soy la m茨scara[n]que puede decidir tu vida...[n][w][e]

[msg msg_combine_PERSONA164 [Ardha]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Has obtenido la fuerza[n]de todo el universo. Celebr姻moslo[n]juntos, t雨 y yo.[n][w][e]

[msg msg_combine_PERSONA165 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA166 [Vishnu]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Preservar el universo, doblegar[n]el mal... Soy la manifestaci吋n[n]de tu alma, tu m茨scara invencible.[n][w][e]

[msg msg_combine_PERSONA167 [Hariti]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en m茨scara afectuosa[n]para protegerte, cual madre[n]que cuida de su d姻bil criatura...[n][w][e]

[msg msg_combine_PERSONA168 [Yurlungur]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Le conceder姻 a tu m茨scara[n]una fuerza que podr胤a unir[n]los cielos y la tierra.[n][w][e]

[msg msg_combine_PERSONA169 [Hecat吋nquiro]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Estas cien manos que han vencido[n]incontables guerras se unen ahora[n]en tu m茨scara![n][w][e]

[msg msg_combine_PERSONA170 [Satanael]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Matar胤as a dioses para proteger[n]la justicia en la que crees...[n]Muy bien, ser姻 tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA171 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA172 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA173 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA174 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA175 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA176 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA177 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA178 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA179 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA180 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA181 [Orfeo]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]夷Quieres que sea tu m茨scara?[n]Muy bien, busquemos las respuestas[n]al misterio de la vida.[n][w][e]

[msg msg_combine_PERSONA182 [T茨natos]]
[s]Soy [clr 1][var 1][clr 27]...[n][w][e]
[s]De ti nazco y contigo[n]recorrer姻 esta tierra...[n][w][e]

[msg msg_combine_PERSONA183 [Izanagi]]
[s]Soy [clr 1][var 1][clr 27]...[n][w][e]
[s]Abre los ojos... 斡威lzate...![n][w][e]

[msg msg_combine_PERSONA184 [Magatsu-Izanagi]]
[s]夷Qui姻n osa llamarme?[n][w][e]
[s]Aquel que refulge en la oscuridad[n]absoluta... 夷Hasta a la misma nada[n]te atreves a hacer tuya?[n][w][e]
[s]Soy [clr 1][var 1][clr 27].[n]Yo ser姻 testigo de tu viaje.[n][w][e]

[msg msg_combine_PERSONA185 [Kaguya]]
[s]夷Qui姻n osa llamarme?[n][w][e]
[s]Oh, coraz吋n que brilla en la noche...[n]Me convertir姻 en tu fuerza...[n][w][e]
[s]Soy [clr 1][var 1][clr 27].[n]Tu luz no se extinguir茨[n]mientras viva.[n][w][e]

[msg msg_combine_PERSONA186 [Ariadna]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡La victoria ser茨 tuya si esta[n]diosa se convierte en tu m茨scara![n][w][e]

[msg msg_combine_PERSONA187 [Asteri吋n]]
[s]斡Ja, ja, ja! 斡Soy [clr 1][var 1][clr 27]![n][w][e]
[s]夷Convertirme en tu m茨scara, dices?[n]*risita* Muy bien... Pero[n]斡te destruir姻 si bajas la guardia![n][w][e]

[msg msg_combine_PERSONA188 [Tsukiyomi]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mitad locura, mitad tenacidad...[n]Bueno, 斡夷a qui姻n[n]hay que destruir primero?![n][w][e]

[msg msg_combine_PERSONA189 [Mes胤as]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]De ahora en adelante,[n]mi existencia ser茨 la tuya...[n][w][e]

[msg msg_combine_PERSONA190 [Mes胤as P胤caro]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Al convertirme en la m茨scara[n]del Trickster, acepto estar[n]a tu lado de ahora en adelante...[n][w][e]

[msg msg_combine_PERSONA191 [Orfeo P胤caro]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]夷Quieres que sea la m茨scara[n]del Trickster? Bueno, supongo que[n]puedo ayudarte a limpiar tu nombre.[n][w][e]

[msg msg_combine_PERSONA192 [T茨natos P胤caro]]
[s]Soy [clr 1][var 1][clr 27]...[n][w][e]
[s]De ti nazco y contigo[n]recorrer姻 esta tierra...[n]Ser姻 la m茨scara del Trickster...[n][w][e]

[msg msg_combine_PERSONA193 [Izanagi P胤caro]]
[s]Soy [clr 1][var 1][clr 27]...[n][w][e]
[s]Abre los ojos...[n]斡Despierta, Trickster...![n][w][e]

[msg msg_combine_PERSONA194 [M. Izanagi P胤caro]]
[s]夷Qui姻n osa llamarme?[n][w][e]
[s]Aquel que refulge en la oscuridad[n]absoluta... 夷Hasta a la misma nada[n]te atreves a hacer tuya?[n][w][e]
[s]Soy [clr 1][var 1][clr 27].[n]Yo ser姻 testigo de tu viaje.[n][w][e]

[msg msg_combine_PERSONA195 [Kaguya P胤caro]]
[s]夷Qui姻n osa llamarme?[n][w][e]
[s]Oh, coraz吋n que brilla en la noche...[n]Me convertir姻 en tu fuerza,[n]Trickster...[n][w][e]
[s]Soy [clr 1][var 1][clr 27].[n]Tu luz no se extinguir茨[n]mientras viva.[n][w][e]

[msg msg_combine_PERSONA196 [Ariadna P胤caro]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡En guardia, Trickster![n]斡Me convertir姻 en tu m茨scara y[n]te seguir姻 donde quiera que vayas![n][w][e]

[msg msg_combine_PERSONA197 [Asteri吋n P胤caro]]
[s]斡Ja, ja, ja! 斡Soy [clr 1][var 1][clr 27]![n][w][e]
[s]Conque el Trickster quiere que me[n]convierta en su m茨scara... Muy bien...[n]斡Destruir姻 a quien te contrar胤e![n][w][e]

[msg msg_combine_PERSONA198 [Tsukiyomi P胤caro]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]夷Me he convertido en la m茨scara[n]del Trickster...? 斡Sea como sea,[n]causar姻 dolor como siempre![n][w][e]

[msg msg_combine_PERSONA199 [RESERVE]]
[s]038[n][w][e]

[msg msg_combine_PERSONA200 [RESERVE]]
[s]X[n][w][e]

[msg msg_combine_PERSONA201 [Ars因ne]]
[s]斡Soy el saqueador del crep雨sculo,[n][clr 1][var 1][clr 27]![n][w][e]
[s]夷Vuelves a necesitar mi ayuda?[n]Muy bien, usa mi poder sabiamente.[n][w][e]

[msg msg_combine_PERSONA202 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA203 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA204 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA205 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA206 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA207 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA208 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA209 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA210 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA211 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA212 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA213 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA214 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA215 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA216 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA217 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA218 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA219 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA220 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA221 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA222 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA223 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA224 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA225 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA226 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA227 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA228 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA229 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA230 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA231 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA232 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA233 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA234 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA235 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA236 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA237 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA238 [Capit茨n Kidd]]
[s]X[n][w][e]

[msg msg_combine_PERSONA239 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA240 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA241 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA242 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA243 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA244 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA245 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA246 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA247 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA248 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA249 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA250 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA251 [Capit茨n Kidd]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA252 [Sat茨n]]
[s]Soy [clr 1][var 1][clr 27],[n]juez de todas las cosas.[n][w][e]
[s]Oh, pecador que no conoce[n]el significado del miedo... Ser姻 tu[n]m茨scara y testigo hasta el final.[n][w][e]

[msg msg_combine_PERSONA253 [Lucifer]]
[s]Soy [clr 1][var 1][clr 27],[n]la estrella del alba[n]que se eleva sobre la oscuridad.[n][w][e]
[s]Aquel que trasciende[n]el sombr胤o mundo del coraz吋n...[n]Me convertir姻 en tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA254 [Kouryuu]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]El poder que mueve toda creaci吋n[n]se convertir茨 en tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA255 [Okuninushi]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mi espada, mi arco...[n]Aquello que form吋 este mundo[n]ahora te da poder como m茨scara.[n][w][e]

[msg msg_combine_PERSONA256 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA257 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA258 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA259 [Futsunushi]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Soy la deidad de las espadas[n]que una vez conquist吋 esta tierra.[n]Templar姻 el filo de tu coraz吋n.[n][w][e]

[msg msg_combine_PERSONA260 [Futsunushi]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA261 [Set]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]夷Codicias el poder de matar aunque[n]este te granjee odios? En tal caso,[n]yo ser姻 tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA262 [Ishtar]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Recibo el amor de toda la humanidad[n]y, por supuesto, tambi姻n el tuyo,[n]como tu m茨scara...[n][w][e]

[msg msg_combine_PERSONA263 [Ishtar]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA264 [Surt]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Gracias a mi m茨scara, har茨s arder[n]el mundo ante tus ojos[n]con el poder de mis llamas...[n][w][e]

[msg msg_combine_PERSONA265 [Sigfrido]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Tu alma catalizar茨 mi poder[n]y lo convertir茨[n]en una m茨scara imparable.[n][w][e]

[msg msg_combine_PERSONA266 [Laksm胤]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Basta de admirar mi belleza... Es[n]hora de convertirme en tu m茨scara[n]y ense隠arte la danza de la alegr胤a...[n][w][e]

[msg msg_combine_PERSONA267 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA268 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA269 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA270 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA271 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA272 [Fortuna]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Tu suerte va a cambiar. 斡De verdad![n]En fin, ah胤 va tu m茨scara[n]de la fortuna.[n][w][e]

[msg msg_combine_PERSONA273 [Suzaku]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]La luz ardiente que ilumina el[n]futuro es ahora tu nueva m茨scara...[n][w][e]

[msg msg_combine_PERSONA274 [Seiryu]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]El poder m茨s noble de las cuatro[n]bestias sagradas se convertir茨 en[n]m茨scara al servicio de este joven...[n][w][e]

[msg msg_combine_PERSONA275 [Genbu]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara[n]y emplear姻 mi sabidur胤a[n]para darte un futuro provechoso.[n][w][e]

[msg msg_combine_PERSONA276 [Byakko]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Mi rugido hace que todas[n]las bestias se postren ante m胤...![n]斡Yo ser姻 tu m茨scara![n][w][e]

[msg msg_combine_PERSONA277 [Bishamonten]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Tus enemigos no son nada al lado[n]de mi fuerza. 斡Ser姻 tu m茨scara[n]y te conceder姻 un nuevo poder...![n][w][e]

[msg msg_combine_PERSONA278 [Koumokuten]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Deja que yo vigile a los monstruos...[n]A cambio, te otorgar姻 una m茨scara[n]con la que gobernar el mundo...[n][w][e]

[msg msg_combine_PERSONA279 [Jikokuten]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mi obligaci吋n es mantener la paz[n]y la seguridad... 斡Ser姻 tu m茨scara[n]y te conceder姻 mi poder![n][w][e]

[msg msg_combine_PERSONA280 [Zouchouten]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mi poder hace desarrollarse[n]a quienes me veneran. Me convertir姻[n]en tu m茨scara y proteger姻 tu alma...[n][w][e]

[msg msg_combine_PERSONA281 [威ngel del infierno]]
[s]Mi nombre es [clr 1][var 1][clr 27].[n][w][e]
[s]El odio y la violencia son[n]lo mejor, 夷no te parece? 斡Ponte mi[n]m茨scara y empieza a repartir le隠a...![n][w][e]

[msg msg_combine_PERSONA282 [Daisoujou]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]T雨, cuyo cuerpo es inmune a la[n]podredumbre... Recibamos el inminente[n]d胤a de la salvaci吋n como uno solo...[n][w][e]

[msg msg_combine_PERSONA283 [Trompetista]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]El sonido de mis trompetas trae[n]calamidad y muerte... Ser姻 tu[n]m茨scara y tocaremos en armon胤a...[n][w][e]

[msg msg_combine_PERSONA284 [Jinete blanco]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Si ans胤as la victoria,[n]esta puede ser tuya... Tan solo[n]tienes que aceptar mi m茨scara...[n][w][e]

[msg msg_combine_PERSONA285 [Matador]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mi cuerpo, nacido[n]en el horror de la batalla, ser茨[n]tu m茨scara de ahora en adelante.[n][w][e]

[msg msg_combine_PERSONA286 [Jinete p茨lido]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Tu m茨scara estar茨 impregnada con el[n]poder de invocar letales[n]maldiciones del inframundo.[n][w][e]

[msg msg_combine_PERSONA287 [Horus]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Ser姻 tu m茨scara a partir de ahora![n]斡Volemos juntos hacia la luz![n][w][e]

[msg msg_combine_PERSONA288 [Horus]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA289 [Atis]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Liberar姻 la energ胤a m茨gica[n]de la sangre derramada...[n]Ahora, toma mi m茨scara.[n][w][e]

[msg msg_combine_PERSONA290 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA291 [RESERVE]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA292 [Sraosha]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mis o胤dos escuchar茨n todas[n]tus plegarias. Ser姻 tu m茨scara[n]y recompensar姻 tu noble alma.[n][w][e]

[msg msg_combine_PERSONA293 [Sraosha]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA294 [Sraosha]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA295 [Mitra]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Vigilo que se cumplan todos[n]los juramentos y soy quien[n]ha de convertirse en tu m茨scara...[n][w][e]

[msg msg_combine_PERSONA296 [F姻nix]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Todas las bestias aladas[n]est茨n a mis 吋rdenes... Ser姻[n]tu m茨scara y te conceder姻 paz...[n][w][e]

[msg msg_combine_PERSONA297 [Principado]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]El orden y la disciplina son lo[n]primero. Toma mi m茨scara[n]y defendamos juntos nuestro honor.[n][w][e]

[msg msg_combine_PERSONA298 [Neko Shogun]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]斡Tu futuro brilla m茨s que el sol![n]斡Yo ser姻 tu m茨scara![n][w][e]

[msg msg_combine_PERSONA299 [Vasuki]]
[s]Soy [clr 1][var 1][clr 27]...[n][w][e]
[s]La inmundicia es mi poder,[n]y por lo tanto, el tuyo tambi姻n.[n]Te otorgo pues esta m茨scara impura.[n][w][e]

[msg msg_combine_PERSONA300 [Ananta]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]El poder de la creaci吋n que ha[n]despertado en tu interior vivir茨 en[n]lo sucesivo dentro de tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA301 [Trono]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Te ayudar姻 a proteger[n]tu regia autoridad.[n]Ac姻ptame como tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA302 [Trono]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA303 [Quetzalc吋atl]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Brindo fertilidad y te guiar姻[n]hacia el futuro. Este fecundo[n]cuerpo ahora ser茨 tu m茨scara.[n][w][e]

[msg msg_combine_PERSONA304 [Jinete rojo]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara y te[n]mostrar姻 c吋mo ejerzo mi autoridad[n]sobre los perros de la guerra...[n][w][e]

[msg msg_combine_PERSONA305 [Jinete negro]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara y te[n]mostrar姻 mi poder haciendo padecer[n]desgracias a tus peores enemigos...[n][w][e]

[msg msg_combine_PERSONA306 [Sati]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA307 [Sati]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA308 [Pazuzu]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu m茨scara. Caminemos juntos[n]y tomemos las riendas[n]de este des姻rtico mundo.[n][w][e]

[msg msg_combine_PERSONA309 [Pazuzu]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA310 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA311 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA312 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA313 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA314 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA315 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA316 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA317 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA318 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA319 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA320 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA321 [Pazuzu]]
[s]X[n][w][e]

[msg msg_combine_PERSONA322 [Pazuzu]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA323 [Pazuzu]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA324 [Pazuzu]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA325 [Pazuzu]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA326 [Pazuzu]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA327 [Pazuzu]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA328 [Pazuzu]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA329 [Pazuzu]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA330 [Mar胤a]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Con mi coraz吋n misericordioso,[n]ser姻 tu m茨scara. [n][w][e]

[msg msg_combine_PERSONA331 [Vohu Manah]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu m茨scara[n]y alumbrar姻 las tinieblas. [n][w][e]

[msg msg_combine_PERSONA332 [Cait Sith]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Conmigo como tu mi茨uscara,[n]no tienes nada de que preocuparte![n][w][e]

[msg msg_combine_PERSONA333 [Mishaguji]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ahora que tienes mi m茨scara,[n]poseer茨s el poder de la naturaleza.[n][w][e]

[msg msg_combine_PERSONA334 [Loa]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu m茨scara[n]y beber姻, cantar姻 y bailar姻[n]como si no hubiera un ma隠ana. [n][w][e]

[msg msg_combine_PERSONA335 [Quimera]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Quiz茨 deber胤a convertirme[n]en tu m茨scara y dejar[n]que mi grotesco cuerpo descanse.  [n][w][e]

[msg msg_combine_PERSONA336 [Atavaka]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 tu m茨scara[n]y destruir姻 los esp胤ritus malignos. [n][w][e]

[msg msg_combine_PERSONA337 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA338 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA339 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA340 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA341 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA342 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA343 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA344 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA345 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA346 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA347 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA348 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA349 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA350 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA351 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA352 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA353 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA354 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA355 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA356 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA357 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA358 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA359 [Atavaka]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA360 [Izanagi-no-Okami]]
[s]Soy el dios original...[n][clr 1][var 1][clr 27]... [n][w][e]
[s]Desde el momento de mi creaci吋n,[n]he servido como luz gu胤a[n]que ilumina tu camino. [n][w][e]

[msg msg_combine_PERSONA361 [Izanagi-no-Okami]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA362 [Atenea]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mi mascar茨 har茨 las veces[n]del escudo que te proteja. [n][w][e]

[msg msg_combine_PERSONA363 [Raoul]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Has despertado mi verdadera forma![n]De acuerdo.[n]Contin雨a el camino en el que crees.[n][w][e]

[msg msg_combine_PERSONA364 [Raoul]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA365 [Orfeo]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]夷Yo debo convertirme en tu m茨scara?[n]En tal caso, caminar姻 a tu vera[n]y encontrar姻 el sentido de la vida. [n][w][e]

[msg msg_combine_PERSONA366 [Izanagi-no-Okami P胤c.]]
[s]Soy el dios original...[n][clr 1][var 1][clr 27]... [n][w][e]
[s]Ser茨s la m茨scara del Trickster,[n]y yo ser姻 una luz gu胤a[n]que iluminar茨 tu camino. [n][w][e]

[msg msg_combine_PERSONA367 [Izanagi-no-Okami P胤c.]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA368 [Atenea P胤caro]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Ser姻 la m茨scara del Trickster[n]y me convertir姻 en un escudo[n]que te proteger茨. [n][w][e]

[msg msg_combine_PERSONA369 [Atenea P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA370 [Atenea P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA371 [Orfeo P胤caro]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]夷La m茨scara del Trickster?[n]De acuerdo.[n]Puedo ayudarte a limpiar tu nombre. [n][w][e]

[msg msg_combine_PERSONA372 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA373 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA374 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA375 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA376 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA377 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA378 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA379 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA380 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA381 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA382 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA383 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA384 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA385 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA386 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA387 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA388 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA389 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA390 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA391 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA392 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA393 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA394 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA395 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA396 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA397 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA398 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA399 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA400 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA401 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA402 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA403 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA404 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA405 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA406 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA407 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA408 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA409 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA410 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA411 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA412 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA413 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA414 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA415 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA416 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA417 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA418 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA419 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA420 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA421 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA422 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA423 [Orfeo P胤caro]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA424 [Macabro]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara[n]y te guiar姻 hasta la danza[n]de la muerte.  [n][w][e]

[msg msg_combine_PERSONA425 [Alilat]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en una m茨scara[n]robusta y te proteger姻. [n][w][e]

[msg msg_combine_PERSONA426 [Ave del trueno]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]斡夷Puedes usar el poder[n]del esp胤ritu del ave?! [n][w][e]

[msg msg_combine_PERSONA427 [Fafnir]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Mientras tengas la m茨scara,[n]el oro ser茨 nuestro.[n][w][e]

[msg msg_combine_PERSONA428 [Byakhee]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]斡Si t雨 desear, yo pelear[n]con el alma que t雨 tener! [n][w][e]

[msg msg_combine_PERSONA429 [Hastur]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]La oscuridad es principio y fin.[n]Gobierna el mundo con mi m茨scara.[n]郁sala y apod姻rate del universo. [n][w][e]

[msg msg_combine_PERSONA430 [Tam Lin]]
[s]Soy el caballero de las hadas,[n][clr 1][var 1][clr 27]. [n][w][e]
[s]Ll茨mame cuando necesites mi ayuda.[n]斡Te abrir姻 un camino![n][w][e]

[msg msg_combine_PERSONA431 [Trono]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Observar姻 tu sendero de progreso.[n]Por favor, t吋mame como m茨scara. [n][w][e]

[msg msg_combine_PERSONA432 [Surt]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Gracias a mi m茨scara, har茨s arder[n]el mundo ante tus ojos[n]con el poder de mis llamas...[n][w][e]

[msg msg_combine_PERSONA433 [Loa]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]Ahora que soy tu m茨scara,[n]bebamos, cantemos y bailemos[n]como si no hubiera un ma隠ana. [n][w][e]

[msg msg_combine_PERSONA434 [Quimera]]
[s]Yo [clr 1][var 1][clr 27].[n][w][e]
[s]夷Crees poder controlar mi cuerpo,[n]aquel que has fusionado? [n][w][e]

[msg msg_combine_PERSONA435 [Atavaka]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Me convertir姻 en tu m茨scara[n]y destruir姻 los esp胤ritus malignos. [n][w][e]

[msg msg_combine_PERSONA436 [Cait Sith]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]斡Conmigo como tu mi茨uscara,[n]no tienes nada de que preocuparte![n][w][e]

[msg msg_combine_PERSONA437 [Sigfrido]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Tu alma catalizar茨 mi poder[n]y lo convertir茨[n]en una m茨scara imparable.[n][w][e]

[msg msg_combine_PERSONA438 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA439 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA440 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA441 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA442 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA443 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA444 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA445 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA446 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA447 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA448 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA449 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA450 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA451 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA452 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA453 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA454 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA455 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA456 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA457 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA458 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA459 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA460 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA461 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA462 [Sigfrido]]
[s]RESERVE[n][w][e]

[msg msg_combine_PERSONA463 [Sigfrido]]
[s]RESERVE[n][w][e]

