[msg MSG_001_0_0 [Joven ostentoso]]
[s][vp 8 0 0 0 65535 0]Ostras, 夷has visto a la mujer[n]con la que acabamos de cruzarnos?[n]斡Qu姻 bellez吋n![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Llevaba una bata blanca,[n]as胤 que ser茨 m姻dica.[n]斡Maaadre! 斡Me encanta![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Joven sabelotodo]]
[s][vp 8 0 0 0 65535 0]Eh, t胤o, rel茨jate,[n]que podr胤a ser la matasanos[n]de la que tanto se habla.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Joven ostentoso]]
[s][vp 8 0 0 0 65535 0]夷De esas que ni examinan ni nada[n]y recetan a lo loco?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Joven sabelotodo]]
[s][vp 8 0 0 0 65535 0]As胤 es. Parece que tiene una[n]consulta por aqu胤 cerca.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Un colega m胤o quer胤a pastillas para[n]dormir y se puso supercontento[n]cuando se las dio sin poner pegas.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Joven ostentoso]]
[s][vp 8 0 0 0 65535 0]Pero... Qu姻 movida.[n]夷Ser茨 solo una matasanos[n]o tambi姻n le faltar茨 la licencia?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Joven sabelotodo]]
[s][vp 8 0 0 0 65535 0]He mirado en internet[n]y es m姻dica de verdad.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aunque nunca ir胤a a su consulta.[n]Es muy arriesgado.[n][f 1 3 65535][w][e]

[msg ``MSG_0**_0_0`` [Joven sabelotodo]]
[s][vp 8 0 0 0 65535 0][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][vp 8 0 0 0 65535 0]Oye, 夷te has enterado?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Si vamos a su consulta,[n]podr胤amos conseguir[n]alg雨n medicamento potent胤simo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aunque se lo encarg茨ramos[n]a Ryuji...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mm, ser茨 mejor esperar a que se[n]pongan en contacto con nosotros.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][vp 8 0 0 0 65535 0]Anda, un mensaje de Ryuji.[n]Hablando del rey de Roma...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14][vp 8 0 0 0 65535 0]斡La he cagado![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Le he pedido el medicamento[n]a un m姻dico colega m胤o.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero dice que no me recetar茨[n]nada si estamos sanos. Qu姻 mierda.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Voy a preguntarles a otros,[n]pero ya es muy tarde...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Perdona por meterte en esto, t胤o,[n]pero necesito[n]que me eches un cable.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][vp 8 0 0 0 65535 0]Pf, ser茨 zopenco.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ya sabes qu姻 hacer, 夷no?[n]A hablar con la m姻dica.[n][f 1 3 65535][w][e]

