[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 65535 0]Chicos, 夷sab姻is lo que es[n]un tiro con truco?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Lo vi hace poco por la tele.[n]斡Molaba un mont吋n![n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Creo que se llamaba[n][clr 1]tiro con salto[clr 27].[n]斡Vamos a probar![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 0 65535 0][vp 8 0 0 0 65535 0]斡S胤! 斡Parece divertido![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 0 65535 0]Eh, 夷quieres intentar hacer[n]un tiro con truco?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Creo que se llamaba[n][clr 1]tiro por la espalda[clr 27].[n]夷Podremos hacerlo bien?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][vp 8 0 0 0 65535 0]No sabes ni como coger el taco.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 65535 0]Chicos, 斡vamos a intentar hacer[n]un tiro con truco![n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]斡Vamos a probar un tiro llamado[n][clr 1]mass姻[clr 27]![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Si tuviera dos piernas...[n]Vale, 斡te dejo ser el centro[n]de atenci吋n, [f 4 2]![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Vale, 斡vamos a intentar hacer[n]un tiro con truco![n][f 1 3 65535][w][e]

[msg MSG_007_0_0]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]斡Se te da muy bien![n]Seguramente ser茨s el t胤o m茨s guay...[n]despu姻s de m胤, por supuesto.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][vp 8 0 0 0 65535 0]Avanzar es poder.[n]La cosa pintaba muy bien[n]cuando estabas d茨ndolo todo.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][vp 8 0 0 0 65535 0]斡Todo listo![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][vp 8 0 0 0 65535 0]斡A punto![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 1 65535 0][vp 8 0 0 0 65535 0]斡Cuando quieras![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][vp 8 0 0 0 65535 0]Todo preparado.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][vp 8 0 0 0 65535 0]Todo a punto.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Haru]]
[s][bup 0 7 1 65535 0][vp 8 0 0 0 65535 0]斡Ya lo tienes![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][vp 8 0 0 0 65535 0]Preparaci吋n completada.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][vp 8 0 0 0 65535 0]斡Ya est茨 todo listo![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][vp 8 0 0 0 65535 0]Adelante.[n][f 1 3 65535][w][e]

