[msg MSG_000_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ponte c吋modo.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Es agradable y est茨 recogida.[e]
[s]Estoy nervioso.[e]

[msg MSG_002_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se dice que si tienes la habitaci吋n[n]desordenada, tendr茨s el coraz吋n igual.[n]Bueno, Kasumi siempre lo repet胤a.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷En serio? Qu姻 sorpresa.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, gracias por sacar tiempo[n]para venir hoy.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quer胤a hablarte aqu胤 porque es[n]donde me siento m茨s cerca[n]de mi hermana...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Casi todo en esta habitaci吋n[n]es igual que en la de Kasumi.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Los colores son diferentes, y para de contar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Siempre ha sido as胤. Siempre quise[n]que todo lo m胤o fuera igual[n]que lo de Kasumi.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]La quer胤as mucho.[e]
[s]La admirabas.[e]

[msg MSG_007_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Admito que, al tener tanto talento,[n]a veces me sent胤a inferior, incluso[n]celosa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero el amor que sent胤a por ella[n]era m茨s fuerte. Siempre quise[n]parecerme a ella en todo lo posible.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nunca habr胤a imaginado que[n]acabar胤a viviendo como si fuera ella.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La verdad es que... En general,[n]le estoy agradecida al doctor Maruki.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]夷Agradecida por qu姻?[e]
[s]夷Qu姻 quieres decir?[e]

[msg MSG_011_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, 姻l me demostr吋 que pod胤a[n]vivir mi vida igual que Kasumi[n]vivi吋 la suya.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ahora entiendo que no fue[n]la mejor manera de abordarlo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aun as胤, de no haber sucedido,[n]dudo que hubiera podido[n]seguir adelante.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero despu姻s de vivir como Kasumi[n]y conocerte, [f 4 2]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Fui consciente de que lo que estaba[n]haciendo era un error.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es por eso que, por raro que suene,[n]agradezco lo que hizo[n]el doctor Maruki.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por eso mismo quiero hablar con 姻l.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quiero demostrarle que pude[n]enfrentarme a m胤 misma y que 姻l[n]tambi姻n se replantee sus actos.[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]As胤 me gusta.[e]
[s]Estar姻 ah胤 para ayudarte.[e]

[msg MSG_016_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡S胤![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Har姻 todo lo que pueda para ser[n]la Sumire Yoshizawa m茨s fuerte![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Este es mi poder...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gracias, [f 4 2].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si no te hubiera conocido, nunca[n]habr胤a encontrado la fortaleza[n]para enfrentarme a m胤 misma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por eso mismo... eres mi h姻roe.[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]Bueno, sigamos.[e]
[s]夷Aunque sea un Ladr吋n Fantasma?[e]

[msg MSG_020_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡S胤! 斡Vamos a esforzarnos a tope![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Ten胤as que sacar ese tema ahora?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Da igual. Sigues siendo mi h姻roe[n]a pesar de ser un Ladr吋n Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vaya, mira qu姻 hora es... Bueno,[n]gracias por venir hoy.[n][f 1 3 65535][w][e]

