[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Eh? 夷Qu姻 es este lugar?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Es el castillo de Kamoshida.[e]
[s]夷Y ese color?[e]
[s]夷Una emisora de televisi吋n?[e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No, es evidente que no.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Creo que es un estudio de grabaci吋n[n]para la tele, pero qu姻 colores m茨s raros...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Este sitio parece un estudio de[n]grabaci吋n en una emisora.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eso parece, pero los colores[n]son muy raros...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Estos tipos son parte de la[n]cognici吋n de Kamoshida?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡夷Y vosotros qui姻nes narices sois?![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Que no me ignores![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Hala![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Mira, mira![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Un momento, 斡夷no es ese Kamoshida?![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ayudante de direcci吋n veterano]]
[s][vp 8 2 0 0 65535 0]斡Volvemos de los anuncios![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Siete, seis, cinco segundos para empezar, cuatro, tres...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Locutora animada]]
[s][vp 8 2 0 0 9 0]Y ahora pasamos a nuestro[n]或Encuentro de actualidad位. Este a隠o es el[n]cuarto desde el mundial...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 9 0]Hoy est茨 aqu胤 el capit茨n del equipo[n]masculino de voleibol que gan吋[n]el 雨ltimo mundial: Suguro Kamoshida.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hola, soy Kamoshida,[n]es un honor estar aqu胤 hoy...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pero 斡si es 姻l! 夷No es muy joven?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No s姻 qu姻 est茨 pasando...[n]Sigamos vi姻ndolo.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]斡Vaya, qu姻 popular! 斡Y seguro[n]que no has cambiado nada desde[n]que te hiciste profesional![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]N-ni por asomo.[n]No tengo nada especial.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]夷Lo dices en serio?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Locutora animada]]
[s][vp 8 2 0 0 9 0]Sin duda. Ahora sales en varios[n]anuncios y tienes otras cosillas[n]pendientes.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 9 0]Y despu姻s de firmar tu contrato[n]profesional, donaste la mitad de los[n]beneficios a tu instituto.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]斡Exacto! 斡Una persona normal[n]no habr胤a hecho eso![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]Bueno, hoy te queremos pedir un[n]favorcillo especial, se隠or atleta.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Ah, claro![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]斡Hala, c吋mo brilla![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 8 0]斡Todav胤a recuerdo tu remate[n]final! 夷C吋mo te sentiste[n]en ese momento?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bueno, estaba en plan[n]或斡lo he logrado!位, no s姻,[n]superfeliz.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]夷Sentiste presi吋n[n]por ser el capit茨n?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]En cierta forma, s胤. Tengo que[n]entrenar y tambi姻n ocuparme[n]de mis compa隠eros.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]La parte m茨s dura fue no fallar en[n]mis responsabilidades como capit茨n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Igual que ahora mismo.[n]Hablar delante de gente[n]no es lo m胤o, pero...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]夷Qu姻? 夷De verdad? 斡Nadie lo dir胤a![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ja, ja, 夷tengo pinta de que[n]se me de bien la gente?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Locutora animada]]
[s][vp 8 2 0 0 9 0]Entiendo c吋mo te sientes.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Locutora animada]]
[s][vp 8 2 0 0 9 0]Todo trabajo que requiera estar[n]de cara al p雨blico es muy[n]duro, 夷no crees?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 9 0]Siempre que veo una c茨mara,[n]enciendo el piloto de 或actuaci吋n位.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 9 0]A lo mejor es que es dif胤cil ser yo mismo.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡...![n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Locutora animada]]
[s][vp 8 2 0 0 9 0]斡Eres incre胤ble, Kamoshida![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 9 0]斡Estuviste genial en la entrevista[n]que te hicieron cuando ganaste![n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]En su 姻poca de instituto, la chica[n]estaba en el club de voleibol y[n]era tu mayor fan, Kamoshida.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡夷Qu姻?![n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Locutora animada]]
[s][vp 8 2 0 0 9 0]斡Y tanto! Si no te importa,[n]podr胤amos hablar un poco[n]m茨s luego.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]斡Hala, hala! 夷Marc茨ndote[n]un tanto en riguroso directo?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]Bueno, ya la has o胤do, Kamoshida.[n]夷Qu姻 dices?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Kamoshida]]
[s][bup 0 202 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Eh? Ah, bueno...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Maestro de ceremonias hablador]]
[s][vp 8 2 0 0 8 0]夷Te est茨s poniendo rojo, Kamoshida?[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Se ha parado... 夷Qu姻 narices era eso?[n][f 1 3 65535][w][e]

[sel SEL_041_0_0 top]
[s]Qu姻 joven estaba Kamoshida.[e]
[s]Debemos estar en el Palacio.[e]

[msg MSG_042_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]S胤, era 姻l.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Le胤 que hab胤a ganado la medalla[n]de oro en el 雨ltimo mundial,[n]pero 夷eso no fue hace mucho?[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No recuerdo salir del Palacio...[n]Y Kamoshida parec胤a muy joven, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]O胤 que hab胤a ganado la medalla[n]de oro en el 雨ltimo mundial,[n]pero 夷eso no fue hace mucho?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Eh? 夷Kamoshida de joven?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Eso quiere decir... que ese[n]era el pasado de Kamoshida?[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡夷El pasado de Kamoshida?![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Claro, un Palacio es[n]el interior del coraz吋n[n]de una persona.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No ser胤a extra隠o que pudi姻ramos[n]ver recuerdos que son importantes[n]para esa persona.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Cosas que no pueden olvidar,[n]o que quieren olvidar pero[n]no pueden...[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Me importa una mierda el pasado[n]de ese cabr吋n![n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Kamoshida seguramente tampoco[n]quer胤a que lo vi姻ramos. Fijo que[n]se le va la olla si seguimos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Por otra parte, si entendemos[n]el coraz吋n del due隠o del[n]Palacio, nos orientaremos mejor.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]C吋mo era el dicho...[n]夷或Conoce a tu enemigo位?[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Exacto, hay que estar atentos por[n]si aparecen puertas similares.[n][f 1 3 65535][w][e]

[msg SYS_051_0_0]
[s]Hay puertas ocultas en los Palacios[n]que guardan recuerdos del pasado[n]del due隠o del Palacio.[n][f 1 3 65535][w][e]
[s]Abrir esas puertas te permitir茨[n]moverte por el Palacio con[n]m茨s facilidad.[n][f 1 3 65535][w][e]

