[msg MSG_000_0_0 [スーツの男A]]
[s][vp 8 0 0 1 65535 0]Supongo que el f茨rmaco[n]era demasiado fuerte...[n][f 1 2 75][e]

[msg MSG_000_5_0 [スーツの男A]]
[s][vp 8 0 0 2 65535 0]Despi姻rtalo.[n][f 1 2 21][e]

[msg MSG_001_0_0 [スーツの男A]]
[s][vp 8 0 0 3 65535 0]Nada de siestecitas.[n][f 1 2 35][e]

[msg MSG_002_0_0 [スーツの男A]]
[s][vp 6 0 0 4 6 0]Sigues sin pillarlo, 夷verdad?[n][f 1 2 56][e]

[msg MSG_003_0_0 [スーツの男A]]
[s][vp 6 0 0 5 6 0]斡R胤ndete![n][f 1 2 40][e]

[msg MSG_004_0_0 [スーツの男A]]
[s]No te quedan fuerzas, 夷eh?[n][f 1 2 48][e]

[msg MSG_005_0_0 [スーツの男A]]
[s]斡Di algo![n][f 1 2 54][e]

[msg MSG_006_0_0 [(SE)主人公]]
[s][vp 8 0 0 8 65535 0]Aj... *tos*[n][f 1 2 65][e]

[msg MSG_006_5_0 [スーツの男A]]
[s][vp 6 0 0 9 6 0]Venga, colabora.[n]夷O quieres otra inyecci吋n?[n][f 1 2 162][e]

[msg MSG_007_0_0 [スーツの男A]]
[s][vp 6 0 0 10 6 0]夷Eh? 夷Qu姻 pasa con la c茨mara?[n][f 1 2 78][e]

[msg MSG_008_0_0 [スーツの男A]]
[s][vp 8 0 0 11 65535 0]夷Crees que la grabaci吋n[n]se podr茨 usar como prueba?[n][f 1 2 100][e]

[sel SEL_010_0_0 top]
[s]Claro que no...[e]
[s]夷Qu姻 quieres decir...?[e]
[s]...[e]

[msg MSG_011_0_0 [スーツの男A]]
[s][vp 6 0 0 12 6 0]As胤 que no eres tan tonto.[n][f 1 2 65][e]

[msg MSG_012_0_0 [スーツの男A]]
[s][vp 6 0 0 13 6 0]Eso es bueno, porque nostomaremos el tiempo necesario.[n][f 1 2 155][e]

[msg MSG_013_0_0 [スーツの男A]]
[s][vp 6 0 0 14 6 0]夷A雨n no lo has adivinado?[n][f 1 2 65][e]

[msg MSG_014_0_0 [スーツの男A]]
[s][vp 6 0 0 15 6 0]斡No hay leyes que protejan[n]a los criminales como t雨![n][f 1 2 140][e]

[msg MSG_015_0_0 [スーツの男A]]
[s][vp 6 0 0 16 6 0]夷No has o胤do mi pregunta?[n]斡Contesta![n][f 1 2 90][e]

[msg MSG_016_0_0 [(SE)主人公]]
[s][vp 8 0 0 17 65535 0]*tos* 斡Aj...! *jadeo*[n][f 1 2 90][e]

[msg MSG_017_0_0 [スーツの男A]]
[s][vp 6 0 0 18 6 0]Obstrucci吋n a la justicia, chantaje,[n]difamaci吋n, posesi吋n de armas...[n][f 1 2 160][e]

[msg MSG_018_0_0 [スーツの男A]]
[s][vp 6 0 0 19 6 0]Homicidio imprudente[n]tambi姻n, 夷no? Menudo historial.[n][f 1 2 155][e]

[msg MSG_019_0_0 [スーツの男A]]
[s][vp 6 0 0 20 6 0]Y pensar que esos delitos[n]los instig吋 un ni隠ato como t雨...[n][f 1 2 125][e]

[msg MSG_020_0_0 [スーツの男A]]
[s][vp 6 0 0 21 6 0]Disfrutaste cada segundo, 夷verdad?[n][f 1 2 135][e]

[msg MSG_020_5_0 [スーツの男A]]
[s]...[n][f 1 2 1][e]

[sel SEL_021_0_0 top]
[s]S胤...[e]
[s]No me acuerdo...[e]
[s]...[e]

[msg MSG_022_0_0 [スーツの男A]]
[s][vp 6 0 0 22 6 0]Me alegro por ti.[n]No volver茨 a ocurrir.[n][f 1 2 130][e]

[msg MSG_023_0_0 [スーツの男A]]
[s][vp 6 0 0 23 6 0]斡夷Qu姻?! 斡Fuiste t雨![n][f 1 2 95][e]

[msg MSG_024_0_0 [スーツの男A]]
[s][vp 6 0 0 24 6 0]Deber胤as saber cu茨l es tu lugar.[n][f 1 2 70][e]

[msg MSG_025_0_0 [スーツの男A]]
[s][vp 8 0 0 25 65535 0]Firma aqu胤.[n][f 1 2 55][e]

[msg MSG_026_0_0 [スーツの男A]]
[s][vp 8 0 0 26 65535 0]Es una confesi吋n a tu nombre.[n][f 1 2 65][e]

[sel SEL_027_0_0 top]
[s]Entiendo...[e]
[s]...[e]

[msg MSG_028_0_0 [スーツの男A]]
[s][vp 6 0 0 27 6 0]Ya veo...[n][f 1 2 45][e]

[msg MSG_029_0_0 [スーツの男A]]
[s][vp 6 0 0 28 6 0]Necesito que firmes esto, pero...[n][f 1 2 80][e]

[msg MSG_030_0_0 [(SE)主人公]]
[s][vp 8 0 0 29 65535 0]斡Aj![n][f 1 2 25][e]

[msg MSG_031_0_0 [スーツの男A]]
[s][vp 6 0 0 30 6 0]No me importa que[n]pierdas una pierna.[n][f 1 2 85][e]

[msg MSG_032_0_0 [スーツの男A]]
[s][vp 6 0 0 31 6 0]De aqu胤 no saldr茨s[n]de una pieza.[n][f 1 2 80][e]

[msg MSG_033_0_0 [スーツの男A]]
[s][vp 6 0 0 32 6 0]Lo vas a entender por las buenas[n]o por las malas.[n][f 1 2 65][e]

[msg MSG_032_5_0 [スーツの男A]]
[s][vp 6 0 0 33 6 0]Uno debe asumir toda[n]la responsabilidad de sus actos.[n][f 1 2 105][e]

