[msg TalkMsg_01 [Sombra de Fukurai]]
[s]斡Hazme caso![n][w][e]

[msg TalkMsg_02 [Sombra de Fukurai]]
[s]斡Eh, que me hagas caso![n][w][e]

[msg TalkMsg_03 [Sombra de Fukurai]]
[s]斡No voy a hablar contigo de eso![n][w][e]

[msg TalkMsg_04 [Sombra de Fukurai]]
[s]夷C吋mo? 夷No quieres hablar[n]de algo que te beneficie m茨s?[n][w][e]

[msg TalkMsg_05 [Sombra de Fukurai]]
[s]夷El tesoro...?[n][w][e]

[msg TalkMsg_06 [Sombra de Fukurai]]
[s]斡Da lo mismo![n][w][e]

[msg TalkMsg_07 [Sombra de Fukurai]]
[s]斡Espera, por favor![n][w][e]

[msg TalkMsg_08 [Sombra de Fukurai]]
[s]Eh, 夷no ibas a decir algo?[n][w][e]

[sel TalkSel_01 top]
[s]Hablemos de Chihaya.[e]
[s]Hablemos de dinero.[e]
[s]Hablemos sobre el tesoro.[e]

[sel TalkSel_02 top]
[s]H茨blame de Chihaya...[e]
[s]H茨blame de dinero...[e]
[s]H茨blame del tesoro...[e]

[sel TalkSel_03 top]
[s]D茨melo.[e]
[s]Entr姻gamelo.[e]
[s]Lo quiero ya.[e]

