[msg TalkMsg_DUMMY]
[s]...[n][w][e]

[msg TalkMsg_GUY_CONTACT_01]
[s]Uf, qu姻 fuerte eres...[n][w][e]

[msg TalkMsg_GUY_CONTACT_02]
[s]Eres demasiado insistente.[n]A nadie le gusta esa actitud.[n][w][e]

[msg TalkMsg_GUY_CONTACT_03]
[s]Maldita sea... 夷Otra vez esto?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01]
[s]Asaltas nuestro territorio y act雨as[n]como si estuvieses en tu casa...[n][w][e]
[s]夷Qui姻n narices te has cre胤do[n]que eres?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_01 top]
[s]Me siento mal por ello.[e]
[s]斡Soy yo![e]
[s]No te debo una respuesta.[e]

[msg TalkMsg_GUY_CHAT_FQ_01_R]
[s]Mmm, las apariencias enga隠an.[n]Parece que contigo[n]se puede razonar.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_2]
[s]S胤, s胤, muy bien.[n]Los ni隠os deben ser obedientes.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_3]
[s]Si es cierto, vete. Tus acciones[n]difieren mucho de tus palabras.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_4]
[s]Si las disculpas bastasen,[n]no har胤a falta la justicia, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_5]
[s]夷Intentas ser guay?[n]A ver, no es que[n]no lo entienda, pero...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_6]
[s]斡Ja, ja! Imaginaba que dir胤as[n]algo as胤. Me parece incre胤ble[n]que lo hayas hecho.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_7]
[s]No abras la boca si no entiendes[n]la pregunta, ni隠ato.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_8]
[s]斡Cierra el pico, imb姻cil![n]Qu姻 ganas de darte un pu隠etazo[n]en ese careto de arrogante.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_9]
[s]夷Sabes con qui姻n est茨s[n]hablando? 斡Resp吋ndeme,[n]pedazo de zoquete![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_10]
[s]Pues c茨llate. Tanta ch茨chara[n]me pone de los nervios.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_11]
[s]Yo, bueno... Tienes raz吋n.[n]No hab胤a ca胤do.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_12]
[s]Ya veo que est茨s en la edad[n]del pavo. 夷Est茨s intentando[n]llamar la atenci吋n?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_13]
[s]斡C茨lmate! Solo quer胤a hablar.[n]No quiero que[n]desperdicies las balas.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_14]
[s]Bien... A los chavales de hoy d胤a[n]les faltan agallas, pero todav胤a[n]queda gente como t雨, 夷eh?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_15]
[s]夷Crees que me da miedo?[n]No tienes ni idea de lo que[n]pasar茨 si entra un intruso.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_16]
[s]夷Abres fuego cuando intentaba[n]mantener una charla amistosa?[n]斡Qu姻 poca educaci吋n![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02]
[s]Bah, abandono. 夷Mi hor吋scopo dec胤a[n]que hoy tendr胤a mala suerte?[n][w][e]
[s]Pues nada, haz lo que quieras.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_02 top]
[s]Necesito tu ayuda.[e]
[s]L胤mpiame los zapatos con la lengua.[e]
[s]夷Seguro que est茨 bien?[e]

[msg TalkMsg_GUY_CHAT_FQ_02_R]
[s]Creo que tendr茨s que darme[n]m茨s detalles.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_2]
[s]夷Me pides ayuda mientras[n]me apuntas con un arma?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_3]
[s]斡Soy yo quien necesita ayuda![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_4]
[s]Dime con claridad lo que quieres.[n]Tal y como hablas, dir胤a que[n]la expresi吋n no es lo tuyo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_5]
[s]斡Vale, pero cuidadito con lo que[n]dices! 斡Eres una verg鵜enza[n]para tus padres![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_6]
[s]No pasa nada, pero 夷qui姻n los ha[n]hecho? Me fastidia[n]que no se vea la marca.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_7]
[s]No creo que sea necesario.[n]夷Esta es tu afici吋n?[n]夷Lo saben tus amigos?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_8]
[s]夷Solo eso? Qu姻 f茨cil. Ten,[n]ponte estos zapatos brillantes.[n]斡Est茨n como nuevos![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_9]
[s]He dicho que vale. No me[n]hagas repetirlo. 夷Cu茨ntas veces[n]vas a preguntar?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_10]
[s]Veo los ojos tras la m茨scara[n]brillar con curiosidad... Solo[n]pido que no sea doloroso.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_11]
[s]S胤, vale. Si me puedes[n]ofrecer algo mejor que[n]andar por aqu胤... Mmm.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_12]
[s]夷Qu姻 dices? 夷Est茨s insinuando[n]que miento? Lo de las interacciones[n]sociales se te da fatal, 夷eh?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_13]
[s]斡夷Qu姻姻姻?! 斡Me has disparado![n]斡夷Era de verdad?![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_14]
[s]夷Qu姻 narices...?[n]Ni siquiera te ha temblado el pulso.[n]斡Hasta has quitado el seguro![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_15]
[s]E-entiendo lo que dices. Vamos[n]a evitar que esto se desmadre.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_16]
[s]Dispararle a algo que no os gusta...[n]斡No sois los Ladrones Fantasma![n]斡Sois unos matones![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03]
[s]Si lo que deseas son objetos,[n]podemos llegar a un acuerdo. Aunque[n]vas tras aquel al que sirvo, 夷no?[n][w][e]
[s]夷Por qu姻 no lo pasas por alto?[n]Hagamos un trato.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_03 top]
[s]Vale.[e]
[s]夷Un trato con el enemigo?[e]
[s]No puedo confiar en ti.[e]

[msg TalkMsg_GUY_CHAT_FQ_03_R]
[s]Espl姻ndido. He venido a ti con[n]esta tarea porque sab胤a que[n]aceptar胤as realizarla.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_2]
[s]Entonces, 夷te importar胤a responder[n]a unas preguntas relacionadas[n]con la transacci吋n?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_3]
[s]Qu姻 forma de hablar m茨s arrogante.[n]Mira, esto es un intercambio,[n]no una rendici吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_4]
[s]Ah, 夷tan poco importo?[n]Es dif胤cil de procesar.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_5]
[s]No has medido bien tus palabras,[n]夷a que no? Los de tu clase[n]sois todos unos abusones, seguro.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_6]
[s]Mira, esto no va de con qui姻n[n]se negocia, sino del tipo de acuerdo[n]al que se llega, 夷lo pillas?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_7]
[s]斡Las apariencias enga隠an![n]Hablamos tranquilamente, 夷no?[n]Podemos llegar a acuerdo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_8]
[s]夷Y qu姻 pasa? 斡夷C吋mo te atreves a[n]decir eso cuando me he rebajado[n]a tu nivel para hablar contigo?![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_9]
[s]Tiene todo el sentido del mundo.[n]Hasta hace un momento, pensaba que[n]acabar胤amos mat茨ndonos.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_10]
[s]Si es as胤, no te preocupes.[n]No quiero que conf胤es en m胤,[n]sino que hagas la vista gorda.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_11]
[s]夷Por qu姻 temes a un oponente que[n]suplica por su vida? 夷Acaso eres[n]m茨s cobarde de lo que aparentas?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_12]
[s]斡Esa no es la respuesta[n]que quer胤a! 斡夷Vamos a hacer[n]un trato o qu姻 pasa?![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_13]
[s]夷Vas a matar a alguien que suplica[n]por su vida? Qu姻 cruel. Aunque yo[n]ya lo he hecho antes...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_14]
[s]夷Balas en lugar de respuestas?[n]Estos cr胤os de hoy en d胤a...[n]Por lo menos tienes estilo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_15]
[s]Qu姻 inocente he sido creyendo[n]que podr胤a hablar con alguien[n]incapaz de negociar...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_16]
[s]No sabes c吋mo me he sentido...[n]Me he tragado la verg鵜enza para[n]hacer un trato as胤... 斡Aj, no puedo![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04]
[s]夷As胤 tratas a un enemigo en[n]apuros despu姻s de derrotarlo?[n][w][e]
[s]Pero 夷te gustar胤a que[n]te hiciera pedazos?[n]夷De qu姻 color manar胤a tu sangre?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_04 top]
[s]Rojo.[e]
[s]Verde.[e]
[s]No sangro ni lloro.[e]

[msg TalkMsg_GUY_CHAT_FQ_04_R]
[s]Je, que era broma. Deja que[n]me ahorre las respuestas de verdad.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_2]
[s]夷En serio? 夷A pesar de cometer[n]semejantes atrocidades? 夷Te abrimos[n]para comprobarlo?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_3]
[s]夷Qu姻? 夷Sigues afirmando[n]que eres 或humano位 hasta la m姻dula?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_4]
[s]Buf, espesa como el lodo, sin duda.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_5]
[s]斡Ja, ja! 夷Verde? 夷En serio?[n]No puedes ser humano si eres[n]tan cruel.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_6]
[s]Eres la primera persona[n]que me lo dice. Arr茨ncate el dedo[n]de un mordisco y mu姻stramelo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_7]
[s]夷Eh? 夷Qu姻 clase de broma es esta?[n]夷De verdad esperas que me crea[n]que eres un extraterrestre?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_8]
[s]Conque es eso. Por favor...[n]夷Eres solo t雨 o tu familia tambi姻n[n]es igual?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_9]
[s]夷No muestras emoci吋n alguna a tus[n]rivales? Eres muy machito, pero[n]as胤 solo te granjear茨s m茨s enemigos.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_10]
[s]夷Qu姻 has dicho? Entonces...[n]夷no eres humano? La cara bajo[n]la m茨scara... 斡夷Es...?![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_11]
[s]No... No deber胤as estar aqu胤.[n]Tienes que ir al hospital.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_12]
[s]No te hagas el chulo, chaval.[n]夷Te crees especial?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_13]
[s]Ah, 夷que no quieres hablar?[n]Normal. M茨tame. 斡Venga![n]斡Ja, ja, ja, ja, ja![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_14]
[s]Uy, perd吋name. Dejemos de hablar[n]del color de la sangre y cambiemos[n]de tema, 夷vale?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_15]
[s]Uy, qu姻 extra隠o, pero supongo[n]que no lo sabes. Vale,[n]cambiemos de tema...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_16]
[s]Emplear una estrategia que apela[n]a las emociones de un chico[n]poco inteligente no sirve de nada.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05]
[s]Venga, calm姻monos[n]y hablemos un poco. Respira hondo[n]y escucha con atenci吋n...[n][w][e]
[s]夷Y si yo fuese humano?[n]斡Lo que est茨s a punto de hacer[n]ser胤a un crimen![n][w][e]

[sel TalkSel_GUY_CHAT_FQ_05 top]
[s]Es verdad...[e]
[s]No puede ser cierto.[e]
[s]Es irrelevante.[e]

[msg TalkMsg_GUY_CHAT_FQ_05_R]
[s]斡Admirable! Has hecho[n]bien reconoci姻ndolo. Tu madre[n]estar茨 muy orgullosa de ti.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_2]
[s]夷Verdad? Si es as胤, me gustar胤a[n]que parases con esta locura.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_3]
[s]夷A que s胤? Si no paras, la gente[n]te llamar茨 criminal a tus espaldas[n]durante el resto de tu vida.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_4]
[s]Si lo has entendido, 斡qu胤tame eso[n]de las narices! Al fin y al cabo,[n]cometer un delito no vale la pena.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_5]
[s]斡No vengas con fantochadas[n]pseudofilos吋ficas! 斡Eres un ni隠ato![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_6]
[s]No saques conclusiones[n]precipitadas porque te[n]arrepentir茨s. Lo digo por tu bien.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_7]
[s]夷Que la probabilidad de que esto[n]sea un delito es cero?[n]Dudo que puedas demostrarlo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_8]
[s]夷Puedes afirmarlo con certeza?[n]Ya sab胤as qu姻 clase de lugar[n]era este cuando viniste.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_9]
[s]夷Matar a un enemigo que te molesta?[n]Tienes m茨s de psic吋pata[n]que de Ladr吋n Fantasma.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_10]
[s]斡Claro que tiene que ver! 斡Tendr茨s[n]antecedentes penales y te costar茨[n]la vida conseguir un empleo![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_11]
[s]夷Vas a desperdiciar la vida[n]tan joven? Pero 斡si te aguarda[n]mucha diversi吋n![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_12]
[s]Bueno, si tan claro lo tienes,[n]prep茨rate para vivir[n]entre rejas.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_13]
[s]斡Lo entiendo! Disculpa si te he[n]ofendido. Deja que te lo demuestre.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_14]
[s]斡No seas tan impulsivo! 斡Eres[n]miembro de la sociedad,[n]no puedes hacer algo as胤![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_15]
[s]夷Tampoco vas a dejar[n]que me defienda? Razonar contigo[n]es como hablar con una pared.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_16]
[s]斡Espera un momento! Piensa[n]en tu futuro. 夷Qui姻n se casar胤a[n]con alguien tan violento?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06]
[s]Me pregunto si es para m胤.[n][w][e]
[s]Si hubiese sabido que esto iba[n]a pasar, habr胤a tenido el valor[n]de pedirle salir a aquella chica.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_06 top]
[s]No es demasiado tarde.[e]
[s]Nunca tuviste oportunidad.[e]
[s]Me asegurar姻 de que sea feliz.[e]

[msg TalkMsg_GUY_CHAT_FQ_06_R]
[s]夷Quieres decir que me dejas ir?    [n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_2]
[s]No me esperaba para nada[n]que acabaras anim茨ndome.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_3]
[s]En ese caso, 夷te importa[n]bajar el arma?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_4]
[s]Creo que dejar las cosas as胤[n]ser胤a de lo m茨s conmovedor.[n]Una conclusi吋n muy po姻tica.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_5]
[s]夷Siempre eres tan negativo?[n]No conseguir茨s pareja[n]con esa actitud.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_6]
[s]Si dije tal cosa, no podr胤a seguir[n]adelante. Qu姻 bien que me haya dado[n]cuenta ahora, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_7]
[s]Me ofendes. 斡Mira a tu alrededor![n]Hay tantas parejas en las que[n]el hombre ha tenido suerte...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_8]
[s]Mmm, tienes raz吋n... No es que est姻[n]cantando victoria, pero[n]en la vida hay que arriesgarse.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_9]
[s]夷Dices eso a pesar de que[n]no la conoces de nada?[n]Ojal茨 yo tuviese tanta confianza.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_10]
[s]Pues s胤. Tal y como est茨n[n]las cosas, es mejor que la olvide.[n]Lo har姻 por ella.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_11]
[s]Es dif胤cil pensar en c吋mo hacer[n]felices a las mujeres, pero no se[n]las puede obligar a que lo sean.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_12]
[s]斡Como si un chaval que ni siquiera[n]paga impuestos pudiese conseguirlo![n]斡No es una chica cualquiera![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_13]
[s]夷Crees que es una tonter胤a?[n]Me refiero a lo de querer dejar[n]atr茨s la solter胤a...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_14]
[s]夷Por qu姻 eres tan fr胤o?[n]Te quedar茨s muy solo en el futuro[n]si no escuchas a los dem茨s.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_15]
[s]Si muriese de un tiro, creo que[n]no me arrepentir胤a de nada si fuese[n]ella la que disparase.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_16]
[s]Pero 夷a ti qu姻 te pasa? 夷No sabes[n]nada del tema? 夷Alguna vez[n]le has pedido salir a una chica?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07]
[s]Ejem. Tampoco es que estuviera[n]esforz茨ndome mucho.[n][w][e]
[s]Jo, qu姻 pena. Si me lo hubiera[n]tomado en serio desde el principio,[n]no me habr胤a quedado as胤.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_07 top]
[s]Pues ahora ve en serio.[e]
[s]夷Ya est茨s poniendo excusas?[e]
[s]Yo tampoco me estaba esforzando.[e]

[msg TalkMsg_GUY_CHAT_FQ_07_R]
[s]夷Eh? Ah, eh, no, si es que[n]tienes raz吋n.[n]No quiero molestarte.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_2]
[s]Se-ser茨 mejor que pases. Correr胤as[n]peligro si le diera rienda suelta[n]a mi furia. 斡Va en serio![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_3]
[s]No te conf胤es... 夷No sabes[n]que no estar preparado puede llegar[n]a ser tu peor enemigo?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_4]
[s]Ya has visto c吋mo estoy, 夷no?[n]Eres bastante cruel,[n]la verdad.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_5]
[s]Je, te chinchan un poco y saltas[n]de buenas a primeras.[n]斡Propio de un mocoso como t雨![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_6]
[s]Puede que est姻s tramando algo[n]o puede que no. 夷Te frustra[n]lo que digo? Mmm...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_7]
[s]Pero 斡no pienso perder![n]斡Al menos sigo teniendo[n]ganas de acabar contigo![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_8]
[s]Mmm... 夷Te has despistado al tratar[n]de rematarme? Parece que entonces[n]tocar茨 hablar... Con calma.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_9]
[s]Tampoco es que me haya esforzado...[n]Parece un t吋pico, pero es que esta[n]no es ni mi 雨ltima transformaci吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_10]
[s]夷S胤? 夷Entonces tendr胤a que[n]apa隠茨rmelas solo? 夷No he sabido[n]ser un buen ser humano?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_11]
[s]Ah, s胤, con eso vale.[n]Da igual,[n]as胤 que acabemos rapidito.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_12]
[s]夷Cu茨ndo piensas dejar[n]de juguetear? No puedes ponerte[n]a tope as胤 sin m茨s.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_13]
[s]斡Ah! Me he expresado mal. Este era[n]todo mi poder. 斡Al cien por cien[n]desde el comienzo![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_14]
[s]夷Se te han quitado las ganas? Mmm.[n]夷No ser茨 que te has acobardado[n]al ver mi verdadero poder?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_15]
[s]Es-esto no habr胤a ocurrido[n]si me lo hubiera tomado en serio.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_16]
[s]夷Has disparado a pesar[n]de que no quieres matarme?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08]
[s]Un segundo. 夷No crees que est茨s[n]apuntando a la persona equivocada?[n][w][e]
[s]Yo no soy a quien deber胤as[n]querer disparar.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_08 top]
[s]Ah胤 tienes raz吋n...[e]
[s]No especialmente.[e]
[s]Cualquiera servir茨.[e]

[msg TalkMsg_GUY_CHAT_FQ_08_R]
[s]Vale, vale... Ya sab胤a yo[n]que se podr胤a razonar contigo[n]hablando un poco.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_2]
[s]斡Si nos hubi姻ramos conocido[n]en otro momento, habr胤amos[n]hecho buenas migas![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_3]
[s]夷Y eso qu姻 significa?[n]夷Que podr胤as haberme disparado[n]aunque no tuvieras motivo?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_4]
[s]Parece que te arrepientes. Aun as胤,[n]me has apuntado directamente.[n]斡Esto es un trauma de por vida![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_5]
[s]夷Siempre he sido el objetivo?[n]Mmm... 斡Pues qu姻 honor![n]Ja, ja, ja, ja.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_6]
[s]Aj茨. No lo tienes claro, 夷eh?[n]No tiene sentido luchar si no[n]se sabe qui姻n es el enemigo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_7]
[s]夷Est茨s intentando darme pena porque[n]lo he dicho? Basta ya de tanta...[n]Bueno, tampoco te queda tan mal.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_8]
[s]夷Y qu姻 quieres decir con eso?[n]Te agradecer胤a que fueses m茨s[n]conciso y claro.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_9]
[s]Algo te incit吋 a actuar as胤, 夷no?[n]Quiz茨 es porque no ten胤as ni a los[n]amigos ni a la familia cerca.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_10]
[s]斡Pues b雨scate a otro! No tengo[n]por qu姻 ser yo, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_11]
[s]夷Me tratas como si fuera un[n]PNJ cualquiera? Mmm... No s姻...[n]Tampoco est茨 tan mal.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_12]
[s]Pues deber胤an dispararte a ti.[n]Abandona toda esperanza[n]y no salgas de casa nunca m茨s.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_13]
[s]夷Has fallado?[n]Noto que est茨s dudando.[n]Ser茨 porque tendr姻 algo de raz吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_14]
[s]夷C吋mo? He fallado, 夷no?[n]Eres duro de pelar.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_15]
[s]斡Co-cont姻stame! 夷No sabes[n]mantener una conversaci吋n?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_16]
[s]Da igual lo noble que sea la causa,[n]un ladr吋n es un ladr吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01]
[s]Creo que llego a entenderte.[n]He conocido a mucha gente[n]trabajando aqu胤 y...[n][w][e]
[s]En realidad...[n]Eres buena persona, 夷no?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_01 top]
[s]Me lo dicen mucho.[e]
[s]En realidad... soy terrible.[e]
[s]夷Te est茨s riendo de m胤?[e]

[msg TalkMsg_GUY_CHAT_SQ_01_R]
[s]Lo sab胤a. Entonces me imagino[n]que me ayudar茨s, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_2]
[s]Me lo imaginaba.[n]Tu cara te delata.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_3]
[s]Me lo imaginaba, pero[n]no hace falta que vayas chuleando.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_4]
[s]Mmm... 夷Y lo dices t雨?[n]Pues parece que no eres igual[n]que esos otros.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_5]
[s]Nadie que dice eso sobre s胤[n]mismo es malvado de verdad.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_6]
[s]Mmm... Si tuviera tu edad,[n]quiz茨 dir胤a lo mismo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_7]
[s]夷Es eso cierto?[n]夷Te he juzgado mal?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_8]
[s]夷En serio vas a seguir[n]con esa actitud de malote?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_9]
[s]No entiendes lo que te digo[n]a pesar de que no dejo de[n]elogiarte, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_10]
[s]Depende de c吋mo se interprete.[n]Podr胤a entenderse as胤 tambi姻n.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_11]
[s]Mmm... 夷No es un elogio que te digan[n]que eres buena persona?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_12]
[s]Ya estoy otra vez hasta el mo隠o[n]de que seas as胤 de borde conmigo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_13]
[s]Ya lo pillo. Parece que[n]lo ten胤as todo planeado.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_14]
[s]夷As胤 piensas conseguir que deje[n]de querer que me perdonen?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_15]
[s]Si te he molestado,[n]ha sido sin querer. 夷He dicho algo[n]que no tendr胤a que haber dicho?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_16]
[s]Ah, si es que soy mal胤simo[n]juzgando a la gente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02]
[s]S姻 que eres menor,[n]pero me encantar胤a charlar[n]contigo y tomar algo.[n][w][e]
[s]Suena a t吋pico, pero podr胤amos[n]hablar sobre la vida y sobre[n]qu姻 chicas nos gustan y tal.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_02 top]
[s]Me gustan las mujeres mayores.[e]
[s]No tengo preferencias.[e]
[s]Me gustan los hombres.[e]

[msg TalkMsg_GUY_CHAT_SQ_02_R]
[s]Si te gusta una mujer que trabaje[n]en una tienda o un restaurante,[n]olv胤date. No es buena idea.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_2]
[s]Ya, lo s姻. Las que son mayores[n]tienden a ser m茨s maduras[n]y generosas, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_3]
[s]Las mujeres a las que conozco est茨n[n]acostumbradas al lujo,[n]y eso mina la moral...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_4]
[s]Te entiendo. Salir con alguien mayor[n]y con experiencia ayuda[n]a crecer como persona.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_5]
[s]Los chicos que dicen eso[n]suelen ser los m茨s quisquillosos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_6]
[s]Qu姻 aburrido. Con esta actitud,[n]nunca nadie te har茨 caso.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_7]
[s]Entonces, 夷no sacas conclusiones[n]de la primera impresi吋n?[n]La qu胤mica lleva tiempo, es verdad.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_8]
[s]Mmm. Abarcas mucho, 夷no crees?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_9]
[s]Aj茨. Creo que tendr茨s que afrontar[n]muchos retos, pero quiz茨 algunas[n]cosas te sean f茨ciles, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_10]
[s]Ya veo... Buen trabajo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_11]
[s]夷En serio? Eh, bueno...[n]Me sorprende un poco.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_12]
[s]Molar胤a que encontraras a[n]alguien que lo comprendiera.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_13]
[s]Cre胤a que te pillar胤a desprevenido[n]si te entreten胤a un poco,[n]pero veo que...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_14]
[s]Pues s胤. No deber胤amos estar[n]hablando de algo as胤 en una lucha[n]a muerte.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_15]
[s]Aj茨. 夷Te negar胤as[n]a tomar algo con el enemigo?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_16]
[s]夷Eh? 夷Vas de machote como si no[n]necesitaras a ninguna mujer? Mmm...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03]
[s]Pase lo que pase, me vasa matar,[n]夷verdad? 夷Te puedo preguntar algo?[n][w][e]
[s]Por lo que a ti respecta,[n]夷qu姻 he sido yo para ti?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_03 top]
[s]Mi rival.[e]
[s]Nadie, en realidad.[e]
[s]No importa.[e]

[msg TalkMsg_GUY_CHAT_SQ_03_R]
[s]Ah, admites mis virtudes[n]como enemigo.[n]夷Me est茨s elogiando?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_2]
[s]夷Estabas buscando una excusa[n]para tener un rival o qu姻?[n]Admito que tiene cierto gancho.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_3]
[s]夷Me est茨s haciendo la pelota?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_4]
[s]Venga, d姻jalo ya.[n]La diferencia entre nosotros[n]est茨 m茨s que clara.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_5]
[s]Ten cuidadito con esa[n]actitud de desprecio que te gastas.[n]Cada uno recoge lo que siembra.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_6]
[s]Es verdad. Pero 夷sabes qu姻? Sienta[n]la mar de bien decirlo[n]as胤 de claro.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_7]
[s]夷Quieres llegar a lo m茨s alto[n]a costa de pisotear a los dem茨s?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_8]
[s]斡No te emociones, que solo eres[n]un ladr吋n![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_9]
[s]As胤 que no te interesan[n]los perdedores. 夷Me equivoco?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_10]
[s]Estoy alucinando.[n]夷En serio has pasado as胤 de m胤?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_11]
[s]Tienes raz吋n. Los sentimientos no[n]tienen cabida en una lucha.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_12]
[s]No te culpo, normal que no te[n]haya causado mucha impresi吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_13]
[s]夷Que no tengo nada[n]que valga la pena?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_14]
[s]夷Te niegas a responder[n]a unas preguntas tan sencillas?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_15]
[s]Creo que ya entiendo[n]qu姻 significaba la bala.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_16]
[s]Responder a una pregunta con[n]una bala... Das asco, 夷sabes?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04]
[s]Un segundo...[n]No s姻 si podr胤as aclararme una cosa[n]para el futuro.[n][w][e]
[s]夷Qu姻 es lo que ha provocado[n]mi derrota?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_04 top]
[s]Tu falta de determinaci吋n.[e]
[s]Tan solo mala suerte.[e]
[s]No voy a dec胤rtelo.[e]

[msg TalkMsg_GUY_CHAT_SQ_04_R]
[s]Ah, as胤 que ha sido gracias[n]a mi determinaci吋n... Qu姻 curioso.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_2]
[s]Qu姻 respuesta tan ambigua,[n]夷no te parece?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_3]
[s]Pues yo no creo[n]que me falte determinaci吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_4]
[s]Determinaci吋n... Qu姻 f茨cil[n]es decirlo. Aunque supongo[n]que tienes raz吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_5]
[s]夷Suerte, dices? Bueno, eso[n]no depende de m胤.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_6]
[s]斡Ja! 夷Que es cosa de suerte?[n]A la pr吋xima no perder姻.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_7]
[s]A m胤 eso me suena[n]a consolaci吋n barata.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_8]
[s]Si dices eso, le est茨s quitando[n]importancia al esfuerzo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_9]
[s]夷No piensas decirle nada al[n]enemigo? Mira que eres[n]meticuloso...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_10]
[s]Lo s姻. Lo 雨nico bueno que tiene[n]que me lo digas es que podr姻[n]morir en paz.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_11]
[s]Vamos, que no soltar茨s prenda.[n]Pues me tocar茨[n]averiguarlo sin ayuda.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_12]
[s]Tiene sentido. No ganar胤as[n]nada cont茨ndomelo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_13]
[s]Cuando te forjas un enemigo,[n]夷no hay que mostrar clemencia[n]hasta que est姻 perdido?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_14]
[s]Je. Pretendes pararme los pies[n]antes de que me haga[n]m茨s fuerte, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_15]
[s]斡Ah! 斡Me toca asumir la derrota![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_16]
[s]夷Esta es la fuerza de[n]un forajido de verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05]
[s]Perd吋n, pero 夷te importar胤a[n]decirme una cosa?[n][w][e]
[s]夷Qu姻 te ha tra胤do a este[n]lugar? 夷Qu姻 buscas?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_05 top]
[s]Una aventura.[e]
[s]En realidad, nada.[e]
[s]Una matanza.[e]

[msg TalkMsg_GUY_CHAT_SQ_05_R]
[s]El Metaverso es el lugar donde[n]se busca lo que no puede[n]encontrarse en la realidad, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_2]
[s]Eso es lo que todo el mundo piensa[n]cuando es joven.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_3]
[s]Mmm... Antes de salir a la aventura,[n]hacen falta algunas cosas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_4]
[s]Y ahora me dir茨s que te aburre[n]la realidad.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_5]
[s]Entonces, 夷te importar胤a no[n]volver nunca?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_6]
[s]夷Solo est茨s matando tiempo?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_7]
[s]夷Buscas un prop吋sito, entonces?[n]Suena divertido.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_8]
[s]斡No me mientas! Aqu胤 no[n]viene nadie sin una meta.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_9]
[s]斡夷Eres un psic吋pata?![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_10]
[s]斡Eres peligroso! Aunque eso[n]tiene cierto atractivo...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_11]
[s]Perdonarme la vida es lo mejor[n]para los dos, la verdad...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_12]
[s]斡La gente como t雨 es lo peor![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_13]
[s]As胤 que... quer胤as disparar.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_14]
[s]斡Ya vale con ese rollo![n]夷No se supone que hay reglas[n]sobre los rehenes?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_15]
[s]夷S胤? 夷Y crees[n]que eso es una respuesta?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_16]
[s]Por favor, no te enfades...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06]
[s]Me han informado muy mal.[n]Se supone que iba a ser algo[n]sencillo, solo amenazar a la gente...[n][w][e]
[s]Nunca habr胤a aceptado la oferta[n]si hubiese sabido que[n]conllevar胤a tanto sufrimiento.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_06 top]
[s]Qu姻 pena...[e]
[s]Decidir sin informaci吋n es lo peor.[e]
[s]De nada sirve quejarse.[e]

[msg TalkMsg_GUY_CHAT_SQ_06_R]
[s]夷No tienes tiempo para[n]compadecerte de los dem茨s?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_2]
[s]Por alguna raz吋n, que te preocupes[n]me hace sentir mejor.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_3]
[s]夷Te doy pena solo porque te[n]encuentras en una posici吋n[n]de superioridad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_4]
[s]斡Eres la causa de mi desaliento![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_5]
[s]Todos sufren porque[n]lo entienden perfectamente,[n]pero no pueden negarse.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_6]
[s]No puedes desafiar a aquellos[n]que son m茨s poderosos que t雨.[n]Bueno, eso piensa la mayor胤a.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_7]
[s]Por aquel entonces, no habr胤a[n]podido negarme.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_8]
[s]Mmm... Lo 雨nico que hacemos es[n]cumplir las 吋rdenes que nos dan.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_9]
[s]Te juro que yo no ser胤a el t胤pico[n]que se pasa el d胤a quej茨ndose[n]en el bar.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_10]
[s]Creo que solo un adulto puede[n]saber a qu姻 me refiero.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_11]
[s]Lo s姻. Yo solo quer胤a a[n]alguien que me escuchara.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_12]
[s]Je, los j吋venes de hoy en d胤a os[n]las apa隠茨is muy bien, pero sois un[n]poco fr胤os y despiadados, eso s胤.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_13]
[s]Si llego a saber que los intrusos[n]eran un grupito como este...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_14]
[s]Pf, 夷pretendes motivarme[n]dici姻ndome eso?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_15]
[s]Te equivocas. Yo no te he echado[n]la culpa.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_16]
[s]斡Espera! 斡Ya he recibido la mitad[n]del pago por adelantado![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07]
[s]Por cierto, has hecho un trabajo[n]de primera llegando hasta aqu胤.[n][w][e]
[s]夷No te has desviado del camino[n]ni te has perdido?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_07 top]
[s]Me he descargado una aplicaci吋n.[e]
[s]Estoy algo perdido.[e]
[s]No me acuerdo.[e]

[msg TalkMsg_GUY_CHAT_SQ_07_R]
[s]Ah, 夷as胤 que hay cosas tan[n]雨tiles hoy en d胤a?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_2]
[s]Supongo que nos sirve para[n]demostrar que preparase es[n]vital para cualquier aventura.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_3]
[s]Si no llega a ser por esa[n]maldita aplicaci吋n, no me habr胤a[n]metido en este l胤o.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_4]
[s]Bah, solo eres un cr胤o[n]que depende de la tecnolog胤a.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_5]
[s]Ojal茨 siguieras perdido.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_6]
[s]Al fin y al cabo, es el Metaverso.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_7]
[s]斡Aj茨! Te orientas que da pena.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_8]
[s]Quiz茨 te venga bien una[n]siesta. Te matar姻 mientras[n]duermes...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_9]
[s]斡Bueno, has alcanzado tu[n]destino final![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_10]
[s]斡Hay que ser torpe para olvidarse[n]de que est茨s perdido![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_11]
[s]夷Dependes de tus amigos para[n]no perderte? Supongo que[n]no tiene nada de malo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_12]
[s]En ese caso, 夷y si te lo recuerdo[n]por las malas?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_13]
[s]Al menos parece que tu objetivo[n]sigue siendo matarme.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_14]
[s]Venga ya, no intentaba[n]recopilar informaci吋n sobre ti[n]ni nada por el estilo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_15]
[s]Venga ya, tampoco he dicho[n]que tuvieras mucho tiempo libre[n]ni nada as胤.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_16]
[s]Vaya, no hay manera.[n]Este ni隠o es incapaz de tener[n]una conversaci吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08]
[s]Dime, 夷c吋mo te encuentras?[n]Solo por curiosidad.[n][w][e]
[s]O sea, 夷qu姻 se siente[n]al apuntar a un enemigo[n]que ha perdido el deseo de luchar?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_08 top]
[s]No est茨 mal.[e]
[s]Podr胤a acostumbrarme.[e]
[s]Me duele en el alma.[e]

[msg TalkMsg_GUY_CHAT_SQ_08_R]
[s]Bueno, a m胤 me sabe fatal.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_2]
[s]Esa respuesta tan indirecta[n]solo me pone m茨s de los nervios.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_3]
[s]Vaya, has respondido a mi sarcasmo[n]de forma sencilla y serena. Touch姻.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_4]
[s]Creo que tienes una faceta s茨dica...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_5]
[s]Parece que me he topado[n]con un verdadero psic吋pata.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_6]
[s]Est茨 bien tener un fetiche[n]del que puedes disfrutar[n]libremente, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_7]
[s]Est茨s enfermo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_8]
[s]斡夷Disfrutas haci姻ndole[n]esto a la gente?![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_9]
[s]Tienes raz吋n. Un conflicto[n]sin respeto por tu contrincante[n]no tiene sentido.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_10]
[s]As胤 que lo primero que deber胤as[n]hacer es disculparte.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_11]
[s]Solo estaba siendo sarc茨stico...[n]No te deprimas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_12]
[s]Qu姻 actuaci吋n tan horrible.[n]Puaj, es verdaderamente repugnante.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_13]
[s]斡Espera! Solo quer胤a parecer guay.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_14]
[s]Mmmm... Ya veo. Imagino que sentir茨s[n]un subid吋n indescriptible, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_15]
[s]Te lo est茨s pasando bien, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_16]
[s]Lo siento... Me he pasado un poco[n]con ese chiste, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09]
[s]Espera, me parece[n]que me est茨s malinterpretando...[n][w][e]
[s]No te odio.[n]Eso no es lo que siento...[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_09 top]
[s]Ah, 夷s胤?[e]
[s]Demasiado tarde.[e]
[s]Entonces, d姻monos la mano.[e]

[msg TalkMsg_GUY_CHAT_SQ_09_R]
[s]S胤, ha sido un malentendido[n]por ambas partes.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_2]
[s]As胤 es. No tenemos por qu姻[n]llevarnos como el perro y el gato.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_3]
[s]Esto es lo que ocurre cuando[n]alguien es muy diferente de lo[n]que su aspecto da a entender.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_4]
[s]Esperaba que te dieras cuenta[n]antes de incapacitarme, pero...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_5]
[s]Es as胤, 夷verdad?[n]Yo... tambi姻n lo entiendo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_6]
[s]Por favor, no respondas a un chiste[n]con una amenaza tan seria.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_7]
[s]Bien... 斡Pues lucharemos[n]hasta el final![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_8]
[s]斡No digas eso, por favor![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_9]
[s]Genial, entonces lo entend姻is.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_10]
[s]No hace falta que nos comportemos[n]como si fu姻ramos enemigos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_11]
[s]斡Era broma![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_12]
[s]斡No me refer胤a a eso! 斡Largo![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_13]
[s]Ah... 夷Te sienta mal que alguien[n]se隠ale un malentendido?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_14]
[s]夷Haces lo mismo incluso[n]con quienes no son tus enemigos?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_15]
[s]Parece que no tienes[n]tiempo para hablar...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_16]
[s]Entonces, cuando algo[n]se te mete en la cabeza...[n]夷sigues hasta el final?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10]
[s]夷Eh? Espera un momento.[n]夷Qu姻 ha sido eso?[n][w][e]
[s]夷Te acaba de temblar la mano?[n]夷Te atormenta la culpa?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_10 top]
[s]Solo es un escalofr胤o.[e]
[s]S胤, puedo aguantar...[e]
[s]C茨llate.[e]

[msg TalkMsg_GUY_CHAT_SQ_10_R]
[s]Nada de hacerse el duro.[n]S姻 la verdad.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_2]
[s]夷Quieres que mire el termostato?[n]Creo que paso.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_3]
[s]Seguro que has pillado un catarro.[n]夷Por qu姻 no te vas a casa?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_4]
[s]斡Mentiroso! No me creo[n]que tengas fr胤o aqu胤 abajo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_5]
[s]Lo has dicho de una forma[n]tan honesta que hasta me sabe mal[n]haberme metido contigo...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_6]
[s]夷Verdad? Es normal, llevas[n]encima algo muy amenazante.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_7]
[s]Lo realmente aterrador es que no[n]asumes tu responsabilidad.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_8]
[s]Entonces sabes lo terror胤fico[n]que es esto. Qu姻 admirable.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_9]
[s]Venga, no hay por qu姻 perder[n]la cabeza por algo as胤.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_10]
[s]Mmmm, te has puesto sentimental[n]y me has revelado tu punto d姻bil.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_11]
[s]El dedo en la llaga, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_12]
[s]夷Sabes? La forma[n]en la que hablas est茨 solo[n]a un paso de considerarse acoso.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_13]
[s]斡Lo siento! 斡Lo siento![n]斡Estaba bromeando![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_14]
[s]Era broma. Venga, ja, ja...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_15]
[s]夷Eres de los que explotan[n]en cuanto se enfadan?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_16]
[s]No se te da muy bien[n]entablar conversaciones, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11]
[s]Ponte en mi lugar. Aparece un grupo[n]de desconocidos y me obligan[n]a hacer lo que quieren...[n][w][e]
[s]夷Lo que est茨s haciendo[n]no te remuerde la conciencia?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_11 top]
[s]Ahora que lo dices...[e]
[s]Nanay.[e]
[s]夷Qu姻 es la conciencia?[e]

[msg TalkMsg_GUY_CHAT_SQ_11_R]
[s]Gracias por tener en cuenta[n]mi observaci吋n, al menos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_2]
[s]Me basta con que lo entiendas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_3]
[s]Eso es. Eres bondadoso[n]por naturaleza.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_4]
[s]Si ya has aprendido la lecci吋n,[n]esto no deber胤a volver a pasar.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_5]
[s]A ti... no te criaron con amor,[n]夷o me equivoco?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_6]
[s]Entonces, no hay por qu姻 apiadarse[n]de alguien como t雨, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_7]
[s]Sab胤a que dir胤as eso.[n]Lo est茨s disfrutando, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_8]
[s]Ese nivel de rebeld胤a es incluso[n]mayor que el de una rueda[n]de prensa desastrosa.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_9]
[s]Has llamado[n]la atenci吋n con la respuesta, al menos.[n]夷Quer胤as eso?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_10]
[s]Mm, al menos ha tenido m茨s gracia[n]que los c吋micos de la tele.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_11]
[s]Si sigues diciendo cosas[n]tan desagradables, te vas[n]a quedar sin amigos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_12]
[s]Seguro que con esa personalidad[n]la vida no te va a ir muy bien.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_13]
[s]Parece que ni siquiera preguntarme[n]ten胤a sentido.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_14]
[s]夷Te est茨s rayando[n]porque te da miedo pensar[n]en la respuesta a esa pregunta?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_15]
[s]No conoces el significado de[n]la palabra 或consciencia位, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_16]
[s]Pareces alguien que prefiere[n]tomar cartas en el asunto[n]en lugar de reflexionar.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12]
[s]De todas formas... 夷Por qu姻 soy el 雨nico[n]al que le pasan estas cosas?[n][w][e]
[s]夷Qu姻 he hecho yo para merecer esto?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_12 top]
[s]El karma te devuelve tus fechor胤as.[e]
[s]No te hagas la v胤ctima.[e]
[s]Nada en particular.[e]

[msg TalkMsg_GUY_CHAT_SQ_12_R]
[s]斡Los cr胤os no deber胤ais ser[n]tan condescendientes![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_2]
[s]Mmm... Es curioso que digas eso.[n]Desde mi punto de vista, me parece[n]fatal lo que est茨s haciendo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_3]
[s]夷C吋mo? 夷Ahora te pones m胤stico?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_4]
[s]Ya, cosa del karma, 夷eh?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_5]
[s]夷Dices que no soy el 雨nico[n]que est茨 sufriendo?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_6]
[s]Bueno, nadie me va a ayudar[n]si no desempe隠o mi papel...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_7]
[s]Uf, mira que eres irritante.[n]Paso de escuchar tus sermones.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_8]
[s]Paso de hablar contigo[n]si solo vas a soltar clich姻s.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_9]
[s]Ni siquiera dejas que me quite[n]la culpa...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_10]
[s]夷Es una muestra de tu complejo[n]de inferioridad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_11]
[s]Ah. En otras palabras,[n]no he hecho nada malo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_12]
[s]No respetas nada[n]de lo que hago...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_13]
[s]Supongo que ni siquiera puedes[n]tolerar mi existencia...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_14]
[s]Tienes raz吋n. Decir cosas as胤...[n]es de cobardes.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_15]
[s]Ya entiendo... Me est茨s diciendo[n]que me calle, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_16]
[s]斡Ay, no me lo puedo creer![n]斡El d胤a de hoy ha sido horrible![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13]
[s]夷Sabes? La verdad es que deber胤as[n]dejarme en paz. Olvid姻[n]mencionarlo, pero...[n][w][e]
[s]Soy un hombre[n]con un trasfondo complicado.[n]La gente que conozco, bueno...[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_13 top]
[s]Quiero conocerlos.[e]
[s]夷Complicado...?[e]
[s]Mentiroso.[e]

[msg TalkMsg_GUY_CHAT_SQ_13_R]
[s]Vale, pero 夷en qu姻 d胤a estamos?[n]Oh, puede que no les venga bien.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_2]
[s]No, puede que eso no ocurra,[n]porque es... complicado.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_3]
[s]斡Menuda coincidencia![n]Justo estaba pensando lo mismo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_4]
[s]Eh, 夷pensabas que estaba bromeando?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_5]
[s]Bueno, lo mejor ser茨[n]que lo deje. Es muy complicado...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_6]
[s]Si al final vienen, la cosa[n]se podr胤a complicar.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_7]
[s]Ah, as胤 es. 夷C吋mo puedo explicarlo?[n]Uf, hasta eso es complicado.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_8]
[s]As胤 es. Conf胤a en m胤,[n]no merece la pena plantar cara.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_9]
[s]N-No es mentira... De eso nada.[n]Puedo d-demostrarlo... Oh...[n]斡Vale, tienes raz吋n![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_10]
[s]No estaba listo para una respuesta[n]tan sencilla como esa.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_11]
[s]Esta persona complicada, que... yo...[n]Lo que quiero decir, eh...[n]Es muy complejo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_12]
[s]斡No es mentira![n]Tienes mucho morro, 夷no crees?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_13]
[s]Te est茨s volviendo[n]much胤simo m茨s complicado.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_14]
[s]Lo entiendo... Te pagar姻 un poco.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_15]
[s]Entonces, si va a haber[n]un combate a muerte,[n]夷ser茨 entre las partes interesadas?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_16]
[s]Como me pase algo, te arrepentir茨s.[n]斡Ya ver茨s![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14]
[s]夷Entonces?[n]夷Qu姻 piensas hacer despu姻s de esto?[n][w][e]
[s]No sirve de nada[n]que apuntes esa cosa al tunt雨n.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_14 top]
[s]Lo s姻.[e]
[s]No te hagas el duro.[e]
[s]No tan in雨til como t雨.[e]

[msg TalkMsg_GUY_CHAT_SQ_14_R]
[s]斡Bien! Eh... No quiero decir[n]que me dispares, claro.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_2]
[s]Si no vale para nada,[n]夷por qu姻 no destruirlo?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_3]
[s]Si lo sabes, me gustar胤a[n]que acabaras con esto ya.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_4]
[s]夷Y bien? 夷Hoy hemos[n]aprendido algo nuevo?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_5]
[s]Mmm, no esperaba que un ni隠o[n]como t雨 dijera eso.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_6]
[s]No es que me haga el duro, pero...[n]En esta situaci吋n las cosas[n]no pintan bien para m胤.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_7]
[s]Que sepas que a雨n[n]no has quebrantado mi esp胤ritu.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_8]
[s]Es una mala costumbre, aunque[n]no tenga posibilidades de ganar.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_9]
[s]夷Y si averiguamos[n]lo in雨til que soy realmente?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_10]
[s]Mmm. Es verdad.[n]Supongo que no soy muy bueno[n]a la hora de detener intrusos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_11]
[s]Puede que t雨 lo veas as胤,[n]pero al menos soy un adulto[n]que contribuye a la sociedad.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_12]
[s]As胤 que mides a los dem茨s[n]seg雨n su utilidad...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_13]
[s]斡Si lo sabes, dilo![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_14]
[s]Nunca imagin姻 que un estudiante[n]me retendr胤a a punta de pistola.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_15]
[s]Al final resulta que sabes[n]muy bien lo que haces.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_16]
[s]Solo te ofendiste porque alguien[n]se meti吋 contigo, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15]
[s]No tienes ni idea[n]de lo que haces, 夷verdad?[n][w][e]
[s]Si tus padres te vieran, seguro[n]que les romper胤as el coraz吋n...[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_15 top]
[s]Puede que tengas raz吋n...[e]
[s]Ellos no tienen nada que ver.[e]
[s]En realidad, se alegrar胤an.[e]

[msg TalkMsg_GUY_CHAT_SQ_15_R]
[s]夷Lo sab胤as, y aun as胤 insistes[n]en seguir con esto? Eres de los que[n]se comprometen de verdad, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_2]
[s]As胤 es. Tienes que querer[n]a tus padres.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_3]
[s]No intentes enga隠arte[n]pensando lo contrario.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_4]
[s]Me sorprende[n]lo comprensivo que eres.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_5]
[s]夷Dices eso, cuando sigues[n]viviendo de tus padres?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_6]
[s]Sabes que los tutores legales[n]son responsables de los actos[n]de un menor, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_7]
[s]Mmm, eres joven, pero tienes[n]tu propia forma de pensar, 夷eh?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_8]
[s]Pero esto los pondr胤a[n]muy tristes, 夷no crees?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_9]
[s]斡No me lo puedo creer! 夷En qu姻[n]clase de familia te has criado?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_10]
[s]Vaya... 夷Eres el fruto[n]de una familia disfuncional?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_11]
[s]Eso es una mentira como una casa.[n]Deja de enga隠arte[n]cuando te conviene.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_12]
[s]Ya veo. Te han criado[n]unos paletos... Pobrecito.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_13]
[s]Me he pasado. No pretend胤a sacar[n]el tema de tus padres.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_14]
[s]C-Claro, 斡no le dir姻[n]a tus padres lo que has estado[n]haciendo por aqu胤![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_15]
[s]Se me est茨 acabando la paciencia.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_16]
[s]Bueno, al tratarse de alguien[n]como t雨, tal vez tus padres[n]no estar胤an tan decepcionados.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16]
[s]De acuerdo. Digamos[n]que me has vencido. Aun as胤,[n]no podr茨s salir de aqu胤 ileso.[n][w][e]
[s]Y en ese caso, 夷por qu姻 no[n]abandonas esta empresa tan in雨til?[n]No tiene sentido...[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_16 top]
[s]Ah胤 tienes raz吋n...[e]
[s]No puedo parar.[e]
[s]Le encontrar姻 el sentido.[e]

[msg TalkMsg_GUY_CHAT_SQ_16_R]
[s]Me alegra que est姻s de acuerdo.[n]Me facilita las cosas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_2]
[s]S胤, as胤 es. La victoria va m茨s all茨[n]de oprimir a tu oponente.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_3]
[s]Eso significa[n]que me he salvado, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_4]
[s]Entonces, 夷deber胤a hacerlo[n]a雨n m茨s insignificante?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_5]
[s]Apuesto a que eres de los que no[n]abandona un juego de lucha[n]hasta que gana, 夷o me equivoco?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_6]
[s]Te entiendo. Es importante[n]llegar hasta el final.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_7]
[s]夷Seguro que lo tuyo[n]no es solo cabezoner胤a?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_8]
[s]Te has jugado la vida por esto,[n]夷no? Has sido muy atrevido[n]para ser tan joven.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_9]
[s]Ah, no, gracias.[n]Esas cosas son una lata...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_10]
[s]No entiendo qu姻 quieres[n]decir con eso, pero...[n]digamos que me intriga.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_11]
[s]夷Vas de fil吋sofo?[n]Supongo que es una fase[n]por la que pasan todos los ni隠os.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_12]
[s]斡No pongas excusas[n]rimbombantes para justificarlo![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_13]
[s]Creo que la expresi吋n es[n]或Act雨a antes de pensar位.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_14]
[s]Parece que has rechazado[n]todo lo que he dicho.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_15]
[s]Perd吋name, quiz茨s me exced胤[n]al decir que nada de esto[n]ten胤a sentido.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_16]
[s]La verdad es que intelectualmente[n]s胤 entiendes lo que digo, 夷no?[n]Solo me llevas la contraria...[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND]
[s](corte) Espera un momento.[n]夷Quieres algo? No dispares[n]y p胤demelo, har姻 lo que pueda.[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_2]
[s](corte) Vamos a calmarnos. Baja[n]el arma y respira hondo... as胤.[n]Ahora dime qu姻 quieres hacer.[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_3]
[s](corte) Por favor, espera. 夷Qu姻 quieres[n]que haga? Acabemos bien, 夷vale?[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_4]
[s](corte) Nunca imagin姻 que existiese[n]alguien como t雨. Impresionante.[n]夷Qu姻 quieres? T雨 pide.[n][w][e]

[sel TalkSel_GUY_NEGO_SURREND top]
[s]Te quiero a ti.[e]
[s]Dame dinero.[e]
[s]Quiero un objeto raro.[e]
[s]Quiero informaci吋n.[e]
[s]Reduce el nivel de seguridad.[e]

[msg TalkMsg_GUY_NEGO_FIFTYFI]
[s]夷Puedes darme [var 0]?[n]Al fin y al cabo, esto es[n]cuesti吋n de vida o muerte para m胤.[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_2]
[s]Prefiero no arriesgarme[n]a menos que me des [n][f 2 5 3 9999 1].[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_3]
[s]Ay, seguro que mi salud y bienestar[n]no saldr茨n muy bien parados.[n]Dame un poco de tu fuerza vital.[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_4]
[s]Lo que propones me inquieta.[n]Voy a necesitar[n]un poco de tu fuerza mental.[n][w][e]

[sel TalkSel_GUY_NEGO_FIFTYFI top]
[s]Vale, te lo dar姻.[e]
[s]No puedo darte lo que pides.[e]

[msg TalkMsg_GUY_NEGO_REQUIRE]
[s]夷A qu姻 se debe este calor?[n]斡Tienes que hacer algo![n][w][e]
[s]Espera. Antes de nada,[n]夷no podr胤as darme[n][f 2 5 3 9999 4]?[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_2]
[s]*tos* El aire est茨[n]muy seco 雨ltimamente...[n][w][e]
[s]Es suficiente como para pensar[n]que puedo pillar la gripe. 夷Tienes[n][f 2 5 3 9999 4]?[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_3]
[s]夷Qui姻n est茨 esparciendo este polen?[n]Me pican mucho los ojos...[n][w][e]
[s]Ojal茨 hubiera algo que me aliviase.[n]Si tienes [f 2 5 3 9999 4],[n]me vendr胤a bien.[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_4]
[s]Espera. 夷Significa eso que quieres[n]que involucre a otras sombras?[n]夷Y quieres que les mienta?[n][w][e]
[s]Es una mala idea. Si se enteran,[n]me matar茨n. Pero lo har姻 si me das[n]un poco de fuerza mental.[n][w][e]

[sel TalkSel_GUY_NEGO_REQUIRE top]
[s]Entr姻galo[e]
[s]Qu姻datelo[e]

[msg TalkMsg_GUY_NEGO_PAYFOR_]
[s]Mira, aqu胤 tienes [var 0] yenes.[n]Para ti.[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__2]
[s]Seguro que a ti tambi姻n se te[n]han amontonado las facturas.[n]Mira, aqu胤 tienes [var 0] yenes.[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__3]
[s]No quiero desprenderme de esto,[n]pero toma... [f 2 5 3 9999 1].[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__4]
[s]Esto me encanta.[n]Toma, [f 2 5 3 9999 1].[n][w][e]

[sel TalkSel_GUY_NEGO_PAYFOR top]
[s]Me lo quedo.[e]
[s]Eso no es lo mejor que tienes.[e]

[msg TalkMsg_GUY_NEGO_Re_ACCE]
[s]夷En serio? Vale, se acab吋.[n][w][e]

[msg TalkMsg_GUY_NEGO_Re_ACCE_2]
[s]Lo entiendo. En ese caso...[n][w][e]

[msg TalkMsg_GUY_NEGO_Re_ACCE_3 [Ryuji]]

[msg TalkMsg_GUY_RESULT_GET_P]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_2]
[s]Vaya. Ya siento [clr 1][var 2][clr 27][n]en tu interior.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_3]
[s]Si insistes...[n][w][e]
[s]Espera, tu nivel es demasiado bajo.[n]Por ahora, tendr茨s que apa隠arte[n]con [f 2 5 3 9999 1].[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_M]
[s]Con [var 0] yenes te basta, 夷no?[n]Si no, hablaremos m茨s[n]la pr吋xima vez.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_I]
[s]Toma, [f 2 5 3 9999 1].[n]Es un buen final[n]para esta reuni吋n.[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_S]
[s]Ah, lo que voy a darte es[n]algo que escrib胤 en mis notas.[n]Quiz茨 te resulte de utilidad.[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY]
[s]Hoy no estoy de humor[n]para hablar. Vuelve al lugar[n]del que hayas salido.[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_2]
[s]No has vivido suficientes[n]experiencias dolorosas.[n]斡Vamos a remediarlo![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_3]
[s]Te puede la avaricia, 夷no?[n]Bueno, si solo sabes quedarte[n]con cosas, 斡qu姻date con esto![n][w][e]
[s]斡Te ense隠ar姻 el movimiento[n]especial de mi colega![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_4]
[s]Esto no va bien.[n]斡Quiz茨 sea hora de irse![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_5]
[s]Y con eso... 斡me voy![n]斡Estar姻 m茨s que feliz[n]si vivo para contarlo![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_6]
[s]斡Espera! 夷Eh?[n]夷No nos vamos a reunir aqu胤?[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_7]
[s]夷Vienes a por m胤? 斡Pues no[n]me voy a quedar esperando![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_8]
[s]...[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_9]
[s]斡Estoy furioso![n]斡No pienso escucharte![n][w][e]
[s]Eh, 夷por qu姻 me he cabreado?[n]Quiz茨 deber胤a escucharte.[n][w][e]

[msg TalkMsg_RESULT_GET_SECRE]
[s]Ah, 夷lo sab胤as? Qu姻 decepci吋n.[n]Quiz茨 esto no baste[n]para compensarte, pero ac姻ptalo.[n][w][e]

[msg TalkMsg_SURRENDER_FROM_C]
[s]Vale, admito mi derrota.[n][w][e]

[msg TalkMsg_SUCCESS_SKIMMING]
[s]Si has encontrado esto[n]es que eres muy observador...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_SHO]
[s]Ay, ah...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_SLE]
[s]Zzz...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_FLA]
[s]Uf, qu姻 calor hace... Si tienes algo[n]que decir, que sea r茨pido.[n][w][e]
[s]Me estoy acostumbrando al calor...[n]Podemos hablar.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_VER]
[s]Qu姻 mareo tengo... Espera, 夷c吋mo?[n]夷Intentas hablar conmigo?[n][w][e]
[s]Me estoy acostumbrando al mareo...[n]Podemos hablar.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_FOR]
[s]Ay, siento que he olvidado algo...[n][w][e]
[s]Uy, espera. Creo que empiezo[n]a acordarme... Supongo que[n]podemos hablar.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_DES]
[s]D姻jame en paz. No tengo talento[n]ni valor... soy todo palabrer胤a.[n][w][e]
[s]Ah... 夷me necesitas?[n]Entonces yo necesito escucharte...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_BRA]
[s]Veo algo... 夷Este puente lleva...[n]a la dicha sublime?[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH]
[s]Ya veo. Al otro lado del puente...[n][w][e]
[s]Nos espera una gran dicha si...[n]斡Acabo de recordar algo![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_2]
[s]Ya veo. Al otro lado del puente...[n][w][e]
[s]Olv胤dalo. All胤 no hay nada...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_3]
[s]Ya veo. Al otro lado del puente...[n][w][e]
[s]Oh, por favor, 斡acepta esto![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_4]
[s]Ya veo. Al otro lado del puente...[n][w][e]
[s]Olv胤dalo. All胤 no hay nada...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_5]
[s]Ya veo. Al otro lado del puente...[n]Oh, por favor, 斡acepta esto![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_6]
[s]Ya veo. Al otro lado del puente...[n][w][e]
[s]Olv胤dalo. All胤 no hay nada...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_7]
[s]Conque ese es mi camino...[n]Gracias. He abierto los ojos.[n]Toma esto.[n][w][e]

[msg TalkMsg_CONTACT_11]
[s]夷No ves que da igual[n]cu茨nto te esfuerces? Nadie puede[n]ganarle al rey Kamoshida.[n][w][e]

[msg TalkMsg_CONTACT_12]
[s]夷No ves que da igual[n]cu茨nto te esfuerces? Nadie puede[n]ganarle al se隠or Madarame.[n][w][e]

[msg TalkMsg_CONTACT_13]
[s]夷No ves que da igual[n]cu茨nto te esfuerces? Nadie puede[n]ganarle al se隠or Kaneshiro.[n][w][e]

[msg TalkMsg_CONTACT_14]
[s]夷No ves que da igual[n]cu茨nto te esfuerces? Nadie puede[n]ganarle a la reina Futaba.[n][w][e]

[msg TalkMsg_CONTACT_15]
[s]夷No ves que da igual[n]cu茨nto te esfuerces? Nadie puede[n]ganarle al se隠or Okumura.[n][w][e]

[msg TalkMsg_CONTACT_16]
[s]夷No ves que da igual[n]cu茨nto te esfuerces? Nadie puede[n]ganarle a la se隠ora Nijima.[n][w][e]

[msg TalkMsg_CONTACT_17]
[s]夷No ves que da igual[n]cu茨nto te esfuerces? Nadie puede[n]ganarle al maestro Akechi.[n][w][e]

[msg TalkMsg_CONTACT_18]
[s]夷No ves que da igual[n]cu茨nto te esfuerces? Nadie puede[n]ganarle al se隠or Shido.[n][w][e]

[msg TalkMsg_CONTACT_19]
[s]夷No ves que da igual cu茨nto te esfuerces?[n]Nadie puede ganarle a Su Excelencia.[n][w][e]

[msg TalkMsg_CONTACT_10]
[s]夷No ves que da igual[n]cu茨nto te esfuerces? Nadie puede[n]ganarle al jefe secreto.[n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS]
[s]A-ay雨dame. No quiero[n]desaparecer.[n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS_2]
[s]No tienes piedad, 夷eh?[n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS_3]
[s]夷De verdad me odias tanto solo[n]porque soy una sombra?[n][w][e]

[msg TalkMsg_GREET_POSSESSING]
[s]El [clr 1][var 2][clr 27] en tu interior... [n]Soy yo. Muy bien, tendr茨s todo mi apoyo.[n][w][e]

[msg TalkMsg_NEGO_POSSESSING_]
[s]Ah, si no me equivoco,[n]quer胤as dinero, 夷no?[n][w][e]

[msg TalkMsg_NEGO_POSSESSING__2]
[s]Ah, si no me equivoco,[n]quer胤as objetos, 夷no? Toma.[n][w][e]

[msg TalkMsg_GREET_POSSESSED]
[s]畏ramos inseparables, 夷verdad?[n]夷C吋mo te va todo?[n][w][e]

[msg TalkMsg_NEGO_POSSESSED]
[s]No puedes cargar[n]con el pasado, 夷no crees?[n]Limit姻monos a seguir adelante.[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_M]
[s]Dinero, 夷verdad?[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_I]
[s]Objetos, 夷verdad?. Toma esto.[n][w][e]

[msg TalkMsg_GREET_POSSESSED_]
[s]夷Qu姻 piensas de nuestra relaci吋n?[n]Dudo que hablar de intentarlo[n]de nuevo haga da隠o a nadie.[n][w][e]

[msg TalkMsg_TALK_POSSESSED_B]
[s]Recuerdo cuando t雨 y yo[n]est茨bamos juntos...[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B]
[s]Eso tambi姻n es cierto...[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B_2]
[s]夷Era dinero lo que quer胤as...?[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B_3]
[s]夷Busca algo? Qu姻dese con esto.[n][w][e]

[msg TalkMsg_FIRST_CONTACT]
[s]En ese caso, hablemos.[n]Quiero saber qu姻 tipo[n]de persona eres.[n][w][e]

[msg TalkMsg_PRE_QUESTION]
[s]Recuerdo que eres muy capaz[n]de resolver las cosas hablando.[n]Vamos a intentarlo otra vez...[n][w][e]

[msg TalkMsg_PRE_QUESTION_ACQ]
[s]斡Ahora s胤 que s胤![n][w][e]

[msg TalkMsg_PRE_QUESTION_DEN]
[s]Te has vuelto un humano aburrido...[n]Espera. 斡Acabo de recordar algo![n][w][e]

[msg TalkMsg_TALK_TECH_ITEM]
[s]No puedo hacer nada[n]contra un esp胤ritu tan abrumador.[n]Toma, quiero que tengas esto.[n][w][e]

[msg TalkMsg_TALK_TECH_PERSON]
[s]Eso es algo que podr胤a decir yo...[n]Espera, 斡acabo de recordar algo![n][w][e]

[msg TalkMsg_SETTLE_DOWN]
[s]斡E-Es broma! 斡Solo era una broma![n]Nada como una buena broma, 夷eh?[n]Ay... cambiemos de tema.[n][w][e]

[msg TalkMsg_RESULT_SHOT_1]
[s]斡夷C吋mo?! 夷Qu姻 narices...? 夷Recurres[n]a la violencia? 斡夷Intentas librarte[n]de m胤 por la fuerza?![n][w][e]
[s]Si eso es lo que quieres...[n][w][e]

[msg TalkMsg_RESULT_SHOT_2]
[s]斡Agh...! Qu姻 dolor...[n][w][e]
[s]Espera, 夷no me ha hecho nada?[n]斡Deja de tomarme el pelo![n][w][e]

[msg TalkMsg_RESULT_SHOT_3]
[s]斡Argh! 斡Un asesino a sangre fr胤a![n]Debo... 斡Debo escapar![n][w][e]

[msg TalkMsg_RESULT_SHOT_4]
[s]Ay... Te dar姻 esto,[n]斡as胤 que d姻jate ya de tonter胤as![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_2]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_3]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_4]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_5]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_6]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_7]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_8]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_9]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_10]
[s]Ya veo... 斡As胤 que mi destino[n]era hallarme en tu interior![n][w][e]
[s]Mi nuevo nombre es [clr 1][var 2][clr 27].[n]Soy una Persona que te acompa隠ar茨.[n]Desde ahora, estoy de tu parte.[n][w][e]

[msg TalkMsg_ED_bye_D01_01]
[s]A fin de cuentas, no eres rival[n]para el rey Kamoshida.[n][w][e]

[msg TalkMsg_ED_bye_D01_02]
[s]Pff... 夷De verdad crees que tienes[n]la m茨s remota posibilidad[n]contra el rey Kamoshida?[n][w][e]

[msg TalkMsg_ED_bye_D01_03]
[s]Ten en cuenta[n]que el poder del rey Kamoshida[n]eclipsa el m胤o.[n][w][e]

[msg TalkMsg_ED_bye_D02_01]
[s]A fin de cuentas, no eres rival[n]para el se隠or Madarame.[n][w][e]

[msg TalkMsg_ED_bye_D02_02]
[s]夷De verdad crees que tienes[n]la m茨s remota posibilidad[n]contra el se隠or Madarame?[n][w][e]

[msg TalkMsg_ED_bye_D02_03]
[s]Ten en cuenta[n]que el poder del se隠or Madarame[n]eclipsa el m胤o.[n][w][e]

[msg TalkMsg_ED_bye_D03_01]
[s]A fin de cuentas, no eres rival[n]para el se隠or Kaneshiro.[n][w][e]

[msg TalkMsg_ED_bye_D03_02]
[s]Pff... 夷De verdad crees que tienes[n]la m茨s remota posibilidad[n]contra el se隠or Kaneshiro?[n][w][e]

[msg TalkMsg_ED_bye_D03_03]
[s]Ten en cuenta[n]que el poder del se隠or Kaneshiro[n]eclipsa el m胤o.[n][w][e]

[msg TalkMsg_ED_bye_D04_01]
[s]Bueno, alguien como t雨 est茨[n]a a隠os luz de llegara la reina Futaba.[n][w][e]

[msg TalkMsg_ED_bye_D04_02]
[s]Mmm... De todas formas, un ratero[n]como t雨 nunca podr茨 llegar[n]a la reina Futaba.[n][w][e]

[msg TalkMsg_ED_bye_D04_03]
[s]No creo que me hagas caso,[n]pero es mejor que dejes[n]a la reina Futaba en paz.[n][w][e]

[msg TalkMsg_ED_bye_D05_01]
[s]A fin de cuentas, no eres rival[n]para el se隠or Okumura.[n][w][e]

[msg TalkMsg_ED_bye_D05_02]
[s]Pff... 夷De verdad crees que tienes[n]la m茨s remota posibilidad[n]contra el se隠or Okumura?[n][w][e]

[msg TalkMsg_ED_bye_D05_03]
[s]Ten en cuenta[n]que el poder del se隠or Okumura[n]eclipsa el m胤o.[n][w][e]

[msg TalkMsg_ED_bye_D06_01]
[s]A fin de cuentas, no eres rival[n]para la se隠ora Niijima.[n][w][e]

[msg TalkMsg_ED_bye_D06_02]
[s]Pff... 夷De verdad crees que tienes[n]la m茨s remota posibilidad[n]contra la se隠ora Niijima?[n][w][e]

[msg TalkMsg_ED_bye_D06_03]
[s]Ten en cuenta[n]que el poder de la se隠ora Niijima[n]eclipsa el m胤o.[n][w][e]

[msg TalkMsg_ED_bye_D07_01]
[s]A fin de cuentas, no eres rival[n]para el maestro Akechi.[n][w][e]

[msg TalkMsg_ED_bye_D07_02]
[s]Pff... 夷De verdad crees que tienes[n]la m茨s remota posibilidad[n]contra el maestro Akechi?[n][w][e]

[msg TalkMsg_ED_bye_D07_03]
[s]Ten en cuenta[n]que el poder del maestro Akechi[n]eclipsa el m胤o.[n][w][e]

[msg TalkMsg_ED_bye_D08_01]
[s]A fin de cuentas, no eres rival[n]para el se隠or Shido.[n][w][e]

[msg TalkMsg_ED_bye_D08_02]
[s]Pff... 夷De verdad crees que tienes[n]la m茨s remota posibilidad[n]contra el se隠or Shido?[n][w][e]

[msg TalkMsg_ED_bye_D08_03]
[s]Ten en cuenta[n]que el poder del se隠or Shido[n]eclipsa el m胤o.[n][w][e]

[msg TalkMsg_ED_bye_D09_01]
[s]A fin de cuentas, no eres rival[n]para Su Excelencia.[n][w][e]

[msg TalkMsg_ED_bye_D09_02]
[s]Vaya, ese poder...[n]Me pregunto c吋mo te las apa隠ar胤as[n]contra Su Excelencia.[n][w][e]

[msg TalkMsg_ED_bye_D09_03]
[s]Ten en cuenta[n]que el poder de Su Excelencia[n]eclipsa el m胤o.[n][w][e]

[msg TalkMsg_ED_bye_D10_01]
[s]A fin de cuentas, no eres rival[n]para el jefe secreto.[n][w][e]

[msg TalkMsg_ED_bye_D10_02]
[s]Pff... 夷De verdad crees que tienes[n]la m茨s remota posibilidad[n]contra el jefe secreto?[n][w][e]

[msg TalkMsg_ED_bye_D10_03]
[s]Ten en cuenta[n]que el poder del jefe secreto[n]eclipsa el m胤o.[n][w][e]

[msg TalkMsg_CONTACT_11_1]
[s]斡E-espera! Antes de[n]disparar, dime qu姻 quieres.[n]Pero 斡antes de disparar![n][w][e]

[msg TalkMsg_CONTACT_11_2]
[s]斡Tranquil胤zate! No le dir姻 nada[n]al rey Kamoshida.[n][w][e]

[msg TalkMsg_CONTACT_11_3]
[s]夷De verdad me odias tanto solo[n]porque soy una sombra?[n][w][e]

[msg TalkMsg_CONTACT_12_1]
[s]斡E-espera! Antes de[n]disparar, dime qu姻 quieres.[n]Pero 斡antes de disparar![n][w][e]

[msg TalkMsg_CONTACT_12_2]
[s]斡Tranquil胤zate! No le dir姻 nada[n]al se隠or Madarame.[n][w][e]

[msg TalkMsg_CONTACT_12_3]
[s]A-ay雨dame. No quiero[n]desaparecer.[n][w][e]

[msg TalkMsg_CONTACT_13_1]
[s]斡E-espera! Antes de[n]disparar, dime qu姻 quieres.[n]Pero 斡antes de disparar![n][w][e]

[msg TalkMsg_CONTACT_13_2]
[s]斡Tranquil胤zate! No le dir姻 nada[n]al se隠or Kaneshiro.[n][w][e]

[msg TalkMsg_CONTACT_13_3]
[s]No tienes piedad, 夷eh?[n][w][e]

[msg TalkMsg_CONTACT_14_1]
[s]斡E-espera! Antes de[n]disparar, dime qu姻 quieres.[n]Pero 斡antes de disparar![n][w][e]

[msg TalkMsg_CONTACT_14_2]
[s]斡Tranquil胤zate! No le dir姻 nada[n]a la reina Futaba.[n][w][e]

[msg TalkMsg_CONTACT_14_3]
[s]斡Espera! 夷Qu姻 quieres? Te dar姻[n]lo que sea menos mi vida.[n][w][e]

[msg TalkMsg_CONTACT_15_1]
[s]斡E-espera! Antes de[n]disparar, dime qu姻 quieres.[n]Pero 斡antes de disparar![n][w][e]

[msg TalkMsg_CONTACT_15_2]
[s]斡Tranquil胤zate! No le dir姻 nada[n]al se隠or Okumura.[n][w][e]

[msg TalkMsg_CONTACT_15_3]
[s]斡Espera! 夷Qu姻 quieres? Te dar姻[n]lo que sea menos mi vida.[n][w][e]

[msg TalkMsg_CONTACT_16_1]
[s]斡E-espera! Antes de[n]disparar, dime qu姻 quieres.[n]Pero 斡antes de disparar![n][w][e]

[msg TalkMsg_CONTACT_16_2]
[s]斡Tranquil胤zate! No le dir姻 nada[n]a la se隠ora Niijima.[n][w][e]

[msg TalkMsg_CONTACT_16_3]
[s]斡Espera! 夷Qu姻 quieres? Te dar姻[n]lo que sea menos mi vida.[n][w][e]

[msg TalkMsg_CONTACT_17_1]
[s]斡E-espera! Antes de[n]disparar, dime qu姻 quieres.[n]Pero 斡antes de disparar![n][w][e]

[msg TalkMsg_CONTACT_17_2]
[s]斡Tranquil胤zate! No le dir姻 nada[n]al maestro Akechi.[n][w][e]

[msg TalkMsg_CONTACT_17_3]
[s]斡Espera! 夷Qu姻 quieres? Te dar姻[n]lo que sea menos mi vida.[n][w][e]

[msg TalkMsg_CONTACT_18_1]
[s]斡E-espera! Antes de[n]disparar, dime qu姻 quieres.[n]Pero 斡antes de disparar![n][w][e]

[msg TalkMsg_CONTACT_18_2]
[s]斡Tranquil胤zate! No le dir姻 nada[n]al se隠or Shido.[n][w][e]

[msg TalkMsg_CONTACT_18_3]
[s]斡Espera! 夷Qu姻 quieres? Te dar姻[n]lo que sea menos mi vida.[n][w][e]

[msg TalkMsg_CONTACT_19_1]
[s]斡E-espera! Antes de[n]disparar, dime qu姻 quieres.[n]Pero 斡antes de disparar![n][w][e]

[msg TalkMsg_CONTACT_19_2]
[s]夷Eh...? 斡Tranquil胤zate! No le dir姻[n]nada a Su Excelencia.[n][w][e]

[msg TalkMsg_CONTACT_19_3]
[s]斡Espera! 夷Qu姻 quieres? Te dar姻[n]lo que sea menos mi vida.[n][w][e]

[msg TalkMsg_CONTACT_10_1]
[s]斡E-espera! Antes de[n]disparar, dime qu姻 quieres.[n]Pero 斡antes de disparar![n][w][e]

[msg TalkMsg_CONTACT_10_2]
[s]斡Tranquil胤zate! No le dir姻 nada[n]al jefe secreto.[n][w][e]

[msg TalkMsg_CONTACT_10_3]
[s]斡Espera! 夷Qu姻 quieres? Te dar姻[n]lo que sea menos mi vida.[n][w][e]

[msg TalkMsg_FQ_REACT_GOODMOO]
[s]Je, je, eres lo mejor. 斡Qu姻[n]bien me lo paso contigo![n][w][e]

[msg TalkMsg_FQ_REACT_INTERES]
[s]Deja que te haga una pregunta[n]m茨s. Me intriga hablar contigo.[n][w][e]

[msg TalkMsg_FQ_REACT_DISPLEA]
[s]Bueno, 斡siguiente! No me[n]resultas muy agradable.[n][w][e]

[msg TalkMsg_FQ_REACT_ANGER]
[s]Me cabreas mucho. De no[n]estar en esta situaci吋n,[n]perder胤a la paciencia.[n][w][e]

[msg TalkMsg_FQ_REACT_BROKEDO]
[s]No pasa nada. Sinceramente,[n]tampoco me esperaba demasiado.[n][w][e]

[msg TalkMsg_HAVE_NO_SECRET]
[s]Lo siento, pero... no tengo[n]informaci吋n que parezca 雨til.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF]
[s]斡Venga, pues disp茨rame! 斡Prefiero[n]eso a que me mates[n]de aburrimiento con tu ch茨chara![n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF_2]
[s]Qu姻 ingenuidad la tuya. 夷Crees que[n]cualquiera se har胤a amigo tuyo?[n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF_3]
[s]斡Negociar contigo no tiene sentido![n][w][e]

[msg TalkMsg_SHOOT_REACTION01]
[s]夷No le das tiempo al oponente[n]para que ataque? No est茨 mal.[n]Yo hago lo mismo.[n][w][e]
[s]斡Eh, espera![n]斡Me ha recordado a algo![n][w][e]

[msg TalkMsg_SHOOT_REACTION02]
[s]夷Prefieres hacer las cosas[n]a lo bruto, eh? Te entiendo...[n][w][e]
[s]斡Eh, espera![n]斡Me ha recordado a algo![n][w][e]

[msg TalkMsg_SHOOT_REACTION03]
[s]Veo por donde vas.[n]Consigues ventaja y, despu姻s,[n]acorralas. He usado esa t茨ctica.[n][w][e]
[s]斡Eh, espera![n]斡Me ha recordado a algo![n][w][e]

[msg TalkMsg_SHOOT_REACTION04]
[s]Qu姻 miserable...[n]Creerse superior a un oponente[n]indefenso. Yo hago lo mismo.[n][w][e]
[s]斡Eh, espera![n]斡Me ha recordado a algo![n][w][e]

[msg TalkMsg_PLEAD_SKIMMING]
[s]斡Espera! Me ten胤as fichado[n]todo el tiempo, 夷verdad?[n][w][e]

[msg TalkMsg_PLEAD_NO_SKIMMIN]
[s]夷Vienes a por m胤? 斡Pues no[n]me voy a quedar esperando![n][w][e]

[msg TalkMsg_ACCEPT_ALERT_DOW]
[s]Muy bien. Avisar姻 de que todo[n]est茨 tranquilo por aqu胤.[n][w][e]

[msg TalkMsg_NO_REQUIREMENT]
[s]斡夷No tienes?![n][w][e]

[msg TalkMsg_RESULT_SQ_ITEM1]
[s]Bueno, te dar姻 esto,[n]as胤 que olvida que me has visto.[n][w][e]

[msg TalkMsg_RESULT_SQ_ITEM2]
[s]夷Eres de esa clase de persona?[n]Pues toma esto y estamos en paz.[n][w][e]

[msg TalkMsg_RESULT_SQ_PERSON]
[s]T雨 y yo somos parecidos.[n]夷Mm? 斡Me acabo de acordar de algo![n][w][e]

[msg TalkMsg_RESULT_SQ_PERSON_2]
[s]T雨 y yo pensamos igual.[n]斡Ah! 斡Me acabo de acordar de algo![n][w][e]

[msg TalkMsg_RESULT_SQ_PAYFOR]
[s]Te entiendo, pero... a雨n tengo[n]mis dudas. Te dar姻 esto. Adi吋s.[n][w][e]

[msg TalkMsg_RESULT_SQ_PAYFOR_2]
[s]Ya veo. Creo que te entiendo.[n]Por hoy, te dar姻 esto.[n][w][e]

[msg TalkMsg_RESULT_SQ_AGAIN1]
[s]Entonces, al final, 夷qu姻 era[n]lo que quer胤as decir?[n][w][e]

[msg TalkMsg_RESULT_SQ_AGAIN2]
[s]Entonces, al final, 夷qu姻 era[n]lo que quer胤as decir?[n][w][e]

[msg TalkMsg_RESULT_SQ_CARD1]
[s]A ver, 夷c吋mo te lo digo...?[n]Te dar姻 esto, as胤 que...[n]Haz la vista gorda, 夷vale?[n][w][e]

[msg TalkMsg_RESULT_SQ_CARD2]
[s]S姻 lo que te interesa,[n]as胤 que aqu胤 lo tienes.[n]Espero que te sea de ayuda.[n][w][e]

[msg TalkMsg_RESULT_SQ_COUNTE]
[s]Parece que ninguno de nosotros[n]piensa ceder. As胤 que,[n]斡decid茨moslo combatiendo![n][w][e]

[msg TalkMsg_RESULT_SQ_COUNTE_2]
[s]As胤 que... 夷eres de esa clase[n]de persona? 斡Entonces debes morir,[n]no queda otra![n][w][e]

[msg TalkMsg_RESULT_SQ_ALERT1]
[s]Solo para alguien como t雨...[n]斡Deja que te presente[n]a mi socio m茨s brutal![n][w][e]

[msg TalkMsg_RESULT_SQ_ALERT2]
[s]Ya veo. Acabo de tener una idea.[n]Quiz茨 te venga bien[n]un sabio consejo...[n][w][e]
[s]Un sabio consejo...[n]斡y honestidad brutal![n][w][e]

[msg TalkMsg_RESULT_SQ_INFO1]
[s]Te dar姻 informaci吋n 雨til,[n]as胤 que ya basta.[n][w][e]

[msg TalkMsg_RESULT_SQ_INFO2]
[s]Mira, te dar姻 informaci吋n[n]de calidad, as胤 que pon[n]un poco de tu parte.[n][w][e]

[msg TalkMsg_RESULT_SQ_MONEY1]
[s]Como m胤nimo, me gustar胤a[n]que aceptases esto.[n][w][e]

[msg TalkMsg_RESULT_SQ_MONEY2]
[s]Por eso te voy a dar esto.[n]T雨 no has visto nada, 夷vale?[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_8]
[s]Conque ese es mi camino...[n]Sin embargo, parece que ya[n]conoces la informaci吋n que tengo.[n][w][e]
[s]Deja que te entregue[n][f 2 5 3 9999 1] a cambio...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_9]
[s]Ya veo. Al otro lado del puente...[n]斡Podemos crear un mundo sin guerra![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_10]
[s]Ya veo. Al otro lado del puente...[n]Olv胤dalo. All胤 no hay nada...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_11]
[s]Ya veo. Al otro lado del puente...[n]斡Nos espera una dicha sublime[n]si lo cruzamos juntos![n][w][e]
[s]Pero tu Persona es[n][clr 1][var 2][clr 27]... Toma,[n]acepta [f 2 5 3 9999 1].[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_12]
[s]Ya veo. Al otro lado del puente...[n]斡Nos espera una dicha sublime[n]si lo cruzamos juntos![n][w][e]
[s]Pero tu nivel es demasiado bajo...[n]Lo siento, pero a cambio[n]acepta [f 2 5 3 9999 1].[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_13]
[s]夷Cu茨l es mi camino...?[n][w][e]

[msg TalkMsg_RESULT_HACKING]
[s]Tus palabras me han emocionado...[n]Toma. Lo estaba guardando, pero[n]me gustar胤a que te lo quedaras.[n][w][e]

[msg TalkMsg_SKIMMING_BRAINWA]
[s]Vaya, 夷puedes verlo todo?[n]夷No ser茨s omnisciente?[n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_11]
[s]Gracias por dejarme con vida.[n]夷Mm? 斡Acabo de recordar algo![n][w][e]

[msg TalkMsg_CHARM_TECH_ITEM]
[s]Qu姻 mal. 夷De verdad hay gente que[n]ha sido v胤ctima de tal treta?[n][w][e]

[msg TalkMsg_CHARM_TECH_PERSO]
[s]Pero 夷qu姻...? Bueno, vale.[n]No puedo rechazarte.[n]Te escucho... Je, je, je.[n][w][e]

[msg TalkMsg_BONUS_CARD]
[s]Ah, toma esto.[n]Creo que lo necesitar茨s.[n][w][e]

[msg TalkMsg_DONATION]
[s]夷Ser茨 esto suficiente como[n]para que mires hacia otro lado?[n]El dinero mueve el mundo...[n][w][e]

[msg TalkMsg_UNTALKABLE]
[s]Uh... 斡Aaargh![n][w][e]

[msg TalkMsg_GUY_OP_00_00]
[s]Se acab吋.[n][e]

[msg TalkMsg_GUY_OP_00_01]
[s]Ayuda...[n][e]

[msg TalkMsg_GUY_OP_01_00]
[s]Apuntarme con un arma...[n][e]

[msg TalkMsg_GUY_OP_01_01]
[s]斡Hijo de...![n][e]

[msg TalkMsg_GUY_OP_02_00]
[s]*jadeo* *jadeo*...[n][e]

[msg TalkMsg_GUY_OP_02_01]
[s]斡Es hora de luchar![n][e]

[msg TalkMsg_GUY_OP_03_00]
[s]夷Necesitas algo?[n][e]

[msg TalkMsg_GUY_OP_03_01]
[s]No me subestimes.[n][e]

[msg TalkMsg_GUY_EN_No_00]
[s]Pensaba que iba a morir.[n]Qu姻 magn茨nimo por tu parte[n]dejarme con vida.[n][w][e]

[msg TalkMsg_GUY_EN_No_01]
[s]斡Hasta la vista! Cuando volvamos[n]a encontrarnos, ten por seguro[n]que recordar姻 lo que pas吋 hoy.[n][w][e]

[msg TalkMsg_GUY_EN_No_02]
[s]Me has perdonado la vida.[n]Te lo agradezco.[n][w][e]

[msg TalkMsg_GUY_EN_bye_00]
[s]夷Contento? Bueno, pues me marcho.[n][w][e]

[msg TalkMsg_GUY_EN_bye_01]
[s]Mmm... No s姻 hasta d吋nde[n]llegar茨s con esa actitud.[n][w][e]

[msg TalkMsg_GUY_EN_bye_02]
[s]Es un clich姻, pero lo voy a decir.[n]斡Esto no ha acabado![n][w][e]

[msg TalkMsg_GUY_NEGO_GIVE_00]
[s]夷Esto es para m胤? Mmm...[n]Lo acepto sin reservas.[n][w][e]

[msg TalkMsg_GUY_NEGO_GIVE_01]
[s]Acepto todo lo que me den.[n]Esa es mi filosof胤a.[n][w][e]

[msg TalkMsg_GUY_NEGO_DECLINE]
[s]夷Qu姻 narices...? 夷No te basta[n]con eso? Vaya, no me lo esperaba...[n][w][e]

[msg TalkMsg_GUY_NEGO_DECLINE_2]
[s]夷C吋mo? Qu姻 decepci吋n.[n][w][e]

[msg TalkMsg_GUY_NEGO_TAKE_00]
[s]Me alegro de que nuestro encuentro[n]no fuera in雨til.[n][w][e]

[msg TalkMsg_GUY_NEGO_TAKE_01]
[s]Bueno, supongo[n]que nuestro encuentro[n]tambi姻n es cosa del destino, 夷no?[n][w][e]

[msg TalkMsg_GUY_NEGO_DOUBLEU]
[s]No te cortas un pelo[n]con la avaricia, 夷eh? Vale...[n][w][e]

[msg TalkMsg_GUY_NEGO_DOUBLEU_2]
[s]Supongo que tengo que estar[n]a la altura de las expectativas.[n][w][e]

[msg TalkMsg_GUY_NEGO_AGREE_0]
[s]斡Vaya! Eres mucho m茨s generoso[n]de lo que pareces.[n][w][e]

[msg TalkMsg_GUY_NEGO_AGREE_0_2]
[s]S胤, eso pensaba.[n][w][e]

[msg TalkMsg_GUY_NEGO_REFUSE_]
[s]Si te niegas, me voy a deprimir.[n]夷Cu茨nto pretendes herirme...?[n][w][e]

[msg TalkMsg_GUY_NEGO_REFUSE__2]
[s]斡夷Qu姻?! 夷No te gusta? Eres[n]un humano muy tiquismiquis, 夷eh?[n][w][e]

[msg TalkMsg_Coop_Reiji_00 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 10 301 1]Oye, 夷qu姻 est茨s intentando hacer?[n]斡Piensa en la situaci吋n![n][w][e]

[msg TalkMsg_Coop_Reiji_01 [Ryuji]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Morgana_00 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 10 301 1]斡No te muevas![n]斡Tu destino est茨 en mis garras![n][w][e]

[msg TalkMsg_Coop_Morgana_01 [Morgana]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Ann_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 3 301 1]斡Si no quieres acabar[n]como un colador, no te muevas![n][w][e]

[msg TalkMsg_Coop_Ann_01 [Ann]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Yugo_00 [Yusuke]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 5 3 301 1]斡Resistirse es in雨til![n]Piensa bien en qu姻 situaci吋n est茨s.[n][w][e]

[msg TalkMsg_Coop_Yugo_01 [Yusuke]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Makoto_00 [Makoto]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 3 301 1]斡Deja de resistirte y vamos[n]a negociar![n][w][e]

[msg TalkMsg_Coop_Makoto_01 [Makoto]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Haruko_00 [Haru]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 3 301 1]斡Espera! 夷Entiendes acaso[n]la situaci吋n en la que est茨s?[n][w][e]

[msg TalkMsg_Coop_Haruko_01 [Haru]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Akechi_00 [Akechi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 3 301 1]斡Quieto! Ser茨 mejor que[n]no hagas movimientos repentinos.[n][w][e]

[msg TalkMsg_Coop_Akechi_01 [Akechi]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Sense_Sixthsense [Akechi]]
[s]斡Iniciando Sexto sentido![n][f 1 3 65535][w][e]
[s]Tu sentido aumentado[n]ha detectado una opci吋n[n]que no deb胤a ser escogida.[n][w][e]

[msg TalkMsg_Sense_Negotiatio [Akechi]]
[s]斡Iniciando Negociaci吋n![n][f 1 3 65535][w][e]
[s]Has recibido mayor[n]cooperaci吋n con una t姻cnica de[n]negociaci吋n mejorada.[n][w][e]

[msg TalkMsg_Sense_Gigolo_00 [Akechi]]
[s]斡Iniciando Gigol吋![n][f 1 3 65535][w][e]
[s]Hacer alarde de tu refinada[n]seducci吋n estimula el coraz吋n y[n]la mente de las sombras femeninas.[n][w][e]

[msg TalkMsg_Sense_Performanc [Akechi]]
[s]斡Iniciando Actuaci吋n![n][f 1 3 65535][w][e]
[s]斡Monta un n雨mero espl姻ndido[n]y despierta el inter姻s[n]de las sombras enemigas![n][w][e]

[msg TalkMsg_Sense_Intelligen [Akechi]]
[s]斡Iniciando Inteligencia![n][f 1 3 65535][w][e]
[s]斡Tus amplios conocimientos[n]te servir茨n para ganarte el respeto[n]de las sombras masculinas![n][w][e]

[msg TalkMsg_Tisei]
[s]No tienes la inteligencia[n]suficiente para escoger eso.[n][f 1 4][e]

[msg TalkMsg_Iroke]
[s]No tienes la seducci吋n suficiente[n]para escoger eso.[n][f 1 4][e]

[msg TalkMsg_Ginou]
[s]No tienes la t姻cnica suficiente[n]para escoger eso.[n][f 1 4][e]

[msg TalkMsg_Hinsei]
[s]No tienes el car茨cter suficiente[n]para escoger eso.[n][f 1 4][e]

[msg TalkMsg_Yuuki]
[s]No tienes el Coraje suficiente[n]para escoger eso.[n][f 1 4][e]

[sel Nego_Surrender_sel top]
[s]Conc姻deme tu poder.[e]
[s]Ens姻隠ame el dinero.[e]
[s]Quiero un objeto.[e]
[s]Panther, enc茨rgate t雨.[e]

[sel Nego_Surrender_sel_01 top]
[s][clr 2]郁nete a mi causa.[clr 27][e]
[s]Dame dinero.[e]
[s]Quiero un objeto.[e]
[s]Panther, enc茨rgate t雨.[e]

[sel Nego_Surrender_sel_02 top]
[s]Conc姻deme tu poder.[e]
[s][clr 2]Ens姻隠ame el dinero.[clr 27][e]
[s]Quiero un objeto.[e]
[s]Panther, enc茨rgate t雨.[e]

[sel Nego_Surrender_sel_03 top]
[s]Conc姻deme tu poder.[e]
[s]Dame dinero.[e]
[s][clr 2]Dame la mercanc胤a.[clr 27][e]
[s]Panther, enc茨rgate t雨.[e]

[sel Nego_Surrender_sel_04 top]
[s]Conc姻deme tu poder.[e]
[s]Ens姻隠ame el dinero.[e]
[s][clr 2]Dame lo que escondes.[clr 27][e]
[s]Panther, enc茨rgate t雨.[e]

[sel Nego_Payfor_sel top]
[s]Me lo quedo.[e]
[s][clr 2]Eso no es lo mejor que tienes.[clr 27][e]

[sel Nego_Brainwash_sel top]
[s]R胤ndete ante m胤.[e]
[s]Dame un donativo.[e]
[s]Dame algo 雨til.[e]
[s]Panther, enc茨rgate t雨.[e]

[sel TalkSel_Greet_Possesed_B top]
[s]Bueno, vale.[e]
[s]No te he pedido esto.[e]

[sel TalkSel_Pre_Question top]
[s]Bueno, vale.[e]
[s]No es necesario.[e]

[msg Talk_tech]
[s]Yoshida Toranosuke[n]斡Gesti吋n de impresi吋n! (Provisional)[n][w][e]

[sel TalkSel_Tech top]
[s]斡Ayuda, por favor![e]
[s]...[e]

[msg CharmTech [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]Vamos, ricura. 夷No puedes ser[n]un poco m茨s amable conmigo?[n][w][e]

[msg CharmActing [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]夷C吋mo te atreves a quitarnos eso?[n][w][e]

[msg RareBooster]
[s]Yoshida Toranosuke[n]斡Gesti吋n de impresi吋n! (Provisional)[n][w][e]

[msg CheapAct [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 300 1]Joker, tengo miedo... Deber胤amos[n]irnos. 斡Eh! 夷Puedes decirle[n]a tu jefe que nos vamos?[n][w][e]

[msg TalkMsg_cnt_interruptE]
[s]Otro enemigo se ha metido[n]en la conversaci吋n.[n][w][e]

[msg TalkMsg_cnt_interruptP]
[s]Tras hablar con el objetivo una vez[n]tus compa隠eros pueden entrometerse[n]para avanzar (% de posibilidad).[n][w][e]

[msg TalkMsg_cnt_refuse]
[s]El objetivo se niega a hablar.[n]→Esto ocurre si el resultado[n]de la conversaci吋n es una negativa.[n][w][e]

[msg TalkMsg_cnt_anger]
[s]Target is angry and counterattacks[n]Bad case when the result of[n]the conversation is refusal.[n][w][e]

[msg TalkMsg_cnt_unusual]
[s]No se puede hablar[n]debido a los efectos de estado.[n][w][e]

[msg TalkMsg_EOF]
[s]...[n][w][e]

[msg DebugMsg_ERROR]
[s](Error)[n]→A variable is set[n]to an invalid value.[n][w][e]

[msg DebugMsg_CHARACTER]
[s](Debug Mode)[n]Target Personality Type[n][w][e]

[sel DebugSel_CHARACTER top]
[s]Tipo A[e]
[s]Tipo B[e]
[s]Tipo C[e]
[s]Tipo D[e]
[s]Aleatorio[e]

[msg DebugMsg_CHECK_VAR]
[s][var 0].[n][w][e]

[msg DebugMsg_ENEMY_LV]
[s]ID del enemigo: [var 3][n]Nivel del enemigo: [var 0][n]Nivel del protagonista: [var 1][n]AI_CHK_ENIDLV_O([var 0], 1) = [var 2][n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_4 [Ann]]
[s]Bien. Compartir姻 esta experiencia[n]con mi yo en tu interior.[n][w][e]

[msg TalkMsg_Coop_AkechiB_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 3 301 1]No parece una decisi吋n[n]muy acertada...[n]Quiz茨 deber胤as pens茨rtelo mejor.[n][w][e]

[msg TalkMsg_Coop_Kasumi_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 1]斡Alto! Ser茨 mejor que[n]no hagas nada imprudente.[n][w][e]

[msg TalkMsg_Coop_Sumire_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 1]斡Alto! Ser茨 mejor que[n]no hagas nada imprudente.[n][w][e]

