[msg TalkMsg_DUMMY]
[s]...[n][w][e]

[msg TalkMsg_GUY_CONTACT_01]
[s]Ayyy... Qu姻 mal...[n]Vaya, 夷c吋mo han podido[n]terminar as胤 las cosas?[n][w][e]

[msg TalkMsg_GUY_CONTACT_02]
[s]Uf, eres un pelmazo.[n]斡Acosador! 斡Rarito! [n][w][e]

[msg TalkMsg_GUY_CONTACT_03]
[s]Odio esto.[n]Quiero irme a casa. [n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01]
[s]斡Oye! 斡Eso ha dolido![n][w][e]
[s]夷Y si me deja[n]una cicatriz permanente?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_01 top]
[s]Lo siento... [e]
[s]Ret吋cate con cirug胤a pl茨stica.[e]
[s]Yo asumo la responsabilidad.[e]

[msg TalkMsg_GUY_CHAT_FQ_01_R]
[s]A veces est茨 bien[n]que un t胤o sea un poco agresivo,[n]pero ser violento ya es pasarse.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_2]
[s]Oye, ten cuidado, 夷vale?[n]Tengo la piel sensible...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_3]
[s]Espera, 夷est茨s haciendo esto[n]para llamar mi atenci吋n? Se siente.[n]No lo vas a conseguir.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_4]
[s]夷Eres imb姻cil o qu姻?[n]夷Piensas que te voy a perdonar[n]cuando me est茨s disparando?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_5]
[s]斡Oye! 斡No me hace falta! 斡M胤rame![n]夷Est茨s ciego o algo por el estilo?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_6]
[s]Pero he o胤do que si empiezas, no[n]puedes parar. 夷Cu茨nto me costar胤a[n]arreglarme todo el cuerpo?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_7]
[s]Oh, 斡eso es cierto! Tambi姻n quiero[n]operarme los ojos y la nariz... 斡Ah![n]斡Y hacerme una liposucci吋n![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_8]
[s]Oye, 斡eso no solucionar胤a[n]el verdadero problema! 斡Me refiero[n]a ti! 斡Todo esto es tu culpa![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_9]
[s]夷Eh? Asume la responsa... 斡Madre m胤a![n]斡Nos acabamos de conocer! 斡A雨n no[n]podemos casarnos ni nada de eso![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_10]
[s]夷Eh? Asume la responsa... Espera, 斡es[n]demasiado pronto! No me disgusta[n]la idea, pero no puedo hacerlo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_11]
[s]Ah, 夷s胤? 夷Cu茨nto costar胤a tratar[n]mis heridas? No puedes[n]permit胤rtelo con tu paga.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_12]
[s]Uf, qu姻 maleducado.[n]Deber胤as estar suplic茨ndome[n]para que te deje compens茨rmelo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_13]
[s]Dios, 斡qu姻 ruido! 夷Sabes[n]a cu茨nta gente est茨s molestando?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_14]
[s]斡夷Me quieres disparar ahora?![n]Leer entre l胤neas se te da de pena...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_15]
[s]Uf, nunca has hablado[n]con una chica[n]en la vida real, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_01_R_16]
[s]夷Es que no lo ves? Soy una chica.[n]No deber胤as tratarme as胤.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02]
[s]Adem茨s, 夷por qu姻 llevas encima[n]algo as胤?[n][w][e]
[s]夷Vas con un arma[n]porque crees que te har茨[n]m茨s popular entre las chicas?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_02 top]
[s]Eso es.[e]
[s]夷Que no?[e]
[s]Es una cuesti吋n de autosuperaci吋n.[e]

[msg TalkMsg_GUY_CHAT_FQ_02_R]
[s]Espera, 夷en serio? 夷O sea que ya[n]ha funcionado en alguna parte?[n]夷Me estaba equivocando yo?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_2]
[s]Ah... Normalmente eso...[n]no suele funcionar...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_3]
[s]Ah, he o胤do hablar de chicos[n]como t雨. Est茨n tan desesperados[n]por ligar que da grima...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_4]
[s]Si quieres ser popular entre[n]las chicas, 斡debes ser majo! Gasta[n]dinero en citas, 斡no en armas![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_5]
[s]Est茨s fatal. Madre m胤a, y tambi姻n[n]creer茨s que los pa隠uelos y[n]las camisas sin mangas molan, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_6]
[s]Venga ya. 或Si no te gusto,[n]te disparo位. Hasta los animales[n]pueden ser m茨s rom茨nticos.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_7]
[s]Te has tomado demasiado en serio[n]lo de que a ellas les van los[n]chicos con aficiones. Qu姻 triste.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_8]
[s]斡Claro que no![n]斡夷C吋mo vas a ganarte[n]a una chica enca隠on茨ndola?![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_9]
[s]Supongo que la superaci吋n personal[n]es importante, s胤, pero es que[n]no lo est茨s haciendo bien.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_10]
[s]夷Qu姻? Pues hazlo con un experto[n]en artes marciales o un yakuza,[n]no con una chica delicada como yo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_11]
[s]夷C吋mo te vas a superar as胤?[n]Debes ser el peor de la clase.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_12]
[s]Ah, 夷no podr胤as superarte[n]t雨 solito en tu habitaci吋n,[n]sin molestar a otras personas?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_13]
[s]Vale, vale, vas bien.[n]Ya vale, c茨lmate.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_14]
[s]Vale, entiendo que eso podr胤a[n]atraer a ciertas chicas, pero[n]no es para todo el mundo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_15]
[s]Oh, no... Est茨s completamente[n]perdido en tu propio mundo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_02_R_16]
[s]斡Ay! 斡Debes odiar escuchar[n]a los dem茨s! 夷Tu familia[n]te trata as胤?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03]
[s]Oye. Esto es un asalto, 夷verdad?[n][w][e]
[s]Quiz茨 llame a la polic胤a.[n]斡Quiz茨 diga que has hecho cosas[n]peores de las que has hecho![n][w][e]

[sel TalkSel_GUY_CHAT_FQ_03 top]
[s]Venga, ll茨malos, ten narices.[e]
[s]Perd吋name.[e]
[s]Era en defensa propia.[e]

[msg TalkMsg_GUY_CHAT_FQ_03_R]
[s]Soy la v胤ctima aqu胤, 夷y te enfadas[n]t雨? 夷Y qu姻 m茨s? Vaya...[n]Te da exactamente igual, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_2]
[s]S胤, probablemente ni aparecer茨n[n]aunque los llame.[n]O sea, mira d吋nde estamos...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_3]
[s]夷Qu姻? 夷A qu姻 viene esa actitud?[n]Vale, 斡ll茨malos t雨 si tanto[n]quieres que vengan![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_4]
[s]Supongo que tendr姻 que llamar yo... [n]斡No me vengas llorando cuando[n]te arrepientas![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_5]
[s]夷Tienes miedo? No seas tonto.[n]La polic胤a no puede venir aqu胤.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_6]
[s]夷Qu姻? 夷Te da miedo? Je, quiz茨[n]tambi姻n llame a tus papis.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_7]
[s]夷Te da miedo la palabra 或polic胤a位?[n]Qu姻 pat姻tico.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_8]
[s]斡Quiz茨 no deber胤as haber hecho[n]algo as胤 en primer lugar! [n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_9]
[s]Eso dilo cuando te enfrentes[n]a alg雨n engendro. Herir a una[n]monada como yo deber胤a ser delito.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_10]
[s]夷Alegar胤as defensa propia[n]contra una chica como yo?[n]Uf, qu姻 pat姻tico...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_11]
[s]A雨n as胤, 夷no crees que[n]est茨s exagerando?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_12]
[s]夷Sabes? Yo podr胤a hacer lo mismo[n]y decir que fue en defensa propia.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_13]
[s]Si vemos a la polic胤a,[n]les contar姻 lo del disparo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_14]
[s]斡Esto es un intento de asesinato![n]斡Qu姻 miedo![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_15]
[s]Vaya, me has disparado y todo...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_03_R_16]
[s]斡Bah, olv胤dalo! 斡No llamar姻[n]a la polic胤a! De hecho, 斡puede[n]que ni pueda venir aqu胤![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04]
[s]No me digas que vas a disparar.[n]No vas a hacerme eso[n]de verdad, 夷no?[n][w][e]
[s]Oye, 夷qu姻 te parece esto? Si no[n]me disparas, te doy un beso.[n]No es mal trato, 夷verdad?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_04 top]
[s]No es mala idea.[e]
[s]No quiero besos.[e]
[s]Resp姻tate un poco.[e]

[msg TalkMsg_GUY_CHAT_FQ_04_R]
[s]斡Admite que eso te alegra![n]Uf, qu姻 aguafiestas.[n]Olv胤dalo, lo retiro.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_2]
[s]Pens茨ndolo mejor, esa m茨scara[n]que llevas me lastimar胤a la cara.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_3]
[s]夷Eh? 夷No sabes lo valioso[n]que es un beso m胤o? Uf, pues[n]ya no me apetece.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_4]
[s]Espera, ahora que lo pienso,[n]no es un trato justo. Lo retiro.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_5]
[s]Venga ya, no iba a obligarte.[n]斡夷A ti qu姻 te pasa?![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_6]
[s]Ah, no sabes c吋mo se hace, 夷verdad?[n]No hace falta que lo digas...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_7]
[s]夷Qu姻? 斡Qu胤tate la m茨scara y[n]ven aqu胤! 斡Te dar姻 un beso[n]que te provocar茨 pesadillas![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_8]
[s]Ah, mira qu姻 t胤mido.[n]斡Debes estar rojo como un tomate[n]bajo esa m茨scara![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_9]
[s]夷Qu姻? 夷Lo dices para ser amable?[n]夷Estamos intentando matarnos[n]y sales con esas?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_10]
[s]斡C茨llate! 夷Qui姻n te crees que eres?[n]Si quieres vivir como en una peli[n]de adolescentes, 斡ve a otra parte![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_11]
[s]夷Te lo tomaste en serio?[n]斡Madre m胤a! Yo no voy por ah胤[n]besando a nadie, 夷sabes?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_12]
[s]斡No hace falta que me lo digas![n]Soy una monada, 斡as胤 que claro[n]que tengo amor propio![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_13]
[s]夷Qu姻 narices...? 夷Esto es como cuando[n]un ni隠o te pega porque siente[n]verg鵜enza? Te est茨s pasando.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_14]
[s]Alto ah胤... 夷No te basta con un beso?[n]夷No crees que quiz茨 esperas[n]demasiado de m胤?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_15]
[s]Hala, qu姻 grosero. No solo quieres[n]hacerme da隠o, sino tambi姻n piensas[n]herir mis sentimientos. 夷En serio?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_04_R_16]
[s]斡Cuidado! 斡Si me das en los labios,[n]arruinar茨s lo mejor que tengo![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05]
[s]夷Eh? Tu olor tiene algo especial...[n]Ah, claro...[n][w][e]
[s]Cuesta verlo[n]con esa m茨scara, pero...[n]eres guapo, 夷verdad?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_05 top]
[s]夷C吋mo lo has sabido?[e]
[s]No, para nada.[e]
[s]No s姻, yo me veo bien.[e]

[msg TalkMsg_GUY_CHAT_FQ_05_R]
[s]夷Eh? 夷Por qu姻 llevas m茨scara[n]entonces? Creo que no[n]se te da bien venderte.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_2]
[s]斡Pues s胤 que tenemos la confianza[n]hasta arriba! 斡Qu姻 gracioso![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_3]
[s]Ah, 夷lo admites tan f茨cilmente?[n]Est茨 bien. Creo que ahora[n]entiendo qu姻 clase de persona eres.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_4]
[s]斡Podr茨s decir eso cuando te quites[n]esa m茨scara! 斡Antes[n]no tienes derecho a juzgarme![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_5]
[s]Bueno, los chicos pod姻is permitiros[n]no arreglaros tanto, cuenta m茨s el[n]coraz吋n... y la cartera.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_6]
[s]夷Eh? Me tratas as胤...[n]夷y ni siquiera eres guapo?[n]Vaya, qu姻 decepci吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_7]
[s]Al menos eres mejor[n]que toda esa gente fea[n]que va de sobrada.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_8]
[s]夷En serio? Bueno, quiz茨 lo pens姻[n]por tus ojos. Oye, al menos[n]tienes eso bueno.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_9]
[s]Ese tipo de modestia es la que[n]suele usar la gente m茨s arrogante.[n]Deber胤as cortar el rollo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_10]
[s]Puaj. No admitirlo[n]abiertamente te hace parecer[n]narcisista. 斡Qu姻 pelmazo! [n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_11]
[s]Me suena a falsa modestia.[n]夷Seguro que no eres[n]un engre胤do?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_12]
[s]夷Ah, s胤? Pues te aviso de que soy[n]bastante exigente a la hora[n]de dar mi visto bueno.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_13]
[s]No estoy segura de si tu reacci吋n[n]ha querido decir 或C茨llate位[n]o 或斡Pues claro que s胤!位.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_14]
[s]夷Sabes? Tu aspecto y[n]tu constituci吋n no est茨n nada mal.[n]Pero tu personalidad...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_15]
[s]夷Qu姻? 夷Crees que supongo[n]una amenaza para ti ahora mismo?[n]斡No me muevo tan r茨pido![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_05_R_16]
[s]斡Esto no una conversaci吋n![n]Tus habilidades comunicativas[n]dejan mucho que desear.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06]
[s]斡Ah! 斡El bajo de ese abrigo[n]es una monada![n][w][e]
[s]夷Solo lo tienen para hombre?[n]夷D吋nde lo has comprado?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_06 top]
[s]夷Lo quieres?[e]
[s]Por internet.[e]
[s]No est茨 a la venta.[e]

[msg TalkMsg_GUY_CHAT_FQ_06_R]
[s]Eso me da igual, pero la marca[n]s胤 me interesa.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_2]
[s]La verdad es que tampoco me[n]gusta tanto. Da igual.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_3]
[s]夷Qu姻? 夷De verdad? Espera, es para[n]chicos. Ya no lo quiero.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_4]
[s]斡Pero no el que llevas t雨, puag![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_5]
[s]Comprar por internet es lo mejor,[n]y te lo vienen a traer. Le echar姻[n]un vistazo si logro volver a casa.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_6]
[s]Debes haber pasado mucho tiempo[n]buscando en internet para encontrar[n]eso. 夷Es que no tienes amigos?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_7]
[s]Pero me da miedo que me roben[n]informaci吋n privada[n]y la divulguen en internet. [n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_8]
[s]Pero 夷no es arriesgado comprar[n]por internet? Hay empresas[n]extranjeras que venden imitaciones.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_9]
[s]Entonces, 夷qu姻? 夷Lo llevabas puesto[n]sin darte cuenta?[n]Tienes que mentir mejor.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_10]
[s]Has limpiado algo que encontraste[n]en la basura, 夷verdad? No finjas[n]que es mejor de lo que es.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_11]
[s]夷Me tratas as胤 por mostrar inter姻s?[n]Bah, 斡quiero matarte[n]por ser tan capullo![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_12]
[s]夷Qu姻? 夷Te lo has hecho t雨? 斡No![n]Eres muy h茨bil con las manos, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_13]
[s]夷Tanto te importa que no se sepa?[n]夷Quieres que tu tiendecilla[n]favorita no se haga famosa?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_14]
[s]Si de verdad no quieres dec胤rmelo,[n]no te preguntar姻 m茨s.[n]Tampoco es que me importe.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_15]
[s]No hace falta mucho[n]para provocarte, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_06_R_16]
[s]夷As胤 me pagas que intente[n]portarme bien contigo?[n]Uf, qu姻 fastidio.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07]
[s]Entonces... 夷este es mi fin?[n]Pero si a雨n soy muy joven.[n][w][e]
[s]Oye, si no me muero aqu胤, 夷c吋mo[n]crees que ser姻 en el futuro?[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_07 top]
[s]Una mujer mayor muy moderna.[e]
[s]No puedo medirlo.[e]
[s]Viviendo en las sombras.[e]

[msg TalkMsg_GUY_CHAT_FQ_07_R]
[s]Bueno, s胤. Est茨 claro que voy por[n]buen camino, y soy muy exigente[n]con mi maquillaje y mi estilo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_2]
[s]Quiero seguir siendo guapa cuando[n]sea mayor. Pero hay que invertir[n]tiempo y dinero para eso.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_3]
[s]El futuro parece estar muy lejos,[n]as胤 que cuesta imaginarlo. Y pensar[n]en m胤 de mayor me asusta...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_4]
[s]Jo, no quiero envejecer. Algunas[n]mujeres elegantes est茨n estupendas,[n]pero siguen pareciendo viejas.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_5]
[s]Solo lo dices porque no se te[n]ocurre nada m茨s, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_6]
[s]夷Insin雨as que eres incapaz[n]de medirme?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_7]
[s]夷A que s胤?[n]斡Tengo un potencial ilimitado![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_8]
[s]斡Venga ya! Ahora es cuando[n]tienes que esforzarte[n]al m茨ximo para medirlo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_9]
[s]Calla, 斡no lo decidas por m胤![n]斡Est茨s hablando de m胤![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_10]
[s]Bueno, s胤... Si dejo esto,[n]es lo que pasar茨. 斡Tengo que[n]levantar el 茨nimo![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_11]
[s]夷Vivir en las tinieblas? 夷Como[n]la gente fiestera? Yo me veo[n]trabajando de hostess.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_12]
[s]Oye, si mi futuro est茨[n]en las tinieblas,[n]夷no ser胤a por tu culpa?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_13]
[s]Intentas... 夷Intentas animarme?[n]Creo que ya entiendo...[n]Si me rindo, se acabar茨 todo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_14]
[s]夷Quieres que... mire hacia delante?[n]Mirar hacia delante y no hacia[n]atr茨s. Supongo que tienes raz吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_15]
[s]Vale, no est茨s de humor[n]para charlar. Ya paro.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_07_R_16]
[s]斡Oye, ya basta! 斡D姻jame pensar[n]un momento, idiota![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08]
[s]Pero 夷por qu姻 yo?[n][w][e]
[s]Seguro que hay otras personas[n]en el mundo que te incordiar胤an[n]m茨s. Anda, venga, cu姻ntamelo.[n][w][e]

[sel TalkSel_GUY_CHAT_FQ_08 top]
[s]La gente mayor que se cree joven.[e]
[s]A m胤 no me molesta nadie.[e]
[s]Odio a todo el mundo.[e]

[msg TalkMsg_GUY_CHAT_FQ_08_R]
[s]夷Qu姻姻姻? 夷De verdad? 夷Tan malo[n]es que alguien quiera volver[n]a sentirse joven?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_2]
[s]斡Claro! Me gustar胤a que vistieran[n]acorde con su edad...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_3]
[s]Alg雨n d胤a t雨 tambi姻n[n]te har茨s mayor.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_4]
[s]斡Ah! 斡Lo entiendo perfectamente![n]Aunque la mona se vista de seda...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_5]
[s]斡S胤, desde luego![n]斡Todos tienen sus cosas! 斡Pero[n]es mucho mejor ser superamiguis![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_6]
[s]斡Ojal茨! Entonces... 斡夷por qu姻[n]me est茨s haciendo esto?![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_7]
[s]斡Ah, qu姻 gran forma de ver la vida![n]Al fin y al cabo, la gente[n]no puede vivir sola.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_8]
[s]斡Me cabreas much胤simo![n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_9]
[s]夷Te ha pasado algo?[n]Si te oyera tu madre,[n]se preocupar胤a mucho.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_10]
[s]Te entiendo. 夷Por qu姻 ibas a querer[n]vivir en un mundo[n]que no gira alrededor de ti?[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_11]
[s]S姻 c吋mo te sientes. A veces[n]pienso que todo el mundo[n]es tonto de remate, menos yo.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_12]
[s]Ese punto de vista es muy extremo.[n]Creo que pasas mucho tiempo[n]jugando a la consola.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_13]
[s]Espera, 夷yo soy quien te irrita?[n]Me da que est茨s enamorado...[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_14]
[s]夷A ti qui姻n te ha dado permiso para[n]llevar un arma? Quiero hablar[n]con el encargado.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_15]
[s]Cualquiera se enfadar胤a con alguien[n]que dispara en vez de hablar[n]como una persona normal.[n][w][e]

[msg TalkMsg_GUY_CHAT_FQ_08_R_16]
[s]夷Por qu姻 no intentas expresar[n]cu茨nto te irrito con palabras?[n]Preferir胤a que no usaras tu arma.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01]
[s]Vale, lo entiendo. En realidad,[n]no quer胤as acercarte a m胤.[n][w][e]
[s]A la hora de la verdad,[n]斡no fuiste capaz de hacerme nada![n][w][e]

[sel TalkSel_GUY_CHAT_SQ_01 top]
[s]Podr胤a.[e]
[s]夷C吋mo lo sabes?[e]
[s]夷Qu姻 quieres que haga?[e]

[msg TalkMsg_GUY_CHAT_SQ_01_R]
[s]Entonces, hazlo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_2]
[s]Ohhh, 夷te quejas porque te he[n]tocado la fibra sensible? Ja, ja.[n]As胤 no vamos a ninguna parte.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_3]
[s]斡Si mientes as胤 te crecer茨[n]la nariz! 斡Esa frase[n]no me ha gustado nada![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_4]
[s]斡Hablar es muy f茨cil![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_5]
[s]Puedes llamarlo intuici吋n femenina...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_6]
[s]斡Claro que puedo![n]Al fin y al cabo,[n]tengo mucha experiencia.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_7]
[s]Oh, 夷lo dec胤as en serio...?[n]Ya veo...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_8]
[s]Mmm, mira c吋mo est茨 la situaci吋n.[n]No mola nada.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_9]
[s]Bueno... 夷no deber胤as guiarme[n]t雨 a m胤?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_10]
[s]Vamos, 斡al menos intenta[n]adivinar lo que quiero![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_11]
[s]夷Puedes dejar que me marche?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_12]
[s]Pfff, 斡solo los viejos cascarrabias[n]dicen esas cosas![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_13]
[s]夷Quieres demostrar[n]que me equivoco? Qu姻 fastidio...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_14]
[s]斡Vale, lo pillo! Supongo que[n]haces las cosas a tu propio ritmo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_15]
[s]夷Eres de los que intenta demostrar[n]que la gente se equivoca[n]cuando te subestima?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_01_R_16]
[s]夷Eres de los que usan la violencia[n]en vez de hablar[n]como una persona normal?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02]
[s]Da igual, estoy muy enfadada.[n]Parece que la predicci吋n[n]estaba en lo cierto.[n][w][e]
[s]Mi hor吋scopo dec胤a que hoy iba[n]a tener 或problemas en mi relaci吋n位.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_02 top]
[s]Parece que se ha hecho realidad.[e]
[s]Es un simple hor吋scopo.[e]
[s]夷Tienes suerte en el amor?[e]

[msg TalkMsg_GUY_CHAT_SQ_02_R]
[s]A m胤 me lo vas a decir... 斡Uf![n]斡Tambi姻n tengo muy mala suerte[n]con el dinero![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_2]
[s]夷Por qu姻 se cumplen siempre[n]las cosas malas?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_3]
[s]Bueno, supongo que es[n]mejor que estar sola, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_4]
[s]夷Te est茨s riendo de m胤?[n]Uf, 斡eres un pelmazo![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_5]
[s]Supongo que no echarle[n]la culpa a nada demuestra[n]que tienes una mente abierta.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_6]
[s]C茨llate, ahora mismo[n]no me apetece que me den un serm吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_7]
[s]斡Oye, que todo esto es culpa tuya![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_8]
[s]Lo entiendo. Mentalmente vale,[n]pero 夷emocionalmente?[n]Yo no lo soporto.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_9]
[s]Quieres decir...[n]夷porque te he conocido?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_10]
[s]Creo que mi vida amorosa[n]es bastante buena... Creo...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_11]
[s]Uf, el amor es un asco.[n]Ahora mismo no quiero saber[n]nada de aventuras amorosas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_12]
[s]夷Crees que eso va a hacer[n]que me sienta mejor?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_13]
[s]Es verdad. Si he conocido[n]a un t胤o tan rarito como t雨...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_14]
[s]Oye, 夷tienes alg雨n problema?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_15]
[s]斡Olv胤date de los problemas![n]斡Esto es pura mala suerte![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_02_R_16]
[s]Puede que tengas problemas[n]de personalidad, pero est茨 bien[n]que tomes cartas en el asunto.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03]
[s]Eh, 夷tienes hambre?[n][w][e]
[s]夷Qu姻 te parece si hacemos[n]una pausa y picamos algo?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_03 top]
[s]夷Qu姻 te apetece?[e]
[s]Me da que s胤.[e]
[s]Ahora no es momento.[e]

[msg TalkMsg_GUY_CHAT_SQ_03_R]
[s]Eso deber胤a decidirlo el chico.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_2]
[s]Podemos ir a pillar algo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_3]
[s]斡Me apetece algo frito![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_4]
[s]Eh, 夷crees que te voy a comer a ti?[n]斡Un poquito de por favor![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_5]
[s]斡Genial! 斡Venga, vamos![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_6]
[s]斡Vale! 夷Ad吋nde vamos?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_7]
[s]Mejor no. Es probable que tengamos[n]gustos distintos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_8]
[s]No llevo dinero encima. 斡Qu姻 pena![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_9]
[s]Entonces... 斡A lo mejor soy yo [n]quien te come a ti![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_10]
[s]... No tiene ninguna gracia.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_11]
[s]斡No seas as胤! 斡No iba en serio![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_12]
[s]Pus vamos cuando terminemos aqu胤.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_13]
[s]Mmm, obtengo suficiente[n]hierro tomando suplementos...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_14]
[s]Esta humareda...[n]Me hace pensar en un arroz frito[n]o una barbacoa...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_15]
[s]Vale, 夷te parece bien si pedimos[n]algo para que nos lo traigan?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_03_R_16]
[s]斡Si no tienes hambre, dilo![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04]
[s]斡Mierda! 斡El evento era hoy![n]Espero que vengan muchos guaperas.[n][w][e]
[s]夷Qu姻 crees que deber胤a ponerme?[n]Lo admito, hoy quiero[n]llamar la atenci吋n.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_04 top]
[s]El uniforme del instituto.[e]
[s]Kimono.[e]
[s]Nada.[e]

[msg TalkMsg_GUY_CHAT_SQ_04_R]
[s]夷Que qu姻? 夷Te van los uniformes?[n]斡Venga ya! 斡No fastidies![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_2]
[s]No, as胤 no destacar胤a.[n]Habr茨 muchas chicas[n]vestidas de esa forma.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_3]
[s]S胤, pero creo que muchas chicas[n]llevar茨n lo mismo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_4]
[s]Ah, esa es la regla de oro, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_5]
[s]Eso no se me hab胤a ocurrido. Yo[n]tambi姻n parecer胤a pura e inocente.[n]A los chicos os gusta eso...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_6]
[s]夷Qu姻? 夷Y no me ser茨 dif胤cil[n]bailar y comer con eso?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_7]
[s]夷C吋mo? 夷Un kimono[n]le quedar胤a bien incluso[n]a alguien con mi figura?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_8]
[s]Lo pillo. El estilo japon姻s[n]ahora est茨 muy de moda[n]en todo el mundo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_9]
[s]No, no pienso ir desnuda.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_10]
[s]斡Todos los chicos sois iguales![n]斡Eres muy divertido![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_11]
[s]夷Como una nudista?[n]斡Yo no puedo hacer eso![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_12]
[s]C茨llate, 雨ltimamente[n]he comido muchas chucher胤as...[n]No podr胤a ni aunque quisiera.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_13]
[s]夷Qu姻? 夷Me recomiendas[n]a隠adirle un toque de sangre[n]a mi modelito? 斡Qu姻 buena idea![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_14]
[s]Oye, ten cuidado. 斡No vayas[n]a agujerearme la ropa![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_15]
[s]Creo que lo pillo. Es mejor[n]obligar a los chicos a mirarme[n]que intentar satisfacer sus gustos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_04_R_16]
[s]斡Deja eso para la disco![n]斡Con la energ胤a que derrochas,[n]ser茨s el alma de la fiesta![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05]
[s]夷Se puede saber por qu姻 est茨s[n]tan interesado en m胤?[n][w][e]
[s]Si quieres, hoy podemos[n]salir juntos sin compromiso.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_05 top]
[s]Si te apetece a ti...[e]
[s]夷Sin compromiso?[e]
[s]Ya tengo bastante con lo m胤o.[e]

[msg TalkMsg_GUY_CHAT_SQ_05_R]
[s]Oh, no, deber胤a ser yo[n]la que dijera eso...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_2]
[s]Vaya, parece que s胤 tienes modales[n]despu姻s de todo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_3]
[s]Guau. 夷Sales con gente[n]con tanta facilidad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_4]
[s]夷Est茨s nervioso? Vaya,[n]eso no me lo esperaba.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_5]
[s]夷Qu姻? 夷Dices que un d胤a[n]no es suficiente?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_6]
[s]S胤, solo hoy.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_7]
[s]El principio es lo de menos.[n]Lo importante[n]es lo que viene despu姻s.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_8]
[s]斡No me hagas repetirlo[n]tantas veces![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_9]
[s]斡Eh! 斡Te estoy haciendo un favor![n]斡Ser茨 mejor que aceptes![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_10]
[s]斡Qu姻 maleducado! Encima que[n]yo he dado el primer paso...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_11]
[s]斡Ah! 夷Eres de los que har胤a[n]algo as胤 con cualquiera?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_12]
[s]Venga ya, no finjas.[n]No tienes a nadie esper茨ndote[n]en casa, 夷a que no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_13]
[s]斡Je! Ese es el pistoletazo[n]de salida de nuestra relaci吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_14]
[s]夷Ya est茨s intentado imponer[n]tu dominio sobre la relaci吋n?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_15]
[s]Qu姻 pesado... Si no te interesa,[n]solo tienes que decirlo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_05_R_16]
[s]夷No quieres una cita?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06]
[s]Si quieres que vayamos[n]a alg雨n sitio, yo encantada.[n][w][e]
[s]No me entusiasma la idea[n]de volver a casa[n]con los pesados de mis padres.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_06 top]
[s]Los padres son lo peor.[e]
[s]Deber胤as querer a tus padres.[e]
[s]夷Quieres venirte a mi casa?[e]

[msg TalkMsg_GUY_CHAT_SQ_06_R]
[s]Bueno, no todos son malos...[n]Nada, olvida lo que he dicho.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_2]
[s]S胤, no entienden que las cosas[n]no son como en su 姻poca...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_3]
[s]S胤, pero los llamas cuando[n]no sabes nada de ellos[n]o se encuentran mal, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_4]
[s]S胤, verlos llorar[n]me saca de quicio.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_5]
[s]Ya, pero me pone de los nervios[n]c吋mo dicen las cosas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_6]
[s]斡Soy m茨s independiente[n]de lo que piensan![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_7]
[s]斡Ya lo s姻![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_8]
[s]斡Lo que no entiendo es por qu姻[n]se tienen que meter[n]en mis cosas![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_9]
[s]Uf, creo que paso, que[n]tampoco somos tan amigos...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_10]
[s]斡Vale, venga! Ah, espera, quiz茨s[n]me lo deber胤a tomar m茨s en serio...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_11]
[s]Eh, un momento... Ya veo lo que[n]intentas hacer...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_12]
[s]Decir eso mientras me apuntas con[n]un arma me hace sentir como[n]si me fueras a secuestrar...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_13]
[s]Vale... No lo volver姻 a repetir.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_14]
[s]斡Ah! Si me muero, 斡har茨s llorar[n]a mi pobre madre![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_15]
[s]斡Ah! Si me muero, 斡mi padre[n]se desmayar茨 del disgusto![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_06_R_16]
[s]Mis padres son unos pesados,[n]pero no me molestan tanto[n]como que me disparen sin raz吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07]
[s]Uf, esto ya me est茨 aburriendo.[n][w][e]
[s]Si lo dejamos en que t雨 ganas,[n]夷podemos parar ya?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_07 top]
[s]Me siento mal.[e]
[s]No estoy de acuerdo.[e]
[s]Todo el mundo gana.[e]

[msg TalkMsg_GUY_CHAT_SQ_07_R]
[s]No te preocupes,[n]a m胤 no me importa.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_2]
[s]O sea, al fin y al cabo,[n]empez吋 como un malentendido...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_3]
[s]Sab胤a que eras un humano listo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_4]
[s]De verdad, 斡eso ha dolido mucho![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_5]
[s]C茨llate. Has ganado,[n]y es lo 雨nico que importa.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_6]
[s]斡Uf, qu姻 pesado![n]Has ganado. 夷Qu姻 m茨s da?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_7]
[s]No tienes que estar de acuerdo.[n]斡T雨 ganas![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_8]
[s]夷Qu姻 m茨s da? Lo que importa[n]es el resultado,[n]no los sentimientos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_9]
[s]Me da igual ganar,[n]corta el rollo ya...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_10]
[s]Eso es cierto. Supongo que da igual[n]qui姻n gane o qui姻n pierda...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_11]
[s]夷Y esto es como el premio de[n]consolaci吋n para los de primaria?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_12]
[s]夷Qu姻? 斡Eso no tiene ning雨n sentido![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_13]
[s]夷Qu姻 narices...? 夷No te basta[n]con haber ganado?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_14]
[s]Vale, has disparado.[n]夷Ya est茨s contento?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_15]
[s]Uf, no puedo quedarme[n]aqu胤 eternamente, 夷sabes?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_07_R_16]
[s]夷Dices que quieres m茨s[n]que una simple victoria o derrota?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08]
[s]Me he olvidado por completo[n]de responder mis mensajes. Espero[n]que no se enfaden...[n][w][e]
[s]夷Tienes muchos amigos?[n]夷Y no te molestan las cosas[n]que hacen a veces?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_08 top]
[s]A veces.[e]
[s]No.[e]
[s]No tengo amigos.[e]

[msg TalkMsg_GUY_CHAT_SQ_08_R]
[s]斡Por supuesto! 夷No es genial[n]tener amigos que te apoyan?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_2]
[s]S胤, claro. Entiendo perfectamente[n]c吋mo te sientes.[n]Ser popular es muy duro.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_3]
[s]Eh, un momento, 夷es que les hablas[n]a tus amigos as胤? Y luego dices[n]que los dem茨s no tienen coraz吋n...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_4]
[s]Claro, es un rollo tener[n]que salir a comer sola.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_5]
[s]夷En serio?[n]夷Le caes bien a la gente[n]aunque digas esas cosas?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_6]
[s]Pareces un santito.[n]Me est茨s poniendo de los nervios.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_7]
[s]夷En serio? Me tienes hasta la narices.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_8]
[s]斡Pues deber胤as juntarte conmigo![n]斡Podemos ser amigos![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_9]
[s]夷Qu姻? Bueno... Lo siento...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_10]
[s]Vaya, 斡no has dudado lo m茨s m胤nimo[n]cuando lo has dicho![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_11]
[s]Lo entiendo. Yo tampoco[n]tengo amigos de verdad.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_12]
[s]Supongo que los dem茨s humanos[n]no entienden tu encanto.[n]O, m茨s bien, la falta de este.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_13]
[s]夷Quieres que deje de hablar mal[n]de tus amigos?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_14]
[s]Oh, no estaba hablando mal[n]de tus amigos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_15]
[s]Uf, me molesta mucho[n]que te pongas a disparar[n]en vez de hablar conmigo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_08_R_16]
[s]Los amigos est茨n para aprovecharse[n]de ellos. Seguro que ellos[n]piensan lo mismo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09]
[s]夷Esto es solo un juego para ti?[n][w][e]
[s]Tienes suerte de que sea yo.[n]En el mundo real, no puedes[n]hacer estas cosas, 夷no?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_09 top]
[s]Correcto.[e]
[s]Elijo a mis objetivos a conciencia.[e]
[s]Lo digo en serio.[e]

[msg TalkMsg_GUY_CHAT_SQ_09_R]
[s]夷De verdad? Si vuelves a hacerlo,[n]te dejar姻 sin dientes.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_2]
[s]En el fondo, s姻[n]que no eres mal chico.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_3]
[s]斡Un paso en falso[n]y podr胤a haber muerto![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_4]
[s]Puede que sea un poco tarde[n]para que te des cuenta, pero...[n]斡Qu姻 le vamos a hacer![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_5]
[s]斡Eso es favoritismo![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_6]
[s]Para sobrevivir en este mundo,[n]hay que ser listo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_7]
[s]Uf, no s姻. Tu estrategia[n]me parece un poco floja.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_8]
[s]Bueno... Si me elegiste a m胤,[n]no estuviste muy acertado.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_9]
[s]Madre m胤a... No sabe distinguir[n]los videojuegos de la vida real...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_10]
[s]Entonces, cuanto m茨s te diviertas[n]en este mundo, mejor, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_11]
[s]斡Como si a m胤 me importase![n]斡Da igual! 斡Ya no me interesa![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_12]
[s]Espera, 夷lo dices en serio?[n]夷Eres idiota?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_13]
[s]Ah, me ha rozado...[n]Creo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_14]
[s]Has fallado. Se te da muy mal.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_15]
[s]Este lugar no es real,[n]as胤 que, si me quisieras disparar,[n]ya lo habr胤as hecho.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_09_R_16]
[s]Te resulta muy divertido hacer[n]cosas que a los dem茨s[n]no les gustan, 夷eh?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10]
[s]He estado pensando.[n]S姻 que es una tonter胤a que[n]me toque decirlo a m胤...[n][w][e]
[s]Est茨s tonteando conmigo, 夷no?[n]夷No te parece que[n]lo est茨s haciendo fatal?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_10 top]
[s]No tiene nada de malo.[e]
[s]夷Y qu姻 es lo correcto?[e]
[s]No te estoy tirando la ca隠a.[e]

[msg TalkMsg_GUY_CHAT_SQ_10_R]
[s]Ah... 夷Conque esto[n]pasa a veces?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_2]
[s]Eso parece. En fin,[n]no puedes brillar si haces[n]lo mismo que todo el mundo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_3]
[s]夷Qu姻? No, para nada.[n]Madre m胤a, mira que eres raro.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_4]
[s]夷Acaso soy un bicho raro?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_5]
[s]No s姻, yo no flirteo con chicos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_6]
[s]Eres t雨 quien est茨 ligando conmigo.[n]夷No es un poco tonto preguntarle a[n]quien le est茨s tirando los trastos?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_7]
[s]Ah, a lo mejor llevas raz吋n.[n]夷Acaso hay una forma correcta?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_8]
[s]斡Uf, pues para eso existe internet![n]斡B雨scalo![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_9]
[s]A decir verdad, ten胤a mis dudas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_10]
[s]Si no, es que en realidad[n]viniste a matarme, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_11]
[s]夷Y qu姻 hacemos aqu胤?[n]Quiero irme a casa.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_12]
[s]Uh, no cabe duda de que[n]me est茨s tirando la ca隠a.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_13]
[s]夷No?[n]Vaya, mira que soy idiota.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_14]
[s]Me da igual. De todas formas,[n]esto es una estupidez.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_15]
[s]Oye, a lo mejor no me estoy[n]enamorando de ti, pero eso no[n]significa que puedas dispararme.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_10_R_16]
[s]Con ese car茨cter, seguro que[n]no eres muy popular[n]entre las chicas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11]
[s]O sea, 夷la raz吋n por la que[n]estoy aqu胤 as胤 son los humanos?[n][w][e]
[s]Si eso es cierto, no creo[n]que haya motivos para matarme.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_11 top]
[s]Claro, tiene sentido.[e]
[s]Tienes raz吋n.[e]
[s]夷Y qui姻n es el enemigo?[e]

[msg TalkMsg_GUY_CHAT_SQ_11_R]
[s]Ah, 夷te has enfadado porque no[n]estoy de acuerdo contigo?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_2]
[s]Creer茨s que te est茨s haciendo[n]el duro, pero desde mi punto[n]de vista, 斡solo quieres matarme![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_3]
[s]A lo mejor es as胤 desde tu punto de[n]vista, pero desde el m胤o...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_4]
[s]夷Eh? Te refieres a que[n]toda experiencia nos[n]ense隠a algo, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_5]
[s]夷Verdad? 夷Y por qu姻 no podemos[n]llegar a un acuerdo?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_6]
[s]Si eso es lo que piensas,[n]斡demu姻stramelo con hechos![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_7]
[s]斡Ahora ya es un poquito tarde[n]para darse cuenta, idiota![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_8]
[s]Los humanos discut胤s[n]por cualquier tonter胤a.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_9]
[s]No me refiero a cosas complicadas[n]como esas. 斡Yo solo quiero vivir![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_10]
[s]夷Y por qu姻 te importa tanto?[n]Qu姻 pregunta tan est雨pida.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_11]
[s]Mmm...夷Humanos?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_12]
[s]No importa lo real que sea,[n]斡un enemigo es un enemigo![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_13]
[s]Conque me quieres matar de verdad.[n]Al menos tienes las cosas claras.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_14]
[s]Como ya he dicho,[n]no tiene sentido[n]que me mates.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_15]
[s]夷Te da miedo no saber[n]por qu姻 est茨s luchando?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_11_R_16]
[s]Vale, voy contigo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12]
[s]Ah, s胤... No me ba隠姻 ayer.[n][w][e]
[s]Oye, 夷c吋mo llevo el pelo?[n]夷Est茨 liso? 夷Est茨 bien?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_12 top]
[s]Es una monada.[e]
[s]Es m茨s raro que un perro verde.[e]
[s]夷Qu姻 m茨s da?[e]

[msg TalkMsg_GUY_CHAT_SQ_12_R]
[s]Cualquiera podr胤a decirlo...[n]O sea, es de sentido com雨n[n]decirle eso a una chica.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_2]
[s]Vaya, no se te da nada mal[n]regalar los o胤dos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_3]
[s]Bah, eso ya lo s姻. No tienes un[n]vocabulario muy extenso, 夷eh?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_4]
[s]斡Todo lo que hac胤as era decirme[n]lo que cre胤as que quer胤a o胤r![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_5]
[s]Bueno, 斡aunque sea verdad,[n]sigo teniendo mejor aspecto[n]que la mayor胤a![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_6]
[s]Lo s姻. Soy algo consciente[n]de m胤 misma, 夷sabes? [n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_7]
[s]夷De verdad? 夷Te importa matarme[n]en otro momento? Quiero llevar[n]el pelo bonito cuando suceda.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_8]
[s]夷Est茨s de co隠a? Es solo pelo,[n]no deber胤a importarte.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_9]
[s]斡Si te cargas a alguien con[n]el pelo mal, tendr茨s antecedentes![n]斡Te arrepentir茨s![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_10]
[s]As胤 que eres de los que niegan[n]todo lo que no tiene cabida[n]en su forma de ver el mundo, 夷eh?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_11]
[s]斡Eh, vamos! 斡Para una chica[n]como yo, el pelo es m茨s importante[n]que la vida![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_12]
[s]Ya, ya, pero seguro que te echas[n]un buen vistazo cuando te miras[n]en el espejo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_13]
[s]夷Intentas decir que eso no[n]importar茨 si la palmo? Qu姻 miedo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_14]
[s]斡Si las balas me rozan el pelo,[n]me lo quemar茨n![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_15]
[s]夷Dices que deber胤a centrarme[n]en el interior en vez de[n]preocuparme por mi aspecto?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_12_R_16]
[s]Mi pelo ser茨 raro,[n]pero mi personalidad[n]no se queda atr茨s.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13]
[s]Me estoy empezando a aburrir.[n]Supongo que seguir姻 y dejar姻[n]que me mates.[n][w][e]
[s]Pero antes, haz algo gracioso.[n]夷Qu姻 sabes hacer?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_13 top]
[s]Imitaciones.[e]
[s]Poner caretos divertidos.[e]
[s]Nada.[e]

[msg TalkMsg_GUY_CHAT_SQ_13_R]
[s]夷Qu姻? 夷Sabes imitar a la gente?[n]Tienes m茨s talento[n]del que esperaba.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_2]
[s]Ah, 斡tambi姻n s姻 imitar [n]a algunas personas famosas![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_3]
[s]Uy, no, gracias. A menos que seas[n]un c吋mico o algo as胤,[n]las imitaciones son est雨pidas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_4]
[s]Uy, vaya, 夷sabes hacer imitaciones?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_5]
[s]Ay, pues est茨s muy guapo...[n]夷Te agradan estas cosas?[n]Creo que me gusta esa parte de ti.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_6]
[s]夷Quiere decir eso que me ense隠ar茨s[n]lo que hay bajo tu m茨scara? [n]Ay, 斡d姻jame echar un vistazo![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_7]
[s]Pero 夷son divertidas?[n]Porque si no, dan verg鵜enza ajena.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_8]
[s]La gente que dice esa clase[n]de cosas es incapaz de poner[n]caras graciosas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_9]
[s]Uf, eres un tost吋n para ser humano.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_10]
[s]Bueno, supongo que con ese[n]modelito habr茨 risas para rato...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_11]
[s]Tienes miedo de no ser capaz de[n]hacer nada gracioso, 夷verdad?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_12]
[s]Bueno, supongo que es mejor[n]que hacer una tonter胤a, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_13]
[s]Anda, 夷esto es una ruleta rusa?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_14]
[s]Ah, 夷acaso te comportas como los[n]detectives de la tele?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_15]
[s]Si no quer胤as,[n]podr胤as haberlo dicho.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_13_R_16]
[s]夷Y qu姻 parte es la que me deber胤a[n]hacer gracia y tal?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14]
[s]Ah, s胤, he o胤do que las [n]famosas humanas tienen [n]que pasar muchas pruebas.[n][w][e]
[s]Pues yo creo que soy[n]mucho mejor, 夷no?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_14 top]
[s]T雨 s胤 que eres 雨nica.[e]
[s]La verdad es que no...[e]
[s]夷A qui姻n le importan las famosas?[e]

[msg TalkMsg_GUY_CHAT_SQ_14_R]
[s]斡夷Verdad?! [n]斡Y con mucha diferencia![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_2]
[s]A lo mejor me est茨s adulando pero,[n]teniendo en cuenta que nos parecemos,[n]tambi姻n te halagas a ti mismo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_3]
[s]Oye, 斡soy mucho m茨s que 雨nica![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_4]
[s]或郁nica位 es una palabra[n]de lo m茨s conveniente, 夷no?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_5]
[s]Deber胤as revisarte la vista.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_6]
[s]Bueno, ya sabes, cantan, bailan[n]y se ponen guapas. No puedo[n]competir contra ellas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_7]
[s]C茨llate, 斡夷qui姻n te crees que soy?![n]斡Soy mucho m茨s guapa [n]que muchas famosas![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_8]
[s]Ya veo. Vaya, las famosas [n]deben de estar ca隠吋n.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_9]
[s]夷En serio...? Eres de lo que no hay...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_10]
[s]Si le hablas a la gente de esta[n]forma, fijo que no tienes amigos.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_11]
[s]Supongo que m茨s vale mejorar y[n]centrarse en uno mismo que ser[n]el perrito faldero de los dem茨s.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_12]
[s]Ah, pasas de ellos porque sabes[n]que tampoco quieren juntarse[n]con un rarito como t雨.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_13]
[s]夷Qu姻? Ah, debes ser un gran fan[n]del mundo del famoseo.[n]Pues lo siento mucho.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_14]
[s]斡Hala! Ya lo entiendo. Eres un fan[n]ac姻rrimo de esos,[n]夷a que s胤?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_15]
[s]Ya lo pillo. 夷Me est茨s diciendo[n]que no deber胤a ser tan arrogante?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_14_R_16]
[s]夷Qu姻? 夷Est茨s diciendo que[n]yo no soy tan buena?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15]
[s]Ya, mucha gente me ha dicho[n]雨ltimamente que deber胤a crecer[n]y actuar con m茨s madurez y tal.[n][w][e]
[s]夷Es que no lo hago ya? O sea, 夷d吋nde[n]est茨 el medidor de madurez[n]o lo que sea?[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_15 top]
[s]Cuando eres adulto.[e]
[s]Pagar el alquiler.[e]
[s]Cuestionarse la madurez.[e]

[msg TalkMsg_GUY_CHAT_SQ_15_R]
[s]No s姻, hay muchos adultos que se[n]comportan como cr胤os cuando[n]empiezan a empinar el codo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_2]
[s]Vale, pero 夷que te convierte[n]en adulto?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_3]
[s]Vamos, que no sabes qu姻 responder.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_4]
[s]Ha sido una respuesta simplona,[n]pero gracias de todas formas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_5]
[s]斡Yo a veces pienso en c吋mo[n]ser胤a vivir sola! 斡Molar胤a mucho![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_6]
[s]夷Eh? Ni de co隠a. 夷El alquiler [n]hay que pagarlo?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_7]
[s]夷As胤 que no se puede vivir de[n]los padres toda la vida?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_8]
[s]Buah, qu姻 mal...[n]Supongo que tendr姻 que[n]ser m茨s dura conmigo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_9]
[s]夷Eh? Pero eso estoy haciendo...[n]Ah, vaya, 斡entonces soy una adulta![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_10]
[s]Ya sabes, dices cosas [n]de persona madura.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_11]
[s]No entiendo lo que dices.[n]夷Es un consejo o qu姻?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_12]
[s]夷Y de d吋nde te sacas [n]esa respuesta? [n]Qu姻 cursi. Me da grimita.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_13]
[s]Bueno, yo soy la que est茨 perdida.[n]Supongo que ser adulta o no[n]no importa mucho ahora.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_14]
[s]Ah, supongo que no quieres hablar[n]del tema. No pasa nada.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_15]
[s]Supongo que tendr姻 que esperar y[n]ser una adulta cuando llegue[n]el momento, aunque no quiera.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_15_R_16]
[s]Solo s姻 una cosa:[n]madurar significa conectar[n]de verdad con las personas.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16]
[s]Uf, si esto fuera una peli, ahora[n]vendr胤a un pr胤ncipe apuesto[n]y me salvar胤a.[n][w][e]
[s]Bueno, pues aqu胤 sigo.[n]S胤 que me est茨[n]haciendo esperar, s胤.[n][w][e]

[sel TalkSel_GUY_CHAT_SQ_16 top]
[s]La vida no es como en los cuentos.[e]
[s]T雨 espera un poco m茨s.[e]
[s]Lo tienes delante.[e]

[msg TalkMsg_GUY_CHAT_SQ_16_R]
[s]Oye, 斡que no digas eso![n]斡Es culpa tuya que me est姻 pasando[n]esto a m胤![n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_2]
[s]Ahora que lo pienso, la gente[n]espera demasiado de los dem茨s.[n]Qu姻 panda de mimados.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_3]
[s]Bueno, no tendr胤a problemas[n]si tu fueras mi pr胤ncipe.[n]夷C吋mo lo ves?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_4]
[s]Tienes toda la raz吋n. Tengo que[n]hacer algo por m胤 misma. No puedo[n]pensar en pr胤ncipes.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_5]
[s]夷Eh? Ah... Vale.[n]夷No tienes nada mejor[n]que hacer o qu姻?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_6]
[s]Bueno, no hace falta.[n]Cuanto m茨s tarde en aparecer,[n]m茨s triste me pondr姻.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_7]
[s]夷Te est茨s riendo de m胤 o qu姻?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_8]
[s]Me lo dices como si supieras[n]que no va a venir.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_9]
[s]夷Eh? 夷D吋nde? No le veo.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_10]
[s]斡夷T雨?! Bueno, supongo que no puede[n]estar tan mal...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_11]
[s]夷No se supone que los pr胤ncipes[n]visten bien y tal?[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_12]
[s]No tomes notas sobre eso...[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_13]
[s]Anda, 夷intentas llamar la atenci吋n[n]del pr胤ncipe por m胤?[n]Qu姻 detalle por tu parte.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_14]
[s]斡Tienes raz吋n![n]No deber胤a enfadarme con los pr胤ncipes[n]imaginarios por no aparecer. [n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_15]
[s]Uy, est茨s celoso porque me he[n]puesto a hablar de[n]pr胤ncipes buenorros.[n][w][e]

[msg TalkMsg_GUY_CHAT_SQ_16_R_16]
[s]斡Bah! No tiene sentido esperar a[n]ning雨n pr胤ncipe si este loco puede[n]matarme en cualquier momento.[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND]
[s](このページはカット予定)ねー、おっかないもの向けないでよ...[n]どーしたら許してくれんの?[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_2]
[s](このページはカット予定)...ホンット、今日運勢サイアク。[n]で、何? 何か欲しいわけ?[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_3]
[s](このページはカット予定)銃とかサイアクだし。[n]...何か欲しいんでしょ? 早く言いなよ。[n][w][e]

[msg TalkMsg_GUY_NEGO_SURREND_4]
[s](このページはカット予定)ねえ、向けんなってソレ。マジゴメンって。[n]もー...どーすりゃいーの?[n][w][e]

[sel TalkSel_GUY_NEGO_SURREND top]
[s]Te quiero a ti.[e]
[s]Dame dinero.[e]
[s]Quiero un objeto raro.[e]
[s]Quiero informaci吋n.[e]
[s]Reduce el nivel de seguridad.[e]

[msg TalkMsg_GUY_NEGO_FIFTYFI]
[s]Vaya con las travesuras...[n]Quiero unos [var 0] yenes, por cierto. [n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_2]
[s]Ni de co隠a. Si esto sale a la luz,[n]me meter姻 en un buen l胤o.[n]Uf, ojal茨 tuvieras [f 2 5 3 9999 3].[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_3]
[s]Me siento muy d姻bil...[n]Me lo pensar姻 si me dejas que[n]absorba un poco de tu fuerza vital.[n][w][e]

[msg TalkMsg_GUY_NEGO_FIFTYFI_4]
[s]Ay, pero no es justo para[n]mis amigos, 夷no? D姻jame absorber[n]unos cuantos PE y ya veremos.[n][w][e]

[sel TalkSel_GUY_NEGO_FIFTYFI top]
[s]Vale, te lo dar姻.[e]
[s]No puedo darte lo que pides.[e]

[msg TalkMsg_GUY_NEGO_REQUIRE]
[s]斡夷En serio me tiras la ca隠a[n]en un d胤a tan caluroso como hoy?![n][w][e]
[s]Mmm, entonces estar茨s[n]dispuesto a traerme[n][f 2 5 3 9999 4], 夷no?[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_2]
[s]*tos* Ay, odio resfriarme.[n]Uf, me est茨n dando escalofr胤os.[n][w][e]
[s]夷Eres mi caballero[n]de brillante armadura,[n]que me trae [f 2 5 3 9999 4]?[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_3]
[s]Madre m胤a, 夷en serio? 夷Quieres[n]hablar conmigo ahora mismo?[n][w][e]
[s]Me escuecen un mont吋n los ojos[n]por culpa del polen.[n]夷No tendr茨s [f 2 5 3 9999 4]?[n][w][e]

[msg TalkMsg_GUY_NEGO_REQUIRE_4]
[s]Espera. 夷Me est茨s pidiendo que les[n]mienta a las dem茨s sombras?[n][w][e]
[s]De eso nada. Si se enteran,[n]me matar茨n. Bueno, me lo pensar姻[n]si me das [f 2 5 3 9999 3].[n][w][e]

[sel TalkSel_GUY_NEGO_REQUIRE top]
[s]Entr姻galo[e]
[s]Qu姻datelo[e]

[msg TalkMsg_GUY_NEGO_PAYFOR_]
[s]Toma, estos [var 0] yenes son para ti.[n]Mmm, ahora tengo que encontrar[n]un trabajo en el que paguen bien.[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__2]
[s]Como soy buena gente,[n]te voy a ayudar. Toma, [var 0] yenes.[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__3]
[s]Este es mi favorito,[n]as胤 que cu胤dalo bien.[n]Ten, [f 2 5 3 9999 1].[n][w][e]

[msg TalkMsg_GUY_NEGO_PAYFOR__4]
[s]Te voy a dar una cosa que[n]te va a hacer tan feliz[n]que vas a llorar. Ten, [f 2 5 3 9999 1].[n][w][e]

[sel TalkSel_GUY_NEGO_PAYFOR top]
[s]Me lo quedo.[e]
[s]Eso no es lo mejor que tienes.[e]

[msg TalkMsg_GUY_NEGO_Re_ACCE]
[s]Ah, eres uno de esos[n]humanos despiadados. Pues vale.[n][w][e]

[msg TalkMsg_GUY_NEGO_Re_ACCE_2]
[s]S胤胤胤, vaaale. [n][w][e]

[msg TalkMsg_GUY_NEGO_Re_ACCE_3 [Ryuji]]

[msg TalkMsg_GUY_RESULT_GET_P]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_2]
[s]斡Pero si ya tienes [clr 1][var 2][clr 27]![n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_3]
[s]斡Oye, de eso nada! 斡Eres demasiado[n]d姻bil! Vete a entrenar, 夷vale?[n]Te dar姻 [f 2 5 3 9999 1].[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_M]
[s]Vale, toma [var 0] yenes.[n]夷Contento?[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_I]
[s]Vale, ten,[n][f 2 5 3 9999 1].[n]Con eso basta, 夷no?[n][w][e]

[msg TalkMsg_GUY_RESULT_GET_S]
[s]斡Es un secreto que solo[n]sabemos nosotros dos! 夷A que mola?[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY]
[s]斡Oye! 斡No tengo tiempo[n]para gente tan pat姻tica como[n]vosotros![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_2]
[s]斡Si tanto lo quieres,[n]te lo dar姻! [n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_3]
[s]Ostras, 夷todav胤a no es suficiente?[n]夷No crees que me est茨s[n]pidiendo demasiado?[n][w][e]
[s]斡Voy a preguntarles[n]a unos amigos sobre el tema![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_4]
[s]斡No puedo seguir![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_5]
[s]Oye, por ah胤[n]brilla algo...[n][w][e]
[s]斡Madre m胤a! 斡Es precioso![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_6]
[s]斡No, espera! 斡Nooo! S姻 que ya he[n]tenido el picoteo de medianoche,[n]pero este es el de despu姻s...[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_7]
[s]E-eh... 斡No te acerques [n]m茨s! En serio, [n]斡al姻jate de m胤, asqueroso![n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_8]
[s]...[n][w][e]

[msg TalkMsg_GUY_RESULT_ENEMY_9]
[s]夷Eh? 斡夷Qu姻 quieres?![n]No s姻 por qu姻, pero [n]斡estoy hasta la coronilla![n][w][e]
[s]Igual me he pasado...[n]Lo siento. Si quieres hablar,[n]adelante.[n][w][e]

[msg TalkMsg_RESULT_GET_SECRE]
[s]夷Qu姻? 夷Ya lo sab胤as? 斡Hala, seguro[n]que te lo ha chivado un topo![n]Bueno, pues toma esto.[n][w][e]

[msg TalkMsg_SURRENDER_FROM_C]
[s]Qu姻 fuerte, no me creo[n]que haya conocido a alguien[n]a quien no pueda vencer...[n][w][e]
[s]Ah, bueno, de todos modos[n]no se me da bien pelear.[n]Se me da mejor ser guapa.[n][w][e]

[msg TalkMsg_SUCCESS_SKIMMING]
[s]夷Quer胤as esto?[n]No le quitas los ojos de encima.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_SHO]
[s]Uh, uh...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_SLE]
[s]Zzz...[n][w][e]

[msg TalkMsg_RESULT_ENEMY_FLA]
[s]斡Ah! 斡Quema, quema![n]斡Esto no mola![n][w][e]
[s]Espera, no es tan malo [n]como pensaba. Lo siento. [n]Si quieres hablar, adelante.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_VER]
[s]Ay, qu姻 mareo... Mira,[n]ahora no puedo escucharte...[n][w][e]
[s]Espera, no es tan malo [n]como pensaba. Lo siento. [n]Si quieres hablar, adelante.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_FOR]
[s]Mmm, parece que se me[n]olvida algo importante.[n][w][e]
[s]Bueno, 斡ya da igual![n]Lo siento. [n]Si quieres hablar, adelante.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_DES]
[s]Vivir no tiene nada [n]de divertido, la verdad... [n]Oye, di algo...[n][w][e]
[s]Pero 夷est茨s interesado en [n]m胤 o qu姻? Si quieres [n]hablar, adelante.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_BRA]
[s]Anda, 夷qu姻 es esto?[n]Hay algo que brilla...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH]
[s]斡Entonces tambi姻n puedo brillar![n][w][e]
[s]斡Mira! Brillamos juntos... [n]斡No, espera! 斡Hablar contigo [n]me ha recordado algo![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_2]
[s]Ah, entonces tambi姻n[n]puedo brillar...[n][w][e]
[s]斡Un momento! 斡Uf, con[n]el brillo estar胤a horrible![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_3]
[s]斡Entonces tambi姻n puedo brillar![n][w][e]
[s]Anda, toma. Toma esto.[n]Gracias por dec胤rmelo.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_4]
[s]斡Entonces tambi姻n puedo brillar![n][w][e]
[s]斡Un momento! 斡Uf, con[n]el brillo estar胤a horrible![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_5]
[s]Ah, entonces tambi姻n[n]puedo brillar... Anda, toma. Toma esto.[n]Gracias por dec胤rmelo.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_6]
[s]斡Entonces tambi姻n puedo brillar![n][w][e]
[s]斡Un momento! 斡Uf, con[n]el brillo estar胤a horrible![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_7]
[s]Ah, as胤 que tengo que hacer eso...[n]Creo que... lo entiendo. Hala.[n]Toma, esto es para ti.[n][w][e]

[msg TalkMsg_CONTACT_11]
[s]夷De verdad intentas[n]desafiar al rey Kamoshida?[n]夷Es que eres imb姻cil?[n][w][e]

[msg TalkMsg_CONTACT_12]
[s]夷De verdad intentas desafiar[n]al se隠or Madarame?[n]夷Es que eres imb姻cil?[n][w][e]

[msg TalkMsg_CONTACT_13]
[s]夷De verdad intentas desafiar[n]al se隠or Kaneshiro?[n]夷Es que eres imb姻cil?[n][w][e]

[msg TalkMsg_CONTACT_14]
[s]夷De verdad intentas desafiar[n]a la reina Futaba?[n]夷Es que eres imb姻cil?[n][w][e]

[msg TalkMsg_CONTACT_15]
[s]夷De verdad intentas desafiar[n]al se隠or Okumura?[n]夷Es que eres imb姻cil?[n][w][e]

[msg TalkMsg_CONTACT_16]
[s]夷De verdad intentas desafiar[n]a la se隠ora Niijima?[n]夷Es que eres imb姻cil?[n][w][e]

[msg TalkMsg_CONTACT_17]
[s]夷De verdad intentas desafiar[n]al se隠or Akechi?[n]夷Es que eres imb姻cil?[n][w][e]

[msg TalkMsg_CONTACT_18]
[s]夷De verdad intentas desafiar[n]al se隠or Shido?[n]夷Es que eres imb姻cil?[n][w][e]

[msg TalkMsg_CONTACT_19]
[s]夷De verdad intentas desafiara Su Excelencia?[n]夷Es que eres imb姻cil?[n][w][e]

[msg TalkMsg_CONTACT_10]
[s]夷De verdad intentas desafiar[n]al jefe secreto?[n]夷Es que eres imb姻cil?[n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS]
[s]斡Ayyy! Qu姻 mala pata tengo...[n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS_2]
[s]斡Oye, espera! 斡No dispares![n][w][e]

[msg TalkMsg_CONTACT_MEMENTOS_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_GREET_POSSESSING]
[s][clr 1][var 2][clr 27] est茨 dentro de ti.[n]Genial, os estar姻 animando.[n][w][e]

[msg TalkMsg_NEGO_POSSESSING_]
[s]Ah, 夷quer胤as dinero?[n]Bueno, espero que con esto valga.[n][w][e]

[msg TalkMsg_NEGO_POSSESSING__2]
[s]Quieres un regalo, 夷eh?[n]Vale, 夷qu姻 te parece esto?[n][w][e]

[msg TalkMsg_GREET_POSSESSED]
[s]Oh, cu茨nto tiempo.[n]Vaya, 夷cu茨nto hace[n]que nos separamos?[n][w][e]
[s]Supongo que los corazones humanos[n]cambian con facilidad...[n][w][e]

[msg TalkMsg_NEGO_POSSESSED]
[s]Supongo que no sirve de nada[n]pensar en ello. Al fin[n]y al cabo, el pasado, pasado est茨.[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_M]
[s]Quer胤as dinero, 夷no?[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_I]
[s]夷Quer胤as un regalo, verdad?[n]夷Qu姻 tal esto?[n][w][e]

[msg TalkMsg_GREET_POSSESSED_]
[s]Ah, 夷te est茨s volviendo a enamorar[n]de un antiguo amor? 斡Je, je, je...![n][w][e]
[s]夷Por qu姻 no hablamos un rato?[n][w][e]

[msg TalkMsg_TALK_POSSESSED_B]
[s]Qu姻 raro...[n]Ni que no nos conoci姻ramos.[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B]
[s]Supongo...[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B_2]
[s]El dinero deber胤a ser [n]la clave, 夷no?[n][w][e]

[msg TalkMsg_NEGO_POSSESSED_B_3]
[s]夷Quer胤as un obsequio? Aqu胤 tienes.[n][w][e]

[msg TalkMsg_FIRST_CONTACT]
[s]夷Quieres hablar? 斡Olv胤dalo![n]No le pienso prestar mi poder[n]a alguien tan pat姻tico.[n][w][e]

[msg TalkMsg_PRE_QUESTION]
[s]Espera, 夷qu姻 tipo[n]de personalidad tienes?[n]夷Podemos hablar?[n][w][e]

[msg TalkMsg_PRE_QUESTION_ACQ]
[s]斡Yuju![n][w][e]

[msg TalkMsg_PRE_QUESTION_DEN]
[s]斡Uf, qu姻 cruel! Yo soy igual, [n]pero... 斡Un momento! 斡Hablar [n]contigo me ha recordado algo![n][w][e]

[msg TalkMsg_TALK_TECH_ITEM]
[s]斡Me juego lo que sea[n]a que piensas que soy tonta![n]斡Qu姻 mal se te da esto![n][w][e]

[msg TalkMsg_TALK_TECH_PERSON]
[s]夷A qu姻 viene tanta ch茨chara?[n]斡A esto podemos jugar los dos![n]斡Espera! 斡Acabo de recordar algo![n][w][e]

[msg TalkMsg_SETTLE_DOWN]
[s]斡E-era broma! 斡Ya sabes[n]c吋mo son las chicas! Ah, s胤,[n]tengo que preguntarte una cosa...[n][w][e]

[msg TalkMsg_RESULT_SHOT_1]
[s]斡Nooooooo! 斡No permitir姻[n]que me mateeeees![n][w][e]

[msg TalkMsg_RESULT_SHOT_2]
[s]斡夷Qu姻?! 斡Qu姻 miedo de t胤o![n][w][e]
[s]斡Que alguien me salveeee![n][w][e]

[msg TalkMsg_RESULT_SHOT_3]
[s]斡Aaaah! 斡Tengo que escapar![n][w][e]

[msg TalkMsg_RESULT_SHOT_4]
[s]Se-se隠or ladr吋n..., te doy[n]esto, pero 斡d姻jame marchar![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_2]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_3]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_4]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_5]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_6]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_7]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_8]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_9]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_10]
[s]Yo no pertenezco[n]a este lugar. Viv胤a en el mar[n]de las almas humanas.[n][w][e]
[s]Soy [clr 1][var 2][clr 27].[n]Al fin y al cabo, soy t雨, as胤 que[n]斡espero que nos llevemos bien![n][w][e]

[msg TalkMsg_ED_bye_D01_01]
[s]Bueno, yo me marcho. Pero no[n]lo olvides, este es el castillo[n]del rey Kamoshida.[n][w][e]

[msg TalkMsg_ED_bye_D01_02]
[s]Cierto, deber胤a advertirte...[n]Nunca derrotar茨s al rey Kamoshida.[n][w][e]

[msg TalkMsg_ED_bye_D01_03]
[s]Eh, escucha. Debes saber que a雨n[n]no has visto el verdadero poder[n]del rey Kamoshida.[n][w][e]

[msg TalkMsg_ED_bye_D02_01]
[s]Bueno, yo me marcho. Pero no[n]lo olvides, esta es la exhibici吋n[n]del se隠or Madarame.[n][w][e]

[msg TalkMsg_ED_bye_D02_02]
[s]Cierto, deber胤a advertirte...[n]Nunca derrotar茨s al se隠or Madarame.[n][w][e]

[msg TalkMsg_ED_bye_D02_03]
[s]Eh, escucha. Debes saber que a雨n[n]no has visto el verdadero poder[n]del se隠or Madarame.[n][w][e]

[msg TalkMsg_ED_bye_D03_01]
[s]Bueno, yo me marcho. Pero no[n]lo olvides, este es el banco[n]del se隠or Kaneshiro.[n][w][e]

[msg TalkMsg_ED_bye_D03_02]
[s]Cierto, deber胤a advertirte...[n]Nunca derrotar茨s[n]al se隠or Kaneshiro.[n][w][e]

[msg TalkMsg_ED_bye_D03_03]
[s]Eh, escucha. Debes saber que a雨n[n]no has visto el verdadero poder[n]del se隠or Kaneshiro.[n][w][e]

[msg TalkMsg_ED_bye_D04_01]
[s]Bueno, yo me marcho.[n]Pero me gustar胤a que dejaras[n]en paz a la reina Futaba.[n][w][e]

[msg TalkMsg_ED_bye_D04_02]
[s]Cierto, deber胤a advertirte...[n]Nunca llegar茨s[n]hasta la reina Futaba.[n][w][e]

[msg TalkMsg_ED_bye_D04_03]
[s]Eh, escucha. Debes saber[n]que no es buena idea intentar[n]conocer a la reina Futaba.[n][w][e]

[msg TalkMsg_ED_bye_D05_01]
[s]Bueno, yo me marcho. Pero no lo[n]olvides, este es el establecimiento[n]del se隠or Okumura.[n][w][e]

[msg TalkMsg_ED_bye_D05_02]
[s]Cierto, deber胤a advertirte...[n]Nunca derrotar茨s al se隠or Okumura.[n][w][e]

[msg TalkMsg_ED_bye_D05_03]
[s]Eh, escucha. Debes saber que a雨n[n]no has visto el verdadero poder[n]del se隠or Okumura.[n][w][e]

[msg TalkMsg_ED_bye_D06_01]
[s]Bueno, yo me marcho. Pero no[n]lo olvides, este es el casino[n]de la se隠ora Niijima.[n][w][e]

[msg TalkMsg_ED_bye_D06_02]
[s]Cierto, deber胤a advertirte...[n]Nunca derrotar茨s[n]a la se隠ora Niijima.[n][w][e]

[msg TalkMsg_ED_bye_D06_03]
[s]Eh, escucha. Debes saber que a雨n[n]no has visto el verdadero poder[n]de la se隠ora Niijima.[n][w][e]

[msg TalkMsg_ED_bye_D07_01]
[s]Bueno, yo me marcho. Pero no[n]lo olvides, este es el castillo[n]del se隠or Akechi.[n][w][e]

[msg TalkMsg_ED_bye_D07_02]
[s]Cierto, deber胤a advertirte...[n]Nunca derrotar茨s al se隠or Akechi.[n][w][e]

[msg TalkMsg_ED_bye_D07_03]
[s]Eh, escucha. Debes saber que a雨n[n]no has visto el verdadero poder[n]del se隠or Akechi.[n][w][e]

[msg TalkMsg_ED_bye_D08_01]
[s]Bueno, yo me marcho. Pero no[n]lo olvides, este es el crucero[n]del se隠or Shido.[n][w][e]

[msg TalkMsg_ED_bye_D08_02]
[s]Cierto, deber胤a advertirte...[n]Nunca derrotar茨s al se隠or Shido.[n][w][e]

[msg TalkMsg_ED_bye_D08_03]
[s]Eh, escucha. Debes saber que a雨n[n]no has visto el verdadero poder[n]del se隠or Shido.[n][w][e]

[msg TalkMsg_ED_bye_D09_01]
[s]Bueno, yo me marcho. Pero no[n]lo olvides, este es el territorio[n]de Su Excelencia.[n][w][e]

[msg TalkMsg_ED_bye_D09_02]
[s]Cierto, deber胤a advertirte...[n]Nunca derrotar茨s a Su Excelencia.[n][w][e]

[msg TalkMsg_ED_bye_D09_03]
[s]Eh, escucha. Debes saber que a雨n[n]no has visto el verdadero poder[n]de Su Excelencia.[n][w][e]

[msg TalkMsg_ED_bye_D10_01]
[s]Bueno, yo me marcho. Pero no[n]lo olvides, este es el territorio[n]del jefe secreto.[n][w][e]

[msg TalkMsg_ED_bye_D10_02]
[s]Cierto, deber胤a advertirte...[n]Nunca derrotar茨s al jefe secreto.[n][w][e]

[msg TalkMsg_ED_bye_D10_03]
[s]Eh, escucha. Debes saber que a雨n[n]no has visto el verdadero poder[n]del jefe secreto.[n][w][e]

[msg TalkMsg_CONTACT_11_1]
[s]斡E-espera! 斡No quiero morir a雨n![n][w][e]

[msg TalkMsg_CONTACT_11_2]
[s]斡S茨lvame, por favor![n]No se lo contar姻 al rey Kamoshida...[n][w][e]

[msg TalkMsg_CONTACT_11_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_CONTACT_12_1]
[s]斡E-espera! 斡No quiero morir a雨n![n][w][e]

[msg TalkMsg_CONTACT_12_2]
[s]斡S茨lvame, por favor![n]No se lo contar姻 al se隠or Madarame...[n][w][e]

[msg TalkMsg_CONTACT_12_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_CONTACT_13_1]
[s]斡E-espera! 斡No quiero morir a雨n![n][w][e]

[msg TalkMsg_CONTACT_13_2]
[s]斡S茨lvame, por favor![n]No se lo contar姻 al se隠or Kaneshiro...[n][w][e]

[msg TalkMsg_CONTACT_13_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_CONTACT_14_1]
[s]斡E-espera! 斡No quiero morir a雨n![n][w][e]

[msg TalkMsg_CONTACT_14_2]
[s]斡S茨lvame, por favor![n]No se lo contar姻 a la reina Futaba...[n][w][e]

[msg TalkMsg_CONTACT_14_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_CONTACT_15_1]
[s]斡E-espera! 斡No quiero morir a雨n![n][w][e]

[msg TalkMsg_CONTACT_15_2]
[s]斡S茨lvame, por favor![n]No se lo contar姻 al se隠or Okumura...[n][w][e]

[msg TalkMsg_CONTACT_15_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_CONTACT_16_1]
[s]斡E-espera! 斡No quiero morir a雨n![n][w][e]

[msg TalkMsg_CONTACT_16_2]
[s]斡S茨lvame, por favor![n]No se lo contar姻[n]a la se隠ora Niijima...[n][w][e]

[msg TalkMsg_CONTACT_16_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_CONTACT_17_1]
[s]斡E-espera! 斡No quiero morir a雨n![n][w][e]

[msg TalkMsg_CONTACT_17_2]
[s]斡S茨lvame, por favor![n]No se lo contar姻 al se隠or Akechi...[n][w][e]

[msg TalkMsg_CONTACT_17_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_CONTACT_18_1]
[s]斡E-espera! 斡No quiero morir a雨n![n][w][e]

[msg TalkMsg_CONTACT_18_2]
[s]斡S茨lvame, por favor![n]No se lo contar姻 al se隠or Shido...[n][w][e]

[msg TalkMsg_CONTACT_18_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_CONTACT_19_1]
[s]斡E-espera! 斡No quiero morir a雨n![n][w][e]

[msg TalkMsg_CONTACT_19_2]
[s]斡S茨lvame, por favor![n]No se lo contar姻 a Su Excelencia...[n][w][e]

[msg TalkMsg_CONTACT_19_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_CONTACT_10_1]
[s]斡E-espera! 斡No quiero morir a雨n![n][w][e]

[msg TalkMsg_CONTACT_10_2]
[s]斡S茨lvame, por favor![n]No se lo contar姻 al jefe secreto...[n][w][e]

[msg TalkMsg_CONTACT_10_3]
[s]De verdad, ya he dicho[n]que lo siento. Uf... 夷Qu姻 hago?[n][w][e]

[msg TalkMsg_FQ_REACT_GOODMOO]
[s](このページはカット予定)...ふーん、[n]アンタ案外ノリいいね![n][w][e]

[msg TalkMsg_FQ_REACT_INTERES]
[s](このページはカット予定)...そーゆーノリか。[n]ガゼン興味わいてきた![n][w][e]

[msg TalkMsg_FQ_REACT_DISPLEA]
[s](このページはカット予定)...アンタ、ガチでノリ悪いね。[n][w][e]

[msg TalkMsg_FQ_REACT_ANGER]
[s](このページはカット予定)...そーゆー系?[n]アンタ、最低クラスだね。[n][w][e]

[msg TalkMsg_FQ_REACT_BROKEDO]
[s]Vaaaaya, qu姻 cruel.[n][w][e]

[msg TalkMsg_HAVE_NO_SECRET]
[s]Lo siento, pero no s姻 nada[n]que pueda ayudarte.[n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF]
[s]斡Venga, dispara![n]斡No tenemos nada de qu姻 hablar![n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF_2]
[s]夷Qu姻? 斡No voy a permitir[n]que me manipules![n][w][e]

[msg TalkMsg_RESULT_ENEMY_REF_3]
[s]夷Eh? No puedo hablar contigo.[n]夷Es que eres idiota?[n][w][e]

[msg TalkMsg_SHOOT_REACTION01]
[s]斡N-no mola nada disparar[n]a una chica sin venir a cuento![n]Aunque yo soy igual, pero...[n][w][e]
[s]Espera... 斡Mierda![n]斡Hablar contigo[n]me ha recordado algo![n][w][e]

[msg TalkMsg_SHOOT_REACTION02]
[s]斡Hala! 斡Ten cuidado con la pistola![n]No me van mucho esas cosas...[n][w][e]
[s]Espera... 斡Mierda![n]斡Hablar contigo[n]me ha recordado algo![n][w][e]

[msg TalkMsg_SHOOT_REACTION03]
[s]E-es decir, entiendo que llevarpistola te haga sentir poderoso,[n]pero aun as胤...[n][w][e]
[s]Espera... 斡Mierda![n]斡Hablar contigo[n]me ha recordado algo![n][w][e]

[msg TalkMsg_SHOOT_REACTION04]
[s]斡T-tienes que aprender a controlar[n]la ira! Eres exactamente igual[n]de malo que yo, creo.[n][w][e]
[s]Espera... 斡Mierda![n]斡Hablar contigo[n]me ha recordado algo![n][w][e]

[msg TalkMsg_PLEAD_SKIMMING]
[s]夷Qu姻 es lo que quieres de m胤?[n]斡Menudo bicho raro! Si tienes [n]algo que decirme, su姻ltalo.[n][w][e]

[msg TalkMsg_PLEAD_NO_SKIMMIN]
[s]斡Lo siento! 斡Por favor, quiero vivir![n][w][e]

[msg TalkMsg_ACCEPT_ALERT_DOW]
[s]De acuerdo, les dir姻 a todos[n]que no pasa nada.[n][w][e]

[msg TalkMsg_NO_REQUIREMENT]
[s]Espera, entonces lo que me est茨s[n]diciendo es que... 斡no tienes![n][w][e]

[msg TalkMsg_RESULT_SQ_ITEM1]
[s]Toma esto en mi lugar.[n][w][e]

[msg TalkMsg_RESULT_SQ_ITEM2]
[s]Toma, te dar姻 esto[n]como premio. Ya sabes,[n]por tu 或esfuerzo位.[n][w][e]

[msg TalkMsg_RESULT_SQ_PERSON]
[s]Me recuerdas un poco a m胤... [n]斡Un momento! 斡Hablar contigo [n]me ha recordado algo![n][w][e]

[msg TalkMsg_RESULT_SQ_PERSON_2]
[s]Nos parecemos bastante... [n]斡Un momento! 斡Hablar contigo [n]me ha recordado algo![n][w][e]

[msg TalkMsg_RESULT_SQ_PAYFOR]
[s]Ya te voy entendiendo...[n]Lo siento, no puedo[n]hacer m茨s. [n][w][e]

[msg TalkMsg_RESULT_SQ_PAYFOR_2]
[s]Mmm, as胤 que eres de esa clase[n]de personas. No[n]esperaba que fueses as胤.[n][w][e]
[s]Me lo he pasado bien hablando[n]contigo, as胤 que te dar姻 esto.[n][w][e]

[msg TalkMsg_RESULT_SQ_AGAIN1]
[s]Un momento. Al final,[n]夷qu姻 es lo que quer胤as decir?[n][w][e]
[s]D胤melo de nuevo.[n][w][e]

[msg TalkMsg_RESULT_SQ_AGAIN2]
[s]Un momento. Al final,[n]夷qu姻 es lo que quer胤as decir?[n][w][e]
[s]D胤melo de nuevo.[n][w][e]

[msg TalkMsg_RESULT_SQ_CARD1]
[s]Te dar姻 esto, pero d姻jame marchar.[n][w][e]

[msg TalkMsg_RESULT_SQ_CARD2]
[s]Te dar姻 esto. [n][w][e]

[msg TalkMsg_RESULT_SQ_COUNTE]
[s]Ah, eres de esos.[n]斡Pues no me subestimes![n][w][e]

[msg TalkMsg_RESULT_SQ_COUNTE_2]
[s]Ya lo entiendo. 斡Solo[n]quieres que nos matemos![n][w][e]

[msg TalkMsg_RESULT_SQ_ALERT1]
[s]Uf, qu姻 sospechoso.[n]Ser茨 mejor que llame a mis[n]amigos para que hablemos del tema.[n][w][e]

[msg TalkMsg_RESULT_SQ_ALERT2]
[s]斡Uf, me pones de los nervios![n]Voy a tener que llamar a alguien.[n][w][e]

[msg TalkMsg_RESULT_SQ_INFO1]
[s]Veeenga, vaaale. S姻[n]algo que podr胤a[n]ayudarte, as胤 que para.[n][w][e]

[msg TalkMsg_RESULT_SQ_INFO2]
[s]Te contar姻 una cosa muy[n]interesante, pero d姻jame marchar...[n][w][e]

[msg TalkMsg_RESULT_SQ_MONEY1]
[s]Al menos, quiero que tengas esto.[n][w][e]

[msg TalkMsg_RESULT_SQ_MONEY2]
[s]Te dar姻 esto,[n]pero deja que me vaya.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_8]
[s]Ah, as胤 que tengo que hacer eso...[n]Creo que... lo entiendo. Hala,[n]pero si ya lo sabes.[n][w][e]
[s]Toma, te doy[n][f 2 5 3 9999 1] a cambio.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_9]
[s]Ah, entonces tambi姻n[n]puedo brillar... Ser姻 como un 茨ngel[n]portador de la paz mundial. Espera...[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_10]
[s]斡Un momento! 斡Uf, con[n]el brillo estar胤a horrible![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_11]
[s]斡Entonces tambi姻n puedo brillar![n][w][e]
[s]Pero ya llevas[n][clr 1][var 2][clr 27] dentro de ti.[n]Ten, 斡[f 2 5 3 9999 1]![n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_12]
[s]斡Entonces tambi姻n puedo brillar![n][w][e]
[s]Un momento, 夷tu nivel no es muy bajo?[n]Te dar姻 [f 2 5 3 9999 1].[n]Hasta luego.[n][w][e]

[msg TalkMsg_RESULT_BRAINWASH_13]
[s]夷Qu姻 es eso que brilla?[n]夷Qu姻 es?[n][w][e]

[msg TalkMsg_RESULT_HACKING]
[s]Ay, madre. Me has tocado[n]la fibra sensible. Bueno,[n]te dar姻 algo especial.[n][w][e]

[msg TalkMsg_SKIMMING_BRAINWA]
[s]斡Hostia puta! 斡Lo has encontrado![n][w][e]

[msg TalkMsg_RESULT_GET_PERSO_11]
[s]En serio, gracias por salvarme. [n]斡Un momento! 斡Hablar contigo [n]me ha recordado algo![n][w][e]

[msg TalkMsg_CHARM_TECH_ITEM]
[s]斡夷Crees que me puedes enga隠ar[n]con eso?! 斡No me subestimes![n][w][e]

[msg TalkMsg_CHARM_TECH_PERSO]
[s]斡Qu姻 gracia! S胤, 斡creo que quiero[n]que seamos amigos![n][w][e]

[msg TalkMsg_BONUS_CARD]
[s]夷Me perdonar茨s si te doy esto?[n]斡Ten, cielo![n][w][e]

[msg TalkMsg_DONATION]
[s]夷Eh? 夷Solo quieres dinero?[n]斡De acuerdo![n][w][e]

[msg TalkMsg_UNTALKABLE]
[s]斡N-nooo![n][w][e]

[msg TalkMsg_GUY_OP_00_00]
[s]夷Qu姻 hacemos?[n][e]

[msg TalkMsg_GUY_OP_00_01]
[s]Tengo un mal presentimiento...[n][e]

[msg TalkMsg_GUY_OP_01_00]
[s]No mires hacia aqu胤...[n][e]

[msg TalkMsg_GUY_OP_01_01]
[s]Por favor, deja que me vaya...[n][e]

[msg TalkMsg_GUY_OP_02_00]
[s]Ba bum, ba bum...[n][e]

[msg TalkMsg_GUY_OP_02_01]
[s]斡夷Qu姻 me va a pasar?![n][e]

[msg TalkMsg_GUY_OP_03_00]
[s]No me mires.[n][e]

[msg TalkMsg_GUY_OP_03_01 [Ryuji]]

[msg TalkMsg_GUY_EN_No_00]
[s]斡Nos vemos! 斡Ojal茨 te conviertas[n]en un gran ladr吋n alg雨n d胤a![n][w][e]

[msg TalkMsg_GUY_EN_No_01]
[s]Je, je. Has sido muy f茨cil.[n]斡Adi吋s![n][w][e]

[msg TalkMsg_GUY_EN_No_02]
[s]斡Adi吋s![n]斡Qu姻 bien que fueras tan majo![n][w][e]

[msg TalkMsg_GUY_EN_bye_00]
[s]Bueno, me voy, pero la pr吋xima vez[n]no te perdonar姻.[n][w][e]

[msg TalkMsg_GUY_EN_bye_01]
[s]斡Espero que te apresen pronto, [n]por criminal![n][w][e]

[msg TalkMsg_GUY_EN_bye_02]
[s]Ayyy... 斡Vuelvo a casa![n][w][e]

[msg TalkMsg_GUY_NEGO_GIVE_00]
[s]斡Vale, gracias! 斡Qu姻 suerte la m胤a![n][w][e]

[msg TalkMsg_GUY_NEGO_GIVE_01]
[s]斡Yuju! Qu姻 feliz estoy.[n][w][e]

[msg TalkMsg_GUY_NEGO_DECLINE]
[s]斡夷No?! 斡夷Por qu姻 no?![n]斡No me lo puedo creer![n][w][e]
[s]斡Pues vale![n]斡A la porra todo![n][w][e]

[msg TalkMsg_GUY_NEGO_DECLINE_2]
[s]Ay, qu姻 baj吋n...[n]夷Qu姻 ha pasado?[n][w][e]
[s]No me hace ninguna gracia.[n]Es hora de hacerte pupa.[n][w][e]

[msg TalkMsg_GUY_NEGO_TAKE_00]
[s]夷Te parece bien? Ja, ja, ja. Eres de[n]los que se conforman con poco, 夷eh?[n][w][e]

[msg TalkMsg_GUY_NEGO_TAKE_01]
[s]斡Tienes que estar content胤simo[n]de que te haya dado algo! [n][w][e]

[msg TalkMsg_GUY_NEGO_DOUBLEU]
[s]夷Qu姻? 夷Que quieres m茨s?[n]Venga, va, pero es la 雨ltima vez. [n][w][e]

[msg TalkMsg_GUY_NEGO_DOUBLEU_2]
[s]Uf, no queda casi nada para m胤...[n]Supongo que, si a ti te vale,[n]a m胤 tambi姻n.[n][w][e]

[msg TalkMsg_GUY_NEGO_AGREE_0]
[s]斡Eso es! 斡Gracias![n][w][e]

[msg TalkMsg_GUY_NEGO_AGREE_0_2]
[s]斡Vaya, eres un primor![n]Sab胤a que lo lograr胤as[n]si te esforzabas.[n][w][e]

[msg TalkMsg_GUY_NEGO_REFUSE_]
[s]斡夷Qu姻?! 夷En serio? 夷Eres un ladr吋n[n]muerto de hambre o qu姻?[n][w][e]

[msg TalkMsg_GUY_NEGO_REFUSE__2]
[s]夷Por qu姻 no? Ah... 夷Es porque[n]no te parezco lo bastante sexy?[n][w][e]

[msg TalkMsg_Coop_Reiji_00 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 10 301 1]Eh, 夷qu姻 est茨s tramando?[n]T胤o, 斡usa la cabeza![n][w][e]

[msg TalkMsg_Coop_Reiji_01 [Ryuji]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Morgana_00 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 10 301 1]斡No te muevas![n]斡Tu destino est茨 en mis garras![n][w][e]

[msg TalkMsg_Coop_Morgana_01 [Morgana]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Ann_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 3 301 1]斡Si no quieres acabar[n]como un colador, no te muevas![n][w][e]

[msg TalkMsg_Coop_Ann_01 [Ann]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Yugo_00 [Yusuke]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 5 3 301 1]Piensa bien en qu姻 situaci吋n est茨s.[n]No me gusta esa idea.[n][w][e]

[msg TalkMsg_Coop_Yugo_01 [Yusuke]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Makoto_00 [Makoto]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 6 3 301 1]斡Deja de resistirte y colabora![n][w][e]

[msg TalkMsg_Coop_Makoto_01 [Makoto]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Haruko_00 [Haru]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 3 301 1]斡Espera! 夷Entiendes acaso[n]la situaci吋n en la que est茨s?[n][w][e]

[msg TalkMsg_Coop_Haruko_01 [Haru]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Coop_Akechi_00 [Akechi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 3 301 1]斡Quieto! Ser茨 mejor que[n]no hagas movimientos repentinos.[n][w][e]

[msg TalkMsg_Coop_Akechi_01 [Akechi]]
[s]Parece que la sombra[n]se lo ha pensado mejor...[n][w][e]

[msg TalkMsg_Sense_Sixthsense [Akechi]]
[s]斡Iniciando Sexto sentido![n][f 1 3 65535][w][e]
[s]Tu sentido aumentado[n]ha detectado una opci吋n[n]que no deb胤a ser escogida.[n][w][e]

[msg TalkMsg_Sense_Negotiatio [Akechi]]
[s]斡Iniciando Negociaci吋n![n][f 1 3 65535][w][e]
[s]Has recibido mayor[n]cooperaci吋n con una t姻cnica de[n]negociaci吋n mejorada.[n][w][e]

[msg TalkMsg_Sense_Gigolo_00 [Akechi]]
[s]斡Iniciando Gigol吋![n][f 1 3 65535][w][e]
[s]Hacer alarde de tu refinada[n]seducci吋n estimula el coraz吋n y[n]la mente de las sombras femeninas.[n][w][e]

[msg TalkMsg_Sense_Performanc [Akechi]]
[s]斡Inicia Actuaci吋n![n][f 1 3 65535][w][e]
[s]斡Monta un n雨mero espl姻ndido[n]y despierta el inter姻s[n]de las sombras enemigas![n][w][e]

[msg TalkMsg_Sense_Intelligen [Akechi]]
[s]斡Inicia Inteligencia![n][f 1 3 65535][w][e]
[s]斡Monta un n雨mero espl姻ndido[n]y despierta el inter姻s[n]de las sombras enemigas![n][w][e]

[msg TalkMsg_Tisei]
[s]No tienes la inteligencia[n]suficiente para escoger eso.[n][f 1 4][e]

[msg TalkMsg_Iroke]
[s]No tienes la seducci吋n suficiente[n]para escoger eso.[n][f 1 4][e]

[msg TalkMsg_Ginou]
[s]No tienes la t姻cnica suficiente[n]para escoger eso.[n][f 1 4][e]

[msg TalkMsg_Hinsei]
[s]No tienes el car茨cter suficiente[n]para escoger eso.[n][f 1 4][e]

[msg TalkMsg_Yuuki]
[s]No tienes el Coraje suficiente[n]para escoger eso.[n][f 1 4][e]

[sel Nego_Surrender_sel top]
[s]Conc姻deme tu poder.[e]
[s]Ens姻隠ame el dinero.[e]
[s]Quiero un objeto.[e]
[s]Panther, enc茨rgate t雨.[e]

[sel Nego_Surrender_sel_01 top]
[s][clr 2]郁nete a mi causa.[clr 27][e]
[s]Ens姻隠ame el dinero.[e]
[s]Quiero un objeto.[e]
[s]Panther, enc茨rgate t雨.[e]

[sel Nego_Surrender_sel_02 top]
[s]Conc姻deme tu poder.[e]
[s][clr 2]Ens姻隠ame el dinero.[clr 27][e]
[s]Quiero un objeto.[e]
[s]Panther, enc茨rgate t雨.[e]

[sel Nego_Surrender_sel_03 top]
[s]Conc姻deme tu poder.[e]
[s]Ens姻隠ame el dinero.[e]
[s][clr 2]Dame la mercanc胤a.[clr 27][e]
[s]Panther, enc茨rgate t雨.[e]

[sel Nego_Surrender_sel_04 top]
[s]Conc姻deme tu poder.[e]
[s]Ens姻隠ame el dinero.[e]
[s][clr 2]Dame la mercanc胤a.[clr 27][e]
[s]Panther, enc茨rgate t雨.[e]

[sel Nego_Payfor_sel top]
[s]Me lo quedo.[e]
[s][clr 2]Eso no es lo mejor que tienes.[clr 27][e]
[s][w][e]

[sel Nego_Brainwash_sel top]
[s]R胤ndete ante m胤.[e]
[s]Dame un donativo.[e]
[s]Dame algo 雨til.[e]
[s]Panther, enc茨rgate t雨.[e]

[sel TalkSel_Greet_Possesed_B top]
[s]Bueno, vale.[e]
[s]No te he pedido esto.[e]

[sel TalkSel_Pre_Question top]
[s]Bueno, vale.[e]
[s]No es necesario.[e]

[msg Talk_tech]
[s]Yoshida Toranosuke[n]斡Gesti吋n de impresi吋n! (Provisional)[n][w][e]

[sel TalkSel_Tech top]
[s]斡Ayuda, por favor![e]

[msg CharmTech [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]Vamos, ricura. 夷No puedes ser[n]un poco m茨s amable conmigo?[n][w][e]

[msg CharmActing [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 301 1]斡Aaah! 斡夷C吋mo te atreves[n]a pedirnos eso?![n][w][e]

[msg RareBooster]
[s]Yoshida Toranosuke[n]斡Gesti吋n de impresi吋n! (Provisional)[n][w][e]

[msg CheapAct [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 5 300 1]Joker, tengo miedo... Deber胤amos[n]irnos. 斡Eh! 夷Puedes decirle[n]a tu jefe que nos vamos?[n][w][e]

[msg TalkMsg_cnt_interruptE]
[s]Otro enemigo se ha metido[n]en la conversaci吋n.[n][w][e]

[msg TalkMsg_cnt_interruptP]
[s]Tras hablar con el objetivo una vez[n]tus compa隠eros pueden entrometerse[n]para avanzar (% de posibilidad).[n][w][e]

[msg TalkMsg_cnt_refuse]
[s]El objetivo se niega a hablar.[n]→Esto ocurre si el resultado[n]de la conversaci吋n es una negativa.[n][w][e]

[msg TalkMsg_cnt_anger]
[s]Target is angry and counterattacks[n]Bad case when the result of[n]the conversation is refusal.[n][w][e]

[msg TalkMsg_cnt_unusual]
[s]No se puede hablar[n]debido a los efectos de estado.[n][w][e]

[msg TalkMsg_EOF]
[s]...[n][w][e]

[msg DebugMsg_ERROR]
[s](Error)[n]→A variable is set[n]to an invalid value.[n][w][e]

[msg DebugMsg_CHARACTER]
[s](Debug Mode)[n]Target Personality Type[n][w][e]

[sel DebugSel_CHARACTER top]
[s]Tipo A[e]
[s]Tipo B[e]
[s]Tipo C[e]
[s]Tipo D[e]
[s]Aleatorio[e]

[msg DebugMsg_CHECK_VAR]
[s][var 0].[n][w][e]

[msg DebugMsg_ENEMY_LV]
[s]ID del enemigo: [var 3][n]Nivel del enemigo: [var 0][n]Nivel del protagonista: [var 1][n]AI_CHK_ENIDLV_O([var 0], 1) = [var 2][n][w][e]

[msg TalkMsg_GUY_RESULT_GET_P_4 [Ann]]
[s]斡Pues le dar姻 algo de experiencia[n]a mi yo en tu interior![n][w][e]

[msg TalkMsg_Coop_AkechiB_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 3 301 1]No parece una decisi吋n[n]muy acertada...[n]Quiz茨 deber胤as pens茨rtelo mejor.[n][w][e]

[msg TalkMsg_Coop_Kasumi_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 1]斡Alto! Ser茨 mejor que[n]no hagas nada imprudente.[n][w][e]

[msg TalkMsg_Coop_Sumire_00 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 11 3 301 1]斡Alto! Ser茨 mejor que[n]no hagas nada imprudente.[n][w][e]

