[msg MSG_BUY_CONF]
[s]夷Comprar esta pista?[n][e]

[msg MSG_BGM_CHANGE]
[s]夷Cambiar la m雨sica de fondo?[n][e]

[msg MSG_INFO_START_ID]
[s]Persona 5[n]Canci吋n de apertura[n](versi吋n cinematogr茨fica)[n][e]

[msg MSG_002]
[s]Persona 5[n]Canci吋n de apertura[n][e]

[msg MSG_003]
[s]Persona 5[n]Pantalla de t胤tulo[n][e]

[msg MSG_004]
[s]Suena durante la escena del casino[n]al inicio del juego.[n][e]

[msg MSG_005]
[s]Suena durante la investigaci吋n[n]y los interrogatorios de Sae.[n][e]

[msg MSG_006]
[s]Suena durante escenas tensas.[n][e]

[msg MSG_007]
[s]Suena cuando los protagonistas[n]despiertan sus Personas.[n][e]

[msg MSG_008]
[s]Suena cuando la gente habla[n]de sus problemas o de su pasado.[n][e]

[msg MSG_009]
[s]Suena el d胤a del asalto.[n][e]

[msg MSG_010]
[s]Suena cuando los Ladrones Fantasma[n]hallan al se隠or de un Palacio.[n][e]

[msg MSG_011]
[s]Suena cuando el se隠or[n]de un Palacio despierta.[n][e]

[msg MSG_012]
[s]Suena cuando el protagonista[n]est茨 mejorando[n]sus estad胤sticas sociales.[n][e]

[msg MSG_013]
[s]Suena durante escenas tranquilas.[n][e]

[msg MSG_014]
[s]Suena mientras los protagonistas[n]analizan y comparten informaci吋n.[n][e]

[msg MSG_015]
[s]Suena en el d胤a a d胤a.[n][e]

[msg MSG_016]
[s]Alright[n](versi吋n arreglada)[n][e]

[msg MSG_017]
[s]Suena cuando la gente habla[n]de sus problemas o de su pasado.[n]Diferente de Confession / Secret.[n][e]

[msg MSG_018]
[s]Suena en la casa de Niijima.[n][e]

[msg MSG_019]
[s]Suena cuando los protagonistas[n]planean estrategias.[n][e]

[msg MSG_020]
[s]Suena durante escenas de suspense.[n][e]

[msg MSG_021]
[s]Suena cuando los protagonistas[n]se lo pasan bien.[n][e]

[msg MSG_022]
[s]Suena en momentos de calma.[n][e]

[msg MSG_023]
[s]Break it Down[n](versi吋n arreglada)[n][e]

[msg MSG_024]
[s]Suena durante los ex茨menes[n]del instituto. [n][e]

[msg MSG_025]
[s]Suena cuando la gente habla[n]de sus problemas o de su pasado.[n]Tiene un tono especialmente triste.[n][e]

[msg MSG_026]
[s]Suena cuando se establece[n]relaci吋n con un Confidente.[n][e]

[msg MSG_027]
[s]Suena durante las conversaciones[n]con un Confidente.[n][e]

[msg MSG_028]
[s]Suena cuando se pasa tiempo[n]con una amante.[n][e]

[msg MSG_029]
[s]Suena cuando los Ladrones Fantasma[n]toman decisiones importantes.[n][e]

[msg MSG_030]
[s]Suena en el instituto.[n][e]

[msg MSG_031]
[s]Suena cuando los Ladrones Fantasma[n]escapan.[n][e]

[msg MSG_032]
[s]Suena en las escenas donde los[n]personajes principales planean su[n]estrategia. Diferente de Suspicion.[n][e]

[msg MSG_033]
[s]Suena en escenas amenazadoras,[n]como cuando el enemigo conspira[n]o los personajes est茨n preocupados.[n][e]

[msg MSG_034]
[s]La canci吋n final que suena[n]tras derrotar al dios mal姻volo.[n][e]

[msg MSG_035]
[s]Suena en la ciudad por la noche.[n][e]

[msg MSG_036]
[s]Suena en el Leblanc,[n]mientras vas al instituto[n]y en otros acontecimientos diarios.[n][e]

[msg MSG_037]
[s]Suena en la ciudad mientras llueve.[n][e]

[msg MSG_038]
[s]Suena en el Leblanc cuando llueve,[n]mientras vas al instituto[n]y en otros acontecimientos diarios.[n][e]

[msg MSG_039]
[s]Suena en la ciudad[n]cuando las cosas est茨n tranquilas.[n][e]

[msg MSG_040]
[s]Suena en la ciudad[n]cuando las cosas est茨n tensas.[n][e]

[msg MSG_041]
[s]Suena en la Cl胤nica Takemi.[n][e]

[msg MSG_042]
[s]Suena en la tienda Untouchable.[n][e]

[msg MSG_043]
[s]Suena en la Habitaci吋n Terciopelo.[n][e]

[msg MSG_044]
[s]Suena en 777,[n]la tienda de autoservicio.[n][e]

[msg MSG_045]
[s]Suena en el Big Bang Burger.[n][e]

[msg MSG_046]
[s]Suena en la iglesia de Kanda.[n][e]

[msg MSG_047]
[s]Suena en el Crossroads.[n][e]

[msg MSG_048]
[s]Suena en el planetario.[n][e]

[msg MSG_049]
[s]Suena en la tienda[n]de electr吋nica de Akihabara.[n][e]

[msg MSG_050]
[s]Suena en Destinyland.[n][e]

[msg MSG_051]
[s]Suena en El delantal de Alicia,[n]la cafeter胤a de sirvientas.[n][e]

[msg MSG_052]
[s]Suena al jugar en una m茨quina[n]de gancho.[n][e]

[msg MSG_053]
[s]Suena al echar un ojo[n]en Art胤culos sospechosos Tanaka.[n][e]

[msg MSG_054]
[s]Suena durante un combate normal.[n][e]

[msg MSG_055]
[s]Suena en la pantalla de resultados[n]de combate.[n][e]

[msg MSG_056]
[s]Suena al hablar con las sombras.[n][e]

[msg MSG_057]
[s]Suena cuando un miembro de[n]los Ladrones Fantasma despierta[n]su Persona y entra en combate.[n][e]

[msg MSG_058]
[s]Suena al pelear[n]contra enemigos poderosos.[n][e]

[msg MSG_059]
[s]Suena al pelear[n]contra el se隠or de un Palacio.[n][e]

[msg MSG_060]
[s]Suena al pelear contra la bestia[n]del sacrificio humano.[n][e]

[msg MSG_061]
[s]Suena al pelear contra Samael[n]y el Santo Grial.[n][e]

[msg MSG_062]
[s]Suena al pelear contra Yaldabaoth.[n][e]

[msg MSG_063]
[s]Suena al pelear contra Yaldabaoth,[n]despu姻s de invocar a Satanael.[n][e]

[msg MSG_064]
[s]Suena en las Habitaciones seguras.[n][e]

[msg MSG_065]
[s]Palacio de Kamoshida:[n]prisi吋n subterr茨nea[n]e interior del castillo[n][e]

[msg MSG_066]
[s]Palacio de Kamoshida:[n]torre[n][e]

[msg MSG_067]
[s]Palacio de Madarame:[n]museo[n][e]

[msg MSG_068]
[s]Palacio de Madarame:[n]sala del tesoro[n][e]

[msg MSG_069]
[s]Palacio de Kaneshiro:[n]banco[n][e]

[msg MSG_070]
[s]Palacio de Kaneshiro:[n]c茨mara[n][e]

[msg MSG_071]
[s]Palacio de Futaba:[n]pir茨mide[n][e]

[msg MSG_072]
[s]Palacio de Futaba:[n]ciudad del desierto[n][e]

[msg MSG_073]
[s]Palacio de Okumura:[n]puerto espacial[n][e]

[msg MSG_074]
[s]Palacio de Okumura:[n]espacio exterior[n][e]

[msg MSG_075]
[s]Palacio de Niijima[n][e]

[msg MSG_076]
[s]Palacio de Shido[n][e]

[msg MSG_077]
[s]Suena en la prisi吋n de Acedia.[n][e]

[msg MSG_078]
[s]Suena en zonas de Mementos[n]como el camino de Qimranut.[n][e]

[msg MSG_079]
[s]Persona 5 Royal[n]Canci吋n de apertura[n][e]

[msg MSG_080]
[s]Persona 5 Royal[n]Pantalla de t胤tulo[n][e]

[msg MSG_081]
[s]Suena el d胤a del asalto[n]al Palacio de Maruki.[n][e]

[msg MSG_082]
[s]Suena en la versi吋n de la realidad[n]de Maruki.[n][e]

[msg MSG_083]
[s]Suena durante las sesiones[n]con Maruki.[n][e]

[msg MSG_084]
[s]M雨sica de fondo del pasado[n]de Maruki (sin usar)[n][e]

[msg MSG_085]
[s]Suena durante la escena de baile[n]despu姻s del festival.[n][e]

[msg MSG_086]
[s]M雨sica del Instituto Shujin.[n][e]

[msg MSG_087]
[s]Final 或Abandono位 (sin usar)[n][e]

[msg MSG_088]
[s]La canci吋n final que suena tras[n]rechazar la realidad de Maruki.[n][e]

[msg MSG_089]
[s]Suena en la ciudad mientras[n]el Palacio de Maruki est茨 activo.[n][e]

[msg MSG_090]
[s]Suena en la Guarida[n]de los Ladrones.[n][e]

[msg MSG_091]
[s]Aria of the Soul con voz (sin usar)[n][e]

[msg MSG_092]
[s]Suena en Jazz Jin, el club de jazz.[n][e]

[msg MSG_093]
[s]Suena en Jazz Jin, el club de jazz,[n]cuando un cantante va a actuar.[n][e]

[msg MSG_094]
[s]Suena en Penguin Sniper,[n]el bar de dardos.[n][e]

[msg MSG_095]
[s]Suena en las emboscadas.[n][e]

[msg MSG_096]
[s]Suena al pelear contra Azathoth.[n][e]

[msg MSG_097]
[s]Suena al pelear contra Adam Kadmon.[n][e]

[msg MSG_098]
[s]Palacio de Maruki:[n]laboratorio[n][e]

[msg MSG_099]
[s]Palacio de Maruki:[n]pasillo del Crep雨sculo[n][e]

[msg MSG_100]
[s]Mementos: cambio de piso 1[n](sin usar)[n][e]

[msg MSG_101]
[s]Suena en zonas de Mementos[n]en el camino de Chemdah.[n][e]

[msg MSG_102]
[s]Suena en zonas de Mementos[n]en el camino de Akzeriyyuth.[n][e]

[msg MSG_103]
[s]Suena en zonas de Mementos[n]en el camino de Sheriruth.[n][e]

[msg MSG_104]
[s]Suena en zonas de Mementos[n]en el camino de Da'at.[n][e]

[msg MSG_105]
[s]El nuevo tema de Lilina estrella.[n][e]

[msg MSG_106]
[s]La canci吋n final que suena[n]tras aceptar[n]la realidad perfecta de Maruki.[n][e]

[msg MSG_107]
[s]Suena durante los desaf胤os[n]de combate.[n][e]

[msg MSG_108]
[s]108[n]あいうえお[n]かきくけこ[n][e]

[msg MSG_109]
[s]109[n]あいうえお[n]かきくけこ[n][e]

[msg MSG_110]
[s]111[n]あいうえお[n]かきくけこ[n][e]

[msg MSG_111]
[s]111[n]あいうえお[n]かきくけこ[n][e]

[msg MSG_112]
[s]112[n]あいうえお[n]かきくけこ[n][e]

[msg MSG_113]
[s]113[n]あいうえお[n]かきくけこ[n][e]

[msg MSG_114]
[s]114[n]あいうえお[n]かきくけこ[n][e]

[msg MSG_115]
[s]115[n]あいうえお[n]かきくけこ[n][e]

[msg MSG_116]
[s]116[n]あいうえお[n]かきくけこ[n][e]

