[sel SAVELOAD_YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg SAVELOAD_MSG_GET_SAVE_DA]
[s]Accediendo a los datos guardados...[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_SAVE_CONF]
[s]Ya existen datos de guardado[n]en este espacio.[n]夷Quieres sobrescribirlos?[n][e]

[msg SAVELOAD_MSG_SAVE_RUN]
[s]Guardando...[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_SAVE_SUCCES]
[s]Guardado completado.[n][w][e]

[msg SAVELOAD_MSG_SAVE_FAILED]
[s]Error al guardar.[n][w][e]

[msg SAVELOAD_MSG_LOAD_CONF]
[s]Se cargar茨n tus datos.[n]夷Est茨s de acuerdo?[n][f 1 2 0][e]

[msg SAVELOAD_MSG_LOAD_RUN]
[s]Cargando...[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_LOAD_SUCCES]
[s]Carga completada.[n][f 1 2 15][e]

[msg SAVELOAD_MSG_LOAD_FAILED]
[s]Error al cargar.[n][w][e]

[msg SAVELOAD_MSG_CONFIG_NET_]
[s]La funci吋n de red[n]est茨 deshabilitada. Act胤vala[n]y vuelve a intentarlo.[n][w][e]

[msg SAVELOAD_MSG_CLOUD_GET_D]
[s]Debes acceder a la nube[n]para comprobar los datos guardados.[n]夷Continuar?[n][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_2]
[s]Accediendo a los datos guardadosen la nube...[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_3]
[s]Se ha accedido[n]a los datos guardados en la nube...[n][w][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_4]
[s]Error al accedera los datos guardados.[n][w][e]

[msg SAVELOAD_MSG_CLOUD_NEW_S]
[s]No hay datos guardados en la nube.[n]夷Quieres crear un nuevo archivo[n]de guardado?[n][e]

[msg SAVELOAD_MSG_CLOUD_BROKE]
[s]Los datos guardados en la nube[n]est茨n da隠ados. 夷Quieres crear[n]un nuevo archivo de guardado?[n][e]

[msg SAVELOAD_MSG_ClOUD_NO_DA]
[s]No hay datos guardados en la nube.[n][w][e]

[msg SAVELOAD_MSG_ClOUD_BROKE]
[s]Los datos guardados en la nubeest茨n da隠ados.[n][w][e]

[msg SAVELOAD_TXT_TITLE_SAVE]
[s]夷Guardar tus acciones hasta este punto?[n][w][e]

[msg SAVELOAD_TXT_TITLE_LOAD]
[s]夷Releer las entradas hasta este punto?[n][w][e]

[msg SAVELOAD_TXT_CLOUD_GET_D]
[s]夷Obtener datos de guardado de la nube?[n][w][e]

[msg SAVELOAD_MSG_GET_SAVE_DA_2]
[s]Accediendo a los datos guardados…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_GET_SAVE_DA_3]
[s]Accediendo a los datos guardados…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_GET_SAVE_DA_4]
[s]Accediendo a los datos guardados…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_GET_SAVE_DA_5]
[s]Accediendo a los datos guardados…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_5]
[s]Recuperando los datos guardados en la nube.[n]夷Est茨s de acuerdo?[n][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_6]
[s]Recuperando los datos guardados en la nube.[n]夷Est茨s de acuerdo?[n][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_7]
[s]Recuperando los datos guardados en la nube.[n]夷Est茨s de acuerdo?[n][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_8]
[s]Recuperando los datos guardados en la nube.[n]夷Est茨s de acuerdo?[n][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_9]
[s]Recuperando los datos guardados en la nube.[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_10]
[s]Recuperando los datos guardados en la nube.[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_11]
[s]Recuperando los datos guardados en la nube.[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_12]
[s]Recuperando los datos guardados en la nube.[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_13]
[s]Se han recuperado los datos guardados en la nube.[n][w][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_14]
[s]Se han recuperado los datos guardados en la nube.[n][w][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_15]
[s]Se han recuperado los datos guardados en la nube.[n][w][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_16]
[s]Se han recuperado los datos guardados en la nube.[n][w][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_17]
[s]No se han podido recuperar los datos guardados[n]en la nube.[n][w][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_18]
[s]No se han podido recuperar los datos guardados[n]en la nube.[n][w][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_19]
[s]No se han podido recuperar los datos guardados[n]en la nube.[n][w][e]

[msg SAVELOAD_MSG_CLOUD_GET_D_20]
[s]No se han podido recuperar los datos guardados[n]en la nube.[n][w][e]

[msg SAVELOAD_MSG_CLOUD_NEW_S_2]
[s]No hay datos guardados en la nube.[n]夷Crear un nuevo archivo de guardado?[n][e]

[msg SAVELOAD_MSG_CLOUD_NEW_S_3]
[s]No hay datos guardados en la nube.[n]夷Crear un nuevo archivo de guardado?[n][e]

[msg SAVELOAD_MSG_CLOUD_NEW_S_4]
[s]No hay datos guardados en la nube.[n]夷Crear un nuevo archivo de guardado?[n][e]

[msg SAVELOAD_MSG_CLOUD_NEW_S_5]
[s]No hay datos guardados en la nube.[n]夷Crear un nuevo archivo de guardado?[n][e]

[msg SAVELOAD_MSG_CLOUD_BROKE_2]
[s]Los datos guardados en la nube est茨n da隠ados.[n]夷Crear un nuevo archivo de guardado?[n][e]

[msg SAVELOAD_MSG_CLOUD_BROKE_3]
[s]Los datos guardados en la nube est茨n da隠ados.[n]夷Crear un nuevo archivo de guardado?[n][e]

[msg SAVELOAD_MSG_CLOUD_BROKE_4]
[s]Los datos guardados en la nube est茨n da隠ados.[n]夷Crear un nuevo archivo de guardado?[n][e]

[msg SAVELOAD_MSG_CLOUD_BROKE_5]
[s]Los datos guardados en la nube est茨n da隠ados.[n]夷Crear un nuevo archivo de guardado?[n][e]

[msg SAVELOAD_MSG_ClOUD_NO_DA_2]
[s]No hay datos guardados en la nube.[n][w][e]

[msg SAVELOAD_MSG_ClOUD_NO_DA_3]
[s]No hay datos guardados en la nube.[n][w][e]

[msg SAVELOAD_MSG_ClOUD_NO_DA_4]
[s]No hay datos guardados en la nube.[n][w][e]

[msg SAVELOAD_MSG_ClOUD_NO_DA_5]
[s]No hay datos guardados en la nube.[n][w][e]

[msg SAVELOAD_MSG_ClOUD_BROKE_2]
[s]Los datos guardados en la nube est茨n da隠ados.[n][w][e]

[msg SAVELOAD_MSG_ClOUD_BROKE_3]
[s]Los datos guardados en la nube est茨n da隠ados.[n][w][e]

[msg SAVELOAD_MSG_ClOUD_BROKE_4]
[s]Los datos guardados en la nube est茨n da隠ados.[n][w][e]

[msg SAVELOAD_MSG_ClOUD_BROKE_5]
[s]Los datos guardados en la nube est茨n da隠ados.[n][w][e]

[msg SAVELOAD_TXT_CLOUD_GET_D_2]
[s]夷Recuperar los datos guardados en la nube?[n][w][e]

[msg SAVELOAD_TXT_CLOUD_GET_D_3]
[s]夷Recuperar los datos guardados en la nube?[n][w][e]

[msg SAVELOAD_TXT_CLOUD_GET_D_4]
[s]夷Recuperar los datos guardados en la nube?[n][w][e]

[msg SAVELOAD_TXT_CLOUD_GET_D_5]
[s]夷Recuperar los datos guardados en la nube?[n][w][e]

[msg SAVELOAD_MSG_LOAD_CONF_F]
[s]Cargando.[n]夷Est茨s de acuerdo?[n][f 1 2 0][e]

[msg SAVELOAD_MSG_LOAD_CONF_F_2]
[s]Cargando.[n]夷Est茨s de acuerdo?[n][f 1 2 0][e]

[msg SAVELOAD_MSG_LOAD_CONF_F_3]
[s]Cargando.[n]夷Est茨s de acuerdo?[n][f 1 2 0][e]

[msg SAVELOAD_MSG_LOAD_CONF_F_4]
[s]Cargando.[n]夷Est茨s de acuerdo?[n][f 1 2 0][e]

[msg SAVELOAD_MSG_LOAD_RUN_Fi]
[s]Cargando…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_LOAD_RUN_Fi_2]
[s]Cargando…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_LOAD_RUN_Fi_3]
[s]Cargando…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_LOAD_RUN_Fi_4]
[s]Cargando…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_LOAD_SUCCES_2]
[s]Se ha terminado de cargar el archivo.[n][f 1 2 15][e]

[msg SAVELOAD_MSG_LOAD_SUCCES_3]
[s]Se ha terminado de cargar el archivo.[n][f 1 2 15][e]

[msg SAVELOAD_MSG_LOAD_SUCCES_4]
[s]Se ha terminado de cargar el archivo.[n][f 1 2 15][e]

[msg SAVELOAD_MSG_LOAD_SUCCES_5]
[s]Se ha terminado de cargar el archivo.[n][f 1 2 15][e]

[msg SAVELOAD_MSG_LOAD_FAILED_2]
[s]No se ha podido cargar.[n][w][e]

[msg SAVELOAD_MSG_LOAD_FAILED_3]
[s]No se ha podido cargar.[n][w][e]

[msg SAVELOAD_MSG_LOAD_FAILED_4]
[s]No se ha podido cargar.[n][w][e]

[msg SAVELOAD_MSG_LOAD_FAILED_5]
[s]No se ha podido cargar.[n][w][e]

[msg SAVELOAD_MSG_SAVE_RUN_Fi]
[s]Guardando…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_SAVE_RUN_Fi_2]
[s]Guardando…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_SAVE_RUN_Fi_3]
[s]Guardando…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_SAVE_RUN_Fi_4]
[s]Guardando…[n][f 1 2 65535][e]

[msg SAVELOAD_MSG_SAVE_SUCCES_2]
[s]Se ha terminado de guardar.[n][w][e]

[msg SAVELOAD_MSG_SAVE_SUCCES_3]
[s]Se ha terminado de guardar.[n][w][e]

[msg SAVELOAD_MSG_SAVE_SUCCES_4]
[s]Se ha terminado de guardar.[n][w][e]

[msg SAVELOAD_MSG_SAVE_SUCCES_5]
[s]Se ha terminado de guardar.[n][w][e]

[msg SAVELOAD_MSG_SAVE_FAILED_2]
[s]No se ha podido guardar.[n][w][e]

[msg SAVELOAD_MSG_SAVE_FAILED_3]
[s]No se ha podido guardar.[n][w][e]

[msg SAVELOAD_MSG_SAVE_FAILED_4]
[s]No se ha podido guardar.[n][w][e]

[msg SAVELOAD_MSG_SAVE_FAILED_5]
[s]No se ha podido guardar.[n][w][e]

[msg SAVELOAD_MSG_SAVE_CONF_F]
[s]Ya existen datos de guardado[n]en este espacio.[n]夷Quieres sobrescribirlos?[n][e]

[msg SAVELOAD_MSG_SAVE_CONF_F_2]
[s]Ya existen datos de guardado[n]en este espacio.[n]夷Quieres sobrescribirlos?[n][e]

[msg SAVELOAD_MSG_SAVE_CONF_F_3]
[s]Ya existen datos de guardado[n]en este espacio.[n]夷Quieres sobrescribirlos?[n][e]

[msg SAVELOAD_MSG_SAVE_CONF_F_4]
[s]Ya existen datos de guardado[n]en este espacio.[n]夷Quieres sobrescribirlos?[n][e]

[msg SAVEDATA_DELETE_ACTIVITY]
[s]No hay datos guardados.[n]Empezar茨s desde la pantalla de t胤tulo.[n][w][e]

[msg LANGUAGE_CHANGE_NAME_Fib]
[s]Como se ha cambiado el idioma,[n]el nombre del protagonista ser茨 "Ren Amamiya",[n]y el de los Ladrones Fantasma, "Los Ladrones".[n]Si quieres jugar con el nombre que creaste,[n]tendr茨s que volver al idioma usado en ese momento.[n][w][e]

