[msg CROSSWORD_00_TEXT_00]
[s]Material para fuegos artificiales[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]PIROTECNIA[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Cordel que se adhiere a los explosivos[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Palito que emite chispas[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_09]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_10]
[s][XLOC_NOTUSED][n][w][e]

