[msg CROSSWORD_00_TEXT_00]
[s]Promesa hecha en A隠o Nuevo[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]PROP遺SITO[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Mejora la condici吋n f胤sica[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Restricci吋n alimentaria[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_09]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_10]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_11]
[s][XLOC_NOTUSED][n][w][e]

