[msg CROSSWORD_00_TEXT_00]
[s]Lo hacen las luces[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]ILUMINAR[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Adornan las tartas[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]La luz de la Estatua de la Libertad[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

