[msg CROSSWORD_00_TEXT_00]
[s]Hermano gemelo del hurac茨n[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]TIF遺N[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Advertencia[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Viento fuerte y repentino[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s]Vac胤o entre dos elementos[n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

