[msg CROSSWORD_00_TEXT_00]
[s]T姻rmino ingl姻s de 或clasificaci吋n位[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]RANKING[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Perteneciente o relativo a las academias[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Un deportista de categor胤a y edad superior[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

