[msg CROSSWORD_00_TEXT_00]
[s]Festividad c姻ltica adoptada[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]HALLOWEEN[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Alternativa al truco[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Hechicera malvada[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

