[msg MSG_DUMMY]
[s]...[n][w][e]

[sel SPOT_SELECT_COMMON top]
[s]Ir con Ryuji[e]
[s]Ir con Ann[e]
[s]Ir con Yusuke[e]
[s]Ir con Makoto[e]
[s]Ir solo[e]
[s]Cancelar[e]

[sel SEL_SPOT_GO top]
[s]Vamos.[e]
[s]Da igual.[e]

[sel SEL_SPOT_GO_ASAKUSA top]
[s]Skytree[e]
[s]Calle Nakamise[e]
[s]Cancelar[e]

[msg OGIKUBO_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Ogikubo[clr 27]? All胤 hay un[n][clr 2]restaurante de ramen famoso[clr 27]. 夷Quieres ir?[n][w][e]

[msg OGIKUBO_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]ramen[clr 27] de [clr 2]Ogikubo[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg OGIKUBO_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]ramen[clr 27] de [clr 2]Ogikubo[clr 27] con la[n]se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg OGIKUBO_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]ramen[clr 27] de [clr 2]Ogikubo[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg OGIKUBO_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]ramen[clr 27] de [clr 2]Ogikubo[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg OGIKUBO_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]ramen[clr 27] de [clr 2]Ogikubo[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg OGIKUBO_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]ramen[clr 27] de [clr 2]Ogikubo[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg ITIGAYA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Ichigaya[clr 27]?[n]All胤 hay un [clr 2]estanque[clr 27]. 夷Quieres ir?[n][w][e]

[msg ITIGAYA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]estanque[clr 27][n]de [clr 2]Ichigaya[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg ITIGAYA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]estanque[clr 27][n]de [clr 2]Ichigaya[clr 27] con la se隠orita Ann.[n]夷Quieres volver?[n][w][e]

[msg ITIGAYA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]estanque[clr 27][n]de [clr 2]Ichigaya[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg ITIGAYA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]estanque[clr 27][n]de [clr 2]Ichigaya[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg ITIGAYA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]estanque[clr 27][n]de [clr 2]Ichigaya[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg ITIGAYA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]estanque[clr 27][n]de [clr 2]Ichigaya[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg SUIDOUBASHI_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Suidobashi[clr 27]? All胤 est茨[n][clr 2]Dome Town[clr 27]. 夷Quieres ir?[n][w][e]

[msg SUIDOUBASHI_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]夷Suidobashi[clr 27]? All胤 est茨[n][clr 2]Dome Town[clr 27], pero hoy no hace[n]buen d胤a. Vayamos a otro sitio.[n][w][e]

[msg SUIDOUBASHI_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Dome Town[clr 27],[n]que est茨 en [clr 2]Suidobashi[clr 27],[n]con Ryuji. 夷Quieres volver?[n][w][e]

[msg SUIDOUBASHI_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]Dome Town[clr 27],[n]que est茨 en [clr 2]Suidobashi[clr 27], con la[n]se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg SUIDOUBASHI_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Dome Town[clr 27],[n]que est茨 en [clr 2]Suidobashi[clr 27],[n]con Yusuke. 夷Quieres volver?[n][w][e]

[msg SUIDOUBASHI_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Dome Town[clr 27],[n]que est茨 en [clr 2]Suidobashi[clr 27],[n]con Makoto. 夷Quieres volver?[n][w][e]

[msg SUIDOUBASHI_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Dome Town[clr 27],[n]que est茨 en [clr 2]Suidobashi[clr 27],[n]con Futaba. 夷Quieres volver?[n][w][e]

[msg SUIDOUBASHI_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Dome Town[clr 27],[n]que est茨 en [clr 2]Suidobashi[clr 27],[n]con Haru. 夷Quieres volver?[n][w][e]

[msg INOKASIRA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]El Parque Inokashira[clr 27]? All胤 hay[n]un [clr 2]lago muy grande[clr 27]. 夷Quieres ir?[n][w][e]

[msg INOKASIRA_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]夷El Parque Inokashira[clr 27]? All胤 hay[n]un [clr 2]lago muy grande[clr 27], pero hoy hace[n]mal tiempo. Vamos a otro sitio.[n][w][e]

[msg INOKASIRA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]lago[clr 27][n]del [clr 2]Parque Inokashira[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg INOKASIRA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]lago[clr 27][n]del [clr 2]Parque Inokashira[clr 27] con[n]la se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg INOKASIRA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]lago[clr 27][n]del [clr 2]Parque Inokashira[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg INOKASIRA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]lago[clr 27][n]del [clr 2]Parque Inokashira[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg INOKASIRA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]lago[clr 27][n]del [clr 2]Parque Inokashira[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg INOKASIRA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]lago[clr 27][n]del [clr 2]Parque Inokashira[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg INOKASIRA_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]lago[clr 27][n]del [clr 2]Parque Inokashira[clr 27] con Kasumi.[n]夷Quieres volver?[n][w][e]

[msg INOKASIRA_COMMON_008 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]lago[clr 27][n]del [clr 2]Parque Inokashira[clr 27] con Sumire.[n]夷Quieres volver?[n][w][e]

[msg TUKISIMA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Tsukishima[clr 27]? All胤 hay[n]un [clr 2]restaurante de monjayaki[clr 27]. 夷Quieres ir?[n][w][e]

[msg TUKISIMA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]monjayaki[clr 27] de [clr 2]Tsukishima[clr 27][n]con Ryuji. 夷Quieres volver?[n][w][e]

[msg TUKISIMA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]monjayaki[clr 27] de [clr 2]Tsukishima[clr 27] con la[n]se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg TUKISIMA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]monjayaki[clr 27] de [clr 2]Tsukishima[clr 27][n]con Yusuke. 夷Quieres volver?[n][w][e]

[msg TUKISIMA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]monjayaki[clr 27] de [clr 2]Tsukishima[clr 27][n]con Makoto. 夷Quieres volver?[n][w][e]

[msg TUKISIMA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]monjayaki[clr 27] de [clr 2]Tsukishima[clr 27][n]con Futaba. 夷Quieres volver?[n][w][e]

[msg TUKISIMA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante de[n]monjayaki[clr 27] de [clr 2]Tsukishima[clr 27][n]con Haru. 夷Quieres volver?[n][w][e]

[msg HARAJUKU_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Harajuku[clr 27]? All胤 est茨[n]la [clr 2]calle Takenoko[clr 27]. 夷Quieres ir?[n][w][e]

[msg HARAJUKU_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]夷Harajuku[clr 27]? All胤 est茨[n]la [clr 2]calle Takenoko[clr 27].[n]Pero hoy no hace buen tiempo.[n][w][e]

[msg HARAJUKU_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]calle Takenoko[clr 27][n]de [clr 2]Harajuku[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg HARAJUKU_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]calle Takenoko[clr 27][n]de [clr 2]Harajuku[clr 27] con la se隠orita Ann.[n]夷Quieres volver?[n][w][e]

[msg HARAJUKU_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]calle Takenoko[clr 27][n]de [clr 2]Harajuku[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg HARAJUKU_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]calle Takenoko[clr 27][n]de [clr 2]Harajuku[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg HARAJUKU_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]calle Takenoko[clr 27][n]de [clr 2]Harajuku[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg HARAJUKU_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]calle Takenoko[clr 27][n]de [clr 2]Harajuku[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg IKEBUKURO_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Ikebukuro[clr 27]?[n]All胤 hay un [clr 2]planetario[clr 27]. 夷Quieres ir?[n][w][e]

[msg IKEBUKURO_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]planetario[clr 27][n]de [clr 2]Ikebukuro[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg IKEBUKURO_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]planetario[clr 27][n]de [clr 2]Ikebukuro[clr 27] con la se隠orita Ann.[n]夷Quieres volver?[n][w][e]

[msg IKEBUKURO_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]planetario[clr 27][n]de [clr 2]Ikebukuro[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg IKEBUKURO_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]planetario[clr 27][n]de [clr 2]Ikebukuro[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg IKEBUKURO_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]planetario[clr 27][n]de [clr 2]Ikebukuro[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg IKEBUKURO_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]planetario[clr 27][n]de [clr 2]Ikebukuro[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg AKIHABARA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]Akihabara[clr 27], 夷no? All胤 hay una[n][clr 2]tienda de electr吋nica[clr 27].[n]夷Quieres ir?[n][w][e]

[msg AKIHABARA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]tienda[n]de electr吋nica[clr 27] de [clr 2]Akihabara[clr 27][n]con Ryuji. 夷Quieres volver?[n][w][e]

[msg AKIHABARA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]tienda de[n]electr吋nica[clr 27] de [clr 2]Akihabara[clr 27] con[n]la se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg AKIHABARA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]tienda de[n]electr吋nica[clr 27] de [clr 2]Akihabara[clr 27][n]con Yusuke. 夷Quieres volver?[n][w][e]

[msg AKIHABARA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]tienda de[n]electr吋nica[clr 27] de [clr 2]Akihabara[clr 27][n]con Makoto. 夷Quieres volver?[n][w][e]

[msg AKIHABARA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]tienda de[n]electr吋nica[clr 27] de [clr 2]Akihabara[clr 27][n]con Futaba. 夷Quieres volver?[n][w][e]

[msg AKIHABARA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]tienda de[n]electr吋nica[clr 27] de [clr 2]Akihabara[clr 27][n]con Haru. 夷Quieres volver?[n][w][e]

[msg UENO_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Ueno[clr 27]? All胤 hay un [clr 2]museo[n]de arte[clr 27]. 夷Quieres ir?[n][w][e]

[msg UENO_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el[n][clr 2]museo de arte[clr 27][n]de [clr 2]Ueno[clr 27] con Ryuji. 夷Quieres volver?[n][w][e]

[msg UENO_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el[n][clr 2]museo de arte[clr 27][n]de [clr 2]Ueno[clr 27] con la se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg UENO_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el[n][clr 2]museo de arte[clr 27][n]de [clr 2]Ueno[clr 27] con Yusuke. 夷Quieres volver?[n][w][e]

[msg UENO_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el[n][clr 2]museo de arte[clr 27][n]de [clr 2]Ueno[clr 27] con Makoto. 夷Quieres volver?[n][w][e]

[msg UENO_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el[n][clr 2]museo de arte[clr 27][n]de [clr 2]Ueno[clr 27] con Futaba. 夷Quieres volver?[n][w][e]

[msg UENO_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el[n][clr 2]museo de arte[clr 27][n]de [clr 2]Ueno[clr 27] con Haru. 夷Quieres volver?[n][w][e]

[msg GINZA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Ginza[clr 27]? All胤 hay un[n][clr 2]restaurante elegante de sushi[clr 27]. 夷Quieres ir?[n][w][e]

[msg GINZA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante[n]elegante de sushi[clr 27] de [clr 2]Ginza[clr 27][n]con Ryuji. 夷Quieres volver?[n][w][e]

[msg GINZA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante[n]elegante de sushi[clr 27] de [clr 2]Ginza[clr 27] con[n]la se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg GINZA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante[n]elegante de sushi[clr 27] de [clr 2]Ginza[clr 27][n]con Yusuke. 夷Quieres volver?[n][w][e]

[msg GINZA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante[n]elegante de sushi[clr 27] de [clr 2]Ginza[clr 27][n]con Makoto. 夷Quieres volver?[n][w][e]

[msg GINZA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante[n]elegante de sushi[clr 27] de [clr 2]Ginza[clr 27][n]con Futaba. 夷Quieres volver?[n][w][e]

[msg GINZA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]restaurante[n]elegante de sushi[clr 27] de [clr 2]Ginza[clr 27][n]con Haru. 夷Quieres volver?[n][w][e]

[msg ASAKUSA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Asakusa[clr 27]? La [clr 2]calle Nakamise[clr 27][n]y la [clr 2]Skytree[clr 27] est茨n all胤.[n]夷Quieres ir?[n][w][e]

[msg ASAKUSA_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]La calle Nakamise[clr 27] y la [clr 2]Skytree[clr 27],[n]夷no? Hoy no hace muy buen tiempo.[n]Vamos a otra parte.[n][w][e]

[msg ASAKUSA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la calle Nakamise[clr 27][n]de [clr 2]Asakusa[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg ASAKUSA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la calle Nakamise[clr 27][n]de [clr 2]Asakusa[clr 27] con la se隠orita Ann.[n]夷Quieres volver?[n][w][e]

[msg ASAKUSA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la calle Nakamise[clr 27][n]de [clr 2]Asakusa[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg ASAKUSA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la calle Nakamise[clr 27][n]de [clr 2]Asakusa[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg ASAKUSA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la[n][clr 2]Skytree[clr 27] de [clr 2]Asakusa[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg ASAKUSA_COMMON_015 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la calle Nakamise[clr 27][n]de [clr 2]Asakusa[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg ASAKUSA_COMMON_025 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]Skytree[clr 27][n]y en la [clr 2]calle Nakamise[clr 27] con Futaba.[n]夷Qu姻 quieres hacer ahora?[n][w][e]

[msg ASAKUSA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la calle Nakamise[clr 27][n]de [clr 2]Asakusa[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg ASAKUSA_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la[n][clr 2]Skytree[clr 27] de [clr 2]Asakusa[clr 27] con Sumire.[n]夷Quieres volver?[n][w][e]

[msg ASAKUSA_COMMON_008 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la[n][clr 2]Skytree[clr 27] de [clr 2]Asakusa[clr 27] con Sumire.[n]夷Quieres volver?[n][w][e]

[msg JINBOUTYOU_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Jinbocho[clr 27]? All胤 est茨[n][clr 2]La ciudad de los libros[clr 27]. 夷Quieres ir?[n][w][e]

[msg JINBOUTYOU_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]夷Jinbocho[clr 27]? All胤 est茨 [clr 2]La ciudad[n]de los libros[clr 27], pero hoy hace[n]mal tiempo. Vayamos a otro sitio.[n][w][e]

[msg JINBOUTYOU_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]La ciudad de[n]los libros[clr 27] de [clr 2]Jinbocho[clr 27][n]con Ryuji. 夷Quieres volver?[n][w][e]

[msg JINBOUTYOU_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]La ciudad de[n]los libros[clr 27] de [clr 2]Jinbocho[clr 27] con[n]la se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg JINBOUTYOU_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]La ciudad de[n]los libros[clr 27] de [clr 2]Jinbocho[clr 27][n]con Yusuke. 夷Quieres volver?[n][w][e]

[msg JINBOUTYOU_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]La ciudad de[n]los libros[clr 27] de [clr 2]Jinbocho[clr 27][n]con Makoto. 夷Quieres volver?[n][w][e]

[msg JINBOUTYOU_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]La ciudad de[n]los libros[clr 27] de [clr 2]Jinbocho[clr 27][n]con Futaba. 夷Quieres volver?[n][w][e]

[msg JINBOUTYOU_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]La ciudad de[n]los libros[clr 27] de [clr 2]Jinbocho[clr 27][n]con Haru. 夷Quieres volver?[n][w][e]

[msg ODAIBA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]El Parque Seaside[clr 27] de Odaiba?[n]All胤 hay una [clr 2]noria[clr 27]. 夷Quieres ir?[n][w][e]

[msg ODAIBA_COMMON_999 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Odaiba[clr 27]? Ah胤 est茨[n]el [clr 2]Parque Seaside[clr 27]. 夷Quieres ir?[n][w][e]

[msg ODAIBA_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]夷Odaiba[clr 27]? All胤 est茨 el [clr 2]Parque[n]Seaside[clr 27], pero hoy hace[n]muy mal tiempo. Vamos a otro sitio.[n][w][e]

[msg ODAIBA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido a la [clr 2]noria[clr 27] del [clr 2]Parque[n]Seaside de Odaiba[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg ODAIBA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido a la [clr 2]noria[clr 27] del [clr 2]Parque[n]Seaside de Odaiba[clr 27] con la[n]se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg ODAIBA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido a la [clr 2]noria[clr 27] del [clr 2]Parque[n]Seaside de Odaiba[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg ODAIBA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido a la [clr 2]noria[clr 27] del [clr 2]Parque[n]Seaside de Odaiba[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg ODAIBA_COMMON_014 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]Parque Seaside[clr 27][n]de [clr 2]Odaiba[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg ODAIBA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido a la [clr 2]noria[clr 27] del [clr 2]Parque[n]Seaside de Odaiba[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg ODAIBA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido a la [clr 2]noria[clr 27] del [clr 2]Parque[n]Seaside de Odaiba[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg ODAIBA_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido a la [clr 2]noria[clr 27] del [clr 2]Parque[n]Seaside de Odaiba[clr 27] con Yoshizawa.[n]夷Quieres volver?[n][w][e]

[msg YOKOHAMA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Motomachi[clr 27]? All胤 est茨[n][clr 2]Chinatown[clr 27]. 夷Quieres ir?[n][w][e]

[msg YOKOHAMA_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]夷Motomachi[clr 27]? All胤 est茨[n][clr 2]Chinatown[clr 27], pero hoy no hace[n]buen tiempo. Vamos a otra parte.[n][w][e]

[msg YOKOHAMA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Chinatown[clr 27],[n]que est茨 en [clr 2]Motomachi,[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg YOKOHAMA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Chinatown[clr 27],[n]que est茨 en [clr 2]Motomachi,[clr 27] con la[n]se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg YOKOHAMA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Chinatown[clr 27],[n]que est茨 en [clr 2]Motomachi,[clr 27][n]con Yusuke. 夷Quieres volver?[n][w][e]

[msg YOKOHAMA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Chinatown[clr 27],[n]que est茨 en [clr 2]Motomachi,[clr 27][n]con Makoto. 夷Quieres volver?[n][w][e]

[msg YOKOHAMA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Chinatown[clr 27],[n]que est茨 en [clr 2]Motomachi[clr 27],[n]con Futaba. 夷Quieres volver?[n][w][e]

[msg YOKOHAMA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Chinatown[clr 27],[n]que est茨 en [clr 2]Motomachi[clr 27], con Haru.[n]夷Quieres volver?[n][w][e]

[msg MIURAKAIGAN_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Miura[clr 27]?[n]All胤 hay una [clr 2]playa[clr 27]. 夷Quieres ir?[n][w][e]

[msg MAIHAMA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Maihama[clr 27]?[n]All胤 est茨 [clr 2]Destinyland[clr 27]. 夷Quieres ir?[n][w][e]

[msg MAIHAMA_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]夷Maihama[clr 27]? All胤 est茨[n][clr 2]Destinyland[clr 27], pero hoy el tiempo[n]no pinta nada bien.[n][w][e]

[msg MAIHAMA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Destinyland[clr 27],[n]que est茨 en [clr 2]Maihama[clr 27], con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg MAIHAMA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Destinyland[clr 27],[n]que est茨 en [clr 2]Maihama[clr 27], con la[n]se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg MAIHAMA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Destinyland[clr 27],[n]que est茨 en [clr 2]Maihama[clr 27], con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg MAIHAMA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Destinyland[clr 27],[n]que est茨 en [clr 2]Maihama[clr 27], con Makoto.[n]夷Quieres volver?[n][w][e]

[msg MAIHAMA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Destinyland[clr 27],[n]que est茨 en [clr 2]Maihama[clr 27], con Futaba.[n]夷Quieres volver?[n][w][e]

[msg MAIHAMA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Destinyland[clr 27],[n]que est茨 en [clr 2]Maihama[clr 27], con Haru.[n]夷Quieres volver?[n][w][e]

[msg MAIHAMA_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en [clr 2]Destinyland[clr 27],[n]que est茨 en [clr 2]Maihama[clr 27], con Sumire.[n]夷Quieres volver?[n][w][e]

[msg MEIJIJINGU_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]El Santuario Meiji[clr 27]?[n]All胤 se va a [clr 2]rezar[clr 27]. 夷Quieres ir?[n][w][e]

[msg MEIJIJINGU_BAD_WEATHER [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]夷El Santuario Meiji[clr 27]?[n]All胤 se va a [clr 2]rezar[clr 27], pero hoy hace[n]muy mal tiempo. Vamos a otro sitio.[n][w][e]

[msg MEIJIJINGU_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has [clr 2]rezado[clr 27] en el[n][clr 2]Santuario Meiji[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg MEIJIJINGU_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has [clr 2]rezado[clr 27] en el[n][clr 2]Santuario Meiji[clr 27] con[n]la se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg MEIJIJINGU_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has [clr 2]rezado[clr 27] en el[n][clr 2]Santuario Meiji[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg MEIJIJINGU_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has [clr 2]rezado[clr 27] en el[n][clr 2]Santuario Meiji[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg MEIJIJINGU_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has [clr 2]rezado[clr 27] en el[n][clr 2]Santuario Meiji[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg MEIJIJINGU_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has [clr 2]rezado[clr 27] en el[n][clr 2]Santuario Meiji[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg MEIJIJINGU_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has [clr 2]rezado[clr 27] en el[n][clr 2]Santuario Meiji[clr 27] con Kasumi.[n]夷Quieres volver?[n][w][e]

[msg MEIJIJINGU_COMMON_008 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has [clr 2]rezado[clr 27] en el[n][clr 2]Santuario Meiji[clr 27] con Sumire.[n]夷Quieres volver?[n][w][e]

[msg SHIBUYA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][clr 2]夷Shibuya?[clr 27] Ah胤 est茨[n]el [clr 2]bufet Wilton[clr 27]. 夷Quieres ir?[n][w][e]

[msg SHIBUYA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]bufet Wilton[clr 27][n]de [clr 2]Shibuya[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg SHIBUYA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]bufet Wilton[clr 27][n]de [clr 2]Shibuya[clr 27] con la se隠orita Ann.[n]夷Quieres volver?[n][w][e]

[msg SHIBUYA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]bufet Wilton[clr 27][n]de [clr 2]Shibuya[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg SHIBUYA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]bufet Wilton[clr 27][n]de [clr 2]Shibuya[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg SHIBUYA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]bufet Wilton[clr 27][n]de [clr 2]Shibuya[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg SHIBUYA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]bufet Wilton[clr 27][n]de [clr 2]Shibuya[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg YONCHA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷Quieres que vayamos[n]a [clr 2]tu casa[clr 27] juntos?[n][w][e]

[msg SINAGAWA_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Shinagawa[clr 27]? Ah胤 est茨[n][clr 2]el acuario[clr 27]. 夷Quieres ir?[n][w][e]

[msg SINAGAWA_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido al [clr 2]acuario[clr 27] de[n][clr 2]Shinagawa[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg SINAGAWA_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido al [clr 2]acuario[clr 27] de[n][clr 2]Shinagawa[clr 27] con la se隠orita Ann.[n]夷Quieres volver?[n][w][e]

[msg SINAGAWA_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido al [clr 2]acuario[clr 27] de[n][clr 2]Shinagawa[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg SINAGAWA_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido al [clr 2]acuario[clr 27] de[n][clr 2]Shinagawa[clr 27] con Makoto.[n]夷Quieres volver?[n][w][e]

[msg SINAGAWA_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido al [clr 2]acuario[clr 27] de[n][clr 2]Shinagawa[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg SINAGAWA_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido al [clr 2]acuario[clr 27] de[n][clr 2]Shinagawa[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg SINAGAWA_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido al [clr 2]acuario[clr 27] de[n][clr 2]Shinagawa[clr 27] con Yoshizawa.[n]夷Quieres volver?[n][w][e]

[msg SINAGAWA_COMMON_008 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has ido al [clr 2]acuario[clr 27] de[n][clr 2]Shinagawa[clr 27] con Sumire.[n]夷Quieres volver?[n][w][e]

[msg NAKANO_COMMON_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷[clr 2]Nakano[clr 27]? Ah胤 est茨[n][clr 2]la zona comercial[clr 27]. 夷Quieres ir?[n][w][e]

[msg NAKANO_COMMON_001 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]zona[n]comercial[clr 27] de [clr 2]Nakano[clr 27] con Ryuji.[n]夷Quieres volver?[n][w][e]

[msg NAKANO_COMMON_002 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]zona[n]comercial[clr 27] de [clr 2]Nakano[clr 27] con[n]la se隠orita Ann. 夷Quieres volver?[n][w][e]

[msg NAKANO_COMMON_003 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]zona[n]comercial[clr 27] de [clr 2]Nakano[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg NAKANO_COMMON_004 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en la [clr 2]zona[n]comercial[clr 27] de [clr 2]Nakano[clr 27] con Yusuke.[n]夷Quieres volver?[n][w][e]

[msg NAKANO_COMMON_005 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]distrito[n]comercial[clr 27] de [clr 2]Nakano[clr 27] con Futaba.[n]夷Quieres volver?[n][w][e]

[msg NAKANO_COMMON_006 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]distrito[n]comercial[clr 27] de [clr 2]Nakano[clr 27] con Haru.[n]夷Quieres volver?[n][w][e]

[msg NAKANO_COMMON_007 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]distrito[n]comercial[clr 27] de [clr 2]Nakano[clr 27] con Yoshizawa.[n]夷Quieres volver?[n][w][e]

[msg NAKANO_COMMON_008 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ya has estado en el [clr 2]distrito[n]comercial[clr 27] de [clr 2]Nakano[clr 27] con Sumire.[n]夷Quieres volver?[n][w][e]

[msg MSG_SPOT_DUMMY [Morgana]]
[s]Dummy MSG_SPOT_DUMMY[n][w][e]

[msg MSG_RYUJI_SPOT_OGIKUBO [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 0 65535 0]Ah, 夷al sitio este del ramen?[n]Claro, tengo much胤sima hambre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]斡Venga, a mover el culo![n][w][e]

[msg MSG_RYUJI_SPOT_OGIKUBO_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]Te encanta el ramen, 夷eh?[n]Vale, 斡vamos![n][w][e]

[msg MSG_RYUJI_SPOT_TUKISHIMA [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]Ah, 夷quieres ir al restaurante[n]de monjayaki? Ya se me est茨[n]haciendo la boca agua.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]斡Venga, a mover el culo![n][w][e]

[msg MSG_RYUJI_SPOT_TUKISHIMA_2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]El monjayaki es mejor cuando[n]te quema el paladar.[n]Venga, 斡vamos![n][w][e]

[msg MSG_RYUJI_SPOT_AKIHABARA [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]夷La tienda de electr吋nica?[n]Mola que no veas. 斡Vamos a ver[n]las m茨quinas de musculaci吋n![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]斡Venga, a mover el culo![n][w][e]

[msg MSG_RYUJI_SPOT_AKIHABARA_2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]夷No es un poco raro que uno[n]mire chismes que no puedo permitirse?[n]Bueno, 斡vamos![n][w][e]

[msg MSG_RYUJI_SPOT_SUIDOUBAS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]夷Ah胤 no van las parejas?[n]Bueno, mientras que mole...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]Vale, vamos. 斡Conquistaremos[n]la monta隠a rusa![n][w][e]

[msg MSG_RYUJI_SPOT_SUIDOUBAS_2 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]Genial, 斡hoy vamos a pasarlo[n]de lujo! 斡En marcha![n][w][e]

[msg MSG_RYUJI_SPOT_YOKOHAMA [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]Chachi, me apunto al bufet libre[n]de comida china.[n]Vamos a ponernos morados, t胤o.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]斡Venga, a mover el culo![n][w][e]

[msg MSG_RYUJI_SPOT_YOKOHAMA_ [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]斡Nunca me cansar姻 de ir![n]斡Vamos![n][w][e]

[msg MSG_RYUJI_SPOT_NAKANO [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10]夷Nakano...? Podemos echarle[n]un vistazo, s胤.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 7051 65535 0]Vale, 斡vamos![n][w][e]

[msg MSG_RYUJI_SPOT_NAKANO_02 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 23 1 207 32 10 31 10][vp 8 2 1 7052 65535 0]斡Nunca me cansar姻 de ir![n]斡Vamos![n][w][e]

[msg MSG_ANNE_SPOT_INOKASIRA [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]夷Al Parque Inokashira? Vale.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]A m胤 tambi姻n me gusta. 斡Vamos![n][w][e]

[msg MSG_ANNE_SPOT_INOKASIRA_ [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]S胤, me parece bien que vayamos[n]al Parque Inokashira. 斡Venga![n][w][e]

[msg MSG_ANNE_SPOT_HARAJUKU [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]A Harajuku... 夷Y qu姻 tal la calle[n]Takenoko? Me encantar胤a[n]que vinieses de compras conmigo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]Simplemente ir all胤 y observar[n]a la gente es interesante.[n]斡Venga, vamos![n][w][e]

[msg MSG_ANNE_SPOT_HARAJUKU_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]Vale, me parece bien que vayamos[n]a la calle Takenoko.[n][w][e]

[msg MSG_ANNE_SPOT_IKEBUKURO [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]斡Llevo a隠os queriendo ir al[n]planetario! Adem茨s, Ikebukuro[n]no est茨 muy lejos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]斡Vamos![n][w][e]

[msg MSG_ANNE_SPOT_IKEBUKURO_ [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]S胤, vamos.[n]El planetario es genial.[n][w][e]

[msg MSG_ANNE_SPOT_BUFFET [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]夷Al bufet al que fuimos antes?[n]Pero no dejes que me atiborre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]斡Vamos![n][w][e]

[msg MSG_ANNE_SPOT_BUFFET_02 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]Me parece bien, pero 斡no dejes[n]que me atiborre![n][w][e]

[msg MSG_ANNE_SPOT_MAIHAMA [Ann]]
[s][bup 0 4 6 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]Hala, 夷en serio? 斡Qu姻 bien[n]que lo hayas dicho! 斡Vamos[n]a pasarlo genial![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]斡Vamos![n][w][e]

[msg MSG_ANNE_SPOT_MAIHAMA_02 [Ann]]
[s][bup 0 4 6 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]斡Claro que s胤! 斡Disfrutar姻[n]al m茨ximo de la excursi吋n![n][w][e]

[msg MSG_ANNE_SPOT_KANRANSYA [Ann]]
[s][bup 0 4 6 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]S胤, me parece bien que subamos a la[n]noria. Me apetece pasar[n]un rato a solas contigo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]斡Vamos![n][w][e]

[msg MSG_ANNE_SPOT_KANRANSYA_ [Ann]]
[s][bup 0 4 6 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]斡S胤, vamos! Las vistas desde arriba[n]son espectaculares. Me encantar胤a[n]volver a subir.[n][w][e]

[msg MSG_ANNE_SPOT_UENO [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10]夷Al museo de arte? S胤, claro.[n]Seguro que aprendo algo[n]雨til para mi carrera como modelo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 6052 65535 0]斡Vamos![n][w][e]

[msg MSG_ANNE_SPOT_UENO_02 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 226 14 10 13 10][f 4 23 1 206 3 10 0 10][vp 8 2 1 6023 65535 0]S胤, me vendr茨 de perlas para[n]estudiar. 斡Vamos![n][w][e]

[msg MSG_YUSUKE_SPOT_OGIKUBO [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]夷Quieres comer ramen en Ogikubo?[n]Ya empezaba a tener hambre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Salgamos de inmediato.[n][w][e]

[msg MSG_YUSUKE_SPOT_OGIKUBO_ [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]Mm... Estaba pensando en que[n]me apetec胤a comer eso. Vamos.[n][w][e]

[msg MSG_YUSUKE_SPOT_UENO [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]Ah, s胤, observar la obra[n]de los maestros...[n]Qu姻 idea tan interesante.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Vale, pues vamos.[n][w][e]

[msg MSG_YUSUKE_SPOT_UENO_02 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]S胤, as胤 estudiaremos[n]a los grandes cl茨sicos.[n][w][e]

[msg MSG_YUSUKE_SPOT_IKEBUKUR [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 204 3 10 0 10]El planetario, 夷eh?[n]All胤 aprender姻 cosas nuevas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Vamos, [f 4 2].[n][w][e]

[msg MSG_YUSUKE_SPOT_IKEBUKUR_2 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]Muy bien. Las estrellas me inspiran[n]much胤simo art胤sticamente.[n]Vamos para all茨.[n][w][e]

[msg MSG_YUSUKE_SPOT_JINBO [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]Ah, 夷crees que podremos[n]buscar libros de arte?[n]Espero que haya alguno bueno.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Salgamos de inmediato.[n][w][e]

[msg MSG_YUSUKE_SPOT_JINBO_02 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]夷Quieres buscar la joya oculta que[n]es un libro de arte maravilloso?[n]Muy bien, salgamos.[n][w][e]

[msg MSG_YUSUKE_SPOT_MEIJIJIN [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]Un santuario, 夷eh? Disfrutar de[n]la cultura tradicional est茨 bien.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Vamos, cuento con que sabes llegar.[n][w][e]

[msg MSG_YUSUKE_SPOT_MEIJIJIN_2 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]Me apetece mucho ir al santuario[n]a meditar otra vez. Vamos.[n][w][e]

[msg MSG_YUSUKE_SPOT_SINAGAWA [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10]Un acuario... Vayamos[n]a admirar los delicados[n]movimientos de los peces.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 4059 65535 0]Vamos, cuento con que sabes llegar.[n][w][e]

[msg MSG_YUSUKE_SPOT_SINAGAWA_2 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 204 3 10 0 10][vp 8 2 1 4060 65535 0]Tal vez pueda crear un nuevo cuadro[n]en mi cabeza a trav姻s[n]de la observaci吋n. En marcha.[n][w][e]

[msg MSG_MAKOTO_SPOT_OGIKUBO [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]Mmm, hace mucho que no voy[n]a un restaurante de ramen.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Estar胤a bien volver.[n]Dime d吋nde est茨, por favor.[n][w][e]

[msg MSG_MAKOTO_SPOT_OGIKUBO_ [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Claro. El sabor del ramen[n]es adictivo, la verdad.[n][w][e]

[msg MSG_MAKOTO_SPOT_TUKISIMA [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]Nunca he probado[n]el monjayaki, pero tengo curiosidad.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]夷Vamos, [f 4 2]?[n][w][e]

[msg MSG_MAKOTO_SPOT_TUKISIMA_2 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Claro. Podemos pensar[n]en lo que vamos a comer de camino.[n][w][e]

[msg MSG_MAKOTO_SPOT_HARAJUKU [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]Nunca he ido a la calle[n]Takenoko... Es la ocasi吋n perfecta[n]para vivir algo nuevo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Te sigo.[n][w][e]

[msg MSG_MAKOTO_SPOT_HARAJUKU_2 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Sigo con ganas de ir. Vamos.[n][w][e]

[msg MSG_MAKOTO_SPOT_SUIDOUBA [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 202 3 10 0 10]He o胤do hablar de[n]Dome Town, pero nunca he ido.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Venga, ll姻vame.[n][w][e]

[msg MSG_MAKOTO_SPOT_SUIDOUBA_2 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Claro, ir姻 tantas veces[n]como me lo pidas. Vamos.[n][w][e]

[msg MSG_MAKOTO_SPOT_YOKOHAMA [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]Buena idea. La verdad es que[n]ya ten胤a ganas de ir.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Andando.[n][w][e]

[msg MSG_MAKOTO_SPOT_YOKOHAMA_2 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]All胤 me siento como si fuese[n]forastera. Vamos.[n][w][e]

[msg MSG_MAKOTO_SPOT_MAIHAMA [Makoto]]
[s][bup 0 6 6 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]Je, je, estoy segura de que ir[n]ser茨 muy divertido. Disfrutemos[n]de un buen d胤a al aire libre.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Deber胤amos ir tirando.[n][w][e]

[msg MSG_MAKOTO_SPOT_MAIHAMA_ [Makoto]]
[s][bup 0 6 6 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Claro, me encantar胤a relajarme[n]contigo en el reino de los sue隠os.[n][w][e]

[msg MSG_MAKOTO_SPOT_KANRANSY [Makoto]]
[s][bup 0 6 6 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]Creo que nunca he montado[n]en la noria... Estoy nerviosa.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Bueno, 夷vamos?[n][w][e]

[msg MSG_MAKOTO_SPOT_KANRANSY_2 [Makoto]]
[s][bup 0 6 6 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]Qu姻 buena idea.[n]Me encantar胤a volver a disfrutar[n]de las vistas contigo, [f 4 2].[n][w][e]

[msg MSG_MAKOTO_SPOT_ODAIBA [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10]No s姻 mucho sobre Odaiba,[n]pero pinta bien.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 2118 65535 0]Vamos.[n][w][e]

[msg MSG_MAKOTO_SPOT_ODAIBA_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 202 3 10 0 10][vp 8 2 1 2051 65535 0]S胤, las vistas eran maravillosas.[n]Andando.[n][w][e]

[msg MSG_FUTABA_SPOT_ASAKUSA_ [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 209 3 10 0 10]夷A la Skytree? 斡Vale![n]Me gustan los lugares altos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]Dime c吋mo se llega, [f 4 2].[n][w][e]

[msg MSG_FUTABA_SPOT_ASAKUSA__2 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]Las vistas la 雨ltima vez[n]fueron flipantes. Ir姻 contigo.[n][w][e]

[msg MSG_FUTABA_SPOT_ASAKUSA__3 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]Es un lugar tur胤stico famoso,[n]夷verdad? 夷C吋mo ser茨?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]Venga, vamos.[n][w][e]

[msg MSG_FUTABA_SPOT_ASAKUSA__4 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]斡Vale! 斡Voy a comer toda[n]la comida que tengan![n][w][e]

[msg MSG_FUTABA_SPOT_HARAJUKU [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]斡夷La calle Takenoko?![n][w][e]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]N-no, vale... 斡Vamos![n][w][e]

[msg MSG_FUTABA_SPOT_HARAJUKU_2 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]La calle Takenoko...[n]S胤, s胤, vale. Vamos.[n][w][e]

[msg MSG_FUTABA_SPOT_AKIHABAR [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]斡A-A-Akihabara es la ca隠a![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]斡Qu姻 contenta estoy![n]斡Nos lo pasaremos genial! 斡Vamos![n][w][e]

[msg MSG_FUTABA_SPOT_AKIHABAR_2 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]斡Akihabara me parece guay![n]斡Hay cosas que quiero ver![n][w][e]

[msg MSG_FUTABA_SPOT_INOKASIR [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]Es un parque, 夷no?[n]Los lugares tranquilos est茨n bien.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]Me apunto. 斡Vamos![n][w][e]

[msg MSG_FUTABA_SPOT_INOKASIR_2 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]Es un sitio muy relajante.[n]Ir姻 encantada contigo.[n][w][e]

[msg MSG_FUTABA_SPOT_KANRANSY [Futaba]]
[s][bup 0 8 6 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]夷Solos en la noria?[n]Sin problema. Es m茨s, creo[n]que me gustar胤a mucho.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]斡Vamos! 斡Voy a ser[n]una novia estupenda![n][w][e]

[msg MSG_FUTABA_SPOT_KANRANSY_2 [Futaba]]
[s][bup 0 8 6 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]Claro que s胤.[n]Estaremos solos en la noria.[n][w][e]

[msg MSG_FUTABA_SPOT_YOKOHAMA [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]斡夷Chinatown?! V-vale...[n]All胤 hablan japon姻s, 夷no?[n][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]P-pero ir姻. 斡Estoy muy animada![n][w][e]

[msg MSG_FUTABA_SPOT_YOKOHAMA_2 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]Quiero explorar Chinatown un poco[n]m茨s... Ir姻 contigo.[n][w][e]

[msg MSG_FUTABA_SPOT_MAIHAMA [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]Uf, ah胤 hay much胤sima[n]gente, 夷no?[n][w][e]
[s][bup 0 8 6 65535 0][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]Pero 斡solo si vamos en una cita![n][w][e]

[msg MSG_FUTABA_SPOT_MAIHAMA_ [Futaba]]
[s][bup 0 8 6 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]斡S胤, quiero ir! 斡Las multitudes[n]no son nada para m胤[n]cuando estamos juntos![n][w][e]

[msg MSG_FUTABA_SPOT_NAKANO [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10]斡Oh, Nakano! 斡Mi para胤so![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 9069 65535 0]斡Qu姻 contenta estoy![n]斡Nos lo pasaremos genial! 斡Vamos![n][w][e]

[msg MSG_FUTABA_SPOT_NAKANO_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 23 1 209 3 10 0 10][vp 8 2 1 9070 65535 0]斡Nakano me parece genial![n]Hay algo all胤 que quiero ver.[n][w][e]

[msg MSG_HARU_SPOT_OGIKUBO [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]El ramen de Ogikubo es famoso, 夷no?[n]Siempre he querido probarlo.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]Vale, pues vamos para all茨.[n][w][e]

[msg MSG_HARU_SPOT_OGIKUBO_02 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Claro, me encantar胤a comerlo[n]de nuevo. Vamos, [f 4 2].[n][w][e]

[msg MSG_HARU_SPOT_TUKISHIMA [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]夷Monjayaki? Creo que nunca[n]lo he probado.[n][w][e]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]夷A qu姻 sabe?[n]斡Hora de descubrirlo![n][w][e]

[msg MSG_HARU_SPOT_TUKISHIMA_ [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Claro. 斡Me gustar胤a intentar[n]cocinarlo! Vamos.[n][w][e]

[msg MSG_HARU_SPOT_HARAJUKU [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]夷La calle Takenoko?[n]S胤, me apetece dar una vuelta.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]Vale, pues vamos para all茨.[n][w][e]

[msg MSG_HARU_SPOT_HARAJUKU_0 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Claro, vamos. De hecho, hay[n]una tienda a la que quer胤a ir.[n][w][e]

[msg MSG_HARU_SPOT_AKIHABARA [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]夷Una tienda de electr吋nica?[n]Estoy ansiosa por ver[n]qu姻 tienen por all胤.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]Vale, pues vamos para all茨.[n][w][e]

[msg MSG_HARU_SPOT_AKIHABARA_ [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Claro. Ir y echar un vistazo[n]ya es divertido, 夷no?[n][w][e]

[msg MSG_HARU_SPOT_GINZA [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]Ah, 夷al que hay en Ginza?[n]Me encanta el sushi que tienen.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]Vale, pues vamos para all茨.[n][w][e]

[msg MSG_HARU_SPOT_GINZA_02 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]S胤, las gambas est茨n para morirse.[n]Vamos.[n][w][e]

[msg MSG_HARU_SPOT_MAIHAMA [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]Ah, 斡me alegro de que me lo pidas![n]Hoy tenemos el d胤a libre[n]y podemos ir con calma y divertirnos.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]Vale, pues vamos para all茨.[n][w][e]

[msg MSG_HARU_SPOT_MAIHAMA_02 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]斡Viva! 斡Daremos una vuelta[n]y lo veremos todo![n][w][e]

[msg MSG_HARU_SPOT_KANRANSYA [Haru]]
[s][bup 0 7 206 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]Me da un poco de verg鵜enza[n]estar a solas en la noria[n]contigo, pero no me importa.[n][w][e]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]Mmm... Vamos.[n][w][e]

[msg MSG_HARU_SPOT_KANRANSYA_ [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Claro, ten胤a ganas de volver[n]a subir a la noria contigo.[n]Vamos, [f 4 2].[n][w][e]

[msg MSG_HARU_SPOT_MEIJIJINGU [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10]Siempre he querido echar[n]un vistazo.[n]El altar es maravilloso.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 3051 65535 0]Vale, pues vamos para all茨.[n][w][e]

[msg MSG_HARU_SPOT_MEIJIJINGU_2 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 4 23 1 203 3 10 0 10][vp 8 2 1 3052 65535 0]Hay historia en cada rinc吋n.[n]Bueno, vamos.[n][w][e]

[msg MSG_KASUMI_SPOT_MEIJIJIN [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Suena estupendo![n]Es bueno rezar de vez en cuando.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57087 65535 0]夷Nos vamos?[n][w][e]

[msg MSG_SUMIRE_SPOT_MEIJIJIN [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Qu姻 gran idea! Siempre voy[n]a rezar cuando se avecina[n]algo importante.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57087 65535 0]斡Vamos![n][w][e]

[msg MSG_KASUMI_SPOT_MEIJIJIN_2 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Vale! Me he encontrado[n]mucho mejor desde la 雨ltima[n]vez que rec姻 all胤.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57087 65535 0]夷Nos vamos?[n][w][e]

[msg MSG_SUMIRE_SPOT_MEIJIJIN_2 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Me parece genial! Seguro[n]que los dioses y diosas volver茨n[n]a escuchar nuestras plegarias.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57087 65535 0]斡Vamos![n][w][e]

[msg MSG_KASUMI_SPOT_SKYTREE [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57086 65535 0]斡Qu姻 ganas de subir![n]Puede que no lo parezca, pero[n]斡me encantan las alturas![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Nos vamos?[n][w][e]

[msg MSG_SUMIRE_SPOT_SKYTREE [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57086 65535 0]斡Mira ese edificio tan alto![n]Me encantan las alturas.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Vamos![n][w][e]

[msg MSG_KASUMI_SPOT_SKYTREE_ [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Suena muy bien! 斡Tengo ganas[n]de contemplar las vistas[n]desde las alturas de nuevo![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]斡Vamos para all茨![n][w][e]

[msg MSG_SUMIRE_SPOT_SKYTREE_ [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Las vistas desde aqu胤[n]son magn胤ficas.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57069 65535 0]斡Vamos![n][w][e]

[msg MSG_KASUMI_SPOT_INOKASHI [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57086 65535 0]斡Genial! 斡Me encanta ese sitio![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Vamos![n][w][e]

[msg MSG_SUMIRE_SPOT_INOKASHI [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57086 65535 0]Me encantan los barcos. Tambi姻n[n]son buenos para practicar[n]el equilibrio.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Vamos![n][w][e]

[msg MSG_KASUMI_SPOT_INOKASHI_2 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Claro! Rode姻monos de naturaleza.[n]斡Me vendr茨 bien esa energ胤a![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]斡Vamos![n][w][e]

[msg MSG_SUMIRE_SPOT_INOKASHI_2 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]夷Vamos a volver a montar en barco?[n]斡Me alegro de que te acuerdes[n]de que me gusta![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]斡Muy bien! 斡Vamos para all茨![n][w][e]

[msg MSG_KASUMI_SPOT_YOKOHAMA [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Nunca he ido![n]斡Quiero visitar cada tienda![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]斡Vamos, deprisa![n][w][e]

[msg MSG_SUMIRE_SPOT_YOKOHAMA [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Ser茨 la primera vez que vaya.[n]夷Podremos ir a todas las tiendas?[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]Y ahora, vamos.[n][w][e]

[msg MSG_KASUMI_SPOT_YOKOHAMA_2 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Tengo antojo de comida china![n]Esta vez vamos a pasar[n]por todas las tiendas.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]斡Vamos![n][w][e]

[msg MSG_SUMIRE_SPOT_YOKOHAMA_2 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Llevo todo el d胤a con ganas[n]de comida china. 斡Esta vez hay que[n]ir a todas las tiendas![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]斡Vamos![n][w][e]

[msg MSG_KASUMI_SPOT_SHINAGAW [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Me encantan los acuarios![n]Espero que haya ping鵜inos...[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]斡Vamos![n][w][e]

[msg MSG_SUMIRE_SPOT_SHINAGAW [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Los acuarios son lo mejor![n]夷Veremos alg雨n ping鵜ino?[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57067 65535 0]斡Vamos ya! 斡Venga![n][w][e]

[msg MSG_KASUMI_SPOT_SHINAGAW_2 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Hace poco vi por la tele[n]un especial sobre calamares, y[n]llevo queriendo ir desde entonces.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]斡Vamos![n][w][e]

[msg MSG_SUMIRE_SPOT_SHINAGAW_2 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Llevo queriendo ir desde que[n]hace un tiempo vi por la tele[n]un especial sobre calamares![n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57068 65535 0]斡Vamos![n][w][e]

[msg MSG_SUMIRE_SPOT_MAIHAMA [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]斡Quiero subirme a las atracciones[n]m茨s fuertes! Si estoy contigo,[n]todo ir茨 bien.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57093 65535 0]斡D姻monos prisa, venga![n][w][e]

[msg MSG_SUMIRE_SPOT_MAIHAMA_ [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Pasar tiempo con mi novio[n]en la tierra de los sue隠os...[n]Esta vez vayamos con calma.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57093 65535 0]Vayamos ahora.[n][w][e]

[msg MSG_SUMIRE_SPOT_ODAIBA [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57058 65535 0]Ha pasado tanto tiempo desde[n]la 雨ltima vez que sub胤 a una noria.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Venga, date prisa![n][w][e]

[msg MSG_SUMIRE_SPOT_ODAIBA_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 57076 65535 0]Estoy muy contenta de montar[n]en la Noria de nuevo contigo.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Venga, vamos.[n][w][e]

[msg MSG_SUMIRE_SPOT_MYROOM [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Si estoy contigo, hasta sentarse[n]y charlar es divertido.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57093 65535 0]Vamos.[n][w][e]

[msg MSG_SUMIRE_SPOT_MYROOM_0 [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 23 1 222 3 10 0 10][vp 8 2 1 0 65535 0]Tu habitaci吋n huele a caf姻.[n]Me encanta.[n][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57093 65535 0]Vamos all茨.[n][w][e]

[msg MSG_MONEY_SHORTAGE_FARE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Mm, no tienes suficiente dinero.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hacer planes es importante[n]para ser un buen ladr吋n.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]En fin, usar姻 mis ahorros[n]para pagarte el viaje de vuelta.[n][w][e]

[msg MND_MONEY_SHORTAGE_FARE]
[s]No tengo suficiente dinero[n]para el tren.[n][w][e]
[s]Ah, s胤...[n][w][e]
[s]Morgana me dio parte[n]de sus ahorros. Deber胤a[n]tener cuidado con lo que gasto.[n][e]

[msg MSG_NO_MONEY]
[s]No tengo suficiente dinero[n]para el viaje de vuelta.[n][w][e]

[msg MSG_ERROR_DISABLE_KF [Morgana]]
[s]No tengo ning雨n motivo[n]para ir all胤 ahora mismo.[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT [Morgana]]
[s]Deber胤a volver con alguien...[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_R [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7085 65535 0]No s姻, no est茨 mal, pero...[n]deber胤amos ir a otro sitio.[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_A [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6032 65535 0]Eh... Perdona, pero 夷podemos ir[n]a otro sitio?[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_Y [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4111 65535 0]No me interesa en absoluto...[n]Lo siento, pero 夷te importa[n]que vayamos a otro sitio?[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_M [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2128 65535 0]Bueno, gracias por la propuesta,[n]pero 夷no se te ocurre[n]otro sitio al que podamos ir?[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_F [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9113 65535 0]夷Te importa si no vamos ah胤?[n]Yo prefiero ir a otro sitio.[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_H [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 3032 65535 0]Oye, espero que no te moleste,[n]pero, ya que estamos juntos,[n]preferir胤a ir a otro lugar.[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_K [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57037 65535 0]Lo siento, pero 夷podr胤amos ir[n]a otro lado?[n][w][e]

[msg MSG_ERROR_DISABLE_SPOT_S [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 57037 65535 0]Lo siento, pero[n]夷te importar胤a ir a otro lado?[n][w][e]

[msg MSG_ERROR_SPOT_SHIBUYA]
[s]Aqu胤 es donde fuimos a aquel bufet.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_YONCHA]
[s]Es pronto para volver a Leblanc.[n][w][e]

[msg MSG_ERROR_SPOT_AOYAMA]
[s]No tengo motivos para[n]ir al instituto ahora mismo.[n][w][e]

[msg MSG_ERROR_SPOT_SHINJUKU]
[s]No tengo motivos para[n]ir a Shinjuku ahora mismo.[n][w][e]

[msg MSG_ERROR_SPOT_AKIBA]
[s]Hay una tienda de electr吋nica[n]enorme al lado de la estaci吋n.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_KANDA]
[s]Ahora mismo, no tengo nada[n]que hacer en Kanda.[n][w][e]

[msg MSG_ERROR_SPOT_KANDA_NIG]
[s]Ahora mismo, no tengo nada que[n]hacer en Kanda.[n]Deber胤a volver de d胤a.[n][w][e]

[msg MSG_ERROR_SPOT_HARAJYUKU]
[s]La calle Takenoko est茨[n]al lado de la estaci吋n.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_IKEBUKURO]
[s]Conozco un planetario[n]cerca de la estaci吋n.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_AKIBA_SPO]
[s]Hay una tienda de electr吋nica[n]enorme al lado de la estaci吋n.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_UENO]
[s]Hay muchos museos de arte[n]cerca de la estaci吋n.[n]Deber胤a visitarlos con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_OGIKUBO]
[s]La estaci吋n est茨 cerca de un buen[n]restaurante de ramen.[n]Deber胤a ir a comer con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_ICHIGAYA]
[s]Hay un estanque[n]al lado de la estaci吋n.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_INOKASIRA]
[s]Aqu胤 est茨 el Parque Inokashira.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_NAGATACHO]
[s]El Edificio de la Dieta est茨[n]al lado de la estaci吋n, pero ahora[n]no tengo motivos para ir...[n][w][e]

[msg MSG_ERROR_SPOT_GINZA]
[s]Conozco un restaurante elegante de[n]sushi por aqu胤 cerca.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_ASAKUSA]
[s]La Skytree y la calle Nakamise[n]est茨n muy cerca.[n]Deber胤a ir con alguien.[n][w][e]

[msg MSG_ERROR_SPOT_KORAKUEN]
[s]Dome Town est茨 al lado de[n]la estaci吋n.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_JINBOCHO]
[s]Hay una zona comercial repleta[n]de librer胤as por aqu胤 cerca.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_JINBOCHO_]
[s]Hay una zona comercial repleta[n]de librer胤as por aqu胤 cerca.[n]Deber胤a ir con alguien de d胤a...[n][w][e]

[msg MSG_ERROR_SPOT_TUKISIMA]
[s]Hay un restaurante de monjayaki[n]cerca de la estaci吋n.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_KAIHINPAR]
[s]Al lado de la estaci吋n, hay[n]un parque y una noria.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_KAIHINPAR_2]
[s]Al lado de la estaci吋n, hay[n]un parque y una noria.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_AKASAKA]
[s]Est茨 cerca de la cadena de[n]televisi吋n que visit姻 durante una[n]excursi吋n. No necesito ir ahora.[n][w][e]

[msg MSG_ERROR_SPOT_YOKOHAMA]
[s]Chinatown est茨 cerca[n]de la estaci吋n. Deber胤a ir a comer[n]all胤 con alguien en mi d胤a libre.[n][w][e]

[msg MSG_ERROR_SPOT_BEACH]
[s]Esta es la playa a la que vinimos[n]juntos. Aunque la temporada de[n]playa ya se ha acabado...[n][w][e]

[msg MSG_ERROR_SPOT_ROPPONGI]
[s]La estaci吋n est茨 cerca de[n]la sede de Okumura Foods.[n]No pinto nada all胤...[n][w][e]

[msg MSG_ERROR_SPOT_MAIHAMA]
[s]Esto est茨 al lado de Destinyland.[n]Deber胤a ir con alguien[n]cuando tenga un d胤a libre...[n][w][e]

[msg MSG_ERROR_SPOT_MAIHAMA_S]
[s]Esto est茨 al lado de Destinyland.[n]Deber胤a ir con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_MEIJI_JIN]
[s]El Santuario Meiji est茨 muy cerca[n]de la estaci吋n. Deber胤a ir[n]a rezar con alguien...[n][w][e]

[msg MSG_ERROR_SPOT_MEIJI_JIN_2]
[s]El Santuario Meiji est茨 muy cerca[n]de la estaci吋n. Deber胤a ir[n]a rezar con alguien de d胤a...[n][w][e]

[msg MSG_ERROR_SPOT_NAKANO]
[s]La estaci吋n est茨 llena de lugares[n]culturales 雨nicos. Deber胤a ir[n]con alguien.[n][w][e]

[msg MSG_ERROR_SPOT_SINAGAWA]
[s]La estaci吋n es conocida por sus[n]hoteles y el acuario. Deber胤a ir[n]con alguien la pr吋xima vez.[n][w][e]

[msg MSG_ERROR_SPOT_SHIBUYA_L]
[s]Aqu胤 es donde fuimos a aquel bufet.[n]Deber胤a ir a comer con alguien[n]cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_AKIBA_LAS]
[s]Hay una tienda de electr吋nica[n]enorme cerca. Deber胤a ir[n]con alguien cuando vuelva a Tokio.[n][w][e]

[msg MSG_ERROR_SPOT_HARAJYUKU_2]
[s]La calle Takenoko est茨 al lado de[n]la estaci吋n. Deber胤a ir[n]con alguien cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_IKEBUKURO_2]
[s]Conozco un planetario cerca[n]de la estaci吋n. Deber胤a ir[n]con alguien cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_AKIBA_SPO_2]
[s]Hay una tienda de electr吋nica[n]enorme cerca. Deber胤a ir[n]con alguien cuando vuelva a Tokio.[n][w][e]

[msg MSG_ERROR_SPOT_UENO_LAST]
[s]Hay muchos museos de arte cerca[n]de la estaci吋n. Deber胤a visitarlos[n]con alguien cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_OGIKUBO_L]
[s]La estaci吋n est茨 cerca de un buen[n]restaurante de ramen. Deber胤a ir[n]con alguien cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_ICHIGAYA_]
[s]Hay un estanque al lado de[n]la estaci吋n. Deber胤a ir[n]con alguien cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_INOKASIRA_2]
[s]Aqu胤 est茨 el Parque Inokashira.[n]Deber胤a ir con alguien[n]cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_GINZA_LAS]
[s]Conozco un restaurante elegante de[n]sushi por aqu胤 cerca. Deber胤a ir[n]con alguien cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_ASAKUSA_L]
[s]La Skytree y la calle Nakamise[n]est茨n muy cerca. Deber胤a ir[n]con alguien cuando vuelva a Tokio.[n][w][e]

[msg MSG_ERROR_SPOT_KORAKUEN_]
[s]Dome Town est茨 al lado de[n]la estaci吋n. Deber胤a ir[n]con alguien cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_JINBOCHO__2]
[s]Aqu胤 cerca hay muchas librer胤as.[n]Deber胤a ir con alguien[n]cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_TUKISIMA_]
[s]Hay un restaurante de monjayaki[n]cerca de la estaci吋n. Deber胤a ir[n]con alguien cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_KAIHINPAR_3]
[s]Aqu胤 cerca hay un parque[n]y una noria. Deber胤a ir con alguien[n]cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_YOKOHAMA_]
[s]Chinatown est茨 cerca[n]de la estaci吋n. Deber胤a ir[n]con alguien cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_MAIHAMA_L]
[s]Esto est茨 al lado de Destinyland.[n]Deber胤a ir con alguien[n]cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_MEIJI_JIN_3]
[s]El Santuario Meiji est茨 muy cerca[n]de la estaci吋n. Deber胤a ir a rezar[n]con alguien cuando vuelva a Tokio...[n][w][e]

[msg MSG_ERROR_SPOT_NAKANO_LA]
[s]La estaci吋n est茨 llena de lugares[n]culturales 雨nicos. Deber胤a ir[n]con alguien cuando vuelva a Tokio.[n][w][e]

[msg MSG_ERROR_SPOT_SINAGAWA_]
[s]La estaci吋n es conocida por sus[n]hoteles y el acuario. Deber胤a ir[n]con alguien cuando vuelva a Tokio.[n][w][e]

[msg MSG_RYUJI_SPOT_CANCEL [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 7063 65535 0]T胤o, qu姻 aguafiestas.[n][w][e]

[msg MSG_ANNE_SPOT_CANCEL [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 6063 65535 0]Ah, qu姻 rabia.[n][w][e]

[msg MSG_YUSUKE_SPOT_CANCEL [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 4026 65535 0]Qu姻 decepci吋n...[n][w][e]

[msg MSG_MAKOTO_SPOT_CANCEL [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 2120 65535 0]Ah, 夷has cambiado de opini吋n?[n][w][e]

[msg MSG_FUTABA_SPOT_CANCEL [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 9062 65535 0]斡No te rajes![n][w][e]

[msg MSG_HARU_SPOT_CANCEL [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 1 3063 65535 0]Ah, vale...[n][w][e]

