[msg serif5001]
[s]Qu姻 cartas[n]tan buenas.[n][e]

[msg serif5002]
[s]S胤, estupendo.[n][e]

[msg serif5003]
[s]Bueno,[n]me quedo esto.[n][e]

[msg serif5004]
[s]Mm, no est茨 mal.[n][e]

[msg serif5005]
[s]Quiz茨 me baste[n]para ganar.[n][e]

[msg serif5006]
[s]Tu carta, por favor.[n][e]

[msg serif5007]
[s]No pienso perder.[n][e]

[msg serif5008]
[s]Uf, qu姻 remedio.[n][e]

[msg serif5009]
[s]Toma.[n][e]

[msg serif5010]
[s]En tal caso...[n][e]

[msg serif5011]
[s]Qu姻 mala suerte.[n][e]

[msg serif5012]
[s]Una tr茨gica p姻rdida.[n][e]

[msg serif5013]
[s]Voy primero, 夷no?[n][e]

[msg serif5014]
[s]Parece que[n]empiezo yo.[n][e]

[msg serif5015]
[s]Comencemos.[n][e]

[msg serif5016]
[s]Que sea[n]un juego justo.[n][e]

[msg serif5017]
[s]Comienzas t雨.[n][e]

[msg serif5018]
[s]No te contengas.[n][e]

[msg serif5019]
[s]Tu turno.[n][e]

[msg serif5020]
[s]夷Qu姻 vas a tirar?[n][e]

[msg serif5021]
[s]Juguemos.[n][e]

[msg serif5022]
[s]Soy un magnate...[n]Maravilloso.[n][e]

[msg serif5023]
[s]Siento decir que[n]la partida es m胤a.[n][e]

[msg serif5024]
[s]斡He ganado![n][e]

[msg serif5025]
[s]Siempre un paso[n]por detr茨s...[n][e]

[msg serif5026]
[s]Me conformo[n]con ser segundo.[n][e]

[msg serif5027]
[s]Una gran partida.[n][e]

[msg serif5028]
[s]Oh, esto[n]no pinta bien.[n][e]

[msg serif5029]
[s]斡夷Eh?![n][e]

[msg serif5030]
[s]Qu姻 fallo...[n][e]

[msg serif5031]
[s]He terminado[n]primero.[n][e]

[msg serif5032]
[s]斡He ganado![n][e]

[msg serif5033]
[s]Magnate.[n][e]

[msg serif5034]
[s]Una gran partida.[n][e]

[msg serif5035]
[s]Qu姻 bonito es[n]ser adinerado.[n][e]

[msg serif5036]
[s]Acab姻.[n][e]

[msg serif5037]
[s]Lento pero seguro...[n][e]

[msg serif5038]
[s]Podr胤a[n]haber sido peor.[n][e]

[msg serif5039]
[s]Es lo que hay.[n][e]

[msg serif5040]
[s]Argh... Soy pobre...[n][e]

[msg serif5041]
[s]Deber胤a haberlo[n]sabido...[n][e]

[msg serif5042]
[s]夷Por qu姻...?[n][e]

[msg serif5043]
[s]斡Qu姻 humillaci吋n![n][e]

[msg serif5044]
[s]Deja mucho[n]que desear...[n][e]

[msg serif5045]
[s]Oh, soy un pobre[n]mendigo...[n][e]

[msg serif5046]
[s]斡Contempla[n]mi revoluci吋n![n][e]

[msg serif5047]
[s]斡Aqu胤 viene[n]la revoluci吋n![n][e]

[msg serif5048]
[s]斡Ahora empieza[n]la revoluci吋n![n][e]

[msg serif5049]
[s]斡Hora de una escalera[n]de revoluci吋n![n][e]

[msg serif5050]
[s]斡Lo siento,[n]pero debo ganar![n][e]

[msg serif5051]
[s]斡Venga, una escalera[n]de revoluci吋n![n][e]

[msg serif5052]
[s]斡Contrarrevoluci吋n![n][e]

[msg serif5053]
[s]斡Contrarrestar姻[n]esa revoluci吋n![n][e]

[msg serif5054]
[s]斡Magn胤fico![n]斡Contrarrevoluci吋n![n][e]

[msg serif5055]
[s]夷Qu姻 tal esto?[n][e]

[msg serif5056]
[s]夷Puedes con esto?[n][e]

[msg serif5057]
[s]No me voy[n]a contener.[n][e]

[msg serif5058]
[s]Un buen comienzo.[n][e]

[msg serif5059]
[s]Lento pero seguro.[n][e]

[msg serif5060]
[s]Todo tiene un orden.[n][e]

[msg serif5061]
[s]Mi mejor jugada...[n][e]

[msg serif5062]
[s]斡Paro del 8![n][e]

[msg serif5063]
[s]斡Paro del 8![n][e]

[msg serif5064]
[s]No he terminado.[n][e]

[msg serif5065]
[s]Aj茨... Una pareja.[n][e]

[msg serif5066]
[s]Dos cartas a la vez.[n][e]

[msg serif5067]
[s]夷Puedes con esto?[n][e]

[msg serif5068]
[s]Ahora tres cartas.[n][e]

[msg serif5069]
[s]Aqu胤 va mi jugada.[n][e]

[msg serif5070]
[s]Jugar姻 tres cartas.[n][e]

[msg serif5071]
[s]斡Contempla[n]la verdadera belleza![n][e]

[msg serif5072]
[s]La primera jugada[n]es crucial.[n][e]

[msg serif5073]
[s]No puedo detenerme.[n][e]

[msg serif5074]
[s]Jugar姻 con cuidado.[n][e]

[msg serif5075]
[s]Esto bastar茨.[n][e]

[msg serif5076]
[s]Mm... Puede que esto...[n][e]

[msg serif5077]
[s]Aceleremos el ritmo.[n][e]

[msg serif5078]
[s]夷Podr姻 solucionarlo?[n][e]

[msg serif5079]
[s]A ver qu姻 te parece.[n][e]

[msg serif5080]
[s]斡Eso deber胤a bastar![n][e]

[msg serif5081]
[s]No me contendr姻.[n][e]

[msg serif5082]
[s]Mis disculpas.[n][e]

[msg serif5083]
[s]Todo en orden.[n][e]

[msg serif5084]
[s]Esperar姻[n]y observar姻...[n][e]

[msg serif5085]
[s]Aqu胤 viene...[n][e]

[msg serif5086]
[s]斡Ha llegado la hora![n][e]

[msg serif5087]
[s]Te voy a detener.[n][e]

[msg serif5088]
[s]Yo primero.[n][e]

[msg serif5089]
[s]Arriesguemos.[n][e]

[msg serif5090]
[s]Toca atacar.[n][e]

[msg serif5091]
[s]斡Ahora![n][e]

[msg serif5092]
[s]Una jugada[n]arriesgada...[n][e]

[msg serif5093]
[s]Un arreglo temporal,[n]pero...[n][e]

[msg serif5094]
[s]Jugar姻 esto.[n][e]

[msg serif5095]
[s]夷Qu姻 tal esto?[n][e]

[msg serif5096]
[s]Esto podr胤a[n]funcionar.[n][e]

[msg serif5097]
[s]Esto servir茨.[n][e]

[msg serif5098]
[s]夷No te parece[n]precioso?[n][e]

[msg serif5099]
[s]斡Una escalera[n]exquisita![n][e]

[msg serif5100]
[s]Una escalera[n]podr胤a funcionar...[n][e]

[msg serif5101]
[s]斡Aj茨, un bloqueo![n][e]

[msg serif5102]
[s]斡Cartas bloqueadas![n][e]

[msg serif5103]
[s]斡Hora de bloquear[n]esto![n][e]

[msg serif5104]
[s]斡Un regreso hermoso![n][e]

[msg serif5105]
[s]Olvidas algo.[n][e]

[msg serif5106]
[s]斡No es suficiente![n][e]

[msg serif5107]
[s]Me he descuidado...[n][e]

[msg serif5108]
[s]斡夷Un tres de picas?![n][e]

[msg serif5109]
[s]斡Est茨s[n]contraatacando![n][e]

[msg serif5110]
[s]Tres[n][e]

[msg serif5111]
[s]Cuatro[n][e]

[msg serif5112]
[s]Cinco[n][e]

[msg serif5113]
[s]Seis[n][e]

[msg serif5114]
[s]Siete[n][e]

[msg serif5115]
[s]Nueve[n][e]

[msg serif5116]
[s]Diez[n][e]

[msg serif5117]
[s]Once[n][e]

[msg serif5118]
[s]Jota[n][e]

[msg serif5119]
[s]Doce[n][e]

[msg serif5120]
[s]Reina[n][e]

[msg serif5121]
[s]Trece[n][e]

[msg serif5122]
[s]Rey[n][e]

[msg serif5123]
[s]Uno[n][e]

[msg serif5124]
[s]As[n][e]

[msg serif5125]
[s]Dos[n][e]

[msg serif5126]
[s]Joker[n][e]

[msg serif5127]
[s]No me quedan[n]opciones...[n][e]

[msg serif5128]
[s]夷C吋mo contrarresto[n]esto?[n][e]

[msg serif5129]
[s]斡Paso![n]斡Es muy fuerte![n][e]

[msg serif5130]
[s]Uf, nada...[n][e]

[msg serif5131]
[s]Siguiente.[n][e]

[msg serif5132]
[s]Paso.[n][e]

[msg serif5133]
[s]Voy a pasar.[n][e]

[msg serif5134]
[s]Esta escalera[n]es problem茨tica...[n][e]

[msg serif5135]
[s]No ser茨 nada f茨cil...[n][e]

[msg serif5136]
[s]斡No puedo[n]sacar nada![n][e]

[msg serif5137]
[s]斡Estoy bloqueado![n][e]

[msg serif5138]
[s]Argh,[n]夷por qu姻 ahora?[n][e]

[msg serif5139]
[s]Lamentable.[n][e]

[msg serif5140]
[s]夷Otra vez?[n][e]

[msg serif5141]
[s]斡Otra vez no![n][e]

[msg serif5142]
[s]Lo est茨s disfrutando.[n][e]

[msg serif5143]
[s]夷Vas a ponerle fin?[n][e]

[msg serif5144]
[s]Vuelta a empezar.[n][e]

[msg serif5145]
[s]Te toca otra vez.[n][e]

[msg serif5146]
[s]斡Una revoluci吋n![n]Bien hecho.[n][e]

[msg serif5147]
[s]斡Te mereces[n]un aplauso![n][e]

[msg serif5148]
[s]斡Una revoluci吋n[n]espectacular![n][e]

[msg serif5149]
[s]Una revoluci吋n[n]inoportuna...[n][e]

[msg serif5150]
[s]Prefer胤a[n]el statu quo...[n][e]

[msg serif5151]
[s]No me esperaba[n]una revoluci吋n...[n][e]

[msg serif5152]
[s]斡Maravillosa[n]contrarrevoluci吋n![n][e]

[msg serif5153]
[s]Una muy oportuna[n]contrarrevoluci吋n.[n][e]

[msg serif5154]
[s]Una maniobra[n]elegant胤sima.[n][e]

[msg serif5155]
[s]Una contra es[n]tan poco elegante...[n][e]

[msg serif5156]
[s]Una[n]contrarrevoluci吋n...[n][e]

[msg serif5157]
[s]夷Ahora contraataca?[n][e]

[msg serif5158]
[s]Qu姻 oportuno.[n][e]

[msg serif5159]
[s]Bien jugado.[n][e]

[msg serif5160]
[s]La perfecci吋n.[n][e]

[msg serif5161]
[s]No puede ser...[n][e]

[msg serif5162]
[s]A este paso...[n][e]

[msg serif5163]
[s]Estoy a merced[n]del destino...[n][e]

[msg serif5164]
[s]Parece divertido.[n][e]

[msg serif5165]
[s]夷Puedo jugar?[n][e]

[msg serif5166]
[s]Con esto me olvidar姻[n]del hambre.[n][e]

[msg serif5167]
[s]斡夷C吋mo?![n]斡夷Bancarrota?![n][e]

[msg serif5168]
[s]No me lo puedo[n]creer...[n][e]

[msg serif5169]
[s]夷C吋mo ha ocurrido?[n][e]

[msg serif5170]
[s]夷Qu姻 ocurre? Te toca.[n][e]

[msg serif5171]
[s]Juega algo bajo, va.[n][e]

[msg serif5172]
[s]夷Est茨s al loro?[n][e]

[msg serif5173]
[s]Tengo que detenerte...[n][e]

[msg serif5174]
[s]夷Qu姻 est茨s tramando?[n][e]

[msg serif5175]
[s]No hace falta[n]que corras. Calma.[n][e]

[msg serif5176]
[s]Pronto terminar姻.[n][e]

[msg serif5177]
[s]Agradecer胤a[n]un poco de ayuda.[n][e]

[msg serif5178]
[s]夷Me est茨s vigilando?[n][e]

[msg serif5179]
[s]No me esperaba[n]una revoluci吋n...[n][e]

[msg serif5180]
[s]夷Este era[n]tu objetivo?[n][e]

[msg serif5181]
[s]Mu姻strame[n]lo que tienes.[n][e]

[msg serif5182]
[s]夷Te ha disgustado[n]la revoluci吋n?[n][e]

[msg serif5183]
[s]Si vas a jugar, ve[n]con una carta alta.[n][e]

[msg serif5184]
[s]夷No tienes[n]nada bajo?[n][e]

[msg serif5185]
[s]Podr胤as jugar[n]una sola carta.[n][e]

[msg serif5186]
[s]Yo evitar胤a[n]una pareja.[n][e]

[msg serif5187]
[s]No tendr茨s[n]una pareja, 夷no?[n][e]

[msg serif5188]
[s]Algo que no sea[n]una escalera...[n][e]

[msg serif5189]
[s]Una escalera[n]ser胤a problem茨tica...[n][e]

[msg serif5190]
[s]夷Seguro que[n]no tienes escalera?[n][e]

[msg serif5191]
[s]夷Est茨s al loro?[n][e]

[msg serif5192]
[s]Una gran partida.[n][e]

