[msg MSG_BUY]
[s]夷Comprar esta imagen?[n][e]

[msg MSG_000]
[s]Ficha modelo del protagonista[n]con su uniforme de pleno invierno.[n][e]

[msg MSG_001]
[s]Ficha modelo del protagonista[n]con su atuendo casual[n]de pleno invierno.[n][e]

[msg MSG_002]
[s]Ficha modelo de la Persona[n]del protagonista, Raoul.[n][e]

[msg MSG_003]
[s]Ficha modelo de Morgana[n]con su traje de Ladr吋n Fantasma.[n][e]

[msg MSG_004]
[s]Ficha modelo de Morgana[n]en su forma humana.[n][e]

[msg MSG_005]
[s]Ficha modelo de la Persona[n]de Morgana en su tercera evoluci吋n.[n][e]

[msg MSG_006]
[s]Ficha modelo del Monam吋vil.[n][e]

[msg MSG_007]
[s]Ficha modelo del Monac吋ptero.[n][e]

[msg MSG_008]
[s]Ficha modelo de Ryuji[n]con su uniforme de pleno invierno.[n][e]

[msg MSG_009]
[s]Ficha modelo de Ryuji[n]con su atuendo casual[n]de pleno invierno.[n][e]

[msg MSG_010]
[s]Ficha modelo de la Persona[n]de Ryuji en su tercera evoluci吋n.[n][e]

[msg MSG_011]
[s]Ficha modelo de Ann[n]con su uniforme de pleno invierno.[n][e]

[msg MSG_012]
[s]Ficha modelo de Ann[n]con su atuendo casual[n]de pleno invierno.[n][e]

[msg MSG_013]
[s]Ficha modelo de la Persona[n]de Ann en su tercera evoluci吋n.[n][e]

[msg MSG_014]
[s]Ficha modelo de Yusuke[n]con su uniforme de pleno invierno.[n][e]

[msg MSG_015]
[s]Ficha modelo de Yusuke[n]con su atuendo casual[n]de pleno invierno.[n][e]

[msg MSG_016]
[s]Ficha modelo de la Persona[n]de Yusuke en su tercera evoluci吋n.[n][e]

[msg MSG_017]
[s]Ficha modelo de Makoto[n]con su uniforme de pleno invierno.[n][e]

[msg MSG_018]
[s]Ficha modelo de Makoto[n]con su atuendo casual[n]de pleno invierno.[n][e]

[msg MSG_019]
[s]Ficha modelo de la Persona[n]de Makoto en su tercera evoluci吋n.[n][e]

[msg MSG_020]
[s]Ficha modelo de Futaba[n]con su atuendo casual[n]de invierno.[n][e]

[msg MSG_021]
[s]Ficha modelo de Futaba[n]con su atuendo casual[n]de pleno invierno.[n][e]

[msg MSG_022]
[s]Ficha modelo de la Persona[n]de Futaba en su tercera evoluci吋n.[n][e]

[msg MSG_023]
[s]Ficha modelo de Haru[n]con su uniforme de pleno invierno.[n][e]

[msg MSG_024]
[s]Ficha modelo de Haru[n]con su atuendo casual[n]de pleno invierno.[n][e]

[msg MSG_025]
[s]Ficha modelo de la Persona[n]de Haru en su tercera evoluci吋n.[n][e]

[msg MSG_026]
[s]Ficha modelo de Akechi[n]con su uniforme de pleno invierno.[n][e]

[msg MSG_027]
[s]Ficha modelo de Akechi[n]con su atuendo casual[n]de pleno invierno.[n][e]

[msg MSG_028]
[s]Ficha modelo de la Persona[n]de Akechi en su tercera evoluci吋n.[n][e]

[msg MSG_029]
[s]Ficha modelo del uniforme[n]de verano de Sumire.[n][e]

[msg MSG_030]
[s]Ficha modelo de Sumire[n]con su atuendo casual[n]de verano.[n][e]

[msg MSG_031]
[s]Ficha modelo de Sumire[n]con su atuendo casual[n]de invierno.[n][e]

[msg MSG_032]
[s]Ficha modelo de Sumire[n]con su atuendo casual[n]de pleno invierno.[n][e]

[msg MSG_033]
[s]Ficha modelo de Sumire[n]con su traje de Ladr吋n Fantasma.[n][e]

[msg MSG_034]
[s]Ficha modelo[n]de la Persona de Sumire.[n][e]

[msg MSG_035]
[s]Ficha modelo de la Persona[n]de Sumire en su segunda evoluci吋n.[n][e]

[msg MSG_036]
[s]Ficha modelo de la Persona[n]de Sumire en su tercera evoluci吋n.[n][e]

[msg MSG_037]
[s]Ficha modelo de Takuto Maruki.[n][e]

[msg MSG_038]
[s]Ficha modelo de Takuto Maruki.[n][e]

[msg MSG_039]
[s]Ficha modelo de Takuto Maruki.[n][e]

[msg MSG_040]
[s]Ficha modelo[n]de la Persona de Maruki.[n][e]

[msg MSG_041]
[s]Ficha modelo de la Persona[n]de Maruki evolucionada.[n][e]

[msg MSG_042]
[s]Ficha modelo de Sojiro Sakura.[n][e]

[msg MSG_043]
[s]Ficha modelo de Chihaya Mifune.[n][e]

[msg MSG_044]
[s]Ficha modelo de Munehisa Iwai.[n][e]

[msg MSG_045]
[s]Ficha modelo de Tae Takemi.[n][e]

[msg MSG_046]
[s]Ficha modelo de Sadayo Kawakami.[n][e]

[msg MSG_047]
[s]Ficha modelo de Ichiko Ohya.[n][e]

[msg MSG_048]
[s]Ficha modelo de Shinya Oda.[n][e]

[msg MSG_049]
[s]Ficha modelo de Hifumi Togo.[n][e]

[msg MSG_050]
[s]Ficha modelo de Yuuki Mishima.[n][e]

[msg MSG_051]
[s]Ficha modelo de Toranosuke Yoshida.[n][e]

[msg MSG_052]
[s]Ficha modelo de Sae Niijima.[n][e]

[msg MSG_053]
[s]Imagen de Igor.[n][e]

[msg MSG_054]
[s]Ficha modelo de Justine y Caroline.[n][e]

[msg MSG_055]
[s]Ficha modelo de Lavenza.[n][e]

[msg MSG_056]
[s]Ficha modelo de Jose.[n][e]

[msg MSG_057]
[s]Ficha modelo del se隠or del Palacio[n]de Kamoshida.[n][e]

[msg MSG_058]
[s]Ficha modelo del se隠or del Palacio[n]de Madarame.[n][e]

[msg MSG_059]
[s]Ficha modelo del se隠or del Palacio[n]de Kaneshiro.[n][e]

[msg MSG_060]
[s]Ficha modelo del monstruo[n]del Palacio de Futaba.[n][e]

[msg MSG_061]
[s]Ficha modelo del se隠or del Palacio[n]de Okumura.[n][e]

[msg MSG_062]
[s]Ficha modelo de la se隠ora[n]del Palacio de Niijima.[n][e]

[msg MSG_063]
[s]Ficha modelo del se隠or del Palacio[n]de Shido.[n][e]

[msg MSG_064]
[s]Ficha modelo del Santo Grial.[n][e]

[msg MSG_065]
[s]Ficha modelo del dios maligno[n]del mundo de Qliphoth.[n][e]

[msg MSG_066]
[s]La ilustraci吋n usada[n]para la caja de Persona 5.[n][e]

[msg MSG_067]
[s]La ilustraci吋n creada[n]para la imagen del h姻roe[n]de Persona 5.[n][e]

[msg MSG_068]
[s]La ilustraci吋n usada para[n]la cubierta de la edici吋n[n]limitada de Persona 5.[n][e]

[msg MSG_069]
[s]La portada usada para el libro[n]de arte incluido en la edici吋n[n]limitada de Persona 5.[n][e]

[msg MSG_070]
[s]La ilustraci吋n creada como aviso[n]justo antes del lanzamiento[n]de Persona 5.[n][e]

[msg MSG_071]
[s]La ilustraci吋n creada para celebrar[n]el lanzamiento de Persona 5.[n][e]

[msg MSG_072]
[s]La ilustraci吋n creada para celebrar[n]el lanzamiento en Occidente[n]de Persona 5.[n][e]

[msg MSG_073]
[s]Una ilustraci吋n de agradecimiento[n]para conmemorar la venta de m茨s[n]de 550 000 copias de Persona 5.[n][e]

[msg MSG_074]
[s]Una ilustraci吋n de agradecimiento[n]para conmemorar la venta de[n]2 millones de copias de Persona 5.[n][e]

[msg MSG_075]
[s]Una ilustraci吋n extra[n]de una revista sensacionalista.[n][e]

[msg MSG_076]
[s]Ilustraci吋n de Persona 5.[n][e]

[msg MSG_077]
[s]Ilustraci吋n usada como portada[n]del n雨mero 614 de la revista[n]Dengeki PlayStation.[n][e]

[msg MSG_078]
[s]Ilustraci吋n usada como portada[n]del n雨mero 622 de la revista[n]Dengeki PlayStation.[n][e]

[msg MSG_079]
[s]Ilustraci吋n usada como portada[n]del n雨mero 623 de la revista[n]Dengeki PlayStation.[n][e]

[msg MSG_080]
[s]Ilustraci吋n usada para celebrar[n]el A隠o Nuevo en 2017.[n][e]

[msg MSG_081]
[s]Ilustraci吋n usada para celebrar[n]el A隠o Nuevo en 2018.[n][e]

[msg MSG_082]
[s]Ilustraci吋n usada para celebrar[n]la Navidad.[n][e]

[msg MSG_083]
[s]Ilustraci吋n usada para la cubierta[n]de la banda sonora.[n][e]

[msg MSG_084]
[s]Ilustraci吋n usada para la[n]cubierta de The Day Breakers[n]en el anime de Persona 5.[n][e]

[msg MSG_085]
[s]Ilustraci吋n que se mostr吋 en una[n]transmisi吋n del Tokyo Game Show[n]2015 en el canal de Persona.[n][e]

[msg MSG_086]
[s]Corto del protagonista que[n]se muestra durante la batalla.[n][e]

[msg MSG_087]
[s]Corto de Morgana que[n]se muestra durante la batalla.[n][e]

[msg MSG_088]
[s]Corto de Ryuji que[n]se muestra durante la batalla.[n][e]

[msg MSG_089]
[s]Corto de Ann que[n]se muestra durante la batalla.[n][e]

[msg MSG_090]
[s]Corto de Yusuke que[n]se muestra durante la batalla.[n][e]

[msg MSG_091]
[s]Corto de Makoto que[n]se muestra durante la batalla.[n][e]

[msg MSG_092]
[s]Corto de Futaba que[n]se muestra durante la batalla.[n][e]

[msg MSG_093]
[s]Corto de Haru que[n]se muestra durante la batalla.[n][e]

[msg MSG_094]
[s]Corto de Akechi que[n]se muestra durante la batalla.[n][e]

[msg MSG_095]
[s]Corto de Sumire que[n]se muestra durante la batalla.[n][e]

[msg MSG_096]
[s]Corto de Justine y Caroline[n]que se muestra en las batallas.[n][e]

[msg MSG_097]
[s]El aviso que los Ladrones Fantasma[n]enviaron a Kamoshida.[n][e]

[msg MSG_098]
[s]El aviso que los Ladrones Fantasma[n]enviaron a Madarame.[n][e]

[msg MSG_099]
[s]El aviso que los Ladrones Fantasma[n]enviaron a Kaneshiro.[n][e]

[msg MSG_100]
[s]El aviso que los Ladrones Fantasma[n]enviaron a Futaba.[n][e]

[msg MSG_101]
[s]El aviso que los Ladrones Fantasma[n]enviaron a Okumura.[n][e]

[msg MSG_102]
[s]El aviso que los Ladrones Fantasma[n]enviaron a Sae.[n][e]

[msg MSG_103]
[s]Imagen de fondo del calendario[n]de Tokio por el d胤a.[n][e]

[msg MSG_104]
[s]Imagen de fondo del calendario[n]de Tokio por la noche.[n][e]

[msg MSG_105]
[s]El mapa de Mementos.[n][e]

[msg MSG_106]
[s]El mapa de Mementos que[n]se ha visto afectado por Maruki.[n][e]

[msg MSG_107]
[s]El mapa de Mementos despu姻s[n]de verse afectado por los deseos[n]materializados de la gente.[n][e]

[msg MSG_108]
[s]Los iconos usados[n]en los chats y las batallas.[n][e]

[msg MSG_109]
[s]Un grafiti dibujado en la pizarra[n]en una clase del Instituto Shujin.[n][e]

[msg MSG_110]
[s]Una foto conmemorativa[n]de los Ladrones Fantasma tras[n]completar su primera misi吋n.[n][e]

[msg MSG_111]
[s]Una foto conmemorativa de la fiesta[n]de bienvenida de Yusuke.[n][e]

[msg MSG_112]
[s]Una foto sacada de camino[n]al festival de fuegos artificiales.[n][e]

[msg MSG_113]
[s]Una foto del final del festival[n]de verano.[n][e]

[msg MSG_114]
[s]Una foto conmemorativa del viaje[n]a la playa para hacerse[n]m茨s amigos de Futaba.[n][e]

[msg MSG_115]
[s]Una foto en la playa Waikiki[n]durante la excursi吋n a Haw茨i.[n][e]

[msg MSG_116]
[s]Una foto en una tienda[n]de souvenirs de Haw茨i.[n][e]

[msg MSG_117]
[s]Una foto en el festival[n]del instituto comiendo yakisoba[n]de un puesto de comida.[n][e]

[msg MSG_118]
[s]Una foto en la celebraci吋n[n]de la derrota de Shido.[n][e]

[msg MSG_119]
[s]Una foto conmemorativa[n]de la fiesta de Navidad.[n][e]

[msg MSG_120]
[s]Una foto conmemorativa[n]de las chicas en A隠o Nuevo.[n][e]

[msg MSG_121]
[s]Una foto conmemorativa[n]de la primera visita[n]de la pareja al santuario.[n][e]

[msg MSG_122]
[s]Una foto conmemorativa de Sumire[n]para mostrar lo lejos[n]que ha llegado.[n][e]

[msg MSG_123]
[s]Una foto del protagonista[n]y Morgana que tom吋 Sojiro.[n][e]

[msg MSG_124]
[s]Corto de Akechi que[n]se muestra durante la batalla.[n][e]

[msg MSG_125]
[s]Corto de Lavenza que[n]se muestra durante la batalla.[n][e]

[msg MSG_126]
[s]El aviso que los Ladrones Fantasma[n]enviaron a Maruki.[n][e]

[msg MSG_127]
[s]Ficha modelo del uniforme[n]de invierno de Sumire.[n][e]

[msg MSG_128]
[s]Ficha modelo de Sumire[n]con su uniforme de pleno invierno.[n][e]

[msg MSG_129]
[s]Corto del protagonista que[n]se muestra en un ataque combinado.[n][e]

[msg MSG_130]
[s]Imagen del protagonista[n]que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_131]
[s]Corto de Morgana que[n]se muestra en un ataque combinado.[n][e]

[msg MSG_132]
[s]Imagen de Morgana que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_133]
[s]Corto de Ryuji que[n]se muestra en un ataque combinado.[n][e]

[msg MSG_134]
[s]Imagen de Ryuji que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_135]
[s]Corto de Ann que[n]se muestra en un ataque combinado.[n][e]

[msg MSG_136]
[s]Imagen de Ann que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_137]
[s]Corto de Yusuke que[n]se muestra en un ataque combinado.[n][e]

[msg MSG_138]
[s]Imagen de Yusuke que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_139]
[s]Corto de Makoto que[n]se muestra en un ataque combinado.[n][e]

[msg MSG_140]
[s]Imagen de Makoto que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_141]
[s]Imagen de Futaba que se muestra[n]en su pantalla de Estado.[n][e]

[msg MSG_142]
[s]Imagen de Futaba que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_143]
[s]Corto de Haru que[n]se muestra en un ataque combinado.[n][e]

[msg MSG_144]
[s]Imagen de Haru que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_145]
[s]Corto de Akechi que[n]se muestra en un ataque combinado.[n][e]

[msg MSG_146]
[s]Imagen de Akechi que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_147]
[s]Corto de Akechi que[n]se muestra en un ataque combinado.[n][e]

[msg MSG_148]
[s]Imagen de Akechi que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_149]
[s]Corto de Sumire que[n]se muestra en un ataque combinado.[n][e]

[msg MSG_150]
[s]Imagen de Sumire que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_151]
[s]Corto de Justine y Caroline[n]que se muestra[n]durante los ataques combinados.[n][e]

[msg MSG_152]
[s]Imagen de Justine y Caroline[n]que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_153]
[s]Imagen de Lavenza que se muestra[n]tras un ataque combinado final.[n][e]

[msg MSG_154]
[s]La ilustraci吋n de la caja[n]de Persona 5 Royal.[n][e]

[msg MSG_155]
[s]Ryuji se mentaliza con su equipo[n]antes de una gran competici吋n.[n]Su cara refleja seguridad.[n][e]

[msg MSG_156]
[s]Morgana de compras con Ann.[n]畏l va cargando con las bolsas,[n]pero parece muy feliz.[n][e]

[msg MSG_157]
[s]Ann y Shiho codo con codo.[n]El pasado que Kamoshida[n]destruy吋 ya no existe.[n][e]

[msg MSG_158]
[s]Madarame ense隠ando a Yusuke.[n]Es la relaci吋n perfecta[n]entre profesor y alumno.[n][e]

[msg MSG_159]
[s]Makoto a punto de comer con su[n]familia. Seguro que su padre est茨[n]hablando del valor de la justicia.[n][e]

[msg MSG_160]
[s]Futaba de camino a la ceremonia de[n]inauguraci吋n del curso. La familia[n]que siempre dese吋 va con ella.[n][e]

[msg MSG_161]
[s]Haru abre un nuevo restaurante[n]con el hombre que m茨s respeta:[n]su padre y mentor.[n][e]

[msg MSG_162]
[s]Akechi disfrutando de una partida[n]de ajedrez. Le gusta la rivalidad[n]sana y no se intuye tensi吋n alguna.[n][e]

[msg MSG_163]
[s]Ya sin pena ni arrepentimiento,[n]sigue sus sue隠os para cumplir la[n]promesa que le hizo a su hermana.[n][e]

[msg MSG_164]
[s]Un atisbo de un mundo feliz hecho[n]realidad. 夷Qu姻 estar茨n[n]mirando esos dos?[n][e]

[msg MSG_165]
[s]MSG_165[n][e]

[msg MSG_166]
[s]MSG_166[n][e]

[msg MSG_167]
[s]MSG_167[n][e]

[msg MSG_168]
[s]MSG_168[n][e]

[msg MSG_169]
[s]MSG_169[n][e]

[msg MSG_170]
[s]MSG_170[n][e]

[msg MSG_171]
[s]MSG_171[n][e]

[msg MSG_172]
[s]MSG_172[n][e]

[msg MSG_173]
[s]MSG_173[n][e]

[msg MSG_174]
[s]MSG_174[n][e]

[msg MSG_175]
[s]MSG_175[n][e]

[msg MSG_176]
[s]MSG_176[n][e]

[msg MSG_177]
[s]MSG_177[n][e]

[msg MSG_178]
[s]MSG_178[n][e]

[msg MSG_179]
[s]MSG_179[n][e]

[msg MSG_180]
[s]MSG_180[n][e]

[msg MSG_181]
[s]MSG_181[n][e]

[msg MSG_182]
[s]MSG_182[n][e]

[msg MSG_183]
[s]MSG_183[n][e]

[msg MSG_184]
[s]MSG_184[n][e]

[msg MSG_185]
[s]MSG_185[n][e]

[msg MSG_186]
[s]MSG_186[n][e]

[msg MSG_187]
[s]MSG_187[n][e]

[msg MSG_188]
[s]MSG_188[n][e]

[msg MSG_189]
[s]MSG_189[n][e]

[msg MSG_190]
[s]MSG_190[n][e]

[msg MSG_191]
[s]MSG_191[n][e]

[msg MSG_192]
[s]MSG_192[n][e]

[msg MSG_193]
[s]MSG_193[n][e]

[msg MSG_194]
[s]MSG_194[n][e]

[msg MSG_195]
[s]MSG_195[n][e]

[msg MSG_196]
[s]MSG_196[n][e]

[msg MSG_197]
[s]MSG_197[n][e]

[msg MSG_198]
[s]MSG_198[n][e]

[msg MSG_199]
[s]MSG_199[n][e]

