[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]斡O-oye, esperad un segundo![n]夷Vais a ignorar ese brillo dorado?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 8 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Mmm... Menudo lustre...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Tal vez llev茨rselo cueste[n]lo suyo, pero podr胤amos venderlo[n]por una millonada.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Venga, que no hemos venido a...[n][f 1 3 65535][w][e]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]斡Cuidado! 斡Est茨s pisando algo![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]斡夷Eso es malo?![n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Alejaos.[e]
[s]Calmaos un poco.[e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]斡Oh, no! 斡He activado la seguridad![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Y t雨 eras el que dec胤a que fu姻semos[n]con cuidado... 夷Y ahora qu姻?[n]夷Salimos por patas?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]斡No! 斡Atravesar los l茨seres[n]atraer茨 a much胤simos enemigos[n]a nuestra posici吋n![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]斡Esperad! 斡Joker no est茨 atrapado![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Lo siento, Joker, pero tendr茨s que[n]encontrar la forma de desactivar[n]los l茨seres infrarrojos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Es un museo. Habr茨 un interruptor[n]para que los empleados los apaguen.[n]斡Encu姻ntralo![n][f 1 3 65535][w][e]

