[msg MSG_000_0_0 [Voz misteriosa]]
[s][vp 8 0 0 1 65535 0]夷Por fin has entrado en raz吋n?[n][f 1 2 75][e]

[msg MSG_001_0_0 [Yusuke]]
[s][vp 8 0 0 2 65535 0]Argh...[n][f 1 2 20][e]

[msg MSG_002_0_0 [Voz misteriosa]]
[s][vp 8 0 0 3 65535 0]Qu姻 ingenuidad la de desviar[n]la mirada ante la verdad...[n][f 1 2 98][e]

[msg MSG_003_0_0 [Voz misteriosa]]
[s][vp 8 0 0 4 65535 0]Una imitaci吋n lamentable, sin duda.[n][f 1 2 75][e]

[msg MSG_005_0_0 [Voz misteriosa]]
[s][vp 8 0 0 5 65535 0]斡M茨s vale que te despidas[n]de esa parte de ti![n][f 1 2 92][e]

[msg MSG_006_0_0 [Yusuke]]
[s][vp 8 0 0 6 65535 0]斡A-arrrgh![n][f 1 2 120][e]

[msg MSG_007_0_0 [Voz misteriosa]]
[s][vp 8 0 0 7 65535 0]Forjemos un contrato...[n][f 1 2 110][e]

[msg MSG_008_0_0 [Voz misteriosa]]
[s][vp 8 0 0 8 65535 0]Yo soy t雨, t雨 eres yo...[n][f 1 2 90][e]

[msg MSG_009_0_0 [Voz misteriosa]]
[s][vp 8 0 0 9 65535 0]El mundo est茨 repleto[n]de belleza y de vicios...[n][f 1 2 100][e]

[msg MSG_010_0_0 [Voz misteriosa]]
[s][vp 8 0 0 10 65535 0]斡Es hora de que les demuestres[n]a los dem茨s cu茨l es cu茨l![n][f 1 2 120][e]

[msg MSG_011_0_0 [Yusuke]]
[s][vp 8 0 0 11 65535 0]Muy bien...[n][f 1 2 41][e]

[msg MSG_012_0_0 [Yusuke]]
[s][vp 6 0 0 12 29 0]斡Ven, Goemon![n][f 1 2 70][e]

[msg MSG_013_0_0 [Yusuke]]
[s][vp 6 0 0 13 30 0]Es asombroso...[n][f 1 2 60][e]

[msg MSG_013_5_0 [Yusuke]]
[s][vp 6 0 0 27 30 0]Ser茨n imitaciones, pero[n]juntas forman un buen espect茨culo.[n][f 1 2 120][e]

[msg MSG_014_0_0 [Yusuke]]
[s][vp 6 0 0 14 30 0]Aunque las flores del mal florezcan, que se sepa que[n]las abominaciones est茨n destinadas a perecer.[n][f 1 2 180][e]

[msg MSG_015_0_0 [Morgana]]
[s][vp 6 0 0 15 26 0]斡Hala, qu姻 pasada![n][f 1 2 65][e]

[msg MSG_016_0_0 [Sombra de Madarame]]
[s][vp 1 0 0 16 0 0]Mmm... 斡夷Qui姻n te crees que eres?![n][f 1 2 76][e]

[msg MSG_017_0_0 [Sombra de Madarame]]
[s][vp 1 0 0 17 0 0]斡El precio por tu insolencia[n]ser茨 la muerte![n][f 1 2 103][e]

[msg MSG_018_0_0 [Sombra de Madarame]]
[s][vp 1 0 0 18 0 0]斡夷D吋nde est茨n los guardias?![n]斡Matadlos a todos![n][f 1 2 70][e]

[msg MSG_019_0_0 [Yusuke]]
[s][vp 6 0 0 19 30 0]Los ni隠os que lo adoraban[n]como a un padre...[n][f 1 2 90][e]

[msg MSG_020_0_0 [Yusuke]]
[s][vp 6 0 0 20 30 0]Las expectativas de sus alumnos...[n][f 1 2 80][e]

[msg MSG_021_0_0 [Yusuke]]
[s][vp 6 0 0 21 30 0]夷A cu茨ntos pisote吋?[n][f 1 2 86][e]

[msg MSG_022_0_0 [Yusuke]]
[s][vp 6 0 0 22 30 0]斡夷Cu茨ntos sue隠os[n]cambi吋 por riqueza?![n][f 1 2 85][e]

[msg MSG_023_0_0 [Yusuke]]
[s][vp 1 0 0 23 0 0]Me da igual lo que cueste...[n]斡Se har茨 justicia![n][f 1 2 115][e]

[sel SEL_024_0_0 top]
[s]夷T雨 te encargas?[e]
[s]M茨s vale que no huyas.[e]
[s]A ver de qu姻 est茨s hecho.[e]

[msg MSG_025_0_0 [Yusuke]]
[s][vp 1 0 0 24 0 0]斡Estoy preparado![n][f 1 2 47][e]

[msg MSG_026_0_0 [Yusuke]]
[s][vp 1 0 0 25 0 0]斡Lo mismo digo![n][f 1 2 47][e]

[msg MSG_027_0_0 [Yusuke]]
[s][vp 1 0 0 26 0 0]斡Muy bien! 斡Adelante![n][f 1 2 47][e]

