[msg MSG_001_0_0 [Personal de la exposici吋n]]
[s][vp 8 0 0 1 10 0]Disc雨lpeme, se隠or. Hay algo[n]de lo que deber胤amos informarle.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Madarame]]
[s][bup 0 203 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Disc雨lpenme un momento.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Madarame]]
[s][bup 0 203 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]夷Qu姻 sucede?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Personal de la exposici吋n]]
[s][vp 8 0 0 4 10 0]Hemos encontrado esto fuera...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Madarame]]
[s][bup 0 203 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]夷Una carta?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Personal de la exposici吋n]]
[s][vp 8 0 0 6 10 0]Es... Esto...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Personal de la exposici吋n]]
[s][vp 8 0 0 40 10 0]或Don Ichiryusai Madarame,[n]un pecador, hijo de la vanidad[n]cuyo talento ha expirado位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 41 10 0]或Eres un artista que usa su[n]autoridad para robarles las ideas[n]a los alumnos位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 42 10 0]或Hemos decidido hacerte confesar[n]todos tus delitos,[n]y lo vas a hacer t雨 solito位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 43 10 0]或Te arrancaremos todos tus[n]distorsionados deseos de cuajo位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 44 10 0]或Atentamente, [f 4 28]位.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Madarame]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 203 3 301 1][vp 8 0 0 13 65535 0]斡夷Qui姻n me env胤a esto?![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Personal de la exposici吋n]]
[s][vp 8 0 0 14 10 0]斡No lo sabemos! Han puesto la[n]misma carta por todos lados.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Madarame]]
[s][bup 0 203 2 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]斡夷Y no hay nada en las[n]c茨maras de seguridad?![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Personal de la exposici吋n]]
[s][vp 8 0 0 16 10 0]Ni rastro del culpable. Solo hemos[n]visto un gato rondando por all胤.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Madarame]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 203 3 301 1][vp 8 0 0 17 65535 0]斡Quitadlas de inmediato![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Personal de la exposici吋n]]
[s][vp 8 0 0 18 10 0]斡S胤, se隠or![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [(SE)斑目 一流斎]]
[s][vp 8 0 0 19 65535 0]フン...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Personal de la exposici吋n]]
[s][vp 8 0 0 20 10 0]Mm...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Madarame]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 203 12 301 1][vp 8 0 0 21 65535 0]夷Y ahora qu姻?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Personal de la exposici吋n]]
[s][vp 8 0 0 22 10 0]Quiz茨 afecte a la exposici吋n.[n]Creemos que es una broma, pero 夷qu姻[n]dir茨n los medios de comunicaci吋n?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Madarame]]
[s][bup 0 203 2 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]夷Insin雨as acaso que este[n]bulo es verdad?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Personal de la exposici吋n]]
[s][vp 8 0 0 24 10 0]斡Claro que no![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Sombra de Madarame]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 209 3 301 1][vp 8 0 0 25 5 0]Es cosa de esos criajos, 夷verdad?[n][f 1 3 65535][w][e]
[s][bup 0 203 102 0 0][f 4 10 65535 0 0][vp 8 0 0 26 5 0]Bueno, no importa... Una vez termine[n]la exposici吋n se les acabar茨[n]el jueguecito.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]夷Bastar茨 con esto?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]斡S胤! 斡Ha sido perfecto![n]斡Y el dise隠o estaba genial![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]El tesoro deber胤a aparecer[n]a la de ya.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Ser茨 mejor que saborees[n]la libertad mientras[n]puedas, viejales.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]夷Hab姻is mirado internet? La pe隠a[n]ya est茨 hablando del aviso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Ya ver茨n...[n]斡Lo van a flipar![n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Estoy seguro de que lo sab姻is,[n]pero 斡solo tenemos una oportunidad![n][f 1 3 65535][w][e]

[sel SEL_032_0_0 top]
[s]A por todas.[e]
[s]O lo hacemos o es el fin.[e]
[s]Cuento con vosotros.[e]

[msg MSG_033_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Tranquis, la 雨ltima vez[n]lo logramos.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Venga, que no puede ser que nuestro[n]l胤der se muestre tan asustadizo.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Tambi姻n contamos contigo.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]T雨 tambi姻n lo tienes claro,[n]夷no, Yusuke?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Como el agua.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Lo conseguiremos.[n][f 1 3 65535][w][e]

