[msg MSG_000_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 10 300 1][vp 8 0 0 1 65535 0]斡夷Hab姻is visto la noticia sobre[n]Madarame?! 斡Es igual que lo[n]que pas吋 con Kamoshida![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]斡Y mencionaron a los[n]Ladrones Fantasma![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Esto se est茨 poniendo interesante...[n]Si lo hacemos bien, despertaremos[n]los corazones de la gente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Con este poder, no solo[n]vamos a hacer justicia.[n]斡Qu姻 pasote![n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Ser茨 divertido.[e]
[s]No s姻...[e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]斡Pues sigamos![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Joer, qu姻 plasta. Todo te da igual.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Y eso no hace que sea[n]m茨s de fiar como l胤der?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]斡Pues yo espero que cada[n]vez seamos m茨s famosos![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Que algo as胤 pase dos veces es la[n]leche. Ser胤a mucha coincidencia[n]que pasara por las buenas.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Si seguimos haciendo esto,[n]la gente que necesite valor[n]lo conseguir茨.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Quiz茨 nos convenga[n]disimular un poco m茨s.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]夷Los conoces?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]斡Idiota! 斡Son los encargados[n]de controlar qui姻n falta a clase![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Polic胤a con gafas de sol]]
[s][vp 8 0 0 16 10 0]Hola. 夷Puedo hablar con[n]vosotros un momento?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]斡Claro! 夷En qu姻 podemos ayudar?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Que act雨e de forma tan mon吋tona[n]siempre me provoca escalofr胤os.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Polic胤a con gafas de sol]]
[s][vp 8 0 0 19 10 0]夷Qu姻 hac姻is aqu胤?[n]夷Sois amigos?[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]Quer胤amos tomar un t姻...[e]
[s]Somos delincuentes juveniles.[e]
[s]夷Qu姻 parecemos?[e]

[msg MSG_019_0_0 [Polic胤a estricto]]
[s][vp 8 0 0 20 9 0]Mm. 夷Ah, s胤? 夷Y qu姻 hac姻is[n]en un sitio as胤?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Pues pensar a d吋nde vamos.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Polic胤a estricto]]
[s][vp 8 0 0 22 9 0]夷Eh? 夷Qu姻 has dicho?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]斡Ja, ja, ja! 斡E-era broma![n]Es que no durmi吋 mucho anoche.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Polic胤a con gafas de sol]]
[s][vp 8 0 0 25 10 0]Bueno, muy bien.[n]Vosotros procurad marcharos[n]antes de que sea muy tarde, 夷vale?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 26 10 0]Pasan cosas muy raras[n]雨ltimamente, y el asunto[n]del artista ha causado revuelo.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Tendremos cuidado.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]A雨n hay luz fuera...[n]Uf, esos t胤os tienen demasiado[n]tiempo libre.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Oye, no vayas inventando cosas[n]as胤 por las buenas.[n]斡Menudo susto me has dado![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]A partir de ahora, habr茨 que[n]tener a雨n m茨s cuidado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]斡Jol胤n! Justo despu姻s del segundo[n]incidente de los Ladrones,[n]las v胤ctimas anteriores se re雨nen.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]夷Crees que hay alguien[n]escuch茨ndonos?[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Eh, no pasar茨 nada. Mira[n]a tu alrededor. Somos los[n]雨nicos preocupados por eso.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Supongo que tienes raz吋n...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Por cierto, Yusuke, 夷has podido[n]sonsacarle algo a Madarame?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]夷Recuerdas que hablaba de la[n]persona de la m茨scara negra?[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Bueno, intent姻 que me contara[n]cosas, pero ni siquiera entend胤a[n]lo que le hab胤a pasado.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]En realidad, 姻l no vio[n]c吋mo le robaban los deseos.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Se rumorea que quiz茨 lo manden[n]a prisi吋n. Si es as胤, ser茨 dif胤cil[n]conseguir informaci吋n...[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]夷Y qu姻 vas a hacer ahora?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Me ir姻 de la casa. No puedo[n]seguir dibujando en un lugar as胤.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]夷Tienes alg雨n sitio al que ir?[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]A la residencia del instituto.[n]Puedo quedarme all胤 gratis gracias[n]a la beca.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]斡夷Tienes beca?![n]夷Tan bien se te da?[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Aunque la casa de Takamaki[n]tampoco estar胤a mal.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]斡夷Que qu姻?![n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]斡As胤 puedes pedirle que[n]pose para ti cuando quieras![n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]斡Ser茨s idiota![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Bueno, ahora que Yusuke va a[n]vivir solo, nos resultar茨 m茨s f茨cil[n]reunirnos cuando queramos.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]De momento, deber胤amos esperar[n]y ver c吋mo se resuelve el caso.[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Y nos llevar茨 tiempo encontrar[n]un objetivo tan importante[n]como Madarame.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Pues nada, habr茨 que ir por la vida[n]de estudiantes normales mientras[n]buscamos otro objetivo.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]De eso te encargas t雨, Ryuji.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Vale. Pues ahora toca[n]prepararse m茨s hasta entonces.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 55 65535 0]Yusuke Kitagawa...[n][f 1 3 65535][w][e]

