[msg MSG_000_0_0 [Miembro del consejo]]
[s][vp 8 0 0 1 65535 0]Presidenta...[n]夷Qu姻 significa esa nota?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]El director Kobayakawa[n]la ha colgado sin pregun...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Miembro del consejo]]
[s][vp 8 0 0 3 5 0]Ya hemos recibido[n]informaci吋n an吋nima.[n][f 1 3 65535][w][e]
[s][f 4 16 6 7 301 65535 65535][vp 8 0 0 4 5 0]或He o胤do que est茨n amenazando[n]a parte del alumnado. Tengo mucho[n]miedo... Haced algo, por favor位.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 4 16 6 7 301 1 65535][vp 8 0 0 5 65535 0]斡夷Qu姻?![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Miembro del consejo]]
[s][vp 8 0 0 6 4 0]或Tienen con qu姻 chantajearme[n]y me exigen dinero. No puedo[n]acudir a la polic胤a... 夷Qu姻 hago?位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 4 0]Esto no se referir茨 a los[n]delitos que se est茨n cometiendo[n]en Shibuya, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Miembro del consejo]]
[s][vp 8 0 0 8 5 0]As胤 que hay v胤ctimas hasta en[n]nuestro instituto... 夷Qu姻 hacemos?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Miembro del consejo]]
[s][vp 8 0 0 9 4 0]Esto no es responsabilidad[n]del consejo estudiantil.[n]A nosotros tambi姻n nos asusta.[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Miembro del consejo]]
[s][vp 8 0 0 10 4 0]El director Kobayakawa[n]te llam吋 ayer, 夷no?[n]夷Te cont吋 algo?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Bueno, no...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Hoy no est茨,[n]pero le preguntar姻 ma隠ana.[n]De momento, esperad...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Miembro del consejo]]
[s][vp 8 0 0 13 4 0]Si t雨 lo dices...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Pido disculpas por la confusi吋n.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]No te preocupes.[n]Har姻 algo para ayudar.[n][f 1 3 65535][w][e]

