[msg MSG_000_0_0 [Relaciones p雨blicas]]
[s][vp 8 0 0 1 10 0]Por eso tenemos patrocinadores,[n]para que nos ayuden a hacer[n]programas de televisi吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 10 0]Seguramente habr姻is visto anuncios[n]alguna vez. Pues en realidad son[n]productos de los patrocinadores.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 10 0]En resumen, la audiencia[n]es vital para la financiaci吋n y[n]la producci吋n de un canal, y...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]Vale.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Todo el mundo lo sabe...[e]
[s]Qu姻 interesante.[e]
[s]Zzzzz...[e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]No te rayes, t胤o.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]夷Qu姻? Ah..., pues ser茨 mejor[n]que sigas escuchando.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]No est茨 haciendo ni caso.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Relaciones p雨blicas]]
[s][vp 8 0 0 8 10 0]Las telenovelas se echan durante[n]el d胤a, y el atractivo equipo de[n]reporteros trabaja por la noche.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 10 0]En el departamento de programaci吋n[n]es donde decidimos a qu姻 hora se[n]emite cada programa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 10 10 0]Se podr胤a decir que es el lugar[n]donde se fijan los horarios.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Tampoco hay que ser muy listo[n]para saber eso...[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Tienes raz吋n.[e]
[s]No es tan dif胤cil de entender.[e]
[s]Tengo sue隠o...[e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]*bostezo* Qu姻 sue隠o...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]B-bueno, supongo que s胤...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Jop姻... Ni caso me ha hecho...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Relaciones p雨blicas]]
[s][vp 8 0 0 15 10 0]Se seleccionan las mejores partes[n]de un programa para darle[n]la duraci吋n deseada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 16 10 0]El lugar donde se edita el material[n]filmado es la sala de edici吋n.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Oye, 夷le queda mucho a esto?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Yo me muero antes de que acabe.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Argh...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Presentador de las noticias famoso]]
[s][vp 8 0 0 20 8 0]夷Qu姻 est茨 pasando?[n]No aguanto tanto ruido.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Eh, capu...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Relaciones p雨blicas]]
[s][vp 8 0 0 22 10 0]斡Perd吋n! 斡Les dir姻 que se[n]vayan ahora mismo![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Relaciones p雨blicas]]
[s][vp 8 0 0 35 65535 0]Y ahora vais a vivir la experiencia[n]de primera mano.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Vaya t胤o imb姻cil.[n]夷Qui姻n se cree que es?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ayudante de direcci吋n mand吋n]]
[s][vp 8 0 0 24 9 0]Oye, t雨, 夷quieres salir en la tele?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]夷Eh?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ayudante de direcci吋n mand吋n]]
[s][vp 8 0 0 26 9 0]Es que tienes un cuerpazo.[n]Je, je, je...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Eh, estoy de excursi吋n...[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ayudante de direcci吋n mand吋n]]
[s][vp 8 0 0 28 9 0]Ll茨mame si est茨s interesada.[n]Ser胤a un placer recibir un mensaje[n]tuyo a cualquier hora del d胤a.[n][f 1 3 65535][w][e]

[msg MSG_026_5_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Eh, vale...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]或Ser胤a un placer位, y una mierda.[n]Est茨 claro lo que quiere.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]斡夷Hay algo que les importe[n]a estos miserables adultos[n]que no sean las apariencias?![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Les voy a arrancar el coraz吋n[n]a bocados, co隠o.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 3 300 1][vp 8 0 0 33 65535 0]Baja el volumen.[n]斡Se supone que hoy os ten姻is que[n]comportar como buenos estudiantes![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Kawakami]]
[s][bup 0 109 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Vale que est姻s aburrido,[n]pero no montes ning雨n pollo.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ayudante de direcci吋n mand吋n]]
[s][vp 8 0 0 36 9 0]Bueno, eh...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ayudante de direcci吋n mand吋n]]
[s][vp 8 0 0 37 9 0]Hoy vais a ver en qu姻 consiste el[n]trabajo de un ayudante de c茨mara.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 38 9 0]Mientras movemos las c茨maras,[n]necesitamos a gente que impida[n]que se enreden los cables.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 39 9 0]A ver, el rubio. Parece que[n]tienes energ胤a de sobra.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 40 9 0]T雨, el de al lado, tambi姻n puedes[n]venir si te sientes solo. Venga,[n]coged los cables.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Joder... 斡Menuda mierda![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Aj, 斡qu姻 co隠azo![n][f 1 3 65535][w][e]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Me est茨 cortando todo el rollo.[n][f 1 3 65535][w][e]

[msg MND_035_0_0]
[s][vp 8 0 0 0 65535 0]Luchamos valientemente[n]contra los grandes cables.[n][f 1 3 65535][w][e]

