[msg MSG_000_0_0 [Voz de chica]]
[s][vp 8 0 0 1 65535 0]Hola.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]夷Alguna novedad sobre[n]la b雨squeda del jefe?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Las cosas van bien.[e]
[s]No es asunto tuyo.[e]
[s]Shibuya es enorme.[e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Menos mal...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Eso es que no.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Bueno, no te equivocas.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Voz de hombre]]
[s][vp 8 0 0 6 65535 0]Vosotros dos, 夷ten姻is algo[n]que hacer? Tengo un curro[n]estupendo para vosotros.[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Tipo sospechosamente s吋rdido]]
[s][vp 8 0 0 7 65535 0]Es muy f茨cil, como un trabajo[n]de repartidor.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Al final no ha hecho falta[n]buscar mucho.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Tipo sospechosamente s吋rdido]]
[s][vp 8 0 0 9 65535 0]Vais al instituto, 夷no?[n]夷Quer姻is un dinerillo extra,[n]aparte de vuestras mesadas?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Mmm... Con lo de repartir,[n]夷te refieres a cosas[n]un poquito raras?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Tipo sospechosamente s吋rdido]]
[s][vp 8 0 0 11 65535 0]Je, qu姻 chica m茨s graciosa.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]夷No me vas a responder?[n]Pues ten胤a yo raz吋n...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Tipo sospechosamente s吋rdido]]
[s][vp 8 0 0 13 65535 0]夷Eh?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 14 65535 0]夷Qu姻 mosca te ha picado?[n]夷A qu姻 viene tanta preguntita?[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]No hay que recurrir a la violencia.[e]
[s]Te denunciar姻.[e]

[msg MSG_014_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Ah...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Tipo sospechosamente s吋rdido]]
[s][vp 8 0 0 16 65535 0]Era broma. 夷Por qu姻 me iba[n]a enfadar con unos cr胤os[n]como vosotros?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 17 65535 0]Bueno, me tengo que ir.[n]斡Hasta luego![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Va-vale, si no quieres tratar[n]con nosotros, siempre podemos ir[n]a ver directamente a tu jefe.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Tipo sospechosamente s吋rdido]]
[s][vp 8 0 0 19 65535 0]夷Lo dices de verdad,[n]sabiendo qui姻n es?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 20 65535 0]Je, no me lo creo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 21 65535 0]Bueno, me voy,[n]que ya me est茨is hartando.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Estoy segura de que forma[n]parte de la mafia a la que[n]estamos buscando.[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]A por 姻l.[e]
[s]Incre胤ble, lo has descubierto.[e]

[msg MSG_020_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Creo que deber胤amos conseguir[n]pruebas antes de nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Intent姻 enga隠arlo[n]para ver si soltaba algo,[n]pero no hubo manera.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Pero no tengo pruebas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Intent姻 enga隠arlo[n]para ver si soltaba algo,[n]pero no hubo manera.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Por cierto, gracias por defenderme.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Me marcho ya.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Parece que el jefe es astuto.[n]Ha ense隠ado a sus subordinados[n]demasiado bien.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]No me extra隠a que la polic胤a est姻[n]teniendo problemas para dar con 姻l.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Cambiando de tema, s胤 que tienes[n]coraje. No te echaste atr茨s[n]contra semejante rufi茨n.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Aunque al final[n]no conseguimos informaci吋n...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Dej姻moslo por hoy.[n][f 1 3 65535][w][e]

