[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Venga, hoy vamos a Shibuya,[n]tal como planeamos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Es posible que tengamos[n]que combatir,[n]as胤 que estad en guardia.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vale, ya estamos todos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Yo pas姻 por aqu胤 ayer.[n]Joder, qu姻 gent胤o.[n]Ver茨s t雨 qu姻 mierda...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y hay mucha polic胤a.[n]A lo mejor la mafia no da se隠ales[n]por eso.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya, en las noticias hablan mucho[n]del aumento del n雨mero de delitos.[n]Quiz茨 ni aparezcan.[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Tenemos que hacerlo.[e]
[s]Dej姻moslo por hoy.[e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Pues habr茨 que ir en su busca![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Venga, que somos cuatro.[n]Conseguir algo va a ser f茨cil.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Ya te vale! 斡Que somos cinco![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como acordamos ayer,[n]ve a la calle principal, [f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Genial, 斡vamos! Av胤same si ves[n]a alguien con pinta rara.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La calle principal es[n]la zona que te toca.[n]Los dem茨s se ocupar茨n del resto.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Estudiante del Kosei de pelo negro]]
[s][vp 8 0 0 0 65535 0]Oye, entr姻 en un foro el otro d胤a[n]y me encontr姻 con este mensaje:[n]或Emb吋lsate 10 000位.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Estudiante del Kosei de pelo casta隠o]]
[s][vp 8 0 0 0 65535 0]夷Ser茨 alg雨n c吋digo?[n]Parece sospechoso...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aunque debo decir que o胤[n]algo por el estilo el otro d胤a[n]en aquel callej吋n.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Estudiante del Kosei de pelo negro]]
[s][vp 8 0 0 0 65535 0]Est茨n pasando cosas muy raras, 夷no?[n]Apuesto a que por eso anda por aqu胤 la poli.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Host]]
[s][vp 8 0 0 0 65535 0]Se acab吋 mi turno. Uf, me siento[n]fatal. He bebido un huevo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Quiz茨 deber胤a buscar otro trabajo.[n]夷Sabes c吋mo puedo[n]ganar dinero r茨pido?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Jugador]]
[s][vp 8 0 0 0 65535 0]Ojal茨. Podr胤as trabajar[n]para la mafia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ya sabes, para esos t胤os turbios[n]de los callejones. Pero tendr胤as[n]que estafar a los chavales.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Host]]
[s][vp 8 0 0 0 65535 0]Ah, yo paso de esas movidas.[n]Me gusta vivir fuera[n]de la c茨rcel, gracias.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Patrullero]]
[s][vp 8 0 0 0 65535 0]Nada de lo que informar.[n]Hemos atrapado varias v胤ctimas,[n]pero ninguna mov胤a los hilos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aparecen y desaparecen cuando[n]quieren y, adem茨s, se camuflan[n]entre los adolescentes.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Polic胤a en alerta]]
[s][vp 8 0 0 0 65535 0]斡Deja de quejarte! Si no intentamos[n]conseguir informaci吋n, dir茨n que[n]la polic胤a no sirve para nada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ya tenemos a los medios encima[n]y nuestros superiores no nos[n]ayudan. Qu姻 depresi吋n.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Vagabundo]]
[s][vp 8 0 0 0 65535 0]夷Por qu姻 me miras con esa[n]cara tan siniestra? Si tienes algo[n]que decirme, dilo y punto.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]Quiero un trabajo a tiempo parcial.[e]
[s]夷Eres de la mafia?[e]

[msg MSG_021_0_0 [Vagabundo]]
[s][vp 8 0 0 0 65535 0]夷Un trabajo a tiempo parcial? No te[n]referir茨s a un trabajo normal, 夷no?[n]Mira, que no se te ocurra.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Te sacar茨n hasta el 雨ltimo c姻ntimo[n]con amenazas y extorsi吋n.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Vagabundo]]
[s][vp 8 0 0 0 65535 0]夷Yo? No, solo soy un ermita隠o[n]solitario. 夷Qu姻 quieres[n]de ellos de todas formas?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mejor ni te acerques.[n]Son gentuza.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Vagabundo]]
[s][vp 8 0 0 0 65535 0]Algunos amigos m胤os[n]han ca胤do en sus redes.[n]Controlan toda la ciudad.[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]夷C吋mo doy con la mafia?[e]
[s]夷Tus amigos van a escapar?[e]

[msg MSG_025_0_0 [Vagabundo]]
[s][vp 8 0 0 0 65535 0]Se camuflan entre la gente[n]normal de por aqu胤,[n]pero usan palabras raras.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Es como una especie[n]de lenguaje secreto.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]En fin, si ves algo raro,[n]al姻jate. Su principal objetivo[n]son los j吋venes.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Vagabundo]]
[s][vp 8 0 0 0 65535 0]Es f茨cil decirlo, pero no[n]tienen ning雨n sitio al que ir.[n]No te acerques a la mafia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Se camuflan entre la gente[n]normal de por aqu胤,[n]pero hay cosas que los delatan.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Usan palabras raras, como[n]un c吋digo secreto. Ten cuidado[n]si oyes cosas turbias.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]夷C吋mo vas?[n]夷Has encontrado algo?[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]Nada.[e]
[s]Quiero irme a casa...[e]

[msg MSG_029_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Ha sido un fracaso 姻pico.[n]Me pregunto c吋mo[n]les habr茨 ido a los dem茨s.[n][f 1 3 65535][w][e]

[sel SEL_030_0_0 top]
[s]夷C吋mo ha ido, Ryuji?[e]
[s]夷C吋mo ha ido, Ann?[e]
[s]夷C吋mo ha ido, Yusuke?[e]

[msg MSG_031_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Supuestamente, un t胤o cerca[n]de la entrada ha mencionado[n]algo de drogas duras.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]No creo que consiga nada,[n]pero ir姻 a comprobarlo.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Me he enterado de que alguien[n]ofrece un trabajo bien pagado[n]en la estaci吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Al parecer, busca chicas.[n]Ir姻 a ver de qu姻 se trata.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Me he enterado de que hay gente[n]que dice cosas raras en el callej吋n[n]trasero cerca de los recreativos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Algo sobre hielo y verduras[n]e incluso algo sobre que[n]va a nevar ma隠ana...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Ir姻 a ver qu姻 pasa por si acaso.[n]Los recreativos est茨n en[n]la calle principal, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Deber胤amos hacer todo[n]lo posible para ayudarlos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No tengo ni idea de qu姻[n]pistas son reales. Ve al lugar[n]que parezca m茨s sospechoso.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Vagabundo]]
[s][vp 8 0 0 0 65535 0]Ya te he hablado de la mafia.[n]夷Necesitas algo m茨s?[n][f 1 3 65535][w][e]

[sel SEL_036_0_0 top]
[s]Gracias.[e]
[s]夷C吋mo puedo identificarlos?[e]

[msg MSG_037_0_0 [Vagabundo]]
[s][vp 8 0 0 0 65535 0]No hace falta. Me has distra胤do[n]y ya no me aburro tanto. La mafia[n]me ha dado problemas a m胤 tambi姻n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Bueno, ser茨 mejor que pases[n]desapercibido. Si se fijan en ti,[n]te har茨n la vida m茨s dif胤cil.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Vagabundo]]
[s][vp 8 0 0 0 65535 0]Dicen todo tipo de frases raras[n]y poco comunes.[n]Creo que es un c吋digo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Eso s胤, son muy cuidadosos.[n]Hasta la polic胤a tiene problemas[n]para averiguar qui姻nes son.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Anciana amable]]
[s][vp 8 0 0 0 65535 0]Hola, joven.[n]夷Podr胤as indicarme por d吋nde[n]se va a la l胤nea Inogami?[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo siento, abuela, estoy ocupado.[n]Baje las escaleras[n]y luego gire a la izquierda...[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Anciana amable]]
[s][vp 8 0 0 0 65535 0]Jo, Shibuya tiene tela.[n]Estos huesos ya no se mueven[n]como antes. Qu姻 desgracia.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*suspiro* Bueno, venga.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Hombre alto]]
[s][vp 8 0 0 0 65535 0]斡Te dije que era una pasada![n]斡D茨melo, r茨pido![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He o胤do que es muy eficaz.[n]Cualquier desierto se convierte[n]en un frondoso bosque de pelo.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esa era la persona de la que[n]hablaba Ryuji. Un bosque frondoso...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No quiero saber nada m茨s.[n]Entiendo por qu姻 lo has confundido[n]con la gente a la que buscamos.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Deber胤amos pasar de 姻l.[n]Busquemos en otro sitio.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Jol胤n, cu茨nta gente![n]斡Son todos ojeadores[n]y proxenetas, puaj![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Cazatalentos desenfadado]]
[s][vp 8 0 0 0 65535 0]Quinientos mil yenes por un v胤deo.[n]Si eres famosa, puede que m茨s...[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Cazatalentos desenfadado]]
[s][vp 8 0 0 0 65535 0]夷Qu姻? 夷Quieres salir[n]en uno de nuestros v胤deos?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No es que no haya demanda,[n]pero nuestra empresa solo contrata[n]a chicas, lo siento.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Salir en un v胤deo?[n]夷Qu姻 clase de trabajo es ese?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Supongo que no tendr茨 nada[n]que ver con drogas.[n]No creo que sea 姻l.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No es la persona a la que estamos[n]buscando. Vayamos a otro sitio.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estaba buscando los recreativos.[n]Ya me voy.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Polic胤a de avanzada edad]]
[s][vp 8 0 0 0 65535 0]Oye, t雨 eres estudiante de[n]secundaria, 夷no? No deber胤as[n]merodear por ah胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]En mis tiempos, los recreativos[n]eran el sitio donde quedaban[n]los matones para liarla.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Hombre amenazante]]
[s][vp 8 0 0 0 65535 0]T雨 vas al instituto, 夷no?[n]夷Quieres tener un trabajillo[n]a tiempo parcial?[n][f 1 3 65535][w][e]

[sel SEL_054_0_0 top]
[s]Te escucho.[e]
[s]En realidad no.[e]

[msg MSG_055_0_0 [Hombre amenazante]]
[s][vp 8 0 0 0 65535 0]Ja, ja, ja. Lo sab胤a.[n]Todo el mundo quiere sacar tajada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aqu胤 no se puede hablar[n]con tanto ruido.[n]Vayamos a la parte de atr茨s...[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Hombre amenazante]]
[s][vp 8 0 0 0 65535 0]Ja, ja, ja. No digas eso. Aqu胤[n]ganar茨s dinero sin mover un dedo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aqu胤 no se puede hablar[n]con tanto ruido.[n]Vayamos a la parte de atr茨s...[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es 姻l, no hay duda.[n]Permanece atento.[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Hombre amenazante]]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Sabes lo que es un rizador?[n]Lo que usan las chicas[n]para rizarse el pelo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Qu姻 pasar胤a si le golpease a alguien[n]en la cara con el metal caliente?[n]Imag胤natelo.[n][f 1 3 65535][w][e]

[sel SEL_059_0_0 top]
[s]Que se quemar胤a.[e]
[s]Pues no s姻.[e]
[s]Y lo del trabajo...[e]

[msg MSG_060_0_0 [Hombre amenazante]]
[s][vp 8 0 0 0 65535 0]Ja, ja, ja. 斡Correcto![n]Ni los m姻dicos[n]podr胤an arregl茨rsela.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Lo prob姻 con uno y no dejaba[n]de gritar. Tengo una foto suya.[n]夷Quieres verla?[n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [Hombre amenazante]]
[s][vp 8 0 0 0 65535 0]Ah, 夷no sabes la respuesta?[n]*risa* Pues...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...que gritar胤a y pedir胤a perd吋n.[n]Tengo una foto suya.[n]夷Quieres verla?[n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Hombre amenazante]]
[s][vp 8 0 0 0 65535 0]Lo siento, chaval. Se ha cerrado[n]el periodo de inscripci吋n.[n]Largo, que estoy muy ocupado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Si juegas con fuego, te quemar茨s.[n]Y no querr茨s quemarte, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Hombre amenazante]]
[s][vp 8 0 0 0 65535 0]Me he quedado con tu cara.[n]Deja de fisgonear por aqu胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Te lo estoy diciendo por las buenas.[n]Avisado quedas.[n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mierda, 斡nos est茨 amenazando![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Creo que nuestra estrategia[n]ha fracasado. Vamos a cont茨rselo[n]a los dem茨s.[n][f 1 3 65535][w][e]

[msg MSG_065_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Los he subestimado.[n]No puedo creer que hayan averiguado[n]lo que pretendemos hacer...[n][f 1 3 65535][w][e]

[msg MSG_066_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]夷Seguro que no era un farol[n]lo de que se ha quedado[n]con nuestras caras?[n][f 1 3 65535][w][e]

[msg MSG_067_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Da igual, ahora ser茨 mucho[n]m茨s dif胤cil investigar.[n][f 1 3 65535][w][e]

[sel SEL_068_0_0 top]
[s]A雨n podemos hacerlo.[e]
[s]Probemos otra cosa.[e]

[msg MSG_069_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]No te emociones. Ser胤a horrible[n]que te ocurriera algo malo.[n][f 1 3 65535][w][e]

[msg MSG_070_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Puede que estemos otra vez[n]en la casilla de salida, pero es[n]la 雨nica opci吋n que tenemos.[n][f 1 3 65535][w][e]

[msg MSG_071_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]De acuerdo, volver姻 al Kosei[n]e investigar姻 un poco m茨s por all胤.[n][f 1 3 65535][w][e]

[msg MSG_072_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Ah, yo puedo hablar con unas amigas[n]que vienen mucho por Shibuya.[n][f 1 3 65535][w][e]

[msg MSG_073_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Chachi. Yo paso de movidas[n]de polis, as胤 que echar姻[n]un ojo por internet.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Venga, cada uno a lo suyo.[n]Si alguien descubre algo[n]interesante, lo hablamos ma隠ana.[n][f 1 3 65535][w][e]

[msg MSG_074_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]夷D吋nde quedamos?[n]Propongo que en alg雨n[n]lugar discreto.[n][f 1 3 65535][w][e]

[msg MSG_075_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Mmm, un sitio en el que[n]podamos hablar en secreto...[n]夷Un karaoke? Es bonito y barato.[n][f 1 3 65535][w][e]

[msg MSG_076_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]S胤, eso vale. All胤 tienen ofertas[n]de 或hora febril位, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_077_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]T胤o, se llama 或hora feliz位.[n]Febril, dice, y se queda tan ancho...[n][f 1 3 65535][w][e]

