[msg MSG_000_0_0 [Iida]]
[s][vp 8 0 0 1 4 0]Niijima, 夷no vas a ayudarme?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 4 0]Hab胤as dicho que lo mantendr胤as[n]en secreto, pero los rumores[n]vuelan...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 4 0]Oye, no lo habr茨s ido[n]contando t雨, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Tranquilo... 夷Siguen acos茨ndote?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Iida]]
[s][vp 8 0 0 5 4 0]Hasta ese delincuente lo sabe.[n]Puede que intente amenazarme ahora.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 4 0]Por qu姻 me pasa esto...[n]Ya no puedo pagar m茨s...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Ya tengo pistas sobre el incidente.[n]Solo necesito que esperes[n]un poco m茨s.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Iida]]
[s][f 4 16 6 4 300 65535 65535][vp 8 0 0 8 4 0]夷De verdad vas a ayudarme? La gente[n]piensa que lo haces para conseguir[n]una carta de recomendaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Mentira. Lo que quiero es proteger[n]a los alumnos del instituto.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Iida]]
[s][vp 8 0 0 10 4 0]Date prisa, por favor...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 4 16 6 4 300 1 65535][vp 8 0 0 11 65535 0]......[n][f 1 3 65535][w][e]

