[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]La periodista me ha respondido.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]El bar Crossroads...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Este mensaje es de la periodista,[n]夷no? 夷Quiere que vayas[n]a verla ahora?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]El bar Crossroads est茨 en Shinjuku.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Quedar en Shinjuku...[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Suena bien.[e]
[s]夷C吋mo es Shinjuku?[e]
[s]夷Me acompa隠as?[e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]As胤 me gusta.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]No te vuelvas loco solo[n]porque Shinjuku sea la zona[n]de marcha, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]A ver...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]En resumen, es la zona de marcha[n]para los adultos.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]夷D吋nde has aprendido esas cosas?[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Bueno, Shinjuku es una zona[n]de marcha y est茨 hasta arriba[n]de cosas tentadoras. Prep茨rate.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]M茨ndales un mensaje[n]a los dem茨s para que sepan[n]lo que est茨s haciendo.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Shinjuku de noche, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Suena bastante peligroso.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Deber胤a ser un grupo reducido.[n]Podr胤amos levantar sospechas[n]si somos muchos.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Qu姻date t雨, Ann.[n]No vaya a ser que te vuelvan[n]a ofrecer hacer de modelo...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]En fin... Muchas gracias.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Iremos solo los t胤os.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Yo no tengo dinero para el tren.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Pues iremos [f 4 2] y yo.[n]夷Os parece?[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s][f 5 14]Genial.[e]
[s]Yusuke, t雨 tambi姻n te vienes.[e]

[msg MSG_017_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Bueno, pues ya est茨.[n]Nos vemos en Shibuya.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]Yo lo siento,[n]pero no me queda dinero.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Pues nada, nos toca a nosotros.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Tened cuidado.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][vp 8 0 0 0 65535 0][f 5 14]A partir de ahora, ahorrar姻[n]para este tipo de situaciones.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]夷Vas a ir con el uniforme?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Lo mejor ser胤a no llamar[n]la atenci吋n.[n]C茨mbiate antes de irte.[n][f 1 3 65535][w][e]

