[msg MSG_000_0_0 [Voz misteriosa]]
[s][vp 8 0 0 1 65535 0]夷Has decidido escoger[n]el camino del conflicto...?[n][f 1 2 75][e]

[msg MSG_001_0_0 [Makoto]]
[s][vp 6 0 0 2 25 0]S胤... Ven a m胤.[n][f 1 2 55][e]

[msg MSG_002_0_0 [Voz misteriosa]]
[s][vp 8 0 0 3 65535 0]Genial. Procedamos con el contrato.[n][f 1 2 105][e]

[msg MSG_003_0_0 [Voz misteriosa]]
[s][vp 8 0 0 4 65535 0]Yo soy t雨, t雨 eres yo...[n][f 1 2 95][e]

[msg MSG_004_0_0 [Voz misteriosa]]
[s][vp 8 0 0 5 65535 0]Por fin has encontrado[n]tu propia justicia...[n][f 1 2 80][e]

[msg MSG_005_0_0 [Voz misteriosa]]
[s][vp 8 0 0 6 65535 0]Por favor... no vuelvas[n]a perderla de vista.[n][f 1 2 70][e]

[msg MSG_006_0_0 [Voz misteriosa]]
[s][vp 8 0 0 7 65535 0]Este d胤a memorable marca[n]la separaci吋n de tu 或yo位 falso...[n][f 1 2 165][e]

[msg MSG_007_0_0 [Sombra de Kaneshiro]]
[s][vp 6 0 0 8 20 0]斡夷Qu姻 narices?![n][f 1 2 30][e]

[msg MSG_008_0_0 [Yusuke]]
[s][vp 6 0 0 9 10 0]夷Una Persona...?[n][f 1 2 35][e]

[msg MSG_009_0_0 [Ryuji]]
[s][vp 6 0 0 10 7 0]No, colega... Eso es una moto...[n][f 1 2 65][e]

[msg MSG_010_0_0 [Makoto]]
[s][vp 6 0 0 11 24 0]Lo noto...[n][f 1 2 60][e]

[msg MSG_011_0_0 [Makoto]]
[s][vp 6 0 0 12 24 0]Mi 或yo位... 斡Yo...![n][f 1 2 75][e]

[msg MSG_012_0_0 [Makoto]]
[s][vp 6 0 0 13 24 0]斡Dale gas![n][f 1 2 25][e]

[msg MSG_013_0_0 [Ann]]
[s][vp 6 0 0 14 9 0]Hala... 斡Genial![n][f 1 2 50][e]

[msg MSG_014_0_0 [Morgana]]
[s][vp 6 0 0 15 8 0]斡夷Q-qu姻 es eso?![n][f 1 2 40][e]

[msg MSG_015_0_0 [Morgana]]
[s][vp 6 0 0 16 8 0]Nunca hab胤a visto nada igual...[n][f 1 2 60][e]

[msg MSG_016_0_0 [Sombra de Kaneshiro]]
[s][vp 6 0 0 17 20 0]斡M茨s vale que os gan姻is[n]el pan u os matar姻![n][f 1 2 85][e]

[msg MSG_017_0_0 [Makoto]]
[s][vp 6 0 0 18 24 0]Nunca m茨s volver姻[n]a perder la esperanza.[n][f 1 2 88][e]

[msg MSG_018_0_0 [Makoto]]
[s][vp 6 0 0 19 24 0]斡Voy a ir a toda mecha, sin parar![n][f 1 2 60][e]

[msg MSG_019_0_0 [Makoto]]
[s][vp 1 0 0 20 0 0]斡夷A que s胤, Johanna?![n][f 1 2 60][e]

