[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Conque estas son las profundidades[n]del coraz吋n de Kaneshiro...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Contrase隠as...? Parece que[n]ha protegido bien sus secretos[n]m茨s preciados...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero 夷qu姻 querr茨 ocultar...?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Esto huele a complejo[n]de inferioridad.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Solo tenemos que revelar[n]los fallos que 姻l cree que tiene.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]As胤 llegaremos al verdadero[n]n雨cleo de su coraz吋n. S胤,[n]es una tarea bastante sencillita.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Entonces, 夷qu姻 es lo que[n]tanto ansiaba...?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ah, claro, dinero... Se cre胤a[n]capaz de todo siempre que[n]tuviera el dinero suficiente...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]O... quiz茨s era justo al rev姻s...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Sin dinero, no era nadie. Por eso[n]sus inseguridades deben ser[n]cosas que no puede comprar...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]En ese caso...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]P-pero 夷qu姻...? No entiendo qu姻[n]pu隠etas le pasa por la cabeza[n]en estos momentos...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Parece que por ahora[n]solo podemos observar.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En 雨ltima instancia, la raz吋n por[n]la que Kaneshiro adoraba el dinero...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Era para paliar el complejo de[n]inferioridad contra el que luchaba.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Muy bien,[n]su primera inseguridad es...[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Su voz grave.[e]
[s]Su aspecto poco atractivo.[e]
[s]Sus entradas.[e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ahora a por la segunda.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Es hijo 雨nico.[e]
[s]No tiene amigos.[e]
[s]Fue pobre durante su infancia.[e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vale, solo queda una...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]La 雨ltima inseguridad es...[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Su terrible olor corporal.[e]
[s]Su estupidez.[e]
[s]Su f胤sico poco atl姻tico.[e]

[msg MSG_009_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡S胤![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Hostia puta![n]斡Eres brillante, presidenta![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me quito el sombrero yo tambi姻n.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Lo has conseguido![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No ha sido nada.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esto no es el fin.[n]De hecho, las cosas se van[n]a poner mucho m茨s dif胤ciles...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Bueno, es hora de acorralar[n]a Kaneshiro! 斡En marcha![n][f 1 3 65535][w][e]

