[msg MSG_002_0_0 [Voz de Makoto]]
[s][bup 0 6 1 3 1][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Menos mal.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Voz de Makoto]]
[s][bup 0 6 4 3 1][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Ah... Lo siento.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Voz de Makoto]]
[s][bup 0 6 1 3 1][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Supongo que no pasa nada[n]si puedes hacer esos chistes.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Voz de Makoto]]
[s][bup 0 6 0 3 1][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Hay algo que creo[n]que deber胤as saber.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Kaneshiro ha contactado conmigo.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]斡夷Kaneshiro?![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Voz de Makoto]]
[s][bup 0 6 0 3 1][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Ha dicho que cancela nuestra deuda.[n]Parece que tambi姻n[n]ha destruido todas las fotos.[n][f 1 3 65535][w][e]
[s][bup 0 6 3 3 1][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Y, esto...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Mi hermana y su equipo[n]lo han detenido.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 7 301 1][vp 8 0 0 11 65535 0]斡夷Qu姻?![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Voz de Makoto]]
[s][bup 0 6 3 3 1][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Parece que no quer胤an que...[n]desapareciera, no s姻[n]si me entiendes.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Al fin y al cabo, su grupo se[n]consideraba una mafia... Y ya sabes[n]qu姻 les hacen a los chivatos.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Voz de Makoto]]
[s][bup 0 6 0 3 1][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]斡夷Esto significa que conseguimos[n]despertar su coraz吋n?![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]A雨n no sabr胤a decirte.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Voz de Makoto]]
[s][bup 0 6 4 3 1][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Ya...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Voz de Makoto]]
[s][bup 0 6 0 3 1][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]夷Y esos episodios de descontrol[n]que mencion吋 Kaneshiro?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]No estoy seguro, pero supongo[n]que se refer胤a a los incidentes que[n]han salido en todas las noticias.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Quiz茨 est姻 relacionado[n]con esa otra persona que[n]ha estado entrando en Palacios...[n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]No estoy seguro, pero supongo[n]que se refer胤a a los incidentes que[n]han salido en todas las noticias.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Quiz茨 est姻 relacionado[n]con esa otra persona que[n]ha estado entrando en Palacios...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Voz de Makoto]]
[s][bup 0 6 0 3 1][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Cierto...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Dicho eso, ahora solo podemos[n]esperar a que el despertar[n]de Kaneshiro se confirme.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Gracias.[n][f 1 3 65535][w][e]

