[msg MSG_000_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]A pesar de sus esfuerzos,[n]el departamento contra el crimen[n]organizado no atrap吋 a Kaneshiro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Y un d胤a, este se entreg吋 y confes吋[n]todos sus cr胤menes sin m茨s.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Los Ladrones Fantasma...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][vp 8 0 0 6 65535 0]夷Es delito manipular[n]el coraz吋n de alguien?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sae]]
[s][vp 8 0 0 7 65535 0]Depende de los medios utilizados,[n]s胤. Lleva toda la raz吋n.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][vp 8 0 0 8 65535 0]夷Aunque haga admitir a alguien[n]sus fechor胤as y le haga[n]pagar por sus cr胤menes?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Espero que no haya ca胤do[n]en sus redes...[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]*suspiro*[n][f 1 3 65535][w][e]

