[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ese Kaneshiro era una verdadera[n]lacra para la sociedad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Igual que Kamoshida y Madarame.[n]Da隠aron y explotaron a otra gente[n]solo para satisfacer sus deseos...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Hab胤a personas en su entorno[n]que eran conscientes[n]de sus fechor胤as, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Me pregunto por qu姻[n]har胤an la vista gorda...[n]夷Por qu姻 no lo impidi吋 nadie?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Probablemente quer胤an...[e]
[s]No pod胤an.[e]
[s]Estaban demasiado asustados.[e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Pero 夷no tienen coraje?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Entonces es porque[n]no tienen coraje.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Los humanos son muy d姻biles.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Los humanos...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Oye, 夷de verdad crees[n]que podr姻 convertirme[n]en un humano?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Cuando toqu姻 el tesoro,[n]recuper姻 algunos recuerdos.[n]He intentado olvidarlo, pero...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]En realidad puede que[n]no sea humano...[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Seguro que lo eres.[e]
[s]Tienes que tener fe.[e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Qu姻 respuesta tan indiferente.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]夷Con qui姻n te crees que hablas?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 10 301 1][vp 8 0 0 14 65535 0]Ahora que lo pienso, tengo que ser[n]humano. Despu姻s de todo, 斡yo soy el[n]alma de los Ladrones Fantasma![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Venga, no te conviene estar[n]despierto hasta tan tarde.[n]Vamos a dormir.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 1 0 0 0 0 0]Siento que mi v胤nculo[n]con Morgana se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

