[msg MSG_000_0_0 [Director]]
[s][bup 0 204 2 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]夷Cu茨l es tu explicaci吋n para esto?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Me mantengo firme[n]en lo que escrib胤...[n]或Los Ladrones Fantasma son justos位.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Director]]
[s][bup 0 204 4 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]夷Has descubierto qui姻nes son?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]No, ni de lejos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Tras sopesar los hechos, he llegado[n]a la conclusi吋n de que sus actos[n]y principios no est茨n errados.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Y dado que considero que est茨n del[n]lado de la justicia, he decidido[n]concluir mi investigaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Director]]
[s][bup 0 204 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]斡Imposible![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]夷Imposible...?[n]夷Podr胤a mostrarme las pruebas[n]que le han conducido a creer eso?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Director]]
[s][bup 0 204 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Ahora mismo hablaba con el director[n]de una prestigiosa universidad[n]sobre tu carta de recomendaci吋n...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]No ser茨 necesario. Tengo pensado[n]entrar en una buena universidad[n]por m姻ritos propios.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Si me disculpa...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Director]]
[s][bup 0 204 4 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Oye, 斡a雨n no hemos acabado![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Director]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]*suspiro*[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Director]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Se隠or, soy yo.[n]Perd吋n por molestarle...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Respecto a eso...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Director]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]S胤, estoy progresando,[n]pero me he topado[n]con algunos contratiempos...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Igualmente, 夷por qu姻 alguien[n]tan importante como usted est茨[n]interesado en un caso como este?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Director]]
[s][bup 0 204 4 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]斡N-no! 斡No quer胤a decir eso![n]Llevar姻 a cabo la investigaci吋n[n]con todos mis recursos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]S胤, claro...[n]Deber胤a poder decirle algo pronto.[n]S胤, le dar姻 buenas noticias...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Muy bien, gracias por su...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Director]]
[s][bup 0 204 3 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Mierda...[n][f 1 3 65535][w][e]

