[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Oye, busca los ingredientes[n]en el frigor胤fico.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Eh, 夷qu姻 pasa?[n][f 1 3 65535][w][e]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷C吋mo? 夷No est茨 bien?[n]夷No es adorable?[n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Pero me lo recomend吋 el personal...[n]夷Esa impresora no sirve?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]夷C吋mo? 夷Que est茨 bien[n]pero no sirve?[n][f 1 3 65535][w][e]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Vale, ahora mismo voy.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [(SE)佐倉 惣治郎]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0](ため息)[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Esto puede llevarme un rato...[n]Te dejo a cargo del Leblanc.[n][f 1 3 65535][w][e]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Cierra por m胤 si no vuelvo.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Recibido.[e]
[s]夷Te vas a una cita?[e]
[s]Vuelve pronto.[e]

[msg MSG_009_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Te debo una.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Algo as胤...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Pfff, menudo problema...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Reportero de televisi吋n]]
[s][vp 8 0 0 18 65535 0]Y as胤 concluyen las 雨ltimas[n]noticias sobre el sospechoso,[n]Kaneshiro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 19 65535 0]Se dice que este caso es resultado[n]de las acciones de los Ladrones[n]Fantasma, pero 夷usted qu姻 cree?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Especialista]]
[s][vp 8 0 0 20 65535 0]Desconocemos sus m姻todos, pero creo[n]que son una amenaza y que pondr茨n en[n]peligro el estado de derecho del pa胤s.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 21 65535 0]Este peligroso grupo manipula[n]los corazones de la gente.[n]Es lo mismo que lavar el cerebro.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Reportero de televisi吋n]]
[s][vp 8 0 0 22 65535 0]Entiendo. Tiene toda la raz吋n.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Cliente anciana]]
[s][vp 8 0 0 23 7 0]Me pregunto qu姻 estar茨 pasando.[n]夷No hubo tambi姻n un caso[n]similar hace poco?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 24 7 0]夷C吋mo se llamaba?[n]Ya sabes, ese artista famoso...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Cliente anciano]]
[s][vp 8 0 0 25 6 0]Ah, Madarame, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Cliente anciana]]
[s][vp 8 0 0 26 7 0]Castigaron a gente malvada, 夷no?[n]Yo no creo que haya que culpar[n]a los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Cliente anciano]]
[s][vp 8 0 0 27 6 0]Puede que sea cierto, pero...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Cliente anciana]]
[s][vp 8 0 0 28 7 0]夷No piensas lo mismo, querido?[n]Los Ladrones Fantasma no est茨n[n]haciendo nada malo, 夷verdad?[n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Claro que no.[e]
[s]Seguramente no.[e]
[s]No lo s姻.[e]

[msg MSG_030_0_0 [Cliente anciana]]
[s][vp 8 0 0 29 7 0]Hasta 姻l dice[n]que hacen cosas buenas.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Cliente anciana]]
[s][vp 8 0 0 31 7 0]Bueno, yo creo que son buenos.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Cliente anciana]]
[s][vp 8 0 0 31 7 0]Bueno, yo creo que son buenos.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Cliente anciana]]
[s][vp 8 0 0 32 7 0]Vaya, mira qu姻 hora es.[n]Deber胤amos irnos a casa.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Cliente anciano]]
[s][vp 8 0 0 33 6 0]S胤, tienes raz吋n.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Cliente anciano]]
[s][vp 8 0 0 34 6 0]Gracias por la bebida.[n][f 1 3 65535][w][e]

