[msg MSG_000_0_0 [Reportero de televisi吋n]]
[s][vp 8 0 0 1 65535 0]Estos son los detalles del mensaje[n]publicado en la p茨gina web[n]de Medjed.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 65535 0]或A los Ladrones Fantasma tan[n]famosos de Jap吋n: no promulgu姻is[n]vuestra falsa justicia位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 65535 0]或No necesitamos que difund茨is[n]esa farsa. Somos los verdaderos[n]ejecutores de la justicia位.[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]夷Otra vez los Ladrones Fantasma?[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Reportero de televisi吋n]]
[s][vp 8 0 0 5 65535 0]或Sin embargo, somos magn茨nimos.[n]Os daremos una oportunidad[n]de arrepentiros位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 65535 0]或Si despert茨is un coraz吋n,[n]os aceptaremos entre nosotros位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 65535 0]或Si rechaz茨is nuestra oferta,[n]la justicia caer茨 sobre vosotros位.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Justicia, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Reportero de televisi吋n]]
[s][vp 8 0 0 9 65535 0]或Somos Medjed. Actuamos[n]en la sombra. Detendremos el mal位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 10 65535 0]Akechi, 夷por qu姻 crees que[n]han anunciado esto ahora?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]No conozco los detalles, pero[n]no hay duda de que los han[n]provocado los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Pero no puedo decir si es[n]rivalidad o solo quieren[n]llamar la atenci吋n.[n][f 1 3 65535][w][e]
[s][bup 0 9 2 2 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]En cualquier caso, es un incordio.[n][f 1 3 65535][w][e]

[msg MSG_007_3_0 [Reportero de televisi吋n]]
[s][vp 8 0 0 14 65535 0]夷Un incordio?[n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Akechi]]
[s][bup 0 9 2 2 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Tanto Medjed como los[n]Ladrones Fantasma son grupos que[n]defienden una justicia ego胤sta.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Menuda est茨n montando[n]por una tonter胤a...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Los Ladrones Fantasma, 夷eh?[n]夷Qu姻 son? 夷Los conoces?[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]夷Qui姻n?[e]
[s]No.[e]
[s]No me interesa.[e]

[msg MSG_011_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Soy yo el que pregunta.[n]No me contestes con otra pregunta.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]夷Qu姻 es lo que roban?[n]Todav胤a no entiendo esa parte.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]夷Es que no sabes conversar?[n]Deber胤as tener m茨s inter姻s[n]por lo que pasa en el mundo.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Bueno, va siendo hora de irme.[n][f 1 3 65535][w][e]

[msg MSG_014_5_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Cierra bien.[n]Y lo del frigor胤fico...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Supongo que no pasa nada,[n]pero no te pases.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 2 2 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Es posible que aparezca m茨s[n]gente as胤 debido[n]a su influencia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]En ese aspecto, los Ladrones[n]se enfrentan a un delito grave.[n][f 1 3 65535][w][e]

