[msg MSG_000_0_0 [Makoto]]
[s][vp 8 0 0 0 65535 0][f 5 14]夷Has probado a preguntarle[n]al Jefe por Futaba Sakura?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Era sospechoso.[e]
[s]Adivina.[e]
[s]Daba miedo.[e]

[msg MSG_002_0_0 [Makoto]]
[s][vp 8 0 0 0 65535 0][f 5 14]夷En serio?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][vp 8 0 0 0 65535 0][f 5 14]El Jefe sabe algo,[n]pero no te va a decir nada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Supongo que hay algo entre l胤neas.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][vp 8 0 0 0 65535 0][f 5 14]夷Eso quiere decir que no quer胤a[n]que preguntaras por ella?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Qu姻 turbio.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][vp 8 0 0 0 65535 0][f 5 14]Intenta averiguar m茨s sobre 姻l,[n]pero que no te pille.[n][f 1 3 65535][w][e]

