[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]夷Pensabas irte a dormir[n]sin ni siquiera preguntarte[n]d吋nde estaba?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Supongo que el jefe os habl吋[n]de Futaba, y que luego os fuisteis[n]aliviados por el momento.[n][f 1 3 65535][w][e]

[sel SEL_000_2_0 top]
[s]夷C吋mo sabes eso?[e]
[s]夷D吋nde estabas?[e]

[msg MSG_000_4_0 [Morgana]]
[s][bup 0 3 11 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]No subestimes mi capacidad[n]de conseguir informaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_000_6_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Estaba inspeccionando[n]la casa del Jefe.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]No pensaba que Al胤 Bab茨[n]ser胤a tan joven...[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷Joven?[e]
[s]夷C吋mo era?[e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Bueno, ella debe de tener[n]la misma edad que vosotros.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Al menos por la voz[n]parec胤a bastante joven.[n]斡Ah, y ten胤a el pelo largo![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Ten胤a el pelo largo y una voz[n]que sonaba bastante joven.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Bueno..., digo joven,[n]pero creo que tendr茨 m茨s o menos[n]la misma edad que vosotros.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Lo que s胤 est茨 claro[n]es que no es una aficionada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Escuch吋 tu conversaci吋n[n]con el Jefe y tambi姻n puede[n]hackear nuestros chats.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Aunque no pueda enfrentarse[n]a Medjed, puede que tenga[n]alguna pista sobre ellos.[n][f 1 3 65535][w][e]

[sel SEL_004_8_0 top]
[s]夷Qui姻n es...?[e]
[s]Qu姻 chica tan rara.[e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]En cualquier caso,[n]tendremos que contar con Futaba[n]para acercarnos a Medjed.[n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Volvamos a reunirnos ma隠ana.[n]夷Y si quedamos aqu胤?[n]Hace demasiado calor fuera...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Bueno, avisa a todo el mundo.[n][f 1 3 65535][w][e]

