[msg MSG_000_0_0 [Esfinge]]
[s][vp 8 0 0 1 65535 0]斡Fuuuuutaaaaaabaaaaaa![n][f 1 2 170][e]

[msg MSG_001_0_0 [Makoto]]
[s][vp 6 0 0 2 9 0]夷Es una sombra...?[n][f 1 2 50][e]

[msg MSG_002_0_0 [Makoto]]
[s][vp 6 0 0 3 9 0]No... Entonces...[n][f 1 2 58][e]

[msg MSG_003_0_0 [Yusuke]]
[s][vp 6 0 0 4 8 0]斡No es Futaba![n][f 1 2 30][e]

[msg MSG_004_0_0 [Morgana]]
[s][vp 6 0 0 5 6 0]No fastidies...[n][f 1 2 47][e]

[msg MSG_005_0_0 [Ann]]
[s][vp 6 0 0 6 7 0]斡Esto es de locos![n][f 1 2 43][e]

[msg MSG_006_0_0 [Ryuji]]
[s][vp 6 0 0 7 5 0]Si no es una sombra,[n]斡夷qu姻 leches es?![n][f 1 2 74][e]

[msg MSG_007_0_0 [Morgana]]
[s][vp 6 0 0 8 6 0]斡Es una... cognici吋n![n][f 1 2 60][e]

[msg MSG_008_0_0 [Morgana]]
[s][vp 6 0 0 9 6 0]斡Un monstruo que ha creado[n]la cognici吋n de Futaba![n][f 1 2 94][e]

[msg MSG_009_0_0 [Makoto]]
[s][vp 6 0 0 10 9 0]斡夷C吋mo puede ser?![n][f 1 2 55][e]

[msg MSG_010_0_0 [Ryuji]]
[s][vp 6 0 0 11 5 0]斡Eh, cuidado![n][f 1 2 34][e]

[msg MSG_011_0_0 [Ryuji]]
[s][vp 8 0 0 12 65535 0]斡Ah胤 viene![n][f 1 2 20][e]

