[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]夷Estaba disfrutando?[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Lo tengo borroso...[n]No me acuerdo...[n][f 1 3 65535][w][e]

[msg SYS_002_0_0]
[s][vp 8 0 0 0 65535 0]Selecciona la dificultad.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Segura[e]
[s]F茨cil[e]
[s]Normal[e]
[s]Dif胤cil[e]
[s]Despiadada[e]

[msg SYS_004_0_0]
[s][vp 8 0 0 0 65535 0]En [clr 2]Segura[clr 27], podr茨s reintentar[n]los combates las veces que quieras.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Cuando selecciones 或Segura位,[n][clr 2]no podr茨s cambiar la dificultad[clr 27].[n][vp 8 0 0 0 65535 0][f 1 3 65535][w][e]
[s]La dificultad elegida no afectar茨[n]al resultado de la historia.[n]夷Quieres empezar en [clr 2]Segura[clr 27]?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]S胤[e]
[s]No[e]

[msg SYS_004_5_0]
[s][vp 8 0 0 0 65535 0]La historia empezar茨 en [clr 2]Segura[clr 27].[n][f 1 3 65535][w][e]

[msg SYS_006_0_0]
[s][vp 8 0 0 0 65535 0]En [clr 2]F茨cil[clr 27], los combates son m茨s[n]sencillos y podr茨s cambiar[n]la dificultad cuando quieras.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]La dificultad elegida no afectar茨[n]al resultado de la historia.[n]夷Quieres empezar en [clr 2]F茨cil[clr 27]?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]S胤[e]
[s]No[e]

[msg SYS_006_5_0]
[s][vp 8 0 0 0 65535 0]La historia empezar茨 en [clr 2]F茨cil[clr 27].[n][f 1 3 65535][w][e]

[msg SYS_008_0_0]
[s][vp 8 0 0 0 65535 0]En [clr 2]Normal[clr 27], los combates te[n]mantendr茨n en vilo y podr茨s cambiar[n]la dificultad cuando quieras.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]La dificultad elegida no afectar茨[n]al resultado de la historia.[n]夷Quieres empezar en [clr 2]Normal[clr 27]?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]S胤[e]
[s]No[e]

[msg SYS_008_5_0]
[s][vp 8 0 0 0 65535 0]La historia empezar茨 en [clr 2]Normal[clr 27].[n][f 1 3 65535][w][e]

[msg SYS_010_0_0]
[s][vp 8 0 0 0 65535 0]En [clr 2]Dif胤cil[clr 27], los combates[n]son bastante duros y podr茨s cambiar[n]la dificultad cuando quieras.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]La dificultad elegida no afectar茨[n]al resultado de la historia.[n]夷Quieres empezar en [clr 2]Dif胤cil[clr 27]?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]S胤[e]
[s]No[e]

[msg SYS_010_5_0]
[s][vp 8 0 0 0 65535 0]La historia empezar茨 en [clr 2]Dif胤cil[clr 27].[n][f 1 3 65535][w][e]

[msg SYS_012_0_0]
[s][vp 8 0 0 0 65535 0]En [clr 2]Despiadada[clr 27], los combates[n]requieren paciencia y nervios[n]a prueba de bombas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Cuando selecciones 或Despiadada位,[n][clr 2]no podr茨s cambiar la dificultad[clr 27].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]La dificultad elegida no afectar茨[n]al resultado de la historia.[n]夷Quieres empezar en [clr 2]Despiadada[clr 27]?[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]S胤[e]
[s]No[e]

[msg SYS_012_5_0]
[s][vp 8 0 0 0 65535 0]La historia empezar茨 en [clr 2]Despiadada[clr 27].[n][f 1 3 65535][w][e]

