[msg D153_003_LOCK_EV01_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]夷Eh? 夷Es esto...?[n][w][e]

[msg D153_003_LOCK_EV01_mes02 [夷夷??]]
[s]Hay intrusos en la segunda sala[n]de exposici吋n.[n]斡Capturadlos de inmediato![n][w][e]

[msg D153_003_LOCK_EV01_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Joder, 斡hay que irse de aqu胤[n]echando leches! 斡夷Por d吋nde[n]est茨 la salida?![n][w][e]

