[msg D07_01_e407_010_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7115 65535 0]Si no nos ha cambiado la ropa,[n]es que a雨n no nos ve[n]como una amenaza, 夷no?[n][w][e]
[s][bup 0 2 1 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, hablando de eso,[n]夷[f 4 2] no deber胤a[n]haberse puesto el disfraz?[n][w][e]

[msg D07_01_e407_010_mes02 [Ann]]
[s][bup 0 4 3 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ver a alguien disfrazado[n]por ah胤 con un mont吋n de cr胤os[n]de instituto es un poco raro.[n][w][e]

[msg D07_01_e407_010_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]No tendremos que preocuparnos[n]por nada de eso cuando hayamos[n]robado el tesoro... 斡Vamos![n][w][e]

[msg D07_01_e407_015_mes01 [Yusuke]]
[s][bup 0 5 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]El Palacio de Masayoshi Shido...[n]夷Qu姻 misterios ocultar茨?[n][w][e]

[msg D07_01_e407_015_mes02 [Makoto]]
[s][bup 0 6 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Enseguida lo sabremos.[n]斡Que comience la operaci吋n![n][w][e]

[msg D07_02_e408_010_mes01 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2099 65535 0]Primero iremos por el pasillo[n]central, donde est茨n las puertas[n]de la sala de reuniones principal.[n][w][e]

[msg D07_02_e408_010_mes02 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entendido. 斡Vamos![n][w][e]

[msg dummy_mes]
[s]......[n][w][e]

