[msg dummy_mes]
[s]...[n][w][e]

[msg START_COLOR_INFO_RED]
[s]El color ahora es [clr 2]rojo[clr 27].[n][w][e]

[msg START_COLOR_INFO_GREEN]
[s]El color ahora es [clr 2]verde[clr 27].[n][w][e]

[msg START_COLOR_INFO_BLUE]
[s]El color ahora es [clr 2]azul[clr 27].[n][w][e]

[msg START_COLOR_INFO_CYAN]
[s]El color ahora es [clr 2]cian[clr 27].[n][w][e]

[msg START_COLOR_INFO_MAGENTA]
[s]El color ahora es [clr 2]magenta[clr 27].[n][w][e]

[msg START_COLOR_INFO_YELLOW]
[s]El color ahora es [clr 2]amarillo[clr 27].[n][w][e]

[msg START_COLOR_INFO_WHITE]
[s]El color ahora es [clr 2]blanco[clr 27].[n][w][e]

[msg START_COLOR_INFO_NOT_COL]
[s]La luz ahora mismo est茨 apagada.[n][w][e]

[msg CHANGE_COLOR_INFO_RED]
[s]Vale, el color ahora es[n][clr 2]rojo[clr 27].[n][w][e]

[msg CHANGE_COLOR_INFO_GREEN]
[s]Vale, el color ahora es[n][clr 2]verde[clr 27].[n][w][e]

[msg CHANGE_COLOR_INFO_BLUE]
[s]Vale, el color ahora es[n][clr 2]azul[clr 27].[n][w][e]

[msg CHANGE_COLOR_INFO_CYAN]
[s]Vale, el color ahora es[n][clr 2]cian[clr 27].[n][w][e]

[msg CHANGE_COLOR_INFO_MAGENT]
[s]Vale, el color ahora es[n][clr 2]magenta[clr 27].[n][w][e]

[msg CHANGE_COLOR_INFO_YELLOW]
[s]Vale, el color ahora es[n][clr 2]amarillo[clr 27].[n][w][e]

[msg CHANGE_COLOR_INFO_WHITE]
[s]Vale, el color ahora es[n][clr 2]blanco[clr 27].[n][w][e]

[msg CHANGE_COLOR_INFO_NOT_CO]
[s]La luz est茨 apagada ahora.[n][w][e]

[msg D10_11_keeper_Clear_star [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esto ya est茨. Ya podemos ir[n]a por la semilla de deseo.[n][w][e]

[msg D10_11_keeper_Clear_end [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es verdad. Deber胤amos llevarnos[n]todo lo que nos pueda servir.  [n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54503 65535 0]Eso nos lo llevamos.[n][w][e]

