[msg D05_02_e341_036_mes01 [夷夷??]]
[s]斡[clr 2]EJEM[clr 27]! 夷QUI畏NES SOIS, GRANUJAS?[n]夷C遺MO HAB畏IS ENTRADO AQU緯?[n][w][e]
[s]夷QU畏 BUSC威IS[n][clr 2]EN LO MEJOR DE LO MEJOR[clr 27],[n]EN OKUMURA FOODS?[n][w][e]

[sel D05_02_e341_036_selA top]
[s]夷Eres el director jefe?[e]
[s]Nada en particular.[e]
[s]Vamos a charlar un rato.[e]

[msg D05_02_e341_036_selA_0_m [夷夷??]]
[s]夷MMM? AH, CREO QUE YA LO S畏.[n]斡VOSOTROS DEB畏IS SER[n]LOS LADRONES FANTASMA ESOS![n][w][e]
[s]斡[clr 2]JA, JA, JA, JA[clr 27]! MUY BIEN,[n]OS DIR畏 LA VERDAD.[n][w][e]
[s]斡SOY EL DIRECTOR JEFE![n]CREERME O NO[n]YA ES COSA VUESTRA.[n][w][e]
[s]BUENO... 夷ESO ES LO 郁NICO[n]QUE QUER緯AIS PREGUNTARME?[n][w][e]

[msg D05_02_e341_036_selA_1_m [夷夷??]]
[s]ENTONCES, 夷POR QU畏 HAB畏IS VENIDO?[n]斡LARGAOS DE UNA VEZ![n]斡VUESTRA PRESENCIA ME PONE ENFERMO![n][w][e]
[s]斡夷HAY ALGO M威S DE LO QUE[n]QUER威IS HABLAR ANTES[n]DE QUE OS ECHE A PATADAS?![n][w][e]

[msg D05_02_e341_036_selA_2_m [夷夷??]]
[s]NO ME GUSTA ESE TONO, PERO[n]VALE. SE ME HACE RARO[n]HABLAR CON GENTE JOVEN.[n][w][e]
[s]CASI NUNCA INTERACT郁O[n]CON SERES TAN INSIGNIFICANTES.[n]斡[clr 2]JA, JA, JA, JA[clr 27]![n][w][e]
[s]夷QU畏 PASA?[n]斡VENGA, SIGAMOS CON LA CHARLA![n][w][e]

[sel D05_02_e341_036_selB top]
[s]Hablemos del pasado.[e]
[s]Hablemos del futuro.[e]
[s]Hablemos de cualquier cosa.[e]

[msg D05_02_e341_036_selB_0_m [夷夷??]]
[s]QU畏 ADMIRABLE. QUIERES[n]QUE TE HABLE DE MIS 畏XITOS, 夷NO?[n][w][e]
[s]TODOS ERAN HUMILDES COMO T郁[n][clr 2]CUANDO ERA JOVEN[clr 27].[n]PERO LA JUVENTUD DE HOY EN D緯A...[n][w][e]

[msg D05_02_e341_036_selB_1_m [夷夷??]]
[s]夷ALGUIEN SIN NING郁N TIPO DE[n]ESTABILIDAD PREGUNTA POR EL FUTURO?[n]斡[clr 2]JA, JA, JA, JA[clr 27]! QU畏 INGENUO.[n][w][e]
[s]EL FUTURO ES UNA NIMIEDAD[n]PARA UN CHAVAL COMO T郁.[n][w][e]
[s]AUNQUE HE DE ADMITIR[n]QUE ES UN TEMA INTERESANTE...[n][w][e]

[msg D05_02_e341_036_selB_2_m [夷夷??]]
[s]夷QUIERES HABLAR DE TEMAS[n]BANALES CONMIGO?[n]NO PUEDO TOLERARLO.[n][w][e]
[s]斡CALLA Y ESCUCHA![n]斡[clr 2]CUANDO YO ERA JOVEN[clr 27]...![n][w][e]

[msg D05_02_e341_036_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2158 65535 0]Hay que tomar una decisi吋n,[n]Joker. 夷Qu姻 quieres hacer?[n][w][e]

[sel D05_02_e341_036_selC top]
[s]A por 姻l.[f 2 7 0 0 106 1][e]
[s]Deber胤amos irnos.[f 2 7 0 0 106 1][e]

[msg D05_02_e341_036_selC_0_m [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]斡De acuerdo, Joker![n]斡A por 姻l![n][w][e]

[msg D05_02_e341_036_selC_1_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Entonces, 夷no quieres luchar[n]ahora? 斡Pues nos retiramos![n][w][e]

[msg D05_02_e341_036_selC_1_m_2 [夷夷??]]
[s]斡EH! 斡夷AD遺NDE VAIS?![n]斡A郁N NO HEMOS TERMINADO DE HABLAR![n][w][e]

[msg D05_02_e341_036_end_mes0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]Parece que hemos acabado con 姻l.[n]夷Mmm? 夷Qu姻 es eso del suelo?[n][w][e]

[msg D05_02_e341_036_end_mes0_2 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Perfecto! 斡Por fin tenemos[n]la tarjeta del director jefe![n][w][e]

[msg D05_02_e341_036_end_mes0_3 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ya podemos bajar y pasar[n]por la puerta de rango alto![n][w][e]

[msg D05_02_e341_036_end_mes0_4 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9048 65535 0]斡Bueno, vamos a echar[n]un vistazo! 斡Hora de darse el piro![n][w][e]

[msg D05_02_e341_035_mes01 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2128 65535 0]Mm, otro control. 夷Tambi姻n tiene[n]identificaci吋n por rango?[n][w][e]

[msg D05_02_e341_035_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤. Podremos pasar si conseguimos[n]una tarjeta de director jefe[n]o superior.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque por la distribuci吋n[n]de esta planta, parece que no[n]lleva a ning雨n sitio nuevo.[n][w][e]

[msg D05_02_e341_035_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2020 65535 0]Entonces, nuestro objetivo[n]sigue siendo la puerta de abajo.[n][w][e]

[msg D05_02_e341_035_mes04 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 no nos saltamos todo esto[n]y cogemos la tarjeta del[n]presidente? 斡Quiero terminar ya![n][w][e]

[msg D05_02_e341_035_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm, otro control. 夷Tambi姻n tiene[n]identificaci吋n por rango?[n][w][e]

[msg D05_02_e341_035_mes06 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aj茨. Podremos pasar si conseguimos[n]una tarjeta de director jefe[n]o superior.[n][w][e]

[msg D05_02_e341_035_mes07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Podremos pasar si conseguimos[n]una tarjeta de director jefe[n]o superior.[n][w][e]

[msg D05_02_e341_035_clear_me [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3048 65535 0]斡S胤, se ha abierto![n][w][e]

[msg D05_02_e341_035_clear_me_2 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ahora podemos movernos[n]libremente por esta planta![n][w][e]

[msg D05_02_e341_035_clear_me_3 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perfecto. Tenemos la tarjeta de[n]identificaci吋n que quer胤amos, 斡as胤[n]que bajemos cuando hayamos acabado![n][w][e]

