[msg D03_BRIEFING_050_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2165 65535 0]Ya tenemos las dos llaves[n]de acceso. Solo nos queda abrir[n]la puerta para poder continuar.[n][w][e]

[msg D03_BRIEFING_050_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guay, 斡pues adelante![n][w][e]

[msg D03_BRIEFING_050_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1157 65535 0]Cuando crucemos esa puerta,[n]por fin estaremos cerca del final.[n]斡Hay que seguir concentrados![n][w][e]

