[msg GMC_PASSCODE_EXIT_CHECK_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1057 65535 0]夷Qu姻 pasa, Joker?[n]夷Quieres pens茨rtelo mejor?[n][w][e]

[sel YESNO_SEL top]
[s]Pensarlo[e]
[s]No pensarlo[e]

[msg e259_504_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espera, Joker. 夷Y si volvemos[n]a repasar la informaci吋n[n]que tenemos?[n][w][e]

[msg e259_504_mes02 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, buena idea. Veamos...[n]El c吋digo era 或GOLD位, 夷no?[n][w][e]

[msg e259_504_mes03_00 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4133 65535 0]Mm. Hemos encontrado bastantes[n]p茨ginas, pero estas tambi姻n tienen[n]f吋rmulas mezcladas.[n][w][e]

[msg e259_504_mes03_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenemos todas las pistas, as胤 que[n]deber胤amos poder resolverlo[n]si nos calmamos y pensamos un poco.[n][w][e]

[msg e259_504_mes04_00 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2128 65535 0]Mm, a pesar de que hemos reunido[n]muchas p茨ginas, parece que[n]todav胤a nos falta informaci吋n.[n][w][e]

[msg e259_504_mes04_01 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eso significa que no hemos[n]encontrado todas las p茨ginas.[n]Vamos a buscarlas.[n][w][e]

[msg e259_504_mes05_00 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4171 65535 0]A雨n no hemos encontrado[n]m茨s p茨ginas... 夷No podemos resolverlo[n]con lo que tenemos hasta ahora?[n][w][e]

[msg e259_504_mes05_01 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por c吋mo ha sido la cosa[n]hasta ahora, no me cabe duda[n]de que hay m茨s pistas ocultas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiz茨s lo mejor ser胤a[n]buscarlas primero.[n][w][e]

