[msg D10_BRIEFING_170_mes01 [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54502 65535 0]Por fin hemos asegurado[n]una ruta hacia el tesoro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero vamos a enfrentarnos a una[n]deidad, aunque sea artificial.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiero decir que por prepararnos[n]bien no perdemos nada.[n][w][e]

