[msg D10_07_e511_131_mes01 [Akechi]]
[s][bup 0 9 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8127 65535 0]No cabe ninguna duda de que Maruki[n]est茨 m茨s adelante. Prep茨rate bien.[n][w][e]

[msg D10_07_CENDRILLON_mes01 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 quieres hacer, Joker?[n]夷Volvemos a la entrada?[n][w][e]

[sel DO_07_CENDRILLON top]
[s]Salgamos.[e]
[s]Vamos a buscar un poco m茨s.[e]

[msg D10_07_CENDRILLON_mes02 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Pues vamos all茨![n][w][e]

[msg D10_07_CENDRILLON_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Se te ha olvidado[n]un cofre o algo as胤?[n][w][e]

[msg D10_07_CENDRILLON_mes04]
[s]丸城が消え、放送で「1ヶ月何もしない」の声。[n]色々あってパレスから脱出することに。[n][w][e]

