[msg MSG_START_SeedSelect [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0]Creo que las verduras crecer茨n[n]de lo lindo aqu胤. 夷T雨 qu姻 dices?[n][w][e]

[msg MSG_DayCount_Test [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][f 2 5 3 9999 0] va bien. 斡Se podr茨 recoger[n]el [clr 2][var 2]/[var 1][clr 27]![n][w][e]
[s][f 4 10 65535 0 0]Je, je. Espero que tengas ganas.[n][w][e]

[msg MSG_SeedSelect_Cancel [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0]Av胤same cuando quieras plantar[n]algo. Har姻 todo lo posible[n]para que crezca para ti.[n][w][e]

[msg MSG_NowPlant_Pattern01 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0]Je, je. Espero que crezca...[n][w][e]

[msg MSG_NowPlant_Pattern02 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0]Este est茨 yendo bien.[n]Seguro que crecer茨 mucho.[n][w][e]

[msg MSG_NowPlant_Pattern03 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0]Hay que tener cuidado con[n]las ra胤ces para no da隠arlas.[n]Espero que crezca bien.[n][w][e]

[msg MSG_NowPlant_Pattern04 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0]Las plantas crecen mejor[n]si hablas con ellas.[n]Creced mucho, 夷vale?[n][w][e]

[msg MSG_GetPlant_Think [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0]Ya han crecido lo suficiente.[n]斡Es hora de recolectar![n][w][e]

[msg MSG_GetPlant_Low [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0]斡Estos me dan muy buena espina![n]Hay que tener cuidado[n]y respeto, 夷vale?[n][w][e]

[msg MSG_GetPlant_High [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0]斡Tienen muy buena pinta![n]Hay que tener cuidado[n]y respeto, 夷vale?[n][w][e]

[msg MSG_Plnater_HarvestNow [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0]All茨 vamos... Je, je.[n]Han crecido bastante.[n][w][e]

