[msg MSG_e296_113_000 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Eh, esta estatua tiene una gema.[n]Nos la llevamos, 夷no?[n][w][e]

[msg MSG_e296_113_001 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6165 65535 0]Espera, aqu胤 hay una inscripci吋n.[n]或Una maldici吋n caer茨 sobre aquellos[n]que intenten robar esta gema位.[n][w][e]

[msg MSG_e296_113_002 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aqu胤 tambi姻n... Ya vimos lo mismo[n]en la otra estatua de Anubis.[n][w][e]

[msg MSG_e296_113_003 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]No podemos tomarnos en serio[n]algo as胤, 夷verdad? Venga, c吋gela.[n][w][e]

[msg MSG_e296_113_004 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, esta estatua tiene una gema.[n]Nos la llevamos, 夷no?[n][w][e]

[msg MSG_e296_113_005 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, aqu胤 hay[n]una inscripci吋n grabada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]或Una maldici吋n caer茨 sobre aquellos[n]que intenten robar esta gema位.[n][w][e]

[msg MSG_e296_113_006 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]T胤o, no podemos asustarnos por[n]una maldici吋n de nada, 夷verdad?[n]Venga, c吋gela.[n][w][e]

[sel D04_03_e296_113_selA top]
[s]Coger la gema[e]
[s]No coger la gema[e]

[msg D04_03_e296_113_selA_0_m [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Genial, la tenemos. Vamos.[n][w][e]

[msg D04_03_e296_113_selA_0_m_2 [Voz profunda]]
[s]Una maldici吋n caer茨 sobre vosotros...[n][w][e]

[msg D04_03_e296_113_selA_1_m [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6027 65535 0]S胤, ser茨 mejor que no.[n]No es que yo crea[n]en maldiciones y esas cosas, pero...[n][w][e]

[msg MSG_e296_113_AF01_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Venga, c吋gela ya.[n][w][e]

[msg MSG_e296_115_000 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, 夷quieres dejar[n]la gema que cogimos antes?[n][w][e]

[sel SEL_e296_115_001 top]
[s]Ponerla en su sitio[e]
[s]No ponerla en su sitio[e]

[msg MSG_e296_115_002 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, siempre podemos volver[n]a por ella si la necesitamos.[n][w][e]

[msg MSG_e296_115_003 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uy, parece que el ambiente[n]ha cambiado.[n][w][e]

[msg MSG_e296_115_004 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Habremos roto la maldici吋n?[n]Deber胤amos comprobar[n]si ha cambiado algo.[n][w][e]

[msg MSG_e296_115_005 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ah, s胤? Bueno, supongo que eso[n]tambi姻n vale.[n][w][e]

[msg MSG_e296_118_000 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, es otra estatua[n]de Anubis. Tambi姻n tiene[n]una inscripci吋n...[n][w][e]

[msg MSG_e296_118_001 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pone 或Una maldici吋n caer茨 sobre[n]aquellos que intenten robar[n]esta gema位. 斡夷Otra vez lo mismo?![n][w][e]

[msg MSG_e296_118_002 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero esta estatua no est茨[n]sosteniendo ninguna gema.[n]夷Qu姻 significa todo esto?[n][w][e]

[msg MSG_e296_118_003 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, es una estatua de Anubis.[n]Aqu胤 hay una inscripci吋n...[n][w][e]

[msg MSG_e296_118_004 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]或Una maldici吋n caer茨 sobre aquellos[n]que intenten robar esta gema位.[n][w][e]

[msg MSG_e296_118_005 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]T胤o, no podemos acojonarnos por[n]una mierda de maldici吋n.[n]Venga, p胤llala.[n][w][e]

[msg MSG_e296_118_006 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero esta estatua no est茨[n]sosteniendo ninguna gema.[n]夷Qu姻 significa todo esto?[n][w][e]

[msg MSG_e296_118_007 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espera, nosotros tenemos una.[n]夷Quieres ponerla aqu胤?[n][w][e]

[sel SEL_e296_118_008 top]
[s]Colocar la gema[e]
[s]No colocar la gema[e]

[msg MSG_e296_118_009 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, el ambiente ha cambiado[n]de un modo imperceptible...[n]Quiz茨 hemos roto la maldici吋n.[n][w][e]

[msg MSG_e296_118_00A [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Para empezar, ah胤 no hab胤a[n]ninguna gema. 斡No es justo que[n]nos obligue a colocar una![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me da igual que sea un dios[n]perruno, 斡no es justo y punto![n][w][e]

[msg MSG_e296_118_00B [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Seguro que alguien vino antes[n]que nosotros y se la llev吋.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En fin, hay que buscar[n]una que podamos colocar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A lo mejor hay una por aqu胤.[n]Vamos a echar un vistazo.[n][w][e]

[msg MSG_e296_118_00C [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Creo que es lo m茨s seguro.[n]La gema que tenemos no era[n]de esta estatua.[n][w][e]

[msg MSG_e296_118_AF01_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 es toda esa mierda de la[n]maldici吋n? Da igual, 夷quieres[n]colocar la gema que tenemos?[n][w][e]

[sel SEL_e296_118_AF01_001 top]
[s]Colocar la gema[e]
[s]No colocar la gema[e]

[msg MSG_e296_118_AF01_002 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, el ambiente ha cambiado[n]de un modo imperceptible...[n]Quiz茨 hemos roto la maldici吋n.[n][w][e]

[msg MSG_e296_118_AF01_003 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Para empezar, ah胤 no hab胤a[n]ninguna gema. 斡No es justo que[n]nos obligue a colocar una![n][w][e]

[msg MSG_e296_118_AF01_004 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya gilipollez de maldici吋n.[n]Para empezar, ah胤 no[n]hay ninguna gema.[n][w][e]

[msg MSG_e296_118_AF02_000 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que la gema que dejamos[n]en la estatua de Anubis sigue all胤.[n]夷Nos la llevamos?[n][w][e]

[sel SEL_e296_118_AF02_001 top]
[s]Coger la gema[e]
[s]Dejar la gema[e]

[msg MSG_e296_118_AF02_002 [Voz profunda]]
[s]Una maldici吋n caer茨 sobre vosotros...[n][w][e]

[msg MSG_e296_118_AF02_003 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No me ha gustado nada[n]c吋mo ha sonado eso.[n]夷Crees que nos ir茨 bien?[n][w][e]

[msg MSG_e296_118_AF02_004 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, no es problema nuestro. Vamos,[n]que somos nosotros los que trajimos[n]la gema aqu胤 en primer lugar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hora de pirarse, Joker.[n][w][e]

[msg MSG_e296_118_AF02_005 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si t雨 lo dices... Vamos.[n][w][e]

[msg D155_07_c_01_mes01]
[s]La estatua no tiene ninguna gema...[n][w][e]

[msg D155_07_c_02_mes01]
[s]La estatua no tiene ninguna gema...[n][w][e]

[msg D155_07_c_02_mes02 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenemos una gema.[n]夷Probamos a colocarla aqu胤?[n][w][e]

[msg MSG_e296_118_00C_AF [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]De acuerdo. Sigamos adelante.[n][w][e]

[msg D155_07_GIMMICK_NG_01_me [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, tenemos una gema de[n]otro sitio, pero creo que[n]no hay que usarla aqu胤.[n][w][e]

[msg D155_07_GIMMICK_NG_01_me_2 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tienes raz吋n. Busquemos otro lugar[n]donde colocarla.[n][w][e]

[msg D155_07_GIMMICK_NG_02_me [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, tenemos una gema de[n]otro sitio, pero creo que[n]no hay que usarla aqu胤.[n][w][e]

[msg D155_07_GIMMICK_NG_02_me_2 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tienes raz吋n. Busquemos otro lugar[n]donde colocarla.[n][w][e]

