[sel DUNGEON_CHECK_SEL top]
[s]Guardar progreso de exploraci吋n[f 2 7 0 0 106 1][e]
[s]Hablar con el equipo[f 2 7 0 0 106 1][e]
[s]Usar objetos de curaci吋n[f 2 7 0 0 106 1][e]
[s]Ir a la entrada[f 2 7 0 0 106 1][e]
[s]Seguir explorando[f 2 7 0 0 106 1][e]

[msg DUNGEON_CHECK_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1157 65535 0]夷Qu姻 vas a hacer, Joker?[n][w][e]

[msg DUNGEON_CHECK_PC09_mes01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Cu茨l es el plan?[n][w][e]

[msg DUNGEON_REST_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1157 65535 0]Aprovechemos para descansar.[n]夷Cu茨l es el plan, Joker?[n][w][e]

[msg DUNGEON_REST_PC09_mes01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puede que descansar sea lo mejor.[n]夷O prefieres hacer otra cosa?[n][w][e]

[msg DUNGEON_CHECK_AF_PC03_me [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1186 65535 0]夷Hay algo m茨s[n]de lo que quieras hablar?[n][w][e]

[msg DUNGEON_CHECK_AF_PC09_me [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Hay algo m茨s[n]de lo que quieras hablar?[n][w][e]

[msg DUNGEON_CHECK_NOT_PC03_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Uy, 夷ya hemos acabado?[n][w][e]

[msg DUNGEON_CHECK_NOT_PC09_m [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale. 夷Hemos acabado?[n][w][e]

[msg DUNGEON_BRIEFING_OR_STAT [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De qu姻 quieres hablar?[n][w][e]

[msg DUNGEON_BRIEFING_OR_STAT_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻? 夷No vamos a hablar?[n][w][e]

[msg DUNGEON_BRIEFING_OR_STAT_3 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De qu姻 quieres que hablemos?[n][w][e]

[msg DUNGEON_BRIEFING_OR_STAT_4 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale. 夷Hemos acabado?[n][w][e]

[sel DUNGEON_BRIEFING_OR_STAT_5 top]
[s]夷C吋mo vamos?[f 2 7 0 0 106 1][e]
[s]夷C吋mo estamos?[f 2 7 0 0 106 1][e]
[s]Nada en particular.[e]

[sel AT_DUNGEON_CHECK_SEL top]
[s]Guardar progreso de exploraci吋n[f 2 7 0 0 106 1][e]
[s]Hablar con el equipo[f 2 7 0 0 106 1][e]
[s]Usar objetos de curaci吋n[f 2 7 0 0 106 1][e]
[s]Ir a la entrada[f 2 7 0 0 106 1][e]
[s]Seguir explorando[f 2 7 0 0 106 1][e]

[msg DUNGEON_CHECK_END_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7051 65535 0]Vamos.[n][w][e]

[msg DUNGEON_CHECK_END_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1051 65535 0]Entendido. En marcha.[n][w][e]

[msg DUNGEON_CHECK_END_mes04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6099 65535 0]Bueno, aqu胤 ya no hay[n]nada m茨s que hacer.[n][w][e]

[msg DUNGEON_CHECK_END_mes05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4052 65535 0]Vale. Pues v茨monos.[n][w][e]

[msg DUNGEON_CHECK_END_mes06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2051 65535 0]Tienes raz吋n. Deber胤amos irnos.[n][w][e]

[msg DUNGEON_CHECK_END_mes07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9055 65535 0]斡No se hable m茨s! 斡En marcha![n][w][e]

[msg DUNGEON_CHECK_END_mes08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3052 65535 0]S胤, deber胤amos irnos.[n][w][e]

[msg DUNGEON_CHECK_END_mes09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8099 65535 0]Entendido. V茨monos.[n][w][e]

[msg DUNGEON_CHECK_END_mes10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57106 65535 0]O胤do cocina. 斡Vamos![n][w][e]

[msg DUNGEON_CHECK_END_PC03_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, ya va siendo hora de que nos[n]vayamos. De todos modos,[n]no podemos avanzar.[n][w][e]

[msg SAFEROOM_GOTO_ENTRANCE_P [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Quieres que volvamos a la entrada?[n][w][e]

[msg SAFEROOM_GOTO_ENTRANCE_P_2 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Quieres volver a la entrada?[n][w][e]

[sel SAFEROOM_GOTO_ENTRANCE_S top]
[s]Vamos.[f 2 7 0 0 106 1][e]
[s]Esperad.[f 2 7 0 0 106 1][e]

[msg SAFEROOM_GOTO_ENTRANCE_E [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Volvemos a casa?[n][w][e]

[msg SAFEROOM_GOTO_ENTRANCE_E_2 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entonces regresemos.[n][w][e]

[msg SAFEROOM_GOTO_ENTRANCE_N [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale, avisa cuando quieras[n]que regresemos.[n][w][e]

[msg SAFEROOM_GOTO_ENTRANCE_N_2 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entiendo.[n]Avisa cuando quieras que volvamos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_01_P [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, a雨n nos queda tiempo hasta[n]la fecha l胤mite. Ir a casa[n]me parece buena idea.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_01_P_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cierto, parece que a雨n queda hasta[n]la fecha l胤mite. V茨monos a casa.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_01_P_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, no hace falta ir con prisas.[n]Creo que va siendo hora de volver.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_01_P_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm, todav胤a queda[n]para la fecha l胤mite.[n]Deber胤amos aprovechar e irnos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_01_P_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tienes raz吋n. Tenemos algo de[n]tiempo, as胤 que, de momento,[n]marcharnos es lo mejor.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_01_P_6 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, todav胤a queda para la fecha[n]l胤mite. Va siendo hora de[n]que nos vayamos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_01_P_7 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Supongo que tenemos tiempo antes[n]de la fecha l胤mite. V茨monos, anda.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_01_P_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cierto, tenemos mucho tiempo antes[n]de la fecha l胤mite. La retirada[n]es una decisi吋n sabia.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_01_P_9 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, tenemos tiempo de sobra[n]hasta la fecha l胤mite. Volvamos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_02_0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos un poco justos de tiempo,[n]pero creo que podemos volver.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_02_0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S姻 que vamos justos de tiempo,[n]pero quiz茨 sea buena idea volver.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_02_0_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos quedamos sin tiempo,[n]pero a lo mejor volver[n]no es tan mala idea.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_02_0_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos quedamos sin tiempo,[n]pero quiz茨 no sea mala idea[n]irnos a casa.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_02_0_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S姻 que la fecha l胤mite se acerca,[n]pero deber胤amos pensar en irnos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_02_0_6 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se nos acaba el tiempo,[n]pero es mejor que nos vayamos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_02_0_7 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos quedamos sin tiempo,[n]pero quiz茨 volver no sea mala idea.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_02_0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estamos perdiendo tiempo,[n]pero irnos ahora es lo mejor.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_02_0_9 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos queda poco tiempo, pero quiz茨[n]retirarse sea lo m茨s sensato.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_03_0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hemos asegurado el camino, 夷no?[n]Venga, pues v茨monos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_03_0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya hemos asegurado el camino[n]hacia el tesoro. Si no tienes[n]nada m茨s que hacer, v茨monos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_03_0_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sabemos d吋nde est茨 el tesoro,[n]夷no? V茨monos ya.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_03_0_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hemos asegurado el camino hacia el[n]tesoro. Si no tienes nada m茨s[n]que hacer, v茨monos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_03_0_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No hemos asegurado ya el camino[n]hacia el tesoro? Si no tienes[n]nada m茨s que hacer, v茨monos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_03_0_6 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El camino al tesoro est茨 despejado.[n]Si no tienes que hacer nada m茨s,[n]v茨monos de aqu胤.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_03_0_7 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No hemos asegurado ya el camino[n]hacia el tesoro? Si no tienes[n]nada m茨s que hacer, v茨monos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_03_0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hemos asegurado el camino hacia[n]el tesoro, 夷no? Si no hay nada m茨s[n]que hacer, v茨monos.[n][w][e]

[msg SAFEROOM_EXIT_CHECK_03_0_9 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya hemos asegurado el camino[n]hacia el tesoro. Deber胤amos volver[n]si no tenemos nada m茨s que hacer.[n][w][e]

[msg PARTY_ALL_Good_01_PC02_m [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7138 65535 0]斡Yo estoy bien! Parece[n]que el resto tambi姻n puede seguir.[n][w][e]

[msg PARTY_ALL_Good_01_PC03_m [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1109 65535 0]Nadie tiene pinta de estar cansado.[n]斡A雨n nos queda energ胤a para seguir![n][w][e]

[msg PARTY_ALL_Good_01_PC04_m [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6023 65535 0]斡Yo estoy bien! Y creo que el resto[n]tambi姻n puede seguir.[n][w][e]

[msg PARTY_ALL_Good_01_PC05_m [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4021 65535 0]A m胤 me sobra aguante[n]y energ胤a y creo que el resto[n]est茨 en las mismas.[n][w][e]

[msg PARTY_ALL_Good_01_PC06_m [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2109 65535 0]No creo que haya problemas ahora[n]mismo. Todo lo contrario,[n]nos sobra energ胤a.[n][w][e]

[msg PARTY_ALL_Good_01_PC07_m [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9177 65535 0]Todos estamos de lujo,[n]as胤 que podemos continuar.[n][w][e]

[msg PARTY_ALL_Good_01_PC08_m [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3120 65535 0]Parece que todos estamos bien.[n]Yo tengo energ胤a[n]para dar y regalar.[n][w][e]

[msg PARTY_ALL_Good_01_PC09_m [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8020 65535 0]No hay ning雨n problema ahora mismo.[n]Es m茨s, tenemos[n]energ胤a de sobra.[n][w][e]

[msg PARTY_ALL_Good_01_PC10_m [[f 4 31 10 0]]]
[s][bup 0 10 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57026 65535 0]斡No hay problema! 斡Sigamos![n][w][e]

[msg PARTY_Bad_01_PC02_mes [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]Uf, me estoy quedando[n]sin combustible...[n][w][e]

[msg PARTY_Bad_01_PC03_mes [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1182 65535 0]Jo, al final me he cansado y todo.[n][w][e]

[msg PARTY_Bad_01_PC04_mes [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6028 65535 0]Ay, lo siento.[n]Estoy un poco cansada...[n][w][e]

[msg PARTY_Bad_01_PC05_mes [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4030 65535 0]Mis disculpas,[n]pero apenas tengo fuerza...[n][w][e]

[msg PARTY_Bad_01_PC06_mes [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2178 65535 0]Perd吋n...[n]Ya no soy capaz de concentrarme.[n][w][e]

[msg PARTY_Bad_01_PC07_mes [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9043 65535 0]Qu姻 sue隠o...[n]Necesito recargar las pilas.[n][w][e]

[msg PARTY_Bad_01_PC08_mes [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]Lo siento, estoy falta de energ胤as...[n][w][e]

[msg PARTY_Bad_01_PC09_mes [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8038 65535 0]Perdona, pero no soy capaz[n]de centrarme...[n][w][e]

[msg PARTY_Bad_01_PC10_mes [[f 4 31 10 0]]]
[s][bup 0 10 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57045 65535 0]Perd吋n...[n]No soy capaz de concentrarme.[n][w][e]

[msg PARTY_RESERVE_Good_01_PC [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo me muero por seguir.[n]夷Quieres cambiar?[n][w][e]

[msg PARTY_RESERVE_Good_01_PC_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A m胤 me sobra energ胤a.[n]Quiz茨s deber胤amos cambiar[n]a alg雨n compa隠ero.[n][w][e]

[msg PARTY_RESERVE_Good_01_PC_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo puedo seguir.[n]C茨mbiame por alguien, si quieres.[n][w][e]

[msg PARTY_RESERVE_Good_01_PC_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Luchar姻 si es necesario.[n]Av胤same si necesitas[n]que sustituya a alguien.[n][w][e]

[msg PARTY_RESERVE_Good_01_PC_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora mismo me siento de lujo.[n]夷Quieres que sustituya a alg雨n[n]compa隠ero que est姻 m茨s cansado?[n][w][e]

[msg PARTY_RESERVE_Good_01_PC_6 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo puedo seguir. Av胤same si[n]necesitas que sustituya a alguien.[n][w][e]

[msg PARTY_RESERVE_Good_01_PC_7 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo tengo fuerzas de sobra. 夷Quieres[n]que reemplace a alg雨n compa隠ero?[n][w][e]

[msg PARTY_RESERVE_Good_01_PC_8 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo puedo continuar.[n]夷Quieres que sustituya a alguien?[n][w][e]

[msg PARTY_ALL_NORMAL_01_PC02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]Yo estoy empezando a estar cansado,[n]pero no pienso rendirme.[n][w][e]

[msg PARTY_ALL_NORMAL_01_PC04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6023 65535 0]Puede que me est姻 cansando un poco,[n]pero puedo seguir.[n]Luchar姻 sin problemas.[n][w][e]

[msg PARTY_ALL_NORMAL_01_PC05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4020 65535 0]Estoy un poco cansado ahora mismo.[n]No me encuentro muy bien,[n]pero luchar姻 si es necesario.[n][w][e]

[msg PARTY_ALL_NORMAL_01_PC06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2035 65535 0]Me encuentro algo deca胤da,[n]pero, tranquilo, que puedo seguir.[n][w][e]

[msg PARTY_ALL_NORMAL_01_PC07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9196 65535 0]Estamos en plena forma.[n]斡As胤 me gusta, Ladrones Fantasma![n][w][e]

[msg PARTY_ALL_NORMAL_01_PC08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3020 65535 0]Estoy un poco cansada, pero no pasa[n]nada. Tengo fuerzas para luchar.[n][w][e]

[msg PARTY_ALL_NORMAL_01_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8020 65535 0]Mm, el cansancio ya hace mella,[n]pero no es para tanto, 夷no?[n][w][e]

[msg PARTY_ALL_NORMAL_01_PC10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57025 65535 0]Todo el mundo parece cansado,[n]pero creo que podemos seguir.[n][w][e]

[msg PARTY_LIMIT_CHECK_01_PC0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Nos quedan [var 1] d胤as...[n][w][e]

[msg PARTY_LIMIT_CHECK_01_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1192 65535 0]La fecha l胤mite es[n]dentro de [var 1] d胤as.[n][w][e]

[msg PARTY_LIMIT_CHECK_01_PC0_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Tenemos [var 1] d胤a(s)[n]hasta la fecha l胤mite, 夷no?[n][w][e]

[msg PARTY_LIMIT_CHECK_01_PC0_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4079 65535 0]La fecha l胤mite es[n]dentro de [var 1] d胤as...[n][w][e]

[msg PARTY_LIMIT_CHECK_01_PC0_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]Todav胤a tenemos [var 1] d胤as[n]para asegurar el camino.[n][w][e]

[msg PARTY_LIMIT_CHECK_01_PC0_6 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9156 65535 0]斡No os olvid姻is de que quedan[n][var 1] d胤as para la fecha l胤mite![n][w][e]

[msg PARTY_LIMIT_CHECK_01_PC0_7 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3018 65535 0]Nos quedan [var 1] d胤as, 夷no?[n][w][e]

[msg PARTY_LIMIT_CHECK_01_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8018 65535 0]Tenemos aproximadamente [var 1] d胤a(s)[n]hasta la fecha l胤mite.[n][w][e]

[msg PARTY_LIMIT_CHECK_01_PC1 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57113 65535 0]Tenemos [var 1] d胤a(s)[n]hasta la fecha l胤mite.[n][w][e]

[msg PARTY_LIMIT_HIGH_01_PC02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A雨n tenemos tiempo.[n]Volver es buena idea.[n][w][e]

[msg PARTY_LIMIT_HIGH_01_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A雨n hay tiempo hasta la fecha[n]l胤mite, as胤 que tranquilos.[n][w][e]

[msg PARTY_LIMIT_HIGH_01_PC04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Volver ahora no es mala idea.[n]A雨n nos sobra tiempo.[n][w][e]

[msg PARTY_LIMIT_HIGH_01_PC05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A雨n quedan unos cuantos d胤as.[n]夷Y si nos lo tomamos con tranquilidad[n]y nos vamos a casa?[n][w][e]

[msg PARTY_LIMIT_HIGH_01_PC06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos sobra tiempo,[n]as胤 que actuemos con cautela[n]y tom姻monoslo con calma.[n][w][e]

[msg PARTY_LIMIT_HIGH_01_PC07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenemos mogoll吋n de tiempo.[n]Actuemos con cabeza.[n][w][e]

[msg PARTY_LIMIT_HIGH_01_PC08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No hace falta avanzar al tunt雨n.[n]Volvamos, anda.[n][w][e]

[msg PARTY_LIMIT_HIGH_01_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tranquilidad y buenos alimentos.[n]Retirarse es lo m茨s inteligente.[n][w][e]

[msg PARTY_LIMIT_HIGH_01_PC10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenemos tiempo m茨s que suficiente.[n]夷Y si nos vamos?[n][w][e]

[msg PARTY_LIMIT_LOW_01_PC02_ [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos estamos quedando sin d胤as.[n]Hoy tocar茨 curr茨rselo un poco m茨s.[n][w][e]

[msg PARTY_LIMIT_LOW_01_PC03_ [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La fecha l胤mite se acerca. Igual hay[n]que tirar tanta precauci吋n por[n]la borda y seguir.[n][w][e]

[msg PARTY_LIMIT_LOW_01_PC04_ [Ann]]
[s][bup 0 4 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos estamos quedando sin tiempo...[n]Deber胤amos continuar un poco m茨s,[n]aunque sea arriesgado.[n][w][e]

[msg PARTY_LIMIT_LOW_01_PC05_ [Yusuke]]
[s][bup 0 5 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos quedan pocos d胤as, as胤 que no[n]podemos perder el tiempo.[n]Continuemos.[n][w][e]

[msg PARTY_LIMIT_LOW_01_PC06_ [Makoto]]
[s][bup 0 6 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La fecha l胤mite se aproxima.[n]Hay que seguir avanzando.[n][w][e]

[msg PARTY_LIMIT_LOW_01_PC07_ [Futaba]]
[s][bup 0 8 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Estamos en la recta final![n]夷No deber胤amos seguir?[n][w][e]

[msg PARTY_LIMIT_LOW_01_PC08_ [Haru]]
[s][bup 0 7 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S姻 que las cosas est茨n dif胤ciles,[n]pero no nos queda tiempo.[n]Sigamos adelante.[n][w][e]

[msg PARTY_LIMIT_LOW_01_PC09_ [Akechi]]
[s][bup 0 9 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya no nos queda tiempo.[n]Deber胤amos continuar.[n][w][e]

[msg PARTY_LIMIT_LOW_01_PC10_ [[f 4 31 10 0]]]
[s][bup 0 10 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No nos queda mucho tiempo.[n]夷Y si avanzamos un poco m茨s?[n][w][e]

[msg SP_CHECK_80_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Todo el mundo est茨 a tope.[n]Creo que podemos seguir[n]explorando si te apetece.[n][w][e]

[msg SP_CHECK_60_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Todo el mundo parece estar bien,[n]pero tom茨oslo con calma.[n][w][e]

[msg SP_CHECK_40_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Algunos est茨n cansados.[n]Deber胤as pensar en ellos, Joker.[n][w][e]

[msg SP_CHECK_20_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Todo el mundo est茨 cansado...[n]No los presiones mucho, 夷vale?[n][w][e]

[msg SP_CHECK_20_PC03_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El equipo titular est茨 reventado...[n]No los presiones mucho.[n][w][e]

[msg SP_CHECK_00_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Todo el mundo est茨 cansado...[n]Ser胤a peligroso luchar as胤.[n][w][e]

[msg SP_CHECK_00_PC03_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El equipo titular est茨 hecho polvo...[n]Ser胤a peligroso luchar as胤.[n][w][e]

[msg PARTY_Bad_EX_PC01_mes01 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1038 65535 0]Tienes cara de cansado, Joker.[n]夷Va todo bien?[n][w][e]

[msg PARTY_Bad_EX_PC01_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]Vaya cara tienes, Joker.[n]夷Te pasa algo?[n][w][e]

[msg PARTY_Bad_EX_PC01_mes03 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]Pareces agotado. 夷Est茨s bien?[n][w][e]

[msg PARTY_RESERVE_Good_EX_PC [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tengo energ胤a para dar y regalar.[n]斡Cuenta conmigo, colega![n][w][e]

[msg PARTY_RESERVE_Good_EX_PC_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tengo energ胤a de sobra.[n]Cuenta conmigo para luchar.[n][w][e]

[msg PARTY_RESERVE_Good_EX_PC_3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo puedo seguir.[n]斡Mi poder es tuyo, Joker![n][w][e]

[msg PARTY_RESERVE_Good_EX_PC_4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A雨n puedo luchar.[n]Cuenta con mi poder, Joker.[n][w][e]

[msg PARTY_RESERVE_Good_EX_PC_5 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tengo energ胤a de sobra.[n]斡Luchar姻 e ir姻 a por todas![n]斡Conf胤a en m胤![n][w][e]

[msg PARTY_RESERVE_Good_EX_PC_6 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Soy capaz de seguir.[n]Cuenta conmigo si lo necesitas.[n][w][e]

[msg PARTY_RESERVE_Good_EX_PC_7 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo todav胤a tengo fuerza.[n]Aprovecha mis poderes si crees[n]que te resultar茨n 雨tiles.[n][w][e]

[msg PARTY_RESERVE_Good_EX_PC_8 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puedo continuar sin problema.[n]Cuenta conmigo.[n][w][e]

[msg SP_CHECK_40_limit_PC03_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Algunos est茨n cansados,[n]pero, con los pocos d胤as que faltan,[n]no nos queda elecci吋n.[n][w][e]

[msg SP_CHECK_20_limit_PC03_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que todo el mundo[n]est茨 agotado...[n][w][e]
[s]Deber胤amos volver.[n]Aunque, ahora que lo pienso,[n]no nos queda mucho tiempo.[n][w][e]

[msg SP_CHECK_00_limit_PC03_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Todo el mundo est茨 cansado...[n][w][e]
[s]Lo mejor ser胤a irnos,[n]pero no queda tiempo.[n][w][e]

[msg SP_RESERVE_20_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 no cambias[n]a los que est姻n cansados?[n][w][e]

[msg SP_RESERVE_00_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 no cambiamos[n]el equipo titular?[n][w][e]

[msg HP_CHECK_40_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, ojo con el aguante del equipo.[n]Algunos estamos en las 雨ltimas.[n][w][e]

[msg DEBUG_CALENDAR_10_TITLE]
[s]Obj. de curaci吋n de la Hab. segura[n][e]

[sel DEBUG_CALENDAR_10_SEL top]
[s]Cancelar[e]

[sel START_CHECK_SEL top]
[s]Ir a la 雨ltima Habitaci吋n segura[e]
[s]Infiltrarse tal cual[e]
[s]No entrar a雨n[e]

[msg START_CHECK_MES [Morgana]]
[s][bup 0 3 0 65535 0]Bueno, 夷por d吋nde quieres[n]empezar a explorar?[n][w][e]

[msg START_CHECK_MES_NEXT [Morgana]]
[s][bup 0 3 0 65535 0]Elige sabiamente la ubicaci吋n.[n][w][e]

[sel DUNGEON_EXIT_SEL top]
[s]*Especial[e]
[s]Volver al mundo real[e]
[s]Quedarse un poco m茨s[e]

[sel DUNGEON_EXIT_154_SEL top]
[s]Ir a la ciudad[e]
[s]Volver al mundo real[e]
[s]Quedarse un poco m茨s[e]

[sel DUNGEON_EXIT_155_SEL top]
[s]Ir a la ciudad[e]
[s]Volver al mundo real[e]
[s]Quedarse un poco m茨s[e]

[msg D01_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Kamoshida.[n]Buen trabajo.[n][w][e]

[msg D02_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Madarame.[n]Buen trabajo.[n][w][e]

[msg D03_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Kaneshiro.[n]Buen trabajo.[n][w][e]

[msg D04_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Futaba.[n]Buen trabajo.[n][w][e]

[msg D05_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Okumura.[n]Buen trabajo.[n][w][e]

[msg D06_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Niijima.[n]Buen trabajo.[n][w][e]

[msg D07_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Shido.[n]Buen trabajo.[n][w][e]

[msg D08_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde Mementos. Buen trabajo.[n][w][e]

[msg D10_EXIT_MES [Navegador del Metaverso]]
[s]Volviendo al mundo real[n]desde el Palacio de Maruki.[n]Buen trabajo.[n][w][e]

[msg DUNGEON_ROUTE_COMP_PC03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Hemos asegurado un camino[n]hacia el tesoro. 夷Es que[n]quieres irte ahora?[n][w][e]

[msg DUNGEON_ROUTE_COMP_PC04_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]Solo podemos prepararnos[n]para el gran d胤a. 夷Y ahora qu姻?[n]夷Volvemos?[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ya volvemos?[n]Pero si no hemos hecho nada...[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 ocurre, Joker? Todav胤a[n]no hemos hecho nada.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Ya te quieres ir a casa?[n]Si no hemos hecho nada.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 sucede?[n]Todav胤a queda mucho por explorar.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 ocurre? 夷Quieres volver?[n]Apenas hemos hecho nada.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Nos volvemos ya?[n]Hoy no hemos hecho nada.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 ocurre, Joker?[n]No hemos llegado a hacer nada hoy.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC09 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Quieres regresar? Pero si a雨n[n]no hemos conseguido nada[n]importante en lo que llevamos aqu胤.[n][w][e]

[msg DUNGEON_EXIT_NOT_01_PC10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Volvemos ya?[n]Hoy no hemos hecho nada.[n][w][e]

[msg DUNGEON_EXIT_01_PC02_mes [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7072 65535 0]夷Qu姻 ocurre?[n]夷Quieres volver y reagruparte?[n][w][e]

[msg DUNGEON_EXIT_01_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1059 65535 0]夷Eh? 夷Quieres retirarte, Joker?[n][w][e]

[msg DUNGEON_EXIT_01_PC04_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6072 65535 0]夷Qu姻 pasa?[n]夷Quieres que lo dejemos aqu胤?[n][w][e]

[msg DUNGEON_EXIT_01_PC05_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4072 65535 0]夷Quieres que nos reunamos, Joker?[n][w][e]

[msg DUNGEON_EXIT_01_PC06_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2120 65535 0]Mmm, 夷quieres volver?[n][w][e]

[msg DUNGEON_EXIT_01_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9136 65535 0]Puede que sea buena idea[n]que nos reagrupemos.[n][w][e]

[msg DUNGEON_EXIT_01_PC08_mes [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3001 65535 0]夷Es hora de retirarse?[n][w][e]

[msg DUNGEON_EXIT_01_PC09_mes [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]夷C吋mo? 夷Nos retiramos?[n][w][e]

[msg DUNGEON_EXIT_01_PC10_mes [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57089 65535 0]夷Quieres que nos reagrupemos?[n][w][e]

[msg DUNGEON_EXIT_01_PC11_mes [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8130 65535 0]夷C吋mo? 夷Nos retiramos?[n][w][e]

[msg ATD_EXIT_REMIND_FLOWER_V [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53101 65535 0]Jose dijo que las flores[n]desaparecen cuando sales[n]de Mementos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......[n][w][e]

[msg ATD_EXIT_REMIND_FLOWER_V_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 53101 65535 0]Jose dijo que las flores[n]desaparecen cuando sales[n]de Mementos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Has recogido [clr 2][var 0][clr 27] flores[n]de momento. 夷Seguro[n]que quieres irte?[n][w][e]

[msg ATD_EXIT_REMIND_FLOWER_V_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]夷Eh? 夷Nos retiramos?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora mismo tienes [clr 2][var 0][clr 27] flores.[n]Si te vas, desaparecer茨n.[n][w][e]

[msg ATD_EXIT_CABLE_VANISHED_ [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]Ya hemos hecho todo lo que[n]ten胤amos que hacer.[n]Dej姻moslo por hoy.[n][w][e]

[msg ATD_EXIT_CANCEL_CABLE_VA [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]Muy bien. Exploremos un rato m茨s.[n][w][e]

[msg D_EXIT_OK_01_PC02_mes [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7050 65535 0]Chachi, prosigamos.[n][w][e]

[msg D_EXIT_OK_01_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1049 65535 0]Mmm, dej姻moslo por hoy.[n][w][e]

[msg D_EXIT_OK_01_PC04_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6049 65535 0]V茨monos.[n][w][e]

[msg D_EXIT_OK_01_PC05_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4049 65535 0]Mmm, muy bien. Nos vamos.[n][w][e]

[msg D_EXIT_OK_01_PC06_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2049 65535 0]Vale, dej姻moslo por hoy.[n][w][e]

[msg D_EXIT_OK_01_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9050 65535 0]斡S胤胤胤, v茨monos a casa![n][w][e]

[msg D_EXIT_OK_01_PC08_mes [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3049 65535 0]Muy bien, march姻monos a casa.[n][w][e]

[msg D_EXIT_OK_01_PC09_mes [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8035 65535 0]Qu姻 buena idea. En ese caso,[n]march姻monos.[n][w][e]

[msg D_EXIT_OK_01_PC10_mes [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57066 65535 0]Entendido, 夷damos media vuelta?[n][w][e]

[msg D_EXIT_OK_01_PC11_mes [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8138 65535 0]Qu姻 buena idea. En ese caso,[n]march姻monos.[n][w][e]

[sel DUNGEON_EXIT_151_EX_SEL top]
[s]*Especial[e]
[s]Activar el [clr 6]Navegador del Metaverso[clr 27][e]
[s]No activar el navegador[e]

[msg DUNGEON_EXIT_D01_EX_mes [Ryuji]]
[s][bup 0 2 0 65535 0]Si usamos el Navegador aqu胤,[n]volveremos al mundo real.[n][w][e]

[msg D_EXIT_OK_D01_EX_mes [Ryuji]]
[s][bup 0 2 0 65535 0]斡Estupendo, ha funcionado![n][w][e]

[msg D_EXIT_NG_D01_EX_mes [Ryuji]]
[s][bup 0 2 0 65535 0]夷Qu姻 haces? 斡Hay que salir de aqu胤![n][w][e]

[msg D_EXIT_CANCEL_PC02_mes [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]Chachi, puedo seguir[n]si es eso lo que quieres.[n][w][e]

[msg D_EXIT_CANCEL_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1096 65535 0]Bueno, sigamos explorando.[n][w][e]

[msg D_EXIT_CANCEL_PC04_mes [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6096 65535 0]Vale, vamos a echar otro vistazo[n]por esta zona.[n][w][e]

[msg D_EXIT_CANCEL_PC05_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4052 65535 0]Coincido. Seguro que quedan lugares[n]por visitar.[n][w][e]

[msg D_EXIT_CANCEL_PC06_mes [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2081 65535 0]Tienes raz吋n, sigamos.[n][w][e]

[msg D_EXIT_CANCEL_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9130 65535 0]Vale, vamos a quedarnos[n]un poquito m茨s.[n][w][e]

[msg D_EXIT_CANCEL_PC08_mes [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3051 65535 0]Mmm, bueno, pong茨monos a explorar.[n][w][e]

[msg D_EXIT_CANCEL_PC09_mes [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8070 65535 0]Vale, sigamos un poco m茨s.[n][w][e]

[msg D_EXIT_CANCEL_PC10_mes [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57163 65535 0]Vale. Solo un poquito m茨s.[n][w][e]

[msg D_EXIT_CANCEL_PC11_mes [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8137 65535 0]斡No bajes la guardia![n][w][e]

[msg ALERT_MAX_EXIT_mes00 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1039 65535 0]斡Uf, esto no mola nada! El nivel[n]de seguridad de esta zona[n]es demasiado alto![n][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Nuestras vidas corren[n]peligro si nos quedamos.[n][w][e]
[s]斡Tenemos que retirarnos, Joker![n][w][e]

[msg ALERT_MAX_EXIT_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]U-un momentito.[n]Estar胤a bien que...[n][w][e]

[msg ALERT_MAX_EXIT_mes02 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1082 65535 0]斡Las sombras no dejan[n]de multiplicarse! 斡Tenemos[n]que marcharnos, y r茨pido![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]斡夷Qu姻 dices, t胤o?! 斡Si ya hemos[n]mandado el aviso![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Todo nuestro trabajo[n]se va a ir a tomar por culo[n]si no robamos el tesoro hoy![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC03 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1040 65535 0]夷Qu姻? 斡夷Es que no has escuchado[n]nada de lo que te he dicho?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Si no nos llevamos el tesoro hoy,[n]todo lo que hemos logrado[n]se ir茨 por la borda![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6039 65535 0]斡Eso no va a pasar! 斡Ni de broma![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Todo nuestro plan se ir茨[n]al garete si no nos llevamos[n]el tesoro hoy mismo![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4104 65535 0]夷Quieres volver? Ja, ja, anda que[n]mira que ponerte a gastar bromas[n]en medio de una misi吋n...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En fin, sigamos con lo que[n]est茨bamos haciendo.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2043 65535 0]Venga, basta de quejas.[n]夷Es que no eres el l胤der?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Tenemos que hacernos con el tesoro[n]hoy, cueste lo que cueste![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale, volvamos a casa...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9100 65535 0]Esto, eh... que era broma.[n]Nadie se va a largar ahora.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC08 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cre胤a que no pod胤amos retirarnos[n]hasta haber enviado el aviso.[n][w][e]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3136 65535 0]斡No te preocupes, Joker![n]斡Nosotros te apoyamos![n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC09 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8112 65535 0]夷Quieres abandonar ahora[n]que hemos llegado hasta aqu胤?[n]No es muy propio de ti.[n][w][e]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenemos que intentar solucionar[n]esto hoy. Tienes mi apoyo.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC10 [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 57118 65535 0]Pensaba que no pod胤amos volver[n]hasta que envi茨semos el aviso.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos, Joker, yo tambi姻n[n]me esforzar姻 al m茨ximo.[n][w][e]

[msg D_EXIT_NG_ACTIVE_01_PC11 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8018 65535 0]Hemos llegado muy lejos,[n]no podemos marcharnos ahora.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Acabemos con esto![n][w][e]

[msg SAFEROOM_EXIT_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De veras quieres irte, Joker?[n][w][e]

[msg SAFEROOM_EXIT_PC07_mes [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷En serio nos vamos a casa, Joker?[n][w][e]

[msg D01_04_e166_015_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]Chachi, ahora solo tenemos[n]que robar el tesoro que aparezca.[n]Por fin lleg吋 el momento.[n][w][e]

[msg D01_04_e166_015_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero primero tenemos que enviar[n]el aviso. 夷Cu茨ndo lo hacemos?[n][w][e]

[msg D01_04_e166_015_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale, dej姻moslo. Retir姻monos[n]por ahora, ya trataremos m茨s[n]ese tema en el escondite.[n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1030 65535 0]斡Ah, y buen trabajo![n][w][e]

[msg D02_MISSION_POINT_PC03_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1172 65535 0]Deber胤amos irnos e intentar[n]desactivar la seguridad del patio.[n][w][e]

[msg D02_04_e210_240_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7153 65535 0]Bueno, sigo preocupado...[n]pero no nos queda otra.[n][w][e]

[msg D02_04_e210_240_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4076 65535 0]No puedo ni imaginarme[n]qu姻 es el tesoro de Madarame...[n][w][e]

[msg D02_04_e210_240_mes03 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es igual, lo robaremos de todos[n]modos. 斡Ah, y hoy lo hab姻is[n]hecho de maravilla![n][w][e]

[msg D03_FIRST_END_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1172 65535 0]La puerta cognitiva est茨 cerrada.[n]夷Deber胤amos volver ya?[n][w][e]

[msg D06_FIRST_END_PC06_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2118 65535 0]Tenemos que reagruparnos[n]en el mundo real.[n][w][e]

[msg D07_FIRST_END_PC03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]Entendido, Joker. 斡Retirada![n][w][e]

[msg D01_EXIT_NG_EV01_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ad吋nde vas, Joker?[n][w][e]
[s]Ya hemos revisado esas celdas.[n]Vamos a echarle un vistazo[n]al castillo por dentro.[n][w][e]

[msg D01_EXIT_NG_EV01_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenemos que pasar por la entrada[n]para llegar hasta all胤.[n]Pero 夷no estaba cerrada la puerta?[n][w][e]
[s]Ser茨 imposible de conseguir[n]a menos que encontremos[n]otro camino a la primera planta.[n][w][e]

[msg D07_DUNGEON_EXIT_SC_mes0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Venga, hemos llegado hasta aqu胤.[n]Al menos vamos a comprobar[n]la zona primero.[n][w][e]

