[msg D08_01_e441_021_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2159 65535 0]夷Y esta puerta? Parece que[n]en el hueco del centro cabe algo...[n][w][e]

[msg D08_01_e441_021_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Y si pasamos del tema?[n]Ah胤 detr茨s no hay nada.[n][w][e]

[msg D08_01_e441_021_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es verdad.[n][w][e]

[msg D08_01_e441_021_re_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De verdad cre姻is que la puerta[n]no tiene ning雨n prop吋sito?[n][w][e]

[msg D08_01_e441_021_clear_me]
[s]El artilugio que conseguimos antes[n]podr胤a encajar en el hueco.[n][w][e]

