[msg D07_02_e409_034_mes01 [Mujer en ba隠ador]]
[s]夷A que es bonito el ba隠ador?[n]Es de una nueva l胤nea de uno[n]de los mejores dise隠adores.[n][w][e]
[s]En el bar se pueden alquilar[n]ba隠adores como estos.[n][w][e]

[msg D07_02_e409_034_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Je, je, je...[n][w][e]

[msg D07_02_e409_034_mes03 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]斡Tengo el plan perfecto![n][w][e]

[msg D07_02_e409_034_mes04 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1025 65535 0]Qu姻 miedo de risa.[n][w][e]

[msg D07_02_e409_034_mes05 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ni caso! 斡Vamos al bar![n][w][e]

[msg D07_02_e409_034_AF_mes01 [Mujer en ba隠ador]]
[s]En el bar se pueden alquilar[n]ba隠adores como estos.[n][w][e]

[msg D07_02_e409_034_AF_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7074 65535 0]夷En el bar? 斡Vamos, Joker![n][w][e]

[msg D159_10_c_01_mes01 [Camarero]]
[s]Le doy la bienvenida a[n]la cubierta de la piscina.[n][w][e]
[s]No dude en hablar con nosotros[n]si necesita cualquier cosa.[n][w][e]

[msg D159_10_c_01_AF_mes01 [Camarero]]
[s]Hola. Aqu胤 puede relajarse[n]todo lo que desee.[n][w][e]

[msg D07_02_e409_035_mes01 [Camarero]]
[s]Hola. 夷Puedo ayudarle en algo?[n][w][e]

[msg D07_02_e409_035_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Oye, aqu胤 alquil茨is ba隠adores, 夷no?[n]斡Necesitamos unos cuantos ya![n][w][e]

[msg D07_02_e409_035_mes03 [Camarero]]
[s]Ah, por supuesto. Ens姻隠eme su[n]tarjeta de embarque y se los[n]dar姻 de inmediato.[n][w][e]

[msg D07_02_e409_035_mes04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]斡Idiota! 斡Venga, Skull, v茨monos[n]de aqu胤! 斡T雨 tambi姻n, Joker![n][w][e]

[msg D07_02_e409_035_mes05 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En serio, Skull, 夷en qu姻 estabas[n]pensando? 夷De repente[n]te apetece nadar?[n][w][e]

[msg D07_02_e409_035_mes06 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7036 65535 0]斡Qu姻 va, si era parte de mi plan![n][w][e]

[msg D07_02_e409_035_mes07 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]All胤 hay unos probadores...[n]Joker, necesito que me ayudes[n]a colarme.[n][w][e]

[msg D07_02_e409_035_AF_mes01 [Camarero]]
[s]Los clientes que quieran alquilar[n]un ba隠ador deben presentar[n]primero la tarjeta de embarque.[n][w][e]

[msg D159_10_c_02_mes01 [Camarero]]
[s]Disculpe, esos son los probadores.[n][w][e]
[s]Tiene que registrarse y presentar[n]la tarjeta de embarque en el[n]mostrador si quiere entrar.[n][w][e]

[msg D159_10_c_02_AF_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]Eh, 斡夷qu姻 haces?![n]斡No se nos ha perdido nada ah胤![n][w][e]

[msg D159_10_c_02_AF_mes02 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No me esperaba que Joker[n]tuviera los deseos carnales[n]de un adolescente.[n][w][e]

[msg D07_02_e409_036_mes01 [Camarero]]
[s]Disculpe, esos son los probadores.[n][w][e]
[s]Tiene que registrarse aqu胤[n]si quiere alquilar un ba隠ador.[n][w][e]

[msg D07_02_e409_036_mes02 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Mierda, as胤 no nos vamos a colar.[n]Hay que buscar[n]otra forma de entrar.[n][w][e]

[msg D07_02_e409_036_mes03 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Supongo que no podemos entrar[n]as胤 como as胤.[n]Bueno, vamos al mostrador.[n][w][e]

[msg D159_10_L_01_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9114 65535 0]夷Ad吋nde vas? Tenemos que encontrar[n]al objetivo y conseguir su carta de[n]recomendaci吋n.[n][w][e]

[msg D159_10_c_03_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece un conducto de ventilaci吋n,[n]pero est茨 tapado.[n][w][e]

