[msg MSG_e296_531_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡T雨, bandido! 夷A ti qu姻 te pasa?[n]夷Te has cansado de correr?[n][w][e]

[msg MSG_e296_531_001 [夷夷??]]
[s]Ni se os ocurra dar un paso m茨s...[n][w][e]

[sel SEL_e296_531_002 top]
[s]Hablemos del tema.[f 2 7 0 0 106 1][e]
[s]Devu姻lvenos lo que has robado.[f 2 7 0 0 106 1][e]

[msg MSG_e296_531_003 [夷夷??]]
[s]Anda, basta de bromas.[n]Ten姻is que soltarme.[n][w][e]
[s]夷No hab姻is venido a saquear[n]la tumba? Yo digo que unamos[n]fuerzas y nos repartamos el bot胤n.[n][w][e]

[msg MSG_e296_531_004 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6115 65535 0]斡Ni se te ocurra compararnos[n]con los de tu cala隠a! Hemos venido[n]a salvar a Futaba.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Devu姻lvenos lo que has robado![n][w][e]

[msg MSG_e296_531_005 [夷夷??]]
[s]Ya veo que no me dej茨is[n]alternativa, 夷eh?[n]Pues... 斡qu姻 le vamos a hacer![n][w][e]

[msg MSG_e296_535_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]斡Toma! Anda, se le ha ca胤do algo.[n][w][e]

[msg MSG_e296_535_001 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es como una especie de pergamino.[n]Parece que pone algo.[n][w][e]

[msg MSG_e296_535_002 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6025 65535 0]Oye, nada de cotillear las cosas[n]de una se隠orita sin su permiso.[n][w][e]

[msg D04_02_e296_535_mes04 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 leches le est茨 pasando[n]a su coraz吋n?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Primero est茨 el bandido ese,[n]luego las voces raras diciendo[n]或la mataste位...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya tela.[n][w][e]

[msg D04_02_e296_535_mes05 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6128 65535 0]Entonces, 夷ella no puede controlar[n]lo que pasa aqu胤 aunque[n]sea la se隠ora del Palacio?[n][w][e]

[msg D04_02_e296_535_mes06 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ni idea... Nunca hab胤a visto[n]algo as胤.[n][w][e]

[msg D04_02_e296_535_mes07 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En cualquier caso, no tenemos[n]m茨s asuntos pendientes aqu胤.[n]Joker, 夷regresamos?[n][w][e]

