[msg D02_BRIEFING_070_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7184 65535 0]Tronco... A雨n no me creo que nos[n]hayamos metido en esos cuadros.[n]Flipo con los Palacios.[n][w][e]

[msg D02_BRIEFING_070_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻? Hay una estrecha relaci吋n[n]entre los cuadros[n]y la imagen cognitiva.[n][w][e]
[s]Dado que este lugar es un mundo[n]basado en la cognici吋n, es l吋gico[n]que seamos capaces de atravesarlos.[n][w][e]

[msg D02_BRIEFING_070_mes03 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7022 65535 0]Esto, eh... Ya veo...[n][w][e]

[msg D02_BRIEFING_070_mes04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, Mona, 夷cu茨nto crees[n]que llevamos ahora?[n][w][e]

[msg D02_BRIEFING_070_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Estaremos por la mitad m茨s o menos.[n]Y percibo presencia enemiga[n]m茨s adelante.[n][w][e]

[msg D02_BRIEFING_070_mes06 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entiendo... Supongo que habr茨[n]que seguir esforz茨ndose al m茨ximo.[n][w][e]

