[msg D157_009_miniEV_03_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Oye, 夷eso no es una [clr 2]terminal[clr 27]?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Puedes echarle un vistazo y ver[n]c吋mo hacen trampas, Oracle?[n][w][e]

[msg D157_009_miniEV_03_mes02 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno... Esta est茨 desactivada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]B茨sicamente, voy a tener que[n]activarla remotamente desde una[n]terminal principal de otro sitio.[n][w][e]

[msg D157_009_miniEV_03_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8134 65535 0]As胤 que esta es in雨til salvo[n]que accedamos a la red principal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya. Al menos deber胤amos[n]memorizar este sitio.[n][w][e]

[msg D157_009_miniEV_05_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1179 65535 0]Ah, 斡aqu胤 est茨! Ay, espera...[n]Este panel es [clr 2]azul[clr 27].[n][w][e]

[msg D157_009_miniEV_05_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Debemos encontrar el [clr 2]rojo[clr 27][n]y el [clr 2]verde[clr 27], 夷no?[n]夷Como... colores de comida?[n][w][e]

[msg D157_009_miniEV_05_mes03 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eso qu姻 significa exactamente?[n]Venga, sigamos adelante.[n][w][e]

