[msg D02_BRIEFING_010_mes01 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6028 65535 0]夷No os parece muy grande[n]este edificio?[n][w][e]

[msg D02_BRIEFING_010_mes02 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, y encima con todos[n]esos cuadros... Menuda movida.[n][w][e]

[msg D02_BRIEFING_010_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero esto acaba de empezar.[n]M茨s nos vale estar preparados[n]para lo que pueda venir.[n][w][e]

[msg D02_BRIEFING_010_mes04 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]S胤, ya lo s姻.[n]斡Hay que ir a por el tesoro![n][w][e]

