[msg D159_10_npc_01_mes01 [Hombre en ba隠ador]]
[s]Qu姻 ropa m茨s inapropiada. Esto es[n]una piscina. Poneos el ba隠ador[n]si no quer姻is que os echen.[n][w][e]
[s]A este lujoso para胤so, uno viene[n]a tumbarse, a mirar al cielo[n]y a perder el tiempo.[n][w][e]

[msg D159_10_npc_02_mes01 [Hombre en ba隠ador]]
[s]Qu姻 maravilla de sitio.[n]Venga cuando venga, 斡siempre est茨[n]a rebosar de cuerpazos![n][w][e]
[s]Que no te d姻 verg鵜enza.[n]A eso hab姻is venido, 夷no?[n][w][e]

[msg D159_10_npc_03_mes01 [Mujer en ba隠ador]]
[s]Qu姻 tranquilidad hay 雨ltimamente.[n][w][e]
[s]Gracias al se隠or Shido,[n]podemos pasar unos d胤as[n]rodeados de lujos.[n][w][e]

