[msg D04_03_e295_081_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4158 65535 0]Mmm, puede que nos resulte 雨til[n]en alg雨n lado. 夷Nos lo llevamos?[n][w][e]

[sel D04_03_e295_081_selA top]
[s]Coger la gema[e]
[s]No coger la gema[e]

[msg D04_03_e295_081_selA_0_m [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Muy bien. Podr胤a tratarse[n]de un objeto de vital importancia.[n][w][e]

[msg D04_03_e295_081_selA_1_m [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4020 65535 0]Comprendo. Deber胤amos recordar[n]d吋nde est茨 al menos. Podr胤a ser[n]un objeto de vital importancia.[n][w][e]

[msg MSG_e295_081_AF01_000 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entonces, 夷nos llevamos la gema?[n][w][e]

[msg MSG_e295_081_AF02_000 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2089 65535 0]Joker, 夷qu姻 sucede?[n]夷Crees que deber胤amos dejar[n]la gema que hemos cogido?[n][w][e]

[sel SEL_e295_081_AF02_001 top]
[s]Desde luego.[e]
[s]No, da igual.[e]

[msg MSG_e295_081_AF02_002 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2090 65535 0]Ya est茨, igualita que antes.[n]V茨monos.[n][w][e]

[msg MSG_e295_081_AF02_003 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2023 65535 0]Venga, v茨monos.[n][w][e]

[msg MSG_e295_082_000 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Entonces, 夷crees que deber胤amos[n]coger la gema?[n][w][e]

[sel SEL_e295_082_001 top]
[s]Coger la gema[e]
[s]No coger la gema[e]

[msg MSG_e295_082_002 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]Vale. Coj茨mosla y continuemos.[n][w][e]

[msg MSG_e295_082_003 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1023 65535 0]夷De veras? Supongo que podemos[n]dejarla de momento.[n][w][e]

[msg MSG_e295_082_AF01_000 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷qu姻 pasa?[n]夷Al final vas a coger la gema?[n][w][e]

[msg MSG_e295_082_AF02_000 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻? 夷Est茨s pensando en dejar[n]la gema otra vez aqu胤?[n][w][e]

[sel SEL_e295_082_AF02_001 top]
[s]Ponerla en su sitio[e]
[s]No ponerla en su sitio[e]

[msg MSG_e295_082_AF02_002 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y as胤 es como si nunca nos la[n]hubi姻ramos llevado. 斡Adelante![n][w][e]

[msg MSG_e295_082_AF02_003 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale, pues nos la quedamos.[n][w][e]

[msg D04_03_e295_081_AF03_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya hemos usado la gema que[n]conseguimos de aqu胤. No creo que[n]haya nada m茨s que hacer con esto.[n][w][e]

[msg D04_03_e295_082_AF03_mes [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya hemos hecho buen uso[n]de la gema de la estatua.[n]Dudo que sirva para algo m茨s.[n][w][e]

[msg D04_03_e295_081_FIRST_me [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Est茨 sujetando algo. De todas[n]formas, 夷qu姻 es esta estatua?[n]Parece un perro, 夷no?[n][w][e]

[msg D04_03_e295_081_FIRST_me_2 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es Anubis, el dios egipcio[n]del inframundo. Parece que lleva[n]como un orbe resplandeciente.[n][w][e]

[msg D04_03_e295_081_FIRST_me_3 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]Me suena. 夷Pasaba algo con la luz[n]del dios del inframundo?[n][w][e]

[msg D04_03_e295_081_SECOND_m [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]Eh, esta estatua es el mismo perro[n]raruno de antes. Y, mirad, tambi姻n[n]tiene una gema.[n][w][e]

[msg D04_03_e295_081_SECOND_m_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El dios se llama Anubis. No es[n]tan dif胤cil de recordar, Skull.[n][w][e]

