[msg D01_BRIEFING_020_mes01 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1045 65535 0]Es genial que hayamos conseguido[n]un mapa del Palacio. Ahora[n]explorar ser茨 mucho m茨s f茨cil.[n][w][e]

[msg D01_BRIEFING_020_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Hemos averiguado ya[n]d吋nde est茨 el tesoro?[n][w][e]

[msg D01_BRIEFING_020_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No aparece en el mapa...[n]Tiene que haber otro que[n]no hayamos conseguido todav胤a.[n][w][e]

[msg D01_BRIEFING_020_mes04 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos, que todav胤a[n]nos queda un mont吋n...[n][w][e]

