[msg D151_16_CHECK_01_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Est茨 tan oscuro que cuesta verlo,[n]pero 夷ese tambi姻n es Kamoshida?[n][w][e]

[msg D151_16_CHECK_01_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Probablemente sea un retrato[n]del se隠or de este mundo...[n][w][e]

[msg D151_16_CHECK_01_mes03 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Se隠or? 夷De qu姻 co隠o[n]est茨s hablando?[n][w][e]

[msg D151_16_CHECK_01_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bajad la voz. No queremos[n]que los guardias nos detecten.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deber胤amos centrarnos[n]en escapar. 斡Venga![n][w][e]

[msg D151_16_CHECK_01_AF_mes0]
[s]Hay un autorretrato[n]descomunal colgado[n]en la pared.[n][w][e]

[msg D151_16_CHECK_01_AF_mes0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, no te distraigas con eso.[n]斡Centr姻monos en salir de aqu胤![n][w][e]

[msg D151_16_CHECK_02_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 夷qu姻...?[n]夷Es alg雨n tipo de interruptor?[n][w][e]

[msg D151_16_CHECK_02_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, nada de tocar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Debemos centrarnos[n]en llegar a la salida.[n][w][e]

[msg D151_16_CHECK_02_AF_mes0 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, que no tenemos[n]que tocar nada.[n]Venga, pir姻monos.[n][w][e]

[msg D01_01_LOCK_01_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No hay raz吋n para volver por aqu胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hay que ir cagando leches[n]hacia la salida.[n][w][e]

[msg D01_01_LOCK_01_AF_mes01]
[s]Deber胤amos ir hacia la salida[n]en lugar de volver por aqu胤.[n][w][e]

[msg D01_01_LOCK_02_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eh! 斡Espera![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Que por ah胤 todav胤a hay guardias![n]斡Vuelve aqu胤 si no quieres que te[n]metan en prisi吋n otra vez![n][w][e]

[msg D01_01_LOCK_02_AF_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Que no es por ah胤![n]斡Vuelve![n][w][e]

[msg D01_01_LOCK_03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Un momento![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Que ah胤 hay[n]guardias! La salida est茨[n]en direcci吋n contraria.[n][w][e]

[msg D01_01_LOCK_03_AF_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No nos pillar茨n si vamos por ah胤?[n]Venga, vuelve aqu胤.[n][w][e]

