[msg QUEST_53_ENTER_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1164 65535 0]As胤 que esa es la sombra[n]de Fukurai, el presidente.[n][w][e]

[msg QUEST_53_ENTER_mes01f [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah胤 est茨.[n]La sombra del presidente Fukurai.[n][w][e]

[msg QUEST_53_ENTER_mes02 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Tiene una pinta turb胤sima.[n][w][e]

[msg QUEST_53_ENTER_mes03 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Bueno, les vende piedras[n]in雨tiles y seminarios comecocos[n]a sus seguidores, 夷no?[n][w][e]

[msg QUEST_53_ENTER_mes04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Si dejamos que siga as胤,[n]va a hacer infeliz[n]a mucha gente.[n][w][e]

[msg QUEST_53_ENTER_mes05 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2165 65535 0]Vamos a quitarle[n]la m茨scara a ese impostor.[n][w][e]

[msg MSG_000_0_0 [Sombra de Fukurai]]
[s][vp 8 2 1 46710 65535 0]No quieres tristezas ni tragedias[n]en tu vida, 夷verdad?[n]斡Dame dinero y te salvar姻![n][w][e]
[s][vp 1 0 0 0 0 0]P茨game o sufrir茨s una desgracia.[n]斡A lo mejor te mueres![n][w][e]

[sel SEL_001_0_0 top]
[s]Deja de timar a la gente.[e]
[s]El destino puede cambiar.[e]

[msg MSG_002_0_0 [Sombra de Fukurai]]
[s][vp 8 2 1 46703 65535 0]Mira que eres ingenuo.[n][w][e]
[s][vp 1 0 0 0 0 0]Todos creen[n]que una Piedra sagrada los salvar茨[n]de sus predicciones.[n][w][e]
[s][vp 1 0 0 0 0 0]Aunque no funcione,[n]夷qu姻 m茨s da?[n]Si con eso son felices...[n][w][e]
[s][vp 1 0 0 0 0 0]斡La gente quiere que la enga隠en![n]夷No lo ves? 斡Est茨n desesperados[n]por sentirse a salvo![n][w][e]

[sel SEL_003_0_0 top]
[s]Eso es mentira.[e]
[s]Lo que has hecho es un delito.[e]

[msg MSG_004_0_0 [Sombra de Fukurai]]
[s][vp 1 0 0 0 0 0]斡C茨llate! 斡No[n]te interpongas en mi camino[n]hacia la salvaci吋n de las masas![n][w][e]

[msg MSG_005_0_0 [Sombra de Fukurai]]
[s][vp 1 0 0 0 0 0]斡Mierda! He perdido.[n]A lo mejor es mi naturaleza.[n]Solo soy un paleto de pueblo...[n][w][e]

[msg MSG_006_0_0 [Sombra de Fukurai]]
[s][vp 1 0 0 0 0 0]La primera vez que vine a Tokio[n]iba a ir a un centro de formaci吋n[n]profesional, pero me enga隠aron.[n][w][e]
[s][vp 1 0 0 0 0 0]Me gast姻 todo el dinero que ten胤a[n]en la supuesta matr胤cula.[n]Estaba solo en la ciudad.[n][w][e]
[s][vp 1 0 0 0 0 0]La polic胤a se rio de m胤: 或Es obvio[n]que esos anuncios son timos. 夷Has[n]sido tan tonto como para picar?位.[n][w][e]
[s][vp 1 0 0 0 0 0]Por eso me promet胤 que nunca[n]volver胤an a enga隠arme as胤.[n][w][e]
[s][vp 1 0 0 0 0 0]No volver姻 a ser una v胤ctima.[n]Si vuelve a ocurrir,[n]斡ser姻 yo el que enga隠e![n][w][e]

[sel SEL_007_0_0 top]
[s]夷Te hace feliz?[e]
[s]夷Y despu姻s de enga隠arlos...?[e]

[msg MSG_008_0_0 [Sombra de Fukurai]]
[s][vp 1 0 0 0 0 0]Yo... nunca lo pens姻.[n][w][e]
[s][vp 1 0 0 0 0 0]Supongo que, a fin[n]de cuentas, soy tonto perdido.[n]Ja, ja, ja... Ja, ja...[n][w][e]

[msg MSG_009_0_0 [Sombra de Fukurai]]
[s][vp 1 0 0 0 0 0]Los poderes de la doncella[n]son reales. Por eso la traje.[n][w][e]
[s][vp 1 0 0 0 0 0]Soy el 雨nico mentiroso.[n]Y me aprovech姻[n]de que volvi姻ramos a encontrarnos.[n][w][e]
[s][vp 1 0 0 0 0 0]Hac胤a tiempo que quer胤a[n]pedirle disculpas...[n]Lo siento mucho, Chi...[n][w][e]

[msg MND_010_0_0]
[s][vp 1 0 0 0 0 0]Me pregunto si se supone[n]que Chi es Chihaya.[n][w][e]
[s][vp 1 0 0 0 0 0]De todas formas, parece[n]que Yuichi Fukurai ha cambiado.[n]Deber胤a ir a hablar con Chihaya.[n][w][e]

