[msg D08_BRIEFING_020_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que la gente de los trenes[n]de Mementos ven胤a a esta prisi吋n.[n][w][e]

[msg D08_BRIEFING_020_mes02 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La gente de Mementos son sombras[n]de la gente del mundo real, 夷no?[n][w][e]
[s]Ir a la c茨rcel por voluntad propia...[n]Pero 夷en qu姻 est茨n pensando?[n][w][e]

[msg D08_BRIEFING_020_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me extra隠a que no les llamemos[n]la atenci吋n. Tiene sentido,[n]pero da mal rollo.[n][w][e]

[msg D08_BRIEFING_020_mes04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En Mementos damos igual,[n]no como en los Palacios.[n][w][e]

[msg D08_BRIEFING_020_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No lo entiendo...[n][w][e]
[s]夷Aqu胤 es donde siempre[n]he querido venir?[n][w][e]

