[msg AT_D_BF_D03_010_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4150 65535 0]夷Y no cabr胤a la posibilidad de que[n]di姻semos con nuestras propias[n]sombras en Mementos?[n][w][e]

[msg AT_D_BF_D03_010_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Imposible. Nuestras sombras siempre[n]est茨n a nuestro lado, 夷recuerdas?[n][w][e]

[msg AT_D_BF_D03_010_mes03 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, es verdad... Nuestras Personas...[n][w][e]

[msg AT_D_BF_D03_010_mes04 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1156 65535 0]Uno se convierte en usuario de[n]Personas cuando reconoce, afronta y[n]puede controlar a su propia sombra.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por eso no podemos tener Palacios[n]ni nuestras sombras pueden existir[n]en los Palacios de otras personas.[n][w][e]

[msg AT_D_BF_D03_010_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya, pero nosotros vimos la sombra[n]de Panther en el Palacio[n]de Kamoshida.[n][w][e]

[msg AT_D_BF_D03_010_mes06 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]斡Eh, que aquella cosa no era m胤a![n][w][e]

[msg AT_D_BF_D03_010_mes07 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Solo era una cognici吋n creada por[n]la mente de Kamoshida. Nada que ver[n]con la verdadera sombra de Panther.[n][w][e]

[msg AT_D_BF_D03_010_mes08 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4087 65535 0]As胤 que para usar una Persona hay[n]que reconocer la sombra propia...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pues sabiendo eso, veo que[n]la capacidad de Joker de controlar[n]a varias Personas es muy especial.[n][w][e]

[msg AT_D_BF_D03_010_mes09 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷A que s胤? 斡Eso demuestra que tuve[n]buen ojo con 姻l![n][w][e]

[msg AT_D_BF_D03_010_mes10 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ver, que t雨 tambi姻n te quedaste[n]a cuadros cuando pas吋 aquello...[n][w][e]

