[msg MSG_e296_510_000 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hemos llegado. Esta debe de ser[n]la ciudad que la sombra[n]de Futaba mencion吋.[n][w][e]

[msg MSG_e296_510_001 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4129 65535 0]Est茨 bastante desolada.[n]Dijo que solo resid胤an bandidos,[n]pero a pesar de eso...[n][w][e]

[msg MSG_e296_510_AF_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7052 65535 0]Venga, 斡a recuperar lo que[n]haya robado el bandido![n][w][e]

