[msg D08_01_twins_cure_start_ [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11027 65535 0]D-despu姻s de todo lo que te[n]ha pasado, 斡夷sigues queriendo[n]evadir la situaci吋n, recluso?![n][w][e]

[sel D08_01_twins_cure_start__2 top]
[s]Pues claro que s胤.[e]
[s]No pienso rendirme.[e]
[s]Ay雨dame, por favor.[e]

[msg D08_01_twins_cure_start__3 [Caroline]]
[s][bup 0 102 5 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11055 65535 0]Claro...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La verdad es que no deber胤a[n]sorprenderme en absoluto.[n][w][e]

[msg D08_01_twins_cure_start__4 [Caroline]]
[s][bup 0 102 5 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11055 65535 0]Que no...[n][w][e]
[s]Mmm.[n][w][e]

[msg D08_01_twins_cure_start__5 [Caroline]]
[s][bup 0 102 5 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11064 65535 0]夷Que te ayude?[n][w][e]
[s]...[n][w][e]

[msg D08_01_twins_cure_start__6 [Caroline]]
[s][bup 0 102 3 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ayudar a los reclusos con su[n]rehabilitaci吋n es nuestro deber.[n][w][e]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale, te echar姻 una mano.[n][w][e]

[msg D08_01_twins_cure_start__7]
[s]Siento que he recuperado algo[n]de esp胤ritu y salud.[n][w][e]

[msg D08_01_twins_cure_start__8 [Caroline]]
[s][bup 0 102 6 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11022 65535 0]夷Sorprendido? Para nosotras,[n]esto no es nada.[n][w][e]
[s]Ven a vernos[n]cuando est姻s herido, recluso.[n][w][e]

[msg D08_01_twins_cure_mes01 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 11064 65535 0]Todo esto es para ayudar[n]con tu rehabilitaci吋n. No deber胤a[n]haber ning雨n problema.[n][w][e]

[msg D08_01_twins_cure_mes02]
[s]Siento que he recuperado algo[n]de esp胤ritu y salud.[n][w][e]

