[msg D02_BRIEFING_030_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6018 65535 0]Mona, 夷cu茨nto nos queda[n]para llegar al tesoro?[n][w][e]

[msg D02_BRIEFING_030_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque hayamos ca胤do en varias[n]trampas... seguimos al principio.[n]A雨n nos queda mucho.[n][w][e]

[msg D02_BRIEFING_030_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7184 65535 0]Oye, por curiosidad...[n]夷C吋mo lo sabes?[n][w][e]

[msg D02_BRIEFING_030_mes04 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Je, je, je. Con mis habilidades[n]puedo saber lo grande que es[n]un edificio nada m茨s verlo.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El resto es por la distorsi吋n y...[n]supongo que por[n]la presencia del tesoro.[n][w][e]

[msg D02_BRIEFING_030_mes05 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6020 65535 0]Vaya... En cualquier caso,[n]hasta ahora has acertado bastante.[n][w][e]

[msg D02_BRIEFING_030_mes06 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, supongo que ser茨 verdad eso[n]de que estamos al principio.[n]Venga, andando que es gerundio.[n][w][e]

