[msg fev0409_10_CHECK_mes01]
[s]Si voy a vivir aqu胤, al menos[n]deber胤a limpiar un poco.[n][w][e]

[msg fev0409_10_CHECK_mes02]
[s]Dudo que pueda dormir tranquilo[n]si no limpio un poco este lugar.[n][w][e]

[sel fev0409_10_CHECK_SEL top]
[s]Empezar a limpiar[e]
[s]Hacerlo luego[e]

[msg fev0409_10_STEP_mes02]
[s]Deber胤a limpiar mi habitaci吋n...[n][w][e]

[msg fev0409_10_NG_mes01 [Sojiro]]
[s][bup 0 103 0 0 0]夷Qu姻 pasa? 夷Necesitas algo?[n][w][e]

[sel fev0409_10_NG_SEL top]
[s]Esa habitaci吋n es lo peor.[e]
[s]夷Necesitas ayuda en el Leblanc?[e]
[s]No es nada.[e]

[msg fev0409_10_NG_A_mes01 [Sojiro]]
[s][bup 0 103 0 0 0]Ja, podr茨s decir eso cuando[n]puedas permitirte tu propio sitio.[n][w][e]
[s]Si no est茨s conforme, haz algo[n]al respecto, como limpiar un poco.[n][w][e]

[msg fev0409_10_NG_B_mes01 [Sojiro]]
[s][bup 0 103 0 0 0]No, tranquilo.[n]Cualquier cosa, te aviso.[n][w][e]
[s]Si te aburres,[n]limpia tu habitaci吋n.[n][w][e]

[msg fev0409_10_NG_C_mes01 [Sojiro]]
[s][bup 0 103 0 0 0]Si te aburres,[n]limpia tu habitaci吋n.[n][w][e]
[s]Dudo que puedas dormir ah胤 tal y[n]como est茨. Tal vez deber胤a haberla[n]limpiado antes de que llegaras.[n][w][e]

[msg fev0409_10_NG_mes02 [Sojiro]]
[s][bup 0 103 0 0 0]Bueno, estoy ocupado.[n]Sube a tu habitaci吋n.[n][w][e]

[msg fev0409_11_1F_NG_mes01]
[s]Parece que el Leblanc est茨 cerrado.[n][w][e]
[s]Estoy bastante cansado.[n]Deber胤a irme a la cama.[n][w][e]

[msg fev0409_11_2F_NG_mes01]
[s]Estoy bastante cansado.[n]Deber胤a irme a la cama.[n][w][e]

[msg fev0409_10_CLEAN_EV_DUMM]
[s]※掃除中[n][w][e]

