[msg COMBINE_WARNING_MSG]
[s]Tengo un mal presentimiento...[n][w][e]

[msg COMBINE_WARNING_TUTORIAL [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 55232 65535 0]Tenemos que hablar de un asunto[n]contigo. Entra.[n][w][e]

[msg COMBINE_WARNING_TUTORIAL_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1018 65535 0]夷Qu姻 haces? Deber胤amos ir tirando.[n][w][e]

[msg COMBINE_WARNING_TUTORIAL_3]
[s]Tengo un mal presentimiento...[n][w][e]

