[msg QUEST_58_ENTER_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]夷As胤 que esta es la sombra de[n]la madre de la jugadora de shogi,[n]Hifumi?[n][w][e]

[msg QUEST_58_ENTER_mes01f [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah胤 est茨 la sombra.[n]Es la madre de la jugadora[n]de shogi, Hifumi, 夷no?[n][w][e]

[msg QUEST_58_ENTER_mes02 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Por lo que he o胤do, la usa[n]como si fuera un pe吋n.[n][w][e]

[msg QUEST_58_ENTER_mes03 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Y eso que es su propia hija...[n]夷Qu姻 narices le ocurre?[n][w][e]

[msg QUEST_58_ENTER_mes04 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]No entiendo mucho de shogi, pero[n]斡s胤 s姻 que esa se隠ora es una arp胤a![n][w][e]

[msg QUEST_58_ENTER_mes05 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]斡Exactamente, se隠orita Ann![n]斡Venga, a por ella![n][w][e]

[msg MSG_000_0_0 [Sombra de Togo]]
[s][vp 8 2 1 48051 65535 0]Hifumi es mi hija.[n]Yo soy su madre. [n][w][e]
[s][vp 1 0 0 0 0 0]斡Le di la vida y la crie! 斡Deber胤a[n]dedicar su existencia a servirme![n][w][e]
[s][vp 1 0 0 0 0 0]斡Cuando Hifumi se convierta[n]en una famosa jugadora de shogi,[n]ser姻 feliz![n][w][e]

[sel SEL_001_0_0 top]
[s]Hifumi no es ning雨n juguete.[e]
[s]Eres una madre horrible.[e]

[msg MSG_002_0_0 [Sombra de Togo]]
[s][vp 1 0 0 0 0 0]Mmm.[n][w][e]
[s][vp 1 0 0 0 0 0]Se piensa que ha ganado por[n]m姻ritos propios, pero la verdad es[n]que las partidas estaban ama隠adas.[n][w][e]

[msg MSG_003_0_0 [Sombra de Togo]]
[s][vp 1 0 0 0 0 0]斡Yo soy quien ha creado un r姻dito[n]comercial a partir de Hifumi![n][w][e]
[s][vp 1 0 0 0 0 0]斡Si yo no me ocupase de[n]sus rivales, ella no habr胤a[n]llegado hasta donde est茨! [n][w][e]
[s][vp 1 0 0 0 0 0]Contrat姻 a detectives privados[n]y a matones para encontrar sus[n]puntos d姻biles y hacerlos trizas.[n][w][e]
[s][vp 1 0 0 0 0 0]Y he sobornado a todos los que[n]sospechaban o se iban de la lengua.[n][w][e]
[s][vp 1 0 0 0 0 0]Ah, y tambi姻n les vend胤 historias[n]a los de las revistas del coraz吋n.[n]斡No hay hero胤na sin tragedia![n][w][e]
[s][vp 1 0 0 0 0 0]Un paso m茨s y la visi吋n de Hifumi[n]que imagin姻 se har茨 realidad.[n]斡Estoy tan cerca de la victoria![n][w][e]
[s][vp 1 0 0 0 0 0]斡No dejar姻 que nadie se interponga![n][w][e]

[msg MSG_004_0_0 [Sombra de Togo]]
[s][vp 1 0 0 0 0 0]Siempre fui una perdedora...[n]Quer胤a saber lo que era el 姻xito,[n]aunque solo fuera una vez.[n][w][e]
[s][vp 1 0 0 0 0 0]No pod胤a ganar yo sola, tuve que[n]utilizar a Hifumi, tuve que...[n][w][e]

[sel SEL_005_0_0 top]
[s]夷Y la felicidad de Hifumi?[e]
[s]Lo que haces est茨 mal.[e]

[msg MSG_006_0_0 [Sombra de Togo]]
[s][vp 1 0 0 0 0 0]Nunca quise hacerla infeliz.[n]De verdad, jam茨s.[n][w][e]
[s][vp 1 0 0 0 0 0]Pero cuando gan吋 aquella[n]competici吋n del instituto...[n][w][e]
[s][vp 1 0 0 0 0 0]Le dec胤an que era un genio y no me[n]lo pod胤a quitar de la cabeza...[n][w][e]
[s][vp 1 0 0 0 0 0]He sido una madre espantosa.[n]Lo siento much胤simo, Hifumi...[n][w][e]

[msg MND_007_0_0]
[s][vp 1 0 0 0 0 0]Parece que Mitsuyo ha despertado.[n]Lo hablar姻 con Hifumi.[n][w][e]

