[msg D154_005_mini_EV_05_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]夷Eh...? Este no tiene[n]contrase隠a ni nada...[n][w][e]

[msg D154_005_mini_EV_05_mes0_2 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A lo mejor por eso lo estaba[n]protegiendo una sombra.[n][w][e]

[msg D154_005_mini_EV_05_mes0_3 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm, no parece que haga falta[n]ninguna clave, pero hay botones[n]a derecha e izquierda...[n][w][e]

[msg D154_005_mini_EV_05_mes0_4 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1187 65535 0]Seguro que lo estaban protegiendo[n]por alg雨n motivo.[n]Hay que intentar averiguar cu茨l es.[n][w][e]

[sel D154_005_mini_EV_05_selA top]
[s]Pulsar el bot吋n derecho[e]
[s]Pulsar el bot吋n izquierdo[e]
[s]No hacer nada[e]

[msg D154_005_mini_EV_05_mes0_5 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Esta es nuestra 雨nica opci吋n.[n]Ten fe y pulsa, a ver qu姻 pasa.[n][w][e]

[sel D154_005_mini_EV_05_selB top]
[s]Pulsar el bot吋n[e]
[s]No pulsarlo[e]

[msg D154_005_mini_EV_05_mes0_6 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2157 65535 0]Mm, parece el mismo dispositivo[n]de antes.[n][w][e]

[msg D154_005_mini_EV_05_mes0_7 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4106 65535 0]Igual sacamos algo de todo esto.[n]Haz lo que tengas que hacer.[n][w][e]

