[msg MSG_Study_Q_Sojiro [Sojiro]]
[s][f 4 23 1 205 33 10 33 10][f 4 23 1 235 31 10 30 10][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5081 65535 0]No tendr茨s tiempo para estudiar[n]cuando salgas al mundo real,[n]as胤 que hazlo ahora que puedes.[n][w][e]

[msg MSG_Study_Q_R [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]夷Qu姻 vas a hacer hoy, estudiar?[n][w][e]

[msg MSG_Study_Q_Rain [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Hoy hace un tiempo de perros,[n]pero es m茨s f茨cil concentrarse en[n]estudiar cuando no puedes salir.[n][w][e]

[msg MND_Study_Q]
[s]Quiz茨 deber胤a[n]pasar el d胤a estudiando.[n][w][e]

[sel SEL_TABLE_USE top]
[s]Estudiar[e]
[s]Cancelar[e]

[msg MSG_Sentou_ParamInfo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Anda, hay mesas libres. Tal vez[n]podr胤as estudiar para mejorar[n]tu [f 4 11 0][clr 26][f 4 12 0][clr 27].[n][w][e]

[msg MND_Sentou_ParamInfo]
[s]Creo que mi [f 4 11 0][clr 26][f 4 12 0][clr 27][n]mejorar茨 si estudio aqu胤.[n][w][e]

[msg MND_Sentou_ParamEndInfo]
[s]Creo que ya tengo suficiente[n][f 4 11 0][clr 26][f 4 12 0][clr 27].[n][w][e]

