[msg D07_BRIEFING_030_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4155 65535 0]El pol胤tico que buscamos est茨[n]en un restaurante exclusivo[n]para miembros.[n][w][e]

[msg D07_BRIEFING_030_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Necesitamos una tarjeta[n]de miembro para entrar...[n]夷Alguien tiene un plan?[n][w][e]

[msg D07_BRIEFING_030_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos a preguntar por ah胤.[n]Cualquier cosa que nos digan[n]nos puede dar alguna pista.[n][w][e]

