[msg D10_BRIEFING_050_mes01 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4169 65535 0]Menos mal que hemos conseguido[n]la tarjeta.[n][w][e]

[msg D10_BRIEFING_050_mes02 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Recordad que no hemos visto qu姻 hay[n]tras la puerta que abre la tarjeta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No sabemos qu姻 clase de trampas[n]nos aguardan. Deber胤amos[n]andarnos con cuidado.[n][w][e]

[msg D10_BRIEFING_050_mes03 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7079 65535 0]Bah, ya tenemos experiencia.[n]斡Todo ir茨 bien![n][w][e]

[msg D10_BRIEFING_050_mes04 [Sumire]]
[s][bup 0 10 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya... 斡Hablas como[n]todo un veterano, Skull![n][w][e]

[msg D10_BRIEFING_050_mes05 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llegados a este punto, cabe[n]destacar que nunca hab胤amos[n]llegado tan lejos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Toda precauci吋n es poca, chavales.[n][w][e]

