[msg dummy_mes]
[s]...[n][w][e]

[msg D10_11_keeper_Clear_star [[f 4 31 10 0]]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hemos acabado con 姻l. Ya podemos[n]ir a por la semilla de deseo.[n][w][e]

[msg D10_11_keeper_Clear_end [Akechi]]
[s][bup 0 9 800 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 54503 65535 0]No tiene sentido dejar algo[n]que nos puede ser 雨til.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya es nuestra.[n][w][e]

