[msg MSG_e295_201_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Mierdaaaa![n][w][e]

[msg MSG_e295_201_001 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aj, esto son...[n][w][e]

[msg MSG_e295_201_002 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Arenas movedizas![n]斡Nadad con todas vuestras fuerzas![n][w][e]

[msg MSG_e295_201_003 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, 夷segu胤s vivos?[n][w][e]

[msg MSG_e295_201_004 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ay...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Primero fue esa roca y ahora esto...[n]夷Qu姻 hemos hecho para que se enfade?[n][w][e]

[msg MSG_e295_201_005 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Creo que no tiene nada que ver[n]con que la hayamos cabreado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Record茨is lo que solt吋 la 雨ltima[n]vez? 或Yo mat姻 a mi madre位.[n]夷Qu姻 querr茨 decir eso?[n][w][e]

[msg MSG_e295_201_006 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No creo que sea cierto.[n]El Jefe dijo que fue[n]un accidente, 夷no?[n][w][e]

[msg MSG_e295_201_007 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero quiz茨 Futaba cree[n]que fue culpa suya.[n][w][e]

[msg MSG_e295_201_008 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya... Entonces, puede que[n]esto no sea una tumba normal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Algunas teor胤as afirman que[n]las pir茨mides no son tumbas,[n]sino dispositivos de resurrecci吋n.[n][w][e]

[msg MSG_e295_201_009 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 pues, el deseo que origin吋 este[n]Palacio es su anhelo por volver[n]a ver a su madre.[n][w][e]

[msg MSG_e295_201_00A [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Qu姻 triste! 斡夷Por qu姻[n]se ha hecho una tumba[n]para ella tambi姻n?![n][w][e]

[msg MSG_e295_201_00B [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, en ese caso, es posible que[n]la sombra de Futaba no sea hostil[n]con nosotros de forma deliberada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No puede evitar rechazar a otras[n]personas. Es una reacci吋n natural,[n]dada su situaci吋n.[n][w][e]

[msg MSG_e295_201_00C [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Joker, hay que salvarla! 斡Tenemos que ayudar[n]a Futaba para que abra[n]la puerta a su coraz吋n![n][w][e]

[sel SEL_e295_201_00D top]
[s]Claro.[e]
[s]Primero tenemos que escapar.[e]

[msg MSG_e295_201_00E [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No tengo nada en contra,[n]pero ahora deber胤amos[n]preocuparnos por nosotros mismos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Venga, tenemos que subir a la[n]superficie o este sitio tambi姻n[n]acabar茨 siendo nuestra tumba.[n][w][e]

[msg MSG_e295_201_00F [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, pero ahora deber胤amos[n]preocuparnos por nosotros mismos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Venga, tenemos que subir a la[n]superficie o este sitio tambi姻n[n]acabar茨 siendo nuestra tumba.[n][w][e]

