[msg e210_160_mes01 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]Mierda... 斡夷Qu姻 narices le pasa[n]a este sitio de los cojones?![n][w][e]

[msg e210_160_mes02 [Ann]]
[s][bup 0 4 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hay oro a tutipl姻n![n]Duele hasta mirarlo...[n][w][e]

[msg e210_160_mes03 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1040 65535 0]La distorsi吋n es especialmente mala[n]aqu胤. Aguanta a duras penas.[n]Adem茨s, no est茨 ni en nuestro mapa.[n][w][e]

[msg e210_160_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Debemos confiar solo en la vista[n]para determinar la verdad.[n][w][e]

