[msg D01_04_e160_086_mes01 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]*jadeo* *jadeo* No sab胤a[n]que pod胤an ser tan duros...[n][w][e]

[msg D01_04_e160_086_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤... Parece[n]que se ha empe隠ado[n]en detenernos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, te he ense隠ado ya[n]unas cuantas cosas, pero no[n]hay tiempo para lecciones.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voy a recopilar informaci吋n que[n]necesitas saber para combatir, no[n]olvides echarle un ojo m茨s tarde.[n][w][e]

[msg D01_04_e160_086_mes05 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Mierda... Hay m茨s...[n][w][e]

[msg D01_04_e160_086_mes06 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 hacemos? 夷Volvemos?[n][w][e]

[msg D01_04_e160_086_mes07 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No. El tesoro est茨 m茨s adelante,[n]y tiene que haber[n]un camino para llegar hasta 姻l.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ves algo que nos pueda servir[n]para pasar por aqu胤? 斡Al loro![n][w][e]

[msg D01_04_e160_086_af_mes02]
[s]或Estados alterados位, 或Afinidades位,[n]或Acometida位 y 或Ayuda de selec. de hab.位[n]a隠adidos al tutorial de combate.[n][w][e]
[s]Puedes ver tutoriales anteriores[n]en la secci吋n 或Tutoriales位[n]del men雨 [f 1 10 25].[n][w][e]

[msg D01_04_e160_091_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aqu胤 hay gato encerrado.[n]La puerta tiene hasta enredaderas.[n][w][e]

[msg D01_04_e160_091_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤. A juzgar por su aspecto, hace[n]mucho que no viene nadie por aqu胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ojal茨 tuvi姻ramos forma de pasar...[n][w][e]

[msg D01_04_e160_091_mes03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No veo nada de utilidad. L茨stima[n]que no podamos saltar sin m茨s.[n][w][e]

[msg D01_04_e160_091_mes04]
[s]夷...?[n][w][e]

[msg D01_04_e160_091_mes05]
[s]夷Eso es...?[n][w][e]

[msg D01_04_e160_091_mes06 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 pasa, Joker?[n][w][e]

[sel D01_04_e160_091_selA top]
[s]Es hora de darle uso a tu regalito.[e]
[s]Es la ocasi吋n perfecta.[e]

[msg D01_04_e160_091_mes07 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Qu姻 est茨s...? 斡Ah, genial![n]斡Es hora del arpeo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si lo usas bien podr茨s cruzar[n]sin problema, pero[n]夷a d吋nde vas a apuntar?[n][w][e]

[msg D01_04_e160_092_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hostia puta! 斡夷Has visto eso?![n]斡Hemos pasado en un suspiro![n][w][e]

[msg D01_04_e160_092_mes02 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No me ha dado tiempo ni a reponerme[n]de la sorpresa. Es super雨til.[n][w][e]

[msg D01_04_e160_092_mes03 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Qu姻 bien te mueves, Joker![n]斡Sab胤a que hab胤as nacido para esto![n][w][e]
[s][bup 0 3 8 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siempre que veas una zona[n]inalcanzable a pie, el arpeo[n]puede serte de ayuda.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Busca cualquier cosa en la que[n]engancharte. Es fundamental para[n]los Ladrones Fantasma. 夷Entendido?[n][w][e]

[msg D01_04_e160_092_mes04 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya estamos...[n][w][e]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ech姻mosle un vistazo a esa puerta.[n][w][e]

[msg D01_04_e160_093_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1109 65535 0]Uf... Ha faltado poco. 斡Buena, Joker![n]Ha sido un enganche de categor胤a. [n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ya podemos investigar[n]esta zona! Vamos al l胤o.[n][w][e]

