[msg D02_mi_e205_101_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7037 65535 0]斡Tronco, se va a cerrar la puerta[n]como no nos demos vida![n][w][e]

[msg D02_mi_e205_103_mes01 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]A la sala de control, deprisa.[n]El camino se va a cerrar como nos[n]quedemos haciendo el gilipollas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos a estar solos[n]si nos encontramos[n]con alg雨n enemigo. 夷Listo?[n][w][e]

[sel D02_mi_e205_103_selA top]
[s]Vamos a darles para el pelo.[e]
[s]Estoy preocupado.[e]

[msg D02_mi_e205_103_selA_0_m [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7023 65535 0]Eso es, 斡cuento contigo![n][w][e]

[msg D02_mi_e205_103_selA_1_m [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7198 65535 0]La verdad es que me siento igual.[n][w][e]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero Mona y Panther ya han arrimado[n]el hombro. 斡Ahora nos[n]toca a nosotros![n][w][e]

[msg D02_mi_e207_120_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7103 65535 0]Vale, parece[n]que toda la seguridad est茨 kaput.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos con los dem茨s.[n][w][e]

[msg D02_mi_e207_121_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]斡Hay que salir de aqu胤![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]A todo esto, ahora tenemos[n]a un novato con nosotros.[n]Evitemos luchar.[n][w][e]

