[msg D01_04_e160_051_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Espera, Joker![n][w][e]

[msg D01_04_e160_051_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1148 65535 0]夷Podemos echar otro vistazo[n]antes de volver? Puede que[n]haya alg雨n camino oculto.[n][w][e]

[msg D01_04_e159_020_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]Joder, este sitio est茨 petado[n]de sombras, como siempre.[n][w][e]

[msg D01_04_e159_020_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cierto, pero no nos descubrir茨n[n]desde donde estamos ahora. 斡Es[n]un punto de infiltraci吋n genial![n][w][e]

[sel D01_04_e159_020_selA top]
[s]Es gracias a Panther.[e]
[s]Esto es 雨til.[e]
[s]Sigamos.[e]

[msg D01_04_e159_020_selA_0_m [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6027 65535 0]夷Eh? 斡Ah, es verdad, esa soy yo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es que... todav胤a no me[n]he acostumbrado a ese nombre.[n][w][e]

[msg D01_04_e159_020_selA_0_m_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7095 65535 0]De todas formas, nos viene bien[n]haber visto c吋mo era este sitio[n]cuando estuvimos aqu胤.[n][w][e]

[msg D01_04_e159_020_selA_1_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1022 65535 0]Cierto. Desde aqu胤 deber胤amos poder[n]llegar a lugares[n]que no hemos revisado todav胤a.[n][w][e]

[msg D01_04_e159_020_selA_1_m_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]De todas formas, nos viene bien[n]haber visto c吋mo era este sitio[n]cuando estuvimos aqu胤.[n][w][e]

[msg D01_04_e159_020_selA_2_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1047 65535 0]夷Mm? Qu姻 animado est茨s, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aun as胤, si no tenemos cuidado,[n]nos acabar茨n echando[n]como la 雨ltima vez.[n][w][e]

[msg D01_04_e159_020_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6019 65535 0]Nuestro objetivo ahora es[n]encontrar el tesoro, 夷verdad?[n][w][e]

[msg D01_04_e159_020_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aj茨.[n][w][e]

[msg D01_04_e159_020_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como he dicho antes, tenemos que[n]encontrar el tesoro y asegurar[n]un camino hasta donde se encuentre.[n][w][e]

[msg D01_04_e159_020_mes06 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7192 65535 0]No entiendo lo que dices[n]de asegurar no s姻 qu姻[n]de un camino...[n][w][e]

[msg D01_04_e159_020_mes07 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te lo explicar姻 cuando[n]encontremos el tesoro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No creo que lo entendieras[n]si te lo ense隠ara todo de golpe.[n][w][e]

[msg D01_04_e159_020_mes08 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, supongo que es verdad... Espera,[n]me da la sensaci吋n de que[n]te est茨s riendo de m胤.[n][w][e]

[msg D01_04_e159_020_mes9 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, sigamos haciendo[n]lo que diga Mona.[n][w][e]

[msg D01_04_e159_020_mes10 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tendremos que buscar sitios[n]que todav胤a no hayamos revisado.[n][w][e]

