[msg D04_03_e296_231_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Es el mismo mecanismo[n]que vimos antes.[n][w][e]

[msg D04_03_e296_231_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Tenemos que tocarlo y pasar茨 algo,[n]夷no? Venga, vamos a intentarlo.[n][w][e]

[msg MSG_e296_231_AF_000 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 15 0 0]Algo ocurrir茨 si logramos ordenar[n]la imagen. Venga, vamos[n]a intentarlo otra vez.[n][w][e]

[msg D04_03_e296_231_AF02_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]Parece que el reflejo de la luz[n]ha cambiado de direcci吋n[n]al resolver el puzle.[n][w][e]

[msg D04_03_e296_231_AF02_mes_2 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Venga, vamos a ver si ya[n]se ha abierto la puerta.[n][w][e]

[msg D04_03_e296_201_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4155 65535 0]Parece que vuelve a estar en orden.[n][w][e]

[msg D04_03_e296_201_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]夷Est茨 tir茨ndose[n]delante de un coche...?[n][w][e]

[msg D04_03_e296_201_mes03 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]夷Ser茨 el momento en el que[n]la madre de Futaba se suicid吋...?[n][w][e]

[msg D04_03_e296_201_mes04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]夷Eh? Otra voz...[n][w][e]

[msg D04_03_e296_201_mes05 [Mujer joven]]
[s](廃人化するときの恐ろしいうめき)[n][w][e]

[msg D04_03_e296_201_mes06 [Voz de mujer joven]]
[s][vp 1 0 0 9 0 0]F-Futabaaaa...[n][w][e]
[s][vp 1 0 0 10 0 0]E-ereeeeees...[n][w][e]

[msg D04_03_e296_201_mes07]
[s](SE)車の衝突音[n][w][e]

[msg D04_03_e296_201_mes08 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 11 0 0]Muri吋 justo delante de Futaba.[n][w][e]

[msg D04_03_e296_201_mes09 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 12 0 0]Qu姻 horror...[n][w][e]

[msg D04_03_e296_201_mes10 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 13 0 0]Entonces, 夷el deseo[n]de olvidar esos recuerdos[n]ha hecho que los reprima?[n][w][e]

[msg dummy_mes01]
[s](仮)反射板が動く[n][w][e]

[msg dummy_mes02]
[s](仮)光が反射される[n][w][e]

[msg dummy_mes03]
[s](仮)壁画が消える[n][w][e]

[msg dummy_mes04]
[s](仮)扉がひらく[n][w][e]

[msg D04_PUZZLE_dummy1_mes01]
[s](仮)パズルギミック調整中のため飛ばします[n][w][e]

