[msg MSG_QST_084_01 [Haru]]
[s][bup 0 7 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3197 65535 0]As胤 que ese es Nao Minamoto.[n][w][e]

[msg MSG_QST_084_02 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Quiere suicidarse por haberle hecho[n]da隠o a su hermana.[n][w][e]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]No podemos dejarle.[n][w][e]

[msg MSG_QST_084_03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Parece tener la determinaci吋n[n]de alguien que quiere suicidarse.[n][w][e]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9158 65535 0]斡Cuidado, Joker![n][w][e]

[msg MSG_QST_084_04 [Sombra de Minamoto]]
[s]Los Ladrones Fantasma...[n]Hab姻is venido.[n][w][e]
[s]Bien... Ya no podr姻 volver a hacerle[n]da隠o a mi hermana.[n][w][e]

[msg MSG_QST_084_05 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2037 65535 0]No hemos venido a matarte.[n]Vamos a despertar tu coraz吋n.[n][w][e]

[msg MSG_QST_084_06 [Sombra de Minamoto]]
[s][vp 8 2 1 46759 65535 0]夷Despertar? No, yo quiero[n]que me mat姻is.[n][w][e]
[s]Porque... porque yo...[n][w][e]
[s]斡La odio! 斡Odio a mi hermana[n]por entrometerse en mi vida![n][w][e]
[s]斡Si no fuera por ella,[n]podr胤a haber ido al instituto[n]y a la universidad![n][w][e]
[s]斡Podr胤a haber salido con mis amigos[n]en lugar de trabajar todo el d胤a![n]斡Podr胤a haberme unido a alg雨n club![n][w][e]

[msg MSG_QST_084_07 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7046 65535 0]斡Pi姻nsatelo mejor![n][w][e]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Todav胤a hay una parte de ti[n]que desea protegerla, aunque[n]implique renunciar a tu tiempo.[n][w][e]

[msg MSG_QST_084_08 [Sombra de Minamoto]]
[s]S胤... No deber胤a pensar as胤.[n]No es cierto.[n][w][e]
[s]Quiero... quiero que tenga una vida[n]diferente a la m胤a. Lo que m茨s[n]quiero es que sea feliz...[n][w][e]
[s]斡No! 斡La odio![n]斡La odio con toda mi alma![n][w][e]
[s]No, 斡eso no es verdad![n]Matadme... Quiero morir.[n][w][e]
[s]Mam茨, pap茨, 夷por qu姻[n]me dejasteis as胤?[n][w][e]
[s]斡夷Por... Por qu姻 no me escuch茨is?![n][w][e]
[s]斡Os pido que me mat姻is![n][w][e]

[msg MSG_QST_084_09 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9065 65535 0]斡Cuidado, Joker! 斡Va a atacar![n][w][e]

[msg MSG_QST_084_10 [Sombra de Minamoto]]
[s][vp 8 2 1 0 65535 0]*soplido* *jadeo*[n][w][e]

[msg MSG_QST_084_11 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2017 65535 0]夷Est茨s bien? 夷Te has tranquilizado?[n][w][e]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Seguro que lo has pasado mal[n]dici姻ndote a ti mismo que[n]odias a tu hermana.[n][w][e]

[msg MSG_QST_084_12 [Sombra de Minamoto]]
[s][vp 8 2 1 0 65535 0]S胤...[n][w][e]
[s]Pero no es algo que me dijera[n]a m胤 mismo.[n][w][e]

[msg MSG_QST_084_13 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]夷Eh...?[n][w][e]

[msg MSG_QST_084_14 [Sombra de Minamoto]]
[s][vp 8 2 1 0 65535 0]Me negaba a creer que parte de m胤[n]sent胤a eso por mi hermana.[n][w][e]
[s]Cuanto m茨s lo negaba,[n]m茨s crec胤a el sentimiento, hasta[n]que se volvi吋 algo monstruoso.[n][w][e]
[s][vp 8 2 1 46766 65535 0]Ahora puedo aceptar[n]esa parte de m胤.[n][w][e]

[msg MSG_QST_084_15 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2132 65535 0]Eso quiere decir...[n][w][e]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]夷De verdad odiabas a tu hermana?[n][w][e]

[msg MSG_QST_084_16 [Sombra de Minamoto]]
[s][vp 8 2 1 0 65535 0]S胤, as胤 lo siento.[n][w][e]
[s]Pero tambi姻n[n]es cierto que la quiero.[n][w][e]
[s]Ambos sentimientos son reales.[n][w][e]

[sel SEL_Q84_BATTLE_A17 top]
[s]夷Todav胤a quieres que te matemos?[e]
[s]Se acab吋 el querer morir.[e]

[msg MSG_QST_084_18 [Sombra de Minamoto]]
[s]No...[n][w][e]
[s]Si muriera ahora, mi hermana[n]estar胤a completamente sola.[n]No puedo dejar que eso ocurra.[n][w][e]

[msg MSG_QST_084_19 [Sombra de Minamoto]]
[s]Gracias...[n][w][e]
[s]Me vienes con eso incluso[n]despu姻s de haberte dicho[n]que odio a mi hermana...[n][w][e]
[s]A lo mejor envi姻 esa petici吋n[n]porque era lo que quer胤a escuchar.[n][w][e]

[msg MSG_QST_084_20 [Sombra de Minamoto]]
[s][vp 8 2 1 0 65535 0]Seguramente ya no pueda estar[n]con mi hermana despu姻s[n]de haberla herido, pero...[n][w][e]
[s]Me alegro mucho de poder volver[n]a querer a mi hermana.[n][w][e]
[s][vp 8 2 1 46769 65535 0]Gracias, Ladrones Fantasma...[n][w][e]

