[msg D03_BRIEFING_080_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6162 65535 0]No me puedo creer que haya[n]un sitio as胤 aqu胤 tambi姻n. Supongo[n]que en un Palacio cabe de todo.[n][w][e]

[msg D03_BRIEFING_080_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ver, la realidad ya se fue[n]a tomar por saco cuando vimos[n]esta cosa flotando en el aire.[n][w][e]

[msg D03_BRIEFING_080_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Es incre胤ble lo complejo que puede[n]ser el coraz吋n de la gente. Los[n]anteriores no eran muy distintos.[n][w][e]

[msg D03_BRIEFING_080_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, s胤, recuerdo haber o胤do[n]que vuestro primer asalto[n]tuvo lugar en un castillo antiguo.[n][w][e]

[msg D03_BRIEFING_080_mes05 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Era como una fantas胤a medieval?[n][w][e]

[msg D03_BRIEFING_080_mes06 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7114 65535 0]Dicho as胤, suena hasta bien,[n]pero eran los deseos[n]de ese cabr吋n de Kamoshida.[n][w][e]

[msg D03_BRIEFING_080_mes07 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, deber胤amos irnos. Si superamos[n]esta zona, seguramente llegaremos[n]a las profundidades del Palacio.[n][w][e]

