[msg D05_02_e341_091_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Esta es la zona de las escotillas...[n]斡夷Eso significa que tenemos[n]que ir al espacio?![n][w][e]

[msg D05_02_e341_091_mes02 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Creo que tal acci吋n conducir胤a a nuestro[n]exterminio, por no decir algo peor.[n][w][e]

[msg D05_02_e341_091_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Bueno, parece que estar姻is bien[n]durante treinta segundos[n]si cerr茨is los ojos y la boca.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Es raro. La verdad es que pensaba[n]que 胤bamos a explotar[n]si sal胤amos ah胤 fuera.[n][w][e]

[msg D05_02_e341_091_mes04 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]斡No nos asustes as胤, joder![n][w][e]

