[msg D05_BRIEFING_070_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]Oye, 斡pues esta mierda de volar[n]por el espacio s胤 que mola![n]Ya casi hemos llegado...[n][w][e]

[msg D05_BRIEFING_070_mes02 [Futaba]]
[s][bup 0 8 105 0 0]......[n][w][e]

[msg D05_BRIEFING_070_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tienes mala cara, Oracle.[n]夷Te encuentras bien?[n][w][e]

[msg D05_BRIEFING_070_mes04 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2028 65535 0]Debe haberse mareado...[n][w][e]

[msg D05_BRIEFING_070_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya casi hemos llegado al tesoro.[n]斡Aguanta un poco, Oracle![n][w][e]

[msg D05_BRIEFING_070_mes06 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E-eso intento.[n][w][e]

