[msg EV_SEL_MES_157_011_mes01 [Voz mec茨nica]]
[s]Seleccione una planta.[n][w][e]

[sel EV_SEL_MES_157_011_selA top]
[s]Ir a la planta de miembros[e]
[s]Ir a la planta normal[e]
[s]Da igual[e]

[msg EV_SEL_MES_157_011_selA_ [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg EV_SEL_MES_157_011_selA__2 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg EV_SEL_MES_157_011_selA__3 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

