[msg e200_120_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]A partir de aqu胤, estamos[n]en territorio desconocido, 夷no?[n][w][e]

[msg e200_120_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Probablemente tambi姻n haya[n]m茨s medidas de seguridad.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aseguraos de no tocar nada[n]ni tropezar con ninguna obra,[n]夷queda claro?[n][w][e]

[msg e200_120_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 me miras a m胤?[n][w][e]

