[msg MSG_NG_NotSetTv_NoIdea [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Anda, un videoclub.[n][w][e]
[s][f 4 10 65535 0 0]Una pena que no tengas tele.[n]No hay raz吋n para ir ahora mismo.[n][w][e]

[msg MSG_NG_SetTv_NoIdea [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Anda, un videoclub.[n][w][e]
[s][f 4 10 65535 0 0]Tienes tele, pero no un DVD.[n]No hay raz吋n para ir ahora mismo.[n][w][e]

[msg MSG_Rental_SetUp_OK_1ST [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Anda, un videoclub.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Anda, mira ese anuncio. Tienen[n]una campa隠a de afiliaci吋n anual.[n][w][e]

[msg MSG_YearSp_Info01 [Trabajador de tienda de alquiler]]
[s]斡Buenas![n][w][e]
[s]夷Te gustar胤a solicitar nuestra[n]afiliaci吋n anual? Para estudiantes,[n]son 4800 yenes durante la campa隠a.[n][w][e]
[s]斡Alquila todos los DVD antiguos[n]que quieras sin cuota de extensi吋n![n]Solo puedes llevarte uno cada vez.[n][w][e]

[msg MSG_YearSp_Info02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1108 65535 0]Tenemos mucho l胤o, as胤 que no[n]tener que preocuparnos por[n]la cuota de extensi吋n es genial.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Si tienes el dinero, a lo mejor[n]deber胤as apuntarte.[n][w][e]

[msg MSG_YearSp_Info03 [Trabajador de tienda de alquiler]]
[s]斡Solo 4800 yenes al a隠o para[n]estudiantes! 夷Qu姻 vas a hacer?[n][w][e]

[sel SEL_RentalAdmin top]
[s]Apuntarme.[e]
[s]No me interesa.[e]

[msg MSG_YearSp_Info04 [Trabajador de tienda de alquiler]]
[s]斡Muchas gracias! 夷Me ense隠as[n]tu carn姻 de estudiante?[n][w][e]
[s]Vives en... Yongen-Jaya...[n]Firma aqu胤... 斡Listo![n][w][e]

[msg MSG_YearSp_Info05 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0]Te temblaban las manos[n]al escribir 或[f 4 3]位.[n]Estabas nervioso, 夷no?[n][w][e]

[msg MSG_YearSp_Info06 [Trabajador de tienda de alquiler]]
[s]Como ya eres socio, puedes[n]alquilar DVD desde hoy mismo.[n][w][e]

[msg MSG_YearSp_Cancel [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1022 65535 0]Ah, 夷no te apuntas?[n][w][e]

[msg MSG_YearSp_NoMoney [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0]Madre m胤a, no tienes ni un duro.[n]夷Por qu姻 no consigues[n]un trabajo a tiempo parcial?[n][w][e]

[msg MSG_Rental_LoopStart [Trabajador de tienda de alquiler]]
[s]夷Necesita algo m茨s?[n][w][e]

[msg MSG_Rental_ShopStart [Trabajador de tienda de alquiler]]
[s]斡Bienvenido! 夷Qu姻 desea?[n][w][e]

[msg MSG_RentalGreetingBefore [Trabajador de tienda de alquiler]]
[s]De acuerdo...[n][w][e]

[msg MSG_Rental_ShopStart_New [Trabajador de tienda de alquiler]]
[s]斡Hola! 斡Nos han llegado[n]varios DVD nuevos![n][w][e]

[msg MSG_Rental_ShopStart_Can [Trabajador de tienda de alquiler]]
[s]Vuelva pronto.[n][w][e]

[sel SEL_Rental_Q top]
[s]Alquilar un DVD[e]
[s]Devolver DVD[e]
[s]Irse[e]

[sel SEL_Rental_Q2 top]
[s]Alquilar un DVD[e]
[s]Irse[e]

[msg MSG_Rental_ShopUse [Trabajador de tienda de alquiler]]
[s]斡Muchas gracias![n]斡Vuelve pronto![n][w][e]

[msg MSG_Rental_ReturnStart [Trabajador de tienda de alquiler]]
[s]夷Viene a devolver un DVD?[n][w][e]

[msg MSG_Rental_NotComp_Q [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Un momento... A雨n no hemos terminado.[n]夷Vas a devolverlo?[n][w][e]

[sel SEL_Rental_NotComp_Q top]
[s]Devolverlo[e]
[s]Todav胤a no[e]

[sel SEL_Rental_Return_Q top]
[s]Pagar[e]
[s]Volver luego[e]

[msg MSG_Rental_Over_Return [Trabajador de tienda de alquiler]]
[s]Much胤simas gracias.[n][w][e]

[msg MSG_Rental_Over_ReturnCa [Trabajador de tienda de alquiler]]
[s]Entendido. Por favor, devu姻lvalo[n]antes de que se pase el plazo.[n][w][e]

