[msg D190_01_OPEN_EV06_01_mes]
[s]El Meta-Nav est茨 reaccionando.[n][w][e]

[msg D190_01_OPEN_EV06_02_mes [Navegador del Metaverso]]
[s]Se ha confirmado una nueva[n]zona en las profundidades.[n]Actualizando informaci吋n de gu胤a.[n][w][e]

[msg D190_01_OPEN_EV06_02_mes_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que el n雨mero de 茨reas a las[n]que podemos acceder ha aumentado.[n][w][e]

[msg D190_01_OPEN_EV06_02_mes_3 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora hay mucha m茨s gente[n]que sabe qui姻nes somos, aunque[n]no sea por los mejores motivos.[n][w][e]

[msg D190_01_OPEN_EV06_02_mes_4 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estoy segura de que el malentendido[n]se resolver茨 cuando acabemos con[n]esto. 斡Alegrad esas caras![n][w][e]

[msg D190_01_OPEN_EV06_02_mes_5 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tiene raz吋n. Adem茨s, cuanto m茨s[n]nos adentremos, m茨s poderosos ser茨n[n]los enemigos. Id con cuidado.[n][w][e]

[msg D190_01_OPEN_EV06_02_mes_6 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vamos a intentar localizar[n]el cambio, Joker.[n][w][e]

