[msg DRESSTALK_DLC_NONE [NADA]]
[s]DLC衣装装備者なし[n][w][e]

[msg DRESSTALK_ERROR [NADA]]
[s]Error[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, llevas ropa de verano.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los polos del Shujin molan[n]bastante, 夷no? Adem茨s, son c吋modos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero aunque fuera verano,[n]no llevar胤a ese uniforme. Para m胤,[n]la ropa que llevo ya es perfecta.[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ese es el uniforme de verano[n]del Shujin? Tiene pinta de ser[n]c吋modo y de no dar nada de calor.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Yo tambi姻n tengo uniforme de[n]verano! Cep胤llame cuando[n]crezca, 夷vale?[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, llevas el uniforme de verano.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷T雨 crees que esos polos[n]son c吋modos y modernos?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hace bastante calor fuera.[n]A lo mejor yo tambi姻n me cambio.[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, Joker, 夷ese es el uniforme[n]de verano del Shujin?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta la nitidez del blanco[n]y que no d姻 calor. El dise隠o[n]de la camiseta tambi姻n est茨 bien.[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has puesto[n]el uniforme de verano del Shujin.[n][f 4 10 65535 0 0][f 4 25 1 65535 0 0][w][e]
[s]夷El negro y el rojo[n]no son una combinaci吋n inusual[n]para un uniforme de instituto?[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, Joker. 夷Llevas puesto[n]el uniforme de verano del Shujin?[n][w][e]
[s]夷Qu姻 tal en comparaci吋n[n]con el de tu anterior instituto?[n]Espero que te resulte m茨s c吋modo.[n][w][e]
[s]Pero como es tan blanco,[n]se nota enseguida[n]si tiene manchas o est茨 sucio.[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, 夷ese es el uniforme de[n]verano del Shujin?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm... Te sienta bien, pero siempre[n]me he preguntado lo siguiente.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 hay que ir al instituto[n]con ropa fresquita cuando puedes[n]estudiar en casa?[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es el uniforme de verano del[n]Shujin? Nosotros llevamos camisas[n]de vestir, as胤 que me dais envidia.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si no recuerdo mal, llevabais los[n]de verano cuando nos conocimos[n]en la cadena de televisi吋n, 夷no?[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, 夷te has cambiado?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta la sencillez del uniforme[n]de verano. Se ve limpio[n]y es fresquito.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, ese es[n]el uniforme de invierno, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, te queda bien, pero[n]tambi姻n es como...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No parece muy distinto, 夷verdad?[n]Me hace pensar: 或S胤, 斡eres t雨!位.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, el uniforme de invierno[n]del Shujin, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pareces el mismo de siempre, pero[n]te queda bien. Me gustar胤a[n]probarme un uniforme alg雨n d胤a.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Llevas el uniforme de invierno[n]del Shujin?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No crees que los uniformes est茨n[n]a la 雨ltima? Me encanta c吋mo[n]han usado el rojo, negro y blanco.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷ese es tu uniforme[n]de invierno?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, parece abrigado.[n]Tambi姻n me gusta el dise隠o[n]sencillo en rojo y negro.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Te has puesto[n]el uniforme de invierno?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puede que me est姻 repitiendo, pero[n]te queda bien. 夷C吋mo era el[n]uniforme de tu antiguo instituto?[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Llevas el uniforme de invierno[n]del Shujin?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hoy hace un poco de fr胤o.[n]Voy a tener que abrigarme tambi姻n.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nuestro uniforme tiene mucho negro,[n]as胤 que puede estar bien[n]para parecer ladrones.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira, el uniforme de invierno[n]del Shujin.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un l胤o que los institutos usen[n]distintos uniformes. Le pedir姻[n]a Sojiro que lo saque del armario.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No me gusta el calor, as胤 que creo[n]que volver姻 a mi[n]uniforme de verano.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ese es el uniforme de invierno[n]del Shujin?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El dise隠o es m茨s oscuro que el de[n]nuestro instituto. No digo que[n]sea malo. Me gusta bastante.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espero que no te moleste, pero...[n]夷ten胤as que ponerte eso aqu胤?[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No deber胤a decirlo siendo novata,[n]pero me gusta el estilo desenfadado[n]del uniforme de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A lo mejor ya te lo he dicho, pero[n]te queda bien. Llevabas eso[n]cuando me ayudaste.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Esa es tu ropa informal[n]de verano? Mola, y parece[n]que no da calor.[n][w][e]
[s]Pero no me van mucho[n]las camisas con cuello.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker. Llevas[n]puesta ropa informal de verano.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es bonita.[n]La camiseta negra te sienta genial.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, ropa de verano.[n][w][e]
[s]Las camisas blancas son lo m茨s.[n]斡Creo que te queda muy bien![n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker. Te has puesto[n]la ropa informal de verano.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷C吋mo consigues que una sencilla[n]camiseta negra sea elegante? Igual[n]es por la blanca que llevas encima.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La ropa puede inspirar arte.[n]Puede que mi pr吋xima obra[n]sea en blanco y negro.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷te has puesto[n]la ropa de verano?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te queda bien. Seguro que[n]con eso est茨s muy fresquito.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero... 夷servir茨 para pelear?[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, 夷te has puesto[n]la ropa informal de verano?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Tienes por costumbre remangarte?[n]夷O es porque hace calor?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo tambi姻n lo hago. Si no,[n]me pondr胤a perdida. Tambi姻n me da[n]m茨s libertad de movimiento.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Conque ropa informal de verano,[n]夷eh, Joker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Recuerdo que llevabas eso puesto[n]la primera vez que te vi.[n]Marc吋 un antes y un despu姻s.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Gracias otra vez[n]por lo que hiciste.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Esa es tu ropa de verano? Parece[n]adecuada para un d胤a caluroso.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, Joker, te has cambiado de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eso es lo que llevas en verano?[n]Te queda muy bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tienes una figura envidiable,[n]as胤 que te pongas[n]lo que te pongas, te quedar茨 bien.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que ropa de invierno, 夷eh?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es calentita? Yo nunca llevo[n]chaquetas, as胤 que no s姻.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero te sienta bien. Aunque, t胤o...[n]tienes un montonazo de ropa[n]blanca y negra.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevas ropa de invierno, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tienes much胤sima ropa blanca[n]y negra. 夷Intentas imitarme?[n]Es porque soy superguay, 夷verdad?[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker.[n]Llevas ropa de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es dif胤cil que una chaqueta as胤[n]quede bien, pero t雨 est茨s de miedo.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado de traje, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ropa de invierno? Te queda bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esa chaqueta tiene pinta de ser[n]calentita. Adem茨s, es moderna[n]y los colores combinan bien.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que ropa de invierno, 夷eh?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La chaqueta tiene mucha clase.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y no tiene arrugas... Has debido[n]de doblarla la mar de bien.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Llevas ropa de invierno?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Te gusta la ropa oscura?[n]Siempre sueles ir de negro.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que ropa de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Pareces todo un adulto[n]con esa chaqueta![n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Esa es tu ropa de invierno?[n]Vaya, la m胤a es similar.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷te has puesto[n]tu ropa de invierno?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te sienta genial.[n]夷Te gustan m茨s las prendas ce隠idas?[n][w][e]

[msg DRESSTALK_JERSEY_PC01_PC [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ah! Llevas ropa de deporte.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es la mar de c吋moda,[n]perfecta para cualquier ocasi吋n.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hala, t胤o! 夷Vas a correr?[n]斡Me apunto![n][w][e]

[msg DRESSTALK_JERSEY_PC01_PC_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Seguro que es muy c吋moda![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ropa de deporte, 夷eh? 斡Quiz茨[n]sea 雨til para moverse en combate![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque no es el mejor atuendo[n]para un Ladr吋n Fantasma...[n][w][e]

[msg DRESSTALK_JERSEY_PC01_PC_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker.[n]夷Llevas ropa de deporte?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece bastante c吋moda, pero[n]a m胤 no me gusta mucho.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me recuerda al torneo[n]de voleibol y a Kamoshida...[n]Pero el rojo me gusta.[n][w][e]

[msg DRESSTALK_JERSEY_PC01_PC_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ropa de deporte?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te queda bien. Aunque el ch茨ndal[n]del instituto es m茨s elegante.[n][w][e]

[msg DRESSTALK_JERSEY_PC01_PC_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, 夷llevas ropa de deporte?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puede que sea m茨s f茨cil investigar[n]as胤. Quiz茨 me cambie yo tambi姻n.[n][w][e]

[msg DRESSTALK_JERSEY_PC01_PC_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, llevas ropa de deporte.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm... Parece fresca, y ser茨 f茨cil[n]moverse con ella. La ropa[n]de deporte es la mar de 雨til.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Yo siempre me la pongo para[n]trabajar en el jard胤n. Tambi姻n[n]me gusta el dise隠o.[n][w][e]

[msg DRESSTALK_JERSEY_PC01_PC_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Eh?! 斡夷Ese es el ch茨ndal[n]del instituto?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷El atuendo m茨gico que solo[n]pueden llevar aquellos[n]con la velocidad del rayo?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pues te queda bien, pero yo[n]nunca me lo pondr胤a.[n][w][e]

[msg DRESSTALK_JERSEY_PC01_PC_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es el ch茨ndal del Shujin?[n]El rojo llama la atenci吋n.[n][w][e]

[msg DRESSTALK_JERSEY_PC01_PC_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, 夷te has cambiado?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esa ropa de deporte te sienta[n]como un guante. Es muy c吋moda,[n]斡y me recuerda a Educaci吋n F胤sica![n][w][e]

[msg DRESSTALK_SWIM_PC01_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye... 夷eso es un ba隠ador?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ver... seguro que es fresquito...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero cuanto m茨s lo miro, m茨s ganas[n]tengo de nadar. Vayamos a una[n]piscina climatizada alg雨n d胤a.[n][w][e]

[msg DRESSTALK_SWIM_PC01_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Anda, Joker, vas en ba隠ador![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Buena idea! Puede que en alg雨n[n]Palacio o en Mementos[n]tengamos que nadar.[n][w][e]
[s]...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eso es! 斡夷Por qu姻 vas[n]en ba隠ador?! 斡Un Ladr吋n[n]Fantasma jam茨s llevar胤a algo as胤![n][w][e]

[msg DRESSTALK_SWIM_PC01_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, Joker, ese es tu ba隠ador, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No es que tenga ning雨n problema,[n]pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 tienes eso? Es m茨s,[n]夷por qu姻 te has puesto eso?[n][w][e]

[msg DRESSTALK_SWIM_PC01_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻...? 夷Llevas un ba隠ador?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La visi吋n de tu cuerpo en contraste[n]con el fondo del Metaverso[n]es una hermosa imagen.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm... Quiz茨 yo tambi姻n deber胤a...[n][w][e]
[s]Mm, mejor no.[n][w][e]

[msg DRESSTALK_SWIM_PC01_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Llevas puesto un ba隠ador?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No tienes fr胤o? Vas a resfriarte.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espera. 夷Por qu姻 llevas puesto[n]un ba隠ador?[n][w][e]

[msg DRESSTALK_SWIM_PC01_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Ese es tu ba隠ador?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya se ha acabado el verano, no creo[n]que vayamos a nadar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No tengo ning雨n problema, pero no[n]vayas a resfriarte ahora.[n][w][e]

[msg DRESSTALK_SWIM_PC01_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, oye... Un momento...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 llevas puesto tu ba隠ador?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es un episodio para dar el gusto[n]a los fans? 夷Un d胤a especial?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷A qui姻n quieres complacer?[n][w][e]

[msg DRESSTALK_SWIM_PC01_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Ese es... tu ba隠ador?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, mientras puedas luchar...[n]Aunque distrae un poco.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]D姻jate de tonter胤as.[n][w][e]

[msg DRESSTALK_SWIM_PC01_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷J-Joker?![n]夷Por qu姻 vas en ba隠ador?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te queda bien, pero no creo[n]que sea el momento...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Tienes pensado luchar as胤?[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC01_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eso no se pone para ir a dormir?[n]Vale que es c吋modo,[n]pero 夷vas a poder luchar as胤?[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC01__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda,[n]夷llevas ropa de andar por casa?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, vamos a dormir.[n][w][e]
[s]...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Pero no hemos venido a hacer eso![n]斡夷Por qu姻 te has puesto esa ropa?![n][w][e]

[msg DRESSTALK_ROOMWEAR_PC01__3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, Joker... 夷Llevas ropa[n]de andar por casa?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El dise隠o es simple. Parece[n]divertido. Puede que yo[n]tambi姻n me cambie.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷En qu姻 estoy pensando? 夷De verdad?[n]夷Con eso puesto vas a robar?[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC01__4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷eso llevas[n]para estar por casa?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Visto as胤 cuando dibujo, pero[n]me parece demasiado informal[n]para este sitio.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque ahora que lo pienso...[n]夷Llevas eso para calmarte?[n]Impresionante.[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC01__5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Jo-Joker, 夷vas en ropa de casa?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S姻 que quieres relajarte, pero...[n]Deber胤as pensar en nuestra imagen.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque por otra parte, luchar胤as[n]mejor relajado. Mmm...[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC01__6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷llevas ropa[n]de andar por casa?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta el color,[n]negro como el caf姻.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No pega mucho con lo que hacemos,[n]pero por m胤 bien[n]si as胤 te mueves mejor.[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC01__7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hala! Joker,[n]夷llevas ropa de andar por casa?[n][w][e]
[s]斡Me gusta! Con esa ropa[n]podr茨s relajarte y sacar[n]todo tu potencial.[n][w][e]
[s]Pero... ten cuidado.[n]Queen parece un poco molesta.[n]De hecho, mejor no te pongas eso.[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC01__8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, esa ropa[n]es la de andar por casa, 夷verdad?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puedes llevar lo que quieras,[n]pero no creo que eso sea[n]apropiado para el sitio.[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC01__9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷vas con ropa[n]de andar por casa?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Suelo llevar ropa c吋moda[n]como esa cuando estiro.[n]Me ayuda a relajarme m茨s.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]*risita* Qu姻 suerte,[n]he visto otra faceta tuya.[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, te has cambiado de traje.[n][w][e]
[s]夷El uniforme del Gekkoukan?[n]Ah, s胤, el instituto de Odaiba.[n][w][e]
[s]No est茨 mal, y lleva un brazalete...[n]夷S.E.E.S? 夷Qu姻 narices es eso?[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC01_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este uniforme es[n]diferente, 夷no, Joker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷El Instituto Gekkoukan?[n]Qu姻 nombre tan peculiar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Te queda muy guay![n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC01_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]C吋mo mola ese uniforme,[n]夷verdad, Joker?[n][w][e]
[s]Los colores no son muy estridentes,[n]y el brazalete tiene estilo.[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC01_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado de uniforme.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es... del Instituto Gekkoukan, 夷no?[n]Est茨 muy bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El emblema y la banda son muy[n]interesantes, pero 夷qu姻 significan[n]los pines verdes y amarillos?[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC01_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Te has cambiado, Joker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es el uniforme del Gekkoukan?[n]Tuvo una presidenta del consejo[n]estudiantil muy famosa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es lista, talentosa y guapa,[n]adem茨s de ser la heredera[n]de una compa隠胤a de prestigio.[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC01_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No es el uniforme del Gekkoukan?[n]Ese instituto tan famoso que est茨[n]junto al mar, en Odaiba.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los alumnos van al centro en[n]monorra胤l. Me encantar胤a ir a clase[n]mientras contemplo el oc姻ano.[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC01_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, Joker, te has cambiado.[n][w][e]
[s]Ah, 夷el Instituto Gekkoukan, no?[n]Es conocido por estar en Odaiba.[n]He o胤do hablar de ellos.[n][w][e]
[s]夷Y esa arma?[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC01_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Te has cambiado, Joker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el uniforme del Gekkoukan. Tiene[n]mucha historia, y fue levantado por[n]las mayores compa隠胤as del mundo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Y esa arma de tu cintura?[n]Nunca hab胤a visto nada igual.[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC01_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, Joker, te has cambiado de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Creo que es el uniforme del[n]Gekkoukan. Invierten mucho esfuerzo[n]en los clubes deportivos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es conocido por sus equipos[n]de kendo, atletismo y nataci吋n,[n]y los femeninos de tenis y v吋ley.[n][w][e]

[msg DRESSTALK_YASOGAMI_PC01_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Qu姻 uniforme tan bonito, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]T胤o, ese es el uniforme perfecto[n]para hombres. El nuestro[n]no est茨 mal, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De qu姻 instituto es ese?[n]Te pareces a uno de esos capos.[n][w][e]

[msg DRESSTALK_YASOGAMI_PC01__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Maestro, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ese tipo de uniforme se llama[n]或gakuran位, 夷no? Te queda[n]como un guante, Joker.[n][w][e]
[s]...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻? 夷He dicho algo raro?[n][w][e]

[msg DRESSTALK_YASOGAMI_PC01__3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, Joker, 夷ese qu姻 uniforme es?[n][w][e]
[s]夷Del Instituto Yasogami?[n]Nunca lo hab胤a escuchado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Todo te queda bien, Joker.[n]Eres como un...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Maestro de la moda.[n][w][e]

[msg DRESSTALK_YASOGAMI_PC01__4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ese uniforme tiene un estilo[n]antiguo, pero te queda bien[n]abierto y con el cuello vuelto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡斡斡Es supermoderno!!![n][w][e]

[msg DRESSTALK_YASOGAMI_PC01__5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ese uniforme te queda bien.[n][w][e]
[s]Aunque me gustar胤a[n]que te abrochases los botones...[n][w][e]

[msg DRESSTALK_YASOGAMI_PC01__6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado de traje, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es un uniforme del Instituto[n]Yasogami? No los suelo ver mucho,[n]pero a ti te queda muy bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 ser茨? Por alg雨n motivo,[n]te he imaginado vestido de chica.[n]斡Ay! Perdona que diga cosas raras.[n][w][e]

[msg DRESSTALK_YASOGAMI_PC01__7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷E-es eso un 或gakuran位?! Solo[n]se los dan a un n雨mero limitado[n]de jugadores de juegos en l胤nea.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pensaba que ese uniforme formaba[n]parte de los mitos. Pero te[n]queda bien. Desprendes poder胤o.[n][w][e]

[msg DRESSTALK_YASOGAMI_PC01__8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Te has cambiado, Joker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un uniforme del Instituto[n]Yasogami, 夷no? Es el que antes[n]usaba el Pr胤ncipe Detective.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]畏l fue quien llev吋 el caso del[n]misterioso asesinato en una ciudad[n]cubierta de una espesa niebla.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tenemos que asegurarnos de que[n]no nos quedamos atr茨s.[n][w][e]

[msg DRESSTALK_YASOGAMI_PC01__9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Te queda muy bien![n]斡Pareces un rebelde![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, y tus gafas son distintas, 夷no?[n]Pero te quedan igual de bien.[n]Je, je.[n][w][e]

[msg DRESSTALK_HERMELIN_PC01_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, Joker, ahora llevas otra ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca hab胤a visto ese uniforme.[n]夷De d吋nde es?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pone... 或Instituto St. Hermelin位.[n]斡Hala, suena guay![n][w][e]

[msg DRESSTALK_HERMELIN_PC01__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es muy diferente al del Shujin.[n]Te queda muy bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷D吋nde est茨 mi uniforme?[n][w][e]

[msg DRESSTALK_HERMELIN_PC01__3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado de traje, Joker.[n][w][e]
[s]Nunca hab胤a visto ese uniforme,[n]pero sus colores sencillos le dan[n]un aire innovador y refrescante.[n][w][e]

[msg DRESSTALK_HERMELIN_PC01__4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has cambiado de ropa, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un uniforme del Instituto[n]St. Hermelin? Mmm... L茨stima,[n]no me suena.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pues me gusta el dise隠o. El verde[n]oscuro realza el escudo.[n][w][e]

[msg DRESSTALK_HERMELIN_PC01__5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Veo que te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷El uniforme del Instituto[n]St. Hermelin? Primera vez[n]que lo oigo.[n][w][e]

[msg DRESSTALK_HERMELIN_PC01__6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Intentas algo diferente?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es del Instituto St. Hermelin?[n]Nunca hab胤a o胤do hablar de 姻l.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷或Hermelin位 no significa armi隠o[n]en franc姻s?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Lo del escudo es un armi隠o?[n][w][e]

[msg DRESSTALK_HERMELIN_PC01__7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, un atuendo diferente, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷St. Hermelin? Ni idea. No se me[n]dan muy bien los nombres.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te queda bien. 斡Me gusta![n][w][e]

[msg DRESSTALK_HERMELIN_PC01__8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷El uniforme de St. Hermelin?[n]Mm, nunca lo hab胤a escuchado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Suelo verte vestido de negro,[n]pero los colores p茨lidos tambi姻n[n]te sientan bien. Qu姻 envidia.[n][w][e]

[msg DRESSTALK_HERMELIN_PC01__9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, te has cambiado de uniforme.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷St. Hermelin? No, no me suena...[n]Qu姻 nombre tan peculiar.[n]Si lo hubiera o胤do, lo recordar胤a.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 斡creo que te queda muy bien![n]El dise隠o sencillo evoca emociones[n]fuertes, 夷sabes?[n][w][e]

[msg DRESSTALK_SEVENS_PC01_PC [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷El Instituto Seven Sisters?[n]No lo hab胤a escuchado nunca.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 斡mola que no veas! Tiene[n]estilo y un toque salvaje a la vez.[n][w][e]

[msg DRESSTALK_SEVENS_PC01_PC_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No tiene nada que ver[n]con el uniforme del Shujin.[n]Pero el negro te sienta bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora vamos conjuntados.[n][w][e]

[msg DRESSTALK_SEVENS_PC01_PC_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado de traje, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es del Instituto Seven Sisters?[n]斡Pareces muy maduro con el[n]uniforme blanco y negro![n][w][e]

[msg DRESSTALK_SEVENS_PC01_PC_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷El Instituto Seven Sisters?[n]No lo hab胤a escuchado nunca.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El dise隠o es incre胤ble. El blanco[n]y el negro parecen representar[n]los conceptos de pecado y castigo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 夷qu姻 digo? No me hagas caso.[n][w][e]

[msg DRESSTALK_SEVENS_PC01_PC_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Veo que te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es un uniforme[n]del Instituto Seven Sisters?[n]No lo conozco, pero te queda bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷La peque隠a estrella en el pecho[n]representa a las siete hermanas?[n][w][e]

[msg DRESSTALK_SEVENS_PC01_PC_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado de traje, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es de un instituto llamado[n]Seven Sisters? Es un nombre[n]poco com雨n. No me suena de nada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El dise隠o del cuello est茨 muy bien.[n]夷El uniforme de las chicas[n]ser茨 igual?[n][w][e]

[msg DRESSTALK_SEVENS_PC01_PC_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, un atuendo diferente, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷El Instituto Seven Sisters?[n]Ni idea, pero el uniforme mola.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La corbata te sienta bien, pero[n]a m胤 no me va. Me obsesionar胤a[n]pensar que podr胤a estrangularme.[n][w][e]

[msg DRESSTALK_SEVENS_PC01_PC_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, Joker, ahora llevas otra ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el uniforme del Instituto Seven[n]Sisters, 夷no? Me han hablado de 姻l.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te sienta bien, pero[n]夷por qu姻 te lo pones?[n]夷Te vas a cambiar de instituto?[n][w][e]

[msg DRESSTALK_SEVENS_PC01_PC_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, te has cambiado de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un uniforme del Seven Sisters?[n]No, no lo hab胤a o胤do nunca.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Qu姻 bien te queda[n]ese negro, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siempre he tenido curiosidad.[n]Joker, 夷te gusta el negro?[n][w][e]

[msg DRESSTALK_CATHERINE_PC01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca te hab胤a visto as胤.[n]Me parece a m胤 que el rosa[n]no te queda muy bien, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y menudas ojeras...[n]夷Est茨s durmiendo bien?[n][w][e]

[msg DRESSTALK_CATHERINE_PC01_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Llevas ropa informal?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No estoy acostumbrado a verte as胤...[n]Ni siquiera sab胤a[n]que ten胤as ese tipo de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻? 夷Que parezco una oveja?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Qu姻 dices?! 斡Soy un gato![n]斡O sea, no soy un gato![n][w][e]

[msg DRESSTALK_CATHERINE_PC01_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esa ropa es muy de adulto.[n]Te queda bien, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Tambi姻n se te ve indeciso![n][w][e]

[msg DRESSTALK_CATHERINE_PC01_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷esa es tu ropa informal?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Podr胤a ser por la ropa, pero...[n]pareces cansado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No duermes bien 雨ltimamente?[n]夷Tienes pesadillas?[n][w][e]

[msg DRESSTALK_CATHERINE_PC01_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya, qu姻 raro verte vestido as胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No es que te quede mal ni nada[n]de eso... Pero es que no te pega.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Me escondes algo?[n]夷Est茨n yendo a bares?[n][w][e]

[msg DRESSTALK_CATHERINE_PC01_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷esa es tu ropa informal?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No inspiras confianza... Es solo[n]mi opini吋n, claro, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Te pasa algo?[n]夷Ya est茨s con alg雨n lio de faldas?[n][w][e]

[msg DRESSTALK_CATHERINE_PC01_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm... Tienes una pinta sospechosa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pareces un extranjero[n]con un aire despreocupado.[n][w][e]

[msg DRESSTALK_CATHERINE_PC01_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Te has cambiado de ropa?[n][w][e]
[s]Sonar茨 borde, pero esa ropa[n]no parece adecuada para un ladr吋n.[n]M茨s bien para holgazanear.[n][w][e]
[s]Hasta tienes ojeras...[n]夷Est茨s durmiendo lo suficiente?[n][w][e]

[msg DRESSTALK_CATHERINE_PC01_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, te has cambiado de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No s姻 muy bien c吋mo decirlo, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Con eso puesto no inspiras[n]mucha confianza. Ten cuidado.[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ese uniforme es azul oscuro.[n]夷Es de otro instituto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los cascos son muy chulos,[n]pero 夷y eso que tienes en la mano?[n]夷Es alg雨n tipo de artefacto?[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Madre, Joker! 夷Y esos cascos?[n][w][e]
[s]Me gustan los colores vivos.[n]斡Es muy bonito! Eh... 夷Es un uniforme[n]del Instituto Karukozaka?[n][w][e]
[s]Pero con ese aspecto no eres[n]un Ladr吋n Fantasma ni nada.[n]Tenlo en cuenta, Joker.[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Caray, Joker! 斡Est茨s divino![n][w][e]
[s]La chaqueta combina bien con[n]el verde y el azul del pantal吋n.[n]Te doy puntos extra por los cascos. [n][w][e]
[s]Es algo anticuado, pero te queda[n]muy bien, Joker. 斡Muy bonito![n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De d吋nde es ese uniforme, Joker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Del Instituto Karukozaka?[n]No lo hab胤a escuchado antes.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eso s胤, el dise隠o y los colores[n]son geniales. Se nota[n]la dedicaci吋n del dise隠ador.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los pantalones son muy coloridos.[n]Es sencillamente impresionante.[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, Joker. 夷Ese no es el uniforme[n]del Instituto Karukozaka?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El azul llama la atenci吋n. Se ve[n]a simple vista que es del[n]Instituto Karukozaka.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No van contra las normas[n]del centro, pero 夷no se te cansa[n]el cuello con esos cascos?[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, no llevas el uniforme[n]habitual.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es del Instituto Karukozaka?[n]夷Est茨 cerca del nuestro?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta el color[n]de los pantalones.[n]夷Se deste隠ir茨n en la lavadora?[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta el azul de esa ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Cu茨les son las especificaciones[n]de los cascos? 夷Te busco[n]unos mejores?[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, Joker, qu姻 ropa tan inusual.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Del Instituto Karukozaka?[n]No lo hab胤a escuchado antes.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta el dise隠o, pero llama[n]mucho la atenci吋n. Como detective,[n]no me ser胤a de mucha ayuda.[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Qu姻 atuendo tan colorido, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Que es del Instituto Karukozaka?[n]No lo hab胤a escuchado antes.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Para qu姻 sirve la m茨quina de[n]tu mano izquierda? 夷Y los cascos?[n][w][e]

[msg DRESSTALK_BUTLER_PC01_PC [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷y ese traje?[n]夷Ahora eres un mayordomo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pues te tendr姻 que pedir algo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Vale! 斡Ve a comprarme pan![n]Un momento. 夷As胤 es como se hace?[n][w][e]

[msg DRESSTALK_BUTLER_PC01_PC_2 [Morgana]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Vas vestido de mayordomo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Genial, iba a pedir algo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Primero, 斡quiero sushi! Ah, espera.[n]Solo ser胤a cuesti吋n de pedirlo.[n][w][e]

[msg DRESSTALK_BUTLER_PC01_PC_3 [Ann]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 斡qu姻 bien te queda[n]el traje de mayordomo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La de cosas que te podr胤a pedir...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya s姻. 斡Ve a comprarme un crepe![n]斡Y que lleve doble de nata[n]y sirope de chocolate![n][w][e]

[msg DRESSTALK_BUTLER_PC01_PC_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Mm? Vas vestido de mayordomo...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Entonces, quiero pedirte algo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiero que vengas conmigo a ver[n]las ofertas del supermercado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El descuento del 50 % en tofu[n]est茨 limitado a 3 por cliente,[n]pero si te unes a m胤, tendremos 6.[n][w][e]

[msg DRESSTALK_BUTLER_PC01_PC_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, si eres un mayordomo.[n]夷Qu姻 te puedo pedir que hagas?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm, a ver. Ve a comprarme todos[n]los libros de referencia[n]a la tienda escolar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]*risita* Es broma. De todas formas,[n]conozco casi todas las respuestas.[n][w][e]

[msg DRESSTALK_BUTLER_PC01_PC_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷vas vestido de mayordomo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es interesante verte as胤.[n]夷Atender茨s mi petici吋n?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hazme caf姻. Aunque supongo[n]que en el Leblanc haces lo mismo.[n][w][e]

[msg DRESSTALK_BUTLER_PC01_PC_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eres un mayordomo?[n]夷Te van esos temas?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, da igual.[n]斡Ah, voy a pedirte algo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Juega conmigo y si ganas,[n]te libero![n][w][e]

[msg DRESSTALK_BUTLER_PC01_PC_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker.[n]Vas vestido de mayordomo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya que eres mayordomo,[n]tendr姻 que pedirte algo... Es broma.[n][w][e]

[msg DRESSTALK_BUTLER_PC01_PC_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 斡te has cambiado de ropa![n]夷Ahora eres... mayordomo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm... Si eres un mayordomo,[n]夷vas a escuchar mis peticiones?[n][w][e]

[msg DRESSTALK_CHRIST_PC01_PC [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Feliz Navidad! Oye,[n]夷no es un poco pronto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pap茨 Noel, 夷eh? 夷Qu姻 podr胤a pedir?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Supongo que algo para hacer[n]musculaci吋n estar胤a bien.[n][w][e]

[msg DRESSTALK_CHRIST_PC01_PC_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Feliz Navidad! Oye...[n]Todav胤a queda para eso.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un traje de Pap茨 Noel, 夷no?[n]Mm, 夷qu姻 te pido?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Vale! 斡Voy a pedir sushi![n]斡Y que sea del bueno![n][e]

[msg DRESSTALK_CHRIST_PC01_PC_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Feliz Navidad![n]Aunque todav胤a queda.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, ya que vas de Pap茨 Noel...[n]A ver, 夷qu姻 te pido?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm... Creo que quiero un juego.[n]De todas formas acabar胤a jugando.[n][w][e]

[msg DRESSTALK_CHRIST_PC01_PC_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un disfraz de Pap茨 Noel, 夷eh?[n]夷No te has adelantado un poco?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 podr胤a pedir?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm. 夷Materiales de pintura?[n]No. 夷Dinero para el transporte?[n][w][e]

[msg DRESSTALK_CHRIST_PC01_PC_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un traje de Pap茨 Noel?[n]夷Ya es la 姻poca?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 pido este a隠o? Puede que[n]unos guantes para la moto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiero empezar a montar en moto[n]cuando empiece la universidad.[n][w][e]

[msg DRESSTALK_CHRIST_PC01_PC_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻? 夷Un traje de Pap茨 Noel?[n]夷Qu姻 podr胤a pedirte?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiz茨 pida plantas ex吋ticas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No deber胤a resultarte dif胤cil,[n]Pap茨 Noel. Total, t雨 vuelas[n]por todo el mundo, 夷no?[n][w][e]

[msg DRESSTALK_CHRIST_PC01_PC_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Llevas un disfraz de Pap茨 Noel?[n]夷Ya ha llegado la 姻poca?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 pido este a隠o?[n]Ah, quiero piezas de ordenador.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora que lo pienso... Me gustar胤a[n]poder elegirlas yo, as胤 que no.[n][w][e]

[msg DRESSTALK_CHRIST_PC01_PC_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un traje de Pap茨 Noel?[n]夷Qu姻 mosca te ha picado, Joker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Supongo que dejarse llevar[n]tambi姻n es importante.[n]夷Vas a preguntarme qu姻 quiero?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm... Pues entonces...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiero seguir compitiendo contigo.[n][w][e]

[msg DRESSTALK_CHRIST_PC01_PC_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷llevas un disfraz[n]de Pap茨 Noel?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero si ya ha pasado la Navidad.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ah! 夷Si te lo pido ahora, podr茨s[n]conseguir lo que quiero[n]para la pr吋xima Navidad?[n][w][e]

[msg DRESSTALK_DANCE_PC01_PC0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Oye, vas vestido para bailar![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qu姻 pinta de granuja.[n]斡Luchar con ritmo suena divertido![n][w][e]

[msg DRESSTALK_DANCE_PC01_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hala! 斡Me encanta[n]tu ropa para bailar![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Qu姻 bien te queda, Joker![n]斡Tiene cierto rollo[n]a Ladr吋n Fantasma![n][w][e]

[msg DRESSTALK_DANCE_PC01_PC0_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eso te pones para bailar?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Con la bufanda roja y las gafas[n]se te ve lleno de energ胤a.[n]斡Pareces un artista profesional![n][w][e]

[msg DRESSTALK_DANCE_PC01_PC0_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, 夷eso te pones para bailar?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dicen que una imagen poderosa[n]se parece al baile. Me cambiar姻[n]tambi姻n para conseguir inspiraci吋n.[n][w][e]

[msg DRESSTALK_DANCE_PC01_PC0_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, vas vestido para bailar![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Viene bien para moverse. Quiz茨[n]no sea mala idea para este trabajo...[n]A lo mejor yo tambi姻n me cambio.[n][w][e]

[msg DRESSTALK_DANCE_PC01_PC0_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷esa es tu ropa de baile?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La estrella destaca mucho.[n]斡Seguro que esa ropa viene bien[n]para canciones alegres y r茨pidas![n][w][e]

[msg DRESSTALK_DANCE_PC01_PC0_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hala! 斡夷Esa es tu ropa de baile?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que eso se pone la gente[n]en las fiestas para partir la pana...[n]Es algo que nunca vivir姻...[n][w][e]

[msg DRESSTALK_DANCE_PC01_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es tu ropa para bailar?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ver, te queda bien, pero...[n]夷pega con lo que estamos haciendo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, no perder姻 ni en un concurso[n]de baile. Hasta los detectives[n]deben saber bailar con elegancia.[n][w][e]

[msg DRESSTALK_DANCE_PC01_PC1 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, esa ropa...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ah! 夷Eso te pones para bailar?[n]斡No me extra隠a que parezca[n]tan c吋modo para moverse![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siempre he pensado que te iba[n]la moda m茨s sofisticada, pero[n]la ropa informal te queda bien.[n][w][e]

[msg DRESSTALK_SHADOW_W_PC01_ [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eh! 斡夷Qu姻 llevas puesto?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Equipo... sombra? 夷Es para una[n]fiesta o algo as胤?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Tambi姻n luchan contra las sombras?[n]斡Joder, el traje es una pasada![n]Parece de guardia de seguridad. [n][w][e]

[msg DRESSTALK_SHADOW_W_PC01__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hala, Joker! 夷Y ese traje?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es el uniforme de unas fuerzas[n]especiales que tambi姻n[n]derrotan sombras? 斡Mola![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero... Ese esmoquin y esa m茨scara...[n]No tendr茨s rosas, 夷no?[n][w][e]

[msg DRESSTALK_SHADOW_W_PC01__3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Qu姻?! 斡Pero 夷qu姻 ropa es esa?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Equipo... sombra? No tengo ni idea[n]de qu姻 es eso.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero tiene pinta de ser resistente.[n]斡Hace que parezcas[n]un guardaespaldas de confianza![n][w][e]

[msg DRESSTALK_SHADOW_W_PC01__4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker,[n]夷y ese atuendo tan interesante?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Equipo sombra? No s姻 qu姻 es eso,[n]pero me gusta mucho el dise隠o.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es traje y armadura a la vez.[n]夷Cuenta con buenas[n]propiedades defensivas?[n][w][e]

[msg DRESSTALK_SHADOW_W_PC01__5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya ropa tan poco com雨n, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Las fuerzas especiales[n]Equipo sombra? No, nunca[n]he o胤do hablar de ellos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si son fuerzas especiales,[n]puede que guarden relaci吋n con[n]la polic胤a. Le preguntar姻 a Sae.[n][w][e]

[msg DRESSTALK_SHADOW_W_PC01__6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ese traje es rar胤simo, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Las fuerzas especiales[n]Equipo sombra? Mmm, no me suenan[n]de nada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Se trata de un equipo[n]que investiga sombras[n]o que lucha contra ellas?[n][w][e]

[msg DRESSTALK_SHADOW_W_PC01__7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ostras! 斡C吋mo mola, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Equipo sombra? Ni idea.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los he buscado en internet,[n]pero no hay nada sobre ellos.[n]夷Es una organizaci吋n secreta?[n][w][e]

[msg DRESSTALK_SHADOW_W_PC01__8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, Joker. Ese es el traje[n]del Equipo sombra, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sae me dijo que eran un rumor,[n]pero nunca imagin姻[n]que existiesen de verdad.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo he dicho por lo que llevas en el[n]brazo. Pareces un inspector.[n][w][e]

[msg DRESSTALK_SHADOW_W_PC01__9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷qu姻 llevas puesto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Departamento de seguridad,[n]Unidad de respuesta a sombras...?[n]斡Hay m茨s gente en esta lucha![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, creo que te queda bien,[n]pero esa m茨scara parece[n]de una fiesta de disfraces.[n][w][e]

[msg DRESSTALK_SAMURAI_PC01_P [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qu姻 ropa m茨s rara llevas, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, es un traje de samur茨i.[n]斡Te queda muy bien![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es diferente del samur茨i que[n]conozco, 斡pero est茨 bien![n][w][e]

[msg DRESSTALK_SAMURAI_PC01_P_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qu姻 atuendo tan raro, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De samur茨i? No s姻 si es algo que[n]llevar胤a un Ladr吋n Fantasma,[n]pero a ti te queda bien.[n][w][e]

[msg DRESSTALK_SAMURAI_PC01_P_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca hab胤a visto nada igual.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻? 夷Ropa de samur茨i?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te da un toque muy original.[n]斡Parece que acabas de salir[n]de un mundo de fantas胤a![n][w][e]

[msg DRESSTALK_SAMURAI_PC01_P_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya, llevas un atuendo[n]poco com雨n, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un samur茨i? Absurdo. Nunca he[n]visto un samur茨i que vista as胤.[n][w][e]

[msg DRESSTALK_SAMURAI_PC01_P_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷qu姻 llevas puesto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Se supone que eres un samur茨i?[n]Eso no se parece a ning雨n[n]samur茨i que haya visto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]*risita* Pero te queda bien.[n]Pareces un caballero medieval. [n][w][e]

[msg DRESSTALK_SAMURAI_PC01_P_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya, qu姻 traje m茨s interesante,[n]Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es un ropaje de samur茨i?[n]Es diferente a los samur茨is[n]que yo conozco.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷El cintur吋n no es muy del oeste?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sea como sea, pareces muy valeroso.[n]Oh, valiente samur茨i,[n]斡protege a Noir! *risita*[n][w][e]

[msg DRESSTALK_SAMURAI_PC01_P_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡El 雨ltimo ninja![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? 夷Es un traje de samur茨i?[n]夷Vas a usar alguna t姻cnica[n]de ninjutsu molona?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Seguro que vas de samur茨i?[n]夷Y ese cintur吋n? 夷D吋nde tienes[n]la espada? 夷Y las estrellas ninja?[n][w][e]

[msg DRESSTALK_SAMURAI_PC01_P_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷qu姻 llevas puesto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un samur茨i? 夷Seguro?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya veo. Es otro tipo de samur茨i.[n]Aun as胤, no te pases[n]con el cosplay.[n][w][e]

[msg DRESSTALK_SAMURAI_PC01_P_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, te has cambiado de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Que esto... es un samur茨i? Mmm...[n]No me lo imaginaba as胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Pero te queda muy bien![n][w][e]

[msg DRESSTALK_RAIDOU_PC01_PC [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, pero 夷qu姻? 斡夷Desde cu茨ndo[n]te gusta tanto leer?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es un uniforme[n]del Instituto imperial Yumizuki?[n]夷Hace cu茨nto se fund吋?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No digo que te quede mal, pero...[n]no entiendo a qu姻 viene tanto tubo.[n][w][e]

[msg DRESSTALK_RAIDOU_PC01_PC_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Veo que te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece antiguo, 斡pero te queda[n]muy bien! Eres como un alumno[n]y un detective a la vez.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pareces un Ladr吋n Fantasma[n]con esa capa. 夷Tienes una para m胤?[n][w][e]

[msg DRESSTALK_RAIDOU_PC01_PC_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A-ah, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ver c吋mo lo digo... Parece algo[n]antiguo que solo se pondr胤a[n]alguien muy estudioso.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ver, te queda bien,[n]pero no querr胤a que me viesen[n]en p雨blico contigo as胤 vestido.[n][w][e]

[msg DRESSTALK_RAIDOU_PC01_PC_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya ropa m茨s extra隠a, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece pasada de moda,[n]pero tambi姻n tiene un toque 雨nico[n]que puede que no volvamos a ver.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me est茨n entrando ganas de dibujar.[n]夷Te importar胤a no moverte[n]durante una hora?[n][w][e]

[msg DRESSTALK_RAIDOU_PC01_PC_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya... traje, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un uniforme del Instituto imperial[n]Yumizuki? Mmm... Creo que[n]no lo hab胤a escuchado antes.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es extra隠o ver un uniforme[n]con capa. 夷Ser茨 una nueva moda?[n][w][e]

[msg DRESSTALK_RAIDOU_PC01_PC_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hala, qu姻 uniforme m茨s peculiar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que es un uniforme[n]del Instituto imperial Yumizuki.[n]夷Cu茨ntos a隠os tendr茨 ese instituto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es mi opini吋n y quiz茨 suene borde,[n]pero solo de verlo me est茨 entrando[n]antojo de boniato.[n][w][e]

[msg DRESSTALK_RAIDOU_PC01_PC_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Y ese traje, Joker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uf... 夷Qu姻 premios hab胤a[n]con los anuarios?[n]Lo tengo en la punta de la lengua...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ah! 斡Ya me acuerdo![n]斡Estaba el premio al mejor vestido![n][w][e]

[msg DRESSTALK_RAIDOU_PC01_PC_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, qu姻 uniforme tan raro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷El Instituto imperial Yumizuki?[n]Ni idea. 夷Es un instituto[n]de otra 姻poca?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esa espada y esa pistola tambi姻n[n]molan mucho, pero te arrestar胤an[n]si las llevaras en la realidad.[n][w][e]

[msg DRESSTALK_RAIDOU_PC01_PC_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya uniforme tan raro, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca hab胤a visto un uniforme as胤.[n]Me hace sentir nostalgia.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pareces un polic胤a militar[n]m茨s que un estudiante.[n]斡Si hasta llevas espada y pistola![n][w][e]

[msg DRESSTALK_P5Dance_PC01_P [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya, Joker, te has puesto[n]la ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷La chaqueta es la del Shujin?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Cuando lo llevas as胤[n]parece guay y todo![n][w][e]

[msg DRESSTALK_P5Dance_PC01_P_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Veo que vas vestido[n]para bailar, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Me gusta la bufanda roja![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puede que yo tambi姻n cambie[n]el color de mi bufanda.[n][w][e]

[msg DRESSTALK_P5Dance_PC01_P_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷te has puesto la ropa[n]de baile?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dependiendo de c吋mo lo lleves,[n]el uniforme del Shujin puede[n]marcar tendencia.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El rojo de los guantes[n]y de las zapatillas queda muy bien.[n][w][e]

[msg DRESSTALK_P5Dance_PC01_P_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Esa ropa es para bailar? Te pega.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Seguro que esos auriculares no te[n]molestar茨n cuando bailes?[n][w][e]

[msg DRESSTALK_P5Dance_PC01_P_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eso que llevas es para bailar?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eh, pero si es el uniforme del[n]Instituto Shujin![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Procura que el uniforme no parezca[n]demasiado informal. Por cierto,[n]夷puedes bailar con eso puesto?[n][w][e]

[msg DRESSTALK_P5Dance_PC01_P_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, Joker, ahora llevas otra ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es para bailar? 斡Te queda genial![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta el toque de los guantes[n]rojos. Son dignos[n]de un Ladr吋n Fantasma.[n][w][e]

[msg DRESSTALK_P5Dance_PC01_P_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Qu姻 ropa de baile tan chula![n]Te queda muy bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los cascos tambi姻n est茨n muy bien.[n]La m雨sica es indispensable[n]para bailar.[n][w][e]

[msg DRESSTALK_P5Dance_PC01_P_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Veo que te has puesto[n]la ropa de baile, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 no organizamos una[n]competici吋n de baile?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Era broma. No tengo mucha[n]experiencia bailando.[n][w][e]

[msg DRESSTALK_P5Dance_PC01_P_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, te has cambiado de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Llevas ropa de baile?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora que lo pienso, en el festival[n]escolar acab姻 bailando, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si vas as胤 vestido,[n]puede que te pida bailar y todo...[n]Je, je. 斡Es broma![n][w][e]

[msg DRESSTALK_P3Dance_PC01_P [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_P3Dance_PC01_P_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_P3Dance_PC01_P_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_P3Dance_PC01_P_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_P3Dance_PC01_P_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_P3Dance_PC01_P_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_P3Dance_PC01_P_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_P3Dance_PC01_P_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_P3Dance_PC01_P_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_velvetroom_PC0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ahora eres botones?[n]夷Por qu姻 tienes un traje as胤?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero t胤o, 斡mola que te cagas![n][w][e]

[msg DRESSTALK_velvetroom_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 夷esto qu姻 es?[n]Un uniforme, 夷verdad?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta el tono azulado.[n]Me relaja mirarlo.[n][w][e]

[msg DRESSTALK_velvetroom_PC0_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eso es... un uniforme de botones?[n]Es, mm... peculiar.[n][w][e]

[msg DRESSTALK_velvetroom_PC0_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Veo que te has cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tiene un todo de azul exquisito.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mis disculpas. Me hab胤a quedado[n]absorto mirando el color.[n]Me gustar胤a usarlo en alguna obra.[n][w][e]

[msg DRESSTALK_velvetroom_PC0_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un uniforme de botones?[n]Te queda bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 夷por qu姻 vas vestido as胤?[n]Adem茨s, es un color un poco[n]extra隠o para ese tipo de uniforme.[n][w][e]

[msg DRESSTALK_velvetroom_PC0_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ahora eres un botones, Joker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca hab胤a visto un uniforme as胤,[n]pero tiene un azul precioso.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es de un hotel conocido?[n][w][e]

[msg DRESSTALK_velvetroom_PC0_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vaya... Llevas un traje de botones.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Guay, nunca hab胤a visto nada igual.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 夷es ese el color[n]de un uniforme de botones? Nunca[n]hab胤a visto ninguno azul.[n][w][e]

[msg DRESSTALK_velvetroom_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, 夷te has cambiado?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qu姻 uniforme de botones tan bonito.[n]夷Has empezado en un nuevo trabajo?[n][w][e]

[msg DRESSTALK_velvetroom_PC0_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, te has cambiado de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eso es un uniforme de botones?[n]Vaya, es bastante peculiar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es algo distinto a lo que te sueles[n]poner, pero el azul[n]te queda muy bien.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Anda! 斡Eres Neo Featherman![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Era superfan cuando era peque隠o![n]斡Son mis h姻roes de infancia![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Yo voy de rojo, 夷no?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Pero si t雨 ya vas de rojo![n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hala, qu姻 traje tan chulo, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pareces m茨s un h姻roe que un Ladr吋n,[n]斡pero te queda tan bien que[n]puedo ignorarlo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡No puedes hacer justicia[n]sin el atuendo adecuado![n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eres t雨, 夷no, Joker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Neo Featherman, 夷no?[n]夷D吋nde lo has conseguido?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm... Pues no te queda mal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero no te lo pongas cuando[n]salgamos... Nunca.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Menudo traje, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Est茨s haciendo cosplay de una de[n]las figuras que tiene Futaba[n]en su habitaci吋n?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pens茨ndolo bien, no est茨 tan mal.[n]Jam茨s pens姻 que tendr胤a[n]este aspecto.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has cambiado, 夷Jo... ker?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los Featherman... S胤, los conozco.[n]Mi padre me llevaba a sus[n]actuaciones cuando era ni隠a.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece el traje real.[n]夷De qu姻 material est茨 hecho?[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, 夷no es Neo Featherman?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]*risita* Me sorprende que disfrutes[n]con estas cosas, Joker. Ve胤a[n]la serie cuando era peque隠a.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero entiendo que quieras sentirte[n]como un h姻roe. Las hero胤nas[n]que se transforman me fascinan.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Halaaa! 斡Joder, es Neo Featherman![n]斡斡斡C吋mo mola!!![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Tu estilo raya la perfecci吋n! Yo,[n]la mayor fan de los Featherman[n]del equipo, apruebo el traje.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale, voy a volver a verme[n]Featherman.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker. Eso es de Phoenix[n]Ranger Neo Featherman, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Son h姻roes admirados por los ni隠os,[n]y a pesar de su edad, la serie[n]sigue siendo muy popular.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero deber胤as dejar de hacer[n]cosplay, ya no eres un cr胤o.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Eh?! 斡夷Qui姻n eres?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, eres t雨, Joker.[n]Qu姻 sorpresa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Neo Featherman? Lo siento,[n]no tengo ni idea.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Pero creo que te queda muy bien![n][w][e]

[msg DRESSTALK_DEMONICA_MASKE [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Oye, 夷qui姻n eres t雨?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, eres Joker. 夷Qu姻 llevas puesto?[n]夷Eso es un casco?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El dorado queda raro.[n]Parece m茨s un cubo que un casco.[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Qu姻?! 斡夷Qui姻n eres?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, eres t雨, Joker.[n]No me des esos sustos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 斡ese cubo mola mucho![n]斡Seguro que puedes usarlo de casco![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻? 夷Que es al rev姻s?[n]夷Qu姻 quieres decir?[n][e]

[msg DRESSTALK_DEMONICA_MASKE_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Joker? Si no fuera por tu voz,[n]no me lo creer胤a...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un casco, 夷no? Es imposible[n]saber qui姻n eres con eso puesto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es... mmm... singular.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]N-no, para nada pienso que sea[n]un simple cubo dorado.[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm... Qu姻 casco tan raro...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No s姻 qu姻 tipo de motivo[n]se supone que lleva. A m胤[n]me parece un simple cubo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Creo que te queda perfecto, Skull.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Mm? Pero si Skull est茨 all胤.[n]斡夷Joker?![n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻...? 斡夷Qui姻n eres?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ay, Joker... No me des esos sustos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cre胤a que hab胤a aparecido[n]un fantasma con un cubo... Al menos[n]qu胤tatelo en la Habitaci吋n segura.[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm... eres Joker, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Menos mal que he acertado.[n]夷Qu姻 ha pasado? 夷Por qu姻[n]llevas un cubo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Qu姻?! 夷Que no es un cubo?[n]Pero... si parece uno.[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hala! 斡Es alucinante![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷verdad? No te hab胤a[n]reconocido con ese casco.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El tubo que tienes cerca[n]de la boca es para respirar, 夷no?[n]夷Y por qu姻 no hace 或pssssh位?[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷por qu姻 llevas[n]un traje Demonica?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Que c吋mo he sabido que eras t雨?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo sab胤a por tu vestimenta, claro.[n]Est茨 hecha a medida.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque a m胤 tambi姻n me gustar胤a[n]poder cambiar la forma del casco...[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eres J-Joker... 夷No?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es imposible saber[n]qui姻n eres con ese casco puesto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De verdad te resulta c吋modo?[n]A m胤 me parece un simple cubo.[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, ese es el traje Demonica, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece ropa militar o algo as胤...[n]Aunque no lo tengo muy claro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A lo mejor lo sabe el t胤o de la[n]tienda de airsoft.[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker.[n]Llevas un traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Supongo que es obvio, pero[n]al ser un traje militar[n]puedes equiparlo con varias cosas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puede que pese un poco,[n]pero igual hasta puedes ponerle[n]herramientas de infiltraci吋n.[n][e]

[msg DRESSTALK_DEMONICA_UNMAS_3 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker, te has cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, eso parece que pesa. 夷Seguro[n]que podr茨s luchar con eso puesto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es probable que sea demasiado[n]para ti solo... 斡Esperemos[n]que alguien se ofrezca a ayudarte![n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_4 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, te has puesto[n]un traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece resistente. Supongo que es[n]porque est茨 hecho para el combate.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 es eso dorado de tu espalda?[n]夷Para qu姻 sirve?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La verdad es que parece dif胤cil[n]combatir con eso.[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_5 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker.[n]Llevas un traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Sab胤as que aunque los trajes[n]sean iguales se puede saber[n]de qui姻nes son si te fijas bien?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El color de la manga de cada traje[n]es diferente. El tuyo es blanco.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sabiendo eso, podemos saber[n]qui姻n eres hasta cuando lleves[n]el cub... Digo, el casco.[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_6 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, llevas... un traje Demonica, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ese traje parece muy 雨til. Se ve[n]que le puedes poner herramientas.[n]Quiz茨 sirva para la jardiner胤a.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Debo usar palas, cuerdas y m茨s[n]cosas, pero no me caben en los[n]bolsillos de la ropa de deporte.[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_7 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, Joker. Buen traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dicen que puedes instalarle[n]aplicaciones a ese traje.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A saber qu姻 aplicaciones tiene.[n]夷Podr姻 desarrollar yo una?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 puedo instal茨rsela a los trajes[n]de los dem茨s. Ya me dar茨s[n]las gracias. Je, je, je.[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Veo que te has cambiado, Joker.[n]Creo que es el traje Demonica, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por el color y el equipamiento,[n]parece estar hecho para combatir.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Con lo equipado que est茨, podr胤a[n]venir bien en un Palacio.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por cierto, 夷qu姻 es ese tanque que[n]tienes en la espalda? 夷Con eso[n]se puede bucear?[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_9 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, te has cambiado de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ese es el traje Demonica, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puedes llevar muchas m茨s cosas[n]que con el de Ladr吋n Fantasma.[n]Es muy 雨til tener tanto espacio.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero... 夷hac胤a falta el tanque[n]en la espalda?[n][w][e]

[msg DRESSTALK_PQ2_PC01_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Joder, 夷qu姻 le ha pasado[n]a tu cara?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷J-Joker?! Madre m胤a,[n]casi no te reconozco.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 夷qu姻 es eso? 夷Un disfraz[n]de mascota o algo as胤?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Normalmente vas muy guay,[n]pero 斡con esto eres una monada![n][w][e]

[msg DRESSTALK_PQ2_PC01_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eh, 夷qu姻 le pasa a tu cabeza?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 se supone que eres?[n]夷Es un cosplay o algo as胤?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No lo pillo, pero ese traje[n]tiene algo...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que dan ganas de abrazarte.[n][w][e]

[msg DRESSTALK_PQ2_PC01_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Por qu姻 tienes la cabeza[n]tan grande?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Madre m胤a, qu姻 raro est茨s![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, eres t雨, 夷no?[n]夷Es un disfraz? 夷O un producto[n]de los Ladrones Fantasma?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque bien mirado... es una monada.[n][w][e]

[msg DRESSTALK_PQ2_PC01_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷eso qu姻 es?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es un disfraz? La piel est茨[n]muy bien hecha.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aun as胤, es mono.[n]Es asombroso lo mucho[n]que la ropa cambia a una persona.[n][w][e]

[msg DRESSTALK_PQ2_PC01_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷eres t雨?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parec胤a un disfraz, as胤 que[n]no estaba segura de si eras t雨.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La piel parece humana.[n]夷De qu姻 est茨 hecho?[n][w][e]

[msg DRESSTALK_PQ2_PC01_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Madre m胤a, qu姻 adorable![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ay, lo siento. No he podido[n]resistirme. 斡Est茨s muy cuqui![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dan ganas de darte un achuch吋n.[n]*risita* Es que es tan mono...[n][w][e]

[msg DRESSTALK_PQ2_PC01_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷por qu姻 tienes[n]la cabeza tan grande?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A decir verdad,[n]todo lo que llevas es raro.[n]夷Es una forma nueva o qu姻?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cuanto m茨s lo miro,[n]m茨s se me enternece el coraz吋n.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Joker us吋 moner胤a extrema![n]斡Es superefectivo![n][w][e]

[msg DRESSTALK_PQ2_PC01_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷qu姻 llevas puesto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Supongo que es un traje[n]personalizado, pero tienes[n]un aspecto bastante distinto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Puedes ver algo desde ah胤 dentro?[n]夷Joker? 斡Holaaaa![n][w][e]

[msg DRESSTALK_PQ2_PC01_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Eh?! 夷Qu姻 es eso?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷eres t雨?[n]夷Llevas un disfraz?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No s姻 c吋mo decirlo, pero est茨s[n]muy cuqui. 斡Y con cuqui digo[n]que te queda muy bien![n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_10 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi uniforme de verano.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esta ropa me encanta.[n]斡Y es muy el茨stica![n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_10 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira, me he puesto mi[n]uniforme de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Solo me lo he puesto un a隠o,[n]pero el uniforme[n]del Shujin me sienta de lujo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece la camisa amarilla?[n]斡A que mola![n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_10 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Tach茨n! Mira mi ropa informal.[n]Que haga atletismo no significa que[n]solo tenga en forma las piernas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Yo tambi姻n tengo m雨sculos![n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_10 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, mira mi ropa de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Las parkas sirven para todo.[n]Basta con ponerte la capucha[n]si llueve o nieva.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora entiendo por qu姻 Panther[n]siempre lleva eso puesto.[n][w][e]

[msg DRESSTALK_JERSEY_PC02 [Ryuji]]
[s]Eh, mira mi ch茨ndal.[n][w][e]
[s]Me la pongo para entrenar[n]o hacer atletismo,[n]pero 斡es que me queda de muerte![n][w][e]
[s]斡Bueno, me piro a correr![n]夷Qu姻? 夷Que ahora no?[n][w][e]

[msg DRESSTALK_SWIM_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Mira mi ba隠ador![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hace fr胤o, pero con esto puesto[n]estoy a tope.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Cu茨l es el plan? 夷Nos vamos[n]a la piscina?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Quieres que investigue con esto[n]puesto?! 斡夷En serio?![n][w][e]

[msg DRESSTALK_ROOMWEAR_PC02 [Ryuji]]
[s]RESERVE[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira, es el uniforme[n]del Instituto Gekkoukan.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Menudo estilazo, 夷no?[n]Imagina ir a clase al ladito[n]del oc姻ano... Qu姻 envidia.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero me pregunto algo...[n]夷Por qu姻 tengo un rev吋lver[n]en la cintura?[n][w][e]

[msg DRESSTALK_YASOGAMI_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, mira el uniforme del Yasogami.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tronco, me chiflan este tipo[n]de uniformes. 夷No te parecen[n]la leche estas gafas de sol?[n][w][e]

[msg DRESSTALK_HERMELIN_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, mira. El uniforme de[n]St. Hermelin.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es verde claro en su mayor parte,[n]pero no est茨 mal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Te va a sonar raro, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Con esto puesto, me acuerdo de mi[n]pasado. Cuando todo empez吋.[n][w][e]

[msg DRESSTALK_SEVENS_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que este es el uniforme[n]del Seven Sisters.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Al sitio lo llaman 或Sevens位[n]o algo as胤, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En mi cabeza parec胤a pat姻tico,[n]pero mola un poco m茨s[n]al decirlo en voz alta.[n][w][e]

[msg DRESSTALK_CATHERINE_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, he cambiado un poco mi aspecto.[n]Es bastante moderno, 夷a que s胤?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Parezco adulto! Seguro que[n]si fuera as胤 a un bar no[n]sabr胤an qu姻 edad tengo.[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_10 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Estoy probando algo nuevo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el uniforme del Karukozaka.[n]Los pantalones son muy sofisticados[n]para mi gusto, pero no est茨n mal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uf, los cascos me est茨n machacando[n]el cuello. 夷Y para qu姻 narices[n]es la m茨quina de la mano?[n][w][e]

[msg DRESSTALK_BUTLER_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voy vestido de mayordomo...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eso es lo que les va a las chicas[n]ahora? Estoy muy apretado con esto...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, vamos a probar ya que[n]tengo la ropa puesta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Welcome Home, Master![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ughhh, no, ni hablar.[n]Esto no me gusta.[n][w][e]

[msg DRESSTALK_CHRIST_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ropa de Pap茨 Noel, 夷eh?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ver, que te queda bien y eso...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 hace que parezca[n]que estoy robando regalos[n]en vez de reparti姻ndolos?[n][w][e]

[msg DRESSTALK_DANCE_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Mira mi ropa de baile![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Vale, qu姻 ganas![n]斡Venga, Joker, a bailar![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Alumnos de d胤a; de noche, Ladrones.[n]Si ten姻is un Palacio, despertaremos[n]vuestros corazones. 夷Qu姻 te parece?[n][w][e]

[msg DRESSTALK_SHADOW_W_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Llevo el uniforme del[n]Equipo sombra![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me siento como los h姻roes de las[n]pelis con esto puesto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Igual podemos atrapar alien胤genas[n]o cr胤ptidos![n][w][e]

[msg DRESSTALK_SAMURAI_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que as胤 es un traje de samur茨i.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No sab胤a que un samur茨i era as胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 斡el traje mola mucho,[n]as胤 que da igual![n][w][e]

[msg DRESSTALK_RAIDOU_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, Joker, mira mi uniforme.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que es del Instituto imperial[n]Yumizuki. 夷D吋nde queda?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, mientras me quede bien,[n]da igual. 斡Con este uniforme[n]estoy listo para lo que sea![n][w][e]

[msg DRESSTALK_P5Dance_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira mi ropa de baile, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece la bandana?[n]He pillado una con la calavera.[n]Porque soy Skull, 夷lo pillas?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡No est茨 mal, eh![n][w][e]

[msg DRESSTALK_P3Dance_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_velvetroom_PC0_10 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este uniforme es como el que llevan[n]esos tipos de los hoteles, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Creo que es muy guay.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ojal茨 nuestros uniformes[n]fueran as胤. Quiz茨 de ese modo ir胤a[n]a clase con ropa en condiciones.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_10 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Phoenix Ranger Neo Featherman![n]斡Me pido Feather Yellow![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ya ves! 斡C吋mo mola![n]Est茨 en mi top 3 de trajes[n]que quiero llevar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Yo, Skull...! Quiero decir...[n]斡Feather Yellow, derrotar姻[n]a las malvadas sombras! [n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_10 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ey, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este casco es genial. Es[n]resistente, pero aun as胤[n]es muy ligero.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es la hostia. El dorado[n]tambi姻n mola... Parezco[n]el malo de un anime.[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_10 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Mira c吋mo me queda[n]el traje Demonica![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me va que ni pintado, y moverse[n]con 姻l es pan comido.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Y las herramientas doradas?[n]夷C吋mo se usan?[n][w][e]

[msg DRESSTALK_PQ2_PC02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, vale... Me he puesto esta cosa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 le pasa a este disfraz?[n]Me hace sentir... 夷C吋mo se dice?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Me siento m茨s cuqui?[n]Qu姻 verg鵜enza.[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_11 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]秀尽学園制服・夏・モルガナ[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_11 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]秀尽学園制服・冬・モルガナ[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_11 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]私服・夏・モルガナ[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_11 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]私服・冬・モルガナ[n][w][e]

[msg DRESSTALK_JERSEY_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]ジャージ・モルガナ[n][w][e]

[msg DRESSTALK_SWIM_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]水着・モルガナ[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]部屋着・モルガナ[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Cambio de ropa completado![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espera, no es lo que piensas.[n]Me han entrado ganas de hablar as胤[n]por el uniforme, nada m茨s.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me han entrado ganas de repente[n]de matar sombras. 斡夷Qu姻 le[n]pasa a este traje?![n][w][e]

[msg DRESSTALK_YASOGAMI_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por alguna raz吋n, me apetece[n]llamarte 或maestro位.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ser茨 por el atuendo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tengo la sensaci吋n de que[n]se me olvida algo importante.[n][w][e]

[msg DRESSTALK_HERMELIN_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, un traje nuevo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷est茨s herido?[n]Te curar姻 si lo necesitas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eso s胤, no ser茨 gratis.[n]El mundo funciona mediante[n]el toma y daca, 夷verdad?[n][w][e]

[msg DRESSTALK_SEVENS_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Anda, un traje nuevo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷est茨s herido?[n]Te curar姻 si lo necesitas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eso s胤, no ser茨 gratis.[n]El mundo funciona mediante[n]el toma y daca, 夷verdad?[n][w][e]

[msg DRESSTALK_CATHERINE_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Una ovejita... Dos ovejitas...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Je, je, je. Joker, 夷qu姻 te parece[n]mi disfraz de oveja?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Oye, que no soy una oveja![n]斡Voy de gato![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡E-espera, tampoco soy un gato![n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_11 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Joker, mira mi ropa nueva![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece? Me siento[n]hasta m茨s inteligente.[n][w][e]

[msg DRESSTALK_BUTLER_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, Joker, 夷por qu姻 llevo[n]un traje de sirvienta?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No soy una chica.[n][w][e]

[msg DRESSTALK_CHRIST_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Feliz Navidad![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷qu姻 te parece mi traje de[n]Pap茨 Noel? Ahora puedo[n]dar regalos a...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Es co隠a?! 斡Es un mu隠eco de nieve![n]夷Por qu姻 soy el 雨nico? 斡夷Por qu姻[n]no voy de Pap茨 Noel yo tambi姻n?![n][w][e]

[msg DRESSTALK_DANCE_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eh, mirad! 斡Soy Morgana,[n]el mejor Ladr吋n Fantasma![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Destrozar sombras[n]es lo que m茨s me entusiasma![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Venga, Joker! 夷Por qu姻 no est茨s[n]bailando con mi incre胤ble flow?[n][w][e]

[msg DRESSTALK_SHADOW_W_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Mira! 斡Llevo el uniforme del[n]Equipo sombra![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este traje no est茨 nada mal[n]夷eh, Joker? 斡Sigo pareciendo[n]un Ladr吋n Fantasma![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero tambi姻n me da ganas de gritar:[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Morgana! 斡Transformaci吋吋吋吋吋n![n][w][e]

[msg DRESSTALK_SAMURAI_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Amo... 斡Digo, Joker! 夷Qu姻 tal estoy?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Creo que prefiero mi traje normal[n]de los Ladrones Fantasma.[n][w][e]

[msg DRESSTALK_RAIDOU_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, Joker. 夷Qu姻 se supone[n]que es este disfraz?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un gato de compa隠胤a?[n]斡Yo no soy eso![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Adem茨s, 夷no te acompa隠a el Jefe?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Oye, que yo no soy un gato![n][w][e]

[msg DRESSTALK_P5Dance_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eh, Joker! 夷Qu姻 te parece[n]mi ropa de baile?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, 夷no puedo quedarme[n]con esta ropa?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me emociona verme con corona.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cuando molas tanto como yo,[n]es normal ir as胤 de elegante.[n][w][e]

[msg DRESSTALK_P3Dance_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_velvetroom_PC0_11 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]O-oye, Joker...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm... 夷Y este traje?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eh! 斡No te r胤as! 斡T雨 eres el que[n]me pidi吋 que me lo pusiera![n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_11 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Phoenix Ranger Neo-Featherman![n]斡Soy Mona, tambi姻n conocido[n]como Feather Black![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Je, je, je. 斡Mientras yo est姻 aqu胤,[n]el mal no prevalecer茨![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Vamos, Joker! 斡Deja que[n]Feather Black se encargue![n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_11 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que este es el casco Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷El m胤o no es algo diferente[n]al del resto? Los ojos y la boca[n]son de otro color...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Esto es para humanos?[n]Es que es de mi talla...[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_11 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira mi traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es muy c吋modo y bastante calentito.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Con esto puesto, 斡no pasar姻 fr胤o[n]aunque vayamos a un Palacio helado![n][w][e]

[msg DRESSTALK_PQ2_PC03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Es el atuendo m茨s adorable![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece? Me queda guay, 夷eh?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 quieres decir con que[n]no he cambiado nada?[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_12 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Perdona. Estaba haciendo calor,[n]as胤 que me he puesto[n]mi ropa de verano.[n][w][e]
[s]Como es un polo, transpira bien.[n]斡No te preocupes, que podr姻[n]seguir luchando e investigando![n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_12 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este es mi uniforme de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A decir verdad, se parece bastante[n]a mi ropa informal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevar ropa con la que est茨s[n]c吋modo es lo mejor, 夷verdad?[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_12 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Esta es mi ropa informal![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como tengo los ojos claros,[n]tengo que llevar gafas de sol[n]en verano.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La luz me molesta... Pero al menos[n]son elegantes, 夷verdad?[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_12 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esta es mi ropa de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es dif胤cil combinar chaquetas,[n]pero estas me encantan.[n]Adem茨s, son bien calentitas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca te veo con chaquetas, Joker.[n]Seguro que te quedan de miedo.[n][w][e]

[msg DRESSTALK_JERSEY_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esta es mi ropa de deporte.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No os da verg鵜enza ajena?[n]Que s胤, que es c吋moda, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me recuerda a Kamoshida, as胤 que[n]no estoy muy c吋moda.[n][w][e]

[msg DRESSTALK_SWIM_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno... Este es mi ba隠ador.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me da mucha verg鵜enza... y es raro.[n]夷Por qu姻 me he puesto esto ahora?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo cierto es que hay algo[n]bastante m茨s preocupante.[n][w][e]
[s]夷T雨 qu姻 haces con mi ba隠ador?[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]部屋着・杏 Ann [n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el uniforme[n]del Instituto Gekkoukan.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Est茨 junto al oc姻ano, 夷verdad?[n]Tienes que coger el monorra胤l[n]para llegar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A diferencia del metro, tiene[n]que ser genial contemplar el oc姻ano[n]mientras vas a clase.[n][w][e]

[msg DRESSTALK_YASOGAMI_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el uniforme[n]del Instituto Yasogami.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este tono de amarillo[n]resulta sofisticado, y tambi姻n[n]me gustan las gafas falsas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero... le vendr胤a bien m茨s color.[n]夷Qu姻 te parece un c茨rdigan rojo?[n][w][e]

[msg DRESSTALK_HERMELIN_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Me he cambiado de uniforme![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Te suena un juego llamado[n]或Persona位? Se us吋 como herramienta[n]de adivinaci吋n hace mucho.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Las adivinas me dan mal rollo,[n]pero quiero probar.[n][w][e]

[msg DRESSTALK_SEVENS_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el uniforme del Seven Sisters.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No te parece muy mono este lazo?[n]斡Me encanta este uniforme![n][w][e]

[msg DRESSTALK_CATHERINE_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ey, Joker. 夷Qu姻 te parece[n]esta camisola?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No s姻 por qu姻, pero[n]me hace sentir bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ay! 夷Q-qu姻 me pasa? 斡Lo siento[n]mucho! 斡Es que hace mucho calor![n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_12 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me estoy probando el uniforme[n]del Instituto Karukozaka.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Al principio cre胤a que era muy[n]elegante, pero no est茨 tan mal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Para qu姻 sirve la m茨quina[n]de mi mano izquierda?[n]夷Dispara l茨seres o qu姻?[n][w][e]

[msg DRESSTALK_BUTLER_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voy vestida de sirvienta...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Esto es lo que te va, Joker?[n]A ver, que me da igual[n]porque es una cucada...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, tendr姻 que actuar como una.[n]斡Bienvenido a casa, amo![n][w][e]

[msg DRESSTALK_CHRIST_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un traje de Navidad, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 es tan... revelador?[n]夷No voy ense隠ando demasiado?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Y esto es un reno, no Pap茨 Noel![n]斡Solo hay que ver las astas![n][w][e]

[msg DRESSTALK_DANCE_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es muy c吋moda, as胤 que es perfecta[n]para combatir. 斡Y ahora[n]me apetece bailar![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, ya que llevo esto puesto,[n]夷por qu姻 no bailamos?[n][w][e]

[msg DRESSTALK_SHADOW_W_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Soy Panther, del Equipo sombra![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Era broma. Me siento adulta[n]con esto puesto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece la ropa que llevar胤a[n]el ejecutivo de una empresa turbia.[n]斡Siempre he querido llevar uno![n][w][e]

[msg DRESSTALK_SAMURAI_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que este es el traje de[n]samur茨i. 夷Qu姻 te parece?[n]夷Me queda bien?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es de Mikado, el reino del este?[n]Es distinto al de Jap吋n, 夷no?[n]Tiene cierto toque occidental.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque yo no me har胤a[n]el peinado tradicional con mo隠o.[n]夷Eh? 夷No hace falta?[n][w][e]

[msg DRESSTALK_RAIDOU_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que es del Instituto Ouran.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca he o胤do hablar[n]de ese instituto, pero me gusta[n]el uniforme. Sencillo y muy adulto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷El Instituto Ouran[n]tiene una larga historia o qu姻?[n][w][e]

[msg DRESSTALK_P5Dance_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, Joker, mira mi ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y no solo la ropa, je, je.[n]斡Tambi姻n me he cambiado el pelo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto extensiones y mechas.[n]夷A que son una monada?[n][w][e]

[msg DRESSTALK_P3Dance_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_velvetroom_PC0_12 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un traje de ascensorista,[n]夷no? No te preguntar姻[n]por qu姻 lo tienes...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El estilo de este vestido[n]me gusta, y el color tambi姻n.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Buena elecci吋n, Joker![n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_12 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ph-phoenix Ranger Neo-Featherman![n]斡Y-yo soy... Feather Pink![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Era as胤? No termino de pillarlo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]*suspiro* 夷Qu姻 estoy haciendo...?[n]Me gusta llevar eso puesto,[n]pero tambi姻n me da verg鵜enza.[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_12 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el casco, pero...[n]夷seguro que tengo que hacerlo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ver, que no es inc吋modo, pero[n]cuando me imagino con ese casco...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Siento que llevo un cubo[n]en la cabeza![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡No quiero llevarlo m茨s![n]斡Deja que me lo quite![n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_12 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los colores son de estilo militar.[n]夷Es un uniforme de alg雨n ej姻rcito?[n][w][e]

[msg DRESSTALK_PQ2_PC04 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Mira, Joker! 斡Es el atuendo[n]m茨s adorable![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S姻 que sonar茨 raro, pero[n]夷no es una monada?[n]Adem茨s, est茨 muy bien hecho.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo malo es que mi cabeza[n]parece enorme.[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_13 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto la ropa[n]que llevo al instituto.[n][w][e]
[s]En mi instituto no hace falta[n]uniforme, as胤 que me pongo[n]la ropa que me gusta.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_13 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto la ropa[n]que llevo al instituto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque en mi instituto[n]no haga falta llevar uniforme,[n]suelo llevar camisas abotonadas.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_13 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa informal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Normalmente hace fr胤o donde[n]me gusta dibujar, as胤 que llevo[n]camisetas de manga larga.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece esta camisa de[n]tres colores? A m胤 me gusta.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_13 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No me gustan demasiado las prendas[n]r胤gidas. Prefiero llevar chaquetas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷t雨 tambi姻n prefieres[n]las chaquetas? En ese aspecto[n]se ve que nos parecemos.[n][w][e]

[msg DRESSTALK_JERSEY_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_SWIM_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ba隠ador.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el茨stico y bastante c吋modo.[n]Podr胤a pelear con 姻l.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero, Joker... 夷Por qu姻 tengo que[n]ponerme esto ahora?[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]部屋着・祐介[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Conque el uniforme del Instituto[n]Gekkoukan... El evocador con forma[n]de pistola es muy particular.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Con dicho evocador, uno debe[n]enfrentarse a la muerte[n]para invocar a su Persona.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En mi caso, 夷deber胤a partirme[n]en dos?[n][w][e]

[msg DRESSTALK_YASOGAMI_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme[n]del Instituto Yasogami.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca me hab胤a puesto este tipo[n]de uniforme, pero no me disgusta.[n]El dise隠o tiene pasi吋n y elegancia.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De verdad son falsas estas gafas?[n]Mi visi吋n cambia un poco con ellas...[n][w][e]

[msg DRESSTALK_HERMELIN_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira, Joker. Es el uniforme del[n]Instituto St. Hermelin.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El verde claro combina bien[n]con las l胤neas negras. Es agradable[n]y sencillo, pero... le falta algo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tambi姻n me ayuda a despejarme.[n]Siento que puedo dibujar[n]con la mente fresca.[n][w][e]

[msg DRESSTALK_SEVENS_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira, llevo el uniforme del[n]Instituto Seven Sisters.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta el dise隠o del pecho.[n]Las siete estrellas parecen sacadas[n]de una bandera nacional.[n][w][e]

[msg DRESSTALK_CATHERINE_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he probado ropa m茨s adulta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por cierto, Joker. 郁ltimamente[n]tengo sue隠os muy raros.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Subo constantemente[n]mientras algo me persigue...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es lo 雨nico que recuerdo.[n]Siento hablar de algo tan extra隠o.[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_13 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el uniforme[n]del Instituto Karukozaka.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La chaqueta azul, la colorida pieza[n]inferior... Parece algo anticuado,[n]pero me gusta el dise隠o.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Para qu姻 sirve la m茨quina[n]de mi mano izquierda?[n]夷Es para marcar tendencia?[n][w][e]

[msg DRESSTALK_BUTLER_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voy vestido de mayordomo, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esta ropa me da ganas de mantener[n]una buena postura. No es como un[n]traje normal. Me siento impoluto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por lo visto los mayordomos tienen[n]rangos. Este atuendo es para[n]los mejores.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deben confiar mucho en ellos,[n]siendo los mejores clasificados...[n]夷T雨 conf胤as tanto en m胤, Joker?  [n][w][e]

[msg DRESSTALK_CHRIST_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo un traje de Pap茨 Noel.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cre胤a que Pap茨 Noel ten胤a que ser[n]grande. Quiz茨 estoy[n]demasiado delgada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siempre me he preguntado algo...[n]夷Pap茨 Noel no se queda[n]atascado al bajar por la chimenea?[n][w][e]

[msg DRESSTALK_DANCE_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hac胤a tiempo que no me pon胤a[n]una camiseta sin mangas.[n]*risita* Qu姻 fresquito.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y ahora, 斡alcanza las profundidades[n]del espacio y siente el ritmo![n]斡A bailar, Joker![n][w][e]

[msg DRESSTALK_SHADOW_W_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es mi uniforme del Equipo sombra.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tengo entendido que el dise隠o[n]de las gafas cambia seg雨n[n]cada persona. 夷Por qu姻 ser茨?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pues a ver... Casi parece[n]que est茨 hecho del mismo material[n]que un robot.[n][w][e]

[msg DRESSTALK_SAMURAI_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo una cosa que se llama[n]ropaje de samur茨i.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Al pensar en 或samur茨i位 me imaginaba[n]algo m茨s japon姻s, pero esto[n]no est茨 nada mal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por el guantelete de la mano[n]izquierda parece medieval. O eso,[n]o es de un mundo de fantas胤a.[n][w][e]

[msg DRESSTALK_RAIDOU_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el uniforme del Instituto[n]imperial Yumizuki.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No est茨 nada mal.[n]Con esta ropa podr姻 concentrarme[n]en el instituto y dibujar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un estudiante pobre?[n]斡No me digas eso![n][w][e]

[msg DRESSTALK_P5Dance_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, me he puesto[n]mi ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 mi ropa tiene[n]tantos pinchos?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷En serio hacen falta para bailar?[n]Tengo miedo de lastimarme.[n][w][e]

[msg DRESSTALK_P3Dance_PC05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_velvetroom_PC0_13 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Un uniforme de botones? Bueno,[n]no voy a preguntarte por qu姻[n]tienes algo as胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 斡qu姻 color![n]斡Es un tono azul precioso![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Debo reunir mis utensilios[n]de dibujo y plasmar este color[n]antes de que se me olvide![n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_13 [Yusuke]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Soy Phoenix Ranger Neo-Featherman,[n]Feather Blue![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mientras exista el mal, aplacar姻 mi[n]hambre, seguir姻 mi amor por el arte[n]y ser姻 el h姻roe de la justicia...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Feather Blue! Vale, creo que me[n]presentar姻 as胤.[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_13 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi casco Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qu姻 raro... A pesar de todo[n]lo que lleva, es muy ligero.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Panther dice que parece un cubo,[n]pero a m胤 me gusta el dise隠o.[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_13 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tiene que tener un casco, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No escatima en funciones,[n]y el dise隠o es exquisito.[n][w][e]

[msg DRESSTALK_PQ2_PC05 [Yusuke]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qu姻 disfraz tan raro...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 斡夷qu姻...?! Mi cabeza parece[n]m茨s grande, y es muy suave[n]por fuera.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La cabeza... me pesa...[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_14 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi uniforme.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es triste pensar que no me voy a[n]poner esto cuando me grad雨e.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_14 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi uniforme.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Hay chaquetas espec胤ficas[n]del instituto,[n]pero no nos obligan a llevarlas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es triste pensar que no me voy a[n]pon姻rmelo cuando me grad雨e.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_14 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado a mi ropa informal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mi amiga me dijo que suelo[n]vestir m茨s... seria.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cuando compro ropa, normalmente[n]voy con Sae, as胤 que puede[n]deberse a eso.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_14 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado[n]a mi ropa de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esta chaqueta era de mi hermana.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como hay una diferencia de edad[n]entre nosotras, me alegr姻[n]mucho cuando me la dio.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me hizo sentir que estaba preparada[n]para vestir con la misma[n]madurez que mi hermana.[n][w][e]

[msg DRESSTALK_JERSEY_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa de deporte.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Con ella, saltar y correr es pan[n]comido. La libertad de movimiento[n]en una pelea es esencial.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷C吋mo era la ropa de deporte[n]de tu anterior instituto?[n][w][e]

[msg DRESSTALK_SWIM_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ba隠ador.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 llevo un ba隠ador aqu胤?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me cuesta decir si siento[n]m茨s fr胤o o verg鵜enza...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y... 夷por qu姻 tienes t雨 mi ba隠ador?[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme[n]del Instituto Gekkoukan.[n][w][e]
[s]Tengo entendido que una[n]de las graduadas fue una presidenta[n]del consejo estudiantil ejemplar.[n][w][e]
[s]La vida tambi姻n le fue bien despu姻s[n]de graduarse. Es la representante[n]de una compa隠胤a importante.[n][w][e]

[msg DRESSTALK_YASOGAMI_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No solemos tener la oportunidad[n]de llevar estos trajes de marinero,[n]pero me parecen una monada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los trajes de marinero que llevamos[n]est茨n basados en lo que vest胤an[n]los ni隠os de la realeza europea.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El pa隠uelo del traje tradicional[n]se usaba hasta para torniquetes[n]en momentos de vida o muerte.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Todo tiene su historia, hasta[n]nuestra ropa. 夷No es fascinante?[n][w][e]

[msg DRESSTALK_HERMELIN_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me estoy probando el uniforme del[n]Instituto St. Hermelin.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca he llevado uniforme con[n]corbata. 夷Qu姻 te parece?[n]夷Me queda bien?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Creo que te queda muy bien,[n]en serio. 斡Y tiene un aire a m胤[n]que me encanta![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Parece que formas parte[n]del consejo estudiantil![n][w][e]

[msg DRESSTALK_SEVENS_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el uniforme del[n]Seven Sisters.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Recuerdo un caso que ocurri吋 all胤.[n]Dec胤an que si se comenzaba[n]un rumor, se convert胤a en realidad.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiz茨 es un tipo de manipulaci吋n[n]cognitiva. Interesante.[n][w][e]

[msg DRESSTALK_CATHERINE_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oye, Joker. Llevamos mucho[n]esperando. A lo mejor ya[n]es hora de que...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]E-espera, 斡夷q-qu姻 he[n]estado a punto de decir?![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡N-no es lo que piensas! No s姻[n]por qu姻, esta ropa me hace pensar[n]en apresurarme y en el matrimonio...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Pero qu姻 digo?! 斡Perdona,[n]no he dicho nada![n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_14 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, llevo el uniforme[n]del Instituto Karukozaka.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los colores son algo exc姻ntricos,[n]夷no crees? Y la falda[n]es muy corta para mi gusto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Para qu姻 servir茨 esta m茨quina?[n]夷Podr姻 usarla en combate?[n][w][e]

[msg DRESSTALK_BUTLER_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voy... vestida de sirvienta...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me parece adorable. Me preocupa[n]un poco que no me quede bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Espera! 斡Eso no es lo importante![n]斡夷Por qu姻 llevo[n]un vestido de sirvienta?![n][w][e]

[msg DRESSTALK_CHRIST_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Feliz Navidad, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me da un poco de verg鵜enza,[n]pero nunca he llevado un traje[n]de Pap茨 Noel. Me siento diferente.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 no tengo manga derecha?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y... 夷este cintur吋n[n]no da un poco de miedo?[n][w][e]

[msg DRESSTALK_DANCE_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ense隠a demasiado para mi gusto,[n]pero resulta f茨cil moverse.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero me da un poco de verg鵜enza.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No me mires, porfa.[n][w][e]

[msg DRESSTALK_SHADOW_W_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el traje del[n]Equipo sombra.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este traje es un poco estrecho...[n]Me siento rara.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Los ojos de esta m茨scara[n]no est茨n un poco torcidos?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷De verdad parece que[n]estoy de mal humor?[n][w][e]

[msg DRESSTALK_SAMURAI_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el traje de samur茨i.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se ha hecho para ser resistente,[n]pero me he dado cuenta[n]al pon姻rmelo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece que a胤sla muy bien[n]la temperatura. Tiene pinta[n]de que ir茨 bien para luchar.[n][w][e]

[msg DRESSTALK_RAIDOU_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme[n]del Instituto Ouran.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No lo conozco, pero[n]parece un instituto con historia.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me encantan los colores[n]del uniforme. Este tono rosado[n]me recuerda a los cerezos en flor.[n][w][e]

[msg DRESSTALK_P5Dance_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto[n]mi ropa de baile, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entiendo que este traje es[n]para llevarlo sobre el escenario[n]pero 夷este corte es necesario?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gustar胤a arreglarlo.[n]S姻 que es para parecer guay, pero...[n][w][e]

[msg DRESSTALK_P3Dance_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_velvetroom_PC0_14 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esta ropa es elegante y bonita.[n]La diadema tambi姻n es una monada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y este azul me encanta.[n]Podr胤a mirarlo durante horas.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_14 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Soy... Soy... Phoenix Ranger...[n]Neo Featherman.[n][w][e]
[s]No me mires con esa cara.[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_14 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el casco[n]del traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tengo la sensaci吋n de que nadie[n]me va a reconocer con esto puesto.[n]夷Qu姻 pasar茨 si todos lo llevan?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entiendo que sea muy 雨til, pero[n]podr胤an haberse esforzado un poco[n]m茨s con el dise隠o.[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_14 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece el mismo que el de los[n]dem茨s, pero color del brazo[n]es un poco diferente.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los propietarios originales sab胤an[n]en qu姻 departamentos estaban[n]por los colores de los brazos.[n][w][e]

[msg DRESSTALK_PQ2_PC06 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el traje 或Q位, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 es esto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este cabez吋n es la mar de inc吋modo...[n]夷Es un disfraz de mascota?[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_15 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi uniforme de verano.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En el Shujin son un poco m茨s[n]indulgentes, as胤 que suelo llevar[n]camisetas sin mangas en verano.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me resulta m茨s sencillo moverme[n]cuando trabajo en el jard胤n.[n]Me entiendes, 夷verdad?[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_15 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo mi uniforme normal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como no me gusta pasar fr胤o,[n]suelo llevar estas mallas[n]y una chaqueta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Adem茨s, llevo unos calentadores[n]en los bolsillos[n]para mantener el calor.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_15 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa informal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es dif胤cil escoger entre la ropa[n]fresca y la que impide que[n]coja un bronceado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Suelo decantarme[n]por la ropa fresca,[n]pero no s姻 qu姻 har茨 el resto.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_15 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me encanta la temporada de fr胤o.[n]El t姻 y el caf姻 siempre[n]saben mejor.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷t雨 qu姻 prefieres,[n]t姻 o caf姻? 斡Seguro[n]que el caf姻 del Leblanc![n][w][e]

[msg DRESSTALK_JERSEY_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa de deporte.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es comod胤sima, como siempre.[n]Estoy acostumbrada a llevarla,[n]y es genial para moverse.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Adem茨s, no pasa nada si se mancha[n]en el jard胤n, 夷no? O puede que s胤... [n][w][e]

[msg DRESSTALK_SWIM_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Por qu姻 me he puesto mi ba隠ador?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es cierto que no hemos llegado a ir[n]a la playa con todos, pero[n]夷de verdad tengo que llevar esto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No es que no quiera llevarlo,[n]pero me da verg鵜enza.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un momento... 夷Por qu姻 ten胤as[n]t雨 esto, Joker?[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado al uniforme[n]del Instituto Gekkoukan. Dicen que[n]tiene una residencia. 夷C吋mo ser茨?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Hablar茨n por las noches?[n]Me recuerda a nuestro escondite.[n][w][e]

[msg DRESSTALK_YASOGAMI_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el uniforme[n]del Instituto Yasogami.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es una monada de uniforme,[n]pero creo que el lazo amarillo[n]destaca demasiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Elegir胤an este color para evitar[n]accidentes de tr茨fico?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No me esperaba que hubiera tantos[n]accidentes, pero tal vez haya[n]mucha niebla por el instituto.[n][w][e]

[msg DRESSTALK_HERMELIN_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el uniforme[n]del Instituto St. Hermelin.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qu姻 atuendo tan especial.[n]No s姻 por qu姻, pero da la impresi吋n[n]de que es muy c吋modo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ser茨 por el verde claro? Es el[n]color de las plantas. Estar茨 hecho[n]para que transmita tranquilidad.[n][w][e]

[msg DRESSTALK_SEVENS_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme del[n]Seven Sisters. 夷Me queda bien?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A m胤 me parece un poco soso,[n]pero algo me dice que[n]no deber胤a preocuparme.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]或斡Pensemos en positivo!位.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]N-no es lo que piensas. Por alguna[n]raz吋n, ten胤a que decirlo.[n][w][e]

[msg DRESSTALK_CATHERINE_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Con esto puesto, me siento[n]como si trabajara en una[n]de nuestras tiendas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A lo mejor es porque se parece[n]al uniforme del Big Bang Burger,[n]con alguna peque隠a diferencia.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si pillamos comida para llevar,[n]no pasaremos hambre[n]mientras investigamos.[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_15 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme del[n]Instituto Karukozaka.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si me abrocho la camisa[n]me siento algo tensa, y me aprieta[n]en el pecho.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los cascos est茨n conectados[n]a mi brazo izquierdo,[n]pero 夷por qu姻?[n][w][e]

[msg DRESSTALK_BUTLER_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, llevo un vestido de sirvienta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Q-qu姻 te parece? Joker,[n]夷te gustan estos vestidos?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya que lo llevo puesto, quiz茨[n]deber胤a actuar como si lo fuera.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ver qu姻 tal... Nos vemos en casa,[n]amo. 夷As胤 est茨 bien?[n][w][e]

[msg DRESSTALK_CHRIST_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo un traje de Navidad.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La gargantilla, el lazo[n]y las mallas son muy bonitos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Antes siempre iba[n]a las fiestas de mi padre, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiz茨 este a隠o pueda pasar[n]tiempo con vosotros.[n][w][e]

[msg DRESSTALK_DANCE_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No suelo llevar estas cosas,[n]pero 夷qu姻 tal estoy? Hasta me he[n]puesto una estrellita en la cara.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiz茨 mis mallas son[n]demasiado llamativas.[n][w][e]

[msg DRESSTALK_SHADOW_W_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el uniforme del[n]Equipo sombra.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque esta ropa[n]es un poco ajustada.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me da verg鵜enza, es muy ajustado...[n][w][e]

[msg DRESSTALK_SAMURAI_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que este es el ropaje[n]de samur茨i.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No me importa llevarlo, pero es un[n]poco diferente de los samur茨i[n]que conozco.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es bastante resistente. Igual[n]viene bien para la jardiner胤a.[n][w][e]

[msg DRESSTALK_RAIDOU_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me estoy probando el uniforme del[n]Instituto Ouran, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los colores son peculiares,[n]pero me parece muy mono.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Normalmente no me pongo trajes[n]de marinera, as胤 que no est茨 mal.[n][w][e]

[msg DRESSTALK_P5Dance_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, me he puesto[n]mi ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Antes hac胤a ballet,[n]pero nunca he bailado[n]con un traje como este.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece el lazo? *risita*[n]La verdad es que me gusta mucho.[n][w][e]

[msg DRESSTALK_P3Dance_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_velvetroom_PC0_15 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, Joker. Me he probado otra cosa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un atuendo muy maduro.[n]Tiene un tono de azul precioso.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece el traje de una secretaria.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]或Se隠or, tiene una reuni吋n[n]en una hora位. *risita* Es broma.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_15 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Soy Phoenix Ranger Neo-Featherman,[n]Feather Purple.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]*risita* No importa lo antiguos[n]que sean, a los chicos les encantan[n]los superh姻roes.[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_15 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, Joker. Me he puesto[n]el traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es c吋modo, pero[n]夷de verdad es necesario llevarlo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nos protege de gases venenosos[n]y virus, pero 夷habr茨 de eso[n]en un Palacio?[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_15 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado al traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ser茨 para alg雨n tipo de ej姻rcito?[n]Otorga mucha movilidad[n]y es muy robusto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Puede ir bien para jardiner胤a.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiz茨 deber胤a pon姻rmelo m茨s[n]a menudo... Pero llamar胤a mucho[n]la atenci吋n.[n][w][e]

[msg DRESSTALK_PQ2_PC07 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el disfraz adorable.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es muy mono, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 es exactamente?[n]La cabeza pesa un mont吋n.[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_16 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]秀尽学園制服・夏・双葉[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_16 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]秀尽学園制服・冬・双葉[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_16 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto ropa informal.[n]Es tan c吋moda como siempre.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esta bolsa tambi姻n es muy 雨til.[n]Tiene herramientas de hackeo[n]para cuando las necesite.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, y fideos instant茨neos.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_16 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto[n]mi ropa informal de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevar cascos en oto隠o e invierno[n]me da la vida.[n]斡Hasta los puedo usar de orejeras![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Es perfecta para esta estaci吋n![n]斡Dos p茨jaros de un tiro![n][w][e]

[msg DRESSTALK_JERSEY_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]ジャージ・双葉[n][w][e]

[msg DRESSTALK_SWIM_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Joker? 夷Por qu姻 llevo mi ba隠ador?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uf, llamo much胤simo la atenci吋n.[n]En serio, 夷por qu姻[n]llevo esto puesto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y ahora que lo pienso, 夷por qu姻[n]ten胤as mi biquini, Joker?[n]斡Oye, no mires para otro lado![n][w][e]

[msg DRESSTALK_ROOMWEAR_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]部屋着・双葉[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el uniforme[n]del Instituto Gekkoukan.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dicen que es un instituto de alta[n]tecnolog胤a junto al oc姻ano.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, todo muy tecnol吋gico,[n]pero paso, porque tendr胤amos[n]que vivir en una residencia.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡No quiero dejar solo a Sojiro![n][w][e]

[msg DRESSTALK_YASOGAMI_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme[n]del Instituto Yasogami.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un instituto de las afueras,[n]夷no? 夷Hay muchos insectos por all胤?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uf, ni de co隠a. Yo ese juego[n]no lo puedo ganar. Es como decirme[n]que hay enemigos en cada esquina.[n][w][e]

[msg DRESSTALK_HERMELIN_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme[n]del St. Hermelin.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es raro... No s姻 si me convence.[n][w][e]

[msg DRESSTALK_SEVENS_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el uniforme del[n]Instituto Seven Sisters.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La ciudad de donde viene[n]es muy interesante.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por lo visto, si manipulas[n]la cognici吋n de alguien,[n]esta se convierte en realidad.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷C吋mo lo har胤an? 夷Crees que[n]ser茨 f茨cil?[n][w][e]

[msg DRESSTALK_CATHERINE_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, as胤 en general, 夷qu姻 opinas?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No s姻 por qu姻 me apetece trastear[n]con m茨quinas. Podr胤a arreglar[n]un coche o algo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A lo mejor puedo trastear[n]con el Monam吋vil. Siempre[n]he querido ver el interior.[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_16 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira, me he puesto el uniforme[n]de... 夷Karukozaka? Pues eso.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es muy apretado. Esta clase[n]de uniformes no me queda bien.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y la m茨quina de la mano izquierda[n]pesa mucho.[n][w][e]

[msg DRESSTALK_BUTLER_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Mua, ja, ja, ja![n]斡Llevo un vestido de sirvienta![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En Akihabara hay cafeter胤as de[n]sirvientas, 夷no? Seguro que dicen:[n]或Amo, 斡me haces sentir especial!位.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Vale, quiero probar![n]斡Bienvenido a casa, sirviente![n][w][e]

[msg DRESSTALK_CHRIST_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Oracle, la hacker de nariz roja.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hackeando por el Metaverso![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Feliz Navidad, Joker. 斡Vamos a casa[n]a comer curry con Sojiro![n][w][e]

[msg DRESSTALK_DANCE_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Mira mi traje de baile, Joker![n]斡M胤ralo! B-bueno, 斡no, no lo mires![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ya qu姻 m茨s da? 斡Es una revoluci吋n![n]Solo tengo que entusiasmarme...[n][w][e]

[msg DRESSTALK_SHADOW_W_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Soy Oracle![n]斡Miembro del Equipo[n]Phoenix Neosombra![n][w][e]
[s]Mua, ja, ja, 夷qu姻 te parece?[n]斡No puedo evitarlo cuando[n]me pongo algo as胤![n][w][e]

[msg DRESSTALK_SAMURAI_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esta cosa de samur茨i pesa mucho.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pensaba que llevar胤a un kimono,[n]pero 斡la tableta de mi mano[n]izquierda est茨 que arde![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Supongo que tener una tableta[n]incorporada en la armadura[n]es un concepto interesante.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Puedo abrirla y trastearla?[n][w][e]

[msg DRESSTALK_RAIDOU_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me voy a probar un uniforme, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es inc吋modo y poco flexible.[n]No soporto los uniformes.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No puedo creer que la gente[n]vaya al instituto as胤 vestida.[n]Esta misi吋n es demasiado para m胤.[n][w][e]

[msg DRESSTALK_P5Dance_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷A qu姻 te refieres con que es mi[n]ropa normal? 斡Qu姻 borde![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo 雨nico que no ha cambiado son[n]mis cascos, que se van[n]a quedar como est茨n. 斡As胤 de claro![n][w][e]

[msg DRESSTALK_P3Dance_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_velvetroom_PC0_16 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Me he cambiado, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un traje de botones, 夷verdad?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora que lo pienso, nunca he visto[n]a nadie as胤 en un hotel de verdad.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, al menos en Yongen[n]no hay ning雨n sitio as胤.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_16 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Phoenix Ranger Neo-Featherman![n]斡Yo! 斡Soy! 斡Feather Green![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mua, ja, ja. 斡Siempre he querido[n]ponerme esto! 斡Featherman[n]es el mejor![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 夷por qu姻 no soy roja?[n]斡Ah, t雨 eres el rojo, Joker![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me lo tienes que dejar, 夷vale?[n]斡Y es una orden![n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_16 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi casco Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parezco el malo de una pel胤cula[n]de ciencia ficci吋n, 夷eh? Me gusta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, yo soy tu padre... 斡Shhh![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya, claro. De todas formas,[n]es una cita err吋nea...[n]Pero se parece, 夷a que s胤?[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_16 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi traje Demonica,[n]Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Normalmente llevo[n]el Ciberequipamiento, as胤 que[n]no hay mucha diferencia.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eso s胤, es m茨s calentito[n]que el m胤o. Tendr茨 una funci吋n[n]para controlar la temperatura.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Podr胤a ir hasta al Ant茨rtico![n]Aunque preferir胤a quedarme en casa.[n][w][e]

[msg DRESSTALK_PQ2_PC08 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, este traje es muy raro.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Esto qu姻 es? Queda demasiado[n]bien para ser un disfraz.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 le pasa a la cabeza?[n]斡Es enorme![n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC0_17 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa de verano.[n]Hac胤a bastante calor.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aunque me he dejado la corbata.[n]Tengo que seguir pareciendo[n]un caballero.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC0_17 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo mi ropa de invierno.[n][w][e]
[s]El uniforme del Shujin no est茨 mal,[n]pero prefiero el de mi instituto.[n][w][e]
[s]No me pienso quitar estos guantes.[n]Nunca se sabe cu茨ndo me pueden[n]llamar al escenario de un crimen.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_17 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esta es mi ropa informal.[n]Suelo estar rodeado de adultos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por lo tanto, me gusta[n]vestirme de forma m茨s madura.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_17 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo puesta mi ropa[n]informal de invierno.[n]Hoy parec胤a que iba a refrescar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mi ropa informal es m茨s de adulto.[n]Para los detectives, es importante[n]no llamar mucho la atenci吋n.[n][w][e]

[msg DRESSTALK_JERSEY_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]ジャージ・明智[n][w][e]

[msg DRESSTALK_SWIM_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷por qu姻 me has hecho[n]ponerme el ba隠ador?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A ver, s姻 que te puedes mover[n]mejor, pero...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me parece de caj吋n[n]no llevarlo puesto aqu胤.[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece el uniforme[n]del Instituto Gekkoukan?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uno no puede llevar uniformes[n]de otros centros todos los d胤as.[n]Me gusta el cambio de aires.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He o胤do que tuvieron una presidenta[n]del consejo estudiantil muy capaz[n]hace un tiempo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gustar胤a jugar al ajedrez con[n]ellos si pudiera alguna vez.[n][w][e]

[msg DRESSTALK_YASOGAMI_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme[n]del Instituto Yasogami.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Has o胤do hablar del Pr胤ncipe[n]Detective? Es el primer detective[n]de instituto de 姻lite.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dicen que el Pr胤ncipe Detective era[n]implacable con los culpables, pero[n]que luego se volvi吋 m茨s expresivo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No s姻 lo que ha pasado. Solo puedo[n]asumir que el pr胤ncipe ha[n]encontrado buenos amigos.[n][w][e]

[msg DRESSTALK_HERMELIN_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el uniforme del[n]Instituto St. Hermelin.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca me hab胤a probado un uniforme[n]que fuera diferente arriba[n]y abajo. 夷C吋mo me queda?[n][w][e]

[msg DRESSTALK_SEVENS_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me estoy probando el uniforme[n]del Instituto Kasugayama.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El azul claro es peculiar,[n]pero destaca demasiado. No parece[n]la mejor opci吋n para un detective.[n][w][e]

[msg DRESSTALK_CATHERINE_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece? Es el traje[n]de camarera, por lo visto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo siento, pero no puedo servir[n]alcohol. Puedo serviros zumo...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eso o un c吋ctel sin alcohol.[n]Conozco un buen sitio en Kichijoji.[n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC0_17 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Creo que es el uniforme de Hazama.[n]夷No crees que es exagerado?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero cuando llevo este tipo[n]de ropa, siento un extra隠o poder[n]dentro de m胤.[n][w][e]

[msg DRESSTALK_BUTLER_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Voy de mayordomo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta. Con los guantes,[n]hasta me parecer胤a[n]adecuado para investigar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si fueras una mujer, te llamar胤a[n]或princesa位... pero supongo[n]que en tu caso te llamar姻 或amo位.[n][w][e]

[msg DRESSTALK_CHRIST_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 pasa? 夷Por qu姻 me miras as胤?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto esta ropa porque[n]me lo has pedido, pero... 夷No parece[n]m茨s bien ropa de payaso?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eh, que te veo re胤rte![n][w][e]

[msg DRESSTALK_DANCE_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Me queda bien? A m胤 me gusta.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Que ponga 或HERO位 me pega bastante,[n]por lo de la justicia y todo eso.[n]夷A que me va como anillo al dedo?[n][w][e]

[msg DRESSTALK_SHADOW_W_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es el traje del Equipo sombra.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Nunca lo hab胤a escuchado, pero[n]tambi姻n luchan contra[n]las sombras, 夷verdad?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qu姻 sorpresa que haya[n]m茨s como nosotros.[n][w][e]

[msg DRESSTALK_SAMURAI_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo un ropaje de samur茨i.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No tiene nada que ver[n]con los samur茨is de Jap吋n. Parece[n]de los que viajaron a occidente.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Con esto voy protegido, as胤 que[n]puede que vaya bien para luchar.[n][w][e]

[msg DRESSTALK_RAIDOU_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Es un uniforme imperial[n]del ej姻rcito? Me cuesta creer[n]que tengas uno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ser茨 mejor que acates mis 吋rdenes.[n]Por aquel entonces,[n]te partir胤an en dos.[n][w][e]

[msg DRESSTALK_P5Dance_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me da un poco de verg鵜enza...[n]Es que no suelo llevar[n]este tipo de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No pienso perder contra ti[n]ni bailando.[n][w][e]

[msg DRESSTALK_P3Dance_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_velvetroom_PC0_17 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un uniforme de botones, 夷verdad?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevar las pertenencias[n]de los clientes y guiarlos[n]cuando haga falta...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Vas a pedirme que te lleve el[n]equipaje? Pues ni hablar.[n][w][e]

[msg DRESSTALK_FEATHERMAN_PC0_17 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Soy Phoenix Ranger Neo-Featherman,[n]Feather Silver.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ay, cu茨ntos recuerdos.[n]Lo ve胤a hace ya mucho.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los personajes de apoyo que se unen[n]a tu equipo suelen ser m茨s fuertes[n]que los principales, 夷no?[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_17 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He decidido probarme[n]el casco Demonica, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷A que es incre胤ble? Puede parecer[n]raro, pero es bastante c吋modo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me sorprende que adivinaras[n]que era yo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espera... A lo mejor[n]no me has reconocido.[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_17 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el traje Demonica.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me queda como un guante,[n]as胤 que es f茨cil moverse[n]a la hora de investigar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷D吋nde los has conseguido?[n]Le ir胤an mejor a un ej姻rcito.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]*risita* Es broma, no quiero[n]ser entrometido. Ya lo descubrir姻[n]por mi cuenta.[n][w][e]

[msg DRESSTALK_PQ2_PC09 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he cambiado, pero...[n]no s姻 qu姻 es esto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como mi cabeza es m茨s grande,[n]la nariz de la m茨scara[n]pesa m茨s de lo que parece.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Deja que me lo quite.[n][w][e]

[msg DRESSTALK_UNI_SUMMER_PC1 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, me he puesto[n]mi uniforme de verano.[n][w][e]
[s]Tengo un buen metabolismo y[n]prefiero el fr胤o, as胤 que esta ropa[n]es m茨s c吋moda para m胤.[n][w][e]

[msg DRESSTALK_UNI_WINTER_PC1 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Me he puesto mi uniforme![n][w][e]
[s]Me gusta la ropa de los Ladrones[n]Fantasma, pero el uniforme[n]del instituto es mi favorito.[n][w][e]

[msg DRESSTALK_SIFU_SUMMER_PC_18 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa informal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece? 夷Me queda bien?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta la ropa con lunares.[n]Cada vez que miro el armario[n]parece que se han multiplicado.[n][w][e]

[msg DRESSTALK_SIFU_WINTER_PC_18 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa de invierno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Me queda bien?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cuando llevo ropa con colores[n]c茨lidos, siento m茨s calor[n]incluso en sitios m茨s fr胤os.[n][w][e]

[msg DRESSTALK_JERSEY_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ropa de deporte.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gustan los leotardos,[n]pero esta ropa de deporte tampoco[n]est茨 nada mal.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡De hecho, es muy pr茨ctica![n]Me mantiene fresca[n]y el sudor se seca en un momento.[n][w][e]

[msg DRESSTALK_SWIM_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto mi ba隠ador.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Va genial para nadar, pero[n]me da un poco de verg鵜enza.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por cierto, Joker. 夷Por qu姻 tienes[n]t雨 mi ba隠ador?[n][w][e]

[msg DRESSTALK_ROOMWEAR_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0] 着・ Kasumi[n][w][e]

[msg DRESSTALK_GEKKOUKAN_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, me estoy probando el[n]uniforme del Instituto Gekkoukan.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Gekkoukan es famoso por sus clubes[n]deportivos, en concreto[n]los de kendo, atletismo y nataci吋n.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y los de tenis y voleibol[n]no se quedan atr茨s. 斡En fin,[n]que son muy buenos![n][w][e]

[msg DRESSTALK_YASOGAMI_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el uniforme[n]del Instituto Yasogami.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]He o胤do que ah胤 se come un bol[n]de ternera para chuparse los dedos.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si pienso en mi peso, no es algo[n]que deba comer ahora mismo...[n]Pero 斡quiero probarlo alg雨n d胤a![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Joker, cuando llegue el momento,[n]vamos juntos![n][w][e]

[msg DRESSTALK_HERMELIN_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo el uniforme[n]del Instituto St. Hermelin.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es la primera vez que llevo[n]corbata. Me gusta bastante.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gusta el detalle del hombro[n]izquierdo. 夷No es una comadreja?[n][w][e]

[msg DRESSTALK_SEVENS_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme del[n]Seven Sisters.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se parece al uniforme del Instituto[n]Shujin, 夷no? 夷C吋mo estoy?[n][w][e]

[msg DRESSTALK_CATHERINE_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, me he cambiado.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El conjunto de marinera, la peluca[n]de pelo corto... 斡Es todo[n]mon胤simo y muy femenino![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y llevo este brazalete tambi姻n.[n]夷Crees que la piedra tiene poder?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Esta ropa me ha tocado[n]la fibra sensible![n][w][e]

[msg DRESSTALK_KARUKOZAKA_PC1 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme del[n]Instituto Karukozaka.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esta m茨quina que tengo en el brazo[n]y los auriculares... 夷son parte[n]del uniforme?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Lo utilizan en clase? Debe ser[n]un instituto muy tecnol吋gico.[n][w][e]

[msg DRESSTALK_BUTLER_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Joker, voy de sirvienta![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No voy a preguntarte[n]por qu姻 tienes esto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 era lo que dec胤an?[n]斡Buen trabajo hoy, amo![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espera, 夷eso est茨 bien?[n][w][e]

[msg DRESSTALK_CHRIST_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Me estoy probando[n]mi disfraz de Navidad![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Q-qu姻 tal estoy? Me preocupaba,[n]porque nunca me hab胤a[n]puesto este tipo de ropa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Te gusta? 斡Ji, ji, menos mal![n][w][e]

[msg DRESSTALK_DANCE_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]ダンス Costume ・ Kasumi [n][w][e]

[msg DRESSTALK_SHADOW_W_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Llevo el uniforme del[n]Equipo sombra![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece? 斡Con esto puesto[n]me siento mayor que t雨![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Yo me encargo de las sombras![n]斡Solo tienes que pedirlo![n][w][e]

[msg DRESSTALK_SAMURAI_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Llevo mi traje de samur茨i.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No me lo imaginaba as胤,[n]pero creo que est茨 muy guay.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Otorga mayor libertad de movimiento[n]que una hakama.[n][w][e]

[msg DRESSTALK_RAIDOU_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he puesto el uniforme[n]del Instituto Ouran.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este color vino es muy inusual[n]en un uniforme de instituto.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece muy maduro para un alumno[n]de instituto. Me mola.[n][w][e]

[msg DRESSTALK_P5Dance_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mira, me he puesto ropa de baile.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Solo he bailado[n]en el festival del instituto,[n]pero 斡fue muy divertido![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Seguro que bailar m茨s me ayuda con[n]mi ejercicio, as胤 que voy a probar![n][w][e]

[msg DRESSTALK_P3Dance_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]RESERVE[n][w][e]

[msg DRESSTALK_velvetroom_PC1 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me he probado otra cosa, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es un traje de ascensorista, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Subimos. Ja, ja, es broma.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qu姻 color tan bonito. 斡Me gusta![n][w][e]

[msg DRESSTALK_FEATHERMAN_PC1 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Soy Phoenix Ranger Neo Featherman:[n]Feather White![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siempre he admirado a los dobles[n]de acci吋n que se ponen estos trajes[n]y se llevan los golpes.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me encantar胤a dar volteretas hacia[n]atr茨s y laterales en una rutina.[n][w][e]

[msg DRESSTALK_DEMONICA_MASKE_18 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, Joker.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm. 夷Puedo quitarme el casco[n]en las Habitaciones seguras?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No es que pese... Es que[n]me da verg鵜enza...[n][w][e]

[msg DRESSTALK_DEMONICA_UNMAS_18 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Llevo un traje Demonica![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Me siento 茨gil, pero muy robusta![n]Tambi姻n conserva el calor,[n]pero deja pasar el aire.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Creo que lo usar姻 para practicar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero paso del casco.[n][w][e]

[msg DRESSTALK_PQ2_PC10 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Joker, 夷este traje qu姻 es?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me pesa la cabeza. 夷De verdad tengo[n]que llevar esto puesto?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡No me eches la culpa si pierdo el[n]equilibrio y te doy a ti![n][w][e]

