[msg e259_212_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2156 65535 0]Vale, lo intentar姻.[n]夷Estamos listos?[n][w][e]

[sel e259_212_selA top]
[s]Vamos.[e]
[s]Un segundo.[e]

[msg e259_212_selA_0_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2129 65535 0]Vale, silencio...[n][w][e]

[msg e259_212_selA_0_mes02 [Makoto]]
[s][bup 0 6 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sala de seguridad, 斡夷me recibe?![n]斡Al habla la sala de vigilancia![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Nos han atacado unos intrusos![n]斡Solicitamos refuerzos ahora mismo![n]斡Una persona ser胤a perfecto![n][w][e]

[msg e259_212_selA_0_mes03 [Sombra prudente]]
[s]斡Recibido! 斡Enviaremos[n]a alguien de inmediato![n][w][e]

[msg e259_212_selA_0_mes04 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2165 65535 0]斡Y ya est茨! Ahora solo tenemos[n]que esperar al enemigo.[n][w][e]

[msg e259_212_selA_1_mes01 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2090 65535 0]Entendido. Aseguraos de estar[n]preparados antes de decidir[n]seguir con esto.[n][w][e]

[msg e259_212_mes02 [Sombra prudente]]
[s]斡夷Qu姻?! 夷No hay nadie aqu胤...?[n][w][e]

[msg e259_212_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No exactamente.[n][w][e]

[msg e259_212_mes04 [Sombra prudente]]
[s]斡夷V-vosotros sois...?![n][w][e]

[msg e259_212_mes05 [Sombra prudente]]
[s]斡夷Era una trampa?! 斡Desgraciados![n][w][e]

