[msg D04_BRIEFING_050_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Tengo la sensaci吋n de que hemos[n]llegado bastante lejos.[n]夷Cu茨nto cre姻is que nos queda?[n][w][e]

[msg D04_BRIEFING_050_mes02 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Teniendo en cuenta la distancia[n]de la primera vez, dudo[n]que hayamos llegado a la mitad.[n][w][e]

[msg D04_BRIEFING_050_mes03 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por desgracia, pienso lo mismo.[n][w][e]

[msg D04_BRIEFING_050_mes04 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]Jol胤n, es verdad...[n]Se est茨 haciendo cuesta arriba.[n][w][e]

