[msg D01_BRIEFING_030_mes01 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6058 65535 0]Skull, 夷de qu姻 te r胤es?[n][w][e]

[msg D01_BRIEFING_030_mes02 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, de nada. Estaba pensando[n]en c吋mo hemos cruzado[n]los candelabros de antes.[n][w][e]

[msg D01_BRIEFING_030_mes03 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]夷No os sent胤s[n]como si fuerais ladrones de verdad?[n][w][e]

[msg D01_BRIEFING_030_mes04 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6022 65535 0]*suspiro* Sabes que todav胤a[n]nos falta mucho, 夷no?[n][w][e]

[msg D01_BRIEFING_030_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tiene raz吋n. Aunque seamos[n]optimistas, todav胤a nos[n]falta mucho camino por recorrer.[n][w][e]

[msg D01_BRIEFING_030_mes06 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, s胤... No os preocup姻is,[n]斡voy a seguir esforz茨ndome[n]al m茨ximo![n][w][e]

