[msg D159_03_KANBAN_mes01 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6127 65535 0]Este es el restaurante exclusivo[n]para miembros, 或Ristorante 畏lite位.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Aqu胤 hay algo escrito...[n][w][e]

[msg D159_03_KANBAN_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]或Restaurante exclusivo para[n]miembros. No se admitir茨 la entrada[n]a personas sin tarjeta de socio位.[n][w][e]

[msg D159_03_npc_01_mes01 [Invitado enmascarado]]
[s]Ah, por cierto, 夷has probado[n]aquel restaurante?[n][w][e]

[msg D159_03_npc_01_mes02 [Invitado enmascarado]]
[s]No, a雨n no. Me han dicho que un[n]famoso congresista lo ha[n]puesto por las nubes.[n][w][e]

[msg D159_03_npc_01_mes03 [Invitado enmascarado]]
[s]Ja, ja, ja, cierto. Ese ilustre[n]se隠or lo visita casi a diario.[n][w][e]

[msg D159_03_npc_02_mes01 [Invitado enmascarado]]
[s]Madre m胤a. Este barco es una[n]aut姻ntica maravilla.[n]Estoy m茨s que impresionado.[n][w][e]

[msg D159_03_npc_02_mes02 [Invitado enmascarado]]
[s]斡No me extra隠a que su estabilidad[n]sea excelente! A fin de cuentas,[n]es el barco de Shido.[n][w][e]

[msg D159_03_npc_02_mes03 [Invitado enmascarado]]
[s]Cierto... Habr姻 pasado dificultades[n]de joven, pero ahora puedo[n]disfrutar de una vida de placeres.[n][w][e]

[msg D07_02_e408_033_mes01 [Invitado enmascarado]]
[s]夷Eh? 夷Sucede algo? Te veo con[n]mucho menos carrete de lo habitual.[n][w][e]

[msg D07_02_e408_033_mes02 [Invitado enmascarado]]
[s]Ay, creo que se me ha ca胤do por[n]aqu胤 mi tarjeta de acceso[n]al restaurante.[n][w][e]

[msg D07_02_e408_033_mes03 [Invitado enmascarado]]
[s]Vaya, vaya. Pues no podr茨s entrar[n]a cenar sin ella. 夷Le has[n]preguntado al personal?[n][w][e]

[msg D07_02_e408_033_mes04 [Invitado enmascarado]]
[s]Ja, ja, a雨n no. No hay ning雨n[n]problema. Ya preguntar姻 luego[n]por las barras.[n][w][e]
[s]Conozco al se隠or Shido[n]personalmente y seguro que me[n]facilita otra si no la encuentro.[n][w][e]

[msg D07_02_e408_033_mes05 [Invitado enmascarado]]
[s]斡Anda, qu姻 bien! 斡No sab胤a que te[n]codeabas con las altas esferas![n]斡As胤 destilas tanta elegancia![n][w][e]

[msg D07_02_e408_033_mes06 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]斡Qu姻 pedazo de oportunidad tenemos![n]Ha dicho que se le ha ca胤do[n]la tarjeta de socio.[n][w][e]

[msg D07_02_e408_033_mes07 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No es que esto me entusiasme, pero[n]quiz茨 consigamos hacernos[n]con ella si la encontramos antes.[n][w][e]

[msg D07_02_e408_033_mes08 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7024 65535 0]斡Claro, co隠o! Si la ha perdido,[n]que se joda. 斡Para nosotros![n][w][e]

[msg D07_02_e408_033_mes09 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tambi姻n ha dicho que iba a[n]preguntar por las barras.[n]斡Lleguemos antes que 姻l![n][w][e]

[msg D07_02_e408_033_AF_mes01 [Invitado enmascarado]]
[s]Es una suerte que el se隠or Shido[n]te haya entregado personalmente[n]la tarjeta de socio.[n][w][e]

[msg D07_02_e408_033_AF_mes02 [Invitado enmascarado]]
[s]Ja, ja, ja, ya te digo. Se me[n]debe haber ca胤do en alg雨n sitio[n]cerca de las barras.[n][w][e]
[s]Les preguntar姻 a los camareros[n]si han encontrado[n]alg雨n objeto perdido.[n][w][e]

[msg D07_02_e408_033_AF_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1066 65535 0]Esta es la nuestra. 斡Vamos a[n]preguntar antes que 姻l![n][w][e]

[msg D159_03_npc_04_mes01 [Invitado enmascarado]]
[s]夷Conoces aquel restaurante[n]exclusivo? 夷C吋mo se podr茨 conseguir[n]la tarjeta de socio?[n][w][e]

[msg D159_03_npc_04_mes02 [Invitado enmascarado]]
[s]Ni la m茨s remota idea.[n][w][e]
[s]Mis contactos, si acaso, me han[n]procurado una plaza en el barco,[n]que ya es algo...[n][w][e]

[msg D159_03_npc_04_mes03 [Invitado enmascarado]]
[s]Me figuro que no somos m茨s que[n]parte del populacho comparados con[n]algunos de los dem茨s clientes.[n][w][e]
[s]Para empezar, quiz茨 debamos hasta[n]dar las gracias por poder cenar[n]en este bar.[n][w][e]

[msg D07_02_e408_022_mes01 [Invitado enmascarado]]
[s]夷Eh? Qu姻 raro...[n]夷D吋nde la habr姻 metido?[n][w][e]

[msg D07_02_e408_022_mes02 [Invitado enmascarado]]
[s]夷Qu姻 ocurre?[n][w][e]

[msg D07_02_e408_022_mes03 [Invitado enmascarado]]
[s]No, nada.[n]Estoy buscando una cosa.[n][w][e]

