[msg D157_005_miniEV_02_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]斡Ay, mierda![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No va a dejarnos pasar...[n]夷Qu姻 hacemos? 夷Atacamos?[n][w][e]

[msg D157_005_miniEV_02_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Siempre podr胤amos buscar[n]una ruta alternativa para rodearlo[n]y evitar el enfrentamiento.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 quieres hacer, Joker?[n]Haremos lo que decidas.[n][w][e]

[sel D157_005_miniEV_02_selA top]
[s]A por 姻l.[f 2 7 0 0 106 1][e]
[s]Mejor que no.[f 2 7 0 0 106 1][e]

[msg D157_005_miniEV_02_selA_ [Yusuke]]
[s][bup 0 5 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4021 65535 0]Pareces decidido a luchar...[n]斡Atravesaremos sus defensas![n][w][e]

[msg D157_005_miniEV_02_selA__2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Entendido. Si lo crees oportuno,[n]buscaremos otra forma de entrar.[n][w][e]

[msg D157_005_miniEV_02_02_me [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9133 65535 0]Esperad, 斡siento un enemigo[n]detr茨s de esa puerta![n][w][e]

[sel D157_005_miniEV_02_02_se top]
[s]Acabemos con 姻l.[f 2 7 0 0 106 1][e]
[s]Evit姻moslo.[f 2 7 0 0 106 1][e]

[msg D157_005_miniEV_02_02_se_2 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9196 65535 0]Lo conseguir姻is.[n]斡Har姻 todo lo posible para ayudaros![n][w][e]

[msg D157_005_miniEV_02_02_se_3 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9197 65535 0]El enemigo hace guardia[n]en el otro lado, as胤 que [clr 2]podr胤amos[n]emboscarlo[clr 27] desde aqu胤 si quer姻is.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]M茨s nos vale estar preparados,[n]que puede que sea la 雨nica opci吋n.[n][w][e]

[msg D157_005_miniEV_03_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Oye, que ha dejado caer algo...[n]夷No es una especie de tarjeta?[n][w][e]

[msg D157_005_miniEV_03_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiz茨 nos ayude a abrir algo[n]m茨s adelante. Ser茨 mejor[n]que la guardemos por ahora.[n][w][e]

[msg D157_005_miniEV_03_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pues demos gracias por haberla[n]encontrado y prosigamos.[n][w][e]

[msg D157_005_miniEV_03_mes04 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Oye, que ha dejado caer algo...[n]夷No es una especie de tarjeta?[n][w][e]

[msg D157_005_miniEV_03_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Bien visto! Puede que abra[n]la puerta con rejas.[n][w][e]

