[msg MSG_e296_311_000 [Yusuke]]
[s][bup 0 5 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4105 65535 0]Qu姻 formas tan maravillosas.[n]Ver estatuas tan excepcionales[n]en persona es todo un privilegio.[n][w][e]

[msg MSG_e296_311_001 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, si no estuvieses en un Palacio,[n]no estar胤as contemplando cosas as胤.[n][w][e]

[msg MSG_e296_311_002 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La verdad es que parece que estemos[n]de viaje por el extranjero.[n][w][e]

[msg MSG_e296_311_003 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, 斡no es momento de bajar[n]la guardia! 斡Me da que hay[n]muchas sombras m茨s adelante![n][w][e]

