[msg fev0409_01_mes01]
[s]四軒茶屋のアナウンスを聞いたあと[n]自動で階段を上っていく。[n][w][e]

[msg fev0409_01_greet]
[s]Yongen-Jaya. Esto es Yongen-Jaya.[n][w][e]

[msg fev0409_02_mes01]
[s]As胤 que este lugar es [clr 2]Yongen-Jaya[clr 27]...[n][w][e]

[msg fev0409_02_mes02]
[s]La direcci吋n a la que me dirijo[n]est茨 un poco m茨s adelante.[n][w][e]

[msg fev0409_03_mes01]
[s]路地裏を見せる絵[n][w][e]

[msg fev0409_03_mes02]
[s]イベントキーフリー開始[n][w][e]

[msg fev0411_02_mes01]
[s]Tengo que coger la [clr 2]l胤nea Ginza[clr 27][n]para llegar a mi instituto,[n]que est茨 en Aoyama-Itchome.[n][w][e]

[msg fev0411_03_mes01]
[s]Esto es [clr 2]Aoyama-Itchome[clr 27]...[n][w][e]
[s]He tardado un rato, pero[n]al fin he llegado.[n][w][e]

[msg MSG_CATBED_01 [Morgana]]
[s][bup 0 3 0 0 0]斡Ah, acabo de caer...![n][w][e]
[s]夷No hab胤as comprado una cama para[n]gatos? Aunque era de segunda mano.[n][w][e]
[s]Bueno, da igual.[n]斡Decidamos d吋nde vamos a ponerla![n][w][e]

[msg MSG_CATBED_SET_1ST_01 [Morgana]]
[s][bup 0 3 0 0 0]夷Qu姻 te parece este magn胤fico[n]lugar? 斡Justo en el medio[n]de la habitaci吋n![n][w][e]

[sel SEL_CATBED_SET_1ST top]
[s]Ni de co隠a.[e]
[s]夷Lo dices en serio?[e]

[msg MSG_CATBED_SET_1ST_02 [Morgana]]
[s][bup 0 3 0 0 0]Era broma, no te preocupes.[n]Ah胤 estorbar胤a, 夷no?[n][w][e]

[msg MSG_CATBED_SET_1ST_03 [Morgana]]
[s][bup 0 3 0 0 0]斡Claro que s胤! Aunque... imagino[n]que te molestar胤a cuando pasases.[n][w][e]

[msg MSG_CATBED_SET_1ST_LAST [Morgana]]
[s][bup 0 3 0 0 0]夷Y qu姻 te parece aqu胤?[n][w][e]

[msg MSG_CATBED_SET_2ND_01 [Morgana]]
[s][bup 0 3 0 0 0]Tendr姻 una gran vista[n]de la habitaci吋n, y no tendr姻 que[n]preocuparme por el polvo del suelo.[n][w][e]

[sel SEL_CATBED_SET_2ND top]
[s]No lo veo...[e]
[s]夷Qu姻 clase de broma es esta?[e]

[msg MSG_CATBED_SET_2ND_02 [Morgana]]
[s][bup 0 3 0 0 0]夷No te convence? Pensaba que era[n]buena idea... Aunque no podr胤as usar[n]el sof茨 si la pusi姻ramos ah胤.[n][w][e]

[msg MSG_CATBED_SET_2ND_03 [Morgana]]
[s][bup 0 3 0 0 0]Ja, ja, ja, 斡claro que s胤![n]O sea, no podr胤as usar el sof茨[n]si la pusi姻ramos ah胤, 夷verdad?[n][w][e]

[msg MSG_CATBED_SET_2ND_LAST [Morgana]]
[s][bup 0 3 0 0 0]Mm, est茨 siendo m茨s dif胤cil[n]de lo que esperaba... Pero seguro que[n]la siguiente idea ser茨 la 雨ltima.[n][w][e]

[msg MSG_CATBED_SET_3RD_01 [Morgana]]
[s][bup 0 3 0 0 0]Vale, 斡夷y aqu胤?![n][w][e]
[s]No te estorbar姻. Adem茨s,[n]te sentir茨s m茨s seguro[n]si duermo cerca de ti.[n][w][e]

[sel SEL_CATBED_SET_3RD top]
[s]Suena bien.[e]
[s]No s姻...[e]

[msg MSG_CATBED_SET_3RD_02 [Morgana]]
[s][bup 0 3 0 0 0]斡S胤, creo que este lugar es el mejor![n][w][e]

[msg MSG_CATBED_SET_3RD_03 [Morgana]]
[s][bup 0 3 0 0 0]斡Se siente, la decisi吋n ya[n]est茨 tomada! La cama ir茨 aqu胤.[n][w][e]

[msg MSG_CATBED_SET_END [Morgana]]
[s][bup 0 3 0 0 0]Por fin tengo mi propia cama...[n]Ya no tendr姻 que volver[n]a dormir encima de...[n][w][e]
[s]E-Es decir, 斡ja, ja, ja![n]斡Nunca he hecho nada as胤![n][w][e]

