[msg mini_EV_e210_146_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]O-oye, aqu胤 hay uno con pinta de[n]forzudo... Ya hemos visto alguno as胤.[n][w][e]

[msg mini_EV_e210_146_mes02 [Yusuke]]
[s][bup 0 5 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Su porte y postura sugieren que[n]no ser茨 una batalla cualquiera.[n][w][e]

[msg mini_EV_e210_146_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Creo que la sala de control est茨[n]detr茨s. Es probable que est姻[n]vigilando que nadie se acerque.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]Pero, si queremos[n]contar con una ruta segura,[n]hay que desactivar los sistemas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Creo que tendremos[n]que abrirnos paso a la fuerza.[n][w][e]

[msg mini_EV_e210_146_mes04 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]夷Estamos listos?[n][w][e]

[sel mini_EV_e210_146_selB top]
[s]Vamos.[e]
[s]Necesito prepararme.[e]

[msg mini_EV_e210_146_mes05 [Sombra de seguridad]]
[s][vp 1 0 0 7 0 0]斡夷Eh?! 斡夷Y vosotros qui姻nes sois?![n]斡夷C吋mo hab姻is entrado?![n][w][e]

[sel mini_EV_e210_146_selA top]
[s]Ap茨rtate.[e]
[s]Tampoco ha sido para tanto.[e]

[msg mini_EV_e210_146_selA_0_ [Sombra de seguridad]]
[s][vp 1 0 0 8 0 0]斡夷Esper茨is que me mueva[n]porque me lo orden茨is?![n]Est茨is muy equivocados.[n][w][e]

[msg mini_EV_e210_146_selA_1_ [Sombra de seguridad]]
[s][vp 1 0 0 9 0 0]斡Pues esto no va a ser tan f茨cil![n][w][e]

[msg mini_EV_e210_146_mes06 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]Buf, ese t胤o iba en serio...[n]Bueno, es lo que tienen los Palacios.[n][w][e]

[msg mini_EV_e210_146_mes07 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Estaba bastante por encima[n]de los dem茨s, la verdad.[n][w][e]

[msg mini_EV_e210_146_mes08 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Mm, se le ha ca胤do[n]una especie de tarjeta.[n][w][e]

[msg mini_EV_e210_146_mes09 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]夷Y esto para qu姻 sirve?[n]Nunca hab胤a visto nada igual.[n][w][e]

[msg mini_EV_e210_146_mes10 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]夷No ser茨 un bot胤n sin m茨s?[n]Venga, a seguir explorando.[n][w][e]

