[msg D07_01_e407_024_mes01 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9040 65535 0]Joker, 斡un enemigo![n][w][e]

[msg D07_01_e407_024_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uf, 斡夷es que piensa atacarnos con[n]toda esta gente alrededor?![n][w][e]

[msg D07_01_e407_025_mes01 [Invitado enmascarado]]
[s][vp 1 0 0 1 0 0]Ah, pero 夷esto es un espect茨culo?[n]斡El se隠or Shido siempre[n]tan atento con sus invitados![n][w][e]

[msg D07_01_e407_025_mes02 [Invitado enmascarado]]
[s][vp 1 0 0 2 0 0]斡Ya lo creo! 斡Los privilegiados que[n]han podido subir al barco est茨n[n]de aut姻ntica enhorabuena![n][w][e]

[msg D07_01_e407_025_mes03 [Invitado enmascarado]]
[s][vp 1 0 0 3 0 0]斡Ja, ja, ja, ja, ja![n][w][e]

[msg D07_01_e407_025_mes04 [Invitado enmascarado]]
[s][vp 1 0 0 4 0 0]斡Ja, ja, ja, ja![n][w][e]

[msg D07_01_e407_025_mes05 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]夷De qu姻 va toda esta gente?[n]夷No se sienten amenazados despu姻s[n]de lo que acaban de presenciar?[n][w][e]

[msg D07_01_e407_025_mes06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Parece que piensan que est茨n a salvo[n]de todo da隠o por estar[n]en el barco de Shido.[n][w][e]

[msg D07_01_e407_025_mes07 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]Ni siquiera notan el peligro...[n]斡Vamos, demostr姻mosles[n]la verdadera naturaleza de este barco![n][w][e]

