[msg CRAFTWORK_HELP [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]Yo pongo los materiales[n]esta vez. Intenta hacer[n][f 2 5 3 9999 0].[n][w][e]

[msg CRAFTWORK_START [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]No le des muchas vueltas.[n]Ya lo pillar茨s.[n][w][e]

[msg MSG_ToolMake_START_Gogo [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Como hoy est茨s libre,[n]deber胤as tener m茨s tiempo[n]para fabricar herramientas.[n][w][e]

[msg MSG_ToolMake_START_BadWe [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Hoy hace un tiempo de perros, pero es[n]m茨s f茨cil hacer herramientas de[n]infiltraci吋n cuando no puedes salir.[n][w][e]

[msg TOOLWIN_MAKE_END_FIRST [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]斡Genial! Esto podr胤amos usarlo.[n][w][e]

[msg TOOLWIN_MAKE_ONEMORE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]A este paso, deber胤as[n]poder fabricar una m茨s.[n][w][e]

[msg TOOLWIN_MAKE2_ONEMORE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]Todav胤a puedes fabricar m茨s.[n]夷Qu姻 vas a hacer?[n][w][e]

[msg TOOLWIN_MAKE3_ONEMORE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]斡Qu姻 bien te ha salido esa![n]Ya lo vas pillando.[n][w][e]
[s][f 4 10 65535 0 0]夷No est茨s cansado? 夷Quieres seguir?[n][w][e]

[sel TOOLWIN_CONTINUE_SEL top]
[s]Seguir[e]
[s]Parar ya[e]

[msg MSG_LAST_Message_end [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1034 65535 0]Est茨s mejorando mucho.[n]Lo s姻 solo con mirarte.[n][w][e]

[msg MSG_LAST_Message_end_SP [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 1045 65535 0]Te he visto.[n]Qu姻 habilidad con las manos...[n]斡Lo has hecho genial![n][w][e]

[msg MND_LAST_Message_end]
[s]Creo que estoy mejorando.[n][w][e]

[msg MSG_LAST_Message_0417 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Creo que estamos preparados.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]Ma隠ana vamos al Palacio.[n]Es hora de descansar.[n][w][e]

[msg MSG_LAST_Message [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0]斡Venga, a dormir![n][w][e]

[msg MSG_LAST_Message_Hiru [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Est茨s cansado, 夷verdad?[n]Durmamos un poco.[n][w][e]

[msg MND_LAST_Message]
[s]Se ha hecho tarde...[n]Deber胤a descansar.[n][w][e]

[msg MND_LAST_Message_Hiru]
[s]Deber胤a descansar.[n][w][e]

[msg MSG_KawakamiWorkInfo [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1185 65535 0]Podr胤as pedirle a Kawakami[n]que fabrique una, pero quiz茨[n]solo pueda hacer un tipo.[n][w][e]

[msg MSG_KawakamiWorkInfo_Day [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Solo puedes pedir ayuda a Kawakami[n]por la noche. Plan姻alo todo[n]bien antes de actuar, 夷vale?[n][w][e]

[msg MSG_DOUGUDUKURI_PLAYPARA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Creo que ya puedes fabricar[n][var 0]. Buena suerte.[n][w][e]

[msg MSG_DOUGUDUKURI_PLAYPARA_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]斡Has le胤do ese libro y ya[n]le has cogido el truco, as胤 que[n]quiz茨 puedas fabricar [var 0]![n][w][e]

[msg MSG_DOUGUDUKURI_PLAYPARA_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Gracias a las herramientas[n]que compraste en Akihabara, creo[n]que ya puedes fabricar [var 0].[n][w][e]

[msg MSG_DOUGUDUKURI_PLAYPARA_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Has le胤do el libro y comprado[n]las herramientas. 斡Creo que ya[n]puedes fabricar [var 0]![n][w][e]

