[msg e382_310_mes01 [Comentarista del ring]]
[s][vp 1 0 0 1 0 0]Atenci吋n, 斡la apasionante batalla[n]por fin comienza! El liderucho[n]de los ni隠atos ladrones ha llegado.[n][w][e]
[s][vp 1 0 0 2 0 0]Las probabilidades de ganar[n]son de 1,1 para la casa[n]y de 23 para los Ladrones Fantasma.[n][w][e]
[s][vp 1 0 0 3 0 0]斡Pues s胤 que son populares![n]Es muy extra隠o ver dos d胤gitos[n]en las probabilidades.[n][w][e]

[msg e382_310_mes02 [Comentarista del ring]]
[s][vp 1 0 0 4 0 0]Que comience el combate[n]uno contra uno.[n]斡Recibamos al primer participante![n][w][e]

[msg e382_310_mes03 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]Pero 斡夷qu姻 cojones?! 斡Si hay dos![n][w][e]

[msg e382_310_mes04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]斡Eso no es uno contra uno![n]斡Se est茨n saltando las reglas[n]desde el principio![n][w][e]

[msg e382_310_mes05 [Comentarista del ring]]
[s][vp 1 0 0 7 0 0]斡Nuestro triplete de combates va[n]a comenzar! Preparados, listos... 斡ya![n][w][e]

