[msg MSG_NET_1ST_01 [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Je, je, je... 斡Bienvenido[n]al atractivo mundo de[n]Art胤culos sospechosos Tanaka![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Esta web funciona[n]con reconocimiento de voz[n]para que comprar sea m茨s f茨cil![n][w][e]

[msg MSG_YamiNet_TutorialEnd [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Deja de lado las dudas[n]y los prejuicios y reg胤strate ya![n][w][e]

[msg MSG_NET_1ST_02 [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Bienvenido! 斡Est茨s en[n]Art胤culos sospechosos Tanaka![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Crea una cuenta para poder[n]disfrutar del atractivo mundo[n]de Art胤culos sospechosos Tanaka.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Deja de lado las dudas[n]y los prejuicios y reg胤strate ya![n][w][e]

[msg MSG_YamiNet_MemberQ [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]Esta web es un poco turbia...[n]夷Te vas a registrar?[n][w][e]

[msg MND_YamiNet_MemberQ]
[s]夷Deber胤a crear una cuenta?[n][w][e]

[sel SEL_NET_1ST_YES_NO top]
[s]Voy a registrarme.[e]
[s]Mejor no.[e]

[msg MSG_NET_1ST_NO [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Vaya, qu姻 verg鵜enza! 斡Qu姻 pena![n]斡Pero vuelve otra vez![n][w][e]

[msg MSG_NAME_CHANGE_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 22 65535 3 22]夷Te parece bien usar tu nombre[n]real en una p茨gina as胤?[n][w][e]

[sel SEL_NAME_CHANGE_ON_OFF_M top]
[s]Est茨 bien.[e]
[s]Usar姻 或Joker位.[e]

[msg MSG_NAME_CHANGE_02 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]No s姻. Usar un nombre real en esta[n]p茨gina me parece bastante[n]arriesgado, pero como quieras.[n][w][e]

[msg MSG_NAME_CHANGE_03 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Tu nombre en clave?[n]Bien pensado.[n][w][e]

[msg MSG_NAME_CHANGE_ON_01]
[s][vp 8 2 1 0 65535 0]夷Con qu姻 nombre me registro?[n][w][e]

[sel SEL_NAME_CHANGE_ON_OFF top]
[s]Usar姻 mi nombre real.[e]
[s]Me pondr姻 或Joker位.[e]

[msg MSG_NET_1ST_SHOP [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Gracias por registrarte![n]斡Bienvenido a Art胤culos[n]sospechosos Tanaka![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡[f 4 1], has abierto la puerta a[n]un mundo de posibilidades con las[n]que la gente normal solo sue隠a![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Ahora podr茨s encontrar todos[n]los objetos raros que quieras![n][w][e]

[msg MSG_NET_1ST_SHOP_NAME_CH [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Gracias por registrarte![n]斡Bienvenido a Art胤culos[n]sospechosos Tanaka![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Joker, has abierto la puerta a[n]un mundo de posibilidades con las[n]que la gente normal solo sue隠a![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Ahora podr茨s encontrar todos[n]los objetos raros que quieras![n][w][e]

[msg MSG_NET_SHOP_IN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Bienvenido! 斡Est茨s en[n]Art胤culos sospechosos Tanaka![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡[f 4 1], has abierto la puerta a[n]un mundo de posibilidades con las[n]que la gente normal solo sue隠a![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Ahora podr茨s encontrar todos[n]los objetos raros que quieras![n][w][e]

[msg MSG_NET_SHOP_IN_NAME_CHA [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Bienvenido! 斡Est茨s en[n]Art胤culos sospechosos Tanaka![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Joker, has abierto la puerta a[n]un mundo de posibilidades con las[n]que la gente normal solo sue隠a![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Ahora podr茨s encontrar todos[n]los objetos raros que quieras![n][w][e]

[msg MSG_NET_NO_BUY_END_YN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Se te ha pasado comprar algo?[n]斡Que no se te olvide nada![n][w][e]

[sel SEL_NET_BUY_YES_NO top]
[s]Cancelar compra[e]
[s]Seguir mirando[e]

[msg MSG_TRANSPORT [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Bienvenido! 斡Est茨s en[n]Art胤culos sospechosos Tanaka![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tu pedido est茨 en camino.[n]No deber胤a tardar mucho en llegar.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Esperamos volver a verte pronto![n][w][e]

[msg MSG_SOLDOUT [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Bienvenido! 斡Est茨s en[n]Art胤culos sospechosos Tanaka![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡No nos queda nada ahora mismo![n]Lo sentimos much胤simo.[n]斡Lamentamos decepcionarte![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Esperamos volver a verte pronto![n][w][e]

[msg MSG_RANK_UP_00 [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Buenas noticias, [f 4 1]![n][w][e]

[msg MSG_RANK_UP_00_NAME_CHAN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Buenas noticias, Joker![n][w][e]

[msg MSG_RANK_BLACK [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Ya has gastado[n]m茨s de 10 000 yenes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Tu rango de miembro es Negro![n]斡Ahora puedes comprar todos[n]los productos de rango Negro![n][w][e]

[msg MSG_RANK_BLACK_NAME_CHAN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Ya has gastado[n]m茨s de 10 000 yenes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Tu rango de miembro es Negro![n]斡Ahora puedes comprar todos[n]los productos de rango Negro![n][w][e]

[msg MSG_RANK_UP_01 [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Y eso no es todo![n][w][e]

[msg MSG_RANK_DARK [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Has gastado m茨s de 50 000 yenes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Tu rango de miembro es Oscuro![n]斡Ahora puedes comprar todos[n]los productos de rango Oscuro![n][w][e]

[msg MSG_RANK_DARK_NAME_CHANG [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Has gastado m茨s de 50 000 yenes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Tu rango de miembro es Oscuro![n]斡Ahora puedes comprar todos[n]los productos de rango Oscuro![n][w][e]

[msg MSG_RANK_UP_02 [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero 斡todav胤a hay m茨s![n][w][e]

[msg MSG_RANK_CHAOS [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Has gastado m茨s de 100 000 yenes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Tu rango de miembro es Ca吋tico![n]斡Ahora puedes comprar todos[n]los productos de rango Ca吋tico![n][w][e]

[msg MSG_RANK_CHAOS_NAME_CHAN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Has gastado m茨s de 100 000 yenes![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Tu rango de miembro es Ca吋tico![n]斡Ahora puedes comprar todos[n]los productos de rango Ca吋tico![n][w][e]

[msg MSG_RANK_Max [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Has llegado al rango de miembro m茨s[n]alto, as胤 que aqu胤 tienes todos[n]los productos. 斡Muchas gracias![n][w][e]

[msg MSG_NO_RANK_UP [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Llevas gastado un total[n]de [var 0] yenes![n][w][e]

[msg MSG_NO_RANK_UP_NAME_CHAN [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Llevas gastado un total[n]de [var 0] yenes![n][w][e]

[msg MSG_SHOP_BUY [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Tu pedido llegar茨 pronto.[n]斡Sabemos que tienes ganas[n]de recibirlo, pero s姻 paciente![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Esperamos volver a verte pronto![n][w][e]

[msg MSG_SHOP_END [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Esperamos volver a verte pronto![n][w][e]

[msg MSG_Kokuti_1GATU [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Se va a proceder al mantenimiento[n]de los servidores el d胤a 31/01[n]y estaremos fuera de servicio.[n][w][e]

[msg MSG_Kokuti_Saigo [Tanaka]]
[s][bup 0 210 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Se va a proceder al mantenimiento[n]de los servidores ma隠ana, 31/01,[n]y estaremos fuera de servicio.[n][w][e]

[msg MSG_Yami_Siyouhuka [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1165 65535 0]或Mantenimiento de los servidores位.[n]Parece que no podremos usar[n]la web.[n][w][e]

