[msg QUEST_57_ENTER_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Conque esa es la sombra[n]del jefe de Ohya, la periodista.[n][w][e]

[msg QUEST_57_ENTER_mes01f [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah, es la sombra del jefe[n]de Ohya, la periodista.[n][w][e]

[msg QUEST_57_ENTER_mes02 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]No me da ninguna confianza.[n][w][e]

[msg QUEST_57_ENTER_mes03 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Bueno, es que est茨 obstruyendo[n]una investigaci吋n period胤stica[n]para ocultar no s姻 qu姻 incidente.[n][w][e]

[msg QUEST_57_ENTER_mes04 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Hasta hubo muertos. Deber胤a[n]darle verg鵜enza catalogarse[n]como periodista.[n][w][e]

[msg QUEST_57_ENTER_mes05 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6101 65535 0]斡Hay que conseguir[n]que reconozca la verdad![n][w][e]

[msg MSG_000_0_0 [Sombra de Honjo]]
[s][vp 8 2 1 46703 65535 0]T雨... T雨 eres el chaval[n]que iba con Ohya, 夷no?[n][w][e]
[s][vp 1 0 0 0 0 0]Que os den. Mira que husmear[n]por ah胤 todos juntitos, meti姻ndoos[n]donde no os llaman...[n][w][e]
[s][vp 1 0 0 0 0 0]斡夷Y si ahora los de arriba[n]se fijan en lo que hago yo?![n]斡Dejad de entremeteros![n][w][e]

[sel SEL_001_0_0 top]
[s]夷D吋nde ha quedado el periodismo?[e]
[s]斡Libera a Ohya![e]

[msg MSG_002_0_0 [Sombra de Honjo]]
[s][vp 1 0 0 0 0 0]斡No vayas de listo, chaval![n][w][e]

[msg MSG_003_0_0 [Sombra de Honjo]]
[s][vp 1 0 0 0 0 0]斡Ser胤a mejor para la organizaci吋n[n]no estar cerca de rebeldes as胤![n][w][e]

[msg MSG_004_0_0 [Sombra de Honjo]]
[s][vp 8 2 1 46701 65535 0]No debes tenerle mucho aprecio[n]a tu vida si te me encaras as胤.[n]斡Obedece si quieres vivir![n][w][e]

[msg MSG_005_0_0 [Sombra de Honjo]]
[s][vp 8 2 1 46715 65535 0]斡Hostia puta![n]夷Qu姻 quer胤ais que hiciera?[n][w][e]
[s][vp 1 0 0 0 0 0]No puedo enfrentarme a los jefes.[n]Es m茨s f茨cil no agitar las aguas.[n][w][e]
[s][vp 1 0 0 0 0 0]Los medios de comunicaci吋n solo son[n]empresas, el periodismo de verdad[n]no da ni para pipas.[n][w][e]
[s][vp 1 0 0 0 0 0]No sirve de nada perseguir[n]unos ideales...[n][w][e]

[sel SEL_006_0_0 top]
[s]No, Ohya no es as胤.[e]
[s]夷Seguro que no sirve de nada?[e]

[msg MSG_007_0_0 [Sombra de Honjo]]
[s][vp 1 0 0 0 0 0]Es una chica incre胤ble.[n][w][e]
[s][vp 1 0 0 0 0 0]Da igual lo que digan los dem茨s,[n]no escatima en esfuerzos[n]para dar con la verdad.[n][w][e]

[msg MSG_008_0_0 [Sombra de Honjo]]
[s][vp 1 0 0 0 0 0]Puede que para Ohya no.[n][w][e]
[s][vp 1 0 0 0 0 0]Da igual lo que digan los dem茨s,[n]no escatima en esfuerzos[n]para dar con la verdad.[n][w][e]

[msg MSG_009_0_0 [Sombra de Honjo]]
[s][vp 1 0 0 0 0 0]Su pasi吋n infantil puede ser[n]agobiante, lo que me recuerda[n]todo el dolor del pasado.[n][w][e]
[s][vp 1 0 0 0 0 0]Un pasado anterior a mi rendici吋n,[n]a mi p姻rdida de inspiraci吋n[n]y a que mi mujer se fuera con otro...[n][w][e]

[msg MND_010_0_0]
[s][vp 1 0 0 0 0 0]La sombra de Honjo ha desaparecido.[n]Deber胤a ir a ver a Ohya.[n][w][e]

