[msg MSG_D155_03_c_02_000 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, este no tiene[n]ning雨n panel de control.[n][w][e]

[msg MSG_D155_03_c_02_001 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero tiene esa cosa roja[n]flotando encima. 夷Crees que[n]ser茨 especial de alg雨n modo?[n][w][e]

[msg MSG_D155_03_c_02_002 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Esto debe de tener alg雨n sentido.[n]La 或A位 del c吋digo significaba[n]azul, as胤 que esto ser茨...[n][w][e]

[msg D155_03_c_01_AF_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No creo que haya ning雨n motivo[n]para que usemos esto ahora.[n]Vamos a investigar a otro sitio.[n][w][e]

