[msg D08_01_e446_055_mes01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1159 65535 0]Ah胤 abajo nos aguardan las[n]profundidades de Mementos...[n]夷Listo para el descenso, Joker?[n][w][e]

[sel D08_01_e446_055_selA top]
[s]Vamos.[e]
[s]Esperad.[e]

[msg D08_01_e446_055_selA_1_m [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1034 65535 0]S胤, es mejor que nos preparemos[n]para lo que nos espere ah胤 abajo.[n][w][e]

