[msg D151_04_miniEV01_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7021 65535 0]A ver... 或La historia de Kamoshida位...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]或Tras los pasos de Kamoshida位...[n]或Las heroicidades de Kamoshida位...[n]夷或La ley de Kamoshida位...?[n][w][e]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 斡夷qu姻 co隠o...?! 斡Todos los[n]putos libros hablan de Kamoshida![n][w][e]

[msg D151_04_miniEV01_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1158 65535 0]Eso me recuerda... 夷No hemos[n]encontrado un libro antes?[n][w][e]

[sel D151_04_miniEV01_selA top]
[s]夷Crees que puede haber relaci吋n?[e]
[s]Vamos a probar a meterlo.[e]

[msg D151_04_miniEV01_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1157 65535 0]S胤, si ponemos un libro aqu胤,[n]puede que pase algo.[n][w][e]

[sel D151_04_miniEV01_selB top]
[s]Introducir 或El libro del rey位[e]
[s]Introducir 或El libro de la reina位[e]
[s]Introducir 或El libros de los esclavos位[e]
[s]Introducir 或El libro de los cachas位[e]
[s]Ignorar de momento[e]

[msg D151_04_miniEV01_ng_book [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1001 65535 0]Uy... Ese parece demasiado peque隠o.[n]No encaja tan bien como los dem茨s.[n][w][e]

[msg D151_04_miniEV01_re_mes0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1133 65535 0]Parece que esta estanter胤a est茨[n]llena de libros sobre Kamoshida.[n][w][e]

[msg D151_04_miniEV01_recover [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1185 65535 0]夷Eh? 夷Lo vas a sacar?[n][w][e]

[sel D151_04_miniEV01_selC top]
[s]S胤.[e]
[s]Mejor que no.[e]

[msg D151_04_miniEV01_recover_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]S胤, probar a ordenar los libros[n]de formas diferentes es buena idea.[n]Bueno, 夷ahora qu姻?[n][w][e]

[msg D151_04_miniEV01_none_me [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6155 65535 0]Oh... Oye, aqu胤 hay un hueco[n]donde cabe otro libro.[n][w][e]

[msg D151_04_miniEV02_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6165 65535 0]Aqu胤 hay un mont吋n de libros[n]diferentes... Los t胤tulos no tienen[n]ni pies ni cabeza.[n][w][e]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Eh? Este libro... lleva el nombre[n]de Shiho en el t胤tulo...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un momento... 斡No es solo este![n]斡Todos los libros que hay aqu胤[n]son sobre alumnas...![n][w][e]

[msg D151_04_miniEV02_mes02 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]或Ann Takamaki: la mu隠eca[n]encantadora位. La madre...[n][w][e]

[msg D151_04_miniEV02_mes03 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6190 65535 0]斡夷Qu姻 narices es esto...?![n][w][e]

[msg D151_04_miniEV02_mes04 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7158 65535 0]Oye, antes hemos[n]encontrado un libro, 夷no?[n]夷No es buen momento para usarlo?[n][w][e]

[sel D151_04_miniEV02_selA top]
[s]夷Usarlo...?[e]
[s]Voy a colocarlo.[e]

[msg D151_04_miniEV02_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]S胤, puede que pase algo[n]si ponemos un libro[n]en este estante...[n][w][e]

[sel D151_04_miniEV02_selB top]
[s]Introducir 或El libro del rey位[e]
[s]Introducir 或El libro de la reina位[e]
[s]Introducir 或El libros de los esclavos位[e]
[s]Introducir 或El libro de los cachas位[e]
[s]Ignorar de momento[e]

[msg D151_04_miniEV02_ng_book [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7192 65535 0]Oye, ese libro es m茨s peque隠o de la[n]cuenta, 夷no? Queda algo de espacio,[n]夷lo ves?[n][w][e]

[msg D151_04_miniEV02_re_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7038 65535 0]En esta estanter胤a no hay m茨s[n]que libros de alumnas...[n][w][e]

[msg D151_04_miniEV02_recover [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7088 65535 0]夷Eh? 夷Lo vas a sacar?[n][w][e]

[sel D151_04_miniEV02_selC top]
[s]S胤.[e]
[s]Mejor que no.[e]

[msg D151_04_miniEV02_recover_2 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7186 65535 0]Venga, vale. Probemos otra cosa.[n][w][e]

[msg D151_04_miniEV02_none_me [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1159 65535 0]Jum... Parece que entre[n]esos libros cabe uno m茨s...[n][w][e]

[msg D151_04_miniEV03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1171 65535 0]Mm... Un segundo. Los libros de esta[n]estanter胤a me resultan familiares.[n][w][e]

[msg D151_04_miniEV03_mes02 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Son los nombres de los miembros[n]del equipo de voleibol![n][w][e]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡No jodas! 斡Los t胤tulos son todo[n]nombres de pe隠a del instituto![n][w][e]

[msg D151_04_miniEV03_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]或Ryuji Sakamoto: el simio vulgar位.[n]Este es el de Skull.[n][w][e]

[msg D151_04_miniEV03_mes04 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]斡夷Qui姻n co隠o se cree[n]el capullo ese?![n][w][e]

[msg D151_04_miniEV03_mes05 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6157 65535 0]Oye, 夷no hemos encontrado[n]un libro antes? 夷Qu姻 tal si...?[n][w][e]

[sel D151_04_miniEV03_selA top]
[s]夷Qu姻 tal si qu姻?[e]
[s]Pong茨moslo en la estanter胤a.[e]

[msg D151_04_miniEV03_mes06 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6035 65535 0]S胤, puede que cambie algo[n]si lo ponemos en la estanter胤a.[n][w][e]

[sel D151_04_miniEV03_selB top]
[s]Introducir 或El libro del rey位[e]
[s]Introducir 或El libro de la reina位[e]
[s]Introducir 或El libros de los esclavos位[e]
[s]Introducir 或El libro de los cachas位[e]
[s]Ignorar de momento[e]

[msg D151_04_miniEV03_ng_book [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6118 65535 0]夷Ese libro no es un pel胤n peque隠o?[n]Hay un huequito ah胤.[n][w][e]

[msg D151_04_miniEV03_re_mes0 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6127 65535 0]Los libros de esta estanter胤a[n]van sobre los alumnos varones[n]del instituto...[n][w][e]

[msg D151_04_miniEV03_recover [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6001 65535 0]夷Vas a sacar el libro?[n][w][e]

[sel D151_04_miniEV03_selC top]
[s]S胤.[e]
[s]Mejor que no.[e]

[msg D151_04_miniEV03_recover_2 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6108 65535 0]斡Suena bien! Probemos otro orden.[n][w][e]

[msg D151_04_miniEV03_none_me [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]Pero 斡夷qu姻...?![n]Parece que falta un libro.[n][w][e]

[msg D151_04_miniEV06_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7183 65535 0]夷Eh? 夷Has encontrado algo?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]或M雨sculos divinos位...[n]或M雨sculos de machote位... [n][w][e]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7119 65535 0]Madre m胤a, todos van de lo mismo.[n]Ese t胤o est茨 obsesionado[n]con sus m雨sculos...[n][w][e]

[msg D151_04_miniEV06_mes02 [Ann]]
[s][bup 0 4 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6197 65535 0]Qu姻 asco.[n][w][e]

[sel D151_04_miniEV06_selB top]
[s]Introducir 或El libro del rey位[e]
[s]Introducir 或El libro de la reina位[e]
[s]Introducir 或El libros de los esclavos位[e]
[s]Introducir 或El libro de los cachas位[e]
[s]Ignorar de momento[e]

[msg D151_04_miniEV06_choice_ [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7088 65535 0]夷Vas a poner ese libro ah胤?[n][w][e]

[msg D151_04_miniEV06_choice__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1171 65535 0]夷Vas a poner ese libro ah胤?[n][w][e]

[msg D151_04_miniEV06_choice__3 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm... Me pregunto si habr茨[n]alguno por aqu胤 que encaje bien. [n][w][e]

[msg D151_04_miniEV06_re_mes0 [Ryuji]]
[s][bup 0 2 107 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7106 65535 0]Anda, la estanter胤a de musculaci吋n...[n][w][e]

[msg D151_04_miniEV06_none_me [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1171 65535 0]Parece que aqu胤[n]tambi姻n falta un libro.[n][w][e]

[msg D151_04_miniEV07_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7174 65535 0]夷Eh? 夷Ese no va ah胤?[n][w][e]

[msg D151_04_miniEV07_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6166 65535 0]Igual hay algo en ese espacio.[n]夷Por qu姻 no tratas de llegar[n]hasta ah胤, Skull?[n][w][e]

[msg D151_04_miniEV07_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Eh! 斡Aqu胤 hay algo![n]All茨 vamos.[n][w][e]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Genial. Toma, qu姻datelo.[n][w][e]

[msg D151_04_miniEV07_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1175 65535 0]No hay ning雨n interruptor secreto,[n]pero hemos conseguido algo 雨til...[n]斡Para m胤, ha sido un 姻xito![n][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Menci吋n especial para Joker[n]por haber explorado todos[n]los rincones de la sala![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Sigue as胤 mientras avanzamos[n]por el Palacio, 夷vale? 斡Y[n]ahora, de vuelta a la infiltraci吋n![n][w][e]

[msg D151_04_miniEV08_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6139 65535 0]Creo que ese libro no cabe ah胤.[n][w][e]

[msg D151_04_miniEV08_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tiene que ser un poco m茨s peque隠o,[n]夷no? 夷Tenemos libros de ese tama隠o?[n][w][e]

[msg D151_04_miniEV08_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6127 65535 0]Necesitamos un libro m茨s peque隠o[n]que el resto para este hueco, 夷no?[n][w][e]

[msg D151_04_miniEV10_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Ignoremos ese libro de momento,[n]no cabe aqu胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si hubiera otro libro que cupiese...[n][w][e]

