[msg ALL_PICTURE_CHECK_EVENT_ [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6028 65535 0]Todos parecen muy similares,[n]hasta en la composici吋n.[n][w][e]

[msg ALL_PICTURE_CHECK_EVENT__2 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]As胤 que sus alumnos son solo[n]cuadros... 夷Qu姻 ser茨 el arte[n]para Madarame a estas alturas?[n][w][e]

[msg ALL_PICTURE_CHECK_EVENT__3 [Yusuke]]
[s][bup 0 5 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4171 65535 0]Creo que este alumno ha dejado[n]el mundo del arte.[n]Circulaban rumores muy turbios.[n][w][e]

