[msg MSG_COFFEE_NG_mes01]
[s]Han colocado unas [clr 2]herramientas[n]profesionales para hacer caf姻[clr 27][n]en la barra.[n][w][e]
[s]Me pregunto si sabr茨 diferente[n]si hago un poco con ellas.[n][w][e]

[msg MSG_COFFEE_NG_0410_mes01]
[s]Primero deber胤a coger el tel姻fono.[n][w][e]

[msg MSG_COFFEE_NG_0410_mes02]
[s]Ahora mismo, prefiero comer algo[n]antes que tomar caf姻.[n]Vamos a mirar en el [clr 2]frigor胤fico[clr 27].[n][w][e]

