[msg D07_BRIEFING_170_mes01 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4026 65535 0]Goro Akechi... La mayor v胤ctima[n]de las fechor胤as de Shido.[n][w][e]

[msg D07_BRIEFING_170_mes02 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Era la 雨nica forma?[n][w][e]

[msg D07_BRIEFING_170_mes03 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo vengaremos[n]cuando derrotemos a Shido. Ya[n]tenemos las cartas. 斡Vamos a ello![n][w][e]

