[msg D08_BRIEFING_070_mes01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3019 65535 0]Hemos llegado muy lejos...[n]夷Qu姻 opinas, Mona?[n][w][e]

[msg D08_BRIEFING_070_mes02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Casi hemos alcanzado el tesoro.[n]Siento su presencia muy cerca.[n][w][e]

[msg D08_BRIEFING_070_mes03 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que ha llegado el momento...[n][w][e]

[msg D08_BRIEFING_070_mes04 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7080 65535 0]S胤, no cabe la menor duda.[n]斡A por el tesoro[n]de la gente, equipo![n][w][e]

[msg D08_BRIEFING_070_mes05 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero... 夷qu姻 suceder茨 cuando[n]nos hagamos con 姻l?[n][w][e]

[msg D08_BRIEFING_070_mes06 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No s姻 si eso bastar茨 para que todo[n]salga bien. Aun as胤, merece[n]la pena intentarlo.[n][w][e]

[msg D08_BRIEFING_070_mes07 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3020 65535 0]Aj茨. Seguro que, de una forma[n]u otra, todos despertar茨n.[n][w][e]

[msg D08_BRIEFING_070_mes08 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ser胤a un locur吋n que los ciudadanos[n]se pusieran a llorar y a pedir[n]perd吋n por todo.[n][w][e]

[msg D08_BRIEFING_070_mes09 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A雨n no se sabe qu姻 va a pasar,[n]pero ya que hemos llegado hasta[n]aqu胤... Tenemos que seguir adelante.[n][w][e]

[sel D08_BRIEFING_070_selA top]
[s]斡Vamos a por el tesoro![e]
[s]斡Acabemos con esto![e]

[msg D08_BRIEFING_070_selA_0_ [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7023 65535 0]斡Eso es![n][w][e]

[msg D08_BRIEFING_070_selA_0__2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1181 65535 0]斡No conozco la palabra 或fracaso位![n][w][e]

[msg D08_BRIEFING_070_selA_0__3 [Ann]]
[s][bup 0 4 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6117 65535 0]斡Se acab吋 lo que se daba![n][w][e]

[msg D08_BRIEFING_070_selA_0__4 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4083 65535 0]斡Por fin vamos a cosechar[n]los frutos de tant胤simo esfuerzo![n][w][e]

[msg D08_BRIEFING_070_selA_0__5 [Makoto]]
[s][bup 0 6 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2165 65535 0]斡As胤 se habla![n][w][e]

[msg D08_BRIEFING_070_selA_0__6 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9035 65535 0]Eh, 斡que aqu胤 tambi姻n estoy yo![n]斡Que nadie se preocupe por nada![n][w][e]

[msg D08_BRIEFING_070_selA_0__7 [Haru]]
[s][bup 0 7 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3023 65535 0]斡Unamos nuestras fuerzas para poner[n]el broche de oro![n][w][e]

