[msg D08_BRIEFING_040_mes01 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El mecanismo que hace que el suelo[n]se ilumine es complicad胤simo. [n][w][e]

[msg D08_BRIEFING_040_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los colores cambian al pisarlos.[n]Hay que planear bien[n]c吋mo proceder.[n][w][e]

[msg D08_BRIEFING_040_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y hay l胤mites a la hora de pisar[n]el suelo o de ver los niveles. Hay[n]que tener en cuenta muchas cosas.[n][w][e]

[msg D08_BRIEFING_040_mes04 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por suerte, los enemigos no nos[n]atacar茨n aunque fallemos.[n][w][e]
[s]Tom姻monoslo con calma[n]y resolv茨moslo con prudencia.[n][w][e]

