[msg D05_BRIEFING_030_mes01 [Futaba]]
[s][bup 0 8 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9026 65535 0]Entonces hay tres 茨reas que[n]recorrer... Qu姻 pe隠azo.[n][w][e]

[msg D05_BRIEFING_030_mes02 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es muy pronto para tirar la toalla,[n]夷eh? Ni siquiera hemos llegado[n]a la primera 茨rea.[n][w][e]

[msg D05_BRIEFING_030_mes03 [Futaba]]
[s][bup 0 8 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Va en serio? Me voy a pudrir[n]aqu胤 dentro, de verdad.[n][w][e]

[msg D05_BRIEFING_030_mes04 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7114 65535 0]Eh, tampoco te pases.[n][w][e]

[msg D05_BRIEFING_030_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A雨n nos queda un mont吋n[n]por delante, chicos. No es[n]momento de ponerse quejicas.[n][w][e]

[msg D05_BRIEFING_030_mes06 [Futaba]]
[s][bup 0 8 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Vale, vale. Solo quer胤a[n]desahogarme un poco.[n][w][e]

