[msg D159_07_npc_01_mes01 [Invitado enmascarado]]
[s]*risita* Ser testigo de esto[n]me hace sentir como que soy[n]uno de los elegidos.[n][w][e]

[msg D159_07_npc_02_mes01 [Invitado enmascarado]]
[s]Uy, me he emocionado mucho[n]en la sala de entretenimiento.[n]Voy a descansar un rato.[n][w][e]

[msg D159_07_npc_03_mes01 [Invitado enmascarado]]
[s]Ese hombre ten胤a tatuajes[n]y sus modales dejaban[n]mucho que desear...[n][w][e]
[s]Pero, si est茨 en este barco,[n]es porque Shido lo ha aceptado.[n][w][e]

[msg D159_07_npc_04_mes01 [Camarero]]
[s]Hola. La cubierta trasera[n]se encuentra por aqu胤.[n][w][e]
[s]Actualmente estamos en alerta,[n]pero haga como que no estamos.[n]P吋ngase c吋modo.[n][w][e]

[msg D159_07_npc_05_mes01 [Camarero]]
[s]La sala de entretenimiento[n]est茨 por aqu胤.[n][w][e]
[s]Tenemos todo tipo de juegos,[n]incluidas las tragaperras. Le recomiendo[n]que vaya ah胤 si se aburre.[n][w][e]

