[msg MSG_DUMMY]
[s]...[n][w][e]

[sel YESNO_SEL top]
[s]Solicitar[e]
[s]Cancelar[e]

[msg MSG_BAITO_MAGAZINE_1ST_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]夷Un trabajo a tiempo parcial?[n]Bueno, s胤, necesitas dinero.[n][w][e]
[s][f 4 10 65535 0 0]Pero piden unos requisitos, 夷no?[n]夷Est茨s seguro de que los cumples?[n][w][e]

[msg MSG_BAITO_MAGAZINE_1ST_0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]A ver, pues... 夷Qu姻 clase de trabajos ofrecen?[n][w][e]

[msg MSG_BAITO_MAGAZINE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1186 65535 0]夷Hay algo que valga la pena?[n][w][e]

[msg MSG_Arbeit_Tell [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]斡Llama ahora mismo![n][w][e]

[msg MSG_Arbeit_Tell_may [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]斡S胤, podemos ir a Shibuya[n]ahora mismo![n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]斡Llama ahora mismo![n][w][e]

[msg MSG_Arbeit_Tell_Bar [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]No s姻 muy bien qu姻 decir,[n]pero, si t雨 quieres, llama.[n][w][e]

[msg MSG_BAITO_MAGAZINE_Error [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]La florister胤a est茨 en el [clr 2]centrocomercial subterr茨neo[clr 27] de Shibuya.[n]Oye, 夷hoy te tocaba trabajar?[n][w][e]

[msg MSG_BAITO_MAGAZINE_Error_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]La tienda de autoservicio est茨[n]en [clr 2]la calle principal[clr 27], 夷verdad?[n]M胤rate bien el horario antes de ir.[n][w][e]

[msg MSG_BAITO_MAGAZINE_Error_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]El restaurante de gyuudon est茨 en[n]la [clr 2]calle principal[clr 27]. 夷Hoy te toca trabajar?[n][w][e]

[msg MSG_BAITO_MAGAZINE_Error_4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1023 65535 0]El bar de [clr 2]Shinjuku[clr 27]...[n]Ir茨s a trabajar, 夷no?[n][w][e]

[msg MSG_Arbeit_Flower_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]夷Trabajar en una florister胤a?[n]Si te rodeas de flores, puede que[n]aumente tu [f 4 11 4][clr 26][f 4 12 4][clr 27].[n][w][e]
[s][f 4 10 65535 0 0]Parece la mar de duro.[n]夷En serio est茨s dispuesto a eso?[n][w][e]

[msg MSG_Arbeit_Flower_Tell [Tel姻fono]]
[s]Hola, florister胤a Rafflesia.[n]夷Le gustar胤a encargar flores?[n][w][e]
[s]Ah, 夷llama por la oferta[n]de trabajo?[n][w][e]

[msg MSG_Arbeit_Flower_Tell_O [Tel姻fono]]
[s]Gracias. No tenemos suficiente[n]personal y necesitamos ayuda.[n][w][e]
[s]Y los horarios... podemos[n]cuadrarlos para que te vayan bien.[n][w][e]
[s]P茨sate la pr吋xima vez que[n]est姻s disponible.[n][w][e]
[s]Estamos en el [clr 2]centro comercial[n]subterr茨neo de Shibuya[clr 27].[n]Aqu胤 te espero.[n][w][e]

[msg MSG_Arbeit_Flower_Tell_O_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]斡Te han dado el trabajo! 斡As胤 se hace![n][w][e]

[msg MSG_Arbeit_Flower_NG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]En los requisitos pone que hay[n]que tener Encanto, pero creo que[n]t雨 de momento no lo cumples.[n][w][e]

[msg MSG_Arbeit_Flower_NG_par]
[s]Tu [f 4 11 1][clr 26][f 4 12 1][clr 27] tiene que ser [clr 2][f 4 13 1 2][clr 27][n]para trabajar en la florister胤a.[n][w][e]

[msg MSG_Arbeit_Convini_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]夷Un trabajo a tiempo parcial[n]en una tienda de autoservicio?[n]Muy de estudiante.[n][w][e]
[s][f 4 10 65535 0 0]No te vendr胤a mal mejorar[n]tu [f 4 11 1][clr 26][f 4 12 1][clr 27] trabajando[n]en atenci吋n al cliente.[n][w][e]
[s][f 4 10 65535 0 0]Oye, 夷por qu姻 no te apuntas?[n][w][e]

[msg MSG_Arbeit_Convini_Tell [Tel姻fono]]
[s]777 de la calle principal, hola.[n]夷Llama por la oferta de trabajo?[n][w][e]
[s]Espere un momento,[n]que llamo al encargado.[n][w][e]

[msg MSG_Arbeit_Convini_Tell_ [Voz de hombre]]
[s]Disculpe la espera.[n]夷Le interesa el puesto de trabajo?[n][w][e]
[s]Ah, eres estudiante, 夷no?[n]Pues te har姻 un horario[n]que cuadre con tus d胤as libres.[n][w][e]
[s]Siempre estoy en la tienda,[n]as胤 que ven aqu胤 directamente.[n][w][e]
[s]Tengo muchas ganas de que[n]trabajes con nosotros.[n][w][e]

[msg MSG_Arbeit_Convini_Tell__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]斡Te han dado el trabajo! 斡As胤 se hace![n][w][e]

[msg MSG_Arbeit_BeefDon_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Uy, trabajar en el restaurante de[n]gyuudon parece duro, pero[n]mejorar茨s tu [f 4 11 2][clr 26][f 4 12 2][clr 27].[n][w][e]
[s]夷Qu姻 quieres hacer?[n]夷Vas a solicitar el puesto?[n][w][e]

[msg MSG_Arbeit_BeefDon_Tell [Tel姻fono]]
[s]Hola. Ore no Beko de la calle[n]principal. 夷Para cu茨nta gente[n]va a pedir?[n][w][e]
[s]Ah, pregunta por la oferta[n]de trabajo.[n][w][e]

[msg MSG_Arbeit_BeefDon_Tell_ [Voz de hombre]]
[s]Perfecto. Necesitamos urgentemente[n]a gente. Nos da igual quien sea.[n][w][e]
[s]No te importa trabajar de noche,[n]夷verdad?[n]P茨sate cuando tengas tiempo.[n][w][e]
[s]Estamos justo en la entrada[n]de la calle principal.[n][w][e]
[s]Aqu胤 te espero.[n][w][e]

[msg MSG_Arbeit_BeefDon_Tell__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Con eso queda solucionado.[n]Ya puedes curr茨rtelo.[n][w][e]

[msg MSG_Arbeit_BeefDon_NG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1044 65535 0]Pero 夷no es un trabajo nocturno?[n][w][e]

[msg MSG_Arbeit_BeefDon_NG_pa]
[s]Solo puedes trabajar en el[n]restaurante de gyuudon por la noche.[n][w][e]

[msg MSG_Arbeit_Bar_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0]夷Trabajar en un bar?[n]Un momento, si es...[n][w][e]
[s][f 4 10 65535 0 0]夷Hablas en serio?[n][w][e]

[msg MSG_Arbeit_Bar_Tell [Tel姻fono]]
[s]斡Hola, hola! 斡Crossroads al habla![n][w][e]

[msg MSG_Arbeit_Bar_Tell_OK_0 [Tel姻fono]]
[s]夷Llama por lo del trabajo a[n]tiempo parcial? 斡Ah, gracias![n]Nos ha sacado de un apuro.[n][w][e]
[s]Ah, reconozco tu voz.[n]Llamaste el otro d胤a, 夷no?[n][w][e]
[s]As胤 que te ha picado la curiosidad...[n]Ser胤a un placer contar[n]contigo como trabajador.[n][w][e]
[s]斡P茨sate cuando quieras![n]Aqu胤 te espero.[n][w][e]

[msg MSG_Arbeit_Bar_Tell_OK_0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1022 65535 0]Pues todo en orden.[n]C-creo que as胤 ya vale, 夷no?[n][w][e]

