[msg QUEST_50_ENTER_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1035 65535 0]Esa es la sombra de Wakasa.[n][w][e]

[msg QUEST_50_ENTER_mes01f [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Hemos visto a la sombra de Wakasa.[n][w][e]

[msg QUEST_50_ENTER_mes02 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Es una especie de estafador, 夷no?[n][w][e]

[msg QUEST_50_ENTER_mes03 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3127 65535 0]S胤, y sus v胤ctimas[n]son gente anciana y solitaria.[n][w][e]

[msg QUEST_50_ENTER_mes04 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]夷C吋mo puede[n]hacer algo tan horrible?[n][w][e]

[msg QUEST_50_ENTER_mes05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4020 65535 0]Hay que despertar su coraz吋n.[n][w][e]

[msg MSG_013_0_0 [Sombra de Wakasa]]
[s][vp 8 2 1 46760 65535 0]Los Ladrones Fantasma, 夷eh? He o胤do[n]hablar de vosotros. Sois un grupo[n]de ladrones de lujo, 夷no?[n][w][e]
[s][vp 1 0 0 0 0 0]Aunque, tras las c茨maras,[n]seguro que gan茨is una pasta.[n]Decidme c吋mo lo hac姻is.[n][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1046 65535 0]斡No nos metas en el mismo saco[n]que a los estafadores como t雨![n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Enga隠ar a los ancianos con buena fe[n]para que te den su dinero...[n]夷C吋mo puedes ser tan capullo?[n][w][e]

[msg MSG_016_0_0 [Sombra de Wakasa]]
[s][vp 8 2 1 46759 65535 0]夷Eh? Es el pago por mis cuidados.[n]Les sigo el rollo y escucho[n]sus estupideces, 夷no?[n][w][e]
[s][vp 1 0 0 0 0 0]Hablan sin parar de lo buenos que[n]son sus hijos. 斡Pues anda que no[n]son tontos los padres! 斡Ja, ja, ja![n][w][e]

[msg MSG_017_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]斡夷Dir胤as algo as胤[n]sobre tus padres?![n][w][e]

[msg MSG_018_0_0 [Sombra de Wakasa]]
[s][vp 1 0 0 0 0 0]Ay, los Ladrones Fantasma[n]me ten姻is harto. 斡Largaos[n]antes de que os d姻 una paliza![n][w][e]

[msg QUEST_50_BOSS_EV_mes04 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]斡Vamos![n][w][e]

[msg MSG_020_0_0 [Sombra de Wakasa]]
[s][vp 1 0 0 0 0 0]He sido un capullo.[n]L-le he sacado los cuartos[n]a la gente mayor. Madre m胤a...[n][w][e]

[sel SEL_021_0_0 top]
[s]Vas a ir al infierno.[e]
[s]Esto es imperdonable.[e]
[s]Pide perd吋n.[e]

[msg MSG_022_0_0 [Sombra de Wakasa]]
[s][vp 1 0 0 0 0 0]S胤, estoy listo.[n][w][e]

[msg MSG_023_0_0 [Sombra de Wakasa]]
[s][vp 1 0 0 0 0 0]Lo siento, no s姻 qu姻 decir...[n][w][e]

[msg MSG_024_0_0 [Sombra de Wakasa]]
[s][vp 1 0 0 0 0 0]Lo siento, lo siento mucho...[n][w][e]

[msg MSG_025_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Es horrible que te hayas[n]aprovechado de las debilidades[n]de los dem茨s de esa manera.[n][w][e]

[msg MSG_026_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]夷Qu姻 vas a hacer[n]a partir de ahora?[n][w][e]

[msg MSG_027_0_0 [Sombra de Wakasa]]
[s][vp 8 2 1 46768 65535 0]Ir姻 a ver a toda la gente[n]a la que he enga隠ado. Les pedir姻[n]disculpas y luego me entregar姻.[n][w][e]
[s][vp 1 0 0 0 0 0]Tambi姻n les contar姻 a mis padres[n]lo que he hecho y les pedir姻[n]perd吋n por ser tan idiota.[n][w][e]

[msg MSG_028_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]De haber sabido cu茨nto iban[n]a sufrir tus v胤ctimas,[n]no habr胤as hecho nada de esto.[n][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Recuerda la verg鵜enza que[n]has sentido y haz lo que est姻[n]en tu mano para enmendarlo.[n][w][e]

[msg QUEST_50_BATTLE_END_mes0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Muy bien, tenemos el tesoro![n][w][e]

[msg QUEST_50_BATTLE_END_mes0_2 [Sombra de Wakasa]]
[s]斡Lo sientooooo![n][w][e]

[msg QUEST_50_BATTLE_END_mes0_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡No vuelvas a hacerlo! 斡Paga por[n]todo el mal que has hecho![n][w][e]

