[msg e210_151_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]斡Anda, otro cuadro![n][w][e]

[msg e210_151_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Atravesar un pasaje secreto[n]hace que otro se materialice...[n]Qu姻 estratagema tan ingeniosa.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es probable que haya un nuevo[n]camino a trav姻s de los cuadros.[n]Investiguemos m茨s, Joker.[n][w][e]

[msg e210_151_mes03 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6186 65535 0]Otro cuadro...[n][w][e]

[msg e210_151_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, por aqu胤 ya no hay[n]ning雨n marco vac胤o m茨s.[n][w][e]

[msg e210_151_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Seguro que volvemos a encontrar[n]otro camino. Vamos a entrar, a ver[n]si estoy en lo cierto.[n][w][e]

