[msg MSG_DUMMY_01]
[s]Siempre logro tranquilizarme[n]en el ba隠o.[n][w][e]
[s]Deber胤a pensar en qu姻 hacer ahora.[n][w][e]
[s]...[n][w][e]

[msg MSG_DUMMY_0410_mes01]
[s]夷Deber胤a coger el tel姻fono?[n][w][e]

[msg MSG_DUMMY_0410_mes02]
[s]Me ha pedido que gire el cartel.[n]夷Se referir茨 al de la puerta?[n][w][e]

[msg MSG_DUMMY_0410_mes03]
[s]Me muero de hambre...[n][w][e]

[msg MSG_DUMMY_0410_mes04]
[s]Ma隠ana tengo clase.[n]Deber胤a irme a la cama.[n][w][e]

[msg MSG_DUMMY_0411_mes01]
[s]Espero no liarme con[n]los transbordos de tren.[n][w][e]

[msg MSG_TOILET_001 [Morgana]]
[s]夷Quieres usar el ba隠o?[n][e]

[msg MSG_TOILET_001_0_0 [Morgana]]
[s]No hay prisa.[n][w][e]

[msg MSG_TOILET_001_0_1 [Morgana]]
[s]Buen trabajo.[n][w][e]

[msg MSG_TOILET_001_1_0 [Morgana]]
[s]No me hace falta un sitio[n]tan pomposo para hacer mis cosas.[n]Me puedo ir a la esquina y...[n][w][e]
[s]Espera, esto no deber胤a ser motivo[n]de orgullo. 夷Estar姻 perdiendo[n]mi sentido humano de la moralidad?[n][w][e]

[msg MND_TOILET]
[s]Siempre logro tranquilizarme[n]en el ba隠o.[n][w][e]
[s]...[n][w][e]

[msg MND_HERO_WEAK]
[s]Sigo siendo bastante d姻bil. Deber胤a[n]intentar hacerme m茨s fuerte.[n][w][e]
[s]...[n][w][e]

[msg MND_HERO_WEAK2]
[s]No s姻 si deber胤a prepararme m茨s[n]o enviar ya el aviso.[n][w][e]
[s]...[n][w][e]

[msg MND_HERO_STRONG]
[s]Creo que ahora soy algo m茨s fuerte.[n]Deber胤a enviar pronto el aviso.[n][w][e]
[s]...[n][w][e]

[msg MND_HERO_BANDIT]
[s]Ma隠ana es el d胤a de nuestro asalto.[n]Debo prepararme.[n][w][e]
[s]...[n][w][e]

[msg MND_CHK_TOILET_DIRTY]
[s]El ba隠o est茨 muy sucio.[n]Deber胤a limpiarlo pronto.[n][w][e]

[msg MND_CHK_TOILET_BEAUTIFUL]
[s]No es que est姻 como los chorros[n]del oro, pero ya no est茨 tan sucio[n]como para molestarme.[n][w][e]
[s]Deber胤a limpiarlo cada vez que[n]llegue a ese punto.[n][w][e]

[msg MND_CHK_TOILET_YORU_NG]
[s]La cafeter胤a sigue abierta.[n]Ya limpiar姻 por la noche.[n][w][e]

[msg MND_CHK_TOILET_KF_NG]
[s]Acabo de llegar a casa. Antes[n]deber胤a pasarme por mi habitaci吋n.[n][w][e]

[msg MND_CHK_TOILET_NG]
[s]Deber胤a limpiar cuando[n]haya descansado un poco.[n][w][e]

[msg MND_CHK_TOILET_spot_play]
[s]Deber胤a limpiar cuando[n]haya descansado un poco.[n][w][e]

[msg MND_CHK_TOILET_MORU_NG]
[s]Morgana sigue conmigo. Deber胤a[n]pasarme antes por mi habitaci吋n.[n][w][e]

[msg MSG_CHK_TOILET_ROOM_CLEA]
[s]Morgana ten胤a algo que decirme.[n]Cuando hable con 姻l,[n]debo decidir si limpiar o no.[n][w][e]

[msg MSG_CHK_TOILET_ROOM_CLEA_2]
[s]...[n][w][e]
[s]Siento que Morgana me est茨 mirando[n]desde detr茨s de la puerta.[n]Creo que quiere que limpie.[n][w][e]
[s]Ser茨 mejor que me vaya.[n][w][e]

[msg MND_CHK_SPOT]
[s]Creo que limpiar el ba隠o mejorar茨[n]mi [clr 1]Dignidad[clr 27]. Deber胤a ponerme[n]a ello esta noche.[n][w][e]

[msg MND_CHK_TOILET]
[s]Creo que limpiar el ba隠o mejorar茨[n]mi [clr 1]Dignidad[clr 27]. Deber胤a ponerme[n]a ello esta noche.[n][w][e]

[sel SEL_CHK_TOILET top]
[s]Limpiar el ba隠o[e]
[s]Cancelar[e]

[msg MND_CHK_TOILET_00]
[s]He limpiado el ba隠o.[n][w][e]
[s]Ahora est茨 un poco mejor.[n][w][e]

