[msg QUEST_11_ENTER_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Esa debe de ser[n]la sombra de Kazuya Makigami.[n][w][e]

[msg QUEST_11_ENTER_mes01f [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah胤 est茨 la sombra[n]de Kazuya Makigami.[n][w][e]

[msg QUEST_11_ENTER_mes02 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Tiene muy mala pinta...[n][w][e]

[msg QUEST_11_ENTER_mes03 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4088 65535 0]Pertenece a un grupo que[n]roba restaurantes. Ha empleado la[n]violencia contra su propio hermano.[n][w][e]

[msg QUEST_11_ENTER_mes04 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Tenemos que hacer algo al respecto.[n][w][e]

[msg QUEST_11_ENTER_mes05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Hablemos con 姻l.[n][w][e]

[msg MSG_069_0_0 [Sombra de Makigami]]
[s][vp 8 2 1 47160 65535 0]夷Que si estoy detr茨s del[n]grupo secreto? 夷Yo?[n]Pues s胤, como lo oyes.[n][w][e]
[s][vp 8 0 0 0 65535 0]Convenc胤 a mis amigos para[n]que me echaran un cable con unos[n]或trabajillos位. 斡Y no me arrepiento![n][w][e]

[msg MSG_070_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]夷Ahora vienes con excusas?[n]No tienes verg鵜enza.[n][w][e]

[msg MSG_070_0_0b [Sombra de Makigami]]
[s][vp 8 2 1 0 65535 0]斡Eh! Yo solo quer胤a pas茨rmelo[n]bien un rato, pero esos[n]imb姻ciles se pasaron de listos.[n][w][e]
[s][vp 8 0 0 0 65535 0]夷Y me toca aguantar esto a m胤?[n]斡夷Por qu姻 co隠o me sale todo[n]siempre mal?![n][w][e]

[msg MSG_071_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]夷Que te sale todo mal?[n]夷De qu姻 hablas?[n][w][e]

[msg MSG_072_0_0 [Sombra de Makigami]]
[s][vp 8 0 0 0 65535 0]S胤, desde que era un cr胤o,[n]todo el mundo me ha tratado[n]con desprecio.[n][w][e]
[s][vp 8 0 0 0 65535 0]Mi hermano peque隠o era el m茨s[n]listo, el favorito de mis padres.[n]Yo les daba igual...[n][w][e]
[s][vp 8 0 0 0 65535 0]夷Y esper茨is que tenga una[n]vida normal? 斡Paso de esta[n]sociedad de mierda![n][w][e]

[msg MSG_073_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]夷Y lo demuestras con violencia?[n]Menuda gilipollez.[n][w][e]

[msg MSG_074_0_0 [Sombra de Makigami]]
[s][vp 8 2 1 47164 65535 0]Anda, 夷qu姻 dices? Si vosotros[n]tambi姻n sois ladrones. 夷Os[n]cre姻is mejores que yo? 斡Largo![n][w][e]

[msg MSG_075_0_0 [Sombra de Makigami]]
[s][vp 8 0 0 0 65535 0]No me mir姻is con condescendencia...[n]斡Os voy a aplastar![n][w][e]

[msg MSG_076_0_0 [Sombra de Makigami]]
[s][vp 8 2 1 47165 65535 0]斡夷De qu姻 vais, Ladrones Fantasma?![n][w][e]
[s][vp 8 0 0 0 65535 0]Es imposible...[n][w][e]
[s][vp 8 0 0 0 65535 0]斡Ah, pues claro![n]Hab姻is hablado con mi hermano.[n][w][e]

[sel SEL_077_0_0 top]
[s]Eso es.[e]
[s]Ahora piensa en lo que has hecho.[e]

[msg MSG_078_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]斡Si te ha costado tan poco[n]adivinarlo es porque sabes[n]c吋mo se siente![n][w][e]

[msg MSG_079_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]夷Y ahora te das cuenta?[n]Entonces, ya sabes c吋mo se siente[n]tu hermano.[n][w][e]

[msg MSG_080_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7179 65535 0]Bueno, est茨 bien que lo sientas.[n][w][e]

[msg MSG_081_0_0 [Sombra de Makigami]]
[s][vp 8 0 0 0 65535 0]...[n][w][e]
[s][vp 8 0 0 0 65535 0]Lo hizo por m胤...[n][w][e]

[msg MSG_082_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]斡Ah胤 est茨![n][w][e]

[msg MSG_083_0_0 [Sombra de Makigami]]
[s][vp 8 0 0 0 65535 0]Esa es la llave del cofre de mi[n]habitaci吋n. D茨dsela a mi hermano.[n][w][e]
[s][vp 8 0 0 0 65535 0]Se supone que sois[n]ladrones de los buenos, 夷no?[n][w][e]

[msg MSG_084_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]斡夷Qu姻?! 夷Por qu姻 胤bamos a hacer[n]algo as胤 por ti?[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]Ps姻. 夷Quieres decirle algo?[n][w][e]

[msg MSG_085_0_0 [Sombra de Makigami]]
[s][vp 8 0 0 0 65535 0]Bueno...[n][w][e]
[s][vp 8 0 0 0 65535 0]Je, je. 或Quema lo que hay dentro[n]o des姻chalo位.[n][w][e]
[s][vp 8 0 0 0 65535 0]*sollozo*[n][w][e]

[msg MSG_086_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 vamos a hacer con ese tesoro?[n][w][e]

[sel SEL_087_0_0 top]
[s]Le daremos un buen uso.[e]
[s]Se la entregaremos a su hermano.[e]

[msg MSG_088_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]夷Usarla? No podemos colarnos[n]en una casa, buscar un cofre[n]y llevarnos lo que haya dentro.[n][w][e]

[msg MSG_089_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]Vamos a d茨rsela al hermano.[n][w][e]

[msg MSG_092_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]S胤. De todas formas,[n]no la queremos para nada.[n][w][e]

[msg MSG_093_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 vamos a hacer?[n]Como va a mi instituto,[n]puedo d茨rsela yo.[n][w][e]

[msg MSG_094_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]No, me colar姻 en su casa.[n]Creo que es la mejor opci吋n.[n][w][e]

[msg MSG_095_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]Espero que todo se resuelva[n]por s胤 solo.[n][w][e]

[msg MSG_096_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 0 0 65535 0]En cualquier caso,[n]斡la misi吋n ha sido un 姻xito![n][w][e]

