[msg GOTO_DUNGEON_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1172 65535 0]Muy bien, Joker...[n]夷Qu姻 quieres hacer?[n][w][e]

[sel GOTO_DUNGEON_sel01 top]
[s]Empezar en alg雨n punto del camino[e]
[s]Empezar desde el principio[e]
[s]Cambiar aspecto de la furgoneta[e]
[s]Prepararse antes[e]

[msg GOTO_DUNGEON_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Uy, perfecto.[n]Lo 雨nico, prep茨rate bien.[n][w][e]

[msg GOTO_DUNGEON_mes03 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]斡Disfrazarse nunca est茨 de m茨s![n][w][e]
[s]夷C吋mo quieres que vayamos?[n][w][e]

[sel GOTO_DUNGEON_sel02 top]
[s]Un estilo de fiesta[e]
[s]Estilo Ladr吋n Fantasma[e]
[s]Con grafitis[e]
[s]El estilo habitual[e]

[msg GOTO_DUNGEON_mes04 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1067 65535 0]Je, je. O胤do cocina.[n]斡Espero que tengas ganas de verme![n][w][e]

[msg GOTO_DUNGEON_mes05 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1048 65535 0]Muy bien, 斡me apetece algo[n]diferente! 斡Espero que tengas[n]ganas de ver mi nuevo aspecto![n][w][e]

[msg GOTO_DUNGEON_mes06 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1166 65535 0]斡Vale! 斡La verdad es que yo ya[n]soy guapo tal y como soy![n][w][e]

[msg GOTO_DUNGEON_mes07 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1067 65535 0]斡Vale, te voy a ense隠ar[n]lo guay que soy![n][w][e]

