[msg D10_BRIEFING_130_mes01 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7025 65535 0]斡Argh! Cre胤a que[n]encontrar胤amos el v胤deo...  [n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No nos lo est茨n poniendo[n]nada f茨cil, 夷eh?[n][w][e]

[msg D10_BRIEFING_130_mes02 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ya te digo... Aunque espero[n]que no est姻 muy lejos.[n][w][e]

[msg D10_BRIEFING_130_mes03 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9155 65535 0]Detecto indicios de sombras[n]superfuertes m茨s adelante.[n]夷Estar茨 all胤?  [n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cabe la posibilidad de que haya[n]que pelear para conseguirlo.[n]Cuidado con la b雨squeda.[n][w][e]

