[msg e379_204_mes01 [Voz mec茨nica]]
[s]Autentificaci吋n necesaria.[n]Introduzca su tarjeta de miembro.[n][w][e]

[msg e379_204_mes02 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 tarjeta de miembro?[n][w][e]

[msg e379_204_mes03 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A lo mejor es como[n]un club de jugadores o algo as胤.[n][w][e]

[msg e379_204_mes04 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡No entiendo esas palabras[n]tan t姻cnicas! 斡Habla claro![n][w][e]

[msg e379_204_mes05 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Los casinos suelen tener[n]un sistema de miembros,[n]un club de jugadores.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Algunas zonas incluso est茨n[n]limitadas para determinados[n]niveles de jugador.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por c吋mo pintan las cosas,[n]creo que este sitio[n]cuenta con un sistema similar.[n][w][e]

[msg e379_204_mes06 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 ser茨 m茨s f茨cil. Venga,[n]vamos a meternos en ese embolado.[n][w][e]

[msg e379_204_mes07 [Akechi]]
[s][bup 0 9 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me gustar胤a decir lo mismo, pero...[n][w][e]

[msg e379_204_mes08 [Haru]]
[s][bup 0 7 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Una sombra?![n][w][e]

[msg e379_204_mes09 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como imaginaba, apuntarnos[n]no va a ser tan f茨cil.[n][w][e]

[msg e379_204_mes10 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Seguro que nos est茨 haciendo[n]enfrentarnos a la seguridad[n]antes de que lleguemos a ella.[n][w][e]

[msg e379_204_mes11 [Sombra de guardia de seguridad]]
[s]斡Ah胤 est茨n! 斡Las 吋rdenes[n]son matar en el acto![n][w][e]

[msg e379_204_mes12 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ah胤 viene![n][w][e]

[msg e379_204_mes13 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No hay de qu姻 preocuparse.[n]Yo me ocupo. Tengo que demostraros[n]que valgo.[n][w][e]

[sel e379_204_selA top]
[s]Espero mucho de ti.[e]
[s]夷Estar茨s bien?[e]

[msg e379_204_selA_0_mes01 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Prometo superar incluso[n]unas expectativas tan altas.[n][w][e]

[msg e379_204_selA_1_mes01 [Akechi]]
[s][bup 0 9 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A saber, pero creo que nadie[n]va a tener que intervenir.[n][w][e]

[msg e379_204_mes14 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Uf, ya est茨.[n][w][e]

[msg e379_204_mes15 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Incre胤ble. Cuesta creer[n]que fuera tu primera vez.[n][w][e]

[msg e379_204_mes16 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Un momento. Esto significa que[n]a partir de ahora vamos a luchar[n]contra un mont吋n de enemigos, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora que sabemos c吋mo entrar,[n]deber胤amos prepararnos bien.[n][w][e]

[msg e379_204_mes17 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es verdad... Me gustar胤a darme[n]prisa, pero ser茨 mejor no echarlo[n]todo a perder por imprudentes.[n][w][e]

[msg e379_204_mes18 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, 斡pues v茨monos![n]斡Volveremos cuando estemos listos![n][w][e]

[msg e379_204_mes19 [Voz mec茨nica]]
[s]Autentificaci吋n necesaria.[n]Introduzca su tarjeta de miembro.[n][w][e]

[msg e379_204_mes20 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8155 65535 0]Al parecer, necesitamos una tarjeta[n]de miembro para usar el ascensor.[n][w][e]

[msg e379_204_mes21 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm, no sirve de nada perder[n]el tiempo aqu胤. R茨pido, avancemos.[n][w][e]

[msg EV_SEL_MES_157_004_mes01 [Voz mec茨nica]]
[s]Seleccione una planta.[n][w][e]

[sel EV_SEL_MES_157_004_selA top]
[s]Ir a la planta alta[e]
[s]Ir a la planta de miembros[e]
[s]Da igual[f 2 7 0 0 106 1][e]

[msg EV_SEL_MES_157_004_selA_ [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg EV_SEL_MES_157_004_selA__2 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg EV_SEL_MES_157_004_selA__3 [Morgana]]
[s][bup 0 3 0 65535 0]......[n][w][e]

[msg e379_230_mes01 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6127 65535 0]Si escaneamos la tarjeta[n]de miembro, el ascensor[n]deber胤a funcionar, 夷no?[n][w][e]

[msg e379_230_mes02 [Voz mec茨nica]]
[s]Autentificaci吋n completada.[n][w][e]
[s]Acceso permitido a estas[n]plantas:[n][w][e]
[s]Planta normal.[n]Planta de miembros.[n][w][e]

[msg e379_230_mes03 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No dice nada de la de direcci吋n...[n][w][e]

[msg e379_230_mes04 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 8020 65535 0]Las plantas accesibles dependen[n]de la clasificaci吋n del jugador.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Por el momento, la planta de[n]miembros es el nivel m茨s alto[n]al que podemos acceder.[n][w][e]

[msg e379_230_mes05 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Es imposible modificar los datos[n]de la tarjeta. No se parece en nada[n]a las que he visto hasta ahora.[n][w][e]

[msg e379_230_mes06 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3128 65535 0]Pues no podemos ir a la planta[n]de direcci吋n...[n]夷Qu姻 hacemos?[n][w][e]

[msg e379_230_mes07 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Lo primero ser茨 ir hacia arriba.[n]De todas formas, no queda nada[n]por hacer en esta planta.[n][w][e]

