[sel SEL_FAMIRES_START_MORU top]
[s]Entrar[e]
[s]Cancelar[e]

[sel SEL_FAMIRES_START top]
[s]Entrar[e]
[s]Cancelar[e]

[msg MSG_FAMIRES_START_1ST_MO [Morgana]]
[s][bup 0 3 2 0 0]Ah, s胤, he o胤do que van muy bien[n]estos restaurantes porque se puede[n]estudiar mientras se come.[n][w][e]

[msg MSG_FAMIRES_START_COMMON [Morgana]]
[s][bup 0 3 0 0 0]夷Quieres estudiar un poco[n]en el restaurante?[n][w][e]

[msg MSG_FAMIRES_NOMONEY_MORU [Morgana]]
[s][bup 0 3 0 0 0]Con el poco dinero que tienes,[n]no puedes comprar nada.[n][w][e]

