[msg QUEST_56_ENTER_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Esas sombras deben ser[n]los tutores de ese tal Takase.[n][w][e]

[msg QUEST_56_ENTER_mes01f [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Aqu胤 es. Esas sombras deben ser[n]los tutores de ese tal Takase.[n][w][e]

[msg QUEST_56_ENTER_mes02 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Parecen muy seguros de s胤[n]mismos, se lo tienen muy cre胤do.[n][w][e]

[msg QUEST_56_ENTER_mes03 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Est茨n chantajeando a la profesora[n]Kawakami por lo del incidente[n]en el que muri吋 su hijo.[n][w][e]

[msg QUEST_56_ENTER_mes04 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Pero Kawakami no hizo[n]nada malo, 夷verdad?[n]斡Hay que ayudarla![n][w][e]

[msg QUEST_56_ENTER_mes05 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1174 65535 0]夷Todos listos? Vamos.[n][w][e]

[msg MSG_000_0_0 [Sombra del Sr. Takase]]
[s][vp 8 2 1 47010 65535 0]斡Dinerito, ay, mi dinerito![n]斡Daos prisa y soltad la pasta![n]斡Es vuestra obligaci吋n![n][w][e]

[msg MSG_001_0_0 [Sombra de la Sra. Takase]]
[s][vp 8 2 1 47610 65535 0]Ropa, bolsos, maquillaje...[n]斡Lo quiero todo![n][w][e]

[msg MSG_002_0_0 [Sombra del Sr. Takase]]
[s][vp 1 0 0 0 0 0]夷Qui姻n narices eres t雨? Ah, eres[n]uno de esos Ladrones Fantasma.[n][w][e]
[s][vp 1 0 0 0 0 0]Yo no he hecho nada malo.[n]斡No necesito despertar![n][w][e]
[s][vp 1 0 0 0 0 0]斡Menuda in雨til es![n]斡Deber胤a darme las gracias[n]por dejar que me financie![n][w][e]

[sel SEL_003_0_0 top]
[s]斡No es ninguna in雨til![e]
[s]斡Para incompetente, t雨![e]

[msg MSG_004_0_0 [Sombra del Sr. Takase]]
[s][vp 8 2 1 47012 65535 0]斡A callar! 斡Kawakami estaba[n]interfiriendo! 斡Yo quer胤a ayudar[n]por lo que le pas吋 a mi hijo![n][w][e]
[s][vp 1 0 0 0 0 0]No pienso perder, 斡y menos contra[n]unos elitistas como vosotros![n][w][e]

[msg MSG_005_0_0 [Sombra del Sr. Takase]]
[s][vp 1 0 0 0 0 0]夷T雨 tambi姻n me miras por encima[n]del hombro? Seguro que te r胤es[n]de m胤 entre dientes...[n][w][e]

[msg MSG_006_0_0 [Sombra de la Sra. Takase]]
[s][vp 8 2 1 47609 65535 0]Marcas de lujo,[n]tratamientos est姻ticos...[n]Sin ellos, la gente se burlar茨...[n][w][e]

[sel SEL_007_0_0 top]
[s]Nadie se est茨 riendo.[e]
[s]Pero 夷qu姻 dices?[e]

[msg MSG_008_0_0 [Sombra del Sr. Takase]]
[s][vp 1 0 0 0 0 0]Somos unas personas horribles.[n]Nuestro hijo, Taiki, y sus padres[n]biol吋gicos eran diferentes...[n][w][e]
[s][vp 1 0 0 0 0 0]Eran dos ricachones que[n]trabajaban en empresas de 姻lite[n]y siempre nos miraban con desd姻n.[n][w][e]
[s][vp 1 0 0 0 0 0]斡Por eso le ense隠amos[n]lo que es tener que arrodillarse![n][w][e]

[msg MSG_009_0_0 [Sombra de la Sra. Takase]]
[s][vp 1 0 0 0 0 0]Era tan bonito verlo[n]derrumbarse poco a poco[n]por trabajar tanto...[n][w][e]

[sel SEL_010_0_0 top]
[s]Sois malas personas.[e]
[s]Cu茨nta maldad.[e]

[msg MSG_011_0_0 [Sombra del Sr. Takase]]
[s][vp 1 0 0 0 0 0]Supongo que por eso todos nos[n]miraban por encima del hombro...[n][w][e]

[msg MSG_012_0_0 [Sombra del Sr. Takase]]
[s][vp 1 0 0 0 0 0]夷Tan equivocados est茨bamos?[n][w][e]

[msg MSG_013_0_0 [Sombra del Sr. Takase]]
[s][vp 1 0 0 0 0 0]Ya no estoy tan seguro[n]de que sus padres biol吋gicos[n]nos mirasen mal...[n][w][e]

[msg MSG_014_0_0 [Sombra de la Sra. Takase]]
[s][vp 1 0 0 0 0 0]Era feliz con Toshio,[n]pero lo olvid姻 todo.[n]Me obsesion姻 con el dinero...[n][w][e]

[msg MSG_015_0_0 [Sombra del Sr. Takase]]
[s][vp 1 0 0 0 0 0]Taiki era un ni隠o muy bueno...[n][w][e]

[msg MND_016_0_0]
[s][vp 1 0 0 0 0 0]Parece que el matrimonio Takase[n]ha despertado. Le dir姻 a Kawakami[n]que venga a mi habitaci吋n.[n][w][e]

