[msg MSG_DESK_START_THINK]
[s]夷Qu姻 hago en el escritorio?[n][w][e]

[msg MSG_DESK_START_THINK_MOR [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷Qu姻 vas a hacer?[n][w][e]

[sel MSG_DESK_START_THINK_SEL top]
[s]Fabricar herramientas[e]
[s]Arreglar el port茨til[e]
[s]Mirar en Art胤culos sospechosos[e]
[s]Cancelar[e]

[msg MSG_REPAIR_NotePc_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ahora que me acuerdo, has comprado[n]un port茨til, pero est茨 roto.[n][w][e]

[msg MSG_REPAIR_NotePc_NoItem [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Vas a necesitar herramientas[n]especializadas para repararlo.[n]夷D吋nde vender茨n?[n][w][e]

[msg MSG_REPAIR_NotePc_NoItem_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]No puedes arreglar el port茨til[n]sin herramientas especializadas.[n]夷Vender茨n en Akihabara?[n][w][e]

[msg MSG_REPAIR_NotePc_HaveIt [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Bueno, reparar[n]el port茨til parece dif胤cil.[n]斡Int姻ntalo cuando te apetezca![n][w][e]

[msg MSG_NotePc_Tool_NoItem_N [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Necesitas herramientas especiales[n]para arreglarlo. Puede que en las[n]tiendas de electr吋nica vendan.[n][w][e]

[msg MSG_NotePc_Tool_NoItem_Y [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Necesitas herramientas especiales[n]para arreglarlo.[n]Puede que en Akihabara vendan.[n][w][e]

[msg MSG_NotePc_Tool_HaveItem [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Va a ser complicado[n]hacer que funcione.[n]Arreglarlo te llevar茨 tiempo.[n][w][e]

[sel SEL_Repair_Q top]
[s]Intentemos arreglarlo.[e]
[s]Quiz茨 m茨s tarde.[e]

[msg MSG_WorkDesk_NG_NotToolO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1021 65535 0]Ahora no es el momento.[n]No te preocupes,[n]te ense隠ar姻 m茨s adelante.[n][w][e]

[msg MSG_WorkDesk_NG_GoAfterD [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Pero tienes que estar muy cansado.[n]No te preocupes,[n]te ense隠ar姻 m茨s adelante.[n][w][e]

[msg MSG_CHK_WORKBENCH_NG_DNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷No est茨s cansado?[n]Deja eso para otro momento.[n][w][e]

[msg MSG_ActNg_OnlySave [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]Deber胤amos descansar para ma隠ana.[n][w][e]

[msg MSG_CHK_WORKBENCH_NG_SPO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷No est茨s hecho polvo?[n]Deber胤as descansar.[n][w][e]

[msg MSG_DESK_NG_DEFAULT]
[s]Hay un mont吋n de libros[n]apilados en el escritorio.[n][w][e]

[msg MSG_ActNg_0505 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0]Est茨s lleno, 夷no?[n]Venga, vamos a descansar.[n][w][e]

