[msg D01_02_e129_202_mes01 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Muy bien, 斡aqu胤 es![n][w][e]

[msg D01_02_e129_202_mes02 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Q-qu姻 est茨 pasando aqu胤?[n][w][e]

[msg D01_02_e129_202_mes03 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Hab胤a gente del equipo de voleibol[n]aqu胤 metida la 雨ltima vez![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Verdad que s胤? Los viste, 夷no?[n][w][e]

[sel D01_02_e129_202_selA top]
[s]Claro.[e]
[s]Yo no vi nada.[e]
[s]No me acuerdo.[e]

[msg D01_02_e129_202_selA_0_m [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Lo sab胤a! Tiene que ser[n]aqu胤, 夷verdad?[n][w][e]

[msg D01_02_e129_202_selA_1_m [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡No, estaban aqu胤, lo juro![n][w][e]

[msg D01_02_e129_202_selA_2_m [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Los vi, lo juro![n]斡Tiene que ser aqu胤![n][w][e]

[msg D01_02_e129_202_mes04 [Morgana]]
[s][bup 0 3 0 65535 0]La celda est茨 abierta...[n][w][e]

[msg D01_02_e129_202_mes05 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Crees que se los han llevado a[n]otras celdas? 斡Echemos un vistazo![n][w][e]

[msg D01_02_e129_202_mes07 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7085 65535 0]Se han llevado a los tipos[n]de las celdas al sal吋n[n]de entrenamiento...[n][w][e]

[msg D01_02_e129_202_mes08]
[s]No hay nadie en la celda.[n][w][e]

[msg D01_02_e129_202_mes11 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1159 65535 0]Parece que no hay nadie.[n][w][e]

[msg D01_02_e129_202_mes10]
[s]No hay nadie en la celda.[n][w][e]

[msg D01_02_e129_202_mes12]
[s]No hay nadie en la celda.[n][w][e]

[msg D01_02_e129_202_mes13 [Morgana]]
[s][bup 0 3 0 65535 0]Oye, el rubiales est茨 haciendo[n]cosas raras. Echemos[n]un vistazo juntos.[n][w][e]

[msg D01_02_e129_202_mes14 [Ryuji]]
[s][bup 0 2 0 2 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espera, voy a mirar un poco m茨s.[n][w][e]

[msg D01_02_e129_202_mes15 [Morgana]]
[s][bup 0 3 0 65535 0]斡夷Eh?! 斡Vosotros dos,[n]esto no me gusta nada![n]斡Salid de las celdas ahora mismo![n][w][e]

