[msg D08_BRIEFING_060_mes01 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9043 65535 0]Hay un l胤mite de movimientos...[n]Las medidas de seguridad[n]cada vez son m茨s estrictas.[n][w][e]

[msg D08_BRIEFING_060_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eso es porque estamos[n]muy cerca. 夷A que s胤, Mona?[n][w][e]

[msg D08_BRIEFING_060_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]En efecto. Ya hemos recorrido[n]un setenta por ciento.[n][w][e]

[msg D08_BRIEFING_060_mes04 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3178 65535 0]Eso significa que a雨n nos queda[n]trabajo con los sistemas[n]de seguridad.[n][w][e]

[msg D08_BRIEFING_060_mes05 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No te preocupes por eso. Joker[n]ya nos ha ayudado un mont吋n.[n]Con su ayuda, 斡ser茨 pan comido![n][w][e]

[msg D08_BRIEFING_060_mes06 [Ann]]
[s][bup 0 4 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]T雨 ya pasas de pensar[n]t雨 solito, 夷eh?[n][w][e]

