[msg D03_BRIEFING_090_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7184 65535 0]Joder con las contrase隠as...[n]Los Palacios son una locura.[n][w][e]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Me pregunto c吋mo ser胤a tener[n]Palacios en vez de Personas.[n][w][e]

[msg D03_BRIEFING_090_mes02 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tu Palacio ser胤a un restaurante[n]de gyuudon, sin duda.[n][w][e]

[msg D03_BRIEFING_090_mes03 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]斡夷Y esa respuesta[n]tan directa de repente?![n]斡Cualquiera te lo discute![n][w][e]

[msg D03_BRIEFING_090_mes04 [Makoto]]
[s][bup 0 6 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Venga, no me hag茨is re胤r.[n]Estoy intentando centrarme[n]en nuestra operaci吋n.[n][w][e]

[msg D03_BRIEFING_090_mes05 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1169 65535 0]No me puedo creer que est姻is[n]tan tranquilos teniendo[n]el tesoro tan cerca...[n][w][e]

