[msg e259_501_mes01 [Voz mec茨nica]]
[s]Sistema bloqueado.[n]Introduzca el pin correcto.[n][w][e]

[msg e259_501_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7182 65535 0]夷Pin...? 夷Y con eso se abrir茨[n]una de las c茨maras?[n][w][e]

[msg e259_501_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm, hay algo escrito[n]encima del teclado num姻rico.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]或RICH位... C吋mo no, rico. Qu姻 asco...[n]夷C吋mo puede haber gente[n]tan obsesionada con el dinero?[n][w][e]

[msg e259_501_mes04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espera, 斡igual no es tan simple![n]夷Cre姻is que puede tener[n]algo que ver con ese diario?[n][w][e]

[msg e259_501_mes05 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Mm, d姻jame pensar... Si mal no[n]recuerdo, dec胤a [clr 2]R=C=0 I=1 H=2[clr 27].[n][w][e]

[msg e259_501_mes06 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Veis? 斡Son todas las letras[n]de la palabra 或RICH位![n][w][e]

[msg e259_501_mes07 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm. Merece la pena intentarlo.[n]夷Te encargas t雨, Joker?[n][w][e]

[sel e259_501_selA top]
[s]Lo averiguar姻.[f 2 7 0 0 106 1][e]
[s]Dentro de un rato.[f 2 7 0 0 106 1][e]

[msg e259_501_selA_0_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4194 65535 0]Lo dejamos en tus manos. Puede que[n]el tesoro est姻 pasado este punto.[n][w][e]

[msg e259_501_selA_0_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si no te aclaras, echa un vistazo[n]al [clr 2]diario[clr 27] de Kaneshiro.[n]Est茨 entre nuestras cosas.[n][w][e]

[msg e259_501_selA_1_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7079 65535 0]No tengas miedo.[n]No va a explotar ni nada[n]si la l胤as... digo yo.[n][w][e]

[msg e259_501_selA_1_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cierto. Si no hay otra manera[n]de avanzar, no perdemos nada[n]por intentarlo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si no te aclaras, echa un vistazo[n]al [clr 2]diario[clr 27] de Kaneshiro.[n]Est茨 entre nuestras cosas.[n][w][e]

[msg e259_501_mes08 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]El diario dec胤a [clr 2]R=C=0 I=1 H=2[clr 27].[n][w][e]

[msg e259_501_mes09 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Merece la pena intentarlo.[n]夷Te encargas t雨, Joker?[n][w][e]

[sel e259_501_selB top]
[s]Lo intentar姻.[f 2 7 0 0 106 1][e]
[s]Mejor no.[f 2 7 0 0 106 1][e]

[msg e259_501_OPEN_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7041 65535 0]Pero 斡夷qu姻...?![n]斡夷Se ha movido toda la c茨mara?![n][w][e]

[msg e259_501_OPEN_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Entonces mi deducci吋n[n]puede que sea correcta...[n][w][e]

[msg e259_501_OPEN_mes03 [Voz de Kaneshiro]]
[s][bup 0 207 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Dinero... Necesito m茨s dinero...[n]斡Tengo que hacerme m茨s rico![n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mientras sea rico,[n]puedo hacer lo que quiera...[n][w][e]

[msg e259_501_OPEN_mes04 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6184 65535 0]Esa voz... 斡Es Kaneshiro![n]斡夷Nos est茨 viendo?![n][w][e]

[msg e259_501_OPEN_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No creo.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Parece m茨s bien la voz de su[n]coraz吋n... A fin de cuentas, supongo[n]que solo le preocupa el dinero.[n][w][e]

[msg e259_501_OPEN_mes06 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7044 65535 0]Se dedica a chantajear a la gente[n]y a dejarlos sin un duro, 夷y aun[n]as胤 no es suficiente? Ser茨 mam吋n...[n][w][e]

[msg e259_501_OPEN_mes07 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A todo esto, 斡el mensaje[n]del diario era el c吋digo pin![n][w][e]

[msg e259_501_OPEN_mes08 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4180 65535 0]S胤, eso parece...[n]pero dudo que vaya a ser[n]tan f茨cil de aqu胤 en adelante.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El resto de las p茨ginas[n]del diario est茨n arrancadas.[n]Qui姻n sabe qu姻 pistas contendr茨n...[n][w][e]

[msg e259_501_OPEN_mes09 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, no seamos pesimistas.[n]Hay que seguir explorando[n]para intentar encontrar m茨s pistas.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Venga, vamos a buscar[n]esos n雨meros pin![n][w][e]

[msg D03_05_KINKO_KAITEN_DONE]
[s]No ha pasado nada.[n][w][e]

