[msg ALL_PICTURE_CHECK_EVENT_ [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1133 65535 0]Hay cuadros como estos[n]por todo el Palacio...[n][w][e]

[msg ALL_PICTURE_CHECK_EVENT__2 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Desde que hemos llegado,[n]siento que nos observan.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ahora que ya sabemos m茨s,[n]entiendo mejor la sensaci吋n.[n][w][e]

[msg ALL_PICTURE_CHECK_EVENT__3 [Yusuke]]
[s][bup 0 5 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4047 65535 0]Me suena que este alumno[n]hab胤a dejado la pintura. Parece[n]que no quieren seguir con ello...[n][w][e]

