[msg D07_02_e411_041_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7156 65535 0]S胤, estamos de vuelta[n]en la sala principal.[n][w][e]

[msg D07_02_e411_041_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Y sin ninguna informaci吋n que valga[n]la pena sobre el presidente[n]de la empresa inform茨tica.[n][w][e]

[msg D07_02_e411_041_mes03 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Casi nunca sale de su habitaci吋n![n]斡Nadie lo ha visto por aqu胤![n][w][e]

[msg D07_02_e411_041_mes04 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4192 65535 0]Mmm... Si no sale casi nunca, es[n]que s胤 que sale en ocasiones,[n]夷verdad?[n][w][e]

[msg D07_02_e411_041_mes05 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero tendr茨 que salir para ir al[n]ba隠o, 夷no? 斡Yo sal胤a de la[n]m胤a para eso![n][w][e]

[msg D07_02_e411_041_mes06 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero las habitaciones tienen[n]aseos... 夷Y para comer?[n][w][e]

[msg D07_02_e411_041_mes07 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9098 65535 0]Una llamada basta para que te[n]lleven la comida a la habitaci吋n.[n][w][e]

[sel D07_02_e411_041_selA top]
[s]Por ah胤 podremos entrar.[e]
[s]夷Y qui姻n hace la entrega?[e]

[msg D07_02_e411_041_selA_0_m [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2022 65535 0]Tienes raz吋n. Aunque este lugar[n]solo sea una cognici吋n, tambi姻n[n]tiene restaurantes y bares.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si el presidente de la empresa[n]inform茨tica no sale nunca,[n]alguien le llevar茨 la comida.[n][w][e]

[msg D07_02_e411_041_selA_1_m [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2197 65535 0]Bien visto. Aunque este lugar[n]solo sea una cognici吋n, tambi姻n[n]tiene restaurantes y bares.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si el presidente de la empresa[n]inform茨tica no sale nunca,[n]alguien le llevar茨 la comida.[n][w][e]

[msg D07_02_e411_041_mes08 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6152 65535 0]Ah, o sea, 斡que tambi姻n pillemos[n]informaci吋n en los restaurantes![n]斡Buena idea, Joker! 斡Ah, y Queen![n][w][e]

