[msg D07_BRIEFING_200_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7184 65535 0]Ya nos hemos pateado[n]todo el Palacio, 夷no? Podemos[n]enviar el aviso cuando queramos.[n][w][e]

[msg D07_BRIEFING_200_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tranquilidad. Investigar[n]la distribuci吋n tambi姻n puede ser[n]雨til. Hay que pensarlo bien.[n][w][e]

[msg D07_BRIEFING_200_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Como siempre, queda[n]en manos de Joker decidir[n]cu茨ndo enviamos el aviso.[n][w][e]

