[msg D02_SP_ABILITY_START_00]
[s]★仮テキスト[n]特性解禁イベント・開始[n][w][e]

[msg D02_SP_ABILITY_START_01]
[s]★仮テキスト[n]特性解禁イベント・終了[n][w][e]

[msg EV_SP_ABILITY_OPEN_START [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1052 65535 0]Chicos, es la primera infiltraci吋n[n]en la que Fox estar茨 desde[n]el principio. 斡Hag茨mosla bien![n][w][e]

[msg EV_SP_ABILITY_OPEN_START_2 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 12018 65535 0]Parece que te va bien, recluso.[n][w][e]

[msg EV_SP_ABILITY_OPEN_START_3 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 55232 65535 0]Nuestro maestro desea hablar[n]contigo. Pasa.[n][w][e]

[msg EV_SP_ABILITY_OPEN_END_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1018 65535 0]斡Oye, Joker! [n][w][e]

[msg EV_SP_ABILITY_OPEN_END_0_2 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1026 65535 0]夷Qu姻 haces ah胤 parado?[n][w][e]

[msg EV_SP_ABILITY_OPEN_END_0_3 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Espabila! Eres un miembro[n]imprescindible del equipo.[n][w][e]

[msg dummy_mes]
[s]...[n][w][e]

