[msg e382_300_mes01 [Sombra]]
[s]Bienvenidos al campo de batalla,[n]donde el dolor se fragua con[n]las fulgurantes ascuas de la vida.[n][w][e]
[s]Ah, que sois vosotros... Ya[n]nos hab胤a avisado la directora.[n][w][e]

[msg e382_300_mes02 [Ryuji]]
[s][bup 0 2 102 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7043 65535 0]夷C吋mo? 斡夷Y t雨 qu姻 co隠o[n]sabes de nosotros?![n][w][e]

[msg e382_300_mes03 [Sombra]]
[s]Veo que pierdes la paciencia[n]con facilidad. Estupendo. Si no[n]fuera as胤, ser胤a muy aburrido.[n][w][e]

[msg e382_300_mes04 [Sombra]]
[s]Antes de explicar nada,[n]necesito que me confirm姻is algo.[n]夷Dispon姻is de [clr 2]10 000[clr 27] monedas?[n][w][e]

[msg e382_300_mes05 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Eh, 夷qu姻 dices? Pues no.[n][w][e]

[msg e382_300_mes06 [Sombra]]
[s]Pues entonces nada.[n]Si no pod姻is pagar la inscripci吋n,[n]os qued茨is sin participar.[n][w][e]
[s]Hacedme caso y no volv茨is hasta[n]que teng茨is suficiente dinero.[n][w][e]

[msg e382_300_mes07 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm, parece que hay que pagar[n]una cuota en todos los juegos[n]de este piso.[n][w][e]

[msg e382_300_mes08 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mm, parece que hay que pagar[n]una cuota para este juego.[n][w][e]

[msg e382_300_mes09 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2099 65535 0]No tenemos m茨s remedio que seguir[n]las normas. Hay que buscar[n]una forma de conseguir monedas.[n][w][e]

[msg e382_300_mes10 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3164 65535 0]斡Por supuesto que las tenemos![n][w][e]

[msg e382_300_mes11 [Sombra]]
[s]Vaya, veo que no perd姻is el tiempo.[n]Bien, pues os explicar姻 en qu姻[n]consiste el juego.[n][w][e]
[s]El objetivo es alzarse con la[n]victoria en un tr胤o de encarnizados[n]enfrentamientos uno contra uno.[n][w][e]
[s]Tened en cuenta que esta es [n]la c雨spide del casino.[n][w][e]
[s]Nuestros clientes vip suelen enviar[n]a sustitutos que luchan[n]a muerte en su nombre.[n][w][e]
[s]Y los invitados apuestan[n]sobre qui姻n saldr茨 vencedor.[n][w][e]

[msg e382_300_mes12 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Aqu胤 tambi姻n? Pero qu姻 puto asco.[n][w][e]

[msg e382_300_mes13 [Akechi]]
[s][bup 0 9 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Creo que todo este piso[n]funciona de forma similar.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Correr un peque隠o riesgo[n]por la posibilidad de ganar mucho[n]es una estrategia 吋ptima.[n][w][e]

[msg e382_300_mes14 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Podemos participar sin sustituto?[n][w][e]

[msg e382_300_mes15 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1190 65535 0]Para el juego anterior[n]no necesitamos ninguno.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A lo mejor para este tampoco.[n][w][e]

[msg e382_300_mes16 [Sombra]]
[s]Por irritante que resulte, tienes[n]raz吋n. Os animo a participar.[n][w][e]
[s]Os pod姻is registrar[n]en aquel mostrador.[n][w][e]

