[msg MSG_e296_213_000 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Aqu胤 tambi姻n hay un bloque[n]de piedra. Pero... no hay nada[n]legible inscrito en la superficie.[n][w][e]

[msg MSG_e296_213_001 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]A m胤 me parece bastante in雨til.[n]夷Qu姻 quieres hacer, Joker?[n][w][e]

[sel SEL_e296_213_002 top]
[s]Examin姻moslo mejor.[f 2 7 0 0 106 1][e]
[s]Vamos a ver otra cosa.[e]

[msg MSG_e296_213_003 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Oooh! 斡Brilla![n][w][e]

[msg MSG_e296_213_004 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Mmm, los artefactos[n]que controlan los murales parecen[n]reaccionar de forma similar.[n][w][e]

[msg MSG_e296_213_005 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6159 65535 0]斡Ha aparecido algo! 斡Pone [clr 2]A01010[clr 27]![n][w][e]

[msg MSG_e296_213_006 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiz茨 sea una pista de alg雨n tipo.[n]En cualquier caso, debemos[n]buscar por si ha cambiado algo.[n][w][e]

[msg MSG_e296_213_007 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Seguro? Esa cosa[n]es supersospechosa.[n][w][e]

[msg MSG_e296_213_AF01_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No es algo raro este bloque?[n]夷Crees que deber胤amos mirarlo?[n][w][e]

[msg MSG_e296_213_AF02_000 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Algo ha aparecido sobre el bloque[n]de piedra. [clr 2]A01010[clr 27]... 夷Crees[n]que ser茨 alg雨n tipo de c吋digo?[n][w][e]

[msg MSG_e296_213_AF02_000_AF [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷No hemos resuelto ya[n]el misterio de este bloque?[n]Deber胤amos ir a ver otra cosa.[n][w][e]

[msg MSG_e296_214_000 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6029 65535 0]P-pero 斡夷qu姻...?![n][w][e]

[msg MSG_e296_214_001 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]As胤 que el v胤nculo de esta cosa[n]al bloque de piedra[n]es lo que le da energ胤a...[n][w][e]

[msg MSG_e296_214_002 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4023 65535 0]Un artilugio impresionante.[n]夷Por qu姻 no lo examinamos mejor?[n][w][e]

