[msg D10_BRIEFING_090_mes01 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 3127 65535 0]Gran parte de esta tecnolog胤a es[n]futurista, pero el formato de los[n]v胤deos de Maruki es antiguo.[n][w][e]

[msg D10_BRIEFING_090_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, es verdad.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Ser茨 que piensa[n]que el pasado est茨 obsoleto?[n][w][e]

[msg D10_BRIEFING_090_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1020 65535 0]Podr胤a ser...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]De todos modos, a雨n tenemos mucho[n]que averiguar. Ahora que la puerta[n]est茨 abierta, pong茨monos en marcha.[n][w][e]

