[msg D01_BRIEFING_010_mes01 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7155 65535 0]Oye, 夷crees que nos falta[n]mucho para llegar al tesoro?[n][w][e]

[msg D01_BRIEFING_010_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero si acabamos de entrar. Por la[n]forma que tiene, dir胤a que[n]nos queda mucho.[n][w][e]

[msg D01_BRIEFING_010_mes03 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6162 65535 0]Todav胤a no me creo que una[n]aplicaci吋n nos trajera hasta aqu胤.[n][w][e]

[msg D01_BRIEFING_010_mes04 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, todos no la necesitamos...[n]El gato puede venir cuando quiera.[n][w][e]

[msg D01_BRIEFING_010_mes05 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1046 65535 0]斡Que no soy un gato![n][w][e]

[msg D01_BRIEFING_010_mes06 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Y qu姻 pasa con esa especie[n]de soldados que est茨n[n]con Kamoshida?[n][w][e]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Se transforman en monstruos[n]cuando luchamos contra ellos.[n][w][e]

[msg D01_BRIEFING_010_mes07 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]夷Qu姻? Ah, te refieres[n]a las sombras.[n][w][e]

[msg D01_BRIEFING_010_mes08 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 son?[n][w][e]

[msg D01_BRIEFING_010_mes09 [Ryuji]]
[s][bup 0 2 105 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]S胤, a m胤 tambi姻n me gustar胤a[n]saberlo. 夷De qu姻 van?[n][w][e]

[msg D01_BRIEFING_010_mes10 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1038 65535 0]Explicarlo es... complicado.[n]夷Quer姻is saberlo?[n][w][e]

[sel D01_BRIEFING_010_selA top]
[s]Pues s胤.[e]
[s]Ahora mismo no.[e]

[msg D01_BRIEFING_010_selA_0_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1155 65535 0]En lo m茨s profundo del coraz吋n de[n]cada humano, yace su verdadera[n]personalidad, es decir, su sombra.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No es que los guardias[n]se transformen en monstruos,[n]sino que en realidad son as胤.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]La raz吋n por la que parecen dioses[n]y criaturas mitol吋gicas es porque[n]son fruto de la mente humana.[n][w][e]

[msg D01_BRIEFING_010_selA_0__2 [Ann]]
[s][bup 0 4 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 6021 65535 0]Ha-hala...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 夷qu姻 hacen en el[n]castillo de Kamoshida?[n][w][e]

[msg D01_BRIEFING_010_selA_0__3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1165 65535 0]Al parecer, la distorsi吋n de[n]este sitio las atrae.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Cuando ya est茨n aqu胤, cambian[n]de forma y se convierten en[n]sirvientes del se隠or del Palacio.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Si lo piensas bien, el se隠or[n]del Palacio solo es la sombra[n]del due隠o del Palacio...[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiz茨 estos lugares tengan que[n]ver con los mundos de nuestra[n]mente, el inconsciente colectivo...[n][w][e]

[msg D01_BRIEFING_010_selA_0__4 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7020 65535 0]Ah, vale.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 斡no tiene sentido![n][w][e]

[msg D01_BRIEFING_010_selA_0__5 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1169 65535 0]Sab胤a que ibas a decir eso.[n][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Bueno, no le deis muchas vueltas.[n]Son enemigos,[n]as胤 que no baj姻is la guardia.[n][w][e]

[msg D01_BRIEFING_010_selA_1_ [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1157 65535 0]S胤, no tenemos tiempo para[n]andar de ch茨chara.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quedaos con que son enemigos.[n]No baj姻is la guardia.[n][w][e]

