[msg MSG_SHOP_AMAZONES_START]
[s]He entrado en la p茨gina de Amazona.[n][w][e]

[msg MSG_SHOP_YAMINET_START]
[s]He entrado en la p茨gina[n]de Art胤culos sospechosos.[n][w][e]

[msg MSG_OPEN_DOUBLE_SHOP]
[s]Puede que eche un vistazo[n]en Art胤culos sospechosos.[n][w][e]

[sel MSG_SHOP_SELECT_SEL top]
[s]Acceder[e]
[s]Cancelar[e]

[msg MSG_CLOSE_DOUBLE_SHOP]
[s]Ahora mismo no quiero[n]mirar ninguna p茨gina web.[n][w][e]

