[msg ALL_PICTURE_CHECK_EVENT_ [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7175 65535 0]Este tiene nombre... y edad.[n][w][e]

[msg ALL_PICTURE_CHECK_EVENT__2 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7047 65535 0]As胤 que Madarame us吋 el talento[n]de este y luego se deshizo de 姻l[n]como con todos los dem茨s, 夷eh?[n][w][e]

[msg ALL_PICTURE_CHECK_EVENT__3 [Yusuke]]
[s][bup 0 5 103 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4026 65535 0]Era de los alumnos m茨s j吋venes,[n]pero no dur吋 mucho.[n][w][e]

