[msg e259_130_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4169 65535 0]Por el dise隠o interior...[n]dir胤a que estamos en el banco.[n]Parece que el plan ha salido bien.[n][w][e]

[msg e259_130_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No recuerdo haber visto este sitio[n]la 雨ltima vez... 夷D吋nde estamos exactamente?[n][w][e]

[msg e259_130_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Tiene que haber un mapa en alg雨n[n]sitio. Vamos a intentar explorar[n]y buscar el tesoro por ahora.[n][w][e]

[msg D03_154_02_COMBINED_TUTO [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 1 0 0]斡E-espera! 斡夷Qu姻 es eso?![n][w][e]

[msg D03_154_02_COMBINED_TUTO_2 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 2 0 0]Una sombra con forma de perro.[n]Parece que este sitio tiene[n]sus propios perros guardianes.[n][w][e]

[msg D03_154_02_COMBINED_TUTO_3 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 3 0 0]Mmm, esto no me gusta nada.[n][w][e]

[msg D03_154_02_COMBINED_TUTO_4 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 4 0 0]夷Porque eres un gato?[n][w][e]

[msg D03_154_02_COMBINED_TUTO_5 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 5 0 0]斡No, porque seguramente[n]pueda oler a los intrusos[n]y perseguirnos muy r茨pido![n][w][e]

[msg D03_154_02_COMBINED_TUTO_6 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 6 0 0]Pero, si al final l胤a mucho alboroto,[n]podr胤amos sacarle provecho.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 7 0 0]斡Podremos utilizar[n]nuestro movimiento final sorpresa![n][w][e]

[msg D03_154_02_COMBINED_TUTO_7 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 8 0 0]夷或Nuestro位? 夷C吋mo que 或nuestro位?[n][w][e]

[msg D03_154_02_COMBINED_TUTO_8 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 9 0 0]Lamento la interrupci吋n, pero...[n]斡nos han descubierto![n][w][e]

