[msg QUEST_40_ENTER_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Mirad. Esa debe de ser[n]la sombra de Naguri.[n][w][e]

[msg QUEST_40_ENTER_mes01f [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah胤 est茨 la sombra de Naguri...[n][w][e]

[msg QUEST_40_ENTER_mes02 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Tiene mirada de loco.[n][w][e]

[msg QUEST_40_ENTER_mes03 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Dicen que ataca a la gente[n]indiscriminadamente. Supongo[n]que ha perdido la raz吋n.[n][w][e]

[msg QUEST_40_ENTER_mes04 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]Si no logramos despertar[n]su coraz吋n, no estar姻[n]tranquila yendo por la calle.[n][w][e]

[msg QUEST_40_ENTER_mes05 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1099 65535 0]Tenemos que hacerlo.[n][w][e]

[msg MSG_022_0_0 [Sombra de Naguri]]
[s][vp 8 2 1 46657 65535 0]Eh, 夷sois los Ladrones Fantasma?[n]夷Hab姻is venido a verme?[n]Vaya, supongo que soy famoso.[n][w][e]

[msg MSG_023_0_0 [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Madre m胤a, es uno[n]de esos t胤os irritantes...[n][w][e]

[msg MSG_024_0_0 [Sombra de Naguri]]
[s][vp 1 0 0 0 0 0]Entonces, 夷puedo ayudaros?[n]No hab姻is venido a pelear[n]contra m胤, 夷verdad? No ser茨 eso.[n][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Deja de hacerte el loco.[n]Eres un loco violento.[n][w][e]

[msg MSG_026_0_0 [Sombra de Naguri]]
[s][vp 1 0 0 0 0 0]Tan solo ayudo al mundo.[n]Hay un problema de superpoblaci吋n[n]por el exceso de ancianos.[n][w][e]
[s][vp 1 0 0 0 0 0]Consideradlo mi aportaci吋n personal[n]a la justicia. Pero 斡no tiene nada[n]que ver con vosotros, mocosos![n][w][e]

[msg MSG_027_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2047 65535 0]Yo te ense隠ar姻 lo que es[n]realmente la justicia.[n][w][e]

[msg MSG_028_0_0 [Sombra de Naguri]]
[s][vp 8 2 1 46659 65535 0]Tanto hablar me est茨 irritando.[n]斡Os voy a machacar![n][w][e]

[msg QUEST_40_BOSS_EV_mes04 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Argh. 斡Vamos a por 姻l, Joker![n][w][e]

[msg MSG_030_0_0 [Sombra de Naguri]]
[s][vp 8 2 1 46666 65535 0]夷Qu姻...? 夷Qu姻 he hecho?[n]夷Solo hac胤a da隠o a la gente[n]para desahogar mi frustraci吋n?[n][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Pedir perd吋n no basta.[n]Has atacado y hecho da隠o[n]a mucha gente, 夷sabes?[n][w][e]

[msg MSG_032_0_0 [Sombra de Naguri]]
[s][vp 1 0 0 0 0 0]Yo... 夷Qu姻 puedo hacer?[n][w][e]

[sel SEL_033_0_0 top]
[s]Entr姻gate.[e]
[s]夷Qui姻n sabe?[e]
[s]夷En serio lo preguntas?[e]

[msg MSG_034_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Cu姻ntaselo todo a la polic胤a.[n][w][e]

[msg MSG_035_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Entr姻gate y confi姻salo todo.[n][w][e]

[msg MSG_036_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Entr姻gate y confi姻salo todo.[n][w][e]

[msg MSG_037_0_0 [Sombra de Naguri]]
[s][vp 1 0 0 0 0 0]Entregarme... Supongo[n]que no hay otro camino.[n][w][e]
[s][vp 1 0 0 0 0 0]He estado haciendo algo espantoso.[n]Me merezco un buen castigo...[n][w][e]

[msg MSG_038_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Hemos tenido suerte de atraparlo[n]antes de que muriera nadie.[n]Somos sumamente afortunados.[n][w][e]

[msg QUEST_40_BATTLE_END_mes0 [Ryuji]]
[s][bup 0 2 100 0 0]斡Genial, tenemos el tesoro![n][w][e]

[msg QUEST_40_BATTLE_END_mes0_2 [Sombra de Naguri]]
[s]斡Uaaaaah![n][w][e]

[msg QUEST_40_BATTLE_END_mes0_3 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡Ni se te ocurra repetirlo![n]M茨s te vale pagar[n]por todos tus cr胤menes.[n][w][e]

