[msg D03_BRIEFING_110_mes01 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7045 65535 0]Chachi, ahora solo tenemos[n]que enviar el aviso.[n][w][e]

[msg D03_BRIEFING_110_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]El Palacio desaparecer茨 en cuanto[n]cojamos el tesoro, 夷no? Pues quiz茨[n]a雨n quede mucho por hacer aqu胤.[n][w][e]

[msg D03_BRIEFING_110_mes03 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1157 65535 0]S胤. Aunque tengamos fecha l胤mite,[n]enviar el aviso deprisa y corriendo[n]no tiene por qu姻 ser lo mejor.[n][w][e]
[s]En fin, Joker, esa decisi吋n[n]es tuya en 雨ltima instancia.[n][w][e]

