[msg D08_01_e440_030_mes01 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 斡夷qu姻 cojones...?![n][w][e]

[msg D08_01_e440_030_mes02 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Da la impresi吋n de no tener fin...[n]夷Ad吋nde conducir茨?[n][w][e]

[msg D08_01_e440_030_mes03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]No me esperaba para nada[n]que quedara tanto por recorrer,[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]pero cada vez siento[n]m茨s cerca el tesoro.[n]Vamos por buen camino.[n][w][e]

