[msg D04_03_e296_323_mes01 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4160 65535 0]Mmm, este ata雨d tiene un dise隠o[n]distinto al resto. 夷No despierta[n]vuestra curiosidad?[n][w][e]

[msg D04_03_e296_323_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Qu姻 raro... 夷Por qu姻[n]no le echamos un vistazo?[n][w][e]

[sel D04_03_e296_323_selA top]
[s]Hag茨moslo.[e]
[s]Deber胤amos dejarlo.[e]

[msg D04_03_e296_323_selA_0_m [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]......[n][w][e]

[msg D04_03_e296_323_selA_1_m [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 4026 65535 0]Muy bien. Si deseas ser[n]cauteloso, no te detendr姻.[n][w][e]

[msg D04_03_e296_323_mes03 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 7040 65535 0]斡Hala, no puedo creer[n]que hayas visto que era un truco![n][w][e]

[msg D04_03_e296_323_AF01_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este ata雨d a雨n me llama[n]la atenci吋n. 夷Investigamos, Joker?[n][w][e]

[msg MSG_e296_323_AF02_000 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, 斡eso tiene que ser[n]un bot吋n secreto o algo as胤![n]斡Probemos a pulsarlo![n][w][e]

[sel SEL_e296_323_AF02_001 top]
[s]Puls姻moslo.[e]
[s]Ahora no.[e]

[msg MSG_e296_323_AF02_002 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]斡夷Q-qu姻 ha sido eso?![n]斡Acabo de o胤r algo![n][w][e]

[msg MSG_e296_323_AF02_003 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Espera, 斡夷no vas a pulsarlo?![n]Supongo que es muy sospechoso...[n][w][e]

[msg D04_03_e296_323_AF03_mes [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Este bot吋n ya est茨 activado.[n][w][e]

[msg MSG_e296_324_000 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 2019 65535 0]Mmm. Parece que hay un bot吋n.[n]夷Quieres que lo pulsemos?[n][w][e]

[sel SEL_e296_324_001 top]
[s]Puls姻moslo.[e]
[s]Ahora no.[e]

[msg MSG_e296_324_002 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1183 65535 0]斡Ah! 斡Se ha movido![n][w][e]

[msg MSG_e296_324_003 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1157 65535 0]S胤, supongo que no hay necesidad[n]de precipitarse. Antes debemos[n]explorar la zona con m茨s cuidado.[n][w][e]

[msg D04_03_e296_324_BF_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 夷qu姻...? Noto una corriente[n]que sale del interior del ata雨d.[n][w][e]

[msg D04_03_e296_324_BF_mes02 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Quiz茨 haya una apertura por[n]detr茨s? Pero no creo que se pueda[n]mover como es debido.[n][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Quiz茨 haya otro modo[n]de poder hacerlo...[n][w][e]

[msg D04_03_e296_324_BF02_mes [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Todav胤a sigo d茨ndole vueltas[n]al ata雨d. Creo que est茨 conectado[n]a un mecanismo en alg雨n sitio.[n][w][e]

