[msg MSG_UFO_Start_Contents01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Anda, una m茨quina de gancho.[n]El premio actual es... 夷Jack Frost?[n][w][e]

[msg MSG_UFO_Start_Contents02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Anda, una m茨quina de gancho.[n]El premio actual es...[n]夷un mu隠eco de Big Bang Burger?[n][w][e]

[msg MSG_UFO_Start_Contents03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Anda, una m茨quina de gancho.[n]El premio actual es... 夷Segur胤n?[n][w][e]

[msg MSG_UFO_Start_Contents04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Anda, una m茨quina de gancho.[n]El premio actual es... 夷Lexy?[n][w][e]

[msg MSG_UFO_Start_Contents05 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Anda, una m茨quina de gancho.[n]El premio actual es...[n]夷un hombre oveja descarriado?[n][w][e]

[msg MSG_UFO_Start_Contents06 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Anda, una m茨quina de gancho.[n]El premio es... 夷Frost oscuro?[n][w][e]

[msg MSG_UFO_Start_Contents07 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Anda, una m茨quina de gancho.[n]El premio es... 夷Buchimaru?[n][w][e]

[msg MSG_UFO_Start_Contents08 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0]Anda, una m茨quina de gancho.[n]El premio es... 夷Jagao?[n][w][e]

[msg MSG_UFO_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Son 300 yenes por intento.[n]夷Te atreves a probar?[n][w][e]

[msg MSG_UFO_Start_Lucky [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Parece que los d胤as que terminan[n]en siete dan buena suerte.[n]El gancho va mejor de lo normal.[n][w][e]

[sel SEL_UFO_Start_Q top]
[s]Probemos.[e]
[s]Tal vez en otro momento.[e]

[msg MSG_UFO_Cancel [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ah, 夷no vas a jugar?[n][w][e]

[msg MSG_UFO_Line_YOKO_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1174 65535 0]Vale, 夷est茨s listo? 斡Ya![n][w][e]

[msg MSG_UFO_Line_OKU_Start [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Este es el momento crucial![n]Cuidado... 斡Cuidado![n][w][e]

[msg MSG_UFO_CatchOK [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0]斡Toma! 斡Lo has conseguido![n][w][e]

[msg MSG_UFO_CatchNG [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1169 65535 0]Joo... No lo has conseguido.[n][w][e]

[msg MSG_UFO_CatchNG_kiyou [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Estoy seguro de que para triunfar[n]en esto hay que tener bastante[n][f 4 11 2][clr 26][f 4 12 2][clr 27].[n][w][e]

[msg MSG_UFO_ItemGet01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0]斡Qu姻 guay![n]斡Has conseguido el premio![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Un mu隠eco de Jack Frost, 夷eh?[n]斡Col吋calo en tu habitaci吋n[n]cuando volvamos![n][w][e]

[msg MSG_UFO_ItemGet02 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0]斡Qu姻 guay![n]斡Has conseguido el premio![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Un mu隠eco de Big Bang Burger, 夷eh?[n]斡Col吋calo en tu habitaci吋n[n]cuando volvamos![n][w][e]

[msg MSG_UFO_ItemGet03 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0]斡Qu姻 guay![n]斡Has conseguido el premio![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Un mu隠eco de Segur胤n, 夷eh?[n]斡Col吋calo en tu habitaci吋n[n]cuando volvamos![n][w][e]

[msg MSG_UFO_ItemGet04 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0]斡Qu姻 guay![n]斡Has conseguido el premio![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Un mu隠eco de Lexy, 夷eh?[n]斡Col吋calo en tu habitaci吋n[n]cuando volvamos![n][w][e]

[msg MSG_UFO_ItemGet05 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0]斡Qu姻 guay![n]斡Has conseguido el premio![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Un mu隠eco de un hombre oveja[n]descarriado, 夷eh? 斡Col吋calo en[n]tu habitaci吋n cuando volvamos![n][w][e]

[msg MSG_UFO_ItemGet06 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0]斡Qu姻 guay![n]斡Has conseguido el premio![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Un mu隠eco de Frost oscuro, 夷eh?[n]斡Col吋calo en tu habitaci吋n[n]cuando volvamos![n][w][e]

[msg MSG_UFO_ItemGet07 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0]斡Qu姻 guay![n]斡Has conseguido el premio![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Un mu隠eco Buchimaru, 夷eh?[n]斡Col吋calo en tu habitaci吋n[n]cuando volvamos![n][w][e]

[msg MSG_UFO_ItemGet08 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0]斡Qu姻 guay![n]斡Has conseguido el premio![n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Un mu隠eco Jagao, 夷eh?[n]斡Col吋calo en tu habitaci吋n[n]cuando volvamos![n][w][e]

[msg MSG_UFO_NOITEM [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Es hora de dejarlo.[n]Vuelve a casa y descansa.[n][w][e]

[msg MSG_UFO_NOMONEY [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Es una m茨quina de gancho.[n]Cada intento cuesta 300 yenes.[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Parece que no tienes dinero[n]suficiente para jugar. Qu姻 l茨stima.[n][w][e]

[msg MSG_NowItemAlready_Get [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1057 65535 0]夷Eh? 夷No hab胤as ganado[n]ya este premio?[n][w][e]

