[msg QUEST_59_ENTER_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1167 65535 0]Y ah胤 las tenemos: las[n]sombras de los padres de Kana.[n][w][e]

[msg QUEST_59_ENTER_mes01f [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9178 65535 0]Ah胤 est茨n, las sombras[n]de los padres de Kana.[n][w][e]

[msg QUEST_59_ENTER_mes02 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]夷Por qu姻 los padres siempre[n]intentan controlar a sus hijos?[n][w][e]

[msg QUEST_59_ENTER_mes03 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]No te rayes con eso[n]y centr姻monos en ayudar a la hija.[n][w][e]

[msg QUEST_59_ENTER_mes04 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 0 65535 0]斡Hay que despertar sus corazones[n]para salvar a la amiga de Futaba![n][w][e]

[msg QUEST_59_ENTER_mes05 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 9108 65535 0]斡V-vamos![n][w][e]

[msg MSG_000_0_0 [Sombra del se隠or Magario]]
[s][vp 8 2 1 46809 65535 0]Malas apuestas en las carreras,[n]p姻rdidas, deudas, otra vez malas[n]apuestas, m茨s p姻rdidas, m茨s deudas...[n][w][e]
[s][vp 1 0 0 0 0 0]斡夷Por qu姻 tenemos tan mala[n]suerte?! 斡No salimos nunca[n]de esta espiral de pobreza![n][w][e]

[msg MSG_001_0_0 [Sombra de la se隠ora Magario]]
[s][vp 8 2 1 47651 65535 0]No pod胤amos dejarla ir a clase.[n]Ten胤a que ganar dinero.[n][w][e]
[s][vp 1 0 0 0 0 0]De su atractivo, de su aspecto de[n]ni隠a buena, de lo que fuera...[n]Ten胤amos que aprovecharlo.[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][vp 1 0 0 0 0 0]斡夷Y os hac姻is llamar padres?![n][w][e]
[s][vp 1 0 0 0 0 0]斡Kana est茨 sufriendo mucho[n]por vuestra culpa![n][w][e]

[msg MSG_003_0_0 [Sombra de la se隠ora Magario]]
[s][vp 1 0 0 0 0 0]No est茨 bien... pero 斡tiene[n]que darnos beneficios![n][w][e]

[msg MSG_004_0_0 [Sombra del se隠or Magario]]
[s][vp 1 0 0 0 0 0]斡Kana tiene que ganar dinero[n]o la familia acabar茨 destrozada![n][w][e]

[sel SEL_005_0_0 top]
[s]Conseguid un trabajo de verdad.[e]
[s]No explot姻is a vuestra hija.[e]

[msg MSG_006_0_0 [Sombra del se隠or Magario]]
[s][vp 1 0 0 0 0 0]斡No es culpa nuestra![n]斡Hemos tenido mala suerte![n][w][e]

[msg MSG_007_0_0 [Sombra de la se隠ora Magario]]
[s][vp 8 2 1 47662 65535 0]Que se aguante Kana.[n]斡Alg雨n d胤a ganaremos el gordo[n]y los tres seremos felices![n][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][vp 1 0 0 0 0 0]Lo sab胤a... Estos dos est茨n[n]podridos hasta la m姻dula.[n][w][e]
[s][vp 1 0 0 0 0 0]斡Joker, salva a Kana![n][w][e]

[msg MSG_009_0_0 [Sombra del se隠or Magario]]
[s][vp 8 2 1 46817 65535 0]No nos quedaba otra...[n]Est茨bamos endeudadoshasta las cejas...[n][w][e]

[msg MSG_010_0_0 [Sombra de la se隠ora Magario]]
[s][vp 1 0 0 0 0 0]Somos muy malos padres...[n][w][e]

[sel SEL_011_0_0 top]
[s]Pues sed mejores padres.[e]
[s]Sed humildes de ahora en adelante.[e]

[msg MSG_012_0_0 [Sombra del se隠or Magario]]
[s][vp 1 0 0 0 0 0]Lo s姻, tengo que cambiar...[n][w][e]
[s][vp 1 0 0 0 0 0]No dejar姻 que Kana vuelva[n]a hacer ese tipo de trabajos.[n][w][e]

[msg MSG_013_0_0 [Sombra de la se隠ora Magario]]
[s][vp 1 0 0 0 0 0]Lo siento, Kana...[n][w][e]
[s][vp 1 0 0 0 0 0]Reestructuraremos la deuda.[n]Somos nosotros quienes tenemos[n]que pagar, no t雨.[n][w][e]
[s][vp 1 0 0 0 0 0]Dejar姻 de apostar y buscar姻[n]trabajo. Pagar姻 todas[n]las deudas poquito a poco.[n][w][e]

[msg MSG_014_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][vp 1 0 0 0 0 0]斡Eso es lo que tienes que hacer![n]斡No vuelvas a hacer sufrir a Kana![n][w][e]

[msg MSG_015_0_0 [Sombra del se隠or Magario]]
[s][vp 1 0 0 0 0 0]Empec姻 a apostar para ganar dinero,[n]pero acab姻 obligando a[n]Kana a hacer cosas asquerosas.[n][w][e]
[s][vp 1 0 0 0 0 0]Y pensar que yo solo quer胤a[n]que mi hija tuviese algo[n]que llevarse a la boca...[n][w][e]

[msg MSG_016_0_0 [Sombra de la se隠ora Magario]]
[s][vp 1 0 0 0 0 0]Tienes raz吋n, cielo,[n]pero, antes, hagamos[n]a Kana feliz...[n][w][e]

[msg MSG_017_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][vp 1 0 0 0 0 0]Gracias, Joker. Creo que Kana[n]estar茨 bien a partir de ahora.[n][w][e]

[msg MND_018_0_0]
[s][vp 1 0 0 0 0 0]Parece que los Magario[n]han despertado.[n]Lo hablar姻 con Kana.[n][w][e]

