[msg D08_BRIEFING_030_mes01 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1027 65535 0]Esa celda solitaria...[n][w][e]

[msg D08_BRIEFING_030_mes02 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Desde luego que tiene toda la pinta[n]de que hay algo malo.[n]Mona, 夷de verdad estuviste ah胤?[n][w][e]

[msg D08_BRIEFING_030_mes03 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]夷Qu姻 es lo que Mona no recuerda[n]sobre guiarnos?[n][w][e]

[msg D08_BRIEFING_030_mes04 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1111 65535 0]Lo siento, todo es culpa m胤a.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Pero 斡creo que descubrir姻 algo[n]si sigo avanzando![n][w][e]
[s]斡Ayudadme, venga![n][w][e]

[msg D08_BRIEFING_030_mes05 [Haru]]
[s][bup 0 7 103 0 0]Por supuesto, Mona. 夷No, Joker?[n][w][e]

