[msg DUMMY]
[s]Prueba[n][w][e]

[msg TV_PROGRAM_TEST]
[s]Esto es lo que sale en la tele el [var 1]/[var 0].[n][w][e]

[msg TV_CH01_DEFAULT]
[s]Parece que est茨n informando[n]sobre los esc茨ndalos empresariales[n]m茨s recientes.[n][w][e]

[msg TV_NEWS_DEFAULT_000_00 [Presentador de telediario]]
[s]夷Quieren saber qu姻 tiempo har茨[n]ma隠ana? A continuaci吋n,[n]la previsi吋n del tiempo.[n][w][e]

[msg TV_NEWS_DEFAULT_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que no hay nada interesante[n]en las noticias.[n][w][e]

[msg TV_NEWS_0409_000_00 [Presentador de telediario]]
[s]Ha empezado un nuevo a隠o escolar.[n]Los centros educativos celebran[n]ceremonias de inicio de curso.[n][w][e]
[s]Los ni隠os tienen muchas ganas[n]de empezar un nuevo a隠o...[n][w][e]
[s]...pero sus padres est茨n preocupados[n]por los incidentes que[n]han ocurrido 雨ltimamente.[n][w][e]

[msg TV_NEWS_0409_100_00]
[s]Son las noticias.[n]夷Han ocurrido muchos[n]accidentes 雨ltimamente?[n][w][e]

[msg TV_NEWS_0410_000_00 [Presentador de telediario]]
[s]Ha habido muchos heridos[n]en el accidente de metro.[n][w][e]
[s]Se han interrumpido los horarios[n]y no se sabe cu茨ndo[n]volver茨 todo a la normalidad.[n][w][e]
[s]Parece que los problemas de[n]tr茨nsito causados por el accidente[n]seguir茨n ma隠ana por la ma隠ana.[n][w][e]

[msg TV_NEWS_0410_100_00]
[s]Son las noticias[n]del descarrilamiento. Parece que[n]ha sido un accidente grave.[n][w][e]

[msg TV_NEWS_0411_000_00 [Presentador de telediario]]
[s]El d胤a despu姻s de la tragedia,[n]la gente coge otras l胤neas para[n]evitar la estaci吋n donde ocurri吋.[n][w][e]
[s]Esto ha provocado que algunas[n]estaciones est姻n abarrotadas[n]de pasajeros y...[n][w][e]

[msg TV_NEWS_0411_100_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 1 5121 65535 0][f 4 25 1 65535 0 0]Parece que todos los trenes van[n]con retraso. Si te duermes en los[n]laureles, vas a llegar tarde.[n][w][e]

[msg TV_NEWS_0411_200_00 [Presentador de telediario]]
[s]Tenemos nueva informaci吋n sobre[n]la tragedia del metro.[n][w][e]
[s]La polic胤a est茨 investigando el[n]lugar del accidente y va a empezar[n]una investigaci吋n a gran escala.[n][w][e]
[s]Los horarios, que se han[n]interrumpido desde entonces,[n]vuelven a la normalidad y...[n][w][e]

[msg TV_NEWS_0411_300_00]
[s]Son nuevas noticias sobre[n]el descarrilamiento. Parece que[n]las cosas se est茨n calmando.[n][w][e]

[msg TV_NEWS_0412_000_00 [Presentador de telediario]]
[s]Todav胤a se desconoce la causa[n]del accidente, y seguimos[n]esperando nuevas noticias.[n][w][e]
[s]Muchos pasajeros est茨n preocupados,[n]y otros presionan a los empleados[n]en busca de respuestas.[n][w][e]

[msg TV_NEWS_0412_100_00]
[s]Son nuevas noticias sobre[n]el accidente del metro. Parece que[n]todav胤a no saben la causa.[n][w][e]

[msg TV_NEWS_0413_000_00 [Presentador de telediario]]
[s]La polic胤a sospecha de negligencia[n]profesional y est茨 interrogando[n]al operador del metro.[n][w][e]
[s]Sin embargo, su testimonio sobre[n]el accidente y las condiciones[n]que se dieron no est茨 claro.[n][w][e]
[s]Se le va a realizar una prueba[n]psiqui茨trica para ver si es[n]responsable del incidente.[n][w][e]

[msg TV_NEWS_0413_100_00]
[s]M茨s noticias del accidente.[n]夷Habr茨n avanzado[n]en la investigaci吋n?[n][w][e]

[msg TV_NEWS_0414_000_00 [Presentador de telediario]]
[s]Pasamos a una noticia sobre[n]el accidente del metro.[n][w][e]
[s]Nos acaban de comunicar que[n]los trabajadores de mantenimiento[n]informaron de posibles riesgos.[n][w][e]
[s]La polic胤a va a comenzar[n]a investigar la gesti吋n[n]de la compa隠胤a ferroviaria.[n][w][e]

[msg TV_NEWS_0414_100_00]
[s]Es una noticia sobre[n]la investigaci吋n de la polic胤a.[n]夷Habr茨n encontrado la causa?[n][w][e]

[msg TV_NEWS_0415_000_00 [Presentador de telediario]]
[s]Tenemos novedades acerca[n]del accidente del metro.[n][w][e]
[s]La polic胤a que investigaba el caso[n]ha confiscado varios documentos[n]de la compa隠胤a ferroviaria.[n][w][e]
[s]Hablar茨n con las personas que[n]guardan relaci吋n con esta compa隠胤a[n]mientras los analizan.[n][w][e]

[msg TV_NEWS_0415_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]夷Han ocurrido muchos[n]accidentes como este 雨ltimamente?[n][w][e]

[msg TV_NEWS_0416_000_00 [Presentador de telediario]]
[s]Y ahora, seguimos con las noticias[n]de la tragedia del metro.[n][w][e]
[s]Se sospecha que la compa隠胤a[n]ferroviaria ten胤a constancia[n]del mal funcionamiento del equipo.[n][w][e]
[s]La empresa niega las acusaciones,[n]pero las cr胤ticas contra ellos[n]no paran de aumentar.[n][w][e]

[msg TV_NEWS_0416_100_00]
[s]Parece que todav胤a[n]siguen investigando el accidente.[n][w][e]

[msg TV_NEWS_0416_100_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]Qu姻 accidente tan horrible.[n]夷Pasan muchas cosas as胤?[n][w][e]

[msg TV_NEWS_0417_000_00 [Presentador de telediario]]
[s]Una semana despu姻s de la tragedia,[n]tenemos nuevas noticias sobre[n]el descarrilamiento.[n][w][e]
[s]Con respecto a las afirmaciones[n]de que la empresa ignor吋[n]advertencias sobre la seguridad...[n][w][e]
[s]Se sospecha que[n]el Ministerio de Transporte[n]ignor吋 estos problemas.[n][w][e]
[s]La gente pide que el ministro[n]responda, y sus oficinas no[n]dan abasto.[n][w][e]

[msg TV_NEWS_0417_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]No lo entiendo. 夷Por qu姻[n]ignorar胤an algo as胤 a prop吋sito?[n][w][e]

[msg TV_NEWS_0418_000_00 [Presentador de telediario]]
[s]Ahora hablaremos de pol胤tica.[n][w][e]
[s]El ministro de Transporte ha[n]aparecido p雨blicamente por primera[n]vez desde el accidente.[n][w][e]
[s]Se ha negado a responder a las[n]afirmaciones de que ignor吋 los[n]riesgos que causaron el accidente.[n][w][e]

[msg TV_NEWS_0418_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]夷Los ignor吋 sabiendo lo[n]que hab胤a? Eso parece muy grave.[n][w][e]

[msg TV_NEWS_0419_000_00 [Presentador de telediario]]
[s]Continuamos con las noticias sobre[n]las sospechas de c吋mo el gobierno[n]ha tratado el accidente.[n][w][e]
[s]Las cr胤ticas al gobierno[n]han aumentado, y el ministro puede[n]verse obligado a dimitir.[n][w][e]
[s]Este incidente ha afectado a su[n]胤ndice de popularidad, como muestra[n]la encuesta de este programa.[n][w][e]

[msg TV_NEWS_0419_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Conque ha perdido popularidad[n]por culpa del accidente.[n][w][e]

[msg TV_NEWS_0420_000_00 [Presentador de telediario]]
[s]El ministro de Transporte, bajo[n]la lluvia de cr胤ticas de la gente,[n]ha anunciado su dimisi吋n.[n][w][e]
[s]El partido de la oposici吋n culpa[n]al primer ministro por haberle[n]dado su cargo...[n][w][e]

[msg TV_NEWS_0420_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Madre m胤a... Parece que alg雨n[n]alto cargo se ha visto[n]obligado a dimitir.[n][w][e]

[msg TV_NEWS_0421_000_00 [Presentador de telediario]]
[s]Contin雨a la investigaci吋n sobre[n]el tr茨gico descarrilamiento.[n][w][e]
[s]Muchos otros incidentes[n]similares han tenido lugar[n]recientemente.[n][w][e]
[s]En todos los casos, no hubo[n]ninguna se隠al de advertencia[n]en las personas afectadas.[n][w][e]
[s]La polic胤a no se ha pronunciado[n]oficialmente con respecto[n]a estas semejanzas, pero...[n][w][e]

[msg TV_NEWS_0421_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]As胤 que ha habido muchos incidentes[n]extra隠os, 夷eh? Parece que este[n]mundo tiene sus propios problemas.[n][w][e]

[msg TV_NEWS_0422_000_00 [Presentador de telediario]]
[s]Dejamos las noticias[n]sobre el festival de las flores[n]para hablar del aumento de estafas.[n][w][e]
[s]Es el timo de la transferencia[n]bancaria, y se ha ido extendiendo[n]cada vez m茨s por la ciudad.[n][w][e]
[s]Muchos j吋venes han sido[n]v胤ctimas de 姻l, y la polic胤a[n]permanece alerta.[n][w][e]

[msg TV_NEWS_0422_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]夷Las v胤ctimas son sobre todo[n]j吋venes? Entonces ser茨 mejor[n]que vayas con cuidado.[n][w][e]

[msg TV_MACHI_0423_000_00 [Periodista]]
[s]Hoy tenemos una edici吋n especial[n]de 或斡Exploradores de la ciudad!位.[n][w][e]
[s]斡En estas emisiones especiales,[n]compartimos productos de[n]edici吋n limitada que est茨n de moda![n][w][e]
[s]斡Hoy hablaremos[n]del [clr 2]aceite de recuperaci吋n[clr 27]![n][w][e]
[s]Es muy popular entre las j吋venes,[n]y est茨 de oferta en Body Chop.[n][w][e]

[msg TV_MACHI_0423_100_00 [Especialista]]
[s]Creo que hay un Body Chop[n]en el centro comercial subterr茨neo[n]de Shibuya.[n][w][e]
[s]Siempre he tenido debilidad por los[n]art胤culos de edici吋n limitada.[n]Quiero el [clr 2]aceite de recuperaci吋n[clr 27].[n][w][e]

[msg TV_NEWS_0425_000_00 [Presentador de telediario]]
[s]Ahora, pasamos a la pol胤tica.[n][w][e]
[s]Aumentan las cr胤ticas al partido[n]gobernante tras la dimisi吋n[n]del ministro de Transporte.[n][w][e]
[s]Nuestros sondeos indican que[n]el 胤ndice de popularidad del[n]gobierno ha ca胤do dr茨sticamente.[n][w][e]
[s]El descontento general y la falta[n]de confianza en el gobierno[n]son superiores a lo esperado.[n][w][e]

[msg TV_NEWS_0425_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]Parece que no todo el mundo est茨[n]contento con el gobierno. Estar[n]en el poder no debe ser f茨cil.[n][w][e]

[msg TV_SHOUGI_0426_000_00 [Entrevistadora]]
[s]No me esperaba pe吋n a 5-6 en la[n]primera jugada. Esto puede acabar[n]en torre central animada.[n][w][e]
[s]Por cierto, 夷se llama as胤[n]por algo en especial?[n][w][e]

[msg TV_SHOUGI_0426_100_00 [Jugador profesional de shogi]]
[s]Pues porque el primer jugador[n]de shogi que us吋 ese movimiento[n]siempre estaba sonriendo.[n][w][e]
[s]De ah胤 proviene el nombre.[n]No tiene nada que ver[n]con la estrategia en s胤.[n][w][e]

[msg TV_SHOUGI_0426_200_00 [Entrevistadora]]
[s]Vamos, que el nombre no da pistas[n]sobre la estrategia. Pues anda[n]que llamarla as胤 por un jugador...[n][w][e]

[msg TV_MACHI_0427_000_00 [Periodista]]
[s]En esta edici吋n de 或斡Exploradores[n]de la ciudad!位, hablaremos del[n][clr 2]Parque Inokashira[clr 27] de Kichijoji.[n][w][e]
[s]夷Veis todos esos cerezos en flor?[n]斡Este lugar est茨 muy de moda[n]y es ideal para familias y parejas![n][w][e]

[msg TV_MACHI_0427_100_00 [Especialista]]
[s]Tambi姻n se puede encontrar gente[n]paseando o dibujando. Es un sitio[n]magn胤fico para relajarse.[n][w][e]

[msg TV_NEWS_0428_000_00 [Presentador de telediario]]
[s]El puente empieza[n]ma隠ana, y parece que har茨 sol.[n][w][e]
[s]Pero los usuarios de transporte[n]p雨blico han expresado su inquietud[n]ante los recientes accidentes.[n][w][e]

[msg TV_NEWS_0428_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]La Golden Week, 夷eh?[n]Me gustar胤a ir a alg雨n sitio[n]con la se隠orita Ann.[n][w][e]

[msg TV_WIDESHOW_0429_000_00 [Presentador]]
[s]斡Saludos! A continuaci吋n, 斡nuestra[n]emisi吋n especial sobre el pr吋ximo[n]Pr胤ncipe Detective![n][w][e]
[s]El Pr胤ncipe Detective original fue[n]Naoto Shirogane, pero 斡el p雨blico[n]espera el nuevo con ganas![n][w][e]

[msg TV_WIDESHOW_0429_100_00 [Panelista]]
[s]Mi hija es una gran fan del nuevo[n]Pr胤ncipe Detective. Es el sabueso[n]del instituto, 斡y encima es guapo![n][w][e]

[msg TV_ANIME_0430_000_00 [Narrador]]
[s]Una misteriosa figura ha vuelto[n]a reunir a Feathermen,[n]pero 斡les han robado la memoria![n][w][e]
[s]夷Encontrar茨n el modo[n]de recuperar sus recuerdos?[n]斡Revivid y luchad, Phoenix Rangers![n][w][e]
[s]En el pr吋ximo episodio...[n]或斡No des tres pasos[n]o perder茨s tus recuerdos!位.[n][w][e]

[msg TV_NEWS_0501_000_00 [Presentador de telediario]]
[s]Han pasado tres semanas desde[n]el tr茨gico desastre del metro.[n][w][e]
[s]Aunque intent吋 lidiar con la[n]situaci吋n, el ministro de[n]Transporte ha acabado dimitiendo.[n][w][e]
[s]Pero muchas preguntas[n]han quedado sin respuesta, ante[n]la confusi吋n de la polic胤a.[n][w][e]

[msg TV_NEWS_0501_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Ese accidente se produjo[n]justo despu姻s de que[n]te vinieras a vivir aqu胤, 夷no?[n][w][e]

[msg TV_DRAMA_0502_000_00 [Detective ingenioso]]
[s]Adm胤talo. Estaba en el escenario[n]del crimen cuando pas吋, 夷verdad?[n][w][e]

[msg TV_DRAMA_0502_100_00 [Mujer inquieta]]
[s]斡T-tengo coartada! 斡Ni siquiera[n]estaba por all胤 cerca! Es imposible[n]que escuchara el disparo.[n][w][e]

[msg TV_DRAMA_0502_200_00 [Detective ingenioso]]
[s]斡Qu姻 curioso! Yo no he dicho nada[n]acerca de un disparo.[n][w][e]

[msg TV_MORGANA_0502 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Es un drama polic胤aco, 夷no?[n]Es muy interesante.[n][w][e]

[msg TV_NEWS_0503_000_00 [Presentador de telediario]]
[s]En la asamblea escolar, Suguru[n]Kamoshida confes吋 haber agredido[n]y abusado de sus alumnos.[n][w][e]
[s]La confesi吋n del carism茨tico[n]profesor ha sido recibida[n]con desconcierto y estupefacci吋n.[n][w][e]

[msg TV_NEWS_0503_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Ah, est茨n hablando de Kamoshida[n]en la televisi吋n. Esto est茨[n]teniendo mucho impacto.[n][w][e]

[msg TV_NEWS_0504_000_00 [Presentador de telediario]]
[s]Hoy es el D胤a Verde, y[n]la gente abarrota los lugares[n]m茨s populares de toda la ciudad.[n][w][e]
[s]Con el puente a punto[n]de terminar, es previsible que[n]tambi姻n sigan llenos ma隠ana.[n][w][e]

[msg TV_NEWS_0504_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]Lugares populares, 夷eh?[n]斡Deber胤amos ir a visitar alguno![n][w][e]

[msg TV_NEWS_0505_000_00 [Presentador de telediario]]
[s]郁ltimas noticias sobre el arresto[n]del carism茨tico profesor[n]Suguru Kamoshida.[n][w][e]
[s]Este antiguo jugador de voleibol[n]del equipo ol胤mpico confes吋 haber[n]abusado de sus alumnos.[n][w][e]
[s]La polic胤a investigar茨 los hechos[n]en el instituto a partir[n]de ma隠ana.[n][w][e]

[msg TV_NEWS_0505_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Parece que la polic胤a vendr茨[n]a tu instituto. T雨 act雨a como[n]si no supieras nada.[n][w][e]

[msg TV_WIDESHOW_0506_000_00 [Presentador]]
[s]斡Saludos! Ahora hablaremos[n]sobre el artista japon姻s[n]Ichiryusai Madarame.[n][w][e]
[s]Todas sus obras son[n]codiciadas incluso en otros pa胤ses.[n]Es un artista de talla mundial.[n][w][e]

[msg TV_WIDESHOW_0506_100_00 [Panelista]]
[s]Madarame adopta a ni隠os sin familia[n]como alumnos y les proporciona un[n]hogar, 夷verdad? Es un santo...[n][w][e]

[msg TV_NEWS_0507_000_00 [Anuncio]]
[s]Este programa est茨 patrocinado[n]por KJ Mobile.[n][w][e]
[s]Ma隠ana en Good Morning Japan,[n]nuestro invitado ser茨 el artista[n]japon姻s Ichiryusai Madarame.[n][w][e]
[s]Este maestro que da vida[n]a escenas fant茨sticas nos dar茨 su[n]opini吋n sobre su 雨ltima exposici吋n.[n][w][e]

[msg TV_NEWS_0509_000_00 [Presentador de telediario]]
[s]El pasado fin de semana la polic胤a[n]visit吋 el instituto donde ense隠aba[n]Kamoshida para reunir informaci吋n.[n][w][e]
[s]Los alumnos no pod胤an ocultar[n]su estupefacci吋n ante el esc茨ndalo[n]que rodea a este popular profesor.[n][w][e]
[s]La polic胤a pretende realizar[n]el arresto tras reunir m茨s pruebas[n]y terminar la investigaci吋n.[n][w][e]

[msg TV_NEWS_0509_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Hab胤a polic胤a en la entrada, 夷no?[n]Todo apunta a que[n]este caso est茨 llegando a su fin.[n][w][e]

[msg TV_NEWS_0510_000_00 [Presentador de telediario]]
[s]Hemos hablado con especialistas del[n]esc茨ndalo de violencia y conducta[n]inmoral del profesor Kamoshida.[n][w][e]
[s]Opinan que hay problemas dentro[n]del sistema educativo japon姻s.[n][w][e]

[msg TV_NEWS_0510_050_00 [Panelista]]
[s]Puede ser. Crec胤 en Finlandia[n]y all胤 todos los estudiantes[n]tienen los mismos conocimientos.[n][w][e]
[s]Apenas hay costes hasta[n]el instituto. Adem茨s, todos[n]los profesores son doctorados.[n][w][e]

[msg TV_NEWS_0510_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]En tal caso, 夷llamar胤as[n]a esos panelistas profesores?[n][w][e]

[msg TV_NEWS_0511_000_00 [Presentador de telediario]]
[s]Hemos hablado con especialistas del[n]esc茨ndalo de violencia y conducta[n]inmoral del profesor Kamoshida.[n][w][e]
[s]Opinan que hay problemas dentro[n]del sistema educativo japon姻s.[n][w][e]

[msg TV_NEWS_0511_050_00 [Panelista]]
[s]Puede ser. Crec胤 en Finlandia[n]y all胤 todos los estudiantes[n]tienen los mismos conocimientos.[n][w][e]
[s]Apenas hay costes hasta[n]el instituto. Adem茨s, todos[n]los profesores son doctorados.[n][w][e]

[msg TV_NEWS_0511_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]En tal caso, 夷llamar胤as[n]a esos panelistas profesores?[n][w][e]

[msg TV_NEWS_0512_000_00 [Presentador de telediario]]
[s]Vamos a tratar el pasado[n]del profesor Kamoshida, envuelto en[n]el esc茨ndalo de conducta inmoral.[n][w][e]
[s]Hay una cita que dice 或mente sana[n]en cuerpo sano位. Me gustar胤a[n]conocer su opini吋n al respecto.[n][w][e]

[msg TV_NEWS_0512_050_00 [Panelista]]
[s]No estoy de acuerdo. Creo[n]que el alma y la mente deber胤an[n]considerarse dos cosas distintas.[n][w][e]
[s]Juvenal dijo: 或Que se nos conceda[n]una mente sana en un cuerpo sano位.[n]Lo dem茨s es superficial.[n][w][e]

[msg TV_NEWS_0512_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]夷Qu姻 querr茨 decir con eso? Bueno,[n]los Ladrones Fantasma se dejan[n]cuerpo y alma en el trabajo.[n][w][e]

[msg TV_NEWS_0513_000_00 [Presentador de telediario]]
[s]El esc茨ndalo de los abusos[n]del profesor Kamoshida ha tenido[n]un serio impacto social.[n][w][e]
[s]El instituto en el que trabajaba[n]y el comit姻 educativo han recibido[n]un aluvi吋n de protestas.[n][w][e]
[s]Hasta en la ciudad y en internet,[n]muchos padres han manifestado[n]su ira e inquietud.[n][w][e]
[s]El instituto ha contratado[n]a un orientador para mejorar[n]la salud mental de los alumnos.[n][w][e]

[msg TV_NEWS_0513_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Est茨n hablando de Kamoshida[n]otra vez. Parece que mucha gente[n]se ha quejado de sus actos.[n][w][e]
[s][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0][f 4 10 65535 0 0]夷Y acaba de decir orientador?[n]夷Se referir茨 al tal Maruki?[n][w][e]

[msg TV_NEWS_0514_000_00 [Presentador de telediario]]
[s]Ahora, noticias culturales.[n][w][e]
[s]Ma隠ana se inaugura una exposici吋n[n]del artista japon姻s Ichiryusai[n]Madarame en Shibuya.[n][w][e]
[s]Hay mucha expectaci吋n, con[n]programas televisivos dedicados al[n]evento y gran demanda de entradas.[n][w][e]

[msg TV_NEWS_0514_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]斡Eh, si es ese anciano![n]No sab胤a que de verdad era famoso...[n][w][e]

[msg TV_DRAMA_0516_000_00 [Detective ingenioso]]
[s]Sus huellas estaban en el arma[n]del crimen. Eso prueba[n]que lo hizo usted. R胤ndase.[n][w][e]

[msg TV_DRAMA_0516_100_00 [Mujer deca胤da]]
[s]Detective...[n][w][e]
[s]Me ha pillado. Lo confieso.[n]Fui yo quien lo mat吋.[n][w][e]

[msg TV_MORGANA_0516 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]Vaya, lo ha averiguado muy r茨pido.[n]夷Ser茨n as胤 las investigaciones[n]de verdad?[n][w][e]

[msg TV_NEWS_0517_000_00 [Presentador de telediario]]
[s]A continuaci吋n, un reportaje[n]sobre las distintas agresiones[n]de Suguru Kamoshida.[n][w][e]
[s]Este esc茨ndalo ha conmocionado[n]el mundo deportivo y se interroga a[n]toda la gente relacionada con 姻l.[n][w][e]
[s]La asociaci吋n de voleibol[n]se plantea su expulsi吋n[n]permanente, y...[n][w][e]

[msg TV_NEWS_0517_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Lo van a echar de la asociaci吋n[n]de voleibol, 夷eh? Bueno,[n]se lo merece.[n][w][e]

[msg TV_NEWS_0518_000_00 [Presentador de telediario]]
[s]...ha sido v胤ctima de una filtraci吋n[n]de datos personales a gran escala.[n][w][e]
[s]Los datos de los clientes[n]de varias empresas japonesas[n]se han filtrado al p雨blico.[n][w][e]
[s]Se han publicado datos de miles de[n]clientes, y muchas personas ya han[n]expresado su preocupaci吋n.[n][w][e]
[s]Los expertos creen que[n]el responsable puede ser[n]un grupo internacional de hackers...[n][w][e]

[msg TV_NEWS_0518_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]夷Alguien ha robado[n]los datos personales de toda[n]esa gente? Vaya...[n][w][e]

[msg TV_QUIZ_0519_000_00 [Presentador de concurso]]
[s]Si golpea a alguien y le hace da隠o,[n]le provoca 或lesiones位.[n]Piensen en los siguientes casos...[n][w][e]
[s]A: Corte de pelo sin consentimiento.[n]B: Hacer ruido para incomodar.[n][w][e]
[s]斡夷Cu茨l de estas dos opciones[n]se considera un caso de lesiones?![n]斡Juzguen ustedes mismos![n][w][e]

[sel SEL_QUIZ_0519 top]
[s]Corte de pelo sin consentimiento.[e]
[s]Hacer ruido para incomodar.[e]

[msg TV_QUIZ_0519_100_00 [Presentador de concurso]]
[s]La respuesta correcta es... 斡la B![n]斡Volver a alguien loco usando[n]ruidos puede provocarle lesiones![n][w][e]

[msg TV_QUIZ_0519_200_00 [Abogado]]
[s]Si altera las funciones corporales,[n]斡cuenta como lesi吋n aunque[n]no haya contacto f胤sico alguno![n][w][e]
[s]El pelo vuelve a crecer, as胤 que no[n]se considera una herida.[n]Ser胤a m茨s bien un caso de 或asalto位.[n][w][e]

[msg TV_MORGANA_0519_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]夷Qu姻? 夷No has acertado?[n]Las leyes pueden ser confusas.[n][w][e]

[msg TV_MORGANA_0519_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]Eh, has acertado.[n]Me sorprende que sepas[n]tanto sobre las leyes.[n][w][e]

[msg TV_NEWS_0520_000_00 [Presentador de telediario]]
[s]Ahora, noticias culturales.[n][w][e]
[s]Esta semana se inaugur吋 en Shibuya[n]una exposici吋n de las obras[n]del artista Ichiryusai Madarame.[n][w][e]
[s]En ella se pueden contemplar[n]numerosas obras de todas[n]las etapas de su carrera.[n][w][e]
[s]Los cr胤ticos han alabado[n]la exposici吋n, que refleja[n]la continua evoluci吋n de su estilo.[n][w][e]

[msg TV_NEWS_0520_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]Todo el mundo se ha tragado[n]sus mentiras. Pero pronto[n]se sabr茨 la verdad, 夷eh?[n][w][e]

[msg TV_NEWS_0521_000_00 [Presentador de telediario]]
[s]Ya estamos a mediados de mayo,[n]y las hojas de los 茨rboles[n]empiezan a brotar.[n][w][e]
[s]La gente pasea por la ciudad[n]disfrutando de la brisa[n]de principios de verano.[n][w][e]
[s]En la ciudad, es posible[n]escaparse y disfrutar de la[n]naturaleza en el Parque Inokashira.[n][w][e]

[msg TV_NEWS_0521_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Oye, ese parque parece muy bonito.[n]Podr胤a ser buena idea tomarse[n]un descanso e ir all胤 a relajarse.[n][w][e]

[msg TV_NEWS_0523_000_00 [Presentador de telediario]]
[s]Es la 姻poca del a隠o en que las[n]calles se llenan de j吋venes[n]trajeados. Van a buscar trabajo.[n][w][e]
[s]Con la reciente recesi吋n econ吋mica,[n]muchas empresas ofertan un n雨mero[n]muy limitado de puestos.[n][w][e]
[s]Las empresas populares se ven[n]inundadas de solicitudes y pueden[n]permitirse pagar sueldos muy bajos.[n][w][e]

[msg TV_NEWS_0523_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Con esos trajes, todos[n]parecen iguales. Debe de ser[n]duro encontrar trabajo.[n][w][e]

[msg TV_SHOUGI_0524_000_00 [Jugador profesional de shogi]]
[s]Uf, eso podr胤a haberse evitado[n]f茨cilmente. 畏l lo sabe y seguro[n]que se arrepiente. Un doble pe吋n...[n][w][e]
[s]Ser茨 complicado encajar[n]esa derrota. Ojal茨 pudi姻ramos[n]darle un poco de tiempo...[n][w][e]

[msg TV_SHOUGI_0524_100_00 [Entrevistadora]]
[s]Bueno, vamos con el an茨lisis[n]post mortem, donde analizamos[n]lo ocurrido en la partida.[n][w][e]

[msg TV_NEWS_0525_000_00 [Presentador de telediario]]
[s]Cada vez hay m茨s v胤ctimas[n]de estafa en Tokio.[n][w][e]
[s]Los ardides son cada vez son m茨s[n]sofisticados, y muchos j吋venes[n]han ca胤do en estas estafas.[n][w][e]
[s]La polic胤a trata de proteger a[n]la poblaci吋n de estos timos, pero[n]no encuentra medidas efectivas.[n][w][e]

[msg TV_NEWS_0525_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Por lo que se ve, est茨n timando[n]cada vez a m茨s gente.[n]Qu姻 pena que haya quien pique.[n][w][e]

[msg TV_QUIZ_0526_000_00 [Presentador de concurso]]
[s]Confesar un delito, como ha hecho[n]el profesor Kamoshida, ha dado[n]lugar a una vieja expresi吋n.[n][w][e]
[s]La confesi吋n de un delito es...[n]A) 或Reina位 de las pruebas.[n]B) 或Joya位 de las pruebas.[n][w][e]
[s]夷Cu茨l es la respuesta correcta?[n]斡Juzguen ustedes mismos![n][w][e]

[sel SEL_QUIZ_0526 top]
[s]或Reina位 de las pruebas.[e]
[s]或Joya位 de las pruebas.[e]

[msg TV_QUIZ_0526_100_00 [Chico]]
[s]La respuesta correcta es la A,[n]或reina位. S胤, es una expresi吋n[n]muy famosa en el campo del derecho.[n][w][e]
[s]Una confesi吋n es una prueba[n]determinante. Incluso se recurr胤a[n]a la tortura para conseguir una.[n][w][e]

[msg TV_QUIZ_0526_200_00 [Abogado]]
[s]Con ustedes, un genio de instituto.[n]Hoy en d胤a, conseguir una confesi吋n[n]a la fuerza est茨 prohibido, y...[n][w][e]

[msg TV_MORGANA_0526_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]Me sorprende que lo supieras.[n]夷Ha sido a voleo? Aunque[n]la tortura es terrible.[n][w][e]

[msg TV_MORGANA_0526_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]Ah, 夷la respuesta era 或reina位?[n]斡Yo creo que 或joya位[n]hubiera quedado mejor![n][w][e]

[msg TV_NEWS_0527_000_00 [Presentador de telediario]]
[s]La exposici吋n de las obras[n]de Madarame sigue atrayendo[n]a un gran n雨mero de visitantes.[n][w][e]
[s]La afluencia es muy superior[n]a la esperada, para satisfacci吋n[n]de los organizadores.[n][w][e]

[msg TV_NEWS_0527_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]夷De verdad es tan popular?[n]夷Qu姻 van a hacer cuando[n]se sepa lo que ha hecho?[n][w][e]

[msg TV_ANIME_0528_000_00 [Narrador]]
[s]威guila Roja y Halc吋n han tenido[n]una acalorada discusi吋n.[n]斡夷Qui姻n es el verdadero l胤der?![n][w][e]
[s]H姻roe contra h姻roe, enfrentados[n]en una batalla 姻pica de shiritori.[n]斡Revivid y luchad, Phoenix Rangers![n][w][e]
[s]En el pr吋ximo episodio...[n]或Si tienes la 雨ltima palabra,[n]斡pierdes!位.[n][w][e]

[msg TV_NEWS_0530_000_00 [Presentador de telediario]]
[s]Ichiryusai Madarame ha recibido[n]cr胤ticas muy favorables,[n]incluso desde el extranjero.[n][w][e]
[s]Lo m茨s alabado es lo cambiante[n]de su estilo art胤stico. Mucha gente[n]desea encargarle obras nuevas.[n][w][e]

[msg TV_NEWS_0530_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Parece que hasta la gente[n]que vive fuera de Jap吋n lo adora.[n]No entiendo esto del arte...[n][w][e]

[msg TV_SHOUGI_0531_000_00 [Jugador profesional de shogi]]
[s]Bueno, aqu胤 lo natural[n]ser胤a pe吋n a 4-3.[n][w][e]
[s]Pero 夷preguntas por pe吋n a 9-5?[n]Yo creo que no har胤a eso jam茨s.[n]Me parece muy arriesgado...[n][w][e]

[msg TV_SHOUGI_0531_100_00 [Entrevistadora]]
[s]Pues acaba de hacer pe吋n a 9-5...[n][w][e]

[msg TV_NEWS_0601_000_00 [Presentador de telediario]]
[s]Wild Duck Burger se desploma en[n]bolsa. Un empleado public吋 fotos[n]realizando actos poco higi姻nicos.[n][w][e]
[s]El esc茨ndalo se produjo justo antes[n]de una reuni吋n de accionistas,[n]y tuvo efectos devastadores.[n][w][e]
[s]El empleado implicado afirma[n]que no se dio cuenta de que[n]estaba desnudo en el trabajo.[n][w][e]

[msg TV_NEWS_0601_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0][f 4 25 1 65535 0 0]夷Por qu姻 har胤a eso nadie?[n]夷Pensar胤a que ten胤a gracia o qu姻?[n][w][e]

[msg TV_QUIZ_0602_000_00 [Presentador de concurso]]
[s]En la delincuencia juvenil, se usa[n]mucho la palabra 或condicional位 para[n]reformar a los culpables.[n][w][e]
[s]Durante una libertad condicional...[n]A) No se puede viajar al extranjero.[n]B) Los agentes no cobran.[n][w][e]
[s]夷Cu茨l de estas afirmaciones[n]es verdadera?[n]斡Juzguen ustedes mismos![n][w][e]

[sel SEL_QUIZ_0602 top]
[s]No se puede viajar al extranjero.[e]
[s]Los agentes no cobran.[e]

[msg TV_QUIZ_0602_100_00 [Chico]]
[s]La respuesta correcta es... 斡la B![n]斡Los agentes de la condicional[n]no tienen salario![n][w][e]

[msg TV_QUIZ_0602_200_00 [Abogado]]
[s]Los agentes de la condicional son[n]voluntarios. Solo se les paga[n]lo justo al entregar un informe.[n][w][e]
[s]El fin de la libertad condicional[n]es rehabilitar, viajar[n]al extranjero no est茨 prohibido.[n][w][e]

[msg TV_MORGANA_0602_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]Vaya, 夷no has acertado? Aun as胤,[n]es bueno que puedas salir[n]del pa胤s si quieres.[n][w][e]

[msg TV_MORGANA_0602_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]斡Has acertado! Aunque es[n]incre胤ble que el Jefe haga esto[n]a cambio de nada...[n][w][e]

[msg TV_NEWS_0603_000_00 [Presentador de telediario]]
[s]M茨s visitantes acuden[n]a la exposici吋n de Madarame[n]en sus 雨ltimos d胤as.[n][w][e]
[s]Hasta los que solo se pasaron por[n]curiosidad se han visto atrapados[n]por sus delicadas im茨genes.[n][w][e]
[s]La exposici吋n seguir茨[n]abierta hasta el 5 de junio.[n][w][e]

[msg TV_NEWS_0603_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]Esa exposici吋n termina[n]pronto, 夷eh? A saber qu姻 pasar茨.[n][w][e]

[msg TV_ANIME_0604_000_00 [Narrador]]
[s]Halc吋n ha recuperado la memoria.[n]Pero 斡ahora ha aparecido[n]un nuevo villano![n][w][e]
[s]斡La revelaci吋n de un nuevo l胤der[n]cambia el panorama![n]斡Revivid y luchad, Phoenix Rangers![n][w][e]
[s]En el pr吋ximo episodio...[n]或Se llama 威guila Roja位.[n][w][e]

[msg TV_NEWS_0605_000_00 [Presentador de telediario]]
[s]Y ahora, informamos de la rueda[n]de prensa en la que el artista[n]Ichiryusai Madarame confes吋.[n][w][e]
[s]Ha admitido vender copias[n]de su famoso cuadro 或Sayuri位[n]como si fueran aut姻nticas.[n][w][e]
[s]La polic胤a pretende investigar[n]a fondo a Madarame por fraude.[n][w][e]

[msg TV_NEWS_0605_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]斡Madarame sale en la tele![n]Es una noticia importante.[n][w][e]

[msg TV_NEWS_0606_000_00 [Presentador de telediario]]
[s]Contin雨a la investigaci吋n[n]de Madarame la noche despu姻s[n]de su rueda de prensa.[n][w][e]
[s]Tambi姻n se habla de una extra隠a[n]carta de un grupo que se hace[n]llamar 或[f 4 28]位.[n][w][e]
[s]La polic胤a est茨 investigando[n]si este grupo tiene[n]algo que ver con el caso.[n][w][e]

[msg TV_NEWS_0606_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]Ah, 斡est茨n hablando del aviso que[n]enviamos! 斡Y han dicho nuestro[n]nombre en la tele![n][w][e]

[msg TV_NEWS_0607_000_00 [Presentador de telediario]]
[s]Noticias culturales.[n][w][e]
[s]Hay una avalancha de quejas de[n]coleccionistas por la autenticidad[n]de las obras de Madarame.[n][w][e]
[s]Parece que este esc茨ndalo seguir茨[n]creando confusi吋n en el mundo[n]del arte una buena temporada.[n][w][e]

[msg TV_NEWS_0607_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]La gente que le compr吋 obras[n]a Madarame ya deber胤a haber[n]aceptado la verdad sobre 姻l.[n][w][e]

[msg TV_MACHI_0608_000_00 [Periodista]]
[s]En 或斡Exploradores de la ciudad!位,[n]hablamos de [clr 2]Chinatown[clr 27],[n]un lugar ideal para los sibaritas.[n][w][e]
[s]斡En Motomachi hay muchos[n]restaurantes chinos! S胤, la comida[n]china de calidad es sublime.[n][w][e]

[msg TV_MACHI_0608_100_00 [Especialista]]
[s]Los olores procedentes de sus[n]restaurantes son un regalo para el[n]olfato, y ofrece muchas opciones.[n][w][e]

[msg TV_NEWS_0609_000_00 [Presentador de telediario]]
[s]El repentino arrepentimiento[n]del artista ha sido toda[n]una sorpresa en el mundo del arte.[n][w][e]
[s]A雨n no se sabe[n]qu姻 ha llevado a Madarame[n]a confesar sus delitos.[n][w][e]

[msg TV_NEWS_0609_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Es igual que con Kamoshida,[n]夷verdad? No se da cuenta[n]de lo que le ha pasado.[n][w][e]

[msg TV_MACHI_0610_000_00 [Periodista]]
[s]Hoy tenemos una edici吋n especial[n]de 或斡Exploradores de la ciudad!位.[n][w][e]
[s]斡En estas emisiones especiales,[n]compartimos productos de[n]edici吋n limitada que est茨n de moda![n][w][e]
[s]斡Hoy hablaremos[n]del [clr 2]soba relajante[clr 27],[n]el plato contra el calor![n][w][e]
[s]Est茨 de oferta en las tiendas[n]de Tokio y se espera[n]que se agote enseguida.[n][w][e]

[msg TV_MACHI_0610_100_00 [Especialista]]
[s]Es mejor que algunos platos chinos.[n]Es sorprendente que se pueda[n]comprar en tiendas de autoservicio.[n][w][e]

[msg TV_NEWS_0611_000_00 [Presentador de telediario]]
[s]Hablamos de lo que se cuenta[n]en la ciudad para informarlos.[n]Hoy, 或[f 4 28]位.[n][w][e]
[s]Tienen tir吋n entre la juventud[n]y se comenta que tuvieron que ver[n]con la confesi吋n de Madarame.[n][w][e]
[s]Se desconocen sus m姻todos,[n]y hay quien se preocupa de que este[n]grupo pueda ser peligroso, pero...[n][w][e]

[msg TV_NEWS_0611_100_00]
[s]Parece que mucha gente[n]ha empezado a hablar[n]de los Ladrones Fantasma.[n][w][e]

[msg TV_NEWS_0612_000_00 [Presentador de telediario]]
[s]A continuaci吋n, hablamos[n]de los peligros que[n]se ciernen sobre la ciudad.[n][w][e]
[s]En lo que va de a隠o, cada vez hay[n]m茨s estafados, sobre todo[n]en el 茨rea metropolitana de Tokio.[n][w][e]
[s]Se rumorea que detr茨s de estos[n]timos est茨 una gran mafia,[n]pero...[n][w][e]

[msg TV_NEWS_0612_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]夷Una mafia? Vaya. 夷Qui姻nes ser茨n?[n][w][e]

[msg TV_NEWS_0613_000_00 [Presentador de telediario]]
[s]Estamos a mediados de junio[n]y el cielo a雨n no se ha despejado.[n][w][e]
[s]Se espera que la regi吋n[n]de Kanto entre[n]en su 姻poca de lluvias pronto.[n][w][e]
[s]Seg雨n la Agencia Meteorol吋gica[n]de Jap吋n, este a隠o tendremos[n]un nivel normal de lluvias.[n][w][e]

[msg TV_NEWS_0613_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1043 65535 0][f 4 25 1 65535 0 0]Eso significa que a partir de ahora[n]llover茨 m茨s, 夷no?[n]Habr茨 m茨s humedad...[n][w][e]

[msg TV_NEWS_0614_000_00 [Presentador de telediario]]
[s]A continuaci吋n, hablamos[n]de los peligros que[n]se ciernen sobre la ciudad.[n][w][e]
[s]Un equipo de reporteros acompa隠吋[n]a un investigador de la polic胤a[n]a cargo del caso de la mafia.[n][w][e]
[s]La conclusi吋n es que hay poco[n]que se pueda hacer.[n][w][e]

[msg TV_NEWS_0614_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Hasta la polic胤a tiene problemas.[n]No podemos bajar la guardia.[n][w][e]

[msg TV_MACHI_0615_000_00 [Periodista]]
[s]En 或斡Exploradores de la ciudad!位,[n]hablamos del [clr 2]Parque Seaside[clr 27],[n]famoso entre la gente joven.[n][w][e]
[s]Te puedes relajar en el parque,[n]斡y las vistas desde la noria[n]son incre胤bles![n][w][e]

[msg TV_MACHI_0615_100_00 [Especialista]]
[s]S胤, la noria est茨 de moda entre[n]las parejas j吋venes. Ojal茨 alg雨n[n]d胤a lleve a alguna chica.[n][w][e]

[msg TV_NEWS_0616_000_00 [Presentador de telediario]]
[s]M茨s noticias. El incendio provocado[n]en una f茨brica que pertenece[n]al gigante Haneruya.[n][w][e]
[s]Un empleado ha sido arrestado,[n]pero afirma que no recuerda[n]nada del delito que cometi吋.[n][w][e]
[s]Al preguntarle por el motivo,[n]insisti吋 en que[n]no sab胤a por qu姻 lo hizo.[n][w][e]
[s]Es un nuevo incidente en el sector[n]alimentario cuya motivaci吋n a雨n[n]no ha podido aclararse.[n][w][e]

[msg TV_NEWS_0616_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]Es extra隠o que no lo recuerden.[n]夷C吋mo van a evitar[n]estos delitos tan raros?[n][w][e]

[msg TV_NEWS_0617_000_00 [Presentador de telediario]]
[s]En nuestra secci吋n de peligros[n]que amenazan la ciudad,[n]analizamos la respuesta policial.[n][w][e]
[s]La polic胤a ha declarado que dedica[n]todos sus esfuerzos a evitar que[n]la mafia siga cobr茨ndose v胤ctimas.[n][w][e]
[s]Pero no ha logrado cumplir[n]esa promesa, y los ciudadanos[n]cada vez est茨n m茨s inquietos.[n][w][e]

[msg TV_NEWS_0617_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]Hacen da隠o a much胤sima gente.[n]Ojal茨 pudi姻ramos encontrar[n]alg雨n tipo de pista.[n][w][e]

[msg TV_NEWS_0618_000_00 [Presentador de telediario]]
[s]Tenemos novedades sobre el incendio[n]provocado en una f茨brica[n]del gigante Haneruya.[n][w][e]
[s]El empleado arrestado sigue[n]afirmando que no recuerda[n]haber cometido el delito.[n][w][e]
[s]Sin una admisi吋n que permita[n]establecer el m吋vil, a雨n[n]no se sabe por qu姻 lo hizo.[n][w][e]
[s]Es uno m茨s de los delitos en el[n]sector alimentario en los que el[n]sospechoso afirma no recordar nada.[n][w][e]

[msg TV_NEWS_0618_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Hay incidentes de todo tipo...[n]Los incendios provocados dan miedo.[n][w][e]

[msg TV_DRAMA_0620_000_00 [Detective ingenioso]]
[s]Los delitos no se comenten[n]en una sala de conferencias.[n][w][e]
[s]Los delitos tienen lugar[n]en el mundo real. 夷Lo entiende?[n][w][e]

[msg TV_DRAMA_0620_100_00 [Sospechosa confusa]]
[s]Mmm... 夷Por qu姻 dice eso?[n][w][e]

[msg TV_MORGANA_0620 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]Este detective sabe bien lo que[n]pasa. Aprovechar tu propia[n]experiencia es importante.[n][w][e]

[msg TV_NEWS_0621_000_00 [Presentador de telediario]]
[s]Pasemos a otra noticia.[n][w][e]
[s]En un evento de la ciudad,[n]varias personas empezaron a sentir[n]n茨useas y fueron hospitalizadas.[n][w][e]
[s]El Departamento de Salud sospecha[n]de intoxicaci吋n alimentaria y[n]est茨 realizando una investigaci吋n.[n][w][e]

[msg TV_NEWS_0621_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Ten cuidado t雨 tambi姻n. Un dolor[n]de est吋mago podr胤a hundir hasta[n]a los Ladrones Fantasma.[n][w][e]

[msg TV_MACHI_0622_000_00 [Periodista]]
[s]En 或斡Exploradores de la ciudad!位,[n]visitamos la Sky Tower, 斡el[n]nuevo lugar de moda en [clr 2]Asakusa[clr 27]![n][w][e]
[s]斡Con las vistas que[n]hay desde el mirador, parece que[n]est茨s andando por el aire![n][w][e]

[msg TV_MACHI_0622_100_00 [Especialista]]
[s]Me dan miedo las alturas, as胤 que[n]puede que me quede en los puestos[n]de Asakusa, ja, ja, ja.[n][w][e]

[msg TV_QUIZ_0623_000_00 [Presentador de concurso]]
[s]Aqu胤 hay una pregunta relacionada[n]con el fraude que acaba[n]de confesar Madarame.[n][w][e]
[s]Piensen en los siguientes casos:[n]A) Usar dinero falso en una m茨quina.[n]B) Pedir comida sin tener dinero.[n][w][e]
[s]夷Cu茨l de estos se considera fraude?[n]斡Juzguen ustedes mismos![n][w][e]

[sel SEL_QUIZ_0623 top]
[s]Usar dinero falso en una m茨quina.[e]
[s]Pedir comida sin tener dinero.[e]

[msg TV_QUIZ_0623_100_00 [Presentador de concurso]]
[s]La respuesta correcta es... 斡la B![n]斡Pedir comida cuando no[n]se tiene dinero![n][w][e]

[msg TV_QUIZ_0623_200_00 [Abogado]]
[s]El fraude consiste en enga隠ar a[n]una persona. Por eso, pedir comida[n]si no se tiene dinero es fraude.[n][w][e]
[s]Usar dinero falso en una m茨quina[n]expendedora o en una lavander胤a[n]autoservicio es hurto.[n][w][e]

[msg TV_MORGANA_0623_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]Espera, 夷no es fraude si se hace[n]con una m茨quina? Siento que[n]me est茨n enga隠ando.[n][w][e]

[msg TV_MORGANA_0623_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]Entonces, 夷hacer un simpa[n]se considera fraude? Hala,[n]deber胤a tener cuidado con eso.[n][w][e]

[msg TV_NEWS_0624_000_00 [Presentador de telediario]]
[s]Ahora hablaremos de los peligros[n]que se ciernen sobre la ciudad.[n][w][e]
[s]Se sospecha que la mafia est茨[n]detr茨s de una oleada de estafas, y[n]hemos entrevistado a una v胤ctima.[n][w][e]
[s]Nos encontramos a un joven[n]sumido en una profunda[n]desesperaci吋n.[n][w][e]

[msg TV_NEWS_0624_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]En la tele est茨 saliendo[n]una v胤ctima.[n]Tambi姻n habr茨 sido Kaneshiro.[n][w][e]

[msg TV_ANIME_0625_000_00 [Narrador]]
[s]斡夷Cisne Azul y Grulla Rosa hablan[n]de amor?! 斡Grulla y Cisne[n]tambi姻n se han unido![n][w][e]
[s]斡Ning雨n villano puede soportar[n]el poder de una noche de chicas![n]斡Revivid y luchad, Phoenix Rangers![n][w][e]
[s]En el pr吋ximo episodio...[n]或Ans胤o tanto amar,[n]que volver胤a de entre los muertos位.[n][w][e]

[msg TV_NEWS_0627_000_00 [Presentador de telediario]]
[s]La polic胤a ha anunciado los da隠os[n]causados por timos de transferencia[n]bancaria el mes pasado.[n][w][e]
[s]Ha habido m茨s da隠os que los que[n]suele haber en un a隠o, y creen que[n]la seguridad p雨blica ha empeorado.[n][w][e]
[s]La polic胤a pide a los ciudadanos[n]que tengan cuidado, pero a雨n hay[n]que establecer medidas eficaces.[n][w][e]

[msg TV_NEWS_0627_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]Ese Kaneshiro...[n]Ha llegado demasiado lejos.[n][w][e]

[msg TV_SHOUGI_0628_000_00 [Entrevistadora]]
[s]Es genial ver a tantas jugadoras[n]de shogi hoy en d胤a. 夷Te gustar胤a[n]destacar alguna en particular?[n][w][e]

[msg TV_SHOUGI_0628_100_00 [Jugador profesional de shogi]]
[s]Ah, claro. Creo que me[n]decanto por Hifumi Togo.[n][w][e]
[s]Es una jugadora que equilibra[n]muy bien el ataque y la defensa.[n]Y adem茨s es muy guapa.[n][w][e]

[msg TV_SHOUGI_0628_200_00 [Entrevistadora]]
[s]S胤, he o胤do que ha empezado[n]a hacer de modelo hace poco.[n][w][e]

[msg TV_NEWS_0629_000_00 [Presentador de telediario]]
[s]Ya se han resuelto[n]las interrupciones en el servicio[n]de internet.[n][w][e]
[s]Los proveedores de servicios[n]han anunciado que fueron[n]causadas por ataques ilegales.[n][w][e]
[s]Los culpables no han declarado,[n]pero se sospecha que se trata[n]de un grupo de hackers an吋nimos.[n][w][e]

[msg TV_NEWS_0629_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1043 65535 0][f 4 25 1 65535 0 0]Ataques en grupo...[n]Debe de ser terrible[n]ser el blanco de eso.[n][w][e]

[msg TV_NEWS_0630_000_00 [Presentador de telediario]]
[s]A continuaci吋n hablaremos sobre los[n]peligros que acechan la ciudad.[n][w][e]
[s]Hoy entrevistaremos a un hombre[n]que sol胤a dedicarse a las estafas.[n][w][e]
[s]Durante la charla, mostraremos[n]los m姻todos de los estafadores,[n]que evolucionan continuamente.[n][w][e]

[msg TV_NEWS_0630_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Le dan mucho bombo[n]a las estafas. Ojal茨 se esforzaran[n]tanto en otras cosas.[n][w][e]

[msg TV_WIDESHOW_0701_000_00 [Presentador]]
[s]斡Saludos! 斡Llegan las noticias del[n]mundo del espect茨culo![n][w][e]
[s]斡El 胤dolo de masas Rise Kujikawa[n]ha lanzado una nueva canci吋n[n]titulada 或Amor maduro位![n][w][e]

[msg TV_WIDESHOW_0701_100_00 [Panelista]]
[s]Es mucho m茨s atractiva desde que[n]cumpli吋 la veintena. Y lleva[n]un traje espectacular.[n][w][e]

[msg TV_NEWS_0702_000_00 [Presentador de telediario]]
[s]Aunque ya estamos en julio,[n]la lluvia sigue yendo y viniendo[n]y el nivel de humedad es alto.[n][w][e]
[s]Seg雨n la Agencia Meteorol吋gica[n]de Jap吋n, se espera que la 姻poca[n]de lluvias acabe el fin de semana.[n][w][e]

[msg TV_NEWS_0702_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1043 65535 0][f 4 25 1 65535 0 0]Qu姻 asco da tanta humedad.[n]Adem茨s, echo de menos el sol.[n][w][e]

[msg TV_DRAMA_0704_000_00 [Detective ingenioso]]
[s]Hay algo muy extra隠o escrito[n]en el escenario del crimen. Ser茨[n]su mensaje de pedida...[n][w][e]
[s]O sea, de despedida.[n][w][e]

[msg TV_DRAMA_0704_100_00 [Sospechoso]]
[s]夷Ha sido un fallo[n]de su subconsciente, desertor?[n]Perd吋n, inspector.[n][w][e]

[msg TV_MORGANA_0704 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0][f 4 25 1 65535 0 0]Hala, eso ha sido brutal.[n]Hasta ese detective experimentado[n]se asust吋 cuando escuch吋 eso.[n][w][e]

[msg TV_NEWS_0705_000_00 [Presentador de telediario]]
[s]En nuestra secci吋n recurrente sobre[n]los peligros que acechan la ciudad,[n]hablamos del aumento de estafas.[n][w][e]
[s]Hoy compartiremos la historia[n]de una mujer que fue[n]v胤ctima de fraude.[n][w][e]
[s]Despu姻s de quedarse sin dinero,[n]empez吋 a culparse y ahora sufre[n]de depresi吋n.[n][w][e]

[msg TV_NEWS_0705_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]夷Emocionalmente inestable?[n]Esos estafadores son implacables.[n][w][e]

[msg TV_NEWS_0706_000_00 [Presentador de telediario]]
[s]Algunas personas siguen sin poder[n]acceder a internet, pero ya[n]se ha restablecido el servicio.[n][w][e]
[s]El ISP ha vuelto a confirmar[n]que esto ha sucedido[n]por culpa de un ataque externo.[n][w][e]
[s]Tras examinar los m姻todos[n]empleados, se cree que ha sido[n]un grupo de hackers an吋nimos.[n][w][e]

[msg TV_NEWS_0706_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]夷Un ataque de unos hackers?[n]夷Suelen pasar este tipo[n]de cosas aqu胤?[n][w][e]

[msg TV_MACHI_0707_000_00 [Periodista]]
[s]Hoy tenemos una edici吋n especial[n]de 或斡Exploradores de la ciudad!位.[n][w][e]
[s]斡En estas emisiones especiales,[n]compartimos productos de[n]edici吋n limitada que est茨n de moda![n][w][e]
[s]斡Hoy hablamos del [clr 2]melonpan[clr 27],[n]que se hace con melones[n]frescos de temporada![n][w][e]
[s]Al parecer, son la especialidad[n]de Yon-Germain, la pasteler胤a[n]que hay en la estaci吋n de Shibuya.[n][w][e]

[msg TV_MACHI_0707_100_00 [Especialista]]
[s]Anda, parece un aperitivo[n]de lujo. Me encantar胤a probar[n]uno cuando vaya a Shibuya.[n][w][e]

[msg TV_NEWS_0708_000_00 [Presentador de telediario]]
[s]El descontento con la polic胤a[n]va en aumento, pues siguen sin ser[n]capaces de detener las estafas.[n][w][e]
[s]Muchos dicen que la respuesta del[n]gobierno es inadecuada. Esto puede[n]afectar al 胤ndice de popularidad.[n][w][e]

[msg TV_NEWS_0708_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Supongo que eso significa que somos[n]los 雨nicos que podemos hacerle[n]frente a alguien como Kaneshiro.[n][w][e]

[msg TV_NEWS_0709_000_00 [Presentador de telediario]]
[s]Kaneshiro, el sospechoso del caso,[n]es el l胤der de una mafia[n]de Shibuya.[n][w][e]
[s]A mucha gente le ha sorprendido[n]que hayan arrestado de repente[n]a un gran delincuente.[n][w][e]
[s]La polic胤a ha vuelto a confirmar[n]que los 或Ladrones Fantasma位[n]no participaron en el arresto.[n][w][e]
[s]No obstante, algunos medios[n]dicen lo contrario.[n][w][e]

[msg TV_NEWS_0709_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]La polic胤a deber胤a decir la verdad.[n]夷Por qu姻 se hacen los tontos?[n][w][e]

[msg TV_NEWS_0710_000_00 [Presentador de telediario]]
[s]Y ahora, una novedad sobre[n]el arresto de Kaneshiro, estafador[n]y l胤der de la mafia.[n][w][e]
[s]Justo antes de su arresto, hab胤a[n]或avisos位 con el nombre[n]del sospechoso por toda la zona.[n][w][e]
[s]Se han publicado fotos en internet.[n]Seg雨n algunos, son la prueba de que[n]los 或Ladrones Fantasma位 existen.[n][w][e]

[msg TV_NEWS_0710_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Poner avisos por toda la ciudad[n]ha sido muy eficaz. Si nos hacemos[n]famosos, estaremos muy ocupados.[n][w][e]

[msg TV_NEWS_0711_000_00 [Presentador de telediario]]
[s]A continuaci吋n, una novedad sobre[n]el accidente ocurrido cuando todos[n]estaban pendientes de Kaneshiro.[n][w][e]
[s]A las 8 de esta ma隠ana, un veh胤culo[n]perdi吋 el control en un accidente[n]que se ha cobrado cuatro vidas.[n][w][e]
[s]La polic胤a va a presentar cargos[n]contra el culpable del accidente[n]por las muertes de las v胤ctimas.[n][w][e]
[s]El hombre en cuesti吋n no ten胤a[n]antecedentes de enfermedades y era[n]conductor de 或Goodness Food位.[n][w][e]

[msg TV_NEWS_0711_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1043 65535 0][f 4 25 1 65535 0 0]Qu姻 miedo dan los accidentes.[n]M茨s vale que conduzcas con cuidado.[n][w][e]

[msg TV_NEWS_0712_000_00 [Presentador de telediario]]
[s]A continuaci吋n, una novedad sobre[n]el arresto del l胤der de la mafia.[n][w][e]
[s]Kaneshiro ha admitido que orden吋[n]a sus subordinados[n]que cometieran delitos.[n][w][e]
[s]Sin embargo, mucha gente[n]ha sido v胤ctima de sus estafas.[n]Llevar茨 tiempo investigarlas todas.[n][w][e]

[msg TV_NEWS_0712_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]Vaya, ha estafado a un mont吋n[n]de gente. Supongo que la polic胤a[n]se encargar茨 del resto.[n][w][e]

[msg TV_NEWS_0713_000_00 [Presentador de telediario]]
[s]...acusado de apuestas ilegales.[n]Puede que parezca una tienda[n]de juegos en l胤nea...[n][w][e]
[s]Pero en esa habitaci吋n permiten que[n]los clientes apuesten ilegalmente.[n]Han ganado miles de millones.[n][w][e]
[s]Se dice que parte de las ganancias[n]va para el grupo de Kaneshiro.[n][w][e]

[msg TV_NEWS_0713_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Apostar solo trae problemas.[n]Se ve que hemos destapado muchos[n]de los trapos sucios de Kaneshiro.[n][w][e]

[msg TV_NEWS_0714_000_00 [Presentador de telediario]]
[s]Uno de los miembros[n]de Kaneshiro ha sido arrestado[n]hoy en el aeropuerto.[n][w][e]
[s]Suponemos que trataba de huir[n]a otro pa胤s despu姻s de lo que[n]le ha ocurrido a Kaneshiro.[n][w][e]

[msg TV_NEWS_0714_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1046 65535 0][f 4 25 1 65535 0 0]Las leyes variar茨n seg雨n el pa胤s,[n]pero lo ilegal sigue si姻ndolo[n]all茨 donde vayas.[n][w][e]

[msg TV_NEWS_0715_000_00 [Presentador de telediario]]
[s]Cada a隠o disminuye la cantidad[n]de cerveza que se exporta.[n]En un intento de elevar las cifras...[n][w][e]
[s]Tres grandes compa隠胤as cerveceras[n]han organizado un evento en el que[n]se puede probar su nueva cerveza.[n][w][e]
[s]Hemos hablado con los empleados[n]de la compa隠胤a, que trabajan[n]como personal del evento.[n][w][e]

[msg TV_NEWS_0715_050_00 [Jefe cervecero]]
[s]夷C吋mo hacemos cerveza m茨s rica?[n]Escuchando a nuestros empleados.[n]Su experiencia es valios胤sima...[n][w][e]

[msg TV_NEWS_0715_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Conque la experiencia[n]es valios胤sima... M茨s sabe el diablo[n]por viejo que por diablo.[n][w][e]

[msg TV_NEWS_0716_000_00 [Anuncio de televisi吋n]]
[s]斡Ya est茨 aqu胤 el descomunal sorteo[n]de verano! 斡Este a隠o, el premio[n]son 800 millones de yenes![n][w][e]
[s]La 雨nica forma de ganar[n]es comprar un n雨mero. 斡Estar茨n[n]a la venta hasta el 31 de julio![n][w][e]

[msg TV_NEWS_0716_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1170 65535 0]Eso es verdad, si no compras[n]un n雨mero, no puedes ganar.[n]夷Quieres comprar uno?[n][w][e]

[msg TV_NEWS_0717_000_00 [Presentador desenfadado]]
[s]斡Hoy hablaremos sobre[n]eventos de verano![n][w][e]
[s]斡Reci姻n salidos del horno! Veamos[n]c吋mo fue el festival de verano.[n]斡Dentro v胤deo![n][w][e]

[msg TV_NEWS_0717_050_00 [Ryuji]]
[s]Y si hace este calor en julio,[n]斡imag胤nate qu姻 locura ser茨 esto[n]cuando llegue diciembre![n][w][e]
[s]Somos m茨s bien amantes de la fruta.[n]斡Y de los dulces, que son lo mejor![n][w][e]

[msg TV_NEWS_0717_100_00]
[s]Ryuji est茨 respondiendo[n]al entrevistador.[n][w][e]

[msg TV_NEWS_0717_150_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]Madre m胤a. Al final[n]decidieron meter esa parte...[n][w][e]

[msg TV_NEWS_0718_000_00 [Presentador de telediario]]
[s]Este es el comunicado[n]del grupo internacional de hackers,[n]Medjed.[n][w][e]
[s]或A los Ladrones Fantasma tan[n]famosos de Jap吋n: no promulgu姻is[n]vuestra falsa justicia位.[n][w][e]
[s]或No necesitamos que difund茨is[n]esa farsa. Somos los verdaderos[n]ejecutores de la justicia位.[n][w][e]
[s]或Sin embargo, somos magn茨nimos.[n]Os daremos una oportunidad[n]de arrepentiros位.[n][w][e]
[s]或Si despert茨is un coraz吋n,[n]os aceptaremos entre nosotros位.[n][w][e]
[s]或Si rechaz茨is nuestra oferta,[n]la justicia caer茨 sobre vosotros位.[n][w][e]

[msg TV_NEWS_0718_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]或Falsa justicia位, 夷eh? Pero[n]夷qui姻nes se creen que son?[n][w][e]

[msg TV_NEWS_0719_000_00 [Presentador de telediario]]
[s]El fat胤dico accidente de tr茨fico[n]del 11 de este mes ha tenido[n]unas consecuencias inesperadas.[n][w][e]
[s]Las acciones de Goodness Food se[n]han desplomado, y hay una inquietud[n]general en el mercado.[n][w][e]
[s]Desde el incendio de su filial,[n]Haneruya, Goodness Food intenta[n]limpiar su imagen desesperadamente.[n][w][e]
[s]Tras la muerte del vicepresidente,[n]que era su as bajo la manga,[n]la empresa est茨 atemorizada.[n][w][e]
[s]No obstante, la competencia[n]de Goodness Food est茨[n]aprovechando este bache.[n][w][e]

[msg TV_NEWS_0719_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Esta empresa va de mal en peor.[n]Mmm. Lo mismo est茨n[n]malditos o algo as胤.[n][w][e]

[msg TV_NEWS_0720_000_00 [Presentador de telediario]]
[s]Este es el 雨ltimo comunicado[n]del grupo Medjed.[n][w][e]
[s]或Los Ladrones Fantasma permanecen[n]en silencio ante nuestra pregunta.[n]Esto demuestra que somos justos位.[n][w][e]
[s]或Ciudadanos y ciudadanas,[n]despertad. No ador姻is[n]a los Ladrones Fantasma位.[n][w][e]
[s]或Confiscaremos las posesiones[n]de cualquiera que los adore[n]a modo de castigo位.[n][w][e]
[s]或Somos Medjed. Actuamos[n]en la sombra. Detendremos el mal位.[n][w][e]

[msg TV_NEWS_0720_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]斡Est茨n actuando sin esperar[n]siquiera a que respondamos![n]夷Qu姻 pretenden hacer?[n][w][e]

[msg TV_NEWS_0721_000_00 [Presentador de telediario]]
[s]Medjed, un peligroso grupo[n]de hackers, ha desafiado[n]a los Ladrones Fantasma.[n][w][e]
[s]Este programa ha conseguido un[n]或aviso位 de, seg雨n pone aqu胤, los[n]或Ladrones Fantasma de Corazones位.[n][w][e]
[s]En 姻l, afirman que har茨n[n]que su objetivo[n]或confiese sus pecados位.[n][w][e]

[msg TV_NEWS_0721_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0][f 4 25 1 65535 0 0]Anda, nos hemos hecho famosos.[n]Supongo que no es ninguna sorpresa[n]que estemos en boca de todos.[n][w][e]

[msg TV_NEWS_0722_000_00 [Presentador de telediario]]
[s]Medjed, un peligroso grupo[n]de hackers, ha desafiado[n]a los Ladrones Fantasma.[n][w][e]
[s]Este programa ha conseguido un[n]或aviso位 de, seg雨n pone aqu胤, los[n]或Ladrones Fantasma de Corazones位.[n][w][e]
[s]En 姻l, afirman que har茨n[n]que su objetivo[n]或confiese sus pecados位.[n][w][e]

[msg TV_NEWS_0722_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]斡Nos hacemos cada vez m茨s famosos![n]斡Ir a por Kaneshiro[n]fue una idea estupenda![n][w][e]

[msg TV_NEWS_0723_000_00 [Presentador de telediario]]
[s]Un comunicado de Medjed[n]ha provocado a los Ladrones[n]Fantasma de Corazones.[n][w][e]
[s]De momento, nadie ha confesado ser[n]uno de los Ladrones Fantasma.[n][w][e]
[s]Como la identidad de ambos grupos[n]es un misterio, la gente est茨[n]pendiente de lo que har茨n ahora.[n][w][e]

[msg TV_NEWS_0723_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Nos estamos haciendo famosos.[n]Quiero cumplir las expectativas[n]de la gente, pero estos hackers...[n][w][e]

[msg TV_NEWS_0724_000_00 [Presentador de telediario]]
[s]La temporada de lluvias ha acabado[n]y por fin ha llegado el verano.[n][w][e]
[s]Las vacaciones de verano no andan[n]muy lejos, y las playas y piscinas[n]de la zona ya tienen visitantes.[n][w][e]
[s]Una de las playas cercanas[n]al centro est茨 repleta de gente.[n][w][e]

[msg TV_NEWS_0724_100_00]
[s]Se ve que va a empezar[n]a hacer cada vez m茨s calor.[n][w][e]

[msg TV_NEWS_0725_000_00 [Presentador de telediario]]
[s]Y ahora, m茨s novedades[n]sobre Medjed, que emiti吋[n]un comunicado anoche.[n][w][e]
[s]En la p茨gina de Medjed[n]hay una declaraci吋n de victoria y[n]un anuncio sobre su pr吋ximo delito.[n][w][e]
[s]Se cree que es otra provocaci吋n[n]para los Ladrones Fantasma,[n]que a雨n no se han pronunciado.[n][w][e]

[msg TV_NEWS_0725_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]Se les est茨 yendo de las manos.[n]Bueno, que se preparen.[n][w][e]

[msg TV_NEWS_0726_000_00 [Presentador de telediario]]
[s]Y ahora, novedades de Medjed,[n]cuyos comunicados han causado[n]un gran revuelo.[n][w][e]
[s]Tras su segundo comunicado,[n]a muchos les preocupa[n]que vaya a haber otro ciberataque.[n][w][e]
[s]Sin embargo, los Ladrones[n]Fantasma siguen sin decir nada.[n][w][e]

[msg TV_NEWS_0726_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1161 65535 0][f 4 25 1 65535 0 0]Esto se est茨 convirtiendo[n]en un problem吋n. Quiero ir[n]y acabar con Medjed, pero...[n][w][e]

[msg TV_MACHI_0727_000_00 [Periodista]]
[s]En 或斡Exploradores de la ciudad!位,[n]斡hablamos de sitios de citas[n]para las vacaciones de verano![n][w][e]
[s]斡Ahora mismo, estamos[n]en el planetario de [clr 2]Ikebukuro[clr 27]![n][w][e]
[s]Mirar al cielo y verlo lleno[n]de estrellas es muy rom茨ntico.[n]斡Y el ambiente es muy relajante![n][w][e]

[msg TV_MACHI_0727_100_00 [Especialista]]
[s]Es un lugar m茨gico. Si quieres[n]acercarte a alguien, es[n]el sitio ideal para ir de cita.[n][w][e]

[msg TV_MACHI_0727_200_00 [Maestro de ceremonias]]
[s]斡Tenemos otro sitio que presentar[n]en nuestra emisi吋n[n]especial de verano![n][w][e]
[s]Si no has o胤do hablar de 姻l,[n]es que vives en una burbuja.[n]斡S胤, el Destinyland de [clr 2]Maihama[clr 27]![n][w][e]
[s]Como siempre, est茨 llen胤simo[n]de gente. 斡Es un mundo[n]lleno de sue隠os y esperanza![n][w][e]

[msg TV_MACHI_0727_300_00 [Especialista]]
[s]Siempre he querido ir ah胤[n]con pareja. Parece[n]un lugar de ensue隠o.[n][w][e]

[msg TV_NEWS_0728_000_00 [Presentador de telediario]]
[s]Aunque hay pistas, el grupo de[n]hackers, Medjed, no ha dejado claro[n]el objetivo de su pr吋ximo ataque.[n][w][e]
[s]Seg雨n los expertos,[n]hay varias empresas que podr胤an ser[n]objetivos potenciales.[n][w][e]
[s]Las empresas de transporte p雨blico[n]y otros servicios se han visto[n]presionadas a tomar medidas.[n][w][e]

[msg TV_NEWS_0728_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Qu姻 mal rollo da Medjed.[n]La est茨n liando much胤simo.[n][w][e]

[msg TV_NEWS_0729_000_00 [Presentador de telediario]]
[s]Los Ladrones Fantasma a雨n no[n]han respondido a Medjed.[n]夷Qu姻 les parece?[n][w][e]

[msg TV_NEWS_0729_100_00 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 2 1 54406 65535 0][f 4 25 1 65535 0 0]Lo m茨s probable es que[n]los Ladrones Fantasma no tengan[n]forma de enfrentarse a ellos.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Al fin y al cabo, Medjed es[n]bastante diferente a los dem茨s[n]rivales que se han encontrado.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Creo que la mejor opci吋n es[n]que desvelen su identidad antes[n]de que m茨s gente salga mal parada.[n][w][e]

[msg TV_NEWS_0729_200_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Nos ha dado donde m茨s nos duele.[n]Pero 斡acabaremos con ellos![n][w][e]

[msg TV_NEWS_0729_000_00_HIRU [Narraci吋n]]
[s]Hoy, en 或斡La verdad![n]Documento Jap吋n 24位...[n][w][e]
[s]El popular Pr胤ncipe Detective[n]hablar茨 sobre el enfrentamiento de[n]los Ladrones Fantasma con Medjed.[n][w][e]

[msg TV_NEWS_0729_100_00_HIRU [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 2 1 54436 65535 0][f 4 25 1 65535 0 0]Opino lo siguiente...[n][w][e]

[msg TV_ANIME_0730_000_00 [Narrador]]
[s]斡El enemigo controla el cuerpo[n]de B雨ho y le obliga a comer platos[n]de delicioso curry sin parar![n][w][e]
[s]夷Podr茨 B雨ho Amarillo ingerir[n]tanto curry, o explotar茨?[n]斡Revivid y luchad, Phoenix Rangers![n][w][e]
[s]En el pr吋ximo episodio...[n]或Cuando se trata de curry,[n]apuesta siempre por el amarillo位.[n][w][e]

[msg TV_NEWS_0731_000_00 [Presentador de telediario]]
[s]Medjed ha pedido que[n]los Ladrones Fantasma desvelen[n]su verdadera identidad.[n][w][e]
[s]Estos, sin embargo, han ganado[n]popularidad en internet[n]como 或aliados de la justicia位.[n][w][e]
[s]Cada vez reciben m茨s apoyo,[n]y algunos dicen que son los 雨nicos[n]que pueden derrotar a Medjed.[n][w][e]
[s]El mundo ver茨 lo que hacen[n]los Ladrones Fantasma antes de[n]la fecha l胤mite, el 21 de agosto.[n][w][e]

[msg TV_NEWS_0731_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1162 65535 0][f 4 25 1 65535 0 0]Todos cuentan con nosotros.[n]No podemos decepcionarlos.[n][w][e]

[msg TV_NEWS_0801_000_00 [Presentador de telediario]]
[s]Y ahora, Palabras noticieras, donde[n]explicamos palabras que salen en[n]las noticias. La palabra de hoy es...[n][w][e]
[s]或Medjed位. Son un grupo famoso[n]de hackers. Se desconoce[n]la identidad de sus miembros.[n][w][e]
[s]Medjed ha llevado a cabo muchos[n]ataques ciberterroristas y se[n]han hecho famosos en todo el mundo.[n][w][e]
[s]No obstante, a雨n no se sabe[n]por qu姻 quieren atacar Jap吋n.[n][w][e]

[msg TV_NEWS_0801_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]Nuestros rivales tambi姻n son[n]muy famosos. Si quieren luchar,[n]斡lo haremos limpiamente![n][w][e]

[msg TV_NEWS_0802_000_00 [Presentador de telediario]]
[s]Y ahora, Palabras noticieras, donde[n]explicamos palabras que salen en[n]las noticias. La palabra de hoy es...[n][w][e]
[s]或[f 4 28]位. Est茨n en el[n]punto de mira con motivo de su[n]inminente contienda con Medjed.[n][w][e]
[s]Los Ladrones Fantasma son[n]un tema de actualidad y est茨n[n]entre los t姻rminos m茨s buscados.[n][w][e]

[msg TV_NEWS_0802_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]La gente nos quiere.[n]No podemos estropearlo ahora.[n][w][e]

[msg TV_MACHI_0803_000_00 [Periodista]]
[s]En 或斡Exploradores de la ciudad!位,[n]un especial de zonas de citas[n]para adultos, 斡justo para el Obon![n][w][e]
[s]Estamos en [clr 2]Jinbocho[clr 27], en La ciudad[n]de los libros, el para胤so para[n]los ratones de biblioteca.[n][w][e]
[s]斡Mirad! Libros, libros[n]y m茨s libros mires donde mires.[n]斡Estoy sin palabras![n][w][e]

[msg TV_MACHI_0803_100_00 [Especialista]]
[s]En una era en la que todo es[n]digital, sienta bien hojear[n]un libro de verdad.[n][w][e]

[msg TV_MACHI_0803_200_00 [Maestro de ceremonias]]
[s]Y ahora hablamos del estanque[n]de [clr 2]Ichigaya[clr 27].[n][w][e]
[s]Puedes ir a pescar[n]en medio de la ciudad. Es una[n]buena forma de pasar el rato.[n][w][e]

[msg TV_MACHI_0803_300_00 [Especialista]]
[s]Yo voy mucho por all胤.[n]Aunque hace tiempo que no[n]pesco nada. Ja, ja, ja...[n][w][e]

[msg TV_QUIZ_0804_000_00 [Presentador de concurso]]
[s]Los carteristas y rateros[n]son culpables de hurto,[n]pero 夷y los siguientes casos?[n][w][e]
[s]A) Robar de un monedero extraviado.[n]B) Robar un coche, pero devolverlo.[n][w][e]
[s]夷Cu茨l de estas opciones[n]se considera hurto?[n]斡Juzguen ustedes mismos![n][w][e]

[sel SEL_QUIZ_0804 top]
[s]Robar de un monedero extraviado.[e]
[s]Robar un coche, pero devolverlo.[e]

[msg TV_QUIZ_0804_100_00 [Presentador de concurso]]
[s]La respuesta correcta es... 斡la B![n]斡Decir que ten胤as pensado[n]devolverlo no servir茨 en un juicio![n][w][e]

[msg TV_QUIZ_0804_200_00 [Abogado]]
[s]Consumes gasolina y desgastas[n]las ruedas. Robar el coche[n]de alguien sin su permiso es hurto.[n][w][e]
[s]Coger algo que alguien ha perdido[n]o que se le ha ca胤do es otra clase[n]de robo menos grave.[n][w][e]
[s]Por cierto, lo que hacen[n]los Ladrones Fantasma[n]no se puede considerar hurto.[n][w][e]

[msg TV_MORGANA_0804_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]S胤, te has equivocado... pero o胤r[n]esto me ha dado ganas de jugar[n]al 或ratero位 y el gato.[n][w][e]

[msg TV_MORGANA_0804_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]Anda, has acertado. Incluso si[n]lo devuelves despu姻s,[n]se considera robo, 夷no?[n][w][e]

[msg TV_WIDESHOW_0805_000_00 [Presentador]]
[s]斡Saludos! 斡Hoy tenemos un especial[n]dedicado al desconocido mundo[n]de los videojuegos antiguos![n][w][e]
[s]斡Poco a poco se est茨[n]convirtiendo en todo un fen吋meno![n]夷Quieres volver a tu infancia?[n][w][e]

[msg TV_WIDESHOW_0805_100_00 [Comentarista]]
[s]Me recuerda a mi infancia. Sol胤a[n]jugar a escondidas sin que[n]mis padres lo supieran.[n][w][e]
[s]Mucha gente compra [clr 2]videoconsolas[clr 27][n]antiguas en [clr 2]tiendas de segunda[n]mano[clr 27] por pura nostalgia.[n][w][e]

[msg TV_NEWS_0806_000_00 [Presentador de telediario]]
[s]Traemos las 雨ltimas novedades[n]sobre el grupo hacktivista Medjed[n]y los Ladrones Fantasma.[n][w][e]
[s]Hemos hecho una encuesta sobre[n]el pr吋ximo enfrentamiento entre[n]los Ladrones Fantasma y Medjed.[n][w][e]
[s]El 80 % de los encuestados[n]est茨 interesado, lo que indica[n]que est茨 captando mucha atenci吋n.[n][w][e]

[msg TV_NEWS_0806_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]斡Estamos en boca de todos![n]Tenemos que hacer algo pronto.[n][w][e]

[msg TV_NEWS_0808_000_00 [Comentarista minuto a minuto]]
[s]斡Ha sonado la sirena! Ya[n]es oficial. 斡El torneo de b姻isbol[n]de institutos ha comenzado![n][w][e]
[s]En este primer partido,[n]tenemos un equipo de un instituto[n]p雨blico con tan solo 13 miembros.[n][w][e]

[msg TV_NEWS_0808_100_00 [Presentador de telediario]]
[s]夷Cu茨l es su opini吋n sobre[n]el revuelo que se ha formado[n]por este enfrentamiento?[n][w][e]

[msg TV_NEWS_0808_200_00 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 2 1 54436 65535 0][f 4 25 1 65535 0 0]Creo que, tanto para Medjed[n]como para los Ladrones Fantasma,[n]esta atenci吋n mueve sus delitos.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]De ah胤 tanto espect茨culo para[n]impresionar a la gente. Aconsejo[n]no dejarse llevar tanto.[n][w][e]

[msg TV_NEWS_0808_300_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1043 65535 0][f 4 25 1 65535 0 0]夷Est茨 hablando como si nosotros[n]tambi姻n fu姻ramos delincuentes?[n]No nos guardar茨 rencor, 夷no?[n][w][e]

[msg TV_NEWS_0809_000_00 [Presentador de telediario]]
[s]Han pasado poco m茨s de dos[n]semanas desde que Medjed[n]anunci吋 su ataque.[n][w][e]
[s]La polic胤a est茨 recabando datos[n]sobre Medjed y promoviendo[n]medidas de seguridad. Sin embargo...[n][w][e]
[s]No se espera mucho de ellos. Todos[n]est茨n atentos al enfrentamiento[n]de los Ladrones Fantasma y Medjed.[n][w][e]

[msg TV_NEWS_0809_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]La polic胤a no puede hacer nada[n]en esta situaci吋n. Tendremos[n]que ocuparnos nosotros.[n][w][e]

[msg TV_NEWS_0810_000_00 [Comentarista minuto a minuto]]
[s]En el momento decisivo[n]del tercer partido. 斡El as[n]Tanaka se sube al mont胤culo![n][w][e]
[s]A pesar de haber sufrido[n]una lesi吋n grave justo antes[n]del torneo, 斡ha vuelto a la carga![n][w][e]

[msg TV_NEWS_0810_100_00 [Presentador de telediario]]
[s]Las empresas han estado luchando[n]por establecer medidas en[n]respuesta al comunicado de Medjed.[n][w][e]
[s]Se ha publicado una estimaci吋n[n]de los posibles da隠os[n]por un ataque ciberterrorista.[n][w][e]
[s]Seg雨n los expertos,[n]podr胤an alcanzar[n]los trillones de yenes.[n][w][e]

[msg TV_NEWS_0810_200_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]夷Trillones?[n]Estos t胤os son un peligro.[n][w][e]

[msg TV_NEWS_0811_000_00 [Presentador de telediario]]
[s]Todo el mundo ha empezado[n]a volver a sus hogares[n]para prepararse para el Obon.[n][w][e]
[s]Los trenes y aviones est茨n[n]llenos, y sigue habiendo[n]atascos en las carreteras.[n][w][e]

[msg TV_NEWS_0811_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]Volver a casa, 夷eh?[n]Debe ser bonito tener un hogar[n]al que poder regresar.[n][w][e]

[msg TV_NEWS_0812_000_00 [Presentador de telediario]]
[s]El anuncio del ataque de Medjed[n]tambi姻n ha llamado la atenci吋n[n]en el extranjero.[n][w][e]
[s]Este es un claro indicador de c吋mo[n]han ganado influencia y notoriedad[n]estos hacktivistas internacionales.[n][w][e]
[s]Al elegir a los Ladrones Fantasma[n]como sus rivales,[n]su publicidad es a雨n mayor.[n][w][e]

[msg TV_NEWS_0812_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Nuestra fama traspasa[n]las fronteras de otros pa胤ses.[n]夷No deber胤amos estar contentos?[n][w][e]

[msg TV_NEWS_0813_000_00 [Comentarista minuto a minuto]]
[s]Tras acabar el quinto partido[n]de la segunda ronda con 23 puntos[n]de diferencia, la cosa pinta mal.[n][w][e]
[s]Pero 斡aqu胤 no se rinde nadie![n]斡Vuelven a la final de las ligas[n]menores a darlo todo![n][w][e]

[msg TV_NEWS_0813_100_00 [Presentador de telediario]]
[s]Anoche, el primer ministro[n]dio una rueda de prensa.[n][w][e]
[s]Inst吋 a la ciudadan胤a a 或mantener[n]la calma位 tras el anuncio[n]de los planes de ataque de Medjed.[n][w][e]
[s]No obstante, se desconocen[n]las medidas que est茨 tomando[n]el gobierno para evitar el golpe.[n][w][e]
[s]Parece que la ola de cr胤ticas por[n]su debilidad ante los ciberdelitos[n]cobrar茨 a雨n m茨s fuerza.[n][w][e]

[msg TV_NEWS_0813_200_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Nadie puede tocarlos... Futaba[n]es nuestra 雨ltima esperanza.[n][w][e]

[msg TV_NEWS_0815_000_00 [Comentarista minuto a minuto]]
[s]Parece que tocar茨 tierra justo[n]frente al central. 斡No, la ha[n]atrapado! 斡Qu姻 jugada![n][w][e]
[s]Ser茨 bajito, pero vaya m茨quina.[n][w][e]

[msg TV_NEWS_0815_100_00 [Presentador de telediario]]
[s]Hoy tenemos a Goro Akechi[n]como invitado.[n][w][e]
[s]En internet se espera mucho[n]de los Ladrones Fantasma.[n]夷Qu姻 opinas al respecto?[n][w][e]

[msg TV_NEWS_0815_200_00 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 2 1 54433 65535 0][f 4 25 1 65535 0 0]Me parece inadmisible.[n]Aunque, en cierto modo,[n]quiz茨s soy responsable de ello.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Puede que mis declaraciones sobre[n]los Ladrones Fantasma hayan[n]magnificado su popularidad.[n][w][e]

[msg TV_NEWS_0815_300_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Pf, encima intenta ir de guay.[n]Espera y ver茨s.[n][w][e]

[msg TV_NEWS_0816_000_00 [Presentador de telediario]]
[s]Los ciudadanos que regresaron[n]a sus hogares para[n]el Obon vuelven ahora en masa.[n][w][e]
[s]Los aeropuertos y estaciones de[n]autobuses est茨n a rebosar de gente[n]cargando con maletas y regalos.[n][w][e]

[msg TV_NEWS_0816_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Hala, qu姻 de gente.[n]Y todos parecen muy ocupados.[n][w][e]

[msg TV_NEWS_0817_000_00 [Presentador de telediario]]
[s]Continuamos con lo 雨ltimo sobre la[n]declaraci吋n de ataque por parte[n]del grupo de hacktivistas Medjed.[n][w][e]
[s]Quedan unos d胤as para el[n]21 de agosto, el d胤a del ataque,[n]y las empresas tiemblan de miedo.[n][w][e]
[s]Al no haber respuesta[n]de los Ladrones Fantasma, hay quien[n]piensa que se han acobardado.[n][w][e]

[msg TV_NEWS_0817_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]夷Eh? 斡Nosotros no huimos![n]斡Y nunca nos rendimos![n]斡Ya vais a ver![n][w][e]

[msg TV_NEWS_0818_000_00 [Presentador de telediario]]
[s]Continuamos con el seguimiento[n]del grupo Medjed.[n][w][e]
[s]Ya falta poco para el d胤a[n]del ataque, y se ha desatado[n]una gran expectaci吋n.[n][w][e]
[s]En otros pa胤ses se muestra tambi姻n[n]un enorme inter姻s, y se organizan[n]apuestas sobre qui姻n ganar茨.[n][w][e]
[s]Un corredor de apuestas afirma[n]que Medjed tiene m茨s posibilidades.[n][w][e]

[msg TV_NEWS_0818_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]夷En serio est茨n apostando?[n]夷Creen que vamos a perder?[n][w][e]

[msg TV_NEWS_0819_000_00 [Comentarista minuto a minuto]]
[s]Las bases est茨n llenas, y parece[n]que podr胤an estar en apuros.[n]夷Lograr茨n salir de esta?[n][w][e]
[s]Y ah胤 va... 斡Tercer strike! 斡Y[n]este es su d姻cimo[n]strikeout hoy![n][w][e]
[s]Es una acalorada batalla entre[n]lanzadores. Los equipos no est茨n[n]anotando carreras en la final.[n][w][e]

[msg TV_NEWS_0819_100_00 [Presentador de telediario]]
[s]El d胤a del ataque de Medjed[n]se acerca. 夷Alg雨n comentario que[n]desees compartir con la audiencia?[n][w][e]

[msg TV_NEWS_0819_200_00 [Akechi]]
[s][bup 0 9 0 2 0][f 4 10 65535 0 0][vp 8 2 1 54436 65535 0][f 4 25 1 65535 0 0]Medjed es un enorme peligro.[n]A juzgar por su historial,[n]cumplir茨n sus amenazas.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Es evidente que Medjed ha aparecido[n]porque los Ladrones Fantasma[n]los han provocado est雨pidamente.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Si a los Ladrones Fantasma les[n]queda una pizca de decencia, dar茨n[n]la cara y se responsabilizar茨n.[n][w][e]

[msg TV_NEWS_0819_300_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]夷Est茨 diciendo que es nuestra[n]culpa? 夷Has visto c吋mo[n]nos ha cargado el muerto?[n][w][e]

[msg TV_NEWS_0820_000_00 [Presentador de telediario]]
[s]Continuamos con las noticias[n]sobre Medjed.[n][w][e]
[s]A pocas horas del 21 de agosto,[n]los hacktivistas est茨n demasiado[n]tranquilos.[n][w][e]
[s]Si se produce el ataque, no[n]podemos descartar que d姻 lugar[n]a una recesi吋n a nivel mundial.[n][w][e]

[msg TV_NEWS_0820_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1038 65535 0][f 4 25 1 65535 0 0]La fecha l胤mite es ma隠ana, 夷no?[n]No me extra隠a que la gente[n]haya entrado en p茨nico.[n][w][e]

[msg TV_NEWS_0821_000_00 [Presentador de telediario]]
[s]Hoy es el d胤a del ataque de Medjed,[n]y el p茨nico inunda la ciudad.[n][w][e]
[s]Algunos ciudadanos evitan[n]salir al exterior, y todos[n]est茨n muy alterados.[n][w][e]
[s]Muchas empresas han estado[n]trabajando d胤a y noche para[n]intentar protegerse del ataque.[n][w][e]

[msg TV_NEWS_0821_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]No ha cambiado nada todav胤a.[n]Solo podemos rezar...[n][w][e]

[msg TV_NEWS_0822_000_00 [Presentador de telediario]]
[s]Con esto termina nuestro informe[n]sobre el hackeo a la p茨gina[n]de Medjed. Continuemos.[n][w][e]
[s]Las temperaturas est茨n aumentando[n]en todo el pa胤s, dando lugar a los[n]d胤as m茨s calurosos de este verano.[n][w][e]
[s]La temperatura de hoy es[n]extremadamente alta, y muchos[n]escapan de ella gracias al agua.[n][w][e]
[s]La playa cercana a la ciudad[n]est茨 abarrotada de gente[n]que disfruta de la 姻poca estival.[n][w][e]

[msg TV_NEWS_0822_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]斡Tienes que ir a la playa este[n]verano! 斡Deber胤amos ir juntos![n][w][e]

[msg TV_NEWS_0823_000_00 [Presentador de telediario]]
[s]El grupo hacktivista Medjed declar吋[n]sus intenciones de atacar, pero...[n][w][e]
[s]De momento, sus amenazas[n]se han quedado en nada.[n][w][e]
[s]Mientras, las redes bullen[n]de entusiasmo, aclamando la[n]victoria de los Ladrones Fantasma.[n][w][e]

[msg TV_NEWS_0823_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]斡Hala, qu姻 pasada, hemos ganado![n][w][e]

[msg TV_NEWS_0824_000_00 [Periodista]]
[s]En 或斡Exploradores de la ciudad!位,[n]hoy tenemos un especial de verano.[n][w][e]
[s]斡A雨n no es tarde para ir[n]a la playa! 斡Est茨 cerca, as胤 que[n]se puede ir y venir el mismo d胤a![n][w][e]

[msg TV_NEWS_0824_100_00 [Especialista]]
[s]Pinta bien. Sin una visita[n]a la playa, no parece verano.[n]夷Y si me compro un ba隠ador nuevo?[n][w][e]

[msg TV_NEWS_0825_000_00 [Presentador de telediario]]
[s]La polic胤a ha emitido un comunicado[n]sobre el incidente con Medjed.[n][w][e]
[s]Afirman estar 或investig茨ndolo[n]cuidadosamente位, mas no mencionan[n]a los Ladrones Fantasma.[n][w][e]
[s]Muchos han mostrado su descontento[n]con la polic胤a, y...[n][w][e]

[msg TV_NEWS_0825_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]La polic胤a ha quedado fatal,[n]aunque no es culpa suya.[n][w][e]

[msg TV_NEWS_0826_000_00 [Presentador]]
[s]斡Buenas! Hoy el programa durar茨[n]algo m茨s por el especial[n]sobre los Ladrones Fantasma.[n][w][e]
[s]斡Despu姻s de la publicidad, veremos[n]si logramos arrojar luz sobre[n]los misterios que los rodean![n][w][e]

[msg TV_NEWS_0826_100_00 [Panelista]]
[s]Los Ladrones Fantasma son muy[n]populares entre los j吋venes.[n]Para algunos, son dioses.[n][w][e]

[msg TV_NEWS_0827_000_00 [Presentador de telediario]]
[s]Y ahora, vamos con el informe sobre[n]el incidente con Medjed ocurrido[n]hace unos d胤as.[n][w][e]
[s]El p雨blico sigue venerando[n]a los Ladrones Fantasma, quienes[n]parecen haber evitado el ataque.[n][w][e]
[s]Su popularidad, nacida[n]en las redes, se expande[n]ahora m茨s all茨 de internet.[n][w][e]
[s]Los Ladrones Fantasma[n]se han convertido en un fen吋meno[n]social en boca de todos.[n][w][e]

[msg TV_NEWS_0827_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]斡Todo el mundo habla de nosotros![n]斡Nos hemos hecho famosos![n][w][e]

[msg TV_NEWS_0828_000_00 [Presentador de telediario]]
[s]El 雨ltimo domingo de las vacaciones[n]ha amanecido soleado, y la[n]temperatura ha seguido aumentado.[n][w][e]
[s]La presi吋n atmosf姻rica es alta,[n]y se espera que el buen tiempo[n]de hoy se alargue hasta ma隠ana.[n][w][e]

[msg TV_NEWS_0828_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]斡Parece que no habr茨 que[n]preocuparse por el tiempo![n]斡Qu姻 ganas de que sea ma隠ana![n][w][e]

[msg TV_NEWS_0829_000_00 [Presentador de telediario]]
[s]La siguiente noticia es sobre[n]los Ladrones Fantasma.[n][w][e]
[s]La popularidad[n]de [f 4 28] no deja de crecer.[n][w][e]
[s]Hay todo tipo de productos[n]sobre ellos, y se venden[n]en un abrir y cerrar de ojos.[n][w][e]
[s]Su influencia sigue aumentando,[n]y esta fiebre fantasmal[n]no muestra indicios de remitir.[n][w][e]

[msg TV_NEWS_0829_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]斡Han dicho que hay[n]una fiebre fantasmal! 斡Qu姻[n]orgulloso estoy de nosotros![n][w][e]

[msg TV_SHOUGI_0830_000_00 [Jugador profesional de shogi]]
[s]Lancero a 2-6...[n]Mm, no s姻 yo, me da[n]mala espina ese movimiento.[n][w][e]
[s]Tiende a enfadar al rival,[n]que suele actuar de forma muy[n]agresiva cuando lo provocan.[n][w][e]

[msg TV_SHOUGI_0830_100_00 [Entrevistadora]]
[s]A m胤 no me parece mal movimiento,[n]pero supongo que t雨 hablas[n]desde la experiencia.[n][w][e]

[msg TV_SHOUGI_0830_200_00 [Jugador profesional de shogi]]
[s]Adem茨s, cuando el rival se enfada[n]de esa forma, es casi imposible[n]revertir la situaci吋n.[n][w][e]
[s]No te s姻 decir la de veces[n]que yo... No, da igual.[n][w][e]

[msg TV_MACHI_0831_000_00 [Periodista]]
[s]En 或斡Exploradores de la ciudad!位,[n]斡tenemos un especial[n]sobre [clr 2]Akihabara[clr 27]![n][w][e]
[s]Este es un lugar lleno de turistas.[n]La ca吋tica atm吋sfera que se[n]respira en 姻l es impresionante.[n][w][e]

[msg TV_MACHI_0831_100_00 [Especialista]]
[s]A m胤 me gustan mucho los juegos[n]retro y siempre visito las tiendas[n]de segunda mano de Akihabara.[n][w][e]
[s]Siempre me emociono cuando[n]encuentro una [clr 2]consola[clr 27] antigua[n]en esas tiendas, ja, ja.[n][w][e]

[msg TV_NEWS_0901_000_00 [Presentador de telediario]]
[s]La siguiente noticia tambi姻n est茨[n]relacionada con los Ladrones[n]Fantasma.[n][w][e]
[s]Muchos famosos han empezado[n]a publicar disculpas en blogs[n]personales y medios similares.[n][w][e]
[s]La opini吋n general es que[n]lo hacen para protegerse[n]de los Ladrones Fantasma.[n][w][e]
[s]Creen que, si se disculpan[n]con antelaci吋n, no ser茨n un blanco[n]de los Ladrones Fantasma.[n][w][e]

[msg TV_NEWS_0901_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]夷Hay gente confesando[n]voluntariamente lo que han hecho?[n]Pues s胤 que nos tienen miedo.[n][w][e]

[msg TV_NEWS_0902_000_00 [Presentador de telediario]]
[s]La p茨gina web del grupo hacktivista[n]que amenaz吋 con atacar Jap吋n...[n]ha sido hackeada.[n][w][e]
[s]Pero 夷qui姻n lo hizo?[n]夷Podr胤a [f 4 28][n]tener algo que ver?[n][w][e]
[s]Hemos estado investigando[n]para intentar[n]llegar al fondo del asunto.[n][w][e]

[msg TV_NEWS_0902_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Vaya, a todo el mundo le interesan[n]los Ladrones Fantasma.[n]Que no nos descubran, 夷eh?[n][w][e]

[msg TV_ANIME_0903_000_00 [Narrador]]
[s]Cuando todo parec胤a estar en contra[n]de Featherman, ha aparecido[n]un nuevo aliado.[n][w][e]
[s]斡Con una capa de viento, una[n]flecha emplumada surca los cielos![n]斡Revivid y luchad, Phoenix Rangers![n][w][e]
[s]En el pr吋ximo episodio...[n]或La victoria de Grulla Rosa位.[n][w][e]

[msg TV_NEWS_0904_000_00 [Presentador de telediario]]
[s]Otros pa胤ses tambi姻n tienen[n]los ojos puestos en las actividades[n]de los Ladrones Fantasma.[n][w][e]
[s]Medios de todo el mundo[n]se han hecho eco[n]de la ca胤da de Medjed.[n][w][e]
[s]Gente de todas partes elogia[n]a los Ladrones Fantasma por[n]salvar al mundo de esta amenaza.[n][w][e]

[msg TV_NEWS_0904_100_00 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]Tambi姻n somos noticia[n]en otros pa胤ses. Nunca pens姻[n]que llegar胤amos tan lejos.[n][w][e]

[msg TV_NEWS_0905_000_00 [Presentador de telediario]]
[s]Se ha formado un enorme tif吋n[n]en el oc姻ano Pac胤fico, y se[n]aproxima con furia.[n][w][e]
[s]A la Agencia Meteorol吋gica de[n]Jap吋n le preocupa que toque tierra,[n]y est茨 siguiendo su recorrido.[n][w][e]

[msg TV_NEWS_0905_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]Conque un tif吋n, 夷eh? Espero[n]que no le pase nada al avi吋n.[n][w][e]

[msg TV_NEWS_0906_000_00 [Presentador de telediario]]
[s]No fue la polic胤a quien acab吋 con[n]el ciberterrorismo de Medjed, sino[n]un misterioso grupo de justicieros.[n][w][e]
[s]Se hacen llamar 或los Ladrones[n]Fantasma位, y han alcanzado[n]una enorme popularidad.[n][w][e]
[s]Vamos a intentar ponerles cara.[n]En la primavera pasada[n]hicieron su primera aparici吋n.[n][w][e]

[msg TV_NEWS_0906_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]Una enorme popularidad, 夷eh?[n]Deber胤amos tener cuidado[n]de que no se nos suba a la cabeza.[n][w][e]

[msg TV_NEWS_0907_000_00 [Entrevistadora]]
[s]夷Podr胤as contarnos m茨s sobre[n]el grupo de investigaci吋n[n]de los Ladrones Fantasma?[n][w][e]

[msg TV_NEWS_0907_050_00 [Universitario entrevistado]]
[s]夷En serio? Me da un poco[n]de verg鵜enza...[n][w][e]
[s]Antes era un club de misterio,[n]pero empezamos a investigarlos[n]cuando la cosa se puso interesante.[n][w][e]

[msg TV_NEWS_0907_100_00 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1043 65535 0][f 4 25 1 65535 0 0]斡夷Qu姻?! 夷Intentan descubrir[n]qui姻nes somos?[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 25 1 65535 0 0]夷Hablan de los Ladrones Fantasma[n]mientras comen en la universidad?[n]Uf... menudo susto.[n][w][e]

[msg TV_NEWS_0908_000_00 [Presentador desenfadado]]
[s]Ahora daremos paso al informe[n]sobre Haw茨i, en Estados Unidos.[n][w][e]
[s]Todos conocemos la estatua del rey[n]Kamehameha. 斡Lo que no sab胤amos[n]es que el modelo no fue 姻l![n][w][e]
[s]En realidad fue un oficial del rey[n]Kalakaua. Lo escogieron por guapo,[n]pero no se parec胤a nada al rey.[n][w][e]

[msg TV_NEWS_0908_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]Seguro que yo tambi姻n estar姻[n]para mojar pan cuando sea humano.[n][w][e]

[msg TV_NEWS_0909_000_00 [Presentador de telediario]]
[s]Se ha confirmado[n]que Mitchell Jackson[n]actuar茨 de nuevo en Jap吋n.[n][w][e]
[s]Jackson es mundialmente conocido.[n]Esta ser茨 su 17.鮎 actuaci吋n[n]en Jap吋n.[n][w][e]
[s]Le preguntamos por su comida[n]favorita y nos dijo que el sushi[n]con una sonrisa de oreja a oreja.[n][w][e]

[msg TV_NEWS_0909_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]Anda, igual que yo.[n]斡Tiene buen gusto![n][w][e]

[msg TV_NEWS_0910_000_00 [Anuncio]]
[s]斡Mam茨, qu姻 buena pinta[n]tiene esta naranja![n][w][e]
[s]斡No, no! No soy una fruta,[n]pero puedes disfrutar[n]de estos maravillosos precios.[n][w][e]
[s]斡Quince ochenta! 斡Quince ochenta![n]Con KJ Mobile,[n]solo son 1580 al mes.[n][w][e]
[s]斡La vida es m茨s f茨cil[n]cuando contratas internet[n]con KJ Mobile![n][w][e]

[msg TV_NEWS_0911_000_00 [Presentador de telediario]]
[s]Debido a la creciente popularidad[n]de los Ladrones Fantasma,[n]la econom胤a de Jap吋n ha...[n][w][e]
[s]Las grandes compa隠胤as est茨n[n]creando productos y eventos[n]basados en los Ladrones Fantasma...[n][w][e]
[s]Ciertas empresas obtienen beneficio[n]de las promociones y otras dicen[n]que deber胤a estar controlado, y...[n][w][e]

[msg TV_NEWS_0911_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0][f 4 25 1 65535 0 0]Es una pena que no veamos[n]nada de ese dinero.[n][w][e]

[msg TV_NEWS_0912_000_00 [Presentador de telediario]]
[s]Cada vez m茨s competidores[n]venden productos relacionados[n]con los Ladrones Fantasma.[n][w][e]
[s]Pel胤culas, series de televisi吋n...,[n]y no parece que esta fiebre[n]vaya a disminuir.[n][w][e]
[s]La econom胤a est茨 en recesi吋n, por[n]lo que esto podr胤a ser una ayuda.[n][w][e]

[msg TV_NEWS_0912_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]夷Hay gente sacando pasta gracias[n]a nosotros? 夷Y nuestra parte?[n][w][e]

[msg TV_SHOUGI_0913_000_00 [Entrevistadora]]
[s]Tras el devastador pe吋n a 6-4,[n]hemos parado a comer algo.[n][w][e]
[s]Acabamos de volver, pero...[n]Tiene claro que va a rendirse[n]sin hacer ni un solo movimiento.[n][w][e]

[msg TV_SHOUGI_0913_100_00 [Jugador profesional de shogi]]
[s]La verdad es que me sorprende.[n][w][e]
[s]Se habr茨 dado cuenta de que ha[n]perdido la partida mientras com胤a.[n][w][e]

[msg TV_SHOUGI_0913_200_00 [Entrevistadora]]
[s]Han comido curry, al parecer.[n]Por su estado de 茨nimo,[n]ha tenido que costarle tragarlo...[n][w][e]

[msg TV_NEWS_0914_000_00 [Presentador de telediario]]
[s]Los elogios a los Ladrones[n]Fantasma parecen no tener fin.[n][w][e]
[s]Los Ladrones Fantasma de Corazones[n]se han hecho con el apoyo masivo[n]de personas de todas las edades.[n][w][e]
[s]夷A qu姻 se debe su atractivo?[n]Les hemos preguntado su opini吋n[n]a los ciudadanos.[n][w][e]

[msg TV_NEWS_0914_100_00]
[s]Parece que la popularidad de los[n]Ladrones Fantasma sigue creciendo.[n][w][e]

[msg TV_NEWS_0915_000_00 [Presentador de telediario]]
[s]Han roto las ventanas de la central[n]de Okumura Foods dos d胤as seguidos.[n][w][e]
[s]La polic胤a cree que es obra[n]de un 雨nico v茨ndalo,[n]y est茨 investigando el asunto.[n][w][e]
[s]Okumura Foods ha emitido[n]un comunicado afirmando[n]desconocer qui姻n ha podido ser.[n][w][e]

[msg TV_NEWS_0915_100_00]
[s]Parece que la polic胤a est茨[n]investigando a Okumura Foods.[n][w][e]

[msg TV_NEWS_0916_000_00 [Presentador de telediario]]
[s]Esto es un duro golpe[n]para Okumura Foods, conocida[n]por Big Bang Burger.[n][w][e]
[s]Los antiguos empleados de Okumura[n]Foods han comenzado a alzar[n]la voz en se隠al de protesta.[n][w][e]
[s]Entre sus quejas se incluyen[n]las horas extra no remuneradas y[n]problemas de salud por estr姻s.[n][w][e]
[s]Se han vivido momentos de tensi吋n[n]frente a la sede durante disputas[n]entre manifestantes y polic胤as.[n][w][e]
[s]Se sospecha que estas protestas[n]est茨n relacionadas con los actos[n]vand茨licos de hace unos d胤as.[n][w][e]

[msg TV_NEWS_0916_100_00]
[s]Parece que hay un mont吋n de gente[n]protestando en Okumura Foods.[n][w][e]

[msg TV_NEWS_0917_000_00 [Presentador de telediario]]
[s]Tenemos novedades sobre[n]las protestas de los antiguos[n]empleados de Okumura Foods.[n][w][e]
[s]Tras los primeros informes sobre[n]las protestas, muchos han[n]secundado los hechos en internet.[n][w][e]
[s]Piden que el CEO, Kunikazu[n]Okumura, se haga responsable.[n][w][e]

[msg TV_NEWS_0917_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Todos esos trabajadores han sufrido[n]lo suyo. Deben estar desesperados.[n][w][e]

[msg TV_NEWS_0918_000_00 [Presentador de telediario]]
[s]A continuaci吋n, las acusaciones[n]de pr茨cticas poco 姻ticas[n]en Okumura Foods.[n][w][e]
[s]La empresa ha guardado silencio[n]ante las preguntas de los medios.[n][w][e]
[s]Parece que este interrogatorio[n]continuar茨 hasta que se den[n]las explicaciones pertinentes.[n][w][e]

[msg TV_NEWS_0918_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Tenemos que hacer algo antes de que[n]Haru acabe metida en este l胤o.[n][w][e]

[msg TV_NEWS_0919_000_00 [Presentador de telediario]]
[s]A continuaci吋n, las acusaciones[n]de pr茨cticas poco 姻ticas[n]en Okumura Foods.[n][w][e]
[s]Se ha confirmado que[n]las duras condiciones de trabajo[n]eran la norma en Okumura Foods.[n][w][e]
[s]Las crecientes cr胤ticas hacia[n]el presidente Okumura han[n]ensuciado la imagen de la empresa.[n][w][e]

[msg TV_NEWS_0919_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]斡Nuestro objetivo es Okumura![n]斡Dejar茨n de pedirnos que actuemos[n]cuando nos ocupemos de 姻l![n][w][e]

[msg TV_NEWS_0920_000_00 [Presentador de telediario]]
[s]Ha sido arrestado a un hombre[n]tras publicar una amenaza[n]de bomba en internet.[n][w][e]
[s]El detenido declar吋 que afirm吋 ser[n]un Ladr吋n Fantasma en internet[n]para llamar la atenci吋n.[n][w][e]
[s]La polic胤a advierte que hay[n]delincuentes que usan el nombre[n]de los Ladrones Fantasma.[n][w][e]

[msg TV_NEWS_0920_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0][f 4 25 1 65535 0 0]Ojal茨 la gente dejara de hacer[n]esas chorradas. Supongo que[n]es lo malo de la fama.[n][w][e]

[msg TV_NEWS_0921_000_00 [Presentador de telediario]]
[s]Hoy el especial trata de pr茨cticas[n]empresariales poco 姻ticas.[n][w][e]
[s]Okumura Foods ha recibido cr胤ticas[n]feroces por c吋mo han empeorado[n]sus condiciones de trabajo.[n][w][e]
[s]Se cree que hay muchos m茨s[n]empleados afectados de los que[n]se tiene constancia.[n][w][e]
[s]Hay quien dice que, dado que[n]el gobierno no hace nada, hay que[n]confiar en los Ladrones Fantasma.[n][w][e]

[msg TV_NEWS_0921_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Ese CEO es un delincuente...[n]Y somos los 雨nicos que[n]podemos detenerlo.[n][w][e]

[msg TV_QUIZ_0922_000_00 [Presentador de concurso]]
[s]La Ley de normas laborales recoge[n]los derechos de los trabajadores y[n]las penas por violar estas normas.[n][w][e]
[s]夷Cu茨l de estos es el castigo por[n]trabajo forzoso, la m茨s grave[n]de las ofensas?[n][w][e]
[s]A) Diez a隠os de prisi吋n.[n]B) Multa de 20 millones de yenes.[n][w][e]

[sel SEL_QUIZ_0922 top]
[s]Diez a隠os de prisi吋n.[e]
[s]Multa de 20 millones de yenes.[e]

[msg TV_QUIZ_0922_100_00 [Presentador de concurso]]
[s]La respuesta correcta es... 斡la A![n]斡Un empresario inhumano recibe[n]diez a隠os de prisi吋n![n][w][e]

[msg TV_QUIZ_0922_200_00 [Abogado]]
[s]Se acusa a Okumura Foods de largas[n]jornadas laborales y no pagar horas[n]extra, no de trabajo forzoso.[n][w][e]
[s]Dicen que el castigo ser茨 demasiado[n]indulgente: seis meses de c茨rcel o[n]trescientos mil yenes de multa.[n][w][e]

[msg TV_MORGANA_0922_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]斡El castigo es muy flojo[n]en las dos respuestas! Por eso[n]la gente acude a nosotros.[n][w][e]

[msg TV_MORGANA_0922_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Da igual que no acertaras.[n]El castigo es muy flojo. Por eso[n]la gente acude a nosotros.[n][w][e]

[msg TV_NEWS_0923_000_00 [Presentador de telediario]]
[s]Otro delincuente ha intentado sacar[n]provecho de la popularidad[n]de los Ladrones Fantasma.[n][w][e]
[s]Un hombre de Tokio ha sido[n]detenido por estafa.[n][w][e]
[s]Les ped胤a dinero a las v胤ctimas[n]y les promet胤a que podr胤an conocer[n]a [f 4 28].[n][w][e]

[msg TV_NEWS_0923_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Hay personas malas de verdad.[n]Me gustar胤a darles una lecci吋n[n]alg雨n d胤a, pero...  [n][w][e]

[msg TV_NEWS_0924_000_00 [Presentador de telediario]]
[s]Hoy, en la serie sobre la falta de[n]姻tica en el trabajo, hablaremos[n]de las condiciones laborales.[n][w][e]
[s]Acompa隠amos a un estudiante[n]que trabaja a tiempo parcial[n]en una gran empresa...[n][w][e]
[s]Se trata de j吋venes con un gran[n]sentido de la responsabilidad[n]que luchan por salir adelante.[n][w][e]

[msg TV_NEWS_0924_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1043 65535 0][f 4 25 1 65535 0 0]Parece que Okumura Foods no es la[n]雨nica empresa que lo hace...[n][w][e]

[msg TV_NEWS_0926_000_00 [Presentador de telediario]]
[s]Okumura Foods sigue recibiendo[n]cr胤ticas por el mal trato[n]hacia sus empleados.[n][w][e]
[s]Los propios trabajadores, dando[n]muestras evidentes de cansancio,[n]han tenido que lidiar con las quejas.[n][w][e]
[s]El presidente Okumura a雨n no ha[n]comparecido p雨blicamente, pero[n]algunos ya piden indemnizaciones.[n][w][e]

[msg TV_NEWS_0926_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]As胤 que trata de esconderse, 夷no?[n]Hay que apresurarse y terminar[n]cuanto antes.[n][w][e]

[msg TV_NEWS_0927_000_00 [Presentador de telediario]]
[s]Ahora hablaremos de los cr胤menes[n]cometidos por Okumura Foods[n]contra sus trabajadores.[n][w][e]
[s]Aquellos que se consideran v胤ctimas[n]han creado una asociaci吋n y se han[n]reunido para tratar el tema.[n][w][e]
[s]Parece que han decidido[n]no descansar hasta[n]que se haga justicia.[n][w][e]

[msg TV_NEWS_0927_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]As胤 que han unido sus fuerzas.[n]Es cierto que cuesta conseguir[n]algo tan dif胤cil si est茨s solo.[n][w][e]

[msg TV_MACHI_0928_000_00 [Periodista]]
[s]En 或斡Exploradores de la ciudad!位,[n]visitamos un lugar muy espiritual[n]de Tokio, el [clr 2]Santuario Meiji[clr 27].[n][w][e]
[s]La gente viene a admirar[n]la naturaleza, y algunos[n]a rezar para encontrar el amor.[n][w][e]

[msg TV_MACHI_0928_100_00 [Especialista]]
[s]Tambi姻n es el santuario m茨s popular[n]en A隠o Nuevo y un buen sitio para[n]quedar cerca de la calle Takenoko.[n][w][e]

[msg TV_QUIZ_0929_000_00 [Presentador de concurso]]
[s]La era de la informaci吋n esconde[n]trampas. 斡Quiz茨 haya cometido un[n]delito de informaci吋n y no lo sepa![n][w][e]
[s]Piense en los siguientes casos:[n]A) Divulgar los delitos de alguien.[n]B) Insultar por internet.[n][w][e]
[s]夷Cu茨l de estos actos[n]se considera difamaci吋n?[n]斡Juzguen ustedes mismos![n][w][e]

[sel SEL_QUIZ_0929 top]
[s]Divulgar los delitos de alguien.[e]
[s]Insultar por internet.[e]

[msg TV_QUIZ_0929_100_00 [Presentador de concurso]]
[s]La respuesta correcta es... 斡la A![n]斡Es delito divulgar los[n]antecedentes de alguien![n][w][e]

[msg TV_QUIZ_0929_200_00 [Abogado]]
[s]Decir p雨blicamente algo[n]que da隠a la reputaci吋n de alguien[n]es difamaci吋n, aunque sea cierto.[n][w][e]
[s]Insultar no se suele considerar[n]difamaci吋n, y si fuera el caso,[n]se quedar胤a en libelo en internet.[n][w][e]

[msg TV_MORGANA_0929_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]Anda, has acertado. Entonces,[n]los que crean rumores sobre alguien[n]son culpables de difamaci吋n.[n][w][e]

[msg TV_MORGANA_0929_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Vaya, no has acertado. Bueno,[n]tanto difundir rumores como[n]que te insulten me parece mal.[n][w][e]

[msg TV_NEWS_0930_000_00 [Presentador de telediario]]
[s]Okumura Foods ha recibido numerosas[n]denuncias debido a sus deplorables[n]condiciones laborales.[n][w][e]
[s]Nuestros reporteros han logrado[n]entrevistar a un antiguo[n]empleado de la compa隠胤a.[n][w][e]
[s]Habl吋 de unas condiciones laborales[n]muy duras en las que los empleados[n]apenas ten胤an libertad.[n][w][e]

[msg TV_NEWS_0930_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Caray, trabajar parece la mar[n]de duro. 夷Qu姻 piensas hacer[n]cuando seas mayor?[n][w][e]

[msg TV_MACHI_1001_000_00 [Periodista]]
[s]Hoy tenemos una edici吋n especial[n]de 或斡Exploradores de la ciudad!位.[n][w][e]
[s]斡En estas emisiones especiales,[n]compartimos productos de[n]edici吋n limitada que est茨n de moda![n][w][e]
[s]斡Hoy hablamos del aroma[n]relajante y terap姻utico[n]de [clr 2]Aroma refrescante[clr 27]![n][w][e]
[s]Es una mezcla especial[n]de ingredientes oto隠ales[n]que est茨 arrasando.[n][w][e]

[msg TV_MACHI_1001_100_00 [Especialista]]
[s]Lo venden en Body Chop, 夷no?[n]Espero que todav胤a quede[n]en el subterr茨neo de Shibuya.[n][w][e]

[msg TV_NEWS_1002_000_00 [Presentador de telediario]]
[s]El oto隠o es sin吋nimo de cosechas,[n]y la del arroz est茨 a la vuelta[n]de la esquina.[n][w][e]
[s]La demanda de las variedades usadas[n]en los mejores locales de sushi[n]de Tokio alcanzar茨 m茨ximos pronto.[n][w][e]

[msg TV_NEWS_1002_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]斡Parece que la cosecha de este[n]a隠o pinta bien! Jo,[n]ahora me apetece sushi.[n][w][e]

[msg TV_DRAMA_1003_000_00 [Detective ingenioso]]
[s]D胤game qu姻 vio. Soy el detective[n]Sakyo Hinoshita de la polic胤a[n]de Tokio.[n][w][e]
[s]Miembro del equipo especial de la[n]secci吋n n雨mero cinco de la divisi吋n[n]contra el crimen organizado.[n][w][e]

[msg TV_DRAMA_1003_100_00 [Testigo material]]
[s]Oh, as胤 que es un poli, 夷no?[n][w][e]

[msg TV_MORGANA_1003 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]夷Qu姻 narices? Es como[n]un trabalenguas. 夷Tiene que decir[n]eso en cada cap胤tulo?[n][w][e]

[msg TV_NEWS_1004_000_00 [Presentador de telediario]]
[s]La gente espera que [f 4 28][n]responda a las acciones[n]de Okumura Foods.[n][w][e]
[s]Su influencia ha cruzado fronteras,[n]y ahora los Ladrones Fantasma[n]son conocidos en todo el globo.[n][w][e]
[s]Incluso hay pa胤ses que han empezado[n]a apostar sobre cu茨l ser茨[n]su pr吋ximo movimiento.[n][w][e]

[msg TV_NEWS_1004_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]Nos conocen hasta en Haw茨i, 夷no?[n]Pues s胤 que nos hemos[n]vuelto famosos.[n][w][e]

[msg TV_NEWS_1005_000_00 [Presentador de telediario]]
[s]A continuaci吋n, les traemos m茨s[n]informaci吋n sobre la locura[n]por los Ladrones Fantasma.[n][w][e]
[s]Son m茨s populares que nunca,[n]y cada vez tienen m茨s fans.[n][w][e]
[s]Sin embargo, algunos se exceden[n]pidiendo que exterminen[n]a todos los malhechores.[n][w][e]

[msg TV_NEWS_1005_100_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Me alegro de que tengamos fans,[n]pero que no sean tan fan茨ticos.[n][w][e]

[msg TV_NEWS_1006_000_00 [Presentador de telediario]]
[s]Ahora hablaremos[n]sobre Okumura Foods.[n][w][e]
[s]Hoy nos centraremos en Kunikazu[n]Okumura, el hombre que ha llevado[n]la empresa a lo que es hoy en d胤a.[n][w][e]
[s]Tiene muchos contactos en[n]diferentes industrias, y se dice[n]que podr胤a meterse en pol胤tica.[n][w][e]

[msg TV_NEWS_1006_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Est茨n hablando del padre de Haru.[n]Parece que es una persona[n]muy influyente...[n][w][e]

[msg TV_WIDESHOW_1007_000_00 [Presentador]]
[s]斡Saludos! 斡La fiebre por los[n]Ladrones Fantasma est茨 en su[n]punto m茨s 茨lgido y crean tendencia![n][w][e]
[s]斡Todo el mundo quiere estar divino[n]y misterioso al mismo tiempo![n]Las chicas se vuelven locas, 夷eh?[n][w][e]

[msg TV_WIDESHOW_1007_100_00 [Panelista]]
[s]Claro. Con veinte a隠os menos, no me[n]importar胤a que un Ladr吋n Fantasma[n]despertara mi coraz吋n... Ja, ja, ja.[n][w][e]

[msg TV_ANIME_1008_000_00 [Narrador]]
[s]斡Por fin reaparece el villano que[n]reuni吋 a los Phoenix Rangers![n][w][e]
[s]斡夷Qu姻 hab胤a en la bandeja de comida[n]que envi吋 a nuestros h姻roes?![n]斡Revivid y luchad, Phoenix Rangers![n][w][e]
[s]En el pr吋ximo episodio...[n]或La molleja a la plancha[n]me chifla, pero es una trampa位.[n][w][e]

[msg TV_NEWS_1009_000_00 [Presentador de telediario]]
[s]Hablamos del presidente de Okumura[n]Foods, que no ha aparecido[n]en p雨blico desde el mes pasado.[n][w][e]
[s]Muchos expresan su descontento[n]y creen que este largo silencio[n]es muestra de su falta de honradez.[n][w][e]
[s]Incluso hay quienes creen[n]que ha huido del pa胤s.[n][w][e]
[s]Sin saber el paradero[n]del se隠or Okumura,[n]es dif胤cil poner fin al esc茨ndalo.[n][w][e]

[msg TV_NEWS_1009_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Solo faltan unos d胤as[n]para que todo acabe.[n][w][e]

[msg TV_NEWS_1010_000_00 [Presentador de telediario]]
[s]Los centros educativos del pa胤s[n]celebraron festivales culturales[n]y deportivos el fin de semana.[n][w][e]
[s]Las exhibiciones reflejaban los[n]deseos de los estudiantes, y muchos[n]se llevaron un grato recuerdo.[n][w][e]

[msg TV_NEWS_1010_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Los festivales parecen divertidos.[n]夷Tu instituto no hace nada[n]por el estilo?[n][w][e]

[msg TV_NEWS_1011_000_00 [Presentador de telediario]]
[s]Volvemos a lo sucedido[n]durante la rueda de prensa[n]del presidente de Okumura Foods.[n][w][e]
[s]El presidente Okumura[n]se ha desmayado durante el evento[n]y ha sido trasladado al hospital.[n][w][e]
[s]Por desgracia, nos acaban[n]de informar de su fallecimiento.[n][w][e]

[msg TV_NEWS_1011_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]No me puedo creer que haya muerto...[n][w][e]

[msg TV_NEWS_1012_000_00 [Presentador de telediario]]
[s]A continuaci吋n, les traemos m茨s[n]informaci吋n sobre el fallecimiento[n]anoche del se隠or Okumura.[n][w][e]
[s]La polic胤a ha estado investigando[n]su casa a lo largo del d胤a de hoy,[n]as胤 como otros lugares de inter姻s.[n][w][e]
[s]Intentan esclarecer si fue un[n]delito o un accidente, pero se[n]desconocen las causas de la muerte.[n][w][e]

[msg TV_NEWS_1012_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0][f 4 25 1 65535 0 0]Parece que la polic胤a ha ido[n]a tu instituto... 夷Qu姻 piensan hacer?[n][w][e]

[msg TV_NEWS_1013_000_00 [Presentador de telediario]]
[s]Tras la repentina muerte de su[n]presidente, Okumura Foods trata[n]ahora de capear el temporal.[n][w][e]
[s]Sus acciones han bajado[n]y se espera que haya una[n]reestructuraci吋n de la directiva.[n][w][e]
[s]La gente espera ver c吋mo se[n]solucionan los temas que el se隠or[n]Okumura trat吋 ante la prensa.[n][w][e]

[msg TV_NEWS_1013_100_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]夷Qu姻 le pasar茨 a la compa隠胤a[n]de Haru? Me preocupa bastante.[n][w][e]

[msg TV_NEWS_1014_000_00 [Presentador de telediario]]
[s]Con respecto al fallecimiento[n]del CEO de Okumura Foods[n]la noche del d胤a 11...[n][w][e]
[s]Es muy probable que[n][f 4 28] estuvieran[n]envueltos en el incidente.[n][w][e]
[s]Algunos informes policiales[n]apuntan a que fue un homicidio.[n][w][e]

[msg TV_NEWS_1014_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Nos culpan a nosotros. Qu姻 r茨pido[n]cambia de parecer la gente...[n][w][e]

[msg TV_NEWS_1015_000_00 [Presentador de telediario]]
[s]Se han disparado las cr胤ticas hacia[n]los Ladrones Fantasma.[n][w][e]
[s]Tras la emisi吋n de la rueda[n]de prensa, la gente ha empezado[n]a llamarlos criminales y asesinos.[n][w][e]
[s]A pie de calle, la gente no puede[n]evitar mostrar preocupaci吋n[n]e incluso miedo.[n][w][e]

[msg TV_NEWS_1015_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]斡Mierda! 夷Por qu姻...?[n]斡夷Por qu姻 nos odian de repente?![n][w][e]

[msg TV_NEWS_1016_000_00 [Presentador de telediario]]
[s]El 16 de octubre, D胤a Mundial de la[n]Alimentaci吋n, se celebran varios[n]eventos relacionados con la comida.[n][w][e]
[s]Big Bang Burger hab胤a organizado[n]un acontecimiento ben姻fico...[n][w][e]
[s]Sin embargo, se ha cancelado[n]por culpa de los[n]acontecimientos recientes.[n][w][e]

[msg TV_NEWS_1016_100_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]Haru tiene que estar pas茨ndolo[n]fatal. Estoy preocupado por ella.[n][w][e]

[msg TV_DRAMA_1017_000_00 [Detective ingenioso]]
[s]Ja, ja... de acuerdo.[n]斡A ver si me das![n][w][e]

[msg TV_DRAMA_1017_050_00 [Culpable]]
[s]No es de mentira,[n]斡es un rev吋lver de verdad![n][w][e]

[msg TV_DRAMA_1017_100_00 [Detective ingenioso]]
[s]斡Espera! 斡N-no dispares![n][w][e]

[msg TV_DRAMA_1017_150_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]夷Es valiente o no?[n][w][e]

[msg TV_NEWS_1018_000_00 [Presentador de telediario]]
[s]Un hombre que aseguraba pertenecer[n]a los Ladrones Fantasma entr吋[n]con un objeto afilado a una tienda...[n][w][e]
[s]Se llev吋 varios cientos de miles[n]de yenes y huy吋. La polic胤a pudo[n]arrestarlo media hora despu姻s.[n][w][e]
[s]Seg雨n la polic胤a, el hombre estaba[n]iracundo y no guardaba relaci吋n[n]con los Ladrones Fantasma.[n][w][e]

[msg TV_NEWS_1018_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]斡Pues claro que no![n]斡Lo que faltaba![n][w][e]

[msg TV_NEWS_1019_000_00 [Presentador desenfadado]]
[s]斡Repaso de moda! Hoy hablaremos de[n]una de las prendas m茨s importantes[n]del oto隠o, el jersey.[n][w][e]
[s]夷Sab姻is esas pelotillas[n]que aparecen con el uso? 斡Pues[n]hay una buena forma de quitarlas![n][w][e]
[s]Con una esponja h雨meda, frotadlas[n]con cuidado para eliminarlas[n]sin da隠ar vuestro jersey.[n][w][e]

[msg TV_NEWS_1019_100_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Nosotros no tenemos tiempo[n]para preocuparnos por la moda.[n][w][e]

[msg TV_NEWS_1020_000_00 [Presentador de telediario]]
[s]La popularidad del gobierno[n]est茨 por debajo del 10 %,[n]la m茨s baja desde su llegada.[n][w][e]
[s]Parece que se debe a la mala[n]gesti吋n del asunto de [f 4 28].[n][w][e]
[s]Adem茨s, la muerte del se隠or Okumura[n]tambi姻n ha pasado factura.[n][w][e]

[msg TV_NEWS_1020_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Creo que empatizo con ellos.[n]Nuestra popularidad tambi姻n[n]ha ca胤do en picado...[n][w][e]

[msg TV_NEWS_1021_000_00 [Presentador de telediario]]
[s]Les traemos m茨s informaci吋n[n]sobre el fallecimiento[n]de Kunikazu Okumura.[n][w][e]
[s]Parece que las autoridades se[n]preparan para arrestar al culpable.[n][w][e]
[s]Hemos o胤do que est茨n dispuestos[n]a emplear m姻todos poco ortodoxos.[n]Seguiremos informando.[n][w][e]

[msg TV_NEWS_1021_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Las cosas no van nada bien.[n]No bajes la guardia[n]ni un momento.[n][w][e]

[msg TV_NEWS_1022_000_00 [Presentador de telediario]]
[s]La polic胤a sigue investigando[n]y est茨 centrada en detener[n]a los Ladrones Fantasma.[n][w][e]
[s]Se dedicaron a investigar a fondo[n]un instituto durante el d胤a de ayer.[n][w][e]
[s]Sin embargo, no queda claro[n]si han podido encontrar pistas, lo[n]que provoca temor en la ciudadan胤a.[n][w][e]
[s]Las cr胤ticas al gobierno contin雨an[n]por dejar que un grupo tan[n]peligroso campe a sus anchas...[n][w][e]

[msg TV_NEWS_1022_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1026 65535 0][f 4 25 1 65535 0 0]斡夷Creen que somos peligrosos?![n]夷Se puede saber qu姻 hemos hecho?[n][w][e]

[msg TV_NEWS_1023_000_00 [Presentador de telediario]]
[s]El fallecimiento del se隠or Okumura[n]hace diez d胤as ha influido[n]claramente en bolsa.[n][w][e]
[s]Las aseguradoras han visto c吋mo[n]sus acciones se disparan ante[n]el clima de inseguridad p雨blica.[n][w][e]
[s]En cambio, el mercado de valores y[n]las compa隠胤as relacionadas con los[n]Ladrones Fantasma van a la baja.[n][w][e]

[msg TV_NEWS_1023_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Nunca imagin姻 que[n]la econom胤a ir胤a a peor...[n]Pero 斡no es nuestra culpa![n][w][e]

[msg TV_NEWS_1024_000_00 [Presentador de telediario]]
[s]A continuaci吋n, noticias sobre[n][f 4 28].[n][w][e]
[s]Hemos hecho una encuesta sobre[n]los Ladrones Fantasma, objetivo[n]de numerosas cr胤ticas.[n][w][e]
[s]Cerca del 90 % de los entrevistados[n]ha dicho que no los apoya.[n][w][e]

[msg TV_NEWS_1024_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Ahora tenemos a todo el mundo[n]en contra... La cosa no pinta bien.[n][w][e]

[msg TV_NEWS_1025_000_00 [Presentador de telediario]]
[s]El primer ministro a雨n no ha podido[n]idear un plan efectivo contra[n]los Ladrones Fantasma.[n][w][e]
[s]Las cr胤ticas le llegan[n]no solo desde la oposici吋n,[n]sino tambi姻n de su propio partido.[n][w][e]
[s]La posible disoluci吋n del partido[n]en el gobierno supondr胤a[n]nuevas elecciones.[n][w][e]

[msg TV_NEWS_1025_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]No s姻 mucho de pol胤tica, pero[n]parece que el gobierno[n]se ha metido en un buen l胤o.[n][w][e]

[msg TV_MACHI_1026_000_00 [Periodista]]
[s]En 或斡Exploradores de la ciudad!位,[n]斡nos encontramos en [clr 2]Shibuya[clr 27], en[n]el famoso bufet del hotel Wilton![n][w][e]
[s]斡Es dif胤cil elegir, porque toda la[n]comida est茨 buen胤sima! 斡Perfecto[n]para darte un capricho en Shibuya![n][w][e]

[msg TV_MACHI_1026_100_00 [Especialista]]
[s]Muchos famosos y peces gordos[n]de la pol胤tica van all胤[n]a comer en secreto.[n][w][e]
[s]El que todo el mundo dice que[n]ser茨 el pr吋ximo primer ministro[n]tambi姻n va. 斡Yo quiero![n][w][e]

[msg TV_NEWS_1027_000_00 [Presentador de telediario]]
[s]El tema de hoy se centra[n]en los esfuerzos para descubrir[n]a los Ladrones Fantasma.[n][w][e]
[s]Para ello, contamos con la ayuda[n]de un experto analista.[n][w][e]
[s]Afirma que tendr胤an entre veinte[n]y treinta a隠os, o incluso[n]cuarenta o cincuenta.[n][w][e]

[msg TV_NEWS_1027_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0][f 4 25 1 65535 0 0]Pues no aciertan ni de lejos.[n]夷En serio era un experto?[n][w][e]

[msg TV_NEWS_1028_000_00 [Presentador de telediario]]
[s]Halloween est茨 al caer, y con 姻l[n]llegan los eventos de disfraces[n]por toda la ciudad.[n][w][e]
[s]Muchas compa隠胤as hab胤an fabricado[n]art胤culos de los Ladrones Fantasma[n]para aprovechar el tir吋n...[n][w][e]
[s]in embargo, el repentino desafecto[n]de la opini吋n p雨blica por el grupo[n]ha hecho que no se vendan.[n][w][e]

[msg TV_NEWS_1028_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Halloween suena divertido, pero[n]despu姻s de lo que han dicho,[n]no me apetece celebrarlo...[n][w][e]

[msg TV_ANIME_1029_000_00 [Narrador]]
[s]威guila Roja est茨 destrozado[n]por la sorprendente traici吋n[n]de Halc吋n Negro.[n][w][e]
[s]Pero 斡姻l no es el 雨nico traidor![n]斡Revivid y luchad, Phoenix Rangers![n][w][e]
[s]En el pr吋ximo episodio...[n]或夷Otra vez t雨, Halc吋n?位.[n][w][e]

[msg TV_NEWS_1030_000_00 [Presentador de telediario]]
[s]Ha habido otra serie[n]de episodios de descontrol.[n][w][e]
[s]Se cree que han sido obra[n]de los Ladrones Fantasma.[n][w][e]
[s]La ciudadan胤a sigue horrorizada[n]ante la crueldad de los cr胤menes[n]que est茨n cometiendo.[n][w][e]

[msg TV_NEWS_1030_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]斡Jol胤n! 夷Qu姻 est茨 pasando?[n]斡Si no tenemos culpa de nada![n][w][e]

[msg TV_NEWS_1031_000_00 [Presentador de telediario]]
[s]Y ahora, un reportaje sobre [f 4 28][n]y la cuantiosa[n]recompensa que se paga por ellos.[n][w][e]
[s]Las aseguradoras no dan abasto[n]debido a ciudadanos desesperados[n]que buscan protecci吋n.[n][w][e]
[s]Esto ha sucedido muy pocas veces[n]a lo largo de la historia, y el[n]terror entre la gente es evidente.[n][w][e]

[msg TV_NEWS_1031_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Han puesto recompensa a nuestras[n]cabezas, as胤 que no queda otra: hay[n]que descubrir qui姻n lo ha hecho.[n][w][e]

[msg TV_NEWS_1101_000_00 [Presentador de telediario]]
[s]Es posible que el clamor contra[n]los Ladrones Fantasma[n]haya llegado a la pol胤tica.[n][w][e]
[s]La popularidad del gobierno[n]ha tocado fondo por su p姻sima[n]gesti吋n sobre el grupo criminal.[n][w][e]
[s]El se隠or Shido abandera[n]las cr胤ticas y muchos se plantean[n]abandonar el partido del gobierno.[n][w][e]
[s]Si el Partido Liberal de la[n]Coprosperidad se disuelve, pronto[n]habr茨 elecciones anticipadas.[n][w][e]

[msg TV_NEWS_1101_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0][f 4 25 1 65535 0 0]夷Su partido se desmorona por culpa[n]nuestra? No entiendo la pol胤tica.[n][w][e]

[msg TV_NEWS_1102_000_00 [Presentador de telediario]]
[s]Y seguimos con pol胤tica.[n][w][e]
[s]Se especula que Masayoshi Shido[n]est茨 organizando un nuevo partido[n]debido a los apoyos recibidos.[n][w][e]
[s]Si se adelantan las elecciones,[n]este nuevo grupo ser茨[n]el centro de atenci吋n.[n][w][e]

[msg TV_NEWS_1102_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]Parece que habr茨 elecciones.[n]Aunque todav胤a no tienes[n]edad para votar, 夷no?[n][w][e]

[msg TV_NEWS_1103_000_00 [Presentador de telediario]]
[s]La polic胤a ha ofrecido la mayor[n]recompensa nunca vista por atrapar[n]a los Ladrones Fantasma.[n][w][e]
[s]Sin embargo, no se han dado[n]demasiadas pistas puesto que la[n]gente teme posibles represalias.[n][w][e]
[s]La polic胤a est茨 considerando[n]aumentar la recompensa y[n]contin雨a solicitando informaci吋n.[n][w][e]

[msg TV_NEWS_1103_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1161 65535 0][f 4 25 1 65535 0 0]Esto va de mal en peor...[n]Utilizar茨n cualquier m姻todo[n]posible para atraparnos.[n][w][e]

[msg TV_WIDESHOW_1104_000_00 [Presentador]]
[s]斡Saludos! Hoy analizaremos[n]al Pr胤ncipe Detective, Goro Akechi.[n]斡Es la comidilla de todos![n][w][e]
[s]Hablaremos de su vida privada[n]y de las mujeres que le gustan.[n]斡Prometemos no especular mucho![n][w][e]

[msg TV_WIDESHOW_1104_100_00 [Panelista]]
[s]Muchas lo consideran el hombre[n]ideal, 夷verdad? Es m茨s[n]popular que muchos famosos.[n][w][e]

[msg TV_NEWS_1105_000_00 [Presentador de telediario]]
[s]El reino del terror de[n]los Ladrones Fantasma contin雨a.[n][w][e]
[s]Se dice que est茨n tras los[n]recientes episodios de descontrol,[n]y parece que estos no remiten.[n][w][e]
[s]Aunque la polic胤a asegura haber hecho[n]avances en la investigaci吋n, muchas son[n]las voces que lo ponen en duda.[n][w][e]

[msg TV_NEWS_1105_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]No solo nos concierne a nosotros...[n]Tenemos que evitar que haya[n]m茨s desconexiones mentales.[n][w][e]

[msg TV_NEWS_1107_000_00 [Presentador de telediario]]
[s]Parece que las elecciones[n]se llevar茨n a cabo antes[n]de final de a隠o.[n][w][e]
[s]Masayoshi Shido ha abandonado[n]oficialmente su actual partido.[n][w][e]
[s]Gracias al apoyo de otros miembros,[n]el Partido Liberal de la[n]Coprosperidad tendr茨 que separarse.[n][w][e]
[s]Si la moci吋n de censura prospera,[n]la C茨mara de Representantes[n]acabar茨 disuelta.[n][w][e]

[msg TV_NEWS_1107_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]As胤 que es probable que la C茨mara[n]de Representantes se disuelva...[n][w][e]

[msg TV_NEWS_1107_200_00 [Morgana]]
[s][bup 0 3 3 0 0][vp 8 2 1 0 65535 0]...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 25 1 65535 0 0]Tambi姻n era nuestro prop吋sito[n]despu姻s de llevar a cabo el plan...[n][w][e]

[msg TV_SHOUGI_1108_000_00 [Entrevistadora]]
[s]Los jugadores de shogi suelen estar[n]en su mejor momento, entre veinte[n]y treinta a隠os. 夷T雨 qu姻 opinas?[n][w][e]

[msg TV_SHOUGI_1108_100_00 [Jugador profesional de shogi]]
[s]Es cierto que ahora no leo[n]el tablero tan r茨pido como[n]cuando ten胤a veinte o as胤.[n][w][e]
[s]Sin duda, para los j吋venes[n]es m茨s f茨cil ganar en[n]una partida r茨pida de shogi.[n][w][e]
[s]Bueno, aunque[n]hay una excepci吋n...[n][w][e]

[msg TV_NEWS_1109_000_00 [Presentador de telediario]]
[s]La popularidad del gobierno toca[n]fondo tras no poder atrapar[n]a los Ladrones Fantasma.[n][w][e]
[s]El primer ministro ha vuelto a[n]asegurar que la seguridad de los[n]ciudadanos es primordial.[n][w][e]
[s]Sin embargo, muy pocos lo apoyan.[n]El partido gobernante lo tiene muy[n]complicado en futuras elecciones.[n][w][e]

[msg TV_NEWS_1109_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Su popularidad est茨 por los[n]suelos... Aunque nosotros no[n]estamos para tirar cohetes.[n][w][e]

[msg TV_QUIZ_1110_000_00 [Presentador de concurso]]
[s]La siguiente pregunta es f茨cil.[n]夷Qui姻n se considera que tiene[n]m茨s poder en este pa胤s?[n][w][e]
[s]A) El primer ministro.[n]B) Usted delante de la tele.[n][w][e]
[s]Si acaba de incorporarse, 斡le damos[n]la bienvenida a 或Variedad legal位![n]Y bien, 夷cu茨l es su respuesta?[n][w][e]

[sel SEL_QUIZ_1110 top]
[s]El primer ministro.[e]
[s]Yo delante de la tele.[e]

[msg TV_QUIZ_1110_100_00 [Presentador de concurso]]
[s]La respuesta correcta es... 斡la B![n]斡Gente como usted y como yo somos[n]los que gobernamos este pa胤s![n][w][e]

[msg TV_QUIZ_1110_200_00 [Abogado]]
[s]El art胤culo 1 de la Constituci吋n[n]establece que 或el pueblo japon姻s[n]es soberano位. 斡El poder es suyo![n][w][e]
[s]Quiz茨 haya gente en desacuerdo,[n]pero yo creo que cada uno tenemos[n]el poder de cambiar la sociedad.[n][w][e]

[msg TV_MORGANA_1110_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Una pregunta trampa, 夷eh? Bueno,[n]或primer ministro位 parece[n]un t胤tulo algo presuntuoso.[n][w][e]

[msg TV_MORGANA_1110_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]斡Has acertado![n]Entonces, 夷qu姻 piensas?[n]夷Cuento como ciudadano?[n][w][e]

[msg TV_NEWS_1111_000_00 [Presentador de telediario]]
[s]La C茨mara de Representantes[n]se ha disuelto oficialmente[n]hoy mismo.[n][w][e]
[s]El nuevo partido del se隠or Shido,[n]或Futuro Unido位, ha presentado[n]una moci吋n de censura.[n][w][e]
[s]Como se ha aprobado por mayor胤a,[n]se ha disuelto la c茨mara.[n][w][e]
[s]Se espera que las elecciones sean[n]antes de fin de a隠o, cuando todos[n]los partidos est姻n preparados.[n][w][e]

[msg TV_NEWS_1111_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Pues parece que habr茨[n]elecciones. Me pregunto[n]qui姻n ganar茨.[n][w][e]

[msg TV_ANIME_1112_000_00 [Narrador]]
[s]El objetivo del malvado Daimaho[n]no era otro que erradicar[n]a todas las aves de la Tierra.[n][w][e]
[s]斡夷C吋mo saldr茨 de esta[n]Feathermen ahora que est茨n[n]infectados con la gripe aviar?![n][w][e]
[s]En el pr吋ximo episodio...[n]或Alas rotas位.[n][w][e]

[msg TV_NEWS_1114_000_00 [Presentador de telediario]]
[s]A continuaci吋n, hablaremos sobre[n]el incidente relacionado con [f 4 28].[n][w][e]
[s]Hemos recibido mucha informaci吋n,[n]pero no hemos podido encontrar[n]pistas nuevas.[n][w][e]
[s]La polic胤a est茨 considerando[n]retirar la recompensa y continuar[n]con su investigaci吋n.[n][w][e]

[msg TV_NEWS_1114_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]斡Nos tratan como si fu姻ramos[n]criminales peligrosos![n]No me gusta ni un pelo.[n][w][e]

[msg TV_NEWS_1115_000_00 [Presentador de telediario]]
[s]El clima fr胤o contin雨a[n]y se espera que la gripe[n]empiece a propagarse pronto.[n][w][e]
[s]Seg雨n un centro m姻dico de Tokio,[n]el n雨mero de pacientes puede[n]aumentar a雨n m茨s la pr吋xima semana.[n][w][e]

[msg TV_NEWS_1115_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]La gripe, 夷eh? Ser茨 mejor[n]que te cuides, no vayas[n]a ponerte enfermo.[n][w][e]

[msg TV_MACHI_1116_000_00 [Periodista]]
[s]Hoy tenemos una edici吋n especial[n]de 或斡Exploradores de la ciudad!位.[n][w][e]
[s]斡En estas emisiones especiales,[n]compartimos productos de[n]edici吋n limitada que est茨n de moda![n][w][e]
[s]斡Hoy hablamos de la [clr 2]tarta 茨ngel[clr 27][n]de la tienda Taisho![n]斡Est茨 en venta hasta Navidad![n][w][e]

[msg TV_MACHI_1116_100_00 [Especialista]]
[s]Me encantan las [clr 2]tartas 茨ngel[clr 27].[n]No me importar胤a hacer[n]una cola enorme para comprarlas.[n][w][e]
[s]Cuando las veo en los estantes,[n]me hacen sentir que[n]la Navidad est茨 muy cerca.[n][w][e]

[msg TV_NEWS_1117_000_00 [Presentador de telediario]]
[s]Con la C茨mara de Representantes[n]disuelta, los partidos han empezado[n]la campa隠a electoral.[n][w][e]
[s]Los temas de seguridad relacionados[n]con los Ladrones Fantasma[n]reciben especial atenci吋n.[n][w][e]
[s]La clave para ganar las elecciones[n]ser茨 la forma que tenga cada[n]partido de afrontar el problema.[n][w][e]

[msg TV_NEWS_1117_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1102 65535 0][f 4 25 1 65535 0 0]夷Ahora somos los chivos[n]expiatorios? Solo se gu胤an[n]por sus intereses...[n][w][e]

[msg TV_WIDESHOW_1118_000_00 [Presentador]]
[s]斡Saludos! 夷Qu姻 le aguarda[n]a la Dieta tras la disoluci吋n[n]de la C茨mara de Representantes?[n][w][e]
[s]Hoy dedicaremos nuestro especial[n]a Masayoshi Shido, quien puede que[n]sea el pr吋ximo primer ministro.[n][w][e]

[msg TV_WIDESHOW_1118_100_00 [Panelista]]
[s]Shido goza del benepl茨cito[n]del pueblo. Hay puestas muchas[n]esperanzas en 姻l como pol胤tico.[n][w][e]

[msg TV_NEWS_1119_000_00 [Presentador de telediario]]
[s]Los partidos han estado ocupados[n]prepar茨ndose para el anuncio[n]de la fecha de las elecciones.[n][w][e]
[s]La ruptura del Partido Liberal[n]de la Coprosperidad ha provocado[n]serios problemas a sus exmiembros.[n][w][e]
[s]La oposici吋n ha pasado al ataque[n]con el partido Futuro Unido[n]del se隠or Shido en cabeza.[n][w][e]

[msg TV_NEWS_1119_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0][f 4 25 1 65535 0 0]No paran de hablar[n]de las elecciones en televisi吋n.[n]Claro, es un asunto muy importante.[n][w][e]

[msg TV_NEWS_1121_000_00 [Presentador de telediario]]
[s]Por ahora, la polic胤a ha compartido[n]poca informaci吋n sobre el muchacho[n]que parece ser el culpable.[n][w][e]
[s]Dado lo inusual del caso, est茨n[n]siendo muy precavidos[n]con los datos que revelan.[n][w][e]
[s]La operaci吋n ha sido un 姻xito[n]y no ha habido ninguna protesta[n]importante hasta ahora.[n][w][e]

[msg TV_NEWS_1121_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Nos viene de perlas que no hayan[n]desvelado demasiada informaci吋n.[n]Debe de ser gracias a Niijima.  [n][w][e]

[msg TV_NEWS_1122_000_00 [Presentador de telediario]]
[s]El caso de los Ladrones Fantasma ha[n]llegado a un abrupto final con el[n]suicidio del l胤der tras el arresto.[n][w][e]
[s]Hay quien exige a la polic胤a que[n]asuma la responsabilidad[n]por no haber evitado el suicidio.[n][w][e]
[s]Aun as胤, la mayor胤a alaba al se隠or[n]Goro Akechi y a su equipo por[n]detener a los Ladrones Fantasma.[n][w][e]

[msg TV_NEWS_1122_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]斡Parece que les hemos dado gato[n]por liebre! Debemos actuar antes[n]de que se den cuenta...[n][w][e]

[msg TV_NEWS_1123_000_00 [Presentador de telediario]]
[s]La campa隠a electoral ha empezado[n]tras anunciarse la fecha[n]de las elecciones.[n][w][e]
[s]Los candidatos han salido[n]a las calles buscando[n]el apoyo de los votantes.[n][w][e]
[s]Masayoshi Shido, del partido Futuro[n]Unido, ha estado dando discursos[n]en Yongen-Jaya y otras zonas.[n][w][e]

[msg TV_NEWS_1123_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]夷C吋mo puede ser tan popular?[n]Si es lo peor...[n][w][e]

[msg TV_QUIZ_1124_000_00 [Presentador de concurso]]
[s]Las elecciones se acercan y todos[n]las tenemos en mente, pero quiz茨[n]no todos sepan esto sobre la Dieta...[n][w][e]
[s]La Dieta decide las cosas por[n]mayor胤a, pero 夷qu姻 ocurre si los[n]votos se reparten al 50 %?[n][w][e]
[s]A) Elige el Presidente de la C茨mara.[n]B) Se decide a cara o cruz.[n][w][e]

[sel SEL_QUIZ_1124 top]
[s]Elige el Presidente de la C茨mara.[e]
[s]Se decide a cara o cruz.[e]

[msg TV_QUIZ_1124_100_00 [Presentador de concurso]]
[s]La respuesta correcta es... 斡la A![n]斡Elige el Presidente de la C茨mara![n]He aqu胤 la explicaci吋n.[n][w][e]

[msg TV_QUIZ_1124_200_00 [Abogado]]
[s]Seg雨n el art胤culo 56, secci吋n 2[n]de la Constituci吋n, el Presidente[n]de la C茨mara es quien decide.[n][w][e]
[s]Tras las elecciones generales,[n]la Dieta debe nombrar a un nuevo[n]primer ministro por ley.[n][w][e]

[msg TV_MORGANA_1124_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]斡Has acertado! Los empates no son[n]muy comunes, supongo.[n][w][e]

[msg TV_MORGANA_1124_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Lanzar una moneda ser胤a m茨s[n]interesante. Los empates no son[n]muy comunes, supongo.[n][w][e]

[msg TV_NEWS_1125_000_00 [Presentador de telediario]]
[s]A continuaci吋n les traemos[n]nueva informaci吋n sobre[n]las elecciones generales.[n][w][e]
[s]Teniendo en cuenta el caos[n]pol胤tico actual, la fecha de las[n]elecciones queda bastante lejos.[n][w][e]
[s]Se celebrar茨n el 18 del mes que[n]viene. A los candidatos les espera[n]una larga y ardua contienda.[n][w][e]

[msg TV_NEWS_1125_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Las elecciones ser茨n el 18.[n]斡Tenemos que acabar[n]con esto cuanto antes![n][w][e]

[msg TV_NEWS_1126_000_00 [Presentador de telediario]]
[s]Empieza una feroz batalla tras el[n]anuncio del d胤a de las elecciones[n]a la C茨mara de Representantes.[n][w][e]
[s]Futuro Unido, un nuevo partido[n]liderado por Masayoshi Shido,[n]est茨 obteniendo un gran apoyo.[n][w][e]
[s]Se ha ganado el coraz吋n de los[n]votantes con discursos vehementes[n]y una ret吋rica f茨cil de entender.[n][w][e]

[msg TV_NEWS_1126_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]斡Ja, espera y ver茨s! 斡Antes de que[n]te des cuenta, estar茨s llorando[n]como un beb姻![n][w][e]

[msg TV_NEWS_1126_200_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 53106 65535 0][f 4 25 1 65535 0 0]Qu姻 raro...[n]Si ya hemos expuesto sus delitos...[n][w][e]

[msg TV_NEWS_1128_000_00 [Presentador de telediario]]
[s]Hemos pedido la opini吋n del[n]p雨blico sobre las elecciones[n]a la C茨mara de Representantes.[n][w][e]
[s]Les hemos preguntado[n]por el que creen que es[n]el pol胤tico m茨s prometedor...[n][w][e]
[s]El de Masayoshi Shido, l胤der del[n]partido Futuro Unido, es el nombre[n]que m茨s se ha repetido.[n][w][e]
[s]Es una prueba evidente[n]de que es el principal candidato.[n][w][e]

[msg TV_NEWS_1128_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]斡Ya ver茨s![n]斡Te vamos a bajar los humos![n][w][e]

[msg TV_NEWS_1128_200_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 53106 65535 0][f 4 25 1 65535 0 0]Espera... 夷Shido es el favorito?[n]夷Qu姻 est茨 pasando?[n][w][e]

[msg TV_SHOUGI_1129_000_00 [Entrevistadora]]
[s]Pe吋n a 3-6, pero no parece que esto[n]vaya a acabar en jaque mate...[n][w][e]

[msg TV_SHOUGI_1129_100_00 [Jugador profesional de shogi]]
[s]S胤, es todo un acontecimiento.[n]Creo que le he dado la vuelta.[n][w][e]
[s]Espera... 夷Eh?[n][w][e]
[s]Si yo hago esto y ellos esto otro,[n]夷me quedan suficientes peones...?[n][w][e]
[s]斡H-hala! Ahora s胤 que la he liado...[n][w][e]

[msg TV_SHOUGI_1129_200_00 [Entrevistadora]]
[s]夷Eh?[n][w][e]

[msg TV_MACHI_1130_000_00 [Periodista]]
[s]斡Hoy retransmitimos[n]或斡Exploradores de la ciudad!位[n]desde Yasoinaba![n][w][e]
[s]Estamos delante de Marukyu[n]Tofu, 斡hogar de la famosa Risette![n][w][e]

[msg TV_MACHI_1130_100_00 [Especialista]]
[s]斡Rise Kujikawa ha estado ausente[n]un tiempo, pero 夷su atractivo se[n]deber茨 al poder del tofu?[n][w][e]

[msg TV_NEWS_1201_000_00 [Presentador de telediario]]
[s]Diciembre es un mes de preocupaci吋n[n]econ吋mica para muchos, as胤 como[n]la 姻poca de las pagas navide隠as.[n][w][e]
[s]Tras analizar a varias empresas,[n]hemos concluido que la mayor胤a de[n]pagas son inferiores al a隠o pasado.[n][w][e]
[s]Muchos culpan al gobierno[n]por el estado de la econom胤a,[n]cuya recuperaci吋n ser茨 complicada.[n][w][e]

[msg TV_NEWS_1201_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]Yo tambi姻n quiero una paga extra.[n]夷Me dar茨s una si trabajo mucho?[n][w][e]

[msg TV_WIDESHOW_1202_000_00 [Presentador]]
[s]斡Saludos! 斡Hoy veremos el caso de[n]unos bellezones que se las apa隠an[n]ante cualquier situaci吋n![n][w][e]
[s]Recibimos a Yukari Takeba,[n]斡una universitaria que hace[n]programas de superh姻roes![n][w][e]

[msg TV_WIDESHOW_1202_100_00 [Panelista]]
[s]Ah, es la que hace de Grulla Rosa[n]en la serie esa, 夷no?[n][w][e]

[msg TV_ANIME_1203_000_00 [Narrador]]
[s]斡Cruzando el espacio-tiempo,[n]los Phoenix Rangers han unido todos[n]sus poderes en uno solo![n][w][e]
[s]斡夷Podr茨n volver[n]a sus mundos originales?![n]斡Revivid y luchad, Phoenix Rangers![n][w][e]
[s]En el pr吋ximo episodio...[n]或El regreso[n]de los Phoenix Rangers位.[n][w][e]

[msg TV_NEWS_1204_000_00 [Presentador de telediario]]
[s]A雨n queda la segunda mitad de[n]la campa隠a electoral, pero parece[n]que ya hay un claro ganador.[n][w][e]
[s]El partido Futuro Unido, liderado[n]por el se隠or Shido, tiene mucha[n]ventaja sobre sus rivales.[n][w][e]
[s]Su victoria parece segura,[n]y la gente est茨 ansiosa por tener[n]un nuevo primer ministro.[n][w][e]

[msg TV_NEWS_1204_001_00 [Presentador de telediario]]
[s]En cuanto al se隠or Shido,[n]ha seguido dando discursos y...[n][w][e]

[msg TV_NEWS_1204_101_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]斡A este paso, acabar茨 siendo[n]el pr吋ximo primer ministro![n]斡Hay que despertarlo![n][w][e]

[msg TV_NEWS_1204_001_01 [Presentador de telediario]]
[s]Shido no ha hecho apariciones[n]p雨blicas 雨ltimamente. Puede que se[n]deba a lo mucho que ha trabajado.[n][w][e]

[msg TV_NEWS_1204_101_01 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]La idea de que gane despu姻s de todo[n]lo que hemos hecho para[n]despertarlo es insoportable...[n][w][e]

[msg TV_DRAMA_1205_000_00 [Detective ingenioso]]
[s]Ha hecho bien en confesar.[n][w][e]
[s]En el juicio, deber胤an[n]tener en cuenta[n]sus circunstancias atenuantes.[n][w][e]
[s]Pero 夷por qu姻 decidi吋 cont茨rmelo[n]tan de repente?[n][w][e]

[msg TV_DRAMA_1205_100_00 [Mujer que ha confesado]]
[s]Porque... quer胤a comer katsudon.[n][w][e]

[msg TV_MORGANA_1205 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1040 65535 0][f 4 25 1 65535 0 0]斡夷Por eso?! Oye, 夷te dieron[n]katsudon cuando[n]estuviste en la c茨rcel?[n][w][e]

[msg TV_SHOUGI_1206_000_00 [Entrevistadora]]
[s]夷Plata a 9-1? Estabas temblando[n]mientras mov胤as esa pieza.[n][w][e]

[msg TV_SHOUGI_1206_100_00 [Jugador profesional de shogi]]
[s]Oh, 夷en serio? Quiz茨 no tenga[n]m茨s opci吋n que rendirme[n]llegado a este punto.[n][w][e]
[s]Ninguno de mis rivales ha temblado[n]jam茨s mientras jugaba conmigo,[n]as胤 que ahora tengo cierta envidia.[n][w][e]

[msg TV_NEWS_1207_000_00 [Presentador de telediario]]
[s]En esta segunda mitad[n]de la campa隠a, la competencia es[n]feroz hasta en las zonas rurales.[n][w][e]
[s]Tenemos con nosotros al se隠or[n]Taro Namatame, un candidato[n]independiente reci姻n llegado.[n][w][e]
[s]Empez吋 como secretario de[n]un pol胤tico y se abri吋 camino desde[n]lo m茨s bajo en Inaba, y...[n][w][e]

[msg TV_NEWS_1207_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0][f 4 25 1 65535 0 0]夷No es un poco mayor para ser[n]un novato? Me han entrado[n]ganas de apoyarlo.[n][w][e]

[msg TV_QUIZ_1208_000_00 [Presentador de concurso]]
[s]Digamos que alguien dispara un arma[n]porque quiere matar a otra persona,[n]pero acaba hiriendo a un tercero.[n][w][e]
[s]En tal caso, 夷de qu姻 delito[n]se le acusar胤a a la persona[n]que dispara el arma?[n][w][e]
[s]A) Intento de asesinato.[n]B) Homicidio involuntario.[n][w][e]
[s]夷Cu茨l es la respuesta correcta?[n]斡Juzguen ustedes mismos![n][w][e]

[sel SEL_QUIZ_1208 top]
[s]Intento de asesinato.[e]
[s]Homicidio involuntario.[e]

[msg TV_QUIZ_1208_100_00 [Presentador de concurso]]
[s]La respuesta correcta es... 斡la A![n]Entonces, 夷herir a un transe雨nte[n]no cuenta como agresi吋n?[n][w][e]

[msg TV_QUIZ_1208_200_00 [Abogado]]
[s]La pregunta era un poco enga隠osa.[n]La respuesta es la A, pero los dos[n]son casos de intento de asesinato.[n][w][e]
[s]Se le acusar胤a del mismo delito[n]aunque alguien ajeno se vea[n]envuelto sin comerlo ni beberlo.[n][w][e]

[msg TV_MORGANA_1208_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]Me sorprende que acertaras.[n]Yo no ten胤a ni idea.[n][w][e]

[msg TV_MORGANA_1208_b [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]夷Te pueden condenar[n]por el mismo delito dos veces?[n]Vaya pregunta m茨s rara.[n][w][e]

[msg TV_WIDESHOW_1209_000_00 [Presentador]]
[s]斡Saludos! 斡El especial de hoy va[n]sobre unos h姻roes de la polic胤a[n]muy especiales! 斡Conozc茨moslos![n][w][e]
[s]斡Veremos a un atractivo detective[n]con gafas de sol rojas y a un poli[n]legendario que acab吋 con un oso![n][w][e]

[msg TV_WIDESHOW_1209_100_00 [Panelista]]
[s]A雨n no es agente de polic胤a, pero[n]en la academia hay una chica de[n]armas tomar que sabe kung-fu.[n][w][e]

[msg TV_NEWS_1210_000_00 [Presentador de telediario]]
[s]Y ahora, m茨s noticias sobre[n]las elecciones. Hemos hecho una[n]encuesta entre los espectadores.[n][w][e]
[s]Futuro Unido cuenta con[n]much胤simo apoyo, recibiendo[n]m茨s del 50 % de los votos.[n][w][e]
[s]Lo tiene dif胤cil el Partido[n]Liberal de la Coprosperidad,[n]actualmente en el poder.[n][w][e]

[msg TV_NEWS_1210_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]斡夷El partido de Shido va a ganar?![n]Qu姻 mal...[n][w][e]

[msg TV_DRAMA_1212_000_00 [Detective ingenioso]]
[s]夷Por qu姻 colg吋 los cad茨veres[n]en postes de tel姻fono[n]y antenas de televisi吋n?[n][w][e]

[msg TV_DRAMA_1212_100_00 [Sospechoso bajo investigaci吋n]]
[s]Supongo que lo hice[n]porque el mundo es una mierda.[n][w][e]

[msg TV_DRAMA_1212_200_00 [Detective ingenioso]]
[s]斡夷Los mat吋 a todos por una raz吋n[n]como esa?! 斡夷Y no se arrepiente?![n][w][e]

[msg TV_MORGANA_1212 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]斡Qu姻 miedo! Este detective[n]se vuelve loco cuando se cabrea.[n][w][e]

[msg TV_NEWS_1213_000_00 [Presentador de telediario]]
[s]Con el partido Futuro Unido[n]del se隠or Shido en cabeza...[n][w][e]
[s]El resto de candidatos est茨n[n]trabajando con especial ah胤nco[n]en sus discursos.[n][w][e]
[s]En Shibuya, un candidato sosten胤a[n]un cartel mientras hablaba[n]con energ胤a y pasi吋n.[n][w][e]

[msg TV_NEWS_1213_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Es impresionante que sigan a pesar[n]de no tener opciones. Espera, 夷no[n]hemos visto a ese tipo antes?[n][w][e]

[msg TV_MACHI_1214_000_00 [Periodista]]
[s]斡Hoy retransmitimos[n]或斡Exploradores de la ciudad!位[n]desde Yasoinaba![n][w][e]
[s]La posada Amagi tiene una larga[n]historia, y es famosa por[n]su deliciosa comida y sus ba隠os.[n][w][e]

[msg TV_MACHI_1214_100_00 [Especialista]]
[s]斡La due隠a es muy simp茨tica![n]Merece la pena ir solo[n]para hablar con ella, ja, ja, ja.[n][w][e]

[msg TV_QUIZ_1215_000_00 [Presentador de concurso]]
[s]La pregunta de hoy es sobre[n]entregarse, algo que se ve a[n]menudo en las series polic胤acas.[n][w][e]
[s]El entregarse...[n]A) Asegura clemencia en un juicio.[n]B) No pueden hacerlo los fugitivos.[n][w][e]
[s]夷Cu茨l es la respuesta correcta?[n]斡Juzguen ustedes mismos![n][w][e]

[sel SEL_QUIZ_1215 top]
[s]Asegura clemencia en un juicio.[e]
[s]No pueden hacerlo los fugitivos.[e]

[msg TV_QUIZ_1215_100_00 [Presentador de concurso]]
[s]La respuesta correcta es... 斡la B![n]斡Uno no puede entregarse[n]si est茨 en busca y captura![n][w][e]

[msg TV_QUIZ_1215_200_00 [Abogado]]
[s]Se llama 或rendirse位 cuando alguien[n]en busca y captura va a las autoridades.[n]Al huir renuncia al derecho a entregarse.[n][w][e]
[s]Si puede entregarse y lo hace,[n]quiz茨 el juez sea indulgente,[n]pero eso depende de 姻l.[n][w][e]

[msg TV_MORGANA_1215_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Te has equivocado, 夷eh? Bueno,[n]es normal pensar as胤.[n][w][e]

[msg TV_MORGANA_1215_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]Muy bien, has acertado.[n]Aunque no s姻 c吋mo nos va[n]a ayudar saber eso.[n][w][e]

[msg TV_NEWS_1216_000_00 [Presentador de telediario]]
[s]Los candidatos intentan[n]movilizar a sus votantes[n]a pocos d胤as de las elecciones.[n][w][e]
[s]Entre ellos, el partido Futuro[n]Unido, liderado por Shido,[n]se ha ganado el coraz吋n de muchos.[n][w][e]

[msg TV_NEWS_1216_001_00 [Presentador de telediario]]
[s]El p雨blico celebr吋 apasionadamente[n]el discurso del se隠or Shido.[n][w][e]

[msg TV_NEWS_1216_101_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]斡Oye! 斡No podemos dejar que se gane[n]as胤 a la gente! 斡Nos estamos[n]quedando sin tiempo![n][w][e]

[msg TV_NEWS_1216_001_01 [Presentador de telediario]]
[s]El se隠or Shido todav胤a no ha[n]aparecido en p雨blico, y algunos[n]se preguntan por su salud.[n][w][e]

[msg TV_NEWS_1216_101_01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0][f 4 25 1 65535 0 0]Si Shido mete la pata,[n]al fin se acabar茨 todo.[n][w][e]

[msg TV_NEWS_1217_000_00 [Presentador de telediario]]
[s]La temporada electoral empieza[n]con una moci吋n de censura y la[n]ruptura del partido en el gobierno.[n][w][e]
[s]Qu姻 clase de victoria conseguir茨[n]el partido Futuro Unido de Shido[n]sigue siendo un misterio.[n][w][e]

[msg TV_NEWS_1217_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Ma隠ana es el d胤a...[n]斡Le demostraremos[n]de lo que somos capaces![n][w][e]

[msg TV_NEWS_1218_000_00 [Presentador de telediario]]
[s]Como ya hemos informado,[n]las elecciones de la C茨mara[n]de Representantes han finalizado...[n][w][e]
[s]El partido Futuro Unido de[n]Masayoshi Shido se ha hecho[n]con una gran mayor胤a de esca隠os.[n][w][e]
[s]Con estos resultados, se prev姻[n]la formaci吋n de un nuevo gobierno[n]a finales de mes.[n][w][e]

[msg TV_NEWS_1218_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 53130 65535 0][f 4 25 1 65535 0 0]Ha ganado las elecciones, pero[n]Niijima har茨 algo al respecto.[n][w][e]

[msg TV_NEWS_1219_000_00 [Presentador de telediario]]
[s]Futuro Unido ha obtenido[n]la mayor胤a de esca隠os[n]en las elecciones generales.[n][w][e]
[s]Pero la baja de Shido por[n]enfermedad ha ocasionado problemas[n]a los l胤deres del partido.[n][w][e]
[s]Est茨n en alerta m茨xima y se han[n]cerrado por completo a los medios.[n]Volveremos con m茨s detalles.[n][w][e]

[msg TV_NEWS_1219_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 53130 65535 0][f 4 25 1 65535 0 0]Contamos contigo, Niijima.[n]Nos hemos dejado la piel para[n]que Shido no se salga con la suya...[n][w][e]

[msg TV_NEWS_1220_000_00 [Presentador de telediario]]
[s]Con las Navidades a la vuelta[n]de la esquina, hemos preguntado[n]a los viandantes algo interesante.[n][w][e]
[s]Seg雨n el gobierno, la sociedad[n]envejece. Para recordarles[n]a los mayores su juventud...[n][w][e]
[s]Algunos restaurantes ofrecen a las[n]parejas mayores de 65 a隠os comer a[n]mitad de precio el d胤a de Navidad.[n][w][e]

[msg TV_NEWS_1220_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 53130 65535 0][f 4 25 1 65535 0 0]Vaya, Navidad... Aunque nosotros[n]solo deber胤amos preocuparnos[n]de que todo haya salido bien.[n][w][e]

[msg TV_NEWS_1221_000_00 [Presentador de telediario]]
[s]Y ahora, pasamos a la pol胤tica.[n][w][e]
[s]Todos se preguntan qui姻n ser茨[n]el nuevo primer ministro. Los[n]datos de nuestra encuesta indican...[n][w][e]
[s]Que muchos quieren el regreso[n]de Masayoshi Shido, el ganador[n]de las elecciones anteriores.[n][w][e]

[msg TV_NEWS_1221_100_00 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1043 65535 0][f 4 25 1 65535 0 0]斡夷Qu姻?! Pero 斡si hemos[n]ganado nosotros![n][w][e]

[msg TV_NEWS_1222_000_00 [Presentador de telediario]]
[s]Y ahora, pasamos a la pol胤tica.[n][w][e]
[s]Todos se preguntan qui姻n ser茨[n]el nuevo primer ministro. Los[n]datos de nuestra encuesta indican...[n][w][e]
[s]Que muchos quieren el regreso[n]de Masayoshi Shido, el ganador[n]de las elecciones anteriores.[n][w][e]

[msg TV_NEWS_1222_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Ma隠ana dejar茨 de ser tan popular.[n]Todo el mundo descubrir茨[n]qui姻n es en realidad.[n][w][e]

[msg TV_NEWS_1223_000_00 [Presentador de telediario]]
[s]Nochebuena est茨 al caer,[n]y ya se puede sentir la emoci吋n[n]en el ambiente.[n][w][e]
[s]Las calles est茨n iluminadas[n]con luces de colores[n]y abarrotadas de gente...[n][w][e]
[s]Se pueden ver familias enteras[n]comprando regalos.[n][w][e]

[msg TV_NEWS_1223_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]Ma隠ana es Nochebuena...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 53130 65535 0][f 4 25 1 65535 0 0]El 雨nico regalo que quiero[n]es que nuestro plan salga bien.[n]Lo deseo con toda mi alma.[n][w][e]

[msg TV_NEWS_1224_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]12月24日の番組内容 [n][w][e]

[msg TV_NEWS_1224_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_1225_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]12月25日の番組内容[n][w][e]

[msg TV_NEWS_1225_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_1226_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]12月26日の番組内容[n][w][e]

[msg TV_NEWS_1226_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_1227_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]12月27日の番組内容[n][w][e]

[msg TV_NEWS_1227_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_1228_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]12月28日の番組内容[n][w][e]

[msg TV_NEWS_1228_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_1229_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]12月29日の番組内容[n][w][e]

[msg TV_NEWS_1229_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_1230_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]12月30日の番組内容[n][w][e]

[msg TV_NEWS_1230_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_1231_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]12月31日の番組内容[n][w][e]

[msg TV_NEWS_1231_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0101_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]1月1日の番組内容[n][w][e]

[msg TV_NEWS_0101_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0102_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]1月2日の番組内容[n][w][e]

[msg TV_NEWS_0102_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0103_000_00 [Presentador de telediario]]
[s]Mucha gente est茨 volviendo[n]de visitar a sus familias.[n][w][e]
[s]La estaci吋n estaba bastante vac胤a[n]a primera hora, pero despu姻s[n]del mediod胤a empez吋 a llenarse.[n][w][e]

[msg TV_NEWS_0103_100_00]
[s]Hay mucha gente arremolinada.[n]De solo verlo ya me entra[n]dolor de cabeza.[n][w][e]

[msg TV_NEWS_0104_000_00 [Presentador de telediario]]
[s]Han pasado tres d胤as desde que[n]comenz吋 el a隠o, pero la gente[n]sigue visitando los santuarios.[n][w][e]
[s]Hoy hemos preguntado[n]cu茨nto dejan de ofrenda.[n][w][e]
[s]La mayor胤a deja de 10 a 100 yenes,[n]pero algunos aseguran[n]haber dejado hasta 10 000 yenes.[n][w][e]

[msg TV_NEWS_0104_100_00]
[s]Hay personas que no escatiman[n]en generosidad.[n][w][e]

[msg TV_NEWS_0105_000_00 [Presentador de telediario]]
[s]Han aumentado las muertes[n]de ancianos por atragantamiento[n]con mochi.[n][w][e]
[s]Hablaremos con un profesional[n]para conocer el mejor m姻todo[n]para evitar este problema.[n][w][e]

[msg TV_NEWS_0105_100_00 [Profesional]]
[s]Ser胤a conveniente cortarlo[n]en trozos peque隠os[n]o comerlo lentamente...[n][w][e]
[s]Pero la t姻cnica infalible es[n]no comer mochi.[n][w][e]

[msg TV_NEWS_0105_200_00]
[s]M茨s me vale tener cuidado[n]cuando coma mochi...[n][w][e]

[msg TV_NEWS_0106_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]1月6日の番組内容[n][w][e]

[msg TV_NEWS_0106_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0107_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]1月7日の番組内容[n][w][e]

[msg TV_NEWS_0107_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0108_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]1月8日の番組内容[n][w][e]

[msg TV_NEWS_0108_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0109_000_00 [Presentador de telediario]]
[s]Es el D胤a de la Mayor胤a de Edad.[n]Hay quienes celebran volverse[n]adultos en distintos lugares.[n][w][e]
[s]Incluso algunos han alquilado[n]Destinyland, en Maihama, para...[n][w][e]

[msg TV_NEWS_0109_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]Es como una superfiesta, 夷no?[n]夷El D胤a de la Mayor胤a de Edad[n]es siempre as胤?[n][w][e]

[msg TV_NEWS_0110_000_00 [Presentador de telediario]]
[s]Se han acabado las vacaciones[n]de invierno y da comienzo[n]un nuevo a隠o escolar.[n][w][e]
[s]Vemos a estudiantes que[n]se saludan al volver[n]de las vacaciones, as胤 como[n][w][e]
[s]A otros preocupados por entrar[n]en el instituto que desean[n]tras los ex茨menes de acceso.[n][w][e]

[msg TV_NEWS_0110_100_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]Aunque me muera de ganas[n]de ser humano, no me gustar胤a[n]presentarme a esos ex茨menes.[n][w][e]

[msg TV_NEWS_0111_000_00 [Presentador de telediario]]
[s]Hoy cubrimos un evento en el que[n]se rompe el mochi de a隠o nuevo[n]para atraer la buena suerte.[n][w][e]
[s]En estos santuarios, los ni隠os se[n]turnan para romper el mochi gigante[n]expuesto para el A隠o Nuevo.[n][w][e]

[msg TV_NEWS_0111_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]夷C吋mo comen tan r茨pido[n]sin atragantarse?[n][w][e]

[msg TV_QUIZ_0112_000_00 [Presentador de concurso]]
[s]En A隠o Nuevo, es posible[n]que los mayores se atraganten[n]sin querer con el mochi.[n][w][e]
[s]En tal caso, 夷ser胤an los cocineros[n]que prepararon el mochi[n]los responsables legales?[n][w][e]
[s]A) Son responsables.[n]B) No son responsables.[n][w][e]

[sel SEL_QUIZ_0112 top]
[s]Son responsables.[e]
[s]No son responsables.[e]

[msg TV_QUIZ_0112_100_00 [Presentador de concurso]]
[s]La respuesta correcta es la B.[n]斡Pod姻is seguir preparando[n]mochi sin problemas![n][w][e]

[msg TV_QUIZ_0112_200_00 [Abogado]]
[s]Debemos saber si es obligatorio[n]avisarles de que comer mochi es[n]peligroso y se pueden atragantar.[n][w][e]
[s]Como en Jap吋n es de sentido com雨n,[n]la falta de explicaciones[n]no se considera infracci吋n.[n][w][e]
[s]No obstante, si hay piezas grandes[n]de mochi y no se les avisa[n]antes de comer...[n][w][e]
[s]Se vuelve una infracci吋n de[n]或obligaci吋n de seguridad位, y los[n]cocineros podr胤an ser responsables.[n][w][e]

[msg TV_MORGANA_0112_a [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]No llevabas raz吋n, pero es[n]un alivio. Imagina que te hacen[n]responsable de algo as胤.[n][w][e]

[msg TV_MORGANA_0112_b [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1072 65535 0][f 4 25 1 65535 0 0]斡S胤, eso es! En otras palabras,[n]mientras tengas sentido com雨n,[n]te ir茨 bien.[n][w][e]

[msg TV_NEWS_0113_000_00 [Presentador]]
[s]斡Hola, hola! 斡夷Qu姻 tal el[n]descomunal sorteo de fin de a隠o?![n][w][e]
[s]斡Hoy hablaremos con alguien que[n]ha ganado 800 millones de yenes![n][w][e]

[msg TV_NEWS_0113_100_00 [Panelista]]
[s]800 millones, 夷no es as胤?[n]斡Es tanto dinero[n]que no me lo podr胤a creer![n][w][e]
[s]Qui姻n iba a imaginar que un sue隠o[n]as胤 se har胤a realidad...[n]夷C吋mo se sentir茨n ahora mismo?[n][w][e]

[msg TV_NEWS_0114_000_00 [Narrador]]
[s]斡Malas noticias para nuestros[n]h姻roes! Han engordado estas fiestas[n]y ya no les caben los trajes.[n][w][e]
[s]Para volver a ponerse en forma,[n]tendr茨n que... 斡夷bailar?![n]斡Revivid y bailad, Phoenix Rangers![n][w][e]
[s]En el pr吋ximo episodio...[n]或斡Bailando a la luz de las alas!位.[n][w][e]

[msg TV_NEWS_0115_000_00 [Presentador de telediario]]
[s]En el episodio 3 de 或Gente en su[n]camino位, hablamos de los humoristas[n]que vendieron su alma a la comedia.[n][w][e]

[msg TV_NEWS_0115_050_00 [Narrador]]
[s]Lo 雨nico que los hac胤a felices[n]en la pobreza era la risa.[n][w][e]
[s]或斡Mam茨, me voy a Tokio! Voy a hacer[n]re胤r al mundo位. A pesar de decirlo[n]esto, pas吋 una mala racha.[n][w][e]

[msg TV_NEWS_0115_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]斡Este es nuestro momento crucial![n][w][e]

[msg TV_NEWS_0116_000_00 [Presentador de telediario]]
[s]Parece que habr茨 una ola de fr胤o[n]en Jap吋n durante una temporada.[n][w][e]
[s]Los meteor吋logos aseguran[n]que puede haber olas de fr胤o[n]y mal tiempo.[n][w][e]

[msg TV_NEWS_0116_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0][f 4 25 1 65535 0 0]A Mementos tambi姻n[n]le afecta el tiempo.[n]Deber胤amos estar pendientes.[n][w][e]

[msg TV_NEWS_0117_000_00 [Entrevistadora]]
[s]Tras el devastador pe吋n a 6-4,[n]hemos parado a comer algo.[n][w][e]
[s]Acabamos de volver, pero...[n]Tiene claro que va a rendirse[n]sin hacer ni un solo movimiento.[n][w][e]

[msg TV_NEWS_0117_100_00 [Jugador profesional de shogi]]
[s]La verdad es que me sorprende.[n][w][e]
[s]Se habr茨 dado cuenta de que ha[n]perdido la partida mientras com胤a.[n][w][e]

[msg TV_NEWS_0117_200_00 [Entrevistadora]]
[s]Han comido curry, al parecer.[n]Por su estado de 茨nimo,[n]ha tenido que costarle tragarlo...[n][w][e]

[msg TV_NEWS_0118_000_00 [Periodista]]
[s]En 或斡Exploradores de la ciudad!位,[n]斡tenemos un especial[n]sobre Odaiba en invierno![n][w][e]
[s]Aunque se hayan desmontado[n]las luces de Navidad, la nieve[n]en Odaiba es digna de admiraci吋n.[n][w][e]
[s]Este estadio est茨 en construcci吋n,[n]pero cuando est姻 terminado[n]atraer茨 muchos visitantes.[n][w][e]

[msg TV_NEWS_0118_100_00 [Especialista]]
[s]A pesar de estar en construcci吋n,[n]lo rodea un halo de misterio...[n][w][e]

[msg TV_NEWS_0118_200_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]No saben que es un Palacio.[n]La gente corriente no puede[n]ver lo que son en realidad.[n][w][e]

[msg TV_NEWS_0119_000_00 [Presentador de telediario]]
[s]Hoy, en El Consejero... Hablaremos[n]sobre la situaci吋n actual[n]de muchas empresas.[n][w][e]
[s]Acoso sexual, abuso de poder,[n]muerte por exceso de trabajo...[n]Es necesario un cambio urgente.[n][w][e]
[s]Por eso mismo las grandes compa隠胤as[n]est茨n empezando a contratar[n]a asesores, y...[n][w][e]

[msg TV_NEWS_0119_100_00 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1028 65535 0][f 4 25 1 65535 0 0]Trabajar ya es lo suficientemente[n]duro... Espero que esto mejore su[n]entorno de trabajo de alg雨n modo.[n][w][e]

[msg TV_NEWS_0120_000_00 [Presentador de telediario]]
[s]Hemos preguntado a las empresas[n]por su estado financiero[n]despu姻s del A隠o Nuevo.[n][w][e]
[s]Las estad胤sticas indican que[n]a las compa隠胤as les va muy bien.[n][w][e]
[s]Por lo visto, su deseo de escapar[n]de esta situaci吋n y reflotar[n]la econom胤a se ha vuelto realidad.[n][w][e]

[msg TV_NEWS_0120_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0][f 4 25 1 65535 0 0]夷Deseos volvi姻ndose realidad?[n]夷Ser茨 cosa de Maruki?[n][w][e]

[msg TV_NEWS_0121_000_00 [Presentador de telediario]]
[s]Hoy es el 或d胤a m茨s fr胤gido位[n]del per胤odo solar,[n]es decir, el d胤a m茨s fr胤o del a隠o.[n][w][e]
[s]Lo m茨s probable es que haya[n]una ola de fr胤o la semana[n]que viene, as胤 que prep茨rense.[n][w][e]

[msg TV_NEWS_0121_100_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0][f 4 25 1 65535 0 0]No me extra隠a que haga tanto fr胤o...[n]Me pasar胤a el d胤a delante[n]de una estufa con una mantita.[n][w][e]

[msg TV_NEWS_0123_000_00 [Detective ingenioso]]
[s]Hab胤a una huella en la nieve.[n]Esa es la prueba.[n][w][e]
[s]Te he localizado[n]por la huella que dejaste... [n][w][e]

[msg TV_NEWS_0123_100_00 [Sospechoso]]
[s]夷Hablas en serio?[n][w][e]

[msg TV_NEWS_0123_200_00 [Detective ingenioso]]
[s]Ah, perdona. Era broma.[n][w][e]
[s]Creo que mi humor[n]no te ha dejado suficiente... huella.[n][w][e]

[msg TV_NEWS_0123_300_00 [Sospechoso]]
[s]Esto... 夷me puedo ir a casa?[n][w][e]

[msg TV_NEWS_0123_400_00 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1067 65535 0][f 4 25 1 65535 0 0]Dejar huellas en la nieve...[n]斡Menudo novato! Nosotros[n]nunca har胤amos algo as胤.[n][w][e]

[msg TV_NEWS_0124_000_00 [Entrevistadora]]
[s]Mover el rey a 5-7... Jam茨s[n]se me habr胤a ocurrido[n]esa jugada en estas circunstancias.[n][w][e]

[msg TV_NEWS_0124_100_00 [Jugador profesional de shogi]]
[s]S胤, ha sido una sorpresa.[n]Mandar el rey a proteger el pe吋n...[n][w][e]
[s]Aunque, visto el panorama,[n]casi parece como ese castillo[n]flotante...[n][w][e]

[msg TV_NEWS_0124_200_00 [Entrevistadora]]
[s]Pero 夷ese castillo[n]no se acab吋 derrumbando?[n][w][e]

[msg TV_NEWS_0126_000_00 [Presentador de telediario]]
[s]Hoy, en El Consejero, escucharemos[n]algunas de las voces de la ciudad.[n][w][e]
[s]Se est茨 empezando a tener[n]en cuenta la profesi吋n, pero...[n][w][e]
[s]Hay gente que cree que ir[n]a terapia es vergonzoso[n]o solo para los d姻biles.[n][w][e]

[msg TV_NEWS_0126_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]No me extra隠a... Ese pensamiento es[n]el que hace que el d姻bil crea[n]que no deber胤a buscar ayuda.[n][w][e]

[msg TV_NEWS_0125_000_00 [Presentador de telediario]]
[s]Se especula que la ola de fr胤o[n]que afecta a Jap吋n[n]puede deberse al cambio clim茨tico.[n][w][e]
[s]El calentamiento global no se[n]refiere solo a un aumento[n]de las temperaturas.[n][w][e]
[s]Tambi姻n a olas de fr胤o,[n]aguaceros y otros fen吋menos[n]meteorol吋gicos extremos.[n][w][e]

[msg TV_NEWS_0125_100_00 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 1025 65535 0][f 4 25 1 65535 0 0]Haga el tiempo que haga,[n]los extremos nunca son buenos.[n][w][e]

[msg TV_NEWS_0127_000_00 [Presentador]]
[s]斡Hola! El tema de hoy es[n]el amor de a隠o nuevo. [n][w][e]
[s]Con la llegada del nuevo a隠o,[n]mucha gente se ha percatado[n]de notables mejor胤as en sus vidas.[n][w][e]

[msg TV_NEWS_0127_100_00 [Panelista]]
[s]Lo cierto es que mucha gente[n]de mi entorno[n]est茨 en la misma situaci吋n.[n][w][e]
[s]El a隠o pasado no consiguieron[n]trabajo, y de pronto, este a隠o[n]han logrado encontrar uno.[n][w][e]

[msg TV_NEWS_0128_000_00 [Narrador]]
[s]斡Los Feather Rangers consiguieron[n]su ataque especial para detener[n]la destrucci吋n del espacio-tiempo![n][w][e]
[s]Pero no podr茨n quedarse aqu胤.[n]A cambio, deber茨n volver[n]a su mundo y no retornar茨n jam茨s.[n][w][e]
[s]斡Su enardecida voluntad resonar茨[n]hasta en los cielos! 斡Revivid[n]y luchad, Phoenix Rangers![n][w][e]
[s]郁ltimo episodio...[n]或Hasta la pr吋xima位.[n][w][e]

[msg TV_NEWS_0130_000_00 [Detective ingenioso]]
[s]Es una pena. Cometiste[n]un error crucial al final.[n][w][e]

[msg TV_NEWS_0130_100_00 [Sospechoso joven]]
[s]No puede ser... Mi plan era perfecto...[n][w][e]

[msg TV_NEWS_0130_200_00 [Detective ingenioso]]
[s]No advertiste el fallo en tu plan[n]porque solo ve胤as tu propia[n]realidad perfecta, 夷me equivoco?[n][w][e]
[s]Y eso no te permiti吋 vislumbrar[n]el peor de los casos.[n][w][e]

[msg TV_NEWS_0130_300_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1166 65535 0][f 4 25 1 65535 0 0]Si solo piensas en el mejor[n]de los casos, no lograr茨s ver[n]la realidad de forma realista.[n][w][e]

[msg TV_NEWS_0131_000_00 [Presentador de telediario]]
[s]Solo quedan dos semanas para el D胤a[n]de San Valent胤n y ya se nota[n]en las tiendas de todo Jap吋n.[n][w][e]
[s]Los grandes almacenes[n]ofrecen art胤culos al alcance[n]de la clase media.[n][w][e]
[s]No obstante, hay quienes se oponen[n]a esta estrategia comercial[n]y pretenden boicotearla.[n][w][e]

[msg TV_NEWS_0131_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1019 65535 0][f 4 25 1 65535 0 0]夷Y t雨 qu姻? 夷Crees que te regalar茨n[n]algo de chocolate?[n][w][e]

[msg TV_NEWS_0201_000_00 [Presentador de telediario]]
[s]Hoy, en El Consejero, hablaremos[n]sobre los problemas que se dan[n]en los institutos.[n][w][e]
[s]El estr姻s y el acoso no afectan[n]solo a los adultos,[n]sino tambi姻n a los ni隠os.[n][w][e]
[s]A causa de la violencia y acoso[n]a manos de un profesor la primavera[n]pasada, los estudiantes se re雨nen...[n][w][e]

[msg TV_NEWS_0201_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 53101 65535 0][f 4 25 1 65535 0 0]Por eso fue Maruki[n]a tu instituto, 夷no?[n][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0][f 4 25 1 65535 0 0]Me entra hasta nostalgia al pensar[n]en ello. Las cosas ahora[n]van genial, pero...[n][w][e]

[msg TV_NEWS_0202_000_00 [Presentador de telediario]]
[s]Ahora vamos con el tiempo.[n][w][e]
[s]Tendremos una buena ma隠ana, pero[n]por la tarde comenzar茨 a nevar.[n][w][e]
[s]Ser茨 una fr胤a noche de invierno.[n][w][e]

[msg TV_NEWS_0202_100_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1156 65535 0][f 4 25 1 65535 0 0]Ma隠ana es nuestro gran d胤a[n]con Maruki. Tenlo todo listo.[n][w][e]

[msg TV_NEWS_0203_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月3日の番組内容[n][w][e]

[msg TV_NEWS_0203_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0204_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月4日の番組内容[n][w][e]

[msg TV_NEWS_0204_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0205_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月5日の番組内容[n][w][e]

[msg TV_NEWS_0205_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0206_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月6日の番組内容[n][w][e]

[msg TV_NEWS_0206_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0207_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月7日の番組内容[n][w][e]

[msg TV_NEWS_0207_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0208_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月8日の番組内容[n][w][e]

[msg TV_NEWS_0208_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0209_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月9日の番組内容[n][w][e]

[msg TV_NEWS_0209_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0210_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月10日の番組内容[n][w][e]

[msg TV_NEWS_0210_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0211_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月11日の番組内容[n][w][e]

[msg TV_NEWS_0211_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0212_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月12日の番組内容[n][w][e]

[msg TV_NEWS_0212_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0213_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月13日の番組内容[n][w][e]

[msg TV_NEWS_0213_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0214_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月14日の番組内容[n][w][e]

[msg TV_NEWS_0214_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0215_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月15日の番組内容[n][w][e]

[msg TV_NEWS_0215_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0216_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月16日の番組内容[n][w][e]

[msg TV_NEWS_0216_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0217_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月17日の番組内容[n][w][e]

[msg TV_NEWS_0217_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0218_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月18日の番組内容[n][w][e]

[msg TV_NEWS_0218_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0219_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月19日の番組内容[n][w][e]

[msg TV_NEWS_0219_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0220_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月20日の番組内容[n][w][e]

[msg TV_NEWS_0220_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0221_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月21日の番組内容[n][w][e]

[msg TV_NEWS_0221_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0222_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月22日の番組内容[n][w][e]

[msg TV_NEWS_0222_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0223_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月23日の番組内容[n][w][e]

[msg TV_NEWS_0223_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0224_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月24日の番組内容[n][w][e]

[msg TV_NEWS_0224_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0225_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月25日の番組内容[n][w][e]

[msg TV_NEWS_0225_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0226_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月26日の番組内容[n][w][e]

[msg TV_NEWS_0226_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0227_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月27日の番組内容[n][w][e]

[msg TV_NEWS_0227_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0228_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]2月28日の番組内容[n][w][e]

[msg TV_NEWS_0228_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0301_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月1日の番組内容[n][w][e]

[msg TV_NEWS_0301_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0302_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月2日の番組内容[n][w][e]

[msg TV_NEWS_0302_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0303_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月3日の番組内容[n][w][e]

[msg TV_NEWS_0303_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0304_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月4日の番組内容[n][w][e]

[msg TV_NEWS_0304_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0305_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月5日の番組内容[n][w][e]

[msg TV_NEWS_0305_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0306_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月6日の番組内容[n][w][e]

[msg TV_NEWS_0306_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0307_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月7日の番組内容[n][w][e]

[msg TV_NEWS_0307_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0308_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月8日の番組内容[n][w][e]

[msg TV_NEWS_0308_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0309_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月9日の番組内容[n][w][e]

[msg TV_NEWS_0309_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0310_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月10日の番組内容[n][w][e]

[msg TV_NEWS_0310_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0311_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月11日の番組内容[n][w][e]

[msg TV_NEWS_0311_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0312_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月12日の番組内容[n][w][e]

[msg TV_NEWS_0312_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0313_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月13日の番組内容[n][w][e]

[msg TV_NEWS_0313_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0314_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月14日の番組内容[n][w][e]

[msg TV_NEWS_0314_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0315_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月15日の番組内容[n][w][e]

[msg TV_NEWS_0315_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0316_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月16日の番組内容[n][w][e]

[msg TV_NEWS_0316_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0317_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月17日の番組内容[n][w][e]

[msg TV_NEWS_0317_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0318_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月18日の番組内容[n][w][e]

[msg TV_NEWS_0318_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0319_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月19日の番組内容[n][w][e]

[msg TV_NEWS_0319_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0320_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月20日の番組内容[n][w][e]

[msg TV_NEWS_0320_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0321_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月21日の番組内容[n][w][e]

[msg TV_NEWS_0321_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0322_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月22日の番組内容[n][w][e]

[msg TV_NEWS_0322_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0323_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月23日の番組内容[n][w][e]

[msg TV_NEWS_0323_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0324_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月24日の番組内容[n][w][e]

[msg TV_NEWS_0324_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0325_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月25日の番組内容[n][w][e]

[msg TV_NEWS_0325_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0326_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月26日の番組内容[n][w][e]

[msg TV_NEWS_0326_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0327_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月27日の番組内容[n][w][e]

[msg TV_NEWS_0327_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0328_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月28日の番組内容[n][w][e]

[msg TV_NEWS_0328_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0329_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月29日の番組内容[n][w][e]

[msg TV_NEWS_0329_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0330_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月30日の番組内容[n][w][e]

[msg TV_NEWS_0330_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_NEWS_0331_000_00 [Presentador de telediario]]
[s]※ダミーメッセージ[n]3月31日の番組内容[n][w][e]

[msg TV_NEWS_0331_100_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mu隠eco TV_NEWS_1224_100_00[n][w][e]

[msg TV_CH02_DEFAULT]
[s]Parece que el tiempo[n]de los pr吋ximos tres d胤as ser茨[n]○○××△△.[n][w][e]

[msg TV_WEATHER_PATTERN01 [Meteor吋loga]]
[s]Ma隠ana har茨 sol todo el d胤a.[n]Ser茨 un d胤a fant茨stico para[n]tender la colada al aire libre.[n][w][e]

[msg TV_WEATHER_PATTERN02 [Meteor吋loga]]
[s]Al parecer, ma隠ana har茨 sol[n]durante el d胤a, aunque puede[n]que haya nubes por la noche.[n][w][e]

[msg TV_WEATHER_PATTERN03 [Meteor吋loga]]
[s]Ma隠ana har茨 sol durante el d胤a,[n]pero parece que tendremos algo[n]de lluvia por la noche.[n][w][e]

[msg TV_WEATHER_PATTERN04 [Meteor吋loga]]
[s]Ma隠ana llover茨 a intervalos[n]durante el d胤a, pero de noche[n]el cielo se despejar茨.[n][w][e]

[msg TV_WEATHER_PATTERN05 [Meteor吋loga]]
[s]Por la tarde empezar茨n a aparecer[n]algunas nubes y el cielo[n]estar茨 un poco gris.[n][w][e]

[msg TV_WEATHER_PATTERN06 [Meteor吋loga]]
[s]Por la tarde empezar茨n a aparecer[n]algunas nubes, as胤 que podemos[n]esperar lluvia por la noche.[n][w][e]

[msg TV_WEATHER_PATTERN07 [Meteor吋loga]]
[s]A mediod胤a tendremos algunas nubes[n]repentinas. Si llueve,[n]ser茨 ya al ponerse el sol.[n][w][e]

[msg TV_WEATHER_PATTERN08 [Meteor吋loga]]
[s]Aparecer茨n nubes a mediod胤a que[n]traer茨n posibilidad de lluvia. El[n]cielo estar茨 nublado toda la noche.[n][w][e]

[msg TV_WEATHER_PATTERN09 [Meteor吋loga]]
[s]Tendremos una ma隠ana soleada,[n]pero habr茨 nubes por la tarde[n]y lluvia el resto del d胤a.[n][w][e]

[msg TV_WEATHER_PATTERN10 [Meteor吋loga]]
[s]Ma隠ana habr茨 nubes por la ma隠ana,[n]pero por la tarde se despejar茨[n]y tendremos sol el resto del d胤a.[n][w][e]

[msg TV_WEATHER_PATTERN11 [Meteor吋loga]]
[s]Las nubes se ir茨n por la tarde,[n]pero el tiempo estar茨 gris[n]la mayor parte del d胤a.[n][w][e]

[msg TV_WEATHER_PATTERN12 [Meteor吋loga]]
[s]El tiempo ser茨 un poco inestable[n]ma隠ana. El cielo estar茨 despejado[n]por la tarde y de noche llover茨.[n][w][e]

[msg TV_WEATHER_PATTERN13 [Meteor吋loga]]
[s]Ma隠ana estar茨 nublado todo el d胤a,[n]pero el cielo se despejar茨 por la[n]noche y podremos ver las estrellas.[n][w][e]

[msg TV_WEATHER_PATTERN14 [Meteor吋loga]]
[s]Ma隠ana habr茨 nubes todo el d胤a.[n]No llover茨, pero no se ver茨 el sol[n]y el d胤a estar茨 un poco gris.[n][w][e]

[msg TV_WEATHER_PATTERN15 [Meteor吋loga]]
[s]Por la ma隠ana habr茨 nubes y por[n]la noche seguramente llover茨.[n]斡No salgan de casa sin paraguas![n][w][e]

[msg TV_WEATHER_PATTERN16 [Meteor吋loga]]
[s]Habr茨 nubes por la ma隠ana y[n]seguramente llover茨 por la tarde.[n]Por la noche estar茨 despejado.[n][w][e]

[msg TV_WEATHER_PATTERN17 [Meteor吋loga]]
[s]Por el d胤a habr茨 nubes y lluvia.[n]La lluvia parar茨 por la noche,[n]pero no se ver茨n las estrellas.[n][w][e]

[msg TV_WEATHER_PATTERN18 [Meteor吋loga]]
[s]Ma隠ana por la ma隠ana estar茨 nublado[n]y llover茨 durante el resto del d胤a.[n]斡Tengan a mano el paraguas![n][w][e]

[msg TV_WEATHER_PATTERN19 [Meteor吋loga]]
[s]Ma隠ana por la ma隠ana llover茨,[n]pero se despejar茨 por la tarde.[n]Ser茨 un buen d胤a para salir.[n][w][e]

[msg TV_WEATHER_PATTERN20 [Meteor吋loga]]
[s]Llover茨 ma隠ana por la ma隠ana,[n]luego el cielo se despejar茨[n]y volver茨 a nublarse de noche.[n][w][e]

[msg TV_WEATHER_PATTERN21 [Meteor吋loga]]
[s]Tendremos lluvia por la ma隠ana,[n]que amainar茨 por la tarde[n]pero volver茨 otra vez de noche.[n][w][e]

[msg TV_WEATHER_PATTERN22 [Meteor吋loga]]
[s]Tendremos lluvia por la ma隠ana,[n]pero parar茨 por la tarde. De noche[n]podremos ver las estrellas.[n][w][e]

[msg TV_WEATHER_PATTERN23 [Meteor吋loga]]
[s]Ma隠ana llover茨 por la ma隠ana.[n]Los chubascos cesar茨n por la tarde,[n]pero el cielo seguir茨 encapotado.[n][w][e]

[msg TV_WEATHER_PATTERN24 [Meteor吋loga]]
[s]La lluvia volver茨 por la ma隠ana,[n]pero habr茨 un receso antes de las[n]nuevas precipitaciones nocturnas.[n][w][e]

[msg TV_WEATHER_PATTERN25 [Meteor吋loga]]
[s]Ma隠ana llover茨 todo el d胤a,[n]pero los cielos se despejar茨n[n]por la noche.[n][w][e]

[msg TV_WEATHER_PATTERN26 [Meteor吋loga]]
[s]Ma隠ana ser茨 un d胤a lluvioso. Las[n]precipitaciones cesar茨n por la[n]noche, pero persistir茨n las nubes.[n][w][e]

[msg TV_WEATHER_PATTERN27 [Meteor吋loga]]
[s]Ma隠ana llover茨 todo el d胤a,[n]desde la ma隠ana hasta la noche.[n]M茨s vale no guardar los paraguas.[n][w][e]

[msg MSG_TV_SHOPPING_TUTO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]Oh, es el canal de teletienda[n]del que habla todo el mundo.[n][w][e]

[msg MND_TV_SHOPPING_TUTO]
[s]Es el canal de la teletienda.[n][w][e]

[msg TV_SHOPPING_START_00 [Presentador]]
[s]斡Hola a todos! 斡Ha llegado la hora[n]de hacer algunas compras![n][w][e]
[s]斡Esto es lo que tenemos[n]hoy para ustedes![n][w][e]

[msg TV_SHOPPING_START_01 [Presentador]]
[s]斡Este es un producto limitado![n]斡Estar茨 disponible solo hoy[n]y nada m茨s que hoy![n][w][e]
[s]斡Y puede ser suyo por un precio[n]incre胤blemente m吋dico![n]斡Me lo quitan de las manos![n][w][e]

[msg TV_SHOPPING_START_02 [Presentadora]]
[s]Oh, 斡no damos abasto[n]con tantas llamadas![n][w][e]

[msg TV_SHOPPING_START_03 [Presentador]]
[s]斡Solo quedan unos pocos![n]斡Es su oportunidad de comprar,[n]comprar, comprar![n][w][e]

[msg TV_SHOPPING_START_04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0][f 4 25 1 65535 0 0]Si es cierto que los tel姻fonos[n]no dejan de sonar, si compramos[n]uno, el otro se agotar茨 entretanto.[n][w][e]

[msg TV_SHOPPING_START_04_2nd [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1168 65535 0][f 4 25 1 65535 0 0]Qu姻 de productos populares.[n]A este paso,[n]solo podremos conseguir uno.[n][w][e]

[msg TV_SHOPPING_BUY_00 [Presentadora]]
[s]Oh, 斡acabamos de recibir[n]una llamada de otro comprador![n]斡Much胤simas gracias![n][w][e]

[msg TV_SHOPPING_BUY_00_0 [Presentadora]]
[s]斡Vaya! 斡夷Se han agotado los dos?![n]斡El 雨ltimo cliente ha tenido[n]much胤sima suerte![n][w][e]

[msg TV_SHOPPING_BUY_01 [Presentador]]
[s]斡Trataremos de enviarle[n]su pedido lo antes posible![n][w][e]
[s]斡Hasta otra! 斡Nos vemos pronto[n]con m茨s productos fabulosos![n][w][e]

[msg TV_SHOPPING_BUY_02 [Presentadora]]
[s]斡Hasta otra![n][w][e]

[msg MSG_TV_SHOPPING_NotBuy [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1170 65535 0][f 4 25 1 65535 0 0]As胤 que solo est茨 de oferta hoy...[n]Si de verdad lo quieres, podr茨s[n]conseguir por lo menos uno.[n][w][e]

[msg MSG_TV_SHOPPING_BUY_END [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1172 65535 0][f 4 25 1 65535 0 0]Ahora solo tenemos[n]que esperar a que llegue.[n][w][e]

[msg MND_TV_SHOPPING_BUY_END]
[s]Ahora solo tengo que esperar[n]a que llegue.[n][w][e]

[msg MSG_ALLREADY_VIEW [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1171 65535 0][f 4 25 1 65535 0 0]夷No est茨s esperando un pedido?[n]斡Estoy deseando que llegue![n][w][e]

[msg MND_ALLREADY_VIEW]
[s]Ya he realizado el pedido.[n]Ahora solo tengo que esperar[n]a que llegue.[n][w][e]

[msg MND_TV_SHOPPING_KYANSERU]
[s]No deber胤a dar[n]ning雨n regalo por el momento.[n][w][e]

[msg TV_SHOPPING_ITEM_Woman_C [Presentadora]]
[s]斡Vaya! 斡Son unos art胤culos tan[n]buenos que no s姻 cu茨l escoger![n][w][e]

[msg TV_SHOPPING_ITEM_0424_01 [Presentador]]
[s]Les presento[n]el [clr 3]lote primaveral del despertar[clr 27].[n]斡Digan adi吋s a todo letargo![n][w][e]
[s]Incluye: [clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1], y[n][w][e]
[s]斡[clr 2][var 10][clr 27] [f 2 5 3 9999 2]![n]斡Qu姻 ofert吋n![n][w][e]
[s]斡Y eso no es todo![n][w][e]
[s]Nuestro siguiente art胤culo es el [clr 3]lote de[n]raciones primaverales[clr 27]. 斡Para quienes se[n]preocupan por su salud y aguante![n][w][e]
[s][clr 2][var 12][clr 27] [f 2 5 3 9999 4],[n][clr 2][var 13][clr 27] [f 2 5 3 9999 5],[n]y...[n][w][e]
[s]斡[clr 2][var 14][clr 27] [f 2 5 3 9999 6]! 斡Todo en uno![n][w][e]

[msg TV_SHOPPING_ITEM_0501_01 [Presentador]]
[s][clr 3]Raci吋n de supervivencia[clr 27].[n]Obtengan nutrientes para no[n]pelear con el est吋mago vac胤o.[n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1],[n]y...[n][w][e]
[s]斡[clr 2][var 10][clr 27] [f 2 5 3 9999 2]! 斡Todo en uno![n]斡Menudo ofert吋n![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Lote ejercitam雨sculos[clr 27].[n]Notar茨n una gran mejor胤a[n]en su entrenamiento. Incluye[n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_0508_01 [Presentador]]
[s]Pasamos al [clr 3]lote de relajaci吋n[clr 27].[n]Todo lo que necesitan para[n]cuando no se encuentren muy bien.[n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1],[n]y...[n][w][e]
[s]斡[clr 2][var 10][clr 27] [f 2 5 3 9999 2]! 斡夷Lo est茨n viendo?![n]斡Me lo quitan de las manos![n][w][e]
[s]斡Y eso no es todo! 斡Hay m茨s![n][w][e]
[s][clr 3]Lote de bionutrientes[clr 27],[n]para quienes tienen buena[n]mano para la jardiner胤a.[n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_0515_01 [Presentador]]
[s]Primero, el [clr 3]lote antialergia[clr 27],[n]ideal para quienes est茨n[n]hartos de encontrarse mal.[n][w][e]
[s]斡[clr 2][var 8][clr 27] [f 2 5 3 9999 0][n]y [clr 2][var 9][clr 27] [f 2 5 3 9999 1]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Regalo de salud[clr 27],[n]斡perfecto para quienes[n]buscan paz mental![n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_0522_01 [Presentador]]
[s]斡Vamos a ello! [clr 3]Lote aumento de m雨sculo[clr 27],[n]斡un estimulante perfecto para antes[n]de ir al trabajo![n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1],[n]y...[n][w][e]
[s][clr 2][var 10][clr 27] [f 2 5 3 9999 2], 斡todo en uno![n][w][e]
[s]斡Y eso no es todo! 斡Todav胤a tenemos[n]mucho que ense隠arle![n][w][e]
[s][clr 3]Kit para exteriores[clr 27]. Domine el[n]fuego, el hielo y la electricidad[n]y sea un maestro de la acampada.[n][w][e]
[s][clr 2][var 12][clr 27] [f 2 5 3 9999 4],[n][clr 2][var 13][clr 27] [f 2 5 3 9999 5],[n]y...[n][w][e]
[s][clr 2][var 14][clr 27] [f 2 5 3 9999 6], 斡todo en uno![n]Imposible mejorar la oferta.[n][w][e]

[msg TV_SHOPPING_ITEM_0529_01 [Presentador]]
[s][clr 3]Lote de regalos japoneses[clr 27].[n]斡Demuestre su amor[n]por Jap吋n con estos art胤culos![n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1],[n]y...[n][w][e]
[s][clr 2][var 10][clr 27] [f 2 5 3 9999 2]. 斡Todo en uno![n]斡No lo dej姻is escapar![n][w][e]
[s]Y eso no es todo, 斡a雨n hay m茨s![n][w][e]
[s][clr 3]Lote de biombos[clr 27].[n]Con esto, el viento y los rayos[n]ya no ser茨n tan terror胤ficos.[n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_0619_01 [Presentador]]
[s]斡El primero! [clr 3]Lote de regalos de apoyo[clr 27].[n]斡Les ayudar茨 a sobrellevar[n]mejor su atareada vida![n][w][e]
[s]斡[clr 2][var 8][clr 27] [f 2 5 3 9999 0][n]y [clr 2][var 9][clr 27] [f 2 5 3 9999 1]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]
[s]斡Y eso no es todo! 斡Hay m茨s![n][w][e]
[s][clr 3]Lote del 雨ltimo empuj吋n[clr 27].[n]斡Nada podr茨 con ustedes![n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_0626_01 [Presentador]]
[s]Tenemos el [clr 3]lote de poderes oscuros[clr 27].[n]Con tales poderes misteriosos,[n]斡夷qu姻 caminos se le abrir茨n?![n][w][e]
[s]斡[clr 2][var 8][clr 27] [f 2 5 3 9999 0][n]y [clr 2][var 9][clr 27] [f 2 5 3 9999 1]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Lote de herramientas malditas[clr 27].[n]P-para aquellos con ganas[n]de maldecir a alguien...[n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_0703_01 [Presentador]]
[s]斡Mirad! [clr 3]Lote de culturismo[clr 27].[n]La vida es muy dura,[n]as胤 que 斡endurezca sus m雨sculos![n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1],[n]y...[n][w][e]
[s]斡[clr 2][var 10][clr 27] [f 2 5 3 9999 2]! 斡Todo en uno![n]Menuda maravilla.[n][w][e]
[s]斡Y eso no es todo! 斡Hay m茨s![n][w][e]
[s][clr 3]Lote de relajaci吋n mental[clr 27].[n]斡Experimenten sus beneficios![n][w][e]
[s][clr 2][var 12][clr 27] [f 2 5 3 9999 4],[n][clr 2][var 13][clr 27] [f 2 5 3 9999 5],[n]y...[n][w][e]
[s]斡[clr 2][var 14][clr 27] [f 2 5 3 9999 6]![n]斡Qu姻 pedazo de ganga![n][w][e]

[msg TV_SHOPPING_ITEM_0807_01 [Presentador]]
[s][clr 3]Lote de Ladr吋n Fantasma[clr 27].[n]斡Usted tambi姻n puede ser un Ladr吋n[n]Fantasma y despertar corazones![n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1],[n]y...[n][w][e]
[s]斡[clr 2][var 10][clr 27] [f 2 5 3 9999 2]! 斡Todo en uno![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s]Ahora, les presentamos[n]el [clr 3]lote heroico[clr 27].[n]斡Todo el mundo puede ser un h姻roe![n][w][e]
[s][clr 2][var 12][clr 27] [f 2 5 3 9999 4],[n][clr 2][var 13][clr 27] [f 2 5 3 9999 5],[n]y...[n][w][e]
[s]斡[clr 2][var 14][clr 27] [f 2 5 3 9999 6]![n]斡Todo en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_0814_01 [Presentador]]
[s]Traemos un [clr 3]lote de bebidas[clr 27].[n]斡Refr姻squese en este calor estival![n][w][e]
[s]斡[clr 2][var 8][clr 27] [f 2 5 3 9999 0][n]y [clr 2][var 9][clr 27] [f 2 5 3 9999 1]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]
[s]斡Y eso no es todo! 斡Todav胤a tenemos[n]mucho que ense隠arle![n][w][e]
[s][clr 3]Lote de regalos florales[clr 27].[n]斡Un regalo estupendo para[n]los amantes de las flores![n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_0925_01 [Presentador]]
[s][clr 3]Lote de Ladr吋n Fantasma 2[clr 27].[n]斡Con la m茨scara,[n]ser茨 un Ladr吋n Fantasma![n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1],[n]y...[n][w][e]
[s][clr 2][var 10][clr 27] [f 2 5 3 9999 2],[n]斡todo en uno![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Lote divertido de Ladr吋n[clr 27].[n]斡A los fans les 或fanscinar茨位![n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_1002_01 [Presentador]]
[s]Comencemos con el[n][clr 3]lote de fantasma calabaza[clr 27].[n]斡Consigan el esp胤ritu de Halloween![n][w][e]
[s]斡[clr 2][var 8][clr 27] [f 2 5 3 9999 0][n]y [clr 2][var 9][clr 27] [f 2 5 3 9999 1]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]
[s]斡Y eso no es todo! 斡Todav胤a tenemos[n]mucho que ense隠arle![n][w][e]
[s][clr 3]Lote antifantasmas[clr 27].[n]夷No le gusta el esp胤ritu de[n]Halloween? 斡M茨ndelo a tomar viento![n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_1106_01 [Presentador]]
[s][clr 3]Lote de ung鵜entos fuertes[clr 27].[n]斡Mejor prevenir que curar![n][w][e]
[s]斡[clr 2][var 8][clr 27] [f 2 5 3 9999 0][n]y [clr 2][var 9][clr 27] [f 2 5 3 9999 1]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Lote de m雨sculo interior[clr 27].[n]Mientras lo tenga,[n]no le faltar茨 fortaleza interior.[n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_1113_01 [Presentador]]
[s]Vamos all茨: [clr 3]Lote de instaespr茨is[clr 27].[n]斡Adi吋s, g姻rmenes![n]斡Desh茨gase de ellos con este lote![n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1],[n]y...[n][w][e]
[s]斡[clr 2][var 10][clr 27] [f 2 5 3 9999 2]![n]夷Acaso estoy so隠ando? 斡Este ofert吋n[n]es demasiado bueno para ser cierto![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Lote de meditaci吋n[clr 27]. 斡Su ex吋tico aroma[n]le dar茨 una infinidad de posibilidades![n][w][e]
[s][clr 2][var 12][clr 27] [f 2 5 3 9999 4],[n][clr 2][var 13][clr 27] [f 2 5 3 9999 5],[n]y...[n][w][e]
[s]斡[clr 2][var 14][clr 27] [f 2 5 3 9999 6]![n]斡Imposible! 斡Espero que no dejen[n]pasar estas gangas![n][w][e]

[msg TV_SHOPPING_ITEM_1127_01 [Presentador]]
[s][clr 3]Lote de boniatos[clr 27].[n]斡El oto隠o ya est茨 aqu胤! 斡Coman[n]boniato y aumenten su aguante![n][w][e]
[s]斡[clr 2][var 8][clr 27] [f 2 5 3 9999 0][n]y [clr 2][var 9][clr 27] [f 2 5 3 9999 1]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Lote de dulces especiales[clr 27].[n]斡Es su oportunidad de conseguir[n]algo tan especial![n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg TV_SHOPPING_ITEM_1211_01 [Presentador]]
[s][clr 3]Lote de superdepuraci吋n[clr 27].[n]斡Elimine todas las toxinas[n]de su cuerpo![n][w][e]
[s]斡[clr 2][var 8][clr 27] [f 2 5 3 9999 0][n]y [clr 2][var 9][clr 27] [f 2 5 3 9999 1]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Lote de magatamas[clr 27].[n]斡Fuego! 斡Hielo! 斡Viento![n]斡Electricidad! 斡Dominen el mundo![n][w][e]
[s][clr 2][var 12][clr 27] [f 2 5 3 9999 4],[n][clr 2][var 13][clr 27] [f 2 5 3 9999 5]...[n][w][e]
[s]斡[clr 2][var 14][clr 27] [f 2 5 3 9999 6], y[n][clr 2][var 15][clr 27] [f 2 5 3 9999 7]![n][w][e]
[s]斡夷Todos estos art胤culos en uno?![n]斡Me lo van a quitar de las manos![n][w][e]

[msg TV_SHOPPING_ITEM_0115_01 [Presentador]]
[s]Para empezar, tenemos las [clr 3]mochilas[n]de la suerte para trabajadores[clr 27].[n]斡Venzan al estr姻s y vuelvan a tope![n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1],[n]y...[n][w][e]
[s][clr 2][var 10][clr 27] [f 2 5 3 9999 2], 斡todo en uno![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Mochila de la suerte fortalecedora[clr 27].[n]Mejore su cuerpo y mente[n]incluso con actividades diarias.[n][w][e]
[s][clr 2][var 12][clr 27] [f 2 5 3 9999 4],[n][clr 2][var 13][clr 27] [f 2 5 3 9999 5],[n]y...[n][w][e]
[s]斡[clr 2][var 14][clr 27] [f 2 5 3 9999 6]! 斡Todos[n]estos art胤culos son una ganga![n]斡Compren antes de que vuelen![n][w][e]

[msg TV_SHOPPING_ITEM_0122_01 [Presentador]]
[s]Les presentamos el [clr 3]lote[n]de talismanes[clr 27], 斡perfecto[n]para darles suerte![n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1],[n]y...[n][w][e]
[s][clr 2][var 10][clr 27] [f 2 5 3 9999 2],[n]斡todo en uno![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Lote de dulces deliciosos[clr 27].[n]斡Una explosi吋n de dulce que[n]repone salud con muchas calor胤as![n][w][e]
[s][clr 2][var 12][clr 27] [f 2 5 3 9999 4],[n][clr 2][var 13][clr 27] [f 2 5 3 9999 5],[n]y...[n][w][e]
[s]斡[clr 2][var 14][clr 27] [f 2 5 3 9999 6]![n]斡夷Se lo pueden creer?![n]斡Todo en uno![n][w][e]

[msg TV_SHOPPING_ITEM_0129_01 [Presentador]]
[s][clr 3]Lote regenerador de energ胤a[clr 27].[n]斡Despierten a su cuerpo![n]斡Vivan sus sue隠os![n][w][e]
[s][clr 2][var 8][clr 27] [f 2 5 3 9999 0],[n][clr 2][var 9][clr 27] [f 2 5 3 9999 1]...[n][w][e]
[s]斡[clr 2][var 10][clr 27] [f 2 5 3 9999 2], y[n][clr 2][var 11][clr 27] [f 2 5 3 9999 3]![n][w][e]
[s]斡夷Todos estos art胤culos en uno?![n]斡Esto s胤 que es una ganga![n][w][e]
[s]Pero 斡todav胤a hay m茨s![n][w][e]
[s][clr 3]Lote superdelicioso resurrector[clr 27].[n]斡Est茨 tan bueno que puede[n]revivir a cualquiera![n][w][e]
[s]斡[clr 2][var 12][clr 27] [f 2 5 3 9999 4][n]y [clr 2][var 13][clr 27] [f 2 5 3 9999 5]![n][w][e]
[s]斡Los dos art胤culos en uno![n]斡Esto s胤 que es una ganga![n][w][e]

[msg MSG_SPOT_OPEN_INOKASIRA_ [Presentador de telediario]]
[s]Un mes despu姻s de la resoluci吋n del[n]asesinato del grupo de teatro, la[n]paz ha vuelto al Parque Inokashira.[n][w][e]
[s]Aunque est茨 cerrado temporalmente,[n]la gente ha vuelto a visitarlo[n]desde que detuvieron al sospechoso.[n][w][e]
[s]Como era habitual, no es raro[n]ver a actores ensayando[n]en el parque.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASIRA__2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]夷La se隠orita Ann no estaba buscando[n]un sitio donde ensayar[n]sin que la observe la gente?[n][w][e]
[s]夷Por qu姻 no le dices que vaya[n]al Parque Inokashira? Me suena que[n]all胤 van muchos actores a ensayar.[n][w][e]

[msg HELP_SPOT_OPEN_INOKASIRA]
[s]Ahora conoces el Parque Inokashira.[n][w][e]

[msg CAFE_TV_KAMOSIDA_NEWS00]
[s]Parece que est茨n hablando sobre[n]Kamoshida en las noticias.[n][w][e]

[msg CAFE_TV_KAMOSIDA_NEWS01 [Locutor]]
[s]Pasemos a la siguiente noticia.[n][w][e]
[s]Se ha descubierto que un atleta[n]ol胤mpico retirado que ejerc胤a como[n]profesor agred胤a a sus estudiantes.[n][w][e]
[s]Muchas personas han expresado su[n]descontento con el comit姻 educativo[n]en relaci吋n con este esc茨ndalo.[n][w][e]

[msg CAFE_TV_KAMOSIDA_NEWS02 [Hombre arrogante]]
[s]No solo eso, sino que hay personas[n]que se cuestionan el modelo[n]educativo de todo el pa胤s.[n][w][e]

[msg CAFE_TV_KAMOSIDA_NEWS03 [Mujer arrogante]]
[s]斡S胤! 夷Qu姻 est茨 haciendo[n]el gobierno?[n][w][e]

[msg CAFE_TV_KAMOSIDA_NEWS04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]El comit姻 educativo y el gobierno...[n]Est茨n hablando de temas[n]muy complicados.[n][w][e]

[msg CAFE_TV_KAMOSIDA_NEWS_AF]
[s]Las noticias solo cuentan medias[n]verdades sobre el asunto[n]de Kamoshida.[n][w][e]

[msg CAFE_TV_OKUMURA_NEWS_00_ [Presentador de telediario]]
[s]Okumura Foods ha recibido numerosas[n]denuncias debido a sus deplorables[n]condiciones laborales.[n][w][e]
[s]Hace poco, alguien se infiltr吋[n]en la sede central y tuvieron que[n]llamar a una empresa de seguridad.[n][w][e]
[s]En una entrevista, su CEO insisti吋[n]en que ese incidente no estaba[n]relacionado con la ola de cr胤ticas.[n][w][e]

[msg CAFE_TV_OKUMURA_NEWS_00__2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Es tal y como dijo Futaba.[n]斡Ahora deber胤amos avanzar algo![n][w][e]

[msg CAFE_TV_OKUMURA_NEWS_01_ [Presentador de telediario]]
[s]El presidente de Okumura Foods[n]ha recibido un aviso de los[n]Ladrones Fantasma en su casa.[n][w][e]
[s]En internet circulan todo tipo[n]de teor胤as sobre las exigencias[n]incluidas en el aviso.[n][w][e]
[s]Todo el mundo est茨 pendiente de los[n]Ladrones Fantasma, y quieren saber[n]cu茨l ser茨 su pr吋ximo movimiento.[n][w][e]

[msg CAFE_TV_OKUMURA_NEWS_01__2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 53105 65535 0][f 4 25 1 65535 0 0]Ya nos hemos ocupado de eso. Ahora[n]solo debemos esperar a ver[n]qu姻 pasa.[n][w][e]

[msg CAFE_TV_OKUMURA_NEWS_02_ [Presentador de telediario]]
[s]Okumura Foods est茨 en boca de todos[n]tras haber recibido un aviso[n]de [f 4 28].[n][w][e]
[s]Desde que se envi吋 el aviso, muchas[n]personas han exigido un castigo[n]para el presidente Okumura.[n][w][e]
[s]El susodicho a雨n no ha hecho[n]ninguna declaraci吋n, por lo que[n]no se sabe c吋mo ha reaccionado.[n][w][e]

[msg CAFE_TV_OKUMURA_NEWS_02__2 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 53105 65535 0][f 4 25 1 65535 0 0]Hemos hecho todo lo posible.[n]Ahora solo nos queda esperar.[n][w][e]

[msg CAFE_Q79_NEWS_00_00 [Presentador de telediario]]
[s]La v胤ctima es un hombre que est茨[n]bajo custodia por agresi吋n.[n]A雨n se desconoce lo que sucedi吋.[n][w][e]
[s]La polic胤a especula que esto[n]guarda relaci吋n con su caso[n]y contin雨a con la investigaci吋n.[n][w][e]

[msg CAFE_Q79_NEWS_01_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1192 65535 0][f 4 25 1 65535 0 0]As胤 que alguien se col吋[n]en casa de Toji... 夷Crees[n]que se trata de una coincidencia?[n][w][e]

[msg RNK_UP2]
[s]斡Ahora puedo afrontar[n]desaf胤os mayores![n][w][e]

[msg PARAM_UP2]
[s]Parece que he mejorado[n]mi [f 4 11 0][clr 26][f 4 12 0][clr 27].[n][w][e]

