[sel PLAYGO_CHOICE_SEL top]
[s]Return to title[e]
[s]Save and return to title[e]
[s]Wait for data preparation[e]

[msg PLAYGO_NOT_DOWNLOAD]
[s]You must have data prepared in[n]order to continue from here.[n][w][e]

[msg PLAYGO_LOCAL_SLOW]
[s]You must have data prepared in[n]order to continue from here.[n][w][e]

[msg PLAYGO_GOTO_TILE]
[s]This will return you to the[n]title screen. Is that OK?[n][w][e]

[sel PLAYGO_GOTO_TITLE_SEL top]
[s]Yes[e]
[s]No[e]

[msg PLAYGO_INSTALL_PROGRESS]
[s]Please wait for installation to complete.[n][var 0]/[var 1] ([var 2])[n][w][e]

