[msg TEST_000]
[s]スクリプトから発行した[n]メッセージです。[n][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Lo has o胤do?[n]Es una hamburguesa gigantesca.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Pinta bien.[e]
[s]No me interesa.[e]
[s]Seguro que me sienta mal.[e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Bien dicho![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Los Ladrones Fantasma necesitan [f 4 11 3][clr 26][f 4 12 3][clr 27]Coraje[n]para afrontar[n]lo que sea. Deber胤amos ir un d胤a.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No seas as胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Los Ladrones Fantasma necesitan [f 4 11 3][clr 26][f 4 12 3][clr 27][n]para afrontar[n]lo que sea. Deber胤amos ir un d胤a.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Basta de quejas![n]斡Los j吋venes zamp茨is de todo![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Los Ladrones Fantasma necesitan [f 4 11 3][clr 26][f 4 12 3][clr 27][n]para afrontar[n]lo que sea. Deber胤amos ir un d胤a.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 clase de libros[n]tendr茨n en la librer胤a que hay[n]bajo la estaci吋n de Shibuya?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Vamos a echar un ojo.[e]
[s]夷Quieres revistas para mascotas?[e]
[s]No me gustan los libros.[e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷En serio te gusta leer?[n]Es un buen h茨bito.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ganar [f 4 11 0][clr 26][f 4 12 0][clr 27][n]en el d胤a a d胤a es importante.[n]斡Vamos a comprar libros![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No, 夷y a qui姻n llamas t雨 mascota?[n]Tsss.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ganar [f 4 11 0][clr 26][f 4 12 0][clr 27][n]en el d胤a a d胤a es importante.[n]斡Vamos a comprar libros![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Venga, que un estudiante[n]deber胤a disfrutar de la lectura.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ganar [f 4 11 0][clr 26][f 4 12 0][clr 27][n]en el d胤a a d胤a es importante.[n]斡Vamos a comprar libros![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mmm, puede que consigamos[n]una receta m姻dica.[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Est茨 bien saberlo.[e]
[s]夷Por qu姻 nos hacen falta?[e]
[s]A m胤 no me hacen falta.[e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Son geniales para curarse.[n]Tenerlos ayuda bastante[n]a la hora de explorar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero necesitamos un m姻dico[n]dispuesto a darnos las recetas.[n]Creo que conozco a alguien.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤, nos han sido muy 雨tiles.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero necesitamos un m姻dico[n]dispuesto a darnos las recetas.[n]Creo que conozco a alguien.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No subestimes los Palacios.[n]No tienes ni idea de lo 雨tiles[n]que son los objetos de curaci吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero necesitamos un m姻dico[n]dispuesto a darnos las recetas.[n]Creo que conozco a alguien.[n][f 1 3 65535][w][e]

[msg MSG_BEING_TOGETHER_RYU [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7005 65535 0]Buenos d胤as, [f 4 2].[n]夷Qu姻 hac姻is aqu胤?[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vayamos al instituto juntos.[n]Est茨 justo ah胤, pero bueno.[n][f 1 3 65535][w][e]

[msg MSG_BEING_TOGETHER_ANN [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6005 65535 0]Ah, hola, [f 4 2]. 斡Buenos d胤as![n]夷Eh? 夷Hay algo ah胤?[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Venga, v茨monos o llegaremos tarde.[n][f 1 3 65535][w][e]

[msg MSG_BEING_TOGETHER_MKT [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2005 65535 0]Buenos d胤as, [f 4 2].[n]夷Qu姻 est茨s mirando?[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]V茨monos. Si no nos damos prisa,[n]llegaremos tarde.[n][f 1 3 65535][w][e]

[msg MSG_BEING_TOGETHER_HAR [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53512 65535 0]Buenos d胤as, [f 4 2] y Mona.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]V茨monos. Hoy debemos esforzarnos[n]al m茨ximo.[n][f 1 3 65535][w][e]

[msg MSG_BEING_TOGETHER_KSM [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57005 65535 0]斡Buenos d胤as, [f 4 1]![n]Qu姻 bien que haya dejado de llover.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aunque me gustar胤a m茨s[n]que el cielo se despejase.[n][f 1 3 65535][w][e]

[msg MSG_BEING_TOGETHER_SMR [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57005 65535 0]斡Buenos d胤as, [f 4 1]![n]Qu姻 bien que haya dejado de llover.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aunque me gustar胤a m茨s[n]que el cielo se despejase.[n][f 1 3 65535][w][e]

[msg MSG_BEING_TOGETHER_MSM [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 19005 65535 0]Buenos d胤as, [f 4 1].[n]夷C吋mo est茨s?[n][f 1 3 65535][w][e]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Vamos a clase juntos?[n]Como somos amigos,[n]no te importar茨, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_BEING_TOGETHER_KSM07 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57005 65535 0]斡Buenos d胤as, [f 4 1]![n]Tenemos suerte de que haga[n]tan buen d胤a hoy.[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0]Me preocupaba perderme[n]el entrenamiento matutino, pero[n]contigo aqu胤 no tendr姻 problema.[n][f 1 3 65535][w][e]

