[msg item_000]
[s]En blanco[n][e]

[msg Item_001]
[s]Gafas con montura negra[n]que te hacen parecer inteligente.[n][e]

[msg Item_002]
[s]Tirantes que pegan[n]con un atuendo casual.[n][e]

[msg Item_003]
[s]Ri隠onera en la que pueden[n]guardarse objetos peque隠os.[n][e]

[msg Item_004]
[s]Accesorio sencillo[n]que sirve para sujetar el pelo.[n][e]

[msg Item_005]
[s]Llavero cl茨sico[n]ba隠ado en plata.[n][e]

[msg Item_006]
[s]Medias negras y gruesas.[n][e]

[msg Item_007]
[s]Medias con lunares hechas[n]en el extranjero.[n][e]

[msg Item_008]
[s]Para los verdaderos amantes[n]del sonido de alta calidad.[n][e]

[msg Item_009]
[s]Corbata formal[n]para eventos elegantes.[n][e]

[msg Item_00A]
[s]RESERVE[n][e]

[msg Item_00B]
[s]Da vida a cualquier[n]atuendo.[n][e]

[msg Item_00C]
[s]Le da energ胤a a[n]cualquier atuendo.[n][e]

[msg Item_00D]
[s]Mejora mucho[n]la vitalidad.[n][e]

[msg Item_00E]
[s]RESERVE[n][e]

[msg Item_00F]
[s]RESERVE[n][e]

[msg Item_010]
[s]RESERVE[n][e]

[msg Item_011]
[s]Una gargantilla[n]que abre los chakras.[n][e]

[msg Item_012]
[s]Gargantilla que fortalece[n]la mente.[n][e]

[msg Item_013]
[s]Gargantilla que fortalece[n]el alma.[n][e]

[msg Item_014]
[s]RESERVE[n][e]

[msg Item_015]
[s]RESERVE[n][e]

[msg Item_016]
[s]RESERVE[n][e]

[msg Item_017]
[s]Pulsera que potencia[n]los ataques de fuego.[n][e]

[msg Item_018]
[s]Pulsera que potencia[n]los ataques de hielo.[n][e]

[msg Item_019]
[s]Pulsera que potencia[n]los ataques de viento.[n][e]

[msg Item_01A]
[s]Una faja amarilla[n]que fortalece los ataques[n]el姻ctricos.[n][e]

[msg Item_01B]
[s]Collar de calabaza que[n]potencia los atq. de fuego.[n][e]

[msg Item_01C]
[s]RESERVE[n][e]

[msg Item_01D]
[s]RESERVE[n][e]

[msg Item_01E]
[s]RESERVE[n][e]

[msg Item_01F]
[s]Un brazalete con forma de estrella[n]que fortalece los ataques nucleares.[n][e]

[msg Item_020]
[s]Pulsera que potencia[n]los ataques psicoquin姻ticos.[n][e]

[msg Item_021]
[s]Pulsera que potencia[n]los ataques de bendici吋n.[n][e]

[msg Item_022]
[s]Pulsera que potencia[n]los ataques de maldici吋n.[n][e]

[msg Item_023]
[s]RESERVE[n][e]

[msg Item_024]
[s]RESERVE[n][e]

[msg Item_025]
[s]RESERVE[n][e]

[msg Item_026]
[s]RESERVE[n][e]

[msg Item_027]
[s]Pulsera que proporciona[n]una pasi吋n ardiente.[n][e]

[msg Item_028]
[s]Un cintur吋n de colores brillantes.[n]Quiz茨 te miren raro[n]cuando lo lleves puesto.[n][e]

[msg Item_029]
[s]RESERVE[n][e]

[msg Item_02A]
[s]Collar con cierre[n]magn姻tico.[n][e]

[msg Item_02B]
[s]Corbata inspiradora.[n][e]

[msg Item_02C]
[s]Tirantes que sujetan[n]cualquier cosa.[n][e]

[msg Item_02D]
[s]Un cintur吋n que te hace[n]sentir m茨s fuerte.[n][e]

[msg Item_02E]
[s]Casta隠uelas que extinguen[n]el fuego.[n][e]

[msg Item_02F]
[s]Bolsa de goma rellena[n]de agua caliente.[n][e]

[msg Item_030]
[s]Guantes que previenen[n]la electrificaci吋n.[n][e]

[msg Item_031]
[s]Gafas que protegen los ojos[n]de cualquier da隠o.[n][e]

[msg Item_032]
[s]M茨scara que relaja[n]de forma natural.[n][e]

[msg Item_033]
[s]Zuecos de madera. Hace[n]falta coraje para usarlos.[n][e]

[msg Item_034]
[s]Cuaderno en el que[n]escribir recordatorios.[n][e]

[msg Item_035]
[s]Capa que sacia.[n][e]

[msg Item_036]
[s]Gema m茨gica que previene[n]el sue隠o.[n][e]

[msg Item_037]
[s]Capa que relaja cuando[n]se lleva puesta.[n][e]

[msg Item_038]
[s]Capa que transmite[n]esperanza.[n][e]

[msg Item_039]
[s]RESERVE[n][e]

[msg Item_03A]
[s]Cinta para el pelo[n]que despeja la mente.[n][e]

[msg Item_03B]
[s]Amuleto que protege[n]contra las quemaduras.[n][e]

[msg Item_03C]
[s]Amuleto que protege[n]contra la congelaci吋n.[n][e]

[msg Item_03D]
[s]Amuleto que ayuda a golpear[n]como un campe吋n.[n][e]

[msg Item_03E]
[s]Amuleto que protege[n]contra la electricidad.[n][e]

[msg Item_03F]
[s]RESERVE[n][e]

[msg Item_040]
[s]Una capa misteriosa que[n]te permite olvidar tu miedo.[n][e]

[msg Item_041]
[s]RESERVE[n][e]

[msg Item_042]
[s]RESERVE[n][e]

[msg Item_043]
[s]RESERVE[n][e]

[msg Item_044]
[s]RESERVE[n][e]

[msg Item_045]
[s]Amuleto que protege[n]contra la tristeza.[n][e]

[msg Item_046]
[s]RESERVE[n][e]

[msg Item_047]
[s]RESERVE[n][e]

[msg Item_048]
[s]Espejo que exige[n]venganza.[n][e]

[msg Item_049]
[s]Espejo que contraataca[n]ante cualquier acci吋n.[n][e]

[msg Item_04A]
[s]Espejo que castiga al mal[n]por sus fechor胤as.[n][e]

[msg Item_04B]
[s]Parche que mantiene[n]despierto y alerta.[n][e]

[msg Item_04C]
[s]Popurr胤 de fragancia[n]relajante.[n][e]

[msg Item_04D]
[s]Calendario lleno[n]de est胤mulos diarios.[n][e]

[msg Item_04E]
[s]Gafas con estilo que[n]tambi姻n protegen la vista.[n][e]

[msg Item_04F]
[s]Capa que ayuda[n]a ver con claridad.[n][e]

[msg Item_050]
[s]Bote de aceite inflamable.[n][e]

[msg Item_051]
[s]Paquete de hielo[n]reutilizable.[n][e]

[msg Item_052]
[s]Bater胤a recargable.[n][e]

[msg Item_053]
[s]M茨scara que causa v姻rtigo.[n][e]

[msg Item_054]
[s]M茨scara con un aura[n]m胤stica.[n][e]

[msg Item_055]
[s]M茨scara terror胤fica[n]hasta la m姻dula.[n][e]

[msg Item_056]
[s]M茨scara de distracci吋n[n]que borra los pensamientos.[n][e]

[msg Item_057]
[s]M茨scara hipn吋tica que[n]duerme a quien la mire.[n][e]

[msg Item_058]
[s]M茨scara provocadora que[n]pide una torta a gritos.[n][e]

[msg Item_059]
[s]M茨scara decadente[n]con un aire arrogante.[n][e]

[msg Item_05A]
[s]Una m茨scara maldita.[n][e]

[msg Item_05B]
[s]Tiene el sello de un[n]pervertido.[n][e]

[msg Item_05C]
[s]Tiene el sello de un[n]narcisista.[n][e]

[msg Item_05D]
[s]Tiene el sello de un[n]avaricioso.[n][e]

[msg Item_05E]
[s]Tiene el sello de un[n]berserker.[n][e]

[msg Item_05F]
[s]Tiene el sello de un[n]avaro.[n][e]

[msg Item_060]
[s]Tiene el sello de un[n]conspirador.[n][e]

[msg Item_061]
[s]Tiene el sello de un[n]ego胤sta.[n][e]

[msg Item_062]
[s]Tiene el sello de un[n]doliente.[n][e]

[msg Item_063]
[s]Cristal que contiene[n]el poder de la lujuria.[n][e]

[msg Item_064]
[s]Cristal que contiene[n]el poder de la vanidad.[n][e]

[msg Item_065]
[s]Cristal que contiene[n]el poder de la gula.[n][e]

[msg Item_066]
[s]Cristal que contiene[n]el poder de la ira.[n][e]

[msg Item_067]
[s]Cristal que contiene[n]el poder de la avaricia.[n][e]

[msg Item_068]
[s]Cristal que contiene[n]el poder de la envidia.[n][e]

[msg Item_069]
[s]Cristal que contiene[n]el poder del orgullo.[n][e]

[msg Item_06A]
[s]Cristal que contiene[n]el poder de la tristeza.[n][e]

[msg Item_06B]
[s]RESERVE[n][e]

[msg Item_06C]
[s]RESERVE[n][e]

[msg Item_06D]
[s]RESERVE[n][e]

[msg Item_06E]
[s]RESERVE[n][e]

[msg Item_06F]
[s]Cintur吋n con el poder[n]de una deidad violenta.[n][e]

[msg Item_070]
[s]Cintur吋n con forma[n]de arma divina.[n][e]

[msg Item_071]
[s]Cintur吋n que port吋 un[n]dios de la guerra.[n][e]

[msg Item_072]
[s]Gorra de b姻isbol que llev吋[n]puesta un campe吋n.[n][e]

[msg Item_073]
[s]Cintur吋n que otorga el[n]poder de resistir ataques.[n][e]

[msg Item_074]
[s]Llavero que, a primera[n]vista, parece seguro.[n][e]

[msg Item_075]
[s]Faja que infunde valent胤a[n]a quien la porta.[n][e]

[msg Item_076]
[s]Pulsera de la amistad[n]potenciada.[n][e]

[msg Item_077]
[s]Un arpa que embruja[n]a quienes la escuchan.[n][e]

[msg Item_078]
[s]Un harpa regia que embruja[n]a quienes la escuchan.[n][e]

[msg Item_079]
[s]Anillo con el poder[n]de El segador.[n][e]

[msg Item_07A]
[s]Un anillo regio que alberga[n]a雨n m茨s poder de El segador.[n][e]

[msg Item_07B]
[s]Una diadema llena de energ胤a.[n][e]

[msg Item_07C]
[s]Una diadema regia[n]llena de m茨s energ胤a a雨n.[n][e]

[msg Item_07D]
[s]Diadema que muestra[n]los deseos m茨s 胤ntimos.[n][e]

[msg Item_07E]
[s]Diadema regia que muestra[n]los deseos m茨s 胤ntimos.[n][e]

[msg Item_07F]
[s]Un ovillo de hilo que conduce[n]a la salvaci吋n.[n][e]

[msg Item_080]
[s]Un ovillo de hilo regio que[n]conduce a la salvaci吋n.[n][e]

[msg Item_081]
[s]Cuernos como los de[n]un toro bravo.[n][e]

[msg Item_082]
[s]Cuernos regios[n]como los de un toro bravo.[n][e]

[msg Item_083]
[s]Piedra de brillo d姻bil.[n][e]

[msg Item_084]
[s]Piedra regia[n]de brillo d姻bil.[n][e]

[msg Item_085]
[s]RESERVE[n][e]

[msg Item_086]
[s]Arpa encantadora con[n]forma de coraz吋n.[n][e]

[msg Item_087]
[s]Arpa regia y encantadora[n]con forma de coraz吋n.[n][e]

[msg Item_088]
[s]Una armadura[n]que aumenta la defensa de todos.[n][e]

[msg Item_089]
[s]Una armadura regia que aumenta[n]la defensa de todo el mundo. [n][e]

[msg Item_08A]
[s]Un cintur吋n con[n]un poderoso brillo.[n][e]

[msg Item_08B]
[s]Un cintur吋n regio[n]con un poderoso brillo.[n][e]

[msg Item_08C]
[s]Sombrero de seda de[n]un Ladr吋n Fantasma.[n][e]

[msg Item_08D]
[s]Corona de un legendario[n]Ladr吋n Fantasma.[n][e]

[msg Item_08E]
[s]RESERVE[n][e]

[msg Item_08F]
[s]RESERVE[n][e]

[msg Item_090]
[s]Parche usado por[n]un guerrero.[n][e]

[msg Item_091]
[s]Calcetines que mejoran el tiempo[n]de reacci吋n de quien los porta.[n][e]

[msg Item_092]
[s]RESERVE[n][e]

[msg Item_093]
[s]Una gargantilla roja que permite[n]esquivar los ataques de fuego.[n][e]

[msg Item_094]
[s]Un misterioso brazalete[n]que ayuda a esquivar[n]los ataques de fuego.[n][e]

[msg Item_095]
[s]RESERVE[n][e]

[msg Item_096]
[s]Una gargantilla azul que permite[n]los ataques de hielo.[n][e]

[msg Item_097]
[s]Un misterioso brazalete[n]que ayuda a esquivar[n]los ataques de hielo.[n][e]

[msg Item_098]
[s]RESERVE[n][e]

[msg Item_099]
[s]Una gargantilla que evita[n]ataques de electricidad.[n][e]

[msg Item_09A]
[s]Un misterioso brazalete[n]que ayuda a esquivar[n]los ataques de electricidad.[n][e]

[msg Item_09B]
[s]RESERVE[n][e]

[msg Item_09C]
[s]Una gargantilla que evita[n]ataques de viento.[n][e]

[msg Item_09D]
[s]Un misterioso brazalete[n]que ayuda a esquivar[n]los ataques de viento.[n][e]

[msg Item_09E]
[s]RESERVE[n][e]

[msg Item_09F]
[s]Una gargantilla roja que permite[n]esquivar los ataques nucleares.[n][e]

[msg Item_0A0]
[s]Un misterioso brazalete[n]que ayuda a esquivar[n]los ataques nucleares.[n][e]

[msg Item_0A1]
[s]RESERVE[n][e]

[msg Item_0A2]
[s]Una gargantilla retorcida[n]que permite esquivar[n]los ataques psicoquin姻ticos.[n][e]

[msg Item_0A3]
[s]Un misterioso brazalete[n]que ayuda a esquivar[n]los ataques psicoquin姻ticos.[n][e]

[msg Item_0A4]
[s]RESERVE[n][e]

[msg Item_0A5]
[s]Una gargantilla brillante[n]que permite esquivar[n]los ataques de bendici吋n.[n][e]

[msg Item_0A6]
[s]Un misterioso brazalete[n]que ayuda a esquivar[n]los ataques de bendici吋n.[n][e]

[msg Item_0A7]
[s]RESERVE[n][e]

[msg Item_0A8]
[s]Gargantilla impura que[n]evita ataques de maldici吋n.[n][e]

[msg Item_0A9]
[s]Horquilla roja que evita[n]los ataques de maldici吋n.[n][e]

[msg Item_0AA]
[s]RESERVE[n][e]

[msg Item_0AB]
[s]Emblema angelical que evita[n]los ataques m茨gicos.[n][e]

[msg Item_0AC]
[s]RESERVE[n][e]

[msg Item_0AD]
[s]RESERVE[n][e]

[msg Item_0AE]
[s]Anillo que permite aprender[n]con mayor rapidez.[n][e]

[msg Item_0AF]
[s]RESERVE[n][e]

[msg Item_0B0]
[s]RESERVE[n][e]

[msg Item_0B1]
[s]RESERVE[n][e]

[msg Item_0B2]
[s]RESERVE[n][e]

[msg Item_0B3]
[s]RESERVE[n][e]

[msg Item_0B4]
[s]RESERVE[n][e]

[msg Item_0B5]
[s]RESERVE[n][e]

[msg Item_0B6]
[s]RESERVE[n][e]

[msg Item_0B7]
[s]Gema que fortalece[n]a quien la porta.[n][e]

[msg Item_0B8]
[s]Un colgante m茨gico que[n]anima el coraz吋n[n]de quien lo porta.[n][e]

[msg Item_0B9]
[s]Una gema m胤stica que mejora[n]el esp胤ritu de quien la porta.[n][e]

[msg Item_0BA]
[s]Una atractiva corona[n]que hace resplandecer[n]a quien la lleva.[n][e]

[msg Item_0BB]
[s]Una gema m茨gica[n]que provoca sufrimiento.[n][e]

[msg Item_0BC]
[s]Una gema m茨gica[n]con el poder de un emperador.[n][e]

[msg Item_0BD]
[s]Una famosa gema[n]maldita pero curativa.[n][e]

[msg Item_0BE]
[s]Una gema m茨gica[n]que ayuda a evitar las[n]habilidades m茨gicas.[n][e]

[msg Item_0BF]
[s]Amuleto con forma de cruz.[n][e]

[msg Item_0C0]
[s]Cintur吋n de un marinero.[n][e]

[msg Item_0C1]
[s]Cintur吋n de un dios veloz.[n][e]

[msg Item_0C2]
[s]Cintur吋n de un famoso.[n][e]

[msg Item_0C3]
[s]M茨scara con el logo[n]de los Ladrones Fantasma.[n][e]

[msg Item_0C4]
[s]Piedra que se transforma[n]en varios equipamientos.[n][e]

[msg Item_0C5]
[s]Amuleto espeluznante[n]con forma de calavera.[n][e]

[msg Item_0C6]
[s]Colgante de piedra[n]que quema al tocarlo.[n][e]

[msg Item_0C7]
[s]Collar de piedra fr胤o[n]como el hielo.[n][e]

[msg Item_0C8]
[s]Collar de piedra verde.[n][e]

[msg Item_0C9]
[s]Un colgante con piedras[n]con forma de rayo.[n][e]

[msg Item_0CA]
[s]Collar que parece[n]un compuesto c胤clico.[n][e]

[msg Item_0CB]
[s]Un collar con un adorno ps胤quico.[n][e]

[msg Item_0CC]
[s]Precioso collar del color[n]del cielo.[n][e]

[msg Item_0CD]
[s]Collar oscuro[n]como la noche.[n][e]

[msg Item_0CE]
[s]RESERVE[n][e]

[msg Item_0CF]
[s]Un par de mu隠ecos con forma[n]de enanos hawaianos.[n][e]

[msg Item_0D0]
[s]Un anillo con forma de lei[n]con iniciales grabadas.[n][e]

[msg Item_0D1]
[s]Una medalla ganada por pasarse[n]Star Forneus.[n][e]

[msg Item_0D2]
[s]Una medalla ganada por pasarse[n]Train of Life.[n][e]

[msg Item_0D3]
[s]Una medalla ganada por pasarse[n]Power Intuition.[n][e]

[msg Item_0D4]
[s]Una medalla ganada por pasarse[n]Punch Ouch.[n][e]

[msg Item_0D5]
[s]Una medalla ganada por pasarse[n]Legend of Gambla Goemon.[n][e]

[msg Item_0D6]
[s]Una medalla ganada por pasarse[n]Pro Golfer Sarutahiko.[n][e]

[msg Item_0D7]
[s]Un cintur吋n para los que tienen[n]la mirada del tigre.[n][e]

[msg Item_0D8]
[s]Espejo compacto[n]usado por un veterano.[n][e]

[msg Item_0D9]
[s]Contiene los mejores granos[n]de caf姻 del Jefe.[n][e]

[msg Item_0DA]
[s]Los calzoncillos selectos del Jefe.[n][e]

[msg Item_0DB]
[s]Una insignia que demuestra que[n]eres Teniente Comandante.[n][e]

[msg Item_0DC]
[s]Una insignia que demuestra que[n]eres Comandante.[n][e]

[msg Item_0DD]
[s]Una insignia que demuestra que[n]eres Capit茨n.[n][e]

[msg Item_0DE]
[s]Parche que cura[n]un poco de salud.[n][e]

[msg Item_0DF]
[s]Parche que cura[n]algo de salud.[n][e]

[msg Item_0E0]
[s]Parche que cura[n]bastante salud.[n][e]

[msg Item_0E1]
[s]Esparadrapo que restaura[n]un poco de esp胤ritu.[n][e]

[msg Item_0E2]
[s]Esparadrapo que restaura[n]algo de esp胤ritu.[n][e]

[msg Item_0E3]
[s]Esparadrapo que restaura[n]bastante esp胤ritu.[n][e]

[msg Item_0E4]
[s]RESERVE[n][e]

[msg Item_0E5]
[s]RESERVE[n][e]

[msg Item_0E6]
[s]Una copa que solo puede sujetar[n]quienes se alcen con la victoria.[n][e]

[msg Item_0E7]
[s]Emblema que permite[n]esquivar cualquier ataque.[n][e]

[msg Item_0E8]
[s]Orbe con un poder[n]casi celestial.[n][e]

[msg Item_0E9]
[s]Pilar que otorga[n]protecci吋n divina.[n][e]

[msg Item_0EA]
[s]Un velo que protege[n]de los d姻biles de voluntad.[n][e]

[msg Item_0EB]
[s]RESERVE[n][e]

[msg Item_0EC]
[s]Perla que provoca apego[n]hacia las cosas.[n][e]

[msg Item_0ED]
[s]Cintur吋n que emplea el mal[n]tiempo para afligir.[n][e]

[msg Item_0EE]
[s]RESERVE[n][e]

[msg Item_0EF]
[s]RESERVE[n][e]

[msg Item_0F0]
[s]RESERVE[n][e]

[msg Item_0F1]
[s]Parece que podr胤a venderse[n]por una buena suma, pero...[n][e]

[msg Item_0F2]
[s]Gafas que permiten[n]ver con claridad en la niebla.[n][e]

[msg Item_0F3]
[s]Un brazalete con 或S.E.E.S.位[n]escrito en 姻l.[n][e]

[msg Item_0F4]
[s]Emblema del Instituto Seven[n]Sisters. Cuidado con los rumores.[n][e]

[msg Item_0F5]
[s]Emblema del Instituto[n]St. Hermelin.[n][e]

[msg Item_0F6]
[s]Un ordenador de brazo[n]con el programa[n]Demon Summoner.[n][e]

[msg Item_0F7]
[s]Un pa隠uelo amarillo capaz[n]de bailar toda la noche.[n][e]

[msg Item_0F8]
[s]Un evocador port茨til.[n][e]

[msg Item_0F9]
[s]Un amuleto de la suerte[n]con forma de tortuga.[n][e]

[msg Item_0FA]
[s]Un llavero con una estatua Tiki[n]de madera.[n][e]

[msg Item_0FB]
[s]Con bajo extra para aumentar[n]el ritmo.[n][e]

[msg Item_0FC]
[s]Te a胤slan del ruido para[n]ayudar a concentrarse.[n][e]

[msg Item_0FD]
[s]Portada por hombres insomnes[n]en sus sue隠os.[n][e]

[msg Item_0FE]
[s]Tiene un PC interno que[n]solo pueden usar los samur茨is.[n][e]

[msg Item_0FF]
[s]Tubos que usa el clan Kuzunoha[n]para invocar demonios.[n][e]

[msg Item_100]
[s]Una medalla ganada por pasarse[n]Featherman Seeker.[n][e]

[msg Item_101]
[s]Sin usar[n][e]

[msg Item_102]
[s]Sin usar[n][e]

[msg Item_103]
[s]Sin usar[n][e]

[msg Item_104]
[s]Sin usar[n][e]

[msg Item_105]
[s]Sin usar[n][e]

[msg Item_106]
[s]Sin usar[n][e]

[msg Item_107]
[s]Sin usar[n][e]

[msg Item_108]
[s]Sin usar[n][e]

[msg Item_109]
[s]Sin usar[n][e]

[msg Item_10A]
[s]RESERVE[n][e]

[msg Item_10B]
[s]Sin usar[n][e]

[msg Item_10C]
[s]RESERVE[n][e]

[msg Item_10D]
[s]Anillo que permite moverse[n]como el viento.[n][e]

[msg Item_10E]
[s]Placa de identificaci吋n[n]de un francotirador famoso.[n][e]

[msg Item_10F]
[s]Un gran lazo rojo.[n][e]

[msg Item_110]
[s]Anillo cargado con fuego.[n][e]

[msg Item_111]
[s]Anillo potenciado[n]con fuego.[n][e]

[msg Item_112]
[s]Anillo que genera[n]un poder fogoso.[n][e]

[msg Item_113]
[s]Anillo en espiral cargado[n]con fuego.[n][e]

[msg Item_114]
[s]Anillo en espiral[n]potenciado con fuego.[n][e]

[msg Item_115]
[s]Anillo en espiral que[n]genera un poder fogoso.[n][e]

[msg Item_116]
[s]Anillo cargado con hielo.[n][e]

[msg Item_117]
[s]Anillo potenciado[n]con hielo.[n][e]

[msg Item_118]
[s]Anillo que genera[n]un poder helado.[n][e]

[msg Item_119]
[s]Anillo en espiral cargado[n]con hielo.[n][e]

[msg Item_11A]
[s]Anillo en espiral[n]potenciado con hielo.[n][e]

[msg Item_11B]
[s]Anillo en espiral que[n]genera un poder helado.[n][e]

[msg Item_11C]
[s]Anillo cargado con viento.[n][e]

[msg Item_11D]
[s]Anillo potenciado[n]con viento.[n][e]

[msg Item_11E]
[s]Anillo potenciado[n]con viento.[n][e]

[msg Item_11F]
[s]Anillo en espiral cargado[n]con viento.[n][e]

[msg Item_120]
[s]Anillo en espiral[n]potenciado con viento.[n][e]

[msg Item_121]
[s]Anillo en espiral que[n]genera un poder ventoso.[n][e]

[msg Item_122]
[s]Un peque隠o anillo que aloja[n]el poder de la electricidad.[n][e]

[msg Item_123]
[s]Un anillo que alberga[n]un gran poder de electricidad.[n][e]

[msg Item_124]
[s]Un anillo que alberga[n]el poder de electricidad[n]m茨s absoluto.[n][e]

[msg Item_125]
[s]Un peque隠o anillo en espiral[n]que alberga el poder[n]de la electricidad.[n][e]

[msg Item_126]
[s]Un anillo en espiral que alberga[n]un gran poder de electricidad.[n][e]

[msg Item_127]
[s]Un anillo en espiral que alberga[n]el poder de electricidad[n]m茨s absoluto.[n][e]

[msg Item_128]
[s]Un anillo imbuido[n]con el poder de los cielos.[n][e]

[msg Item_129]
[s]Anillo potenciado[n]por los cielos.[n][e]

[msg Item_12A]
[s]Anillo en espiral imbuido[n]con el poder de los cielos.[n][e]

[msg Item_12B]
[s]Anillo en espiral[n]potenciado por los cielos.[n][e]

[msg Item_12C]
[s]Anillo cargado[n]por los cielos.[n][e]

[msg Item_12D]
[s]Anillo potenciado[n]por los cielos.[n][e]

[msg Item_12E]
[s]Anillo que genera[n]un poder celestial.[n][e]

[msg Item_12F]
[s]Anillo en espiral cargado[n]por los cielos.[n][e]

[msg Item_130]
[s]Anillo en espiral[n]potenciado por los cielos.[n][e]

[msg Item_131]
[s]Anillo en espiral que[n]genera un poder celestial.[n][e]

[msg Item_132]
[s]Un anillo imbuido[n]con el poder del infierno.[n][e]

[msg Item_133]
[s]Un anillo imbuido[n]con el gran poder del infierno.[n][e]

[msg Item_134]
[s]Anillo en espiral imbuido[n]con un poder infernal.[n][e]

[msg Item_135]
[s]Anillo en espiral imbuido[n]con un poder infernal.[n][e]

[msg Item_136]
[s]Anillo con un aura[n]siniestra.[n][e]

[msg Item_137]
[s]Anillo que porta[n]una maldici吋n.[n][e]

[msg Item_138]
[s]Anillo que porta[n]un maleficio.[n][e]

[msg Item_139]
[s]Anillo en espiral con[n]un aura siniestra.[n][e]

[msg Item_13A]
[s]Anillo en espiral que porta[n]un maleficio.[n][e]

[msg Item_13B]
[s]Anillo en espiral que porta[n]una maldici吋n.[n][e]

[msg Item_13C]
[s]Anillo cargado con[n]una habilidad divina.[n][e]

[msg Item_13D]
[s]Anillo potenciado con[n]una habilidad divina.[n][e]

[msg Item_13E]
[s]Anillo que genera[n]la habilidad m茨s divina.[n][e]

[msg Item_13F]
[s]Un peque隠o anillo que alberga[n]poder nuclear.[n][e]

[msg Item_140]
[s]Un anillo que aloja un[n]poder nuclear superior.[n][e]

[msg Item_141]
[s]Un anillo en espiral que alberga[n]el poder nuclear m茨s absoluto.[n][e]

[msg Item_142]
[s]Un peque隠o anillo en espiral[n]que alberga poder nuclear.[n][e]

[msg Item_143]
[s]Un anillo en espiral que alberga[n]un gran poder nuclear.[n][e]

[msg Item_144]
[s]Un anillo en espiral que alberga[n]el poder nuclear m茨s absoluto.[n][e]

[msg Item_145]
[s]Pulsera que puede marear[n]a un individuo.[n][e]

[msg Item_146]
[s]Pulsera en espiral que[n]puede marear a muchos.[n][e]

[msg Item_147]
[s]Pulsera que puede confundir[n]a los dem茨s.[n][e]

[msg Item_148]
[s]Pulsera en espiral que[n]puede confundir a muchos.[n][e]

[msg Item_149]
[s]Pulsera que puede asustar[n]a los dem茨s.[n][e]

[msg Item_14A]
[s]M茨scara sonriente que[n]puede asustar a muchos.[n][e]

[msg Item_14B]
[s]Pulsera que provoca que[n]un individuo olvide.[n][e]

[msg Item_14C]
[s]Pulsera en espiral que[n]provoca que muchos olviden.[n][e]

[msg Item_14D]
[s]Pulsera que puede[n]adormecer a un individuo.[n][e]

[msg Item_14E]
[s]Pulsera en espiral que[n]puede adormecer a muchos.[n][e]

[msg Item_14F]
[s]Pulsera que puede enfadar[n]a los dem茨s.[n][e]

[msg Item_150]
[s]Pulsera en espiral que[n]puede enfadar a muchos.[n][e]

[msg Item_151]
[s]Pulsera que puede[n]entristecer a un individuo.[n][e]

[msg Item_152]
[s]Pulsera en espiral que[n]puede entristecer a muchos.[n][e]

[msg Item_153]
[s]Pulsera con un poder[n]manipulador.[n][e]

[msg Item_154]
[s]Extra隠a corona que puede[n]manipular a muchos.[n][e]

[msg Item_155]
[s]Una m茨scara que roba[n]salud al enemigo.[n][e]

[msg Item_156]
[s]M茨scara que le arrebata[n]el esp胤ritu al enemigo.[n][e]

[msg Item_157]
[s]Un espejo de mano que[n]aterroriza a quien lo ve.[n][e]

[msg Item_158]
[s]Espejo que enturbia[n]el 茨nimo a tu alrededor.[n][e]

[msg Item_159]
[s]Una c茨mara que destruye[n]a quienes tienen miedo.[n][e]

[msg Item_15A]
[s]Un collar con un siniestro[n]dise隠o de fuego.[n][e]

[msg Item_15B]
[s]Un collar que quema[n]todo lo que est姻 a la vista.[n][e]

[msg Item_15C]
[s]Un lirio artificial creado[n]con peque隠as part胤culas de hielo.[n][e]

[msg Item_15D]
[s]Corona con el poder[n]del hielo.[n][e]

[msg Item_15E]
[s]La escultura de un dios malvado[n]que provoca una tormenta.[n][e]

[msg Item_15F]
[s]Corona con el poder[n]del viento.[n][e]

[msg Item_160]
[s]Un cuerno electrificado[n]con la cara de una diosa.[n][e]

[msg Item_161]
[s]Un amuleto con el poder[n]de invocar al dios del trueno.[n][e]

[msg Item_162]
[s]Corona imbuida con[n]el juicio de un dios.[n][e]

[msg Item_163]
[s]Sin usar[n][e]

[msg Item_164]
[s]Lazo blanco que contiene[n]la maldici吋n de una joven.[n][e]

[msg Item_165]
[s]Sin usar[n][e]

[msg Item_166]
[s]El cuerno de un drag吋n de fuego,[n]imbuido con calor.[n][e]

[msg Item_167]
[s]Una corona que alberga[n]poder nuclear.[n][e]

[msg Item_168]
[s]Corona de alguien[n]que anhela justicia.[n][e]

[msg Item_169]
[s]Una corona[n]con el poder de las estrellas.[n][e]

[msg Item_16A]
[s]Un peque隠o anillo que alberga[n]el poder de la psicoquinesis.[n][e]

[msg Item_16B]
[s]Un anillo que alberga[n]un gran poder de psicoquinesis.[n][e]

[msg Item_16C]
[s]Un anillo que alberga[n]el poder de psicoquinesis[n]m茨s absoluto.[n][e]

[msg Item_16D]
[s]Un peque隠o anillo en espiral[n]que alberga el poder[n]de la psicoquinesis.[n][e]

[msg Item_16E]
[s]Un anillo en espiral que alberga[n]un gran poder de psicoquinesis.[n][e]

[msg Item_16F]
[s]Un anillo en espiral que alberga[n]el poder de psicoquinesis[n]m茨s absoluto.[n][e]

[msg Item_170]
[s]RESERVE[n][e]

[msg Item_171]
[s]Una piedra m胤stica que contiene[n]el poder de un drag吋n.[n][e]

[msg Item_172]
[s]Una corona que encierra[n]el poder de la psicoquinesis.[n][e]

[msg Item_173]
[s]Cintur吋n que permite[n]golpear con contundencia.[n][e]

[msg Item_174]
[s]Cintur吋n que permite[n]pegar con fuerza.[n][e]

[msg Item_175]
[s]Cintur吋n que permite[n]asestar un golpe grave.[n][e]

[msg Item_176]
[s]Cintur吋n con el poder[n]de la Mano de Dios.[n][e]

[msg Item_177]
[s]Cintur吋n que permite[n]asestar un golpe de suerte.[n][e]

[msg Item_178]
[s]Un cintur吋n que permite[n]asestar un fuerte golpe.[n][e]

[msg Item_179]
[s]Un cintur吋n que permite[n]asestar un gran golpe.[n][e]

[msg Item_17A]
[s]Un cintur吋n que permite[n]atacar varias veces.[n][e]

[msg Item_17B]
[s]Un extra隠o cintur吋n que otorga[n]el poder de abrir cosas[n]con un corte.[n][e]

[msg Item_17C]
[s]Un cintur吋n que[n]otorga al portador el poder[n]de partir cosas por la mitad.[n][e]

[msg Item_17D]
[s]Cintur吋n que permite[n]asestar un golpe aterrador.[n][e]

[msg Item_17E]
[s]Cintur吋n que permite una[n]danza de espadas temible.[n][e]

[msg Item_17F]
[s]Sin usar[n][e]

[msg Item_180]
[s]Sin usar[n][e]

[msg Item_181]
[s]Cintur吋n que te ayuda[n]cuando est茨s acorralado.[n][e]

[msg Item_182]
[s]Cintur吋n que permite[n]atacar con fuerza.[n][e]

[msg Item_183]
[s]Cintur吋n que permite[n]atacar con fiereza.[n][e]

[msg Item_184]
[s]Cintur吋n adornado con[n]un chasquido de dedos.[n][e]

[msg Item_185]
[s]Un cintur吋n que tiene tres balas.[n][e]

[msg Item_186]
[s]Cintur吋n equipado[n]con balas especiales.[n][e]

[msg Item_187]
[s]Cintur吋n con balas imbuidas[n]con el alma de un rebelde.[n][e]

[msg Item_188]
[s]Un cintur吋n que tiene dos balas.[n][e]

[msg Item_189]
[s]Cintur吋n que permite[n]romper cualquier cosa.[n][e]

[msg Item_18A]
[s]Cintur吋n que permite cortar[n]y matar cualquier cosa.[n][e]

[msg Item_18B]
[s]Cintur吋n que permite[n]atravesar cualquier cosa.[n][e]

[msg Item_18C]
[s]Un cintur吋n que ayuda[n]a derribar cualquier cosa.[n][e]

[msg Item_18D]
[s]Cintur吋n que permite[n]aniquilar cualquier cosa.[n][e]

[msg Item_18E]
[s]Peligroso cintur吋n usado[n]en las peleas a golpes.[n][e]

[msg Item_18F]
[s]Cintur吋n que te permite[n]sacar todo tu potencial.[n][e]

[msg Item_190]
[s]Cintur吋n que permite[n]dar un golpe terror胤fico.[n][e]

[msg Item_191]
[s]Un cintur吋n imbuido con el aura[n]de un arma ancestral.[n][e]

[msg Item_192]
[s]Un cintur吋n con un par[n]de colmillos.[n][e]

[msg Item_193]
[s]Cintur吋n que permite[n]asestar tajos poderosos.[n][e]

[msg Item_194]
[s]Cintur吋n que permite[n]asestar muchos tajos.[n][e]

[msg Item_195]
[s]Cintur吋n que permite[n]dar un aluvi吋n de tajos.[n][e]

[msg Item_196]
[s]Cintur吋n de un maestro[n]martillista.[n][e]

[msg Item_197]
[s]Cintur吋n que ayuda[n]a desorientar al oponente.[n][e]

[msg Item_198]
[s]Cintur吋n con un gato negro.[n][e]

[msg Item_199]
[s]Cintur吋n que permite[n]asestar un golpe amn姻sico.[n][e]

[msg Item_19A]
[s]RESERVE[n][e]

[msg Item_19B]
[s]Cintur吋n con el que se ven[n]las estrellas.[n][e]

[msg Item_19C]
[s]Cintur吋n con el que dar[n]un bofet吋n ofensivo.[n][e]

[msg Item_19D]
[s]Cintur吋n con un aura[n]deprimente.[n][e]

[msg Item_19E]
[s]Cintur吋n raro de dise隠o[n]hipn吋tico.[n][e]

[msg Item_19F]
[s]Cintur吋n popular de dise隠o[n]deslumbrante.[n][e]

[msg Item_1A0]
[s]Cintur吋n que hace criticar[n]tu sentido de la moda.[n][e]

[msg Item_1A1]
[s]Cintur吋n temible que deja[n]tiesos a tus enemigos.[n][e]

[msg Item_1A2]
[s]Cintur吋n que afecta[n]a la memoria.[n][e]

[msg Item_1A3]
[s]RESERVE[n][e]

[msg Item_1A4]
[s]Si te duermes, pierdes.[n][e]

[msg Item_1A5]
[s]Cintur吋n irritante para[n]molestar a los dem茨s.[n][e]

[msg Item_1A6]
[s]Cintur吋n con un aura[n]l雨gubre y deprimente.[n][e]

[msg Item_1A7]
[s]Cintur吋n para persuadir[n]a los dem茨s.[n][e]

[msg Item_1A8]
[s]Amuleto cargado[n]con un poder curativo.[n][e]

[msg Item_1A9]
[s]Amuleto potenciado[n]con un poder curativo.[n][e]

[msg Item_1AA]
[s]Amuleto que genera[n]un poder curativo.[n][e]

[msg Item_1AB]
[s]Amuleto en espiral cargado[n]con un poder curativo.[n][e]

[msg Item_1AC]
[s]Amuleto en espiral potenc.[n]con un poder curativo.[n][e]

[msg Item_1AD]
[s]Amuleto en espiral que[n]genera un poder curativo.[n][e]

[msg Item_1AE]
[s]Amuleto que otorga[n]vida a los ca胤dos.[n][e]

[msg Item_1AF]
[s]Amuleto poderoso que[n]otorga vida a los ca胤dos.[n][e]

[msg Item_1B0]
[s]Un rosario que salva[n]las almas de quienes rezan.[n][e]

[msg Item_1B1]
[s]Amuleto de agua[n]espiritual.[n][e]

[msg Item_1B2]
[s]Amuleto en espiral[n]de agua espiritual.[n][e]

[msg Item_1B3]
[s]Una corona divina con el poder[n]de salvar a muchas personas.[n][e]

[msg Item_1B4]
[s]Un cintur吋n para quienes[n]ans胤an ser el centro de atenci吋n.[n][e]

[msg Item_1B5]
[s]Un anillo con el poder de ocultar[n]la presencia del portador.[n][e]

[msg Item_1B6]
[s]Un amuleto que ayuda[n]a despertarse.[n][e]

[msg Item_1B7]
[s]Un amuleto en espiral que cura[n]la fatiga mental de todos.[n][e]

[msg Item_1B8]
[s]Amuleto que cura[n]la fatiga mental.[n][e]

[msg Item_1B9]
[s]Un amuleto que protege[n]de los da隠os elementales.[n][e]

[msg Item_1BA]
[s]Un amuleto en espiral[n]que ayuda a despertarse.[n][e]

[msg Item_1BB]
[s]Un amuleto en espiral que protege[n]de los da隠os elementales.[n][e]

[msg Item_1BC]
[s]Tobillera con la fuerza[n]de un esp胤ritu malvado.[n][e]

[msg Item_1BD]
[s]Una tobillera con el poder[n]de aumentar la defensa.[n][e]

[msg Item_1BE]
[s]Un broche[n]con un gato 茨gil.[n][e]

[msg Item_1BF]
[s]Tobillera que te anima.[n][e]

[msg Item_1C0]
[s]Tobillera en espiral con la[n]fuerza de un esp胤ritu vil.[n][e]

[msg Item_1C1]
[s]Una tobillera en espiral[n]con el poder de aumentar la defensa[n]de todos.[n][e]

[msg Item_1C2]
[s]Tobillera en espiral que[n]aumenta los reflejos.[n][e]

[msg Item_1C3]
[s]Un broche que desbloquea[n]tu verdadero potencial cuando[n]est茨s a punto de morir.[n][e]

[msg Item_1C4]
[s]Tobillera que debilita[n]a cualquier enemigo.[n][e]

[msg Item_1C5]
[s]Tobillera que reduce[n]la defensa de un enemigo.[n][e]

[msg Item_1C6]
[s]Tobillera en espiral con la[n]que se reacciona mejor.[n][e]

[msg Item_1C7]
[s]Tobillera que hace sentir[n]d姻biles a los enemigos.[n][e]

[msg Item_1C8]
[s]Tobillera en espiral que[n]debilita a los enemigos.[n][e]

[msg Item_1C9]
[s]Tobillera en espiral que[n]red. la def. de los enem.[n][e]

[msg Item_1CA]
[s]Tobillera en espiral con la[n]que se reacciona mejor.[n][e]

[msg Item_1CB]
[s]Tobillera que disipa[n]la sensaci吋n de debilidad.[n][e]

[msg Item_1CC]
[s]Una tobillera con el poder[n]de calmar a un enemigo.[n][e]

[msg Item_1CD]
[s]Tobillera que potencia[n]los ataques f胤sicos.[n][e]

[msg Item_1CE]
[s]Tobillera que potencia[n]los ataques m茨gicos.[n][e]

[msg Item_1CF]
[s]Una tobillera que mejora[n]la concentraci吋n.[n][e]

[msg Item_1D0]
[s]Tobillera que mejora[n]la concentraci吋n de muchos.[n][e]

[msg Item_1D1]
[s]Amuleto con el poder[n]de reflejar atq. m茨gicos.[n][e]

[msg Item_1D2]
[s]Un amuleto con el poder[n]de reflejar los ataques f胤sicos.[n][e]

[msg Item_1D3]
[s]Amuleto que protege[n]de la muerte.[n][e]

[msg Item_1D4]
[s]Un amuleto que puede romper[n]barreras que reflejan lo f胤sico.[n][e]

[msg Item_1D5]
[s]Un amuleto que rompe[n]barreras que reflejan la magia.[n][e]

[msg Item_1D6]
[s]Gargantilla que escuda[n]del fuego.[n][e]

[msg Item_1D7]
[s]Gargantilla que escuda[n]del hielo.[n][e]

[msg Item_1D8]
[s]Una gargantilla con un escudo.[n]Protege a quien la porta[n]de los ataques de electricidad.[n][e]

[msg Item_1D9]
[s]Gargantilla que escuda[n]del viento.[n][e]

[msg Item_1DA]
[s]Campana que rompe[n]las barreras de fuego.[n][e]

[msg Item_1DB]
[s]Campana que rompe[n]las barreras de hielo.[n][e]

[msg Item_1DC]
[s]Campana que rompe[n]las barreras de viento.[n][e]

[msg Item_1DD]
[s]Una campana con el poder[n]de atravesar guardias[n]de electricidad.[n][e]

[msg Item_1DE]
[s]Una gargantilla con un escudo.[n]Protege a quien la porta[n]de los ataques nucleares.[n][e]

[msg Item_1DF]
[s]Una gargantilla con un escudo.[n]Protege a quien la porta[n]de los ataques psicoquin姻ticos.[n][e]

[msg Item_1E0]
[s]Una campana con el poder[n]de atravesar guardias nucleares.[n][e]

[msg Item_1E1]
[s]Una campana con el poder[n]de atravesar guardias de[n]psicoquinesis.[n][e]

[msg Item_1E2]
[s]RESERVE[n][e]

[msg Item_1E3]
[s]Gema regia que fortalece[n]a quien la porta.[n][e]

[msg Item_1E4]
[s]Un colgante regio que[n]anima el coraz吋n[n]del quien lo porta.[n][e]

[msg Item_1E5]
[s]Una gema regia que mejora[n]el esp胤ritu de quien la porta.[n][e]

[msg Item_1E6]
[s]Una corona regia[n]que hace resplandecer[n]a quien la lleva.[n][e]

[msg Item_1E7]
[s]Una gema m茨gica regia[n]que provoca sufrimiento.[n][e]

[msg Item_1E8]
[s]Una gema m茨gica regia[n]con el poder de un emperador.[n][e]

[msg Item_1E9]
[s]Una gema regia maldita[n]pero curativa.[n][e]

[msg Item_1EA]
[s]Una gema regia m茨gica[n]que ayuda a evitar las[n]habilidades m茨gicas.[n][e]

[msg Item_1EB]
[s]Un metal m茨gico que[n]protege a quien [n]lo porta.[n][e]

[msg Item_1EC]
[s]Un metal regio[n]que protege[n]a quien lo porta.[n][e]

[msg Item_1ED]
[s]Un anillo de la suerte[n]que llevaba un apostador famoso.[n][e]

[msg Item_1EE]
[s]Un netsuke muy[n]impresionante.[n][e]

[msg Item_1EF]
[s]Un broche que permite usar un[n]ataque nuclear a quien lo porta.[n][e]

[msg Item_1F0]
[s]Guante escarlata que baila[n]a la luz de las estrellas.[n][e]

[msg Item_1F1]
[s]Auriculares muy molones.[n][e]

[msg Item_1F2]
[s]El bast吋n favorito[n]de la alcaidesa.[n][e]

[msg Item_1F3]
[s]Capa de plumas que ayuda[n]a esquivar los golpes.[n][e]

[msg Item_1F4]
[s]Aparato con una aplicaci吋n[n]de mejora de armas.[n][e]

[msg Item_1F5]
[s]Cinta hecha para llevar[n]una c茨mara.[n][e]

[msg Item_1F6]
[s]Objeto sin usar[n][e]

[msg Item_1F7]
[s]RESERVE[n][e]

[msg Item_1F8]
[s]RESERVE[n][e]

[msg Item_1F9]
[s]RESERVE[n][e]

[msg Item_1FA]
[s]RESERVE[n][e]

[msg Item_1FB]
[s]RESERVE[n][e]

[msg Item_1FC]
[s]RESERVE[n][e]

[msg Item_1FD]
[s]RESERVE[n][e]

[msg Item_1FE]
[s]RESERVE[n][e]

[msg Item_1FF]
[s]RESERVE[n][e]

