[msg injection00]
[s]Evita la disminuci吋n de PS[n]hasta dos veces.[n][e]

[msg injection01]
[s]Evita la disminuci吋n de PE[n]hasta dos veces.[n][e]

[msg injection02]
[s]Evita la disminuci吋n de PS[n]hasta tres veces.[n][e]

[msg injection03]
[s]Evita la disminuci吋n de PE[n]hasta tres veces.[n][e]

[msg injection04]
[s]Evita la disminuci吋n de PE[n]hasta dos veces.[n][e]

[msg injectiond05]
[s]Puede anular[n]los ataques de fuego.[n][e]

[msg injection06]
[s]Puede anular[n]los ataques de hielo.[n][e]

[msg injection07]
[s]Puede anular[n]los ataques de electricidad.[n][e]

[msg injection08]
[s]Puede anular[n]los ataques de viento.[n][e]

[msg injection09]
[s]Puede anular[n]los ataques psicoquin姻ticos.[n][e]

[msg injection10]
[s]Puede anular[n]los ataques nucleares.[n][e]

[msg injection11]
[s]Puede anular[n]los ataques de bendici吋n.[n][e]

[msg injection12]
[s]Puede anular[n]los ataques de maldici吋n.[n][e]

[msg injection13]
[s]Puede anular[n]los ataques f胤sicos.[n][e]

[msg injection14]
[s]注射のヘルプ15[n]効果をここに書くこと[n][e]

