[msg item_000]
[s]En blanco[n][e]

[msg Item_001]
[s]Sin usar[n][e]

[msg Item_002]
[s]Sin usar[n][e]

[msg Item_003]
[s]Sin usar[n][e]

[msg Item_004]
[s]Sin usar[n][e]

[msg Item_005]
[s]Sin usar[n][e]

[msg Item_006]
[s]Sin usar[n][e]

[msg Item_007]
[s]Sin usar[n][e]

[msg Item_008]
[s]Sin usar[n][e]

[msg Item_009]
[s]Sin usar[n][e]

[msg Item_00A]
[s]Sin usar[n][e]

[msg Item_00B]
[s]Sin usar[n][e]

[msg Item_00C]
[s]Sin usar[n][e]

[msg Item_00D]
[s]Sin usar[n][e]

[msg Item_00E]
[s]Sin usar[n][e]

[msg Item_00F]
[s]Sin usar[n][e]

[msg Item_010]
[s]Sin usar[n][e]

[msg Item_011]
[s]Sin usar[n][e]

[msg Item_012]
[s]Un bast吋n resplandeciente.[n]Se vende por mucho dinero.[n][e]

[msg Item_013]
[s]Se toca al celebrar algo.[n]Se vende por mucho dinero.[n][e]

[msg Item_014]
[s]Se da a los ganadores.[n]Se vende por mucho dinero.[n][e]

[msg Item_015]
[s]Una bonita taza de t姻 de porcelana.[n]Se vende por bastante dinero.[n][e]

[msg Item_016]
[s]De acero inoxidable.[n]Se vende por bastante dinero.[n][e]

[msg Item_017]
[s]Tiene una llama misteriosa.[n]Se vende por bastante dinero.[n][e]

[msg Item_018]
[s]Le gotea cera.[n]Se vende por bastante dinero.[n][e]

[msg Item_019]
[s]Tiene una bola y una cadena.[n]Se vende por algo de dinero.[n][e]

[msg Item_01A]
[s]Un collar con candado.[n]Se vende por algo de dinero.[n][e]

[msg Item_01B]
[s]El filo est茨 quebrado.[n]Se vende por algo de dinero.[n][e]

[msg Item_01C]
[s]Tiene un gran agujero.[n]Se vende por poco dinero.[n][e]

[msg Item_01D]
[s]Se ha doblado de muchas formas.[n]Se vende por poco dinero.[n][e]

[msg Item_01E]
[s]Parece que se han usado.[n]Se venden por poco dinero.[n][e]

[msg Item_01F]
[s]Una copa de vino con desperfectos.[n]Se vende por poco dinero.[n][e]

[msg Item_020]
[s]Una obra de una hermosa mujer.[n]Se vende por mucho dinero.[n][e]

[msg Item_021]
[s]Muestra un hermoso paisaje.[n]Se vende por mucho dinero.[n][e]

[msg Item_022]
[s]Con muchas flores y p茨jaros.[n]Se vende por mucho dinero.[n][e]

[msg Item_023]
[s]Tiene un gran contenido sat胤rico.[n]Se vende por bastante dinero.[n][e]

[msg Item_024]
[s]Se usa en representaciones de noh.[n]Se vende por bastante dinero.[n][e]

[msg Item_025]
[s]Hecha con pelo animal.[n]Se vende por bastante dinero.[n][e]

[msg Item_026]
[s]Resulta agradable escribir encima.[n]Se vende por algo de dinero.[n][e]

[msg Item_027]
[s]El bordado est茨 suelto.[n]Se vende por algo de dinero.[n][e]

[msg Item_028]
[s]Un jarr吋n peque隠o con desperfectos.[n]Se vende por algo de dinero.[n][e]

[msg Item_029]
[s]Una tetera de hierro.[n]Se vende por algo de dinero.[n][e]

[msg Item_02A]
[s]Parece que se hizo a mano.[n]Se vende por poco dinero.[n][e]

[msg Item_02B]
[s]De pl茨stico ligero.[n]Se vende por poco dinero.[n][e]

[msg Item_02C]
[s]Un retrato hecho por un aficionado.[n]Se vende por poco dinero.[n][e]

[msg Item_02D]
[s]Una escultura torcida.[n]Se vende por poco dinero.[n][e]

[msg Item_02E]
[s]Una moneda conmemorativa.[n]Se vende por mucho dinero.[n][e]

[msg Item_02F]
[s]Para una gran compa隠胤a alimenticia.[n]Se vende por mucho dinero.[n][e]

[msg Item_030]
[s]Un sello de 茨mbar.[n]Se vende por mucho dinero.[n][e]

[msg Item_031]
[s]Un billete viejo muy valioso.[n]Se vende por bastante dinero.[n][e]

[msg Item_032]
[s]Una moneda antigua rara.[n]Se vende por bastante dinero.[n][e]

[msg Item_033]
[s]Se usa en viejos festivales.[n]Se vende por bastante dinero.[n][e]

[msg Item_034]
[s]Un estuche de cuero para sellos.[n]Se vende por algo de dinero.[n][e]

[msg Item_035]
[s]De la puerta de una caja fuerte.[n]Se vende por algo de dinero.[n][e]

[msg Item_036]
[s]Se usa para contar billetes.[n]Se vende por algo de dinero.[n][e]

[msg Item_037]
[s]Lo usan los banqueros.[n]Se vende por algo de dinero.[n][e]

[msg Item_038]
[s]Se ha quedado sin tinta.[n]Se vende por poco dinero.[n][e]

[msg Item_039]
[s]No se puede abrir.[n]Se vende por poco dinero.[n][e]

[msg Item_03A]
[s]Se ha usado bastante.[n]Se vende por poco dinero.[n][e]

[msg Item_03B]
[s]Una cartera vieja usada.[n]Se vende por poco dinero.[n][e]

[msg Item_03C]
[s]Con gemas de adorno.[n]Se vende por mucho dinero.[n][e]

[msg Item_03D]
[s]Blas吋n con una serpiente.[n]Se vende por mucho dinero.[n][e]

[msg Item_03E]
[s]Lleno de 吋rganos.[n]Se vende por mucho dinero.[n][e]

[msg Item_03F]
[s]Cabe en una mano.[n]Se vende por bastante dinero.[n][e]

[msg Item_040]
[s]Una piedra con forma de escarabajo.[n]Se vende por bastante dinero.[n][e]

[msg Item_041]
[s]La llevan las momias.[n]Se vende por bastante dinero.[n][e]

[msg Item_042]
[s]Una espada machacada.[n]Se vende por algo de dinero.[n][e]

[msg Item_043]
[s]Una cruz egipcia oxidada.[n]Se vende por algo de dinero.[n][e]

[msg Item_044]
[s]Demasiado roto para descifrarlo.[n]Se vende por algo de dinero.[n][e]

[msg Item_045]
[s]Un trozo de un mural.[n]Se vende por algo de dinero.[n][e]

[msg Item_046]
[s]Un fragmento de un mural.[n]Se vende por algo de dinero.[n][e]

[msg Item_047]
[s]Un trozo de un ata雨d.[n]Se vende por poco dinero.[n][e]

[msg Item_048]
[s]Un bast吋n con jerogl胤ficos.[n]Se vende por poco dinero.[n][e]

[msg Item_049]
[s]Del pilar del altar.[n]Se vende por poco dinero.[n][e]

[msg Item_04A]
[s]Roca que podr胤a ser lunar.[n]Se vende por mucho dinero.[n][e]

[msg Item_04B]
[s]Metal que no parece[n]provenir de este planeta.[n]Se vende por mucho dinero.[n][e]

[msg Item_04C]
[s]Se usa desde la antig鵜edad.[n]Se vende por mucho dinero.[n][e]

[msg Item_04D]
[s]Nave espacial de juguete.[n]Se vende por bastante dinero.[n][e]

[msg Item_04E]
[s]Una linterna port茨til.[n]Se vende por bastante dinero.[n][e]

[msg Item_04F]
[s]Emite luces de todos los colores.[n]Se vende por bastante dinero.[n][e]

[msg Item_050]
[s]Se usa para dirigir astronaves.[n]Se vende por algo de dinero.[n][e]

[msg Item_051]
[s]De un androide.[n]Se vende por algo de dinero.[n][e]

[msg Item_052]
[s]Se usa para captar se隠ales.[n]Se vende por algo de dinero.[n][e]

[msg Item_053]
[s]Una versi吋n mini de bolsillo.[n]Se vende por algo de dinero.[n][e]

[msg Item_054]
[s]Comida congelada para el espacio.[n]Se vende por poco dinero.[n][e]

[msg Item_055]
[s]Una placa de circuitos rota.[n]Se vende por poco dinero.[n][e]

[msg Item_056]
[s]Tambi姻n es popular en el espacio.[n]Se vende por poco dinero.[n][e]

[msg Item_057]
[s]Pieza de una nave espacial.[n]Se vende por poco dinero.[n][e]

[msg Item_058]
[s]Hecho por un artesano famoso.[n]Se vende por mucho dinero.[n][e]

[msg Item_059]
[s]Pendientes peque隠os pero valiosos.[n]Se vende por mucho dinero.[n][e]

[msg Item_05A]
[s]Con gemas incrustadas.[n]Se vende por mucho dinero.[n][e]

[msg Item_05B]
[s]El marco es de plata.[n]Se vende por bastante dinero.[n][e]

[msg Item_05C]
[s]Tallado en marfil.[n]Se vende por bastante dinero.[n][e]

[msg Item_05D]
[s]A los crupieres h茨biles les gusta.[n]Se vende por bastante dinero.[n][e]

[msg Item_05E]
[s]Del tipo que les gusta a los magos.[n]Se vende por algo de dinero.[n][e]

[msg Item_05F]
[s]Tiene un centro muy estable.[n]Se vende por algo de dinero.[n][e]

[msg Item_060]
[s]Hace que barajar sea f茨cil.[n]Se vende por algo de dinero.[n][e]

[msg Item_061]
[s]Lanza al tocarlo.[n]Se vende por algo de dinero.[n][e]

[msg Item_062]
[s]Para cerrar los pu隠os de la camisa.[n]Se vende por poco dinero.[n][e]

[msg Item_063]
[s]Ha perdido su color.[n]Se vende por poco dinero.[n][e]

[msg Item_064]
[s]Caro pero usado.[n]Se vende por poco dinero.[n][e]

[msg Item_065]
[s]No es una baraja completa.[n]Se vende por poco dinero.[n][e]

[msg Item_066]
[s]Bisuter胤a hecha de coral.[n]Se vende por mucho dinero.[n][e]

[msg Item_067]
[s]Lleno de perlas negras.[n]Se vende por mucho dinero.[n][e]

[msg Item_068]
[s]Un estuche de cosm姻ticos elegante.[n]Se vende por mucho dinero.[n][e]

[msg Item_069]
[s]De m茨rmol.[n]Se vende por bastante dinero.[n][e]

[msg Item_06A]
[s]De caparaz吋n de tortuga.[n]Se vende por bastante dinero.[n][e]

[msg Item_06B]
[s]Tiene una concha grabada.[n]Se vende por bastante dinero.[n][e]

[msg Item_06C]
[s]Con adornos de concha reluciente.[n]Se vende por bastante dinero.[n][e]

[msg Item_06D]
[s]Se basa en un pavo real.[n]Se vende por algo de dinero.[n][e]

[msg Item_06E]
[s]Se cre吋 con habilidad.[n]Se vende por algo de dinero.[n][e]

[msg Item_06F]
[s]Viene con una tapa.[n]Se vende por algo de dinero.[n][e]

[msg Item_070]
[s]De los de dar cuerda.[n]Se vende por poco dinero.[n][e]

[msg Item_071]
[s]Da un aire muy nost茨lgico.[n]Se vende por poco dinero.[n][e]

[msg Item_072]
[s]Ilumina la pista de baile.[n]Se vende por poco dinero.[n][e]

[msg Item_073]
[s]Se usa para ocultar la identidad.[n]Se vende por poco dinero.[n][e]

[msg Item_074]
[s]En blanco[n][e]

[msg Item_075]
[s]En blanco[n][e]

[msg Item_076]
[s]En blanco[n][e]

[msg Item_077]
[s]En blanco[n][e]

[msg Item_078]
[s]En blanco[n][e]

[msg Item_079]
[s]En blanco[n][e]

[msg Item_07A]
[s]En blanco[n][e]

[msg Item_07B]
[s]En blanco[n][e]

[msg Item_07C]
[s]En blanco[n][e]

[msg Item_07D]
[s]En blanco[n][e]

[msg Item_07E]
[s]En blanco[n][e]

[msg Item_07F]
[s]En blanco[n][e]

[msg Item_080]
[s]En blanco[n][e]

[msg Item_081]
[s]En blanco[n][e]

[msg Item_082]
[s]Un mont吋n de oro de gran tama隠o.[n]Se vende por bastante dinero.[n][e]

[msg Item_083]
[s]Un mont吋n de oro de buen tama隠o.[n]Se vende por bastante dinero.[n][e]

[msg Item_084]
[s]Un peque隠o mont吋n de oro.[n]Se vende por bastante dinero.[n][e]

[msg Item_085]
[s]Moneda de plata dentada.[n]Se vende por algo de dinero.[n][e]

[msg Item_086]
[s]Moneda de plata con un agujero.[n]Se vende por algo de dinero.[n][e]

[msg Item_087]
[s]Una moneda fina de plata.[n]Se vende por algo de dinero.[n][e]

[msg Item_088]
[s]Moneda de cobre dentada.[n]Se vende por poco dinero.[n][e]

[msg Item_089]
[s]Moneda de cobre con un agujero.[n]Se vende por poco dinero.[n][e]

[msg Item_08A]
[s]Una moneda fina de cobre.[n]Se vende por poco dinero.[n][e]

[msg Item_08B]
[s]Una hermosa gema de color negro.[n]Se vende por un dineral.[n][e]

[msg Item_08C]
[s]Una gema redonda de color blanco.[n]Se vende por un dineral.[n][e]

[msg Item_08D]
[s]Una gema de color violeta claro.[n]Se vende por un dineral.[n][e]

[msg Item_08E]
[s]Una gema de color azul v胤vido.[n]Se vende por un dineral.[n][e]

[msg Item_08F]
[s]Una gema multicolor.[n]Se vende por un dineral.[n][e]

[msg Item_090]
[s]Una gema amarilla brillante.[n]Se vende por un dineral.[n][e]

[msg Item_091]
[s]Una gema de color rojo carmes胤.[n]Se vende por un dineral.[n][e]

[msg Item_092]
[s]Una gema de color azul aguamarina.[n]Se vende por un dineral.[n][e]

[msg Item_093]
[s]Una gema preciosa de color rojo.[n]Se vende por un dineral.[n][e]

[msg Item_094]
[s]Una gema verde de conocimiento.[n]Se vende por un dineral.[n][e]

[msg Item_095]
[s]Una gema de color azul oscuro.[n]Se vende por un dineral.[n][e]

[msg Item_096]
[s]Una gema que brilla con encanto.[n]Se vende por un dineral.[n][e]

[msg Item_097]
[s]Una gema de color verde oscuro.[n]Se vende por un dineral.[n][e]

[msg Item_098]
[s]En blanco[n][e]

[msg Item_099]
[s]En blanco[n][e]

[msg Item_09A]
[s]En blanco[n][e]

[msg Item_09B]
[s]En blanco[n][e]

[msg Item_09C]
[s]En blanco[n][e]

[msg Item_09D]
[s]En blanco[n][e]

[msg Item_09E]
[s]En blanco[n][e]

[msg Item_09F]
[s]En blanco[n][e]

[msg Item_0A0]
[s]En blanco[n][e]

[msg Item_0A1]
[s]Un mont吋n de un metal[n]precioso de color plateado.[n]Se vende por un dineral.[n][e]

[msg Item_0A2]
[s]Equipamiento quir雨rgico[n]que no se enciende.[n]Se vende por poco dinero.[n][e]

[msg Item_0A3]
[s]Cinta de casete desenrollada.[n]Se vende por poco dinero.[n][e]

[msg Item_0A4]
[s]Cables inextricables.[n]Se vende por poco dinero.[n][e]

[msg Item_0A5]
[s]P吋ster con erratas.[n]Se vende por poco dinero.[n][e]

[msg Item_0A6]
[s]Grabadora sin usar.[n]Se vende por algo de dinero.[n][e]

[msg Item_0A7]
[s]No se enciende.[n]Se vende por algo de dinero.[n][e]

[msg Item_0A8]
[s]Conversor de voltaje antiguo.[n]Se vende por algo de dinero.[n][e]

[msg Item_0A9]
[s]Medidor extra隠o.[n]Se vende por algo de dinero.[n][e]

[msg Item_0AA]
[s]Lente industrial distorsionada.[n]Se vende por algo de dinero.[n][e]

[msg Item_0AB]
[s]Protector desgastado.[n]Se vende por un dineral.[n][e]

[msg Item_0AC]
[s]Sensor de sonido.[n]Se vende por un dineral.[n][e]

[msg Item_0AD]
[s]Aparato con un control[n]de temperatura roto.[n]Se vende por un dineral.[n][e]

[msg Item_0AE]
[s]Maruki: supercaro S[n][e]

[msg Item_0AF]
[s]Maruki: supercaro S[n][e]

[msg Item_0B0]
[s]En blanco[n][e]

[msg Item_0B1]
[s]Joya de la c茨rcel[n][e]

[msg Item_0B2]
[s]Cuerno que no hace ruido.[n]Se vende por poco dinero.[n][e]

[msg Item_0B3]
[s]Gorra de uniforme con un agujero.[n]Se vende por poco dinero.[n][e]

[msg Item_0B4]
[s]Porra rota e inservible.[n]Se vende por poco dinero.[n][e]

[msg Item_0B5]
[s]Esposas que no cierran.[n]Se vende por poco dinero.[n][e]

[msg Item_0B6]
[s]Bola de hierro con correa negra.[n]Se vende por algo de dinero.[n][e]

[msg Item_0B7]
[s]Uniforme de c茨rcel en buen estado.[n]Se vende por algo de dinero.[n][e]

[msg Item_0B8]
[s]Insignia reluciente.[n]Se vende por algo de dinero.[n][e]

[msg Item_0B9]
[s]Meg茨fono que se oye[n]desde cualquier parte.[n]Se vende por algo de dinero.[n][e]

[msg Item_0BA]
[s]Alambre de p雨as muy afiladas.[n]Se vende por algo de dinero.[n][e]

[msg Item_0BB]
[s]Insignia con un brillo dorado.[n]Se vende por un dineral.[n][e]

[msg Item_0BC]
[s]Insignia dorada para gorras.[n]Se vende por un dineral.[n][e]

[msg Item_0BD]
[s]Brazalete de color plateado.[n]Se vende por un dineral.[n][e]

[msg Item_0BE]
[s]C茨rcel: supercaro S[n][e]

[msg Item_0BF]
[s]C茨rcel: supercaro S[n][e]

[msg Item_0C0]
[s]En blanco[n][e]

[msg Item_0C1]
[s]Mont吋n de cobre reluciente.[n]Se vende por algo de dinero.[n][e]

[msg Item_0C2]
[s]Cadena de lujo hecha[n]de cobre reluciente.[n]Se vende por poco dinero.[n][e]

[msg Item_0C3]
[s]Objeto de cobre[n]con forma de mano.[n]Se vende por poco dinero.[n][e]

[msg Item_0C4]
[s]Objeto de cobre[n]con forma de coraz吋n.[n]Se vende car胤simo.[n][e]

[msg Item_0C5]
[s]Objeto de cobre reluciente[n]con forma de estrella.[n]Se vende car胤sima.[n][e]

[msg Item_0C6]
[s]Objeto de cobre[n]con forma de luna.[n]Se vende por una fortuna.[n][e]

[msg Item_0C7]
[s]Objeto de niebla de cobre.[n]Se vende[n]por una fortuna.[n][e]

[msg Item_0C8]
[s]Un gran mont吋n de[n]plata reluciente.[n]Se vende por poco dinero.[n][e]

[msg Item_0C9]
[s]Cadena de lujo hecha[n]de plata reluciente.[n]Se vende car胤sima.[n][e]

[msg Item_0CA]
[s]Objeto de plata[n]con forma de mano.[n]Se vende car胤sima.[n][e]

[msg Item_0CB]
[s]Objeto de plata[n]con forma de coraz吋n.[n]Se vende car胤simo.[n][e]

[msg Item_0CC]
[s]Objeto de plata reluciente[n]con forma de estrella.[n]Se vende car胤sima.[n][e]

[msg Item_0CD]
[s]Objeto de plata[n]con forma de luna.[n]Se vende por una fortuna.[n][e]

[msg Item_0CE]
[s]Objeto de niebla de plata.[n]Se vende[n]por una fortuna.[n][e]

[msg Item_0CF]
[s]Un gran mont吋n de oro.[n]Se vende car胤sima.[n][e]

[msg Item_0D0]
[s]Cadena de lujo hecha[n]de oro reluciente.[n]Se vende car胤sima.[n][e]

[msg Item_0D1]
[s]Objeto de oro[n]con forma de mano.[n]Se vende car胤sima.[n][e]

[msg Item_0D2]
[s]Objeto de oro[n]con forma de coraz吋n.[n]Se vende car胤simo.[n][e]

[msg Item_0D3]
[s]Objeto de oro reluciente[n]con forma de estrella.[n]Se vende car胤sima.[n][e]

[msg Item_0D4]
[s]Objeto de oro reluciente[n]con forma de luna.[n]Se vende por una locura.[n][e]

[msg Item_0D5]
[s]Objeto de niebla de oro.[n]Se vende por una locura.[n][e]

[msg Item_0D6]
[s]Un mont吋n de platino.[n]Se vende car胤sima.[n][e]

[msg Item_0D7]
[s]Un mont吋n de diamantes.[n]Se vende[n]por una fortuna.[n][e]

[msg Item_0D8]
[s]En blanco[n][e]

[msg Item_0D9]
[s]En blanco[n][e]

[msg Item_0DA]
[s]En blanco[n][e]

[msg Item_0DB]
[s]En blanco[n][e]

[msg Item_0DC]
[s]En blanco[n][e]

[msg Item_0DD]
[s]En blanco[n][e]

[msg Item_0DE]
[s]En blanco[n][e]

[msg Item_0DF]
[s]En blanco[n][e]

[msg Item_0E0]
[s]En blanco[n][e]

[msg Item_0E1]
[s]En blanco[n][e]

[msg Item_0E2]
[s]En blanco[n][e]

[msg Item_0E3]
[s]En blanco[n][e]

[msg Item_0E4]
[s]En blanco[n][e]

[msg Item_0E5]
[s]En blanco[n][e]

[msg Item_0E6]
[s]En blanco[n][e]

[msg Item_0E7]
[s]En blanco[n][e]

[msg Item_0E8]
[s]En blanco[n][e]

[msg Item_0E9]
[s]En blanco[n][e]

[msg Item_0EA]
[s]En blanco[n][e]

[msg Item_0EB]
[s]En blanco[n][e]

[msg Item_0EC]
[s]En blanco[n][e]

[msg Item_0ED]
[s]En blanco[n][e]

[msg Item_0EE]
[s]En blanco[n][e]

[msg Item_0EF]
[s]En blanco[n][e]

[msg Item_0F0]
[s]En blanco[n][e]

[msg Item_0F1]
[s]En blanco[n][e]

[msg Item_0F2]
[s]En blanco[n][e]

[msg Item_0F3]
[s]En blanco[n][e]

[msg Item_0F4]
[s]En blanco[n][e]

[msg Item_0F5]
[s]En blanco[n][e]

[msg Item_0F6]
[s]En blanco[n][e]

[msg Item_0F7]
[s]En blanco[n][e]

[msg Item_0F8]
[s]En blanco[n][e]

[msg Item_0F9]
[s]En blanco[n][e]

[msg Item_0FA]
[s]En blanco[n][e]

[msg Item_0FB]
[s]En blanco[n][e]

[msg Item_0FC]
[s]En blanco[n][e]

[msg Item_0FD]
[s]En blanco[n][e]

[msg Item_0FE]
[s]En blanco[n][e]

[msg Item_0FF]
[s]En blanco[n][e]

