[msg quest00]
[s]No hab姻is llevado a cabo la misi吋n.[n][w][e]

[msg quest_notice_00]
[s]斡Despertad el coraz吋n del objetivo [n]en Mementos![n][w][e]

[msg quest_clear_01]
[s]Parece que hemos conseguido[n]despertar el coraz吋n del objetivo.[n]Vamos a comprobarlo.[n][w][e]

[msg quest_clear_02]
[s]Parece que hemos despertado[n]el coraz吋n del objetivo.[n][w][e]

[msg quest_faild]
[s]Parece que el objetivo[n]ha desaparecido en las[n]profundidades de Mementos...[n][w][e]

[msg questTEST_0]
[s]クエストのテストメッセージ。[n]これは概要です。[n][w][e]

[msg questTEST_1]
[s]クエストのテストメッセージ。[n]これは調査中です。[n][w][e]

[msg questTEST_2]
[s]クエストのテストメッセージ。[n]これは受注可能です。[n][w][e]

[msg quest01_0]
[s]Ann me habl吋 de un host que se[n]aprovecha de mujeres y se deshace[n]de ellas cuando ya no las necesita.[n][w][e]

[msg quest01_2]
[s]Tengo informaci吋n interesante[n]de parte de Ann. 斡Ya tenemos un nombre,[n]as胤 que vayamos al escondite![n][w][e]

[msg quest02_0]
[s]Un ama de casa codiciosa[n]que coge las cosas de los dem茨s[n]est茨 dando problemas...[n][w][e]

[msg quest02_1]
[s]Esta ama de casa codiciosa[n]que coge las cosas de los dem茨s[n]suele estar por la calle principal.[n][w][e]

[msg quest02_2]
[s]Mishima me habl吋 de un ama de casa[n]que coge las cosas de los dem茨s. 斡Ya sabemos su nombre![n]斡Nos vemos en el escondite![n][w][e]

[msg quest03_0]
[s]Un estudiante acosa a otro[n]delante del Instituto Shujin[n]como si fuera una broma...[n][w][e]

[msg quest03_1]
[s]Me he enterado de un caso de acoso[n]cerca de la entrada del instituto.[n]Investigu姻moslo cuando podamos.[n][w][e]

[msg quest03_2]
[s]S姻 qui姻n es el abus吋n del[n]Shujin. Sabemos su nombre,[n]as胤 que nos vemos en el escondite.[n][w][e]

[msg quest04_0]
[s]Ryuji me ha hablado de una madre[n]taca隠a y ego胤sta que no quiere[n]pagar la comida del instituto.[n][w][e]

[msg quest04_2]
[s]Ryuji me ha hablado de una madre[n]taca隠a y ego胤sta. Sabemos su nombre,[n]as胤 que nos vemos en el escondite.[n][w][e]

[msg quest05_0]
[s]S姻 de un ama de casa que se cree[n]con derecho a tantas cosas que[n]no para de quejarse.[n][w][e]

[msg quest05_1]
[s]Mishima dice que en el foro[n]han hablado de un ama de casa[n]que no para de quejarse.[n][w][e]

[msg quest05_2]
[s]Mishima me ha hablado de un ama de[n]casa muy quejica. Sabemos su[n]nombre. 斡Nos vemos en el escondite![n][w][e]

[msg quest07_0]
[s]Hay una alumna que tiene[n]unos celos muy peligrosos por[n]el chico que le gusta.[n][w][e]

[msg quest07_1]
[s]Mishima me ha contado lo de la[n]estudiante ciberacosadora. Busqu姻mosla[n]por el campus del Shujin.[n][w][e]

[msg quest07_2]
[s]Mishima me ha hablado de la[n]ciberacosadora. Sabemos su nombre,[n]as胤 que nos vemos en el escondite.[n][w][e]

[msg quest08_0]
[s]クエ08概要(不要)[n][w][e]

[msg quest08_1]
[s]クエ08調査中(不要)[n][w][e]

[msg quest08_2]
[s]Nuestro objetivo parece estar[n]en alg雨n lugar de Mementos.[n]斡Hay que encontrarlo![n][w][e]

[msg quest09_0]
[s]Un banquero se dedica a abusar[n]de su autoridad para malversar[n]fondos del sitio en el que trabaja.[n][w][e]

[msg quest09_1]
[s]S姻 de un delincuente que malversa[n]dinero de un banco.[n][w][e]

[msg quest09_2]
[s]Mishima me ha hablado de[n]un malversador. Sabemos su nombre,[n]as胤 que nos vemos en el escondite.[n][w][e]

[msg quest10_0]
[s]Un cliente problem茨tico molesta[n]a una empleada de la tienda[n]en la que trabajo a tiempo parcial.[n][w][e]

[msg quest10_1]
[s]Mi compa隠era de la tienda me habl吋[n]del hombre que ha estado[n]acosando a las trabajadoras.[n][w][e]

[msg quest10_2]
[s]Ya s姻 qui姻n es el tipo de[n]la tienda. Sabemos su nombre.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest11_0]
[s]Igual que los Ladrones Fantasma,[n]un grupo ha estado robando[n]en los restaurantes de Shibuya.[n][w][e]

[msg quest11_1]
[s]He o胤do algo sobre un grupo secreto[n]que se dedica a robar en Shibuya.[n]Busquemos pistas.[n][w][e]

[msg quest11_2]
[s]Tengo pistas sobre los ladrones de[n]Shibuya. Sabemos su nombre,[n]as胤 que nos vemos en el escondite.[n][w][e]

[msg quest12_0]
[s]Un estudiante se dedica a acosar[n]a los dem茨s y a delinquir como[n]si fuera un mafioso o algo as胤.[n][w][e]

[msg quest12_1]
[s]Este es el cabecilla abus吋n[n]cuyo coraz吋n despertamos. Est茨[n]cerca de la entrada del instituto.[n][w][e]

[msg quest12_2]
[s]S姻 qui姻n es el cabecilla[n]de los abusones. Sabemos su nombre.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest13_0]
[s]La madre de una empleada de[n]la florister胤a se gasta el dinero[n]de toda la familia en el juego.[n][w][e]

[msg quest13_1]
[s]Mi compa隠era de la florister胤a[n]me ha hablado de su madre,[n]que est茨 enganchada al juego.[n][w][e]

[msg quest13_2]
[s]En el trabajo me han hablado de[n]una lud吋pata. S姻 su nombre,[n]as胤 que nos vemos en el escondite.[n][w][e]

[msg quest15_0]
[s]Hay un se隠or mayor muy vanidoso[n]que no para de evocar el pasado[n]y criticar a los j吋venes.[n][w][e]

[msg quest15_1]
[s]Mishima me ha hablado del rumor que[n]corre por el foro sobre un viejales[n]arrogante y cascarrabias.[n][w][e]

[msg quest15_2]
[s]Mishima me ha hablado de un viejo[n]gru隠吋n. Sabemos su nombre,[n]as胤 que nos vemos en el escondite.[n][w][e]

[msg quest19_0]
[s]Un promotor sin escr雨pulos ha[n]amenazado a un se隠or mayor para[n]que venda su cine de Yongen-Jaya.[n][w][e]

[msg quest19_1]
[s]Mishima me ha dicho que en el foro[n]se ha publicado algo sobre[n]un promotor sin escr雨pulos.[n][w][e]

[msg quest19_2]
[s]Mishima me ha hablado del promotor[n]de Yongen-Jaya. Sabemos su nombre.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest21_0]
[s]Una alumna que se cree[n]superimportante trata a[n]los novatos como esclavos.[n][w][e]

[msg quest21_1]
[s]Mishima me ha dicho que en el foro[n]se ha publicado algo sobre una[n]alumna d姻spota.[n][w][e]

[msg quest21_2]
[s]Mishima me ha hablado[n]de una d姻spota del Kosei. Sabemos su[n]nombre. 斡Nos vemos en el escondite![n][w][e]

[msg quest22_0]
[s]Un trabajador desesperado[n]que no se atreve a enfrentarse[n]a su jefe planea liarla.[n][w][e]

[msg quest22_2]
[s]Yusuke me ha hablado de un empleado[n]desesperado. Sabemos su nombre,[n]as胤 que nos vemos en el escondite.[n][w][e]

[msg quest23_0]
[s]Un alumno est茨 chantajeando [n]a otro de un curso inferior [n]para que le haga recados.[n][w][e]

[msg quest23_1]
[s]He o胤do en la tienda que hay[n]un alumno del Shujin que mangonea[n]a otro de un curso inferior.[n][w][e]

[msg quest23_2]
[s]Un alumno del Shujin obliga a otro [n]a hacerle recados. S姻 su nombre.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest24_0]
[s]Kaneshiro, un joven falsificador,[n]est茨 haciendo circular dinero[n]falso por la calle principal.[n][w][e]

[msg quest24_1]
[s]Mishima me ha dicho que en el foro[n]se ha publicado algo sobre un tal[n]Kaneshiro, un joven falsificador.[n][w][e]

[msg quest24_2]
[s]Mishima me ha hablado de Kaneshiro,[n]el falsificador. Sabemos su nombre.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest25_0]
[s]Futaba me ha hablado de un polic胤a[n]negligente que pasa[n]de los informes sobre acoso.[n][w][e]

[msg quest25_2]
[s]Futaba me ha hablado de un polic胤a[n]negligente. Sabemos su nombre.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest26_0]
[s]He o胤do que un jefe de mediana[n]edad abusa de su autoridad con[n]las personas que tiene a su cargo.[n][w][e]

[msg quest26_1]
[s]En el bar donde trabajo he o胤do que[n]un jefe de mediana edad abusa de[n]las personas que tiene a su cargo.[n][w][e]

[msg quest26_2]
[s]S姻 de un jefe de mediana edad[n]que se pasa mucho. Sabemos su nombre.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest27_0]
[s]Un jugador de Gun About,[n]el famoso videojuego, hace trampas[n]para ganar las partidas online.[n][w][e]

[msg quest27_1]
[s]Por el mundo de los juegos corre el[n]rumor de que alguien hace trampas[n]en partidas online de Gun About.[n][w][e]

[msg quest27_2]
[s]Un jugador algo irascible dijo algo[n]sobre un tramposo. Sabemos su nombre.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest28_0]
[s]La hija de la presidenta de la AMPA[n]usa a su madre para chantajear[n]a su profesor, seg雨n Morgana.[n][w][e]

[msg quest28_2]
[s]Morgana dice que una alumna acosa[n]a su profesor. Sabemos su nombre.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest29_0]
[s]Al parecer hay un asesino[n]en Shibuya que va a volver a matar[n]si nadie hace nada para evitarlo.[n][w][e]

[msg quest29_1]
[s]Mishima me ha hablado[n]de un asesino[n]que merodea por Shibuya.[n][w][e]

[msg quest29_2]
[s]Por fin tengo el nombre[n]del sicario sin hogar. 斡Nos[n]vemos en el escondite![n][w][e]

[msg quest30_0]
[s]Hay una chica a la que su madre[n]obliga a vivir seg雨n ella quiere[n]para cumplir sus propios sue隠os.[n][w][e]

[msg quest30_1]
[s]He o胤do en la tienda algo sobre una[n]chica obligada a hacer cosas para[n]cumplir los sue隠os de su madre.[n][w][e]

[msg quest30_2]
[s]S姻 el nombre de la madre que obliga[n]a su hija a vivir como ella quiere.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest31_0]
[s]Un chico de Akihabara ha estado[n]descargando videojuegos de manera[n]ilegal y encima alardea de ello.[n][w][e]

[msg quest31_1]
[s]Mishima me ha dicho que en el foro[n]se ha hablado de un chaval[n]que pirateaba videojuegos.[n][w][e]

[msg quest31_2]
[s]Hay un chaval acusado de piratear[n]videojuegos. Sabemos su nombre,[n]as胤 que nos vemos en el escondite.[n][w][e]

[msg quest32_0]
[s]Haru me ha hablado de un chaval[n]rico, guapo y lig吋n que encandila a[n]las mujeres para que le den dinero.[n][w][e]

[msg quest32_2]
[s]Hay un chico encantador que enga隠a[n]a las mujeres por dinero. Sabemos su[n]nombre. 斡Nos vemos en el escondite![n][w][e]

[msg quest33_0]
[s]Un productor indecente del mundo[n]del entretenimiento se aprovecha de[n]las j吋venes que buscan la fama.[n][w][e]

[msg quest33_1]
[s]Seg雨n Mishima, hay un productor del[n]mundo del espect茨culo que obliga[n]a sus clientas a acostarse con 姻l.[n][w][e]

[msg quest33_2]
[s]S姻 el nombre del[n]productor desgraciado.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest34_0]
[s]Mishima dice que un encargado de[n]una tienda se dedica a robar[n]y a acosar a los trabajadores.[n][w][e]

[msg quest34_2]
[s]Mishima me habl吋 de un encargado[n]de una tienda corrupto. Sabemos su[n]nombre. 斡Nos vemos en el escondite![n][w][e]

[msg quest35_0]
[s]Una estrella pop se lleva la fama[n]de los Ladrones Fantasma y miente[n]para conseguir m茨s popularidad.[n][w][e]

[msg quest35_1]
[s]Mishima dice que, al parecer, una[n]estrella pop de la calle principal[n]hace cosas raras 雨ltimamente.[n][w][e]

[msg quest35_2]
[s]Tengo el nombre de la estrella[n]del pop, 斡as胤 que nos vemos[n]en el escondite![n][w][e]

[msg quest36_0]
[s]Un director de una empresa no hace[n]nada y se lleva todo el m姻rito[n]de sus subordinados.[n][w][e]

[msg quest36_1]
[s]Mishima conoce a un director de[n]empresa tirano. 斡Vamos[n]al bar de Shinjuku a investigar![n][w][e]

[msg quest36_2]
[s]He o胤do hablar de un empresario[n]muy tirano en el bar. Sabemos su[n]nombre. 斡Nos vemos en el escondite![n][w][e]

[msg quest39_0]
[s]Una profesora mayor del Shujin[n]contrata a gente nueva y la obliga[n]a hacer sus tareas m茨s tediosas.[n][w][e]

[msg quest39_1]
[s]Mishima me ha hablado sobre[n]una profesora mayor del Shujin que[n]se pasa con los profesores nuevos.[n][w][e]

[msg quest39_2]
[s]Sabemos que una profesora del Shujin[n]abusa de los nuevos. Sabemos su[n]nombre. 斡Nos vemos en el escondite![n][w][e]

[msg quest40_0]
[s]Me consta que alguien se dedica[n]a atacar a los vagabundos y[n]oficinistas de Shibuya.[n][w][e]

[msg quest40_1]
[s]Mishima dice que alguien ha estado[n]atacando a la gente. Vamos al[n]centro subterr茨neo a investigar.[n][w][e]

[msg quest40_2]
[s]En la florister胤a he o胤do hablar de[n]alguien que asalta a la gente. Sabemos su[n]nombre. 斡Nos vemos en el escondite![n][w][e]

[msg quest42_0]
[s]Alguien borr吋 unos datos vitales[n]y no va a trabajar porque le tiene[n]rencor a su empresa.[n][w][e]

[msg quest42_1]
[s]En el bar donde trabajo se habla de[n]un t胤o que borr吋 datos vitales para[n]su empresa por rencor.[n][w][e]

[msg quest42_2]
[s]En el bar he o胤do hablar de un[n]empleado vengativo. Sabemos su[n]nombre. 斡Nos vemos en el escondite![n][w][e]

[msg quest48_0]
[s]Hay un universitario que paga toda[n]su frustraci吋n con los gatos.[n][w][e]

[msg quest48_1]
[s]Recabemos informaci吋n sobre el caso[n]de los gatos trabajando en la tienda [n]de autoservicio de la calle principal.[n][w][e]

[msg quest48_2]
[s]En la tienda he o胤do algo sobre[n]el que abusa de los gatos. Sabemos su[n]nombre. 斡Nos vemos en el escondite![n][w][e]

[msg quest49_0]
[s]Un hombre avaro que no hace m茨s[n]que pedir dinero intenta huir al[n]extranjero sin saldar sus deudas.[n][w][e]

[msg quest49_1]
[s]Mishima me ha hablado de un deudor[n]que intenta huir.[n]Lo ha le胤do en el foro.[n][w][e]

[msg quest49_2]
[s]Mishima me habl吋 de uno que intenta[n]librarse de sus deudas. Sabemos su[n]nombre. 斡Nos vemos en el escondite![n][w][e]

[msg quest50_0]
[s]Hay gente por ah胤 que se dedica [n]a defraudar para aprovecharse de[n]los mayores y robarles el dinero.[n][w][e]

[msg quest50_1]
[s]Mishima me ha hablado de un joven[n]que se aprovecha de los mayores.[n]Lo ha le胤do en el foro.[n][w][e]

[msg quest50_2]
[s]S姻 de un joven que se aprovecha de[n]los mayores. Sabemos su nombre.[n]斡Nos vemos en el escondite![n][w][e]

[msg quest51_0]
[s]La madre de Shinya, Hanae Oda,[n]tiene un problema de agresividad[n]que afecta gravemente a su hijo.[n][w][e]

[msg quest51_1]
[s]Ayudemos a Shinya [n]y despertemos el coraz吋n[n]de su madre en Mementos.[n][w][e]

[msg quest51_2]
[s]Quiero ayudar a Shinya y despertar[n]el coraz吋n de su madre. Ya sabemos su nombre...[n]斡Nos vemos en el escondite![n][w][e]

[msg quest51_3]
[s]He conseguido despertar el coraz吋n [n]de la madre de Shinya.[n][w][e]

[msg quest52_0]
[s]Una mujer le est茨 pidiendo ayuda a[n]la adivina de Shinjuku porque[n]su novio la maltrata...[n][w][e]

[msg quest52_1]
[s]Vamos a demostrarle a la adivina[n]que el destino se puede cambiar[n]despertando el coraz吋n del novio.[n][w][e]

[msg quest52_2]
[s]Tengo el nombre del tipo que[n]pega a su novia. Vamos al escondite[n]a hablar del tema.[n][w][e]

[msg quest52_3]
[s]He conseguido despertar el coraz吋n[n]del novio maltratador del que[n]me hab胤a hablado la adivina.[n][w][e]

[msg quest53_0]
[s]Yuichi Fukurai, el presidente[n]de la APD, controla a Chihaya...[n][w][e]

[msg quest53_1]
[s]Ayudemos a Chihaya despertando el [n]coraz吋n del presidente en Mementos.[n][w][e]

[msg quest53_2]
[s]Vamos a exponer la verdadera naturaleza del[n]presidente, por Chihaya. Ya tengo su nombre...[n]斡Nos vemos en el escondite![n][w][e]

[msg quest53_3]
[s]He conseguido despertar el coraz吋n[n]del presidente de la APD.[n][w][e]

[msg quest54_0]
[s]Iwai tiene un trato relacionado con[n]sus r姻plicas con un antiguo socio,[n]Tsuda, pero algo no va bien.[n][w][e]

[msg quest54_1]
[s]Despertemos el coraz吋n de Tsuda[n]en Mementos para ayudar a Iwai.[n][w][e]

[msg quest54_2]
[s]El antiguo socio de Iwai lo amenaza[n]para que modifique armas. Sabemos su nombre...[n]斡Nos vemos en el escondite![n][w][e]

[msg quest54_3]
[s]He conseguido despertar[n]el coraz吋n de Tsuda.[n][w][e]

[msg quest55_0]
[s]A Takemi se le atribuy吋 un error de[n]Oyamada, el director m姻dico, en su[n]姻poca en el hospital universitario.[n][w][e]

[msg quest55_1]
[s]Despertemos el coraz吋n de Oyamada,[n]el jefe m姻dico, en Mementos.[n][w][e]

[msg quest55_2]
[s]El antiguo jefe de Takemi est茨[n]intentando arruinar sus pr茨cticas. Sabemos su nombre...[n]斡Nos vemos en el escondite![n][w][e]

[msg quest55_3]
[s]He conseguido despertar[n]el coraz吋n[n]del jefe m姻dico.[n][w][e]

[msg quest56_0]
[s]Kawakami est茨 siendo extorsionada[n]por los tutores de su antiguo[n]alumno, que la culpan de su muerte.[n][w][e]

[msg quest56_1]
[s]Vamos a despertar los corazones de[n]los tutores de su antiguo alumno[n]en Mementos para ayudar a Kawakami.[n][w][e]

[msg quest56_2]
[s]Quiero que se lleven su merecido[n]por amenazar a Kawakami. Tengo sus nombres...[n]斡Nos vemos en el escondite![n][w][e]

[msg quest56_3]
[s]He conseguido despertar el coraz吋n[n]de los tutores.[n][w][e]

[msg quest57_0]
[s]Ohya quiere investigar el caso[n]de su compa隠ero desaparecido, pero[n]su jefe intenta pararle los pies.[n][w][e]

[msg quest57_1]
[s]Vamos a despertar el coraz吋n[n]del jefe para que Ohya pueda[n]investigar la desaparici吋n.[n][w][e]

[msg quest57_2]
[s]Quiero hacer que el jefe de Ohya[n]la deje investigar en paz. Sabemos su nombre...[n]斡Nos vemos en el escondite![n][w][e]

[msg quest57_3]
[s]He conseguido despertar el coraz吋n [n]del jefe de Ohya.[n][w][e]

[msg quest58_0]
[s]Mitsuyo Togo es la controladora[n]madre de una ni隠a famosa,[n]Hifumi...[n][w][e]

[msg quest58_1]
[s]Despertemos el coraz吋n de la madre[n]de Hifumi en Mementos para[n]solucionar el problema.[n][w][e]

[msg quest58_2]
[s]Hifumi est茨 angustiada porque[n]su madre insisti吋 en que perdiera[n]un partido a prop吋sito. 斡Nos vemos en el escondite![n][w][e]

[msg quest58_3]
[s]He conseguido despertar el coraz吋n[n]de la madre de Hifumi.[n][w][e]

[msg quest59_0]
[s]Los padres de Kana, la mejor amiga[n]de Futaba, se aprovechan de ella...[n][w][e]

[msg quest59_1]
[s]Vamos a despertar el coraz吋n[n]de los padres de Kana en Mementos[n]para ayudar a Futaba.[n][w][e]

[msg quest59_2]
[s]Quiero salvar a la mejor amiga[n]de Futaba. Sabemos sus nombres,[n]as胤 que nos vemos en el escondite.[n][w][e]

[msg quest59_3]
[s]He conseguido despertar el coraz吋n[n]de los padres de Kana.[n][w][e]

[msg quest60_0]
[s]El t胤o de Futaba est茨 intentando[n]quitarle la custodia[n]de Futaba al Jefe...[n][w][e]

[msg quest60_1]
[s]Despertemos el coraz吋n del t胤o[n]de Futaba en Mementos para[n]resolver el problema de Sojiro.[n][w][e]

[msg quest60_2]
[s]Tengo que evitar que el t胤o de[n]Futaba amenace el Leblanc. Hablemos[n]con Futaba para pensar en algo.[n][w][e]

[msg quest60_3]
[s]He conseguido despertar[n]el coraz吋n del t胤o de Futaba[n]por el bien de Sojiro.[n][w][e]

[msg quest70_0]
[s]秘宝NPC解禁クエ の概要[n]何が起きてる?[n][w][e]

[msg quest70_1]
[s]秘宝NPC解禁クエ を調査中[n]ターゲットは誰だ?[n][w][e]

[msg quest70_2]
[s]He conseguido informaci吋n sobre[n]el objetivo. 斡Ya tenemos un nombre,[n]as胤 que nos vemos en el escondite![n][w][e]

[msg quest70_3]
[s]斡Despertemos el coraz吋n[n]del objetivo en Mementos![n][w][e]

[msg quest70_4]
[s]He conseguido despertar el coraz吋n[n]del objetivo. Regresemos[n]al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest70_5]
[s]Parece que he logrado despertar[n]el coraz吋n del objetivo.[n][w][e]

[msg quest71_0]
[s]せめて、心だけでも の概要[n]何が起きてる?[n][w][e]

[msg quest71_1]
[s]せめて、心だけでも を調査中[n]ターゲットは誰だ?[n][w][e]

[msg quest71_2]
[s]Ryuji me habl吋 de un quejica desquiciado. 斡Tenemos[n]un nombre, as胤 que nos vemos en el escondite![n]El Meta-Nav dice: 或carta de habilidad: Carga位.[n][w][e]

[msg quest71_3]
[s]Despertemos el coraz吋n del quejica irracional[n]de Mementos y salvemos la tienda[n]de accesorios de Shibuya.[n]En el Meta-Nav pone: 或carta de habilidad: Carga位.[n][w][e]

[msg quest71_4]
[s]He conseguido despertar el coraz吋n[n]del quejica desquiciado. Regresemos[n]al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest71_5]
[s]He conseguido despertar el coraz吋n del quejica[n]irracional. La paz ha vuelto a la tienda[n]de accesorios de Shibuya. [n][w][e]

[msg quest72_0]
[s]町から猫が消えたなら の概要[n]何が起きてる?[n][w][e]

[msg quest72_1]
[s]Morgana me cont吋 que est茨n[n]secuestrando gatos.[n]斡Hora de preguntar por Yongen![n][w][e]

[msg quest72_2]
[s]He conseguido informaci吋n sobre[n]el secuestro de gatos. 斡Nos vemos[n]en el escondite para ir a Mementos![n][w][e]

[msg quest72_3]
[s]He conseguido informaci吋n sobre la[n]secuestradora de gatos. 斡Despertemos[n]su coraz吋n en Mementos![n][w][e]

[msg quest72_4]
[s]He conseguido despertar el coraz吋n[n]de la secuestradora. Regresemos[n]al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest72_5]
[s]He conseguido despertar el coraz吋n[n]de la secuestradora. Ojal茨[n]volvamos a ver gatos en Yongen.[n][w][e]

[msg quest73_0]
[s]くすんだ栄光 の概要[n]何が起きてる?[n][w][e]

[msg quest73_1]
[s]Ann ha mencionado que alguien odia a Shiho.[n]Pregunta por el patio para conseguir informaci吋n.[n][w][e]

[msg quest73_2]
[s]He conseguido informaci吋n sobre la persona[n]que odia a Shiho. 斡Ya tenemos un nombre,[n]as胤 que nos vemos en el escondite![n][w][e]

[msg quest73_3]
[s]He conseguido informaci吋n sobre[n]la persona que odia a Shiho.[n]斡Despertemos su coraz吋n en Mementos![n][w][e]

[msg quest73_4]
[s]He conseguido despertar el coraz吋n[n]del objetivo. Regresemos[n]al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest73_5]
[s]He conseguido despertar[n]el coraz吋n del objetivo.[n]Ann se sentir茨 aliviada.[n][w][e]

[msg quest74_0]
[s]虚構の通貨 の概要[n]何が起きてる?[n][w][e]

[msg quest74_1]
[s]Makoto ha mencionado a una mujer[n]que est茨 cometiendo fraude.[n]斡Recaba informaci吋n en Shibuya y Shinjuku![n][w][e]

[msg quest74_2]
[s]He conseguido informaci吋n sobre la mujer que[n]cometi吋 fraudes de inversi吋n.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest74_3]
[s]He conseguido informaci吋n sobre la mujer que[n]cometi吋 fraudes de inversi吋n.[n]斡Despertemos su coraz吋n en Mementos![n][w][e]

[msg quest74_4]
[s]He conseguido despertar el coraz吋n de la mujer[n]que cometi吋 fraudes de inversi吋n. Regresemos[n]al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest74_5]
[s]He conseguido despertar el coraz吋n de la mujer[n]que cometi吋 fraudes de inversi吋n[n]Ha habido justicia para las v胤ctimas del fraude.[n][w][e]

[msg quest75_0]
[s]冴えないオタクのアンビバレンス の概要[n]何が起きてる?[n][w][e]

[msg quest75_1]
[s]Futaba me ha hablado sobre 或el Asaltante位,[n]que ha estado causando problemas en Akihabara.[n]斡Pregunta por all胤 y por Shinjuku![n][w][e]

[msg quest75_2]
[s]He conseguido informaci吋n sobre 或el Asaltante位,[n]que ha estado causando problemas en Akihabara.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest75_3]
[s]He conseguido informaci吋n sobre 或el Asaltante位,[n]que ha estado causando problemas en Akihabara.[n]斡Despertemos su coraz吋n en Mementos![n][w][e]

[msg quest75_4]
[s]He conseguido despertar el coraz吋n[n]de 或el Asaltante位.[n]Regresemos al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest75_5]
[s]He conseguido despertar el coraz吋n de 或el Asaltante位.[n]La paz ha vuelto a Akihabara.[n][w][e]

[msg quest76_0]
[s]日本画と同人誌 の概要[n]何が起きてる?[n][w][e]

[msg quest76_1]
[s]Yusuke ha mencionado a una artista de dojinshi[n]acusada de plagio. 斡Pregunta[n]por Akihabara y recaba informaci吋n![n][w][e]

[msg quest76_2]
[s]He conseguido informaci吋n sobre la artista[n]de dojinshi que fue acusada de plagio.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest76_3]
[s]Ya tengo informaci吋n sobre la artista de dojinshi[n]a la que acusan de plagio. 斡Despertemos[n]su coraz吋n en Mementos![n][w][e]

[msg quest76_4]
[s]Ya tengo informaci吋n sobre la artista de dojinshi[n]a la que acusan de plagio. Regresemos[n]al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest76_5]
[s]Ya tengo informaci吋n sobre la artista de dojinshi[n]a la que acusan de plagio. Se ha arrepentido y ahora[n]se esforzar茨 para escribir manga.[n][w][e]

[msg quest77_0]
[s]奇跡のドリンク の概要[n]何が起きてる?[n][w][e]

[msg quest77_1]
[s]Haru me ha hablado de un empresario corrupto[n]que vende comida saludable.[n]斡Hora de preguntar en Yongen-Jaya![n][w][e]

[msg quest77_2]
[s]He conseguido informaci吋n sobre el turbio negocio[n]de la comida saludable.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest77_3]
[s]He conseguido informaci吋n sobre el turbio negocio[n]de la comida saludable.[n]斡Despertemos el coraz吋n del objetivo en Mementos![n][w][e]

[msg quest77_4]
[s]He conseguido despertar el coraz吋n del vendedor[n]corrupto de comida saludable.[n]Regresemos al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest77_5]
[s]He conseguido despertar el coraz吋n del vendedor[n]corrupto de comida saludable. Ahora m茨s[n]personas podr茨n buscar un tratamiento adecuado.[n][w][e]

[msg quest78_0]
[s]偶像と一角獣 の概要[n]何が起きてる?[n][w][e]

[msg quest78_1]
[s]He o胤do hablar de un hombre que est茨[n]obsesionado con las famosas. 斡Pregunta[n]por Akihabara y recaba informaci吋n![n][w][e]

[msg quest78_2]
[s]He reunido informaci吋n del obseso[n]de las famosas en Akihabara.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest78_3]
[s]Ya tengo informaci吋n del hombre que est茨[n]obsesionado con las famosas en Akihabara.[n]斡Despertemos su coraz吋n en Mementos![n][w][e]

[msg quest78_4]
[s]He conseguido despertar el coraz吋n del hombre[n]obsesionado con las famosas.[n]Regresemos al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest78_5]
[s]He conseguido despertar el coraz吋n[n]del obseso de las famosas.[n]Ahora su familia podr茨 tener paz de nuevo.[n][w][e]

[msg quest79_0]
[s]代議士と声なき依頼人 の概要[n]何が起きてる?[n][w][e]

[msg quest79_1]
[s]He o胤do hablar sobre un caso de falsas[n]acusaciones en la calle principal. 斡Deber胤a cooperar[n]con Akechi y recabar m茨s informaci吋n![n][w][e]

[msg quest79_2]
[s]He conseguido informaci吋n[n]sobre el caso de la acusaci吋n falsa.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest79_3]
[s]He conseguido informaci吋n[n]sobre el caso de la acusaci吋n falsa.[n]斡Despertemos el coraz吋n del objetivo en Mementos![n][w][e]

[msg quest79_4]
[s]He conseguido despertar el coraz吋n del congresista[n]acus吋 en falso a su hijo.[n]Regresemos al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest79_5]
[s]He conseguido despertar el coraz吋n del congresista[n]que acus吋 en falso a su hijo.[n]Han arrestado al hijo por extorsi吋n.[n][w][e]

[msg quest80_0]
[s]フェイクマン・ショー の概要[n]何が起きてる?[n][w][e]

[msg quest80_1]
[s]He o胤do hablar sobre AIMaask OUZI.[n]Deber胤a preguntar por Kichijoji esta tarde.[n][w][e]

[msg quest80_2]
[s]He conseguido informaci吋n sobre AIMaask OUZI.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest80_3]
[s]He conseguido informaci吋n sobre AIMaask OUZI.[n]斡Despertemos su coraz吋n en Mementos![n][w][e]

[msg quest80_4]
[s]He conseguido despertar[n]el coraz吋n de AIMaask OUZI.[n]Regresemos al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest80_5]
[s]He conseguido despertar[n]el coraz吋n de AIMaask OUZI.[n]Su familia podr茨 tener paz al fin.[n][w][e]

[msg quest81_0]
[s]色男のバラッド の概要[n]何が起きてる?[n][w][e]

[msg quest81_1]
[s]色男のバラッド を調査中[n]ターゲットは誰だ?[n][w][e]

[msg quest81_2]
[s]Ann me ha hablado[n]de un mujeriego cruel. 斡Nos vemos[n]en el escondite para ir a Mementos![n][w][e]

[msg quest81_3]
[s]Ann me ha hablado[n]de un mujeriego cruel. 斡Despertemos[n]su coraz吋n en Mementos![n][w][e]

[msg quest81_4]
[s]He conseguido despertar el coraz吋n[n]del mujeriego cruel. Regresemos[n]al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest81_5]
[s]He conseguido despertar el coraz吋n[n]del mujeriego cruel.[n]Ahora las mujeres estar茨n tranquilas.[n][w][e]

[msg quest82_0]
[s]老人狂騒曲 の概要[n]何が起きてる?[n][w][e]

[msg quest82_1]
[s]Mishima ha mencionado a un anciano problem茨tico.[n]Recaba informaci吋n en Kichijoji por la noche.[n][w][e]

[msg quest82_2]
[s]He conseguido informaci吋n[n]sobre el anciano problem茨tico.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest82_3]
[s]He conseguido informaci吋n sobre[n]el anciano problem茨tico.[n]斡Despertemos su coraz吋n en Mementos![n][w][e]

[msg quest82_4]
[s]He despertado el coraz吋n del anciano[n]que causaba problemas por Kichijoji.[n]Regresemos al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest82_5]
[s]He despertado el coraz吋n del anciano que estaba[n]causando problemas en Kichijoji por la noche.[n]Volver茨 a haber paz por la zona.[n][w][e]

[msg quest83_0]
[s]理想と現実の狭間で の概要[n]何が起きてる?[n][w][e]

[msg quest83_1]
[s]Sumire ha mencionado a una jugadora de pimp吋n[n]a la que han acusado de hacer trampas.[n]斡Pregunta por Shibuya![n][w][e]

[msg quest83_2]
[s]He reunido informaci吋n sobre la jugadora de pimp吋n[n]que ha sido acusada de ama隠ar partidos.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest83_3]
[s]Ya tengo informaci吋n sobre la jugadora[n]a la que han acusado de hacer trampas.[n]斡Despertemos su coraz吋n en Mementos![n][w][e]

[msg quest83_4]
[s]He conseguido despertar el coraz吋n de la jugadora[n]a la que han acusado de hacer trampas.[n]Regresemos al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest83_5]
[s]He conseguido despertar el coraz吋n de la jugadora[n]a la que han acusado de hacer trampas.[n]Esperemos que ahora vaya por el buen camino.[n][w][e]

[msg quest84_0]
[s]僕が僕であるために の概要[n]何が起きてる?[n][w][e]

[msg quest84_1]
[s]仮[n][w][e]

[msg quest84_2]
[s]Mishima me ha hablado sobre un chico[n]que desea su propia muerte.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest84_3]
[s]He obtenido informaci吋n[n]sobre el ni隠o que desea morir.[n]斡Despertemos su coraz吋n en Mementos![n][w][e]

[msg quest84_4]
[s]He conseguido despertar el coraz吋n del chico.[n]Regresemos al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest84_5]
[s]He conseguido despertar el coraz吋n del chico.[n]Ahora los hermanos podr茨n vivir en paz.[n][w][e]

[msg quest85_0]
[s]メメントス最奥部クエストボス の概要[n]何が起きてる?[n][w][e]

[msg quest85_1]
[s]メメントス最奥部クエストボス を調査中[n]ターゲットは誰だ?[n][w][e]

[msg quest85_2]
[s]Futaba me ha hablado sobre una madre[n]que no se ocupa de su hija.[n]斡Nos vemos en el escondite para ir a Mementos![n][w][e]

[msg quest85_3]
[s]He o胤do hablar sobre una madre[n]que no se ocupa de su hija.[n]斡Despertemos su coraz吋n en Mementos![n][w][e]

[msg quest85_4]
[s]He conseguido despertar el coraz吋n[n]de la madre negligente.[n]Regresemos al mundo real a ver qu姻 pasa.[n][w][e]

[msg quest85_5]
[s]He conseguido despertar el coraz吋n[n]de la madre negligente.[n]La paz volver茨 a la familia.[n][w][e]

