[msg item_000]
[s]En blanco[n][e]

[msg Item_001]
[s]Sin usar[n][e]

[msg Item_002]
[s]Un arma que surgi吋[n]del despertar de un poder.[n][e]

[msg Item_003]
[s]Cuchillo curvo nepal胤 que tambi姻n[n]se utiliza como herramienta.[n][e]

[msg Item_004]
[s]Un bast吋n que llev吋 en su d胤a[n]un caballero ladr吋n legendario.[n][e]

[msg Item_005]
[s]Una daga con un filo[n]de color azul claro.[n][e]

[msg Item_006]
[s]Una daga que se usaba[n]durante los rituales wiccanos.[n][e]

[msg Item_007]
[s]Reservado[n][e]

[msg Item_008]
[s]Una daga que se usa[n]para desollar presas.[n][e]

[msg Item_009]
[s]RESERVE[n][e]

[msg Item_00A]
[s]Una daga capaz de conducir[n]la electricidad.[n][e]

[msg Item_00B]
[s]Una herramienta letal que usan[n]los profesionales sanitarios.[n][e]

[msg Item_00C]
[s]RESERVE[n][e]

[msg Item_00D]
[s]Un daga de imitaci吋n[n]usada por un rey.[n][e]

[msg Item_00E]
[s]Un cuchillo para desollar;[n]m茨s afilado y de mejor calidad.[n][e]

[msg Item_00F]
[s]RESERVE[n][e]

[msg Item_010]
[s]Una daga templada[n]mediante t姻cnicas avanzadas.[n][e]

[msg Item_011]
[s]Una daga usada antiguamente[n]por un apostador famoso.[n][e]

[msg Item_012]
[s]RESERVE[n][e]

[msg Item_013]
[s]Un cuchillo[n]que pesa mucho.[n][e]

[msg Item_014]
[s]R姻plica de una daga que se usaba[n]en la Europa medieval.[n][e]

[msg Item_015]
[s]RESERVE[n][e]

[msg Item_016]
[s]R姻plica de una daga capaz[n]de enfurecer a los enemigos.[n][e]

[msg Item_017]
[s]Una daga que viene bien[n]para bloquear y para defenderse.[n][e]

[msg Item_018]
[s]RESERVE[n][e]

[msg Item_019]
[s]Una daga medieval que se usa[n]para asestar golpes mortales.[n][e]

[msg Item_01A]
[s]Una daga ligera[n]que facilita la evasi吋n.[n][e]

[msg Item_01B]
[s]RESERVE[n][e]

[msg Item_01C]
[s]RESERVE[n][e]

[msg Item_01D]
[s]Una filo curvo que usaban[n]los antiguos griegos.[n][e]

[msg Item_01E]
[s]Una daga forjada a fuego[n]que arde intensamente.[n][e]

[msg Item_01F]
[s]RESERVE[n][e]

[msg Item_020]
[s]RESERVE[n][e]

[msg Item_021]
[s]RESERVE[n][e]

[msg Item_022]
[s]RESERVE[n][e]

[msg Item_023]
[s]Una daga usada para desterrar[n]a los 茨ngeles del para胤so.[n][e]

[msg Item_024]
[s]RESERVE[n][e]

[msg Item_025]
[s]Un arma que surgi吋[n]del despertar de un poder.[n][e]

[msg Item_026]
[s]Un bate de b姻isbol[n]con clavos.[n][e]

[msg Item_027]
[s]Un arma contundente usada[n]para juzgar a los enemigos.[n][e]

[msg Item_028]
[s]Un tubo de hierro reforzado.[n][e]

[msg Item_029]
[s]RESERVE[n][e]

[msg Item_02A]
[s]Una r姻plica de un martillo de metal[n]que se usa en combate.[n][e]

[msg Item_02B]
[s]Un arma contundente que[n]atiza con gran fuerza.[n][e]

[msg Item_02C]
[s]RESERVE[n][e]

[msg Item_02D]
[s]R姻plica que pesa a雨n m茨s.[n][e]

[msg Item_02E]
[s]Instrumento contundente[n]con abrojos acoplados.[n][e]

[msg Item_02F]
[s]RESERVE[n][e]

[msg Item_030]
[s]R姻plica de un martillo[n]con una historia extraordinaria.[n][e]

[msg Item_031]
[s]Un tubo contaminado[n]con energ胤a demon胤aca.[n][e]

[msg Item_032]
[s]RESERVE[n][e]

[msg Item_033]
[s]R姻plica de un martillo[n]con una historia extraordinaria.[n][e]

[msg Item_034]
[s]Un precioso[n]instrumento contundente.[n][e]

[msg Item_035]
[s]RESERVE[n][e]

[msg Item_036]
[s]Un instrumento contundente[n]que duerme a los enemigos.[n][e]

[msg Item_037]
[s]Un instrumento contundente[n]que provoca da隠os graves.[n][e]

[msg Item_038]
[s]RESERVE[n][e]

[msg Item_039]
[s]R姻plica de un arma[n]que se usaba en la Antigua China.[n][e]

[msg Item_03A]
[s]Un arma contundente[n]que vibra con luz et姻rea.[n][e]

[msg Item_03B]
[s]Un arma contundente[n]capaz de romper un meteorito.[n][e]

[msg Item_03C]
[s]Un instrumento contundente[n]y excepcionalmente pesado.[n][e]

[msg Item_03D]
[s]RESERVE[n][e]

[msg Item_03E]
[s]RESERVE[n][e]

[msg Item_03F]
[s]RESERVE[n][e]

[msg Item_040]
[s]Un arma contundente[n]que hace arder el alma.[n][e]

[msg Item_041]
[s]Un bast吋n que puede[n]alargarse de forma misteriosa.[n][e]

[msg Item_042]
[s]RESERVE[n][e]

[msg Item_043]
[s]Un arma contundente[n]que duerme a los enemigos.[n][e]

[msg Item_044]
[s]RESERVE[n][e]

[msg Item_045]
[s]RESERVE[n][e]

[msg Item_046]
[s]Un arma contundente[n]que intimida a los enemigos.[n][e]

[msg Item_047]
[s]RESERVE[n][e]

[msg Item_048]
[s]Un arma legendaria[n]empu隠ada por un dios.[n][e]

[msg Item_049]
[s]Una espada[n]hecha para robar.[n][e]

[msg Item_04A]
[s]Cuchar吋n usado por bakeneko[n]para cazar talentos ciudadanos.[n][e]

[msg Item_04B]
[s]Una espada de un lugar en el que[n]llueve antes de lo normal.[n][e]

[msg Item_04C]
[s]Se dice que esta espada corta m茨s[n]r茨pido que la velocidad del sonido.[n][e]

[msg Item_04D]
[s]Un filo curvo que[n]se usaba en Oriente Medio.[n][e]

[msg Item_04E]
[s]Una hoja curva que confunde[n]a los enemigos.[n][e]

[msg Item_04F]
[s]RESERVE[n][e]

[msg Item_050]
[s]Una espada que provoca[n]sue隠o a los enemigos.[n][e]

[msg Item_051]
[s]Un filo curvo que[n]se usaba en Oriente Medio.[n][e]

[msg Item_052]
[s]Una espada con un filo[n]de aspecto siniestro.[n][e]

[msg Item_053]
[s]Se dice que esta espada[n]hace milagros.[n][e]

[msg Item_054]
[s]Una espada[n]que podr胤a usar un h姻roe pirata.[n][e]

[msg Item_055]
[s]RESERVE[n][e]

[msg Item_056]
[s]Una espada con electricidad[n]en su interior.[n][e]

[msg Item_057]
[s]Una espada[n]con grabados en el filo.[n][e]

[msg Item_058]
[s]Una espada[n]que irradia calor.[n][e]

[msg Item_059]
[s]Una espada forjada[n]con materiales pesados.[n][e]

[msg Item_05A]
[s]RESERVE[n][e]

[msg Item_05B]
[s]Una espada que confunde[n]a los enemigos con cada corte.[n][e]

[msg Item_05C]
[s]RESERVE[n][e]

[msg Item_05D]
[s]Una espada que brilla[n]con una luz fr胤a y et姻rea.[n][e]

[msg Item_05E]
[s]Sin usar.[n][e]

[msg Item_05F]
[s]Una espada que obedece[n]a la voluntad de quien la porta.[n][e]

[msg Item_060]
[s]RESERVE[n][e]

[msg Item_061]
[s]RESERVE[n][e]

[msg Item_062]
[s]Una espada[n]con un filo luminoso.[n][e]

[msg Item_063]
[s]Sin usar.[n][e]

[msg Item_064]
[s]RESERVE[n][e]

[msg Item_065]
[s]RESERVE[n][e]

[msg Item_066]
[s]RESERVE[n][e]

[msg Item_067]
[s]RESERVE[n][e]

[msg Item_068]
[s]RESERVE[n][e]

[msg Item_069]
[s]Una espada[n]con fuerza divina.[n][e]

[msg Item_06A]
[s]RESERVE[n][e]

[msg Item_06B]
[s]RESERVE[n][e]

[msg Item_06C]
[s]Un arma que surgi吋[n]del despertar de un poder.[n][e]

[msg Item_06D]
[s]RESERVE[n][e]

[msg Item_06E]
[s]Un l茨tigo plegable[n]capaz de desgarrar la carne.[n][e]

[msg Item_06F]
[s]Un l茨tigo de color rojo.[n][e]

[msg Item_070]
[s]Un l茨tigo que puede arrancarles[n]la piel a los enemigos.[n][e]

[msg Item_071]
[s]Un l茨tigo que trae suerte.[n][e]

[msg Item_072]
[s]Un l茨tigo que puede[n]arder en llamas.[n][e]

[msg Item_073]
[s]Un l茨tigo que podr胤a usar[n]cualquier h姻roe.[n][e]

[msg Item_074]
[s]RESERVE[n][e]

[msg Item_075]
[s]Una espadal茨tigo plegable[n]con p雨as.[n][e]

[msg Item_076]
[s]Un l茨tigo plegable[n]y electrificado.[n][e]

[msg Item_077]
[s]RESERVE[n][e]

[msg Item_078]
[s]Un l茨tigo que borra[n]los recuerdos.[n][e]

[msg Item_079]
[s]Un l茨tigo con forma de cola.[n][e]

[msg Item_07A]
[s]RESERVE[n][e]

[msg Item_07B]
[s]Un l茨tigo plegable[n]con m茨s potencia.[n][e]

[msg Item_07C]
[s]Un l茨tigo hecho con cadenas.[n][e]

[msg Item_07D]
[s]RESERVE[n][e]

[msg Item_07E]
[s]Un l茨tigo con un[n]golpe aterrador.[n][e]

[msg Item_07F]
[s]Un l茨tigo plegable[n]y electrificado.[n][e]

[msg Item_080]
[s]RESERVE[n][e]

[msg Item_081]
[s]Un l茨tigo capaz[n]de inducir el sue隠o.[n][e]

[msg Item_082]
[s]RESERVE[n][e]

[msg Item_083]
[s]RESERVE[n][e]

[msg Item_084]
[s]RESERVE[n][e]

[msg Item_085]
[s]Un l茨tigo que exp胤a el pecado.[n][e]

[msg Item_086]
[s]Un l茨tigo ligero y robusto.[n][e]

[msg Item_087]
[s]RESERVE[n][e]

[msg Item_088]
[s]RESERVE[n][e]

[msg Item_089]
[s]RESERVE[n][e]

[msg Item_08A]
[s]RESERVE[n][e]

[msg Item_08B]
[s]Un l茨tigo que controla[n]la noche.[n][e]

[msg Item_08C]
[s]RESERVE[n][e]

[msg Item_08D]
[s]Un l茨tigo que congela[n]a los enemigos.[n][e]

[msg Item_08E]
[s]Un arma que surgi吋[n]del despertar de un poder.[n][e]

[msg Item_08F]
[s]Una espada sin filo.[n][e]

[msg Item_090]
[s]Una espada que no puede[n]cortar ni una patata.[n][e]

[msg Item_091]
[s]Una espada con un aspecto[n]precioso.[n][e]

[msg Item_092]
[s]Una espada con el poder[n]de controlar el fr胤o.[n][e]

[msg Item_093]
[s]Una espada[n]de aspecto amenazador.[n][e]

[msg Item_094]
[s]Una espada que se usaba de forma[n]reglamentaria en el ej姻rcito.[n][e]

[msg Item_095]
[s]Una espada que se usaba[n]en dramas hist吋ricos.[n][e]

[msg Item_096]
[s]Una espada que puede[n]hacer milagros.[n][e]

[msg Item_097]
[s]Una espada que brilla[n]a la luz de la luna.[n][e]

[msg Item_098]
[s]RESERVE[n][e]

[msg Item_099]
[s]RESERVE[n][e]

[msg Item_09A]
[s]Una espada que se usaba en iaido.[n][e]

[msg Item_09B]
[s]RESERVE[n][e]

[msg Item_09C]
[s]Esta espada marea[n]con solo mirarla.[n][e]

[msg Item_09D]
[s]Una espada con un filo[n]extremadamente largo.[n][e]

[msg Item_09E]
[s]RESERVE[n][e]

[msg Item_09F]
[s]Una espada capaz[n]de inducir el sue隠o.[n][e]

[msg Item_0A0]
[s]Una espada que puede[n]cortar los recuerdos.[n][e]

[msg Item_0A1]
[s]RESERVE[n][e]

[msg Item_0A2]
[s]Una espada m茨gica[n]que libera la sangre del cuerpo.[n][e]

[msg Item_0A3]
[s]RESERVE[n][e]

[msg Item_0A4]
[s]Una espada que se puede utilizar[n]para cualquier cosa.[n][e]

[msg Item_0A5]
[s]RESERVE[n][e]

[msg Item_0A6]
[s]La famosa espada[n]de la Novela de Genji.[n][e]

[msg Item_0A7]
[s]RESERVE[n][e]

[msg Item_0A8]
[s]RESERVE[n][e]

[msg Item_0A9]
[s]Una espada camuflada[n]como una pipa de fumar enorme.[n][e]

[msg Item_0AA]
[s]RESERVE[n][e]

[msg Item_0AB]
[s]Una espada que hace distinguir[n]entre actores y aficionados.[n][e]

[msg Item_0AC]
[s]RESERVE[n][e]

[msg Item_0AD]
[s]Un arma que surgi吋[n]del despertar de un poder.[n][e]

[msg Item_0AE]
[s]Guantes que asestan[n]impactos fuertes.[n][e]

[msg Item_0AF]
[s]RESERVE[n][e]

[msg Item_0B0]
[s]RESERVE[n][e]

[msg Item_0B1]
[s]Nudilleras de metal.[n][e]

[msg Item_0B2]
[s]Guantes que brillan[n]con plata oxidada.[n][e]

[msg Item_0B3]
[s]Guantes de hierro[n]que albergan poder en su interior.[n][e]

[msg Item_0B4]
[s]Guantes cuyos golpes[n]rompen la barrera del sonido.[n][e]

[msg Item_0B5]
[s]RESERVE[n][e]

[msg Item_0B6]
[s]Guantes con poder.[n][e]

[msg Item_0B7]
[s]Guantes que marean[n]a los enemigos.[n][e]

[msg Item_0B8]
[s]RESERVE[n][e]

[msg Item_0B9]
[s]Guantes[n]con m茨s potencia.[n][e]

[msg Item_0BA]
[s]Los guantes preferidos[n]de los luchadores profesionales.[n][e]

[msg Item_0BB]
[s]Guantes que hacen promesas.[n][e]

[msg Item_0BC]
[s]RESERVE[n][e]

[msg Item_0BD]
[s]RESERVE[n][e]

[msg Item_0BE]
[s]RESERVE[n][e]

[msg Item_0BF]
[s]RESERVE[n][e]

[msg Item_0C0]
[s]Guantes adorables y fuertes[n]que parecen huellas de oso. Ooh.[n][e]

[msg Item_0C1]
[s]Guantes con un incre胤ble[n]poder de destrucci吋n.[n][e]

[msg Item_0C2]
[s]Guantes dise隠ados[n]seg雨n el padre del cielo n吋mada.[n][e]

[msg Item_0C3]
[s]RESERVE[n][e]

[msg Item_0C4]
[s]RESERVE[n][e]

[msg Item_0C5]
[s]En honor al arma[n]de Indra.[n][e]

[msg Item_0C6]
[s]Un l茨tigo que te permite[n]controlar al enemigo.[n][e]

[msg Item_0C7]
[s]Un instrumento contundente[n]y vulgar pero eficaz.[n][e]

[msg Item_0C8]
[s]Sin usar.[n][e]

[msg Item_0C9]
[s]Un hacha peque隠a[n]para primerizos.[n][e]

[msg Item_0CA]
[s]Un hacha que deja[n]una marca profunda.[n][e]

[msg Item_0CB]
[s]RESERVE[n][e]

[msg Item_0CC]
[s]Un hacha que causa[n]un gran impacto.[n][e]

[msg Item_0CD]
[s]RESERVE[n][e]

[msg Item_0CE]
[s]Un hacha de aspecto fr胤o[n]con un tono azul.[n][e]

[msg Item_0CF]
[s]RESERVE[n][e]

[msg Item_0D0]
[s]Un hacha primitiva.[n][e]

[msg Item_0D1]
[s]Es posible que esta hacha provenga[n]de un cuento de hadas.[n][e]

[msg Item_0D2]
[s]Un hacha que emana poder.[n][e]

[msg Item_0D3]
[s]RESERVE[n][e]

[msg Item_0D4]
[s]RESERVE[n][e]

[msg Item_0D5]
[s]RESERVE[n][e]

[msg Item_0D6]
[s]Una imitaci吋n[n]que podr胤a provenir del espacio.[n][e]

[msg Item_0D7]
[s]Sin usar.[n][e]

[msg Item_0D8]
[s]RESERVE[n][e]

[msg Item_0D9]
[s]R姻plica de un hacha[n]que portaba un h姻roe legendario.[n][e]

[msg Item_0DA]
[s]RESERVE[n][e]

[msg Item_0DB]
[s]Un hacha que desprende[n]un aroma floral deslumbrante.[n][e]

[msg Item_0DC]
[s]Un guante que sacude[n]los huesos.[n][e]

[msg Item_0DD]
[s]Un guante con hojas triangulares[n]que destroza los 吋rganos vitales.[n][e]

[msg Item_0DE]
[s]Guantes[n]de metales pesados.[n][e]

[msg Item_0DF]
[s]Una aut姻ntica imitaci吋n[n]de la espada de energ胤a para ni隠os.[n][e]

[msg Item_0E0]
[s]Una espada adornada[n]con llamas premonitorias.[n][e]

[msg Item_0E1]
[s]Espada de energ胤a de imitaci吋n[n]con una cuchilla cegadora.[n][e]

[msg Item_0E2]
[s]Una espada[n]que lo quema todo.[n][e]

[msg Item_0E3]
[s]Una espada de filo curvo.[n][e]

[msg Item_0E4]
[s]Un l茨tigo que hace[n]que giren las cabezas.[n][e]

[msg Item_0E5]
[s]Una cadena con un peso[n]en el extremo.[n][e]

[msg Item_0E6]
[s]Un hacha que puede destruirlo[n]todo con un barrido.[n][e]

[msg Item_0E7]
[s]RESERVE[n][e]

[msg Item_0E8]
[s]RESERVE[n][e]

[msg Item_0E9]
[s]Un hacha de aspecto cruel.[n][e]

[msg Item_0EA]
[s]Un hacha capaz de causar[n]desesperaci吋n.[n][e]

[msg Item_0EB]
[s]Una espada que posee[n]el poder para transmutar.[n][e]

[msg Item_0EC]
[s]RESERVE[n][e]

[msg Item_0ED]
[s]RESERVE[n][e]

[msg Item_0EE]
[s]RESERVE[n][e]

[msg Item_0EF]
[s]RESERVE[n][e]

[msg Item_0F0]
[s]Una cadena pesada[n]dise隠ada para atar piernas.[n][e]

[msg Item_0F1]
[s]Guantes para inculcar[n]disciplina.[n][e]

[msg Item_0F2]
[s]RESERVE[n][e]

[msg Item_0F3]
[s]Una espada dif胤cil de golpear[n]pero f茨cil de derribar.[n][e]

[msg Item_0F4]
[s]RESERVE[n][e]

[msg Item_0F5]
[s]Una espada de plata que[n]brilla por su decoraci吋n.[n][e]

[msg Item_0F6]
[s]Una espada[n]con dise隠o en zigzag.[n][e]

[msg Item_0F7]
[s]RESERVE[n][e]

[msg Item_0F8]
[s]RESERVE[n][e]

[msg Item_0F9]
[s]Used as data, will not show.[n][e]

[msg Item_0FA]
[s]Used as data, will not show.[n][e]

[msg Item_0FB]
[s]Sable con una punta muy afilada.[n][e]

[msg Item_0FC]
[s]RESERVE[n][e]

[msg Item_0FD]
[s]RESERVE[n][e]

[msg Item_0FE]
[s]Un sable angelical.[n][e]

[msg Item_0FF]
[s]Un sable angelical y divino.[n][e]

[msg Item_100]
[s]Un bast吋n que llev吋 en su d胤a[n]un caballero ladr吋n legendario.[n][e]

[msg Item_101]
[s]La noble daga[n]de un 茨ngel ca胤do.[n][e]

[msg Item_102]
[s]Un arma legendaria[n]empu隠ada por un dios.[n][e]

[msg Item_103]
[s]Un bast吋n refinado de gran alcance.[n][e]

[msg Item_104]
[s]Un cuchar吋n usado por un bakeneko[n]para cazar talentos guerreros.[n][e]

[msg Item_105]
[s]Una espada noble[n]con un filo luminoso.[n][e]

[msg Item_106]
[s]Un l茨tigo elegante que hace[n]que giren las cabezas.[n][e]

[msg Item_107]
[s]Un fuerte l茨tigo que controla[n]la noche.[n][e]

[msg Item_108]
[s]Un l茨tigo que asusta[n]y congela a los enemigos.[n][e]

[msg Item_109]
[s]Una espada refinada[n]para actores experimentados.[n][e]

[msg Item_10A]
[s]La verdadera espada[n]de la Novela de Genji.[n][e]

[msg Item_10B]
[s]Guantes adorables y fuertes[n]que parecen huellas de oso. Ooh.[n][e]

[msg Item_10C]
[s]Guantes dise隠ados[n]seg雨n el padre del cielo n吋mada.[n][e]

[msg Item_10D]
[s]En honor al arma de Indra,[n]pero mejorada.[n][e]

[msg Item_10E]
[s]Un hacha fuerte capaz[n]de causar desesperaci吋n.[n][e]

[msg Item_10F]
[s]Un hacha noble que desprende[n]un aroma floral deslumbrante.[n][e]

[msg Item_110]
[s]Una daga con un dise隠o[n]electrizante.[n][e]

[msg Item_111]
[s]Un arma contundente[n]de gran nobleza.[n][e]

[msg Item_112]
[s]Una espada[n]con el nombre de un mago.[n][e]

[msg Item_113]
[s]Un l茨tigo que brilla[n]en la oscuridad de la noche.[n][e]

[msg Item_114]
[s]Una espada de aspecto llamativo.[n][e]

[msg Item_115]
[s]Guantes tan ligeros como un caballo[n]corriendo por el cielo.[n][e]

[msg Item_116]
[s]Un hacha de dise隠o[n]c吋smico.[n][e]

[msg Item_117]
[s]Una espada[n]de dise隠o aterrador.[n][e]

[msg Item_118]
[s]Un sable con un atractivo[n]brillo blanco.[n][e]

[msg Item_119]
[s]Una daga del juicio.[n][e]

[msg Item_11A]
[s]Un arma contundente a la que[n]algunos llaman el arma definitiva.[n][e]

[msg Item_11B]
[s]Una r姻plica de una espada[n]muy afilada.[n][e]

[msg Item_11C]
[s]Un l茨tigo que lleva el nombre[n]de una cadena m茨gica.[n][e]

[msg Item_11D]
[s]Una espada con un filo estupendo.[n][e]

[msg Item_11E]
[s]Guantes que solo pueden usar[n]quienes se alcen con la victoria.[n][e]

[msg Item_11F]
[s]Una imitaci吋n[n]usada por un cruzado.[n][e]

[msg Item_120]
[s]Una espada[n]con un filo afilado.[n][e]

[msg Item_121]
[s]Un sable con una hoja[n]muy fina.[n][e]

[msg Item_122]
[s]Una espada que no refleja[n]luz alguna.[n][e]

[msg Item_123]
[s]Una espada con el poder[n]de una diosa.[n][e]

[msg Item_124]
[s]Guantes que pueden ser 雨tiles[n]a la hora de apostar.[n][e]

[msg Item_125]
[s]Una espada l茨ser que permite[n]ganar cualquier batalla.[n][e]

[msg Item_126]
[s]Un sable que infunde valor.[n][e]

[msg Item_127]
[s]Una espada que recuerda[n]a los enemigos que corta.[n][e]

