[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3030 65535 0]Gracias por invitarme.[n]Tu opini吋n sobre las verduras[n]me ha ayudado mucho.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Ah! Si hay alguna verdura que[n]te guste particularmente, av胤same.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tengo mogoll吋n de semillas.[n]Si tienes[n]alguna preferencia, habla.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Perfecto.[e]
[s][f 0 8 2 1 2217]Ese era nuestro trato.[clr 27][e]
[s]Gracias, cuento contigo.[e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 4 5 7]Jii, jii... D姻jamelo a m胤.[n]A fin de cuentas, as胤 contribuyo yo[n]a los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Eh? 斡Vaya, es verdad![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100][f 5 13 4 15 7]Ja, ja... 斡Lo dices as胤 y resulta[n]emocionante! 斡Qu姻 extra隠o![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 4 5 7]Por supuesto. No te decepcionar姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A雨n no brillo con luz propia,[n]pero ayudar姻 a los Ladrones[n]Fantasma como pueda.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, me voy a casa.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][f 4 10 65535 0 0][vp 8 2 0 3062 65535 0]Hasta luego.[n][f 1 3 65535][w][e]

