[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3032 65535 0]Siento haberte pedido que vinieras as胤[n]de repente. Ponte c吋modo,[n]por favor.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Tu habitaci吋n es preciosa.[e]
[s]夷Quer胤as hablar?[e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 3178 65535 0]Ah, aqu胤 no hay nada especial.[n]No tienes por qu姻 mirar[n]as胤 por todos lados.[n][f 1 3 65535][w][e]

[msg MSG_002_5_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ten胤a que hablar contigo sobre esta[n]situaci吋n..., o m茨s bien, a causa[n]de ella.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]S胤, bueno...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ten胤a que hablar contigo sobre esta[n]situaci吋n..., o m茨s bien, a causa[n]de ella.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Te debo una disculpa, [f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3177 65535 0]Lo siento... He sido una in雨til.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]夷De qu姻 va esto?[e]
[s]夷A qu姻 te refieres?[e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Qu姻 verg鵜enza...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]El doctor Maruki cre吋 una nueva,[n]dulce y perfecta realidad para m胤,[n]y yo la acept姻 sin titubeos.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si he logrado encontrar mi camino,[n]ha sido gracias a ti.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]T雨 fuiste quien me dio un futuro...[n]夷y qu姻 hice con 姻l?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Soy pat姻tica.[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]No te preocupes.[e]
[s]No es culpa tuya.[e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3182 65535 0]Qu姻 amable eres, [f 4 2],[n]pero me temo que no es suficiente.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quiero estar a tu lado en esto,[n]y quiero hacerlo con orgullo.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3184 65535 0]Desde luego, ojal茨 mi padre[n]estuviera vivo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quer胤a reflotar la empresa con 姻l.[n]No, es m茨s, quer胤a salvarlo.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pero eso no es posible.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Por muy importante que fuera para[n]m胤, se ha ido y jam茨s volver茨.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Si pudiera reescribir el pasado[n]en beneficio propio, ser胤a un acto[n]tremendamente ego胤sta.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]夷Qu姻 te hace pensar eso?[e]
[s]夷Qu姻 pasa con tu felicidad?[e]

[msg MSG_015_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3021 65535 0]No s姻...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Y qu姻 hay de lo que me propuse[n]tras la muerte de mi padre[n]y de todo el apoyo que me has dado?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Si pudiera elegir vivir feliz,[n]no merecer胤a la pena renegar[n]de cuanto me ha tra胤do hasta aqu胤.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3194 65535 0]Que algo me haya hecho feliz[n]no quiere decir que sea apropiado.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Y la pr吋xima vez? Si fracaso [n]o algo sale mal, 夷simplemente[n]lo borro tambi姻n y ya est茨?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mi padre se ha ido, lo s姻. Duele[n]y es triste, pero el dolor es lo[n]que me dio fuerza y determinaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hemos pasado por muchas cosas[n]juntos. No quiero renunciar a ello[n]ni al v胤nculo que nos ha unido.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Haru]]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Necesito que sepas[n]que afrontar姻 lo que venga.[n]Lo de huir se acab吋.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Rechazo el 或regalo位[n]del doctor Maruki.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 53510 65535 0]Elegir姻 nuestra realidad,[n]la que he definido con mis penas,[n]mis errores y mis l茨grimas.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Haru]]
[s][vp 8 2 0 53511 65535 0]夷Este es... mi poder? Ya veo.[n]A雨n puedo luchar con m茨s fuerza.[n][f 1 3 65535][w][e]

[msg PFM_019_5_0]
[s][vp 1 0 0 0 0 0]斡[clr 1]Astart姻[clr 27], la Persona de Haru,[n]se ha transformado en [clr 2]Lucy[clr 27]![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Lamento haberte entretenido tanto.[n]Ya te lo he soltado todo.[n][f 1 3 65535][w][e]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 2 0 0 65535 0]Ahora me esforzar姻 a雨n m茨s[n]para compensar[n]por los problemas que he causado.[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]Ya peleas con fuerza.[e]
[s]Cuento contigo.[e]

[msg MSG_022_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3023 65535 0]Gracias.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Dices eso y me siento capaz[n]de hacer cualquier cosa.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3023 65535 0]S胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Dices eso y me siento capaz[n]de hacer cualquier cosa.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Cada vez ser姻 m茨s fuerte.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tengo que seguir adelante.[n]Por padre.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Haru]]
[s][vp 8 2 0 3060 65535 0]Gracias otra vez por venir.[n]Ten cuidado por el camino.[n][f 1 3 65535][w][e]

