[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 0 3115 65535 0]Vaya, [f 4 2].[n]斡Tienes mucha ma隠a![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El suelo ser胤a mucho m茨s f姻rtil[n]si estuvieras aqu胤 m茨s a menudo.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La verdad es que me sorprende[n]que cultivar nos sea 雨til[n]a los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Empez吋 siendo solo un pasatiempo,[n]as胤 que es incre胤ble que pase a ser[n]una habilidad m茨s pr茨ctica.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 1 300 65535][vp 8 2 0 3018 65535 0]Aparte, he comenzado a cultivar[n]plantas en casa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Granos de caf姻, por ejemplo.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]夷Te gusta el caf姻?[e]
[s]夷Vas a abrir una cafeter胤a?[e]
[s][f 0 8 2 1 2217]夷Vas a montar una granja?[clr 27][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 0 3111 65535 0][f 5 13 4 5 7]En realidad soy m茨s de t姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Siempre me aseguro de tener[n]al menos diez variedades a mano[n]para mi t姻 matutino y vespertino.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0][f 5 13 4 10 7]*risita* 夷Vendr胤as si yo estuviera?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷No te parece bonita la idea[n]de montar una cafeter胤a de dise隠o?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Haru]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 1 300 1][vp 8 2 0 3048 65535 0][f 5 13 4 15 7]*risita* 斡Eres la monda,[n][f 4 2]![n][f 1 3 65535][w][e]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]No hace falta una granja[n]para cultivar caf姻. Se puede hacer[n]en un jard胤n, como las verduras.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aunque el terreno que uso en la[n]villa de mi padre es tan grande[n]como para montar una granja.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, he descubierto el placer[n]en el sabor y aroma del caf姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Antes solo pensaba que era amargo,[n]pero ahora entiendo[n]la intensidad del sabor.[n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Para serte sincera, ni siquiera[n]era capaz de beberlo antes.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][bup 0 7 204 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En fin, disculpa.[n]Tan solo estaba recordando...[n][f 1 3 65535][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, 夷puedo contarte algo?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][vp 8 2 0 3195 65535 0]Como ya coment姻 antes,[n]no consigo fiarme de ninguno[n]de los empleados de Okumura Foods.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Desde que tengo uso de raz吋n,[n]la compa隠胤a la ha llevado mi padre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Caerle en gracia siempre ha sido[n]primordial. Algunos empleados hasta[n]ven胤an a congraciarse conmigo.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero, desde que falleci吋,[n]est茨 todo patas arriba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se nota que intentan usar[n]mi influencia de mayor accionista[n]para derrocar a otros empleados.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Dicen que vienen a m胤 por respeto,[n]pero s姻 que en realidad[n]solo quieren usarme.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se rumorean tantas cosas...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][vp 8 2 0 3192 65535 0]Los peores son sobre Takakura, el[n]nuevo presidente. Dicen que estaba[n]encantado cuando mi padre falleci吋.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quiz茨 sea cierto. Lleva en la[n]compa隠胤a a隠os, pero me ha empezado[n]a tratar bien hace poco.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Incluso se ofreci吋 a asesorarme[n]con la gesti吋n de los activos.[n]Me da miedo que vaya con segundas...[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]夷Qu姻 quieres decir?[e]
[s]夷No vas a aceptar la oferta?[e]
[s][f 0 8 2 1 2217]Algo huele a chamusquina.[clr 27][e]

[msg MSG_014_0_0 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No, no puedo confiar en 姻l.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 4 5 7]S胤, pero no puedo evitar[n]darle vueltas... [n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 2 0 3193 65535 0]Incluso me recomend吋 que vendiera[n]mis acciones el otro d胤a. Me dijo[n]que podr胤a ganar una fortuna.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero me di cuenta de que,[n]de ser as胤, podr胤a eliminar[n]el nombre de Okumura por completo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Takakura debe estar maquinando[n]c吋mo quedarse con la compa隠胤a.[n][f 1 3 65535][w][e]

[msg MSG_017_5_0 [Haru]]
[s][bup 0 7 203 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Al menos cabe esa posibilidad.[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s][f 0 8 2 1 2217]Es complicado.[clr 27][e]
[s]Puede que est姻s equivocada.[e]
[s]Quiz茨 deber胤as despedirlo.[e]

[msg MSG_019_0_0 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 4 10 7]En efecto, as胤 es...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tampoco han sido 雨tiles ninguno[n]de los consejos que he recibido.[n]Todos hablan por su propio inter姻s.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Haru]]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 4 5 7]Supongo, pero no s姻 decirte.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tampoco han sido 雨tiles ninguno[n]de los consejos que he recibido.[n]Todos hablan por su propio inter姻s.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 4 5 7]*risita* 夷Cazarlos antes de que[n]te cacen a ti? Ese concepto s胤[n]que es de Ladr吋n Fantasma.[n][f 1 3 65535][w][e]
[s][bup 0 7 200 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 59 5 100][f 4 24 0 4 0 5 5 100]Pero no estoy segura de si tendr姻[n]influencia para hacer algo as胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tampoco han sido 雨tiles ninguno[n]de los consejos que he recibido.[n]Todos hablan por su propio inter姻s.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 2 0 3020 65535 0]Gracias por lo de hoy.[n]Me siento algo mejor[n]despu姻s de haber hablado contigo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, y no te preocupes. Intentar姻[n]seguir motivada, aunque est姻[n]pasando por un mal momento.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento la confianza[n]que Haru tiene en m胤...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Haru]]
[s][bup 0 7 201 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me voy a quedar aqu胤 un poco m茨s[n]para echarle un ojo al drenaje.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Necesito asegurarme de que[n]las verduras sean 雨tiles[n]para los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Haru]]
[s][vp 8 2 0 3062 65535 0]Bueno, nos vemos luego.[n][f 1 3 65535][w][e]

