[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3133 65535 0]Vale... Hay ocho formas diferentes[n]de tostar granos de caf姻.[n]El tueste ligero es el m茨s 茨cido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aqu胤 dice que el tipo de tostado[n]que te interese depender茨 de[n]c吋mo te quieras beber el caf姻.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]Es impresionante.[clr 27][e]
[s]Eres muy estudiosa.[e]
[s][f 0 8 2 1 2217]夷Puedes hacerme uno?[clr 27][e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3020 65535 0][f 5 13 4 10 7]S胤. Creo que alg雨n d胤a me gustar胤a[n]aprender a hacer todos esos[n]tuestes a mano.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3020 65535 0][f 5 13 4 5 7]Gracias. Quiero asegurarme de que[n]los granos que estoy cultivando[n]desarrollen todo su potencial.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0][f 5 13 4 10 7]*risita* Mejor no. No creo que[n]llegue nunca a igualar la profunda[n]intensidad del caf姻 de Sojiro.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3188 65535 0]Okumura Foods no empez吋[n]como una cadena de hamburgueser胤as...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Al principio solo era una cafeter胤a[n]peque隠a que llevaba mi abuelo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La cafeter胤a cerr吋 antes de que yo[n]tuviera edad para apreciar[n]las particularidades del caf姻...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero ese es el verdadero[n]origen de nuestro negocio familiar.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s][f 0 8 2 1 2217]No ten胤a ni idea.[clr 27][e]
[s]Menuda sorpresa.[e]
[s]Podr胤a haberlo imaginado.[e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 4 5 7]Yo tampoco. Mi padre me lo cont吋[n]por primera vez hace un a隠o o dos.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤, claro, todo el mundo conoce[n]la empresa por sus hamburguesas.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷En serio? Pero si solo servimos[n]caf姻 soluble en el Big Bang.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3193 65535 0]Bueno, cuando muri吋 mi abuelo,[n]la empresa cerr吋 la cafeter胤a[n]por la p姻rdida de ingresos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A 姻l nunca le import吋 el dinero.[n]Su 雨nico objetivo[n]era hacer feliz a la gente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Form吋 una comunidad fuerte en la[n]cafeter胤a... Hasta daba comida gratis[n]a quien no pod胤a permit胤rsela.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cuando cerr吋, la gente hizo una[n]cola enorme para ponerle flores.[n]Les encantaba ese lugar...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3189 65535 0]Me pregunto cu茨nta gente har胤a[n]cola si el Big Bang Burger[n]cerrara de repente...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S姻 que tenemos que ir bien para[n]pagar a los empleados, pero creo[n]que hemos perdido algo importante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Takakura parece que solo se centra[n]en las ganancias... El futuro[n]de la empresa pinta muy negro.[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]Puede que tengas raz吋n.[e]
[s]S胤, la cosa puede ponerse fea.[e]
[s][f 0 8 2 1 2217]夷Negro como el caf姻?[clr 27][e]

[msg MSG_013_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷No hay nada que pueda hacer...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El nombre de la empresa[n]va a seguir manchado...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3194 65535 0][f 5 13 4 10 7]S胤... tengo que dar con alguna[n]forma de cambiar la situaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 3024 65535 0]夷Eh?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Ah, ya lo tengo![n][f 1 3 65535][w][e]

[msg MSG_015_5_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3088 65535 0][f 5 13 4 15 7]*risita* 斡Qu姻 divertido eres,[n][f 4 2]![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Intentabas animarme,[n]夷verdad? Gracias.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*suspiro* Creo que lo que necesito[n]es... volverme m茨s fuerte.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Puedo hacerme la dura delante[n]de mis empleados... pero[n]sabes que en el fondo soy d姻bil.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3187 65535 0]Aunque tengo un plan.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Antes de ver en qui姻n conf胤o,[n]tengo que saber qu姻 significa[n]que otros conf胤en en m胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por eso me har姻 m茨s fuerte...[n]斡lo suficiente para que t雨 y[n]los dem茨s confi姻is en m胤![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que Haru est茨 muy decidida.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3111 65535 0]Mmm... pero 夷c吋mo voy a ganarme[n]la confianza de mis trabajadores?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 7 300 65535][vp 8 0 0 0 65535 0]No se me da bien hablar en p雨blico...[n]y hasta dar mi opini吋n[n]me pone nerviosa...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]夷Haru?[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Haru]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 7 300 1][vp 8 2 0 3040 65535 0]斡夷S-Sugimura?! 夷Qu姻 haces aqu胤?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Prometido de Haru]]
[s][bup 0 211 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Volv胤a a casa de una reuni吋n[n]de negocios y te vi[n]desde el coche.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Prometido de Haru]]
[s][bup 0 211 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Mm? 夷Te conozco de algo?[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]斡...![n][f 1 3 65535][w][e]
[s][bup 0 211 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eres uno de esos mocosos...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 3178 65535 0]Es un amigo del instituto. Me est茨[n]ayudando a buscar unos libros.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Deber胤amos volver a lo que[n]est茨bamos haciendo. Disculpa.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Prometido de Haru]]
[s][bup 0 211 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espera, Haru. 夷Crees que puedes[n]salir con otros hombres y dejar[n]a tu prometido olvidado?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No eres mi prometido... Ya te dije[n]que no iba a casarme contigo.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Prometido de Haru]]
[s][bup 0 211 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, 夷s胤? 夷Y qu姻 pasa con[n]el contrato que ten胤a con tu padre?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3029 65535 0]M-mi padre... ya no est茨... Adem茨s,[n]el matrimonio es algo que[n]se hace por voluntad propia...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Un contrato nunca va[n]a tener el mismo valor...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Prometido de Haru]]
[s][bup 0 211 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Est茨s segura?[n]Piensa en las indemnizaciones.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si te echas atr茨s ahora,[n]perder茨s todo lo que tienes.[n]Okumura Foods, tu patrimonio...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aun as胤, yo...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Prometido de Haru]]
[s][bup 0 211 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 pasar茨 con tus trabajadores?[n]夷Vas a arriesgar sus trabajos[n]por tu ego胤smo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Adem茨s, este matrimonio es[n]lo que necesita Okumura Foods.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mi padre no tendr胤a problema[n]en gestionar tus acciones o limpiar[n]el mal nombre de la empresa.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 7 300 65535][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Prometido de Haru]]
[s][bup 0 211 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ahora que me acuerdo, 夷te dijo[n]Takakura lo del banquete?[n]Ha reservado una zona en el Wilton.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Haru]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 7 300 1][vp 8 2 0 3040 65535 0]斡夷Q-qu姻?![n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Prometido de Haru]]
[s][bup 0 211 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ha hecho una reserva provisional[n]de diez d胤as para esta primavera.[n]A ver, cuanto antes, mejor.[n][f 1 3 65535][w][e]

[msg MSG_036_1_0 [Haru]]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡E-espera un momento![n][f 1 3 65535][w][e]

[msg MSG_036_2_0 [Prometido de Haru]]
[s][bup 0 211 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tendremos que ver los invitados[n]tambi姻n. Habr茨 m茨s de trescientos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Takakura puede ocuparse[n]de Okumura Foods mientras tanto.[n]夷Por qu姻 no vas al gimnasio, Haru?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A ver, si tienes tiempo para[n]andar con este pavo, tambi姻n[n]lo tendr茨s para adelgazar.[n][f 1 3 65535][w][e]

[msg MSG_036_3_0 [Prometido de Haru]]
[s][bup 0 211 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me voy.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Siento lo que ha pasado...[n][f 1 3 65535][w][e]

[sel SEL_038_0_0 top]
[s]No tienes que disculparte.[e]
[s]Ese t胤o es horrible.[e]

[msg MSG_039_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3195 65535 0]No te equivocas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo tiene todo. Fama,[n]inteligencia, modales...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo 雨nico que le falta es[n]una mujer que pueda controlar...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Supongo que soy el blanco perfecto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y adem茨s, se va a llevar[n]Okumura Foods y toda mi herencia,[n]y no puedo hacer nada...[n][f 1 3 65535][w][e]

[sel SEL_040_0_0 top]
[s]No est茨s indefensa.[e]
[s][f 0 8 2 1 2217]S姻 fuerte, Haru.[clr 27][e]

[msg MSG_041_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo siento. Casi que te[n]he obligado a decir eso.[n][f 1 3 65535][w][e]
[s][f 4 24 0 4 0 59 5 100][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero... gracias.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 4 15 7]Tienes raz吋n... no puedo dejar[n]que la negatividad me destruya.[n][f 1 3 65535][w][e]
[s][f 4 24 0 4 0 36 5 100][f 4 24 0 4 0 9 5 100][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gracias.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3018 65535 0]Bueno, espero poder quedar[n]contigo m茨s veces.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por hoy... estoy bastante cansada.[n]夷Te importa si lo dejamos aqu胤?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Haru]]
[s][vp 8 2 0 3054 65535 0]Bueno, adi吋s.[n][f 1 3 65535][w][e]

