[msg MND_000_1_0]
[s][vp 8 0 0 0 65535 0]El cuadro de Yusuke se ha llevado[n]el primer premio de la competici吋n...[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]A雨n me queda mucho por aprender,[n]pero por fin he pintado algo de[n]lo que estoy plenamente satisfecho.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]S胤. Este es el verdadero coraz吋n[n]de la humanidad.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Se titula 或Deseo y esperanza位.[n]夷Qu姻 te parece?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]No te ha quedado nada mal.[e]
[s]夷Has a隠adido la esperanza?[e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]He incluido ciertos aspectos[n]que faltaban.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Esta luz... os representa a vosotros.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]El t胤tulo menciona la esperanza,[n]pero en mi mente se trata[n]de algo mucho m茨s concreto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]No puedo creer que[n]no me haya dado cuenta[n]hasta ahora...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kawanabe]]
[s][vp 8 0 0 11 5 0]Mmm...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Usted...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Kawanabe]]
[s][vp 8 0 0 13 5 0]Es un buen cuadro.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 5 7 301 1][vp 8 0 0 14 65535 0]夷Qu姻?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Kawanabe]]
[s][vp 8 0 0 15 5 0]No es una obra exc姻ntrica[n]por el hecho mismo de serlo,[n]como la 雨ltima vez.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 17 5 0]Qui姻n iba a pensar que un cuadro[n]puede cambiar tanto...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kawanabe]]
[s][vp 8 0 0 18 5 0]Entonces, 夷esta es la respuesta[n]que se te ha ocurrido?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]As胤 es.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Kawanabe]]
[s][vp 8 0 0 20 5 0]或Deseo y esperanza位... Ya veo.[n]Belleza y fealdad...[n]Los humanos poseemos las dos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 21 5 0]Parece que lo entiendes muy bien.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]夷Qu姻 se trae entre manos?[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]夷Provoc吋 a Yusuke a prop吋sito?[e]
[s]夷Qu姻 est茨 tramando?[e]

[msg MSG_016_0_0 [Kawanabe]]
[s][vp 8 0 0 23 5 0]Supongo que no puedo culparte[n]por pensar as胤.[n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Kawanabe]]
[s][vp 8 0 0 24 5 0]Mis disculpas. Aunque mi intenci吋n[n]solo era motivarte, puede[n]que fuera bastante duro.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]夷Qu姻 quiere decir?[n]夷No estaba apoyando[n]a otra persona?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Kawanabe]]
[s][vp 8 0 0 26 5 0]Ah, eso...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 27 5 0]El principiante prometedor[n]al que apoyaba...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Kawanabe]]
[s][vp 8 0 0 28 5 0]Es 姻l.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]夷De qu姻 habla?[e]
[s]夷Todo ha sido un parip姻?[e]

[msg MSG_021_0_0 [Kawanabe]]
[s][vp 8 0 0 29 5 0]Bueno, supongo que tienes raz吋n.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Kawanabe]]
[s][vp 8 0 0 31 5 0]Aun as胤, sigo pensando que[n]este teatrillo era necesario para[n]encender tu esp胤ritu competitivo.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Pero... 夷por qu姻 lo ha hecho?[n]夷Cu茨l era su objetivo?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Kawanabe]]
[s][vp 8 0 0 35 5 0]Solo quer胤a hacer algo por alguien[n]que tambi姻n se ha librado de las[n]cadenas de Madarame. Eso es todo.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]夷C吋mo?[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Kawanabe]]
[s][vp 8 0 0 38 5 0]Madarame me la ten胤a jurada porque,[n]seg雨n 姻l, le robaba a los clientes.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 39 5 0]Para empezar, nunca[n]consegu胤a alquilar espacios para[n]mis exposiciones... Lo pas姻 muy mal.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]As胤 que es por eso...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Kawanabe]]
[s][vp 8 0 0 42 5 0]S胤... El coraz吋n de un hombre se[n]colorea con el deseo, aunque a[n]veces sea tan negro como el carb吋n.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Kawanabe]]
[s][vp 8 0 0 43 5 0]Sin embargo, parece que[n]t雨 eres capaz de[n]enfrentarte a 姻l y superarlo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 44 5 0]Si 姻l hubiera tenido la misma[n]fuerza de voluntad que t雨...[n][f 1 3 65535][w][e]

[sel SEL_030_0_0 top]
[s]夷或畏l位?[e]
[s]夷Se refiere a Madarame?[e]

[msg MSG_031_0_0 [Kawanabe]]
[s][vp 8 0 0 45 5 0]Madarame y yo nos conoc胤amos muy[n]bien. Fuimos estudiantes y luego[n]profesores en la misma escuela.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 46 5 0]Ten胤a un esp胤ritu noble y siempre[n]dec胤a que deseaba llegar a lo m茨s[n]alto del mundo del arte.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][vp 1 0 0 48 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Kawanabe]]
[s][vp 8 0 0 49 5 0]Pero al final, la pol胤tica existe[n]incluso en el mundo del arte...[n]Y solo ganan los m茨s astutos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 50 5 0]As胤 fue como se ennegrecieron[n]nuestros corazones.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Kawanabe]]
[s][vp 8 0 0 51 5 0]Pero el coraz吋n humano es muy[n]peculiar. No sabe distinguir bien[n]entre el blanco y el negro.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Kawanabe]]
[s][vp 8 0 0 52 5 0]Me sorprendi吋 mucho que[n]te acogiera, porque a 姻l[n]no le gustaban los ni隠os.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Yusuke]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 5 7 301 1][vp 8 0 0 53 65535 0]夷C吋mo?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Kawanabe]]
[s][vp 8 0 0 54 5 0]Justo antes de que cort茨semos[n]toda relaci吋n,[n]recib胤 una llamada suya.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 55 5 0]Estaba hist姻rico porque todas las[n]cl胤nicas cercanas hab胤an cerrado[n]y ten胤a a un ni隠o con fiebre.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]Maestro...[n][f 1 3 65535][w][e]

[sel SEL_039_0_0 top]
[s][f 0 8 2 1 2217]En el fondo, era un buen hombre.[clr 27][e]
[s][f 0 8 2 1 2217]Ese era otro lado suyo.[clr 27][e]

[msg MSG_040_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 57 65535 0][f 5 13 5 10 5]S胤.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Kawanabe]]
[s][vp 8 0 0 60 5 0]No quiero que este mundo cree m茨s[n]perdedores como yo ni ganadores[n]desencaminados como 姻l.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 61 5 0]Por eso cre姻 esta fundaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Kawanabe]]
[s][vp 8 0 0 62 5 0]夷Qu姻 me dices?[n]夷Te gustar胤a que fu姻ramos[n]tus mecenas?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 64 5 0]Sin ning雨n tipo de compromiso[n]sobre tu producci吋n, por supuesto.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 65 65535 0]Es una oferta muy generosa...[n]Muchas gracias por su amabilidad.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]No obstante, me temo[n]que debo rechazarla.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Kawanabe]]
[s][vp 8 0 0 67 5 0]Mmm... 夷Por qu姻 dices eso?[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 68 65535 0]Yo no soy Madarame.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 69 65535 0]No permitir姻 que el deseo[n]me mancille. Despu姻s de todo,[n]yo tengo esperanza.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 70 65535 0]Si me pierdo, ellos me ayudar茨n[n]a encontrar el camino. Y si[n]me equivoco, ellos me reprender茨n.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 71 65535 0]Mientras tenga mis rayos[n]de esperanza para guiarme,[n]estar姻 bien.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Kawanabe]]
[s][vp 8 0 0 74 5 0]Mmm, Madarame ten胤a muy buen ojo.[n]斡Ja, ja, ja, ja, ja![n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 75 65535 0]Qu姻 hombre tan extra隠o...[n][f 1 3 65535][w][e]

[sel SEL_049_0_0 top]
[s]S胤...[e]
[s]T雨 eres m茨s extra隠o a雨n, Yusuke.[e]
[s]夷Est茨s seguro de esto?[e]

[msg MSG_050_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]Invertir su propio dinero para[n]ayudar a los dem茨s no es algo que[n]est姻 dispuesto a hacer cualquiera.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 77 65535 0]Quiz茨 sea una estupidez[n]por mi parte rechazar su oferta.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 78 65535 0]夷Por rechazar su oferta?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 79 65535 0]Es una estupidez por mi parte.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 80 65535 0]Es una estupidez por mi parte[n]rechazar su oferta.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 81 65535 0]Aun as胤, creo que es lo mejor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 82 65535 0]Tengo sentimientos encontrados,[n]pero supongo que as胤 es[n]el coraz吋n humano, 夷no?[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 83 65535 0]Interesante... Eso es exactamente[n]lo que deber胤a pintar.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 85 65535 0]Tratar conmigo no debe[n]haber sido nada f茨cil.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 86 65535 0]Pero por alguna raz吋n, sab胤a que[n]no me abandonar胤as hasta que[n]todo se hubiera resuelto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 87 65535 0]Gracias, amigo m胤o.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento un fuerte v胤nculo[n]con Yusuke.[n][f 1 3 65535][w][e]

[msg MSG_054_5_0 [Yusuke]]
[s][vp 8 0 0 255 7 0]La Persona que hay en mi interior[n]ha despertado un nuevo poder.[n][f 1 3 65535][w][e]

[msg PFM_054_7_0]
[s][vp 8 0 0 0 65535 0]斡[clr 1]Goemon[clr 27], la Persona de Yusuke,[n]se ha transformado[n]en [clr 2]Kamu Susanoo[clr 27]![n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 90 65535 0]Ahora que por fin he superado este[n]bache, tengo que recuperar todo[n]el tiempo que he estado sin pintar.[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 91 65535 0]Reitero mi promesa hacia ti.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 93 65535 0]Si alguna vez tropiezas,[n]puedes contar con mi ayuda.[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 95 65535 0]Bueno, 夷qu姻? 夷Nos vamos?[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 96 65535 0]Si quiero aprender m茨s sobre el[n]coraz吋n, tendremos que aplicarnos[n]a fondo como Ladrones.[n][f 1 3 65535][w][e]

