[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4031 65535 0]Muchas gracias por tu ayuda hoy.[n]Sin ti no habr胤a descubierto esa[n]maravillosa fuente de inspiraci吋n.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No esperaba que mis dotes[n]art胤sticas fuesen a serle 雨tiles[n]a los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 59 5 100]He de cumplir con mi parte del[n]trato para dar lo mejor de m胤.[n]Solo tienes que ped胤rmelo.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Gracias.[e]
[s]Intentar姻 no hacerlo.[e]
[s][f 0 8 2 1 2217]Te har姻 muchas preguntas.[clr 27][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 5 5 5]Soy yo quien deber胤a darte las[n]gracias. Sin tu ayuda, no podr胤a[n]haber terminado la obra de hoy.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 5 5 5]夷Tienes miedo de molestar?[n]No te preocupes, anda.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53733 65535 0][f 5 13 5 10 5]夷S胤? Entonces cuenta conmigo.[n]Mi pincel est茨 a tu servicio.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por ahora deber胤amos volver.[n]斡Tengo que dar el toque final[n]lo antes posible![n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Ja... Mi pincel va a volver[n]a las andadas por primera vez[n]en mucho tiempo.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 4 10 65535 0 0][vp 8 2 0 4063 65535 0]Hasta m茨s ver.[n][f 1 3 65535][w][e]

