[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 2 0 4100 65535 0]Ah, [f 4 2]... Hace[n]tanto fr胤o como de costumbre, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero es parte del encanto invernal,[n]夷no? El aire puro y fresco...[n][f 1 3 65535][w][e]
[s][bup 0 5 3 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 38 5 100]Posee una extra隠a... claridad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como si de repente todo se viera[n]m茨s n胤tido, tanto en nuestro[n]interior como m茨s all茨.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]夷Me puedo ir ya?[e]
[s]夷Est茨s bien?[e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 3 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, espera, no era eso de lo que[n]quer胤a hablar contigo.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 59 5 100]Sin presiones, pero 夷te importa[n]si nos vemos luego?[n]Cuando tengas un rato.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 3 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me pregunto si... Yo...[n][f 1 3 65535][w][e]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 59 5 100]Sin presiones, pero 夷te importa[n]si nos vemos luego?[n]Cuando tengas un rato.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 0 5 0][f 4 10 65535 0 0][vp 8 2 0 4031 65535 0]Gracias. Hasta luego.[n][f 1 3 65535][w][e]

