[msg MSG_000_0_0 [Kawanabe]]
[s][vp 8 0 0 0 5 0]Ah, vosotros dos...[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4182 65535 0]Se隠or Kawanabe.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Kawanabe]]
[s][vp 8 0 0 0 5 0]夷Ya vuelves? S胤 que tienes[n]tiempo libre, Yusuke.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Ahora iba a preparar[n]la competici吋n. Y hablando[n]del tema, 夷piensas presentarte?[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Desde luego.[n][f 1 3 65535][w][e]

[msg MSG_001_7_0 [Kawanabe]]
[s][vp 8 0 0 0 5 0]Puede que tu orgullo[n]se resienta con el resultado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Despu姻s de todo, no est茨[n]garantizado que vayas a ganar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Supongo que est茨 en tus manos[n]decidir si participas o no.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 5 0]Cuantos m茨s seamos,[n]mejor, 夷no? 斡Ja, ja, ja![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4064 65535 0]Ganar... Oh, s胤. Esperaba poder[n]demostrarle mi talento haci姻ndome[n]con el primer premio.[n][f 1 3 65535][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero ya no importa. Voy a[n]participar con mi cuadro solo para[n]que los dem茨s puedan verlo.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4181 65535 0]Bueno, hablamos despu姻s,[n][f 4 2]. Hasta pronto.[n][f 1 3 65535][w][e]

