[msg MSG_000_1_0 [Clienta ostentosa]]
[s][vp 8 0 0 0 65535 0]夷Nunca se siente solo, Sojiro?[n]Lleva tanto tiempo soltero...[n]夷Acaso no piensa casarse?[n][f 1 3 65535][w][e]

[msg MSG_000_2_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 2 0 5024 65535 0]De una relaci吋n solo quiero un[n]est胤mulo picante seguido por[n]un confort placentero y relajante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y puedo conseguir ambas cosas[n]con mi curry y mi caf姻.[n]Con eso me basta.[n][f 1 3 65535][w][e]

[msg MSG_000_3_0 [Clienta ostentosa]]
[s][vp 8 0 0 0 65535 0]Siempre esquiva ese tipo[n]de preguntas. Es muy listo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Por cierto, 夷qu姻 piensas t雨[n]de que Sojiro lleve[n]un estilo de vida solitario?[n][f 1 3 65535][w][e]

[sel SEL_000_4_0 top]
[s]Lo admiro.[e]
[s]No me extra隠a.[e]
[s][f 0 8 2 1 2217]Sobre gustos no hay nada escrito.[clr 27][e]

[msg MSG_000_5_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Puedes admirarme si quieres,[n]pero no te recomiendo que[n]sigas mis pasos.[n][f 1 3 65535][w][e]

[msg MSG_000_6_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Fue a hablar el delincuente.[n][f 1 3 65535][w][e]

[msg MSG_000_7_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 6 5 1003]Esa es una forma muy sutil[n]de mostrar tu desacuerdo...[n][f 1 3 65535][w][e]

[msg MSG_000_8_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, lo 雨nico que me importa[n]en esta vida es que mis clientes[n]queden satisfechos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nada me hace m茨s feliz que ver[n]a la gente relajarse aqu胤.[n]Vuelva cuando quiera, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 2 0 5018 65535 0]Hoy estaba bastante agresiva, 夷no?[n]Menos mal que no[n]ha seguido insistiendo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 103 3 300 65535][vp 8 0 0 0 65535 0]Supongo que en este sector hay que[n]mantener la distancia justa...[n]Ni mucho ni poco.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bienve...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sojiro]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 103 3 300 1][vp 8 2 0 5047 65535 0]No sabe cu茨ndo rendirse, 斡夷eh...?![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]Bueno... 斡es que acabo de descubrir[n]algo muy interesante![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Futaba ha estado aislada[n]del instituto y de la sociedad todo[n]este tiempo, 夷no? Qu姻 mal padre.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Ah, s胤? 夷Y usted qu姻 ha hecho[n]para cuidar de ella?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]Sabe muy bien lo que he hecho...[n]y ya va siendo hora de que pague.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 103 3 300 1][vp 8 2 0 5046 65535 0]No diga tonter胤as.[n]Futaba lo pas吋 fatal[n]cuando vivi吋 con usted...[n][f 1 3 65535][w][e]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Adem茨s, ya le di la mayor胤a[n]de la herencia a cambio[n]de la custodia! 斡夷Qu姻 m茨s quiere?![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]Podr胤amos descubrirlo en un juicio.[n]Me pregunto qui姻n ganar茨, un simple[n]tutor legal o un familiar...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Usted...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]斡Y ni hablemos del cr胤o que tiene[n]aqu胤! Lo s姻 todo sobre 姻l,[n]incluyendo sus antecedentes.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]Eso nos deja con un 或padre位 que no[n]la deja ir al instituto y[n]con un delincuente bajo su techo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No parece ser el mejor entorno[n]para Futaba, 夷no?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Te equivocas.[e]
[s]Lo siento.[e]
[s][f 0 8 2 1 2217]C茨llate la boca.[clr 27][e]

[msg MSG_012_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]斡夷Qu姻 has dicho?![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]No te preocupes... yo me encargo.[n]Vete arriba.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]Je, no me cabe duda. Me alegra[n]ver que alguien sabe cu茨l[n]es su lugar.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡No tienes que pedirle[n]perd吋n, idiota![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Venga, yo me encargo.[n]Vete arriba.[n][f 1 3 65535][w][e]

[msg SYS_016_0_0]
[s][vp 8 0 0 0 65535 0]No tengo el Coraje[n]suficiente para decir eso.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]斡夷T-tienes alg雨n problema, ni隠ato?![n]斡Te denunciar姻 por intimidaci吋n![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 6 10 1003]Oye, no te metas en esto.[n]Vete arriba, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Sojirooo, me muero de hambre![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Futaba]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 5 301 1][vp 8 2 0 9178 65535 0]Oh...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 103 5 300 65535]斡Futaba! 斡Cu茨nto tiempo![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yo... Yo... Yo...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Futaba![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]夷Ve a lo que me refiero? Est茨[n]hecha un desastre. Esta no es[n]una situaci吋n muy saludable.[n][f 1 3 65535][w][e]

[msg MSG_024_3_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Se ha puesto as胤 porque[n]le ha visto aqu胤![n][f 1 3 65535][w][e]

[msg MSG_024_5_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]No me haga repetirlo... No puede[n]ganarme en un juicio, as胤 que[n]lo mejor ser茨 que me d姻 el dinero.[n][f 1 3 65535][w][e]

[msg MSG_024_7_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Grrr...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]Bueno, 斡espero que tome[n]la decisi吋n correcta![n]斡Hasta la pr吋xima![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Futaba... Deber胤as irte a casa.[n]Yo te llevo.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sojiro...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 0 5028 65535 0]Futaba est茨 bien. Estaba agotada[n]despu姻s de tanto drama... Se durmi吋[n]en cuanto llegamos a casa.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ese hombre... es el t胤o de Futaba.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tras la muerte de Wakaba, Futaba[n]pas吋 por la casa de todos[n]sus familiares... 畏l fue el 雨ltimo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La trataba como basura. No le daba[n]de comer y la obligaba a dormir[n]en el suelo como un animal.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No dejaba ni que se ba隠ara... Cuando[n]me enter姻, supe que ten胤a[n]que intervenir.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No pod胤a aguantar la situaci吋n[n]en la que estaba Futaba, as胤 que[n]decid胤 acogerla.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Incluso entonces, se quejaba[n]de todos los pu隠eteros gastos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Le di algo de dinero, pensando[n]que ser胤a el fin del problema...[n]pero ahora quiere m茨s.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ni siquiera s姻 c吋mo ha conseguido[n]encontrarme... Puede que pagarle[n]fuera un error.[n][f 1 3 65535][w][e]

[sel SEL_034_0_0 top]
[s][f 0 8 2 1 2217]Salvar a Futaba no fue un error.[clr 27][e]
[s]Corta tus lazos con 姻l.[e]

[msg MSG_035_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 6 5 1003]Je... Gracias. Nunca imagin姻[n]que t雨 ser胤as quien[n]me acabar胤a consolando.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Para m胤 eso es f茨cil, pero para[n]Futaba no tanto. No puedes[n]elegir a tu familia.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En cualquier caso, es mi culpa[n]que Futaba nunca saliera[n]de su habitaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No sab胤a c吋mo ayudarla...[n]Yo solo preparaba curry, lo dejaba[n]en su puerta y me iba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A雨n estar胤a esperando a que saliera[n]de no ser por ti.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As胤 que si me preguntaras[n]si merezco ser el tutor de Futaba...[n]mi respuesta ser胤a que no.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Dicen que la sangre tira, 夷no?[n]夷Qu姻 ser茨 lo mejor para ella...?[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 2 0 5032 65535 0]Ja, ja... M胤rame, abri姻ndole[n]mi coraz吋n a un cr胤o como t雨.[n][f 1 3 65535][w][e]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No s姻, es raro. Por alg雨n motivo,[n]me nace contarte estas cosas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es como si pudieras ver mi coraz吋n...[n]Je, supongo que s胤 que tienes[n]algo especial.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo[n]con Sojiro se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya es bastante tarde.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 5152 65535 0]Deber胤a irme a casa.[n]Sigo preocupado por Futaba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No te acuestes muy tarde, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, y... gracias.[n][f 1 3 65535][w][e]

