[msg MSG_000_0_0 [Futaba]]
[s][vp 8 0 0 0 65535 0][f 5 14]斡Namast姻![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]斡BUENAS NOTICIAS![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]He buscado a mi t胤o...[n]斡y hay un resultado en Mementos![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14][f 5 15]夷Te enfadar胤as si te[n]pidiera ayuda?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Claro que no.[e]
[s]Puede que un poco.[e]

[msg MSG_001_3_0 [Futaba]]
[s][vp 8 0 0 0 65535 0][f 5 14]Vaya...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]No puedo hacer mucho yo sola.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Tal vez pueda aumentar su deuda[n]hasta el mill吋n de yenes o as胤...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14][f 5 15]Pero eso no solucionar胤a[n]el problema.[n][f 1 3 65535][w][e]

[msg MND_001_5_0]
[s][vp 8 0 0 0 65535 0]Parece que no me queda otra[n]que aceptar...[n][f 1 3 65535][w][e]

[sel SEL_001_7_0 top]
[s]Solo esta vez.[e]
[s]Supongo que no puedo negarme.[e]

[msg MSG_002_0_0 [Futaba]]
[s][vp 8 0 0 0 65535 0][f 5 14]斡夷De verdad?! 斡Much胤simas gracias![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Mi t胤o se llama Youji Isshiki.[n]Vayamos a Mementos[n]a despertar su coraz吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Pero antes, quiero pedirte algo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]No quiero tener que hablarle[n]a todo quisqui de la temporada[n]que viv胤 con 姻l.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Puede que alg雨n d胤a, pero...[n]hoy no es ese d胤a, desde luego.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]As胤 que estaba pensando...[n]que podr胤amos ir los dos solos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14][f 5 15]斡Necesito tu ayuda,[n][f 4 2]! 斡Porfaaaaaa![n][f 1 3 65535][w][e]

[msg MND_003_0_0]
[s][vp 8 0 0 0 65535 0]Debo encargarme del t胤o de Futaba[n]y ayudar a Sojiro.[n][f 1 3 65535][w][e]

