[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Eh, 夷c吋mo va el instituto?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]No estar茨s metido[n]en ning雨n l胤o, 夷no?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]No.[e]
[s]Quiz茨.[e]
[s]...[e]

[msg MSG_002_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Estupendo.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Esc雨chame...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]夷Por qu姻 est茨s tan callado?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Tengo que informar a tu agente[n]de la condicional dos veces al mes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Ya es todo un incordio de por s胤,[n]as胤 que no hagas que tenga que[n]escribir m茨s de lo necesario.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 103 2 300 1][vp 8 0 0 8 65535 0]夷Entendido? Esta sociedad se rige[n]por leyes y figuras de autoridad.[n][f 1 3 65535][w][e]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Si quieres terminar muerto,[n]es tu problema, pero no arrastres[n]a nadie m茨s contigo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Ya hay demasiados idiotas[n]pululando por ah胤.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]夷Qu姻 pasa?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]S胤, ya me voy.[n]Perdona por todo eso.[n][f 1 3 65535][w][e]

[msg MSG_008_5_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Ya lo s姻. Lo de siempre, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Vale. Nos vemos luego.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Como puedes ver, estoy[n]muy ocupado tanto en lo profesional[n]como en lo personal.[n][f 1 3 65535][w][e]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 3 100][f 4 24 0 4 0 9 3 100][vp 8 0 0 16 65535 0]Si me echaras una mano,[n]te lo agradecer胤a mucho...[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]Me encantar胤a.[e]
[s]Estoy bastante ocupado...[e]
[s]Es mucha molestia.[e]

[msg MSG_011_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]As胤 me gusta.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Lo dice el estudiante de instituto[n]sin preocupaciones.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Claro, y vigilarte es pan comido.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]En cualquier caso,[n]no te pido que trabajes gratis.[n]Si decides ayudarme...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Te ense隠ar姻 a preparar[n]una taza de caf姻 perfecta.[n]No es un mal trato, 夷verdad?[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]Supongo.[e]
[s]Suena interesante.[e]

[msg MSG_016_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Muy bien. Parece que[n]hemos llegado a un acuerdo.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Parece que la distancia[n]entre Sojiro y yo se est茨[n]reduciendo un poco...[n][f 1 3 65535][w][e]

[msg MSG_016_4_0 [Sae]]
[s][vp 8 0 0 800 65535 0]Puede que seas un Ladr吋n Fantasma,[n]pero tambi姻n eres menor de edad.[n]Alguien ten胤a que mantenerte.[n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Sae]]
[s][vp 8 0 0 801 65535 0]Adem茨s, lo hicieron sabiendo[n]que formabas parte de ese grupo...[n][f 1 3 65535][w][e]

[msg MSG_016_6_0 [Sae]]
[s][vp 8 0 0 802 65535 0]夷El propietario de esa cafeter胤a[n]no es tu c吋mplice?[n][f 1 3 65535][w][e]

[msg MSG_016_7_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Has aceptado un nuevo[n]contrato. Excelente.[n][f 1 3 65535][w][e]

[msg MSG_016_8_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Usa este nuevo v胤nculo para[n]fortalecer tu c胤rculo de confianza.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Estupendo.[n][f 1 3 65535][w][e]

[msg MSG_017_5_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Cuento con tu ayuda.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Hasta luego.[n][f 1 3 65535][w][e]

