[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 0 5102 65535 0]Bueno, puesto que vas a trabajar[n]en mi cafeter胤a, tendremos que[n]establecer unas normas b茨sicas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya sabes a lo que me refiero,[n]夷verdad?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]A hacer caf姻.[clr 27][e]
[s]A ligar con chicas.[e]
[s]Ni idea.[e]

[msg MSG_002_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 6 5 1003]Exacto. Me alegra que[n]lo hayas entendido tan r茨pido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esta cafeter胤a no es de las m茨s[n]concurridas, pero soy muy[n]quisquilloso para preparar el caf姻.[n][f 1 3 65535][w][e]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si veo que no sirves una taza en[n]condiciones, no dudar姻 en ponerte[n]de patitas en la calle.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A雨n eres muy joven para[n]aprender eso, chaval. Voy a[n]ense隠arte a preparar un buen caf姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esta cafeter胤a no es de las m茨s[n]concurridas, pero soy muy[n]quisquilloso para preparar el caf姻.[n][f 1 3 65535][w][e]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si veo que no sirves una taza en[n]condiciones, no dudar姻 en ponerte[n]de patitas en la calle.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*suspiro* Eso es preocupante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 37 3 100][f 4 24 0 4 0 0 5 100][vp 8 0 0 0 65535 0]夷Qu姻 podr胤a ser sino[n]hacer caf姻? Soy muy[n]quisquilloso para prepararlo.[n][f 1 3 65535][w][e]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si veo que no sirves una taza en[n]condiciones, no dudar姻 en ponerte[n]de patitas en la calle.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Clienta ostentosa]]
[s][vp 8 0 0 0 65535 0]Una cosa es cierta.[n]Sojiro sabe c吋mo preparar[n]un caf姻 en condiciones.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Y casa tan bien con su curry[n]especial, que no puedo evitar[n]pedir siempre lo mismo.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esa es la marca de esta cafeter胤a,[n]que cada cliente disfrute de una[n]experiencia personalizada.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Clienta ostentosa]]
[s][vp 8 0 0 0 65535 0]夷Cu茨l es la clave de este sabor[n]tan delicioso, Sojiro?[n]Me encantar胤a prepararlo en casa.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo siento, es un secreto[n]profesional. Siempre puede[n]intentar adivinarlo por el sabor...[n][f 1 3 65535][w][e]

[msg MSG_008_1_0 [Clienta ostentosa]]
[s][vp 8 0 0 0 65535 0]Qu姻 taca隠o. Me oculta sus secretos[n]aunque sabe que me ha robado[n]el coraz吋n con su comida...[n][f 1 3 65535][w][e]

[msg MSG_008_3_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷No le apetece un postre?[n]Solo son trescientos yenes.[n][f 1 3 65535][w][e]

[msg MSG_008_5_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cuando regentas una cafeter胤a,[n]recibes todo tipo de clientes,[n]y conocerlos es esencial.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esa es la clave de un negocio[n]de restauraci吋n.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bienve...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sojiro]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 103 7 300 1][vp 8 2 0 5041 65535 0]T雨...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]斡Muy buenas![n]斡Cu茨nto tiempo, Sakura![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Me enter姻 de que hab胤a abierto una[n]cafeter胤a, 斡y aqu胤 estoy! Aunque ya[n]me lo podr胤a haber dicho usted.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]Este sitio est茨 muy bien ubicado.[n]Cerca de la estaci吋n y todo.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 le pongo?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]夷Directo al grano? Qu姻 impersonal.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Oh, este olor...[n]me trae muy buenos recuerdos.[n]夷Sigue haciendo ese curry?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Supongo que a雨n[n]no la ha olvidado...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 le pongo, se隠or?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Hombre mayor alegre]]
[s][vp 8 0 0 0 65535 0]Ja, ja, 斡qu姻 insistente![n]Hoy solo he venido a saludar...[n]pero volver姻 pronto. 斡Adi吋s![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 2 0 5043 65535 0]Uf... No s姻 c吋mo[n]ha encontrado este sitio.[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]夷Qui姻n era ese?[e]
[s][f 0 8 2 1 2217]Ese t胤o parec胤a sospechoso.[clr 27][e]
[s]夷Qui姻n es esa 或ella位 que mencion吋?[e]

[msg MSG_019_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Olv胤dalo. No es de tu incumbencia.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 6 5 1003]Mmm, parece que tienes[n]buen ojo para ciertas cosas.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qui姻n sabe?[n]Hay demasiadas personas[n]que se ajustan a ese perfil.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, si tienes tiempo de hacer[n]preguntas, tienes tiempo[n]de aprender sobre tipos de caf姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si no aprendes lo b茨sico,[n]no me sirves de nada.[n][f 1 3 65535][w][e]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][f 4 23 0 4 3 10 0 10][vp 8 0 0 0 65535 0]Adem茨s, a las mujeres les encantan[n]los hombres que entienden de caf姻.[n]Eso que te llevas.[n][f 1 3 65535][w][e]

[sel SEL_022_2_0 top]
[s][f 0 8 2 1 2217]Quiero que las mujeres me adoren.[clr 27][e]
[s]Esas cosas no me interesan.[e]

[msg MSG_022_4_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 2 0 5048 65535 0][f 5 13 6 5 1003]Anda, ojal茨 fueras siempre[n]as胤 de obediente.[n][f 1 3 65535][w][e]

[msg MSG_022_6_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Venga, que tienes que seguirme[n]el rollo... Es uno de los principios[n]b茨sicos del servicio al cliente.[n][f 1 3 65535][w][e]

[msg MSG_022_5_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Da igual, yo te ense隠ar姻[n]en condiciones. As胤 podr姻 relajarme[n]mientras t雨 trabajas.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo[n]con Sojiro se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oh, 夷ya es hora?[n][f 1 3 65535][w][e]

[msg MSG_023_5_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 0 5102 65535 0]Vamos a cerrar.[n]Y nada de holgazanear, 夷entendido?[n][f 1 3 65535][w][e]

