[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 0 5001 65535 0]Lo siento, hoy ya hemos cerrado...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Mujer estirada]]
[s][vp 8 0 0 0 8 0]夷Es usted Sojiro Sakura?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Hombre respetable]]
[s][vp 8 0 0 0 6 0]Disculpe que vengamos tan tarde.[n]Somos investigadores[n]del juzgado de familia.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Investigador estirado]]
[s][vp 8 0 0 0 8 0]Nos han informado de que alguien[n]en libertad condicional que vive[n]aqu胤 atac吋 a uno de sus clientes.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 8 0]Es m茨s, tambi姻n se dice[n]que abusa usted de su hija,[n]Futaba.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]N-no... No lo hemos conseguido...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Mi t胤o ha puesto la denuncia[n]antes de que despert茨ramos[n]su coraz吋n...![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Investigador respetable]]
[s][vp 8 0 0 0 6 0]Sin embargo, el informe es an吋nimo[n]y eso nos hace dudar[n]de su validez. 夷Podr胤amos hablar?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sin problema. No tengo[n]nada que esconder.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si姻ntense, por favor.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Investigador estirado]]
[s][vp 8 0 0 0 8 0]夷Me est茨 diciendo[n]que el informe era falso?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 2 0 5035 65535 0]Es cierto que Futaba viv胤a[n]aislada, pero logr吋 superar[n]ese problema ella sola.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 3 301 65535][vp 8 0 0 0 65535 0]Y... nunca abusar胤a de ella.[n]Es como mi hija.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Investigador estirado]]
[s][vp 8 0 0 0 8 0]夷Y qu姻 me dice de la agresi吋n?[n]Su historial delictivo ayuda[n]a reforzar esta historia violenta...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 3 301 1][vp 8 2 0 9187 65535 0]斡Se equivoca...![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El chico ni siquiera[n]toc吋 a ese t胤o. Solo se puso[n]en medio para proteger a Futaba.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Investigador respetable]]
[s][vp 8 0 0 0 6 0]A decir verdad, [f 4 1],[n]hemos investigado su reputaci吋n[n]actual en el instituto...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 6 0]Y parece que no ha[n]habido ning雨n problema.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Investigador respetable]]
[s][vp 8 0 0 0 6 0]Tambi姻n es nuestro deber[n]que menores como usted est姻n bien.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 6 0]夷C吋mo es vivir con el se隠or Sakura?[n]Por favor, sea sincero.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s][f 0 8 2 1 2217]Es genial.[clr 27][e]
[s]Es un poco gru隠吋n.[e]

[msg MSG_015_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 6 10 1003]Bueno... ah胤 lo tienen.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 6 5 1003]Madre m胤a, no tienes remedio.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Investigador estirado]]
[s][vp 8 0 0 0 8 0]夷Y usted qu姻 piensa, Futaba?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yo... yo estoy bien.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Durante un tiempo no pod胤a salir...[n]pero todos me han ayudado.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 103 7 300 65535][vp 8 0 0 0 65535 0]Ya no tengo miedo.[n][f 1 3 65535][w][e]

[msg MSG_020_5_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]P-por eso... 斡estoy muy[n]feliz de vivir con mi padre![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Sojiro]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 103 7 300 1][vp 8 2 0 5123 65535 0]Futaba...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Investigador respetable]]
[s][vp 8 0 0 0 6 0]Entiendo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 6 0]Es obvio que el informe que[n]recibimos es falso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 6 0]Tampoco creo que tengamos[n]que planificar visitas para[n]vigilar a [f 4 1].[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Investigador estirado]]
[s][vp 8 0 0 0 8 0]夷Est茨s seguro?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Investigador respetable]]
[s][vp 8 0 0 0 6 0]Si hubieran querido enga隠arnos,[n]no habr胤an sido tan sinceros.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 6 0]Adem茨s, verlos solo ha servido[n]para reafirmar mis sospechas...[n]Estos ni隠os son las v胤ctimas aqu胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 6 0]Te quedar茨 m茨s clara[n]la verdad de este asunto cuando[n]tengas m茨s experiencia.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Investigador respetable]]
[s][vp 8 0 0 0 6 0]Bueno, gracias por su cooperaci吋n.[n]No hace falta que nos acompa隠en[n]a la puerta.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Futaba]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 8 1 300 1][vp 8 2 0 9191 65535 0]斡Sojiro, lo hemos conseguido![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Sojiro?[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]夷Est茨s llorando?[e]
[s][f 0 8 2 1 2217]Tienes una hija fant茨stica.[clr 27][e]
[s]Enhorabuena.[e]

[msg MSG_029_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 2 0 5024 65535 0]No digas tonter胤as...[n]E-es que estoy sudando, ya est茨.[n][f 1 3 65535][w][e]

[msg MSG_029_5_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤, claaaaaaaro.[n]斡Sudando por los ojos![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 2 0 5024 65535 0][f 5 13 6 15 1003]No es solo ella, idiota.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hay otra persona muy[n]importante viviendo aqu胤.[n][f 1 3 65535][w][e]

[msg MSG_030_5_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡S胤, s胤! 斡Se refiere a ti,[n][f 4 2]![n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 2 0 5024 65535 0][f 5 13 6 10 1003]*suspiro*[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yo no suelo ser as胤...[n][f 1 3 65535][w][e]

[msg MSG_031_5_0 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Oooh! 斡夷Est茨s llorando?![n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Sojiro]]
[s][bup 0 103 5 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*llanto* Todo porque dos[n]mocosos ten胤an que liarse[n]a decir cursiladas...[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡No eran cursiladas! 斡Era verdad![n][f 1 3 65535][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][f 4 24 0 5 0 42 3 100][f 4 24 0 5 0 0 0 0][vp 8 0 0 0 65535 0]斡Da igual, tengo hambreeee![n]斡Hazme curry![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Demasiado estaba durando[n]el momento sentimental.[n][f 1 3 65535][w][e]

[msg MSG_034_5_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vale, sentaos.[n]Este es vuestro hogar.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Mua, ja, ja! 斡Vamos, [f 4 2]![n]斡Hora de comer![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo[n]con Sojiro se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, y... Futaba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo que dijiste antes...[n]cuando dijiste que era tu padre...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Crees que podr胤as[n]decirlo otra vez...?[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo siento, no te he escuchado.[n]斡Me estaba rugiendo el est吋mago![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 has dicho?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 2 0 5028 65535 0]Nada, da igual...[n][f 1 3 65535][w][e]

