[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6156 65535 0]Le cont姻 a Shiho[n]lo que pas吋 con Mika[n]en la sesi吋n de fotos...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 42 4 100][f 4 24 0 4 0 0 0 0][vp 8 0 0 0 65535 0]夷Y sabes qu姻 hizo? 斡Re胤rse![n]Y hablar sin parar de que Mika[n]parec胤a una chica de armas tomar.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero bueno... la verdad[n]es que me vino bien.[n]Ya ni siquiera estoy enfadada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Supongo que solo hace falta[n]alguien que se r胤a de ti[n]para hacerte sentir mejor.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 0 8 2 1 2217]Eso parece.[clr 27][e]
[s]Qu姻 soluci吋n tan simple.[e]
[s]Si sois amigos, claro.[e]

[msg MSG_003_0_0 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 1 300 1][vp 8 2 0 6035 65535 0][f 5 13 7 10 4]Siempre dicen que re胤rse es[n]la mejor medicina, 夷no?[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pues yo lo he podido comprobar[n]de primera mano...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero 斡eso no tiene nada de malo![n]斡Cuanto m茨s simple, mejor![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 7 5 4]Ah胤 seguramente tengas raz吋n.[n]Si fuera una persona cualquiera[n]me cabrear胤a a雨n m茨s.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero bueno, aunque yo intente[n]volverme m茨s fuerte... la que es[n]fuerte de verdad aqu胤 es Shiho. [n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6058 65535 0]El otro d胤a fui a una[n]de sus sesiones de rehabilitaci吋n...[n]Me dijo que quer胤a tenerme all胤...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As胤 que acept姻 sin pens茨rmelo[n]mucho, pero lo cierto es que...[n]lo pas姻 bastante mal.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]夷Y eso?[e]
[s]夷Estaba haciendo mucho esfuerzo?[e]
[s]夷Le dol胤a mucho?[e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Fue mucho m茨s duro de lo que[n]pensaba... Horrible, te lo juro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estaba sudando a chorros, con los[n]dientes apretados... Estaba[n]sufriendo, se le ve胤a en la cara...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Al parecer... no puede ni mover los[n]pies. Dice que es como si tuviera[n]las piernas cubiertas de arena...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Las ten胤a hinchadas[n]y llenas de hematomas,[n]pero las arrastraba como pod胤a...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yo estaba deseando que parara...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤...[n][f 1 3 65535][w][e]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estaba sudando a chorros, con los[n]dientes apretados... Estaba[n]sufriendo, se le ve胤a en la cara...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Al parecer... no puede ni mover los[n]pies. Dice que es como si tuviera[n]las piernas cubiertas de arena...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Las ten胤a hinchadas[n]y llenas de hematomas,[n]pero las arrastraba como pod胤a...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yo estaba deseando que parara...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤, fue mucho m茨s duro de lo que[n]pensaba... Horrible, te lo juro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estaba sudando a chorros, con los[n]dientes apretados... Estaba[n]sufriendo, se le ve胤a en la cara...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Al parecer... no puede ni mover los[n]pies. Dice que es como si tuviera[n]las piernas cubiertas de arena...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Las ten胤a hinchadas[n]y llenas de hematomas,[n]pero las arrastraba como pod胤a...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yo estaba deseando que parara...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 6183 65535 0]Cuando acab吋,[n]estaba llorando desconsolada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Fue dur胤simo...[n]Dec胤a que no pod胤a m茨s...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 1 5 100][vp 8 0 0 0 65535 0]Y por eso me pidi吋 que fuera...[n]Para motivarse.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 1 10 30][vp 8 0 0 0 65535 0]En todo el rato no par吋 de quejarse[n]de cosas de las que jam茨s[n]se quejar胤a normalmente...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero, aun as胤...[n]termin吋 la sesi吋n.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ann]]
[s][bup 0 4 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yo... no s姻 por qu姻 estoy llorando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No fui yo la que tuvo[n]que pasar por eso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Es porque soy d姻bil?[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]No eres d姻bil.[e]
[s]Es porque eres buena persona.[e]

[msg MSG_016_0_0 [Ann]]
[s][bup 0 4 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Y por qu姻... no paro de llorar?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ann]]
[s][bup 0 4 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Te equivocas...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A pesar de todo ese dolor,[n]me pareci吋 que Shiho era incre胤ble...[n]incluso preciosa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A pesar de quejarse...[n]se esforz吋 al m茨ximo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ser fuerte no es simplemente que[n]nada te afecte... Es la capacidad[n]de luchar contra las adversidades.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6197 65535 0]As胤 que he estado pensando y...[n]夷qu姻 puedo hacer para ayudarla?[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]Consolarla.[e]
[s]Escucharla.[e]
[s][f 0 8 2 1 2217]Mostrarle lo fuerte que eres t雨.[clr 27][e]

[msg MSG_021_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6188 65535 0][f 5 13 7 10 4]Tienes raz吋n... Tengo que estar[n]a su lado y hablar con ella.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6188 65535 0][f 5 13 7 5 4]Tienes raz吋n...[n]斡Tengo que llamarla a menudo![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 7 15 4]夷Lo fuerte que soy...?[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6034 65535 0]S胤, eso har姻.[n]斡Voy a dar lo mejor de m胤...![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Sabes, [f 4 2]?[n]Cuando estoy contigo,[n]veo las cosas con claridad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Qu姻 deber胤a hacer, lo que[n]realmente significa ser fuerte...[n][f 1 3 65535][w][e]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][f 4 24 0 4 0 9 3 100][vp 8 2 0 6061 65535 0]Quer胤a... darte las gracias.[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Siento que Ann est茨[n]todav胤a m茨s motivada.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6025 65535 0]Uf, me moquea la nariz...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷P-por qu姻 me miras as胤?[n]斡Las chicas guapas tambi姻n[n]tenemos mocos, que lo sepas![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ann]]
[s][vp 8 2 0 6053 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

