[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 605 0 0][f 4 10 65535 0 0][vp 8 2 0 7170 65535 0]*tos* *jadeo*[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uf...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vuelvo a estar... en forma...,[n]pero no me queda... resistencia...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 6 301 65535][vp 8 0 0 0 65535 0]*tos*[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Estudiante que va al gimnasio]]
[s][vp 8 0 0 0 65535 0]夷Sakamoto?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 6 301 1][vp 8 2 0 54220 65535 0]斡Ey, Ikeda! 夷C吋mo va la marcha?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]Vaya forma de preguntar[n]que tienes, majete.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷As胤 es como saludas a un colega?[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][bup 0 2 601 0 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]Solo intento acu隠ar alg雨n palabro[n]as胤 guay. 斡Igual lo pongo de moda![n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]No puedes hacer eso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Y no te pases con las formalidades,[n]que somos j吋venes.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]T雨 no me suenas.[n]夷Estabas en el equipo de atletismo?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 601 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Es un amigo![n][f 1 3 65535][w][e]
[s][bup 0 2 603 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][vp 8 0 0 0 65535 0]Cuando se decidi吋 a venir,[n]el equipo ya..., bueno, ya sabes.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]Hablando de todo un poco,[n]夷qu姻 tal la pierna?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pues ah胤 va.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Y t雨? 夷Sigues corriendo?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]Pues estoy en el equipo de la uni.[n]Pensar胤as que lo habr胤a dejado[n]despu姻s de lo que pas吋, pero...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 603 0 0][f 4 10 65535 0 0][vp 8 2 0 7191 65535 0]A todo esto, lo siento.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]No, soy yo[n]el que tendr胤a que disculparse.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]Era el capit茨n, pero me resign姻[n]a los caprichos de Kamoshida.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][bup 0 2 611 0 0][f 4 10 65535 0 0][vp 8 2 0 7187 65535 0]Porque necesitabas[n]una carta de recomendaci吋n, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Solo pensabas en tu futuro,[n]pero yo siempre la jodo.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]Kamoshida nunca quiso escrib胤rmela[n]y te us吋 a ti como excusa.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ahora estoy a gusto. El equipo[n]no es nada del otro mundo,[n]pero es importante para m胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]En realidad tendr胤a que darte[n]las gracias, Sakamoto.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Ryuji]]
[s][bup 0 2 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vale...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 7 301 65535]Siempre he lamentado no hacer[n]m茨s para protegeros...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero tengo buenas noticias.[n]斡El equipo de atletismo[n]del Shujin va a volver![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 7 301 1][vp 8 2 0 7039 65535 0]斡夷En serio?![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]Bueno, Kamoshida ha confesado todas[n]las cosas horribles que hizo, 夷no?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Supongo que el instituto[n]llam吋 al viejo equipo[n]y le propuso volver.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 603 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nadie me hab胤a dicho nada.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]Ah, qu姻 raro... Hasta yo[n]me enter姻 y eso que[n]ni siquiera estudio all胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]El caso es que dicen que van a[n]nombrar nuevo asesor a Yamauchi.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 604 0 0][f 4 10 65535 0 0][vp 8 2 0 7174 65535 0]夷Qu姻 Yamauchi?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 39 5 100][vp 8 0 0 0 65535 0]No me digas que es el Yamauchi[n]en el que estoy pensando...[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]S胤, el que era[n]el perrito faldero de Kamoshida.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Al parecer se ofreci吋.[n]Est茨 ansioso por lograr que[n]el equipo renazca de sus cenizas.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Ryuji]]
[s][bup 0 2 605 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷En serio?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ikeda]]
[s][vp 8 0 0 0 65535 0]A ver, ahora que se restablece[n]el equipo ya no tiene sentido[n]que sigan enfadados, 夷no?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Por qu姻 no vas a hablar con ellos?[n]Seguro que les vendr胤a bien[n]alguien con tu pasi吋n.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 603 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 600 0 0][f 4 10 65535 0 0][vp 8 2 0 7038 65535 0]Vuelve el equipo de atletismo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me alegro por ellos.[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s][f 0 8 2 1 2217]No sabes qu姻 hacer, 夷verdad?[clr 27][e]
[s][f 0 8 2 1 2217]夷Quieres volver?[clr 27][e]
[s]No quieres saber nada, 夷no?[e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 603 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 5 2]En realidad no.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][bup 0 2 603 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 5 2]No lo s姻.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][bup 0 2 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero, la verdad, me alegro de que[n]vuelva el equipo. Mola que Nakaoka[n]y el resto entrenen de nuevo.[n][f 1 3 65535][w][e]
[s][bup 0 2 611 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 41 5 100][vp 8 0 0 0 65535 0]Pero me sigue preocupando[n]el asesor, Yamauchi, porque[n]es un miniKamoshida.[n][f 1 3 65535][w][e]

[sel SEL_038_0_0 top]
[s]夷Es bajito?[e]
[s][f 0 8 2 1 2217]夷Es un capullo?[clr 27][e]

[msg MSG_039_0_0 [Ryuji]]
[s][bup 0 2 611 0 0][f 4 10 65535 0 0][vp 8 2 0 7036 65535 0][f 5 13 8 5 2]斡No quer胤a decir eso! Es como[n]Kamoshida, pero m茨s capullo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Siempre nos gritaba en clase,[n]pero luego era superpelota[n]cuando ven胤an nuestros padres.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No puedo creer que ese idiota vaya[n]a ser asesor del equipo.[n]斡Si no es ni profe![n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Ryuji]]
[s][bup 0 2 611 0 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0][f 5 13 8 10 2]Pues eso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Siempre nos gritaba en clase,[n]pero luego era superpelota[n]cuando ven胤an nuestros padres.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No puedo creer que ese idiota vaya[n]a ser asesor del equipo.[n]斡Si no es ni profe![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 611 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estar茨 tramando algo.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Ryuji]]
[s][bup 0 2 600 0 0][f 4 10 65535 0 0][vp 8 2 0 7085 65535 0]Voy a investigar.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][bup 0 2 600 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es posible que necesite tu ayuda.[n][f 1 3 65535][w][e]
[s][bup 0 2 601 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 0 0 0 65535 0]Estar茨s libre para echarme[n]una mano si lo necesito, 夷no?[n]斡Cuento contigo![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo[n]con Ryuji se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Ryuji]]
[s][bup 0 2 601 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Muy bien, 斡ya no tenemos tiempo[n]para andar por aqu胤![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡V茨monos a casa![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uy, 斡que tengo que ducharme antes![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][vp 8 2 0 7053 65535 0]斡Nos vemos![n][f 1 3 65535][w][e]

