[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 10 300 65535][vp 8 2 0 7045 65535 0]He quedado aqu胤 con Nakaoka[n]y Takeishi. Voy a contarles lo que[n]trama el capullo de Yamauchi.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷Qu姻 pasa si empiezan a pelearse?[e]
[s]Dudo mucho que te crean.[e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 10 300 1][vp 8 2 0 7024 65535 0]Je, je, je...[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quiz茨 no te diste cuenta, pero[n]斡grab姻 toda la conversaci吋n de[n]Yamauchi en el sitio de monjayaki![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Soy un genio, lo s姻.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno... puede que necesite[n]un poco de ayuda con esto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Te importa quedarte aqu胤?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]夷Qu姻 quieres, Sakamoto?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 12 300 65535]夷Takeishi?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]斡夷Nakaoka?! 斡夷Q-qu姻 narices?![n]斡夷Os hab姻is unido contra m胤?![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 12 300 1][vp 8 2 0 7036 65535 0]T胤o, rel茨jate.[n]Solo quiero hablar contigo.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Escucha. Esto es lo que[n]realmente est茨 pasando[n]en el equipo de atletismo.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Voz de Yamauchi]]
[s][vp 8 0 0 0 65535 0]Ser茨 el renacer de un equipo[n]sumido en la desesperaci吋n...[n]A la gente le encantar茨.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Voz de Yamauchi]]
[s][vp 8 0 0 0 65535 0]Lo mejor es que los padres[n]de Takeishi est茨n forrados y[n]su madre es la presidenta del AMPA.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Voz de Yamauchi]]
[s][vp 8 0 0 0 65535 0]Pero hasta entonces,[n]les ense隠ar茨 a los dem茨s[n]el valor de la obediencia.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Tiene que ser una broma...[n]Yamauchi dijo que[n]me nombrar胤a capit茨n...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]夷Esto es real?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 7194 65535 0]Es la voz de Yamauchi, 夷no?[n]Y adem茨s, todo ha sucedido[n]tal y como 姻l dijo.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Takeishi]]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Yamauchi tiene raz吋n.[n]Yo no tengo el mismo talento[n]que ten姻is vosotros.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Por m茨s que me esforzaba corriendo,[n]vosotros siempre ibais por delante...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷C吋mo va a triunfar[n]alguien como yo?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡夷C吋mo voy a estar[n]orgulloso de m胤 mismo?![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Orgulloso?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Mi padre siempre habla de[n]lo orgulloso que est茨 de su hijo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Le ha dicho a todo el mundo que[n]conseguir姻 una beca de atletismo[n]como 姻l hizo en su d胤a...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Que seguir姻 sus pasos como graduado[n]de Taisei...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Por eso escuch姻 a Yamauchi.[n]Me dijo que si era capit茨n, me[n]escribir胤a una buena carta de rec...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 7156 65535 0]夷Me est茨s diciendo que cre胤ste[n]lo que te cont吋 sobre Nakaoka[n]por culpa de esa mierda?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 12 300 65535]斡C-c茨llate! 斡夷Qu姻 va a saber[n]un maleante como t雨?![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]T雨 no entiendes c吋mo me siento...[n]斡Nadie lo entiende![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 12 300 1][vp 8 2 0 7187 65535 0]斡Joder que si lo entiendo![n][f 1 3 65535][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 0 0 0 65535 0]斡夷Cu茨nto tiempo estuvimos corriendo[n]juntos, eh?! Hemos pasado por[n]miles de marrones juntos![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Sakamoto...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qui姻n tiene las riendas[n]de tu vida? 夷Tus padres?[n]夷Los profesores? 夷La sociedad?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quiz茨 deber胤as dejar de intentar[n]vivir por ellos y hacerlo por ti.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Crees que hay que[n]traicionar a la gente[n]para poder estar orgulloso?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]B-bueno, yo...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si eso es lo que piensas,[n]斡est茨s muy equivocado![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 7192 65535 0]Nakaoka, t雨 tambi姻n sab胤as que[n]pasaba algo con Yamauchi, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O sea, a ese cabr吋n nunca[n]le ha interesado el atletismo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero no dijiste nada.[n]Sab胤as que quer胤a pasar por encima[n]de ti, y dejaste que lo hiciera.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]S胤...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ten胤a miedo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Sin Yamauchi, no tendr胤amos equipo...[n]ni ning雨n sitio al que pertenecer.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 7169 65535 0]夷Tanto echabas de menos correr?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No tener un sitio al que pertenecer[n]no es tan malo, 夷sabes?[n]As胤 te sientes m茨s libre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si acaso, a m胤 me da m茨s miedo[n]ser una mala persona.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo que quiero decir es que yo[n]sol胤a ser como vosotros... ten胤a[n]miedo y me enga隠aba a m胤 mismo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero eso era antes[n]de conocer a este t胤o.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No quiero insultaros ni nada por[n]el estilo, pero s姻 que no deb姻is[n]estar contentos con esta situaci吋n...[n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 7 300 65535][f 4 24 0 4 0 41 5 100][vp 8 0 0 0 65535 0]As胤 que si quer姻is pegarme,[n]adelante. Estoy listo.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]En ese caso...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]Si insistes...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 7 300 1][vp 8 2 0 7041 65535 0]斡Eh! 斡夷De verdad lo vais a hacer?![n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]Has dicho que no te importaba, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡E-esperad un momento![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ay... No hac胤a falta[n]pegar tan fuerte...[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]Ja, ja, ja. Yo ya me siento[n]mejor, la verdad.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]Yo tambi姻n. Creo que ya estoy[n]preparado para dejarlo todo atr茨s.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Nakaoka... lo siento.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Nakaoka]]
[s][vp 8 0 0 0 65535 0]Yo tambi姻n lo siento.[n]Bueno, 夷quieres que resucitemos[n]el equipo de atletismo?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Takeishi]]
[s][vp 8 0 0 0 65535 0]斡Por supuesto![n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 1 300 65535][vp 8 2 0 7028 65535 0]Has visto eso, 夷no? 斡Qu姻 violencia![n][f 1 3 65535][w][e]

[sel SEL_040_0_0 top]
[s][f 0 8 2 1 2217]Todo ha salido a pedir de boca.[clr 27][e]
[s]Te lo merec胤as.[e]

[msg MSG_041_0_0 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 15 2]No, t胤o. Con lo mucho que cuido[n]yo de esta cara, 斡y mira c吋mo[n]me la han dejado![n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 10 2]S胤, supongo que en realidad[n]ha sido culpa m胤a.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 1 300 1][vp 8 2 0 7079 65535 0]En cualquier caso, seguro que[n]ya se sienten mejor.[n]Creo que les ir茨 bien juntos.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 0 0 0 65535 0]Gracias.[n][f 1 3 65535][w][e]

[sel SEL_044_0_0 top]
[s][f 0 8 2 1 2217]Yo me he limitado a mirar.[clr 27][e]
[s]夷C吋mo me lo vas a pagar?[e]

[msg MSG_045_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 10 2]斡Mira qui姻n habla![n]Te has quedado ah胤 pasmado[n]mientras me daban para el pelo...[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 5 2]夷Lo dices en serio? Bueno, si te[n]pones as胤, puedo invitarte a ramen...[n]斡Pero los extras los pagas t雨![n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En serio... has sido de gran ayuda.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me has obligado[n]a estar tranquilo todo el rato.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 2 0 7024 65535 0]Ha sido como si estuviera[n]esprintando... y t雨 corrieras[n]a mi lado.[n][f 1 3 65535][w][e]

[sel SEL_048_0_0 top]
[s]Pero si estaba aqu胤 parado...[e]
[s][f 0 8 2 1 2217]Bueno, muy tranquilo no has estado.[clr 27][e]

[msg MSG_049_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 5 2]斡No me has entendido![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Era una met茨fora de esas![n]斡Pues claro que no estabas[n]corriendo en realidad, t胤o![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 10 2]斡Qu姻 cruel! Olvida la paliza[n]que me han dado, 夷vale?[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo[n]con Ryuji se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7050 65535 0]Bueno, v茨monos a casa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Creo que me est茨 sangrando la boca,[n]as胤 que ya comeremos otro d胤a.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Ryuji]]
[s][vp 8 2 0 7053 65535 0]斡Nos vemos![n][f 1 3 65535][w][e]

