[msg MSG_000_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 14 301 1][vp 8 2 0 7131 65535 0]Aqu胤 estamos,[n]斡en el gimnasio Protein Lovers![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vinimos con Ann[n]una vez, 夷te acuerdas?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aquel d胤a fue gratis,[n]pero ahora tienes que pagar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Se paga cuando se viene, as胤 que[n]no tendr茨s que preocuparte por[n]contratos chungos ni nada de eso.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]El equipo es un poco cutre,[n]pero hay mucha variedad.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Adem茨s, es que es barat胤simo.[n]Vale totalmente la pena, aunque[n]no tenga piscina ni jacuzzi.[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se paga cuando se viene, as胤 que[n]no tendr茨s que preocuparte por[n]contratos chungos ni nada de eso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El equipo es un poco cutre,[n]pero hay mucha variedad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Adem茨s, es que es barat胤simo.[n]Vale totalmente la pena, aunque[n]no tenga piscina ni jacuzzi.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7184 65535 0]斡Ah, s胤! Tienes que traer una cosa.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]夷Una toalla?[e]
[s][f 0 8 2 1 2217]夷Prote胤na en polvo?[clr 27][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 5 2]Qu姻 va, te dejan una.[n][f 1 3 65535][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][vp 8 0 0 0 65535 0]斡Ropa interior, panoli![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ponerse la ropa sudada[n]despu姻s de una ducha caliente[n]da un asco que flipas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, pero no te ilusiones.[n]Yo no pienso prestarte[n]mi ropa.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 10 2]Claro, t胤o, si quieres ponerte[n]cachas, tienes que... 斡No, eso no![n][f 1 3 65535][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][vp 8 0 0 0 65535 0]斡Ropa interior, panoli![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ponerse la ropa sudada[n]despu姻s de una ducha caliente[n]da un asco que flipas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, pero no te ilusiones.[n]Yo no pienso prestarte[n]mi ropa.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7060 65535 0]Pues nada, a entrenar.[n][f 1 3 65535][w][e]

[msg MND_000_0_1]
[s][vp 8 0 0 0 65535 0]Ha dejado de llover.[n][f 1 3 65535][w][e]

