[msg MSG_000_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 10006 65535 0]Buenas tardes.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Chica oficinista]]
[s][vp 8 0 0 0 9 0]Hola, Mifune. Qu姻 ganas tengo[n]de la sesi吋n de hoy. Tu 雨ltima[n]predicci吋n fue casi perfecta.[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Chica oficinista]]
[s][vp 8 0 0 0 9 0]Por cierto, mmm... 夷Qui姻n es este?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, ni caso. Es mi aprendiz.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como mucho, piensa[n]que es un animal de tama隠o humano.[n]Mira qu姻 pelo m茨s suave.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Chica oficinista]]
[s][vp 8 0 0 0 9 0]夷Le parece bien[n]trabajar para una mujer?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 9 0]*suspiro* Eso es impensable[n]en mi trabajo.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10135 65535 0]夷Te ha pasado[n]algo m茨s en el trabajo?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Chica oficinista]]
[s][vp 8 0 0 0 9 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 113 5 300 65535]S胤, un compa隠ero se llev吋[n]todo el m姻rito por un proyecto[n]en el que me dej姻 la piel.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 9 0]夷Y sabes qu姻 me dijo mi jefe?[n]Que me aguantara,[n]que soy una mujer y esto es as胤.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Chihaya]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 113 5 300 1][vp 8 2 0 10047 65535 0]斡Qu姻 horror![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Chica oficinista]]
[s][vp 8 0 0 0 9 0]Por eso me estoy planteando[n]irme y montar mi propio negocio.[n]Ya llevo un tiempo plane茨ndolo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 9 0]Aunque no s姻 si conseguir姻[n]hacerme un hueco en el mercado...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10090 65535 0]斡A ver qu姻 dicen las cartas! Oh,[n]poder divino, mu姻stranos la verdad.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤... Lo he visto todo.[n][f 1 3 65535][w][e]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 50][vp 8 0 0 0 65535 0]Mmm. Las cartas est茨n al rev姻s.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 10091 65535 0]Eso quiere decir... que[n]tu negocio est茨 abocado al fracaso.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Chica oficinista]]
[s][vp 8 0 0 0 9 0]斡No! 斡夷Y-y ahora qu姻 hago?![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo siento, pero parece que[n]esta vez tu destino es ineludible.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Chica oficinista]]
[s][vp 8 0 0 0 9 0]夷Ineludible?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 piensas?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Me est茨s haciendo caso?[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s] <※1>[e]

[msg MSG_016_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10089 65535 0]夷Qu姻 podemos hacer para ayudar[n]a esta mujer oprimida por[n]un entorno de trabajo patriarcal?[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]Sugerir que se rinda.[e]
[s]Despertar el coraz吋n de su jefe.[e]
[s]Animarla.[e]

[msg MSG_018_0_0 [Chihaya]]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 10046 65535 0]Ha venido a que le lea[n]el futuro y a pedir consejo.[n]夷Esa es tu mejor sugerencia?[n][f 1 3 65535][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como no pienses[n]en otra cosa, voy a usar[n]mi poder divino para maldecirte.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10043 65535 0]No s姻 si he entendido[n]muy bien lo que quieres decir.[n][f 1 3 65535][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Te aconsejo que pienses en[n]otra cosa. Tengo poder para[n]maldecirte de por vida.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10026 65535 0]夷Qu姻? Es muy idealista[n]pensar que algo as胤 funcionar胤a.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A ver, 夷qu姻 le dir胤as[n]si quisieras animarla?[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s]斡Aaaah![e]
[s]斡Cambia el destino![e]
[s]斡Lucha contra el poder![e]

[msg MSG_023_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 10042 65535 0]斡Hala![n][f 1 3 65535][w][e]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E-eso no es animar,[n]斡es muy agresivo![n]斡Piensa bien la respuesta![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Chihaya]]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 10044 65535 0]斡No seas irresponsable![n]斡Eso no puede ser![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡夷C吋mo pretendes que evite[n]lo que es ineludible?![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Chihaya]]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 10021 65535 0]Sabes que hablamos del 姻xito[n]de su negocio, 夷no? No tiene[n]nada que ver con el poder.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Piensa bien la respuesta![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Chica oficinista]]
[s][vp 8 0 0 0 9 0]夷Que cambie el destino?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 9 0]Claro... 斡No tengo que seguir las[n]reglas de una sociedad opresora![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 9 0]Lo conseguir姻. 斡Reestructurar姻[n]todos los aspectos de mi industria![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Chica oficinista]]
[s][vp 8 0 0 0 9 0]Lo he decidido. 斡Voy a dejar[n]el trabajo y a montar un negocio![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 9 0]Y, si fracaso, al menos no[n]estar姻 trabajando para[n]un machista desgraciado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 9 0]斡Gracias, joven![n]Disculpa, Mifune.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 10040 65535 0]夷Eh?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Chihaya]]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 113 7 300 65535][vp 8 2 0 10044 65535 0]斡Qu姻 irresponsable eres,[n][f 4 1]! 斡Su mala suerte[n]est茨 clar胤sima![n][f 1 3 65535][w][e]

[msg MSG_029_5_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seguro que las cartas[n]me respaldan.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Chihaya]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 113 7 300 1][vp 8 2 0 10039 65535 0]斡夷Q-qu姻?![n][f 1 3 65535][w][e]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]P-parece que la secuencia de cartas[n]ha cambiado. 斡Ahora dicen que[n]su futuro financiero ser茨 un 姻xito![n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 has hecho?[n][f 1 3 65535][w][e]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 0 0 0 65535 0]夷Eres... vidente?[n]斡夷Has usado tus poderes para[n]cambiar el orden de las cartas?![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Mi poder divino puede enviar[n]a la gente como t雨 a las[n]profundidades del infierno![n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10069 65535 0]S胤, ser茨 eso.[n]Es la 雨nica manera...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No se puede cambiar el destino.[n]Es absoluto... As胤 debe ser.[n][f 1 3 65535][w][e]

[sel SEL_033_0_0 top]
[s]Qu姻 cabezota eres.[e]
[s][f 0 8 2 1 2217]Para cambiar, abre la mente.[clr 27][e]

[msg MSG_034_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]P-pero, si se pudiera cambiar[n]el destino, nadie comprar胤a[n]estas Piedras sagradas.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 11 5 1013]Igual no es tan mala idea.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero, de ser posible,[n]夷c吋mo voy a mantener[n]mi negocio de Piedras sagradas?[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡B-bueno![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya has cambiado el flujo[n]del destino dos veces[n]delante de mis narices.[n][f 1 3 65535][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][vp 8 2 0 10030 65535 0]斡El proceso de verificaci吋n[n]est茨 resultando ser mucho m茨s[n]significativo de lo que esperaba![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento la intensa motivaci吋n[n]de Chihaya.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Volver茨s pronto, 夷no?[n]斡Prom姻temelo![n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Bueno, ya est茨 bien[n]por hoy. 斡Buenas noches![n][f 1 3 65535][w][e]

