[msg MSG_000_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 10019 65535 0]Hace poco que mi reputaci吋n[n]ha empezado a mejorar.[n]斡Y la clientela est茨 muy contenta![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Hasta he podido usar mis poderes[n]para cambiar destinos[n]que parec胤an inevitables![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya veo que hace falta[n]una fuerte voluntad, como la tuya,[n]para cambiar el destino.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 113 7 300 65535][vp 8 0 0 0 65535 0]Ojal茨 pudiera hacer algo m茨s...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Hombre de mediana edad pedante]]
[s][vp 8 0 0 0 11 0]夷Est茨s descansando, Mifune?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Chihaya]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 113 7 300 1][vp 8 2 0 10040 65535 0]斡夷Se隠or Fukurai?![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]As胤 que t雨 eres el aprendiz[n]del que tanto he o胤do hablar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Por qu姻 est茨s[n]tan interesado en Mifune?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Me gusta que me lean el futuro.[e]
[s]Es una t胤a guay.[e]
[s]Es para un trabajo de clase.[e]

[msg MSG_006_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]夷Y por eso te interesaste[n]en que te tutelara? Pues tienes[n]que ser muy fan suyo...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]夷Guay? S胤 que eres raro.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]Bueno, esto es un negocio,[n]as胤 que termina lo antes posible.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]A todo eso, hay que decir[n]que tienes buen ojo[n]por haber elegido a Mifune.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Sus predicciones son como[n]la luz que gu胤a a las ovejas[n]descarriadas en la oscuridad.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 10029 65535 0]Por cierto, [f 4 1], este[n]es el se隠or Fukurai, el...[n]presidente de la APD.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, es verdad. 斡A雨n no sabes nada[n]sobre la APD! Son las siglas de...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]La Asamblea del Poder Divino.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mediante seminarios y sanaciones,[n]aliviamos el pesar de las mentes[n]y corazones que lo necesiten.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]Vendemos Piedras sagradas,[n]que son la fuente de nuestros[n]poderes divinos.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10018 65535 0]Se隠or Fukurai, eh...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]Y, por cierto, Yokoda me ha dicho[n]que 雨ltimamente act雨as de forma...[n]un poco rara.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Y, adem茨s, parece que no est茨s[n]alcanzando las ventas necesarias[n]este trimestre. 夷Va todo bien?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S-s胤. Compensar姻 esta bajada[n]con lo que saque de m茨s[n]de las adivinaciones.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se隠or Fukurai...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es que... no s姻 hasta qu姻 punto[n]son eficaces las Piedras sagradas...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]夷Perdona?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10069 65535 0]B-bueno...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]夷Ya no te acuerdas de qui姻n te[n]mostr吋 el camino cuando llegaste[n]sola y perdida desde tu pueblo?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷No recuerdas qui姻n te salv吋[n]cuando trabajabas en un club[n]de alterne turbio y peligroso?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Fui yo. 夷Y ahora me dices que[n]ya no conf胤as en aquel que ha[n]hecho tanto por ti?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]N-no quer胤a decir eso...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]Pues basta de tanto escepticismo.[n]C姻ntrate en cumplir tu papel[n]de Or茨culo del Alivio.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Adivina el futuro de las almas que[n]vienen a nosotros y gu胤alas a la[n]salvaci吋n con las Piedras sagradas.[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]夷Or茨culo del Alivio?[e]
[s]Ser茨 una broma.[e]

[msg MSG_022_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]Es el nombre que le puse[n]en la APD. Es precioso, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]Mmmm. Aquellos que bromean[n]no llegar茨n a la salvaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10110 65535 0]Yo...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]No quieres que todo vuelva[n]a ser como antes, 夷verdad, Mifune?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Te acuerdas de que te derrumbaste[n]y me contaste que todo el mundo[n]te llamaba monstruo?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Si no cumples con tu deber como[n]Or茨culo del Alivio ser茨s eso mismo,[n]un monstruo.[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s]Qu姻 t胤o m茨s raro.[e]
[s]D姻jala en paz.[e]

[msg MSG_027_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 1]...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Presidente Fukurai]]
[s][vp 8 0 0 0 65535 0]Vale. Si quieres perder el tiempo[n]con este cr胤o, adelante.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero acu姻rdate, Mifune,[n]de que la APD es el 雨nico lugar[n]en el que encajas.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10140 65535 0]Ja, ja, ja...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡N-nunca he trabajado en un club[n]de esos! Solo me enga隠aron[n]para que entrara a verlo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero, bueno, el presidente[n]ha exagerado un poco las cosas.[n][f 1 3 65535][w][e]
[s][bup 0 113 3 65535 0][f 4 24 0 4 0 38 5 50][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pensar茨s que soy un bicho raro, 夷no?[n]Que si soy un or茨culo[n]o un monstruo...[n][f 1 3 65535][w][e]

[sel SEL_030_0_0 top]
[s]夷Qu姻 es un Or茨culo del Alivio?[e]
[s]夷Qui姻n dice que seas un monstruo?[e]
[s][f 0 8 2 1 2217]Para m胤 eres solo Chihaya.[clr 27][f 2 7 0 1 738 1][e]

[msg MSG_031_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10069 65535 0]Es el t胤tulo[n]que me han dado en la APD.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10069 65535 0]Prefiero no recordarlo.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 10040 65535 0][f 5 13 11 15 1013]夷Eh? Nadie me hab胤a tratado[n]as胤 de bien hasta ahora.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10122 65535 0]Por cierto, hemos aguantado bien[n]el tipo delante del presidente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sola no me habr胤a atrevido[n]a hablarle[n]sobre las Piedras sagradas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ha sido tu fuerza la que me ha[n]ayudado a dar el paso.[n]Tengo que ser m茨s como t雨.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que Chihaya [n]est茨 muy decidida.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10021 65535 0]Aun as胤, el presidente parec胤a no[n]bromear sobre la Piedra sagrada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me har茨 pagar una multa[n]si no alcanzo mi objetivo...[n]y, si renuncio, me penalizan...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Supongo que no puedo[n]cambiar mi destino.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10131 65535 0]斡En fin, hora de cerrar![n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Chihaya]]
[s][vp 8 2 0 10054 65535 0]斡Buenas noches![n][f 1 3 65535][w][e]

