[msg MSG_000_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 10006 65535 0]Hac胤a mucho que no te ve胤a...[n]夷Te acuerdas de m胤?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yo desde luego[n]no me he olvidado de[n]una persona tan peculiar como t雨...[n][f 1 3 65535][w][e]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 0 0 0 65535 0]El d胤a que rechazaste[n]mi invitaci吋n... 斡descubr胤[n]tu verdadera identidad![n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]La confianza que Chihaya tiene[n]en m胤 depende de esta pregunta.[n]斡Tengo que responderla bien![n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]夷Que soy un Ladr吋n Fantasma?[e]
[s]夷Que soy un criminal?[e]
[s]夷Que te soy infiel?[e]

[msg MSG_003_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 10039 65535 0]斡夷A eso te has estado dedicando?![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Para ser estudiante de instituto,[n]tienes muchas aventuras amorosas...[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]斡He logrado que siga[n]confiando en m胤![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 10040 65535 0]夷Qu姻...? 夷En serio...?[n][f 1 3 65535][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]*grito ahogado* 斡Ahora mismo[n]no me interesa la verdad![n][f 1 3 65535][w][e]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 2 0 10103 65535 0]Aun as胤, 斡lo sab胤a![n]斡No eres un estudiante[n]de instituto normal![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya cada vez conf胤a[n]menos en m胤.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]斡Sabe que le he mentido![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Tendr姻 que recuperar su confianza.[n][f 1 3 65535][w][e]

