[msg MSG_000_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10019 65535 0]He reunido a todos los miembros[n]de la APD y les he pedido disculpas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Al principio no me cre胤an,[n]pero al final ha salido[n]la verdad a la luz.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10123 65535 0]Aunque parece que a los ejecutivos[n]todav胤a les dura el lavado [n]de cerebro.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estoy hablando con un abogado.[n]Recibiremos reembolsos[n]y nos ocuparemos de ellos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Devolver姻 todo el dinero que[n]gan姻 vendiendo Piedras sagradas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es lo m胤nimo que puedo hacer[n]por lo ignorante que he sido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As胤 que... acepta esto, [f 4 1].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No te lo tomes como una disculpa,[n]sino como un gesto de gratitud[n]por ayudarme a abrir los ojos.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yokoda]]
[s][vp 8 0 0 0 8 0]斡Or茨culo! 斡Me alegro de verte![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Chihaya]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 113 7 300 1][vp 8 2 0 10040 65535 0]斡夷Yokoda?! 斡夷Qu姻 hac姻is[n]todos aqu胤?![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yokoda]]
[s][vp 8 0 0 0 8 0]Tus disculpas eran falsas,[n]夷verdad? 斡Te amenazaron[n]para que dijeras eso![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 8 0]Quiero decir, al presidente le[n]tendieron una trampa, est茨 claro.[n]斡Dinos la verdad![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 10087 65535 0]N-no. Nada de lo que dije[n]era falso.[n][f 1 3 65535][w][e]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 2 0 10131 65535 0]Mirad, todo lo que os cont吋[n]el presidente en los seminarios[n]era mentira.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La promesa de un futuro brillante,[n]el poder de las Piedras sagradas,[n]la importancia de donar... Mentiras.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷No es raro que siguiera pidiendo[n]dinero a los miembros incluso en[n]momentos de dificultad financiera? [n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es m茨s, vosotros deber胤ais haber[n]sabido mejor que nadie d吋nde[n]acababan esas 或donaciones位.[n][f 1 3 65535][w][e]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 50][vp 8 2 0 10110 65535 0]Incluso yo sab胤a lo horrible que[n]era el plan de la APD.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por eso lo denunci姻.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Mujer taciturna]]
[s][vp 8 0 0 0 10 0]斡No! 斡No puede ser cierto![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Hombre con cara seria]]
[s][vp 8 0 0 0 7 0]斡T雨! 斡夷T雨 le has hecho esto[n]a nuestra hermosa Or茨culo?![n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]No lo entend姻is.[e]
[s]Escuchad a Chihaya.[e]

[msg MSG_010_0_0 [Yokoda]]
[s][vp 8 0 0 0 8 0]斡Cierra el pico![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Chihaya]]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 10027 65535 0]Por favor, 斡ya basta! 斡畏l no[n]tiene nada que ver con vuestra situaci吋n![n][f 1 3 65535][w][e]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 0 0 0 65535 0]斡Yo os vend胤 las piedras![n]Si vais a cabrearos[n]con alguien, 斡que sea conmigo![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Hombre con cara seria]]
[s][vp 8 0 0 0 7 0]Pero... Or茨culo...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Mujer taciturna]]
[s][vp 8 0 0 0 10 0]Madre m胤a...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yokoda]]
[s][vp 8 0 0 0 8 0]No, hay que seguir[n]confiando en ella.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 8 0]Por favor, Or茨culo, 斡l胤branos[n]de nuestro sufrimiento![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 8 0]Si nos dejas ahora,[n]斡estaremos condenados[n]a sumirnos en la tristeza![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10069 65535 0]M-mirad, 斡solo pod姻is cambiar[n]eso con vuestras convicciones![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No podemos ayudaros ni yo[n]ni esas piedras in雨tiles.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Mujer taciturna]]
[s][vp 8 0 0 0 10 0]P-pero 夷c吋mo vamos[n]a evitar nuestro infeliz destino?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Hombre con cara seria]]
[s][vp 8 0 0 0 7 0]No... 斡Una maldici吋n[n]se cierne sobre nosotros![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yokoda]]
[s][vp 8 0 0 0 8 0]斡Or茨culo, por favor![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Chihaya]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 113 3 300 1][vp 8 2 0 10108 65535 0]斡Callaos, por favor![n]斡Calmaos y escuchadme![n][f 1 3 65535][w][e]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 0 0 0 65535 0]斡Que se茨is infelices o no[n]depende de vosotros![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡No necesit茨is un poder divino[n]ni chorradas de esas[n]para cambiar vuestro destino![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Chihaya]]
[s][bup 0 113 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Todos ten姻is esa fuerza dentro![n]斡La adivinaci吋n no vale nada[n]ante la fuerza de voluntad![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y, leche, aunque las cosas[n]est姻n mal, todo ir茨 guay[n]si vais con la cabeza bien alta.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 10029 65535 0]Ah, lo siento.[n]Con el estr姻s pierdo las formas...[n][f 1 3 65535][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Pero mantengo lo que he dicho.[n]Nada cambiar茨 si os limit茨is[n]a apoyaros en los dem茨s.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Miradme a m胤, por ejemplo. Cre胤[n]que mi destino era vivir como un[n]monstruo y logr姻 dar marcha atr茨s.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si quer姻is controlar vuestro[n]futuro, solo necesit茨is... fuerza.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡El 雨nico modo de avanzar[n]es tener un coraz吋n fuerte![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yokoda]]
[s][vp 8 0 0 0 8 0]夷Un coraz吋n fuerte...?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quiz茨 no sea muy f茨cil[n]lograrlo al principio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Despu姻s de todo, vuestra fuerza[n]de voluntad qued吋 sofocada[n]por los seminarios y donativos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y yo tengo parte de culpa.[n][f 1 3 65535][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][vp 8 2 0 10147 65535 0]Por eso debo mostraros[n]la luz y ayudaros a aguantar.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yokoda]]
[s][vp 8 0 0 0 8 0]Or茨culo...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No, ya no soy el Or茨culo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ahora soy Chihaya Mifune,[n]斡la adivina que gu胤a el destino![n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 10028 65535 0]夷Estar茨n bien Yokoda y los dem茨s?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero s姻 c吋mo se sienten.[n]Se aferran a las Piedras sagradas[n]igual que yo a ser el Or茨culo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nosotros solo quer胤amos ser[n]felices, evitar nuestros destinos...[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]夷Te arrepientes?[e]
[s][f 0 8 2 1 2217]El destino se puede cambiar.[clr 27][e]
[s]Eso es agua pasada.[e]

[msg MSG_029_0_0 [Chihaya]]
[s][bup 0 113 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤, profundamente.[n][f 1 3 65535][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Pero por eso estoy aqu胤 ahora.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Voy a dar un paso adelante[n]hacia el futuro para ayudar[n]a los que perjudiqu姻.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 11 15 1013]Claro. Yo lo consegu胤, 斡as胤 que[n]estoy segura de que Yokoda[n]y los dem茨s tambi姻n podr茨n![n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 11 5 1013]Tienes raz吋n. Tengo que dar[n]un paso adelante hacia el futuro[n]para ayudar a los que perjudiqu姻.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Da igual cu茨ntas veces deba[n]intentarlo, hablar姻 con ellos[n]hasta que lo entiendan.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y, cuando abran los ojos,[n]los ayudar姻 a recuperarse.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En mi pueblo, la gente[n]me llamaba monstruo. Aqu胤,[n]me veneraban como el Or茨culo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aunque mi coraz吋n contin雨a[n]desorientado, t雨 lograste ver[n]mi verdadero yo.[n][f 1 3 65535][w][e]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][vp 8 2 0 10097 65535 0]Ni el Or茨culo, ni un monstruo...[n]Soy Chihaya.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 1]... Gracias.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento un fuerte v胤nculo[n]de confianza que emana de Chihaya.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 10094 65535 0]Por cierto, [f 4 1],[n]夷te ha dicho alguien que[n]eres un poco entrometido?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quiero decir que normalmente[n]a nadie se le ocurrir胤a[n]meterse en un fregado as胤.[n][f 1 3 65535][w][e]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 2 0 10096 65535 0]E-entonces, pues...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En realidad hay algo que[n]llevo pregunt茨ndome un tiempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Vienes a verme solo[n]para que te lea el futuro?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]N-no, 夷verdad?[n][f 1 3 65535][w][e]

[msg MND_034_3_0]
[s][vp 8 0 0 0 65535 0]Deber胤a tener mucho[n]cuidado con lo que digo.[n][f 1 3 65535][w][e]

[msg MND_034_5_0]
[s][vp 8 0 0 0 65535 0]Deber胤a tener mucho[n]cuidado con lo que digo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ya tengo [clr 2]una relaci吋n[n]con otra chica[clr 27].[n][f 1 3 65535][w][e]

[msg MSG_034_7_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10135 65535 0][f 4 1], 夷por qu姻 vienes?[n][f 1 3 65535][w][e]

[sel SEL_035_0_0 top]
[s]Me gusta que me lean el futuro.[e]
[s]Para poder estar contigo.[f 2 7 0 1 733 1][e]

[msg MSG_036_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A-ah, vale...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Perdona, supongo que me[n]lo estaba creyendo demasiado.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 10129 65535 0]Pero 斡no hay nada mejor[n]que saber que mis lecturas[n]ayudan a los dem茨s![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ven a que te lea[n]el futuro cuando quieras.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Al fin y al cabo, 斡estamos unidos[n]en nuestra misi吋n de oponernos[n]al destino![n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10051 65535 0]Pues nada, me voy.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Chihaya]]
[s][vp 8 2 0 10054 65535 0]斡Buenas noches![n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Chihaya]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 113 7 300 1][vp 8 2 0 10040 65535 0]夷Eh? Es broma, 斡夷no?![n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Chihaya]]
[s][bup 0 113 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 10087 65535 0]E-es que... 斡a m胤 tambi姻n me gustas![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero o胤rte decirlo[n]me ha dejado loca, leche.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Perdona, he vuelto[n]a perder las formas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero...[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Chihaya]]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 0][vp 8 2 0 10097 65535 0]Tengo muchas ganas[n]de conocerte mejor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero a las cartas del tarot[n]puede chocarles.[n]Mi fortuna en el amor no existe.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero supongo que se nos[n]da bastante bien cambiar[n]el destino, 夷eh? *risita*[n][f 1 3 65535][w][e]

[msg MND_044_5_0]
[s][vp 8 0 0 0 65535 0]Ahora tengo una relaci吋n[n]con Chihaya.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ya no hay vuelta atr茨s.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se est茨 haciendo tarde.[n][f 1 3 65535][w][e]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][vp 8 2 0 10084 65535 0]Pero... 夷no podemos hablar[n]un rato m茨s?[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Chihaya]]
[s][vp 8 2 0 10139 65535 0]Bueno..., buenas noches, [f 4 1].[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]L-lo sab胤a.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][bup 0 113 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][f 4 1], siempre prestas[n]atenci吋n a lo que digo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y por eso mismo me he dado cuenta...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eh, mis padres te han mandado[n]aqu胤 para vigilarme, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No se me ocurre otro motivo para[n]que te interese tanto lo que hago.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si te soy sincera, llegu姻 a pensar[n]que te gustaba...[n][f 1 3 65535][w][e]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][vp 8 2 0 10094 65535 0]Pero 斡es imposible![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, perdona, 斡no quer胤a que[n]pensases que siento algo por ti![n][f 1 3 65535][w][e]

[msg MND_048_5_0]
[s][vp 8 0 0 0 65535 0]Me ha rechazado.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 10135 65535 0]Oye, diles a mis padres[n]que me va bien.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, y... que ir姻 pronto a casa.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Chihaya]]
[s][bup 0 113 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷No? 夷No te han mandado ellos?[n]Pues perdona.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Supongo que tendr姻[n]que llamarlos yo...[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Chihaya]]
[s][bup 0 113 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 10131 65535 0]Q-quiz茨 me haya equivocado,[n]pero mis poderes de adivinaci吋n[n]a雨n funcionan, 斡te lo juro![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ven a que te lea[n]el futuro cuando quieras.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 10086 65535 0]Al fin y al cabo, 斡siempre estaremos[n]unidos en nuestra misi吋n[n]de oponernos al destino![n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Chihaya]]
[s][bup 0 113 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pues nada, me voy.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Chihaya]]
[s][vp 8 2 0 10054 65535 0]Buenas noches.[n][f 1 3 65535][w][e]

