[msg MSG_000_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 12015 65535 0]Parece que has tra胤do[n]un L茨quesis con Tetraja.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Al fin ves c吋mo funciona.[n]Bueno, otra tarea completada.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 0 11001 65535 0]Bueno, pasemos a la siguiente tarea[n]antes de que las cosas se l胤en[n]como la 雨ltima vez.[n][f 1 3 65535][w][e]

[msg MSG_002_5_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Justine, nada de preguntas[n]complejas. Solo dale la tarea.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 12020 65535 0]Entendido.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0][vp 8 2 0 11027 65535 0]夷Eh...? 夷Qu姻 pasa contigo?[n]Normalmente no eres[n]tan cooperativa.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No tengo intenci吋n de abandonar[n]mi deber, pero... me gustar胤a saber[n]la verdad de esta situaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A fin de cuentas, poseemos una[n]misteriosa lista que ha profetizado[n]el estado actual de las cosas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qui姻n la escribi吋? 夷Por qu姻[n]reconozco la caligraf胤a? 夷Por qu姻[n]su crecimiento provoca nostalgia?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y m茨s all茨 de eso... 夷cu茨l era la[n]verdadera intenci吋n de su creador?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 11035 65535 0]Pens姻 que hab胤a dicho que[n]nada de preguntas complejas.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si te soy sincera... creo[n]que tengo una hip吋tesis.[n][f 1 3 65535][w][e]

[msg MSG_007_1_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 7 300 1][vp 8 2 0 11096 65535 0]斡夷Qu姻?! 夷Sabes la respuesta?[n][f 1 3 65535][w][e]

[msg MSG_007_3_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gestionamos el poder del recluso[n]por varios arcanos que simbolizan[n]la naturaleza m胤stica del mundo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En realidad, el encuentro[n]que compartimos con 姻l lo[n]representa el arcano de la Fuerza.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La Fuerza representa un gran poder,[n]una voluntad poderosa,[n]y el despertar de lo desconocido...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tiene sentido.[n][f 1 3 65535][w][e]

[msg MSG_008_5_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Caroline... Cuando interactuamos,[n]夷ha sido el recluso el 雨nico al que[n]se le ha despertado algo dentro?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tal vez la respuesta resida en eso.[n][f 1 3 65535][w][e]

[msg MSG_009_5_0 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡夷Q-qu姻 quiere decir eso?![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uf, 斡maldita sea![n]夷Por qu姻 me siento tan rara?[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]夷Ya hab姻is acabado?[e]
[s]夷Me vais a dar mi recompensa?[e]
[s]...[e]

[msg MSG_011_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 300 1][vp 8 2 0 11032 65535 0]斡Q-que te calles, recluso! 夷No ves[n]que estamos en medio de algo?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Caroline]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 102 15 300 1][vp 8 2 0 11032 65535 0]斡Q-que te calles, recluso! 夷No ves[n]que estamos en medio de algo?[n][f 1 3 65535][w][e]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y ya te hemos dicho que tienes[n]que hacer tres tareas antes de que[n]te demos tu siguiente recompensa.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 11064 65535 0]Aunque esta tarea[n]va a ser la octava.[n]Ya no quedan tantas en la lista.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 5 0 41 3 100][vp 8 0 0 0 65535 0]Has llegado muy lejos, recluso.[n]Espero que llegues hasta el final.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Justine]]
[s][bup 0 101 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si lo consigues, la respuesta[n]quedar茨 clara.[n][f 1 3 65535][w][e]

[msg MSG_013_7_0 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y, eh...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ahora eres m茨s que un panoli[n]cualquiera para nosotras...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eres el 雨nico que puede encontrar[n]la respuesta que estamos buscando.[n]斡夷Lo pillas, recluso?![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo[n]con Caroline y Justine[n]se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 2 0 11071 65535 0]Pues hale, 斡siguiente! 斡Solo tienes[n]que traernos otra Persona para[n]obtener otra recompensa![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 2 0 12053 65535 0]Tu tarea es la siguiente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Obt姻n un Hecat吋nquiro[n]con Masukunda.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 2 0 11001 65535 0]Eso es un Hecat吋nquiro.[n]斡Uno que sabe Masukunda![n][f 1 3 65535][w][e]

