[msg MSG_000_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13071 65535 0]Vaya, eres justo la persona[n]con la que esperaba hablar.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tsuda me llam吋 hace un rato.[n]Me dijo que olvidara[n]todas sus amenazas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La verdad es que al principio[n]cre胤a que era broma, pero no[n]lo he visto ni nada desde entonces.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Iwai]]
[s][bup 0 104 3 0 0][f 4 10 65535 0 0][vp 8 2 0 13021 65535 0]Fue casi como hablar[n]con el viejo Tsuda.[n]Mi hermano de armas...[n][f 1 3 65535][w][e]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][f 4 24 0 4 0 0 5 100][vp 8 0 0 0 65535 0]Oye, 夷crees que alguien puede dar[n]un cambio dr茨stico as胤 de r茨pido?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Imposible no es.[e]
[s][f 0 8 2 1 2217]No lo s姻.[clr 27][e]
[s]Ha madurado.[e]

[msg MSG_004_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷T雨 crees?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Llevo m茨s tiempo que t雨 por[n]aqu胤, y nunca he visto nada igual.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13045 65535 0][f 5 13 13 5 1004]夷Qu姻 clase de respuesta es esa?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No soy qui姻n para hablar,[n]pero igual deber胤as tomarte[n]esto m茨s en serio.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Un hombre tan mayor deber胤a[n]haber madurado hace a隠os.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estar胤a de acuerdo contigo si[n]fueras t雨 o Kaoru, pero no Tsuda.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, sigue habiendo gato[n]encerrado, pero el cambio de Tsuda[n]me ha quitado un peso de encima.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13035 65535 0]Ah, y seguramente con esto[n]concluya nuestro trato, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tu parte consist胤a en[n]echar a Tsuda[n]y lo has cumplido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Una 雨ltima cosa...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13019 65535 0]S姻 que te desped胤 y tal,[n]pero 夷querr胤as seguir[n]trabajando aqu胤 conmigo?[n][f 1 3 65535][w][e]
[s][bup 0 104 3 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][f 4 24 0 4 0 1 5 100][vp 8 0 0 0 65535 0]S姻 que hoy en d胤a los chavales[n]ten姻is mucho que hacer, as胤 que[n]lo entiendo si me dices que no.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]Voy a volver.[e]
[s][f 0 8 2 1 2217]Bueno, me lo pensar姻.[clr 27][e]
[s][f 0 8 2 1 2217]Si me pagas bien, s胤.[clr 27][e]

[msg MSG_011_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13020 65535 0][f 5 13 13 5 1004]Estupendo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No pienses que te voy[n]a facilitar el trabajo, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13048 65535 0][f 5 13 13 10 1004]Eh, no te pongas as胤.[n]S姻 que quieres volver.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No pienses que te voy[n]a facilitar el trabajo, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13082 65535 0][f 5 13 13 10 1004]Je, parece ser que a雨n[n]sigues siendo valiente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No pienses que te voy[n]a facilitar el trabajo, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13089 65535 0]Cuento contigo, chaval.[n]Digo, [f 4 2].[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Iwai[n]se est茨 fortaleciendo a雨n m茨s.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Iwai]]
[s][bup 0 104 1 0 0][f 4 10 65535 0 0][vp 8 2 0 13086 65535 0]Vale, la primera tarea[n]es sacar la basura. Venga,[n]vamos a tirar estos prototipos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero desm吋ntalos y limpia[n]las huellas primero, 夷vale?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 13083 65535 0]斡Ah! Y no puedes irte[n]hasta que no termines.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Iwai]]
[s][vp 8 2 0 13054 0 0]Oye, hoy has hecho un buen trabajo.[n][f 1 3 65535][w][e]

