[msg MSG_000_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13018 65535 0]Tambi姻n tengo chaquetas militares,[n]desde modelos como los de la[n]Armada de los Estados Unidos hasta...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][bup 0 104 2 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 37 5 100][vp 8 0 0 0 65535 0]Si tan entusiasta eres,[n]sabr茨s qu姻 es la Armada, 夷no?[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]La confianza que Iwai tiene en m胤[n]depende de esta pregunta.[n]斡Tengo que responderla bien![n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]El Ej姻rcito del Aire.[e]
[s]La Marina.[e]
[s]El Ej姻rcito Brit茨nico.[e]

[msg MSG_003_0_0 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0][vp 8 2 0 13082 65535 0]Pues claro que lo sab胤as.[n]Es una de las ramas[n]de las Fuerzas Armadas.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]斡He logrado que siga[n]confiando en m胤![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Iwai]]
[s][bup 0 104 2 0 0][f 4 10 65535 0 0][vp 8 2 0 13046 65535 0]夷No lo sabes?[n]夷Y t雨 eres un entusiasta?[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 7 0][f 4 16 104 15 300 1 13103][vp 8 0 0 0 65535 0]Vete de aqu胤, anda.[n]No puedo confiar en ti.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Iwai cada vez conf胤a[n]menos en m胤.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]斡Sabe que le he mentido![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Tendr姻 que recuperar su confianza.[n][f 1 3 65535][w][e]

