[msg MSG_000_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 0 14018 65535 0]Ah, s胤. Me pondr姻 en contacto[n]contigo cuando tenga listo[n]el pr吋ximo ensayo cl胤nico.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Para entonces tendr姻 preparado[n]alg雨n pago por tu esfuerzo,[n]pero no lo voy a poner por escrito.[n][f 1 3 65535][w][e]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Seg雨n los resultados de hoy, creo[n]que puedo crear un f茨rmaco[n]nuevo. P茨sate cuando est姻s listo.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Me parece bien.[e]
[s][f 0 8 2 1 2217]No te pases conmigo.[clr 27][e]
[s]Cu茨ntas lucecitas...[e]

[msg MSG_003_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 14 5 1008]Me alegro.[n][f 1 3 65535][w][e]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 59 5 100]Vives cerca, 夷no?[n]Quiz茨 te marees un poco,[n]as胤 que ten cuidado al volver.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 0 14093 65535 0][f 5 13 14 15 1008]Ya veremos. Todo depende de ti.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vives cerca, 夷no?[n]Quiz茨 te marees un poco,[n]as胤 que ten cuidado al volver.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 14 5 1008]Te veo un poco desconcertado.[n]Quiz茨 deber胤a equilibrar[n]las cantidades...[n][f 1 3 65535][w][e]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 59 5 100]Vives cerca, 夷verdad?[n]Intenta que no te d姻 un jamacuco[n]de camino a casa.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14096 65535 0]No me apetece escribir[n]una autopsia, as胤 que ve[n]con cuidado.[n][f 1 3 65535][w][e]

