[msg MSG_000_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 4 0]En un caso como el tuyo,[n]se debe normalmente al estr姻s.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 4 0]Te voy a recetar un analg姻sico.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [M姻dica l茨nguida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 5 301 1][vp 8 0 0 3 4 0]Uy, pero si todav胤a[n]no me han tra胤do m茨s.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 4 4 0]Pues recurriremos a los somn胤feros.[n]Dicen que el sue隠o[n]es la mejor medicina, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 4 0]夷Los prefieres dulces o amargos?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Cualquiera me sirve.[e]
[s]夷Eso es todo lo que tienes?[e]
[s]Quiero analg姻sicos.[e]

[msg MSG_004_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 6 4 0]夷Y qu姻 tal unos que apesten?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 4 0]Es broma. No hay de esos.[n]Bueno, vayamos al grano.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 4 0]夷Eh? Pero si el paciente eres t雨.[n]夷Te parece normal decirme c吋mo[n]tengo que hacer mi trabajo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 4 0]Aj茨, lo que pensaba.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 4 0]夷Me equivoco? Y me juego lo[n]que quieras a que te gustar胤a[n]tener suficientes para un a隠o.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [M姻dica l茨nguida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 3 301 1][vp 8 0 0 11 4 0]No est茨s enfermo, 夷verdad?[n]Que no soy tan tonta como crees.[n][f 1 3 65535][w][e]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 12 4 0]Me imagino que has venido[n]por los rumores que corren[n]sobre m胤, 夷verdad?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]As胤 es.[e]
[s]Que estoy enfermo de verdad.[e]
[s]夷Los rumores son verdad?[e]

[msg MSG_009_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 13 4 0]Te traes algo entre manos...[n]El mundo se est茨 volviendo loco.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 14 4 0]Claaaro, claro. Todos dec胤s[n]lo mismo, pero luego todo se sabe.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 15 4 0]A saber, pero 雨ltimamente[n]no paran de venir pacientes[n]con segundas intenciones.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 16 4 0]Parece que os lo ponen dif胤cil[n]a los adolescentes, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 4 0]Vale, vale. Te recetar姻 algo.[n][f 1 3 65535][w][e]

[msg MSG_012_5_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 18 4 0]Pero solo un medicamento[n]que te mejore la salud.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 4 0]No creo que pase nada. Se te ve[n]sincero y sensato y no tienes pinta[n]de ir causando problemas.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 20 4 0]Esta es mi consulta privada.[n]Los medicamentos que distribuyo[n]son originales.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 4 0]Mi licencia me permite[n]trabajar con f吋rmulas propias que[n]habr茨s visto en otros hospitales.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 4 0]Cuidarte es cosa tuya,[n]as胤 que p茨sate cuando quieras.  [n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]Esto me ayudar茨 mucho.[e]
[s]Eres una m姻dica nefasta.[e]

[msg MSG_015_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 0 0 23 4 0]Perfecto. Qu姻 bien[n]que seas un chico avispado.[n]Me ahorras mucha faena.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 24 4 0]Mi intenci吋n es ofrecerles[n]reconocimientos m姻dicos f茨ciles[n]y r茨pidos a los pacientes.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 25 4 0]Eres un cr胤o la mar de raro,[n]夷lo sab胤as? A saber para qu姻[n]vas a usar el medicamento...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [M姻dica l茨nguida]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 26 4 0]Bueno, mientras no me des[n]problemas, por m胤 perfecto.[n][f 1 3 65535][w][e]

