[msg MSG_000_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 2 0 14028 65535 0]夷De qu姻 quieres hablar?[n]Te ped胤 que no volvieras[n]a venir aqu胤...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Padre de la chica]]
[s][vp 8 0 0 0 65535 0]斡Oh, doctora! 斡Doctora![n]斡Y t雨 tambi姻n![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷S胤?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Padre de la chica]]
[s][vp 8 0 0 0 65535 0]斡Ten胤a que hablar con usted[n]enseguida![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Usted trabajaba en el hospital[n]que ha salido en las noticias,[n]夷cierto?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Takemi]]
[s][bup 0 108 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷El hospital de las noticias?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Se隠ora mayor]]
[s][vp 8 0 0 0 8 0]Vaya por dios. Me temo que todo[n]el mundo ha pensado lo mismo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 8 0]Pero yo sab胤a que usted no era[n]capaz de hacer esas cosas[n]tan horribles.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 2 0 14043 65535 0]夷Q-qu姻 ocurre?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Se隠ora mayor]]
[s][vp 8 0 0 0 8 0]Vaya, a雨n no se ha enterado,[n]夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Padre de la chica]]
[s][vp 8 0 0 0 65535 0]El jefe m姻dico Oyamada se[n]ha entregado. Lo manipulaba todo[n]desde las sombras.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Resulta que 姻l fue el responsable[n]de aquel error m姻dico, y que le[n]ech吋 la culpa a su subordinado![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Padre de la chica]]
[s][vp 8 0 0 0 65535 0]El jefe m姻dico Oyamada se[n]ha entregado. Lo manipulaba todo[n]desde las sombras.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Resulta que 姻l fue el responsable[n]de aquel error m姻dico, y que le[n]ech吋 la culpa a su subordinado![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 7 301 1][vp 8 2 0 14039 65535 0]夷Es eso... cierto?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Padre de la chica]]
[s][vp 8 0 0 0 65535 0]斡Ha salido en los canales[n]de noticias de todo el pa胤s![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No lo he... visto...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Padre de la chica]]
[s][vp 8 0 0 0 65535 0]Ya dec胤a yo que algo no cuadraba[n]en esa historia.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Se隠ora mayor]]
[s][vp 8 0 0 0 8 0]Yo sab胤a que alguien como usted[n]no era capaz de hacer algo as胤.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Chica enferma]]
[s][vp 8 0 0 0 65535 0]斡Hurra, doctora![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero... 夷qu姻 es un error m姻dico?[n][f 1 3 65535][w][e]

[msg MSG_015_5_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻? Mmm... Es algo que[n]no se debe permitir que ocurra...[n]supongo.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 2 0 14101 65535 0]夷Se trata de una broma enrevesada?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oyamada se ha entregado...[n]justo en el momento oportuno.[n]夷Por qu姻...?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Takemi]]
[s][bup 0 108 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No importa. Es demasiado tarde.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eso no cambia el hecho de que[n]no pude salvarla.[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]Miwa est茨 viva.[e]
[s]Oyamada te minti吋.[e]

[msg MSG_019_0_0 [Takemi]]
[s][bup 0 108 4 0 0][f 4 10 65535 0 0][vp 8 2 0 14040 65535 0]斡夷Qu姻...?![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No puede ser...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 13 301 1][vp 8 2 0 14067 65535 0]斡夷Han dicho algo en las noticias[n]sobre la paciente involucrada[n]en el incidente del error m姻dico?![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Padre de la chica]]
[s][vp 8 0 0 0 65535 0]Oh, debe haber sido dif胤cil[n]para ella tambi姻n. He o胤do que[n]la han trasladado a otro hospital...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Se隠ora mayor]]
[s][vp 8 0 0 0 8 0]夷Qu姻 ocurre, querida?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Chica enferma]]
[s][vp 8 0 0 0 65535 0]斡夷Se encuentra bien, doctora?![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14045 65535 0]Entonces... est茨 viva...[n][f 1 3 65535][w][e]

[sel SEL_025_0_0 top]
[s]Deber胤as darte prisa.[e]
[s][f 0 8 2 1 2217]Manos a la obra, doctora.[clr 27][e]
[s]Esto a雨n no ha terminado.[e]

[msg MSG_026_0_0 [Takemi]]
[s][bup 0 108 4 0 0][f 4 10 65535 0 0][vp 8 2 0 14079 65535 0][f 5 13 14 5 1008]斡S胤, claro, tienes raz吋n![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14121 65535 0][f 5 13 14 15 1008]斡S胤, por supuesto![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14081 65535 0][f 5 13 14 10 1008]S胤, tienes raz吋n...[n]Tengo que acabar lo que empec姻.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Takemi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 108 16 300 1][vp 8 2 0 14058 65535 0]夷T雨 me ayudar茨s, verdad?[n]Retiro lo que dije. Continuaremos[n]con el desarrollo de inmediato.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Takemi[n]se est茨 fortaleciendo a雨n m茨s.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Takemi]]
[s][bup 0 108 2 0 0][f 4 10 65535 0 0][vp 8 2 0 14127 65535 0]Hoy iremos r茨pido,[n]as胤 que es posible que sientas un[n]poco de dolor durante la prueba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo siento. T雨 aguanta, 夷vale?[n][f 1 3 65535][w][e]

[sel SEL_031_0_0 top]
[s][f 0 8 2 1 2217]Lo har姻 por Miwa.[clr 27][f 2 7 0 1 739 1][e]
[s]Lo har姻 por mis ex茨menes.[e]
[s]Lo har姻 por ti.[e]

[msg MSG_032_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14126 65535 0][f 5 13 14 15 1008]Gracias. Eres muy buen chico.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cuando perfeccione el medicamento,[n]te presentar姻 a Miwa y le contar姻[n]lo mucho que me has ayudado.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14048 65535 0][f 5 13 14 5 1008]夷Por los ex茨menes de acceso?[n]Oh, 夷por eso has hecho todo esto?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, lo que t雨 digas.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Takemi]]
[s][bup 0 108 1 0 0][f 4 10 65535 0 0][vp 8 2 0 14048 65535 0][f 5 13 14 10 1008]Je, je. Tienes mucha labia.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De acuerdo, a la consulta.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Takemi]]
[s][vp 8 2 0 14115 65535 0]Eso es todo por hoy.[n]Cu胤date.[n][f 1 3 65535][w][e]

