[msg MSG_000_0_0 [Voz de m姻dica]]
[s][vp 8 0 0 0 65535 0]夷Qu姻 te pasa?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Est茨s resfriado? 夷Te duele el[n]est吋mago? 夷Tienes hongos[n]en los pies? Bueno, coge n雨mero.[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]斡Basta ya![n][f 1 3 65535][w][e]

[msg MSG_000_6_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]Solo t雨 podr胤as haber[n]desarrollado un medicamento as胤.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Voz de m姻dica]]
[s][vp 8 2 0 14028 65535 0]Siento decir que no tengo[n]ni idea de lo que hablas.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]No te hagas la tonta.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Se rumorea que es un f茨rmaco[n]tan potente que proporciona[n]un poder ilimitado.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Voz de m姻dica]]
[s][vp 8 0 0 0 65535 0]夷En serio? Es la primera vez[n]que lo oigo.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]Trabajar con f茨rmacos, medicamentos[n]y remedios experimentales[n]va contra las normas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Acaso buscas crear un[n]superestimulante? Una droga as胤[n]ser胤a un problema para todos.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Voz de m姻dica]]
[s][vp 8 0 0 0 65535 0]Qu姻 pesado eres.[n]Si solo soy una matasanos...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]Puede que la polic胤a no haga nada,[n]pero los medios se interesar茨n[n]tarde o temprano.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Quieres cargarte mi reputaci吋n[n]otra vez, 夷no? Eres una deshonra[n]para la comunidad m姻dica.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Voz de m姻dica]]
[s][vp 8 2 0 14041 65535 0]Ja...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]夷Por qu姻 me miras as胤?[n]Ha sido culpa tuya, 夷no?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No pienso ser responsable[n]de tus delitos. Deshazte[n]del 或medicamento位 y dimite.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]El nombre de Tae Takemi jam茨s...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]斡Hola! 斡夷Hay alguien ah胤?![n][f 1 3 65535][w][e]

