[msg MSG_000_0_0 [Aficionado persistente]]
[s][vp 8 0 0 0 65535 0]斡Gracias por darme la mano![n]斡No me la pienso lavar nunca![n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Hifumi]]
[s][bup 0 106 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 18024 65535 0]夷Eh? Es mejor que te la laves.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Aficionado persistente]]
[s][vp 8 0 0 0 65535 0]No me puedo creer que est姻s[n]aqu胤, en una iglesia...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He visto por internet que rezas[n]por la victoria. 夷Es cierto?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Aficionado persistente]]
[s][vp 8 0 0 0 65535 0]夷Me puedo hacer una foto[n]contigo para las redes sociales?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo siento, pero ya no acepto[n]propuestas de ese tipo...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Aficionado persistente]]
[s][vp 8 0 0 0 65535 0]Oye, 夷es verdad que est茨s[n]pensando en hacerte[n]jugadora profesional de shogi?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A雨n no he decidido...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Aficionado persistente]]
[s][vp 8 0 0 0 65535 0]斡Espero que te clasifiques![n]斡Ser胤as la primera mujer[n]en superar la liga de tercer dan![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Conf胤o en ti, puedes hacerlo![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Muchas gracias.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 18006 65535 0]Esto... Buenas tardes.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me encuentro con hombres[n]como 姻l constantemente.[n]Pens姻 que eras uno de ellos...[n][f 1 3 65535][w][e]

[msg MSG_010_5_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lamento much胤simo haberte[n]tratado de forma injusta...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 18043 65535 0]Me resulta muy inc吋modo[n]que se hable tanto de m胤... [n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Adem茨s, el cura me est茨[n]haciendo un gran favor al dejarme[n]jugar aqu胤.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es que es mi compa隠ero de shogi.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es muy amable. Un d胤a[n]me cont吋 que quer胤a ser[n]jugador profesional.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y no se r胤e de mi[n]vergonzosa costumbre cuando[n]jugamos juntos...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 18001 65535 0]Ah, fui a la sesi吋n de fotos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me pongo colorada solo de pensarlo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷La has visto? La han titulado[n]或La Venus del shogi位.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s][f 0 8 2 1 2217]Te describe perfectamente.[clr 27][e]
[s]La verdad es que no.[e]
[s]Pedazo de titular.[e]

[msg MSG_015_0_0 [Hifumi]]
[s][bup 0 106 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 18 5 1006]Va-vaya tonter胤a...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]D姻jalo ya.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Hifumi]]
[s][bup 0 106 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷S胤?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]E-entonces... Ay, creo que[n]he metido la pata.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Hifumi]]
[s][bup 0 106 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A decir verdad...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No quiero que suene a excusa,[n]pero fue a los de la editorial a[n]los que se les ocurri吋 ese t胤tulo.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Desde que gan姻 la liga[n]femenina de shogi, hay muchos ojos[n]puestos en m胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Creo que podr胤a aportar mi granito[n]de arena al mundo del shogi.[n]Adem茨s, mi madre est茨 muy contenta.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cada vez que gano, disfruta[n]la victoria como si fuese suya.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 18028 65535 0]Solo quiero cumplir las expectativas[n]que tiene puestas en m胤.[n][f 1 3 65535][w][e]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aunque 雨ltimamente est茨 demasiado[n]entusiasmada. La entrevista y la[n]sesi吋n de fotos fueron cosa suya.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es como si quisiera ser[n]la representante de una celebridad.[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]夷Es que no te gusta?[e]
[s][f 0 8 2 1 2217]夷Lo est茨s pasando mal?[clr 27][e]
[s]Deber胤as rechazar.[e]

[msg MSG_022_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No, la verdad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero no pasa nada.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 18 5 1006]Un poco...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero no pasa nada,[n]porque lo hago por mi madre.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No puedo...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Hifumi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 106 7 300 1][vp 8 2 0 18032 65535 0]斡Oh, lo siento! Deber胤a estar[n]ense隠茨ndote a jugar,[n]no habl茨ndote de mi madre.[n][f 1 3 65535][w][e]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hoy te mostrar姻 algo muy pr茨ctico.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es una t茨ctica para usar de manera[n]m茨s efectiva los peones en reserva[n]que le hayas arrebatado al rival.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No obstante, quisiera disculparme.[n]Sabes escuchar, y me siento[n]muy c吋moda hablando contigo.[n][f 1 3 65535][w][e]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 18071 65535 0]Eres la primera persona, adem茨s[n]del cura, a quien le cuento[n]cosas de mi madre.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Creo que Hifumi[n]cada vez conf胤a m茨s en m胤.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y ahora, te ense隠ar姻[n]mientras jugamos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 18059 65535 0]夷Preparado?[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Hifumi]]
[s][vp 8 2 0 18053 65535 0]Bueno, pues aguardar姻 con ansias[n]nuestra pr吋xima partida.[n][f 1 3 65535][w][e]

