[msg MND_000_5_0]
[s][vp 8 0 0 0 65535 0]Es una retransmisi吋n en l胤nea[n]de la partida. Los comentaristas[n]describen las jugadas.[n][f 1 3 65535][w][e]

[msg MSG_000_0_0 [Periodista de la revista de shogi]]
[s][vp 8 0 0 0 65535 0]夷Se le acaba la fiesta[n]a la princesa tramposa?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Editor de la revista de shogi]]
[s][vp 8 0 0 0 65535 0]Se ve obligada a irse retirando.[n]Ya solo es cuesti吋n de tiempo...[n][f 1 3 65535][w][e]

[msg MND_001_5_0]
[s][vp 8 0 0 0 65535 0]Hifumi se muerde el labio.[n]No parece que le est姻[n]yendo muy bien...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Editor de la revista de shogi]]
[s][vp 8 0 0 0 65535 0]Vaya, 斡esa s胤 que ha sido[n]una jugada impresionante![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Periodista de la revista de shogi]]
[s][vp 8 0 0 0 65535 0]夷Y si de verdad es buena?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Editor de la revista de shogi]]
[s][vp 8 0 0 0 65535 0]Vaya, la cosa pinta mal.[n]La pr吋xima jugada ser茨 jaque.[n][f 1 3 65535][w][e]

[msg MND_004_5_0]
[s][vp 8 0 0 0 65535 0]Parece que Hifumi est茨 en apuros,[n]apenas le queda tablero.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A雨n no ha hecho una jugada.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Periodista de la revista de shogi]]
[s][vp 8 0 0 0 65535 0]夷Qu姻 te parece un titular como[n]或La ca胤da de la princesa tramposa位?[n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Voz de Hifumi]]
[s][vp 8 0 0 0 65535 0]Me rindo.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Hifumi]]
[s][bup 0 106 5 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 106 12 300 65535][vp 8 2 0 18027 65535 0]Esa partida ha sido humillante.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me sent胤a como una hormiga ante[n]un elefante. Una buena jugadora[n]de shogi conoce sus l胤mites.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Hifumi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 106 12 300 1][vp 8 2 0 18028 65535 0]Ha sido la primera y 雨nica vez[n]que he abandonado una partida.[n][f 1 3 65535][w][e]
[s][bup 0 106 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me he sentido tan avergonzada...[n]No quer胤a seguir mancillando[n]las piezas ni un segundo m茨s.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]Te has esforzado mucho.[e]
[s][f 0 8 2 1 2217]Ya ganar茨s la siguiente.[clr 27][e]
[s]Una decisi吋n digna de una reina.[e]

[msg MSG_011_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gracias...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pues...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Con mi actual nivel, lo veo[n]complicado, pero me esforzar姻[n]en mejorar.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 18 10 1006]斡Te has acordado![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Las derrotas hay que encajarlas[n]con elegancia y dignidad,[n]tal y como har胤a una reina.  [n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Admito que estoy algo confusa.[n]Huelga decir que la derrota[n]supone una decepci吋n...[n][f 1 3 65535][w][e]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero, aun as胤, me siento feliz,[n]como si mis demonios[n]se hubieran evaporado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En cuanto vi que ganar era[n]poco m茨s que imposible,[n]me invadi吋 una extra隠a paz.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Solo importa lo que haga[n]a partir de ahora.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y pensar que has visto[n]lo mal que he jugado...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero puedes tom茨rtelo como ejemplo[n]de lo que no hay que hacer.[n][f 1 3 65535][w][e]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 18088 65535 0]As胤 entender茨s que, en ocasiones,[n]es preferible abandonar[n]con gracia y valor.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Creo que Hifumi[n]cada vez conf胤a m茨s en m胤.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 18066 65535 0]Llevo un tiempo d茨ndole[n]vueltas al tema...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hoy ser茨 el d胤a en el que[n]recibas tu 雨ltima clase.[n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estar conmigo solo[n]te ha tra胤do sufrimiento...[n][f 1 3 65535][w][e]

[msg MND_016_7_0]
[s][vp 8 0 0 0 65535 0]Hifumi est茨 muy concentrada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Deber胤a tener cuidado con[n]lo que digo en esta situaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_016_8_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As胤 que aqu胤 nos despedimos.[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s]Quiero ser m茨s fuerte.[e]
[s]Quiero quedarme a tu lado.[e]

[msg MSG_018_0_0 [Hifumi]]
[s][bup 0 106 4 65535 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 106 1 300 65535][vp 8 0 0 0 65535 0]A veces tienes unas cosas...[n][f 1 3 65535][w][e]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Deber胤a aprender a ser tan[n]ambiciosa como t雨.[n][f 1 3 65535][w][e]

[msg MSG_018_5_0 [Hifumi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 106 1 300 1][vp 8 2 0 18048 65535 0]Si eso es lo que quieres,[n]ve prepar茨ndote. Vas a recibir un[n]entrenamiento bastante intensivo.[n][f 1 3 65535][w][e]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quiz茨 yo tambi姻n aprenda[n]algunas cosas de ti.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Imagino que esto es una rivalidad[n]amistosa... como compa隠eros[n]irremplazables de shogi.[n][f 1 3 65535][w][e]

[msg MSG_018_7_0 [Hifumi]]
[s][vp 8 2 0 18049 65535 0]Bueno, v茨monos a casa.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Hifumi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 106 7 300 1][vp 8 2 0 18024 65535 0]夷Eh...? 夷Qu姻 has...?[n][f 1 3 65535][w][e]
[s][bup 0 106 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Solo intentas hacerme sentir mejor[n]porque he perdido, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Hifumi]]
[s][bup 0 106 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]P-para ya, por favor...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Soy la princesa tramposa,[n]le he mentido a todo el mundo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Y aun as胤, quieres[n]estar a mi lado...?[n][f 1 3 65535][w][e]

[msg MND_900_0_0]
[s][vp 8 0 0 0 65535 0]Deber胤a tener mucho[n]cuidado con lo que digo.[n][f 1 3 65535][w][e]

[msg MND_901_0_0]
[s][vp 8 0 0 0 65535 0]Deber胤a tener mucho[n]cuidado con lo que digo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ya tengo [clr 2]una relaci吋n[n]con otra chica[clr 27].[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷A qu姻 te refieres?[n][f 1 3 65535][w][e]

[sel SEL_021_5_0 top]
[s]Quiero tener una cita contigo.[f 2 7 0 1 737 1][e]
[s]Seremos amigos para siempre.[e]

[msg MSG_021_7_0 [Hifumi]]
[s][bup 0 106 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷En serio? 夷Lo dices de coraz吋n?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Hifumi]]
[s][bup 0 106 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pues si eso es lo que quieres, yo...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Hifumi]]
[s][bup 0 106 6 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me convertir姻 en una mujer[n]digna de ti.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 18085 65535 0]E-espero que... nuestra relaci吋n[n]prospere e-en los muchos a隠os que...[n]nos quedan por vivir juntos...[n][f 1 3 65535][w][e]
[s][bup 0 106 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ay, pero 夷q-qu姻 demonios[n]estoy diciendo...?[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Hifumi y yo ahora tenemos[n]una relaci吋n especial.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ya no hay vuelta atr茨s.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Hifumi]]
[s][bup 0 106 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Amigos...[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤, tienes raz吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Somos camaradas que se ayudan[n]a mejorar, por as胤 decirlo.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seguir姻 trabajando duro[n]para mejorar. La nuestra ser茨[n]una rivalidad amistosa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 18059 65535 0]Disfrutar姻 de nuestra amistad como[n]compa隠eros insustituibles de shogi.[n]斡Y que sea por muchos a隠os![n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Hifumi]]
[s][vp 8 2 0 18049 65535 0]V茨monos a casa.[n][f 1 3 65535][w][e]

