[msg MSG_000_0_0 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 19028 65535 0]夷Te acuerdas de los tipos que[n]le dieron una paliza a Akiyama?[n][f 1 3 65535][w][e]
[s][bup 0 111 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Resulta que eran muy peligrosos.[n]Los he buscado por internet[n]y he encontrado cosas preocupantes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Forman parte de una banda[n]involucrada en extorsiones.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 38 5 100]Ojal茨 lo hubiera sabido antes...[n]Un paso en falso[n]y soy hombre muerto.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]S胤, bien muerto.[e]
[s][f 0 8 2 1 2217]Has mostrado mucha valent胤a.[clr 27][e]
[s]Me alegro de que sigas vivo.[e]

[msg MSG_002_0_0 [Mishima]]
[s][bup 0 111 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 19082 65535 0]Tampoco hace falta pasarse.[n][f 1 3 65535][w][e]
[s][bup 0 111 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ni hablar.[n]No funcionar胤a ni en sue隠os.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 19039 65535 0][f 5 13 19 10 1011]夷D-de verdad lo crees?[n]Casi me meo de miedo otra vez[n]cuando los estaba investigando...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 19035 65535 0][f 5 13 19 5 1011]斡Yo tambi姻n! C吋mo voy[n]a disfrutar de la vida.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero t雨 eres incre胤ble, en serio.[n]No ten胤as nada de miedo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Puede que sea lo normal[n]despu姻s de todas las pesadillas[n]a las que te has enfrentado.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]斡Buenas, Mishima![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Mishima]]
[s][bup 0 111 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 19001 65535 0]H-hola...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Estudiante de instituto de pelo corto]]
[s][vp 8 0 0 0 11 0]斡Vaya, s胤 que es Mishima![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Estudiante de instituto de cejas finas]]
[s][vp 8 0 0 0 12 0]夷Verdad? 夷Qui姻n sino podr胤a[n]ser tan muermo?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Akiyama]]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Estudiante de instituto de cejas finas]]
[s][vp 8 0 0 0 12 0]夷Ya sabes a qu姻 te vas a dedicar[n]cuando acabes el instituto?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Mishima]]
[s][bup 0 111 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 19044 65535 0]A-a雨n no...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Estudiante de instituto de cejas finas]]
[s][vp 8 0 0 0 12 0]夷Y si te alistas en el ej姻rcito?[n]Un mindundi como t雨 ser胤a[n]indetectable en una infiltraci吋n.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Estudiante de instituto de pelo corto]]
[s][vp 8 0 0 0 11 0]斡Ja, ja! 斡Qu姻 buena! Apuesto[n]a que podr胤as colarte donde sea.[n]斡Ser胤as nuestra arma definitiva![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akiyama]]
[s][vp 8 0 0 0 65535 0]斡Callaos de una vez![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Mishima]]
[s][bup 0 111 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Akiyama...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Estudiante de instituto de cejas finas]]
[s][vp 8 0 0 0 12 0]夷Eh? 夷Te pasa algo?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Akiyama]]
[s][vp 8 0 0 0 65535 0]No es nada...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Venga, olvid姻monos de 姻l.[n]Meterse con Mishima[n]ya no es divertido.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Estudiante de instituto de pelo corto]]
[s][vp 8 0 0 0 11 0]夷C吋mo que no? Si te pasas[n]el santo d胤a haci姻ndolo.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Akiyama]]
[s][vp 8 0 0 0 65535 0]Me habr姻 cansado, yo qu姻 s姻.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Akiyama]]
[s][vp 8 0 0 0 65535 0]Oye, sobre lo de antes...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He estado pensando y...[n]deber胤a darte las gracias.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Estudiante de instituto de pelo corto]]
[s][vp 8 0 0 0 11 0]夷Qu姻 ha pasado entre vosotros dos?[n]Akiyama, 雨ltimamente[n]has estado muy raro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 11 0]No te creas que no he notado[n]todos los moratones que tienes.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Akiyama]]
[s][vp 8 0 0 0 65535 0]Y-yo...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 19038 65535 0]夷Qu姻? 夷或Lo de antes位? No s姻[n]de qu姻 me est茨s hablando.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Akiyama]]
[s][vp 8 0 0 0 65535 0]Mishima...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Me habr姻 confundido de persona.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]S胤 que has cambiado.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Mishima]]
[s][bup 0 111 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 19039 65535 0]夷S胤?[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Akiyama]]
[s][vp 8 0 0 0 65535 0]Eh, cuatro ojos. Siempre os veo[n]juntos. 夷Has estado entren茨ndole?[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]Algo as胤.[e]
[s]Exactamente.[e]

[msg MSG_029_0_0 [Akiyama]]
[s][vp 8 0 0 0 65535 0]Ah, 夷s胤? Menuda envidia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Estudiante de instituto de cejas finas]]
[s][vp 8 0 0 0 12 0]E-espera, Akiyama.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 19024 65535 0]Parece que Akiyama estar茨 bien.[n]Es un t胤o con mucho car茨cter.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y yo... he cambiado, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Crees que empiezo a parecerme[n]a los Ladrones Fantasma?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 19080 65535 0]斡Voy a trabajar a destajo[n]para estar a vuestra altura![n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Mishima est茨 decidido[n]a m茨s no poder.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Mishima]]
[s][bup 0 111 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 19104 65535 0]Siempre pens姻[n]que no serv胤a para nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero he conseguido mejorar y he[n]ayudado a Akiyama con esos matones.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ahora soy consciente de que puedo[n]hacer algo para salvar a los dem茨s.[n][f 1 3 65535][w][e]

[msg MSG_032_1_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por eso he empezado a escribir[n]un documental sobre[n]los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me decid胤 a hacerlo[n]cuando investigu姻 la banda[n]relacionada con Akiyama.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estoy extrayendo de la Fansite un[n]registro de vuestras actividades.[n][f 1 3 65535][w][e]

[sel SEL_032_2_0 top]
[s]No uses nuestros nombres reales.[e]
[s]夷De d吋nde ha salido la idea?[e]
[s]Qu姻 ganas de verlo.[e]

[msg MSG_032_3_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 19037 65535 0]斡No te preocupes, que no estoy[n]usando vuestros nombres de pila![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si ten姻is nombres en clave,[n]tambi姻n me sirven.[n][f 1 3 65535][w][e]

[msg MSG_032_4_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 19020 65535 0]Si te soy sincero, he estado[n]guardando art胤culos sobre vosotros[n]en un 茨lbum todo este tiempo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Habr胤a sido un desperdicio no[n]aprovechar el tener cerca[n]a gente tan incre胤ble.[n][f 1 3 65535][w][e]

[msg MSG_032_5_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 19024 65535 0]Cu茨nta presi吋n... pero[n]斡os demostrar姻 lo que puedo hacer![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gan姻 un concurso de relatos[n]en quinto, as胤 que no ser茨[n]tan complicado, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Mishima]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 111 14 300 1][vp 8 2 0 19080 65535 0]斡Bueno, esto hay que[n]celebrarlo! 斡Invito yo![n][f 1 3 65535][w][e]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se acabaron las bebidas baratas...[n]斡A por los zumos de frutas de lujo![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Si valen tres veces m茨s, tienen[n]que estar el triple de buenos![n][f 1 3 65535][w][e]

[sel SEL_033_5_0 top]
[s]Meh.[e]
[s]夷No quieres un helado?[e]
[s]En realidad me apetece un filete.[e]

[msg MSG_033_6_0 [Mishima]]
[s][bup 0 111 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero tengo el dinero justo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si quieres pedir algo m茨s,[n]tendr茨s que pagarlo t雨, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_033_7_0 [Mishima]]
[s][bup 0 111 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En fin... 斡Vamos a celebrar[n]hasta que salga el 雨ltimo tren![n][f 1 3 65535][w][e]

[msg MSG_033_8_0 [Mishima]]
[s][f 4 7 65535][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 111 1 300 1][vp 8 2 0 19083 65535 0]斡Uoooh![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Mishima]]
[s][vp 8 2 0 19128 65535 0]斡Nos vemos![n][f 1 3 65535][w][e]

