[msg MSG_000_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]El podio est茨 listo.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20030 65535 0]Gracias. Te lo agradezco,[n]pero...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Lo s姻. No quieres ser mi mano[n]derecha, 夷verdad? No te preocupes,[n]que no te la voy a jugar.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Habla todo lo que quieras[n]de la acusaci吋n falsa, que yo[n]asumo las consecuencias.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]He visto al nieto de Kuramoto[n]rondando por aqu胤.[n]Seguro que le pica la curiosidad.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20064 65535 0]No he hablado con 姻l desde[n]que nos vimos la 雨ltima vez.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Aprovecha el discurso[n]para responderle.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]Dudo que ning雨n partido[n]apoye al 或in雨til Tora位.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Voz de otro hombre]]
[s][vp 8 0 0 0 65535 0]Tengo entendido que va a hablar[n]de los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Voz de hombre]]
[s][vp 8 0 0 0 65535 0]Yoshida me da igual.[n]Lo que me interesa es lo que[n]se diga de los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20079 65535 0]Muy bien, all茨 voy.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s][f 0 8 2 1 2217]Hazlo lo mejor que puedas.[clr 27][e]
[s]Mucha mierda.[e]
[s]Me estoy poniendo nervioso.[e]

[msg MSG_011_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 2 0 20082 65535 0][f 5 13 20 10 1012]Lo har姻. Y m茨s sabiendo[n]que est茨s mirando.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 2 0 20082 65535 0]Eso espero.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 2 0 20048 65535 0][f 5 13 20 5 1012]Ja, ja. Yo tambi姻n.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20088 65535 0]Todos sabr姻is que se ha relacionado[n]a los Ladrones Fantasma con los[n]sucesos ocurridos recientemente.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Pero 夷qu姻 haces, Toranosuke?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Dejando de lado[n]si sus acciones son correctas...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20088 65535 0]El motivo de que hayan armado[n]semejante revuelo es porque abordan[n]los problemas que padece el mundo.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Pero 夷qu姻 haces, Toranosuke?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Dejando de lado[n]si sus acciones son correctas...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hay algo de los Ladrones Fantasma[n]que puedo afirmar con seguridad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Creer con firmeza en una idea[n]puede llegar a cambiar[n]el coraz吋n de la gente.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Yoshida]]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][vp 8 2 0 20086 65535 0]S姻 que ustedes me conocen como[n]或in雨til Tora位, y que fui acusado[n]por malversaci吋n de fondos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hace veinte a隠os, no era m茨s[n]que un necio. Es natural[n]que no lograra nada como pol胤tico.[n][f 1 3 65535][w][e]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][f 4 24 0 4 0 0 5 100][vp 8 0 0 0 65535 0]Sin embargo, aquella acusaci吋n[n]me ayud吋 comprender[n]el sufrimiento de los d姻biles.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20081 65535 0]夷Por qu姻 me met胤 en pol胤tica?[n]En el pasado lo hice para buscar[n]mi propio beneficio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero 夷por qu姻[n]los Ladrones Fantasma[n]despiertan corazones?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mi opini吋n es que lo hacen[n]para ayudar al mundo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y por culpa de buscar justicia para[n]los dem茨s, no les qued吋 m茨s remedio[n]que ocultar su identidad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No me importa lo que diga la gente,[n]pues tienen mi apoyo incondicional.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20086 65535 0]Soy un ciudadano como cualquier[n]otro, pero no dudar姻[n]en expresar mis ideas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 13 301 65535][vp 8 0 0 0 65535 0]Puede que no logre llegar a ser[n]diputado en estos comicios...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y que tampoco consiga cambiar[n]nada en lo que me queda de vida...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yoshida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 13 301 1][vp 8 2 0 20087 65535 0]Pero lo tengo m茨s que asumido.[n][f 1 3 65535][w][e]
[s][bup 0 112 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Me vale con plantar la semilla[n]que d姻 lugar a un futuro mejor[n]para nuestros j吋venes![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gracias por su atenci吋n.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]夷Para esto te ayudo?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]As胤 que nada de acusar[n]al se隠or Kuramoto.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20023 65535 0]Eso es.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Vaya, qu姻 discurso tan emotivo[n]para alguien de tu edad.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Seguro que se r胤en a tus espaldas[n]mientras hablamos. Dudo mucho[n]que los hayas conmovido.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]A lo mejor soy el 雨nico[n]de toda la ciudad a quien[n]has enternecido...[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Yoshida]]
[s][bup 0 112 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Matsushita...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Enfoca tu candidatura como quieras.[n]Yo me asegurar姻[n]de que el partido te respalde.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Dentro de lo posible, claro.[n]Adi吋s.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20021 65535 0]Conque mi candidatura, 夷eh...? Qu姻 giro[n]de los acontecimientos tan inesperado.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Los Ladrones Fantasma...[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ser茨 porque me has llegado[n]al coraz吋n.[n][f 1 3 65535][w][e]

[sel SEL_034_0_0 top]
[s]夷De qu姻 hablas?[e]
[s][f 0 8 2 1 2217]Te han despertado el coraz吋n.[clr 27][e]
[s]...[e]

[msg MSG_035_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Te espera un futuro brillante[n]como diputado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][vp 8 2 0 20075 65535 0]Seguro que podr茨s guardar[n]la compostura cuando[n]la oposici吋n te provoque.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 20 5 1012]Ser茨 eso. Por cierto, a雨n[n]no te he dado las gracias[n]como es debido.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya, tienes raz吋n...[n]No hace falta decir nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 20032 65535 0]夷O es que te has aburrido de[n]mis historias con tanto discurso?[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Los Ladrones Fantasma... El poder[n]de despertar un coraz吋n...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yo no tengo poderes especiales[n]como ellos, pero a convicci吋n[n]no hay quien me gane.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Las palabras son mi 雨nica arma.[n]Tan solo uso mi voz y mi ret吋rica[n]para ganarme a los dem茨s.[n][f 1 3 65535][w][e]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][vp 8 2 0 20030 65535 0]Gracias por quedarte[n]a mi lado, [f 4 1].[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo[n]con Yoshida se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 2 0 20075 65535 0]Al contrario de lo que pensaba,[n]que te despierten el coraz吋n[n]no es malo en absoluto. [n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si es un miembro de los[n]Ladrones Fantasma, entonces...[n][f 1 3 65535][w][e]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Ya estoy otra vez hablando solo.[n]Es una mala costumbre que tengo.[n]Va siendo hora de acabar por hoy.[n][f 1 3 65535][w][e]

[msg MSG_040_5_0 [Yoshida]]
[s][vp 8 2 0 20054 65535 0]Buen trabajo...[n][f 1 3 65535][w][e]

