[msg MSG_000_0_0 [Yoshida]]
[s][bup 0 112 2 0 0][f 4 10 65535 0 0][vp 8 2 0 20088 65535 0]La convicci吋n de un gobierno[n]se suele poner a prueba[n]en 姻pocas de confusi吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sin embargo, la administraci吋n[n]actual se niega a hablar[n]de sus planes para el futuro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡夷De verdad vamos a tolerar[n]semejante falta de transparencia?![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Mujer con cara de agotamiento]]
[s][vp 8 0 0 0 7 0]郁ltimamente la gente critica[n]un mont吋n al gobierno por eso.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Hombre con cara de aburrimiento]]
[s][vp 8 0 0 0 6 0]Eso es porque el diputado Shido[n]est茨 ganando popularidad[n]a base de decir lo mismo.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Mujer con cara de agotamiento]]
[s][vp 8 0 0 0 7 0]Entonces, 夷se dedica a repetir las cr胤ticas[n]al gobierno de otro pol胤tico?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Hombre con cara de aburrimiento]]
[s][vp 8 0 0 0 6 0]Eso parece. Tsss. Pues vale...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Detractor de Yoshida]]
[s][vp 8 0 0 0 65535 0]Si ya robaste fondos de tu partido.[n]斡夷Ahora te dedicas a robar ideas,[n]或in雨til Tora位?![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Detractor de Yoshida]]
[s][vp 8 0 0 0 65535 0]斡No te las des de importante,[n]exconvicto![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yoshida]]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][vp 8 2 0 20027 65535 0]Vaya, creo que he vuelto[n]a enfadar al p雨blico.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Insin雨a que los que han cometido[n]errores en el pasado no deber胤an[n]tener una segunda oportunidad?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷C吋mo respondo yo a eso?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Deja de interrumpirlo.[e]
[s]Est茨s molestando al p雨blico.[e]
[s]Calla y escucha.[e]

[msg MSG_009_0_0 [Detractor de Yoshida]]
[s][vp 8 0 0 0 65535 0]夷Perdona?[n]斡夷Te pasa algo conmigo, chaval?![n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]S胤.[e]
[s]夷A ti qu姻 te parece?[e]

[msg MSG_012_0_0 [Detractor de Yoshida]]
[s][vp 8 0 0 0 65535 0]夷Qu姻 mosca le ha picado al cr胤o?[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]El exconvicto tiene raz吋n.[e]
[s]Escucha lo que tiene que decir.[e]
[s]夷Y si no es tan in雨til como crees?[e]

[msg MSG_014_0_0 [Detractor de Yoshida]]
[s][vp 8 0 0 0 65535 0]Vaya ni隠ato...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 3 301 65535][vp 8 0 0 0 65535 0]S胤, soy 或el in雨til Tora位[n]y he cometido errores. S胤, soy[n]poco popular y no tengo poder.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero 斡eso no tiene nada que ver[n]con mis argumentos! Y esto[n]lo he aprendido por la fuerza.[n][f 1 3 65535][w][e]
[s][f 4 7 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 3 301 1][f 4 24 0 4 0 37 5 100][vp 8 2 0 20023 65535 0]Puede ponerme en rid胤culo[n]todo lo que quiera, pero 斡seguir姻[n]oponi姻ndome a la injusticia![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20028 65535 0]El discurso de hoy ha acabado[n]siendo muy apasionado.[n]Reconozco que no me lo esperaba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y tus gritos han sido el colof吋n.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s][f 0 8 2 1 2217]No he podido evitarlo.[clr 27][e]
[s]Solo he dicho la verdad.[e]

[msg MSG_021_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 20 5 1012]Te envidio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Decir lo que piensas con tanta[n]seguridad. Ojal茨 hubiera hecho[n]lo mismo en el pasado.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Muy prometedor, la verdad.[n][f 1 3 65535][w][e]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Pero tampoco te excedas.[n]Deber胤as evitar hacer enemistades[n]siempre que sea posible.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se te da de f茨bula hacer cumplidos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Te agradezco la ayuda.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, eso es todo por hoy.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Detractor de Yoshida]]
[s][vp 8 0 0 0 65535 0]Sois incre胤bles...[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Detractor de Yoshida]]
[s][vp 8 0 0 0 65535 0]He estado equivocado[n]todo este tiempo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Que alguien haya fracasado[n]en el pasado no significa[n]que no tenga derecho a redimirse.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Detractor de Yoshida]]
[s][vp 8 0 0 0 65535 0]斡E-eso es lo que quer胤a decir![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20018 65535 0]斡Un momento![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 2 0 20030 65535 0]斡Solo quer胤a darte las gracias![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Detractor de Yoshida]]
[s][vp 8 0 0 0 65535 0]Eres de lo m茨s peculiar,[n]como ese cr胤o.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hoy he aprendido algo[n]de tu valerosa actitud.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Yoshida]]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tengo la mala costumbre[n]de ponerme de los nervios cuando[n]alguien me llama 或in雨til Tora位.[n][f 1 3 65535][w][e]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][f 4 24 0 4 0 0 5 100][vp 8 0 0 0 65535 0]Pero t雨 me valoras,[n]as胤 me niego a bajar la cabeza[n]ante las cr胤ticas delante de ti.[n][f 1 3 65535][w][e]

[msg MSG_032_5_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 2 0 20075 65535 0]Me has ense隠ado que debo[n]confiar m茨s en mis argumentos.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo[n]con Yoshida se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mi forma de pensar cambia cuando[n]estoy contigo. Igual es por la[n]influencia de tu esp胤ritu juvenil.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uy, disculpa. No nos queda tiempo.[n][f 1 3 65535][w][e]

[msg MSG_033_5_0 [Yoshida]]
[s][vp 8 2 0 20062 65535 0]Buen trabajo.[n]Nos vemos pronto.[n][f 1 3 65535][w][e]

