[msg MSG_000_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Y, aunque la sociedad parece[n]que prospera, mucha gente[n]joven sufre en silencio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]La falta de trabajo,[n]de seguridad, de ahorros...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]La siguiente generaci吋n nos llevar茨[n]al futuro, pero no tienen[n]ni idea de c吋mo hacerlo.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Voz de hombre de mediana edad]]
[s][vp 8 0 0 4 7 0]斡Mira por d吋nde vas,[n]gilipollas![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Voz de hombre joven]]
[s][vp 8 0 0 5 6 0]斡Si te has chocado t雨[n]conmigo, vejestorio![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yoshida]]
[s][bup 0 112 4 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Esto no me gusta...[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Hay que intervenir.[e]
[s]Mejor d姻jalos estar.[e]
[s]夷Y si cambiamos de sitio?[e]

[msg MSG_005_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]S胤, cierto.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yoshida]]
[s][bup 0 112 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]La apat胤a es intolerable.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yoshida]]
[s][bup 0 112 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]No es momento de huir.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yoshida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 3 300 1][vp 8 0 0 10 65535 0]斡Conciudadanos, por favor,[n]dejen de pelear![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yoshida]]
[s][bup 0 112 2 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]夷Qu姻 sentido tiene discutir[n]por una cuesti吋n tan banal?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Hombre de mediana edad]]
[s][vp 8 0 0 13 7 0]斡A ti qu姻 m茨s te da![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Hombre joven]]
[s][vp 8 0 0 14 6 0]Eso digo yo. 斡T雨 calladito![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Hombre de mediana edad]]
[s][vp 8 0 0 16 7 0]夷A este t胤o qu姻 le pasa...?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Bien, si me lo permiten,[n]continuar姻 con el discurso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Juntos podemos brindarle un futuro[n]prometedor a la pr吋xima generaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Hombre con ropa ostentosa]]
[s][vp 8 0 0 20 65535 0]Vaya con el moralista...[n]Qu姻 asco me da ese tipo de gente.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Hombre con ropa ostentosa]]
[s][vp 8 0 0 21 65535 0]斡No vayas de listo,[n]或in雨til Tora位! [n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Yoshida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 7 300 1][vp 8 0 0 22 65535 0]斡夷Qu姻...?![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Hombre con ropa ostentosa]]
[s][vp 8 0 0 23 65535 0]斡A ti no te vota nadie[n]ni borracho![n][f 1 3 65535][w][e]
[s][vp 8 0 0 24 65535 0]夷Qu姻 vas a hacer, volver[n]a malversar fondos? 夷O mejor[n]meterte con tus votantes?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 25 65535 0]斡Eres un canalla![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yoshida]]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]斡No...! E-eso... pertenece al pasado...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Yoshida]]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Otra vez...[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]Est茨n trabando tu campa隠a.[e]
[s]夷No vas a enfadarte?[e]
[s]夷Eres un delincuente?[e]

[msg MSG_022_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]S胤, pero eso no lo puedo decir en[n]p雨blico antes de unas elecciones.[n][f 1 3 65535][w][e]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][f 4 24 0 4 0 1 5 100][vp 8 0 0 29 65535 0]De todos modos,[n]me da p茨nico que la gente[n]me llame 或in雨til Tora位.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yoshida]]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]No puedo hacer eso[n]en esta situaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]De todos modos,[n]me da p茨nico que la gente[n]me llame 或in雨til Tora位.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Muchos estar胤an de acuerdo[n]con esa afirmaci吋n.[n][f 1 3 65535][w][e]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][f 4 24 0 4 0 1 5 100][vp 8 0 0 33 65535 0]Me da p茨nico que la gente[n]me llame 或in雨til Tora位.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Hace veinte a隠os pas姻[n]por una 姻poca muy dura...[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Me explico...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Yo antes era diputado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Me eligieron durante el auge[n]de los 或Hijos de Kuramoto位. Nos[n]respaldaban diputados importantes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]De esto hace veinte a隠os,[n]m茨s o menos.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Por aquel entonces yo ten胤a muy[n]poca experiencia como pol胤tico,[n]y tambi姻n como persona.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Debido a esa falta de experiencia,[n]me vi involucrado en una serie[n]de esc茨ndalos pol胤ticos muy graves.[n][f 1 3 65535][w][e]

[msg MSG_027_5_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]La gente llam吋 a estos errores[n]或los tres avisos del in雨til Tora位.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Yoshida]]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]El primero fue que me pillaron[n]de vacaciones durante[n]una sesi吋n legislativa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Despu姻s me acusaron de malversar[n]una gran suma de dinero del[n]partido... Ese fue mi segundo aviso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]Y el 雨ltimo fue llamar 或idiota位[n]a un votante en un debate abierto,[n]lo que acab吋 en esc茨ndalo.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Estaba acabado... Me condenaron[n]al ostracismo pol胤tico.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Dec胤as que quer胤as ser diputado,[n]pero 夷ves al hombre[n]que hay ante ti?[n][f 1 3 65535][w][e]

[msg MND_029_3_0]
[s][vp 8 0 0 0 65535 0]Un pasado dudoso[n]y acusado de malversaci吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Sin embargo, tiene convicci吋n[n]y quiere cambiar el mundo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]La habilidad de hablar en p雨blico[n]puede serle 雨til a los Ladrones[n]Fantasma. Har姻 un trato con 姻l.[n][f 1 3 65535][w][e]

[msg MSG_029_5_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]夷De verdad quieres mis consejos?[n][f 1 3 65535][w][e]

[sel SEL_030_0_0 top]
[s]Me encantan tus discursos.[e]
[s]Se te ve alguien con convicci吋n.[e]
[s]No me importa tu pasado.[e]

[msg MSG_031_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Me alegra o胤r eso. Sin embargo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Nadie cree que tenga opciones,[n]as胤 que... 夷por qu姻 yo?[n][f 1 3 65535][w][e]

[sel SEL_032_0_0 top]
[s]Me gusta tu t姻cnica.[e]
[s]Conf胤a en ti mismo.[e]

[msg MSG_033_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]夷A la hora de dar discursos, dices?[n]Me temo que no soy tan bueno[n]como para que puedas aprender algo.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 51 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Lo m茨s importante[n]para dar buenos discursos[n]es creer en uno mismo.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]*risita* Se te da bien animarme...[n][f 1 3 65535][w][e]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 54 65535 0]Pero puede que tengas raz吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 55 65535 0]Lo m茨s importante[n]para dar buenos discursos[n]es creer en uno mismo.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]Quiz茨 alg雨n d胤a pueda[n]confiar en m胤 mismo...otra vez.[n][f 1 3 65535][w][e]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][vp 8 0 0 57 65535 0]Pero s胤, me has calado.[n]Eres un jovencito peculiar,[n][f 4 1].[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]Muy bien. Si lo que buscas es[n]aprender a dar grandes discursos,[n]estar姻 encantado de instruirte.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]A cambio, me gustar胤a[n]que siguieras ayud茨ndome.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]Y bien, 夷empezamos?[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]He hecho un trato con Yoshida.[n][f 1 3 65535][w][e]

[msg MSG_036_4_0 [Sae]]
[s][vp 8 0 0 800 65535 0]Todo ese teatro de enviar avisos[n]antes de los delitos... Cuesta creer[n]que un cr胤o pudiera hacerlo solo.[n][f 1 3 65535][w][e]

[msg MSG_036_5_0 [Sae]]
[s][vp 8 0 0 801 65535 0]Me da que alguien con talento[n]para mover masas con discursos[n]te ha estado instruyendo.[n][f 1 3 65535][w][e]

[msg MSG_036_6_0 [Sae]]
[s][vp 8 0 0 802 65535 0]斡夷No es verdad?![n][f 1 3 65535][w][e]

[msg MSG_036_7_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Has aceptado un nuevo[n]contrato. Excelente.[n][f 1 3 65535][w][e]

[msg MSG_036_8_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Podr茨s mejorar tus dotes[n]de conversaci吋n gracias[n]a este nuevo v胤nculo.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]Venga, a perseguir tu sue隠o[n]de ser diputado.[n][f 1 3 65535][w][e]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 62 65535 0]Vaya... S胤 que llevamos[n]rato hablando.[n]Mejor lo dejamos por hoy.[n][f 1 3 65535][w][e]

[msg MSG_037_5_0 [Yoshida]]
[s][vp 8 0 0 63 65535 0]En fin, nos vemos pronto de nuevo.[n][f 1 3 65535][w][e]

