[msg MSG_000_0_0 [Yoshida]]
[s][bup 0 112 2 0 0][f 4 10 65535 0 0][vp 8 2 0 20088 65535 0]El libre albedr胤o no implica[n]poder hacer siempre[n]lo que a uno le plazca.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tomar tus decisiones en funci吋n[n]de p姻rdidas y beneficios es actuar[n]como una m茨quina sin alma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El motivo por el que tan poca gente[n]se preocupa por el pr吋jimo es[n]porque carecen de energ胤a.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Los pol胤ticos no hemos sabido[n]cambiar la sociedad. 斡Necesitamos[n]vuestro apoyo m茨s que nunca![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Hombre trajeado]]
[s][vp 8 0 0 0 5 0]斡Ese enfoque no va a funcionar![n]斡Tienes que emocionar[n]a los votantes![n][f 1 3 65535][w][e]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 7 301 65535][vp 8 0 0 0 5 0]Vas a hacer que la gente[n]pierda toda la ilusi吋n.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, lo que quer胤a decir es que...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yoshida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 7 301 1][vp 8 2 0 20040 65535 0]斡Matsushita![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Hombre trajeado]]
[s][vp 8 0 0 0 5 0]Cu茨nto tiempo desde la 雨ltima vez[n]que hablamos. Me apetec胤a pasarme[n]a ver qu姻 tal te iba.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Veo que tienes a un joven[n]de voluntario, 夷eh?[n]Vaya, c吋mo cambian las cosas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]夷Sabes algo[n]de los Hijos de Kuramoto?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]S胤, Yoshida me ha contado algo.[e]
[s]No, y me da bastante igual.[e]

[msg MSG_007_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]De eso har茨 ya veinte a隠os.[n]Me sorprende que te interese[n]tanto la pol胤tica.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]斡Ja, ja! Bueno, al menos[n]eres sincero, chaval.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Yo tambi姻n era miembro[n]de los Hijos de Kuramoto.[n]Yoshida y yo entramos el mismo a隠o.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Supuso un cambio dr茨stico[n]en mi carrera. Pas姻 de luchador[n]profesional a diputado.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Me eligieron sin problemas,[n]pero no ten胤a ni idea[n]de qu姻 estaba haciendo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Me di cuenta de que no fue por[n]m姻ritos propios al no conseguir[n]que me reeligieran una segunda vez.[n][f 1 3 65535][w][e]

[msg MSG_010_5_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Eso nos pas吋 a los dos.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20076 65535 0]Pero t雨 has vuelto[n]por la puerta grande.[n]Eres toda una inspiraci吋n para m胤.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]T雨 tambi姻n para m胤, viejo amigo.[n]Trabajas m茨s que nadie[n]en campa隠a.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No pretendas impresionar[n]al chico con falsas alabanzas.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Yoshida conoce muy bien c吋mo[n]funciona la pol胤tica por dentro,[n]seguro que ser茨 un gran profesor.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Sin embargo, te sugiero que hagas[n]lo que dice y no lo que hace[n]si quieres llegar a diputado.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20038 65535 0]夷Y eso qu姻 significa?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]夷畏l no lo sabe...?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 3 301 65535]夷De verdad crees que puedes[n]ganar unas elecciones con total[n]sinceridad y buenos argumentos?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Tienes que afianzar los votos[n]o ser茨s 或el in雨til Tora位[n]toda la vida![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yoshida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 3 301 1][vp 8 2 0 20067 65535 0]斡Sin sinceridad y buenos argumentos[n]no puede haber justicia pol胤tica![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Je... Hace tiempo que no oigo[n]uno de tus grandiosos discursos.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0][f 4 1], 夷no?[n]Dime, 夷qu姻 te llam吋 la atenci吋n[n]de Yoshida?[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s][f 0 8 2 1 2217]Su mensaje.[clr 27][e]
[s][f 0 8 2 1 2217]Su facilidad de palabra.[clr 27][e]
[s]No estoy seguro.[e]

[msg MSG_022_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 20 5 1012][f 4 1]...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yoshida]]
[s][bup 0 112 4 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 20 5 1012][f 4 1]...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Vaya... es impresionante.[n]Puede que tengas[n]madera de diputado.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Una t茨ctica inteligente.[n]A veces, no revelar lo que piensas[n]puede ser la mejor decisi吋n.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Abordas las cosas de una manera[n]muy directa para ser tan joven.[n]Veo que te han ense隠ado bien.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20035 65535 0]Pretendo ense隠arle todo lo que s姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eso es lo que acordamos.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo[n]con Yoshida se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Por cierto, 夷c吋mo van las cosas[n]entre Kuramoto y t雨?[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Yoshida]]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][vp 8 2 0 20020 65535 0]Seguimos sin hablarnos.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Me gustar胤a que me dieras[n]tu opini吋n sobre algo,[n]as胤 que estamos en contacto.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Muy bien.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Diputado Matsushita]]
[s][vp 8 0 0 0 65535 0]Oh, ahora que me acuerdo...[n][f 1 3 65535][w][e]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 5 300 65535][vp 8 0 0 0 65535 0]Puede que desconf胤es de m胤[n]por lo que pas吋 con los fondos[n]del partido que desaparecieron.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pero que sepas que no fui yo[n]quien te se隠al吋.[n]Solo digo eso.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Yoshida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 5 300 1][vp 8 2 0 20047 65535 0]夷Por qu姻 ha tenido que mencionarlo?[n][f 1 3 65535][w][e]

[msg MSG_033_5_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, disculpa.[n]Eso es todo por hoy.[n][f 1 3 65535][w][e]

[msg MSG_033_7_0 [Yoshida]]
[s][vp 8 2 0 20054 65535 0]Buen trabajo...[n][f 1 3 65535][w][e]

