[msg MSG_000_0_0 [Yoshida]]
[s][bup 0 112 2 0 0][f 4 10 65535 0 0][vp 8 2 0 20088 65535 0]Legarles a las nuevas generaciones[n]los vicios que hemos adquirido[n]como sociedad...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡No es lo correcto![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Costar茨 solucionar este problema.[n]No obstante, 斡debemos comenzar[n]con peque隠os cambios![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 2 0 20018 65535 0]Espero que hayas sacado[n]algo 雨til del discurso de hoy.[n][f 1 3 65535][w][e]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Da igual para cu茨nta gente hables.[n]Debes transmitir tus sentimientos[n]como si hablaras cara a cara.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por cierto, la 雨ltima vez que[n]hablamos se me olvid吋 preguntarte[n]por qu姻 quer胤as ser pol胤tico.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Quiero cambiar el mundo.[e]
[s][f 0 8 2 1 2217]Quiero mejorar mi discurso.[clr 27][e]
[s]No estoy seguro...[e]

[msg MSG_003_0_0 [Yoshida]]
[s][bup 0 112 4 0 0][f 4 10 65535 0 0][vp 8 2 0 20038 65535 0]Tienes ambici吋n, desde luego,[n]si bien eso es algo ambiguo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero bueno, ya ir茨s puliendo[n]los detalles con el tiempo. [n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20075 65535 0][f 5 13 20 5 1012]Ja, ja... Veo que eres pragm茨tico.[n]Como casi todos hoy en d胤a, vaya.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero esa mentalidad[n]de querer actuar es la cualidad[n]de un buen pol胤tico.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20038 65535 0]Puede que simplemente[n]te d姻 verg鵜enza dec胤rmelo.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Puedo hacerte una pregunta m茨s?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 tipo de pol胤tico[n]te gustar胤a ser?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s][f 0 8 2 1 2217]Alguien con convicci吋n.[clr 27][e]
[s]Alguien popular.[e]
[s][f 0 8 2 1 2217]A雨n no lo s姻.[clr 27][e]

[msg MSG_008_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 20 5 1012]S胤, eso no lo olvides nunca.[n]Aunque lo importante es[n]lo que hay en el interior.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El apoyo y la popularidad importan,[n]s胤, pero esos no deben ser[n]tus principales objetivos.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 20 5 1012]Agradezco tu sinceridad.[n]Pero bueno, a雨n tienes[n]mucho tiempo para averiguarlo.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 2 0 20035 65535 0]Perm胤teme que te d姻 un consejo.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si aspiras a entrar en pol胤tica,[n]tienes que tener clara[n]tu filosof胤a.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 es lo que pretendes[n]conseguir?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 13 300 65535][vp 8 0 0 0 65535 0]Esa es la base de un gran discurso.[n]Es muy importante[n]que lo recuerdes.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s][f 0 8 2 1 2217]Gracias por la ayuda.[clr 27][e]
[s]Eso ya lo sab胤a.[e]
[s]夷Que qu姻 pretendo conseguir?[e]

[msg MSG_015_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 20 5 1012]Un placer.[n]Por cierto, mi filosof胤a es...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yoshida]]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ja, ja. Bueno,[n]no hay nada m茨s b茨sico.[n]Por cierto, mi filosof胤a es...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Conque a雨n no lo tienes claro, 夷eh?[n]Por cierto, mi filosof胤a es...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yoshida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 13 300 1][vp 8 2 0 20079 65535 0]斡Nunca te rindas hasta que consigas[n]que la gente te oiga![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Para que tu mensaje cale, debes[n]ser constante cuando le expreses[n]a la gente lo que piensas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ten un punto de vista coherente[n]y exponlo con claridad. Esa es[n]la primera regla de la negociaci吋n.[n][f 1 3 65535][w][e]
[s][bup 0 112 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 7 300 65535][vp 8 2 0 20048 65535 0]斡Ja, ja! Gracias a ti, siento el[n]mismo esp胤ritu de lucha que cuando[n]acababa de entrar en pol胤tica.[n][f 1 3 65535][w][e]

[msg MND_990_0_0]
[s][vp 8 0 0 0 65535 0]Yoshida me ha dado las claves de[n]la oratoria. Siento que mi v胤nculo[n]con 姻l se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Detractor de Yoshida]]
[s][vp 8 0 0 0 65535 0]斡Vete a tu puta casa,[n]或in雨til Tora位![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Yoshida]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 112 7 300 1][vp 8 2 0 20041 65535 0]斡In雨til Tora...![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Yoshida]]
[s][bup 0 112 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tienen raz吋n...[n]No valgo para nada...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, lo siento.[n]Se acab吋 por hoy. [n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yoshida]]
[s][vp 8 2 0 20062 65535 0]Gracias por todo tu esfuerzo.[n]Nos vemos otro d胤a.[n][f 1 3 65535][w][e]

