[msg MSG_000_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57021 65535 0]Siento haberte arrastrado[n]hasta aqu胤. Necesito unas gafas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Llevo tiempo queriendo venir,[n]pero nunca he podido pasarme.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷No ves bien?[e]
[s][f 0 8 2 1 2217]夷Quieres comprar unas?[clr 27][e]
[s]Ya tengo muchas gafas.[e]

[msg MSG_002_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Yo? Bueno, no mucho.[n]Normalmente llevo lentillas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero no es para m胤.[n]Solo quiero comprar[n]un buen regalo para mi padre.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 5 10]斡S胤! Quiero comprarle[n]un regalo a mi padre.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Menos mal que no[n]es para ti, [f 4 1].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es un regalo para mi padre.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]T雨 sabes de gafas, 夷no?[n]Pues 姻chame una mano, anda.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Te las pruebas por m胤?[n]Quiero ver c吋mo quedan puestas.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57154 65535 0]斡Muchas gracias! A ver...[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 te parecen estas?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57122 65535 0]斡Hala, qu姻 bien te quedan![n]斡Est茨s genial![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 te parece?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s][f 0 8 2 1 2217]Qu姻 modernas.[clr 27][e]
[s]No son mi estilo.[e]
[s]Qu姻 mal me quedan.[e]

[msg MSG_009_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 10 10]斡Quedan superbi姻n! Y si con ellas[n]se ve bien, mejor que mejor.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ay, 夷no te lo parece? Yo creo[n]que te quedan bastante bien...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 5 10]Ser茨 por tu aura.[n]Las gafas la disimulan,[n]pero a veces es visible.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estas podr胤an estar bien... Mmm...[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]夷Le quedar茨n bien a tu padre?[e]
[s]Yo no estoy tan seguro...[e]

[msg MSG_014_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mmm, igual son[n]demasiado modernas para mi padre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero 斡tu opini吋n me est茨 ayudando[n]mucho! 夷Te importa buscar conmigo[n]un poco m茨s?[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s][f 0 8 2 1 2217]Claro.[clr 27][e]
[s][f 0 8 2 1 2217]Sigamos.[clr 27][e]
[s]Como quieras.[e]

[msg MSG_016_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57160 65535 0][f 5 13 33 5 10]斡Gracias! 斡Qu姻 divertido![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Vamos a acelerar el ritmo![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0][f 5 13 33 5 10]斡Anda, qu姻 entusiasta! T雨 tambi姻n[n]est茨s disfrutando, 夷eh?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Pues sigamos! 斡Hora de probarse[n]gafas a toda pastilla![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57160 65535 0]Te lo agradezco mucho.[n]Vamos a por otras.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57119 65535 0]斡Hala, pareces un vendedor![n]Pero no me terminan de gustar...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57153 65535 0]斡Uy, qu姻 llamativas![n]斡La gente se va a acordar[n]de las gafas en vez de ti![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57157 65535 0]斡Pareces una estrella de Hollywood![n]Si mi padre se las pusiera,[n]tendr胤a una pinta rara.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57165 65535 0]斡夷Y estas?! A m胤 me gustan.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57166 65535 0]Perd吋n... No me decido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hay muchas bonitas, pero ninguna[n]me ha llamado especialmente[n]la atenci吋n.[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]Conf胤a en tu instinto.[e]
[s]No te lo pienses tanto.[e]

[msg MSG_025_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Tienes raz吋n! Esto[n]tengo que decidirlo yo.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Coger姻 estas porque tengo[n]un buen presentimiento.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No s姻 c吋mo explicarlo, pero[n]parecen perfectas para mi padre.[n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s][f 0 8 2 1 2217]Buena elecci吋n.[clr 27][e]
[s]Seguro que le encantan.[e]

[msg MSG_028_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57137 65535 0][f 5 13 33 5 10]S胤, me quedo con estas.[n]斡Seguro que le gustan![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57137 65535 0]斡Eso es! Me lo dice el instinto.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57169 8 0]斡Muchas gracias[n]por acompa隠arme hoy![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Al final me he llevado un regalo[n]estupendo. 斡Y todo gracias a ti,[n][f 4 1]![n][f 1 3 65535][w][e]

[sel SEL_031_0_0 top]
[s]Es parte del trato.[e]
[s]No hay de qu姻.[e]
[s]Espero que me compenses.[e]

[msg MSG_032_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Har姻 que haya valido la pena.[n]斡Vamos a entrenar al Parque[n]Inokashira despu姻s![n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Ji, ji... A雨n tengo que compensarte.[n]斡Vamos a entrenar al Parque[n]Inokashira despu姻s![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 8 0]斡Claro! Es parte del trato, 夷no?[n]斡Vamos a entrenar al Parque[n]Inokashira despu姻s![n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 57036 8 0]Si te soy sincera, elegir[n]unas gafas me produc胤a ansiedad.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Me preocupaba qu姻 pasar胤a[n]si no me decid胤a o si eleg胤a mal...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Soy un fracaso como atleta[n]y la cocina tampoco se me da bien.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Como he cedido tantas veces[n]ante la presi吋n,[n]pienso que la voy a cagar en todo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Cuantas m茨s vueltas le doy,[n]m茨s vac胤a estoy.[n]Me siento fuera de lugar.[n][f 1 3 65535][w][e]

[sel SEL_037_0_0 top]
[s][f 0 8 2 1 2217]Todo el mundo pasa por eso.[clr 27][e]
[s]Eso es que est茨s de baj吋n.[e]

[msg MSG_038_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 8 0][f 5 13 33 5 10]Ah, t雨 me entiendes, [f 4 1].[n]No solo es cosa m胤a...[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Vale, s胤, pero...[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57021 8 0]Creo que empiezo a entender[n]lo que me dijo la entrenadora.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Decir que se est茨 pasando[n]una mala racha y rendirse es f茨cil.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Quiz茨 encontrarme a m胤 misma[n]me sirva para conocerme mejor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Me siento un poco mal,[n]pero creo que estoy recuperando[n]la confianza en m胤 misma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Y que me apoyes me ayuda[n]a estar m茨s decidida[n]para esforzarme y cumplirlo.[n][f 1 3 65535][w][e]

[sel SEL_041_0_0 top]
[s]Buena suerte.[e]
[s][f 0 8 2 1 2217]Lo haremos juntos.[clr 27][e]
[s]Sin prisa.[e]

[msg MSG_042_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57076 8 0]斡Muchas gracias![n]Eso me da confianza.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Kasumi]]
[s][bup 0 10 6 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 8 0][f 5 13 33 5 10]Qu姻 raro... No s姻[n]si deber胤a sentirme as胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Quiero dar lo mejor de m胤, pero es[n]como si lo hiciera por los dos...[n]斡o algo as胤![n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57186 8 0]Ya. La entrenadora me dijo[n]que me tomara las cosas con calma.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 8 0]Sigo trabajando en m胤 misma, pero[n]espero que sigamos ayud茨ndonos.[n][f 1 3 65535][w][e]

[msg MND_046_0_0]
[s][vp 8 0 0 0 65535 0]Siento que Kasumi[n]tiene mucha confianza.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 8 0]斡Ahora vamos a entrenar![n]Hoy podr胤amos hacer[n]ejercicios de nivel intermedio.[n][f 1 3 65535][w][e]

[msg MND_048_0_0]
[s][vp 8 0 0 0 65535 0]Despu姻s de estirar,[n]he entrenado con Kasumi.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Kasumi]]
[s][vp 8 0 0 0 65535 0]Lo dejamos aqu胤. 斡Buen trabajo![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Kasumi]]
[s][vp 8 2 0 57070 65535 0]Deber胤a irme. 斡Me pondr姻[n]en contacto contigo pronto![n][f 1 3 65535][w][e]

