[msg MSG_000_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57021 65535 0]Siento haberte llamado[n]tan de repente. [n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Desde que hablamos, he intentado[n]pensar en algo que no sea[n]gimnasia y que me interese.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y 斡me he dado cuenta de una cosa![n]斡Mira esto![n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]夷Te interesa la cocina?[clr 27][e]
[s]夷Te gustan los p胤cnics?[e]
[s]夷Y eso es...?[e]

[msg MSG_002_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0][f 5 13 33 10 10]斡S胤, s姻 cocinar![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57030 65535 0]Eso parece divertido,[n]pero 斡me refer胤a a cocinar![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57143 65535 0]Lo tienes justo delante.[n]斡S姻 cocinar![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En gimnasia, hay que controlar[n]la dieta, as胤 que yo misma[n]preparo mucho de lo que como.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Pues eso! Como quer胤a darte[n]las gracias, te he cocinado algo.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57073 65535 0]Es la primera vez que cocino para[n]alguien que no es de mi familia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As胤 recuperar姻 la confianza[n]en m胤 misma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo he hecho teniendo en cuenta[n]tu metabolismo y el ejercicio[n]que haces. 夷Lo quieres?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s][f 0 8 2 1 2217]斡Qu姻 emoci吋n![clr 27][e]
[s][f 0 8 2 1 2217]Qu姻 buena pinta.[clr 27][e]
[s]A ver si est茨 bueno...[e]

[msg MSG_008_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0][f 5 13 33 5 10]Me alegra haberle puesto[n]tanto cari隠o.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0][f 5 13 33 5 10]斡Y es todo tuyo![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57173 65535 0]A ver, es cierto que no es[n]un plato de lujo. Ay, me estoy[n]poniendo nerviosa.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El pollo y los huevos son[n]para el cansancio. Tambi姻n hay[n]alubias y arroz integral.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Controlar el peso es importante[n]para una deportista, pero tambi姻n[n]se necesita energ胤a y aguante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Solemos tomar muchas[n]prote胤nas y poca grasa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y necesitamos hierro para[n]tener aguante y vitamina B[n]para tener energ胤a.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espera... Estoy centr茨ndome de nuevo[n]en la gimnasia.[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 5 6 36 6 100][f 4 24 0 5 6 9 6 100]En fin...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57099 65535 0]斡Al ataque![n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s][f 0 8 2 1 2217]夷Todo eso es para ti?[clr 27][e]
[s]Parece demasiado.[e]
[s]夷Qu姻 es eso?[e]

[msg MSG_015_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 10 10]斡Claro! Necesito hasta[n]el 雨ltimo grano de arroz.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 5 10]Hoy tengo entrenamiento, as胤 que es[n]la cantidad ideal para m胤.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Eh? Es mi comida.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷A qu姻 viene tanto escepticismo,[n][f 4 1]?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Parece lioso,[n]pero no es para tanto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No te preocupes, he calculado[n]las calor胤as. Las quemar姻[n]todas entrenando.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57187 65535 0]斡威nimo! 斡Acabar茨s antes[n]de que te des cuenta![n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]斡Este es...[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]El sabor me suena,[n]pero no le pega a la comida...[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]Sigo probando otras partes,[n]pero sabe todo el rato igual.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Me suena.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57033 65535 0]夷[f 4 1]? 夷Est茨s bien?[n]Tienes los ojos llorosos.[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]Sabe a...[e]
[s][f 0 8 2 1 2217]Es especial, sin duda.[clr 27][e]
[s]Est茨... geniaaaaal...[e]

[msg MSG_025_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pensaba que eso llamar胤a[n]tu atenci吋n. 斡Es la mejor parte![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pens姻 que no te gustar胤a con mucho[n]sabor, as胤 que no le he puesto[n]muchas especias.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 33 5 10]夷T雨 crees? No es tan raro[n]para una atleta.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No hay que colarse[n]con las especias,[n]as胤 que he puesto las justas.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡夷Por qu姻 suenas como un robot?![n][f 1 3 65535][w][e]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 5 6 38 6 100]夷Le falta sabor?[n]Pens姻 que no te sentar胤a muy bien[n]si echaba muchas especias.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mmm. 夷No ten胤a sabor? Perdona...[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Mmm! S胤, es el sabor que estaba[n]buscando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]N-no sab胤a muy bien qu姻[n]especias usar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡A todo el mundo le gusta el curry![n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡As胤 que apost姻 por que supieran[n]a tope a curry![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mm, lo siento... 夷No te gusta[n]mucho el sabor?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Prefieres la comida muy picante?[n][f 1 3 65535][w][e]

[sel SEL_031_0_0 top]
[s]No exactamente.[e]
[s]夷Hay una tercera opci吋n?[e]

[msg MSG_032_0_0 [Kasumi]]
[s][bup 0 10 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 57042 65535 0]斡Lo siento! Me ha salido todo mal.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A ver si consigo alg雨n condimento[n]que cambie el sabor.[n]斡Ver茨s como te gusta![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Deber胤a coger mayonesa o salsa[n]de soja? 夷O mejor miso? 夷Crees[n]que el doctor Maruki tendr茨 sal?[n][f 1 3 65535][w][e]

[sel SEL_033_0_0 top]
[s]C茨lmate.[e]
[s]夷Vas a ir ahora?[e]

[msg MSG_034_0_0 [Kasumi]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57064 65535 0]斡Ah, tienes toda la raz吋n![n]斡Deber胤a comprar algo que[n]puedas comerte ahora mismo![n][f 1 3 65535][w][e]

[sel SEL_035_0_0 top]
[s]Est茨 bien as胤.[e]
[s]Me est茨 gustando.[e]
[s]Vamos a comer.[e]

[msg MSG_036_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esto, pero...[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Gracias! Pues a comer.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57100 65535 0]Uf, estaba delicioso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gracias por acabarte la comida,[n][f 4 1].[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Siento que no haya salido perfecto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se me ocurri吋 prepararte esto,[n]pero no me decid胤a con el sabor.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En definitiva, 斡que lo siento![n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Qu姻 verg鵜enza. Pensaba[n]que estaba perfecto cuando[n]te lo he dado, pero ahora...[n][f 1 3 65535][w][e]

[sel SEL_042_0_0 top]
[s][f 0 8 2 1 2217]Puedes intentarlo otra vez.[clr 27][e]
[s]Cosas que pasan.[e]
[s]No te rindas.[e]

[msg MSG_043_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57077 65535 0][f 5 13 33 15 10]Eres muy amable, [f 4 1].[n][f 1 3 65535][w][e]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 5 6 42 6 100]La pr吋xima vez te preguntar姻[n]qu姻 te gusta antes de cocinar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La pr吋xima vez comprar姻[n]la salsa Megido, que pica mucho.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57039 65535 0][f 5 13 33 10 10]Ya, supongo... Gracias.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La pr吋xima vez te preguntar姻[n]qu姻 te gusta antes de cocinar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La pr吋xima vez comprar姻[n]la salsa Megido, que pica mucho.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57026 65535 0][f 5 13 33 10 10]斡Es verdad! 斡Cuando fallas,[n]debes levantarte de nuevo![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La pr吋xima vez te preguntar姻[n]qu姻 te gusta antes de cocinar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La pr吋xima vez comprar姻[n]la salsa Megido, que pica mucho.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0]Je, je. Siempre me ayudas[n]a salir adelante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si no te tuviera, habr胤a dejado[n]que mis errores me afectaran[n]y reca胤do en la depresi吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A lo mejor esta confianza[n]me ayuda a descubrir qui姻n soy.[n][f 1 3 65535][w][e]

[sel SEL_047_0_0 top]
[s]Suena bien.[e]
[s]Quiz茨s...[e]

[msg MSG_048_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En cualquier caso, lo 雨nico[n]que puedo hacer es avanzar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 1], espero que[n]sigamos ayud茨ndonos a mejorar.[n][f 1 3 65535][w][e]

[msg MND_049_0_0]
[s][vp 8 0 0 0 65535 0]Siento la pasi吋n de Kasumi.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vale, ahora que hemos obtenido[n]todos los nutrientes necesarios,[n]斡pasemos a la siguiente fase![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No quiero pasarme de la raya,[n]pero vas a entrenar mucho m茨s[n]que antes. 斡No bajes el ritmo![n][f 1 3 65535][w][e]

[msg MND_051_0_0]
[s][vp 8 0 0 0 65535 0]Fuimos al gimnasio y entrenamos.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Kasumi]]
[s][vp 8 0 0 0 65535 0]Uy... Ya no queda tiempo.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Kasumi]]
[s][vp 8 2 0 57080 65535 0]Aqu胤 lo dejamos por hoy.[n]斡Espero que repitamos otro d胤a![n][f 1 3 65535][w][e]

