[msg MSG_000_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57142 65535 0]Mmm. [f 4 2]...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Lo siento much胤simo![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Verme actuar como si fuera Kasumi[n]habr茨 sido muy doloroso[n]y extra隠o para todos.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seguro que todos se han dado cuenta[n]de que estaba actuando[n]de forma extra隠a...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seguro que solo estaban siendo[n]amables sabiendo que acababa[n]de perder a mi hermana...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero... no ten胤a ni idea de que[n]deb胤a estar triste. Ni siquiera[n]recordaba que ella ya no estaba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La entrenadora me dijo que[n]reflexionara sobre qui姻n soy, pero[n]cre胤a que era una forma de hablar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Estaba a mi rollo, como si no me[n]importase que ella se hubiera ido![n]Qu姻 verg鵜enza...[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Fue sin querer.[e]
[s]夷Qu姻 pod胤as hacer?[e]
[s]Al menos ahora te has dado cuenta.[e]

[msg MSG_005_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57189 65535 0]Bueno, s胤... Pero aun as胤,[n]夷c吋mo voy a perdonarme?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57040 65535 0]Te agradezco tus palabras, pero...[n]no puedo perdonarme.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57180 65535 0]S胤... Tengo que pensar[n]en mis errores.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cuando 姻ramos peque隠as, Kasumi[n]decid胤a qu姻 hacer y ad吋nde ir.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No pod胤a hacer nada sin ella...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es evidente por qu姻 mis notas[n]no mejoraban. Para empezar,[n]nunca estuve a su altura.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Era tan pretenciosa que acab姻[n]ahog茨ndome en mis bobadas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Era demasiado egoc姻ntrica[n]como para hacer nada![n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]No te atormentes.[e]
[s]夷Qu姻 vas a hacer ahora?[e]
[s]Tranquil胤zate.[e]

[msg MSG_010_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo siento. He perdido los papeles.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 57075 65535 0]Estoy empezando a recordar cosas[n]del pasado. Es dif胤cil,[n]pero lo intento.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tengo para parar un tren: desde[n]cuando Kasumi y yo 胤bamos a clase[n]de gimnasia hasta hace nada.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quiero hablar de la relaci吋n[n]que ten胤a con Kasumi.[n]夷Me vas a escuchar?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57037 65535 0]Empez吋 a ir a clases de gimnasia[n]cuando era muy peque. Yo la imitaba[n]en todo, as胤 que me apunt姻 tambi姻n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Era demasiado peque隠a[n]para comprender[n]el deporte y las reglas.[n][f 1 3 65535][w][e]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 59 5 100][vp 8 0 0 0 65535 0]Pero me dec胤an que se me daba[n]bien y la entrenadora me premiaba[n]con helados y chuches.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nos esforz茨bamos en aprender las[n]rutinas y los movimientos[n]porque nos invitaba a un helado.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]Veo que estabais muy unidas.[e]
[s]Qu姻 recuerdos tan bonitos.[e]
[s]Conque todo era por el helado, 夷eh?[e]

[msg MSG_015_0_0 [Sumire]]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0]S胤. Est茨bamos juntas a diario.[n][f 1 3 65535][w][e]
[s][bup 0 10 901 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 5 100][vp 8 0 0 0 65535 0]Devor茨bamos juntas los helados,[n]charl茨bamos, nos re胤amos...[n]Qu姻 bien me lo pasaba.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Sumire]]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0]Ja, ja. Supongo que tienes raz吋n.[n][f 1 3 65535][w][e]
[s][bup 0 10 901 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 5 100][vp 8 0 0 0 65535 0]Devor茨bamos juntas los helados,[n]charl茨bamos, nos re胤amos...[n]Qu姻 bien me lo pasaba.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Sumire]]
[s][bup 0 10 901 65535 0][f 4 10 65535 0 0][vp 8 2 0 57186 65535 0]斡Ja, ja! Supongo, pero claramente[n]funcion吋, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nos esforz茨bamos mucho para[n]ganarnos los helados. Charl茨bamos,[n]nos re胤amos... Qu姻 tiempos.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Sumire]]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Un d胤a, cuando empezamos a ir[n]a las competiciones,[n]Kasumi me pregunt吋...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]或Si me convierto en la n雨mero uno[n]del mundo, 夷nos dar茨n[n]todo el helado que queramos?位.[n][f 1 3 65535][w][e]
[s][bup 0 10 901 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 5 100][vp 8 0 0 0 65535 0]Toda seriota, ella.[n]A veces era muy graciosa.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Sumire]]
[s][bup 0 10 901 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0]Y, claro, yo le dije:[n]或斡Kasumi, eres un genio!位.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]T雨 s胤 que eres un genio.[e]
[s]夷Cu茨ntos a隠os dices que ten胤a?[e]

[msg MSG_021_0_0 [Sumire]]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ella s胤 que era un aut姻ntico genio.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Sumire]]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, 姻ramos unas cr胤as, pero[n]te juro que ella era alucinante.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Sumire]]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo hac胤a todo con una facilidad[n]pasmosa. Cada d胤a era mejor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Recuerdas lo que dijo mi[n]entrenadora? Que el punto fuerte[n]de Kasumi era su valent胤a.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Kasumi era siempre muy valiente.[n]Todo un ejemplo de confianza.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57188 65535 0]Luego me di cuenta de que, por mucho que[n]me esforzase, nunca estar胤a a su altura.[n]Ser胤a siempre la eterna segundona.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Kasumi era la que siempre[n]se sub胤a al podio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero, aunque ella ganase un helado,[n]nunca se lo com胤a sin m胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Le dec胤a que daba igual, pero[n]insist胤a en que esperar胤a[n]a que nos lo comi姻ramos juntas.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cre胤a en m胤 de coraz吋n y repet胤a[n]que alg雨n d胤a ser胤amos las mejores.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ten胤a sus propios entrenamientos,[n]pero aun as胤 siempre se pasaba[n]horas ayud茨ndome.[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s]Se preocupaba por ti.[e]
[s]Qu姻 entrenamiento tan duro.[e]
[s]Todo por el helado, 夷eh?[e]

[msg MSG_027_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Era tan amable y tan fuerte...[n]La hermana mayor perfecta.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me gustaba entrenar.[n]No me importaba.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Sumire]]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ja, ja, ja... S胤, en los viejos tiempos, aquello[n]era todo a lo que aspir茨bamos.[n][f 1 3 65535][w][e]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 0 0 0 65535 0]Era divertido. No s姻[n]cu茨ndo cambi吋 eso.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 57184 65535 0]La gentileza de Kasumi[n]era tan... tan...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]exasperante.[n][f 1 3 65535][w][e]

[sel SEL_032_0_0 top]
[s]夷Por qu姻?[e]
[s]Me lo imagino.[e]

[msg MSG_033_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Siempre era ella la que estaba en[n]el podio acaparando los flashes,[n]y yo, observ茨ndola en las sombras.[n][f 1 3 65535][w][e]
[s][bup 0 10 905 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 6 44 5 100]斡No soy Kasumi... y haga lo que haga,[n]nunca ser姻 como ella![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Sumire]]
[s][bup 0 10 902 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si hubiera tirado la toalla conmigo,[n]no habr胤a dolido tant胤simo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Al menos as胤 la gente[n]habr胤a dejado de compararnos...[n][f 1 3 65535][w][e]

[sel SEL_035_0_0 top]
[s]Debe de haber sido dif胤cil.[e]
[s]夷Y los sentimientos de Kasumi?[e]
[s]Suena a huida.[e]

[msg MSG_036_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57027 65535 0]S胤, es una forma de verlo.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57180 65535 0]Tienes raz吋n. Supongo[n]que fui una ego胤sta.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57027 65535 0]Si lo prefieres. S胤, quer胤a huir.[n]Solo pensaba en m胤 misma.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eso era lo que pensaba[n]todos los d胤as, una y otra vez...[n]Que la gente estar胤a mejor sin m胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]O que ojal茨 fuese Kasumi,[n]ya que la prefer胤an a ella.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sumire no vale la pena.[n]夷Qu姻 m茨s da si se muere?[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero fue mi hermana la que muri吋.[n][f 1 3 65535][w][e]
[s][bup 0 10 905 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 44 5 100][vp 8 2 0 57185 65535 0]夷Por qu姻 protegi吋 a una in雨til[n]como yo? Yo... Yo la vi...[n][f 1 3 65535][w][e]

[sel SEL_041_0_0 top]
[s]Ac姻ptalo ya.[e]
[s]No le des m茨s vueltas.[e]
[s]夷Qu姻 vas a hacer ahora?[e]

[msg MSG_042_0_0 [Sumire]]
[s][bup 0 10 902 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤. Estoy harta de huir.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Sumire]]
[s][bup 0 10 902 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡No puedo seguir as胤! Me promet胤[n]que no me esconder胤a.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 2 0 57023 65535 0][f 4 2]... No puedo detenerme. [n][f 1 3 65535][w][e]
[s][bup 0 10 902 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 37 5 100][vp 8 0 0 0 65535 0]Quiero seguir haciendo[n]gimnasia como Sumire.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quiero llegar muy alto,[n]como quer胤a Kasumi.[n][f 1 3 65535][w][e]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 0 0 0 65535 0]Si no... nunca[n]podr姻 mirarla a la cara.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Sumire]]
[s][bup 0 10 902 65535 0][f 4 10 65535 0 0][vp 8 2 0 57136 65535 0]夷Seguir茨s saliendo conmigo[n]ahora que soy Sumire?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Obl胤game a ir de frente.[n]No me permitas huir[n]de m胤 misma otra vez.[n][f 1 3 65535][w][e]

[sel SEL_046_0_0 top]
[s]S胤.[e]
[s]Me las apa隠ar姻.[e]
[s]Forma parte del trato.[e]

[msg MSG_047_0_0 [Sumire]]
[s][bup 0 10 904 65535 0][f 4 10 65535 0 0][vp 8 2 0 57039 65535 0]夷D-de verdad? Muchas gracias...[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Sumire]]
[s][bup 0 10 904 65535 0][f 4 10 65535 0 0][vp 8 2 0 57039 65535 0]G-gracias. Te tomo la palabra.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Sumire]]
[s][bup 0 10 904 65535 0][f 4 10 65535 0 0][vp 8 2 0 57039 65535 0]G-gracias... No te arrepentir茨s.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Sumire]]
[s][bup 0 10 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Je, je... Pensar茨s que doy pena...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero... supongo que as胤 es Sumire.[n]Esa soy yo.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Sumire]]
[s][bup 0 10 902 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tengo que ser m茨s fuerte.[n]De coraz吋n y haciendo gimnasia.[n][f 1 3 65535][w][e]

[msg MSG_051_5_0 [Sumire]]
[s][bup 0 10 902 65535 0][f 4 10 65535 0 0][vp 8 2 0 57080 65535 0]Pero por ahora... soy Sumire[n]Yoshizawa. Encantada de nuevo.[n][f 1 3 65535][w][e]

[msg MND_052_0_0]
[s][vp 8 0 0 0 65535 0]Siento que Sumire[n]tiene una confianza enorme.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Sumire]]
[s][bup 0 10 900 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uf... Qu姻 bien me ha sentado[n]soltarlo todo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me ha servido de gran ayuda.[n]Empezar姻 de cero[n]y lo har姻 lo mejor posible.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Sumire]]
[s][bup 0 10 901 65535 0][f 4 10 65535 0 0][vp 8 2 0 57067 65535 0]Vamos a entrenar hasta que tenga[n]que irme al club.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Entrenaremos m茨s que antes[n]y ser姻 mucho m茨s estricta.[n][f 1 3 65535][w][e]

[msg MND_055_0_0]
[s][vp 8 0 0 0 65535 0]Tuve una larga sesi吋n[n]de entrenamiento con Sumire.[n][f 1 3 65535][w][e]

