[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Hoy he aprendido algo nuevo[n]sobre ti.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Como aliados que luchan en el mismo bando,[n]nadie podr胤a dudar de tu fuerza.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Te lo digo de verdad. Si estuviera en[n]peligro, confiar胤a en ti con los ojos cerrados.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Lo mismo digo.[e]
[s]El sentimiento es mutuo.[e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]斡No me digas! Eso me agradar胤a[n]sobremanera.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Ja, ja, tienes nervios de acero.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Lamento haberte pedido que me complacieras,[n]pero ahora me siento algo mejor.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo[n]con Akechi se est茨 fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Por cierto, una cosa... Si hubi姻ramos[n]luchado hasta el final, 夷crees[n]que habr胤as ganado?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s][f 0 8 2 1 2217]Seguro que no perder胤a.[clr 27][e]
[s]No lo s姻.[e]
[s]Probablemente.[e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 5 13 9 10 9][vp 8 0 0 8 65535 0]Sab胤a que dir胤as eso.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 5 13 9 5 9][vp 8 0 0 9 65535 0]As胤 que habr胤a cabido la posibilidad...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Ya veo. Se te ve bastante seguro.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Te voy a decir algo con el coraz吋n[n]en la mano. Te odio.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Tu habilidad para gestionar tus circunstancias,[n]tu genialidad, tu capacidad[n]de superarme... Me quema la sangre.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Akechi]]
[s][bup 0 9 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Eres la 雨nica persona ante la que me niego a perder.[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]Lo mismo digo.[e]
[s][f 0 8 2 1 2217]Detesto perder, 夷y t雨?[clr 27][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][f 5 13 9 5 9][vp 8 0 0 14 65535 0]Desde luego, eres... No, da igual.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][f 5 13 9 10 9][vp 8 0 0 15 65535 0]Que no te quepa duda. Ni siquiera[n]hab胤a reparado en lo grave del asunto.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Hoy te concedo esta victoria, pero[n]la pr吋xima vez ser茨 m胤a.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Esto servir茨 de prueba.[n][f 1 3 65535][w][e]

[msg MND_019_0_0]
[s][vp 8 0 0 0 65535 0]Es uno de los guantes[n]que Akechi suele llevar.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]夷Qu姻 demuestra este guante?[e]
[s]夷A qu姻 te refieres con 或prueba位?[e]

[msg MSG_021_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]En Occidente existe la tradici吋n de lanzarle[n]un guante a tu adversario cuando[n]quieres retarlo a un duelo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Si este acepta el guante,[n]el duelo queda fijado.[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s]Acepto.[f 2 7 0 1 2221 1][e]
[s]Deja que me lo piense.[e]

[msg MSG_023_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]No lo olvides,[n]yo soy el que te va a derrotar.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Vaya, mira qu姻 hora es. Ya est茨 bien[n]por hoy.[n][f 1 3 65535][w][e]

