[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8018 65535 0]El billar es un juego fascinante,[n]夷no crees?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No basta con apuntar a la bola.[n]Para embocarla, tienes que ser[n]preciso pero indirecto.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]S胤, es muy enrevesado...[e]
[s][f 0 8 2 1 2217]Por eso es tan divertido.[clr 27][e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 5 13 9 5 9][vp 8 0 0 0 65535 0]Entiendo lo que quieres decir,[n]pero comparte similitudes con[n]un hipot姻tico 或crimen perfecto位.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 5 13 9 10 9][vp 8 0 0 0 65535 0]Exacto. Y lo m茨s interesante es que[n]comparte muchos paralelismos con[n]un te吋rico 或crimen perfecto位.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54404 65535 0]Eliminas al objetivo sin[n]relacionarte directamente con 姻l.[n]夷Te suena?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Los episodios de descontrol.[e]
[s]夷Ad吋nde quieres llegar?[e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As胤 es. Hasta los casos de[n]criminales a los que despertaron.[n][f 1 3 65535][w][e]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][vp 8 0 0 0 65535 0]Todo lo que nos pasa, hasta los[n]sucesos sin importancia, podr胤an[n]ser bolas chocando entre ellas.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No es tan complicado. Hablo[n]de los episodios de descontrol...[n]y del despertar de los criminales.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 36 5 100][vp 8 0 0 0 65535 0]Todo lo que nos pasa, hasta los[n]sucesos sin importancia, podr胤an[n]ser bolas chocando entre ellas.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Pero no hay forma de saber[n]con certeza que la bola se puede[n]controlar con precisi吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La intenci吋n del jugador puede ser[n]buena, pero la bola puede chocar[n]contra obst茨culos inesperados.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y ahora que sabes esto... 夷Quieres[n]seguir adelante con el juego?[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]He tomado una decisi吋n.[e]
[s]No perder姻 mi oportunidad.[e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54460 65535 0]Incre胤ble. Has ganado.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8156 65535 0]Qu姻 partida m茨s re隠ida. 夷Quieres[n]salir a que nos d姻 el aire un rato?[n][f 1 3 65535][w][e]

