[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*bostezo* Qu姻 aburrimiento.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Profesor Ushimaru]]
[s][bup 0 301 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Oye, [f 4 1]![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Oye! 斡Presta atenci吋n![n]斡夷As胤 escuchas t雨 a los dem茨s[n]cuando te hablan?![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Alumna]]
[s][vp 8 0 0 0 65535 0]斡Hala! 斡Qu姻 finta m茨s 姻pica![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Alumno]]
[s][vp 8 0 0 0 65535 0]Qu姻 locura... 夷Es un ninja o qu姻?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Profesor Ushimaru]]
[s][bup 0 301 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As胤 que estabas despierto...[n]No lo parec胤a.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Bueno, sigamos.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1183 65535 0]斡Menuda finta![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Alumna]]
[s][vp 8 0 0 0 65535 0]Buah, eso tiene pinta de doler.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Alumno]]
[s][vp 8 0 0 0 65535 0]*risa* Le ha dado[n]en toda la frente.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Profesor Ushimaru]]
[s][bup 0 301 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eso te pasa[n]por dar cabezadas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Los j吋venes de hoy en d胤a[n]no respet茨is a los mayores.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1046 65535 0]Hala, t胤o, la has cagado.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Alumna]]
[s][vp 8 0 0 0 65535 0]斡No puede ser! 斡夷Lo ha ignorado?![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Alumno]]
[s][vp 8 0 0 0 65535 0]斡Madre m胤a! 斡Qu姻 malote![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Profesor Ushimaru]]
[s][bup 0 301 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Chsss... Bueno, venga. Sigamos.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1163 65535 0]Me gusta el aura que te envuelve.[n]Es como si nada pudiera alcanzarte.[n][f 1 3 65535][w][e]

