[msg MSG_000_0_0 [Lala Escargot]]
[s][vp 8 0 0 0 65535 0]夷Buscas un lugar t胤pico[n]de Shinjuku?[n]Pues ojal茨 pudiera ayudarte.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Es que los sitios m茨s interesantes[n]no son adecuados[n]para unos chiquillos.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Lo siento, chicos.[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7188 65535 0]Me parece un lugar bastante chulo.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤. No s姻 por qu姻, pero[n]curiosamente me relaja.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ex吋tico y elegante... Un lugar[n]tan incre胤ble como su due隠a.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oye, [f 4 2],[n]夷de qu姻 conoces a esta se隠ora?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Un colega de un colega.[e]
[s][f 0 8 2 1 2217]Trabajo para ella.[clr 27][e]
[s]No lo s姻.[e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 8 5 2]Tienes amigos en todas partes, t胤o.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 5 5 5]Es maravilloso tener amigos[n]de todo tipo. Ojal茨 yo consiga[n]tener la mente tan abierta.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 4 5 7]Yo igual.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7086 65535 0][f 5 13 8 10 2]夷T雨 trabajas aqu胤?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 5 10 5]Qu姻 dedicaci吋n. Es admirable.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 5 13 4 10 7]斡As胤 que trabajas en un bar![n]Habr茨s aprendido a relacionarte[n]con los adultos, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷C吋mo que no lo sabes?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 2]...[n]夷De verdad no puedes contarlo?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, vale. No insistiremos.[n]Todo el mundo tiene secretos.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Lala Escargot]]
[s][vp 8 0 0 0 65535 0]Sois un soplo de aire fresco,[n]como una brisa... Con esos ojos[n]tan brillantes y llenos de energ胤a.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Adoro a mis clientes, pero est茨n[n]hartos de todo. Esto es un[n]cambio en mi rutina.[n][f 1 3 65535][w][e]

[msg MSG_014_5_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero si viene mucha gente,[n]ser茨 un sitio seguro,[n]un lugar para descansar.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Lala Escargot]]
[s][vp 8 0 0 0 65535 0]斡Ay, cielo! Eres un amor.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]No puedo pedir m茨s. Quiero que la[n]gente venga aqu胤 a relajarse,[n]sobre todo si lo necesitan.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4088 65535 0]Qu姻 amable. Eres como una gran[n]madre que cuida de Shinjuku.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤. Este bar y Lala...[n]As胤 deber胤a ser todo Shinjuku.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Cliente habitual borracho]]
[s][vp 8 0 0 0 65535 0]斡Lalaaaaa! *hip* 斡Otra copa![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Lala Escargot]]
[s][vp 8 0 0 0 65535 0]Oye, 斡no hemos abierto todav胤a![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Cliente habitual borracho]]
[s][vp 8 0 0 0 65535 0]Pero... *hip* Las luces estaban[n]encendidas... 夷Puedo tomarme...?[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Lala Escargot]]
[s][vp 8 0 0 0 65535 0]斡Oye, a vomitar al ba隠o![n]斡Como potes en el mostrador[n]no vuelves a entrar aqu胤 jam茨s![n][f 1 3 65535][w][e]

[msg MSG_021_5_0 [Cliente habitual borracho]]
[s][vp 8 0 0 0 65535 0]S-s胤, se隠ora.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Lala Escargot]]
[s][vp 8 0 0 0 65535 0]斡Madre m胤a! 夷Tan pronto y ya est茨s[n]como una cuba? Vaya tela...[n][f 1 3 65535][w][e]

[msg MSG_022_5_0 [Lala Escargot]]
[s][vp 8 0 0 0 65535 0]Cuanto m茨s tarde se hace,[n]m茨s capullos aparecen.[n]Deber胤ais iros a casa pronto.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S-s胤, se隠ora.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53515 65535 0]Gracias por el zumo.[n]Venga, v茨monos...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Parece que incluso la gran madre[n]de Shinjuku tiene que poner firme[n]a su prole.[n][f 1 3 65535][w][e]

