[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah... Esto es el para胤so...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A los gatos les gusta mucho[n]la naturaleza, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Eso no tiene nada que ver! Es que[n]es agradable ser libre. Siempre[n]estoy encerrado en esa mochila.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Adem茨s, la ciudad huele fatal.[n]Hac胤a mucho que no ol胤a[n]un aire tan fresco.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Creo que lo entiendo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El parque tiene un aire[n]tirando a h雨medo, 夷no?[n]A m胤 me calma olerlo.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero la ciudad est茨 llena[n]de luces y movimiento.[n]Para m胤, es irresistible.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷T雨 crees? 夷Y a ti qu姻 te gusta,[n][f 4 2]?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]El glamour de la ciudad.[e]
[s]La tranquilidad de la naturaleza.[e]
[s]Las dos cosas tienen su encanto.[e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡夷Verdad?![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Verdad?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, es cierto. Has vivido tanto en[n]el centro como en las afueras, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Quiero ir de viaje! A alg雨n sitio[n]como un balneario, o a la playa.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]De viaje, 夷eh? Yo nunca[n]he salido de la isla...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]En realidad, creo que ni he salido[n]de la regi吋n de Kanto.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, el viaje escolar[n]va a ser al extranjero.[n]夷Ya te has sacado el pasaporte?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No... El papeleo de la oficina[n]gubernamental es un rollazo.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, 夷qu姻 hacemos con Morgana?[n]Tendr茨s que quedarte solo en casa[n]de [f 4 2], 夷no?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][vp 8 0 0 0 65535 0]Zzz...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Est茨... disfrutando del sol...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ja, ja, 斡t胤pico de un gato![n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]Me he relajado en el parque[n]con todos.[n][f 1 3 65535][w][e]

