[msg MSG_000_0_0 [Megafon胤a del instituto]]
[s][vp 8 0 0 1 65535 0]La fiesta de despu姻s del festival[n]est茨 a punto de empezar.[n]Os esperamos en el gimnasio.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]夷La fiesta? Pens姻 que ya hab胤a[n]terminado...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]No te han invitado, as胤 que venga,[n]v茨monos a casa.[n][f 1 3 65535][w][e]

