[msg MSG_000_0_0 [Hifumi]]
[s][bup 0 106 5 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Qu姻 mala pata. No es posible[n]que todos los restaurantes est姻n llenos.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Es una gran lecci吋n.[e]
[s]Bueno, es Nochebuena.[e]
[s]Hemos paseado juntos.[e]

[msg MSG_002_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Cierto. Ya hemos aprendido[n]la lecci吋n para la pr吋xima.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Supongo, aunque no es nada en[n]comparaci吋n con toda la gente[n]que va a la misa de Nochebuena.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Hifumi]]
[s][bup 0 106 6 4 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Podr胤a acostumbrarme[n]a ese optimismo.[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]V茨monos a casa.[e]
[s]夷Quieres venir?[e]

[msg MSG_006_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]No, a雨n no.[n][f 1 3 65535][w][e]
[s][bup 0 106 3 4 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]No voy a desperdiciar la ocasi吋n[n]de pasar tiempo contigo.[n]Es muy pronto para despedirse.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷O quieres que volvamos a casa?[n]Por m胤, bien.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Mmm, 夷a tu casa?[n]No me importar胤a.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Hifumi]]
[s][bup 0 106 0 4 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Pero al menos d姻jame llevar[n]tarta. Es Navidad, qu姻 menos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Ah, ah胤 hay una tienda.[n]A ver si les quedan...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Hifumi]]
[s][bup 0 106 3 4 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Algo me dice[n]que es tonter胤a intentarlo.[n][f 1 3 65535][w][e]
[s][bup 0 106 2 4 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]斡No! 斡No se puede perder[n]una batalla antes de empezar! 斡Vamos![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Hifumi]]
[s][bup 0 106 0 4 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Perdona, 夷no os quedar茨[n]alguna tarta navide隠a?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Empleada alegre]]
[s][f 4 10 65535 0 0][vp 8 0 0 14 8 0]斡Pues s胤![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Justo lo que pen... 夷Eh?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Empleada alegre]]
[s][f 4 10 65535 0 0][vp 8 0 0 16 8 0]Nos acaban de cancelar un pedido.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]斡De verdad! Pues...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Nos la llevamos ahora mismo.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Empleada alegre]]
[s][f 4 10 65535 0 0][vp 8 0 0 19 8 0]斡Claro que s胤! 斡Un momento,[n]os la voy a preparar![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Y, de golpe, la derrota se convirti吋[n]en victoria. Casi no me lo creo.[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]Qu姻 emoci吋n.[e]
[s]Me muero de ganas.[e]

[msg MSG_020_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Ni yo. Nunca me aburro contigo.[n][f 1 3 65535][w][e]
[s][bup 0 106 6 4 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Me alegro de que hayamos pasado[n]el d胤a as胤.[n][f 1 3 65535][w][e]

