[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ah, claro, hoy es San Valent胤n.[n]Normal que hayan venido[n]tantas parejitas.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]夷No tienes ning雨n plan rom茨ntico?[n]Ya llevas aqu胤 casi un a隠o entero.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Cuando yo era joven...[n]Je, je, je, si yo te contara...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 4 22 0]Buenas tardes.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 5 22 0]夷Vuelvo m茨s tarde?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Uy, pero hab姻rmelo dicho.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Os dejo el Leblanc, anda.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Disfrutad.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Takemi]]
[s][bup 0 108 501 6 0][f 4 10 65535 0 0][vp 8 0 0 9 22 0]Parece que vas bien.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Si姻ntate.[e]
[s]Te har姻 un caf姻, anda.[e]

[msg MSG_009_0_0 [Takemi]]
[s][bup 0 108 501 6 0][f 4 10 65535 0 0][vp 8 0 0 10 22 0]Claro...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Me alegra verte de nuevo.[n]No pareces muy angustiado.[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Me siento bien.[e]
[s]No sabr胤a decirte.[e]
[s]Te he echado de menos.[e]

[msg MSG_012_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]夷S胤? Me gustar胤a decir lo mismo.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Siempre podr胤a hacerte[n]una revisi吋n a fondo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Pero antes...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Takemi]]
[s][bup 0 108 501 6 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Esa frase es m胤a.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Takemi]]
[s][bup 0 108 502 6 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]夷Suicidarte en la c茨rcel? 夷A隠o Nuevo[n]en un reformatorio? Una disculpa[n]no solventar茨 el problema.[n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Lo siento.[e]
[s]Culpa m胤a.[e]

[msg MSG_017_0_0 [Takemi]]
[s][bup 0 108 501 6 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Ser茨 posible. No puedo dejarte solo[n]ni un segundo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Ser茨 mejor que vaya al grano.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Toma.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Son bombones. No te preocupes,[n]no llevan nada peligroso.[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]Los disfrutar姻 poco a poco.[e]
[s]夷Los has hecho t雨?[e]
[s]Me alegra no haberme perdido esto.[e]

[msg MSG_020_0_0 [Takemi]]
[s][bup 0 108 501 6 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Con moderaci吋n, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Por desgracia, no. 夷Eso es lo que quer胤as?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Takemi]]
[s][bup 0 108 501 6 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Me puse en lo peor. Estaba[n]dispuesta a llev茨rtelos a la c茨rcel.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Takemi]]
[s][bup 0 108 501 6 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]El nuevo medicamento,[n]el de la chica de la que te habl姻,[n]ha dado buenos resultados.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Y el trabajo tambi姻n va bien.[n]Ahora solo soy una doctora de barrio.[n][f 1 3 65535][w][e]

[sel SEL_024_0_0 top]
[s]Me alegra o胤r eso.[e]
[s]Te pega.[e]

[msg MSG_025_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Gracias.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Esperaba que no salieras mal parado,[n]pero no tienes ni un rasgu隠o. Supongo[n]que no ten胤a de qu姻 preocuparme.[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Deber胤a decirle a Takemi[n]que me voy a casa.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]夷Pasa algo?[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]Vuelvo a donde nac胤.[e]
[s]Vuelvo a casa.[e]

[msg MSG_029_0_0 [Takemi]]
[s][bup 0 108 503 6 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Ya veo...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]夷Puedo sentarme a tu lado?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Conozco esa mirada.[n]Ya te has decidido.[n][f 1 3 65535][w][e]

[sel SEL_032_0_0 top]
[s]夷Me echar茨s de menos?[e]
[s]Te visitar姻 en cuanto pueda.[e]

[msg MSG_033_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Quiz茨 un poco.[n][f 1 3 65535][w][e]
[s][bup 0 108 503 6 0][f 4 10 65535 0 0][f 4 24 0 6 6 38 3 100][vp 8 0 0 33 65535 0]O un mont吋n, a saber. No puedo mentirte.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]No hace falta correr.[n]Ser茨 mejor que antes te asientes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Pero, si ocurre algo, ll茨mame.[n]Ya sabes c吋mo.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]A todo esto, pareces cambiado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]No ha pasado tanto desde la 雨ltima[n]vez que te vi, pero dir胤a que[n]conf胤as m茨s en ti mismo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Puede que yo tambi姻n haya cambiado.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Takemi]]
[s][bup 0 108 500 6 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Como doctora, tengo las mismas[n]obligaciones con los pacientes, pero...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]Ahora siento que tengo algo[n]m茨s concreto y que me lo jugar胤a todo[n]por hacer feliz a una persona.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Takemi]]
[s][bup 0 108 501 6 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Eres listo, no hace falta[n]que te haga un croquis.[n][f 1 3 65535][w][e]

[sel SEL_038_0_0 top]
[s]...[e]
[s]S胤, lo pillo[e]

[msg MSG_039_0_0 [Takemi]]
[s][bup 0 108 506 6 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Nunca me han molado los jovencitos.[n][f 1 3 65535][w][e]

[msg MND_040_0_0]
[s][vp 8 0 0 0 65535 0]He pasado una noche[n]rom茨ntica con Takemi.[n][f 1 3 65535][w][e]

