[msg MSG_000_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Anda, [f 4 2]...[n]Me alegro de verte.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Qu姻 bien que est姻s a salvo.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Hablando de eso, tengo un regalito[n]para la ocasi吋n, si lo quieres...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Al parecer, hoy en d胤a la gente[n]regala chocolate a sus amigos,[n]aunque sea algo plat吋nico.[n][f 1 3 65535][w][e]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 0 0 5 65535 0]Parece una gran oportunidad[n]para celebrar que has vuelto[n]y darte las gracias.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Gracias.[e]
[s]Lo aceptar姻 encantado.[e]

[msg MSG_004_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Espero que el shogi[n]nos una a雨n m茨s.[n][f 1 3 65535][w][e]

