[msg MSG_000_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]斡Anda! Justo a tiempo. 夷Tienes un momento?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Genial. Solo quer胤a[n]darte una cosa.[n][f 1 3 65535][w][e]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 0 0 3 65535 0]No te preocupes, no es nada raro.[n]Aunque, si Sojiro lo viera,[n]pensar胤a lo que no es y flipar胤a.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]斡Aqu胤 tienes![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Chocolatito de regalo[n]para mi amigo y compa隠ero.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Si quieres agradec姻rmelo, con un a隠o[n]de fideos instant茨neos gratis me vale.[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Es un mont吋n.[e]
[s]Eso es imposible.[e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Qu姻? 夷Cre胤as que iba en serio?[n]斡Tranqui, que solo es un regalo![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Eres mi amuleto, 夷no?[n]斡Y siempre lo ser茨s![n][f 1 3 65535][w][e]

