[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]S姻 que te pilla de improviso,[n]pero 夷puedes echarle un ojo al Leblanc?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Tengo que salir un rato.[n]Echa un ojo hasta que vuelva.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Kawakami]]
[s][bup 0 109 500 6 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Ay, 夷estabas trabajando?[n]Perdona por distraerte.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Pens姻 que estar胤a bien pasarme[n]cuando volviese a casa,[n]en parte para darte esto.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Kawakami]]
[s][bup 0 109 501 6 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Al fin y al cabo, me has ayudado un[n]mont吋n. Quer胤a darte las gracias.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Gracias.[e]
[s]Lo aceptar姻 encantado.[e]

[msg MSG_004_0_0 [Kawakami]]
[s][bup 0 109 503 6 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Ah, y no pude dec胤rtelo[n]en el trabajo, pero...[n][f 1 3 65535][w][e]
[s][bup 0 109 501 6 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 4 100][vp 8 0 0 7 65535 0]Bienvenido. Me alegro de que est姻s bien.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kawakami]]
[s][bup 0 109 500 6 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Ah, s胤...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kawakami]]
[s][bup 0 109 500 6 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]He preparado una minigu胤a de estudio[n]para las clases que te has perdido.[n]Creo que cubre lo m茨s importante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Si aun as胤 no entiendes algo,[n]preg雨ntame cuando quieras.[n]Soy tu profesora. Es mi trabajo.[n][f 1 3 65535][w][e]
[s][bup 0 109 501 6 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 3 100][vp 8 0 0 11 65535 0]Bueno, te veo en el instituto.[n][f 1 3 65535][w][e]

