[msg MSG_000_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eh, 夷qu姻 tal?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Ven a Shinagawa.[e]
[s]夷Te apetece ir a Shinagawa?[e]

[msg MSG_002_0_0 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Ahora? 夷As胤 por las buenas?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si es lo que quiere mi novio,[n]斡que as胤 sea! Acabo una cosilla y voy.[n][f 1 3 65535][w][e]

[msg MND_003_0_0]
[s][vp 8 0 0 0 65535 0]Deber胤a prepararme[n]para ir a Shinagawa.[n][f 1 3 65535][w][e]

