[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]A ver... Primero toca reservar.[n]夷Te acuerdas del restaurante[n]del que te habl吋 el Jefe?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Tendero amistoso]]
[s][vp 8 0 0 2 65535 0]Gracias por llamar.[n]夷Est茨 interesado en hacer una reserva?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Mesa para dos ma隠ana por la noche.[e]
[s]Cena para dos el catorce.[e]

[msg MSG_003_0_0 [Tendero amistoso]]
[s][vp 8 0 0 3 65535 0]Lo siento mucho, pero no tenemos[n]mesas disponibles para ma隠ana.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]El D胤a Blanco es una locura...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Pero 斡t雨 tranquilo, [f 4 2]![n]斡Di que llamas de parte del Jefe![n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Soy amigo de Sojiro Sakura.[e]
[s]Sojiro Sakura me habl吋 del local.[e]

[msg MSG_006_0_0 [Tendero amistoso]]
[s][vp 8 0 0 6 65535 0]斡夷E-es amigo del se隠or Sakura?![n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 65535 0]斡Disc雨lpeme![n]Espere un momento, por favor.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Tendero amistoso]]
[s][vp 8 0 0 8 65535 0]Gracias por su paciencia.[n]Quer胤a una mesa para dos[n]para el d胤a 14, 夷verdad?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 65535 0]Se la prepararemos con mucho gusto.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]斡Ostras![n]斡El Jefe s胤 que tiene influencia![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Tendero amistoso]]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Deme su nombre[n]y datos de contacto, por favor.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Bien, los planes de la cena est茨n listos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Ahora hay que comprar las flores,[n]斡y luego toca ir al acuario[n]y al restaurante![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Ma隠ana ser茨 un d胤a ajetreado,[n]as胤 que vamos a descansar ahora.[n][f 1 3 65535][w][e]

