[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ah, ah胤 est茨s.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Venga, 夷todo listo[n]para sorprender al Jefe?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]夷Qu姻 pasa? 夷No tienes nada mejor[n]que hacer que quedarte ah胤 pasmado?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Tengo una sorpresa para ti.[e]
[s]Ten, c吋gelo.[e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Hala... 夷Es para m胤?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Ser茨 broma... Aunque, si lo fuese,[n]no sabr胤a decir d吋nde est茨 la gracia.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Gracias por todo.[e]
[s]Quiero agradecerte tus esfuerzos.[e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]No hay de qu姻, pero...[n]夷De d吋nde ha salido todo esto?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 4 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Aprecio?[n]夷De d吋nde ha salido todo esto?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Espera, no ser茨[n]por lo que dije ayer, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sojiro]]
[s][bup 0 103 3 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Venga, hombre, no me refer胤a[n]a que hicieses algo por m胤.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Pero gracias.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Qui姻n me iba a decir[n]que me regalar胤an algo as胤.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 600 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]斡Hala! El Jefe est茨 radiante.[n]斡Lo conseguimos![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Pero reg茨laselas a otra persona[n]el a隠o que viene, 夷vale?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]A alguien especial que no puedas[n]quitarte de la cabeza.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Hagas lo que hagas.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sojiro]]
[s][bup 0 103 1 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Venga, si姻ntate.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Te preparar姻 un caf姻.[n][f 1 3 65535][w][e]

