[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]He quedado con Makoto en el acuario.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Es precioso...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]He estado en m茨s acuarios,[n]pero ninguno era tan m茨gico[n]como este.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Aunque eso fue hace mucho.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Mi padre me trajo aqu胤 una vez[n]cuando estaba en el instituto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Mi hermana habr胤a venido, pero...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Creo que ese d胤a se qued吋 en casa[n]estudiando para un examen.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 4 0][vp 8 0 0 7 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Anda, 夷esto es por lo de San Valent胤n?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Por supuesto.[e]
[s]As胤 es.[e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 1 4 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]No tendr胤as que haberte molestado,[n]pero me alegro de que lo hicieras.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Gracias...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 0 4 0][vp 8 0 0 11 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Oye, 夷esta cita[n]es por el D胤a Blanco?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Por supuesto.[e]
[s]As胤 es.[e]

[msg MSG_009_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]斡Menos mal![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Como no te vi en San Valent胤n,[n]me preocup姻 bastante.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]La verdad es que me alegro[n]de que pasemos tiempo juntos.[n][f 1 3 65535][w][e]
[s][bup 0 6 1 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 16 65535 0]Gracias...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][bup 0 6 0 4 0][vp 8 0 0 17 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Oye, me has pedido salir[n]porque es el D胤a Blanco, 夷no?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Por supuesto.[e]
[s]S胤.[e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 2 4 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]En San Valent胤n,[n]no sab胤a qu姻 pensar.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 35 3 100][vp 8 0 0 20 65535 0]Pero me alegra[n]que te est姻s esforzando.[n][f 1 3 65535][w][e]
[s][bup 0 6 1 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 21 65535 0]Gracias...[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Makoto parece contenta.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Oye, 夷tienes hambre?[n]Creo que ya lo hemos visto todo.[n]Si quieres, podemos ir a cenar.[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]Ya he hecho una reserva.[e]
[s]Tengo un sitio en mente.[e]

[msg MSG_016_0_0 [Makoto]]
[s][bup 0 6 4 4 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]夷Qu姻? 夷En serio?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]斡Me estoy haciendo ilusiones![n]M茨s nos vale ir tirando.[n][f 1 3 65535][w][e]

