[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]He quedado con Takemi en el acuario.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][bup 0 108 500 1 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Hay estudios que afirman[n]que los acuarios son buenos[n]para combatir la ansiedad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Ahora que estoy en uno,[n]creo que entiendo por qu姻 lo dicen.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][bup 0 108 500 1 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Sabes a lo que me refiero... Estoy disfrutando[n]mucho, sobre todo porque estoy[n]con mi conejillo de Indias.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Nunca habr胤a dicho que a mi edad[n]tendr胤a una cita en un acuario.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Takemi]]
[s][bup 0 108 501 1 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Pero me gusta.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Me pasa bastante contigo.[n]Me cuesta acostumbrarme.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Takemi]]
[s][bup 0 108 501 1 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Por cierto, gracias por devolverme el favor...[n]a tu estilo.[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Acabamos de empezar.[e]
[s]La cita est茨 lejos de terminar.[e]

[msg MSG_006_0_0 [Takemi]]
[s][bup 0 108 501 1 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]夷Ah, s胤? 斡Me muero de ganas![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]A ver si me sorprendes.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Takemi]]
[s][bup 0 108 500 1 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Ah胤 va otra pregunta tonta.[n]夷La cita es por el D胤a Blanco?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Por supuesto.[e]
[s]As胤 es.[e]

[msg MSG_009_0_0 [Takemi]]
[s][bup 0 108 501 1 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Vale, gracias por responder.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]San Valent胤n se fue igual que vino[n]y no sab胤a qu姻 pasaba entre nosotros.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Me alegra saber[n]que pensabas en m胤.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Takemi]]
[s][bup 0 108 500 1 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]夷Cu茨nto tiempo m茨s[n]vamos a estar d茨ndole vueltas?[n]夷Esto es una disculpa?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Por supuesto.[e]
[s]S胤.[e]

[msg MSG_012_0_0 [Takemi]]
[s][bup 0 108 501 1 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Ya que mi conejillo de Indias[n]est茨 siendo sincero para variar, acepto.[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Takemi parece contenta.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Takemi]]
[s][bup 0 108 500 1 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Ya he visto suficientes peces hoy.[n]夷Ahora qu姻 hacemos?[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]He hecho una reserva.[e]
[s]Tengo un sitio en mente.[e]

[msg MSG_016_0_0 [Takemi]]
[s][bup 0 108 504 1 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]夷De verdad?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Takemi]]
[s][bup 0 108 506 1 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Entonces, vayamos a ver ese sitio.[n][f 1 3 65535][w][e]

