[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Este sitio es una locura.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷Te gusta?[e]
[s]Es la primera vez que vengo.[e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 3 4 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Estoy tan nerviosa[n]que no s姻 ni qu姻 hacer.[n][f 1 3 65535][w][e]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 3 65535 0]Pero s姻 que me alegro de estar aqu胤.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]夷S胤? Y yo que pensaba[n]que eras cliente habitual...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]La verdad es que lo dudo.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Esto es mucho m茨s intenso[n]de lo que me esperaba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Lo ten胤as bien planeado, 夷eh?[n]斡Me encantan los chicos previsores![n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Me sacas los colores.[e]
[s]Gracias.[e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]S胤.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 59 5 100][vp 8 0 0 9 65535 0]Ay, perd吋n, disc雨lpame.[n][f 1 3 65535][w][e]

[msg MND_007_0_0]
[s][vp 8 0 0 0 65535 0]夷Cu茨ndo deber胤a darle el regalo?[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]○○○ me est茨 llamando.[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]斡Ahora no puedo contestar![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]夷Te est茨n llamando?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]No es nada.[e]
[s]No te preocupes.[e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Vale.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Vale, 斡todo listo![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Locutor]]
[s][vp 8 0 0 13 65535 0]Damas y caballeros, gracias por venir[n]en este d胤a tan especial.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 14 65535 0]Esperamos que est姻n pasando una[n]velada inolvidable. Perm胤tannos[n]poner el broche final.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ann]]
[s][bup 0 4 14 4 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]夷Qu姻? Espera...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ann]]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Qu姻 bonito...[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]Quiero darte una cosa.[e]
[s]Quiero darte esto.[e]

[msg MSG_019_0_0 [Ann]]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]夷Esto es para m胤?[n][f 1 3 65535][w][e]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 5 100][vp 8 0 0 18 65535 0]Gracias.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ann]]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Vaya, el regalo perfecto[n]en el momento perfecto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Me siento como en una pel胤cula.[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]夷C吋mo te sientes?[e]
[s]夷Prefieres que te regalen comida?[e]
[s]Sorpresa.[e]

[msg MSG_022_0_0 [Ann]]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]斡Pues supercontenta, claro![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Ah, s胤. La cita habr胤a sido perfecta[n]si hubieses tra胤do tarta.[n][f 1 3 65535][w][e]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 5 100][vp 8 0 0 23 65535 0]Oye, en serio, estoy superfeliz.[n]Gracias.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Jo, qu姻 bueno eres.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]No me puedo creer que te hayas[n]tomado tantas molestias,[n]pero es que es t胤pico de ti.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Desde el d胤a en que te conoc胤...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Siempre te has centrado en qu姻[n]pod胤as hacer por quienes te rodean.[n]Siempre antepones a los dem茨s.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Admiro much胤simo esa parte de ti.[n]Quiz茨 alg雨n d胤a yo tambi姻n sea as胤.[n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s]Eres m茨s que capaz.[e]
[s]Me muero de ganas.[e]

[msg MSG_028_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Gracias.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Lo intentar姻 y alg雨n d胤a pensar茨s:[n]或Jo, 斡c吋mo me alegro[n]de que Ann est姻 en mi vida!位.[n][f 1 3 65535][w][e]

[sel SEL_029_0_0 top]
[s]Ya lo creo.[e]
[s]Lo estoy pensando.[e]

[msg MSG_030_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Pues lo pensar茨s m茨s todav胤a.[n]Yo me encargar姻.[n][f 1 3 65535][w][e]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Pase lo que pase, a partir de ahora[n]quiero estar contigo, 夷vale?[n][f 1 3 65535][w][e]

[msg MND_031_0_0]
[s][vp 8 0 0 0 65535 0]Ann y yo hemos pasado[n]un rato a solas...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Como se ha hecho tarde,[n]la he acompa隠ado a la estaci吋n.[n][f 1 3 65535][w][e]

