[msg MSG_000_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]No me esperaba algo[n]tan exuberante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Esto no es algo que dos alumnos de[n]instituto normalitos puedan[n]permitirse, 夷cierto?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]S胤.[e]
[s]Tampoco somos 或normalitos位.[e]

[msg MSG_002_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]No ten胤a ni idea.[n]Me has abierto los ojos.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Pues s胤, bien dicho.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Ser姻 feliz siempre y cuando[n]me lleves en el coraz吋n.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Je, je... Cu茨nta seguridad.[n]Veo en ti a mi valiente compa隠ero[n]de las guerras de shogi.[n][f 1 3 65535][w][e]
[s][bup 0 106 6 4 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]E incluso a alguien en quien[n]puedo confiar fuera del tablero.[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Gracias.[e]
[s]Me alegro.[e]

[msg MSG_006_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Lo m茨s justo es que me dedique[n]a ayudarte a cambio.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Hifumi]]
[s][bup 0 106 0 4 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Uy, disc雨lpame un segundo.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]夷Cu茨ndo deber胤a darle el regalo?[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]○○○ me est茨 llamando.[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]斡Ahora no puedo contestar![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]夷Te est茨 sonando el tel姻fono?[n]Si es urgente, contesta.[n][f 1 3 65535][w][e]

[sel SEL_012_0_0 top]
[s]No es para tanto.[e]
[s]No te preocupes.[e]

[msg MSG_013_0_0 [Hifumi]]
[s][bup 0 106 0 4 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Si insistes...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Hifumi]]
[s][bup 0 106 0 4 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Perd吋n por la espera.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Locutor]]
[s][vp 8 0 0 13 65535 0]Damas y caballeros, gracias por venir[n]en este d胤a tan especial.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 14 65535 0]Esperamos que est姻n pasando una[n]velada inolvidable. Perm胤tannos[n]poner el broche final.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]夷Qu姻 ser茨...?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Qu姻 maravilla...[n][f 1 3 65535][w][e]

[sel SEL_019_0_0 top]
[s]Tengo un regalo para ti.[e]
[s]Quiero que tengas esto.[e]

[msg MSG_020_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]夷Est茨s seguro?[n][f 1 3 65535][w][e]
[s][bup 0 106 6 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 18 65535 0]Muchas gracias...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Hifumi]]
[s][bup 0 106 6 4 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]El restaurante ya me hab胤a dejado sin habla[n]y encima me das un regalo precioso...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]No s姻 c吋mo agradec姻rtelo.[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s]Me alegro de que te guste.[e]
[s]No tienes que darme las gracias.[e]
[s]Sorpresa.[e]

[msg MSG_023_0_0 [Hifumi]]
[s][bup 0 106 6 4 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]El a隠o que viene te lo compensar姻.[n]No, ahora mismo.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Hifumi]]
[s][bup 0 106 3 4 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Pues claro que s胤.[n][f 1 3 65535][w][e]
[s][bup 0 106 6 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 23 65535 0]Soy tu novia, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Hifumi]]
[s][bup 0 106 6 4 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Pues s胤, menuda sorpresa.[n]La ejecuci吋n ha sido impecable.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Hifumi]]
[s][bup 0 106 0 4 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Cuidas mucho de los dem茨s...[n]No vacilas a la hora de anteponer[n]sus necesidades a las tuyas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Por ese motivo, y por muchos otros,[n]te respeto tanto.[n][f 1 3 65535][w][e]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 0 0 27 65535 0]Pero respetarte no es suficiente.[n]Alg雨n d胤a espero ser[n]tan generosa como t雨.[n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s]Gracias.[e]
[s]Haces que me sonroje.[e]

[msg MSG_028_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Me lo propondr姻 como meta.[n][f 1 3 65535][w][e]
[s][bup 0 106 7 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 0 0 29 65535 0]Pero eso puede esperar, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Ahora mismo, siempre y cuando no[n]haya un tablero de shogi de por medio,[n]solo quiero dedicarme a ti.[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Hifumi y yo hemos pasado[n]un rato a solas...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Como se ha hecho tarde,[n]la he acompa隠ado a la estaci吋n.[n][f 1 3 65535][w][e]

