[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]He quedado con Hifumi en el acuario.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Qu姻 et姻reo... Es la primera vez[n]que vengo a un acuario.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Es precioso... Aqu胤 me relajar胤a[n]y me despejar胤a mucho antes de competir.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Aunque en realidad no s姻 si estar胤a[n]tan relajada si no estuviese contigo.[n][f 1 3 65535][w][e]
[s][bup 0 106 3 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 6 100][vp 8 0 0 4 65535 0]Es posible que lo que tenga[n]que hacer no es venir al acuario,[n]sino quedar contigo.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]斡...![n][f 1 3 65535][w][e]
[s][bup 0 106 7 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 6 100][vp 8 0 0 6 65535 0]斡P-perd吋n, no s姻 en qu姻 estaba pensando![n]Haz como que no he dicho nada.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]A-ah, s胤...[n]Hoy es el D胤a Blanco, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Que hayamos quedado hoy[n]no es casualidad, 夷verdad?[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]Por supuesto.[e]
[s]As胤 es.[e]

[msg MSG_006_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Estaba en lo cierto. No te imaginas[n]las ganas que ten胤a de o胤r eso.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]A-ah, s胤...[n]Hoy es el D胤a Blanco, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Que hayamos quedado hoy[n]no es casualidad, 夷verdad?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Por supuesto.[e]
[s]As胤 es.[e]

[msg MSG_009_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]斡A-as胤 que es cierto![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Pues me alegra[n]que podamos pasar el d胤a juntos,[n]ya que no celebramos San Valent胤n.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]A-ah, s胤...[n]Hoy es el D胤a Blanco, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Que hayamos quedado hoy[n]no es casualidad, 夷verdad?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Por supuesto que no.[e]
[s]Verdad.[e]

[msg MSG_012_0_0 [Hifumi]]
[s][bup 0 106 0 4 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Ya veo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Imagino que esto formar茨 parte[n]de una gran disculpa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Pero no te ganar茨s mi perd吋n[n]con tan poco.[n][f 1 3 65535][w][e]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 6 100][vp 8 0 0 19 65535 0]Que es broma. Me alegra[n]que tus intenciones sean buenas.[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Hifumi parece contenta.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Hifumi]]
[s][bup 0 106 3 4 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]La exhibici吋n ya casi ha terminado.[n]Ojal茨 la velada no tuviera[n]que acabar tan pronto.[n][f 1 3 65535][w][e]

[sel SEL_015_0_0 top]
[s]He hecho una reserva.[e]
[s]Tengo un sitio en mente.[e]

[msg MSG_016_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]夷Qu姻...?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Hifumi]]
[s][bup 0 106 1 4 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]V-vale... Si as胤 puedo pasar[n]m茨s tiempo contigo, mejor.[n][f 1 3 65535][w][e]

