[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]Me puse nervioso cuando propusiste[n]venir al club de jazz...[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pero 斡no est茨 nada mal![n]Es como hacerse adulto[n]de nuevo...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]斡Para m胤 lo de siempre, Jefe![n]Ja, ja, nah, es co隠a.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54234 65535 0][f 5 13 8 5 2]Gracias por invitarme, t胤o.[n]Me siento como nuevo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vaya, je, je. Es m茨s tarde de[n]lo que pensaba.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 4 10 65535 0 0][vp 8 2 0 7053 65535 0]Hasta luego.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1133 65535 0]La m雨sica, el olor... No me cabe[n]duda, este es un sitio para adultos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Mua, ja, ja, el sitio ideal para[n]un caballero como yo![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 53120 65535 0]Me paso el d胤a contigo,[n]pero hay algo diferente[n]cuando estamos aqu胤.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1180 65535 0][f 5 13 2 5 3]Hemos estado un buen rato.[n]Gracias por traerme.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Deber胤amos irnos a casa.[n]No queremos que nos pillen.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][vp 8 2 0 1049 65535 0]Venga, v茨monos a casa.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6015 65535 0]斡Vaya! 斡No me imaginaba que ser胤a[n]as胤 por dentro! 斡Es como[n]un escondite para adultos![n][f 1 3 65535][w][e]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Tu habitaci吋n mola, pero esto[n]tampoco est茨 nada mal![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54030 65535 0]Puede que sea por el ambiente,[n]pero me siento un poco[n]m茨s madura...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6119 65535 0][f 5 13 7 5 4]斡Qu姻 tarde es! No me hab胤a enterado.[n][f 1 3 65535][w][e]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Vamos a casa![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ann]]
[s][vp 8 2 0 6053 65535 0]斡Hasta la pr吋xima![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 53723 65535 0]Pens姻 que 胤bamos a entrar en[n]unas catacumbas, pero...[n]esto no est茨 nada mal.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Puedo sentir la inspiraci吋n fluyendo[n]dentro de m胤! 斡Ja, ja, ja, ja![n]斡Esta noche no pienso dormir![n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53724 65535 0]Si fuera posible, me encantar胤a[n]dibujar algo... Seguro que[n]el resultado es fant茨stico.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53728 65535 0][f 5 13 5 5 5]Lamento haberte robado tanto[n]tiempo, pero agradezco que[n]me hayas tra胤do.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Creo que deber胤amos irnos. Ha sido[n]una tarde bien invertida, sin duda.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]斡Nos vemos![n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 2117 65535 0]夷Qui姻n iba a decir que tambi姻n conoces[n]sitios como este...? Es incre胤ble.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A-ah. Supongo que ser胤a de mala[n]educaci吋n echar un vistazo[n]cuando hay tanta gente...[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53323 65535 0]Al principio estaba nerviosa, pero[n]mira t雨 por d吋nde, ha resultado[n]ser relajante.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53327 65535 0][f 5 13 3 5 6]Gracias por invitarme.[n]Me lo he pasado muy bien.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uy, mira qu姻 hora es.[n]Deber胤amos irnos.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Makoto]]
[s][vp 8 2 0 2053 65535 0]斡Nos vemos![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53527 65535 0]Es un sitio bastante tranquilo,[n]y la atm吋sfera es muy acogedora.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Gracias por invitarme. Qu姻 ganas[n]de que lleguen las bebidas.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0]Tras bajar las escaleras, acabaron[n]de nuevo en el misterioso club[n]de jazz... 斡Je, es broma![n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53531 65535 0][f 5 13 4 5 7]Gracias, me lo he pasado[n]de maravilla. Espero que me invites[n]de nuevo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quiz茨 sea hora de irse a casa.[n]Hemos estado m茨s de[n]lo que esperaba.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Haru]]
[s][vp 8 2 0 3062 65535 0]斡Hasta otra![n][f 1 3 65535][w][e]

[msg MSG_060_0_0 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 9027 65535 0]斡N-no puede ser! 斡Imposible![n]斡Estoy supernerviosa![n][f 1 3 65535][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pero 斡tambi姻n tengo unas ganas[n]tremendas! 斡Es como una mazmorra![n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54725 65535 0]Hay todo un mundo de diversi吋n[n]bajo tierra. 斡Esto mola mazo![n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54729 65535 0][f 5 13 10 5 8]斡El club de jazz ha estado genial![n]Madre, no sabes[n]lo nerviosa que estaba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pero me lo he pasado muy bien.[n]斡Volvamos a casa,[n][f 4 2]![n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Futaba]]
[s][vp 8 2 0 9012 65535 0]斡Me las piro, vampiro![n][f 1 3 65535][w][e]

[msg MSG_070_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54452 65535 0]Me alegro de volver aqu胤 contigo.[n]Este club de jazz es estupendo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Me encanta que no sea muy[n]conocido... Espera,[n]夷ha sonado muy sobrado?[n][f 1 3 65535][w][e]

[msg MSG_071_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54453 65535 0]Este sitio es como tu casa.[n]No es la mejor, pero te acabas[n]sintiendo c吋modo.[n][f 1 3 65535][w][e]

[msg MSG_072_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54457 65535 0][f 5 13 9 5 9]El tiempo que paso contigo es[n]siempre muy valioso. Por cierto,[n]quer胤a comentarte algo...[n][f 1 3 65535][w][e]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Uy, perd吋n. Tengo que[n]volver al trabajo. El tiempo vuela[n]cuando te diviertes, 夷no crees?[n][f 1 3 65535][w][e]

[msg MSG_073_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Hasta la pr吋xima.[n][f 1 3 65535][w][e]

[msg MSG_080_0_0 [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57033 65535 0]夷Sueles venir a clubs de jazz?[n]Eres tan maduro...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Puedes ir a pedir t雨 solo?[n]O...[n][f 1 3 65535][w][e]

[msg MSG_081_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57039 65535 0]Muchas gracias por invitarme.[n]Hay tanto de lo que[n]te quiero hablar...[n][f 1 3 65535][w][e]

[msg MSG_082_0_0 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0][f 5 13 33 5 10]斡Me lo he pasado tan bien![n]Espero que me invites de nuevo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Nos vamos a casa?[n]Se est茨 haciendo tarde.[n][f 1 3 65535][w][e]

[msg MSG_083_0_0 [Sumire]]
[s][vp 8 2 0 57071 65535 0]Hasta luego.[n][f 1 3 65535][w][e]

[msg MSG_090_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54410 65535 0]Incluso en tiempos como estos,[n]este sitio sigue igual.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Quer胤as hablar conmigo? Podemos[n]charlar largo y tendido, si quieres.[n][f 1 3 65535][w][e]

[msg MSG_091_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54503 65535 0]夷Tanto te gusta este sitio?[n]El sentimiento es mutuo.[n][f 1 3 65535][w][e]

[msg MSG_092_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54475 65535 0][f 5 13 9 5 9]No ha estado nada mal.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece que es la hora.[n][f 1 3 65535][w][e]

[msg MSG_093_0_0 [Akechi]]
[s][vp 8 2 0 54502 65535 0]Nos vemos.[n][f 1 3 65535][w][e]

