[msg MSG_000_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55501 65535 0]Te doy la bienvenida a la Habitaci吋n Terciopelo.[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 2 0 0 65535 0]La puerta de la c茨rcel[n]est茨 abierta...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55404 65535 0]El estado de la Habitaci吋n[n]Terciopelo refleja el estado[n]de tu coraz吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Los cambios en la sala reflejan[n]tu esp胤ritu de rebeli吋n hacia[n]la entidad que domina tu futuro.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55506 65535 0]Sin duda. Tu cambio de aspecto[n]tambi姻n se puede deber al esp胤ritu[n]rebelde que has albergado.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece que ese esp胤ritu[n]te ha abierto nuevas posibilidades.[n][f 1 3 65535][w][e]

[sel SEL_005_0_0 top]
[s]夷Qu姻 posibilidad?[e]
[s]夷A qu姻 te refieres?[e]

[msg MSG_006_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55476 65535 0]Ahora deber胤as ser capaz[n]de fusionar nuevas Personas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]郁salo con cabeza[n]para mantener la perdici吋n a raya.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 2 0 55505 65535 0]Te seguiremos ayudando[n]en tu peligroso viaje.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ahora, vuelve a tus asuntos...[n][f 1 3 65535][w][e]

