[msg CROSSWORD_00_TEXT_00]
[s]What lights do for store signage[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]ILLUMINATE[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Birthday cake topper[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Lady Liberty's light[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

