[msg CROSSWORD_00_TEXT_00]
[s]Draws people to you[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]CHARISMA[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Watching paint dry[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Walk arrogantly[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

