[msg CROSSWORD_00_TEXT_00]
[s]Ancient goddess of fate[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]LACHESIS[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Longest prison term[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Foreordained[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_09]
[s][XLOC_NOTUSED][n][w][e]

