[msg CROSSWORD_00_TEXT_00]
[s]Tsukimi: lunar viewing (?)[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]FESTIVAL[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Many lack time for these[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Prayer site[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s]Buzzkill victim[n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_09]
[s][XLOC_NOTUSED][n][w][e]

