[msg CROSSWORD_00_TEXT_00]
[s]Absorbs the most light[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]BLACK[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Bottomless chasm[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Bereaved wife[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s]Only dies in darkness[n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_09]
[s][XLOC_NOTUSED][n][w][e]

