[msg CROSSWORD_00_TEXT_00]
[s]A.K.A. sweating sickness[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]INFLUENZA[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Extreme tiredness[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]"Gesundheit!" trigger[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

