[msg CROSSWORD_00_TEXT_00]
[s]A border between air masses[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]FRONT[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Cooled with cubes[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Checked daily[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s]Atmospheric disturbance[n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_09]
[s][XLOC_NOTUSED][n][w][e]

