[msg CROSSWORD_00_TEXT_00]
[s]Many students' greatest love[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]VACATION[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Go here and there[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Sunny season[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

