[msg CROSSWORD_00_TEXT_00]
[s]Tipster hotlines offer this[n][w][e]

[msg CROSSWORD_00_TEXT_01]
[s]REWARD[n][w][e]

[msg CROSSWORD_00_TEXT_02]
[s]Cold, hard payment[n][w][e]

[msg CROSSWORD_00_TEXT_03]
[s]Wasn't just given[n][w][e]

[msg CROSSWORD_00_TEXT_04]
[s]Buyer's proposal[n][w][e]

[msg CROSSWORD_00_TEXT_05]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_06]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_07]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_08]
[s][XLOC_NOTUSED][n][w][e]

[msg CROSSWORD_00_TEXT_09]
[s][XLOC_NOTUSED][n][w][e]

