[msg D_TUTORIAL_20_mes01 [Jose]]
[s]Al hablar con [clr 2]Jose[clr 27] en Mementos, podr茨s darle [clr 2]flores[clr 27][n]a cambio de objetos. El n雨mero de flores variar茨[n]en funci吋n del objeto que quieras. Cuanto m茨s raro[n]sea, m茨s flores necesitar茨s.[n][w][e]

[msg D_TUTORIAL_20_mes02 [Jose]]
[s]Estas flores solo existen en Mementos,[n]as胤 que ten cuidado. [clr 2]Perder茨s[n]las flores recogidas[clr 27] al marcharte.[n][w][e]

