[msg D_TUTORIAL_27_mes01 [Ayuda de Ladr吋n]]
[s]Pulsa [clr 2][f 1 10 35][clr 27] mientras investigas el Metaverso[n]para usar Ayuda de ladr吋n, que te da acceso[n]a varias funciones de utilidad para tu progreso.[n][w][e]

[msg D_TUTORIAL_27_mes02 [Ayuda de Ladr吋n]]
[s]Autorrecuperaci吋n usa las habilidades[n]curativas del grupo [clr 2]en todos los miembros[clr 27].[n]Para ello, [clr 2]se utilizar茨n los PE necesarios[clr 27].[n][w][e]

[msg D_TUTORIAL_27_mes03 [Ayuda de Ladr吋n]]
[s]Puedes usar [clr 2]herramientas de infiltraci吋n[clr 27] como[n][clr 2]pantallas de humo[clr 27] para huir del combate.[n]Estas herramientas te dar茨n ventaja durante las batallas.[n][w][e]

