[msg TUTORIAL_MSG01 [Estudiar en la biblioteca]]
[s]Cuando estudies en la biblioteca, el tiempo[n]pasar茨, pero mejorar茨 tu [f 4 11 0][clr 26][f 4 12 0][clr 27].[n]Adem茨s, cuando haga [clr 2]mal tiempo[clr 27], tu concentraci吋n[n]y tu [f 4 11 0][clr 26][f 4 12 0][clr 27] aumentar茨n a雨n m茨s.[n][w][e]

[msg TUTORIAL_MSG02 [Estudiar en la biblioteca]]
[s]A veces oir茨s a los dem茨s hablar[n]de ti y perder茨s la concentraci吋n.[n]Tu [f 4 11 0][clr 26][f 4 12 0][clr 27][clr 2] no aumentar茨 mucho[clr 27], pero tu[n][f 4 11 3][clr 26][f 4 12 3][clr 27] aumentar茨 un poco en su lugar.[n][w][e]

