[msg TUTORIAL_MSG01 [Trabajar en el restaurante]]
[s]Trabajar en el restaurante de gyuudon[n]har茨 que pase el tiempo, pero ganar茨s[n]dinero y tu [f 4 11 2][clr 26][f 4 12 2][clr 27] mejorar茨.[n][w][e]

[msg TUTORIAL_MSG02 [Trabajar en el restaurante]]
[s]Algunos d胤as habr茨 m茨s gente que de costumbre[n]y tendr茨s que recordar muchos pedidos.[n]Mant姻n la calma. Si superas este apuro,[n]ganar茨s m茨s dinero de lo normal.[n][w][e]

