[msg D_TUTORIAL_24_mes01 [Salas de espera]]
[s]Encontrar茨s [clr 2]Salas de espera[clr 27] en Mementos.[n]Al igual que en las Habitaciones seguras, puedes [clr 2]guardar[clr 27] y[n]usar [clr 2]Viaje r茨pido[clr 27] desde ellas.[n][w][e]

[msg D_TUTORIAL_24_mes01_NX [Salas de espera]]
[s]Encontrar茨s [clr 2]Salas de espera[clr 27] en Mementos.[n]Al igual que en las Habitaciones seguras, puedes [clr 2]guardar[clr 27] y[n]usar [clr 2]Viaje r茨pido[clr 27] desde ellas.[n][w][e]

[msg D_TUTORIAL_24_mes01_PS5 [Salas de espera]]
[s]Encontrar茨s [clr 2]Salas de espera[clr 27] en Mementos.[n]Al igual que en las Habitaciones seguras, puedes [clr 2]guardar[clr 27] y[n]usar [clr 2]Viaje r茨pido[clr 27] desde ellas.[n][w][e]

[msg D_TUTORIAL_24_mes01_Xbox [Salas de espera]]
[s]Encontrar茨s [clr 2]Salas de espera[clr 27] en Mementos.[n]Al igual que en las Habitaciones seguras, puedes [clr 2]guardar[clr 27] y[n]usar [clr 2]Viaje r茨pido[clr 27] desde ellas.[n][w][e]

[msg D_TUTORIAL_24_mes01_Stea [Salas de espera]]
[s]Encontrar茨s [clr 2]Salas de espera[clr 27] en Mementos.[n]Al igual que en las Habitaciones seguras, puedes [clr 2]guardar[clr 27] y[n]usar [clr 2]Viaje r茨pido[clr 27] desde ellas.[n][w][e]

