[msg TUTORIAL_MSG01 [Atravesar la defensa enemiga]]
[s]Los ataques a distancia no pueden asestar golpes cr胤ticos.[n]Sin embargo, debilitar茨n la defensa del enemigo[n]y propiciar茨n que otros ataques s胤 lo hagan.[n][w][e]

[msg TUTORIAL_MSG02 [Atravesar la defensa enemiga]]
[s]Cuanto mayor sea el poder de ataque,[n]m茨s posibilidades tendr茨s de atravesar la defensa del enemigo,[n]que se reestablecer茨 al recibir un golpe cr胤tico.[n][w][e]

