[msg TUTORIAL_MSG01 [Tiempo libre en otras clases]]
[s]Kawakami a veces te dar茨 tiempo libre[n]haciendo salir a profesores.[n]Aprov姻chalo para [clr 2]leer[clr 27] o[n]crear [clr 2]herramientas de infiltraci吋n[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Tiempo libre en otras clases]]
[s]Sin embargo, ganar茨s [f 4 11 0][clr 26][f 4 12 0][clr 27][n]si eliges estudiar. Piensa bien[n]qu姻 es lo que m茨s te conviene.[n][w][e]

