[msg TUTORIAL_MSG01 [Estados alterados]]
[s]Los [clr 2]estados alterados[clr 27] son estados negativos anormales[n]que suelen presentar inconvenientes mientras surten efecto.[n]Los estados alterados son los siguientes:[n][w][e]

[msg TUTORIAL_MSG02 [Estados alterados]]
[s][clr 2]Quemadura[clr 27]: recibes da隠o tras actuar.[n][clr 2]Congelaci吋n[clr 27]: no puedes actuar.[n][clr 2]Electrificaci吋n[clr 27]: no puedes actuar y puedes[n]electrificar a quienes te rodean.[n][w][e]

[msg TUTORIAL_MSG03 [Estados alterados]]
[s][clr 2]Mareo[clr 27]: se reduce mucho la precisi吋n.[n][clr 2]Amnesia[clr 27]: no puedes usar habilidades.[n][clr 2]Sue隠o[clr 27]: no puedes actuar, pero recuperas[n]PS y PE con el tiempo.[n][w][e]

[msg TUTORIAL_MSG04 [Estados alterados]]
[s][clr 2]Confusi吋n[clr 27]: realizas acciones desfavorables[n]para tu grupo.[n][clr 2]Miedo[clr 27]: alta probabilidad de ignorar 吋rdenes.[n]Riesgo de huir del combate.[n][w][e]

[msg TUTORIAL_MSG05 [Estados alterados]]
[s][clr 2]Desesperaci吋n[clr 27]: no puedes actuar y los PE[n]disminuyen con el tiempo. Provoca la muerte.[n][clr 2]Furia[clr 27]: aumenta el atq. y disminuye la def.[n]Solo puedes usar ataques cuerpo a cuerpo.[n][w][e]

[msg TUTORIAL_MSG06 [Estados alterados]]
[s][clr 2]Manipulaci吋n[clr 27]: atacas a aliados y potencias o curas a enemigos.[n][clr 2]Hambre[clr 27]: disminuye mucho la potencia de todos los ataques.[n][w][e]

