[msg TUTORIAL_MSG01 [Desaf胤o de combate]]
[s]Para acceder a un desaf胤o de combate,[n]habla con las alcaidesas de la Habitaci吋n Terciopelo.[n][w][e]

[msg TUTORIAL_MSG02 [Desaf胤o de combate]]
[s]En un desaf胤o de combate, t雨 y tu grupo luchar姻is[n]contra enemigos con el objetivo de conseguir la[n]m茨xima puntuaci吋n infligi姻ndoles todo el da隠o posible.[n][w][e]

[msg TUTORIAL_MSG03 [Desaf胤o de combate]]
[s]Las alcaidesas os recompensar茨n en funci吋n[n]de la puntuaci吋n que consig茨is.[n][w][e]

[msg TUTORIAL_MSG04 [Desaf胤o de combate]]
[s]Tras el combate, se restaurar茨n tus PS y PE,[n]pero no se te devolver茨n los objetos que hayas consumido.[n]Si te derrotan, la partida no terminar茨.[n][w][e]

[msg TUTORIAL_MSG05 [Desaf胤o de combate]]
[s]Dummy[n][w][e]

