[msg TUTORIAL_MSG01 [Usar las jaulas de bateo]]
[s]Usar las jaulas de bateo har茨 que pase[n]el tiempo, pero obtendr茨s premios seg雨n tu[n]desempe隠o. Tu [f 4 11 2][clr 26][f 4 12 2][clr 27][n]tambi姻n mejorar茨.[n][w][e]

[msg TUTORIAL_MSG02 [Usar las jaulas de bateo]]
[s]Har茨s un total de 5 lanzamientos.[n]Si golpeas las cinco bolas, conseguir茨s [clr 2]el premio bateador[clr 27],[n]y si haces una carrera, el [clr 2]premio home run[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Usar las jaulas de bateo]]
[s]Las actividades var胤an seg雨n la hora del d胤a.[n]Por la noche no hay premios, pero puedes [clr 2]golpear sin l胤mite[clr 27].[n]Adem茨s, si haces [clr 2]3 home runs[clr 27][n]recibir茨s un [clr 2]cup吋n de bateo gratis[clr 27].[n][w][e]

