[msg TUTORIAL_MSG01 [Ir a la tienda de segunda mano]]
[s]En la tienda de segunda mano puedes vender [clr 2]armadura[n]sucia[clr 27]. Dependiendo de lo que fuera originariamente,[n]podr胤as conseguir un buen precio por ella.[n][w][e]

[msg TUTORIAL_MSG02 [Ir a la tienda de segunda mano]]
[s]Por cada prenda que vendas, ganar茨s[n][clr 2]puntos de la tienda[clr 27], que puedes cambiar[n]por [clr 2]premios[clr 27] en ella. 斡A lo mejor ves algo 雨til![n][w][e]

