[msg D_TUTORIAL_04_mes01 [Mal tiempo]]
[s]Si hace [clr 2]mal tiempo[clr 27] o llueve,[n]Mementos ser茨 m茨s peligroso,[n]pero [clr 2]podr茨s obtener objetos adicionales[clr 27].[n][w][e]

[msg D_TUTORIAL_04_mes02 [Mal tiempo]]
[s]Los refuerzos enemigos ser茨n m茨s comunes,[n]pero a veces incluir茨n [clr 2]enemigos raros[clr 27].[n][w][e]

[msg D_TUTORIAL_04_mes03 [Mal tiempo]]
[s]Los objetos ser茨n m茨s valiosos[n]y habr茨 [clr 2]m茨s cofres[clr 27], as胤 que aprovecha.[n][w][e]

