[msg TUTORIAL_MSG01 [或Especial位 y combinaciones]]
[s]或Especial位 suele darse cuando[n][clr 2]realizas un Relevo[clr 27] a [clr 2][f 4 2] o[n]a otro miembro del grupo en apuros[clr 27]; o cuando el [clr 2]enemigo[n]est茨 a punto de ser derrotado[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [或Especial位 y combinaciones]]
[s]Al principio, solo se activar茨 para Ann[n]y Morgana, pero ir茨s consiguiendo combinaciones[n]a medida que avances en la historia.[n][w][e]

[msg TUTORIAL_MSG03 [或Especial位 y combinaciones]]
[s]或Especial位 puede activarse[n]incluso si el otro miembro del grupo est茨 en la reserva.[n]Echa un vistazo a las combinaciones en[n][clr 2]Estad胤sticas[clr 27], en el men雨 [f 1 10 25].[n][w][e]

