[msg TUTORIAL_MSG01 [Controles de la jaula de batear]]
[s]Ajusta el 茨ngulo de bateo con [clr 2][f 1 10 43][clr 27][n]para adaptarte a la trayectoria de la bola.[n][w][e]

[msg TUTORIAL_MSG02 [Controles de la jaula de batear]]
[s]Cuando la bola coincida con su icono,[n]pulsa [clr 2][f 1 10 22][clr 27] para batear. Golpea la[n]diana para hacer un home run.[n][w][e]

[msg TUTORIAL_MSG01_Fiber_Ste [Controles de la jaula de batear]]
[s]Ajusta el 茨ngulo de bateo con [clr 2][f 1 10 81][clr 27][n]para adaptarte a la trayectoria de la bola.[n][w][e]

