[msg TUTORIAL_MSG01 [Rotar la c茨mara]]
[s]Puedes usar [clr 2][f 1 10 45][clr 27] para rotar[n]la c茨mara. Si pulsas [clr 2][f 1 10 70][clr 27] o [clr 2][f 1 10 59][clr 27],[n]la c茨mara volver茨 a su posici吋n[n]predeterminada.[w][e]

[msg TUTORIAL_MSG02 [Rotar la c茨mara]]
[s]Puedes ajustar la velocidad y la direcci吋n[n]de la rotaci吋n de la c茨mara en [clr 2]Ajustes[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Rotar la c茨mara]]
[s]Rota la c茨mara para mirar[n]la ciudad y a la gente.[n][w][e]

