[msg TUTORIAL_MSG01 [Obst茨culos especiales en los Palacios]]
[s]A veces te topar茨s con [clr 2]obst茨culos de Palacio[n]que no podr茨s ignorar y que requieren interacci吋n[n]con el objetivo en el mundo real[clr 27].[n][w][e]

[msg TUTORIAL_MSG02 [Obst茨culos especiales en los Palacios]]
[s]Tendr茨s que abandonar el Palacio para descubrir[n]qu姻 causa esa obstrucci吋n. Entra en los Palacios[n]lo antes posible para encontrar los obst茨culos y[n]superar los desaf胤os antes de la fecha l胤mite.[n][w][e]

