[msg TUTORIAL_MSG01 [El quinto asalto: Okumura]]
[s]Gracias a los datos de Sae, Futaba averigua[n]que al CEO de Okumura Foods,[n][clr 2]Kunikazu Okumura[clr 27], lo est茨n investigando.[n][w][e]

[msg TUTORIAL_MSG02 [El quinto asalto: Okumura]]
[s]Los Ladrones Fantasma debaten si despertar[n]su coraz吋n solo por la opini吋n p雨blica.[n]La situaci吋n se pone tensa y Morgana se escapa[n]de casa.[n][w][e]

[msg TUTORIAL_MSG03 [El quinto asalto: Okumura]]
[s][f 4 2] y los dem茨s lo siguen hasta el[n]Palacio de Okumura, donde lo encuentran[n]con una mujer llamada 或Bella ladrona位.[n]No consiguen hacer las paces con 姻l.[n][w][e]

[msg TUTORIAL_MSG04 [El quinto asalto: Okumura]]
[s]Mientras investigan la identidad de la[n]mujer, averiguan que se trata de [clr 2]Haru[n]Okumura[clr 27], la hija de Okumura.[n][w][e]

[msg TUTORIAL_MSG05 [El quinto asalto: Okumura]]
[s]Haru les explica que quiere despertar[n]el coraz吋n de su padre. Tras unirse[n]a ellos, regresan al Palacio de Okumura.[n][w][e]

[msg TUTORIAL_MSG06 [El quinto asalto: Okumura]]
[s]Los Ladrones Fantasma derrotan a la sombra de[n]Okumura y le roban el tesoro. Despu姻s se marchan[n]y esperan que acabe despertando.[n][w][e]

[msg TUTORIAL_MSG07 [El quinto asalto: Okumura]]
[s]Ven la rueda de prensa de Okumura[n]mientras lo celebran en Destinyland,[n]pero la fiesta no dura mucho...[n][w][e]

[msg TUTORIAL_MSG08 [El quinto asalto: Okumura]]
[s]Okumura sufre una desconexi吋n mental[n]durante la rueda de prensa y muere,[n]cosa que les sorprende porque ellos[n]no han tenido nada que ver.[n][w][e]

