[msg TUTORIAL_MSG01 [Puntuaciones altas de Desaf胤os en combate]]
[s]Las puntuaci吋n de los desaf胤os de[n]combate se basa en el [clr 2]da隠o infligido[clr 27].[n]Infligir mucho da隠o te ayudar茨[n]a conseguir una puntuaci吋n alta.[n][w][e]

[msg TUTORIAL_MSG02 [Puntuaciones altas en Desaf胤os de combate]]
[s]Utiliza [clr 2]habilidades de apoyo[clr 27], [clr 2]Relevo[clr 27][n]y [clr 2]ataques t姻cnicos[clr 27] para obtener[n]una puntuaci吋n alta. Consigue a雨n[n]m茨s puntos con efectos adicionales.[n][w][e]

[msg TUTORIAL_MSG03 [Mu隠eco]]
[s]Mu隠eco[n][w][e]

[msg TUTORIAL_MSG04 [Mu隠eco]]
[s]Mu隠eco[n][w][e]

