[msg TUTORIAL_MSG01 [Creador de Palacio]]
[s]Una vez hayas [clr 2]comprado objetos[clr 27][n]con medallas P, podr茨s colocarlos[n]en la Guarida de los Ladrones.[n][w][e]

[msg TUTORIAL_MSG02 [Creador de Palacio]]
[s][clr 2]Los aliados cognitivos y los Confidentes[clr 27] vendr茨n a ver y[n][clr 2]hablar de tus objetos[clr 27]. Esos personajes cambiar茨n cuando[n]entres en la Guarida o cambies la ubicaci吋n del objeto.[n][w][e]

[msg TUTORIAL_MSG03 [Creador de Palacio]]
[s]Puedes ajustar la [clr 2]decoraci吋n[clr 27] seg雨n el progreso[n]de la historia. El interior de la Guarida de los Ladrones[n]puede cambiar en funci吋n de la decoraci吋n.[n][w][e]

