[msg TUTORIAL_MSG01 [Afinidades de atributo]]
[s]Toda Persona y sombra[n]tiene afinidades de atributo.[n][w][e]

[msg TUTORIAL_MSG02 [Afinidades de atributo]]
[s]夷?: desconocido, ya que no ha sido atacado.[n]Punto d姻bil: recibe mucho da隠o[n]y puede ser derribado.[n][w][e]

[msg TUTORIAL_MSG03 [Afinidades de atributo]]
[s]Resistencia: no recibe mucho da隠o.[n]Anular: no recibe da隠o.[n]Reflejar: refleja el da隠o.[n]Absorber: absorbe el da隠o.[n][w][e]

[msg TUTORIAL_MSG04 [Afinidades de atributo]]
[s]Puedes cambiar las afinidades de atributo[n]con potenciadores y habilidades autom茨ticas.[n][w][e]

