[msg D_TUTORIAL_11_mes01 [Ponerse a cubierto]]
[s]Pulsa [clr 2][f 1 10 22][clr 27] junto a un escondite[n]para ocultarte. As胤 podr茨s ver,[n][clr 2]pero a ti no te ver茨n[clr 27].[n][w][e]

[msg D_TUTORIAL_11_mes02 [Ponerse a cubierto]]
[s]Si hay otro escondite cerca, pulsa[n][clr 2][f 1 10 22][clr 27] para saltar hacia 姻l.[n][w][e]

[msg D_TUTORIAL_11_mes03 [Ponerse a cubierto]]
[s]Si hay enemigos al alcance, puedes atacar[n]desde el escondite y tenderles una [clr 2]emboscada[clr 27].[n][w][e]

[msg D_TUTORIAL_11_mes04 [Ponerse a cubierto]]
[s]Usa este truco y gana ventaja.[n]Eso s胤, no podr茨s esconderte si el[n]enemigo ya te est茨 persiguiendo.[n][w][e]

