[msg TUTORIAL_MSG01 [Duplicado]]
[s]Ahora Yusuke puede usar [clr 1]Duplicado[clr 27] para[n]hacerte copias de las cartas de habilidad.[n][w][e]

[msg TUTORIAL_MSG02 [Duplicado]]
[s]Para copiar una carta de habilidad,[n]dale a Yusuke una en blanco y la que quieras copiar.[n]Podr茨s recoger las dos al [clr 2]d胤a siguiente[clr 27].[n][w][e]

[msg TUTORIAL_MSG03 [Duplicado]]
[s][clr 2]La carta en blanco se transformar茨[clr 27] y crear茨[n]una nueva. Yusuke te devolver茨 las dos.[n][w][e]

[msg TUTORIAL_MSG04 [Duplicado]]
[s]Las cartas en blanco se obtienen [clr 2]buscando[n]objetos en Mementos[clr 27]. Encuentra todas las que puedas.[n][w][e]

