[msg D_TUTORIAL_37_mes01 [Gancho de cadenas]]
[s]Tras las clases con Kasumi,[n][f 4 2] ha aprendido a usar [clr 2]Gancho de cadenas[clr 27].[n][w][e]

[msg D_TUTORIAL_37_mes02 [Gancho de cadenas]]
[s]El arpeo te permitir茨 atacar[n]a una sombra que est姻 m茨s lejos[n]de lo normal e iniciar una batalla preventiva.[n][w][e]

[msg D_TUTORIAL_37_mes03 [Gancho de cadenas]]
[s]Al iniciar un combate con el Gancho[n]de cadenas, los enemigos comenzar茨n[n]con Mareo, Confusi吋n o Miedo.[n][w][e]

