[msg D_TUTORIAL_17_mes01 [Demonios del tesoro]]
[s]Los objetos rompibles pueden contener [clr 2]Demonios del[n]tesoro[clr 27], sobre todo cuando el [clr 2]nivel de seguridad es alto[clr 27].[n]Tambi姻n aparecen en enfrentamientos normales.[n]V姻ncelos y gana muchos puntos de experiencia.[n][w][e]

[msg D_TUTORIAL_17_mes02 [Demonios del tesoro]]
[s]Si alguno acepta ser tu Persona, valdr茨[n]como material de fusi吋n.[n]Eso s胤, [clr 2]no podr茨s usarlo[n]en combate[clr 27].[n][w][e]

