[msg SYS_039_0_0]
[s][vp 1 0 0 0 0 0]El combate dur吋 ○○ turnos...[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Mm... no ha estado muy bien[n]que digamos, pero creo[n]que vas por buen camino.[n][f 1 3 65535][w][e]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]En realidad ha sido[n]muy divertido, recluso.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Perm胤teme que revele[n]los resultados de la prueba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Si tuviera que describir[n]tu estado actual...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]...dir胤a que eres[n]alguien con potencial.[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Caroline]]
[s][bup 0 102 1 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Apuntas alto, 夷eh?[n][f 1 3 65535][w][e]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Que no se te suba a la cabeza.[n]Todav胤a te queda[n]mucho por aprender.[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Sin embargo, has luchado bien.[n]Acepta esto.[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Justine]]
[s][bup 0 101 0 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Sigue entrenando y vuelve despu姻s.[n]Quiz茨 el pr吋ximo[n]combate sea mejor.[n][f 1 3 65535][w][e]

