[msg MSG_000_0_0 [Lavenza]]
[s][bup 0 100 3 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Argh...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Ha sido... como esperaba.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]He presenciado de primera mano[n]los frutos de tu rehabilitaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Sin importar lo que te acechara,[n]sigues siendo libre[n]gracias a tu propia voluntad...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]A pesar del dolor y las adversidades,[n]has tenido fe en tus compa隠eros[n]y has luchado por lo que crees.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]No veas...[e]
[s]No s姻...[e]

[msg MSG_003_0_0 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Aunque digas eso, has logrado[n]tu objetivo. Eso debe ser lo que[n]cautiva a los que te rodean.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Admitir eso y al mismo tiempo lograr[n]tu objetivo debe ser lo que[n]cautiva a los que te rodean.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]No eclipsas a los dem茨s, sino que[n]los cautivas y haces que lleven sus[n]habilidades m茨s all茨 de sus l胤mites...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Debe ser tambi姻n una forma de poder[n]que dominar.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Gracias a ti, creo que ahora entiendo[n]perfectamente mi papel de 或quien[n]domina el poder位.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Soy un ser que necesita tener fe[n]en el potencial de la humanidad[n]cuando cuenta con una gu胤a...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Como tal, no es sencillo[n]admitir esto...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Pero soy feliz.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Me siento muy afortunada[n]de poder presenciar la forja[n]de tu camino.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Muchas gracias, Trickster m胤o.[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Deber胤a darte yo darte las gracias.[e]
[s]Sigo contando contigo.[e]

[msg MSG_012_0_0 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Eh... No hay de qu姻.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]S胤, por supuesto.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Aqu胤 tienes una muestra de agradecimiento.[n]Ac姻ptala, por favor.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Cuando me derrotaste mientras estaba[n]dividida en dos mitades,[n]te di un marcap茨ginas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]En su d胤a, se les entreg吋 como[n]recept茨culo de mis recuerdos...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]No era m茨s que una mera copia.[n]Lo que ahora te otorgo[n]es la reliquia original.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Que ambos marcap茨ginas est姻n en tus[n]manos es prueba de tu excepcional val胤a.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Ese marcap茨ginas tiene para m胤 un valor[n]incalculable, y t雨 te lo mereces.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Puede que, ahora mismo, tus compa隠eros[n]y t雨 os enfrent姻is a un duro calvario...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]No obstante, no debes tener miedo,[n]sin importar los obst茨culos que[n]os encontr姻is.[n][f 1 3 65535][w][e]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][f 4 24 0 4 6 42 5 100][vp 8 0 0 26 65535 0]Al fin y al cabo, eres el hombre[n]m茨s maravilloso del mundo.[n][f 1 3 65535][w][e]

