[msg MSG_000_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Estaba esper茨ndote.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]He venido a pedirte un favor.[n]夷Podr胤as permitirme algo?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷Un favor?[e]
[s]夷Qu姻 quieres?[e]

[msg MSG_002_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Me gustar胤a... enfrentarme a ti.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Ahora que he recuperado mi forma[n]original, me gustar胤a volver a luchar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Te he visto crecer mucho desde que[n]derrotaste al dios maligno y[n]completaste tu rehabilitaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Al ser 或quien domina el poder位, me gustar胤a[n]juzgar ese crecimiento.[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]夷Quien domina el poder?[e]
[s]夷Es necesario?[e]

[msg MSG_005_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]As胤 es. Como tal, mi responsabilidad[n]es evaluar tu poder...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Es un paso vital en mi autoconocimiento.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Lavenza]]
[s][bup 0 100 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]S胤. Es vital para mi autoconocimiento.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]El maestro me ha dado permiso[n]para que nos enfrentemos, pero[n]no te obligar姻 a aceptar el desaf胤o.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Por favor, av胤same cando est姻s[n]preparado.[n][f 1 3 65535][w][e]

