[msg MND_000_0_0]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]夷Qu姻 hora es?[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]夷Y mi tel姻fono?[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 1 0 0 0 0 0]Parece que he olvidado ponerlo a cargar.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 1 0 0 0 0 0]Me est茨 volviendo a entrar sue隠o...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Deber胤a dormir un poco m茨s...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]No quiero... pensar m茨s...[n][f 1 3 65535][w][e]

