[msg MSG_000_0_0 [Futaba]]
[s][vp 6 0 0 1 0 0]斡Lo tenemos encima![n][f 1 2 150][e]

[msg MSG_001_0_0 [Yusuke]]
[s][vp 6 0 0 2 0 0]斡Violet![n][f 1 2 30][e]

[msg MSG_002_0_0 [Sumire]]
[s][vp 6 0 0 3 0 0]斡Cendrillon![n][f 1 2 29][e]

[msg MSG_003_0_0 [Sumire]]
[s][vp 6 0 0 4 0 0]斡夷Qu姻?![n][f 1 2 75][e]

[msg MSG_004_0_0 [Morgana]]
[s][vp 6 0 0 5 0 0]Su Persona...[n][f 1 2 30][e]

[msg MSG_007_0_0 [Ryuji]]
[s][vp 6 0 0 6 0 0]斡Va a ser que no![n][f 1 2 37][e]

[msg MSG_008_0_0 [Sumire]]
[s][vp 6 0 0 7 0 0]斡Manteneos atr茨s![n][f 1 2 40][e]

[msg MSG_008_5_0 [Sumire]]
[s][vp 6 0 0 8 0 0]Os lo agradezco,[n]pero dej茨dmelo a m胤.[n][f 1 2 65][e]

[msg MSG_009_0_0 [Sumire]]
[s][vp 6 0 0 9 0 0]Yo elijo valerme por m胤[n]misma y luchar.[n][f 1 2 66][e]

[msg MSG_010_0_0 [Sumire]]
[s][vp 6 0 0 10 0 0]斡Ya vale de ser una in雨til![n][f 1 2 54][e]

[msg MSG_011_0_0 [Sumire]]
[s][vp 6 0 0 11 0 0]Agach姻 la cabeza[n]y te agarr姻 la mano...[n][f 1 2 102][e]

[msg MSG_012_0_0 [Sumire]]
[s][vp 6 0 0 12 0 0]En el fondo siempre lo supe...[n][f 1 2 60][e]

[msg MSG_013_0_0 [Sumire]]
[s][vp 6 0 0 13 0 0]Fingir ser Kasumi no es lo correcto.[n][f 1 2 80][e]

[msg MSG_016_0_0 [Sumire]]
[s][vp 6 0 0 14 0 0]Argh... 斡Aaah...![n][f 1 2 215][e]

[msg MSG_018_0_0 [Sumire]]
[s][vp 6 0 0 15 0 0]斡La insegura y d姻bil Sumire...[n]morir茨 hoy![n][f 1 2 120][e]

[msg MSG_019_0_0 [Haru]]
[s][vp 6 0 0 16 0 0]Violet...[n][f 1 2 25][e]

[msg MSG_021_0_0 [Sumire]]
[s][vp 6 0 0 17 0 0]T雨 eres de verdad, 斡solo t雨 te[n]mantuviste fiel a ti misma![n][f 1 2 115][e]

[msg MSG_022_0_0 [Sumire]]
[s][vp 6 0 0 18 0 0]斡Venga, Cendrillon![n][f 1 2 48][e]

[msg MSG_024_0_0 [Sumire]]
[s][vp 6 0 0 19 0 0]Si no me respondes ahora mismo...[n][f 1 2 65][e]

[msg MSG_025_0_0 [Sumire]]
[s][vp 6 0 0 20 0 0]斡夷C吋mo se har茨 realidad[n]nuestro sue隠o si no?![n][f 1 2 70][e]

[msg DVL_026_0_0 [Voz misteriosa]]
[s][vp 6 0 0 21 0 0]Cu茨nta tenacidad...[n][f 1 2 65][e]

[msg DVL_027_0_0 [Cendrillon]]
[s][vp 6 0 0 22 0 0]Parece que te sienta mejor que nunca.[n][f 1 2 120][e]

[msg DVL_028_0_0 [Cendrillon]]
[s][vp 6 0 0 23 0 0]Los zapatos de cristal[n]son s胤mbolo del 姻xito.[n][f 1 2 120][e]

[msg DVL_029_0_0 [Cendrillon]]
[s][vp 6 0 0 24 0 0]No solo para ti, tambi姻n para la otra[n]muchacha que yace en tu interior.[n][f 1 2 131][e]

[msg DVL_030_0_0 [Cendrillon]]
[s][vp 6 0 0 25 0 0]Yo soy t雨, t雨 eres yo...[n][f 1 2 95][e]

[msg DVL_031_0_0 [Cendrillon]]
[s][vp 6 0 0 26 0 0]夷Todo listo para el estreno?[n]斡Te est茨n esperando para el baile![n][f 1 2 115][e]

[msg MSG_032_0_0 [Sumire]]
[s][vp 6 0 0 27 0 0]斡Por supuesto![n][f 1 2 27][e]

