[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Has venido.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]A juzgar por esa mirada,[n]intuyo que tus amigos[n]no nos van a ser de utilidad.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Seguro que vendr茨n.[e]
[s]夷Alg雨n problema?[e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Claro, os llev茨is tan bien[n]como antes de que[n]la realidad cambiase.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Cuanta m茨s gente, mejor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 0 0 5 65535 0]Esperaba que, al menos, alguno de ellos[n]no resultara in雨til, pero parece que[n]eso es pedir demasiado.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]En fin, no sirve de nada[n]darle vueltas.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Todo listo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Como dije ayer, es m茨s que probable[n]que tengamos que enfrentarnos[n]a Maruki f胤sicamente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Si todav胤a no est茨s listo,[n]mejor que te ocupes[n]de tus asuntos cuanto antes.[n][f 1 3 65535][w][e]

