[msg MSG_000_0_0 [Nakaoka]]
[s][vp 8 2 0 0 65535 0]Hala... 斡夷Esa universidad[n]se ha fijado en ti?![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 0 7029 65535 0]斡Cierra el pico, idiota![n][f 1 3 65535][w][e]
[s][bup 0 2 200 0 0][f 4 10 65535 0 0][f 4 24 0 4 6 59 5 100][f 4 24 0 4 2 5 5 100][vp 8 2 0 0 65535 0]Todav胤a no es seguro.[n]Solo digo que el instituto[n]se ha enterado de algo as胤.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Takeishi]]
[s][vp 8 2 0 0 65535 0]斡T胤o, pero aun as胤! 斡Si hasta te[n]subiste al podio en los nacionales![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Nakaoka]]
[s][vp 8 2 0 0 65535 0]Me preocupaba qu姻 pasar胤a contigo[n]despu姻s de que te reventaras la rodilla,[n]pero me alegro de que te recuperaras.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 0 7037 65535 0]No exageres. Solo estoy esforz茨ndome[n]al m茨ximo para que[n]los del equipo no os riais de m胤.[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 1 0 0 0 0 0]Ryuji se lo est茨 pasando pipa con los[n]dem茨s miembros del equipo de atletismo.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Dir胤a que esta es la realidad[n]que Ryuji anhelaba.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 200 0 0][f 4 10 65535 0 0][vp 8 2 0 7183 65535 0]夷[f 4 2]? 夷T雨 qu姻 haces aqu胤?[n]Estamos de vacaciones.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Nakaoka]]
[s][vp 8 2 0 0 65535 0]Ah, quiz茨 tambi姻n se ha pasado[n]para felicitarte.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Takeishi]]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]T胤o, este est茨 que se sale.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Quieres ir a comer a alg雨n lado[n]despu姻s de entrenar? 斡Te invitamos![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Anda! Qu姻 amables... Me apetece[n]un bol de ternera extragrande y[n]sopa de miso con cerdo.[n][f 1 3 65535][w][e]

[msg MSG_009_5_0 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][vp 8 2 0 0 65535 0]Oye, 夷por qu姻 no te vienes,[n][f 4 2]?[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]夷Feliz por poder correr de nuevo?[e]
[s]夷Disfrutando de tu regreso a las pistas?[e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]夷Eh? S胤, claro, pero...[n][f 1 3 65535][w][e]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 2 0 0 65535 0]夷A qu姻 viene esto de repente?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 0 7022 65535 0]S胤, est茨 guay,[n]pero 夷a d吋nde quieres llegar?[n][f 1 3 65535][w][e]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][f 4 24 0 4 2 9 5 100][vp 8 2 0 0 65535 0]Esto es lo que me va. Necesito[n]correr para no venirme abajo.[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]夷Te gusta esta realidad?[e]
[s]夷Ya tienes bien la pierna?[e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 204 65535 0][f 4 10 65535 0 0][vp 8 2 0 7189 65535 0]夷Q-que si me gusta?[n]Ja, ja, 夷de qu姻 narices est茨s hablando?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A ver..., el a隠o pasado crec胤[n]mogoll吋n. De lo contrario,[n]hoy ser胤a otra persona.[n][f 1 3 65535][w][e]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 38 5 100][vp 8 2 0 0 65535 0]Un momento, 夷qu姻...?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 0 7080 65535 0]Mi pierna... Anda, 夷te preocupas por[n]m胤? 斡Estoy bien, hombre! No me ha[n]pasado nada desde aquella lesi吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Y eso fue culpa de Kamoshida,[n]as胤 que... Calla. 夷Qu姻?[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Aqu胤 pasa algo, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pero, 夷de qu姻 nos conocemos? Nos[n]vimos por primera vez en la estaci吋n[n]del instituto y entonces...[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]Pi姻nsatelo mejor, t胤o.[e]
[s]Te estar姻 esperando.[e]

[msg MSG_019_0_0 [Ryuji]]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 2 0 7174 65535 0]Eh... Claro.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][vp 8 2 0 0 65535 0]Es ahora o nunca...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]斡All茨 va! 斡Aaaaaaah![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 5 300 1][vp 8 2 0 7040 65535 0]斡Hala! 夷Qu姻 narices ha sido eso?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Nakaoka]]
[s][vp 8 2 0 0 65535 0]夷Est茨s bien, Sakamoto?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Takeishi]]
[s][vp 8 2 0 0 65535 0]S胤, 夷qu姻 os pas吋[n]en la estaci吋n?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][bup 0 2 204 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eh, 斡nada![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 2 0 7062 65535 0]Lo siento, tengo que volver[n]a entrenar. 斡Nos vemos![n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 1 0 0 0 0 0]...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]Lo 雨nico que puedo hacer[n]es esperar.[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 1 0 0 0 0 0]Deber胤a volver a casa...[n][f 1 3 65535][w][e]

