[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 810 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Creo que eso es todo.[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷D吋nde estamos?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Esta sala es muy diferente al resto[n]del Palacio...[n]y estaba mejor custodiada.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 2 0 2127 65535 0]夷Ser茨 una especie[n]de sala de vigilancia?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Los monitores muestran varias[n]salas del Palacio.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][vp 8 2 0 6184 65535 0]Espera, 夷nos han estado vigilando[n]todo este tiempo?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No sabr胤a decirte.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][vp 8 2 0 9135 65535 0]斡S胤! Lo sab胤a. Esta sala sirve[n]m茨s como sistema central que[n]como sistema de supervisi吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aqu胤 se recoge todo tipo[n]de informaci吋n del Palacio y se[n]convierte en datos sin procesar. [n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 104 0 0][f 4 10 65535 0 0][vp 8 2 0 4090 65535 0]夷Recolecci吋n de datos? 夷Para qu姻?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 100 0 0][f 4 10 65535 0 0][vp 8 2 0 7115 65535 0]Esta sala no nos va a llevar[n]a ning雨n sitio. 夷Y si nos buscamos[n]la vida por otro lado?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece que hay un camino pasando[n]esos cables, aunque no lo tengo[n]del todo claro, la verdad.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][vp 8 2 0 6189 65535 0]夷Eh? 夷Y ahora qu姻?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Eso es Mementos...?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][vp 8 2 0 9034 65535 0]斡He dado con la ubicaci吋n destino[n]de toda la informaci吋n![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Parece que se dirige[n]hacia Mementos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Quiz茨 hagamos alg雨n avance[n]si investigamos este lugar.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Acabo de recordar algo.[n]Lavenza nos dijo que...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El doctor Maruki est茨 usando[n]Mementos para distorsionar[n]la realidad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Aun as胤, 夷en serio son cables[n]de informaci吋n?[n][f 1 3 65535][w][e]

[sel SEL_013_0_0 top]
[s]Vamos a Mementos.[e]
[s]Aqu胤 no se nos ha perdido nada.[e]

[msg MSG_014_0_0 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][vp 8 2 0 9128 65535 0]Estoy de acuerdo.[n]Quedarnos de brazos cruzados[n]no servir茨 de nada.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Primero hay que pirarse de aqu胤.[n]Qui姻n sabe, a lo mejor el viaje[n]a Mementos nos sienta bien.[n][f 1 3 65535][w][e]

