[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Se隠orita Lavenza...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Hola. Gracias por venir.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]Gracias a ti por venir.[e]
[s]Bueno, me lo has pedido.[e]
[s]夷Y estas formalidades?[e]

[msg MSG_003_0_0 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Entiendo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Intercambiar expresiones coloquiales[n]como hacen los humanos[n]es muy agradable, a decir verdad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Pero eso ahora es irrelevante.[n]Centr姻monos en lo que nos ocupa.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Lavenza]]
[s][bup 0 100 3 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]夷Eh?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Cre胤a que los humanos intercambiabais[n]tales expresiones cuando os ve胤ais.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Pero eso ahora no importa.[n]Centr姻monos en lo que nos ocupa.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Qu姻 extra隠o. Cre胤a que los humanos[n]intercambiabais tales expresiones[n]cuando os ve胤ais.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]夷Habr胤a sido m茨s apropiado[n]decir 或Qu姻 pasa, tronco位?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Mmm, esto...[n]夷No deber胤amos empezar?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Como te dije ayer,[n]me gustar胤a explicarte algo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Pero antes debes traer[n]a tus amigos.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]夷Aqu胤? 夷Quieres quedar[n]en la enfermer胤a?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Este lugar est茨 lleno de la cognici吋n[n]del 或reposo absoluto位.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Mantener mi existencia en una[n]realidad controlada por Maruki[n]no es tarea f茨cil.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Pero el agotamiento que induce est茨 limitado[n]por la cognici吋n de este sitio,[n]as胤 que aqu胤 puedo hablaros en persona.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Bueno...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Lavenza]]
[s][bup 0 100 8 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Prosigamos la conversaci吋n cuando[n]los involucrados nos hayamos reunido.[n][f 1 3 65535][w][e]
[s][bup 0 100 9 0 0][f 4 10 65535 0 0][f 4 24 0 4 1 1 10 40][vp 8 0 0 20 65535 0]Hasta entonces, me tomar姻[n]un merecido descanso.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]夷C吋mo que 或descanso位? 夷Se隠orita Lavenza...?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [(SE)ラヴェンツァ]]
[s][vp 8 0 0 0 65535 0](寝息)[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 3 0 0][vp 1 0 0 22 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]No nos queda otra que traer a los dem茨s.[n][f 1 3 65535][w][e]

