[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Bueno, intentemos lidiar[n]con esta situaci吋n.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷Qu姻 haces aqu胤?[e]
[s]夷Qu姻 est茨 pasando?[e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Es un buen sitio para empezar,[n]la verdad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]A finales del a隠o pasado, me entregu姻[n]a la polic胤a y confes姻 ser responsable[n]de los episodios de descontrol.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Eso lo recuerdas a la perfecci吋n,[n]夷me equivoco?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]S胤.[e]
[s]Pero... 夷c吋mo sigues con vida?[e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Ah, s胤.[n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Akechi]]
[s][vp 8 0 0 54 65535 0]Mi enemigo final es una marioneta[n]basada en m胤 mismo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 55 65535 0]斡Yo...![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][vp 8 0 0 6 65535 0]Mi enemigo final es una marioneta[n]basada en m胤 mismo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 65535 0]No est茨 mal.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Ahora mismo tenemos otros problemas.[n]De hecho, me molesta que me dieras[n]por muerto. Qu姻 poca fe.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]La parte m茨s confusa es, quiz茨, la que[n]viene despu姻s del arresto.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Evidentemente, me interrogaron a fondo[n]sobre el caso de Shido...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Pero, por alg雨n motivo, despu姻s de eso[n]me dejaron irme. Sin ning雨n tipo[n]de explicaci吋n.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s]Es muy extra隠o.[e]
[s]夷Te dejaron libre?[e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Estoy de acuerdo. Lo mire como lo mire,[n]no entiendo por qu姻 me dejaron[n]irme.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Y retiraron todos los cargos.[n]Es totalmente absurdo.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Es m茨s, no deber胤an poder poner[n]en libertad a un sospechoso que[n]ha confesado tras un interrogatorio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Lo m茨s incre胤ble de todo es...[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]Wakaba.[e]
[s]Morgana.[e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Eso es.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Efectivamente, eso es peculiar,[n]pero lo m茨s inusual es...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Wakaba Isshiki.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]No me puedo creer que haya vuelto a la vida...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]De momento, parece que t雨 eres[n]el 雨nico que sigue cuerdo[n]por aqu胤.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Deber胤a ir al grano.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Hagamos un trato.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]夷Y si unimos nuestras fuerzas?[n][f 1 3 65535][w][e]

[sel SEL_021_0_0 top]
[s]夷Qu姻 hacemos?[e]
[s]No conf胤o en ti.[e]
[s]Deja que me lo piense.[e]

[msg MSG_022_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Quiero descubrir qu姻 est茨[n]pasando aqu胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Estoy bastante seguro de que t雨[n]compartes mi inter姻s, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Bueno, lo entiendo...[n][f 1 3 65535][w][e]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Pero teniendo en cuenta las circunstancias,[n]creo que es mejor dejar de lado el rencor[n]y trabajar juntos.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Vaya, es extra隠o que seas tan[n]cauto. No creo que tengamos tiempo[n]para que le des muchas vueltas.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]De momento, tenemos[n]el mismo objetivo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Para solucionar este problema,[n]夷no ser胤a mejor trabajar juntos?[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Tiene raz吋n, hay que trabajar en equipo[n]para lidiar con semejante situaci吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ser茨 mejor colaborar[n]con Akechi.[n][f 1 3 65535][w][e]

[msg MSG_026_5_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]夷Te has decidido?[n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s]Parece que no tengo elecci吋n.[e]
[s]夷Qu姻 tengo que hacer?[e]

[msg MSG_028_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Deja que te recuerde que en esta[n]empresa somos iguales, 夷entendido?[n]Bueno, vamos al tema en cuesti吋n.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Pues...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Primero necesitamos informaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Cu姻ntame qu姻 pas吋 despu姻s de que nos...[n]separ茨ramos en el Palacio de Shido.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Entiendo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Aunque algunas cosas paranormales[n]surgieron antes, la mayor胤a se dieron[n]despu姻s de A隠o Nuevo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Y todos los Ladrones Fantasma, excepto[n]t雨, est茨n viviendo esa realidad alterada[n]sin darse cuenta...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Adelante.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Kasumi]]
[s][bup 0 10 0 65535 1][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]夷Hola? 斡Soy Yoshizawa![n][f 1 3 65535][w][e]
[s][bup 0 10 4 65535 1][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Ahora mismo estoy en Odaiba y... eh...[n][f 1 3 65535][w][e]

[sel SEL_034_0_0 top]
[s]Tranquil胤zate.[e]
[s]夷Qu姻 ha ocurrido?[e]

[msg MSG_035_0_0 [Kasumi]]
[s][bup 0 10 3 65535 1][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]No entiendo muy bien qu姻 estoy[n]viendo, pero te lo describir姻...[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Kasumi]]
[s][bup 0 10 3 65535 1][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Es aquel edificio...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]No es muy n胤tido, pero puedo distinguir[n]el Palacio ese que mencion吋 Morgana[n]hace tiempo.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Kasumi]]
[s][bup 0 10 3 65535 1][f 4 10 65535 0 0][vp 8 0 0 45 65535 0][f 4 1], s姻 que es repentino,[n]pero 夷podr胤as venir a Odaiba?[n][f 1 3 65535][w][e]

[sel SEL_038_0_0 top]
[s]Ya voy.[e]
[s]Esp姻rame all胤.[e]

[msg MSG_039_0_0 [Kasumi]]
[s][bup 0 10 0 65535 1][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Vale. 斡Ahora nos vemos![n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Esa era Yoshizawa,[n]夷me equivoco?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Creo haber o胤do la palabra[n]或Palacio位.[n][f 1 3 65535][w][e]

[sel SEL_041_0_0 top]
[s]Alguno habr茨 visto.[e]
[s]No te dejes enga隠ar.[e]

[msg MSG_042_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]夷Aunque no est姻 en el Metaverso?[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]夷T雨 sabes lo que significa[n]或trabajar juntos位?[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Vas a ir a ver a Yoshizawa,[n]夷verdad?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Voy contigo. No dudo que encontraremos[n]alguna pista.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]Ahora que hemos hecho un trato,[n]no me dir茨s que no, 夷verdad?[n][f 1 3 65535][w][e]

