[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 13 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Pas姻 mucho tiempo investigando[n]a la gente que te rodeaba para[n]tenderte una trampa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Y pensar que Takuto Maruki[n]manejaba los hilos[n]de esta absurda situaci吋n...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Est茨 distorsionando toda la realidad[n]porque, seg雨n 姻l, aspira a hacer[n]realidad los sue隠os de todo el mundo.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Qu姻 motivos tan incomprensibles...[n]Ni siquiera puedo entender[n]sus intenciones.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Sea como sea, tenemos que definir[n]nuestros pr吋ximos pasos.[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]Sumire me preocupa.[e]
[s]Tenemos que salvar a Sumire.[e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Creo que ser胤a un suicidio regresar all胤[n]de momento.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷No crees que ser胤a un suicidio intentar[n]salvarla en nuestro estado actual?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]...丸喜拓人か。[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]秀尽のカウンセラーだったっけ?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]よく調べたな[e]
[s]何故それを?[e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]一応、探偵だからね。[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]敵対して...しかも♀に♀めて[n]殺そうとしてた相手の周囲ぐらい調べるよ。[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]僕は君を、♀に♀めて殺そうとしてたんだよ?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]その男の個人情報を調べることぐらい、[n]当然だと思わない?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Debemos recabar informaci吋n. Si vamos[n]a plantarle cara, tenemos que[n]saber algo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Indagar姻 por mi cuenta.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Odio tener que hacerle caso, pero Maruki[n]nos dijo que deb胤amos esperar[n]hasta el 9 de enero.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Nos vemos aqu胤 la semana que viene.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Aunque imagino que nuestras vidas ser茨n[n]muy diferentes si optas por vivir[n]en esta realidad, como tus amigos.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]As胤 que esta es la realidad que ha creado Maruki...[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]No tiene sentido obsesionarse.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Deber胤a volver a mi habitaci吋n.[n][f 1 3 65535][w][e]

