[msg MSG_000_0_0 [Futaba]]
[s][bup 0 8 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No esperaba que recibi姻ramos algo[n]a cambio por lo de ayer.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tengo unas ganas de ver lo que es...[n]Pero 夷d吋nde est茨?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hab胤a que venir a esta hora, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sumire]]
[s][bup 0 10 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seguro que ha planeado algo.[n]Imaginaos que...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Eh? 夷Qu姻 est茨 pasando?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡夷Sae?![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El Jefe me pidi吋 ayer que me pasara[n]para liderar la velada[n]como la 雨ltima vez.[n][f 1 3 65535][w][e]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Y bien? 夷Est茨is listos?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Estupendo, parece que sobran[n]las preguntas. 斡Empecemos![n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Empieza el espect茨culo.[e]
[s]Es para vosotras.[e]

[msg MSG_009_0_0 [(SE)女性たち]]
[s][vp 8 0 0 0 65535 0]キャー! などの歓声[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Hifumi]]
[s][bup 0 106 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eh... 斡Aqu胤 tambi姻n, por favor![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Chihaya]]
[s][bup 0 113 6 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡[f 4 1]![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Futaba]]
[s][bup 0 8 6 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Ostras, Joker, c吋mo molas![n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][bup 0 6 7 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No me puedo creer que hayas hecho[n]todo esto por nosotras.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]Esto no ha acabado.[e]
[s]Todav胤a hay m茨s.[e]

[msg MSG_015_0_0 [Makoto]]
[s][bup 0 6 6 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Ja! 斡Con raz吋n eres[n]un Ladr吋n Fantasma de primera![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ann]]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤, por lo que veo,[n]nos has robado el coraz吋n a todas.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Futaba]]
[s][bup 0 8 6 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡[f 4 2]! 斡Yo tambi姻n[n]quiero chocolate, porfi![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Kawakami]]
[s][bup 0 109 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Las fans quieren m茨s! 斡Venga![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Muchas gracias por el regalo.[n][f 1 3 65535][w][e]

[sel SEL_020_0_0 top]
[s]He venido a robaros el coraz吋n.[e]
[s]Lo que sea por vosotras, se隠oritas.[e]

[msg MSG_021_0_0 [Haru]]
[s][bup 0 7 6 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Jo, venga...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Futaba]]
[s][bup 0 8 7 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mmmm... No s姻 por qu姻, pero parece[n]que hoy, digas lo que digas,[n]tienes raz吋n.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ohya]]
[s][bup 0 107 6 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Trae un trozo[n]de ese corazoncito, grandull吋n![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Sumire]]
[s][bup 0 10 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡夷Y por aqu胤 tambi姻n, por favor?![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Takemi]]
[s][bup 0 108 506 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es una superestrella.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Sumire]]
[s][bup 0 10 1 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nunca imagin姻 que conseguir胤amos[n]un regalo as胤... 斡Qu姻 alegr胤a![n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s]Feliz D胤a Blanco.[e]
[s]La noche a雨n es joven.[e]

[msg MSG_028_0_0 [Sumire]]
[s][bup 0 10 4 4 0][vp 8 0 0 0 0 0]斡...![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Futaba]]
[s][bup 0 8 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡A Sumire se le est茨 yendo la olla![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Sumire]]
[s][bup 0 10 4 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*grito ahogado* Ay, perdona...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Haru]]
[s][bup 0 7 6 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*risita* No te disculpes. Todas[n]pensamos lo mismo de [f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ann]]
[s][bup 0 4 6 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y que lo digas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No me esperaba semejante[n]regalazo por el D胤a Blanco.[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Parece que he estado a la altura[n]de las expectativas.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Makoto]]
[s][bup 0 6 6 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pasamos un San Valent胤n incre胤ble[n]y el D胤a Blanco[n]est茨 siendo alucinante.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Futaba]]
[s][bup 0 8 6 4 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡S胤! 斡Ese es nuestro [f 4 2]![n][f 1 3 65535][w][e]

