[msg MSG_Clean_Start [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hm, ahora est茨 mucho m茨s limpio.[n]El Jefe estar茨 contento.[n][w][e]
[s]Pensar en los clientes[n]y limpiar el Leblanc ha contribuido[n]a aumentar tu [f 4 11 4][clr 26][f 4 12 4][clr 27], 夷no?[n][w][e]

[msg MSG_Clean_End [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bien hecho.[n]Creo que ya es suficiente.[n][w][e]

