[msg MSG_012_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Al fin lo he conseguido...[n]Ya hace dos a隠os y medio[n]que nos conocemos.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Antes llamaba la atenci吋n[n]de los medios porque era joven[n]y se opon胤a a la burocracia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Por eso, los que quer胤an ocuparse[n]preventivamente de los problemas[n]intentaban meterlo en esc茨ndalos.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Shido]]
[s][bup 0 206 5 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Y pensar que ca胤 en la trampa[n]de unos est雨pidos decr姻pitos[n]que estaban en el poder...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Recuerdo que fue entonces cuando[n]me buscaste. Me dijiste que ten胤as[n]poderes especiales.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]De no haber sido por toda[n]mi investigaci吋n sobre la cognici吋n,[n]te habr胤a tachado de demente.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Volv胤 locos a sus problem茨ticos[n]oponentes y elimin姻 todo rastro[n]del esc茨ndalo.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]夷Qui姻n iba a pensar que manipular[n]un coraz吋n provocar胤a un lapsus[n]psic吋tico o una desconexi吋n mental?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Y, cuando alguien as胤 dijo que[n]me ayudar胤a, sospech姻 que habr胤a[n]alg雨n prop吋sito detr茨s.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Es porque apoyaba su ideolog胤a.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Cre胤a que sus ideales deb胤an[n]cumplirse por el bien del futuro[n]de este pa胤s.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Gracias a mi fe en ti,[n]acab姻 con la investigaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Solo t雨 puedes usar el poder.[n]Si alguien m茨s descubre[n]c吋mo funciona, tendremos problemas.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Se llamaba Wakaba Isshiki, 夷no?[n]La investigadora, digo.[n]Seguir胤a viva si hubiera obedecido.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Toda sospecha debe de ser[n]eliminada. Hay que arrancar de ra胤z[n]hasta la m茨s m胤nima duda.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Hasta hace poco[n]ten胤amos al director[n]de la Fiscal胤a de nuestro lado.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]Es incre胤ble, 夷no?[n]Que el director falsificara[n]pruebas para ascender.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Se sorprendi吋 cuando se enfrent吋[n]a 姻l por eso. No sab胤a qui姻n hab胤a[n]filtrado la informaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Lo ir吋nico es que me lo cont吋[n]su sombra, as胤 que t姻cnicamente[n]fue 姻l quien me lo dijo.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Shido]]
[s][bup 0 206 5 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Este pa胤s se ha quedado estancado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]El mundo de la pol胤tica est茨 lleno[n]de carcamales que solo buscan[n]mantener sus propios intereses.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Y la gente de a pie pasa[n]de los asuntos pol胤ticos.[n]Estamos perdidos.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Pienso lo mismo.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]No hay por qu姻 caer junto a esos[n]necios incompetentes. Yo liderar姻[n]y revivir姻 el pa胤s.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Aquellos que se interpongan[n]en mi camino ser茨n eliminados...[n]Para eso sirve el Metaverso.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Pero no conviene que haya tantas[n]muertes y esc茨ndalos entre sus[n]rivales. Llamar胤a la atenci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Por eso los he convertido[n]en sospechosos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Denunci姻 a los objetivos que volv胤[n]psic吋ticos y lo resolv胤 todo como[n]si fuesen casos ajenos a usted.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Akechi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 10 300 1][vp 8 0 0 26 65535 0]Y as胤 es como naci吋 el carism茨tico[n]superdetective.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Shido]]
[s][bup 0 206 1 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Gracias a tu ayuda, mi imagen sigue[n]siendo honrada y he monopolizado[n]la opini吋n p雨blica.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]En cuanto me gan姻 el cari隠o de la[n]gente, varios colaboradores de[n]todos los sectores se me acercaron.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]Incluida la polic胤a.[n]Como la ten胤a en el bolsillo,[n]controlarla fue tarea f茨cil.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Pensaba que la cosa se pondr胤a[n]complicada cuando aparecieron[n]los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Shido]]
[s][bup 0 206 1 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Pero descubrimos[n]que eran unos cr胤os. Solo hubo[n]que echarles la culpa de todo.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Cuando me lo cont吋,[n]supe que hac胤a lo correcto.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Eran m茨s populares de lo esperado,[n]pero por eso el impacto negativo[n]de la prensa fue mayor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Despu姻s, solo tuve que criticarlos[n]abiertamente. No he parado de ganar[n]seguidores desde entonces.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]El gobierno tiene los d胤as contados[n]por culpa de los esc茨ndalos,[n]cosa que tambi姻n fue obra m胤a.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Hasta los partidos gubernamentales[n]se est茨n separando y disolviendo.[n]Todo va seg雨n lo planeado.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [(SE)獅童 正義]]
[s][vp 8 0 0 35 65535 0](抑えきれない笑いがこみ上げる)[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Por fin ha llegado la hora.[n]Queda muy poco para que el puesto[n]de primer ministro sea m胤o.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Pero la investidura en s胤 no es[n]mi meta. Eso solo es el principio[n]de mi verdadero plan.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Har姻 rico a este pa胤s por el bien[n]de las masas ego胤stas e ignorantes[n]que no saben valerse por s胤 mismas.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]En otras palabras, va a crear[n]un poderoso pa胤s que pueda[n]competir con el resto del mundo.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Shido]]
[s][bup 0 206 1 0 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]La gente simpatiza con mis ideales[n]y me sigue.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]Por eso, algunos sacrificios[n]son inevitables.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Ese es mi deber[n]como el elegido que soy.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]Tu ayuda ha sido vital[n]para que mis planes se desarrollen[n]sin complicaciones.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]Cuando sea primer ministro,[n]te conceder姻 cualquier deseo.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]Gracias al 雨ltimo caso, todo[n]el pa胤s conoce mi nombre, incluso[n]puede que el mundo entero.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Seguramente mi historia ser茨 la de[n]un h姻roe que venci吋 a los monstruos[n]que controlaban corazones.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Intentar姻 pasar desapercibido[n]y me centrar姻 en los estudios.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Supongo que con tu edad[n]no tendr茨s deseos corruptos.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Akechi]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 9 10 300 1][vp 8 0 0 49 65535 0]Pero s胤 que estoy pensando[n]en el futuro.[n][f 1 3 65535][w][e]

