[msg MSG_000_0_0 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 7 300 1][vp 8 0 0 1 65535 0]斡夷Shido es el t胤o que te la jug吋?![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]夷Qu姻 aciago destino[n]os ha reunido de nuevo?[n][f 1 3 65535][w][e]

[sel SEL_001_5_0 top]
[s]S胤 que es 姻l.[e]
[s]Ya me gustar胤a a m胤 saberlo.[e]
[s]夷Ser茨 casualidad?[e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Esto s胤 que es el destino...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Shido tambi姻n estaba involucrado[n]en la investigaci吋n cognitiva, 夷no?[n]No puede ser casualidad.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Madre m胤a, 夷qu姻 narices[n]est茨 pasando aqu胤?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Shido ya era pol胤tico entonces,[n]夷y aun as胤 denunci吋 a un[n]estudiante y le arruin吋 la vida?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Mover胤a algunos hilos[n]para que su nombre[n]no saliera a la luz...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Adem茨s, seguro que oblig吋 a la[n]mujer a mentir en su declaraci吋n.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Har胤a cualquier cosa. Hablamos[n]de un hombre que mand吋 asesinar[n]a alguien en una comisar胤a.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]No se queda tranquilo hasta que[n]aplasta al que se le oponga.[n]Siempre ha sido as胤.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 3 301 1][vp 8 0 0 10 65535 0]斡Menudo desgraciado![n][f 1 3 65535][w][e]

[msg MSG_008_5_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]或Los ni隠os son el futuro位, 斡y una[n]mierda! 斡Lo que dice y lo que[n]hace es totalmente diferente![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Ahora que sabemos qui姻n lo hizo,[n]夷se puede hacer algo con los[n]antecedentes de [f 4 2]?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Cuando los juzgados dictan[n]sentencia, es dif胤cil que[n]revoquen su decisi吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Ser胤a complicado hasta[n]con pruebas de inocencia[n]y con la confesi吋n de Shido.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]En cualquier caso, tenemos que[n]despertar su coraz吋n.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Es que lo que Shido aparenta[n]y su verdadera forma de ser[n]son diferentes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Es m茨s que hip吋crita.[n]Es como si fuera[n]una persona diferente.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Habla de lo bueno del pa胤s...[n]夷Qu姻 tendr茨 en realidad[n]en la cabeza?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Todo lo que tiene es ambici吋n[n]por llegar cada vez m茨s alto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Ve a los d姻biles como meros[n]escalones para alcanzar la cima.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Se cree que es superior y que[n]est茨 por encima de los dem茨s...[n]Es lo peor.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Seguro que la palabra clave para[n]lo que cree que es el Edificio[n]de la Dieta es despreciable.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Ser茨 algo muy ego胤sta[n]y que no tenga relaci吋n[n]con la pol胤tica.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Haru]]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]斡Hay que castigar a la gente[n]como 姻l lo antes posible![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 3 300 1][vp 8 0 0 25 65535 0]Vamos al Edificio de la Dieta[n]ma隠ana despu姻s de clase.[n]斡Esta vez lo conseguiremos![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Quej茨ndonos no conseguiremos nada.[n]Hay que ponerse en marcha.[n][f 1 3 65535][w][e]

