[msg MSG_000_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Es hora de reconstruir[n]esta naci吋n en ruinas![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Nuestro gobierno est茨 hasta[n]arriba de esc茨ndalos y los[n]delincuentes andan sueltos![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Hay que dejar atr茨s un pasado[n]as胤... 斡Tenemos que navegar[n]hacia un nuevo futuro de esperanza![n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [(SE)群衆]]
[s][vp 8 0 0 0 65535 0](SE)歓声[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Anciano]]
[s][vp 8 0 0 0 65535 0]夷Shido? 斡夷Shido?![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ama de casa]]
[s][vp 8 0 0 0 65535 0]斡夷Est茨 aqu胤?! 斡夷D吋nde?![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [若者]]
[s][vp 8 0 0 0 65535 0]斡Hala, es incre胤ble![n]斡Vamos a ver![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Para que nuestros hijos, que[n]son la siguiente generaci吋n,[n]est姻n orgullosos de su pa胤s![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Para que nuestra naci吋n sea[n]otra vez poderosa y cuente[n]con riquezas y lujos![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Para que nuestro precioso hogar[n]sea reconocido como el mejor[n]pa胤s del mundo![n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [(SE)群衆]]
[s][vp 8 0 0 0 65535 0](SE)歓声[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ni隠o]]
[s][vp 8 0 0 0 65535 0]夷Ese es Shido?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Madre]]
[s][vp 8 0 0 0 65535 0]S胤. 斡Es un hombre[n]fuerte y admirable![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ni隠o]]
[s][vp 8 0 0 0 65535 0]夷M茨s que pap茨?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Padre]]
[s][vp 8 0 0 0 65535 0]Mmm, bueno, dir胤a que s胤.[n]Shido es una persona maravillosa.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Shido]]
[s][bup 0 206 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Me dejar姻 la piel[n]para que nuestros ciudadanos[n]disfruten de una vida de calidad![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [(SE)群衆]]
[s][vp 8 0 0 0 65535 0](SE)ひときわ大きな歓声[n][f 1 3 65535][w][e]

