[msg MSG_000_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Los criminales conocidos[n]como los 或Ladrones Fantasma位[n]han desaparecido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Desafortunadamente, estoy convencido[n]de que hay gente que todav胤a[n]vive angustiada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Los esc茨ndalos solo agravan[n]la desconfianza hacia el gobierno.[n]斡Como ciudadano, estoy indignado![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Le dijo la sart姻n al cazo.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]夷Qu姻 significa ser un pol胤tico[n]con responsabilidad?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]斡Trabajar por el beneficio propio[n]dejando de lado al pa胤s[n]es intolerable![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]El aviso p雨blico de las elecciones[n]es ma隠ana, y vaya adonde vaya,[n]todo el mundo apoya a Shido.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Se dejan tomar el pelo[n]con una facilidad...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]斡Para salvar a este pa胤s[n]mancillado por los malvados,[n]es necesaria una reforma social![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Uf...[n][f 1 3 65535][w][e]

