[msg MSG_000_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Eso son ba隠adores?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Y son de mujer...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Esto tambi姻n forma parte[n]de la cognici吋n de Shido?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Uf, qu姻 asco de hombre,[n]y no solo por esto...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A decir verdad,[n]despu姻s de acosar a una mujer,[n]esto no deber胤a sorprendernos.[n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tanto hablar sobre ba隠adores[n]me recuerda a las piscinas...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Uno de los vips suele estar[n]en la piscina. Me he enterado[n]de que es un exnoble.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Debido a su orgullo[n]y su abolengo, ser茨 dif胤cil[n]tratar con 姻l con normalidad.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Si no se nos ocurre alg雨n[n]tipo de plan elaborado, es[n]probable que ni nos escuche.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Tengo una idea![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tengo un mal presentimiento.[n]夷Qu姻 idea es esa, Ryuji?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Primero, llevemos[n]estos ba隠adores a la piscina...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Os dir姻 cu茨l es el plan[n]cuando estemos all胤![n]斡Va a ser genial![n][f 1 3 65535][w][e]

