[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Vale, 斡tenemos la carta de recomendaci吋n![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]斡Ya solo nos faltan otras cuatro![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]斡Ya solo nos faltan otras tres![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]斡Ya solo nos faltan otras dos![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]斡Ya solo nos falta una m茨s![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Entiendo que, siendo parte de los[n]medios, conoce de sobra varios[n]temas de vital importancia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Si accede a compartir[n]la informaci吋n que le ha ocultado[n]a la gente, no lo mataremos.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sombra de presidente de TV]]
[s][vp 8 0 0 8 65535 0]夷Te acuerdas de Kaneshiro? Aquel[n]mafioso que fue noticia[n]no hace mucho.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 65535 0]Pues bien, todo el dinero que hab胤a[n]conseguido acab吋 en manos[n]de Shido.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]夷Shido y Kaneshiro estaban relacionados?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sombra de presidente de TV]]
[s][vp 8 0 0 11 65535 0]Exacto. Y tambi姻n el viejo[n]de Madarame.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 12 65535 0]El negocio de falsificaciones[n]y la mafia de Kaneshiro ayudaron[n]mucho econ吋micamente a Shido.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Ahora lo entiendo...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Usted hizo que en la tele no[n]pararan de hablar sobre Goro[n]y Shido, 夷no? 斡Hasta en la sopa![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Espera, pero si este pavo no es[n]ni real. No va a servir para nada[n]decirle todo esto.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Haru]]
[s][bup 0 7 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]斡Venga! 斡Hay que acabar con Shido![n][f 1 3 65535][w][e]

