[msg MSG_000_0_0 [Futaba]]
[s][bup 0 8 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]斡Toma ya! 斡Tenemos[n]una carta de recomendaci吋n![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][bup 0 8 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]斡Nos faltan cuatro![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][bup 0 8 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]斡Nos faltan tres![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][bup 0 8 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]斡Ya solo nos faltan dos![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]斡Ya solo nos falta una![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Lo del Medjed falso no fue[n]lo 雨nico que hiciste, 夷verdad?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Cu姻ntame tu secreto[n]mejor guardado.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sombra de presidente de TI]]
[s][vp 8 0 0 8 65535 0]Los estudios de psiencia cognitiva...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 4 16 8 3 301 1 65535][vp 8 0 0 9 65535 0]斡夷Qu姻 has hecho?! 斡Canta![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sombra de presidente de TI]]
[s][vp 8 0 0 10 65535 0]Tras extraer los resultados[n]de la investigaci吋n,[n]elimin姻 todo rastro de los datos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Luego lo encript姻 todo y lo colgu姻[n]en un dominio inaccesible[n]para el com雨n de los mortales.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]No me malinterpretes. No s姻 nada[n]sobre las desconexiones mentales.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Shido... 夷Qu姻 narices[n]estaba investigando?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][bup 0 8 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Fuera lo que fuera, 斡no dejaremos[n]que se aproveche de ello![n][f 1 3 65535][w][e]

