[msg MSG_000_0_0 [Detective]]
[s][vp 8 0 0 1 65535 0]夷D吋nde est茨 el cad茨ver[n]del Ladr吋n Fantasma?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sae]]
[s][bup 0 105 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]夷Qu姻 Ladr吋n Fantasma? 夷Qu姻 cad茨ver?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Detective]]
[s][vp 8 0 0 3 65535 0]斡No es momento para jueguecitos![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]No s姻 de qu姻 me est茨 hablando...[n][f 1 3 65535][w][e]

[msg MSG_003_3_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Ahora que me acuerdo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Recib胤 un aviso[n]de los Ladrones Fantasma...[n]pero luego est茨 todo borroso...[n][f 1 3 65535][w][e]

[msg MSG_003_6_0 [Sae]]
[s][bup 0 105 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]No... 斡夷He hecho algo mal?![n][f 1 3 65535][w][e]
[s][bup 0 105 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Entonces yo... yo...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [(SE)新島 冴]]
[s][vp 8 0 0 5 65535 0](『くっ』というような♀き)[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Detective]]
[s][vp 8 0 0 6 65535 0]斡夷Eh?![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Detective junior]]
[s][vp 8 0 0 7 6 0]夷Los Ladrones Fantasma[n]han llegado hasta ella?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Detective]]
[s][vp 8 0 0 8 65535 0]No me diga que su coraz吋n...[n]斡夷Es cierto, Niijima?![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Sae]]
[s][bup 0 105 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]夷Qu姻 he hecho?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Detective]]
[s][vp 8 0 0 10 65535 0]斡El Ladr吋n Fantasma! 斡Est茨 vivo![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Detective junior]]
[s][vp 8 0 0 11 6 0]Pero 夷c吋mo escap吋 de la comisar胤a?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Detective]]
[s][vp 8 0 0 12 65535 0]斡Eso no importa![n]斡Tenemos que atraparlo![n][f 1 3 65535][w][e]
[s][vp 8 0 0 13 65535 0]斡No podemos dejar que se corra[n]la voz! 斡Su suicidio fue una farsa[n]y encima se nos ha escapado![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Detective]]
[s][vp 8 0 0 14 65535 0]Tendremos que interrogarla...[n]como testigo principal.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Sae]]
[s][bup 0 105 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]夷Por qu姻 yo?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Detective]]
[s][vp 8 0 0 16 65535 0]Revise los documentos que elabor吋.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 17 65535 0]A lo mejor se acuerda de algo...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 18 65535 0]Pero aunque no recuerde nada, toda[n]la responsabilidad de su fuga[n]recaer茨 sobre usted.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Sae]]
[s][bup 0 105 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Lo siento, no entiendo[n]qu姻 est茨 ocurriendo...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Detective]]
[s][vp 8 0 0 20 65535 0]斡Es la 雨ltima persona que[n]habl吋 con el Ladr吋n Fantasma![n][f 1 3 65535][w][e]
[s][vp 8 0 0 21 65535 0]斡Usted pagar茨 el pato![n]斡Si quiere enfadarse con alguien,[n]que sea con su difunto director![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Sae]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 105 15 301 1][vp 8 0 0 22 65535 0]夷De verdad ha muerto[n]por una enfermedad?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]斡夷En serio se creen eso?![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Detective]]
[s][vp 8 0 0 24 65535 0]斡Eso da igual![n][f 1 3 65535][w][e]
[s][vp 8 0 0 25 65535 0]斡Se ha estado usted riendo[n]de la polic胤a y lo va a lamentar![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Muy bien.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Sae]]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]En vuestras manos est茨.[n][f 1 3 65535][w][e]

