[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*suspiro* 夷Por qu姻 tengo que[n]ir a hurtadillas?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Entrevistador de televisi吋n]]
[s][vp 8 0 0 0 65535 0]斡夷No es ese Akechi?![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [(SE)明智 吾郎]]
[s][vp 8 0 0 0 65535 0](舌打ち)[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Entrevistador de televisi吋n]]
[s][vp 8 0 0 0 65535 0]斡Akechi![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Nos gustar胤a saber qu姻 opinas[n]del comunicado de la polic胤a sobre[n]el suicidio del Ladr吋n Fantasma![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡夷Era un informe falso?![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Periodista del peri吋dico]]
[s][vp 8 0 0 0 65535 0]斡夷Es cierto que tu estratagema[n]condujo a su arresto?![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Entrevistador de televisi吋n]]
[s][vp 8 0 0 0 65535 0]斡Akechi![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Es culpa de los polic胤as que[n]lo dejaron escapar![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Entrevistador de televisi吋n]]
[s][vp 8 0 0 0 65535 0]Pero entonces, 斡夷c吋mo escap吋[n]el Ladr吋n Fantasma? 斡Nos encantar胤a[n]escuchar tu opini吋n, Akechi![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡No lo s姻![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Periodista del peri吋dico]]
[s][vp 8 0 0 0 65535 0]斡夷Y qu姻 pasa con Masayoshi Shido?![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Los Ladrones dijeron que estaba[n]detr茨s de los esc茨ndalos[n]y las desconexiones mentales.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Entrevistador de televisi吋n]]
[s][vp 8 0 0 0 65535 0]斡夷Es cierto que la polic胤a[n]estaba manipulando informaci吋n?![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡夷Me quer姻is dejar pasar?![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Entrevistador de televisi吋n]]
[s][vp 8 0 0 0 65535 0]斡夷Est茨n realmente los Ladrones[n]Fantasma de parte de la justicia?![n]Te han retado sin pa隠os calientes.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Basta, plebeyos![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [(SE)明智 吾郎]]
[s][vp 8 0 0 0 65535 0](自♀の笑いが大きくなる)[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Los Ladrones Fantasma...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Con 姻l solo no me basta...[n]斡Me los cargar姻 a todos![n][f 1 3 65535][w][e]

