[msg MSG_000_0_0 [Akechi]]
[s][vp 8 0 0 0 65535 0]夷Amigos?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Akechi]]
[s][vp 8 0 0 0 65535 0]斡No necesito nada de eso![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][vp 1 0 0 1 0 0]Mirad... Os demostrar姻[n]qui姻n soy realmente.[n][f 1 2 165][e]

[msg MSG_003_0_0 [Akechi]]
[s][vp 1 0 0 2 0 0]斡Ven![n][f 1 2 30][e]

[msg MSG_003_5_0 [Akechi]]
[s][vp 1 0 0 19 0 0]斡Loki![n][f 1 2 70][e]

[msg MSG_004_0_0 [Yusuke]]
[s][vp 6 0 0 3 7 0]斡Otra vez esa Persona![n][f 1 2 57][e]

[msg MSG_005_0_0 [Akechi]]
[s][vp 8 0 0 4 65535 0]斡Aaaaah![n][f 1 2 150][e]

[msg MSG_006_0_0 [Haru]]
[s][vp 6 0 0 5 9 0]斡夷Qu姻 est茨 pasando?![n][f 1 2 38][e]

[msg MSG_007_0_0 [Akechi]]
[s][vp 1 0 0 6 0 0]斡No me hag茨is re胤r![n][f 1 2 37][e]

[msg MSG_008_0_0 [Akechi]]
[s][vp 1 0 0 7 0 0]斡夷Justicia?! 斡夷Virtud?![n]斡No dig茨is gilipolleces![n][f 1 2 130][e]

[msg MSG_009_0_0 [Akechi]]
[s][vp 1 0 0 8 0 0]斡T雨 y tus compa隠eros me cabre茨is![n][f 1 2 115][e]

[msg MSG_010_0_0 [Morgana]]
[s][vp 6 0 0 9 5 0]夷Puede usar dos poderes distintos?[n][f 1 2 65][e]

[msg MSG_011_0_0 [Morgana]]
[s][vp 1 0 0 10 0 0]Entonces... 斡todo era falso,[n]hasta su aspecto![n][f 1 2 92][e]

[msg MSG_012_0_0 [Akechi]]
[s][vp 1 0 0 11 0 0]Vais a morder el polvo...[n]Os destruir姻...[n][f 1 2 130][e]

[msg MSG_013_0_0 [Akechi]]
[s][vp 1 0 0 12 0 0]斡Caed conmigo![n][f 1 2 70][e]

[msg MSG_014_0_0 [Ann]]
[s][vp 6 0 0 13 6 0]Anda ya...[n][f 1 2 25][e]

[msg MSG_015_0_0 [Ryuji]]
[s][vp 6 0 0 14 4 0]Ese cabr吋n... 斡Se ha vuelto[n]psic吋tico a prop吋sito![n][f 1 2 103][e]

[msg MSG_016_0_0 [(SE)明智 吾郎]]
[s][vp 1 0 0 15 0 0](絶叫するような笑い)[n][f 1 2 230][e]

[msg MSG_017_0_0 [Akechi]]
[s][vp 1 0 0 16 0 0]斡Ahora os ver姻 caer uno a uno[n]ante vuestros queridos amigos![n][f 1 2 175][e]

[msg MSG_018_0_0 [Morgana]]
[s][vp 1 0 0 17 0 0]斡Ha enloquecido! 斡Ah胤 viene![n][f 1 2 75][e]

[msg MSG_019_0_0 [Akechi]]
[s][vp 1 0 0 18 0 0]斡Moriiiid![n][f 1 2 78][e]

