[msg MSG_000_0_0 [(SE)獅童 正義]]
[s][vp 8 0 0 1 65535 0](改心させられそうになるうめき声)[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Lacayo de Shido joven]]
[s][vp 8 0 0 2 65535 0]斡Se隠or![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Shido]]
[s][bup 0 206 5 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]No... 夷Lo han logrado?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]斡Eh![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Investigador]]
[s][vp 8 0 0 5 5 0]斡S胤, se隠or![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]斡夷De verdad podr姻[n]matar a los Ladrones Fantasma[n]si me tomo esto?![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Investigador]]
[s][vp 8 0 0 7 5 0]Seg雨n la investigaci吋n[n]de Wakaba Isshiki...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 8 5 0]El derrumbe temporal[n]de un Palacio tambi姻n acabar茨[n]con los que est姻n dentro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 5 0]Como se produce abruptamente,[n]solo ser茨n capaces de escapar[n]si tienen mucha suerte.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Investigador]]
[s][vp 8 0 0 10 5 0]La 雨nica manera de eliminar un[n]mundo cognitivo es interrumpiendo[n]la actividad biol吋gica.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 11 5 0]Es decir, este medicamento[n]lo matar茨 temporalmente.[n]Tiene sus riesgos, pero...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Me da igual. 斡D茨melo![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Investigador]]
[s][vp 8 0 0 13 5 0]斡Ah![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [(SE)獅童 正義]]
[s][vp 8 0 0 14 65535 0](飲み込む音)[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Shido]]
[s][bup 0 206 5 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Argh...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Shido]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 206 10 300 1][vp 8 0 0 16 65535 0]Por fin... est茨n acabados...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Lacayo de Shido]]
[s][vp 8 0 0 17 65535 0]Qu姻 incauto...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [M姻dico privado]]
[s][vp 8 0 0 18 8 0]斡Hay que transferirlo de inmediato[n]si algo sale mal![n][f 1 3 65535][w][e]

