[msg MSG_000_0_0 [(SE)獅童 正義]]
[s][vp 8 0 0 1 65535 0](目覚めるうめき)[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Secretario]]
[s][vp 8 0 0 2 5 0]斡Se隠or![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Shido]]
[s][bup 0 206 905 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]夷Qu姻 he...?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Secretario]]
[s][vp 8 0 0 4 5 0]夷Eh?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Investigador]]
[s][vp 8 0 0 5 4 0]夷Todav胤a le dura el efecto?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Shido]]
[s][bup 0 206 903 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]夷Qu姻 efecto?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Secretario]]
[s][vp 8 0 0 7 5 0]Deber胤amos llevarlo a un hospital.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [M姻dico privado]]
[s][vp 8 0 0 8 7 0]Vamos a esperar un poco m茨s[n]y a ver qu姻 sucede.[n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Shido]]
[s][bup 0 206 903 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Yo...[n][f 1 3 65535][w][e]
[s][bup 0 206 905 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Argh...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [(SE)獅童 正義]]
[s][vp 8 0 0 9 65535 0](改心のすすり泣き)[n][f 1 3 65535][w][e]

[msg MSG_008_5_0 [Shido]]
[s][bup 0 206 905 0 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Debo... expiar...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Lacayo de Shido joven]]
[s][vp 8 0 0 10 6 0]No... 斡夷Ha despertado?![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Investigador]]
[s][vp 8 0 0 11 4 0]夷El suero de muerte provisional[n]no ha funcionado?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Secretario]]
[s][vp 8 0 0 12 5 0]斡Se隠or![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Lacayo de Shido joven]]
[s][vp 8 0 0 13 6 0]Si ha despertado,[n]夷se ir茨 de la lengua?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Lacayo de Shido]]
[s][vp 8 0 0 14 65535 0]斡Se lo va a cargar todo![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Secretario]]
[s][vp 8 0 0 15 5 0]夷Qu姻 vamos a hacer con la campa隠a?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Lacayo de Shido joven]]
[s][vp 8 0 0 16 6 0]Anunciaremos que no[n]se encuentra bien.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Lacayo de Shido]]
[s][vp 8 0 0 17 65535 0]斡Preparad que lo hospitalicen[n]en el m茨s absoluto secreto![n]Que nadie se le acerque.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [M姻dico privado]]
[s][vp 8 0 0 18 7 0]斡S-s胤, se隠or![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Lacayo de Shido joven]]
[s][vp 8 0 0 19 6 0]斡Y que no se enteren los medios![n][f 1 3 65535][w][e]

[msg MSG_018_5_0 [Lacayo de Shido joven]]
[s][vp 8 0 0 20 6 0]Mierda, hay que hacer algo.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [(SE)獅童 正義]]
[s][vp 8 0 0 21 65535 0](すすり泣き)[n][f 1 3 65535][w][e]

