[msg MSG_000_0_0 [(SE)選挙関係者]]
[s][vp 8 0 0 0 65535 0]バンザーイ! バンザーイ![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Shido]]
[s][bup 0 206 1 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Mi nombramiento es el resultado[n]de vuestra ayuda, ciudadanos.[n]斡Vuestro apoyo me alegra el alma![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [(SE)選挙関係者]]
[s][vp 8 0 0 0 65535 0](歓声)[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [(SE)街頭ビジョン見物人]]
[s][vp 8 0 0 0 65535 0]*vitoreo*[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Hombre satisfecho]]
[s][vp 8 0 0 2 65535 0]Sab胤a que ganar胤a Shido.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Mujer euf吋rica]]
[s][vp 8 0 0 3 65535 0]No hab胤a ning雨n motivo[n]para celebrar elecciones.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Shido]]
[s][bup 0 206 3 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Por eso...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Shido]]
[s][bup 0 206 5 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Por eso...,[n]斡no puedo perdonarme![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [(SE)街頭ビジョン見物人]]
[s][vp 8 0 0 0 65535 0](動揺『は?』『なになに?』など)[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Shido]]
[s][bup 0 206 5 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Por mi culpa falleci吋[n]el presidente Okumura.[n]Yo... lo mat姻.[n][f 1 3 65535][w][e]

[msg MSG_009_5_0 [Shido]]
[s][bup 0 206 3 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Tambi姻n manipul姻 la informaci吋n[n]de que los Ladrones Fantasma[n]estaban detr茨s de los incidentes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]El que control吋 los corazones[n]de los dem茨s y caus吋[n]incontables v胤ctimas... soy yo.[n][f 1 3 65535][w][e]
[s][bup 0 206 5 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Lo hice todo por mi ascenso,[n]para salir beneficiado.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Voz de hombre curioso]]
[s][vp 8 0 0 10 65535 0]夷Qu姻 est茨 pasando?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Shido]]
[s][bup 0 206 5 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Incluso pisote姻 varias vidas[n]para hacer de este pa胤s[n]mi propio barco.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Soy un delincuente al que se le[n]puede acusar de cualquier cosa[n]y aun as胤 no ser胤a suficiente.[n][f 1 3 65535][w][e]

[msg MSG_011_5_0 [Shido]]
[s][bup 0 206 2 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Lo confieso todo.[n]Por favor, os suplico[n]que me conden姻is...[n][f 1 3 65535][w][e]
[s][bup 0 206 5 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Como no puedo reparar todo el mal[n]que he hecho, solicito[n]que se me juzgue de inmediato.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Mujer asombrada]]
[s][vp 8 0 0 15 65535 0]夷Eh?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Hombre asustado]]
[s][vp 8 0 0 16 65535 0]斡No puede ser cierto![n]斡Presidente Shido![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [(SE)街頭ビジョン見物人]]
[s][vp 8 0 0 0 65535 0](ガヤ)[n][f 1 3 65535][w][e]

