[msg MSG_000_0_0 [Representante del director de la UEI]]
[s][vp 8 0 0 1 65535 0]No me puedo creer[n]que hayan despertado[n]el coraz吋n de Shido.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Psiquiatra]]
[s][vp 8 0 0 2 65535 0]Hemos llegado tan lejos porque[n]se encargaba de cualquiera que se[n]interpusiera en nuestro camino.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 65535 0]Si abren un caso contra 姻l,[n]saldr茨 a la luz todo lo que[n]hemos hecho...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Psiquiatra]]
[s][vp 8 0 0 4 65535 0]夷Y qu姻 hacemos?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Legislador partidario de Shido]]
[s][vp 8 0 0 5 5 0]斡Para eso nos hemos reunido![n]斡Hay que barajar las opciones![n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 5 0]La fiscal Niijima va en serio[n]y quiere llevar a Shido[n]a los tribunales, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Psiquiatra]]
[s][vp 8 0 0 7 65535 0]夷No est茨 bajo su mando?[n]斡Pues haga algo![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Representante del director de la UEI]]
[s][vp 8 0 0 8 65535 0]S胤, ya lo s姻...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 65535 0]Pero, aunque lo evitemos, 夷qu姻 pasa[n]con la gente? El comportamiento[n]de Shido fue vergonzoso.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Legislador partidario de Shido]]
[s][vp 8 0 0 10 5 0]Tendremos que seguir su pol胤tica[n]enfocada a conseguir un pa胤s rico.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Psiquiatra]]
[s][vp 8 0 0 11 65535 0]夷Un pa胤s rico?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Representante del director de la UEI]]
[s][vp 8 0 0 12 65535 0]夷Se refiere al plan de mejorar[n]en asuntos exteriores controlando[n]los corazones de la gente?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Legislador partidario de Shido]]
[s][vp 8 0 0 13 5 0]A fin de cuentas, la investigaci吋n[n]sobre eso deber胤a estar avanzando.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 14 5 0]Continuaremos con el plan[n]y mataremos a quien se interponga[n]en nuestro camino usando ese mundo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 15 5 0]Nos comprometeremos a crear un pa胤s[n]poderoso. Nosotros cumpliremos con[n]lo que esper茨bamos de Shido.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Psiquiatra]]
[s][vp 8 0 0 16 65535 0]Un pa胤s poderoso, 夷eh? Ya veo.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Representante del director de la UEI]]
[s][vp 8 0 0 17 65535 0]Pero 夷sus otros socios[n]se mantendr茨n en silencio si[n]continuamos donde 姻l lo dej吋?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Psiquiatra]]
[s][vp 8 0 0 18 65535 0]No deber胤an darnos problemas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 19 65535 0]Tras la conferencia, cualquiera[n]que haya recibido ayuda de Shido[n]creer茨 que su vida corre peligro.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 20 65535 0]Igual que nosotros.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Representante del director de la UEI]]
[s][vp 8 0 0 21 65535 0]Bueno, lo primero que hay que hacer[n]es impedir que abran un caso,[n]cueste lo que cueste.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Psiquiatra]]
[s][vp 8 0 0 22 65535 0]夷Y c吋mo controlamos[n]la opini吋n p雨blica?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Legislador partidario de Shido]]
[s][vp 8 0 0 23 5 0]Afortunadamente, a雨n hay quienes[n]apoyan a Shido.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 24 5 0]Masayoshi Shido es un h姻roe que[n]cay吋 antes de alcanzar sus metas,[n]y nosotros continuaremos su legado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 25 5 0]Eso es lo que les diremos[n]a los medios de comunicaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Psiquiatra]]
[s][vp 8 0 0 26 65535 0]Vale.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 27 65535 0]Es posible que la gente se aferre[n]a eso tras el p茨nico por haber[n]perdido a su l胤der.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Legislador partidario de Shido]]
[s][vp 8 0 0 28 5 0]Pero, si se ponen en nuestra[n]contra..., estamos perdidos.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Representante del director de la UEI]]
[s][vp 8 0 0 29 65535 0]No hay vuelta atr茨s.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Representante del director de la UEI]]
[s][vp 8 0 0 30 65535 0]Mi grupo se encargar茨 de Niijima.[n]夷Podemos confiar en que vosotros[n]os ocupar姻is de Shido?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Psiquiatra]]
[s][vp 8 0 0 31 65535 0]Nos aseguraremos de que le[n]hagan una evaluaci吋n psiqui茨trica.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Legislador partidario de Shido]]
[s][vp 8 0 0 32 5 0]Recordad que estamos en el mismo[n]barco. Tenemos que colaborar.[n][f 1 3 65535][w][e]

