[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]En las noticias hablan de la victoria[n]aplastante de Shido...[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Presentador de telediario]]
[s][vp 8 0 0 2 65535 0]Anunciaron que su l胤der,[n]Masayoshi Shido, se encuentra[n]en un estado de salud delicado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 65535 0]Por eso, la reuni吋n extraordinaria[n]de la Dieta y la investidura[n]de Shido se han pospuesto.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]夷Que se han pospuesto?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]斡Deber胤an despedirlo![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]夷Y han dicho que est茨 delicado?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Es todo lo contrario[n]a lo que nos cont吋 mi hermana.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Hombre l茨nguido]]
[s][vp 8 0 0 8 65535 0]Dicen que apenas dorm胤a durante[n]la campa隠a electoral. Pobrecito.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Hombre preocupado]]
[s][vp 8 0 0 9 14 0]No se ir茨 a retirar ahora, 夷no?[n]夷Funcionar茨 bien el pa胤s sin 姻l?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]夷Por qu姻 la gente[n]sigue creyendo en 姻l?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]斡夷Qu姻 narices...?![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]斡Tratan a los Ladrones Fantasma[n]como si nunca hubieran existido![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Madre m胤a...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Haru]]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]或No hay relaci吋n con los[n]despertares, solo son casos de[n]trastornos mentales coincidentes位.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]或Los Ladrones Fantasma solo usaban[n]los rumores en su beneficio位.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Esto es absurdo.[n]夷Qui姻n se creer胤a algo as胤?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]El que lo dice es[n]un investigador famoso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Hasta el ministerio dice que[n]han evaluado[n]as胤 la situaci吋n...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Hombre despreocupado]]
[s][vp 8 0 0 19 65535 0]夷Cu茨ndo va a volver Shido?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Hombre grandilocuente]]
[s][vp 8 0 0 20 15 0]Sinceramente, creo que solo[n]姻l puede hacer algo[n]en los tiempos que corren.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]夷Qu姻 est茨 pasando? Se mire como[n]se mire, es que no es normal.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]S胤, es como si la gente de la[n]realidad se hubiera corrompido...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Es preocupante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Pero lo 雨nico que podemos hacer[n]es esperar a ver qu姻 pasa.[n][f 1 3 65535][w][e]

