[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Es cierto que, aunque eliminemos[n]el Metaverso, nada nos asegura[n]que el mundo vaya a cambiar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Y, si perdemos los poderes,[n]no podremos enfrentarnos a[n]delincuentes como Shido nunca m茨s.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]En ese caso, 夷no ser胤a mejor ir[n]despertando los corazones de los[n]delincuentes que vayan apareciendo?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Sinceramente, no tengo claro[n]cu茨l es la mejor soluci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Despertamos el coraz吋n de Shido,[n]as胤 que dudo que nos d姻 problemas[n]aun siendo primer ministro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Aunque no sea de nuestro agrado...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Deber胤amos perseguir[n]a los delincuentes,[n]no a la gente normal, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Pues...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]夷Sab姻is qu姻?[n][f 4 2] tiene raz吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Mi lugar est茨 aqu胤...[n]斡Quiero seguir formando parte[n]de los Ladrones Fantasma![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Me has le胤do la mente.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Creo que me opondr姻[n]a la decisi吋n del l胤der.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]夷Alguna objeci吋n?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Entonces, 夷seguimos adelante[n]con los Ladrones Fantasma?[n][f 1 3 65535][w][e]

