[msg MSG_000_0_0 [Universitario]]
[s][vp 8 0 0 1 18 0]Qu姻 buen tiempo hace, t胤o.[n]夷Te apetece dar una vuelta?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Hombre de negocios]]
[s][vp 8 0 0 2 15 0]夷Hola? S胤, es por la reuni吋n[n]preliminar de ma隠ana...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Friki]]
[s][vp 8 0 0 3 65535 0]斡Esta noche se anuncia[n]un m吋vil nuevo![n][f 1 3 65535][w][e]

[msg MSG_002_2_0 [Mujer ostentosa]]
[s][vp 8 0 0 21 65535 0]夷De qu姻 iba todo eso[n]de los Ladrones Fantasma?[n][f 1 3 65535][w][e]

[msg MSG_002_5_0 [Hombre tratable]]
[s][vp 8 0 0 22 65535 0]Madre m胤a, 斡qu姻 recuerdos![n]Mira que fui imb姻cil.[n]Anda que creerme que existieran...[n][f 1 3 65535][w][e]

[msg MSG_002_7_0 [Mujer conocedora]]
[s][vp 8 0 0 23 65535 0]Bueno, al menos nos divert胤amos.[n]Pero dudo que nadie[n]crea en ellos ya.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 3 4 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]夷Por qu姻 nadie se percata[n]de esta anomal胤a?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 5 4 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Seguramente sea[n]porque no ven nada raro...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 2 4 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]斡夷Qu姻 te pasa?![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 3 4 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Uff... Estoy... un poco mareada...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][bup 0 8 5 4 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Ahh...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ann]]
[s][bup 0 4 2 4 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]斡Futaba, ag茨rrate![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 5 4 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]斡Argh...![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 5 4 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]斡夷Ann?! Argh...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [(SE)主人公]]
[s][vp 8 0 0 12 65535 0]ぐ...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [(SE)坂本 竜司]]
[s][vp 8 0 0 13 65535 0]うぉあ...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [(SE)モルガナ]]
[s][vp 8 0 0 14 65535 0]ぐ...ふ...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [(SE)高巻 杏]]
[s][vp 8 0 0 15 65535 0]んう...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [(SE)喜多川 祐介]]
[s][vp 8 0 0 16 65535 0]む...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [(SE)新島 真]]
[s][vp 8 0 0 17 65535 0]くっ...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [(SE)佐倉 双葉]]
[s][vp 8 0 0 18 65535 0]うあ...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [(SE)奥村 春]]
[s][vp 8 0 0 19 65535 0]ああ...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Makoto]]
[s][bup 0 6 5 4 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]夷Esto es...[n]cosa del Santo Grial tambi姻n?[n][f 1 3 65535][w][e]

