[msg MSG_000_5_0 [Yusuke]]
[s][bup 0 5 104 0 0][f 4 10 65535 0 0][vp 8 0 0 73 65535 0]夷Qu姻 es este lugar?[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][vp 8 0 0 74 65535 0]夷Qui姻nes son?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Me llamo Igor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Soy el maestro[n]de la Habitaci吋n Terciopelo.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Soy Lavenza, residente[n]de este lugar. Os[n]hemos estado esperando.[n][f 1 3 65535][w][e]

[msg MSG_003_1_0 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 0 0 75 65535 0]夷La Habitaci吋n Terciopelo?[n][f 1 3 65535][w][e]

[msg MSG_003_2_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 77 65535 0]Mi maestro se acaba de liberar[n]de un largo periodo de encierro.[n]A雨n no ha recuperado todo su poder.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 78 65535 0]Aunque puede ser presuntuoso[n]de mi parte, hablar姻 por...[n][f 1 3 65535][w][e]

[msg MSG_003_3_0 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][vp 8 0 0 76 65535 0]Oye, 夷d吋nde est茨 Morgana?[n][f 1 3 65535][w][e]

[msg MSG_003_4_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 79 65535 0]夷Quer姻is verlo?[n][f 1 3 65535][w][e]

[sel SEL_003_5_0 top]
[s]Claro que s胤.[e]
[s]夷Lo conoces?[e]

[msg MSG_003_6_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Est茨 justo ah胤.[n][f 1 3 65535][w][e]

[msg MSG_003_7_0 [Ryuji]]
[s][bup 0 2 104 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]斡夷Te hab胤as escondido ah胤?![n][f 1 3 65535][w][e]

[msg MSG_003_8_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 80 65535 0]Yo... nac胤 aqu胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 81 65535 0]Fue para eliminar a un ser maligno[n]del mundo espiritual del hombre...[n][f 1 3 65535][w][e]

[msg MSG_003_8_2 [Futaba]]
[s][bup 0 8 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 72 65535 0]夷Mona?[n][f 1 3 65535][w][e]

[msg MSG_003_8_4 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 82 65535 0]Mi labor consist胤a en encontrar al[n]Trickster y ayudar a derrotarlo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 83 65535 0]Por eso me cre吋 mi maestro.[n][f 1 3 65535][w][e]

[msg MSG_003_8_6 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]En efecto.[n][f 1 3 65535][w][e]

[msg MSG_003_8_8 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 84 65535 0]Lo recuerdo todo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 85 65535 0]Cuando iban a tomar este lugar,[n]mi maestro reuni吋 los 雨ltimos[n]vestigios de esperanza del hombre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 86 65535 0]Reuni吋 toda la fuerza que[n]le quedaba para crearme.[n][f 1 3 65535][w][e]

[msg MSG_003_9_0 [Lavenza]]
[s][bup 0 100 3 0 0][f 4 10 65535 0 0][vp 8 0 0 87 65535 0]La entidad que dice ser un dios es[n]una voluntad mal姻vola que condena[n]al hombre a la esclavitud perpetua.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 88 65535 0]Espera alcanzar la paz eterna[n]colmando la realidad con aquellos[n]que ya no piensan por s胤 mismos. [n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 89 65535 0]Esa es la perdici吋n del hombre[n]que este dios maligno imagina.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 103 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Yo... Mmm... No entiendo[n]nada de lo que dices...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Lavenza]]
[s][bup 0 100 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]斡Calla y escucha![n]斡No nos queda mucho tiempo![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 104 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Un momento.[n]夷El Santo Grial es... un 或dios位?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Me preguntaba por qu姻[n]ten胤a voluntad propia, pero[n]夷quieres decir que no es un tesoro?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 90 65535 0]No. Igual que los deseos[n]distorsionados de las masas,[n]es el n雨cleo del propio Mementos.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Haru]]
[s][bup 0 7 103 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Entonces... 夷el tesoro se convirti吋[n]en un dios porque la gente[n]deseaba que la gobernaran?[n][f 1 3 65535][w][e]

[msg MSG_029_0_5 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 91 65535 0]Correcto.[n][f 1 3 65535][w][e]

[msg MSG_029_1_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 92 65535 0]Para decidir el destino del mundo,[n]eligi吋 a dos personas con potencial[n]e hizo que se enfrentaran.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 93 65535 0]Goro Akechi incit吋 a la distorsi吋n[n]de las masas. Si ganaba, el mundo[n]ser胤a destruido y reconstruido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 94 65535 0]La otra persona era un[n]Trickster que le har胤a frente...[n]Era [f 4 3].[n][f 1 3 65535][w][e]

[msg MSG_029_1_5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 95 65535 0]Si ganaba [f 4 2], el mundo[n]humano se quedar胤a tal cual...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 96 65535 0]Esas eran las condiciones[n]del juego, o al menos[n]lo que deber胤a haber ocurrido.[n][f 1 3 65535][w][e]

[msg MSG_029_2_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 97 65535 0]El ser maligno sab胤a[n]que los humanos indolentes[n]no provocar胤an una revoluci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 98 65535 0]No deja de ser la reencarnaci吋n[n]de los deseos distorsionados.[n][f 1 3 65535][w][e]

[msg MSG_029_2_5 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 99 65535 0]Sin embargo, mi verdadero[n]maestro cre胤a en la humanidad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 100 65535 0]Cre胤a que se alzar胤a[n]un Trickster y que[n]lograr胤a llevar a cabo el cambio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 101 65535 0]Pero la entidad maligna se rio[n]ante tal posibilidad y trat吋 de[n]demostrar la impotencia del hombre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 102 65535 0]Y [f 4 3] ten胤a[n]un potencial enorme... por eso[n]se le acerc吋.[n][f 1 3 65535][w][e]

[msg MSG_029_3_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 103 65535 0]Ayud吋 a entrenar al Trickster para[n]desesperarlo usando a las masas,[n]que rechazaron a su salvador.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 104 65535 0]Es probable que fuera su manera[n]de cortar de ra胤z[n]cualquier tipo de amenaza.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 117 65535 0]Recuerdo que nunca[n]estuve de acuerdo[n]con la palabra 或rehabilitaci吋n位.[n][f 1 3 65535][w][e]

[msg MSG_029_3_2 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 118 65535 0]Claro que no...[n]Solo era una forma de[n]mantenerte vigilado.[n][f 1 3 65535][w][e]

[msg MSG_029_3_5 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 105 65535 0]B茨sicamente, se vio inmerso[n]en un juego en el que el dios[n]maligno manipulaba el resultado.[n][f 1 3 65535][w][e]

[msg MSG_029_4_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 17 301 1][vp 8 0 0 14 65535 0]Mierda. 斡夷Qu姻 narices?![n][f 1 3 65535][w][e]

[msg MSG_029_4_5 [Lavenza]]
[s][bup 0 100 3 0 0][f 4 10 65535 0 0][vp 8 0 0 106 65535 0]Tu mundo real ya se[n]ha fusionado con Mementos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 107 65535 0]No existes porque la realidad est茨[n]repleta de la cognici吋n de quienes[n]rechazan a los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 108 65535 0]Se puede decir que el mundo[n]est茨 a un paso de las maquinaciones[n]del dios maligno.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 109 65535 0]Pero a雨n queda esperanza,[n][f 4 3]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 119 65535 0]Ahora que se ha descubierto[n]la identidad del dios maligno,[n]puedes completar tu rehabilitaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 120 65535 0]Solo t雨 puedes salir de esta[n]prisi吋n y salvar este mundo[n]distorsionado y a su gente...[n][f 1 3 65535][w][e]

[msg MSG_035_7_0 [Lavenza]]
[s][bup 0 100 2 0 0][f 4 10 65535 0 0][vp 8 0 0 110 65535 0]Joven guiado por Morgana y[n]digno del nombre Trickster...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 111 65535 0]Debes desafiar al dios maligno[n]y reivindicar tu existencia en el[n]mundo real. 夷Aceptas esta tarea?[n][f 1 3 65535][w][e]

[sel SEL_036_0_0 top]
[s]Claro.[e]
[s]No estoy seguro.[e]
[s]夷Reivindicar mi existencia?[e]

[msg MSG_037_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 3 300 1][vp 8 0 0 59 65535 0]斡Vamos a destruir esa birria[n]de tesoro de una pu隠etera vez![n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Ann]]
[s][bup 0 4 101 0 0][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]Todo saldr茨 bien. No estar茨s solo.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Ryuji]]
[s][bup 0 2 101 0 0][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]Nos tienes a nosotros, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_042_5_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]*risita* Excelente...[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 67 65535 0]No hay nada que temer.[n]Ya tienes la fuerza[n]para enfrentarte al dios maligno.[n][f 1 3 65535][w][e]

[msg MSG_043_5_0 [Igor]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 201 1 301 1][vp 8 0 0 68 65535 0]*risita* 斡Qu姻 ganas[n]tengo de que ocurra![n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 112 65535 0]Nuestro amigo en com雨n[n]sabe d吋nde est茨 la salida.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 113 65535 0]Morgana, gu胤alos, por favor.[n][f 1 3 65535][w][e]
[s][bup 0 100 3 0 0][f 4 10 65535 0 0][vp 8 0 0 114 65535 0]Y gracias por todo.[n]Se te ha encomendado[n]una responsabilidad muy cruel...[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 115 65535 0]Aceptar姻 sus elogios[n]cuando todo esto haya acabado.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 116 65535 0]Y ahora, 斡seguidme![n][f 1 3 65535][w][e]

