[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 7 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Eh...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Parece que seguimos[n]vivitos y coleando...[n][f 1 3 65535][w][e]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Pero... 夷d吋nde?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Fuera de la Habitaci吋n Terciopelo.[e]
[s]Ven conmigo.[e]
[s]Me alegra que est姻s bien.[e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]夷Eh? 夷Terciopelo...?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 5 4 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Vale...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Esta celda me recuerda[n]a cuando nos conocimos...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Recuerdas que ahora Shibuya[n]estaba hecha una mierda?[n]Y nadie ve胤a nada de eso...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Bueno, m茨s bien parec胤a[n]que nadie quer胤a verlo...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 5 4 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]夷Qu姻 co隠o...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]夷Incluso los que estaban[n]sufriendo y pidi姻ndonos[n]que los ayud茨ramos...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]夷En realidad habr胤an preferido que todo[n]se hubiera quedado tal como estaba...?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]夷Tiene sentido todo lo que hemos[n]estado haciendo...?[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]Claro que s胤.[e]
[s]No te rindas ahora, Ryuji.[e]
[s]......[e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Ja, ja. Eres duro de pelar...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 5 4 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Cuando cre胤 que 胤bamos[n]a morir sin llegar a saber[n]la verdad sobre todo esto...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Sent胤, por primera vez,[n]que a lo mejor no hab胤amos[n]hecho lo correcto...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Que igual merec胤amos perder...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]夷Me entiendes?[n][f 1 3 65535][w][e]

[sel SEL_009_0_0 top]
[s]Para nada.[e]
[s]Yo me siento igual.[e]
[s]No s姻.[e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 5 4 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Ahora que lo pienso,[n]empec姻 con todo esto[n]por lo cabreado que estaba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]A lo mejor la cosa nunca[n]ha ido sobre ganar ni nada de eso...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]A lo mejor solo estaba[n]siguiendo mi instinto de rebeld胤a...[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]夷Y qu姻?[e]

[msg MSG_012_0_0 [Ryuji]]
[s][bup 0 2 4 4 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]夷Y... qu姻?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 4 4 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0][f 4 2]...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Ja, ja... Tienes raz吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Ya lo pillo...[n][f 1 3 65535][w][e]
[s][bup 0 2 11 4 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Hacemos esto para que[n]la gente no tenga que pasar[n]por la misma mierda que nosotros.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Da igual que piensen que[n]somos justos o que no. 斡Debemos[n]seguir nuestros principios![n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 11 4 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Je, adem茨s, tampoco es[n]que la gente piense mucho en m胤.[n][f 1 3 65535][w][e]

[msg MSG_015_5_0 [Ryuji]]
[s][f 4 16 2 10 301 1 65535][vp 8 0 0 28 65535 0]斡Voy a hacer esto[n]de la 雨nica forma que s姻![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Je... Me has sacado de la prisi吋n,[n]como la otra vez.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Gracias... Me da un poco de verg鵜enza decirlo,[n]pero me alegro de haberte conocido.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]斡Bueno, ya basta[n]de llevarme palizas![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Ese desgraciado se cree una especie[n]de dios... 斡No me quedar姻 tranquilo[n]hasta que nos ocupemos de 姻l![n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 5 0]Largu姻monos. Vamos[n]a ocuparnos de ese imb姻cil, 夷vale?[n][f 1 3 65535][w][e]

