[msg MSG_000_0_0 [Oficinista cansado]]
[s][vp 8 0 0 1 19 0]斡夷Qu姻 ha sido eso?![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Hombre a la moda]]
[s][vp 8 0 0 3 13 0]L-la ciudad...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Oficinista cansado]]
[s][vp 8 0 0 4 19 0]斡夷Qu姻 est茨 pasando aqu胤?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]斡Parece que por fin[n]se han dado cuenta[n]de que sus vidas corren peligro![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]斡Anda que no les ha costado![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][bup 0 6 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]No me puedo creer que no se[n]hayan dado cuenta hasta que el[n]peligro no se les ha echado encima...[n][f 1 3 65535][w][e]

[msg MSG_007_5_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Y las cosas van[n]a ponerse a雨n m茨s feas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Toda la ciudad ha colapsado. Al[n]menos a雨n pueden entrar en p茨nico...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 102 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Si la gente no se moviliza[n]despu姻s de ver esto...[n]斡no habr茨 nada que podamos hacer![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]斡En fin, vamos para el templo![n][f 1 3 65535][w][e]

