[msg MSG_000_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]*risita* Magn胤fico.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Pero... ahora est茨s preso en el[n]mundo real, incluso tras huir de la[n]prisi吋n dentro de tu coraz吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Qu姻 giro de los acontecimientos[n]tan ir吋nico. Antepon胤as a los dem茨s[n]por encima de tu bienestar y mira.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Aun as胤..., servir茨.[n]Elegiste el camino correcto[n]por voluntad propia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]No renunciaste a tus creencias por[n]tu beneficio propio hasta el final.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]El 雨ltimo arcano que has[n]adquirido es el Mundo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Consiste en la fuerza de voluntad para valerse por uno mismo sin que nadie lo impida.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Esa ser茨 la base de la esperanza[n]en un futuro con tus compa隠eros[n]que compartan las mismas creencias.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Ahora que has obtenido[n]ese poder, has dejado[n]de vagar en soledad...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Mi labor tambi姻n acaba aqu胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Has sido un hu姻sped excepcional.[n][f 1 3 65535][w][e]

