[msg MSG_000_2_0 [Hombre asustado]]
[s][vp 8 0 0 2 13 0]斡夷Sab姻is d吋nde est茨 mi amigo?![n]Lo ten胤a al lado, pero...[n][f 1 3 65535][w][e]

[msg MSG_000_7_0 [Mujer aturdida]]
[s][vp 8 0 0 4 15 0]斡No! 斡Una persona ha desaparecido[n]delante de mis narices![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Hombre de negocios de mediana edad]]
[s][vp 8 0 0 1 11 0]斡Por favor, que alguien nos salve![n][f 1 3 65535][w][e]

