[msg DVL_000_0_0 [Gu胤a apocal胤ptico]]
[s][vp 8 0 0 1 65535 0]Oh, aciagos acontecimientos. Nunca pens姻 que[n]derrotar胤ais a los otros arc茨ngeles... Solo resto yo.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 4 3 300 1][vp 8 0 0 2 65535 0]斡Y t雨 eres el 雨ltimo que se[n]interpondr茨 en nuestro camino![n][f 1 3 65535][w][e]

[msg DVL_002_0_0 [Gu胤a apocal胤ptico]]
[s][vp 8 0 0 3 65535 0]夷Osar姻is destruir al mismo se隠or que anhelabais?[n]La arrogancia humana no tiene l胤mites.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 5 3 300 1][vp 8 0 0 4 65535 0]斡No todo el mundo quiere[n]que esa cosa nos domine![n][f 1 3 65535][w][e]

[msg DVL_004_0_0 [Gu胤a apocal胤ptico]]
[s][vp 8 0 0 5 65535 0]夷Ansi茨is la libertad? 夷Goz茨is en la diversidad?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 65535 0]Desde los albores, los humanos han sucumbido[n]a la violencia causada por su propia libertad.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 7 65535 0]Ahora, por fin, buscan un se隠or que los gu胤e bajo[n]su yugo. 斡夷Qu姻 sentido tiene vuestra justicia,[n]que desaf胤a sus deseos?![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 3 3 301 1][vp 8 0 0 8 65535 0]斡Ni que conceder deseos[n]fuera justicia![n][f 1 3 65535][w][e]

[msg MSG_005_5_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]夷C吋mo puedes decir que la gente es[n]libre cuando est茨 encadenada en las[n]prisiones de este mundo roto?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Haru]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 7 3 301 1][vp 8 0 0 10 65535 0]Si alguien est茨 descarriado,[n]nuestro trabajo es ayudar[n]a que recobre el juicio.[n][f 1 3 65535][w][e]

[msg DVL_007_0_0 [Gu胤a apocal胤ptico]]
[s][vp 8 0 0 11 65535 0]No hay sacrilegio mayor que el vuestro.[n]Por vuestros ideales, profanar姻is lo m茨s sagrado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 12 65535 0]斡No hay salvaci吋n para vosotros![n][f 1 3 65535][w][e]

