[msg MSG_000_0_0 [(SE)サラリーマン]]
[s][vp 8 0 0 1 65535 0]うわああああ![n][f 1 3 65535][w][e]

[msg MSG_000_2_0 [(SE)大衆]]
[s][vp 8 0 0 0 65535 0](ある程度、大勢の悲鳴)[n][f 1 3 65535][w][e]

[msg MSG_000_5_0 [Mujer llorosa]]
[s][vp 8 0 0 25 65535 0]Alguien... acaba de desaparecer.[n][f 1 3 65535][w][e]

[msg MSG_000_7_0 [Hombre p茨lido]]
[s][vp 8 0 0 26 6 0]斡夷Qu姻 narices?! 斡夷Qu姻 ocurre?![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Macarra asustado]]
[s][vp 8 0 0 4 9 0]斡Haga algo, joder![n]斡夷No es polic胤a?![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Polic胤a joven]]
[s][vp 8 0 0 5 10 0]Por favor, c茨lmese.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 10 0]Caballero, 夷qu姻 ocurre aqu胤?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Polic胤a veterano]]
[s][vp 1 0 0 7 0 0]......[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [(SE)電子音声]]
[s][vp 8 0 0 8 65535 0]...電波の届かない所にいるか、電源が入っておりません。[n][f 1 2 74][e]

[msg MSG_006_0_0 [Hombre asombrado]]
[s][vp 8 0 0 9 5 0]Es in雨til...[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Y sin ninguna... ninguna duda...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Hombre asombrado]]
[s][vp 8 0 0 10 5 0]夷Eh?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]斡Conquistaremos el mundo![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Alumno atento]]
[s][vp 8 0 0 13 20 0]夷Qu姻 ha sido eso?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Polic胤a veterano]]
[s][vp 8 0 0 14 23 0]夷Los Ladrones Fantasma?[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Polic胤a joven]]
[s][vp 8 0 0 15 22 0]夷No eran los Ladrones Fantasma?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Estudiante t胤mida]]
[s][vp 8 0 0 16 24 0]A雨n no se han rendido.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Joven trajeado]]
[s][vp 8 0 0 17 25 0]夷Es que pueden hacer algo[n]en una situaci吋n as胤?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Joven introvertido]]
[s][vp 8 0 0 18 19 0]No, es imposible...[n]No puede ser...[n][f 1 3 65535][w][e]

