[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 4 3 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]斡夷En serio?![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][bup 0 6 0 3 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Ahora que tenemos un nombre,[n]solo nos falta la direcci吋n.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][bup 0 6 0 3 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Cierto. Solo lo conseguiremos[n]si lo hacemos juntos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Mi hermana a雨n no ha dicho nada,[n]pero creo que tambi姻n est茨 pensando[n]en qu姻 se puede hacer.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]En cuanto a m胤, estudiar姻[n]todas las soluciones viables.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][bup 0 6 1 3 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Gracias. Dale recuerdos[n]a Shiho de mi parte.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 3 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Ah, 夷podemos pedirles que nos[n]ayuden tambi姻n? Seguro que estar茨n[n]encantados de echar una mano.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][bup 0 6 1 3 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Ser胤a de gran ayuda.[n]Lo dejo en tus manos.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][bup 0 6 0 3 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Vale. Hablamos ma隠ana.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Hay que salvarlo sea como sea.[n][f 1 3 65535][w][e]

