[msg MSG_000_0_0 [Investigador]]
[s][vp 8 0 0 1 65535 0]Ahora empezaremos[n]el interrogatorio.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 4 0]Usted ejerc胤a de l胤der de los[n]Ladrones Fantasma que debilitaron[n]nuestra sociedad... 夷Correcto?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]As胤 es.[e]
[s]No, hemos salvado a la sociedad.[e]
[s]...[e]

[msg MSG_002_0_0 [Investigador]]
[s][vp 8 0 0 3 4 0]Muy bien. Siga respondiendo as胤[n]a nuestras preguntas.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Investigador]]
[s][vp 8 0 0 4 4 0]Su opini吋n no nos interesa.[n]Continuemos...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Investigador]]
[s][vp 8 0 0 5 4 0]夷Se acoge a su derecho[n]de permanecer en silencio? As胤 solo[n]conseguir茨 alargar la condena.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 4 0]Responda con sinceridad[n]a las preguntas.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Investigador]]
[s][vp 8 0 0 7 4 0]Como l胤der de los Ladrones[n]Fantasma, cometi吋 numerosos delitos...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 8 4 0]Allanamiento de la residencia[n]de Madarame y de Okumura Foods,[n]destrucci吋n de propiedad ajena...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 4 0]Ah, y al interceptar la se隠al de[n]emisi吋n del otro d胤a infringisteis[n]la Ley de Radio.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Investigador]]
[s][vp 8 0 0 10 4 0]Pero esas no son[n]las 雨nicas infracciones...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 11 4 0]Adem茨s de todo lo que ya[n]he mencionado, tiene m茨s delitos[n]a sus espaldas, 夷cierto?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Investigador]]
[s][vp 8 0 0 12 65535 0]Ya hemos decidido que lo[n]internaremos en un reformatorio.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 13 4 0]Lo trasladaremos all胤[n]en los pr吋ximos d胤as.[n][f 1 3 65535][w][e]

