[msg MSG_000_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Tampoco ha habido suerte este a隠o...[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]夷De qu姻 hablas?[e]
[s]Qu姻 mal.[e]
[s]夷Con chocolate, dices?[e]

[msg MSG_002_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]斡Anda, es San Valent胤n![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Bueno, si a m胤 nadie[n]me regala chocolate.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]斡No digas eso![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Yusuke al menos viste[n]guay, 夷no? Es como[n]un im茨n de t胤as.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 14]Joder, se supone que yo[n]tambi姻n deber胤a ser un h姻roe...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oye, hoy es el d胤a de San Valent胤n.[n]夷Tienes novia?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]No.[e]
[s]No me hace falta.[e]
[s]La verdad es que s胤.[e]

[msg MSG_008_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Je, qu姻 t胤o m茨s solitario.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No te hagas el machote.[n]En el fondo[n]s胤 que quieres una, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mentiroso.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Sojirooo! 斡Tengo hambreee![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero si te he dejado comida.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No quiero comer sola.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vale. 夷Y si salimos[n]a comer en familia?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷A qu姻 viene tanta amabilidad?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Intento ser compasivo por el p姻simo[n]San Valent胤n de este.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [(SE)佐倉 双葉]]
[s][vp 8 0 0 0 65535 0](ぷくく...と意地悪い含み笑い)[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Penoso...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Voy a cerrar y nos vamos.[n]Al gato no le pasar茨 nada...[n]Creo que est茨 dormido.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Sushi! 斡Sushiiiii![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]夷Qu姻 tal? Has tardado en[n]responder. 夷Pasa algo?[n][f 1 3 65535][w][e]

[sel SEL_022_0_0 top]
[s][f 5 14]Hoy ceno con mi familia.[e]
[s]Tengo una cita.[e]
[s]No es nada.[e]

[msg MSG_023_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Eh, pues pinta bien.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]斡T胤o, no voy a picar en[n]esa mierda! 斡Que no![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Je, cre胤 que alguien te hab胤a[n]pedido una cita o algo as胤.[n]No me tomes el pelo, anda.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][vp 8 0 0 0 65535 0][f 5 14]Intent姻moslo el a隠o que viene.[n][f 1 3 65535][w][e]

