[msg MSG_000_0_0 [Chica misteriosa]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 0 1 4 0]Creo que... ese era el 雨ltimo.[n][f 1 3 65535][w][e]

[msg MSG_000_0_1 [Kasumi]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 0 1 4 0]Creo que... ese era el 雨ltimo.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Voz de chica]]
[s][bup 0 8 150 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]No tengo ni idea de lo que ha pasado,[n]pero me imagino que est茨s bien.[n][f 1 3 65535][w][e]

[msg MSG_001_0_1 [Futaba]]
[s][bup 0 8 100 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]No tengo ni idea de lo que ha pasado,[n]pero me imagino que est茨s bien.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Voz de chica]]
[s][bup 0 8 154 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]斡Malas noticias! 斡Refuerzos enemigos[n]se dirigen hacia vosotros![n]斡Haced algo ya![n][f 1 3 65535][w][e]

[msg MSG_002_0_1 [Futaba]]
[s][bup 0 8 104 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]斡Malas noticias! 斡Refuerzos enemigos[n]se dirigen hacia vosotros![n]斡Haced algo ya![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Chica misteriosa]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 0 4 4 0]M茨rchate. Yo los distraer姻[n]para que no te persigan.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 4 0]Todav胤a tienes un asunto pendiente[n]como Ladr吋n Fantasma, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_003_0_1 [Kasumi]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 0 4 4 0]M茨rchate. Yo los distraer姻[n]para que no te persigan.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 4 0]Todav胤a tienes un asunto pendiente[n]como Ladr吋n Fantasma, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Chica misteriosa]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 0 6 4 0]Pues no te detendr姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 4 0]No puedo interferir porque no soy[n]miembro de los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_004_0_1 [Kasumi]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 0 6 4 0]Pues no te detendr姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 4 0]No puedo interferir porque no soy[n]miembro de los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Chica misteriosa]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 0 8 4 0]Aun as胤... no te olvides de la promesa[n]que hicimos, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_005_0_1 [Kasumi]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 0 8 4 0]Aun as胤... no te olvides de la promesa[n]que hicimos, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Voz de chica]]
[s][bup 0 8 152 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Joker, 斡tienes que salir de ah胤![n]斡Vamos![n][f 1 3 65535][w][e]

[msg MSG_006_0_1 [Futaba]]
[s][bup 0 8 102 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Joker, 斡tienes que salir de ah胤![n]斡Vamos![n][f 1 3 65535][w][e]

