[msg MSG_000_0_0 [Estudiante con cinta en el pelo]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 4 0]Si姻ntese, por favor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 4 0]Ya casi llegamos a mi parada.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Anciana]]
[s][vp 8 0 0 3 5 0]夷Est茨s segura? Entonces...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Estudiante con cinta en el pelo]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 4 0]斡Vaya, qu姻 rapidez![n][f 1 3 65535][w][e]

[msg MSG_002_5_0 [Estudiante con cinta en el pelo]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 4 0]Oiga, disculpe, el sitio era[n]para esta se隠ora...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Estudiante con cinta en el pelo]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 4 0]Uy...[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]夷Quieres que lo 或despierte位?[e]
[s]Di algo, anda.[e]

[msg MSG_005_0_0 [Estudiante con cinta en el pelo]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 4 0]No pasa nada. Tambi姻n entiendo[n]su situaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Estudiante con cinta en el pelo]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 4 0]Siento no haber sido de mucha ayuda.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Anciana]]
[s][f 4 10 65535 0 0][vp 8 0 0 9 5 0]No pasa nada, cielo. No te preocupes.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Estudiante con cinta en el pelo]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 4 0]Deje que al menos lleve su equipaje.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Anciana]]
[s][vp 8 0 0 11 5 0]斡Gracias![n][f 1 3 65535][w][e]
[s][vp 8 0 0 12 5 0]夷No pesa?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Estudiante con cinta en el pelo]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 4 0]斡Qu姻 va! Entreno mucho.[n][f 1 3 65535][w][e]

