[msg MSG_000_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Gracias por dejarme ir contigo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]La preliminar est茨 al caer, as胤 que[n]no quiero ponerme enferma.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷Preliminar?[e]
[s]夷Es algo de gimnasia?[e]

[msg MSG_002_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Ah, la fase preliminar[n]de la competici吋n de gimnasia.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]S胤, eso es.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Tengo dos grandes competiciones[n]pronto: una a principios de verano[n]y otra a finales.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Si quiero ir a la preliminar, tengo[n]que salir elegida representante[n]del equipo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Y tenemos un encuentro[n]clasificatorio para decidirlo.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Kasumi]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Mi sue隠o es competir en gimnasia[n]a nivel mundial.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]As胤 que seguir姻 un plan estricto[n]con mi entrenadora.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Te dejas la piel.[e]
[s]Yo te animar姻.[e]

[msg MSG_008_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]No es nada del otro mundo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Pero es mi sue隠o, as胤 que[n]voy a esforzarme al m茨ximo.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Kasumi]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]斡Entonces ser胤a invencible![n]Es broma.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Kasumi]]
[s][bup 0 10 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Ah, ya estamos en la estaci吋n...[n][f 1 3 65535][w][e]

