[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Pero qu姻 calooor...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Me siento como si estuvi姻ramos[n]en una sauna gigante.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]夷De qui姻n fue la brillante idea de venir aqu胤?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Tuya...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Presentadora]]
[s][vp 8 0 0 5 9 0]斡Y mirad qu姻 de gente![n]斡Sonrisas por todas partes![n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 9 0]Bueno, vamos a charlar con algunos[n]visitantes para que nos digan[n]qu姻 opinan.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Un equipo de televisi吋n, 夷eh?[n][f 1 3 65535][w][e]

[sel SEL_005_5_0 top]
[s]M茨s nos vale pasar desapercibidos...[e]
[s]No quiero salir en la tele.[e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][f 4 24 0 4 2 12 5 100][vp 8 0 0 10 65535 0]Venga, vamos a por kebabs[n]y nos largamos de aqu胤.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Presentadora]]
[s][vp 8 0 0 11 9 0]Anda, vamos a entrevistar a esos tres.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Oye, 夷se refiere a nosotros?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Pero 夷qu姻...?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]夷Qu姻 hacemos, [f 4 2]?[n][f 1 3 65535][w][e]

[sel SEL_011_0_0 top]
[s]Tranquilic姻monos.[e]
[s]Salgamos pitando.[e]

[msg MSG_012_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Es verdad. Si nos entra el p茨nico,[n]pareceremos m茨s sospechosos.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Con eso solo llamar胤amos a雨n m茨s[n]la atenci吋n.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]斡Nos han pillado![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Buf, qu姻 mal...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Vale, voy a dejarme llevar y a dar un mont吋n[n]de verg鵜enza ajena para que[n]no puedan emitirlo.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Presentadora]]
[s][vp 8 0 0 21 9 0]斡Hola! Hace mucho calor, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]斡Buf, vaya que s胤![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Y si hace este calor en julio,[n]斡imag胤nate qu姻 locura ser茨 esto[n]cuando llegue diciembre![n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Presentadora]]
[s][vp 8 0 0 24 9 0]Eh, bueno... Has venido al festival,[n]as胤 que intuyo que a ti y a tus amigos[n]os encanta la carne, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Eh...[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][f 4 24 0 4 6 36 5 100][f 4 24 0 4 2 12 5 100][vp 8 0 0 26 65535 0]Somos m茨s bien amantes de la fruta.[n]斡Y de los dulces, que son lo mejor![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Presentadora]]
[s][vp 8 0 0 27 9 0]Je, je, je...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Presentadora]]
[s][vp 8 0 0 28 9 0]Esto... 斡Gracias por hablar[n]con nosotros![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Uf, ha faltado poco.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Ha sido bastante rid胤culo, la verdad,[n]pero 夷seguro que no lo emitir茨n?[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Estoy seguro de que le pareci吋[n]un desastre total. No os preocup姻is.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]斡Lo m茨s importante es que[n]ahora toca carne![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]斡Ah, s胤! 斡Los kebabs![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Las colas para comprar comida[n]eran casi peores que el calor.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Aguantar en pie bajo este sol abrasador[n]ha sido todo un reto.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Y casi todo lo bueno se hab胤a[n]agotado ya...[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]Ni siquiera he desayunado.[n]Me estoy empezando a marear...[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]Aun as胤, en estas ocasiones[n]todo cobra un sabor delicioso...[n]斡Es un misterio![n][f 1 3 65535][w][e]

[sel SEL_033_0_0 top]
[s]Eso es porque estamos juntos.[e]
[s]Qu姻 pasada.[e]
[s]Me apetec胤a un kebab.[e]

[msg MSG_034_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Qu姻 po姻tico te pones, t胤o.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 40 65535 0]*risita* A pesar de este sudor[n]tan pegajoso.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 41 65535 0]P-pero mira, [f 4 2],[n]斡al menos hay granizados![n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 42 65535 0]Ya que hemos venido hasta aqu胤,[n]podemos ir a echar un vistazo[n]a esa cosa.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 43 65535 0]夷Qu姻 cosa?[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 44 65535 0]He o胤do que est茨n construyendo[n]una especie de estadio gigante[n]por aqu胤 cerca o algo as胤.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 45 65535 0]No tienes ni idea de lo que dices,[n]夷eh?[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 46 65535 0]Un estadio...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Ese tipo de construcciones suelen[n]tener una estructura intrigante[n]que me encantar胤a analizar.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]夷S胤? Pues venga, vamos.[n][f 1 3 65535][w][e]

