[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 3 4 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Morgana...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][bup 0 8 3 4 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Mona...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 3 4 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]El Meta-Nav no est茨...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Mementos tambi姻n debe[n]haber desaparecido...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][bup 0 8 3 4 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]No podremos[n]volver a ver a Mona... 夷verdad?[n][f 1 3 65535][w][e]

[sel SEL_004_0_0 top]
[s]Puede que no...[e]
[s]夷Qui姻n sabe...?[e]
[s]...[e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 3 4 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 3 4 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Est茨 bien.[n]Ya s姻 la respuesta.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][bup 0 8 3 4 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Est茨 bien.[n]Ya lo s姻...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 3 4 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]夷Qu姻 hac姻is todos tan depres?[n]Mona se reir胤a de nosotros...[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Por cierto, 夷qu姻 pasa con la gente?[n]夷Pudimos despertar sus corazones?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Mujer arreglada]]
[s][vp 8 0 0 11 65535 0]Voy a llegar tarde a mi cita...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Joven con mal aspecto]]
[s][vp 8 0 0 12 65535 0]Solo en Navidad...[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 3 4 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]A saber.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Hombre de mediana edad trajeado]]
[s][vp 8 0 0 14 65535 0]夷Vamos a empezar el a隠o[n]sin primer ministro?[n]夷No pasar茨 nada?[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Joven trajeado]]
[s][vp 8 0 0 15 65535 0]De Shido ya podemos olvidarnos.[n]Hay un mont吋n de rumores[n]sobre 姻l.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Haru]]
[s][bup 0 7 3 4 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Me pregunto c吋mo ir茨 todo...[n]Espero que bien...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Creamos en los adultos. Al fin[n]y al cabo, mi hermana nos lo prometi吋.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]De ahora en adelante,[n]que se encarguen los fiscales...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Si no podemos entrar[n]en el Metaverso, ya no tenemos[n]que ser los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Haru]]
[s][bup 0 7 3 4 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Me da un poco de pena...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]夷Qu姻 acabo de decir?[n]斡Ya vale de caras largas![n]斡Pensad en lo que acabamos de hacer![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Tienes raz吋n. Deber胤amos hacer[n]un brindis por la victoria.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Ann]]
[s][bup 0 4 3 4 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Oye, que somos menores de edad.[n]No podemos beber.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Pues pensemos en otra cosa.[n]夷Qu姻 hacen los atletas tras la victoria?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]夷Quieres hacer un corrillo?[n]Podemos juntarnos y entonar[n]un grito de la victoria.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Futaba]]
[s][bup 0 8 1 4 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Mola, pero estamos[n]en pleno centro de Shibuya,[n]rodeados de cientos de personas.[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][bup 0 2 4 4 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]斡夷Qu姻?! 斡夷Aqu胤 y ahora?![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Futaba]]
[s][bup 0 8 1 4 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]斡Vamos, Ryuji, espabila![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Yusuke]]
[s][bup 0 5 2 4 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Eso, despu姻s de todo lo que[n]hemos pasado, ya no tienes[n]nada que perder.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Ryuji]]
[s][bup 0 2 2 4 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]斡Oye, habla por ti![n]斡Yo tengo mucho que perder![n][f 1 3 65535][w][e]

[msg MSG_029_5_0 [Ryuji]]
[s][bup 0 2 2 4 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Acabemos con esto de una vez.[n]斡Que todo el mundo ponga las manos![n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Makoto]]
[s][bup 0 6 3 4 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]夷No crees que esto es pasarse?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ann]]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]Daos prisa, por favor. Me da igual[n]gritar, pero que sea r茨pido.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][bup 0 2 7 4 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Bueno, la celebraci吋n va genial.[n][f 1 3 65535][w][e]

[msg MSG_032_5_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Lo que t雨 digas.[n]Joker, t雨 te ocupas.[n][f 1 3 65535][w][e]

[sel SEL_033_0_0 top]
[s]Entendido.[e]
[s]Vaaaale...[e]
[s]Ni de co隠a.[e]

[msg MSG_034_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]Mmm, creo que lo l吋gico[n]es que t雨 tomes el mando.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 37 65535 0]斡Eso, hora de tomar el mando![n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Ryuji]]
[s][bup 0 2 2 4 0][f 4 10 65535 0 0][vp 8 0 0 38 65535 0]斡Que no! 斡De algo as胤[n]solo puede ocuparse el l胤der![n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 39 65535 0]Cuando nos d姻 la se隠al, lo seguimos[n]con un grito de victoria, 夷vale?[n]A la de una, a la de dos...[n][f 1 3 65535][w][e]

[sel SEL_038_0_0 top]
[s]斡Lo hemos logrado![e]
[s]斡Han despertado![e]

[msg MSG_039_0_0 [(SE)一同]]
[s][vp 8 0 0 0 65535 0](SE)オー![n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]La verdad es que me siento[n]mejor, como si todo hubiera terminado.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 48 65535 0]Pues puede ser. Cuanto m茨s[n]lo pienso, m茨s me doy cuenta[n]de la presi吋n que ten胤amos encima.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 49 65535 0]Ojal茨 podamos descansar un poco.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Ann]]
[s][bup 0 4 5 4 0][f 4 10 65535 0 0][vp 8 0 0 50 65535 0]Brr, 斡qu姻 fr胤o![n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Futaba]]
[s][bup 0 8 4 4 0][f 4 10 65535 0 0][vp 8 0 0 51 65535 0]斡Est茨 nevando![n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Ryuji]]
[s][bup 0 2 0 4 0][f 4 10 65535 0 0][vp 8 0 0 52 65535 0]Normal que haga fr胤o.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Ann]]
[s][bup 0 4 4 4 0][f 4 10 65535 0 0][vp 8 0 0 53 65535 0]夷A esto se refieren[n]con 或blanca Navidad位?[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Makoto]]
[s][bup 0 6 1 4 0][f 4 10 65535 0 0][vp 8 0 0 54 65535 0]Todav胤a es Nochebuena.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Haru]]
[s][bup 0 7 1 4 0][f 4 10 65535 0 0][vp 8 0 0 55 65535 0]Navidad... Se me hab胤a olvidado[n]por completo...[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Makoto]]
[s][bup 0 6 0 4 0][f 4 10 65535 0 0][vp 8 0 0 56 65535 0]En fin, ya veremos qu姻 pasa.[n]Deber胤amos tomarnos[n]el d胤a libre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 57 65535 0]Reun茨monos ma隠ana[n]en el Leblanc[n]para evaluar la situaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 58 65535 0]S胤, eso.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 59 65535 0]斡Eh![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 60 65535 0]Ma隠ana es Navidad. 斡夷Y si hacemos[n]una 雨ltima fiesta de celebraci吋n?![n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Ryuji]]
[s][bup 0 2 1 4 0][f 4 10 65535 0 0][vp 8 0 0 61 65535 0]斡Buena idea![n]斡Espero que nadie tenga planes![n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Ann]]
[s][bup 0 4 1 4 0][f 4 10 65535 0 0][vp 8 0 0 62 65535 0]斡Pues decidido![n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 63 65535 0]Convence al Jefe[n]para que cierre el Leblanc[n]para la fiesta.[n][f 1 3 65535][w][e]

[sel SEL_054_0_0 top]
[s]Eso est茨 hecho.[e]
[s]夷Que lo cierre...?[e]
[s]Una celebraci吋n...[e]

[msg MSG_055_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 64 65535 0]Lo dejamos en tus manos.[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Yusuke]]
[s][bup 0 5 0 4 0][f 4 10 65535 0 0][vp 8 0 0 64 65535 0]Lo dejamos en tus manos.[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 66 65535 0]Venga, no seas as胤.[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Yusuke]]
[s][bup 0 5 1 4 0][f 4 10 65535 0 0][vp 8 0 0 67 65535 0]Bueno, nos vemos ma隠ana.[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Futaba]]
[s][bup 0 8 0 4 0][f 4 10 65535 0 0][vp 8 0 0 68 65535 0]Me preocupa Sojiro.[n]Me voy a ir a casa.[n][f 1 3 65535][w][e]

[msg MSG_060_0_0 [Ann]]
[s][bup 0 4 0 4 0][f 4 10 65535 0 0][vp 8 0 0 69 65535 0]Deber胤amos irnos nosotros tambi姻n.[n][f 1 3 65535][w][e]

