[msg MSG_000_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]La excursi吋n est茨 llegando[n]a su fin...[n][f 1 3 65535][w][e]
[s][bup 0 6 1 1 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Nunca cre胤 que tambi姻n podr胤a[n]ir a una este curso...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 3 1 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Aunque es como si no hubi姻ramos[n]salido del pa胤s.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Si hasta vino Yusuke.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Me alegro de que la tormenta[n]no haya llegado aqu胤...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Puede que no haya sido una gran aventura,[n]pero nos lo hemos pasado muy bien.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 3 1 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]La verdad, me alegro de que no[n]tuvi姻ramos que lidiar con esas[n]tormentas. Son brutales...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]夷Al final qu姻 hiciste ayer? 夷Ahora[n]tienes secretos conmigo? 斡Eso no[n]lo hacen los colegas![n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]No te lo voy a decir.[e]
[s]Me fui la playa.[e]
[s]Estaba con alguien.[e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 5 1 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]斡夷Qu姻?! Eso huele a chamusquina[n]que no veas...[n][f 1 3 65535][w][e]
[s][bup 0 2 7 1 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Pero no pienso seguir curioseando.[n]Lo 雨ltimo que necesito es que tu[n]admiradora secreta me quiera matar.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 2 1 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]夷En serio, t雨 solo? 斡Es que ni de co隠a[n]me lo creo![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][bup 0 5 3 1 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]La desesperaci吋n que muestras[n]es muy inapropiada, Ryuji.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 4 1 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]斡T胤o! 斡夷En serio?![n][f 1 3 65535][w][e]
[s][bup 0 2 7 1 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Mejor no digas nada. Lo 雨ltimo que necesito[n]es que tu admiradora secreta[n]me quiera matar.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Ya basta, chicos.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 0 1 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]El viaje se me ha pasado volando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Ya no s姻 si quiero volver a casa o[n]quedarme unos d胤as m茨s aqu胤...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][bup 0 2 0 1 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Eh, 夷por qu姻 no vamos a comprar[n]recuerdos antes de irnos?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ann]]
[s][bup 0 4 1 1 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]斡Me apunto![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][bup 0 5 0 1 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Si no os importa, os acompa隠o.[n]Aunque yo no tengo dinero[n]para comprar nada.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][bup 0 6 3 1 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Pero 夷podr茨s volver a Jap吋n,[n]verdad?[n][f 1 3 65535][w][e]

