[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Dada la situaci吋n, s姻 que deber胤a[n]reprimir estos sentimientos...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Pero es Nochebuena.[n]Quiero pasarla contigo.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]夷Quieres que vayamos a dar[n]una vuelta... y que despu姻s vayamos[n]a tu habitaci吋n?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]En vista de las circunstancias,[n]no sab胤a si hablar o no, pero...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][f 5 14]Me gustar胤a pasar[n]la Nochebuena contigo.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]夷Y si vamos a dar una vuelta...[n]y despu姻s subimos a tu habitaci吋n?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]No s姻 muy bien c吋mo decirlo...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Quedemos, solo t雨 y yo.[n]No hace falta cont茨rselo a los dem茨s.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]夷Y si salimos a cenar[n]y despu姻s vamos a tu habitaci吋n?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]斡He llamado a Sojiro[n]y le parece guay![n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][f 5 14]Tengo una propuesta.[n]斡Pasemos la Nochebuena juntos![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][f 5 14]Quiero que pillemos pastel[n]y pollo asado[n]y vayamos a tu habitaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Chihaya]]
[s][f 5 14]He le胤do mi fortuna en el amor.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Chihaya]]
[s][f 5 14]Dec胤a que deber胤a profundizar[n]mi amor pasando tiempo[n]con mi pareja.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Chihaya]]
[s][f 5 14]夷Te parece bien?[n]夷O est茨s muy ocupado?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Takemi]]
[s][f 5 14]Cuando te acostumbras a tanto[n]hospital, la Navidad pierde[n]su encanto.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Takemi]]
[s][f 5 14]Pero supon胤a que querr胤as[n]hacer algo en pareja.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Takemi]]
[s][f 5 14]Podemos pasar la Nochebuena[n]juntos si te apetece.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Kawakami]]
[s][f 5 14]He acabado la tarea en clase.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Kawakami]]
[s][f 5 14]Podemos pasar la Nochebuena[n]juntos si te apetece,[n]pero sin compromiso...[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ohya]]
[s][f 5 14]Las cosas no van bien 雨ltimamente.[n]Me voy a tomar el d胤a libre.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ohya]]
[s][f 5 14]斡Hagamos algo juntos![n]夷Qu姻 te parece si vamos a tomar[n]t姻 y volvemos a tu casa?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Hifumi]]
[s][f 5 14]Hay mucha gente en la iglesia.[n]Est茨n preparando la misa.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Hifumi]]
[s][f 5 14]Seg雨n la tradici吋n, las parejas[n]pasan juntas esta noche,[n]夷no es cierto?[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Hifumi]]
[s][f 5 14]Me encantar胤a desconectar del shogi[n]y hacer algo contigo.[n][f 1 3 65535][w][e]

[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]He recibido unos cuantos mensajes.[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]夷Con qui姻n deber胤a quedar?[n][f 1 3 65535][w][e]

[sel SEL_027_0_0 top]
[s]Pasar un rato con Makoto[e]
[s]Pasar un rato con Haru[e]
[s]Pasar un rato con Ann[e]
[s]Pasar un rato con Futaba[e]
[s]Pasar un rato con Chihaya[e]
[s]Pasar un rato con Takemi[e]
[s]Pasar un rato con Kawakami[e]
[s]Pasar un rato con Ohya[e]
[s]Pasar un rato con Hifumi[e]

[msg MSG_028_0_0 [Makoto]]
[s][f 5 14]斡Gracias![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Makoto]]
[s][f 5 14]Ahora estoy en Shibuya,[n]as胤 que nos vemos aqu胤.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Haru]]
[s][f 5 14]斡夷En serio?![n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Haru]]
[s][f 5 14]斡Sigo en Shibuya! 斡Podemos quedar[n]frente a la estaci吋n![n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Ann]]
[s][f 5 14]斡Viva![n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Ann]]
[s][f 5 14]Sab胤a que dir胤as eso.[n]斡Resulta que ya estoy en Shibuya![n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Futaba]]
[s][f 5 14]斡斡斡!!![n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Futaba]]
[s][f 5 14]Sigo en Shibuya.[n]Vamos a quedar.[n]Me cansa tanta gente...[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Chihaya]]
[s][f 5 14]斡Gracias![n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Chihaya]]
[s][f 5 14]斡Cierro ya mismo y voy para all茨![n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Takemi]]
[s][f 5 14]Gracias. Eso era lo que quer胤a.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Takemi]]
[s][f 5 14]Voy a cerrar ya.[n]Quedemos para dar una vuelta.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Kawakami]]
[s][f 5 14]斡夷De verdad?! 斡Qu姻 guay, en serio![n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Kawakami]]
[s][f 5 14]斡Estoy que lo flipo![n]En breve salgo para la ciudad.[n][f 1 3 65535][w][e]

[msg MSG_042_0_0 [Ohya]]
[s][f 5 14]斡Genial! 斡Vamos![n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Ohya]]
[s][f 5 14]夷Nos vemos en Shibuya?[n]Te espero al lado de la estaci吋n.[n][f 1 3 65535][w][e]

[msg MSG_044_0_0 [Hifumi]]
[s][f 5 14]Gracias. La verdad[n]es que estoy un poco nerviosa[n]porque no tengo experiencia.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Hifumi]]
[s][f 5 14]夷Nos vemos en Shibuya?[n]Hasta ahora.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Deber胤a ir al sitio acordado.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Sojiro]]
[s][f 5 14]夷Qu姻 te traes entre manos?[n]Futaba me ha escrito[n]y me ha dicho que iba a venir.[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Sojiro]]
[s][f 5 14]Ven ahora mismo[n]a echarnos una mano.[n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Sojiro]]
[s][f 5 14]斡Vale! Te estar姻 esperando.[n][f 1 3 65535][w][e]

[msg MND_003_0_0]
[s][vp 8 0 0 0 65535 0]Deber胤a irme...[n][f 1 3 65535][w][e]

