[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Un momento. 夷Escuch茨is algo?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Los trenes siguen funcionando![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pues claro.[n]Estamos en el metro, 夷sabes?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]S胤, pero 斡pensaba que esto era un Palacio![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Entonces, 夷as胤 es como el p雨blico[n]ve este lugar? A saber.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷La gente pasa por esta oscuridad[n]todos los d胤as...?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Y qu姻 m茨s da? 夷Seguro que no pasa[n]nada por estar corriendo por las v胤as?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No deber胤a pasar nada mientras no[n]estemos en las mismas, creo.[n]No soy experto en trenes.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷En serio?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, que hay que ir a la zona[n]inferior. Deber胤a estar justo despu姻s[n]de bajar por las escaleras.[n][f 1 3 65535][w][e]

