[msg MSG_000_0_0 [Peat吋n]]
[s][vp 8 0 0 1 65535 0]夷Qu姻 le pasa al viejo ese?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Peatona]]
[s][vp 8 0 0 2 65535 0]夷Est茨 llorando?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Madarame]]
[s][bup 0 203 3 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Yo... He cometido delitos[n]impropios de un artista.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Para que quede m茨s claro,[n]he plagiado obras...[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Madarame]]
[s][bup 0 203 3 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]H-he... mancillado el nombre...[n]de mi pa胤s... y...[n]hasta el 或Sayuri位...[n][f 1 3 65535][w][e]

[msg MSG_003_5_0 [Madarame]]
[s][bup 0 203 8 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]C-c吋mo podr胤a...[n]disculparme...[n]por lo que he hecho...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Peat吋n]]
[s][vp 8 0 0 7 65535 0]Est茨 llorando una barbaridad...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Presentador de telediario]]
[s][vp 8 0 0 8 65535 0]Por eso ha dado una rueda de prensa[n]urgente hace unos minutos.[n]Quer胤a pedir disculpas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 65535 0]Tras informar a la asociaci吋n,[n]Madarame ha aceptado la petici吋n[n]de la polic胤a y se ha entregado.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Peatona]]
[s][vp 8 0 0 10 65535 0]夷No sali吋 en la tele el otro d胤a?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Presentador de telediario]]
[s][vp 8 0 0 11 65535 0]Adem茨s de los cargos por abusar de sus[n]alumnos, Madarame est茨 siendo investigado[n]por apropiarse de sus obras.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 12 65535 0]Algunos dudan que[n]robaran el 或Sayuri位 y creen[n]que fue objeto de alg雨n fraude.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 13 65535 0]Este delito a gran escala ha[n]causado una enorme conmoci吋n[n]en el mundo art胤stico y...[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Peatona]]
[s][vp 8 0 0 14 65535 0]Ese vejestorio est茨 acabado.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Presentador de telediario]]
[s][vp 8 0 0 15 65535 0]Tras la rueda de prensa, Madarame[n]fue trasladado al hospital de la[n]polic胤a, donde lo interrogaron.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 16 65535 0]No obstante, las evaluaciones[n]psiqui茨tricas previas indican que[n]est茨 en plenas facultades mentales.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Peat吋n]]
[s][vp 8 0 0 17 65535 0]No hay que ser agradables[n]con un viejo como 姻l.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Peat吋n]]
[s][vp 8 0 0 18 65535 0]夷Por qu姻 lo larga todo?[n]Me parece rar胤simo.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Presentador de telediario]]
[s][vp 8 0 0 19 65535 0]El grupo que se autodenomina[n]los Ladrones Fantasma ha colocado[n]una nota en la exhibici吋n.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 20 65535 0]La polic胤a investigar茨 su[n]relaci吋n con el caso, pero de[n]momento no los considera sospechosos.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Peat吋n]]
[s][vp 8 0 0 27 65535 0]夷Los Ladrones Fantasma? 夷Esos[n]bandidos tienen algo que ver[n]con las disculpas del viejales?[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Peatona]]
[s][vp 8 0 0 28 65535 0]Ah, he o胤do hablar de ellos. Dicen[n]que despiertan corazones malvados y[n]por eso los culpables piden perd吋n.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Peatona]]
[s][vp 8 0 0 29 65535 0]夷Que despiertan corazones?[n]Anda ya.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Peat吋n]]
[s][vp 8 0 0 30 65535 0]Creo que le胤 algo sobre eso[n]en internet. Enviaron[n]un aviso de verdad.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Peat吋n]]
[s][vp 8 0 0 31 65535 0]Pon胤a algo en plan 或Te arrancaremos[n]el coraz吋n位. Ser胤a tremendo[n]que alguien lo hiciera de verdad.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Chico simp茨tico]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Los Ladrones Fantasma, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Otra vez los Ladrones Fantasma...[n][f 1 3 65535][w][e]

