[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 104 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ese era... el doctor Maruki, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]S胤, estoy seguro.[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]No podemos negar lo que hemos visto.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Por lo que hemos visto, podr胤amos inferir[n]que los recuerdos del doctor Maruki[n]acabaron de alg雨n modo en esa cinta.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sumire]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Esa forma de actuar de la chica[n]al final... A m胤 me ocurri吋 lo mismo...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][bup 0 6 100 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]As胤 que reescribi吋 su cognici吋n...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Por lo que dec胤a en el v胤deo, ese[n]podr胤a ser el momento en el que[n]despert吋 su habilidad.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sumire]]
[s][bup 0 10 100 0 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Acaso el doctor Maruki quer胤a[n]que vi姻ramos este recuerdo?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Eh, no creo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Puede que fuera un mero recuerdo[n]que intent吋 enterrar[n]en su inconsciente.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 810 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Aun as胤, si ocurri吋 de verdad, no hay[n]duda de lo importante que es[n]para Maruki.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][bup 0 5 100 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Ya sea para bien o para mal, parece[n]que esto fue lo que llev吋 al doctor[n]Maruki a su misi吋n actual...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Haru]]
[s][bup 0 7 100 0 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Tienes raz吋n.[n][f 1 3 65535][w][e]

