[msg MSG_000_0_0 [Shibusawa]]
[s][bup 0 222 502 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 4 0]斡Mierda! O胤rlo de tu boca me est茨 cabreando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 4 0]Has llegado tan lejos... 斡夷Qu姻[n]problema podr胤a haber?![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Maruki]]
[s][bup 0 216 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Intent姻 negociarlo en persona[n]con el profesor y los inversores,[n]pero no me escucharon.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]或Las investigaciones e inversiones[n]en el campo de la psiencia cognitiva[n]se detendr茨n por falta de pruebas concretas位.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Me dijeron que se acab吋.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Maruki]]
[s][bup 0 216 905 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Pero 夷por qu姻 precisamente ahora?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]斡La primera vez que vieron[n]mi investigaci吋n, estaban muy[n]emocionados![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Shibusawa]]
[s][bup 0 222 503 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 4 0]Y el laboratorio de investigaci吋n de Odaiba...[n]夷Ya no van a seguir con eso?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Maruki]]
[s][bup 0 216 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]S胤...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Maruki]]
[s][bup 0 216 902 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Joder. 斡A la mierda[n]con sus 或pruebas concretas位![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]斡夷C吋mo vamos a conseguir pruebas[n]si no podemos hacer ninguna[n]investigaci吋n?![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Si podemos cambiar la cognici吋n[n]de gente con traumas, podr胤amos[n]acabar con su sufrimiento...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]A saber cu茨nta gente podr胤a[n]salvarse con esta investigaci吋n.[n]夷No son obvios los beneficios?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Shibusawa]]
[s][bup 0 222 503 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 4 0]Entonces, 夷crees que[n]todo se ha ido al traste[n]por falta de pruebas?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Maruki]]
[s][bup 0 216 903 65535 0][vp 1 0 0 15 0 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]No tiene ning雨n sentido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]Despu姻s del tiempo y el dinero invertido...[n]van y paran la investigaci吋n[n]por falta de pruebas inmediatas.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Maruki]]
[s][bup 0 216 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Incluso si todo fuera todo parte de[n]una conspiraci吋n, 夷qu姻 podr胤a hacer?[n]No tengo ninguna prueba.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Shibusawa]]
[s][bup 0 222 503 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 4 0]Ah...[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Shibusawa]]
[s][bup 0 222 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 4 0]夷Y qu姻 vas a hacer ahora?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 23 4 0]Los patrocinadores se han echado atr茨s,[n]as胤 que dudo que la universidad[n]te deje usar los laboratorios...[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Maruki]]
[s][bup 0 216 903 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Estoy harto de esa universidad.[n]Ya no pueden aportarme nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Buscar姻 trabajo en otro sitio mientras[n]sigo completando la investigaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]En alg雨n momento podr姻 probar que[n]el mundo cognitivo existe. Nadie[n]podr茨 quejarse entonces.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Maruki]]
[s][bup 0 216 907 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Rumi...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Te juro que lo conseguir姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]Ahora puedo... Me ha costado[n]mi vida contigo.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Maruki]]
[s][bup 0 216 907 65535 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]As胤 que voy a liberar a todo el mundo[n]de su dolor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Me da igual cu茨nto tarde.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]Lo har姻.[n][f 1 3 65535][w][e]

