[msg MSG_FIRSTROULETTE_001_00 [Sombra de Sae]]
[s][vp 8 0 2 1008 1 228]Bueno, 夷cu茨l es tu apuesta?[n][w][e]

[sel SEL_FIRSTROULETTE_001_00 top]
[s]Apuesta arriesgada y muy rentable[e]
[s]Apuesta segura y poco rentable[e]

[msg MSG_FIRSTROULETTE_002_00 [Sombra de Sae]]
[s]夷D吋nde caer茨 la bola...?[n]夷Rojo o negro?[n][w][e]

[sel SEL_FIRSTROULETTE_002_00 top]
[s]Una casilla roja[e]
[s]Una casilla negra[e]

[msg MSG_FIRSTROULETTE_002_00_2 [Sombra de Sae]]
[s]夷Por qu姻 casillas apuesto...?[n][w][e]

[sel SEL_FIRSTROULETTE_002_00_2 top]
[s]Casillas de la 1 a la 12[e]
[s]Casillas de la 13 a la 24[e]
[s]Casillas de la 25 a la 36[e]

[msg MSG_FIRSTROULETTE_002_00_3 [Sombra de Sae]]
[s]夷Por qu姻 casillas apuesto...?[n][w][e]

[sel SEL_FIRSTROULETTE_002_00_3 top]
[s]Casillas de la 1 a la 6[e]
[s]Casillas de la 7 a la 12[e]
[s]Casillas de la 13 a la 18[e]
[s]Casillas de la 19 a la 24[e]
[s]Casillas de la 25 a la 30[e]
[s]Casillas de la 31 a la 36[e]

[msg MSG_SECONDROULETTE_000_0 [Sombra de Sae]]
[s]夷Cu茨l deber胤a ser mi apuesta...?[n][w][e]

