[msg CMB00_DUMMY]
[s]Dummy[n][w][e]

[msg CMB00_MSG_001 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5001 0 0]*risita* No te preocupes.[n]Las Personas nacen del interior...[n][w][e]

[msg CMB00_MSG_002 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5002 0 0]Cuando te deshaces de tu antigua[n]identidad, creas una nueva.[n]Por eso esto se llama 或ejecuci吋n位.[n][w][e]

[msg CMB00_MSG_003 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5003 0 0]Piensa que se trata[n]de una fusi吋n de tus Personas.[n][w][e]

[msg CMB00_MSG_004 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5004 0 0]Ahora probemos[n]con una fusi吋n de Personas real.[n][w][e]

[msg CMB00_MSG_005 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5005 0 0]Elige la primera Persona[n]que quieres fusionar.[n][w][e]

[msg CMB00_MSG_006 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5006 0 0]Antes de elegir la segunda,[n]te contar姻 algo[n]de suma importancia.[n][w][e]

[msg CMB00_MSG_007 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5007 0 0]夷Recuerdas aquello que dije sobre[n]formar v胤nculos con Confidentes?[n][w][e]

[msg CMB00_MSG_008 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5008 0 0]Las Personas son el poder del[n]coraz吋n... Cuanto m茨s fuerte sea un v胤nculo,[n]m茨s poderosa ser茨 tu Persona.[n][w][e]

[msg CMB00_MSG_015 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5009 0 0]Se puede decir que los efectos[n]de tus v胤nculos en la ejecuci吋n...[n]o en la fusi吋n son substanciales.[n][w][e]

[msg CMB00_MSG_016 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5010 0 0]Si fusionas una Persona[n]que comparte arcano con uno de[n]tus v胤nculos, obtendr茨 mucho poder.[n][w][e]

[msg CMB00_MSG_017 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5011 0 0]Este ser茨 un principio b茨sico[n]durante tus avances en la fusi吋n.[n]Que no se te olvide.[n][w][e]

[msg CMB00_MSG_018 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5012 0 0]Adem茨s, hay otra cosa[n]de la que he de advertirte.[n][w][e]

[msg CMB00_MSG_019 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5013 0 0]No puedes crear una Persona[n]que supere tu nivel actual.[n][w][e]

[msg CMB00_MSG_020 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5014 0 0]Eso dar胤a lugar a una Persona[n]demasiado poderosa y no podr胤as[n]controlarla eficazmente.[n][w][e]

[msg CMB00_MSG_021 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5015 0 0]Ahora, echa un vistazo a los[n]resultados de la fusi吋n y elige una[n]Persona que se adapte a tu nivel.[n][w][e]

[msg CMB00_MSG_009 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5016 0 0]Esta es la forma que se espera[n]que coja tu Persona tras la fusi吋n.[n][w][e]

[msg CMB00_MSG_010 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5017 0 0]Pueden heredar habilidades[n]que normalmente no obtendr胤an.[n][w][e]

[msg CMB00_MSG_011 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Adem茨s, aparte de las habilidades,[n]las Personas tienen especialidades.[n][w][e]

[msg CMB00_MSG_012 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5019 0 0]Las habilidades y las especialidades[n]son diferentes. Las primeras son atributos[n]que se pueden conseguir mediante la fusi吋n.[n][w][e]

[msg CMB00_MSG_012_01 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Las especialidades de una Persona[n]no se pueden heredar.[n][w][e]

[msg CMB00_MSG_012_02 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0]Pero no hace falta que pienses[n]en eso ahora. De momento[n]selecciona la que quieras.[n][w][e]

[msg CMB00_MSG_013 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0][vp 1 0 0 5048 0 0]斡El Maestro a雨n no ha acabado![n]斡Hazle caso, recluso![n][w][e]

[msg CMB00_MSG_TUTORIAL_ELECT [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Este ritual te permite[n]sacrificar Personas[n]y transmutarlas en objetos.[n][w][e]
[s][f 4 10 65535 0 0]Perder茨s la Persona, pero[n]obtendr茨s objetos[n]como armas y accesorios 雨tiles.[n][w][e]
[s][f 4 10 65535 0 0]Registraremos el resultado[n]de la transmutaci吋n de cada Persona[n]en el Registro de reclusos.[n][w][e]
[s][f 4 10 65535 0 0]Cada vez que hagas un sacrificio,[n]necesitar茨s un material especial[n]capaz de transmutar.[n][w][e]
[s][f 4 10 65535 0 0]Seguramente no sepas lo que es,[n]as胤 que toma este y ent姻rate.[n]斡Ya puedes estar agradecido![n][w][e]
[s][f 4 10 65535 0 0]Las encontrar茨s tambi姻n[n]en tu realidad, no solo en la otra.[n]斡Esfu姻rzate para encontrarlas![n][w][e]

[msg CMB00_MSG_TUTORIAL_ELECT_2 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Este ritual sirve para sacrificar[n]Personas y transmutarlas[n]en objetos.[n][w][e]
[s][f 4 10 65535 0 0]Perder茨s la Persona, pero[n]a cambio obtendr茨s objetos 雨tiles[n]como armas y accesorios.[n][w][e]
[s][f 4 10 65535 0 0]Registrar姻 los resultados de la[n]transmutaci吋n en el Compendio de[n]Personas. Tal vez te resulte 雨til.[n][w][e]
[s][f 4 10 65535 0 0]Para ofrecer un sacrificio[n]necesitar茨s un material especial[n]capaz de transmutar.[n][w][e]
[s][f 4 10 65535 0 0]Creo que verlo en acci吋n[n]ser茨 m茨s eficaz que explicarlo,[n]as胤 que te dar姻 uno.[n][w][e]
[s][f 4 10 65535 0 0]Deber胤as poder encontrar[n]estos materiales en ambas[n]realidades. Mantente alerta.[n][w][e]

[msg CMB00_MSG_CELL_001 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Si metes a una de tus Personas en[n]una jaula, le daremos un 或trato[n]especial位 para que mejore.[n][w][e]
[s][f 4 10 65535 0 0]Eso s胤, solo puedes meter[n]a una Persona por vez.[n][w][e]
[s][f 4 10 65535 0 0]Mientras est姻 encerrada, no podr茨s[n]usarla en combate ni en fusiones.[n]斡Si se te olvida, es cosa tuya![n][w][e]
[s][f 4 10 65535 0 0]D胤a a d胤a, tu Persona se volver茨[n]m茨s fuerte y aprender茨[n]una nueva resistencia.[n][w][e]
[s][f 4 10 65535 0 0]Y eso no es todo. Si quemas[n]incienso, 斡la Persona[n]se volver茨 todav胤a m茨s fuerte![n][w][e]
[s][f 4 10 65535 0 0]Si quieres m茨s detalles, podr茨s[n]preguntar m茨s adelante. Por ahora,[n]mete una Persona en Confinamiento.[n][w][e]

[msg CMB00_MSG_CELL_001_001 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]斡Vaya! No s姻 de d吋nde has sacado[n]ese incienso, pero deber胤as[n]usarlo con esta Persona.[n][w][e]
[s][f 4 10 65535 0 0]Escoge una Persona, enci姻rrala[n]y despu姻s quema el incienso. Ver茨s[n]los efectos ma隠ana como pronto.[n][w][e]

[msg CMB00_MSG_CELL_001_002 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]夷C吋mo? 夷No tienes incienso?[n]Vale, te dar姻 este, pero 斡no pidas[n]m茨s! Se acabaron los regalitos.[n][w][e]
[s][f 4 10 65535 0 0]Escoge una Persona, enci姻rrala[n]y despu姻s quema el incienso. Ver茨s[n]los efectos en unos d胤as.  [n][w][e]

[msg CMB00_MSG_CELL_001_L [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Si metes a una de tus Personas en[n]una jaula, recibir茨 entrenamiento[n]especial para que mejore.[n][w][e]
[s][f 4 10 65535 0 0]Eso s胤, solo puedes meter[n]a una Persona por vez.[n][w][e]
[s][f 4 10 65535 0 0]Adem茨s, la Persona en aislamiento[n]no estar茨 disponible[n]para las batallas o las fusiones.[n][w][e]
[s][f 4 10 65535 0 0]D胤a a d胤a, tu Persona se volver茨[n]m茨s fuerte y aprender茨[n]una nueva resistencia.[n][w][e]
[s][f 4 10 65535 0 0]No solo eso, sino que podr茨s[n]aumentar el ritmo de crecimiento[n]quemando incienso.[n][w][e]
[s][f 4 10 65535 0 0]Si deseas saber m茨s, pregunta[n]m茨s adelante. Por ahora, mete[n]una Persona en Confinamiento.[n][w][e]

[msg CMB00_MSG_CELL_001_001_L [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Parece que ya tienes incienso.[n][w][e]
[s][f 4 10 65535 0 0]Encierra una Persona y despu姻s[n]quema el incienso. Ver茨s el efecto[n]cuando pase el tiempo suficiente.[n][w][e]

[msg CMB00_MSG_CELL_001_002_L [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Todav胤a no tienes incienso.[n]Te dar姻 un poco,[n]pero solo por esta vez.[n][w][e]
[s][f 4 10 65535 0 0]Encierra la Persona y despu姻s[n]quema el incienso. Ver茨s el efecto[n]cuando pase el tiempo suficiente.[n][w][e]

[msg CMB00_MSG_CELL_002 [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Hecho eso, solo queda esperar.[n]Pero 斡no la dejes sola[n]demasiado tiempo![n][w][e]
[s][f 4 10 65535 0 0]La Persona es parte de tu coraz吋n.[n]Si est茨 lejos de ti demasiado[n]tiempo, podr胤a desaparecer.[n][w][e]
[s][f 4 10 65535 0 0]Te daremos un solo aviso antes[n]de que suceda, pero despu姻s[n]depende de ti.[n][w][e]

[msg CMB00_MSG_CELL_002_L [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Debes esperar hasta que acabe[n]el entrenamiento, pero es peligroso[n]dejar la Persona demasiado tiempo.[n][w][e]
[s][f 4 10 65535 0 0]Una Persona forma parte de tu[n]coraz吋n. Si os separ茨is durante[n]mucho tiempo, desaparecer茨.[n][w][e]
[s][f 4 10 65535 0 0]Solo te dar姻 un aviso antes[n]de que desaparezca. Si no tomas[n]medidas, habr茨 consecuencias.[n][w][e]

[sel CMB00_SEL_WARNING_ACC top]
[s]Que siga.[e]
[s]Mejor no.[e]

[msg CMB00_MSG_WARNING_ACC_00 [Caroline]]
[s][bup 0 102 2 0 0][f 4 10 65535 0 0]El equipo se ha vuelto inestable.[n]Cuidado con los accidentes.[n][w][e]
[s][f 4 10 65535 0 0]No garantizamos que los resultados[n]sean lo que esperas.[n]夷Aun as胤 deseas continuar?[n][w][e]

[msg CMB00_MSG_WARNING_ACC_01 [Caroline]]
[s][bup 0 102 4 0 0][f 4 10 65535 0 0]Toda ejecuci吋n ser茨[n]bastante arriesgada ahora mismo.[n][w][e]
[s][f 4 10 65535 0 0]No garantizamos que los resultados[n]sean lo que esperas.[n]夷Aun as胤 deseas continuar?[n][w][e]

[msg CMB00_MSG_WARNING_ACC_YE [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Vale, la alarma se queda encendida.[n][w][e]

[msg CMB00_MSG_WARNING_ACC_NO [Caroline]]
[s][bup 0 102 0 0 0][f 4 10 65535 0 0]Vale, apagaremos la alarma.[n]Pero 斡no dejes de lado[n]tu rehabilitaci吋n, recluso![n][w][e]

[msg CMB00_MSG_WARNING_ACC_00_2 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]El equipo se ha vuelto inestable.[n]Cuidado con los accidentes.[n][w][e]
[s][f 4 10 65535 0 0]No garantizo que los resultados[n]sean lo que esperas.[n]夷Aun as胤 quieres continuar?[n][w][e]

[msg CMB00_MSG_WARNING_ACC_01_2 [Lavenza]]
[s][bup 0 100 4 0 0][f 4 10 65535 0 0]Es muy arriesgado realizar[n]ejecuciones en estos momentos.[n][w][e]
[s][f 4 10 65535 0 0]No garantizo que los resultados[n]sean lo que esperas.[n]夷Aun as胤 quieres continuar?[n][w][e]

[msg CMB00_MSG_WARNING_ACC_YE_2 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Muy bien, que siga la alarma.[n][w][e]

[msg CMB00_MSG_WARNING_ACC_NO_2 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0]Muy bien, har姻 que cese la alarma.[n]Pero te pido que sigas trabajando[n]duro en tu rehabilitaci吋n.[n][w][e]

