[sel QST_MSG_SELECT top]
[s]はい[e]
[s]いいえ[e]

[msg QST_MSG_PRIZE [桜庭 志乃]]
[s]依頼完了、確認しました。[n]ありがとう、報酬を渡すわね。[n][w][e]

[msg QST_MSG_TOP [桜庭 志乃]]
[s]何か用?[n][e]

[msg QST_MSG_MAIN [桜庭 志乃]]
[s]今お願いしたい依頼は、これ。[n][e]

[msg QST_MSG_OK [桜庭 志乃]]
[s]この依頼を受けるの?[n][w][e]

[msg QST_MSG_CANCEL [桜庭 志乃]]
[s]この依頼をやめるの?[n][w][e]

[msg QST_MSG_OK_END [桜庭 志乃]]
[s]じゃぁ、よろしくね。[n][w][e]

[msg QST_MSG_END [桜庭 志乃]]
[s]またね。[n][w][e]

