[msg HELP_URANAI_OPEN [運命 テラー]]
[s]斡Has sellado un contrato con la[n]adivina del arcano de la Fortuna![n][w][e]

[msg HELP_URANAI_ARCANA_BONUS [合体ボーナス]]
[s][vp 8 0 0 0 65535 0]斡Ganar茨s una bonificaci吋n[n]de experiencia cuando fusiones una[n]Persona del arcano de la Fortuna![n][f 1 3 65535][w][e]

[msg HELP_URANAI_FUNCTION [本日の占い]]
[s]Ahora la adivina puede [clr 2]leer[n]el futuro del d胤a a d胤a[clr 27].[n][f 1 3 65535][w][e]
[s]Sigue estrechando lazos[n]para mejorar el v胤nculo y que ella[n]realice m茨s [clr 2]tipos de lecturas[clr 27].[n][f 1 3 65535][w][e]

