[msg MSG_000_0_0]
[s][vp 8 0 0 0 65535 0]すみれコープランク9[n]メッセージダミー[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]Deber胤a tener mucho[n]cuidado con lo que digo.[n][f 1 3 65535][w][e]

[msg MND_035_0_0]
[s][vp 8 0 0 0 65535 0]Deber胤a tener mucho[n]cuidado con lo que digo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ya tengo [clr 2]una relaci吋n[n]con otra chica[clr 27].[n][f 1 3 65535][w][e]

