[msg MSG_000_0_0]
[s]Dummy[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]斡T胤o, es que no paran![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]斡En cuanto les d姻 esquinazo,[n]nos vemos en el esconsdhakf![n][f 1 3 65535][w][e]

[msg MSG_026_7_0 [Ryuji]]
[s][f 5 14]eeeeeeh, tio! olvida lo q he dicho[n]JUAS me piro de compras[n][f 1 3 65535][w][e]
[s][f 5 14]luego t env胤o unas fotos[n]quando me ponga requetemono ;D[n][f 5 15][f 1 3 65535][w][e]

