[msg MSG_Start_Ruyji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Oye, parece que lo vas pillando.[n]夷Ya te sientes un maestro del caf姻?[n][f 1 3 65535][w][e]

[msg MSG_Start_Yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4135 65535 0]Est茨s incre胤ble. Claro,[n]que cualquiera lo estar胤a[n]con el atuendo adecuado.[n][f 1 3 65535][w][e]

[msg MSG_Start_Futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9034 65535 0]斡Eh, barista! El traje[n]te queda como un guante.[n][f 1 3 65535][w][e]

[msg MSG_Start_Moru [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]No te preocupes.[n]Yo te vigilar姻 y me asegurar姻[n]de que no la cagas.[n][f 1 3 65535][w][e]

[msg MND_Start]
[s][vp 8 2 0 0 65535 0]Deber胤a verter el agua caliente.[n][f 1 3 65535][w][e]

[msg MND_FriendThink_Ryuji]
[s][vp 8 2 0 0 65535 0]Ryuji tiene una mirada intensa.[n]Parece que alberga[n]grandes expectativas.[n][f 1 3 65535][w][e]

[msg MND_FriendThink_Yusuke]
[s][vp 8 2 0 0 65535 0]Yusuke tiene una mirada intensa.[n]Parece que alberga[n]grandes expectativas.[n][f 1 3 65535][w][e]

[msg MND_FriendThink_Futaba]
[s][vp 8 2 0 0 65535 0]Futaba tiene una mirada intensa.[n]Parece que alberga[n]grandes expectativas.[n][f 1 3 65535][w][e]

[sel SEL_FriendService top]
[s]Hacer lo que me han ense隠ado[e]
[s]Ponerle un poco de cari隠o[e]

[msg MSG_Trouble_type01_A_Mor [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oye, 夷no est茨s echando[n]el agua demasiado despacio?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Por qu姻 no echas m茨s?[n]Los granos tienen que mojarse bien.[n][f 1 3 65535][w][e]

[msg MSG_Trouble_type01_A_Ryu [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oye, 夷no se va a enfriar el caf姻[n]si lo echas tan despacio?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Date prisa! 斡Quiero que[n]est姻 ardiendo![n][f 1 3 65535][w][e]

[msg MSG_Trouble_type01_A_Yus [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Personalmente, creo que[n]el caf姻 se va a resecar[n]si lo echas tan despacio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]La pintura se seca conforme[n]pasa el tiempo... 夷Por qu姻 no[n]a隠ades m茨s agua caliente?[n][f 1 3 65535][w][e]

[msg MSG_Trouble_type01_A_Fut [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Qu姻 lentitud... y qu姻 aburrimiento...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Si fueran fideos, estar胤an[n]pastosos cuando terminaras[n]de hacerlos![n][f 1 3 65535][w][e]

[msg MND_Trouble_type01_A]
[s][vp 8 2 0 0 65535 0]Quiz茨 la he vertido muy despacio...[n][f 1 3 65535][w][e]

[sel SEL_Trouble_Type01_A top]
[s]Seguir a esta velocidad[e]
[s]Echar m茨s r茨pido[e]

[msg MSG_Trouble_type01_B_Mor [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oye, 夷seguro que hay que echar[n]el agua caliente tan r茨pido?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Me gusta que lo hagas con[n]fuerza, pero te falta delicadeza.[n][f 1 3 65535][w][e]

[msg MSG_Trouble_type01_B_Ryu [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Seguro que tienes que echar toda[n]esa agua de golpe?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece arriesgado, pero 夷ese es[n]el secreto? Hacer caf姻 es m茨s[n]complicado de lo que pensaba.[n][f 1 3 65535][w][e]

[msg MSG_Trouble_type01_B_Yus [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No quiero interrumpir, pero[n]夷seguro que esa es la forma[n]correcta de echar el agua?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]La pintura se agua si se[n]a隠ade demasiada...[n]夷Pasar茨 lo mismo con el caf姻?[n][f 1 3 65535][w][e]

[msg MSG_Trouble_type01_B_Fut [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Hala, es como una cascada![n]斡C吋mo cae esa agua caliente![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Ah, ya lo pillo! Al salpicar[n]tanto, haces que nos llegue[n]el aroma, 夷no?[n][f 1 3 65535][w][e]

[msg MND_Trouble_type01_B]
[s][vp 8 2 0 0 65535 0]Quiz茨 la he vertido muy r茨pido...[n][f 1 3 65535][w][e]

[sel SEL_Trouble_Type01_B top]
[s]Esta velocidad est茨 bien[e]
[s]Echar m茨s despacio[e]

[msg MSG_Trouble_type02_A_Mor [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece que te has dejado algunos[n]posos en el borde del filtro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Intenta echarles m茨s agua.[n]Si no, no conseguir茨s tanto[n]sabor al final.[n][f 1 3 65535][w][e]

[msg MSG_Trouble_type02_A_Ryu [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Te has dejado mucho caf姻[n]en el filtro... 夷Por qu姻 no[n]haces algo al respecto?[n][f 1 3 65535][w][e]

[msg MSG_Trouble_type02_A_Yus [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece que hay muchos posos[n]residuales en el per胤metro[n]del filtro...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Te ha costado mucho moler[n]los granos. 郁salo todo y[n]no lo desperdicies.[n][f 1 3 65535][w][e]

[msg MSG_Trouble_type02_A_Fut [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Has dejado muchos posos[n]en el borde del filtro![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Qu姻 vas a hacer con ellos?[n]夷Tirarlos?[n][f 1 3 65535][w][e]

[msg MND_Trouble_type02_A]
[s][vp 8 2 0 0 65535 0]Parece que he dejado algunos posos[n]por el borde del filtro...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]夷Vierto m茨s agua caliente?[n][f 1 3 65535][w][e]

[sel SEL_Trouble_Type02_A top]
[s]Est茨 bien as胤[e]
[s]Echar m茨s agua[e]

[msg MSG_SelFix_Moru [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Espero que tomaras[n]la decisi吋n correcta.[n][f 1 3 65535][w][e]

[msg MSG_SelFix_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Siempre que sepa bien,[n]me da igual lo que hagas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Oye! 斡A m胤 ponme[n]mucha leche y az雨car![n][f 1 3 65535][w][e]

[msg MSG_SelFix_Yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Me muero de ganas[n]de tomar una buena taza de caf姻.[n][f 1 3 65535][w][e]

[msg MSG_SelFix_Futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mi cuerpo est茨 listo.[n][f 1 3 65535][w][e]

[msg MND_500_0_0]
[s][vp 8 2 0 0 65535 0]Creo que no he cometido[n]ning雨n error.[n][f 1 3 65535][w][e]

[msg MND_500_1_0]
[s][vp 8 2 0 0 65535 0]夷He cometido un error?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1184 65535 0]斡Mmm! Me encanta el aroma[n]de un buen caf姻.[n][f 1 3 65535][w][e]

[msg MSG_019_1_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7069 65535 0]斡Vaya! T胤o, pareces todo[n]un profesional preparando caf姻.[n][f 1 3 65535][w][e]

[msg MSG_019_3_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4023 65535 0]Mmm... 斡Menudo aroma![n][f 1 3 65535][w][e]

[msg MSG_019_6_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 9105 65535 0]Qu姻 nivel吋n... 夷Cu茨ndo[n]has mejorado tanto?[n][f 1 3 65535][w][e]

[msg MND_019_7_0]
[s][vp 8 2 0 0 65535 0]Parece que todo ir茨 sobre ruedas...[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Te lo bebes de tal forma que[n]cualquiera dir胤a que est茨[n]delicioso.[n][f 1 3 65535][w][e]

[msg MSG_029_1_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Hala! 斡Esto es incre胤ble![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Me gusta el caf姻! T胤o,[n]y yo que he estado renegando[n]de 姻l toda mi vida...[n][f 1 3 65535][w][e]

[msg MSG_029_3_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Exquisito.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Sabe casi igual que el del Jefe.[n][f 1 3 65535][w][e]

[msg MSG_029_6_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]S胤. 斡Es como el de Sojiro![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Cuando lo bebo, me siento en casa.[n][f 1 3 65535][w][e]

[msg MND_029_7_0]
[s][vp 8 2 0 0 65535 0]No s姻 c吋mo, pero lo he conseguido.[n][f 1 3 65535][w][e]

[msg MND_Coffee_MakeEnd_Com]
[s][vp 8 2 0 0 65535 0]斡He podido hacer un caf姻[n]en condiciones![n][f 1 3 65535][w][e]

[msg MSG_227_1_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 8 10 2]Jam茨s pens姻 que llegar胤a el d胤a[n]en que quisiera tomar caf姻.[n]La vida est茨 llena de sorpresas.[n][f 1 3 65535][w][e]

[msg MSG_227_3_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 5 10 5]Pero es m茨s que una mera imitaci吋n.[n]El coraz吋n y alma que has puesto[n]en ello brillan con luz propia.[n][f 1 3 65535][w][e]

[msg MSG_227_6_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 10 10 8][f 4 2], puede que alg雨n[n]d胤a seas el Jefe de la segunda[n]generaci吋n del Leblanc.[n][f 1 3 65535][w][e]

[msg MND_Coffee_Lightly]
[s][vp 8 2 0 0 65535 0]斡No sabe a nada![n][f 1 3 65535][w][e]

[msg MND_Coffee_Bitter]
[s][vp 8 2 0 0 65535 0]斡Est茨 muy amargo![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 3 22]Por tu cara dir胤a que no ha salido[n]bien, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_024_1_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Sorprendente... El amargor te golpea[n]en la cara como si fuera un cami吋n.[n][f 1 3 65535][w][e]

[msg MSG_024_3_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡夷Esto qu姻 es?! Jam茨s hab胤a probado[n]un caf姻 como este.[n][f 1 3 65535][w][e]

[msg MSG_024_6_0 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Qu姻 fuerte est茨, madre de mi vida![n][f 1 3 65535][w][e]

[msg MSG_022_1_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7199 65535 0][f 5 13 8 10 2]夷Esto es caf姻 de verdad? Yo paso,[n]pero 斡me sorprende que la gente[n]se lo pueda beber![n][f 1 3 65535][w][e]

[msg MSG_022_3_0 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4132 65535 0][f 5 13 5 10 5]No, seguro que este es el sabor[n]del aut姻ntico caf姻... A雨n no tengo[n]el paladar tan refinado.[n][f 1 3 65535][w][e]

[msg MSG_022_6_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9073 65535 0][f 5 13 10 10 8]Esto es lo que a los adultos[n]les gusta tomar, 夷no? 夷Alg雨n d胤a[n]pensar姻 que est茨 delicioso?[n][f 1 3 65535][w][e]

[msg MND_125_0_0]
[s][vp 8 2 0 0 65535 0]Lo he hecho correctamente,[n]pero no me he podido recuperar...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Creo que necesito practicar m茨s.[n][f 1 3 65535][w][e]

[msg MND_125_1_0]
[s][vp 8 2 0 0 65535 0]Parece que he cometido un error.[n][f 1 3 65535][w][e]

[msg MND_125_2_0]
[s][vp 8 2 0 0 65535 0]He podido hacerlo correctamente.[n][f 1 3 65535][w][e]

[msg MND_COFFEE_EFFECT_SUCCES]
[s][vp 8 2 0 0 65535 0]夷...?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]No me lo explico, pero me siento[n]a tope...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Esto podr胤a serme 雨til[n]en el Metaverso.[n][f 1 3 65535][w][e]

[msg MSG_Coffee_1st_EffectInf [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]En este caf姻 hay mucha pasi吋n y[n]amor, 夷eh?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 10 65535 0 0]Quiz茨 sea capaz tambi姻n de curar[n]tus heridas si lo tomas[n]en el Metaverso.[n][f 1 3 65535][w][e]

[msg MSG_Coffee_HumanParamUp [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Je, je... Has aprendido algunos[n]trucos del Jefe.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Sojiro]]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 5024 65535 0]Parece que lo est茨s haciendo bien.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Anda, d姻jame probarlo.[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Sojiro]]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 5024 65535 0]Practicando de nuevo, 夷eh?[n]夷C吋mo va la cosa?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A ver, voy a probarlo.[n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este aroma y esta suave riqueza...[n][f 1 3 65535][w][e]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Has usado Blue Mountain, 夷verdad?[n][f 1 3 65535][w][e]

[msg SYS_050_1_0 [Blue Mountain de Jamaica]]
[s][vp 8 2 0 0 65535 0]Las Monta隠as Azules de Jamaica[n]tienen un clima 雨nico y un suelo[n]volc茨nico bueno para cultivar caf姻.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El caf姻 se controla y se[n]cosecha en peque隠as cantidades. As胤[n]se obtiene un caf姻 con mucho aroma.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Esta acidez...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Esto debe de ser caf姻 SHB[n]guatemalteco.[n][f 1 3 65535][w][e]

[msg SYS_051_1_0 [Caf姻 SHB guatemalteco]]
[s][vp 8 2 0 0 65535 0]El suelo volc茨nico de Guatemala es ideal[n]para plantar caf姻. Sus granos se clasifican[n]seg雨n la altitud a la que se cultivan.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El caf姻 estrictamente duro (SHB),[n]cultivado a m茨s de 1400 metros,[n]es consistente y de acidez c胤trica.[n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este sabor...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Debe de ser colombiano de Nari隠o.[n][f 1 3 65535][w][e]

[msg SYS_052_1_0 [Colombiano de Nari隠o]]
[s][vp 8 2 0 0 65535 0]La altitud, el clima lluvioso y[n]el terreno monta隠oso crean una[n]buena base para el caf姻 de calidad.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El caf姻 de Nari隠o es cremoso y[n]sabe a frutas y nueces.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este sabor...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es Crystal Mountain de Cuba,[n]夷verdad?[n][f 1 3 65535][w][e]

[msg SYS_053_1_0 [Crystal Mountain de Cuba]]
[s][vp 8 2 0 0 65535 0]Cuba es la isla m茨s grande[n]del Caribe. Su caf姻 es conocido[n]por su aroma y sabor.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El caf姻 Crystal Mountain se hace[n]con los granos m茨s grandes. Es[n]dulce, poco 茨cido y sabe a nueces.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Esta suavidad...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No cabe duda. Es caf姻[n]Kona hawaiano.[n][f 1 3 65535][w][e]

[msg SYS_054_1_0 [Caf姻 Kona hawaiano]]
[s][vp 8 2 0 0 65535 0]Una delicia hawaiana. Por su rareza[n]y el precio de los granos, la mezcla[n]solo necesita un 10 % de granos Kona.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Preparar un caf姻 Kona 100 % es muy[n]caro. Es famoso por tener sabor,[n]una ligera acidez y un aroma complejo.[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este sabor...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es caf姻 Moca Harrar[n]de Etiop胤a, 夷verdad?[n][f 1 3 65535][w][e]

[msg SYS_055_1_0 [Caf姻 Moca Harrar de Etiop胤a]]
[s][vp 8 2 0 0 65535 0]Moca es una ciudad de Yemen,[n]desde donde se exportan el caf姻[n]yemen胤 y el Moca Harrar de Etiop胤a.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El caf姻 de esta zona se llama moca.[n]Tiene un sabor especiado y[n]un fuerte aroma con notas de mora.[n][f 1 3 65535][w][e]

[msg MSG_056_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Mmm...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Esto es caf姻 moca Matari.[n][f 1 3 65535][w][e]

[msg SYS_056_1_0 [Caf姻 moca Matari]]
[s][vp 8 2 0 0 65535 0]Moca es una ciudad de Yemen,[n]desde donde se exportan el caf姻[n]yemen胤 y el Moca Harrar de Etiop胤a.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Moca Matari tiene sabor a especias[n]y chocolate con un cuerpo pesado[n]parecido al del vino.[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este agradable aroma...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es caf姻 mexicano Altura.[n][f 1 3 65535][w][e]

[msg SYS_057_1_0 [Caf姻 mexicano Altura]]
[s][vp 8 2 0 0 65535 0]Los espa隠oles trajeron el caf姻 a[n]M姻xico en el siglo XVIII. Ahora, es[n]uno de los mayores productores.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El nombre 或Altura位 se debe a la[n]altitud a la que se cultiva el caf姻,[n]que huele a tomillo y sabe a nueces.[n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]夷Eh? Este aroma...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es brasile隠o n.伊 2/18.[n][f 1 3 65535][w][e]

[msg SYS_058_1_0 [Brasile隠o n.伊 2/18]]
[s][vp 8 2 0 0 65535 0]Brasil es el mayor productor[n]de caf姻. Este es de gran calidad,[n]acidez justa y acabado amargo.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El caf姻 n.伊 2/18, conocido como[n]Santos, es un caf姻 muy famoso. El 2[n]es la calidad, y el 18, el tama隠o.[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Qu姻 sabor tan rico...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Esto es caf姻 colombiano[n]de Bucaramanga supremo.[n][f 1 3 65535][w][e]

[msg SYS_059_1_0 [Colombiano de Bucaramanga supremo]]
[s][vp 8 2 0 0 65535 0]La altitud, el clima lluvioso y[n]el terreno monta隠oso crean una[n]buena base para el caf姻 de calidad.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Supremo se refiere al tama隠o,[n]y Bucaramanga es donde se cultiva.[n]Tiene sabor dulce y acidez suave.[n][f 1 3 65535][w][e]

[msg MSG_060_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este regusto...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es caf姻 SHB de Costa Rica.[n][f 1 3 65535][w][e]

[msg SYS_060_1_0 [Caf姻 SHB de Costa Rica]]
[s][vp 8 2 0 0 65535 0]En Costa Rica abundan la flora[n]y la fauna, y el pa胤s ha exportado[n]caf姻 durante siglos.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El caf姻 estrictamente duro (SHB) es el[n]que se cultiva a m茨s de 1400 metros.[n]Es elegante y tiene un sabor dulce.[n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Ya veo...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Esto es caf姻 Kenia AA.[n][f 1 3 65535][w][e]

[msg SYS_061_1_0 [Caf姻 Kenia AA]]
[s][vp 8 2 0 0 65535 0]Las granjas de caf姻 de Kenia est茨n[n]muy controladas y producen granos[n]de caf姻 de gran calidad.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El caf姻 AA se cultiva a gran[n]altitud. AA se refiere a la calidad.[n]Tiene mucho aroma y acidez media.[n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Ya s姻 cu茨l es...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Esto es bourbon brasile隠o.[n][f 1 3 65535][w][e]

[msg SYS_062_1_0 [Bourbon brasile隠o]]
[s][vp 8 2 0 0 65535 0]Brasil es el mayor productor[n]de caf姻. Este es de gran calidad,[n]acidez justa y acabado amargo.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El Bourbon brasile隠o se produce[n]en peque隠as cantidades y es raro.[n]Es dulce y tiene un acabado limpio.[n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este sabor tan fresco...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es caf姻 colombiano 100 % Typica.[n][f 1 3 65535][w][e]

[msg SYS_063_1_0 [Colombiano 100 % Typica]]
[s][vp 8 2 0 0 65535 0]La altitud, el clima lluvioso y[n]el terreno monta隠oso crean una[n]buena base para el caf姻 de calidad.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Este caf姻 se hace con granos[n]Typica y es dif胤cil de cosechar.[n]Es c胤trico y muy arom茨tico.[n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Esta suave acidez...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es caf姻 SHG de Honduras.[n][f 1 3 65535][w][e]

[msg SYS_064_1_0 [Caf姻 SHG de Honduras]]
[s][vp 8 2 0 0 65535 0]El paisaje de Honduras es monta隠oso[n]o de terreno alto. La calidad[n]del caf姻 depende de la altitud.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]El caf姻 SHG se cultiva a gran altitud.[n]Tiene un aroma afrutado, suave[n]acidez y un sabor s吋lido.[n][f 1 3 65535][w][e]

[msg MSG_065_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este aroma c胤trico...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es Guatemala Antigua.[n][f 1 3 65535][w][e]

[msg SYS_065_1_0 [Guatemala Antigua]]
[s][vp 8 2 0 0 65535 0]El suelo volc茨nico de Guatemala es ideal[n]para plantar caf姻. Sus granos se clasifican[n]seg雨n la altitud a la que se cultivan.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Los minerales y nutrientes del suelo[n]dotan al caf姻 Antigua de[n]una acidez suave y un regusto fresco.[n][f 1 3 65535][w][e]

[msg MSG_066_0_0 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este aroma afrutado...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es El Salvador Pacamara.[n][f 1 3 65535][w][e]

[msg SYS_066_1_0 [El Salvador Pacamara]]
[s][vp 8 2 0 0 65535 0]El 50 % de las exportaciones de El[n]Salvador son de caf姻. El Pacamara[n]es un h胤brido que viene de all胤.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Surge de una planta h胤brida que[n]produce muchos granos grandes.[n]Es denso y sabe a chocolate.[n][f 1 3 65535][w][e]

[msg MSG_067_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este aroma floral...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Debe de ser Panama Esmeralda[n]Geisha.[n][f 1 3 65535][w][e]

[msg SYS_067_1_0 [Panama Esmeralda Geisha]]
[s][vp 8 2 0 0 65535 0]Esta variedad tan codiciada tiene[n]el r姻cord de pujas m茨s altas[n]en las subastas de caf姻 de Panam茨.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Se cultiva muy poco y por eso[n]es tan rara. Tiene aroma a flores,[n]una fresca acidez y acabado dulce.[n][f 1 3 65535][w][e]

[msg MSG_068_0_0 [Sojiro]]
[s][bup 0 103 505 65535 0][f 4 10 65535 0 0][vp 8 2 0 5038 65535 0]Este aroma...[n][f 1 3 65535][w][e]
[s][bup 0 103 504 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es Kopi Luwak de Indonesia.[n][f 1 3 65535][w][e]
[s][bup 0 103 502 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oye, este tueste es caro.[n]No lo desperdicies.[n][f 1 3 65535][w][e]

[msg SYS_068_1_0 [Kopi Luwak de Indonesia]]
[s][vp 8 2 0 0 65535 0]Este raro caf姻 se hace con granos[n]que han sido digeridos[n]por la civeta de palmera asi茨tica.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Aunque es caro, el Kopi Luwak tiene[n]gran aroma y sabor por las[n]encimas digestivas de la civeta.[n][f 1 3 65535][w][e]

[msg MSG_093_0_0 [Sojiro]]
[s][bup 0 103 503 65535 0][f 4 10 65535 0 0][vp 8 2 0 5028 65535 0]El perfil de sabor es suave.[n]Deber胤as practicar m茨s para extraer[n]todo el potencial del tueste.[n][f 1 3 65535][w][e]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 6 3 1003]Aunque ya veo que est茨s preparando[n]el caf姻 tal y como te ense隠姻.[n]Agradezco tu esfuerzo.[n][f 1 3 65535][w][e]

[msg MSG_Sojiro_Check_OK_Midd [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5028 65535 0][f 5 13 6 8 1003]Ah...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No est茨 mal. Se merece un cumplido.[n][f 1 3 65535][w][e]

[msg MSG_094_0_0 [Sojiro]]
[s][bup 0 103 504 65535 0][f 4 10 65535 0 0][vp 8 2 0 5022 65535 0][f 5 13 6 8 1003]Delicioso...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Estoy impresionado. Eso s胤, nunca[n]me alcanzar茨s.[n][f 1 3 65535][w][e]

[msg MSG_RANK_2_1 [Sojiro]]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 5024 65535 0]Pareces un aut姻ntico barista[n]pertrechado as胤 en la barra.[n][f 1 3 65535][w][e]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece que est茨s siguiendo todas[n]las reglas y directrices que te di.[n][f 1 3 65535][w][e]
[s][bup 0 103 503 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Me parece incre胤ble que el chico[n]que tengo delante sea[n]un alborotador con antecedentes.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bueno, no hace falta hablar largo[n]y tendido sobre el tema.[n]Sigue practicando.[n][f 1 3 65535][w][e]

[msg MSG_RANK_2_2 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5080 65535 0]A雨n te queda mucho por aprender,[n]sobre caf姻 y sobre la vida.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 10 65535 0 0]Ten paciencia.[n][f 1 3 65535][w][e]

[msg MSG_RANK_3_1 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5028 65535 0]En una cafeter胤a como esta,[n]uno recibe a clientes de lo m茨s[n]variopintos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Aunque alguien parezca[n]problem茨tico, le servir姻 el mismo[n]caf姻 que a todos los dem茨s.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ese es mi trabajo. Mi profesi吋n[n]me llena de orgullo.[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]T雨 tambi姻n eres como un cliente.[n]Uno que requiere mucho esfuerzo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tienes potencial, as胤 que[n]sigue practicando.[n][f 1 3 65535][w][e]

[msg MSG_RANK_3_2 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5080 65535 0]Seguir姻 ense隠茨ndote cosas,[n]as胤 que no te rindas.[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Un d胤a, el sabor de tu caf姻 ser茨[n]雨nico. Tienes potencial, as胤 que[n]sigue practicando.[n][f 1 3 65535][w][e]

[msg MSG_RANK_4_1 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5028 65535 0]Quiz茨 sea el destino... Parece que[n]tu pasado te sigue all茨[n]donde vayas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Supongo que todo est茨 escrito,[n]tanto lo bueno como lo malo. Y yo[n]no soy de creer en esas mierdas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Ser茨 tu llegada cosa del destino[n]tambi姻n?[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ja, ja. Esto no es propio de m胤,[n]pero espero que de aqu胤 salga[n]algo bueno.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ya lo s姻, ya lo s姻. Los viejos[n]que divagan no est茨n bien vistos.[n]Bueno, gracias por el caf姻.[n][f 1 3 65535][w][e]

[msg MSG_RANK_4_2 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5080 65535 0]Quiz茨 sea cosa del destino que est姻[n]tom茨ndome tu caf姻 aqu胤 y ahora...[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ser胤a estupendo, 夷verdad? Ay, me[n]recuerdas mucho a m胤 mismo[n]cuando estaba form茨ndome.[n][f 1 3 65535][w][e]

[msg MSG_RANK_5_1 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5028 65535 0]Lamento haber mantenido[n]lo de Futaba en secreto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pens姻 que no ver胤a el d胤a en que[n]viniera sola a la cafeter胤a[n]a probar de nuevo mi curry.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No entiendo lo que ha sucedido,[n]pero parece que le agradas.[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bueno, sea por lo que sea,[n]me alegro de que est姻 mejor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Imagino que tambi姻n te he[n]preocupado a ti. Espero que hagas[n]buenas migas con Futaba.[n][f 1 3 65535][w][e]

[msg MSG_RANK_5_2 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5080 65535 0]夷C吋mo van las cosas con Futaba?[n][f 1 3 65535][w][e]
[s][bup 0 103 503 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pero esc雨chame bien... Si la haces[n]llorar, te vas a enterar.[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pero conf胤o en ti.[n]Cuida de Futaba, por favor.  [n][f 1 3 65535][w][e]

[msg MSG_RANK_6_1 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5028 65535 0]Hay cosas en el mundo[n]que no podemos controlar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No sirve de nada[n]intentar desafiarlas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Aunque puede que no[n]lo entiendas, porque todav胤a[n]eres muy joven...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vaya, te he echado un buen serm吋n.[n]Olvida lo que he dicho.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Y no te preocupes por lo del otro[n]d胤a. No voy a dejar que[n]os pase nada.[n][f 1 3 65535][w][e]

[msg MSG_RANK_6_2 [Sojiro]]
[s][bup 0 103 500 65535 0][vp 8 2 0 5080 65535 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ah, lo siento.[n]Solo estaba reflexionando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Y no te preocupes por lo del otro[n]d胤a. No voy a dejar que[n]os pase nada.[n][f 1 3 65535][w][e]

[msg MSG_RANK_7_1 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5028 65535 0]Hay muchas cosas en la vida[n]que no salen como t雨 quieres.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No se puede hacer nada.[n]Lo importante es c吋mo reacciones[n]en esas situaciones.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Huir茨s y vivir茨s arrepentido[n]el resto de tu vida?[n]夷O te enfrentar茨s al problema?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Todav胤a eres joven. Puedes[n]empezar de cero cuanto quieras.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Aunque yo no soy qui姻n para hablar.[n]Bueno, la cabeza bien alta.[n][f 1 3 65535][w][e]

[msg MSG_RANK_7_2 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5080 65535 0]S姻 que es repentino, pero[n]deja que te diga una cosa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Si sientes que es el momento[n]adecuado, dile c吋mo te sientes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es algo que aprend胤 por las malas.[n]No quiero que sufras como sufr胤 yo.[n][f 1 3 65535][w][e]

[msg MSG_RANK_8_1 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5018 65535 0]Siento lo del otro d胤a. Y gracias[n]por dar la cara por Futaba.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Estar茨s preocupado, pero quiero[n]que me dejes solucionarlo a m胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ya me he decidido.[n]Har姻 lo que sea por vosotros.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Quiero que me dejes hacer[n]mi trabajo como tutor.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Por lo menos me alegro[n]de haberte ense隠ado a hacer[n]buen caf姻...[n][f 1 3 65535][w][e]

[msg MSG_RANK_8_2 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5080 65535 0]He encontrado lo que es[n]importante para m胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vosotros sois mi prioridad.[n]No te preocupes,[n]os proteger姻 a Futaba y a ti.[n][f 1 3 65535][w][e]

[msg MSG_RANK_9_1 [Sojiro]]
[s][bup 0 103 500 65526 0][vp 8 2 0 5028 65535 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Y yo que pensaba que solo[n]eras un macarra.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Suena rid胤culo que lo diga[n]un adulto, pero[n]me est茨is ense隠ando mucho.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A cambio, te ense隠ar姻[n]todo lo que s姻, como[n]muestra de gratitud.[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]S姻 que puedes hacerlo[n]si te esfuerzas.[n][f 1 3 65535][w][e]
[s][bup 0 103 502 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Y para que conste...[n][f 1 3 65535][w][e]
[s][bup 0 103 503 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ten胤a miedo.[n]Cu姻ntaselo a Futaba tambi姻n.[n][f 1 3 65535][w][e]

[msg MSG_RANK_9_2 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5080 65535 0]Como agradecimiento,[n]te ense隠ar姻 todo lo que s姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]S姻 que lo conseguir茨s.[n][f 1 3 65535][w][e]

[msg MSG_RANK_10_1 [Sojiro]]
[s][bup 0 103 500 65535 0][f 4 10 65535 0 0][vp 8 2 0 5028 65535 0]Si he podido cambiar, ha sido[n]gracias a ti. Eres de lo que[n]no hay.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pero, en lo que respecta al caf姻,[n]no llevar茨s la voz cantante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Eso s胤, tengo que reconocer que no[n]tardar茨s en superar[n]mis habilidades.[n][f 1 3 65535][w][e]
[s][bup 0 103 501 65535 0][vp 8 2 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es un aut姻ntico placer tener un[n]aprendiz tan competente. Perm胤teme[n]que siga mostr茨ndote el camino.[n][f 1 3 65535][w][e]

[msg MSG_RANK_10_2 [Sojiro]]
[s][bup 0 103 501 65535 0][f 4 10 65535 0 0][vp 8 2 0 5080 65535 0]Me gusta tu caf姻.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es un aut姻ntico placer tener un[n]aprendiz tan competente. Perm胤teme[n]que siga mostr茨ndote el camino.[n][f 1 3 65535][w][e]

[msg MSG_250_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tienes la oportunidad de aprender,[n]as胤 que t吋mate tu tiempo y sigue[n]mejorando.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 1166 65535 0]La gente te tratar茨 con respeto[n]cuando sepa que sirves un caf姻[n]de gran calidad.[n][f 1 3 65535][w][e]

[msg MND_250_1_0]
[s][vp 8 2 0 0 65535 0]Creo que deber胤a preparar caf姻[n]m茨s a menudo para m胤[n]y los Ladrones Fantasma.[n][f 1 3 65535][w][e]

[msg MSG_135_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1172 65535 0]Deber胤amos descansar un poco.[n]Ma隠ana nos espera un gran d胤a.[n][f 1 3 65535][w][e]

[msg MND_135_1_0]
[s][vp 8 2 0 94 65535 0]Creo que ya est茨 bien por hoy.[n][f 1 3 65535][w][e]

[msg MSG_DEBUG [Debug]]
[s]Debug Mode[n][f 1 3 65535][w][e]

[sel SEL_DEBUG top]
[s]Ryuji[e]
[s]Yusuke[e]
[s]Futaba[e]
[s]Morgana[e]
[s]Solo[e]

[msg MSG_DEBUG_2 [Debug]]
[s]sojiro debug[n][f 1 3 65535][w][e]

[sel SEL_DEBUG_2 top]
[s]Viene[e]
[s]No viene[e]

