[msg MSG_GAMESTART [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Juguemos a Legend of Gambla Goemon.[n][f 1 3 65535][w][e]

[msg MSG_GAMESTART_NULL]
[s][vp 8 2 0 91 65535 0]Juguemos a Legend of Gambla Goemon.[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_FI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1172 65535 0]Por cierto, 夷no has le胤do el libro[n]ese de t姻cnicas secretas?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Si te has quedado atascado,[n]Goemon puede solventar[n]el problema con su truco especial.[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_NU]
[s][vp 8 2 0 0 65535 0]Ahora que caigo, me he le胤do[n]un libro sobre t姻cnicas secretas[n]de videojuegos.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Pon胤a que Goemon[n]puede superar cualquier obst茨culo[n]con su truco especial.[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_FI_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Entonces, 夷quieres usar el truco?[n]El juego ser茨 m茨s f茨cil.[n][f 1 3 65535][w][e]

[msg MND_201_6_0]
[s][vp 8 2 0 0 65535 0]夷Deber胤a usar el truco?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Usar la t姻cnica[e]
[s]Jugar de forma normal[e]

[msg MSG_READ_BOOK_URAWAZA_YE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Se nota que has aprendido.[n]斡Vale, vamos al l胤o![n][f 1 3 65535][w][e]

[msg MND_203_6_0]
[s][vp 8 2 0 0 65535 0]Bueno, ahora el juego[n]deber胤a ser menos dif胤cil.[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_NO [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Vaya, est茨s que te sales![n]斡Venga, a por ello![n][f 1 3 65535][w][e]

[msg MND_202_6_0]
[s][vp 8 2 0 0 65535 0]Deber胤a recurrir a mis habilidades[n]para conseguirlo.[n][f 1 3 65535][w][e]

[msg MSG_Ura01 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1178 65535 0]Jol胤n, has fallado.[n][f 1 3 65535][w][e]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Espera, 夷qu姻 es eso?[n]斡La mano de Goemon est茨 brillando![n][f 1 3 65535][w][e]

[msg MSG_Ura_oni [Demonio]]
[s][vp 8 2 0 59555 65535 0]斡Ay! 斡C吋mo brilla![n][f 1 3 65535][w][e]

[msg MSG_Ura_enma [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]斡Aj! 斡Cu茨nta luz![n][f 1 3 65535][w][e]

[msg MSG_Ura02 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1040 65535 0]斡Mira, los n雨meros de los dados[n]han cambiado![n][f 1 3 65535][w][e]

[msg MSG_Ura_oni02 [Demonio]]
[s][vp 8 2 0 59556 65535 0]夷Mm? Pensaba que era pares,[n]pero he metido la pata.[n]Ha salido nones, t雨 ganas.[n][f 1 3 65535][w][e]

[msg MSG_Ura_oni03 [Demonio]]
[s][vp 8 2 0 59556 65535 0]夷Mm? Pensaba que era nones,[n]pero he metido la pata.[n]Ha salido pares, t雨 ganas.[n][f 1 3 65535][w][e]

[msg MSG_Ura_enma02 [Rey Yama]]
[s][vp 8 2 0 59556 65535 0]Aj, pensaba que hab胤a salido[n]pares, pero me equivocaba.[n]Ha salido nones, t雨 ganas.[n][f 1 3 65535][w][e]

[msg MSG_Ura_enma03 [Rey Yama]]
[s][vp 8 2 0 59556 65535 0]Aj, pensaba que hab胤a salido[n]nones, pero me equivocaba.[n]Ha salido pares, t雨 ganas.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1163 65535 0]El juego va de un ladr吋n[n]conocido que cay吋[n]en las profundidades del infierno.[n][f 1 3 65535][w][e]

[msg MND_205_6_0]
[s][vp 8 2 0 86 65535 0]El juego va de un ladr吋n[n]famoso que cay吋[n]en las profundidades del infierno.[n][f 1 3 65535][w][e]

[msg MSG_GAMBLE_TUTORIAL_2_MO [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]El demonio ha vuelto.[n]Preg雨ntale por las reglas.[n][f 1 3 65535][w][e]

[msg MSG_GAMBLE_TUTORIAL_2_02]
[s][vp 8 2 0 0 65535 0]El demonio est茨 ah胤 delante.[n]夷Le pregunto por las reglas?[n][f 1 3 65535][w][e]

[sel GAMBLE_TUTORIAL_2_YES_NO top]
[s]Preguntar por las reglas[e]
[s]No preguntar[e]

[msg MSG_110_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1171 65535 0][f 4 22 65535 3 4]Cuidado. Ha aparecido algo...[n]夷Es un demonio?[n][f 1 3 65535][w][e]

[msg MND_225_6_0]
[s][vp 8 2 0 62 65535 0]Ha aparecido ante m胤[n]una criatura gigante.[n]Tiene aspecto de demonio.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_TUTORI [Demonio]]
[s][vp 8 2 0 59556 65535 0]Conque el ladr吋n sin escr雨pulos[n]que asol吋 el mundo ha entrado[n]tan campante en el infierno.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]Te ense隠ar胤a con gusto[n]los horrores del infierno...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]Si quisiera, claro, pero ser胤a[n]aburrido derrotar al famoso Goemon[n]igual que a cualquier otro humano.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]En su lugar, jugaremos a los dados.[n]El juego se llama... 斡pares o nones![n][f 1 3 65535][w][e]

[msg MSG_GAMBLE_TUTORIAL_MORU [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mmm, parece que toca vencerlo[n]en una partida de dados.[n][f 1 3 65535][w][e]

[msg MSG_GAMBLE_TUTORIAL_02]
[s][vp 8 2 0 0 65535 0]Creo que debo derrotar[n]al demonio en una partida de dados.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_TUTORI_2 [Demonio]]
[s][vp 8 2 0 59555 65535 0]Primero, tendr茨s que elegir[n]si saldr茨n pares o nones.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]Los pares son n雨meros como dos,[n]seis y ocho, mientras que los nones[n]son tres, siete y once.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]Una vez que elijas, lanzar姻[n]los dados. Si aciertas, ganas,[n]y, si no, pierdes.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59555 65535 0]Y eso es todo.[n]夷Entiendes las reglas?[n][f 1 3 65535][w][e]

[sel GAMBLE_TUTORIAL_YES_NO top]
[s]Sin duda.[e]
[s]Todav胤a no.[e]

[msg MSG_JIGOKU_GAMBLE_START [Demonio]]
[s][vp 8 2 0 59555 65535 0]夷Y bien? 夷Escoges pares o nones?[n]斡Elige![n][f 1 3 65535][w][e]

[sel MSG_JIGOKU_GAMBLE_START_ top]
[s]Pares.[e]
[s]Nones.[e]

[msg MSG_JIGOKU_GAMBLE_TYOU [Demonio]]
[s][vp 8 2 0 59555 65535 0]Mmm, una apuesta interesante.[n]Si sale una cifra par, ganas.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_HAN [Demonio]]
[s][vp 8 2 0 59555 65535 0]Mmm, una apuesta interesante.[n]Si sale nones, ganas.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_GO [Demonio]]
[s][vp 8 2 0 59554 65535 0]斡Muy bien, veamos los resultados![n][f 1 3 65535][w][e]

[msg MSG_Stage01_Clear01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1181 65535 0]斡Mola! 斡Has ganado la apuesta![n][f 1 3 65535][w][e]

[msg MND_Stage01_Clear01]
[s][vp 8 2 0 0 65535 0]斡He ganado la apuesta![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_CLEAR02 [Demonio]]
[s][vp 8 2 0 59556 65535 0]Jo, qu姻 suerte.[n]斡Trat茨ndose del famoso Goemon,[n]tendr胤a que haberlo visto venir![n][f 1 3 65535][w][e]
[s][vp 8 2 0 59555 65535 0]Has ganado.[n]Puedes seguir adelante.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_CLEAR03_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oye, el demonio se ha dado el piro[n]y la puerta se ha abierto.[n]斡Parece que puedes avanzar![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_CLEAR03]
[s][vp 8 2 0 0 65535 0]El demonio ha desaparecido[n]y la puerta se ha abierto.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_RESULT01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Te has apa隠ado[n]para superar la fase.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Pero tu actitud ha sido encomiable.[n]斡La perseverancia es importante![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_RESULT01_2]
[s][vp 8 2 0 0 65535 0]Me las he apa隠ado[n]para superar la fase.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Siento que he aprendido[n]a seguir adelante sin darme[n]por vencido.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_RESULT_U [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1166 65535 0]夷El libro de t姻cnicas secretas te ayud吋?[n]Lo que m茨s admiro de ti es que[n]siempre busques c吋mo ser eficiente.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Pero tu actitud ha sido encomiable.[n]斡La perseverancia es importante![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_RESULT_U_2]
[s][vp 8 2 0 78 65535 0]Vaya t姻cnica...[n]Tampoco te has roto la cabeza.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Siento que he aprendido[n]a seguir adelante sin darme[n]por vencido.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_OVER [Demonio]]
[s][vp 8 2 0 59555 65535 0]Mua, ja, ja, qu姻 mala suerte.[n]斡Has perdido![n][f 1 3 65535][w][e]
[s][vp 8 2 0 59555 65535 0]斡Pasar茨s el resto de tus d胤as[n]en el abismo infernal![n][f 1 3 65535][w][e]

[msg MSG_STEP2_START_02_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1171 65535 0]夷Ese edificio es un templo?[n]Hay un demonio gigante[n]vestido de rojo.[n][f 1 3 65535][w][e]

[msg MND_STEP2_START_02]
[s][vp 8 2 0 62 65535 0]夷Eso de ah胤 es un santuario?[n]Hay un demonio gigante de rojo.[n][f 1 3 65535][w][e]

[msg MSG_GAMBLE_TUTORIAL_STEP [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mm, ah胤 sigue Rey Yama.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Habr茨 que apostar de nuevo.[n]夷Quieres preguntarle las reglas[n]otra vez?[n][f 1 3 65535][w][e]

[msg MSG_GAMBLE_TUTORIAL_STEP_2]
[s][vp 8 2 0 0 65535 0]Rey Yama me est茨 esperando.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Estoy a punto de afrontar[n]otro desaf胤o de apuestas. Deber胤a[n]preguntar las reglas de nuevo.[n][f 1 3 65535][w][e]

[msg MSG_STEP2_START [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]斡Conque has venido! Maravilloso.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]Me llamo Rey Yama[n]y soy el responsable de todo[n]lo que ocurre en estas tierras.[n][f 1 3 65535][w][e]

[msg MSG_STEP2_START_03_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Querr茨 que echemos[n]otra partida a los dados?[n][f 1 3 65535][w][e]

[msg MND_STEP2_START_03]
[s][vp 8 2 0 0 65535 0]Tendremos que echar[n]otra partida a los dados, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_STEP2_START_02 [Rey Yama]]
[s][vp 8 2 0 59556 65535 0]Vamos a jugar a un juego.[n]Seguro que ya conoces las reglas,[n]pero 夷quieres que te las repita?[n][f 1 3 65535][w][e]

[sel GAMBLE_TUTORIAL_STEP2_YE top]
[s]No es necesario.[e]
[s]Ser胤a estupendo.[e]

[msg MSG_STEP2_START_03 [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]Primero, tendr茨s que elegir[n]entre pares o nones.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]Los pares son n雨meros como dos,[n]seis y ocho, mientras que los nones[n]son tres, siete y once.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]Una vez que elijas, lanzar姻[n]los dados. Si aciertas, ganas,[n]y, si no, pierdes.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59555 65535 0]Y eso es todo.[n]夷Entiendes las reglas?[n][f 1 3 65535][w][e]

[msg MSG_STEP2_START_04 [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]Sin embargo, 斡mi juego es mucho[n]m茨s estricto que el anterior![n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]斡Tendr茨s que ganar dos partidas[n]de tres para triunfar![n]Si no, pierdes.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_START__2 [Rey Yama]]
[s][vp 8 2 0 59556 65535 0]Esta es la primera ronda.[n]夷Qu姻 escoges, pares o nones?[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_START__3 [Rey Yama]]
[s][vp 8 2 0 59556 65535 0]Ahora viene la segunda ronda.[n]夷Qu姻 escoges, pares o nones?[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_START__4 [Rey Yama]]
[s][vp 8 2 0 59556 65535 0]A por la tercera y 雨ltima ronda.[n]夷Qu姻 escoges, pares o nones?[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_TYOU_E [Rey Yama]]
[s][vp 8 2 0 59556 65535 0]夷Escoges par?[n]Que los dados decidan tu destino.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_HAN_EN [Rey Yama]]
[s][vp 8 2 0 59556 65535 0]Jo, jo. As胤 que eliges nones.[n]Que los dados decidan tu destino.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_START__5 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]Muy bien, 斡empecemos![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_CLEAR02_ [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]斡夷Qu姻?! 斡夷Has ganado?![n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]Parece que el destino te favorece.[n]Todav胤a no ha llegado tu fin.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]El mundo de los vivos no es m茨s[n]que sufrimiento. 斡Espero que tengas[n]la fuerza necesaria para sobrevivir![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_OVER_ROU [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]Vaya, vaya. La batalla ha llegado[n]a su fin en la ronda final.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]Para tu desgracia,[n]no has conseguido las victorias[n]suficientes. 斡Est茨s acabado![n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]斡Disfruta del descenso[n]a las profundidades del infierno![n]斡Jaaa, ja, ja, ja![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_OVER_ROU_2 [Rey Yama]]
[s][vp 8 2 0 59556 65535 0]夷Qu姻 tenemos aqu胤?[n]Solo estamos a la mitad, pero[n]斡la situaci吋n no pinta nada bien![n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]Para tu desgracia,[n]no has conseguido las victorias[n]suficientes. 斡Est茨s acabado![n][f 1 3 65535][w][e]
[s][vp 8 2 0 59556 65535 0]斡Disfruta del descenso[n]a las profundidades del infierno![n]斡Jaaa, ja, ja, ja![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_S2_CLEAR [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1181 65535 0]斡Bien hecho! 斡Te has pasado[n]Legend of Gambla Goemon![n][f 1 3 65535][w][e]

[msg MND_JIGOKU_GAME_S2_CLEAR]
[s][vp 8 2 0 63 65535 0]斡Al fin he acabado[n]Legend of Gambla Goemon![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_THINK_ [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1171 65535 0]斡Bien, has acertado![n][f 1 3 65535][w][e]

[msg MND_JIGOKU_GAMBLE_THINK_]
[s][vp 8 2 0 54 65535 0]斡Lo he adivinado![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_THINK__2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1067 65535 0]Justo como esperaba de Goemon.[n]斡El oponente no se ha dado cuenta![n][f 1 3 65535][w][e]

[msg MND_JIGOKU_GAMBLE_THINK__2]
[s][vp 8 2 0 54 65535 0]斡El enemigo no se ha dado cuenta[n]de nuestro truco![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_LOSE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1182 65535 0]Has fallado.[n][f 1 3 65535][w][e]

[msg MND_JIGOKU_GAMBLE_LOSE]
[s][vp 8 2 0 20 65535 0]Me he equivocado.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_OVER_COM [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Qu姻 crees que le va a pasar[n]al protagonista?[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_OVER_COM_2]
[s][vp 8 2 0 0 65535 0]Me pregunto qu姻 le aguarda[n]al protagonista a partir de ahora.[n][f 1 3 65535][w][e]

[msg MSG_FAILED_UP [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Puede que hayas perdido...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Pero tu actitud ha sido encomiable.[n]斡La perseverancia es importante![n][f 1 3 65535][w][e]

[msg MND_FAILED_UP]
[s][vp 8 2 0 0 65535 0]He perdido.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Pero siento que he aprendido[n]a seguir adelante sin darme[n]por vencido, aunque sea un poco.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_END_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1035 65535 0]L茨stima, pero el juego se reduce[n]a la suerte. No te queda otra que[n]aceptar la derrota con dignidad.[n][f 1 3 65535][w][e]

[msg MSG_HINTO_BOOK_NO [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ojal茨 hubiera una forma de hacer[n]que este juego fuera m茨s f茨cil...[n][f 1 3 65535][w][e]

[msg MND_HINTO_BOOK_NO]
[s][vp 8 2 0 0 65535 0]Ojal茨 hubiera una forma[n]de bajar la dificultad del juego.[n][f 1 3 65535][w][e]

[msg MSG_HINTO_BOOK00 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷No tienes un libro[n]que habla de t姻cnicas secretas?[n]Igual estar胤a bien leerlo.[n][f 1 3 65535][w][e]

[msg MND_HINTO_BOOK04]
[s][vp 8 2 0 0 65535 0]Ahora que me acuerdo, yo tengo[n]un libro de t姻cnicas secretas.[n]Igual deber胤a le姻rmelo.[n][f 1 3 65535][w][e]

[msg MSG_BOOK_DONE_M [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Te parece demasiado dif胤cil?[n]斡Habr茨 que volver a intentarlo![n][f 1 3 65535][w][e]

[msg MND_BOOK_DONE_N]
[s][vp 8 2 0 0 65535 0]Es bastante dif胤cill...[n]Volver姻 a intentarlo m茨s tarde.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_END_MORU_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1166 65535 0]Bueno, se est茨 haciendo tarde.[n]Acost姻monos pronto, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAME_END_MORU_3 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1166 65535 0]Lo que ha costado...[n]Igual deber胤amos dejar de jugar[n]de momento, 夷no crees?[n][f 1 3 65535][w][e]

[msg MND_JIGOKU_GAME_END]
[s][vp 8 2 0 57 65535 0]Se est茨 haciendo tarde.[n]Deber胤a irme a la cama.[n][f 1 3 65535][w][e]

[msg MND_JIGOKU_GAME_END_DAY]
[s][vp 8 2 0 57 65535 0]Mmm. Igual deber胤a dejar[n]un rato los videojuegos...[n][f 1 3 65535][w][e]

[msg MSG_PASS_MORU [Morgana]]
[s][bup 0 3 0 65535 0][vp 8 2 0 0 65535 0]Venga, 斡a disfrutar del final![n][f 1 3 65535][w][e]

[msg MND_PASS]
[s][vp 8 2 0 0 65535 0]Es hora de disfrutar del final...[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Seg雨n este manual, si env胤as[n]la contrase隠a que sale despu姻s[n]del final, obtendr茨s un premio.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Esta promoci吋n tiene a隠os.[n]Lo m茨s seguro es que[n]est姻 caducad胤sima.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Aunque no pasa nada por[n]apuntarla. A lo mejor cuela[n]en alguna tienda de juegos.[n][f 1 3 65535][w][e]

[msg MND_053_1_0]
[s][vp 8 2 0 0 65535 0]Supuestamente, si env胤o[n]la contrase隠a que sale despu姻s[n]del final, obtendr姻 un premio.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Pero la promoci吋n es viej胤sima.[n]Lo m茨s seguro[n]es que haya caducado.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Aunque deber胤a anotarla,[n]por si acaso.[n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_1_1 [Demonio]]
[s][vp 8 2 0 59555 65535 0]Ojos de serpiente. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_1_2 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un uno y un dos. 斡Nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_1_3 [Demonio]]
[s][vp 8 2 0 59555 65535 0]Un uno y un tres. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_1_4 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un uno y un cuatro. 斡Nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_1_5 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un uno y un cinco. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_1_6 [Demonio]]
[s][vp 8 2 0 59555 65535 0]Un uno y un seis. 斡Nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_2_2 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Dos doses. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_3_2 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un dos y un tres. 斡Nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_4_2 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un dos y un cuatro. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_5_2 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un dos y un cinco. 斡Nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_6_2 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un dos y un seis. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_3_3 [Demonio]]
[s][vp 8 2 0 59555 65535 0]Dos treses. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_4_3 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un tres y un cuatro. 斡Nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_5_3 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un tres y un cinco. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_6_3 [Demonio]]
[s][vp 8 2 0 59555 65535 0]Un tres y un seis. 斡Nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_4_4 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Dos cuatros. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_5_4 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un cuatro y un cinco. 斡Nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_6_4 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un cuatro y un seis. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_5_5 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Dos cincos. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_5_6 [Demonio]]
[s][vp 8 2 0 59554 65535 0]Un cinco y un seis. 斡Nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S1_6_6 [Demonio]]
[s][vp 8 2 0 59555 65535 0]Dos seises. 斡Pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_1_1 [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]夷Ojos de serpiente? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_1_2 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un uno y un dos? 斡Es nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_1_3 [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]夷Un uno y un tres? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_1_4 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un uno y un cuatro? 斡Es nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_1_5 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un uno y un cinco? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_1_6 [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]夷Un uno y un seis? 斡Es nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_2_2 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Dos doses? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_3_2 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un dos y un tres? 斡Es nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_4_2 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un dos y un cuatro? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_5_2 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un dos y un cinco? 斡Es nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_6_2 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un dos y un seis? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_3_3 [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]夷Dos treses? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_4_3 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un tres y un cuatro? 斡Es nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_5_3 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un tres y un cinco? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_6_3 [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]夷Un tres y un seis? 斡Es nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_4_4 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Dos cuatros? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_5_4 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un cuatro y un cinco? 斡Es nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_6_4 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un cuatro y un seis? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_5_5 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Dos cincos? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_5_6 [Rey Yama]]
[s][vp 8 2 0 59554 65535 0]夷Un cinco y un seis? 斡Es nones![n][f 1 3 65535][w][e]

[msg MSG_JIGOKU_GAMBLE_S2_6_6 [Rey Yama]]
[s][vp 8 2 0 59555 65535 0]夷Dos seises? 斡Es pares![n][f 1 3 65535][w][e]

[msg MSG_DEBUG [for debug]]
[s][vp 8 2 0 0 65535 0]Debug mode[n][f 1 3 65535][w][e]

[sel SEL_DEBUG top]
[s]with morgana[e]
[s]no morgana[e]

[msg MSG_DEBUG_2 [for debug]]
[s][vp 8 2 0 0 65535 0]Debug mode[n][f 1 3 65535][w][e]

[sel SEL_DEBUG_2 top]
[s]Stage 1[e]
[s]Stage 2[e]

[msg MSG_DEBUG_3 [for debug]]
[s][vp 8 2 0 0 65535 0]Debug mode[n][f 1 3 65535][w][e]

[sel SEL_DEBUG_3 top]
[s]1st time[e]
[s]2nd time[e]

