[msg MSG_GAMESTART [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]Juguemos a Star Forneus.[n][f 1 3 65535][w][e]

[msg MSG_GAMESTART_NULL]
[s][vp 8 2 0 91 65535 0]Es hora de jugar a Star Forneus.[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_FI [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1172 65535 0]Por cierto,[n]夷no te hab胤as le胤do el libro[n]ese de t姻cnicas secretas?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Se ve que hay una forma de disparar[n]l茨seres dobles desde el barco[n]para facilitar un poco las cosas.[n][f 1 3 65535][w][e]

[msg MND_200_6_0]
[s][vp 8 2 0 0 65535 0]Ahora que caigo, me he le胤do[n]un libro sobre t姻cnicas secretas[n]de videojuegos.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Pon胤a que hay una forma de disparar[n]l茨seres dobles desde el barco[n]para que el juego sea m茨s f茨cil.[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_FI_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1172 65535 0]夷Usamos el truco para disparar[n]l茨seres dobles?[n][f 1 3 65535][w][e]

[msg MND_201_6_0]
[s][vp 8 2 0 0 65535 0]夷Uso el truco del libro?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Usar la t姻cnica[e]
[s]Jugar de forma normal[e]

[msg MSG_READ_BOOK_URAWAZA_NO [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Vaya, est茨s que te sales![n]斡Venga, a por ello![n][f 1 3 65535][w][e]

[msg MND_202_6_0]
[s][vp 8 2 0 0 65535 0]Deber胤a recurrir a mis habilidades[n]para conseguirlo.[n][f 1 3 65535][w][e]

[msg MSG_READ_BOOK_URAWAZA_YE [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Se nota que has aprendido.[n]斡Vale, vamos al l胤o![n][f 1 3 65535][w][e]

[msg MND_203_6_0]
[s][vp 8 2 0 0 65535 0]Ahora el juego[n]deber胤a ser menos dif胤cil.[n][f 1 3 65535][w][e]

[msg HLP_BOOK_NG_01]
[s][vp 8 2 0 0 65535 0]Pulsa [f 1 10 75] muchas veces[n]antes de que se acabe el tiempo.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Este juego va de batallas[n]espaciales, 夷no? 夷Y esto tan[n]peque隠o de aqu胤 es tu nave?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hala... Te est茨s cargando[n]las naves enemigas una tras otra...[n]No est茨 mal para un novato.[n][f 1 3 65535][w][e]

[msg MND_205_6_0]
[s][vp 8 2 0 0 65535 0]Los enemigos son agresivos[n]hasta al principio del juego.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vale, le has pillado el tranquillo[n]a derrotar a los enemigos.[n]斡Y has conseguido potenciadores![n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece que esta vez lo est茨s[n]haciendo bien. Creo que, si lo[n]intentas, puedes derrotar al jefe.[n][f 1 3 65535][w][e]

[msg MND_205_7_0]
[s][vp 8 2 0 0 65535 0]Ya me he pasado esta fase.[n]Me acuerdo bastante bien[n]de los patrones de los enemigos.[n][f 1 3 65535][w][e]

[msg MSG_Stage01_Boss1st [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ya no hay m茨s enemigos en pantalla.[n]夷Has ganado?[n][f 1 3 65535][w][e]

[msg MSG_Stage01_Boss1st_2 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]斡夷Q-qu姻 narices?! 斡Qu姻 cosa[n]m茨s grande! Debe de ser el jefe.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oye, creo que tienes que ir a por[n]el n雨cleo del centro. 斡Disp茨rale![n][f 1 3 65535][w][e]

[msg MSG_Stage01_BossCommon [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]El n雨mero de enemigos est茨[n]bajando. 夷Aparecer茨 pronto el jefe?[n][f 1 3 65535][w][e]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 1179 65535 0]斡Anda, ah胤 est茨! 斡Lo sab胤a![n]Bueno, 斡apunta al n雨cleo y dispara![n][f 1 3 65535][w][e]

[msg MND_206_6_0]
[s][vp 8 2 0 0 65535 0]Parece que el nivel est茨 cambiando.[n][f 1 3 65535][w][e]

[msg MND_206_6_0_2]
[s][vp 8 2 0 0 65535 0]斡Es el jefe![n]Ser茨 f茨cil derrotarlo[n]si disparo r茨pidamente al n雨cleo.[n][f 1 3 65535][w][e]

[msg MND_207_6_0]
[s][vp 8 2 0 0 65535 0]Me ha faltado tiempo.[n]Esto cuenta como derrota...[n][f 1 3 65535][w][e]

[msg MND_208_6_0]
[s][vp 8 2 0 5 65535 0]斡He ganado![n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Mmm. Ese enemigo es nuevo.[n]Apunta bien antes de[n]intentar derribarlo.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bien, bien...[n]Parece que vas a conseguirlo.[n][f 1 3 65535][w][e]

[msg MND_023_1_0]
[s][vp 8 2 0 0 65535 0]Estos enemigos[n]son tan agresivos como siempre.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Jol胤n, estos t胤os son tan[n]peligrosos como siempre. Cuidado,[n]que tambi姻n vienen por abajo.[n][f 1 3 65535][w][e]

[msg MND_024_1_0]
[s][vp 8 2 0 12 65535 0]Estos enemigos[n]son tan agresivos como siempre.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1132 65535 0]Vaya, no quedan muchos[n]enemigos. 夷Ya viene el jefe?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Ah胤 est茨! Qu姻 de tent茨culos...[n]Hay que destruirlos[n]antes de atacar el n雨cleo.[n][f 1 3 65535][w][e]

[msg MND_025_1_0]
[s][vp 8 2 0 0 65535 0]No quedan muchos enemigos[n]a estas alturas.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Un momento. 斡Es el jefe![n]Creo que utiliza los tent茨culos[n]para proteger el n雨cleo.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1181 65535 0]斡Bien! 斡Has destruido todos[n]los tent茨culos y el n雨cleo![n][f 1 3 65535][w][e]

[msg MND_028_1_0]
[s][vp 8 2 0 0 65535 0]斡Lo he derribado![n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 1179 65535 0]Vaya, te ha dado con un tent茨culo.[n]Creo que te has acercado demasiado.[n][f 1 3 65535][w][e]

[msg MND_031_1_0]
[s][vp 8 2 0 0 65535 0]Jol胤n, me ha dado con un tent茨culo.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1184 65535 0]Por fin hemos llegado al 雨ltimo[n]nivel. Qu姻 mal rollo da esto...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Ya hemos derrotado a un mont吋n[n]de enemigos! Pero ten cuidado.[n]El jefe debe de estar al caer.[n][f 1 3 65535][w][e]

[msg MND_034_1_0]
[s][vp 8 2 0 0 65535 0]Por fin he llegado al 雨ltimo nivel.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1035 65535 0]Este es el 雨ltimo nivel.[n]斡No bajes la guardia![n][f 1 3 65535][w][e]

[msg MND_035_1_0]
[s][vp 8 2 0 0 65535 0]Estoy en el 雨ltimo nivel.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]斡Hala! 斡Acaban de salir enemigos[n]de los agujeros del fondo![n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Has llegado muy lejos...[n]斡No puedes perder ahora![n][f 1 3 65535][w][e]

[msg MND_036_1_0]
[s][vp 8 2 0 0 65535 0]斡Est茨n saliendo enemigos[n]de los agujeros del fondo![n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vale, has sobrevivido.[n]Pero 夷este es el final?[n][f 1 3 65535][w][e]

[msg MND_039_1_0]
[s][vp 8 2 0 10 65535 0]He salido con vida...[n][f 1 3 65535][w][e]

[msg MSG_040_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡No! Te han pillado...[n][f 1 3 65535][w][e]

[msg MND_040_1_0]
[s][vp 8 2 0 19 65535 0]He perdido.[n][f 1 3 65535][w][e]

[msg MSG_041_0_0 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 1179 65535 0]La pantalla se ha quedado en negro.[n][f 1 3 65535][w][e]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡H-hala! 斡El 雨ltimo jefe![n]斡Tienes que ir a por todas![n][f 1 3 65535][w][e]

[msg MND_041_1_0]
[s][vp 8 2 0 0 65535 0]La pantalla dej吋 de moverse...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]... y ha aparecido un jefe m茨s grande[n]que todos los que hemos visto[n]hasta ahora. 斡Ser茨 el jefe final![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1045 65535 0][f 4 22 65535 3 22]斡Incre胤ble! 斡Est茨 explotando![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 1182 65535 0]Vaya, no lo has conseguido.[n][f 1 3 65535][w][e]

[msg MSG_045_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1171 65535 0]El jefe est茨 desapareciendo.[n]Creo que eso es que hemos ganado.[n][f 1 3 65535][w][e]

[msg MND_045_1_0]
[s][vp 8 2 0 0 65535 0]斡He derrotado al jefe final![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Aj! Nos han derrotado...[n][f 1 3 65535][w][e]

[msg MND_050_1_0]
[s][vp 8 2 0 0 65535 0]No... Me ha machacado.[n][f 1 3 65535][w][e]

[msg MSG_StageClear [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1183 65535 0]斡Vaya! Has conseguido[n]pasarte el nivel. Impresionante.[n][f 1 3 65535][w][e]

[msg MND_StageClear]
[s][vp 8 2 0 93 65535 0]斡Me he pasado la fase![n][f 1 3 65535][w][e]

[msg MSG_StageGameOver [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 1169 65535 0]Pf, qu姻 decepci吋n.[n]Se ha acabado la partida.[n][f 1 3 65535][w][e]

[msg MND_StageGameOver]
[s][vp 8 2 0 87 65535 0]Se ha acabado la partida...[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1048 65535 0]斡Te has pasado Star Forneus![n][f 1 3 65535][w][e]

[msg MND_046_1_0]
[s][vp 8 2 0 100 65535 0]斡Me he pasado Star Forneus![n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 1182 65535 0]Con lo lejos que hemos llegado[n]y van y nos derrotan...[n][f 1 3 65535][w][e]

[msg MND_051_1_0]
[s][vp 8 2 0 102 65535 0]Se ha acabado la partida...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Seguro que traspasar la barrera[n]enemiga ha aumentado tu [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][f 1 3 65535][w][e]

[msg MND_018_1_0]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Parece que luchar contra el[n]enemigo ha aumentado mi [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Seguro que acercarte al[n]enemigo ha aumentado tu [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][f 1 3 65535][w][e]

[msg MND_029_1_0]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Parece que luchar contra el[n]enemigo ha aumentado mi [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Has sobrevivido a sus[n]ataques agresivos... Seguro que[n]tu [f 4 11 3][clr 26][f 4 12 3][clr 27] ha aumentado.[n][f 1 3 65535][w][e]

[msg MND_048_1_0]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Parece que luchar contra el[n]enemigo ha aumentado mi [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1166 65535 0][f 4 22 65535 1 41]夷El libro de t姻cnicas secretas te ayud吋?[n]Lo que m茨s admiro de ti es que[n]siempre busques c吋mo ser eficiente.[n][f 1 3 65535][w][e]

[msg MND_019_1_0]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Las t姻cnicas secretas[n]han sido muy 雨tiles.[n][f 1 3 65535][w][e]

[msg MSG_FAILED_UP [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Has perdido, pero aun as胤[n]parece que combatir[n]ha aumentado tu [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][f 1 3 65535][w][e]

[msg MND_FAILED_UP]
[s][vp 8 2 0 0 65535 0]He fracasado, pero mi [f 4 11 3][clr 26][f 4 12 3][clr 27][n] aumentado un poco debido[n]a que he luchado contra el enemigo.[n][f 1 3 65535][w][e]

[msg MSG_HINTO_BOOK_NO [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ojal茨 hubiera una forma de hacer[n]que este juego fuera m茨s f茨cil...[n][f 1 3 65535][w][e]

[msg MND_HINTO_BOOK_NO]
[s][vp 8 2 0 0 65535 0]Ojal茨 hubiera una forma[n]de bajar la dificultad del juego.[n][f 1 3 65535][w][e]

[msg MSG_HINTO_BOOK00 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷No tienes un libro[n]que habla de t姻cnicas secretas?[n]Igual estar胤a bien leerlo.[n][f 1 3 65535][w][e]

[msg MND_HINTO_BOOK04]
[s][vp 8 2 0 0 65535 0]Ahora que me acuerdo, yo tengo[n]un libro de t姻cnicas secretas.[n]Igual deber胤a le姻rmelo.[n][f 1 3 65535][w][e]

[msg MSG_BOOK_DONE_M [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Te parece demasiado dif胤cil?[n]斡Habr茨 que volver a intentarlo![n][f 1 3 65535][w][e]

[msg MND_BOOK_DONE_N]
[s][vp 8 2 0 0 65535 0]Es bastante dif胤cil...[n]Volver姻 a intentarlo m茨s tarde.[n][f 1 3 65535][w][e]

[msg MSG_GAME_END_MORU [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1175 65535 0]Vaya, se est茨 haciendo tarde.[n]Acost姻monos pronto, 夷eh?[n][f 1 3 65535][w][e]

[msg MND_GAME_END_NULL]
[s][vp 8 2 0 94 65535 0]Se est茨 haciendo tarde.[n]Deber胤a irme a la cama.[n][f 1 3 65535][w][e]

[msg MSG_GAME_END_MORU_DAY [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1175 65535 0]Lo que ha costado...[n]Igual deber胤amos dejar de jugar[n]de momento, 夷no crees?[n][f 1 3 65535][w][e]

[msg MND_GAME_END_NULL_DAY]
[s][vp 8 2 0 94 65535 0]Mmm. Igual deber胤a dejar[n]un rato los videojuegos...[n][f 1 3 65535][w][e]

[msg MSG_DEBUG]
[s][vp 8 2 0 0 65535 0]Debug Mode[n][f 1 3 65535][w][e]

[sel SEL_DEBUG top]
[s]with morgana[e]
[s]no morgana[e]

[msg MSG_DEBUG_2]
[s][vp 8 2 0 0 65535 0]Debug Mode[n][f 1 3 65535][w][e]

[sel SEL_DEBUG_2 top]
[s]stage 1[e]
[s]stage 2[e]
[s]stage 3[e]

[msg MSG_DEBUG_3]
[s][vp 8 2 0 0 65535 0]Debug Mode[n][f 1 3 65535][w][e]

[sel SEL_DEBUG_3 top]
[s]1st time[e]
[s]2nd time[e]

