[msg MSG_MOVIE11_VOICE_1 [ドン]]
[s][vp 8 0 0 0 65535 0]友は近くに置く。[n]敵...? 遠くに置くよ! 当然だろ、危ないし![n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]家族を大切にしないやつは、父親じゃない。[n][f 1 3 65535][w][e]

[msg MSG_MOVIE11_VOICE_2 [二代目]]
[s][vp 8 0 0 0 65535 0]親父...優しさと小心は違う。親父の優しさは、[n]きっと巡り巡って...誰かを死なせる。[n][f 1 3 65535][w][e]

[msg MSG_MOVIE11_MORU_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Qu姻 profundo... Te hace reflexionar...[n][f 1 3 65535][w][e]

[msg MSG_MOVIE11_MORU_02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Al final, 夷qu姻 es ser gentil?[n][f 1 3 65535][w][e]

[msg MSG_MOVIE11_MIND]
[s][vp 8 0 0 0 65535 0][f 4 22 65535 1 41]Siento que he aprendido a ser[n]m茨s compasivo con los dem茨s.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE11_MIND_Book]
[s][vp 8 0 0 0 65535 0]Siento que he aprendido a ser[n]m茨s compasivo con los dem茨s.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Gracias a [clr 3]El arte del cine[clr 27],[n]pude disfrutar de la pel胤cula[n]en mayor profundidad.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE12_VOICE_1 [師範ニンジャ]]
[s][vp 8 0 0 0 65535 0]あっ、拙者のワラジのひもが...[n]...ビシッ!![n][f 1 3 65535][w][e]

[msg MSG_MOVIE12_VOICE_2 [Protagonista]]
[s][vp 8 0 0 0 65535 0]グアーーッ![n][f 1 3 65535][w][e]

[msg MSG_MOVIE12_VOICE_3 [師範ニンジャ]]
[s][vp 8 0 0 0 65535 0]遅い! 光と同じくらい素早くならねば、[n]未来へは帰れぬでござるぞ...!![n][f 1 3 65535][w][e]

[msg MSG_MOVIE12_MORU_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡夷Vuelven solos?! 夷C吋mo es que esto[n]es un cl茨sico de culto?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Pero supongo que se puede[n]considerar educativa por toda[n]la ciencia que hay.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE12_MORU_02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ser茨 rara, pero cada vez[n]me gusta m茨s.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE12_MIND]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Siento que he aprendido m茨s sobre[n]el lado divertido de la ciencia.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE12_MIND_Book]
[s][vp 8 0 0 0 65535 0]Siento que he aprendido m茨s sobre[n]el lado divertido de la ciencia.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Gracias a [clr 3]El arte del cine[clr 27],[n]pude disfrutar de la pel胤cula[n]en mayor profundidad.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE12_MIND_Friend]
[s][vp 8 2 0 0 65535 0]Siento que he aprendido m茨s sobre[n]el lado divertido de la ciencia.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Con Futaba a mi lado, me sent胤 como[n]si hubiese visto la pel胤cula[n]por primera vez...[n][f 1 3 65535][w][e]

[msg MSG_MOVIE12_MIND_Book_Fr]
[s][vp 8 0 0 0 65535 0]Siento que he aprendido m茨s sobre[n]el lado divertido de la ciencia.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][vp 8 0 0 0 65535 0]Con Futaba a mi lado, me sent胤 como[n]si hubiese visto la pel胤cula[n]por primera vez...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Gracias a [clr 3]El arte del cine[clr 27],[n]pude disfrutar de la pel胤cula[n]en mayor profundidad.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE13_VOICE_1 [デビッド少佐]]
[s][vp 8 0 0 0 65535 0]メリークリスマス、軍曹?[n]特別メニューは捗っているかな?[n][f 1 3 65535][w][e]

[msg MSG_MOVIE13_VOICE_2 [トラ軍曹]]
[s][vp 8 0 0 0 65535 0]メニー苦しみます...![n]メニー苦しみます...![n][f 1 3 65535][w][e]

[msg MSG_MOVIE13_VOICE_3 [デビッド少佐]]
[s][vp 8 0 0 0 65535 0]オーケー、ただでさえ寒い冬にクールな♀落を[n]ありがとう。...更に10セット追加だッ![n][f 1 3 65535][w][e]

[msg MSG_MOVIE13_VOICE_4 [トラ軍曹]]
[s][vp 8 0 0 0 65535 0]に、日本軍人は、ぜったい、助けてなんて、[n]言わないのであります...![n][f 1 3 65535][w][e]

[msg MSG_MOVIE13_MORU_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Venga! 斡P胤dele ayuda[n]de una vez! Jo, este personaje[n]tiene un coraje que no es normal...[n][f 1 3 65535][w][e]

[msg MSG_MOVIE13_MORU_02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El estoicismo fingido y el coraje[n]falso no son nada sanos...[n][f 1 3 65535][w][e]

[msg MSG_MOVIE13_MIND]
[s][vp 8 0 0 0 65535 0][f 4 22 65535 1 41]Siento que he entendido la voluntad[n]del sargento para enfrentarse[n]a las adversidades.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE13_MIND_Book]
[s][vp 8 0 0 0 65535 0]Siento que he entendido la voluntad[n]del sargento para enfrentarse[n]a las adversidades.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Gracias a [clr 3]El arte del cine[clr 27],[n]pude disfrutar de la pel胤cula[n]en mayor profundidad.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE16_MORU_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]T胤o, ese psiquiatra da mal rollo.[n]Pero debo admitir que[n]parece saber de lo que habla.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE16_MORU_02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espero que no venga a por m胤 ahora...[n]Sin mi abrigo de piel,[n]斡seguro que me resfr胤o![n][f 1 3 65535][w][e]

[msg MSG_MOVIE16_MIND]
[s][vp 8 0 0 0 65535 0][f 4 22 65535 1 41]Creo que he aprendido un poco m茨s[n]sobre analizar problemas[n]con calma.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE16_MIND_Book]
[s][vp 8 0 0 0 65535 0]Creo que he aprendido un poco m茨s[n]sobre analizar problemas[n]con calma.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Gracias a [clr 3]El arte del cine[clr 27],[n]pude disfrutar de la pel胤cula[n]en mayor profundidad.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE17_MORU_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No me puedo creer que se haya[n]enfrentado al decano... Deber胤amos[n]aprender de su sacrificio.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE17_MORU_02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El decano parece un sargento[n]de instrucci吋n...[n][f 1 3 65535][w][e]

[msg MSG_MOVIE17_MIND]
[s][vp 8 0 0 0 65535 0][f 4 22 65535 1 41]Siento que he aprendido a ser[n]m茨s compasivo con los dem茨s.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE17_MIND_Book]
[s][vp 8 0 0 0 65535 0]Siento que he aprendido a ser[n]m茨s compasivo con los dem茨s.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Gracias a [clr 3]El arte del cine[clr 27],[n]pude disfrutar de la pel胤cula[n]en mayor profundidad.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE18_MORU_01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No hay que rendirse nunca, por muy[n]desesperada que sea la situaci吋n.[n]Es una actitud admirable.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE18_MORU_02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El circo est茨 lleno de bestias.[n]Normal que Pierre haya huido.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE18_MIND]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]He aprendido mucho sobre la vida.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE18_MIND_Book]
[s][vp 8 0 0 0 65535 0]He aprendido mucho sobre la vida.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Gracias a [clr 3]El arte del cine[clr 27],[n]pude disfrutar de la pel胤cula[n]en mayor profundidad.[n][f 1 3 65535][w][e]

[msg MSG_MOVIE_END_1]
[s][vp 8 0 0 0 65535 0]Vimos los cr姻ditos hasta el final...[n][f 1 3 65535][w][e]

[msg MSG_MOVIE_END_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Muy bien, v茨monos a casa.[n][f 1 3 65535][w][e]

[msg MSG_FUTABA_1 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9048 65535 0]斡Ya la he visto como cincuenta[n]veces, pero la ac雨stica del cine[n]me sigue impresionando![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Sabes? Las pelis de ciencia[n]ficci吋n no son solo chorradas[n]que se inventan.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es como... un sue隠o que quiz茨s alg雨n[n]d胤a se har茨 realidad. 斡Es como[n]la esperanza! 夷Entiendes?[n][f 1 3 65535][w][e]

[sel SEL_FUTABA_1 top]
[s]Creo que s胤...[e]
[s]La verdad es que no.[e]

[msg MSG_FUTABA_2 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 9161 65535 0][f 5 13 10 10 8]斡Mola, tienes potencial![n][f 1 3 65535][w][e]

[msg MSG_FUTABA_3 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 9062 65535 0][f 5 13 10 5 8]Supongo que necesitar茨s[n]un poco de formaci吋n...[n]Je, je. 斡Ser茨 divertido![n][f 1 3 65535][w][e]

[msg MSG_FUTABA_5 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9030 65535 0]斡Bueno, gracias por quedar conmigo![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ehh... Ha sido mucho m茨s divertido[n]que todas las veces que[n]la he visto sola.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Y si hacemos una marat吋n de pelis[n]de ciencia ficci吋n extranjeras?[n]斡Espero que te haga ilusi吋n![n][f 1 3 65535][w][e]

[msg MSG_MOVIE_END [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tan peculiar como siempre...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 1050 65535 0]V茨monos a casa nosotros tambi姻n.[n]Aunque est茨 justo ah胤...[n][f 1 3 65535][w][e]

[msg TEST_MONA2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Has subido de nivel, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_DEBUG [Debug]]
[s]※April 1st Only Debug[n]Scene check setting[n][f 1 3 65535][w][e]

[sel SEL_DEBUG top]
[s]Morgana[e]
[s]Futaba[e]
[s]Takemi[e]
[s]Salir de debug[e]

