[msg MSG_045_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, [f 4 2],[n]夷qu姻 quieres usar esta vez?[n][f 1 3 65535][w][e]

[sel SEL_046_0_0 top]
[s]Vamos a usar el banco de pesas.[e]
[s]Vamos a hacer cinta.[e]
[s]Vamos a usar el mu隠eco de madera.[e]

[msg MSG_047_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Venga, vamos a empezar.[n]Espera, 夷quieres un batido[n]de prote胤nas antes de entrenar?[n][f 1 3 65535][w][e]

[sel SEL_048_0_0 top]
[s]Tomar [var 0].[e]
[s]Tomar [var 1].[e]
[s]Nada[e]

[msg MND_049_0_0]
[s][vp 8 0 0 0 65535 0]Buf, qu姻 mal sabe...[n][f 1 3 65535][w][e]

[msg MND_050_0_0]
[s][vp 8 0 0 0 65535 0]Mm, no est茨 mal...[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Buen trabajo, [f 4 2]![n]斡Lev茨ntalo! 斡T雨 puedes![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Lleva tus m雨sculos al l胤mite[n]y luego... 斡sobrep茨salo![n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Buen trabajo! Bueno, 夷qu姻?[n]夷Ha sido un buen entrenamiento?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Con tanto ejercicio,[n]seguro que te has hecho m茨s fuerte.[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 22 65535 1 41]Y puede que sea por[n]el efecto del batido de prote胤nas,[n]pero... se te ve m茨s varonil.[n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Vas a buen ritmo,[n][f 4 2]![n]斡Hoy est茨s que te sales![n][f 1 3 65535][w][e]
[s][bup 0 3 8 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Qu姻 te parece[n]si lo complicamos un poco?[n][f 1 3 65535][w][e]

[sel SEL_055_0_0 top]
[s]斡Acepto el desaf胤o![e]
[s]Mejor no...[e]

[msg MSG_056_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya veo. Bueno, de todas formas,[n]no siempre es bueno[n]exigirse demasiado.[n][f 1 3 65535][w][e]

[msg MSG_057_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Halaaa! 斡Incre胤ble![n]斡As胤 se hace, [f 4 2]![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Est茨s espl姻ndido![n]斡Brillante y espl姻ndido,[n]como el sol![n][f 1 3 65535][w][e]

[msg MSG_058_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Buen trabajo. Igual te has[n]exigido demasiado...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Aunque seguro que[n]merecer茨 la pena.[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sin embargo, dudo que notes[n]los efectos de la prote胤na.[n][f 1 3 65535][w][e]

[msg MSG_060_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Ha sido incre胤ble, [f 4 2]![n]斡No pensaba que pudieras[n]entrenar as胤![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Seguro que esta vez[n]obtienes mejores resultados.[n][f 1 3 65535][w][e]

[msg MSG_061_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 22 65535 1 41]Puede que sea por[n]el efecto del batido de prote胤nas,[n]pero... se te ve m茨s varonil.[n][f 1 3 65535][w][e]

[msg MSG_062_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, ya est茨 bien.[n]Deber胤amos volver a casa.[n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Oye! 斡夷Qu姻 pasa, [f 4 2]?![n]斡Yo todav胤a voy bien![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Corre, correeee! 斡No te detengas[n]hasta que me supereees![n][f 1 3 65535][w][e]

[msg MSG_064_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Buen trabajo! 斡Has corrido mucho![n]夷Te ha gustado el entrenamiento?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Has hecho mucho ejercicio.[n]Seguro que has obtenido[n]beneficios a nivel f胤sico y mental.[n][f 1 3 65535][w][e]

[msg MSG_065_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 22 65535 1 41]Y puede que sea por[n]el efecto del batido de prote胤nas,[n]pero... se te ve m茨s varonil.[n][f 1 3 65535][w][e]

[msg MSG_066_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Guau, [f 4 2]! 斡Est茨s[n]corriendo m茨s que de costumbre![n][f 1 3 65535][w][e]
[s][bup 0 3 8 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero seguro que puedo[n]batir tu r姻cord.[n]Bueno, 夷qu姻? 夷Subimos el ritmo?[n][f 1 3 65535][w][e]

[sel SEL_067_0_0 top]
[s]斡Venga![e]
[s]Nah, yo voy a mi ritmo.[e]

[msg MSG_068_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Eh? 夷En serio? B-bueno,[n]supongo que no es bueno exigirse[n]demasiado de todas formas.[n][f 1 3 65535][w][e]

[msg MSG_069_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Hala! 夷Vas a velocidad m茨xima?[n]斡Vaya, [f 4 2]![n]斡Qu姻 r茨pido eres![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Soy el 雨nico que te puede[n]seguir el ritmo. 斡Venga, venga![n][f 1 3 65535][w][e]

[msg MSG_070_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Buen trabajo. Igual te has[n]exigido demasiado...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]B-bueno, seguro que obtienes[n]resultados por todo el esfuerzo[n]que has realizado.[n][f 1 3 65535][w][e]

[msg MSG_070_1_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]B-buen trabajo... Igual... te has[n]exigido... demasiado...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]P-pero... seguro que obtienes[n]resultados... por todo el esfuerzo...[n]que has realizado...[n][f 1 3 65535][w][e]

[msg MSG_071_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sin embargo, dudo que notes[n]los efectos de la prote胤na.[n][f 1 3 65535][w][e]

[msg MSG_071_1_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aunque dudo...[n]que notes los efectos...[n]de la prote胤na...[n][f 1 3 65535][w][e]

[msg MSG_072_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ha sido una carrera incre胤ble,[n][f 4 2]. 斡Has batido[n]tu r姻cord en distancia y ritmo![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Has hecho mucho ejercicio,[n]as胤 que seguro que esta vez[n]obtienes mejores resultados.[n][f 1 3 65535][w][e]

[msg MSG_073_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 22 65535 1 41]Puede que sea por[n]el efecto del batido de prote胤nas,[n]pero... se te ve m茨s varonil.[n][f 1 3 65535][w][e]

[msg MSG_074_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Muy bien, ya llevamos bastante[n]tiempo aqu胤. 夷Nos vamos a casa?[n][f 1 3 65535][w][e]

[msg MSG_074_1_0 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Lo... lo siento mucho...[n]Ya llevamos bastante[n]tiempo aqu胤... V茨monos a casa...[n][f 1 3 65535][w][e]

[msg MSG_075_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Venga, pu隠etazo! 斡Patada![n]斡No olvides defenderte![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Tu enemigo no es de madera![n]斡Es un enemigo poderoso![n]斡Mira! 斡Mira c吋mo te atacaaa![n][f 1 3 65535][w][e]

[msg MSG_076_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Buen trabajo. Bueno, 夷has podido[n]entrenar visualizando[n]a tu enemigo?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Si lo has hecho bien,[n]seguro que has entrenado[n]tambi姻n a nivel mental.[n][f 1 3 65535][w][e]

[msg MSG_077_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 22 65535 1 41]Y puede que sea por[n]el efecto del batido de prote胤nas,[n]pero... se te ve m茨s varonil.[n][f 1 3 65535][w][e]

[msg MSG_078_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Vaya, hoy est茨s en plena forma.[n]斡Est茨s que te sales![n][f 1 3 65535][w][e]
[s][bup 0 3 8 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Venga, vamos a aprovechar[n]para darle ca隠a.[n]斡Aumentemos la velocidad![n][f 1 3 65535][w][e]

[sel SEL_079_0_0 top]
[s]斡Vamos all茨![e]
[s]Nah, yo voy a mi ritmo.[e]

[msg MSG_080_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Eh? 夷En serio? B-bueno,[n]supongo que no es bueno exigirse[n]demasiado de todas formas.[n][f 1 3 65535][w][e]

[msg MSG_081_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Buen trabajo, [f 4 2]![n]Tus movimientos son suaves[n]y fluidos. 斡Es impresionante![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Pareces una estrella de cine.[n]斡Sigue as胤![n][f 1 3 65535][w][e]

[msg MSG_082_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]B-buen trabajo. 夷Qu姻 pasa?[n]夷Te has hecho da隠o en el pu隠o?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]C-creo que me he emocionado y[n]te he exigido demasiado. Lo siento.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]B-bueno, seguro que obtienes[n]buenos resultados. Creo...[n][f 1 3 65535][w][e]

[msg MSG_083_0_0 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sin embargo, dudo que notes[n]los efectos de la prote胤na.[n][f 1 3 65535][w][e]

[msg MSG_084_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Has visualizado tan bien a tu[n]enemigo que yo tambi姻n lo he visto.[n]斡Has hecho unos combos incre胤bles![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ha sido una sesi吋n de entrenamiento[n]genial, as胤 que creo que obtendr茨s[n]m茨s beneficios que de costumbre.[n][f 1 3 65535][w][e]

[msg MSG_085_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 22 65535 1 41]Puede que sea por[n]el efecto del batido de prote胤nas,[n]pero... se te ve m茨s varonil.[n][f 1 3 65535][w][e]

[msg MSG_086_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Muy bien, ya llevamos bastante[n]tiempo aqu胤. 夷Nos vamos a casa?[n][f 1 3 65535][w][e]

[msg SYS_090_0_0]
[s]Tus [clr 2]PS m茨ximos[clr 27] aumentan en [clr 2][var 0][clr 27].[n][f 1 3 65535][w][e]

[msg SYS_091_0_0]
[s]Tus [clr 2]PE m茨ximos[clr 27] aumentan en [clr 2][var 1][clr 27].[n][f 1 3 65535][w][e]

[msg MSG_100_0_0 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 47 65535 0]Has subido de nivel, 夷no?[n][f 1 3 65535][w][e]

