[msg MSG_007_0_0 [Encargado]]
[s][vp 8 2 0 58451 5 0]Ah, t雨 eres el nuevo, 夷no?[n]Te estaba esperando.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]No hace falta que te presentes.[n]De hecho, necesito que empieces[n]a trabajar ya mismo.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 58452 5 0]夷Tienes alguna pregunta[n]sobre el trabajo?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0_2nd [Encargado]]
[s][vp 8 2 0 0 5 0]夷Algo m茨s?[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]夷En qu姻 consiste el trabajo?[e]
[s]夷Ten姻is m茨s empleados?[e]
[s]No, ninguna.[e]

[msg MSG_009_0_0 [Encargado]]
[s][vp 8 2 0 58453 5 0]Apuntas los pedidos de la gente,[n]los preparas, los sirves, avisas[n]y luego lo limpias todo.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]La comida ya est茨 preparada,[n]as胤 que te ser茨 sencillo.[n]S姻 amable con los clientes, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Encargado]]
[s][vp 8 2 0 58454 5 0]Pues no. A pesar de que nos falta[n]gente, nos han recortado el[n]presupuesto, as胤 que est茨s t雨 solo.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Te veo lleno de energ胤a, 夷eh?[n]Te las arreglar茨s. Para compensar,[n]te pagar姻 mejor.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1038 65535 0]Esto es rid胤culo. 夷Te las tienes[n]que arreglar t雨 solo con todo[n]desde el primer d胤a?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bueno, t雨 haz lo que puedas.[n]Estar姻 aqu胤 para animarte.[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]Oye, a雨n quedan platos sucios[n]en la mesa.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Y hay clientes esperando para[n]pagar... 夷Puedes con todo?[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]Ese cliente de ah胤 enfrente[n]est茨 esperando para pagar,[n]y tiene cara de mala leche.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oye, hay alguien que quiere cambiar[n]el pedido. 夷Que quiere un huevo?[n]Deber胤a haberlo dicho antes.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1179 65535 0]Oye, que la carne ya est茨 lista.[n]Si la dejas en el fuego,[n]se va a quemar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ese cliente de ah胤 quiere su pedido[n]para llevar. 斡Con la de tiempo[n]que se necesita para prepararlo![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Encargado]]
[s][vp 8 2 0 58456 5 0]Bueno, buen trabajo. Puedes[n]irte, que ya has terminado por hoy.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Aqu胤 tienes lo tuyo.[n]Gracias. 斡Espero que sigas as胤![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]B-buf, ha sido duro...[n]Este trabajo se las trae.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Pero has conseguido encargarte[n]de todo t雨 solito. Yo creo que[n]lo has hecho muy bien.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Es normal que est姻s destrozado...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Pero has conseguido encargarte[n]de todo t雨 solito. Yo creo que[n]lo has hecho muy bien.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷S-seguro que est茨s bien?[n]Has estado todo el rato ah胤 solo...[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Pero has conseguido encargarte[n]de todo t雨 solito. Yo creo que[n]lo has hecho muy bien.[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1050 65535 0]斡Venga, v茨monos![n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1181 65535 0]A-a ver, mant姻n la calma,[n]斡y no olvides ning雨n pedido![n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷C吋mo era el primer pedido?[n][f 1 3 65535][w][e]

[msg MSG_028_1_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1180 65535 0]S胤, 斡eso es![n][f 1 3 65535][w][e]

[msg MSG_028_2_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Qu姻 llevaba el segundo pedido?[n][f 1 3 65535][w][e]

[msg MSG_028_3_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1183 65535 0]S胤, eso mismo.[n][f 1 3 65535][w][e]

[msg MSG_028_4_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Y el tercero?[n][f 1 3 65535][w][e]

[msg MSG_028_5_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1166 65535 0]S胤, yo tambi姻n entend胤 eso.[n][f 1 3 65535][w][e]

[msg MSG_028_6_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Y el cuarto pedido, 夷c吋mo era?[n][f 1 3 65535][w][e]

[msg MSG_028_7_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1157 65535 0]斡S胤, era justo eso![n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]斡O-oye, no era eso![n]Era un bol de ternera mediano.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1037 65535 0]Oye, un momento. 夷No quer胤an[n]un bol de ternera grande?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1139 65535 0]斡No, espera![n]Era un bol de barbacoa mediano.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1018 65535 0]夷En serio? Yo creo que era[n]un bol de barbacoa grande.[n][f 1 3 65535][w][e]

[msg MSG_033_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1027 65535 0]夷Eh? Pues yo creo que era[n]un bol de curry mediano.[n][f 1 3 65535][w][e]

[msg MSG_034_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1029 65535 0]No, no era eso. Han pedido[n]un bol de curry grande.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1038 65535 0]No, te digo yo que no.[n]Era un bol de natto mediano.[n][f 1 3 65535][w][e]

[msg MSG_036_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1043 65535 0]Creo que no era eso, 夷eh?[n]Era un bol de natto grande.[n][f 1 3 65535][w][e]

[msg MSG_037_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]No, estoy seguro de que era[n]un bol de cerdo mediano.[n][f 1 3 65535][w][e]

[msg MSG_038_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1065 65535 0]No, no era eso. Han pedido[n]un bol de cerdo grande.[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vale, ahora solo queda prepararlo[n]todo y servir los boles.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Vaya, ese cliente lleva un buen[n]rato esperando. 斡Date prisa![n][f 1 3 65535][w][e]

[msg MSG_048_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Qu姻 mal, les estamos haciendo[n]esperar un mont吋n. 斡Date prisa![n][f 1 3 65535][w][e]

[msg MSG_049_0_0 [Encargado]]
[s][vp 8 2 0 58458 5 0]斡Hala! Buen trabajo.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Hoy ha venido un mont吋n de gente,[n]pero lo has hecho de maravilla[n]t雨 solito.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 58455 5 0]Te he dado algo m茨s de dinero.[n]斡Sigue as胤![n][f 1 3 65535][w][e]

[msg MSG_049_0_1 [Encargado]]
[s][vp 8 2 0 58458 5 0]斡Hala! Buen trabajo.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Hoy ha venido un mont吋n de gente,[n]pero lo has hecho de maravilla[n]t雨 solito.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Hoy ha venido tanta gente[n]como en el [clr 2]D胤a de Yakiniku[clr 27].[n]夷Habr茨 pasado algo por aqu胤 cerca?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 58455 5 0]Te he dado algo m茨s de dinero.[n]斡Sigue as胤![n][f 1 3 65535][w][e]

[msg MSG_049_0_2 [Encargado]]
[s][vp 8 2 0 58458 5 0]斡Hala! Buen trabajo.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Hoy ha venido un mont吋n de gente,[n]pero lo has hecho de maravilla[n]t雨 solito.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Como el [clr 2]D胤a de Yakiniku[clr 27][n]vienen clientes a mansalva,[n]nadie quiere trabajar...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 58455 5 0]Te he dado algo m茨s de dinero.[n]斡Sigue as胤![n][f 1 3 65535][w][e]

[msg MSG_050_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Hoy has tenido un mont吋n[n]de pedidos, pero lo has bordado![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]S姻 que ha sido duro,[n]pero lo has llevado todo[n]con mucha profesionalidad.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Encargado]]
[s][vp 8 2 0 58456 5 0]Buen trabajo, chaval.[n]Hoy ha venido un mont吋n de gente.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]斡Hab胤a un mont吋n de trabajo, pero[n]te las has apa隠ado bastante bien[n]t雨 solo![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]No es mucho, pero te he pagado un[n]poquito m茨s hoy. 斡Sigue as胤![n][f 1 3 65535][w][e]

[msg MSG_051_0_1 [Encargado]]
[s][vp 8 2 0 58456 5 0]Buen trabajo, chaval.[n]Hoy ha venido un mont吋n de gente.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]斡Hab胤a un mont吋n de trabajo, pero[n]te las has apa隠ado bastante bien[n]t雨 solo![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Ni que hoy fuera el [clr 2]D胤a de[n]Yakiniku[clr 27]... 夷Habr茨 habido[n]alg雨n evento por aqu胤?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]No es mucho, pero te he pagado un[n]poquito m茨s hoy. 斡Sigue as胤![n][f 1 3 65535][w][e]

[msg MSG_051_0_2 [Encargado]]
[s][vp 8 2 0 58456 5 0]Buen trabajo, chaval.[n]Hoy ha venido un mont吋n de gente.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]斡Hab胤a un mont吋n de trabajo, pero[n]te las has apa隠ado bastante bien[n]t雨 solo![n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Como el [clr 2]D胤a de Yakiniku[clr 27][n]vienen clientes a mansalva,[n]nadie quiere trabajar...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]No es mucho, pero te he pagado un[n]poquito m茨s hoy. 斡Sigue as胤![n][f 1 3 65535][w][e]

[msg MSG_052_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Ja! Ese encargado s胤 que sabe[n]c吋mo tenerte contento.[n]Lo has hecho muy bien, la verdad.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Metiste un poco la pata, pero ha[n]sido un buen [f 4 11 2][clr 26][f 4 12 2][clr 27] entrenamiento,[n]夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_053_0_0 [Encargado]]
[s][vp 8 2 0 58456 5 0]Buen trabajo, chaval.[n]Hoy ha venido un mont吋n de gente.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]No suele haber tanto trabajo.[n]斡Espero que vuelvas pronto![n][f 1 3 65535][w][e]

[msg MSG_053_0_1 [Encargado]]
[s][vp 8 2 0 58456 5 0]Buen trabajo, chaval.[n]Hoy ha venido un mont吋n de gente.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Ni que hoy fuera el [clr 2]D胤a de[n]Yakiniku[clr 27]... 夷Habr茨 habido[n]alg雨n evento por aqu胤?[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]No suele haber tanto trabajo.[n]斡Espero que vuelvas pronto![n][f 1 3 65535][w][e]

[msg MSG_053_0_2 [Encargado]]
[s][vp 8 2 0 58456 5 0]Buen trabajo, chaval.[n]Hoy ha venido un mont吋n de gente.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]Como el [clr 2]D胤a de Yakiniku[clr 27][n]vienen clientes a mansalva,[n]nadie quiere trabajar...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 5 0]No suele haber tanto trabajo.[n]斡Espero que vuelvas pronto![n][f 1 3 65535][w][e]

[msg MSG_054_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Ja! Ese encargado s胤 que sabe[n]c吋mo tenerte contento.[n]Lo has hecho muy bien, la verdad.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 4 22 65535 1 41]Metiste un poco la pata, pero ha[n]sido un buen [f 4 11 2][clr 26][f 4 12 2][clr 27] entrenamiento,[n]夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1169 65535 0]Buf... Bueno, venga, v茨monos a casa.[n][f 1 3 65535][w][e]

[msg MSG_080_0_0 [Cliente]]
[s][vp 8 2 0 0 65535 0]Hola. Un bol de ternera mediano,[n]por favor.[n][f 1 3 65535][w][e]

[msg MSG_081_0_0 [Cliente]]
[s][vp 8 2 0 0 65535 0]Un bol de ternera grande,[n]por favor.[n][f 1 3 65535][w][e]

[msg MSG_082_0_0 [Cliente]]
[s][vp 8 2 0 0 65535 0]Yo quiero[n]un bol de barbacoa mediano.[n][f 1 3 65535][w][e]

[msg MSG_083_0_0 [Cliente]]
[s][vp 8 2 0 0 65535 0]Para m胤, un bol de barbacoa grande.[n][f 1 3 65535][w][e]

[msg MSG_084_0_0 [Cliente]]
[s][vp 8 2 0 0 65535 0]Un bol de curry mediano.[n][f 1 3 65535][w][e]

[msg MSG_085_0_0 [Cliente]]
[s][vp 8 2 0 0 65535 0]Un bol de curry grande, por favor.[n][f 1 3 65535][w][e]

[msg MSG_086_0_0 [Cliente]]
[s][vp 8 2 0 0 65535 0]Un bol de natto mediano.[n][f 1 3 65535][w][e]

[msg MSG_087_0_0 [Cliente]]
[s][vp 8 2 0 0 65535 0]Un bol de natto grande, por favor.[n][f 1 3 65535][w][e]

[msg MSG_088_0_0 [Cliente]]
[s][vp 8 2 0 0 65535 0]Un bol de cerdo mediano.[n][f 1 3 65535][w][e]

[msg MSG_089_0_0 [Cliente]]
[s][vp 8 2 0 0 65535 0]Un bol de cerdo grande, por favor.[n][f 1 3 65535][w][e]

[sel SEL_GYUDON_ANSWER0 top]
[s]Un bol de ternera mediano[e]
[s]Un bol de barbacoa grande[e]
[s]Un bol de curry mediano[e]

[sel SEL_GYUDON_ANSWER1 top]
[s]Un bol de natto mediano[e]
[s]Un bol de ternera mediano[e]
[s]Un bol de cerdo mediano[e]

[sel SEL_GYUDON_ANSWER2 top]
[s]Un bol de curry grande[e]
[s]Un bol de barbacoa grande[e]
[s]Un bol de ternera mediano[e]

[sel SEL_GYUDON_ANSWER3 top]
[s]Un bol de ternera grande[e]
[s]Un bol de barbacoa grande[e]
[s]Un bol de natto grande[e]

[sel SEL_GYUDON_ANSWER4 top]
[s]Un bol de curry mediano[e]
[s]Un bol de ternera grande[e]
[s]Un bol de cerdo grande[e]

[sel SEL_GYUDON_ANSWER5 top]
[s]Un bol de natto mediano[e]
[s]Un bol de curry mediano[e]
[s]Un bol de ternera grande[e]

[sel SEL_GYUDON_ANSWER6 top]
[s]Un bol de barbacoa mediano[e]
[s]Un bol de curry mediano[e]
[s]Un bol de ternera mediano[e]

[sel SEL_GYUDON_ANSWER7 top]
[s]Un bol de curry grande[e]
[s]Un bol de barbacoa mediano[e]
[s]Un bol de cerdo grande[e]

[sel SEL_GYUDON_ANSWER8 top]
[s]Un bol de cerdo grande[e]
[s]Un bol de barbacoa grande[e]
[s]Un bol de barbacoa mediano[e]

[sel SEL_GYUDON_ANSWER9 top]
[s]Un bol de barbacoa grande[e]
[s]Un bol de ternera grande[e]
[s]Un bol de curry grande[e]

[sel SEL_GYUDON_ANSWER10 top]
[s]Un bol de natto mediano[e]
[s]Un bol de barbacoa grande[e]
[s]Un bol de cerdo mediano[e]

[sel SEL_GYUDON_ANSWER11 top]
[s]Un bol de ternera mediano[e]
[s]Un bol de cerdo mediano[e]
[s]Un bol de barbacoa grande[e]

[sel SEL_GYUDON_ANSWER12 top]
[s]Un bol de curry mediano[e]
[s]Un bol de ternera grande[e]
[s]Un bol de cerdo grande[e]

[sel SEL_GYUDON_ANSWER13 top]
[s]Un bol de barbacoa mediano[e]
[s]Un bol de curry mediano[e]
[s]Un bol de cerdo mediano[e]

[sel SEL_GYUDON_ANSWER14 top]
[s]Un bol de natto mediano[e]
[s]Un bol de curry grande[e]
[s]Un bol de curry mediano[e]

[sel SEL_GYUDON_ANSWER15 top]
[s]Un bol de curry grande[e]
[s]Un bol de natto mediano[e]
[s]Un bol de ternera grande[e]

[sel SEL_GYUDON_ANSWER16 top]
[s]Un bol de natto mediano[e]
[s]Un bol de curry grande[e]
[s]Un bol de cerdo grande[e]

[sel SEL_GYUDON_ANSWER17 top]
[s]Un bol de barbacoa mediano[e]
[s]Un bol de barbacoa grande[e]
[s]Un bol de curry grande[e]

[sel SEL_GYUDON_ANSWER18 top]
[s]Un bol de natto mediano[e]
[s]Un bol de curry grande[e]
[s]Un bol de ternera mediano[e]

[sel SEL_GYUDON_ANSWER19 top]
[s]Un bol de cerdo mediano[e]
[s]Un bol de natto mediano[e]
[s]Un bol de curry grande[e]

[sel SEL_GYUDON_ANSWER20 top]
[s]Un bol de ternera grande[e]
[s]Un bol de barbacoa grande[e]
[s]Un bol de natto mediano[e]

[sel SEL_GYUDON_ANSWER21 top]
[s]Un bol de natto grande[e]
[s]Un bol de barbacoa grande[e]
[s]Un bol de cerdo grande[e]

[sel SEL_GYUDON_ANSWER22 top]
[s]Un bol de curry mediano[e]
[s]Un bol de natto grande[e]
[s]Un bol de ternera mediano[e]

[sel SEL_GYUDON_ANSWER23 top]
[s]Un bol de ternera grande[e]
[s]Un bol de barbacoa mediano[e]
[s]Un bol de natto grande[e]

[sel SEL_GYUDON_ANSWER24 top]
[s]Un bol de cerdo mediano[e]
[s]Un bol de curry mediano[e]
[s]Un bol de natto mediano[e]

[sel SEL_GYUDON_ANSWER25 top]
[s]Un bol de natto grande[e]
[s]Un bol de cerdo mediano[e]
[s]Un bol de barbacoa mediano[e]

[sel SEL_GYUDON_ANSWER26 top]
[s]Un bol de curry grande[e]
[s]Un bol de barbacoa mediano[e]
[s]Un bol de cerdo mediano[e]

[sel SEL_GYUDON_ANSWER27 top]
[s]Un bol de cerdo grande[e]
[s]Un bol de natto mediano[e]
[s]Un bol de barbacoa mediano[e]

[sel SEL_GYUDON_ANSWER28 top]
[s]Un bol de curry mediano[e]
[s]Un bol de cerdo grande[e]
[s]Un bol de ternera grande[e]

[sel SEL_GYUDON_ANSWER29 top]
[s]Un bol de natto mediano[e]
[s]Un bol de barbacoa mediano[e]
[s]Un bol de cerdo grande[e]

[msg MSG_RYUUJI_0_1 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7029 65535 0]Hala, 斡sab胤a que te conoc胤a![n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 8 5 2]A veces se llena hasta los topes...[n]No te fuerces, 夷eh?[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bueno, 斡voy a tomar gyuudon[n]con extra de salsa![n][f 1 3 65535][w][e]

[msg MSG_RYUUJI_1_1 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54250 65535 0]Eh, 夷currando a tope?[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 8 5 2]Te veo diferente cuando trabajas[n]aqu胤. Pareces m茨s maduro.[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]T胤o, 斡un gyuudon grande, porfa![n][f 1 3 65535][w][e]

[msg MSG_YOSIDA_0_1 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 2 0 20020 65535 0]Ah, eres t雨. Buenas noches.[n][f 1 3 65535][w][e]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 20 5 1012]Trabajando duro, como siempre.[n]Qu姻 chico tan responsable.[n][f 1 3 65535][w][e]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Bueno, creo que pedir姻 un[n]gyuudon mediano.[n][f 1 3 65535][w][e]

[msg MSG_YOSIDA_1_1 [Yoshida]]
[s][bup 0 112 500 0 0][f 4 10 65535 0 0][vp 8 2 0 20006 65535 0]Buenas noches. Parece que est茨s[n]trabajando duro.[n][f 1 3 65535][w][e]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0][f 5 13 20 5 1012]Verte trabajar me motiva[n]a esforzarme.[n][f 1 3 65535][w][e]
[s][bup 0 112 501 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Ah, deber胤a pedir algo. Quiero un[n]gyuudon mediano con huevo.[n][f 1 3 65535][w][e]

[msg MSG_DEBUG_NPC [デバッグ]]
[s][vp 8 2 0 0 65535 0]Aparece un amigo[n][f 1 3 65535][w][e]

[sel SEL_DEBUG_NPC top]
[s]竜司(初回)[e]
[s]竜司(汎用)[e]
[s]吉田(初回)[e]
[s]吉田(汎用)[e]
[s]誰も来ない[e]

