[msg MSG_Start_1st_000 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1126 65535 0]Qu姻 elegante pareces[n]con el taco en la mano.[n][f 1 3 65535][w][e]

[msg MSG_Start_1st_001 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Te lo juro. 斡Tienes pinta[n]de profesional![n][f 1 3 65535][w][e]

[msg MSG_Start_1st_002 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Ya has jugado antes?[n]Es que sabes cosas que solo[n]un profesional sabr胤a.[n][f 1 3 65535][w][e]

[sel SEL_Start_1st top]
[s]Lo dejo a tu imaginaci吋n.[e]
[s]夷Qu姻 es un taco?[e]

[msg MSG_Start_1st_003_00 [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 1134 65535 0]斡Qu姻 burl吋n! Creo que esto ser茨[n]un buen espect茨culo.[n][f 1 3 65535][w][e]

[msg MSG_Start_1st_003_01 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 1043 65535 0]斡Lo que tienes en la mano![n]Ya no tienes pinta de ser[n]tan profesional, 夷eh?[n][f 1 3 65535][w][e]

[msg MSG_Start_1st_004 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7045 65535 0]Je, je. Me estoy entusiasmando.[n]斡Venga, comencemos![n][f 1 3 65535][w][e]

[msg MSG_Start_Common_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Je, je... 斡Estoy deseando jugar![n]斡Empecemos de una vez![n][f 1 3 65535][w][e]

[msg MSG_Start_Common_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1180 65535 0]斡Parece que ya estamos todos![n]斡Os animar姻![n][f 1 3 65535][w][e]

[msg MSG_Start_Common_Anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6117 65535 0]斡Bien, vamos a empezar![n]斡Espero estar a la altura![n][f 1 3 65535][w][e]

[msg MSG_Start_Common_Yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4105 65535 0]Este ambiente estimula mis[n]sentidos. 斡Venga, empecemos![n][f 1 3 65535][w][e]

[msg MSG_Start_Common_Makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2034 65535 0]Estoy lista. Empecemos.[n][f 1 3 65535][w][e]

[msg MSG_Start_Common_Futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9003 65535 0]Parece que hemos llegado todos.[n]斡Dejadme a m胤 el apoyo![n][f 1 3 65535][w][e]

[msg MSG_Start_Common_Haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0]斡Que emocionante estar aqu胤 con[n]todos! Bien, 斡lo har姻 lo mejor[n]que pueda![n][f 1 3 65535][w][e]

[msg MSG_Start_Common_Akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54440 65535 0]夷Comenzamos? C茨lmate y mant姻n el[n]pulso firme al apuntar,[n]夷de acuerdo?[n][f 1 3 65535][w][e]

[msg MSG_Start_Common_Akechi_ [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54502 65535 0]Venga, comencemos.[n][f 1 3 65535][w][e]

[msg MSG_Start_Common_Yoshiza [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0]Esto es estresante, 夷verdad? 斡Pero conf胤o[n]en mi capacidad de concentraci吋n![n][f 1 3 65535][w][e]

[msg MSG_PreBreak_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7024 65535 0]Esta intensidad justo[n]antes de empezar...[n]斡Me encanta![n][f 1 3 65535][w][e]

[msg MSG_PreBreak_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1156 65535 0]夷Vas a arriesgarte o no?[n]Medita bien qu姻 decisi吋n tomar.[n][f 1 3 65535][w][e]

[msg MSG_PreBreak_Anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6019 65535 0]La postura es importante, 夷eh?[n]Si no ejecutas un tiro limpio,[n]la bola saldr茨 disparada.[n][f 1 3 65535][w][e]

[msg MSG_PreBreak_Yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4134 65535 0]Mmm. Qu姻 postura tan especial.[n]斡Es pura belleza![n][f 1 3 65535][w][e]

[msg MSG_PreBreak_Makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2105 65535 0]Estabilizar la forma, luego[n]apuntar...[n]Aqu胤 hay mucho que aprender.[n][f 1 3 65535][w][e]

[msg MSG_PreBreak_Futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9142 65535 0]斡Qu姻 agradable es el ruido[n]que hacen las bolas al esparcirse![n][f 1 3 65535][w][e]

[msg MSG_PreBreak_Haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53541 65535 0]El nerviosismo te llevar茨 al fracaso.[n]Venga, c茨lmate...[n][f 1 3 65535][w][e]

[msg MSG_PreBreak_Akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]夷Vemos de lo que eres capaz?[n][f 1 3 65535][w][e]

[msg MSG_PreBreak_Akechi_Blac [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54475 65535 0]S胤, no lo haces mal del todo...[n][f 1 3 65535][w][e]

[msg MSG_PreBreak_Yoshizawa [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57037 65535 0]Si te centras en la posici吋n de los[n]dedos, no adoptar茨s una buena[n]postura. 斡El equilibrio es vital![n][f 1 3 65535][w][e]

[msg MSG_ShotGood_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54247 65535 0]斡Hala! 斡Bien![n][f 1 3 65535][w][e]

[msg MSG_ShotGood_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Vaya! 斡Como los profesionales![n][f 1 3 65535][w][e]

[msg MSG_ShotGood_Anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54047 65535 0]斡Vaya! 斡Qu姻 profesional![n][f 1 3 65535][w][e]

[msg MSG_ShotGood_Yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53741 65535 0]斡Es fascinante![n][f 1 3 65535][w][e]

[msg MSG_ShotGood_Makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53340 65535 0]Vaya... No pod胤a apartar la mirada.[n][f 1 3 65535][w][e]

[msg MSG_ShotGood_Futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54742 65535 0]斡Lo lograste! 斡Menudo chulito![n][f 1 3 65535][w][e]

[msg MSG_ShotGood_Haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53544 65535 0]Vaya, 斡ha sido incre胤ble![n]斡Parec胤a magia![n][f 1 3 65535][w][e]

[msg MSG_ShotGood_Akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54470 65535 0]Oye, no est茨 mal.[n]Incluso yo dir胤a que casi perfecto.[n][f 1 3 65535][w][e]

[msg MSG_ShotGood_Akechi_Blac [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54500 65535 0]Ha sido un buen tiro.[n][f 1 3 65535][w][e]

[msg MSG_ShotGood_Yoshizawa [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57167 65535 0]Ha sido incre胤ble.[n]斡Estoy pasmada...![n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54238 65535 0]Vaya, eh, no te martirices.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷E-est茨s bien?[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Anne [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 54048 65535 0]夷Est茨s bien?[n]No dejes que te afecte.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53742 65535 0]No temas. Lo que importa[n]es la pasi吋n.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Makoto [Makoto]]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 53341 65535 0]Sab胤a lo que ibas a hacer.[n]斡A la pr吋xima, hazlo bien![n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54743 65535 0]Si te lo piensas mucho,[n]puedes ir aceptando la derrota.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53545 65535 0]No te sientas mal. Ya sabes lo que[n]dicen: el fracaso es la madre del[n]姻xito.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54471 65535 0]Qu姻 l茨stima. Esto es lo que pasa[n]cuando uno se piensa las cosas.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Akechi_Black [Akechi]]
[s][bup 0 9 14 65535 0][f 4 10 65535 0 0][vp 8 2 0 54473 65535 0]Eso no ha sido aposta, 夷verdad?[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Yoshizawa [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57168 65535 0]No te preocupes. 斡Todo el mundo[n]aprende de sus fracasos![n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Ryuji_JumpMi [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]斡Ha faltado poco! Buenos reflejos.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_moru_JumpMis [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷E-est茨s bien?[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Anne_JumpMis [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6028 65535 0]斡Qu姻 poco ha faltado![n]Pensaba que te hab胤a dado.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Yusuke_JumpM [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4017 65535 0]Menos mal que no te ha dado.[n]Aunque debo decir que ha sido una[n]pelea genial.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Makoto_JumpM [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 2028 65535 0]斡夷C吋mo has esquivado eso?![n]Oh, ahora no es el momento de[n]quedarme impresionada...[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Futaba_JumpM [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 54741 65535 0]斡Me alegro de que est姻s bien![n]Ha sido una evasi吋n perfecta.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Haru_JumpMis [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 3028 65535 0]Qu姻 alivio.[n]Menos mal que no te ha dado.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Akechi_JumpM [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]Es importante concentrarse, 夷sabes?[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Akechi_Black_2 [Akechi]]
[s][bup 0 9 14 65535 0][f 4 10 65535 0 0][vp 8 2 0 54502 65535 0]Intenta concentrarte m茨s.[n][f 1 3 65535][w][e]

[msg MSG_ShotBad_Yoshizawa_Ju [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57046 65535 0]Q-qu姻 buen regate. Me alegra[n]que no te haya dado.[n][f 1 3 65535][w][e]

[msg MSG_PlayEnd_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]斡Vaya, ha sido divertido![n]Tengo los brazos hechos polvo.[n][f 1 3 65535][w][e]

[msg MSG_PlayEnd_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]斡Ganar no es lo importante![n]斡Lo divertido es meter las bolas![n][f 1 3 65535][w][e]

[msg MSG_PlayEnd_Anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54049 65535 0]斡Ganar no es lo importante![n]斡Lo divertido es meter las bolas![n][f 1 3 65535][w][e]

[msg MSG_PlayEnd_Yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4107 65535 0]El ruido que hacen las bolas al[n]rodar y entrar en las troneras[n]es muy agradable.[n][f 1 3 65535][w][e]

[msg MSG_PlayEnd_Makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2164 65535 0]No pasa siempre, pero mola[n]que las bolas vayan justo[n]donde quieras.[n][f 1 3 65535][w][e]

[msg MSG_PlayEnd_Futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9105 65535 0]斡Buen trabajo! 斡Tengo las manos[n]pringando de sudor![n][f 1 3 65535][w][e]

[msg MSG_PlayEnd_Haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3114 65535 0]Solo con ver las bolas rodando[n]suavemente por la mesa,[n]ya me lo he pasado bien.[n][f 1 3 65535][w][e]

[msg MSG_PlayEnd_Akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54465 65535 0]No est茨 mal jugar al billar con un[n]grupo grande. As胤 la presi吋n est茨[n]m茨s repartida.[n][f 1 3 65535][w][e]

[msg MSG_PlayEnd_Akechi_Black [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54501 65535 0]No ha estado mal para entretenerse...[n]Es broma, es broma.[n][f 1 3 65535][w][e]

[msg MSG_PlayEnd_Yoshizawa [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57119 65535 0]斡Es muy interesante ver c吋mo[n]la indecisi吋n se refleja[n]en el movimiento de las bolas![n][f 1 3 65535][w][e]

[msg MSG_Happy_Ryuji [Ryuji]]
[s][f 5 13 3 2 6][f 5 13 4 2 7][f 5 13 5 2 5][f 5 13 7 2 4][f 5 13 8 2 2][f 5 13 10 2 8][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54242 65535 0]斡Ha sido genial! Hay que repetir.[n][f 1 3 65535][w][e]

[msg MSG_Happy_Anne [Ann]]
[s][f 5 13 3 2 6][f 5 13 4 2 7][f 5 13 5 2 5][f 5 13 7 2 4][f 5 13 8 2 2][f 5 13 10 2 8][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54042 65535 0]斡Qu姻 bien me lo he pasado![n]Tienes que volver a invitarme.[n][f 1 3 65535][w][e]

[msg MSG_Happy_Yusuke [Yusuke]]
[s][f 5 13 3 2 6][f 5 13 4 2 7][f 5 13 5 2 5][f 5 13 7 2 4][f 5 13 8 2 2][f 5 13 10 2 8][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53736 65535 0]Mira cu茨nto tiempo ha pasado...[n]y lo satisfactorio que ha sido.[n][f 1 3 65535][w][e]

[msg MSG_Happy_Makoto [Makoto]]
[s][f 5 13 3 2 6][f 5 13 4 2 7][f 5 13 5 2 5][f 5 13 7 2 4][f 5 13 8 2 2][f 5 13 10 2 8][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53342 65535 0]Qu姻 divertido.[n]Inv胤tame a la pr吋xima.[n][f 1 3 65535][w][e]

[msg MSG_Happy_Futaba [Futaba]]
[s][f 5 13 3 2 6][f 5 13 4 2 7][f 5 13 5 2 5][f 5 13 7 2 4][f 5 13 8 2 2][f 5 13 10 2 8][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54737 65535 0]Cu茨ntas emociones... 斡Me gusta![n]斡Av胤same para la pr吋xima![n][f 1 3 65535][w][e]

[msg MSG_Happy_Haru [Haru]]
[s][f 5 13 3 2 6][f 5 13 4 2 7][f 5 13 5 2 5][f 5 13 7 2 4][f 5 13 8 2 2][f 5 13 10 2 8][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53539 65535 0]斡Qu姻 divertido![n]Inv胤tame la pr吋xima vez.[n][f 1 3 65535][w][e]

[msg MSG_Happy_Akechi [Akechi]]
[s][f 5 13 3 2 6][f 5 13 4 2 7][f 5 13 5 2 5][f 5 13 7 2 4][f 5 13 8 2 2][f 5 13 10 2 8][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54465 65535 0]Ha sido una buena diversi吋n.[n]Gracias por invitarme.[n][f 1 3 65535][w][e]

[msg MSG_Happy_Akechi_Black [Akechi]]
[s][f 5 13 3 2 6][f 5 13 4 2 7][f 5 13 5 2 5][f 5 13 7 2 4][f 5 13 8 2 2][f 5 13 10 2 8][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54502 65535 0]El billar es un juego estupendo.[n]夷A que ha sido emocionante?[n][f 1 3 65535][w][e]

[msg MSG_Happy_Yoshizawa [Sumire]]
[s][f 5 13 3 2 6][f 5 13 4 2 7][f 5 13 5 2 5][f 5 13 7 2 4][f 5 13 8 2 2][f 5 13 10 2 8][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57162 65535 0]斡Me lo he pasado muy bien![n]斡Tienes que invitarme otro d胤a![n][f 1 3 65535][w][e]

[msg MSG_BillBye_Ryuji [Ryuji]]
[s][vp 8 2 0 7062 65535 0]Venga, hasta otra.[n][f 1 3 65535][w][e]

[msg MSG_BillBye_Moru [Morgana]]
[s][vp 8 2 0 1049 65535 0]Hora de volver a casa.[n][f 1 3 65535][w][e]

[msg MSG_BillBye_Anne [Ann]]
[s][vp 8 2 0 6053 65535 0]斡Hasta luego![n][f 1 3 65535][w][e]

[msg MSG_BillBye_Yusuke [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Hasta la pr吋xima.[n][f 1 3 65535][w][e]

[msg MSG_BillBye_Makoto [Makoto]]
[s][vp 8 2 0 2053 65535 0]Bueno, hasta luego.[n][f 1 3 65535][w][e]

[msg MSG_BillBye_Futaba [Futaba]]
[s][vp 8 2 0 9012 65535 0]斡Hora de darme el piro![n][f 1 3 65535][w][e]

[msg MSG_BillBye_Haru [Haru]]
[s][vp 8 2 0 3054 65535 0]Vale, nos vemos.[n][f 1 3 65535][w][e]

[msg MSG_BillBye_Akechi [Akechi]]
[s][vp 8 2 0 8053 65535 0]Hasta luego.[n][f 1 3 65535][w][e]

[msg MSG_BillBye_Akechi_Black [Akechi]]
[s][vp 8 2 0 54504 65535 0]Volvamos.[n][f 1 3 65535][w][e]

[msg MSG_BillBye_Yoshizawa [Sumire]]
[s][vp 8 2 0 57175 65535 0]斡Hasta la pr吋xima![n][f 1 3 65535][w][e]

[msg MND_SpecialShot_Thinking]
[s][vp 8 2 0 0 65535 0]Por el modo en que est茨n[n]posicionadas las bolas...[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]斡Tendr姻 que hacer un tiro dif胤cil[n]para superar esto![n][f 1 3 65535][w][e]

[msg MSG_TechRankUp_Info [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53140 65535 0]斡Vaya pedazo de tiro![n]斡Por algo eres el l胤der![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Parece que tu desaf胤o[n]ha unido a todo el mundo.[n][f 1 3 65535][w][e]

[msg MSG_TechRankUp_Miss [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1112 65535 0]La has liado con el tiro con truco,[n]pero no te desanimes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]S胤... Seguro que ir胤a mejor[n]si tuvieras m茨s [f 4 11 2][clr 26][f 4 12 2][clr 27].[n][f 1 3 65535][w][e]

[msg SYS_NeedParamRank_Back]
[s]Un [clr 2]tiro por la espalda[clr 27][n]con 姻xito requiere suficiente[n][f 4 11 2][clr 26][f 4 12 2][clr 27] para ser [clr 2][f 4 13 2 2][clr 27].[n][w][e]

[msg SYS_NeedParamRank_Jump]
[s]Un [clr 2]tiro con salto[clr 27][n]con 姻xito requiere suficiente[n][f 4 11 2][clr 26][f 4 12 2][clr 27] para ser [clr 2][f 4 13 2 3][clr 27].[n][w][e]

[msg SYS_NeedParamRank_Masse]
[s]Un [clr 2]tiro mass姻[clr 27][n]con 姻xito requiere suficiente[n][f 4 11 2][clr 26][f 4 12 2][clr 27]para ser [clr 2][f 4 13 2 5][clr 27].[n][w][e]

[msg MSG_HumanParam_PreInfo [Morgana]]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Me alegro de que disfrutarais,[n]pero que conste que...[n][f 1 3 65535][w][e]

[msg MSG_HumanParam_Atama [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1168 65535 0][f 4 22 65535 1 41]Por jugar al billar,[n]parece que se te da mejor[n]analizar situaciones.[n][f 1 3 65535][w][e]

[msg MSG_HumanParam_Miryoku [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1168 65535 0][f 4 22 65535 1 41]Por jugar al billar, sabes[n]presentarte con un poco m茨s[n]de atractivo, 夷a que s胤?[n][f 1 3 65535][w][e]

[msg MSG_HumanParam_Kiyousa [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1168 65535 0][f 4 22 65535 1 41]Por jugar al billar, has ganado[n]experiencia en realizar[n]movimientos precisos con las manos.[n][f 1 3 65535][w][e]

[msg MSG_HumanParam_Dokyo [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1168 65535 0][f 4 22 65535 1 41]Por jugar al billar, has aprendido[n]mucho sobre tomar decisiones[n]dr茨sticas cuando corresponde.[n][f 1 3 65535][w][e]

[msg MSG_TenchoInfo_1st_000 [Joven informal]]
[s][vp 8 2 0 0 65535 0]Oye, perdona por cortarte[n]el rollo.[n][f 1 3 65535][w][e]

[msg MSG_TenchoInfo_1st_001 [Joven informal]]
[s][vp 8 2 0 0 65535 0]El billar tiene mucho intr胤ngulis,[n]夷verdad? Me alegro de que te hayas[n]aficionado.[n][f 1 3 65535][w][e]

[msg MSG_TenchoInfo_1st_002 [Joven informal]]
[s][vp 8 2 0 0 65535 0]Si quieres saber m茨s, te puedo[n]recomendar un libro sobre el tema.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Se llama [clr 3][var 0][clr 27].[n]Abarca desde lo m茨s b茨sico[n]hasta las aplicaciones pr茨cticas.[n][f 1 3 65535][w][e]

[msg MSG_TenchoInfo_1st_003 [Joven informal]]
[s][vp 8 2 0 0 65535 0]Lo malo es que es bastante raro.[n]Puede ser dif胤cil encontrarlo.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Ser茨 m茨s f茨cil conseguirlo en una[n][clr 2]tienda especializada[clr 27] en productos[n]deportivos que en una librer胤a.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Si ya te vas, no te entretengo m茨s.[n]Vuelve cuando quieras.[n][f 1 3 65535][w][e]

[msg MSG_TenchoInfo_1st_010 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1133 65535 0]Un libro de billar... Deber胤amos ir[n]a una tienda de deportes a ver si[n]lo tienen cuando tengamos un rato.[n][f 1 3 65535][w][e]

[msg MSG_TenchoInfo_2nd_000 [Joven informal]]
[s][vp 8 2 0 0 65535 0]Oye, perdona por cortarte[n]el rollo.[n][f 1 3 65535][w][e]

[msg MSG_TenchoInfo_2nd_001 [Joven informal]]
[s][vp 8 2 0 0 65535 0]Parece que est茨s intentando[n]aprender los tiros t姻cnicos.[n][f 1 3 65535][w][e]

[msg MSG_TenchoInfo_2nd_002 [Joven informal]]
[s][vp 8 2 0 0 65535 0]A ver, yo creo que podr胤as marcarte[n]un buen tiro avanzado.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Se llama 或tiro mass姻位. Consigue[n]que la bola haga una curva... Uy.[n][f 1 3 65535][w][e]

[msg MSG_TenchoInfo_2nd_003 [Joven informal]]
[s][vp 8 2 0 0 65535 0]No tiene sentido[n]que lo explique ahora.[n][f 1 3 65535][w][e]
[s][vp 8 2 0 0 65535 0]Toma este libro.[n]Creo que lo encontrar茨s muy 雨til.[n][f 1 3 65535][w][e]

[msg MSG_TenchoInfo_2nd_010 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Tiros mass姻s, 夷eh? Si conf胤as en tu[n][f 4 11 2][clr 26][f 4 12 2][clr 27], tal vez[n]deber胤as probarlo la pr吋xima vez.[n][f 1 3 65535][w][e]

[msg MSG_ShotType_Back_000 [Morgana]]
[s][bup 0 3 8 65535 0][f 4 10 65535 0 0][vp 8 2 0 1130 65535 0]斡Hala! 斡夷Vas a intentar ese tiro?![n][f 1 3 65535][w][e]

[msg MSG_ShotType_Jump_000 [Morgana]]
[s][bup 0 3 8 65535 0][f 4 10 65535 0 0][vp 8 2 0 1130 65535 0]Ese taco...[n]斡夷Vas a intentar ese tiro?![n][f 1 3 65535][w][e]

[msg MSG_ShotType_Masse_000 [Morgana]]
[s][bup 0 3 8 65535 0][f 4 10 65535 0 0][vp 8 2 0 1130 65535 0]Esa madera... 斡夷Vas a intentar[n]ese tiro?![n][f 1 3 65535][w][e]

[msg MSG_BackEnd_MyQueIsHave [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1165 65535 0]夷No te hab胤as comprado t雨 un taco?[n]Parece que hoy no lo has usado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]A ver, uno no se hace experto[n]en un d胤a. Ya jugaremos[n]en otro momento.[n][f 1 3 65535][w][e]

[msg MSG_BackEnd_MyQueIsNotHa [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53101 65535 0]Ah, s胤, el libro de billar[n]conten胤a informaci吋n sobre otros tiros[n]con truco, 夷verdad?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Para uno se necesitaba[n]un taco especial, 夷no? A ver[n]si tenemos tiempo y lo buscamos.[n][f 1 3 65535][w][e]

[msg MND_chr_haiti]
[s][vp 8 2 0 0 65535 0]誰まで仲間にする?[n][f 1 3 65535][w][e]

[sel SEL_chr_haiti_dbg top]
[s]祐介まで[e]
[s]真まで[e]
[s]双葉まで[e]
[s]春まで[e]
[s]明智まで[e]
[s]すみれまで[e]
[s]今の状態で開始する[e]

[msg MSG_TEST_FAULT]
[s]ミニゲームに「失敗」した[n][f 1 3 65535][w][e]

[msg MSG_TEST_SUCCESS]
[s]ミニゲームに「成功」した[n][f 1 3 65535][w][e]

[msg MSG_TEST_SUCCESS_SUPER]
[s]ミニゲームに「大成功」した[n][f 1 3 65535][w][e]

[msg MSG_TEST_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]コースと結果を強制変更する[n]デバッグ処理です。[n][f 1 3 65535][w][e]

[sel MSG_TEST_02 top]
[s]ジャンプ 大成功[e]
[s]ジャンプ 成功[e]
[s]ジャンプ 失敗[e]
[s]バック 大成功[e]
[s]バック 成功[e]
[s]バック 失敗[e]
[s]マッセ 大成功[e]
[s]マッセ 成功[e]
[s]マッセ 失敗[e]

[sel DBG_ShotProgress top]
[s]トリックショットを知らない[e]
[s]バックハンドを知っている:失敗[e]
[s]バックハンドを知っている:成功[e]
[s]ジャンプショットを知らない[e]
[s]ジャンプショットを知っている:失敗[e]
[s]ジャンプショットを知っている:成功[e]
[s]マッセを知らない[e]
[s]マッセを知っている:失敗[e]
[s]マッセを知っている:成功[e]
[s]すべてクリアした後[e]

