[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Qu姻 aburrimiento de clase.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Eh, te vibra el m吋vil.[n][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Una invitaci吋n para ir[n]a alg雨n sitio despu姻s de clase?[n]Veamos...[n][w][e]

[msg MSG_003_0_0 [Profesora Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷[f 4 1]? No se permiten[n]tel姻fonos m吋viles en clase.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷[f 4 1]? *tos* Mmm...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I-intenta no usarlo mucho, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Profesora Chouno]]
[s][bup 0 304 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por cierto, [f 4 2].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Te agradecer胤a que no jugases[n]con el m吋vil en clase.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Profesor Inui]]
[s][bup 0 302 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Oye, [f 4 1]![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Que est茨s en clase![n]斡Deja el m吋vil quietecito![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Profesora Usami]]
[s][bup 0 305 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Te estoy viendo, [f 4 1].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Deja de usar el m吋vil en clase.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Profesor Taihei]]
[s][bup 0 301 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Oye, [f 4 1]![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]斡Que est茨s en clase![n]斡Deja el m吋vil quietecito![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Profesor Hiruta]]
[s][bup 0 303 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oye, [f 4 1].[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Atiende en lugar de jugar[n]con el m吋vil.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nos han pillado.[n][w][e]
[s]Quiz茨 sea mejor atender[n]y ya lo mirar茨s despu姻s de clase.[n][w][e]

