[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e805_062[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Ann parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 7 10 4][vp 8 0 0 0 65535 0]Dir胤a que siente curiosidad[n]por una tienda en concreto.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Ann[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]夷Volvemos a casa?[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e805_062[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Ann parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 7 10 4][vp 8 0 0 0 65535 0]Dir胤a que siente curiosidad[n]por una tienda en concreto.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Ann[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]夷Volvemos a casa?[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e805_062[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Ann parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 7 10 4][vp 8 0 0 0 65535 0]Dir胤a que siente curiosidad[n]por una tienda en concreto.[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Ann[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]夷Volvemos a casa?[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e805_062[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Ann parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 7 10 4][vp 8 0 0 0 65535 0]Dir胤a que siente curiosidad[n]por una tienda en concreto.[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Ann[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]夷Volvemos a casa?[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e805_062[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Ann parece emocionada.[n][f 1 3 65535][w][e]
[s][f 5 13 7 10 4][vp 8 0 0 0 65535 0]Dir胤a que siente curiosidad[n]por una tienda en concreto.[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Ann[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]夷Volvemos a casa?[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e805_062[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Ann parece emocionada.[n][f 1 3 65535][w][e]
[s][f 5 13 7 10 4][vp 8 0 0 0 65535 0]Dir胤a que siente curiosidad[n]por una tienda en concreto.[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Ann[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]夷Volvemos a casa?[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e805_062[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Ann est茨 buscando todo[n]tipo de productos de belleza.[n][f 1 3 65535][w][e]
[s][f 5 13 7 10 4][vp 8 0 0 0 65535 0]Ir姻 a comprar con ella un rato.[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Ann[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]夷Volvemos a casa?[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e805_062[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Ann est茨 buscando todo[n]tipo de productos de belleza.[n][f 1 3 65535][w][e]
[s][f 5 13 7 10 4][vp 8 0 0 0 65535 0]Ir姻 a comprar con ella un rato.[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Ann[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]夷Volvemos a casa?[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e805_062[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Ann est茨 buscando todo[n]tipo de productos de belleza.[n][f 1 3 65535][w][e]
[s][f 5 13 7 10 4][vp 8 0 0 0 65535 0]Ir姻 a comprar con ella un rato.[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Ann[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]夷Volvemos a casa?[n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e805_062[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]Parece que Ann se est茨 divirtiendo.[n][f 1 3 65535][w][e]
[s][f 5 13 7 10 4][vp 8 0 0 0 65535 0]Iremos a echar un vistazo[n]a todas las tiendas.[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Ann[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]Gracias por haber venido conmigo.[n]夷Volvemos a casa?[n][f 1 3 65535][w][e]

