[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3028 65535 0]Mmm, 斡qu姻 bien huele![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Los santuarios desprenden un aroma[n]de lo m茨s misterioso, 夷no crees?[n]夷Ser茨 por los 茨rboles?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 0 8 2 1 2217]夷Qu姻 clase de aroma?[clr 27][e]
[s][f 0 8 2 1 2217]Sin duda.[clr 27][e]
[s]La atm吋sfera es distinta.[e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3111 65535 0][f 5 13 4 10 7]Mmm... Es como si estuviera[n]atravesando un mar[n]de energ胤a condensada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cuando vengo a estos lugares,[n]pienso que tener una boda sinto胤sta[n]no estar胤a nada mal.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3035 65535 0][f 5 13 4 10 7]斡S胤! 夷No te parece[n]algo fuera de lo com雨n?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Entiendo perfectamente[n]que haya gente que quiera[n]casarse en un sitio como este.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3192 65535 0][f 5 13 4 5 7]夷Qu姻 ser茨?[n]Hace que me ponga tensa,[n]pero no en un sentido negativo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es verdad. Una vez, vi que aqu胤 se[n]celebraba una boda... Fue una[n]experiencia de lo m茨s especial.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por cierto, todos creceremos[n]y nos casaremos alg雨n d胤a, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Creo que me gustar胤a celebrar[n]mi boda aqu胤. Invitar姻 al resto[n]de los Ladrones Fantasma.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]A fin de cuentas,[n]si vuelvo a tener una vida...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]es gracias a todos vosotros.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0]夷Te apetece pasear un poco m茨s?[n]斡Me encanta explorar lugares[n]llenos de energ胤a![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][vp 8 2 0 3049 65535 0]En fin, volvamos a casa.[n][f 1 3 65535][w][e]

