[msg MSG_000_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3193 65535 0]Mmm... 夷No se te derrite en la boca?[n]He o胤do que aqu胤 usan un m姻todo[n]de preparaci吋n especial.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es una obra maestra que te puede[n]cambiar la vida. Bueno... puede[n]que ah胤 me haya pasado un poco.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]夷Vienes aqu胤 a menudo?[clr 27][e]
[s]S胤 que tienes dinero.[e]
[s][f 0 8 2 1 2217]Quiero repetir.[clr 27][e]

[msg MSG_002_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3194 65535 0][f 5 13 4 10 7]S胤, en ocasiones... aunque suelo[n]estar en una sala privada.[n]Nunca hab胤a estado en barra.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ver al chef preparando la comida[n]delante de ti es poes胤a[n]en movimiento.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 3182 65535 0][f 5 13 4 5 7]Qu姻 exagerado. Ni que fuera[n]un restaurante exclusivo.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Aunque s胤 que hay varias salas[n]solo para vips.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]He o胤do que una vez vino[n]un presidente extranjero[n]en secreto con su esposa.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3111 65535 0][f 5 13 4 10 7]Yo tambi姻n, pero est茨 limitado[n]a un plato por cliente.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As胤 pueden ofrecer el mejor sushi[n]a tantos clientes como sea posible.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mmm... 夷Qu姻 te apetece ahora?[n]Decidir qu姻 pedir en un restaurante[n]de sushi es todo un dilema.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya s姻. Pedir lo que te apetece[n]est茨 bien, pero 夷qu姻 te parece si[n]hoy le dejamos la elecci吋n al chef?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0]斡Qu姻 buen saque![n]He disfrutado vi姻ndote comer.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El sushi estaba igual de bueno[n]que siempre, pero esta vez ten胤a[n]algo especial.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Puede que la compa隠胤a sea m茨s[n]importante que lo que comes.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3019 65535 0][f 4 2], 夷podemos venir[n]aqu胤 m茨s veces?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Haru]]
[s][vp 8 2 0 3060 65535 0]Gracias por lo de hoy.[n][f 1 3 65535][w][e]

