[msg MSG_000_0_0 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 9162 65535 0]Hala, toda esa gente de ah胤 abajo[n]parece granos de arena.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Casi me rindo de camino hasta[n]aqu胤 por las aglomeraciones.[n][f 1 3 65535][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero 斡estas vistas son incre胤bles![n]斡Es como si fuera una diosa[n]contemplando a sus s雨bditos![n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Me alegro de que te guste.[e]
[s]夷Y las aglomeraciones de despu姻s?[e]
[s]夷De verdad eres una deidad?[e]

[sel SEL_001_5_0 top]
[s][f 0 8 2 1 2217]Me alegro de que te guste.[clr 27][e]
[s]夷Y las aglomeraciones de despu姻s?[e]
[s]夷De verdad eres una deidad?[e]

[msg MSG_002_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9076 65535 0][f 5 13 10 15 8]Mua, ja, ja, ja, 斡me siento gigante![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Ahora mismo, la maestra[n]Futaba puede aplastar hasta[n]la vida extraterrestre![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 9047 65535 0][f 5 13 10 5 8]Seguramente est姻 jodida.[n][f 1 3 65535][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero voy a esforzarme.[n]斡Y me voy a enfadar mucho[n]si me abandonas, [f 4 2]![n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 9199 65535 0][f 5 13 10 10 8]As胤 que lo has averiguado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Si as胤 vas a estar callado, creo[n]que puedo darte el privilegio[n]de seguir saliendo conmigo.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Hala! 斡Mira los trenes![n][f 1 3 65535][w][e]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La ciudad entera parece[n]una maqueta, pero hay gente[n]ah胤 viviendo como si nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El paisaje parece muy diferente[n]cuando se mira as胤.[n]夷Por qu姻 ser茨?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9200 65535 0]Ahora que lo pienso, 夷d吋nde est茨[n]el Leblanc? Aunque viva en Tokio,[n]no tengo ni idea.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]D胤melo t雨, [f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][vp 8 2 0 9049 65535 0]Ay, vamos a casa.[n][f 1 3 65535][w][e]

