[msg MSG_000_0_0 [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 9105 65535 0]斡Estoy en el para胤so![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me gustar胤a vivir aqu胤, la verdad.[n]Uf, cuant胤sima gente hay.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero... 斡me hace much胤sima ilusi吋n![n]斡Verlo en persona[n]no es lo mismo que por internet![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Vamos a ver el port茨til ultrafino[n]del que tanto hablan![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Fino era, pero aun as胤[n]me ha decepcionado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Dicen que tiene[n]un mont吋n de funciones,[n]pero yo no las veo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, ya da igual.[n]夷Entiendes c吋mo me siento?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]夷No tienes ya un ordenador?[e]
[s]Qu姻 mal.[e]
[s][f 0 8 2 1 2217]Sientes un desega隠o...[clr 27][e]

[msg MSG_003_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 9189 65535 0][f 5 13 10 10 8]Hablas como Sojiro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tampoco iba a comprarlo.[n]Solo quer胤a entusiasmarme[n]con el futuro de la electr吋nica.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 9176 65535 0][f 5 13 10 10 8]Lo has entendido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Se han cargado[n]lo que yo esperaba[n]del avance de la electr吋nica.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9132 65535 0][f 5 13 10 15 8]斡Eso es! 斡Me han defraudado![n][f 1 3 65535][w][e]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][vp 8 0 0 0 65535 0]Ten胤a grandes expectativas[n]sobre c吋mo iba a avanzar[n]la electr吋nica...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero lo 雨nico que he visto[n]ha sido un bloque de metal vac胤o.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][bup 0 8 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, de nada sirve venirse abajo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Tiene que haber[n]m茨s tesoros escondidos[n]en este para胤so de la electr吋nica![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Vamos a explorar, [f 4 2]![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Empecemos por la planta m茨s baja![n]斡A las escaleras mec茨nicaaas![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9076 65535 0]斡C吋mo mola![n]斡Da igual cu茨ntas veces lo mire![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Aunque yo ya tengo tres,[n]as胤 que qu姻datelo,[n][f 4 2]. 斡Es un regalo![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][vp 8 2 0 9043 65535 0]No quiero irme a casa.[n]D姻jame seguir en el para胤so.[n][f 1 3 65535][w][e]

