[msg MSG_000_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 18048 65535 0]S胤... Siento que aqu胤 puedo jugar[n]al shogi a otro ritmo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Las vistas, los sonidos,[n]los aromas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Puedo utilizar los cinco sentidos.[n]A lo mejor hasta[n]se me ocurren ideas nuevas.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Me alegro.[e]
[s][f 0 8 2 1 2217]Es un buen estimulante, 夷no?[clr 27][e]
[s]夷Usas los sentidos en el shogi?[e]

[msg MSG_002_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 18123 65535 0][f 5 13 18 10 1006]Las alteraciones de la sensibilidad[n]provocan cambios en las decisiones.[n]As胤 se mejora.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 18130 65535 0][f 5 13 18 15 1006]S胤, despierta una sensibilidad[n]diferente. Ayuda a dar con[n]nuevos movimientos.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 18123 65535 0][f 5 13 18 10 1006]Correcto. El shogi no consiste solo[n]en usar la cabeza.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Hay que valerse de los sentidos[n]para identificar las posibilidades[n]y los mejores movimientos.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Hifumi]]
[s][bup 0 106 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Con el shogi me he abierto[n]a nuevas oportunidades.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Una persona es como una pieza[n]con infinidad de movimientos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Y qu姻 llegar茨s a ser t雨?[n]Disfruto imaginando[n]todas las posibilidades.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*risita* Empiezo a sentir[n]que pronto dar姻[n]con un nuevo movimiento.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 18096 65535 0]Ahora que ya me siento mejor,[n]斡a jugar, as胤 de claro![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Hifumi]]
[s][vp 8 2 0 18097 65535 0]Vamos a dejarlo ya.[n][f 1 3 65535][w][e]

