[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e821_042[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece animado.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Este lugar estimula[n]su vena art胤stica.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Yusuke[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Mmm, parece que tendr姻 que[n]ponerme las pilas. Hasta m茨s ver.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e821_042[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece animado.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Este lugar estimula[n]su vena art胤stica.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Yusuke[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Mmm, parece que tendr姻 que[n]ponerme las pilas. Hasta m茨s ver.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e821_042[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece animado.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Este lugar estimula[n]su vena art胤stica.[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Yusuke[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Mmm, parece que tendr姻 que[n]ponerme las pilas. Hasta m茨s ver.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e821_042[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece animado.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Este lugar estimula[n]su vena art胤stica.[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Yusuke[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Mmm, parece que tendr姻 que[n]ponerme las pilas. Hasta m茨s ver.[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e821_042[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece animado.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Este lugar estimula[n]su vena art胤stica.[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Yusuke[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Mmm, parece que tendr姻 que[n]ponerme las pilas. Hasta m茨s ver.[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e821_042[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece algo inquieto.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Este lugar estimula[n]su vena art胤stica.[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Yusuke[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Mmm, parece que tendr姻 que[n]ponerme las pilas. Hasta m茨s ver.[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e821_042[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece algo inquieto.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Este lugar estimula[n]su vena art胤stica.[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Yusuke[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Mmm, parece que tendr姻 que[n]ponerme las pilas. Hasta m茨s ver.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e821_042[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece animado.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Este lugar estimula[n]su vena art胤stica.[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Yusuke[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Mmm, parece que tendr姻 que[n]ponerme las pilas. Hasta m茨s ver.[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e821_042[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece animado.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Este lugar estimula[n]su vena art胤stica.[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Yusuke[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Mmm, parece que tendr姻 que[n]ponerme las pilas. Hasta m茨s ver.[n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco e821_042[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]Yusuke parece animado.[n][f 1 3 65535][w][e]
[s][f 5 13 5 10 5][vp 8 0 0 0 65535 0]Este lugar estimula[n]su vena art胤stica.[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Yusuke[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Mmm, esto solo demuestra cu茨nta[n]experiencia me falta. Tendr姻 que[n]ponerme las pilas. Hasta m茨s ver.[n][f 1 3 65535][w][e]

