[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6058 65535 0]夷Sabes? Venir a un museo[n]me recuerda a cuando[n]nos enfrent茨bamos a Madarame.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La verdad, ahora que lo pienso,[n]me sorprende estar yendo[n]a un sitio sola contigo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero 斡no lo digo como[n]algo malo! No, al rev姻s.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷Qu姻 quieres decir?[e]
[s]夷Tan sorprendente es?[e]
[s][f 0 8 2 1 2217]Han cambiado muchas cosas.[clr 27][e]

[msg MSG_002_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6127 65535 0][f 5 13 7 5 4]Bueno... la primera impresi吋n que[n]tuvimos el uno del otro fue[n]p姻sima, 夷verdad?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cuando nos conocimos, nunca pens姻[n]que alg雨n d胤a ser胤a capaz[n]de confiar plenamente en ti.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6034 65535 0][f 5 13 7 5 4]Cuando nos conocimos, nunca pens姻[n]que alg雨n d胤a ser胤a capaz[n]de confiar plenamente en ti.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya creo que no pasa nada[n]si te lo digo... Al principio[n]pensaba que eras un baboso.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6048 65535 0][f 5 13 7 15 4]S胤, ahora me sorprende[n]pensar en todo eso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cuando nos conocimos, nunca pens姻[n]que alg雨n d胤a ser胤a capaz[n]de confiar plenamente en ti.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 6058 65535 0]Supongo que es imposible[n]saber lo que te depara la vida.[n][f 1 3 65535][w][e]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 42 5 100][f 4 24 0 4 0 1 5 0]斡En fin! Me alegro mucho[n]de que hayamos venido hoy aqu胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ver las expresiones y poses[n]del arte ha sido superinformativo.[n]斡Quiz茨 hasta me ayude como modelo![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bueno, espero que podamos volver[n]juntos cuando tengas tiempo.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Aunque no crees que[n]las descripciones dejan mucho que[n]desear? Ojal茨 fueran m茨s legibles...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ann]]
[s][vp 8 2 0 6049 65535 0]Venga, v茨monos a casa.[n][f 1 3 65535][w][e]

