[msg MSG_000_0_0 [Yusuke]]
[s][bup 0 5 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 4090 65535 0]Mm... Ha venido el doble[n]de gente de lo normal.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero la verdad es que me gusta[n]el ruido que produce la multitud.[n]Me ayuda a agudizar los sentidos.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 1 5 100]Si cierro los ojos, es casi como[n]si estuviera[n]flotando en el espacio.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]夷Este ruido es relajante?[clr 27][e]
[s]Me alegro de que lo disfrutes.[e]
[s]En el espacio no hay sonido.[e]

[msg MSG_002_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0][f 5 13 5 15 5]El silencio absoluto es[n]demoledor para m胤.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷No te sientes como r胤gido cuando[n]est茨s en un lugar sin sonido,[n]solo con tus pensamientos?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]La cantidad de ruido justa me[n]permite fundirme con el entorno.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4168 65535 0][f 5 13 5 10 5]Desde luego. Se puede[n]aprender mucho observando[n]el trabajo de otros.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]C吋mo se interprete tambi姻n depende[n]del estado del observador.[n]Es como una obra de arte viviente.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4129 65535 0][f 5 13 5 5 5]Es m茨s una cuesti吋n[n]de imaginaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Es bastante dif胤cil conseguir[n]tener la sensaci吋n de fundirse[n]con algo mayor que uno mismo.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Sinceramente, siento que algo[n]ha cambiado en m胤 despu姻s[n]de nuestra visita aqu胤...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Parece que mi actitud hacia[n]el arte ha cambiado de alg雨n modo.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ah, s胤. Me gustar胤a mostrarte[n]una de mis obras favoritas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Una obra que te hace ver[n]algo nuevo en cada visita[n]es muy dif胤cil de encontrar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tengo ganas de ver lo que saco[n]de ella hoy. Espero que sientas[n]lo mismo, [f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4071 65535 0]Han hecho una estatua basada[n]en el cuadro de antes.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Puede que sea una mera r姻plica,[n]pero me gustar胤a d茨rtela,[n][f 4 2].[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][vp 8 2 0 4076 65535 0]Mi impulso art胤stico se est茨[n]disparando... Volvamos a casa.[n][f 1 3 65535][w][e]

