[msg MSG_000_0_0 [Shinya]]
[s][bup 0 110 4 0 0][f 4 10 65535 0 0][vp 8 2 0 17066 65535 0]斡夷Eh?! Vaya, 斡夷hay gente que[n]viene aqu胤 sola?![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Y qu姻 haces en un parque de atracciones[n]sin compa隠胤a? 夷No te sientes solo?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Son fans ac姻rrimos.[e]
[s]Eso parece.[e]
[s][f 0 8 2 1 2217]Venir solo no est茨 tan mal.[clr 27][e]

[msg MSG_002_0_0 [Shinya]]
[s][bup 0 110 0 0 0][f 4 10 65535 0 0][vp 8 2 0 17072 65535 0][f 5 13 17 10 1010]Mmm... Bueno, supongo que es bastante divertido.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cuando empec姻 a jugar[n]a Gun About, fui solo[n]a varios recreativos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero creo que esto no es exactamente lo mismo.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Shinya]]
[s][bup 0 110 1 0 0][f 4 10 65535 0 0][vp 8 2 0 17075 65535 0][f 5 13 17 10 1010]Pero seguro que[n]se est茨n divirtiendo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oye, 夷qu姻 pensar茨n[n]los dem茨s de nosotros?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No nos parecemos tanto como[n]para ser hermanos. Y nadie[n]se creer胤a que soy tu maestro.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Shinya]]
[s][bup 0 110 4 0 0][f 4 10 65535 0 0][vp 8 2 0 17039 65535 0][f 5 13 17 15 1010]斡夷T雨 tambi姻n vienes solo,[n][f 4 1]?![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]As胤 que es un sitio muy divertido...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Shinya]]
[s][bup 0 110 0 0 0][f 4 10 65535 0 0][vp 8 2 0 17019 65535 0]夷Quieres montarte en algo,[n][f 4 1]? A m胤[n]me interesan varias atracciones.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Shinya]]
[s][bup 0 110 1 0 0][f 4 10 65535 0 0][vp 8 2 0 17059 65535 0]夷Est茨s seguro?[n]Vale, 斡pues decidido![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Ser茨 posible montarse en todo[n]en un solo d胤a? Hay que hacer cola,[n]夷verdad? 斡D姻monos prisa![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mmm, en realidad...[n]斡hace mucho que quer胤a venir aqu胤![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Shinya]]
[s][bup 0 110 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Me han dado esto. Solo[n]se lo dan a los ni隠os, 夷verdad?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Te conseguir姻 uno,[n][f 4 1]![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Shinya]]
[s][vp 8 2 0 17030 65535 0]斡Me lo he pasado genial hoy![n]Gracias.[n][f 1 3 65535][w][e]

