[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Sumire se lo est茨 pasando bien...[n][f 1 3 65535][w][e]
[s][f 5 13 33 10 10][vp 8 0 0 0 65535 0]Parece ensimismada por la luz[n]que se cuela entre las hojas...[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sumire[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]Gracias por lo de hoy.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Sumire se lo est茨 pasando bien...[n][f 1 3 65535][w][e]
[s][f 5 13 33 10 10][vp 8 0 0 0 65535 0]Parece ensimismada por la luz[n]que se cuela entre las hojas...[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sumire[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]Gracias por lo de hoy.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Sumire se lo est茨 pasando bien...[n][f 1 3 65535][w][e]
[s][f 5 13 33 10 10][vp 8 0 0 0 65535 0]Parece ensimismada por la luz[n]que se cuela entre las hojas...[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sumire[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]Gracias por lo de hoy.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Sumire se lo est茨 pasando bien...[n][f 1 3 65535][w][e]
[s][f 5 13 33 10 10][vp 8 0 0 0 65535 0]Parece ensimismada por la luz[n]que se cuela entre las hojas...[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sumire[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]Muchas gracias por el d胤a de hoy.[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Sumire se lo est茨 pasando bien...[n][f 1 3 65535][w][e]
[s][f 5 13 33 10 10][vp 8 0 0 0 65535 0]Parece ensimismada por la luz[n]que se cuela entre las hojas...[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sumire[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]Muchas gracias por el d胤a de hoy.[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Sumire se lo est茨 pasando bien...[n][f 1 3 65535][w][e]
[s][f 5 13 33 10 10][vp 8 0 0 0 65535 0]Parece ensimismada por la luz[n]que se cuela entre las hojas...[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sumire[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]Muchas gracias por el d胤a de hoy.[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Sumire se lo est茨 pasando bien...[n][f 1 3 65535][w][e]
[s][f 5 13 33 10 10][vp 8 0 0 0 65535 0]Parece ensimismada por la luz[n]que se cuela entre las hojas...[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sumire[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]Muchas gracias por el d胤a de hoy.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Sumire se lo est茨 pasando bien...[n][f 1 3 65535][w][e]
[s][f 5 13 33 10 10][vp 8 0 0 0 65535 0]Parece ensimismada por la luz[n]que se cuela entre las hojas...[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sumire[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]Muchas gracias por el d胤a de hoy.[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Sumire se lo est茨 pasando bien...[n][f 1 3 65535][w][e]
[s][f 5 13 33 10 10][vp 8 0 0 0 65535 0]Parece ensimismada por la luz[n]que se cuela entre las hojas...[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sumire[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]Muchas gracias por el d胤a de hoy.[n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]Dummy[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]Sumire se lo est茨 pasando bien...[n][f 1 3 65535][w][e]
[s][f 5 13 33 10 10][vp 8 0 0 0 65535 0]Parece ensimismada por la luz[n]que se cuela entre las hojas...[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sumire[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Sumire]]
[s][vp 8 2 0 57169 65535 0]斡Muchas gracias por el d胤a de hoy![n]斡Deber胤amos volver alguna vez![n][f 1 3 65535][w][e]

