[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Makoto parece un poco nerviosa.[n][f 1 3 65535][w][e]
[s][f 5 13 3 10 6][vp 8 0 0 0 65535 0]Creo que ahora ve la habitaci吋n[n]de forma diferente.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Makoto[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][vp 8 2 0 2076 65535 0]Qu姻 relajante...[n][f 1 3 65535][w][e]

[msg MND_003_5_0]
[s][vp 8 0 0 0 65535 0]He acompa隠ado[n]a Makoto a la estaci吋n...[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Makoto parece un poco nerviosa.[n][f 1 3 65535][w][e]
[s][f 5 13 3 10 6][vp 8 0 0 0 65535 0]Creo que ahora ve la habitaci吋n[n]de forma diferente.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Makoto[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][vp 8 2 0 2076 65535 0]Qu姻 relajante... Me encantar胤a[n]volver y pasar otro[n]rato contigo.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]He acompa隠ado[n]a Makoto a la estaci吋n...[n][f 1 3 65535][w][e]

