[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 11 10 1013][vp 8 0 0 0 65535 0]Las cartas del tarot hab胤an[n]predicho que ser胤a[n]afortunada en el amor.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Chihaya]]
[s][vp 8 2 0 10049 65535 0]夷Te importar胤a acompa隠arme...?[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 11 10 1013][vp 8 0 0 0 65535 0]Las cartas del tarot hab胤an[n]predicho que ser胤a[n]afortunada en el amor.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Chihaya]]
[s][vp 8 2 0 10049 65535 0]Hoy estoy muy contenta.[n]夷Te importar胤a acompa隠arme...?[n][f 1 3 65535][w][e]

