[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Futaba est茨 esforz茨ndose mucho.[n][f 1 3 65535][w][e]
[s][f 5 13 10 10 8][vp 8 0 0 0 65535 0]A este paso, acabar茨[n]acostumbr茨ndose a la gente.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Futaba[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][vp 8 2 0 9049 65535 0]Me voy a casa.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Futaba est茨 esforz茨ndose mucho.[n][f 1 3 65535][w][e]
[s][f 5 13 10 10 8][vp 8 0 0 0 65535 0]A este paso, acabar茨[n]acostumbr茨ndose a la gente.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Futaba[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][vp 8 2 0 9049 65535 0]Me voy a casa.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Futaba est茨 esforz茨ndose mucho.[n][f 1 3 65535][w][e]
[s][f 5 13 10 10 8][vp 8 0 0 0 65535 0]A este paso, acabar茨[n]acostumbr茨ndose a la gente.[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Futaba[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][vp 8 2 0 9049 65535 0]Me voy a casa.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Futaba est茨 esforz茨ndose mucho.[n][f 1 3 65535][w][e]
[s][f 5 13 10 10 8][vp 8 0 0 0 65535 0]A este paso, acabar茨[n]acostumbr茨ndose a la gente.[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Futaba[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][vp 8 2 0 9049 65535 0]Me voy a casa.[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Futaba est茨 haciendo grandes progresos.[n][f 1 3 65535][w][e]
[s][f 5 13 10 10 8][vp 8 0 0 0 65535 0]Parece que quiere ir a un lugar[n]con m茨s gente la pr吋xima vez.[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Futaba[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Futaba]]
[s][vp 8 2 0 9137 65535 0]Bueno, 斡lo intentar姻![n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Futaba est茨 de los nervios.[n][f 1 3 65535][w][e]
[s][f 5 13 10 10 8][vp 8 0 0 0 65535 0]Pero esto la ayudar茨[n]a desenvolverse entre la multitud.[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Futaba[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Futaba]]
[s][vp 8 2 0 9083 65535 0]Me voy a casa.[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Futaba est茨 de los nervios.[n][f 1 3 65535][w][e]
[s][f 5 13 10 10 8][vp 8 0 0 0 65535 0]Pero esto la ayudar茨[n]a desenvolverse entre la multitud.[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Futaba[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Futaba]]
[s][vp 8 2 0 9083 65535 0]Me voy a casa.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][f 4 24 0 4 0 42 3 100][f 4 24 0 4 0 9 3 100][f 4 24 0 4 0 0 0 0][vp 8 0 0 0 65535 0]Futaba parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 10 10 8][f 4 24 0 4 0 36 5 100][f 4 24 0 4 0 0 10 100][vp 8 0 0 0 65535 0]Creo que hasta ella se da cuenta[n]de lo mucho que ha mejorado.[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Futaba[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Cha胤to, 斡me voy a casa![n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][f 4 24 0 4 0 42 3 100][f 4 24 0 4 0 9 3 100][f 4 24 0 4 0 0 0 0][vp 8 0 0 0 65535 0]Futaba parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 10 10 8][f 4 24 0 4 0 36 5 100][f 4 24 0 4 0 0 10 100][vp 8 0 0 0 65535 0]Creo que hasta ella se da cuenta[n]de lo mucho que ha mejorado.[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Futaba[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]Venga, 斡vamos a casa![n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][f 4 24 0 4 0 42 3 100][f 4 24 0 4 0 9 3 100][f 4 24 0 4 0 0 0 0][vp 8 0 0 0 65535 0]Futaba parece feliz.[n][f 1 3 65535][w][e]
[s][f 5 13 10 10 8][f 4 24 0 4 0 36 5 100][f 4 24 0 4 0 0 10 100][vp 8 0 0 0 65535 0]Creo que hasta ella se da cuenta[n]de lo mucho que ha mejorado.[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Futaba[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Futaba]]
[s][vp 8 2 0 9050 65535 0]斡Ya me desenvuelvo mejor entre[n]la multitud gracias a ti, [f 4 2]![n]Bueno, 斡me voy a casa![n][f 1 3 65535][w][e]

