[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]ダミーメッセージ[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 10 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 10 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 10 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 10 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 10 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Sojiro parece abstra胤do.[n][f 1 3 65535][w][e]
[s][f 5 13 6 10 1003][vp 8 0 0 0 65535 0]Me he puesto a trabajar[n]como de costumbre.[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 10 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Sojiro parece abstra胤do.[n][f 1 3 65535][w][e]
[s][f 5 13 6 10 1003][vp 8 0 0 0 65535 0]Me he puesto a trabajar[n]como de costumbre.[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 10 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 10 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Ya eres todo un experto, 夷eh?[n]En fin, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_040_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_041_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_042_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_043_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_044_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_045_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_046_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_047_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_048_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_049_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_050_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_051_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_052_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_053_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_054_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_055_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_056_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_057_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_058_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_059_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_060_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_061_0_0]
[s][vp 8 0 0 0 65535 0]Sojiro parece abstra胤do.[n][f 1 3 65535][w][e]
[s][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]Me he puesto a trabajar[n]como de costumbre.[n][f 1 3 65535][w][e]

[msg MND_062_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_063_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_064_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_065_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_066_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_067_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_068_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_069_0_0]
[s][vp 8 0 0 0 65535 0]Sojiro parece abstra胤do.[n][f 1 3 65535][w][e]
[s][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]Me he puesto a trabajar[n]como de costumbre.[n][f 1 3 65535][w][e]

[msg MND_070_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_071_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_072_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_073_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_074_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_075_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Oye, gracias por ayudarme.[n][f 1 3 65535][w][e]

[msg MND_076_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_077_0_0]
[s][vp 8 0 0 0 65535 0]La tutela de Sojiro[n]es sumamente precisa.[n][f 1 3 65535][w][e]
[s][f 5 13 6 5 1003][vp 8 0 0 0 65535 0]He seguido sus instrucciones[n]al mil胤metro.[n][f 1 3 65535][w][e]

[msg MND_078_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Sojiro[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_079_0_0 [Sojiro]]
[s][vp 8 2 0 5030 65535 0]Ya eres todo un experto, 夷eh?[n]En fin, gracias por ayudarme.[n][f 1 3 65535][w][e]

