[msg MND_000_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_001_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece desconcertada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 11 10 1013]Le dejar姻 que me lea el futuro[n]hasta que se d姻 por satisfecha.[n][f 1 3 65535][w][e]

[msg MND_002_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MND_004_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_005_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece desconcertada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 11 10 1013]Le dejar姻 que me lea el futuro[n]hasta que se d姻 por satisfecha.[n][f 1 3 65535][w][e]

[msg MND_006_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_009_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece desconcertada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 11 10 1013]Le dejar姻 que me lea el futuro[n]hasta que se d姻 por satisfecha.[n][f 1 3 65535][w][e]

[msg MND_010_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MND_012_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_013_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece desconcertada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 11 10 1013]Le dejar姻 que me lea el futuro[n]hasta que se d姻 por satisfecha.[n][f 1 3 65535][w][e]

[msg MND_014_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MND_016_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_017_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece desconcertada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 11 10 1013]Le dejar姻 que me lea el futuro[n]hasta que se d姻 por satisfecha.[n][f 1 3 65535][w][e]

[msg MND_018_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MND_020_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_021_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece afligida.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 11 10 1013]Le dejar姻 que me lea el futuro[n]hasta que se d姻 por satisfecha.[n][f 1 3 65535][w][e]

[msg MND_022_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MND_024_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece afligida.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 11 10 1013]Le dejar姻 que me lea el futuro[n]hasta que se d姻 por satisfecha.[n][f 1 3 65535][w][e]

[msg MND_026_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MND_028_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_029_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece desconcertada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 11 10 1013]Le dejar姻 que me lea el futuro[n]hasta que se d姻 por satisfecha.[n][f 1 3 65535][w][e]

[msg MND_030_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MND_032_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_033_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece desconcertada.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 11 10 1013]Le dejar姻 que me lea el futuro[n]hasta que se d姻 por satisfecha.[n][f 1 3 65535][w][e]

[msg MND_034_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_035_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MND_036_0_0]
[s][vp 8 0 0 0 65535 0]Mu隠eco[n][f 1 3 65535][w][e]

[msg MND_037_0_0]
[s][vp 8 0 0 0 65535 0]Chihaya parece feliz.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 5 13 11 10 1013]Le dejar姻 que me lea el futuro[n]hasta que se d姻 por satisfecha.[n][f 1 3 65535][w][e]

[msg MND_038_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi v胤nculo con Chihaya[n]se fortalecer茨 pronto.[n][f 1 3 65535][w][e]

[msg MSG_039_0_0 [Chihaya]]
[s][vp 8 2 0 10128 65535 0]Ja, ja, me lo he pasado bien.[n]Hasta luego.[n][f 1 3 65535][w][e]

