[msg MSG_000_0_0 [Profesor Ushimaru]]
[s][bup 0 301 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37066 65535 0]斡Oye, [f 4 1]![n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Profesor Ushimaru]]
[s][bup 0 301 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]斡Oye! 斡Presta atenci吋n![n]斡夷As胤 escuchas t雨 a los dem茨s[n]cuando te hablan?![n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Alumna]]
[s][vp 8 0 0 0 65535 0]斡Hala! 斡Qu姻 finta m茨s 姻pica![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Alumno]]
[s][vp 8 0 0 0 65535 0]Es flipante que haya esquivado[n]el lanzamiento de Ushimaru.[n]夷Es un ninja o qu姻?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Profesor Ushimaru]]
[s][bup 0 301 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37062 65535 0]Chsss... Bueno, venga. Sigamos.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1183 65535 0]Hala... 斡Toda la clase est茨 pendiente[n]de ti! Tu [f 4 11 1][clr 26][f 4 12 1][clr 27][n]seguro que ha subido.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Alumna]]
[s][vp 8 0 0 0 65535 0]Buah, eso tiene pinta de doler.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Alumno]]
[s][vp 8 0 0 0 65535 0]*risa* Le ha dado[n]en toda la frente.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Profesor Ushimaru]]
[s][bup 0 301 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37067 65535 0]Eso te pasa por dormirte.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0][f 4 10 65535 0 0]Los j吋venes de hoy en d胤a[n]no respet茨is a los mayores.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]Madre m胤a... Parece que necesitas[n]m茨s [f 4 11 2][clr 26][f 4 12 2][clr 27] para esquivar eso.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Alumna]]
[s][vp 8 0 0 0 65535 0]斡No puede ser! 斡夷Lo ha ignorado?![n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Alumno]]
[s][vp 8 0 0 0 65535 0]斡夷No le hace nada?![n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Profesor Ushimaru]]
[s][bup 0 301 0 0 0][f 4 10 65535 0 0][vp 8 2 0 37062 65535 0]Chsss... Bueno, venga. Sigamos.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1168 65535 0]As胤 que lo har茨s con calma, 夷eh?[n]Desprendes mucha [f 4 11 4][clr 26]Gentileza[clr 27][n]ahora mismo.[n][f 1 3 65535][w][e]

