[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0]Has mirado los mensajes, 夷no?[n][w][e]
[s]Es normal que duden de ti[n]si no respondiste a su invitaci吋n.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ahora ya no sirve de nada[n]darle vueltas.[n]Venga, a la cama.[n][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0]Hala, vuelven a dudar de ti.[n]Presta un poco m茨s de atenci吋n[n]a los mensajes que recibes.[n][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Bueno, a la cama.[n][w][e]

