[msg MES_GROUP0_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 40 10 50 10][vp 8 2 1 54502 65535 0]Bueno, parece que has cumplido[n]con nuestro trato.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero no pienso darte las gracias.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si no hubierais intervenido, todo[n]habr胤a salido como hab胤a planeado.[n][w][e]

[msg MES_GROUP0_02 [Morgana]]
[s][bup 0 3 11 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 1025 65535 0]Je, tampoco es para ponerse as胤.[n]Ya sabemos c吋mo te sientes.[n][w][e]

[msg MES_GROUP1_01 [Akechi]]
[s][bup 0 9 2 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 51 10 50 10][vp 8 2 1 8028 65535 0]Ahora que lo veo con mis ojos,[n]puedo afirmar que no he visto[n]nada m茨s repulsivo en mi vida.[n][w][e]

[msg MES_GROUP1_02 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 65535 3 10 0 10]Tan estrecho de parietales[n]como siempre...[n][w][e]

[msg MES_GROUP1_03 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 65535 51 10 50 10]夷Acaso deber胤a sentirme[n]de otra manera?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]De hecho, seguro que sientes[n]lo mismo por Madarame.[n][w][e]

[msg MES_GROUP1_04 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 33 10 0 10][vp 8 2 1 4194 65535 0]Madarame...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Cierto, lleg吋 un punto en que solo[n]sent胤a decepci吋n y odio hacia 姻l.[n][w][e]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero el tiempo[n]me ha permitido reflexionar...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pudo haber un cierto traspi姻[n]en su vida que lo arrastrara[n]por el mal camino.[n][w][e]

[msg MES_GROUP1_05 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 42 10 50 10][vp 8 2 1 54477 65535 0]夷Insin雨as que quiz茨 no fuera[n]tan malvado? T雨 y[n]tus estrafalarias sandeces...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Fueran cuales fueran sus razones,[n]no cambia el hecho de que haya[n]sido una mierda de padre.[n][w][e]
[s][bup 0 9 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Adem茨s, no me interesa malgastar[n]el tiempo empatizando con 姻l tras[n]todo lo que me ha hecho pasar.[n][w][e]

[msg MES_GROUP2_01 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 51 10 50 10][vp 8 2 1 8028 65535 0]Nunca pens姻 que el plan acabar胤a[n]con Shido. Siempre asum胤 que[n]otro monstruo coger胤a el testigo.[n][w][e]

[msg MES_GROUP2_02 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 65535 3 10 0 10]Aun as胤, yo ya hab胤a decidido[n]que no dejar胤a de exponer[n]a las partes culpables.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Quiero conservar mi fe[n]en la justicia.[n][w][e]

[msg MES_GROUP2_03 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 35 10 50 10][vp 8 2 1 8133 65535 0]夷Eh? Un t吋pico como ese[n]sorprende viniendo de ti, Sae.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Sospecho que los Ladrones Fantasma[n]han influido un poco en ti.[n][w][e]

[msg MES_GROUP2_04 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 21034 65535 0]Cabe la posibilidad.[n][w][e]
[s][bup 0 105 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Y si t雨 tambi姻n haces algo[n]por cambiar? Como dejar de ir[n]de persona fr胤a y vivir el momento.[n][w][e]

[msg MES_GROUP2_05 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 51 10 50 10][vp 8 2 1 54418 65535 0]斡Ja! Menos guasa. Yo paso.[n][w][e]

[msg MES_GROUP3_01 [Yoshida]]
[s][bup 0 112 3 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 33 10 0 10][vp 8 2 1 20026 65535 0]Ser popular en la sociedad atrae,[n]pero la cuesti吋n es que su poder[n]cost吋 muchas vidas inocentes.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷C吋mo demonios lleg吋 a consumirle[n]la locura de esa forma?[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷C吋mo demonios lleg吋 a consumirle[n]tanto la megaloman胤a?[n][w][e]

[msg MES_GROUP3_02 [Sojiro]]
[s][bup 0 103 2 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 5080 65535 0]Sus intenciones no importan[n]lo m茨s m胤nimo. La realidad es[n]que destruy吋 m茨s de lo que cre吋.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Y parte del da隠o no se podr茨[n]reparar jam茨s.[n][w][e]

[msg MES_GROUP4_01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 1044 65535 0]Siempre pens姻 que Shido era un[n]conspirador, hasta en el mundo real.[n]Me preguntaba c吋mo nos atacar胤a...[n][w][e]

[msg MES_GROUP4_02 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 32 10 0 10][vp 8 2 1 7021 65535 0]No esperaba que se pusiera hecho[n]un basilisco al final.[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Crees que era igual[n]en la realidad?[n][w][e]

[msg MES_GROUP4_03 [Morgana]]
[s][bup 0 3 7 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 42 10 0 10][vp 8 2 1 1169 65535 0]夷Qui姻n sabe? Sea como sea,[n]no quiero imagin茨rmelo.[n][w][e]

[msg MES_GROUP5_01 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 4156 65535 0]Lo peor de Shido era su fuerza[n]bruta, y no solo por dejar atr茨s[n]un pilar de sacrificios humanos.[n][w][e]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Incluso en el mundo cognitivo,[n]su fuerza no ten胤a parang吋n.[n][w][e]

[msg MES_GROUP5_02 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 9034 65535 0]夷Qui姻n iba a pensar que su forma[n]final ser胤a un cachas asqueroso?[n]Odio admitirlo, pero era fuerte.[n][w][e]

[msg MES_GROUP8_01 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 54001 65535 0]Menos mal que Ryuji nos baj吋[n]ese bote cuando est茨bamos[n]escapando del Palacio de Shido.  [n][w][e]

[msg MES_GROUP8_02 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 65535 36 10 0 10]斡Fue para fliparlo! Y todo gracias[n]al carrer吋n que se dio.[n][w][e]

[msg MES_GROUP8_03 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 2048 65535 0]*risita* Sin duda fue[n]el mejor jugador de ese Palacio.[n]Al final me acab吋 sorprendiendo.[n][w][e]
[s][bup 0 6 3 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Aunque por su culpa casi[n]nos morimos de pena...[n][w][e]

[msg MES_GROUP8_04 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 9098 65535 0]Creo que nos pasamos[n]un poco con 姻l.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0][f 4 23 1 65535 42 10 0 10]A ver si le pido perd吋n[n]un d胤a de estos...[n][w][e]

[msg MES_GROUP9_01 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 32 10 0 10][vp 8 2 1 7192 65535 0]Este t胤o lo ten胤a todo: era listo,[n]rico, famoso... 夷Por qu姻 se molest吋[n]en hacer toda esa mierda?[n][w][e]

[msg MES_GROUP9_02 [Lavenza]]
[s][bup 0 100 0 0 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 55479 65535 0]Para bien o para mal, los deseos[n]del ser humano no conocen l胤mites.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]El tal Shido no es una excepci吋n.[n]Seguramente a雨n alberga[n]deseos que jam茨s satisfar茨.[n][w][e]

[msg MES_GROUP9_03 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][f 4 23 1 65535 3 10 0 10][vp 8 2 1 7038 65535 0]A ver, entiendo que todos queremos[n]cosas en la vida, pero...[n][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]夷Hacer sufrir a los dem茨s[n]solo por tu propio beneficio? As胤[n]no se hacen realidad los sue隠os.[n][w][e]

