[msg MND_COOP_START_000_00]
[s]夷Qui姻n llama a estas horas?[n][w][e]

[msg MND_COOP_NEXT_000_00]
[s]Otra llamada...[n]夷Qui姻n es ahora?[n][w][e]

[msg MND_COOP_END_000_00]
[s]Han colgado.[n][w][e]
[s]Qu姻 raro...[n][w][e]
[s]Quiz茨 habr胤a sido mejor[n]aceptar su invitaci吋n.[n][w][e]
[s]Creo que ya est茨 bien por hoy.[n][w][e]

[msg MSG_COOP_MORGANA_000_00 [Morgana]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_MAKOTO_000_00 [Makoto]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_HARU_000_00 [Haru]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_YUSUKE_000_00 [Yusuke]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_SOJIRO_000_00 [Sojiro]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_ANNE_000_00 [Ann]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_RYUJI_000_00 [Ryuji]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_AKECHI_000_00 [Akechi]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_FUTABA_000_00 [Futaba]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_URANAI_000_00 [Chihaya]]
[s][bup 0 113 0 0 0][f 4 10 65535 0 0]He le胤do mi futuro en las cartas,[n]y dec胤an que deb胤a llamarte.[n][w][e]
[s]As胤 que les he hecho caso.[n]斡Hasta luego![n][w][e]

[msg MSG_COOP_URANAI_000_01 [Chihaya]]
[s][bup 0 113 0 0 0][f 4 10 65535 0 0]Solo quer胤a preguntarte una cosa.[n]夷Tan ocupado est茨s que no[n]tienes tiempo para hablar conmigo?[n][w][e]
[s]夷Tienes mucho entre manos?[n]夷Hay secretos que no puedes[n]compartir con otra gen...?[n][w][e]
[s]斡Da igual! 斡Olvida lo que he dicho![n]斡Adi吋s![n][w][e]

[msg MSG_COOP_VELVET_A_000_00 [Justine]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_VELVET_B_000_00 [Caroline]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_IWAI_000_00 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0]Oye, soy yo. 夷Por qu姻 te rajaste?[n][w][e]
[s]夷Por miedo? Quer胤as un pedido, 夷no?[n][w][e]
[s]Pues cambia de actitud,[n]se隠or amante de las armas.[n][w][e]

[msg MSG_COOP_IWAI_000_01 [Iwai]]
[s][bup 0 104 0 0 0][f 4 10 65535 0 0]Anda, pero si eres t雨.[n]No volviste a aparecer.[n][w][e]
[s]Te gustan las armas, 夷verdad?[n]夷O era una trola?[n][w][e]
[s]No me decepciones.[n][w][e]

[msg MSG_COOP_TAKEMI_000_00 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0]Oye, una cosa, necesitas medicinas[n]para los ex茨menes, 夷verdad?[n][w][e]
[s]Ya no vienes a los ensayos[n]cl胤nicos. 夷Era todo palabrer胤a?[n][w][e]
[s]No me hagas perder el tiempo.[n][w][e]

[msg MSG_COOP_TAKEMI_000_01 [Takemi]]
[s][bup 0 108 0 0 0][f 4 10 65535 0 0]夷Ya no quieres venir[n]a los ensayos cl胤nicos?[n][w][e]
[s]夷Era mentira eso de que lo hac胤as[n]por los ex茨menes de acceso[n]a la universidad?[n][w][e]
[s]Si todav胤a te interesa, date prisa.[n][w][e]

[msg MSG_COOP_KAWAKAMI_000_00 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0]Eh... Bueno...[n][w][e]
[s]夷No necesitas volver[n]a saltarte las clases?[n][w][e]
[s]Voy justa de dinero. Por favor...[n][w][e]

[msg MSG_COOP_KAWAKAMI_000_01 [Kawakami]]
[s][bup 0 109 0 0 0][f 4 10 65535 0 0]No habr茨s olvidado tu promesa[n]de solicitar mis servicios si dejo[n]que te saltes las clases, 夷no?[n][w][e]
[s]De todas formas,[n]夷qu姻 haces en ese tiempo?[n][w][e]
[s]Es sospechoso.[n][w][e]
[s]斡Ay! Disculpa por haberte llamado[n]tan tarde. Buenas noches.[n][w][e]

[msg MSG_COOP_OOYA_000_00 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0]Soy yo.[n][w][e]
[s]夷Qu姻 ocurre?[n]夷Ya no tienes m茨s informaci吋n?[n][w][e]
[s]A lo mejor ni siquiera eres fan[n]de los Ladrones Fantasma.[n][w][e]
[s]Si lo que me has dicho hasta ahora[n]es cierto, ven a verme.[n]斡Date prisa![n][w][e]

[msg MSG_COOP_OOYA_000_01 [Ohya]]
[s][bup 0 107 0 65535 0][f 4 10 65535 0 0]Oye, ya vale.[n]夷A qu姻 viene esa reacci吋n?[n][w][e]
[s]Empiezo a dudar que seas[n]fan de los Ladrones Fantasma.[n][w][e]
[s]*suspiro* Ya me da igual.[n]Nos vemos.[n][w][e]

[msg MSG_COOP_ODA_000_00 [Shinya]]
[s][bup 0 110 0 0 0][f 4 10 65535 0 0]Oye, 夷por qu姻 no has venido[n]a verme? Quer胤a hablar contigo[n]sobre los Ladrones Fantasma.[n][w][e]
[s]夷No ser茨 mentira eso[n]de que los conoces?[n][w][e]
[s]Bah, da igual. Nos vemos.[n][w][e]

[msg MSG_COOP_ODA_000_01 [Shinya]]
[s][bup 0 110 0 0 0][f 4 10 65535 0 0]Oye, 夷qu姻 pasa? Dijiste que me[n]hablar胤as de los Ladrones Fantasma.[n][w][e]
[s]夷Al final era mentira[n]eso de que los conoc胤as?[n][w][e]
[s]Yo ya paso. Me largo.[n][w][e]

[msg MSG_COOP_HIFUMI_000_00 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0]Quiz茨 te resulte maleducada, pero[n]que sepas... que nunca mejorar茨s[n]si le pones tan pocas ganas.[n][w][e]
[s]Tienes que dejarte la piel. Si[n]de verdad te gusta el shogi, claro.[n][w][e]

[msg MSG_COOP_HIFUMI_000_01 [Hifumi]]
[s][bup 0 106 0 65535 0][f 4 10 65535 0 0]Cre胤a que te apasionaba el shogi,[n]pero puede que estuviera[n]equivocada.[n][w][e]
[s]Me llevar胤a una gran decepci吋n[n]si todo lo que te llev吋 a querer[n]ser mi aprendiz fuera mentira.[n][w][e]

[msg MSG_COOP_MISHIMA_000_00 [Mishima]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_YOSHIDA_000_00 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0]Hola, soy Yoshida. 夷Qu姻 has estado[n]haciendo 雨ltimamente?[n][w][e]
[s]Es importante dedicarle tiempo[n]a los estudios. 夷Ya no te apasiona[n]la legislaci吋n?[n][w][e]
[s]Vaya, con lo que esperaba yo de ti...[n][w][e]

[msg MSG_COOP_YOSHIDA_000_01 [Yoshida]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0]Hola, soy Yoshida.[n]夷Ya no te interesa la pol胤tica?[n][w][e]
[s]A lo mejor no era cierto[n]que aspirabas a dedicarte a esto.[n][w][e]
[s]Me has decepcionado mucho.[n][w][e]

[msg MSG_COOP_SAE_000_00 [Sae]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

[msg MSG_COOP_WORLD_000_00 [Mundo]]
[s]夷Por qu姻 no coges el tel姻fono?[n][w][e]

