[msg MND_COOP_START_000_00]
[s][vp 8 0 0 0 65535 0]夷Qui姻n llama a estas horas?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Shinya]]
[s][f 5 14]Le he ense隠ado el aviso a mam茨.[n]Yo tambi姻n estaba un poco asustado.[n][w][e]
[s]D胤selo a los Ladrones[n]Fantasma de mi parte.[n][w][e]

[msg MSG_002_0_0 [Yoshida]]
[s][f 5 14]Hoy he ganado las elecciones.[n][w][e]
[s]No lo habr胤a conseguido[n]de no ser por ti. Gracias.[n][w][e]
[s]Dicho eso, aqu胤 empieza la lucha de[n]verdad. A partir de ahora tendremos[n]que esforzarnos al m茨ximo.[n][w][e]

[msg MSG_003_0_0 [Yoshida]]
[s][f 5 14]Te llamo para que seas consciente[n]de los rumores que circulan[n]sobre las elecciones anticipadas.[n][w][e]
[s]Creo que solo puedes[n]ser mi ayudante durante[n]otro mes m茨s o menos.[n][w][e]
[s]Por ley, no puedo contar[n]con la ayuda de menores[n]durante las elecciones.[n][w][e]
[s]Lo siento, pero quiero[n]que lo tengas presente.[n][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][f 5 14]Gracias por lo de hoy.[n][w][e]
[s][f 5 14]Aunque hoy haya ganado, no me gust吋[n]irme sin darte la oportunidad[n]de resarcir tu p姻rdida.[n][w][e]
[s][f 5 14]Como ya he mencionado antes,[n]si me pidieras revancha,[n]la aceptar胤a.[n][w][e]
[s][f 5 14]Estar姻 delante[n]de la estaci吋n de Shibuya.[n][w][e]
[s][f 5 14]Si deseas volver a intentarlo,[n]p茨sate por all胤.[n]Te estar姻 esperando.[n][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Akechi estar茨 por Shibuya un rato.[n]Pero espera, 夷revancha?[n][f 1 3 65535][w][e]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]夷Eso era lo que estabais haciendo[n]en Mementos? Ahora tenemos mucho[n]entre manos. Ten cuidado, 夷vale?[n][f 1 3 65535][w][e]

