[msg MSG_000_0_0 [Voz misteriosa]]
[s][vp 8 0 0 1 65535 0]Esta historia es ficticia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 2 65535 0]Cualquier parecido con sucesos[n]o personas reales[n]es pura coincidencia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 3 65535 0]Solo quienes hayan aceptado[n]lo anterior tendr茨n el honor[n]de participar en el juego.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Aceptar[e]
[s]No aceptar[e]

[msg MSG_002_0_0 [Voz misteriosa]]
[s][vp 8 0 0 4 65535 0]El contrato est茨 sellado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 5 65535 0]Todo lo que pase[n]a partir de ahora es ficci吋n,[n]tal como has aceptado.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 6 65535 0]Es hora de que disfrutes[n]del juego[n]todo lo que te apetezca...[n][f 1 3 65535][w][e]

[msg MSG_002_5_0 [Voz misteriosa]]
[s][vp 8 0 0 7 65535 0]Se dice que el hombre tiene[n]la capacidad de resistir[n]a las situaciones m茨s desesperadas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 8 65535 0]Algunos se oponen al destino[n]y buscan un cambio. A veces[n]se les denominaba Tricksters.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 9 65535 0]El mundo no es como deber胤a ser.[n]Hay distorsi吋n por todas partes,[n]y no se puede evitar la 或perdici吋n位.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 10 65535 0]T雨 eres el Trickster...[n]Es hora de alzarse contra[n]el abismo de la distorsi吋n.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Voz misteriosa]]
[s][vp 8 0 0 11 65535 0]Ya veo.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 12 65535 0]Todo lo que pase a partir[n]de ahora ser茨 real...[n]夷Esa es tu cognici吋n sobre esto?[n][f 1 3 65535][w][e]
[s][vp 8 0 0 13 65535 0]Por desgracia, no puedo[n]permitir que participes en el juego.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 14 65535 0]Debo pedirte que te marches...[n][f 1 3 65535][w][e]

