[msg MSG_000_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]夷Que el instituto se ha[n]transformado en un castillo?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]夷Un gato parlante?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]夷Te ha dado una sobredosis[n]y est茨s alucinando o qu姻?[n]No te pasar姻 ni una sola.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Y ahora, contin雨a[n]con la historia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]El que recibi吋 un aviso de los Ladrones[n]Fantasma era nada menos[n]que un medallista ol胤mpico...[n][f 1 3 65535][w][e]

[msg MSG_001_5_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Un exalumno del Instituto Shujin[n]y profesor de Educaci吋n F胤sica,[n]Suguru Kamoshida.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Cuando confes吋, sali吋 a la luz que era culpable[n]de todo: de los abusos, las infracciones...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Pero no deber胤a haber conexi吋n[n]alguna entre vosotros dos,[n]ya que acababas de llegar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]夷Por qu姻 姻l?[n][f 1 3 65535][w][e]

[sel SEL_003_0_0 top]
[s]No quiero hablar.[e]
[s]Te lo dir姻 luego.[e]

[msg MSG_004_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]斡Esto es inaceptable![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]斡Intenta recordarlo![n][f 1 3 65535][w][e]

[msg SYS_005_0_0]
[s][vp 8 0 0 0 65535 0]Se ha actualizado el resumen[n]de la historia.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Para leerlo, pulsa [f 1 10 25][n]y despu姻s selecciona [clr 2]Historia[clr 27],[n]bajo la opci吋n [clr 2]Sistema[clr 27].[n][f 1 3 65535][w][e]

