[msg MSG_000_0_0 [Kawakami]]
[s][bup 0 109 3 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Por cierto, cuando te presentes...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]T吋matelo en serio[n]incluso si est茨s mintiendo, 夷vale?[n]No digas nada innecesario.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Estudiante con muy buen o胤do]]
[s][vp 8 0 0 3 5 0]夷Crees que es 姻l?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Estudiante de pelo corto]]
[s][vp 8 0 0 4 6 0]夷Qu姻? 夷El de los rumores?[n][f 1 3 65535][w][e]

