[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]斡夷Qu姻?![n][f 1 3 65535][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Pero 斡qu姻 cojones! 斡夷Es que[n]ese imb姻cil puede ser[n]m茨s mierda a雨n?![n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]C茨lmate.[e]
[s]Todav胤a estoy comiendo.[e]
[s]Ya es cosa del pasado...[e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]斡Me estoy cabreando solo con o胤rte![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Ah. Lo siento.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]夷En serio? Si llego a ser yo,[n]no me calmo hasta reventarle[n]la cara a ese mamonazo.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]As胤 que dejaste tu ciudad...[n]y ahora vives aqu胤, 夷eh?[n][f 1 2 90][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Puede que nos parezcamos m茨s[n]de lo que pensaba.[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]Puede que tengas raz吋n.[e]
[s]夷Y eso?[e]
[s]夷Qu姻 hiciste?[e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Eres el primer t胤o que me[n]ha hecho pensar eso.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]No es exactamente el 或c吋mo位,[n]pero... ya sabes.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]A m胤 no me han fichado nunca.[n][f 1 3 65535][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Aunque eso ahora no importa.[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Me imagino que es c吋mo nos trata[n]la gente, como si fu姻ramos[n]una molestia y no pint茨ramos nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Yo tambi姻n hice una estupidez[n]en el insti.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Ahora vives en Yongen, 夷verdad?[n][f 1 3 65535][w][e]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Es hora punta en el metro, as胤 que[n]te recomiendo que mates un poco[n]el tiempo antes de irte a casa.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Pero 夷c吋mo puede ser, t胤o?[n]Si apenas has probado bocado.[n][f 1 3 65535][w][e]

[sel SEL_014_0_0 top]
[s]夷Qu姻 haces?[e]
[s]Yo tambi姻n puedo hacer eso.[e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]D姻jamelo a m胤. Tengo que[n]agradecerte la ayuda prestada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]En fin, a partir de ma隠ana[n]nos cubrimos las espaldas[n]el uno al otro.[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Nos sentiremos mejor yendo[n]a clase cuando nos encarguemos[n]de Kamoshida.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 4 17 1 65535 65535 65535 65535 65535 65535 65535 2 7 300 1][vp 8 0 0 28 65535 0]斡Ah, s胤![n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Dame tu n雨mero y tu chat ID.[n][f 1 3 65535][w][e]

[msg SYS_017_0_0]
[s][vp 8 0 0 0 65535 0]Ya puedes acceder al chat.[n]Puede que de vez en cuando recibas[n]mensajes de tus allegados.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Prep茨rate, Kamoshida...[n][f 1 3 65535][w][e]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Ma隠ana mismo empezamos. Primero,[n]iremos a hablar con los chavales[n]que tiene esclavizados.[n][f 1 3 65535][w][e]

[msg MSG_018_3_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Ma隠ana es lo de voleibol, 夷no?[n]Kamoshida est茨 detr茨s de ello.[n]Me dan ganas de potar.[n][f 1 3 65535][w][e]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Pero gracias a ello, no hay clase[n]por la tarde y podremos movernos[n]sin que nadie se fije en nosotros.[n][f 1 3 65535][w][e]

[msg MSG_018_5_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Bueno, ma隠ana ya ultimaremos[n]los detalles...[n][f 1 3 65535][w][e]

[msg MSG_018_7_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Venga, tienes que comer m茨s.[n]Si hay un mont吋n de jengibre.[n][f 1 3 65535][w][e]

