[msg MSG_000_0_0 [Mishima]]
[s][bup 0 111 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]El despacho de Educaci吋n F胤sica...[n]El profesor Kamoshida siempre[n]lo usaba para... eh... ya sabes...[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][bup 0 111 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No ten胤amos alternativa. Nadie[n]puede desafiarlo. Pero Suzui...[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][bup 0 111 500 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷No deber胤amos perseguirlo? Vas[n]a ver al profesor Kamoshida, 夷no?[n][f 1 3 65535][w][e]

