[msg MSG_000_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Esa es la llave de este sitio.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]A partir de ahora cierras t雨.[n]No pienso esperar[n]hasta que vuelvas a casa.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]No prendas fuego a nada,[n]夷de acuerdo?[n][f 1 3 65535][w][e]

