[msg MSG_000_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]夷Conociste al pupilo de Madarame[n]de casualidad?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Vaya, qu姻 oportuno.[n]Me pregunto si est茨s[n]diciendo la verdad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]No importa.[n]Lo que me interesa es el m姻todo.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Es cierto que Madarame era[n]un delincuente imperdonable[n]que merece total desprecio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Era un adulto que sacrificaba[n]el bienestar de j吋venes en busca[n]de su propia fama y fortuna...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Pero 夷c吋mo has descubierto esos[n]actos tan ruines en tan poco tiempo[n]si se han desconocido durante a隠os?[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s]En el Metaverso.[e]
[s]No me acuerdo.[e]
[s]...[e]

[msg MSG_003_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Otra vez con eso del 或Metaverso位?[n][f 1 3 65535][w][e]
[s][vp 1 0 0 8 0 0]...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sae]]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Bien. Supongamos que, como dices,[n]la gente puede despertar[n]si les robas su tesoro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]En tal caso, tengo otra sospecha.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Hay gente que enloquece o pierde[n]la consciencia para siempre..., como[n]en el accidente de metro en abril.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sae]]
[s][bup 0 105 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Seg雨n se mire, tambi姻n se podr胤a[n]entender como un fen吋meno[n]que cause un despertar repentino.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]夷Tuviste algo que ver[n]en eso tambi姻n?[n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]No quiero decirlo.[e]
[s]No lo s姻...[e]
[s]...[e]

[msg MSG_008_0_0 [Sae]]
[s][bup 0 105 2 65535 0][vp 1 0 0 15 0 0]...[n][f 1 3 65535][w][e]
[s][bup 0 105 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Ya veo.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Sae]]
[s][bup 0 105 2 65535 0][vp 1 0 0 17 0 0]Pff...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Vale.[n]Cu姻ntame m茨s del caso de Madarame.[n]S姻 conciso y c胤隠ete a la verdad.[n][f 1 3 65535][w][e]

