[msg MSG_000_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Ohh, has tra胤do un mont吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]夷Qu姻 te parece haber[n]dado con comida tan lujosa?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]Estoy muy contento.[e]
[s]Solo quiero comer.[e]
[s]No tengo hambre.[e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Qu姻 adorable o胤r eso[n]de alguien como t雨.[n]No te emociones mucho, 夷vale?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Eres la 雨ltima persona a la que[n]quiero aconsejar sobre ello, Ryuji.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Eso pensaba yo, pero pru姻balo.[n]斡Con mejores ingredientes[n]las cosas saben muy diferentes![n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]M胤rate, actuando como si de repente[n]tuvieras un paladar refinado.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Eso dices, pero te has tra胤do[n]un mont吋n de comida...[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Supongo que si no la quieres, pues...[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][f 4 16 3 3 300 1 65535][vp 8 0 0 9 65535 0]斡Aparta esas manos![n]斡Me lo comer姻 despu姻s![n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]夷No crees que est茨s[n]comiendo demasiado, Mona?[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]No sabemos cu茨ndo[n]volveremos a venir.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]Ya, pero hab姻is tra胤do[n]un mont吋n de comida...[n]Ser胤a una pena desperdiciarla.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]夷Por qu姻 no les ayudas, Ryuji?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Deber胤amos ayudar los dos.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Ah, 夷yo? 斡Estoy muuuy lleeena![n]斡No puedo ayudar![n][f 1 3 65535][w][e]

[msg MSG_012_5_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]S胤, ya... Te est茨s hartando de tarta...[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 4 16 2 3 301 1 65535][vp 8 0 0 17 65535 0]Da igual. 斡Ya nos encargamos nosotros![n][f 1 3 65535][w][e]

[msg MND_013_5_0]
[s][vp 8 0 0 0 65535 0]Es como si diera igual[n]cu茨nto comamos. La cantidad[n]de comida no disminuye...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]夷A雨n hay m茨s...?[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][bup 0 2 11 65535 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]斡No desist茨is! 斡Sigamos![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Morgana]]
[s][bup 0 3 7 0 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]L-lo hemos conseguido...[n][f 1 3 65535][w][e]

[msg MND_016_5_0]
[s][vp 8 0 0 0 65535 0]El cintur吋n me aprieta m茨s...[n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]夷Eh? Ah, s胤...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Hemos ganado... todos...[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s]Ha sido pan comido.[e]
[s]Ha sido complicado.[e]
[s]夷Esto te parece un juego?[e]

[msg MSG_019_0_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]夷Tu est吋mago... es del tama隠o[n]de un pu隠etero Palacio...?[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Hemos ganado... porque[n]est茨bamos juntos...[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]No exactamente...[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]Buen trabajo, chicos.[n]夷Os hace un 雨ltimo plato[n]para limpiar el paladar?[n][f 1 3 65535][w][e]

[msg MSG_023_5_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]斡Os recomiendo la tarta[n]de temporada! 斡El pomelo le da[n]acidez y un incre胤ble dulzor![n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Para... No me hables de acidez...[n][f 1 3 65535][w][e]

[msg MSG_024_5_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]*eructo* Qu姻 mal...[n]Tengo que ir al ba隠o...[n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]Y yo... Por favor...[n]ll姻vame con cuidado...[n][f 1 3 65535][w][e]

[msg MSG_026_0_0 [Mujer elegante]]
[s][vp 8 0 0 31 30 0]Ay, mira esa mesa...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Hombre rico]]
[s][vp 8 0 0 32 9 0]Vamos, no te quedes mirando.[n]Normalmente no deben tener[n]la oportunidad de comer estos manjares.[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Mujer elegante]]
[s][vp 8 0 0 33 30 0]No puedo ni imaginarme[n]c吋mo ser茨n sus padres.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][f 4 16 2 3 301 1 65535][vp 8 0 0 34 65535 0]夷Qu姻 has dicho?[n][f 1 3 65535][w][e]

[msg MSG_030_5_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]斡Brrr![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 36 65535 0]No hay tiempo para eso...[n]Venga, vamos...[n][f 1 3 65535][w][e]

