[msg MSG_000_0_0 [Sombra de Nakanohara]]
[s][bup 0 214 501 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Lo siento... 斡Perd吋nenme, por favor![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]N-no supe superar que alguien[n]en quien confiaba me utilizara[n]y me d-desechara de tal forma...[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷Qui姻n?[e]
[s]夷Sigues culpando a los dem茨s?[e]
[s]...[e]

[msg MSG_002_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Oye, 夷te refieres al t胤o que[n]dijiste antes? 夷El Madarame ese?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]No hace falta ser tan arisco,[n]parece que se arrepiente de verdad.[n][f 1 3 65535][w][e]

[msg MSG_003_5_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Ese tipo del que hablas...[n]夷Es el tal Madarame[n]que mencionaste antes?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Sombra de Nakanohara]]
[s][bup 0 214 501 0 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Ten胤a miedo de que se me[n]volviera a tratar as胤,[n]como si no valiera nada...[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Ann]]
[s][bup 0 4 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]As胤 que alg雨n cabr吋n ego胤sta te ha[n]hecho sufrir a ti tambi姻n...[n][f 1 3 65535][w][e]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Aun as胤, no tendr胤as que haber[n]metido a esa mujer en este l胤o.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Sombra de Nakanohara]]
[s][bup 0 214 501 0 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Ya, ahora me doy cuenta. Acabar姻[n]con mis sentimientos por ella...[n][f 1 3 65535][w][e]

[msg MSG_006_1_0 [Sombra de Nakanohara]]
[s][bup 0 214 501 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Oye, 夷vosotros no despert茨is[n]los corazones de la gente?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]En ese caso...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]斡夷Por qu姻 no despert茨is[n]el coraz吋n de Madarame antes de que[n]haga da隠o a m茨s gente?![n][f 1 3 65535][w][e]

[msg MSG_006_3_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]夷Despertar... el coraz吋n de Madarame?[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Ryuji]]
[s][bup 0 2 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]夷Mmm? 夷Qu姻 es eso que brilla?[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Es la semilla de un tesoro.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]Si la hubi姻ramos dejado,[n]podr胤a haberse convertido[n]en un Palacio.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 17 65535 0]斡Joker, es la recompensa ideal![n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][bup 0 2 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Entonces, Nakanohara[n]ha despertado, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Seguramente.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Ann]]
[s][bup 0 4 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Pero 夷c吋mo vamos a saber[n]si hemos tenido 姻xito?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]La mujer public吋 el nombre del pavo[n]ese en internet. Si cambia,[n]seguro que vuelve a comentar.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Tienes raz吋n.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]斡En fin, entrenar contra sombras[n]es la ca隠a! 斡Es genial poder[n]prepararnos para lo que viene![n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Ann]]
[s][bup 0 4 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Tambi姻n mola infundir coraje[n]a aquellos que publican[n]sus problemas en internet.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]斡Y adem茨s, podemos vender[n]los tesoros que conseguimos[n]y ganar dinerito![n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 4 16 2 10 301 1 65535][vp 8 0 0 26 65535 0]斡Parece que todo[n]va a pedir de boca![n][f 1 3 65535][w][e]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]斡Muy bien, lo hemos conseguido![n][f 1 3 65535][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 28 65535 0]Un momento. Hay un sitio que os[n]quiero ense隠ar antes de irnos.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][bup 0 2 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]夷Eh, que hay m茨s?[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 30 65535 0]No tardaremos.[n][f 1 3 65535][w][e]

