[msg MSG_000_0_0 [Ryuji]]
[s][f 4 16 3 3 301 65535 65535][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Los Ladrones Fantasma viajando[n]en tren... Exactamente igual[n]que cuando vuelvo del instituto.[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]El tren es lo m茨s r茨pido.[n]Adem茨s, dejan viajar con mascotas.[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][f 4 16 3 3 301 1 65535][vp 8 0 0 3 65535 0]Oye, 斡夷a qui姻n llamas mascota?![n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]斡T胤o, c茨llate! No hemos[n]pagado el suplemento de mascota.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]斡Os estoy guiando[n]a vuestro destino![n]斡Deber胤ais llamarme 或Maestro位![n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Chica inocente]]
[s][vp 8 0 0 6 6 0]斡Hala, un gatito![n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Jol胤n...[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Chica inocente]]
[s][vp 8 0 0 8 6 0]夷Es suyo, se隠or?[n]斡Lo he o胤do maullar![n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]Es un peluche.[e]
[s]Te est茨s imaginando cosas.[e]
[s]Solo es una criatura.[e]

[msg MSG_009_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Es de juguete. Ma雨lla cuando se le[n]aprieta en la cabeza.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Chica inocente]]
[s][vp 8 0 0 10 6 0]Pero veo una cabeza asom茨ndose[n]de su mochila. 夷Es un gatito?[n][f 1 3 65535][w][e]

[msg MSG_011_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Es, eh... 斡un juguete! Ma雨lla cuando[n]le presionas la cabeza.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Chica inocente]]
[s][vp 8 0 0 12 6 0]夷Qu姻 es una cria... tura...?[n]夷Eso no es un gatito?[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Es, eh... 斡un juguete! Ma雨lla cuando[n]le presionas la cabeza.[n][f 1 3 65535][w][e]

[msg MSG_013_5_0 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Ya la has o胤do, [f 4 2].[n]Presi吋nale la cabeza.[n][f 1 3 65535][w][e]

[msg MSG_013_7_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 15 65535 0]Esto es rid胤...[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 16 65535 0]M-miauuu...[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Chica inocente]]
[s][vp 8 0 0 17 6 0]斡Halaaaaaa! 斡Otra vez! 斡Otra vez![n][f 1 3 65535][w][e]

[sel SEL_016_0_0 top]
[s]Deber胤a presionar con cuidado.[e]
[s]Presionar姻 con fuerza.[e]
[s]Voy a hacerlo papilla.[e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 8 0 0][f 4 10 65535 0 0][vp 8 0 0 18 65535 0]Prrrr...[n][f 1 3 65535][w][e]

[msg MSG_017_5_0 [Morgana]]
[s][bup 0 3 8 0 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]Miau, miau...[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Chica inocente]]
[s][vp 8 0 0 20 6 0]Ja, ja, ja, 斡qu姻 mono![n]斡Quiero o胤rlo otra vez![n][f 1 3 65535][w][e]

[msg MSG_018_5_0 [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]T胤o... El gato est茨 babeando...[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]斡夷Miau?![n][f 1 3 65535][w][e]

[msg MSG_019_5_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]斡Bleghhh![n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Chica inocente]]
[s][vp 8 0 0 24 6 0]Ja, ja, ja,[n]斡qu姻 gritito tan gracioso![n]斡Quiero o胤rlo otra vez![n][f 1 3 65535][w][e]

[msg MSG_020_5_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]S-siento... que voy a vomitar...[n][f 1 3 65535][w][e]

[msg MSG_020_7_0 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]斡Contente, memo![n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 0 0 27 65535 0]Miau... 斡Miau, miau, miau, miau![n][f 1 3 65535][w][e]
[s][vp 8 0 0 28 65535 0]...[n][f 1 3 65535][w][e]

[msg MSG_021_5_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 0 0 29 65535 0]斡Bleghhh![n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Chica inocente]]
[s][vp 8 0 0 30 6 0]Ja, ja, ja, 斡qu姻 gracioso![n]斡Quiero o胤rlo otra vez![n][f 1 3 65535][w][e]

[msg MSG_022_5_0 [Morgana]]
[s][bup 0 3 10 0 0][f 4 10 65535 0 0][vp 8 0 0 31 65535 0]Acabo de vomitar en mi boca...[n][f 1 3 65535][w][e]

[msg MSG_022_7_0 [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]夷En serio...?[n][f 1 3 65535][w][e]

[msg MSG_023_0_0 [Anuncio del tren]]
[s][vp 8 0 0 33 65535 0]La siguiente parada es Shibuya.[n]Shibuya. Las puertas se abrir茨n[n]por el lado izquierdo.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 34 65535 0]Ah, 斡esta es nuestra parada![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 35 65535 0]Bueno, 斡nos vemos! 斡Hasta luego![n][f 1 3 65535][w][e]

[msg MSG_025_0_0 [Chica inocente]]
[s][vp 8 0 0 36 65535 0]斡Vale! 斡Adi吋s![n][f 1 3 65535][w][e]

