[msg MSG_000_0_0 [Ann]]
[s][bup 0 4 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]Es tan extravagante... Hasta el punto[n]en que resulta de mal gusto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]Es un museo, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][bup 0 2 104 65535 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]夷Esto es de Madarame?[n][f 1 3 65535][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 4 65535 0]Bueno, un Palacio es un mundo fruto[n]de una mente retorcida por el deseo...[n]夷Recuerdas el castillo de Kamoshida?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ann]]
[s][bup 0 4 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 5 65535 0]Pero las obras de Madarame[n]ya se exponen en museos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]Su exposici吋n fue popular[n]y la gente ya lo respeta. Entonces,[n]夷por qu姻 fantasea con un museo?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][bup 0 2 107 65535 0][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Cierto... Y no parece estar[n]relacionado con plagios o abuso.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]Investiguemos un poco.[n]Estar aqu胤 quietos d茨ndole[n]al coco no servir茨 de nada.[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][bup 0 2 100 65535 0][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Cierto...[n][f 1 3 65535][w][e]

[msg MSG_006_5_0 [Ryuji]]
[s][bup 0 2 101 65535 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]Por cierto... 斡夷no es un museo[n]un lugar ideal para[n]los Ladrones Fantasma?![n][f 1 3 65535][w][e]

[sel SEL_007_0_0 top]
[s]S胤, sin duda.[e]
[s]Puede que tambi姻n haya trampas.[e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 11 65535 0]Ese es nuestro Joker.[n]Yo pienso igual.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][bup 0 2 107 65535 0][f 4 10 65535 0 0][vp 8 0 0 12 65535 0]S胤. Todos los fans de ese viejo[n]eran muy fuertes.[n][f 1 3 65535][w][e]

[msg MSG_010_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 13 65535 0]Eso no tiene nada que ver con esto.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][bup 0 2 103 65535 0][f 4 10 65535 0 0][vp 8 0 0 14 65535 0]Pero joder, mirad[n]a toda esa gente. Es una locura...[n][f 1 3 65535][w][e]

