[msg MSG_RESERVE]
[s]...[n][w][e]

[msg MSG_MORU_Q80_000_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1138 65535 0]斡Eh! Parece que Shibuya est茨 a tope[n]de estudiantes. 斡Quiz茨 podamos[n]obtener m茨s informaci吋n![n][w][e]

[msg MSG_E24420100_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]夷D吋nde estar茨 Ryuji?[n][w][e]

[msg MSG_E24420100_001_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Eh, qu姻 pronto hab姻is llegado.[n][w][e]

[msg MSG_E24420100_002_0_0 [E244_201]]
[s][vp 1 0 0 0 0 0]渋谷駅のアジトで竜司と合流。[n]目立つなどと考えていない竜司は制服のまま。[n][w][e]
[s][vp 1 0 0 0 0 0]キーフリーでJL線の改札まで歩き、[n]電車で新宿コマ劇前まで向かう。[n][w][e]

[msg MSG_E24420100_003_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Bueno, 斡v茨monos![n][w][e]

[msg MSG_E28510100_000_0_0]
[s][vp 1 0 0 0 0 0]e285_101[n]イセカイナビに情報を入力。[n]フタバパレスへ向かう怪盗団一行。[n][w][e]

[msg YOKOKU_RESERVE [Ryuji]]
[s][bup 0 2 0 65535 0]...[n][w][e]

[sel SEL_YOKOKU top]
[s]A por todas.[e]
[s]夷Est茨is todos preparados?[e]

[msg D03_YOKOKU_DAY_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][vp 1 0 0 1 0 0][f 4 10 65535 0 0]Hemos puesto el aviso[n]por todo Shibuya.[n][w][e]

[msg D03_YOKOKU_DAY_mes02 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Ha sido una buena idea, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Con toda esta teatralidad,[n]seguro que ya han avisado[n]a Kaneshiro.[n][w][e]

[msg D03_YOKOKU_DAY_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 4 0 0]斡Eres la cabeza pensante[n]de los Ladrones Fantasma![n]斡Ryuji, a ver si aprendes![n][w][e]

[msg D03_YOKOKU_DAY_mes04 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 23 1 2 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 5 0 0]Pero si yo los he estado[n]pegando por todos lados.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 6 0 0]斡Hasta tuve que disfrazarme[n]para que no me reconocieran![n][w][e]

[msg D03_YOKOKU_DAY_mes05 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 7 0 0]Venga, no tenemos tiempo[n]para estas tonter胤as.[n]V茨monos.[n][w][e]

[msg D03_YOKOKU_DAY_mes06 [Ann]]
[s][bup 0 4 2 65535 0][f 4 23 1 4 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 8 0 0]Esta vez nos enfrentamos[n]a un delincuente terrible.[n][w][e]

[msg D03_YOKOKU_DAY_mes07 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 23 1 2 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 9 0 0]斡Ese imb姻cil no nos va a parar[n]ahora que tenemos una[n]compa隠era nueva![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 10 0 0]斡Makoto! 夷Recuerdas c吋mo va esto?[n][w][e]

[msg D03_YOKOKU_DAY_mes08 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 11 0 0]Una vez que robamos el tesoro,[n]el Palacio se derrumba[n]y el se隠or del lugar despierta.[n][w][e]

[msg D03_YOKOKU_DAY_mes09 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 12 0 0]斡Lo has pillado r茨pido![n]Creo que a Ryuji todav胤a[n]le cuesta entenderlo...[n][w][e]

[msg D03_YOKOKU_DAY_mes10 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 13 0 0]Los adultos malvados son basura,[n]aunque yo no soy mucho mejor...[n]斡Prometo que acabar姻 con esto![n][w][e]

[msg D03_YOKOKU_DAY_mes11 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 14 0 0]斡Se te ve con ganas![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 15 0 0]斡Vale, Joker! 斡T雨 das la se隠al![n][w][e]

[msg D06_YOKOKU_DAY_mes01 [Haru]]
[s][bup 0 7 2 65535 0][f 4 23 1 7 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Ha llegado el d胤a.[n]夷Est茨is todos preparados?[n][w][e]

[msg D06_YOKOKU_DAY_mes02 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 23 1 9 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Makoto, 夷y el aviso?[n][w][e]

[msg D06_YOKOKU_DAY_mes03 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Se lo he ense隠ado a Sae.[n]Me lo quit吋 de las manos...[n][w][e]

[msg D06_YOKOKU_DAY_mes04 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 8 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 4 0 0]Makoto...[n][w][e]

[msg D06_YOKOKU_DAY_mes05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 23 1 5 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 5 0 0]Entiendo c吋mo te sientes,[n]pero no debes desanimarte.[n][w][e]

[msg D06_YOKOKU_DAY_mes06 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 23 1 2 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 6 0 0]Exacto... Si la cagamos ahora,[n]estamos acabados.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 7 0 0]Adem茨s de perder el lugar al que[n]pertenecemos, podr胤amos perder[n]nuestras vidas.[n][w][e]

[msg D06_YOKOKU_DAY_mes07 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 8 0 0]Va a salir todo bien. Quiero salvar[n]a mi hermana cueste lo que cueste.[n][w][e]

[msg D06_YOKOKU_DAY_mes08 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 9 0 0]夷Est茨is decididos?[n][w][e]

[msg D06_YOKOKU_DAY_mes09 [Ann]]
[s][bup 0 4 2 65535 0][f 4 23 1 4 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 10 0 0]斡S胤! 斡Bien est茨 lo que bien acaba![n][w][e]

[msg D06_YOKOKU_DAY_mes10 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 11 0 0]Han pasado muchas cosas desde[n]que empezamos. Ahora sois[n]todo un equipo, chicos.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 12 0 0]斡Vale, Joker! 斡Este es el[n]雨ltimo golpe de los Ladrones[n]Fantasma! 斡Danos la se隠al![n][w][e]

