[msg TEST_DUMMY]
[s]...[n][w][e]

[msg MSG_MORU_Q80_000_000 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]夷Qu姻 mejor sitio para buscar[n]estudiantes que un instituto?[n]斡A preguntar por Nagata![n][w][e]

[msg MSG_E150101_000_0_0 [Mishima]]
[s][bup 0 111 503 65535 0][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]Apuesto a que... Sakamoto va a buscar[n]al profesor Kamoshida.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]Probablemente est姻[n]en [clr 2]el despacho de Educaci吋n F胤sica[n]de la segunda planta[clr 27].[n][w][e]

[msg MSG_E150103_000_0_0 [Mishima]]
[s][bup 0 111 504 65535 0][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]斡Ha ido al despacho[n]de Educaci吋n F胤sica! R茨pido,[n]tenemos que ir tras 姻l.[n][w][e]

[msg MSG_E651103_START_01]
[s][vp 1 0 0 0 0 0]Esto parece el instituto.[n][w][e]

[msg MSG_E651103_START_02]
[s][vp 1 0 0 0 0 0]Tengo que irme a casa.[n][w][e]

[msg MSG_E651103_START [Megafon胤a del instituto]]
[s][vp 1 0 0 0 0 0]Se suspenden las clases.[n][w][e]
[s][vp 1 0 0 0 0 0]Se suspenden las clases.[n][w][e]
[s][vp 1 0 0 3 0 0]Repito...[n][w][e]

[msg MSG_E651103_RESTART_000 [Megafon胤a del instituto]]
[s][vp 1 0 0 0 0 0]Se suspenden las clases.[n][w][e]
[s][vp 1 0 0 0 0 0]Se ruega a los alumnos que est姻n[n]en el edificio que vuelvan[n]a sus casas lo antes posible.[n][w][e]
[s][vp 1 0 0 0 0 0]Repito...[n][w][e]

[msg MND_E651103_RESTART_010]
[s][vp 1 0 0 0 0 0]Es un anuncio que indica el fin[n]de la jornada escolar.[n][w][e]
[s][vp 1 0 0 0 0 0]Tengo que irme a casa.[n][w][e]

[msg MSG_E651103_START_A3_000]
[s][vp 1 0 0 0 0 0]校内には「速やかに下校の準備を~」などの[n]校内アナウンスや、丸城のカウンセリング中の[n]やり取りが怪盗団メンバーの声が流れている。[n][w][e]
[s][vp 1 0 0 0 0 0]その最中を玄関を目指して歩いてゆく...[n][w][e]

[msg MSG_E654102_003_00 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 1040 65535 0]夷En la enfermer胤a?[n]夷Qu姻 est茨 pasando aqu胤?[n][w][e]

[sel MSG_E654102_003_selA top]
[s]Esa mariposa...[e]
[s]Es igual que la de mi sue隠o.[e]

[msg MSG_E654102_003_01 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 53105 65535 0]Creo que somos los 雨nicos[n]que la vemos. Parece que[n]tiene una finalidad.[n][w][e]

[msg MSG_E654102_003_02 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]夷Tambi姻n aparece en tus sue隠os?[n]Qu姻 raro...[n]Bueno, no le des importancia.[n][w][e]

[msg MSG_E654102_003_03 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]No tiene sentido[n]pensar en eso ahora.[n]Vamos a la enfermer胤a, r茨pido.[n][w][e]

