[msg DUMMY_MSG]
[s]...[n][w][e]

[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg YUSUKE_0614_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]Hemos quedado delante del instituto[n]ma隠ana, 夷no? No te preocupes,[n]encontraremos algo nuevo.[n][w][e]

[msg YUSUKE_0614_1 [Yusuke]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]夷Me disculpas un momento?[n][w][e]

[sel SEL_YUSUKE_0614 top]
[s]夷Qu姻 pasa?[e]
[s]Claro...[e]

[msg YUSUKE_0614_2 [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Bueno, resulta que...[n][w][e]

[msg YUSUKE_0614_3 [Yusuke]]
[s][f 4 23 1 65535 3 10 0 0][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]Anhelaba ver el 或Sayuri位...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Si vas de camino a casa,[n]te acompa隠o.[n][w][e]

[msg MSG_MORU_Q80_000_000 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1138 65535 0]斡Eh! Parece que Shibuya est茨 a tope[n]de estudiantes. 斡Quiz茨 podamos[n]obtener m茨s informaci吋n![n][w][e]

[msg MSG_E19310100_001_00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]Bueno, 夷qu姻 l胤nea hay que coger?[n][w][e]

[msg MSG_E19310100_002_00 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]No parece que haya ninguna estaci吋n[n]cerca de esa direcci吋n...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]Si acaso, esta es[n]la estaci吋n m茨s cercana.[n][w][e]

[msg MSG_E19310100_003_00 [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]斡夷C吋mo?![n]斡夷Tenemos que seguir a pie?![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]斡夷Qu姻 clase de Ladr吋n Fantasma[n]coge el tren y luego[n]va andando hasta su destino?![n][w][e]

[msg MSG_E19310100_004_00 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Deja de quejarte.[n][w][e]

[msg MSG_E19310100_005_00 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]Se supone que es un cuchitril,[n]pero este es su vecindario...[n]Como se espera de un famoso.[n][w][e]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]Parece que el camino m茨s r茨pido es[n]ir por la plaza de la estaci吋n y[n]por la calle principal. 斡En marcha![n][w][e]

[msg MSG_E24420100_000_00 [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 7110 65535 0]夷No tienes ganas de ver c吋mo[n]es la vida nocturna en Shinjuku?[n][w][e]

[msg MSG_E24310100_001_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Ma隠ana reuniremos informaci吋n[n]en el instituto. Es tarde, as胤 que[n]muchos alumnos se habr茨n ido ya.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Pero ya que estamos en Shibuya,[n]reunamos informaci吋n aqu胤 tambi姻n.[n][w][e]

[sel SEL_E24310100_002_00 top]
[s]Esa era mi intenci吋n.[e]
[s]Qu姻 rollo.[e]

[msg MSG_E24310100_003_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]斡Genial! Por fin act雨as[n]como un l胤der, 夷eh?[n][w][e]

[msg MSG_E24310100_003_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]斡夷No puedes ponerle[n]un poquito de entusiasmo?![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]斡No tenemos mucho tiempo,[n]as胤 que vamos a darnos prisa[n]para sorprender a la se隠orita Ann![n][w][e]

[msg MSG_E24310100_004_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Shibuya es enorme, as胤 que hay[n]que reducir la b雨squeda. Si casi[n]todas las v胤ctimas son estudiantes...[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Miremos los lugares a los que[n]suelen ir, como el centro comercial[n]subterr茨neo o la calle principal.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Si encontramos a gente de[n]tu instituto, mataremos dos p茨jaros[n]de un tiro. Vamos all茨.[n][w][e]

