[msg MSG_JINBOUTYOU_START_1ST [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 1 1184 65535 0]斡Caray! 斡Qu姻 placer ver tantas[n]librer胤as juntas! Claro, esto es[n]Jinbocho, la ciudad de los libros.[n][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0]Ven, entremos en esta librer胤a.[n][w][e]

[msg MSG_JINBOUTYOU_START [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1162 65535 0]Aqu胤 hay much胤simos libros.[n]斡Qu姻 locura! Me siento abrumado[n]y emocionado a partes iguales.[n][w][e]

[sel BOOKSTORE_YESNO_SEL top]
[s]S胤.[f 2 7 0 0 106 1][e]
[s]No, gracias.[f 2 7 0 0 106 1][e]

[msg BOOKSTORE_START [Due隠o de librer胤a]]
[s]Hola... Uy, qu姻 joven eres,[n]comparado con la mayor胤a[n]de mis clientes.[n][w][e]
[s]Aqu胤 vendemos libros para expertos[n]y puede que sean bastante complicados[n]para un adolescente.[n][w][e]
[s]Te ofrecer姻 el libro m茨s sencillo[n]que tenemos. T吋mate tu tiempo[n]para leerlo, no tengas prisa.[n][w][e]

[msg BOOKSTORE_SELECT [Due隠o de librer胤a]]
[s]Hola...[n][w][e]

[msg MSG_BookStore_2nd [Due隠o de librer胤a]]
[s]Anda... 夷Sigues buscando algo?[n][w][e]

[msg MSG_BookStore_OpenLMAP [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]Muy bien, vamos a otro sitio.[n][w][e]

[msg BOOKSTORE_READ_01 [Due隠o de librer胤a]]
[s]Mmm, ya has acabado de leer[n][clr 3]或Maestro espadach胤n位[clr 27].[n]Muy impresionante dada tu juventud.[n][w][e]
[s]Bueno, te voy a vender otro libro.[n]*risita* Lo siento, parece[n]que te est姻 poniendo a prueba.[n][w][e]

[msg BOOKSTORE_READ_02 [Due隠o de librer胤a]]
[s]Mmm, ya has acabado de leer[n][clr 3]或Ll茨mame Jefe位[clr 27].[n]Muy impresionante dada tu juventud.[n][w][e]
[s]Entonces, permite que te ofrezca[n]otro libro que te pueda gustar.[n][w][e]

[msg BOOKSTORE_READ_03 [Due隠o de librer胤a]]
[s]夷Eh? Parece que has le胤do[n]todos los libros que hay aqu胤...[n]Te he subestimado, jovencito.[n][w][e]
[s]Mi mayor tesoro...[n]Quiz茨 no pase nada por vend姻rtelo.[n][w][e]

[msg BOOKSTORE_THANKS [Due隠o de librer胤a]]
[s]Gracias. Vuelve pronto.[n][w][e]

[msg BOOKSTORE_NOT_BUY [Due隠o de librer胤a]]
[s]Hasta la pr吋xima.[n][w][e]

[msg BOOKSTORE_SOLDOUT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷Mmm? 夷Has comprado lo que[n]te ha recomendado el due隠o?[n][w][e]

[msg MSG_BOOKSTORE_OUT [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]Ah, 夷quieres ir a otro sitio?[n][w][e]

[sel RETURN_SELECT_SEL top]
[s]Espera, se me ha olvidado una cosa.[f 2 7 0 0 106 1][e]
[s]Vamos a otra parte.[f 2 7 0 0 106 1][e]

[msg MSG_LMAP_RETURN [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0]夷Tienes que hacer algo[n]m茨s por aqu胤?[n][w][e]

