[msg TEST_DUMMY]
[s]...[n][w][e]

[msg MSG_MORU_Q80_000_000 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]夷Qu姻 mejor sitio para buscar[n]estudiantes que un instituto?[n]斡A preguntar por Nagata![n][w][e]

[msg MSG_E13710100_000_00 [Ryuji]]
[s][bup 0 2 205 65535 0][f 4 10 65535 0 0][vp 8 0 1 1 65535 0]Ese imb姻cil va de rey[n]aqu胤 tambi姻n...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]夷Que quiere conocernos m茨s?[n]Y una mierda. Lo ha hecho[n]para quedar bien y alimentar su ego.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 3 65535 0]夷Y ahora act雨a como si estuviera[n]preocupado por Mishima?[n]斡Pedazo de capullo abus吋n...![n][w][e]

[msg MSG_E13710100_000_03 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7187 65535 0]...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 4 65535 0]En fin...[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]Esta es nuestra oportunidad[n]de buscar a los esclavos[n]que vimos ayer.[n][w][e]

[msg MSG_E13710100_000_05 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 0 1 6 65535 0]Busquemos a quienes vimos[n]en el castillo. Hoy estar茨n aqu胤[n]todos los miembros del equipo.[n][w][e]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 0 1 7 65535 0]Seguro que encontrar姻 a alguien[n]que confiese el maltrato f胤sico[n]de Kamoshida. Ya ver茨s, capullo.[n][w][e]

[sel SEL_E13710100_001_00 top]
[s]夷D吋nde vas a buscar?[e]
[s]Muy bien, hasta luego.[e]
[s]No recuerdo sus caras...[e]

[msg MSG_E13710100_002_00 [Ryuji]]
[s][bup 0 2 204 65535 0][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]斡T雨 tambi姻n vienes conmigo![n][w][e]

[msg MSG_E13710100_003_00 [Ryuji]]
[s][bup 0 2 201 65535 0][f 4 10 65535 0 0][vp 8 0 1 9 65535 0]No te preocupes,[n]los recuerdo muy bien.[n][w][e]

[msg MSG_E13710100_004_00 [Ryuji]]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 0 1 10 65535 0]El primero que apareci吋 fue un t胤o[n]de la clase D,[n]as胤 que empecemos por ah胤.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]Esa es tu clase.[n][w][e]
[s][bup 0 2 203 65535 0][f 4 10 65535 0 0][vp 8 0 1 12 65535 0]Espero que no tengas problema[n]para hacer que hable. A m胤 la gente[n]me evita 雨ltimamente, as胤 que...[n][w][e]
[s][bup 0 2 200 65535 0][f 4 10 65535 0 0][vp 8 0 1 13 65535 0]Ah, pero t雨 est茨s m茨s o menos[n]en el mismo barco, claro.[n][w][e]

[msg MSG_E13720100_000_00 [Ryuji]]
[s][bup 0 2 203 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]T胤o, ojal茨 pudiera pillar a Mishima[n]y conseguir que hable ya.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Siempre acaba huyendo de m胤,[n]no s姻 por qu姻...[n][w][e]
[s][bup 0 2 200 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Como vais a la misma clase,[n]quiz茨 a ti te resultar胤a m茨s f茨cil[n]hablar con 姻l. 夷Puedes encargarte?[n][w][e]
[s][bup 0 2 204 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]斡Ah! 夷Estar茨 en la enfermer胤a?[n]Ese remate le dio en toda la cara.[n][w][e]
[s][bup 0 2 201 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Muy bien, ir姻 para all茨.[n]Tambi姻n le preguntar姻 a la gente[n]en el edificio de pr茨cticas.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si lo encuentro,[n]te aviso. Hasta luego.[n][w][e]

[msg MSG_E13910100_000_00 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si no nos damos prisa, Mishima[n]se ir茨 a casa. 斡Pill姻mosle[n]en la entrada del instituto![n][w][e]

