[msg MND_EVENT_YUSUKE_000_00]
[s][vp 8 2 65535 0 0 0]Veo a Yusuke a lo lejos. Parece[n]que est茨 observando un cuadro.[n][w][e]

[msg MND_EVENT_YUSUKE_001_00]
[s][vp 8 2 65535 0 0 0]夷Qu姻 hago?[n][w][e]

[sel SEL_EVENT_YUSUKE_001_00 top]
[s]Hablar con 姻l[e]
[s]Ir a otro sitio[e]

[msg MND_EVENT_NEXT_000_00]
[s][vp 8 2 65535 0 0 0]No veo a mis amigos por aqu胤.[n]Mejor voy a otro sitio.[n][w][e]

[msg MSG_KAWANABE_001_0_0 [Kawanabe]]
[s][vp 8 2 1 0 65535 0]夷[f 4 1]? Cu茨nto tiempo.[n][w][e]
[s][vp 8 2 1 0 65535 0]Me ha llamado Kitagawa.[n]Dice que ha encontrado[n]un nuevo tema sobre el que pintar.[n][w][e]

[sel SEL_KAWANABE_002_0_0 top]
[s]夷Qu姻 tema?[e]
[s]夷Te refieres a...?[e]

[msg MSG_KAWANABE_003_0_0 [Kawanabe]]
[s][vp 8 2 1 0 65535 0]No me ha comentado nada m茨s,[n]pero me ha dado a entender[n]que era la amistad o algo as胤.[n][w][e]

[msg MSG_KAWANABE_003_1_0 [Kawanabe]]
[s][vp 8 2 1 0 65535 0]No me ha comentado nada m茨s,[n]pero me ha dado a entender[n]que era la amistad o algo as胤.[n][w][e]

[msg MSG_KAWANABE_004_0_0 [Kawanabe]]
[s][vp 8 2 1 0 65535 0]*risita* Soy incapaz de ocultar[n]la emoci吋n. No es propio[n]de alguien de mi edad, pero bueno.[n][w][e]
[s][vp 8 2 1 0 65535 0]Seguro que me entiendes.[n]Haga lo que haga,[n]ser茨 una obra de arte.[n][w][e]
[s][vp 8 2 1 0 65535 0]Qu姻 ganas tengo[n]de que lo acabe para verlo.[n][w][e]

[msg MND_KAWANABE_010_0_0]
[s][vp 1 0 0 0 0 0]Deber胤a despedirme de Kawanabe[n]e irme a otro sitio.[n][w][e]

[msg MSG_KAWANABE_010_5_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1051 65535 0]Ya has hablado con Kawanabe.[n]Vamos a otro sitio.[n][w][e]

[msg MSG_KAWANABE_END [Kawanabe]]
[s][vp 8 2 1 0 65535 0]Puede mejorar como artista[n]porque tiene a alguien como t雨[n]que lo entiende.[n][w][e]
[s][vp 8 2 1 0 65535 0]Qu姻 ganas de ver su pr吋xima obra.[n]Seguro que es asombrosa.[n][w][e]

