[msg MSG_BLANK]
[s]...[n][w][e]

[msg AZITO_HIT_PC02_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]T胤o, con esta lluvia[n]me entra un bajonazo...[n]Bueno, 夷qu姻 hacemos hoy?[n][w][e]

[msg AZITO_HIT_PC02_mes02 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0]Mierda, est茨 lloviendo... En fin,[n]夷qu姻 vamos a hacer hoy?[n][w][e]

[msg AZITO_HIT_PC03_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]A pesar de la lluvia,[n]hemos venido todos.[n][w][e]

[msg AZITO_HIT_PC03_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0]A pesar de la lluvia,[n]hemos venido todos.[n][w][e]

[msg AZITO_HIT_PC04_mes01 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0]Est茨 lloviendo mogoll吋n.[n]Bueno, 夷qu姻 hacemos hoy?[n][w][e]

[msg AZITO_HIT_PC04_mes02 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0]Ah胤 est茨s. Vamos a hablar[n]aqu胤 debajo, para no mojarnos.[n][w][e]

[msg KAMOSHIDA_FIRST_mes01 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 23 1 2 3 5 11 5][vp 8 0 1 1 65535 0]Parece que ya estamos todos.[n][f 1 3 65535][w][e]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][vp 8 0 1 2 65535 0]斡Venga, a mover el culo![n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes02 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 23 1 3 3 5 11 5][vp 8 0 1 3 65535 0]Un momento, todav胤a es muy pronto[n]para ir al Palacio.[n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes03 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 23 1 2 3 5 11 5][vp 8 0 1 4 65535 0]Pero 夷por qu姻? 夷No tenemos[n]que robar el tesoro y ya?[n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes04 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 23 1 3 3 5 11 5][vp 8 0 1 5 65535 0]No subestimes los peligros[n]de ese lugar. Debemos prepararnos.[n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes05 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 10 65535 0 0][f 4 23 1 2 3 5 11 5][vp 8 0 1 6 65535 0]夷No basta con las Personas esas[n]que tenemos?[n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes06 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 23 1 3 3 5 11 5][vp 8 0 1 7 65535 0]A eso me refer胤a[n]con lo de que no lo subestimes.[n]Si metes la pata all胤, adi吋s.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 8 65535 0]Por eso digo que debemos[n]prepararnos antes de entrar.[n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes07 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 23 1 4 3 5 11 5][f 4 22 1 65535 3][vp 8 0 1 9 65535 0]Pero 夷c吋mo vamos a hacer eso?[n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes08 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 23 1 3 3 5 11 5][vp 8 0 1 10 65535 0]Buena pregunta, se隠orita Ann.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 11 65535 0]Primero, hay que encontrar equipamiento[n]mejor para todos.[n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes09 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][f 4 23 1 2 3 5 11 5][vp 8 0 1 12 65535 0]夷Te refieres a armas?[n]斡Conozco un sitio que te cagas![n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes10 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 23 1 3 3 5 11 5][vp 8 0 1 13 65535 0]En tal caso, t雨 te encargas de eso.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 1 14 65535 0]Lo otro es abastecernos[n]de medicinas. En un Palacio,[n]la fatiga es inevitable.[n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes11 [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][f 4 23 1 4 3 5 11 5][vp 8 0 1 15 65535 0]夷D吋nde conseguimos medicina?[n][f 1 3 65535][w][e]

[msg KAMOSHIDA_FIRST_mes12 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][f 4 23 1 3 3 5 11 5][vp 8 0 1 16 65535 0]No te preocupes, conozco el sitio perfecto.[n]斡Se隠orita Ann, espero haberte intrigado![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 1 17 65535 0]Bueno, [f 4 2] y yo[n]tenemos cosas que hacer en Yongen,[n]as胤 que v茨monos.[n][f 1 3 65535][w][e]

[sel KAMOSHIDA_FIRST_sel13 top]
[s]Eh... 夷qu姻 cosas?[e]
[s]Yo no tengo nada que hacer.[e]
[s]夷Nos vamos a casa?[e]

[msg KAMOSHIDA_FIRST_mes16 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][f 4 23 1 3 3 5 11 5][vp 8 0 1 18 65535 0]斡Ven conmigo! 斡No podr姻[n]acercarme lo suficiente yo solo![n][f 1 3 65535][w][e]

[msg MSG_MORU_Q80_000_000 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 1133 65535 0]夷Qu姻 mejor sitio para buscar[n]estudiantes que un instituto?[n]斡A preguntar por Nagata![n][w][e]

[msg YOKOKU_RESERVE [Ryuji]]
[s][bup 0 2 0 65535 0]...[n][w][e]

[sel SEL_YOKOKU top]
[s]A por todas.[e]
[s]夷Est茨is todos preparados?[e]

[msg D03_YOKOKU_DAY_mes01 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][vp 1 0 0 1 0 0][f 4 10 65535 0 0]Hemos puesto el aviso[n]por todo Shibuya.[n][w][e]

[msg D03_YOKOKU_DAY_mes02 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Ha sido una buena idea, 夷no?[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Con toda esta teatralidad,[n]seguro que ya han avisado[n]a Kaneshiro.[n][w][e]

[msg D03_YOKOKU_DAY_mes03 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 4 0 0]斡Eres la cabeza pensante[n]de los Ladrones Fantasma![n]斡Ryuji, a ver si aprendes![n][w][e]

[msg D03_YOKOKU_DAY_mes04 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 23 1 2 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 5 0 0]Pero si yo los he estado[n]pegando por todos lados.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 6 0 0]斡Hasta tuve que disfrazarme[n]para que no me reconocieran![n][w][e]

[msg D03_YOKOKU_DAY_mes05 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 7 0 0]Venga, no tenemos tiempo[n]para estas tonter胤as.[n]V茨monos.[n][w][e]

[msg D03_YOKOKU_DAY_mes06 [Ann]]
[s][bup 0 4 2 65535 0][f 4 23 1 4 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 8 0 0]Esta vez nos enfrentamos[n]a un delincuente terrible.[n][w][e]

[msg D03_YOKOKU_DAY_mes07 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 23 1 2 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 9 0 0]斡Ese imb姻cil no nos va a parar[n]ahora que tenemos una[n]compa隠era nueva![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 10 0 0]斡Makoto! 夷Recuerdas c吋mo va esto?[n][w][e]

[msg D03_YOKOKU_DAY_mes08 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 11 0 0]Una vez que robamos el tesoro,[n]el Palacio se derrumba[n]y el se隠or del lugar despierta.[n][w][e]

[msg D03_YOKOKU_DAY_mes09 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 12 0 0]斡Lo has pillado r茨pido![n]Creo que a Ryuji todav胤a[n]le cuesta entenderlo...[n][w][e]

[msg D03_YOKOKU_DAY_mes10 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 13 0 0]Los adultos malvados son basura,[n]aunque yo no soy mucho mejor...[n]斡Prometo que acabar姻 con esto![n][w][e]

[msg D03_YOKOKU_DAY_mes11 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 14 0 0]斡Se te ve con ganas![n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 15 0 0]斡Vale, Joker! 斡T雨 das la se隠al![n][w][e]

[msg D06_YOKOKU_DAY_mes01 [Haru]]
[s][bup 0 7 2 65535 0][f 4 23 1 7 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Ha llegado el d胤a.[n]夷Est茨is todos preparados?[n][w][e]

[msg D06_YOKOKU_DAY_mes02 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 23 1 9 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Makoto, 夷y el aviso?[n][w][e]

[msg D06_YOKOKU_DAY_mes03 [Makoto]]
[s][bup 0 6 0 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Se lo he ense隠ado a Sae.[n]Me lo quit吋 de las manos...[n][w][e]

[msg D06_YOKOKU_DAY_mes04 [Futaba]]
[s][bup 0 8 3 65535 0][f 4 23 1 8 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 4 0 0]Makoto...[n][w][e]

[msg D06_YOKOKU_DAY_mes05 [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 23 1 5 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 5 0 0]Entiendo c吋mo te sientes,[n]pero no debes desanimarte.[n][w][e]

[msg D06_YOKOKU_DAY_mes06 [Ryuji]]
[s][bup 0 2 2 65535 0][f 4 23 1 2 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 6 0 0]Exacto... Si la cagamos ahora,[n]estamos acabados.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 7 0 0]Adem茨s de perder el lugar al que[n]pertenecemos, podr胤amos perder[n]nuestras vidas.[n][w][e]

[msg D06_YOKOKU_DAY_mes07 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 23 1 6 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 8 0 0]Va a salir todo bien. Quiero salvar[n]a mi hermana cueste lo que cueste.[n][w][e]

[msg D06_YOKOKU_DAY_mes08 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 9 0 0]夷Est茨is decididos?[n][w][e]

[msg D06_YOKOKU_DAY_mes09 [Ann]]
[s][bup 0 4 2 65535 0][f 4 23 1 4 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 10 0 0]斡S胤! 斡Bien est茨 lo que bien acaba![n][w][e]

[msg D06_YOKOKU_DAY_mes10 [Morgana]]
[s][bup 0 3 2 0 0][f 4 23 1 3 3 5 11 5][f 4 10 65535 0 0][vp 1 0 0 11 0 0]Han pasado muchas cosas desde[n]que empezamos. Ahora sois[n]todo un equipo, chicos.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 12 0 0]斡Vale, Joker! 斡Este es el[n]雨ltimo golpe de los Ladrones[n]Fantasma! 斡Danos la se隠al![n][w][e]

