[msg dummy_mes]
[s]...[n][w][e]

[msg D01_01_e116_201af_mes01 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 2 1 1156 65535 0]No te quedes sin PS, 夷vale?[n]Puede que todav胤a tengamos[n]que luchar aqu胤.[n][w][e]

[msg D01_01_e116_201af_mes02 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0]Ah, y ll姻vate esto tambi姻n por si[n]lo necesitamos. Solo tenemos uno,[n]as胤 que ten cuidado, 夷vale?[n][w][e]

