[msg HELP_FOOL_OPEN [愚者 世直し怪盗団]]
[s]『愚者』属性のコープレーションである[n]『世直し怪盗団』とコープ契約を結んだ![n][w][e]

[msg HELP_FOOL_ARCANA_BONUS [合体ボーナス]]
[s][vp 8 0 0 0 65535 0]『愚者』属性のペルソナを合体で生み出す時に、[n]経験値のボーナスが入るようになった![n][f 1 3 65535][w][e]

[msg MIND_NAMEENTRY]
[s]どの名前にしようか...[n](α用仮処理。実際はネームエントリー)[n][w][e]

[sel MIND_NAMEENTRY_SEL top]
[s]自分で決める[e]
[s]ピンク・ダイアモンズ[e]
[s]アマダイノポワレシャンピニオンソース[e]

[msg MSG_053_0_0 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 63 65535 0]Hay miles de adultos corruptos...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 64 65535 0]夷Por qu姻 no nos centramos[n]en los peces gordos?[n][f 1 3 65535][w][e]

[sel SEL_054_0_0 top]
[s]夷Como un famoso?[e]
[s]夷Como un CEO?[e]
[s]夷Como un pez espada?[e]

[msg MSG_NOT_SELECT_PARA]
[s]...[n][w][e]
[s]No, mi [f 4 11 2][clr 26]Destreza[clr 27][n]tiene que ser al menos[n][clr 26]Aceptable[clr 27] para decir eso.[n][w][e]

[msg MSG_053_5_0 [Ryuji]]
[s][bup 0 2 0 65535 0][vp 1 0 0 0 0 0][f 0 6 255 0]夷Por qu姻 no nos centramos[n]en los peces gordos?[n][f 1 3 65535][e]

[msg SYS_NETWORK_CAUTION]
[s][vp 8 0 0 0 65535 0]El nombre de tu equipo ser茨 visible[n]cuando utilices internet.[n]No introduzcas datos personales.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Adem茨s, no uses palabras[n]que puedan considerarse ofensivas.[n][f 1 3 65535][w][e]

