[msg MSG_060_030_00_01_01 [Lavenza]]
[s][bup 0 100 4 0 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]斡Ese es mi Trickster![n][f 1 3 65535][w][e]

[msg MSG_060_030_00_02_01 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 2 65535 0]No me equivocaba contigo.[n][f 1 3 65535][w][e]

[msg MSG_060_030_00_03_01 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 3 65535 0]Vaya, vaya, menudo resultado.[n][f 1 3 65535][w][e]

[msg MSG_060_030_00_03_02 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Esta prueba[n]era extremadamente dif胤cil,[n]pero sab胤a que la superar胤as.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Gracias al poder que has conseguido[n]con tus incansables esfuerzos...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Seguramente podr茨s abrirte paso[n]al futuro.[n][f 1 3 65535][w][e]

[msg MSG_060_030_00_03_03 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Has derrotado al que evit吋[n]el fin de la humanidad.[n]Impresionante.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Has progresado mucho.[n]Tu fuerza est茨 a la altura[n]de los h姻roes del pasado.  [n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como encargada de guiar tus pasos,[n]no hay mayor honor para m胤[n]que presenciar tal magnificencia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mientras poseas este poder,[n]no cabe duda de que conseguir茨s[n]el futuro que deseas.[n][f 1 3 65535][w][e]

[msg MSG_060_030_00_03_04 [Lavenza]]
[s][bup 0 100 1 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Has derrotado al que[n]disip吋 un velo de neblina[n]insondable. Extraordinario.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Has progresado mucho.[n]Tu fuerza est茨 a la altura[n]de los h姻roes del pasado.  [n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Como encargada de guiar tus pasos,[n]no hay mayor honor para m胤[n]que presenciar tal magnificencia.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Mientras poseas este poder,[n]no cabe duda de que conseguir茨s[n]el futuro que deseas.[n][f 1 3 65535][w][e]

