[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_000_0_0]
[s]Dummy[n][w][e]

[msg MSG_E152101_007_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]Ay, qu姻 pe隠azo. En cualquier caso,[n]el instant茨neo y el de verdad[n]saben exactamente igual.[n][w][e]

[msg MSG_E152101_008_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 23 1 816 3 10 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]Eh... 夷Qu姻 quieres? Si te aburres,[n]ponte a fregar los platos o algo.[n][w][e]

[sel SEL_E152101_009_00 top]
[s]夷C吋mo va el negocio?[e]
[s]Qu姻 gran servicio...[e]

[msg MSG_E152101_010_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 23 1 816 3 10 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]Bien, como siempre.[n][w][e]

[msg MSG_E152101_010_01 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 23 1 816 3 10 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]Como siempre.[n][w][e]

[msg MSG_E152101_011_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]Mientras la cafeter胤a vaya bien, no importa.[n]No me gusta sonre胤r como un hip吋crita.[n][w][e]

[sel SEL_E152101_012_00 top]
[s]夷Ese es tu lema?[e]
[s]夷Y qu姻 pasa si deja de ir bien?[e]

[msg MSG_E152101_013_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 23 1 816 3 10 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]No, no tiene nada que ver con eso.[n][w][e]

[msg MSG_E152101_013_01 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 23 1 816 3 10 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]夷Qui姻n sabe? A lo mejor[n]acabo viviendo en la calle.[n][w][e]

[msg MSG_E152101_014_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 23 1 816 3 10 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]Mientras est姻 aqu胤,[n]el mundo me dejar茨 en paz.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]No hay asuntos ni personas[n]que me incordien. Es como[n]mi escondite personal.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]Si lo perdiera,[n]estar胤a muy jodido,[n]pero supongo que t雨 tambi姻n.[n][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]As胤 que al menos[n]deber胤as intentar ayudar un poco.[n][w][e]

[msg MSG_E152101_015_00 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]A partir de hoy, te har茨s cargo[n]de cerrar cuando llegue la hora.[n][w][e]
[s][f 4 10 65535 0 0][f 4 23 1 816 3 10 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]No me pienso quedar todos los[n]d胤as esperando a que vuelvas.[n][w][e]

[msg MSG_E152101_015_01]
[s]斡Has obtenido [f 2 5 3 9999 0]![n][w][e]

[msg TUTORIAL_GO_OUT_NIGHT]
[s]Ya puedes salir por la [clr 2]noche[clr 27].[n][w][e]

[msg MSG_E152101_015_02 [Sojiro]]
[s][bup 0 103 0 0 0][f 4 10 65535 0 0][f 4 23 1 816 3 10 0 0][vp 1 0 0 0 0 0][f 4 25 1 816 0 0]Tampoco es que haya nada que robar.[n]Mientras que no le prendas fuego...[n][w][e]

