[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_TEST_800]
[s]A la 2.鮎 planta del ala este[n][w][e]

[msg MSG_TEST_801]
[s]A la 1.鮎 planta (por la cafeter胤a)[n][w][e]

[msg MSG_TEST_802]
[s]A la 1.鮎 planta (por el patio)[n][w][e]

[msg MSG_TEST_803]
[s]A la 3.鮎 planta (por el patio)[n][w][e]

[msg MSG_TEST_804]
[s]A la 3.鮎 planta (por la cafeter胤a)[n][w][e]

[msg MSG_TEST_805]
[s]Entrada oeste: sala de profesores[n][w][e]

[msg MSG_TEST_806]
[s]Entrada este: sala de profesores[n][w][e]

[msg MSG_TEST_807]
[s]Despacho del director[n][w][e]

[msg MSG_TEST_808]
[s]Entrada sur al aula[n][w][e]

[msg MSG_TEST_809]
[s]Entrada norte al aula[n][w][e]

[msg MSG_029_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Joder, 斡no consigo dar con 姻l![n]夷Y t雨?[n][w][e]

[sel SEL_030_0_0 top]
[s]Todav胤a nada.[e]
[s]No lo s姻.[e]
[s]Me rindo.[e]

[msg MSG_031_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Uno de los chicos[n]al que maltrataron era[n]un atleta de tercer a隠o.[n][w][e]
[s][vp 1 0 0 0 0 0]No estaba aqu胤...[n]斡Prueba a mirar por las clases[n]de la primera planta![n][w][e]
[s][vp 1 0 0 0 0 0]Seguramente est姻 herido,[n]as胤 que deber胤amos verlo enseguida.[n][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]As胤 que t雨 tampoco tienes nada...[n][w][e]
[s][vp 1 0 0 0 0 0]Uno de los chicos[n]al que maltrataron era[n]un atleta de tercer a隠o.[n][w][e]
[s][vp 1 0 0 0 0 0]No estaba aqu胤...[n]斡Prueba a mirar por las clases[n]de la primera planta![n][w][e]
[s][vp 1 0 0 0 0 0]Seguramente est姻 herido,[n]as胤 que deber胤amos verlo enseguida.[n][w][e]

[msg MSG_033_0_0 [Ryuji]]
[s][vp 1 0 0 0 0 0]Venga, que te invito[n]a un gyuudon si me ayudas.[n][w][e]
[s][vp 1 0 0 0 0 0]Uno de los chicos[n]al que maltrataron era[n]un atleta de tercer a隠o.[n][w][e]
[s][vp 1 0 0 0 0 0]No estaba aqu胤...[n]斡Prueba a mirar por las clases[n]de la primera planta![n][w][e]
[s][vp 1 0 0 0 0 0]Seguramente est姻 herido,[n]as胤 que deber胤amos verlo enseguida.[n][w][e]

