[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_TEST_800]
[s]Salida del instituto[n][w][e]

[msg MSG_TEST_801]
[s]Acceso este (1.鮎 planta)[n][w][e]

[msg MSG_TEST_802]
[s]Al patio[n][w][e]

[msg MSG_TEST_803]
[s]A la 2.鮎 planta (por la cafeter胤a)[n][w][e]

[msg MSG_TEST_804]
[s]A la 2.鮎 planta (por el patio)[n][w][e]

[msg MSG_TEST_805]
[s]Recepci吋n[n][w][e]

[msg MSG_TEST_806]
[s]Tienda escolar[n][w][e]

