[msg DUMMY_MSG]
[s]...[n][w][e]

[msg MSG_CHK_YAMANOTE_LINE [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 0 0 0][vp 1 0 0 0 0 0]夷Por qu姻 no visitamos diferentes[n]lugares en tren cuando estemos[n]m茨s familiarizados con Tokio?[n][w][e]

[msg MSG_CHK_LOTTERY_SHOP_M01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 0 0 0][vp 1 0 0 0 0 0]Los Ladrones Fantasma de verdad[n]no lo dejan todo al azar, sino que[n]hacen que la suerte acuda a ellos.[n][w][e]

[msg MSG_CHK_LOTTERY_SHOP_01]
[s][vp 1 0 0 0 0 0]Si lo intentara una sola vez,[n]creo que ser胤a dif胤cil de detener.[n][w][e]

[msg MSG_TEST_PARAUP]
[s][vp 1 0 0 0 0 0]Si compro n雨meros de loter胤a que no[n]tengan pinta de salir ganadores,[n]creo que aumentar茨 mi [f 4 11 3][clr 26]Coraje[clr 27].[n][w][e]
[s][vp 1 0 0 0 0 0]夷Deber胤a comprar uno?[n][w][e]

[sel YESNO_SEL top]
[s]S胤[e]
[s]No[e]

[msg MSG_CHK_HUMAN_PARAUP]
[s][vp 1 0 0 0 0 0]夷Qu姻 estad胤stica quiero aumentar?[n][w][e]

[sel MSG_CHK_HUMAN_PARAUP_SEL top]
[s]Solo una estad胤stica[e]
[s]Dos o cuatro estad胤sticas[e]
[s]Todas las estad胤sticas[e]
[s]Un mensaje "?"[e]
[s]Cancelar[e]

[sel MSG_CHK_HUMAN_PARAUP_SEL_2 top]
[s]Autoestima[e]
[s]Atractivo f胤sico[e]
[s]Perspicacia[e]
[s]Coraje[e]
[s]Dignidad[e]
[s]Cancelar[e]

[sel MSG_CHK_HUMAN_PARAUP_SEL_3 top]
[s]Autoestima y perspicacia[e]
[s]Todo menos autoestima[e]
[s]Cancelar[e]

[msg MSG_CHK_HUMAN_PARAUP_NUM]
[s]Autoestima: [var 0], Atractivo f胤sico: [var 1][n]Perspicacia: [var 2], Coraje: [var 3][n]Dignidad: [var 4][n][w][e]

[msg CHK_HACHI_KOU_M01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 0 0 0][vp 1 0 0 0 0 0]As胤 que un perro que fue fiel[n]a su due隠o hasta el final...[n][w][e]
[s][f 4 10 0 0 0][vp 1 0 0 0 0 0]Prefiero vivir mi vida[n]con libertad, que para algo[n]es m胤a, 夷no?[n][w][e]

[msg CHK_HACHI_KOU_01]
[s][vp 1 0 0 0 0 0]Es el ep胤tome de un perro fiel.[n][w][e]

[msg CHK_SMOKE_SPACE_M01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 0 0 0][vp 1 0 0 0 0 0]斡Puf! *cof, cof*[n][w][e]
[s][f 4 10 0 0 0][vp 1 0 0 0 0 0]斡Salgamos de aqu胤,[n]este sitio es peligroso![n][w][e]

[msg CHK_SMOKE_SPACE_01]
[s][vp 1 0 0 0 0 0]Hay mucho humo. Es como[n]si estuviera rodeado de niebla.[n][w][e]

[msg MSG_FLD_ACT_011_NG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Tienes que seguir a Ryuji.[n]夷Qu姻 har茨s si lo pierdes?[n][w][e]

[msg MSG_FLD_ACT_015_YOSHIDA_ [Orador callejero]]
[s][bup 0 112 0 0 0][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 8 0 1 3 65535 0]斡Es hora de despertar! 斡El pa胤s est茨 podrido![n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]Aunque la sociedad japonesa sea[n]pr吋spera, los j吋venes no han tenido[n]tanta suerte como sus mayores.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]No tienen trabajo, ahorros,[n]ni ning雨n tipo[n]de seguridad econ吋mica.[n][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 9 65535 0]Estos j吋venes deber胤an abordar[n]su futuro de frente, pero bastante[n]tienen con intentar sobrevivir.[n][w][e]

[msg MSG_FLD_ACT_015_YOSHIDA__2 [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 0 1 5 65535 0]La gente da discursos todo el rato.[n]De todas formas, los pol胤ticos son aburridos.[n][w][e]

