[msg MSG_025_0_0 [Locutora adorable]]
[s][vp 8 0 0 37 12 0]Vale, vamos a preguntar[n]a este estudiante de aqu胤.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 38 12 0]Hipot姻ticamente, 夷qu姻[n]pensar胤as de los Ladrones[n]Fantasma si fueran reales?[n][f 1 3 65535][w][e]

[sel SEL_026_0_0 top]
[s]Son la justicia.[e]
[s]Son necesarios.[e]
[s]Hacen m茨s que los polis.[e]

[msg MSG_NOT_SELECT_PARA]
[s]...[n][w][e]
[s]No, mi [f 4 11 0][clr 26][f 4 12 0][clr 27] tiene que ser al menos[n][clr 26]Acad姻mico[clr 27] para decir eso.[n][w][e]

[msg MSG_025_5_0 [Locutora adorable]]
[s][vp 1 0 0 0 0 0][f 0 6 255 0]Hipot姻ticamente, 夷qu姻 pensar胤as[n]de los Ladrones Fantasma[n]si fueran reales?[n][f 1 3 65535][e]

[msg TEST_MINE]
[s]Parece que he perfeccionado[n]mi [f 4 11 3][clr 26][f 4 12 3][clr 27].[n][w][e]

[msg TEST_MINE2]
[s]斡Ahora puedo afrontar[n]desaf胤os mayores![n][w][e]

