[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]Se acercan los ex茨menes, 夷no?[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]Deber胤as estudiar de vez en cuando.[n]斡Estudiemos juntos![n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Estoy en Yongen-Jaya.[n]Av胤same si vas a venir.[n][f 5 15][w][e]

[msg MSG_REACTION [Futaba]]
[s][f 5 14]Vale. Aqu胤 te espero.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Bueno, 夷entonces qu姻?[n]夷Quieres ir a ver a Futaba?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Responder luego[e]

[sel SEL_002 top]
[s][f 5 14]Ahora mismo voy.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]Deber胤a poder mejorar[n]nuestro v胤nculo ya que tengo[n]a [clr 1][var 5][clr 27] del arcano [var 2]...[n][w][e]

