[msg MSG_000_0_0 [Yoshida]]
[s][f 5 14]Como hoy es fiesta, creo que[n]voy a dar un discurso m茨s largo.[n][w][e]

[msg MSG_001_0_0 [Yoshida]]
[s][f 5 14]Ser茨 delante de la estaci吋n de[n]Shibuya, como de costumbre.[n][w][e]

[msg MSG_002_0_0 [Yoshida]]
[s][f 5 14]Estar胤a bien que me ayudases.[n]夷Qu姻 te parece?[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Yoshida te est茨[n]esperando delante de la estaci吋n.[n]夷Quieres ir?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Ahora mismo voy.[e]

[msg MSG_REACTION [Yoshida]]
[s][f 5 14]Nos vemos delante[n]de la estaci吋n.[n][f 5 15][w][e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Yoshida te est茨[n]esperando delante de la estaci吋n.[n]夷Quieres ir?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Parece que Yoshida te est茨[n]esperando delante de la estaci吋n.[n]夷Quieres ir?[n][f 1 3 65535][w][e]

