[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Deber胤a despertar pronto...[n]Me pregunto qu姻 va a pasar.[n][w][e]

[msg MSG_000_1_0 [Ann]]
[s][f 5 14]Deber胤a despertar pronto...[n]Me pregunto qu姻 va a pasar.[n][w][e]

[msg MSG_000_2_0 [Ann]]
[s][f 5 14]Deber胤a despertar pronto...[n]Me pregunto qu姻 va a pasar.[n][w][e]

[msg MSG_000_3_0 [Ann]]
[s][f 5 14]Deber胤a despertar pronto...[n]Me pregunto qu姻 va a pasar.[n][w][e]

[msg MSG_000_4_0 [Ann]]
[s][f 5 14]Deber胤a despertar pronto...[n]Me pregunto qu姻 va a pasar.[n][w][e]

[msg MSG_000_5_0 [Ann]]
[s][f 5 14]Deber胤a despertar pronto...[n]Me pregunto qu姻 va a pasar.[n][w][e]

[msg MSG_000_6_0 [Ann]]
[s][f 5 14]Deber胤a despertar pronto...[n]Me pregunto qu姻 va a pasar.[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Oye, me resulta dif胤cil[n]mantener la calma, as胤 que[n]夷te apetece hablar de algo?[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Estoy en la clase.[n][f 5 15][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Estoy en el centro comercial[n]subterr茨neo de Shibuya.[n][f 5 15][w][e]

[msg MSG_REACTION [Ann]]
[s][f 5 14]Vale, te estar姻 esperando.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Bueno, 夷entonces qu姻?[n]夷Quieres ir a ver a[n]la se隠orita Ann?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Responder luego[e]

[sel SEL_002 top]
[s][f 5 14]Ahora mismo voy.[e]

