[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]T胤o, ser胤a un marr吋n[n]que esa foto saliera a la luz...[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]夷A qu姻 viene eso ahora?[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]No s姻. Ni que hubi姻ramos[n]hecho algo malo...[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Est茨bamos en el sitio equivocado[n]en el momento equivocado.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Mmm, s胤. Ese es el problema.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]夷Crees que la gente no comprender茨[n]lo que ha pasado[n]aunque intentemos explicarlo?[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Mmm...[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Creo que ser茨 dif胤cil.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Estoy de acuerdo.[n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Dudo que la gente quiera escuchar[n]lo que tengamos que decir.[n][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]Si esa foto sale a luz,[n]la gente se tomar茨 a chiste[n]cualquier cosa que digamos.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Si llegamos a eso,[n]de chiste no tendr茨 nada...[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Entonces no nos queda otra[n]que despertar su coraz吋n.[n][w][e]

