[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Kaneshiro se libr吋[n]de las fotos, 夷no?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Eso dijo.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]夷Crees que podemos fiarnos de 姻l?[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Dudo que mintiese si de verdad[n]ha despertado.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Parece que todo est茨 bien.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Yo no lo dir胤a tan deprisa.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]夷Quieres decir que a lo mejor[n]no ha despertado?[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]No, estoy bastante seguro[n]de que s胤. El problema no es ese.[n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]Aunque Kaneshiro ha despertado,[n]su organizaci吋n sigue intacta.[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Solo espero que no huyan[n]con las fotograf胤as.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Podr胤amos robarlas.[n]Supongo que es posible...[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Despu姻s de todo, perder a un l胤der[n]no supone que un grupo se disuelva.[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14]Lo sabe todo el mundo.[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14]Pero tambi姻n puede[n]pasar todo lo contrario.[n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14]Si un grupo no tiene un gu胤a[n]fuerte, se desmoronar茨.[n][w][e]

[msg MSG_015_0_0 [Ann]]
[s][f 5 14]As胤 que todo depende de[n]c吋mo salga la cosa...[n][w][e]

[sel SEL_016_0_0 top]
[s][f 5 14]Nos ir茨 bien.[e]
[s]Estoy preocupado...[e]

[msg MSG_017_0_0 [Makoto]]
[s][f 5 14]Solo podemos rezar para que[n]sea a nuestro favor.[n][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][f 5 14]Con suerte, la confesi吋n de[n]Kaneshiro animar茨 a la polic胤a[n]a perseguir a la mafia.[n][w][e]

[msg MSG_019_0_0 [Yusuke]]
[s][f 5 14]Nada me gustar胤a m茨s que[n]verlos caer de una vez por todas.[n][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]Todo depende[n]de la hermana de Makoto.[n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][f 5 14]Aparte de eso, hemos hecho[n]todo lo que hemos podido.[n][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][f 5 14][f 5 15]Ya solo nos queda esperar[n]hasta que tengamos los resultados.[n][w][e]

