[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]No dejan de escribir publicaciones[n]rar胤simas en la Fansite.[n][w][e]
[s][f 5 14]或Mi madre est茨 rara位.[n]或Estoy solo y tengo hambre位.[n][w][e]
[s][f 5 14]或夷Es que no puede verme?位[n]或No me responde位.[n][w][e]
[s][f 5 14]或La casa est茨 patas arriba位.[n]或Todo est茨 hecho un asco位.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]夷Crees que es real?[e]
[s]Merece la pena investigar.[e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Yo tambi姻n dud姻, pero[n]parecen gritos de ayuda.[n]No creo que sea ninguna broma.[n][w][e]
[s][f 5 14]Me suena a abandono o,[n]directamente, a malos tratos.[n][w][e]
[s][f 5 14]As胤 que...[n][w][e]
[s][f 5 14]Me puse a investigar[n]y consegu胤 m茨s informaci吋n.[n][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][f 5 14]Sab胤a que dir胤as eso,[n]as胤 que consegu胤 m茨s informaci吋n[n]por adelantado.[n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]Pone que la due隠a registrada[n]del m吋vil es 或Kuniko Kagami位.[n][w][e]
[s][f 5 14]La ni隠a debe de publicarlo todo[n]desde el m吋vil de su madre.[n][w][e]
[s][f 5 14]Ya he comprobado el nombre en[n]el Meta-Nav y hay un resultado.[n][w][e]
[s][f 5 14]Creo que est茨 claro[n]que est茨 desatendiendo a su hija.[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Buen trabajo.[e]
[s]Te has pasado.[e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]Je, je. No, no he hecho gran cosa.[n]Solo... ya sabes, todo.[n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]Mira, no puedo ignorarlo.[n][w][e]
[s][f 5 14]夷Y si le ha pasado algo y nunca[n]llegaron a resolverlo?[n]夷Y si ha tenido un accidente?[n][w][e]
[s][f 5 14]Lo siento...[n][w][e]
[s][f 5 14]Pero...[n][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][f 5 14]Creo que un ni隠o nunca[n]deber胤a sentir que no le importa[n]a su madre.[n][w][e]
[s][f 5 14]Quiero hacerla entrar en raz吋n.[n][w][e]
[s][f 5 14][f 5 15]Hablemos del tema[n]en el escondite, 夷de acuerdo?[n][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si ya tenemos un resultado[n]en Mementos, no podemos ignorarlo.[n][f 1 3 65535][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Y por las publicaciones, parece que[n]la v胤ctima es una ni隠a peque隠a.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Hay much胤sima gente por ah胤[n]que nos necesita. 斡Vamos[n]a ver si podemos echar una mano![n][f 1 3 65535][w][e]

