[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]夷Se te ha olvidado la fecha[n]l胤mite? Del Palacio, digo.[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]Av胤same si vamos a ir hoy.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Bueno, 夷qu姻 quieres hacer?[n]夷Nos vemos en el escondite[n]y vamos al Palacio?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Reunirse[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Vamos al Palacio.[e]

[msg MSG_REACTION [Futaba]]
[s][f 5 14]O胤do cocina.[n][w][e]

[msg MSG_REACTION_02 [Futaba]]
[s][f 5 14]Se lo dir姻 a los dem茨s.[n]Vente, [f 4 2].[n][f 5 15][w][e]

