[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Record茨is que vamos a la[n]televisi吋n ma隠ana, 夷no?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Creo que all胤 encontraremos[n]al siguiente objetivo.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]斡Es verdad![n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Siempre se oyen rumores[n]sobre el lado oscuro[n]de los famosos.[n][w][e]

[sel SEL_004_0_0 top]
[s][f 5 14]Nunca lo hab胤a o胤do.[e]
[s]Tienes toda la raz吋n.[e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Con toda esta pasta, fijo[n]que est茨n de mierda[n]hasta las trancas.[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]Mmm...[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Ese modo de expresarse[n]es un poco inmoral...[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]T胤o, te fijas en unas[n]cosas superraras.[n][w][e]

[msg MSG_009_0_0 [Ann]]
[s][f 5 14]En fin, veremos la grabaci吋n de[n]un programa en directo, 夷no?[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]斡Puede que salgamos en la tele![n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]Solo vamos de p雨blico.[n]Si salimos, ser茨 como[n]mucho dos segundos.[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Procurad no hacer ning雨n movimiento[n]sospechoso que llame la atenci吋n,[n]夷vale?[n][w][e]

