[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]Te he tra胤do informaci吋n[n]de primera. 夷Quieres saber qu姻 es?[n][w][e]
[s][f 5 14]Al parecer, hay un viejo[n]armando foll吋n en Kichijoji.[n][w][e]
[s][f 5 14]Si haces movimientos raros[n]o dices algo que no le gusta,[n]se le va la olla y monta un pollo.[n][w][e]
[s][f 5 14]E incluso si no lo atacas,[n]se lo inventa y te denuncia[n]por da隠os y perjuicios.[n][w][e]
[s][f 5 14]斡Es un embustero de tomo y lomo![n]Un artista del conflicto.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Vaya ridiculez.[e]
[s]夷Y la polic胤a?[e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Estoy de acuerdo.[n]Hay que pararle los pies.[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]A ver,[n]ya le han llamado la atenci吋n...[n][w][e]
[s][f 5 14]Pero hace como que est茨 senil[n]y se sale con la suya.[n][w][e]
[s][f 5 14]No podemos pasarlo por alto, 夷no?[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]La 雨nica pega es que[n]no es m茨s que un viejales liante.[n]No nos va a dar cach姻.[n][w][e]
[s][f 5 14][f 5 15]Tengo entendido que frecuenta[n]el callej吋n Harmony de Kichijoji.[n][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]Ese anciano es un problem吋n.[n][f 1 3 65535][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero, si no sabemos su nombre,[n]no podemos despertar su coraz吋n.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Nuestra siguiente parada[n]es Kichijoji. 斡Al callej吋n Harmony![n][f 1 3 65535][w][e]

