[msg MSG_000_0_0 [Haru]]
[s][f 5 14]La fiesta de despu姻s del festival[n]est茨 a punto de empezar.[n]夷Quieres que vayamos juntos?[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]He intentado pensar en lo que[n]pas吋 antes, pero no[n]he sacado nada en claro...[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Me ir胤a bien un cambio[n]de aires. 夷Qu姻 te parece?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Claro, vamos.[e]

[msg MSG_020_0_0 [Haru]]
[s][f 5 14]斡Gracias![n][w][e]

[msg MSG_021_0_0 [Haru]]
[s][f 5 14]Te estar姻 esperando en el gimnasio.[n][f 5 15][w][e]

