[msg MSG_000_0_0 [Kawakami]]
[s][f 5 14]夷Te pasa algo?[n][w][e]

[msg MSG_001_0_0 [Kawakami]]
[s][f 5 14]Hoy no tengo clientes, [n]as胤 que si me llamas, voy.[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Kawakami parece aburrida...[n]夷Qu姻 opinas? 夷Deber胤amos llamarla?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Llamarla[e]
[s]Responder luego[e]

