[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Oye, 夷no cre姻is que ha[n]cambiado el ambiente[n]en el insti?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]夷Lo dices porque ya[n]no est茨 Kamoshida?[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Exacto. Antes nadie[n]hablaba de 姻l tan[n]abiertamente.[n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]Es verdad.[e]
[s]Te lo est茨s imaginando.[e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]No estar胤a mal que alguien[n]nos lo agradeciese.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Bah, suda. El caso es que[n]la situaci吋n ha mejorado[n]gracias a nosotros.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Sea como fuere, todo ha salido[n]a pedir de boca.[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Despu姻s de todo, Kamoshida[n]ha pagado por sus delitos.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Para m胤, ya es victoria suficiente.[n][w][e]

[sel SEL_009_0_0 top]
[s][f 5 14]Estoy de acuerdo.[e]
[s]夷T雨 crees?[e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]No, es m茨s que eso.[n]Sienta de lujo.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]A saber qu姻 ser茨 de 姻l[n]a partir de ahora.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Al fin y al cabo,[n]ya es un criminal reconocido, 夷no?[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]No le queda otra que tragar[n]con el odio de la gente.[n][w][e]

[msg MSG_014_0_0 [Ann]]
[s][f 5 14]Puede, pero no me[n]da ninguna pena.[n][w][e]

[msg MSG_015_0_0 [Ann]]
[s][f 5 14]Tiene lo que se merece.[n][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Claro.[n][w][e]

