[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Ha llegado la hora.[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Pase lo que pase,[n]hay que despertar su coraz吋n.[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]S胤.[e]
[s]No hay que precipitarse.[e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Cuento contigo.[n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]S胤, lo entiendo.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Todos tenemos nuestra forma[n]de hacer las cosas.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Pero debemos proceder[n]como siempre.[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Yo me encargo.[e]
[s]夷Como siempre?[e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]No te preocupes, [f 4 2].[n]Conf胤o en ti.[n][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]No paro de dec胤rmelo.[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14]Sinceramente, no creo que pueda[n]mantener la calma esta vez.[n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14][f 5 15]Por eso te pido que[n]me eches una mano.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1190 65535 0]Tampoco hay necesidad de[n]precipitarse por esto, 夷no?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]T吋mate el tiempo que necesites[n]para prepararte. Cualquier cosa[n]sirve si nos ayuda en la misi吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Confiamos en ti.[n]Al fin y al cabo, eres el l胤der.[n][f 1 3 65535][w][e]

