[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Mmm, Kaneshiro a雨n[n]no ha dado se隠ales[n]de cumplir su amenaza.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Probablemente piensa que el grifo[n]del dinero sigue abierto.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Despu姻s de todo, 姻l es quien tiene[n]ventaja sobre nosotros...[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Si esa foto viera la luz,[n]qui姻n sabe lo que ocurrir胤a[n]con [f 4 2]...[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]En el peor de los casos,[n]lo expulsar胤an.[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]No, hay una alternativa peor...[n]Ahora tiene la condicional,[n]lo que significa...[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Lo siento mucho.[n]Todo esto es por mi culpa.[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Venga, ya vale.[n]Ahora mismo t雨 eres quien[n]tiene el problema m茨s gordo.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Mi hermana es fiscal...[n]Esto tambi姻n ser茨 un problema[n]para ella. 夷Qu姻 deber胤a hacer?[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Seguro que Kaneshiro tambi姻n[n]ha tenido eso en cuenta...[n][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Tenemos que detenerlo.[e]
[s]Despertemos su coraz吋n.[e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]Por supuesto. Hasta la polic胤a[n]tiene problemas con ese gilipollas.[n]斡Si lo capturamos, seremos h姻roes![n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]A mayor riesgo, mayor recompensa...[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14]Qu姻 optimistas...[n][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][f 5 14]Mmm... En cierto modo, tu temeridad[n]es la raz吋n por la que podemos[n]intentar despertar su coraz吋n.[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Claro que s胤. Estamos en la mierda,[n]as胤 que tenemos que hacer todo[n]lo posible por salir del agujero.[n][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][f 5 14]No me lo hab胤a planteado as胤...[n][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][f 5 14]Es raro escuchar algo tan positivo[n]de boca de Ryuji.[n][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][f 5 14]斡Cierra el pico![n][w][e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14][f 5 15]斡De acuerdo, l胤der![n]斡Puedes decidir cu茨ndo quedamos![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Cuando tu posici吋n cambia, tambi姻n[n]lo hace tu perspectiva del mundo.[n]Es un cambio de cognici吋n.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]De todas formas, si no conseguimos[n]despertar el coraz吋n de Kaneshiro,[n]estaremos en apuros. 斡Vamos all茨![n][f 1 3 65535][w][e]

