[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]夷Es cosa m胤a o se est茨n filtrando[n]cosas por un tubo 雨ltimamente?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]No es cosa de Medjed, 夷verdad?[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]Creo que ellos lo har胤an[n]de una forma mucho m茨s teatral.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]斡Es verdad! 斡No han hecho[n]declaraciones ni nada![n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]Aun as胤...[n]es un quebradero de cabeza.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Y en internet nos tienen[n]una tirria que no veas. La gente[n]se cree que todo es culpa nuestra.[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]Quiz茨 nos acusen si no hacemos[n]algo r茨pido al respecto.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]夷A alguien se le ha ocurrido algo[n]para resolver el problema?[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]A雨n no.[e]
[s]Necesito algo m茨s de tiempo.[e]
[s]No hay esperanza...[e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Bueno, voy a seguir intent茨ndolo.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Lo mismo digo.[n]Quiero hacer todo lo posible.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]No podemos desistir todav胤a.[n]Hay que intentar abordarlo[n]desde diferentes perspectivas.[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]Tenemos que hacer todo lo posible.[n][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][f 5 14]Sea como sea,[n]no bastar茨 con confiar en Futaba.[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14][f 5 15]A ver, si nos quedamos[n]sin opciones, no habr茨 elecci吋n...[n][w][e]

