[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]夷El instituto siempre ha sido as胤?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]夷No cre姻is que algo ha cambiado?[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]夷T雨 crees?[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Yo tambi姻n noto algo raro.[n][w][e]

[msg MSG_004_0_0 [Haru]]
[s][f 5 14]夷Por qu姻 lo dices?[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]Es como si la gente estuviera[n]inquieta o algo as胤.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Es muy raro, 夷verdad?[n][w][e]

[sel SEL_007_0_0 top]
[s][f 5 14]Creo que no ha cambiado nada.[e]
[s]Hay algo diferente.[e]

[msg MSG_008_0_0 [Haru]]
[s][f 5 14]Estoy de acuerdo.[n][w][e]

[msg MSG_009_0_0 [Haru]]
[s][f 5 14]夷Solo yo pienso[n]que nada ha cambiado?[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]Yo no noto nada raro.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]夷Y t雨, Makoto?[n][w][e]

[msg MSG_012_0_0 [Futaba]]
[s][f 5 14]夷Alguien ha preguntado por m胤?[n][w][e]

[msg MSG_013_0_0 [Futaba]]
[s][f 5 14]Todo normal por aqu胤.[n][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][f 5 14]Estoy seguro de que[n]nadie ha preguntado por ti.[n][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][f 5 14]夷Le pasa algo hoy a Makoto?[n][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][f 5 14]Lo siento, acabo de ver[n]la conversaci吋n.[n][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][f 5 14]Todo el mundo est茨 inquieto por los[n]rumores de los Ladrones Fantasma.[n][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][f 5 14]Intentad que no os afecte[n]lo que diga la gente.[n][w][e]

[msg MSG_019_0_0 [Futaba]]
[s][f 5 14][f 5 15]斡Es importante mantener la calma[n]en un momento as胤![n][w][e]

