[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]夷C吋mo vamos a proceder[n]con el siguiente objetivo?[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Qu姻 repentino...[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Despu姻s de lo que dijo ese tipo,[n]斡me jode quedarme sentado de[n]brazos cruzados![n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Hablas de Akechi, 夷no?[n]S姻 c吋mo te sientes.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Ah, el detective de instituto ese.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Si despertamos otro coraz吋n,[n]tendr茨 que callarse la boca.[n][w][e]

[sel SEL_006_0_0 top]
[s][f 5 14]Puede.[e]
[s]夷T雨 crees?[e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]斡Totalmente![n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]斡Venga, hay que afrontar[n]esto con m茨s confianza![n][w][e]

[msg MSG_009_0_0 [Ann]]
[s][f 5 14]Pero dijo que la polic胤a hab胤a[n]empezado a movilizarse...[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Aun as胤, no podemos dejarle[n]hacer lo que le d姻 la gana.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Es el momento perfecto para[n]reunirse y hablar sobre qu姻[n]estrategia seguir.[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Nos vemos ma隠ana[n]en el escondite.[n][w][e]

