[msg MSG_000_0_0 [Hanasaki]]
[s][f 5 14]Hola, soy Hanasaki,[n]de la florister胤a Rafflesia.[n][w][e]

[msg MSG_001_0_0 [Hanasaki]]
[s][f 5 14]Perd吋n por la molestia, pero[n]夷podr胤as venir a trabajar?[n][w][e]

[msg MSG_002_0_0 [Hanasaki]]
[s][f 5 14]Hoy hemos puesto descuentos[n]y no s姻 si podr姻[n]yo sola con todo el gent胤o.[n][w][e]

[msg MSG_003_0_0 [Hanasaki]]
[s][f 5 14]斡Te llevar茨s dinerillo[n]extra si vienes![n][w][e]

[msg MSG_004_0_0 [Hanasaki]]
[s][f 5 14]Avisa si puedes venir, 夷vale?[n][f 5 15][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1187 65535 0]夷Te va a tocar preparar ramos?[n]Puedes aprovechar para mejorar[n]tu [f 4 11 4][clr 26][f 4 12 4][clr 27].[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Si no tienes nada m茨s que hacer,[n]podr胤as ayudarla. Como t雨 veas.[n][f 1 3 65535][w][e]

