[msg MSG_000_0_0 [Haru]]
[s][f 5 14]No traigo muchas novedades...[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Pero creo que ma隠ana[n]volver姻 al instituto.[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Perd吋n por preocuparos a todos.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]夷De verdad que est茨s bien?[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]No te fuerces mucho en un[n]momento de luto como este.[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]Es que tengo que forzarme.[n]Le doy muchas vueltas si no[n]tengo nada que hacer...[n][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]Ya, te entiendo.[n][w][e]

[msg MSG_007_0_0 [Haru]]
[s][f 5 14]Adem茨s, no tengo nada[n]que hacer en casa.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Bueno, pues... no s姻 c吋mo decirlo,[n]pero intenta no darle muchas[n]vueltas.[n][w][e]

[sel SEL_009_0_0 top]
[s][f 5 14]Nos tienes aqu胤 para lo que sea.[e]
[s]Estamos contigo, Haru.[e]

[msg MSG_0010_0_0 [Ann]]
[s][f 5 14]S胤, 斡puedes pedirnos lo[n]que sea sin problema![n]Estamos aqu胤 para ti.[n][w][e]

[msg MSG_010_0_1 [Ann]]
[s][f 5 14]S胤, 斡cuenta con nosotros[n]para lo que sea![n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14]Pues... para ser sincera...[n][w][e]

[msg MSG_012_0_0 [Haru]]
[s][f 5 14]Cuando me vi sola, s胤 que dud姻[n]un poco de vosotros.[n][w][e]

[msg MSG_014_0_0 [Haru]]
[s][f 5 14]Pero es horrible que haya dudado[n]de vosotros. O sea, fui yo la que[n]os pidi吋 que lo hicierais.[n][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][f 5 14]Tu padre acaba de fallecer, Haru.[n]Es normal que sientas una avalancha[n]de emociones en estos momentos.[n][w][e]

[msg MSG_016_0_0 [Futaba]]
[s][f 5 14]S胤, perder a alguien as胤[n]siempre es duro...[n][w][e]

[msg MSG_017_0_0 [Haru]]
[s][f 5 14]Pero ahora estoy bien.[n]Me hab姻is ayudado mucho.[n][w][e]

[msg MSG_018_0_0 [Futaba]]
[s][f 5 14]斡Lo mismo digo![n][w][e]

[msg MSG_019_0_0 [Haru]]
[s][f 5 14]Gracias. O胤r algo as胤[n]tranquiliza bastante.[n][w][e]

[msg MSG_020_0_0 [Haru]]
[s][f 5 14][f 5 15]Bueno, os veo[n]en el instituto.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Pobre Haru... No me extra隠a que[n]est姻 de capa ca胤da.[n]Piensa en ella, [f 4 2].[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Aunque no lo parezca, Haru[n]tiene agallas. Estoy seguro[n]de que estar茨 bien.[n][f 1 3 65535][w][e]

