[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Lo del padre de Haru... Esto...[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Seg雨n las noticias,[n]ha sufrido un paro card胤aco...[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Pero hay posibilidades[n]de que salga adelante, 夷no...?[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Odio tener que decir esto...[n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]Pero normalmente, despu姻s[n]de una noticia as胤, suele venir[n]la confirmaci吋n de la muerte...[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]斡No...![n][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]Haru...[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]斡夷Por qu姻 est茨 pasando esto?![n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]斡夷Se puede morir alguien[n]por una desconexi吋n mental?![n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]斡No lo s姻![n][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]Supongo que la conmoci吋n[n]puede matar a una persona...[n][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][f 5 14]Haru mencion吋 que su padre[n]no andaba muy bien de salud...[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Pero... 夷morir tan de repente?[n]Tiene que ser una broma...[n][w][e]

[msg MSG_014_0_0 [Futaba]]
[s][f 5 14]夷Tenemos la culpa[n]de que haya muerto...?[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]斡Cre胤a que todo ir胤a bien[n]siempre que no[n]mat茨semos a su sombra![n][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 5 14]斡夷No es eso[n]lo que dijiste, Morgana?![n][w][e]

[msg MSG_017_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 33 0 0]斡Deber胤a haber ido bien![n][f 1 3 65535][w][e]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 1 0 0 34 0 0]D-deber胤a...[n][f 1 3 65535][w][e]

[sel SEL_018_0_0 top]
[s][f 5 14]Dice que deber胤a haber ido bien.[e]
[s]夷Por qu姻 ha pasado esto...?[e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14]S胤, 斡no sirve de nada[n]enfadarse con Mona por eso![n]Yo tambi姻n he escuchado lo mismo...[n][w][e]

[msg MSG_020_0_0 [Ann]]
[s][f 5 14]Hicimos lo mismo de siempre...[n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][f 5 14]En cualquier caso, tenemos[n]que sosegarnos. Hay que[n]actuar con normalidad en p雨blico.[n][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][f 5 14][f 5 15]Pero teniendo en cuenta a Haru...[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 1 0 0 35 0 0]Joder, esto no tiene ning雨n[n]sentido... Una cosa es por qu姻[n]tuvo una desconexi吋n mental...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 36 0 0]Pero 夷qu姻 se supone que tenemos[n]que hacer a partir de ahora...?[n][f 1 3 65535][w][e]

