[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]夷Podemos quedar hoy?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Quiero hablar contigo de una cosa.[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]Est茨s libre, 夷no?[n]Aunque me gustar胤a que vinieras,[n]por muy ocupado que est姻s.[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Te espero delante[n]de la entrada del instituto.[n][w][e]

[msg CHAT_NOREACTION_MSG [Makoto]]
[s][f 5 14]夷Te pillo en mal momento?[n]Llevo esperando todo el d胤a...[n]Bueno, ya te volver姻 a invitar.[n][w][e]

[msg CHAT_REACTION_MSG [Makoto]]
[s][f 5 14]Vale. No tardes mucho.[n]Aqu胤 te espero.[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]夷Qu姻 vas a hacer?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir de inmediato[e]
[s]Comprobar v胤nculo con Makoto[e]
[s]Responder luego[e]

[sel SEL_002 top]
[s][f 5 14]Ya mismo voy.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]Deber胤a poder mejorar[n]nuestro v胤nculo ya que tengo[n]a [clr 1][var 5][clr 27] del arcano [var 2]...[n][w][e]

