[msg MSG_000_0_0 [Ann]]
[s][f 5 14]La reuni吋n del consejo[n]es ma隠ana, 夷no?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Nos van a expulsar[n]si Kamoshida no despierta[n]para entonces...[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Seguro que s胤.[e]
[s]Hemos hecho lo que hemos podido.[e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Despertar茨, ya ver茨s.[n]Menudo l胤o si no.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Bueno, yo no voy a perder[n]la esperanza.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Tienes raz吋n.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Es un poco pronto para rendirse.[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Supongo que ma隠ana ya nos las[n]arreglaremos como sea.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Hay que prepararse[n]para lo que pueda pasar.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Siento no poder asegur茨rtelo,[n]pero deber胤a despertar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Vamos a pensar eso mientras[n]esperamos a que llegue ma隠ana.[n][f 1 3 65535][w][e]

