[msg MSG_000_0_0 [Chihaya]]
[s][f 5 14]夷Mis adivinaciones son poco[n]precisas?[n][w][e]

[msg MSG_001_0_0 [Chihaya]]
[s][f 5 14]夷O es que te averg鵜enzas de algo?[n][w][e]

[msg MSG_002_0_0 [Chihaya]]
[s][f 5 14]Me gustar胤a hablar contigo.[n]Estar姻 en Shinjuku, como siempre.[n][w][e]

[msg MSG_003_0_0 [Chihaya]]
[s][f 5 14]斡Has vuelto a darme plant吋n![n]斡Ya he tenido suficiente![n][w][e]

[msg MSG_004_0_0 [Chihaya]]
[s][f 5 14]Gracias por lo de hoy.[n][w][e]

[msg CHAT_REACTION_MSG [Chihaya]]
[s][f 5 14]斡Genial! Te estar姻 esperando.[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Bueno, 夷qu姻 quieres hacer? 夷Vas[n]a aceptar la invitaci吋n de Chihaya?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir de inmediato[e]
[s]Comprobar v胤nculo con Chihaya[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Ahora mismo voy.[e]

