[msg MSG_000_0_0 [Haru]]
[s][f 5 14]He cultivado verduras nuevas.[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Me encantar胤a que Sakura[n]me diese su opini吋n[n]sobre ellas lo antes posible...[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Pero las cosas est茨n un poco[n]patas arriba. Ser茨 mejor ir cuando[n]tengamos m茨s tiempo.[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]Estar姻 en la azotea[n]despu姻s de clase, as胤 que p茨sate[n]cuando te venga bien.[n][f 5 15][w][e]

[msg MSG_999_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Vaya, parece que las verduras[n]de Haru est茨n listas.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Vamos a verla a la azotea.[n][f 1 3 65535][w][e]

