[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Tengo como ansiedad...[n]O a lo mejor estoy deprimida.[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Necesito desahogarme.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Ma隠ana tenemos el d胤a libre,[n]as胤 que podr胤amos avisar a Ryuji[n]e ir al karaoke.[n][w][e]

[msg MSG_100_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]斡Ann nos ha invitado al karaoke![n]夷Te apetece?[n][f 1 3 65535][w][e]

[sel SEL_111_0_0 top]
[s]Comprometerse[e]
[s]Rechazar[e]
[s]Responder luego[e]

[sel SEL_111_1_0 top]
[s]Ir de inmediato[e]
[s]Rechazar[e]
[s]Responder luego[e]

[sel SEL_200_0_0 top]
[s][f 5 14]Vamos juntos.[e]
[s]Ma隠ana tengo planes...[e]

[msg MSG_201_0_0 [Ann]]
[s][f 5 14]Vale. Avisar姻 a Ryuji.[n][w][e]

[msg MSG_202_0_0 [Ann]]
[s][f 5 14]Quedamos delante de la estaci吋n[n]de Shibuya por la tarde.[n][w][e]

[msg MSG_210_0_0 [Ann]]
[s][f 5 14]Ah, vale.[n][w][e]

[msg MSG_400_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]斡Yo tambi姻n me apunto![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0]Dej姻moslo por hoy[n]y vayamos a dormir.[n][f 1 3 65535][w][e]

[msg MSG_401_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]夷Qu姻? 斡夷No quieres ir?![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0]夷Es que tienes otros planes?[n][f 1 3 65535][w][e]

[msg MSG_402_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Acu姻rdate de contestarle[n]ma隠ana, 夷vale?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0]Venga, a dormir.[n][f 1 3 65535][w][e]

