[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Como estamos de vacaciones,[n]esperar姻 en tu casa.[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Adem茨s, he encontrado[n]algo interesante.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Es un DVD que habla[n]de la vida de un pintor.[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]He pensado que podr胤amos compartir[n]nuestro aprecio por el arte.[n][w][e]

[msg MSG_003_1_0 [Yusuke]]
[s][f 5 14]No te preocupes si ya tienes[n]planes, me pasar姻 de todas maneras.[n][f 5 15][w][e]

[msg MSG_003_2_0 [Yusuke]]
[s][f 5 14]No te preocupes si ya tienes[n]planes, me pasar姻 de todas maneras.[n][w][e]

[sel SEL_004_0_0 top]
[s][f 5 14]No tengo tele.[e]
[s]Soy muy pobre para eso.[e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]夷A雨n no tienes?[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]No deb胤 ilusionarme tanto.[n]Que tengas un buen d胤a.[n][f 5 15][w][e]

[msg MSG_MORGANA_TV_NotSet [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Espero que la tele que[n]has pedido llegue pronto...[n][f 1 3 65535][w][e]

[msg MSG_MORGANA_TV [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1170 65535 0]Una tele... Qu姻 pena que no[n]podamos usar la de la[n]primera planta.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Pero mira cu茨ntos trastos...[n]Puede que encontraras una tele[n]si limpiaras un poco.[n][f 1 3 65535][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Pues nos vemos ma隠ana.[n][f 5 15][w][e]

[msg MSG_999_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0]Yusuke viene ma隠ana, 夷no? Podr胤a[n]estar bien pasar el rato con 姻l.[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]No tengo reproductor de DVD.[e]
[s]Soy muy pobre para eso.[e]

[msg MSG_MORGANA_NO_DVD [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1170 65535 0]No podemos hacer mucho con esa tele[n]a menos que consigamos[n]un reproductor de DVD.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Cuando podamos, podr胤amos mirar[n]en la tienda de segunda mano[n]que hay en el barrio.[n][f 1 3 65535][w][e]

