[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Lo agradezco de coraz吋n.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]夷A qu姻 viene[n]tanta educaci吋n de repente?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Os estoy muy agradecido por[n]haberme hecho entrar en raz吋n.[n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]Exageras.[e]
[s]Nos debes una.[e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Casi seguro que no. He de expresar[n]mi gratitud con sinceridad.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Sin duda. Alg雨n d胤a[n]devolver姻 el favor.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Ahora eres uno de los nuestros.[n]Contamos contigo, 夷vale?[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Claro.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Y si ocurre cualquier cosa,[n]no dudaremos en echarte una mano.[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Gracias.[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Nos vemos.[n][w][e]

