[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]夷Qu姻 tenemos que hacer como comit姻[n]ejecutivo del festival del instituto?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Voy a necesitar ayuda[n]con los cuestionarios.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]夷Qu姻 cuestionarios?[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Los de la persona que la gente[n]quiere ver como invitada de honor.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Ah, ya. Eso que se hace[n]todos los a隠os.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Te refieres a cuando vienen[n]a dar una charla, 夷no?[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Las fechas del festival han[n]cambiado debido a la situaci吋n.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Tenemos que darnos prisa[n]y anotar los resultados.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Venid al aula[n]del consejo estudiantil[n]cuando acaben las clases.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Uf, qu姻 puto aburrimiento.[n][w][e]

[msg MSG_010_0_0 [Haru]]
[s][f 5 14]No seas as胤. Es para poder[n]reunirnos sin llamar la atenci吋n.[n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14]Hagamos lo que podamos de momento.[n][w][e]

[msg MSG_012_0_0 [Futaba]]
[s][f 5 14]斡Me aseguro[n]de trabajar mucho en casa![n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Pero eso lo haces siempre.[n][w][e]

[msg MSG_014_0_0 [Futaba]]
[s][f 5 14]斡Puedo buscar cosas![n]夷Has encontrado algo, Haru?[n][w][e]

[msg MSG_015_0_0 [Haru]]
[s][f 5 14]Pues ver茨s...[n][w][e]

[msg MSG_016_0_0 [Futaba]]
[s][f 5 14]Nada bueno, 夷no?[n][w][e]

[msg MSG_017_0_0 [Haru]]
[s][f 5 14]Lo siento.[n][w][e]

[msg MSG_018_0_0 [Haru]]
[s][f 5 14]Si pregunto demasiados detalles,[n]levantar姻 sospechas.[n][w][e]

[msg MSG_019_0_0 [Futaba]]
[s][f 5 14]斡No pasa nada![n][w][e]

[msg MSG_020_0_0 [Futaba]]
[s][f 5 14]斡Ya me las apa隠ar姻![n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][f 5 14]Contamos contigo.[n][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][f 5 14]No puedo ir, pero escribidme[n]si ocurre cualquier cosa.[n][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Os lo dejo a vosotros.[n]Disculpadme, pero no puedo[n]ayudaros mucho en esta situaci吋n.[n][w][e]

