[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]斡Parece que 或el Asaltante位[n]se ha entregado![n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Qu姻 buena noticia.[e]
[s]Misi吋n completada.[e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]斡La paz ha vuelto al para胤so![n]斡Aleluya![n][w][e]
[s][f 5 14]No hay novedades sobre su amigo,[n]pero imagino que estar茨 bien, 夷no?[n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]Por supuesto.[e]
[s]No lo s姻.[e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]斡Claro que s胤! 斡Los otakus[n]tenemos que confiar entre nosotros![n][w][e]
[s][f 5 14][f 5 15]Gracias, [f 4 2].[n][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][f 5 14]S胤. Tendr茨n que solucionarlo[n]por su cuenta.[n][w][e]
[s][f 5 14][f 5 15]Pero espero que lleguen[n]a entenderse de alg雨n modo.[n][w][e]

[msg MSG_006_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1164 65535 0]Preocuparse por el amigo[n]del objetivo es t胤pico de Futaba.[n][f 1 3 65535][w][e]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Encontrar茨n el modo de solucionar[n]sus problemas, ya lo ver茨s.[n][f 1 3 65535][w][e]

