[msg MSG_001_0_0 [Haru]]
[s][f 5 14]No me puedo creer[n]lo que ha pasado con Mementos...[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Su verdadero poder es apabullante.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]斡No me esperaba que Mementos[n]tuviese tanta profundidad![n]斡Este sitio es la hostia de grande![n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Y a雨n queda... Yo he perdido[n]la cuenta del tiempo[n]que hemos estado en las escaleras.[n][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][f 5 14]S胤, 夷verdad? Este sitio no es[n]para gente en baja forma.[n][w][e]

[msg MSG_006_0_0 [Sumire]]
[s][f 5 14]Quiz茨 sea evidente, pero estirarse[n]ayuda bastante cuando se te cansan[n]las piernas y los brazos.[n][w][e]

[msg MSG_007_0_0 [Sumire]]
[s][f 5 14]Y tambi姻n viene bien darse masajes[n]en los puntos de presi吋n.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]斡Ostras, la atleta s胤 que sabe![n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]A todo esto, 夷no ibas a ir directa[n]a entrenar nada m茨s acabar, Sumire?[n][w][e]

[msg MSG_010_0_0 [Sumire]]
[s][f 5 14]斡Pues iba a ello ahora mismo, s胤![n][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][f 5 14]斡夷Eh?! 夷Y todo este aguante?[n][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][f 5 14]Bueno, t雨 decides.[n]No te canses mucho.[n][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][f 5 14]Si agotas toda tu energ胤a[n]fuera de combate, no solo[n]eres in雨til, tambi姻n un lastre.[n][w][e]

[msg MSG_014_0_0 [Sumire]]
[s][f 5 14][f 5 15]斡Intentar姻 no cansarme[n]m茨s de lo necesario![n][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1035 65535 0]Habr茨 que volver a infiltrarse[n]en el Palacio la pr吋xima vez.[n]Ojal茨 el camino no est姻 bloqueado.[n][f 1 3 65535][w][e]

