[msg MSG_000_0_0 [Haru]]
[s][f 5 14]La reputaci吋n de Shido[n]est茨 por las nubes...[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Es absurdo.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Este no es el nivel de[n]popularidad de un pol胤tico normal.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]夷Qu姻 lo hace tan genial?[n]De verdad que no lo entiendo.[n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]Es un l胤der fuerte que protege[n]a sus ciudadanos... Bueno, supuestamente.[n][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][f 5 14]斡夷Es que est茨 todo el mundo ciego?![n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Tendremos que aclarar[n]qui姻n es de verdad.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Por cierto, 夷os importa[n]que mi hermana venga ma隠ana?[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Quiere ayudar.[n][w][e]

[sel SEL_009_0_0 top]
[s][f 5 14]Me parece bien.[e]
[s]Ser胤a genial.[e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]Vale. Se lo dir姻.[n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14][f 5 15]Vale, ma隠ana averiguaremos[n]las palabras clave sin falta.[n][w][e]

