[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]斡Me abuuurrooo![n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]斡夷Pero qu姻 dices?![n]斡Analiza esos datos![n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Mi ordenador est茨 en ello.[n][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][f 5 14]斡Yo no tengo que hacer nada![n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Estamos preparando nuestro viaje[n]escolar. Nadie tiene tiempo[n]para entretenerte ahora mismo.[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]斡Oh, jol胤n![n]斡Tengo que ir de compras![n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Solo hace falta cepillo de dientes,[n]夷no? 夷A qu姻 viene tanto p茨nico?[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]斡Necesito muchas cosas! 斡Champ雨s,[n]lociones, acondicionadores...![n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]Ah, eso me recuerda que deber胤a[n]llevar un lienzo. Este viaje puede[n]ser una oportunidad de oro.[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Pero 夷bastar茨 con uno...?[n][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Es m茨s que suficiente.[e]
[s]No te va a hacer falta.[e]
[s]夷Por qu姻 vas a llevar uno siquiera?[e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]No, quiz茨 tres mejor.[n]La inspiraci吋n podr胤a llegar[n]en cualquier momento...[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14]Pero no podr胤a dibujar nada.[n]Puede que me lleve tres[n]por si acaso.[n][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][f 5 14]Para dibujar, obviamente.[n]Me llevar姻 tres, uno de sobra.[n][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][f 5 14]Y en cuanto al tama隠o del lienzo...[n]Cuanto m茨s grande, mejor, 夷no?[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Pero 斡夷por qu姻 nos preguntas[n]a nosotros?![n][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 5 14][f 5 15]斡Yo no me llevar胤a[n]mierdas de ese tipo![n][w][e]

