[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Se acercan los ex茨menes.[n][w][e]

[msg MSG_000_0_1 [Ryuji]]
[s][f 5 14]夷No ir茨s a estudi茨rtelo todo[n]sin m胤? 夷verdad?[n][w][e]

[msg MSG_000_0_2 [Ryuji]]
[s][f 5 14]Si vas a estudiar,[n]夷te apetece que te acompa隠e?[n]Estoy metido en un buen l胤o...[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Bueno, 夷entonces qu姻?[n]夷Quieres estudiar con Ryuji?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Estudiemos juntos.[e]

[msg MSG_REACTION [Ryuji]]
[s][f 5 14]Qu姻 gran ayuda.[n][w][e]

[msg MSG_REACTION_02 [Ryuji]]
[s][f 5 14]Estar姻 esperando en[n]el restaurante de Shibuya.[n][f 5 15][w][e]

