[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]18/07. D胤a del Mar.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Los finales acaban el 16, as胤 que[n]no deber胤a haber problema, 夷no?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]夷De qu姻 est茨is hablando?[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Del festival de fuegos artificiales.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]S胤 que te das prisa[n]para buscar ese tipo de cosas...[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Incre胤ble, Ryuji.[e]
[s]Ponte a estudiar.[e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Es m茨s f茨cil trabajar cuando tienes[n]un objetivo en mente, 夷a que s胤?[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Ya lo har姻 ma隠ana.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Eh, estamos en medio de la clase.[n]Hablad de esas cosas m茨s tarde.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Ya, ya.[n][w][e]

