[msg MSG_000_0_0 [Kawakami]]
[s][f 5 14]夷Est茨s libre hoy? 夷Podemos vernos?[n][w][e]

[msg MSG_001_0_0 [Kawakami]]
[s][f 5 14]Hay mucho de lo que[n]no podemos hablar en clase...[n][w][e]

[msg MSG_002_0_0 [Kawakami]]
[s][f 5 14]Ah, ya no soy sirvienta, pero sigo[n]dispuesta a hacerte las tareas.[n][f 5 15][w][e]

[msg MSG_MORUGANA_CORPNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Seguro que est茨s cansado[n]de la incursi吋n al Metaverso.[n]Quiz茨 deber胤as descansar por hoy.[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_CORPNG2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ya le has asignado una tarea[n]a Kawakami.[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Llamarla[e]
[s]Decidir luego[e]

[msg MSG_MORUGANA_01 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Pues llamemos.[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Kawakami quiere quedar[n]esta noche. 夷La llamo por el[n]tel姻fono amarillo como siempre?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Parece que Kawakami quiere quedar[n]esta noche. 夷La llamo por el[n]tel姻fono amarillo como siempre?[n][f 1 3 65535][w][e]

