[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]La diversi吋n no ha terminado.[n]Ma隠ana es el gran d胤a.[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]Cuando acabes de trabajar, 夷quieres[n]que quedemos los dos solos?[n]Es que quiero darte algo.[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Claro.[e]

[msg MSG_020_0_0 [Futaba]]
[s][f 5 14]斡Chachi! Pues ma隠ana[n]invado tu casa.[n][w][e]

[msg MSG_021_0_0 [Futaba]]
[s][f 5 14]斡Hora de darme el piro![n][f 5 15][w][e]

