[msg MSG_000_0_0 [Ann]]
[s][f 5 14]He encontrado otra solicitud[n]resuelta en internet...[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Justo estaba pensando en eso.[n][w][e]

[msg MSG_001_5_0 [Makoto]]
[s][f 5 14]Parece que el problema[n]se ha solucionado de verdad.[n]No puede ser falso.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Eso significa que hay alguien m茨s[n]entrando en Mementos.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Todo esto me recuerda[n]a nuestras primeras andadas[n]como los Ladrones Fantasma.[n][w][e]

[msg MSG_003_5_0 [Ryuji]]
[s][f 5 14]De repente, Morgana decidi吋[n]llevarnos a Mementos.[n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]Esperad un momento, 夷podr胤a ser...?[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Morgana y Haru.[e]
[s]Solo es una broma.[e]
[s]No podemos perder contra ellos.[e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]S胤, es la 雨nica conclusi吋n l吋gica.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Se me hace dif胤cil seguir[n]pensando eso. Est茨n resolviendo[n]solicitudes de verdad, 夷record茨is?[n][w][e]

[msg MSG_007_5_0 [Makoto]]
[s][f 5 14]Quiz茨 Morgana est姻 llevando[n]a Okumura a Mementos.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]夷Y qu姻 ganamos[n]con esta competici吋n?[n][w][e]

[msg MSG_008_5_0 [Makoto]]
[s][f 5 14]Lo que quiero decir[n]es que Morgana acompa隠a[n]a Okumura a Mementos.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]夷En serio? 夷No se dar茨 cuenta[n]la gente de lo que pasa?[n][w][e]

[msg MSG_009_5_0 [Ryuji]]
[s][f 5 14]Nosotros nunca respondemos[n]ni nada por el estilo.[n]Est茨n llamando mucho la atenci吋n.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Creo que a雨n no se ha dado cuenta[n]nadie, pero no nos convendr胤a[n]que lo investigasen.[n][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][f 5 14]Ser胤a muy f茨cil encontrar[n]a Morgana y a Haru[n]mediante el registro de red.[n][w][e]

[msg MSG_011_5_0 [Futaba]]
[s][f 5 14]Creo que ninguno de los dos[n]entiende muy bien[n]c吋mo funciona esto.[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14]Si lo dejamos estar,[n]nuestras identidades podr胤an[n]descubrirse junto con las suyas.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Tenemos que detenerlos. Makoto,[n]夷puedes intentar ponerte[n]en contacto con Okumura?[n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14]No tengo sus datos de contacto.[n][w][e]

[msg MSG_014_5_0 [Makoto]]
[s][f 5 14]Y gracias a la Ley[n]de Protecci吋n de Datos,[n]el n雨mero de su casa es privado.[n][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][f 5 14]Entonces, 夷tenemos que[n]esperar hasta el lunes?[n]Lo mejor ser胤a actuar cuanto antes...[n][w][e]

[sel SEL_016_0_0 top]
[s][f 5 14]Vayamos a su casa.[e]
[s]Esperemos en Mementos.[e]

[msg MSG_017_0_0 [Ann]]
[s][f 5 14]Pero tambi姻n es la casa del[n]presidente. Seguro que hay guardias[n]y c茨maras por todos lados...[n][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][f 5 14]Adem茨s, a雨n no estamos del todo[n]seguros de que Morgana y Haru[n]est姻n detr茨s de todo esto.[n][w][e]

[msg MSG_018_5_0 [Ryuji]]
[s][f 5 14]Entonces, vigilaremos Mementos[n]hasta que los atrapemos, 夷no?[n][w][e]

[msg MSG_018_7_0 [Makoto]]
[s][f 5 14]Esa es la manera m茨s segura...[n][w][e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14]Est茨s de broma, 夷no?[n]夷Quieres que esperemos hasta[n]que decidan presentarse?[n][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]Creo que es la 雨nica opci吋n...[n]Si queremos atraparlos,[n]probablemente sea la mejor forma.[n][w][e]

[msg MSG_021_0_0 [Futaba]]
[s][f 5 14]T胤o, suena superdivertido.[n][w][e]

[msg MSG_021_5_0 [Futaba]]
[s][f 5 14]斡Traedme juegos, aperitivos,[n]refrescos y fideos instant茨neos![n][w][e]

[msg MSG_022_0_0 [Yusuke]]
[s][f 5 14]Vosotros os encarg茨is de cocinar.[n]Yo quiero una sopa acompa隠ada[n]de cinco platos de verdura.[n][w][e]

[msg MSG_023_0_0 [Ann]]
[s][f 5 14]A m胤 no me vendr胤a mal un poco[n]de crema hidratante. No quiero[n]que se me reseque la piel.[n][w][e]

[msg MSG_024_0_0 [Ryuji]]
[s][f 5 14]斡De toda esa mierda[n]os encarg茨is vosotros![n][w][e]

[msg MSG_025_0_0 [Makoto]]
[s][f 5 14]Bueno, quedamos en Mementos[n]ma隠ana por la ma隠ana.[n][w][e]

[msg MSG_025_5_0 [Makoto]]
[s][f 5 14][f 5 15]Quiz茨 no sea f茨cil,[n]pero haremos lo que podamos.[n][w][e]

