[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Macho, a Ushimaru le pasa algo.[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]夷Por qu姻 lo dices?[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]斡No s姻, pero algo pasa![n]Supongo que no es nada malo,[n]pero est茨 muy raro.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]夷Alguien sabe de qu姻 habla?[n][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][f 5 14]夷Qu姻 Ushimaru?[n][w][e]

[sel SEL_006_0_0 top]
[s][f 5 14]Un profesor estricto.[e]
[s]Nuestro profe de Ciencias Sociales.[e]

[msg MSG_007_0_0 [Sumire]]
[s][f 5 14]Uno que es experto en lanzar tizas.[n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]Ah. No digas m茨s.[n][w][e]

[msg MSG_009_0_0 [Sumire]]
[s][f 5 14]Es superestricto, 夷a que s胤? Hasta[n]los novatos han o胤do hablar de 姻l.[n][w][e]

[msg MSG_010_0_0 [Haru]]
[s][f 5 14]夷Qu姻 es lo que ha cambiado?[n]夷Su personalidad?[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]夷Qu姻, ahora es supersimp茨tico?[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]斡Exacto! 斡Tan simp茨tico[n]que da hasta grima![n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]斡Y le pregunte a quien le pregunte,[n]me dicen que siempre ha sido as胤![n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14]斡Hasta hay quien dice[n]que es el Buda del instituto![n][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][f 5 14]Parece que[n]le ha venido la iluminaci吋n...[n][w][e]

[msg MSG_016_0_0 [Haru]]
[s][f 5 14]夷El doctor Maruki ha cambiado[n]la personalidad de alguien?[n][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][f 5 14]Si de verdad quer胤a cambiar,[n]s胤 que es posible...[n][w][e]

[msg MSG_017_0_1 [Ryuji]]
[s][f 5 14]斡夷A Ushimaru?! 斡夷En serio?![n][w][e]

[msg MSG_018_0_0 [Sumire]]
[s][f 5 14]Es como cuando yo quer胤a[n]ser Kasumi...[n][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][f 5 14]Lo m茨s probable es que[n]sea una situaci吋n parecida.[n]Habr茨 cambiado algo del pasado.[n][w][e]

[msg MSG_019_0_1 [Akechi]]
[s][f 5 14]Tambi姻n es posible que solo[n]haya cambiado su personalidad,[n]al margen de otros sucesos.[n][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]夷Le pasar胤a algo malo[n]al aut姻ntico Ushimaru?[n][w][e]

[msg MSG_021_0_0 [Futaba]]
[s][f 5 14]A lo mejor era tan simp茨tico que los [n]estudiantes se aprovecharon de 姻l y se[n]convirtieron en delincuentes totales.[n][w][e]

[msg MSG_022_0_0 [Ann]]
[s][f 5 14]Buf. Eso s胤 que ser胤a traum茨tico.[n][w][e]

[msg MSG_022_0_1 [Akechi]]
[s][f 5 14]Podemos hacer todas las conjeturas[n]que queramos. 畏l es el 雨nico[n]que sabe lo que ha cambiado.[n][w][e]

[msg MSG_022_0_2 [Yusuke]]
[s][f 5 14]Es dif胤cil de comprender...[n][w][e]

[msg MSG_023_0_0 [Yusuke]]
[s][f 5 14]O sea que por ser feliz, hasta[n]la personalidad puede cambiar...[n][w][e]

[sel SEL_024_0_0 top]
[s][f 5 14]Ese no es Ushimaru.[e]
[s]Seguro que ahora es feliz.[e]
[s]Como un despertar.[e]

[msg MSG_025_0_0 [Ryuji]]
[s][f 5 14]Exacto.[n][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][f 5 14]No es que me cayera muy bien antes,[n]pero esto es raro de narices.[n][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][f 5 14]No, ya, pero aun as胤...[n][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][f 5 14]Algo va mal.[n][w][e]

[msg MSG_029_0_0 [Ryuji]]
[s][f 5 14]Supongo, aunque tampoco es que[n]Ushimaru fuera completamente malo.[n][w][e]

[msg MSG_030_0_0 [Ryuji]]
[s][f 5 14]Estoy tan cabreado[n]que me voy a ir a dormir.[n][w][e]

[msg MSG_031_0_0 [Futaba]]
[s][f 5 14]夷Eso es lo que hace[n]la gente cuando se enfada?[n][w][e]

[msg MSG_032_0_0 [Makoto]]
[s][f 5 14][f 5 15]Bueno... Siempre[n]puedes prestar atenci吋n en clase.[n][w][e]

[msg MSG_033_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]Ese Ushimaru, 夷eh? Cuesta creerlo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Supongo que tendremos[n]que comprobarlo en su clase.[n][f 1 3 65535][w][e]

