[msg MSG_001_0_0 [Kasumi]]
[s][f 5 14]Hola.[n][w][e]

[msg MSG_002_0_0 [Kasumi]]
[s][f 5 14]夷Te acuerdas de nuestro trato?[n]夷De c吋mo iba a ayudarte[n]con el entrenamiento f胤sico?[n][w][e]

[msg MSG_003_0_0 [Kasumi]]
[s][f 5 14]夷No podemos dejarlo[n]para la semana que viene?[n][w][e]

[msg MSG_004_0_0 [Kasumi]]
[s][f 5 14]Me voy a un campamento[n]de entrenamiento y estar姻 fuera[n]del pa胤s una temporada.[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Me voy a Haw茨i por mi cuenta.[e]
[s]Yo igual.[e]

[msg MSG_006_0_0 [Kasumi]]
[s][f 5 14]夷Eh?[n][w][e]

[msg MSG_007_0_0 [Kasumi]]
[s][f 5 14]斡Uy, s胤! El viaje de los de segundo[n]tambi姻n es la semana que viene.[n][w][e]

[msg MSG_008_0_0 [Kasumi]]
[s][f 5 14]斡Qu姻 casualidad que vayamos[n]al extranjero a la vez![n][w][e]

[msg MSG_009_0_0 [Kasumi]]
[s][f 5 14]Vale. 斡Se suspende el entrenamiento[n]hasta que lleguemos a casa![n][w][e]

[msg MSG_010_0_0 [Kasumi]]
[s][f 5 14]Cuando nos pongamos, me esforzar姻[n]al m茨ximo para ayudarte.[n][w][e]

[msg MSG_011_0_0 [Kasumi]]
[s][f 5 14][f 5 15]斡Disfruta del viaje![n]斡Ya me contar茨s qu姻 tal![n][w][e]

