[msg MSG_000_0_0 [Ann]]
[s][f 5 14]夷Qu姻 vamos a hacer hoy?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]夷No vamos a quedar hoy?[n]Estoy en el centro comercial[n]subterr茨neo de Shibuya.[n][w][e]

[msg MSG_001_1_0 [Ann]]
[s][f 5 14]No puedo estar sin hacer nada...[n][w][e]

[msg MSG_001_1_1 [Ann]]
[s][f 5 14]Ahora estoy de compras[n]en el centro comercial[n]subterr茨neo de Shibuya.[n][w][e]

[msg MSG_001_2_0 [Ann]]
[s][f 5 14]Ahora estoy en el centro comercial[n]subterr茨neo de Shibuya.[n][w][e]

[msg MSG_001_0_SUMMER_0 [Ann]]
[s][f 5 14]夷No vamos a quedar hoy?[n]Estoy en el centro comercial[n]subterr茨neo de Shibuya.[n][w][e]

[msg MSG_001_0_SUMMER_1 [Ann]]
[s][f 5 14]Est茨 todo lleno[n]por las vacaciones de verano.[n][w][e]

[msg MSG_001_1_SUMMER_0 [Ann]]
[s][f 5 14]No puedo estar sin hacer nada,[n]as胤 que estoy por el centro comercial[n]de Shibuya.[n][w][e]

[msg MSG_001_1_SUMMER_1 [Ann]]
[s][f 5 14]Est茨 todo lleno[n]por las vacaciones de verano.[n][w][e]

[msg MSG_001_1_SUMMER_2 [Ann]]
[s][f 5 14]夷Te vienes? No s姻.[n][w][e]

[msg MSG_001_2_SUMMER_0 [Ann]]
[s][f 5 14]Estoy en el centro comercial[n]de Shibuya. Est茨 todo lleno[n]por las vacaciones de verano...[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Seguir姻 un rato por Shibuya.[n]Av胤same si surge algo.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que la se隠orita Ann[n]no se ha ido a casa todav胤a.[n]夷Quieres ir a verla un rato?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]La se隠orita Ann est茨 en Shibuya.[n]夷Quieres ir a verla un rato?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]夷Quieres ir a ver[n]a la se隠orita Ann?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Voy para all茨.[e]

[msg MSG_REACTION [Ann]]
[s][f 5 14]Ah, vale, claro.[n][f 5 15][w][e]

