[msg MSG_000_0_0 [Ann]]
[s][f 5 14]He o胤do que se ha filtrado[n]la informaci吋n de una empresa, 夷no?[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]S胤, al parecer han salido a la luz[n]las transacciones privadas[n]de una gran corporaci吋n.[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]Ha causado mucho revuelo.[n]La gente se pregunta[n]si Medjed est茨 detr茨s de ello.[n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]夷Crees que ha sido Medjed?[e]
[s]Esa no fue su promesa.[e]
[s]Mejor ignorarlo.[e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]Yo dir胤a que no.[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]Correcto. Dudo que hagan nada[n]antes de la fecha l胤mite[n]que nos impusieron.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Estoy de acuerdo.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Esto parece algo sin importancia.[n]Nada que ver con lo que Medjed[n]ha hecho hasta la fecha.[n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]夷De verdad?[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]斡夷Entonces no ha sido Medjed?![n]斡Joder, esa mierda me ten胤a[n]de los nervios![n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]La verdad, es dif胤cil no cabrearse[n]con cosas as胤 hoy en d胤a...[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]A veces la gente reacciona a[n]estas situaciones suplicando ayuda[n]a los Ladrones Fantasma.[n][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14][f 5 15]Tenemos que encontrar[n]la manera de defenderlos...[n][w][e]

