[msg MSG_000_0_0 [Yoshida]]
[s][f 5 14]Las elecciones de hoy[n]han sido un 姻xito.[n][w][e]

[msg MSG_001_0_0 [Yoshida]]
[s][f 5 14]Bueno, ha sido el partido de Shido[n]el que ha ganado por goleada.[n][w][e]

[msg MSG_002_0_0 [Yoshida]]
[s][f 5 14]Pero hay gente que apoya[n]mis argumentos.[n][w][e]

[msg MSG_003_0_0 [Yoshida]]
[s][f 5 14]El mundo no est茨 tan mal[n]como parec胤a.[n][w][e]

[msg MSG_004_0_0 [Yoshida]]
[s][f 5 14]Si no llega a ser por ti, esto[n]no habr胤a sido posible. Gracias.[n][w][e]

[msg MSG_005_0_0 [Yoshida]]
[s][f 5 14]La contienda de verdad est茨[n]a punto de comenzar.[n]Tenemos que trabajar duro.[n][f 5 15][w][e]

