[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Mishima est茨 como loco[n]por encontrar el pr吋ximo objetivo.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Pero tengo la sensaci吋n de que[n]se va a meter en l胤os. Quiz茨[n]deber胤amos ir con 姻l.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Dec胤a que iba a Harajuku.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Se lo dir姻 a Ann tambi姻n.[n]No pasa nada, 夷no?[n][f 5 15][w][e]

[msg MSG_101_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]斡夷Que viene Ann?! Mm... O sea, vale.[n]No es para tanto.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Pero todav胤a no conoces Tokio muy[n]bien. Podr胤a ser un buen momento[n]para familiarizarte con la zona.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Bueno, 夷qu姻 te parece?[n]夷Vas a ir a [clr 2]Harajuku[clr 27] con Ryuji?[n][f 1 3 65535][w][e]

[sel SEL_111_0_0 top]
[s]Comprometerse[e]
[s]Rechazar[e]
[s]Responder luego[e]

[sel SEL_111_1_0 top]
[s]Ir de inmediato[e]
[s]Rechazar[e]
[s]Responder luego[e]

[msg MSG_999_0_0 [Ryuji]]
[s][f 5 14]夷Crees que podr茨s venir[n]a Harajuku hoy?[n][f 5 15][w][e]

[sel SEL_200_0_0 top]
[s][f 5 14]Supongo que ir姻.[e]
[s]Tengo planes.[e]

[msg MSG_201_0_0 [Ryuji]]
[s][f 5 14]斡Vale! Nos vemos all胤.[n][f 5 15][w][e]

[msg MSG_201_1_0 [Ryuji]]
[s][f 5 14]斡Vale, pues vente![n][w][e]
[s][f 5 14]Te estaremos esperando.[n][f 5 15][w][e]

[msg MSG_210_0_0 [Ryuji]]
[s][f 5 14]S胤, me imaginaba que[n]estar胤as ocupado.[n][w][e]
[s][f 5 14]Pues yo me ocupo de Mishima.[n]斡Nos vemos![n][f 5 15][w][e]

[msg MSG_400_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ma隠ana has quedado con todos[n]en Harajuku. Deber胤as descansar,[n]斡no vayas a quedarte dormido![n][f 1 3 65535][w][e]

[msg MSG_401_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Conque a Harajuku, 夷eh?[n]Vayamos al sitio acordado.[n][f 1 3 65535][w][e]

[msg MSG_402_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]No vas a ir, 夷eh?[n]夷Ya ten胤as planes?[n][f 1 3 65535][w][e]

[msg MSG_403_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Lo dejas para luego, 夷eh?[n]Acu姻rdate de contestarle.[n][f 1 3 65535][w][e]

[msg ERROR_MSG_000_0_0 [Sojiro]]
[s][bup 0 103 2 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Oye, estoy a punto de abrir.[n]夷Puedes dejar[n]de trastear con el m吋vil?[n][w][e]

[msg ERROR_MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]El jefe se ha enfadado contigo.[n]Ser茨 mejor que respondas luego.[n][w][e]

[msg MND_CHAT_INVITE_STOP]
[s]Ahora estoy comiendo.[n]Ser茨 mejor que responda luego.[n][w][e]

[msg MND_COOP_RANK_UP_OK]
[s]Siento que mi v胤nculo con [var 7][n]se fortalecer茨 pronto.[n][w][e]

[msg MND_COOP_RANK_UP_ROCK]
[s]Siento que mi v胤nculo con [var 7][n]se fortalecer茨 pronto, pero...[n][w][e]

[msg MND_COOP_RANKUP_2]
[s]Esta puede ser una buena[n]oportunidad para fortalecer[n]mi v胤nculo con [var 7].[n][w][e]

[msg MND_COOP_DOUZOKUSEI_HAVE]
[s]Gracias a la Persona del arcano[n][var 2], [clr 1][var 5][clr 27],[n]puedo estrechar lazos con [var 7].[n][w][e]

[msg MSG_SPOT_OPEN_KANDA]
[s]Ya puedes ir a [clr 2]Kanda[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_SHINJUKU]
[s]Ya puedes ir a [clr 2]Shinjuku[clr 27].[n][w][e]

[msg MSG_SPOT_OPEN_AKIHABARA]
[s]Ya puedes ir a [clr 2]Akihabara[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el santuario[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_INOKASHIRA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Parque Inokashira[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el parque[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_OGIKUBO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Ogikubo Ramen[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el ramen[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ODAIBA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Parque Seaside de Odaiba[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste este tipo[n]de parques para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_UENO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Museo Ueno[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le gusten los museos[n]de arte para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_TSUKISHIMA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Tsukishima Monja[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el monjayaki[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_HARAJUKU]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]calle Takenoko de Harajuku[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente a[n]la que le guste la calle Takenoko[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_TYUKAGAI]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Chinatown de Motomachi[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste ese lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MAIHAMA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Destinyland de Maihama[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le gusten las atracciones[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Asakusa[clr 27].[n][w][e]
[s]Puedes invitar a gente a la que le[n]guste la Skytree o la calle[n]Nakamise para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_IKEBUKURO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Planetario de Ikebukuro[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el planetario[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_MEIJIJINGU]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Santuario Meiji[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el santuario[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir por tu cuenta[n]para venerarlo.[n][w][e]

[msg MSG_SPOT_OPEN_SUIDOUBASH]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Dome Town de Suidobashi[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste ese lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_SHIBUYA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Hotel Wilton de Shibuya[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste ese lugar[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_GINZA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]restaurante de sushi de Ginza[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el sushi caro[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_JINBOCHO]
[s]Tienes informaci吋n sobre un nuevo[n]punto de encuentro: [clr 2]La ciudad[n]de los libros de Jinbocho[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste ese lugar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir por tu cuenta[n]a comprar.[n][w][e]

[msg MSG_SPOT_OPEN_ICHIGAYA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Estanque Ichigaya[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste pescar[n]para que vaya contigo.[n][w][e]
[s]Adem茨s, puedes ir[n]por tu cuenta para ver[n]qu姻 tal se te da pescar.[n][w][e]

[msg MSG_SPOT_OPEN_SHINAGAWA]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]Acuario de Shinagawa[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste el acuario[n]para que vaya contigo.[n][w][e]

[msg MSG_SPOT_OPEN_NAKANO]
[s]Tienes informaci吋n[n]sobre un nuevo punto de encuentro:[n][clr 2]zona comercial de Nakano[clr 27].[n][w][e]
[s]Tambi姻n puedes invitar a gente[n]a la que le guste ese lugar[n]para que vaya contigo.[n][w][e]

