[msg MSG_000_0_0 [Ann]]
[s][f 5 14]No has o胤do nada de la presidenta[n]del consejo estudiantil, 夷verdad?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Do隠a Alumna Honor胤fica estar茨[n]lamiendo culos por ah胤.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Tampoco hay que pasarse...[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]夷Qu姻 es eso de una presidenta[n]del consejo estudiantil?[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]La de nuestro instituto[n]nos tiene vigilados.[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]Creo que sospecha de nosotros.[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]夷Seguro que no se debe simplemente[n]al mal comportamiento habitual[n]de Ryuji?[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]斡Cierra el pico![n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]Aunque la verdad es que[n]los tres llam茨is la atenci吋n.[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Ten姻is que andar con cuidado.[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]Ya sab姻is que no puedo hacer nada[n]para ayudaros en el instituto.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Esa tarea depende de ti,[n][f 4 2].[n][w][e]

[sel SEL_012_0_0 top]
[s][f 5 14]Lo pillo.[e]
[s]No te preocupes.[e]

[msg MSG_013_0_0 [Ann]]
[s][f 5 14]Tambi姻n me asegurar姻[n]de vigilar a Ryuji.[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14][f 5 15]夷Por qu姻 la tomas conmigo...?[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Los dem茨s te hacen sombra a veces,[n]pero recuerda,[n]t雨 tambi姻n eres famoso.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0]威ndate con cuidado, 夷vale?[n][f 1 3 65535][w][e]

