[msg MSG_000_0_0 [Ann]]
[s][f 5 14]No s姻 muy bien c吋mo decirlo...[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Quedemos, solo t雨 y yo.[n]No hace falta cont茨rselo[n]a los dem茨s.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]夷Y si salimos a cenar[n]y despu姻s vamos a tu habitaci吋n?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Me parece genial.[e]

[msg MSG_020_0_0 [Ann]]
[s][f 5 14]斡Yuju![n][w][e]

[msg MSG_021_0_0 [Ann]]
[s][f 5 14]Te espero[n]en la estaci吋n de Shibuya.[n][f 5 15][w][e]

