[msg MSG_000_0_0 [Haru]]
[s][f 5 14]No s姻 por qu姻, pero algo[n]me inquieta por alg雨n motivo...[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Conseguimos despertar el coraz吋n[n]de Shido, pero las reacciones...[n]podr胤an haber sido mejores.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]S胤, ha costado mucho[n]poder relajarse.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Me pregunto si la gente se sentir茨[n]decepcionada al enterarse de cu茨l[n]es su verdadera naturaleza.[n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]Quiz茨 sea m茨s[n]que una simple decepci吋n.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]斡En cualquier caso, es mejor eso[n]a que siga enga隠ando a la gente![n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Pero aunque su verdadera[n]naturaleza se d姻 a conocer...[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Me pregunto qu姻 resultados[n]tendr茨n estas elecciones...[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Supongo que ya veremos.[e]
[s]Qui姻n sabe.[e]

[msg MSG_009_0_0 [Ann]]
[s][f 5 14]La verdad es que no se han[n]presentado grandes pol胤ticos, pero[n]斡cualquiera ser胤a mejor que Shido![n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]Pero vivir preocupados[n]por ello no cambiar茨 nada.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Bueno, esperemos a que despierte.[n]Ya hablaremos cuando eso pase.[n][w][e]

