[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]夷Vas a ir a la fiesta de despu姻s[n]del festival con alguien?[n][w][e]

[msg MSG_000_5_0 [Mishima]]
[s][f 5 14]Yo voy con Ryuji,[n]pero que vayamos los dos solos[n]va a ser un poco raro...[n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]夷C吋mo se llama? 夷Kitagawa?[n]El de la excursi吋n, digo.[n]Va a volver...[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Cuento contigo, as胤 que ven[n]al gimnasio, 夷vale? 斡S茨lvame![n][w][e]

