[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]斡Tengo informaci吋n nueva![n][w][e]
[s][f 5 14]Parece que hay un grupo de ladrones[n]aterrorizando Shibuya.[n][w][e]
[s][f 5 14]Al parecer, solo roban[n]en restaurantes y entran[n]despu姻s del cierre.[n][w][e]
[s][f 5 14]En internet, una persona[n]pregunt吋 si era cosa[n]de los Ladrones Fantasma...[n][w][e]
[s][f 5 14]斡Qu姻 cabreo me pill姻 al leerlo![n][w][e]
[s][f 5 14]No podemos dejar que os metan[n]en el mismo saco[n]que a unos ladronzuelos, 斡夷no?![n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Imposible.[e]
[s]夷Acaso no somos iguales?[e]
[s]Olv胤dalo.[e]

[msg MSG_006_0_0 [Mishima]]
[s][f 5 14]斡S胤! 斡Vosotros sois mucho mejores[n]que esos capullos![n][w][e]

[msg MSG_007_0_0 [Mishima]]
[s][f 5 14]斡夷Qu姻?! 斡No es posible[n]que creas eso![n][w][e]

[msg MSG_010_0_0 [Mishima]]
[s][f 5 14]Escuchar eso me hace sentir peor.[n][w][e]

[msg MSG_012_0_0 [Mishima]]
[s][f 5 14]Bueno, he o胤do que han estado[n]huyendo sin dejar rastro.[n][w][e]
[s][f 5 14]Esa es toda la informaci吋n[n]que tengo por ahora... Lo siento.[n][w][e]
[s][f 5 14][f 5 15]Puede que la gente sepa m茨s. Har姻[n]una publicaci吋n en la Fansite[n]para pedir m茨s informaci吋n.[n][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 2 65535 1038 0 0]Vaya, ser famoso[n]conlleva sus propios problemas...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Pero no tenemos informaci吋n.[n]Tocar茨 esperar a que Mishima[n]consiga una buena pista.[n][f 1 3 65535][w][e]

