[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14][f 5 19]斡Se me hab胤a olvidado subir[n]la foto que he hecho hoy![n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14][f 5 18 275 1 1][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]斡Oye, no est茨 mal![n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]斡夷A que s胤?! 斡Parece que[n]he nacido para esto![n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Espero que no lo digas en serio.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Una pena lo de la lluvia, pero[n]al menos vamos a recordar[n]este d胤a.[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]斡S胤! Pero 斡la pr吋xima vez no[n]podemos perdernos los fuegos![n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]Coincido.[n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Me impresiona lo r茨pido que[n]empeor吋 el tiempo.[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Quiz茨 alguno de nosotros es gafe[n]y atrae la lluvia all茨 donde vaya.[n][w][e]

