[msg MSG_CHAT_quest27_00 [Ryuji]]
[s][f 5 14]夷Qu姻 hacemos con el tramposo?[n]Estamos jodidos si nuestros ataques[n]no le afectan.[n][w][e]

[msg MSG_CHAT_quest27_01 [Yusuke]]
[s][f 5 14]No hay quien le tosa[n]en el juego, as胤 que tambi姻n[n]es invencible en Mementos...[n][w][e]

[msg MSG_CHAT_quest27_02 [Ann]]
[s][f 5 14]夷Por qu姻 no lo derrotamos[n]en su juego? Ah, no,[n]que har茨 trampas...[n][w][e]

[msg MSG_CHAT_quest27_03 [Futaba]]
[s][f 5 14]夷Y si le pedimos ayuda[n]a un experto en ese juego?[n][w][e]

[msg MSG_CHAT_quest27_04 [Futaba]]
[s][f 5 14]Dicen que hay un t胤o que es[n]buen胤simo. Lo llaman 或Rey位, y est茨[n]en alg雨n lugar de la ciudad.[n][w][e]

[msg MSG_CHAT_quest27_05 [Futaba]]
[s][f 5 14]En los foros de internet no paran[n]de hablar de c吋mo derrot吋[n]al tramposo de manera limpia.[n][w][e]

[msg MSG_CHAT_quest27_06 [Ryuji]]
[s][f 5 14]斡夷En serio?! 夷Y d吋nde est茨?[n][w][e]

[msg MSG_CHAT_quest27_07 [Futaba]]
[s][f 5 14]He investigado su cuenta[n]en el servidor oficial...[n][w][e]

[msg MSG_CHAT_quest27_08 [Futaba]]
[s][f 5 14]Aun as胤, no he podido dar[n]con los recreativos a los que va.[n]Lo siento...[n][w][e]

[msg MSG_CHAT_quest27_09 [Ann]]
[s][f 5 14]Pero si es tan famoso,[n]夷encontrarlo no ser茨 pan comido?[n][w][e]

[msg MSG_CHAT_quest27_10 [Makoto]]
[s][f 5 14]Tienes raz吋n. Venga, debemos reunir[n]informaci吋n sobre el Rey[n]en los recreativos de la ciudad.[n][f 5 15][w][e]

[msg MSG_CHAT_quest27_14 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1021 65535 0]No sab胤a que alguien[n]pudiera hacerse famoso[n]por jugar a un videojuego.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Pero parece que podremos[n]completar la solicitud si damos con[n]ese tal Rey.[n][f 1 3 65535][w][e]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1106 65535 0]斡Con su ayuda, destrozaremos[n]a ese tramposo de una maldita vez![n][f 1 3 65535][w][e]

