[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]Algo no va bien.[n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]No hay movimiento en la Web[n]del Aficionado de los Fantasmas...[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]No tiene sentido.[n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]夷Por?[e]
[s]No me interesa.[e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]Quiero decir...[n][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][f 5 14]Venga, p茨rate a pensarlo.[n][w][e]

[msg MSG_006_0_0 [Mishima]]
[s][f 5 14]斡Le han parado los pies[n]a Masayoshi Shido![n][w][e]

[msg MSG_007_0_0 [Mishima]]
[s][f 5 14]斡La gente deber胤a estar[n]como loca poniendo comentarios![n]斡Es absurdo que haya tanta calma![n][w][e]

[msg MSG_008_0_0 [Mishima]]
[s][f 5 14]夷Es porque no ha salido[n]en las noticias?[n][w][e]

[msg MSG_009_0_0 [Mishima]]
[s][f 5 14][f 5 15]Uf, pero 斡es que es obvio que es[n]cosa de los Ladrones Fantasma...![n][w][e]

