[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]夷Morgana ha entrado en el Palacio[n]de Okumura? 夷Es eso cierto, Futaba?[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Ha dicho que quer胤a ir solo.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]夷Eso significa que corre peligro?[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Es muy probable.[n][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][f 5 14]S胤. Deber胤amos ir todos tras 姻l.[n][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]Seguramente el Palacio estar茨[n]en su sede central.[n]Investigar姻 un poco m茨s.[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Muy bien, 斡a por todas![n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Tambi姻n deber胤amos investigar[n]esas cosas de desconexi吋n mental.[n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Yo preferir胤a algo m茨s de cautela,[n]pero esto es una emergencia...[n][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][f 5 14][f 5 15]Entonces iremos ma隠ana.[n]Que nadie lo olvide.[n][w][e]

