[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Lo investigamos.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]夷Te refieres al sitio ese al que[n]fuiste con Makoto y con Futaba?[n]夷C吋mo fue la cosa?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Hay algo que nos gustar胤a[n]intentar.[n][w][e]
[s][f 5 14]Es una apuesta arriesgada,[n]pero, si sale bien, averiguaremos[n]qui姻n es el responsable de todo.[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]斡夷En serio?![n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]S胤, lo vamos a mandar[n]para all茨.[n]Ya ver茨s qu姻 sorpresa.[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]As胤 que vamos derechitos[n]a la trampa, y a sabiendas.[n]Es muy peligroso.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Mi hermana estar茨 a cargo[n]del interrogatorio.[n][w][e]
[s][f 5 14]Que le muestre[n]el tel姻fono manipulado por[n]Futaba deber胤a funcionar.[n][w][e]

[sel SEL_007_0_0 top]
[s][f 5 14]夷T雨 crees?[e]
[s]夷Cu茨l es la probabilidad de 姻xito?[e]
[s]No quiero morir.[e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]No puedo asegurarlo al 100 %,[n]pero s胤.[n][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]Si tuviera que elegir,[n]ser胤a 0 % o 100 %.[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]S胤, yo me siento igual.[n][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][f 5 14]La verdad es que todo el trabajo[n]duro le va a tocar a [f 4 2].[n][w][e]

[msg MSG_012_0_0 [Haru]]
[s][f 5 14]夷Seguro? Me gustar胤a ocuparme[n]yo, si puede ser.[n][w][e]
[s][f 5 14]Har姻 lo que haga falta[n]para encontrar al responsable.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Es demasiado peligroso.[n]Mejor d姻jame[n]las cosas chungas a m胤.[n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14]Para esta operaci吋n necesitaremos a[n]alguien con excelentes[n]dotes para la negociaci吋n.[n][w][e]
[s][f 5 14]Es m茨s, quien se encargue[n]tendr茨 que crear distracciones[n]dentro del propio Palacio.[n][w][e]
[s][f 5 14]Solo puedo confiarle a[n][f 4 2] una tarea as胤.[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Es verdad, pero...[n][w][e]
[s][f 5 14]夷T雨 qu姻 dices, [f 4 2]?[n][w][e]

[sel SEL_016_0_0 top]
[s][f 5 14]No me queda otra.[e]
[s]夷Es que no hay otra forma?[e]
[s]Dej茨dmelo a m胤.[e]

[msg MSG_017_0_0 [Ryuji]]
[s][f 5 14]Ya, tienes raz吋n.[n][w][e]
[s][f 5 14]Tampoco es que nos sobre[n]tiempo como para estar dudando.[n][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][f 5 14]Si lo pintas as胤...[n][w][e]
[s][f 5 14]No, no se me ocurre nada.[n][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][f 5 14]En fin, pero que conste[n]que t雨 lo has querido.[n][w][e]

[msg MSG_020_0_0 [Ann]]
[s][f 5 14]No te preocupes, nos aseguraremos[n]de que todo est姻 listo.[n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][f 5 14]Todo tuyo.[n][w][e]

[msg MSG_022_0_0 [Futaba]]
[s][f 5 14][f 5 15]Solo tenemos una oportunidad.[n]斡Hay que conseguirlo![n][w][e]

