[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Como estamos de vacaciones,[n]voy a ir al Leblanc[n]ma隠ana por la tarde.[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Es un sitio fresco y tranquilo,[n]y es relajante tener all胤[n]el 或Sayuri位. Es un remanso de paz.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Estoy pensando en relajarme[n]y leer un libro.[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Adem茨s, podemos reunirnos[n]con facilidad si pasa algo.[n]Matamos dos p茨jaros de un tiro.[n][w][e]
[s][f 5 14]No te preocupes si ya tienes[n]planes, me pasar姻 de todas maneras.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Si te apetece,[n]podemos quedar un rato.[n][f 5 15][w][e]

[msg MSG_999_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Yusuke viene ma隠ana, 夷no? Podr胤a[n]estar bien pasar el rato con 姻l.[n][f 1 3 65535][w][e]

[msg MSG_999_1_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]*bostezo* Me voy a la cama...[n][f 1 3 65535][w][e]

