[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]No olvid姻is prepararos[n]para el viaje, 夷vale?[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]T胤a, ni que fueras la profe.[n]夷Por qu姻 dices eso?[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]夷No os lo he contado?[n]Yo tambi姻n voy.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]夷Qu姻?[n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]Los profesores me han pedido[n]que os acompa隠e en su lugar.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Espera, 斡夷qu姻?![n]斡No sab胤a nada de eso![n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]夷Hay alg雨n problema?[n][w][e]

[sel SEL_007_0_0 top]
[s][f 5 14]Me alegra que vayamos juntos.[e]
[s]Se nos ha fastidiado el viaje...[e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]S胤. Estaba preocupada[n]por los gamberros que ir茨n.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]斡夷Hablas de nosotros?![n][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]Me asegurar姻 de vigilaros[n]para que la experiencia[n]sea agradable para todos.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]No tienes que vigilarnos...[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]夷Pero por qu姻 te env胤an[n]a ti, Makoto?[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14]Algunos profesores tienen que[n]quedarse para lidiar con ese asunto[n]del art胤culo sensacionalista.[n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14]As胤 que han decidido enviar[n]a un par de alumnos de tercero[n]como acompa隠antes adicionales.[n][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][f 5 14]Tambi姻n vienen otros alumnos,[n]aparte de m胤.[n][w][e]

[msg MSG_016_0_0 [Ann]]
[s][f 5 14]Ah, ya veo.[n][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][f 5 14]En cualquier caso, todos ten胤amos[n]ganas de que llegara este viaje.[n][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][f 5 14]Creo que salir de Jap吋n[n]ser茨 una experiencia[n]esclarecedora para todos.[n][w][e]

[msg MSG_019_0_0 [Yusuke]]
[s][f 5 14]Es una oportunidad magn胤fica,[n]y debemos disfrutarla al m茨ximo.[n][w][e]

[msg MSG_020_0_0 [Futaba]]
[s][f 5 14][f 5 15]斡No olvid姻is traerme un souvenir![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]

