[msg MSG_OKUMURA_MAEOKI [Mishima]]
[s][f 5 14]Oye, perdona que hable de esto[n]en medio de tanto l胤o...[n][w][e]
[s][f 5 14]S姻 que no ha sido f茨cil despu姻s de[n]lo que le ha pasado al presidente[n]Okumura y tal...[n][w][e]
[s][f 5 14]Pero despertar el coraz吋n a[n]otra gente os ayudar胤a[n]con vuestra reputaci吋n.[n][w][e]
[s][f 5 14]Bueno, aqu胤 tienes informaci吋n...[n][w][e]

[msg MSG_SIMEITEHAI_MAEOKI [Mishima]]
[s][f 5 14]Oye, perdona que saque esto[n]ahora que est茨s ocupado, pero...[n][w][e]
[s][f 5 14][f 4 28] puede hacerlo.[n]Conf胤o en vosotros.[n][w][e]
[s][f 5 14]Bueno, aqu胤 tienes informaci吋n...[n][w][e]

[msg MSG_062_0_0 [Mishima]]
[s][f 5 14]斡Este es muy especial![n][w][e]
[s][f 5 14]No est茨 ni en el foro todav胤a.[n][w][e]
[s][f 5 14]En fin, 夷te acuerdas del tal[n]Daisuke Takanashi cuyo coraz吋n[n]despertaste?[n][w][e]
[s][f 5 14]斡Pues resulta que[n]hab胤a alguien detr茨s[n]de ese asunto todo el tiempo![n][w][e]
[s][f 5 14]Parece que Takanashi no[n]pod胤a hacer otra cosa[n]que no fuera obedecer.[n][w][e]
[s][f 5 14]Hacer que alguien moleste[n]a los dem茨s es de ser mala gente,[n]夷no te parece?[n][w][e]

[sel SEL_063_0_0 top]
[s][f 5 14]Es horrible.[e]
[s]Es inteligente.[e]
[s]La verdad es que no.[e]

[msg MSG_064_0_0 [Mishima]]
[s][f 5 14]斡夷Verdad?! Es inaceptable.[n][w][e]

[msg MSG_065_0_0 [Mishima]]
[s][f 5 14]S胤, pero no puedo perdonar[n]algo tan horroroso.[n][w][e]

[msg MSG_066_0_0 [Mishima]]
[s][f 5 14]Me temo que esta vez no estoy[n]de acuerdo contigo.[n]Es un acto inaceptable.[n][w][e]

[msg MSG_067_0_0 [Mishima]]
[s][f 5 14]Esta persona tiene que estar en[n]alg雨n lugar del instituto, 夷no?[n]Ve a echar un vistazo.[n][w][e]
[s][f 5 14][f 5 15]斡Yo tambi姻n[n]indagar姻 mientras tanto![n][w][e]

[msg MSG_quest12_MORGANA_SAY [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Si queremos ir a por este objetivo,[n]necesitaremos un nombre.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Investiguemos por el instituto.[n][f 1 3 65535][w][e]

[msg MND_quest12_OPEN_SELF]
[s][vp 8 2 65535 0 0 0]Parece que hay un objetivo[n]en el instituto. Tendr胤a que ir[n]a ver c吋mo se llama...[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Dummy scriptChat_227[e]

