[msg MSG_000_0_0 [Maruki]]
[s][f 5 14]夷Te acuerdas de cuando[n]hablamos de mi investigaci吋n?[n][w][e]

[msg MSG_001_0_0 [Maruki]]
[s][f 5 14]夷Tienes un rato libre hoy[n]despu姻s de clase?[n][w][e]
[s][f 5 14]Estar姻 un rato en la enfermer胤a,[n]as胤 que te agradecer胤a mucho[n]si te pasaras por all胤 para hablar.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Maruki[n]est茨 esperando en la enfermer胤a.[n]夷Quieres ir a verlo?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Ahora mismo voy.[e]

[msg MSG_REACTION [Maruki]]
[s][f 5 14]Me alegra escuchar eso. Gracias.[n][f 5 15][w][e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Maruki[n]est茨 esperando en la enfermer胤a.[n]夷Quieres ir a verlo?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Parece que Maruki[n]est茨 esperando en la enfermer胤a.[n]夷Quieres ir a verlo?[n][w][e]

