[msg MSG_000_0_0 [Ann]]
[s][f 5 14]No habr茨 intentado nada raro[n]ese asqueroso, 夷verdad, Haru?[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]No, estoy bien.[n]Gracias por preguntar, Ann.[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Padre dijo que tambi姻n retirar胤a[n]la proposici吋n de matrimonio.[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Aunque me preocupa un poco...[n]A雨n queda algo de tiempo[n]hasta la fecha l胤mite.[n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]Av胤sanos si pasa algo, por favor.[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]Gracias, Mako.[n]Confiar姻 en vosotros sin dudarlo.[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]Tambi姻n est茨 la cuesti吋n[n]de la desconexi吋n mental.[n]Espero que Haru no corra peligro...[n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]Supongo que el padre de Haru dijo[n]que solo daba la orden.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]S胤, el verdadero culpable[n]sigue ah胤 fuera provocando[n]desconexiones mentales por dinero.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]Sea quien sea, hay que pillarlo...[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]夷Alguna idea de qui姻n puede ser,[n][f 4 2]?[n][w][e]

[sel SEL_011_0_0 top]
[s][f 5 14]La persona de la m茨scara negra.[e]
[s]Alguien obsesionado con el dinero.[e]
[s]Ni idea.[e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14]S胤, sin duda es quien m茨s[n]probabilidades tenga de serlo.[n][w][e]

[msg MSG_013_0_0 [Yusuke]]
[s][f 5 14]Realizar desconexiones mentales[n]para enriquecerse es un acto[n]verdaderamente zafio...[n][w][e]

[msg MSG_014_0_0 [Ann]]
[s][f 5 14]En fin, seguro que sabremos m茨s[n]cuando el padre de Haru[n]hable del tema.[n][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][f 5 14][f 5 15]斡Solo hay que esperar[n]a que despierte![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Futaba tiene raz吋n.[n]No tenemos informaci吋n,[n]as胤 que no podemos hacer nada.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Esperemos a que Okumura despierte[n]y luego descubriremos la verdad[n]sobre las desconexiones mentales.[n][f 1 3 65535][w][e]

