[msg MSG_000_0_0 [Hifumi]]
[s][f 5 14]Estamos en Navidad. La iglesia[n]tambi姻n est茨 hasta arriba.[n][w][e]

[msg MSG_001_0_0 [Hifumi]]
[s][f 5 14]Las parejas suelen pasar[n]esta 姻poca juntas, 夷no?[n][w][e]

[msg MSG_002_0_0 [Hifumi]]
[s][f 5 14]夷Podemos vernos ahora?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Me apunto a pasar el rato.[e]

[msg MSG_020_0_0 [Hifumi]]
[s][f 5 14]Gracias. La verdad[n]es que estoy un poco nerviosa.[n][w][e]

[msg MSG_021_0_0 [Hifumi]]
[s][f 5 14]Nos vemos en Shibuya.[n]Estar姻 delante de la estaci吋n.[n][f 5 15][w][e]

