[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]Ya va siendo hora de saber el[n]resultado de la desconexi吋n mental,[n]pero solo podemos esperar.[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Por cierto,[n]夷conoces alg雨n buen santuario?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Se me ocurri吋 visitar alguno[n]por si me inspiraba.[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Ma隠ana es [var 0],[n]as胤 que me gustar胤a que[n]me hicieras de gu胤a, si quieres.[n][f 5 15][w][e]

[msg MSG_100_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Mmm... Podr胤as ir a alg雨n sitio[n]con Yusuke,[n]ya que tienes el d胤a libre...[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Pero nunca has visitado[n]un santuario, 夷verdad?[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Deber胤as investigar[n]en una librer胤a. Vaya... Tendr茨s que[n]rechazar la propuesta de Yusuke.[n][f 1 3 65535][w][e]

[msg MSG_101_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]夷Qu姻 te parece el Santuario Meiji?[n]Nunca has ido con 姻l, 夷no?[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0]夷Y bien? 夷Qu姻 te parece?[n]夷Quieres ir ma隠ana con Yusuke[n]al [clr 2]Santuario Meiji[clr 27]?[n][f 1 3 65535][w][e]

[sel SEL_111_0_0 top]
[s]Comprometerse[e]
[s]Rechazar[e]
[s]Responder luego[e]

[sel SEL_111_1_0 top]
[s]Ir de inmediato[e]
[s]Rechazar[e]
[s]Responder luego[e]

[sel SEL_200_0_0 top]
[s][f 5 14]Vayamos al Santuario Meiji.[e]
[s]Tengo planes.[e]
[s]No conozco ning雨n buen sitio.[e]

[msg MSG_201_0_0 [Yusuke]]
[s][f 5 14]El Santuario Meiji, 夷eh?[n]No est茨 mal.[n][w][e]

[msg MSG_202_0_0 [Yusuke]]
[s][f 5 14]Perdona por avisarte tan tarde.[n]Nos vemos ma隠ana.[n][f 5 15][w][e]

[msg MSG_201_1_0 [Yusuke]]
[s][f 5 14]El Santuario Meiji, 夷eh?[n]Pues nos vemos en Shibuya.[n][f 5 15][w][e]

[msg MSG_210_0_0 [Yusuke]]
[s][f 5 14]Ya veo. Perdona[n]la invitaci吋n repentina.[n][f 5 15][w][e]

[msg MSG_400_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Conque ma隠ana vas con Yusuke[n]al Santuario Meiji, 夷eh? Es[n]festivo, as胤 que habr茨 mucha gente.[n][f 1 3 65535][w][e]

[msg MSG_401_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Vas al Santuario Meiji, 夷eh?[n]Vayamos al sitio acordado.[n][f 1 3 65535][w][e]

[msg MSG_402_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]No vas a ir, 夷eh?[n]夷Ya ten胤as planes?[n][f 1 3 65535][w][e]

[msg MSG_403_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Lo dejas para luego, 夷eh?[n]Acu姻rdate de contestarle.[n][f 1 3 65535][w][e]

