[msg MSG_000_0_0 [Takemi]]
[s][f 5 14]Como doctora, no me interesa[n]mucho la Nochebuena...[n][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][f 5 14]Pero supon胤a que querr胤as[n]hacer algo en pareja.[n][w][e]

[msg MSG_002_0_0 [Takemi]]
[s][f 5 14]No me importar胤a[n]que pas茨ramos la noche juntos...[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Vale, hacemos eso.[e]

[msg MSG_020_0_0 [Takemi]]
[s][f 5 14]Gracias. Cerrar姻 pronto la cl胤nica.[n][w][e]

[msg MSG_021_0_0 [Takemi]]
[s][f 5 14]Voy para Shibuya, as胤 que[n]nos vemos frente a la estaci吋n.[n][f 5 15][w][e]

