[msg MSG_000_0_9 [Ryuji]]
[s][f 5 14]クエスト挙動確認用に[n]デバッグ用チャット[n][w][e]

[msg MSG_000_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Le he echado un vistazo[n]a la Fansite mientras dorm胤as.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s]夷Con tus patitas?[e]
[s]夷Algo interesante?[e]
[s]斡Me vas a pagar t雨 los datos![e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Apenas puedo escribir,[n]pero s胤 deslizar la pantalla[n]arriba y abajo.[n][f 1 3 65535][w][e]

[msg MSG_002_1_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]En fin, he visto un mensaje[n]que me ha llamado la atenci吋n.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]S胤, he encontrado algo.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]斡Sab胤a que dir胤as eso![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]斡D姻jate de tonter胤as y escucha![n]He visto un mensaje interesante[n]en el foro.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Han desaparecido un mont吋n[n]de gatos en Yongen. Los due隠os[n]creen que los han raptado.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s]夷Qui姻n es el culpable?[e]
[s]夷Sabemos su nombre?[e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]La sospechosa es una oficinista,[n]una tal Neko Nora. En su casa[n]se oyen muchos maullidos.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Ya ha raptado gatos antes.[n]Por lo visto, tuvo que intervenir[n]la polic胤a y todo.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Pero no es tan f茨cil como parece.[n]Estaba preocupado por los gatos,[n]as胤 que fui a ver su habitaci吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]斡Y estaban zampando pienso[n]gourmet! La oficinista los miraba[n]con una felicidad...[n][f 1 3 65535][w][e]

[sel SEL_008_0_0 top]
[s]夷Qu姻 est茨 pasando?[e]
[s]Qu姻 raro.[e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Hay que averiguar por qu姻[n]lo ha hecho. Visto lo visto,[n]no parece mala persona.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]夷Buscamos m茨s informaci吋n[n]y luego vamos a Mementos?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]A ser posible, preferir胤a evitar[n]el uso la violencia.[n]Quiz茨 podamos persuadirla.[n][f 1 3 65535][w][e]

[msg SYS_010_0_0]
[s]En ocasiones, podr茨s despertar el[n]coraz吋n del objetivo sin violencia[n]y hablando durante el combate.[n][w][e]
[s]Para que salga bien,[n]tendr茨s que recabar informaci吋n[n]en el mundo real.[n][w][e]
[s]Habla con la gente y recaba[n]informaci吋n que ayude a despertar[n]el coraz吋n del objetivo.[n][w][e]

[msg HELP_MEMENTOS_MISSION_04 [斡Solicitud recibida!]]
[s][clr 4]Informaci吋n de objetivo conseguida[clr 27][n]Ahora puedes enviar avisos desde[n]el [clr 2]escondite[clr 27]. As胤 tus [clr 3]compa隠eros[clr 27][n]podr茨n proporcionarte informaci吋n.[n][w][e]

[msg SYS_000_0_0]
[s]こちらのクエストのセリフは[n]チャットだけでなく[n]全て仮になっています[n][w][e]
[s]シナリオチームの監修後、[n]変更がかかる予定ですので[n]セリフに関しては無視してください[n][w][e]

