[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Vaya donde vaya,[n]solo hay rumores de Shido.[n]Me pone de mala hostia.[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Es como si su postura[n]contra los Ladrones Fantasma[n]aumentara su popularidad.[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Pero 斡es todo una farsa![n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Es m茨s, 夷por qu姻 nadie[n]se est茨 quejando de la polic胤a?[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]El mayor criminal que han atrapado[n]se suicid吋 bajo su vigilancia.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Lo mires por donde lo mires,[n]es un esc茨ndalo.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Yo solo me alegro de que no[n]revelaran la identidad de[n][f 4 2].[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]En cuanto a eso...,[n]夷no os parece un poco raro?[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]S胤.[e]
[s]夷A qu姻 te refieres?[e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]夷Por qu姻 nadie muestra inter姻s[n]por la identidad o las intenciones[n]de los Ladrones Fantasma?[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]夷Acaso no piensa la gente[n]que est茨n detr茨s[n]de los 雨ltimos cr胤menes?[n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14]S胤, cualquiera pensar胤a que[n]se montar胤a m茨s revuelo por eso.[n][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14]Yo tambi姻n lo he pensado.[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14]Es como si la conmoci吋n que[n]rodeaba al suicidio se hubiera[n]calmado muy r茨pido...[n][w][e]

[msg MSG_014_0_0 [Ann]]
[s][f 5 14]Parece que a nadie[n]le importa ya eso.[n][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][f 5 14]S胤. Est茨n demasiado ocupados[n]lami姻ndole el culo a Shido.[n][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Esto no tiene ning雨n sentido.[n]Da much胤sima grima...[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][vp 1 0 0 0 0 0]......[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Tienen raz吋n, esto es muy raro.[n]夷Qu姻 est茨 pasando?[n][f 1 3 65535][w][e]

