[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Me pas姻 por la tienda de accesorios[n]de camino a casa.[n][w][e]
[s][f 5 14]斡Y adivina! La mujer estaba[n]disculp茨ndose justo cuanto entr姻.[n][w][e]
[s][f 5 14]Al due隠o de la tienda[n]le va a ir de co隠a.[n][w][e]
[s][f 5 14]C吋mo mola ser Ladr吋n Fantasma, t胤o.[n]As胤 puedo proteger[n]a mis seres queridos.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Caso cerrado.[e]
[s]Le echar姻 un vistazo a la tienda.[e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14][f 5 15]斡Es un peso que me quito[n]de encima![n]斡Deber胤as pasarte alguna vez![n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14][f 5 15]斡Eso! P胤llate algo que te d姻[n]un aire de tipo duro.[n][w][e]

[msg MSG_004_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]夷Una tienda de accesorios?[n]Ser茨 la que est茨 enfrente[n]del gimnasio de Shibuya.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 8 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]夷Crees que tendr茨n accesorios[n]para gatos?[n][f 1 3 65535][w][e]

