[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]斡夷C吋mo que lo sabe todo?![n]斡Tienes que estar de puta co隠a![n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Espera, 夷est茨s bien?[n]夷Te ha denunciado o algo?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]No estar胤amos recibiendo estos[n]mensajes si [f 4 2][n]no estuviera bien.[n][w][e]
[s][f 5 14]Yo ten胤a la sensaci吋n de que el[n]Jefe no era un tipo normal.[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]Pero 姻l no te recomend吋 que[n]te entregaras, 夷verdad?[n][w][e]
[s][f 5 14]En tal caso, creo que podemos[n]considerarlo un nuevo aliado.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Tengo curiosidad por saber[n]qu姻 te ha dicho.[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]夷Te refieres a que nuestros[n]enemigos podr胤an ser los mismos[n]que se cargaron a la madre de Futaba?[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]S胤. Muri吋 de una desconexi吋n[n]mental, el mismo m姻todo que usa[n]la persona a la que buscamos.[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Un segundo...[n]夷No dijiste que el Jefe tuvo[n]que huir de todo?[n][w][e]
[s][f 5 14]夷Significa eso que alguien estaba[n]ocultando las noticias?[n]夷Qui姻n har胤a algo as胤?[n][w][e]
[s][f 5 14]夷Qui姻n crees que podr胤a[n]ser el culpable?[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Un funcionario del gobierno.[e]
[s]Alguien poderoso.[e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]夷No est茨s dejando volar[n]tu imaginaci吋n un poquito demasiado?[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]Pero tiene sentido.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]斡Un momento! Si llevas raz吋n,[n]斡夷la polic胤a no estar胤a[n]metida en el ajo tambi姻n?![n][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14]Es posible.[n][w][e]

[msg MSG_013_0_0 [Ann]]
[s][f 5 14]Esto es demasiado para m胤...[n][w][e]

[msg MSG_014_0_0 [Haru]]
[s][f 5 14][f 5 15]夷Acaso podemos ganar?[n][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 1 65535 0]斡Ganaremos sea como sea![n][f 1 3 65535][w][e]

