[msg MSG_CHAT_quest19_clear_0 [Mishima]]
[s][f 5 14]斡Has salvado el cine de Yongen![n]斡Ya nadie amenaza con desahuciar[n]a la pareja![n][w][e]
[s][f 5 14][f 5 15]Y, como ya no hay especuladores[n]pululando cerca, pueden volver a[n]echar pel胤culas.[n][w][e]

[msg MSG_001_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1175 65535 0]斡Estar胤a bien ir[n]a ver una peli all胤![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Invita a alguien para que te[n]acompa隠e a la pr吋xima.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Dummy scriptChat_236[e]

