[msg MSG_000_0_0 [Hifumi]]
[s][f 5 14]夷Me ayudas a preparar[n]un movimiento nuevo?[n][w][e]

[msg MSG_001_0_0 [Hifumi]]
[s][f 5 14]Tambi姻n ser茨 una experiencia[n]buena para ti.[n][w][e]

[msg MSG_002_0_0 [Hifumi]]
[s][f 5 14]Si tienes tiempo,[n]p茨sate por la iglesia.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Hifumi te est茨 esperando[n]en la iglesia. 夷Quieres ir?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Ahora mismo voy.[e]

[msg MSG_REACTION [Hifumi]]
[s][f 5 14]Vale, te estar姻 esperando.[n][f 5 15][w][e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Hifumi te est茨 esperando[n]en la iglesia. 夷Quieres ir?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Parece que Hifumi te est茨 esperando[n]en la iglesia. 夷Quieres ir?[n][f 1 3 65535][w][e]

