[msg MSG_000_0_0 [Haru]]
[s][f 5 14]夷Por qu姻 no le pedimos a Futaba[n]que investigue qui姻n es el culpable[n]de los episodios de descontrol?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]斡Qu姻 buena idea! 夷Por qu姻[n]no se me ha ocurrido a m胤?[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Al fin y al cabo, la habilidad de[n]Futaba para procesar informaci吋n[n]es la mejor del mundo.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]斡Qu姻 lista eres, Haru![n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]Ya lo he intentado.[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]夷Y?[e]
[s]夷Has encontrado algo?[e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]S姻 tanto que ahora es dif胤cil[n]separar lo importante de lo dem茨s.[n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]Aparece gente sospechosa y[n]de repente desaparece.[n]Es as胤 todo el rato.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Entonces, est茨n manipulando[n]informaci吋n para que nadie[n]llegue a la verdad...[n][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]Bueno, hay una cosa[n]que s胤 s姻 seguro.[n][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][f 5 14][f 5 15]La persona a la que nos enfrentamos[n]ahora es m茨s poderosa de lo[n]que podemos imaginar.[n][w][e]

