[msg MSG_000_0_0 [Maruki]]
[s][f 5 14]Oye, [f 4 1].[n][w][e]

[msg MSG_001_0_0 [Maruki]]
[s][f 5 14]夷Qu姻 piensas hacer[n]despu姻s de clase?[n][w][e]
[s][f 5 14]Si tienes tiempo,[n]yo siempre estoy encantado[n]de hablar sobre mi investigaci吋n.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Maruki[n]est茨 esperando en la enfermer胤a.[n]夷Quieres ir a verlo?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Ahora mismo voy.[e]

[msg MSG_REACTION [Maruki]]
[s][f 5 14]Gracias. Siempre me eres de ayuda.[n][w][e]
[s][f 5 14]Bueno, te espero en la enfermer胤a.[n][f 5 15][w][e]

[msg MSG_CORP_PLAY_CHECK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Maruki[n]est茨 esperando en la enfermer胤a.[n]夷Quieres ir a verlo?[n][f 1 3 65535][w][e]

[msg MSG_CORP_PLAY_CHECK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Parece que Maruki[n]est茨 esperando en la enfermer胤a.[n]夷Quieres ir a verlo?[n][f 1 3 65535][w][e]

