[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Me encantar胤a ir a dar un paseo[n]por la playa. Al fin y al cabo,[n]estamos en Haw茨i.[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]As胤 tambi姻n puedo[n]desconectar del trabajo...[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]Si no tienes ning雨n plan, 夷te[n]vienes a dar una vuelta conmigo?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Venga.[e]

[msg MSG_020_0_0 [Makoto]]
[s][f 5 14]斡夷En serio?! 斡Gracias![n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][f 5 14]夷Deber胤a ponerme ba隠ador...?[n]斡Bueno, hasta luego![n][f 5 15][w][e]

