[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]T胤o, 夷la periodista aquella a雨n no[n]se ha puesto en contacto contigo?[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Le enviamos un correo electr吋nico[n]el otro d胤a.[n]夷A qu姻 viene tanta prisa?[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]No s姻. He estado buscando[n]informaci吋n, pero no[n]he encontrado nada, joder...[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Solo nos quedan dos semanas, t胤o.[n]Claro que hay prisa.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Para ser m茨s exactos,[n]a雨n tenemos diez d胤as.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Aunque empecemos en cuanto[n]responda, no tendremos[n]mucho tiempo.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Entonces tendremos que despachar[n]r茨pido esta batalla.[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Tambi姻n hay que pensar[n]qu姻 haremos si no responde.[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Oye, 斡no seas gafe![n][w][e]

[msg MSG_009_0_0 [Yusuke]]
[s][f 5 14]Yo me limito a exponer[n]todos los escenarios posibles.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]夷No os pone nerviosos este tema?[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Los nervios no nos ayudar茨n[n]a resolver nada[n]llegados a este punto.[n][w][e]

[msg MSG_012_0_0 [Yusuke]]
[s][f 5 14]Si esa fuera la soluci吋n[n]a nuestro problema, ya estar胤a[n]subi姻ndome por las paredes.[n][w][e]

[msg MSG_013_0_0 [Ann]]
[s][f 5 14]Vaya, es como un fil吋sofo...[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Yo creo que es solo un idiota...[n][w][e]

