[msg MSG_004_0_0 [Al胤 Bab茨]]
[s][f 5 14]Es un placer conocerte.[n][w][e]

[msg MSG_004_3_0 [Al胤 Bab茨]]
[s][f 5 14]Soy a quien llaman Al胤 Bab茨.[n][w][e]

[msg MSG_004_5_0 [Al胤 Bab茨]]
[s][f 5 14]Quiero preguntarte algo.[n][w][e]

[msg MSG_004_7_0 [Al胤 Bab茨]]
[s][f 5 14]Eres un Ladr吋n Fantasma, 夷verdad?[n][w][e]

[msg MSG_004_9_0 [Al胤 Bab茨]]
[s][f 5 14]夷De verdad pod姻is[n]despertar corazones?[n][w][e]

[msg MSG_005_0_0 [Morgana]]
[s][bup 0 3 4 65535 0][f 4 10 65535 0 0][vp 8 0 0 6 65535 0]夷Qui姻n es? 夷Por qu姻 sabe[n]que eres un Ladr吋n Fantasma?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 7 65535 0]夷Es alguien de tu equipo[n]gast茨ndote una broma?[n][f 1 3 65535][w][e]

[msg MSG_006_0_0 [Al胤 Bab茨]]
[s][f 5 14]Hay alguien cuyo coraz吋n[n]me gustar胤a que despertarais.[n][w][e]

[msg MSG_006_1_0 [Al胤 Bab茨]]
[s][f 5 14]Pero no pido caridad.[n]Hagamos un trato.[n][w][e]

[msg MSG_006_2_0 [Al胤 Bab茨]]
[s][f 5 14]Quieres informaci吋n[n]de Medjed, 夷correcto?[n][w][e]

[msg MSG_006_3_0 [Al胤 Bab茨]]
[s][f 5 14]Puedo darte informaci吋n sobre ellos[n]si el despertar sale bien.[n][w][e]

[msg MSG_006_4_0 [Al胤 Bab茨]]
[s][f 5 14]Si lo deseas, tambi姻n puedo[n]ocuparme de ellos.[n][w][e]

[msg MSG_006_5_0 [Al胤 Bab茨]]
[s][f 5 14]夷Crees en mis habilidades?[n][w][e]

[msg MSG_006_6_0 [Al胤 Bab茨]]
[s][f 5 14]Puedo rastrear sus cuentas,[n]como hice con la tuya.[n][w][e]

[msg MSG_006_7_0 [Al胤 Bab茨]]
[s][f 5 14]Pero esto es todo lo que puedo[n]demostrar por ahora.[n][w][e]

[msg MSG_006_8_0 [Al胤 Bab茨]]
[s][f 5 14]He preparado la herramienta[n]necesaria por mi parte.[n][w][e]

[msg MSG_006_9_0 [Al胤 Bab茨]]
[s][f 5 14][f 5 15]Espero impaciente.[n][w][e]

[msg MSG_007_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 8 0 0 8 65535 0]夷No deber胤as responder?[n][f 1 3 65535][w][e]

[msg MND_008_0_0]
[s]夷C吋mo deber胤a responder?[n][w][e]

[sel SEL_009_0_0 top]
[s][f 5 14][f 5 15]夷Qui姻n eres?[e]
[s]Te equivocas de persona.[e]
[s]夷Es una broma?[e]

