[msg MSG_OKUMURA_MAEOKI [Mishima]]
[s][f 5 14]Oye, perdona que hable de esto[n]en medio de tanto l胤o...[n][w][e]
[s][f 5 14]S姻 que no ha sido f茨cil despu姻s de[n]lo que le ha pasado al presidente[n]Okumura y tal...[n][w][e]
[s][f 5 14]Pero despertar el coraz吋n a[n]otra gente os ayudar胤a[n]con vuestra reputaci吋n.[n][w][e]
[s][f 5 14]Bueno, aqu胤 tienes informaci吋n...[n][w][e]

[msg MSG_SIMEITEHAI_MAEOKI [Mishima]]
[s][f 5 14]Oye, perdona que saque esto[n]ahora que est茨s ocupado, pero...[n][w][e]
[s][f 5 14][f 4 28] puede hacerlo.[n]Conf胤o en vosotros.[n][w][e]
[s][f 5 14]Bueno, aqu胤 tienes informaci吋n...[n][w][e]

[msg MSG_030_0_0 [Mishima]]
[s][f 5 14]Este es un poco dif胤cil.[n][w][e]

[msg MSG_CHAT_quest02_clear_0 [Mishima]]
[s][f 5 14]Han estado ocurriendo cosas[n]raras en el callej吋n trasero[n]de la calle principal de Shibuya.[n][w][e]

[msg MSG_CHAT_quest02_clear_0_2 [Mishima]]
[s][f 5 14]Parece que han encontrado[n]gatos muertos o heridos[n]con bastante frecuencia.[n][w][e]
[s][f 5 14]Pasa tan a menudo que la[n]gente empieza a pensar[n]que es culpa de alguien.[n][w][e]

[sel SEL_031_0_0 top]
[s][f 5 14]Es imperdonable.[e]
[s]Qu姻 mal rollo.[e]
[s]Yo no he sido.[e]

[msg MSG_032_0_0 [Mishima]]
[s][f 5 14]S胤, solo la escoria atacar胤a[n]a los animales inocentes[n]e indefensos.[n][w][e]

[msg MSG_033_0_0 [Mishima]]
[s][f 5 14]Qu姻 ascazo.[n][w][e]

[msg MSG_034_0_0 [Mishima]]
[s][f 5 14]斡No dudo de ti![n]斡No soy tan mala persona![n][w][e]

[msg MSG_035_0_0 [Mishima]]
[s][f 5 14]En fin, esta es la informaci吋n[n]que he podido sacar[n]del foro.[n][w][e]
[s][f 5 14]Si te preocupa,[n]deber胤as ir a investigar[n]por tu cuenta.[n][w][e]
[s][f 5 14][f 5 15]A lo mejor alguien que[n]trabaje en la calle principal[n]puede darte m茨s detalles.[n][w][e]

[msg MSG_036_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1176 65535 0]斡Es del todo imperdonable![n][f 1 3 65535][w][e]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]A ver, no es porque yo[n]sea un gato ni nada.[n]斡Es muy cruel y punto![n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Mmm, si trabajas en la calle[n]principal, a lo mejor obtienes[n]informaci吋n de tus compa隠eros...[n][f 1 3 65535][w][e]

[msg MSG_001_0_1 [Igor]]
[s][bup 0 201 0 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]*risita* Un paso m茨s en tu[n]rehabilitaci吋n... Espero grandes[n]cosas de ti.[n][f 1 3 65535][w][e]

[msg MND_quest02_CLEAR_SELF]
[s][vp 8 2 65535 0 0 0]Parece que hay disponible un[n]nuevo objetivo. Tendr胤a que ir[n]a ver c吋mo se llama...[n][f 1 3 65535][w][e]
[s][vp 8 2 65535 0 0 0]Podr胤a obtener informaci吋n de mis[n]compa隠eros si trabajo a[n]tiempo parcial en la calle principal.[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Dummy scriptChat_220[e]

