[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]T胤o, necesitamos pasta.[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Ya, pero 夷a qu姻 viene eso ahora?[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Bueno, ahora hay que pillar armas,[n]medicinas y esas mierdas.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Pero no podemos comprar[n]nada sin pasta.[n][w][e]

[sel SEL_004_0_0 top]
[s][f 5 14]夷Tienes algo ahorrado?[e]
[s]Pues a conseguir dinero.[e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]斡Qu姻 va![n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Como si fuera tan f茨cil.[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]夷Y si nos buscamos un trabajo[n]a tiempo parcial?[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]No s姻... 夷Tenemos que hacerlo?[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]斡Mierda![n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Ushimaru est茨 mirando hacia aqu胤.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Lo siento, dejo el chat[n]un momento. 斡Adi吋s![n][w][e]

