[msg MSG_000_0_0 [Al胤 Bab茨]]
[s][f 5 14]夷A雨n no hab姻is acabado?[n][w][e]

[msg MSG_001_0_0 [Al胤 Bab茨]]
[s][f 5 14]Ya os dije que[n]no soy una persona paciente.[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]No me digas...[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Nos dijiste que esperar胤as.[n]No faltes a tu palabra.[n][w][e]

[msg MSG_004_0_0 [Al胤 Bab茨]]
[s][f 5 14]Eso no importa. 夷Pens茨is que no[n]os entregar姻 a la polic胤a?[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]No, te creo.[e]
[s]No te atrever胤as.[e]
[s]Hazlo.[e]

[msg MSG_006_0_0 [Al胤 Bab茨]]
[s][f 5 14]Ser茨 mejor que me tom姻is en serio.[n]Tengo muchas pruebas[n]contra vosotros, chicos.[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]夷C吋mo? 夷Que tienes pruebas?[n][w][e]

[msg MSG_008_0_0 [Al胤 Bab茨]]
[s][f 5 14]No me subestim姻is.[n][w][e]

[msg MSG_009_0_0 [Al胤 Bab茨]]
[s][f 5 14]Filtrar el historial de vuestro[n]chat a la polic胤a ser胤a pan comido.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Eh, no lo hagas.[n][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][f 5 14]No nos malinterpretes.[n][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14]De verdad queremos que nos ayudes.[n][w][e]

[msg MSG_013_0_0 [Makoto]]
[s][f 5 14]Por eso haremos lo que haga[n]falta para cumplir nuestra promesa.[n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14]Que no te quepa ninguna duda.[n][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][f 5 14][f 5 15]Solo necesitamos[n]un poco m茨s de tiempo...[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 1 0 0 24 0 0]Parece que no entiende[n]nuestras circunstancias...[n]Podr胤a suponer un problema...[n][f 1 3 65535][w][e]

