[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]斡Hemos asegurado[n]un camino hacia el tesoro![n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]夷Vamos a enviar el aviso?[n]夷Quedamos?[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Entonces, 夷qu姻? Si quieres[n]enviar el aviso,[n]reun茨monos en el escondite.[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Reunirse[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Vamos a enviar el aviso.[e]

[msg MSG_REACTION [Futaba]]
[s][f 5 14]O胤do cocina.[n][w][e]

[msg MSG_REACTION_02 [Futaba]]
[s][f 5 14]Estar姻 esperando en el escondite.[n][f 5 15][w][e]

