[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]La fecha l胤mite es ma隠ana...[n]Nos va bien, 夷no?[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Adi吋s a las fotos. Ya no tiene[n]nada con lo que amenazarnos.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Vamos, si es que podemos confiar[n]en lo que dijo Kaneshiro.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]No digas esas cosas, que dan miedo.[n][w][e]

[msg MSG_004_0_0 [Makoto]]
[s][f 5 14]A雨n no podemos relajarnos.[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]La polic胤a podr胤a[n]dejarlo en libertad...[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]斡夷En serio?![n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Vamos, salvo que tengan pruebas[n]concluyentes como una confesi吋n.[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Todo ir茨 bien.[e]
[s]Estoy preocupado.[e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Cierto, parece haber[n]algo de movimiento.[n][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]Pero al menos parece haber[n]algo de movimiento.[n][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][f 5 14]Mi hermana me ha escrito para[n]decirme que esta noche no viene.[n][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14]Puede que la polic胤a[n]haya hecho alg雨n avance.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Entonces, 斡夷ha sucedido?![n][w][e]

[msg MSG_014_0_0 [Ann]]
[s][f 5 14]Es el momento perfecto.[n]Confiemos en que salga bien.[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14][f 5 15]斡Ver姻 las noticias[n]toda la noche para ver[n]si me entero de algo![n][w][e]

