[msg MSG_030_0_0 [Mishima]]
[s][f 5 14]夷Oyes esos gritos de j雨bilo?[n][w][e]

[msg MSG_CHAT_quest09_clear_0 [Mishima]]
[s][f 5 14]Me refiero a la repentina oleada[n]de publicaciones que hemos tenido[n]en la Fansite.[n][w][e]
[s][f 5 14]Debe ser por lo populares[n]que se han vuelto[n]los Ladrones Fantasma.[n][w][e]

[sel SEL_031_0_0 top]
[s][f 5 14]Bien por ellos.[e]
[s]Qu姻 fastidio.[e]
[s]Es todo gracias a ti.[e]

[msg MSG_032_0_0 [Mishima]]
[s][vp 1 0 0 0 0 0][f 5 14]夷Verdad? Espera, 夷por qu姻 haces[n]como si no estuvieras implicado?[n][w][e]

[msg MSG_033_0_0 [Mishima]]
[s][vp 1 0 0 0 0 0][f 5 14]Yo igual. Me va a tocar[n]empalmar otra noche por[n]culpa de esto...[n][w][e]

[msg MSG_034_0_0 [Mishima]]
[s][vp 1 0 0 0 0 0][f 5 14]夷Yo? Tampoco me molestar胤a[n]o胤rlo un poco m茨s a menudo.[n][w][e]

[msg MSG_035_0_0 [Mishima]]
[s][vp 1 0 0 0 0 0][f 5 14]Bueno, deja que te cuente[n]lo m茨s interesante que[n]he averiguado hasta ahora.[n][w][e]
[s][f 5 14]Actos indiscriminados de violencia[n]en Shibuya.[n][w][e]
[s][f 5 14]Da miedito, 夷no? Pero no[n]encuentro mucho m茨s...[n][w][e]
[s][f 5 14]Las publicaciones hablan de rumores[n]en el centro comercial subterr茨neo[n]de Shibuya, pero nada m茨s.[n][w][e]
[s][f 5 14]Es poco fiable...[n][w][e]
[s][f 5 14]Estar胤a bien saber m茨s[n]sobre esos rumores, pero[n]mi presencia se limita a la web.[n][w][e]
[s][f 5 14][f 5 15]Podr胤as intentar investigar m茨s[n]por tu cuenta si te interesa.[n][w][e]

[msg MSG_036_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]Mmm... Parece que no nos queda otra[n]que buscar informaci吋n[n]por nuestra cuenta.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]Puedes [clr 2]infiltrarte como empleado[n]del centro comercial subterr茨neo[clr 27][n]si quieres m茨s informaci吋n.[n][f 1 3 65535][w][e]

[msg MND_quest09_CLEAR_SELF]
[s]Parece que hemos despertado[n]el coraz吋n del objetivo.[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Dummy scriptChat_252[e]

