[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Parece que los rumores sobre[n]nuestra expulsi吋n se[n]propagan con rapidez.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Eso parece.[e]
[s]夷En serio?[e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Supongo que tuvimos[n]un buen foll吋n con 姻l...[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]夷No has o胤do a nadie[n]hablar del tema?[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Qu姻 m茨s da.[n]Le daremos la vuelta a la tortilla.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Todo el mundo se sorprender胤a si[n]logr茨semos despertar el[n]coraz吋n de Kamoshida.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Dudo que creyesen[n]que es cosa nuestra.[n][w][e]

[sel SEL_007_0_0 top]
[s][f 5 14]Es as胤 y punto.[e]
[s]Est茨 bien.[e]
[s]夷Se lo decimos?[e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Pero ser胤a una putada no obtener[n]ning雨n reconocimiento...[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]T胤o, yo flipo[n]con lo maduro que eres.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Aunque lo hici姻ramos,[n]nadie nos creer胤a.[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]Da lo mismo, no podemos[n]preocuparnos por[n]lo que dicen de nosotros.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Ya lo s姻.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14][f 5 15]斡A este paso, nos expulsar茨n![n]斡Hay que acabar con esta[n]mierda cueste lo que cueste![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]La se隠orita Ann tiene raz吋n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0]No nos distraigamos[n]y centr姻monos en despertar[n]el coraz吋n de Kamoshida.[n][f 1 3 65535][w][e]

