[msg MSG_000_0_0 [Kawakami]]
[s][f 5 14]Voy al instituto a dar una clase.[n][w][e]

[msg MSG_001_0_0 [Kawakami]]
[s][f 5 14]夷Quieres dar un paseo[n]por el instituto[n]y recordar viejos tiempos?[n][w][e]

[msg MSG_002_0_0 [Kawakami]]
[s][f 5 14]Como te vas ma隠ana...[n][w][e]

[msg MSG_003_0_0 [Kawakami]]
[s][f 5 14]Te estar姻 esperando[n]en la entrada del instituto.[n][f 5 15][w][e]

[msg MSG_LAST_GREETING_DOOR_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Todav胤a no has hablado con ninguno[n]de los dos. 夷Aun as胤 quieres[n]ir a ver a Kawakami?[n][f 1 3 65535][w][e]

[msg MSG_LAST_GREETING_DOOR_0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Todav胤a no has hablado con Futaba.[n]夷Aun as胤 quieres[n]ir a ver a Kawakami?[n][f 1 3 65535][w][e]

[msg MSG_LAST_GREETING_DOOR_0_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Todav胤a no has hablado con el Jefe.[n]夷Aun as胤 quieres[n]ir a ver a Kawakami?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]夷Quieres ir a ver a Kawakami?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

