[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Oye, quedemos ma隠ana otra vez.[n][w][e]

[msg MSG_000_5_0 [Ann]]
[s][f 5 14]Podemos celebrar que has salido.[n]Solo t雨 y yo.[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Tengo una cosa que darte.[n]夷Nos vemos en tu casa?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Te estar姻 esperando.[e]

[msg MSG_020_0_0 [Ann]]
[s][f 5 14]斡Bien! Me pasar姻[n]ma隠ana por la noche.[n][w][e]

[msg MSG_021_0_0 [Ann]]
[s][f 5 14]斡Buenas nocheeees![n][f 5 15][w][e]

