[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Los Ladrones Fantasma, eh...[n]斡Suena que te cagas![n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Espero que ayudemos a la gente.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Tengo curiosidad por la Web[n]del Aficionado de los Fantasmas.[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]A saber qui姻n la har胤a...[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Ni idea.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Y lo m茨s importante,[n]夷hab姻is visto el sondeo ese?[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]No s姻 muy bien qu姻 pensar.[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]S胤, estaba eso del 胤ndice de[n]aprobaci吋n, pero solo estaba[n]al seis por ciento.[n][w][e]

[sel SEL_012_0_0 top]
[s][f 5 14]Est茨 muy bajo.[e]
[s]Es mejor de lo que esperaba.[e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]S胤.[n][w][e]

[msg MSG_014_0_0 [Ann]]
[s][f 5 14]Pues no parece[n]que est姻 tan mal.[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Pero 夷no quieres mejorar[n]el porcentaje?[n][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 5 14]Si acabamos con objetivos gordos,[n]seguro que sube como la espuma.[n][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][f 5 14]Y visto as胤, me parece[n]la mar de emocionante.[n][w][e]

[msg MSG_018_0_0 [Ann]]
[s][f 5 14]夷Sabes qu姻? Que tienes raz吋n.[n][w][e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14][f 5 15]斡Pues a darlo todo de[n]ahora en adelante![n][w][e]

