[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Muchas gracias a todos[n]por el d胤a de hoy.[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Igualmente.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Estar茨s agotada.[n]Deber胤as irte a dormir pronto.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]斡Eh, hay que hablar de la[n]fiesta de bienvenida de Haru![n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Hab胤amos dicho que 胤bamos[n]a dejarla descansar, imb姻cil.[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]Os agradezco que os preocup姻is,[n]pero estoy bien, de verdad.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Si t雨 est茨s bien...[n]Bueno, 夷quieres ir a alg雨n sitio?[n][w][e]

[msg MSG_007_0_0 [Haru]]
[s][f 5 14]Pues la verdad es que me[n]gustar胤a ir al festival del[n]insti con todo el mundo.[n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]夷Al del Shujin?[n]Reconozco que a m胤[n]tambi姻n me interesa.[n][w][e]

[sel SEL_009_0_0 top]
[s][f 5 14]Adjudicado.[e]
[s]Me muero de ganas.[e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]Eso me recuerda que a雨n no[n]tenemos ning雨n invitado.[n][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][f 5 14]斡夷Como que ning雨n invitado?![n][w][e]

[msg MSG_012_0_0 [Futaba]]
[s][f 5 14]斡夷Un famoso, dices?![n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Espera, 斡夷significa eso[n]que los Ladrones Fantasma[n]podr胤an ser candidatos?![n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14]夷Y bien? 夷Te apetece ir?[n][w][e]

[msg MSG_015_0_0 [Haru]]
[s][f 5 14]Igual es pasarse...[n][w][e]

[msg MSG_016_0_0 [Ann]]
[s][f 5 14]Se te est茨 yendo mucho la olla.[n][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][f 5 14]No digas esas cosas tan raras.[n][w][e]

[msg MSG_018_0_0 [Yusuke]]
[s][f 5 14]Qu姻 idea tan superficial.[n][w][e]

[msg MSG_019_0_0 [Futaba]]
[s][f 5 14]斡Hala, un combo de cuatro golpes![n][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Lo siento...[n][w][e]

