[msg MSG_056_0_0 [Yusuke]]
[s][f 5 14]Lamento molestaros mientras[n]esper茨is informaci吋n[n]de esa periodista.[n][w][e]
[s][f 5 14]Pero 夷record茨is esa publicaci吋n[n]sobre los ladrones en Shibuya?[n][w][e]
[s][f 5 14]Parece que el que habl吋 sobre[n]su hermano estudia en mi instituto.[n][w][e]
[s][f 5 14]Y despu姻s de insistir,[n]logr姻 sacarle m茨s informaci吋n[n]sobre el hermano.[n][w][e]

[msg MSG_057_0_0 [Ann]]
[s][f 5 14]斡Ah, cierto! La verdad[n]es que me estaba preguntando eso.[n][w][e]
[s][f 5 14]No parec胤a que tuviera nada[n]que ver con la mafia[n]a la que hemos estado persiguiendo.[n][w][e]

[msg MSG_064_0_0 [Yusuke]]
[s][f 5 14]Pues s胤. Adem茨s, he logrado[n]averiguar el nombre de su hermano...[n][w][e]
[s][f 5 14]Se llama Kazuya Makigami.[n][w][e]

[msg MSG_058_0_0 [Ryuji]]
[s][f 5 14]T胤o, es una puta locura que alguien[n]involucrado en esa mierda[n]vaya a tu instituto.[n][w][e]
[s][f 5 14]斡Buen trabajo, Yusuke![n][w][e]

[msg MSG_060_0_0 [Ann]]
[s][f 5 14]斡Hasta has averiguado el nombre[n]del tipo al que est茨bamos buscando![n][w][e]
[s][f 5 14]斡Ha sido de alucine![n][w][e]

[msg MSG_063_0_0 [Ryuji]]
[s][f 5 14]Ahora lo 雨nico que tenemos[n]que hacer es castigarlo[n]en Mementos.[n][w][e]
[s][f 5 14]Este ladronzuelo no dar茨[n]ni la mitad de miedo que la mafia.[n]Es un t胤o cualquiera, 夷no?[n][w][e]
[s][f 5 14]斡Vamos a mostrarle lo que significa[n]ser un Ladr吋n Fantasma![n][w][e]

[msg MSG_065_0_0 [Yusuke]]
[s][f 5 14]Parece que la decisi吋n es un茨nime.[n][w][e]
[s][f 5 14][f 5 15]Podemos concretar los detalles[n]en el escondite.[n][w][e]

[msg MSG_quest11_MORGANA_SAY [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1020 65535 0]斡Tenemos a nuestro objetivo! Y hay[n]que ocuparse de la mafia. Aseg雨rate[n]de elegir el mejor momento.[n][f 1 3 65535][w][e]
[s][vp 8 2 65535 0 0 0][f 4 10 65535 0 0]Bueno, reun茨monos en el escondite[n]cuando est姻s listo.[n][f 1 3 65535][w][e]

[msg MND_quest11_OPEN_SELF]
[s]He conseguido informaci吋n de un[n]objetivo. Deber胤a ir al escondite[n]a ver qu姻 opinan los dem茨s...[n][w][e]

