[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Por fin lo hemos conseguido.[n]Lo 雨nico que nos queda[n]es enviar el aviso.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Parece que conseguiremos enviarlo[n]antes de que la investigaci吋n[n]se vaya al traste.[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Pero a雨n no sabemos nada[n]del responsable de las[n]desconexiones mentales...[n][w][e]

[msg MSG_003_0_0 [Ann]]
[s][f 5 14]Me pregunto si conseguiremos[n]sonsacarle algo[n]a la sombra de Niijima.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Dudo mucho que haya confirmado[n]alguna prueba relevante.[n][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][f 5 14]Estoy de acuerdo.[n]Por eso tiene la orden[n]contra los Ladrones Fantasma.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Adem茨s, la gente cree que arrestarnos[n]resolver茨 el caso.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Los fiscales no se detendr茨n ahora.[n]Tienen la mirada de la opini吋n[n]p雨blica puesta en ellos.[n][w][e]

[msg MSG_008_0_0 [Haru]]
[s][f 5 14]Si supi姻ramos qui姻n es el culpable,[n]no tendr胤amos que enfrentarnos[n]a la sombra de Niijima.[n][w][e]

[msg MSG_009_0_0 [Haru]]
[s][f 5 14]夷Qui姻n ser茨...? 夷Cre姻is que puede[n]ser alguien que conozcamos?[n][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Es una posibilidad.[e]
[s]Lo dudo mucho.[e]
[s]No tengo ni idea.[e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Cierto, pero si empezamos a dudar[n]de nuestros compa隠eros, nunca nos[n]libraremos de esa desconfianza.[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]Yo tampoco quiero pensar mal,[n]pero quiz茨 est姻s siendo[n]demasiado optimista...[n][w][e]

[msg MSG_013_0_0 [Futaba]]
[s][f 5 14]Se trata de alguien que siente[n]rencor hacia nosotros y que siempre[n]se adelanta a nuestros actos...[n][w][e]

[msg MSG_014_0_0 [Futaba]]
[s][f 5 14]Mmm, es verdad.[n]No se me ocurre nadie[n]que encaje con esa descripci吋n.[n][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][f 5 14]Sea como sea, solo tenemos[n]una oportunidad para darle[n]la vuelta a la tortilla.[n][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][f 5 14]Este 雨ltimo aviso[n]ser茨 mi obra maestra.[n][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Av胤sanos cuando est姻s preparado,[n][f 4 2].[n][w][e]

