[msg MSG_000_0_0 [Al胤 Bab茨]]
[s][f 5 14]夷Qu姻 hac姻is?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]斡Es ella otra vez![n][w][e]

[msg MSG_002_0_0 [Al胤 Bab茨]]
[s][f 5 14]夷Vais a hacerme esperar mucho m茨s?[n][w][e]

[msg MSG_003_0_0 [Al胤 Bab茨]]
[s][f 5 14]夷No os importa que[n]os entregue a la polic胤a?[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]斡Oye, echa el freno![n]Solo necesitamos un poco[n]m茨s de tiempo.[n][w][e]

[msg MSG_005_0_0 [Al胤 Bab茨]]
[s][f 5 14]Imposible.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Estamos haciendo[n]todo lo que podemos.[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Si de verdad no puedes esperar[n]m茨s, adelante, ve a la polic胤a.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]斡Eh![n][w][e]

[msg MSG_009_0_0 [Al胤 Bab茨]]
[s][f 5 14]Mmm. Quiz茨 pueda daros[n]algo m茨s de tiempo.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14][f 5 15]斡夷Quiz茨?![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 22 0 0]Al胤 Bab茨 no sabe lo que pasa,[n]as胤 que seguro que[n]se est茨 poniendo nerviosa...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 23 0 0]De momento, tendremos[n]que seguirle la corriente...[n][f 1 3 65535][w][e]

