[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Entonces, cuanto m茨s famosos somos,[n]m茨s Mementos se abren, 夷no?[n][w][e]

[msg MSG_000_0_00 [Ryuji]]
[s][f 5 14]No me lo saco del coco...[n][w][e]

[msg MSG_000_0_1 [Futaba]]
[s][f 5 14]Y por eso no pod胤as centrarte[n]en tus deberes hasta hoy, 夷no?[n][w][e]

[msg MSG_000_0_2 [Ryuji]]
[s][f 5 14]斡S胤, eso es![n][w][e]

[msg MSG_000_0_3 [Makoto]]
[s][f 5 14]Me huele a excusa desde aqu胤.[n][w][e]

[msg MSG_000_0_4 [Ann]]
[s][f 5 14]Yo tambi姻n he estado[n]pregunt茨ndome eso.[n]夷Por qu姻 funcionar茨 as胤?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14][f 5 15]夷Morgana sabe algo?[n][w][e]

[msg MSG_CHAT_MORU_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]No lo s姻... Ni siquiera[n]recuerdo cu茨ndo descubr胤[n]lo que es Mementos...[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Parece que no lo sabe.[e]
[s]No lo recuerda.[e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]Entiendo... Entonces no hay[n]forma de que podamos averiguarlo.[n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]Probablemente se aclare si seguimos[n]como los Ladrones Fantasma.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Ahora lo m茨s importante es[n]averiguar la identidad del criminal[n]que est茨 utilizando el Metaverso.[n][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]斡Quiz茨 sea la persona[n]que mat吋 a mi madre![n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]La encontrar姻 sin importar[n]lo que cueste.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Antes coje茨bamos en ciertos temas...[n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Pero ahora que tenemos a Futaba[n]para ayudarnos, se nos presentan[n]muchas m茨s posibilidades.[n][w][e]

[msg MSG_010_0_0 [Yusuke]]
[s][f 5 14]S胤, casi sin querer,[n]hemos conseguido una magn胤fica[n]adici吋n al equipo.[n][w][e]

[msg MSG_011_0_0 [Futaba]]
[s][f 5 14]Ohhh, 斡me estoy poniendo colorada![n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]斡Contamos contigo, Futaba![n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14][f 5 15]斡Esto es mucho mejor que[n]tener a un gato tonto como l胤der![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][vp 1 0 0 2 0 0]......[n][f 1 3 65535][w][e]

