[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Los que no est茨n del lado de Shido[n]no son patriotas.[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]斡夷Pero qu姻 dices?![n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]Son comentarios que se escuchan[n]en toda la ciudad.[n][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][f 5 14]En internet tambi姻n.[n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]Todo el mundo dice lo mismo.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]斡Eso no tiene ning雨n sentido![n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]El entusiasmo de la gente se ha[n]transformado en una fe ciega.[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Puede que al final nos beneficie[n]que no se sepa mucho sobre[n]tu informe de suicidio.[n][w][e]

[sel SEL_008_0_0 top]
[s][f 5 14]Probablemente.[e]
[s]夷Por qu姻 dices eso?[e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Cuanto m茨s llamativa es[n]una noticia, m茨s probable es que[n]la gente busque informaci吋n nueva.[n][w][e]

[msg MSG_010_0_0 [Haru]]
[s][f 5 14]Qui姻n sabe lo que le hubieran[n]hecho a [f 4 2] si[n]supieran que sigue vivo...[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]En este momento, el m茨s[n]m胤nimo est胤mulo puede[n]ser un gran problema.[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]El pa胤s es como un globo gigante[n]con demasiado aire dentro.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Qu姻 puta locura...[n][w][e]

[msg MSG_014_0_0 [Futaba]]
[s][f 5 14]斡La gente ha perdido la cabeza![n][w][e]

[msg MSG_015_0_0 [Makoto]]
[s][f 5 14][f 5 15]Ahora mismo, casi parece[n]como si adoraran a Shido.[n]Da un poco de miedo...[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Makoto tiene raz吋n.[n]Tengo un mal presentimiento...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0][f 4 2], t雨 eres[n]quien corre m茨s peligro.[n]Ten cuidado.[n][f 1 3 65535][w][e]

