[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Ese cabr吋n de Akechi...[n]Pensar en lo que ha dicho hace[n]que me suba por las paredes.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Est茨 claro que ha intentado echar[n]por tierra todo nuestro trabajo.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]斡Y encima lo ha soltado[n]en directo![n][w][e]

[msg MSG_004_0_0 [Yusuke]]
[s][f 5 14]No te lo tomes tan a pecho.[n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Hemos salvado a gente y[n]eso no nos lo quita nadie.[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]Y no habr胤a sucedido de no[n]ser por las haza隠as de los[n]Ladrones Fantasma.[n][w][e]

[msg MSG_007_0_0 [Yusuke]]
[s][f 5 14]Yo mismo soy prueba de ello.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]斡Ay, pero qu姻 bonito![n][w][e]

[msg MSG_009_0_0 [Ann]]
[s][f 5 14]Pero 夷se ha equivocado Akechi[n]con lo que ha dicho?[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Creo que ten胤a algo de raz吋n.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]夷A qu姻 viene esto ahora?[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]夷Tenemos derecho a[n]hacerle esto a la gente[n]solo por ser criminales?[n][w][e]

[msg MSG_013_0_0 [Ann]]
[s][f 5 14]夷No os parece ego胤sta?[n][w][e]

[msg MSG_014_0_0 [Yusuke]]
[s][f 5 14]Somos los Ladrones Fantasma, Ann.[n][w][e]

[msg MSG_015_0_0 [Yusuke]]
[s][f 5 14]Supongo que hay gente que no[n]perdonar茨 lo que le hicimos a[n]Madarame.[n][w][e]

[msg MSG_016_0_0 [Yusuke]]
[s][f 5 14]Aun as胤, tengo claro que fue[n]absolutamente necesario.[n][w][e]

[msg MSG_017_0_0 [Ryuji]]
[s][f 5 14]Y lo mismo con Kamoshida. No[n]habr胤amos podido hacer nada[n]con m姻todos convencionales.[n][w][e]

[msg MSG_018_0_0 [Ann]]
[s][f 5 14]Es cierto, pero...[n][w][e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14]夷Qu姻 opinas, [f 4 2]?[n]夷Estamos siendo ego胤stas?[n][w][e]

[sel SEL_020_0_0 top]
[s][f 5 14]No lo niego.[e]
[s]Estamos ayudando.[e]
[s]Akechi me saca de mis casillas.[e]

[msg MSG_021_0_0 [Ann]]
[s][f 5 14]Qu姻 dif胤cil...[n][w][e]

[msg MSG_022_0_0 [Ann]]
[s][f 5 14]Pues tampoco[n]se me ocurre otra forma...[n][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][f 5 14]斡Estoy totalmente de acuerdo![n][w][e]

[msg MSG_024_0_0 [Ann]]
[s][f 5 14]斡Que lo digo en serio![n][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][f 5 14]Es posible que no nos quede otra[n]que ce隠irnos a nuestro concepto[n]de justicia, no a la ley.[n][w][e]

[msg MSG_026_0_0 [Yusuke]]
[s][f 5 14]夷No es m茨s que suficiente?[n][w][e]

[msg MSG_027_0_0 [Yusuke]]
[s][f 5 14]Y habiendo tomado la decisi吋n[n]de forma un茨nime, dudo que[n]perdamos el norte.[n][w][e]

[msg MSG_028_0_0 [Ann]]
[s][f 5 14]Ya, tienes raz吋n.[n][w][e]

[msg MSG_029_0_0 [Ann]]
[s][f 5 14]Perd吋n por sacar el tema.[n][w][e]

[msg MSG_030_0_0 [Ann]]
[s][f 5 14]Y no os preocup姻is, que no voy a[n]abandonar a los Ladrones Fantasma[n]ni nada parecido.[n][w][e]

[msg MSG_031_0_0 [Ryuji]]
[s][f 5 14]Te vas a enterar, Akechi.[n][w][e]

[msg MSG_032_0_0 [Ryuji]]
[s][f 5 14]斡Llegar茨 el d胤a en el que sepas[n]qui姻n llevaba raz吋n![n][w][e]

[msg MSG_033_0_0 [Ann]]
[s][f 5 14][f 5 15]Muy bien, dejemos[n]el tema por ahora.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Parece que el detective[n]Akechi tiene mucha influencia[n]en los medios.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Acercarse a 姻l podr胤a ser[n]peligroso, pero tambi姻n 雨til[n]en algunas situaciones.[n][f 1 3 65535][w][e]

