[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]Eh, 夷est茨s vivo? Dicen que[n]el cabecilla cometi吋...[n]No es cierto, 夷verdad?[n][w][e]

[msg MSG_000_1_0 [Mishima]]
[s][f 5 14]T雨 no te morir胤as[n]tan f茨cilmente, 夷verdad?[n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]夷Tienes tiempo hoy?[n]Quiero hacer otro informe,[n]pero 夷qu姻 opinas?[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Te agradecer胤a que habl茨semos[n]si no tienes otros planes.[n]Estar姻 en Akihabara.[n][w][e]

[msg CHAT_NOREACTION_MSG [Mishima]]
[s][f 5 14]夷Es mal momento?[n]Ya te invitar姻 en otra ocasi吋n.[n][w][e]

[msg CHAT_REACTION_MSG [Mishima]]
[s][f 5 14]Ah, estupendo, no has muerto.[n]Entonces ven. Hasta pronto.[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Bueno, 夷vas a aceptar[n]la invitaci吋n de Mishima?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir de inmediato[e]
[s]Comprobar v胤nculo con Mishima[e]
[s]Responder luego[e]

[sel SEL_002 top]
[s][f 5 14]Voy ahora mismo.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]Deber胤a poder mejorar[n]nuestro v胤nculo ya que tengo[n]a [clr 1][var 5][clr 27] del arcano [var 2]...[n][w][e]

