[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]Ha llegado una solicitud pavorosa.[n][w][e]
[s][f 5 14]Pone: 或Matadme位.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Parece serio.[e]
[s]No mataremos a nadie.[e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]El hombre est茨 de pena[n]y los detalles me ponen[n]la piel de gallina.[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]斡Ya lo s姻! Pero no podemos[n]dejarlo pasar, 夷verdad?[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]Se llama Nao Minamoto.[n][w][e]
[s][f 5 14]Se qued吋 hu姻rfano muy joven[n]y ha cuidado de su hermana[n]peque隠a desde entonces.[n][w][e]
[s][f 5 14]Se ha dejado la piel trabajando[n]para salir adelante, pero...[n][w][e]
[s][f 5 14]Odia tanto a su hermana[n]que no lo soporta.[n][w][e]
[s][f 5 14]Es su 雨nica familia, pero no puede[n]controlar sus sentimientos.[n][w][e]
[s][f 5 14]Un d胤a, estaba tan enfadado[n]que le empuj吋, se cay吋 y...[n][w][e]
[s][f 5 14]En fin, que se hizo mucho da隠o.[n][w][e]
[s][f 5 14]Fue un golpe de mala suerte,[n]pero 姻l es incapaz de aceptarlo.[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]夷Es una forma de expiaci吋n?[e]
[s]夷C吋mo est茨 su hermana?[e]

[msg MSG_006_0_0 [Mishima]]
[s][f 5 14]As胤 es. Quiere que lo paremos antes[n]de que mate a su hermana.[n][w][e]

[msg MSG_007_0_0 [Mishima]]
[s][f 5 14]Parece que bien.[n][w][e]
[s][f 5 14]Pero 姻l dice que no puede asegurar[n]que la cosa no vaya a ir a peor.[n]Prefiere que lo maten.[n][w][e]

[msg MSG_008_0_0 [Mishima]]
[s][f 5 14]Despertar su coraz吋n[n]servir茨 de algo, 夷no?[n][w][e]
[s][f 5 14][f 5 15]斡Hay que acabar[n]con sus sentimientos negativos![n][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]或Matadme位...[n]Qu姻 solicitud m茨s macabra.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1099 65535 0]Debemos ayudarlo[n]antes de que las cosas se tuerzan.[n][f 1 3 65535][w][e]

