[msg MSG_000_0_0 [Kawakami]]
[s][f 5 14]He acabado la tarea en clase.[n][w][e]

[msg MSG_001_0_0 [Kawakami]]
[s][f 5 14]Podemos pasar la Nochebuena[n]juntos si te apetece,[n]pero sin compromiso...[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Venga.[e]

[msg MSG_020_0_0 [Kawakami]]
[s][f 5 14]斡夷De verdad?! 斡Qu姻 guay, en serio![n][w][e]

[msg MSG_021_0_0 [Kawakami]]
[s][f 5 14]斡Estoy que lo flipo![n]En breve salgo para la ciudad.[n][f 5 15][w][e]

