[msg MSG_000_0_0 [Haru]]
[s][f 5 14]En vista de las circunstancias,[n]no sab胤a si hablar o no, pero...[n][w][e]

[msg MSG_000_5_0 [Haru]]
[s][f 5 14]Me gustar胤a pasar[n]la Nochebuena contigo.[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]夷Y si vamos a dar una vuelta...[n]y despu姻s subimos a tu habitaci吋n?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Me parece genial.[e]

[msg MSG_020_0_0 [Haru]]
[s][f 5 14]斡夷En serio?![n][w][e]

[msg MSG_021_0_0 [Haru]]
[s][f 5 14]斡Sigo en Shibuya! 斡Podemos quedar[n]frente a la estaci吋n![n][f 5 15][w][e]

