[msg MSG_000_0_0 [Takemi]]
[s][f 5 14]夷C吋mo est茨s? 夷Te han dado[n]escalofr胤os o fiebre?[n][w][e]

[msg MSG_001_0_0 [Takemi]]
[s][f 5 14]Quiero examinarte, as胤 que[n]p茨sate por la cl胤nica, por favor.[n][w][e]

[msg MSG_REACTION [Takemi]]
[s][f 5 14]Vale, te estar姻 esperando.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Takemi quiere examinarte.[n]夷Qu姻 vas a hacer?[n]夷Quieres ir a la cl胤nica?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir de inmediato[e]
[s]Comprobar v胤nculo con Takemi[e]
[s]Responder luego[e]

[sel SEL_002 top]
[s][f 5 14]Ahora mismo voy.[e]

