[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Por fin lo hemos conseguido.[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]Hemos hecho todo lo posible.[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]斡Al final esta vez hemos[n]empezado con un gran anuncio![n][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][f 5 14]Me muero por ver los resultados.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Pero toda esa popularidad[n]ya da igual.[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]Cierto. Cosas como el 胤ndice de[n]aprobaci吋n no importan ya.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]斡S胤![n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Seguro que hicimos lo[n]correcto por la sociedad.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Tenemos que estar[n]orgullosos, 夷no?[n][w][e]

[sel SEL_009_0_0 top]
[s][f 5 14]Claro.[e]
[s]No nos precipitemos.[e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]S胤, s胤.[n]No te rayes por m胤.[n][w][e]

[msg MSG_011_0_0 [Haru]]
[s][f 5 14][f 5 15]Ahora solo queda esperar[n]tranquilamente a los resultados.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Vale...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Tambi姻n deber胤amos actuar con[n]normalidad mientras esperamos.[n][f 1 3 65535][w][e]

