[msg MSG_000_0_0 [Yusuke]]
[s][f 5 14]夷Sab姻is algo de Akechi?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Nada.[n][w][e]

[msg MSG_002_0_0 [Haru]]
[s][f 5 14]Pero ma隠ana empieza el festival.[n]夷No pasar茨 nada?[n][w][e]

[msg MSG_003_0_0 [Haru]]
[s][f 5 14]Si Akechi rechaza nuestra oferta,[n]no tendremos invitado...[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]夷Eh? 夷Eso es lo que te preocupa?[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]Agradezco la preocupaci吋n,[n]pero no pasar茨 nada.[n][w][e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]Solo tengo que conseguir que[n]Akechi acepte sea como sea.[n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]S胤.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]夷Qu姻 est茨 tramando ese capullo?[n][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]No ha hecho nada desde[n]que dijo que se esconder胤a.[n][w][e]

[msg MSG_010_0_0 [Makoto]]
[s][f 5 14]No estoy segura. Intentar姻[n]explicarle las circunstancias[n]ligadas al festival otra vez.[n][w][e]

[msg MSG_011_0_0 [Makoto]]
[s][f 5 14]Con un poco de suerte,[n]podr茨 responder hoy.[n][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14][f 5 15]Ya os avisar姻 si hay[n]novedades sobre ese tema.[n][w][e]

