[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Buenas, 夷est茨is libres ma隠ana[n]despu姻s de clase?[n][w][e]

[msg MSG_001_0_0 [Yusuke]]
[s][f 5 14]En principio s胤. 夷Por qu姻?[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Quiero comentaros algo.[n]Podr胤amos quedar en el Leblanc.[n][w][e]
[s][f 5 14]Preg雨ntale tambi姻n al Jefe[n]si puede venir, [f 4 2].[n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]Claro.[e]
[s]A tus 吋rdenes.[e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Ning雨n problema.[n][w][e]

[msg MSG_005_0_0 [Haru]]
[s][f 5 14]A m胤 tambi姻n me va bien.[n]Ir姻 al salir de clase.[n][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]Yo tambi姻n me apunto.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Lo mismo digo. Vayamos ma隠ana[n]en cuanto podamos.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Guay, all胤 nos vemos.[n][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]夷Que Ryuji quiere hablar?[n]夷Le habr茨 pasado algo?[n][f 1 3 65535][w][e]

