[msg MSG_000_0_0 [Haru]]
[s][f 5 14]夷Sabes... qu姻 d胤a es hoy?[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]He de admitir que estoy[n]bastante emocionada.[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Lo tengo todo controlado.[e]

[msg MSG_020_0_0 [Haru]]
[s][f 5 14]斡夷En serio?![n][w][e]

[msg MSG_021_0_0 [Haru]]
[s][f 5 14]Quedamos en la estaci吋n de Shibuya.[n]Hasta pronto.[n][f 5 15][w][e]

