[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]斡Dios, qu姻 rabia![n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]Has o胤do lo que[n]ha dicho Akechi, 夷no, [f 4 1]?[n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]夷C吋mo se atreve a decir que los[n]Ladrones Fantasma son delincuentes?[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]Como administrador de la[n]Web del Aficionado de los Fantasmas,[n]no puedo quedarme callado.[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]斡Voy a mostrarle a Akechi c吋mo[n]se siente la gente en internet![n][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][f 5 14]Ma隠ana por la ma隠ana cambiar姻[n]la pregunta de la encuesta.[n][w][e]

[msg MSG_006_0_0 [Mishima]]
[s][f 5 14][f 5 15]斡La justicia est茨 del lado de[n]los Ladrones Fantasma! 斡Seguid[n]haciendo lo que sab姻is hacer![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]夷Por qu姻, con toda[n]la gente que hay, se enfada 姻l?[n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]De todas formas, se refiere[n]a la Fansite, 夷no?[n]Habr茨 que prepararse.[n][f 1 3 65535][w][e]

