[msg MSG_001_0_0 [Sojiro]]
[s][f 5 14]He o胤do que ese gato es ahora[n]tu compinche, 夷eh?[n][w][e]

[msg MSG_002_0_0 [Sojiro]]
[s][f 5 14]Es como si fuera tu compa隠ero.[n]O tu c吋mplice, tal vez.[n][w][e]

[msg MSG_003_0_0 [Sojiro]]
[s][f 5 14][f 5 19]Bueno, he conseguido haceros[n]una foto a los dos.[n][w][e]

[msg MSG_004_0_0 [Sojiro]]
[s][f 5 14][f 5 18 473 0 1][w][e]

[msg MSG_005_0_0 [Sojiro]]
[s][f 5 14]No sois muy diferentes, la verdad.[n][w][e]

[msg MSG_006_0_0 [Sojiro]]
[s][f 5 14]Los dos entr茨is y sal胤s[n]cuando os da la gana.[n][w][e]

[msg MSG_007_0_0 [Sojiro]]
[s][f 5 14][f 5 15]Seguid llev茨ndoos bien, 夷vale?[n][w][e]

[msg MSG_008_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 65535 0 0 0]Dummy[n][f 1 3 65535][w][e]

