[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]夷Qu姻 plan hay para hoy?[n]夷Ya lo has decidido?[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]Estoy en el Leblanc, as胤[n]que puedo quedar cuando sea.[n][w][e]

[msg MSG_001_1_0 [Futaba]]
[s][f 5 14]Estoy un poco nerviosa,[n]as胤 que estoy por el Leblanc.[n][w][e]

[msg MSG_001_2_0 [Futaba]]
[s][f 5 14]Estoy delante del Leblanc.[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Av胤same si pasa algo.[n]Sea lo que sea.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Parece que Futaba est茨[n]fuera del Leblanc otra vez.[n]夷Quieres ir a verla un rato?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Nadie cree que sigas vivo a estas[n]alturas, as胤 que no pasar茨 nada[n]mientras vayas con cuidado.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0]夷Quieres ir a ver a Futaba?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Voy para all茨.[e]

[msg MSG_REACTION [Futaba]]
[s][f 5 14]O胤do cocina.[n][f 5 15][w][e]

