[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Buah, 斡qu姻 f茨cil ha sido[n]lo del Nakanohara ese![n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Si acabamos con alg雨n objetivo[n]medianamente gordo a la pr吋xima,[n]ah胤 s胤 que nos hacemos famosos.[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]斡Oye, queremos ayudar a la gente,[n]no hacernos famosos![n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Pero si no saben qui姻nes somos,[n]夷c吋mo vamos a infundirles valor?[n][w][e]

[sel SEL_004_0_0 top]
[s][f 5 14]Tiene raz吋n.[e]
[s]Ryuji, 夷est茨s seguro?[e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]夷Veis?[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]夷Me equivoco?[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14]Tampoco es que crea[n]que te equivoques...[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]Pero 夷deber胤amos estar[n]haciendo esto sin motivos?[n]Con Kamoshida los ten胤amos...[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]夷Te refieres a que no deber胤amos[n]meter las narices[n]en asuntos ajenos?[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Uf, no s姻.[n]Si alguien tiene problemas,[n]斡es l吋gico querer ayudarlo![n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]A ver, en eso estoy de acuerdo.[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14]Y me alegro de haber podido[n]resolver el caso del acosador.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]Adem茨s,[n]夷de qu姻 sirven nuestras Personas[n]si no las usamos para el bien?[n][w][e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14]夷No es verdad, [f 4 2]?[n][w][e]

[sel SEL_015_0_0 top]
[s][f 5 14]Desde luego.[e]
[s]Quiero ayudar a la gente.[e]

[msg MSG_016_0_0 [Ann]]
[s][f 5 14]S胤, tienes raz吋n.[n][w][e]

[msg MSG_017_0_0 [Ann]]
[s][f 5 14]Lo mismo digo.[n][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][f 5 14]Y tampoco tenemos mucho tiempo[n]para discutir por esto.[n]Me preocupa ese tal Madarame.[n][w][e]

[msg MSG_019_0_0 [Ann]]
[s][f 5 14]S胤, pero nada de dejarse llevar,[n]夷entendido?[n][w][e]

[msg MSG_020_0_0 [Ann]]
[s][f 5 14]Y no hagas nada[n]que llame demasiado la atenci吋n,[n]como suspender todos los ex茨menes.[n][w][e]

[msg MSG_021_0_0 [Ryuji]]
[s][f 5 14][f 5 15]斡Hostia! Ahora que lo dices,[n]no he estudiado ni pizca...[n][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][f 5 14]夷Qu姻 pasa con la estrella,[n]la que nos dio Jose?[n][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][f 5 14]夷Servir茨 para bordar los ex茨menes?[n][w][e]

[msg MSG_024_0_0 [Ann]]
[s][f 5 14]La verdad es que lo dudo.[n][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][f 5 14]Bueno, me basta con no suspender.[n][w][e]

[msg MSG_026_0_0 [Ann]]
[s][f 5 14]Aqu胤 no vale negociar,[n]y tampoco es que la fu姻ramos[n]a usar para eso.[n][w][e]

[msg MSG_027_0_0 [Ann]]
[s][f 5 14]A lo mejor deber胤as,[n]no s姻, esforzarte.[n]A雨n tienes tiempo.[n][w][e]

[msg MSG_028_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Vaaale...[n][w][e]

