[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Si viene, ser茨 hoy.[n][w][e]

[msg MSG_002_0_0 [Sumire]]
[s][f 5 14]Qu姻 nervios...[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Yo tambi姻n estoy nervioso.[n]No me puedo ni centrar en clase.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Pues como siempre.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]斡Calla! Va en serio, hoy no he[n]podido. Lo he intentado y todo.[n][w][e]

[sel SEL_006_0_0 top]
[s][f 5 14]Nos ir茨 igual de bien que siempre.[e]
[s]Solo nos queda luchar.[e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]斡Por supuesto![n][w][e]

[msg MSG_008_0_0 [Yusuke]]
[s][f 5 14]Nos congratula enormemente[n]tu buena compostura.[n][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][f 5 14][f 4 2], Maruki seguramente[n]se acerque a ti.[n][w][e]

[msg MSG_010_0_0 [Akechi]]
[s][f 5 14]En tal caso, c胤隠ete[n]a lo que hemos planeado.[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]Estamos hablando de [f 4 2].[n]斡No hay de qu姻 preocuparse![n][w][e]

[msg MSG_012_0_0 [Makoto]]
[s][f 5 14][f 5 15]S姻 que es mucho pedir, pero[n]夷podr胤as llamar por nosotros [n]si no pasa por aqu胤?[n][w][e]

[sel SEL_013_0_0 top]
[s][f 5 14]Entendido.[e]
[s]Yo me encargo.[e]

[msg MSG_014_0_0 [Haru]]
[s][f 5 14][f 5 15]Av胤sanos si algo va mal,[n]夷de acuerdo?[n][w][e]

[msg MSG_015_0_0 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 1 1027 65535 0]夷Cu茨l ser茨 el pr吋ximo movimiento[n]de Maruki? Incluso yo[n]me estoy poniendo nervioso.[n][f 1 3 65535][w][e]

