[msg MSG_000_0_0 [Ohya]]
[s][f 5 14]Hace tiempo que no vienes.[n][w][e]

[msg MSG_001_0_0 [Ohya]]
[s][f 5 14]夷No tienes pistas[n]interesantes para darme? O es que...[n][w][e]

[msg MSG_002_0_0 [Ohya]]
[s][f 5 14]夷Ya no nos vemos[n]porque no necesitas[n]que te d姻 informaci吋n?[n][f 5 15][w][e]

[msg MSG_003_0_0 [Ohya]]
[s][f 5 14]Te espero en el bar esta noche.[n][f 5 15][w][e]

[msg CHAT_NOREACTION_MSG [Ohya]]
[s][f 5 14]夷Por qu姻 no has venido?[n]斡He estado esper茨ndote[n]un buen rato![n][w][e]

[msg CHAT_REACTION_MSG [Ohya]]
[s][f 5 14]Vale.[n][f 5 15][w][e]

[msg MND_COOP_RANK_UP_OK]
[s]Siento que mi v胤nculo con Ohya[n]se fortalecer茨 pronto.[n][w][e]

[msg MSG_MORUGANA_RANK1 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ten cuidado. Levantar茨s sospechas[n]si rechazas una invitaci吋n[n]justo despu姻s de cerrar un trato.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Si no tienes otros planes,[n]ve. 夷Entendido?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ten cuidado. Levantar茨s sospechas[n]si rechazas una invitaci吋n[n]justo despu姻s de cerrar un trato.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Si no tienes otros planes,[n]ve. 夷Entendido?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ten cuidado. Levantar茨s sospechas[n]si rechazas una invitaci吋n[n]justo despu姻s de cerrar un trato.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Si no tienes otros planes,[n]ve. 夷Entendido?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK4 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ten cuidado. Levantar茨s sospechas[n]si rechazas una invitaci吋n[n]justo despu姻s de cerrar un trato.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Si no tienes otros planes,[n]ve. 夷Entendido?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_RANK5 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ten cuidado. Levantar茨s sospechas[n]si rechazas una invitaci吋n[n]justo despu姻s de cerrar un trato.[n][f 1 3 65535][w][e]
[s][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Si no tienes otros planes,[n]ve. 夷Entendido?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA_CORPNG [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Seguro que est茨s cansado[n]de la incursi吋n al Metaverso.[n]Quiz茨 deber胤as descansar por hoy.[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir de inmediato[e]
[s]Comprobar v胤nculo con Ohya[e]
[s]Responder luego[e]

[sel SEL_002 top]
[s][f 5 14]Ahora mismo voy.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]Gracias a la Persona del arcano[n][var 2], [clr 1][var 5][clr 27],[n]puedo estrechar lazos con Ohya.[n][w][e]

[msg MSG_SPOT_OPEN_ASAKUSA]
[s]Ahora puedes acceder a una nueva[n]ubicaci吋n: [clr 1]Asakusa[clr 27].[n][w][e]

