[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Oye, [f 4 2], 夷tienes un rato hoy?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]Me gustar胤a[n]que nos vi姻ramos un rato...[n][w][e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]Te estar姻 esperando en el centro[n]comercial subterr茨neo.[n][w][e]

[msg CHAT_NOREACTION_MSG [Makoto]]
[s][f 5 14]夷Te pillo en mal momento?[n]Llevo esperando todo el d胤a...[n]Bueno, ya te volver姻 a invitar.[n][w][e]

[msg CHAT_REACTION_MSG [Ann]]
[s][f 5 14]Gracias. 夷Te importa venir[n]a donde estoy yo?[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Bueno, 夷vas a aceptar[n]la invitaci吋n de la se隠orita Ann?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir de inmediato[e]
[s]Comprobar v胤nculo con Ann[e]
[s]Responder luego[e]

[sel SEL_002 top]
[s][f 5 14]Ya mismo voy.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]Deber胤a poder mejorar[n]nuestro v胤nculo ya que tengo[n]a [clr 1][var 5][clr 27] del arcano [var 2]...[n][w][e]

