[msg MSG_000_0_0 [Haru]]
[s][f 5 14]Perdonad que os escriba[n]tan temprano.[n][w][e]

[msg MSG_001_0_0 [Haru]]
[s][f 5 14]Parece ser que mi padre dar茨[n]una rueda de prensa urgente.[n][w][e]

[msg MSG_002_0_0 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 1 0 0 48 0 0]Supongo que Okumura[n]por fin despert吋.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 49 0 0]Eso le quitar茨[n]un peso de encima a Haru.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]斡夷En serio?![n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]斡Enhorabuena![n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]夷Cu茨ndo ser茨?[n][w][e]

[msg MSG_006_0_0 [Haru]]
[s][f 5 14]Esta noche a las 8.[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Me pregunto si hablar茨[n]de las desconexiones mentales.[n][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][f 5 14]夷D吋nde podemos verla?[n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]夷Por qu姻 no nos reunimos antes?[n][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Suena bien.[e]
[s]夷Te preocupa algo?[e]

[msg MSG_011_0_0 [Makoto]]
[s][f 5 14]No tengo ning雨n motivo[n]para quedar, pero puede[n]que nos beneficie.[n][w][e]

[msg MSG_012_0_0 [Haru]]
[s][f 5 14]Muy bien, 夷qu姻 os parece[n]la azotea del Instituto Shujin?[n][w][e]

[msg MSG_013_0_0 [Haru]]
[s][f 5 14]De hecho, tengo unos asuntos[n]que atender all胤.[n][w][e]

[msg MSG_014_0_0 [Ann]]
[s][f 5 14]Por m胤 perfecto.[n]Hace siglos que no subo all胤.[n][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][f 5 14]Espera... 夷El instituto?[n][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][f 5 14]Futaba, aseg雨rate de entrar[n]por la puerta principal.[n][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][f 5 14][f 5 15]Nos vemos all胤 despu姻s de clase.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 50 0 0]Mmm... Esperad, 夷d吋nde est茨 Yusuke?[n][f 1 3 65535][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 1 0 0 51 0 0]Si sigue dormido a esta hora,[n]llegar茨 tarde a clase.[n][f 1 3 65535][w][e]

