[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]Eh, no lo habr姻is olvidado, 斡夷no?![n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]斡Ya sab姻is, lo del folleto![n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]Tenemos que investigar[n]ese servicio de tareas del hogar.[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14][f 5 15]Ahora mismo estoy en[n]la calle principal, as胤 que venid[n]a hablar conmigo si os interesa.[n][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Mishima nos est茨 esperando[n]en Shibuya.[n]夷Cre姻is que deber胤amos ir a verlo?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Ya mismo voy.[e]

[msg MSG_REACTION [Mishima]]
[s][f 5 14]斡Vale, os espero![n][w][e]

[msg MSG_REACTION_02 [Mishima]]
[s][f 5 14]Por favor, no me dej姻is[n]plantado, 夷vale?[n][f 5 15][w][e]

