[msg MSG_000_0_0 [Futaba]]
[s][f 5 14]Te est茨n costando[n]los estudios, 夷no?[n][w][e]

[msg MSG_001_0_0 [Futaba]]
[s][f 5 14]Lo s姻. En nada[n]tienes los ex茨menes, 夷no?[n][w][e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]No tienes remedio.[n]夷Te echo una mano?[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Bueno, 夷entonces qu姻?[n]夷Vas a estudiar con Futaba?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Estudiar con ella[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]畏chame una mano.[e]

[msg MSG_REACTION [Futaba]]
[s][f 5 14]Ya veo, ya.[n]Pues te veo en el Leblanc.[n][f 5 15][w][e]

