[msg MSG_000_0_0 [Sumire]]
[s][f 5 14]夷Sabes que hoy es el D胤a Blanco?[n]斡Ahora te toca a ti![n][w][e]

[msg MSG_001_0_0 [Sumire]]
[s][f 5 14]Esperaba poder verte hoy.[n]夷Est茨s libre?[n][f 5 15][w][e]

[sel SEL_010_0_0 top]
[s][f 5 14]Para ti, s胤.[e]

[msg MSG_020_0_0 [Sumire]]
[s][f 5 14]斡Pues quedamos en Shibuya![n][w][e]

[msg MSG_021_0_0 [Sumire]]
[s][f 5 14]斡Voy ahora mismo![n]斡Qu姻 ganas![n][f 5 15][w][e]

