[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]夷Has visto ya el art胤culo?[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]No.[e]
[s]夷Qu姻 clase de art胤culo?[e]
[s]夷Habla de nosotros?[e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Es una entrevista a un[n]chico del instituto.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Dir胤a que no. Es una entrevista[n]a un chaval del Shujin.[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]或El chico M lo explica todo:[n]斡Los abusos del caso Kamoshida!位.[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Como dec胤a, trata principalmente[n]el tema del maltrato f胤sico.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]夷Cre姻is que el tal M es Mishima?[n][w][e]

[sel SEL_013_0_0 top]
[s][f 5 14]No lo s姻.[e]
[s]Podr胤a ser Makoto.[e]
[s]Probablemente.[e]

[msg MSG_014_0_0 [Ryuji]]
[s][f 5 14]Quiz茨 me lo estoy imaginando,[n]yo qu姻 s姻...[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Pero 夷qu姻 otra persona tiene[n]una eme en el nombre y fue[n]maltratada por Kamoshida?[n][w][e]

[msg MSG_016_0_0 [Ryuji]]
[s][f 5 14]Ah, claro. Makoto tambi姻n[n]tiene una eme. 夷Ser茨 ella?[n][w][e]

[msg MSG_018_0_0 [Ryuji]]
[s][f 5 14]Pero 斡si dice 或chico M位![n]斡Tiene que ser un t胤o![n][w][e]

[msg MSG_019_0_0 [Ryuji]]
[s][f 5 14]Adem茨s, Makoto nunca har胤a[n]una entrevista para un tabloide.[n][w][e]

[msg MSG_020_0_0 [Ryuji]]
[s][f 5 14]As胤 que tiene que ser 姻l.[n][w][e]

[msg MSG_022_0_0 [Ryuji]]
[s][f 5 14]Y la Fansite esa tambi姻n[n]ha sido de gran ayuda.[n][w][e]

[msg MSG_023_0_0 [Ryuji]]
[s][f 5 14]Ser茨 mejor dejarlo tranquilo.[n]No nos hace ning雨n da隠o.[n][w][e]

[msg MSG_025_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Hasta luego.[n][w][e]

[msg MSG_026_0_0 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Sobre el art胤culo...[n]夷Crees que ha sido cosa de[n]la periodista del Crossroads?[n][f 1 3 65535][w][e]

[msg MSG_026_5_0]
[s][vp 1 0 0 0 0 0]Debo echarle un vistazo al art胤culo[n]del que ha hablado Ryuji...[n][f 1 3 65535][w][e]

[msg MSG_027_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Como pensaba, pone que[n]la autora es Ichiko Ohya.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Interesante. Puede que el art胤culo[n]haya acabado benefici茨ndonos.[n][f 1 3 65535][w][e]

[sel SEL_028_0_0 top]
[s]Cierto.[e]
[s]夷C吋mo?[e]

[msg MSG_029_0_0 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 4 0 0]Si el se隠or del Palacio lo ve y[n]su concepto de los Ladrones[n]Fantasma cambia...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 5 0 0]Oye, [f 4 2]. Hay que sacar[n]ventaja de esto s胤 o s胤.[n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 6 0 0]Si dejamos que hable bien de[n]nosotros, 斡pondremos a la opini吋n[n]p雨blica de nuestra parte![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 7 0 0]斡Tienes que intentar que[n]escriba m茨s art胤culos sobre[n]los Ladrones Fantasma![n][f 1 3 65535][w][e]

