[msg MSG_013_0_0 [Mishima]]
[s][f 5 14]Oye, traigo informaci吋n fresca.[n][w][e]

[msg MSG_014_0_0 [Mishima]]
[s][f 5 14]Lo he visto en la Fansite,[n]pero tambi姻n se comenta[n]por el instituto.[n][w][e]
[s][f 5 14]Hay un tipo en el instituto[n]que se pasa de abus吋n.[n][w][e]
[s][f 5 14]Quiero ayudar a la v胤ctima, pero[n]me es imposible.[n][w][e]
[s][f 5 14]斡Los Ladrones Fantasma[n]tomar茨n cartas en el asunto![n][w][e]
[s][f 5 14]Despertaste el coraz吋n[n]de una acosadora, as胤 que esto[n]ser茨 pan comido.[n][w][e]

[sel SEL_015_0_0 top]
[s][f 5 14]Qu姻 f茨cil.[e]
[s]Estoy algo asustado...[e]
[s]No me interesa.[e]

[msg MSG_016_0_0 [Mishima]]
[s][f 5 14]斡Eres incre胤ble![n][w][e]

[msg MSG_017_0_0 [Mishima]]
[s][f 5 14]Venga ya, s姻 que no lo dices[n]en serio. Basta de bromas.[n][w][e]

[msg MSG_018_0_0 [Mishima]]
[s][f 5 14]Venga ya, no seas as胤. Al menos[n]d姻jame que te cuente los detalles.[n][w][e]

[msg MSG_019_0_0 [Mishima]]
[s][f 5 14]El abus吋n es un chaval de pelo[n]casta隠o que suele estar[n]en la entrada del instituto.[n][w][e]
[s][f 5 14]Hasta donde yo s姻,[n]se llama Daisuke Takanashi.[n][w][e]
[s][f 5 14][f 5 15]斡S姻 que pod姻is hacerlo![n][w][e]

[msg MSG_quest03_MORGANA_SAY [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]斡Has conseguido informaci吋n[n]de un nuevo objetivo![n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 1 0 65535 0]S姻 que es un caso insignificante,[n]pero tenemos un nombre, as胤 que[n]debemos considerarlo un objetivo.[n][f 1 3 65535][w][e]

[msg MND_quest03_OPEN_SELF]
[s][vp 8 2 65535 0 0 0]He conseguido informaci吋n de un[n]objetivo. Deber胤a ir al escondite[n]a ver qu姻 opinan los dem茨s...[n][f 1 3 65535][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Dummy scriptChat_223[e]

