[msg MSG_000_0_0 [Ann]]
[s][f 5 14]夷Has encontrado alguna pista?[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Tengo un nombre.[e]
[s]Te lo digo ma隠ana.[e]

[msg MSG_002_0_0 [Ann]]
[s][f 5 14]斡Lo has conseguido![n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Teniendo en cuenta c吋mo intentas[n]mantenernos en vilo,[n]supongo que ser茨n buenas noticias.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Muy bien,[n]斡nos vemos en el escondite ma隠ana![n][w][e]

[msg MSG_005_0_0 [Yusuke]]
[s][f 5 14]Entendido.[n][w][e]

[msg MSG_006_0_0 [Yusuke]]
[s][f 5 14]Ryuji parece estar ausente[n]de esta conversaci吋n.[n]夷Le hablamos por privado?[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14][f 5 15]Seguro que luego mirar茨 el m吋vil[n]y se enterar茨 de todo.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 8 0 0]斡Pues a lo tonto, ya estamos[n]en el Palacio de Kaneshiro![n][f 1 3 65535][w][e]
[s][bup 0 3 1 65535 0][f 4 10 65535 0 0][vp 1 0 0 9 0 0]斡Ha sido incre胤blemente f茨cil![n][f 1 3 65535][w][e]

