[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]夷C吋mo vamos a encontrar a Medjed?[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]No lo s姻. Por mucho que[n]busque en internet, solo encuentro[n]rumores poco fiables.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Han realizado campa隠as de terror[n]y sin embargo consiguen evitar[n]que los detengan.[n][w][e]

[msg MSG_003_0_0 [Yusuke]]
[s][f 5 14]Kaneshiro dio muchos problemas,[n]pero esto se est茨 convirtiendo[n]en un suplicio.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]夷Nos hemos metido[n]en camisa de once varas?[n][w][e]

[sel SEL_005_0_0 top]
[s][f 5 14]Son demasiado grandes.[e]
[s]No lo s姻.[e]

[msg MSG_006_0_0 [Makoto]]
[s][f 5 14]S胤...[n][w][e]

[msg MSG_007_0_0 [Makoto]]
[s][f 5 14]Claro. No hay forma de saber[n]a qui姻n nos enfrentamos[n]si no lo sabemos todo.[n][w][e]

[msg MSG_008_0_0 [Makoto]]
[s][f 5 14]Ni siquiera sabemos si se trata[n]de un 雨nico individuo o de un gran[n]conglomerado de personas.[n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Y aunque logr茨semos encontrar[n]una pista, 夷qu姻 haremos despu姻s?[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Joder, esto pinta muy mal...[n][w][e]

[msg MSG_011_0_0 [Ryuji]]
[s][f 5 14]Probablemente tambi姻n[n]la cagar姻 con los ex茨menes.[n][w][e]

[msg MSG_012_0_0 [Ann]]
[s][f 5 14][f 5 15]Sabes que son dos cosas[n]distintas, 夷no?[n][w][e]

