[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]C吋mo molan las motos, colega...[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Ojal茨 mi Persona fuera as胤.[n][w][e]

[msg MSG_002_0_0 [Yusuke]]
[s][f 5 14]Pero si la tuya va en barco.[n][w][e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]斡夷Lo dices en serio, tronco?![n]斡Las motos les dan mil vueltas[n]a los cacharros esos![n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Ya lo dice la canci吋n:[n]或I'm a phantom, on[n]a steel horse I ride...位.[n][w][e]

[msg MSG_005_0_0 [Makoto]]
[s][f 5 14]No estoy segura de que[n]la canci吋n diga eso...[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Sinceramente, Niijima,[n]me sorprende el mero hecho[n]de que sepas ir en moto.[n][w][e]

[msg MSG_013_0_0 [Ryuji]]
[s][f 5 14]夷Tienes carnet?[n][w][e]

[msg MSG_014_0_0 [Makoto]]
[s][f 5 14]S胤, el normal.[n][w][e]

[msg MSG_015_0_0 [Ryuji]]
[s][f 5 14]Mooola...[n]Estoy como loco por tener una.[n][w][e]

[msg MSG_016_0_0 [Makoto]]
[s][f 5 14]Por cierto,[n]quer胤a hablaros de otro tema.[n][w][e]

[msg MSG_017_0_0 [Yusuke]]
[s][f 5 14]夷Qu姻 ocurre?[n][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][f 5 14]Lo siento.[n][w][e]

[msg MSG_019_0_0 [Makoto]]
[s][f 5 14]S姻 que no deber胤a decir esto,[n]de verdad...[n][w][e]

[msg MSG_020_0_0 [Makoto]]
[s][f 5 14]Pero quiero disculparme.[n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][f 5 14]Est茨is metidos en este l胤o[n]por mi culpa.[n][w][e]

[msg MSG_022_0_0 [Makoto]]
[s][f 5 14]Adem茨s, malinterpret姻[n]vuestras intenciones.[n][w][e]

[msg MSG_023_0_0 [Makoto]]
[s][f 5 14]Ojal茨 me hubiera dado cuenta[n]de lo que le pasaba a Suzui...[n][w][e]

[msg MSG_024_0_0 [Ann]]
[s][f 5 14]Venga, no hablemos de eso ahora.[n][w][e]

[msg MSG_025_0_0 [Yusuke]]
[s][f 5 14]Parece que a todos nos rondan[n]asuntos todav胤a.[n][w][e]

[msg MSG_026_0_0 [Ryuji]]
[s][f 5 14]Pero 斡ahora no es momento[n]de hablar de esas mierdas![n][w][e]

[msg MSG_027_0_0 [Ryuji]]
[s][f 5 14]夷No deber胤amos estar haciendo[n]algo con Kaneshiro?[n][w][e]

[msg MSG_028_0_0 [Ann]]
[s][f 5 14]Tiene raz吋n.[n][w][e]

[msg MSG_029_0_0 [Makoto]]
[s][f 5 14]Es verdad, lo entiendo.[n][w][e]

[msg MSG_030_0_0 [Makoto]]
[s][f 5 14][f 5 15]En fin, har姻 todo lo posible[n]por no ralentizaros.[n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 3 65535 0][f 4 10 65535 0 0][vp 1 0 0 10 0 0]Vaya, si hasta hace un momento[n]est茨bamos todos en desacuerdo...[n][f 1 3 65535][w][e]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 11 0 0]Pero Ryuji tiene toda la raz吋n.[n]斡Hay que trabajar juntos[n]para acabar con esto![n][f 1 3 65535][w][e]

