[msg MSG_000_0_0 [Sumire]]
[s][f 5 14]Una cosa...[n][w][e]

[msg MSG_001_0_0 [Sumire]]
[s][f 5 14]En teor胤a, el doctor Maruki[n]nos va a llamar hoy, 夷no?[n][w][e]

[msg MSG_002_0_0 [Sumire]]
[s][f 5 14]Hay algo que me gustar胤a[n]decirte antes.[n][w][e]

[msg MSG_003_0_0 [Sumire]]
[s][f 5 14]夷Tienes tiempo?[n][f 5 15][w][e]

[msg CHAT_REACTION_MSG_01 [Sumire]]
[s][f 5 14]斡Genial![n][w][e]

[msg CHAT_REACTION_MSG_02 [Sumire]]
[s][f 5 14]夷Quedamos primero?[n][w][e]
[s]Prefiero un sitio donde podamos[n]relajarnos y hablar.[n][w][e]
[s]Siento tanto l胤o.[n]Espero que hablemos pronto.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Creo que quer胤a hablar contigo[n]antes. Tal vez deber胤as escucharla.[n][f 1 3 65535][w][e]
[s][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Bueno, 夷entonces qu姻?[n]夷Quieres ir a ver a Sumire?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir de inmediato[e]
[s]Comprobar v胤nculo con Sumire[e]
[s]Responder luego[e]

[sel SEL_002 top]
[s][f 5 14]Ahora mismo voy.[e]

[msg MND_COOP_DOUZOKUSEI]
[s]Deber胤a poder mejorar[n]nuestro v胤nculo ya que tengo[n]a [clr 1][var 5][clr 27] del arcano [var 2]...[n][w][e]

