[msg MSG_000_0_0 [Ann]]
[s][f 5 14]Sigo pensando en lo que[n]ha dicho Nakanohara...[n][w][e]

[msg MSG_001_0_0 [Ann]]
[s][f 5 14]夷Y si estaba hablando de[n]Madarame, el artista famoso?[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Pues s胤.[e]
[s]Probablemente no.[e]
[s]Bien visto.[e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Eso creo.[n][w][e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Genial. El nombre me llam吋[n]mucho la atenci吋n.[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]Me gustar胤a estar de acuerdo[n]contigo, pero ese apellido es raro...[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]Bueno, es un apellido[n]muy inusual.[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]S胤. 夷Alguna vez hab胤ais o胤do hablar[n]de alguien que se llame Madarame?[n][w][e]

[msg MSG_008_0_0 [Ann]]
[s][f 5 14]No es com雨n, para nada.[n][w][e]

[msg MSG_009_0_0 [Ann]]
[s][f 5 14]Si lo que hemos o胤do es cierto,[n]Kitagawa est茨 bajo la tutela de[n]un profesor corrupto.[n][w][e]

[msg MSG_010_0_0 [Ryuji]]
[s][f 5 14]Es decir, un profesor que trata[n]a la gente como herramientas.[n][w][e]

[msg MSG_011_0_0 [Ann]]
[s][f 5 14]La vida de Kitagawa[n]tiene que ser horrorosa.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14][f 5 15]Hay que investigar.[n][w][e]

