[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]Madre m胤a, pues s胤 que es[n]impactante eso del Palacio.[n][w][e]

[msg MSG_001_0_0 [Ryuji]]
[s][f 5 14]Quiero decir...[n][w][e]

[msg MSG_002_0_0 [Ryuji]]
[s][f 5 14]Solo existe por lo cabr吋n[n]que es Kamoshida, 夷verdad?[n][w][e]

[sel SEL_003_0_0 top]
[s][f 5 14]Eso parece.[e]
[s]夷En serio?[e]

[msg MSG_004_0_0 [Ann]]
[s][f 5 14]Qu姻 miedo...[n][w][e]

[msg MSG_005_0_0 [Ryuji]]
[s][f 5 14]Bueno, eso dijo Morgana.[n][w][e]

[msg MSG_006_0_0 [Ann]]
[s][f 5 14]La verdad, todav胤a me cuesta creer[n]que un sitio as胤 exista siquiera.[n][w][e]

[msg MSG_007_0_0 [Ryuji]]
[s][f 5 14]Pues da igual[n]que te lo creas o que no.[n][w][e]

[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Esta oportunidad[n]nos ha ca胤do del cielo.[n][w][e]

[msg MSG_009_0_0 [Ryuji]]
[s][f 5 14]No nos queda otra opci吋n[n]que aprovecharla.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14][f 5 15]Tienes raz吋n. 斡Hay que apostarlo[n]todo a su despertar![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Parece que esos dos[n]est茨n muy animados.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 2 0 0]Y esta es una oportunidad[n]雨nica para ti tambi姻n.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 1 0 0 3 0 0]Si quieres darle la vuelta[n]a tu situaci吋n actual,[n]no puedes desaprovechar la ocasi吋n.[n][f 1 3 65535][w][e]

