[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]夷Te acuerdas de esa solicitud[n]de Mishima que aceptamos?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Ahora mismo no tenemos ning雨n[n]Palacio al que darle prioridad.[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]Si hacemos eso ahora,[n]quiz茨 nos ayude a prepararnos[n]para lo que venga.[n][w][e]

[msg MSG_003_0_0 [Makoto]]
[s][f 5 14]夷Qu姻 tal si vamos a Mementos hoy?[n]Si os viene bien.[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Ah, s胤, a雨n no hemos acabado[n]la solicitud de Mishima.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][f 4 25 1 65535 0 0][vp 1 0 0 0 0 0]Si vamos a ir a Mementos,[n]re雨ne a todo el mundo[n]en el escondite, 夷quieres?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Reunirse[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Venga.[e]

[msg MSG_REACTION [Makoto]]
[s][f 5 14]Entendido. 夷Puedes reunir[n]a todo el mundo en el escondite?[n][f 5 15][w][e]

