[msg MSG_000_0_0 [Hifumi]]
[s][f 5 14]Me gustar胤a verte hoy...[n][w][e]

[msg MSG_001_0_0 [Hifumi]]
[s][f 5 14]Ma隠ana empieza el torneo de[n]shogi en el que participo, as胤 que...[n][w][e]

[msg MSG_002_0_0 [Hifumi]]
[s][f 5 14]Si tienes tiempo, ven[n]a charlar un rato.[n][w][e]

[msg MSG_003_0_0 [Hifumi]]
[s][f 5 14]Te espero en la iglesia.[n][f 5 15][w][e]

[msg MSG_LAST_GREETING_DOOR_0 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Todav胤a no has hablado con ninguno[n]de los dos. 夷Aun as胤 quieres[n]ir a ver a Hifumi?[n][f 1 3 65535][w][e]

[msg MSG_LAST_GREETING_DOOR_0_2 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Todav胤a no has hablado con Futaba.[n]夷Aun as胤 quieres[n]ir a ver a Hifumi?[n][f 1 3 65535][w][e]

[msg MSG_LAST_GREETING_DOOR_0_3 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0]Todav胤a no has hablado con el[n]Jefe. 夷Aun as胤 quieres[n]ir a ver a Hifumi?[n][f 1 3 65535][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]夷Quieres ir a ver a Hifumi?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

