[msg test_mes01 [Ryuji]]
[s][f 5 14]斡夷Lo hab姻is o胤do?![n][w][e]

[msg test_mes02 [Ann]]
[s][f 5 14]夷Qu姻 pasa? 夷Es algo[n]de Al胤 Bab茨 o de Medjed?[n][w][e]

[msg test_mes03 [Ryuji]]
[s][f 5 14]斡Tenemos que recuperar[n]clase hasta el 1 de agosto![n][w][e]

[msg test_mes04 [Makoto]]
[s][f 5 14]......[n][w][e]

[msg test_mes04_1 [Makoto]]
[s][f 5 14]Ser茨 como hemos perdido[n]algunas por el incidente[n]de Kamoshida.[n][w][e]

[msg test_mes05 [Ryuji]]
[s][f 5 14]斡A la mierda el tiempo libre![n][w][e]

[msg test_mes06 [Ann]]
[s][f 5 14]Espera... 夷Solo nos has[n]llamado por eso?[n][w][e]

[msg test_mes06_1 [Ann]]
[s][f 5 14]Me voy a dormir.[n][w][e]

[msg test_mes07 [Ryuji]]
[s][f 5 14]夷Qu姻? 斡Espera, porfa![n][w][e]

[sel test_selA top]
[s][f 5 14]Buenas noches, Ryuji.[e]
[s]夷Y qu姻 pasa con el verano?[e]

[msg test_selA_0_mes01 [Ryuji]]
[s][f 5 14][f 5 15]夷De verdad soy el 雨nico[n]al que le jode?[n][w][e]

[msg test_selA_1_mes01 [Ryuji]]
[s][f 5 14]斡夷Verdad?! 斡Que le den a Kamoshida![n][w][e]

[msg test_selA_1_mes02 [Makoto]]
[s][f 5 14]Supongo que el tiempo libre[n]es algo valioso. Venga,[n]buenas noches.[n][w][e]

[msg test_selA_2_mes01 [Ryuji]]
[s][f 5 14][f 5 15]......[n][w][e]

