[msg MSG_000_0_0 [Futaba]]
[s][f 5 14][f 5 15]Perd吋n por irme as胤.[n]Quer胤a investigar[n]una cosa.[n][w][e]

[sel SEL_001_0_0 top]
[s][f 5 14]Est茨 bien.[e]
[s]夷Qu姻 era?[e]
[s]夷Te has resfriado?[e]

[msg MSG_002_0_0 [Futaba]]
[s][f 5 14]Gracias.[n][w][e]

[msg MSG_003_0_0 [Futaba]]
[s][f 5 14]Es un secreto.[n][w][e]

[msg MSG_004_0_0 [Futaba]]
[s][f 5 14]Me lavo las manos religiosamente,[n]as胤 que casi nunca enfermo.[n][w][e]

[msg MSG_005_0_0 [Futaba]]
[s][f 5 14]De todas formas, es una[n]porquer胤a detr茨s de otra.[n][w][e]

[msg MSG_006_0_0 [Futaba]]
[s][f 5 14]夷Conoces al vendedor de boniatos[n]de Yongen? Viene a mi casa cada dos[n]por tres. Est茨n para morirse.[n][w][e]

[msg MSG_007_0_0 [Futaba]]
[s][f 5 14]Pru姻balos, [f 4 2].[n]As胤 te calmar茨s.[n][w][e]

[msg MSG_008_0_0 [Futaba]]
[s][f 5 14]Los vende hasta[n]finales de octubre.[n]斡Yo recomiendo los Fantasmiatos![n][w][e]

[msg MSG_009_0_0 [Futaba]]
[s][f 5 14]Eso me recuerda que[n]ahora venden unos guisos oscuros[n]en las m茨quinas expendedoras...[n][w][e]

[msg MSG_010_0_0 [Futaba]]
[s][f 5 14][f 5 15]夷Quieres probarlos?[n][w][e]

[sel SEL_011_0_0 top]
[s][f 5 14]Gracias, pero no.[e]
[s]Solo si lo pruebas t雨.[e]
[s]Vamos a d茨rselo a Morgana.[e]

[msg MSG_012_0_0 [Futaba]]
[s][f 5 14]La experiencia lo es todo.[n]Tampoco es que vaya a probarlo.[n][w][e]

[msg MSG_013_0_0 [Futaba]]
[s][f 5 14]Yo no quiero, pero[n]me lo pensar胤a dos veces[n]si dijeras que est茨 rico.[n][w][e]

[msg MSG_014_0_0 [Futaba]]
[s][f 5 14]斡Buena idea! Pero recuerda[n]dejar que se enfr胤e antes.[n][w][e]

[msg MSG_015_0_0 [Futaba]]
[s][f 5 14]Oye, [f 4 2]...[n][w][e]

[msg MSG_016_0_0 [Futaba]]
[s][f 5 14]Bah, da igual.[n][w][e]

[msg MSG_017_0_0 [Futaba]]
[s][f 5 14]Ahora tienes que esconderte.[n]Ya te contar姻.[n][w][e]

