[msg MSG_000_0_0 [Mishima]]
[s][f 5 14]斡Qu姻 pasada! 斡Nunca me habr胤a[n]imaginado que ir胤ais a por Shido![n][w][e]

[msg MSG_001_0_0 [Mishima]]
[s][f 5 14]No importa qui姻n sea el objetivo[n]de los Ladrones Fantasma. 斡Siempre[n]tienen la justicia de su lado![n][w][e]

[msg MSG_002_0_0 [Mishima]]
[s][f 5 14]Me alegro de haber mantenido[n]la Fansite a flote a pesar[n]de tener tantas cr胤ticas.[n][w][e]

[msg MSG_003_0_0 [Mishima]]
[s][f 5 14]Creo que cambiar姻 la[n]pregunta de la encuesta para[n]conmemorar vuestro regreso.[n][w][e]

[msg MSG_004_0_0 [Mishima]]
[s][f 5 14]斡Y esta vez dir姻 que s胤![n][w][e]

[msg MSG_005_0_0 [Mishima]]
[s][f 5 14][f 5 15]斡Creo en vosotros! 斡Sed fuertes![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 5 65535 0][f 4 10 65535 0 0][vp 8 2 1 1178 65535 0]Este t胤o no cambia.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 65535 0][vp 1 0 0 0 0 0][f 4 10 65535 0 0]Bueno, parece que est茨[n]deseando ver c吋mo va.[n]Ahora solo nos queda esperar.[n][f 1 3 65535][w][e]

