[msg MSG_000_0_0 [Ryuji]]
[s][f 5 14]夷Acciones legales? No tiene gracia.[n][w][e]

[sel SEL_002_0_0 top]
[s][f 5 14]Pues f茨cil no va a ser.[e]
[s]夷Por qu姻?[e]

[msg MSG_003_0_0 [Ryuji]]
[s][f 5 14]Si la polic胤a se entera,[n]llamar茨 al instituto.[n][w][e]

[msg MSG_004_0_0 [Ryuji]]
[s][f 5 14]Esta vez nos expulsan.[n][w][e]

[msg MSG_005_0_0 [Ann]]
[s][f 5 14]El instituto es lo de menos...[n]Nos van a detener.[n]Por allanamiento, difamaciones...[n][w][e]

[msg MSG_006_0_0 [Ryuji]]
[s][f 5 14]Pues esta vez va a ser[n]que no podemos cagarla.[n][w][e]

[msg MSG_007_0_0 [Ann]]
[s][f 5 14][f 5 15]Pues s胤. Todo cuenta a partir[n]de ahora. 斡Venga![n][w][e]

[msg MSG_CHAT_MORUEND_00 [Morgana]]
[s][bup 0 3 2 65535 0][f 4 10 65535 0 0][vp 1 0 0 1 0 0]Hay que hacer que despierte[n]antes de que presente cargos.[n]Centraos en eso.[n][f 1 3 65535][f 1 3 65535][w][e]

