[msg MSG_008_0_0 [Al胤 Bab茨]]
[s][f 5 14]夷Qu姻 hac姻is aqu胤?[n][w][e]

[msg MSG_009_0_0 [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 0 0 10 65535 0]夷Por qu姻 reacciona solo[n]a ese nombre?[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Al胤 Bab茨]]
[s][f 5 14]Vale.[n][w][e]

[msg MSG_017_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 19 65535 0]De acuerdo...[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 20 65535 0]Nuestro l胤der, el tipo que vive[n]en el 茨tico del Leblanc,[n]quiere hablar contigo.[n][f 1 3 65535][w][e]

[msg MSG_018_0_0 [Makoto]]
[s][bup 0 6 1 1 0][f 4 10 65535 0 0][vp 8 0 0 21 65535 0]Contamos contigo, [f 4 2].[n]A ver si t雨 le sacas[n]una palabra clave.[n][f 1 3 65535][w][e]

[msg MSG_018_5_0 [Al胤 Bab茨]]
[s][f 5 14]夷Qu姻 quer姻is que os diga?[n][w][e]

[sel SEL_019_0_0 top]
[s][f 5 14]夷Qu姻 significa esta casa para ti?[e]
[s]夷Qu姻 aspecto tiene esta casa?[e]
[s]夷Qu姻 tal se vive en esta casa?[e]

[sel SEL_019_1_0 top]
[s][f 5 14]夷Qu姻 aspecto tiene esta casa?[e]
[s]夷Qu姻 tal se vive en esta casa?[e]

[sel SEL_019_2_0 top]
[s][f 5 14]夷Qu姻 significa esta casa para ti?[e]
[s]夷Qu姻 tal se vive en esta casa?[e]

[sel SEL_019_3_0 top]
[s][f 5 14]夷C吋mo te sientes viviendo aqu胤?[e]

[msg MSG_020_0_0 [Al胤 Bab茨]]
[s][f 5 14]Una casa es una casa.[n][w][e]

[msg MSG_021_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 22 65535 0]Creo que deber胤as[n]preguntarle otra cosa...[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Al胤 Bab茨]]
[s][f 5 14]夷...?[n][w][e]

[msg MSG_023_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 23 65535 0]Creo que deber胤as[n]preguntarle otra cosa...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Al胤 Bab茨]]
[s][f 5 14]Es doloroso...[n][w][e]

[sel SEL_025_0_0 top]
[s][f 5 14]夷Por qu姻?[e]
[s]夷La odias?[e]
[s]夷Por qu姻 no sales?[e]

[sel SEL_025_1_0 top]
[s][f 5 14]夷La odias?[e]
[s]夷Por qu姻 no sales?[e]

[sel SEL_025_2_0 top]
[s][f 5 14]夷Por qu姻?[e]
[s]夷Por qu姻 no sales?[e]

[sel SEL_025_3_0 top]
[s][f 5 14]夷Por qu姻 no sales?[e]

[msg MSG_026_0_0 [Al胤 Bab茨]]
[s][f 5 14]No lo s姻.[n][w][e]

[msg MSG_027_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 24 65535 0]Creo que deber胤as[n]preguntarle otra cosa...[n][f 1 3 65535][w][e]

[msg MSG_028_0_0 [Al胤 Bab茨]]
[s][f 5 14]No.[n][w][e]

[msg MSG_029_0_0 [Makoto]]
[s][bup 0 6 0 1 0][f 4 10 65535 0 0][vp 8 0 0 25 65535 0]Creo que deber胤as[n]preguntarle otra cosa...[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Al胤 Bab茨]]
[s][f 5 14]No puedo abandonar este lugar.[n][w][e]
[s][f 5 14]Morir姻 aqu胤.[n][w][e]

[msg MSG_031_0_0 [Ann]]
[s][bup 0 4 4 1 0][f 4 10 65535 0 0][vp 8 0 0 26 65535 0]夷Qu姻...? 夷Morir...?[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Al胤 Bab茨]]
[s][f 5 14]夷Esto va a seguir as胤?[n][w][e]

[sel SEL_033_0_0 top]
[s][f 5 14]夷Morir?[e]
[s]Deber胤as salir.[e]
[s]夷Por qu姻 piensas eso?[e]

[msg MSG_034_0_0 [Al胤 Bab茨]]
[s][f 5 14]Eso es. Morir姻 aqu胤, sin duda.[n][w][e]

[msg MSG_035_0_0 [Al胤 Bab茨]]
[s][f 5 14]Eso es imposible.[n][w][e]

[msg MSG_036_0_0 [Al胤 Bab茨]]
[s][f 5 14]夷Por qu姻?[n][w][e]

[msg MSG_037_0_0 [Al胤 Bab茨]]
[s][f 5 14]Este lugar es mi tumba.[n][w][e]

[msg MSG_043_0_0 [Al胤 Bab茨]]
[s][f 5 14]夷Suficiente?[n][w][e]

[msg MSG_045_0_0 [Makoto]]
[s][bup 0 6 1 1 0][f 4 10 65535 0 0][vp 8 0 0 32 65535 0]S胤, de sobra.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 33 65535 0]No habr茨s olvidado tu promesa[n]de ayudarnos si hacemos[n]lo que nos pediste, 夷no?[n][f 1 3 65535][w][e]

[msg MSG_046_0_0 [Al胤 Bab茨]]
[s][f 5 14][f 5 15]No. Hicimos un trato.[n][w][e]

