[msg MSG_000_0_0 [Makoto]]
[s][f 5 14]Se acercan los ex茨menes.[n]夷Te van bien los estudios?[n][w][e]

[msg MSG_001_0_0 [Makoto]]
[s][f 5 14]Puedo darte una idea general[n]de c吋mo eran cuando[n]yo estaba en segundo.[n][w][e]

[msg MSG_002_0_0 [Makoto]]
[s][f 5 14]夷Qu姻 te parece?[n]夷Estudiamos juntos?[n][f 5 15][w][e]

[msg MSG_MORUGANA [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 1 0 0 0 0 0][f 4 25 1 65535 0 0]Bueno, 夷entonces qu姻?[n]夷Quieres estudiar con Makoto?[n][f 1 3 65535][w][e]

[sel SEL_001 top]
[s]Ir ya[e]
[s]Decidir luego[e]

[sel SEL_002 top]
[s][f 5 14]Estudiemos juntos.[e]

[msg MSG_REACTION [Makoto]]
[s][f 5 14]Muy bien. Ven a la biblioteca.[n][w][e]

[msg MSG_REACTION_02 [Makoto]]
[s][f 5 14]Muy bien. Vamos al restaurante.[n][w][e]

[msg MSG_REACTION_03 [Makoto]]
[s][f 5 14]Voy a machacarte,[n]as胤 que prep茨rate.[n][f 5 15][w][e]

