[msg MSG_025_0_0 [Ryuji]]
[s][f 5 14]Mishima no ha logrado nada.[n]夷Hab姻is conseguido algo vosotros?[n][w][e]

[msg MSG_026_0_0 [Makoto]]
[s][f 5 14]Le pregunt姻 a mi hermana,[n]pero parece que no sab胤a mucho[n]sobre ellos.[n][w][e]

[msg MSG_026_5_0 [Makoto]]
[s][f 5 14]Tampoco es que est姻[n]especializada en ciberdelitos.[n][w][e]

[msg MSG_027_0_0 [Ann]]
[s][f 5 14]He probado a investigarlos[n]yo tambi姻n, pero[n]no he encontrado nada.[n][w][e]

[msg MSG_027_5_0 [Ann]]
[s][f 5 14]No hay ninguna pista.[n][w][e]

[msg MSG_028_0_0 [Yusuke]]
[s][f 5 14][f 5 15]Nuestro rival es muy escurridizo.[n][w][e]

