[msg MSG_001]
[s]Decoraci吋n b茨sica para la Guarida [n]de los Ladrones.[n][e]

[msg MSG_002]
[s]Decoraci吋n tem茨tica del[n]Palacio de Kamoshida.[n][e]

[msg MSG_003]
[s]Decoraci吋n tem茨tica del[n]Palacio de Madarame.[n][e]

[msg MSG_004]
[s]Decoraci吋n tem茨tica del[n]Palacio de Kaneshiro.[n][e]

[msg MSG_005]
[s]Decoraci吋n tem茨tica del[n]Palacio de Futaba.[n][e]

[msg MSG_006]
[s]Decoraci吋n tem茨tica del[n]Palacio de Okumura.[n][e]

[msg MSG_007]
[s]Decoraci吋n tem茨tica del[n]Palacio de Niijima.[n][e]

[msg MSG_008]
[s]Decoraci吋n tem茨tica del[n]Palacio de Shido.[n][e]

[msg MSG_009]
[s]Decoraci吋n tem茨tica de la prisi吋n[n]de Acedia y del mundo de Qliphoth.[n][e]

[msg MSG_010]
[s]Decoraci吋n tem茨tica del[n]Palacio de Maruki.[n][e]

[msg MSG_011]
[s]Decoraci吋n tem茨tica de la[n]Habitaci吋n Terciopelo.[n][e]

[msg MSG_012]
[s]Decoraci吋n inspirada en Mementos.[n][e]

